### ISSUE TITLE
QT UI never appears

### ISSUE THREAD

**Issue by sheldonth** [bitcoin/bitcoin#10005]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

The UI never appears. It seems to get stuck at "Done loading"

<img width="481" alt="screen shot 2017-03-15 at 6 13 42 pm" src="https://cloud.githubusercontent.com/assets/733784/23973169/4441d62e-09ab-11e7-9670-1b7a817a2848.png">

The final entries in debug.log are
```
2017-03-15 22:12:34 UPnP Port Mapping successful.
2017-03-15 22:12:43 Loading addresses from DNS seeds (could take a while)
2017-03-15 22:12:44 202 addresses found from DNS seeds
2017-03-15 22:12:44 dnsseed thread exit
017-01-25 19:30:11' progress=0.933531 cache=12.3MiB(6668tx)
2017-03-15 22:15:08 GUI: Platform customization: "macosx"
2017-03-15 22:15:09 GUI: PaymentServer::LoadRootCAs: Loaded  169  root certificates
2017-03-15 22:16:46 UpdateTip: new best=000000000000000002979e885deeefde60442b7bd2b8676549bec4594b27eca2 height=449981 version=0x20000000 log2_work=85.875006 tx=190716632 date='2017-01-25 19:39:46' progress=0.933539 cache=19.6MiB(12337tx)
2017-03-15 22:16:46 connect() to 46.253.252.167:8333 failed after select(): Connection refused (61)
```

#### If so, please list the steps to reproduce below:
1. Start bitcoin-qt (on OS X 10.12.3) using a custom data directory

### Expected behaviour
The QT UI should appear.

### Actual behaviour
I get stuck with the splash screen and never see the QT UI.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
Official binary 0.14.0

### Machine specs:
- OS: Mac OS 10.12.3
- CPU: Core i7
- RAM: 8gig
- Disk size: 1tb
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by TheBlueMatt** [comment]
If this is reproduceable, can you try running with -debug? Either way, can you paste more of the debug.log? There isn't enough in the three lines you posted to figure much out.

**Comment by jonasschnelli** [comment]
I vaguely remember that I have also encountered this one time... but I could not reproduce it. Could be a race.
@sheldonth: do you have this behaviour every time you start bitcoin-qt? What QT version are you using? A pastebin of your config.log would indeed be helpful.

**Comment by laanwj** [comment]
I think it can (rarely) still happen that the start of the GUI is blocked on cs_main because it is verifying blocks (the problem discussed in #8117) that came in last session.
In that case it should continue to log "UpdateTip: new best=..." lines and come up at some point.
See https://github.com/bitcoin/bitcoin/pull/8392#issuecomment-236897026

**Comment by sheldonth** [comment]
Hi -- so I just let the "Done loading" screen sit there all night and it looks like the entire system behaved as it should have -- loading blocks and catching up the chain. Here is a gist of the entire debug.log @TheBlueMatt https://gist.github.com/sheldonth/2ba09ba625375bee7f2f64957ca4fe10

I have yet to be able to get the QT UI to appear. I am using 0.14 -- one factor to note is that my bitcoin data directory is on an external drive which also had Time Machine backups start on it (automatically) while bitcoin was trying to open. I realized this morning that I was simultaneously Time Machine'ing a backup onto the same drive that Bitcoin was working off of. I wonder if that could've casued the locks referred to above. Since I can currently reproduce the problem I will try starting bitcoin with the -debug flag and sending any other logs over.

**Comment by sheldonth** [comment]
Update: Now that I updated to the latest chaintip whilst stuck at the "Done Loading" screen overnight I tried again starting 0.14 and I was able to get the GUI up -- should note that it's very UI-lock intenseive (e.g. seeing the spinning pinwheel on OSX very aggressively). But it looks like the lack-of-UI problem has somewhat resolved itself.

**Comment by TheBlueMatt** [comment]
Yea, Bitcoin Core (still) doesn't do well with super slow disks, though we should likely fix the slow-to-open-GUI issue.

**Comment by jonasschnelli** [comment]
Looks after more users affected by this problem: http://bitcoin.stackexchange.com/questions/50117/bitcoint-core-gui-will-not-display-once-index-is-loaded

**Comment by laanwj** [comment]
So it seems the point where it blocks on cs_main has been moved from during the splash screen (albeit with the wrong message) to the handover between the splash screen and the GUI. Somewhat awkward.

Ideally we should never block the GUI on anything that requires cs_main. That's non-trivial, though, as e.g. getting the wallet transaction list from the core requires that lock, and showing the window but not showing transactions is not nice either...

Also we should find a solution to the validation thread starving other threads of any access to cs_main. It drops the lock but not for long enough for anyone else to have a chance to grab it (?). "pthread_yield" didn't seem to solve it either from tests in #8117. Maybe adding a delay is the only option, but that's quite ugly as it would slow down the validation progress... :/

**Comment by sheldonth** [comment]
@jonasschnelli Been doing some testing on the 0.14.2 binaries and I'm certain that your work in !10231 has solved this problem. I'd also like to deeply thank you for that effort, the UI lock issue was a huge usability hangup for me lately.

**Comment by Leviathn** [comment]
This is closeable.
