### ISSUE TITLE
Unable to use bitcoin-cli on Windows if bitcoin-qt connects through tor

### ISSUE THREAD

**Issue by AKJ** [bitcoin/bitcoin#10019]
### Describe the issue
When setting up the gui to connect through tor, bitcoin-cli commands fail to work if accessed through the Windows command prompt with a message about failing to get rpc credentials. This problem does not occur for me once I revert those settings.

#### If so, please list the steps to reproduce below:
1. Start bitcoin-qt on Windows 7, using a custom data directory.
2. In settings > network, set proxy and tor checkboxes and connect through 127.0.0.1:9150 for both.
3. While tor is running and there are active connections to the bitcoin network, attempt any bitcoin-cli command from the command prompt, for example bitcoin-cli help

### Expected behaviour
Normally this would result in the help text for bitcoin-cli being displayed.

### Actual behaviour
Instead, I receive this text:
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (C:\Users\user\AppData\Roaming\Bitcoin\bitcoin.conf)

Setting an rpcpassword value in bitcoin.conf yields:
error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)

Server is set to 1. 

### What version of bitcoin-core are you using?
0.14.0 official binary

### Any extra information that might be useful in the debugging process.
If needed I can provide a debug.log; I'm not sure if that would be valuable in this instance. Happy to provide any other information..

**Comment by sipa** [comment]
Are you running with -server ?

**Comment by AKJ** [comment]
I have server=1 set in bitcoin.conf

Additionally, changing from connecting through tor to connecting 
regularly allows me to run bitcoin-cli commands normally.

**Comment by laanwj** [comment]
This is strange. In principle, using tor or not should not have any influence on reachability of the RPC port - those subsystems are separate.

So I think your problem is unrelated to Tor.

Have you perhaps changed the data directory in the GUI? If you did, you need to specify that to `bitcoin-cli` using `-datadir=<newdatadir>`. The console tools will not pick up GUI settings.

**Comment by AKJ** [comment]
Okay, that makes sense in principle. I have tried a couple things with confusing results though. I apologize if this is teaching kindergarten, but can you help me understand what I might be doing wrong here?

Command: %path-to-bitcoin%\daemon\bitcoin-cli.exe -datadir=newdatadir
Result: error: too few parameters (need at least command)

Command: bitcoind.exe -datadir=newdatadir
Result: A .cookie file is created (good) but bitcoind seems to hang and I cannot execute any rpc commands (less good).

Again, apologies if this is easy stuff.

**Comment by MeshCollider** [comment]
@AKJ, bitcoin-cli has to be given a command to run, as a parameter, it isn't like bitcoin-qt which has a GUI or anything, its a command line tool (hence the 'cli'). E.g. `bitcoin-cli.exe getbalance`

**Comment by AKJ** [comment]
Well regardless, if this is an issue with the code (which I doubt now) it certainly isn't the one presented here. Closing.
