### ISSUE TITLE
`addwitnessaddress` should have a `rescan` option similar to `importprivkey`

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#10016]
Sorry if this has been addressed already. 

With Wallet-1: `getnewaddress` and `addwitnessaddress`. Then also `dumpprivkey`.

After moving files around and restarting with Wallet-2: `importprivkey` and also `addwitnessaddress` which gives me the same P2SH-enclosed witness address as Wallet-1, I need to rescan the blockchain for the wallet to update.

Is there a way to wallet-rescan from bitcoin-cli? or some behavior similar to `importprivkey rescan=true`?

**Comment by laanwj** [comment]
> After moving files around and restarting with Wallet-2: importprivkey and also addwitnessaddress which gives me the same P2SH-enclosed witness address as Wallet-1, I need to rescan the blockchain for the wallet to update.

`importmulti`, which is a superset of the various import functions, supports this by providing a key birthday.

> Is there a way to wallet-rescan from bitcoin-cli? or some behavior similar to importprivkey rescan=true?

No, the only way to do a full rescan is by restarting `bitcoind` with `-rescan`.

**Comment by promag** [comment]
:+1: on `importmulti` with timestamp.

@pinheadmz there is a patch for RPC rescan, see #7061.

**Comment by pinheadmz** [comment]
Will this work for a P2WPKH nested in BIP16 P2SH? If there is an old transaction on the blockchain with a P2SH output and the redeem script is a witness PKH that I generated with `addwitnessaddress`, how should I import and scan for that tx?  Would I use `importmulti` with the `redeemscript` option ? And if so, how do I get the actual redeem script for the P2SH address generated by `addwitnessaddress`?

**Comment by Sjors** [comment]
`addwitnessaddress` is now deprecated.
