### ISSUE TITLE
Overview of slow unit tests

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#10026]
At last IRC meeting we've discussed trying to speed up the unit tests, as they've become much too slow.
For this purpose I've run `test_bitcoin --log_level=test_suite` and picked out the slowest from the list.

The top 20 is (updated 2018-04-14 by @lucash-dev):

| Test                                     | Time (μs) |
| ---------------------------------------- | ---------:|
| `test_big_witness_transaction`           |  39133014 |
| `test_CheckQueue_Correct_Random`         |  14808019 |
| `knapsack_solver_test`                   |   9304171 |
| `checkinputs_test`                       |   6370348 |
| `CreateNewBlock_validity`                |   6105558 |
| `test_CheckQueue_Memory`                 |   4230330 |
| `versionbits_test`                       |   3835090 |
| `coins_cache_simulation_test`            |   3205869 |
| `updatecoins_simulation_test`            |   2499840 |
| `merkle_test`                            |   2391688 |
| `rescan`                                 |   1900315 |
| `SelectCoins_test`                       |   1731901 |
| `passphrase`                             |   1730167 |
| `ListCoins`                              |   1689793 |
| `test_CheckQueue_Catches_Failure`        |   1563869 |
| `test_CheckQueue_UniqueCheck`            |   1521864 |
| `PrevectorTestInt`                       |   1409636 |
| `test_CheckQueue_Correct_Max`            |   1401687 |
| `bnb_search_test`                        |   1147974 |
| `cuckoocache_generations`                |    978637 |

I think (open for discussion, of course) it is unreasonable for a unit test case to take more than ~1s (mind you, we have 242 of them, so each test is supposed to be quick) so we should take a look at each of these up to `merkle_test`.

It could be as simple in some cases as getting rid of (reasonably heavy) `BOOST_*` tests in inner loops, moving the checks up to a higher level.

Edit: I added the script to create this table to maintainer-tools: https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/unittest-statistics.py

**Comment by paveljanik** [comment]
The first one is 
```C++
/** Test that random numbers of checks are correct
 */
BOOST_AUTO_TEST_CASE(test_CheckQueue_Correct_Random)
{
    std::vector<size_t> range;
    range.reserve(100000/1000);
    for (size_t i = 2; i < 100000; i += std::max((size_t)1, (size_t)GetRand(std::min((size_t)1000, ((size_t)100000) - i))))
        range.push_back(i);
    Correct_Queue_range(range);
}
```

By simply removing `GetRand` call, the time is reduced from 33s to 15s here. Ie. the test spends ~half of the time in generating random numbers.

**Comment by paveljanik** [comment]
`test_big_witness_transaction` is signing 4500 inputs and it takes time.

**Comment by NicolasDorier** [comment]
`test_big_witness_transaction` was a test I wrote for checking if the CachedHashes of segwit was thread safe. What takes time is the signing of inputs. I think a better idea is to hard code the transaction. But I think it would be kind of big.

**Comment by JeremyRubin** [comment]
Sorry for writing so many of the slow tests!

Getting rid of GetRand from the CheckQueue tests is 100% fine; and should speed things up ( @kallewoof brought that up in review, but I didn't think it would be a huge time sink).

The cuckoocache_generations test is parametrized by:

```cpp
    const uint32_t BLOCK_SIZE = 10000;
    // We expect window size 60 to perform reasonably given that each epoch
    // stores 45% of the cache size (~472k).
    const uint32_t WINDOW_SIZE = 60;
    const uint32_t POP_AMOUNT = (BLOCK_SIZE / WINDOW_SIZE) / 2;
    const double load = 10;
    const size_t megabytes = 32;
    const size_t bytes = megabytes * (1 << 20);
    const uint32_t n_insert = static_cast<uint32_t>(load * (bytes / sizeof(uint256)));
```

picking smaller constants should be fine (although increases the potential variance, e.g., likelihood of deterministic failure). The rest of the cuckoocache_tests are also parametric (e.g., just a size in MB and a hit rate lower bound) so can be easily adjusted. I initially picked a size to match the default parameter, but we could scale down to, say 4mb or 2mb.

**Comment by NicolasDorier** [comment]
would writing my transaction hard coded be a problem ? I can do it but unsure if it is the right way.

**Comment by laanwj** [comment]
@NicolasDorier just how large would that data be? Very large (multi-MB) files of test data likely shouldn't be part of the repository.

**Comment by NicolasDorier** [comment]
@laanwj around 1 MB.

**Comment by JeremyRubin** [comment]
I would also note that checkqueue tests should improve a lot under https://github.com/bitcoin/bitcoin/pull/9938, I need to clean up that PR a bit though in accordance to Matt's feedback.

**Comment by laanwj** [comment]
Updated for #10128

**Comment by VermillionAzure** [comment]
Do you guys think we could get an update on this issue? I think that the top unit `test_CheckQueue_Correct_Random` is ultimately using a `FastRandomContext` which seems to be doing a lot of extra sampling for the random values -- the procedure retries every time it fails to generate a bit sequence in a certain bit range. Would there be a more efficient way to pre-set the range, customize the random number generator to generate uniformly-distributed values in this bit range so that no retries are not necessary. Or, could the slowdown be happening in the verification phase?

**Comment by MarcoFalke** [comment]
Marking "up for grabs" to see what unit tests are still slow and master and figure out how to speed them up.

https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/unittest-statistics.py might come in hnady.

**Comment by jamesob** [comment]
Should we add a "good first issue" label to this?

**Comment by lucash-dev** [comment]
Hi, I would like to work on this as my first issue.

**Comment by MarcoFalke** [comment]
Just go ahead. No need to ask for permission :)

**Comment by laanwj** [comment]
@lucash-dev Thanks! Moved your table into the OP.

**Comment by lucash-dev** [comment]
The https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/unittest-statistics.py script was mixing up test suite and test case statistics (presumably due to some change in how `test_bitcoin`output is generated). 

Created an [issue](https://github.com/bitcoin-core/bitcoin-maintainer-tools/issues/17) and a [PR](https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/18) in the maintainer tools repo.

**Comment by lucash-dev** [comment]
`test_big_witness_transaction` is spending most of time converting `CMutableTransaction` to `CTransaction`, which involves recalculating hashes. That's because each call to `SignSignature` does the conversion again for the whole transaction.

This means the time complexity for providing witnesses for the 4500 inputs has a O(n2) component.

Changing the test to use lower level functions `ProduceSignature` and `UpdateTransaction`, and reusing the same `CTransaction` in all iterations, reduces run time in about 70%.

Created a [WIP PR](https://github.com/bitcoin/bitcoin/pull/13050) (will add improvements to other tests to this PR).

I'm just wondering if that is not rather a bug in `SignSignature`. Should it create a new `CTransaction` every time it's called?

**Comment by lucash-dev** [comment]
Actually the problem lies deeper, in `MutableTransactionSignatureCreator`. It's constructor just creates a new `CTransaction` out of the mutable one. This doesn't seem right.
Changing it might require a bit of refactoring though. I'll try and see if I can come up with a solution.

**Comment by lucash-dev** [comment]
@JeremyRubin Is there a particular reason `test_CheckQueue_Correct_Random` needs to check so many ranges? Would 10,000 instead of 100,000 represent too low a probability of catching errors?
This test case is still one of the most time consuming, and maybe you could better analyze the cost-benefit trade-off.

**Comment by lucash-dev** [comment]
I think [#13050](https://github.com/bitcoin/bitcoin/pull/13050), which addresses the top 5 test cases, is in good shape for a review and possible merge.

**Comment by MarcoFalke** [comment]
I think this has been fixed? Anything left to do here?

**Comment by adamjonas** [comment]
Latest run on my machine still found a bunch of tests over a second:

| Test                                                    | Time (μs) |
| ------------------------------------------------------- | ---------:|
| `test_big_witness_transaction`                          |   3453172 |
| `CreateNewBlock_validity`                               |   2167830 |
| `knapsack_solver_test`                                  |   2074167 |
| `test_CheckQueue_Correct_Random`                        |   1675857 |
| `updatecoins_simulation_test`                           |   1314895 |
| `checkinputs_test`                                      |   1229128 |
| `SelectCoins_test`                                      |   1206660 |
| `coins_cache_simulation_test`                           |   1134890 |
| `versionbits_test`                                      |   1001234 |

**Comment by adamjonas** [comment]
Though in the middle of the list above, my old laptop (2013 MacBook Pro) runs into a bunch of trouble with `test_CheckQueue_Correct_Random`. It consistently comes above 30 seconds. Here are the others that are over a second:

| Test                                                    | Time (μs) |
| ------------------------------------------------------- | ---------:|
| `test_CheckQueue_Correct_Random`                        |  35218784 |
| `test_big_witness_transaction`                          |   6219762 |
| `CreateNewBlock_validity`                               |   3941990 |
| `knapsack_solver_test`                                  |   3168931 |
| `test_CheckQueue_Memory`                                |   2229287 |
| `updatecoins_simulation_test`                           |   2214178 |
| `checkinputs_test`                                      |   1905050 |
| `coins_cache_simulation_test`                           |   1775631 |
| `versionbits_test`                                      |   1510278 |

**Comment by MarcoFalke** [comment]
I was running the tests on arm64 bionic and still got a bunch of tests that take longer than one second. (Including the `test_CheckQueue_Correct_Random` test case)


| Test                                                    | Time (μs) |
| ------------------------------------------------------- | ---------:|
| `test_big_witness_transaction`                          |  29437948 |
| `test_CheckQueue_Correct_Random`                        |  22050372 |
| `knapsack_solver_test`                                  |  14629919 |
| `CreateNewBlock_validity`                               |  12781948 |
| `updatecoins_simulation_test`                           |  11699386 |
| `checkinputs_test`                                      |   8679608 |
| `SelectCoins_test`                                      |   8266631 |
| `coins_cache_simulation_test`                           |   8176292 |
| `util_ArgsMerge`                                        |   6467467 |
| `versionbits_test`                                      |   6014103 |
| `processnewblock_signals_ordering`                      |   5476931 |
| `psbt_updater_test`                                     |   3793910 |
| `merkle_test`                                           |   3661272 |
| `mempool_locks_reorg`                                   |   3524035 |
| `passphrase`                                            |   3458565 |
| `cuckoocache_generations`                               |   3174970 |
| `compress_amounts`                                      |   2708759 |
| `skiplist_test`                                         |   2623142 |
| `ListCoins`                                             |   2607134 |
| `test_CheckQueue_Memory`                                |   2349730 |
| `sighash_test`                                          |   1611576 |
| `BlockPolicyEstimates`                                  |   1611403 |
| `getlocator_test`                                       |   1591312 |
| `addrman_getaddr`                                       |   1524868 |
| `test_CheckQueue_Catches_Failure`                       |   1503379 |
| `script_build`                                          |   1313951 |
| `script_json_test`                                      |   1294559 |
| `script_standard_push`                                  |   1265544 |
| `cuckoocache_hit_rate_ok`                               |   1190260 |
| `PrevectorTestInt`                                      |   1181760 |
| `varints`                                               |    987794 |

**Comment by JeremyRubin** [comment]
*ducks*

I can take a look at improving it. Generally the checkqueue tests are aggressive and slow for two reasons:

1) They were designed to be slow on the existing checkqueue, and fast on the lock free one
2) They want to test the parallelism-safety of the checkqueue, so absent a parallelism permutation testing framework (like loom for rust) we're stuck with something that is bigger (& probabilistic)

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
