### ISSUE TITLE
Do you guys need assistance updating that block size?

### ISSUE THREAD

**Issue by dzimbeck** [bitcoin/bitcoin#10028]
If you like I can happily push the blocksize update to github and you can merge it.

It's become apparent to me that you guys don't seem to know how to do that. If you all are truly against centralization, then you won't centralize this github. Do the right thing and take action in **any** direction. Because inaction is insecure.

**Comment by sipa** [comment]
Bitcoin Core's maintainers do not, and do not want to, decide what the network's rules are. If there is widespread agreement about a change, it will be merged. But if you want to rally for such a change, the correct place is in public fora that involve the whole community, not on the issue tracker of just one software project.

As far as me individually and several others are concerned, we have gone through a large scale effort to bring a capacity increase in a safe and backward-compatible way, known as SegWit. At this point it is out of our hands and up to the community to adopt it. So please don't accuse people of inaction.

**Comment by dzimbeck** [comment]
Well when an issue effects the security of the chain, historically maintainers have had to fork. Bitcoin has certainly been hard forked in the past . Segwit is not a viable solution because settlement networks such as lightning lead to centralization because they either A: force users to deposit with extremely rich holders of coins so more settlements can be made without owing funds or B: funds are connecting two multisig accounts with two asymmetrical channels. The problem with the 2nd scenario is that it runs serious security threats because one you use hash time locked contracts to link unrelated multisignature with funds that are not held by the intermediate party, then the one routing the payment can simply collude and double spend (because they can secretly pose as transferor and channel via collusion). A channel which is highly centralized can be hacked and the hacker may default on any payments owed. This collusion and hacking can only be prevented by forcing users to deposit their 2 of 2 with very rich holders or constantly clear payments when they are owed funds not to mention problems with getting disconnected and not being able to clear payments before expiry of the time lock. All of these are mess and seriously risky security threats with the only solution being a centralized one aka trusting the ultra wealthy. So no, Segwit doesn't solve the issue.

The "community" will never be in agreement because humans never reach consensus on anything especially when there are more than 2 options. Furthermore they are not gifted coders such as us devs and aren't adept at making decisions. The silent majority wants and needs github to make security fixes. Namely bip 100 which is a dynamic solution to block size instead of set and relying on votes or as you put it "the community". The miners are the ones investing hard ware and electricity and this solution is the best of both worlds. You cannot ignore the greatest current security threat to Bitcoin and eventually you must allow and embrace change. Otherwise all of you are guilty of inaction. Please make the right decision you all know in your heart to be true and do not centralize this github. Not all contributors to Bitcoin are in agreement. Don't brush devs off by closing issues that are in fact bugs as small block size is a bug not a feature. Please reconsider and reopen this issue.
