### ISSUE TITLE
Hello I lost access to Bitcoin organization

### ISSUE THREAD

**Issue by jonaschnelli** [bitcoin/bitcoin#10032]
Please add me back @gmaxwell @sipa @petertodd

**Comment by jonaschnelli** [comment]
@luke-jr @midnightmagic @NicolasDorier

**Comment by lichtamberg** [comment]
FAKE / SCAM! TAKE CARE!

**Comment by tulip0** [comment]
<img width="414" alt="no" src="https://cloud.githubusercontent.com/assets/15009664/24077317/6c8628fc-0c9d-11e7-88ff-0092e85eb2fd.png">

**Comment by TheBlueMatt** [comment]
Lol, as if that was going to work.
