### ISSUE TITLE
Question about BIP 16

### ISSUE THREAD

**Issue by yxliang01** [bitcoin/bitcoin#10031]
```
[20-byte-hash-value] shall be the push-20-bytes-onto-the-stack opcode (0x14) followed by exactly 20 bytes.
```
from https://github.com/bitcoin/bips/blob/master/bip-0016.mediawiki

However, in the example on the same page
```
scriptSig: [signature] {[pubkey] OP_CHECKSIG}
scriptPubKey: OP_HASH160 [20-byte-hash of {[pubkey] OP_CHECKSIG} ] OP_EQUAL
```
It didn't include the OP code `0x14`.

Therefore, what should a P2SH script look like?

Besides, when the scriptSig contains {serialized script} and we hash it using HASH_160, will it really be executed?

Thanks

**Comment by TheBlueMatt** [comment]
Generally nomenclature of pushes does not include the push byte, it is implied. This kind of question, however, is better suited for the Bitcoin stackexchange.

**Comment by laanwj** [comment]
This is not the place for questions about BIPs, this is an issue tracker. As said, use the bitcoin stack exchange.
