### ISSUE TITLE
Pass os, gui to the Alert system

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#1005]
The client id in 'version' messages are specifically vague so potential attackers can't easily tell exactly what flavor of Bitcoin you're running.

But we can, and should, pass full information to the Alert system, so we can send alerts targeted to just Windows Bitcoin-Qt users.

I think just platform (Linux/OSX/Windows) and Qt-or-not.

**Comment by laanwj** [comment]
The current alert system is pretty much deprecated (see discussions in  #6260, #5160), certainly for reporting client software specific issues, so there is no point in doing this anymore
