### ISSUE TITLE
Support not reusing addresses

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#10065]
An advanced wallet feature should be the ability to disable all address reuse. The attack this is designed to stop is if I know that the address 1BPmZt3kjnFffANNs6MCBBBKRYwRGGrXQZ is part of Alice's wallet, it shouldn't be possible to continually pepper it with dust and learn more about her as her wallet automatically keeps spend-linking it with her other outgoing transactions.

I'm not exactly sure how the implementation of this would look, but I think a sensible route would be to make the `lockunspent` shit persistent (it's already annoying that it's not), and if the "-ignore-funds-from-reused-addresses" feature is enable, the wallet would automatically lock that output upon it being received. 

(It's probably bad form: But I'm offering a 1 BTC bounty to anyone who can get such a feature merged in within 6 months of this posting).

**Comment by luke-jr** [comment]
Which of these interest you?

1) optimisation: don't check for used addresses in new blocks
2) best practice: don't show more than one payment made to each address
2b) or at least, don't show payments made after coins sent to that address are spent
3) privacy: don't spend coins received by the same address in different transactions (requires 2)

**Comment by RHavar** [comment]
Option 3, privacy.

I don't think 1 is that useful, and could be harmful if someone does send you money to an old address and you need to retrieve it.

What I would like to do, is be able to have a bitcoin wallet that is non clusterable. I have talked to other bitcoin service operators, and they are forced to periodically create new bitcoin wallets for privacy reasons.

Let's say I know you sent money to  17p47toGLR5zBZw2pNzRDFh9yWKX2qxyaJ, and I don't know who owns that address but I'm trying to figure it out. A pretty easy way now is to spray it with a bunch of dust. Then if who ever owns 17p47toGLR5zBZw2pNzRDFh9yWKX2qxyaJ is running a wallet like bitcoin core, it'll automatically spend link all that dust. Eventually I should be able to figure out who owns that address, especially if it's a service. And thus where you were sending your money.

That's a pretty big privacy hole that should be disable-able.

**Comment by kallewoof** [comment]
@RHavar I believe #12257 and #13756 together address this problem. Please confirm.

**Comment by RHavar** [comment]
Looks like it. Fantastic work! Keep it up 👍

**Comment by luke-jr** [comment]
I don't see how. I can still send you coins to the same address twice if I'm arbitrarily quick enough...

**Comment by RHavar** [comment]
Yeah, but then both those outputs will be spent with the same transaction -- so it's not an issue.

**Comment by luke-jr** [comment]
It's still address reuse, and in some cases retains the problems of such reuse.

**Comment by kallewoof** [comment]
What @luke-jr is talking about is orthogonal to the issue raised here, so I believe closing it was the correct decision. The issue @luke-jr is talking about is in #3266 and there is a PR open in #15987.
