### ISSUE TITLE
Update WM_CLASS window property

### ISSUE THREAD

**Issue by fturco** [bitcoin/bitcoin#10064]
I'm running Bitcoin Core 0.13.2.0 on a Gentoo Linux machine. GNOME is my desktop environment.

When the mouse cursor is over the application icon "Bitcoin-Qt" is displayed instead of "Bitcoin Core":

![bitcoin-core](https://cloud.githubusercontent.com/assets/5459866/24255202/1485f010-0fe5-11e7-8556-bd397763f817.png)

`xprop` returns the following informations:

    $ xprop| grep Bitcoin-Qt
    WM_CLASS(STRING) = "bitcoin-qt", "Bitcoin-Qt"

In my opinion it should be replaced with the new official name, which is "Bitcoin Core".

**Comment by laanwj** [comment]
Any idea how to set that w/ Qt, without changing the application name that is also used to locate settings?

**Comment by fturco** [comment]
No, sorry, I don't know anything about Qt programming...

**Comment by laanwj** [comment]
This seems to be where the functionality for WM_CLASS was introduced: https://codereview.qt-project.org/#/c/61009/7/src/plugins/platforms/xcb/qxcbintegration.cpp . It uses the application name, and if none, falls back to argv[0] (executable name). `bitcoin-qt` happens to be both. So there's nothing we can do here to resolve this specific issue without having effect on a ton of other things.

**Comment by jonasschnelli** [comment]
There is a constant `#define QAPP_APP_NAME_DEFAULT "Bitcoin-Qt"` in `guiconstants.h` that could be changed. This should work IMO.
I'm setting up a Ubuntu Gnome VM to test this.

**Comment by laanwj** [comment]
AFAIK, that will change where the GUI settings are stored in the registry/`.config`, so that would need to be carefully tested.

**Comment by jonasschnelli** [comment]
`setApplicationName()` works for correcting the `WM_CLASS`, but @laanwj is right,.. it will also affects the QSettings path/filename.

I see three possible solutions:
1. We don't change it (keep Bitcoin-Qt)
2. We change it to "Bitcoin Core" and move the old `QSettings` file (Bitcoin-Qt.conf) if it has never been moved and the file exists
3. We set "Bitcoin Core" over `setApplicationName()` and tell `QSettings` to use `Bitcoin-Qt.conf` as settings file (would "require" to abstract the QSettings interface first, code-change tend to be large).

IMO solution 2 is preferable.

**Comment by laanwj** [comment]
The problem is that Qt (AFAIK) provides no abstraction for renaming the application, so this has to be done with custom code for Windows, Linux and possibly MacOSX.

I'd prefer to just keep this minor issue and leave it as is for now. There are tons of more pressing concerns.

**Comment by jonasschnelli** [comment]
> I'd prefer to just keep this minor issue and leave it as is for now. There are tons of more pressing concerns.

Indeed.
