### ISSUE TITLE
Can not find blkindex.dat file

### ISSUE THREAD

**Issue by Demontf** [bitcoin/bitcoin#10070]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
I can not find blkindex.dat on my computer, but everything is ok. Anyone else can tell where I can find it, Thanks a lot.
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
The full node is running well
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
bitcoin-0.14.0-win64
### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by laanwj** [comment]
What are you trying to do? What error message do you get? Can you paste debug.log contents?

That issue template isn't there for nothing!

**Comment by Demontf** [comment]
@laanwj  Everything is Ok. I want to analysis some data from the blockchain, So I need the block index file. But I can not find the blkindex.dat.

**Comment by laanwj** [comment]
The place for a question like that would be the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

In any case the block files (blkXXXX.dat) are in your data directory. Under Linux this is `~/.bitcoin` by default, on other OSes it varies. To create a single, in-order file there is the script in `contrib/linearize`.

**Comment by luke-jr** [comment]
Note that blkindex.dat hasn't been used since v0.8.0.

**Comment by laanwj** [comment]
Yes, because having all blocks in a single file became unwieldy.
