### ISSUE TITLE
[rpc] Createrawtransaction doc does not match named args

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#10079]
According to the help text of createrawtransaction, the following args are accepted:
```
Arguments:
1. "inputs"                (string, required) A json array of json objects
2. "outputs"               (string, required) a json object with outputs
3. locktime                  (numeric, optional, default=0) Raw locktime. Non-0 value also locktime-activates inputs
```

however, this does not match the named args ( https://github.com/bitcoin/bitcoin/blob/8152d3fe57a991e9088d0b9d261d2b10936f45a9/src/rpc/client.cpp#L84 )

Imo, backporting a breaking change to 0.14.1 is reasonable. Though, I'd like to hear other opinions.

**Comment by jnewbery** [comment]
Named arguments were only introduced in 0.14.0, so I think it makes sense to change this and backport to 0.14.0.
