### ISSUE TITLE
Validation of Configuration Parameters

### ISSUE THREAD

**Issue by jlopp** [bitcoin/bitcoin#10091]
The current way that incorrectly named configuration parameters are handled (they are silently ignored) seems to be a poor user experience for novice node operators. Because config values are only fetched when needed at runtime, if a config parameter is passed in with a typo, it is assumed not to exist and the default value is used.

Wouldn't it be an improvement to add logic during node initialization that iterates through all user-supplied configuration parameters and checks that they are supported parameter names? It seems like this would require the creation of a single data structure that can act as a directory for all available parameters.

**Comment by jonasschnelli** [comment]
Yes. This would be a great improvement.
Ideally we create a structure that contains all available configuration options with help-information, rules how they depend/interact with other options.
A check for invalid options during startup would be good. The only downside might be that an older version with a newer configuration (or vice versa) could break the startup (in case we stop the startup process).

**Comment by laanwj** [comment]
Agreed. Duplicate of #1044, though.

> The only downside might be that an older version with a newer configuration (or vice versa) could break the startup (in case we stop the startup process).

Running an older version with a newer configuration is not supported. The other way around should usually work, but if we do remove or rename command line arguments it's better if the user is made aware of that. And some arguments could be explicitly ignored in some cases.

**Comment by jlopp** [comment]
Aha, I figured this had probably been discussed before but didn't find 1044 - I'll close this issue.
