### ISSUE TITLE
importprivkey RPC call locks the whole client while rescanning

### ISSUE THREAD

**Issue by davout** [bitcoin/bitcoin#1011]
When I import a private key, other JSON-RPC calls seem frozen and return a result only when the private key import JSON-RPC call has finished.

This makes the feature hardly usable when used in web app or other shared wallet contexts.

EDIT : Tested on latest master

**Comment by promag** [comment]
@weex #6570

**Comment by unsystemizer** [comment]
Just encountered this on 0.12.1. Following this link it turns out #7551 (merged into master 23 days ago) fixes this. 

@davout can you try with 0.13.1 (I think the fix went in before its release)? I can't upgrade my instance yet.
