### ISSUE TITLE
Feature request: Client whitelist for bandwidth limiting (maxuploadtarget)

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#10131]
### maxuploadtarget limit applies also for localhost clients

When using option `maxuploadtarget` and that limit is reached, even clients on localhost (where Bitcoin is running) do not get any more data from Bitcoin (Bitcoind says "historical block serving limit reached, disconnect peer").

E.g. this let to disfunction of Bitsquare, which could not connect to Bitcoin on localhost anymore. See
https://github.com/bitsquare/bitsquare/issues/758, where the workaround solution was to disable maxuploadtarget.

I would like to be able to whitelist localhost to be excluded from traffic limiting.

### Version
Bitcoin 0.14.0 amd64 binary for Linux

**Comment by laanwj** [comment]
Huh, I seriously thought this it was already the case that whitelisted peers could get around this limit.
In any case a more fine-grained whitelisting configuration where 'allow client to ignore serving limit' is an option would make sense to me.

ping @cfields (would make sense to take this into account in https://github.com/bitcoin/bitcoin/pull/10051#issuecomment-289114010)

**Comment by smartbrain** [comment]
Even​aa

**Comment by gmaxwell** [comment]
Whitelisted peers are exempted.  Localhost is not whitelisted (in part because that includes all Tor HS inbound.)

> if (send && connman.OutboundTargetReached(true) && ( ((pindexBestHeader != NULL) && (pindexBestHeader->GetBlockTime() - mi->second->GetBlockTime() > nOneWeek)) || inv.type == MSG_FILTERED_BLOCK) &&  ***** !pfrom->fWhitelisted   ***** )

**Comment by MarcoFalke** [comment]
With `NetPermissions` this should now be possible to implement. However,

The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
