### ISSUE TITLE
Sendrawtransaction failed ?

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#10147]
Hey,

I have forked your Source Code for an Altcoin, but if I wanna send a rawtransaction it says:

transaction rejected (code -22)

debug.log: "ERROR: CTxMemPool::accept() : nonstandard transaction: scriptsig-size"

The sender Address is a Multisign Address with 6 Signs required.

How can I fix this?

**Comment by jonasschnelli** [comment]
Please no altcoin issues.
Maybe follow the code part that leads to that error?
Closing.
