### ISSUE TITLE
Downloading sipa's seeds.txt yields a 404 error

### ISSUE THREAD

**Issue by JeremyRand** [bitcoin/bitcoin#10163]
### Describe the issue

Downloading `seeds.txt` from sipa's DNS seed yields a 404 error.

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:

1. Run the following command from a terminal: `curl -s http://bitcoin.sipa.be/seeds.txt`.
2. (My OS is Whonix 13; I have no reason to expect different results on other OS's but I haven't tried.)
3. (I tried replacing `http://` with `https://` since I was wondering if a Tor exit was interfering with the response; the results were unchanged.)

### Expected behaviour

A valid seeds.txt file should be displayed by curl.

### Actual behaviour

I get the following output:

```
$ curl -s http://bitcoin.sipa.be/seeds.txt
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

### Machine specs:

- OS: Whonix 13.  (That means all traffic is tunneled through Tor.)
- Other specs: believed to not be relevant.

**Comment by laanwj** [comment]
Would make sense to tag @sipa  (or maybe even mail him privately or ask on IRC). Not sure why this is a bitcoin core issue.

**Comment by jonasschnelli** [comment]
As far as I know is there no promise to provide the `seed.txt` as a 24/7 API. I guess this is not a Bitcoin-Core issue. The only timeframe where the seed.txt is used (can be used) is when updating the static internal ip list.
You can run your own seeder and create your own seed.txt.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I don't think I (or anyone else) alleged that the seeds.txt API (or
any other non-critical Bitcoin Core development API) needs to have
perfect uptime.  That said, for transparency and educational purposes,
it is beneficial for average bystanders to be able to learn how the
release process works.  This would mean either making an effort to
keep the seeds.txt API running where feasible (in which case it's
unclear to me why pointing out that it's down would be problematic on
GitHub), or mentioning somewhere in documentation how average
bystanders such as me can reproduce that API.  I looked at the docs
for the seeder software and was unable to find any mention of
seeds.txt -- I'd be happy to submit a PR to the Bitcoin Core docs
explaining how to set up your own seeds.txt API, if said process were
explained to me.

You're correct that I probably should have tagged @sipa , apologies
for not doing that.  (I'm hesitant to tag people due to risk of
appearing spammy, apparently that was a mistake this time.)

Cheers.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY5/1NAAoJELPy0WV4bWVwcYsP/R4fyNTYja2lMWAjmA+M8KSa
c5z1k8s8yQ0m93a/OY2/6rwnXCEGcybnMlCSPiNc1qTQrzHHbu9o90Tu8hEck+3j
greru288369G3UVdTH3A4DOvXCtoG09e1aPGrPEdYr7J4ppKOm99eRC/2vyrhGy7
NngWnhQkLEE81HxyElr6V0kiOy9F3cnY4jKSI5OKE5zKT87C2vP/5tnA+BwzW2uj
BZK1synzM4YAXSkHLQZPHP6H/xu1p5NHBCJKnWWlJz3910B5gmknETFGyiSPIiUs
6Esu/2HxuEHJR1PG+sYlrrIXafOCkSQ1bShvahcYvSwhpn+WvvWVbXV9N/ziW5en
8NN0egxqScCNUub1+X8hAErFMhcCyTOW/4f8VAgxhxYySZRJmQPqs9pSrxoh9ChG
8gAsEhBPrrX4H7lWzgI2ZTFP/Y5VDeYysZhh7yvvpkKrLCn7YgZBAZ92k4+LYjZf
MUfruwwhcILphkxpRWPK8TSMF/BIa/2Dhe83fR2aLJQzVCMrYf7m132WbcAp6JoI
6QJY0KL0NIvyjZMvufx1tA0kXm8Bd6S4iTlpu2jptM8Ts9onoLxMrhtRCXvbfV/w
QI6SZj9q0F9J+i/7dLEMsRuY6bRyL/42f8y6SoU9r9utVhlhW0sBvuIHf0QqYEbU
XDND0DYSZpHxBqAOsfd7
=+EF0
-----END PGP SIGNATURE-----

**Comment by laanwj** [comment]
> I'm hesitant to tag people due to risk of appearing spammy, apparently that was a mistake this time.

Yes, to be clear I only said that because you specifically request his file. If some other DNS seeder's `seeds.txt`'s is fine too you should say so.

**Comment by jonathancross** [comment]
Are you looking for this file?
http://bitcoin.sipa.be/seeds.txt.gz

(got the file name from [here](https://github.com/sipa/bitcoin-stats/blob/b1690b87a781a2bdd1b5f7e6fa284e1bc0e50541/update.sh#L104))

Issues like this should probably be filed here: https://github.com/sipa/bitcoin-stats/issues

**Comment by laanwj** [comment]
Seems resolved, closing.
