### ISSUE TITLE
UI misrenders sendmany

### ISSUE THREAD

**Issue by zw** [bitcoin/bitcoin#10173]
On 0.14 from bitcoin.org binaries, a sendmany TX doesn't get decomposed properly in the UI.

A TX was created that spent coins behind the UI's back.  (It was made with createraw but is basically a sendmany, apart from not using a fresh change address.)  This TX (ID 32a4915187c0e3213696903b05ee029b20a9e4c3cf4873b1be165593de5155c3) sent 0.001 to each of three addresses; two non-ismine and one ismine (1MichaiL1SZsctjm4gwoSZEueCWN38i4RW) for the change.  In the UI, personally I'd expect to see one of the following:
 * each non-ismine destination and corresponding amount on its own "transaction split" line, or
 * one line summarising the total spent to non-ismine destinations, not attempting to split them up, or
 * something indicating that this tx can't be decomposed at all

There's [a screenshot of what actually appeared](https://i.imgur.com/Q2A4vsB.png) (for some reason I can't attach it right now).  It appears to misidentify which addresses are owned by the wallet; the split labelled `1JGW...` is clearly either wrongly labelled or has the wrong amount, and it's unclear whether `1Eig...` is that output or mislabelled change. @gmaxwell kindly eyeballed this quickly and said "it renders sendmany normally, but it looks like it's wonking up ismine".

A sanity-checking console interaction verifying the ismine-ness is available [in a pastebin](https://pastebin.com/seH6qFD7) too.

**Comment by jonasschnelli** [comment]
I think this is partially related to:
https://github.com/bitcoin/bitcoin/issues/6814
https://github.com/bitcoin/bitcoin/pull/7101

**Comment by MeshCollider** [comment]
I tested a similar transaction in 0.15.0rc3 and it seems to be working fine, can you confirm if this has been resolved or if it's still an issue?
