### ISSUE TITLE
Cursor bein' all, like: I ain't gotta be doin' shizzle that be makin' sense.

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [bitcoin/bitcoin#10174]
I am using Windows 8 and Bitcoin Core version 0.14.0.  In the operating system's settings for the mouse I have the "Snap To" option ("Automatically move pointer to the default button in a dialog box.") enabled.

When I click on the "Send" tab at the top of Bitcoin Core the cursor/pointer snaps to the send button (which I kind of think is a bit ill advised, possibly).  Then, when another tab is selected (either "Overview", "Receive" or "Transactions"), the cursor is moved to the place on the screen, the place in the program, where the Send tab's Send button was.  So you move from the Send tab to another tab, and just like when you selected the Send tab and the cursor was moved to where the Send button is, your cursor gets moved to that same spot, even though you just selected a different tab to become active.  O.o

I could be entirely wrong, but . . . me thinks this is what the experto-Bitcoiner-toshi types call: "a bug".

I am rather excited that I might be the first one to bitch about this because I want to be cited in the release notes as a contributor or advisor or "peon shit nothing" or whatever.  Please, some big huge important Bitcoin Core developer type person, agree with me that this is a bug and do all the work and fix it and cite me as being the most important person since Isaac Newton in some official press release or version release notes.  Thank you and good night.

**Comment by laanwj** [comment]
Looks like the same issue as #4840. Bitcoin Core has no code for changing the cursor position as that is indeed terribly annoying behavior.

Apparently this is a windows feature:
```
<TheSeven> windows itself has such a "feature"
<TheSeven> you can enable it somewhere in the mouse settings
<TheSeven> if something opens a dialog, the cursor will automatically jump to the default button of that dialog
<TheSeven> IIUC that user has thar weird feature enabled, and is just complaining that it's somehow picking the wrong buttons to jump to
```

**Comment by KibbledJiveElkZoo** [comment]
I am closing this "issue" because I was told to by my Oracle.
