### ISSUE TITLE
"Signer" in gitian build - what is it?

### ISSUE THREAD

**Issue by runn1ng** [bitcoin/bitcoin#10203]
I am trying to make a binary out of bitcoind sources.

I am stuck at this line on gitian build guide:

> At this point you have two options, you can either use the automated script (found in contrib/gitian-build.sh) or you could manually do everything by following this guide. If you're using the automated script, then run it with the "--setup" command. Afterwards, run it with the "--build" command (example: "contrib/gitian-build.sh -b signer 0.13.0"). Otherwise ignore this.

What is `signer`? I am reading all the documentation and I can't figure out what to write there. I have a GPG key, but it is not "gitian key", I haven't registered with gitian anywhere.

**Comment by sipa** [comment]
It's just some name you choose. There is no registration process.

You can see some examples here: https://github.com/bitcoin-core/gitian.sigs/tree/master/0.14.0-linux

**Comment by runn1ng** [comment]
Thank you, but what if I don't want to sign anything? I just want a static bitcoind binary, that's why I am following the gitian process mostly.

I haven't put my GPG key into the virtual machine either; there is nothing about it in the guide :)

**Comment by runn1ng** [comment]
I have been able to get the script out of gitian.yml and into Docker though, with some changes, and it is building bitcoind binary as well (and it's easier for me to run), so I don't need this anymore and I might close this

**Comment by sipa** [comment]
If you just want a static binary, and not necessarily one that is byte identical to the release binaries, it's much easier to just do a depends build (which doesn't need any virtual machine). See the documentation inside the depends/ directory.

**Comment by runn1ng** [comment]
Thanks a lot! I didn't know this. I will look at it.

**Comment by MarcoFalke** [comment]
I think we should mention that signer is optional for gitian building (and also fix the script to make it actually optional)

**Comment by laanwj** [comment]
> I haven't put my GPG key into the virtual machine either; there is nothing about it in the guide :)

You don't need to put your GPG key in the VM. I think most gitian builders don't. Signer is the name that will be given to the assert files. You need that even if you sign them manually outside the VM.

**Comment by runn1ng** [comment]
Thanks for clarifying. I will close this issue now
