### ISSUE TITLE
feature request: non destructive prune switch

### ISSUE THREAD

**Issue by pscTheOne** [bitcoin/bitcoin#10217]
-prune option deletes blockchain files irreversibly.
A switch (like -prune-keep-files for renaming the files instead of deleting would enable someone with a fully downloaded blockchain to create a trusted pruned node to copy onto other computers and thereafter revert to a full blockchain without first having to backup .bitcoin/blocks

**Comment by laanwj** [comment]
There is a `fastcopy_chainstate` script here that helps with doing that conveniently: https://gist.github.com/laanwj/3c4614a23e072cbb3d39090da1834a68 
I use this for testing pruning.
It uses hard links to quickly make a "copy" of the chain state + utxo set. The files that are not changed by bitcoind are linked, the rest is copied. Files not necessary for this (such as the wallet, debug log, etc) are not copied.
This copy of the data directory can be pruned at will, then copied, or simply deleted without adverse effect on the original datadir.
