### ISSUE TITLE
using deep learning frameworks in bitcoin mining

### ISSUE THREAD

**Issue by tiagmoraismorgado** [bitcoin/bitcoin#10261]
<h1>Ideas for improving bitcoin mining:</h1>

<h2>it would be interesting if bitcoin mining system could take advantage of:</h2>
- <i>deep learning frameworks, and specially deep convolutional neural networks</i>

<h2>another interesting thing, specially for lowering the down the mining difficulty ratio would be:</h2>
- <i>allowing users to have their own mining pool, so instead of having community pools, creating a system where mining is only possible, if you do it on a single machine, and it's only possible to use like gpgpu (not heterogeneus computing)</i>

<h3>that is a good idea becuase:</h3>
- <i>it would make bitcoin mining even more de-centralized</i>

**Comment by jonasschnelli** [comment]
This is the development issue tracker.
Please use the mailing lists or forums for high level brainstorming.
