### ISSUE TITLE
MAX_BLOCK_SERIALIZED_SIZE is not a consensus-enforced constant

### ISSUE THREAD

**Issue by SergioDemianLerner** [bitcoin/bitcoin#10289]
The constant MAX_BLOCK_SERIALIZED_SIZE in  
https://github.com/bitcoin/bitcoin/blob/master/src/consensus/consensus.h#L12

is not a consensus constant. It's not enforced by consensus code. Its presence in consensus.h only confuses the reader.

### What version of bitcoin-core are you using?
0.14.0

**Comment by TheBlueMatt** [comment]
I believe the comment that's there is intended to imply this, do you have a proposed better wording for it?

**Comment by dcousens** [comment]
@TheBlueMatt I suppose the idea was that,  if it isn't relevant to consensus,  why is it in `consensus.h`

**Comment by sipa** [comment]
It isn't exactly a consensus constant, but it is related to it (if it's set to a value below the consensus maximum, some of the rescanning/network code may start failing). Perhaps we should just remove the constant, and replace its use sites with an expression that computes it from consensus constants.

**Comment by pinheadmz** [comment]
Could the useage sites be switched to `MAX_BLOCK_WEIGHT`?

> an expression that computes it from consensus constants.

What would this expression be besides `MAX_BLOCK_WEIGHT * 1` ?

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.
