### ISSUE TITLE
crazy 'estimated time left until synced' estimate

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#10291]
Running "Bitcoin version v0.14.0.0-b0c9b33" when it first started up I saw this:

![screenshot - 17-04-27 - 03 17 02 pm](https://cloud.githubusercontent.com/assets/573356/25506778/2b72bf86-2b5d-11e7-9832-98b6ea47d7bd.png)

1. The estimated time is way too high. It will only take a few hours to sync the remaining blocks.

2. The estimation is shown as a huge number of seconds instead of converting it to "48 years". Later, the estimation changed to "3 hours", so the code is capable of doing such conversions, but in this case it didn't.

**Comment by jonasschnelli** [comment]
devision by 0 issue.
`remainingMSecs = remainingProgress / progressDelta * timeDelta;`.
In your case, you tip-update-time-samples had only two (or more) tip updates during the same second (which can happen often). I'll fix this soon.
