### ISSUE TITLE
Network Traffic graph displays errenous traffic spikes

### ISSUE THREAD

**Issue by marukka** [bitcoin/bitcoin#10296]
### Describe the issue
**First Issue**
In Bitcoin Core 0.14.0 the Network Traffic graph in the Debug window displays erroneous traffic spikes when synchronizing the block chain. My internet connection is limited to 50 mega**bit**/sec downstream yet the bursts are over 10 mega**bytes**/sec, approximately twice the bandwidth that  my internet connection should be capable of. Although theoretically my internal network could be buffering this traffic and sending it as a burst, these theoretical traffic bursts are not seen by the operating system's Task Manager or Resource Monitor applications therefor I believe it is safe to rule this out as the cause.

**Second Issue**
When you press the Clear button in the Network Traffic graph, and no network activity is taking place, it will not render a graphic for the graph. After a period of time when network traffic does take place it will render a flat line followed by a graph of the traffic

#### If so, please list the steps to reproduce below:
**First Issue**
Replicate the environment, begin to download the block chain and watch the traffic graph window for hours. I'm sure you could save yourself a lot of time by doing this programmatically and have your code look for traffic spikes which would exceed the available internet bandwidth.

**Second Issue**
Replication the environment, begin to download the block chain, wait for a period of no network traffic, press the clear button, wait for network traffic to resume.

### Expected behaviour
**First Issue**
The network graph should display accurate traffic statistics.

**Second Issue**
The network graph should display a flat line during periods of no traffic

### Actual behaviour
**First Issue**
There are erroneous traffic spikes.

**Second Issue**
A flat line is not displayed until traffic occurs after the graph has been cleared.

### Screenshots.
**First Issue**
Please be aware that there is also iSCSI and Remote Desktop Services traffic accounted for in the Task Manager/Resource Monitor graphs. Even with this extra traffic, Task Manager/Resource Monitor does not display the same 10+ megabyte/sec traffic spikes.
Video of it happening with Task Manager - https://my.mixtape.moe/ugszqy.mp4
Screenshot of it happening with Resource Monitor:
<img width="1680" alt="screen shot 2017-04-28 at 5 04 59 pm" src="https://cloud.githubusercontent.com/assets/3067075/25549689/071638c0-2c39-11e7-8925-5e103c5c00f1.png">

**Second Issue**
Video of it happening - https://my.mixtape.moe/gcazhi.mp4

### What version of bitcoin-core are you using?
0.14.0

### Machine specs:
- OS: Windows Server 2016 Remote Desktop Services Session Host virtual machine with Bitcoin Core configured as a RemoteApp on a VMware ESXi 6.5 host
- CPU: 4 cores from a dual Xeon E5-2660v2 with high latency sensitivity and 100% resource reservations
- RAM: 4GB with 100% resource reservations
- Disk size: OS/Bitcoin Core 32GB, data directory 1TB
- Disk Type (HD/SDD): OS/Bitcoin Core is stored on the host as a VMDK on a 8x SSD RAID 0 VMFS6 datastore, the data directory is a thin provisioned LUN on a Microsoft iSCSI target server 2016 failover cluster running deduplication stored on the host as a VMDK on a 8x HDD RAID 6 VMFS5 datastore.
- Network: Cable Modem->Cisco ASA 5510 firewall->Two Cisco Aironet 1141 802.11n (2.4Ghz) APs configured as a workgroup bridge->Cisco Catalyst 3750E switch->ESXi host with a Intel X520 NIC as the uplinks for the VDS port group->VM with a VMXNET3 network adapter

### Any extra information that might be useful in the debugging process.
Debug.log - https://my.mixtape.moe/fczubf.zip

**Comment by marukka** [comment]
I discovered a second issue with the graph and edited my OP to reflect this.

**Comment by paveljanik** [comment]
Please report the second issue as a separate one. I can reproduce it. Some scale (maybe the latest used?) should be chosen and drawn with no values.

**Comment by fanquake** [comment]
I've moved this to the GUI repo: https://github.com/bitcoin-core/gui/issues/50.
