### ISSUE TITLE
Feature Request (RPC): Specify a txid when calling getrawmempool in verbose mode

### ISSUE THREAD

**Issue by dabura667** [bitcoin/bitcoin#10300]
`bitcoin-cli getrawmempool true`

Currently this command returns all transactions in the mempool. it would be nice to have an extra arg dependent on verbose mode. (It would have no meaning in non-verbose mode)

ie.:
```
bitcoin-cli getrawmempool true 7dde270e7071667c5d53b073f1d7854319696ea10202e0fb8874c2361dcdd6da
```

Which would only return that single transaction if it is still unconfirmed and return empty if it has already confirmed or does not exist in your mempool.

ie.:
```
{
  "7dde270e7071667c5d53b073f1d7854319696ea10202e0fb8874c2361dcdd6da": {
    "size": 258,
    "fee": 0.00050000,
    "modifiedfee": 0.00050000,
    "time": 1493525525,
    "height": 464139,
    "startingpriority": 0,
    "currentpriority": 0,
    "descendantcount": 1,
    "descendantsize": 258,
    "descendantfees": 50000,
    "ancestorcount": 2,
    "ancestorsize": 516,
    "ancestorfees": 100000,
    "depends": [
      "8fb66a50a714462308fbaff262abe15d85a5823b7e8cbdefff23c2076685373f"
    ]
  }
}
```

Use case: Child Pays For Parent fee calculation by looking at ancestorsize and ancestorfees.

**Comment by sipa** [comment]
Isn't that what `getmempoolentry` does?

**Comment by paveljanik** [comment]
It is. @dabura667 Is your issue solved now? If it is, let's close this issue please.

**Comment by dabura667** [comment]
#10310

This issue will continue on in the above issue.
