### ISSUE TITLE
Progress bar when reindexing jumps back and forward quickly by a few years

### ISSUE THREAD

**Issue by wintercooled** [bitcoin/bitcoin#10315]
### Describe the issue
When running wth -reindex the progress bar jumps back and forward by a few years. The reindex itself does seem to be progressing as the 'last block time' text is progressing at a decent speed and sequentially by date and time. See behaviour here: http://imgur.com/kelVOnT

Not sure but I think I remember the progress bar moved sequentially forward in time only the last time I reindexed (also with 0.14.1).

### Can you reliably reproduce the issue?
It's still re-indexing and will take a while so is not easy to reproduce without taking my node off line.

### Expected behaviour
Progress reported normally

### Actual behaviour
Jumps back and forth by a few years

### Screenshots.
Video - http://imgur.com/kelVOnT

### What version of bitcoin-core are you using?
Binary on Windows 64 bit - 0.14.1
From: https://bitcoin.org/bin/bitcoin-core-0.14.1/bitcoin-0.14.1-win64-setup.exe

### Machine specs:
- OS: Windows 10 Pro
- CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
- RAM: 4GB
- Disk size: Client runs on 256GB SSD, datadir points to a 1TB internal HDD
- Disk Type (HD/SDD):  Client runs on 256GB SSD, datadir points to a 1TB internal HDD

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
