### ISSUE TITLE
Stop creating change outputs when not necessary

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#10329]
This issue follows the [discussion from here](https://github.com/bitcoin/bitcoin/issues/7664#issuecomment-230359114).

Core currently does an exact match to check if it should omit the change output when creating a transaction. However the correct logic should be to have a little of leeway, donating extra money to miners if required.

(This is because creating a change output itself isn't free, you need to pay the extra bytes in the transaction, and in the future source that change output at least paying `relayfee`).

So instead of an exact match against `amount == target` it should check if it's `amount >= target && amount < target + sizeof(a_change_output) * fee_rate + sizeof(sourcing_that_change) * relayFee)`.

This has the benefit of improving coin selection, but most importantly it will hugely improve privacy for bitcoin users as it'll break a lot of the wallet clustering logic that identifies change outputs.

**Comment by instagibbs** [comment]
Change outputs are created or not due to this check:
https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L2538

Seems that would line up with any `SelectCoinsMinConf` change you'd want made?

**Comment by RHavar** [comment]
> Change outputs are created or not due to this check:
https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L2538

Yeah, that sort of thing just needs to be extended over the whole thing. e.g. to lines like this
https://github.com/bitcoin/bitcoin/blob/35da2aeed7d4000dde93957c3b6e048ab83c4f2b/src/wallet/wallet.cpp#L2133 

(although to be honest, I haven't studied that code enough to know how it interacts with the constant like MIN_FINAL_CHANGE)

> Seems that would line up with any SelectCoinsMinConf change you'd want made?

I closed that issue and desire to change it. Too much bike shedding involved in coin selection algorithms, and easier for me to just run my own patched coin selection than try push it on others

**Comment by RHavar** [comment]
(If someone has already started working on this, please let me know and I'll honor the 1 btc bounty. Otherwise I'm removing it -- as I have finished implemented this logic in my own code, so no longer really require it in bitcoin core itself)

**Comment by MeshCollider** [comment]
I believe the new coin selection algorithm tracked in https://github.com/bitcoin/bitcoin/issues/7664 addresses this

**Comment by jnewbery** [comment]
@RHavar - does this issue need to stay open now that https://github.com/bitcoin/bitcoin/pull/10637 is merged?
