### ISSUE TITLE
block accepted in solo mining in Antpool  and never rewards in the dashboard

### ISSUE THREAD

**Issue by ozeiuyo** [bitcoin/bitcoin#10326]
(5s):2.143M (avg):1.512Mh/s | A:1  R:0  HW:0  U:0.0/m  WU:0.0/m
 ST: 1  SS: 0  NB: 143  LW: 7312  GF: 11  RF: 0
 Connected to stratum.antpool.com diff 16 with stratum as user vanessaq.x
 Block: 00000179309b18ae...  Diff:522G  Started: [14:46:37]  Best share: 486
--------------------------------------------------------------------------------
 [P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit
 GPU 0:                | 2.254M/1.512Mh/s | A:1 R:0 HW:0 U:0.00/m I: 1
--------------------------------------------------------------------------------
 A:2  R:0  HW:0  U:0.0/m  WU:0.0/m
 ST: 0  SS: 0  NB: 33  LW: 1145  GF: 5  RF: 0
 Connected to stratum.antpool.com diff 16 with stratum as user vanessaq.x
 Block: 0000006e164874b9...  Diff:522G  Started: [06:03:46]  Best share: 132

no support reponse for few days ago

**Comment by jonasschnelli** [comment]
Please place this question on something like http://bitcoin.stackexchange.com or contact Antpool.
Closing.
