### ISSUE TITLE
massively wrong time displayed in transaction fee suggestions.

### ISSUE THREAD

**Issue by TiiStyle** [bitcoin/bitcoin#10320]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
if you select a time of roughly 2 hours until confimation shall start you will still be waiting after more than 27 hours to confirmations to start, if they ever will.

#### If so, please list the steps to reproduce below:
1. Send 0.01 BTC to another wallet; use transaction fee suggestions:
2. Set suggestion the the highest point where the lowest amount is suggested.
Example: If the lowest rate is: 26k Satoshi / kB at 4hours but it still is 26k Satoshi at 3 hours but 1 higher more would be suggested, set it to 3 hours.

### Expected behaviour
Transaction conformations should for real start roughly at the suggested times +- 20%.

### Actual behaviour
Transactions that used low fees when the load was low don't get confirmed after the suggested time if load increased. I now wait for 27 hours for my 0.01 BTC to start being confirmed at 26k Satoshi / kB, which was a suggestion where was displayed that the transaction confirmation should start within the next 2 hours!

### What version of bitcoin-core are you using?
Bitcoin Core Version v0.14.1 (64-Bit) - Provided by developers, not self compiled.

### Machine specs:
- OS: Win 10

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions about transactions fee estimation and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
