### ISSUE TITLE
Coin Control Dialog is not (very) useful for manual privacy protection

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#10337]
The "received by address" groupings that we group by right now are based on walking back any outputs we consider change by their first input. So two outputs to the same change address (which I suppose we dont support) could end up in different trees/address groupings. Further, the tree mode seems to imply that it displays groups ala listaddressgroupings, which it clearly does not, instead it appears to pull its "received by address" labels from something more akin to our accounts crap.

It should probaboy, instead, consider change outputs as their own category, and we should also likely have a listaddressgroupings mode, given this seems to have been the whole point of the feature, and it is how the feature is described to users.

**Comment by Sjors** [comment]
Personally I've only used this to select a single output to spend from, never anything more complicated.

**Comment by MarcoFalke** [comment]
Accounts has been removed. Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
