### ISSUE TITLE
RPC: bad character in bip125-replaceable in listtransactions

### ISSUE THREAD

**Issue by kewde** [bitcoin/bitcoin#10334]
### Describe the issue
`listtransactions` returns a JSON key with the name `bip125-replaceable`, which turns out to be a bad choice for naming. When you run listtransactions through the JSON parser (written in a language such as JavaScript) that maps it to an object then it will try to create a variable with a '-' in it. 

It will crash the application since '-' is not a valid character for a variable name as it is also a mathematical operator.
However the JSON RFC manual does not explicitly forbid the usage of '-' in the key names so technically it is completely valid JSON. The blame is with the people who write the JSON parsers, but I do think it's worth bringing it up as an issue such that this character is prevented in the future.

**Comment by luke-jr** [comment]
IMO close as invalid, since '-' is a valid character. If your parser is broken, fix your parser.

Javascript can parse JSON with `eval()` (it's not secure, but neither is a broken parser trying to evaluate the '-' as a subtraction...)

**Comment by kewde** [comment]
I agree that this issue is doesn't share much relevance to Core, it fully confirms with the RFC specifications but I do think we should avoid the usage of this character in the future.

**Comment by dcousens** [comment]
@luke-jr or he could use `JSON.parse`... which absolutely does support `-`.

**Comment by kewde** [comment]
@dcousens JSON.parse indeed supports the '-', which is what I currently use.
