### ISSUE TITLE
wallet 0.14.1 not responding 

### ISSUE THREAD

**Issue by alafax** [bitcoin/bitcoin#10349]
I noticed some unusual behaviour of wallet 0.14.1 during normal daily synhronization.After downloading blockchain data,during processing blocks,wallet is not responding almost 90% of time,until it finished processing.CPU load is never over 15-20%,so it is not overload problem.Problem dissapeared when I disconnect from network and let wallet processing downloaded data to the end.

### Machine specs:
- OS: Windows 7 32bit
- CPU: Quad core 8200
- RAM: 4Gb
- Disk size: 640 Gb
- Disk Type (HD/SDD):HD

**Comment by laanwj** [comment]
Yes, the GUI can sometimes hang while processing blocks, as the background thread that validates blocks monopolizes the `cs_main` lock. This usually, but not always accompanied by 100% CPU usage, it depends on your system, verification can also be I/O bound.

**Comment by xianglanlan** [comment]
My bitcoin core money synchronized to December 31, 2013 was stuck, then synchronization can no longer update, how to solve?

**Comment by alafax** [comment]
@xianglanlan 
Try to use wallet 0.13.2. It is the most stable one of recent versions.

**Comment by xianglanlan** [comment]
@alafax Can I uninstall re-install? If the re-install, I originally in this wallet to receive the bitcoin will disappear?

**Comment by xianglanlan** [comment]
![20170506003453](https://cloud.githubusercontent.com/assets/28524124/25793733/68f7b3f6-3400-11e7-9583-16df8baca4e9.png)

**Comment by xianglanlan** [comment]
I installed the computer installed Bitcoin Core version v0.14.0 (64-bit), the block did not synchronize the completion of the case, I received a bitcoin currency, but the wallet can not find the deal, and the transaction has been in blockchain Network confirmed, and my wallet sync block data has been stuck in December 31, 2013, no longer updated, how to solve it?

**Comment by alafax** [comment]
@xianglanlan 

I see on the screenshot you have connections,so it is not connection problem.Version 0.14 has some problems,so my advise is to install 0.14.1 or 0.13.2 version over it.Dont need to uninstall version you have now,just install 0.14.1 or 0.13.2 over it.
Also mine 0.14 and 0.14.1 wallet had crashed during sinhronization when I had this window which shows progress open, so after your wallet starts and open interface,close that window.
If the process of sinhronization stop(node problem),you can click on little picture which shows connections(picture right from HD mark).It will terminate connections to nodes.After 2-3 minutes click on it to establish connections with new batch of nodes

**Comment by jonasschnelli** [comment]
https://github.com/bitcoin/bitcoin/pull/10231 could reduce the symptoms of the problem described here...
If you self-compile, maybe give it a try or wait for 0.14.2

**Comment by Leviathn** [comment]
@alafax did this resolve?
