### ISSUE TITLE
My bitcoin core wallet sync block data to December 31, 2013 can no longer be synchronized, so far has been shown in the calculation process...

### ISSUE THREAD

**Issue by xianglanlan** [bitcoin/bitcoin#10356]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
My bitcoin core wallet synchronized to December 31, 2013 was stuck, then synchronization can no longer update, how to solve?
#### If so, please list the steps to reproduce below:
1. I installed the computer installed Bitcoin Core version v0.14.0 (64-bit), the block is not synchronized to complete the case, I received a bit of coins, but the wallet has not shown, and the block has been confirmed on the network ,How to do it?
2. Can Bitcoin Core receive and pay Bitcoin if the blocks are not synchronized?
3. Has been shown in the synchronization, has been several days, or stay in sync 2013, how to solve?

### Expected behaviour
Tell us what should happen
Can I uninstall re-install? If the re-install, I originally in this wallet to receive the bitcoin will disappear?
### Actual behaviour
Tell us what happens instead
Will bitcoin core wallet have any way to improve the speed of synchronization?
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
Has been shown in the synchronization, has been several days, or stay in sync 2013
### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
 Bitcoin Core version v0.14.0 (64-bit)
### Machine specs:
- OS: Windows 10
- CPU: Intel Core i5-2410M 2.30 GHz
- RAM: 4.00 GB
- Disk size: 750 GB
- Disk Type (HD/SDD):  HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
![20170506003453](https://cloud.githubusercontent.com/assets/28524124/25805865/d7625fb6-3433-11e7-84da-5fe31a691452.png)

**Comment by MarcoFalke** [comment]
You are asking for a "way to improve the speed of synchronization". Do you mean that synchronization is slow or instead stalled altogether?

**Comment by xianglanlan** [comment]
Synchronized to December 31, 2013 to pause, so far no longer continue to synchronize.

**Comment by xianglanlan** [comment]
@MarcoFalke  That synchronization is instead stalled altogether.

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by Leviathn** [comment]
@xianglanlan has this resolved? Or can you please post the debug.log?

**Comment by xianglanlan** [comment]
not solved
发自网易邮箱大师
On 09/05/2017 20:51, Leviathn wrote: @xianglanlan has this resolved? Or can you please post the debug.log?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bitcoin/bitcoin","title":"bitcoin/bitcoin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bitcoin/bitcoin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Leviathn in #10356: @xianglanlan has this resolved? Or can you please post the debug.log?"}],"action":{"name":"View Issue","url":"https://github.com/bitcoin/bitcoin/issues/10356#issuecomment-327165361"}}}

**Comment by Sjors** [comment]
Have you tried this again with 0.16? We'll need debug.log to be more helpful.

**Comment by MeshCollider** [comment]
Closing this now, if its still an issue please post the debug log as requested
