### ISSUE TITLE
Add more columns to the transaction list in the GUI

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#10369]
On big screens the transaction list has a lot of space that is not utilized:

![image](https://cloud.githubusercontent.com/assets/12032350/25846547/79e4c75a-34b2-11e7-9e32-6c3f3b74a301.png)

I suggest that the columns shown here are made configurable. I would personally like the following columns:

* Debit
* Fee
* Net amount
* TxID
* Number of recipients
* Number of inputs
* Number of confirmations (right now this is rendered as a graphical indicator combined with a tooltip)
* A button column "Copy transaction details to clipboard". This is useful for copying out all of the data to document the transaction in some other place.
* Maybe a text comment for the transaction in addition to the label (which is meant to be short)

I am always unsure what the "Amount (BTC)" column means. It would help to have all three amount-based columns available. Right now I have to open the transaction details to find those values.

Maybe there are other data that can be exposed for power users as well.

**Comment by jonasschnelli** [comment]
I'm not sure if the amount of columns can depend on the window-width. Adding more column for "standard" window-widths may result into confusion.
However, I think this approach should by tried out...

**Comment by laudaa** [comment]
How about an option to enable/disable each individual extra column, but keep these disabled by default? @jonasschnelli

**Comment by GSPP** [comment]
@laudaa that's what I meant.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
