### ISSUE TITLE
Unable to gitian-build bitcoin for Windows

### ISSUE THREAD

**Issue by 39otrebla** [bitcoin/bitcoin#10398]
I've gone 4 times through the gitian build following the official documentation provided within the repo, but still no luck.

### Can you reliably reproduce the issue?
Yes, it happens every  time trying to build Bitcoin 0.13 for Windows using gitian-build

### Expected behaviour
Build

### Actual behaviour
`util.h:31:26: fatal error: sys/resource.h: No such file or directory
 #include <sys/resource.h>
                          ^
compilation terminated.`

### What version of bitcoin-core are you using?
Official Bitcoin repostiory, branch `0.13`

### Machine specs:
- OS: Ubuntu 16.04
- CPU: i7 6700 hq
- RAM: 16gb ddr4
- Disk size: 512 gb
- Disk Type (HD/SDD): ssd pcie

### Any extra information that might be useful in the debugging process.
Using gitian-build

**Comment by fanquake** [comment]
Which gitian build command is the one failing, can you provide the options you are using? 
Can you provide a more extensive build log?

**Comment by fanquake** [comment]
Closing due to lack of follow up. If have more information please re-open.
