### ISSUE TITLE
My sync will not proceed past Feb 25th 17:42.10 2017

### ISSUE THREAD

**Issue by klfstl** [bitcoin/bitcoin#10399]
### Describe the issue

I recently installed 0.14.01 on my MBP after a 3 month hiatus. As the software attempts to update to the newest block it suffers a fatal error on the Feb 25th 17:42:10 2017 Chain as can be seen in the screen shot attached. 

### Can you reliably reproduce the issue?
YES, every time 

#### If so, please list the steps to reproduce below:
1. Open Bitcoin Core Wallet 
2. Software attempts to automatically update block chains 
3. Software suffers a fatal error when reaching the Feb 25 17:42:10 2017 chain

### Expected behaviour
Tell us what should happen
***The software should continue updating the chain until it is up to date

### Actual behaviour
Tell us what happens instead
***
![screen shot 2017-05-14 at 9 40 19 am](https://cloud.githubusercontent.com/assets/12863057/26035010/5dee5f34-388b-11e7-8d5a-f93cdd1b4adb.png)
Software suffers a fatal error when reaching the Feb 25 17:42:10 2017 chain

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
Screen shot attached 

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
ver 0.14.1
Downloaded 2017 05 13 from https://bitcoin.org/en/download 

### Machine specs:
- OS:Sierra 10.12.4
- CPU:i7 2.8GHz
- RAM:16GB 1600MHz DDR3
- Disk size: InternalSSD 500GB (containing the software) ExternalHD 3TB (containing the digital/encrypted wallet)
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Smiggel** [comment]
Having the same issue here on my Raspberry Pi 3. Ran fine till it arrives at the end of feb. I get the same kind of error. Only the debug.log doesn't report any errors. So I can not see what happened.

**Comment by Leviathn** [comment]
Can you post the debug.log please?

**Comment by Smiggel** [comment]
@Leviathn my debug log is empty. There is only one line in with a date and time and nothing else. No description, etc.

**Comment by klfstl** [comment]
Just ran this

**Comment by klfstl** [comment]
[debug.txt](https://github.com/bitcoin/bitcoin/files/1001451/debug.txt)
here is my log file

**Comment by jonasschnelli** [comment]
```
2017-05-15 14:50:28 Corruption: block checksum mismatch
2017-05-15 14:50:28 *** System error while flushing: Database corrupted
2017-05-15 14:51:03 connect() to [2001::5ef5:79fb:14b9:9c33:a606:a062]:8333 failed: No route to host (65)
```

You are using `/Volumes/KLF Storage B/Bit Coin`?
Is this a network attached storage?

LevelDB runs much smoother if you have the database on a local spinning or SSD disk.

Try to re-sync with a data-dir set on your local drive.
Maybe use pruning (-prune=550) if you have not enough disk space.

**Comment by klfstl** [comment]
It is a 3TB flash drive connected via USB

I have since started a new file in the same drive and was able to download
the entire blockchain in 36 hours

It works now

Something was corrupted so it should be ok now…

This was eye opening though, the first 6 years is roughly 25% and the last
2 years makes up the remain 75% of the total block chain data


On May 25, 2017 at 1:39:01 PM, Jonas Schnelli (notifications@github.com)
wrote:

2017-05-15 14:50:28 Corruption: block checksum mismatch
2017-05-15 14:50:28 *** System error while flushing: Database corrupted
2017-05-15 14:51:03 connect() to
[2001::5ef5:79fb:14b9:9c33:a606:a062]:8333 failed: No route to host
(65)

You are using /Volumes/KLF Storage B/Bit Coin?
Is this a network attached storage?

LevelDB runs much smoother if you have the database on a local spinning or
SSD disk.

Try to re-sync with a data-dir set on your local drive.
Maybe use pruning (-prune=550) if you have not enough disk space.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin/bitcoin/issues/10399#issuecomment-304089212>,
or mute the thread

**Comment by jonasschnelli** [comment]
Okay. Great to hear.
closing...
