### ISSUE TITLE
Error message when relaunching bitcoin core every time

### ISSUE THREAD

**Issue by pjtallon** [bitcoin/bitcoin#10394]
#### If so, please list the steps to reproduce below:
1. Install bitcoin core
2. Wait or not for database to be synchronized with the network
3. shutdown bitcoin core / shutdown computer
4. launch bitcoin core leads to the issue

### Expected behaviour
I expect the app to launch correctly even after I closed it once.

### Actual behaviour
An assertion failed message occurs and the program crashes.

### Screenshots.
![bitcoincoreerrormessage](https://cloud.githubusercontent.com/assets/16851376/26026911/ea648d76-3804-11e7-8c9c-b676dba26f8c.PNG)

### What version of bitcoin-core are you using?
0.14.1.0 latest published and available easily without compiling

### Machine specs:
- OS: Windows 10 family 64bits
- CPU: Intel(R) Core(TM) i7-7700K CPU @4.20GHz
- RAM: 8 GB
- Disk size: 938 GB
- Disk Type (HD/SDD): bitcoin core installed on HD but main disk is a SSD for the OS 128GB)

### Any extra information that might be useful in the debugging process.
I checked the debug file, which only contains logs before last closure, so useless for you.
I could not find the config.log file in the installation folder (anywhere also).

**Comment by TheBlueMatt** [comment]
Hmm, this should only happen if it fails to open the debug log, how is the datadir mounted/is there enough disk space/any idea why that might be the case?

**Comment by pjtallon** [comment]
My OS is installed on my SSD C:\ and I set the installation dir to a custom location in my HD D:\Bitcoin folder which had 800GB available memory before installation (so way more than needed).

If this issue is caused by a problem to access debug.log file, I can open it myself through windows explorer at the following location : D:\Bitcoin/Bitcoin/debug.log

So I guess it might be related to the custom location of the install dir ? But it seems weird as the choice of installation dir is left to the user at the beginning...

**Comment by laudaa** [comment]
Why is the debug.log in D:\Bitcoin\Bitcoin\debug.log when the program is trying to access: D:\Bitcoin\bitcoin-qt.exe?

Are you sure that you didn't add 1 extra subfolder and forgot to properly pick the path?

**Comment by pjtallon** [comment]
I set as install directory D:\Bitcoin.
But I made subdirectory dedicated to store the database (history of transactions), which is D:\Bitcoin/Bitcoin where debug.log is stored.
Unfortunately, I don't have a portable HDD : this one is inside my computer.
What I could test, on the other hand, would be to reinstall bitcoin core only after the download is completed, in D:\Bitcoin/Bitcoin folder. Which would at least test if the problem is the discrepancy between INSTALL_DIR and DATADIR.

Updates to come

**Comment by Apps4rent** [comment]
This is "one of the many" issues with hardware... people are renting computer for mining as this not only avoids hardware issues, but same time/money otherwise spend on maintenance.

A lot of customer's are successfully mining at www.apps4rent.com rigs. In fact, now you can use mining using GPU's well.

App4rent also offers money back guarantee.

**Comment by Apps4rent** [comment]
This is "one of the many" issues with hardware... people are renting computers for mining as this not only avoids hardware issues, but saves time/money otherwise spend on maintenance.

A lot of customer's are successfully mining at www.apps4rfent.com rigs. In fact, now you can use mining using GPU's as well.

Apps4rent also offers money back guarantee.

**Comment by TheBlueMatt** [comment]
Can you get some editor to open the debug.log for writing or can you append to the file?

**Comment by pjtallon** [comment]
Yes I could at the time, at least opening itin windows pad. I did not try to write and record it though

**Comment by lncpp** [comment]
It might be an idea to run procmon (https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) and monitor file events of the bitcoin-qt.exe process. This should show the windows error when calling the win32 File apis. This might give some hints...

**Comment by donaloconnor** [comment]
It might be an idea to run procmon (https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) and monitor file events of the bitcoin-qt.exe process. This should show the windows error when calling the win32 File apis. This might give some hints...

**Comment by Sjors** [comment]
Is this still an issue? Have you tried again with 0.16.0?

**Comment by MeshCollider** [comment]
Closing now, please reopen if this is still an issue
