### ISSUE TITLE
Timezone feature in bitcoinqt settings?

### ISSUE THREAD

**Issue by 2SI3NX** [bitcoin/bitcoin#10392]
### Describe the issue
Currently there is no timezone feature to set in bitcoin-qt so that it sets bitcoind to use it.
I see in debug.log that the log times are 2 hours early than my current timezone.

Ive heard that you could maybe create bitcoin.conf and manually put in the timezone but i havent tried anything like that yet because im not sure how to.

### Expected behaviour
A feature option should be available in the bitcoin-qt settings to be able to set the user's timezone correctly.

### Actual behaviour
Right now no timezone option is available.

### What version of bitcoin-core are you using?
Ubuntu 16.04 PPA

### Machine specs:
- OS: Ubuntu 16.04

**Comment by sipa** [comment]
debug.log always uses UTC time in log files, so if you're currently in Western Europe, that would correctly be 2 hours off. It uses your system's clock  and time zone, so there is nothing to configure.

**Comment by jonasschnelli** [comment]
Seems to be not an issue.. closing
