### ISSUE TITLE
Network Traffic/Reset delayed action

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#10406]
The Reset button in Debug window/Network Traffic clears the graph only after ~1s after clicking on it, not immediately.

**Comment by jonasschnelli** [comment]
What I propose is to completely rewrite the traffic graphs with stats collecting over something like https://github.com/bitcoin/bitcoin/pull/8501 and drawing logic from here: #8550.

IMO the best path towards this is currently #8501.

**Comment by fanquake** [comment]
While this might be annoying (that there is a slight lag in clearing the graph), I don't think this warrants keeping an issue open.
