### ISSUE TITLE
error: make sure server is running and you are connecting to the correct RPC port

### ISSUE THREAD

**Issue by zottirik** [bitcoin/bitcoin#10402]
### Describe the issue
I installed bitcoin-cli but i can't run it.
I got an error : "make sure server is running and you are connecting to the correct RPC port"

### What version of bitcoin-core are you using?
0.14

### Machine specs:
- OS: Ubuntu Server 14
- CPU: Intel® Xeon® E3-1270
- RAM: 16 GB
- Disk size: 600 GB
- Disk Type (HD/SDD): SSD

**Comment by sipa** [comment]
Is `bitcoind` running?

**Comment by zottirik** [comment]
When I try to start bitcoind, I get this;

root@server:~# bitcoind -daemon start
Error: There is no RPC client functionality in bitcoind anymore. Use the bitcoin-cli utility instead.

**Comment by MarcoFalke** [comment]
Try without the trailing "start".

You can use `bitcoind -h` or look at the [manpages](https://github.com/bitcoin/bitcoin/tree/master/doc/man) for futher information about the usage and command line options.

**Comment by fanquake** [comment]
@zottirik is this still an issue? If not can you please close this.

**Comment by laanwj** [comment]
> Error: There is no RPC client functionality in bitcoind anymore. Use the bitcoin-cli utility instead.

Eeh we should probably change that message at some point to something like `Error: Command line contains unexpected token *thing*, see bitcoind -h for a list of options`. Hardly anyone even remembers that bitcoind used to be a cli utility, let alone new users.

**Comment by vinyyoo** [comment]
i face same problem,
can anyone suggest me how to solved it.
![errrorrrr](https://user-images.githubusercontent.com/32484213/31169540-953c1250-a916-11e7-865c-6269a99b675e.png)

**Comment by MarcoFalke** [comment]
It might be more comfortable for you to use the GUI. Make sure to start with `bitcoin-qt -server -testnet`, so that you can connect with the `bitcoin-cli -testnet getblockchaininfo`.

Otherwise, you'd have to start the daemon first: `bitcoind -testnet`. (Should work without `-server` specified)

**Comment by songtaoM** [comment]
just run `bitcoind --daemon`. It works for me
