### ISSUE TITLE
How to get external address transaction information？

### ISSUE THREAD

**Issue by roddyofchina** [bitcoin/bitcoin#10401]
Dear developer, I want to get the transaction information of the external wallet address, but did not see the relevant interface, is there any way?

**Comment by jonasschnelli** [comment]
Can you explain what you mean by "external wallet address"?
Do you want to get information about a transaction not relevant to your wallet (then use `-txindex`)?

And I guess you question should be posted on bitcoin.stackexchange.com (or similar).
This issue tracker is mainly for development issues.

**Comment by roddyofchina** [comment]
Get a bicoin address transaction information, It's not a local wallet.

**Comment by jonasschnelli** [comment]
What exactly is a "bitcoin address transaction"? Do you mean all transactions of a specific Bitcoin address?
This is not possible with Bitcoin Core. Bitcoin Core does not provide an by address index.

However there are attempts to add this to bitcoin core:
* https://github.com/bitcoin/bitcoin/pull/10370
* https://github.com/bitcoin/bitcoin/pull/9806

There are external tools to maintain an address index:
https://github.com/bitcoinjs/indexd
https://github.com/bitpay/insight-api

**Comment by roddyofchina** [comment]
thanks so much

**Comment by runn1ng** [comment]
I will add - insight-api actually depends on bitcoin with custom patches (the same patches that are in https://github.com/bitcoin/bitcoin/pull/10370 )
