### ISSUE TITLE
getnewaddress gives out used address

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#10411]
### Describe the issue

I have 2 chains with identical copies of the wallet.dat. The keypool has 10000 addresses of which a tiny fraction has received bitcoin. So far, I've only used it to receive bitcoin.

The rpc command 'getnewaddress' gives out addresses that have already received bitcoin. I would think the bitcoin client, no matter what machine it runs from looks at what addresses have received bitcoin and then give out a clean unused address.

I've performed a start up with -rescan, but same result.

### Can you reliably reproduce the issue? 
Yes

### Expected behaviour
Tell us what should happen

receive an unused address, no matter which one of identical wallet.dat files are used. 

### Actual behaviour
Tell us what happens instead

See above.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

0.14.1 32 bit from bitcoin.org, not self compiled.

### Machine specs:
- OS: Ubuntu 14.1 
- CPU: Intel duo
- RAM: 1 G
- Disk size: 200 Gb
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

debug.log: 

keypool reserve 33
keypool keep 33

**Comment by laanwj** [comment]
Using the same wallet on multiple nodes is not a supported scenario at the moment. This is expected behavior.
There is some work in progress to automatically roll forward the HD chain when keys in the keypool are seen to be used, which might help here, but I'd still not recommend to do this.

**Comment by MarcoFalke** [comment]
I think `-rescan` will forward the HD chain/keypool appropriately if a tx was found in the chain. If it was never used on-chain, but given out, the only thing that can be done is to manually call `getnewaddress` in a loop to "discard" used addresses.
