### ISSUE TITLE
Need fee estimation migration for 0.15

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#10418]
#10199 has some basic deserialization code still in place for old fee estimations to support reading 0.14-formatted fee estimates so that they can be at least utilized to populate some basic fee results until the new buckets fill up. We'd need to implement such a scheme for 0.15.

@morcos.

**Comment by morcos** [comment]
This isn't going to happen.  Would have been a nice addition, but not critical.
Let's let it go

**Comment by laanwj** [comment]
Closing, if it's not going to happen for 0.15, it makes no sense to do later on.
