### ISSUE TITLE
Cannot Launch Bitcoin Core

### ISSUE THREAD

**Issue by Owennnnnn** [bitcoin/bitcoin#10430]
### Describe the issue
Bitcoin Core crashes when it launches.
#### If so, please list the steps to reproduce below:
1.Open bitcoin core
2.It Crashes

### Expected behaviour
It should have opened to the normal bitcoin core window.

### Actual behaviour
It stops responding and doesn't respond again.

### Screenshots.
![crash](https://cloud.githubusercontent.com/assets/27851824/26233897/412e54a0-3c26-11e7-8759-030f3090d62b.PNG)

### What version of bitcoin-core are you using?
0.14.0

### Machine specs:
- OS: Microsoft Windows 10 Pro (Windows 10)
- CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz, 3201 Mhz, 6 Core(s), 12 Logical Processor(s)
- RAM: 16 GB
- Disk size: 479 GB
- Disk Type (HD/SDD): I do not know

### Any extra information that might be useful in the debugging process.

**Comment by fanquake** [comment]
Can you provide your debug.log?
Did Bitcoin Core shutdown correctly the last time it was run?

**Comment by Owennnnnn** [comment]
where would i find the debug.log?

and yes

**Comment by fanquake** [comment]
On Windows, the debug.log should be in this directory: C:\Users\YourUserName\Appdata\Roaming\Bitcoin

**Comment by Owennnnnn** [comment]
[debug.zip](https://github.com/bitcoin/bitcoin/files/1015965/debug.zip)
It is zipped because I could not upload it as debug.log

**Comment by jonasschnelli** [comment]
@Owennnnnn: you have a data corruption in your level db database:

```
2017-05-19 04:41:49 GUI: PaymentServer::LoadRootCAs: Loaded  51  root certificates
2017-05-19 04:41:50 UpdateTip: new best=0000000000000000005d8827700258e29d6523b8ae29e088fde47613c39d6925 height=465321 version=0x20000002 log2_work=86.395183 tx=220074984 date='2017-05-07 20:46:10' progress=0.985965 cache=11.6MiB(11412tx)
2017-05-19 04:41:50 LevelDB read failure: Corruption: block checksum mismatch
```

Make sure you are not using network file storage and try to sync again (remove everything from the data-dir expect your wallet.dat).

**Comment by Owennnnnn** [comment]
I think it  worked but its still synchonizing with the network.
