### ISSUE TITLE
Update maxmempool at runtime

### ISSUE THREAD

**Issue by shivaenigma** [bitcoin/bitcoin#10435]
It would be good to increase/decrease maxmempool without restarting bitcoind. The issue right now is that after restarting the node, it again takes half a day to catch up with all the currrent unconfirmed transactions. There seems to be no way to restart and quickly getting back the unconfirmed tx list.

Many times the webmaster wants to tweak maxmempool to handle memory issues.

**Comment by paveljanik** [comment]
Eh? We are dumping mempool at shutdown and loading it again at the start...

**Comment by jnewbery** [comment]
@shivaenigma what version of bitcoind are you running? Since v0.14.0, mempool is stored to disk on shutdown and reloaded on startup. If you're stop-starting the bitcoind client you don't need to wait half a day to catch up with unconfirmed transactions.

This was added in #8448

**Comment by shivaenigma** [comment]
@jnewbery I am on 0.13 . This is exactly what I needed. Thanks a lot
Closing in favour of  #8448
