### ISSUE TITLE
Problems with command-line options silently ignored

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#1044]
In this case, the **rpcport** argument is silently ignored:

```
-testnet -nolisten -server -connect 192.168.1.11 -rpcport=12345
```

However, when adding a = after connect, it works, i.e.

```
-testnet -nolisten -server -connect=192.168.1.11 -rpcport=12345
```

It could be that the first is simply wrong; in that case, it should probably show an error message.

**Comment by laanwj** [comment]
Other long-term improvements to option parsing would be:

- Type-safe argument parsing. Prevent issues where arguments are assigned to signed integer types in one place and unsigned in other place. Same issue with different sizes (32 versus 64).
- Parse arguments once, in initialization. There is no need to parse arguments from string every time they are used, which tends to happen now.

**Comment by MarcoFalke** [comment]
Also unknown (=deprecated) params should be detected.

Links to https://github.com/bitcoin/bitcoin/pull/4194#issuecomment-44521490

**Comment by jtimon** [comment]
It would be also nice if all the glohal initializations were in init.o (obviously  not for bitcoin-tx) and getArg () [which internally uses the global argsMap] wasn't call from all over the place (and new places when we introduce new functionality but are too lazy to properly implement the new command line options or is not a priority  to o things right(tm) (ie like in the case of the mempool limit ).

**Comment by promag** [comment]
Similar #11819.

**Comment by MeshCollider** [comment]
FYI I've been working on this for a while, hope to have a PR up soon
