### ISSUE TITLE
osx make deploy error

### ISSUE THREAD

**Issue by out0fmemory** [bitcoin/bitcoin#10453]
i meet error when "make deploy" on mac 2015 early,the error msg is below

$ make deploy
make -C src qt/litecoin-qt
make[1]: Entering directory '/Volumes/sd_card/git_project/litecoin/src'
  OBJCXXLD qt/litecoin-qt
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:3407: qt/litecoin-qt] Error 1
make[1]: Leaving directory '/Volumes/sd_card/git_project/litecoin/src'
make: *** [Makefile:1185: src/qt/litecoin-qt] Error 2

**Comment by paveljanik** [comment]
We do not compile `litecoin-qt`, wrong project probably.

Please close this.

**Comment by out0fmemory** [comment]
but of course the litecoin is forked from bitcoin, And bitcoin project is active then litecoin, so i open this issues here

**Comment by jonasschnelli** [comment]
Seems to be a local issue. Maybe cross compile problem (sd_card?).

Please open this issue at the litecoin issue tracker.
We have recently change the mac make deploy procedure.
Closing

**Comment by out0fmemory** [comment]
thank you
i use a sd_card in my MBP formated with osx file system,and i resolve the problem：the ./configure need add --with-gui pram,because --without-gui is default. And then i find that the litecoin project does not sync the bug-fix to it, such as this fix [https://github.com/bitcoin/bitcoin/pull/9412/files](url)

#  **And i recommend that the build doc explain the -gui param's default value**
