### ISSUE TITLE
bitcoin core pending deposit issue

### ISSUE THREAD

**Issue by mrmarvelous** [bitcoin/bitcoin#10456]
i made a order for .15btc and it went to pending in my wallet and stayed there for over a day with no confirmations. Then i restarted computer and now there is nothing showing in pending..but its still listed as unconfirmed transaction in blockchain.. Could i have lost my coins by doin a reboot..or should they still arrive in my wallet..this was 2 days ago now

### Expected behaviour
usually when i order coins they go directly to pending and after about a 30-60mins they start gettin confirmations1/6 etc

### Actual behaviour
coins stuck in pending over 24 hours...did a restart and now coins not in pending

### What version of bitcoin-core are you using?
v0.13.1 64bit
### Machine specs:
- OS:win7
- CPU:I5 intel
- RAM:6gbddr3
- Disk size:1tb
- Disk Type (HD/SDD):hd

**Comment by jonasschnelli** [comment]
The sender has probably chosen a low fee which may take up to a couple of days until it gets confirmed (or it may never confirm).
However, this is not a development issue and should therefore be posten somewhere else.
Closing.
