### ISSUE TITLE
Transaction stuck

### ISSUE THREAD

**Issue by EddieOne** [bitcoin/bitcoin#10465]
I sent a transaction with a low fee. I'm trying to resend the transaction but I get an error. `258: txn-mempool-conflict`. Is there no way to get a transaction out of the mempool? How long should I wait?

**Comment by jonasschnelli** [comment]
This question doesn't belong here. Please use https://bitcoin.stackexchange.com or similar for such questions.

Did you signal RBF in the transaction? If so, use the "bumpfee" RPC command.
Maybe try to use CPFP (Use GUI Coin-control to RPC rawtx* interface to spend the change output of the stuck transaction in a high fee transaction).

**Comment by EddieOne** [comment]
ok thanks, I will try the RBF signal.

I would suggest nodes not accept low fee transactions when there is a excessive amount of unconfirmed transactions. There was 200k at the time. I would assume for most situations, paying a higher fee is better than losing control of funds.

**Comment by jonasschnelli** [comment]
RBF can't be done *after* broadcasting a low fee transaction.
If you want to bump an existing low-fee transaction that does not already signal RBF, then you should use child-pays-for-parent (CPFP) by creating a high-fee-transaction with the change-output of the "stuck transaction" as input for the new transaction.

**Comment by jonasschnelli** [comment]
Closing
