### ISSUE TITLE
i cant compile the bitcoin source

### ISSUE THREAD

**Issue by zhiyan114** [bitcoin/bitcoin#10472]
### Describe the issue
when i compile it shows a error that i don't know why

### Expected behaviour
https://pastebin.com/RzcRv466
error

### Actual behaviour
It should compile

### What version of bitcoin-core are you using?
latest

### Machine specs:
- OS: Linux 14.XX.X
- CPU: 8 cores
- RAM: 1 GB
- Disk size: 200 GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by sipa** [comment]
The compiler almost certainly just ran out of memory. See the build instructions for how to compile in low memory situations.

**Comment by zhiyan114** [comment]
so i need a higher memory to run it?

**Comment by sipa** [comment]
Try following the instructions here: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#memory-requirements

**Comment by zhiyan114** [comment]
so change the heapsize correct?

**Comment by sipa** [comment]
There's no way you're going to run a node with 512 MB RAM.
