### ISSUE TITLE
Перегрузка сети bitcoin 

### ISSUE THREAD

**Issue by 3315151515** [bitcoin/bitcoin#10487]
https://forum.bits.media/index.php?/topic/38912-bitkoin-na-pike-ili-zakat-blizok/
Выросли комиссии , ожидание подтверждения по 3 дня , и биткоин догоняет мутный для меня эфириум, голосовать должны все узлы , а не только майнеры (например которые часто активные и более менее старые) ,
в кошельке программе нет (надо) удаление адресов лишник , при удаление программы должно предлагать удалить не вседа нужный блокчейн и файл с кошельком (а также написать предостирежение о потери денег) и далее предложить сохранить файл кошелек и загрузить через программу обратно, в программе надо настроку о желаемом количестве предоставление места под блокчейн,  
(моя не оформивщаяся до конца мысль ниже)
и еще биткоин должен в будущем выполнять 1 000 000 000 000 в секунду (а то обещали оплату в реальном времени например нефти за кубометр), для ускорения надо что то вроде (асинхронных параллельных мини блокчейнов/нод в блокчейне хз, и что то типо замена майнерам когда нет (в которых выгодня только гона мощности и прибыли а не поддержани и масштабирования сети) пулов (а достаточно клиента чтобы обрабатывать и зарабатывать биткоин , чтобы клиент жрал 1-10 %  мало короче для поддержания сети по умолчанию и мог зарабатывать и были настроки для прибавления мощности разных процессоров и памяти , чтобы не все мощности сети тратились на поиск блока а достаточная часть , остальное дублировало копии блокчейнов которые обрабатывали бы дополнительные транзакции и потом канть синхронизировались с основой , чтобы блокчейны размазывались по клиентам) дадеюсь мою мысль понели, что биткоин с клиентом каждый должен выполнять роль майнера (как основному так и) асинхронно(сами как придумаете ) основному блокчену дополнительно , содержать часть соседского блокчейна и все это должно автоматически масштабироваться и синхронизироваться в клиентах.

**Comment by jonasschnelli** [comment]
The project language is English. Please avoid any other language.
