### ISSUE TITLE
GUI unresponsive during slow operations

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#10504]
As mentioned https://botbot.me/freenode/bitcoin-core-dev/msg/83983170/, in Qt making slow or blocking calls in the event loop thread makes the user interface nonresponsive. Keyboard and mouse events are not processed and the display is not updated. There are different places in the code where this can happen, so this github issue is intended to be an umbrella issue to figure out a general strategy for turning synchronous calls into asynchronous ones and dealing with the problem.

# Background

In Qt, there are two different ways to keep the event thread responsive when handling an event that triggers an asynchronous operation:

1. Return from the event handler right away after starting the operation (usually in some worker thread) so the main event loop can keep processing events.
2. Run a [nested event loop](https://doc.qt.io/archives/qq/qq27-responsive-guis.html#waitinginalocaleventloop) in the event handling function in parallel with the asynchronous operation.

Approach 1 requires using a using continuation style of programming that works best when an event only needs to trigger a single operation and UI update.

Approach 2 can be more convenient when handling events that do more than trigger a single slow operation followed by a UI update. It can be a lot easier to implement than approach 1 in existing code, where separating all the slow operations from the ui updates could require rewriting control flow.

Approach 2 doesn't work well when the user interface needs to support multiple async operations running in parallel. (For example if there are two buttons that both trigger async operations with nested event loops followed by UI updates, and you click the first button then the second button before the first operation completes, then the first ui update will be blocked until after the second nested loop exits even if the first operation completes first.)

# Strategies for improvement

Given choices between returning to the main event loop or using nested loops, different strategies are possible for making slow synchronous operations asynchronous and making the GUI more responsive:

1. Rewriting all blocking operations in the event thread in continuation style, never blocking in any event handler, and always returning immediately to the main event loop. This is pretty easy to do in new code, but would require rewriting a lot of existing code.

2. Making a helper function using a nested event loop and a worker thread that would allow blocking code in event handlers to be easily replaced by asynchronous code, without having to change control flow. E.g. a `DoAsync` function that allows mechanically replacing code like:

```
ResultType result = SomeSlowOperation();
widget->updateState(result);
```

with:

```
ResultType result = DoAsync([&]() { return SomeSlowOperation(); });
widget->updateState(result);
```

3. Running nested event loops as part of the framework introduced by #10244, using the approach described in https://github.com/bitcoin/bitcoin/pull/10102#issuecomment-294094610. This would allow code in Qt that appears to be blocking just transparently handle events in the background.

Regardless of which of the above strategies are used, it could make sense to use the #10244 refactoring as a starting point because it makes blocking calls in Qt code easy to identify (they all happen through m_node / m_wallet accesses), and in a few places it combines scattered operations into single calls.

**Comment by ryanofsky** [comment]
IRC discussion yesterday: https://botbot.me/freenode/bitcoin-core-dev/msg/87282208/. Jonas mentioned later there is blocking calling sendtoaddress after generate (https://botbot.me/freenode/bitcoin-core-dev/msg/87296576/). And there was just a bug report of ui lag during syncing on windows: https://github.com/bitcoin/bitcoin/issues/10610

**Comment by ryanofsky** [comment]
This stackoverflow question: https://stackoverflow.com/questions/15097861/qt-measure-event-handling-time has sample code for measuring time it takes to process Qt events. We could adopt it and log events that take longer than a certain amount of time to be processed to get a better idea of where there are and aren't problems with blocking.

**Comment by ryanofsky** [comment]
Some more talk about switching to async operations in GUI here: https://botbot.me/freenode/bitcoin-core-dev/msg/94385934/

**Comment by Sjors** [comment]
The latest multiwallet action is at  #11383 & #12610. Dynamic wallet loading WIP at #10740.

**Comment by promag** [comment]
I think the only valid approach is run blocking code in a different thread.

**Comment by promag** [comment]
@ryanofsky I mean that nested even loop are pointless here. Do you think otherwise?

**Comment by ryanofsky** [comment]
> nested even loops are pointless here. Do you think otherwise?

Not if they make the gui more responsive and can be implemented with no changes to existing GUI code as described. In general I tend to think it's better if GUI just to respond to events and make asynchronous requests, but we've had this discussion before (https://github.com/bitcoin/bitcoin/pull/15153#discussion_r249851732). It's all good.

**Comment by laanwj** [comment]
Though they can be useful, one thing to be careful with with nested event loops: in the past we had an issue where a pointer to a stack-local object from the inner loop stayed around after escaping to the global event loop, inside Qt, through some very unexpected mechanism. See e.g. http://jblog.andbit.net/2006/10/24/nested-eventloops/

**Comment by promag** [comment]
@laanwj are you referring to #15310?

**Comment by laanwj** [comment]
@promag something much longer ago, but I guess that one's similar.

**Comment by kord1e** [comment]
Latest git revision, it's so unresponsive during intensive operations that it quickly becomes annoying.
