### ISSUE TITLE
make on mac failing

### ISSUE THREAD

**Issue by Benudek** [bitcoin/bitcoin#10507]
Hi there, trying to follow the instructions here https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md

on my MAC and running into an issue with 'make': 
(1) produces several errors (some below), one might be related to Qt. 
(2) when configuring without GUI can make but the tests fail.

--------------------------------------------------------------
--------------------------------------------------------------
--------------------------------------------------------------
Make after ./configure
--------------------------------------------------------------
--------------------------------------------------------------
--------------------------------------------------------------

  GEN      qt/rpcconsole.moc
  CXX      qt/qt_bitcoin_qt-bitcoin.o
In file included from qt/bitcoin.cpp:260:
./qt/bitcoin.moc:13:2: error: "This file was generated using the moc from 5.6.2.
      It"
#error "This file was generated using the moc from 5.6.2. It"
 ^
./qt/bitcoin.moc:14:2: error: "cannot be used with the include files from this
      version of Qt."
#error "cannot be used with the include files from this version of Qt."
 ^
./qt/bitcoin.moc:15:2: error: "(The moc has changed too much.)"
#error "(The moc has changed too much.)"
 ^
./qt/bitcoin.moc:20:5: error: unknown type name 'QByteArrayData'; did you mean
      'QByteArray'?
    QByteArrayData data[9];
    ^~~~~~~~~~~~~~
    QByteArray
./qt/paymentserver.h:47:7: note: 'QByteArray' declared here
class QByteArray;
      ^
In file included from qt/bitcoin.cpp:260:
./qt/bitcoin.moc:30:1: error: unknown type name 'QByteArrayData'; did you mean
      'QByteArray'?
QT_MOC_LITERAL(0, 0, 11), // "BitcoinCore"
^
... fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [qt/qt_bitcoin_qt-bitcoin.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
bherudek-ltm:bitcoin bherudek$

**Comment by paveljanik** [comment]
You probably have more Qts installed and `moc` from 5.6.2 is in your PATH before `moc` from Qt actually used. What configure arguments have you used? What PATH do you have?

**Comment by Benudek** [comment]
let me check the path, thx Pavel !

**Comment by fanquake** [comment]
@Benudek Did you figure out the problem here? Can you close this if the issue was Qt misconfiguration.

**Comment by fanquake** [comment]
Going to close this. Please re-open if your still having an issue, and there are no Qt conflicts.
