### ISSUE TITLE
missing bitcoin

### ISSUE THREAD

**Issue by maveric7911** [bitcoin/bitcoin#10510]
My last transaction was -0.1BTC with the previous transaction being +1.03. However it shows available, pending and total at 0.0. What happened to my BTC?

**Comment by Leviathn** [comment]
Can you post any specific Txids?

**Comment by gabrieldov** [comment]
Hard to help you if you don't provide any additional info.

**Comment by laanwj** [comment]
As replied by previous posters, it is impossible to troubleshoot this without further information.
You've completely ignored the issue template as well. So I'm closing this issue.
