### ISSUE TITLE
How can we use API qt btc with C#?

### ISSUE THREAD

**Issue by 30amak** [bitcoin/bitcoin#10528]
Hello.
We like to connect our website to btc wallet qt.
How can we use API qt btc with C#?
Best Regards.

**Comment by NicolasDorier** [comment]
This is not the right repository for such question. For using Bitcoin RPC you need to use [NBitcoin](https://github.com/MetacoSA/NBitcoin). Read [this book](https://www.gitbook.com/book/programmingblockchain/programmingblockchain/details) for knowing more about Bitcoin programming in C#.  And come on [this chat](https://gitter.im/MetacoSA/NBitcoin) to ask questions.

**Comment by MarcoFalke** [comment]
Looks like the question was answered.
