### ISSUE TITLE
estimaterawfee 50  not returning a value

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#10525]
Running master:

```
 bitcoin-cli estimatesmartfee 50
{
  "feerate": 0.00241213,
  "blocks": 50
}
```

but trying to use estimaterawfee:
```
bitcoin-cli estimaterawfee 50
{
  "feerate": -1,
  "decay": 1.023300286635292e-312,
  "scale": -1997275853,
  "pass": {
    "startrange": -1,
    "endrange": -1,
    "withintarget": 0,
    "totalconfirmed": 0,
    "inmempool": 0,
    "leftmempool": 0
  },
  "fail": {
    "startrange": -1,
    "endrange": -1,
    "withintarget": 0,
    "totalconfirmed": 0,
    "inmempool": 0,
    "leftmempool": 0
  }
}
```

estimaterawfee 50 doesn't appear to be working with any threshold or horizon .

estimaterawfee 48 seems to work, but 49 and above stop (I tried using long horizon too).

estimatesmartfee on the other hand seems to be working up until 1008

@morcos

**Comment by morcos** [comment]
Is this how you tried estimaterawfee for 50?
`estimaterawfee 50 0.95 2` ?

For targets 49 and higher you have to use the long time horizon.

**Comment by RHavar** [comment]
Hm, it's working now. I guess the problem is that it probably hadn't collected enough data? (Or I'm an idiot?) I guess I'll close the issue

**Comment by RHavar** [comment]
@morcos sorry, I apologize. The fault is 100% mine. Looking at my tests, when I was checking for a long threshold, I was actually passing it as a target. Sorry ><
