### ISSUE TITLE
Problem with Transaction

### ISSUE THREAD

**Issue by Frankoxz** [bitcoin/bitcoin#10567]
### Hello, I made a transaction but by mistake I put only 0.1 tax, I want to cancel the sending of bitcoin but BitCoin Core will not let me cancel the transaction I dont know why.

How Can I cancel the transaction?

Thanks!

### Screenshots.

![sin titulo](https://user-images.githubusercontent.com/4790376/26972880-a684810a-4ce1-11e7-8ca6-c0b78668aa6e.png)

### What version of bitcoin-core are you using?
Bitcoin Core versión v0.13.0 (64-bit)

### Machine specs:
- OS: Win 8.1
- CPU: Intel i7 2.4 / 3.4 Ghz
- RAM:8 GB
- Disk size: 1 TB
- Disk Type (HD/SDD): HD

**Comment by TheBlueMatt** [comment]
There is no such thing as abandoning a transaction in Bitcoin, once its created, it could be confirmed by a miner at any point, however, if you wish to cancel a transaction, you can manually double spend it and create a conflicting transaction with a higher fee, which, if mined, would make it impossible to confirm the previous one. There are lots of guides on manually double spending a transaction in Core if you look around for them.

(The abandon option is only available if the transaction created doesn't even make it into your own mempool, which is usually a good indication that the rest of the network also doesnt see the transaction).
