### ISSUE TITLE
error reading from database

### ISSUE THREAD

**Issue by koalana** [bitcoin/bitcoin#10576]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. run bitcoin core wallet
2. at 4029 blocks left to sync I receive the following message
error reading from database.
3. the same thing happens when I restart and the program tries to sync.

### Expected behaviour
it should complete the sync and allow me to access and operate the wallet

### Actual behaviour
it stops at 4029 blocks left to sync and shuts down

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
latest

### Machine specs:
- OS: win10
- CPU:i7 5820
- RAM:8
- Disk size:1 Tera
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by jonasschnelli** [comment]
Seems like you face disk corruptions.
Can you post your debug log somewhere?
Have you tried a hard disk and or memory test?

**Comment by koalana** [comment]
error seemed to occur on receiving transaction.
Transaction will not confirm'
Just ran defrag.
Do not know what else to do.

Gordon

**Comment by koalana** [comment]
[mebug.txt](https://github.com/bitcoin/bitcoin/files/1071195/mebug.txt)

**Comment by koalana** [comment]
please review file and assist.

**Comment by MarcoFalke** [comment]
You might want to check your hardware for defects: Cf. https://bitcoin.stackexchange.com/a/12206

**Comment by koalana** [comment]
its all working BUT
The last transaction is stuck unconfirmed
any ideas?

**Comment by jli225** [comment]
This repository has been hijacked by Wladimir J. van der Laan and his Blockstream ally.

If you want to contribute to Bitcoin, please come to github.com/btc1/bitcoin

**Comment by MarcoFalke** [comment]
> its all working BUT

Though, you mentioned that your problem was "it stops at 4029 blocks left to sync and shuts down". If this is solved, please close this issue.
