### ISSUE TITLE
Access to longer fee estimates using GUI

### ISSUE THREAD

**Issue by morcos** [bitcoin/bitcoin#10590]
0.15 supports fee estimates up to 1008 blocks
It would be great if someone could add support for this to the GUI with a redesign of the slider.
My recommendation was just to make the slider have discrete values such as:
2, 4, 6, 12, 24, 48, 144, 504, 1008

Do we really need more fee choices than that?
But perhaps someone with more QT expertise could whip it up faster than me

**Comment by morcos** [comment]
ping @jonasschnelli   :wink:

**Comment by lichtamberg** [comment]
Wouldn't it be more user friendly to select the desired time frame?
~20 minutes, ~40 minutes, ... ~3,5 days, ~1 week?

**Comment by jonasschnelli** [comment]
@lichtamberg: the GUI already shows "time/blocks"

**Comment by jonasschnelli** [comment]
Brainstorming:
* Not sure if we want to expose targets of 144, 504, 1008 already in the GUI. Would it make sense to hide them behind an (expert)option?
* Would a dropdown instead of a slider makes it more clear that it's non-linear (the dropdown could also include the absolute fee if the transaction details are provided)

**Comment by morcos** [comment]
No opinion on dropdown vs slider, but I do like the slider now.

Why wouldn't we want to expose the longer horizon targets?
Why should those be an expert option?
Perhaps we should more clearly display on the slider that those are slow values (change color or include some additional text or something), but I think the whole point is to give users those cheaper options.

**Comment by jli225** [comment]
This repo was hijacked by Vladimir and his Blockstream ally. 

The whole Bitcoin community has stood up. This typo will become obsolete inevitably.

Welcome to the new reference client supported by the majority: https://github.com/btc1/bitcoin

**Comment by TheBlueMatt** [comment]
This can be closed, no?

**Comment by morcos** [comment]
Fixed by #10769
