### ISSUE TITLE
QA: Document our preferred test writing style

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#10601]
When writing a new test, I often ask myself what the best existing test we have is, so that I can mimic the style and usage of the various test_framework components, especially as we re-work the test_framework and create new preferred idioms.

So I think it'd be great to update the docs in test/functional/README.md to have a sample short test, with lots of comments, that people can look to when writing a test from scratch.

**Comment by jnewbery** [comment]
Addressed in #10612. Any feedback welcomed!
