### ISSUE TITLE
Segwit/Scaling and Core Developer Consensus

### ISSUE THREAD

**Issue by spencerlievens** [bitcoin/bitcoin#10606]
I believe this is an issue which should be opened here as this is where the developers are situated.

Should SegWit be activated or not? Are the media misinforming the public when saying that Bitcoin Core developers are not in favour of it being activated?

I, personally, am in favour of at least a block size increase of 4MB & "SegWit" activation, I have committed code to Bitcoin and I am interested in what others have to say, I believe the public are too.

**Comment by laudaa** [comment]
This isn't the place for this. Check this page out anyways: https://en.bitcoin.it/wiki/Segwit_support

**Comment by sipa** [comment]
Of course SegWit should be activated. Who the hell is claiming that?

The means through which is a political question that's off topic here.

**Comment by spencerlievens** [comment]
@sipa please don't close this 'Issue' as this IS the place all developers come to that are involved in Bitcoin Core development. This I believe really needs to be heard, even the fact you have instantly said that it does need activating will instantly make a difference to the public. Media are dangerous and this sort of public, transparent conversation, about an 'Issue' with Bitcoin is really needed. SegWit and Scaling are serious issues that are being addressed, but only being reported by media, we can change that by simply leaving this 'Issue' open.

**Comment by sipa** [comment]
@spencerlievens I'm sorry, but this venue is for discussion software development. Please respect that not everyone wants to be involved in politics.

**Comment by spencerlievens** [comment]
@sipa there is irony here however, decentralised project, centralised control of GitHub, I cannot close nor open this issue, but you can, the issue of decentralised development is true.
