### ISSUE TITLE
Windows bitcoin-qt Verry laggy while syncing Blocks [0.14.1]

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#10610]
If I sync Blocks in the Bitcoin-QT Wallet V. 0.14.1 It's very laggy.
The Wallet sometimes is not responding if I click on a Transaction while downloading Blocks or something it says "Bitcoin Core - Wallet [not responding]" on Windows, so the Wallet stucks every time.

In earlier Version I never get this Issues.
If the Wallet has finished with syncing Blocks, It's working but while it's syncing its very very laggy.

Pls fix that.

**Comment by ryanofsky** [comment]
Probably relates to #10504.

**Comment by globaltoken** [comment]
Thanks for the fast referrene and and your fast answer :) 👍

**Comment by jonasschnelli** [comment]
@globaltoken If you are willing to try, you could run master + #10251 (https://bitcoin.jonasschnelli.ch/build/179) and see if its better...

**Comment by fanquake** [comment]
Going to close in favour of #10504, which has a lot more discussion.
