### ISSUE TITLE
Bitcoin core is draining storage on my Mac

### ISSUE THREAD

**Issue by Tokyonomaku** [bitcoin/bitcoin#10617]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using? Latest one
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:

Sierra
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by paveljanik** [comment]
WORKSASDESIGNED. Please close this issue.

**Comment by Tokyonomaku** [comment]
Why? No one has a fix.

**Comment by MarcoFalke** [comment]
Usually, you don't need to keep historic blocks on disk. You can set a
prune target to delete such historic blocks.

Cf. https://bitcoin.stackexchange.com/a/38847

On Sat, Jun 17, 2017 at 3:30 PM, Mark Featherstone <notifications@github.com

**Comment by Tokyonomaku** [comment]
Okay. Thanks. Where do I access the files to input the pruning agent and no connect functions?

**Comment by MarcoFalke** [comment]
The location of bitcoin.conf depends on your operating system and you might
have to create the file if it does not exist. Cf.
https://bitcoin.stackexchange.com/a/11210

Append the line without the leading dash:

prune=550

On Sat, Jun 17, 2017 at 4:08 PM, Mark Featherstone <notifications@github.com

**Comment by Tokyonomaku** [comment]
Okay. Thanks. Will do.

**Comment by jonasschnelli** [comment]
Closing. Works as intended.
