### ISSUE TITLE
bitcoin-14 + ‘mutex’ in namespace ‘std’ does not name a type

### ISSUE THREAD

**Issue by KingfisherTao** [bitcoin/bitcoin#10624]
Ok When i make the bitcoin (ver 14.0 14.1 14.2) 
An error has occurred
'mutex' in namespace 'std' does not name a type 

I building it in Windows10 Subsystem for Linux 
My Gcc and G++ version is 5.4.0 and I'm sure this version support C++11. I find the same issues in the Internet but the other people's answer can't solve my problem. 
So, I don't know what to do, please help me, thank you.

When i make "libbitcoin_server_a-httprpc.o"
./support/lockedpool.h 195: error: 'mutex' in namespace 'std' does not name a type 

- OS:    windows 10 
- CPU:  i7-6800k
- RAM: 16G

**Comment by achow101** [comment]
Are you cross compiling with mingw or just building it for linux? If you are cross compiling, it will not work, see https://github.com/bitcoin/bitcoin/projects/1 for the issues about that.

**Comment by KingfisherTao** [comment]
Tank you @achow101
