### ISSUE TITLE
'make deploy' fails on OSX 10.12.5

### ISSUE THREAD

**Issue by dwasyluk** [bitcoin/bitcoin#10620]
Trying to compile Bitcoin on a new machine and followed the usual steps at https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md. `make` works fine but when `make deploy` is attempted it fails with the following error:

```
$ make deploy
build-aux/install-sh -c -d Bitcoin-Qt.app/Contents
build-aux/install-sh -c -d Bitcoin-Qt.app/Contents/Resources
build-aux/install-sh -c -d Bitcoin-Qt.app/Contents/Resources
/usr/bin/install -c -m 644 src/qt/res/icons/bitcoin.icns Bitcoin-Qt.app/Contents/Resources/bitcoin.icns
build-aux/install-sh -c -d Bitcoin-Qt.app/Contents
/usr/bin/install -c -m 644 share/qt/Info.plist Bitcoin-Qt.app/Contents/Info.plist
/Library/Developer/CommandLineTools/usr/bin/make -C src qt/bitcoin-qt
  OBJCXXLD qt/bitcoin-qt
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/bitcoin-qt] Error 1
make: *** [src/qt/bitcoin-qt] Error 2
```

Not entirely sure how to address this, any help is much appreciated!

**Comment by jonasschnelli** [comment]
Make deploy works fine on my OSX 10.12 machine.
Idea: do you have Qt installed (`brew install qt5`)?
If so, can you post `debug.log`

Does `make` compile `qt/bitcoin-qt`?

**Comment by dwasyluk** [comment]
Already have qt5 installed via brew 👍 I'm seeing `Bitcoin-Qt` in the root folder after `make deploy` but its attributed as an invalid application (question mark icon) and its only 922Kb and cannot be run. Since I can't actually execute the built .app I can't provide any `debug.log` output unless maybe there's a flag I can pass to the compiler for more info?

**Comment by jonasschnelli** [comment]
Argh. Mean `config.log`.
Make pastbin that and the output of a plain `make`.

**Comment by dwasyluk** [comment]
Aha that I can do :) https://pastebin.com/PZ5UqgLq

**Comment by jonasschnelli** [comment]
config.log looks okay.
Can you post the output of a `make V=1`?

**Comment by dwasyluk** [comment]
`make V=1` doesn't output much since it executes without issue (`nothing to be done`).`make deploy V=1` included some more output:

```
$ make deploy V=1
/Library/Developer/CommandLineTools/usr/bin/make -C src qt/bitcoin-qt
/bin/sh ../libtool    --mode=link g++ -std=c++11  -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -Wno-implicit-fallthrough  -Wl,-headerpad_max_install_names -Wl,-dead_strip -o qt/bitcoin-qt   -L/usr/local/opt/berkeley-db@4/lib
libtool: link: g++ -std=c++11 -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register -Wno-implicit-fallthrough -Wl,-headerpad_max_install_names -Wl,-dead_strip -o qt/bitcoin-qt -Wl,-bind_at_load  -L/usr/local/opt/berkeley-db@4/lib
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/bitcoin-qt] Error 1
make: *** [src/qt/bitcoin-qt] Error 2
```

If you'd like me to `make clean` and then `make V=1` just let me know.

**Comment by dwasyluk** [comment]
Still really struggling with this, forcing me to use my older machine to put together .app releases. Is there any further info I could provide to assist in debugging this? TIA!

**Comment by fanquake** [comment]
@dwasyluk Can you still reproduce this? I can't using https://github.com/bitcoin/bitcoin/commit/0e707919f596c80056bca295abd71543ccae4956 and OS X 10.12.6.

**Comment by Empact** [comment]
@dwasyluk Good for me on 62fdf9b07087b80d2142799bdd2324f61483359d and OS X 10.12.6

**Comment by fanquake** [comment]
Closing, please re-open if this is still an issue.
