### ISSUE TITLE
globaltoken wallet reseted after few hours

### ISSUE THREAD

**Issue by gawaynX** [bitcoin/bitcoin#10641]
@globaltoken  iam new here,  i downloaded my globaltoken wallet from github yesterday and deposited coins. a few hours later the wallet reseted (downloaded files again)  and my coins were away. I need help. 
who can i speak to? thanks
this was my glt adress GQqh5tm8jLrte3ZHNyJm58bmBN8eFMmchp

**Comment by globaltoken** [comment]
Post your Wallet .log

**Comment by achow101** [comment]
@gawaynX This repo is for Bitcoin Core, not whatever altcoin you are asking about. Please take your discussion elsewhere as it is off topic for this repo.
