### ISSUE TITLE
importprivkey found bitcoins even with rescan set to false

### ISSUE THREAD

**Issue by FrozenPrincess** [bitcoin/bitcoin#10666]
I imported a private key to a funded address with `importprivkey {privateKey} "" false` expecting that the wallet would only know about future transactions to this address. However it immediately found the funds (which had 4 confirmations), despite rescan set to false. My expectation was that it would only find funds for future transactions. Looking at the source code I can't see how this would happen and how many blocks it actually does scan back.

I'm not sure if the current behavior is intended or not, but it could be made a lot more clear

**Comment by laanwj** [comment]
Did it do a rescan?
(hard to miss, your node would hang for some time and it prints to debug.log)

**Comment by FrozenPrincess** [comment]
Yeah, there was no rescan. I am able to reproduce by:

Create an address on bitaddress.org
Send some bitcoin to that address
Wait until the bitcoin have got a couple of confirmations
Check the balance
Import private key with false set for rescan
Check the balance (it found it)

**Comment by FrozenPrincess** [comment]
I'm also totally sure I didn't run with rescan, because if I try:

`Rescan is disabled in pruned mode (code -4)`

**Comment by underst00d** [comment]
i thought this is how it works as we used to set `rescan=false` when doing `importprivkeys` to save lots of time and notifications. we were able to see the coins associated with the imported privkeys instantly.

but, we just tried again using 0.14.1 and it's no longer working. The call returned w/o an error but the coins did not show up, and `validateaddress` did not even list the address as mine. Repeating the same `importprivkey` with `rescan=true` had no effect.

What happened? What's the proper way of importing privkeys with coins in them? Really don't want the rescan as it takes too long to run and fires out duplicate notifications. Thanks

**Comment by achow101** [comment]
> we were able to see the coins associated with the imported privkeys instantly.

What made you think that would happen? The wallet only knows about your coins if it rescans the blockchain. If you don't have it rescan, then it won't know about any of your coins.

> The call returned w/o an error but the coins did not show up

As is expected.

> repeating the same `importprivkey` with `rescan=true` had no effect.

What exactly is the command you are running?

**Comment by underst00d** [comment]
i did it a few months ago (or more than 1 year) and i'm very sure the coins showed up. cannot remember the exact version number though.

ok then why `validateaddress` shows `ismine` as false after an error-free privkey import?

`bitcoin-cli importprivkey <key> "" false`

**Comment by jonasschnelli** [comment]
random though: do you import an HD derived private key that uses the same seed and derivation-path than core does (maybe exported your xpriv via dumpwallet)?

Or: do you have "rescan=1" in your bitcoin.conf?

**Comment by FrozenPrincess** [comment]
> random though: do you import an HD derived private key that uses the same seed and derivation-path than core does (maybe exported your xpriv via dumpwallet)?

No. The issue is [easily reproducible](https://github.com/bitcoin/bitcoin/issues/10666#issuecomment-310855213) with arbitrary addresses  

> Or: do you have "rescan=1" in your bitcoin.conf?

Nope

**Comment by MarcoFalke** [comment]
Transforming your description into a python test, I could not reproduce on current master:

```py
        # clean chain. set up nodes[1] with "-prune=550". Mine 101 blocks on nodes[0]

        address_new = self.nodes[0].getnewaddress()
        self.nodes[0].sendtoaddress(address_new, 0.1)
        self.nodes[0].generate(4)
        self.nodes[1].importprivkey(privkey=self.nodes[0].dumpprivkey(address_new), rescan=False)
        assert self.nodes[1].getbalance() == 0

**Comment by MeshCollider** [comment]
Did you send the coins to the new address from the wallet you are importing into? If so I'd imagine the transaction would already be 'yours' as a sent transaction in the wallet, might be the cause?
