### ISSUE TITLE
I run a full node bitcoin core in a raspberry-pi-like device, the synchronization stop and server gone away after a short time running

### ISSUE THREAD

**Issue by jobsfan** [bitcoin/bitcoin#10664]
Hi dear! I run a full node bitcoin core in a raspberry-pi-like device, the synchronization stop and server gone away after a short time running.

I have a device called cubie board, it is similar to raspberry-pi, a small computer model. with 2G RAM and 8G ROM, and I mount a 350G hard disk as the main folder for bitcoin-core, I download the arm version and run in it.

the first time, I run the software for the synchronization, when the datachain reach around 40G, the server stop for unknown reason. I type ./bitcoind -daemon and start the server again. however it stop, I run the "top" in the termination and watch, the progress of bitcoind just show for a while, and then disappear.

I delete all the data inside the ~./bitcoin folder, and start over. this time, the phenomenon happened again when the datachain size reach around 65G.

I don't know why this happened, And I don't know whether this happened in others computer. I cannot find the answer on the internet, like goole or baidu [a web search engine in China], most of the results I searched via the goole or baidu are how to make money with bitcoin or how to do a wish vestment with bitcoin, very few tech answer about my problem.

So. it is very appreciated if someone can help me with it!!

**Comment by TheBlueMatt** [comment]
Bitcoin Core tends to be pretty good at finding hardware issues, which tends to be a common issue on these types of devices - what does the end of the debug.log file in your bitcoin folder look like?

**Comment by jobsfan** [comment]
2017-06-24 03:34:33 Pre-allocating up to position 0xc00000 in rev00451.dat
2017-06-24 03:34:44 Error: Out of memory. Terminating.

**Comment by MarcoFalke** [comment]
You might want to reduce the memory usage:
https://gist.github.com/laanwj/efe29c7661ce9b6620a7

**Comment by jobsfan** [comment]
Hello MarcoFalke, should I reduce the dbcache size in config file? Ok, I will write the -dbcache=100 into the bitcoin.conf and then report back. Thank you for your efforts!

**Comment by laanwj** [comment]
Seems it has been answered. For next time: these kind of questions are more suited to the bitcoin stack exchange, https://bitcoin.stackexchange.com/.

**Comment by jobsfan** [comment]
Hi MarcoFalke, I come and report back, in these two days, I try different dbcache size in my little device, from 100, 50,30, to 10. I don't think it make sense I have 2G ram, and I just can use 10M of it. And it still unstable even I set dbcache to 10, it run for a while and then quit with error Out of memory. Terminating in the debug.log, what I can do now is to set it to 5? 3? 1?

**Comment by TheBlueMatt** [comment]
Did you also try reducing your connection count and some of the other tips in that document? 0.15 should be much better about dbcache usage, so might help when its available.

**Comment by jobsfan** [comment]
Hi TheBlueMatt, thanks for your reply! I tried to run with 
"./bitcoind -daemon --dbcache=30 --maxconnections=8", hope it is a stable one. The connection count you mean is maxconnection? Thanks again for your efforts

**Comment by sdaftuar** [comment]
Since 0.14.0, unused memory allocated to the mempool (default: 300MB) is shared with the utxo cache, so if you're trying to reduce memory usage you should also try limiting the mempool, with the `-maxmempool` command line argument.

**Comment by laanwj** [comment]
@sdaftuar Thanks, I've also added that to https://gist.github.com/laanwj/efe29c7661ce9b6620a7

**Comment by jobsfan** [comment]
I have tried many params in these days, like 
"./bitcoind -daemon --dbcache=20 --maxconnections=3 --timeout=10000 --par=2 --maxmempool=100"

All the same, it runs for a little while, and then quit with "out of memory" error.
I wana cry!

**Comment by TheBlueMatt** [comment]
Are you running something else on this device? Running out with 2GB of memory seems very strange, lots of people run nodes on hosts with much, much less memory. Otherwise your best bet may be to wait for 0.15.

**Comment by jobsfan** [comment]
Hi TheBlueMatt, I am so sure  that no other services run on  this device. It is a brand-new ubuntu 16.04 server I just built it for bitcoin-core. I install the system, set the network and ssl for connection from a terminator. Then the arm version bitcoin core.

My device is cubieboard truck, it is a raspberry-pi-like device, with 2G RAM, and 8G ROM, I mount a 320G hard disk as the blockchain folder in /opt/bitcoin, and set a soft link to /opt/bitcoin/data from ~./bitcoin folder.

By the way, the 320G hard disk is a combination hard disk, I take the hard disk from a PC, and fixed it into a hard-disk-box. and, a hand-made hard disk!

**Comment by laanwj** [comment]
Maybe add a swap file / partition?

**Comment by TheBlueMatt** [comment]
Can you give the output of "ps auH" or so?

**Comment by jobsfan** [comment]
Hi Lannwj and TheBlueMatt, I have create a swap partition of 2G, and it has been running for a long while. And I will keep watching, Hope this time is works good.

**Comment by jobsfan** [comment]
Hi Lannwj and TheBlueMatt, till now, it runs for almost a whole day, I guess my problem has been fixed! Thank your so much for all your efforts and time!
