### ISSUE TITLE
Total Input/Output issue

### ISSUE THREAD

**Issue by Stasyanz** [bitcoin/bitcoin#10671]
I've sent some btc 0.0753 exactly (tx 561e8afc413aa72a7bd8de9942374e91fac9d8e4094080908c4c828ed1f2fe3f)

but there additional 0.33 were withrawn

These 0.33 are still not back to me

**Comment by laudaa** [comment]
They are at '15qG8zYoGJ5mzGCGuXwUpXc9RpTp8Hd9z5' which is likely to be a change address in your wallet. What seems to be the problem? If you don't see the balance, try doing a rescan.

**Comment by Stasyanz** [comment]
what is rescan? I cant see 0.33 in my wallet. Cant see in blockchain.info too

**Comment by laudaa** [comment]
Are you sure? It seems spent now. https://blockchain.info/tx/3ee4ab1279a14ca62d49110f4c408374e792f9dae4e1668f617ceb9aa8ff027a

Rescan: https://bitcoin.stackexchange.com/questions/1249/how-exactly-does-rescan-work

**Comment by MarcoFalke** [comment]
Unfortunately, Bitcoin Core does not support sharing the wallet.dat file over multiple machines. This might lead to unexpected results or in rare cases to loss of funds if you don't know exactly what you are doing.

Looks like this can be closed.
