### ISSUE TITLE
User agent hasn't been updated

### ISSUE THREAD

**Issue by jli225** [bitcoin/bitcoin#10713]
The beta here is still claiming to simply be "Satoshi" (Bitcoin Client). Vlamidir colluded with Blockstream full-time liars to hijack this repo successfully and refused to return it back to Gavin. The current Core Committee no longer follows Satoshi's vision and they tell lies to defame Satoshi & Gavin & Mike Hearn regularly.

This should be updated so people can more reasonably distinguish between the two.

The current Core Committee has been corrupt completely. Good guys left one after another. Only unashamed clown still stay as a Core Committee member.

Welcome to the new Bitcoin reference client supported by the majority: https://github.com/btc1/bitcoin

**Comment by MarcoFalke** [comment]
Thanks for the kind words.

**Comment by TheBlueMatt** [comment]
@MarkoFalke I believe usually policy is to delete obviously-misinformed-FUD-trolling. No need to close/reply.

**Comment by jli225** [comment]
@TheBlueMatt Thank you for keeping this repo as an echo chamber.
