### ISSUE TITLE
Please curb your Luke-jr from trolling the new Bitcoin reference repo with obviously-misinformed-FUD-trolling. 

### ISSUE THREAD

**Issue by jli225** [bitcoin/bitcoin#10716]
Hi, @laanwj, we all know you colluded with Blockstream to hijack this repo. Although many people asked you to return it back to Gavin, you refused by seeing it as your private property.

Well, the whole Bitcoin community has stood up to create a new Bitcoin reference repo github.com/btc1/bitcoin  Which is supported by hashrate majority, economic majority, and user majority.

Please curb your Luke-jr from spamming lies and propaganda to attack Bitcoin, like this https://github.com/btc1/bitcoin/issues/55

You have been warned.

To test, I submitted a similar post here, and in minutes was it not only closed but also deleted by a Blockstream staff. https://github.com/bitcoin/bitcoin/issues/10713

Curb yourself. Bitcoin is here to stay, with or without hijacked Core.

Enjoy your life in this echo chamber. Anyway, you can't hijack Bitcoin.

**Comment by joshuayabut** [comment]
Conceptual ACK

**Comment by jli225** [comment]
@sipa We know you are also a full-time employer of Blockstream. But it's not okay to close this issue without providing any solution.
