### ISSUE TITLE
Create a default bitcoin.conf in the correct location.

### ISSUE THREAD

**Issue by kek-coin** [bitcoin/bitcoin#10746]
A recurring problem when helping new users getting started with running Bitcoin Core is the config file location; a lot of uncertainty is caused by the config file and the folders it should go in not being created automatically by the installation process.

It does not even have to be the full sample as found in contrib, just having an empty config file (or one with a minimal comment directing people to the sample file) created by default would ease the assisting of users on OSes one is not familiar with, as it would be easier for them to verify that they are putting their OS-agnostic configuration in the correct OS-specific location without some unnecessary trial-and-error.

**Comment by laanwj** [comment]
> not being created automatically by the installation process.

That's because the data directory is not known at the time of the installation process. It's chosen on first run.

> It does not even have to be the full sample as found in contrib, just having an empty config file (or one with a minimal comment directing people to the sample file) created by default 

If you are using the GUI, there's a button in the debug window to open it, also the path of the data directory can be found there.

>  OS-agnostic configuration in the correct OS-specific location without some unnecessary trial-and-error.

Indeed, this part is OS/distro-specific.

There is no requirement that the configuration file is writable (by the user that the daemon runs at) at all. A common setup for system-wide daemons is to put the configuration file somewhere under `/etc/` and specify it using `-conf`. For this reason we don't write to the configuration file from `bitcoind` itself, not even to create it initially.

**Comment by kek-coin** [comment]
@laanwj fair points, would an acceptable solution be to try to create the default config file (including the appropriate directories) if `-conf` is not set if it does not exist and fail gracefully on error?

**Comment by lichtamberg** [comment]
+1 this would really help a lot of people.

**Comment by superquest** [comment]
First time user here trying to run a full node.

Once I finally got everything working and `$ bitcoind -printtoconsole` started spitting out progress, I found myself *wondering what configuration I was using*. The output included the string "Using config file /home/vagrant/.bitcoin/bitcoin.conf". But no such file existed, which was odd.

No idea how to improve, but in my experience this was one of the more confusing parts of running daemon for the first time.

**Comment by cisba** [comment]
As pointed by @laanwj "...the data directory is not known at the time of the installation process. It's chosen on first run".
But isn't this feature the origin of problems? Isn't a choice to be moved in the packages setup process?
If the answer would be yes, then the setup could put also the bitcoin.conf file in the right place.

**Comment by MarcoFalke** [comment]
Related: #14057

**Comment by leishman** [comment]
@MarcoFalke yes, #14057 is the simplest solution to this problem. Creating the default conf file is a bit more complex and will probably have to be merged later.

**Comment by jarolrod** [comment]
Why not just instruct someone to `cp` the example `bitcoin.conf` under `bitcoin/share/examples/` into their data directory. This can be included in the docs somewhere in the appropriate place. Something like the following:

If you would like to configure your bitcoin node, an example `bitcoin.conf` including all possible configuration options is provided. Copy this example into your data directory.

```
cp share/examples/bitcoin.conf ~/my/data/dir/
```

You can now open up the copied file with your favorite text editor and uncomment the options that fit your needs.

**Comment by laanwj** [comment]
I like your suggestion @jarolrod . Having a documented example configuration could be useful. But it would not be good to have another separate source of truth for the option help (more maintenance work, creates a merge "hotspot", documentations can diverge over time).  Could it be generated from the `--help` when installing?

**Comment by josibake** [comment]
@laanwj seems like it would be possible to generate from `--help` using something like the following:

```bash
bitcoind -h | sed -E "s/^[[:space:]]{2}\-/#/" | sed -E "s/^[[:space:]]{7}/# /" | sed '/[=[:space:]]/!s/#.*$/&=1/' > /path/to/example/bitcoin.conf
```
not 100% there (remove a few options like version, conf and add some text that explains it is a config file), but does this seem like a feasible approach? if so, i can finish the sed expression.

also, im not super familiar with make and wasn't sure where to add this expression so that it gets run during `make install`. any pointers?

**Comment by chrisbward** [comment]
What's the most basic conf file I could need? At least someone post that please.... I'm on 22

**Comment by prayank23** [comment]
@chrisbward Try this https://jlopp.github.io/bitcoin-core-config-generator/ and use the drop down on right-top to generate some predefined conf

Or check different options and create a config file based on your needs

**Comment by niVelion** [comment]
Since @MarcoFalke added the "good first issue" label to this issue @josiblake and @prayank123 have proposed PRs, I think this label could at least for now be removed - I'm not sure this is the best starting point anymore.

**Comment by MarcoFalke** [comment]
"Good first issue" also means that this might be a good starting point to review. Instead of looking for "good first issue" to create a pull request, one can also look for "good first issue" to find existing pull requests to review.

**Comment by gargabhishek100** [comment]
Is this issue is still open?
