### ISSUE TITLE
update assumevalid and minimum chain work

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#10778]
We've missed doing this for a number of point releases, we shouldn't miss doing it for 0.15. I'd like to do it shortly before we cut the RCs.  (I'll do it, it's easy, it's just that I want to do it as late as possible but still within the window and I've missed the last couple).

Please tag for 0.15.

**Comment by achow101** [comment]
This should be set before any forks happen. Or at the very least, set to a that precedes a fork.

**Comment by MarcoFalke** [comment]
Closing for now, since #10945 is merged.
