### ISSUE TITLE
Need tests for bitcoin-cli

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#10791]
There are tests for `bitcoin-tx` but not for `bitcoin-cli`.
The RPC server is tested extensively, but the client is not tested at all.

**Comment by jnewbery** [comment]
ACK. I've already started working on this.

**Comment by laanwj** [comment]
Great!

**Comment by MarcoFalke** [comment]
I will likely prepare a backports pull with test related changes for 0.15.1. Would like to see this here.

**Comment by laanwj** [comment]
Closing (implemented by #10798)
