### ISSUE TITLE
checkblock.cpp invalid name for included datafile

### ISSUE THREAD

**Issue by ko3ak** [bitcoin/bitcoin#10797]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.  checkblock.cpp line 13 points to incorrect file name "bench/data/block413567.raw.h" data directory contains file "bench/data/block413567.raw"
Line 13 should be changed from:
12: namespace block_bench {
13: #include "bench/data/block413567.raw.h"
14: } // namespace block_bench
to:
12: namespace block_bench {
13: #include "bench/data/block413567.raw"
14: } // namespace block_bench
2.
3.

### Expected behaviour
raw block should be included 

### Actual behaviour
unresolved inclusion error

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using? git clone master 20170711
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:  Linux
- CPU: Intel
- RAM: 8G
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by MarcoFalke** [comment]
According to
https://github.com/bitcoin/bitcoin/blob/b2e178a2d2e387b147f0d87e64fc773d5ec799d0/src/Makefile.bench.include#L68
those files are autogenerated.

**Comment by ko3ak** [comment]
It was not very obvious '*.raw.h" is dynamically generated... When I was browsing bitcoin source code in eclipse I was seeing number of unresolved symbols. It would be better to have both files:
block413567.raw  block413567.raw.h and regenerate as needed, rather than having unresolved symbols....

**Comment by laanwj** [comment]
I've never seen this error before.

How to reproduce this problem? (e.g. build steps that you enter from the shell, starting from a clean tree)

**Comment by ko3ak** [comment]
1. git clone https://github.com/bitcoin/bitcoin.git
2. cd /home/bitcoin/src/bench
[@fedora bench]$ grep raw *.[ch]*
checkblock.cpp:#include "bench/data/block413567.raw.h" // file does not exists
Note: browsing the source tree at this stage will produce errors as indexer cannot resolve include file, also, include file should be relative to location of .cpp when  "..." is used i.e #include "data/block413567.raw.h" 
will this strategy of rebuilding include file from  raw block work for Big Endian-Systems?
3. cd /home/bitcoin
./autogen.sh
./configure
make
note: only after make source code can be browsed without errors related to missing include file

**Comment by sipa** [comment]
In general, the git repository does not contain files that get generated during the build process anyway. Doing so means extra overhead in maintaining source and output to remain synchronized, and is confusing to people who want to modify the source.

Yes, if you want to browse auto-generated files, you'll need to build them.

**Comment by laanwj** [comment]
So there is no actual build system bug?
Going to close this.

> Yes, if you want to browse auto-generated files, you'll need to build them.

It's the same for other generated files, for example `configure` `Makefile` etc. Checking in auto-generated files is usually a bad idea, as it can result in accidental diff noise if the generation isn't entirely deterministic (e.g. the file includes a date or such).
