### ISSUE TITLE
Redundant conditional in ecdsa_impl.h

### ISSUE THREAD

**Issue by corebob** [bitcoin/bitcoin#10811]
The following code block can be seen in src/secp256k1/src/ecdsa_impl.h starting at line 83

```
while (lenleft > 0) {
    if ((ret >> ((sizeof(size_t) - 1) * 8)) != 0) {
    }
    ret = (ret << 8) | **sigp;
    if (ret + lenleft > (size_t)(sigend - *sigp)) {
        /* Result exceeds the length of the passed array. */
        return -1;
    }
    (*sigp)++;
    lenleft--;
}
```

The conditional _if_ statement at line 84 doesn't appear to have a purpose other than spending cycles

**Comment by fanquake** [comment]
You should submit this issue to the upstream secp256k1 repository  https://github.com/bitcoin-core/secp256k1.

**Comment by corebob** [comment]
Okay, that makes sense, thanks
