### ISSUE TITLE
 --disable-lcov complains there's no lcov

### ISSUE THREAD

**Issue by janstary** [bitcoin/bitcoin#10828]
This is 0.14.2 being built on openBSD 6.1-current.

```
env AUTOCONF_VERSION=2.69  AUTOMAKE_VERSION=1.15 sh autogen.sh
./configure --prefix=$HOME --mandir=$HOME/man --disable-tests --disable-gui-tests --disable-wallet --with-gui=no --disable-lcov CC=egcc CXX=eg++

...
configure: error: "lcov testing requested but lcov not found"
```

**Comment by achow101** [comment]
lcov is disabled by default. Using `--disable-lcov` will toggle the lcov setting, which is defaulted to no, so it will set it to yes. If you don't want to use lcov, then don't have any option involving lcov.

**Comment by janstary** [comment]
Exactly. If `--disable-lcov` _enables_ lcov, it's a bug in the configure script.
