### ISSUE TITLE
Compiling Error: qt/test/test_main.cpp

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#10836]
Hey,

When I'm compining under Linux Ubuntu 14.04 64 bit it crashes at this Step:

`cd depends // works
make HOST=i686-w64-mingw32 // works
cd .. // works
./autogen.sh # not required when building from tarball // works
CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=/ // works
make // failed`

I followed these Instructions:

https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

I used the Current Master Version.

After maybe 30 minutes, it stops compiling with this Error:

 
> Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
  GEN      qt/locale/bitcoin_uk.qm
  GEN      qt/locale/bitcoin_ur_PK.qm
  GEN      qt/locale/bitcoin_uz@Cyrl.qm
  GEN      qt/locale/bitcoin_vi.qm
  GEN      qt/locale/bitcoin_vi_VN.qm
  GEN      qt/locale/bitcoin_zh_CN.qm
  GEN      qt/locale/bitcoin_zh_HK.qm
  GEN      qt/locale/bitcoin_zh.qm
  GEN      qt/locale/bitcoin_zh_TW.qm
  GEN      qt/qrc_bitcoin_locale.cpp
  CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin_locale.o
  AR       qt/libbitcoinqt.a
  OBJCXXLD qt/bitcoin-qt.exe
  CXX      qt/test/qt_test_test_bitcoin_qt-compattests.o
  CXX      qt/test/qt_test_test_bitcoin_qt-rpcnestedtests.o
  CXX      qt/test/qt_test_test_bitcoin_qt-test_main.o
qt/test/test_main.cpp: In function ‘int main(int, char**)’:
qt/test/test_main.cpp:62:43: error: ‘setenv’ was not declared in this scope
     setenv("QT_QPA_PLATFORM", "minimal", 0);
                                           ^
make[2]: *** [qt/test/qt_test_test_bitcoin_qt-test_main.o] Error 1
make[2]: Leaving directory `/home/globaltoken/wallet-compile/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/globaltoken/wallet-compile/bitcoin/src'
make: *** [all-recursive] Error 1

What am I missing ?

Kind Regards.

**Comment by ReneNyffenegger** [comment]
You seem to follow the building instructions for Windows. I was able to compile Bitcoin Core on Ubuntu following these steps: https://gist.github.com/kostaz/19729e6d53adc5d1606c

**Comment by globaltoken** [comment]
Yeah that was right, I want to Compile **Windows** Wallets not Linux Wallets.
And Windows Wallet Compiling failed with this Error.

**Comment by huobur** [comment]
In ../bitcoin/src/qt/test/test_main.cpp:

setenv() is not compatible in Windows 

if you replace it with:
    //setenv("QT_QPA_PLATFORM", "minimal", 0);
    _putenv_s("QT_QPA_PLATFORM", "minimal");

it should build.

Note:
the code above is not portable, but will get your Windows build going.
