### ISSUE TITLE
Solo GPU Miner faied!

### ISSUE THREAD

**Issue by tetsaicn** [bitcoin/bitcoin#10848]
server error: Method not found
no response to getwork, using as stratum
My config:
server=1
rpcuser=user
rpcpassword=password
rpcallowip=127.0.0.1
The getwork() method is removed，How to do it?

**Comment by luke-jr** [comment]
BFGMiner is technically capable of GPU mining using getblocktemplate, but note that GPU mining is not useful for mainnet.

**Comment by tetsaicn** [comment]
So,How to do it?

**Comment by achow101** [comment]
@tetsaicn This is off topic for the github issues for Bitcoin Core. Your question would be more suited for bitcointalk.org or bitcoin.stackexchange.com

**Comment by sipa** [comment]
If your software requires `getwork`, it has not been maintained for at least 3 years. Go use other software.

**Comment by tetsaicn** [comment]
For example? I can't find an supported GPU solo miner

**Comment by luke-jr** [comment]
https://github.com/bitcoin/bitcoin/issues/10848#issuecomment-315689683

**Comment by tetsaicn** [comment]
but i can't run it , I don't know why

**Comment by tetsaicn** [comment]
Log here
https://gist.github.com/tetsaicn/453d481128fe5e4dbf632c5c6346df30

**Comment by sipa** [comment]
This is not a support forum for bfgminer or other mining software.

Please take this elsewhere unless there are actual issues with Bitcoin Core to report.
