### ISSUE TITLE
Warning about "Unknown block versions": Also tell the reason

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#10860]
### bitcoind version
bitcoind 0.14.2

### What happened
Some hours ago I got an alert from bitcoind:
_Warning: Unknown block versions being mined! It's possible unknown rules are in effect_

I guess the unknown version bit triggering this warning is bit 4 (bip91) that got over 50% signalling at that point.

### What I would expect / suggest
I would suggest to include the unknown version bit(s) in the message, so users are assured about exactly what is unknown. 

E.g.
_Warning: Unknown block versions (version bit x) being mined! It's possible unknown rules are in effect_
_Warning: Unknown block versions (version bits x,y,z) being mined! It's possible unknown rules are in effect_

I think that would not do harm to users that do not know anything about version bits, but those who have at least heard something about that before, can read what bits are unknown and maybe search in the internet for more information.

**Comment by TheBlueMatt** [comment]
Seems reasonable. Still, good thing we have this warning, it's doing exactly what it should - informing users that they shouldn't trust blocks or confirmations right now or for the next few weeks. We should maybe make the warning stronger depending on the level of signaling.

**Comment by gmaxwell** [comment]
It both does this already and cannot do this.

It does this already: https://people.xiph.org/~greg/temp/warning_in_gui.png

It cannot do this: the warning you are seeing is a generic non-bip9 specific warning. The meaning of the version may have nothing to do with any kind of bits at all. The meaning of the unexpected version could even be established elsewhere in blocks.

**Comment by wodry** [comment]
I would suggest to tell the user about the reason(s) for the warning in the warning message, so the user is clear about it and not left uncertain. Whatever reason that would be.

**Comment by rebroad** [comment]
Not sure I understand @gmaxwell's reply - are you saying it's not possible to interpret the version bits into understandable human language?

**Comment by sipa** [comment]
All this warning means is that there are many blocks with an overall
version number that we don't expect. It is not due to one specific version
bit being set; there is a different (and more specific) warning for that -
however the threshold isn't met yet for the latter.
