### ISSUE TITLE
Travis: failed to bind to port 11211

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#10869]
Looks like a spurious Travis failure in p2p-segwit.py here: https://travis-ci.org/bitcoin/bitcoin/jobs/254520908#L5356

```
2017-07-17 19:06:34.660901 Unable to bind to 0.0.0.0:11211 on this computer. Bitcoin Core is probably already running.
```

test_runner.py and test_framework.py are very careful to not re-use ports for p2p and rpc interfaces on different nodes/tests, so perhaps another process was bound to 11211. Googling for port 11211 shows that it's memcached's default port.

Should be easy to test whether port 11211 causes problems by pushing a branch with `port_seed()` changed.

**Comment by laanwj** [comment]
Most intermittent failures with ports could be avoided by using UNIX sockets for testing, too bad that that didn't make it.

**Comment by MarcoFalke** [comment]
The most simple work around would be to stop picking 11211:

```diff
diff --git a/test/functional/test_framework/util.py b/test/functional/test_framework/util.py
index acca72aa8..43f689df5 100644
--- a/test/functional/test_framework/util.py
+++ b/test/functional/test_framework/util.py
@@ -164,5 +164,5 @@ def satoshi_round(amount):
 MAX_NODES = 8
 # Don't assign rpc or p2p ports lower than this
-PORT_MIN = 11000
+PORT_MIN = 11222
 # The number of ports to "reserve" for p2p and rpc, each
 PORT_RANGE = 5000

**Comment by MarcoFalke** [comment]
@jnewbery Do you think this issue is worth to tackle/keep open?

**Comment by jnewbery** [comment]
Setting 'Up for grabs'. Next steps, for anyone who wants this:

- confirm that it really is port 11211 that causes problems.
- fix using Marco's workaround or some other way.
