### ISSUE TITLE
Collect node's metrics in Prometheus format

### ISSUE THREAD

**Issue by hyperwang** [bitcoin/bitcoin#10887]
Is it possible to collect node's metrics? Such as bandwidth usage, memory usage, memory pool size, block height, estimate fee and so on, and export all these metrics on the port that offers the [Prometheus](https://prometheus.io/) metric format. This feature will be more convenient for operator to monitor the nodes' performance by using the modern monitor system, such as Grafana.

**Comment by windsok** [comment]
Check out http://statoshi.info/ and https://github.com/jlopp/statoshi

**Comment by jonasschnelli** [comment]
I'd like the idea that Core would allow to collect more statistical data (not a code fork). A move towards that direction is https://github.com/bitcoin/bitcoin/pull/8501.

**Comment by hyperwang** [comment]
@windsok Yes, that's the feature I want and appreciate the maintainer. Have noticed that the code base not follow new release very promptly.

**Comment by hyperwang** [comment]
@jonasschnelli Cool idea for collecting metrics by using CScheduler and offer the data in an rpc interface. But it is a little complicated to manage the stats metric series, it brings more codes to handle the metric storage and collecting interval. Just offering the metric itself not the history is simple, and leave the history collecting to other tools is more decoupled for operator who runs commercial service.  Indeed both the ways would bring invasion to the orginal code, but it is unavoidable for this kind of feature.

**Comment by laanwj** [comment]
See also discussion here https://github.com/bitcoin/bitcoin/issues/20981#issuecomment-767170859

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.
