### ISSUE TITLE
Cross Compiling not directly compiling with installer

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#10909]
Hello,

How to Cross Compile directly into that Bitcoin setup.exe for Windows?
I think with Gitian Building its working, but not with Cross Compiling?

If I compile I get only single files with .exe but how to compile that they are directly in the setup wizard .exe for windows ?

Cheers.

**Comment by jonasschnelli** [comment]
Have you tried `make deploy` when cross-compiling with MinGW?

**Comment by globaltoken** [comment]
Hi,

No - never tried, I'm building under Ubuntu x64 14.04 LTS
I followed these steps:

> cd depends
make HOST=i686-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=/
make # means directly make deplay or make && make deploy ?

**Comment by globaltoken** [comment]
means directly make deplay or make && make deploy ?

**Comment by jonasschnelli** [comment]
> means directly make deplay or make && make deploy ?

Doesn't really matter. But do `make deploy` directly.

**Comment by globaltoken** [comment]
Okay, I will test it and let you know.

**Comment by globaltoken** [comment]
Okay I did it but where are the .exe Files located?
Cant find them :(

**Comment by jonasschnelli** [comment]
They should be on the root level (IIRC). Maybe post the output of your `make deploy`.

**Comment by globaltoken** [comment]
Okay, the thing was if I directly run make deploy, he didn't build the binaries.
Just if I make "make" It builds the binaries.
So I did make && make deploy and I think you mean with root level the Folder where the Files like makefile.am, autogen.sh and so on are right?

because i checked and didn't found them, am I missing some dependencies maybe?
I installed all which was descripted in build-windows.md

Cheers.

**Comment by globaltoken** [comment]
Why is it closed now ?

**Comment by jonasschnelli** [comment]
Can you post your make deploy output?
Can you add V=1 to make (verbose)?

**Comment by globaltoken** [comment]
I receive this:

Seems that QT is not building and thats why its failed.
If I compile without deploy it works ?

> make[2]: Leaving directory `/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/src'
make[1]: Leaving directory `/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/src'
Making all in doc/man
make[1]: Entering directory `/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/doc/man'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/doc/man'
make[1]: Entering directory `/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2'
/bin/mkdir -p ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/build-aux/install-sh -c -s ./src/bitcoind.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/build-aux/install-sh -c -s ./src/qt/bitcoin-qt.exe ./release
/home/globaltoken/wallet-compile/Compilers/deploytest/deploytest2/build-aux/install-sh: ./src/qt/bitcoin-qt.exe does not exist.
make: *** [bitcoin-1.0.3-win64-setup.exe] Error 1
globaltoken@euve59306:~/wallet-compile/Compilers$

**Comment by globaltoken** [comment]
No its not working.
Here the last limes from ssh
[output.txt](https://github.com/bitcoin/bitcoin/files/1174695/output.txt)
