### ISSUE TITLE
`using namespace std` in src/wallet/wallet.cpp even though fully qualified names are used. consistently

### ISSUE THREAD

**Issue by lyle-nel** [bitcoin/bitcoin#10906]
### Describe the issue
src/wallet/wallet.cpp has a `using namespace std;` at the start even though fully qualified names are used throughout the file.
### What version of bitcoin-core are you using?
Master branch:0c173a15ca1bf20999f74987988985508c9de463

**Comment by gmaxwell** [comment]
Wallet.cpp doesn't have the string namespace in it at all in 0c17315ca.
