### ISSUE TITLE
Vestigial CCryptoKeyStore::GetKeys

### ISSUE THREAD

**Issue by lyle-nel** [bitcoin/bitcoin#10904]
### Describe the issue
CCryptoKeyStore::GetKeys at line 173 of file src/wallet/crypter.h and
CBasicKeyStore::GetKeys at line 75 of file src/keystore.h is implemented but never used.
### What version of bitcoin-core are you using?
Master branch:0c173a15ca1bf20999f74987988985508c9de463

**Comment by MarcoFalke** [comment]
Feel free to submit a patch, but I don't think this warrants keeping an issue open.

**Comment by benma** [comment]
It's used here: https://github.com/bitcoin/bitcoin/blob/0c173a15ca1bf20999f74987988985508c9de463/src/wallet/wallet.cpp#L3664

**Comment by lyle-nel** [comment]
Doxygen seems to not have been able to resolve the callgraph.
Very well MarkoFalke I will close it.
