### ISSUE TITLE
Warning about "Unknown block versions" should disappear if the amount of unknown version blocks decreases

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#10918]
### bitcoind version
bitcoind 0.14.2

### What happened
Some days/weeks ago I got an alert from bitcoind:
_Warning: Unknown block versions being mined! It's possible unknown rules are in effect_

This warning (yellow warning line on the dashboard screen) remained, even after the amount of unexpected version blocks decreased to 13/100 blocks, see debug.log:

`2017-07-24 16:23:37 UpdateTip: new best=0000000000000000013b4a70548846b8902da69791abcc8caaf3b808eba80930 height=477379 version=0x20000002 log2_work=86.817098 tx=241550958 date='2017-07-24 16:23:45' progress=1.000000 cache=100.7MiB(50832tx) warning='13 of last 100 blocks have unexpected version'`

Only after restarting bitcoind, the yellow alert line in the GUI did not appear again.

### What I would suggest
I would suggest that the warning message automatically disappears if the unknown version block count gets below a threshold which is some percentage lower than the activation threshold (to prevent state flapping), so no restart of bitcoind is needed to make the warning disappear.

**Comment by achow101** [comment]
That is expected behavior and should most certainly not go away. With versionbits, the version number will reset to the default BIP 9 version number, so if new network rules had activated, you wouldn't know that there may have been new network rules in effect.
