### ISSUE TITLE
getreceivedbyaddress should return error for non-IsMine addresses

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#10921]
Currently, the `getreceivedbyaddress` RPC will return a value of 0 if a non-IsMine address is passed in. This is confusing, and should probably return an error, as it's a situation the caller should be aware of.

Not doing this leads to confusion, with people assuming it can query non-wallet addresses.

See also https://bitcoin.stackexchange.com/questions/57065/why-bitcoin-cli-getreceivedbyaddress-always-returns-0

**Comment by promag** [comment]
Close?

**Comment by sipa** [comment]
Fixed by #11055.
