### ISSUE TITLE
Prune-to mode (removable blockchain storage)

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#10929]
It would be nice if pruning could be configured to move data rather than delete it, such that rescanning/etc would work when the removable (or perhaps simply slower) storage is available.

**Comment by jonasschnelli** [comment]
Move would mean the block(files) would still be accessible from Bitcoin-Core but just moved to a different path (maybe a different filesystem, NAS, etc.)?

**Comment by luke-jr** [comment]
It seems it would be useful to support removable drives, eg for laptops.

**Comment by mrwhythat** [comment]
Started working on this and have some questions:
1. Should this be global (set in `init.cpp` alongside with `-prune` option or even `-prune=/path/to/reserve/location`) or per-command (for example `bitcoin-cli pruneblockchain 1000 --to=/path/to/reserve/location`)?
2. Should logic in `validation.cpp` be aware of this option, i.e. `prunePath` be passed alongside `pruneHeight` as parameter?

**Comment by mrwhythat** [comment]
Assuming we should be able to work with blocks on the removable storage when it's available, some validation logic should be aware of it, so one way of doing it is adding reserve storage location to the set of global flags in `validation.cpp`.

**Comment by jnewbery** [comment]
I have doubts about this concept. What exactly is the use case here?

- a user who has limited disk space so they want to prune
- *but* they have cold storage to back up the blocks that they prune (perhaps an external disk drive)
- *and* that removable storage is attached whenever they're running their node, so the blocks can be pruned to it
- *and* when they want to rescan, the removable storage is attached so they can reload the blocks

so the removable storage is pretty much attached whenever they're running bitcoind, which begs the question: why not just put the datadir on the removable storage?

Implementing this seems like a bunch of complication for not much benefit, or am I totally missing the point?

**Comment by MeshCollider** [comment]
@jnewbery I guess the blocks would not be pruned unless it was attached, so that you could run the node without it and it would not prune anything until you attach the storage and `pruneto` it

**Comment by luke-jr** [comment]
What @MeshCollider said is one use case. Another would be archiving old blocks to non-SSD while keeping recent ones on SSD.

**Comment by mrwhythat** [comment]
My personal usecase is that I have a home storage mounted on my laptop, so it would be great to prune block there and have the whole blockchain when I'm at home without needing to resync. Not that it's a general problem, but still, such a feature would be pretty usefull.

**Comment by TheBlueMatt** [comment]
Hmm, better question, then, is what utility you gain from having the full blocks? If you dont need to rescan, you hopefully don't need to access them, and you cant run with -txindex with pruning, so rescan is about the only thing you could even do with them. It might be cool to create a bootstrap.dat over time as your node prunes blocks, but reindex isn't all that much faster than network sync, and hopefully we can continue to improve that anyway.

**Comment by luke-jr** [comment]
@TheBlueMatt In prune-to mode, you would be able to use txindex...

**Comment by andronoob** [comment]
I'm curious that if BitTorrent-like partial block storage is possible?

Currently, pruned nodes cannot serve historical blocks to a node which is bootstrapping.

Also, there's something like [spruned](https://github.com/gdassori/spruned) which allows a pruned node to provide more services.

**Comment by andronoob** [comment]
I recently [realized](https://github.com/bitcoin/bitcoin/pull/19463#issuecomment-664824305) that this idea is actaully "pluggable block storage". I think this might provide utility just like a peer serving historical blocks.

**Comment by andronoob** [comment]
What's more, some users also want to store their blocks on multiple partitions of a disk, in a case that one partition exhausted its free space - just like a "pool" or "spanned volume".

**Comment by willcl-ark** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Pull requests with improvements are always welcome.
