### ISSUE TITLE
[RPC][Wallet][Segwit] Bug: Transaction sent to imported P2WSH does not appear in listtransaction.

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#10924]
It seems that there is a bug when a node sends coins to an imported P2WSH.
Such transaction does not appear in `listtransaction` unlike P2SH.

Note that if node A sends to node B where B imported the P2WSH, things works as expected, and both A and B would see the transaction in `listtransaction`.

The stangest thing is that `gettransaction` seems to know about the transaction. (but not the details)

Repro:
https://github.com/NicolasDorier/bitcoin/commits/importaddresssegwit
If you switch `use_p2wsh` to false, it passes, else, it does not. 
Failing on `assert(self.nodes[0].listtransactions("*", 1, 0, True)[0]["txid"]  == txid)`

ping @sipa this is the bug I bumped on TumbleBit that I explained to you.

**Comment by sipa** [comment]
A short update (thanks @NicolasDorier): there is no CTxDestination for native witness outputs, which means any `importaddress` is unable to mark the importer scriptPubKey as anything but change. This leads to inconsistent `gettransaction`/`listtransactions` output.

There are 2 solutions here:
* make `importaddress` fail to import addresses with no `CTxDestination` (or warn at least)
* Add BIP173 support

**Comment by sipa** [comment]
Actually, (1) is already warned about in the `importaddress` RPC help text.

**Comment by NicolasDorier** [comment]
my attempt to fix the issue, https://github.com/bitcoin/bitcoin/pull/10947 it would need to have bech32 support though.

**Comment by ryanofsky** [comment]
Should #10947 be tagged for 0.15, or should this be untagged?

**Comment by NicolasDorier** [comment]
Should not be tagged for 0.15. I think the best is to wait next version.

**Comment by MarcoFalke** [comment]
Cleared milestone 0.15.

**Comment by NicolasDorier** [comment]
Closing as this was solved by #11167
