### ISSUE TITLE
ARM Cross Compiling missing QT or normal ?

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#10930]
Hey,

I crossed compiled the Wallets for ARM but just received the daemon, cli and tx.
QT is not there, how can I generate them for ARM or is it not possible?

Thanks,

**Comment by laanwj** [comment]
This is not possible at the moment with depends due to an X11 issue on ARM.

If you compile Qt for your target platform yourself (or can otherwise copy existing headers/libraries for the target) you could direct it at that.

**Comment by laanwj** [comment]
BTW I wouldn't recommend compiling QT *on* the target hw, I did that once on a iMX.53 board, it took more than a week (and that was with a lot of modules disabled).

**Comment by globaltoken** [comment]
Oh okay, I want to cross compile it directly.

However, I can compile all Wallets, can I help contributing Compiling ?

Cheers.

**Comment by laanwj** [comment]
Sure, if you write instructions, feel free to contribute them.

**Comment by fanquake** [comment]
Closing this. If you do write some instructions, you can contribute them via a pull request.
