### ISSUE TITLE
Build failed on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by 315985314** [bitcoin/bitcoin#10938]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. ./autogen.sh
2../configure --enable-logging --enable-debug --enable-dht --with-boost-libdir=/usr/lib/x86_64-linux-gnu
3.make

### Expected behaviour
Tell us what should happen
Build successful
### Actual behaviour
Tell us what happens instead
Build failed

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `GetEmptyStringAlreadyInited':
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `payments::PaymentDetails::MergeFrom(payments::PaymentDetails const&)':
/home/jifenglei/Bitcoin/bitcoin/src/qt/paymentrequest.pb.cc:1136: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInternal(google::protobuf::internal::RepeatedPtrFieldBase const&, void (google::protobuf::internal::RepeatedPtrFieldBase::*)(void**, void**, int, int))':
/usr/local/include/google/protobuf/repeated_field.h:1484: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int)'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `payments::PaymentDetails::MergeFrom(payments::PaymentDetails const&)':
/home/jifenglei/Bitcoin/bitcoin/src/qt/paymentrequest.pb.cc:1118: undefined reference to `google::protobuf::internal::ArenaStringPtr::AssignWithDefault(std::string const*, google::protobuf::internal::ArenaStringPtr)'
/home/jifenglei/Bitcoin/bitcoin/src/qt/paymentrequest.pb.cc:1112: undefined reference to `google::protobuf::internal::MergeFromFail(char const*, int)'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `payments::PaymentDetails::MergeFrom(google::protobuf::Message const&)':
/home/jifenglei/Bitcoin/bitcoin/src/qt/paymentrequest.pb.cc:1095: undefined reference to `google::protobuf::internal::MergeFromFail(char const*, int)'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `CreateInternal<std::basic_string<char> >':
/usr/local/include/google/protobuf/arena.h:640: undefined reference to `google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/local/include/google/protobuf/arena.h:642: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `CreateInternal<google::protobuf::internal::InternalMetadataWithArena::Container>':
/usr/local/include/google/protobuf/arena.h:640: undefined reference to `google::protobuf::Arena::AllocateAligned(std::type_info const*, unsigned long)'
/usr/local/include/google/protobuf/arena.h:642: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `OwnInternal<payments::Output>':
/usr/local/include/google/protobuf/arena.h:824: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `OwnInternal<payments::PaymentDetails>':
/usr/local/include/google/protobuf/arena.h:824: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `OwnInternal<payments::PaymentRequest>':
/usr/local/include/google/protobuf/arena.h:824: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o): In function `OwnInternal<payments::X509Certificates>':
/usr/local/include/google/protobuf/arena.h:824: undefined reference to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequest.pb.o):/usr/local/include/google/protobuf/arena.h:824: more undefined references to `google::protobuf::Arena::AddListNode(void*, void (*)(void*))' follow
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequestplus.o): In function `Get<google::protobuf::RepeatedPtrField<payments::Output>::TypeHandler>':
/usr/local/include/google/protobuf/repeated_field.h:1407: undefined reference to `google::protobuf::internal::empty_string_'
qt/libbitcoinqt.a(qt_libbitcoinqt_a-paymentrequestplus.o): In function `GetEmptyStringAlreadyInited':
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_'
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_'
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_'
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to `google::protobuf::internal::empty_string_'
collect2: error: ld returned 1 exit status
make[2]: *** [qt/bitcoin-qt] Error 1
make[2]: Leaving`/home/xxx/Bitcoin/bitcoin/src'
make[1]: *** [all-recursive] 错误 1
make[1]:Leaving `/home/xxx/Bitcoin/bitcoin/src'
make: *** [all-recursive] 错误 1

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

commit 04d395e8327d512ae31d8e024d95e2d1e1729954 (HEAD -> master, origin/master, origin/HEAD)
Merge: 78f307b66 095b91746
Author: Wladimir J. van der Laan <laanwj@gmail.com>
Date:   Wed Jul 26 08:47:47 2017 +0200

    Merge #10854: Avoid using sizes on non-fixed-width types to derive protocol constants.
    
    095b917 Avoid using sizes on non-fixed-width types to derive protocol constants. (Gregory Maxwell)
    
    Pull request description:
    
      Thanks to awemany for pointing this out.
    
      This replaces #10172 which appears to be abandoned, but uses the constants as requested on that PR.
    
    Tree-SHA512: 032c0d75b3aaf807a7d0c7fb8ff5515acc45ad58bd00fe81413f900fe02bad900534a970403b9bb568e132c9eddea6043e958daf625e8acc84375bd41ee2e2ef

### Machine specs:
- OS: Ubuntu 14.04LTS
- CPU:Intel Core i5-4590 CPU @3.30GHz x 4
- RAM:15.6GiB
- Disk size:967.6GB
- Disk Type (HD/SDD):HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by 315985314** [comment]
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference togoogle::protobuf::internal::empty_string_'

/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to google::protobuf::internal::empty_string_' /usr/local/include/google/protobuf/generated_message_util.h:86:

 undefined reference togoogle::protobuf::internal::empty_string_'
/usr/local/include/google/protobuf/generated_message_util.h:86: undefined reference to 

My protobuf version is  libprotoc 3.0.0
Which protobuf version should I choose?

**Comment by globaltoken** [comment]
Did you installed the whole dependencies ?

**Comment by 315985314** [comment]
I think boost is not install right.
I Run
 ./configure --with-boost=/usr/local
And the build is successful
