### ISSUE TITLE
make deploy for OSX fails on Ubuntu 16.04 LTS x64

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#10944]
Hey,

If I use the current master to try compile for osx with make deploy it fails with this Error:

`

    CN,zh_TW -verbose 2

    Copying source bundle +
    Deploying frameworks +
    Warning: Could not find any external frameworks to deploy in dist/Bitcoin-Qt.app.
    Warning: Could not detect Qt's path, skipping plugin deployment!
    Installing qt.conf +
    Adding Qt translations +
    Done +
    /bin/mkdir -p dist/.background
    /usr/bin/tiffcp -c none dpi36.background.tiff dpi72.background.tiff dist/.background/background.tiff
    /usr/bin/python3.5 contrib/macdeploy/custom_dsstore.py "dist/.DS_Store" "Bitcoin-Core"
    Traceback (most recent call last):
    File "contrib/macdeploy/custom_dsstore.py", line 44, in
    alias = Alias.from_bytes(icvp['backgroundImageAlias'])
    File "/root/Scripting/compiler/compile-processor-osx/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 319, in from_bytes
    return cls._from_fd(b)
    File "/root/Scripting/compiler/compile-processor-osx/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 305, in _from_fd
    alias.volume.disk_image_alias = Alias.from_bytes(value)
    File "/root/Scripting/compiler/compile-processor-osx/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 319, in from_bytes
    return cls._from_fd(b)
    File "/root/Scripting/compiler/compile-processor-osx/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 311, in _from_fd
    tag = struct.unpack(b'>h', b.read(2))[0]
    struct.error: unpack requires a bytes object of length 2
    Makefile🔢 die Regel für Ziel „dist/.DS_Store“ scheiterte
    make: *** [dist/.DS_Store] Fehler 1
    root@Ubuntu-16:~/Scripting/compiler/compile-processor-osx#`

What did I missed ?

**Comment by bilalpakistani** [comment]
How did you fix it?

**Comment by globaltoken** [comment]
@bilalpakistani I used Ubuntu 16.04 to compile OSX, also you need to install all OSX dependencies.

**Comment by bilalpakistani** [comment]
I am still failing, same error pops up.. I am using ubuntu 16.04 like you.  linux and windows builds fine.  I also placed tar ball inside of gitian-build/inputs ... takes couple hours. then pops up with the same error which you have got there ..  can you point me to dependencies

**Comment by globaltoken** [comment]
@bilalpakistani Pls look at: https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-descriptors/gitian-osx.yml

Install the dependencies:
packages:

- "ca-certificates"
- "curl"
- "g++"
- "git-core"
- "pkg-config"
- "autoconf"
- "librsvg2-bin"
- "libtiff-tools"
- "libtool"
- "automake"
- "faketime"
- "bsdmainutils"
- "cmake"
- "imagemagick"
- "libcap-dev"
- "libz-dev"
- "libbz2-dev"
- "python"
- "python-dev"
- "python-setuptools"
- "fonts-tuffy"

This should fix your issue.

**Comment by globaltoken** [comment]
@bilalpakistani I think your issue will be caused through python. Try apt install python python-dev python-setuptools

**Comment by bilalpakistani** [comment]
@globaltoken  Thanks bro, I solved my issue, yesterday.. 
It was not about dependencies, and python was already installed ..
this problem occurs because of wrong byte size in 
https://github.com/berycoin-project/berycoin/blob/9bd643b6330452049a84cf87e85733b57964cf2b/contrib/macdeploy/custom_dsstore.py#L31

I forked from qtum,  when i ran sed, it updated this string and replaced qtum with berycoin .. when i removed berycoin with only bery ... characters are now equal to original string. and it worked miraculously :)

**Comment by globaltoken** [comment]
@bilalpakistani Great mate!
What is this python string doing that had the wrong size?

**Comment by bilalpakistani** [comment]
That string is ImageAlias used to create .DS_store file for MacOS .. I never used Mac . and don't plan to use it.. so I don't know how it is generated. and what is ds_store file ..
