### ISSUE TITLE
Handle 100k accounts

### ISSUE THREAD

**Issue by n0n0n0n0** [bitcoin/bitcoin#10959]
Hello everyone, will bitcoind works properly with 100k addresses associated with 100k accounts?
I need to generate new address for every my client and client should be able to move his funds exactly from same generated beore wallet, how to better done this with bitcoind? Or maybe there exists some alternative solutions for such a huge amount of accounts?

**Comment by Rav3nPL** [comment]
No, it will kill your wallet file (it will be HUGE like 1GB) and hog bitcoind.
You should use external solution, like electrum, for that amount of accounts/addresses.

**Comment by n0n0n0n0** [comment]
Electrum with even 30k addresses lagging as hell and sometimes(about 80%) shows me NotEnoughFunds error but they exists(can see that even in getbalance command). So unfortunately also not works well, sadly.

**Comment by Rav3nPL** [comment]
So you stuck by bx (or similar tool) and own database system :)
Core is not designed for that.

**Comment by n0n0n0n0** [comment]
Sad, Thx

**Comment by samuelGrahame** [comment]
use something like MYSQL if you need a big database.  but you would need to do all your own implementation
