### ISSUE TITLE
Mining feature

### ISSUE THREAD

**Issue by ohhmm** [bitcoin/bitcoin#10955]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
No mining feature

### Screenshots.
n/a

### What version of bitcoin-core are you using?
Latest

### Machine specs:
n/a

### Any extra information that might be useful in the debugging process.
Mining feature would encourage people to leave bitcoin client opened to make bitcoin network fast and reliable everywhere.

**Comment by laanwj** [comment]
Mining using CPUs, even GPUs hasn't been feasible for years. The built-in mining functionality was removed at that point as you'd never, in a 1000 years, get a block. That's not very motivating...
