### ISSUE TITLE
Bitcoin payout address proposal

### ISSUE THREAD

**Issue by jonasman** [bitcoin/bitcoin#10954]
My proposal is a new feature for Bitcoin to support automatic payments without breaking any security

# Use Case
A user wants to use a service that needs a credit card. The service charges him every time he uses the service. 

Example: Apple iTunes. 
Every time the user buys an app, Apple will charge the user's card.

# Solution
Create a pay out address associated with my own account.
## Rules
The payout address is linked to my own wallet - so it can only get coins from my own address 
The payout can only be charged by only one merchant - only one address can receive transfers from this payout address. 
There is a daily and monthly withdraw limit
There is a way to query if the payout address has enough funds to make the purchase - This will trigger a query to the wallet
The wallet address cannot be known using only the payout address

# Comments
I think this proposal would largely increase bitcoin adoption as it solves one of the major problems with automatic payments that current bitcoin doesn't not support.

**Comment by jonasschnelli** [comment]
Please submit Bitcoin proposals elsewhere (this is the issue tracker for Bitcoin Core).
Ideally use the bitcoin dev mailing list.
Closing.
