### ISSUE TITLE
Symbolic link on windows (testnet=1 server=1)

### ISSUE THREAD

**Issue by Junxin-Huo** [bitcoin/bitcoin#10967]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
In testnet ,I run GUI with "server=1". CMD doesn't work.
(Symbolic link doesn't work)

#### If so, please list the steps to reproduce below:
1. Set %DATA%bitcoin.conf with testnet=1 server=1 ......

2. Set %USER%AppData/Roaming/Bitcon/bitcoin.conf symbolic links to %DATA%bitcoin.conf

3. Run %PATH%bitcoin-qt.exe

4. GUI works well while under CMD the %PATH%daemon/bitcoin-cli.exe "Could not locate RPC credentials"

5. Special command:
D:\Program Files\Bitcoin\daemon>bitcoin-cli getinfo
error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)

D:\Program Files\Bitcoin\daemon>bitcoin-cli.exe -testnet=1 getifo
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (C:\Users\xxx\AppData\Roaming\Bitcoin\bitcoin.conf)

6. When I copy %DATA%bitcoin.conf to %USER%AppData/Roaming/Bitcon/bitcoin.conf rather than symbolic link, it works.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Windows 10
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by laanwj** [comment]
Windows symbolic links/junctions aren't supported, this is a known issue.
Closing as duplicate of #6495
