### ISSUE TITLE
Stop translating command-line option help?

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#10962]
A curious property of the current client is that command-line help (`--help`) will be translated when doing `bitcoin-qt --help` but not for `bitcoind --help`. The reason for this is that bitcoind doesn't contain the translations.

This makes it a waste of translator time. It could be achieved by linking `gettext` and converting the translations (see issue #6092). However I'm not sure it's worth it.

Many options are extremely technical, and refer internals, making it difficult to translate usefully. This came up in discussion of e.g. #10949. If a message is not understood by translators (which are typically end-users, not developers) they'll either translate it literally, making it harder to understand instead of easier, with the added drawback of the user no longer being able to google it.

**Comment by MarcoFalke** [comment]
I think that the user base is different for bitcoind and bitcoin-qt. Users
of the daemon interact through json and are likely familiar with technical
English. Though, gui users (often windows users) are not familiar with the
command line and some of them might have difficulties understanding the
technical English.

The solution would be to make the translatable strings as easy to
understand as possible. In case this is not possible and it takes several
lines to explain a single command-line option, it is probably best to not
expose it to the average user anyway.

**Comment by laanwj** [comment]
The problem is that translators usually don't succeed in translating
heavily technical English into anything sensible in another language. This
makes the result harder, not easier to understand - not only technical but
badly translated too.

I think we're failing with regard to not exposing those things to end
users. As long as you consider the command line options at least. The GUI
messages themselves are usually ok.

This is why I'd prefer (and I'm sure many translators want too) to remove
the translation bit from command line options.

The other option would be to be much more strict about option help, but
honestly I don't see that happening - it has shown to be impossible to word
these non-technically.

(That discardfee message was reworded and I immediately got new complaints
about it! So I see this as only option now)

**Comment by jnewbery** [comment]
Concept ACK (but I'm a native English speaker, so my opinion on this is less relevant). Perhaps try to solicit feedback from more non-native English speaking users and contributors.

**Comment by laanwj** [comment]
This issue has been open for almost a year and no one seems to be strongly against it. I'll open a PR.

**Comment by MeshCollider** [comment]
I believe this can be closed now after the merge of #13341
