### ISSUE TITLE
Make with MinGW fails with `recipe for target 'all-recursive' failed`

### ISSUE THREAD

**Issue by MattyAB** [bitcoin/bitcoin#10970]
In Linux subsystem for Windows, I am attempting to make on a clean clone. I had some issues here: #10856, but they are now resolved, and I am just doing the 'make' command in /bitcoin (as stated [here](https://github.com/bitcoin/bitcoin/blob/f66c59650527022b4f7abd98ff0a1a4e4741bd34/doc/build-windows.md#building-for-64-bit-windows)). I am getting this error:

`collect2: error: ld returned 1 exit status
Makefile:3506: recipe for target 'libbitcoinconsensus.la' failed
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: Leaving directory '/home/MattyAB/bitcoin/src'
Makefile:9256: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/MattyAB/bitcoin/src'
Makefile:740: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

Here is the full error with stack trace: [https://pastebin.com/02JRiS1P](https://pastebin.com/02JRiS1P)

I had a look around, this looks similar to #10960, but it's failing in a different directory.

**Comment by fanquake** [comment]
Closing now that #11438, new build instructions, have been merged. If you're still having issues, can you comment in #11685.

**Comment by aaron11193** [comment]
The new build instructions don't seem to be at all relevant to this post.
I'm having the same problem, except I'm trying to build inside Linux.

**Comment by genexcore** [comment]
Add the command -i to the make instructions. It will still build.
