### ISSUE TITLE
"Unknown, syncing headers", bitcoin core stopped synchronization

### ISSUE THREAD

**Issue by volkno25** [bitcoin/bitcoin#10978]
###my bitcoin core say "syncing headers" and it totally stopped downloading blocks for more than 20 hours from then. this happened after 1/8 hard fork and after i set up the bitcoin ABC wallet 0.14.6, which i have removed. i tried many things and really confused now. all i want is to claim my bitcoin cash and move it to a market. please help me with this big thanks!

### Screenshots.
![untitled](https://user-images.githubusercontent.com/30658516/28878699-38381270-77ca-11e7-89ed-b5a13d6df35d.png)

### Version of bitcoin-core
0.14.2 uasfsegwit

### Machine specs:
- RAM: 8gb
- Disk size:500gb 
- Disk Type (HD/SDD): hdd

**Comment by DonDerossi** [comment]
Same problem here, I ran Bitcoin ABC yesterday. It did share the same Blockchain Data as Bitcoin Core. I could not run both at the same time since some directory gets taken exclusively by one or the other app. Today Bitcoin Core ist stalled at 99.89% and block 479758. How do I "unblock" my BTC Blockchain? Or redownload? Thank you.

**Comment by sipa** [comment]
You cannot have different currency's blockchains be stored in the same location; the result is likely corruption both directions. You can always run with -reindex to wipe the database and just process the blocks you already have again.

**Comment by DonDerossi** [comment]
8-O  OMG ... THE man with the most commits on Core is answering... Thank you Peter! If you could just explain to a noob on how to run the -reindex command on a Mac? Do I do that while running the GUI somehow in the console? (tried verifychain...) Or do I start a Terminal, navigate to some place, launch bitcoind...?
BTW. I saw a picture of you and some UASF-Supporters which lead me to believe you are now in SF. If I remember right you lived in Zurich? I live in Zurich and always wandered if you are around... 
Viele Dank für Dini Hilf!
Don

**Comment by MarcoFalke** [comment]
@DonDerossi I don't have a mac, so use at your own risk: There should be an executable file at `/Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt`. So just call that in the command line and append `-reindex` once for this call.

```sh
/Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt -reindex

**Comment by darkfur93** [comment]
I also started getting this error. I have never used the ABC client.

**Comment by AllanDoensen** [comment]
I see this on a clean VM that just runs bitcoin-ABC. It just stops downloading blocks. Killing and restarting works to continue the download but then it gets stuck again requiring a further restart. I have not seen it on a clean VM that is just running core - but I do not rule it out.

**Comment by DonDerossi** [comment]
SOLVED!

Thank you very much Marco Falke!
`/Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt -reindex` is the exact instruction for using in the Terminal on a Mac.

The reindexing took about 2.5 days on my 3 year old MacBook Pro Retina but now everything is back to normal.

Thank you Core Devs! Thank you Core Maintainers! Go SegWit! And sorry for running this Bitcoin ABC garbage.

**Comment by sushilraghav** [comment]
@volkno25 @DonDerossi @sipa @MarcoFalke @darkfur93    For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
