### ISSUE TITLE
Wallet rescan is non-interruptible at startup

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#10987]
When the wallet is rescanned at startup in `bitcoind`, there seems to be no way to interrupt that in a clean way (other than forcefully killing the process).

**Comment by laudaa** [comment]
The same happens when you attempt to import a private key. There's a 'X' button (GUI), but it does not stop/interrupt it.

**Comment by promag** [comment]
Fixed by #11281.

**Comment by MarcoFalke** [comment]
The rpc should probably warm up and accept requests for `abortrescan` and `stop`
