### ISSUE TITLE
-salvagewallet seems to be causing more issues than it fixes, it should be removed

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#10991]
I have noticed that `-salvagewallet` seems to be actually causing more issues than it actually fixes.

Below is a list of things I have found so far that are problematic:

- Default key is not passed through causing problems with encrypted wallets and `-usehd=1` (fixed in #10952)
- Wallet version number is not preserved, so salvaged wallets become version 10500, which could have unexpected behavior with optional features such as HD and HD chain split
- salvaging seems to be skipping keys for some unknown reason. There is no given error, it just skips keys

**Comment by jnewbery** [comment]
Good discussion of the issues with `salvagewallet` here: https://github.com/bitcoin/bitcoin/pull/10540

At the very least, salvagewallet should be in a tool outside of bitcoind. I'm hoping we'll get that done before 0.16. Would you be interested in working on that with me?

**Comment by TheBlueMatt** [comment]
Hmm, can we add an extra warning for when salvage reads an HD key in 15? The others seen to be just "salvage is really not so good and sould be an external tool", but that seems very likely to cause issues.

**Comment by Sjors** [comment]
#18918 moves `salvagewallet` into the wallet tool

**Comment by adamjonas** [comment]
`-salvagewallet` was removed in #18918
