### ISSUE TITLE
Return service bits 6 and 8 on Aug 1, 2018

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#10993]
#10982 started disconnecting service bits 6 and 8 until aug 1, 2018, the code to do so should be removed on or after that date.

**Comment by jgarzik** [comment]
NAK, this code causes compatible clients to prematurely split the network.

**Comment by MarcoFalke** [comment]
Commits to be reverted after that date:
* 1de73f4e19fe789abb636afdb48a165a6fd31009
* 5e35cd9

**Comment by MeshCollider** [comment]
c.f.  https://github.com/bitcoin/bitcoin/pull/11637
