### ISSUE TITLE
[Qt] import* rescans are not abortable and can confuse users

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#10992]
When importing something with any of the `import*` commands from the qt debug window console, a progress bar appears which is uncancelable and unminimizable. Furthermore, trying to close the progress bar window simply makes it disappear, and then shortly appear again. This behavior is clearly seen in the gif below.

![peek 2017-08-05 01-39](https://user-images.githubusercontent.com/3782274/28994277-09a101c2-797f-11e7-8b3c-2ed7d27a66c5.gif)

Rescanning also completely locks up the GUI and nothing else can be done.

Since there is an `abortrescan` RPC command, there should be some way to abort a rescan now through the progress bar dialog that appears, either with an additional button, or by clicking the X to close it.

**Comment by jonasschnelli** [comment]
Agree that one should be able to abort rescans. The fix shouldn't be to hard. The progress dialog (`QProgressDialog` / `WalletView::showProgress`) could have the optional cancel button. The cancel button then could eventually directly call `AbortRescan();` or through a callback.

Rescan locks `cs_main` and `cs_wallet`. Avoiding the GUI locks will be harder (probably doable with @ryanofsky https://github.com/bitcoin/bitcoin/pull/10973).

**Comment by juestr** [comment]
I just tried to `bitcoin-cli abortrescan` a rescan caused by a cli importprivkey, and it hangs too. Maybe this is not just a GUI problem (0.15.0.1).

**Comment by achow101** [comment]
Fixed by #11200
