### ISSUE TITLE
[Qt] Warning messages are not displayed when running bitcoin-qt with -disablewallet

### ISSUE THREAD

**Issue by fametrano** [bitcoin/bitcoin#11016]
### Describe the issue
Warning messages are not displayed when running bitcoin-qt 0.14.2 and 0.14.99 with -disablewallet.
It might be better to always display them.

E.g. on MainNet the "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications" is lost
![image](https://user-images.githubusercontent.com/3296421/29109760-853e5394-7ce4-11e7-8f05-bfcd66ada471.png)
![image](https://user-images.githubusercontent.com/3296421/29109806-adf6e67a-7ce4-11e7-8564-8883c44656ad.png)

On TestNet also the "Warning: unknown new rules activated (versionbit 28)" is missed
![image](https://user-images.githubusercontent.com/3296421/29110269-6b24b79e-7ce6-11e7-91e7-823227eaa200.png)
![image](https://user-images.githubusercontent.com/3296421/29110035-9142cf34-7ce5-11e7-8faf-264e805cdaf4.png)

**Comment by fametrano** [comment]
One possible solution could be to have the messages _also_ in the debug window, as the main page of bitcoin-qt defaults to the debug window in the -disablewallet case.

Anyway, to have them in the main page (above the Overview/Send/Receive/Transactions wallet bar) would be neater in my opinion

**Comment by jonasschnelli** [comment]
Good point and yes, I agree that the message should be visible in disablewallet mode though I haven't made any thought about where to add/move the message.

**Comment by Sjors** [comment]
Concept ACK on somehow fixing this.
