### ISSUE TITLE
Thoughts about rewriting in rust?

### ISSUE THREAD

**Issue by jetbrains99** [bitcoin/bitcoin#11018]
Have you given thoughts about rewriting source code in rust? Or maybe parts of it, so part by part it could replace the totally [inefficient](https://benchmarksgame.alioth.debian.org/u64q/compare.php?lang=rust&lang2=gpp) and memory unsafe language its currently written in? Let me introduce you to [rust lang](https://www.rust-lang.org/en-US/) -

> Rust is a programming language that’s focused on safety, speed, and concurrency. Its design lets you create programs that have the performance and control of a low-level language, but with the powerful abstractions of a high-level language. These properties make Rust suitable for programmers who have experience in languages like C and are looking for a safer alternative, as well as those from languages like Python who are looking for ways to write code that performs better without sacrificing expressiveness.

**Comment by DeftNerd** [comment]
It's impractical to ask excellent C++ programmers with a long-established codebase to rewrite everything in Rust (especially when many of them might not know Rust)

Check out https://github.com/paritytech/parity-bitcoin

Parity has a compliant node written in Rust that might meet your criteria.

**Comment by jonasschnelli** [comment]
Closing due this is not really an issue and something we want and can consider.

**Comment by luke-jr** [comment]
It's not currently possible to obtain a Rust compiler without trusting some third-party binaries, which could possibly carry self-reproducing malware. For this reason, I would object to using Rust in any security-oriented software, such as Bitcoin.

Furthermore, however, Bitcoin relies on a strong guarantee that all nodes implement exactly the same logic for determining if blocks are valid or not. Comparing the exactness of two independent implementations, especially across significantly different languages (such as C++ vs Rust) is not currently possible, and as such, porting the code implementing this logic perfectly to Rust (or any other language) is likely to have undetected errors which can introduce vulnerabilities into the system (or at least, the nodes running the divergent implementation).
