### ISSUE TITLE
How is core going to ensure the survivability of bitcoin without a hard fork?

### ISSUE THREAD

**Issue by floreslorca** [bitcoin/bitcoin#11014]
According to the NYA, 90% of the hashing power will be diverted to segwit2x coin. This will slow the chain to almost a complete stop. Considering the hostility of Core towards the miners, there is a thin chance that bitcoin will get any more than 10% of the current hashing power, and there is a high chance that the network will be exposed to 51% attacks. Since Core has criticized segwit2x coin for forking off, how is core going to protect bitcoin without the need of a hard fork? Is an adjustment like bitcoin-abc did required or the newly created altcoin (corecoin) needs a different pow algo?

**Comment by jonny1000** [comment]
> 90% of the hashing power will be diverted to segwit2x coin. This will slow the chain to almost a complete stop

If 90% of the hashing power leave Bitcoin, the chain should continue to survive.  The average block time should increase to 100 minutes compared to  10 minutes, before the difficulty adjustment kicks in.  This increase is smaller than BCash experienced.  The BCash supporters are in a rush for more throughput, while Bitcoin supporters tend to me more patient.  Therefore the impact of these longer block times may be more limited than one may think.  If the price of Bitcoin remains reasonable, miners are likely to switch back to Bitcoin.  Actually, ironically, longer block times may reduce liquidity, which could provide price support.

> and there is a high chance that the network will be exposed to 51% attacks

If such an attack is successful and caused a large re-org, then there will need to be an emergency change in the PoW function.  There could also be legal consequences for those conducting such an attack.

**Comment by floreslorca** [comment]
it will take like 6 months for the first difficulty change to happen at 10% hash rate. so good luck with waiting. As for the change on the PoW function. that would require a hard fork, thus creating core coin.

**Comment by sushilraghav** [comment]
@floreslorca  @jonny1000  @sipa @ldenman @casey  For 500$, Can you hard-fork of bitcoin at block height of 500888 ,used the BCH reference ,total coins 21210000,and 210000 is pre-mine @saleemrashid  

my email is bitcoinemxmx@gmail.com and skype : sushilraghav
