### ISSUE TITLE
error: Cannot obtain a lock on data directory

### ISSUE THREAD

**Issue by midas717** [bitcoin/bitcoin#11038]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue

Downloaded Bitcoin Core today. I told the program to use an extra hard drive on my computer that I rarely use but works (old laptop hard drive). It was taking forever to sync (est. time 20+ hours), so I shut it down for a bit to resume later.

When I tried to start the program again, I get the error "cannot obtain a lock on data directory L:\Bitcoin. Bitcoin Core is probably already running. Access is denied.." 

So I restarted my computer and tried to start the program again and got the same error. 

#### If so, please list the steps to reproduce below:
1. Click start menu -> Click Bitcoin Core shortcut

### Expected behaviour
open program

### Actual behaviour
error on startup loading screen

### What version of bitcoin-core are you using?
0.14.2

### Machine specs:
- OS: Windows 7
- CPU: Intel i5-4670k
- RAM: DDR3 2x8gb
- Disk size: 232 gb
- Disk Type (HD/SDD): Laptop HD connected into a desktop

**Comment by achow101** [comment]
Check that you don't already have Bitcoin Core already running. Look in task manager and see if you see any processes named `bitcoin-qt` or `bitcoind`.

**Comment by midas717** [comment]
It wasn't running. In my post I wrote that I restarted my computer before trying again.

**Comment by janmande** [comment]
Bitcoin Core uses a file named ".lock" in the data directory to make sure only one instance is accessing it at the time. Your error message indicates that the Bitcoin Core is denied acces to this file which usually only happens if another instance is running.

If you are absolutley sure that no other Bitcoin Core process is running you could try to delete the .lock file before starting Bitcoin Core again. I assume you have backed up your wallet if it contains any coins before attempting this.

**Comment by Mentors4EDU** [comment]
Deleting the lock file can fix it, and sometimes just running as sudo also will fix it if nothing else false. Same applies to SmartCash or other cryptos having that problem

**Comment by fortesp** [comment]
With me this happens when i try to put the ledger in a remote directory via SMB share. Even after deleting .lock file, every startup the same error displays.

**Comment by fortesp** [comment]
Can we reopen this issue please?
