### ISSUE TITLE
Cannot run bitcoind

### ISSUE THREAD

**Issue by natonamco** [bitcoin/bitcoin#11040]
Version: 0.14.2
macOS: Sierra (10.12.6)
When running "bitcoind"
Terminal shows: 
dyld: Symbol not found: __ZN5boost11this_thread5hiden9sleep_forERK8timespec
  Referenced from: /usr/local/bin/bitcoind
  Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
 in /usr/local/bin/bitcoind
Abort trap: 6

Thank you.

**Comment by natonamco** [comment]
When running "make check"

Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
../build-aux/test-driver: line 107: 35365 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: test/test_bitcoin
../build-aux/test-driver: line 107: 35375 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.14.2
============================================================================
# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

**Comment by jonasschnelli** [comment]
Very likely related to #11036

**Comment by djro** [comment]
I also had this issue and uninstall reinstall of boost fixed it:
brew uninstall --force boost 
brew install boost

**Comment by Cren700** [comment]
I also have this problem，try it to resolve

**Comment by Cantoria** [comment]
@djro I've met same problem. I'm afraid that your method doesn't work...

**Comment by hzz780** [comment]
Because your boost lib is not match your bitcoind.
when we make our bitcoind, we use boost lib 1.0, but we update boost lib to 2.0. We will meet the problem.
1. install the right version of boost.
2.rebuild bitcoind.

I hope these will help you.

**Comment by PaulRBerg** [comment]
I reinstalled boost and bitcoin and then tried to rerun bitcoin-cli, but it still failed with the same error as above.

```
dyld: Symbol not found: __ZN5boost11this_thread6hidden9sleep_forERK8timespec
  Referenced from: /usr/local/bin/bitcoin-cli
  Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
 in /usr/local/bin/bitcoin-cli
Abort trap: 6
```

**Comment by conotech** [comment]
> I reinstalled boost and bitcoin and then ran bitcoin-cli again, but it still failed with the same error as above. Tests ran with `make check` passed.
> 
> ```
> dyld: Symbol not found: __ZN5boost11this_thread6hidden9sleep_forERK8timespec
>   Referenced from: /usr/local/bin/bitcoin-cli
>   Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
>  in /usr/local/bin/bitcoin-cli
> Abort trap: 6
> ```
> UPDATE: After I manually removed `bitcoind` and `bitcoin-cli` from `usr/local/bin` and installed a fresh copy of bitcoin again, it worked.

This was true in my case, as well.
