### ISSUE TITLE
QT5 interface build failed

### ISSUE THREAD

**Issue by ne-vlezay80** [bitcoin/bitcoin#11057]
# gmake  
Making all in src
gmake[1]: Entering directory '/usr/src/bitcoin/src'
gmake[2]: Entering directory '/usr/src/bitcoin/src'
gmake[3]: Entering directory '/usr/src/bitcoin'
gmake[3]: Leaving directory '/usr/src/bitcoin'
  OBJCXXLD qt/bitcoin-qt
/usr/local/lib/libevent_core.so.1.1: warning: warning: random() may return deterministic values, is that what you want?
/lib/libdb_cxx-4.8.a(repmgr_stat.o): In function `__repmgr_site_list':
repmgr_stat.c:(.text+0x376): warning: warning: stpcpy() is dangerous; do not use it
/usr/local/lib/libprotobuf.so.1.0: warning: warning: sprintf() is often misused, please use snprintf()
/usr/local/lib/libQt5Core.so.2.0: warning: warning: rand_r() is not random, it is deterministic.
/usr/local/lib/libQt5Core.so.2.0: warning: warning: rand() may return deterministic values, is that what you want?
/usr/local/lib/libboost_filesystem.so.6.0: warning: warning: strcpy() is almost always misused, please use strlcpy()
/usr/local/lib/libgobject-2.0.so.4200.4: warning: warning: strcat() is almost always misused, please use strlcat()
/usr/local/lib/libglib-2.0.so.4200.4: warning: warning: vsprintf() is often misused, please use vsnprintf()
/usr/bin/ld: warning: libxcb.so.4.0, needed by /usr/X11R6/lib/libXext.so.13.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libglapi.so.0.2, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXdamage.so.4.0, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXfixes.so.6.0, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libX11-xcb.so.2.0, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libxcb-glx.so.1.1, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libxcb-dri2.so.1.1, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXxf86vm.so.6.0, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libdrm.so.7.4, needed by /usr/X11R6/lib/libGL.so.17.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libfreetype.so.28.0, needed by /usr/local/lib/libharfbuzz.so.8.7, not found (try using -rpath or -rpath-link)
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XF86VidModeQueryVersion'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_disconnect'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmCommandWriteRead'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_writev'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_create_context_attribs_arb_checked'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Init_FreeType'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmGetVersion'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Reference_Face'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_are_textures_resident_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_get_dispatch'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmFreeDevices'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Load_Glyph'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Done_Face'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Var_Blend_Coordinates'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_connect'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_New_Memory_Face'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_generate_id'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Kerning'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Char_Index'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_wait_sbc_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_get_proc_offset'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Advance'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmGetDevices'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_poll_for_event'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmOpenOnce'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_are_textures_resident_data_length'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XGetXCBConnection'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_wait_for_reply64'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_query_server_string'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Face_GetCharVariantIndex'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_wait_for_event'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_swap_interval'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_render_large'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Glyph_Name'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Select_Charmap'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_get_msc_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_Dispatch'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_connect_to_display_with_auth_info'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_get_string_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_render'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_query_server_string_string_length'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_query_server_string_reply'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_get_setup'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XFixesCreateRegion'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmGetMagic'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_get_string_string'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_client_info'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Load_Sfnt_Table'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_query_version'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmUnmap'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_get_string_string_length'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmMap'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Done_FreeType'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_swap_buffers'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Set_Char_Size'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_set_client_info_2arb'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Set_Transform'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_query_version_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_wait_msc_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_swap_buffers_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_is_direct'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_set_client_info_arb'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmFreeVersion'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_get_dispatch_table_size'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_check_multithread'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_swap_buffers_unchecked'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Set_Var_Blend_Coordinates'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_wait_msc_unchecked'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XFixesDestroyRegion'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_get_string'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XDamageQueryVersion'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_query_server_string_string'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_connection_has_error'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XDamageAdd'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_is_direct_reply'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_are_textures_resident'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_get_file_descriptor'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_flush'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_set_context'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmGetDevice'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_get_proc_address'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_glx_are_textures_resident_data'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_wait_sbc_unchecked'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_get_maximum_request_length'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_poll_for_reply64'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Name_Index'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_parse_display'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmFreeDevice'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_MM_Var'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `_glapi_set_dispatch'
/usr/X11R6/lib/libX11.so.16.1: undefined reference to `xcb_take_socket'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_request_check'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `XF86VidModeGetModeLine'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `xcb_dri2_get_msc_unchecked'
/usr/X11R6/lib/libGL.so.17.1: undefined reference to `drmCloseOnce'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:3632: qt/bitcoin-qt] Error 1
gmake[2]: Leaving directory '/usr/src/bitcoin/src'
gmake[1]: *** [Makefile:9254: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/src/bitcoin/src'
gmake: *** [Makefile:738: all-recursive] Error 1
# 

This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. The bitcoin client build failed.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: OpenBSD 6.1
- CPU: QEMU
- RAM: 2500M
- Disk size:34.5G
- Disk Type (HD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by laanwj** [comment]
I don't think building the GUI was ever tested on OpenBSD.

In any case your error looks like a conflict between libGL and libdrm shared libraries, we use neither of those directly (only through Qt, I guess). Thus looks like a more general build issue. Can you build other Qt applications?

**Comment by Popkultur** [comment]
I am trying to do the same, I have similar errors.

**Comment by MarcoFalke** [comment]
This should now be supported.

Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
