### ISSUE TITLE
Allow abandontransaction to abandon *old* unconfirmed transactions that are in the local memory pool

### ISSUE THREAD

**Issue by clemtaylor** [bitcoin/bitcoin#11060]
With the recent state of the mempool I have some transactions that have been stuck in the memory pool for about a week due to low fees. The memory pool is not anywhere close to being full, but there is a continuous stream of higher fee transactions in the pool. Abandon transaction is not available because the transactions are in my local memory pool (they are unlikely to be evicted from the memory pool anytime soon).

It would be useful if abandontransaction was enhanced to allow abandoning of in-wallet and in-mempool transactions if they have not been confirmed in for X blocks (where X > 72 hours). It would have to delete the abandoned transaction from the local memory pool in this case.

Additional comments:
Yes, one option is to use zapwallettxes. But it seems like zapwallettxes is way to big of a hammer to deal with this problem, all I really want to do is remove my unconfirmed transactions from my wallet and my local memory pool and then just wait for them to fall out of the global memory pool. Also, using zapwalletxes requires restarting the node.

I did not have RBF enabled when I initially created the transactions, so RBF will not fix the problem.

In this case, CPFP (child pays for parent) is an option, but it was unclear if/how well supported this is by the miners and if not, it would only make the problem worse.

**Comment by TheBlueMatt** [comment]
CPFP is incredibly well-supported by miners, and should absolutely work here. abandon is a somewhat-unsupported option, and generally isn't going to help your problem as double-spending these transactions is unlikely to propagate well without RBF having been set on the initial transactions. In the future, we should be pushing people more towards RBF than abandon, as abandon has significantly more limited success.

**Comment by MarcoFalke** [comment]
Related pull: #10823

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
