### ISSUE TITLE
AI for fee estimation and other parts of the system

### ISSUE THREAD

**Issue by deremeda** [bitcoin/bitcoin#11064]
Just wondering, instead constantly tweaking fee estimation algos which will never be perfect why not to deploy AI to do the work?

**Comment by deremeda** [comment]
@fanquake why close this quik? I'd like to at least hear others opinions, I'm genuinely interested in what people have say about it before I commit more energy into exploring this subject further.

@MarcoFalke Nothing is ever perfect, it would just need to be better than what we have now. Performance is just and engineering problem, distributed AI fee estimation, etc. whereas the black box argument I don't buy. If it's safe to fly a fighter jet or drive a car it's safe to estimate a fee surely. Besides how much random is /dev/random, black box too. I don't mean this to be back and forth discussion. Just wanted to hear peoples gut reaction to the idea.

**Comment by MarcoFalke** [comment]
As long as the problem is possible to solve with "conventional" approaches,
I don't see a reason to throw AI at it.

Of course you are still more than welcome to do research in that direction.

Btw, are you aware that fee estimation was reworked for the upcoming 0.15.0?

**Comment by laanwj** [comment]
What kind of AI?
There are many kinds of machine learning. Which one would be suited? What would be the inputs and outputs? What dataset would you train it on? How would you test it? How would it cope with changing circumstances on the network?
As it is, this issue is akin to saying "why not use computation to do the work".

> Of course you are still more than welcome to do research in that direction.

Exactly. This is research-paper level material, creating a github issue achieves nothing.

**Comment by jnewbery** [comment]
@deremeda there's a new `estimaterawfee` RPC in v0.15. That allows you to extract the raw data that bitcoind is using in its fee estimation algorithm. You can then feed that data into whatever ML you want for your AI fee estimation. See #10543 for details of the API.

Definitely interested to see what you come up with. Fee estimation is a difficult problem so the more approaches the better, but as @MarcoFalke and @laanwj have pointed out, this function should live outside bitcoind.

**Comment by ryanofsky** [comment]
> That allows you to extract the raw data that bitcoind is using in its fee estimation algorithm. 

If you want more raw data then estimaterawfee provides, you can run bitcoin with https://github.com/bitcoin/bitcoin/pull/10443 which logs information about individual transactions. I can also share data from a bitcoin node I've been running with #10443 (a 4.6G log file with transactions going back to Jun 25).

**Comment by gmaxwell** [comment]
Keep in mind the fee estimate needs to not only be accurate it must be resistant to manipulation (e.g. there shouldn't be a way to make it go up except by transacting more and paying more fees)

**Comment by pfergi42** [comment]
> @deremeda there's a new `estimaterawfee` RPC in v0.15. That allows you to extract the raw data that bitcoind is using in its fee estimation algorithm. You can then feed that data into whatever ML you want for your AI fee estimation. See #10543 for details of the API.
> 
> Definitely interested to see what you come up with. Fee estimation is a difficult problem so the more approaches the better, but as @MarcoFalke and @laanwj have pointed out, this function should live outside bitcoind.

I'm curious if anyone know's of anyone attempting to do this. I also feel there is an opportunity to improve fee estimation using ML techniques. All the data is is there, it just needs to be crunched appropriately...

Currently I'm using Blockstreams API and also I really like the Mempool.space fee estimations:
https://mempool.space/api/v1/fees/recommended

But a well trained narrow AI could likely do it even better.
