### ISSUE TITLE
allow pre-HD wallets to switch to HD address generation?

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#11070]
I've been using the same wallet.dat since 2011. I'd like to use HD address generation, but with the current implementation that would mean switching to a new wallet and losing all my transaction history.

Would there be any interest in adding an RPC `generatehdseed` or some such that would enable HD address generation for old wallets, and switch to a new random HD master key for wallets which already use HD generation? It could optionally regenerate the keypool so that all pooled keys are generated from the new HD seed, but should warn that a new backup is required if the poolkey is regenerated.

**Comment by laanwj** [comment]
I think this feature would be useful. Would be great to be able to switch to HD key generation 'from now on'.

**Comment by jonasschnelli** [comment]
Yes. That's possible. Though we need to make sure users know what they do. I could imaging some will switch over the HD and maybe find a way to export the xpriv (via `dumpwallet`) while they then only keep/backup that key and think *they are using HD now*.

Also, with multiwallet, mixed wallets (HD/non HD) could be avoided better while still having a way to access the "old" transaction history.

**Comment by TheBlueMatt** [comment]
I believe we can do this relatively simply with the existing -upgradewallet infrastructure. Just have to enable writing a new HD master key and writing proper documentation to inform users prior to the upgrade (and then I assume GUI would want to also support this).

**Comment by MarcoFalke** [comment]
Related pull: #12560

**Comment by instagibbs** [comment]
can this be closed due to merging of #12560 ?
