### ISSUE TITLE
Autosave mempool to disk while running

### ISSUE THREAD

**Issue by shivaenigma** [bitcoin/bitcoin#11086]
Hi,

The feature to save mempool to disk on shutdown is great! This feature however, doesn't help where it could be most useful ie.. crashing/unplanned kill of bitcoind process. I had my bitcoin node crash after 30 days of running and the mempool loaded from disk was ofcourse of no use!

This is to request:

- Frequent autosaving of mempool to disk 
_AND/OR_
- RPC command to trigger save of mempool to disk

**Comment by laanwj** [comment]
> Frequent autosaving of mempool to disk

This was part of the initial PR #8448 that implemented mempool saving to disk, but was deemed too much of an I/O overhead by default. It'd be okay as an optional setting.

> RPC command to trigger save of mempool to disk

Yeah or that...

**Comment by gmaxwell** [comment]
I think RPC would be better.  Then you can just cron it to run whenever you want... 

I think the original PR got cut back more than it needed to just to deflect the wall of criticism being thrown at it.

As an aside, if your node is crashing we'd like to know about it, as that shouldn't happen!

**Comment by shivaenigma** [comment]
@gmaxwell I will check if I can get something from the logs about the crash (it is a rare event though) !
