### ISSUE TITLE
Adding replay protection to btc1 client

### ISSUE THREAD

**Issue by MrHash** [bitcoin/bitcoin#11096]
Requesting assistance to implement replay protection on BTC1 fork at https://github.com/btc2x/bitcoin. I've already merged in the wipeout protection PR. Reference issue https://github.com/btc1/bitcoin/issues/113.

Admittedly I don't really know what i'm doing but it seems like a good idea at the moment and in the spirit of decentralized development. thanks

**Comment by windsok** [comment]
Hi @MrHash , you might want to collaborate with https://github.com/NYAcoin/bitcoin on this.
