### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by eMosbat** [bitcoin/bitcoin#11104]
I am getting this error when compile win64 version in ubuntu server 16.04:

Making all in src
make[1]: Entering directory '/home/coin/bitcoin-0.14.2/src'
make[2]: Entering directory '/home/coin/bitcoin-0.14.2/src'
make[3]: Entering directory '/home/coin/bitcoin-0.14.2'
make[3]: Leaving directory '/home/coin/bitcoin-0.14.2'
make[3]: Entering directory '/home/coin/bitcoin-0.14.2/src/secp256k1'
make[3]: Leaving directory '/home/coin/bitcoin-0.14.2/src/secp256k1'
  CXX      libbitcoin_server_a-httprpc.o
In file included from support/allocators/secure.h:9:0,
                 from key.h:11,
                 from base58.h:18,
                 from httprpc.cpp:7:
./support/lockedpool.h:195:18: error: âmutexâ in namespace âstdâ does not name a type
     mutable std::mutex mutex;
                  ^
./support/lockedpool.h:228:17: error: âonce_flagâ in namespace âstdâ does not name a type
     static std::once_flag init_flag;
                 ^
./support/lockedpool.h: In static member function âstatic LockedPoolManager& LockedPoolManager::Instance()â:
./support/lockedpool.h:215:9: error: âcall_onceâ is not a member of âstdâ
         std::call_once(LockedPoolManager::init_flag, LockedPoolManager::CreateInstance);
         ^
./support/lockedpool.h:215:24: error: âinit_flagâ is not a member of âLockedPoolManagerâ
         std::call_once(LockedPoolManager::init_flag, LockedPoolManager::CreateInstance);
                        ^
Makefile:5306: recipe for target 'libbitcoin_server_a-httprpc.o' failed
make[2]: *** [libbitcoin_server_a-httprpc.o] Error 1
make[2]: Leaving directory '/home/coin/bitcoin-0.14.2/src'
Makefile:8888: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/coin/bitcoin-0.14.2/src'
Makefile:677: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by laanwj** [comment]
Yes, unfortunately this is a known issue - see #8653, #8732.
The recommendation is to use trusty (14.04) for cross-compiling for now.
