### ISSUE TITLE
There is a Quantum Computer with 2000Qubits now are we safe? or should we start working Fast?

### ISSUE THREAD

**Issue by kemoantemo** [bitcoin/bitcoin#11105]
Yesterday i red that a company called D-WAVE make a QC with 2000 Qubits
I know that address with the public key unrevealed is safe but what about mining
i thing that a QC would take the most hashrate and make the difficulty sky high even asics won't have a chance to compete so what we should do now o protect Bitcoin from such Attack?

Details For The QC at this link: [https://www.dwavesys.com/d-wave-two-system](https://www.dwavesys.com/d-wave-two-system)

**Comment by promag** [comment]
Good discussion, wrong place.

**Comment by kemoantemo** [comment]
we are not waiting for a QC now there a one so I think we should start working on how to protect Bitcoin not to discuss

**Comment by sipa** [comment]
This is the issue tracker for Bitcoin Core, an implementation of the Bitcoin protocol. Discussions about Bitcoin's future evolution and resistance against certain attacks is off topic here. Feel free to open a discussion on the bitcoin-dev mailinglist.

**Comment by rebroad** [comment]
https://www.technologyreview.com/s/609408/quantum-computers-pose-imminent-threat-to-bitcoin-security/ - bitcoin core defines bitcoin though - so this seems an appropriate venue - including discussion of hard forks to maintain security of the network

**Comment by sipa** [comment]
> bitcoin core defines bitcoin though

Bitcoin Core is an implementation of the Bitcoin protocol. Bitcoin is defined by people who use it, and choose to run certain software.

**Comment by rebroad** [comment]
Also, whenever I have posted to bitcoin-dev about such things, the posts get rejected as any talk about consensus changes is regarded as talk of alt-coins.
