### ISSUE TITLE
Generate segwit address in receive payment tab?

### ISSUE THREAD

**Issue by mb300sd** [bitcoin/bitcoin#11124]
Now that segwit is active, should there be a check box added so the request payment button generates a segwit address? Perhaps a flag on getnewaddress as well, but it's not that inconvenient to call addwitnessaddress if you're already using CLI.

**Comment by laanwj** [comment]
Yes, this should become possible.

**Comment by cedenday** [comment]
An option to make the change address SegWit when you send a transaction would also be nice.

**Comment by Sjors** [comment]
I noticed `addwitnessaddress` happily produces a SegWit address even if its private key has a 'legacy' address with funds.

This seems unsafe to me for two reasons:

1. privacy wise: when the output of both are spent, anyone can see it's the same public key and learn the addresses have the same owner
2. if only one is spent, the public key is known, so you lose the benefit of the public key hash

Would it be better if the UI always creates a new address?

I agree with @cedenday regarding change addresses. Out of scope perhaps, but it might be useful to have a wallet setting "use SegWit". This would cause new (change and receive) addresses to be SegWit by default.

BIP 49 uses different private keys for SegWit vs. non-SegWit addresses. But BIP 44 is a prerequisite for that. See also https://github.com/bitcoin/bips/pull/456#issuecomment-324937956

**Comment by sipa** [comment]
The UI and RPC interface should of course always generate a new key. `addwitnessaddress` is a temporary approach to facilitate testing.

**Comment by justnonamenoname** [comment]
why not to create segwit by default without any checkboxes?

**Comment by cedenday** [comment]
Apparently some people don't want to.

I think @luke-jr only wants to use it for lightning.

**Comment by luke-jr** [comment]
FWIW, I think the default should probably be to create a segwit address (provided the wallet loaded is of sufficient version). While I do support avoiding using segwit unnecessarily at this time, that should be the decision of the user, and using segwit by default makes sense here.

**Comment by CydeWeys** [comment]
Any updates on this?  I would love to be able to start using segwit.  I've been using Bitcoin Core for over six years (since it was just "Bitcoin"), and I would hate to have to switch to another client, but segwit is a really important feature that I want to use now.

**Comment by sipa** [comment]
Planned for 0.15.1.

**Comment by CydeWeys** [comment]
Awesome, I'm looking forward to it.  Is there a rough release date planned for that yet?  Are we talking a month?  Many months?

**Comment by dooglus** [comment]
@CydeWeys > I would love to be able to start using segwit.

You can already. Get a new receiving address as you would normally, then do:

    Help > Debug Window > Console > addwitnessaddress <address>

That will give you a SegWit address (beginning with a 3) that you can give to the person who is going to pay you.

It's not as convenient as it could be, but if you're in a hurry to start using SegWit, it works.

**Comment by janmande** [comment]
I have chosen this as my first attempt at getting to know, and contributing, to the bitcoin project, but would like some input on how to go about it.

[rpcwallet.cpp](https://github.com/bitcoin/bitcoin/blob/0.15/src/wallet/rpcwallet.cpp) contains the local class Witnessifier that adds a witness script to an address and is used by the addwitnessaddress function.

My idea is to add a new function in [AddressTableModel](https://github.com/bitcoin/bitcoin/blob/0.15/src/qt/addresstablemodel.cpp) called addWitnessRow that behaves the same way as addRow, but uses the Witnessifier class to add the witness script to the address. Is there a reason why Witnessifier class is not exposed in [wallet.h](https://github.com/bitcoin/bitcoin/blob/0.15/src/wallet/wallet.h) which AddressTableModel allready depends on?

**Comment by MeshCollider** [comment]
@janmande, @sipa has already taken this under his wing, but thank you for your interest in helping, there are plenty more issues to claim as a first contribution :)

**Comment by janmande** [comment]
Thanks for the update @MeshCollider, I'll take a look at his ( @sipa ) solution when it's done and look for other issues to dig into.

**Comment by CydeWeys** [comment]
How's this looking now?  It's been almost two months since the last update.  I'm eagerly awaiting the ability to author segwit transactions through the GUI.

**Comment by sipa** [comment]
Feel free to help review and/or test the patch: https://github.com/bitcoin/bitcoin/pull/11403

A previous patch (which adds support for Bech32 addresses internally) was already merged in master but is not in a release yet: https://github.com/bitcoin/bitcoin/pull/11167

**Comment by CydeWeys** [comment]
So it's looking like this is currently scheduled for May?  That's ... unfortunate.  Segwit locked in in August, meaning that GUI implementation will be lagging by a minimum of three quarters.  Segwit transaction adoption will remain low until segwit becomes the default transaction type in all major wallets, and Bitcoin Core is of course the biggest of them all.

I'm curious about the prioritization here.  Bottlenecked transaction throughput and the resultant high fees are big problems facing Bitcoin, and are driving users away to altcoins like BCH.  Segwit is part of the fix for this problem, and yet we're not seeing anything close to the same fervor in making segwit usable to end users as we saw in getting it locked in in the first place.

Should we be recommending that people switch to using wallets with full segwit support, like Electrum?  I've been using Bitcoin Core since 2011, and I trust it, but at this point I'm seriously considering switching instead of waiting at least half a year.

**Comment by CydeWeys** [comment]
And Peter, this comment isn't particularly directed at you.  You've done lots of excellent work over the years.  I'm just ranting about the situation in general.  Companies are making billions of dollars off of Bitcoin, most of them using this exact software, yet few seem willing to invest engineering effort back into the ecosystem even for such important benefits as ~doubling transaction volume through global adoption of segwit.

**Comment by achow101** [comment]
@CydeWeys The release schedule is not necessarily accurate. While we normally do a time based release, 0.16 will likely be a feature based release and released whenever it is ready which will probably be some time before May.

**Comment by montvid** [comment]
Yes, it is a big shame that the project adopts segwit but forgets to fix the gui wallet. And then Greg Maxwell dares to say that people don't seem to care about lower fees @ https://www.youtube.com/watch?v=EHIuuKCm53o&feature=youtu.be&t=1h15m06s

**Comment by jonasschnelli** [comment]
Since #11403, it's selectable via startup argument, config. A GUI setting is proposed in #11937.

**Comment by laanwj** [comment]
Closing, this is implemented in #11991
