### ISSUE TITLE
Sendtoaddress flag for sending change to a segwit address?

### ISSUE THREAD

**Issue by cryptogenesis** [bitcoin/bitcoin#11134]
Hi all,

Congratulations and fantastic work with segwit!

I believe uptake would be much faster if there was a possibility of flagging the sendtoaddress call to send change to a segwit address. Currently the only way to accomplish this is to use raw transactions which makes it quite a bit more complicated for the average user/business owner.

Thank you all for the continued efforts,

Evan

**Comment by coinables** [comment]
Concept ACK

**Comment by sipa** [comment]
This feature is planned for the next minor release (after 0.15.0, whose feature freeze has already passed).

**Comment by luke-jr** [comment]
Probably it should use the same output form as the real destination, at least initially?

**Comment by dooglus** [comment]
It's not possible to tell whether the real destination is a segwit address or not in general, and I don't see why it matters.

**Comment by RHavar** [comment]
> It's not possible to tell whether the real destination is a segwit address or not in general

You can tell it's p2sh though. And do the same with your change

> and I don't see why it matters

Privacy. It makes it harder to tell to tell which address is change and which address is the "send".

I think it's a good idea (to support as a non-default option), but doubt it's worth the implementation cost

**Comment by sipa** [comment]
Is there a strong reason to be able to change the style of change on a per transaction basis? (as opposed to a config option)

**Comment by RHavar** [comment]
> Is there a strong reason to be able to change the style of change on a per transaction basis? (as opposed to a config option)

One case, when sending to an X  address (where X is p2sh/p2wsh/p2pkh), I'd like to use X change. (To make it less obvious which is change and which isn't). 

I guess though that could be a config option ("match change"?) or something though. (And I would suggest that that should even be the default)

**Comment by MarcoFalke** [comment]
Note that after #11403 it is possible to set the change type for all sentoaddress calls. Though, not on a per-call-basis.

```
./src/qt/bitcoin-qt -regtest -changetype=bech32 -server &
./src/bitcoin-cli sendtoaddress $(./src/bitcoin-cli getnewaddress) 1  # Sends to legacy address and change to bech32 address
```

**Comment by MarcoFalke** [comment]
Note that there is also a way to do this automatically when another output is bech32. See #12119

I don't think it makes sense to add another option to `sendtoaddress` to allow setting the change type on a per-call basis.

**Comment by promag** [comment]
See #12194.

**Comment by MarcoFalke** [comment]
#12194 is about fundrawtransaction, this issue is about sendtoaddress

**Comment by MarcoFalke** [comment]
Removing this from the 0.16 milestone, since  #11489 was untagged also.

**Comment by jnewbery** [comment]
I believe the type of change for `sendtoaddress` will now be determined by the `-changetype` parameter, as described in #12119.

I've tried this and I'm able to get bech32 change addresses using the `sendtoaddress` RPC.

@cryptogenesis - do you still need this issue to be open?

**Comment by MarcoFalke** [comment]
It is not possible on a per-call basis, but I don't think that is heavy enough to keep this issue open.
