### ISSUE TITLE
Coin Control doesn't recognize my segwit address as a valid change address

### ISSUE THREAD

**Issue by grant-olson** [bitcoin/bitcoin#11137]
### Describe the issue

1. Open wallet on testnet.
1. Create an address.
2. run addwitnessaddress with new address.
3. Send money with coin control enabled:
    * Check 'Custom Change Address'
    * Specify segwit address

### Expected behaviour

Should work just fine.

### Actual behaviour

1. Get a warning saying I don't control this address, and presumably won't actually get the change.

2. I do get the change.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?

0.14.2

![screen shot 2017-08-25 at 12 15 35 pm](https://user-images.githubusercontent.com/255776/29722523-225e2a30-898f-11e7-8e00-91f52c2df5f3.png)

**Comment by grant-olson** [comment]
Confirmed issue is still there in 0.15.0-rc2.

**Comment by dooglus** [comment]
This also happens on livenet v0.15.0rc2.

**Comment by dooglus** [comment]
The same happens if you try to send change to any multisig address, even if you own all the keys.

The code is checking for the existence of a private key for the address directly:
    `wallet->HaveKey(address)`
rather than using IsMine() which is more sophisticated, and knows about SegWit, multisig, etc.

**Comment by dooglus** [comment]
commit ffe14720573f2d99e808c13cfdab5899c24ec8bf seems to fix the problem. `havePrivKey()` is only used in this one place, and it's the wrong function to use.
