### ISSUE TITLE
addwitnessaddress fails with v0.15.0rc2

### ISSUE THREAD

**Issue by clemtaylor** [bitcoin/bitcoin#11146]
On the console I do:
```
getnewaddress
<address 1...>
addwitnessaddress <addr-from-getnewaddress>
Public key or redeemscript not known to wallet, or the key is uncompressed (code -4)
```
I expected this to produce a segwit witness address, I saw examples of other people doing the same thing with v0.15.x and it worked.

I'm using a wallet from 2011, but I recently flushed out the keypool, so all the keys should have been generated with 0.14.2.

Using client compiled from v0.15.0rc2 git tag on x86_64 linux (fedora 26)

**Comment by sipa** [comment]
Your old wallet may be using uncompressed keys if you never upgraded it using `-upgradewallet`. Such keys cannot be used in SegWit.

**Comment by clemtaylor** [comment]
Okay, I used -upgradewallet (saw "Performing wallet upgrade to 60000" in the log).

I repeated the above test got the same error.

So now I have to call getnewaddress 1000 times to find an compressed key I can use with segwit? Ouch.

I guess it is time to dump my wallet, filter out all the unused keys and import the used keys into a new wallet.

**Comment by achow101** [comment]
Changing your password would also make an entirely new keypool which would have uncompressed keys. So I think if you changed your password (or set one), you would get new addresses for which you could use `addwitnessaddress` with.
