### ISSUE TITLE
Migrate sync module to use standard c++11 locking mechanisms

### ISSUE THREAD

**Issue by danra** [bitcoin/bitcoin#11166]
### Describe the issue
Currently, the sync module uses the boost-defined `condition_variable`, `mutex` and `recursive_mutex`. Since all of these are available in the standard library since C++11, we should migrate the sync module to use the standard classes instead.

### What version of bitcoin-core are you using?
commit 7fd49d01dc2ea444ba4d81d0cfa17486b03c8515

**Comment by practicalswift** [comment]
@danra Please take a look at #10866 and more specifically f01ea9326bc69d4f731a5904881740308c5e4271 :-)

**Comment by fanquake** [comment]
Fixed by #10866.
