### ISSUE TITLE
0.15 release note TODOs

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#11174]
Should the 0.15.0 release notes contain a section detailing the current SegWit support?

* addwitnessaddress is a testing/expert RPC, which does not guarantee recovery from backup
* More complete support is coming in a next version

Also:
< gmaxwell> mental note: we need release notes on the topup stuff and instructions for rescanning

**Comment by MarcoFalke** [comment]
* Add release notes for how to rescan an encrypted wallet in 0.15.

**Comment by achow101** [comment]
I think this can be closed now
