### ISSUE TITLE
compile Mac version in Linux?

### ISSUE THREAD

**Issue by eMosbat** [bitcoin/bitcoin#11189]
Is it possible to cross-compile for Mac in linux? and if yes, How?

**Comment by MarcoFalke** [comment]
I'd assume the easiest would be to run the gitian script for deterministic cross platform builds.

**Comment by eMosbat** [comment]
I dont want to use gitian

**Comment by jonasschnelli** [comment]
It also works without gitian.
Just – on Linux – compile the `depends/` for OSX (`make -C depends HOST=x86_64-apple-darwin11`).
Also make sure you have `SDKs/MacOSX10.11.sdk` installed (https://github.com/bitcoin/bitcoin/blob/master/doc/README_osx.md).

Then compile with the prefix set to you depends compiler directory (`./configure --prefix=`pwd`/depends/x86_64-apple-darwin11`).

**Comment by eMosbat** [comment]
what about older version of bitcoin that doesnt have `depends`?

**Comment by MarcoFalke** [comment]
@eMosbat Those are EOL for a long time: https://bitcoincore.org/en/lifecycle/

**Comment by Lightningcash-dev** [comment]
sudo apt-get update

sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3

sudo apt-get install libboost-all-dev

sudo apt-get install software-properties-common

sudo add-apt-repository ppa:bitcoin/bitcoin

sudo apt-get update

sudo apt-get install libdb4.8-dev libdb4.8++-dev

sudo apt-get install libminiupnpc-dev

sudo apt-get install libzmq3-dev

sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler

sudo apt-get install libqrencode-dev

sudo apt install python-pip

pip install setuptools

sudo apt install cmake

sudo apt install libcap-dev

sudo apt install libbz2-dev

make -C depends HOST=x86_64-apple-darwin11 -j8   ( the number 8 is in fact the number of cpus you have )

./autogen.sh

./configure --prefix=$PWD/depends/x86_64-apple-darwin11 --disable-tests --disable-bench --disable-gui-tests

make -j8

**Comment by Original-Tasty** [comment]
> 
> 
> sudo apt-get update
> 
> sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3
> 
> sudo apt-get install libboost-all-dev
> 
> sudo apt-get install software-properties-common
> 
> sudo add-apt-repository ppa:bitcoin/bitcoin
> 
> sudo apt-get update
> 
> sudo apt-get install libdb4.8-dev libdb4.8++-dev
> 
> sudo apt-get install libminiupnpc-dev
> 
> sudo apt-get install libzmq3-dev
> 
> sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
> 
> sudo apt-get install libqrencode-dev
> 
> sudo apt install python-pip
> 
> pip install setuptools
> 
> sudo apt install cmake
> 
> sudo apt install libcap-dev
> 
> sudo apt install libbz2-dev
> 
> make -C depends HOST=x86_64-apple-darwin11 -j8 ( the number 8 is in fact the number of cpus you have )
> 
> ./autogen.sh
> 
> ./configure --prefix=$PWD/depends/x86_64-apple-darwin11 --disable-tests --disable-bench --disable-gui-tests
> 
> make -j8

HAving error:

`fatal error: 'unistd.h' file not found`

at  make -C depends HOST=x86_64-apple-darwin11 -j8

**Comment by BlockMechanic** [comment]
Did you include the SDK ?
