### ISSUE TITLE
%1 instead of "Bitcoin core" on the tooltip for the open config file button

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#11197]
reported by solidfox on IRC, english UI

**Comment by esotericnonsense** [comment]
Verified using the binaries from bitcoin-0.15.0rc3-x86_64-linux-gnu.tar.gz

![bitcoind- 1-problem](https://user-images.githubusercontent.com/7999704/29886737-157bb008-8db3-11e7-86cc-3a33d1777e04.png)

**Comment by MarcoFalke** [comment]
Closing, as a fix is already available.
