### ISSUE TITLE
[GUI] Proxies in QSettings storage without a colon cause crashes when options dialog is opened

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#11209]
If `addrProxy` or `addrSeparateProxyTor` do not have a colon in the string somewhere in the QSettings storage, then attempting to open the options dialog will cause the entire program to crash.

I'm not sure if this is really a problem since it is impossible to make those strings not have colons in them from normal operation. In order to replicate this, you must modify what QSettings stores (a conf file in Linux and Registry in Windows).

**Comment by MeshCollider** [comment]
Easy to fix, but yeah I don't think its really an issue if it can only be caused through deliberate tampering. Happy to submit a PR if needed and no one else does though
