### ISSUE TITLE
Error when trying to use bitpay bitcore with Bitcoin Core 0.14.2

### ISSUE THREAD

**Issue by thosuperman** [bitcoin/bitcoin#11202]
### Describe the issue
Transactions value error (U), Unparsed address [0]

#### If so, please list the steps to reproduce below:
1. Install nodejs 4.8.1 and npm

2. Install zeromq3-x 3.2.5

3. npm install bitcore

4. Update to use version 0.14.2:
cd /home/ubuntu/node_modules/bitcore/node_modules/bitcore-node/bin
wget https://bitcoin.org/bin/bitcoin-core-0.14.2/bitcoin-0.14.2-x86_64-linux-gnu.tar.gz
tar -zxvf bitcoin-0.14.2-x86_64-linux-gnu.tar.gz
rm –rf bitcoind
ln -s bitcoin-0.14.2/bin/bitcoind bitcoind

Config:
![2017-08-31_123244](https://user-images.githubusercontent.com/17564259/29907902-930586c6-8e48-11e7-879f-271ef1f3d072.png)

5. Start by command: /home/ubuntu/node_modules/bitcore/bin/bitcored

### Expected behaviour
Show the values look like https://insight.bitpay.com/block/000000000000000089c547e40bac7fff104e46b7dc7ea7031d3bf186b786107a

### Actual behaviour
All of the Transactions value showing as **value error (U)**
Address showing as **Unparsed address [0]**

### Screenshots.
![2017-08-31_122804](https://user-images.githubusercontent.com/17564259/29907833-005137e4-8e48-11e7-8cfa-b7ce4e03c08d.png)
![2017-08-31_122826](https://user-images.githubusercontent.com/17564259/29907841-08f9e698-8e48-11e7-8241-4f0365fe306b.png)

### What version of bitcoin-core are you using?
Bitcoin Core version 0.14.2

### Machine specs:
- OS: Ubuntu 16.04 (Amazon EC2 c4.large)
- CPU: 2 cores
- RAM: 3.75 GB
- Disk size: 360 GB
- Disk Type (HD/SDD): SSD

**Comment by achow101** [comment]
This is a problem with bitcore and insight. That has nothing to do with Bitcoin Core. Please use take this issue to insight and bitcore instead.
