### ISSUE TITLE
Failure at pruneing the blockchain

### ISSUE THREAD

**Issue by Aristondo** [bitcoin/bitcoin#11217]
### Describe the issue
I wanted to prune the blockchain of my Bitcoin Core node to save space in my computer. I tried to follow the intructions in different ways but it apeared to fail in all of them. My version of Bitcoin Core is v0.14..2. An my computer works with Windows 10.
#### If so, please list the steps to reproduce below:
1. First, I opened the comand line console, and tried to introduce the code "-prune=1100"and the console answered "Method not found (code -32601)". I trien to use different methods as will be shown in the screenshots I will send, but none of then worked.
2. Then, as other internet instructions told me, I went to the Bitcoin-Ot and created a new file and named it "bitcoin.conf". I will send you the screenshots.
3. A also wrote "-prune=1100" in it but it did not prune the blockchain either.

### Expected behaviour
I expected to eliminate the old blocks of the blockchain to save space in the computer.

### Actual behaviour
Nothing of that happened

### Screenshots.
![bitcoin comand line](https://user-images.githubusercontent.com/31550172/29994489-9b42f83a-8fd0-11e7-87aa-78057a904b33.png)
![bitcoin qt before](https://user-images.githubusercontent.com/31550172/29994490-9f233b2c-8fd0-11e7-8511-cbb9f4b12a05.png)
![bitcoin qt after](https://user-images.githubusercontent.com/31550172/29994491-a2c0a5da-8fd0-11e7-9d26-44bb83d0796b.png)
![bitcoin conf](https://user-images.githubusercontent.com/31550172/29994492-a81710fa-8fd0-11e7-965b-d8446ae1bfce.png)
### What version of bitcoin-core are you using?
General
Client version: v0.14.2
User agent: /Satoshi:v0.14.2/
Using Berkeley DB 4.8.30: (April 9, 2010)
Datadir: C:\Users\ander\AppData\Roaming\Bitcoin
Startup time: sáb sep 2 10:59:22 2017
Network
Name: main
Number of conections: 8 (In: 0 / Out: 8)

**Comment by MarcoFalke** [comment]
Make sure not to use the dash-prefix for options set in the conf file. So `-key=value` becomes `key=value\newline` in the conf file.

**Comment by Aristondo** [comment]
So, Marco, in the conf file I should write: "prune=1100..." and then what more. Sorry I am not a computer programing expert.

**Comment by MarcoFalke** [comment]
Yes, try removing the leading dash (`-`) and see if it helps.

**Comment by Aristondo** [comment]
I have tried but it did not work

**Comment by jonasschnelli** [comment]
You can either start bitcoin-qt with `-prune=<target in MB>` or add this to your `bitcoin.conf` (no `-` there).

If you use `-prune=1`, you can then prune your blockchain manually by calling `pruneblockchain <target in MB>` via RPC or RPC-Console.
If you use a value larger then 550, it will auto-prune to that target (in MB). 550 is the minimal value (that ensures 288 blocks/undos for reorgs).

**Comment by Aristondo** [comment]
@jonasschnelli @MarcoFalke. As I have said, I am not a computer expert, but I tried to follow those intructions, the best I could. I just desire to see where I did wrong. So my questions are:

-  I have tried both ways in the "bitcoin.conf" file once with "-prune=1100" an the other with "prune=1100" it did not  work in any of those times. Maybe, as I created the file from nothing, shall I place it in another carpet?
- @jonasschnelli, what did you mean at telling me to start bitcoin-qt with "-prune=<target in MB>"?
- Where shall I put the "-prune=1" to be able to manualy prune the blockchain?

**Comment by sipa** [comment]
@Aristondo Did you restart the client?

The config file is only read at startup. Just changing the contents of the file won't have an effect - you need to start the client.

**Comment by Aristondo** [comment]
@sipa So, how shall I restart the client? Do I have to uninstall and then install it again? And I have discovered that in fact I have three files with Bitcoin stuff. I do not know were tu exactly put my "bitcoin.conf" file.
![bitcoin 64](https://user-images.githubusercontent.com/31550172/30066433-2e3ce496-9258-11e7-9293-bb35be2355aa.png)
![bitcoin core](https://user-images.githubusercontent.com/31550172/30066443-31a6e848-9258-11e7-99fe-44257c81befd.png)
![bitcoin](https://user-images.githubusercontent.com/31550172/30066446-345a8fe0-9258-11e7-9db7-dc78a732a2ac.png)

**Comment by sipa** [comment]
The bitcoin.conf file needs to be placed in the data directory: https://bitcoin.stackexchange.com/questions/4006/where-is-the-data-folder-for-bitcoin-qt

To restart the client, exit it, and open it again. No need to reinstall.

I'm closing this issue, this is not a support site. Use https//bitcoin.stackexchange.com for community questions.

**Comment by MarcoFalke** [comment]
You can also wait for 0.15.0, which will land end of next week and then go to "Settings">"Options">"Open Configuration File" to make sure you open the correct file.
