### ISSUE TITLE
Crosscompiling with the latest UOW Bash doesn't work.

### ISSUE THREAD

**Issue by neobitz** [bitcoin/bitcoin#11211]
When will you release the updated documentation for building bitcoin on Windows 10? Since there are many errors when we follow the existing documentation in doc/build-windows.md

**Comment by jonasschnelli** [comment]
@neobitz: it seems that you have done it, why not try to update the `build-windows.md` yourself and create a pull request?

**Comment by fanquake** [comment]
Should be handled by #11244, and notes in #8732, which we might have to pull into the build docs.
