### ISSUE TITLE
(Suggestion) Choose lower fee if the amount to be sent is small

### ISSUE THREAD

**Issue by i-rme** [bitcoin/bitcoin#11223]
I'll be brief, suppose this case:

Bob wants to send 10 USD to Alice. (2.2 mBTC)
Bitcoin Core estimates fee in 2.5mBTC/kB to be confirmed in the next 2 blocks. (That is 3.80 USD for 300 bytes).
**As fee is more than 10% of the sent amount, Bitcoin Core should choose a lower fee for this single transaction.**
Bitcoin Core chooses the 11 block fee, that is 0.6mBTC/kB to be confirmed in the next 11 blocks (That is 0.93 USD for 300 bytes).
Bitcoin Core displays a warning to Bob explaining the situation.

**Bob pays lower transaction fee** (9% fee Vs 38% fee). Bob is happy.

This should be the default behaviour, the user can later change the fee if he wants to.

**Comment by AllanDoensen** [comment]
Fees are bitcoins biggest issue. But this is just going to cause the small transactions to never confirm.

**Comment by i-rme** [comment]
It will confirm in 11 blocks, that is the recommended fee from Core.

**Comment by AllanDoensen** [comment]
It *may* confirm in 11 blocks, it may confirm next weekend when the mempool goes down, or it may never confirm causing Bob to have to change/add an extra tx to get it unblocked.
