### ISSUE TITLE
verifytxoutproof can return witnesses but cannot verify them

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#11242]
This is very unexpected and could result in some applications being confused. We should likely provide an option to generatetxoutproof to also provide a witness SPV proof, and remove the witness in verifytxoutproof unless the witness proof is present.

**Comment by sdaftuar** [comment]
verifytxoutproof only returns txids, not wtxids, and it only verifies that a txid is in the chain, and not that a given wtxid is in the chain.

So I think it does the right thing (maybe could use better documentation), and we should just consider adding a way to generate/verify proofs that a given wtxid is in the chain.  (See also #10350.)

**Comment by pinheadmz** [comment]
This is a good idea and seems like something we should support. The output would need to prove the entire coinbase tx and then include a wtxid proof to the witness commitment. `merkleblock` is well-documented but this extra proof might need a BIP spec even if its just for an RPC. 

Are there any other uses for merkleblock proofs outside of SPV wallets? There hasn't been any more discussion on this issue for 6 years and we have client-side filtering available now which doesn't require proofs at all... so I wonder if this is important enough to work on or if we can close as wont-fix ?

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.
