### ISSUE TITLE
Feature request: allow GET requests in the RPC

### ISSUE THREAD

**Issue by 3s3s** [bitcoin/bitcoin#11254]
I suggest making the GUI part of the wallet as html page. Desctop application (bitcoin-qt) looks unusual for new users who are used to online banking.
For this, it is sufficient to allow GET requests in the RPC module.

**Comment by laanwj** [comment]
No, we will not use HTML in the bitcoin core client. It might look unusual but that is small fries compared with the security issues with interfacing with a browser, or (snicker) integrating one.
