### ISSUE TITLE
unclear GUI message in sychronize screen if progress increase is negative (QT)

### ISSUE THREAD

**Issue by telst4r** [bitcoin/bitcoin#11265]
in the GUI, that dark synchronise screen, if "Progress increase per hour" goes negative, then "Estimated time left until synced" says "%n left", not integers, but '%n'. I was expecting a meaningful wording, like "unknown" or "infinity".

## can you reproduce the problem?
I get this behavour by suspending a non-synced node for a few hours and then restoring it.

### What version of bitcoin-core are you using?
0.15.99

## machine:
Atom 330, 2GB RAM, 5400 RPM HDD, GNU/Linux

**Comment by MeshCollider** [comment]
This will be fixed in already existing PR https://github.com/bitcoin/bitcoin/pull/11237 I believe
