### ISSUE TITLE
bitcoin-qt segmentation fault

### ISSUE THREAD

**Issue by mputter** [bitcoin/bitcoin#11262]
I downloaded and compiled Bitcoin Core from GitHub (Bitcoin Core Daemon version v0.15.99.0-d81dccf)
Bitcoind and cli work fine, but starting up bitcoin-qt fails:

console: Segmentation Fault
KDE menu: after some initialisation, loading block index etc. screen dissappears.

Found possibly something useful for people who understand these log-entries:
/var/log/apport.log
ERROR: apport (pid 6859) Thu Sep  7 11:53:41 2017: executable: /usr/local/bin/bitcoin-qt (command line "bitcoin-qt")
ERROR: apport (pid 6859) Thu Sep  7 11:53:41 2017: executable does not belong to a package, ignoring

/var/log/syslog
[96080.684487] bitcoin-qt[6838]: segfault at 8 ip 00007fdfd5d8aa2d sp 00007ffd949139e0 error 4 in libQt5Widgets.so.5.5.1[7fdfd5b31000+659000]

The debug.log of Bitcoin doesn't reveal useful data.

I'm running Kubuntu:
$ uname -a
Linux enterprise 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by MeshCollider** [comment]
Looks to be related to https://github.com/bitcoin/bitcoin/issues/9683, because that's also a segfault in QTableView::setSortingEnabled() from libQt5Widgets.so.5

**Comment by jonasschnelli** [comment]
@mputter: I guess you don't get the segfault with https://bitcoin.org/bin/bitcoin-core-0.15.0/test.rc3/?
Would you mind compile it with Qt5.7 and test again?

**Comment by albandil** [comment]
I had, too, segfault with 0.15.0-rc3 in Qt5Widgets (Qt 5.9.1 on OpenSUSE Tumbleweed), though in `QAbstractButton::setChecked`. GDB pointed to line 131 of sendcoinsdialog.cpp. I was able to prevent the crashes by adding `ui->groupCustomFee->setId(ui->checkBoxMinimumFee, 1);` between lines 130 and 131 in file sendcoinsdialog.cpp, though I am not sure what it would do. To make it funny even more, it was also enough to update OpenSUSE's build of libQt5Widgets from 5.9.1-2.1 to 5.9.1-5.1 via the package manager. That, too, made the previously faulty binaries miraculously work again.

**Comment by MeshCollider** [comment]
@albandil that sounds like a different issue (only related by the fact they both cause segfaults), would you mind opening another Issue for it?

**Comment by jonasschnelli** [comment]
Probably fixed by #11332

**Comment by mputter** [comment]
I compiled v0.15.0.1 and bitcoin-qt is starting smoothly without issues. No segmentation fault. Consider it solved.
