### ISSUE TITLE
Missing script verification flags in libbitcoinconsensus-0.dll

### ISSUE THREAD

**Issue by sipsorcery** [bitcoin/bitcoin#11263]
Is it intended that the the test set in src/test/data/script_tests.json should be able to be successfully executed against libbitcoinconsensus-0.dll? 

After building from source on Windows the list of flags available in the bitcoinconsensus.h header are missing several of the script verification flags that are using in the JSON tests file, for example STRICTENC, CLEANSTACK, DISCOURAGE_UPGRADABLE_NOPS and others.

The full list looks like it's in src/script/interpreter.h. Are some not included in libbitcoinconsensus for a reason?

**Comment by laanwj** [comment]
> The full list looks like it's in src/script/interpreter.h. Are some not included in libbitcoinconsensus for a reason?

Good question. But yes, that is intentional. Only the ones in consensus.h are consensus flags, and exposed on the interface, the other ones are internal to Bitcoin Core (and can change meaning from release to release, or even disappear).
See #8976.

**Comment by sipsorcery** [comment]
Thx.
