### ISSUE TITLE
Problem with my bitcoin purse

### ISSUE THREAD

**Issue by Godsunyar** [bitcoin/bitcoin#11266]
Dear Sir or Madam!

My name is Yaroslav.
I have a problem with my bitcoin purse.

In the distant 2013 I tried to deal with mining. At that time it was much easier than it is now.
I downloaded the official program (the version I did not remember), installed it on my computer with a powerful, at that time, videocard and mined.
When I decided to stop I had a bit less than 1 btc. Without having any possibility to cash it out I just saved it to my wallet.dat. I did it with the thought in mind that in some time I would restore mining on its base.
Currently, it is already 2 months that I can not restore my wallet. I installed different versions of the software from bitcoin.org, synchronized them, but the balance writes 0.

Can you help me find out the reason of the fact that in 2013 I had some money there (the rate was $ 130) but 0 at the moment?

P.S. The only person who had access to the wallet was me. I even have the exact date I used it for the last time.

**Comment by jonasschnelli** [comment]
Check your transaction history of your coins has been sent away.
Maybe call RPC (debug console) `dumpwallet <filename>` and expect the addresses in that file.

However, this is a user and not a development question and should be posted elsewhere (bitcointalk reddit stackexchange).

**Comment by laanwj** [comment]
That's strange - old wallets should work as-is with new versions.
Does it show any transactions?

Closing this as this is not a support site, but for reporting software bugs, so this shouldn't stay open.
