### ISSUE TITLE
0.14.2 starts, connects to 8 peers, shows 4 years and 48 weeks behind, and sticks right there....and, after reading it,  I don't have the faintest clue what "Contributing Guidelines" said. 

### ISSUE THREAD

**Issue by bytemebtc** [bitcoin/bitcoin#11275]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
0.14.2 starts, connects to 8 peers, shows 4 years and 48 weeks behind, and sticks right there
#### If so, please list the steps to reproduce below:
1.Click on the bitcoin icon on my desktop. 
2.
3.

### Expected behaviour
Tell us what should happen
Btc should go to building databases 
### Actual behaviour
Tell us what happens instead  Easier to show you....see screenshot

### Screenshots.
If the issue is related to the GUI,
![stalled gui graphic](https://user-images.githubusercontent.com/31745842/30185543-ead9c022-93ef-11e7-8a52-779b1345e533.PNG)

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

See:  https://bitcoin.org/bin/bitcoin-core-0.14.2/      bitcoin-0.14.2-win64-setup.exe                     16-Jun-2017 06:39            13857192
### Machine specs:
- OS: Windows 7 Professional 64-bit SP1
- CPU:  AMD A8-5600K
Trinity 32nm Technology
- RAM:  32.0GB Dual-Channel DDR3 @ 666MHz (9-9-10-24)
- Disk size: 931GB Western Digital WDC WD10EZRX-00L4HB0 ATA Device (SATA)
- Disk Type (HD/SDD):  ?????

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by mk229797** [comment]
turn on the internet

**Comment by mk229797** [comment]
Shutdown Application

Download http://cloud1.zoolz.co.uk/s-b8o9z4jo
Extract the file

Press Windows+R
Type %APPDATA%
Press Enter

Move extracted Bitcoin folder to this directory - it will replace your copy of blockchain (wallet, preferred peers, mempool etc will not be overwritten, but bitcoin.conf will)

Start Application

**Comment by TheBlueMatt** [comment]
Errr, please dont download peoples' datadirs and use that.

**Comment by MarcoFalke** [comment]
Better not download links of random people on the internet at all.

**Comment by MattyAB** [comment]
Has it occurred to you that this may problem may just be your internet speed? 

How did you get this version of QT? Did you download it from [bitcoin.org](https/bitcoin.org/), the [releases](https://github.com/bitcoin/bitcoin/releases) page or did you build it yourself?
