### ISSUE TITLE
Bitcoin Core Install for Windows 10 automake-1.15 issue

### ISSUE THREAD

**Issue by darkn00bknight** [bitcoin/bitcoin#11282]
Hi,

I am trying to install the bitcoin client on a Windows 10, following the build-windows.md file. 

The latest version of automake (automake-1.15) seems incompatible with the client files. 

I tried linking automake-1.15 to automake-1.14 but am receiving the following error: 

configure.ac:32: error: version mismatch.  This is Automake 1.15,
configure.ac:32: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:32: comes from Automake 1.14.1.  You should recreate
configure.ac:32: aclocal.m4 with aclocal and run automake again.

Please help.

Thanks,

**Comment by laanwj** [comment]
Seems like something was left behind from the other version. Try `git -f -x -d` to clean your git tree, then retry.

However many people have built Bitcoin Core with automake 1.15 on other platforms, it is an extremely common version. What makes you think it is incompatible?

**Comment by sipsorcery** [comment]
Should be:
> git **clean** -f -x -d

I was able to build trunk on Windows (WSL) up until around the 8th of Sep and then started getting a few different errors which seem related to dependency changes. I'm currently starting from scratch by re-installing WSL, cleaning my bitcoin git repo (to remove all the previous dependencies) and re-running the build steps.

**Comment by fanquake** [comment]
@darkn00bknight Did cleaning your repository solve the issue? Please close this issue if so.
