### ISSUE TITLE
Testnet memory usage ~double that of mainnet (bitcoind v0.15.0rc3)

### ISSUE THREAD

**Issue by esotericnonsense** [bitcoin/bitcoin#11290]
### Describe the issue

When running two pruned nodes, one for mainnet and one for testnet3, the memory usage of the testnet3 daemon is much higher than the mainnet node.

#### If so, please list the steps to reproduce below:

Relevant entries in bitcoin.conf:
```
disablewallet=1
listen=1
rest=1
```
mainnet
```
prune=6480
```
testnet3
```
prune=1024
```

Steps to reproduce:

run `bitcoind -maxmempool=100 -dbcache=16`
run `bitcoind -testnet -maxmempool=100 -dbcache=16`

### Expected behaviour

I would expect memory usage to be relatively equivalent across the two instances.

### Actual behaviour

Immediately after start, mainnet has approx. 250M resident whilst testnet has approx 450M resident.

Both nodes are synced to the latest height (484225 main, 1181354 test).

### What version of bitcoin-core are you using?

v0.15.0rc3 verified signed binaries from bitcoin.org/bin.

### Machine specs:

Linode 1024 VPS, Ubuntu 16.04 LTS with 1GB RAM, 20GB SSD.

**Comment by achow101** [comment]
Testnet has way more blocks and occasionally way more spam as people test random stuff on testnet. I don't find this really all that surprising.

**Comment by fanquake** [comment]
I agree this isn't really an issue. Testnet is exactly for testing random stuff, spamming, trying to break things. It can also be reset, in which case the resource requirements can change dramatically. Closing this.
