### ISSUE TITLE
Prune undermines the dbcache.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#11315]
17:13:01 < esotericnonsense> Aaaaand: in particular what was happening for me was that the utxo cache seemingly was being dropped on every   prune event
17:13:18 < esotericnonsense> so with prune off, it'd build up to 2-3GB or more, with it on, it'd never go above 300mb or so

We should probably add the dbcache size to the amount of extra blockdata that prune lets the blocks and disk take up over the pruning size... so that pruning doesn't undermine the user's dbcache settings.

**Comment by esotericnonsense** [comment]
Additional information on how this happened:

0.15.0rc3 running on a Linode VPS with prune=6480 dbcache=8000.

debug.log would indicate cache dropping on every prune event as stated.

When raising prune to 64800, the behaviour stopped happening until hitting the new prune target.

Sounds like gmaxwell's identified the issue already though.

**Comment by Sjors** [comment]
I've been some benchmarking in https://github.com/bitcoin/bitcoin/pull/12404#issuecomment-390595338. So far it appears that reducing the number of flush events if helpful, but reducing them too much appears counter productive, for reasons I don't understand yet.

**Comment by Sjors** [comment]
Continued discussion in #15265
