### ISSUE TITLE
Attempting to create new non-HD wallet ignores -usehd=0 without warning

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#11313]
Built against `master` branch 801dd40666d1e6009920ad3ff755c7bb993b2a62:

If I have no wallet.dat file and run:

    bitcoind -usehd=0

A new wallet.dat file is created and an HD seed is assigned.

I see an error message in the source:

    "Error loading %s: You can't disable HD on an already existing HD wallet or create new non-HD wallets."

but that doesn't get shown because `fFirstRun` is true, and so the code which checks for `-usehd` values doesn't run.

If it's no longer possible to create non-HD wallets, specifying -usehd=0 when creating a wallet should be an error, and not get silently ignored.

**Comment by MarcoFalke** [comment]
#11307

**Comment by dooglus** [comment]
Thanks. I missed that one.

I was hoping to be able to create a pre-HD wallet to test #11085, but I see that is no longer an option. Any ideas how I can write a test that converts a pre-HD wallet to an HD wallet when -usehd has gone away?

**Comment by achow101** [comment]
> Any ideas how I can write a test that converts a pre-HD wallet to an HD wallet when -usehd has gone away?

You could make a small non-hd wallet file and test the upgrade for that.
