### ISSUE TITLE
Running bitcoind daemon on 32-core CPU.

### ISSUE THREAD

**Issue by tw4w3t** [bitcoin/bitcoin#11321]
Hello! I'm launching a crypto currency pool. And when it works, bitcoin consumes half of its total processing power. I have a 32-core processor on the server. And I get the impression that bitcoin uses only one or a couple of cores, and does not know how to work with all cores.
Here is the timetable for bitcoin.
![screen shot 2017-09-13 at 19 32 32](https://user-images.githubusercontent.com/18491324/30389036-6862cfa6-98ba-11e7-8b72-4c61f05a2993.png)
Apparently, in the peak we connected the ASIC. And all this time bitcoin worked only with a couple of cores of my CPU.

**Comment by TheBlueMatt** [comment]
There are very few things bitcoind does which gain significantly from core count as high as 32, especially given the latency involved in passing messages between the cores. Simply "using too few cores" isnt a bug :p.
