### ISSUE TITLE
bitcoind crashes if RPC is spammed

### ISSUE THREAD

**Issue by esotericnonsense** [bitcoin/bitcoin#11322]
bitcoind v0.15.0rc3 (signed binaries), Arch Linux rolling amd64 with 16GB RAM

Upon attempting to connect to the JSON-RPC mechanism using the Python requests library, bitcoind dies unexpectedly;
```
terminate called without an active exception
Aborted (core dumped)
```

debug.log
```
2017-09-13 16:50:28 libevent: evhttp_read_cb: illegal connection state 7
```

(no other relevant entries).

I cannot reproduce this at the moment, if I manage it I will update this issue.

edit: Reproduction steps as follows:

```
while True:
    r = requests.get("http://localhost:8332", data=json.dumps({}))
```

Any payload passed seems to trigger it, passing no payload does not trigger the crash.

Obviously, spamming it in a while loop is an extreme case, but I'm curious as to why this happens. It is pretty much immediate.

**Comment by esotericnonsense** [comment]
Okay, narrowing this down a bit more, running with -debug=http;

GET requests with a valid endpoint (e.g. /rest/chaininfo.json) do not appear to cause issues. I've tried 20,000 requests as quickly as python can throw them out from two request threads.

GET requests on / end up in a number of
`Received a GET request for / from [::1]:port`
followed by the libevent illegal connection state.

Occasionally a segfault is caused, other times the 'terminate called without an active exception' error.

**Comment by esotericnonsense** [comment]
I've dug around a bit and been unable to find the problem.
The work queue is not filling up; adding new items is fine; possibly a libevent issue?

**Comment by promag** [comment]
> possibly a libevent issue

Don't know but I doubt. I'll try to reproduce.

**Comment by esotericnonsense** [comment]
Bit more digging:

```
$ nc -l -p 18334
GET / HTTP/1.1                           
Host: localhost:18334                    
User-Agent: python-requests/2.18.4       
Accept-Encoding: gzip, deflate           
Accept: */*                              
Connection: keep-alive                   
Content-Length: 2                        

{}
```

Tweaking cURL to give the same output:
```
for x in {1..2000}; do curl -s -X GET -H "User-Agent: python-requests/2.18.4" -H "Accept-Encoding: gzip, deflate" -H "Accept: */*" -H "Connection: keep-alive" -H "Content-Type:" --data "{}" http://localhost:18332/ > /dev/null; done
```
(the output of nc is identical given this modification, checked with diff).

Can't reproduce using cURL. It does hit the server much more slowly, though.

**Comment by theuni** [comment]
I've been up to my eyeballs in libevent lately, so I'll take this one.

**Comment by theuni** [comment]
I've tracked down the root cause of this and am working on a proper fix.

**Comment by dcousens** [comment]
Cannot reproduce with fa8a0639f7b0ce04030b72b4d5be4f0aa36fc5cb

**Comment by practicalswift** [comment]
@theuni Missing lock? :-)

**Comment by dcousens** [comment]
@theuni was this actually an issue?

**Comment by ITsolution-git** [comment]
Hi @theuni. Did you find any solution to this? Thanks.

**Comment by promag** [comment]
@theuni ping.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
