### ISSUE TITLE
man pages not updated for Release 0.15.0

### ISSUE THREAD

**Issue by plavcik** [bitcoin/bitcoin#11336]
.TH BITCOIN-CLI "1" "February 2017" "bitcoin-cli v0.14.99.0" "User Commands"
.TH BITCOIN-QT "1" "February 2017" "bitcoin-qt v0.14.99.0" "User Commands"
.TH BITCOIN-TX "1" "February 2017" "bitcoin-tx v0.14.99.0" "User Commands"

and also on other places

please update date and version, thank you

**Comment by laanwj** [comment]
Fixed in 7123b95, which will be in 0.15.0.1
