### ISSUE TITLE
Better text for sending transaction option "Request Replace-By-Fee"

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#11344]
### Howto replace a stuck transaction with another with higher fee ?

bitcoind 0.15.0

The marking option "Request Replace-By-Fee" in the sending transaction GUI page should have a better understandable text.

The sender does not "request" anything when creating the transaction. This is just a tag for a later possibility, as I understand as a rather normal user.

I would suggest something like

"Let me increase the fee of this transaction later, if it should not get confirmed in expected time ('Replace-By-Fee' feature)"

**Comment by wodry** [comment]
I have just read https://bitcointechtalk.com/whats-new-in-bitcoin-core-v0-15-part-3-50c42125625e
about "Replace By Fee (RBF)" and I am unsure, if one needs to tag the initial transaction as "Request Replace-By-Fee" or if one should do that only for the second transaction (which has a higher fee) to replace the first one. This is really unclear to me.

**Comment by sipa** [comment]
@wodry The replace by fee policy is described in BIP125. It's the initial transaction that needs be marked as replacable.

**Comment by wodry** [comment]
@sipa Sure, one could also look into the source code to figure it out. This is intended as a feedback on GUI usability :-)

**Comment by flack** [comment]
How about something like "Allow increasing transaction fee later on"?

**Comment by wodry** [comment]
Issue is solved with PR https://github.com/bitcoin/bitcoin/pull/11428

**Comment by MeshCollider** [comment]
Please don't close the issue until the corresponding PR is merged, that will be done automatically when the PR gets merged.
