### ISSUE TITLE
rfc: Wallets should be in their own directory

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#11348]
With multi-wallet (both "parallel" RPC multiwallet and "serial" `-wallet`), the situation has become quite confusing. There is no way to list the wallets - the obvious `ls ~/.bitcoin/*.dat` will yield a combination of transient state files as well as wallets. This is quite annoying when doing backups, for example.

So at least for new installs I'd propose to set the wallet bdb root to `~/.bitcoin/wallets`. If this directory does not exist, it should fall back to just using the data directory. Another option would be a one-time move, but that doesn't need to be in the first iteration.

Also it would be useful to override the wallet directory with an option, say `-walletdir`, for people that want to store the wallets on a separate file system without potentially hazardous symlink tricks. Implementing just this for a start, and not changing the default, would be fine too.

(Another idea would be to introduce a random component into the wallet-dir name, like firefox does with profile directories `~/.mozilla/firefox/1naf6a1d.default`, this makes it slightly harder to steal a wallet file if all you can do is guess paths - but I digress)

(see also discussion in #10885 and #11343)

**Comment by esotericnonsense** [comment]
What might be useful along with this is some documentation on files within the .bitcoin directory that are affected by the wallet (not only those with potential for corruption of the wallet itself).

For example - debug.log can contain information on 'interesting' txids (AddToWallet messages, as I recall), and so if you're storing the wallet on another filesystem for the purpose of encrypting pubkeys at rest, a lot of that information will 'leak' into debug.log. This isn't a concern for me in particular, but there are probably many different reasons users would like to store their wallets seperately (it would be useful if those use cases were posted here, I think?)

**Comment by TheBlueMatt** [comment]
Yea, not a fan of the one-time-move thing, but defaulting to creating a wallets folder and having a -walletdir option is definitly where we should be headed.

**Comment by laanwj** [comment]
> What might be useful along with this is some  documentation on files within the .bitcoin directory that are affected  by the wallet (not only those with potential for corruption of the  wallet itself).

Everything bdb logs and scribbles will move along to the walletdir.

> For example - debug.log can contain information on 'interesting' txids (AddToWallet messages, as I recall), and so if you're storing the wallet on another filesystem for the purpose of encrypting pubkeys at rest, even if you've included all BDB state, a lot of that information will 'leak' into debug.log.

It's really difficult to contain metadata within a single computer. If the goal is to hide existence of a certain wallet, my recommendation would be to run the software in a VM with the disk fully encrypted, and having it only communicating over Tor/VPN. There's various ways that information can leak and trying to enumerate them is brittle.

It might be an interesting project for someone but this is certainly not part of the scope of this issue.

**Comment by jnewbery** [comment]
> There is no way to list the wallets

This is something I've thought about before. I think the `listwallets` RPC that we introduced in v0.15 as experimental should be changed to return an object with two key-values: one for loaded wallets, and one for 'available' wallets in the `.bitcoin/wallets` directory

**Comment by gmaxwell** [comment]
sounds good to me in general

**Comment by mrwhythat** [comment]
I'd like to take this, if everyone agrees.

**Comment by jnewbery** [comment]
> I'd like to take this, if everyone agrees.

@mrwhythat: no need to ask for permission to start working on something :)

(although in this case it looks like @MeshCollider has now opened a PR for this at #11466. If you're still interested in this, then reviewing/testing that PR would be a really good way to contribute)

**Comment by mrwhythat** [comment]
@jnewbery, sorry, actually I planned to work on that while in Prague for HCPP17 but as soon as I got there, I completely forgot about it :)

**Comment by DarthJahus** [comment]
> Also it would be useful to override the wallet directory with an option, say `-walletdir`.

This would be amazing to create standalone wallets (on removable hard drives, for example).

**Comment by MeshCollider** [comment]
@DarthJahus keep in mind that it could still be dangerous to use them from removal devices, if the device got removed while core was running you could end up corrupting the wallet

**Comment by laanwj** [comment]
#11466 could use some testing!
