### ISSUE TITLE
Bitcoin Core 0.15.0.1 - failing to compile on Debian Jessie

### ISSUE THREAD

**Issue by knoxcard** [bitcoin/bitcoin#11358]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:

./autogen.sh

./configure --without-gui CPPFLAGS="-I/usr/local/src/bitcoin-0.15.0.1/db/include" LDFLAGS="-L/usr/local/src/bitcoin-0.15.0.1/db/lib"

make <- fails here

### Expected behaviour
Tell us what should happen
I should be able to compile successfully.

### Actual behaviour
Tell us what happens instead
When I run make it crashes and is complaining about the Boost library.  I successfully compiled 0.15.0.0 a few days ago, so I have no idea what's any different.

root@localhost:/usr/local/src/bitcoin-0.15.0.1# make
Making all in src
make[1]: Entering directory '/usr/local/src/bitcoin-0.15.0.1/src'
make[2]: Entering directory '/usr/local/src/bitcoin-0.15.0.1/src'
make[3]: Entering directory '/usr/local/src/bitcoin-0.15.0.1'
make[3]: Leaving directory '/usr/local/src/bitcoin-0.15.0.1'
make[3]: Entering directory '/usr/local/src/bitcoin-0.15.0.1/src/secp256k1'
make[3]: Leaving directory '/usr/local/src/bitcoin-0.15.0.1/src/secp256k1'
  CXXLD    bitcoind
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `GetNumCores()':
/usr/local/src/bitcoin-0.15.0.1/src/util.cpp:880: undefined reference to `boost::thread::physical_concurrency()'
libbitcoin_util.a(libbitcoin_util_a-utiltime.o): In function `sleep_for':
/usr/local/include/boost/thread/pthread/thread_data.hpp:252: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-db.o): In function `copy_file':
/usr/local/include/boost/filesystem/operations.hpp:539: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
Makefile:3624: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory '/usr/local/src/bitcoin-0.15.0.1/src'
Makefile:9265: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/bitcoin-0.15.0.1/src'
Makefile:728: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Debian Jessie
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by achow101** [comment]
Try running `make clean` first before running `make`

**Comment by knoxcard** [comment]
Wowzers, you learn something new everyday!  Thank you so much!

**Comment by knoxcard** [comment]
Problem still persists after make clean...

**Comment by MeshCollider** [comment]
There's been nothing changed between .0 and .1 that would cause something like this, try reinstalling the boost libraries?

**Comment by knoxcard** [comment]
Updated to the latest boost library and tried compiling --with-boost-libs=/path/to/boost/libs and it's still giving me an error, strange.

boost_1_65_1.tar.gz
http://www.boost.org/users/download/

**Comment by jonasschnelli** [comment]
Please pastebin your `config.log` and the output of a "make V=1" here.

**Comment by knoxcard** [comment]
I installed boost 1_55 instead of boost_1_65 and received a different error.  What is the recommended boost library version for Bitcoin?

**Comment by knoxcard** [comment]
Here is the result of make V=1

mv -f leveldb/port/.deps/leveldb_libleveldb_sse42_a-port_posix_sse.Tpo leveldb/port/.deps/leveldb_libleveldb_sse42_a-port_posix_sse.Po
rm -f leveldb/libleveldb_sse42.a
/usr/bin/ar cr leveldb/libleveldb_sse42.a leveldb/port/leveldb_libleveldb_sse42_a-port_posix_sse.o
/usr/bin/ranlib leveldb/libleveldb_sse42.a
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./leveldb -DOS_LINUX -DLEVELDB_ATOMIC_PRESENT -D__STDC_LIMIT_MACROS  -DLEVELDB_PLATFORM_POSIX -I./leveldb/include -I./leveldb/helpers/memenv -I/usr/local/src/bitcoin-0.15.1/bitcoin/db/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o -MD -MP -MF leveldb/helpers/memenv/.deps/leveldb_libmemenv_a-memenv.Tpo -c -o leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o `test -f 'leveldb/helpers/memenv/memenv.cc' || echo './'`leveldb/helpers/memenv/memenv.cc
mv -f leveldb/helpers/memenv/.deps/leveldb_libmemenv_a-memenv.Tpo leveldb/helpers/memenv/.deps/leveldb_libmemenv_a-memenv.Po
rm -f leveldb/libmemenv.a
/usr/bin/ar cr leveldb/libmemenv.a leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
/usr/bin/ranlib leveldb/libmemenv.a
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -std=c++11 -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter  -pthread  -Wl,-z,relro -Wl,-z,now -pie  -L/usr/local/src/bitcoin-0.15.1/bitcoin/db/lib -o bitcoind bitcoind-bitcoind.o  libbitcoin_server.a libbitcoin_common.a univalue/libunivalue.la libbitcoin_util.a libbitcoin_wallet.a  libbitcoin_consensus.a crypto/libbitcoin_crypto.a leveldb/libleveldb.a leveldb/libleveldb_sse42.a leveldb/libmemenv.a secp256k1/libsecp256k1.la -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lboost_chrono -ldb_cxx-4.8 -lssl -lcrypto  -lcrypto  -lminiupnpc -levent_pthreads -levent  -levent
libtool: link: g++ -std=c++11 -Wstack-protector -fstack-protector-all -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o bitcoind bitcoind-bitcoind.o  -L/usr/local/src/bitcoin-0.15.1/bitcoin/db/lib libbitcoin_server.a libbitcoin_common.a univalue/.libs/libunivalue.a libbitcoin_util.a libbitcoin_wallet.a libbitcoin_consensus.a crypto/libbitcoin_crypto.a leveldb/libleveldb.a leveldb/libleveldb_sse42.a leveldb/libmemenv.a secp256k1/.libs/libsecp256k1.a -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lboost_chrono /usr/local/BerkeleyDB.4.8/lib/libdb_cxx-4.8.so -lssl -lcrypto -lminiupnpc -levent_pthreads -levent -pthread  -D__LIBTOOL_IS_A_FOOL__   -D__LIBTOOL_IS_A_FOOL__
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `GetNumCores()':
/usr/local/src/bitcoin-0.15.1/bitcoin/src/util.cpp:878: undefined reference to `boost::thread::physical_concurrency()'
libbitcoin_util.a(libbitcoin_util_a-utiltime.o): In function `sleep_for':
/usr/local/include/boost/thread/pthread/thread_data.hpp:252: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-db.o): In function `copy_file':
/usr/local/include/boost/filesystem/operations.hpp:539: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
Makefile:3615: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory '/usr/local/src/bitcoin-0.15.1/bitcoin/src'
Makefile:9284: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/bitcoin-0.15.1/bitcoin/src'
Makefile:728: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by knoxcard** [comment]
Solved, I realized I had installed a different version of the Boost library which did not match the recommended version for my Debian install.  Boost version 1_55, I had version 1_65_1

sudo apt-get autoremove libboost-all-dev
sudo apt-get install libboost-all-dev

Finally, I was able to recompile successfully!

**Comment by possientis** [comment]
Had exactly the same issue also on Debian Jessie while attempting to build v0.16.0. Also because of a boost upgrade (to 1.66). This thread was very useful, thank you !
