### ISSUE TITLE
Failed to make check on an old Linux: python3: no such file or directory

### ISSUE THREAD

**Issue by Zenitur** [bitcoin/bitcoin#11352]
Running test/util/bitcoin-util-test.py...
../test/util/bitcoin-util-test.py
/usr/bin/env: python3: No such file or directory
make[3]: *** [check-local] Error 127

**Comment by MeshCollider** [comment]
As mentioned in the build instructions, you need to have python3 installed. Install python3 and run again :)

**Comment by Zenitur** [comment]
Was python 2 deprecated?

**Comment by MarcoFalke** [comment]
https://pythonclock.org/

**Comment by Zenitur** [comment]
https://news.ycombinator.com/item?id=7581434

**Comment by Zenitur** [comment]
RHEL 6 & 7 are still using python2. Withal, RHEL6 doesn't have python3 in default repository.

**Comment by MarcoFalke** [comment]
Actually we did not yet deprecate python2 in `make && make check`.

**Comment by Zenitur** [comment]
Thank you!

**Comment by laanwj** [comment]
> RHEL 6 & 7 are still using python2. Withal, RHEL6 doesn't have python3 in default repository.

RHEL 6 doesn't have a c++11 compiler by default either, does it? At least gcc 4.4 is below the minimum version (4.7) we support: https://access.redhat.com/solutions/19458
I guess we care about RHEL 7 though.

**Comment by Zenitur** [comment]
**laanwj**, for RHEL, there is "devtoolset" repository with a later GCC versions. https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/
