### ISSUE TITLE
Raspberry Pi 2 B Segmentation fault

### ISSUE THREAD

**Issue by kyluke** [bitcoin/bitcoin#11364]
### Describe the issue
 - Downloaded Bitcoin from https://bitcoin.org/bin/bitcoin-core-0.15.0/bitcoin-0.15.0-arm-linux-gnueabihf.tar.gz
 - Unpacked and install it using
```
tar -zxf bitcoin-0.15.0-arm-linux-gnueabihf.tar.gz
install -m 0755 -o root -g root -t /usr/local/bin bitcoin-0.15.0/bin/*
```
 - Try to run bitcoind
 - Get hit with ```Segmentation Fault```

### Can you reliably reproduce the issue?
Yes, everytime I run anything bitcoin related
```
bitcoind -testnet -daemon
bitcoind -h
```
### Expected behaviour
Bitcoind should run

### Actual behaviour
just get hit with ```Segmentation fault```.
```~/.bitcoin``` exists as well as ```~/.bitcoin/bitcoin.conf``` with rpcuser and rpcpassword defined.
No log file exists in that directory and nothing is logged to ```/var/log/syslog/```

### Machine specs:
- OS: Raspbian GNU/Linux 8 (jessie)
- CPU: ARMv6-compatible processor rev 7 (v6l)
- RAM: 512MB
- Disk size: 16GB
- Disk Type (HD/SDD): SD Card class 10

**Comment by TheBlueMatt** [comment]
Can you install gdb and run "gdb `which bitcoind`", then type "run" and when the crash happens, "thread apply all bt" and provide the output which gdb prints?

**Comment by kyluke** [comment]
Sure thing, here it is.

```
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/bitcoind...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/bitcoind
Cannot access memory at address 0x0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x7f5dc010 in ?? ()
(gdb) thread apply all bt

Thread 1 (Thread 0xb6fef000 (LWP 16556)):
Cannot access memory at address 0x0
#0  0x7f5dc010 in ?? ()
#1  0x7f5ff010 in ?? ()
Cannot access memory at address 0x0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by esotericnonsense** [comment]
I have an RPi2 here so thought I'd do a quick test to check if it was generalizable.
Unfortunately running Arch not Raspbian, can't reboot it at the moment to test.
Synced to height=4000 on testnet successfully.

**Comment by esotericnonsense** [comment]
I downloaded and verified the binary. There may be some dependencies that I have by 'accident' as the system is also used for other purposes. I doubt that I can assist here - just thought I would check if the ARM build was broken in general.

**Comment by kyluke** [comment]
As a long shot I tried it with the 0.15.0.1 release but I get the same result.

**Comment by kyluke** [comment]
Compiling from source has fixed the problem.

**Comment by theuni** [comment]
> CPU: ARMv6-compatible processor rev 7 (v6l)
> RAM: 512MB

This doesn't look like an rpi2. Either it's running a really conservative/compatible kernel, or it's an earlier model or rpi zero. The 512mb ram tells me it's probably not a kernel issue.

armv7 binaries won't work on v6 hardware without major surgery.

Could you please run: ```cat /proc/cpuinfo``` and paste the result here?

**Comment by kyluke** [comment]
@theuni hmmm.. It seems I installed it on the wrong Pi at home :/.

There most likely isn't anything wrong with the arm binary. Compiling solved my issue on the pi I was running this on. I'm going to close this issue for now. I'll test it on the Pi 2 when I get the chance and then just comment on this again.

My bad.

**Comment by theuni** [comment]
No worries, thanks for confirming.
