### ISSUE TITLE
getblocktemplate fails for regtest mode.

### ISSUE THREAD

**Issue by rustyrussell** [bitcoin/bitcoin#11379]
### Describe the issue

In the lightning tests, we run bitcoind in regtest mode.  ~~~We started seeing intermittent test failures, caused by `generate` not including transactions we had just `sendrawtransaction`ed; this delay is noticeable when there are multiple submitted txs.~~~ (Edit: my test harness fail).  I tried to work around it by polling `getblocktemplate` to see when our txs are included, only to run into this bug :(

1. bitcoind -regtest -testnet=0 &
2. bitcoin-cli -regtest -testnet=0 getblocktemplate

### Expected behaviour

I should get the block template.

### Actual behaviour
error code: -9
error message:
Bitcoin is not connected!

### What version of bitcoin-core are you using?
v0.14.2.0-gfc61c83

**Comment by achow101** [comment]
`getblocktemplate` requires that you are connected to at least one other node.

**Comment by instagibbs** [comment]
I suppose the purpose behind this is so people do not make blocks without knowing the state of the network.

**Comment by jtimon** [comment]
Didn't investigated the issue, but it may be related with the gact that there's no CChainParams::MiningRequiresPeers() exists in 0.14 but not in 0.15 ?
Perhaps it is a regression?

**Comment by rustyrussell** [comment]
@achow101 That's not very sane for regtest, is it?  And the unreliable sendrawtransaction/generate behavior on regtest seems to be most simply fixed by allowing this.

**Comment by TheBlueMatt** [comment]
Did you investigate the unreliable sendrawtransaction/generate behavior? I'm skeptical of adding yet more network-specific behavior to chainparams, and can't think of any reasons transactions in mempool would not be included in freshly-CreateNewBlock'd things. Was the generate call to a different node than the sendrawtransaction call was to?

**Comment by rustyrussell** [comment]
@TheBlueMatt I can aim for standalone reproduce, but AFAICT it's threaded, so perfectly possible.

And I can't just generate another block until the tx is included, because we use locktimes and explicitly test set number of blocks.

**Comment by achow101** [comment]
@jtimon It's not a regression; that you have connections is explicitly checked for in `getblocktemplate`: https://github.com/bitcoin/bitcoin/blob/master/src/rpc/mining.cpp#L441

@rustyrussell 
> That's not very sane for regtest, is it?

Perhaps.

> And the unreliable sendrawtransaction/generate behavior on regtest seems to be most simply fixed by allowing this.

How so? AFAIK `generate` and `getblocktemplate` use the same code to produce the block template which `generate` uses to then actually make the block.

Unless you mean it would allow you to workaround your issue (by repeatedly calling `getblocktemplate` and just checking for it there); in which case this is just a workaround, not a fix of the actual problem (transactions just sent not getting into blocks).

**Comment by jnewbery** [comment]
> The getblocktemplate failure is weird, though. regtest is all about being a solo network, AFAICT, and if I were writing mining software I'd probably want to test this way.

This has tripped me up before, but I think it makes sense to keep the current behaviour. Any regtest-specific behaviour means that regtest isn't testing the same code paths as a node running mainnet.

We work around this in our functional tests by just spinning up a second node to peer with the node-under-test. See for example https://github.com/bitcoin/bitcoin/blob/master/test/functional/mining.py#L31 where the second node is brought up for this purpose.

**Comment by sdaftuar** [comment]
@rustyrussell Unfortunately even if we fix or workaround the connectivity requirement issue, I suspect that you'd likely still run into problems using getblocktemplate to test in this way, due to the caching of templates in gbt.  (This has bitten me before.)

I'd be supportive of an rpc command that just called CreateNewBlock and returned the results, without supporting any of the getblocktemplate options / behaviors, in order to explicitly test transaction selection.

**Comment by shwuhk** [comment]
I have the same issue. How can I test getblocktemplate without using testnet, as waiting for sync takes too much time.

**Comment by instagibbs** [comment]
(saw this linked to complaints in IRC)

Would people still be interested in an alternative block-getter RPC?

We've had one in Elements for a few years now and it'd be an easy port.

**Comment by MarcoFalke** [comment]
@instagibbs A (hidden) testing-specific one, or a new one for users as well?

**Comment by instagibbs** [comment]
From the context here it would be offered as testing only, so hidden?

**Comment by JeremyRubin** [comment]
just hit this... yes please! Or at least we can improve the docs / error message for regtest

**Comment by JeremyRubin** [comment]
Perhaps a better solution would be to have a helper for starting N regtest nodes while testing? I could see starting up a mini test network with some fake traffic as being very useful...

**Comment by MarcoFalke** [comment]
95d5d5e6257825bb385cee318d5681597f7f7646

**Comment by JeremyRubin** [comment]
Odd -- I believe I have this patch but still not working for me... in any case should I PR this as a contrib script?
```sh
#!/bin/bash
TMP=$(mktemp -d)
echo $TMP
CONF=$TMP/extra.conf
RPCPASSWORD=$(echo $RANDOM |shasum -a 256 | cut -d ' ' -f1)
RPCUSER=$(echo $RPCPASSWORD |shasum -a 256 | cut -d ' ' -f1)
echo "regtest=1" >> $CONF
echo "[regtest]" >> $CONF
echo "server=1" >> $CONF
echo "txindex=1" >> $CONF
echo "daemon=1" >> $CONF
echo "debug=rpc" >> $CONF
echo "rpcuser=$RPCUSER" >> $CONF
echo "rpcpassword=$RPCPASSWORD" >> $CONF
echo $RPCUSER $RPCPASSWORD
create_node() {
    THIS=$TMP/$3/bitcoin.conf
    cp $CONF $THIS
    echo "port=$1">>$THIS
    echo "rpcport=$2">>$THIS
    ./src/bitcoind  -datadir=$TMP/$3 &
}
stop_node() {
    ./src/bitcoin-cli -conf=$TMP/$1/bitcoin.conf stop
}

peer() {
    ./src/bitcoin-cli -conf=$TMP/$1/bitcoin.conf addnode "127.0.0.1:$2" "add"
    ./src/bitcoin-cli -conf=$TMP/$1/bitcoin.conf addnode "127.0.0.1:$3" "add"
}

mkdir $TMP/A
mkdir $TMP/B
mkdir $TMP/C
create_node 8332 18332 A

create_node 8333 18333 B

create_node 8334 18334 C


cleanup() {
    stop_node A
    stop_node B
    stop_node C
}
trap 'cleanup' 2

echo "waiting"
sleep 3
echo "Node Started"


peer A 8333 8334
peer B 8332 8334
peer C 8332 8333

createwallet() {
    ./src/bitcoin-cli -conf=$TMP/$1/bitcoin.conf createwallet default
}

mine() {
    while true; do ./src/bitcoin-cli -conf=$TMP/$1/bitcoin.conf -generate 1; sleep 30; done
}
createwallet A
mine A &
tail -c+1 -f $TMP/A/regtest/debug.log
```

**Comment by MarcoFalke** [comment]
>  I believe I have this patch but still not working for me.

What are the steps to reproduce?

Works fine locally:

```
$ ./src/bitcoind -datadir=/tmp -regtest -noprinttoconsole &
$ ./src/bitcoin-cli -datadir=/tmp -regtest getblocktemplate '{"rules": ["segwit"]}' | wc -l
36
