### ISSUE TITLE
Bitcoin 0.15.0 repeatedly bans only connect peer

### ISSUE THREAD

**Issue by HamishMacEwan** [bitcoin/bitcoin#11371]
### Describe the issue

After installing Bitcoin Core 0.15.0 I inadvertently ran an earlier version which corrupted the block database.  Stopped 0.13.2 and ran 0.15.0, it crashed without indicating an error.  Deleted the three directories (blocks, chainstate, database) and ran 0.15.0, it crashed.  Ran 0.15.0 again and it began an initial block download from a LAN instance of Bitcoin-QT 0.15.0  Later progress stopped.  As the log indicates it seems to have had a problem with its single LAN peer:

2017-09-19 20:44:48 UpdateTip: new best=00000000000000002b63d17164cde033e40254991a151ed8846233583d9c8035 height=312807 version=0x00000002 log2_work=79.925576 tx=43365575 date='2014-07-28 04:54:42' progress=0.169187 cache=479.3MiB(3351479txo)
2017-09-19 20:44:48 Pre-allocating up to position 0xb00000 in rev00160.dat
2017-09-19 20:44:48 UpdateTip: new best=000000000000000024cef26cfacce582e67132e741891d69c9b50f1e8b532754 height=312808 version=0x00000002 log2_work=79.925677 tx=43366011 date='2014-07-28 05:10:43' progress=0.169189 cache=479.4MiB(3351684txo)
2017-09-19 20:44:48 Misbehaving: 192.168.1.71 peer=0 (0 -> 100) BAN THRESHOLD EXCEEDED
2017-09-19 20:44:48 ERROR: ProcessNewBlock: AcceptBlock FAILED
2017-09-19 20:44:58 receive version message: /Satoshi:0.15.0/: version 70015, blocks=486071, us=[::]:0, peer=1
2017-09-19 20:44:58 Misbehaving: 192.168.1.71 peer=1 (0 -> 100) BAN THRESHOLD EXCEEDED
2017-09-19 20:44:58 ERROR: ProcessNewBlock: AcceptBlock FAILED
2017-09-19 20:45:14 receive version message: /Satoshi:0.15.0/: version 70015, blocks=486071, us=[::]:0, peer=2

This behaviour continues until Bitcoin-QT is exited.

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:

1. Run Bitcoin-QT 0.15.0

### Expected behaviour

Should continue the initial block download.

### Actual behaviour

Performs no block download activity

### What version of bitcoin-core are you using?

Bitcoin Core version v0.15.0 (64-bit)
94d0626426810db85b342dbf801681752e474ff0aff726783cb5297b70999a45  bitcoin-0.15.0-win64-setup.exe

### Machine specs:
- OS: Windows 10 Home
- CPU: i7-4790K
- RAM: 32.0 GB
- Disk size: 931 GB
- Disk Type: HD (Drive E:)

### Any extra information that might be useful in the debugging process.

I use:

 connect=192.168.1.71

in bitcoin.conf to limit connection to the single LAN peer.

Removed that connect, and the IBD resumed without problems.

Stopped Bitcoin-QT, restored the single connect, and IBD resumed without issue.

**Comment by knoxcard** [comment]
I would say double check hard drive space and firewall settings.
I am running the Windows version without any issue so far.

**Comment by HamishMacEwan** [comment]
On 24 September 2017 at 22:13, Justin <notifications@github.com> wrote:

Thank you for your response Justin.

> I would say double check hard drive space and firewall settings.

There is currently (for after the single glitch, 0.15.0 is running
fine) 605GB free on the drive where the blockchain is stored, and a
smaller amount but sufficient free (74GB) on the system (SSD) drive.

Windows Firewall is active for both Private and Public networks, but
since no changes were made to it, only the set of peers the Windows
instance of 0.15.0 was instructed to connect to, I don't see it as an
obvious candidate.

> I am running the Windows version without any issue so far.

My instance has now been running for a week or more without issue.  I
suspect it is the topology and IBD that were the cause of the problem.


Hamish.
-- 
https://www.onename.io/hamishmacewan

**Comment by TheBlueMatt** [comment]
Hmm, not sure that that was the issue, but given the debug.log provided I cant make much progress on debugging this, sadly. Glad it worked out eventually, #11406 should make these things (slightly) more debuggable in the future.

**Comment by HamishMacEwan** [comment]
On 27 September 2017 at 09:29, Matt Corallo <notifications@github.com>
wrote:

> Hmm, not sure that that was the issue, but given the debug.log provided I
> cant make much progress on debugging this, sadly.
>
As far as I could see there wasn't much more in debug.log, just endless
repetitions.

> Glad it worked out eventually, #11406
> <https://github.com/bitcoin/bitcoin/pull/11406> should make these things
> (slightly) more debuggable in the future.
>
Cool.  It is a bit of a corner case, though I do see recommendations from
time to time to have a bare externally exposed node and an internal-only
node that connects to it, so it might be one to watch.


Hamish.
-- 
https://www.onename.io/hamishmacewan

**Comment by adamjonas** [comment]
Looks like this problem did not persist nor was it reproducible. Ready to be closed.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
