### ISSUE TITLE
Bitcoin 0.15.0.1 can't start from cron without permissions error, copied my blocks folder and chainstate folder

### ISSUE THREAD

**Issue by robertclarkson** [bitcoin/bitcoin#11373]
### Describe the issue
Bitcoin can't start from cron without permissions error. I've copied my blocks folder and chainstate folder from an older version of bitcoin v0.14.2.0-gfc61c83

#### If so, please list the steps to reproduce below:
1. Install Bitcoin Core Daemon version v0.15.0.1 On Ubuntu server 16.04
2. set up cron job under user using crontab -e
@reboot bitcoind -daemon 1> /tmp/bitcoincron.out 2> /tmp/bitcoincron.err
3. run bitcoind -daemon
4. stop bitcoin
5. copy blocks and chainstate folders from older bitcoin install v0.14.2.0-gfc61c83
6. reboot, then cat bitcoincron.err:
```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::create_directory: Permission denied: "/home/user/.bitcoin"       
bitcoin in AppInit()       

bitcoind: chainparamsbase.cpp:69: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.
Aborted
```

### What version of bitcoin-core are you using?
Bitcoin Core Daemon version bitcoin-0.15.0.1-x86_64-linux-gnu.tar downloaded from the website
and same issue on apt-get install from PPA with version 0.15.0
 
### Machine specs:
- OS: Ubuntu Server 16.04
- CPU: Intel(R) Pentium(R) CPU G3220 @ 3.00GHz
- RAM: 4GB
- Disk size: 512 SSD

### Any extra information that might be useful in the debugging process.
* As above. nothing in .bitcoin/debug.log
* Running bitcoind and bitcoind -daemon from the command line work fine
* in bitcoin.conf using
** server=1
** txindex=1

**Comment by achow101** [comment]
Make sure that the user the cronjob runs under has permission to access access your datadir.

**Comment by laanwj** [comment]
Closing, this is a permissions issue, as is implied by the error message `
boost::filesystem::create_directory: Permission denied: "/home/user/.bitcoin" `.

**Comment by vivekteega** [comment]
Was anyone able to solve this? I am facing the same issue when running bitcoin-cli commands from a python script being run by supervisord

**Comment by robertclarkson** [comment]
The cron job was not running as a user that had permission to access the data dir. Check that your cron isn't running as root or that your files arent root only accessible
