### ISSUE TITLE
Why is getinfo being removed?

### ISSUE THREAD

**Issue by thequillmagazine** [bitcoin/bitcoin#11382]
"WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",

Why? This command gives me a concise summary of the running node. getnetworkinfo is too detailed, getwalletinfo doesn't apply, and getblockchainifo is a redundant command. Why force the use of three commands (that already exist) when one command is doing good? I've never understood this principal.

**Comment by promag** [comment]
See #8780 for further details.

**Comment by jnewbery** [comment]
From PR #8780:

> Some of the more serious problems with it are:
> 
> - It combines information from different subsystems (wallet, networking, blockchain, ...), so its implementation is messy by definition and has to lock all over the place
> - It is ill-defined and without focus - what information should be added, what shouldn't
> - It behaves differently with and without wallet (and what should it do with multiple wallets)
> 
> It basically still exists as a convenience for people using bitcoin-cli manually

There is an open PR #10871 to implement getinfo in the bitcoin-cli client. If you find `bitcoin-cli getinfo` useful I recommend you review that PR to help it get merged.

**Comment by thequillmagazine** [comment]
@jnewbery I'm using the bitcoin-cli client, I'll take a look at the code. Thanks for the instant reply!

**Comment by kangasbros** [comment]
Why not leave it for legacy purposes, what's the harm? Much code probably uses this command. It can be put to deprecated list or something, but I don't really understand the argumentation of removing it entirely.

**Comment by sipa** [comment]
@kangasbros Guaranteeing that its output remains consistent will become increasingly difficult as subsystems (wallet and blockchain, in particular) become more independent.

**Comment by kangasbros** [comment]
Maybe leave the fields out that are difficult to keep consistent? I can't believe leaving it outright out is the best decision.

**Comment by sipa** [comment]
If we have to break backward compatibility anyway, what is the point in keeping it? Anything relying on it needs to change anyway.

Also see #10871 to still get the convenience for users who want a quick overview.

**Comment by fanquake** [comment]
Closing, this is happening and has been explained sufficiently.
