### ISSUE TITLE
Payment request labels don't correspond with address labels?

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#11396]
For some reason, editing the label of an address does not update the corresponding payment request. There is also no way to edit the label of a payment request.

**Comment by TheBlueMatt** [comment]
It would be somewhat confusing if editing a (seemingly, at the UI level) unrelated field (the address label) edits the payment requiest as well, no? I suppose we could settle for making the label editable, but why not just issue a new payment request?

**Comment by jarolrod** [comment]
As PR [#211](https://github.com/bitcoin-core/gui/pull/211) was merged, there should no longer be a scenario where a receive address label does not correspond to the payment request label. 

I would lean towards NACK on the ability to edit a Payment Request. There is no need to edit the label of a payment request as there is no need to reuse an address. 

Let's consider two scenarios: 
1) Made a mistake with the label, didn't realize until after the payment request was created
    - Just create a new payment request, no need to reuse the address.
2) You want to make a new Payment Request. You had previously made one that has the same `amount` and `message` you want. You just need to edit the `Label`
    - We do not want to encourage this behavior, do not re-use an address. Just create a new payment request.

**Comment by luke-jr** [comment]
Scenario 1 shouldn't require a new request/address.

**Comment by MarcoFalke** [comment]
This feature request can be moved to the gui repo, if still relevant?

**Comment by fanquake** [comment]
> This feature request can be moved to the gui repo, if still relevant?

I'm not sure, but the GUI repo seems like the more appropriate place for this issue in any case. Moved to https://github.com/bitcoin-core/gui/issues/530.
