### ISSUE TITLE
Usability feedback: Tooltips are not intuitively recognized

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#11436]
### Describe the issue
The tooltips are hiding too much, users do not see them intuitively.
E.g. the problem occured here:
https://github.com/bitcoin/bitcoin/pull/11428

### What version of bitcoin-core are you using?
0.15.0.1

**Comment by wodry** [comment]
Not sure if this is an important issue, closing

**Comment by jonasschnelli** [comment]
I guess we can't (or shouldn't) control the Tooltip behaviour. It's should either be controlled by the OS or within Qt.

**Comment by wodry** [comment]
I had the idea of a question mark symbol after a text, which is a link, when the user clicks on it, a windows opens with explanation. So the user can easily see, that there is a help text.
