### ISSUE TITLE
Issue in running bitcoin-cli cmd command

### ISSUE THREAD

**Issue by vinyyoo** [bitcoin/bitcoin#11444]
# Describe the issue
I installed  bitcoin-cli and try to run through command-prompt,
I got an error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port

### Screenshots.
![screenshoot](https://user-images.githubusercontent.com/32484213/31125329-91655c92-a865-11e7-8771-002561f52384.png)

**What version of bitcoin-core are you using?**
v0.14.2

### Machine specs:
- OS:Windows 100
- CPU: Intel(R) Core(TM)i3-6098P CPU @ 3.60GHz 3.60GHz
- RAM: 8GB
- Disk size:1TB
- Disk Type (HD/SDD):SSD

**Comment by MarcoFalke** [comment]
According to `bitcoin-cli -help` there is no "-discover" option. What are you trying to achieve?

**Comment by vinyyoo** [comment]
i m trying to get info about bitcoin-core node and it still trow same error.
![error](https://user-images.githubusercontent.com/32484213/31127829-998a7666-a86d-11e7-822b-fabe28f963c5.png)

**Comment by MarcoFalke** [comment]
Make sure the server is running. Try `bitcoind -help`.

**Comment by vinyyoo** [comment]
sorry to ask i m totally new on bitcoin,how to find server is running or not?
and can i solved this error

**Comment by MarcoFalke** [comment]
The server is running when you start the gui with the `-server` option specified or when you start the daemon.

**Comment by jnewbery** [comment]
@vinyyoo this is an issue tracker for the bitcoin core software. I suggest you try irc #bitcoin, bitcoin.org or bitcoin.stackexchange.com if you need technical help.

**Comment by Jeans5** [comment]
I have the same issue with running bitcoind on my raspberry with the command `bitcoin-cli getblockchaininfo`

> error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
