### ISSUE TITLE
"Warning: Unknown Change Address" when using P2SH-P2WPKH wallet address

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11451]
<img width="820" alt="schermafbeelding 2017-10-04 om 17 55 39" src="https://user-images.githubusercontent.com/10217/31186602-5cda06ec-a92f-11e7-9d8f-e36923215275.png">

Steps to reproduce:
1. create a new address using Bitcoin-QT Receive tab 
2. create corresponding SegWit address through bitcoin-cli
3. use this SegWit address as the custom change address

I haven't tested if this goes away with #11403.

Using v0.15.0.1

**Comment by flack** [comment]
shouldn't it have gone away with #11247 already? (if you're on master ofc)

**Comment by MarcoFalke** [comment]
This will be fixed in 0.15.1 (c.f. #11447)

**Comment by Sjors** [comment]
@flack updated my comment to mention this was v0.15.0.1

**Comment by Sjors** [comment]
@MarcoFalke should I close this, or should it remain open to check later in the release process?

**Comment by Sjors** [comment]
Just recompiled using master 167cef808 and tried again using the same wallet and custom change address. The warning no longer appears.
