### ISSUE TITLE
wallet.dat cannot be symlink anymore in 0.15 (regression)

### ISSUE THREAD

**Issue by phiresky** [bitcoin/bitcoin#11459]
### Describe the issue

My wallet.dat is on a different drive than my bitcoin config directory, and having wallet.dat be a symlink has always worked.

#### If so, please list the steps to reproduce below:
1. `mv ~/.bitcoin/wallet.dat ~/file && ln -sf ~/.bitcoin/wallet.dat ~/file`
2. `bitcoin-qt`

### Expected behaviour

It should work transparently, same as in 0.14 (I think).

### Actual behaviour

"Error loading wallet wallet.dat. -wallet filename must be a regular file."

### What version of bitcoin-core are you using?
0.15.0.1-gfb7b5293844

Presumably introduced in https://github.com/bitcoin/bitcoin/commit/a6da027d83 (@promag)

**Comment by sipa** [comment]
See the discussion in https://github.com/bitcoin/bitcoin/pull/10885

In summary, this was an unintentional and unsupported feature with several risks. We're not going to add active support for it, as it has high risk of funds loss when used incorrectly.

Instead, see #11348 to enable having wallets in a separate directory from the blockchain.

**Comment by fanquake** [comment]
Closing, there was also some discussion in this related issue #11343.
