### ISSUE TITLE
ScanForWalletTransactions return value is incorrectly documented

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#11450]
`ScanForWalletTransactions()` has the following comment about its return value:

```
 * Returns null if scan was successful. Otherwise, if a complete rescan was not
 * possible (due to pruning or corruption), returns pointer to the most recent
 * block that could not be scanned.
```

This is not strictly true. If `abortrescan` is called, then `ScanForWalletTransactions()` will return `nullptr`, even though the scan wasn't successful to the tip.

This in turn causes a minor bug in `importmulti`, where the call doesn't return the correct error and warning about potentially not finding transactions if `abortrescan` was called.

I think the correct fix is for `ScanForWalletTransactions()` to inform the caller that the rescan was aborted.

**Comment by ryanofsky** [comment]
I think this is handled by #11200

**Comment by promag** [comment]
Regardless of #11200 IMO `CWallet::ScanForWalletTransactions` and `CWallet::RescanFromTime` should be improved.

**Comment by ryanofsky** [comment]
@promag noticed your comments in IRC (https://botbot.me/freenode/bitcoin-core-dev/msg/91898082/):

> \<promag> jnewbery: ScanForWalletTransactions interface is a bit weird
> \<promag> I think it should return the last block scanned
> \<promag> and also *all* failed blocks
> \<promag> not sure why only the most recent is useful

It's useful to know the most recent block that failed for the importmulti rescan. If multiple keys are imported, imports of keys with birthdays before the most recent failed block time are marked failed, and imports of later keys are marked successful.

**Comment by promag** [comment]
Yes I came to that conclusion following the result of these functions. However from these scan functions point of view, they should return all failed blocks. `importmulti` should use what fits better.

**Comment by Empact** [comment]
@MarcoFalke I'm on it.

**Comment by MarcoFalke** [comment]
Please note that there is  #12275 by @ryanofsky, which might be related.
