### ISSUE TITLE
Payment to yourself shows no address in Qt client

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#11464]
## Issue
When transacting unspent inputs to a new address in own wallet, the qt registers it as 'payment to yourself' without showing the receiving address. That can only be seen in the details or via 'listunspent' command

## Can you reliably reproduce the issue?
Yes

## If so, please list the steps to reproduce below:
1. create raw transaction to own address with multiple inputs
2. send the raw transaction with a miner fee
3. overall balance stays the same minus miner fee, in the transactions tab shows 'payment to yourself' without the receiving address

## Expected behaviour
I'd expect the payment to show up as a received payment with (my own) recipient address and 'payment to self' tag.

## Actual behaviour
Qt client only shows miner fee as 'transacted' and shows what seems to be an empty transaction without a receiving address in the transactions tab.

## Screenshots.

![qtweird](https://user-images.githubusercontent.com/11705841/31320956-d335c23a-ac7d-11e7-99f8-c696437c7f99.png)

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Core 14.02

### Machine specs:
- OS: Ubuntu 14.04
- CPU: amd
- RAM: 8G
- Disk size: 360Gb
- Disk Type (HD/SDD):Sata

**Comment by jonasschnelli** [comment]
We do split up multi-outputs-to-yourself in multiple transaction-table-rows. I think we could fix this (== show the output address).

**Comment by jonasschnelli** [comment]
Oops. Ignore my comment above. We do combine a multi-output `fAllFromMe` && `fAllToMe` in a single transaction row, opening the question which of the output addresses should be shown there...
If we have Change + a single output, we could display the non-change-outputs address, if we have multiple, we could keep the `(n/a)`.

**Comment by coinsmith** [comment]
Ah right, issue has to do with the change address, If I understand correctly. Why not, in a payment to ones own wallet, show both receiving addresses (target address +  change) in the transactions tab. Those would be outputs in ones own wallet that are transacted on the blockchain. Perhaps there are issues with this I haven't foreseen. Anyway, thanks for looking further into this.
