### ISSUE TITLE
rpc: Update importprivkey named args documentation

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#11462]
The documentation for importprivkey refers to the first named argument with the wrong string:

https://github.com/bitcoin/bitcoin/blob/7f11ef26085549664a911fe00807a199bbd1f041/src/wallet/rpcdump.cpp#L83-L86

The correct string for the name is mentioned in `src/wallet/rpcwallet.cpp`. This should be easy to fix, thus tagging with "hacktoberfest".

The fix could also update the calls to importprivkey in `test/functional/importprunedfunds.py` to use named args.

**Comment by dusty-wil** [comment]
Hi, I can take a look at this! I'm new to python, but interested in learning

**Comment by MarcoFalke** [comment]
@dusty-wil Great to hear. Updating the python test code is optional, but a good way to prove the correctness of your patch. You could start by fixing the help text in the cpp file.

**Comment by dusty-wil** [comment]
Ok, sounds good! I'll be able to look in to this later this evening!

**Comment by dusty-wil** [comment]
@MarcoFalke ok, I think I've got it, created the PR.

**Comment by promag** [comment]
IMO a fix should not do unrelated changes.
