### ISSUE TITLE
There is 3 mistake

### ISSUE THREAD

**Issue by Abdula-2015** [bitcoin/bitcoin#11473]
1) Why is the site https://dot-bit.org not working?
He reports:

```
Forbidden
You do not have permission to access / on this server.
Apache / 2.2.22 (Debian) Server at dot-bit.org Port 443
```

2) Why this manual guide  wrong?
These commands produce errors:

I press: `namecoind name_list
`
`Error: There is no RPC client functionality in namecoind anymore. Use the namecoin-cli utility instead.`

Then I press: `namecoin-cli name_list`

`error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/home/alex/.namecoin/namecoin.conf)`

 
 Why this errors?

**Comment by fanquake** [comment]
This is not related to this repo.
