### ISSUE TITLE
Different size and same transaction

### ISSUE THREAD

**Issue by wtabata** [bitcoin/bitcoin#11481]
Guys! I need undernstand, why size of transaction is different : in testnet

-- bitcoin core 0.15
-- rpc command
-- createrawtransaction -> signrawtransaction -> sendrawtransaction

$ bitcoin-cli decoderawtransaction 'hex' ( size:248 )

https://live.blockcypher.com/btc-testnet/decodetx/ ( size:138 )

https://blockchain.info/pt/decode-tx  ( size:248 )

https://www.blocktrail.com/tBTC/tx/a7df5b5338d0c44c53f367171ba9815009cf2abd793ec999c44aa58eafbb860f  ( size:138 )

- TXID:
a7df5b5338d0c44c53f367171ba9815009cf2abd793ec999c44aa58eafbb860f  

- HEX:
020000000001013ffb4121befab2b62034f150d0710f409e4812bb6bcbfe8bb0a3a842538b320b0 0000000171600145d9ebf621d1fbf2269659d8c8f7d49489ba38ba0ffffffff02400d0300000000 0017a914b626e95b538459fd04b130fbe16a076530220bfc87911623000000000017a9140e5d505 7c501a825422667103f242bfd7829583087024830450221008d46a7bc12e39c0a9c12201b51752f 6d36c4328742c5215fdc935850f7c1fb060220208517a6e1cb12d55dd3768b52c3ce5706682c1cc 20a4e1a5dd1d476c610a07d012103a5353204480d3ff956ab142b3a735d515c1016ca4a0ff21a82 3468e46e10b26400000000

**Comment by laanwj** [comment]
As this is a question and not a software issue, you'd probably get a better response at https://bitcoin.stackexchange.com/
