### ISSUE TITLE
Assertion fail when opening coin control dialog

### ISSUE THREAD

**Issue by mzhou** [bitcoin/bitcoin#11501]
#### If so, please list the steps to reproduce below:
1. Enable coin control features in Settings
2. Click Inputs... on Send tab

### Expected behaviour
Coin inputs dialog apears

### Actual behaviour
Crash with message

`bitcoin-qt: qt/coincontroldialog.cpp:585: static void CoinControlDialog::updateLabels(WalletModel*, QDialog*): Assertion `nBytes != 0' failed.`

### What version of bitcoin-core are you using?

master. 6ab0e4cf49549640b903bf5fce0e6035b8116397 or a865b38bf33202b66ee2e72912fe164aa2a504c7

### Any extra information that might be useful in the debugging process.

Reverting to 892809309c1bc370677241a715e57a2744f94323 fixes the problem

**Comment by MarcoFalke** [comment]
Related: #11133

Ping @practicalswift

**Comment by MeshCollider** [comment]
Perhaps instead of the assert(), dFeeVary should just be set to 0 if nBytes is 0.

**Comment by practicalswift** [comment]
@mzhou Thanks a lot for reporting! Fix on the way!
