### ISSUE TITLE
estimatefee is returning way-off value

### ISSUE THREAD

**Issue by phuongnd08** [bitcoin/bitcoin#11502]
My node running 0.15.0.1.
I run `bitcoin-cli estimatefee 2` and it returns `0.00010216`, way off compare to the industry standard (which should be about `0.00219185`)

`estimatesmartfee` also return similar value that is way off as well.

*Edited*: Removed incorrect observation. https://tradeblock.com/bitcoin/ mempool and my mempool size is closely matched.

**Comment by jonasschnelli** [comment]
Are you sure the "industry standard" you mention does represent an ideal fee for a 2 block confirmation?

**Comment by MarcoFalke** [comment]
Are you aware that `estimatefee` is deprecated and unmaintained?

**Comment by phuongnd08** [comment]
I'm comparing that with https://bitcoinfees.21.co/ and https://estimatefee.com/n/2 to get the "industry standard"

**Comment by phuongnd08** [comment]
And `estimatefee` and `estimatesmartfee` both yield similar result (and `estimatesmartfee` not available if the node is just restarted recently).

**Comment by phuongnd08** [comment]
Also I'm pretty sure that with a fee of 0.00010216BTC/Kb or 9.9765 sat/byte my transaction will rarely make it in 2 blocks, as of for today and the last many months.

**Comment by phuongnd08** [comment]
Okay, 12 hours later, the value start to make sense:

Now `estimatefee` is returning `0.00100288`.  And `estimatesmartfee` is returning `0.00061684`.

**Comment by TheBlueMatt** [comment]
In conservative mode, that is expected - you were seeing numbers that made sense for the time your node was on (which were significantly lower than what others were seeing because conservative mode considers things that were true a long time ago and may adjust upwards because of it).

**Comment by phuongnd08** [comment]
Well I'm a bit confusing now but for the time being I'll using the fact that `estimatefee` and `estimatesmartfee` will only start to make sense after a certain period of time (like 12 hours).

**Comment by TheBlueMatt** [comment]
See the help output for "estimatesmartfee", especially the mode parameter for more info. Feel free to suggest corrections if you're still confused.

**Comment by phuongnd08** [comment]
I'm confused because it is returning way-off value. That's where I'm confused. Either returns error or return a value with general acceptable confidence.

**Comment by TheBlueMatt** [comment]
Your node can only report to you information from when it was online. In this case your node was online for significantly more time than the fee estimate horizon you requested, so returned what were actually accurate fee estimates based on the last few hours. Others who are reporting conservative estimates are reporting something higher because prevailing feerates for fast confirmation were higher a day or three before. It would be prohibitive to require nodes be online non-stop for two weeks before providing fee estimates of any horizon, so instead you may see results for the time you were online which are more analogous to economical estimates than the conservative results of your peers.

**Comment by phuongnd08** [comment]
Okay. So `estimatesmartfee` does that. How about `estimatefee`, does it affected by the running time or it should return analogous value despite the online time?

Also I would like to think CONSERVATIVE mode should always return equal or higher fee compare to ECONOMICAL, shouldn't it?

**Comment by TheBlueMatt** [comment]
estimatefee is, essentially, a deprecated, to-be-removed wrapper for estimatesmartfee. Indeed, CONSERVATIVE should always be >= ECONOMICAL.

**Comment by phuongnd08** [comment]
On a related topic, how do a client know if a node has been running long enough or not so it knows if it is getting reliable result or not? None of `getinfo`, `getblockchaininfo`, `getnetworkinfo`, `getwalletinfo` is giving such information.

**Comment by TheBlueMatt** [comment]
See #10400

**Comment by phuongnd08** [comment]
Thank you @TheBlueMatt. Much appreciated. I just restarted my node and I can totally see that estimatesmartfee is returning in par value with https://bitcoinfees.21.co
