### ISSUE TITLE
getrawtransaction delay too long on non-existent txid

### ISSUE THREAD

**Issue by doersf** [bitcoin/bitcoin#11506]
As of 0.15.0.0, and 0.15.0.1, the `getrawtransaction` call lags when requesting non-existent transaction IDs. 

Tested on Ubuntu 14.04 and 16.04.

Reproduce with:

```$ bitcoin-cli getrawtransaction `openssl rand -hex 32` 1```

**Comment by achow101** [comment]
Lags by how much? It's almost an instant response for me.

**Comment by doersf** [comment]
If it's as intended, that's fine. But large services doing lookups for user-entered inputs will suffer.

You can close this if it's not going to be fixed.

**Comment by achow101** [comment]
I am unable to reproduce your issue, so it does not even seem like there is an issue here. Please provide more information if you think there is a bug.

**Comment by doersf** [comment]
I missed that :)

Lag for a single non-existent transaction is between 0.321s and 0.350s. This is not fine.
Lag for a single valid transaction is between 0.004s and 0.005s. Tested with size: 225b. This is fine.

`txindex` is enabled.

**Comment by achow101** [comment]
I see. This is a side effect of the new UTXO database structure. The slowdown is on searching the UTXO set for the txid, not on txindex. I think it can be sped up, but that may take a bit of work to do. Because the UTXO database is now keyed on the outpoint (txid hash and output index), we have to search through all possible outpoints for a given txid which is slower than previously which was keyed on only the txid. I'll see if it can be sped up.

**Comment by sipa** [comment]
This seems expected when you don't have txindex one, but with it it seems easy to avoid.

**Comment by achow101** [comment]
> This seems expected when you don't have txindex one, but with it it seems easy to avoid.

Is it not possible to just search for the prefix of the key (i.e. the txid) instead of the entire key?

**Comment by achow101** [comment]
@doersf Does #11507 fix your problem?

**Comment by sipa** [comment]
@achow101 The UTXO set cache in memory is a hashtable - it does not support searching by prefix.

**Comment by doersf** [comment]
@achow101 this is better. The results are now:

single valid txid: 0.004s to 0.005s
single non-existent txid: 0.0008s to 0.0017s

**Comment by fanquake** [comment]
@doersf Is this fixed now that #11529 is merged? Can you close if that is the case.

**Comment by doersf** [comment]
Things look fine. Thanks!
