### ISSUE TITLE
How do I determine if the UTXO is the change address or the collection address

### ISSUE THREAD

**Issue by mi2zha** [bitcoin/bitcoin#11503]
How do I determine if the UTXO is the change address or the collection address？

thank u

**Comment by jonasschnelli** [comment]
This question belong to https://bitcoin.stackexchange.com or some other discussion forum (this issue tracker is for Bitcoin Core Development).
There is no protocol feature to identify the change output. You may want to analyse the values, but some wallets are clever enough to create more then a single change output.

**Comment by mi2zha** [comment]
thanku
