### ISSUE TITLE
nVersion is never initialized in ProcessMessage (net_processing.cpp)

### ISSUE THREAD

**Issue by cryptonoob42** [bitcoin/bitcoin#11505]
In net_processing.cpp, in the function ProcessMessage, there's a declaration of 

`int nVersion`

right here: https://github.com/bitcoin/bitcoin/blob/6ab0e4cf49549640b903bf5fce0e6035b8116397/src/net_processing.cpp#L1232

This variable is subsequently used for comparisons, but has never been initialized, neither did it get assigned to any concrete value.

Using uninitialized variables can cause undefined or at least unexpected behaviour and should be avoided.

**Comment by cryptonoob42** [comment]
Link to the line: https://github.com/bitcoin/bitcoin/blob/6ab0e4cf49549640b903bf5fce0e6035b8116397/src/net_processing.cpp#L1232

**Comment by achow101** [comment]
It is, in fact, initialized just a little down below at https://github.com/bitcoin/bitcoin/blob/6ab0e4cf49549640b903bf5fce0e6035b8116397/src/net_processing.cpp#L1239. What that line does is it unserializes `vRecv` and sets the values of `nVersion`, `nServiceInt`, `nTime, and `nAddrme` based on what is unserialized.

**Comment by cryptonoob42** [comment]
Ouch, I did read that line but completely misinterpreted it. I somehow got the direction of the operators wrong. Therefore, I was under the impression that the values were being written into vRecv (which would, on second thought, be completely pointless). Sorry for wasting everyone's time... :see_no_evil:
