### ISSUE TITLE
Lost my Wallet.dat

### ISSUE THREAD

**Issue by pratik91s** [bitcoin/bitcoin#11519]
Hello,

I have received the bitcoin way back in 2013 in Bitcoin Core.
At that time I don't know about the importance of wallet.dat - I have formatted my hard disk and install Bitcoin Core again in 2017 but there it didn't show my Bitcoin in my balance. I have my Bitcoin Key.

How can I get my bitcoin back? Please help me!

It is very important for me to have my Bitcoin back.

Thanks

**Comment by MeshCollider** [comment]
This GitHub issue tracker is for technical issues with Bitcoin Core, not for support. Please visit bitcoin.stackexchange.com for support questions :)

**Comment by vinaybhushanj** [comment]
K friend..down load the app on to your mobile. And first write down all.
Possible remembered user names tel nos and pass words and try with one by
one with all possibilities daily.and be in support@bitcoin .com.further I
will be giving you the clue.thnk you

**Comment by laanwj** [comment]
Without wallet.dat there is no way to recover your bitcoins, unless you have the *private* keys.

It is possible to recover private keys from a formatted drive in some cases, especially as a "format" doesn't usually overwrite the entire disk. However if it is a long time ago there's a huge change they've been overwritten in the meantime. In any case if you're going to try that, stop using your computer right now to minimize the chance of further damage.
