### ISSUE TITLE
Install libdb4.8 to ubuntu 17.10

### ISSUE THREAD

**Issue by iamdaiyuan** [bitcoin/bitcoin#11540]
# sudo apt-get install software-properties-common
# sudo add-apt-repository ppa:bitcoin/bitcoin
# sudo apt-get update

Ign:5 http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu artful InRelease
Err:6 http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu artful Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

# sudo apt-get install libdb4.8-dev libdb4.8++-dev

**Comment by halvors** [comment]
Also experiencing same issue.

**Comment by laanwj** [comment]
This seems like a PPA issue @TheBlueMatt

**Comment by TheBlueMatt** [comment]
Should be resolved.

**Comment by TheBlueMatt** [comment]
Should be resolved, would love to get confirmation, however.

**Comment by nperalez** [comment]
@TheBlueMatt Confirmed issue is now resolved. Did not work for me earlier today but now does. Thanks!

**Comment by iamdaiyuan** [comment]
@TheBlueMatt   @lannwj @nperalez Thanks!

**Comment by iamdaiyuan** [comment]
@TheBlueMatt Confirmed issue is now resolved.

**Comment by lei123zhang** [comment]
666
