### ISSUE TITLE
Ability to use signrawtransaction offline

### ISSUE THREAD

**Issue by bitcoin-throwaway** [bitcoin/bitcoin#11546]
### Describe the issue

Trying to sign a transaction offline using `signrawtransaction` will trigger an error : "Input not found or already spent" (very likely https://github.com/bitcoin/bitcoin/blob/master/src/rpc/rawtransaction.cpp#L860).

The point is to have an offline computer used as cold storage wallet and be able to sign some imported raw transactions created on another online computer (using watch-only addresses).

#### If so, please list the steps to reproduce below:
1. Create an offline wallet (on an offline computer)
2. Export offline wallet public keys (addresses)
3. Import offline wallet public keys on an online wallet (other computer) (=> Watch-Only addresses)
4. Fund an address
5. use `createarawtransaction` from online wallet
6. try to sign created transaction on offline computer having offline wallet : error.

### Expected behaviour
Sign the transaction, don't try to check if transaction is funded when offline.

### Actual behaviour
Won't sign the transaction because don't have access to blockchain offline.

### What version of bitcoin-core are you using?
0.15.0.1

**Comment by TheBlueMatt** [comment]
Bitcoin needs the inputs to sign properly. You can provide the input scriptPubKeys to signrawtransaction with the "prevtxs" argument.

**Comment by sipa** [comment]
As Matt says, this functionality exists, but you do need to know the outputs being spent. You can find these using the `listunspent` or `gettxout` RPCs on the online machine.

**Comment by bitcoin-throwaway** [comment]
yes it worked, thank you !

**Comment by coolbobo** [comment]
@bitcoin-throwaway 
can you show me your code which using "prevtxs" argument.
