### ISSUE TITLE
 Can bitcoin server at the same time serve many wallets using jsonRPCClient.php ?

### ISSUE THREAD

**Issue by BitWaspBitWasp** [bitcoin/bitcoin#11544]
Can bitcoin server at the same time serve many wallets using jsonRPCClient.php ?

**Comment by TheBlueMatt** [comment]
Please see the multiwallet feature at https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md#multi-wallet-support
Note that it is *not* intended to be used across security domains, and wallets on the same bitcoind are accessible to all users who have access to the bitcoind.
