### ISSUE TITLE
Change homepage from "new kind of money" to "intangible commodity"

### ISSUE THREAD

**Issue by theochino** [bitcoin/bitcoin#11567]
The guy that has come up with this definition is in jail so he cannot send this himself.

To make money, you need a commodity (metal, silver, gold, ....) and someone to transform that commodity. Bitcoin is the root and it's virtual, so it's an "intangible commodity."

![image](https://user-images.githubusercontent.com/5959961/32062249-f6c935ca-ba41-11e7-8d7d-d1ba195a3dc1.png)

![image](https://user-images.githubusercontent.com/5959961/32062261-fd1c98fe-ba41-11e7-986d-347026d2f9bf.png)

This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by MeshCollider** [comment]
Did you mean this for https://github.com/bitcoin-dot-org/bitcoin.org? This repository is for the Bitcoin Core source code, not a website

**Comment by fanquake** [comment]
Indeed, this should be opened at https://github.com/bitcoin-dot-org/bitcoin.org.

**Comment by theochino** [comment]
Oups. Thanks.
