### ISSUE TITLE
CDBEnv::EnvShutdown: Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery

### ISSUE THREAD

**Issue by qubit1729** [bitcoin/bitcoin#11575]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
My original wallet is from 2012. I have not done any updates for some time.
My problem appears on two different computers. Sync is working but at the end there comes an error
flashing-db (see screenshot). I tried -rescan and -upgradewallet. 
I resynced from scratch on my original computer. needed more than one week...
At the end it showed a balance of zero. after rescan and upgrade wallet I got my balance but it always crashes at the end answering the error (see screenshot).
The wallet.dat is updated so there is no write problem.

#### If so, please list the steps to reproduce below:
1. Tried several versions - always the same
2. Tried two computers - same error
3.

### Expected behaviour
Tell us what should happen
No error at end of sync

### Actual behaviour
Tell us what happens instead
flashing-db error and exit of program at end of sync

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
Distributed binary v0.15.0.1

### Machine specs:
-> see CPU-Z file
[JIDONG.txt](https://github.com/bitcoin/bitcoin/files/1425366/JIDONG.txt)

- OS: Windows 10 64bit
- CPU: Intel Core 2 Duo -> other computer hexacore AMD
- RAM: Tried computer with 8GB other computer  32GB
- Disk size: 1TB
- Disk Type (HD/SDD): HD, other computer SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

If you need the whole Logfile please tell me a secure way for transfer.
The essential Part at the end looks like this:

2017-10-27 14:07:34 CDBEnv::EnvShutdown: Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery
2017-10-27 14:07:34 Shutdown: done
![err-flashing-db](https://user-images.githubusercontent.com/7703590/32146282-1d6aa62e-bcd5-11e7-9437-ecfb43c8891e.jpg)

**Comment by TheBlueMatt** [comment]
It sounds like your wallet is actually corrupted (this can happen if a file just sits on a drive for some years). I'd recommend a) make sure to work on a copy of the file instead of the original and b) ask on Stackexhange for advice on how to get the private keys out of a corrupted wallet.

**Comment by qubit1729** [comment]
Dear BlueMatt,
Thank you for your repsonse. Are you developer? Is there now way to find out the consistency of the wallet?
It could be checked without the blockchain. I waited more than 10 days to sync the whole blockchain.
Also the errormessage could be more specific. I tried it with several copies of my wallet.dat (different age).
If the wallet is currupt it has been corrupted by the software.
How can I do a database recovery as told by the error message?
Leopold

**Comment by qubit1729** [comment]
Dear BlueMatt,
I made a JSON dump with pywallet which worked fine. So the wallet.dat should not be corrupted.
Am I right?

**Comment by TheBlueMatt** [comment]
BDB does not provide more granular error details as far as I know, and it may be encourtering an error when it tries to write, or at any point, not just reading the wallet in the same way pywallet does. Most likely you should just dump the wallet and create a new one using the dump, but unless you believe this to be a Bitcoin Core issue, you should seek support at StackExchange, where folks will likely know more about pywallet/be more helpful than here.
