### ISSUE TITLE
rpcworkqueue, rpcservertimeout missing from bitcoind -h output

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#11574]
### Describe the issue

`-rpcworkqueue` and `-rpcservertimeout` (maybe some other too) are missing from 
https://github.com/bitcoin/bitcoin/blob/0.15/doc/man/bitcoind.1#L467

They're referred to in here. 
https://github.com/bitcoin/bitcoin/blob/0.15/src/init.cpp#L515

I think online help should show them by default.

### What version of bitcoin-core are you using?
0.15.0.1

```
C:\tempcoin\daemon>bitcoind.exe -h
...
RPC server options:

  -server
       Accept command line and JSON-RPC commands

  -rest
       Accept public REST requests (default: 0)

  -rpcbind=<addr>[:port]
       Bind to given address to listen for JSON-RPC connections. This option is
       ignored unless -rpcallowip is also passed. Port is optional and
       overrides -rpcport. Use [host]:port notation for IPv6. This
       option can be specified multiple times (default: 127.0.0.1 and
       ::1 i.e., localhost, or if -rpcallowip has been specified,
       0.0.0.0 and :: i.e., all addresses)

  -rpccookiefile=<loc>
       Location of the auth cookie (default: data dir)

  -rpcuser=<user>
       Username for JSON-RPC connections

  -rpcpassword=<pw>
       Password for JSON-RPC connections

  -rpcauth=<userpw>
       Username and hashed password for JSON-RPC connections. The field
       <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A
       canonical python script is included in share/rpcuser. The client
       then connects normally using the
       rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This
       option can be specified multiple times

  -rpcport=<port>
       Listen for JSON-RPC connections on <port> (default: 8332 or testnet:
       18332)

  -rpcallowip=<ip>
       Allow JSON-RPC connections from specified source. Valid for <ip> are a
       single IP (e.g. 1.2.3.4), a network/netmask (e.g.
       1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24). This
       option can be specified multiple times

  -rpcserialversion
       Sets the serialization of raw transaction or block hex returned in
       non-verbose mode, non-segwit(0) or segwit(1) (default: 1)

  -rpcthreads=<n>
       Set the number of threads to service RPC calls (default: 4)


C:\tempcoin\daemon>bitcoind.exe --version
Bitcoin Core Daemon version v0.15.0.1
Copyright (C) 2009-2017 The Bitcoin Core developers

```

**Comment by MarcoFalke** [comment]
You can use `C:\tempcoin\daemon>bitcoind.exe -h -help-debug` to show the debug options, which are hidden by default.

**Comment by unsystemizer** [comment]
Thanks. I saw it's qualified with `showDebug`, but that seems quite convoluted. If I need to know `-help-debug` to show these, I may as well grep through the source code tree.

Is there a plan to add more such debug-level parameters? If so, maybe some "advanced" options shouldn't be not shown by default, but it's only two in RPC section (maybe a few more in other sections).

**Comment by jonasschnelli** [comment]
If you need more then 16 workers and and an http timeout > 30 you are very likely debugging or running in a HA/HL environment. I think it's find that we hide **the help** of those expert/debug commands behind `-help-debug`. The term *debug* may misses the point a little bit (could be `-help-expert`) but changing it now does make little sense).

**Comment by dcousens** [comment]
HA/HL ?

**Comment by jonasschnelli** [comment]
>HA/HL ?
>High availability / high load?

Yes. Not sure if these are industry standard abbreviation. :)
