### ISSUE TITLE
Cannot stop daemon when changing config for RPC

### ISSUE THREAD

**Issue by cyberluke** [bitcoin/bitcoin#11586]
./bitcoin-cli stop
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/home/ubuntu/.bitcoin/bitcoin.conf)

This happens if you have bitcoind running, then you edit bitcoin.conf to add RPC port & credentials. Then you want to restart bitcoin daemon. But it is impossible to stop it as it tries to connect & close RPC that does not exist yet. So one have to kill the daemon.

**Comment by achow101** [comment]
You shouldn't be modifying any files in the bitcoin core datadir while Bitcoin core is running. It isn't designed to run like that.

**Comment by cyberluke** [comment]
Okay, I'm ignoring it is dumb decision not to be able to edit configuration text file and the daemon is re-reading it when exiting. Therefore if it is not a bug, but a feature, there should be some warning You cannot edit configuration while bitcoind is running or you will end in infinite loop :))))

**Comment by achow101** [comment]
The software can't warn you against doing something which you do externally.

Also, this isn't an infinite loop. Presumably you know what `rpcuser` and `rpcpassword` were before you changed them so you can use the `-rpcpassword`, `-rpcuser`, and `-rpcport` options in `bitcoin-cli` to set those options from the command line so it can still connect to `bitcoind`.

**Comment by MarcoFalke** [comment]
Indeed, you should revert `bitcoin.conf` to the previous version (the version that existed when you started the server) then `stop` and redo the changes to the conf.

Feel free to add a warning, but I don't think this warrants to leave an issue open.

**Comment by cyberluke** [comment]
Ok, still I think it is messy. All other softwares load properties at start or don't require transactionally safe config file. Imagine you change ALL the parameteres and don't remember the exact values from previous session. Then you have to kill the server, which will corrupt your database. This all because of a bad file handling design.

**Comment by achow101** [comment]
@cyberluke bitcoin-cli is a completely separate program from bitcoind. It can't possibly know whether you modified the bitcoin.conf while bitcoind was running. This is not "bad file handling design", there's just no other way for bitcoin-cli to know the rpcuser and password unless you explicitly give it those parameters.

**Comment by sipa** [comment]
SIGINT will cause bitcoind to shut down cleanly.
