### ISSUE TITLE
Trouble Installing Bitcoin Core on Windows 10 64-Bit

### ISSUE THREAD

**Issue by zzinda19** [bitcoin/bitcoin#11584]
### Describe the issue
Hi all, so I've recently started attempting to install bitcoin core on Windows, I've installed the Linux features using windows developer mode, but I keep hitting this one snag I can't get passed.

When I get to the part in the setup that says:
make HOST=x86_64-w64-mingw32
I get all types of error messages about the configure folder.

I've tried multiple times and keep getting these error messages:
![img3](https://user-images.githubusercontent.com/33239102/32203194-10450ca8-bdb8-11e7-90a6-3ced3bdcba78.JPG)

Any guidance would be greatly appreciated.
Thanks-

**Comment by sipsorcery** [comment]
My guess would be you've still got some problematic directories in your bash path. The Bitcoin build scripts don't seem to cope when there are directories with spaces in them. You can check your path with:

`echo $PATH`

You can further test by setting a minimal path for your current bash session and then retry the depends make script. To do so type the line below on your bash console:

`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by fanquake** [comment]
@zzinda19 have you resolved the issue? Please close this if it is fixed.

**Comment by zzinda19** [comment]
Same response
![capture](https://user-images.githubusercontent.com/33239102/32418368-6348a932-c236-11e7-9d8e-021ec517a5ce.JPG)

**Comment by acasaccia** [comment]
I have solved the same problem by cloning the repo in `/usr/src` rather than in a sub folder of the Windows home. Try to follow the steps listed here: https://github.com/bitcoin/bitcoin/issues/11549#issuecomment-339125280. Apparently they worked for some people. I was able to make the dependencies even though I got stuck compiling the core afterwards.

**Comment by fanquake** [comment]
Closing now that #11438 has been merged. If you're still having issues, can you comment in #11685.
