### ISSUE TITLE
Moving listwallets out of the wallet category on rpc help

### ISSUE THREAD

**Issue by ruimarinho** [bitcoin/bitcoin#11589]
### Expected behaviour
[listwallets](https://github.com/bitcoin/bitcoin/blob/2c66cea2d18682de1eef544fc3b74a1487a1741c/src/wallet/rpcwallet.cpp#L2621-L2636) is currently [the only command](https://github.com/bitcoin/bitcoin/blob/2c66cea2d18682de1eef544fc3b74a1487a1741c/src/wallet/rpcwallet.cpp#L3302) under the `wallet` category which is not wallet-specific. In other words, it operates at the global level.

### Actual behaviour
Adding support for this feature on the [bitcoin-core](https://github.com/ruimarinho/bitcoin-core) js client is more complicated as there is no way to automatically detect which commands require a wallet to be set. Moving this out of the `wallet` category would be a plus (e.g. over to `control`). Another option could be listing a command's support for multiwallet on the help output or providing an rpc with command definitions.

### What version of bitcoin-core are you using?
0.15.0.1

**Comment by jonasschnelli** [comment]
`listwallets` definitively belongs to the wallet(module) and therefore is in the right place.
If you want to do reliable auto-detection of commands requiring to specify a wallet to operate on, then you could parse the RPC source code and look for `GetWalletForJSONRPCRequest()`.
Or just add a static exception list.

**Comment by ruimarinho** [comment]
That's not possible in a remote server context. Adding a static exception a list is what is being done right now (based on `GetWalletForJSONRPCRequest()`), but it's not ideal.

**Comment by ESST0RNAD0** [comment]
I am so sorry. I actually am so dumb I thought this was a jump without looking thing. I’ll not do any more  damage. I’ll study up first. That’s what happens when you’re desperate to make some bitcoin which I’ve never done. Thank you

**Comment by jnewbery** [comment]
I don't have a strong preference about whether this should be under the control or wallet category.

**Comment by promag** [comment]
`signrawtransaction` belongs to the wallet module too but it's in the `rawtransaction` category. That said I don't think there should be a 1 to 1 relation between wallet category and wallet module.

IMO `listwallets` fits better in the control category.

**Comment by promag** [comment]
Even in #10579 the category is `rawtransaction` for both variants of signing.

**Comment by jnewbery** [comment]
> Even in #10579 the category is rawtransaction for both variants of signing.

No, in #10579, `signrawtransactionwithwallet` is wallet category:

```
+    { "wallet",             "signrawtransactionwithwallet",     &signrawtransactionwithwallet,  {"hexstring","prevtxs","sighashtype"} },
```

**Comment by promag** [comment]
Ah sorry my bad!

**Comment by ruimarinho** [comment]
Since the category suggestion does not appear to a consensual choice, what about listing support for multiwallet on a specific endpoint (could be a rest endpoint with command schemas) or even under `help` for now?

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
