### ISSUE TITLE
"bitcoin-cli help" does not show how to encrypt additional multi wallets

### ISSUE THREAD

**Issue by juestr** [bitcoin/bitcoin#11588]
### Describe the issue

I added a second new wallet2.dat. Now I wanted to encrypt it, but `bitcoin-cli help` does not show the command to do so, I need to use `bitcoin-cli -rpcwallet=wallet2.dat help`. This is very un-intuitive, and bad for a help function.

### Can you reliably reproduce the issue?

1. have an encrypted default wallet
2. add new multi wallet wallet2.dat via config file or cmd line options
3. naive `bitcoin-cli help` does not show command to encrypt second wallet.

### Expected behaviour

All wallet encryption, lock and unlock commands should be shown unconditionally in `bitcoin-cli help`.

The dynamic hiding of some lines is arguably worse than the benefit with multiple wallets.

### Actual behaviour

`bitcoin-cli help` shows only wallet encryption commands appropriate for the default wallet.

### What version of bitcoin-core are you using?

bitcoind 0.15.0.1~dfsg-1
deb http://ppa.launchpad.net/luke-jr/bitcoin-core-bip148-unofficial-builds/ubuntu zesty main

### Machine specs:
- OS: Debian 9.2

**Comment by jonasschnelli** [comment]
I can't reproduce your issue.
`bitcoin-cli help` does show `encryptwallet "passphrase"` if you haven't disabled wallet support (through compile option or via `-disablewallet`).

Calling `encryptwallet` does requires you to define which wallet you want to encrypt though `bitcoin-cli`'s `-rpcwallet=<filename>`.

Not sure if the PPA you are using has the same internals and APIs as bitcoin core 0.15.0.1.

**Comment by juestr** [comment]
Did you test in a multi wallet setup, with the first (default) wallet encrypted, and the second one not?

**Comment by juestr** [comment]
Oh yes wallet encryption works fine. 

The problem (far minor) is that the output of `bitcoin-cli help` is sensitive to whether the first wallet is encrypted. It will not show the encryptwallet command, except if you use `bitcoin-cli -rpcwallet=wallet2.dat help`.

I don't think this magic is beneficial any more, at least it caused me quite a bit of head scratching.

Note also that all wallet commands require an explicit -rpcwallet when multi wallets are used, but `help` quietly assumes the default one.

**Comment by jonasschnelli** [comment]
Oh. I see now.
Thanks for the report... a fix is proposed in #11590.

**Comment by juestr** [comment]
Thanks
