### ISSUE TITLE
[GUI] Transaction confirmation counter "clock" symbol does not visualize proportional

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#11581]
### Transaction confirmation counter "clock" symbol does not visualize proportional

- I would expect the clock/progress meter not to show zero, when there is 1 confirmation, but to show/visualize more than zero (I would expect to see a progress of 1/6 <=> 10/60 "mins")
- with "min" here, I do not mean real time minutes, but shares of 60 "min" on a clock (full circle).

### Expected behaviour

When less than six, the transaction confirmation counter "clock" symbol should show the proportional share of 60 min:
0 confirmations: Question sign
1 confirmation:   Clock "10 min" past
2 confirmations: Clock "20 min" past
4 confirmations: Clock "40 min" past
5 confirmations: Clock "50 min" past
6 confirmations: Check sign

### Actual behaviour what clock symbol shows:
0 confirmations: Question sign
1 confirmation:   Empty (white) clock, with a black line showing north (I would interpret that normally as zero, like on a analog speed meter)
2 confirmations: Clock "15 min" past (quarter of the clock black)
3 confirmations: Clock "30 min" past (that is correct)
4 confirmations: Clock "45 min" past, see screenshot
5 confirmations: Clock "60 min" past
6 confirmations: Check sign

### Screenshots
Here a screenshot of the clock symbol for a transaction that got 4 confirmations
![bildschirmfoto](https://user-images.githubusercontent.com/8447873/32188205-778c003a-bda7-11e7-97c4-b16055fcfc67.png)

### Some additional words
I admit, that this is really a nit, nevertheless maybe someone thinks, that this could be improved, too (and has capacity to do that). I know, contributors have really more significant work to do, and I appreciate Your work very much!

Edit: Tried to make my (really trivial?) point more clear, hopefully

**Comment by TheBlueMatt** [comment]
Confirmations are not linear - it's much, much, much more likely for you to see a one block reorg than a 2, and same for further numbers. If anything the logo nonlinearity could be *increased*, IMO.

**Comment by MeshCollider** [comment]
I've always thought of that icon as more of a circular progress meter, not a clock, it fills up one step at a time with each confirmation

**Comment by wodry** [comment]
Text updated. Hopefully, now more clear what I mean...?

**Comment by TheBlueMatt** [comment]
It's possible the concept of "Bitcoin confirmations" doesn't map well to UX elements like progress bars and circles. Indeed, one might expect it to move at some constant rate (though that's also not gonna happen due to natural variance), but then maybe we should use some other element that shows security of a transaction increasing exponentially in some human-understandable way?

**Comment by jonasschnelli** [comment]
I think @wodry has a point here. Also agree with @TheBlueMatt that the security you get with each confirmation is not linear. Though, I'm not sure if that must be transported on the UI (ideally it could, but more or less orthogonal to this issue).
The UI does only count/display the amount of confirmation not the amount of security (the non-linear part), the later is currently up to the users definition (which indeed is not ideal).

The problem with the UI is that the 10min, 20min, 40min, 50min icon would look worse on non HiDPI screens.

PRs welcome.

**Comment by MarcoFalke** [comment]
I think the symbol represents that a transaction ages as it "collects" confirmations. The "clock" symbol is based on the stopwatch icon and does not necessarily represent a time of exactly 60 minutes. Imo it should be interpreted that "more black" means "older" transaction and as @jonasschnelli  suggest it is not worth to mess with the look and feel on non-hidpi screens.

**Comment by MarshMallowMan** [comment]
![clock symbol suggestion](https://user-images.githubusercontent.com/34045599/33329443-6fccc14c-d411-11e7-8088-64274ee824bd.png)
what if we were to make confirmations 1-5 look like the above picture instead?

**Comment by luke-jr** [comment]
Proportionality (current) makes more sense than a clock. Blocks are not evenly spaced every 10 minutes, and there are scenarios where we really ought to ignore blocks toward confirmations (although we don't yet).

**Comment by MarshMallowMan** [comment]
![block icon suggestion](https://user-images.githubusercontent.com/34045599/33343048-e443f6cc-d438-11e7-9847-e31fcfc87b32.png)
If we should stay away from clock-type icons. What about using something like a signal strength icon with 6 bars. Could also separate those bars into blocks so it looks like your stacking blocks. Like the above picture

**Comment by MarcoFalke** [comment]
Please no "signal strength" to count the number of confirmations and if you go for the blocks icon, the number of blocks must match the number of confirmations. Everything else would be confusing.
