### ISSUE TITLE
"Potential stale tip detected" when deliberately not connected to peers

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#11608]
Running the master branch from yesterday, commit 2f959a58744d42859d74579220922e25ac3d2925, I see these in the logs when I'm running with `-connect=0` and also when I have clicked to disable all network activity in bitcoin-qt:

    2017-11-04 20:43:43 Potential stale tip detected, will try using extra outbound peer (last tip update: 1846 seconds ago)
    2017-11-04 20:54:13 Potential stale tip detected, will try using extra outbound peer (last tip update: 2476 seconds ago)

In both cases it's true that I likely have a stale tip, but that's the way I want it, and I don't want to try using extra outbound peers. In both cases I explicitly *don't* want any peers.

As it turns out, no peer seems to actually be added, but the appearance of the debug message itself is disconcerting, and possibly misleading.

**Comment by TheBlueMatt** [comment]
Indeed, if you had normal outbound connections disabled (through -connect) then no additional connections will be made. Simplest would probably be to just change the text of the log to indicate that we are just informing our net layer to try a new peer if enabled.

**Comment by sdaftuar** [comment]
Yeah this is confusing.  Suggestions for better log message here?  The net interactions are surprisingly complicated...  What we're doing is commandeering the feeler connection slot to be a regular outbound peer, which only has any effect if that part of the net logic hasn't been neutered (eg by a `-connect` or max connections setting or maybe other configs I haven't thought of).

**Comment by laanwj** [comment]
No suggestion for the message, though I'd propose moving messages like this about internal P2P behavior to the "net" category so they won't worry users who are not specifically debugging network issues.

**Comment by jarolrod** [comment]
This can be closed as it was fixed by: https://github.com/bitcoin/bitcoin/pull/14027

Confirmed that this is no longer the case with `bitcoind -connect=0` and `bitcoin-qt` with network turned off.
