### ISSUE TITLE
replay protection (segwit2x)

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#11609]
From what I have read, if some miners go ahead with SegWit2X then there's a risk of transactions made using bitcoin-qt will also be valid on the SegWit2X fork - is this true? If so, can something be done to ensure that TXs are valid only on the current/non-SegWit2X chain?

**Comment by MarcoFalke** [comment]
You might want to try splitting your coins. It could take several tries but
should work eventually.

Anyway, support requests should be directed to Bitcoin stack exchange
