### ISSUE TITLE
Compilation fails on Arch Linux

### ISSUE THREAD

**Issue by azavalla** [bitcoin/bitcoin#11601]
### Describe the issue
Compilation of v0.15.0.1 fails on Archlinux.
 
#### To reproduce the issue:
1. $ git checkout v0.15.0.1
2. $ ./autogen.sh
3. $ ./configure
4. $ make

### Behavior 
```
$ make
Making all in src
 [ ... ]
  CXX      libbitcoin_util_a-util.o
util.cpp: In function ‘void locking_callback(int, int, const char*, int)’:
util.cpp:110:16: error: ‘CRYPTO_LOCK’ was not declared in this scope
     if (mode & CRYPTO_LOCK) {
                ^~~~~~~~~~~
util.cpp:110:16: note: suggested alternative: ‘CRYPTO_RWLOCK’
     if (mode & CRYPTO_LOCK) {
                ^~~~~~~~~~~
                CRYPTO_RWLOCK
make[2]: *** [Makefile:6087: libbitcoin_util_a-util.o] Error 1
```

### What version of bitcoin-core are you using?
Version v0.15.0.1, commit fb7b52938

### Machine specs:
- OS:
        Archlinux  4.13.11-1-ARCH
        LSB Version:	1.4
        Release:	rolling

### Any extra information that might be useful in the debugging process.
openssl version:  openssl-1.1.0.f-2
boost-libs version:  boost-libs-1.65.1-1

**Comment by dcousens** [comment]
@azavalla check https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/bitcoin - that is what is available if you use the `community/bitcoin-daemon` pacakage.

**Comment by TheBlueMatt** [comment]
The issue, as @azavalla indicated in #11602, is that OpenSSL made a backwards-incompatible API change, seemingly without deprecation notice. It also resulted in other projects (like PostgreSQL) not building, so they may revert it, but we should update to handle the new API either way.

**Comment by dcousens** [comment]
@TheBlueMatt I just saw that,  and was about to redact my suggestion.

**Comment by MarcoFalke** [comment]
What are the steps to reproduce? I tried to install the version mentioned in OP and it appears to work:

```
$ sudo pacman -U https://archive.archlinux.org/packages/o/openssl/openssl-1.1.0.f-2-x86_64.pkg.tar.xz
...
Packages (1) openssl-1.1.0.f-2
...
$ make
...
  CXX      libbitcoin_util_a-util.o
  AR       libbitcoin_util.a
  CXXLD    bitcoind

**Comment by Empact** [comment]
They added back the constants here: https://github.com/openssl/openssl/pull/1266 / https://github.com/openssl/openssl/commit/dd850bcb395753a130a5d69697092d69555b6e2c

So looks like any 1.1.0 release build should work.
