### ISSUE TITLE
rpc listunspent should expose "is_mine" and "replaceable"

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#11613]
Currently `listunspent` only exposes a `safe` which is coded roughly as `confirmations > 0 || (is_mine && !replaceable)` however a consumer very well might want to distinguish between when it's "mine" and when it's not (as I presently need to).

This ideally would be extended to listunspent, gettransaction and listtransactions. 

(The `listtransactions` already exposes a "trusted" which is basically "is_mine" but also uses the spendZeroConf  configuration, which is imho rather confusing. So my suggestion would be that all apis expose a consistent set of "is_mine", "replaceable" and "confirmations" (which is already always exposed) and RPC consumers can use these primitives to make decisions.

**Comment by gmaxwell** [comment]
Seems reasonable to me.  Though for clarity,  I assume you would want a "Are all inputs mine"  (can a third party double spend me) rather than a "Is any input mine?" (which is IIRC what is_mine actually does).   Right?   Assuming you're not coinjoining they're the same, but they aren't generally the same.

**Comment by RHavar** [comment]
>  Though for clarity, I assume you would want a "Are all inputs mine" (can a third party double spend me) rather than a "Is any input mine?" 

Well for my case it doesn't matter (as as long as one of them is mine, I know it won't be double-spent). But I'm not sure what is most useful in the general case.

> I'm confused. Isn't everything reported by listunspent by definition is_mine?

Hmm not really. listunspent lists all your shit, but you want to know about the source of it.  Consider there two common ways for you to get money: someone sends it to you (not is_mine) or you sent to yourself (i.e. change) and it (is_mine). It makes sense to distinguish these two cases for a variety of things.

**Comment by GabrielDav** [comment]
@RHavar I'm looking into this. I think there is minor confusion with regards of wording (and please correct me if I'm wrong). ``listunspent`` indeed has ``IsMine`` function being used. And this function is being discussed by others here. However, ``IsMine`` means that 'coins are mine to spend' (is any input mine) and not 'coins source belongs to one of my accounts'. If I understand this issue correctly what you actually want to expose is 'from_me'. Correct?

**Comment by RHavar** [comment]
@GabrielDav 

Sorry, I don't understand what you mean. What I want is inputs that are mine to spend (which is what `listunspent` returns) but for each of those inputs I want to know if I was the one who created them or not. 

(i.e. if I was the one who created it, I know that it can't be double-spent or replaced without me myself doing it. Which allows me to treat it differently to other coins)

**Comment by sipa** [comment]
@RHavar I believe what @GabrielDav is trying to say is that internally what you're describing is the IsFromMe function (did I create this output?) rather than the IsMine function (is the output considered mine to spend).

**Comment by RHavar** [comment]
Ah, sorry, I see. So yeah, I guess it should be `IsFromMe`

**Comment by GabrielDav** [comment]
PR #12862 does not extend functionality to ```listtransactions``` since this operation already has field ```category``` indicating whether transaction is incoming (to_me) or outgoing (from_me). Thus making from_me redundant on this function.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
