### ISSUE TITLE
Is there a flag allowing to synchronise the blockchain without using TOR? (to increase the speed)

### ISSUE THREAD

**Issue by stefek99** [bitcoin/bitcoin#11628]
I've asked question on StackOverflow: https://bitcoin.stackexchange.com/questions/60916/how-to-ensure-bitcoin-core-clients-uses-available-bandwidth

I've also read the book - Mastering Bitcoin - and I better understand why the synchronisation process is so painful.

See the source: https://github.com/bitcoinbook/bitcoinbook/blob/8d01749bcf45f69f36cf23606bbbf3f0bd540db3/ch08.asciidoc

> As of Bitcoin Core version 0.12, a node will offer a hidden Tor service automatically if it is able to connect to a local Tor service.

---

Is there a way to synchronise the blockchain in *NON* TOR mode?

All too often TOR is slow, throttled by network providers and / or exit nodes

I believe it's worth adding a flag ```--plaininternet``` so that the synchronisation process is faster.

If such flag already exists please let me know;

**Comment by laanwj** [comment]
It will, by default, connect to the ipv4/ipv6 internet directly, even if Tor is available. To make all connections go through tor you need to configure a proxy.

If you are running Tor and somehow don't want bitcoin core to use it (say, to offer a hidden service), pass `-listenonion=0`.

**Comment by stefek99** [comment]
# Option A

> a node will offer a hidden Tor service automatically

# Option B

> connect to the ipv4/ipv6 internet directly, even if Tor is available

# Who is right?

In my understanding **option A** and **option B** are mutually exclusive.
