### ISSUE TITLE
Cleanup `logging` RPC help text

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#11631]
@jnewbery commented in #11626:

"Could also be done as part of this PR, but not strictly necessary: the help text could be cleaned up. For example "libevent logging is configured on startup and cannot be modified by this RPC during runtime." is incorrect after 7fd50c3 (libevent logging can be updated for most versions of libevent). A few more newlines in the help text wouldn't hurt either."

**Comment by AkioNak** [comment]
I think #11191 is almost same purpose as this issue.
Can someone review it?

**Comment by MarcoFalke** [comment]
Fixed in https://github.com/bitcoin/bitcoin/commit/ef14f2e3ff81c79666fdd5aa3790d1d30f4f81e4#diff-ad6efdc354b57bd1fa29fc3abb6e2872L550 (#11191)
