### ISSUE TITLE
How to create src/test/data/script_tests.json JSON file?

### ISSUE THREAD

**Issue by wjcloud** [bitcoin/bitcoin#11636]
Hi!
I'd like to know how to create src/test/data/script_tests.json JSON file?
Thanks.

**Comment by sipsorcery** [comment]
The JSON file already exists, there's nothing you need to do to create it. 

Do you mean how to create the header file from the JSON file? The src/Makefile.test.include has the commands.

>%.json.h: %.json
@$(MKDIR_P) $(@D)
@{ \
 echo "namespace json_tests{" && \
 echo "static unsigned const char $(*F)[] = {" && \
 $(HEXDUMP) -v -e '8/1 "0x%02x, "' -e '"\n"' $< | $(SED) -e 's/0x  ,//g' && \
 echo "};};"; \
} > "$@.new" && mv -f "$@.new" "$@"
@echo "Generated $@"

Or to make it suitable for a standalone command line (you'll need to add the echos to the top and bottom if desired):

`hexdump script_tests.json -v -e '8/1 "0x%02x, "' -e '"\n"' | sed  -e 's/0x  ,//g'`

**Comment by wjcloud** [comment]
Nope. I am making my own bitcoin and I'd like to switch the existing file. 
I've founded  this code and is there an way to activate this?

bitcoin/src/test/script_tests.cpp:

// Uncomment if you want to output updated JSON tests.
// #define UPDATE_JSON_TESTS

**Comment by sipsorcery** [comment]
In that case you just do exactly as it says. Uncomment the define and then rebuild the bitcoin source. Once the build is complete run test_bitcoin and you should end up with a script_test.json.gen.

Attached is the file I got from master.

[script_tests.json.zip](https://github.com/bitcoin/bitcoin/files/1453676/script_tests.json.zip)
