### ISSUE TITLE
BitcoinQT downcases bitcoin://... address on OSX

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11645]
When entering bitcoin://1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX in the Safari address bar, it opens BitcoinQT, but then says: 
 
<img width="432" alt="invalid" src="https://user-images.githubusercontent.com/10217/32615780-e8e88142-c570-11e7-962d-d3f7c4abe346.png">

Dev hint: try [RCDefault](http://www.rubicode.com/Software/Bundles.html#RCDefaultApp) in order to make OSX open these links using a custom build.

Tested with v0.15.1rc1 as well as master. Using QT 5.8.0.

This doesn't happen when I start QT from the command line:
`Bitcoin-Qt bitcoin://1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX`

It does happen if I use:
`open bitcoin://1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX`

So it's not a Safari issue.

Using log statements I found that this downcase happens somewhere before `bool parseBitcoinURI` in `guiutil.cpp`. This function actually strips `//` from the URI because:

```  
//    Cannot handle this later, because bitcoin:// will cause Qt to see the part after // as host,
```

See also #854.

This function is called from `PaymentServer::handleURIOrFile` in `paymentserver.cpp`. 

Before that `bool PaymentServer::eventFilter` uses:

```cpp
      QFileOpenEvent *fileEvent = static_cast<QFileOpenEvent*>(event);
      ...
          handleURIOrFile(fileEvent->url().toString());
```

Lower case already happened here.

If I use a single slash, there's no downcase, altough the UI then complains about the initial slash.

So perhaps something changed in QT and we need to do this earlier. Or it's OSX that's broken.

This does behave, suggesting that indeed something is treating the address as a host name:
`open bitcoin:1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX`

QT documentation for [QUrl](http://doc.qt.io/qt-5/qurl.html#UrlFormattingOption-enum) suggests this is expected behavior:

> Note that the case folding rules in Nameprep, which QUrl conforms to, require host names to always be converted to lower case, regardless of the Qt::FormattingOptions used.

That remark has been in their documentation more or less [forever](https://github.com/qt/qtbase/blame/5.8/src/corelib/io/qurl.cpp#L247-L249). 

I can't find a workaround, unless there's some way to get additional information out of [QFileOpenEvent](http://doc.qt.io/qt-5/qfileopenevent.html).

**Comment by Sjors** [comment]
On the bright side, bech32 addresses are lower case...

**Comment by laanwj** [comment]
I don't know what to be more surprised about, that this issue exists or that it has been the case forever and no one stumbled on this, or at least reported this before.

**Comment by Sjors** [comment]
Perhaps a subtle change in OSX or a recent update to QT made it behave as documented? Comments in the source code suggest it did work back in the day, otherwise why bother with all the OSX specific code?

**Comment by luke-jr** [comment]
Note that `bitcoin://address` is not a valid BIP21 URI. It should be `bitcoin:address`, which I suspect you'll find works okay since it's not being treated as a hostname...

**Comment by Sjors** [comment]
@luke-jr when I typed`bitcoin:address` into Safari it didn't switch to the BitcoinQT, it just started googling it. Only adding `//` triggered the app switching. This is probably not a real use case though.

When `bitcoin:address` is used as a link in a proper website, the `//` isn't needed.

`open bitcoin:address` indeed works.

The wallet could perhaps throw a more informative error if `//` was used, but I'm not sure if that's worth fixing. Given that BIP-21 doesn't even allow `//` I'll just close this.

**Comment by jonasschnelli** [comment]
I think we should keep that open... it looks like that we have to fix something here.

**Comment by luke-jr** [comment]
Shrug... invalid URIs don't work. No big deal either way IMO.

**Comment by sipa** [comment]
If somehow an invalid URI is passed (whether it looks like a URL or not) due to an overly broad OS level filter, we should at least give an error message, no?

**Comment by jonasschnelli** [comment]
Agree with @sipa. I could imagine that the way how we collect the URI from the event (In Qt) may be deprecated... I'm currently analysing.

**Comment by jonasschnelli** [comment]
RFC 3986 states:
```
   The host subcomponent of authority is identified by an IP literal
   encapsulated within square brackets, an IPv4 address in dotted-
   decimal form, or a registered name.  The host subcomponent is case-
   insensitive.
```
and
```
Some schemes define additional subcomponents that consist of case-
   insensitive data, giving an implicit license to normalizers to
   convert this data to a common case (e.g., all lowercase).  For
   example, URI schemes that define a subcomponent of path to contain an
   Internet hostname, such as the "mailto" URI scheme, cause that
   subcomponent to be case-insensitive and thus subject to case
   normalization (e.g., "mailto:Joe@Example.COM" is equivalent to
   "mailto:Joe@example.com", even though the generic syntax considers
   the path component to be case-sensitive).
```

and

```
When a URI uses components of the generic syntax, the component
   syntax equivalence rules always apply; namely, that the scheme and
   host are case-insensitive and therefore should be normalized to
   lowercase.  For example, the URI <HTTP://www.EXAMPLE.com/> is
   equivalent to <http://www.example.com/>.  The other generic syntax
   components are assumed to be case-sensitive unless specifically
   defined otherwise by the scheme (see Section 6.2.3).
```

Would that mean the concept flaw is in BIP21. AFAIK there is no guarantee by RFC3986 that the address (either it's a host or an additional subcomponent) needs to be handles case sensitive.


Not sure if there is a simple workaround in our code nor would it make sense to try to fix this upstream (because the code there seems to respect RFC3986)

**Comment by jonasschnelli** [comment]
I think BIP21 is correct because the additional subcomponent `bitcoin:<subcomp>` is case-sensitive. The problem just comes with `bitcoin://<host>` (with the double slashes). There, RFC3986 says it's case-insensitive and we need to expect a to-lowercase-normalised string.

The main problem in our source code is probably that we auto-correct `bitcoin://` to `bitcoin:` which does not work at our level.

**Comment by sipa** [comment]
Indeed, we should just treat incoming 'bitcoin://' as invalid-BIP21. No need to deal with lowercase or whatever; it's just not a valid URI.

**Comment by Sjors** [comment]
Only thing I'd like to check though is how iOs app switching works. I vaguely remember that it requires the `//` to work. If that's true then some websites might put in there. In that case it would be nice to support it if it's doable. Unfortunately I'm without iPhone for a few more days...

**Comment by Sjors** [comment]
I just tried this in the iOs Simulator. It's the same behavior as on a Mac; in Safari address bar you need to use `bitcoin://`, but a link can just use `bitcoin:` (e.g. try the BitPay demo page). I can double on a device later, but I suspect it will work.

**Comment by luke-jr** [comment]
What @jonasschnelli said.

> Some schemes define additional subcomponents that consist of case-
   insensitive data, giving an implicit license to normalizers to
   convert this data to a common case (e.g., all lowercase).

The `bitcoin:` scheme *does not* define this property for the address.

**Comment by laanwj** [comment]
> Indeed, we should just treat incoming 'bitcoin://' as invalid-BIP21. No need to deal with lowercase or whatever; it's just not a valid URI.

Yes. The bitcoin:// workaround seems a bad idea. I'm not sure why it was done at the time (maybe some popular site was doing that?), but after all this time I would hold people to follow BIP21 to the letter.

**Comment by Sjors** [comment]
Should we remove that workaround from the code in that case?

**Comment by jonasschnelli** [comment]
@Sjors: Yes. A PR would be welcome. Ideally an error message gets spit in case of a `bitcoin://` (maybe a specific one because we did support it partially in the past).

**Comment by jnewbery** [comment]
Can we close this now that #12723 is merged?
