### ISSUE TITLE
small date/time issue

### ISSUE THREAD

**Issue by Popkultur** [bitcoin/bitcoin#11656]
### Describe the issue

Probably date/time issues when changing time on active node?

### Can you reliably reproduce the issue?

n.a.

#### If so, please list the steps to reproduce below:

n.a.

### Expected behaviour

no network disruption

### Actual behaviour

n.a.

### What version of bitcoin-core are you using?

recent

### Machine specs:

n.a.

**Comment by sipa** [comment]
Please elaborate on what problem you saw, what you did, what you expected, what you saw.

**Comment by Popkultur** [comment]
I saw a date/time problem, I started the walletclient a few times, I expected nothing, I saw a hint that my time is wrong only once.

**Comment by sipa** [comment]
What does "I saw a date/time problem" mean? I have no clue what the issue is.

**Comment by Popkultur** [comment]
Leave it to the developers. They will know.

**Comment by MeshCollider** [comment]
@Popkultur sipa is one of the top developers here,   and no one will be able to understand what you're talking about
