### ISSUE TITLE
Contradictory Windows build instructions 

### ISSUE THREAD

**Issue by sipsorcery** [bitcoin/bitcoin#11659]
The Windows build instructions in doc/build-windows.md seem to be still resulting in headaches for people  #11549 and #11633.

I suspect the problem could be that there is a contradiction with one paragraph stating to avoid building on Ubuntu Xenial and the next paragraph state that building on Windows Subsystem for Linux - which is an Ubuntu Xenial environment - is recommended.

A bump that PR #11438 does remedy this contradiction.

**Comment by MarcoFalke** [comment]
Would be nice if someone with WSL could test the referenced pull request.

**Comment by rebroad** [comment]
@MarcoFalke already have. yes, it works.

**Comment by laanwj** [comment]
Closing because #11438 was merged.
