### ISSUE TITLE
Datadir file permissions issue gives confusing error on Windows

### ISSUE THREAD

**Issue by ekerstein** [bitcoin/bitcoin#11668]
I installed the latest version of Bitcoin on a new computer, everything started up normally and it started synchronizing. I closed the program (waited for it to finish) and reopened. When I did that it now says "Cannot obtain a lock on data directory C:\Program Files\Bitcoin. Bitcoin Core is probably already running. Access is denied".

I've googled the issue, tried deleting the LOCK file, tried uninstalling/reinstalling, and can't get it to work.

There is one thing I changed during the initial installation. When it asked me where I wanted the blockchain data, I changed it to the Program Files\Bitcoin directory instead of the default user App Data directory. I'm not sure if this is bad or messed something up. 

After I uninstalled and reinstalled, it no longer asks me where I want the blockchain data so I don't know how to change that.

**Comment by MeshCollider** [comment]
Try looking for bitcoin in your task manager or simply restarting windows, to confirm its not still running

**Comment by DarthJahus** [comment]
`%ProgramFiles%` directory needs admin permission if a program wants to write there. You can run Bitcoin Qt as admin or simply try to choose another folder for data.

If you don't want `%AppData%`, it's understandable, but believe me, %ProgramFiles% isn't a good choice and you'll probably forget to back it up before you reinstall Windows, hence lose your wallet and your coins. If you have enough room in your `%UserProfile%` folder, you can create a folder there for Bitcoin wallet (`%UserProfile%` is usually in `C:\Users\YourNameHere\`).

**Comment by ekerstein** [comment]
@MeshCollider I restarted and it still didn't work. I also don't see anything in task manager.

@DarthJahus I think you're right, my gut feeling is that it has something to do with the directory that I changed it to. How do I reinstall Bitcoin and change the blockchain directory? I've tried uninstalling/reinstalling but it no longer asks me.

**Comment by MeshCollider** [comment]
@ekerstein you can choose a different data directory if you start bitcoin with the `datadir=<datadir>` parameter

**Comment by ekerstein** [comment]
@MeshCollider Ok I got it to work again by creating a new shortcurt with the datadir parameter. 

Does this need to be reported as a bug?

- I tried using datadir in the bitcoin.conf file but it didn't work. It seems related to https://github.com/bitcoin/bitcoin/issues/3905 but I wasn't 100% sure if that's still a feature.
- Maybe using Program Files\Bitcoin should be discouraged
- Is there an easier way to change the data directory? It seemed to store some stuff in registry, hence the reason it wasn't asking me for the directory again even after uninstall. Maybe that could be made easier?

**Comment by MeshCollider** [comment]
@ekerstein you can start bitcoin once with the `-choosedatadir` parameter and it will ask you again where to put it, so you don't need to permanently have the `-datadir` option in the shortcut.

**Comment by ekerstein** [comment]
@MeshCollider That worked perfectly, thanks! Everything is running smoothly now. It seems to have been the data directory I chose before.

**Comment by DarthJahus** [comment]
> Does this need to be reported as a bug?

Definitely, yes.

> When a software is installed to the `Program Files` / `Program Files (x86)` folder, the setup program is always run with administrator rights. This means that the installation program is allowed to change permission settings for a folder.

Bitcoin installer has to ask for admin rights when launched, or at least when `%ProgramFiles%` is selected as destination folder for the installation. And if it is installed to Program Files, then it has to change folder permission to allow writing files there.

Setup tools may allow adding a script line to handle that. Found [this](http://www.samlogic.net/blog/2013/08/how-to-give-a-standard-user-write-permission-to-a-folder-in-program-files/) blog article that may be interesting.

**Comment by mikedennis** [comment]
> Maybe using Program Files\Bitcoin should be discouraged
I agree with this. Putting bitcoin data directory in program files is a bad idea. As mentioned Program Files isn't for program data it's for applications and requires elevated privileges to write to. Typically applications write their data to either %APPDATA% (which I believe is Bitcoin's default) or %PROGRAMDATA% depending on whether it's user specific or not.
