### ISSUE TITLE
urgent: consensus change required to mitigate death spiral

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#11664]
All attempts to post this to bitcoin-dev have failed, as any submissions about consensus changes are not approved with the argument that it is off-topic. This is now urgent, and needs addressing proactively in preference to reactively.

![image](https://user-images.githubusercontent.com/1530283/32695398-060ae63e-c78d-11e7-970e-fc3257eaae78.png)

I would prefer that Bitcoin survive rather than be replaced by Bitcoin Cash. I am in support of smaller blocks and therefore continued decentralization, and also believe that the lightening network is the better way forward. Bitcoin Core is the ideal team to lead the way, but I fear your lead will be lost if the "death spiral" occurs.

Why isn't this being address nor even allowed to be talked about please? (i.e my post to bitcoin-dev is still awaiting approval).

**Comment by MarcoFalke** [comment]
Closing.
The Bitcoin Core issue tracker is the wrong place to discuss or rush an unspecified "urgent consensus change". I am not a moderator of the bitcoin-dev mailing list, but given the above post, it might very well be inappropriate (non-technical, political or short-sighted).

**Comment by rebroad** [comment]
BCH is implemting this: https://reviews.bitcoinabc.org/D601

I would have thought something similar would work well for Bitcoin also - their development team is *on* this urgent issue.

Please either re-open, or start addressing this in bitcoin-dev!

**Comment by sipa** [comment]
@rebroad How many times do we need to repeat this? This is not the place to discuss consensus changes to Bitcoin.

I don't know why your posts aren't being accepted on bitcoin-dev.

**Comment by MarcoFalke** [comment]
Also, please note that it is Saturday night in Europe and US, so don't expect that the bitcoin-dev moderators are sitting in front of their screens only waiting for you to send them emails.
