### ISSUE TITLE
Old Bitcoin QT Core (V0.7) - Sent BTC - Lost?

### ISSUE THREAD

**Issue by ZoZoCoin345** [bitcoin/bitcoin#11672]
I performed a 'Send Bitcoin' transaction from my really old Bitcoin QT Core client (V0.7 2-beta) a few days ago as a Test. The client is YEARS out of date regarding the Blockchain.

I can see the Transaction Status on the client about an hour after sending it was given as -->

"Status: 0/unconfirmed, broadcast through 28 nodes".

I sent the nominal BTC transaction to an address beginning with "1B.." a legacy BTC address. There was a Transaction fee added natively by the Client (0.0005 BTC).

I’ve got a BTC Transaction ID for the Send BTC - but it is not showing up on blockchain.info, after over a week now.. ?

Anyone know what might be the problem ?

ps - If this is a hopeless scenario - is there anywhere I could reverse that transaction ?

Understand a Core Client Upgrade would be the way to go - but I was just checking if I could so a Send (as a Tester), to save me all the time to get my setup up to date, download 145gig etc..

Thanks!

**Comment by laanwj** [comment]
a) You won't see your transaction confirm if your client is not synced with the block chain

b) If no one knows about it, your transaction was probably sent with too little fee, so it was discarded by everyone you sent it to. It effectively doesn't exist except in your wallet. You can just re-spend the inputs. Newer versions of Bitcoin Core have a feature to abandon transactions.

**Comment by MarcoFalke** [comment]
Usually it is fine to sign transactions with clients that old. Though you should really update your client before connecting to the p2p network. Obviously also for reasons other than having better fee estimates.

Regardless, help and support request should be directed to bitcoin stackexchange.
