### ISSUE TITLE
Bitcoin is Vulnerable to Attacks

### ISSUE THREAD

**Issue by jjxtra** [bitcoin/bitcoin#11679]
Bitcoin code suffers from mining attack vulnerability.

1] Mining attack. If Bitcoin suddenly loses a lot of mining power, block creation slows well beyond the 10 minute average. This is especially bad if it happens at the beginning of a 2 week cycle where the difficulty was just changed.

Resolution: Change block difficulty to exponential moving average difficulty of the last n blocks, where n is probably a fairly small number. 2 weeks is too long, making fees enormous and the network vulnerable. This could be done as a soft fork by changing the algorithm at a future block number, giving everyone time to update their software and/or hardware.

2] Mining centralization. Related to point 1, consider soft fork change for proof of work change. ASIC mining hardware causes centralized mining. While not necessarily a bad thing, it still allows hash rate to quickly move away from bitcoin in large percentages.

Resolution: Support SHA256 and the new proof of work for a range of blocks would be necessary, and at the end of the range, it would fully switch to the new proof of work only. Not sure what a good range would be, but enough to give everyone ample time to update their clients. Related to this, build a miner into the bitcoin core GUI should the proof of work change.

Hope the suggestions are helpful, I am fairly new to cryptocurrency and may be missing some things in these observations.

**Comment by jjxtra** [comment]
Saw this as closed with no explanation. I'm curious if there are plans to address these issues in the coming months and years?

**Comment by sipa** [comment]
Bitcoin Core only implements non-contentious changes for such drastic alterations to the blockchain rules. Please take this at least to the bitcoin-dev mailing list if you want to want to get buy-in from the entire ecosystem for this.

**Comment by jjxtra** [comment]
Wasn't sure how to propose these ideas so I appreciate you letting me know the preferred channels.
