### ISSUE TITLE
Bitcoin-Qt: Label use non-intuitive to newbies: appears to be per-transaction rather than per-address

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#1168]
See 3 posts on the subject at https://bitcointalk.org/?topic=78301.msg873713#msg873713

**Comment by jonasschnelli** [comment]
Related to https://github.com/bitcoin/bitcoin/pull/5905 and https://github.com/bitcoin/bitcoin/issues/2086

**Comment by jarolrod** [comment]
These are the steps I believe should be taken to close this:
- [x] **Remove `Edit Label` in `Transaction View`**
  - PR [#211](https://github.com/bitcoin-core/gui/pull/211) removed the ability to `Edit Label` in the `Transaction View`. The removal of this feature will prevent confusion that you are editing a unique identifier for that transaction. 
- [ ] **Add ability to add a `comment` to a Transaction** (this would be local on the machine)

**Comment by luke-jr** [comment]
This issue shouldn't be fixed (gui#211 should be reverted). Per-transaction *is* per-address.
