### ISSUE TITLE
[RU] Помогите пожалуй2ста с демоном биткоина

### ISSUE THREAD

**Issue by l1feste4ler** [bitcoin/bitcoin#11695]
Здравствуйте, у меня есть проблема с разворачиванием ноды. 
Хотелось бы на своём сервере развернуть ноду биткоина, чтобы она слушала на определенном порту tcp.
Выполняю стандартные команды по установке 
sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install bitcoind
bitcoind -daemon
Также настраиваю конфиги 
server=1
rpcuser=usr
rpcpassword=pass
rpcport=8332

При запуске демона он пишет
Bitcoin server starting
и всё. Слушать ничего не начинает, при повторном вызовекоманды
bitcoind -daemon
снова пишет Bitcoin server starting. 

В чем может быть проблема?

**Comment by MarcoFalke** [comment]
The daemon will fork and run in the background. You can interfere with the server using bitcoin-cli

**Comment by kgcorps** [comment]
Enable debug.log and check what is written there. It most probably is working just fine. To specify protocol port in bitcoin.conf write the port as follows:
port=somePortNumberYouWantToUse
to enable debugging
debug=1 (for me it was enabled by default without anything else in bitcoin.conf file)

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
