### ISSUE TITLE
issue : Message store directory does not exist

### ISSUE THREAD

**Issue by webwakko** [bitcoin/bitcoin#11709]
### Describe the issue
I have a DeepOnion QT-wallet that cannot dump a privatkey and does not allow outgoing transfers.
When looking at the debug.log I get the error message that "message store directory does not exist"
Trying to run the checkwallet & repairwallet returns following:

13:26:38 > checkwallet
13:26:38 > {
"wallet check passed" : true
}
13:27:03 > repairwallet
13:27:03 > {
"wallet check passed" : true
}

running the dumpprivkey command gives this error : 
Private key for address xxx is not known (code -4)

**Comment by fanquake** [comment]
Sounds like you have the wrong repository.

**Comment by webwakko** [comment]
I was looking for the repository who created the original QT-wallet. I thought this was the one? 
The people from DeepOnion have no clue what the problem could be and maybe the original development team from this wallet are able to resolve it? 
In case this is not the right one, any idea where I should be heading ?

**Comment by fanquake** [comment]
Bitcoin Core doesn't have a checkwallet, or repairwallet RPC call. 
The string "message store directory does not exist" doesn't appear anywhere in it's source code.

We don't provide support to alt coins.

**Comment by webwakko** [comment]
Hi, It seems this problem code-4 private key unknown for address, is not only within the wallet i'm using for a certain coin, but also in another coin's qt-wallet. this makes me think the problem is nested deeper in the core of the qt-wallet code. I think there needs to be a focus on that part of the issue.. I need some info in how these wallets have been distributed/ adapted and since when.
