### ISSUE TITLE
How to backup the whole block chain downloaded?

### ISSUE THREAD

**Issue by prajwalrao2012** [bitcoin/bitcoin#11719]
As I was reinstalling windows (Resetting it), I copied the whole (partially)downloaded [blockchain] file, How do I attach it or is there any software that will again validate them over my backed up file to start the download from where it had last downloaded?

Please help me get a resource or make such software if possible.

Thank you

**Comment by laanwj** [comment]
You can simply copy the entire data directory from the old to the new machine. This contains all the blocks, databases and indexes, as well was the wallet.

You should use the stack exchange for questions such as this: https://bitcoin.stackexchange.com/
This is not a questions and answers forum.

**Comment by prajwalrao2012** [comment]
Okkk,
Sorry and thanks for guiding me

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
