### ISSUE TITLE
QT: allow custom fee increase / bump for RBF

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11717]
Currently the UI doesn't give you a choice when increasing the fee of an RBF transaction:
<img width="352" alt="custom please" src="https://user-images.githubusercontent.com/10217/32980386-df931d5e-cc65-11e7-888a-3812eb159bac.png">

The [bumpfee](https://github.com/bitcoin/bitcoin/blob/v0.15.1/src/wallet/rpcwallet.cpp#L2960) RPC command has an option `totalFee`, so the UI could add support for this.

I think the best approach would be to reuse parts of the send screen.

<img width="624" alt="schermafbeelding 2017-11-18 om 13 44 42" src="https://user-images.githubusercontent.com/10217/32980467-180e6b92-cc67-11e7-81f5-b41b60172159.png">

* "Pay only the required fee" would be replaced by "Bump fee by minimum permitted amount". 
* The custom per kilobyte field would show an error if the fee is too low.
* "Request RBF" would be replaced with "Disable RBF" 

 I don't know if the required information for that UI can be obtained with the current RPC methods though. It boils down to reusing the existing transaction screen, but hiding UI elements that aren't properly supported for RBF yet (e.g. changing the recipient).

**Comment by Sjors** [comment]
This can perhaps be done on top of #16966.

**Comment by Sjors** [comment]
@fanquake can this be moved to the GUI repo?

**Comment by fanquake** [comment]
> @fanquake can this be moved to the GUI repo?

Moved to https://github.com/bitcoin-core/gui/issues/647.
