### ISSUE TITLE
dumpwallet problem

### ISSUE THREAD

**Issue by khelle** [bitcoin/bitcoin#11715]
I noticed there is a problem with dumpwallet option. It does not seem to dump segwit addresses ("3"), and dumps only the standard one ("1"). Is it a bug or work as intended? How can I perform full dump of an wallet then?

**Comment by MeshCollider** [comment]
Currently dumpwallet only dumps private keys, not scripts. This is fixed in https://github.com/bitcoin/bitcoin/pull/11667, which adds scripts to the dump.

**Comment by khelle** [comment]
@MeshCollider ok I understand. If I `dumpwallet` and receive all my standard addresses, then `importwallet` on another bitcoin core and write a script that for each "1" address calls "addwitnessaddress" to generate a Segwit one - can I be certain that theses addresses will be the  same I used before? Can I workaround migrating seegwit addreses that way?

**Comment by MeshCollider** [comment]
@khelle yes I believe that is currently the case

**Comment by khelle** [comment]
@MeshCollider I just tested it and it works. Thank you for your guidance.
