### ISSUE TITLE
Wallet downgrade tool

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11716]
The issue of downgrading a wallet came up in a [gist](https://gist.github.com/sipa/125cfa1615946d0c3f3eec2ad7f250a2#gistcomment-2261785) related to #11403.

Use cases I've seen so far:
1. downgrade future SegWit format to v0.15.1 compatible format
2. ~opt-out of HD (e.g. by saving individual keys and deleting the seed)~ (see discussion on #11730)

A separate tool (~or RPC command~) would allow keeping the wallet code itself less complex.

**Comment by Sjors** [comment]
I'll try (2). Not that I would recommend anyone to opt out of HD, but it's probably easier for me to build. Someone else can build (1) on top of it.

**Comment by Sjors** [comment]
Feedback on #11730 suggests that, if done at all, this should be an external tool, not an RPC command.

**Comment by TheBlueMatt** [comment]
I can't say I'm a huge fan of HD-downgrade. I'd like to understand a use-case for it before we go and check in a tool to do it.

**Comment by Sjors** [comment]
@TheBlueMatt I removed that use case from the description. It was mainly there because it's easier to implement than downgrading a future SegWit (or otherwise strongly refactored) wallet format.

The idea came from this discussion between you and @sipa in the above linked [Gist](https://gist.github.com/sipa/125cfa1615946d0c3f3eec2ad7f250a2#gistcomment-2261804):

>>  It seems much easier to just automatically upgrade, and provide a recovery tool in case you need to force your wallet to work with an old version.

> Hmm, a recovery tool is another option, I suppose. I guess I would be perfectly fine with that option instead as well, but certainly one is required IMO.

From this I gather that if you implemented auto-upgrade, then there should be a way to downgrade. I don't know if that's true under all circumstances.

**Comment by MarcoFalke** [comment]
I tend to Concept NACK a wallet downgrade tool. The upgrade paths are already non-trivial to reason about, not to mention that most of them are untested (only implicitly tested on real developers' testnet/mainet wallets).

I don't think we can support a wallet downgrade tool (regardless of the interface) in rpc, command line downgrade or separate tool. Instead, I'd suggest that the prosed way of downgrading a wallet is by not upgrading. That means to create regular backups of the wallet and only upgrade after backing up the wallet.

In case we add auto-upgrade, there should be an option to disable auto-update (advertised in the release notes and command line option help).

**Comment by Sjors** [comment]
Maybe any auto-upgrade should check / ask the user to confirm that a backup was made?

**Comment by TheBlueMatt** [comment]
I'm rather strongly against auto-upgrade in any form, but a downgrade tool for something like SegWit wallet may make sense, but it obviously depends on how SegWit wallet ends up being implemented.

**Comment by MarcoFalke** [comment]
I still don't get the purpose of a wallet downgrade tool. Why would you create a wallet with feature XYZ and then remove that feature right after creation?

Reasonable options are:
* Create wallet with Bitcoin Core version n-1, which does not support feature XYZ. Then use wallet with current Core version
* Current core version can support a `-nouseXYZ`, similar to `-nousehd` to create a wallet without feature XYZ. (This option also works with auto upgrade: Just specify `-nouseXYZ` to prevent auto upgrade)

**Comment by luke-jr** [comment]
Note that we never intentionally auto-upgrade...

**Comment by TheBlueMatt** [comment]
@MarcoFalke see discussion on the gist at https://gist.github.com/sipa/125cfa1615946d0c3f3eec2ad7f250a2

**Comment by jnewbery** [comment]
I'm a concept NACK on a downgrade tool. It just seems too difficult to work through all the edge cases and be satisfied that there isn't some way to lose money.

OTOH, I'm very concept ACKish on a generalised wallet tool. If you're interested in that, take a look at @jonasschnelli's PR here: #8745.

**Comment by MarcoFalke** [comment]
I think this can be closed?
