### ISSUE TITLE
Bitcoin-qt hang after sendrawtransaction

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#11721]
I did a `sendrawtransaction` on the GUI debug console during pretty heavy lock contention (blocks were being verified) and it seemed the debug console hanged. I tried the same `sendrawtransaction` again, but no response. Waited quite a long time, but even after blocks were verified there was no response.

Shutting down, the application seems to hang forever.

Full output from `thread apply all bt` here: 
https://0bin.net/paste/c4FhLI3Yv-OKnCVl#hJBzbgTb1sr+EYnETV4pH1NkTySGfWtsHDQ-C7YQZUW
If you need any other information let me know, I'll keep the gdb session open for now.

Looks like a RPC thread is hanging on https://github.com/bitcoin/bitcoin/blob/master/src/rpc/rawtransaction.cpp#L977
This was introduced in cb06edf938302166030db19017c27889ea5b10b6 (#10286).
Running master as of d080a7d.

@TheBlueMatt any idea?

**Comment by TheBlueMatt** [comment]
Hmm, did you call sendrawtransaction on a transaction already in your mempool? If so #11738 should fix the issue.

**Comment by laanwj** [comment]
Yes, the transaction was already in the mempool. Thanks!
