### ISSUE TITLE
[QT] Inconsistent icons in overview tab

### ISSUE THREAD

**Issue by vmavromatis** [bitcoin/bitcoin#11727]
Can someone please have a look? The 'receive' icon is not the same as the 'receive' tab icon.

![](https://user-images.githubusercontent.com/8668731/32990290-43711cd8-cd27-11e7-8b5e-480cf2f4b822.png)

I am using the latest v0.15.1.0-g7b57bc998f3 (64-bit) version.

I don't mind which one you end up using as long as they are consistent please.

Thanks in advance.

**Comment by jonasschnelli** [comment]
I'm not sure if this is really an issue.
The "Receive-tab" icon must not be identical then the incoming-transaction icon...

@vmavromatis: can you elaborate what parts of the screenshots you have marked confuses you?

**Comment by vmavromatis** [comment]
I'm not a UI expert by any stretch, but it's weird that the "Send-tab" icon is pointing **right**, the "Receive-tab" points **down** and the "Receive-tx" points **bottom-right** and on top of that their styles are a bit different. It just feels very inconsistent and random. I am not able to tell which is which from a quick glance, I need to have a thorough look to know what's going on.

I hope what I said makes sense. I know this is low prio, but maybe worth looking at.

**Comment by MarcoFalke** [comment]
I think it is the easiest if you go ahead and propose a fix. This should be relatively easy. The files are located in https://github.com/bitcoin/bitcoin/tree/master/src/qt/res (subfolder icons and src).

No need to keep an issue open about this, imo.

**Comment by promag** [comment]
Agree. Maybe remove the transaction icon?..

**Comment by MarcoFalke** [comment]
@promag I think it helps that one can quickly differentiate between in and out-payments.
