### ISSUE TITLE
[Wallet Feature] Spend unconfirmed output

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#11723]
Currently the wallet has an expert option that allows us to spend unconfirmed change. This does not allow us to spend unconfirmed outputs coming from elsewhere. It is my strong belief that another option should be added that allows us to spend any unconfirmed output.
An example use case would be moving funds between multiple owns wallets; as it currently stands, you have to wait for confirmations at each stop.
Additionally, with the introduction of multi-wallet support this kind of behavior is going to become more likely and thus is another reason for the addition of such feature.

Thoughts?

**Comment by MarcoFalke** [comment]
This is possible with raw transactions for people that know what they do. For everyone else we can only offer safe wallet options. Spending unconfirmed coins from someone else can be dangerous in many ways.
