### ISSUE TITLE
'make check' fails on OSX 10.13.1

### ISSUE THREAD

**Issue by Ankarrr** [bitcoin/bitcoin#11731]
### Describe the issue

```
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
FAIL: test/test_bitcoin
PASS: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.15.99
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```
### What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?

Master branch at 7293d064133aeafd9f0ae0bdbb2ed74a44d91ecc

### What type of machine are you observing the error on (OS/CPU and disk type)?

OSX 10.13.1
Xcode 9.1

### Attach test-suite.log

[test-suite.log](https://github.com/bitcoin/bitcoin/files/1489808/test-suite.log)

**Comment by jonasschnelli** [comment]
Can you attach the `test-suite.log`?

**Comment by Ankarrr** [comment]
Sure. I update my comment.

**Comment by jonasschnelli** [comment]
```
unknown location:0: fatal error: in "dbwrapper_tests/existing_data_no_obfuscate": dbwrapper_error: Database corrupted
test/dbwrapper_tests.cpp:135: last checkpoint
```

On what filesystem do you run the tests? External USB thumb drive?
Did this issue came up after switching from 10.12 to 10.13 (or 10.13.0 to 10.13.1)?

**Comment by Ankarrr** [comment]
I make and run in my MAC hard drive. As I remember, it also failed when I ran in OSX 10.12.

**Comment by Varunram** [comment]
On OSX 10.13.0 here, my tests went fine on current master. Did you install all the requirements?

**Comment by jnewbery** [comment]
@Varunram - what's the current state here? #11767 makes it look like your issue was resolved. Are you happy to close this issue?

**Comment by Varunram** [comment]
@jnewbery I'd gladly close the issue, but I don't have the rights to do so :)

**Comment by jnewbery** [comment]
Oh sorry, this was opened by @Ankarrr . @Ankarrr , are you happy to close?

**Comment by MarcoFalke** [comment]
Can you reproduce the failure?
