### ISSUE TITLE
error in compile.

### ISSUE THREAD

**Issue by charliegama** [bitcoin/bitcoin#11758]
Error in compile.. code source forksource bitcoin 

********************************************************
Ubuntu 16.04.03 LTS  - kernel 4.4.0-101-generic
********************************************************
Error in compile 
**********************************************************

 make -f makefile.unix RELEASE=1
/bin/sh ../share/genbuild.sh obj/build.h
fatal: Not a git repository (or any of the parent directories): .git

******************************************************************

**Comment by promag** [comment]
Have you followed this guide https://github.com/sipa/bitcoin/blob/201709_segwitwallet2/doc/build-unix.md?

**Comment by laanwj** [comment]
There hasn't been a makefile.unix for years, try using a reasonably recent version at least.
