### ISSUE TITLE
Dumpwallet exports xpriv (in a comment) (==hdmaster) but ignored in importwallet

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#11764]
Dumpwallet does export hd master keys and I don't see a reason why importwallet should not import that hdmasterkey – while not using it for new keys but deriving old ones after the HD rescan did detect new receives. Or a simplified implementation where we just generate a bunch of keys from that imported master-key (10'000?) and rescan back from the masters birthday (while using a new seed for security reasons).

**Comment by nikwelcom** [comment]
Klass

**Comment by TheBlueMatt** [comment]
It'd be nice if we had general multi-hdmaster support. Ideally our hd master rotate function would then be able to use it (though risk is comparably smaller there).

**Comment by willcl-ark** [comment]
@achow101 is it likely that this will ever be added to the legacy wallet now that we have descriptor wallets? If not, perhaps it can be closed.
