### ISSUE TITLE
bitcoind assertion failed, macOS 10.13.0

### ISSUE THREAD

**Issue by Varunram** [bitcoin/bitcoin#11767]
OS version: macOS 10.13.0
Core built on commit a933cb14c75b9c79a02f8de8397a8eae405a264f
Steps to Reproduce:
1. Standard steps to build on OSX
2. `./bitcoind` does not work and spawns the following error:
```
Assertion failed: ((pindexFirstNeverProcessed != nullptr) == (pindex->nChainTx == 0)), function CheckBlockIndex, file validation.cpp, line 4203.
Abort trap: 6
```
Strangely enough, `bitcoin-cli` works, so I think this might be isolated to `bitcoind` and similar.

I Didn't observe this earlier, think it may have occurred recently (or I may have done something which causes this). Any help is greatly appreciated. Thanks!

**Comment by MarcoFalke** [comment]
Do you see this assertion hit on main net?

**Comment by Varunram** [comment]
Yep, same with testnet and regtest too.

**Comment by TheBlueMatt** [comment]
Well you obviously shouldn't be seeing an assertion failure either way, but CheckBlockIndex shouldn't be called in normal runtime - it's gated by the -checkblockindex option which defaults to false on mainnet.

**Comment by MarcoFalke** [comment]
Mind to provide some further details?

* The most recent date without this issue (commit or rough time).
* The bitcoin.conf or command line args or debug.log

**Comment by Varunram** [comment]
I think I got the solution. I had another instance of Core, figured out
that would interfere and changed the data dir and boom, it worked. So I
guess, this ain't a bug, but maybe a more helpful error message would've
been great. Thanks for responding!

**Comment by MarcoFalke** [comment]
I don't think we can provide helpful error messages when the datadir ends
up in a consensus incompatible state. (Assuming that this is what happened
here)

**Comment by TheBlueMatt** [comment]
What is "another instance of Core"? I'm not aware of any cases that could trigger this, except possibly if you ran some other Software that wrote garbage to your chain state (eg a BCH fullnode, btc1, etc)

**Comment by Varunram** [comment]
Nah, I'm not attracted to trash, so no problems there. Here's what I did:

1. I currently have two clones - one on
commit 6157e8ce3937af3f46d3e7dd922d19d6dc272145 running at ~/bitcoin and
another on ~/temp/bitcoin (used to test #11731 with master in this case)

2. I use the one at ~/bitcoin with the default home directory
(~/Library/Application\ Support/Bitcoin/) to run a regtest node. I did not
sync any block on mainnet.

3. I tried to start mainnet (and others consequently) at ~/temp/bitcoin and
it didn't work.

This led me to the conclusion that it might be the data directory which may
be causing problems.

**Comment by MarcoFalke** [comment]
I am still surprised that you see that on main and test net. Would you mind double checking and sharing the corresponding `debug.log` or `-printtoconsole`?

**Comment by Varunram** [comment]
I just checked `debug.log` and it seems that I synced till block 115000 (must've been running in the background, my bad). Still dunno about testnet, but I shall assume that something similar would've happened since cleaning the directories, recloning and building seems to work just fine. Thanks for the inputs and sorry to have taken up your time.
