### ISSUE TITLE
Passphrase not working since update to 0.15.1

### ISSUE THREAD

**Issue by loudthunder** [bitcoin/bitcoin#11768]
Can not send BTC or change passphrase since updating
Utilizing Bitcoin Core .0.15.1, but also reverted back to 0.15.0.1

**Comment by TheBlueMatt** [comment]
I don't believe any wallet encryption-related code changed between 0.15.0.1 and 0.15.1. You tried the password multiple times and reverting to 0.15.0.1 worked instead?

**Comment by loudthunder** [comment]
I set the passphrase on 0.15.01, updated to 0.15.1 and now its not working. Reverted back to 0.15.0.1, still no luck.

**Comment by TheBlueMatt** [comment]
That makes more sense. Obviously the most likely issue is having mistyped your passphrase when encrypting the wallet. You may wish to try a brute force tool to test variations on your passphrase.

**Comment by loudthunder** [comment]
That's what i have been afraid of. Know any brute force tools i can try?

**Comment by vmavromatis** [comment]
@loudthunder https://github.com/glv2/bruteforce-wallet
