### ISSUE TITLE
[qa] Net.py fails occasionally

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#11778]
In net.py we compare the exact number of bytes transmitted or received of two subsequently called rpcs. This fails occasionally. I hypothesise that this might be caused by cross-traffic that happens in between those rpcs, which are obviously not called atomically.

If that is the case, we might be able to repeat the calls up to ${n} times and hope that cross-traffic does not happen in all ${n} cases.

Relevant example log:
* https://travis-ci.org/bitcoin/bitcoin/jobs/305878397

**Comment by jnewbery** [comment]
Agree that your hypothesis is the most likely explanation here.

Your fix seems reasonable. Will open a PR.
