### ISSUE TITLE
Bitcoin-Qt (Settings) reports incorrect "Size of database cache"

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#11788]
```
$ ./bitcoin-0.15.1/bin/bitcoind --version
Bitcoin Core Daemon version v0.15.1
Copyright (C) 2009-2017 The Bitcoin Core developers
$ cat .bitcoin/bitcoin.conf | grep dbcache
dbcache=8000
```
debug.log reflects the correct amount:
```
2017-11-29 17:26:04 * Using 7990.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
```
However, the UI does not:

![image](https://user-images.githubusercontent.com/13134193/33389589-50a3fb9c-d56e-11e7-9be5-f4ae82855763.png)

Both Bitcoin-Qt and bitcoind log the correct amount, only Bitcoin-Qt UI reports 450 MB instead of 8 GB.
I tried to start it with `-dbcache=8000`, it still shows 450 MB.

* Ubuntu 17.10 x64
* Bitcoin 0.15.1 downloaded from bitcoincore.org

**Comment by Varunram** [comment]
I don't think qt spin-boxes can be set to a specific value (at least acc to the documentation here: http://doc.qt.io/qt-5/qspinbox.html). Since at startup, we default to 450, we could change the minimum value of the spin-box to the cli value. This however, would prevent the user from reducing the db cache size from the cli value. What do you suggest?

**Comment by unsystemizer** [comment]
I suppose this question is meant for the devs, but just in case: I suggest to just show (display) it. Because right below there's `Open Configuration File` and the instructions (how to override) are shown just above it.

**Comment by jonasschnelli** [comment]
The problem:
* If you set a DBCache in the GUI, you overwrite the bitcoin.conf value.

The layers are
* Defaults
* Bitcoin.conf
* startup cli arguments
* GUI

We should at least inform the user that the GUI set value does overwrite in case it's set.

**Comment by unsystemizer** [comment]
@jonasschnelli if you set DBCache in the GUI, bitcoin.conf remains unchanged. 
The same goes for `par` in the same window.

**Comment by Varunram** [comment]
@unsystemizer I think what he means is that it supersedes the bitcoin.conf value in that run, not overwrites.

**Comment by jonasschnelli** [comment]
@unsystemizer: Yes. The bitcoin.conf files gets never changed by Core. But GUI / QT settings are stored in a different file and supersedes the settings in `bitcoin.conf`.

**Comment by valentinewallace** [comment]
Hey guys, played around and I think I might have a fix(?). In optionsmodel.cpp, I check if the -dbcache flag and if it's set, I set the settings value to be the value of the flag and it displays the correct value in the options menu. 

Is there some reason this is not good? I'm new. otherwise, i'll submit a PR! :)

**Comment by unsystemizer** [comment]
Sounds good, but if the value is set to something higher or lower and saved elsewhere, will the correct value be displayed?

One part I don’t understand is what if bitcoind is started instead of Bitcoin-Qt, does the custom value from Qt not take effect in that case? That would be very confusing (if cache changed depending on how you start). But that is a separate thing from the issue at hand, so at least if the correct value was displayed I would be happy as far as this issue is concerned.

**Comment by Varunram** [comment]
I think so, because qt doesn't overwrite the config in the conf file as pointed out earlier. This would be a usability issue, so I guess someone from Core would have to comment about this.

**Comment by jnewbery** [comment]
Note that if the `bitcoin.conf` settings are overriding the qt settings, then you should see the following in the options window:

![image](https://user-images.githubusercontent.com/1063656/38054486-21f853bc-32a5-11e8-9311-ea6c4f74216b.png)

**Comment by hebasto** [comment]
Tested after #14375 merging.

**Case A**

```
$ cat bitcoin.conf | grep dbcache
dbcache=3000
$ bitcoin-qt
```

Options window:
![screenshot from 2019-01-04 22-30-44](https://user-images.githubusercontent.com/32963518/50709425-706bb800-1070-11e9-9a99-fcaa3fa95d4f.png)

**Case B**

```
$ cat bitcoin.conf | grep dbcache
dbcache=3000
$ bitcoin-qt -dbcache=2000
```

Options window:
![screenshot from 2019-01-04 22-34-53](https://user-images.githubusercontent.com/32963518/50709579-fa1b8580-1070-11e9-87d8-4e920ac9749d.png)

IMO, the GUI behaves as expected.

@MarcoFalke, @fanquake, @jonasschnelli Close?
