### ISSUE TITLE
dumpprivkey returning error 

### ISSUE THREAD

**Issue by webwakko** [bitcoin/bitcoin#11786]
Hi,

I'm having an issue with one of my QT-wallets.
When trying to dump the private key for my address I get this error:  
"Private key for address DfbVmexCDLhbsSEGEjSXPAQXGhE7ECKghb is not known (code -4)"
Why is this happening and how can this be solved?

**Comment by sipa** [comment]
That does not look like a Bitcoin address.

Q&A don't belong here; perhaps you can try bitcoin.stackexchange.com

**Comment by webwakko** [comment]
The address is not a bitcoin address, but i'm actualy looking for the problem that can cause this error.  It happens with different people on different qt-wallets.. maybe there is something in the core qt-wallet that can explain this?

**Comment by sipa** [comment]
If the address is not a Bitcoin address, then this response is completely expected.

If this issue is not about Bitcoin Core, you're on the wrong site. Talk to the developers of the software you're using.

**Comment by webwakko** [comment]
ok, who can point me in the right direction for this one? 
I must be very much mistaking if I thought that the info found on this location (https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list) , particulary the dumpprivkey command en linked errors to that command could be explained here..
