### ISSUE TITLE
Claim Bitcoin Cash from Bitcoin Core Wallet using Bitcoin.com Wallet

### ISSUE THREAD

**Issue by eul2017** [bitcoin/bitcoin#11780]
I am trying to claim the Bitcoin Cash using Bitcoin.com Wallet. At the moment all my bitcoins are in Bitcoin Core Wallet and I can not seem to find a good way to do so.

I tried this but it doesn't really work: https://www.bitcoin.com/guides/how-to-access-your-bitcoin-cash-bcc-bch

**Comment by fanquake** [comment]
This issue tracker is for technical issues with the bitcoin core client only. We don't provide general user support, or support for alt coins.
