### ISSUE TITLE
dumpwallet command is not clear and can damage the wallet file

### ISSUE THREAD

**Issue by bsod85** [bitcoin/bitcoin#11798]
It seems to me that it's not clear that dumpwallet command parameter is the destination file.
At first glance I thought it was the source wallet.dat file and the content would be dumped into the console.
This caused the loss of the wallet file (it truncated the file to zero length).
I had a backup but I think a check that the specified file is not the current wallet (to avoid accidental data and coins loss), and a clearer explanation in the console command help text should be added.

**Comment by promag** [comment]
IIRC the dump should not work if the destination file exists.

**Comment by promag** [comment]
What version are you using?

**Comment by bsod85** [comment]
v0.14.1.0-g964a185 (64-bit)

**Comment by promag** [comment]
This was fixed in #9937. Mind closing?

**Comment by bsod85** [comment]
Yes, sorry
