### ISSUE TITLE
can i  manual download protobuf when cross-compilation on ubuntu

### ISSUE THREAD

**Issue by wens07** [bitcoin/bitcoin#11805]
when i execute the cmd `make HOST=x86_64-w64-mingw32`,   it will download the protobuf package, but on my ubuntu environment, it cannot download it because of no proxy, so i want to ask that is it possible to download manual first and where to put it?

**Comment by Varunram** [comment]
In the event you download protobuf manually, you'd need to place it in `/usr/include`. Alternatively, you could run this script: https://gist.github.com/sofyanhadia/37787e5ed098c97919b8c593f0ec44d8.

**Comment by laanwj** [comment]
You can put it in `depends/sources`.
Easiest way to get the correct versions is to do `make download` in depends on a computer that does have internet access, then copy that directory.
