### ISSUE TITLE
Block Explorers should be included (as optional)!

### ISSUE THREAD

**Issue by davimello28** [bitcoin/bitcoin#11810]
Before anything, I've read all of the other posts about this topic. It includes "extra indexes", "txIndexes", "block explorers" and some other topics. English is not my native language, but I will try my best. 

**Resume of the issue:** Node software does not contain an alternative to index all the Blockchain data.
**What I think that could solve the issue:** Implement an option to include the extra indexes, and implement new RPC calls in case of this extra indexes exists. Make a RPC Block Explorer.
**Why you should do that instead of others**: Because it would be easier for you to make it and everybody uses your software. 

**Why I think this is important:**

Every time a someone sends Bitcoins from one address to another, they take a look at a Block Explorer to see if the transaction has actually worked fine. It does not matter the value of the transaction because it feels like you are getting a "payment voucher" (the ticket that you received after paying for something containing some details about the transaction). It happens a lot. 

The issue is that all of this Block Explorers are "visions" of the blockchain. None of them actually IS the blockchain, and none of them should be used like it is blockchain. And unfortunately a huge number of dev's relay on the public APIs from services like Blockchain.info and Blockcypher. They cannot avoid that, since deploying a personal block explorer - even for a independent "vision" of the blockchain - requires a lot of work in a lot of different environments. 

If one of this services lies to us for any reason, we have to believe them. And even if we try to use multiple services, we are restricted to a very feel number of them.

And there is more. 

Imagine this: nodes have a very small incentive to keep them running. The blockchain is getting bigger, the number of transactions is exponentially increasing. This "vision of the truth" factor sounds pretty seductive (aka lucrative). I'm not saying that this already happened, but I'm afraid that it might happen. Internet hooligans are there, and every developer - especially financial related developers -  should be afraid of them. 

I wrote an article in Portuguese about the risk of a correlation attack to identify a wallet owner, especially on countries that have a "tuff government". Most of the people do not run their wallets directly from the node, so we can track down an IP address that has used the block explorer and link it to the owner. I know that Bitcoin is not about privacy (not directly, like Monero, ZCash..), but even this Zero-Knowledge Proofs are tricky if you access them from your PC.  The Onion support is awesome but partially inefficient against this issue.  

I'm not sure if you guys can understand my concern. We are constantly receiving news about wallets from Blockchain.info being hacked (even if the 2FA is enabled). It makes me worry even more. 

The solution, in my point of view, is to unleash all the power that the blockchain data already have. I run a full node at home - on a singular blade server for research purpose - and it would be awesome if I can index all the data so that I can see what is going on. And I'm not even saying anything about a Web UI to allow people to publish their nodes (although I can draw a particularly beautiful one for you if you want - I hate Insights). Just the RPC calls would solve most of the problems. 

Thanks for your time.

**Comment by MarcoFalke** [comment]
I am not sure if I follow your feature request, but note that all of this is likely already included in Bitcoin Core:

* When you sign and send a transaction, you can see the transaction id. This is your "receipt". To get more details about that wallet transaction, you can use the `gettransaction` wallet rpc.
* When you talk about insecure light wallets, you can help by reviewing the "hybrid full block" pull request by jonas #9483
* To the best of my knowledge insight is open source and you can easily run it on your local network if you'd prefer not to trust their website.

**Comment by davimello28** [comment]
@MarcoFalke , you can do that only with your own account, and every time that you create a new address, you have to reindex all the database.

**Comment by luke-jr** [comment]
@MarcoFalke Eh, #9483 is just as insecure as the others...

Presumably the request here is for "block explorer" type functionality in the node itself. But since most "block explorer" functionality is fundamentally misinformation, I think it should be made more specific...
