### ISSUE TITLE
Bitcoin-Qt Coin Selection window has unnecessary columns "9" and "10"

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#11811]
Maybe they have some purpose, but it isn't immediately obvious. I tried Tree & List mode, they're never populated.

![image](https://user-images.githubusercontent.com/13134193/33488849-04a2c8a6-d6ed-11e7-85c3-5c05f1ec5346.png)

* Bitcoin-Qt 0.15.1 for Ubuntu 16.04 x64 (from http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial/main amd64)

Note: I just noticed I'm *not* seeing this on Ubuntu 17.10 x64 with 0.15.1 downloaded from bitcoincore.org. 

![image](https://user-images.githubusercontent.com/13134193/33491553-9584dc62-d6f5-11e7-9ba7-e074e0e36151.png)

**Comment by MarcoFalke** [comment]
In theory they are meant to be hidden.

https://github.com/bitcoin/bitcoin/blob/3c098a8aa0780009c11b66b1a5d488a928629ebf/src/qt/coincontroldialog.cpp#L131-L138

**Comment by jonasschnelli** [comment]
It's probably because the PPA is built with an older version then Qt5.7 which we use in depends. Could even be a Qt4 version.
@TheBlueMatt: does it still uses Qt4?

**Comment by unsystemizer** [comment]
The PPA one is linked against `libQtGui.so.4`.

**Comment by TheBlueMatt** [comment]
We (still) cant move off of Qt4 because of #9038. Still waiting on the death of the tray icon...

**Comment by laanwj** [comment]
FWIW it shouldn't be necessary to use columns to store extra per-row information, from what I remember there are other ways to store extra information in the model backing the tree widget, though I don't remember immediately how.

**Comment by jb55** [comment]
Is this still an issue?
