### ISSUE TITLE
When running bitcoind I keep getting - boost::filesystem::space: Operation not permitted       

### ISSUE THREAD

**Issue by LEscobar-Driver** [bitcoin/bitcoin#11825]
Bitcoin Client Software and Version Number: Bitcoin Core 0.15.1
Operating System: Ubuntu 16.04
System Hardware Specs: 2.4 GHz Intel Core CPU with 16 GB RAM and 750 GB free hard drive space.
Description of Problem: bitcoind refuses to start up. Keep getting the same error over and over.
Screenshot of the problem: https://imgur.com/pj2KFrh
debug.log: https://pastebin.com/2LCw5BJt
bitconi.conf: https://pastebin.com/ZsQArYRy

I have a 250GB SDD and a 750GB HDD which I use as storage on my ubuntu 16.04. I have been running a full bitcoin node for a few weeks which I just use to practice interacting with the bitcoin client. A few days ago I turned on my node and got this

EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::space: Operation not permitted       
bitcoin in AppInit()       

Error: Error: A fatal internal error occurred, see debug.log for details
Error: Error: A fatal internal error occurred, see debug.log for details

I have NO idea how to proceed. I have uninstalled bitcoin core from my system, reformatted my storage drive, reinstalled ubuntu, and just spend hours trying to debug this f'ing issue. I have posted on several message boards and have received literally no helpful replies. My storage HDD is located within the media folder, which I changed permissions on for any user to use. Occasionally bitcoind will start and simply just stay at block 0.... Really frustrated and quite frankly im on the verge of moving on to other projects. Any help me would be greatly appreciated.

**Comment by sipa** [comment]
What filesystem are you using for your datadir?

For some reason it seems like `bitcoind` is not permitted to query how much free space you have.

**Comment by LEscobar-Driver** [comment]
Filesystem                  Type     1K-blocks     Used Available Use% Mounted on
udev                        devtmpfs   8135480        0   8135480   0% /dev
tmpfs                       tmpfs      1632136     9712   1622424   1% /run
/dev/mapper/ubuntu--vg-root ext4     213199112 41030224 161315924  21% /
tmpfs                       tmpfs      8160668   211024   7949644   3% /dev/shm
tmpfs                       tmpfs         5120        4      5116   1% /run/lock
tmpfs                       tmpfs      8160668        0   8160668   0% /sys/fs/cgroup
/dev/sdb2                   ext2        483946   128295    330666  28% /boot
/dev/sdb1                   vfat        523248     3480    519768   1% /boot/efi
/dev/sda1                   ext4     720945320 20248600 664051704   3% /media/Storage
tmpfs                       tmpfs      1632136       80   1632056   1% /run/user/1000

**Comment by TheBlueMatt** [comment]
Not sure how much is to be done here, but you may try running bitcoind in strace, and finding which syscall actually got a permission error, and then looking around for issues there.

**Comment by sipa** [comment]
I believe this is fixed by #11280
