### ISSUE TITLE
Shouldn't this be nOut?

### ISSUE THREAD

**Issue by arielgabizon** [bitcoin/bitcoin#11823]
https://github.com/bitcoin/bitcoin/blob/3c098a8aa0780009c11b66b1a5d488a928629ebf/src/script/interpreter.cpp#L1234

**Comment by afk11** [comment]
https://github.com/bitcoin/bitcoin/blob/8dca7864f793072701f810e4c5ea12a6e1087085/script.cpp#L849 Might be missing some historical comments, but this is correct.

**Comment by sipa** [comment]
By definition, no. This part of the consensus code, so even if it were unintentional, there would be no way to change it.

However, it is intentional. `SIGHASH_SINGLE` means that an input's signature signs the contents of the output *at the same index as the input*.
