### ISSUE TITLE
MISSING BTC

### ISSUE THREAD

**Issue by Undersidedog2** [bitcoin/bitcoin#11821]
Hello, i were using multibit hd and Breadwallet together. I used both of them with 1 wallet opened on both. Suddenly my pc broke and i tried to restore my wallet on new pc. When i restored one btc address with money on it was missing. i tried to generate private addresses from BIP39 mnemonic but i couldnt find that recieving addres in the list of 50000 address. Money is still unspent. Help me to get it back i know wallet words and everything. If someone helps me i will gift him/her a bunch of a beer on btc address :)
I reinstalled mac os everything is deleted. I know what was the wallet words 100% but there is not that addres everywhere i try. In electrum bread or etc.
When i restore wallet every other transactions are visible but the address is missing only that address.. Multibit had bugs that moment and said wrong password and etc..
If someone helps bounty will be 1000 euros.

**Comment by fanquake** [comment]
Please open an issue at the Multibit or Breadwallet forums. The bitcoin core issue tracker isn't used for general help requests.
