### ISSUE TITLE
Sometimes missing desktop notification for new transactions

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11840]
I noticed while testing #11403 that there was no desktop notification (OSX) upon receiving a transaction. This is occasionally happening on master as well. I'm trying to find a reliable way to reproduce.

Steps to (sometimes???) reproduce on master 497d0e014:
1. launch QT a fresh (testnet) wallet
2. generate receive address
3. navigate to Overview tab
4. use another wallet to send funds
5. notice the transaction appears in the list
6. notice no popup notification appears

I'm not getting notifications for `v0.15.1` anymore either, both mainnet and testnet.

Rebooting OSX made this issue go away both on v0.15.1 as well as the SegWit WIP. So at least we can rule out that this has anything to do with #11403. Unfortunately I can't reproduce the issue after this reboot, so I'll continue debugging next time it happens.

**Comment by MarcoFalke** [comment]
Assigning Mac label, since it seems to work on Linux/Gnome:

![screenshot from 2017-12-06 12-24-58](https://user-images.githubusercontent.com/6399679/33675495-bf5f615e-da80-11e7-89dc-3af9dfd168ec.png)

**Comment by Sjors** [comment]
Given that it's inconsistent for me, I don't think the fact that it works on Linux means the bug is OSX-only. But I'm investigating on OSX anyway.

**Comment by MarcoFalke** [comment]
Oh, sorry. I think you meant deterministically reproduce.

**Comment by Sjors** [comment]
I clarified the steps to reproduce to say it may not be deterministic (though right now I'm having difficulty getting notifications to work at all, so recompiling v0.15.1 for comparison).

What's a good way to add debug statements to the various methods involved here? For one thing I'd like to rule out that OSX is somehow not showing the popup. See also [IRC](https://botbot.me/freenode/bitcoin-core-dev/2017-12-06/?msg=94312477&page=3).

**Comment by Sjors** [comment]
I haven't seen this recently. Unless someone else has seen this, we should probably close it.

**Comment by jonasschnelli** [comment]
The way how we inject OSX Notification Center messages is following Apples instructions, though, since this is Obj-C weak framework linking magic, it may not be completely stable... though, "loosing" notifications should not happen. I'd say either it works (framework dynamically loaded, etc.) or not.
Maybe we should also keep eyes open in case Qt implements something like that (to avoid operating system depending code in our repository).

**Comment by hebasto** [comment]
Just leave here http://www.erisian.com.au/bitcoin-core-dev/log-2017-12-06.html#l-370 (as link in https://github.com/bitcoin/bitcoin/issues/11840#issuecomment-349725065 is dead).
