### ISSUE TITLE
Bitcoin core build on Android NDK

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#11844]
It would be useful to have support for building against the Android NDK in the repository as well as the depends system.

Greenaddress is currently doing this and has [scripts and patches for doing so](https://github.com/greenaddress/bitcoin_ndk) in a separate repository.

Integrating this into the upstream build would likely be more maintainable, and it would make it possible to make the ndk build part of the gitian build set at some point, providing higher reassurance for the Android executables.

(sister issue for iOS is #11720)

**Comment by greenaddress** [comment]
Thanks @laanwj 

Some things of note: 

- Android deprecated gcc a while back, will be removed entirely eventually so good to use clang
- the currently working build hasn't been investigated/benchmarked/optimized yet
- It uses android ndk r14b as the latest doesn't work (r16, can see a branch [here](https://github.com/greenaddress/bitcoin_ndk/tree/ndk_r16), build failures once travis is done building will be [here](https://travis-ci.org/greenaddress/bitcoin_ndk/builds/312924976?utm_source=github_status&utm_medium=notification)

**Comment by greenaddress** [comment]
ndk r16 works on:

aarch_64, x86_64

fails on:
arm, x86

from https://travis-ci.org/greenaddress/bitcoin_ndk/builds/312924976?utm_source=github_status&utm_medium=notification

/opt/arm-linux-androideabi-clang/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/fstream:826:20: error: use of undeclared identifier 'ftello'

from a quick investigation this seems an issue with the ndk and what would fix it is not setting D_FILE_OFFSET_BITS=64 (but I couldn't see an easy way to do it yet)

**Comment by greenaddress** [comment]
not setting FILE_OFFSET_BITS in core is not sufficient, I believe zlib is also enabling it (or maybe boost, not sure)

**Comment by jonasschnelli** [comment]
+1 for an Android build support

**Comment by greenaddress** [comment]
looks like not building the samples for libevent is already in master (thanks @fanquake) so the set of patches needed is less  going forward (hopefully at least!)

**Comment by greenaddress** [comment]
I've updated the bitcoin_ndk repo with a new branch for the 0.16 release candidate.

Had to modify the patch to take into account the 0.16 changes but so far looking good https://github.com/greenaddress/bitcoin_ndk/tree/core_0.16 and smaller patches (which is great)

**Comment by laanwj** [comment]
Great! Also good to hear that the required amount of patching is less for 0.16.

**Comment by tofutim** [comment]
Just curious if this is working now.

**Comment by laanwj** [comment]
Not with this repository, that's why the issue is still open.
If you want to play with this, you need @greenaddress 's stuff he links above.

**Comment by tofutim** [comment]
@greenaddress, do you have a gitian-descriptor for android ndk I can experiment with?

**Comment by greenaddress** [comment]
@tofutim sorry just saw this. No I don't have gitian-descriptor. Ideally it would have one but really I wanted to make sure we could use the latest NDK (still on r14b because of 32bit archs failing on later versions) and upstream necessary changes where possible. Right now I'm in the process of refreshing to 0.16.1 and at least build the 64 bit arch with r17b

**Comment by greenaddress** [comment]
@laanwj I updated to 0.16.1 and managed to upgrade to latest ndk compiler (r17b) for both 32/64 bit by passing ac_cv_sys_file_offset_bits accordingly. 

I also had to hack zmq depend because of tautological-constant-compare and new compiler (patch is from zmq upstream)

See https://github.com/greenaddress/bitcoin_ndk/commit/a925df4caa94abdac8727dfac1df191bc2c89277

**Comment by fanquake** [comment]
For reference this is the upstream zmq patch https://github.com/zeromq/libzmq/pull/3140.

@greenaddress Did you want to try and incorporate some of your work back into this repository?

**Comment by fanquake** [comment]
@greenaddress we are already applying patches for [zeromq in depends](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/zeromq.mk#L6), so if we need to pull that patch in to fix a build issue, that isn't a problem. 

Given that zeromq/libzmq#3140 was only merged recently, I'd assume it'll be part of zmq 4.2.6 if/when that's released. However, a zeromq bump in the 0.16.x branch is pretty unlikely now, so just pulling that patch into depends is probably the best approach.

**Comment by greenaddress** [comment]
@theuni In https://github.com/greenaddress/bitcoin_ndk I have patches required for 0.16.1 (and 0.16.2rc2 for that matter)  to build bitcoind using NDK latest (r17b) on arm/x86 32/64 bit both. 

It has patches for depends, adds ifaddrs (missing on android) and patches leveldb fread/write/flush_unlocked to fread/write/flush. It also has the ZMQ fix for tautological constant compare directly from upstream (which, as you suggested, in bitcoin master already could be avoided by using --disable-Werror though that's more impactful)

What do you think, if anything, that we should try to backport either into core or even upstream as applicable?  

By the way, if you have other ideas (like --disable-Werror) or comments about the patches that would improve them or simplify them I am keen on feedback!

**Comment by greenaddress** [comment]
@fanquake I raised https://github.com/bitcoin/bitcoin/pull/13689 for the zmq patches (changed from patching in the disabling of tautological constant compare to patch in disabling of Werror as per @theuni feedback)

Note: the --disable-Werror can only be used in master/0.17.x because we use 4.2.3 zmq, in 0.16,{1,2} we use 4.2.2 which doesn't support --disable-Werror.

**Comment by theuni** [comment]
@greenaddress I took a look at the ndk patches, a few quick notes:
- #13689 should be good to go
- #13659 should have fixed the leveldb build for android, I assume you can drop the fread patches now.
- The libevent patch is annoying to have to carry, but looks good
- I'd prefer to just drop the use of ifaddrs if unsupported by android (api level < 24) by adding an autoconf check for getifaddrs

**Comment by theuni** [comment]
@greenaddress See https://github.com/theuni/bitcoin/commit/6c32dd097755595025f6a94551d77d76cdff2569 for my preferred fix for getifaddrs.

**Comment by greenaddress** [comment]
@theuni 

great, thanks a ton!

Looks like #13659 leveldb fixes works fine https://travis-ci.org/greenaddress/bitcoin_ndk/builds/406349358 thanks for fixing that (at least for 0.17.x/master, for 0.16.2 that wasn't back ported)

https://github.com/theuni/bitcoin/commit/6c32dd097755595025f6a94551d77d76cdff2569 also looks much better to me, and it works too - would that be a candidate for merge in master? want me to raise a PR for it?

Can't wait to make the bitcoin_ndk repo unnecessary and looks like we are on the right path :) see branch https://github.com/greenaddress/bitcoin_ndk/tree/v0.17.0_master

**Comment by greenaddress** [comment]
@theuni also, what about the host depends patches for default and linux i.e. https://github.com/greenaddress/bitcoin_ndk/blob/v0.17.0_master/0001-android-patches.patch ? is there a better way to handle that or anything to do a PR in master for?

**Comment by BlockMechanic** [comment]
Any possibility of this working now ?

**Comment by BlockMechanic** [comment]
> @greenaddress I took a look at the ndk patches, a few quick notes:
> 
> * #13689 should be good to go
> * #13659 should have fixed the leveldb build for android, I assume you can drop the fread patches now.
> * The libevent patch is annoying to have to carry, but looks good
> * I'd prefer to just drop the use of ifaddrs if unsupported by android (api level < 24) by adding an autoconf check for getifaddrs

Hi, while building for both android arm64-v8a and arm-v7a i noted that in the ifaddrs.h provided by the ndk , it states that 
>  * [getifaddrs(3)](http://man7.org/linux/man-pages/man3/getifaddrs.3.html) creates a linked list
 * [freeifaddrs(3)](http://man7.org/linux/man-pages/man3/freeifaddrs.3.html) frees a linked list
> 

Are only supported by ANDROID_API__ >= 24

**Comment by RdeWilde** [comment]
Is this still in the picture?

**Comment by hebasto** [comment]
Does the merged #16110 close this issue?

**Comment by MarcoFalke** [comment]
Closing for now. Not sure if anything is left to do here after #16110. Please reopen if I missed something.
