### ISSUE TITLE
listsinceblock shows conflicted transactions forever

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#11853]
Because listsinceblock walks mapWallet and checks only that GetDepthInMainChain() < the depth of the block requested, conflicted transactions (which have negative GetDepthInMainChain()) may be repeatedly included in output forever. This should (hopefully) not break any usage of the API, but some folks appear to rely on listsinceblock not returning things repeatedly.

**Comment by MarcoFalke** [comment]
Fixed in #17258 ?
