### ISSUE TITLE
Failing to compile (qt library)

### ISSUE THREAD

**Issue by jadox** [bitcoin/bitcoin#11850]
`make[1]: Entering directory '/media/lolek/Bitcoin-Node/bitcoin/src'
Making install in .
make[2]: Entering directory '/media/lolek/Bitcoin-Node/bitcoin/src'
make[3]: Entering directory '/media/lolek/Bitcoin-Node/bitcoin/src'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c bitcoind bitcoin-cli '/usr/local/bin'
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/media/lolek/Bitcoin-Node/bitcoin/src'
make[2]: Leaving directory '/media/lolek/Bitcoin-Node/bitcoin/src'
Making install in qt
make[2]: Entering directory '/media/lolek/Bitcoin-Node/bitcoin/src/qt'
make  install-recursive
make[3]: Entering directory '/media/lolek/Bitcoin-Node/bitcoin/src/qt'
Making install in .
make[4]: Entering directory '/media/lolek/Bitcoin-Node/bitcoin/src/qt'
  CXX      libbitcoinqt_a-bitcoin.o
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h:37:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow:1,
                 from bitcoingui.h:12,
                 from bitcoin.cpp:9:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1067:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
Makefile:1232: recipe for target 'libbitcoinqt_a-bitcoin.o' failed
make[4]: *** [libbitcoinqt_a-bitcoin.o] Error 1
make[4]: Leaving directory '/media/lolek/Bitcoin-Node/bitcoin/src/qt'
Makefile:2578: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/media/lolek/Bitcoin-Node/bitcoin/src/qt'
Makefile:2735: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/media/lolek/Bitcoin-Node/bitcoin/src/qt'
Makefile:860: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/media/lolek/Bitcoin-Node/bitcoin/src'
Makefile:509: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
`
This error is thrown when trying to compile the Bitcoin Core.
Any ideas what's wrong?

Thanks

Ubuntu 16.04

**Comment by jonasschnelli** [comment]
If you want to compile Qt yourself, try to compile with the depends system:
```shell
cd depends
make
cd ..
./configure --prefix=`pwd`/depends/<YOUR_HOST_PLATFORM>
```

If you want the simple approach, install the Qt libraries via apt (see https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md).

**Comment by Sjors** [comment]
@jadox are you still having this issue?
