### ISSUE TITLE
Bitcoin core is not opening

### ISSUE THREAD

**Issue by Dhurv000077** [bitcoin/bitcoin#11855]
I downloaded bitcoin core wallet last week, everything was fine but now it won't open properly.
![screenshot from 2017-12-08 23-31-03](https://user-images.githubusercontent.com/18211427/33778729-00d9c4b2-dc70-11e7-8970-7ee1bada3465.png)

It's just stuck at this "Done loading" window.

**Comment by TheBlueMatt** [comment]
Sometimes things get stuck at "Done loading" for quite some time depending on how fast your disk is and how Bitcoin Core was previously shut down. We should, obviously, have better UX here.

**Comment by laanwj** [comment]
Yes, another case there the GUI thread tries to get cs_main and it's not available for a long time.

In the meantime anyhow it will open if you wait long enough, you could check debug.log for progress.

**Comment by amal** [comment]
Same issue with 0.15.1
