### ISSUE TITLE
Visual studio Build setup for CI

### ISSUE THREAD

**Issue by sipsorcery** [bitcoin/bitcoin#11873]
Is there a webhook currently set on this repo for Pull Requests that could be used to trigger external builds?

I've configured an [appveyor Visual Studio 2017 build job](https://ci.appveyor.com/project/sipsorcery/bitcoin) in conjunction with #11526 and it would be nice to trigger it for new commits.

**Comment by huhorler** [comment]
Can you cimmits the VS .sln and .proj ?

**Comment by sipsorcery** [comment]
@huhorler see #11526 for the instructions on how to acquire the Visual Studio solution and project files. They have only been submitted as a pull request at this stage so are not available in the main repository.

If you just want to take a quick peek at them you can use the git command below from your Bitcoin Core repo.

`git pull origin pull/11526/head`

**Comment by huhorler** [comment]
@sipsorcery Thanks,I got it. But,why the main repository do not provide the Windows dev environment,there are so many developers for windows

**Comment by NicolasDorier** [comment]
@huhorler windows was initially supported (satoshi was developing on Visual Studio).
My guess is that it has been dropped in favor of autotools which is easier way to generate cross plateform binaries. 
Having to support both autotool build + msvc might have been a burden that the devs, mostly linux guys, did not wanted to bother with.

This however exclude lot's of potential contributors as well as impact general productivity. 
@sipsorcery  way seems to not be a big burden to maintain though.

**Comment by huhorler** [comment]
The qt need install the qt5?

**Comment by huhorler** [comment]
the bitcoin-qt need to install qt5?

**Comment by sipa** [comment]
@huhorler This issue trackers is for discussing software changes and issues, not for user support.

**Comment by sipsorcery** [comment]
Will attempt to find an alternative to the github webhooks to detect new commits. Probably need a polling script.
