### ISSUE TITLE
Prevent Opening Wallets Simultaneously in Two Instances

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#11888]
As of #11466 we no longer have any logic to prevent a user from opening a wallet twice in two instances simultaneously. Not only could this break BDB (without the -privdb=false option, which I have really no idea why we even have a tuneable option for that), but we certainly don't have logic to handle such a case gracefully. It was noted in the original PR's description, but somehow was never followed up on before merge.

**Comment by ryanofsky** [comment]
> -privdb=false option, which I have really no idea why we even have a tuneable option for that

Presumably, option provides more safety at the cost of some performance. With default privdb setting, wallet could be totally corrupted if opened in more than one process. But with privdb=false, maybe you will reuse an address or see duplicate transactions, but you probably won't lose your private keys. According to https://docs.oracle.com/cd/E17276_01/html/api_reference/C/envopen.html, privdb=false would also let you run BDB utilities like db_dump, db_archive, db_checkpoint, db_stat on the wallet while bitcoin is running.

**Comment by TheBlueMatt** [comment]
> Presumably, option provides more safety at the cost of some performance. With default privdb setting, wallet could be totally corrupted if opened in more than one process. But with privdb=false, maybe you will reuse an address or see duplicate transactions, but you probably won't lose your private keys.

Either way its unsupported, and prior to 0.15.0, without adding symlinks/hardlinks, we would not have allowed it anyway.

> According to https://docs.oracle.com/cd/E17276_01/html/api_reference/C/envopen.html, privdb=false would also let you run BDB utilities like db_dump, db_archive, db_checkpoint, db_stat on the wallet while bitcoin is running.

I'd be surprised if any users using those utilities were aware of the -privdb option. We dont need to have an option for all kinds of random internal minutia.
