### ISSUE TITLE
Replace atoi64 with ParseInt64

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#11897]
When converting user input the result is zero if the conversion fails. There should be a better error handling, especially in argument/config handling.

cc @laanwj

**Comment by MarcoFalke** [comment]
This is already mentioned in the developer notes: https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#strings-and-formatting

Please submit a pull request if the current code is not conformant.

**Comment by promag** [comment]
Such PR could be a complex refactor. One usage to fix is `GetArg(..., uint64_t)`.

**Comment by MarcoFalke** [comment]
That, imo, should be solved by checking the command line args on init. C.f.  #11819
