### ISSUE TITLE
[RPC] gettransaction calculates fee incorrectly if inputs are not all from the bitcoind wallet

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#11893]
I created a transaction with an offline wallet that spent outputs from two different addresses.
I then imported only one of those two private keys into bitcoind with `importprivkey`.

When I viewed the transaction in bitcoind I was shocked to see such an incredible fee! I realize it's because the fee is calculated from the perspective of the wallet, not the actual total `vin - vout` difference the miner actually collects:

vin:
`0.00037120` from imported key
`0.09799380` from the other key

vout:
`0.09802500`

actual miner fee:
`0.00034000`

fee reported by `gettransaction`:
`0.09765380`

```
$ bitcoin-cli gettransaction fa[...obfuscated...]39
{
  "amount": -0.09802500,
  "fee": 0.09765380,
  "confirmations": 0,
  "trusted": false,
  "txid": "fa[...obfuscated...]39",
  "walletconflicts": [
  ],
  "time": 1513211216,
  "timereceived": 1513211216,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "",
      "address": "1[...obfuscated...]j",
      "category": "send",
      "amount": -0.09802500,
      "vout": 0,
      "fee": 0.09765380,
      "abandoned": false
    }
  ],
  "hex": "01[...obfuscated...]00"
}

```

**Comment by morcos** [comment]
This was addressed in #9167 which I let go stale after it didn't get much love.
I or someone should rebase that PR.

**Comment by pinheadmz** [comment]
Ah thanks I'll take a look. I had a feeling this would have already been addressed

**Comment by pinheadmz** [comment]
Would it make sense to implement the fee calculation in rpc/rawtransaction just for the sake of this use-case? Instead of changing the wallet code? That's something I might be able to do.

**Comment by sipa** [comment]
@pinheadmz We can't compute the fee for arbitrary transactions. The inputs may not be available.

**Comment by promag** [comment]
@sipa yes, but should we do it if the inputs are available? With `-txindex` it should be normally possible.

**Comment by sipa** [comment]
@promag I don't think we should. Changing behaviour just because an index is available is very confusing - I think its functionality should be limited to strictly enabling certain functionality but not modify something. Furthemore, `-txindex` is slow, not optimized, and not something we can expect common users to enable.

**Comment by pinheadmz** [comment]
Thanks @sipa that makes sense, I forgot the input values may not be available unless the transaction is relevant to the wallet.
