### ISSUE TITLE
bitcoin.conf issue

### ISSUE THREAD

**Issue by anggaand123** [bitcoin/bitcoin#11898]
Hi ,
today i try running bitcoin daemon in my vps .
but i found the problem , the `bitcoin.conf` is not exist in` .bitcoin` folder .
but the daemon running with no problem ( i not yet tested transaction send or receive )

this a look
http://prntscr.com/hngebc
i running the latest bitcoin and im try `0.14.2` still same
please help me

**Comment by MarcoFalke** [comment]
> the bitcoin.conf is not exist in.bitcoin folder .

You can create a bitcoin.conf using your favorite text editor, if needed at all.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by anggaand123** [comment]
@MarcoFalke i already did it, when i stop the daemon . and start again the daemon could not started . the error showing` (make sure server is running and you are connecting to the correct RPC port)`

**Comment by MarcoFalke** [comment]
That error message should only be thrown by bitcoin-cli, not bitcoind or bitcoin-qt. Make sure to actually start the server (`bitcoind` or `bitcoin-qt -server`)

**Comment by anggaand123** [comment]
so how i take contorl bitcoin-cli ?? i need this command

**Comment by sipa** [comment]
@anggaand123 This is a place to discuss program issues, it is not for support.

If you need help using bitcoin core, there are various other forums available, including bitcoin.stackexchange.com, bitcointall.org, and others.
