### ISSUE TITLE
Bitcoin Core GUI wouldn't pick up custom fees

### ISSUE THREAD

**Issue by omegachien** [bitcoin/bitcoin#11899]
Whenever I want to send BTC, after setting up the custom transaction fees and selecting the radiobox and click send, it seems like it's not reading the value from the custom field that I filled in.

![bug](https://user-images.githubusercontent.com/4597798/33999728-35f377dc-e126-11e7-8379-21a1b0364864.png)

Bitcoin Core version: 0.15.1 Windows 10 64 bits

**Comment by morcos** [comment]
That looks like it's working correctly, what is wrong?
The custom fee is a custom feerate.  you selected 85000 satoshi per kB. and your transaction is 0.226 kB so the fee is 19210 satoshis.

**Comment by omegachien** [comment]
oh my god, that's how it works. Thanks a lot.
