### ISSUE TITLE
For help, move BTC to an unused wallet address.

### ISSUE THREAD

**Issue by sy7870** [bitcoin/bitcoin#11894]
Hello：
I am a faithful believer in BTC. In December 2013, I had a BTC transaction which turned the wrong wallet address, but this address is not yet owned by the owner, and it has not been used yet. I hope that I can get your help, help me find BTC, or distribute the wallet address to me. I can provide the proof of BTC transaction and these BTC coins are my proof materials. I very much hope to get your help. Thank you, and look forward to your reply, my mailbox: 13815849858@163.com.
Wish BTC is getting better and better.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
