### ISSUE TITLE
Travis x86_64-apple-darwin11 errors: "Configuring boost...  /bin/sh: 1: requires: not found"

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#11906]
I'm seeing travis errors for the x86_64-apple-darwin11 build in two PRs (#9381, #9680). Failure happens reliably within a few minutes of restarting the build. Output:

https://travis-ci.org/bitcoin/bitcoin/jobs/316549754
https://travis-ci.org/bitcoin/bitcoin/jobs/316549909

```sh
$ if [ -z "$NO_DEPENDS" ]; then make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS; fi
make: Entering directory `/home/travis/build/bitcoin/bitcoin/depends'
Fetching boost_1_64_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.64.0/source/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 76.7M  100 76.7M    0     0  49.7M      0  0:00:01  0:00:01 --:--:-- 63.9M
/home/travis/build/bitcoin/bitcoin/depends/work/download/boost-1_64_0/boost_1_64_0.tar.bz2.temp: OK
Extracting boost...
/home/travis/build/bitcoin/bitcoin/depends/sources/boost_1_64_0.tar.bz2: OK
Preprocessing boost...
Configuring boost...
/bin/sh: 1: requires: not found
make: *** [/home/travis/build/bitcoin/bitcoin/depends/work/build/x86_64-apple-darwin11/boost/1_64_0-b3948cb0d56/./.stamp_configured] Error 127
make: Leaving directory `/home/travis/build/bitcoin/bitcoin/depends'


The command "if [ -z "$NO_DEPENDS" ]; then make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS; fi" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by fivepiece** [comment]
"requires" seems to be a part of an earlier error : https://travis-ci.org/bitcoin/bitcoin/jobs/316549754#L354
```
grep: requires: No such file or directory
grep: Node.js: No such file or directory
grep: 4.0: No such file or directory
grep: or: No such file or directory
grep: higher: No such file or directory
grep: to: No such file or directory
grep: be: No such file or directory
grep: installed.:: No such file or directory
```
The search term "requires Node.js 4.0 or higher to be installed" points to software called `yarn`, not sure if related.

**Comment by ryanofsky** [comment]
Interesting, and that error on line 354 is very early on, it seems before our configuration environment variables are even loaded (line 381). RIght now, I'm trying rebasing on latest master c66adb286a89738a6a5218be2ecfea8e398878dd -> 8585bb8f058441b951b8012de8c0e45207528dec to see if that will maybe make travis clear some bad cache and work around the error.

**Comment by ryanofsky** [comment]
Same problem's still happening after rebase:

https://travis-ci.org/bitcoin/bitcoin/jobs/316904549
https://travis-ci.org/bitcoin/bitcoin/jobs/316904657

**Comment by ryanofsky** [comment]
As suggested by @MarcoFalke, I'm currently trying to run travis directly on my #9680 github branch:

https://travis-ci.org/ryanofsky/bitcoin/builds/316992931

**Comment by ryanofsky** [comment]
This looks like it might be related to https://github.com/travis-ci/travis-build/pull/1275

**Comment by MarcoFalke** [comment]
Closing, since the issue apparently was caused on the travis end (upstream). Should be fixed now
