### ISSUE TITLE
Additional btc node for a web service. Watch on a web service wallets. Confirm a web service wallets transactions first.

### ISSUE THREAD

**Issue by mxen** [bitcoin/bitcoin#11932]
Watch on my wallets and confirm my wallets transactions first.

As a client, I sent a money to a web service.
My transaction will be confirmed for minutes 10 maybe more...
My suggestion is the web service runs additional bitcoin node to confirm the service wallets transactions first.

Thank you in advance, I hope the Bitcoin transactions will be faster.

**Comment by jonasschnelli** [comment]
This is the issue tracker for direct development issue. Please use the mailing list (bitcoin-dev) for proposals like this.
