### ISSUE TITLE
Error code -1 need help

### ISSUE THREAD

**Issue by BeRichh** [bitcoin/bitcoin#11934]
Hello,

When im downloading the blocks of bitcoinrpc on my server, i got this error code: -1
-> http://prntscr.com/hotl1e

So i restart the bitcoind, and the block restart downloading, but after x time i got the same error, several time.

How can i fix it?
Im on debian, and i have 1TB diskspace

Thanks you!

**Comment by TheBlueMatt** [comment]
It looks like bitcoind is crashing/shutting down. Can you take a look at debug.log and see what it says at the end once bitcoind dies? Also check syslog/dmesg to see if its getting OOM killed.

**Comment by BeRichh** [comment]
My debug.log : https://hastebin.com/igafapeyep.sql

**Comment by MarcoFalke** [comment]
The link with the debug log is dead.

Is this still an issue with a recent version of Bitcoin Core? Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).
