### ISSUE TITLE
Speed Improvements 💡 

### ISSUE THREAD

**Issue by samuelGrahame** [bitcoin/bitcoin#11933]
I know this is probably the wrong place, but I was thinking. Would it be possible to just have the wallets do some little bit of targeted mining. If you send btc it would mine a few transactions and when you awaiting for a payment, that is mines the transaction that is unconfirmed and a few near it. Obviously I don't know the coding structure for mining. If in the same way miners target transactions with big fees. The  you could target by to address.

**Comment by sipa** [comment]
This is not a place for shower thoughts.

If you have a well worked-out design, you can discuss it on the bitcoin-dev mailinglist.

**Comment by samuelGrahame** [comment]
I'm sorry
