### ISSUE TITLE
How to synchronize access to wallet notifications?

### ISSUE THREAD

**Issue by mymixing** [bitcoin/bitcoin#11942]
I want to write a wallet client using bitcoind
Now there's a problem
How can I get the change notification from bitcoind in real time?
I hope to get push notifications from bitcoind
So I found the ZMQ component,
But the ZMQ component supports only the following message push,
  -hashblock
  -hashtx
  -rawblock
  -rawtx
But I only pay attention to my wallet table east notice, ZMQ can't meet my needs
Can someone help me?

**Comment by TheBlueMatt** [comment]
You may be interested in helping review #10554 to get wallet notifications out of ZMQ. You may also want to look into the -walletnotify option.

**Comment by MarcoFalke** [comment]
On a side note, general bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
