### ISSUE TITLE
Bitcoin Core crashes at startup on MAC

### ISSUE THREAD

**Issue by chrisrtz** [bitcoin/bitcoin#11940]
Hello, 

About two months ago, i was able to start Bitcoin Core on my MAC OS.  Nothing has changed, been using the same computer, when i went to start MAC OS, it just keeps crashing.  Does anyone else have the same issue.  

[debug.log](https://github.com/bitcoin/bitcoin/files/1569589/debug.log)

**Comment by MarcoFalke** [comment]
An update from "Bitcoin version v0.8.5-beta (2013-09-12 13:35:18 +1000)" to version v0.15.1 is officially not supported, but should work nonetheless. It appears the 0.8.5 node was not shut down cleanly and the blocks stored on disk might be corrupt, you can try `-reindex` to rebuild the chainstate and download any missing or corrupt blocks.
