### ISSUE TITLE
configure: error: openssl  not found

### ISSUE THREAD

**Issue by nextgentechguru** [bitcoin/bitcoin#11944]
So, I am new to this and using Ubuntu 14.04 LTS on Virtual Box and using the v0.15.1 source. I have been trying to compile the bitcoin source but I am stuck with openssl, below is the error I get when I run configure:
configure: error: openssl  not found  
I have installed openssl following an earlier posted issue on here and verified it's location on my box is  - /usr/bin/openssl
This is for openssl 1.0.1g and I tried to set the $OPENSSL_PREFIX  to be the same as openssl location but keep getting the same "openssl not found" error.
Really looking for some guidance here from anyone who got thru this.
Much appreciated!

**Comment by CarlHoo** [comment]
Same error!
So, how do you resolved it?
Thanks very much!
