### ISSUE TITLE
"make docs" or such to build doxygen documentation

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#11949]
Would be nice to have a "make docs" that builds the developer documentation.
It is hosted on https://dev.visucore.com/bitcoin/doxygen/, but some users prefer an offline copy (and one up to date with their specific branch).

Essentially it would do:
```bash
doxygen doc/Doxyfile
```
(but taking into account build/source directories if separate)

It could also build other documentation in the future.

**Comment by converge** [comment]
hey @laanwj , do you have an example of the expected result ?

**Comment by laanwj** [comment]
You mean the doxygen output? Here's what the output looks like: https://dev.visucore.com/bitcoin/doxygen/

**Comment by Ov3rlo4d** [comment]
My pull request should do exactly that, `make docs` (after configuring the project) will generate the doxygen documentation in docs/doxygen/html.
