### ISSUE TITLE
Avoid generating UI elements from code

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11950]
Please don't do this:
<img width="926" alt="schermafbeelding 2017-12-19 om 16 28 31" src="https://user-images.githubusercontent.com/10217/34164373-ade137e6-e4d9-11e7-84b2-c23e7b35ea31.png">

Or this:
<img width="530" alt="schermafbeelding 2017-12-19 om 17 18 28" src="https://user-images.githubusercontent.com/10217/34166976-b2c86782-e4e0-11e7-907a-eea9fd435b09.png">

QT builder has all sort of nifty tricks to keep the layout pretty, but we can't leverage that when parts of the UI are generated from code. Editing the XML files is probably fine though.

Notice how the amount field in interface builder is given full width:

<img width="789" alt="qt builder" src="https://user-images.githubusercontent.com/10217/34164414-bfe89006-e4d9-11e7-919e-913a072e838f.png">

The currency selection dropdown is added later:

<img width="740" alt="schermafbeelding 2017-12-19 om 16 39 06" src="https://user-images.githubusercontent.com/10217/34164924-292f7e5c-e4db-11e7-9228-f78ce2f7e5a7.png">

If I then try to add some UI element to the right of the currency dropdown (like a bech32 check-box), things get ugly:

<img width="754" alt="schermafbeelding 2017-12-19 om 16 35 30" src="https://user-images.githubusercontent.com/10217/34164755-ab3aee78-e4da-11e7-9ff1-ebdd393eddaa.png">

Note how "format" is too far to the right, and this checkbox should really be snapped to the left. Of course it can be fixed with even more UI generating code, but I've been there, it's a dark place :-)

I'll try to refactor this specific example.

I'll be careful not to create a giant xml diff in the process.

**Comment by jonasschnelli** [comment]
I agree with most @Sjors pointing out in this PR.
Though this issue is not really specific,... and difficult to say, when we have solved it (because it includes recommendations)

**Comment by Sjors** [comment]
Regarding `BitcoinAmountField` we could create a [custom widget plugin](http://doc.qt.io/qt-5/qtdesigner-customwidgetplugin-example.html) to encapsulate its UI subelements (amount field + spinbox + currency dropdown) and functionality. If I understand correctly, the interface builder can then use that widget and show you a preview that's more like the real thing. That's not trivial. Turns out, fortunately, it's not urgent either!

Having studied `BitcoinAmountField` a bit more, it turns out this class isn't messing with the UI as much as I initially thought (and the top most screenshot is something else). Although the code adds a Spinbox (to increase and decrease the amount) and a ComboBox (to select the currency), they are added inside of the space allocated to BitcoinAmountField by interface builder, not next to it. So interface builder still works, I was just using it wrong.

Embedding amount in a QHBoxLayout and putting a horizontal spacer on the right side of the check box did the trick:
<img width="749" alt="schermafbeelding 2017-12-19 om 20 58 48" src="https://user-images.githubusercontent.com/10217/34176215-6ff6a030-e4ff-11e7-8283-82d79c931cf6.png">

**Comment by jnewbery** [comment]
@Sjors - is this issue tracking any specific action? If not, are you happy to close it?

**Comment by Sjors** [comment]
I would like to see this become a code guideline, but currently too lazy to do so. I'll close for now.

**Comment by luke-jr** [comment]
FWIW, I prefer going the opposite direction, at least for the options dialog.
