### ISSUE TITLE
rejected txs and blocks get re-downloaded when seen again

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#1195]
Extract from debug.log:-

04/05/12 22:45:11 askfor tx 6486a05 at 22:45:10 at 78.47.187.252:8333
04/05/12 22:45:11 getdata tx 6486a053d065fb7f94fb to 78.47.187.252:8333
04/05/12 22:45:11 askfor tx 6486a05 at 22:45:21 at p2hwc26zdsrqxiix.onion:8333
04/05/12 22:45:14 txaccept: free tx 6486a053d0 from 78.47.187.252:8333 rejected by rate limiter
04/05/12 22:45:14 askfor tx 6486a05 at 22:45:31 at a57qr3ydpnyntf5k.onion:8333
04/05/12 22:45:14 askfor tx 6486a05 at 22:45:41 at sjdntqu5roj4q6lo.onion:8333
04/05/12 22:45:14 askfor tx 6486a05 at 22:45:51 at 7hxvg2lvr2ashzli.onion:8333
04/05/12 22:45:16 askfor tx 6486a05 at 22:46:01 at siqdznszjf4e6v5j.onion:8333
04/05/12 22:45:20 askfor tx 6486a05 at 22:46:11 at 204.62.15.140:8333
04/05/12 22:45:21 getdata tx 6486a053d065fb7f94fb to p2hwc26zdsrqxiix.onion:8333
04/05/12 22:45:22 askfor tx 6486a05 at 22:45:31 at 88.80.6.187:8333
04/05/12 22:45:26 txaccept: free tx 6486a053d0 from p2hwc26zdsrqxiix.onion:8333 rejected by rate limiter
04/05/12 22:45:31 getdata tx 6486a053d065fb7f94fb to a57qr3ydpnyntf5k.onion:8333
04/05/12 22:45:31 getdata tx 6486a053d065fb7f94fb to 88.80.6.187:8333
04/05/12 22:45:31 txaccept: free tx 6486a053d0 from 88.80.6.187:8333 rejected by rate limiter
04/05/12 22:45:32 txaccept: free tx 6486a053d0 from a57qr3ydpnyntf5k.onion:8333 rejected by rate limiter
04/05/12 22:45:39 askfor tx 6486a05 at 22:45:41 at 69.164.196.4:8333
04/05/12 22:45:41 getdata tx 6486a053d065fb7f94fb to 69.164.196.4:8333
04/05/12 22:45:41 getdata tx 6486a053d065fb7f94fb to sjdntqu5roj4q6lo.onion:8333
04/05/12 22:45:41 txaccept: free tx 6486a053d0 from 69.164.196.4:8333 rejected by rate limiter
04/05/12 22:45:43 txaccept: free tx 6486a053d0 from sjdntqu5roj4q6lo.onion:8333 rejected by rate limiter
04/05/12 22:45:51 getdata tx 6486a053d065fb7f94fb to 7hxvg2lvr2ashzli.onion:8333
04/05/12 22:45:55 txaccept: free tx 6486a053d0 from 7hxvg2lvr2ashzli.onion:8333 rejected by rate limiter
04/05/12 22:46:01 getdata tx 6486a053d065fb7f94fb to siqdznszjf4e6v5j.onion:8333
04/05/12 22:46:03 txaccept: free tx 6486a053d0 from siqdznszjf4e6v5j.onion:8333 rejected by rate limiter
04/05/12 22:46:11 getdata tx 6486a053d065fb7f94fb to 204.62.15.140:8333
04/05/12 22:46:15 txaccept: free tx 6486a053d0 from 204.62.15.140:8333 rejected by rate limiter

This is a grep of debug.log for this one transaction, but the happens with blocks also. This could become more of a problem in the future as the network grows and the same transactions is gossiped around the network for a while.

Is it worth creating a memory pool of rejected blocks and transactions? Perhaps keeping only their hash rather than the whole block or transaction? This way, bandwidth can be saved for all nodes (at some small expense of memory storing the "ignore list").

**Comment by paveljanik** [comment]
Looks like this is fixed by #6452.

**Comment by MarcoFalke** [comment]
@rebroad Is this still an issue?

**Comment by rebroad** [comment]
no idea, it's old so I doubt it.. I'll close it for now - I've not been watching tx debug for a while...
