### ISSUE TITLE
Transaction fees 30%-40%, Transaction congestion 9-16hr

### ISSUE THREAD

**Issue by S5h4D3S** [bitcoin/bitcoin#11963]
Hello I have question how it looks with lowering fees at the moment the fees are extreme 30-40% per transaction the confirmation time is 9-12hours some transactions are unconfirmed 2 weeks.
Micropayments impossible company temporary closed support for bitcoin payment due to high fees and confirmation time.
Is there any plan to implement the lightning network or reduce block time for 2 minute with rewards for miners 1.2 BTG. Or increase the block size for 8MB.
Official Bitcoin Core page is not giving out any information's how this would be solved. Competition fork already have low fees lightning network. Even the bitpay offering payment with fork bitcoin.
This is a serious issue as i see everyday people that bought Bitcoin at november regret that step because of the fees, small mining farms already switch to fork bitcoin, because of extreme Bitcoin transaction fees and others think about it. Thank you for your answer

**Comment by Willtech** [comment]
None of this is related to Bitcoin Core but, I hope that you will allow me to indulge.

There are several proposals in existence, improvements that would each wholly/partly resolve the speed/reliability/fee issues. What is needed are analysts to determine specifications, programmers to code and, testers to verify operations. Nothing happens until specifications are determined, and the process is slow. Also, there is perceived great resistance to hard-fork scenarios, but let us hope not when they are beneficial and necessary.

The ability to send micropayments is a part of the utility value of bitcoin. I do not see that it is necessary to lower the average fee, indeed the highest fees may yet increase, but it is necessary that it is possible also to send small payments with a small fee reliably.

In fact, lowering the average fee may in the long-run be detrimental to Bitcoin, it is just necessary for the service to retain its utility value.

I would welcome your feedback on one of the many proposals, the one that I have been working on "[UTPFOTIB](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-January/015492.html)" - there is still some work to do before that proposal is formalised.
