### ISSUE TITLE
Node dropping it's own transactions

### ISSUE THREAD

**Issue by AdvancedStyle** [bitcoin/bitcoin#11961]
Version: 0.15.1 built from source
OS: Debian Jessie

Issue:
Sent a transaction with low fee, and it was stuck in the mempool, after about 4 days and large increase in fees, the node appears to have dropped the transaction out of the listunspent....however it does not add back the original UTXOs to the listunspent...so basically the bitcoins just disappear.  And only way regain visibility is to rescan (pain on pruned node)

Expected behavior:
Node should either list the original UTXOs and drop the unconfirmed transaction
Or node should remember the new unconfirmed transaction and not drop it

Certainly the bitcoins shouldn't just disappear from the listunspent...

**Comment by RHavar** [comment]
I'm not sure if it's been fixed or not (I haven't observed it recently) but a year ago or so, this could cause a permanent "loss"[1] in funds, even after the transaction confirmed.


[1] only recoverably by doing something like -rescan on your wallet

**Comment by LeandroJF** [comment]
Sometimes this happens to me too, as mempool is full with transactions with higher fees. But to have my low fee transaction back to listunspent, I just need to close the Bitcoin Core, delete the mempool.dat file and reopen my Bitcoin Core. Have you tried that? I'm pretty sure that you don't need to redownload and rescan all the 150GB of the BlockChain.

**Comment by MarcoFalke** [comment]
I think the solution would be to `abandontransaction`, which will allow for their inputs to be respent.

Otherwise you could bump the fee or wait until the transaction can be accepted into the mempool again.
