### ISSUE TITLE
Replace-by-fee via RPC

### ISSUE THREAD

**Issue by khelle** [bitcoin/bitcoin#11973]
Is it possible to replace-by-fee existing transaction in mempool purely using RPC commands? If yes, then how?

**Comment by RHavar** [comment]
You can use `bumpfee` if you purely care about increasing the fee of a transaction (although I would never rely on the ability to do this, as the command is very unreliable).

The more general approach would be to use `createrawtransaction`

Also this question would be best put on stackoverflow, not as a bug report

**Comment by jonasschnelli** [comment]
Replace-by-fee (`bumpfee` or via `createrawtransaction`) is only possible for a transaction where you have previously "enabled" RBF (means the transaction does signal BIP125 RBF via inputs `nSequence`).

If you haven't had `-walletrbf` enabled or did check the checkbox in Qt (or used the right RPC arguments), you can't use RBF reliable.

Another way how to unstuck transactions is by CPFP (child pays for parent) via Qt/CoinControl (I have done that serval times and assisted some users with that).
You basically choose the stuck transactions change output as a new input for a self-to-self transaction and pay twice the required fee.
