### ISSUE TITLE
See if there is consensus for a HF block weight increase?

### ISSUE THREAD

**Issue by booung** [bitcoin/bitcoin#11975]
First of all thanks to all the amazing people who do the great work here on Bitcoin! Now that segwit is active and likely to be included in the coming 0.15.2 release, and that the 2X attack is behind us. Can we start to try and find consensus for a HF for a block weight increase done properly with adequate time and testing? Unfortunately I don't have the technical skills to be involved with something like this but would happily donate 1 btc (I'm sure others would also chip in as well) to start a bounty for this work if we can first get community consensus. Apologies if this is not the correct place for this discussion, please close if so.

**Comment by laudaa** [comment]
The weight is not even being utilized (less than 10%), why would we increase it again?

**Comment by booung** [comment]
I probably shouldn't be posting here as I don't have the technical knowledge or experience so am closing this issue. But my thought was get the smart people here to have a discussion about a possible weight increase and if it's even needed, when they think it would be needed, and how it would be done. Planning and testing this would of course take a lot of time so it will be nice to be ready as Bitcoin seems to be growing much faster than expected.
