### ISSUE TITLE
PUBKEY_ADDRESS problem

### ISSUE THREAD

**Issue by amd5** [bitcoin/bitcoin#11983]
old version PUBKEY_ADDRESS
base58Prefixes[PUBKEY_ADDRESS] = boost::assign::list_of(80);
80=Z
link: https://en.bitcoin.it/wiki/List_of_address_prefixes

current  PUBKEY_ADDRESS
base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1,0);
How to modify ？

**Comment by amd5** [comment]
Why close ?

**Comment by sipa** [comment]
This is a not an issue in Bitcoin Core.

**Comment by amd5** [comment]
I'm a beginner, how can I find my answer

**Comment by sipa** [comment]
Try https://bitcoin.stackexchange.com

**Comment by amd5** [comment]
tks，Fix OK
