### ISSUE TITLE
Unable to compile and download zeromq v4.2.2

### ISSUE THREAD

**Issue by amd5** [bitcoin/bitcoin#11982]
https://github.com/zeromq/libzmq/releases/download/v4.2.2/

bitcoin Unable to compile and download

-----------------------------------------------------------------------------------------------------
===========================================================
Caching libevent...
Fetching zeromq-4.2.2.tar.gz from https://github.com/zeromq/libzmq/releases/download/v4.2.2/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   607    0   607    0     0    527      0 --:--:--  0:00:01 --:--:--   527
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Connection timed out after 10015 milliseconds
Fetching zeromq-4.2.2.tar.gz from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [/home/c32/bitcoin/depends/sources/download-stamps/.stamp_fetched-zeromq-zeromq-4.2.2.tar.gz.hash] 错误 22
root@c:/home/c32/bitcoin/depends# make HOST=i686-w64-mingw32
Checksum missing or mismatched for zeromq source. Forcing re-download.
Fetching zeromq-4.2.2.tar.gz from https://github.com/zeromq/libzmq/releases/download/v4.2.2/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   607    0   607    0     0    598      0 --:--:--  0:00:01 --:--:--   599
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Connection timed out after 10002 milliseconds
Fetching zeromq-4.2.2.tar.gz from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [/home/c32/bitcoin/depends/sources/download-stamps/.stamp_fetched-zeromq-zeromq-4.2.2.tar.gz.hash] 错误 22
root@c:/home/c32/bitcoin/depends#

**Comment by fanquake** [comment]
The problem is that zeromq-4.2.2.tar.gz hasn't yet been added to /depends-sources on bitcoincore.org. It should be made available shortly.
