### ISSUE TITLE
warn user if sending an input that costs more to send (fees) than value of input

### ISSUE THREAD

**Issue by julien-lecomte** [bitcoin/bitcoin#11999]
It occurred to me that you can create a transaction where the number of bytes an input adds is valued at less than the fee cost it represents.

Let's say the fees selected are 400 sat/byte, and you add an input with 1200 satoshis but it also adds 4 bytes to the transaction. If this case you should warn the user.

**Comment by jonasschnelli** [comment]
"Warnings" are currently not possible on the RPC layer... only log prints.
This could be indeed implemented in the GUI.

**Comment by jnewbery** [comment]
@julien-lecomte - what's the status of this issue? Are you planning to implement a warning in the GUI?

**Comment by julien-lecomte** [comment]
It was more of a feature suggestion than a proposal from my part to do an implementation.

**Comment by jnewbery** [comment]
ok, since no-one has picked it up in three months, I'll tag it as 'up for grabs' and close it for now (so anyone can come and find it in future and start working on it). Feel free to re-open and comment if you have any further input.
