### ISSUE TITLE
settxfee strange behaviour

### ISSUE THREAD

**Issue by khelle** [bitcoin/bitcoin#11992]
I don't understand how the `settxfee` works exactly. In documentation it is written that it sets the transaction fee per kB, but I dont' see this to be the case.

I am using Bitcoin Core 0.15.1, a do the following steps:

```
bitcoin-cli settxfee 0.003 // returns true
bitcoin-cli sendmany "" { ... } // I give few addresses here to transfer
```

Then the transaction shows on blockchain with following params:
size: 1109 bytes
fee per Byte: 169.071 sat/B

How is it possible? Since I put 0.003 per kB I would expect the "fee per Byte" to be ~ 292 sat/B.

**Comment by morcos** [comment]
If you are sending from segwit inputs then the problem could be the block explorer that should instead be displaying your fees per virtual size.  

See this post: https://medium.com/@murchandamus/psa-wrong-fee-rates-on-block-explorers-48390cbfcc74

If you aren't sending from a segwit address, take a look at your debug log and there should be a line printed that starts with "Fee Calculation:" , this line will provide debugging information to explain how the fee for your transaction was arrived at.

**Comment by khelle** [comment]
This is one the transactions I have sent https://blockexplorer.com/tx/ee35ff8ce356844fc6708be5c07f68b2705fe863e7a134f92a82143ea4b4aeeb

This is not a segwit transaction, and it clearly states that it was sent with 0.002 BTC / kB instead of the 0.003 I have been setting. What's more, every transaction is being sent with a little different ratio! Its not 0.002 always, but it ranges from 0.002-0.004. Its almost as setting the 0.003 set some kind of average fee, not hard restriction.

**Comment by morcos** [comment]
Can you please post the line that starts with "Fee Calculation:" from your debug.log corresponding to this transaction? Or feel free to email me at morcos at chaincode.com.

This line will print to your debug log whenever you send a transaction regardless of your debug settings.

**Comment by jnewbery** [comment]
What's the latest on this? @khelle - did you provide the debug.log line to @morcos ?
