### ISSUE TITLE
CLI parameter for "blocks" dir ( not datadir )

### ISSUE THREAD

**Issue by sleepndevelop** [bitcoin/bitcoin#11998]
Hello,
i am keeping my sensitive wallet data (i.e. wallet.dat) on a Veracrypt drive, so i launch my full node with -datadir=< veracrypt volume here >

But in that same folder Bitcoin Core keeps the "blocks" subdirectory as well.
The problem is that write operations on a Veracrypt volume are extremely slow due to real-time encryption, so the sync is taking ages.

So i may want an additional parameter , say "-blocks-datadir" , to be able to download the blockchain on a non-Veracrypt drive , since the blockchain is not sensitive info, while wallet.dat is.

Are you planning to add such a parameter?
Or do you have other solutions to this?

Thanks

p.s. i have tried creating a folder junction ( hard link) with **mklink /J** ( i am under windows ) , in order to point the "blocks" folder to another drive.
But folder junctions only work with NTFS volumes, and my Veracrypt volume is exFAT.
A solution would be to create a new Veracrypt volume , this time NTFS.

But if there is already a "blocks-datadir" wallet parameter it would be easier for me.
Thanks!

**Comment by sipa** [comment]
Master (and 0.16) will have a -walletdir option.
