### ISSUE TITLE
where is .bitcoin folder on MacOS ?

### ISSUE THREAD

**Issue by shuuchen** [bitcoin/bitcoin#12004]
Hi there,

I am trying to run the bitcoin node on my mac os,  so where is the .bitcoin folder and bitcoin.conf file ?

**Comment by fanquake** [comment]
‘’’
~/Library/Application Support/Bitcoin/
‘’’

**Comment by shuuchen** [comment]
@fanquake 
Thanks!
There are some files, but no .bitcoin folder. Should I create one myself?

```python
$ ls ~/Library/Application\ Support/Bitcoin/
banlist.dat		chainstate		fee_estimates.dat	peers.dat
blocks			debug.log		mempool.dat		wallets
```

**Comment by sipa** [comment]
The directory is only called .bitcoin on Linux. You have found the data directory on OSX.

In the future, please use https://bitcoin.stackexchange.com for support questions.
