### ISSUE TITLE
How to  build wallet app with QT creator on MACOSX

### ISSUE THREAD

**Issue by Leon-Zhang** [bitcoin/bitcoin#12014]
I have followed the build-osx.md, build the project with QT creator, but it only generated bitcoind executable file, which is a command line application without any GUI.
I've been use previous version of bitcoin repository, it has .pro file that could be opened directly by QT creator, and build to a ".app" application which is wallet application with GUI.

I'm using most recent bitcoin repository.

MACOSX high Sierra, QT creator 4.5.0

**Comment by jimhashhq** [comment]
@Leon-Zhang  To build the bitcoin-qt GUI requires passing "--with-gui=yes" argument to both the _autogen.sh_ and _configure_ AutoTools scripts.  Try making this change to step 2 in build-osx.md.
I provided a detailed writeup of my experience building bitcoin on MacOS Sierra build at [bitcointalk.org](https://bitcointalk.org/index.php?topic=2045748.msg20378938#msg20378938), which may be of some use.  Please let me know if this is any help, thank you very much.

**Comment by fanquake** [comment]
@Leon-Zhang Can you expand more on the issue your having? I've just setup a new Qt Creator project for bitcoin-qt using the instructions in the [osx readme](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md):
![screen shot 2](https://user-images.githubusercontent.com/863730/34427383-859c1580-ec7c-11e7-8d00-6b09fe14c65e.png)

Ensure that your build directory is ```path/to/bitcoin/src/qt``` and your executable, in Run configuration, is ```path/to/bitcoin/src/qt/bitcoin-qt```.

@jimhashhq building with the gui enabled is the default, so you shouldn't have to explicitly pass it to configure. Passing ```--with-gui=yes``` to autogen should have no affect.

**Comment by promag** [comment]
Close?

**Comment by wild-jie** [comment]
hey， @fanquake    i can't find the path/to/bitcoin/src/qt/bitcoin-qt, the Qt show ":-1: error: No rule to make target `bitcoin_qt'.  Stop." , can u help me, thanks

**Comment by senevrensel** [comment]
Guys hi . Can someone pls show in a very basic var how to create a GUI Wallet wth QT Creator.
