### ISSUE TITLE
After loading and opening the programme the synchronizing line shows that last sync was almost 9 years ago and it is not loading at all.

### ISSUE THREAD

**Issue by whosda** [bitcoin/bitcoin#12016]
What behavior did you expect? 
Synchronizing

What was the actual behavior 
Not synchronizing at all

<img width="958" alt="screenshot_1" src="https://user-images.githubusercontent.com/25281743/34338911-d888299e-e96d-11e7-86fe-9b975917fb09.png">

**Comment by MarcoFalke** [comment]
Are you connected to the internet? Any useful information in debug.log?

**Comment by krysch** [comment]
I've the same issues, I am 21 weeks behind. Using Bitcoin Core version v0.15.1 (64-bit)
on debian stretch
`$uname -a
Linux  4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux`

And yes I am connected to Internet. 
Ports are open, I get 8 outgoing connections but no incoming.

**Comment by whosda** [comment]
Hi there! I'm glad I solved this problem. I got my keys out of Bitcoin core
simply by using few commands(not really geeky stuff) and put them into
another wallet (I used Electrum).
Here you can find the example
https://github.com/OmniLayer/omniwallet/wiki/Exporting-a-private-key-from-Bitcoin-Qt---Bitcoin-Core-and-importing-to-Omniwallet.org
Good luck to you!

Btw I made a little mistake that after having my money on Electum I
transferred them into Bitcoin wallet on my android and was caught once
again into the same trap cuz this wallet also needs to be synchronized a
little.  Make sure it's synchronized before you transfer money on that
wallet.

Good luck to everybody!

P.S.
Does anyone here a trader? Can anybody help me with starting? Thank you in
advance! My email is vaniaperetrutov99@gmail.com


2017-12-27 19:06 GMT+01:00 krysch <notifications@github.com>:

**Comment by fanquake** [comment]
Given that you've swapped wallets, I'll close this issue.
