### ISSUE TITLE
./configure prefers 'g++' to 'c++'

### ISSUE THREAD

**Issue by janstary** [bitcoin/bitcoin#12017]
This is the current git on OpenBSD current/amd64.
That's a system with clang 5.0.0 as the system compiler.
In fact,  'c++' is 'clang++':

```
$ ls -li /usr/bin/c++ /usr/bin/clang++
32869 -r-xr-xr-x  6 root  bin  42331608 Dec 18 18:55 /usr/bin/c++
32869 -r-xr-xr-x  6 root  bin  42331608 Dec 18 18:55 /usr/bin/clang++
```

It also has the old GCC 4.2.1 (which used to be the system compiler)
installed as `gcc` and `g++`. It seems that `./configure` prefers the name `g++`
before `c++`, and `gcc` before `cc` (which might be yet another of its gnuisms).
That's why `./configure` fails here with

```
checking whether g++ supports C++11 features with -h std=c++11... no
configure: error: *** A compiler with support for C++11 language features is required.
```

but `./configure CC=cc CXX=c++` succeeds.

I find it strange that I have to explicitly specify `CC=cc` and `CXX=c++`.
Shouldn't that be the default, as opposed to `gcc` and `g++`?

**Comment by fanquake** [comment]
See #11984 for the current work in progress changes for OpenBSD 6.2.

**Comment by MarcoFalke** [comment]
Seems to be fixed in current master, no?
