### ISSUE TITLE
Build native GUI clients

### ISSUE THREAD

**Issue by rex4539** [bitcoin/bitcoin#12025]
The current situation with the QT ports is convenient, I can understand, but performance is slooooowwww...

I propose native GUI clients using a modern, fast and cross platform language. I suggest the use of [Swift](https://swift.org/about/#swiftorg-and-open-source).

The result is a modern looking and responsive client with feature parity that runs on Linux, macOS and [Windows](https://github.com/apple/swift/blob/master/docs/Windows.md).

**Comment by sipa** [comment]
Performance has little to do with the UI implementation - Bitcoin Core is just doing a lot of work behind the scenes.

I'm sure improvements to the UI are welcome, but if you want one in a completely separate language, I expect you'll have to implement it yourself.

**Comment by rex4539** [comment]
I would love to implement it myself, if I was a developer.

Instead, I'm a QA Engineer and I volunteer to test it for free.

**Comment by sipa** [comment]
Thanks for the offer, but I expect it to be highly unlikely that someone will be interested in implementing that for you.

If they're capable and have the resources to do so, they probably have their own preferences on how to improve the UI.

**Comment by MarcoFalke** [comment]
Also note that qt is already a cross platform library.

Anyone is welcome to pick this up, but I am going to close the issue, as there is little gain in keeping it open.
