### ISSUE TITLE
dumpprivkey [wrapped witness address]

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#12037]
A friend of mine sent considerable amount of LTC to an exchange, but accidentally to a P2SH over P2WPKH Bitcoin address.  

The exchange operator told him he is using Bitcoin Core and `dumpprivkey [wrapped witness address]` doesn't work and he does not have time to figure out how to fix the user error.  

So I tested and indeed that's the case. I called `getnewaddress` and fed `addwitnessaddress` with its output.   
So the corresponding private key cannot be acquired with `dumpprivkey [wrapped witness address]`.  

What workarounds are there to tackle this issue?

**Comment by achow101** [comment]
Use the address that was fed to `addwitnessaddresss`.

**Comment by fanquake** [comment]
Please ask this in the #bitcoin IRC channel, the bitcoin stack exchange, or even the bitcoin core slack. This issue tracker isn’t for general user support.

**Comment by nopara73** [comment]
@achow101 Is there a simple way to find the address fed to `addwitnessaddress` based on the witness address?  
Bear in mind, the owner of the exchange is "busy" to write a script on his own and he's not going to run the script someone else writes for that.   
We can either find a step by step solution that can be manually typed into RPC, which I suspect doesn't exist, or wait this PR out: https://github.com/bitcoin/bitcoin/pull/11403

**Comment by sipa** [comment]
With #11403 `dumpprivkey` will be able to dump the key for witness addresses.
