### ISSUE TITLE
Hash Graph - Applied to BTC?

### ISSUE THREAD

**Issue by geekdenz** [bitcoin/bitcoin#12034]
Is it possible to make a hard fork of Bitcoin that implements Hash Graph? Is this legal as Hash Graph is proprietary licensed? Even though the license does not agree with open source, the algorithm is open and potentially could be implemented while still giving value to "old" crypto currency tokens and keys.

Bitcoin to scale to billions if not trillions of transactions per second.

It is known that Bitcoin has a scaling problem. 6 transactions per second is not enough to sustain a global economy. Lightning promises to solve this but it's still not implemented fully?!

I transferred a small amount of BTC to Ethereum and it took several days on a small priority.

Just a simple Wallet (Coinomi).

Have installed a full Bitcoin wallet but tried also easier to use implementations such as Jaxx and Coinomi.

I'm happy to do some coding as I am a programmer, but haven't had any notable experience with implementing crypto algorithms before. However, I have plenty of experience implementing algorithms.

No debug log at this time.

**Comment by fanquake** [comment]
Please use the [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev) to discuss proposals like this.
