### ISSUE TITLE
[Feature Request] dumpprivkey [P2SH over P2WPKH]

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#12039]
Following up to the issue: https://github.com/bitcoin/bitcoin/issues/12037

RPC call `dumpprivkey [P2SH over P2WPKH]` does not work. Is there a reason why this not implemented or just nobody worked on it?

**Comment by fanquake** [comment]
This is currently being implemented as part of #11403. See commit https://github.com/bitcoin/bitcoin/pull/11403/commits/4ef27d945e99310e018b0e2a30c85e9620738c5a.

**Comment by nopara73** [comment]
@fanquake Thank you!
