### ISSUE TITLE
GUI not scaling correctly on hi-res / 4k screens

### ISSUE THREAD

**Issue by steevithak** [bitcoin/bitcoin#12031]
When running bitcoin-core on a computer with a high resolution 4k screen, the app opens in a very, very tiny window (about the size of a postage stamp). I'm running on Redhat Fedora GNU/Linux v27. All my other programs including web browsers and native GNOME apps scale properly based on the screen resolution but bitcoin-core does not, so it appears there's a scaling bug of some sort in bitcoin-core's GUI code rather than something wrong with my desktop (but I could be wrong - I'm happy to investigate further if you think this is a problem on my end). 

The app is tiny and very difficult to read without a magnifying glass. Dialogs with entry fields are too small to contain the text that needs to be entered in them. Some dialogs are too small to contain any visible text. Dragging the window bigger unwraps tangled text but the fonts remain microscopically tiny and hard to see.

GUI window is too small to easily use. I'll attach a screenshot if I can figure out how.

Install bitcoin-core on typical laptop or desktop with 4k screen, start it.

v0.15.1.0-g7b5bc998f3 (64-bit) from ringingliberty.com repo

Dell XPS 15 9650, Intel Core i7, 4k screen running Redhat Fedora GNU/Linux v27

In some cases, dragging the windows bigger helps by exposing text which is hidden due to wrapping or going off screen but I don't see any obvious way to scale everything up to human readable size and, in some cases, lines of text overlap each other even if I drag the window bigger.

**Comment by steevithak** [comment]
I can't find any way to attach a screenshot but I can email one if needed.

**Comment by fanquake** [comment]
@steevithak if you email any images to my username @ gmail I’ll add them to your issue.

**Comment by ReneFroger** [comment]
@steevithak you could edit your post.
Then click on the pciture file with the screenshot only.
Drag the screenshot into the message window/edit window. 
Then the screenshot will be added to your message.

**Comment by MarcoFalke** [comment]
Try to attach files by dragging & dropping.

I see some minor issues on hi-res screens, such as this one:

![screenshot from 2017-12-27 08-23-35](https://user-images.githubusercontent.com/6399679/34382855-83567cfa-eadf-11e7-90cf-45ef7e2c4082.png)

**Comment by jonasschnelli** [comment]
Related to #6472.

> v0.15.1.0-g7b5bc998f3 (64-bit) from ringingliberty.com repo

Can you tell us what Qt versions it is compiled against (check "About Qt")?

**Comment by hebasto** [comment]
Does #16254 fix this issue?
