### ISSUE TITLE
Bitcoind loses the latest blocks.

### ISSUE THREAD

**Issue by openGLnoob** [bitcoin/bitcoin#12036]
Hi there! 

I've the latest version of Bitcoin-qt (bitcoin.org 0.15.1) and GUI version works fine at least no one issues were not detected. But when bitcoind started or I'm mining that seems to me my bitcoind loses infromation about actual blocks periodicly. Sometimes after that warning:

**2017-12-26 19:42:52 Timeout downloading block 000000000000000000594fca8fc2e2e6f7baff5ac96a10d94f33ae3b0f4e1971 from peer=12, disconnecting**

I lose blockchain for a while, and only sometimes I catch up the last block - the easier way is restart bitcoind. Sometimes when I'm mining in a pool, I get:

**...
Stratum detect new block (actual block)
Stratum detect new block (actual block)
Longpool detect new block (irrelevant block)**

and after that I need restart my bitcoind. Is it could be the reason that my ports is not forwarding and I get an insufficient info from network?

**Comment by Damballahwedo** [comment]
Hi my name jamson I ve been receive so much email you guys I want you to
stop.

**Comment by TheBlueMatt** [comment]
Why was this closed? It looks like a peer stalled your block download and you went to other peers to get it, but this issue should resolve itself unless your network was at fault (ie is really, really, really slow or cuts out for long periods at a time).

**Comment by Damballahwedo** [comment]
Bonjour,
Je viens de signer la pétition "Destitution du President Jovenel Moise pour
Corruption et Politique de doublure." et je souhaitais savoir si vous
voudriez nous aider en ajoutant votre signature.

Notre objectif est d'atteindre 100 signatures et nous avons besoin de plus
de soutiens. Pour en savoir plus et pour signer, c'est ici:

http://chn.ge/2HcKADv

Merci!
Lwa
