### ISSUE TITLE
Raise default datacarriersize to 220 byte or higher

### ISSUE THREAD

**Issue by dexX7** [bitcoin/bitcoin#12033]
To disincentivize the use of other and more harmful methods to embed data into the chain, in particular via P2SH, the default datacarriersize should be raised from 82 byte to 220 byte, so it becomes the "cheapest" way of embedding data into the chain.

The following graph shows the relation between transaction sizes and payload sizes:

![](http://i.imgur.com/VAGZWBK.png)

Embedding data with bare-multisig and P2SH can be cheaper in terms of effective transaction size, compared to OP_RETURN with a payload limit of 80 byte. Both methods of embedding data, via bare-multisig and P2SH, were heavily used by the major two meta-protocols on top of Bitcoin: Omni and Counterparty (see [here](https://github.com/OmniLayer/spec#class-b-transactions-also-known-as-the-multisig-method) and [here](https://github.com/CounterpartyXCP/cips/blob/master/cip-0006.md)), but both protocols started to use OP_RETRUN data embedding for a long time.

However, currently token sends are done one by one, each with a single transaction, and this is a heavy burden for the whole network, e.g. when an exchange sends out withdrawals.

We have solutions for "multi-sends with multi-inputs" and considered moving destinations into the payload for token sends, but we need more space, otherwise this solution is limited to very few recipients.

I therefore propose to raise the default datacarriersize to 220 byte or higher and I'd be happy to provide a pull request doing so, if this gets positive feedback.

**Comment by jonasschnelli** [comment]
I guess this is a policy (IsStandard) discussion and maybe therefore something we can discuss here on GitHub. But, because it affects other network participants, I recommend to take this to the bitcoin-dev@ mailing list.

Some history:
#5286
#3737
#2738

**Comment by dexX7** [comment]
Counterparty is going to use P2SH soon due to their need for more space for batched payments, see:

https://github.com/CounterpartyXCP/cips/blob/master/cip-0006.md
https://github.com/chiguireitor/cips/blob/cip10/cip-0010.md

As announced in their latest [blog post](https://counterparty.io/news/counterparty-newsletter-01-10-2018/).

**Comment by MarcoFalke** [comment]
Agree with Jonas that this needs discussion on the mailing list first.

**Comment by dexX7** [comment]
Hi @MarcoFalke, do you think it's worth the time to discuss this any further on the ML?
