### ISSUE TITLE
Enable the ability to view a signed transaction in the wallet UI (in hex format) prior to sending

### ISSUE THREAD

**Issue by crbx** [bitcoin/bitcoin#12044]
It would be extremely useful to be able to view or save a signed transaction generated via the Send UI, in hex format.  While it is possible to generate and sign a raw transaction manually via the command line, using the wallet UI is much simpler and less error prone.

This would be particularly helpful for users who are looking to trade airdrop coins back to BTC.  Forks are derived from Bitcoin Core, however it's not possible to trust the forked code.  So it would be great to be able to generate signed transactions from a permanently offline box running the forked version of Bitcoin Core.  (Then the transaction can be copied to an online box and sent to the network via any web gateway, e.g.: https://bitcointalk.org/index.php?topic=1938621.0)  Having this feature in Bitcoin Core would mean that future forks would include the new UI.

Additionally, this functionality will be useful even just for Bitcoin Core.  It would be nice to be able to fully compose and sign a transaction in the UI without having to be on the network.

A little button to show the signed transaction in the Send confirmation dialog would be sufficient to implement this feature.  (I'm assuming it's possible to get to the Send UI when the wallet is offline.)

Looking into the code in SendCoinsDialog.ccp, it's not immediately clear to me where signing occurs.  Perhaps it happens in prepareTransaction?
https://github.com/bitcoin/bitcoin/blob/master/src/qt/sendcoinsdialog.cpp#L263
...or later on in sendCoins?
https://github.com/bitcoin/bitcoin/blob/master/src/qt/sendcoinsdialog.cpp#L363

**Comment by achow101** [comment]
You can get the raw transaction hex by going to the transactions list, right clicking a transaction, and choosing "Copy raw transaction" (or something like that).

**Comment by crbx** [comment]
Oh that's great, thanks!  I'll give that a try.  I assume it's possible to get a transaction sent out while being offline.

Having to "send" the transaction unnecessary / annoying, but it doesn't matter in any case since the box is permanently offline.  Still, having the ability to view the signed transaction without having to actually send it would be nice, though I guess not absolutely necessary.

**Comment by MarcoFalke** [comment]
Also, note that there is a command line option to disable tx broadcast. Try
bitcoin-qt -help

**Comment by crbx** [comment]
Ok, thanks.  I think that should be:
bitcoin-qt -walletbroadcast=0

**Comment by MarcoFalke** [comment]
I think this can be closed, now.
