### ISSUE TITLE
Unable to compile 0.15 on Cygwin (strerror_r was not declared)

### ISSUE THREAD

**Issue by ZeroGraviti** [bitcoin/bitcoin#12049]
_Issue Description:_ Unable to compile and build bitcoin 0.15

_Expected behavior_: Successful build :)

_Actual Behavior:_ Build breaks -> ~~https://pastebin.com/GYZtKBNC~~
Update #1: https://pastebin.com/9Svrbn8g

_Triage/Reproduce the issue:_ https://pastebin.com/UcWnt8dc

_Version of bittcoin core:_ 0.15 (downloaded from github)

_Type of machine on which issue occured:_
`$ uname -a
CYGWIN_NT-6.1-WOW pluto 2.9.0(0.318/5/3) 2017-09-12 10:41 i686 Cygwin`

**_Extra information/updates_**
SO question I have created on this -> https://stackoverflow.com/questions/48008080/c-compilation-stuck-with-boost-interprocess-lib-error-ftruncate-has-not/48008425?noredirect=1#comment83027051_48008425

Latest config.log -> https://pastebin.com/1q4hzeqD
Latest error console output -> https://pastebin.com/9Svrbn8g

**Comment by laanwj** [comment]
As far as I know, no one is building this on cygwin. You're free to try, but if you want to build for windows, you'll save yourself a lot of pain by following the windows build instructions in https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md.

**Comment by ZeroGraviti** [comment]
I dont have Windows 10 and I did try MinGW.... with no success at all. The only shot I have of some success is with cygwin and I believe I did make some progress... Will update OP with this.

**Comment by ZeroGraviti** [comment]
I have pastebin'ed the latest config.log link in the OP....

**Comment by molxyz** [comment]
@ZeroGraviti  On which OS are you trying to do this?

**Comment by DATSEC** [comment]
@ZeroGraviti 
You can compile on any OS, the main thing is to work on a virtualbox
https://github.com/bitcoin/bitcoin/blob/0.15/doc/gitian-building.md

**Comment by VermillionAzure** [comment]
@DATSEC @molxyz @laanwj The compilation is because `<string.h>` which contains `strerror_r()` is not being declared in the scope in which it is used in `netbase.cpp`. So, it's not being included somewhere, or perhaps it just isn't there within Cygwin. However, I believe it's under the `newlib` source files in Cygwin which implement the `strerror_r()` function.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
