### ISSUE TITLE
I send 0.00120997 and 0.0010492 BTC from a wallet to other and it still unconfirmed for more than 25 days !

### ISSUE THREAD

**Issue by statory** [bitcoin/bitcoin#12053]
Hi 
I send 0.00120997 and 0.0010492 BTC from blockchain a wallet to other and it still unconfirmed for more than 25 days !
tx
https://blockchain.info/tx/4926ba739290455244e6c4a81aecd6227929f070913b560471eec0d0c8ccf680

tx
https://blockchain.info/tx/72e4ac4de7ca30c4425bc80a860b55930a6e0f30a5f2786abf845b7ece773817

can anyone help me?

**Comment by fanquake** [comment]
Please don't use GitHub for general bitcoin help/support issues. Try #bitcoin on Freenode, or the bitcoincore slack channel.

**Comment by heri99** [comment]
Same goes to me
