### ISSUE TITLE
0 block reward at height 501726

### ISSUE THREAD

**Issue by EasonWang01** [bitcoin/bitcoin#12057]
Hi,I was wondering why this block has an 0 reward and -12.5 transaction fee.
 https://blockchain.info/block/0000000000000000004b27f9ee7ba33d6f048f684aaeb0eea4befd80f1701126

But 501728 also got only one transaction but with 12.5 reward?

https://blockchain.info/block/00000000000000000013460c16ffa09553e9739aebbd467d7bf34284f2dd5134

**Comment by sipa** [comment]
It doesn't have -12.5 BTC fee. The miner simply forgot to claim the subsidy it was allowed to.

**Comment by EasonWang01** [comment]
Thanks for reply,but what's means forgot to claim the subsidy?
