### ISSUE TITLE
[Tests] Missing test case for SIGHASH_SINGLE|SIGHASH_ANYONECANPAY

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#12060]
I recently found a consensus bug in NBitcoin script interpreter. (https://github.com/MetacoSA/NBitcoin/commit/7fd1c358b920fdc6c75417f9f2646f2fc0f59585)

It was caused by an out of bound signature with SIGHASH_SINGLE|SIGHASH_ANYONECANPAY recently mined on testnet.

My test cases for the script evaluator are using the same, fairly recent (maybe 1 year ago ?) json test cases of Bitcoin Core, and it failed to catch this bug. So I guess this test is missing from Core as well. (I still need to confirm that)

I wrote this test meanwhile in NBitcoin https://github.com/MetacoSA/NBitcoin/blob/7fd1c358b920fdc6c75417f9f2646f2fc0f59585/NBitcoin.Tests/script_tests.cs#L785 

I plan to add test case to bitcoin core for it as well (in `script_valid.json` which I don't find anymore), but I just don't have time for now, so I am opening issue meanwhile.

**Comment by practicalswift** [comment]
Nice find!

**Comment by Christewart** [comment]
It appears I have the same bug in bitcoin-s, so I took the time to update tx_valid.json to add the test case you have linked in NBitcoin.

**Comment by NicolasDorier** [comment]
@Christewart where did you got the bug from? I thought I got the bug from bitcoin core, but core does not have such bug since the beginning... Maybe I got this code from BitcoinJ?

**Comment by Christewart** [comment]
@NicolasDorier I used bitcoinj for my first pass at implementing signature serialization inside of bitcoin-s. I actually have bitcoinj comments inside the bitcoin-s code to help with my implementation. I would guess that bitcoinj probably has this error too -- but I haven't checked with them. 

https://github.com/bitcoin-s/bitcoin-s-core/blob/master/src/main/scala/org/bitcoins/core/crypto/TransactionSignatureSerializer.scala#L33

**Comment by NicolasDorier** [comment]
It seems they don't have this bug now. I probably got it from BitcoinJ initially though.

**Comment by Christewart** [comment]
I believe this can be closed now?
