### ISSUE TITLE
WTF???

### ISSUE THREAD

**Issue by newbusinessman1** [bitcoin/bitcoin#12085]
<img width="1296" alt="2018-01-04 3 15 28" src="https://user-images.githubusercontent.com/35088086/34549057-bc94cbf6-f0fd-11e7-8766-2d939f6361f2.png">

**Comment by jonasschnelli** [comment]
Closing. Lack of explanation.

**Comment by TheBlueMatt** [comment]
Transaction was confirmed. Either a bug in blockchain.info or you didn't wait for the tx to propagate.
