### ISSUE TITLE
`hdMasterKey` and hd`MasterKeyId` do not actually refer to the BIP 32 Master Key

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#12084]
The actual BIP 32 master key in a wallet (the key which every key is derived from) is not actually the same key that is reported as being the BIP 32 master key by basically everything in the wallet that reports it.

Instead the key that is reported as being the BIP 32 master key is actually the seed. This seed is hashed according to the BIP 32 specification to become the BIP 32 master key which everything else is then derived from.

A number of things are wrongly reported and named because of this:
* `hdmasterkeyid` in `validateaddress` and `getwalletinfo`
* The key marked as `hdmaster` with keypath `m` in the `dumpwallet` output
* The extended private masterkey in `dumpwallet` output is the actual master private key and has a different id than `hdmasterkeyid` used elsewhere
* Almost all uses of `masterkey` and `masterkeyid` in the wallet code refer to the seed rather than the actual masterkey.

While this discrepancy does not currently affect usage, it could in the future with possible master key importing or seed importing. With the way that things are currently named, it would be confusing as to whether an import worked properly.

***

I found this while implementing BIP 174 and it totally derailed me for 3 hours since it needs the actual master key id

**Comment by jonasschnelli** [comment]
Yes. This is correct. It should probably have been named `hdseed`.
I guess the user visible forms of the master key should be in the base58check representation (`xpriv`) of the extend private master key.

* One step would be to rename `hdmaster` to `hdseed` (for legacy reasons and to identify key relations), same for `hdmasterkeyid` (to `hdseedid`)
* Another step would be to add `hdextmaster` where we could use the base58check encoding of the extended master key

**Comment by MarcoFalke** [comment]
Related: #8684

**Comment by jonasschnelli** [comment]
Closing (fixed with #12924)
