### ISSUE TITLE
bech32.cpp why use global variables CHARSET_REV and CHARSET

### ISSUE THREAD

**Issue by waterfok** [bitcoin/bitcoin#12105]
Why not make them local to reduce/optimize ram and speed?

**Comment by sipa** [comment]
They're static constant variables already. Making them local won't change anything (and if you'd make them non-const, they may even end up occupying stack space).

**Comment by Optimizingroman** [comment]
they are not static

**Comment by Optimizingroman** [comment]
its not static

**Comment by sipa** [comment]
they're in an anonymous namespace. that has the same effect as static
