### ISSUE TITLE
UI Request: Bitcoin Core TestNet Icon

### ISSUE THREAD

**Issue by 6hundred** [bitcoin/bitcoin#12107]
When we run bitcoin core on testnet the tray Icon on MacOs appears green.. which almost gave me a feeling if I'm running Bitcoin Cash Node. Is there a possibility that color scheme for testnet instances can be changed to something else. Its just cosmetic. 

Best
6hundred #

**Comment by MarcoFalke** [comment]
> Its just cosmetic.

Closing, since we don't keep issues open for gui-only feature request, especially if they are low priority compared to real issues.
