### ISSUE TITLE
Mempool not loading on node restart

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12106]
Running v0.15.1 (64-bit) officially distributed download of Bitcoin Core from bitcoin.org on Fedora 23.

When restarting bitcoin-qt the mempool is not observed to be loading.

Data paths are all default.

Have tried manually setting -persistmempool=1 on the command line and in the conf file. (command-line options says it is defaulted to =1 anyway).. Makes no observable difference.

**Comment by sipa** [comment]
You're aware that loading of the dumped mempool can take several minutes, and happens in the background while the node is up an running?

**Comment by Willtech** [comment]
Yes, after waiting several minutes the debug window shows only a few thousand transactions of the many tens-of-thousands of transactions that were previously. TBH I haven't tried restarting the node with network connectivity off but after a few hours it still has not recovered to the previous level.

**Comment by sipa** [comment]
Here is what appears in my `debug.log` in a shutdown/restart cycle:

    2018-01-07 09:31:00.501333 Dumped mempool: 0.114326s to copy, 1.2187s to dump
    ...
    2018-01-07 09:39:00.939411 Imported mempool transactions from disk: 63982 succeeded, 225 failed, 0 expired, 481 already there

Do you see something similar?

**Comment by MarcoFalke** [comment]
Note that shutting off while the mempool is loading will discard any transaction that are planned to be imported.

**Comment by Willtech** [comment]
In debug.log I can easily find:
`2018-01-07 09:47:30 Dumped mempool: 0.144742s to copy, 3.00402s to dump`

But no message Imported mempool ... after the restart. Waited more than 10 minutes.

**Comment by Willtech** [comment]
Okay, I found it. It must have been really slow before I shifted swap to SSD. Took 1 hour 32 minutes this time. In the past, after hours the mempool had only recovered to a fraction of its previous level, and I am only just getting around to reporting this and it works.

`2018-01-07 11:19:05 Imported mempool transactions from disk: 58898 successes, 2607 failed, 3 expired`
