### ISSUE TITLE
RemovePrunedFunds / ImportPrunedFunds with multiple wallet outputs

### ISSUE THREAD

**Issue by AdvancedStyle** [bitcoin/bitcoin#12115]
**Case:**

You have a transaction which has multiple outputs to different addresses in your own wallet (let's say 2 for example).  One of the output has already been spent, and the other is unspent.

The problem is that if you import this transaction into your wallet using ImportPrunedFunds it will add both the unspent and spent amounts to your listunspent.

And if you use RemovePrunedFunds it will remove both the unspent and spent amounts.

**Suggested Handling**

RemovePrunedFunds / ImportPrunedFunds should accept an additional optional vout parameter, so that you can specify exactly which vout you want to add or remove as a UTXO

**Comment by MarcoFalke** [comment]
According to the documentation, "The end-user is responsible to import additional transactions that subsequently spend the imported outputs or rescan after the point in the blockchain the transaction is included."

Imo, this can be closed.

**Comment by AdvancedStyle** [comment]
In my case that would be manually importing 1000s of transactions in order to correct it all the way up the chain.

A way to only import specific vouts from the import transaction would be much easier.

**Comment by TheBlueMatt** [comment]
If you're manually watching which outputs are available you can probably also manually select outpouts to spend from when creating a transaction. As @MarcoFalke points out, the "correct" solution is to import all the transactions the wallet needs to know the current state of things. How are you exporting transactions to give to the pruned node? If you're using another Core daemon it may be useful to consider adding an RPC which, when provided with a set of output scripts in the wallet, provides all the transactions it knows how to export to make it easier to get all the available transactions.

**Comment by AdvancedStyle** [comment]
How are you exporting transactions to give to the pruned node?
https://chainquery.com/bitcoin-api/gettxoutproof

In my case there are only a few transactions to import, so can be done manually by grabbing the rawtx and gettxoutproof from chainquery. 

Situation is this:
After 100000s of transactions the bitcoin core wallet starts to respond extremely slowly (once wallet.dat is over 500-600MB.  A workable solution is to dump the private keys, destroy the wallet and then re-import the private keys (basically erasing the history)....wallet then start responding quickly as normal.

However there are then some large older transactions which need to be re-imported.

There are 1000s of transactions after the older transactions, so re-importing all these would, as you said, require creating a script to do this and building some kind of import dump.

Rescan would defeat the purpose because wallet would have all the history again and would slow down.

The only feasible solution was to manually re-spend all the older transactions to put them back into the current view, but this is a poor solution.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
