### ISSUE TITLE
How to spend from a segwit address in Bitcoin Core?

### ISSUE THREAD

**Issue by jonjonez** [bitcoin/bitcoin#12117]
And if I can no longer spend the balance of a segwit address on the bitcoin core, let's say the database corrupts and I do not want to wait for the wallet to sync until the core bitcoin recognizes the segwit rule turned on August 21 (was that date even? ), how can I export the private key and redem script of the segwit address in another wallet or create a raw transaction using this information? Or I can only spend from a segwit address created in bitcoin core and I can only spend it on bitcoin core?

**Comment by sipa** [comment]
This is not a support forum. I suggest you take this question to https://bitcoin.stackexchange.com where it's easier to find for others.
