### ISSUE TITLE
When another MAC OSX Open:Library not loaded: @loader_path/libboost_system-mt.dylib

### ISSUE THREAD

**Issue by caokun8341** [bitcoin/bitcoin#12126]
When make deploy generate Bitcoin-Qt.dmg local machine open and use ok,Then I sent the dmg file to another  mac osx machine ,It can open the dmg and install, but can not open the bitcoin-qt.app,
it report error:
"Bitcoin-Qt" could not be opened because of a problem.
Please contact the developer to make sure that "Bitcoin-Qt" works with this macOS version. You may need to reinstall the application. Be sure to install any available updates for this application and macOS.
Click on "Report" to see more detailed information and send the report to Apple
When click the "Report" button,find the description about the problem:
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Bitcoin-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

I  expect the dmg which make by my osx machine can give others mac osx machine to use like my machine.

I can send the dmg to everyone if you give me a email,thanks.

The bitcoin version what i used is 0.14.

My local machine osx 10.13.2/cpu 64bit intel can run ok  
Another can not run osx 10.12.6 /cpu 64bit intel

**Comment by Tach-Yon** [comment]
Encountering the same issue.

**Comment by jonasschnelli** [comment]
* Can you tell us if you have self compiled that version or if you have installed it via a package-manager like Homebrew?

* Have you tried the "official" binaries: http://bitcoincore.org/bin/?

* Do you get the same result with 0.15.1?

**Comment by Tach-Yon** [comment]
@jonasschnelli It was compiled on a Litecoin, this seems to be an issue related to Mac OS X using Clang++ compiler and fucking up the linking to dependencies (read this on another GitHub issue).

**Comment by jonasschnelli** [comment]
If you want to compile binaries that you can switch from system A to system B, try using the /depends compile system (https://github.com/bitcoin/bitcoin/tree/master/depends) or use the "official" binaries.
Closing.

**Comment by chaiyu2002** [comment]
I encountered the same problem. It seemed that something were wrong with boost library. libboost_thread-mt.dylib referenced the libboost_system-mt.dylib, but the path is "@loader_path", and by now the last library did not copied into the Framework folder. I modified the deploy file (which is at contrib/macdeploy/macdeployqtplus) roughly, copy the library into the Framework folder, and change the linkage reference before packing dmg, and it worked fine.
" os.system("cp libboost_system-mt.dylib dist/xxx.app/Contents/Frameworks/")                                                                                                                
  os.system("install_name_tool -change @loader_path/libboost_system-mt.dylib @executable_path/../Frameworks/libboost_system-mt.dylib dist/xxx.app/Contents/Frameworks/libboost_chrono-mt.dylib")".

**Comment by JiaTaoXie** [comment]
@chaiyu2002 Hello,I encountered the same problem,can you show the detail of macdeployqtplus file you changed?Thanks.

**Comment by brakmic** [comment]
Hi @JiaTaoXie ,

In our project I changed the *macdeployqtplus* file this way: https://github.com/Actinium-project/Actinium/commit/a4ef58a2d9a8fac7dd519600506724743f01e54b

Don't forget to put *libboost_system-mt.dylib* into contrib/Frameworks folder so it can later be copied into the DMG.

Regards,
