### ISSUE TITLE
Implement Confidential Transactions/Bulletproofs

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#12129]
Following up on the issue: [Improve transaction privacy / fungibility in Bitcoin Core and the Bitcoin system](https://github.com/bitcoin/bitcoin/issues/6568), this issue may serve as feature request, meta tracking and consensus builder thread on Confidential Transactions/[Bulletproofs](https://eprint.iacr.org/2017/1066.pdf).

  [Privacy](https://en.wikipedia.org/wiki/Privacy) is a fundamental human right and [fungibility](https://en.wikipedia.org/wiki/Fungibility) is an essential property of good money. Our lack of ability of masking transaction output amounts is the [root of all evil](https://github.com/nopara73/ZeroLink/#transactions-and-transaction-chains) in every Bitcoin privacy scheme, where Confidential Transactions/Bulletproofs tackles this issue.  

  While the development and research on Confidential Transactions [may or may not be](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-December/015346.html) in early stages, it is not too early to explore how much support and opposition the development community has on this [soft fork](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-January/012194.html).

**Comment by sipa** [comment]
I don't believe this is the right place to discuss this.

**Comment by nopara73** [comment]
@sipa I believe it is. Historically all soft forks started by a PR to this repository. If a PR gets merged or not is determined by the consensus of the contributors here. Thus, seeking feedback on other platforms, like the mailing list, is less effective to measure the general sentiment of the contributors of this sub towards CT, this is the best place.

**Comment by sipa** [comment]
@nopara73 I couldn't disagree more with that sentiment. A PR to Core is the last step.  And in this case there isn't even a clear proposal yet, much less an implementation.

I'm going to close this. One software implementation's issue tracker isn't place to discuss what Bitcoin can adopt.

**Comment by nopara73** [comment]
> That hasn't been the case for years.

There was only a few occasions when a proposal ended up having adoption without Bitcoin Core PR. The disastrous forks, like BCH, and UASF, which we have never seen its direct outcome.  

> It mostly depends on confidence the ecosystem will adopt a change.

Opening an issue here is part of exploring the confidence you are talking about.  

> That may be the case for implementation details, but there isn't even a vague proposal for how this would work.

That may be the case, however the issues secion of this repository is full of feature requests and meta threads, I don't see why this case is different, in fact the very first link in my first comment is such kind (labelled with `brainstorming`), and that even links to similar ones.

**Comment by sipa** [comment]
> There was only a few occasions when a proposal ended up having adoption without Bitcoin Core PR.

That's not the point. Of course at some point there will be a PR; if the network adopts CT, I'm sure Core will implement it.

You're however claiming that a PR to Core is how soft fork proposals start. I think that's both not historically true, nor advisable.

**Comment by ntom** [comment]
Personally i find github a much better medium to read these kinds of proposals and discussions than mailing list, which has a shit format to read on the web and irc, wherever the logs for that are. I want to see CT on bitcoin, bitcoin right now is like the twitter of finance, literally no privacy at all. Terrible. I think this kind of upgrade is really important.

**Comment by manginahunter** [comment]
In short you wait there is demand for it before PR it here ? So if BTC is invaded by statist nobody will ask for such features... Are you aware of the recent Bitfury research ? Well they publish it publicly good on them. But that's quite scary no ? That kind of change will be probably UASF'ed for obvious reasons that some entities find quite interesting to track you satoshi by satoshi.

**Comment by nopara73** [comment]
@manginahunter I am aware I am dangerously going into off topic territory here, but let me share some thoughts about the Bitfury research:  

From a technical point of view the [Bitfury research](http://bitfury.com/content/5-white-papers-research/clustering_whitepaper.pdf) was especially uninteresting. It didn't add anything new to the privacy conversation, that wasn't already known. I agree, that it was misleading, because 1. it was conducted by a well-known company and 2. they used a language that implies they came up with new, previously unknown things. I've even heard someone having the takeaway from that Bitfury invented clustering.  
For a better quality research on the same topic, see the paper: [When the cookie meets the blockchain: Privacy risks of web payments via cryptocurrencies](https://arxiv.org/pdf/1708.04748.pdf).

With that said , what was especially worrisome about it, is that Bitfury actually plans to utilize the methods. However they don't have an edge on present day Blockchain analysis companies, because they may don't write research on their methods, they know all the basic things the Bitfury paper talks about, and they have already been collecting various metadata (like Bloom filters) for years now.  

In the end, it all comes down to sales. Having home grown research papers gives Bitfury credibility and opportunities, so they claim their expertise on a specific domain.

**Comment by manginahunter** [comment]
Just read about your analysis on your link above. That's reassuring but still think the more privacy tools the better.

**Comment by nopara73** [comment]
@jnewbery Consider it as feature request.

**Comment by TheBlueMatt** [comment]
Yes, can we just close this? I think should generally avoid opening issues with medium-/long-term feature requests, as we generally lose track of them and they just end up open for years. Also, consensus-level discussion doesn't belong on this repo. If you want to use GitHub to access bitcoin-dev, you could build a wrapper that converts emails to GitHub posts and back.

**Comment by MarcoFalke** [comment]
The discussion seems to derail into a meta discussion about tracker issues. Going to close for now
