### ISSUE TITLE
Reorganize Bitcoin Core directory structure for easier database management

### ISSUE THREAD

**Issue by Ulmo** [bitcoin/bitcoin#12145]
I suspect that the subdirectory blocks/index is accessed more frequently and does better on a fast local disk even if the rest of the blocks subdirectory is on a slower disk.  The symlinks required for that are a bit obscene from a maintenance perspective, so I'd like you to reorganize the subdirectories of Bitcoin to unnest the more frequently accessed files directories from the less frequently accessed larger things, i.e., either move blocks/index into index (e.g., ~/.bitcoin/index rather than ~/.bitcoin/blocks/index), or move blocks/\*.\* into a new subdirectory blocks/data and you can leave blocks/index where it is.  

Less difficulty managing apportionment of large subdirectories and frequently accessed files onto different speed disks

A canonical root-based symlink was required, which can offer difficulties in maintenance in the future.

Oh gosh.  Must you with the extra unnecessary questions?

git as of January 11, 2018.  (git has no manual, so I have no idea which version control system version number.)

Presumably platform independent, but Mac.

P.S., did you know \* is only able to be typed in this Github post with the text \\\*?

**Comment by jsarenik** [comment]
```
$ git --version
git version 2.15.0
```

As far as I know and just proved on Linux with ext4 filesystem (but should be the same on Mac I guess), there is no overhead accessing a particular file in a directory full of thousands of other files. It takes a while to list such a big directory, but for accessing a particular file which name is known (like `index`) there is no need to list the contents of the directory.

I hope that helps.

```
$ mkdir dirs files; seq 999999 | while read a; do mkdir dirs/$a; touch files/$a; done
$ time ls files/ > /dev/null
real	0m 2.71s
user	0m 1.31s
sys	0m 0.59s
lomidrevo:/mnt/yocto/test$ time sh -c "echo test > files/test"
real	0m 0.03s
user	0m 0.00s
sys	0m 0.00s
lomidrevo:/mnt/yocto/test$ time cat files/test
test
real	0m 0.03s
user	0m 0.00s
sys	0m 0.00s
```

**Comment by Willtech** [comment]
@Ulmo If you are interested in git manuals, you can try [Git From The Bottom Up](https://github.com/Willtech/GitRefDocs/blob/master/git.from.bottom.up.pdf) and [Pro Git](https://git-scm.com/book). Enjoy!
