### ISSUE TITLE
I have a Bitcoin Deposit to a Ledger nano and had to rest the wallet and now cant find the address that has the BTC in it on the wallet.  I have the keys and have tried to use Mycelium to recover with no luck.  Is there another  way to retrieve the BTC or add the address to another wallet?  

### ISSUE THREAD

**Issue by bryanste** [bitcoin/bitcoin#12154]

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
