### ISSUE TITLE
Bitcoin core doens't respond

### ISSUE THREAD

**Issue by Jappiecr** [bitcoin/bitcoin#12170]
Hi,

Bitcoin core 0.15.1 get's stuck when I try to open program. Most of the time it goes through the update startup rocess oke and then wehen it starts loading it get's stuck.
I looked in the error.log and this is what it says something like:
2018-01-12 12:08:05 LevelDB read failure: IO error: E:\BT\chainstate\101461.ldb: Can't execute because of an error in I/O-device.

2018-01-12 12:08:05 IO error: E:\BT\chainstate\101461.ldb: Can't execute because of an error in I/O-device.

I have the bitcoin folder on external harddrive. It worked fine a couple of weeks ago when I went to update after a couple of months of not connecting. Everything was updated fine and working properly. Then  I wanted to do a little test and opend an online account on Blockchain and transfered a minimal amount as a test. Test went fine but after that I was no longer able to open my Bitcoin Core wallet because of above descibed error.

Can anybody help?
Thanks in advance!

**Comment by sipa** [comment]
You have an I/O error. This means the operating system is failing to read from your drive.

I'm afraid your harddrive is failing.

**Comment by Jappiecr** [comment]
Thanks for your response! The drive is no older than 4 months! Can it be anything else? Can I try to copy the folder to HD and see if this works?

**Comment by Jappiecr** [comment]
also...I can reach the external drive from my windows expolerer and copy and paste files from here fine!

**Comment by MarcoFalke** [comment]
I'd advise against using an external hard drive, as a loose contact could lead to those errors. C.f. also https://github.com/bitcoin/bitcoin/issues/11569#issuecomment-340078965

**Comment by alphaaurigae** [comment]
It doesent matter how old the drive is, what matters is the IO throughput and its connection bandwidth to the mainboard.
If its a single hdd (not ssd) that might be the bottleneck. https://www.cyberciti.biz/faq/howto-linux-unix-test-disk-performance-with-dd-command/
Anything below 4GB ram, make sure you have 4+ gb swap.
Loading large wallets i recognized ram, swap & cpu may be bottlenecks too, in that order.
Another thing, look at that you use USB 3.0 ports if connected by USB.

I run full nodes with xternal drives on x240 & x260 netbooks, netbooks have a ssd as sys drive and ssd for external bitcoind drive.

**Comment by williamng2112** [comment]
...... really, basically.. regardless what yo do, when yo received the I/O failure error messages....it doesn't mean 100% the PHYSICAL I/O devices have some thing wrong... (because , either the thing can't write into I/O (could be physically gone, or the I/O doesn't let the thing to access, or some thing else in the middle doesn't let the thing to write or access the I/O) so clearly, you need to narrow down... which is which... in your case .. smell like ..right level or permission... good luck
