### ISSUE TITLE
-rescan | single address

### ISSUE THREAD

**Issue by alphaaurigae** [bitcoin/bitcoin#12178]
Dealing with large wallets - would be awesome if one could -rescan just a single address/label instead of the whole wallet address list.

**Comment by jonasschnelli** [comment]
I don't think rescanning a single address would be faster.
Or why would you want to rescan for a single address?
If you just want to check the unspent outputs a utxo set based scan would be much faster.

**Comment by alphaaurigae** [comment]
Its faster eventually - with increased number of wallets rescan slows - could there be other bottlenecks causing this behavior?

**Comment by promag** [comment]
Yes, more addresses, more slow.

**Comment by sipa** [comment]
Almost all of the time for a rescan is spent on deserializing the blocks from disk and hashing. More addresses will likely make things slightly slower, but I expect you'd need 1000s to notice ot.

**Comment by alphaaurigae** [comment]
Thx sipa, that explains a lot to me. Yes indeed, it was about a large stack of addresses.
Ill close the issue as my question has been answered. tyvm
