### ISSUE TITLE
Application crashes when the connected hard disk drive gets disconnected

### ISSUE THREAD

**Issue by DrakonAlpha** [bitcoin/bitcoin#12176]
Application crashes when the connected hard disk drive gets disconnected. Error message would be ok, but crash ist inacceptable.

**Comment by bolekC** [comment]
Any more details? 
Which application crashes? 
What is kept on the hard disk that is disconnected?
Which system you are running?

**Comment by DrakonAlpha** [comment]
I'm sorry for giving so few information. English is difficult for me. ;)
Bitcoin-qt for Windows crashes.
Bitcoin-qt itself runs on the internal disk while the blockchain and all related files run on the external drive.
Is this what you wanted to know?

**Comment by MarcoFalke** [comment]
Similar issue for MacOs: #11569

**Comment by bolekC** [comment]
Just avoid disconnecting the drive or keep all data on internal disk.
Even if it would not crash and just give error message then you might loose data anyway. 
I don't see an easy way to fix it.

**Comment by DrakonAlpha** [comment]
I know this. Thank you. Just one question: Why is it impossible to keep a consistent state while the drive gets disconnected unexpectedly?

**Comment by bolekC** [comment]
If you disconnect unexpectedly then you might be in the middle of write operation and you can get only part of the file written. If that is blockchain files then no problem but if you get corruption on wallet file then have fun.

**Comment by jnewbery** [comment]
Quoting @TheBlueMatt from #11569:

> Bitcoin Core can't handle its datadir dissapearing out from under it well, and there isn't much to be done about that (without implementing some full freeze-the-whole-app-until-its-back logic). It would be nice if we didn't wholesale crash, but you should consider running with -prune on your internal disk instead.

@DrakonAlpha - are you happy to close this issue?

**Comment by DrakonAlpha** [comment]
I'm not happy but I close it anyway. Thanks.
