### ISSUE TITLE
bitcoin-cli estimatesmartfee returns error: {"code":-3,"message":"Expected type number, got string"}

### ISSUE THREAD

**Issue by snitko** [bitcoin/bitcoin#12185]
Running Bitcoin Core version v0.15.1.0-g7b57bc998f (64-bit) on Ubuntu 17.04,
Bitcoin Core RPC client version addrindex-0.10.1

When trying to execute

`$ bitcoin-cli estimatesmartfee 1`
I'm getting:
`error: {"code":-3,"message":"Expected type number, got string"}`

Same goes for any number I put in the end, whether it's 1 or 6 or 50.

Trying to execute the command without that number at all
`bitcoin-cli estimatesmartfee`
Results in the following error message:

`error: {"code":-1,"message":"estimatesmartfee conf_target (\"estimate_mode\")\n\nEstimates the approximate fee per kilobyte needed for a transaction to begin\nconfirmation within conf_target blocks if possible and return the number of blocks\nfor which the estimate is valid. Uses virtual transaction size as defined\nin BIP 141 (witness data is discounted).\n\nArguments:\n1. conf_target     (numeric) Confirmation target in blocks (1 - 1008)\n2. \"estimate_mode\" (string, optional, default=CONSERVATIVE) The fee estimate mode.\n                   Whether to return a more conservative estimate which also satisfies\n                   a longer history. A conservative estimate potentially returns a\n                   higher feerate and is more likely to be sufficient for the desired\n                   target, but is not as responsive to short term drops in the\n                   prevailing fee market.  Must be one of:\n       \"UNSET\" (defaults to CONSERVATIVE)\n       \"ECONOMICAL\"\n       \"CONSERVATIVE\"\n\nResult:\n{\n  \"feerate\" : x.x,     (numeric, optional) estimate fee-per-kilobyte (in BTC)\n  \"errors\": [ str... ] (json array of strings, optional) Errors encountered during processing\n  \"blocks\" : n         (numeric) block number where estimate was found\n}\n\nThe request target will be clamped between 2 and the highest target\nfee estimation is able to return based on how long it has been running.\nAn error is returned if not enough transactions and blocks\nhave been observed to make an estimate for any number of blocks.\n\nExample:\n> bitcoin-cli estimatesmartfee 6\n"}`

**Comment by TheBlueMatt** [comment]
The bitcoin-cli version must match the bitcoind version so it knows how to pass parameters properly. Your versions appear to not match.

**Comment by snitko** [comment]
@TheBlueMatt confirmed, thank you. Resolved the issue.
