### ISSUE TITLE
Debian folder is for 1.4x and does not work for 15.1

### ISSUE THREAD

**Issue by dukeh3** [bitcoin/bitcoin#12186]
The debian file in contrib does not work with latest build. Also if you try to use the latest in debian stable ( build around 15.1 ) fails too. 

Building a nice debian package

The build fails with lost of errors

Every time

15.1 Tag

x86 Debian stable

**Comment by TheBlueMatt** [comment]
I don't see what's 0.14-specific in the contrib/debian scripts. Can you paste the full build log as well as the config.log generated by autotools during the build process?

**Comment by MeshCollider** [comment]
Ping @dukeh3 did you make any progress here? Without more information this should probably just be closed...
