### ISSUE TITLE
[doc] benchmarking.md needs update

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#12199]
A good first issue:

The doc/benchmarking.md hasn't been updated to reflect the new format of the output (and new command line options).

Since a compile of the master branch is needed, the one grabbing this issue might also help with review of  #12197, which adds a warning message to bench.

**Comment by fanquake** [comment]
This is already being done in #12187.

**Comment by MarcoFalke** [comment]
Whoops
