### ISSUE TITLE
bech32-optimized QR codes

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12191]
@sipa said in #11991:

> I haven't looked at the code, but inside QR codes it's advantageous to use uppercase Bech32 (it will result in a smaller QR encoding).

Is that still the case when rendered as URI?

Should amounts be added in a different way?

Would that involve amending BIP-21?

**Comment by sipa** [comment]
Bech32 addresses are valid both in all-lowercase or all-uppercase, so even inside a URI you can use the uppercase version (though the `bitcoin:` locator should remain lowercase).

**Comment by Sjors** [comment]
But wasn't there a more efficient but not BIP-21 compliant way to encode amounts?

**Comment by sipa** [comment]
No clue. All you need to get the better efficiency in QR is sequences of several characters of uppercase+digits in a row. It doesn't require everything to be uppercase.

**Comment by hebasto** [comment]
@sipa 
> No clue. All you need to get the better efficiency in QR is sequences of several characters of uppercase+digits in a row. It doesn't require everything to be uppercase.

That is not the case. For better efficiency with alphanumeric character encoding _all_ symbols _must_ belongs to the set `0`..`9`, `A`..`Z`, `%`, `*`, `+`, `-`, `.`, `/`, `:`.

Ref: https://en.wikipedia.org/wiki/QR_code#Encoding

**Comment by sipa** [comment]
@hebasto My understanding is that QR codes encode a sequence of groups, where each group has a single encoding, and a variable number of characters. As long as there are sufficient numbers of characters to emit a separate group, libqrencode will use it.

**Comment by sipa** [comment]
@hebasto From the wikipedia article:

    Encoding modes can be mixed as needed within a QR symbol. (e.g., a url with a long string of alphanumeric characters )

**Comment by hebasto** [comment]
@sipa TIL, thank you.
