### ISSUE TITLE
Trivial: Update link to MIT license (use HTTPS variant)

### ISSUE THREAD

**Issue by fwolfst** [bitcoin/bitcoin#12190]
Most source files contain the "default" copyright-header (also build by a
script in devtools/copyright_header.py), which points out that the MIT
license can be found in the COPYING file or at
http://www.opensource.org/licenses/mit-license.php.

However, the provided link is

1. using http where it could use https
2. resulting in a permanent (301) redirect (https://opensource.org/licenses/mit-license.php)
anyway.

I guess there are many other non-ssl links in the code base, but lets tackle the easier ones
first.

I originally posted this to the bitcoin-dev mailinglist at
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-January/015495.html
. Unfortunately I got only one feedback, saying I should give it a go on github and pointing out that the bitcoin-dev mailing list ist for protocol discussions. For completeness, I paste the content of my original mail here:

> Hey there
> Most source files contain the "default" copyright-header (also build by a
> script in devtools/copyright_header.py), which points out that the MIT
> license can be found in the COPYING file or at
> http://www.opensource.org/licenses/mit-license.php.
> 
> However, the provided link is 1) using http where it could use https, 2)
> resulting in a redirect (https://opensource.org/licenses/mit-license.php)
> anyway.
> I am strongly in favor of using https where possible (I guess there are
> many other non-ssl links in the code base, but lets tackle the easier ones
> first).
> 
> I propose that I
> 1) create a issue on github,
> 2) `sed -i` the relevant links,
> 3) create a PR on github,
> 4) come back to the mailing list.
> 
> This change would affect a few hundred files I guess.
> 
> A question remaining is this change would require a
> copyright-year-extension (to 2018), too.
> 
> An example header can be seen e.g. here
> https://github.com/bitcoin/bitcoin/blob/a9a49e6e7e8df13d80a6dc3245ce7ef041942e9b/src/consensus/merkle.cpp#L3
> 
> I'd be happy about quick feedback - do not know the culture here, yet.
> 
> Have fun
> Felix

**Comment by MarcoFalke** [comment]
Closing, since we don't keep issues open to keep track of refactoring-wishlists.

**Comment by fwolfst** [comment]
@MarcoFalke I do not understand - is there anything I can/should do? Does that mean you'd prefer a new issue with a new PR or will the PR stay alive and just the issue is closed now?

**Comment by MarcoFalke** [comment]
@fwolfst No action required from your side. Usually we close all issues that do not describe a bug or a feature that is blocking progress on other things. So for example, help requests, questions, standalone features, and refactoring issues (i.e. issues about changing the code but no functionality) are closed.

**Comment by fwolfst** [comment]
Good, thanks for explanation.
