### ISSUE TITLE
More granular net logging

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#12219]
#11583 moved many network logging messages to the `net` category, including the version messages for new connections.

I think this was a good idea in itself, however this means that the only way to get information about connections and abnormal things happening is to enable *all* network logging. This includes every single message and transaction, bogs down performance and fills up the disk quickly.

I'd like a category for just low-traffic network logging.

**Comment by jnewbery** [comment]
I agree, and at the risk of scope creep, It'd be nice to have log levels for all logs (eg CRITICAL, ERROR, WARNING, INFO, DEBUG) and be able to filter logs level for all categories independently.

**Comment by laanwj** [comment]
Yes,  I like that solution, certainly in the long run. Connection/disconnection/misbehavior events could then have INFO priority, while the mish-mash of individual messages would only be logged at DEBUG.
This creates a Cartesian product of category × level, the same as in many other applications that log.
I've proposed it before in an IRC meeting but no one liked it at the time, happy to get some support :)

**Comment by donaloconnor** [comment]
+1

Agreed on the log levels concept. This is pretty standard across my experience. It also makes log viewer programs easy to work with (eg BareTail) by creating filters/colour coded output. This is a bit out of scope of this issue though.

**Comment by laanwj** [comment]
I'm going to close this in favor of adding verbosity levels to logging (#24464). This is a more general solution that can achieve the same goal.

**Comment by jonatack** [comment]
> I'd like a category for just low-traffic network logging.

Agree!
