### ISSUE TITLE
Installation and data directory lock issues

### ISSUE THREAD

**Issue by nQuantPlatforms** [bitcoin/bitcoin#12215]
I'm using Raspbian Stretch and just installed the bitcoin to setup full node using following command
sudo apt-get install bitcoin-qt bitcoind

1. First I was not displayed with start screen to choose location for data directory as mentioned here 
https://bitcoin.org/en/full-node#ubuntu-1610
2. I have mounted FTP drive folder where I want my data directory to be pointed. 
3. So I always have to start bitcoin from terminal with datadir option otherwise it starts downloading into default location and I cant download entire blockchain on my pi sdcard.
4. Unfortunately that doesn't work either. it always errors out saying can not obtain lock may be this and that using it.

Issues:
1. I assume its permission issue, but I can manually create, delete update file in that mounted location so why bitcoin app can not? is there special command it need to start with ? And no there is no other program using it or running that has it locked.

2. What option is requires it to start with to show data directory location screen at start

**Comment by laanwj** [comment]
Leveldb seems a bit finnicky with regard to file system support. It is very likely that ftp-mounted shares do not provide the locking functionality required.

**Comment by laanwj** [comment]
See also #10787, which is another instance of the problem (though on macosx), and #10922 which proposes a partitioning/symlinking scheme to work around issues like this.

**Comment by nQuantPlatforms** [comment]
Thanks, 
1. Tried your solution. I was able to create link for blocks but not for index in mounted ftp
2. So I changed bitcoin code to look for index folder one level up and index problem solved for index folder
3. But bitcoin still has issues to write blocks in ftp location at the link
4. I thought its because linked folder issue.. so I changed code again to accept blockdir as argument to forcefully change block directory but got same issue

debug.log ==> Unable to open file ..../blk0000.dat

Again.. why its so difficult for bitcoin core application to write at ftp location when I can manually create/delete/update files from within the raspberry.

Suggestion: why not add settings in config file to for index, blocks, chainstate locations

**Comment by haydenhab57** [comment]
متشکرم ، بخاطر  لطف و محبت شما ، مشکل من همینه که بلوک ها در سرتاسر لپ تاپ
پراکنده شدن . تصور کن چطور در 500 G  هارد باید تمام فولدر ها رو بگردم ،
روباط نمیشناسید این کار را انجام بده ؟


2018-01-31 3:46 GMT+03:30 nQuantPlatforms <notifications@github.com>:
