### ISSUE TITLE
Bitcoind JSON-RPC is very slow for dumping GetRawTransaction even with a high perf computer.

### ISSUE THREAD

**Issue by Harold-Glitch** [bitcoin/bitcoin#12224]
I'm running a JSON/RPC query program, in mode parallel with 100 Threads dumping GetRawTransaction .
My bitcoin.conf is:

server=1 
txindex=1
dbcache=2048 
rpcworkqueue=128 
rpcthreads=128 
rpctimeout=220

This remains very slow the CPU usage is only 20% the disks 1% (very fast M2 SSDs). This is like there is a lock or a json/rpc serialization. Impossible to go faster. 

Windows 10 - 8700K with 32GB and M2 Samsung 960 SSD

**Comment by laanwj** [comment]
You could try to use REST (see https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md):
> `GET /rest/tx/<TX-HASH>.<bin|hex|json>`
> 
> Given a transaction hash: returns a transaction in binary, hex-encoded binary, or JSON formats.

If you use the binary format, the serialization overhead will be smallest.

**Comment by Harold-Glitch** [comment]
Perfect!
