### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by QubitPi** [bitcoin/bitcoin#12233]
Do we have any plan to release a Java wrapper? It would gain much more popularities from Java communities.

**Comment by knoxcard** [comment]
All you need is something like this....https://github.com/priiduneemre/btcd-cli4j

**Comment by sipa** [comment]
All you need is a JSON-RPC client to talk to `bitcoind`. I'm sure several implementations exist for Java.

**Comment by QubitPi** [comment]
Thank you, @knoxcard , @sipa !
