### ISSUE TITLE
Link no longer works

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#12249]
Get the **Debian 8.x net installe**r
http://cdimage.debian.org/mirror/cdimage/archive/8.5.0/amd64/iso-cd/debian-8.5.0-amd64-netinst.iso

**Comment by fanquake** [comment]
The gitian build setup instructions have been moved to [bitcoin-core/docs](https://github.com/bitcoin-core/docs/). Please open an issue there, or you can submit a PR directly to update the link in the build guide.

**Comment by DATSEC** [comment]
I'm understood, thank you
https://cdimage.debian.org/cdimage/archive/8.10.0/amd64/iso-cd/debian-8.10.0-amd64-netinst.iso
