### ISSUE TITLE
SegWit support for importmulti

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#12253]
It's currently not possible to import (solvable) SegWit addresses (P2SH and native) using `importmulti`. I believe that's a shortcoming we should address before release.

My suggestion would be for P2WPKH (P2SH and native) to be supported without any extra arguments. This means that a P2WPKH address/script with corresponding private or public key should work. For P2SH it means checking if the supplied P2SH address perhaps matches the supplied public key or private key when converted to P2WPKH first.

To support P2WSH, I think we need an extra field "witnessScript". When supplied, it would either be required to match a P2WSH address/script directly, or if the address is P2SH, indirectly.

**Comment by jnewbery** [comment]
I think we can remove the 0.16.0 Milestone from this PR:

```
10:50 < sipa> wumpus: do we want #12253 in 0.16?
10:50 < gribble> https://github.com/bitcoin/bitcoin/issues/12253 | SegWit support for importmulti · Issue #12253 · bitcoin/bitcoin · GitHub
10:51 < wumpus> sipa: if possible, but I think it's getting a bit late for that
10:52 < sipa> i certainly won't have time until next week
10:52 < wumpus> I assume the code still needs to be written, and ofc it will need to go through a review cycle
10:52 < wumpus> right, so I guess that means no
10:53 < wumpus> should probably mention lack of support in importmulti it in the 'known issues' in the release notes
```

(https://botbot.me/freenode/bitcoin-core-dev/2018-01-24/?msg=96111019&page=3)

**Comment by MarcoFalke** [comment]
If this is still not supported, it could make sense to add a note in the rpc help documentation of importmulti.

**Comment by gwillen** [comment]
I'm running into this trying to do stuff with offline signing, which (I'm lead to understand) requires solvability for fundrawtransaction and friends. Sincre everything is segwit now, it seems like there's no way to get a solvable watchonly address anymore.
