### ISSUE TITLE
Error build 0.14 version of windows

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#12263]
**build**
```
Creating build script (var/build-script)
Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:163:in `build_one_configuration'
        from ./bin/gbuild:299:in `block (2 levels) in <main>'
        from ./bin/gbuild:294:in `each'
        from ./bin/gbuild:294:in `block in <main>'
        from ./bin/gbuild:292:in `each'
        from ./bin/gbuild:292:in `<main>'
debian@debian:~/gitian-builder$

```
**log**
```
+ cd ../../
+ rm -rf distsrc-x86_64-w64-mingw32
+ cp -rf contrib/windeploy /home/ubuntu/build
cp: cannot stat ‘contrib/windeploy’: No such file or directory

```

**Comment by VermillionAzure** [comment]
What shell/setup are you using on Windows?

**Comment by bitcoinfuture-btcx** [comment]
Please help
Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:163:in `build_one_configuration'
        from ./bin/gbuild:308:in `block (2 levels) in <main>'
        from ./bin/gbuild:303:in `each'
        from ./bin/gbuild:303:in `block in <main>'
        from ./bin/gbuild:301:in `each'
        from ./bin/gbuild:301:in `<main>'
