### ISSUE TITLE
Makefile:8167

### ISSUE THREAD

**Issue by demeter52** [bitcoin/bitcoin#12272]
When I try to cross compile for Windows on Kubuntu 16.04 I keep getting the following error:

Making all in src
make[1]: Entering directory '/home/zsolti/Dokumentumok/bitcoin/src'
make[2]: Entering directory '/home/zsolti/Dokumentumok/bitcoin/src'
make[3]: Entering directory '/home/zsolti/Dokumentumok/bitcoin'
make[3]: Leaving directory '/home/zsolti/Dokumentumok/bitcoin'
make[3]: Entering directory '/home/zsolti/Dokumentumok/bitcoin/src/secp256k1'
make[3]: Leaving directory '/home/zsolti/Dokumentumok/bitcoin/src/secp256k1'
  CXX      bitcoind-bitcoind.o
Makefile:8167: recipe for target 'bitcoind-bitcoind.o' failed
make[2]: Leaving directory '/home/zsolti/Dokumentumok/bitcoin/src'
Makefile:9419: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/zsolti/Dokumentumok/bitcoin/src'
Makefile:747: recipe for target 'all-recursive' failed

**Comment by MarcoFalke** [comment]
Please provide the commit you are compiling and the exact command line to compile. (If you switch between releases you might have to `./autogen.sh && ./configure` again)

**Comment by demeter52** [comment]
I try to compile the following commit: 
commit 2ae7cf8ef5be67e085abc1b1dc71bc44865a71b3
Merge: 16bac24 bde8bcd
Author: Wladimir J. van der Laan <laanwj@gmail.com>
Date:   Thu Jan 25 19:05:49 2018 +0100

To compile I use the follwing commands (source:https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md):
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make

**Comment by demeter52** [comment]
I've just tried to compile for 32-bit version of Windows and it succeeded without any error, so it seems to me that the error above is related to the bug in the 64 bit Mingw-w64 cross compiler packaged for WSL/Ubuntu Xenial 16.04 .
