### ISSUE TITLE
rodata cannot be recompiled with -fPIC

### ISSUE THREAD

**Issue by Alkaris** [bitcoin/bitcoin#12280]
Trying to compile this from source and I'm hitting this error with

```
.rodata' can not be used when making a shared object; recompile with -fPIC
libbitcoin_consensus.a: error adding symbols: Bad value
```
I run the `./configure --with-incompatible-bdb` and it doesn't have any errors, and I use that `--with-incompatible-bdb` because I have Berkeley DB 5.3, which is higher than the recommended 4.8 version, and it's so much hassle trying to get the previous packages without breaking my linux install.

but anyway I'm not sure what I might be missing which is causing the said error above when I run the `make check` command which produces the following in the error output in Terminal;

```
  CXXLD    bitcoind
/usr/bin/ld: libbitcoin_consensus.a(libbitcoin_consensus_a-cryptonight.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
libbitcoin_consensus.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:3714: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1

```

**Comment by theuni** [comment]
> libbitcoin_consensus_a-cryptonight.o

Closing as not-our-bug.
