### ISSUE TITLE
Socket select error Bad file descriptor (9) after upgrading to master

### ISSUE THREAD

**Issue by Raulo** [bitcoin/bitcoin#12285]
After upgrading to master (9cf6393a4f) from 0.15.1 I get the following errors in debug.log

2018-01-28 11:01:30 socket select error Bad file descriptor (9)
2018-01-28 11:01:30 socket recv error Bad file descriptor (9)

probably after connecting to some of new peers (it's not clear from the log). These errors were not encountered in 0.15.1.

These errors do not seem to impact the operation. I guess other peers work.     

Ubuntu 16.04. GCC  (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519

**Comment by Raulo** [comment]
I'd like to follow up. 

The error has not reappeared even after going back and forth between 0.15.1 and 0.15.99 versions. It seems that the problem was rather caused by problems with reading some old-version files than with peer communication.

Anybody wanting to debug this problem should make a backup of the 0.15.1 data structure because after rewriting the files, the problem is gone. I had the same error appearing after upgrading testnet so backing up testnet might be an easier path.

**Comment by laanwj** [comment]
Thanks for the report. looks like many people have this problem, I've created #12323 to track this issue.

**Comment by gmaxwell** [comment]
I think this can be closed now. Thanks for the report!
