### ISSUE TITLE
QT ignores -changetype=bech32 when coin control features are enabled

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12312]
Steps to reproduce:

1. put `changetype=bech32` in bitcoin.conf or launch QT with `-changetype=bech32`
2. send money to any legacy address
3. use `decoderawtransaction` to see that the change address is `bech32`, as expected since #12119

4. enable Coin Control in settings menu
5. send money to any legacy address
6. use `decoderawtransaction` to see that the change address is now `p2sh-segwit`

**Comment by instagibbs** [comment]
my guess without reading the code is that coin control in QT basically "over-rides" whatever coin control was set to at startup. I wonder how many other settings get wiped too...

**Comment by promag** [comment]
IIUC the problem is the coin control of the dialog is statically instanced and the arguments are not yet processed, submitting a fix.

**Comment by Sjors** [comment]
@jonasschnelli confirmed.
