### ISSUE TITLE
Viruses in the wallet (false)

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#12320]
Sometimes I get scared of wallets that are collected.
Are you checking the packages that you are requesting for installation?
https://www.virustotal.com/ru/file/905a5999fb52b083d7e3bedb2dc6704ca641823f81865db58a55a6a20b454d8c/analysis/

**Comment by fanquake** [comment]
Where did you get `Bitcoin_x64_Rus_Setup.exe`?

**Comment by laanwj** [comment]
That is certainly not a file from our distribution. Make sure you only download from https://bitcoin.org or http://bitcoincore.org, and verify the signatures on the download (SHA256SUMS.asc) before using a download.

**Comment by DATSEC** [comment]
@fanquake @laanwj 
I uploaded it here, please check
https://bitcoin.org/bin/bitcoin-core-0.15.1/

**Comment by laanwj** [comment]
That's interesting. So it seems that bitcoin executables are marked as "riskware" by some AV tools (but not-a-virus)? Maybe due to botnet usage.

**Comment by MarcoFalke** [comment]
Virustotal results are know to be "broken" https://github.com/bitcoin-dot-org/bitcoin.org/issues/1472

**Comment by Willtech** [comment]
It may be worth validating release versions on Virustotal for false positives before release and having any issues resolved.

**Comment by Willtech** [comment]
It would be better to handle this as a part of the release schedule.

@MarcoFalke I would be prepared to do a pre-upload of each release to VT for the team once it is compiled and testing is completed, and leave a comment along the following lines:

    This is the official release vX.X.X of Bitcoin Core for {platform} {architecture} from https://bitcoin.org/en/download where you can check release signatures and review source code.

I would just need to be notified of the final download URL's once the files are pre-staged.

This should help as many AV researchers (and many of those working for the various AV vendor labs) use VT.  At least some AV vendors use notification of detections by other engines, so the details are useful.

**Comment by TheBlueMatt** [comment]
IIRC the issues go away when things get signed, released, and run by many users (some kind of shitty "reputation score", IIRC). Seems not-unreasonable that things which access "wallet.dat" be considered risky by default.

**Comment by Willtech** [comment]
@TheBlueMatt True, the open-source philosophy. Note that the Windows v0.15.1 release seems to be also triggering on generic suspicious behaviour identified: https://www.virustotal.com/#/file/905a5999fb52b083d7e3bedb2dc6704ca641823f81865db58a55a6a20b454d8c/behavior

**Comment by haydenhab57** [comment]
سلام به شما عزیزان . بی نهایت سپاس به خاطر کمک و یاری که به من میکنید و وقت ارزشمندتون را صرف مشکلات من میکنید . ببخشید بخاطر اتفاقی که برایم پیش امد چند روزی در بیمارستان بودم و نشد که به ایمیل هایتان پاسخ دهم  تا چند ساعت دیگر به شما می پیوندم . بای

**Comment by Willtech** [comment]
[Translated](https://translate.google.com/#auto/en/%D8%B3%D9%84%D8%A7%D9%85%20%D8%A8%D9%87%20%D8%B4%D9%85%D8%A7%20%D8%B9%D8%B2%DB%8C%D8%B2%D8%A7%D9%86%20.%20%D8%A8%DB%8C%20%D9%86%D9%87%D8%A7%DB%8C%D8%AA%20%D8%B3%D9%BE%D8%A7%D8%B3%20%D8%A8%D9%87%20%D8%AE%D8%A7%D8%B7%D8%B1%20%DA%A9%D9%85%DA%A9%20%D9%88%20%DB%8C%D8%A7%D8%B1%DB%8C%20%DA%A9%D9%87%20%D8%A8%D9%87%20%D9%85%D9%86%20%D9%85%DB%8C%DA%A9%D9%86%DB%8C%D8%AF%20%D9%88%20%D9%88%D9%82%D8%AA%20%D8%A7%D8%B1%D8%B2%D8%B4%D9%85%D9%86%D8%AF%D8%AA%D9%88%D9%86%20%D8%B1%D8%A7%20%D8%B5%D8%B1%D9%81%20%D9%85%D8%B4%DA%A9%D9%84%D8%A7%D8%AA%20%D9%85%D9%86%20%D9%85%DB%8C%DA%A9%D9%86%DB%8C%D8%AF%20.%20%D8%A8%D8%A8%D8%AE%D8%B4%DB%8C%D8%AF%20%D8%A8%D8%AE%D8%A7%D8%B7%D8%B1%20%D8%A7%D8%AA%D9%81%D8%A7%D9%82%DB%8C%20%DA%A9%D9%87%20%D8%A8%D8%B1%D8%A7%DB%8C%D9%85%20%D9%BE%DB%8C%D8%B4%20%D8%A7%D9%85%D8%AF%20%DA%86%D9%86%D8%AF%20%D8%B1%D9%88%D8%B2%DB%8C%20%D8%AF%D8%B1%20%D8%A8%DB%8C%D9%85%D8%A7%D8%B1%D8%B3%D8%AA%D8%A7%D9%86%20%D8%A8%D9%88%D8%AF%D9%85%20%D9%88%20%D9%86%D8%B4%D8%AF%20%DA%A9%D9%87%20%D8%A8%D9%87%20%D8%A7%DB%8C%D9%85%DB%8C%D9%84%20%D9%87%D8%A7%DB%8C%D8%AA%D8%A7%D9%86%20%D9%BE%D8%A7%D8%B3%D8%AE%20%D8%AF%D9%87%D9%85%20%D8%AA%D8%A7%20%DA%86%D9%86%D8%AF%20%D8%B3%D8%A7%D8%B9%D8%AA%20%D8%AF%DB%8C%DA%AF%D8%B1%20%D8%A8%D9%87%20%D8%B4%D9%85%D8%A7%20%D9%85%DB%8C%20%D9%BE%DB%8C%D9%88%D9%86%D8%AF%D9%85%20.%20%D8%A8%D8%A7%DB%8C): Hello to you loved ones Thanks so much for helping me and helping you with my valuable time and for your problems. Forgive me for the incident that happened to me a few days in the hospital and I could not respond to your emails until a few more hours. Bye

**Comment by MarcoFalke** [comment]
Apparently, one can submit FPs to http://sd.baidu.com/en/submit-file.php

**Comment by laanwj** [comment]
Closing this, this is not an actionable issue with regard to the source repository, and it seems the OP deleted their account.
