### ISSUE TITLE
coinbaseaux flags is empty and coinbasetx is missing

### ISSUE THREAD

**Issue by nQuantPlatforms** [bitcoin/bitcoin#12335]
When I request getblocktemplate, coinbaseaux flags is empty. Also coinbasetx is not included which I understand need to be calculated. Where is complete example of how to create that one ? Wiki example just assums conbasetx in included in response which is not. I want to create coinbase with all rewards going to single wallet address.

```
{
            "capabilities": ["proposal"],
            "version": 536870912,
            "rules": ["csv",
            "segwit"],
            "vbavailable": {

            },
            "vbrequired": 0,
            "previousblockhash": "00000000000000000011f84134ea90036cf16260ef1e2532af2ad4c4128833fa",
            "transactions": [],
            "coinbaseaux": {
                "flags": ""
            },
            "coinbasevalue": 1390108740,
            "longpollid": "00000000000000000011f84134ea90036cf16260ef1e2532af2ad4c4128833fa6254",
            "target": "0000000000000000006c21460000000000000000000000000000000000000000",
            "mintime": 1517434058,
            "mutable": ["time",
            "transactions",
            "prevblock"],
            "noncerange": "00000000ffffffff",
            "sigoplimit": 80000,
            "sizelimit": 4000000,
            "weightlimit": 4000000,
            "curtime": 1517440540,
            "bits": "176c2146",
            "height": 507012,
            "default_witness_commitment": "6a24aa21a9ed63d9ce8e02cbe0c044825f7448ebd2819c3af1390057183bee668219e159be2a"
    }
```

**Comment by gmaxwell** [comment]
@luke-jr

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by Shortsafe** [comment]
@MarcoFalke This is still an issue with a recent version of bitcoin core. After downloading and setting up a RPC server, 
`bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`
returns the following

> {
  "capabilities": [
    "proposal"
  ],
  "version": 536870912,
  "rules": [
  ],
  "vbavailable": {
  },
  "vbrequired": 0,
  "previousblockhash": "00000000000000000007405bd7419a480881b870b3c97ad7753aade9e7ca67e0",
  "transactions": [],
  "coinbaseaux": {
  },
  "coinbasevalue": 635246221,
  "longpollid": "00000000000000000007405bd7419a480881b870b3c97ad7753aade9e7ca67e053968",
  "target": "000000000000000000103a150000000000000000000000000000000000000000",
  "mintime": 1595809886,
  "mutable": [
    "time",
    "transactions",
    "prevblock"
  ],
  "noncerange": "00000000ffffffff",
  "sigoplimit": 80000,
  "sizelimit": 4000000,
  "weightlimit": 4000000,
  "curtime": 1595812328,
  "bits": "17103a15",
  "height": 640957,
  "default_witness_commitment": "6a24aa21a9ed9cff8c300bbcfb7ff4fe23d3040e3947da3a83ce20f55c02c2ace82e186b3744"
}

**Comment by fcojperez** [comment]
Hi,

I have installed Bitcoin Core version v0.21.0 and it is still an issue. You can reproduce just executing 
bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'

**Comment by luke-jr** [comment]
@fcojperez coinbaseaux/coinbasetx are not required at all; see libblkmaker for an example client.

**Comment by fcojperez** [comment]
Hi @luke-jr 

Thanks for the feedback, your comment helped to understand a possible bug in code that is consuming getblocktemplate JSON

Cheers
P

**Comment by ghostcompute** [comment]
@luke-jr The RPC documentation says the coinbase transaction **scriptSig** should contain the **coinbaseaux** values.

If **getblocktemplate** returned a value for **coinbaseaux**, would it be required? If not, why is **coinbaseaux** included in the response?

The issue is still happening with the latest version, but the value is now an empty object.

"coinbaseaux": {
}

**Comment by luke-jr** [comment]
>If getblocktemplate returned a value for coinbaseaux, would it be required?

It is undefined what behaviour to expect if `coinbaseaux` is ignored, but the spec says any values provided SHOULD be included in the scriptSig.

>The issue is still happening with the latest version, but the value is now an empty object.

It's supposed to be empty.

**Comment by ghostcompute** [comment]
Is there recent documentation for creating coinbase transactions in recent versions, or should I just read the source code?

**Comment by luke-jr** [comment]
BIPs 22, 23, and [the amendment for versionbits](https://github.com/bitcoin/bips/blob/master/bip-0008.mediawiki#getblocktemplate_changes) should be everything IIRC

Nothing has changed in regard to coinbaseaux though

**Comment by ghostcompute** [comment]
Ok I'll circle back to this if there's an invalid coinbase error during block submission.

**Comment by MarcoFalke** [comment]
I am going to lock the conversation on this issue from 2018 (4 years ago). Please open a new thread for any new issues.
