### ISSUE TITLE
Bitcoin malloc() error in OpenBSD 6.2amd64

### ISSUE THREAD

**Issue by amore-amore** [bitcoin/bitcoin#12332]
I have malloc() error(s) in bitcoin 0.13.2 built for OpenBSD 6.2amd64 GENERIC.MP. On previous OpenBSD 6.1amd64 GENERIC.MP bitcoin 0.13.2 works smoothly.

The errors usually occurs every time when Bitcoin started.

OpenBSD developers points on some hidden bugs in memory management used in Bitcoin which float after more strict malloc() was implemented.

------------------------------------------
Here is the error using defalt malloc() settings (no any options were enabled from man(5) malloc.conf): 

bitcoind (2672) malloc():bogus pointer (double free?) 0xdfdfdfdfdfdfdfdf
bitcoind (17411) free(): chunk is already free 0x1bc9981cae20
OR
bitcoind (25876) in free(): double free 0xb4b86701cc0
OR
bitcoind (8031) in free(): chink is already free 0x11577e86bb50
OR
bitcoind (3267) in free(): chink is already free 0x14e5fe642910

------------------------------------------
After enabling 'S' option "Enable all options suitable for security auditing" by the command:

ln -s 'S' /etc/malloc.conf

The error is a bit different, but persistent.
 
bitcoind (2476) in free(): chunk canary corrupted 0x1ad4b3e5b3b0
0x2@0x2 (double free?)

------------------------------------------

I tried to run the bitcoin-0.13.2 with 'j' option "Less junking" the malloc() errors still present.
ln -s 'j' /etc/malloc.conf

I can add some further test conditions and build options for bitcoin on this platform.

**Comment by gmaxwell** [comment]
0.13.2 is significantly outdated and no longer supported.  Can you reproduce these issues with 0.16rc2  or 0.15.1?

**Comment by amore-amore** [comment]
I will try it soon.

**Comment by amore-amore** [comment]
Tried to build bitcoin 15.1 from git sources. The bug with memory management is the same.

While running bitcoind I get this error:

bitcoind(23145) in free(): chunk is already free 0x1392d44e9a90
Abort trap (core dumped)

**Comment by fanquake** [comment]
Closing this in favour of #12576.
