### ISSUE TITLE
failed download

### ISSUE THREAD

**Issue by ALLMINER** [bitcoin/bitcoin#12340]
sudo add-apt-repository ppa:bitcoin/bitcoin
 sudo apt-get update

Ign http://ppa.launchpad.net jessie/main Translation-en_US
Ign http://ppa.launchpad.net jessie/main Translation-en
Fetched 19.8 MB in 6s (3,143 kB/s)
W: Failed to fetch http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
and  

sudo apt-get install libdb4.8-dev libdb4.8++-dev

**Comment by ALLMINER** [comment]
sorry im debian )

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
