### ISSUE TITLE
dumpprivkey and dumpwallet give different adress

### ISSUE THREAD

**Issue by chrotz** [bitcoin/bitcoin#12358]
Windows 10. bitcoin 0.16 rc2

I used receive and ticked  generate bech32 adress

dumpwallet gave me a file with all adresses and privkeys, however the bech32 adress is not visible in there

However when I use dumpprivkey bc1q5qk9vteggs707uukmlywjft9uxcgjkh2vhc0tl  it gives me the privkey which is L3kp5RLGeGx7UF8RDuynfGPW46dNvy8m3AiTSbrxnditXyr22qi3

Searching for "L3kp5RLGeGx7UF8RDuynfGPW46dNvy8m3AiTSbrxnditXyr22qi3" in the dumpwallet file gives me the privkey L3kp5RLGeGx7UF8RDuynfGPW46dNvy8m3AiTSbrxnditXyr22qi3 and the adress  1FbvEFxG1YakxckMVaQPeNS9k7m2LUuo4E

**Comment by sipa** [comment]
Yes, this is expected. `dumpwallet` doesn't know to check for possibly used SegWit addresses, and doesn't list them. This is mentioned in the 0.16 release notes, and will be fixed in a later release.

**Comment by chrotz** [comment]
How can "noob"  that is using 0.16 recover/access his  coins then? There should be a user-friendly tutorial maybe linked from the release notes. Otherwise I would say that this release should be "experimental" or something.

Some users might have a old laptop that  has his wifi antenne/board/bluetooth etc removed and is used as a cold wallet. Generates 1000 adresses and then uses the dumpwallet to make a safe "backup" but might have trouble with recovering. :/

Or would the adresses be recovered if I make a dumpwallet and import it somehow later?

**Comment by sipa** [comment]
@chrotz It's just the comment that is wrong. Dumping/importing will work fine.

**Comment by JayKopinski** [comment]
@sipa with regards to 0.16.0 rc4 after dumping priv key, and importing the import displays legacy P2SH and bech32 addresses. I take it this is normal behaviour?
