### ISSUE TITLE
Add ppa:bitcoin/bitcoin repository on linux problem

### ISSUE THREAD

**Issue by antekotarac** [bitcoin/bitcoin#12365]
After executing:

sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update

I get:

Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by antekotarac** [comment]
I believe there are workarounds for this, but getting this by default looks ugly.

**Comment by MarcoFalke** [comment]
What "linux"?

Please add steps to reproduce

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by antekotarac** [comment]
Ubuntu 18.04 (bionic)
Gnome 3.26.2
Kernel: 4.13.0-25-generic

**Comment by antekotarac** [comment]
This is probably early warning before actual release. It happens to me now.

**Comment by TheBlueMatt** [comment]
This is a launchpad bug, which they seem rather uninterested in fixing. Issue is https://bugs.launchpad.net/launchpad/+bug/1331914

**Comment by MarcoFalke** [comment]
@TheBlueMatt Eh, wat?

Are you implying there won't be any bitcoin core compiles for the ppa after and including 18.04?

**Comment by TheBlueMatt** [comment]
Ah, I misunderstood the error message due to lack of context. @antekotarac the Bitcoin PPA usually does not get builds for pre-release Ubuntu releases until they're close to being released. As its still a few months from Bionic getting released, you may want to wait until its released to install the Bitcoin PPA.

**Comment by antekotarac** [comment]
OK, thanks.
Any way, I see you guys have new core release too huh...
