### ISSUE TITLE
Keyboard shortcut to close window without quitting

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12369]
On MacOS - presumably also other platforms - you can close the current window using `Command + w`.

This doesn't work for QT: you have to click the x.

**Comment by Sjors** [comment]
According to [this](https://bugreports.qt.io/browse/QTBUG-42242) it's a simple matter of adding a "Close Window" menu item. I wonder how that works with i18n.

**Comment by dasilvarosa** [comment]
It would be nice if this shortcut, along with the "Hide Window" would work on the currently active window, instead of all windows. In the current behaviour _Command + h_ hides all windows, even if the debug window or the CLI options window are in focus.

**Comment by Sjors** [comment]
@dasilvarosa good point, even more important once multiple wallets are supported and use one window each (#11383 doesn't do that yet though)

**Comment by jakezeal** [comment]
There is a keyboard shortcut to "hide window" (close without quitting) using `Command + h`. Is that what you are referring to?

**Comment by Sjors** [comment]
I didn't know about `Command + h`. That actually makes more sense in the single wallet situation. In a multi wallet situation `Command + w` should probably unload the wallet, whereas `Command + h` would just hide it but keep it loaded.
