### ISSUE TITLE
Query on bitcoin/doc/tor.md out of date?

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12376]
Using config from [`bitcoin/doc/tor.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md) kills Tor service, will not restart using `sudo systemctl start tor` or upon reboot after first start with new config success on Fedora 23. Bitcoin Core v0.15.1. Tor v0.2.8.11-1.fc23.

I will leave the actual Tor errors/logs for elsewhere or, if necessary.

Question - since the linked document says:
>Starting with Tor version 0.2.7.1 it is possible, through Tor's control socket API, to create and destroy 'ephemeral' hidden services programmatically. Bitcoin Core has been updated to make use of this.

>This means that if Tor is running (and proper authentication has been configured), Bitcoin Core automatically creates a hidden service to listen on. This will positively affect the number of available .onion nodes.

Does that make the following lines for `/etc/tor/torrc` redundant - removing these from `torrc` resolve the Tor issue:

    HiddenServiceDir /var/lib/tor/bitcoin-service/
    HiddenServicePort 8333 127.0.0.1:8333
    HiddenServicePort 18333 127.0.0.1:18333

I note the following lines in my v0.15.1 `debug.log` before the preceeding lines were added, while they were added (before Tor was stopped) and after the lines were removed and Tor was working again - and at the start of the log I get `discover=0`:

    2018-02-07 10:52:58 torcontrol thread start
    2018-02-07 10:52:58 Bound to 127.0.0.1:8333
    2018-02-07 10:52:58 init message: Loading P2P addresses...
    2018-02-07 10:52:58 tor: Got service ID {onion}, advertising service {onion}.onion:8333
    2018-02-07 10:52:58 AddLocal({onion}.onion:8333,4)

Seperately (Yes, no not support questions..) is it also necessary to `-setexternalip=` for Bitcoin Core to your onion service at command line / in `bitcoin.conf`as the linked document suggests, even when using 'ephemeral' hidden service working with `AddLocal` message?

The full setup I am using is [here](https://bitcoin.stackexchange.com/a/70070/75001) - *note that I have additional lines in my `bitcoin.conf`.*

**Comment by laanwj** [comment]
>  Does that make the following lines for /etc/tor/torrc redundant - removing these from torrc resolve the Tor issue.

That creates a tor hidden service manually. Bitcoind can also create a tor hidden service automatically (with `-listenonion`) but those two are not exclusive. Specifying both will not cause an error, it will just result in two hidden services.

> Seperately (Yes, no not support questions..) is it also necessary to -setexternalip= for Bitcoin Core to your onion service at command line / in bitcoin.confas the linked document suggests, even when using 'ephemeral' hidden service working with AddLocal message?

The automatic hidden service will automatically be regarded as local address and thus gossiped. Unless you override the external IP with `-externalip`, in which case I think you do need to specify it because that overrides the automatic setting.

**Comment by Willtech** [comment]
[Pull Request# 12384](https://github.com/bitcoin/bitcoin/pull/12384)

**Comment by Willtech** [comment]
FWIW I have done some more follow up on this.

Tor fails to start with -zero- lines of debug output with full debug output enabled. It is a hard crash. Not even a new logfile notice is written.

I have tried stopping `bitcoin-qt`, then stopping Tor, uncommenting the relevant hidden service lines in `/etc/tor/torrc`, and then attempting to restart Tor. No success - just in case it was a port bind conflict or something similar.

The hidden-service lines exactly match the format of the example hidden-service lines in the default `torrc` file.

I have thoroughly reviewed the standard `torrc` examples and notes. I have used nyx to explore all Tor options and cannot locate either error in the config lines or additional options to assist.

In the pull request edit to `/doc/tor.md` I have only noted under the intro to section 2:
>*For Tor version 0.2.7.0 and older versions of Tor only as it is redundant in newer versions.*


This is since manually setting up the hidden service in Tor is no longer necessary with newer versions of Bitcoin Core used with newer versions of Tor, and the document already notes this in section 3. Besides that, the edits to `torrc` breaks things. The use of the options listed in the next part of section 2 are still valid, but are once again redundant as Bitcoin Core does all of the necessary steps automatically.

BTW in what version of Bitcoin Core was Tor control first included?

**Comment by Willtech** [comment]
The pull request commit has been updated.

**Comment by Willtech** [comment]
This is obviously a Tor issue, no issue with the suggested edits to `/etc/tor/torrc` can be identified comparing against multiple sources.

If I start Tor with the hidden-service lines commented out, uncomment them, then restart Tor with a hup via nyx it loads the config quite fine with no complaint.

**Comment by adamjonas** [comment]
closed via https://github.com/bitcoin/bitcoin/pull/12384
