### ISSUE TITLE
travis failure on rc3: "src/crypto/ctaes is not a subtree"

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#12388]
Travis on the 0.16 branch is failing on the subtree check.
```
0.04s$ if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/crypto/ctaes; fi
ERROR: src/crypto/ctaes is not a subtree
The command "if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/crypto/ctaes; fi" failed and exited with 2 during .
```
The reason for this is that it makes a shallow clone, and the last change to that subtree is deeper than the oldest commit fetched.

The obvious solution would be to clone deeper, but that would be kicking the can down the road and make things slower. I'd say to be robust the check needs to generate a warning in this case but continue. If nothing changed to it in the last 50 commits, then the subtree can be assumed to be fine, otherwise we would have intervened by then.

Ping @MarcoFalke @sipa

**Comment by MarcoFalke** [comment]
The compressed size of the git objects for master at --depth 50 and --depth 99999 is 60 MiB and 80 MiB, respectively. 

On the rc3 tag it is 30 MiB, but still with a bandwidth of 19.80 MiB/s, this should have limited effect on the total run time. https://travis-ci.org/bitcoin/bitcoin/jobs/338906244#L351

**Comment by laanwj** [comment]
Grr apparently we already have an `git fetch --unshallow` step, removed it in 5e40e64face29169ef355856dc0db46a98061046, hopefully the tests there are fixed now...

**Comment by aarisa76** [comment]
0.04s$ if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/crypto/ctaes; fi
ERROR: src/crypto/ctaes is not a subtree
The command "if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/crypto/ctaes; fi" failed and exited with 2 during # #

**Comment by MarcoFalke** [comment]
We use a full clone now on all platforms (0f58d7f3d62f012f2584f5e781fc73de4763dd9e) due to
* git subtree check
* verify commits
and to simplify the travis yaml

Hope that is ok.
