### ISSUE TITLE
You need to return the block explorer to the wallet

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#12385]
I consider that it is necessary in the future, it is necessary to accustom people to use a wallet.
If they start to leave because of the size of the blocks, bitcoin will lose a lot of nodes.
It is necessary to return the connections to the people and make them use the purse.
I also suggested adding p2pool inside the wallet with connections to the server.

**Comment by DATSEC** [comment]
In one window a decentralized exchange, in another window a purse with a block explorer on another p2pool
Standard, where the wallet is always open and used.

**Comment by sipa** [comment]
This is not a place for random thoughts.

**Comment by DATSEC** [comment]
@sipa These are not random thoughts, but a concept.

**Comment by sipa** [comment]
Fine, this is not a place for concepts.

What you're suggesting is either impossible with resource limitations (block explorers require very large indexes of the chain that users don't need to be burdened with) or infeasible without massive effort (integrating p2pool). You're welcome to work on such features if you're interested in them, but by no means are these things that anyone *needs* to do, sorry.

Keep the issue tracker for actual issues.

**Comment by DATSEC** [comment]
@sipa 
Then where are the concepts discussed with the bitcoin developers if not here.
If I have topical thoughts where should I describe them, what would you see?

You write it is impossible, but you are not right here.
I suggest dismantling the structure of the bitcoin purse for the server part and desktop PC.

The same block explorer can be supported by the server part via the p2p system.
p2pool can also connect several servers inside the purse.
And this is only the beginning of the concept.
As a result, the user gets a full block explorer and bfgminer p2pool inside the architecture.

**Comment by DATSEC** [comment]
@sipa Later it will be possible to connect the phones to the mining when p2pool will completely unite all the miners into one mine.
Do you understand what I am describing to you?
