### ISSUE TITLE
Which state do I need to checkout on github to get pre-segwit node

### ISSUE THREAD

**Issue by tstasevych** [bitcoin/bitcoin#12383]
Which state do I need to checkout on github to get pre-segwit node?

Thanks!

**Comment by MarcoFalke** [comment]
A wallet with segwit support (addresses and change) is currently in the release phase (rc). Previous releases do not come with segwit wallet support.

Please note, usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
