### ISSUE TITLE
QT says "Synching Headers" during a reindex

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12398]
<img width="837" alt="schermafbeelding 2018-02-09 om 16 30 32" src="https://user-images.githubusercontent.com/10217/36035229-93d1c1bc-0db6-11e8-9e67-fdef9d01c14a.png">

I restarted QT during the reindex, so that may be related.

At the bottom of the screen it does correctly say "Processing blocks on disk"

**Comment by MarcoFalke** [comment]
You might want to try `-reindex-chainstate`

**Comment by MarcoFalke** [comment]
I meant to say that with reindex it is expected to sync the headers first, with reindex chainstate you only reindex the chainstate, which is sufficient in most cases.

I propose to close as "not a bug"

**Comment by Sjors** [comment]
To clarify: I started a reindex using bitcoind, stopped bitcoind, and then started Bitcoin-QT, without `-reindex`. QT just continued the reindexing work. I don't think it was actually syncing headers when I made that screenshot.

**Comment by Sjors** [comment]
I'll reopen if I see this again.
