### ISSUE TITLE
Unable to import Electrum private key to 0.16.0

### ISSUE THREAD

**Issue by rex4539** [bitcoin/bitcoin#12397]
Describe the issue.
Importing a Bech32 private key in the debug console returns "Invalid private key encoding" error.

What behavior did you expect?
Private key is imported.

What was the actual behavior (provide screenshots if the issue is GUI-related)?
Invalid private key encoding (code -5)

![screen shot 2018-02-09 at 16 46 32](https://user-images.githubusercontent.com/227442/36033194-fc38daa4-0db8-11e8-803a-3586aea2c689.png)

How reliably can you reproduce the issue, what are the steps to do so?
1. walletpassphrase "mypasswordhere" 1000
2. importprivkey myprivatekeyhere

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
Bitcoin Core 0.16.0rc3 / https://bitcoin.org/bin/bitcoin-core-0.16.0/test.rc3/

What type of machine are you observing the error on (OS/CPU and disk type)?
OSX 10.11.6 / 2,4 GHz Intel Core 2 Duo / HDD

Any extra information that might be useful in the debugging process.
My private key is a normal 52 character key starting with an L and ending with a K.

[debug.log](https://github.com/bitcoin/bitcoin/files/1711366/debug.log)

**Comment by sipa** [comment]
The error "Invalid private key encoding" is thrown when the Base58 decoding fails. This could happen when there is a typo in the key, or if it's for the wrong network (e.g. it's a testnet key).

Up to that point in the code, there should not be anything segwit specific.

Where did you get this private key? Does importing it work when you run an earlier version?

**Comment by rex4539** [comment]
There is definitely no typo or wrong network issue.

I'm copy/pasting it from Electrum.

I have created and use this Bech32 address in Electrum (mainnet).

I tried with Bitcoin Core 0.16.0rc2 and it fails there too.

Didn't try with earlier versions because it is my understanding that 0.16 is the first version supporting Bech32.

**Comment by sipa** [comment]
This has nothing to do with Bech32. The set of acceptable private keys hasn't changed.

**Comment by rex4539** [comment]
I will test with 0.15.1 and report back.

**Comment by rex4539** [comment]
Same bug with 0.15.1

Oh well, I guess I will not be able to import this key into Core...

It's a shame because I wanted to fully transition to Core.

I have imported all my legacy private keys and this was the last one.

Will stick to Electrum for Bech32 then.

**Comment by sipa** [comment]
@rex4539 I'm sure there's a way to convert the private key into Bitcoin Core's format.

**Comment by rex4539** [comment]
If anyone has a tool for converting it, I'd be happy to try it :)

**Comment by MarshMallowMan** [comment]
Could you possibly be using a 2 Factor Authentication Electrum Wallet? saw another post online of someone failing to import keys to bitcoin core from Electrum and that was his problem.

**Comment by rex4539** [comment]
No, just using a simple segwit wallet.

**Comment by Sjors** [comment]
This might work, but I haven't tested it: https://github.com/spesmilo/electrum/issues/3667

**Comment by Sjors** [comment]
Duplicate of #12111

**Comment by rex4539** [comment]
Tried the solution mentioned in the linked post but still getting the same error.

**Comment by Sjors** [comment]
@rex4539 your best chance is probably to ask the Electrum folks (and maybe share their solution in #12111)

**Comment by rex4539** [comment]
ok, the correct solution is the one posted here:

https://github.com/spesmilo/electrum/issues/3667

Finally imported the bech32 address into Core :)

**Comment by ecdsa** [comment]
@sipa indeed we extended the WIF format in Electrum version 3.0, in order to have a bijection between WIF and addresses. Maybe we will switch to a format with a user-readable prefix, eg: "p2pkh:<base58privkey>"
