### ISSUE TITLE
zapwallettxes should probably clear the mempoool?

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#12400]
I was trying to clean out some transactions out of a wallet, so I restarted bitcoin with `-zapwallettxes`, but after rescanning it ended up having the same transactions again. The next time I deleted the mempool.dat and restarted with zapwallettxes  and it actually worked.

So thinking it probably makes sense that the default behavior of zapwallettxes is to clear out the mempool at launch.

**Comment by Sjors** [comment]
Or at least clear wallet transactions from the mempool?

**Comment by jonasschnelli** [comment]
I guess this is fixed since 0.15 (see #10330).
@RHavar: what version of Bitcoin Core have you used while detecting this misbehaviour?
