### ISSUE TITLE
signrawtransaction without "amount" creates invalid signature

### ISSUE THREAD

**Issue by bitcoinhodler** [bitcoin/bitcoin#12429]
The bitcoin-cli help states that for each "prevtxs", "amount" is a required field. When I use `signrawtransaction` to do an offline signing of a segwit spend, if I omit this field, instead of an error message, I get an invalid signature.

# Expected behavior
When I omit the required "amount" field, I expect bitcoin-cli to report an error message. (Perhaps, for backward compatibility, it should only be an error if the amount is actually used in the signature calculation.)

# Actual behavior
I get a complete, apparently good transaction, but when I attempt to broadcast it using `sendrawtransaction`, I get the following error:
```
64: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation) (code -26)
```
When I include amount, I get a good transaction that differs only in the witness signatures for this input.

# To reproduce
I'm running on my own Linux build of Bitcoin Core from tag v0.16.0rc3.

[This script](https://pastebin.com/xk4hQbXy) shows the issue [[output]](https://pastebin.com/qfKhD4Wj). The first call to `signrawtransaction` is missing the amount.

**Comment by jonasschnelli** [comment]
When you provide the amount during an offline signing process with `signrawtransaction` , I would expect that the outpoint – where you have provided the invalid amount – is not available (because the UTXO set is not present nor do you have wallet unspents).
In a such case (complete offline signing), I'd say it's impossible to detect an invalid amount.

**Comment by bitcoinhodler** [comment]
It's impossible to detect an invalid amount, but it's easy to detect when no amount at all is given, which is what I'm asking for.

**Comment by bitcoinhodler** [comment]
From `bitcoin-cli help signrawtransaction`:

```
2. "prevtxs"       (string, optional) An json array of previous dependent transaction outputs
     [               (json array of json objects, or 'null' if none provided)
       {
         "txid":"id",             (string, required) The transaction id
         "vout":n,                  (numeric, required) The output number
         "scriptPubKey": "hex",   (string, required) script key
         "redeemScript": "hex",   (string, required for P2SH or P2WSH) redeem script
         "amount": value            (numeric, required) The amount spent
       }
       ,...
    ]
```

When I fail to provide the other required fields (scriptPubKey, txid, or vout) I get the following:
```
error code: -3
error message:
Missing txid
```

Shouldn't amount behave the same way?

**Comment by coolmagic** [comment]
any update on this, I am getting the same
