### ISSUE TITLE
Debug.log file does not generated?

### ISSUE THREAD

**Issue by leegod** [bitcoin/bitcoin#12420]
I am trying to compile in ubuntu 16.04, changed source code little bit and tried compile, 

Typed 'make install' and error says, "recipe for target 'install-recursive' failed".

I revised source like this, chainparams.cpp : 123~126 line around approx.assert(consensus.hashGenesisBlock == uint256S("0x"));   // deleted whole after '0x' to spit out error and then debug.log file will show the right value?

but after try, debug.log file itself does not generated.
With older source, debug.log file is generated at folder, Home/.bitcoin  (hidden folder, but ctrl+H key reveals)

**Comment by markaw67** [comment]
Fuck you you little bitch you aint shit


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by leegod** [comment]
Fuck you too
