### ISSUE TITLE
Json value converting error of NetworkHashps 

### ISSUE THREAD

**Issue by jeong760** [bitcoin/bitcoin#12439]
I have a problem to get a NetworkHashps using JSON request after upgrade of 15.01 bitcoin core. so cannot make a mining pool for bitcoin using CoiniumServ.. 

**The issues are** 
Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Pools.INetworkInfo ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Pools.NetworkInfo ---> System.Exception: **There was a problem deserializing the response from the coin wallet**. 
---> Newtonsoft.Json.JsonSerializationException: **Error converting value 1.98121075128195E+19 to type 'System.UInt64'**. Path 'result.networkhashps', line 1, position 158. ---> System.OverflowException: Arithmetic operation resulted in an overflow.

So I want to know where should I changed to prevent this error.

Regards,
John Ahn

**Comment by jeong760** [comment]
Dears,

This is a CoiniumServ code for handling Json response.

**/src/pool/DaemonBase.cs**
private DaemonResponse GetRpcResponse(HttpWebRequest httpWebRequest)
{
string json = GetJsonResponse(httpWebRequest);

        _logger.Verbose("rx: {0}", json.PrettifyJson());

        try
        {
            return JsonConvert.DeserializeObject<DaemonResponse<T>>(json);
        }
        catch (JsonException jsonEx)
        {
            httpWebRequest = null;
            throw new Exception("There was a problem deserializing the response from the coin wallet.", jsonEx);
        }

**src/Daemon/DaemonResponse.cs**
[JsonProperty]
private UInt64 NetworkHashps { get; set; }

    [JsonIgnore]
    public UInt64 NetworkHashPerSec { get; set; }

    [OnDeserialized]
    internal void OnDeserializedMethod(StreamingContext context)
    {
        NetworkHashPerSec = 0;

        if (NetMHashps > 0)
            NetworkHashPerSec = (UInt64)(NetMHashps*1000*1000);
        else if (NetworkGhps > 0)
            NetworkHashPerSec = (UInt64)(NetworkGhps * 1000 * 1000 * 1000);
        else if (NetworkMhps > 0)
            NetworkHashPerSec = (UInt64)(NetworkMhps * 1000 * 1000);
        else if (NetworkHashps > 0)
            NetworkHashPerSec = NetworkHashps;

**Comment by sipa** [comment]
You can't represent this value as a uint64 anymore, you'll need to use a double or a larger integer type.

**Comment by jeong760** [comment]
@sipa, thanks your advise. I will made change and update here
