### ISSUE TITLE
Possibility to import XPub (master public key, e.g. from trezor or ledger or electrum) and watch addresses in read-only mode

### ISSUE THREAD

**Issue by chompomonim** [bitcoin/bitcoin#12449]
I do use Bitcoin Core (`bitcoind`) for monitoring status of my bitcoin addresses. Now I'm generating addresses from XPub (exported from Trezor) and importing them using JSONRPC. This is not very convenient and requires running additional script/service to generate addresses.

I'd like to be able to create new wallet (read-only) by using XPub and then getting new addresses (via `getnewaddress`) and monitoring them (via `getreceivedbyaddress`) using `bitcoind` and it's jsonrpc.

**Comment by jonasschnelli** [comment]
There is a proposal. See #9728

**Comment by achow101** [comment]
Descriptor wallets have enabled this functionality.
