### ISSUE TITLE
QT Core wallet crash on external hard drive unplug

### ISSUE THREAD

**Issue by rbndg** [bitcoin/bitcoin#12440]
Hello everyone.

I was syncing with the btc blockchain, i'm running the wallet in an external hard drive connected to my Macbook Pro (running latest Mac Os)

The external drive accidentally got unplugged and it seems like my copy of the blockchain is now corrupted and now I have to  to start syncing with the blockchain from scratch.

is it possible to prevent this behaviour from happening? 
Since the blockchain is becoming bigger, i'm sure many people will put it in an external drive.
Can QT Core just continue at the last verified block?

**Comment by WorkShop-Office** [comment]
What does it mean ? I am according to prusedur

**Comment by laudaa** [comment]
It is really not recommended to run it on an external hard drive to begin with. This had happened to me in the past as well.

**Comment by rbndg** [comment]
To me It’s seems counter productive.
It’s perfect reasonable to allow people to put the blockchain on an
external hard drive.

**Comment by randolf** [comment]
To be fair, a lot of databases will exhibit problems if the drive they reside on is unexpectedly disconnected.

While it's true that there are strategies that can be used to mitigate these types of problems, the trade-off can be slower performance and even then there's still a risk of data integrity problems.

**Comment by laudaa** [comment]
@rbndg Nobody said that wasn't allowed. If you disconnect your hardware in the middle of a process, then that is a issue caused by the user not the software.

**Comment by jonasschnelli** [comment]
DB corruptions are unfortunate... see also https://github.com/bitcoin/bitcoin/issues/8037 as a proposal to make them less worse.

AFAIK, most people use an external drive because the block data take up to much space. Consider using -prune or symlink out your block file.

I think a configuration option that would allow to specify a block storage directory would be handy (instead of sym-linking)

**Comment by rbndg** [comment]
I agree. I think the initial UX of running Btc Core can be improved.

I think the initial setup phase should be a wizard where the user can choose to run prune or not and the difference is explained.
Then they can choose the block storage directory. 
it's also flexible as it's possible to add more steps in the future.

However, i think initially just a warning will suffice.

**Comment by rbndg** [comment]
@laudaa I'm not saying it's a software issue, i think it's user experience issue. If we want to encourage more people to run Bitcoin Core then UX should be forgiving or at least a bit more clear.

Also sometimes it's not the user's fault. If you run your external hard drive from a USB hub and the user has a power outage then they have to start again from scratch.

**Comment by Willtech** [comment]
@rbndg If the user has a power outage they sometimes have to start again from scratch, even without a USB hub.

**Comment by rbndg** [comment]
If they are using a laptop, they will be unaffected

**Comment by eklitzke** [comment]
Did you actually have to sync from scratch after seeing this error? Generally you should be able to proceed using `-reindex`. Did you try that?

**Comment by jnewbery** [comment]
@rbndg - are you able to answer @eklitzke's question? Did you try a `-reindex`?

**Comment by rbndg** [comment]
It did not work. i'm downloading it again.
