### ISSUE TITLE
QT Windows (64) - `__gxx_personality_v0'

### ISSUE THREAD

**Issue by RossClelland** [bitcoin/bitcoin#12441]
Hey,

I'm trying to build the QT client for Windows using the instructions in /doc. I've installed Ubunutu for Windows, installed the dependencies and run the build script as per the document.

>     PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var
>     cd depends
>     make HOST=x86_64-w64-mingw32
>     cd ..
>     ./autogen.sh # not required when building from tarball
>     CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
>     make

The script ran for about an hour and a half before failing with the following error:

> /usr/include/c++/5/ostream:509: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
> .libs/libbitcoinconsensus_la-utilstrencodings.o: In function `__static_initialization_and_destruction_0':
> /usr/include/c++/5/iostream:74: undefined reference to `__dso_handle'
> /usr/include/c++/5/iostream:74: undefined reference to `__cxa_atexit'
> .libs/libbitcoinconsensus_la-utilstrencodings.o: In function `__static_initialization_and_destruction_0':
> /home/ucs/bitcoin-0.15.1/src/utilstrencodings.cpp:15: undefined reference to `__dso_handle'
> /home/ucs/bitcoin-0.15.1/src/utilstrencodings.cpp:15: undefined reference to `__cxa_atexit'
> /home/ucs/bitcoin-0.15.1/src/utilstrencodings.cpp:17: undefined reference to `__dso_handle'
> /home/ucs/bitcoin-0.15.1/src/utilstrencodings.cpp:17: undefined reference to `__cxa_atexit'
> .libs/libbitcoinconsensus_la-utilstrencodings.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
> collect2: error: ld returned 1 exit status
> Makefile:3562: recipe for target 'libbitcoinconsensus.la' failed
> make[2]: *** [libbitcoinconsensus.la] Error 1
> make[2]: Leaving directory '/home/ross/bitcoin-0.15.1/src'
> Makefile:9295: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/ross/bitcoin-0.15.1/src'
> Makefile:746: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

I've looked online and there are suggestions that the compiler things I'm trying to use c code rather than c++ however I'm at a loss as to where I need to make changes to specify g++. Any assistance would be welcome.

**Comment by RossClelland** [comment]
Started from scratch and it worked.

**Comment by llpin** [comment]
I have the same problem
