### ISSUE TITLE
bitcoin-qt not working

### ISSUE THREAD

**Issue by sapirx3** [bitcoin/bitcoin#12471]
i sent my 2 btg from exodus to bitcoin wallet core (from offical site) and it take to much time (6 hour)and still didn't finish
it's downloaded block i don't know why and then stuck after 6 hour from transference
so i exit from this wallet and try to enter again
and i get this error:

assertion faild!
program: C:\Program Files\BitcoinGold\bitcoin-qt.exe
file chain.cpp, Line 101
Expression: pindexWalk ->pprev

someone know what is the problem?

tnx in advance

**Comment by fanquake** [comment]
If you are using BitcoinGold, this is not the correct repository to report issues too.

**Comment by sapirx3** [comment]
ok sorry
