### ISSUE TITLE
issue when rendering on win10 

### ISSUE THREAD

**Issue by JamesDelmai1195** [bitcoin/bitcoin#12472]
i m having this while building anyone having same with ubuntu and wsl
note i m win user and not really familiar with linux
make HOST=x86_64-w64-mingw32 V=1 AUTOMAKE=:
make: *** No targets specified and no makefile found

**Comment by MarcoFalke** [comment]
At which step of https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#windows-build-notes does it fail?
