### ISSUE TITLE
bitcoin-qt opens the wrong conf file.

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12488]
v0.15.1 release.

`bitcoin-qt` opens the wrong conf file when a conf file is specified with `-conf={file}`

Key:

    >bitcoin-qt -conf=altconf.conf

Go to: Settings --> Options --> Open Configuration File --> OK

Editor opens with `default.conf` instead. Should open specified conf, also using `-datadir={folder path}` parameter which I have not checked.

**Comment by jonasschnelli** [comment]
Can confirm the bug in master, fix available in #12489.

**Comment by Willtech** [comment]
Speedy service on that fix@!

**Comment by dmoney0546** [comment]
Help
