### ISSUE TITLE
bitcoind + testnet on same machine fails when zmq is active

### ISSUE THREAD

**Issue by FeedTheWeb** [bitcoin/bitcoin#12481]
Trying to run bitcoind node and a testnet node on the same machine, but starting testnet fails when zmq is active

```
$ bitcoind  -testnet
bitcoind: zmq/zmqpublishnotifier.cpp:104: virtual void CZMQAbstractPublishNotifier::Shutdown(): Assertion `psocket' failed.
Aborted (core dumped)
```
When zmqnotifications is configured only on mainnet, the testnet fails to start (even when zmq is disabled or configured with different port on testnet).

0.16rc4

ubuntu 16.04

**Comment by promag** [comment]
Can you post the configuration and debug.log?

**Comment by FeedTheWeb** [comment]
debug.log does not show anything, because the application didnt start.

testnet3/bitcoin.conf 
```
listen=1
rpcport=8444
testnet=1
checkblocks=50
#zmqpubrawtx=tcp://127.0.0.1:28441
#zmqpubhashtx=tcp://127.0.0.1:28442
#zmqpubhashblock=tcp://127.0.0.1:28443
#zmqpubrawblock=tcp://127.0.0.1:28444
#zmqpubrawtx=tcp://127.0.0.1:28445

```
