### ISSUE TITLE
bitcoin-qt crashes after clearing proxy info

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12498]
v0.15.1 release version

On F27 `bitcoin-qt` crashes after clearing proxy info from options.

To replicate: (suggested - I cannot re-prove since the issue causes crash)

1. Configure proxy information and correctly restart `bitcoin-qt`
2. Clear all proxy information, IP addresses, ports, ignore the warnings as you do this, and then clear the proxy checkboxes.
3. OK and then correctly restart `bitcoin-qt`
4. When `bitcoin-qt` is loaded, go to Settings --> Options
5. Crash

Console returns `Aborted (core dumped)`

`bitcoin-qt` should not crash if all proxy information is cleared.

Note: in my bitcoin.conf I currently have no proxy settings there either but, still several addnode={onion} lines (actually, tried now without those also). I previously had `proxy={proxy:port}` settings in the `bitcoin.conf` and have also previously set them in the GUI.

`debug.log` says:

    2018-02-21 10:15:47 GUI: ASSERT failure in QList<T>::at: "index out of range", file /home/ubuntu/build/bitcoin/depends/x86_64-linux-gnu/share/../include/QtCore/qlist.h, line 537

Note that I am not on `/home/ubuntu/{etc}` - those paths do not exist on my system.

After this, there is no way to get back into options, even setting `proxy={proxy:port}` AND `onion={proxy:port}` in `bitcin.conf` does not fix this.

This was discovered while checking for replication steps on an additional issue with proxy settings [Issue# 12499](https://github.com/bitcoin/bitcoin/issues/12499).

---
Cannot replicate bug in 0.16rc4.  
Is fixed in v0.16.0 release. 

In PR [#11809](https://github.com/bitcoin/bitcoin/pull/11809) I noted a display issue in Windows version, and a warning display issue generally.

**Comment by Willtech** [comment]
A how/what to edit to fix the crash and get back into options after triggering his bug would be nice.

**Comment by MarcoFalke** [comment]
You can run in gdb or valgrind. They print the trace back for you.

**Comment by Willtech** [comment]
>gdb bitcoin-qt
    GNU gdb (GDB) Fedora 8.0.1-36.fc27
    Copyright (C) 2017 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from bitcoin-qt...Missing separate debuginfo for /usr/local/bin/bitcoin-qt
    Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f0/00148c3dd7884bf7a33ff5c60fcc9cf5c47579.debug
    (no debugging symbols found)...done.
    (gdb) run
    Starting program: /usr/local/bin/bitcoin-qt 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    [New Thread 0x7fffeeca3700 (LWP 21086)]
    [New Thread 0x7fffed685700 (LWP 21087)]
    [New Thread 0x7fffe7ccf700 (LWP 21088)]
    [New Thread 0x7fffe5436700 (LWP 21089)]
    [New Thread 0x7fffe4c35700 (LWP 21090)]
    [New Thread 0x7fffcbfff700 (LWP 21094)]
    [New Thread 0x7fffc9048700 (LWP 21095)]
    [New Thread 0x7fffc8847700 (LWP 21096)]
    [New Thread 0x7fffc22f2700 (LWP 21097)]
    [New Thread 0x7fffc1af1700 (LWP 21098)]
    [New Thread 0x7fffc12f0700 (LWP 21099)]
    [New Thread 0x7fffc0aef700 (LWP 21100)]
    [New Thread 0x7fffa7fff700 (LWP 21101)]
    [New Thread 0x7fffa77fe700 (LWP 21102)]
    [New Thread 0x7fffa6ffd700 (LWP 21103)]
    
    Thread 1 "bitcoin-qt" received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    51	}
    Missing separate debuginfos, use: dnf debuginfo-install freetype-2.8-7.fc27.x86_64
    (gdb) 

I actually do have the debug info for freetype installed.

**Comment by laanwj** [comment]
Can you test with 0.16rc4? I think this issues was solved with #11809.

**Comment by Willtech** [comment]
fixed in 0.16rc4.

**Comment by MarcoFalke** [comment]
Imo we could backport that fix to the 15 branch

**Comment by Willtech** [comment]
Can no longer replicate bug in 0.16rc4.

**Comment by Sjors** [comment]
Can be closed?

**Comment by Willtech** [comment]
Has a v0.15.2 milestone on it.

**Comment by MarcoFalke** [comment]
Tagged the pull for backport instead.
