### ISSUE TITLE
No Information about transaction

### ISSUE THREAD

**Issue by ekembs** [bitcoin/bitcoin#12504]
I am working through the Mastering Bitcoin book
and when I run the getrawtransaction (from Chapter 3) I get an error
Funnily enough, when I run decoderawtransaction and getblockhash, those functions work
$ sudo bitcoin-cli getrawtransaction 0627052b6f28912f2703066a912ea577f2ce4da4caa5a5fbd8a57286c345c2f2
###COMMAND LINE##
error: {"code":-5,"message":"No information available about transaction"}

QUESTION
I have run the below command to redownload the "blocks" and "chainstate" folder
$bitcoind -reindex
But nothing is happening.

Do I have to reinstall bitcoin?

**Comment by sipa** [comment]
You need to run with txindex enabled in order to look up arbitrary chain transactions. Enabling txindex will require you to rebuild the index.

**Comment by MarcoFalke** [comment]
Just to note that with the upcoming 0.16 release you don't need to txindex, if you know what block the transaction is in. Try `help getrawtransaction` on 0.16.0+ for the interface.

**Comment by ekembs** [comment]
I put txindex in the bitcoin.conf.
Does that work or do I have to run it as
$bitcoind -reindex -txindex=1

**Comment by MarcoFalke** [comment]
* You can look up "non-arbitrary", i.e. wallet-transactions, with gettransaction.

> My bitcoin.conf already has txindex=1. How long would it take to rebuild the index.

Txindex might take several days, but you only need to reindex to the block that includes your transaction.

**Comment by ekembs** [comment]
How do you reindex to the particular block? What is the ubuntu command line code
