### ISSUE TITLE
tooltip refers to "total at least" - what is that?

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#12500]
It's not clear to me what this tooltip is talking about:

    If the custom fee is set to 1000 satoshis and the transaction is only
    250 bytes, then "per kilobyte" only pays 250 satoshis in fee, while
    "total at least" pays 1000 satoshis. For transactions bigger than a
    kilobyte both pay by kilobyte.

![screenshot - 18-02-21 - 03 46 12 am](https://user-images.githubusercontent.com/573356/36478594-2265eb72-16ba-11e8-81c4-6a8ed6ee00bf.png)

Is "total at least" an old feature which has since been removed?

**Comment by MarcoFalke** [comment]
Yes, please remove the references from the string.

**Comment by randolf** [comment]
@dooglus Please see PR 12501 in which I'm attempting to improve the wording of this tooltip.
Reference:  https://www.github.com/bitcoin/bitcoin/pull/12501

**Comment by laanwj** [comment]
This message has been changed, so this can be closed.
