### ISSUE TITLE
Bad interaction of -zapwallettxes and pruning / multiwallet

### ISSUE THREAD

**Issue by bpay** [bitcoin/bitcoin#12505]
After some googling, I recently ran `bitcoin-qt -zapwallettxes` on a 0.15.1 pruned multiwallet node in order to remove a stuck transaction from the transaction list, without fully understanding what I was doing. After running the command and realizing what I'd done, I was surprised to learn
1. The operation succeeded without warning despite the fact I was running a multiwallet configuration
2. The operation succeeded without warning even though I was running a pruned node. Meaning I now had to re-download and verify the full blockchain to get my wallets' transactions back
3. The software made no wallet backups despite the destructive nature of the operation

After some poking around in the code a bit it appears there are safeguards against 1 and 2, but they didn't trigger in this case. Maybe because my pruning and wallet options were being set via bitcoin.conf instead of the command line?

**Comment by jnewbery** [comment]
I'm surprised that `-zapwallettxes` worked with multiwallet. Are you sure that you were running with multiple `-wallet` arguments when you started with `-zapwallettxes`? Are you able to share your debug.log?

I agree that `zapwallettxes` should trigger a backup.

Longer term, `zapwallettxes` should move to a separate bitcoin-wallet-tool utility. See #8745.

**Comment by bpay** [comment]
I was loading the wallets via bitcoin.conf rather than `-wallet`. The `-zapwallettxes` sanity checks appear to only look at command line args for conflicts and ignore conf file options.

**Comment by jnewbery** [comment]
> The -zapwallettxes sanity checks appear to only look at command line args

I don't think that's it. All the `gArgs` functions work on the combined command line and conf file arguments.

I've tried this myself (with the following config):

```
daemon=1
debug=all
server=1
regtest=1

[regtest]
wallet=w1
wallet=w2
zapwallettxes=1
```
and bitcoind refuses to start as expected:
```
Error: -zapwallettxes is only allowed with a single wallet file
```

**Comment by MarcoFalke** [comment]
Jup, that check was added in 9cbe8c80bad1b55557a91db65a06b66ec4743f18 and is thus in 0.15.0 and later.

Marking "good first issue", since those are untested right now. Could add a test by modifying `./test/functional/wallet_multiwallet.py`

**Comment by bpay** [comment]
I'm starting bitcoin with `bitcoin-qt -datadir=c:\bitcoindata -zapwallettxes` and with config
```
wallet=wallet1.dat
wallet=wallet2.dat
prune=1
```

**Comment by bpay** [comment]
[debug.log](https://github.com/bitcoin/bitcoin/files/1917562/debug.log)

**Comment by bpay** [comment]
[debug.log](https://github.com/bitcoin/bitcoin/files/1917569/debug.log)
