### ISSUE TITLE
Switch to Ubuntu 18.04 for gitian building

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#12511]
For 0.17 we should aim to use Ubuntu 18.04 for building. This will be the new LTS release of Ubuntu.
We skipped 16.04 because of problems with the windows binary (#8732) but this was solved in 16.10, so ruling out new issues, the way should be clear.

This means finally building with a new C++ compiler, binutils, etc. Also this will solve a known security issue with the NSIS windows installer.

**Comment by MarcoFalke** [comment]
This means the travis configuration no longer mimics the gitian build configuration. I don't think this leads to problems, since the travis configuration is the more ancient one.

**Comment by laanwj** [comment]
Right - upgrading the test infrastructure to the same version would be nice, though indeed not necessary as long as we'll want to keep supporting building on 14.04.

**Comment by akx20000a** [comment]
So it will be 14.04 to 18.04 right?

**Comment by laanwj** [comment]
> So it will be from Trusty to Bionic right?

Correct.

**Comment by cdecker** [comment]
We had the same issue with travis on another project and decided to bite the bullet and build in docker images that shipped with all the dependencies. Since we already use `sudo: required` it shouldn't make CI testing much slower, but it feels a bit like operating through a keyhole to pass in the environment to the containers.

**Comment by Sjors** [comment]
Concept ACK

**Comment by luke-jr** [comment]
`vmbuilder` will likely have difficulty, since it can't handle the latest Debian stable. :/

**Comment by TheCharlatan** [comment]
@cdecker , the project you mentioned is similar to bitcoin? I am looking for a docker image that can handle new build utils, so I do not have to rely on whatever distro Travis is currently supporting. 
The Travis Xenial builds are still not officially supported. When I run them on my fork, I have to constantly restart them, since they stall on startup.

**Comment by cdecker** [comment]
@TheCharlatan yes, it's the c-lightning implementation we are working on, feel free to take a look at our .travis.yml and our builder docker images (in contrib/).

**Comment by Sjors** [comment]
Would it make sense to also change the [suggested host](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md ) (virtual) machine from Debian 8 to Ubuntu 18.04? Fewer distros to deal with in documentation and given Ubuntu's popularity, it might increase the number of potential gitian signers who already have it. The required changes seem non-trivial though.

**Comment by laanwj** [comment]
@sjors In principle I only care that the 'suggested host' way of working is documented and maintained (by regularly testing whether it still works). So I'm ok with switching it to Ubuntu if that's easier. I chose Debian back in the day because of the minimalism.

I think it's a good discussion to have, however it's completely orthogonal to the issue of what to use as the guest.

**Comment by MarcoFalke** [comment]
Ideally it should work on any host that comes with the dependencies. However, the whole vmbuilder, lxc or kvm, gitian-builder setup on top of the host image that is bumped every couple of months seems extremly fragile. Wasn't there some effort to move to something more out-of-the-box like docker? I think @achow101 once mentioned something on IRC?

**Comment by achow101** [comment]
> I think @achow101 once mentioned something on IRC?

I was working on using docker and docker images for gitian as an alternative to lxc or kvm (so it wouldn't use vmbuilder and instead use standard docker images) although I got sidetracked from doing that.

**Comment by ken2812221** [comment]
If I select gcc-7 for gitian-build, it failed at check-symbol. Do this mean that I should choose an older version of gcc?
```
test/test_bitcoin: symbol __divmoddi4 from unsupported version GCC_7.0.0
test/test_bitcoin: symbol log2f from unsupported version GLIBC_2.27
qt/bitcoin-qt: symbol __divmoddi4 from unsupported version GCC_7.0.0
qt/bitcoin-qt: symbol log2f from unsupported version GLIBC_2.27
