### ISSUE TITLE
Instructions for compiling Bitcoin Core missing steps or otherwise not compiling bitcoin for windows in linux

### ISSUE THREAD

**Issue by number9387** [bitcoin/bitcoin#12515]
I downloaded Oracle VM to run Linux on my windows computer to compile a windows executable of bitcoin core.  I've had many errors and spent over the last 24 hours downloading, building, and overall troubleshooting to no avail.  Considering the number of errors I experienced I think the steps may need to be re-examined when running a fresh install of Linux. (I have linux version 16.04).  If there are certain "intuitive" steps that were left out, as someone not that familiar with linux, I am likely unaware of them.

Some specific issues I've run into:

1. https://askubuntu.com/questions/91815/how-to-install-software-or-upgrade-from-an-old-unsupported-release is required, per the download instructions, to build this, but even following the instructions on this page results in errors

2.  funcs.mk:242: recipe for target '/home/a/bitcoin/depends/work/build/x86_64-w64-mingw32/zeromq/4.2.2-58b9134cfdf/./.stamp_configured' failed

3. 
compilation terminated.
...failed gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-mingw-6.2.1/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi/operations.o...
...skipped <pbin.v2/libs/filesystem/build/gcc-mingw-6.2.1/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi>libboost_filesystem-mt-s.a(clean for lack of <pbin.v2/libs/filesystem/build/gcc-mingw-6.2.1/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi>operations.0...
...skipped <pbin.v2/libs/filesystem/build/gcc-mingw-6.2.1/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi>libboost_filesystem-mt-s.a for lack of <pbin.v2/libs/filesystem/build/gcc-mingw-6.2.1/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi>operations.o...
...skipped <pstage/lib> libboost_filesystem-mt-s-.a for lack of <pbin.v2/libs/filesystem/build/gcc-mingw-6.2.1/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi>libboost_filesystem-mt-s.a....
...failed updating 1 target...
...skipped 3 targets...
funcs.mk:242: recipe for target '/home/a/a/bitcoin/depends/work/build/i686-w64-mingw32/boost/1_64_0-e638125fff0/./.stamp_built' failed
make: ***[/home/a/a/bitcoin/depends/work/build/i686-w64-mingw32/boost/1_64_0-e638125fff0/./.stamp_built] Error 1

**Comment by MarcoFalke** [comment]
Note that the notes for windows cross compile are in https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#windows-build-notes

**Comment by number9387** [comment]
Those are the "steps" I was referencing that did not result in a successful build.

**Comment by MarcoFalke** [comment]
> https://askubuntu.com/questions/91815/how-to-install-software-or-upgrade-from-an-old-unsupported-release is required, per the download instructions, to build this, but even following the instructions on this page results in errors

Ubuntu 16.04 is not end-of-life. I am pretty sure you don't need that. Potentially your version of Ubuntu 16.04 is messed up and you could start by wiping the vm and starting all over again. Basically, it should work by just copy pasting the commands into the vm.

**Comment by sipsorcery** [comment]
What does your VM give for the Linux Standard Base command?

`lsb_release -a`

I was one of the ones that contributed some minor updates to the Windows build document and I successfully tested the build on:

- Bare metal with Ubuntu 16.04.3 LTS,
- VMWare (12.5.7) Virtual Machine with Ubuntu 16.04.3 LTS,
- Windows Ubuntu application (aka Windows Subsystem for Linux) with Ubuntu 16.04.3 LTS.

In your case the build seems to have bombed out building the Boost dependency. That's an unusual place to fail and I'd recommend checking your VM has sufficient disk space.

**Comment by number9387** [comment]
I will wipe it and try again.  I am using Oracle VM Virtual Box and downloading a linux iso from ubuntu.com to install it.  There should be plenty of room (100gb fixed storage).

**Comment by number9387** [comment]
Okay, installed ubuntu 17.10.1 and told to download all updates.  Fresh Oracle VM Virtual Box install, I downloaded the ubuntu ISO from ubuntu.com.  I typed 

> sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git

Per the instructions for Ubuntu version 17 I typed:

> sudo update-alternatives --config x86_64-w64-mingw32-g++

Terminal responded there was no "alternative".

Then typed:
> git clone https://github.com/bitcoin/bitcoin.git

Worked.  

Then typed:
> PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var

Response was nothing.
typed:

> cd depends

which changed folders

Then typed:

>make HOST=x86_64-w64-mingw32

It did a lot of work, then it stated, after "snprintf.c" appeared to finish,

> make[1]: *** No rule to make target 'zlib/adler32.o', needed by 'zlib/libz.a'. Stop.
make[1]: Leaving directory '/home/a/bitcoin/depends/work/build/x86_64-w64-mingw32/native_ccache/3.4.1-21245b6733e'
funcs.mk:242: recipe for target '/home/a/bitcoin/depends/work/build/x86_64-w64-mingw32/native_cache/3.4.1-21245b6733e/./.stamp_built' failed
make: *** [/home/a/bitcoin/depends/work/build/x86_64-w64-mingw32/native_ccache/3.4.1-21245b6733e/./.stamp_built] Error 2

I typed lsb_release -a and got:
>No LSB modules are available
>Distributor ID: Ubuntu
>Description: Ubuntu 17.10
>Release: 17.10
>Codename: artful

**Comment by sipsorcery** [comment]
@wwg2018new Not sure what you mean? If you're doing a cross compile build for Windows then the binaries will only execute on a Windows OS and not on Linux.

**Comment by Willtech** [comment]
That same document it says:

>Ubuntu Trusty 14.04 is recommended...

I think you are lucky it works on newer versions of Ubuntu at all, e.g.  Ubuntu 16.04.3 LTS, sometimes those required versions for build are hard fixed.

**Comment by achow101** [comment]
@number9387 Did you do:

    sudo apt install g++-mingw-w64-x86-64

From what you have posted, that seems to be missing, but it is an important step.

**Comment by number9387** [comment]
Well the steps state that's just the general usage, and gave the specific step for the version of Ubuntu I was using.  Either way, I did do that too.  It changed nothing.  Same result.

**Comment by number9387** [comment]
@achow101 I am wiping the VM and will start over again from scratch to ensure no variations will alter my results and I will use your instruction.

**Comment by achow101** [comment]
Do the following commands exactly (as in copy and paste them into your terminal). Note that they are taken directly from the documentation.

```
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64
sudo update-alternatives --config x86_64-w64-mingw32-g++
git clone https://github.com/bitcoin/bitcoin.git
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make
```

**Comment by wwg2018new** [comment]
@achow101  sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64
sudo update-alternatives --config x86_64-w64-mingw32-g++
git clone https://github.com/bitcoin/bitcoin.git
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make

make install DESTDIR=/mnt/c/workspace/bitcoin  then not  exe  file

**Comment by number9387** [comment]
@achow101 Will do.  Though I saw through it, the documentation does technically miss the "cd bitcoin" before "cd depends".  

It would seem the only thing I misunderstood was the phrase "common usage" and the need to use that line at that point in the sequence regardless of the ubuntu version.

**Comment by achow101** [comment]
@wwg2018new Your question does not make any sense whatsoever.

@number9387 Hmm, indeed, that command is missing.

**Comment by wwg2018new** [comment]
@achow101 I want to  compile Bitcoin Core  in windows. I failed with this command

**Comment by achow101** [comment]
Failed in what way? Did make fail? Did it produce non-windows binaries?

**Comment by number9387** [comment]
@wwg2018new The instructions provided do not allow compiling within windows unless you are running Linux in a virtual machine.  If you are trying to compile Bitcoin Core in just straight Windows, the instructions here are not for that.

**Comment by wwg2018new** [comment]
@number9387 I am running Linux in a virtual machine;  i use build_windows_note

**Comment by wwg2018new** [comment]
@number9387  I want to compile bitcoin in Windows ，how？

**Comment by wwg2018new** [comment]
@achow101  I want to compile bitcoin in Windows ，how？

**Comment by number9387** [comment]
@wwg2018new If you're looking for help doing that you should probably start another thread for that.

**Comment by number9387** [comment]
@achow101 I followed your instructions, same exact result on the "make HOST=x86_64-w64-mingw32" step.

**Comment by Willtech** [comment]
I have just tried this on a new install of Ubuntu 16.04 LTS.

I am not convinced that `sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu zesty universe"` does what is expected on its own, there are errors on the following step when I run `sudo apt update`.

`make HOST=x86_64-w64-mingw32` fails.

**Comment by number9387** [comment]
@Willtech You didn't say if it was successful.  Were the steps all successful on Ubuntu 16.04 (without any OS updates)?

**Comment by number9387** [comment]
Just tried it again with a fresh VM install of Ubuntu 14.04.5.  Same result.  I didn't update 14.04.05 at all to ensure it didn't change the version number.  

Still complains about 

> "No rule to make target `zlib/adler32.o', needed by `zlib/libz.a'"

**Comment by Willtech** [comment]
@number9387 No, make fails. Yes, I did `sudo apt update` then `sudo apt upgrade`.

**Comment by number9387** [comment]
> @number9387 No, make fails. Yes, I did sudo apt update then sudo apt upgrade.

@Willtech I don't understand.  Or if it even matters and or to what degree.  I'm not familiar with the significances of all the terms.  If stating that "make is what is failing" is the better way of putting it, then okay.  I'll go for that.  I just want to compile this thing.

**Comment by achow101** [comment]
@number9387 I think the problem is unrelated to build instructions or commands. This looks more like an issue with the build system itself and possibly some package version or dependency issues.

**Comment by Willtech** [comment]
@achow101 note that `sudo update-alternatives --config x86_64-w64-mingw32-g++` also fails with a no alternatives response.

**Comment by mrhuke** [comment]
Failed at the same step
funcs.mk:242: recipe for target '/home/a/a/bitcoin/depends/work/build/i686-w64-mingw32/boost/1_64_0-e638125fff0/./.stamp_built' failed

Running ubuntu app in windows 10
Tried upgrading to Zesty does not work
Tried starting over several times and does not work

**Comment by achow101** [comment]
@Willtech The no alternatives response was because @number9387 did not install the mingw package. He said that even after he installed it that it still failed with the same error.

I was able to reproduce this in two clean VMs, one Ubuntu 14.04 and the other 17.10. However I am not able to reproduce it on my own machine (Ubuntu 17.10).

**Comment by Willtech** [comment]
@achow101 Not from the attempt by @number9387, from my attempt. I did install the mingw package if that is what is in the `build-windows.md` document.

**Comment by Willtech** [comment]
@achow101 To save confusion I will open a new issue - I was attempting to replicate this issue and didn't want to duplicate the thread.

**Comment by achow101** [comment]
Ok, I've identified the issue. It is because one of the dependencies recently had a version bump which now appears to be a problem.

@number9387 @Willtech You should be able to fix the current issue of `make: *** No rule to make target 'zlib/adler32.o', needed by 'zlib/libz.a'.  Stop.` by doing the following:

    sudo apt install zlib1g-dev
    git clean -fdx

Then try the make command from inside the `depends` folder and it should get past where it was stopping before.

**Comment by number9387** [comment]
`sudo apt install zlib1g-dev` definitely install something.  

subsequent command `git clean -fdx` responds with `fatal: Not a git repository (or any of the parent directories): .git`

Attempt to make produced same result as before.

**Comment by achow101** [comment]
You need to do `git clean -fdx` from inside the bitcoin folder (although it should work from inside `bitcoin/depends` too).

Alternatively, delete the folders named `work`, `built`, `sources` and `x86_64-w64-mingw32` inside the `depends` folder.

**Comment by Willtech** [comment]
@achow101 That explains why make is so far working when I this time checked out tag v0.16.0rc4 before building. Still issue with bug in the 64 bit Mingw-w64 cross-compiler that I don't think is upgraded to zesty version. Will see.

**Comment by number9387** [comment]
@willtech I'm currently, apparently, successfully compiling Bitcoin Core as a result of @achow101's help.  I too, have experienced a lack of an option to select POSIX, including this particular time, yet its still working.

**Comment by Willtech** [comment]
*If* you are using Ubuntu 16.04 *and* you haven't successfully got the zesty version of the 64 bit Mingw-w64 cross-compiler *then* your compiled executables may have issues as noted in the footnotes of `build-windows.md`

**Comment by number9387** [comment]
@Willtech Good point.  This particular Ubuntu variation I'm using is 14.04.5.  Guess I'll see soon enough.

**Comment by number9387** [comment]
Well, I just copied the Bitcoin-qt.exe to windows, and it opened and took over the folder for my normal installation w/o a problem.  No errors.  It does claim `This is a pre-release test build - use at your own risk - do not use for mining or merchant applications`, which is disheartening, but either way, it does appear to function just fine!  Thanks @achow101

**Comment by seid123** [comment]
^
Makefile:11266: recipe for target 'bitcoind-bitcoind.o' failed
make[2]: *** [bitcoind-bitcoind.o] Error 1
make[2]: Leaving directory '/home/unix/bitcoin/src'
Makefile:14411: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/unix/bitcoin/src'
Makefile:775: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1


any one respond this command?

**Comment by sipsorcery** [comment]
@seid123 this issue is closed. Could you describe your problem in a new issue. You'll need to provide some minimal information about your OS and build environment. Also there will be some log messages that detail what the error actually was. The console log snippet you've pasted only states there's an error not what it was.

**Comment by seid123** [comment]
@sipsorcery  on win 10  bitcoin 0.19.0 version
