### ISSUE TITLE
Use VMWare (12.5.7) Virtual Machine with Ubuntu 16.04.3 LTS,How to compile in Windows

### ISSUE THREAD

**Issue by wwg2018new** [bitcoin/bitcoin#12524]

**Comment by Willtech** [comment]
I presume that you mean 'How to compile for Windows'?

**Comment by wwg2018new** [comment]
@Willtech  yes , i need  windoes exe file

**Comment by MarcoFalke** [comment]
You can follow the instructions here: https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

Otherwise, you can also get the latest windows executable from https://bitcoincore.org/en/download/
