### ISSUE TITLE
GUI: file->receiving addresses->New only generates non-bech32 addresses, even if the box "generate bech32" is ticked in the main window

### ISSUE THREAD

**Issue by notsureif** [bitcoin/bitcoin#12520]
As the title says:
GUI: file->receiving addresses->New only generates non-bech32 addresses, even if the box "generate bech32" is ticked in the main window

Suggestion: put a tick box "generate bech32 addresses" in the "receiving  addresses: window as well

**Comment by promag** [comment]
To generate bech32 addresses by default launch with `-addresstype=bech32`.

**Comment by Sjors** [comment]
Concept ACK for adding a bech32 checkbox to that dialog:
 
![schermafbeelding 2018-03-15 om 16 38 14](https://user-images.githubusercontent.com/10217/37489870-6663398a-286f-11e8-9ac8-863fb5d9f9b3.png)

However, I'm not going to write that PR :-)

**Comment by jonasschnelli** [comment]
Another way would be just removing the "New" button in the address book since the address book is probably not something that should be there in the long because it leads to address reuse.

Also, there should not be two ways how to generate an address in the GUI.

**Comment by TheKogs** [comment]
Actually I am not happy with removing the New button in the address book. It broke the way I work with the qt client.
I'm usually working with the address book to create new addresses without requesting a new payment in the "Receive" tab. This is not possible anymore.

I already implemented the new checkbox in the New Address Gui. Just before I wanted to create the pull request, I merged the last changes from bitcoin/master branch and found out that my change did not compile anymore as the editaddressdialog.cpp don't support creating a new receiving address any more.

I will try to change my way how I work, but for now I don't see a comfortable way to have an overview of my addresses and can create new ones in one single gui.

Is there any chance to get this feature back?

**Comment by Sjors** [comment]
> a comfortable way to have an overview of my addresses and can create new ones in one single gui

Doesn't the Receive tab offer that?

**Comment by TheKogs** [comment]
I was playing around a bit with the Receive tab.
If I would have worked with the Receive tab from beginning I think it would be OK.
But as I did not use it before, I'm missing the already created addresses in the list. I only see them in the address book.
One advantage I can see in the Receive tab is that it's possible to remove some entries from the list. The address book keeps also unwanted addresses which makes it quite big after time.

Working with the address book was also not perfect for me as I was also missing some things like showing current balance of the addresses (also not available in the Receive tab directly - only in the Coin Control dialog), so I will think of a solution which fits my needs best and then maybe create a proposal to see if there is anyone who might like my ideas.

I will stop here as it starts to get off topic and create a new issue when I have a better idea.

**Comment by notsureif** [comment]
I think I should close this, as the merge by jonasschnelli  removes the issue in the form it's stated.
