### ISSUE TITLE
build: building depends and make install fails with space in path

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12528]
On MacOS 10.13.3 with source files in `/Volumes/Glyph 1TB/src/bitcoin`

```
sudo make install
Password:
Making install in src
  CXX      crypto/libbitcoinconsensus_la-aes.lo
...
  CXXLD    libbitcoinconsensus.la
/usr/local/bin/gsed: can't read 1TB/src/bitcoin/src/secp256k1/libsecp256k1.la: No such file or directory
libtool:   error: '1TB/src/bitcoin/src/secp256k1/libsecp256k1.la' is not a valid libtool archive
make[2]: *** [libbitcoinconsensus.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

Related to #9946?

Running make inside `/depends` also results in a cascade of errors if the source path has a space in it.

**Comment by dongcarl** [comment]
I think [libtool doesn't support spaces in pathnames](https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00033.html)...

[Protobuf seems to have the same problem](https://groups.google.com/d/msg/protobuf/G7KruSnKIek/laqUtRqpxMgJ)

**Comment by Sjors** [comment]
An easy "fix" might be to just add "Ensure sure there's no space in the path" to the build instructions.

**Comment by hebasto** [comment]
> I think [libtool doesn't support spaces in pathnames](https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00033.html)...

Current master (77a2f5d30c5ecb764b8a7c098492e1f5cdec90f0) on macOS Big Sur 11.6.1 (20G224):
```
% ./configure -q
configure: WARNING: Libtool does not cope well with whitespace in `pwd`
...
```

**Comment by hebasto** [comment]
https://github.com/bitcoin/bitcoin/pull/15441#issuecomment-592406930:

> It's uncommon for people to have spaces in their development environment path; it happened to me because I moved everything to an external SSD drive that had a bad default name. But I wouldn't consider that a broken environment.

Does the cited comment mean that this issue could be closed?

**Comment by Sjors** [comment]
I guess it's a good start.
