### ISSUE TITLE
Remove OpenSSL for non-QT builds

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12530]
OpenSSL is only used for (if I understand correctly):

1. Handling BIP-70 payment requests (can be disabled with `without-bip70`)
2. Generating random numbers (see #10299, #14623)

If (2) can be solved, then non-QT builds no longer need OpenSSL (move `openssl` to `qt_packages` in `depends/packages/packages.mk`).

This potentially makes it easier to build the depends for other platforms such as iOs (see #11720), if they don't need QT.

**Comment by MarcoFalke** [comment]
@sipa Are you still working on https://github.com/bitcoin/bitcoin/pull/10299#issuecomment-298785082?
