### ISSUE TITLE
Insert again the option of doing transaction less than 1 sat/byte

### ISSUE THREAD

**Issue by Rayserzor** [bitcoin/bitcoin#12536]
Older versions of Bitcoin Core could send transactions without a fee.
Nowadays we don't even need 1sat/byte to get a transaction confirmation.

**Comment by dooglus** [comment]
I think all you need to do is change these settings from the defaults:

    -mintxfee=<amt>
         Fees (in BTC/kB) smaller than this are considered zero fee for
         transaction creation (default: 0.00001)

    -minrelaytxfee=<amt>
         Fees (in BTC/kB) smaller than this are considered zero fee for relaying,
         mining and transaction creation (default: 0.00001)

**Comment by Raulo** [comment]
@dooglus,

It won't work that easily. The whole network does not usually relay transactions below 1 sat/byte and even if you can find some nodes to relay, the miners won't pick up the transaction. I did a test, set up a 0.000001 relay fee (10x lower than the default)  and my node picked up a few such transactions. Some even show up on block explorers https://btc.com/895d90280089701e00230089337dc8304fbf339d4f1eb8d4f63b606a5abe1b1c but miners do not include them in blocks.

**Comment by dooglus** [comment]
> miners do not include them in blocks

That sounds like something to talk to the miners about rather than being an issue here.
