### ISSUE TITLE
why bitcoin daemon limit the duplicate sending address?

### ISSUE THREAD

**Issue by passionofvc** [bitcoin/bitcoin#12538]
I use createrawtransaction to send bitcoin in testnet,
and I want to send many ammout to the same address with json rpc,
but the bitcoin-cli report me [duplicated address error].
sometime I want to divide input to many output for the same address
in order to send for next time eazily.

bitcoin-cli.exe -testnet -rpcuser=test -rpcpassword=test -rpcport=19888 
```
createrawtransaction "[{\"txid\":\"7a23f88b7e4d2eb9bb4a14192f9c2c44e4f573b6d8fcf772294c236c7e52f188\",\"vout\":1}]" "{\"QTbqygYQKvgCtMA8rWLARN6jpE6Ha2YYsW\":0.10000000,\"QTbqygYQKvgCtMA8rWLARN6jpE6Ha2YYsW\":0.10000000,\"Qg7DfM87ovAVfJdt4CbmjHzeLfSAetrWRx\":0.24805273}"
error code: -8
error message:
Invalid parameter, duplicated address: QTbqygYQKvgCtMA8rWLARN6jpE6Ha2YYsW

```

**Comment by jonasschnelli** [comment]
It's currently not supported. Also, in JSON, re-using keys in an Object seems not to make sense.

Maybe try to use `bitcoin-tx`?

**Comment by promag** [comment]
FYI #12419.

> I want to divide input to many output for the same address in order to send for next time eazily

What do you mean?

**Comment by passionofvc** [comment]
hi @promag 

 for example [1], send 100BTC to A below
 1 send 20BTC -->A
 2 send 20BTC -->A
 3 send 20BTC -->A
 4 send 20BTC -->A
 5 send 20BTC -->A
next when send 10BTC use output of A to C,
I just use 5th output, and other output can use in another send.

for example [2], send 100BTC to A below
1 send 100BTC->A

next when send 10BTC use output of A to C,
I can use 1th output, but  the remain 90BTC can not use until send from A to C tx finished.

**Comment by promag** [comment]
But what is the problem of using different addresses? Or why do you want to use the same address over and over?

**Comment by passionofvc** [comment]
hi @promag 
the A address is my customer address,I can not create new address every time,
when send bitcoin to my customer A, because the customer address can not change.

**Comment by kristapsk** [comment]
> I can use 1th output, but the remain 90BTC can not use until send from A to C tx is finished.

That's not true. You can use outputs from unconfirmed transactions as inputs for new transactions. And then first and second transactions will be confirmed together or the second one will be confirmed at some point after the first, depending on the fees.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
