### ISSUE TITLE
Bitcoin Qt 0.16.0 displays a window title in Chinese instead of English

### ISSUE THREAD

**Issue by dimitris-t** [bitcoin/bitcoin#12544]
I get a bogus window title when clicking on the recipient address selector in the Send dialog. The window title appears to be in Chinese instead of English:

![screen shot 2018-02-26 at 9 14 25 pm](https://user-images.githubusercontent.com/8949706/36690376-c9d2402a-1b3a-11e8-80ca-9b67a3d66d81.png)

This is fully reproducible with Bitcoin Qt 0.16.0 64-bit on macOS Sierra 10.12.6 and Windows 7 x64, both with a US locale. Binaries downloaded from https://bitcoin.org/en/download

1. Click on the Send button.
2. On the Pay To line, click on the first of three icons. The one that resembles an address book.
3. Observe the window title.

**Comment by keystrike** [comment]
I have the same issue on Windows 8.1 x64 with a US locale. This window is also accessible from the sign/verify message window.

**Comment by anduck** [comment]
Source of the problem: https://github.com/bitcoin/bitcoin/blob/0.16/src/qt/locale/bitcoin_en_US.ts

**Comment by drodil** [comment]
Pull request for fix: https://github.com/bitcoin/bitcoin/pull/12558

**Comment by Michagogo** [comment]
https://github.com/bitcoin/bitcoin/blob/0.16/src/qt/locale/bitcoin_en_US.ts#L46,L50

**Comment by laanwj** [comment]
Thanks for reporting, that was one crappy translation (surprised this wasn't found in the rc phase), fixed through ea2e39fd2004e83375c1703543e32a10e3b9d981 which will be in 0.16.1.
