### ISSUE TITLE
getinfo + bt core 0.16 information

### ISSUE THREAD

**Issue by tmany** [bitcoin/bitcoin#12548]
Hello.
Everybody knows, that getinfo in new 0.16 was deprecated. But my project uses getinfo in json-rpc-php. All my php code based on getinfo.
I have a question - is 0.16 working with getinfo? Or I shouldn't update to 0.16?
Because I don't know, can I update to 0.16. If getinfo is really fully deprecated from all sources, I won't update, because my php part (website) doesn't work.
Can you help me? And explain?
Thanks

**Comment by tmany** [comment]
Or I can use -getinfo instead of getinfo in my php sources? As was described here https://github.com/bitcoin/bitcoin/issues/11671 ?

**Comment by achow101** [comment]
The `getinfo` RPC command has been fully removed from Bitcoin Core. `-getinfo` is an argument to the `bitcoin-cli` tool and is not useful to you. You should upgrade your software to use the RPC commands that have replaced `getinfo` as detailed here: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.14.0.md#getinfo-deprecated

**Comment by laanwj** [comment]
Seems answered by @achow101. You need to replace `getinfo` with the appropriate `get*info` command for whatever info you're trying to find.
