### ISSUE TITLE
How can I add function at other file?

### ISSUE THREAD

**Issue by leegod** [bitcoin/bitcoin#12552]
I am using ubuntu within VirtualBox from windows10. 

For example, how can I use "CheckProofOfWork" function from pow.cpp at chainparams.cpp? 

I added #include "pow.h" at chainparams.cpp, but after this and when I tried compile with 'make' at terminal, error says there is no definition of that function...

Is this C++'s linker problem? Then how to solve this?

**Comment by sipa** [comment]
This is a place to report issues, not for learning basic C++.

You may find help on sites like stackoverflow.

**Comment by leegod** [comment]
Hm.... there is no place to ask. I listed same question to stackoverflow, but there is no answer and just received 'close question' request 3 times...  Too harsh.
