### ISSUE TITLE
Bitcoin core 0.16.0rc3 importmulti works with Bech32 segwit! 

### ISSUE THREAD

**Issue by AdamSEY** [bitcoin/bitcoin#12554]
As that answer in [here](https://bitcoin.stackexchange.com/questions/71495/failed-to-import-bech32-segwit-addresses-using-importmulti-bitcoin-core-0-16-0rc)

> As noted in the Bitcoin Core 0.16 release notes, `importmulti` does not support SegWit addresses yet. This will be fixed in an upcoming release.

I've tried to import watch-only segwit bech32 address using `importmulti` and it did work! Sounds great to me But, if not fixed yet how did it work?

I've tried to import addresses as follows:

```
./src/bitcoin-cli  importmulti     [
    {
        "scriptPubKey" : { "address": "tb1qh2sdesazn9ac34xk3qt4d2jn0vhd993hjrkk9h" },
        "timestamp" : "now",
        "watchonly" : "true"
    }
  ] ,  { "rescan": false }

```

Response: {"success":true}

**./src/bitcoin-cli listtransactions "" 10 0 true**
```
[
  {
    "involvesWatchonly": true,
    "account": "",
    "address": "tb1qh2sdesazn9ac34xk3qt4d2jn0vhd993hjrkk9h",
    "category": "receive",
    "amount": 0.10000000,
    "label": "",
    "vout": 0,
    "confirmations": 0,
    "trusted": false,
    "txid": "48089a814ac571944feb7162cc0145eea4e72742aa51f6f23d470debd838eeb3",
    "walletconflicts": [
    ],
    "time": 1519713147,
    "timereceived": 1519713147,
    "bip125-replaceable": "yes"
  }
]
```

**Comment by promag** [comment]
Related to #12253.
