### ISSUE TITLE
[0.16]: Compiling warnings while compiling bitcoin-qt, tx ...

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#12566]
Hello,

While I'm compiling Bitcoin on my 16.04 Ubuntu, I get some warnings.
It seems, that while all executable files where compiled, I get these errors.

You can see a full output in the .txt file.

Regards.
[output-btc.txt](https://github.com/bitcoin/bitcoin/files/1767772/output-btc.txt)

**Comment by randolf** [comment]
This looks like a problem with Boost libraries.  Maybe a version mismatch?  I've had problems with Boost in the past where they broke backward compatibility.

Does the compiled code seem to execute correctly?

**Comment by globaltoken** [comment]
Yes, the Wallet works fine, and this are just warnings for the Code.
But in older Versions like 0.15 I never received such warnings.

**Comment by fanquake** [comment]
These and similar warnings have been appearing in gitian builds for some time.
