### ISSUE TITLE
deprecation-warning and errors without getinfo

### ISSUE THREAD

**Issue by tmany** [bitcoin/bitcoin#12579]
Hello. Guys, help me, In 0.16 how can I check from bitcoin-cli 'deprecation-warning' "errors" and other dev information? In 0.15 this info was in getinfo.  And now, with deprecated getinfo how can I check errors?

**Comment by achow101** [comment]
`errors` are available in `getinfo`'s replacements: `getblockchaininfo`, `getnetworkinfo`, `getminininfo`, and `getwalletinfo`. `deprecation-warning` is specific only to `getinfo` warning about its deprecation.
