### ISSUE TITLE
Bitcoin 0.15.1 malloc() error in OpenBSD 6.2amd64

### ISSUE THREAD

**Issue by amore-amore** [bitcoin/bitcoin#12576]
Tried to build bitcoin 0.15.1 under OpenBSD 6.2amd64 as gmaxwell recommended to test malloc() error (Issue #12332). The bug with memory management is the same.

While running bitcoind I get this:

bitcoind(23145) in free(): chunk is already free 0x1392d44e9a90
Abort trap (core dumped)

**Comment by laanwj** [comment]
I don't remember seeing this issue and I run OpenBSD nodes.
Is there anything specific you to do to reproduce this?

**Comment by fanquake** [comment]
@amore-amore Have you retried with 0.16.0 at all?

**Comment by jb55** [comment]
@amore-amore following up again, you get a chance to test this again on the latest version?
