### ISSUE TITLE
Bitcoin-Qt defaulted to 3sat/byte fee, resulting in unconfirmed transaction

### ISSUE THREAD

**Issue by fbriggs** [bitcoin/bitcoin#12571]
I tried to send ~0.5 BTC to another address from the Bitcoin-Qt app.
I used the default settings for transaction fee, and have never modified these settings since installing.
This resulted in a transaction with only 3 sat / byte fees: https://live.blockcypher.com/btc/tx/0a03f6d0245c5c1609dbd57f1b5e0aa1d6a90e0f177e5eac7123c0dd53a5a5b9/
This transaction got 0 confirmations after 3+ hours. Eventually I paid a transaction accelerator to confirm it.

3 sat/byte is way below the typical fee currently based on a few sites I checked. This transaction basically had no chance of confirming unless the mempool went to 0. Instead it locked up the funds in a state where it is difficult to recover, requiring either paying a transaction accelerator, or attempting a double spend. The default settings for fees should never do this; the default should guarantee success with high probability. A user should have to take some action to change the settings away from default to reduce the fee to a hazardous level such as this.

So far I have done two send transactions with the Bitcoin-Qt wallet. I didn't have a problem with the default fee on a different transaction, where the amount was much smaller.

I am running Bitcoin Core version v0.15.1 (64-bit) on OS X.

OS X.

**Comment by funyug** [comment]
The fees has been as low as 1sat/byte for the past few weeks so 3 sat/byte looks normal to me
You can check the mempool stats at https://jochen-hoenicke.de/queue/#1,2w

**Comment by fbriggs** [comment]
Some transactions are clearing at 1 sat/byte, but after how long, and what fraction of 1 sat/byte transactions are removed from the mempool instead of ever clearing?  There is no way for a user to know if its going to be dropped  or eventually confirmed, or see if it is in any way advancing in priority in the mempool. If it does get dropped, recovering with a double spend is a complicated process, beyond the capabilities of most users. It's fine if advanced users want to subject themselves to this delay and risk by manually configuring a lower fee, but should this really be the default? I would suggest to default to spending a few extra cents to avoid any chance of having 0.5BTC stuck in limbo. Even if only 1% of users are experiencing these unconfirmed transactions as a result of this low default, it is still very bad for mass adoption, because it is a potentially souring experience. A user who loses $5000 USD due to an unconfirmed transaction is never coming back, and will spread their horror story to others.

**Comment by Willtech** [comment]
May I suggest, if it is not already the case, that the project could be well served if the default for fee selection is to use recommendations with a 2 block target confirmation?

**Comment by WorkShop-Office** [comment]
How to ?



Sent from my Redmi 4A
On Willtech <notifications@github.com>, Mar 2, 2018 6:29 PM wrote:

May I suggest, if it is not already the case, that the project could be well served if the default for fee selection is to use recommendations with a 2 block target confirmation?

**Comment by kristapsk** [comment]
There is "Confirmation time target" dropdown in fee selections with "20 minute(s) (2 blocks)" option. That should give 20+ sat/B fee currently.

**Comment by jnewbery** [comment]
It's not clear to me that there's an issue here. The prevailling fee rate for the last couple of months has been as low as 1 sat/byte, so this seems like a reasonable fee rate to set on a transaction.

> Instead it locked up the funds in a state where it is difficult to recover, requiring either paying a transaction accelerator, or attempting a double spend

There are a couple of ways to get a transaction unstuck: Replace-by-fee and child-pays-for-parent. I suggest you take a look at those.

I'm going to close this issue, but if you think there's a genuine bug, feel free to re-open with additional information.
