### ISSUE TITLE
[depends] Crosscompile from trusty to osx

### ISSUE THREAD

**Issue by headhunter911** [bitcoin/bitcoin#12577]
When attempting to compile bitcoin from master source I run into two problems.  One is a boost lib location error which i fix by adding a absolute file path in depends/x86_64-apple-darwin11/share/config.site
this:
-  depends_prefix="`dirname ${ac_site_file}`/.."

to this:
+ depends_prefix="/home/user/osx/bitcoin/depends/x86_64-apple-darwin11"`

My second problem is in the make process, i get a clang linker error.

Compile bitcoin for osx

Errors

Everytime

Branch Master

Ubuntu 14.04 Trusty

My steps I take:
1. cd depends with SDK already added
2. make HOST='x8664-apple-darwin11'
3. cd ..
4. ./autogen.sh
5. change config.site as noted above
6. CONFIG_SITE=depends/x86_64-apple-darwin11/share/config.site ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --with-gui
7. make
8 end at this error:
  CC       src/libsecp256k1_la-secp256k1.lo
CCLD     libsecp256k1.la
make[3]:` Leaving directory `/home/smyers/osx/bitcoin/src/secp256k1'
  CXXLD`    libbitcoinconsensus.la
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
ld: file was built for archive which is not the architecture being linked (x86_64): secp256k1/.libs/libsecp256k1.a for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: Leaving directory `/home/smyers/osx/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/smyers/osx/bitcoin/src'
make: *** [all-recursive] Error 1
smyers@headhunter911-trusty:~/osx/bitcoin$ 

config.log:  https://pastebin.com/Rf6B5Ry4

**Comment by headhunter911** [comment]
I fixed the first issue by putting a absolute path in step 6, example
CONFIG_SITE=/home/user/osx/bitcoin/depends/x86_64-apple-darwin11/share/config.site ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --with-gui

**Comment by headhunter911** [comment]
That ended up fixing both problems.  Thanks.

**Comment by headhunter911** [comment]
Ok so now i have successfully compiled everything but i am running into a problem here (make deploy):
/bin/mkdir -p Bitcoin-Qt.app/Contents
/usr/bin/install -c -m 644 share/qt/Info.plist Bitcoin-Qt.app/Contents/Info.plist
make -C src qt/bitcoin-qt
make[1]: Entering directory `/home/smyers/osx/bitcoin/src'
make[2]: Entering directory `/home/smyers/osx/bitcoin/src/secp256k1'
make[2]: `libsecp256k1.la' is up to date.
make[2]: Leaving directory `/home/smyers/osx/bitcoin/src/secp256k1'
make[1]: Leaving directory `/home/smyers/osx/bitcoin/src'
INSTALLNAMETOOL=/home/smyers/osx/bitcoin/depends/x86_64-apple-darwin11/share/../native/bin/x86_64-apple-darwin11-install_name_tool  OTOOL=/home/smyers/osx/bitcoin/depends/x86_64-apple-darwin11/share/../native/bin/x86_64-apple-darwin11-otool STRIP=/home/smyers/osx/bitcoin/depends/x86_64-apple-darwin11/share/../native/bin/x86_64-apple-darwin11-strip /usr/bin/python3.4 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -translations-dir=/home/smyers/osx/bitcoin/depends/x86_64-apple-darwin11/share/../translations -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -verbose 2
+ Removing old dist folder +
+ Copying source bundle +
+ Deploying frameworks +
**Warning: Could not find any external frameworks to deploy in dist/Bitcoin-Qt.app.
Warning: Could not detect Qt's path, skipping plugin deployment!**
+ Installing qt.conf +
+ Adding Qt translations +
+ Done +
/bin/mkdir -p dist/.background
/usr/bin/tiffcp -c none dpi36.background.tiff dpi72.background.tiff dist/.background/background.tiff
/usr/bin/python3.4 contrib/macdeploy/custom_dsstore.py "dist/.DS_Store" "Bitcoin-Core"
/home/smyers/osx/bitcoin/depends/x86_64-apple-darwin11/share/../native/bin/genisoimage -no-cache-inodes -D -l -probe -V "Bitcoin-Core" -no-pad -r -dir-mode 0755 -apple -o Bitcoin-Core.dmg dist
/home/smyers/osx/bitcoin/depends/x86_64-apple-darwin11/share/../native/bin/genisoimage: Warning: assuming PC Exchange cluster size of 512 bytes
 29.81% done, estimate finish Sun Mar  4 14:09:59 2018
 59.63% done, estimate finish Sun Mar  4 14:09:59 2018
 89.35% done, estimate finish Sun Mar  4 14:09:59 2018
Total translation table size: 0
Total rockridge attributes bytes: 3197
Total directory bytes: 13084
Path table size(bytes): 118
Max brk space used 0
16794 extents written (32 MB)

**Comment by Sjors** [comment]
If you do find a solution, I'm happy to test it (with a Trusty Virtual Box running on macOS).

**Comment by headhunter911** [comment]
Thanks, did you test what I described and have the same problem?

**Comment by MarcoFalke** [comment]
Depends are now built on bionic. Please open a new issue if you can still reproduce on bionic.
