### ISSUE TITLE
v0.16.0rc4 crashes

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12592]
v0.16.0rc4 on Fedora 27

After probably several hours v0.16.0.rc4 crashes. I have observed this only (that I can confirm) in the past two days.

The first time it was loaded on login and I came back to my PC and it was gone from the tray so, I restarted it from the command line.

The second time I do not recall if I left the window open or if it was running in the tray (topicons-plus) however, I this time have an error message in the console:

    >bitcoin-qt
    Gdk-Message: Error 22 (Invalid argument) dispatching to Wayland display.
    >

Nothing useful in `debug.log`

Obviously, I will now try v0.16.0 release.

**Comment by fanquake** [comment]
@Willtech Any follow up after trying 0.16.0?

**Comment by Willtech** [comment]
@fanquake has not happened again yet but I have a few edge cases still to try.

**Comment by Willtech** [comment]
@fanquake I cannot figure out how to replicate this. Has not happened again since with v0.16.0.

**Comment by fanquake** [comment]
@Willtech Thanks for following up, lets close this for now then.
