### ISSUE TITLE
Add RPC to set change/reserve status for addresses

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12595]
I'm trying to merge wallet files together using RPC API calls. It seems that it is not possible to add addresses and mark them as change or as part of the key pool (reserve). The `importwallet` RPC call can do this. But it's not possible for existing addresses.

Also there should be a way to enumerate all addresses including reserve and to obtain the change/reserve flags for each address.

**Comment by achow101** [comment]
NACK. I don't think this is useful and it could be dangerous to allow people to do that.

> Also there should be a way to enumerate all addresses including reserve and to obtain the change/reserve flags for each address.

Use `dumpwallet`.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
