### ISSUE TITLE
Rescanning cannot be aborted by closing the GUI window

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12596]
This is about Bitcoin Core 15.1 on Windows. I assume the same issue still exists in the latest version because I did not see anything about it in the change log.

It is not possible to abort rescanning by closing the window using the "x" window button. If the "x" button is clicked the rescan does not terminate in any reasonable amount of time (I waited about a minute).

Also, if `bitcoind` is run in a console window and the console window is closed with the "x" button during rescanning then the process crashes instead of shutting down gracefully. If I remember correctly it displays an assertion failure message box.

**Comment by GSPP** [comment]
In v16.0 this still does not work and pressing `q` does not help either.

**Comment by promag** [comment]
@GSPP can you try with master?

**Comment by GSPP** [comment]
I cannot compile the project. I can wait for the next official release and test.

**Comment by promag** [comment]
@jonasschnelli can you provide a build?

**Comment by MarcoFalke** [comment]
The nightly builds are on https://bitcoin.jonasschnelli.ch/#nighly

**Comment by GSPP** [comment]
Tested the latestest nightly. It now closes immediately. I tested the window "x" and the key "q". I also tested bitcoind and closing the console window. All OK.

**Comment by promag** [comment]
Great @GSPP, care to close the issue then?
