### ISSUE TITLE
Add RPC to set transaction comment

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12594]
I'm trying to merge wallet files together using RPC API calls. It seems that it is not possible to edit the label of a wallet transaction. The GUI appears to be able to do this. I request this as a new feature.

There's a difference between labeling the receive/send address and labeling the transaction. This is because there can be multiple transactions to/from the same address. So there's still a need to label transactions in contrast to simply labeling addresses using the accounts feature.

**Comment by GSPP** [comment]
In fact I just found out that it is not possible to use `SetAccount` on addresses not owned by the wallet. This means that there is no way to set a label to an outgoing transaction through the RPC interface (or any means at all programmatically).

Maybe `SetAccount` should allow setting a label? I don't know but there should be a way to label outgoing transactions.

**Comment by jnewbery** [comment]
#7729 adds the functionality to set a "send" label on an address that does not belong to the wallet. Please test/review that PR if you want to help get this functionality merged!

**Comment by promag** [comment]
#7729 was replaced by #12892, see `setlabel`.

**Comment by jnewbery** [comment]
I've updated the issue description to refer to transaction _comment_. Labels are associated with addressed. Comments are associated with transactions.

(Note that the accounts API is deprecated in 0.17 and removed in 0.18. It is replaced by the labels API).

@GSPP - is this feature still wanted?

**Comment by jonasschnelli** [comment]
There is a very old/closed PR of mine that did that on the GUI level (in case someone needs inspiration):
https://github.com/bitcoin/bitcoin/pull/5905

**Comment by GSPP** [comment]
Yes, this is still wanted. I very much need read and write access to all the wallets data structures for merging them properly.

To me it seems transactions are lacking a key that can be used to identify them over the API. I have not found any combination of fields that uniquely identifies a transaction. In the case of self transactions there can be almost all fields duplicated including TxID and vout.

**Comment by pinheadmz** [comment]
@GSPP `txid` by definition is a unique identifier for a transaction. Comments can be added to new transactions in some RPCs like `sendtoaddress` and those comments are visible in the GUI. What do you need? The ability to edit a transaction comment in the GUI?
