### ISSUE TITLE
A question to the chain data

### ISSUE THREAD

**Issue by elonmuskismyhero** [bitcoin/bitcoin#12590]
![default](https://user-images.githubusercontent.com/36603128/36934791-915eade4-1f29-11e8-9a82-023a21b7787a.png)
I got a question when I analyzed the blockdata recently. The picture shown above is part of a block. As we can see, it should be the sums of all the transaction after the header of the block which here was FD B9 05, and then version number 01 00 00 00. Now comes the question. The next byte is usually 01 which represents the amount of input of the coinbase. But I found three bytes 00 01 01.  I can't understand it. Can anybody explain it?

**Comment by sipa** [comment]
You're seeing a segwit block. Read BIP141 and BIP144 for a description.

In the future, take these questions to bitcoin.stackexchange.com or other fora. This is a place to report issues, not a helpdesk.
