### ISSUE TITLE
Addresses losing accounts

### ISSUE THREAD

**Issue by theymos** [bitcoin/bitcoin#12608]
There seems to be some sort of bug related to accounts (which I know you intend to deprecate at some point, but still exist). Bitcointalk.org uses the used-to-be-standard accounts pattern of `getaccountaddress <account>` & `getbalance <account>`. Upon upgrading from to 0.16.0, it seems that about 10% of addresses given out by `getaccountaddress X` later do not have their account assignment anymore. They aren't reflected in the `getbalance X` balance, and the account does not show up in `validateaddress`.

I haven't tracked down exactly where the account assignment gets lost. Maybe it's sometimes never made, or maybe it's lost after a while. In some cases, getaccountaddress might've been called twice in quick succession on the same account, so maybe there's a concurrency issue. 

I'm just going to take this opportunity to get rid of accounts usage. Though I suppose that other people will run into this problem, since it was the standard pattern which everyone recommended using from about 2011 to 2015.

**Comment by laanwj** [comment]
Thanks for reporting.

This is a really strange issue, and somewhat scary, though I agree with your assessment that at this point we should just move forward to remove it.

**Comment by MarcoFalke** [comment]
Could you check if this also happens with labels, using the 0.17.0 release (not yet released or branched off)
