### ISSUE TITLE
Example destination address in send tab of bitcoin-qt is pay-to-pubkeyhash instead of pay-to-script-hash

### ISSUE THREAD

**Issue by bill-walker** [bitcoin/bitcoin#12601]
https://github.com/bitcoin/bitcoin/pull/12599

The example destination address in send tab of bitcoin-qt is pay-to-pubkeyhash instead of pay-to-script-hash.

I expected to see a pay-to-script-hash address with an invalid checksum to prevent people from sending to it.

Instead of this, i saw a P2PKH address.

Run the official binary for bitcoin-qt to reproduce the issue.

Observed on linux 64 bit.

Pull request fixes the problem. Is it safe to merge?

**Comment by MarcoFalke** [comment]
Yes, let's wait for review on the pull request.
