### ISSUE TITLE
gui: default port not shown correctly in settings dialog

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#12623]
![screenshot 2018-03-06 at 4 11 21 pm](https://user-images.githubusercontent.com/863730/37058653-389cddc0-2159-11e8-9b02-f4cbc5fe30d7.png)
Using 20e3b9a485fd6b23785c5caa49d01ea49fdc8bcf. Should obviously be 9050, not %2.

**Comment by Willtech** [comment]
Previously noted in PR [11809](https://github.com/bitcoin/bitcoin/pull/11809)

**Comment by Sjors** [comment]
Fixed, see #11809.
