### ISSUE TITLE
Add a way to skip rescanning on startup

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12632]
I sometimes need to attach different wallets to my Bitcoin Core instance only to use certain RPC calls. I do not need up to date transaction or balance information. Basically I only want to perform `dumpwallet`. Would it be feasible to add a startup mode where rescanning and other optional work is skipped? Maybe block verification could also be skipped.

Rescanning takes about 2h on my fairly recent CPU on an SSD. It would be very useful if this step could be skipped.

**Comment by laanwj** [comment]
> Maybe block verification could also be skipped.

At the least use `-listen=0 -connect=0`, so that no new blocks can come in.

**Comment by promag** [comment]
What is preventing calling `dumpwallet`? Maybe the fix is to make it possible instead of adding `-nowalletupdates`?

**Comment by promag** [comment]
What version are you using?

**Comment by GSPP** [comment]
`dumpwallet` cannot be called until the initial rescan is done. Not sure if this was 0.15.1 or 0.16 but I don't think there was any change here.

Looks like this will be implemented. Nice!

**Comment by promag** [comment]
@GSPP do you confirm you are able to call `dumpwallet` during the initial rescan in 0.16?

**Comment by GSPP** [comment]
I don't have a test environment handy at this point in time but I said it was *not* possible to call `dumpwallet`. Maybe you misread. I'm quite certain it was not possible.

**Comment by jonasschnelli** [comment]
I just started Bitcoin-Qt (official 0.16 release) with `--datadir=/tmp` and called `dumpwallet`... seems to work fine. I fail to see the issue here...

**Comment by GSPP** [comment]
@jonasschnelli does this not use an empty data dir? There's nothing to rescan. Use a fully synced node and change the wallet to make it rescan for a long time.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
