### ISSUE TITLE
Error 10053 and code -22 transaction too big?

### ISSUE THREAD

**Issue by number9387** [bitcoin/bitcoin#12645]
When using bitcoin.json package for python and querying a fully up to date bitcoin core wallet, some transactions respond with

> File "....bitcoinrpc\authproxy.py", line 114, in __call__
response = self._get_response()
File "...bitcoinrpc\authproxy.py", line 134, in _get_response
http_response = self.__conn.getresponse()
File "...httplib.py", line 1136, in getresponse
response.begin()
File "...httplib.py", line 409, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "...socket.py", line 488 in readline
data = self._sock.recv(self.rbufsize)
socket.error: [Errno 10053] An established connection was aborted by the software in your host machine

I get this for a number of transactions including https://blockchain.info/tx/dca4ac54fc9a63434daa60fda4cf4b6f176c2660a00b481edc3530a6bf5e49e1  

This does not occur with all transactions.  

When I try to decoderawtransaction in the debug window and place the hex of that transaction from the block explorer, I am met with a "TX decode failed (Code -22)" and that's from a cut and paste of the raw transaction.  Though it should be noted that I can clearly see in the debug window that it didn't accept the full pasted raw transaction, only part of it.  Seeming to suggest a deliberate max size that the debug window will accept.  Copying and pasting the same raw transaction into microsoft word copies the whole transaction, demonstrating it is not some strange limit on the clipboard size itself.

Considering the size of the transaction and the problem of "MAXLINE + 1" leads me to think it may ahve something to do with the size of the transaction.

**Comment by jnewbery** [comment]
Can you paste the raw transaction here?

**Comment by MarcoFalke** [comment]
>  socket.error: [Errno 10053] An established connection was aborted by the software in your host machine

Let's continue discussion in #18623
