### ISSUE TITLE
[gui] close to tray not working

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12642]
v0.16.0 on Fedora 27 with topicons-plus

`bitcoin-qt` does not usually close to tray after restore from tray when clicking `x` or right clicking on the application in the taskbar and clicking on close. Using those methods in the case stated, nothing happens.

To workaround, a) minimise then restore the gui window or, b) maximise the window, and, then click close or, minimise again and it goes to the tray.

**Comment by hebasto** [comment]
Is that still an issue?

**Comment by Willtech** [comment]
No longer an issue in v0.18.0rc4 and think it was fixed in v0.17 or earlier.
