### ISSUE TITLE
walletversion 159900

### ISSUE THREAD

**Issue by tmany** [bitcoin/bitcoin#12655]
Hi, answer, please. I've just updating from 0.15.1

walletversion => 159900
warnings: "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"

How can I update to the last uptodate vestion? 0.16.0 already exists?

Thanks.

**Comment by Varunram** [comment]
@tmany Yes, 0.16.0 is out and can be downloaded at https://github.com/bitcoin/bitcoin/releases/tag/v0.16.0

**Comment by tmany** [comment]
Yes, but I have already updated to 0.16.0 a ~week ago. But still receive this warning.

**Comment by sipa** [comment]
The walletversion reports the software version your wallet was created with. It won't automatically change when upgrading.

When you're running a release, you should not see the "This is a pre-release test build" however.

**Comment by MarcoFalke** [comment]
> Yes, but I have already updated to 0.16.0

@tmany Where did you get the binary from? Is it self compiled?

**Comment by jnewbery** [comment]
No response. Closing.

Please comment if this is still an issue for you and we can reopen.
