### ISSUE TITLE
Serbian Translation / Cyrillic and Latin - Needs better distinction on Transifex 

### ISSUE THREAD

**Issue by nedvedp** [bitcoin/bitcoin#12657]
On Transifex, Serbian language has two options:

- Serbian Latin (sr@lat)
- Serbian (sr) - which is Cyrillic but the label is unclear.

Unfortunately there are plenty of overlaps of people writing Latin in Cyrillic and vice-versa. I am wiling to clean this up, but are there ways to either give a clearer label instead of (sr) for Cyrillic as it is obviously causing plenty of confusion among translators. 

Both are the official styles of writing.

Furthermore, is there a way to get in touch with coordinators as they appear to be inactive? I do not see much progress. I am willing to work on this, but I'd need help from coordinators or have a coordinator access in order to work on it properly. I'm doing same work for bitcoin.org 
I am user [nedved](https://www.transifex.com/user/profile/nedved/) on Transifex.
Thank you.

**Comment by laanwj** [comment]
> Unfortunately there are plenty of overlaps of people writing Latin in Cyrillic and vice-versa. I am wiling to clean this up, but are there ways to either give a clearer label instead of (sr) for Cyrillic as it is obviously causing plenty of confusion among translators.

I don't think we can change the labels for the languages. These are part of the Transifex website.

> Furthermore, is there a way to get in touch with coordinators as they appear to be inactive? I do not see much progress. I am willing to work on this, but I'd need help from coordinators or have a coordinator access in order to work on it properly

I've also wondered this. I don't know much about transifex besides the API. I don't know how to set coordinators etc.
Maybe @luke-jr does?

**Comment by nedvedp** [comment]
Hey @laanwj thanks for clarification. I would like to work on Serbian translation, but I'd either need a better communication with whoever the coordinator is or just an access. I've made good progress so far, but unfortunately I can't publish the changes besides the review of the person in charge, at least as far as I know.

**Comment by laanwj** [comment]
So the project coordinator on Transifex is https://www.transifex.com/user/profile/seone/
I've asked to give the same access to me, but he doesn't seem to be very communicative. At some point I don't really know how to fix this besides move to a different transifex org (we have https://www.transifex.com/bitcoincore/). But he's the only one that can assign team permissions, AFAIK.

**Comment by luke-jr** [comment]
I can add a "project maintainer", but I'm not sure how that compares with "coordinator"...

What do you need coordinator access to do? Maybe one of us can do it as proxy, even if we can't add it?

**Comment by nedvedp** [comment]
@luke-jr I just want to be able to publish the translated changes or to have someone review/confirm them as the person with that access appears to have abandoned the project. 

If a project maintainer can do that, we can give it a try. The main fear I have is that my work and possibly work of others in future will remain locked out in Transifex, because nobody besides inactive coordinator can review the changes. If we can have more people with the access to review and publish changes, it would be less centralized and we would not depend on the single person.

**Comment by jarolrod** [comment]
@nedvedp @laanwj Can this be closed. The stated issues with access to transifex seems to be resolved. The [Transifex Serbian Page](https://www.transifex.com/bitcoin/bitcoin/language/sr/) shows 100% for Bitcoin Core 0.20 and ~90% for Bitcoin Core 0.21.
