### ISSUE TITLE
Add me to bitcoin GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [bitcoin/bitcoin#12667]
Hey,

I am really excited about the active development and wanted to be a part of the **bitcoin** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is **YoginthS**

Thanks, [Yoginth](https://yoginth.ml)

**Comment by fanquake** [comment]
You do not have to be a member of the GitHub organisation to begin contributing. Feel free to open issues, or creating PRs with code you have written.

**Comment by luke-jr** [comment]
You don't need to be a member to get involved. Just begin contributing. Regular contributors are added as organisation members (but this doesn't carry any special privileges or anything like that).

**Comment by YoginthS** [comment]
But being a member adds me a special point as a contributor! in my profile

**Comment by MeshCollider** [comment]
@YoginthS I think you should focus on actually becoming a contributor as suggested above before you request to be labelled as one on GitHub :)
