### ISSUE TITLE
configure: error: No working boost sleep implementation found.

### ISSUE THREAD

**Issue by ValeryDubrava** [bitcoin/bitcoin#12663]
Configure failed in Centos 7.

```
uname -a
Linux myhost 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

configure result: [https://gist.github.com/ValeryDubrava/477268c1bc0507d0cd0c9a3f37f1138d](https://gist.github.com/ValeryDubrava/477268c1bc0507d0cd0c9a3f37f1138d)

**Comment by eklitzke** [comment]
You need to install (or update) boost::thread.

**Comment by ValeryDubrava** [comment]
Could you please tell me what is minimal version?

**Comment by eklitzke** [comment]
There are checks in the `configure.ac` that you can use to see what it's checking for. It looks like you need at least version 1.52.

**Comment by fanquake** [comment]
The minimum required Boost should be [1.47.0](https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L793).

**Comment by ValeryDubrava** [comment]
I've installed boost 1.53 (with devel). There is the installation [log](https://gist.github.com/ValeryDubrava/93e476276690cf8b17d796e10f1c1fd9).

**Comment by jnewbery** [comment]
@ValeryDubrava - did installing boost::thread resolve your issue? Are you happy to close this?

**Comment by fanquake** [comment]
Going to close since there has been no followup. @ValeryDubrava Feel free to re-open with more information.
