### ISSUE TITLE
Bitcoin Core v0.16.0. Master Private key (hdkeypath=m) not same as into Extended Private Key (xprv)

### ISSUE THREAD

**Issue by bigbrain** [bitcoin/bitcoin#12669]
Hello,
I think I found error in last version Bitcoin Core (v0.16.0 windows). In the v0.14.2 was all OK
Master Private key (hdkeypath=m) not same as into Extended Private Key (xprv).

For example:
-
Extended Private Key:
`xprv9s21ZrQH143K3tpWBHWe31sLoXNRQ9AvRYJgitkKxQ4ATFQMwvr7hHNqYRUnS7PsjzB7aK1VxqHLuNQjj1sckJ2Jwo2qxmsvejwECSpFMfC`

Contains Master Private key:
`L4Msh6UhbJibMKMGn3N6tewH6YJmYRiiv93idbwbwnzAvGEzLuFR`

But Bitcoin Core v0.16.0 set and use Master Key:
`L2kkvUrxC6FM8vKnKWpeRUH275oSDYi8ThP96htz88LLw95feHoP`

in Hex:
-
Extended Private Key:
`0488ade4000000000000000000b85def23bdc9db3791d9b8b3e47978c91e4acb7a9d3e3936c8df928323c4638d00d50fc580278e6a9429b41eee1df72ce021c3a67073df94258ab98cf6058d7fd880e46377`

Contains Master Private key:
`d50fc580278e6a9429b41eee1df72ce021c3a67073df94258ab98cf6058d7fd8`

But Bitcoin Core v0.16.0 set and use Master Key:
`a528aa10067b45aad858eee62341097643f4d7fa9aca92cae8a2862618558400`

See: [Example Wallet Dump](https://mega.nz/#!psYC1RIB!Bu4fqDajvpbrzexVP1sUHad5SW04oTguj6SOxQ0Fu60)

This leads to problems with Bip32 compatibility, problems with xprv import, problems with keys and addresses derivation.

**Comment by MarcoFalke** [comment]
Related: #12084

**Comment by bigbrain** [comment]
Sorry guys. I'm stupid. My program failed. Please remove it.
