### ISSUE TITLE
How to debug RPC 500 Internal Server Error ?

### ISSUE THREAD

**Issue by congnghiakhiem** [bitcoin/bitcoin#12673]
walletpassphrase 
* About to connect() to 10.130.xx.xx port 8332 (#1)
*   Trying 10.130.xx.xx...
* Connected to 10.130.xx.xx (10.130.xx.xx) port 8332 (#1)
* Server auth using Basic with user 'xxx'
> POST / HTTP/1.1
Authorization: Basic xxx==
Accept: */*
Host: 10.130.xx.xx:8332
Content-Type: application/json
Content-Length: 113

* upload completely sent off: 113 out of 113 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Mon, 12 Mar 2018 05:34:31 GMT
< Content-Length: 984
< 
* Connection #1 to host 10.130.xx.xx left intact
NULL

I have set debug=rpc. But I've only got 2018-03-12 05:34:31 ThreadRPCServer method=walletpassphrase
How to find out the error ?

**Comment by laanwj** [comment]
Please ask questions about use of the RPC API on the [bitcoin stack exchange](https://bitcoin.stackexchange.com/), not on the bug tracker.
