### ISSUE TITLE
Transactions GUI list does not show a transaction from self to self+foreign

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12688]
For a certain transaction structure the GUI does not show all transactions that occurred.

Perform the following transaction structure to reproduce the bug:

Input: Any owned coins
Output 1: Address not owned by the wallet
Output 2: Address owned by the wallet (generated using the receive payment feature, so it's not a change address)

So there is a payment to someone else and a payment to self. The payment to self is missing in the GUI. Normally, the GUI does list payments to self.

`listtransactions` lists 3 transactions here: The send to the foreign address and a send/receive pair for the payment to self. I don't know if this is correct. I'm mentioning this so that the devs can make sure this is intended.

See transaction `5299f198919d6bd5b9f6d7a5f256b23417cb49ea663828f51cfc1b4d7e69822d` on testnet.

**Comment by GSPP** [comment]
Another suspect situation:

Input: Own addresses
Output: 2 own addresses

Here, I think there should be 2 "Payment to yourself" rows in the transaction list. Instead, there is only one. The transaction details dialog for this row does not show address data. `listtransactions`, though, correctly reports 2 send/receive pairs (4 items in total).

I think it's important to be able to track self payments accurately in the GUI.

**Comment by Rav3nPL** [comment]
It is not GUI failure, `listtransactions `not show up incoming transaction when it is from wallet to existing (already used) address.
How to reproduce:
- create two addresses (A,B)
- send some coins on them
- send all coins from wallet: part to outside address, rest to one of (A,B) - NO CHANGE!

`listunspent `will show properly, `listtransactions `not.

**Comment by promag** [comment]
Does it make sense from the "accounting point of view" to list those movements? Currently all "is mine" outputs of sent transactions are seen as if they were change outputs.

**Comment by promag** [comment]
BTW, in #12578 a dedicated record for the fee is added. The same could be done for these edge cases.
