### ISSUE TITLE
Invalid or non-wallet transaction id

### ISSUE THREAD

**Issue by rockandruby** [bitcoin/bitcoin#12684]
I use bitcoind 16.0 in testnet mode on my local machine Linux MInt 18.3 
Here's my bitcoin.conf

> bind=0.0.0.0:18333
server=1
daemon=1
testnet=1
rpcuser=user
rpcpassword=pass
rpcport=18332
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

The problem is that I receive above error after each testnet transaction, however I can see this tx in testnet blockchain. Separately node works fine and donwloads blocks and I can even use some api like getnetworkinfo etc. Also I run simultaneously bitcoin_cash(on differrent port) and dash. Dash works fine but not btc/bch. I reinstalled core, tried different variations for confix but it didn't help. I even used txindex but no result. Please help.

**Comment by MeshCollider** [comment]
What command are you using when you get that error?

**Comment by rockandruby** [comment]
@MeshCollider hmm, I use get transaction for address transaction. So what's wrong? This works on my dev env, but not local.....

**Comment by laanwj** [comment]
Please use stack exchange for questions of use of the RPC API, not the bug tracker.

**Comment by nopara73** [comment]
@rockandruby Use `getrawtransaction` with `txindex=1`.
