### ISSUE TITLE
On testnet, a dumpwallet/importwallet cycle loses all labels

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#12698]
On testnet, a dumpwallet/importwallet cycle loses all labels and seems to mismanage addresses.

1. Receive some coins
2. Name the receving address in the transaction list GUI by clicking "Edit label"
3. dumpwallet
4. Make new wallet
5. importwallet

Notice, that the label is lost. Also, the "File->Receiving addresses" list shows a wrong address starting with `m...`.

This does work on mainnet.

Also, importwallet does not trigger a rescan on testnet but does on mainnet.

This is v0.16.0.

**Comment by MarcoFalke** [comment]
try `backupwallet` RPC
