### ISSUE TITLE
Enable -fsanitize flags in Travis

### ISSUE THREAD

**Issue by eklitzke** [bitcoin/bitcoin#12691]
This idea is from discussion in #12686 . GCC 4.8 supports two -fsanitize flags, `-fsanitize=address` and `-fsanitize=thread` (and newer versions support even more of these flags). It would be a good idea to enable these options in Travis. @sipa points out that the build still isn't completely clean when using these flags, so to add this we'd either have to fix all of the existing errors or some up with a whilelisting mechanism to grandfather the old violations.

**Comment by eklitzke** [comment]
I'm trying to add a configure option for this in #12692 .

I tested the Bitcoin test suite with various sanitizer configurations, and the Bitcoin test suite passes cleanly with the `thread` and `undefined` sanitizers, but there are serious issues with the `address` sanitizer that need to be resolved. The address sanitizer injects a segfault when errors occur, so enabling this in Travis is an all-or-nothing kind of thing.

**Comment by Empact** [comment]
Partially addressed in #14794
