### ISSUE TITLE
rpc: importmulti improvements

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#12703]
Some comments from @sipa in #12702.

___

Yes, I think `importmulti` is superior in every way, except:
* Slightly less convenient to use (it requires redundant information, as you have to explicitly state what you want to import, and then give the keys/... to enable that).
* ~Doesn't support P2SH-P2WPKH yet~. Added in #14454

The latter can be fixed by just adding support for that case. The former can be improved by adding 'default' cases (e.g. if you prove a WIF private key, it can permit omitting the address, ...).

**Comment by ryanofsky** [comment]
If this is supposed to be a bucked issue for importmulti improvments, #9332 is a simplification to `importmulti` that makes it less restrictive about accepting labels.

**Comment by jarolrod** [comment]
@fanquake @ryanofsky can this be closed? #9332 and #14454 appear to have addressed both bullet points and are now merged.

**Comment by ryanofsky** [comment]
Seems fine to close. It can be reopened if there's more discussion. Or more specific issues can be created. I don't think that the first bullet point's been addressed in any way since this was opened but it doesn't seem to be making a specific request.
