### ISSUE TITLE
bitcoind -help fails to mention options for -proxy

### ISSUE THREAD

**Issue by buzztiaan** [bitcoin/bitcoin#12726]
It turns out , that -proxy -does- support inline user:pass@host:ip format authentication, yet the help does not reflect this is an option. 

Suggesting to add such to the help :)

**Comment by murrayn** [comment]
> It turns out , that -proxy -does- support inline user:pass@host:ip format authentication

It does? I don't think so.

**Comment by buzztiaan** [comment]
This is what gave it away for me ; 

https://github.com/bitcoin/bitcoin/blob/6324c68aa017ceb48fe3edfb5a2b141fcf0090fa/src/netbase.cpp#L350

**Comment by murrayn** [comment]
Looks like the underlying Socks5() routine was written to conform to RFC1928 and RFC1929, which is good. But, no, the -proxy option doesn't support this (yet).
