### ISSUE TITLE
gui: in use `bitcoin.conf` file is not opened

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#12722]
v0.16.0 on Fedora 27

The in use `bitcoin.conf` file is not opened.

Move the .bicoin folder according to these steps: https://bitcoin.stackexchange.com/a/72608/75001

Open bitcoin-qt, go to Settings -> Options -> Open Configuration File

The in use configuration file is not opened. The GUI should open the in use file.

**Comment by jnewbery** [comment]
Yep, `openBitcoinConf()` in guiutil.cpp calls into `GetConfigFile()`, which calls into `AbsPathForConfigVal()`,  which uses the current datadirectory, rather than the conf file that was used.

**Comment by hebasto** [comment]
Tested the current master (446b706696451ae1a66ac416f347d734c5741d7c) on Linux Mint 20.2 and Fedora 34.

The "Open Configuration File" button opens a proper configuration file: either the default `bitcoin.conf` or one which is provided with the `-conf` command-line option.

I think this issue should be closed.
