### ISSUE TITLE
problem with creating genesis block.

### ISSUE THREAD

**Issue by 26rahulsingh** [bitcoin/bitcoin#12724]
can anyone help me with how can i creating genesis block in bitcoin 0.16.0.
Thank you.

**Comment by fanquake** [comment]
What do you mean by "creating a genesis block"?

**Comment by 26rahulsingh** [comment]
actually i'm creating new genesis block with nTime and nNonce.
i changed the CScript and pszTimestamp.

**Comment by laanwj** [comment]
We don't provide support for creating altcoins.
