### ISSUE TITLE
No bitcoin icon on Plasma Wayland session

### ISSUE THREAD

**Issue by stikonas** [bitcoin/bitcoin#12734]
I don't see Bitcoin icon (window icon) on Plasma Wayland session

Bitcoin icon is shown

Generic Wayland icon is used

I use Gentoo packages, they use desktop file from contrib folder

This issue could be fixed by renaming bitcoin-qt.desktop to org.bitcoin.bitcoin-qt.desktop

Arguably this can be done downstream, but I thought it might be useful for other contrib/ users

**Comment by fanquake** [comment]
This issue should be moved to the [packaging repository](https://github.com/bitcoin-core/packaging).
