### ISSUE TITLE
Use importaddress method with label,but I can't get balance of the address!Is always zero!

### ISSUE THREAD

**Issue by cyssxt** [bitcoin/bitcoin#12733]
When I use importaddress method with address and label,but I can't get balance of label!
The issue appears in the testnet！
1、issue
And I can  use listunspend method   to get all transaction about this address!

2、if i wanna to get balance of a address，do I need to traverse the result of listunspend?

3、

**Comment by MeshCollider** [comment]
Are you attempting to use `getbalance` with the label you provided?

**Comment by cyssxt** [comment]
yes，it's always zero

**Comment by cyssxt** [comment]
I had solve this issue！getbalance need the third param with value true to get balance of watch-only wallet

**Comment by jnewbery** [comment]
Thanks @cyssxt . Glad you resolved your issue.

**Comment by cyssxt** [comment]
Thanks!
