### ISSUE TITLE
Add systemd service for debian bitcoind package (contrib)

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#12758]
Please consider adding a systemd service to the debian bitcoind package in contrib, to provide a convenient and unified way to run bitcoind on boot.

(using the bitcoind.service from contrib)

**Comment by ctp-tsteenholdt** [comment]
Working on a proposed pull request right now

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Comment by MarcoFalke** [comment]
Actually looks like it has already been fixed:  #12769
