### ISSUE TITLE
[tests] Fix block size config in feature_fee_estimation.py, feature_maxuploadtarget.py and feature_pruning.py

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#12768]
#11100 broke the `-blockmaxsize` config, which these tests use.

Fix the tests by adding the appropriate `-blockmaxweight` config to the nodes in those tests.

(Note that #12756 removes the ignored `-blockmaxsize` config)

**Comment by fanquake** [comment]
Fixed in #12790
