### ISSUE TITLE
Malware detected in 16.0 windows 64

### ISSUE THREAD

**Issue by halfik** [bitcoin/bitcoin#12777]
Comodo Sercurity (www.comodo.com/) detects malware when installing bitcoin core from:
[https://bitcoincore.org/bin/bitcoin-core-0.16.0/bitcoin-0.16.0-win64-setup.exe](url)

[https://bitcoincore.org/bin/bitcoin-core-0.16.0/bitcoin-0.16.0-win32-setup.exe](url) looks ok.

Screen:
https://files.fm/thumb_show.php?i=jrn75uzu&view
Pls copy link dunno why it dosn't link properly,

PS. I also scaned it with malwarebytes.com software and nothing was detected.

**Comment by fanquake** [comment]
This is a false positive from your antivirus software, we see this issue semi regularly on Windows, ie #4069, #11852, #12320.
