### ISSUE TITLE
Minimal share difficulty in Wallet solo server configuration

### ISSUE THREAD

**Issue by Raito00** [bitcoin/bitcoin#12776]
I have in my wallet config like this:
rpcuser=myuser
rpcpassword=mypassw
rpcallowip=127.0.0.1
rpcport=4210
listen=1
server=1
addnode=nodeIP
addnode=nodeIP
addnode=nodeIP
addnode=nodeIP
#END 

QUESTION:
How can i add in config minimum share difficulty ?

**Comment by MarcoFalke** [comment]
The miner was removed long ago
