### ISSUE TITLE
After compile for windows, how to move -qt.exe file to windows working folder?

### ISSUE THREAD

**Issue by leegod** [bitcoin/bitcoin#12786]
So I followed windows build compile docs, it seems -qt.exe file generated in src/qt folder.

Currently my folder structure is like this, 

root@MyDesktop:/usr/src/bitcoin/src/qt#  

Yes so I git cloned at src folder. 

Now at this folder, src/qt#, there is -qt.exe file.

How to move this file to actual windows file explorer? For see and use it actually. 

Now I am in windows store downloaded Ubuntu environment terminal.

**Comment by laanwj** [comment]
The command for this is `make install`, make sure you pass a prefix to `./configure --prefix=/mnt/c/...` that is inside the windows mount.
