### ISSUE TITLE
Pay-to-self addresses don't display, can't be added to address book

### ISSUE THREAD

**Issue by jamesob** [bitcoin/bitcoin#12796]
Found in `master c948dc8f4285e27d8c0f3553d9d427b2a7b01b77`

An address generated by the wallet for receiving isn't displayed by the address book and can't be added. When the user attempts to add it, an error message is presented saying 'The entered address "..." is already in the address book.'

I'm unsure if this behavior is unintentional or not, but it's pretty confusing.

### Steps to reproduce

Generate a receiving address

![selection_008](https://user-images.githubusercontent.com/73197/37929024-c764dacc-310c-11e8-80cc-dd2d8127e988.jpg)

Open the address book from the send interface. Note that the previously generated address is missing.

![selection_009](https://user-images.githubusercontent.com/73197/37929056-dbd8a524-310c-11e8-93c0-5916aa1494ac.jpg)

Attempt to add the previously generated address

![selection_010](https://user-images.githubusercontent.com/73197/37929097-fa692d38-310c-11e8-9d8b-cd8208ce153e.jpg)

Hit warning

![selection_011](https://user-images.githubusercontent.com/73197/37929106-017740f6-310d-11e8-83c7-c2a2d1c09f75.jpg)

**Comment by jamesob** [comment]
Looks like this is a consequence of the address being entered  into `mapAddressBook` with `purpose="receive"` when the receiving address is created, and then [filtering address book display for `purpose="send"` rows](https://github.com/bitcoin/bitcoin/blob/c948dc8f4285e27d8c0f3553d9d427b2a7b01b77/src/qt/addressbookpage.cpp#L43-L47). We then [don't allow the addition of duplicate addresses](https://github.com/bitcoin/bitcoin/blob/c948dc8f4285e27d8c0f3553d9d427b2a7b01b77/src/qt/addresstablemodel.cpp#L357-L365) to the address book, even when the purposes differ.

One option is to simply not filter addresses for purpose when we're displaying the address book, e.g.
```diff
diff --git a/src/qt/addressbookpage.cpp b/src/qt/addressbookpage.cpp
index f2ddbf259b..16f96abb73 100644
--- a/src/qt/addressbookpage.cpp
+++ b/src/qt/addressbookpage.cpp
@@ -40,11 +40,6 @@ protected:
     {
         auto model = sourceModel();
         auto label = model->index(row, AddressTableModel::Label, parent);
-
-        if (model->data(label, AddressTableModel::TypeRole).toString() != m_type) {
-            return false;
-        }
-
         auto address = model->index(row, AddressTableModel::Address, parent);

         if (filterRegExp().indexIn(model->data(address).toString()) < 0 &&
```
but that may get kinda dumb for cases when the number of receiving addresses in the book is large.

Another approach is to rekey `mapAddressBook` by `std::pair<CTxDestination, std::string>` where the string is purpose, but that's more work.

**Comment by jamesob** [comment]
The kind of repeated pay-to-self behavior that the address book would support probably is edge-casey and not recommended, so this may not be worth fixing.

**Comment by ryanofsky** [comment]
Maybe just clarifying the error message would be a good fix? I think

> Can't add receiving address 2N3... ("ruh roh") to the sending address book

could be an improvement over "The entered address 2N3... is already in the address book."

> One option is to simply not filter addresses for purpose when we're displaying the address book, e.g.

It seems like it would be confusing to show receiving addresses in the send dialog by default, but maybe there could be a checkbox giving the option to display them.

> Another approach is to rekey mapAddressBook by std::pair<CTxDestination, std::string> where the string is purpose, but that's more work.

I don't think this would be great, because it would also allow associating different names with the same address. But one way you could allow addresses to be used for both sending and receiving would be to extend purpose field with a "receive+send" option. Or make purpose a set of strings instead of a single string.

**Comment by jamesob** [comment]
Roger that. Thanks for the input, @ryanofsky @laanwj. I'll file a PR clarifying the error messages.
