### ISSUE TITLE
Wallet file should not be reused across chains

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#12805]
Now that it is possible to specify a full path for the wallet (or a walletdir), the same wallet file is happily reused even when switching chains.

Imo that use case has no purpose, since all transactions on one chain are invalid on the other. It might be better to return an `InitError` in that case than writing useless data to a wallet file of a different chain.

**Comment by ryanofsky** [comment]
It might be possible to prevent this by looking at best block value in the wallet database, and triggering an error if the genesis block referenced there doesn't match the current chain:

https://github.com/bitcoin/bitcoin/blob/0d8fc8de076d1447df63f4d348a19732f5a0d31e/src/chain.cpp#L35

**Comment by prusnak** [comment]
Should this be closed now that https://github.com/bitcoin/bitcoin/pull/18554 has been merged?
