### ISSUE TITLE
Call importaddress with param rescan true，then other calls will take so long time

### ISSUE THREAD

**Issue by cyssxt** [bitcoin/bitcoin#12807]
Call importaddress with param rescan true，then other calls will take so long time，Can‘t response immediately！’

When i importaddress  with param rescan true ，other rpc calls can response immediately！

Other rpc calls blocked！

Open two terminal,One call importaddress method,another call listaccount method!
Then the listaccount will wait long time!

0.15

centos

**Comment by sipa** [comment]
Yes, this is expected. No wallet operations are possible until the rescan completes.

If you want to import multiple addresses at once, you're better off with the `importmulti` RPC which can import multiple addresses at the same time, and rescan only once.

**Comment by cyssxt** [comment]
@sipa I found that,importmulti can rescan, and rpc call also can response immediately!
As long as it is not the request without rescan param‘s value is true！
