### ISSUE TITLE
bitcoin-qt  doesn't  exist when make install successful ？

### ISSUE THREAD

**Issue by mosqiutor** [bitcoin/bitcoin#12817]
guys,here is a trouble for me .
when i was run make install and  successful.  
i saw the bitcoin-cli  & bitcoin-tx  & bitcoind,but not bitcoin-qt.
so why?
i have install QT4 on my laptop.

**Comment by arunsatyarth** [comment]
bitcoin-qt gets created in the src/qt folder
Also you need to do `./configure -with-gui `and then run `make`

**Comment by MarcoFalke** [comment]
Please include you config.log and steps to reproduce. Also, qt5 is recommended
