### ISSUE TITLE
Strange -blocksdir behavior

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#12828]
A bit late to the party, but I just tried #12653 and noticed some non-intuitive behavior (on macOS), that's probably worth explaining release notes and help.

Before this new feature I kept the entire datadir on an SSD drive, so I launch with: `bitcoind -datadir=/Volumes/SSD/Bitcoin`.

Initially I naively moved `/Volumes/SSD/Bitcoin/blocks` to `/Users/bitcoin/blocks` and added a line to `/Volumes/SSD/Bitcoin/bitcoin.conf`: `blocksdir=/Users/bitcoin/blocks`.

I then realized that I shouldn't have moved the `index` subdirectory, so I moved that back to `/Volumes/SSD/Bitcoin/blocks/index`. Having an empty `blocks` dir with just and `index` subdir is a bit weird. Perhaps after @jimpo's #11857 is merged, we could just move / assume all indexes to be there (if `-blocksdir` is set)?

Worse, it created a directory `/Users/bitcoin/blocks/blocks`, which seems like a bug. I had to set `blocksdir=/Users/bitcoin` instead.

**Comment by jnewbery** [comment]
was that a deliberate `bocks`/`blocks` typo?

**Comment by Sjors** [comment]
@jnewbery fixed typo...

**Comment by Sjors** [comment]
Actually this behavior makes sense, but could be better documented:

If you enable testnet, it will use `blocksdir/testnet/blocks`, so `blocksdir/blocks` is appropriate for mainnet. But maybe it should be called `blockstorageroot` or something.

**Comment by MarcoFalke** [comment]
Yes, if the help string doesn't mention that yet, then maybe it should.

**Comment by Sjors** [comment]
```
  -blocksdir=<dir>
       Specify blocks directory (default: <datadir>/blocks)
```

That's not very clear, though not sure how to rephrase it.

**Comment by Fonta1n3** [comment]
I am still experiencing this... I set `blocksdir=/Users/me/Desktop` in my conf and yet when I boot up it still creates a new block dir in the default location.

**Comment by Fonta1n3** [comment]
Ah... I did the same thing as Sjors, I had ignorantly moved my existing blocks folder, the fix is moving the index folder from within the actual blocks folder to the dummy blocks folder in the default location.
