### ISSUE TITLE
importaddress error (p2sh)

### ISSUE THREAD

**Issue by doffing81** [bitcoin/bitcoin#12824]
I tried the rpc command:
`bitcoin-cli importaddress <P2SH ADDRESS> true true`
only to receive the error:

> error: couldn't connect to server: unknown (code -1) (make sure server is running and you are connecting to the correct RPC port)

After adding empty quotes for my label parameter, a different error occurred:

> error code: -5
> error message:
> Cannot use the p2sh flag with an address - use a script instead

I am running 0.16.0 on Ubuntu.

Am I not able to simply give it the address?

**Comment by ken2812221** [comment]
try this
`bitcoin-cli importaddress <P2SH ADDRESS>`

**Comment by MarcoFalke** [comment]
Is this also true on master (i.e. after  #12652)?

**Comment by doffing81** [comment]
@ken2812221, that did not work. I get the same "couldn't connect" error.

@MarcoFalke, I guess I wouldn't know. I use the ppa to update when upon new releases. Can I pull from master if I use the ppa?

**Comment by MarcoFalke** [comment]
I cant reproduce
Are you sure the server was running? Did other calls before that call succeed?

**Comment by doffing81** [comment]
Yes to both.

**Comment by sipa** [comment]
It doesn't make sense that `getbalance` works and `importaddress` doesn't, when invoked in the same environment.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
