### ISSUE TITLE
Organize the address types on the "Receiving addresses" tab

### ISSUE THREAD

**Issue by jonjonez** [bitcoin/bitcoin#12834]
As we generate new addresses, either bech32, p2sh-segwit, and legacy are all merged together into the receive address list. I would like them to split the address types into options, as the following image suggests or something like that if you have a better idea:

![receiving address](https://user-images.githubusercontent.com/23480437/38117792-5d4984ac-338d-11e8-8d5e-783e5b81da5c.png)

Bitcoin core v0.16.0

**Comment by promag** [comment]
Can you explain the use case or the goal?

**Comment by behradkhodayar** [comment]
Do you think its useful from non-technical POV? Do regular users even know the difference? [I'm asking, because I don't know the usage statistics]

**Comment by jonjonez** [comment]
Yes, I find it useful because the list of receiving addresses does not separate the different types of addresses formats and everything is a mess.

normal users should know the difference even before using a wallet with different address strings, the address selection options proposed in the image above is the least

Example: when we use the command: importprivkey the bitcoin core will import the private key and the 3 address formats related to that private key in same window, it would be nicer if bitcoin core separated these addresses to make the interface cleaner. Do I just think that way?

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
