### ISSUE TITLE
bitcoin-qt dumps core during --help

### ISSUE THREAD

**Issue by murrayn** [bitcoin/bitcoin#12848]
src/qt/bitcoin-qt dumps core when run with --help

Segmentation fault (core dumped)

Built from current source on Linux.

Starting happening after commit c7ec5243892c38f9f77781b0e24a237942e7c776

Does not happen with {bitcoind, bitcoin-tx, bitcoin-cli} --help

**Comment by murrayn** [comment]
OK can be closed. I never saw the references to my comment #10762 , that's why I opened it.

**Comment by jnewbery** [comment]
@murrayn , thanks for reporting this. Sorry - I should have acknowledged your comment in #10762 .
