### ISSUE TITLE
(Test net) it's been more than 3 hours, transaction still unconfirmed!! 

### ISSUE THREAD

**Issue by sathwikrao575** [bitcoin/bitcoin#12841]
https://live.blockcypher.com/btc-testnet/tx/1c7c32ea524abce1ff67ce7555651e8464cbc92221499a364d17f428973a4e48/

Is this really normal?

**Comment by Empact** [comment]
Now confirmed! Ready to close this?

**Comment by sipa** [comment]
Testnet is very unreliable and has very irregular mining, so yes, this is normal.
