### ISSUE TITLE
importaddress / importmulti block any further requests until those done.

### ISSUE THREAD

**Issue by AdamSEY** [bitcoin/bitcoin#12858]
I have ubuntu server running Bitcoin core v0.16.

I'm sending RPC calls asynchronously, but, e.g., if I'm importing 1000 address using `importmulti` or `importaddress` command, any further commands such `listunspent` are waits until importing command finish, Even though I have set `rpcthreads=100 rpcworkqueue=50` and I've powerful server.

**Comment by promag** [comment]
The current implementation locks the wallet while importing, so any other wallet call will wait until the lock is released. Thread count doesn't matter here.

**Comment by AdamSEY** [comment]
Why locking wallet in necessary, especially when we are importing watch-only addresses?

**Comment by sipa** [comment]
@AdamSEY No, it would introduce a bug. Whenever shared data structures are accessed, locking is necessary.

**Comment by AdamSEY** [comment]
@sipa Does `importaddress` lock the wallet? Can you suggest any solution to import a thousand address and use the other commands?

**Comment by promag** [comment]
If those commands interact with the wallet then, currently, there is no solution.

**Comment by sipa** [comment]
@AdamSEY I don't know what you're trying to do, but if the time a rescan takes is an issue, perhaps you should change your workflow so it does not  rely on importing existing addresses or keys?

**Comment by AdamSEY** [comment]
Yeah, Thanks for the replies and help @promag @sipa  the addresses I'm importing are new, and I'm not doing a rescan. That what brought my attention. If the addresses are new, no rescan required, and it's watch-only addresses. Why are we blocking wallet access? Importing 20 address takes 4.5s! And If we're doing `listunspent` at the same time, I have to wait for the import to finish. 

But you are right; I have to change my workflow!

**Comment by sipa** [comment]
Wow, it shouldn't take that long if you're not rescanning. That sounds like an issue.

Not the fact that it blocks (that's kind of inevitable), but I don't understand why it takes that long regardless.

**Comment by AdamSEY** [comment]
Perhaps because I have imported too many addresses before?

**Comment by AdamSEY** [comment]
I've removed the wallet.dat and tried to import 20 addresses but importing time is the same

`It took 4.4455699920654 seconds!`

So it seems not because I've imported many addresses. Should I open a different issue for that problem or we just open this one again since there are many details.
