### ISSUE TITLE
Mac make error！what can I do? Mac version 10.13.4

### ISSUE THREAD

**Issue by playgamelxh** [bitcoin/bitcoin#12866]
Making all in src
  OBJCXX   qt/bitcoin_qt-macdockiconhandler.o
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:136:5: error: expected function body after function declarator
    __OSX_AVAILABLE_STARTING(__MAC_10_12_4, __IPHONE_10_3);
    ^
/usr/local/include/Availability.h:186:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:8:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_12_4
^
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:146:5: error: expected function body after function declarator
    __OSX_AVAILABLE_STARTING(__MAC_10_12_4, __IPHONE_10_3);
    ^
/usr/local/include/Availability.h:186:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:9:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_12_4
^
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:181:5: error: expected function body after function declarator
    __OSX_AVAILABLE_STARTING(__MAC_10_13, __IPHONE_11_0);
    ^
/usr/local/include/Availability.h:186:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:11:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_13
^
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:205:5: error: expected function body after function declarator
    __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_7, __MAC_10_13, __IPHONE_NA, __IPHONE_NA, "SecCertificateCopySerialNumber is deprecated. Use SecCertifi...
    ^
/usr/local/include/Availability.h:190:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                    ^
<scratch space>:15:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_7_DEP__MAC_10_13_MSG
^
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:539:9: error: expected function body after function declarator
        __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_7, __MAC_10_12_4, __IPHONE_NA, __IPHONE_NA, "SecCertificateCopyNormalizedIssuerContent is deprecate...
        ^
/usr/local/include/Availability.h:190:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                    ^
<scratch space>:63:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_7_DEP__MAC_10_12_4_MSG
^
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:557:9: error: expected function body after function declarator
        __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_7, __MAC_10_12_4, __IPHONE_NA, __IPHONE_NA, "SecCertificateCopyNormalizedSubjectContent is deprecat...
        ^
/usr/local/include/Availability.h:190:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                    ^
<scratch space>:67:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_7_DEP__MAC_10_12_4_MSG
^
In file included from qt/macdockiconhandler.mm:13:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:85:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:31:
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:452:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:526:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:528:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:530:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:786:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:788:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:790:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:792:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:794:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:796:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:798:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:800:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
/System/Library/Frameworks/Security.framework/Headers/SecItem.h:817:49: error: expected ','
    API_AVAILABLE(macos(10.7), ios(NA), bridgeos(NA));
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by fanquake** [comment]
Going to close due to lack of info. @playgamelxh Please re-open if you can provide more information.

**Comment by domoritz** [comment]
I'm seeing a similar error in another project. @playgamelxh can you tell us how you resolved the issue?

```
xcode-select version 2354
MacOS Mojave
```
