### ISSUE TITLE
rpc: help for commands

### ISSUE THREAD

**Issue by jakubtrnka** [bitcoin/bitcoin#12864]
I find quite annoying that help rpc call returns ca 120 lines as a list of all commands. I don't remember exact form and arguments of bitcoin-cli commands so I need to re-check them quite often and always scroll in terminal.
I suggest that help RPC call will be modified in the following way:
  * `bitcoin-cli help` prints list of *sections*, i. e. `Blockchain`, `Control`, `Generating`, `Mining`, etc.
  * `bitcoin-cli help all` prints list of all commands and sections like current `bitcoin-cli help` does
  * `bitcoin-cli help <section>` prints list of commands from corresponding *section*
  * `bitcoin-cli help <command>` will remain the same as in current implementation.

And I'm willing to do that if it appears to be desirable.

**Comment by jnewbery** [comment]
I don't think it's unusual for help text to fill more than one screen, and I can imagine an extra round trip being annoying for people who are just looking for a single command.

Does piping the output to less make this any less painful for you:

`bitcoin-cli help | less`

**Comment by jakubtrnka** [comment]
It's not that much painful, just a bit annoying. So I wondered whether people liked this idea. But when I think about it more, it's probably not desirable to introduce this unnecessary complexity into a code.
I usually dedicate another whole window(s) to help(s) and man(s).

**Comment by kallewoof** [comment]
If it's a specific command you can fairly easily append a grep to it. E.g. `bitcoin-cli help | grep address`.

**Comment by razamobin** [comment]
@promag Is it worth creating a pull request to implement your partial match suggestion? I put together a simple patch here: https://github.com/razamobin/bitcoin/commit/496310c9f18c8cc300677f2faf5457fd0f326c5b

**Comment by promag** [comment]
@razamobin feel free to submit it and see what other developers have to say.

**Comment by laanwj** [comment]
I think this is very subjective. Personally I prefer the full list of commands on `bitcoin-cli help`, when I need a partial match I pipe it through `grep`.

**Comment by promag** [comment]
It turns out my suggestion has problems. Calling `bitcoin-cli -regtest signrawtransaction` would give 3 matches:
```
signrawtransaction "hexstring" ( [{"txid":"id","vout":n,"scriptPubKey":"hex","redeemScript":"hex"},...] ["privatekey1",...] sighashtype )
signrawtransactionwithkey "hexstring" ["privatekey1",...] ( [{"txid":"id","vout":n,"scriptPubKey":"hex","redeemScript":"hex"},...] sighashtype )
signrawtransactionwithwallet "hexstring" ( [{"txid":"id","vout":n,"scriptPubKey":"hex","redeemScript":"hex"},...] sighashtype )
```
instead of `signrawtransaction` detailed help.

**Comment by razamobin** [comment]
Yeah, I ran into the same issue yesterday. I separated the logic so that exact match shows the detailed help as usual.

**Comment by promag** [comment]
@razamobin are you planning to submit the PR?

@jakubtrnka can this be closed?

**Comment by razamobin** [comment]
I decided not to submit the PR based on feedback.

**Comment by jnewbery** [comment]
This seems very subjective, so I'm going to close for now.

Feel free to open a PR if you have a concrete proposal for a change. I expect it'd have difficulty being merged since most people seem fine with the way things are now.
