### ISSUE TITLE
A way to scan specific block

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#12880]
When importing an address (using e.g. `importaddress`), it is currently impossible to skip the rescan and instead ask the node to scan a specific block in which you know there are related transactions. It is pretty trivial to use a block explorer to find relevant blocks and only scan those.

Is it worthwhile to add a RPC command that lets you specify a (range of) block(s) to address this?

**Comment by okayplanet** [comment]
It looks like ```importaddress``` has a ```rescan``` arg that you can set to false.  Is this not currently working?  You could always ```abortrescan```.  It also looks like ```rescanblockchain``` has args for ```start_height``` and ```stop_height```.

**Comment by kallewoof** [comment]
@okayplanet `rescan` works, the problem was scanning a particular block. You're right about `rescanblockchain` though. Not super intuitive for people, but it definitely does what you want. Thanks for the reminder! :)
