### ISSUE TITLE
encryptwallet has address pool limitation?

### ISSUE THREAD

**Issue by J-Liu** [bitcoin/bitcoin#12907]
in btc.conf
`keypool=200000`

then I run
`bitcoin-cli encryptwallet "pass"`
will failed.

but when I change it into 2000, everything going fine.

**Comment by MarcoFalke** [comment]
Please include the error message and version

**Comment by J-Liu** [comment]
bitcoin-0.16.0
and there is no error message, even no any message, it just made `bitcoind` exit.

**Comment by MarcoFalke** [comment]
Please note that " Successfully executing this command shuts down bitcoin core, it will need to be manually restarted. "

So, this is expected

**Comment by J-Liu** [comment]
Sorry, it is my fault.  I didn't make a clear description.
I know if the `encryptwallet` success, it will shut down bitcoind, and we should restart it manually.
But, when I start bitcoind manually, again, the wallet is still NOT encrypted.

**Comment by J-Liu** [comment]
Sorry, typo, `keypool`
And, I run a release binary...

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by J-Liu** [comment]
Sorry I can not use the product system, so I built a test environment and the test again.
And sorry for I don't understand the log file, so I attached it.  Hope it will be helpful.
[debug.log](https://github.com/bitcoin/bitcoin/files/1887460/debug.log)
[db.log](https://github.com/bitcoin/bitcoin/files/1887462/db.log)

**Comment by achow101** [comment]
The db.log file says it's running out of BDB locks. Is there really a fix for this other than changing the database system? We could limit the number of keypool entries or increase the number of locks, but those aren't really solutions.

**Comment by TheBlueMatt** [comment]
I believe you can change the locks limit with a DB_CONFIG file which BDB will read and set the locks size. https://bitcointalk.org/index.php?topic=152208.0 may be of use (just googled around for those settings cause you ahve to apply them to pre-0.8 nodes to get them to sync the chain).

**Comment by MarcoFalke** [comment]
I can still reproduce. Probably getting rid of bdb is going to fix this #18916

**Comment by achow101** [comment]
Legacy wallets that use BDB are being deprecated. Using descriptor wallets should solve this problem.
