### ISSUE TITLE
Check for AVX

### ISSUE THREAD

**Issue by DesWurstes** [bitcoin/bitcoin#12903]
https://github.com/bitcoin/bitcoin/blob/5f0c6a7b0e47e03f848dc992d37fe209dd9c6975/src/crypto/sha256.cpp#L183

This checks whether the CPU supports SSE4. It should also check if the OS supports SSE4. See this [StackOverflow answer](https://stackoverflow.com/a/22521619/6557621).

**Comment by Empact** [comment]
I think this applies to AVX testing only, and we don't use AVX.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55307
https://sourceware.org/bugzilla/show_bug.cgi?id=13007
https://software.intel.com/en-us/blogs/2011/04/14/is-avx-enabled/
https://gist.github.com/hi2p-perim/7855506
http://svn.cern.ch/guest/gaudi/Gaudi/tags/GaudiKernel/v31r6/src/Lib/instrset_detect.cpp

**Comment by sipa** [comment]
Actually, since this issue was opened, AVX2 code was added.
