### ISSUE TITLE
make debpackage? 

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#12913]
Hello,

Is there a possibility to compile directly through Makefile a ready .deb package?
Would be great if compiling make deploy creates a deb package.
I think makeinstall should create a debpackage or?

Also ready

>  sudo apt-get install bitcoin

Would be awesome.
But is there something like this?

Greetings,
Pawel

**Comment by Aaahh** [comment]
https://bitcoin.org/en/full-node#ubuntu-1610

**Comment by TheBlueMatt** [comment]
You want cp -r contrib/debian ./ && dpkg-buildpackage
