### ISSUE TITLE
wallet unsolved problem

### ISSUE THREAD

**Issue by Ben002** [bitcoin/bitcoin#12936]
instead delete wtx from the wallet and return failure. why not?

![c6652d25-5d0d-4898-ba8a-f1246ee95910](https://user-images.githubusercontent.com/20814894/38595467-8f5eb638-3d7e-11e8-96b6-121ec9696f04.png)

**Comment by MarcoFalke** [comment]
Pull requests welcome. No need to open an issue for a TODO that is already in the code

**Comment by WorkShop-Office** [comment]
Bitcoin Indonesia make broadcast hahaha
