### ISSUE TITLE
macOS make deploy Error

### ISSUE THREAD

**Issue by fengyunyongjie** [bitcoin/bitcoin#12974]
`$ make deploy`
`/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
  OBJCXXLD qt/bitcoin-qt`
`ld: entry point (_main) undefined. for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[1]: *** [qt/bitcoin-qt] Error 1`
`make: *** [src/qt/bitcoin-qt] Error 2`

**Comment by jonasschnelli** [comment]
can you give us some more information...
- maybe pastebin your config.log?
- does this happens on `make deploy` only (or also on `make`)?

**Comment by fanquake** [comment]
Going to close due to lack of information. @fengyunyongjie Please re-open if you can provide some more info.
