### ISSUE TITLE
Validation Interface Logging

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#12994]
https://github.com/bitcoin/bitcoin/issues/12978 was a fun bug where there was a race to enqueue `UpdatedBlockTip()` between the message handling thread and an RPC thread.

That issue and others like it would be a lot easier to debug if the validation interface logged whenever a callback is enqueued or dequeued (similar to #12981, but comprehensively covering all validation interface callbacks).

@TheBlueMatt - any objections before I PR this?

**Comment by skeees** [comment]
Upvote on enhanced logging - I'm going to attempt some unit tests for well ordered behavior from @sdaftuar's suggestion

**Comment by Empact** [comment]
@skeees tests, I presume: #13024

**Comment by jb55** [comment]
did anything come of this?

**Comment by jnewbery** [comment]
> did anything come of this?

No, I moved on to other things. PRs welcome!

**Comment by jkczyz** [comment]
I can pick this up.

@jnewbery Should all logging here use common `BCLog::LogFlags` (e.g. `BCLog::NET`) or should it vary based on the interface method?

https://github.com/bitcoin/bitcoin/blob/c52776e6ff4dd04c37eaee5fb5cf769ed32c9cac/src/logging.h#L34

**Comment by jnewbery** [comment]
> Should all logging here use common BCLog::LogFlags (e.g. BCLog::NET) or should it vary based on the interface method?

I think it should be a new logging category (VALIDATIONINTERFACE), since it could be quite noisy and it seems reasonable to be able to turn it on/off individually.
