### ISSUE TITLE
Need test for rpcauth.py

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#12995]
There is no test for the `share/rpcauth/rpcauth.py` script, there should be one, and it should be part of travis.

**Comment by cdecker** [comment]
I'd like to take a stab at this, but I could use some guidance. Would this be better suited in `test/util` or `test/functional`? The latter is a bit heavier but it'd allow us to also check the correctness of the generated credentials.

**Comment by MarcoFalke** [comment]
We have a test in `./test/functional/rpc_users.py` that has the rpcauth hardcoded. It could make sense to call into `rpcauth.py` and generate a fresh pair every time the test is executed.

**Comment by cdecker** [comment]
Sounds like a plan, I'll take a look at it ^^

**Comment by jnewbery** [comment]
I'm NACKish on adding dependencies to the functional test framework, even if they're on internal project tools. Currently the functional tests can run anywhere. I don't think we should be adding a requirement that the `/share` directory is available (and certainly shouldn't be hard-coding its location relative to the test file).

**Comment by nixbox** [comment]
If I were to add unit testing for rpcauth.py, where would that go in the directory structure?

**Comment by jnewbery** [comment]
> If I were to add unit testing for rpcauth.py, where would that go in the directory structure?

I see two options:

1. Within the `rpcauth.py` module itself, using the Python standard library [unittest module](https://docs.python.org/3/library/unittest.html).
2. In `test/util`, by adding the location of rpcauth.py to config.ini.in (as in https://github.com/bitcoin/bitcoin/pull/13024/commits/6be22e7db3ac815356ba14298d551bfae0e7a74c#diff-914785539d91e7b1d7ec0614606b03eeR12) and then updating `sys.path`.

In either case, you should update make check to run the test.
