### ISSUE TITLE
LevelDB read failure: Corruption: block checksum mismatch

### ISSUE THREAD

**Issue by litecoinz-project** [bitcoin/bitcoin#13009]
No HW issues, all other programs runs without problem except bitcoin. I made a backup of the wallet and deleted the folder .bitcoin 3 times to force a full resync, but same issue:

2018-04-17 19:32:21 UpdateTip: new best=00000000000000000c368b38ac3f24b83b8dff7ae83e59a672f49d5a2a75e924 height=340515 version=0x00000002 log2_work=82.090551 tx=57842905 date='2015-01-26 05:52:51' progress=0.180658 cache=21.0MiB(157966txo)
**2018-04-17 19:32:21 LevelDB read failure: Corruption: block checksum mismatch
2018-04-17 19:32:21 Corruption: block checksum mismatch
2018-04-17 19:33:21 version handshake timeout from 1
2018-04-17 19:35:30 Error reading from database: Database corrupted**

![](https://i.imgur.com/LHfuqFo.png)

The issue can be reproduced with a fresh installation from last release of bitcoin.

Release used: bitcoin-0.16.0

OS: Fedora release 27 (Twenty Seven)
CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
RAM: 16317500 kB
DISK TYPE: SATA Hitachi HTS54101 Rev: A4D0

[debug.log](https://github.com/bitcoin/bitcoin/files/1921306/debug.log)

**Comment by TheBlueMatt** [comment]
"all other programs runs without problem except bitcoin" is not sufficient to rule out hardware issues. Bitcoin is particularly good at breaking peoples' hardware that is stable under low-load conditions. Please run memtest and linpack/prime95, and report the results.

**Comment by MarcoFalke** [comment]
You might want to check your hardware for defects.
* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206

**Comment by litecoinz-project** [comment]
Ok thanks I will check.

**Comment by litecoinz-project** [comment]
OK I confirm and Windows PC everything is fine. Now I must investigate more why my laptop has problem. memtest do not show errors, also disks seems ok. Only problem is a CPU overheat during the chain download. Thank you so much for your attention and sorry if I disturbed you for nothing.
