### ISSUE TITLE
Lock/unlock Bitcoin

### ISSUE THREAD

**Issue by zguoguo** [bitcoin/bitcoin#13015]
Hi, I saw that in the documentation for PEGGY of cosmos(https://github.com/cosmos/peggy/tree/master/spec##smart-contract-component), the readme also mentioned that Bitcoin can be linked to cosmos network through a peg zone. However, Bitcoin does not support Smart Contracts. How does bitcoin perform actions like locking/unlocking bitcoin?

**Comment by fanquake** [comment]
Issues here are for technical problems/queries related to Bitcoin Core. For more general bitcoin questions, try the [bitcoin stackexchange](https://bitcoin.stackexchange.com/).

**Comment by Wallerzzz** [comment]
I know that there are specially organised events for those who either want to start working with blockchain technologies or desire to improve their actual skills thus getting more money from their virtual business. No matter what goal you are after, [bis blockchain](https://bisshow.com/) conference in London can be a very useful event for people working in the current area. The speakers are professionals and they can answer all questions concerning blockchain technologies.
