### ISSUE TITLE
Feature Request: Nanobitcoin Unit Precision

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [bitcoin/bitcoin#13053]
I would like for the satoshi (1/100,000,000th of a bitcoin) to no longer be the smallest unit of a bitcoin that Bitcoin Core can support.  I think as little as two additional decimal places would suffice for my preference, but I suppose I would propose adding four decimal places, so that it is broken down into the nanobitcoin realm (1/1,000,000,000,000th of a bitcoin).

I realise that I am not an expert in how this program/code works, and this suggestion may be a bad technical one, so I would suggest that those with competence/expertise who are interested in this expansion of precision (both for and against) comment here about their thoughts, maybe start a discussion about if more precision should or should not be incorporated into Bitcoin Core.

(I just saw the "Brainstorming" label, I think that (or maybe "Up for Consideration") fits this issue.)

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
