### ISSUE TITLE
two boost version issues in ubuntu

### ISSUE THREAD

**Issue by zhuimengshaonian66** [bitcoin/bitcoin#13089]
hello everynoe
i  have a problem which make me very sad because i have test many method but i can't solve
  one month ago  i use   sudo apt-get install libboost-all-dev  to get the boost and i can compile bitcoin successfully,i kow it is boost1.58 。  one week ago  when i  install a boost1.67 in my ubuntu by source,i cant compile bitcoin anywhere.

i compile bitcoin0.10 show:
rpcserver.cpp:467:102: error: wrong number of template arguments (2, should be 1)
 t::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > accepto
                                                                     ^
In file included from /usr/local/include/boost/asio.hpp:30:0,
                 from rpcprotocol.h:15,
                 from rpcserver.h:10,
                 from rpcserver.cpp:6:
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: provided for ‘template<class Protocol> class boost::asio::basic_socket_acceptor’
 class basic_socket_acceptor
       ^
rpcserver.cpp:467:104: error: template argument 1 is invalid
 :shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
                                                                     ^
rpcserver.cpp:477:95: error: wrong number of template arguments (2, should be 1)
 t::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > accepto
                                                                     ^
In file included from /usr/local/include/boost/asio.hpp:30:0,
                 from rpcprotocol.h:15,
                 from rpcserver.h:10,
                 from rpcserver.cpp:6:
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: provided for ‘template<class Protocol> class boost::asio::basic_socket_acceptor’
 class basic_socket_acceptor
       ^
rpcserver.cpp:477:97: error: template argument 1 is invalid
 :shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,

________________________________________________________________________
when i compile bitcoin 0.16 it it show maybe:
undefine ref boost::test_tools

i know it is boost falut,  later i  install a boost1.58 by source  but i cant solve it .
i have check /user/lib/linux86_64-linux-gnu i think it is libboost_unit_test_framework.so.1,58............
so i think it is boost 1.58     so  what should i do ?????

**Comment by MarcoFalke** [comment]
Please add steps to reproduce. Also note that you can just build from depends (see `./depends/README.md`)

I tried with boost 1.67 and everything works fine:

```diff
diff --git a/depends/packages/boost.mk b/depends/packages/boost.mk
index bf773ccd14..c6d2145fb0 100644
--- a/depends/packages/boost.mk
+++ b/depends/packages/boost.mk
@@ -1,8 +1,8 @@
 package=boost
-$(package)_version=1_64_0
-$(package)_download_path=https://dl.bintray.com/boostorg/release/1.64.0/source/
+$(package)_version=1_67_0
+$(package)_download_path=https://dl.bintray.com/boostorg/release/1.67.0/source/
 $(package)_file_name=$(package)_$($(package)_version).tar.bz2
-$(package)_sha256_hash=7bcc5caace97baa948931d712ea5f37038dbb1c5d89b43ad4def4ed7cb683332
+$(package)_sha256_hash=2684c972994ee57fc5632e03bf044746f6eb45d4920c343937a465fd67a5adba
 
 define $(package)_set_vars
 $(package)_config_opts_release=variant=release

**Comment by MarcoFalke** [comment]
Regardless of that Bitcoin Core 0.10 is EOL for a long time. Would you mind letting us know why you need to build that version?
