### ISSUE TITLE
Invalid wallet path with Chinese characters in windows 

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#13103]
Reported in https://github.com/bitcoin/bitcoin/pull/13100#issuecomment-384836977 by @ken2812221.

**Comment by MarcoFalke** [comment]
Is this on master or only with your pull request?

**Comment by promag** [comment]
I think #13100 has nothing to do with it.

**Comment by ken2812221** [comment]
I think this can happen with non-ASCII characters, not only Chinese.

**Comment by r0zar** [comment]
Found this on the previously used addresses page:
![btcbug](https://user-images.githubusercontent.com/4655474/39452265-380c2f28-4c97-11e8-9c3f-541023c8e6a5.PNG)

**Comment by ken2812221** [comment]
@r0zar That is #12544

**Comment by ken2812221** [comment]
Can we create a wrapper of c++17 `std::filesystem::path`? There are `.u8string()` and `u8path`, but they are not in boost. We can call `.u8string()` everywhere in our code, but call `.string()` if we want a native-encoded string. Once we could upgrade to c++17, it would be less painful.

**Comment by laanwj** [comment]
Is this still an issue with #13787 (and dependencies) merged?

**Comment by ken2812221** [comment]
I think this could be closed.
