### ISSUE TITLE
RPC Feature: option for prevouts in getrawtransaction

### ISSUE THREAD

**Issue by jimpo** [bitcoin/bitcoin#13108]
I think it might be useful for certain applications to be able to get transaction fees from the RPC API. The problem is that loading all prevouts from disk could be pretty expensive depending on the number of inputs, so it should be made optional with a flag. One way to expose this in the API is to include the prevout (scriptPubKey & amount) with every input in vin, as well as adding a "fee" field to the top level of the response payload.

How would people feel about this?

**Comment by sipa** [comment]
NACK getrawtransaction shouldn't do more than getting raw transactions. And it certainly shouldn't even more on having a fully indexed chain available.

**Comment by jimpo** [comment]
I'm not asking for wallet applications, but for fee estimators, explorer-type applications, and the like. Is there an alternative you suggest, or is the answer to build a full auxiliary indexing service? Or two just make the `getrawtransaction` RPC requests for all prevouts at the client level?

**Comment by promag** [comment]
> NACK. getrawtransaction shouldn't do more than getting raw transactions.

Agree on that.

> I think it might be useful for certain applications to be able to get transaction fees from the RPC API.

> I'm not asking for wallet applications, but for fee estimators, explorer-type applications, and the like. Is there an alternative you suggest, or is the answer to build a full auxiliary indexing service?

I feel this is not the best place to serve that data. A "full auxiliary indexing service" sounds more scalable!

> Or two just make the getrawtransaction RPC requests for all prevouts at the client level?

That looks insane?

**Comment by MarcoFalke** [comment]
Something like this has been implemented here: #16083 It is up for grabs (needs rebase).


Let's continue discussion in #18771
