### ISSUE TITLE
 bitcoind -daemon is not supported on this operating system

### ISSUE THREAD

**Issue by thotheolh** [bitcoin/bitcoin#13121]
Bitcoin Core daemon running on a Windows 7 seems to be not supported with the following error:

```
C:\Users\User1>bitcoind -daemon
Error: -daemon is not supported on this operating system
```

**Comment by sipa** [comment]
Yes, the concept of a daemon does not exist on windows.

There are system services, but dealing with those is fairly different from daemons in Unix.

**Comment by thotheolh** [comment]
Does it mean I am not able to access the JSON-RPC service for Bitcoin ?

How do I access JSON-RPC service on Windows ?

**Comment by laanwj** [comment]
You do not need `-daemon` to access JSON-RPC. The option for that is `-server`, however that option is enabled by default for `bitcoind` (it is optional for `bitcoin-qt`). So in that regard you don't have to do anything special, it's exactly the same as on every other operating system.
