### ISSUE TITLE
Bitcoin RPC Calculate the commission (PHP)

### ISSUE THREAD

**Issue by serderovsh** [bitcoin/bitcoin#13132]
Hello, I have a small problem.
I can not calculate the commission in any way.

Implementation example:
```
 $bitcoin = new jsonRPCClient('http://user:password@127.0.0.1:8332/');
 echo "<pre>\n";
  print_r($bitcoin->sendfrom('account', 'toaddress', '0.005')); echo "\n";
  echo "</pre>";
```

Please help, how to calculate the commission before shipment, the second day I can not solve this problem.

And another question: Is it possible to deduct a commission from the amount using the method "sendfrom"?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
