### ISSUE TITLE
[ISSUE]./build/bitcoin.o: file not recognized. File format not recognized

### ISSUE THREAD

**Issue by gurtaj-project** [bitcoin/bitcoin#13156]
Hello Friends!

May I please receive some suggestions, it seems like a very basic error, essentially the build script does not recognize .o files when I build the windows.exe qt using the gitian-win32.yml build-script in the contrib section where all the build scripts are located (all the other build scripts work perfectly)
Perhaps I am simply missing a required dependency that can read and write to .o files? 
anyways here is the error:

./build/bitcoin.o: file not recognized
File format not recognized
collect2: Id returned 1 exit status
make[1]: *** [release/gurtaj-qt.exe] Error 1

**Comment by gurtaj-project** [comment]
![compilationerror](https://user-images.githubusercontent.com/38900360/39560623-da4e5632-4e5c-11e8-9488-af915dcafdbd.JPG)

**Comment by fanquake** [comment]
We don't provide technical support for altcoins here.
