### ISSUE TITLE
Failed to Build Bitcoin-Qt

### ISSUE THREAD

**Issue by august434** [bitcoin/bitcoin#13150]
The error relate to UPnP as show below.

Please kindly help solve the issue.

Thank you!

`C:\Coin>mingw32-make -f Makefile.Release
c:\Qt\4.8.6\bin\rcc.exe -name bitcoin src\qt\bitcoin.qrc -o release\qrc_bitcoin.cpp
g++ -c -pipe -fno-keep-inline-dllexport -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -O2 -frtti -fexceptions -mthreads -fdiagnostics-show-option -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -DUNICODE -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_QRCODE -DUSE_UPNP=1 -DSTATICLIB -DUSE_IPV6=1 -DWIN32 -D_MT -DQT_THREAD_SUPPORT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -I"..\Qt\4.8.6\include\QtCore" -I"..\Qt\4.8.6\include\QtNetwork" -I"..\Qt\4.8.6\include\QtGui" -I"..\Qt\4.8.6\include" -I"src" -I"src\json" -I"src\qt" -I"..\deps" -I"src\leveldb\include" -I"src\leveldb\helpers" -I"..\deps\boost_1_55_0" -I"..\deps\db-4.8.30.NC\build_unix" -I"..\deps\openssl-1.0.1j\include" -I"..\deps\qrencode-3.4.4" -I"..\Qt\4.8.6\include\ActiveQt" -I"build" -I"build" -I"..\Qt\4.8.6\mkspecs\default" -o build\qrc_bitcoin.o release\qrc_bitcoin.cpp
g++ -Wl,--dynamicbase -Wl,--nxcompat -Wl,--large-address-aware -static -static-libgcc -static-libstdc++ -Wl,-s -mthreads -Wl,-subsystem,windows -o release\coin-qt.exe object_script.coin-qt.Release  -L"c:\Qt\4.8.6\lib" -lmingwthrd -lmingw32 -lqtmain build\bitcoin-qt_res.o -lqrencode -LC:/deps/miniupnpc -lminiupnpc -liphlpapi C:/coin/src/leveldb/libleveldb.a C:/coin/src/leveldb/libmemenv.a -lshlwapi -LC:/deps/boost_1_55_0/stage/lib -LC:/deps/db-4.8.30.NC/build_unix -LC:/deps/openssl-1.0.1j -LC:/deps/qrencode-3.4.4/.libs -lssl -lcrypto -ldb_cxx -lshlwapi -lmswsock -lboost_system-mgw49-mt-s-1_55 -lboost_filesystem-mgw49-mt-s-1_55 -lboost_program_options-mgw49-mt-s-1_55 -lboost_thread-mgw49-mt-s-1_55 -lboost_chrono-mgw49-mt-s-1_55 -lQtGui -lQtNetwork -lgdi32 -lcomdlg32 -loleaut32 -limm32 -lwinmm -lwinspool -lmsimg32 -lQtCore -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32
./build\net.o:net.cpp:(.text+0x88f3): undefined reference to `_imp__upnpDiscover'
./build\net.o:net.cpp:(.text+0x892a): undefined reference to `_imp__UPNP_GetValidIGD'
./build\net.o:net.cpp:(.text+0x896b): undefined reference to `_imp__UPNP_GetExternalIPAddress'
./build\net.o:net.cpp:(.text+0x89e7): undefined reference to `_imp__freeUPNPDevlist'
./build\net.o:net.cpp:(.text+0x89fa): undefined reference to `_imp__FreeUPNPUrls'
./build\net.o:net.cpp:(.text+0x8ae7): undefined reference to `_imp__strupnperror'
./build\net.o:net.cpp:(.text+0x8b73): undefined reference to `_imp__UPNP_AddPortMapping'
./build\net.o:net.cpp:(.text+0x8bfb): undefined reference to `_imp__UPNP_DeletePortMapping'
./build\net.o:net.cpp:(.text+0x8c1a): undefined reference to `_imp__freeUPNPDevlist'
./build\net.o:net.cpp:(.text+0x8c29): undefined reference to `_imp__FreeUPNPUrls'
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: ./build\net.o: bad reloc address 0x960 in section `.data'
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status
Makefile.Release:291: recipe for target 'release\coin-qt.exe' failed
mingw32-make: *** [release\coin-qt.exe] Error 1`

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
