### ISSUE TITLE
Make Deploy Cross Compile Not finding Frameworks/Plugins

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [bitcoin/bitcoin#13169]
make deploy during cross compile for darwin in ubuntu 14 can not find frameworks or plugins to package in bitcoin-qt.app

package plugins and frameworks on deployment 

Everytime

self compiled  bitcoin-0.16

vm of ubuntu 14

```
+ Removing old dist folder +
+ Copying source bundle +
+ Deploying frameworks +
Warning: Could not find any external frameworks to deploy in dist/Bitcoin-Qt.app.
Warning: Could not detect Qt's path, skipping plugin deployment!
+ Installing qt.conf +
+ Adding Qt translations +
+ Done +

**Comment by buddilla** [comment]
I hope someone can reproduce this issue it's quite annoying LOL

I have yet to figure out what is going on and how to fix it.

**Comment by buddilla** [comment]
I may have figured out why this may be happening, but it is just a guess. The file paths for the frameworks and plugins are not being passed to bitcoin-qt.pro. I will see if I can add the paths by passing them through a configure variable.

**Comment by ken2812221** [comment]
Do you install all packages listed here?https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-descriptors/gitian-osx.yml

**Comment by buddilla** [comment]
Yes I do

**Comment by buddilla** [comment]
Yes it is still an issue I will get you some more info in a little bit.

**Comment by buddilla** [comment]
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git nsis g++-aarch64-linux-gnu g++-4.8-aarch64-linux-gnu gcc-4.8-aarch64-linux-gnu binutils-aarch64-linux-gnu g++-arm-linux-gnueabihf g++-4.8-arm-linux-gnueabihf gcc-4.8-arm-linux-gnueabihf binutils-arm-linux-gnueabihf g++-4.8-multilib gcc-4.8-multilib binutils-gold librsvg2-bin libtiff-tools cmake imagemagick libcap-dev libz-dev libbz2-dev python-setuptools g++-mingw-w64-x86-64 g++-mingw-w64-i686 mingw-w64-i686-dev libboost-dev libdb4.8-dev libdb4.8++-dev libdbus-1-dev libdbus-glib-1-dev xsltproc expat libharfbuzz-bin libharfbuzz-dev libevent-dev libjpeg8-dev libpng-dev miniupnpc libpcre3-dev libpcre++-dev libprotobuf-dev libprotobuf-c0 qrencode qtbase5-dev qt5-default qttools5-dev-tools qtdeclarative5-dev libxkbcommon-dev libzmq3-dev zlib1g-dev

downloaded and installed https://github.com/theuni/libdmg-hfsplus and install

cd bitcoin-0.16/depends/

make HOST=x86_64-apple-darwin11

./configure --prefix=`pwd`/depends/x86_64-apple-darwin11

make

make deploy

leads to the issue

**Comment by fanquake** [comment]
While the output here might be concerning/annoying. It's not actually a bug, and is expected when doing a cross-compile for macOS. See [macdeployqtplus](https://github.com/bitcoin/bitcoin/blob/master/contrib/macdeploy/macdeployqtplus). Closing this.
