### ISSUE TITLE
Compilation Error : undefined reference to `boost::this_thread::hidden::sleep_for

### ISSUE THREAD

**Issue by MaherBTA** [bitcoin/bitcoin#13182]
Hi, 
I am trying to compile Bitcoin on Ubuntu 16 .
I have installed correctly all the dependencies.
**the ./configure shows no errors, but when I run the make command  :** 

> CXXLD    bitcoind
> libbitcoin_util.a(libbitcoin_util_a-utiltime.o): In function boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
> /usr/local/include/boost/thread/pthread/thread_data.hpp:258: undefined reference to boost::this_thread::hidden::sleep_for(timespec const&)'
> collect2: error: ld returned 1 exit status
> Makefile:3712: recipe for target 'bitcoind' failed

**Also when I run ./configure --with-boost=/usr/local it returns :** 

> checking whether the Boost::Thread library is available... yes
> configure: error: Could not find a version of the boost_thread library!

**Comment by jonasschnelli** [comment]
Try to clean your project:
`git clean -dxf` (removes all your local changes!)
`autogen.sh`
`./configure`
`make -j`

If you still face the issue, please upload your `config.log`

**Comment by MaherBTA** [comment]
It is still showing the same error during make 

[config.log](https://github.com/bitcoin/bitcoin/files/1981713/config.log)

**Comment by Foggyx420** [comment]
-with-boost-libdir=/usr/local/lib add that to configure line to try? This
fedora or centos?

**Comment by MaherBTA** [comment]
I am using Ubuntu 16.
when I run the configure -with-boost-libdir=/usr/local/lib I get this error : 

> checking whether the Boost::Thread library is available... yes
> configure: error: Could not find a version of the boost_thread library!
same error when passing  -with-boost-libdir=/usr/local/ .
boost is correctly installed, but there is a missing library, might it be something wrong with the boost version?

**Comment by MaherBTA** [comment]
Is there any good tutorial to compile bitcoin on Ubuntu ?

**Comment by MarcoFalke** [comment]
@MaherBTA There are steps in `./doc/build-*.md`. E.g. doc/build-unix.md

**Comment by MarcoFalke** [comment]
Also, you could just "fall back" to using depends if you encounter issues. Those are almost guaranteed to work. See the `depends` subfolder.

**Comment by MaherBTA** [comment]
the issue was about boost. Bitcoin compilation works only with boost 1.64 not even another version.
I tested like 5 boost versions . only the 1.64 worked for me.

Remark : in the dependencies.md the boost 1.64 href is linking to the 1.67 version.
