### ISSUE TITLE
Get unspent inputs Via Bitcoind

### ISSUE THREAD

**Issue by 5-digits** [bitcoin/bitcoin#13187]
Hi everyone,
How to get unspent inputs of a bitcoin address through the Bitcoind **without adding the private key** to Wallet.dat  or It's possible to do it in the full node as used in the Blockchain explorer like https://blockchain.info

So when pasting an address and hit enter it gives balances and unspent Inputs if there without even knowing what's the private Key ..
so Could you explains how it Works and Thanks

**Comment by ken2812221** [comment]
You can use `importaddress` command, you must go to https://bitcoin.stackexchange.com/ next time.

**Comment by fanquake** [comment]
Yes, this issue tracker is for technical/code development issues related to Bitcoin Core. Please use use the stack-exchange for general questions.
