### ISSUE TITLE
make check Bitcoin Core 0.16.99 FAIL: qt/test/test_bitcoin-qt.exe

### ISSUE THREAD

**Issue by edmingtsann** [bitcoin/bitcoin#13207]
root@DESKTOP-IFADPRG:/usr/src/bitcoin# make check
Making check in src
make[1]: Entering directory '/usr/src/bitcoin/src'
make[2]: Entering directory '/usr/src/bitcoin/src'
make[3]: Entering directory '/usr/src/bitcoin'
make[3]: Leaving directory '/usr/src/bitcoin'
make  check-TESTS check-local
make[3]: Entering directory '/usr/src/bitcoin/src'
make[4]: Entering directory '/usr/src/bitcoin/src'
make[5]: Entering directory '/usr/src/bitcoin'
make[5]: Leaving directory '/usr/src/bitcoin'
FAIL: qt/test/test_bitcoin-qt.exe
============================================================================
Testsuite summary for Bitcoin Core 0.16.99
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
Makefile:9772: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/usr/src/bitcoin/src'
Makefile:9878: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/usr/src/bitcoin/src'
Makefile:9977: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/usr/src/bitcoin/src'
Makefile:9665: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/usr/src/bitcoin/src'
Makefile:754: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
root@DESKTOP-IFADPRG:/usr/src/bitcoin#

Bitcoin Core 0.16.99 ; website

**Comment by fanquake** [comment]
Can you please post the `test-suite.log` and any other relevant information?

**Comment by ken2812221** [comment]
`make check` does not support WSL.
