### ISSUE TITLE
[GUI] QT shutdown is blocked if called before gettxoutsetinfo is finished

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#13217]
Steps to reproduce:
1) Open QT console.
2) Run gettxoutsetinfo.
3) Exit the debug window (no blocking) -> exit the program (will block).

This is what is shown on Windows (10) for several minutes:
[https://i.imgur.com/AyexgkC.png](https://i.imgur.com/AyexgkC.png)

**Comment by promag** [comment]
The same would happen with other long calls.

**Comment by laudaa** [comment]
It's similar to how rescan used to be uninterruptible. Is this perhaps documented somewhere already?

**Comment by jonasschnelli** [comment]
It would be easy fixable, though I don't see a big need for allowing shutdown during `gettxoutsetinfo`. @laudaa: can you elaborate more more about the use-case and why it would be required to allow a shutdown at this point?

**Comment by laudaa** [comment]
@jonasschnelli As promag as mentioned, this would occur for other long calls as well (although I'm not sure which all of these would be; gettxoutsetinfo is just the one that I encountered this with and it's notably long at ~5 minutes here). The very least that could be done is a proper exiting window informing the user that a call is still in progress (or at the very least document this somewhere if it isn't already?).
The way that it is now (see image) it looks like the software isn't working anymore ("Not responding") which will probably result in users trying to forcefully close it. This might lead to other unexpected issues (e.g., need for a reindex?).

**Comment by LeandroRocha84** [comment]
Console commands run in a separate thread (RPCExecutor) but waiting for that thread to finish takes place in the main thread, causing the GUI to become unresponsive during shutdown for long running calls.

**Comment by LeandroRocha84** [comment]
I've created the PR #13674 to address this issue. Any feedback is greatly appreciated.

**Comment by MarcoFalke** [comment]
This is an issue for the GUI and the RPC. The RPC part is fixed in #19056

**Comment by MarcoFalke** [comment]
The GUI part is fixed in #17659

**Comment by fanquake** [comment]
Given that this issue is now gui-only (RPC half fixed in #19056). I've moved it over to the [GUI repo](https://github.com/bitcoin-core/gui).
