### ISSUE TITLE
Failing to build, qt/bitcoin.cpp

### ISSUE THREAD

**Issue by angelagilhotra** [bitcoin/bitcoin#13225]
I'm building from source v0.16.0 on Ubuntu 17.10
I cloned the repo, checked out on v0.16.0, ran `./autogen.sh` followed by `./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768"`

the `make` command however produces the following error: 

```
Makefile:8224: recipe for target 'qt/qt_bitcoin_qt-bitcoin.o' failed
make[2]: *** [qt/qt_bitcoin_qt-bitcoin.o] Error 1
make[2]: Leaving directory '/home/angelag/src/bitcoin/src'
Makefile:9462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/angelag/src/bitcoin/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```
from the output of make command the errors started here: 
```
...
...
CXX      qt/qt_bitcoin_qt-bitcoin.o
In file included from ./qt/paymentrequestplus.h:10:0,
                 from ./qt/paymentserver.h:35,
                 from qt/bitcoin.cpp:25:
./qt/paymentrequest.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^~~~~
./qt/paymentrequest.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^~~~~
./qt/paymentrequest.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^~~~~
...
...
```

**Comment by ken2812221** [comment]
Did you try `make clean` and compile it again?

**Comment by angelagilhotra** [comment]
@ken2812221 yeah I did
The error persists

**Comment by ken2812221** [comment]
Can you show your config.log?

**Comment by ken2812221** [comment]
Can you try run `PATH=$(echo $PATH|sed 's/\/usr\/local\/bin://') ./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768"`

**Comment by angelagilhotra** [comment]
@ken2812221 nope, didn't work, same error
Should I be removing one version to remove ambiguity?

**Comment by angelagilhotra** [comment]
oops, sorry closed by mistake :sweat_smile:

**Comment by angelagilhotra** [comment]
I did `protoc --version` and got 
```
libprotoc 3.2.0
```

**Comment by ken2812221** [comment]
The newest official version for 17.10 is [3.0.0](https://packages.ubuntu.com/artful/protobuf-compiler), so I think you should get rid of version 3.2.0 and install official pack

**Comment by angelagilhotra** [comment]
@ken2812221 It worked! I had to perform `make clean` before building. I used the configure command you suggested: `PATH=$(echo $PATH|sed 's/\/usr\/local\/bin://') ./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768"`
Thanks!

What does `PATH=$(echo $PATH|sed 's/\/usr\/local\/bin://')` before ./configure do ? 
Should I still be replacing protoc 3.2.0 with 3.0.0 ?

**Comment by vctt94** [comment]
Have the same problem.

Running `PATH=$(echo $PATH|sed 's/\/usr\/local\/bin://') ./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768"` Also fixed it.
