### ISSUE TITLE
missing std:: at a few places after removing the namespace

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#13227]
found some places where the std:: was missed out when the namespace was removed, probably someone finds more so let's collect them here before creating a PR

https://github.com/bitcoin/bitcoin/blob/418ae49ee1eac2c9d6cd4ba83c036a41f1afe922/src/rpc/server.cpp#L162

https://github.com/bitcoin/bitcoin/blob/418ae49ee1eac2c9d6cd4ba83c036a41f1afe922/src/validation.cpp#L3780

**Comment by MarcoFalke** [comment]
Yeah, some `make_pair` are missing the `std::`, I think. However, I am closing this, because we don't track low priority refactoring tasks in issues. Either you fix all of them and create a pull request or you don't.
