### ISSUE TITLE
[Wallet Feature Request]: Multiwallet-compatible walletnotify

### ISSUE THREAD

**Issue by Kexkey** [bitcoin/bitcoin#13237]
Different wallets may be used for different purposes.  When a notification is triggered, we get the TXID but don't know which wallet is involved.  It would be useful to have different walletnotify actions depending on which wallet is involved by the transaction.

It could be used like (bitcoin.conf):

`walletnotify.walletname=action %s`

Or maybe a more simple and flexible (dynamic-wallets compatible) way:

`walletnotify=action %s %w`

where %w is the name of the wallet.  This way, notify action (and not Bitcoin Core) is responsible for choosing the right action depending on the wallet and it is easier to RPC query the good wallet (ie gettransaction).

**Comment by promag** [comment]
Sounds sensible to add support to replace the 2nd `%s` with the wallet name.

Concept ACK.

**Comment by promag** [comment]
Actually it's preferable to use a different placeholder for the wallet name, like @Kexkey suggests, because currently
```cpp
boost::replace_all(strCmd, "%s", wtxIn.GetHash().GetHex());
```
so this should work:
```cpp
boost::replace_all(strCmd, "%w", GetName());
```

**Comment by knoxcard** [comment]
Just throwing my two cents in, this is how I currently deal with incoming transactions.
Others might not be aware of this or just getting started.
It could simply adjust someone's perspective and allow them to create something entirely better.

Incoming Transaction Pseudocode
```
walletnotify=someurl/btc/:txid
cron listtransactions every minute
iterate through all the txids
txdata = gettransaction txid
if txdata.account = "users_wallet"
   add txdata as new record in table user_transactions
  confirmations = txdata.confirmations
  trans_amount = txdata.amount
  ...
end if

```

**Comment by knoxcard** [comment]
After taking one good look at this thread again, I recommend @Kexkey is definitely worth adding because of processing time.  If you are a busy platform receiving thousands of payments, you still have to iterate through every incoming transaction to determine if it belongs to a particular wallet.  Now, what does this cost CPU and memory wise?  Maybe not much, but I find it kind of ugly in terms of a programmatical approach.

**Comment by promag** [comment]
Should the wallet name be in ZMQ notifications too?

**Comment by Kexkey** [comment]
@promag I'd say ZMQ is mostly used for network events (tx and blocks) while walletnotify is tightly related to wallet(s).  So I don't think so.

But I was thinking about the credentials... should there be different authentications for the different wallets?  Is that a use case to have one node shared by multiple users/wallets?  In that case, the different usernames/passwords would make sense.

I personally would share my nodes with my family members or friends, making sure each one has its auth creds and the wallets are independently encrypted.

**Comment by isghe** [comment]
Instead of using the wallet name, could not we introduce a walletid/walletnamehash?

This to avoid escape/unescape (prone to errors) problems, shown in https://github.com/bitcoin/bitcoin/pull/13339

**Comment by promag** [comment]
@isghe I think an alternative is to use environment variables, however the implementation is not that simple.
