### ISSUE TITLE
About QT editing copyright developers

### ISSUE THREAD

**Issue by judybabyq** [bitcoin/bitcoin#13240]
Does anyone know how to change the bitcoin developers copyright line in the opening windows of the bitcoin core? If you know could you please tell which file to change it. Thanks

**Comment by jonasschnelli** [comment]
This question don't belong here... such questions may be ask in IRC, but it's certainly not an issue.

The copyright text is built via the config file (see configure.ac) and via the `CopyrightHolders()` functions in `utils.cpp`.
