### ISSUE TITLE
rpcwallet.cpp line 3488 may have a null dereference issue

### ISSUE THREAD

**Issue by wudigithub1** [bitcoin/bitcoin#13244]
version: 0.16.0
 source: wallet/rpcwallet.cpp
 line:3488
            else if (pindexStop->nHeight < pindexStart->nHeight) {

 Access to filed 'nHeight' results in a dereference of a null pointer ( loaded from variable 'pindexStart )

    in line 3473, pindexStart = chainActive.Genesis();     CChain::Genesis may return null pointer,
     Because:
        CBlockIndex *Genesis() const {
        return vChain.size() > 0 ? vChain[0] : nullptr;
    }

 when line 3477 not enter into if , pindexStart =NULL ,cause a null deference issue

**Comment by MarcoFalke** [comment]
The wallet is loaded after the genesis block, no?

**Comment by wudigithub1** [comment]
yes，genesis return nullptr and var_assigned：pindexStart = NULL；

**Comment by wudigithub1** [comment]
or I mistake the location of  chainActive.Genesis(); ‘s definition’ ?

**Comment by MarcoFalke** [comment]
See `src/init.cpp`, which first loads the chain (genesis) and then the wallet.
