### ISSUE TITLE
7485488e907e236133a016ba7064c89bf9ab6da3 broke lightning corner case

### ISSUE THREAD

**Issue by rustyrussell** [bitcoin/bitcoin#13256]
sendrawtransaction now rejects 

```
02000000000101ef682765dd04d56bfbda730487535294e58f0a70285fcc86c3e2674b3585f80c000000000000000000010000000000000000016a03483045022100bbfbaad7eda35238fb9a0da596ec1229b75aaccce4b19d97df02dfb388a82795022061f25ee6a2097fb8d5504ab4f77b2e12215f8e3cc17cda711919ff6091d897e701008976a9148517b784dbe99eb8d432a2f7981a851e7be2c7b78763ac6721030b652621b88baa0b5b221321dd297e3abee663e127b658ee26421f231c8e0be77c8201208763a91418f5da1d5c63d87c9cb7944ce2b20a2f09481e2188527c2103f2c637a05e16f4f2524a030983a3ec704281c780bd71f8cccdd3a3172a09bf3452ae6775016db175ac68686d000000
```

This is what happens when a lightning output is now considered too small for current fee levels: we create an OP_RETURN spend to give it to miners.  With master branch (commit 4cfe17c3382ba750131cdc8703b2978132822070) we now get:

```
sendrawtx exit 26, gave error code: -26?error message:?tx-size-small (code 64)?'
```

We could choose to abandon the UTXO in this case, but I consider than antisocial.

**Comment by rustyrussell** [comment]
@jl2012

**Comment by rustyrussell** [comment]
@fanquake Not an RPC issue: do you have a label for 'policy' or 'standardness'?

**Comment by fanquake** [comment]
@rustyrussell sorry, updated.

**Comment by achow101** [comment]
Since it's OP_RETURN, you could just pad the output until the entire tx non-witness size is 82 bytes. Although that could be considered a bit rude.

**Comment by jonasschnelli** [comment]
@rustyrussell: are you sure it was https://github.com/bitcoin/bitcoin/commit/4cfe17c3382ba750131cdc8703b2978132822070? This commit did only change wallet files and its very unlikely it would have changed something in the area of standardness.

**Comment by MarcoFalke** [comment]
I assume the miner donations would be more efficient (i.e. more likely to be included by miners due to higher fee per vsize) if the inputs were bundled into a single tx with appropriate sighash flags. This could be done per wallet or even by a third party taking into account inputs from different wallets.

**Comment by jl2012** [comment]
Is to possible to use an ANYONECANPAY|NONE signature, instead of using OP_RETURN? I think this would be more efficient with many such inputs

**Comment by TheBlueMatt** [comment]
Well if you're burning to fee, its probably easier to just keep around a queue of them and batch them eventually after you have a few (or, at that point, actually claim the money with some other input).

**Comment by rustyrussell** [comment]
Waiting for batching almost certainly means they'll never be spent. Wallets have to maintain significant state to spend these outputs (they were generated by mutual agreement with a peer), which will be lost in the long run.

We could sighash_none: that's a good idea. It still doesn't solve this regression, however! Nor does it do anything until someone writes code to collect these.

**Comment by jl2012** [comment]
@rustyrussell Why you "hope" someone steals it? You could use `SIGHASH_NONE` _AND_ keep a queue of these signatures for claiming it later!
