### ISSUE TITLE
Bitcoin cross-platform build for Windows 64 hang 

### ISSUE THREAD

**Issue by nirajkr** [bitcoin/bitcoin#13260]
I have followed the instruction to build windows build on ubuntu 16 

https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

All the exe get build successfully but when I move it to windows machine None of the exe is working. It just hang and dont exit or output any result (bitcoin-cli.exe, bitcoind.exe,bitcoin-qt.exe).

Even help command don't produce any output and it stays hang. Any help

**Comment by ken2812221** [comment]
Please make sure that your anti-virus does not block the executable.

**Comment by nirajkr** [comment]
No I have re-checked it by disabling all anti-virus . Its very weired  I am using Windows 10 64 bit.

 Please find the below screen shot




![bitcoin_windows_build](https://user-images.githubusercontent.com/6111688/40165866-b741b7e0-59da-11e8-8ce3-57f6d7a5c120.jpg)

**Comment by NicolasDorier** [comment]
You need to build with 18.04, not ubuntu 16. It is mentioned in build notes https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md
