### ISSUE TITLE
Remove redundant 'break'.

### ISSUE THREAD

**Issue by wudigithub1** [bitcoin/bitcoin#13272]
version: 0.16.0
source: /src/httpserver.cpp
line 196、199、202、205:  dead code

    switch (m) {
    case HTTPRequest::GET:
        return "GET";
        break;
    case HTTPRequest::POST:
        return "POST";
        break;
    case HTTPRequest::HEAD:
        return "HEAD";
        break;
    case HTTPRequest::PUT:
        return "PUT";
        break;

**Comment by wudigithub1** [comment]
switch (m) {
case HTTPRequest::GET:
    return "GET";
    break;  //dead code

**Comment by ken2812221** [comment]
It's a good C++ programming style and will be optimized by the compiler.

**Comment by wudigithub1** [comment]
yes, i agree this is a code quality issue.  Do you think it need to be modified?

**Comment by sipa** [comment]
I think it would be a regression to make this change.
