### ISSUE TITLE
getblocktemplate fails in regtest mode even when it is connected to the other node

### ISSUE THREAD

**Issue by nirajkr** [bitcoin/bitcoin#13274]
I have created two nodes and connected the 1st node with the 2nd node in regtest mode . Now when I make the getblocktemplate command using bitcoin-cli . It fails with bitcoin is downloading the block.
 
Bitcoin core vs v0.16

_admin1@root:~/Projects/bitcoin$ ./src/bitcoin-cli -regtest -port=8333 -rpcport=8332 -rpcuser=test -rpcpassword=test getconnectioncount_
**1**
_admin1@root:~/Projects/bitcoin$ ./src/bitcoin-cli -regtest -port=8333 -rpcport=8332 -rpcuser=test -rpcpassword=test getblocktemplate_
**error code: -10
error message:
Bitcoin is downloading blocks.**

**Comment by MarcoFalke** [comment]
You might want to generate/download at least one block first

**Comment by cyxinyi** [comment]
how to resolved
