### ISSUE TITLE
"resource leak " issue

### ISSUE THREAD

**Issue by wudigithub1** [bitcoin/bitcoin#13270]
version:  0.16.0
source:  /src/wallet/rpcwallet.cpp
line 606: resource leak

in line 590:
     HTTPEvent* ev = new HTTPEvent(eventBase, true, [req_copy, nStatus]{

but in the end of code segment，"ev" is not released.

**Comment by fanquake** [comment]
Thanks, this was also reported in #12961.

**Comment by wudigithub1** [comment]
OK.
