### ISSUE TITLE
Hidden tray icon even when not selected.

### ISSUE THREAD

**Issue by priem19** [bitcoin/bitcoin#13296]
While 'Minimize to the tray instead of the taskbar' and 'Minimize on close' is selected, and the Bitcoin Core Wallet window gets minimized, it sometimes disappears without showing in the system tray, forcing the user to signal termination via a task manager because maximizing isn't possible. Even when 'Hide tray icon' is unselected.

When minimizing or closing the Bitcoin Core Wallet window, it should show up in the system tray.

The Bitcoin Core Wallet window disappears, does not get shown in the tray, and with no way of maximizing or utilizing it

Minimize or close Bitcoin Core Wallet window while the following options are selected:
- 'Minimize to the tray instead of the taskbar'
- 'Minimize on close'

and this one unselected:
- 'Hide tray icon'

v0.16.0. https://bitcoin.org/nl/download. Linux 64 bit.

OS: Linux Mint 18.3 Sylvia (Xfce) (Compiz as window manager)
CPU: Intel i7 3820
Disk: WD Caviar GP WD20000CSRTL2, 2TB

**Comment by Blackadderrr** [comment]
I have no idea because I've since changed my distro.
