### ISSUE TITLE
check before operator

### ISSUE THREAD

**Issue by wudigithub1** [bitcoin/bitcoin#13290]
version: 0.16.0
source: /src/arith_uint256.cpp
line 179 : if (pn[pos] & 1 << nbits)

when ( pn[pos] & 1) =1 and nbits = 31, can result in overflow

**Comment by ken2812221** [comment]
Why?

**Comment by wudigithub1** [comment]
the operation '<<' on signed integer cam result in overlow when the left operand's value is '1' and the right operand's(nbits) value is '31'

**Comment by Empact** [comment]
This is uint math, as indicated in the class and file names.

**Comment by sipa** [comment]
@Empact No, this is in the internal implementation of uint256; the type of `pn[pos]` is uint32_t.

@wudigithub1 The expression `pn[pos] & 1` is uint32_t, which is unsigned so shifting up by 31 bits is fine.

**Comment by Empact** [comment]
@sipa yes we're in agreement. The underlying data is unsigned so the concern does not apply.

**Comment by wudigithub1** [comment]
thanks，i understand and close the issue
