### ISSUE TITLE
GUI: ShowProgress is missing during ReplayBlocks()

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#13303]
During rolling forward in `ReplayBlocks()` the UI progress starts with 0 then, once sync up again, jumps to 100%. This process can take pretty long and it would be good to show some progress steps within the RollingForwardBlock loop (`for (int nHeight = nForkHeight + 1; nHeight <= pindexNew->nHeight; ++nHeight) {`)

**Comment by promag** [comment]
Concept ACK.
