### ISSUE TITLE
RPC API reqSigs for P2SH outs

### ISSUE THREAD

**Issue by 4tochka** [bitcoin/bitcoin#13331]
When I call RPC  API 
`> bitcoin-cli getrawtransaction de816dca84ab4af9c98f40d826807aa93600978acf62cfa98bc148c80f789c92 1`

Response contains:

 {
      "value": 0.29932592,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_HASH160 59671c40861324648e16c461ded83672ccaf3609 OP_EQUAL",
        "hex": "a91459671c40861324648e16c461ded83672ccaf360987",
        **"reqSigs": 1,**
        "type": "scripthash",
        "addresses": [
          "39qjarFnk49tD9cJR5iMqiJupY2v2vNeg4"
        ]
  }

But script under P2SH address unknown and we cant count  real reqSigs 
API give "reqSigs": 1  for all P2SH outs, I suppose that this behavior is not correct

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
