### ISSUE TITLE
Windows: bitcoin-qt.exe leveldb assertion failed.

### ISSUE THREAD

**Issue by murrayn** [bitcoin/bitcoin#13333]
leveldb assert() fail on Windows as per screenshot.

![bitcoin-qt](https://user-images.githubusercontent.com/5404807/40584588-541fe3a0-6158-11e8-9605-c5a55b7bf499.png)

Official Windows v0.16.0 release.

The last debug.log entry before the crash:

2018-05-27 08:21:41 UpdateTip: new best=000000000000000000071dfc4ed27cdfb03559f91a7470bc9863ae0e62a2991c height=524611 version=0x20000000 log2_work=88.894279 tx=318748815 date='2018-05-27 08:19:51' progress=0.999999 cache=62.6MiB(378174txo)

**Comment by murrayn** [comment]
Probably relevant: router was reset around this time.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core?

It could be a hardware issue. Bitcoin Core makes heavy use of CPU, RAM and disk IO. Hardware defects might only become visible when running Bitcoin Core. You might want to check your hardware for defects.

* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206
