### ISSUE TITLE
RFC: C++14 Requirement

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#13356]
Opening an issue after some recent [IRC discussion](https://botbot.me/freenode/bitcoin-core-dev/2018-05-30/?msg=100617206&page=4) about moving to requiring [C++14](https://en.wikipedia.org/wiki/C%2B%2B14).

#### GCC:
C++14 is available from GCC 5, and is the default mode in [GCC 6.1](https://gcc.gnu.org/projects/cxx-status.html#cxx14). 
"The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98.".
We currently require GCC 4.8+.

#### Clang:
C++14 is available from Clang [3.4+](https://clang.llvm.org/cxx_status.html). 
We currently require Clang 3.3+.

#### Usage:
We currently already use shared mutex.

**Comment by MarcoFalke** [comment]
I think we should wait for trusty to be EOL, which probably happens around the day we release 0.18.0

**Comment by luke-jr** [comment]
Latest RHEL is only GCC 4.8.x

**Comment by MarcoFalke** [comment]
Also should check OpenSuse and CentOS.

According to today's irc chat debian oldstable will only support C++14 in time for our ~0.19.0 release:

https://botbot.me/freenode/bitcoin-core-dev/2018-05-31/?msg=100660663&page=4

**Comment by MarcoFalke** [comment]
@practicalswift Unless there are any objections, we can do the switch on the day that master is branched from 0.18.0.

See #14438

```
2019-03-01
-----------
- Split off `0.18` branch from `master`
```

The pull request itself can be prepared and reviewed in advance, of course.

**Comment by practicalswift** [comment]
@MarcoFalke Excellent news! Thanks for the quick reply!

**Comment by MarcoFalke** [comment]
This is now up for grabs. The previous bump was done in  "build: Enable C++11 in build, require C++11 compiler" #7165

**Comment by gmaxwell** [comment]
The current released version of RHEL is still on GCC 4.8, and even when things are released we can't expect users to be instantly upgraded.  I'm somewhat concerned that we're going to block the next softfork's activation the way we did with segwit by mandating a new OS in the release of or before the softfork and then end up with mining pools unwilling to upgrade for six months because it requires a whole new OS.

**Comment by JeremyRubin** [comment]
Is there a problem running a binary compiled with c++14 on a machine that only has a c++11 compiler? The RHEL OS requirement would purely be for _building Core_, which seems unlikely to be a blocking factor for adopting a soft fork? Unless there is something I'm missing...

**Comment by luke-jr** [comment]
Usually binaries only run on the system they're built on.

**Comment by gmaxwell** [comment]
@JeremyRubin Miners routinely modify their software and we encourage them to do so (at least in various sensible ways). If you can't compile you can't run your modifications.   Also, and perhaps more importantly,  critical fixes are always first available as source code.

Before we actually experienced the issue I would have regarded the concern as largely hypothetical, it was an excusable mistake.  I don't see why we shouldn't learn from that mistake...

**Comment by JeremyRubin** [comment]
Thanks for the information on that @gmaxwell. I was unaware that there was an issue with that during SegWit -- do you have any link to discussion on this? I was unable to find it in my bitcoin-dev email archives, just this article https://www.nasdaq.com/article/where-bitcoin-mining-pools-stand-on-segregated-witness-cm713991 / tweet https://twitter.com/satofishi/status/843910700124717058

@luke-jr I know that's generally true (e.g., Linux, Windows, and OSX). But I figured for Bitcoin the compatibility is sufficient across most linux distributions so as not to require recompilation per-distro. Perhaps it depends on what kinds of changes miners are compiling in...



anyways, I'm indifferent on if to upgrade to 14 or not (the changes in 14 are relatively minor and low advantage compared to say, 17). Just wanted to learn more about the practical issue.

**Comment by luke-jr** [comment]
There is basically no compatibility across Linux distributions, even different versions of the same distro are likely to have issues sometimes.

And despite our efforts to build a hacky gitian static binary that is supposed to run everywhere, in practice even that seems to be a failure (I can't run them!). In any case, the gitian process currently includes a significant amount of trust, and people *shouldn't* be required to use its binaries.

**Comment by MarcoFalke** [comment]
Moved to "Future" due to concerns that this will break builds on currently supported platforms.

**Comment by ysangkok** [comment]
> The current released version of RHEL is still on GCC 4.8, and even when things are released we can't expect users to be instantly upgraded.

Just want to note that RHEL 8 (with [GCC 8.2](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/compilers-and-development-tools_considerations-in-adopting-rhel-8)) has been out for half a year now. And Ubuntu 18.04 has gcc-8 in universe.

Which distributions are most popular with miners?

**Comment by MarcoFalke** [comment]
Some might be using CentOS 7

**Comment by ajtowns** [comment]
> Some might be using CentOS 7

Red Hat has a [devtoolset](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/) software collection that provides a new version of gcc and such for either RHEL or CentOS. I get gcc 8.3.1 on CentOS 7 if I run:

```
# yum install centos-release-scl
# yum install devtoolset-8
# scl enable devtoolset-8 bash
# gcc --version | head -n1
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
# exit
# gcc --version | head -n1
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```

Doing `yum install boost-devel libevent-devel openssl-devel` lets me build with `--disable-wallet` in that environment. I think that should let you get a newer compiler on RHEL/CentOS 6 as well? Looks like [clang](https://www.softwarecollections.org/en/scls/rhscl/llvm-toolset-7/) is available too.

**Comment by MarcoFalke** [comment]
CentOS 8 was released a few days ago, so it seems ok to move forward with this for 0.20.0?

**Comment by practicalswift** [comment]
@MarcoFalke Yes please! :)

**Comment by MarcoFalke** [comment]
Closing. C++17 should be the next bump, it seems
