### ISSUE TITLE
0 Sat Fees Not Possible, Can't Send Transaction without fees !

### ISSUE THREAD

**Issue by cruxby** [bitcoin/bitcoin#13354]
hello, as a small company we have so much dust wallets !

we wanted to move out dust amounts to a single wallet, only way this process could be beneficial is by having 0 sat fees, don't want that child pays for parent mess !

we were unable to use 0 fees transactions from core, is there any problem on bitcoin core or it could be something on my end ?

**Comment by cruxby** [comment]
@MarcoFalke  the thing is I want to clear dust, I can take chances and wait for long time for confirmation,

but -minrelaytxfee is not allowing to process 0 Sat/byte fees transaction, I really like when the fees controlled by the users.

we can't overpay, its like
1000 * 4$ wallets, but the out is distributed among many address, so the transaction size is bigger, thus we only want to process 0 sat/byte

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
