### ISSUE TITLE
Make update-translations.py script check for bitcoin addresses

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#13363]
Someone on the Russian translation added a bitcoin address into the translation, with the idea of confusing people to send coins there. Luckily no one fell for it, but this could have been different.
(was reverted in https://github.com/bitcoin/bitcoin/commit/4ea3e8ef070417ccc22007407d78fa0a41949bee#diff-77c4348ab69f5c434e7b9eda0a655549R66)

To avoid this, an idea would be to add a check to the `contrib/devtools/update-translations.py` script that checks each message for valid bitcoin addresses, and warn, as well as drop the message if it encounters one.

(edit: the "valid" check is not even necessary, I think it would be enough to reject things that look like addresses with a regexp)

**Comment by undercoverGod** [comment]
I would like to work on this
