### ISSUE TITLE
RFC: Set minimum required macOS version to 10.10

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#13362]
After some discussion with @jonasschnelli, I've put together a few notes about increasing our minimum supported version of macOS.

Our current minimum is [10.8](https://github.com/bitcoin/bitcoin/blob/master/depends/hosts/darwin.mk#L1).
We're using the 10.11 [SDK](https://github.com/bitcoin/bitcoin/blob/master/depends/hosts/darwin.mk#L2).

There's currently #12971 open to upgrade Qt in depends to 5.9.x (up from 5.7.1). Starting with Qt 5.9.x the minimum supported version of macOS is [10.10](https://wiki.qt.io/Qt_5.9_Tools_and_Versions#osx_10.10_x86_64).

Targeting 10.10+ should allow us to remove some macOS specific backwards compatibility code as well:
* Font substitution in [guiutil.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L420).
* Weak linking in [macnotificationhandler.mm](https://github.com/bitcoin/bitcoin/blob/master/src/qt/macnotificationhandler.mm#L36). Note this could probably be dropped already, due to 10.8+.

@theuni be good to get your thoughts re Clang, cctools, macOS SDK etc.

Tagged with a 0.17.0 milestone, as if we plan to upgrade Qt in depends, this will need addressing somehow.

**Comment by practicalswift** [comment]
Concept ACK

More generally I don't think we should support OS versions no longer receiving proper security updates by their vendor.

**Comment by theuni** [comment]
Concept ACK, I think this is the right call.

**Comment by laanwj** [comment]
Concept ACK

**Comment by fanquake** [comment]
Given that there's some agreement here, and Qt 5.9.x seems to be going ahead for 0.17, I'll get started on these changes.

**Comment by WorkShop-Office** [comment]
Hahaha

**Comment by Sjors** [comment]
#14953 probably broke unit tests for macOS 10.10, though can be (partially) worked around.
