### ISSUE TITLE
[I need your help] Bitcoin

### ISSUE THREAD

**Issue by KayleyWong** [bitcoin/bitcoin#13361]
Hi guys, I really need your help on this. It has stated in my wallet that i've received my bitcoins of 1.182691BTC on 29/05/18. This's my wallet address: muFjdWSy2DKStSP2gUH2aHZq6kRBva8ZDV it stated on the insight.bitpay.com. It stated confirmed. However, i can't send out to another wallet address as it stated insufficient funds. Please advise me what should i do? Is it a scam?

My transaction ID is b2898b8c5f5f01f573e768ec21fc4f15c1e433e7255960fb71551f06cec36651. It seems that my transaction confirmed. What should I do next? I’m stuck.

**Comment by sipa** [comment]
This is not a support site. Try https://bitcoin.stackexchange.com.

**Comment by susieinkansas** [comment]
Yep
