### ISSUE TITLE
[Debugging]: Debugging not working with Windows mingw64?

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#13377]
Hello,

I compiled the Bitcoin Wallet with --enable-debug to use it on Windows for debugging.
On Windows I am using gcc mingw64.

After I used gdb (run) It is loading until it shows "Loading Blockindex..." or "Loading Wallet..."
While loading this the bitcoin-qt crashed and GDB shows "received Sigmentation fault SIGSERV".

Any fix here?

Regards,
Pawel

**Comment by globaltoken** [comment]
@MarcoFalke Attached here.

I am not very familar with gdb debugging, so if you want me to do more steps, let me know.
[error.txt](https://github.com/bitcoin/bitcoin/files/2066298/error.txt)

**Comment by globaltoken** [comment]
BTW: If I start the wallet normally, It don't crash.
It works.

But if I start debugging in GDB, then it crashes with SIGSEV.

**Comment by MarcoFalke** [comment]
Can you use gdb fine on exe files that are not bitcoin core?

**Comment by globaltoken** [comment]
@MarcoFalke Yeah for other debugging programs it works.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
