### ISSUE TITLE
URGENT ISSUE: Github is now owned by M$

### ISSUE THREAD

**Issue by Viral** [bitcoin/bitcoin#13387]
please move to gitlab or something better. ipfs?

thank you.

**Comment by victorperin** [comment]
I don't think moving to GitLab will solve the problem. But I'm really concerned about bitcoin source code if for some reason they change something.
This could be an opportunity to look at more decentralized hosting way.

I don't know much, but I've heard about [SSB protocol](https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256).
I think this could be a way.

**Comment by sipa** [comment]
While I believe we should always consider other options, and would support in the long term moving to other infrastructure, I don't believe there is an issue here.

We are already not relying strongly on GitHub. All merges of code into the master branch are PGP signed by the maintainer who merges, which is automatically verified. The code itself is mirrorred by developers themselves, and we could easily add other mirrors too. Finally, release binaries are distributed using https://bitcoincore.org, and again use a well-audited system (gitian deterministic builds).

We mostly use GitHub for its ease of access and community, and not so much for actually managing or controlling or source tree. Unless that changes, I see no reason why the company running it should influence our decision.

**Comment by laanwj** [comment]
Yes there is no *urgent* issue here. As @sipa says, we already don't use github's merging, but do so with our own script that checks for a clean merge, allows local reviewing, and signs the commit automatically.

This doesn't preclude hosting somewhere else, too, though.

If you're concerned about not being able to get the code except through Microsoft infrastructure I started a mirror of certain important bitcoin-related repositories on a Tor hidden service: [nxshomzlgqmwfwhcnyvbznyrybh3gotlfgis7wkv7iur2yj2rarlhiad.onion](http://nxshomzlgqmwfwhcnyvbznyrybh3gotlfgis7wkv7iur2yj2rarlhiad.onion/), this can be useful for other reasons too, the sale of GitHub was just my wake-up call to do it.
