### ISSUE TITLE
ARMv8 sha2 support

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13401]
I assume #13191 make this less hard, although benefits may be small. Brief [chat on IRC](https://botbot.me/freenode/bitcoin-core-dev/2018-06-05/?msg=100812298&page=2):

Me
> While trying to get bitcoind to run on one the many *-pi's out there, I wondered: has anyone ever tried to design a system on chip that's optimal for this?

@laanwj:
> provoostenator: you mean secp256k1 specific instructions? people have been thingking about it, could be done on a FPGA, but I don't think it's ever been done

Me: 
> echeveria seems to believe sha256 is the bottleneck (see #bitcoin), but also that anything outside the CPU would be too slow I/O to be worh it.

echeveria:
> I looked at the Zynq combination FPGA / ARM devices a long time ago and came to the conclusion that the copy time even on the shared memory bus between the two chips would make it non viable. I'd enjoy being proved wrong though.

laanwj:
> provoostenator: well sha256 extension instructions exist for ARM (supported on newer SoCs), I intend to add support for them at some point. But I would be surprised if that is the biggest bottleneck in validation.

echeveria:
> yes, if there is high-bandwidth communication between two chpis that tends to dominate. I was > thinking of, say, RiscV extensions for secp256k1 validation so it's in-core.
> for ARM it's somewhat unlikely at this time

I have (at least) three devices to test this on, which all have 4 to 8 ARM Cortex-A53 cores, and 1- 4 GB RAM: an Android Xiaomi A1 ([ABCore](https://github.com/greenaddress/abcore) syncs the whole chain in less than a month), a NanoPi Neo Plus and a Khadas VIM2 Max.

Maybe this c++ code is useful: https://github.com/randombit/botan/issues/841

**Comment by laanwj** [comment]
Thanks for creating an issue to track this. I'll try to add some information in case someone wants to pick this up, if someone doesn't want to wait for me to do so.

To check programmatically if SHA256 instructions are supported on an ARM platform in Linux, one can do:
```c++
#include <arm_acle.h>
#include <sys/auxv.h>
#include <asm/hwcap.h>
...
#elif defined(__aarch64__)
  return (getauxval(AT_HWCAP) & HWCAP_SHA2) != 0;
#elif defined(__arm__)
  return (getauxval(AT_HWCAP2) & HWCAP2_SHA2) != 0;
#else...
```

**Comment by Sjors** [comment]
Also this: https://github.com/noloader/SHA-Intrinsics

**Comment by rollmeister** [comment]
I have attempted to apply SHA256 ArmV8 acceleration for secp256k1 however due to this library using ANSI 89 standard code the intrinsic's refuse to compile: I have however added it and CRC32 to a fork I made for the rest of Bitcoin Core. Block processing performance should improve if it could be extended to secp256k1. Basically would be little more than a copy and paste of the code in sha256.cpp and changing the compiling scripts, at my guess anyway. I lack the skill to do so anytime soon.

**Comment by sipa** [comment]
@rollmeister The SHA256 implementation inside libsecp256k1 isn't performance critical (specifically, it's only used for signing and not used during block validation). We should just focus on the SHA256 in the Bitcoin Core crypto/ directory.

**Comment by rollmeister** [comment]
@sipa Yes I did some more testing and its invoked there infrequently. My code is in the fork in either case and it is up to the Bitcoin developers (if they are interested) to merge the implementation into the main branch using maintainable separate source files and updated build scripts. I do not intend to do so myself, as I have satisfied my own curiosity and personal needs with the work I have done so far.

**Comment by denravonska** [comment]
@rollmeister Has there been any update on your ARM optimizations? A lot of altcoins would be very happy to see it implemented.

**Comment by laanwj** [comment]
Looks like I had a competing issue about the same open (#17414) 😄

**Comment by prusnak** [comment]
Since there are lot of people that are using Raspberry Pi for running a full node - this might be also worth investigating:
* https://github.com/obijywk/qpusha - Hardware-accelerated SHA-256 hashing on the Raspberry Pi (utilizing VideoCore IV Quad Processors)

**Comment by prusnak** [comment]
PR implementing this in https://github.com/bitcoin/bitcoin/pull/24115
