### ISSUE TITLE
bitcoind daemon + reindex does not daemonize 

### ISSUE THREAD

**Issue by linux-mining** [bitcoin/bitcoin#13405]
-daemon flag is ignored

Expected bitcoind to background itself

runs in the foreground. If you disconnect from session it dies. 

Everytime

From website, latest version 0.16

**Comment by achow101** [comment]
What OS are you using? What is the full command you are using? Can you post the contents of your bitcoin.conf? Can you post the contents of the debug.log file?

**Comment by linux-mining** [comment]
Confirmed this morning even after indexing was finished, still failed to background itself.  The -daemon flag works on all other options I've tried so far. 

Not sure if this is intentional?

**Comment by laanwj** [comment]
Cannot reproduce this here (Ubuntu 16.04):
```
$ src/bitcoind -rescan -daemon -datadir=/store/tmp/testbtc.reindex
Bitcoin server starting
$
```

**Comment by linux-mining** [comment]
I've reproduced now on two separate machines. (Fedora 28 and CentOS 7) Same behavior. 

Why is -server not necessary? I am able to run rpc without it? Sorry I'm not in front of my machine now.

**Comment by sipa** [comment]
`-server` is for enabling RPC when running the GUI (`bitcoin-qt`). When you run `bitcoind`, the RPC server is always enabled (otherwise it wouldn't serve any function).

**Comment by linux-mining** [comment]
Ah yes, that makes perfect sense. 

Perhaps leaving that flag off with fix it?

**Comment by sipa** [comment]
No, `-server` should be completely unrelated to your issue.

**Comment by MarcoFalke** [comment]
Could not reproduce on fresh fredora 28:

```
$ lsb_release -d && ./bitcoin-0.16.0/bin/bitcoind -daemon -reindex -server 
Description:	Fedora release 28 (Twenty Eight)
Bitcoin server starting
$

**Comment by linux-mining** [comment]
./bitcoind -daemon -txindex -server
./bitcoin-cli stop
./bitcoind -daemon -server
Asks me to run with -reindex
./bitcoind -reindex -server    #does not background, even when done indexing. I can reproduce everytime

**Comment by MarcoFalke** [comment]
Still can't reproduce

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by kristapsk** [comment]
> Asks me to run with -reindex
> ./bitcoind -reindex -server

You don't have -daemon flag here.

With "bitcoind -daemon -reindex" I also can't reproduce this under Gentoo Linux.

**Comment by linux-mining** [comment]
Typo, fixed it. It was run with the daemon flag for sure
