### ISSUE TITLE
Build: make distclean doesn't fully clean up.

### ISSUE THREAD

**Issue by murrayn** [bitcoin/bitcoin#13433]
`make distclean` should clean up all files created by `configure` and `make`.

These files are left behind currently:

  aclocal.m4
  autom4te.cache
  build-aux/compile
  build-aux/config.guess
  build-aux/config.sub
  build-aux/depcomp
  build-aux/install-sh
  build-aux/ltmain.sh
  build-aux/m4/libtool.m4
  build-aux/m4/lt\~obsolete.m4
  build-aux/m4/ltoptions.m4
  build-aux/m4/ltsugar.m4
  build-aux/m4/ltversion.m4
  build-aux/missing
  build-aux/test-driver
  configure
  doc/man/Makefile.in
  Makefile.in
  src/config/bitcoin-config.h.in
  src/config/bitcoin-config.h.in~
  src/Makefile.in
  src/secp256k1/aclocal.m4
  src/secp256k1/autom4te.cache
  src/secp256k1/build-aux/compile
  src/secp256k1/build-aux/config.guess
  src/secp256k1/build-aux/config.sub
  src/secp256k1/build-aux/depcomp
  src/secp256k1/build-aux/install-sh
  src/secp256k1/build-aux/ltmain.sh
  src/secp256k1/build-aux/m4/libtool.m4
  src/secp256k1/build-aux/m4/lt\~obsolete.m4
  src/secp256k1/build-aux/m4/ltoptions.m4
  src/secp256k1/build-aux/m4/ltsugar.m4
  src/secp256k1/build-aux/m4/ltversion.m4
  src/secp256k1/build-aux/missing
  src/secp256k1/build-aux/test-driver
  src/secp256k1/configure
  src/secp256k1/Makefile.in
  src/secp256k1/src/libsecp256k1-config.h.in
  src/secp256k1/src/libsecp256k1-config.h.in~
  src/univalue/aclocal.m4
  src/univalue/autom4te.cache
  src/univalue/build-aux/compile
  src/univalue/build-aux/config.guess
  src/univalue/build-aux/config.sub
  src/univalue/build-aux/depcomp
  src/univalue/build-aux/install-sh
  src/univalue/build-aux/ltmain.sh
  src/univalue/build-aux/m4/libtool.m4
  src/univalue/build-aux/m4/lt\~obsolete.m4
  src/univalue/build-aux/m4/ltoptions.m4
  src/univalue/build-aux/m4/ltsugar.m4
  src/univalue/build-aux/m4/ltversion.m4
  src/univalue/build-aux/missing
  src/univalue/build-aux/test-driver
  src/univalue/configure
  src/univalue/Makefile.in
  src/univalue/univalue-config.h.in
  src/univalue/univalue-config.h.in~
  
Ubuntu 16

**Comment by murrayn** [comment]
Going to close this, as it would seem the problems are with autogen.sh/configure, and fixes should be applied there.

**Comment by scravy** [comment]
You can use `git clean -xdf` to wipe.
