### ISSUE TITLE
Should `onlynet=onion` allow incoming non-tor connections?

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#13436]
It is noted in https://github.com/bitcoin/bitcoin/issues/13378#issuecomment-395467866 that `onlynet` only affects outgoing connections. I take this to mean a user running `onlynet=onion` will happily accept incoming, non-tor connections on their node. It feels like a user running with `onlynet=onion` option would not want their node to accept incoming non-tor connections.

**Comment by sipa** [comment]
`doc/tor.md` explains this and suggests using `-bind=127.0.0.1` to mitigate this.

**Comment by sipa** [comment]
Right, you can see the source of an incoming connection, but that source may be a proxy. Tor connections always come through tor which acts as proxy, so bitcoind just sees the IP address of the proxy. There may be other reasons why connections seem to come from a known or unknown proxy.

**Comment by kallewoof** [comment]
Got it. Perhaps it would be useful with a warning when seeing `-onlynet=tor` if it is not also seeing `-bind=localhost`.

**Comment by laanwj** [comment]
I don't think `onlynet` affects binding *at all*, that's seperate.

Maybe it should, but it'd be a change from current behavior.

**Comment by laanwj** [comment]
Regarding detection of incoming Tor connections (at least from the automatic Tor hidden sevice setup), see #8973 "Incoming tor connections should use alternative port".

**Comment by wodry** [comment]
Nit: I guess You mean `onlynet=onion`

**Comment by kallewoof** [comment]
I don't think this issue will find a resolution here, so I'm closing.
