### ISSUE TITLE
Build: ./configure --enable-debug generates -O2 optimization option which overrides earlier -Og.

### ISSUE THREAD

**Issue by murrayn** [bitcoin/bitcoin#13432]
` ./configure --enable-debug` generates -O2 gcc option, overriding earlier -Og option which is the correct optimization level for -g debugging.

  CFLAGS        = -g -O2
  [...]
  CXXFLAGS      =  -Og -g3  -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wformat -Wvla -Wformat-security  -Wno-unused-parameter   -g -O2

Ubuntu 16 and OSX 10.13

**Comment by ken2812221** [comment]
You can use `--disable-maintainer-mode` to disable those flags.

**Comment by kallewoof** [comment]
Shouldn't `--enable-debug` automatically do `--disable-maintainer-mode` in that case? Currently `--enable-debug` is useless at least on macs, as it still generates optimized code so lldb barfs.

**Comment by murrayn** [comment]
@ken2812221 Why did you close your PR #13434? At first glance it looked good to me.

**Comment by ken2812221** [comment]
You can still use `./configure --enable-debug --disable-maintainer-mode` to do what you want, so I don't think this is a bug.

**Comment by luke-jr** [comment]
@kallewoof IF `--disable-maintainer-mode` has any effect here, it is accidental, not the purpose of the flag. It shouldn't. `-g -O2` *should* be the default CFLAGS (without `--enable-debug`) with or without maintainer mode.

**Comment by kallewoof** [comment]
@luke-jr Right. Currently, `-g -O2` are the C*FLAGS even if you do `--enable-debug`, which results in optimized binaries that cannot be reliably debugged using lldb on macs. I was not able to use lldb until I realized I had to manually edit the makefile to replace `-g -O2` with `-g` in order to get debuggable binaries.
