### ISSUE TITLE
[RFC] gui: Minimum required Qt5

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#13478]
~~With removal of support for Qt4 [not far away](https://github.com/bitcoin/bitcoin/pull/13458), opening this for any thoughts on setting a minimum required qt5 version. It could be quite possible for us to support Qt 5.0+.~~

Qt4 support was removed in #13458.
The current minimum required Qt is `5.2`. Set in #14725.

#### [Qt Versions](https://download.qt.io/official_releases/qt):
[5.12 (LTS)](https://doc.qt.io/qt-5.12/supported-platforms.html) Supported for 3 years post release.
[5.11](https://doc.qt.io/qt-5.11/supported-platforms.html) Supported until May 2019
[5.10](https://doc.qt.io/archives/qt-5.10/supported-platforms.html) Supported until Dec 2018 (Archived).
[5.9 (LTS)](https://doc.qt.io/qt-5.9/supported-platforms.html) Supported until May 31, 2020.
[5.6 (LTS)](https://doc.qt.io/qt-5.6/supported-platforms.html) Supported until Mar. 16, 2019 (will end around the same time as the `v0.18.0` release).

Any other releases older than 5.10 are no longer supported (by Qt).

Qt releases seem to be getting more frequent, and in some cases more aggressive about dropping support for OS versions. i.e macOS >`10.12` is required for Qt `5.12`.

#### Qt Feature Usage:
There are the following usages of `QT_VERSION` (excluding bitcoin_qt.m4) in the code:
* [QT_VERSION >= 0x050600](https://github.com/bitcoin/bitcoin/blob/master/src/qt/bitcoin.cpp#L446) - 5.6+ Enables high-DPI scaling on supported platforms.

* ~~[QT_VERSION >= 0x050500](https://github.com/bitcoin/bitcoin/blob/master/src/qt/bitcoin.cpp#L595) - 5.5+ Disable SSL and use TLS 1.0+.~~

* [QT_VERSION < 0x050400](https://github.com/bitcoin/bitcoin/blob/master/src/qt/bitcoin.cpp#L58) // Import AccessibleFactory plugin.

* [QT_VERSION >= 0x050300](https://github.com/bitcoin/bitcoin/blob/master/src/qt/test/rpcnestedtests.cpp#L123) - 5.3+ tests using QVERIFY_EXCEPTION_THROWN.

* ~~[QT_VERSION >= 0x050200](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L64), [QT_VERSION >= 0x050200](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L94) - 5.2+ Returns the most appropriate system font.~~
* ~~[QT_VERSION >= 0x050200](https://github.com/bitcoin/bitcoin/blob/master/src/qt/macdockiconhandler.mm#L59) - Set this menu to be the dock menu available by option-clicking on the application dock icon. macOS only.~~

* ~~[QT_VERSION > 0x050100](https://github.com/bitcoin/bitcoin/blob/master/src/qt/bitcoin.cpp#L585) - 5.1+ Support for high-dpi pixmaps.~~
* ~~[QT_VERSION > 0x050100](https://github.com/bitcoin/bitcoin/blob/master/src/qt/splashscreen.cpp#L39), [QT_VERSION > 0x050100](https://github.com/bitcoin/bitcoin/blob/master/src/qt/splashscreen.cpp#L55) - Sets the device pixel ratio for the splash-screen.~~

* ~~[QT_VERSION >= 0x050000](https://github.com/bitcoin/bitcoin/blob/master/src/qt/paymentrequestplus.cpp#L100) - Determine if a certificate is blacklisted.~~ Removed in #13458.

**Comment by MarcoFalke** [comment]
Many distributions come with older versions of qt, e.g. https://packages.ubuntu.com/xenial/libs/qt5-default

**Comment by fanquake** [comment]
Per platform Qt minimums was bought up in #13561, suggesting that on macOS the minimum could be bumped to take advantage of Qt's [Mac Extras module](https://doc.qt.io/qt-5/qtmac.html), which has been available in >5.2.

I'm currently -0 on that idea, as I think it'll lead to complication in the depends system, and the qt portion of the code base.

However, interested to hear other opinions, and potential advantages of that approach.

**Comment by Sjors** [comment]
Depends uses 5.9.6 as per  #12971, so unless there's a reason someone can't use the depends system, it seems safe to set the minimum to 5.9.6.

**Comment by MarcoFalke** [comment]
I think 5.2 is a reasonable minimum, since I couldn't find any distros that come with less than that.
Lowest I could find: https://packages.ubuntu.com/trusty/libs/qt5-default

**Comment by Sjors** [comment]
There's a check in `./configure`:

```
checking for Qt < 5.4... no
```

No idea what it's for, but could potentially be removed depending on which minimum version we pick.

**Comment by laanwj** [comment]
due to use of `QTimer::singleShot` specialization with method pointers, current master is only compatible with qt 5.4 and higher (see #14078)

**Comment by promag** [comment]
I'm in favour of bumping to 5.5.

**Comment by laanwj** [comment]
> I'm in favour of bumping to 5.5.

Any specific reason to choose 5.5 and not 5.4?

**Comment by promag** [comment]
@fanquake because 5.5 is the version that comes with xenial, trusty EOL is april 2019.

On the other hand, because of https://github.com/bitcoin/bitcoin/pull/13529#issue-196954857 we could bump to 5.9 according to the above https://github.com/bitcoin/bitcoin/issues/13478#issuecomment-401093750.

**Comment by jonasschnelli** [comment]
Debian 9 "stretch" is on Qt5.7, though Debian 8 "jessie" is "stuck" on Qt5.3.2... 
Not that it matters, just an indicator.

For me the questions are more:

* `what does it take to gain again compatibility with Qt5.X?`
* `what are the restrictions we take supporting Qt5.X?`

I think we should answer those questions for 5.2 up to 5.5.

Ideally we should support as far back as possible (below 5.2. makes little sense IMO though).
But since this is OSS, if nobody is interested in supporting older Qt versions, so shall it be.

**Comment by MarcoFalke** [comment]
Assigned 0.18.0 milestone, since we need to decide by then.

**Comment by MarcoFalke** [comment]
Unless someone works around the current compile failures on master, we'd have to bump to 5.4. (5.5 still works right now)

**Comment by hebasto** [comment]
Qt LTS comes with three years standard support. We could afford five years support.
Qt 5.2.1 was released on 2013-12-12.

**Comment by droark** [comment]
@hebasto - I'm a bit confused by what you're trying to say. Who exactly would pay for the LTS extension? Which version do you have in mind? (Assuming I understand things correctly, 5.2.1 LTS with five year support would end on Dec. 12 of this year.) Why would this really matter to Core?

**Comment by hebasto** [comment]
[Official Qt site](https://doc.qt.io/archives/index.html) don't expose docs for versions from 5.0 to 5.4.

**Comment by MarcoFalke** [comment]
Someone could probably start by removing all `QT_VERSION > 0x050100` and `QT_VERSION >= 0x50200` checks and bumping the minimum version to 5.2, since we surely won't support less than that.

**Comment by fanquake** [comment]
I've updated the parent, and added a needs release notes tag. Still unclear if we'll bump again before 0.18.0.

**Comment by Sjors** [comment]
I still don't understand the rationale for supporting a QT version that's _older_ than what we include in depends, i.e. 5.9. If anyone really insists on using an ancient Ubuntu version, they can just use the depends system. Unless I'm missing something.

**Comment by MarcoFalke** [comment]
@Sjors depends might not work on every os/arch?

**Comment by fanquake** [comment]
Something else to consider is Qt 5.12s supported platforms, especially if we'd like to use it for 0.18.0. 

Full info [here](http://doc-snapshots.qt.io/qt5-5.12/supported-platforms.html), however the basics are:

| OS | Supported Versions |
| ---- | ---- |
| macOS | > 10.12 |
| Windows | 7, 8.1 and 10 |
| Ubuntu | 16.04 and 18.04 |
| RHEL | > 7.4 |
| OpenSUSE | > 43.2 |

**Comment by Sjors** [comment]
So far we've bumped the minimum version to 5.2. I suggest having Travis check this, see #14983.

**Comment by Sjors** [comment]
See also #15320; in practice QT 5.2 doesn't currently build afaik.

**Comment by fanquake** [comment]
I've updated the top comment here. My current thought is a Qt `5.6` minimum requirement.

**Comment by Sjors** [comment]
ACK 5.5 <= x <= 5.9.6, lower only if Travis checks it

**Comment by MarcoFalke** [comment]
Ok, please someone bump it to 5.5. We are just walking in circles with those discussions.

**Comment by MarcoFalke** [comment]
> My current thought is a Qt `5.6` minimum requirement.

5.6 wouldn't work because xenial still uses 5.5 and removing that would require some workarounds for the ppa as well as people building on xenial.

**Comment by lucayepa** [comment]
Is it supposed to stop during configure, correct? If so, I think there is something not working, because I tested it on a system with QT 5.3.2 and it doesn't stop during configure. Instead it stops during compilation with an error that is not explicative at all. Let me know if this is an issue. Maybe it's only a nit, not worth to be filed as issue.

**Comment by MarcoFalke** [comment]
@lucayepa Yes, please file a separate issue about that

**Comment by lucayepa** [comment]
Ok. Just filed #15688 .
