### ISSUE TITLE
With Bitcoin Core 0.16.1 and LND 0.4.2 ram usage is very low on Raspberry Pi 3 B Plus

### ISSUE THREAD

**Issue by Amiga500** [bitcoin/bitcoin#13487]
With Bitcoin Core 0.16.1 and LND 0.4.2 ram usage is very low on Raspberry Pi 3 B Plus.

![raspibolt_memory](https://user-images.githubusercontent.com/16525337/41505754-c6820910-720f-11e8-8143-93f295ae2d82.png)

**Comment by Nino84** [comment]
Link to start

**Comment by Amiga500** [comment]
https://github.com/Stadicus/guides/blob/master/raspibolt/README.md @Stadicus

**Comment by supersammy7000** [comment]
So there is no issue? If so you should close it.

**Comment by jonasschnelli** [comment]
Thanks for the words @Amiga500!
Closing.
