### ISSUE TITLE
QT cross compile to ARM

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13495]
There are ARM devices out there with HDMI and full desktop linux support. I was able to compile and use QT on an Orange Pi Plus2E running Lubuntu 16.04. Compilation on the device itself takes several hours and QT spends a few minutes loading stuff, but otherwise the UI is pretty snappy.

Gitian builds currently don't include binaries for ARM. Cross compilation (for Gitian) was added in #8188, but QT was intentionally left out. Does anyone remember why?

I've been trying to get this to work on Ubuntu Bionic, but no success so far.

The first step to enabling this (for 32 bit) is to add `qt_arm_linux_packages:=$(qt_x86_64_linux_packages)`  to `depends/packages.mk`. That prevents it from skipping QT. This however will result in an error:

```
make HOST=arm-linux-gnueabihf

Configuring qt...

[...]

   The specified system/compiler is not supported:

      [...]/bitcoin/depends/work/build/arm-linux-gnueabihf/qt/5.7.1-c292d7b0435/qtbase/mkspecs/arm-linux-gnueabihf

   Please see the README file for a complete list.

funcs.mk:242: recipe for target '[...]/bitcoin/depends/work/build/arm-linux-gnueabihf/qt/5.7.1-c292d7b0435/qtbase/.stamp_con
```

I tried replacing `$(package)_config_opts_arm_linux  = $(host)` with ` = -platform linux-g++ -xplatform linux-arm-gnueabi-g++`, which seems to result in something being built. But configure isn't happy:

```sh
./configure --prefix=$PWD/depends/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++ --disable-tests --disable-bench --with-qrencode --with-gui=qt5
[...]
checking for QT5... yes
checking for QT_TEST... yes
checking for QT_DBUS... yes
checking for static Qt... yes
checking for QTPLATFORM... yes
checking for X11XCB... yes
checking for QTXCBQPA... yes
checking for Qt < 5.4... no
checking for static Qt plugins: -lqminimal... no
configure: error: Could not resolve: -lqminimal
```

I tried building the depends with #12971 with `QT_59=1`, but this fails with:

```
Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.

ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.
funcs.mk:242: recipe for target '[...]/bitcoin/depends/work/build/arm-linux-gnueabihf/qt/5.9.5-28b90c3bee9/qtbase/.stamp_configured' failed
make: *** [[...]/bitcoin/depends/work/build/arm-linux-gnueabihf/qt/5.9.5-28b90c3bee9/qtbase/.stamp_configured] Error 3
```

Hopefully someone who actually understands the depends system and cross compilation has more luck...

**Comment by Sjors** [comment]
I'm able to build Bitcoin-QT using Armbian as well using these steps: https://github.com/Sjors/armbian-bitcoin-core

It doesn't use cross-compile (yet) and it doesn't use the depends system (yet), but it's faster that compiling on the device itself, in case anyone needs a workaround.

**Comment by Sjors** [comment]
@TheBlueMatt how do you build QT for Ubuntu ARM? https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin/+packages

**Comment by MarcoFalke** [comment]
I believe it uses Canonicals infrastructure to compile

**Comment by TheCharlatan** [comment]
I seemed to be successful now with a arm qt depends build. Checkout my branch here: https://github.com/TheCharlatan/bitcoin/tree/Qt59arm .

**Comment by TheCharlatan** [comment]
The compilation for aarch64 fails with xextproto . This is a package that is required for libXext , which in turn is one the dependencies required for the qt build. xextproto saw its last update in 2013, so it is probably unmaintained now and never had support for the aarch64 architecture. Maybe @theuni knows whether it can be replaced by something, or if we should put some effort into patching it.

**Comment by Fuzzbawls** [comment]
@TheCharlatan a patch for xextproto is indeed needed for doing a cross-build for aarch64 you can reference this commit: https://github.com/PIVX-Project/PIVX/commit/5bd2a86a91344fa96268451af15ce339088299b3

We've been doing gitian builds to supply Qt binaries for arm/aarch64 for a while now, i've just never had much time to bring the work here. :)

**Comment by BlockMechanic** [comment]
I am trying to compile for android. Any idea how i would mod this to work ? I have applied this :- https://github.com/bitcoin/bitcoin/pull/16110 to make at least bitcoind build. But try as i might, havent managed to get the depends system to compile qt for android and get the config script to find it.
