### ISSUE TITLE
Bitcoin crashes at startup on my wallet

### ISSUE THREAD

**Issue by FreekPaans** [bitcoin/bitcoin#13509]
**What behavior did you expect?**

I expect the server not to crash.

**What was the actual behavior (provide screenshots if the issue is GUI-related)?**

Server crashes on startup

**How reliably can you reproduce the issue, what are the steps to do so?**

Using my wallet (which I obviously can't share).

**What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?**

0.16.0, 0.16.1 on Ubuntu 16.04
0.15.1 does not crash

**Additional info**

```
$ bin/bitcoind -printtoconsole -addresstype=legacy
<snip>
2018-06-20 11:01:30 AddToWalletIfInvolvingMe: Detected a used keypool key, mark all keypool key up to this key as used
bitcoind: wallet/wallet.cpp:4237: void CWallet::LearnRelatedScripts(const CPubKey&, OutputType): Assertion `IsSolvable(*this, witprog)' failed.
Aborted (core dumped)
```

**Comment by ReneFroger** [comment]
Is the additional information from your debug log? If not so, could you share the latest entries from your `debug.log` please? On your Ubuntu system the debug.log file, as well as all other files are placed by default in `~/.bitcoin`; If you have used -datadir to set a different data directory, `debug.log` will be placed there instead.

**Comment by MarcoFalke** [comment]
Do you remember anything "unusual" or usual you did with the wallet before upgrading to 0.16 from 0.15?

**Comment by FreekPaans** [comment]
@MarcoFalke no, nothing unusual. However, I forgot to mention that there's another node running the same wallet, and actually doing transactions. We use the node that we have this problem on as a "read only" node for the wallet.
I think the problem lies with transactions that are made *after* the backup was made.

**Comment by jonasschnelli** [comment]
I think this can only happen if the private key of a corresponding key pool pubkey could not been found/accessed.  @FreekPaans: you could try to run dumpwallet and inspect the output more deeply.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
