### ISSUE TITLE
Upgrading to Bitcoin Core 0.16.1 

### ISSUE THREAD

**Issue by BitcoinVegan** [bitcoin/bitcoin#13502]
This is regarding how to up grade to 0.16.1, I'm running ```bitcoind``` on linux, and I would like to know the proper command to copy to shut down 0.16.0 and upgrade to 0.16.1?

I'm also running ```LND``` on the same Raspberry Pi, and don't want to erase ```LND``` in the process, can someone assist me please?

If I'm on the wrong the place addressing this please don't hesitate to point me in the correct direction.

**Comment by fanquake** [comment]
There is a [How to Upgrade](https://github.com/bitcoin/bitcoin/blob/0.16/doc/release-notes.md#how-to-upgrade) section in the [release notes](https://github.com/bitcoin/bitcoin/blob/0.16/doc/release-notes.md). I've copied it in below:

How to Upgrade
==============

If you are running an older version, shut it down. Wait until it has completely
shut down (which might take a few minutes for older versions), then run the
installer (on Windows) or just copy over `/Applications/Bitcoin-Qt` (on Mac)
or `bitcoind`/`bitcoin-qt` (on Linux).

The first time you run version 0.15.0 or newer, your chainstate database will be converted to a
new format, which will take anywhere from a few minutes to half an hour,
depending on the speed of your machine.

Note that the block database format also changed in version 0.8.0 and there is no
automatic upgrade code from before version 0.8 to version 0.15.0 or higher. Upgrading
directly from 0.7.x and earlier without re-downloading the blockchain is not supported.
However, as usual, old wallet versions are still supported.

**Comment by BitcoinVegan** [comment]
Thanks @fanquake, I've read this upgrade before, I just don't know the proper, codes to put into the linux terminal

**Comment by MarcoFalke** [comment]
What linux? Is it self compiled or ppa? ...

**Comment by BitcoinVegan** [comment]
What do you mean ?

If it helps any I used the @stadicus raspibolt guide to build my node, how can I upgrade to 0.16.1 without jepordizing my lightning node

**Comment by Stadicus** [comment]
Hej @BitcoinVegan, have a look at this (closed) issue, it may give you the right commands:
https://github.com/Stadicus/guides/issues/88

**Comment by BitcoinVegan** [comment]
Thanks @stadicus I'll check it out

**Comment by MarcoFalke** [comment]
Thanks for taking over @Stadicus
