### ISSUE TITLE
Syncronizing is very slow. Been syncronizing for months

### ISSUE THREAD

**Issue by doone57** [bitcoin/bitcoin#13504]

**Comment by fanquake** [comment]
Please edit your issue to provide the information requested in the [ISSUE_TEMPLATE](https://raw.githubusercontent.com/bitcoin/bitcoin/master/.github/ISSUE_TEMPLATE.md).

**Comment by doone57** [comment]
i dont know how to use the template sorry

**Comment by MarcoFalke** [comment]
Sorry, I don't know how to help if you don't provide all the information that was asked when you opened the issue. (You can click on the edit button and then fill out out and let me know again)

**Comment by MarcoFalke** [comment]
Please provide the following information: https://raw.githubusercontent.com/bitcoin/bitcoin/master/.github/ISSUE_TEMPLATE.md

**Comment by doone57** [comment]
What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)? -->

**Comment by doone57** [comment]
I am having trouble with syncronizing taking so long. I am using the lasest version of Bitcoin Core

**Comment by doone57** [comment]
I need my money in Bitcoin Core ASAP

**Comment by doone57** [comment]
if you can call me and help me that way I would appreciate it!  513-702-3882

    On Tuesday, June 19, 2018, 11:37:05 AM EDT, MarcoFalke <notifications@github.com> wrote:  
 
 
Sorry, I don't know how to help if you don't provide all the information that was asked when you opened the issue. (You can click on the edit button and then fill out out and let me know again)

**Comment by sipa** [comment]
This is a place to report bugs, not user support. There is a community of people will can answer your questions on bitcoin.stackexchange.com, but you will have to provide actual detailed information of what you're doing, what you're seeing, what you're expecting, etc.
