### ISSUE TITLE
Estimatefee prints out incorrect error

### ISSUE THREAD

**Issue by Varunram** [bitcoin/bitcoin#13511]
`estimatefee was removed in v0.17.` is the output of `bitcoind` when we try to use `estimatefee`, shouldn't it be `estimatefee was removed in v0.16`?

**Comment by supersammy7000** [comment]
You are looking at the master branch which is used for development of the next release i.e. v0.17. This is the v0.16.1 code https://github.com/bitcoin/bitcoin/blob/v0.16.1/src/rpc/mining.cpp#L796 which says `estimatefee is deprecated and will be fully removed in v0.17. To use estimatefee in v0.16, restart bitcoind with -deprecatedrpc=estimatefee.`

**Comment by Varunram** [comment]
@supersammy7000 https://github.com/bitcoin/bitcoin/commit/ef8340d was merged in 0.16 (not even 0.16.1), so the message has to say `deprecated in 0.16 and removed in 0.17` or something similar to avoid confusion.

**Comment by supersammy7000** [comment]
If that was the message it could lead you to think the method is still
available but it has been removed from the code.

**Comment by Varunram** [comment]
What? the method _is_ still available, it is _deprecated_ which the logs don't show. It should be `deprecated in 0.16 and removed in 0.17` as pointed out in my last comment.

**Comment by sipa** [comment]
@Varunram Exactly which version of the source code are you running?

**Comment by Varunram** [comment]
@sipa Thanks for the reply. I'm running the provided 0.16 binaries at core's website
```
./bitcoin-cli -regtest estimatefee
error code: -32
error message:
estimatefee was removed in v0.17.
Clients should use estimatesmartfee.
```
Commit https://github.com/bitcoin/bitcoin/commit/c6f09c2713333bf335e83bb303e2feec10136751 made this change I guess.

But thinking about this for a while, I guess this is technically not an issue *now* because the next release is 0.17 and the output is accurate anyway for the future release, so I think I should close this issue. (Also, this issue isn't huge in any way) Thanks again!

**Comment by sipa** [comment]
@Varunram Are you sure you're not running master? Neither 0.16.0 or 0.16.1 even contain the string "estimatefee was removed in v0.17" in the source code.

**Comment by Varunram** [comment]
Oh dear, looks like my binary is on master, Really sorry sipa and thanks for your time!
