### ISSUE TITLE
tests: p2p_timeouts should be rewritten with mocktime

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#13518]
The p2p_timeouts functional test should probably be rewritten to use mocktime. Currently it spends all of its time in various `time.sleep(30)` and takes more than a minute to finish for a trivial test.

**Comment by jnewbery** [comment]
Qualified concept ACK.

It's annoying that this test takes a minute to run, but taking a shortcut using mocktime places assumptions on how the bitcoind node is looping its connections and disconnecting misbehaving peers.

If we're not careful in the way we change this test and the implementation changes in bitcoind, this test could cease to be actually testing anything.

**Comment by MarcoFalke** [comment]
Thanks for the input. If the `time.sleep()` are required for some reason, it should be explained in the test why.
