### ISSUE TITLE
tests: bitcoind stdout and error should be passed to the logger

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#13519]
Currently the stdout of bitcoinds in functional tests is written to a file in `self.datadir` of the node. It is only read/examined after the node is shut down. To aid debugging it should (also?) be passed to the logger for visibility and timestamps.

**Comment by jnewbery** [comment]
I don't understand the "visibility and timestamps" comment. combine_logs interleaves node logs with test framework logs. Is there some missing functionality that would make debugging easier?

**Comment by jnewbery** [comment]
No, sorry - you're right. We don't include stderr or stdout. My misunderstanding.

**Comment by MarcoFalke** [comment]
One solution would likely be to create a InitLogger in the "ui_interface" and call it in InitError and InitWarning. Then connect it for both the headless bitcoind and the gui.

**Comment by hartley785** [comment]
Y'all figure out the dollar amount your cotton-picking mistake

**Comment by music** [comment]
What do you mean by "connect it" for the headless bitcoind and gui? (I've taken to trying to fix it, sorry if this question is a bit common sense, this is my first bug.)

**Comment by MarcoFalke** [comment]
Just appending it in combine_logs is probably fine:

* [test] combine_logs: append node stderr and stdout if it exists #15841
