### ISSUE TITLE
qa: p2p_segwit intermittent failure

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#13523]
Line 1545, in test_upgrade_after_activation:

https://github.com/bitcoin/bitcoin/blob/000abbb6b07410357a928768d7d56465ba0d3bac/test/functional/p2p_segwit.py#L1532-L1545

```
AssertionError: Block sync timed out:
  '16b511df7fe274ace2e6256583c897242d0d626fac22198df3008a3b53a2e04b'
  '16b511df7fe274ace2e6256583c897242d0d626fac22198df3008a3b53a2e04b'
  '73af38ce0ed04b5fda9500f374ed625027fb0e4f145ca6346fe8527d0443087c'
```

Full log on travis: https://api.travis-ci.org/v3/job/395178010/log.txt

**Comment by jnewbery** [comment]
#13467 may make p2p_segwit.py failures easier to debug.
