### ISSUE TITLE
bitcoind on macOS stopped logging to STDOUT by default since 0.16.1

### ISSUE THREAD

**Issue by rikur** [bitcoin/bitcoin#13520]
After switching to tag 0.16.1 (from 0.16.0), configuring and building, bitcoind no longer logs to STDOUT by default.

I can see the logs if I add the CLI arg -printtoconsole. I don't configure logging in my bitcoin.conf file at all.

OS: macOS 10.13.5

**Comment by Sjors** [comment]
Does master log to std::out by default for you? Afaik that behavior was added in #13004, so shouldn't be in 0.16.0.

**Comment by rikur** [comment]
I must have made a mistake with my git checkouts. Master outputs to STDOUT by default, 0.16.1 doesn't.

Thanks.
