### ISSUE TITLE
There should be a way to check whether ZeroMQ is enabled

### ISSUE THREAD

**Issue by domob1812** [bitcoin/bitcoin#13526]
Bitcoin's ZeroMQ interface is handy for software layered on top of the core daemon, like wallet frontends (or other similar things).  It would be useful to have an easy way to query the daemon whether ZeroMQ publications are enabled and if so which address is configured for them.  That way, such a frontend application can show a helpful message to the user if the daemon is not configured correctly.

We could add a new RPC method for this, like `getzmqinfo`.  In the simplest case, it would be called without arguments and just return a JSON object that contains whether each of the possible ZeroMQ endpoints (`hashtx`, `hashblock`, `rawtx` and `rawblock`) is configured and if so at which address.

**Comment by domob1812** [comment]
With this issue, I want to get feedback on what everyone thinks about this idea.  If it seems useful, I'm happy to implement it and provide a pull request.

**Comment by ianwaldrop** [comment]
Such a method would also enable self-configuration of zmq ports by front-end applications given the simplest case outlined above.

**Comment by sipa** [comment]
It seems reasonable to add a `getzmqinfo` RPC. Alternatively, we could also have an RPC to inspect the config/cmdline arguments generically.

**Comment by domob1812** [comment]
While I think that an RPC to query for all command-line arguments might be useful as well (and if desired, I'm happy to implement that also), I agree with @promag that having a ZMQ-specific variant solves a somewhat different need and is useful in its own right.

Is the interface proposed in the OP good?  I. e., something like this:

    $ bitcoin-cli getzmqinfo
    {
      "hashtx": "tcp:/tcp://127.0.0.1:28332",
      "hashblock": "ipc:///tmp/bitcoind.tx.raw"
    }

Meaning that `hashtx` and `hashblock` are published at the given addresses, while others (`rawtx` and `rawblock`) are not enabled at all.  Or should the interface be different?

**Comment by promag** [comment]
I would suggest `getzmqnotifications` and return:
```json
{
    "publish": {
        "hashtx": "...",
    },
}
```
Other examples `getzmqconfig`, `setzmqconfig`, `addzmqnotification`...

**Comment by domob1812** [comment]
Yes, that makes sense.  I'll create a patch implementing @promag's `getzmqnotifications` format as a first step.  (I may be interested in adding more things, like `addzmqnotification`, later on as well.)

**Comment by domob1812** [comment]
Change merged, this is now implemented.

I may take a look at `addzmqnotification` (i.e. making the configuration of notifications dynamic / configurable after start up) later, but that is separate and I'll open a new issue to discuss the proposal for it when I do.
