### ISSUE TITLE
[tools] testgen deprecated

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#13553]
Playing around with scripts and tools, I noticed that this payload generator is obsolete since September 2017. That can be slightly confusing, if there's no plan to replace it, it should be removed.

**Comment by MarcoFalke** [comment]
I believe it can be adjusted to output the new test format.

**Comment by bmoo0** [comment]
Where is the script that needs to be removed? I'd like to give this a try.

**Comment by MarcoFalke** [comment]
```
git ls-files|grep testgen

**Comment by bmoo0** [comment]
Do we just need to remove the scripts, also is there a branch naming convention?

**Comment by MarcoFalke** [comment]
I think it should be adjusted to the new test format.

**Comment by AkioNak** [comment]
I agree with @MarcoFalke .
I will make a PR to solve this.

Note: It may be better to change the file name from ```gen_base58_test_vectors.py``` to ```gen_key_io_test_vectors.py```.
