### ISSUE TITLE
archivo bootstrap.dat.torrent

### ISSUE THREAD

**Issue by javiertuerca** [bitcoin/bitcoin#13556]
How are you:
I tried downloading the file https://bitcoin.org/bin/blockchain/bootstrap.dat.torrent, but the link is broken I have seen in some forums that this method is no longer safe.
That another method I can use to accelerate the synchronization of a node?
Thank you very much

**Comment by sipa** [comment]
English, please.

**Comment by MarcoFalke** [comment]
In all supported version of Bitcoin Core, the direct download for peers (normal sync) is faster than bootstrap.dat.
