### ISSUE TITLE
Compilation: warnings, Alpine Linux (ARM)

### ISSUE THREAD

**Issue by jsarenik** [bitcoin/bitcoin#13567]
```
# uname -a
Linux localhost 3.4.0-lineageos-gb263a89 #1 SMP PREEMPT Thu May 3 05:26:06 CEST 2018 armv7l GNU/Linux
```

When compiling on up-to-date Alpine Linux 3.7.0 on ARM I get many of similar warnings:

```
/usr/include/c++/6.4.0/bits/stl_map.h:483:4: note: parameter passing for argument of type 'std::_Rb_tree<CSubNet, std::pair<const CSubNet, CBanEntry>, std::_Select1st<std::pair<const CSubNet, CBanEntry> >, std::less<CSubNet>, std::allocator<std::pair<const CSubNet, CBanEntry> > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const CSubNet, CBanEntry> >}' will change in GCC 7.1      
    __i = _M_t._M_emplace_hint_unique(__i, std::piecewise_construct,           
    ^~~
```

I am wondering if I am doing something wrong or if anything in the code needs to be fixed. The warnings do not show on x86_64 Alpine Linux using the same version of GCC.

The bitcoin version used is c93c360eec4de77af8aaa74d9140dba57160e30d

**Comment by MarcoFalke** [comment]
It is a note that such code is ABI incompatible between GCC 6.x and 7.1,
so if you recompile all the code, there is nothing to worry about, if you
expect ABI compatibility, you should change your code to avoid that.
See https://gcc.gnu.org/gcc-7/changes.html
You can use -Wno-psabi if you don't want these messages.

Source: https://gcc.gnu.org/ml/gcc/2017-05/msg00073.html

**Comment by jsarenik** [comment]
@MarcoFalke Thank you for the explanation. What could be the reason the warning shows only on ARM?

The above-mentioned `stl_map.h` include file is the same on both architectures.

In the end it compiles OK also on ARM and `make check` succeeds.
