### ISSUE TITLE
Sync Interrupted, Can't continue synching full node.

### ISSUE THREAD

**Issue by arminbusatlic** [bitcoin/bitcoin#13597]
Was synching my full node for 4 days now, got to block 350K until we had a power outage. Right now, I can't start bitcoind, getting a permission error and also getting a permission error in the debug.log file.

When I try to run bitcoind -daemon..
Error: Cannot write to data directory '/home/pi/.bitcoin'; check permissions.

Tail of debug.log file..

2018-07-04T23:27:33Z *** System error while flushing: Fatal LevelDB error: IO error: /home/pi/.bitcoin/blocks/index/000324.log: Read-only file system
2018-07-04T23:27:33Z Error: Error: A fatal internal error occurred, see debug.log for details
2018-07-04T23:27:33Z FlushStateToDisk: failed to flush state (System error while flushing: Fatal LevelDB error: IO error: /home/pi/.bitcoin/blocks/index/000324.log: Read-only file system (code 0))

Any help or advice would be greatly appreciated!

Thanks,
Armin

**Comment by StayCoolDK** [comment]
AFAIK this is because one of the block files were corrupted from the outage. I had the same issue. You have to start bitcoin d with a -reindex flag.

**Comment by arminbusatlic** [comment]
I have remounted the drive using "sudo mount -o remount,rw /dev/sdb2".
I have also ran bitcoind -reindex. 

It continues to crash after a while.

Here is the output of the db.log file:

wallet.dat: unable to flush: Read-only file system
wallet.dat: unable to flush: Read-only file system
wallet.dat: unable to flush: Read-only file system
txn_checkpoint: failed to flush the buffer cache: Read-only file system
wallet.dat: Read-only file system

I've tried this a few times now, but Bitcoin Core continues to crash for me.

**Comment by StayCoolDK** [comment]
What you need to know is that the harddisk automatically goes into ReadOnly mode when an error occurs. If i were you i would delete every folder except your wallet.dat and "start over" with syncing, this is normally what -reindex does. I'd recommend that you do the initial sync on a laptop or computer, and then once it's done start using your pi instead and see if the error will occur. There's also a risk that your hard drive might be faulty, how old is it?

**Comment by arminbusatlic** [comment]
It's a brand new external Seagate HD with 4 TB of storage.

It all happened when we had a power outage. After that, errors started to occur and core began to crash.

**Comment by jonasschnelli** [comment]
Clearly a storage / disk issue.
Closing.
