### ISSUE TITLE
.gitignore makes git ignore gen.cpp, Makefiles and patches

### ISSUE THREAD

**Issue by Shtutnik** [bitcoin/bitcoin#13590]
Hi, 
I'm wondering if this is on purpose or not, .gitignore has these lines in it:
39: src/univalue/gen
64: *.patch
82: Makefile

which makes git ignore all Makefiles, patch files and specifically src/univalue/gen/gen.cpp

Is this intentional?

**Comment by fanquake** [comment]
@Shtutnik The `.gitignore` file is correct, what is the problem are you having?

**Comment by fanquake** [comment]
Closing until more info is available.

**Comment by Shtutnik** [comment]
Apologizes for taking time to answer.
I stumbled into this when forking the code outside of github. 
I cloned the project, then I removed the .git folder, then I added all files into a new repository I created elsewhere. 
Of course, there is a better way to do this. Nonetheless, this is where I noticed that there where missing files from the new repository and then I realized that this happened because of the contents of .gitignore. 
If this is intentional, then please disregard this issue. 
Still, I am a bit confused though - if someone makes changes to the mentioned files, they won't be updated (included in a commit). Are they not meant to be updated? Are the Makefiles generated elsewhere somehow?
Many thanks for taking your time to address this, I really appreciate it!

**Comment by sipa** [comment]
These files are automatically generated at build time. Making changes to them would be overwriiten anyway.
