### ISSUE TITLE
Cannot restore bitcoin-qt window if minimized or closed to systray

### ISSUE THREAD

**Issue by redblade7** [bitcoin/bitcoin#13606]
Since Bitcoin Core v0.16.1, bitcoin-qt has this problem where minimizing or closing bitcoin-qt makes the window unrestorable, requiring you to exit the program from the system tray menu and restart bitcoin-qt. The only exception to this is by left-clicking the Bitcoin icon in the system tray to alternate between minimize and restore.

Using Bitcoin Core v0.16.1 compiled from source.

OS: Linux Gentoo w/Plasma
CPU: i7-4790k (Haswell Refresh)
Disk type: HDD

**Comment by laanwj** [comment]
So to be clear:
- this wasn't an issue in 0.16.0, but it is in 0.16.1?
- are you building from original source or the gentoo-patched version?

**Comment by redblade7** [comment]
1. Only in 0.16.1
2. Compiling from original source, downloaded at bitcoincore.org

**Comment by promag** [comment]
Qt version?

**Comment by redblade7** [comment]
Qt5, from Gentoo

**Comment by redblade7** [comment]
This is also true of 0.16.2, and the latest non-tab version Namecoin which is forked from 0.16.2

**Comment by hebasto** [comment]
@redblade7 
Are you still experiencing this problem with the latest `v0.17.0rc2`?

**Comment by redblade7** [comment]
Is it safe to upgrade to 0.17.0rc2 and downgrade back to a stable version?

**Comment by hebasto** [comment]
> Is it safe to upgrade to 0.17.0rc2 and downgrade back to a stable version?

There is an issue regarding downgrade: #14048

**Comment by redblade7** [comment]
This bug is still present as of 0.17.1

**Comment by hebasto** [comment]
I've managed to reproduce this bug on `KDE Plasma 5.12.7` and `Qt 5.9.5` with set option `Minimize to the tray instead of the taskbar`. Will look into it further.

**Comment by promag** [comment]
![download](https://user-images.githubusercontent.com/3534524/50426440-92ea1e00-0885-11e9-95f4-080058ce1cef.jpeg)

Should backport #14123 to 0.17.2?
