### ISSUE TITLE
When running on testnet cannot connect via RPC but no problem on mainnet

### ISSUE THREAD

**Issue by hxsquid** [bitcoin/bitcoin#13607]
Bitcoin-cli would work

Bitcoin-cli did not work

TESTNET

[ec2-user@ip-10-0-0-27 ~]$ ./bitcoin-0.15.0/bin/bitcoind -testnet
Bitcoin server starting
[ec2-user@ip-10-0-0-27 ~]$ ./bitcoin-0.15.0/bin/bitcoin-cli getinfo
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

NOT TESTNET
                                                                                        
[ec2-user@ip-10-0-0-27 ~]$ ./bitcoin-0.15.0/bin/bitcoind 
Bitcoin server starting
[ec2-user@ip-10-0-0-27 ~]$ ./bitcoin-0.15.0/bin/bitcoin-cli getinfo
{
  "deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16",
  "version": 150000,
  "protocolversion": 70015,
  "walletversion": 139900,
  "balance": 0.00000000,
  "blocks": 13046,
  "timeoffset": 0,
  "connections": 0,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "keypoololdest": 1530920109,
  "keypoolsize": 2000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}

version 15

downloaded from bitcoin.org

Amazon Linux

**Comment by sipa** [comment]
If you want you connect to a testnet `bitcoind` you should use `bitcoin-cli -testnet`.

This is not a support forum. You can ask questions on https://bitcoin.stackexchange.com.

**Comment by hxsquid** [comment]
Thanks, that's so obvious and so well documented!
