### ISSUE TITLE
Transactions are selectively mined on a private node

### ISSUE THREAD

**Issue by neptunix** [bitcoin/bitcoin#13635]
I've got a custom compiled bitcoin core node with changed accounts prefixes and blocks creation time.

This node runs mining and produces new block every ~1 min.
I create transactions using bitcoin-cli sendtoaddress and transactions appear in the mempool: 
```
> bitcoin-cli -testnet sendtoaddress sZgFxHLG4AZFCZwVoGKbpBaVX7tve56478 20
b7b710e4599c98a5b97b4846b97ec9cc36a34ff6338dcdbd586110b77f5bfa57
```

It appears in the mempool
```
> bitcoin-cli -testnet getmempoolentry b7b710e4599c98a5b97b4846b97ec9cc36a34ff6338dcdbd586110b77f5bfa57

[
    {
        "fees": {
            "base": 0.000168,
            "modified": 0.000268,
            "ancestor": 0.000268,
            "descendant": 0.000268
        },
        "size": 168,
        "fee": 0.000168,
        "modifiedfee": 0.000268,
        "time": 1531315521,
        "height": 107039,
        "descendantcount": 1,
        "descendantsize": 168,
        "descendantfees": 26800,
        "ancestorcount": 1,
        "ancestorsize": 168,
        "ancestorfees": 26800,
        "wtxid": "d7bb3a08cdefcffe0d3ab129e553059c31bc3a9a431ed7e15b31f93e744d220f",
        "depends": [],
        "spentby": []
    }
]
```

The problem is - transactions are very selectively mined - like 2-3 transactions out of 20-30 created or less. Usually all of them come in one block.
The rest txs stay in mempool forever until I clean them.
Currently I've submitted 22 tx and none are mined after an hour.

`prioritisetransaction` does not help - it just increases tx fee.
version is: v0.16.99. Was built from master branch on Apr 27.

Configuration is as follows:
```
server=1
listen=1
testnet=1
rest=1
maxconnections=100
keypool=1000
txindex=1
addressindex=1
timestampindex=1
spentindex=1
disablewallet=0

maxtxfee=1
minrelaytxfee=0.000001
blockmintxfee=0.000001
mempoolexpiry=2

rpcallowip=127.0.0.1/32
rpcallowip=172.0.0.0/8
rpcallowip=10.0.0.0/8
```

Mining is run through rpc one block at a time in a loop.

Is there something I am missing?

**Comment by MarcoFalke** [comment]
>I've got a custom compiled bitcoin core node with changed accounts prefixes and blocks creation times.

Please provide exact steps to reproduce after you reverted the local changes to a vanilla bitcoin core commit.

**Comment by neptunix** [comment]
> Please provide exact steps to reproduce after you reverted the local changes to a vanilla bitcoin core commit.
Ok, I will.

Is there a description of the algorithm that is responsible for selection transactions from the mempool anywhere?
Thanks

**Comment by MarcoFalke** [comment]
A block template is filled with transaction packages that have the highest feerate. Non-standard transactions are excluded, but they shouldn't be accepted to the mempool either, normally.

**Comment by neptunix** [comment]
You are right about non-standard transactions - it's like testnet transactions are rejected for mainnet and vice versa.

Transactions that I make (since I make them with `bitcoin-cli sendaddress`) are legitimate and are included into mempool - so they are perfectly fine for my node.

Whats more many of them get mined. (!)
My problem is that none all of them are.

**Comment by neptunix** [comment]
@MarcoFalke, reopen the issue please as what you've said is not related the the problem at all.

**Comment by neptunix** [comment]
Here is an example of the tx that was mined:
https://btc-explorer-dev.nekotal.tech/tx/2ad1efc51c553aa4850e1e810095c99401b2c7815491ecccdf9545d41c5cd36a

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base, not user-modified code bases. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by neptunix** [comment]
I'll do the same with the unmodified code and see if the issue persists. Thanks
