### ISSUE TITLE
Bitcoin Address Transaction notify feature in Bitcoin core

### ISSUE THREAD

**Issue by pavans009** [bitcoin/bitcoin#13640]
I am developing one bitcoin buy, sell, withdraw and deposit online platform for one of my client and I stuck in middle of it for Deposit BTC module. I do have set up bitpay 'Bitcore Full Node' and also Insight UI and Insight API and those are working very fine here with all aspects. and my main website is hosted on another separate VPS server.

**My Actual problem:** 
Now I want to set callback for user's assigned address on this node server so whenever there is any transaction on those defined and assigned bitcoin address, this callback feature will make call to my main site and update user's order and bitcoin balance based on number of defined confirmations. So is there any way or solution for this task? I meant I am not understanding how it will work and not sure how it can be implemented. Is there any solution in that Full node or Insight API ? or will I need to implement custom solution and then make call to Insight API to get updates of transaction for each defined bitcoin address?

**Other points to note down:** 

- Currently, I am using BlockCypher and Blockchain.com APi service to set callback for my user's bitcoin addresses and they do make callback for any new transaction and transaction confirmation action and working fine but now I want my own server, my own features to expand it. 
- I also checked Bitcoin Core from bitcoin.org but couldn't find any solution.

_Any input, advise, help will be appreciated. Thanks in advance._

**Comment by StayCoolDK** [comment]
Have you considered the walletnotify feature? 
https://en.bitcoin.it/wiki/Running_Bitcoin

-walletnotify=<cmd> | Execute command when a wallet transaction changes (%s in cmd is replaced by TxID)

Every time a transaction is received in the mempool to an address belonging to the underlying wallet, the API endpoint specified in -walletnotify is called with the TXID, which you can use to figure out the address, belonging to the user.

**Comment by promag** [comment]
You should move this question to https://bitcoin.stackexchange.com.

**Comment by StayCoolDK** [comment]
He already asked there, too.
