### ISSUE TITLE
why 0.16.1 has no method like getbalance?

### ISSUE THREAD

**Issue by efvhi** [bitcoin/bitcoin#13641]
thanks for any response. :)

`root@zdsx-Aspire-GX-781:/media/zdsx/Acer# bitcoin-cli -testnet -datadir="./bitcointestnetdata/" getbalance
error code: -32601
error message:
Method not found`

`root@zdsx-Aspire-GX-781:/media/zdsx/Acer# bitcoin-cli --version
Bitcoin Core RPC client version v0.16.1.0-gdac5d68fc6cf`

**Comment by sipa** [comment]
Perhaps you are running with -disablewallet or you compiled with --disable-wallet?

**Comment by efvhi** [comment]
got it! i remembered.  i used this option. thanks very much!
