### ISSUE TITLE
how can i get all transactions of a specific address ?

### ISSUE THREAD

**Issue by efvhi** [bitcoin/bitcoin#13642]
i found that `listtransactions` does not work what i think it does. i also found `listreceivedbyaddress` can get all received tx. but there is no `listsentbyaddress` or `listtransactionsbyaddress`, should i write it myself or  i  just missed something?

thanks for any response & advice  :)

**Comment by StayCoolDK** [comment]
Listtransactions accepts an account parameter which is optional, if you leave it out all transactions are shown. There is no RPC command for listing transactions based on addresses. You should loop through the addresses returned from listtransactions. Remember when sending transactions there is no "from address", only a receiving address. Any address in the wallet can be used for any transaction.

**Comment by efvhi** [comment]
please check out this. https://tokenview.com/en/btc/address/35SySvJgDkZ1j4psYBA9jScbdffMwyAiA4 

he just listed all transactions by an address in 1 seconds. how did he do it?

**Comment by sipa** [comment]
@StayCoolDK Wrong, it only lists transactions in your own wallet.

@efvhi It's hard to guess what you think these RPCs do if you don't explain what you're trying to do.

Please take this to bitcoin.stackexchange.com. This is an issue tracksr, not a support forum.

**Comment by efvhi** [comment]
@sipa i am trying to implement something like this doing https://tokenview.com/en/btc/address/35SySvJgDkZ1j4psYBA9jScbdffMwyAiA4   but i think if i scan every block to find related transactions. that will take a lot time. there must be a another way to do it.

**Comment by efvhi** [comment]
well, thanks for your advice.
