### ISSUE TITLE
False positive for Sha-NI

### ISSUE THREAD

**Issue by DesWurstes** [bitcoin/bitcoin#13653]
Branch=master
Compiler=gcc-8

![](https://user-images.githubusercontent.com/23437045/42673412-06746856-8674-11e8-84b4-8f6caebe6dd9.png)

So, Intel's Maccpuid tool (also Intel's website) says that my CPU doesn't have SHA-NI. `./configure` should be wrong for some reason.

**Comment by luke-jr** [comment]
configure is just checking for what it needs to compile SHA-NI support. Actual CPU capabilities aren't detected until runtime.
