### ISSUE TITLE
CI: Force all rpc args to be properly named

### ISSUE THREAD

**Issue by jtimon** [bitcoin/bitcoin#13661]
I'm very grateful for trailing spaces being detected in CI being detected for a while now.
That's one thing I always forget and fortunately I don't have to wait for human to tell me anymore.

Another thing I forget is making sure named arguments work when creating a new rpc call.
I would like travis to fail whenever there's any rpc call with un-named arguments.

**Comment by MarcoFalke** [comment]
Do you mean https://github.com/bitcoin/bitcoin/blob/master/test/lint/check-rpc-mappings.py ?

**Comment by jtimon** [comment]
Yeah, looks like it. Sorry, I was trying on an older version
