### ISSUE TITLE
Why use the master key to encrypt private key?

### ISSUE THREAD

**Issue by NickyYangYang** [bitcoin/bitcoin#13675]
When encrypt wallet, using a master key to encrypt private key. Why not directly use the key derived based the wallet's passphrase?

**Comment by MarcoFalke** [comment]
User chosen pass phrases often have very little entropy. Also, you couldn't change the passphrase in the future.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
