### ISSUE TITLE
What is the difference between the PaiCoint project and BitCoin?

### ISSUE THREAD

**Issue by ZexiFangkong** [bitcoin/bitcoin#13685]
[projectpai/paicoin](https://github.com/projectpai/paicoin)
The project was recently identified as PAI. 
Look at its source code and discover the infrastructure file structure and so on, all of which are slightly modified and added from BitCoin. Want to ask everybody this PAI overall how? Does it have anything to do with BitCoin? Does BitCoin have any advantages over BitCoin?

**Comment by promag** [comment]
Please ask there and close this issue.

**Comment by ZexiFangkong** [comment]
Don't understand.
Is this not allowed here?
Do I need to shut down this issue?

**Comment by fanquake** [comment]
Please ask those questions on the https://github.com/projectpai/paicoin repository. We don't discuss/provide support for alt coins here.
