### ISSUE TITLE
Gitian with Bionic host

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13688]
As of #13171 Gitian uses Bionic to build the binaries, but the host machine that runs this doesn't have to be Gitian. The [instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md) currently recommend Debian 9.

This machine-inside-a-machine situation is confusing enough, so all things equal I think it would be better to switch the recommended host to Bionic.

Windows build uses Bionic as well, per #13246. So everyone who does that, could potentially help out with Gitian builds. It would also allow us to reuse the nicely detailed Gitian instructions to help Windows folks out.

Last time I tried I ran into some trouble though. I'll try again for the v0.16.2 release candidate.

**Comment by MarcoFalke** [comment]
Note that gitian builds should work on any host that provides apt-cacher-ng (see the instructions for debian and fedora in https://github.com/bitcoin-core/docs/blob/master/gitian-building.md#preparing-the-gitian-builder-host)

Alternatively, if the host doesn't come with apt-cacher-ng or the vmbuilder doesn't work on the host, you could try docker: https://github.com/bitcoin-core/docs/pull/33

**Comment by Sjors** [comment]
I can't remember what went wrong last time. Hopefully indeed it's purely a documentation change.

**Comment by Sjors** [comment]
Just tried to do a Gitian build for master, with the new Python Gitian script from #13623 as well as `gitian-build.sh` on master. I can build the base image using `--setup`, but trying to do a build I get:

```
./gitian-build.sh --detach-sign --no-commit -b sjors -c master

master
~/bitcoin ~
[...]
Building Dependencies
[...]
make: Leaving directory '/home/gitianuser/bitcoin/depends'

Compiling master Linux

--- Building for bionic amd64 ---
Stopping target if it is up
Making a new image copy
Failed run an application inside container
Traceback (most recent call last):
	6: from ./bin/gbuild:301:in `<main>'
	5: from ./bin/gbuild:301:in `each'
	4: from ./bin/gbuild:303:in `block in <main>'
	3: from ./bin/gbuild:303:in `each'
	2: from ./bin/gbuild:308:in `block (2 levels) in <main>'
	1: from ./bin/gbuild:57:in `build_one_configuration'
./bin/gbuild:21:in `system!': failed to run make-clean-vm --suite bionic --arch amd64 (RuntimeError)
Traceback (most recent call last):
./bin/gsign:70:in `<main>': result/bitcoin-linux-0.17-res.yml does not exist (RuntimeError)
mv: cannot stat 'build/out/bitcoin-*.tar.gz': No such file or directory
mv: cannot stat 'build/out/src/bitcoin-*.tar.gz': No such file or directory
```

I'm guessing it's an LXC related thing.

**Comment by Sjors** [comment]
From [IRC](https://botbot.me/freenode/bitcoin-core-dev/2018-07-17/?msg=102179281&page=3), @ken2812221 wrote:

```
[20:42:11] ken2812221_ Modify lxcbr0 to br0 at /etc/default/lxc-net
[20:43:50] ken2812221_ And add "export GITIAN_HOST_IP=10.0.3.1 LXC_GUEST_IP=10.0.3.5" to your .profile
```

Note that `lxcbr0 to br0` is new (compared to Debian 9 instructions) and that the IP is now `10.0.3.1`  instead of `10.0.3.2`.

This indeed starts a build process for LXC (Docker still has the same issue).

**Comment by MarcoFalke** [comment]
> export GITIAN_HOST_IP=10.0.3.1 LXC_GUEST_IP=10.0.3.5

Would be nice, if the environment variables were exported by the script, so it would't have to be done manually?

**Comment by deadalnix** [comment]
Trying to make that work on debian here as well. I followed instructions found here ( https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-create-vm-debian.md ) and here ( https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md )

I get the same error as above:
> lxc-execute: tools/lxc_execute.c: main: 164 Failed run an application inside container

Ready the instructions to fix this:
> Modify lxcbr0 to br0 at /etc/default/lxc-net
I do not have that file on the system.

> And add "export GITIAN_HOST_IP=10.0.3.1 LXC_GUEST_IP=10.0.3.5" to your .profile
This is done, but do not change anything.

**Comment by achow101** [comment]
@deadalnix Do you have LXC 2.1+ installed? IIRC debian does not have that in its repos, so you will have to install it manually.

**Comment by deadalnix** [comment]
I installed 2.1.1 via the following procedure:

Checkout lxc source from its git repository.
git checkout lxc-2.1.1
./autogen.sh
mkdir build
cd build
./configure --without-werror --prefix=/opt/lxc
make
sudo make install

Then I added /opt/lxc/bin to my path.

lxc-execute --version gives me 2.1.1

Le sam. 29 sept. 2018 à 00:45, Andrew Chow <notifications@github.com> a
écrit :

**Comment by Sjors** [comment]
I've been using a Bionic host for Gitian building for a while now without a problem, though I can't remember if I reconfigured anything :-)
