### ISSUE TITLE
Bitcoin core development in IDE

### ISSUE THREAD

**Issue by LucaPaterlini** [bitcoin/bitcoin#13694]
Hello,
where I could find the guide on how to install an IDE
and debug the code?

**Comment by MarcoFalke** [comment]
Sorry, we don't have documentation on how to use common IDEs with our build configuration, because for integration the IDEs often require `cmake`. However, it is possible to use any IDE (like `clion` or `vim`) to edit the code.

Some further resources, that talk about specific IDEs:

* https://bitcoin.stackexchange.com/questions/56529/what-ide-to-use-for-bitcoin-development
*  Visual Studio build configuration for Bitcoin Core. #11526 (unmerged) 
* https://bitcoin.stackexchange.com/questions/50046/how-to-open-bitcoin-source-in-ide

**Comment by LucaPaterlini** [comment]
why there is not a paragraph or a tutorial on how to debug and make the life easy for the new contrbutors?

**Comment by MarcoFalke** [comment]
> clion is not available for debug mode and step by step inspection

I do believe this is possible. I did this a few years ago, so no guarantee on correctness or completeness:

* Build the executable "normally" in the terminal (`./autogen.sh && ./configure && make -j 2`)
* Open the source tree in clion and add a "run configuration" to clion, selecting the executable manually and specifying the command line args. Something like this:

![screenshot from 2018-07-17 19-29-46](https://user-images.githubusercontent.com/6399679/42850949-1c1a4fd6-89f8-11e8-8155-aeed2b2c11ee.png)

* Set a debug point in one of the source files and debug the configuration target you just created...

See for example:

![screenshot from 2018-07-17 19-35-34](https://user-images.githubusercontent.com/6399679/42851132-fbe64430-89f8-11e8-95ab-f117e0dc0f1a.png)

**Comment by crowdcoinChain** [comment]
hi,
I have a newer version 2018.1, could you explain what datadir param stand for?

I have tried the way you suggested and I got

Error running 'bitcoind'
Cannot run 'bitcoind' on '<default>'

**Comment by jonasschnelli** [comment]
If one wants line by line debugging, `gdb` or `lldb` is probably the most simplest way to do this. Just use `./configure --enable-debug` and run `gdb src/bitcoind`.

Using Qt Creator's IDE is also an effective how to do line-by-line debugging (more GUIish then gdb) including interactive variable inspection, etc.

**Comment by MarcoFalke** [comment]
If someone wants to add documentation on how to setup an IDE with Bitcoin Core please do so at https://github.com/bitcoin-core/docs

**Comment by sipsorcery** [comment]
> If someone wants to add documentation on how to setup an IDE with Bitcoin Core please do so

Double click build_msvc/bitcoin.sln from #11526 ;).

**Comment by toknT** [comment]
I am using wsl  and vscode to debug set .launch.json like this 

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/src/bitcoind",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
