### ISSUE TITLE
Gitian crash for ARM compiling BDB depends (Bionic host)

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13700]
I was trying a Gitian build for master at 9cdb19fe6717b1003e01d997c096fb4ab534aa03? I used LXC (not Docker), but then crashes during depends make with bdb:

```
libtool: compile:  arm-linux-gnueabihf-g++ -c -I. -I../dist/./.. -I/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/include -D_GNU_SOURCE -D_REENTRANT -std=c++11 ../dist/./../cxx/cxx_multi.cpp  -fPIC -DPIC -o cxx_multi.o
libtool: compile:  arm-linux-gnueabihf-g++ -c -I. -I../dist/./.. -I/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/include -D_GNU_SOURCE -D_REENTRANT -std=c++11 ../dist/./../cxx/cxx_mpool.cpp  -fPIC -DPIC -o cxx_mpool.o
In file included from ../dist/./../cxx/cxx_mpool.cpp:1:0:


Internal compiler error: Error reporting routines re-entered.
./libtool --mode=compile arm-linux-gnueabihf-g++ -c -I. -I../dist/./.. -I/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/include     -D_GNU_SOURCE -D_REENTRANT -std=c++11     ../dist/./../cxx/cxx_seq.cpp
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Makefile:2032: recipe for target 'cxx_mpool.o' failed
make[1]: *** [cxx_mpool.o] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  arm-linux-gnueabihf-g++ -c -I. -I../dist/./.. -I/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/include -D_GNU_SOURCE -D_REENTRANT -std=c++11 ../dist/./../cxx/cxx_seq.cpp  -fPIC -DPIC -o cxx_seq.o
make[1]: Leaving directory '/home/ubuntu/build/bitcoin/depends/work/build/arm-linux-gnueabihf/bdb/4.8.30-8f2a4f0c933/build_unix'
funcs.mk:242: recipe for target '/home/ubuntu/build/bitcoin/depends/work/build/arm-linux-gnueabihf/bdb/4.8.30-8f2a4f0c933/build_unix/.stamp_built' failed
make: *** [/home/ubuntu/build/bitcoin/depends/work/build/arm-linux-gnueabihf/bdb/4.8.30-8f2a4f0c933/build_unix/.stamp_built] Error 2
```

Gitian worked when I tested an earlier version of #13604, on a Debian 9 host and before Bionic descriptors were merged. Perhaps the changes added before merge cause a problem, or perhaps there's something about the Bionic descriptors (or host).

**Comment by ken2812221** [comment]
I didn't see this issue on Bionic host. Did you try build it again?

**Comment by Sjors** [comment]
@ken2812221 I'm currently trying to build on the Bionic host directly. If that works, I'll try Gitian again.

**Comment by ken2812221** [comment]
@Sjors I just did gitian build for master a few minutes ago, didn't see any issue.

**Comment by Sjors** [comment]
I was able to cross-compile on the Bionic host (and the QT binary works on the device).

I ran Gitian again:

```sh
python3 gitian-build.py --detach-sign --no-commit -b sjors -c 9cdb19fe6717b1003e01d997c096fb4ab534aa03 -j5
```

This time it's happy.

Maybe it was just a fluke. However I added a bunch of dependencies on the host machine while writing #13702, so maybe that matters? `g++-arm-linux-gnueabihf g++-aarch64-linux-gnu binutils-arm-linux-gnueabihf binutils-aarch64-linux-gnu g++-4.8-multilib gcc-4.8-multilib binutils-gold`

**Comment by laanwj** [comment]
If it isn't a cosmic ray or CPU overheating it's a compiler bug.

**Comment by theuni** [comment]
GCC ICE's in Gitian have historically been due to running out of mem. Maybe you're running too many parallel jobs?

**Comment by Sjors** [comment]
`-j5` on a VM with 10 GB RAM and 4 vCPU's. Happy to blame the cosmic ray if nobody else runs into it on a fresh machine.

**Comment by jonasschnelli** [comment]
Don't you also need the `--memory <4000 or something>` for gbuild? Seems to be very likely OOM.

**Comment by MarcoFalke** [comment]
Closing for now. You can ask me to reopen, if this happens again.
