### ISSUE TITLE
getreceivedbylabel

### ISSUE THREAD

**Issue by melaxon** [bitcoin/bitcoin#13704]
**Describe the issue** 
`bitcoin-cli getreceivedbylabel "xxx" 0`  will not return any error if xxx does not exists. Not sure if this is an issue or "works as designed"

 **What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?** 
0.16.99 compiled
**What type of machine are you observing the error on (OS/CPU and disk type)?** 
Ubuntu 16.04

**Comment by jonasschnelli** [comment]
Should it return an error? IMO its more like a "filtering-technique" (by labels) and an empty list seems to be the better design choice then throwing an error.

**Comment by melaxon** [comment]
At least something like 'false' can be returned. Why to search by non-existing labels then?

**Comment by MeshCollider** [comment]
In my opinion, this seems sensible behavior as-is. If nothing is labelled with a particular label then there should be a total of 0 received by that label, I don't think its necessary not logical to return a different type if the label isn't being used.
