### ISSUE TITLE
why did the rpc call get the error of EOF

### ISSUE THREAD

**Issue by kazaff** [bitcoin/bitcoin#13737]
hi there~

I wonder that what happened when my program call the RPC Api(`gettransaction`method) and the method return the EOF error, like this:`Post http://127.0.0.1:8332: EOF`.

My project is based on Golang, and it send http request by `github.com/go-resty/resty` lib.

I have no idea about this situation. Does anyone can give me any point? thanks in advance~~

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
