### ISSUE TITLE
unable to build in windows 10 x64 using Windows Subsystem for Linux (WSL) 

### ISSUE THREAD

**Issue by FIVIL** [bitcoin/bitcoin#13730]
Hi, i did all the instruction mentioned in [here](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md) but when i hit `CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/` command i get this:
`qwin10helpers.cpp:60:37: fatal error: uiviewsettingsinterop.h: No such file or directory
compilation terminated.
Makefile.Release:6922: recipe for target '.obj/release/qwin10helpers.o' failed
make[5]: *** [.obj/release/qwin10helpers.o] Error 1
make[5]: Leaving directory '/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/src/plugins/platforms/windows'
Makefile:36: recipe for target 'release' failed
make[4]: *** [release] Error 2
make[4]: Leaving directory '/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/src/plugins/platforms/windows'
Makefile:66: recipe for target 'sub-windows-make_first' failed
make[3]: *** [sub-windows-make_first] Error 2
make[3]: Leaving directory '/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/src/plugins/platforms'
Makefile:96: recipe for target 'sub-platforms-make_first' failed
make[2]: *** [sub-platforms-make_first] Error 2
make[2]: Leaving directory '/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/src/plugins'
Makefile:687: recipe for target 'sub-plugins' failed
make[1]: *** [sub-plugins] Error 2
make[1]: Leaving directory '/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/src'
funcs.mk:242: recipe for target '/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/.stamp_built' failed
make: *** [/home/fivil/bitcoin/depends/work/build/x86_64-w64-mingw32/qt/5.9.6-dafa751a5be/qtbase/.stamp_built] Error 2`
well first time it took very long amount of time till showing this error but after that it just keep appearing in no time
Oh and i think it worth to mention that i did try to manually download and attach missed header file but no luck :(

**Comment by ken2812221** [comment]
Can you make sure that you are using Ubuntu 18.04?

**Comment by fanquake** [comment]
@FIVIL Can you provide more information?

I've just done a build of master (https://github.com/bitcoin/bitcoin/commit/07ce278455757fb46dab95fb9b97a3f6b1b84faf) using the [64 bit Windows instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows), and it's working correctly:
![wsl](https://user-images.githubusercontent.com/863730/43032930-b4dc7458-8cf3-11e8-9de2-33957666c77a.png)


Also, are you sure that it's `./configure` that is giving you that output?

**Comment by FIVIL** [comment]
Problem was with the version of ubunto, now its work fine
Tnx for your time

**Comment by MasterKungfu** [comment]
I have the same error, Win10 sub unix system, bash command line. cross compile.
