### ISSUE TITLE
travis job x86_64 Linux with qt5 dev packages takes always 40 minutes (missing cache?)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#13748]
The travis job

https://github.com/bitcoin/bitcoin/blob/7ebd8c6385253bfa30175169a22f93474d8ddfaf/.travis.yml#L36

always takes about 40 minutes on master and pull requests, whereas it should take about 15 minutes with a hot cache.

**Comment by ken2812221** [comment]
#13650 should fix this
