### ISSUE TITLE
would you release v0.16.1 to ppa:bitcoin/bitcoin for ubuntu?

### ISSUE THREAD

**Issue by caiqinghua** [bitcoin/bitcoin#13749]
Ubutun apt install bitcoind.
bitcoind --version
1.6.0
We can't get 1.6.1 in Ubutun.

Release 1.6.1 to ppa:bitcoin/bitcoin

**Comment by jonasschnelli** [comment]
Ping @TheBlueMatt

**Comment by jonasschnelli** [comment]
I guess 0.16.2 makes now more sense.

**Comment by MarcoFalke** [comment]
> I guess 0.16.2 makes now more sense.

I believe this was fixed
