### ISSUE TITLE
cd: depends: no such file or directory

### ISSUE THREAD

**Issue by bekarys0504** [bitcoin/bitcoin#13757]
This is the screenshot of the error I am getting, I am doing everything as shown on the tutorial, could someone pls help, stuck on this for 3 hours.
![image](https://user-images.githubusercontent.com/12554815/43199735-d099326e-9034-11e8-83ea-d333bd6baf9c.png)

**Comment by fanquake** [comment]
You need to cd into `bitcoin` then into `depends`. The file structure is `bitcoin/depends/`.

**Comment by bekarys0504** [comment]
Thanks it helped me
