### ISSUE TITLE
Assembly optimisations cause build to fail when contradicting CXXFLAGS are used

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#13758]
When configuring with `CXXFLAGS="-O1 -ggdb -Wall -mno-avx2"`...

configure detects AVX by passing the `-mavx -mavx2` flags *after* CXXFLAGS, so succeeds:
```
configure:19622: checking whether C++ compiler accepts -mavx -mavx2
configure:19641: g++ -std=c++11 -c -O1 -ggdb -Wall -mno-avx2 -Werror -mavx -mavx2  conftest.cpp >&5
configure:19641: $? = 0
```

But then the build uses `-mavx -mavx2` *before* CXXFLAGS, which fails:
```
/usr/bin/ccache g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DENABLE_AVX2 -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -Wstack-protector -fstack-protector-all      -fPIE -mavx -mavx2 -O1 -ggdb -Wall -mno-avx2 -MT crypto/crypto_libbitcoin_crypto_avx2_a-sha256_avx2.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_avx2_a-sha256_avx2.Tpo -c -o crypto/crypto_libbitcoin_crypto_avx2_a-sha256_avx2.o `test -f 'crypto/sha256_avx2.cpp' || echo './'`crypto/sha256_avx2.cpp
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/immintrin.h:43:0,
                 from crypto/sha256_avx2.cpp:4:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/avx2intrin.h: In function ‘__m256i sha256d64_avx2::{anonymous}::Add(__m256i, __m256i)’:
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/avx2intrin.h:119:1: error: inlining failed in call to always_inline ‘__m256i _mm256_add_epi32(__m256i, __m256i)’: target specific option mismatch
 _mm256_add_epi32 (__m256i __A, __m256i __B)
 ^~~~~~~~~~~~~~~~
crypto/sha256_avx2.cpp:14:72: note: called from here
 __m256i inline Add(__m256i x, __m256i y) { return _mm256_add_epi32(x, y); }
                                                                        ^
make[2]: *** [Makefile:4533: crypto/crypto_libbitcoin_crypto_avx2_a-sha256_avx2.o] Error 1
```

IMO the better solution is to fix the build (ie, continue to build AVX support even with the contradicting CXXFLAGS) by passing `-mavx -mavx2` after CXXFLAGS.

**Comment by luke-jr** [comment]
CC @laurentb

**Comment by luke-jr** [comment]
(on the other hand, simply fixing the build makes it impossible for users to avoid building specific assembly optimisations? maybe that's better done with a hypothetical `--disable-asm=sse4,avx` or such)

**Comment by laurentb** [comment]
For the context, I use Gentoo, and my CFLAGS are basically an expanded -mnative (https://github.com/hartwork/resolve-march-native also does this).

0.16.0 was compiling fine but not 0.16.1.

**Comment by luke-jr** [comment]
(@laurentb means Knots 0.16.1, which has the assembly optimisations from master. The issue is confirmed to affect master also.)

**Comment by luke-jr** [comment]
Note that autotools (apparently intentionally) makes overriding user CXXFLAGS basically impossible, and also expects CXXFLAGS to be valid to change between `configure` and `make`, so there isn't really a solution to this. For now, #13789 uses pragmas to force the required instructions enabled for the relevant files, but this only works with GCC and Clang.

**Comment by fanquake** [comment]
> Note that autotools (apparently intentionally) makes overriding user CXXFLAGS basically impossible,

At least in our build system, this should no-longer be true.

> but this only works with GCC and Clang.

I've PR'd an alternative in #25829 that should work regardless of compiler.
