### ISSUE TITLE
Can't minimize BitcoinQt to tray

### ISSUE THREAD

**Issue by johnnyasantoss** [bitcoin/bitcoin#13772]
I've upgraded to BitcoinQt 0.16.1 and now I can't minimize to tray.

### Expected behavior
Check the setting and it work.

### Reproducing
I don't really know if this is a problem with gnome in Ubuntu 18.04.1 LTS, but this is an almost clean installation (reinstalled +- 1w ago).
I downloaded the compiled binary from https://bitcoin.org/en/download and verified the signature/hash.
Installed following the steps given in the webpage.
Tried to mark the Window options to minimize to tray, but It only works once.
After you open the window it doesn't minimize to tray again, even with the settings checked.

### My machine infos
```bash
johnny ~ uname -a
Linux mars 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
johnny ~ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

```

### Logs & images
Every time I restart it appears unchecked.
![image](https://user-images.githubusercontent.com/14189387/43286925-cac0ef88-90f9-11e8-93e0-51eabcfb8970.png)

[debug.log](https://pastebin.com/raw/3AWvpGXw)
[bitcoin.config w/o rpc](https://pastebin.com/raw/gyGXj7GN)

**Comment by redblade7** [comment]
This may be related to #13606

**Comment by hebasto** [comment]
@johnnyasantoss 
Are you still experiencing this problem with the latest 0.17.0rc2?

**Comment by johnnyasantoss** [comment]
@hebasto Sorry, I totally forgot about this issue. In the end I started using the CLI and didn't have to use the GUI anymore.
