### ISSUE TITLE
Can't set custom rpcport on testnet

### ISSUE THREAD

**Issue by nkostoulas** [bitcoin/bitcoin#13777]
Hello
Is anyone aware of recent changes to the bitcoin client regarding rpcport and testnet. I am trying to set a custom port and get this 

`Warning: Config setting for -rpcport only applied on test network when in [test] section.`

If I put the `[test]` section on top it ignores everything and runs mainnet, and if I only put it on top of `rpcport` it doesn’t work either.

I believe the 'section' thing was recently added but I couldn't find any documentation on how to use it.

**Comment by jonasschnelli** [comment]
Works here as expected.
Have you had a look at https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes-pr12823.md?
(or at the PR itself #11862?)

**Comment by nkostoulas** [comment]
Ah okay so you need to provide a value for [main] before providing one for [test].

Thanks for this! I couldn't find the relevant documentation.
