### ISSUE TITLE
Bitcoin.org supporter donations

### ISSUE THREAD

**Issue by andrerademan** [bitcoin/bitcoin#13785]
I would like to propose a unique "supporter donations" model to support bitcoin.org indefinitely.

## Proposal:

1. Large funds and holders voluntarily pay 0.0x% of their holding to a foundation that reimburses developers and people working on bitcoin.org.
2. Exchanges and other service providers like wallets or even mining pools pay 0.0x% of their income estimated from BTC each year.

This is completely voluntary and such supporters are listed on bitcoin.org. The best placement would be in the right-hand-margin of all pages or the home page as "Bitcoin supporters" (or such-like) and then headings, e.g. Exchanges, Wallets, Funds etc. Could be a logo until there are too many and then it could be a link in order of donation size. The first x under each heading is listed with a more link to a dedicated page listing supporters first and all non-supporters thereafter (have to be comprehensive). The SEO itself is worthwhile.

## Benefit

1. Obviously the benefit is accelerated development of bitcoin (faster rollout of higher quality code because some people might just be able to give up their day job to focus exclusively on Bitcoin development).
1. Exchanges, funds and service providers would obviously benefit from increased Bitcoin adoption. The growth of Bitcoin is also the growth of the whole Crypto industry.
1. With exchanges, funds and service providers listed very publically on Bitcoin.org, they will get additional business from the public who would like to support Bitcoin by the choice of Exchange and Wallet they choose...
1. By having multiple non-exclusive supporters it would avoid divisive politics inside bitcoin.org such as the recent exclusive sponsorship debate.

## Disbursement

Obviously the funds could be used to pay maintainers of the Bitcoin.org site content to continue making it the best bitcoin resource in the world. But the bulk of proceeds should go to bitcoin developers for the extensive time they spend on Bitcoin development. Receivers can either view proceeds as reimbursement for their time, or donate it on to a cause they believe in. Some developers might just be able to give up their day job to focus exclusively on Bitcoin development while others donate their proceeds, completely up to them.

The disbursement % could be decided annually by anonymous vote on who helped advance bitcoin more within the preceding year. In my view the vote can be refined, i.e. after the first year you build up vote karma, and then your vote counts more for the next year, but each successive year Karma points deflates to give people who have benefitted Bitcoin in the last x years more say in the decisions. This is a much better determinant than simply checking commits per year.

## Possible implementation

Ask the biggest potential donors (exchanges, funds) if they might consider donating, what % would make sense to them. Pick a very low average and do it for one year. If it does not work for whatever reason, stop. Or revise the % slightly annually, and continue.

Thanks for your time considering this proposal.

**Comment by fanquake** [comment]
This isnt the right place to discuss this.
