### ISSUE TITLE
How to set some options in config file, like -reindex

### ISSUE THREAD

**Issue by DinoStray** [bitcoin/bitcoin#13800]
I can use -reindex with bitcoind, like
`bitcoind -reindex`
but how can I use reindex in config file?
I tried 
`reindex=true`
or
`reindex=1`
in config file, but nothing happened

**Comment by jonasschnelli** [comment]
Have you used the correct config file name and location?
`reindex=1` should centrally work.
Have you verified it's not re-indexing (check your debug.log)?
