### ISSUE TITLE
NSIS: Error launching the installer when login name contains some non-ascii characters

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#13817]
Steps to reproduce:

* Install Windows 7
* Create user `a_ä_α_Б`
* Launch installer (Tested for 0.16.2 and current master)

![screenshot from 2018-07-31 10-02-37](https://user-images.githubusercontent.com/6399679/43464534-581a1faa-94a9-11e8-9f52-da72fef9988d.png)

**Comment by fanquake** [comment]
I've started looking into some of these issues. Using a binary compiled on WSL, launching for the first time (Windows 10) we can't create the data directory:
<img width="492" alt="wsl" src="https://user-images.githubusercontent.com/863730/43512479-c7c4f7f8-95ad-11e8-9fd7-5b758f8cc606.png">

**Comment by ken2812221** [comment]
@fanquake I believe that issue can be fixed by #13787.(with leveldb change)

**Comment by MarcoFalke** [comment]
Potentially fixed by #13827

**Comment by MarcoFalke** [comment]
An alternative to fix this would be to bump to Ubuntu Focal in gitian. This is fixed in nsis3. https://packages.ubuntu.com/focal/nsis

**Comment by MarcoFalke** [comment]
This is probably fixed by #21036

**Comment by hebasto** [comment]
I can confirm this bug on Windows 10 Pro (20H2, build 19042.804):

![Windows 10_02_03_2021_13_43_16](https://user-images.githubusercontent.com/32963518/109643716-4b463780-7b5d-11eb-99ee-44cae3de54df.png)
