### ISSUE TITLE
Unhide QT window doesn't work when hidden with ⌘ + H

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13829]
Noticed this while reviewing #13529, but it's also in master @ 5ba77df. On macOS 10.13.6:

<img width="209" alt="schermafbeelding 2018-08-01 om 16 22 09" src="https://user-images.githubusercontent.com/10217/43527498-0f571db4-95a7-11e8-8d90-7863947a7689.png">

<img width="178" alt="schermafbeelding 2018-08-01 om 16 12 51" src="https://user-images.githubusercontent.com/10217/43526994-c9a515ec-95a5-11e8-96b8-9e2513e9aac5.png">

* `Show` in the action menu doesn't work if the app was hidden by `Command + H`, it does work when hidden through this menu
* send and receive don't unhide the window when opened for the action menu. It does navigate to the right tab. The other actions do work (sign, verify & debug window)

Clicking "Toon" (= macOS native show) does work, suggesting the GUI uses some non-native method of hiding.

**Comment by redblade7** [comment]
I'm not familiar with Mac, but it might be related to #13606

**Comment by jonasschnelli** [comment]
I can confirm that the action menu "show" doesn't work when hided with `Command + H`.

When hided with the action menu, "send" and "receive" do show the window, but not when used `Command + H`.

Fix welcome.

**Comment by promag** [comment]
> I can confirm that the action menu "show" doesn't work when hided with Command + H.

For me works with Qt 5.11.1 and macOS 10.13.3 at 6c7cfc8da. @Sjors @jonasschnelli which Qt you used?

**Comment by promag** [comment]
> When hided with the action menu, "send" and "receive" do show the window, but not when used Command + H.

I also confirm this with Qt 5.11.1 and macOS 10.13.3.

> Fix welcome.

I take this.

**Comment by promag** [comment]
Similar problems to #5880 and #2530.

**Comment by hebasto** [comment]
Here are more tests.
OS X 10.11.6 (15G22010) + 0.17.0 (Qt 5.9.6)

Step 1: Dock menu "Hide"

... some variants of...
Step 2: Dock menu "Show" - works as expected: shows main window and brings it to the front.

Step 2: Dock menu "Send" or "Receive" - _does not work_: does not show main window at all.

Step 2: Dock menu "Sign message..." or "Verify message..." - works with some issues: (a) shows main window, (b) shows "sign/verify" window, (c) _does not_ bring any of mentioned windows to the front, (d) makes app icon bounce continuously :) , (e) many items of the Dock menu get greyed.

Step 2: Dock menu "Debug window" - works as expected: shows both main window and debug window, and brings the latter to the front.

Moreover, using Command-H or "Hide Bitcoin Core" from the app menu in the Step 1 does not change behaviour.

**Comment by hebasto** [comment]
@fanquake, @jonasschnelli should this issue be labeled "macOS"?
