### ISSUE TITLE
Bitcoind testnet keeps syncing over again

### ISSUE THREAD

**Issue by mareksip** [bitcoin/bitcoin#13839]
Hello,

Running: 0.16 on windows server 2016, x64

After launching bitcoind with following command and letting the node fully sync, on the next launch, bitcoind starts syncing from the same position from block from 24th April.

bitcoind -server -rpcuser=test -rpcpassword=1234 -datadir="D:\BitcoinCoreData" -printtoconsole -testnet

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by mareksip** [comment]
@MarcoFalke I am unable to post here debug.log because it has 0 bytes. I did -reindex for testnet3. Blockchain synchronized on 4th August. Hope it points to where I made mistake.

**Comment by MarcoFalke** [comment]
I see that my link tells you where to find the default location for the debug log. If you set the datadir to a different one, the debug log will be in that location as well.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
