### ISSUE TITLE
Keyboard shortcuts don't work on macOS

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13832]
With the exception of `q` during startup, and system defaults, non of the QT keyboard shortcuts work on macOS. In case anyone wants to test a fix, here's a list:

*  Ctrl + Q (quits application)
*  Ctrl + Shift + C (opens console)
*  Ctrl + Shift + D (opens debug window)
*  regex `tr\(\".*&.*\"\)` for other shortcuts (menu and `QAction`)

There are some complaints on the internet suggesting this is a QT issue, but it's not super clear to me.

**Comment by isghe** [comment]
`Ctrl` or `CMD`?

**Comment by fanquake** [comment]
> ctrl or cmd?

Indeed, you should be using `CMD ( ⌘)` on macOS. 
The following shortcuts seem to be working as expected (f030410):
`q` to quit during startup
`CMD + q` to quit at any point
`CMD + Shift + c` opens the console
`CMD + Shift + d` opens the debug window
`CMD + ,` opens the preferences menu

**Comment by jonasschnelli** [comment]
Works as expected.
macOS always used `CMD` instead of `ctrl` and I guess QT is doing it right here. Also, the menu items correctly list `⌘ Q` for quit, (etc.).
Close?

**Comment by fanquake** [comment]
Agree with @jonasschnelli. @Sjors If there is a specific `CMD` shortcut that isn't working, please reopen.

**Comment by Sjors** [comment]
Ah indeed, CMD + Shift + c and d work, I updated the description.

None of the one letter shortcuts for menu items and form fields work for me, and they're not displayed so you have to guess them.
