### ISSUE TITLE
[GUI] coin selection: (un)select all doesn't toggle coin checkboxes (QT 5.11)

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13833]
<img width="459" alt="schermafbeelding 2018-08-01 om 17 02 24" src="https://user-images.githubusercontent.com/10217/43529950-b2b21a90-95ac-11e8-877f-6d6dd5e2f857.png">

When I press the "(un)select all" button the totals change, but the check box isn't enabled. 
<img width="456" alt="schermafbeelding 2018-08-01 om 17 02 32" src="https://user-images.githubusercontent.com/10217/43529959-b6cbcc84-95ac-11e8-92ff-e20d9cff566f.png">

**Comment by MarcoFalke** [comment]
This is macOS on master only?

**Comment by Sjors** [comment]
I haven't tested it elsewhere, but I'd be surprised if this was OS specific.

**Comment by hartley785** [comment]
#9260 wallet balance

**Comment by jonasschnelli** [comment]
Works for me on my macOS (10.13.5) local build (QT 5.10) as well on "official" 0.16 macOS (Qt 5.7).

**Comment by Sjors** [comment]
I tried again with master @ 2c14c1fa2 and  `v0.16.2` (QT 5.11.1), same problem.

The official download does behave for me. I tried compiling 2c14c1fa2  again this time with `depends` (Qt 5.9.6), which also behaves.

So it looks like some change between QT 5.10 and QT 5.11 breaks things, which could indicate more troubles ahead.

**Comment by promag** [comment]
I have the same issue, macos 10.13.3, Qt 5.11.1. Are you trying to fix @Sjors?

**Comment by Sjors** [comment]
@promag nope, it's not very urgent and I'm not sure where to look, so consider it up for grabs.

**Comment by hartley785** [comment]
Bitcoin belonging to me

**Comment by hebasto** [comment]
Tested on macOS 10.13.6 (17G65) + Qt 5.11.2
It works as expected.

**Comment by Sjors** [comment]
Tested master (two weeks before 0.18 branching) on macOS 10.14.3 with Qt 5.12.0 and not seeing this problem anymore.
