### ISSUE TITLE
Double transaction on same hash (transaction ID) - Loosing 0.01 btc each time

### ISSUE THREAD

**Issue by syrius01** [bitcoin/bitcoin#13858]
Hi,

Each time I send some btc to another bitcoin wallet there is a second transaction on the same transaction ID (hash) and each times i am loosing around 75 USD.

You can see by yourself here;

https://www.blockchain.com/btc/address/1NrZWuS4J8MAqX63NHFuLrdmBYf6FttX29

Another weird fact is that on my bitcoin wallet software balance, it's not showing to balance I lost.

Any help would be very appreciated,

Thanks.

**Comment by MarcoFalke** [comment]
This is the change that is sent to one of you wallet addresses.

**Comment by syrius01** [comment]
Hi @MarcoFalke 

Thank you for replying. I am having a hard time understanding what you are trying to say. It seems to be unclear. The issue I am currently having like I said is that each times I send some amounts of BTCs to another Bitcoin wallet, there is a second transaction created on the same transaction ID (hash). For more details, you can have a look on https://www.blockchain.com/btc/address/1NrZWuS4J8MAqX63NHFuLrdmBYf6FttX29

I'm not sure your answer is accurate with this issue I am having.

Thanks

**Comment by sipa** [comment]
This is not a place to ask basic questions about Bitcoin.

Please head to https://bitcoin.stackexchange.com for questions.
