### ISSUE TITLE
Travis test for commit range

### ISSUE THREAD

**Issue by skeees** [bitcoin/bitcoin#13865]
When a pr contains multiple commits, it would be good to test that every commit in that range at the very least builds and passes unit tests (current travis just runs against the branch head). Having no broken commits preserves git bisectability.

I'm not a travis expert so just leaving this here, for maybe someone who is more familiar to pick up.

This is probably also a "good first issue"

**Comment by dongcarl** [comment]
Would `git rebase --autosquash --exec "<test cmd>"` accomplish this?

**Comment by prusnak** [comment]
Not sure if this is possible as this would exponentially increase requirements put on Travis build servers if more projects used this.

**Comment by piraces** [comment]
I think I can work on this.
I will think about @dongcarl idea, and other possible alternatives.

**Comment by piraces** [comment]
I have researched about it, and Travis don't support this feature, as we can see in this feature request: [building every revision ](https://github.com/travis-ci/travis-ci/issues/9183).

I have also tried in my own fork to execute git rebase --exec "<tests scripts>" but I don't know where to exactly put this command. I think the best place to execute it's actually _lint_05_before_script.sh_

And pass to the exec argument the desired tests to run. 
What do you think about that?

**Comment by MarcoFalke** [comment]
Indeed, if you want every commit to run travis, you'd have to push them individually.

**Comment by piraces** [comment]
@MarcoFalke Actually yes... However, I will watch the referenced feature request in travis-ci, for some resolution.

**Comment by D4nte** [comment]
On Circle CI API you can trigger a new build and pass the commit SHA: https://circleci.com/docs/api/#trigger-a-new-job

Maybe the same is possible for Travis?

In this case, when opening a PR we could create a GitHub Action that triggers a build for each commit in the PR.

If my understanding of GitHub is correct, doing so would show the green ticks against each commit in GitHub (GitHub remembers checks per commit hash).

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
