### ISSUE TITLE
How to disable address change when send?

### ISSUE THREAD

**Issue by toan85** [bitcoin/bitcoin#13874]
How to disable my wallet change address every time I send coin?
I need to use only 1 address! I will add, choose, generate, new address when I want.
Why change address every time send coin?
If I want to change address, I simply send my coin to another address.
I need to disable my wallet change address every time I send coin!

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by luke-jr** [comment]
Bitcoin doesn't work that way. Addresses are single-use tokens, and should only be used to receive a single transaction ever. They don't hold coins at all.

**Comment by rraallvv** [comment]
@luke-jr thanks for the clarification.
