### ISSUE TITLE
Effective value coin selection may not work properly with watching only utxos

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#13906]
Looking through how fees are calculated for calculating the effective value for BnB coin selection, I think there may be an issue with utxos that are considered ISMINE_WATCH_ONLY. Since we cannot solve or sign for these UTXOs, we are unable to calculate the size of the input for these utxos and thus the fee. This means that when we perform BnB on these watching only utxos that the fee will be zero and the effective value will be the entire value. So we could end up with much lower fees than we intend if we are selecting watching only utxos.

I haven't actually tested this yet, but it seems to be correct if I am following the logic correctly.

**Comment by sipa** [comment]
This is only an issue for `fundrawtransaction`, right? In any other place we only select coins that aren't only watched but we can also sign for.

For P2PK/P2WPKH we can estimate the size even without being able to solve them. For others, I guess the only options are either refusing to select the coins, return an error, or give a default guess (say, assume every P2SH is P2WSH/3-of-3-multisig or so).

**Comment by achow101** [comment]
It turns out I did not follow the logic correctly and missed that `GroupOutputs` filters for outputs that are spendable (either actually spendable, or solvable and watch only was enabled). Since spendable means that we can construct the scriptSig if we have the private keys, we can estimate the fee for effective value correctly. So this is not a problem.
