### ISSUE TITLE
adduser: The user `bitcoin' already exists. Exiting.

### ISSUE THREAD

**Issue by SearchAndDestroy** [bitcoin/bitcoin#13901]
I am trying to update my bitcoin core version to 0.16.2 via the Ubuntu ppa but I am getting ```adduser: The user `bitcoin' already exists. Exiting.```.
My system is Bitseed3 running Ubuntu 16.0.5 LTS (Xenial) and a user bitcoin is already existing and is used as the normal login user.
Any idea how to correct this error? I am getting it every time I use apt-get install:
```
$ uname -a
Linux bitseed3 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ sudo apt-get install bitcoind
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  bitcoind
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 0 B/1,811 kB of archives.
After this operation, 6,613 kB of additional disk space will be used.
Selecting previously unselected package bitcoind.
(Reading database ... 88747 files and directories currently installed.)
Preparing to unpack .../bitcoind_0.16.2-xenial1_amd64.deb ...
Unpacking bitcoind (0.16.2-xenial1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up bitcoind (0.16.2-xenial1) ...
adduser: The user `bitcoin' already exists. Exiting.
dpkg: error processing package bitcoind (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bitcoind
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Derek701** [comment]
As a workaround, you can try commenting out the line

`adduser --system --home "${BCHOME}" --no-create-home --group "${BCUSER}"`

near the top of the file `/var/lib/dpkg/info/bitcoind.postinst` and running the install command again.

**Comment by SearchAndDestroy** [comment]
@Derek701 thanks, it worked but I would like to avoid editing every time a new version is released :)

**Comment by TheBlueMatt** [comment]
These issues should be filed against the packaging repo, see https://github.com/bitcoin-core/packaging/issues/5
