### ISSUE TITLE
[testnet] Warning: unknown new rules activated (versionbit 1) on v0.16.2.0-6518bcd

### ISSUE THREAD

**Issue by cryptozeny** [bitcoin/bitcoin#13900]
![bitcoin core - wallet testnet _118](https://user-images.githubusercontent.com/37016180/43766387-43d1b8a4-9a6d-11e8-9dd5-0292fb139c27.png)

```
ubuntu 16.04 64-bit
v0.16.2.0-6518bcd
```

what is this mean? can i ignore this message safely?

**Comment by thelukemccarthy** [comment]
I have the same issue. 
The only this I could find was on ([https://www.reddit.com/r/lightningnetwork/comments/7n4mxt/testnet_warning_unknown_new_rules_activated/](ReadIt)) saying that it was to do with Bitcoin Cash and you can ignore it. **I haven't been able to confirm this.**

**Comment by MarcoFalke** [comment]
Miners can signal support for non-existent versionbips deployments. If they do, this warning pops up and I don't think that anything could be done about that.

**Comment by vishesh3006** [comment]
I have the same issue and even my receiving addresses are not shown

**Comment by HashUnlimited** [comment]
The issue is currently back on master branch. The warning appears if ALL blocks checked back are indeed dec version 4 or 0x20000000 

at least one unimplemented version bit has to be set during the check.
