### ISSUE TITLE
Gitian-Builder fails with check hashing

### ISSUE THREAD

**Issue by oshek14** [bitcoin/bitcoin#13923]
GItian-builder fails when I run deps-win32.yml. I am using bitcoin's earlier version so that to learn creating new coin. I'm using 0.8.7.4 and in that gitian-builder version there's a package requirement named - "miniupnpc-1.9.20140401.tar.gz" so I downloaded it from the official website and put it into gitian's inputs folder. then I run sudo bin/gbuild ../mycoin/contrib/gitian-descriptors/deps-win32.yml and it fails and tells me 
miniupnpc-1.9.20140401.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

I am using the exact same version of miniupnpc as it asks me to use in depth-win32.yml. what is wrong? please guys help

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
