### ISSUE TITLE
Bitcoind no longer outputs logs to stdout

### ISSUE THREAD

**Issue by leishman** [bitcoin/bitcoin#13929]
## Summary
Running `bitcoind` no longer prints anything to stdout. It makes it seem like bitcoind is just hanging, when it is in fact running properly.

## Expected Behavior
I expected to see some logs print to the console when running `bitcoind` not in the daemon mode.

## Actual Behavior
No output when running `bitcoind` from command line. It just appears to hang, but is actually functioning properly.

## Version
0.16.2 from ubuntu ppa

## Machine Type
ubuntu server

**Comment by sipa** [comment]
It never did, AFAIK?

**Comment by leishman** [comment]
It does when I build the binary manually on my Mac and run that. Is there a build flag that changes this behavior perhaps? I feel like everywhere else I run bitcoin it prints to console without the flag.

**Comment by sipa** [comment]
Ah, it was changed in master: https://github.com/bitcoin/bitcoin/pull/13004. It's not in any release yet, but will be 0.17.

Perhaps the versions you've compiled yourself were from the master branch?

**Comment by MarcoFalke** [comment]
Indeed, this is only on the master branch.

**Comment by leishman** [comment]
Ah ok that makes sense. I think previously I had always run it as a daemon and just forgot the default behavior.
