### ISSUE TITLE
Use C++ language binding for ZMQ

### ISSUE THREAD

**Issue by domob1812** [bitcoin/bitcoin#13957]
ZMQ has a [native language binding for C++](http://api.zeromq.org/2-1:zmq-cpp), which among other things takes advantage of RAII for the context, sockets and messages.

Is there any particular reason why Bitcoin Core's ZMQ interface does not use the C++ language bindings?  That would most likely simplify the code a lot and make it more robust against subtle bugs.

I'm aware that the `doc/zmq.md` file explicitly says that "the C++ language bindings are not necessary" - however, at least on my Debian system, it seems that the default ZMQ package `libzmq3-dev` already includes the C++ language bindings; so it is not really a separate dependency.

**Comment by jmcorgan** [comment]
At the time, the C++ wrapper (which is a single, inline C++ header file) was sometimes included in the C package, sometimes not, and the least effort imposed on the build was to do it in C and not worry about it. I don't know if this is still true.

Can you elaborate on the simplifications and bug resilience you're referring to? I've used both the native C API and the C++ wrapper, and there's not much difference.

**Comment by domob1812** [comment]
@jmcorgan:  The main point where I think the C++ wrapper improves readability and robustness is through type-safety and RAII.  Instead of passing around `void*` for the ZMQ context and socket, you have a typed object (e.g. `zmq::socket_t`).  And instead of manually calling an initialiser and a destructor for it, this is done by the language - including a guarantee that the destructor is called, which might be forgotten when using the pure C API (especially with things like multiple returns in a function or exceptions).

If there is no longer a big reason not to depend on the C++ wrapper, then I can simply prepare a PR that changes to it and then we can judge based on that how much it simplifies the code (or not).

**Comment by promag** [comment]
A PR would be great to test builds.

**Comment by practicalswift** [comment]
@domob1812 Sounds great!

**Comment by domob1812** [comment]
Demo PR is in #14017.

**Comment by promag** [comment]
Can close?

**Comment by domob1812** [comment]
Yes, I think we can close this since the C++ bindings seem to require separate dependencies on non-Debian systems (which I can't test).
