### ISSUE TITLE
Qt: "Welcome" dialog should let users set proxy settings

### ISSUE THREAD

**Issue by JeremyRand** [bitcoin/bitcoin#13952]
Describe the issue:

Bitcoin-Qt generates non-Tor network traffic on initial launch before allowing the user to change proxy settings.  This is an anonymity leak for users who aren't aware of the command-line or `bitcoin.conf` flags for proxy settings.

What behavior did you expect?

As part of the "Welcome" dialog on initial launch (which currently lets the user choose the data directory), Bitcoin-Qt should ask the user whether they'd like to set proxy settings.

What was the actual behavior (provide screenshots if the issue is GUI-related)?

Bitcoin-Qt doesn't prompt the user to set proxy settings before it starts connecting to the P2P network.

How reliably can you reproduce the issue, what are the steps to do so?

Run `bitcoin-qt` on a machine that has never run `bitcoin-qt` before.

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?

Bitcoin Core 0.16.2, downloaded from https://bitcoincore.org/en/download/

What type of machine are you observing the error on (OS/CPU and disk type)?

GNU/Linux x86 64-bit (Whonix 13, based on Debian Jessie, running under Qubes 3.2).  Haswell i7.  HDD.

**Comment by jonasschnelli** [comment]
I agree that this would be nice...

Ideally the Welcome dialog should....
* Ask for prune yes/no (I would always use 288 blocks as target)
* Ask for datadir (eventually for block _and_ for levelDB location)
* Ask for proxy (or plain "do you want to route traffic through TOR?")
* Ask for the dbcache ("how much memory do you want to use to speedup your sync?")
* Ask for encrypting the wallet

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/531.
