### ISSUE TITLE
CoInitialize(nullptr) in mt app

### ISSUE THREAD

**Issue by alexeyneu** [bitcoin/bitcoin#13979]
https://github.com/bitcoin/bitcoin/blob/63f8b0128b2aac3b25c6ec4d2f5bda213033162a/src/qt/guiutil.cpp#L548  
it's  (at least)a bit risky outside of  single-thread apps. 
```c++
	CoInitializeEx(NULL,COINIT_MULTITHREADED); 
```
could be used instead.  Only way i know to use it is to make separate thread with init-wait-uninit

**Comment by kirillkovalenko** [comment]
UI threads should and in many cases must be introduced into STA apartments, so CoInitialize is fine.

**Comment by alexeyneu** [comment]
nothing stops you to introduce(?) it in another thread as mta and then use in gui one. 'should' is a wrong word here . There're cases where it must not .In current case may be it's safe ,i didnt catch this stuff with shortcuts so cant say more. It's a warning  My bet is all part iscopy-pasted from somewhere.

**Comment by kirillkovalenko** [comment]
Putting main thread into MTA apartment is not something you usually want in a GUI application.  OLE stuff (shell, clipboard, controls hosting, property pages, etc) is designed to work STA. 

I don't see what is the risk that you mentioned.

**Comment by bill82773** [comment]
I found my old wallet and I need to get s signed copy of this how do I do that

**Comment by alexeyneu** [comment]
just checked msdn ,looks like it will work if this qt hack provides message  queue
