### ISSUE TITLE
[Feature] Make the "Request payment to ..." window printable

### ISSUE THREAD

**Issue by HydraGene** [bitcoin/bitcoin#13970]
I would like to suggest a simple idea to boost merchant adoption. 
Basically every merchant can already just accept Bitcoin, but they can't give out Bitcoin payment receipts yet. Customers would like to receive some form of physical proof of payment. 
Now I think the "Request payment" is a great feature for merchants. Label and Message can function as payment information, such as customercode and ordernumber etc.

The only thing missing in my opinion is the ability to print the "Request payment to ..." window. If we can print the information in this window, this can function as a decent store receipt.
Maybe we should be adding more optional fields in the future, so that the company details can be at the bottom of the receipt. A simple variable input field that allows multiple lines for example.

What do you think about this idea?

**Comment by jonasschnelli** [comment]
Unsure about this but not opposed to it.
I think its out of scope for Bitcoin Core to have a GUI for merchants. But if it is a simple change to add printability to that Screen, yes, why not.

**Comment by cryptobabel** [comment]
I was interested in something similar and can put this together I believe. I could see this being two tickets. One just for printing and another for adding additional fields. I believe adding new fields will require updating the model and store. Maybe I'm thinking about it wrong. That said, printing the data currently there isn't difficult. Would require additional dependency but nothing big or potentially breaking.. and is something that could probably merge quickly. 

To flesh it out a bit more... Would we want to see the QR/addy along with the other data or just the data fields? Also, is the data there currently worth printing out now as a receipt or should we wait to implement additional fields first? I believe we want both and what's there is sufficient for now, just talking it through before I move forward.

**Comment by fanquake** [comment]
I agree with Jonas. I think this is out of scope for this project, and it's unlikely that we'd add the Qt Print Support module to our Qt build.
