### ISSUE TITLE
preparation for support windows 98 ? or what is it

### ISSUE THREAD

**Issue by alexeyneu** [bitcoin/bitcoin#13980]
https://github.com/bitcoin/bitcoin/blob/63f8b0128b2aac3b25c6ec4d2f5bda213033162a/src/qt/guiutil.cpp#L567
So why someone may want not to define unicode?

**Comment by fanquake** [comment]
Please don't use this issue tracker to ask general questions about the codebase. The bitcoin stack exchange would be better suited for that: https://bitcoin.stackexchange.com.

**Comment by alexeyneu** [comment]
really it's not a question. All other stuff except unicode should be removed once you'd decide to support it

**Comment by alexeyneu** [comment]
@sipa i mean unicode support .windows 98 is the last(really last is millenium)  that's not support it .

**Comment by MarcoFalke** [comment]
@alexeyneu Indeed we are working on that. Please help to review #13869 to make progress here.
