### ISSUE TITLE
Can the default "minrelayfee" be decreased from 1 sat/B to 0.1 sat/B? The default value is too high at this moment.

### ISSUE THREAD

**Issue by pedr0-fr** [bitcoin/bitcoin#14012]
I have noticed that in the past weeks the mempool has been very empty and usually all transactions can get through with no problems, even the ones that eventually have feerates smaller than 1 sat/B as the mempool gets completely empty.

Therefore, I have set launched bitcoin with the relevant option `bitcoind -minrelayfee=0` but I am still not getting any transaction with a feerates smaller than 1 sat/B. I think this is because the nodes I am connected to don't relay transactions with feerates smaller than the 1 sat/B default. Can this default be changed to a lower value as the fees are lower now? There is an option to limit the total amount of the mempool so I think there would be no problem is this default was decreased to, say, 0.1 sat/B. 

Alternatively, is there any node I can connect to that relays lower fees than the default?

**Comment by TeoMorabito** [comment]
This is a good idea, though it would also need to include a way to round up the final fee to 1sat or greater as the smaller denomination.

**Comment by ken2812221** [comment]
Related to #13990

**Comment by rebroad** [comment]
I don't think it's a good idea to hard code any value into the code, but to allow it to change dynamically - i.e. if the mempool is getting empty, then lower it, and store this value to disk when the program exits.

**Comment by tryphe** [comment]
@rebroad @pedr0-fr There is some good discussion at https://github.com/bitcoin/bitcoin/pull/13990#issuecomment-889505833

**Comment by fanquake** [comment]
Closing for now.

**Comment by joshuadbryant1985** [comment]
Thank ye
