### ISSUE TITLE
Clean up the rpc method testmempoolaccept

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#14016]
Sorry I didn't see or comment in the initial PR for the RPC method `testmempoolaccept`, but I think the method could do with some finesse.

~~1. Don't take an array of transactions~~

2. Remove `allowhighfees`

This really shouldn't be a parameter going in, it should be part of the output.  e.g. `highFeeAlert: true`. 

3. Additional information like fees/sizes of the transaction (and ideally its entire ancestor cluster) should be returned, similar to what ever the mempool entry stuff has.

**Comment by promag** [comment]
IIRC the idea in supporting an array is to test transaction chaining.

**Comment by RHavar** [comment]
Ah, that makes perfect sense.

**Comment by RHavar** [comment]
Also I'm still not a huge fan of the array-of-transaction's going in. It really feels over-engineered especially as it's likely it'll never even get implemented.  At the least I think it should be overloaded with a simplified style:

testmempoolaccept $hex

instead of needing to wrap it with a json array  (And then unwrap the response)

**Comment by jnewbery** [comment]
Related: #13541

**Comment by glozow** [comment]
Looks like this has been resolved.

> ~1. Don't take an array of transactions~
> I'm still not a huge fan of the array-of-transaction's going in.  It really feels over-engineered especially as it's likely it'll never even get implemented.

Has been implemented in #20833.

> 2. Remove allowhighfees

Removed in #15620.

> 3. Additional information like fees/sizes of the transaction

Added in #19940.

**Comment by MarcoFalke** [comment]
Closing for now. Please open a new issue for anything new or forgotten.
