### ISSUE TITLE
Cross build 0.17.0rc2 for Windows on WSL fails testsuite

### ISSUE THREAD

**Issue by molxyz** [bitcoin/bitcoin#14043]
Not sure if this is important but `make check` gives me this report and tells me to report.
This was done on Windows Sub Linux system with Ubuntu 18.04.1 LTS bionic. 
The compiling was done twice and the testsuite fails both times.
Here is the result on my screen: 

============================================================================
Testsuite summary for Bitcoin Core 0.17.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
Makefile:10147: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/user/bitcoin/src'
Makefile:10253: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/user/bitcoin/src'
Makefile:10352: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/user/bitcoin/src'
Makefile:10040: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/user/bitcoin/src'
Makefile:773: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

=============================================
   Bitcoin Core 0.17.0: src/test-suite.log
=============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

./qt/test/test_bitcoin-qt.exe: Invalid argument
FAIL qt/test/test_bitcoin-qt.exe (exit status: 1)

**Comment by ken2812221** [comment]
#13207

**Comment by fanquake** [comment]
As mentioned in #13207 `make check` is not currently supported on `WSL`.

**Comment by ken2812221** [comment]
You can run test_bitcoin.exe on native Windows to check it.

**Comment by molxyz** [comment]
@ken2812221 thank you for this tip. I've tried it, seems working! Thanks again.

**Comment by varunsingal** [comment]
How

> @ken2812221 thank you for this tip. I've tried it, seems working! Thanks again.

How can you run test_bitcoin.exe on native Windows? Can we compile the bitcoin code on native windows? I am using WSL

**Comment by billygarrison** [comment]
@2w1l1ght see https://github.com/bitcoin/bitcoin/issues/14219#issuecomment-650572382

Supposedly you can [build on native Windows in Visual Studio.](https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md)
