### ISSUE TITLE
0.16.2 binary gives error after latest compiled client has run

### ISSUE THREAD

**Issue by coinsmith** [bitcoin/bitcoin#14048]
-- Describe the issue 

Ran the latest self compiled version of bitcoind on my bitcoin full node datadir. Later when running 0.16.2 precompiled binary, it gives this error
You need to rebuild the database using -reindex to change -txindex.
Please restart with -reindex or -reindex-chainstate to recover.
: You need to rebuild the database using -reindex to change -txindex.
Please restart with -reindex or -reindex-chainstate to recover.
Aborted block database rebuild. Exiting.

--- What behavior did you expect? --

Full node starting as usual

0.16.2 -> gives an error
self compiled client -> works
0.16.2 -> gives error
etc.

-- What type of machine are you observing the error on (OS/CPU and disk type)? --

Ubuntu 16.04, amd processor 

-- Any extra information that might be useful in the debugging process. --

On a side note, the self compiled client prints debug output in the terminal screen, even though I started with the command "./bitcoind &"

**Comment by ken2812221** [comment]
You can't downgrade bitcoin core.

**Comment by coinsmith** [comment]
Yup, backward compatibility is what I assumed, so good to know this issue was worth making.

**Comment by mmortal03** [comment]
Milestone on this should be updated, or was this fixed?

**Comment by coinsmith** [comment]
Not 'fixed', but the issue can be closed, I guess. Core 16.99 client db wasn't compatible with 16.3 and under when txindex=1 and vice versa. Using Core version 17 now. Thanks for the reminder.
