### ISSUE TITLE
unit tests fail --with-sanitizers=thread

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#14058]
On master and 0.17 steps to reproduce:

```sh
git checkout bitcoin/master && make distclean
./configure --with-sanitizers=thread CC=clang CXX=clang++
make -j 16 check

**Comment by skeees** [comment]
oh, i should have remembered this. the BOOST_CHECK_* are not thread safe.
If i change to asserts it resolves the issue, submitting now

**Comment by MarcoFalke** [comment]
Ah thanks.

Seems there is one warning left in the `processnewblock_signals_ordering` test. The reason for that warning is that `block.fChecked` is not atomic, so one thread could write to it while another could read from it. The primitive fix would be to make the member std::atomic.

**Comment by skeees** [comment]
This one is less simple because making that an atomic will delete the automatically generated copy constructors / assignment from CBlock - which means they'll need to be manually declared. Any thoughts?

**Comment by skeees** [comment]
I have a branch with that change here: https://github.com/bitcoin/bitcoin/compare/master...skeees:fchecked-atomic?expand=1
