### ISSUE TITLE
functional tests fail --with-sanitizers=undefined

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#14059]
Steps to reproduce on master and 0.17:

```sh
git checkout bitcoin/master && make distclean
./configure --with-sanitizers=undefined CC=clang CXX=clang++
make -j 16 check && ./test/functional/test_runner.py -j 16
```

Runs into some divide by zero and other issues...

**Comment by practicalswift** [comment]
This is addressed in the following PRs:

* #14242: Avoid triggering undefined behaviour (`std::memset(nullptr, 0, 0)`) if an invalid string is passed to `DecodeSecret(...)`
* #14239: Avoid dividing by zero (undefined behaviour) in `EstimateMedianVal` (policy)/`ConnectTip` (validation)/`CreateTransaction` (wallet)
* #13546: wallet: Avoid potential use of uninitialized value `bnb_used` in `CWallet::CreateTransaction(...)`
* #14252: build: Run functional tests and benchmarks under the undefined behaviour sanitizer (UBSan)
