### ISSUE TITLE
-debuglogfile=0 does not disable logging to a file

### ISSUE THREAD

**Issue by takinbo** [bitcoin/bitcoin#14064]
The documentation for the `-debuglogfile` option says you can disable logging to a file by setting the value to `0`; this does not appear to be the case. Instead a file named `0` is created and used as the log file.

The expectation is that when you run `bitcoind -debuglogfile=0` that no logging is made to a file.

This affects the latest version v0.17.0rc2

**Comment by MarcoFalke** [comment]
If this is documented that way, we should add a functional test case

**Comment by laanwj** [comment]
Thanks for testing this.

This means that `-nodebuglogfile` also doesn't work.
What *is* the way then to not log to a file anymore? I think this worked at some point.

**Comment by laanwj** [comment]
Yep, can reproduce this;
```bash
$ rm -rf $HOME/.bitcoin/regtest
$ src/bitcoind -regtest -debuglogfile=0
<CTRL-C>
$ stat $HOME/.bitcoin/regtest/0
  File: /home/orion/.bitcoin/regtest/0
...
```
`-nodebuglogfile`, curiously enough, does work:
```bash
$ rm -rf $HOME/.bitcoin/regtest
$ src/bitcoind -regtest -nodebuglogfile
<CTRL-C>
$ stat ~/.bitcoin/regtest/0
stat: cannot stat '/home/orion/.bitcoin/regtest/0': No such file or directory
```

**Comment by AkioNak** [comment]
I think #12713 has changed how to disable non boolean options like ```-debuglogfile```.
May be fixing the document is better.

"-nodebuglogfile" is checked by ```feature_logging.py```.
https://github.com/bitcoin/bitcoin/blob/master/test/functional/feature_logging.py#L62-L67

**Comment by laanwj** [comment]
see #14100: I think I made the documentation consistent there, getting rid of `=0` for non-boolean options even if still accepted for backwards compatibility

**Comment by laanwj** [comment]
Closing, this has been documented in #14100/#14108, which is merged and backported.
