### ISSUE TITLE
hi dear programmer

### ISSUE THREAD

**Issue by azetrom** [bitcoin/bitcoin#14067]

**Comment by azetrom** [comment]
hi dear programmer
i have some problem with my blockchain wallet then i imported it to an electrum desktop wallet for windows but in spite of seed and private key that i have, it's show my wallet is watch-only and i can't transfer any coin
i'm very confused 
i have  passphrase and private key from blockchain but my wallet still WATCH-ONLY 
WHAT can i do to remove ?

**Comment by sipa** [comment]
This is not a support channel, and certainly not for electrum or blockchain.info.
