### ISSUE TITLE
Build issue with Qt 5.2.1

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#14078]
It is no longer possible to build the GUI with Qt 5.2.1, which is on Ubuntu Trusty:
```
  CXX      qt/test/qt_test_test_bitcoin_qt-util.o
qt/test/util.cpp: In function ‘void ConfirmMessage(QString*, int)’:
qt/test/util.cpp:21:24: error: no matching function for call to ‘QTimer::singleShot(int&, FunctionCallback<ConfirmMessage(QString*, int)::__lambda0>*, void (Callback::*)())’
     }), &Callback::call);
                        ^
qt/test/util.cpp:21:24: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from qt/test/util.cpp:5:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   no known conversion for argument 3 from ‘void (Callback::*)()’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 3 provided
```
Not a high-priority issue, but I think we either need to fix this or add minimum Qt version check (to what?).

**Comment by fanquake** [comment]
From memory there is a qt5.2 workaround in the tests somewhere? However
this may be related to the recent compile time changes.

**Comment by laanwj** [comment]
I can only find that there's a qt 5.3 workaround in nested RPC tests:
```
src/qt/test/rpcnestedtests.cpp:#if QT_VERSION >= 0x050300
```

**Comment by MarcoFalke** [comment]
This is only on master (due to the change to the new connect syntax). cc @promag

**Comment by ryanofsky** [comment]
The code was only changed to use `QTimer::singleShot` for compatibility with Qt4. Since compatibility is no longer needed, probably a good way to fix the issue and simplify the code is just to revert #10098.

**Comment by promag** [comment]
I'll fix it unless someone is already on it.

**Comment by laanwj** [comment]
@ryanofsky makes sense!

@promag thanks, but I think it makes sense if I do it, as I have the trusty machine VM test with

**Comment by ryanofsky** [comment]
Probably you need to make the same change in the other places: avoid `QTimer::singleShot` by
instantiating a `QTimer` and calling `QObject::connect` on it. You could wrap this up in a convenience function if it's a repeating pattern.

Another option would be to go back to using the `SLOT` macro, but this might be less desirable long term.

**Comment by laanwj** [comment]
If this affects all uses of `singleShot`, that's quite a lot:
```
src/qt/bitcoin.cpp:        QTimer::singleShot(100, paymentServer, &PaymentServer::uiReady);
src/qt/bitcoingui.cpp:                QTimer::singleShot(0, this, &BitcoinGUI::hide);
src/qt/bitcoingui.cpp:                QTimer::singleShot(0, this, &BitcoinGUI::show);
src/qt/optionsdialog.cpp:        QTimer::singleShot(10000, this, &OptionsDialog::clearStatusLabel);
src/qt/test/util.cpp:    QTimer::singleShot(msec, makeCallback([text](Callback* callback) {
src/qt/test/wallettests.cpp:    QTimer::singleShot(0, makeCallback([text, cancel](Callback* callback) {
```

Not sure that's worth it.

Looks like the `QTimer::singleShot(int msec, const QObject *receiver, PointerToMemberFunction method)` function was introduced in Qt 5.4.

**Comment by promag** [comment]
Ref #13478.

**Comment by promag** [comment]
Since this is master only, can we bump Qt to 5.5? Trusty EOL is April 2019.

**Comment by hebasto** [comment]
Qt LTS comes with three years standard support. We could afford five years support.
Qt 5.2.1 was released on 2013-12-12.
