### ISSUE TITLE
Error in make command for WSL in windows 10

### ISSUE THREAD

**Issue by sanjays95** [bitcoin/bitcoin#14095]
I have followed the **build-windows.md** guide. 
On running the **make** command, I get the following error. **Please Help**

`root@LAPTOP-BSNAMMA4:~/bitcoin# make \n
Making all in src
make[1]: Entering directory '/root/bitcoin/src'
make[2]: Entering directory '/root/bitcoin/src'
make[3]: Entering directory '/root/bitcoin'
make[3]: Leaving directory '/root/bitcoin'
make[3]: Entering directory '/root/bitcoin/src/secp256k1'
make[3]: Leaving directory '/root/bitcoin/src/secp256k1'
  **CXX      qt/qt_libbitcoinqt_a-moc_bitcoinaddressvalidator.o
qt/moc_bitcoinaddressvalidator.cpp:21:1: error: ‘QT_WARNING_DISABLE_DEPRECATED’ does not name a type; did you mean ‘QT_WARNING_DISABLE_INTEL’?**
 QT_WARNING_DISABLE_DEPRECATED
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 QT_WARNING_DISABLE_INTEL
qt/moc_bitcoinaddressvalidator.cpp:31:14: error: ‘qt_meta_stringdata_BitcoinAddressEntryValidator_t’ does not name a type; did you mean ‘_ZTI28BitcoinAddressEntryValidator’?
 static const qt_meta_stringdata_BitcoinAddressEntryValidator_t qt_meta_stringdata_BitcoinAddressEntryValidator = {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              _ZTI28BitcoinAddressEntryValidator
qt/moc_bitcoinaddressvalidator.cpp:65:38: error: ‘qt_meta_stringdata_BitcoinAddressEntryValidator’ was not declared in this scope
     { &QValidator::staticMetaObject, qt_meta_stringdata_BitcoinAddressEntryValidator.data,
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
qt/moc_bitcoinaddressvalidator.cpp:65:38: note: suggested alternative: ‘qt_meta_data_BitcoinAddressEntryValidator’
     { &QValidator::staticMetaObject, qt_meta_stringdata_BitcoinAddressEntryValidator.data,
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      qt_meta_data_BitcoinAddressEntryValidator
qt/moc_bitcoinaddressvalidator.cpp: In member function ‘virtual void* BitcoinAddressEntryValidator::qt_metacast(const char*)’:
qt/moc_bitcoinaddressvalidator.cpp:78:26: error: ‘qt_meta_stringdata_BitcoinAddressEntryValidator’ was not declared in this scope
     if (!strcmp(_clname, qt_meta_stringdata_BitcoinAddressEntryValidator.stringdata0))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
qt/moc_bitcoinaddressvalidator.cpp:78:26: note: suggested alternative: ‘qt_meta_data_BitcoinAddressEntryValidator’
     if (!strcmp(_clname, qt_meta_stringdata_BitcoinAddressEntryValidator.stringdata0))
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          qt_meta_data_BitcoinAddressEntryValidator
**Makefile:7192: recipe for target 'qt/qt_libbitcoinqt_a-moc_bitcoinaddressvalidator.o' failed
make[2]: *** [qt/qt_libbitcoinqt_a-moc_bitcoinaddressvalidator.o] Error 1**
make[2]: Leaving directory '/root/bitcoin/src'
Makefile:9480: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/bitcoin/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@LAPTOP-BSNAMMA4:~/bitcoin#`

**Comment by greenaddress** [comment]
@sanjays95 what distro and what version of it are you using in WSL?
