### ISSUE TITLE
ibd memory usage up in 0.17

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#14109]
Just to track the memory usage issue caused by the leveldb subtree change in #13925

See also https://bitcoinperf.com/timeline/?exe=3%2C4%2C2%2C1&base=1%2B23&ben=reindex.522000.dbcache%3D2048.mem-usage&env=1&revs=50&equid=on&quarts=on&extr=on

**Comment by laanwj** [comment]
This was discussed in the meeting of 2018-08-30, 
```
21:04 < gmaxwell> I no longer think #14109 is blocking, it appears to be a measurement artifact. pages in the cache in read only mmaps show up in res.
```
so I'm untagging this from 0.17.0
