### ISSUE TITLE
scantxoutset help about descriptors refers to TODO document

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#14114]
https://github.com/bitcoin/bitcoin/blob/master/src/rpc/blockchain.cpp#L2061

Overseen in #13697.
I guess best would be to add a new document to the docs/ dir.

**Comment by jonasschnelli** [comment]
Fix is already there (sorry for the noise): #14096

**Comment by laanwj** [comment]
closed by #14096
