### ISSUE TITLE
Unbuildable on MacOS

### ISSUE THREAD

**Issue by ohhmm** [bitcoin/bitcoin#14124]
It seems unbuildable on macOS. Any plans for cmake?

**Comment by scravy** [comment]
You can build it on macOS. There are build instructions specifically for macOS in the documentation directory.

**Comment by ohhmm** [comment]
You may find useful to cmake with [cpack](https://cmake.org/cmake/help/latest/module/CPack.html) and [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html?highlight=external%20project%20add) features. CMake is downloadable for macOS as dmg. It produces Xcode native project for macOS and visual studio native project for windows. It is natively supported by kdevelop and clion. Has support of qtcreator. Has generator for eclipse cat project. Has generator of plain makefiles. Clion can create the project for you. I would like to hear forward on plans for cmake if any.

**Comment by sipa** [comment]
We're not going to maintain two build environments in parallel.

**Comment by scravy** [comment]
@sipa There are MSVC build definitions, that is: already two evironments are maintained. When adding a source file it has to be added to the Makefile.am as well as some XML file.

**Comment by MarcoFalke** [comment]
Pull request very welcome to switch to cmake.
