### ISSUE TITLE
Clean up encrypted_batch in wallet

### ISSUE THREAD

**Issue by domob1812** [bitcoin/bitcoin#14139]
For #14138 I took a look at `encrypted_batch` in the wallet code.  My understanding may be incorrect, as the code around it is undocumented and quite messy.  But as far as I understand, `CWallet::encrypted_batch` is only used in these places:

* The destructor, simply to free it.
* `AddKeyPubKeyWithDB`:  If not set initially, it is set to the passed-in reference and reset to `nullptr` before exiting the function.
* `AddCryptedKey`:  It is read if non-null, not changed.
* `EncryptWallet`:  It is expected that `encrypted_batch` is null initially.  Then it is set to a newly allocated object, used, feed and reset to `nullptr` again before exiting the function.

To me, it seems that there is no way through which `encrypted_batch` can be non-null except temporarily while executing either `AddKeyPubKeyWithDB` or `EncryptWallet`.  Thus I feel like this can be cleaned up and clarified quite a bit.  For instance:

* Make it explicit that the member variable / `CWallet` instance never owns the associated memory; it is just a simple reference passed down to `AddCryptedKey`.
* Accordingly, do not do anything about it in the destructor.
* Use a `std::unique_ptr` on the stack in `EncryptWallet` to hold the memory.

One could even go a step further and use RAII to set/restore `encrypted_batch` in both `AddKeyPubKeyWithDB` and `EncryptWallet` rather than doing it in the current "unsafe" way.

Am I missing something here, or is my understanding correct?  If it is, then I'm happy to prepare a clean up PR for this.

**Comment by domob1812** [comment]
As this is probably easier to judge based on actual code, I've implemented the proposed changes in #14144.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
