### ISSUE TITLE
abandontransaction needed after spending orphaned block reward

### ISSUE THREAD

**Issue by domob1812** [bitcoin/bitcoin#14148]
When a block reward is spent together with other outputs in the wallet and that block reward is later orphaned, the wallet does not show the other funds as available anymore.  Even a `-rescan` is not enough - only `-zapwallettxes` or an explicit `abandontransaction` "recovers" the funds.  I prepared a [test case](https://github.com/domob1812/bitcoin/blob/wallet-bug-invalidated-block-rewards/test/functional/wallet_bug.py) that shows this behaviour.

Is this a known issue or the expected behaviour?  While this situation is something that will presumably not occur in practice (as it requires a long reorg), I wonder if that transaction should be automatically abandoned as it seems clear it won't be able to be confirmed anymore.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by domob1812** [comment]
@MarcoFalke Yes, this still applies to current `master`.  I've re-created a testcase showing this behaviour:  [test.zip](https://github.com/bitcoin/bitcoin/files/4539131/test.zip)

Of course, @promag's point is valid.  Perhaps that's the expected behaviour.

**Comment by MarcoFalke** [comment]
I think this is still a bug. Maybe submit the test case as a pull request, so that this can be fixed easier?

**Comment by domob1812** [comment]
@MarcoFalke Sure, created #18795.
