### ISSUE TITLE
account system

### ISSUE THREAD

**Issue by n0n0n0n0** [bitcoin/bitcoin#14142]
In the past we had account system which allowed me to specify account which can be used to send transaction. Then it was deprecated and removed (for what?). How can i do it now?

**Comment by MarcoFalke** [comment]
The account system was confusing and easy to accidentally get wrong. Thus, it was removed in favor of more sane and flexible solutions outside of Bitcoin Core. How to implement those solutions depends on you use case and is out of scope here and best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
