### ISSUE TITLE
Hardware wallet support

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#14145]
Potential benefits of using hardware wallets in combination with Bitcoin Core:
* privacy: all or most hardware wallets rely on a backend to fetch balance and history
* less vendor-specific code to trust, including much of their dependencies (e.g. hardware wallet software often uses ElectronJS and the whole Javascript kitchen sink)
* potentially safer coin storage for Bitcoin Core users than just a `wallet.dat` file

Current easy to use alternatives:
* use the official wallet that goes with the device
* use a different wallet (e.g. Electrum)

Current advanced alternatives:
* [Electrum Personal Server](https://github.com/chris-belcher/electrum-personal-server)
* WIP by @instagibbs: https://github.com/bitcoin/bitcoin/compare/master...instagibbs:external_sign_10
* #14019, #14021, and #14075 by @achow101, guide: https://gist.github.com/achow101/a9cf757d45df56753fae9d65db4d6e1d

Probably out of scope:
* hardware drivers; i.e. there will always be some binary from manufacturer that the user needs to install and trust
* UI changes more complex than "Please approve the transaction on your device"

Potential ingredients:
* drivers:
  * https://github.com/achow101/HWI: combines various hardware drivers into a consistent API. Uses Python, perhaps rewrite in C++? Drivers from e.g. Ledger and Trezor also in Python though.
  * https://github.com/signal11/hidapi: multi-platform USB/Bluetooth driver written in C++: could perhaps be added to depends to minimize the amount of vendor-specific code users need to trust?
  * perhaps the above is too much detail, and we should just specify a list of function calls that the wallet can make to the driver?
* [BIP-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) partially signed transactions are now supported
* [output descriptors](https://github.com/bitcoin/bitcoin/pull/14096)
* [wallet flags](#9662) (e.g. watch-only)
* dynamic wallet loading and creation

Previous issues discussing this:
* #10112 (initially about Yubikey, but more broad)
* #8218 (initially about Trezor, but also more broad)

---
I imagine a UX like this:

1.  User installs hardware driver
2. User starts Bitcoin Core and inserts hardware wallet
3. Core detects this driver and checks device id against all loaded wallets
3a. If no wallet is found, add menu entry "Create wallet with device X"
3b. Core asks device for account xpub `m/49'/0'` (or whatever user enters)
3c. Derive keys (driver provides output descriptor for change and receive addresses, e.g. `/0/*` and `/1/*`)
3d. Mark wallet as watch-only and store the device id.
3e. Ask driver if this is an existing or fresh wallet, rescan if needed
4. When user makes a transaction and wallet has a device id, check with driver that device is inserted, then ask device to sign transaction

What seems to be missing is some sort of reverse-RPC, where the Bitcoin Core can take initiative, e.g. asking the device "give me an xpub", or "sign this". Perhaps drivers can symlink a standardized RPC at  `$bitcoin_datadir/hardware/device-id`?

**Comment by instagibbs** [comment]
I've been dogfooding the PRs @achow101 has mentioned along with HWI. It's a serviceable replacement for my previous pre-PSBT effort which basically does as he says, calls out to the driver for whatever reason requested: https://github.com/instagibbs/bitcoin/tree/external_sign_10 . 

My guess is any integrated version of this will have to happen post-descriptors refactor, where the wallet is more sane about what it thinks it has. For now the raw watchonly version is still viable however.

**Comment by sipa** [comment]
@sjors I'm working on adding support for importing descriptors into the wallet (which would automatically support xpubs, multisig, ...).

**Comment by jb55** [comment]
@achow101 "you can use a hardware wallet with Core via HWI" is a bit vague. Will you be able to import all of your Trezor addresses into core? That's the main use case I care about and it's not immediately clear that it's possible from those commits. 

One other commit that comes to mind is #8723

**Comment by achow101** [comment]
@Sjors @jb55 I've written up a quick guide on how you can use BItcoin Core and HWI: https://gist.github.com/achow101/a9cf757d45df56753fae9d65db4d6e1d

**Comment by jb55** [comment]
@achow101 writes:

> @Sjors @jb55 I've written up a quick guide on how you can use BItcoin Core and HWI: https://gist.github.com/achow101/a9cf757d45df56753fae9d65db4d6e1d

This is great, thanks! My intuition is that this looks to be the right
way to go about it, as all the complexity/new hw wallet support can be
handled by HWI. Looking at your docs, I imagine it wouldn't be too
difficult to put a friendly GUI around it as well.

**Comment by kewde** [comment]
I'll just drop this here. I suppose it can be a relevant resource to someone that wishes to do an implementation in bitcoin-core using hidapi.
https://github.com/particl/particl-core/tree/master/src/usbdevice

**Comment by Sjors** [comment]
I just successfully tried @achow101's [instructions](
https://gist.github.com/achow101/a9cf757d45df56753fae9d65db4d6e1d). TL&DR:
* Python script gets a bunch of addresses from the device, e.g. `m/44'/0'/0'/0/[0-99]`
* add keys to keypool using RPC; the above output is easy to copy-paste. Needs #14075 to make keypool work with watch-only wallet.
* to receive coins, no hardware wallet needed, just generate addresses (legacy, p2sh, bech32) as usual
* to send coins, generate a PSBT and pass that into the python script (needs #14021 to keep track of BIP32 paths)

Review of #14019, #14021, and #14075 would be quite helpful to move this forward.

**Comment by Sjors** [comment]
More progress: #14912

**Comment by Sjors** [comment]
I gave a presentation at Advancing Bitcoin about the latest state of this. [Video](https://vimeo.com/316634495) and [slides](https://github.com/Sjors/presentations/blob/master/2019-02-08%20London%20-%20Advancing%20Bitcoin/2019-02%20London%20Advancing%20Bitcoin.pdf).

The @achow101 created has been moved to the Bitcoin Core Github account and  should work with v0.18 once that's released. Usage is described [here](https://github.com/bitcoin-core/HWI/blob/master/docs/bitcoin-core-usage.md#setup).

I'm adding a number of RPC methods to `bitcoind` to make it easier to use the HWI library, which is work in progress in #14912 that I linked to earlier.

Work on the GUI can probably get started once create wallet functionality is added, the only thing missing from #13059. In fact, the verify address on device and sending transaction functionality can already be worked on even while wallets needs to be created with the command line.

**Comment by Sjors** [comment]
Two main blockers for are:
* #16966 `ui: make send a wizard`; this creates space in the send UI to sign on devices (or handle PSBTs directly). I plan to rebase #16549 `UI external signer support (e.g. hardware wallet)` on top of that when it's a bit more stable.
* #16528 `native descriptor wallets`: although not strictly necessary, descriptor wallets make it easier to stay interoperable with manufacturer wallets that use BIP44/49/84, and makes it easier to support multisig (e.g. BIP67, #16895)

**Comment by Sjors** [comment]
We have liftoff!
