### ISSUE TITLE
Why doesn't v0.17.0 Windows read the rcport from bitcoin.conf?

### ISSUE THREAD

**Issue by molxyz** [bitcoin/bitcoin#14229]
Hello, 

From running v0.17.0 (either by my compiled client or download from bitcoin core binaries) I've noticed that the node can't read the designated rpcport on bitcoin.conf.  This never happens with the previous versions for Windows.

Because I want to run more than one node, I need them to run on different ports, but for some reason unless I run the second node with `-rpcport=xxxxx` at the start up on commandline or put this in "target" of the shortcut, it won't take a different port than the default port. 

Is this a bug or a feature for the new version for Windows?

**Comment by ken2812221** [comment]
From the release notes at https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.17.0-Release-notes#configuration-sections-for-testnet-and-regtest, you should use either 
```
[main]
rpcport=xxx
[test]
rpcport=xxx
[regtest]
rpcport=xxx
```
or
```
main.rpcport=xxx
test.rpcport=xxx
regtest.rpcport=xxx
```

**Comment by molxyz** [comment]
@ken2812221  It works now. Thank you very much!  I wasn't aware of this change and didn't read the release notes yet. This change reminds me of the section convention in btcd, makes sense!  👍 

Devs, thanks for all your hard work. Closing this issue.
