### ISSUE TITLE
debug wih clion

### ISSUE THREAD

**Issue by crowdcoinChain** [bitcoin/bitcoin#14232]
hello,
I got this error when I have tried to compile on lubuntu 16.04

34: error: expected ‘)’ before ‘host_16bits’
 inline uint16_t htole16(uint16_t host_16bits)

using clion, is there any guide on how to debug on linux using clion?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
