### ISSUE TITLE
code : -26 message : "16: bad-txns-time-earlier-than-input"

### ISSUE THREAD

**Issue by Cleberw3b** [bitcoin/bitcoin#14246]
I'm trying to sendrawtransaction using bitcoin-cli and getting the error
```
{
  code:-26
  message:"16: bad-txns-time-earlier-than-input"
}
```

I've decoded the raw tx
```
{
  Time:0
  locktime:0
  size:123
  txid:"ede1ea3a260d4afe2c97fb6498a0a767ee37226b0c6102cc15e70c31091edf2c"
  version:1
vin:
  0:
    scriptSig:{asm: "", hex: ""}
    sequence:4294967295
    txid:"e635de09476e6f582175029d8724262628cf8ff88ceddd8b8aef66357d4e2584"
vout:
  n:0
    scriptPubKey:
      addresses:["KLMrQkb6RDs1GAwsZ3ex2VmXLkJHDjqHqK"]
      asm:"OP_DUP OP_HASH160 903f45ba31183ca199ae545dff70853d49510f25 OP_EQUALVERIFY OP_CHECKSIG"
      hex:"76a914903f45ba31183ca199ae545dff70853d49510f2588ac"
      reqSigs:1
      type:"pubkeyhash"
    value:0.4877156

  n:1
    scriptPubKey:
      addresses:["KEEGo1bkMKna3uRkLENR1QCXhdHjxD5uHP"]
      asm:"OP_DUP OP_HASH160 4cff8b65e7edda080cdf90dd6d17ae4d7e7b0690 OP_EQUALVERIFY OP_CHECKSIG"
      hex:"76a9144cff8b65e7edda080cdf90dd6d17ae4d7e7b069088ac"
      reqSigs:1
      type:"pubkeyhash"
    value:0.0001
```
The first output is the change address and the second is the address I'm willing to send bitcoins.
`hex raw tx: 01000000000000000184254e7d3566ef8a8bdded8cf88fcf28262624879d027521586f6e4709de35e60000000000ffffffff02e831e802000000001976a914903f45ba31183ca199ae545dff70853d49510f2588ac10270000000000001976a9144cff8b65e7edda080cdf90dd6d17ae4d7e7b069088ac00000000`

After I'm siggining the tx
`signed tx:
01000000000000000184254e7d3566ef8a8bdded8cf88fcf28262624879d027521586f6e4709de35e6000000006a47304402203ddd061d6508ea5ef49528ddb32246c9076687c241fad827bc917ec0a324068502200a515e89608a464172dede019c715ae27d557eacebf3abee09106b57495d41ac0121038f01d15ed873aa8a2e3ba0f88221668b195f6295a68e94fe12dd211258a790d4ffffffff02e831e802000000001976a914903f45ba31183ca199ae545dff70853d49510f2588ac10270000000000001976a9144cff8b65e7edda080cdf90dd6d17ae4d7e7b069088ac00000000`

I have no clue what is going wrong, could someone help me out?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
