### ISSUE TITLE
Can I transfer blockchain between different OS machines?

### ISSUE THREAD

**Issue by newmzy** [bitcoin/bitcoin#14274]
I am currently running Bitcoin Core 16.3 on a 64 bit Windows 10 machine.

It is running as a "full node" but limited to 64 connections.

I thought it might be fun to use a Rasberry Pi 3 that I am not otherwise using as a full node, both as a way of learning more about using the Pi and improving my Linux skills. 

The idea of downloading the nearly 200GB of blockchain to it seems like a terrible waste of bandwidth if I can use the data from the Windows machine.

If I install whatever necessary OS and wallet to the Pi, then run it once to create a new wallet, then close the wallet - will I be able to copy across the "blocks", "chainstate" & "database" folders (or just whatever folder/s are necessary, then open the wallet again and have it almost synced?

Another way to put this question: is the Bitcoin blockchain data stored differently between operating systems? I know the folder/s will be in different locations in a linux file structure but will the actual data be the same, and work between different software versions of Bitcoin Core?

I know this isn't technically an "issue" as such but more of a query, so if I am posting in the wrong place I apologise - please let me know where I should ask.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
