### ISSUE TITLE
bitcoin-qt stops while switching SSLv3 to TLS on Arch Linux

### ISSUE THREAD

**Issue by eserlxl** [bitcoin/bitcoin#14273]
After updating packages on Arch Linux ( KDE Plasma, 4.18.8-arch1-1-ARCH x86_64 GNU/Linux ), I cannot start bitcoin-qt even from a fresh installation again. No log, no error messages. Compiling from the latest source on github gives the same result.

I found the problem using `gdb -> run -> CTRL+C -> bt` sequnce and gdb points qt/bitcoin.cpp:579.

I had to disable SSLv3 -> TLS code part in order to run the bitcoin-qt wallet.

Disabled code part ( src/qt/bitcoin.cpp, line 579 )
```
    QSslConfiguration sslconf = QSslConfiguration::defaultConfiguration();
    sslconf.setProtocol(QSsl::TlsV1_0OrLater);
    QSslConfiguration::setDefaultConfiguration(sslconf);
```
I have also reported the issue to Arch Linux BBS forum and AUR page of bitcoin-git package.

Do I need to set up a TLS configuration on Arch Linux? Thanks for your help.

**Comment by MarcoFalke** [comment]
I believe this is an upstream qt bug. You can work around by building from depends.

**Comment by yzhou61** [comment]
@MarcoFalke is there an upstream issue that you could link to? Thanks!

**Comment by eserlxl** [comment]
I found an interesting fix for this issue. An unnecessary SSL library version check allows bitcoin-qt to run again on Arch Linux without disabling switching SSLv3 to TLS. QSslSocket::sslLibraryVersionString() returns an empty string for me.
```
    QSslSocket::sslLibraryVersionString(); // An unnecessary check to solve issue #14273: bitcoin-qt stops while switching SSLv3 to TLS on Arch Linux
    Q_ASSERT( QSslSocket::supportsSsl() );

    QSslConfiguration sslconf = QSslConfiguration::defaultConfiguration();
    sslconf.setProtocol(QSsl::TlsV1_0OrLater);
    QSslConfiguration::setDefaultConfiguration(sslconf);

    Q_ASSERT(QSslConfiguration::defaultConfiguration().protocol() == QSsl::TlsV1_0OrLater);
```
Of course, Q_ASSERT's are not necessary :)

**Comment by yzhou61** [comment]
@eserlxl is this fixed somewhere?

**Comment by eserlxl** [comment]
I couldn't decide to close the issue or keep it as open. Applying a simple patch solves the issue as I mentioned.
Patch to bitcoin/src/qt/bitcoin.cpp at line 579
QSslSocket::sslLibraryVersionString(); // An unnecessary check to solve issue #14273: bitcoin-qt stops while switching SSLv3 to TLS on Arch LinuxI've already posted the bug to Arch Linux official forum. Today, I will post to Arch Linux bug page.
I don't think that this bug is directly related to bitcoin source.

    28 Eylül 2018 Cuma 18:37:21 GMT+3 tarihinde, Joe (Yu) Zhou <notifications@github.com>şunu yazdı:  
 
 
@eserlxl is this fixed somewhere?

**Comment by yzhou61** [comment]
Ok thanks. Here's the forum link: https://bbs.archlinux.org/viewtopic.php?id=240553
