### ISSUE TITLE
Missing RPCAuth script in tarball

### ISSUE THREAD

**Issue by bitstein** [bitcoin/bitcoin#14292]
When running Bitcoin installed from a binary, the `RPCAuth` script found at `share/rpcauth/rpcauth.py` is inaccessible to the user without cloning from the repo, despite being referenced in `bitcoind -help`:

```
RPC server options:
[...]
  -rpcauth=<userpw>
       Username and hashed password for JSON-RPC connections. The field
       <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A
       canonical python script is included in share/rpcuser. The client
       then connects normally using the
       rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This
       option can be specified multiple times
```

v0.16.3, via tarball

Ubuntu 18.04.1 LTS

This could be resolved by including the script in the tarball's `share` directory, so that is accessible to users. Being a small script, this would not require much overhead. Alternatively, another method could be given to allow the user to generate salted password hashes, perhaps as a command line executable.

cc @harding

**Comment by MarcoFalke** [comment]
This is fixed

**Comment by harding** [comment]
@MarcoFalke do you know which commit fixed this?  The file isn't in the 0.20 RC tarballs and I also don't see it in the guix tarballs produced by drahtbot that involve merging with master, e.g. https://drahtbot.space/gitian/bitcoin/bitcoin/798774a521fdf73c873d4a6ece69dd38b4977a20/bitcoin-798774a521fd-x86_64-linux-gnu.tar.gz from PR 18820.

**Comment by MarcoFalke** [comment]
@harding What are the exact steps to reproduce. It works for me:

```
$ wget https://bitcoincore.org/bin/bitcoin-core-0.19.1/bitcoin-0.19.1.tar.gz
$ tar -xvf bitcoin-0.19.1.tar.gz 
$ ls bitcoin-0.19.1/share/rpcauth/rpcauth.py 
bitcoin-0.19.1/share/rpcauth/rpcauth.py

$ wget https://bitcoincore.org/bin/bitcoin-core-0.20.0/test.rc2/bitcoin-0.20.0rc2.tar.gz
$ tar -xvf bitcoin-0.20.0rc2.tar.gz 
$ ls bitcoin-0.20.0rc2/share/rpcauth/rpcauth.py 
bitcoin-0.20.0rc2/share/rpcauth/rpcauth.py

**Comment by MarcoFalke** [comment]
The commit that fixed it 6674a75bfbdf680d0a3648f44c6591ff5fc983cf

**Comment by harding** [comment]
@MarcoFalke 

I think you're downloading the source archive.  I think this issue is about the binary distribution.  Steps to reproduce:

    $ wget https://drahtbot.space/gitian/bitcoin/bitcoin/798774a521fdf73c873d4a6ece69dd38b4977a20/bitcoin-798774a521fd-x86_64-linux-gnu.tar.gz
    $ tar tzf bitcoin-798774a521fd-x86_64-linux-gnu.tar.gz | grep -i rpcauth || echo NOT FOUND
    NOT FOUND

**Comment by MarcoFalke** [comment]
It might be best to file a new issue for the missing script in the binary tarball. I always assumed this issue is about the source tarball.

**Comment by harding** [comment]
Ok, I'll open a new issue.
