### ISSUE TITLE
Deprecate wallet `generate` RPC method

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#14299]
The `generate` RPC method:
- was introduced in 2010
- is now only used for testing
- reaches across multiple components (wallet, mining)

I propose we remove the wallet `generate` RPC method and update all tests to use the `generatetoaddress` RPC method. We can do this non-invasively in the test framework by adding a `generate` method to `TestNode` so that the individual tests do not need to be updated. We could also add a `generate` alias to the `generatetoaddress` RPC method.

Doing this removes a wallet->server dependency and simplifies the wallet->server interface (#10973).

I'm opening this issue before implementing in case anyone has objections.

**Comment by sipa** [comment]
Sounds great to me.

**Comment by promag** [comment]
ACK. Deprecate in 0.18, remove in 0.19?

**Comment by MarcoFalke** [comment]
> We can do this non-invasively in the test framework by adding a generate method to TestNode so that the individual tests do not need to be updated.

I have no objections when done this way.

**Comment by jnewbery** [comment]
Thanks for the input!

@laanwj - any thoughts on this? I suppose some people use `generate` for manual testing, but that can easily be replaced by something like `bitcoin-cli generatetoaddress 1 $(bitcoin-cli getnewaddress)`

**Comment by laanwj** [comment]
if the existence of the method is a problem architecturally I'm not opposed to removing it, it's "only" a testing method so it should affect less users than the other deprecations

**Comment by laanwj** [comment]
nah, if you're going to change the API anyway, might as well really deprecate it, adding an alias to a different command probably just adds confusion

the workaround is good enough:
```
bitcoin-cli generatetoaddress 1 $(bitcoin-cli getnewaddress)
```

**Comment by laanwj** [comment]
> was introduced in 2010

FYI (not a comment on this issue), `generate` was introduced in 2015 in #5957, not in 2010. Before that time there were `setgenerate` and friends
