### ISSUE TITLE
[GUI]: Mac does not show sent / receive notifications

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#14301]
Describe the issue:

If coins are being send with the mac bitcoin-qt 0.16.3, there is no notification that notifies if a transaction was received or sent.

What behavior did you expect?

A notification like the windows GUI / Linux  GUI shows, when sending/receiving coins.

What was the actual behavior (provide screenshots if the issue is GUI-related)

Told above.

How reliably can you reproduce the issue, what are the steps to do so?

Just start the wallet on a macosx and try to send or receive coins.

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)? 

Bitcoin Website, 0.16.3

What type of machine are you observing the error on (OS/CPU and disk type)? 

Mac OS, I think High Sierra

**Comment by Sjors** [comment]
@globaltoken you can find your macOS version by clicking on the Apple icon on the top right and then the first item (About this Mac).
