### ISSUE TITLE
-reindex flag immediately screws up database

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#14313]
After upgrading and reindexing, I goofed up and hit the 'bitcoind -reindex' command again when it was just done reindexing. So, I could wait another full day for it to finish. Perhaps it's an idea to put a safety in, when starting bitcoind or bitcoin-qt with the -reindex flag, that it first asks if you want to reindex. 

If this is too much of a nitwit safety, this issue can be closed.

**Comment by livestradamus** [comment]
A confirmation dialogue of (y/N) is perhaps reasonable, considering we're about to index hundreds of GBs.
On the flip-side, we should be reading very carefully every command we're about to send.

**Comment by coinsmith** [comment]
Agree, we should take care what commands we use. I've been working with bitcoind for years now, these are errors that slip in when arrowing up a previous command (because you don't want to type out the whole alternate datadir, for instance)
Anyway, I'd applaud it, would be quite user friendly.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
