### ISSUE TITLE
macOS Mojave QT 5.11 compilation fails

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#14327]
It's that time of the year again...

Getting a bunch of compilation errors like this:

<img width="925" alt="schermafbeelding 2018-09-26 om 14 22 53" src="https://user-images.githubusercontent.com/10217/46079571-c8ed0880-c197-11e8-9def-75d7a3de17d4.png">

* `error: expected function body after function declarator inline uint qHash(const QPersistentModelIndex &index, uint seed) Q_DECL_NOTHROW`
* `qabstractitemmodel.h:211:5: error: function-like macro 'QT_DEPRECATED_SINCE' is not defined`

Seen on master @ 4dac24db23. macOS 10.14, QT 5.11.1 via Homebrew. Upgrading from 5.11.1 to 5.11.2 with `brew upgrade qt` doesn't help.

Building depends also fails. I haven't tried using cross-compiled depends.

The signed gitian binary for v0.17.0rc4 does work and I'm not seeing strange behaviour.

Suggest adding to 0.17 milestone. Imo either `depends` or regular Homebrew version should work, though not necessarily both.

**Comment by fanquake** [comment]
Some info here on Qt & 10.14 https://bugreports.qt.io/browse/QTBUG-68891. Hopefully there are just a couple patches we can add to `depends`.

**Comment by Sjors** [comment]
The above was on my iMac. I also tried, after `make distclean`, on my Macbook and there everything is happy. Same macOS and QT version, same commit.

Depends is throwing errors though, even though I did the usual #1360 gotcha dance.

```
In file included from libs/thread/src/pthread/thread.cpp:9:
In file included from ./boost/thread/detail/config.hpp:11:
In file included from ./boost/config.hpp:57:
In file included from ./boost/config/platform/macos.hpp:28:
./boost/config/posix_features.hpp:18:15: fatal error: 'unistd.h' file not found
#     include <unistd.h>
              ^~~~~~~~~~
```

Anyone else (not) having this problem?

**Comment by fanquake** [comment]
@Sjors If you install the system headers to `/usr/include` using this script `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`, `depends` compilation should start working again. 

See the `Command Line Tools` section of the Xcode 10 release notes - https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes - for why this is now required.

We'll have to address in the future (not right now, given that the workaround is still available), but I don't think should block 0.17 cc @theuni

**Comment by jonasschnelli** [comment]
I compiled master on a fresh macOS 10.14 (Mojave) installation two days ago. Followed the OSX compile guide. I only had to compile bdb4.8 on my own (homebews Berkeleydb-4,8 package did not compile).

Build was with Qt5.11.
Worked all fine.

I haven't tested depends (only using the depends compile system on linux).

**Comment by Sjors** [comment]
@fanquake thanks, that worked, depends works for me now.

QT also builds normally on my iMac now, so the bug was either because I forgot `xcode-install --select`, or because of what was installed by `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

@jonasschnelli I still had my existing `berkeley-db@4` package which seemed to work.  When I `brew uninstall` and then `brew install` it, compilation indeed fails. I installed the more recent bdb instead. Oddly enough the ./configure summary still shows `-I/usr/local/Cellar/berkeley-db@4/4.8.30/include` under `CPPFLAGS` even though that directory doesn't exist. 

I think we agreed during the IRC meeting yesterday this isn't 0.17.0 release blocking.

**Comment by DesWurstes** [comment]
Hi, I have opened a pull request at Homebrew about it. Testing with `brew install --build-from-source <formula>` is appreciated.

Otherwise, homebrew's broken berkeley-db@4 can be built using
```
export HOMEBREW_CC=gcc-8
brew install berkeley-db@4
```

**Comment by Sjors** [comment]
@DesWurstes thanks! `berkeley-db@4` works for me now.

**Comment by theuni** [comment]
Hmm, there should be no need to use ```/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg```, anything that fixes is likely a bug, especially in a depends build. Let's hold off on recommending that for now.

Sounds like we may need to teach depends how to find sdk paths on native MacOS.

**Comment by fanquake** [comment]
Going to close this now, as compiling works fine. I'm going to roll a bunch of the outstanding macOS SDK type problems into a single issue, so we can get on top of any outstanding problems.

**Comment by Sjors** [comment]
Fwiw I had to use the macOS_SDK_headers_for_macOS workaround again today to get depends build working.
