### ISSUE TITLE
bitcoind abort unexpectedly

### ISSUE THREAD

**Issue by lzl124631x** [bitcoin/bitcoin#14345]
```
[ec2-user@ip... ~]$ bitcoind
terminate called without an active exception
Aborted
```

```
[ec2-user@ip... ~]$ bitcoind -version
Bitcoin Core Daemon version v0.16.2
Copyright (C) 2009-2018 The Bitcoin Core developers

Please contribute if you find Bitcoin Core useful. Visit
<https://bitcoincore.org> for further information about the software.
The source code is available from <https://github.com/bitcoin/bitcoin>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard.
```

**Comment by fanquake** [comment]
Please provide a `debug.log` as well as:
> How reliably can you reproduce the issue, what are the steps to do so?
> What type of machine are you observing the error on (OS/CPU and disk type)?

**Comment by lzl124631x** [comment]
[debug.log](https://github.com/bitcoin/bitcoin/files/2430328/debug.log)

> How reliably can you reproduce the issue, what are the steps to do so?
Frequently. I left the daemon running for a while, later `screen -r` back, I see
![image](https://user-images.githubusercontent.com/5824517/46241683-49676100-c372-11e8-9bb0-7799021b5ed2.png)

> What type of machine are you observing the error on (OS/CPU and disk type)?
```
[ec2-user@ip-172-31-23-227 ~]$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:            2
CPU MHz:             2400.261
BogoMIPS:            4800.08
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            30720K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

**Comment by lzl124631x** [comment]
Oh. I see this issue.

```
2018-09-29 06:14:47 UpdateTip: new best=0000000000000011281e473dc5da50b772eb972c689741a99c576eaeaac7895d height=261460 version=0x00000002 log2_work=72.423216 tx=24818113 date='2013-10-03 11:25:13' progress=0.067093 cache=565.3MiB(4355665txo)
2018-09-29 06:14:47 UpdateTip: new best=000000000000001a849f50c9ac539d295071deaf6d6e24b6e8d1c7856c4fdb0f height=261461 version=0x00000002 log2_work=72.423361 tx=24818228 date='2013-10-03 11:26:34' progress=0.067093 cache=565.3MiB(4355673txo)
2018-09-29 06:14:47 Error: Out of memory. Terminating.
```

**Comment by hairetikos** [comment]
> Oh. I see this issue.
> 
> ```
> 2018-09-29 06:14:47 UpdateTip: new best=0000000000000011281e473dc5da50b772eb972c689741a99c576eaeaac7895d height=261460 version=0x00000002 log2_work=72.423216 tx=24818113 date='2013-10-03 11:25:13' progress=0.067093 cache=565.3MiB(4355665txo)
> 2018-09-29 06:14:47 UpdateTip: new best=000000000000001a849f50c9ac539d295071deaf6d6e24b6e8d1c7856c4fdb0f height=261461 version=0x00000002 log2_work=72.423361 tx=24818228 date='2013-10-03 11:26:34' progress=0.067093 cache=565.3MiB(4355673txo)
> 2018-09-29 06:14:47 Error: Out of memory. Terminating.
> ```
> 
> So `btcd` will increase mem usage as time goes on?
> 
> ```
> [ec2-user@ip-172-31-23-227 ~]$ free -m
>               total        used        free      shared  buff/cache   available
> Mem:            987          46         823           0         117         805
> Swap:             0           0           0
> ```
> 
> After I start `bitcoind` for a while
> 
> ```
> [ec2-user@ip-172-31-23-227 ~]$ free -m
>               total        used        free      shared  buff/cache   available
> Mem:            987         375          63           0         548         463
> Swap:             0           0           0
> ```
> 
> Later
> 
> ```
> [ec2-user@ip-172-31-23-227 ~]$ free -m
>               total        used        free      shared  buff/cache   available
> Mem:            987         860          60           0          66          16
> Swap:             0           0           0
> ```
> 
> Should I simply change to a VM with bigger memory? Is there a cap for the mem usage?

have you tried reducing the `dbcache` option?  try 128 or 256

**Comment by lzl124631x** [comment]
Sorry I updated my EC2 instance and didn't try that parameter.
