### ISSUE TITLE
-blocksdir not working with 0.17

### ISSUE THREAD

**Issue by sangaman** [bitcoin/bitcoin#14351]
I was trying to test the new `blocksdir` option from #12653 but could not get it to work regardless of whether I set it in the config file or passed `-blocksdir` as an argument. `blocksdir` shows up in `bitcoind --help` so it should be working, but every time I tried the opening log output would show LevelDB loading from the default `~/.bitcoin/blocks` dir where there were no blocks, and then error out immediately.

I'm using a symlinked directory currently instead and that works, fwiw.

This is on Ubuntu 18.04, compiled from 0.17.0-rc4 on an Odroid-HC2 32 bit arm device. The setup I'm using has the main `.bitcoin` datadir on an SSD and the `blocks` directory on an HDD.

**Comment by Sjors** [comment]
The `.dat` files should be in `blocksdir`, but the index is still in `~/.bitcoin/blocks/index`.

**Comment by sangaman** [comment]
Oh thank you very much. I was not aware, I will give that a shot.

**Comment by sangaman** [comment]
That did work indeed work. For the record the resulting structure is:

`<datadir>/blocks/index` <-- Where all `.ldb` files go
`<blocksdir>/blocks` <-- Where all `blk*.dat` files go

I'll see if I can help document this more clearly.
