### ISSUE TITLE
Latest release on github is v0.14.3 instead of v0.16.3

### ISSUE THREAD

**Issue by gituser** [bitcoin/bitcoin#14366]
Hi, just noticed you've marked `v0.14.3` instead of `v0.16.3` as the latest release here: https://github.com/bitcoin/bitcoin/releases

Can you fix this?

Thanks.

**Comment by fanquake** [comment]
@gituser `0.14.3` is just the latest release for the [0.14 branch](https://github.com/bitcoin/bitcoin/tree/0.14).

**Comment by MarcoFalke** [comment]
GitHub uses the timestamp of the tag to determine the latest release, which makes no sense on releases from multiple branches, or the semver versioning system. You'd have to contact GitHub support about that issue.
