### ISSUE TITLE
Backup wallet.dat

### ISSUE THREAD

**Issue by aanwhs** [bitcoin/bitcoin#14362]
Hello.
Because I changed the device.
I backup wallet.dat but I don't know how to use it on another device.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
