### ISSUE TITLE
Label support seems insufficient to replace accounts

### ISSUE THREAD

**Issue by Saicere** [bitcoin/bitcoin#14382]
While most of the additional functionality the old account system had over the label system were irrelevant, there is one critical functionality that no longer seems to be possible with labels - specifically, the ability to request a list of transactions (TXID + amount) that pay to addresses with a given account/label. As per the release notes for 0.17.0. the _listtransaction_ method was changed as follows;

> The account named parameter has been renamed to dummy. If provided, the dummy parameter must be set to the string *, unless running with the -deprecatedrpc=accounts argument (in which case functionality is unchanged).

_getreceivedbylabel_ and _getreceivedbyaddress_ only returns the balance, while _listreceivedbylabel_ and _listreceivedbyaddress_ do not actually filter; additionally, the former does not list transactions at all, while the latter does not include the amounts per TXID. While you could use _getaddressesbylabel_ to iterate over addresses, there is no corresponding method to get the TXIDs and amounts from this list of addresses. None of these can therefore be used as a direct replacement for this method.

The only way I can see to get anything resembling the old functionality with the API changes is to dump the entire transaction history with _listreceivedbyaddress_, filter the result by label manually, then use _gettransaction_ on each listed TXID. This is both very fiddly and very inefficient, and likely impossible when you go past a certain number of lifetime transactions.

Am I missing something here, or will it really no longer possible be to iterate over transactions received by account/label? If so, this basically means that many applications will no longer be usable with releases starting from Bitcoin Core 0.18.

**Comment by kristapsk** [comment]
It looks to me JoinMarket's current codebase also have this issue, see https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/185.

**Comment by ryanofsky** [comment]
If we replace the `listtransactions` `dummy` argument (formerly `account`) with a working `label` argument, would that fix the problem? I think this would be easy to implement, with the caveat that unlike the previous  `account` argument which matched both incoming and outgoing transactions, this would only be able to return incoming transactions, since the wallet no longer tries to associate outgoing transactions with accounts.

**Comment by Saicere** [comment]
> If we replace the `listtransactions` `dummy` argument (formerly `account`) with a working `label` argument, would that fix the problem?

That is correct. My use case (which I assume is not an uncommon one) is simply to assign one or more addresses to a user by means of a unique account/label, and then query for incoming transactions to that user on certain events. As long as `listtransactions` can still be used for this, everything else is a trivial update.

Thanks for looking into this.

**Comment by jnewbery** [comment]
Thanks for reporting this @Saicere!
