### ISSUE TITLE
RPC unified format proposal

### ISSUE THREAD

**Issue by karel-3d** [bitcoin/bitcoin#14399]
I have played with the RPC documents and I found out that while the format looks crazy, with some changes, it can be made easily parseable and I actually wrote a parser for that.

I have wrote a proposal for a unified format, that requires minimal changes to the current docs (mostly whitespace), and a parser in go

The proposal is here

https://gist.github.com/karel-3d/1490786786525b0365ea8f459a9fc683

The parser in go is here

https://github.com/karel-3d/bitcoincore.org/blob/formatted_doc/contrib/doc-gen/convert.go

(I found off-by-one error; the first example always has a description "Examples:", please ignore that)

The changes needed in bitcoin core are here

https://github.com/karel-3d/bitcoin/commit/45d2c866b536b30b09b658d8b954c4a7bc820405

And the result is generated here

https://bitcoin-rpc.github.io/en/doc/0.17.99/rpc/wallet/sendmany/ (the repo here https://github.com/bitcoin-rpc/bitcoin-rpc.github.io but it's just the _site from the jekyll)

I want to first hear some general notes before posting a PR.

**Comment by karel-3d** [comment]
It's not easy to write an actual linter on this though.

For example, if the type / description is not separated by two spaces properly, then the whole line is interpreted as pseudocode. But that's still legal.

I can maybe add rule that the pseudocode can't be too long?

**Comment by karel-3d** [comment]
This is when I export it to JSON, not to jekyll templates (slight change in code)

https://gist.github.com/karel-3d/02f8143b8fd463f8fd2b74a9044614c1

**Comment by ch4ot1c** [comment]
- Typo: https://github.com/karel-3d/bitcoin/commit/45d2c866b536b30b09b658d8b954c4a7bc820405#diff-a0c8f511d90e83aa9b5857e819ced344R2044

- We should try eliminate the multi-space tabs in the json. Although I do like your solution for simplicity.
- I dislike the difference in Numeric/Bool and String types' "example" formatting: https://gist.github.com/karel-3d/02f8143b8fd463f8fd2b74a9044614c1#file-rpc-json-L73 ; I wish we could make them all without quotes, and alert the user to use quotes for Strings externally. Maybe the pseudocode portion could be an external file/module, linked by rpc name.

Nice work!

**Comment by karel-3d** [comment]
Closing this, better way is to do similar to this PR instead

https://github.com/bitcoin/bitcoin/pull/14530
