### ISSUE TITLE
Not valid signature with rpc call "signtransaction" for P2SH

### ISSUE THREAD

**Issue by IhorSavva** [bitcoin/bitcoin#14392]
I have a P2SH 2/2 address. When I create a transaction hex and sign it with two keys using "signrawtransactions" and when I send it with "sendrawtransaciton", I get the error "Signature must be zero for failed CHECK (MULTI) SIG operation". But, when I sign the same hex, the same keys - the transaction is completely valid, and it goes into the block

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
