### ISSUE TITLE
Sync speed very slow!

### ISSUE THREAD

**Issue by hungdung1326** [bitcoin/bitcoin#14406]
please help me... 
i using RPC getinfo and response is: 
{
"version": 130200,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 236506,
  "timeoffset": 1,
  "connections": 20,
  "proxy": "",
  "difficulty": 11187257.46136079,
  "testnet": false,
  "keypoololdest": 1536910386,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
the connections to node of mine are 20 but sync speed is very slow.. Could anyone help me please... thank you so much!!

**Comment by jonasschnelli** [comment]
Can you specify "very slow"?
Syncing the whole chain does mostly depends on your CPU and disk performance. The amount of connected peers plays a rather unimportant role (as long as there is a handful of peers).

On an average consumer PC, a full sync can take one or two days.

**Comment by msgilligan** [comment]
I recommend closing this issue as the author is cross-posting into multiple projects: https://github.com/OmniLayer/OmniJ/issues/155
