### ISSUE TITLE
Error with set up WSL in bitcoin core (Windows)

### ISSUE THREAD

**Issue by bunnguyen2410** [bitcoin/bitcoin#14408]
I do all step, download ubuntu from Windows store (i can't see the path of the download) 
when everything is done, i do those steps:
On the cmd of windows, i type Ubuntu1804,and it change to WSL
sudo apt update
sudo apt upgrade
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
sudo apt install g++-mingw-w64-x86-64
sudo update-alternatives --config x86_64-w64-mingw32-g++
At this point the guide says, "Note that for WSL the Bitcoin Core source path MUST be somewhere in the default mount file system, for example /usr/src/bitcoin, AND not under /mnt/d/. If this is not the case the dependency autoconf scripts will fail. This means you cannot use a directory that located directly on the host Windows file system to perform the build."(i'm not sure about this caution, but try to do it just like the issue #14280 )
So, from the terminal above, i do:
cd /usr/src
sudo git clone https://github.com/bitcoin/bitcoin.git
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var
cd depends
but then, it said :"
     -bash : cd :depends:No such file or directory
"(image below)

I'm so new to this, I need the construction to be specific , I'll appreciate that

**Comment by e-nexus** [comment]
After you clone the repo you need to 'cd bitcoin'.
No need to use sudo when you clone also. 
The rest of the guide works fine.

**Comment by bunnguyen2410** [comment]
thank you so so much, i've fix it successfully
