### ISSUE TITLE
Crash in fundrawtransaction in conjunction with watchonly scripts

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#14401]
Steps to reproduce:

* Create a wallet with privatekeys disabled (`createwallet dummy true`) [optional]
* import a P2SH scriptPubKey (`importmulti ...`)
* send some fund (via another wallet) to that P2SH address
* The watch only wallet should show the balance
* Use `fundrawtransaction` with the watch-only wallet ... example: `fundrawtransaction 020000000001605af4050000000017a914396544b6e06f30ea066a7a74a04210804992a2358700000000 '{"includeWatching": true, "changeAddress": "2MxUhpUHCATayFKtLhV3qxJBKj8f5Yyeios"}'`

Crash `Assertion failed: (nBytes_ <= uint64_t(std::numeric_limits<int64_t>::max())), function GetFee, file policy/feerate.cpp, line 25.`

**Comment by practicalswift** [comment]
Some context: https://github.com/bitcoin/bitcoin/pull/14380#issuecomment-426953724 :-)

**Comment by MarcoFalke** [comment]
Let me know if this issue still persists
