### ISSUE TITLE
fundrawtransaction fails with P2SH(P2WPKH) or P2WPKH watchonly inputs 

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#14405]
AFAIK `P2WPKH` does only support compressed keys and should therefor be solvable without knowing the pubkey.

Steps to reproduce
* pay something with a loaded wallet to `bcrt1qlqx4gx4qftlfe94n48ttchsptxqwt7je7tddna`
* `createwallet test true`
* `importmulti '[{"scriptPubKey": "0014f80d541aa04afe9c96b3a9d6bc5e015980e5fa59", "timestamp": "now", "watchonly": true}]' '{"rescan": true}'` (0014f80d541aa04afe9c96b3a9d6bc5e015980e5fa59 is the scriptPubKey of bcrt1qlqx4gx4qftlfe94n48ttchsptxqwt7je7tddna)
* `fundrawtransaction 020000000001c09ee6050000000017a91446d96e0da5bcac1802f33d255c8e67dba29364bd8700000000 '{"includeWatching": true, "changeAddress": "mhb6ZbSC5gtjfgxMQEARF1fG1RdS2woNWu"}'` **fails**

**Comment by MarcoFalke** [comment]
This has been fixed in 79aeed8e76e8bc70722e6178678b0b3840694d5c?
