### ISSUE TITLE
Can't upgrade wallet with 0.17.0's new -upgradewallet feature

### ISSUE THREAD

**Issue by redblade7** [bitcoin/bitcoin#14422]
When using the new Bitcoin Core v0.17.0, and trying to pass -upgradewallet to upgrade to HD, results in an error.

* Bitcoin-Qt shows a popup box entitled "Runaway exception" with "A fatal error occurred. Bitcoin can no longer continue safely and will quit." Terminal output shows:

> ************************
> EXCEPTION: St13runtime_error       
> DeriveNewSeed: AddKeyPubKey failed       
> bitcoin in Runaway exception
> 
> bitcoin-qt: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:116: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
> Aborted

When attempting to do so via bitcoind -upgradewallet, the following is displayed before a shutdown:

> 2018-10-07T05:24:05Z [default wallet] nFileVersion = 170000
> 2018-10-07T05:24:05Z [default wallet] Keys: 0 plaintext, 1158 encrypted, 1158 w/ metadata, 1158 total. Unknown wallet records: 2
> 2018-10-07T05:24:06Z [default wallet] Performing wallet upgrade to 169900
> 2018-10-07T05:24:06Z [default wallet] Upgrading wallet to HD
> 2018-10-07T05:24:06Z [default wallet] Releasing wallet
> 2018-10-07T05:24:06Z 
> 
> ************************
> EXCEPTION: St13runtime_error       
> DeriveNewSeed: AddKeyPubKey failed       
> bitcoin in AppInit()       
> 
> 
> 
> ************************
> EXCEPTION: St13runtime_error       
> DeriveNewSeed: AddKeyPubKey failed       
> bitcoin in AppInit()       
> 
> 2018-10-07T05:24:06Z Shutdown: In progress...
> 2018-10-07T05:24:06Z scheduler thread interrupt
> 2018-10-07T05:24:06Z Shutdown: done

The wallet is shown correctly, and with the correct balance, if I run it without -upgradewallet

**Comment by ryanofsky** [comment]
Is the wallet encrypted? Looking at wallet code, it seems like AddKeyPubKey fails when wallet is encrypted and locked, but generally succeeds otherwise.

**Comment by redblade7** [comment]
Yes, the wallet is encrypted.

**Comment by talisein** [comment]
0.18.0 still crashing

**Comment by codewiz** [comment]
Are there any known workarounds for this?

I thought of decrypting the wallet temporarily, but both the GUI and the console disallow empty passwords.

**Comment by ppppso** [comment]
Still crashing on 0.19.0.1

**Comment by MarcoFalke** [comment]
Is this still an issue after #15761 ?

**Comment by codewiz** [comment]
It seems #15761 was not merged in time for v0.20 :-(
When is the 0.21 release planned for?

**Comment by MarcoFalke** [comment]
#18947

**Comment by codewiz** [comment]
I built bitcoin-qt from source (master branch), and I was able to update a pre-0.17 encrypted wallet.
Thank you for doing this work, @achow101 .

**Comment by ryanofsky** [comment]
Not sure if we ever found out what underlying bug was, but if https://github.com/bitcoin/bitcoin/issues/14422#issuecomment-643815488 is an indication, it seems like it may be fixed.

Will close this bug report, but if anyone is still having an issue upgrading, feel to reopen and post here so we can try to debug. Maybe we can post a gitian build to make the new upgrade RPC easier to test.

**Comment by mattpopovich** [comment]
All, excuse my ignorance as I've only used the GUI client previously.
@codewiz, what was the process you used to upgrade your pre-0.17 encrypted wallet? Did #15761 get included in v0.20.1rc1? Or do I need to build from master? If I do build from master, it seems as if `-upgradewallet` startup option [has been removed](https://github.com/bitcoin/bitcoin/issues/13044#issuecomment-619197849). So now would I use `upgradewallet` via `bitcoin-cli`? 

I just built v0.20.1rc1 from source and am still receiving `Error: DeriveNewSeed: AddKeyPubKey failed` when I try to use the `-upgradewallet` startup option. I get a "Method not found" when I try to run `bitcoin-cli upgradewallet`. 

I will try to build from master in the next day or two and report back.

**Comment by mattpopovich** [comment]
> All, excuse my ignorance as I've only used the GUI client previously.
> @codewiz, what was the process you used to upgrade your pre-0.17 encrypted wallet? Did #15761 get included in v0.20.1rc1? Or do I need to build from master? If I do build from master, it seems as if `-upgradewallet` startup option [has been removed](https://github.com/bitcoin/bitcoin/issues/13044#issuecomment-619197849). So now would I use `upgradewallet` via `bitcoin-cli`?
> 
> I just built v0.20.1rc1 from source and am still receiving `Error: DeriveNewSeed: AddKeyPubKey failed` when I try to use the `-upgradewallet` startup option. I get a "Method not found" when I try to run `bitcoin-cli upgradewallet`.
> 
> I will try to build from master in the next day or two and report back.

I have rebuilt from master (v0.20.99.0-ccef10261) and can confirm that the `upgradewallet` RPC works successfully on my wallet. Thanks for the development @achow101.
FWIW: My wallet was created around v0.11.1 and encrypted some time after that, ~v0.15.0 or so.

**Comment by MarcoFalke** [comment]
fyi, rc2 is now available (if you test, please test with caution, as this is not a final release)

* https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2020-November/000094.html
