### ISSUE TITLE
Cannot find the "bitcoind" to execute or chmod 

### ISSUE THREAD

**Issue by bunnguyen2410** [bitcoin/bitcoin#14423]
I've already install followed by the instruction 
Then the book says: "Run bitcoind by typing bitcoind to the terminal"
But the problem is, I cannot find where the "bitcoind" stored, i've try to cd src, and find something like "bitcoind.exe" ,"bitcoind.cpp"......
But when I run "bitcoind.exe", the terminal says an error: "Invalid argument"
So how can i find the "real bitcoind" that mentioned by the instruction, how to execute it ?
Another problem : when i run make check, these errors appear
![image](https://user-images.githubusercontent.com/30051202/46579006-31f43c00-ca34-11e8-8188-69dd3854a4df.png)
HOW TO FIX IT :( :(, help me please

**Comment by bunnguyen2410** [comment]
I think that i misunderstood, can you tell me how to find and run the "bitcoind" specifically, the book said:
![image](https://user-images.githubusercontent.com/30051202/46591149-f4022100-cae2-11e8-97fc-ec40d4fc902b.png)
and How to fix the FAIL when i run make check, thank you so much

**Comment by e-nexus** [comment]
bitcoind.exe is the command line only version which is in bitcoin/src.
You probably want the gui wallet, bitcoin-qt.exe which is in bitcoin/src/qt.
After you run make there's no need for other commands in general use except
strip src/*.exe
strip src/qt/*.exe 
if you want smaller executable files.

**Comment by bunnguyen2410** [comment]
![image](https://user-images.githubusercontent.com/30051202/46611238-71578100-cb37-11e8-941f-8cfb51340100.png)
Now, when i reinstall, and run "make", it appears these errors :((((((((((, don't know what to do next

**Comment by MeshCollider** [comment]
You can find instructions for building bitcoind on windows here: https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md
The issue tracker on GitHub is for issues with the code rather than help requests, please ask your question somewhere like https://bitcoin.stackexchange.com or similar :)
