### ISSUE TITLE
RPC Connection error after upgaring to version 17

### ISSUE THREAD

**Issue by ghanavati27** [bitcoin/bitcoin#14420]
I upgraded my bitcoin core to version 17
Now my application can't call methods via RPC commands.
Seems , BitcoinCore does not listen to RPC port.

Error message: "connect ECONNREFUSED 127.0.0.1:8332"
Is any new configuration for RPC in version17

My OS is windows server 2016 

When i downgrade my core to version 16.3 , everything will be fine.

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by fanquake** [comment]
Closing after no followup.

**Comment by MarcoFalke** [comment]
Could be a duplicate of  #14627?
