### ISSUE TITLE
estimatesmartfee only works for target>16 (testnet)

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#14431]
Core Version: 0.16.3. Network: TestNet.

![image](https://user-images.githubusercontent.com/9156103/46608405-f4abaf00-cb04-11e8-9c0e-96f30318b4c8.png)

The node is running for a few days now, and was serving targets 2-15 properly. Now, I noticed `estimatesmartfee` fails for any targets under 16. So, there's two abnormalities here:

- `estimatesmartfee` was working, but started failing later on
- `estimatesmartfee` only fails for targets < 16

Are any of these intended behaviors?

**Comment by RHavar** [comment]
I've witnessed this behavior on testnet too, although was running a 0.17 node and it was a bit higher than 16 for me.

**Comment by nopara73** [comment]
For the record a few hours later when I checked, it was estimating fees from target 9 properly. A day later it was estimating properly from target 3. And I checked now (3 days later) and it is estimating fees properly for everything. So the 16 I reported is not a magic number.  

> I wonder if it was something to do with resuming from an extended sleep

In my case it wasn't that. `bitcoind` was running for days on a server, while estimating fees properly, because I prevent even from starting my own server application until feerates for target 2 are not available.

**Comment by rytido** [comment]
I suspect this is just related to the low tx volume on testnet, and the affected targets likely vary. I think the estimates are based on fee rate buckets, and it seems possible that some of the buckets are totally empty at times, and this prevents proper estimation. A slightly educated guess.

**Comment by adamjonas** [comment]
@nopara73 have you retested this with more modern versions and experienced similar behavior?

**Comment by nopara73** [comment]
I haven't encounter this lately. Gonna reopen if I do.
