### ISSUE TITLE
Missing New button on create new receiving addresses screen

### ISSUE THREAD

**Issue by larry-beck** [bitcoin/bitcoin#14435]
In v0.16.2 and before, when I selected in the GUI, File - Receiving Addresses, the screen that came up listed all created receiving addresses for my wallet with a button on the bottom left labeled "New" to create new manual receiving addresses. Now in v0.17.0, there is no "New" button on the Receiving Addresses screen. However, on the Send Addresses screen, there is still a "New" button to create manual send addresses.

"New" button to be on the screen to create manual receive addresses without having to go to console and create the new receive address via the command line and then return to the GUI.

Screenshot of Receiving and Sending Addresses screens attached so you can see no "New" button on Receiving screen but still on the Sending screen.

Every time on v.0.17.0

v0.17.0

MacBook Air running macOS Mojave

No

N/A

![screen shot 2018-10-08 at 5 43 51 pm](https://user-images.githubusercontent.com/40723353/46635957-28e29800-cb24-11e8-8e9f-4b5d73c1cdc6.png)
![screen shot 2018-10-08 at 5 44 05 pm](https://user-images.githubusercontent.com/40723353/46635958-28e29800-cb24-11e8-95af-1d9f0aaabdb3.png)

**Comment by promag** [comment]
The button was removed on purpose. Please see #12721 for more information.

You can close this issue.
