### ISSUE TITLE
Error when "make check" WSL windows v0.17.99 and how to execute "bitcoind" 

### ISSUE THREAD

**Issue by bunnguyen2410** [bitcoin/bitcoin#14432]
![image](https://user-images.githubusercontent.com/30051202/46613537-ad8de000-cb3d-11e8-9f41-0b3d0a43cf71.png)
I got this error when running make check, because i didn't know how to run the "bitcoind" as mentioned in the book, how to fix this error and how to run bitcoind (path to "cd" to and where to run and how to run it). I'm so sorry, i'm new to this :(

**Comment by promag** [comment]
Getting the same error.

**Comment by promag** [comment]
Have you followed https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows? If so you must complete with https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#installation.

**Comment by ReidDinges** [comment]
Mag

**Comment by bunnguyen2410** [comment]
![image](https://user-images.githubusercontent.com/30051202/46709012-e88e3180-cc6b-11e8-9b66-b4d7d723de9a.png)
I got this problem :(

**Comment by ken2812221** [comment]
#14043
#13027
