### ISSUE TITLE
Release schedule for 0.18.0

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#14438]
Here is a proposed release schedule for 0.18.0, the next major release of Bitcoin Core. Like for previous major releases I've aimed for a release 6 months after the last (#12624).

2019-02-01 :heavy_check_mark: 
-----------
- Open Transifex translations for 0.18
- Soft translation string freeze (no large or unnecessary string changes until release)
- Finalize and close translations for 0.16

2019-02-15 :heavy_check_mark: 
-----------
- Feature freeze (bug fixes only until release)
- Translation string freeze (no more source language changes until release)

2019-03-01 :heavy_check_mark:  
-----------
- Split off `0.18` branch from `master`
- Start RC cycle, tag and release `0.18.0rc1`
- Start merging for 0.19 on master branch

2019-04-03 :construction: 
-----------
- Release 0.18.0 final (aim)

If any specific dates or timeframes are a problem for you, let me know.

**Comment by laanwj** [comment]
> Like for previous major releases I've aimed for a release 6 months after the last

There was some slippage there due to various well-known issues; the official release date for `0.17.0` is 2018-10-03, adding 6 months, shouldn't 2018-04-03 be the aim. Say, move it all a month forward?

**Comment by MarcoFalke** [comment]
There should probably be a 0.17.2 release before the 0.18.0 release

**Comment by laanwj** [comment]
> There should probably be a 0.17.2 release before the 0.18.0 release

What's the primary motivation for 0.17.2?

**Comment by MarcoFalke** [comment]
There have been some minor fixes, but I see that that might not be enough motivation to do it before 0.18.0

**Comment by fanquake** [comment]
☃️Feature freeze is today / tomorrow depending on where you are.

**Comment by laanwj** [comment]
Feature freeze was concluded, we'll only merge bugfixes until the 0.18 split-off.

**Comment by fanquake** [comment]
🌱 The `0.18` branch off should be happening today.

**Comment by fanquake** [comment]
[`0.18`](https://github.com/bitcoin/bitcoin/tree/0.18) has been branched 🎉.

**Comment by laanwj** [comment]
Release notes for 0.18.0 can be edited on the wiki now, as usual for major versions in RC-phase: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.18.0-Release-Notes-Draft

**Comment by fanquake** [comment]
[`0.18.0rc1`](https://github.com/bitcoin/bitcoin/releases/tag/v0.18.0rc1) has been tagged 🏷.

**Comment by fanquake** [comment]
[`0.18.0rc1` test binaries](https://bitcoincore.org/bin/bitcoin-core-0.18.0/test.rc1/) are now available.

**Comment by Sjors** [comment]
Testing feedback can go here: #15555

**Comment by fanquake** [comment]
[`0.18.0rc2`](https://github.com/bitcoin/bitcoin/compare/v0.18.0rc2) has been tagged 🏷.

**Comment by fanquake** [comment]
[0.18.0rc2](https://bitcoincore.org/bin/bitcoin-core-0.18.0/test.rc2) test binaries are now available.

**Comment by fanquake** [comment]
[0.18.0rc3](https://bitcoincore.org/bin/bitcoin-core-0.18.0/test.rc3/) test binaries are now available.

**Comment by fanquake** [comment]
[`0.18.0rc4`](https://github.com/bitcoin/bitcoin/releases/tag/v0.18.0rc4) has been tagged 🏷. The changes from `rc3` are [here](https://github.com/bitcoin/bitcoin/compare/v0.18.0rc3...v0.18.0rc4).

**Comment by fanquake** [comment]
[0.18.0rc4](https://bitcoincore.org/bin/bitcoin-core-0.18.0/test.rc4/) test binaries are now available.

**Comment by fanquake** [comment]
[`v0.18.0`](https://github.com/bitcoin/bitcoin/releases/tag/v0.18.0) has been tagged 🏷. The changes since `rc4` are [here](https://github.com/bitcoin/bitcoin/compare/v0.18.0rc4...v0.18.0).

**Comment by MarcoFalke** [comment]
:rocket:

**Comment by JenniferBrooks39** [comment]
#18852

**Comment by JenniferBrooks39** [comment]
- [ ]   #@`[
Duplicate of 
![IMG_0054](https://user-images.githubusercontent.com/59108109/80891726-86e94a00-8c8b-11ea-8b25-97256a7616da.JPG)
#](url)`
