### ISSUE TITLE
Correct balance ?

### ISSUE THREAD

**Issue by hamnaz** [bitcoin/bitcoin#14445]
i installed bitcoin core 0.16.3, and full sync, i load my keys, and wait, and rescan
now balances are diffrent shown, any suggestion what is correct balance
some command i apply, and results here
waiting your help, solutions etc
Thankx

~/bitcoin-0.16.3/bin$ ./bitcoin-cli getwalletinfo
{
  "walletname": "wallet.dat",
  "walletversion": 159900,
  "balance": 19.86576864,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 5666,
  "keypoololdest": 1538466741,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.00000000,
---------------------------------------------------------------
~/bitcoin-0.16.3/bin$ ./bitcoin-cli getbalance
19.86576864
---------------------------------------------------------------
~/bitcoin-0.16.3/bin$ ./bitcoin-cli getreceivedbyaccount ""
253.57105799
---------------------------------------------------------------
~/bitcoin-0.16.3/bin$ ./bitcoin-cli listreceivedbyaccount 
[
  {
    "account": "",
    "amount": 253.55285799,
    "confirmations": 12947
  }
]

------------------------------------------------------------------------
~/bitcoin-0.16.3/bin$ ./bitcoin-cli listaccounts
{
  "": 0.00020000,
  "wallet.dat": 0.00000000
}

--------------------------------------------------------------------

~/bitcoin-0.16.3/bin$ ./bitcoin-cli listunspent
[
  {
    "txid": "15e9ee719ddf0e1f68586b856c5d8e58c7bcb37c955f03a91ed6d9531d68431b",
    "vout": 3,
    "address": "1HyAcHNbUaW8pSWYQWvsobpQFd44BK4xgc",
    "account": "",
    "scriptPubKey": "76a914ba2153b777d3aa93e3ad6fe549636be5204075b788ac",
    "amount": 0.00020000,
    "confirmations": 208324,
    "spendable": true,
    "solvable": true,
    "safe": true
  },
  {
    "txid": "94e247464e6d5f323b0c781ffe0c42562afeafd01430fb7f55ad58b3cf5eb928",
    "vout": 0,
    "address": "17zHADrQXRtTycekZzm5NcxkmxduFTwi7v",
    "account": "",
    "scriptPubKey": "76a9144ca5f410395ed81039a8230fb4a825f96e0080c288ac",
    "amount": 0.00020000,
    "confirmations": 119800,
    "spendable": true,
    "solvable": true,
    "safe": true
  }
]
-------------------------------------------------------------

**Comment by promag** [comment]
@hamnaz this is not the place to get support, please ask in https://bitcoin.stackexchange.com.

You could give more details especially:
 - if you use an existing wallet 
 - what was done in "i load my keys, and wait, and rescan".

**Comment by hamnaz** [comment]
difrent times in last 8 years, i installed bitcoin core and created wallet.dat where i use for send and recive coins, and saved wallet.dat
and now after 3 years i had more then 13 wallet.dat files ( 16000 keys), i use pywallet to decode it my address and keys
newly installed bitcoiin core 0.16.3, and use importprivkeys to load my keys
after these all procedure i see above results by apply commands
dont know what is real balance
advice

**Comment by fanquake** [comment]
As suggested by @promag, please take these kind of questions to https://bitcoin.stackexchange.com. If it turns out there is a technical issue with Bitcoin Core, then please open an issue with all the required info.
