### ISSUE TITLE
Allow direct importing of xpubs

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#14449]
With the new HD wallet code, importing wallets by xpub is now a possibility.

This would facilitate the creation of watch-only wallets. The current process, as I understand it, includes:
- Create a new `wallet.dat` (with `createwallet` or on first-run)
- Use `dumpwallet` to create a file with the `extended private masterkey`
- Delete the wallet
- Recreate the wallet from its xprv with `createwallet "name" true`, so it is watch-only

This doesn't consider the use case where an offline external client generates the `xprv` and `xpub`

We should be allowed to import an xpub:
- At the root
- At a given derivation path

**Comment by ch4ot1c** [comment]
I now see https://github.com/bitcoin/bitcoin/pull/13926. Adding xpubs via `bitcoin-cli` could still be useful, though.

**Comment by Sjors** [comment]
Concept ACK.

I think the best approach would be to add descriptor support to `createwallet`. Alternatively you would create an empty wallet and then import using an improved `importmulti` with descriptor support.

Take for example a bech32 enabled ([BIP84](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki)) hardware wallet:

```sh
bitcoin-cli createwallet "my_hardware_wallet" true 
   '{"receiveDescriptor": "wpkh(tprv8Z...bK/84h/0h/0h/0/[0-1000]",
      "changeDescriptor": "wpkh(tprv8Z...bK/84h/0h/0h/1/[0-1000]"}'`
```
(or however we want to add ranges to descriptors)

This above example uses the master private key to derive everything, which is obviously unsafe. Instead you would use the account xpub, but keep the full derivation info (needed for signing) #14150:

```sh
bitcoin-cli createwallet "my_hardware_wallet" true 
   '{"receiveDescriptor": "wpkh(fingerprint/84h/0h/0h:account_xpub/0/[0-1000]",
      "changeDescriptor": "wpkh(fingerprint/84h/0h/0h:account_xpub/1/[0-1000]"}'`
```





@sipa does this make sense?

**Comment by Sjors** [comment]
The `importmulti` approach now has a PR #14491.

**Comment by Sjors** [comment]
In addition to #14491 you need #14075 to make direct importing of xpubs useful.

Out of scope, but note that the current `importmulti` descriptor approach only works with xpubs, not for private keys, due to [how the keypool works](https://github.com/bitcoin/bitcoin/pull/14075#issuecomment-446547958).

**Comment by prusnak** [comment]
@Sjors can you please update us on how to use `importmulti` command to create a watch-only wallet from xpub?

**Comment by Sjors** [comment]
@prusnak try the (undocumented) `getdescriptors` HWI command on a Trezor to get all three :-)
https://github.com/bitcoin-core/HWI/pull/137

**Comment by prusnak** [comment]
@Sjors Thanks!

**Comment by Sjors** [comment]
Also see the `getkeys` command for the other options you'll need with `importmulti`: set `watchonly` and `keypool` to true, and use `internal` for the change address descriptor.

**Comment by Sjors** [comment]
Descriptor wallets (and HWI integration) now allow all this cool stuff, suggest closing.

**Comment by prusnak** [comment]
+1 for closing in favor of using descriptors

**Comment by jarolrod** [comment]
reiterating the statements above, importdescriptors and hwi integration would have solved this in my opinion.
