### ISSUE TITLE
Widget refresh glitches in v0.17.0 built with Qt 5.11.2 on OS X 10.12.6

### ISSUE THREAD

**Issue by gwillen** [bitcoin/bitcoin#14469]
When I build v0.17.0 myself on OS X (Sierra, 10.12.6) with QT 5.11.2 installed from Homebrew -- but NOT when I use the build downloaded from bitcoincore.org -- I experience glitches in which certain widgets do not refresh when they should.

In particular, when I click "Use available balance" in the Send tab, nothing happens -- the balance field does not update at all until I do one of the following: click in the balance field, open the debug window, change tabs and change back, switch to another app. At that time it updates to show my whole available balance.

This ONLY happens when I build bitcoin-qt myself, not with the binaries downloaded from bitcoincore.org.

I say "widgets" plural because I found that the same thing happens to a QPushButton I have created in a new QDialog -- when I call setEnabled(false) on it, it does not turn grey until I either change focus as above (e.g. switch to another app), or call ui->theButton->repaint().

@Sjors suggested on IRC that my Qt version might be to blame, but I will note that my OS X version is also quite outdated at this point.

**Comment by Sjors** [comment]
I can't reproduce the "Use available balance" bug on macOS 10.14 with QT 5.11.2, perhaps others can try with older versions of macOS (e.g. @jonasschnelli)?

Knowing where this glitch is introduced can be useful in future discussion of bumping minimum supported versions, as well as perhaps in tracking down other bugs.

The distribution binaries use QT 5.9.6. Can you try building with the [depends system](https://github.com/bitcoin/bitcoin/tree/master/depends)?

Another difference is that macOS SDK 10.11 is used for building the binaries, whereas you're on 10.12 and the most recent macOS is 10.14. I'm not sure how you can build against 10.12, other than using Gitian.

**Comment by fanquake** [comment]
I'm also unable to reproduce that behaviour. 
This is using macOS 10.14, brew installed qt 5.11.2 and master at 6746a89.
![14469](https://user-images.githubusercontent.com/863730/47253231-3fbdae80-d483-11e8-89aa-ec23a5826d26.gif)

**Comment by gwillen** [comment]
I'm totally happy for this to be closed -- I reported it because it was suggested I do, but I am mystified about how my system is different. I am working in Qt Creator, for what it's worth, although I can't see why it would make any difference. (It still does it when I run the binary from the commandline, and as far as I know QTC shoud just be building using the Makefile...)

**Comment by fanquake** [comment]
Going to close for now.
