### ISSUE TITLE
Can't Unlock My BTC Core Wallet With Correct Password

### ISSUE THREAD

**Issue by jan2500** [bitcoin/bitcoin#14461]
after my hard disk has got corrupted and my pc stopped working I purchased a new hard disk. have downloaded the bitcoin core wallet and added my backed up wallet.dat into /roaming folder. The wallet shows my correct balances and all transactions but I'm not able to unlock it with my correct password when I try to send or receive bitcoins (I did secure it with my password). 

At the beginning I thought the password/s I was using aren't correct, but then I made an observation, that only when I type in only one specific password then I receive this message in popup:
>>>assertion failed<<<
>>>program: C:\Program Files\Bitcoin\bitcoin-qt.exe<<<
>>>File: wallet/crypter.cpp, line 205<<<
>>>expression false<<<

>>>Runtime Error<<<
>>>program: C:\Program Files\Bitcoin\bitcoin-qt.exe<<<

When I enter any other passwords only message I get your password is incorrect and never receive the message in popup described above. I can use incorrect passwords all day and that message doesn't appear at all, but as soon as I enter correct password the message is on.

after I enter my password I expected to unlock my wallet, but that isn't a case and instead I get an error and I'm not able to send or receive bitcoins

This error message appears only when I type in my correct password. If I type in any other password this message doesn't appear, but instead it tells me the provided password is incorrect. Message in a popup when a correct password is being used:
>>>assertion failed<<<
>>>program: C:\Program Files\Bitcoin\bitcoin-qt.exe<<<
>>>File: wallet/crypter.cpp, line 205<<<
>>>expression false<<<

>>>Runtime Error<<<
>>>program: C:\Program Files\Bitcoin\bitcoin-qt.exe<<<

each time I enter the correct password the window with the message with an error message appears. If I type in any other (not correct) password this doesn't happen at all. I can type 20 incorrect passwords and the error message above doesn't popup.

v0.17.0
Have downloaded it from bitcoin.org website

windows 8.1
64 bit operating system
500GB SSD hard disk
intel celeron cpu N2840 2.16 GHz

I have reinstalled the wallet, deleted all files under /roaming folder (approx. 145GB), so totally clean 
installation. Only old file is my wallet.dat file.

![btc error](https://user-images.githubusercontent.com/44040275/46770496-f38aa580-ccef-11e8-88c2-0d9defc4efdd.png)

[log file.txt](https://github.com/bitcoin/bitcoin/files/2466745/log.file.txt)

**Comment by emilrus** [comment]
Your wallet.dat is probably corrupted, do you have another backup?

**Comment by jan2500** [comment]
unfortunately have only this one backup file

**Comment by jan2500** [comment]
btw, have found another backup from few months earlier, but exactly the same issue as described above. I can see the difference between both back up files (dates and number of transactions). How that can be possible to have 2 back ups from 2 different dates with the same issue?

**Comment by ryanofsky** [comment]
Haven't looked into this yet, but even if the wallet is corrupted, we should try to show a more sensible error instead of asserting false and crashing.

**Comment by emilrus** [comment]
Try with an older version of bitcoin, some wallet related changes were introduced in 0.17

**Comment by jan2500** [comment]
sounds reasonable. will try it. if not solved will comment here.

**Comment by MeshCollider** [comment]
@ryanofsky indeed, the error is only printed to the log but not the GUI

**Comment by jan2500** [comment]
Update on a progress. Have discovered, that when my backup was made in 2013, then I had to download the bitcoin core wallet from 2013. Have literally gone through all wallet releases starting from 2018 down to 2013. Once downloaded, I clicked on 'receive' section and tested if that is asking for my password (note: my wallet was password protected). All wallet newer releases were still asking for my password and showed the same error described in the issue. Once I downloaded the wallet release from 2013 and clicked on the 'receive' section it stopped asking for my password.

Now, I'm still downloading the blockchain files (1 year and 30 weeks left) so haven't tried to send my btc out, which will require my password to enter. Then I will be able to fully conclude this has worked. However, so far it seems like, whenever a back up was made, then btc core wallet version must by from the same year in order to work properly. This at least applies to old wallets. 

Will write an update once whole blockchain downloaded to confirm this solution is valid.

**Comment by jan2500** [comment]
Problem solved. After I have downloaded old version of the bitcoin core wallet from 2013 (when I have made the backup file) then the password I used to lock my wallet has worked and wasn't getting any error message anymore. So the conclusion is, the old back up worked with the old version of bitcoin core wallet and didn't work with the newer version of the bitcoin core wallet

**Comment by MarcoFalke** [comment]
> Problem solved

Ok, closing then.
