### ISSUE TITLE
decoderawtransaction(getrawtrasaction(txid)) error

### ISSUE THREAD

**Issue by wuchiachih** [bitcoin/bitcoin#14483]
Got a different txid while decoding this TX: f46c537e6b5fd02372d5b6c56debd37e4da770168fee921c25859a91957b057f

I thought I should get a TX with txid = f46c537e6b5fd02372d5b6c56debd37e4da770168fee921c25859a91957b057f

But, I get a TX with txid = 074104196feb30c7f3ac030ecc06b90f597e6458eca0e30c2f5fb5b49cef012d like this:

<img width="792" alt="screen shot 2018-10-15 at 4 11 49 pm" src="https://user-images.githubusercontent.com/6262559/46937949-107afc00-d095-11e8-979f-3014a110c250.png">

I can always repro this on my Bitcoin Core node.

I'm running Bitcoin Core Daemon version v0.16.3.0-g49e34e288

**Comment by MeshCollider** [comment]
Could you try `decoderawtransaction(getrawtrasaction(txid), true)` please? It looks like it is just decoding as a non-segwit transaction instead of a segwit one.

**Comment by wuchiachih** [comment]
It works.  So, we need to always put a "true" while calling decoderawtransaction() ?

**Comment by sipa** [comment]
You can always pass `true` if you know the transaction is complete (i.e. fully signed). The alternative is for dealing with transactions that may be missing inputs.
