### ISSUE TITLE
Add ability to specify mining reward in regtest mode

### ISSUE THREAD

**Issue by PWKad** [bitcoin/bitcoin#14488]
As a developer for lightning apps there are times when bitcoind is running and generating blocks.  It is required to send coins to the lightning wallet first.  It would be a nice feature similar to btcd to allow setting the mining reward address when generating blocks.

17

OSX

**Comment by sipa** [comment]
There is a `generatetoaddress` RPC since 0.13, available in regtest mode.

**Comment by PWKad** [comment]
Doh thanks!  Couldn't find any info out there about it, closing now.
