### ISSUE TITLE
Can I upgrade to Bitcoin Core 0.17.0 while 0.16.3 bitcoin is running?

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#14500]
I am afraid I know the answer already, I just hope there may be a little secret trick. If there'd be a way to keep 0.16.3 running or 0.17.0 answering for some RPC commands while `txindex` migration is happenning, that'd be great help, since I'm reluctant to shut down the server for hours.

From the release notes: https://bitcoincore.org/en/releases/0.17.0/

> If your node has a txindex, the txindex db will be migrated the first time you run 0.17.0 or newer, which may take up to a few hours. Your node will not be functional until this migration completes.

**Comment by NicolasDorier** [comment]
I think your best bet is to pop up a second, brand new node and switch over once the sync is done.

**Comment by promag** [comment]
You could keep at least 2 running and in sync which you could use like master slave or to load balance RPC. The point is you can upgrade one, update your clients, and then upgrade the other if everything is fine.

**Comment by nopara73** [comment]
Thanks, pretty good ideas. Probably it doesn't worth the trouble for me, because so many things can go wrong, I'm afraid I'd ruin something, so a simple server shutdown for an hour may be preferable for now, while only a couple of hundred tech savvy early adopter users are effected. But for the future, I'll keep them in mind.

**Comment by nopara73** [comment]
I started upgrading the testnet server. Can I get how much time there's left?
Nor `getnetworkinfo` nor `getblockchaininfo` works.

**Comment by nopara73** [comment]
Wow, testnet reindexed within 4 minutes. The mainnet server much faster (of course the database is much bigger, too)

**Comment by nopara73** [comment]
Done. It took 33min, everything went great.
