### ISSUE TITLE
Version number for `bitcoin.conf` format

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#14514]
Introduce a version number for configuration file(s) _format_; e.g., `version=1` in the first line.

Pros:
- ability to add or deprecate _format_ features (see: #13143,  #14494) without breaking changes

Cons:
- plus 35 LOC per every supported version of parser

Additionally, the client can automaGically bump config file version if it complies to the newer one.

**Comment by luke-jr** [comment]
Seems like it would defeat the point of deprecating features.

**Comment by laanwj** [comment]
Agree with @luke-jr. Don't think this would change anything, deprecating something would still break support for the old versions.

Also I think this would be confusing for users and developers alike. Do you have any example of other software which uses configuration versioning—in this sense—successfully?

**Comment by promag** [comment]
docker-compose.yml has version. You have to support all versions so it I don't see how it helps with deprecation.

**Comment by hebasto** [comment]
@MeshCollider 

> ... and versioning command line arguments seems like a bad idea.

You're right. But this discussion is not about _command line arguments_ versioning, rather about config file _format_ versioning.

**Comment by hebasto** [comment]
@laanwj 

> Also I think this would be confusing for users and developers alike. Do you have any example of other software which uses configuration versioning—in this sense—successfully?

File format versioning (in general) is a common practice. In particular the Electrum Wallet config file has a version (e.g., `"config_version": 2`).

**Comment by hebasto** [comment]
Consider the issue #13143 as a possible use case:

Current non-versioning (`version=0`) format allows a comment to start after an `option=value` pair. That makes the parser to wrong parse a `#` character within a `rpcpassword` value.

Assume that `version=1` format allows comments to start only from the line beginning. This makes possible to use a `#` character within a `rpcpassword` value.

No doubt that previous format versions must be supported during a certain period of time _to prevent the breaking support for the old format config files_ (it will cost 35-40 lines of code per version). And eventually old and deprecated formats support may be dropped.

The future may require more config format improvements and it'll be easy to introduce them with format versioning, IMO.

**Comment by MarcoFalke** [comment]
I think this feature can be added when there is need for it. I don't see a need right now.

**Comment by promag** [comment]
@hebasto do you think this can be closed?

**Comment by MeshCollider** [comment]
Seems like a non-issue for now as mentioned above, closing
