### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aprenminer** [bitcoin/bitcoin#14520]
hello I have a problem to synchronize my portfolio.
I have 20 dollars in bitcoin on my PC.
I need them to spend on a very important debt.
 In an old version of Bitcoin Core, version 0.9.3, but trying to spend them can not be synchronized first.
I tried to synchronize but it's been a month and sometimes the PC freezes
The creators of Bitcoin Core could help me with this problem, where I get the full bootstrap for this version.
someone with the bootstrap for this version someone to upload it, please help.
I believe and trust Bitcoin. I do not want to lose confidence in this currency.

**Comment by sipa** [comment]
This is not a support forum.

For questions about usage, try https://bitcoin.stackexchange.com.
