### ISSUE TITLE
bitcoin client 0.17.0 ignores wallet's name (file)

### ISSUE THREAD

**Issue by nikitasius** [bitcoin/bitcoin#14523]
Old config (version 0.15 and 0.16.0/0.16.3):
```
prune=8192
rpcuser=rpc
rpcpassword=rpc
onlynet=ipv4
testnet=1
rpcbind=127.0.0.1:18332
walletdir=/path/to/wallet/
wallet=mywallet.dat
```
It worked pretty nice.

### UPD: it does not worked in version 0.17.0 ! BTC client made a new `wallet.dat` file

On version 0.17.0 i read what i can use full pathes to wallet files.

```
prune=8192
rpcuser=rpc
rpcpassword=rpc
onlynet=ipv4
testnet=1
rpcbind=127.0.0.1:18332
wallet=/path/to/wallet/mywallet.dat
```
FAILS. It created `wallet.dat` in `/path/to/wallet/` folder
___
```
prune=8192
rpcuser=rpc
rpcpassword=rpc
onlynet=ipv4
testnet=1
rpcbind=127.0.0.1:18332
walletdir=/path/to/wallet/
wallet=/path/to/wallet/mywallet.dat
```
FAILS. It created `wallet.dat` in `~/.bitcoin/wallets` folder.
___
Current config:

```
prune=8192
rpcuser=rpc
rpcpassword=rpc
onlynet=ipv4
testnet=1
rpcbind=127.0.0.1:18332
walletdir=/path/to/wallet/
```
AND i renamed `mywallet.dat` into `wallet.dat` to let client work.

I run `bitcoin core client 0.17.0` on `Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`.

**Comment by ryanofsky** [comment]
> but why i need (or not) to specity test section inside a config? i.e. i already specified a testnet.

Before #11862 and [0.17.0](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.17.0.md#configuration-sections-for-testnet-and-regtest), you didn't need to have `wallet` and other "network-only" options under a network section. Now it looks you need to or they get ignored.

I think this is a mistake, and we should backport a fix that will restore the old behavior. It don't think it is ok to just start ignoring settings that used to work. We should probably keep a log message to encourage people to use network-specific sections and be more explicit about settings that are sensitive to which network is used, but we should not just be dropping the settings on the floor.

It also seems like a mistake to me that `-wallet` is a "network-only" option but "-walletdir" is not. This is another thing that should probably be addressed.

**Comment by MarcoFalke** [comment]
Moving to 0.17.2

**Comment by MarcoFalke** [comment]
Made it an error instead of warning in #15629, so at least Bitcoin Core wouldn't start with such a config file.

**Comment by MarcoFalke** [comment]
Should be "fixed" in master
