### ISSUE TITLE
walletutil.cpp build issue

### ISSUE THREAD

**Issue by wkibbler** [bitcoin/bitcoin#14535]
when` trying to compile bitcoin from source on unix I get this issue

`wallet/walletutil.cpp: In function ‘std::vector<boost::filesystem::path> ListWalletDir()’:
wallet/walletutil.cpp:60:32: error: ‘relative’ is not a member of ‘fs’
             paths.emplace_back(fs::relative(it->path(), wallet_dir));
                                              ^
wallet/walletutil.cpp:71:36: error: ‘relative’ is not a member of ‘fs’
                 paths.emplace_back(fs::relative(it->path(), wallet_dir));
                                                   ^
Makefile:6894: recipe for target 'wallet/libbitcoin_wallet_a-walletutil.o' failed`

im guessing it has something to do with missing the boost file system dependency but ive tried downloading and building boost from source and ive tried resetting my vps 3 times to start again. 
When configure is searching for the file system dep is finds it but i still cant build it.

**Comment by promag** [comment]
Fixed in #14531.

**Comment by fanquake** [comment]
The problem is that usage of a Boost 1.64 function `fs::relative` was introduced into the codebase (master) in #14291. There is currently a PR open to remove its usage https://github.com/bitcoin/bitcoin/pull/14531.

**Comment by wkibbler** [comment]
ok thanks
