### ISSUE TITLE
functional test with ancient wallet.dat (upgrade test)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#14536]
There should be a test that starts a node on a datadir with a wallet that was created by an ancient (potentially no longer supported version) of Bitcoin Core.

Wallets could be created for every released version of Bitcoin Core, but in this repo and on travis it should be sufficient to run against one wallet. Exhaustive tests could be done externally.

In the future we could even run it against the whole datadir with blocks and chainstate, but this is of lower priority.

**Comment by ryanofsky** [comment]
I think it would be nice if this were done using #12134, so old wallets could be programmatically generated in python. This would make it easier to write new tests for specific upgrade bugs. It would also let us avoid having to keep track of a collection of unreadable binary blobs or database dumps.

**Comment by MarcoFalke** [comment]
I see the advantage, but at some point the old code can no longer be compiled on a recent Ubuntu. So the tests would break if we needed to generate the wallet file that way.

**Comment by ryanofsky** [comment]
I think #12134 uses release binaries so is less likely to break due to dependency issues. But even if a release stops working and blobs need to be generated offline, I think it's better if blobs are programmatically generated so tests are understandable and extensible.

**Comment by Sjors** [comment]
Keep in mind that #12134 previous versions currently don't go back far enough to generate a non-HD wallet, and it's non-trivial to keep the functional test suite alive for very old node versions. So a hardcoded payload in the test suite, which we can dynamically load, makes more sense to me.
