### ISSUE TITLE
getBlockHeadersByHash Error: Extension "json" is not supported

### ISSUE THREAD

**Issue by educob** [bitcoin/bitcoin#14537]
Hello.

I am receiving block notifications (via zmq) and by calling client.getBlockByHash (json extension) but when running:
client.getBlockHeadersByHash( '00000xxxxx...', 1, { extension: 'json'})

I get: Error: Extension "json" is not supported

It works with extensions bin and hex.

solution: 
line 220: if (!_lodash.default.includes(['bin', 'hex'], extension)) {
Must be changed to: if (!_lodash.default.includes(['bin', 'hex', 'json'], extension)) {

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests for other clients or software are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
