### ISSUE TITLE
The command "listunspent" returns a transaction that was already spent

### ISSUE THREAD

**Issue by LibraHan** [bitcoin/bitcoin#14545]
Hi,I've encountered difficulties and need help. 
I've got a USDT address and want to get the BTC unspentlist for transfee,   I do the command 
listunspent 0 99999 "[\"\"]" in the OmniCore wallet,but find it always lost transactions, and the result is not correct. Then I think maybe I can check it in the Bitcoin Core wallet, but unfortunately I got a transaction in the result list that was already spent.Why does this already spent transaction still exist in the unspentlist? Cannot I check the unspentlist of USDT address in the Bitcoin Core wallet ?

**Comment by sipa** [comment]
This is the issue tracker for Bitcoin Core, not Omni or Tether.

For questions related to Bitcoin and specific software, try https://bitcoin.stackexchange.com.
