### ISSUE TITLE
fundrawtransaction - select input transaction with minimum confirmations

### ISSUE THREAD

**Issue by g5501439** [bitcoin/bitcoin#14542]
when using to fundrawtransaction, how to select input transaction with minimum confirmations option ? @jonasschnelli what's default option for funded when select inputs ?

**Comment by promag** [comment]
I don't understand the 2nd question.

As for the 1st, that is not possible. Why would you want to do that?

**Comment by onesandzer0es** [comment]
If the fundrawtransaction method selects input (1 confirmation tx), and what happens if the non-valid chain breaks ?

I guess with the createrawtransaction method, 6 confirmations txs can be selected, why can't this selection be made with the fundrawtransaction method ? @promag

**Comment by promag** [comment]
It's not that simple, the coin selection algorithm takes into account several aspects, especially if an input is a transaction created by the wallet and the corresponding depth. AFAIK you can't override the minimum input depth.

**Comment by onesandzer0es** [comment]
So, in the coin selection algorithm, only the coin amount of UTXO are paid attention ? Is algorithm also taken care of the number of confirmations that received ?
