### ISSUE TITLE
Bitcoin Source Code review question.

### ISSUE THREAD

**Issue by bozeyman9000** [bitcoin/bitcoin#14544]
My question is in regards to reviewing the legitimacy of bitcoin itself. I have been involved with bitcoin as a trader since the price was hovering around 10 dollars. I have noticed lots of scams and illegitimate claims from various entities that offer bitcoin doubling etc. I also noticed that while mining with genesis I received a spike in my payouts.  When bitcoin was explained to me i was under the impression that a block created a set amount of coins to be paid out every set time period so this has added to my curiosity of just what is going on "under the hood" I learned pascal years ago and understand the basics of coding and of arranging code to be presentable and easily read by future developers and would like to see exactly what is going on. I already have a good idea of how to create a blockchain type program and from what I can pull from my biological memory and various google searches any attempts at plagiarism would simply speed up my learning process rather than allow me to copy ones work. I have the Bitcoin master folder already unzipped to my desktop and am seeing that there are alot more files than i suspected. To create a blockchain seemed a bit more simple in my head, You simply run a loop with a timer on it to read new data check it against a checksum (the previous block) then once verification is processed (verified =P) you write the new data as the new checksum. Who is to say and prove that all these files dont simply add various backdoors where all of the data can be edited. Anyway, any assistance would be great and ill start reviewing what i can with the knowledge and tools at my disposal.

**Comment by merland** [comment]
A bit hard to get what your main question is, but it seems that you are worried about malicious developers "sneaking in" changes that would benefit themselves. This is not an unusual worry and has been adressed many times before. I recommend that you read [this article](https://en.bitcoin.it/wiki/Myths#Miners.2C_developers_or_some_other_entity_could_change_Bitcoin.27s_properties_to_benefit_themselves), I think/hope you will find your answer there. TL;DR: No need to worry :)

**Comment by fanquake** [comment]
This question would be better suited to the [bitcoin StackExchange](https://bitcoin.stackexchange.com). 
If you search there, you'll likely find questions, as well as answers about some of the topics you raise i.e https://bitcoin.stackexchange.com/search?q=backdoor.
