### ISSUE TITLE
If minimize while opening on Windows, app soon appears as regular window again.

### ISSUE THREAD

**Issue by OneOfMany07** [bitcoin/bitcoin#14548]
I don't want to see your app most of the time, but I don't see a "start minimized" option in your app (I'll file a feature request next).  So I tap the minimize button when it starts (when I see startup dialog before initial sync happens from time while shut down).  Then a short time later I see the sync dialog that I must minimize again to ACTUALLY minimize the app.  The initial dialog's current state should be propagated to any further dialogs that happen during startup.

Have seen this issue for a long time, like years, and wouldn't be surprised if related to another bug I saw mentioning a Qt minimize issue.  But they didn't seem to mention the behavior I'm seeing, so opening another bug.  Note that the other issue has been open for 2 years which is pretty sad for a UI bug that sounds pretty simple/basic.

I have Hide tray icon off, minimize to tray instead of the taskbar on (which doesn't work), and minimize on close off.  I'm running on Windows 10 with all released updates.  Have been periodically upgrading but on v0.16.1 64 bit currently (always been 64 bit...maybe that is the issue?)  Think I saw this on 0.14.x at least if not earlier.

**Comment by merland** [comment]
Maybe #14550 solves your problem?
