### ISSUE TITLE
Automatic notification if user is behind current released version feature request.

### ISSUE THREAD

**Issue by OneOfMany07** [bitcoin/bitcoin#14551]
Instead of requiring the user to manually look to see if they need to update their client, have the client check while running periodically if the current version is older than the currently released version.  That should make user updates, in the event of bad bugs like security issues, much more likely to happen quickly.

This is instead of the much better "automatically upgrade users" option that I'm not sure you want to force users into (though a setting to enable/disable could be easy enough to add, to allow them to override that feature).

**Comment by fanquake** [comment]
Duplicate of #4897, #2626
