### ISSUE TITLE
Start minimized option in settings feature request.

### ISSUE THREAD

**Issue by OneOfMany07** [bitcoin/bitcoin#14550]
I run a node to make current state easy/fast to see later on, after I spend.  I don't want to see your app at all unless I'm spending money or doing some other active action.  To that support goal, I'd like a "start minimized" option in your settings area, and it might be useful to keep the existing state between runs (after system shuts down) as an alternative "no extra user work required" version.  Versus needing them to dig in dialogs to find this setting when they likely want to not be bothered by your app if they'd minimized it before.  I'm on Windows 10, 64 bit if that matters.

**Comment by hebasto** [comment]
There is a `-min` option to start `bitcoin-qt` minimized which may be included in `bitcoin.conf`.
