### ISSUE TITLE
listtransaction count and skip behavior backwards

### ISSUE THREAD

**Issue by morchlo** [bitcoin/bitcoin#14567]
Listtransactions returns $count amount of most recent transactions and skips $skip amount from the most recent transactions.

While there are reasons for doing such previously (with accounts), we should consider the new logic for listtransactions to return $count items from the oldest transactions if $skip is not defined. If $skip is defined, we wil return the items from $skip.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
