### ISSUE TITLE
Setup with dynamic IPv6 address shows outdated info for localaddresses

### ISSUE THREAD

**Issue by frennkie** [bitcoin/bitcoin#14587]
I am running my bitcoin node (`v0.17.0`) at home on my DSL network. My ISP terminates my connection every 24 hours and due to this I get a different IPv4 address every day. This also applies to IPv6 - although here I get a different /64 prefix each day. 

When I start `bitcoind` and let it run for a few minutes it will successfully connect to the bitcoin network and `bitcoin-cli getnetworkinfo | jq '.localaddresses'` will show e.g.:

```
[
  {
    "address": "2001:18c8:2851:e900:979c:f155:XXYY:ZZ1c",
    "port": 8333,
    "score": 1
  },
  {
    "address": "2001:18c8:2851:e900:ffea:fd8e:XXYY:ZZ37",
    "port": 8333,
    "score": 882
  }
]
```

The `2001:18c8:2851:e900` part here is a dynamic prefix. This will change every 24 hours. Waiting 1-2 day I can run `bitcoin-cli getnetworkinfo | jq '.localaddresses'`  again and **it will show exactly the same addresses**. But my DSL router will no longer have this IPv6 prefix assigned. Running `ip -6 a` will also confirm that I no longer have an IPv6 address with global address that starts with `2001:18c8:2851:e900`.

**I do have active connections the bitcoin network on IPv6. Therefore I belief this is more a cosmetic than a functional issue!**

Please let me know if I have any wrong assumptions, am doing something wrong or what else I need to provide so that this issue can be checked.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
