### ISSUE TITLE
[github] Bitcoin Core black logo isn't a perfect circle

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#14586]
Discord exhibits this:

![image](https://user-images.githubusercontent.com/2287825/47590428-db429980-d931-11e8-8f06-e224cbf84595.png)

**Comment by petsinis** [comment]
You can check if this icon works...
![about6](https://user-images.githubusercontent.com/32618554/48676229-94c90f00-eb6c-11e8-9fda-4bf3b9076a25.png)

**Comment by RandyMcMillan** [comment]
Bitcoin image is 128x128
https://avatars2.githubusercontent.com/u/528860?s=200&v=4

Zcash image is 200x200
https://avatars2.githubusercontent.com/u/16122764?s=200&v=4

![bitcoin](https://user-images.githubusercontent.com/152159/52174421-54d3fa00-2761-11e9-91ad-1e866b879f6a.png)

![bitcoin 3x](https://user-images.githubusercontent.com/152159/52174429-661d0680-2761-11e9-89da-3b113afbab8c.png)

**Comment by MarcoFalke** [comment]
Nothing we can do about that
