### ISSUE TITLE
bitcoin not producing exe file for window in ubuntu sub system 

### ISSUE THREAD

**Issue by awaissakhi11** [bitcoin/bitcoin#14598]
when i am compiling the bitcoin source code on ubuntu sub system and its compile perfectly but i run (make install DESTDIR=/mnt/c/Users/ovs_m/DESKTOP/bitcoin) its show me some file in bin folder at my desktop but the file bitcoin-qt is not exe file so in short when i compile source code its not creating exe file

**Comment by sipsorcery** [comment]
@awaissakhi11 can you provide some further information about which instructions you followed, what version of Ubuntu and virtualised environment if applicable?

**Comment by awaissakhi11** [comment]
now its working fine thank you

**Comment by awaissakhi11** [comment]
but i have another issue like i am trying to compie the xtrabyte source
code on ubuntu so its working for but i want to get the exe file from
xtrabyte source code .. i mean for cross platform

**Comment by fanquake** [comment]
@awaissakhi11 We don't provide support for alt coins here.
