### ISSUE TITLE
RPC Error: error -8

### ISSUE THREAD

**Issue by edwardleehl7097** [bitcoin/bitcoin#14607]
i just setup btc wallet and it show this error:
RPC Error: error -8: dummy value must be set to "*"

i have tried run ./bitcoind --deprecatedrpc=accounts
but the error still showing

**Comment by MarcoFalke** [comment]
Is the first argument you are passing to the RPC the dummy value, i.e. a string of `"*"`?

**Comment by edwardleehl7097** [comment]
> Is the first argument you are passing to the RPC the dummy value, i.e. a string of `"*"`?

I didn't pass any argument to the RPC when starting bitcoin server.

**Comment by luke-jr** [comment]
Note that accounts *are* going away in 0.18 (they're already gone in git master), so you should really be working to migrate away from them...

Are you passing `--deprecatedrpc=accounts` to bitcoind *when starting*? You *do* need to do that when starting if you want to use accounts for now.

**Comment by edwardleehl7097** [comment]
If I remove —deprecatedrpc=accounts, the error still showing.

**Comment by MeshCollider** [comment]
Could you please show us exactly what your RPC call is?

**Comment by MeshCollider** [comment]
Closing this because there's no way to tell if there is something wrong without more information, please reopen if this is a legitimate bug

**Comment by dmitriy79** [comment]
RPC Error: error -8: label argument must be a valid label name or "*".
