### ISSUE TITLE
Build error on FreeBSD: 'recompile with -fPIC'

### ISSUE THREAD

**Issue by murrayn** [bitcoin/bitcoin#14616]
Build on FreeBSD fails with:

```
  CXXLD    bitcoind
/usr/bin/ld: libbitcoin_util.a(libbitcoin_util_a-sync.o): relocation R_X86_64_TPOFF32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
libbitcoin_util.a: could not read symbols: Bad value
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

FreeBSD 11.2, but I've had it fail on earlier versions as well.

config.log is here: 

`https://0bin.net/paste/epcDXoNlXiwxyYzG#a-072U7z83TRocrB1f7NIQ3U656RVwinqBQMKti9ful`

**Comment by murrayn** [comment]
As a workaround, appending '-fPIC' to HARDENED_LDFLAGS and PIE_FLAGS in both `Makefile `and `src/Makefile` worked for me.

**Comment by MarcoFalke** [comment]
FreeBSD is supported now.

Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by murrayn** [comment]
Yes, it is still an issue (FreeBSD 11.3). To reproduce, just the usual:

```
$ ./autogen.sh
$ ./configure [...]
$ gmake check

```

**Comment by MarcoFalke** [comment]
FreeBSD 12.1 works just fine:

https://cirrus-ci.com/task/6384853019000832

**Comment by MarcoFalke** [comment]
I also remember that this used to work on freeBSD 11.3. Are you sure this is not a local issue? Is the failure reproducible on a fresh machine?

**Comment by fanquake** [comment]
FWIW I don't see any issues when building master with Clang 8 inside a FreeBSD 11.3 VM (vagrant). @murrayn can you provide any more info?

**Comment by murrayn** [comment]
@fanquake Interesting. I just built on a new FreeBSD 12.1 VM with no issues as well.
