### ISSUE TITLE
Misplaced instructions in READMEs?

### ISSUE THREAD

**Issue by merland** [bitcoin/bitcoin#14639]
Some of the README contents in **doc/** seems to be misplaced, and I suspect it is an heritage from before QT was merged upstream. Mainly I'm thinking about a few instances of _Unpack the files into a directory, and then..._ (and similarly) and also the entire file **doc/README_windows.txt**.

There may be reasons for this that I don't know about. However, in my opinion, all instructions related to running an already built version of Bitcoin Core belong on bitcoincore.org only, not duplicated (poorly) in the developer documentation. Except for maybe the last line of the build instructions.
The README already links to the releases page, which is nice. 

Is this about right? If so, I'd be happy to supply a related PR.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
