### ISSUE TITLE
how to check for received payment? 

### ISSUE THREAD

**Issue by Viral** [bitcoin/bitcoin#14643]
sorry, I tried asking elsewhere and got zero response so I'm coming here... how should I be checking my bitcoind for received payments on my website? right now I do this from node.js:

```
rpc.call('getreceivedbyaddress', [ address, 0 ], (error, result) => {
// do stuff with result
}
```

how long should this take to alert me to a payment with 0 confirmations? is there a better/more efficient way to check for a transaction to an address in my wallet? I'm using Bech32 addresses. I've read the developer documentation about 5 times and this is the best I could come up with.... thank you!

**Comment by sipa** [comment]
This is not a support forum. For questions about usage, try https://bitcoin.stackexchange.com.

**Comment by Viral** [comment]
I asked there, no one responded. How the fuck do you expect people to adopt Bitcoin when such questions are ignored
