### ISSUE TITLE
error code: -28 after upgrade, non an issue, just a hint

### ISSUE THREAD

**Issue by stefanomarty** [bitcoin/bitcoin#14642]
I'm running a full node on Debian jessie. After upgrading from 0.16.3 to 0.17.0.1 I was getting this message from the daemon:

```
$ bitcoin-cli getblockchaininfo
error code: -28
error message:
Verifying blocks...
$
```

It lasted for a couple of hours. I'm not an expert, and I didn't remember such a message after the previous upgrades. It was taking a lot of time, so I was concerned about possible errors or misconfigurations. It later finished and I could see the blockchain info again.

I'd suggest to complete the above message with something like this:

```
error code: -28
error message:
Verifying blocks...
Checking block N of M
Please wait until the verification is complete.

```
so that the user can check the progress of the verification and be sure the daemon is not stuck. Just my 2 cents, thanks.

**Comment by IvanThinking** [comment]
Agree. Some sort of indication that something is actually happening would be wonderful. My raspberry pi lightning node started acting up the other day and I now have this message as I restart it. No big deal, but it might be in this state for days if it needs to get a lot of new blocks so...

**Comment by MarcoFalke** [comment]
You can get the progress with `tail debug.log`.

The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
