### ISSUE TITLE
Compilation warning on Fedora release 28 

### ISSUE THREAD

**Issue by LitecoinZ** [bitcoin/bitcoin#14640]
Compiling on Fedora release 28 I have the following warning:

```
In file included from bench/prevector.cpp:6:
./prevector.h: In instantiation of ‘void prevector<N, T, Size, Diff>::fill(T*, ptrdiff_t) [with unsigned int N = 28; T = nontrivial_t; Size = unsigned int; Diff = int; ptrdiff_t = long int]’:
./prevector.h:340:9:   required from ‘void prevector<N, T, Size, Diff>::resize(prevector<N, T, Size, Diff>::size_type) [with unsigned int N = 28; T = nontrivial_t; Size = unsigned int; Diff = int; prevector<N, T, Size, Diff>::size_type = unsigned int]’
bench/prevector.cpp:47:13:   required from ‘void PrevectorClear(benchmark::State&) [with T = nontrivial_t]’
bench/prevector.cpp:102:1:   required from here
./prevector.h:205:21: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct nontrivial_t’; use assignment or value-initialization instead [-Wclass-memaccess]
             ::memset(dst, 0, count * sizeof(T));
             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
bench/prevector.cpp:12:8: note: ‘struct nontrivial_t’ declared here
 struct nontrivial_t {
        ^~~~~~~~~~~~
```

$ gcc --version
gcc (GCC) 8.2.1 20181011 (Red Hat 8.2.1-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ld --version
GNU ld version 2.29.1-23.fc28
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ g++ --version
g++ (GCC) 8.2.1 20181011 (Red Hat 8.2.1-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Could someone help me to solve this warning.

Thanks

**Comment by MarcoFalke** [comment]
The warning is implemented in the C++ front end and runs without the benefit of any sort of constant propagation or dead code elimination, so there is no way to avoid it in ordinary conditional statements.

In C++ 17 and later the warning can be avoided by using the if constexpr statement:

```
  if constexpr (std::is_trivial<T>::value)
    memset(val, 0, sizeof(T);
  else
    *val = T();
```

In older C++ versions it can be avoided by dispatching to different implementation functions at compile time.

In any event, the preferred way to zero-initialize an object is by making use the appropriate initialization form.   It's safer and easier for compilers to analyze both to detect bugs and to emit efficient code (sometimes more efficient than memset), so I would recommend adopting it in favor or raw memory functions even for trivial types.

Source: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84656#c1
