### ISSUE TITLE
Can't use signrawtransaction in the new version

### ISSUE THREAD

**Issue by jarven-zhang** [bitcoin/bitcoin#14645]
after I update the latest version of bitcoin core (0.17), I can't use "signrawtransaction " to signe my tx.
my cmd is this
```
bitcoin-cli -rpcuser=xxx -rpcpassword=xxx -rpcport=xxx signrawtransaction \
02000000019ea1e1eb2b6d8fca57bb99e5747f2e3446b7aac64c1147f389c025d0af155a9e0000000000ffffffff02a00f00000000000017a914bee24fd1587112a9ab41b202fc2c01e1de59b47e87a87811000000000017a91477c56ac5820aaa6c667cc4856baad24e462a46748700000000
```
the log is
```
error code: -32
error message:
signrawtransaction was removed in v0.18.
Clients should transition to using signrawtransactionwithkey and signrawtransactionwithwallet
```

**Comment by sipa** [comment]
> Clients should transition to using signrawtransactionwithkey and signrawtransactionwithwallet

**Comment by jarven-zhang** [comment]
> > Clients should transition to using signrawtransactionwithkey and signrawtransactionwithwallet

it's the new change, right? I mean , I can use "signrawtransaction" in 0.16

**Comment by sipa** [comment]
Yes, `signrawtransaction` was deprecated in 0.17, and is now removed for 0.18.

In the new code, you need to use `signrawtransactionwithkey` or `signrawtransactionwithwallet`. Look up the documentation for those RPC calls, and decide which one you need instead.

**Comment by jarven-zhang** [comment]
> Yes, `signrawtransaction` was deprecated in 0.17, and is now removed for 0.18.
> 
> In the current version, you need to use `signrawtransactionwithkey` or `signrawtransactionwithwallet`. Look up the documentation for those RPC calls, and decide which one you need instead.


> Yes, `signrawtransaction` was deprecated in 0.17, and is now removed for 0.18.
> 
> In the current version, you need to use `signrawtransactionwithkey` or `signrawtransactionwithwallet`. Look up the documentation for those RPC calls, and decide which one you need instead.

Thanks !
