### ISSUE TITLE
Error when building binary files under Windows 64/32 bit

### ISSUE THREAD

**Issue by progof** [bitcoin/bitcoin#14652]
Hello,

I collect Bitcoin client under Windows 64/32 and an error occurred.

Staging miniupnpc...
Postprocessing miniupnpc...
Caching miniupnpc...
copying packages: native_ccache native_protobuf boost openssl libevent zeromq qrencode protobuf zlib qt bdb miniupnpc
to: /root/bitcoin/depends/x86_64-w64-mingw32
bash: ./configure: No such file or directory

I tried to collect on ubunt 14.04; 16.04; 18.04 64 bit

**Comment by fanquake** [comment]
If you've just finished a depends build, you need to move out of the depends directory before running autogen and/or configure. i.e:
```
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
```

**Comment by MarcoFalke** [comment]
Please share exact steps to reproduce if @fanquake's suggestion doesn't work.

**Comment by progof** [comment]
I understood at what stage I made a mistake, but everything is already work.
@fanquake's Thank :)
