### ISSUE TITLE
fundrawtransaction add inputs bug

### ISSUE THREAD

**Issue by n0n0n0n0** [bitcoin/bitcoin#14656]
According to description of rpc method: "Add inputs to a transaction until it has enough in value to meet its out value."

What i have:
- trying to send **5000** satoshis
- have thousand of unspent inputs in wallet

Steps:
- i'm calling createrawtransaction with empty inputs and my address-amount output
- use fundrawtransaction to fill needed amount
- to check that use decoderawtransaction

so, the transaction bitcoind build is https://tchain.btc.com/bfedf6fb29b699bf57573af4ebee370f48f7153015bb7110fa61fbb90ed0b072

uhm i see tons of inputs with amount > i wanted to send, fee is only **2073** so any of input with 10k satoshi was enough

so the final question, how it should work? according to description "until it has enough in value" it should take only one input from example above, but not so many.

**Comment by promag** [comment]
Could you specify the software version used?

**Comment by n0n0n0n0** [comment]
2018-11-06T04:00:55Z Bitcoin Core version v0.17.0.0-ge1ed37edaedc85b8c3468bd9a726046344036243 (release build)

**Comment by sipa** [comment]
That's perfectly normal. The coin selection algorithm uses a heuristic which doesn't necessarily result in the smallest number of inputs.

**Comment by n0n0n0n0** [comment]
If so i need to correct description, i expected behaviour as it was written, but got a lot of inputs.
Anyway i still cant understand what the point of adding so many inputs and make transaction bigger if we have input with enough coins.

**Comment by sipa** [comment]
@n0n0n0n0 Coin selection is a very difficult problem. It's not just trying to minimize cost right now, but also tries to avoid ending up with too many tiny outputs later (which would be costly to spend in the future). Further there are privacy considerations, long-term UTXO growth considerations on the network, and last but not least implementation complexity. It doesn't always find the best solution, but very often it's a good one.

**Comment by MarcoFalke** [comment]
If you want to optimize the input selection for a specific transaction, you might want to manually select the inputs.

**Comment by promag** [comment]
@sipa agree in updating `fundrawtransaction` description? Maybe change `Add inputs to a transaction until it has enough in value to meet its out value` to `Add inputs to a transaction to at least meet its out value`?
