### ISSUE TITLE
c++ linter instructions

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#14676]
After dozens of nits from @practicalswift I decided to bite the bullet and figure out how to get a c++ linter running in my IDE. I haven't figured it out yet, but I took some notes... Can add to developer docs later:

## Command line:

```sh
...  the_file_you_worked_on.[h/cpp]
```

## Atom

Install [linter-gcc](https://atom.io/packages/linter-gcc) and its dependencies.

Create a new file `.gcc-flags.json`  with the following:

```json
{
  "gccIncludePaths": "src"
}
```

TODO:
* figure how to add dependencies to include path and/or how not to duplicate that effort (call `make`?)
* add `.gcc-flags.json` to project or to `.gitignore` in the PR along with these instructions

### macOS specific

Install `gcc` via Homebrew: `brew install gcc`, and point to that binary in the GCC Executable Path setting: `/usr/local/Cellar/gcc/8.2.0/bin/g++-8`

## [other editor]

**Comment by MarcoFalke** [comment]
I think @fanquake and @ryanofsky brought up that `make check` could run the linters.

**Comment by Sjors** [comment]
That seems a little slow for inside an editor though, but it's a start.

**Comment by fanquake** [comment]
@Sjors Which linter are you setting up? `clang-tidy`?

**Comment by Sjors** [comment]
@fanquake whatever https://atom.io/packages/linter-gcc uses under the hood, though there are [other linter packages](https://atomlinter.github.io) for Atom too.

**Comment by Sjors** [comment]
@practicalswift can explain what commands and tools you're normally using to find all these nits? I'm assuming you're not a bot yourself and can spot these things instantly through AI magic :-)

**Comment by fanquake** [comment]
@Sjors I've started writing some notes on using Clang tools, such as `clang-tidy` and `clang-format`, on macOS. Available here: https://github.com/fanquake/core-review/blob/master/clang-tools.md.

**Comment by practicalswift** [comment]
@Sjors I'm using a wide range of tools of which some are open source, some are commercial and some are homegrown. I've written my own infrastructure for handling/normalising/triaging the results from these tools.

But generally I would recommend simply starting with what Clang provides: `clang-tidy` and the Clang Static Analyser. That will give the most bang for the buck to start with :-)

@fanquake's notes in https://github.com/fanquake/core-review/blob/master/clang-tools.md seems like a good start.

**Comment by practicalswift** [comment]
@Sjors If you're interested in static analysis generally I can recommend Gerard Holzmann's presentation on how NASA's Jet Propulsion Laboratory made use of static analysis during the Mars Curiosity software development project:
* https://vimeo.com/84991949

Unrelated to the video, but NASA's Software Verification and Validation unit is doing some really interesting _sound_ static analysis work.

Tax dollars well spent!

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
