### ISSUE TITLE
bitcoin-qt won't launch, no clear errors

### ISSUE THREAD

**Issue by ak1n** [bitcoin/bitcoin#14675]
### Issue
Bitcoin-qt will not launch, whether called from command line (`bitcoin-qt`) or via desktop launcher. The process does not terminate but hangs without clear error in CLI or journal logs.

### Expected behavior
Bitcoin launching and displaying graphical interface (or failing with error messages/output).

### Reproducibility
Add bitcoin PPA then attempt to launch bitcoin as above.

### Software Setup
* software version: 0.17.0 (cosmic2)
* installation method: via bitcoin PPA

### Hardware Setup
* OS: Ubuntu 18.10 (new install)
* Hardware: Purism Librem15

### Additional Information
Similar phenomenon on Arch linux that has been attributed to qt/openssl bug:
* https://github.com/bitcoin/bitcoin/issues/14359
* https://bugs.archlinux.org/task/60235?project=5&string=bitcoin-qt

No debug information to present.

Please advise if specific additional information would be of utility.

EDIT: for formatting

**Comment by MarcoFalke** [comment]
> software version: 0.17.0 (cosmic2)

Since you build from source, you could try to build from 1e49fe450dbb0c258776526dba3ee583461d42ff, which is unfortunately not yet tagged in a release, but fixes the issue you describe here.

An alternative would be to compile the dependencies (including qt) from `./depends`.

**Comment by MarcoFalke** [comment]
Sorry, I was linking to the HEAD of the 0.17 branch. You can see more commit here: https://github.com/bitcoin/bitcoin/commits/1e49fe450dbb0c258776526dba3ee583461d42ff

**Comment by ak1n** [comment]
Thanks, I presume you're referring to this: https://github.com/bitcoin/bitcoin/commit/b0e88b89149f2aaf7c2eb23524655461214130ee

Unless I'm missing something seems like this breaks bitcoin core qt on most modern platforms. Thus hope this gets released/tagged soon. Thanks for the response and clarification.

**Comment by kyegupov** [comment]
this is pretty shocking: the official binary has been borked on many platforms - and badly, with zero indication of the nature of the problem. Why is this closed?! @MarcoFalke , do you know is there any ETA for a release?

**Comment by JavierRSobrino** [comment]
Checkout v0.17.0.1 doesn't work too on Fedora 29.

**Comment by MarcoFalke** [comment]
This was fixed in v0.17.1
