### ISSUE TITLE
Why did not return?

### ISSUE THREAD

**Issue by xsdxf** [bitcoin/bitcoin#14695]
I use bitcoind -daemon -datadir=/mydata/btc/storage -rpcport=1234 to start BTC wallet.

and use code: as follows (python)

import requests
params={"method": "GetBestBlockHash","params": [],"id": "foo"}
url="http://127.0.0.1:1234"
print(requests.post(url=url,json=params).text)

but no return

**Comment by xsdxf** [comment]
and Now, how much space is needed to store all of them?
BTC block data

**Comment by sipa** [comment]
The name of the RPC you're looking for is `getbestblockhash`, not `GetBestBlockHash`.

This is not a support forum. For questions about usage, try https://bitcoin.stackexchange.com.
