### ISSUE TITLE
docs: Windows build docs are missing `make deploy` 

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#14699]
When building for Windows (using `doc/build-windows.md`), I discovered the following steps were necessary but undocumented, in order to generate the installer:
```
sudo apt install nsis
make deploy
makensis share/setup.nsi
```

**Comment by LucianaMarques** [comment]
Hi there, I'd like to work on this. Is there any PR on this already?

**Comment by fanquake** [comment]
@LucianaMarques no, feel free to make the changes and open one.

**Comment by LucianaMarques** [comment]
@fanquake [pull request](https://github.com/bitcoin/bitcoin/pull/14744) opened! thanks
