### ISSUE TITLE
unlock the wallet just by clicking into the locker on the bottom right

### ISSUE THREAD

**Issue by douglasdeodato** [bitcoin/bitcoin#14703]
Will be possible to implement that for users with no much Knowledge in programing ?

unlock the wallet just by clicking into the locker on the bottom right, after the click shows to the user a window to put the password and unlock the wallet.
![step 1](https://user-images.githubusercontent.com/993318/48300303-e9f88700-e4c1-11e8-92b3-54d384e68c1f.jpg)

or by clicking in settings, show to me a option to click inunlock the wallet put the password and unlock?
![step2](https://user-images.githubusercontent.com/993318/48300339-6b501980-e4c2-11e8-8fd5-b6fc283a9890.jpg)

like that will be much helpful for people who has a lot special characters in the password to unlock.

**Comment by MeshCollider** [comment]
An attempt at implementation of a similar concept was done here #12149 but closed due to inactivity. 

Related comment: 
>Not sure if this is a desirable concept (keeping the wallet unlocked for unlimited time)... especially not with informing the user about the possible consequences / ramification.

**Comment by kristapsk** [comment]
Why would ordinary user want that? You are asked for wallet passphrase when trying to send funds if wallet is locked.

**Comment by meshcollider** [comment]
Closing this because it seems unwanted
