### ISSUE TITLE
Linter errors for unrelated files on local repo but not on bitcoin/bitcoin

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#14709]
I got a weird error with linters for files I haven't touched on my repository, but the error does not appear in the bitcoin repository. Compare

https://travis-ci.org/kallewoof/bitcoin/jobs/453819495 (linter failure)
https://travis-ci.org/bitcoin/bitcoin/builds/453819871 (no linter failure)

It seems to dislike the regexp in 
```Python
    match = re.search('^\+\+\+\ (.*?/){%s}(\S*)' % args.p, line)
```
inside `clangformat-diff.py`, among other things.

The PR in question is here: https://github.com/bitcoin/bitcoin/pull/13541

As you can see, I am not touching any of the files being complained about.

**Comment by AkioNak** [comment]
@kallewoof It seems the versions of flake8 are different from each other.
- 3.6.0 -> linter failure
- 3.5.0 -> no linter failure 

I don't know why travis select these version, but It reproduced on my local enviroment (macos 10.13.6).

**Comment by kallewoof** [comment]
It seems `.travis/lint_04_install.sh` explicitly installs flake8 3.5.0, so that should not be the issue.

**Comment by kallewoof** [comment]
Rebuilding did not reproduce the issue. I'm neutral on leaving this open for further investigation or closing it.

**Comment by MarcoFalke** [comment]
The travis pull request builds run against a merge commit that includes current master and the pull request patch, they don't run on the branch you pushed to your repository. So the travis builds run different program versions and report different results.

**Comment by kallewoof** [comment]
@MarcoFalke First time I heard of this. Thanks for the heads up.
