### ISSUE TITLE
error code: -28 error message: Loading block index...  

### ISSUE THREAD

**Issue by lx495707690** [bitcoin/bitcoin#14717]
I haven't started bitcoin server in a long time. 
When I started bitcoin server today,  and run "bitcoin-cli -getinfo"  always show me  "error code: -28 error message: Loading block index...".
Then after about 10s, i check the progress by "ps aux | grep bitcoind", i didnot see the bitcoin progress, i thought the server had been close.. 

I repeat the above operation , but still the same error..

**Comment by cryptozeny** [comment]
you have to wait to complete loading block index. it takes sometimes over a week. its normal i think. you can check the status with `-printtoconsole` option. and since 0.16.3 `getinfo` is deprecated.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
