### ISSUE TITLE
-onion does not default to -proxy

### ISSUE THREAD

**Issue by qubenix** [bitcoin/bitcoin#14722]
According to help menu:

>-onion=<ip:port>
       Use separate SOCKS5 proxy to reach peers via Tor hidden services, set
       -noonion to disable (default: -proxy)

I would expect that if `-proxy` is set, but `-onion` is not, `-proxy` setting would be used for onion connections.

Instead, according to `getnetworkinfo`, the default Tor port (`127.0.0.1:9050`) is listed for onion, but ipv{4,6} both have the `-proxy` setting. I inspected the traffic and saw that indeed it is not honoring my `-proxy` setting.

Bitcoin Core Daemon version v0.17.0.1-9e87d82e7

OS: Qubes OS, Whonix 14 VM

**Comment by laanwj** [comment]
This is really strange. I have a hard time thinking of where that proxy even comes from.
I think tor control might be erroneously overriding the proxy. Can you try running with `-listenonion=0`?

**Comment by qubenix** [comment]
`listenonion=0` does use my custom proxy setting for onions.

It would be interesting to me if Tor control was to blame as I just recently created [Whonix's onion-grater profile for bitcoind](https://github.com/Whonix/onion-grater/blob/master/usr/share/onion-grater-merger/examples/40_bitcoind.yml).

Here is the comms with Whonix's control port:

```
PROTOCOLINFO 1
250-PROTOCOLINFO 1
250-AUTH METHODS=NULL
250-VERSION Tor="0.3.4.8 (git-5da0e95e4871a0a1)"
250 OK
AUTHENTICATE
250 OK
ADD_ONION NEW:RSA1024 Port=18333,127.0.0.1:18333
250-ServiceID=hzyiu6fm6rdkifa7
250 OK
```

**Comment by qubenix** [comment]
I just found this:

https://github.com/bitcoin/bitcoin/blob/2e8f9dc2bbb1200218feaf80344d35dca1cd6b25/src/torcontrol.cpp#L525-L532

**Comment by roshii** [comment]
For the record, I do face similar issue running v0.18.1 and as described in https://github.com/bitcoin/bitcoin/pull/16940

**Comment by nyxnor** [comment]
Also using Whonix. I believe this was solved. From `-getinfo` or `getnetworkinfo` I see the proxies set correctly to the different networks.
