### ISSUE TITLE
Feature request: Settling offline transactions.

### ISSUE THREAD

**Issue by chainhead** [bitcoin/bitcoin#14730]
# Use Case #
My use case is around a scenario where both customer and merchant possess offline wallets with a balance that has had confirmation on the blockchain.

 1. To begin with, let us say that, the merchant and the buyer's wallets show balances of 20 BTC and 10 BTC respectively. These balances are the one that are confirmed on the block-chain.
 2. Then, let there be multiple transactions between the merchant and buyer such that the balance is always updated locally in the wallets only.
 3. All of the transactions, in 2 above, happen in an offline mode; i.e. no access to network. The period of no access can run into days.
 4. Sometime, in the future, when either/both of the wallets are online, all the offline transactions are published to blockchain and are confirmed.

## Blockchain Sync ##
There are two things that can happen at this point. 

First, the wallets are so secure that, all updates (credits and debits) happen locally without ever having to 'sync' up with the blockchain. The only time the wallets may sync with blockchain is to post the transactions and their sequence; and, also to update their wallet with the credits that happened since the last time the wallet went online. Or, regulatory pressure requires posting transaction data every set frequency.

Second, all credit updates are made to the wallets via the blockchain. This requirement is enough motivation to seek network connectivity; even if it is once in a week or fewer.

### Question ###
In either case, we are looking at a scenario, where a value, confirmed by blockchain, is used in transactions offline to be confirmed online later. How do we implement this?

## Analogy ##
Bus conductors may issue tickets with an offline machine to passengers who board the bus at various points throughout the journey. When the bus reaches its destination, the machine is used at the depot to arrive at a list of tickets sold and the amount collected thereof. Thus, this is an example of an offline transaction where transactions are 'settled' when 'connectivity' is eventually available.

Spawned off of: https://bitcoin.stackexchange.com/a/41356/6975
Originally asked here: https://bitcoin.stackexchange.com/q/50568/6975

**Comment by sipa** [comment]
The description is vague, but PSBT may be what you're looking for (see the doc/psbt.md file and BIP174).

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
