### ISSUE TITLE
blockchain and address_url testnet

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [bitcoin/bitcoin#14743]
in my code I have this to get the blocks and addresses info, my question is how can I get the same thing but using testnet? I tried https://www.blockcypher.com api but did not work, any help? thank you.

  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}

**Comment by fanquake** [comment]
This is not a support forum for blockchain.info. When using bitcoin core, you can pass the `-testnet` flag to `bitcoind` or `bitcoin-qt` to use the testnet chain.

**Comment by openbooknoobdeveloper** [comment]
sorry @fanquake  it is supported yes , have u tried isert this on your browser?

what I want is get the transactions and address info from their in my website.

it is already working but just with btc main chain

I am using testnetchain already: bitcoin.conf testnet=1


understand what I want archive?
