### ISSUE TITLE
No more ways to mine a fork of bitcoin?

### ISSUE THREAD

**Issue by KryptoFranc** [bitcoin/bitcoin#14745]
A huge part of the success of Bitcoin is because it is the base of most altcoin existing. Now the Bitcoin Core team seems to stop supporting forks and altcoin by removing important piece of code, that could be left here and would greatly help new coins creation.

No more CPU mining, no more GPU mining, no more RPC mining, no more solo mining = no more forks and new coins build on the top of Satoshi's work!

Now you MUST use a pool to mine Bitcoin.

I understand that Bitcoin has become too expensive to be solo mined, but what about people learning or doing altcoins? No more legacy?

Because only the latest versions of Bitcoin Core are running with the latest OS, if you get  version 0.12 that is pre CPU solo removal, it won't compile because autogen.sh is incompatible.

So is the goal of the Bitcoin Core team to become an elitist projet that can no longer be forked?

Because if you fork Bitcoin as it is now, there is no way that your fork can be mined. So you are killing the possibility of new coins being created by a fork of the latest version of Bitcoin Core?

Why removing these part of the code, I don't think Satoshi would like to see his coin being stripped from pieces of code that are indispensable if you want to create a new coin based on Bitcoin.

After the genesis, you need to mine right? 

I want to know what is the idea of the Bitcoin core team when they are removing important piece of code that are blocking the possibility to create new coins based on their work.

Thanks

**Comment by MarcoFalke** [comment]
Bitcoin Core is open source and all commits are preserved in the git history. If you need whatever feature was removed so badly, but can't figure out how to revert that commit on a recent branch or master, then maybe you shouldn't "create a new coin".

Also, the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by MarcoFalke** [comment]
The internal miner could only ever be used for testing due to it's inherent performance limitations. So there is really no reason to keep it around in the code base of `bitcoind` today and pay the maintenance cost. Note that you can still mine blocks with `bitcoind` (see https://bitcoincore.org/en/doc/0.17.0/rpc/generating/generatetoaddress/) or use the miner written in python for testing:

https://github.com/bitcoin/bitcoin/blob/35739976c1d9ad250ece573980c57e7e7976ae23/test/functional/test_framework/messages.py#L654-L659

These should suffice for testing purposes, but if you wanted to do anything else, you'd be better off picking one of the heavily optimized open-source miners.

**Comment by KryptoFranc** [comment]
My question is more a political question.
Satoshi did a genius piece of code that should be preserved, at least its features. It should be improved but not amputated.
Everyone who is doing a fork is doing a Bitcoin newborn and should have the same features that Satoshi's work provided to us.
Of course I am doing my own stratum pool, but removing features from Bitcoin is not the way to help the Crypto ecosystem to develop and improve.
Because of these problems most altcoins are using code 4-5 years old, and do not benefit of all the new features created by the Bitcoin core team. The Bitcoin core team is leading the crypto research, and should provide the features that Satoshi intended us to have when we fork and start a coin from scratch using his code.
Bitcoin should federate all the new features, have all the encryption algo included as option etc... that mean it should extend and represent the core of any crypto money instead of removing feature and becoming a coin difficult to fork, difficult to mine for students and people who cannot afford to have a stratum mining dedicated server to learn how the blockchain is working.
That's my opinion, and I hope that in the future, Bitcoin core will preserve the original features of Satoshi Nakamoto,  and will be preserved intact for the sake of learning.
Thanks for your time and explanation though, I appreciate.

**Comment by luke-jr** [comment]
> A huge part of the success of Bitcoin is because it is the base of most altcoin existing.

No, altcoins do nothing to contribute to Bitcoin's success. In fact, the only effect they have is to make Bitcoin look bad by association with such scams.

> Now the Bitcoin Core team seems to stop supporting forks and altcoin

They have never been supported.

> Now you MUST use a pool to mine Bitcoin.

That's not true. `getblocktemplate` is still supported and functional.
