### ISSUE TITLE
Make command Error: Makefile:3949: recipe for target 'bench/bench_bitcoin' failed

### ISSUE THREAD

**Issue by aaroncatalano** [bitcoin/bitcoin#14748]
OS: Ubuntu 18.
Execute Make :throws the following exception:

 CXX      bench/bench_bench_bitcoin-coin_selection.o
  CXXLD    bench/bench_bitcoin
/usr/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 internal error, aborting at ../../bfd/merge.c:908 in _bfd_merged_section_offset

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
Makefile:3949: recipe for target 'bench/bench_bitcoin' failed
make[1]: *** [bench/bench_bitcoin] Error 1
make[1]: Leaving directory '/home/aaron/Bituscloud/bitcoin/src'
Makefile:10374: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by fanquake** [comment]
@aaroncatalano How much memory is available on this machine during compilation, there's a chance it's running out. Otherwise, this doesn't look like an issue with Bitcoin Core, rather with `ld`.

**Comment by fanquake** [comment]
@aaroncatalano Please re-open if you can provide more information.
