### ISSUE TITLE
getrawmempool true RPC call is O(n^2)

### ISSUE THREAD

**Issue by jhoenicke** [bitcoin/bitcoin#14765]
When the mempool fills the verbose `getrawmempool` RPC call gets really slow.  It can take minutes for >100k transactions in the mempool.

The culprit is the univalue library.  Objects are implemented as a big list, but the library checks for duplicate keys.  So inserting n key-value pairs into an object takes O(n^2).

Possible fixes:

- Improve univalue library by using linked hash maps.
- change the RPC output format of getrawmempool to use a list of objects, instead of an object of objects.  But this breaks existing code.
- hack the library to be able to skip the duplicate check.

**Comment by achow101** [comment]
Have you opened an issue with the upstream repo about this?

**Comment by promag** [comment]
@achow101 I don't see why we need the duplicate key check. I'd be surprised if there were duplicate keys.

**Comment by jnewbery** [comment]
> Have you opened an issue with the upstream repo about this? This seems like something best fixed upstream rather than here.

Bitcoin Core uses https://github.com/bitcoin-core/univalue. Could update it there and then offer a PR upstream to jgarzik/univalue.
