### ISSUE TITLE
leveldb/libleveldb.a Error 1

### ISSUE THREAD

**Issue by VtpVlan-oo7** [bitcoin/bitcoin#14769]
if anyone solved it please give me a favour ASAP !!

1: error: src/leveldb/libleveldb.a] Error 1

**Comment by fanquake** [comment]
@VtpVlan-oo7 You need to provide more information. i.e, the items listed in the [issue template](https://raw.githubusercontent.com/bitcoin/bitcoin/master/.github/ISSUE_TEMPLATE.md).

**Comment by VtpVlan-oo7** [comment]
@fanquake  here is screenshot of that please take a look.

![virtualbox_windows _22_11_2018_10_08_57](https://user-images.githubusercontent.com/31241756/48882130-c4af3580-ee3e-11e8-87c5-22b21fdc56fd.png)

**Comment by MeshCollider** [comment]
What is beepmagnet? That is not bitcoin core code, please don't use the issue tracker here...

**Comment by VtpVlan-oo7** [comment]
@MeshCollider  Thanks for  your fast reply,  actually i am a student and new at cryptocurrency development . Beepmagnet is just a cryptocoin which i took to learn for making a window wallet , if i am going to build some other cryptocoin likewise in bitcoin also then also i face same problem .  so can you help me please to find out a way to short out this kind of leveldb problem !!!
