### ISSUE TITLE
Sending ~200KB to bitcoind via RPC causes ECONNABORT

### ISSUE THREAD

**Issue by nao20010128nao** [bitcoin/bitcoin#14767]
# Summary
Sending ~200KB to bitcoind via RPC causes `ECONNABORT` for its connection.      
Such operation cannot be possible via `bitcoin-cli` due to Linux's limitation, so it has to be done via HTTP libraries.    
Confirmed on `sendrawtransaction`.

# Expected
If you did `sendrawtransaction <A Transaction that is very close to the weight limit>`, it should return transaction hash.    
Any other calls like `getwalletinfo` should work too.

# Actual
`ECONNABORT` occured for `sendrawtransaction <A Transaction that is very close to the weight limit>`.    
Any other calls like `getwalletinfo` worked normally.

# Steps to reproduce
- Enable RPC
- Try example at `Expected` field.
  - To make such transaction, you may use 1 input and set 2910 outputs.
- `ECONNABORT` occured.

# Bitcoin Core version
`0.17.0.1`, with binaries at website.

# Computer information
```
$ uname -a
Linux *** #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by promag** [comment]
@nao20010128nao Mind sharing the client used?

I'll try to reproduce and fix.

**Comment by MarcoFalke** [comment]
Doesn't sound like an issue with Bitcoin Core

**Comment by MarcoFalke** [comment]
Corresponding error in python is `OSError: [Errno 7] Argument list too long` fyi

**Comment by Sjors** [comment]
For Google reference, try something like this:

```
cat transaction.txt | bitcoin-cli -stdin sendrawtransaction
```
