### ISSUE TITLE
bumpfee fails with "Transaction does not have a change output" when setting label for newly generated raw change address 

### ISSUE THREAD

**Issue by equalgeek** [bitcoin/bitcoin#14773]
Issue:
The issue seems to be when you generate a new change address via "getrawchangeaddress" and setting a new label for it. When creating a new raw transaction, setting it to be replaceable, and using the new change address for one of the outputs in the raw tx. bumpfee throws an error "Transaction does not have a change output". If you do not perform the setlabel on the newly generated raw change address then bumpfee performs the "bump" correctly. 

Setup: 
v 0.17.0.1

Behavior expected:
bumpfee to notice any address in wallet as a potential "change" address or at least allowing a label to be set for being able to track specific labels being used for change addresses.

Steps to reproduce:
1. Generate new raw change address via "getnewchangeaddress"
2. Set label for newly generated raw change address to whatever you want.
2. Create raw transaction as replaceable with newly generated raw change address as one of the outputs.
3. Sign & Send tx
4. Perform bumpfee on raw txid 
5. Error "Transaction does not have a change output"

Thanks to all the devs btw, just wanted to express my appreciation for all you do

**Comment by MeshCollider** [comment]
>If you do not perform the setlabel on the newly generated raw change address then bumpfee performs the "bump" correctly.

As you correctly observe, if you add a label to an address, it is no longer considered change (change addresses are defined as those which aren't in the address book, adding a label will add it to the address book). Internal addresses can not have labels.

**Comment by promag** [comment]
Related discussion in #14724.

**Comment by MarcoFalke** [comment]
Let's continue discussion in #14724

**Comment by meshcollider** [comment]
#14724 is related but it is certainly a different issue, I don't think this has been resolved

**Comment by glozow** [comment]
no longer a problem since #15557 AFAIU, but feel free to reopen if not
