### ISSUE TITLE
rpc_bind tests failing locally for ipv6 and nonloopback

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#14792]
The following tests are failing locally here:
```
rpc_bind.py --ipv6                    | ✖ Failed  | 2 s
rpc_bind.py --nonloopback             | ✖ Failed  | 1 s
```
I haven't yet been able to investigate in depth, but I think this is caused by the changes in #14532.

**Comment by hebasto** [comment]
I can confirm that skipping #14532 commits from the current master (60b20c869f8df9a81b5080ebcbe8c9cf4e6b9d77) makes `rpc_bind.py` tests pass locally again.
