### ISSUE TITLE
How to let register born with some money 

### ISSUE THREAD

**Issue by zxt2012bs** [bitcoin/bitcoin#14807]
Everyone is born equal, so why not born with equal money?  The film "In time " tell us the evil and  cheat of treasure. But that Government still give every newborn some money. So I think Bitcoins should give every new register with some money.  And this is the only way to let your BitCoins more fascinating than US Dollars.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
