### ISSUE TITLE
--enable-debug default flags much less useful for introspection of variables

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#14830]
https://github.com/bitcoin/bitcoin/pull/13005 changed the flags from `O0` to `Og` when it can. For reasonable debugging experience I change this back, otherwise half the time I'm debugging something it's optimized out.

Would people be open to `--enable-debug-slow` or something that simply preferred `O0`?

**Comment by practicalswift** [comment]
Friendly pinging to the original author @eklitzke  :-)

**Comment by jonasschnelli** [comment]
I have the same issue when debugging with macOS 10.14 (LLVM). I'm for reverting #13005.

**Comment by luke-jr** [comment]
Get a better compiler? `-Og` is supposed to be useful for debugging...

**Comment by instagibbs** [comment]
@luke-jr if you have a list of "better compiler"s now is the time to share them
