### ISSUE TITLE
Race conditions in BerkeleyEnvironment

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#14850]
I believe we should add concurrency control to `BerkeleyEnvironment` members, especially when a wallet is created from `CWallet::CreateWalletFromFile` - the `BerkeleyDatabase` instance is added to `BerkeleyEnvironment::m_databases` without any lock held.

From https://github.com/bitcoin/bitcoin/pull/14552#discussion_r234812302.

**Comment by practicalswift** [comment]
FWIW TSan (`-fsanitize=thread`) complains about races in `BerkeleyEnvironment` when running the unit tests.
