### ISSUE TITLE
feature: Add JSON as a ZMQ output format

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#14873]
When the ZMQ interface publishes to, for example: `rawblock`, the default and only output format is as a binary / hex raw block. An option for `jsonblock` or similar could offer the deserialized version of this, as JSON, for clients that do not want to require dependency methods for interpreting raw blocks.

**Comment by promag** [comment]
Concept ACK __if__ zmq notifications are moved to a different thread and don't lock the main critical sections.

**Comment by ch4ot1c** [comment]
The discussion in the PR seemed to decide that JSON won't be served over ZMQ.

Is there still value in moving ZMQ to a background thread, as it stands?

**Comment by adamjonas** [comment]
Closing due to lack of momentum/interest. Pull requests with improvements are always welcome.
