### ISSUE TITLE
Protection From Re-Org Attacks

### ISSUE THREAD

**Issue by berkhatipoglu** [bitcoin/bitcoin#14871]
I have a solution to stop big Re-Org attacks that can caused by Selfish Mining Attacks. I'm calling it The Great Wall but name isn't important. Here is the solution;

>>>
Big financial companies like Visa etc. would do everything they can to stop Bitcoin and altcoins. That includes reorging txs with selfish mining and they can afford it. They could be doing selfish mining right now that continued for days, weeks, months or even years (even it's very unlikely) and their chain might be just 1 block longer than from ours since they might have only just a little bit more Hashing power. The worst part is we can't know this untill they share their chain to network. An attack big like this might have never happen or it might be happening right know, the real thing is we can't be sure. I was thinking about this when I got this idea. Small attacks can hurt but bigger attacks like this can totally fuck up our network. We all know what they can do with months of selfish mining.

How can we protect nodes within decentralized manner?

We need to build a wall that rejects changes after every recent 8th block (since we need last 7 blocks to changable due to sync reasons). Here is how it will work;

When a new block added to chain, the recent 8th block (since txs need 7 blocks to be confirmed) should be considered as "confirmed" by nodes and all changes that are older than 8 blocks should be automatically rejected. With this, the longer chain (reorganized/corrupted) that shared by Selfish Mining Attacker will be rejected by default by nodes if blocks (or block) that are affected by their attack are older than recent 8th block.

Since the whole network will get information from nodes with protection, the whole network would consider the chain before attack as the real chain automatically even it's the shorter chain. The longer (reorged) chain that mined with selfish mining will be a (most likely unseccessful) hard fork from Bitcoin if they choose to keep mining it. Network and community can decide that if (reorged) chain is the real chain by changing their nodes manually to reorganized chain. With this we are just actively protecting the pure chain from corrupting by attackers with an automatic protection like a wall without giving up from decentralization. The final decion is always on network and community.

This protection is only works if attackers mined more than 8 blocks without sharing with network. It would work if they mine 9 blocks but their chain is only 1 block longer than network has.

Isn't dividing the chain bad and risky?

Yes, most of the times but not always, and we don't acually divide the chain on attacks. Attackers will create their own chain instead of changing the networks. Even their fork will be better than Bcahs and other shitcoin hard forks, noone would use it. Also, if noone use their chain, they are most likely to give up from mining and they chain would die.

How is it decentralized if we block/fork the longer chain?

We block the info that is shared by Selfish Mining attacker for an active protection. We are not censoring it. Their chain will be still available, nodes and miners can decide it manually. If majority of nodes decide to choose their corrupted chain, their chain would be the real chain and the pure chain would be old chain.

How is this different from Checkpoints?

Checkpoints saves a copy of history of chain on nodes they are out of our network. This protection is automaticly blocks changes like a wall. 

What would happen to nodes that aren't online 24/7?

When it comes to offline nodes they should connect to real chain when they need to connect to network because (with adoption of this protection) majority of nodes are keeping the healty chain. Only way to their node connect to the corrupted chain is that if attackers have more nodes than the whole network (as far as I know it's way harder than have more hash power on Bitcoin). With having more corrupted nodes attackers attack would be successful.
<<<

This was my idea/theory to protect from big Re-Org attacks. Even there is a very little possibility to encounter a big attack like this we need to prevent these from happening. I think it's always better to be safe than sorry. We can argue about potantial new problems this solution can create and try to find a solution to them. We can argue about 8th block rule. I think 8th is the safest number but we can change it to which block majority wants if we need. We can argue everything about this protection.

**Comment by sipa** [comment]
This is the issue tracker for a specific implementation of the Bitcoin protocol called Bitcoin Core. This is not the place for wild ideas on how to fundamentally change Bitcoin.

**Comment by berkhatipoglu** [comment]
Even this was a long description, it was very simple change to consensus between nodes that can create a massive protection againts big attacks. Not a fundamental change. I posted this on BitcoinTalk and majority if people who replied find this useful. Isn't Bitcoin decentralized? If so how can one people decide that?

**Comment by sipa** [comment]
You're free to publish software to do this, but it won't be Bitcoin. Your consensus rules are fundamentally different, and risk diverging from the rest of the network.

**Comment by berkhatipoglu** [comment]
Thank you for your helpful comment. I though we can discuss ideas and etc. on Issues. I am sorry about this. I want to help to community and dividing it isn't a good way to do it. So, I will try the mailinglist.
