### ISSUE TITLE
[Suggestion] Warn user on backup, esp. on importprivkey

### ISSUE THREAD

**Issue by andronoob** [bitcoin/bitcoin#14874]
As far as I know, a lot of (paranoid) users followed various "cold storage tutorial" on the Internet. They may try to use Bitcoin Core to restore their fund, but, if they forget the change address, they may encounter permanent fund loss.

**Comment by MarcoFalke** [comment]
See also identical #11827 with different wording

**Comment by andronoob** [comment]
@MarcoFalke 
I think the wallet should remember backup states of every key stored within. Every time there is a key found without backup, the wallet should warn the user explicitly.

**Comment by andronoob** [comment]
Closing in favor of #17748
