### ISSUE TITLE
State of the Repo, December 2018

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#14899]
# State of the Repo Report, December 2018

## Introduction

For all fans of statistics – enjoy! 🤓

The "median open pull request" adds 39&nbsp;lines, removes 13&nbsp;lines and touches 3&nbsp;files.

The total set of open pull requests adds 42085&nbsp;lines, removes 13358&nbsp;lines and touches 1443&nbsp;distinct files.

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines introduced | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 9947&nbsp;(24%) | -1689&nbsp;(13%) | 8258&nbsp;(29%) | 138 | 9&nbsp;(3%) |
| 2 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 4239&nbsp;(10%) | -497&nbsp;(4%) | 3742&nbsp;(13%) | 51 | 11&nbsp;(4%) |
| 3 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 2782&nbsp;(7%) | -321&nbsp;(2%) | 2461&nbsp;(9%) | 70 | 22&nbsp;(8%) |
| 4 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 1853&nbsp;(4%) | -2977&nbsp;(22%) | -1124&nbsp;(-) | 72 | 12&nbsp;(5%) |
| 5 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 1793&nbsp;(4%) | -1279&nbsp;(10%) | 514&nbsp;(2%) | 33 | 5&nbsp;(2%) |
| 6 | [annanay25](https://github.com/bitcoin/bitcoin/pulls/annanay25) | 1433&nbsp;(3%) | -79&nbsp;(1%) | 1354&nbsp;(5%) | 9 | 1&nbsp;(0%) |
| 7 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 1389&nbsp;(3%) | -380&nbsp;(3%) | 1009&nbsp;(4%) | 39 | 9&nbsp;(3%) |
| 8 | [jimpo](https://github.com/bitcoin/bitcoin/pulls/jimpo) | 1368&nbsp;(3%) | -234&nbsp;(2%) | 1134&nbsp;(4%) | 26 | 4&nbsp;(2%) |
| 9 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 1346&nbsp;(3%) | -566&nbsp;(4%) | 780&nbsp;(3%) | 29 | 3&nbsp;(1%) |
| 10 | [ken2812221](https://github.com/bitcoin/bitcoin/pulls/ken2812221) | 1261&nbsp;(3%) | -376&nbsp;(3%) | 885&nbsp;(3%) | 46 | 6&nbsp;(2%) |
| 11 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 1142&nbsp;(3%) | -153&nbsp;(1%) | 989&nbsp;(3%) | 36 | 11&nbsp;(4%) |
| 12 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 1126&nbsp;(3%) | -250&nbsp;(2%) | 876&nbsp;(3%) | 37 | 9&nbsp;(3%) |
| 13 | [mgrychow](https://github.com/bitcoin/bitcoin/pulls/mgrychow) | 1083&nbsp;(3%) | -80&nbsp;(1%) | 1003&nbsp;(3%) | 25 | 1&nbsp;(0%) |
| 14 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 974&nbsp;(2%) | -43&nbsp;(0%) | 931&nbsp;(3%) | 15 | 1&nbsp;(0%) |
| 15 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 959&nbsp;(2%) | -28&nbsp;(0%) | 931&nbsp;(3%) | 18 | 1&nbsp;(0%) |
| 16 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 899&nbsp;(2%) | -685&nbsp;(5%) | 214&nbsp;(1%) | 64 | 18&nbsp;(7%) |
| 17 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 719&nbsp;(2%) | -370&nbsp;(3%) | 349&nbsp;(1%) | 42 | 13&nbsp;(5%) |
| 18 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 577&nbsp;(1%) | -41&nbsp;(0%) | 536&nbsp;(2%) | 11 | 3&nbsp;(1%) |
| 19 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 534&nbsp;(1%) | -436&nbsp;(3%) | 98&nbsp;(0%) | 22 | 4&nbsp;(2%) |
| 20 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 417&nbsp;(1%) | -9&nbsp;(0%) | 408&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 21 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 410&nbsp;(1%) | -294&nbsp;(2%) | 116&nbsp;(0%) | 25 | 11&nbsp;(4%) |
| 22 | [MeshCollider](https://github.com/bitcoin/bitcoin/pulls/MeshCollider) | 390&nbsp;(1%) | -204&nbsp;(2%) | 186&nbsp;(1%) | 9 | 2&nbsp;(1%) |
| 23 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 352&nbsp;(1%) | -174&nbsp;(1%) | 178&nbsp;(1%) | 15 | 4&nbsp;(2%) |
| 24 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 339&nbsp;(1%) | -283&nbsp;(2%) | 56&nbsp;(0%) | 33 | 1&nbsp;(0%) |
| 25 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 334&nbsp;(1%) | -95&nbsp;(1%) | 239&nbsp;(1%) | 6 | 2&nbsp;(1%) |
| 26 | [ch4ot1c](https://github.com/bitcoin/bitcoin/pulls/ch4ot1c) | 331&nbsp;(1%) | -214&nbsp;(2%) | 117&nbsp;(0%) | 13 | 4&nbsp;(2%) |
| 27 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 313&nbsp;(1%) | -34&nbsp;(0%) | 279&nbsp;(1%) | 8 | 3&nbsp;(1%) |
| 28 | [251Labs](https://github.com/bitcoin/bitcoin/pulls/251Labs) | 268&nbsp;(1%) | -87&nbsp;(1%) | 181&nbsp;(1%) | 22 | 2&nbsp;(1%) |
| 29 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 266&nbsp;(1%) | -2&nbsp;(0%) | 264&nbsp;(1%) | 2 | 1&nbsp;(0%) |
| 30 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 252&nbsp;(1%) | -31&nbsp;(0%) | 221&nbsp;(1%) | 3 | 1&nbsp;(0%) |
| 31 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 245&nbsp;(1%) | -218&nbsp;(2%) | 27&nbsp;(0%) | 44 | 11&nbsp;(4%) |
| 32 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 241&nbsp;(1%) | -185&nbsp;(1%) | 56&nbsp;(0%) | 30 | 3&nbsp;(1%) |
| 33 | [mrwhythat](https://github.com/bitcoin/bitcoin/pulls/mrwhythat) | 231&nbsp;(1%) | -12&nbsp;(0%) | 219&nbsp;(1%) | 7 | 2&nbsp;(1%) |
| 34 | [lionello](https://github.com/bitcoin/bitcoin/pulls/lionello) | 191&nbsp;(0%) | -15&nbsp;(0%) | 176&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 35 | [skeees](https://github.com/bitcoin/bitcoin/pulls/skeees) | 186&nbsp;(0%) | -156&nbsp;(1%) | 30&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 36 | [leishman](https://github.com/bitcoin/bitcoin/pulls/leishman) | 177&nbsp;(0%) | -8&nbsp;(0%) | 169&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 37 | [pstratem](https://github.com/bitcoin/bitcoin/pulls/pstratem) | 172&nbsp;(0%) | -48&nbsp;(0%) | 124&nbsp;(0%) | 5 | 1&nbsp;(0%) |
| 38 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 155&nbsp;(0%) | -68&nbsp;(1%) | 87&nbsp;(0%) | 7 | 2&nbsp;(1%) |
| 39 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 103&nbsp;(0%) | -62&nbsp;(0%) | 41&nbsp;(0%) | 5 | 4&nbsp;(2%) |
| 40 | [MapleLaker](https://github.com/bitcoin/bitcoin/pulls/MapleLaker) | 89&nbsp;(0%) | -1&nbsp;(0%) | 88&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 41 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 87&nbsp;(0%) | -69&nbsp;(1%) | 18&nbsp;(0%) | 5 | 2&nbsp;(1%) |
| 42 | [conscott](https://github.com/bitcoin/bitcoin/pulls/conscott) | 87&nbsp;(0%) | -61&nbsp;(0%) | 26&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 43 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 85&nbsp;(0%) | -62&nbsp;(0%) | 23&nbsp;(0%) | 11 | 5&nbsp;(2%) |
| 44 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 83&nbsp;(0%) | -9&nbsp;(0%) | 74&nbsp;(0%) | 5 | 1&nbsp;(0%) |
| 45 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 82&nbsp;(0%) | -39&nbsp;(0%) | 43&nbsp;(0%) | 9 | 5&nbsp;(2%) |
| 46 | [joemphilips](https://github.com/bitcoin/bitcoin/pulls/joemphilips) | 80&nbsp;(0%) | -3&nbsp;(0%) | 77&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 47 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 79&nbsp;(0%) | -3&nbsp;(0%) | 76&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 48 | [greenaddress](https://github.com/bitcoin/bitcoin/pulls/greenaddress) | 77&nbsp;(0%) | -23&nbsp;(0%) | 54&nbsp;(0%) | 9 | 1&nbsp;(0%) |
| 49 | [SuckShit](https://github.com/bitcoin/bitcoin/pulls/SuckShit) | 55&nbsp;(0%) | -8&nbsp;(0%) | 47&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 50 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 47&nbsp;(0%) | -73&nbsp;(1%) | -26&nbsp;(-) | 5 | 1&nbsp;(0%) |
| 51 | [cisba](https://github.com/bitcoin/bitcoin/pulls/cisba) | 46&nbsp;(0%) | -11&nbsp;(0%) | 35&nbsp;(0%) | 5 | 2&nbsp;(1%) |
| 52 | [marcoagner](https://github.com/bitcoin/bitcoin/pulls/marcoagner) | 40&nbsp;(0%) | -19&nbsp;(0%) | 21&nbsp;(0%) | 7 | 1&nbsp;(0%) |
| 53 | [naumenkogs](https://github.com/bitcoin/bitcoin/pulls/naumenkogs) | 40&nbsp;(0%) | -15&nbsp;(0%) | 25&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 54 | [Flowdalic](https://github.com/bitcoin/bitcoin/pulls/Flowdalic) | 27&nbsp;(0%) | -38&nbsp;(0%) | -11&nbsp;(-) | 5 | 1&nbsp;(0%) |
| 55 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2&nbsp;(0%) | 20&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 56 | [tecnovert](https://github.com/bitcoin/bitcoin/pulls/tecnovert) | 22&nbsp;(0%) | -21&nbsp;(0%) | 1&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 57 | [vii](https://github.com/bitcoin/bitcoin/pulls/vii) | 20&nbsp;(0%) | -6&nbsp;(0%) | 14&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 58 | [theuni](https://github.com/bitcoin/bitcoin/pulls/theuni) | 19&nbsp;(0%) | -8&nbsp;(0%) | 11&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 59 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 18&nbsp;(0%) | -13&nbsp;(0%) | 5&nbsp;(0%) | 4 | 1&nbsp;(0%) |
| 60 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 18&nbsp;(0%) | -10&nbsp;(0%) | 8&nbsp;(0%) | 4 | 1&nbsp;(0%) |
| 61 | [JBaczuk](https://github.com/bitcoin/bitcoin/pulls/JBaczuk) | 15&nbsp;(0%) | -16&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 62 | [jlopp](https://github.com/bitcoin/bitcoin/pulls/jlopp) | 14&nbsp;(0%) | -7&nbsp;(0%) | 7&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 63 | [valentinewallace](https://github.com/bitcoin/bitcoin/pulls/valentinewallace) | 14&nbsp;(0%) | -6&nbsp;(0%) | 8&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 64 | [GreatSock](https://github.com/bitcoin/bitcoin/pulls/GreatSock) | 11&nbsp;(0%) | -6&nbsp;(0%) | 5&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 65 | [LucianaMarques](https://github.com/bitcoin/bitcoin/pulls/LucianaMarques) | 11&nbsp;(0%) | -1&nbsp;(0%) | 10&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 66 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -10&nbsp;(0%) | 1&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 67 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 10&nbsp;(0%) | -6&nbsp;(0%) | 4&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 68 | [LeandroRocha84](https://github.com/bitcoin/bitcoin/pulls/LeandroRocha84) | 9&nbsp;(0%) | -5&nbsp;(0%) | 4&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 69 | [kristapsk](https://github.com/bitcoin/bitcoin/pulls/kristapsk) | 9&nbsp;(0%) | -22&nbsp;(0%) | -13&nbsp;(-) | 3 | 2&nbsp;(1%) |
| 70 | [romanz](https://github.com/bitcoin/bitcoin/pulls/romanz) | 9&nbsp;(0%) | -13&nbsp;(0%) | -4&nbsp;(-) | 4 | 1&nbsp;(0%) |
| 71 | [pedrobranco](https://github.com/bitcoin/bitcoin/pulls/pedrobranco) | 8&nbsp;(0%) | -3&nbsp;(0%) | 5&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 72 | [kazcw](https://github.com/bitcoin/bitcoin/pulls/kazcw) | 7&nbsp;(0%) | -9&nbsp;(0%) | -2&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 73 | [priscoan](https://github.com/bitcoin/bitcoin/pulls/priscoan) | 7&nbsp;(0%) | -8&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 74 | [sp4ke](https://github.com/bitcoin/bitcoin/pulls/sp4ke) | 5&nbsp;(0%) | -3&nbsp;(0%) | 2&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 75 | [kostyantyn](https://github.com/bitcoin/bitcoin/pulls/kostyantyn) | 4&nbsp;(0%) | -7&nbsp;(0%) | -3&nbsp;(-) | 3 | 1&nbsp;(0%) |
| 76 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 4&nbsp;(0%) | -6&nbsp;(0%) | -2&nbsp;(-) | 2 | 2&nbsp;(1%) |
| 77 | [TheCharlatan](https://github.com/bitcoin/bitcoin/pulls/TheCharlatan) | 3&nbsp;(0%) | -2&nbsp;(0%) | 1&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 78 | [merland](https://github.com/bitcoin/bitcoin/pulls/merland) | 3&nbsp;(0%) | -27&nbsp;(0%) | -24&nbsp;(-) | 2 | 1&nbsp;(0%) |
| 79 | [HatboyWonder](https://github.com/bitcoin/bitcoin/pulls/HatboyWonder) | 2&nbsp;(0%) | -4&nbsp;(0%) | -2&nbsp;(-) | 2 | 1&nbsp;(0%) |
| 80 | [colourful-land](https://github.com/bitcoin/bitcoin/pulls/colourful-land) | 2&nbsp;(0%) | -3&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 81 | [stevenroose](https://github.com/bitcoin/bitcoin/pulls/stevenroose) | 2&nbsp;(0%) | -2&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 82 | [dooglus](https://github.com/bitcoin/bitcoin/pulls/dooglus) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 83 | [mysticaltech](https://github.com/bitcoin/bitcoin/pulls/mysticaltech) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 84 | [puchu](https://github.com/bitcoin/bitcoin/pulls/puchu) | 1&nbsp;(0%) | -1&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 85 | [rex4539](https://github.com/bitcoin/bitcoin/pulls/rex4539) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 86 | [sangaman](https://github.com/bitcoin/bitcoin/pulls/sangaman) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 87 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6&nbsp;(0%) | -6&nbsp;(-) | 2 | 1&nbsp;(0%) |

**Comment by fanquake** [comment]
Thanks for posting this. Maybe it can become a monthly thing. Closing for now.
