### ISSUE TITLE
Make Style of RPC Documentation Consistent

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#14894]
I noticed RPC documentation is a bit inconsistent. Sometimes there is period at the end of the sentence, sometimes there is not, etc... so I thought I open an up for grab issue that does not require any coding skills.

As a starting point, I selected out 6 reasonable recommendation from [.NET Error Message Guidelines](https://docs.microsoft.com/en-us/windows/desktop/debug/error-message-guidelines) those could make the style more consistent:

- Use complete but simple sentences.
- Use correct capitalization.
- End each sentence in a period.
- Avoid uppercase text and exclamation points.
- Do not anthropomorphize. Do not imply that programs or hardware can think or feel.
- Do not use colloquial words or phrases. Do not use terms that may be offensive in certain cultures.
- Avoid the word "please". It can be interpreted to mean that a required action is optional.

**Comment by Sjors** [comment]
See also the work on RPCHelpMan, e.g. 14726, #14875 and #14885. Some of this could be enforced by a linter, but otherwise should go in the RPC section of [Developer Notes](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#rpc-interface-guidelines).

**Comment by laanwj** [comment]
> but otherwise should go in the RPC section of Developer Notes.

Even if checked by a linter it should probably go there :-)

**Comment by ch4ot1c** [comment]
Ack

**Comment by blueredpen** [comment]
Looking into this issue.

**Comment by MarcoFalke** [comment]
If this is done, then it should be enforced inside the help manager. Otherwise people will remove periods after they have been added, see https://github.com/bitcoin/bitcoin/pull/25420

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix. 

see https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring
