### ISSUE TITLE
[Feature] Persistency for locking unspents

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#14907]
In the way that this is currently implemented, you can lock/unlock unspents using coin control however after a software restart those locks disappear.
This can lead to unintended spending of UTXO due to simply forgetting to lock them every time that the software is booted up.

**Comment by promag** [comment]
BTW, from #1861

> It might be nice to store this in the wallet

6 years later and still not stored 😄

**Comment by madeken** [comment]
It would be amiss if I didn't mention that locking unspents is most often far too low level to use correctly. I think without exception all times I have hoped to or actually locked an unspent, what I have actually meant is: "lock this _address_, with the possible exception of _this_ output"

**Comment by promag** [comment]
I think you are better served with loading/unloading multiple wallets. I think we should avoid persisting state in the wallet file.

**Comment by madeken** [comment]
Multiple wallets doesn't really solve the typical case for wanting to lock inputs/addresses which is because you've had (tiny amounts) of unsolicited funds that if you spend would harm your privacy.

**Comment by madeken** [comment]
@promag A typical reason to wanting to lock an unspent is because someone sent you money (often dust) and if you spend it, you will generally be spend linking with other transactions which will future erode your privacy for typically no benefit. In fact, often the small dust ends up costing more to spend than its value.

An easy solution to this is to "lock" the unspent, so you don't spend it. But in reality what you are actually wanting to do is lock an address (with the exception of the "real" unspent).   None of this is benefited by using multiple wallets

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Comment by prayank23** [comment]
> I think you are better served with loading/unloading multiple wallets. I think we should avoid persisting state in the wallet file.

@promag Sorry but I dont understand the first part. How does loading and unloading wallet solve this problem because if I restart bitcoind/bitcoin-qt, locks are gone.

What are the issues in saving locks in wallet file? I see only positives

**Comment by promag** [comment]
@prayank23, my suggestion was as simple as splitting the wallet in two and then load the 2nd only when you want to spend. Obviously this is limited especially with address reuse. In the past, I had to store utxos locks on the side and sync the wallet with that.. so I'd appreciate this feature at the time.
