### ISSUE TITLE
New method for cryptocurrencies blocks in blockchains...

### ISSUE THREAD

**Issue by bruseyujchbl** [bitcoin/bitcoin#14910]
I think you can release new method for more transactions in one block. You can make blocks in archives (i.e. zip, rar, 7z or gzip or other)... Maybe i'm not right, but that have reason...

And that can make for all cryptocurrencies...

What about that method - https://www.mobilefish.com/services/pseudorandom_number_generator/pseudorandom_number_generator.php

**Comment by fanquake** [comment]
This discussion is not on-topic here.
