### ISSUE TITLE
Make coinselection aware of maxtxfee

### ISSUE THREAD

**Issue by madeken** [bitcoin/bitcoin#14928]
The `maxtxfee` check is applied at the very final stage of creating a transaction, which with a large amount of inputs and/or a low `maxtxfee` setting will cause coinselection to frequently propose a solution that will just be rejected, even though there are many other possible selections which would not exceed the maxtxfee setting.

The simplest fix I believe would be make each "stage" of the coin selection aware of the `maxtxfee` setting, and go to the next when it can't satisfy it.

e.g. if the BnB algorithm can find a selection that requires 0.01 BTC of fees, but the maxtxfee is set to 0.005, it shouldn't bother suggesting it.

And then there could be a final fallback algorithm that is an extremely simple greedy one that picks the largest inputs, where if that fails then there is no hope and an error given.

**Comment by promag** [comment]
The "simplest fix" you suggest is to add backtracking to coin selection right?

> e.g. if the BnB algorithm can find a selection that requires 0.01 BTC of fees, but the maxtxfee is set to 0.005, it shouldn't bother suggesting it.

In that case is it be possible to have less than 0.01? AFAICT the algorithm aims for a minimal fee.

**Comment by madeken** [comment]
> In that case is it possible to have less than 0.01? AFAICT the algorithm aims for a minimal fee.

Yeah. I don't believing minimizing fee is currently an objective of any stage of the current coin selection (although I would definitely appreciate an option to pick that behavior!).

**Comment by MarcoFalke** [comment]
maxtxfee is mostly a belt-and-suspenders check to avoid mishaps. It wasn't designed to be used for coin selection.
