### ISSUE TITLE
gettxoutsetinfo giving two different disksize

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#14921]
I got surprised to see that the disk size of the txoutsetinfo on two different machine is different, is it normal?

Node1:

```json
{
  "height": 553392,
  "bestblock": "000000000000000000296776e029f7f080f7fb5a6add661fa2833dee72e3ab5f",
  "transactions": 26313045,
  "txouts": 50178355,
  "bogosize": 3782162613,
  "hash_serialized_2": "a086c7291271916e2959d6efc107d5ea896df03d3f78ac83223c23d2909b8317",
  "disk_size": 2946125043,
  "total_amount": 17417229.82774740
}
```

Node2:

```json
{
  "height": 553392,
  "bestblock": "000000000000000000296776e029f7f080f7fb5a6add661fa2833dee72e3ab5f",
  "transactions": 26313045,
  "txouts": 50178355,
  "bogosize": 3782162613,
  "hash_serialized_2": "a086c7291271916e2959d6efc107d5ea896df03d3f78ac83223c23d2909b8317",
  "disk_size": 3048699532,
  "total_amount": 17417229.82774740
}
```

**Comment by promag** [comment]
Internally this calls leveldb `GetApproximateSizes`, and from https://stackoverflow.com/a/19614759 looks like it doesn't account memory only keys.

**Comment by sipa** [comment]
Yes, it depends on various factors like exactly when flushes happened, when LevelDB decides to compact the database, configuration settings like dbcache.

If you want a consistent number for size, look at the `bogosize` field (which has a well-defined meaning in function of the sizes of keys and values in the database, and is independent from actual disk usage).

**Comment by NicolasDorier** [comment]
Thanks
