### ISSUE TITLE
I can't connect to Bitcoin using RPC on a remote machine.

### ISSUE THREAD

**Issue by pai01234** [bitcoin/bitcoin#14943]
this  is bitcoin.conf
![image](https://user-images.githubusercontent.com/30950645/49910845-323f0680-febf-11e8-9110-ea2c489acba7.png)

and firewall is not open  
![image](https://user-images.githubusercontent.com/30950645/49910862-471b9a00-febf-11e8-9506-4e65740c0f31.png)

icant connect
![image](https://user-images.githubusercontent.com/30950645/49910891-6286a500-febf-11e8-8174-331aa257734e.png)

![image](https://user-images.githubusercontent.com/30950645/49910883-5ac70080-febf-11e8-95ef-da1260b1573e.png)

**Comment by pai01234** [comment]
the bitcoin version is 0.17.99

**Comment by qshuai** [comment]
Use a integer as id instead of a string. Please try.

**Comment by pai01234** [comment]
> Use a integer as id instead of a string. Please try.

im sorry ,whats u ref

**Comment by pai01234** [comment]
i solute it. i change my bitcoin version to 0.17.0 , I have not changed any configuration except this.maybe 0.17.99 is a bit problematic

**Comment by adamjonas** [comment]
User resolved issue by using released version. Ready to close.
