### ISSUE TITLE
./configure does not favour self-compiled dependecies

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#14959]
Steps to reproduce this issue:
1. Clear minimal installation of Ubuntu 18.04.1
2. Install requirements
```
sudo apt install build-essential libtool automake pkg-config cmake curl git
```
3. Clone repository
```
git clone https://github.com/bitcoin/bitcoin.git
cd bitcoin
```
4. Build dependencies
```
pushd depends
make
popd
```
The final output of `make`:
_copying packages: native_protobuf boost openssl libevent zeromq qrencode protobuf zlib qt expat dbus libxcb xcb_proto libXau xproto freetype fontconfig libX11 xextproto libXext xtrans bdb miniupnpc
to: /home/hebasto/bitcoin/depends/x86_64-pc-linux-gnu_

5. Build
```
./autogen.sh
./configure --prefix=$PWD/depends/x86_64-pc-linux-gnu
make
```

Note the using of the `--prefix` option. That is the only way to build _successfully_ I've found.
`./configure --help` gives description confusing to me:
```
Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr/local]
```

The question ONE:
Why can't `./configure` without any options find out self-compiled dependencies in the `depends/` directory?
Is it intentional?

The question TWO:
What does `--prefix` do in `./configure --prefix=$PWD/depends/x86_64-pc-linux-gnu` exactly?

**Comment by practicalswift** [comment]
FWIW you're not alone here: I found the use of `--prefix` (for anything beyond the ordinary meaning of installation destination) unintuitive too :-)

**Comment by hebasto** [comment]
Closing in favor of #16692 and #17934
