### ISSUE TITLE
[Localization] British vs American English usages in code

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#14962]
I notice that `color` vs `colour`, and `usable` vs `useable` both appear in the codebase. Most instances use the American English spelling. 

However, RPC `prioritisetransaction` uses the British English spelling of `prioritise`.

Do we prefer one or the other? This could be included in the Developer Notes.

I would favor `color` and `usable`, and American English in general.

Source: https://www.dictionary.com/browse/prioritise

**Comment by pstratem** [comment]
Think we should standardise on en_AU cause Satoshi was clearly Australian.

**Comment by MarcoFalke** [comment]
For code comments we accept any dialect as long as it can be understood by a non-native English speaker. It would be nice to normalize user-facing documentation and interfaces. Though, I can't see how this is enforceable, considering that most reviewers are non-native speakers.

**Comment by jnewbery** [comment]
I think this is a non-issue. Contributors should be free to chose whichever variety of English they prefer, so long as it's clear and comprehensible to others.

I choose to make my contributions in American English as I suppose that's more familiar to most readers, but I wouldn't want to impose my color of paint on other contributors.

**Comment by ch4ot1c** [comment]
Ack!

**Comment by fanquake** [comment]
Agree that this is a non-issue. Contributions will likely continue in American/Australia/British english etc.
