### ISSUE TITLE
Building 32bit for Windows wallet version

### ISSUE THREAD

**Issue by guru-god** [bitcoin/bitcoin#14971]
I am now getting errors on building 32bit for Windows wallet version.

```
Making all in src
make[1]: Entering directory '/home/god/bitcoin/src'
make[2]: Entering directory '/home/god/bitcoin/src'
make[3]: Entering directory '/home/god/bitcoin'
make[3]: Leaving directory '/home/god/bitcoin'
  CXXLD    libbitcoinconsensus.la
crypto/.libs/libbitcoinconsensus_la-hmac_sha256.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:3797: recipe for target 'libbitcoinconsensus.la' failed
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: Leaving directory '/home/god/bitcoin/src'
Makefile:10252: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/god/bitcoin/src'
Makefile:774: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

How can i handle this error?
Please give me your hand on this error.

**Comment by minblock** [comment]
You have to go into the sec256k and make that first. It would help if you chmod +x recursively what is happening is when its making the package it crawls to the different folders to compile your coin and if a file is not executable that should be: permission error.

**Comment by minblock** [comment]
If your building for Windows, you need to use Linux subsystem and cross-compile from within that to match your path variables. You won't be able to compile it for windows from a straight ubuntu box.

**Comment by chungin** [comment]
Thank you for your help.
I am now trying to build on WSL, so the permission error can't be happened, I believe.
Can you give me a further explanation?

**Comment by minblock** [comment]
I had the same problem today and the way I went about it, which was actually the only way it worked was the make clean; make

**Comment by ken2812221** [comment]
Could you do `git clean -xdfe depends`, re-configure it and compile.

**Comment by MarcoFalke** [comment]
32 bit windows is no longer supported
