### ISSUE TITLE
Notifications do not popup if app installed from *.dmg on macOS

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#14976]
How to reproduce:

1. Install Bitcoin Core from downloaded `dmg` file (e.g., [v0.17.1rc1](https://bitcoincore.org/bin/bitcoin-core-0.17.1/test.rc1/bitcoin-0.17.1rc1-osx.dmg)).

2. Run with `-regtest`.

3. Generate a new block. A new notification is expected to popup.

Actually, this notification is present in Notification Center; but _it did not popup_.

The same Bitcoin Core version being self-compiled (`git checkout v0.17.1rc1`) works as expected.

**Comment by fanquake** [comment]
Which version of macOS are you testing/have tested on?

**Comment by hebasto** [comment]
@fanquake 
> Which version of macOS are you testing/have tested on?

10.13.6 and 10.11.6; both in VM.

**Comment by Sjors** [comment]
Haven't tested this yet, but reminds me of #11840

**Comment by hebasto** [comment]
It seems related to [CFBundleIdentifier](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102070).

**Comment by jonasschnelli** [comment]
This is not a bug, it's a feature.

When Bitcoin Core is the most foreground application, such notifications go silently to the Notification Center (top right global menu bar).

If you put the Bitcoin Core GUI in the background and trigger a notification via RPC (`generatetoaddress` as example) you will get a banner (popup) notification.

I guess it would be possible to overwrite the `NSUserNotificationDelegate` and make it always popup.

https://developer.apple.com/documentation/foundation/nsusernotification#//apple_ref/occ/instp/NSUserNotification/presented

**Comment by hebasto** [comment]
@jonasschnelli 
> This is not a bug, it's a feature.
> 
> When Bitcoin Core is the most foreground application, such notifications go silently to the Notification Center (top right global menu bar).

Tested. It works as described.
But why do notifications popup for a self-compiled build running from the command line?

**Comment by jonasschnelli** [comment]
> But why do notifications popup for a self-compiled build running from the command line?

Not entirely sure but maybe because the command line is the process initiator and not the front most application?
