### ISSUE TITLE
One Travis instance should run minimum supported QT version

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#14983]
@jonasschnelli wrote in #14979:
> #14573 broke < Qt5.6 compatibility due to calling the lambda version of `addAction` that was added in Qt5.6.

We currently [support](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md) QT >=5.2, but hardly anyone tests with that. If we make one of the Travis machines use it, we should have a better change of catching this.

See also discussion about minimum QT version in #13478

**Comment by promag** [comment]
The problem is that 5.2 is only available in trusty repository, bionic has 5.9. I'm not sure if adding an older repository is a good practice.

**Comment by Sjors** [comment]
That could be a good reason to bump the minimum to whatever is available on Ubuntu Xenial (16.04), since we do have one such instance.

**Comment by MarcoFalke** [comment]
We already build on xenial, but the travis error wasn't reported

**Comment by Sjors** [comment]
@marcofalke I mean we should run the oldest possible version of QT 5.* on the Xenial machine, and then increase the minimum supported version from 5.2 to that.

**Comment by MarcoFalke** [comment]
Again, I am not aware on how to conveniently install a version different from the ubuntu flavoured default that comes in the package manager.

**Comment by MarcoFalke** [comment]
Oh, you said to bump the minimum to 5.5, which comes with xenial

**Comment by promag** [comment]
Related to https://github.com/bitcoin/bitcoin/issues/13478#issuecomment-416877194.

**Comment by luke-jr** [comment]
@Sjors Minimum versions need to be what is at least available with the most recent stable release of major distros... Ubuntu-only is not an acceptable outcome.

Adding old packages *should* be fairly safe, so long as they're not needed for running other packaged tools.

(This bug should probably apply to more dependencies than just Qt.)

Arch: Qt 5.12
Debian: Qt 5.7
Gentoo: Qt 5.11
RHEL: Qt 5.9
Ubuntu: Qt 5.9

**Comment by MarcoFalke** [comment]
> Minimum versions need to be what is at least available with the most recent stable release of major distros

Would be nice to add this to `doc/dependencies.md` and also add what "major distros" are. See also https://github.com/fanquake/core-review/blob/master/operating-systems.md by @fanquake

**Comment by luke-jr** [comment]
Might be good to use a LTS version for the minimum too - which would indicate Qt 5.6

**Comment by Empact** [comment]
I'm working on CI for ubuntu 14.04, which runs QT 5.2.1. Here's the current latest CI run:
https://travis-ci.org/Empact/bitcoin/jobs/469269171

**Comment by jonasschnelli** [comment]
Setting Qt5.6 as minimum requirement would be acceptable I think. Though I don't see a pressing need (except the missing CI)
