### ISSUE TITLE
bitcoin-qt: segmentation fault on Fedora 29

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#14994]
I can reproduce an issue with master; v0.17.1rc1 works fine.

Steps to reproduce:
- `bitcoin-qt -regtest`
- open Console window
- repeat `generatetoaddress 1 AN_ADDRESS` some times until crash

Crash occurs both on wayland and x11.

[debug.log](https://github.com/bitcoin/bitcoin/files/2690776/debug.log)

[wallets.zip](https://github.com/bitcoin/bitcoin/files/2690781/wallets.zip)

**Comment by MarcoFalke** [comment]
I assume if you run in gdb or valgrind it will tell you that the "balloon pop-up" that notifies you of a new transaction is the cause of the issue?

**Comment by hebasto** [comment]
@MarcoFalke 
> I assume if you run in gdb or valgrind it will tell you that the "balloon pop-up" that notifies you of a new transaction is the cause of the issue?

You are right. The bug was introduced in #14228. Mea culpa. Working on fixup.

**Comment by fanquake** [comment]
Confirmed the segfault on Fedora 29-1.2 using master (f5a70d1462592a23bbad4aa150e6b2beaeec7c42).
Compiling and running `bitcoin-qt -regtest`. Followed by (in the gui console):
```
getnewaddress
generatetoaddress 1 the_new_address
```
