### ISSUE TITLE
[RFC] qt: Icon scaling issue on some Linux desktop environments

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#14992]
The app icon in Ubuntu Bionic Dock and GNOME Activities Favorites (e.g., Fedora 29) looks ugly due to improper scaling ([screenshots](https://github.com/bitcoin/bitcoin/pull/14990#issue-239372705)).

There are some possible solutions:

1. [`Qt::SmoothTransformation`](https://doc.qt.io/qt-5.9/qt.html#TransformationMode-enum) does not work as expected (#14990)

2. Multiple `QPixmap`s added by [QIcon::addPixmap()](https://doc.qt.io/qt-5.9/qicon.html#addPixmap) do not work in this case (https://github.com/bitcoin/bitcoin/pull/14990#issuecomment-448127312; Qt bug?)

3. Use SVG images as icons directly

An icon engine that supports SVG is included with Qt since version 4.2 (tested: it works).

**Comment by MarcoFalke** [comment]
I wouldn't subject using SVG

**Comment by hebasto** [comment]
Also: https://github.com/bitcoin-core/packaging/pull/27

**Comment by fanquake** [comment]
If still relevant, can you update / port this issue to the [gui repo](https://github.com/bitcoin-core/gui/issues).
