### ISSUE TITLE
gui: Note own addresses in pay to field 

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#15008]
When a valid address is entered/pasted in the "Pay To" field and it belongs to a loaded wallet then it could note that.

Had the idea after #12688.

**Comment by benthecarman** [comment]
Currently, if you enter an address that has a label it will auto-fill the `label` field which has a similar effect.

**Comment by promag** [comment]
It doesn't work if it belong to other loaded wallet.

**Comment by fanquake** [comment]
Moved to the GUI repo: https://github.com/bitcoin-core/gui/issues/63.
