### ISSUE TITLE
Runaway exception when closing Bitcoin Core

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#15011]
If you close bitcoin core after moving/deleting the wallet.dat file, it will cause a runaway exception while Bitcoin core is shutting down

**Comment by MarcoFalke** [comment]
Touching the wallet file during operation is not a supported feature to the best of my knowledge.

**Comment by HashUnlimited** [comment]
For my experience agreed, just like to add that even an attempt to copy it can result in corrupted data.
