### ISSUE TITLE
importwallet silently returns no error even if pointed to random file

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#15019]
A confused user was trying to use `importwallet` on a wallet.dat directly. It gave no error message.

Perhaps we want an error to be output when nothing is imported, re-iterating that it needs to be a file outputted from `dumpwallet`?

**Comment by kristapsk** [comment]
Looks to me too like a bug (from user's perspective) that needs to be fixed.
```
$ src/bitcoin-cli -testnet listwallets        
[
  ""
]
$ src/bitcoin-cli -testnet importwallet dsadas   
error code: -8
error message:
Cannot open wallet dump file
$ src/bitcoin-cli -testnet importwallet /dev/null
$ src/bitcoin-cli -testnet listwallets        
[
  ""
]
```

**Comment by instagibbs** [comment]
Perhaps it should make sure it sees `# Wallet dump created by Bitcoin` at the beginning of the file?

**Comment by kristapsk** [comment]
Perhaps it could check instead if there was something meaningful at all to import and return result, like number of keys imported or warning about nothing imported or something.

**Comment by willcl-ark** [comment]
We are not adding new features to the legacy wallet now.
