### ISSUE TITLE
slow GUI with large wallets

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#15015]
Loading a large wallet (around 23 mio transactions here on test) is resulting in an unusable GUI. Spinning wheel of death on every mouse click for 5 seconds at least.

branch: master
OS: macOS 10.14.2
CPU: Intel i9 (8th Gen)
RAM: 32 GB DDR4

Note: this behaviour is not limited to the Overview page or CoinControl but in general as long as the wallet is loaded. A headless setup performs nicely though.

**Comment by cryptozeny** [comment]
same here. on custom testnet, empty wallet works like charm, but large wallet tooooooooo slow... one click for 5 seconds.

debug is OK, but only GUI freeze

OS: ubuntu 16.04.5-64bit
CPU: i5 skylake
RAM: 24GB

`v0.16.3`

**Comment by promag** [comment]
@HashUnlimited are you able reproduce with #18160? ty

**Comment by jonatack** [comment]
I was not able to reproduce this issue, though I initially had a different one (see the bottom).

Yesterday tested the GUI with current master @ 5f9cd62f33f, and with #18160 rebased onto it, both on Debian and MacOS. I did not see any real difference between any of the four.

The test was to load several wallets, 2-3 small ones and also one large wallet of 177MB in size, and run various console commands like getbalances, getwalletinfo, listwallets, etc.

The large wallet is a regtest one generated with @achow101's [make-big-wallet.py](https://gist.github.com/achow101/f24309bba501cc08c9a3a3d55fa6eec6) script. On both Debian and MacOS it takes the GUI 5-6 minutes to load that wallet.

Once loaded, the GUI ran fine in my tests, with an additional reaction latency of ~400-500 ms with console commands like getbalances or getwalletinfo when the commands were run on big wallet. The other commands ran basically as fast as they do with tiny wallets.

With one build on Debian, I did see the GUI halt, and then crash with segmentation faults, when loading any wallet at all. However, rebuilding after make clean solved that, so I suspect it was the build.

**Comment by jonatack** [comment]
(If anyone has any suggestions for further tests to run with the big wallet, let me know.)

**Comment by jonatack** [comment]
I was not able to reproduce this issue, though I initially had a different one (see the bottom).

Yesterday tested the GUI on current master 5f9cd62f33f, and with #18160 rebased onto it, both on Debian and MacOS. I did not see a real difference in performance between the four configurations.

- Debian 4.19.37amd64 (2019-08-08) x86_64 - Intel Core i7-6500U 2.50GHz × 4 - 32GB
- MacOS 10.14.6 - MacBook Pro Retina 2012 - Intel Core i7 2.7GHz - 16GB 1600 DDR3

The test was to load several wallets, 2-3 small ones and also one large wallet of 177MB in size, and run various console commands like getbalances, getwalletinfo, listwallets, etc.

The large wallet is a regtest one generated with @achow101's [make-big-wallet.py](https://gist.github.com/achow101/f24309bba501cc08c9a3a3d55fa6eec6) script. On both Debian and MacOS it takes the GUI 5-6 minutes to load that wallet.

Once loaded, the GUI ran fine in my tests, with an additional reaction latency of ~400-500 ms with console commands like getbalances or getwalletinfo when the commands were run on big wallet. The other commands, and clicking on and opening transactions, ran basically as fast as they do with tiny wallets.

With one build on Debian, I did see the GUI halt, and then crash with segmentation faults, when loading any wallet at all. However, rebuilding after make clean solved that, so I suspect it was the build.

If anyone has any suggestions for further tests to run with the big wallet, let me know.

**Comment by achow101** [comment]
@jonatack The big wallet script does ~100,000 txs. It's possible that this is not big enough as it seems that OP has a wallet with several million txs. You should try increasing the iteration count to make a wallet that has a few million txs.

**Comment by promag** [comment]
According to OP

> Note: this behaviour is not limited to the Overview page or CoinControl but in general as long as the wallet is loaded. A headless setup performs nicely though.

@achow101 see my last post at #18160, I think it's safe to say that #18160 will improve in this case.

**Comment by jonatack** [comment]
@achow101 @promag thanks. Both trying with a larger wallet and instrumenting as per https://github.com/bitcoin/bitcoin/pull/18160#issuecomment-606033867 to reproduce @promag's result (and/or with a flamegraph) seem worthwhile.

**Comment by HashUnlimited** [comment]
Sorry for the late reply. Just tested with the same wallet - performance is WAY better now.

**Comment by promag** [comment]
> performance is WAY better now.

@HashUnlimited I guess you tested with #18160, and if so happy to know that.

**Comment by HashUnlimited** [comment]
Yes, tested twice. Once with master and once with 0.18 and implemented #18160 just to make sure this is the performance booster.

**Comment by promag** [comment]
Great, thanks for reporting the result.
