### ISSUE TITLE
[GUI] progress window size

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#15016]
Information in the progress window (example: rescan) is displayed capped to fixed size instead of contents.

<img width="209" alt="screenshot 2018-12-21 at 14 58 20" src="https://user-images.githubusercontent.com/26601261/50345943-0bbd4300-0531-11e9-9c6c-e277ac69eb0c.png">

**Comment by hebasto** [comment]
Here are known related Qt bugs:
- [QProgressDialog too small width at larger font size on Mac](https://bugreports.qt.io/browse/QTBUG-65750)
- [QProgressDialog is too narrow to fit the text of its label](https://bugreports.qt.io/browse/QTBUG-70357)

@fanquake maybe label `macOS`?

**Comment by hebasto** [comment]
@HashUnlimited Could you try #15040?

**Comment by HashUnlimited** [comment]
same issue now with the open wallet popup

**Comment by promag** [comment]
Thanks @HashUnlimited, already have a fix for that.
