### ISSUE TITLE
[Feature Request] Implement `estimatesmartfee` all.

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#15014]
Right now we're extracting this information from Bitcoin Core with a clever algorithm that considers the returned `blocks` (there's a bug there btw: https://github.com/bitcoin/bitcoin/issues/15001), converts the result to s/b and rounds up to integer and asks `estimatesmartfee` between two upper and smaller values and results in a dictionary with the
- key: fee target
- value: integer satoshi/vbyte

This reduces the whole spectrum of 2-1008 feetargets to only a couple of entries today:  

https://wasabiwallet.io/api/v2/btc/Blockchain/all-fees?estimateSmartFeeMode=CONSERVATIVE

https://wasabiwallet.io/api/v2/btc/Blockchain/all-fees?estimateSmartFeeMode=ECONOMICAL

![image](https://user-images.githubusercontent.com/9156103/50340266-98103b80-051a-11e9-9632-6be79183b690.png)

Of course the worst case scenario we'd have to do 1007 `estimatesmartfee` query, but today our algorithm is able to establish this dictionary with only about 12.

With this we are able to show a more accurate pre-transaction build fee estimation than other wallets, who're blindly targeting one or two RPC targets and doesn't try to explore that if the same fee can apply to less targets, thus giving back less accurate feedback to the users, like the user targets 2 weeks, but the tx still confirms within 6 hours.  

Anyway, it's no biggie, but it would be nice if we could reduce our RPC queries to only one, if Core would give back the "allfees" with just one request. Maybe an `estimateallsmartfee CONSERVATIVE/ECONOMICAL` RPC would be a good idea. Thoughts?

**Comment by adamjonas** [comment]
Given this hasn't been picked up since 2018, closing due to lack of momentum/interest. Can re-open if future interest.
