### ISSUE TITLE
GUI balance doesn't update after `importmulti`

### ISSUE THREAD

**Issue by bitcoinhodler** [bitcoin/bitcoin#15027]
After using `bitcoin-cli importmulti` to import a watch-only multisig p2sh-segwit address in a non-default wallet, the GUI shows all balances as 0 despite correctly listing a recent incoming transaction.
# Steps to repeat

    bitcoin-qt -server -testnet
    bitcoin-cli -testnet createwallet "glacier5" true
    bitcoin-cli -testnet -rpcwallet=glacier5 importmulti '[{ "scriptPubKey": { "address": "2MzqiaZzpLT2SSBfsFqqo3FpZsP8g6WTvyC" }, "timestamp":1545413762, "redeemscript":"5221029f531503facdac2496f50a446d9bd29846a06a04a45e3845b656bb471df422fc2102e30787703a990e4015a2cb9071fcfd1c7d4641fb294e4b4c3f5f6b450a1925132102da28088a8022651171c4f13429b98709dabe13bc6da526537fdd2d0730dd2dbb2103286c96ecaa850a6ba43cc45fbb539c1fb1d65c23cc0f3cd09fcf9765826ff9de54ae", "watchonly":true, "label":"Glacier 2012-12-21" }, { "scriptPubKey": { "address": "2MzqiaZzpLT2SSBfsFqqo3FpZsP8g6WTvyC" }, "timestamp":1545413762, "redeemscript":"0020dabea3445c14e4a08d6705db4373bef467d4c64e7c8ddf149be50670de6878ae", "watchonly":true, "label":"Glacier 2012-12-21" }]'

# Expected behavior

The GUI now shows a pulldown in the upper-right corner to select a wallet. When I select the new glacier5 wallet, it shows a recent incoming transaction.

It should also include the amount of this incoming transaction (which the tooltip reports as having 90 confirmations) in the watchonly balances.

# Actual behavior

The watchonly balances are all 0.

After restarting the GUI and doing `loadwallet "glacier5"`, the balances are correct.

# System details

Running Whonix 13 with the binary distro `bitcoin-0.17.0.1-i686-pc-linux-gnu.tar.gz`. Also recreated in my own build of 0.17.1rc1.

**Comment by promag** [comment]
This is fixed and can be closed. I was able to follow instructions and the UI updates accordingly. Just changed the scanning code to stop after the first successfully `AddToWalletIfInvolvingMe`.

<img width="780" alt="Screenshot 2020-03-04 at 16 13 48" src="https://user-images.githubusercontent.com/3534524/75899352-52941180-5e33-11ea-9e8b-b6bffc31b599.png">

**Comment by promag** [comment]
> Is there a commit that fixed it?

@MarcoFalke for sure :trollface:
