### ISSUE TITLE
Question: miner_tests.cpp with new data

### ISSUE THREAD

**Issue by cryptozeny** [bitcoin/bitcoin#15029]
Hi Bitcoin Devs :smiley: 

https://github.com/bitcoin/bitcoin/blob/e2dfeb0146da046ad34655b17941e54e4b3d7769/src/test/miner_tests.cpp#L54

```cpp
    {4, 0xa4a3e223}, {2, 0x15c32f9e}, {1, 0x0375b547}, {1, 0x7004a8a5},
    {2, 0xce440296}, {2, 0x52cfe198}, {1, 0x77a72cd0}, {2, 0xbb5d6f84},
    {2, 0x83f30c2c}, {1, 0x48a73d5b}, {1, 0xef7dcd01}, {2, 0x6809c6c4},
    {2, 0x0883ab3c}, {1, 0x087bbbe2}, {2, 0x2104a814}, {2, 0xdffb6daa},
```

I want to do `miner_tests` with new data. Could you tell me how to create new one? `blockinfo` I would especially like to check blockchain data after segwit. This data is maybe outdated... :thinking: 

If I can, I would like to reinforce the test data and contribute to this project. :smile: I tried a lot. But I could not get the `extranonce` :sob:

**Comment by knight2008** [comment]
hello, how to generate the new data for blockinfo in bitcoin/src/test/miner_tests.cpp?
