### ISSUE TITLE
asymetric encryption ? 

### ISSUE THREAD

**Issue by prateektiwari7** [bitcoin/bitcoin#15035]
Recently I got Question 

Which is not apart of asymmetric encryption?
a.) Mining
b.) Public key
c.) Passphrase
d.) Private key

Mining use the AES libraries. Please help me to find the answer

**Comment by sipa** [comment]
This is not a place for homework questions.

**Comment by sipa** [comment]
For general questions, try https://bitcoin.stackexchange.com , I'm sure you'll find the answer there.
