### ISSUE TITLE
Crash: BerkeleyEnvironment::VerifyResult upon `loadwallet`

### ISSUE THREAD

**Issue by bitcoinhodler** [bitcoin/bitcoin#15030]
# Problem

After creating a new wallet and running a series of operations concluding with `unloadwallet`, the next time that wallet is loaded with `loadwallet`, `bitcoin-qt` crashes after the following assertion fires:

    bitcoin-qt: wallet/db.cpp:236: BerkeleyEnvironment::VerifyResult BerkeleyEnvironment::Verify(const string&, BerkeleyEnvironment::recoverFunc_type, std::__cxx11::string&): Assertion `mapFileUseCount.count(strFile) == 0' failed.

# Recreating

See gist: [loadwallet-crash.sh](https://gist.github.com/bitcoinhodler/a46edc6e94557e2952f8001239c63761)

This fails reliably for me on v0.17.0.1 release binaries, and also on my local build of v0.17.1rc1, on 32-bit Whonix 13.

# Possibly related

#14572, #14850

**Comment by etscrivner** [comment]
Was not able to reproduce this on v0.17.1 on 64-bit Ubuntu.

**Comment by promag** [comment]
@fanquake this is also fixed, the gist in the OP no longer causes the crash.
