### ISSUE TITLE
gui: Use MINUS (U+2212) instead of HYPHEN-MINUS (U+002D)

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#15034]
MINUS (U+2212) is used if money is removed from wallet.

HYPHEN-MINUS (U+002D) is used if money is removed from wallet.

1. Run bitcoin-qt -regtest
2. Mine some blocks
3. Send some coins

0.17.0.1, website

GNU/Linux, x86_64, HDD

**Comment by luke-jr** [comment]
What's the problem? There's no issue that I can see. Changing this seems pointless and just makes stuff gratuitously incompatible with real world keyboards and copy/paste to other software??

**Comment by luke-jr** [comment]
So? That's not a reason to use U+2212 instead of U+002D (which is also a Unicode character, FWIW).
