### ISSUE TITLE
The project "libbitcoin_server" can not load successfully in VS2017

### ISSUE THREAD

**Issue by grantren** [bitcoin/bitcoin#15049]
==============================================
How to reproduce
==============================================
1. execute "python msvc-autogen.py"
2. open "bitcoin.sln" with VS2017
3. The project "libbitcoin_server" can not load successfully.

==============================================
The reason of the problem
==============================================
The file "build_msvc\libbitcoin_server\libbitcoin_server.vcxproj" has an error.

==============================================
How to fix the bug
==============================================
Remove the section in file "libbitcoin_server.vcxproj.in" can reslove the issue:
-----------------------------------------
    <ClCompile Include="..\..\src\rpc\net.cpp">
      <ObjectFileName Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">$(IntDir)\netrpc.obj</ObjectFileName>
      <ObjectFileName Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">$(IntDir)\netrpc.obj</ObjectFileName>
      <ObjectFileName Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">$(IntDir)\netrpc.obj</ObjectFileName>
      <ObjectFileName Condition="'$(Configuration)|$(Platform)'=='Release|x64'">$(IntDir)\netrpc.obj</ObjectFileName>
    </ClCompile>
-----------------------------------------

==============================================
possible reason
==============================================
I think the reason:
There are two files with the same name "net.cpp", one is "src\net.cpp", the other is "src\rpc\net.cpp".
There was a special section in file "libbitcoin_server.vcxproj.in" in order to produce the different obj files before.
But the file "msvc-autogen.py" updated so as to process such scenario. finally, a conflict arises.

**Comment by ryanofsky** [comment]
Analysis in this bug report makes sense. After 7e2e62cf7c513bd7d8e784069c5534fda1c50c52 from #14437, manually creating `netrpc.obj` files is unnecessary and could cause problems. Dropping the section as suggested seems like a good fix:

https://github.com/bitcoin/bitcoin/blob/fb52d0684e0f03bca5d7ddcf3fc5b0657859ac2c/build_msvc/libbitcoin_server/libbitcoin_server.vcxproj.in#L157-L162
