### ISSUE TITLE
remove `-uacomment`

### ISSUE THREAD

**Issue by isghe** [bitcoin/bitcoin#15048]
I think it can be a security problem, in a way I don't know, but:
```
$ bitcoind -h
…
 -uacomment=<cmt>
       Append comment to the user agent string
…
```
it looks to be dangerous and unnecessary.
https://github.com/spesmilo/electrum/issues/4968#issuecomment-450268698

**Comment by achow101** [comment]
NACK. The user agent comment is rarely shown to the user. When shown to the user, it is explicitly known to be part of a node's user agent string and is never shown in it's own dialog or message without surrounding context that makes it clear it is a user agent string for another node. I see no reason to remove this whatsoever.

**Comment by luke-jr** [comment]
Agree with @achow101.

NACK

If there is concern about how it is displayed, it should be addressed on that end. Making it harder to add comments doesn't help anyone.

**Comment by MarcoFalke** [comment]
Any fancy characters in the string are removed before displaying it to the user.

**Comment by markaw67** [comment]
I do have a copy of a user attempting to use a phish/attack.

**Comment by Manbearpixel** [comment]
@markaw67 So someone was trying to use the user agent string maliciously? Do you have a screenshot of this? How did you discover it?
