### ISSUE TITLE
[mempool] A single standard sized transaction should not preclude a CPFP

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#15046]
Current relay policy can lead to a situation where an unconfirmed payment output can be swept by the payee with a standard ~100kvB transaction, such that the payer cannot bump their own package feerate due to the descendant size limits.

One naive way to shore this up would be to increase the total descendant size limit such that this cannot reasonably happen with a single transaction griefing the whole package limit, even if the payer is making small-ish packages.

**Comment by benthecarman** [comment]
A safer way to do it could be making it so the size limit can be broken by X% if a transaction fee is trying to be bumped.  This would allow someone to still bump their fee, but not throw in another huge transaction on top of it.

**Comment by MarcoFalke** [comment]
@instagibbs Is this still an issue?

**Comment by instagibbs** [comment]
That PR carves out a single (useful) exception, but in general relay can still be abused. e.g., if the tx you're replacing has more than one ancestor(IIRC, I'd have to re-read the PR again)

**Comment by instagibbs** [comment]
So after more thinking and research, I believe https://github.com/bitcoin/bitcoin/pull/16421 and https://github.com/bitcoin/bitcoin/pull/15681 do indeed fix this issue.

A single transaction off your transaction(or chain from one output) is unable to pin it any longer with the carve-out rule.

This should be enough to make reliable CPFP/RBF more than a dream in production systems.
