### ISSUE TITLE
gui: Unhidden systray icon gets unusable on KDE

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#15042]
Steps to reproduce the bug:
1. Run `bitcoin-qt`
2. If `Options -> Window -> Hide tray icon` is unchecked, check it and press `OK`
3. Uncheck `Hide tray icon` and press `OK`
4. The appearing tray icon is unusable: neither the icon can be activated by the left-click nor a context menu shows by the right-click.

Kubuntu 18.04.1 LTS
KDE Plasma 5.12.7
Qt 5.9.5

Almost always there is an error message in `debug.log`:
```
GUI: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4609, resource id: 50336490, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by fanquake** [comment]
I'm not sure this warrants having an issue open. In either case, I can't reproduce using 0.19.1rc1, kubuntu 19.10 and the steps provided.

![kubuntu](https://user-images.githubusercontent.com/863730/73807230-adbbef80-4806-11ea-8972-db6cc4b7bf02.png)
