### ISSUE TITLE
docs: Release description on GitHub needs clarification

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#15041]
![github](https://user-images.githubusercontent.com/32963518/50471537-c7f98c00-09bd-11e9-8b10-13243f1b8654.png)

> Preferably use **the above** download link, not **the below** links to download the source tarball, as the release tarballs are generated deterministically whereas GitHub's are not.

But _all_ links are _above_. The rewording is required.

cc: @laanwj

**Comment by MarcoFalke** [comment]
Preferably a wording that does not depend on the GitHub UI should be picked
