### ISSUE TITLE
Consensus: Curious on people's thoughts on checkpoints

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#15095]
Currently, bitcoin has checkpoints for blocks 11111, 33333, 74000, 105000, 134444, 168000, 193000, 210000, 216116, 225430, 250000, 279000, and 295000.  The oldest of these is from 2009 and the newest is from 2014.  I am curious about people's opinions on disabling this feature because currently, the default is to check for these points.

**Comment by HashUnlimited** [comment]
I guess there are more opinions than developers out there regarding checkpoints. Personally mainly as an advanced user, I am on the conservative side with that as they don’t really hurt.

**Comment by sipa** [comment]
We're not extending the checkpoints anymore, as the concept was replaced with the "assumevalid" feature, which is more flexible, and safer.

The old checkpoints remain as they protect against a header flooding attack during initial block download.

**Comment by HashUnlimited** [comment]
Thanks for the clarification, never stop learning as I didn’t take the header flooding into account. 

Was more thinking about “assumevalid” to serve as a cover for “hidden soft forks” like it was to occur when the “difficulty” for creating key pairs increased
