### ISSUE TITLE
bitcoin-cli: Choose wallet through environment variable

### ISSUE THREAD

**Issue by domob1812** [bitcoin/bitcoin#15097]
Multi-wallet support is a very nice feature.  However, it makes using `bitcoin-cli`manually a bit cumbersome, as one always has to type `-rpcwallet=foo` for each command.

What do you think of allowing to choose the wallet through an environment variable, e.g. `BITCOINCLI_WALLET`?  In other words, if `-rpcwallet` is not specified but this variable is set, use the wallet specified in the variable.  That way, the wallet could be chosen once e.g. in a shell session and then shorter commands could be used in the follow-up.

Of course, this only applies to explicit manual usage of `bitcoin-cli`.  Programmatic users (either using the RPC interface directly or calling `bitcoin-cli`) do not really have any benefit from such a change.  Also, as an alternative, one can use a shell `alias` instead.  But I think it might still be nice to have this (from my own experience).  If others agree, I'm happy to implement this.

**Comment by domob1812** [comment]
> IMO arguments are more user friendly, even for auto complete etc.

They are more explicit, but require retyping every time.

> What if both are specified? Honestly why create redundancy?

I imagine the explicit argument would override the environment variable.

> More importantly, I think it would be prone to mistakes (missing change env, hard to understand from bash history, etc..).

That is a fair point.

I personally would have liked something like that a couple of times in shell sessions, that's why I decided to bring up the idea.  Honestly, though, I could probably just as well have used a bash `alias` instead of an environment variable in those situations.  So I don't have a strong opinion here, either.

**Comment by jarolrod** [comment]
@domob1812 can this be closed. I agree with @promag that arguments are better in this scenario. And as you mentioned, you can always use a bash alias

**Comment by domob1812** [comment]
Yes sure, of course.
