### ISSUE TITLE
RPC: Connection Refused

### ISSUE THREAD

**Issue by cryptopool-builders** [bitcoin/bitcoin#15096]
I see that there has been some configuration updates which is why I am sure I am getting a connection refused.

i tried searching for an updated bitcoin.conf example but couldn't find anything. 

this is the config throwing the error:

rpcuser=user
rpcpassword=pass
rpcport=10301
rpcthreads=64
rpcallowip=127.0.0.1
rpcallowip=10.0.0.3
rpcallowip=10.0.0.2
rpcallowip=10.0.0.4
rpcallowip=10.0.0.7
rpcallowip=10.0.0.8
rpcallowip=10.0.0.9
rpcallowip=10.0.0.10
rpcallowip=10.0.0.11
maxconnections=25
daemon=1
gen=0

alertnotify=echo %s | mail -s "Bitcoin alert!" support@xxxx.xxx
blocknotify=blocknotify.sh PORT 6 %s

**Comment by CryptoCanary** [comment]
server=1

**Comment by fanquake** [comment]
@cryptopool-builders can you follow up here, are you still having the same issue?
