### ISSUE TITLE
Information units consistency

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#15106]
There is a plenty diversity in information units through the code, command-line options, GUI and logs. Here are some examples:

`-dbcache`
**megabytes** in CL and GUI _vs_ **MiB** in logs and code (constants in [txdb.h](https://github.com/bitcoin/bitcoin/blob/master/src/txdb.h))

`-prune`
**MiB** in CL _vs_ **GB** in GUI. Also, setting prune = 1 GB in GUI gives _incorrect_ prune target = 1000 MiB.

Which prefix type -- binary (a power of 2) or SI (a power of 10) -- is preferable in the Bitcoin Core project?

**Comment by benthecarman** [comment]
IMO units that people regularly use are most preferable (gigabyte, megabyte).
