### ISSUE TITLE
Wrong transactions order if time is same

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#15116]
First transaction is "In", second is "Out", always.

First transaction is "Out", second is "In" if time is same.

1. Import some known brain wallet private key which has some bitcoins stolen immediately after receiving them.

0.17.1, website

GNU/Linux, x86_64, HDD

Parabola GNU/Linux-libre, LXDE

Locale is Russian.

**Comment by benthecarman** [comment]
Do you have an address I can import to test this on?
