### ISSUE TITLE
bitcoin-0.8.1 version how to generate exe file 

### ISSUE THREAD

**Issue by awaissakhi11** [bitcoin/bitcoin#15119]
i am try to get the exe file from bitcoin-0.8.1 version .In bitcoin latest version we can get easily exe file  but bitcoin-0.8.1 version its not like latest version so if anyone can help to generate exe from bitcoin-0.8.1 version so ill be very thankfull

**Comment by sipa** [comment]
You shouldn't use such outdated code.

**Comment by sipa** [comment]
We do not support such old code: https://bitcoincore.org/en/lifecycle/

You should consider upgrading the code. Further, this is not a support forum; a better place may be https://bitcoin.stackexchange.com
