### ISSUE TITLE
Can't use custom change address if outside of the wallet

### ISSUE THREAD

**Issue by syrop** [bitcoin/bitcoin#15125]
I use custom change address, which is outside of this Core wallet. I receive the usual warning: "Unknown change address". This is okay.

Then I press "Send". The program crashes with no warning and no further error message.

Version 0.17.0.1 downloaded from Bitcoincore.org as Linux binaries in .tgz.

Ubuntu 18.10 Mate.

**Comment by syrop** [comment]
I no longer can reproduce it after upgrading to 0.17.1 (below is the output from 0.17.0.1 for reference).

When I send a transaction with a custom change address in 0.17.1, and then try to use "replace by fee", it says "Transaction does not have a change output", so even though I do can use a custom change address in 0.17.1, it doesn't really count as change, at least the "Fee bump error" pop-up doesn't think it does.

This is the requested output from `valgrind bitcoin-qt`, Core 0.17.0.1, testnet:

>bitcoin-qt: policy/feerate.cpp:25: CAmount CFeeRate::GetFee(size_t) const: Assertion `nBytes_ <= uint64_t(std::numeric_limits<int64_t>::max())' failed.
==1104== 
==1104== Process terminating with default action of signal 6 (SIGABRT)
==1104==    at 0x4EDB077: raise (raise.c:51)
==1104==    by 0x4EBC534: abort (abort.c:79)
==1104==    by 0x4EBC40E: __assert_fail_base.cold.0 (assert.c:92)
==1104==    by 0x4ECC141: __assert_fail (assert.c:101)
==1104==    by 0x73591E: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x617DFF: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x626602: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x628510: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x5B33C0: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x2E9E5F: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x32BCA7: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104==    by 0x2F771C: ??? (in /home/wiktor/.programy/bitcoin-0.17.0/bin/bitcoin-qt)
==1104== 
==1104== HEAP SUMMARY:
==1104==     in use at exit: 428,798,266 bytes in 3,170,688 blocks
==1104==   total heap usage: 10,077,057 allocs, 6,906,369 frees, 1,316,274,049 bytes allocated
==1104== 
==1104== LEAK SUMMARY:
==1104==    definitely lost: 8,392,294 bytes in 75,050 blocks
==1104==    indirectly lost: 352 bytes in 3 blocks
==1104==      possibly lost: 14,854,323 bytes in 6,244 blocks
==1104==    still reachable: 405,551,297 bytes in 3,089,391 blocks
==1104==                       of which reachable via heuristic:
==1104==                         newarray           : 6,288 bytes in 117 blocks
==1104==                         multipleinheritance: 448 bytes in 3 blocks
==1104==         suppressed: 0 bytes in 0 blocks
==1104== Rerun with --leak-check=full to see details of leaked memory
==1104== 
==1104== For counts of detected and suppressed errors, rerun with: -v
==1104== Use --track-origins=yes to see where uninitialised values come from
==1104== ERROR SUMMARY: 425933 errors from 352 contexts (suppressed: 0 from 0)
Aborted (core dumped)

**Comment by sipa** [comment]
This looks like one of the bugs that were fixed in 0.17.1.

**Comment by syrop** [comment]
It is the same situation, as it is also connected to using a custom change address, and I have verified it doesn't occur in 0.17.1.
