### ISSUE TITLE
Build Error Windows 32 - Mingw

### ISSUE THREAD

**Issue by limxdev** [bitcoin/bitcoin#15131]
Build Info
--
![Screenshot](https://i.imgur.com/NA7JSkz.jpg)

Error:
--
![Screenshot](https://i.imgur.com/eBPT9UG.jpg)

https://github.com/bitcoin/bitcoin/blob/master/src/netbase.cpp#L679
`
return strprintf("%s (%d)", std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>,wchar_t>().to_bytes(buf), err);`

https://github.com/bitcoin/bitcoin/blob/master/src/netbase.cpp#L21
`#include <codecvt>`

Is the function really necessary?

**Comment by ken2812221** [comment]
codecvt is in C++11 standard. You must use a compiler that support it.

**Comment by limxdev** [comment]
We should here add also a solution for MinGW.

**Comment by ken2812221** [comment]
@limxdev I think you might have to update your compiler to the latest version.

**Comment by MarcoFalke** [comment]
Let me know if this still persists with a supported version (also share the version with us)
