### ISSUE TITLE
Rename `Bitcoin Core` back to `Bitcoin`

### ISSUE THREAD

**Issue by nvk** [bitcoin/bitcoin#15143]
I know this is contentious and will require a lot of discussion, but in my opinion it needs to be corrected. Disambiguating which was the original implementation will help us avoid more confusion with future forks.

IIRC the bitcoin team embraced `Bitcoin Core` as an overreaction to the manipulation campaign about "control" over Bitcoin protocol, and whether it was clever or just good timing by Gavin to suggest the rename is hard to say.

I was tempted at opening a pull request with the name change everywhere, but think that was silly. If that's something helpful, I'm happy to do it.

There maybe some fear of it being "official", and as we know nothing is "official" in a consensus network like bitcoin, but it is the original client. Nothing stays the same forever, it is possible the consensus of the network looks at a different reference implementation in the future. That's fine, and the name shouldn't matter, but the bar would be higher than just trying a semantic name attack as the recent forks did.

Maybe I'm mistaken, but there seems to be a lot of support for this or if not, we should find out very quickly and i will be the first to put it to rest.

Sorry for the wonderful ESL writing.

**Comment by MarcoFalke** [comment]
See https://bitcoin.stackexchange.com/questions/462/what-is-the-difference-between-bitcoin-bitcoin-and-bitcoin and https://bitcoincore.org/en/about/ about the current use of the term. Imo that is clear enough and changing it (if it made sense) would be too much hassle and only introduce confusion.

**Comment by MrHodl** [comment]
You think saying "Bitcoin Developers" is more confusing than saying "Bitcoin Core Developers?

**Comment by Cobra-Bitcoin** [comment]
@MarcoFalke Why close this unilaterally instead of letting the discussion play out? If the community wants it to be renamed to Bitcoin, it should be renamed IMO.

**Comment by MarcoFalke** [comment]
If people want to discuss this, they are very welcome to. I am happy to reopen if other contributors of Bitcoin Core take part in the discussion, but I'd be surprised to see enough people to chime in in favour of the change to go forward with it. This is not a simple "scripted diff" change, but a whole rebranding of the software project and websites, ... etc. Definitely not a trivial change and probably a waste of time in light of actual technical issues that need to be solved.

**Comment by luke-jr** [comment]
NACK, Bitcoin Core and Bitcoin are two different things, and Bitcoin Core is not really the original implementation either (just based on it). In hindsight, it was also dumb to ever call the software, the currency, and the consensus protocol the same thing anyway. At least now the software has a separate name - let's not regress on that.

**Comment by kristapsk** [comment]
I think this discussion is complete waste of time, not necessary. It's not important for me what is the name of software I use for Bitcoin.
