### ISSUE TITLE
Antivirus "false" positives

### ISSUE THREAD

**Issue by coder82** [bitcoin/bitcoin#15156]
I just downloaded 0.17.1 and checked the SHA, it matches as you can see but it's not all green.
I believe they are all false positives, but this is an issue as I see developers turned down for this!! Slowing adoption. Isn't there any other solution other than notifying all those antivirus companies?
Will there always be reds with this binary?

[Screenshot](https://i.imgur.com/1yiEkjR.png)

.asc file says:

**fa1e80c5e4ecc705549a8061e5e7e0aa6b2d26967f99681b5989d9bd938d8467**  bitcoin-0.17.1-win64-setup.exe

Signature is correct.

**Comment by fanquake** [comment]
Yes this a false positive from your virus software. This happens semi-regularly on Windows, i.e #12320, #11852, #12777, #4069.
