### ISSUE TITLE
IsInitialBlockDownload() can stop syncing

### ISSUE THREAD

**Issue by multicoins** [bitcoin/bitcoin#15174]
Initial syncronization should continue till last block will downloaded

Initial synchronization can stopping when there is 24 hours left to a last block

I do not know is there are real issue or not. But this line is very strange for me https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L1183

So synchronization may fail when user is in initial download mode and when to end of synchronization remains 24 hours

I think it should be like this:
 	    if (chainActive.Tip()->GetBlockTime() < GetTime())

**Comment by sipa** [comment]
The IsInitialBlockDownload result just triggers some optimizations. Having it return false early doesn't materially impact the behavior of the client.
