### ISSUE TITLE
decoderawtransaction assumes output has 1 `reqSig` if not naked multisig

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#15211]
Quite misinformational.

**Comment by promag** [comment]
https://github.com/bitcoin/bitcoin/blob/452acee4da206eb8792505914fd92245246b2290/src/script/standard.h#L152-L163

IIUC this is noted here:

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
