### ISSUE TITLE
GUI: Display amounts/fees in both BTC and fiat

### ISSUE THREAD

**Issue by andrasfuchs** [bitcoin/bitcoin#15237]
From practical standpoint it would be a user friendly feature if the Bitcoin Core client would display the amounts both in BTC (as it does now) and in a preferred fiat currency.

It's easy to make a decimal mistake with BTC now if we need to enter an amount manually, and it's also difficult to guess if the transaction fee we choose is low enough to our taste without knowing its value in a more familiar fiat currency that we use every day.

I think it would be great to have an option to select a fiat currency in Settings / Options / Display, just like we have now with the BTC/mBTC/uBTC/Satoshi dropdown.

Bitcoin Core then could use a 3rd party provider to get the current BTC/USD price and the USD/[preferred currency] and calculate the estimated fiat value of any BTC amount used in the client.

This fiat value would be displayed in a few places by default (Overview/Total, Send/Amount, Confirm Send Coins dialog) and could be displayed only as a tooltip in other places.

3rd-party providers:
* xe.com supports many fiats and some cryptos (including BTC), but they have [only paid API plans](https://www.xe.com/xecurrencydata/#price-section)
* fixer.io has a [free plan](https://fixer.io/product), but they don't support cryptos as far as I know
* CoinMarketCap has [a free API plan as well](https://coinmarketcap.com/api/pricing/), that could be used for the USD/BTC pair

(I'm not sure it matters, but I'm running Bitcoin Core 0.17.1 x64 on Windows 10.)

**Comment by kristapsk** [comment]
Bad idea. Bitcoin Core should not use any 3rd party service providers for anything. If you want to see fiat values, you can use other wallet software or make and maintain a fork of Bitcoin Core that adds this functionality.

**Comment by promag** [comment]
I think this won't happen in this wallet.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
