### ISSUE TITLE
Calculating txid for SegWit transactions with the help of RPC

### ISSUE THREAD

**Issue by kristapsk** [bitcoin/bitcoin#15232]
With legacy non-SegWit transactions one could do (for example, in bash script), `createrawtransaction`, then `signtransactionwith{wallet,key}` and then calculate txid using SHA-256d hash of returned transaction hex string, without sending transaction to the network using `sendrawtransaction`. That's not possible with SegWit transactions, as returned hex string includes witness data. Would be great if we could somehow export either `CTransaction::ComputeHash()` via RPC or be able to get hex string of transactions without witness data too.

**Comment by achow101** [comment]
Use `decoderawtransaction`.

**Comment by kristapsk** [comment]
Ohhh, yes, you're right, somehow missed that.
