### ISSUE TITLE
Confusing description of sending/receiving address

### ISSUE THREAD

**Issue by andronoob** [bitcoin/bitcoin#15230]
I think the current descriptions of sending/receiving address list is somewhat confusing to the user:
> These are your Bitcoin addresses for sending payments. Always check the amount and the receiving address before sending coins.

> These are your Bitcoin addresses for receiving payments. It is recommended to use a new receiving address for each transaction.

So what is exactly *"your"* Bitcoin addresses? For example, a confused user might think that he could "fake" the sending address when he is trying to pay another people.

I think this might be improved, for example:
> You may send payments to these known Bitcoin addresses. Always check the amount and the receiving address before sending coins.

> These Bitcoin addresses are yours, you may use them to receive payments. It is recommended to use a new receiving address for each transaction.

**Comment by andronoob** [comment]
There is another problem: Bitcoin Core currently allows the user to import watch-only addresses - these addresses might not belong to the user.

**Comment by promag** [comment]
Agree, it's confusing. I'd remove those messages though — currently it promotes reusing addresses.

**Comment by andronoob** [comment]
@promag 
I think what Electrum did is pretty good. Electrum doesn't support importing keys/addrs into existing wallet, so there are less confusions around backuping. Screwups caused by change address like #11827 are also avoided. Watch-only wallets and spendable wallets have clear distinction. The address panel of Electrum clearly showed how many times an address has been used.

**Comment by andronoob** [comment]
What the wallet should look like in my humble opinion:
The address list panel should contain known recipients only.
The receiving address list panel might be merged with the coin selection panel, which has a clear hierarchy tree view, thus HD-derived addresses and imported single privkeys would have clear distinction. The user could also benefit from clear backup warnings, change-screwup would become history. It would be even better if PSBT and xpub importing could be supported, so that multisig transactions would be easy.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
