### ISSUE TITLE
Build Error on Ubuntu 

### ISSUE THREAD

**Issue by xt0680** [bitcoin/bitcoin#15234]
Hi

**System** : Ubuntu 18.04.1 LTS
**Command** : $make
**Using version** : v0.12.1

    error:
    Making all in src
    make[1]: Entering directory '/home/xt0680/bitcoin/src'
    make[2]: Entering directory '/home/xt0680/bitcoin/src'
    make[3]: Entering directory '/home/xt0680/bitcoin/src/secp256k1'
    make[3]: Leaving directory '/home/xt0680/bitcoin/src/secp256k1'
    CXX      wallet/libbitcoin_wallet_a-crypter.o
    wallet/crypter.cpp: In member function ‘bool CCrypter::Encrypt(const CKeyingMaterial&,     std::vector<unsigned
      char>&)’:
    wallet/crypter.cpp:61:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
    wallet/crypter.cpp: In member function ‘bool CCrypter::Decrypt(const std::vector<unsigned char>&, CKeyingMa
    terial&)’:
    wallet/crypter.cpp:88:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
    At global scope:
    cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
    Makefile:4358: recipe for target 'wallet/libbitcoin_wallet_a-crypter.o' failed
    make[2]: *** [wallet/libbitcoin_wallet_a-crypter.o] Error 1
    make[2]: Leaving directory '/home/xt0680/bitcoin/src'
    Makefile:6959: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/xt0680/bitcoin/src'
    Makefile:650: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

I tried searching for solve, but I did not find any information

How do I proceed with build?

**Comment by fanquake** [comment]
Indeed, 0.12 is [EOL](https://bitcoincore.org/en/lifecycle/#maintenance-period).
