### ISSUE TITLE
bitcoind wont start with datadir specified in conf file and no home dir

### ISSUE THREAD

**Issue by d3spwn** [bitcoin/bitcoin#15240]
bitcoind won't start if datadir is specified in the conf file and the user running it has no home dir

tested with debian stretch and bitcoin 0.17.1

```
# sudo -u bitcoin bitcoind -daemon -conf=/usr/local/etc/bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid

************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directories: Permission denied: "/home/bitcoin"
bitcoin in AppInit()

bitcoind: chainparamsbase.cpp:29: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.
Aborted

# mkhomedir_helper bitcoin

# sudo -u bitcoin bitcoind -daemon -conf=/usr/local/etc/bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid
Bitcoin server starting
```

**Comment by d3spwn** [comment]
````
datadir=/var/local/lib/bitcoind
txindex=1
server=1
wallet=xxxx.dat
````

**Comment by Viral** [comment]
remove datadir in conf and -conf from command and just specific datadir with your run command?

**Comment by hebasto** [comment]
@d3spwn would you mind trying #15864 to fix this issue?

**Comment by d3spwn** [comment]
I'll test it within the next few days.

**Comment by d3spwn** [comment]
I'm unable to get this to work. Starting bitcoind as per my first post gets me the message `Bitcoin server starting`, but it seems to exit without any message. A `blocks ` directory is created in the datadir, but nothing else.

**Comment by d3spwn** [comment]
note: I deleted my previous reply. I believe this was caused because I didn't have #15278 merged.

I've tested #15864 and it seems to resolve this issue. bitcoind correctly starts the IBD using the datadir set in the conf file even when the user that is running it has no home dir. When no datadir is provided it still uses the home dir or gives an error when it doesn't exist.

**Comment by hebasto** [comment]
@d3spwn Thank you for testing #15864.

**Comment by egp** [comment]
Is there a workaround until the PR is released?

**Comment by MarcoFalke** [comment]
I guess it could be backported to 0.18.2
