### ISSUE TITLE
Build test/* as part of make check

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#15260]
Currently `make` spends a significant amount of time on `test/test_*_tests.o`, even on a modern iMac this is annoyingly slow. 

This causes me to often build with `--disable-tests`, and then run `./configure` again when I do want to run the unit test suite. So I don't run the unit test suite less often than I should (the functional test suite doesn't have this issue).

It would be better if the tests are compiled as part of `make check`.

**Comment by sdaftuar** [comment]
I think the tests are compiled as part of make check -- I assume you mean that it'd be better if the tests were not compiled except as part of make check, to speed up regular compilation?

**Comment by Sjors** [comment]
Indeed, not compiling during `make`, only during `make check`.

**Comment by promag** [comment]
FWIW you can skip those by specifying the target, for instance, `make src/bitcoind`.

**Comment by sipa** [comment]
I think it's pretty unconventional to only build the test at `make check` time.

**Comment by promag** [comment]
BTW, from https://www.gnu.org/prep/standards/html_node/Standard-Targets.html, `all` should be the default target.

**Comment by MarcoFalke** [comment]
> FWIW you can skip those by specifying the target, for instance, `make src/bitcoind`.

Note that some targets (gut tests, fuzz binary, ...?) can not be build this way. I'd be happy if someone changed that.

**Comment by Sjors** [comment]
I guess using `make src/bitcoind` isn't too bad, and it's also a good way to avoid building QT (I currently just have two separate folders).

But that won't build `bitcoin-cli` would it? Though that only matters when working on the RPC.

Maybe `make daemon` could do both files?

**Comment by promag** [comment]
You can make multiple targets, for instance `make -j src/bitcoind src/bitcoin-cli src/qt/bitcoin-qt`.

**Comment by MarcoFalke** [comment]
TIL

**Comment by Sjors** [comment]
I'm fairly contend with the multi target approach @promag suggested.
