### ISSUE TITLE
But old transaction and address are missing.

### ISSUE THREAD

**Issue by mariajohnfranklin** [bitcoin/bitcoin#15269]
We tried to upgrade old version(0.8.XX) to current version. But old transaction and address are missing.

we received below error

 Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.

our previous data folder contains
blocks
chainstate
database

How to upgrade to a new version with old Blocks and address? please advice

**Comment by promag** [comment]
This is not the best place to get support, you should post your question in https://bitcoin.stackexchange.com.
