### ISSUE TITLE
[Windows, MinGW] error windres -f invalid option

### ISSUE THREAD

**Issue by MSFTserver** [bitcoin/bitcoin#15271]
having the hardest time figuring out this issue for some reason it seems like its trying to pass -f option to windres during the check `@test -f $(WINDRES)` i dont see where -f is being passed to windres at all, i know i know i could just build it on linux but i am trying to bring back an old project(easywinbuilder) and this seems to be my last issue im really just stuck with no solution...
![image](https://user-images.githubusercontent.com/18357967/51796824-32b10980-21ae-11e9-9133-6938d319481b.png)
[config.log](https://github.com/bitcoin/bitcoin/files/2799800/config.log)

**Comment by MSFTserver** [comment]
config log is big due to me having so many debug flags trying to pinpoint the issue as my past errors have really been ablut something else and i had to dig to fix past stuff ive had issues this...so im thinking this may be the case here to

**Comment by MSFTserver** [comment]
incase any wonder how im comoiling dependencies and such here is the project im working on https://github.com/MSFTserver/easywinbuilder

**Comment by fanquake** [comment]
Problems with your custom build system do not warrant an issue here. In any case, I'd recommend using the [depends system](https://github.com/bitcoin/bitcoin/tree/master/depends) instead.

**Comment by MSFTserver** [comment]
that just fails for me on windows and MinGW

**Comment by fanquake** [comment]
@MSFT if it’s failing, can you post more information? You can also use it from inside the Windows Subsystem for Linux.

**Comment by MSFTserver** [comment]
@fanquake it really doesnt have an error since im on windows the depends system only detects builders for linux and mac, i tried tricking the system into buolding depends by specifying a linux host that somewhat worked but alot of issues calling other linux based that should work since im on mingw but thats besides this main issie im having even where it checks for windres in the file with test -f commands i removed all of them that point towards windres where it was failing and the error still returns yet it isnt even my code anymore im truely baffled at this sentient compiling lol

**Comment by MSFTserver** [comment]
![img](https://cdn.discordapp.com/attachments/519193647749791755/539257584411213854/unknown.png)
example of this sentient compiling using commands that dont exist

**Comment by MSFTserver** [comment]
could you reopen this issue...@fanquake you honestly didnt even look at my issue and just assumed some shit and closed this issue, and can you clarify what you mean by custom build when your vanilla deps fail with your make file provided?

**Comment by MarcoFalke** [comment]
We only support builds on windows via
* https://github.com/bitcoin/bitcoin/tree/master/build_msvc (native, for development only)
* https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md (cross-compilation, for releases)

**Comment by MSFTserver** [comment]
![img](https://cdn.discordapp.com/attachments/324400517075959808/539490265237422090/Screenshot_20190128-090019.jpg) im working on this(windows MinGW with POSIX) and just wanted a little help

**Comment by MarcoFalke** [comment]
Thanks for working on this, though I presume you are the first one (or one of very few to do it), so don't expect help right away. Going to reopen for now.

**Comment by MSFTserver** [comment]
thanks, yea i dont expect help fast, but its worth a try where it seems the majority of you have alot of experience compiling ive tried asking around in other programmer chats and they are just dumbfounded about my error, spent atleast a month on this issue now and im just resorting to posting here for any solution, that other link may habe confused fanquake it really just launches the stuff you setup for making all my depends seem to be in order configure doesnt fail i can see all tge relevant paths compared them to some others install on linux just this one issue not sure if there some for loop that also checks all the depends because ive deleted that one on line 11227 but says its still erroring there anyway thanks again
