### ISSUE TITLE
Incorrect or duplicate assertion in key.cpp signing code

### ISSUE THREAD

**Issue by maaku** [bitcoin/bitcoin#15286]
The following assertion seems redundant. Is it a mistake? Two lines prior the same assertion is made, and the value being asserted doesn't appear to change in-between. However the next line asserts a condition on a different variable which differs by only one letter. Is the referenced line a duplicate assertion of `ret` and therefore redundant, or is it supposed to be `assert(rec)`?

https://github.com/bitcoin/bitcoin/blob/7275365c9bc7e7ebd6bbf7dcb251946aac44b5de/src/key.cpp#L247-L251

**Comment by promag** [comment]
I think the `ret` must be updated in L249. If that's the case a fix is in #15299.
