### ISSUE TITLE
Removal of Payment Channels

### ISSUE THREAD

**Issue by kanoi** [bitcoin/bitcoin#15298]
Payment channels force people to reduce the security of their wallet and have an inherent design risk of allowing external web access to the wallet.

They require the wallet to have internet access to a (hidden) online web site and allow that web site to provide hidden information to create a transaction in the wallet.

While it is necessary for the user to confirm the transaction, it is clearly a risk to allow a 3rd party to create a transaction in your wallet and also do this via hidden data.

Forcing the wallet computer to allow web access also forces a degradation of security.
One can, of course, run a wallet without any internet access at all, by providing another bitcoin node in the same network as the wallet.
This security design is however compromised by payment channels.

It has already been show clearly with the Electrum wallet, that allowing web data to even just display messages in a wallet is a security risk, and core has already agreed this is a risk when they removed that option from a much earlier version of bitcoin due to that stated risk, and yet payment channels allow a higher level of this risk since the 3rd party provides information that the wallet acts upon.

The idea of a payment channel is to stop people from making stupid mistakes entering data into their wallet, however, if a person is unable to do this, that clearly implies that opening their wallet to an external web site to create the transaction is an even greater risk to such a person.

**Comment by sipa** [comment]
Bitcoin Core has never supported payment channels, but it sounds like you may be referring to the BIP70 (payment protocol) implementation? If so, that's already made optional recently.

**Comment by kanoi** [comment]
Sorry, yes I mean Payment Protocol as is clear by my description.
However, one of the largest online Bitcoin payment companies, BitPay, requires all transactions to use that and thus (as explained) though named incorrectly, require everyone to use this since Core has maid it available.

**Comment by MarcoFalke** [comment]
It is being deprecated in Core and I believe it was never compatible with bitpay in the first place. See also https://github.com/bitcoin/bitcoin/pull/14451#issuecomment-431496319
