### ISSUE TITLE
tests: Running with --usecli ~5x slower than without

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#15309]
Bought up in IRC [here (line 603)](http://www.erisian.com.au/bitcoin-core-dev/log-2019-01-31.html). More discussion [here (line 10)](http://www.erisian.com.au/bitcoin-core-dev/log-2019-02-01.html).

master @ cb35f1d305d88934df64c2e7fb80700b673360e6
with `--usecli`:
```
test/functional/test_runner.py --usecli wallet_disableprivatekeys.py
Temporary test directory at /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_runner_₿_🏃_20190201_113059
1/1 - wallet_disableprivatekeys.py passed, Duration: 35 s             

TEST                         | STATUS    | DURATION

wallet_disableprivatekeys.py | ✓ Passed  | 35 s

ALL                          | ✓ Passed  | 35 s (accumulated) 
Runtime: 35 s
```

without `--usecli`:
```
test/functional/test_runner.py wallet_disableprivatekeys.py
Temporary test directory at /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_runner_₿_🏃_20190201_113144
1/1 - wallet_disableprivatekeys.py passed, Duration: 7 s

TEST                         | STATUS    | DURATION

wallet_disableprivatekeys.py | ✓ Passed  | 7 s

ALL                          | ✓ Passed  | 7 s (accumulated) 
Runtime: 7 s
```

**Comment by MarcoFalke** [comment]
This happens because there is a 30 second overhead to exit the http event loop:

```
 node0 ...:09.423988Z Flushed wallet.dat 0ms 
 node0 ...:37.123147Z Exited http event loop

**Comment by ryanofsky** [comment]
Is this related to #14670?

**Comment by ryanofsky** [comment]
From IRC, it might be related to #14993:

> [00:53:49] \<aj> i'd seen it in december, as at cb52cee2 fwiw

**Comment by promag** [comment]
@sdaftuar thanks, looks like the client is not closing the connection and the server is allowing the connection to persist, this leads to the connection timeout (by default 60sec).

Do you observe slow down only with `--usecli`?. It's strange because bitcoin-cli sends `Connection: close` header and libevent should close the connection after it - unless there are other events in the event base.

I'll revisit this along with #14993.

**Comment by fanquake** [comment]
Going to close this, as I am no longer seeing any significant difference, i.e only 1-2s on applicable tests, with or without `--usecli`. Using master at 89a1f7a250ef70ff2d65701564f1e24bb9280d90.
