### ISSUE TITLE
https://x-bitcoin-generator.net/

### ISSUE THREAD

**Issue by kaminsky575** [bitcoin/bitcoin#15302]

**Comment by kaminsky575** [comment]
problems receiving amount bitcoin https://x-bitcoin-generator.net/. Please help me

**Comment by dragononcrypto** [comment]
Please purge this issue, or label as scam.
Reference: https://imgur.com/c1ca0762-a59e-4018-86bf-efabe709166f
Scam Address: 154UGzZoAntUVH4v7sjmZbMz2LXKudcemR
