### ISSUE TITLE
`encryptwallet` password entered in clear

### ISSUE THREAD

**Issue by darosior** [bitcoin/bitcoin#15318]
When using the RPC command `encryptwallet` in the CLI, the password used to encrypt it has to be entered as an argument and thus can be retrieved with reverse-search for "encryptwallet".
I thought that the password for `encryptwallet` (as well as for `walletpassphrase`) should be asked interactively.

I wanted to submit a PR to change `CommandLineRPC` (https://github.com/bitcoin/bitcoin/blob/b8b0b8ced7fa918ae00b697e5696b1950dfb714c/src/bitcoin-cli.cpp#L444
) so that if `encryptwallet` or ẁalletpassphrase` command is passed to `bitcoin-cli`, it asks interactively for the password, is it the right way to do it ? Is there any reason why passwords are passed in clear in the CLI ?

**Comment by jonasschnelli** [comment]
Hasn't that been implemented with bitcoin-cli's `-stdinrpcpass` in #10997?

**Comment by darosior** [comment]
Yes, it has been and I did not see it. However should not the stdin way be imposed ?

**Comment by KanoczTomas** [comment]
I think explicitly imposing it if pass not given would be nice. It would add to user experience!

**Comment by darosior** [comment]
@jonasschnelli actually I was wrong `-stdinrpcpass` was only related to the RPC password.

**Comment by jonasschnelli** [comment]
Oh. Yes. Your right. I guess there is no solution for bitcoin-cli right now. But you can always use other RPC clients.

Encryption could be implemented in wallet-tool.. 
Unlocking needs probably to go via RPC (eventually stdin function for walletpassphrase.. but meh).

**Comment by darosior** [comment]
It was not for my personal use but to improve it.
A PR would not be welcomed for this case ?

**Comment by adamjonas** [comment]
This was closed by https://github.com/bitcoin/bitcoin/pull/13716
