### ISSUE TITLE
`-maxtxfee` should not be used by both node and wallet

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#15355]
EDITED 2019-02-08

`maxTxFee` is a global variable, used by both the raw transaction and wallet RPCs. It's set from `-maxtxfee`.

~listed in the global help text in init.cpp, but is only set in `WalletInit::ParameterInteraction()`. If the wallet is disabled, then `-maxtxfee` is ignored and the default is used.~

~This behaviour has existed since the mempool was changed to limit acceptance based on `maxTxFee` in https://github.com/bitcoin/bitcoin/commit/fa331db68bcc68e4c93fb45aaa30f911b0ecfe1a.~

~Short-term fix is to move the `-maxtxfee` handling to `InitParameterInteraction()` in init.cpp.~
EDIT: `maxTxFee` initiation bug fixed in #15357 

I don't think we should share this setting between the node and wallet.

**Comment by jnewbery** [comment]
@MarcoFalke

**Comment by MarcoFalke** [comment]
> Longer term, I don't think we should share this setting between the node and wallet.

The wallet should still be aware of what the value is, which is why I made it shared between the node and wallet in the first place. For that to work you'd have to parse it before parsing the wallet specific max fee. So moving it to `src/init.cpp` as you suggest is probably a requirement for that.

> Short-term fix is to move the `-maxtxfee` handling to `InitParameterInteraction()` in init.cpp.

`init.cpp`  is also the place where `AddArgs` is happening, so ACK from me.

**Comment by jnewbery** [comment]
> The wallet should still be aware of what the value is

Right - this command line option was added in aa279d613152e87ea25edfdf76c86779c0632f18 to mean "I don't want my wallet to create a transaction that has a fee higher than this". After a few refactors, the same `maxTxFee` was recycled for use by the raw transaction RPCs. My point is that there should be a separation - `-maxtxfee` should be used to control wallet behaviour, and something else (probably an RPC parameter) should be used to control the raw transaction RPC behaviour.

We both agree that the minimal fix (move `-maxtxfee` to init.cpp) is what we should do now.

**Comment by gmaxwell** [comment]
Creating a plethora of overlapping fee configuration options is not good for users.  The result from doing that is that users set the wrong ones then are surprised when they don't get the behaviour they're expecting.    Maxtxfee shouldn't be ignored when the wallet is disabled, for sure, but what benefit to users of the software is there in splitting  "fee level above which we treat as something has gone wrong"  between the raw transactions interface and the wallet?   I don't believe we've ever gotten a request "I want to set this one to X and the other one to Y".

**Comment by jnewbery** [comment]
> Creating a plethora of overlapping fee configuration options...

I agree that having multiple config options would be confusing, which is why I suggested an RPC parameter for the `sendrawtransaction` and `testmempoolaccept` RPCs, which are the only places that `maxTxFee` is used outside the wallet. In fact, both of those RPCs already have a parameter `allowhighfees` which submits the transaction to the mempool without a `nAbsurdFee` parameter.

My reasoning is that those RPCs are lower-level than wallet operations, and should be separate from the wallet. The existing behaviour doesn't make really make sense to me:

- `testmempoolaccept` currently means "would my wallet be able to submit this to the mempool?" rather than "would this be accepted to the mempool over P2P?", unless `allowhighfees` is set to true, in which case it means "would this be accepted to the mempool over P2P?".
- `sendrawtransaction` currently means "broadcast this transaction if the wallet would submit it to the mempool" rather than "broadcast this transaction", unless `allowhighfees` is set to true, in which case it means "broadcast this transaction".

**Comment by jnewbery** [comment]
#15357 doesn't fully resolve the issue here. Reopening.

**Comment by MarcoFalke** [comment]
I don't think there is anything left to do here after moving the parsing back to the node (`init.cpp`).

Re (about the implicit use in the wallet):
The wallet should never create transactions that have such a high fee that this test could fail (at least in the default setting) and currently this serves as a "last-mile" belt-and-suspenders check for the wallet.

Re (about the implicit use in the rpc interface):
I don't object changing the rpcs to explicitly accept a fee (instead of the bool), but that seems like it should be handled in a separate feature-request.

**Comment by MarcoFalke** [comment]
Removed milestone, but I haven't received a reply either, so I intend to close this

**Comment by jnewbery** [comment]
This is partially fixed by #13541. If the same change is made to `testmempoolaccept` then `maxTxFee` could be removed from the node entirely and moved to the wallet.

**Comment by kallewoof** [comment]
I plan to do the same change to `testmempoolaccept` later today.
