### ISSUE TITLE
Why can't I append an UTXO unseen in the mempool in a replacement transaction?

### ISSUE THREAD

**Issue by calvinlauco** [bitcoin/bitcoin#15369]
### [Setup]
I was trying the opt-in rbf feature by preparing the follow setup:
```
Available UTXO:
U1: 1BTC
U2: 2BTC
U3: 3BTC
```

```
TX1:
vin: [U1, U2]
vout: [Alice: 2.9999BTC]
```

```
TX2:
vin: [U1, U2, U3]
vout: [Alice: 2.9999BTC, Change: 2.9995BTC]
```

Both TX1 and TX2 have their input already marked as replaceable (I used `nSequence`: `0xffffff00`), 

### [Expected Behaviour]
I expect the second transaction will replace the first one.

### [Actual Behaviour]
bitcoind sendrawtransaciton CLI returns error when trying to broadcast the second transaction:
```
replacement-adds-unconfirmed, replacement f67ddaf7df71c376c5ac2c0d802b19334f9bb9d07e4ab88bf0f98b057797d8a3 adds unconfirmed input, idx 2 (code 64)
```

### [Version]

bitcoind: 0.17.0.1

### [Investigation]

After some investigation, I found that in the code
https://github.com/bitcoin/bitcoin/blob/5cdb82111cc128d68ba5268eb94787110ce1fe6e/src/validation.cpp#L859
It checks that the vins have to be one of the previous vins used in the pool (If I understand the comment correctly).

Is this an expected behaviour? Because with this design, reusing the above setup, since the first setup I have already used up all the amount in U1 and U2, 2.9999BTC + 0.0001BTC fee. If I want to increase the fee, I must include another UTXO or I have to reduce the amount to spent in output to leave space for the relay fee.

**Comment by promag** [comment]
Full comment:

Above that line you have the comment

> but for now requiring all new inputs to be confirmed works.

So, in your case, the new input UB3 needs to be confirmed.

**Comment by yuhlau** [comment]
Thanks!

**Comment by yuhlau** [comment]
@promag May I know a bit more about the intention of making sure only confirmed UTXO are included? I am trying to understand what it means for the term `feerate junk`.

**Comment by HashUnlimited** [comment]
If U3 was unconfirmed, you could use another low rate input for that one again. That would fill up the mempool (which is actually only maintained by local node rules) and this can repeat as long as you like to do so.

**Comment by promag** [comment]
@yuhlau see b272ecfdb39f976dd61e35bacb22047da02b3416 in #6871.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
