### ISSUE TITLE
The configuration file could not be opened.

### ISSUE THREAD

**Issue by leon-do** [bitcoin/bitcoin#15409]
Describe the issue
`The configuration file could not be opened.` when clicking on `Open Configuration File`

What behavior did you expect?
Expected to open bitcoin.conf

How reliably can you reproduce the issue, what are the steps to do so?
Lanuch Bitcoin Core
![](https://i.imgur.com/gTR1bGS.png)
![](https://i.imgur.com/KHkJVM3.png)

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
https://bitcoin.org/en/download
v0.17.1

What type of machine are you observing the error on (OS/CPU and disk type)?
OSX

**Comment by MarcoFalke** [comment]
The configuration file does not exist by default. However, it could be created when selecting that button.

Related: #12722

**Comment by leon-do** [comment]
To clarify. When I click `Open Configuration File` it creates the `bitcoin.conf` file but it does not open it. Instead it shows `The configuration file could not be opened.`

I'm able to edit the conf file manually, but I expected that file to open in some text editor.

**Comment by shannon1916** [comment]
I find that the QT wallet fail to open the configuration file on Mac, when these is no default application for `*.conf` files.

Here is a feasible way to solve this bug. When `QDesktopServices::openUrl` fails to open `file:///path/bitcoin.conf` with its default application, use `QProcess::startDetached` to run `open -t /path/bitcoin.conf` command instead, so as to open the configuration file with system's default text editor.

For more details, see this PR https://github.com/bitcoin/bitcoin/pull/16044.

**Comment by brianddk** [comment]
@shannon1916 BTW... Same thing happens on Windows 10 which doesn't provide a default association with `.conf` files.  Double clicking any `.conf` file and assigning a default app to it fixes the problem in windows as well.
