### ISSUE TITLE
 Wladimir J. van der Laan's PGP key is now expired

### ISSUE THREAD

**Issue by kleetus** [bitcoin/bitcoin#15417]
Please note that the key used to sign the SHASUMS.asc for the current release is now expired:

pub   rsa4096 2015-06-24 [SC] **[expired: 2019-02-14]**
      01EA5486DE18A882D4C2684590C8019E36C2E964
uid           [ expired] Wladimir J. van der Laan (Bitcoin Core binary release signing key) <laanwj@gmail.com>

**Comment by fanquake** [comment]
@laanwj Has bumped the expiration dates of the keys. See [here, line 192](http://www.erisian.com.au/bitcoin-core-dev/log-2019-02-11.html). Try `--refresh-keys`.

**Comment by laanwj** [comment]
Yes, I updated it on the 12th, you should receive a new signature with a more recent expiration date on refresh.
