### ISSUE TITLE
snap: Bitcoin Core + Ubuntu 19 - wayland-egl

### ISSUE THREAD

**Issue by braulioholtz** [bitcoin/bitcoin#15418]
**What behavior did you expect?**
Open Bitcoin Core

**What was the actual behavior (provide screenshots if the issue is GUI-related)?**
Opening Bitcoin Core generates error, through the bitcoin.qt command, the error it displays is
_This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"._
_Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb._
_Reinstalling the application may fix this problem._

I tried to reinstall and it did not work

**What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?** 
Snap
- 0.17.0.1 - Stable
- Beta
- Edge

**For the GUI-related issue on Linux provide names and versions of a distro, a desktop environment and a graphical shell (if relevant).** 
Ubuntu 19 - Gnome Beta 3.31.90

**Comment by braulioholtz** [comment]
I don't know why it worked now, problem solved

**Comment by MarcoFalke** [comment]
The `bitcoin` package was removed. Please backup your wallet and upgrade to the `bitcoin-core` package.

**Comment by MarcoFalke** [comment]
Let me know if this is still an issue and what the steps to reproduce are

![screenshot from 2019-03-04 14-34-39](https://user-images.githubusercontent.com/6399679/53757859-c3a09200-3e8a-11e9-9350-aa936b20df71.png)

**Comment by braulioholtz** [comment]
In terminal  "bitcoin-core.qt"
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

I reinstalled through the snap

**Comment by MarcoFalke** [comment]
Does this also happen on a vanilla Ubuntu 19.04? It worked for me (see screenshot above)

**Comment by braulioholtz** [comment]
On the login screen, if I am selected in the regular user, it works, but if I select Ubuntu with wayland it is that the program does not work for me

**Comment by MarcoFalke** [comment]
Thx.

For now, you can work around this by `DISABLE_WAYLAND=1 bitcoin-core.qt`

**Comment by MarcoFalke** [comment]
This has been fixed upstream
