### ISSUE TITLE
zapwallettxes

### ISSUE THREAD

**Issue by ikamran** [bitcoin/bitcoin#15422]
Hello,

During clearing a transaction i used zapwallettxes when start bitcoid 
now when i sent money to the wallet the balance still 0 and also the wallet dont show about 90$ of coins

https://www.blockchain.com/btc/address/32yF1MuqbUmKsGZE7jedkZV8PVJRuimRAu
 this address belong to my wallet
also i sent another 4$ coin to see if balance change but still it shows 0
https://www.blockchain.com/btc/tx/8f6d53cd7bb2ab784fc16652d518560ca43b3d354ac4c16616d95c057230b599

I am very confused of how to do now and why it doesnt show real balance

**Comment by jonasschnelli** [comment]
Have you completed the sync?
What does the progress bar tells you at the bottom of the main window if you use the GUI?
Or call `bitcoin-cli getblockchaininfo` to check your sync progress.

**Comment by Razasangi** [comment]
https://www.blockchain.com/btc/payment_request?address=32yF1MuqbUmKsGZE7jedkZV8PVJRuimRAu&message=Donation%0Ahttps://www.blockchain.com/btc/payment_request?address=32yF1MuqbUmKsGZE7jedkZV8PVJRuimRAu&message=Donation&amount_local=84&currency=USD&nosavecurrency=true%0A&amount_local=84&currency=USD&nosavecurrency=true

**Comment by ikamran** [comment]
it was synced before, but i am trying to load it again

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
