### ISSUE TITLE
Question: DEFAULT_MAX_TIME_ADJUSTMENT != MAX_FUTURE_BLOCK_TIME

### ISSUE THREAD

**Issue by cryptozeny** [bitcoin/bitcoin#15436]
https://github.com/bitcoin/bitcoin/blob/29e82e460e19818b420e7169ac8ed5248d6d0af9/src/timedata.h#L13

https://github.com/bitcoin/bitcoin/blob/29e82e460e19818b420e7169ac8ed5248d6d0af9/src/chain.h#L21

why different? IMHO both should be the same, or should be an associated number... :thinking:

**Comment by benthecarman** [comment]
`DEFAULT_MAX_TIME_ADJUSTMENT` refers to the limit of how different a peer's time can be vs `MAX_FUTURE_BLOCK_TIME` refers to how different a block's timestamp can be

**Comment by cryptozeny** [comment]
good to know thanks, but i am still confused. how to handle this...

**Comment by sipa** [comment]
They're completely unrelated. I don't understand what you mean by "handle it".

I'm going to close this. Questions like this about Bitcoin's design, as opposed to actual sofrware issues with the Bitcoin Core implementation, belong more on https://bitcoin.stackexchange.com or various fora.
