### ISSUE TITLE
Bitcoin core transaction created, but txid not found on blockchain explorers

### ISSUE THREAD

**Issue by lassy77** [bitcoin/bitcoin#15432]
Transaction created as same others, but status - 0/unconfirmed And txid nod found in block explorers Transaction ID: e9c858f852a1de7c70e6f8377f2147f3def1d4b1d85a5947d028bb9c13450318

How to succefuly complete this?
![2](https://user-images.githubusercontent.com/47716727/52914406-d63a9900-32d8-11e9-8b6b-802865cd9799.png)

**Comment by MarcoFalke** [comment]
To see why it was rejected, you can copy-paste the raw transaction (right click) and paste it in the debug window as `sendrawtransaction $The_tx_you_copied`

**Comment by promag** [comment]
Does it make sense to add a button there `Retry Send` when `depth == 0 && !inMempool`?

**Comment by MarcoFalke** [comment]
Issue by the same user: #15449
