### ISSUE TITLE
RFC including boost-process

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#15440]
#15382 and #15421 both need to execute commands, monitor their process and/or consume their `stdout`. At the moment they both add [boost-process](https://www.boost.org/doc/libs/1_64_0/doc/html/process.html).

There is also an alternative [cpp-subprocess](
https://github.com/arun11299/cpp-subprocess/blob/master/subprocess.hpp) which has less code, but probably also less review and doesn't work with Windows yet.

We currently ship Boost 1.64 so the corresponding boost-process code is [here](https://github.com/boostorg/process/tree/boost-1.64.0/include/boost).

Usage wise it's super simple.

The code is spread over at least a hundred small files, which makes it hard to understand the whole, although I'm it makes sense to someone more familiar with Boost. Each component seems well documented. I'm not sure how to go about reviewing this.

It includes the following other Boost components, outside of what we already directly include:

```cpp
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/algorithm/string/join.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/trim.hpp>
#include <boost/asio/async_result.hpp>
#include <boost/asio/buffer.hpp>
#include <boost/asio/dispatch.hpp>
#include <boost/asio/io_context.hpp>
#include <boost/asio/posix/stream_descriptor.hpp>
#include <boost/asio/post.hpp>
#include <boost/asio/read.hpp>
#include <boost/asio/signal_set.hpp>
#include <boost/asio/strand.hpp>
#include <boost/asio/streambuf.hpp>
#include <boost/asio/windows/object_handle.hpp>
#include <boost/asio/windows/stream_handle.hpp>
#include <boost/asio/write.hpp>
#include <boost/config.hpp>
#include <boost/core/ignore_unused.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/fusion/adapted/std_tuple.hpp>
#include <boost/fusion/algorithm/iteration/for_each.hpp>
#include <boost/fusion/algorithm/query/find_if.hpp>
#include <boost/fusion/algorithm/transformation/filter_if.hpp>
#include <boost/fusion/algorithm/transformation/transform.hpp>
#include <boost/fusion/container.hpp>
#include <boost/fusion/container/set/convert.hpp>
#include <boost/fusion/container/vector/convert.hpp>
#include <boost/fusion/iterator/deref.hpp>
#include <boost/fusion/sequence.hpp>
#include <boost/fusion/sequence/comparison/equal_to.hpp>
#include <boost/fusion/sequence/intrinsic/begin.hpp>
#include <boost/fusion/sequence/intrinsic/end.hpp>
#include <boost/fusion/sequence/intrinsic/has_key.hpp>
#include <boost/fusion/tuple.hpp>
#include <boost/fusion/view.hpp>
#include <boost/fusion/view/transform_view.hpp>
#include <boost/iterator/transform_iterator.hpp>
#include <boost/move/move.hpp>
#include <boost/none.hpp>
#include <boost/system/api_config.hpp>
#include <boost/system/error_code.hpp>
#include <boost/tokenizer.hpp>
#include <boost/type_index.hpp>
#include <boost/winapi/access_rights.hpp>
#include <boost/winapi/basic_types.hpp>
#include <boost/winapi/character_code_conversion.hpp>
#include <boost/winapi/config.hpp>
#include <boost/winapi/dll.hpp>
#include <boost/winapi/environment.hpp>
#include <boost/winapi/error_codes.hpp>
#include <boost/winapi/file_management.hpp>
#include <boost/winapi/get_current_process.hpp>
#include <boost/winapi/get_current_process_id.hpp>
#include <boost/winapi/get_last_error.hpp>
#include <boost/winapi/get_system_directory.hpp>
#include <boost/winapi/handle_info.hpp>
#include <boost/winapi/handles.hpp>
#include <boost/winapi/jobs.hpp>
#include <boost/winapi/overlapped.hpp>
#include <boost/winapi/pipes.hpp>
#include <boost/winapi/process.hpp>
#include <boost/winapi/shell.hpp>
#include <boost/winapi/show_window.hpp>
#include <boost/winapi/synchronization.hpp>
#include <boost/winapi/wait.hpp>
```

I'm not sure which of those we're already indirectly using.

I found the following includes, outside of what we already directly include:
```cpp
#include <features.h>
#include <initializer_list>
#include <io.h>
#include <iosfwd>
#include <istream>
#include <ostream>
#include <streambuf>
#include <system_error>
```

The lists were composed with `grep -rhw . -e '#include' --include=\*.{h,cpp,hpp} | sort | uniq` and `comm -23 boost bitcoin`.

**Comment by practicalswift** [comment]
@Sjors If the need is limited to running a process, wait for it to complete and capture the output then the number of lines needed to implement a function for that is likely less than the number of includes listed above? :-)

**Comment by Sjors** [comment]
@practicalswift you'd think so, right? :-)

That's indeed exactly what we need. Plus using `std::in` to pass in transactions that are too long to pass by argument. And it has to work on Windows.

**Comment by luke-jr** [comment]
As previously discussed, it should be an optional dependency initially, and a "second step" might be to use a bundled copy when the system boost is too old.

**Comment by promag** [comment]
@Sjors libuv experiment in https://github.com/promag/bitcoin/commit/eb452d7e5d2fbc65e2b2e05bdc59e5ad625b6de0

**Comment by Sjors** [comment]
The has been done in #15382
