### ISSUE TITLE
Transaction broadcasting failed

### ISSUE THREAD

**Issue by lassy77** [bitcoin/bitcoin#15449]
Cont: When i try to broadcast a raw hex transaction - all look nice, bitcoin-cli return a transaction id for the sended hex data, but i looking on blockchain explorer 
and nohing happens. A my txid not found, likely I dont have no one peers that known about it. In my debug log i not seen no one rejects for sendedded transaction, only inv\getdata\tx messagesd

bitcoin core version: v0.17.99.0-72bd4ab86-dirty
OS: Ubuntu 18.04

[tx.zip](https://github.com/bitcoin/bitcoin/files/2885742/tx.zip)

**Comment by MarcoFalke** [comment]
It might take several minutes for your transaction to propagate to every node (including explorers). You might want to check the fee of the tx via `getmempoolentry txid` and check that your mempool is built on top of the current chain via `getblockchaininfo` (if it wasn't, the tx could be invalid to other nodes)

**Comment by lassy77** [comment]
Yes, see it in mempool (with getrawmempool), then check with getmempoolentry - OK,
 but try find with block explorer - and nothing
txid: 4f07f6e3462401483d4cf79b090a13bd92c7ca1d5f10669c6597cba4452fe301

**Comment by sonofliberty** [comment]
I found a possible cause for this issue. I tried to send a transaction while the node is not connected to any peers (right after starting it up). Core will return a TXID as if everything worked, but if there are no peers to relay the TX to, then it will simply not hit the network at all.

`2019-03-15 05:34:43 CommitTransaction:
2019-03-15 05:34:43 keypool keep 3712
2019-03-15 05:34:43 AddToWallet [MY-TXID]  new
2019-03-15 05:34:43 Relaying wtx [MY-TXID]
2019-03-15 05:34:43 AddToWallet [MY-TXID]
2019-03-15 05:34:57 New outbound peer connected: version: 70015, blocks=567138, peer=0
2019-03-15 05:34:58 New outbound peer connected: version: 70015, blocks=567138, peer=1
2019-03-15 05:34:59 New outbound peer connected: version: 70015, blocks=567138, peer=2`

I had to manually broadcast the raw transaction to make the payment.

**Comment by MarcoFalke** [comment]
Obviously it won't propagate if you have no connections. You can rebroadcast with `resendwallettransactions` manually or wait for the wallet to rebroadcast automatically.

**Comment by jnewbery** [comment]
> You can rebroadcast with resendwallettransactions

`resendwallettransactions` is a test-only RPC and should not be used in production.

> wait for the wallet to rebroadcast automatically.

This is the correct way. txs are rebroadcast automatically at least once every 30 minutes.
