### ISSUE TITLE
gui: Opening wallet dialog doesn't close for certain wallet names

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#15455]
When you open wallets with exotic names, i.e `🦹🏿‍♂️` (Emoji Version 11), via the "Open Wallet" menu, the opening wallet dialog never closes, even after the wallet has finished loading.

![screen shot 2019-02-21 at 2 34 06 pm](https://user-images.githubusercontent.com/863730/53148554-012d3180-35e6-11e9-8a94-62c5fb023d40.png)

**Comment by promag** [comment]
Please tag 0.18.

**Comment by promag** [comment]
But was the wallet loaded?

**Comment by promag** [comment]
It is really weird such paths always trigger the bug. The following patch fixes it:
```diff
index bc88dd5e0..2e7cf65e9 100644
--- a/src/qt/bitcoingui.cpp
+++ b/src/qt/bitcoingui.cpp
@@ -396,6 +396,7 @@ void BitcoinGUI::createActions()
                     connect(activity, &OpenWalletActivity::opened, this, &BitcoinGUI::setCurrentWallet);
                     connect(activity, &OpenWalletActivity::finished, activity, &QObject::deleteLater);
                     connect(activity, &OpenWalletActivity::finished, dialog, &QObject::deleteLater);
+                    QMetaObject::invokeMethod(activity, "open", Qt::QueuedConnection);
                 });
             }
         });
diff --git a/src/qt/walletcontroller.cpp b/src/qt/walletcontroller.cpp
index c532ffbbf..fab86a791 100644
--- a/src/qt/walletcontroller.cpp
+++ b/src/qt/walletcontroller.cpp
@@ -59,7 +59,6 @@ OpenWalletActivity* WalletController::openWallet(const std::string& name, QWidge
 {
     OpenWalletActivity* activity = new OpenWalletActivity(this, name);
     activity->moveToThread(&m_activity_thread);
-    QMetaObject::invokeMethod(activity, "open", Qt::QueuedConnection);
     return activity;
 }
```
@fanquake mind testing it? The bug happens because the signal `OpenWalletActivity::finished` is emitted before the connection to this signal is made.

And I'm inclined to push this to 0.18 branch only due to the simple change.

However for master I'm refactoring the `WalletController` and `OpenWalletActivity` which can auto fix this issue.

**Comment by fanquake** [comment]
@promag I've tested that the above patch fixes this issue. Using it I can open a wallet named `🦹🏿‍♂️` from the `Open Wallet` menu, and the progress dialog closes when the wallet is loaded.
