### ISSUE TITLE
Some functional tests fail on native windows when tempdir has unicode chars in the path

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15460]
The following tests are not emoji-safe:

```
TEST                     | STATUS    | DURATION

feature_config_args.py   | ✖ Failed  | 17 s
feature_includeconf.py   | ✖ Failed  | 11 s
interface_bitcoin_cli.py | ✖ Failed  | 8 s
wallet_multiwallet.py    | ✖ Failed  | 6 s

ALL                      | ✖ Failed  | 42 s (accumulated) 
Runtime: 17 s
```

**Comment by MarcoFalke** [comment]
Tested by using the gitian binaries and the test framework from master.

**Comment by ken2812221** [comment]
Are you using python 3.7 with enviroment `PYTHONUTF8=1`? This is the only way that make python read/write anything with UTF-8 on Windows.

**Comment by MarcoFalke** [comment]
Thanks, that works for most of them but not for `wallet_multiwallet`, it seems
