### ISSUE TITLE
Make check && sudo make install errors on compile

### ISSUE THREAD

**Issue by theodoremt** [bitcoin/bitcoin#15467]
Bitcoin Core v0.17.1
Running Ubuntu on Win10 through WSL

smooth build until command: $ make check && sudo make install where:
 ***2 failures are detected in the test module "Bitcoin Test Suite"

Screenshot:
***** 2 failures are detected in the test module "Bitcoin Test Suite"
Makefile:10602: recipe for target 'test/util_tests.cpp.test' failed
make[3]: *** [test/util_tests.cpp.test] Error 1
make[3]: Leaving directory '/home/teddyt/bitcoin/src'
Makefile:10352: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/teddyt/bitcoin/src'
Makefile:10040: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/teddyt/bitcoin/src'
Makefile:774: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1**

Any assistance would be greatly appreciated. Thank you.

**Comment by ken2812221** [comment]
WSL is not fully compatible with POSIX. So the test suite would fail. Please use native Windows binary instead. [docs/build_windows.md]
