### ISSUE TITLE
[Documentation] limitations in processing inventory

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#15476]
#14897 has introduced new limits which not only causes nightmares for copy-pasta devs but also introduces some undesired behaviour.

MEMPOOL requests are answered as an unlimited batch. The newly introduced limits are forcing us to drop further incoming transactions if the mempool size exceeds 100. Our peers will in no way bother to send us these again because they are filtered by `PushInventory` as well as `timeLastMempoolReq`.

Unless those transactions are included in a block, we'll have no way to know about them, especially when we're behind a gateway node without further peers.

**Comment by sdaftuar** [comment]
Do you have a test case for reproducing the issue you're encountering?  My understanding of the code is that we'll just request transactions 100 at a time; I don't see why this would break anything.  (It would indeed be a bug if we are unable to request all the transactions from a peer that is announcing more than 100 transactions at once.)

**Comment by HashUnlimited** [comment]
Well, "potential bug" would maybe describe it better. Missed out the `NetMsgType::MEMPOOL` has silently been deprecated and isn't used anymore. However, BIP35 is still present in all Developer references and it won't work with the current code. So some little hint would be nice.

**Comment by sdaftuar** [comment]
It sounds like you're saying that we've broken the ability to eventually request all the transactions from a peer, if they announce some large number at a time.  If that is true, it would be a bug -- do you have a test case that reproduces such a problem, or is this just speculation?

**Comment by HashUnlimited** [comment]
it isn't, actually happened on my test environment where I'm issuing the mempool message as a first request when a peer is fully connected.

**Comment by sdaftuar** [comment]
Can you share a minimal patch on top of master that demonstrates the issue?

**Comment by HashUnlimited** [comment]
Sure but that'll take some time... Meanwhile feel free to have a look at these lines as that's the sequence how I was tracing it:

```
            // Respond to BIP35 mempool requests
            if (fSendTrickle && pto->fSendMempool) {
                auto vtxinfo = mempool.infoAll();
                pto->fSendMempool = false;
                CAmount filterrate = 0;
                {
                    LOCK(pto->cs_feeFilter);
                    filterrate = pto->minFeeFilter;
                }

                LOCK(pto->cs_filter);

                for (const auto& txinfo : vtxinfo) {
                    const uint256& hash = txinfo.tx->GetHash();
                    CInv inv(MSG_TX, hash);
                    pto->setInventoryTxToSend.erase(hash);
                    if (filterrate) {
                        if (txinfo.feeRate.GetFeePerK() < filterrate)
                            continue;
                    }
                    if (pto->pfilter) {
                        if (!pto->pfilter->IsRelevantAndUpdate(*txinfo.tx)) continue;
                    }
                    pto->filterInventoryKnown.insert(hash);
                    vInv.push_back(inv);
                    if (vInv.size() == MAX_INV_SZ) {
                        connman->PushMessage(pto, msgMaker.Make(NetMsgType::INV, vInv));
                        vInv.clear();
                    }
                }
                pto->timeLastMempoolReq = GetTime();
            }
```
There the code is definitely attempting to send all of the mempool contents in a batch (MAX_INV_SIZE is still 50000). 
Same time the receiving peer is identifying the CInv as MSG_TX and doing as commanded:
```
                pfrom->AddInventoryKnown(inv);
                if (fBlocksOnly) {
                    LogPrint(BCLog::NET, "transaction (%s) inv sent in violation of protocol peer=%d\n", inv.hash.ToString(), pfrom->GetId());
                } else if (!fAlreadyHave && !fImporting && !fReindex && !IsInitialBlockDownload()) {
                    RequestTx(State(pfrom->GetId()), inv.hash, nNow);
                }
```
where the `RequestTx ` is stopping the show:
```
    CNodeState::TxDownloadState& peer_download_state = state->m_tx_download;
    if (peer_download_state.m_tx_announced.size() >= MAX_PEER_TX_ANNOUNCEMENTS || peer_download_state.m_tx_announced.count(txid)) {
        // Too many queued announcements from this peer, or we already have
        // this announcement
        return;
    }
```

**Comment by HashUnlimited** [comment]
Will try to reproduce reliably but it might well be that I'm chasing a ghost here. For now it looks like some of my gateway nodes are crapped out, logs suggest so. Needed a while to consider that as those are released code and I'm playing with master on the private side.
Will report back if there are other findings. Closing for now, sorry for any inconvenience.
