### ISSUE TITLE
State of the Repo Report, February 2019

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#15488]
# State of the Repo Report, February 2019

## Introduction

For all fans of statistics – enjoy! 🤓

The "median open pull request" adds 47.5&nbsp;lines, removes 13&nbsp;lines and touches 3&nbsp;files.

The total set of open pull requests adds 42&nbsp;064&nbsp;lines, removes 13&nbsp;721&nbsp;lines and touches 1&nbsp;629&nbsp;distinct files.

The repo contains 481&nbsp;587 lines of text and 1&nbsp;683 files.

There are currently 258 open pull requests from in total 78 contributors.

If all open pull requests were merged the project line count would grow by roughly 5%.

Previous edition: [State of the Repo, January 2019](https://github.com/bitcoin/bitcoin/issues/15180)

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines added | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 8885&nbsp;(21%) | -1212&nbsp;(9%) | 7673&nbsp;(27%) | 135 | 7&nbsp;(3%) |
| 2 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 4126&nbsp;(10%) | -511&nbsp;(4%) | 3615&nbsp;(13%) | 48 | 12&nbsp;(5%) |
| 3 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 3315&nbsp;(8%) | -604&nbsp;(4%) | 2711&nbsp;(10%) | 74 | 14&nbsp;(5%) |
| 4 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 3177&nbsp;(8%) | -439&nbsp;(3%) | 2738&nbsp;(10%) | 94 | 24&nbsp;(9%) |
| 5 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 2240&nbsp;(5%) | -1202&nbsp;(9%) | 1038&nbsp;(4%) | 123 | 12&nbsp;(5%) |
| 6 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 1756&nbsp;(4%) | -1664&nbsp;(12%) | 92&nbsp;(0%) | 16 | 7&nbsp;(3%) |
| 7 | [jimpo](https://github.com/bitcoin/bitcoin/pulls/jimpo) | 1574&nbsp;(4%) | -334&nbsp;(2%) | 1240&nbsp;(4%) | 31 | 3&nbsp;(1%) |
| 8 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 1552&nbsp;(4%) | -2564&nbsp;(19%) | -1012&nbsp;(-) | 55 | 9&nbsp;(3%) |
| 9 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 1307&nbsp;(3%) | -255&nbsp;(2%) | 1052&nbsp;(4%) | 44 | 8&nbsp;(3%) |
| 10 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 1280&nbsp;(3%) | -113&nbsp;(1%) | 1167&nbsp;(4%) | 30 | 4&nbsp;(2%) |
| 11 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 1171&nbsp;(3%) | -873&nbsp;(6%) | 298&nbsp;(1%) | 94 | 23&nbsp;(9%) |
| 12 | [mgrychow](https://github.com/bitcoin/bitcoin/pulls/mgrychow) | 1083&nbsp;(3%) | -80&nbsp;(1%) | 1003&nbsp;(4%) | 25 | 1&nbsp;(0%) |
| 13 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 959&nbsp;(2%) | -28&nbsp;(0%) | 931&nbsp;(3%) | 18 | 1&nbsp;(0%) |
| 14 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 881&nbsp;(2%) | -380&nbsp;(3%) | 501&nbsp;(2%) | 44 | 19&nbsp;(7%) |
| 15 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 862&nbsp;(2%) | -133&nbsp;(1%) | 729&nbsp;(3%) | 30 | 2&nbsp;(1%) |
| 16 | [sdaftuar](https://github.com/bitcoin/bitcoin/pulls/sdaftuar) | 718&nbsp;(2%) | -473&nbsp;(3%) | 245&nbsp;(1%) | 18 | 4&nbsp;(2%) |
| 17 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 555&nbsp;(1%) | -393&nbsp;(3%) | 162&nbsp;(1%) | 30 | 9&nbsp;(3%) |
| 18 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 440&nbsp;(1%) | -47&nbsp;(0%) | 393&nbsp;(1%) | 7 | 3&nbsp;(1%) |
| 19 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 417&nbsp;(1%) | -9&nbsp;(0%) | 408&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 20 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 406&nbsp;(1%) | -87&nbsp;(1%) | 319&nbsp;(1%) | 28 | 7&nbsp;(3%) |
| 21 | [MeshCollider](https://github.com/bitcoin/bitcoin/pulls/MeshCollider) | 384&nbsp;(1%) | -170&nbsp;(1%) | 214&nbsp;(1%) | 7 | 2&nbsp;(1%) |
| 22 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 368&nbsp;(1%) | -173&nbsp;(1%) | 195&nbsp;(1%) | 17 | 4&nbsp;(2%) |
| 23 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 341&nbsp;(1%) | -319&nbsp;(2%) | 22&nbsp;(0%) | 35 | 1&nbsp;(0%) |
| 24 | [251Labs](https://github.com/bitcoin/bitcoin/pulls/251Labs) | 315&nbsp;(1%) | -88&nbsp;(1%) | 227&nbsp;(1%) | 23 | 2&nbsp;(1%) |
| 25 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 313&nbsp;(1%) | -34&nbsp;(0%) | 279&nbsp;(1%) | 8 | 3&nbsp;(1%) |
| 26 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 267&nbsp;(1%) | -80&nbsp;(1%) | 187&nbsp;(1%) | 5 | 2&nbsp;(1%) |
| 27 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 253&nbsp;(1%) | -68&nbsp;(0%) | 185&nbsp;(1%) | 7 | 2&nbsp;(1%) |
| 28 | [TheBlueMatt](https://github.com/bitcoin/bitcoin/pulls/TheBlueMatt) | 251&nbsp;(1%) | -53&nbsp;(0%) | 198&nbsp;(1%) | 18 | 2&nbsp;(1%) |
| 29 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 248&nbsp;(1%) | -226&nbsp;(2%) | 22&nbsp;(0%) | 32 | 3&nbsp;(1%) |
| 30 | [benthecarman](https://github.com/bitcoin/bitcoin/pulls/benthecarman) | 242&nbsp;(1%) | -59&nbsp;(0%) | 183&nbsp;(1%) | 19 | 6&nbsp;(2%) |
| 31 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 224&nbsp;(1%) | -97&nbsp;(1%) | 127&nbsp;(0%) | 15 | 3&nbsp;(1%) |
| 32 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 217&nbsp;(1%) | -13&nbsp;(0%) | 204&nbsp;(1%) | 3 | 1&nbsp;(0%) |
| 33 | [ken2812221](https://github.com/bitcoin/bitcoin/pulls/ken2812221) | 201&nbsp;(0%) | -134&nbsp;(1%) | 67&nbsp;(0%) | 17 | 3&nbsp;(1%) |
| 34 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 194&nbsp;(0%) | -225&nbsp;(2%) | -31&nbsp;(-) | 7 | 1&nbsp;(0%) |
| 35 | [lionello](https://github.com/bitcoin/bitcoin/pulls/lionello) | 191&nbsp;(0%) | -15&nbsp;(0%) | 176&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 36 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 130&nbsp;(0%) | -100&nbsp;(1%) | 30&nbsp;(0%) | 8 | 3&nbsp;(1%) |
| 37 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 118&nbsp;(0%) | -32&nbsp;(0%) | 86&nbsp;(0%) | 11 | 2&nbsp;(1%) |
| 38 | [MapleLaker](https://github.com/bitcoin/bitcoin/pulls/MapleLaker) | 89&nbsp;(0%) | -1&nbsp;(0%) | 88&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 39 | [conscott](https://github.com/bitcoin/bitcoin/pulls/conscott) | 87&nbsp;(0%) | -61&nbsp;(0%) | 26&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 40 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 87&nbsp;(0%) | -6&nbsp;(0%) | 81&nbsp;(0%) | 6 | 2&nbsp;(1%) |
| 41 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 83&nbsp;(0%) | -9&nbsp;(0%) | 74&nbsp;(0%) | 5 | 1&nbsp;(0%) |
| 42 | [greenaddress](https://github.com/bitcoin/bitcoin/pulls/greenaddress) | 80&nbsp;(0%) | -33&nbsp;(0%) | 47&nbsp;(0%) | 10 | 1&nbsp;(0%) |
| 43 | [joemphilips](https://github.com/bitcoin/bitcoin/pulls/joemphilips) | 80&nbsp;(0%) | -3&nbsp;(0%) | 77&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 44 | [ch4ot1c](https://github.com/bitcoin/bitcoin/pulls/ch4ot1c) | 76&nbsp;(0%) | -87&nbsp;(1%) | -11&nbsp;(-) | 11 | 1&nbsp;(0%) |
| 45 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 65&nbsp;(0%) | -25&nbsp;(0%) | 40&nbsp;(0%) | 6 | 2&nbsp;(1%) |
| 46 | [adamjonas](https://github.com/bitcoin/bitcoin/pulls/adamjonas) | 49&nbsp;(0%) | -9&nbsp;(0%) | 40&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 47 | [darosior](https://github.com/bitcoin/bitcoin/pulls/darosior) | 43&nbsp;(0%) | -2&nbsp;(0%) | 41&nbsp;(0%) | 2 | 2&nbsp;(1%) |
| 48 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 35&nbsp;(0%) | -30&nbsp;(0%) | 5&nbsp;(0%) | 6 | 2&nbsp;(1%) |
| 49 | [kodslav](https://github.com/bitcoin/bitcoin/pulls/kodslav) | 31&nbsp;(0%) | -5&nbsp;(0%) | 26&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 50 | [Csi18nAlistairMann](https://github.com/bitcoin/bitcoin/pulls/Csi18nAlistairMann) | 27&nbsp;(0%) | -1&nbsp;(0%) | 26&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 51 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2&nbsp;(0%) | 20&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 52 | [tecnovert](https://github.com/bitcoin/bitcoin/pulls/tecnovert) | 22&nbsp;(0%) | -21&nbsp;(0%) | 1&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 53 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 20&nbsp;(0%) | -2&nbsp;(0%) | 18&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 54 | [marcoagner](https://github.com/bitcoin/bitcoin/pulls/marcoagner) | 20&nbsp;(0%) | -2&nbsp;(0%) | 18&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 55 | [mrwhythat](https://github.com/bitcoin/bitcoin/pulls/mrwhythat) | 20&nbsp;(0%) | -3&nbsp;(0%) | 17&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 56 | [stevenroose](https://github.com/bitcoin/bitcoin/pulls/stevenroose) | 19&nbsp;(0%) | -13&nbsp;(0%) | 6&nbsp;(0%) | 2 | 2&nbsp;(1%) |
| 57 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 18&nbsp;(0%) | -13&nbsp;(0%) | 5&nbsp;(0%) | 4 | 1&nbsp;(0%) |
| 58 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 18&nbsp;(0%) | -10&nbsp;(0%) | 8&nbsp;(0%) | 4 | 1&nbsp;(0%) |
| 59 | [JBaczuk](https://github.com/bitcoin/bitcoin/pulls/JBaczuk) | 15&nbsp;(0%) | -16&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 60 | [GreatSock](https://github.com/bitcoin/bitcoin/pulls/GreatSock) | 11&nbsp;(0%) | -6&nbsp;(0%) | 5&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 61 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 11&nbsp;(0%) | -8&nbsp;(0%) | 3&nbsp;(0%) | 2 | 2&nbsp;(1%) |
| 62 | [gkrizek](https://github.com/bitcoin/bitcoin/pulls/gkrizek) | 11&nbsp;(0%) | -3&nbsp;(0%) | 8&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 63 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -3&nbsp;(0%) | 8&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 64 | [LeandroRocha84](https://github.com/bitcoin/bitcoin/pulls/LeandroRocha84) | 9&nbsp;(0%) | -5&nbsp;(0%) | 4&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 65 | [kazcw](https://github.com/bitcoin/bitcoin/pulls/kazcw) | 7&nbsp;(0%) | -9&nbsp;(0%) | -2&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 66 | [pedrobranco](https://github.com/bitcoin/bitcoin/pulls/pedrobranco) | 7&nbsp;(0%) | -2&nbsp;(0%) | 5&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 67 | [marcuswin](https://github.com/bitcoin/bitcoin/pulls/marcuswin) | 5&nbsp;(0%) | -8&nbsp;(0%) | -3&nbsp;(-) | 3 | 1&nbsp;(0%) |
| 68 | [sp4ke](https://github.com/bitcoin/bitcoin/pulls/sp4ke) | 5&nbsp;(0%) | -3&nbsp;(0%) | 2&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 69 | [d3spwn](https://github.com/bitcoin/bitcoin/pulls/d3spwn) | 4&nbsp;(0%) | -2&nbsp;(0%) | 2&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 70 | [kostyantyn](https://github.com/bitcoin/bitcoin/pulls/kostyantyn) | 4&nbsp;(0%) | -7&nbsp;(0%) | -3&nbsp;(-) | 3 | 1&nbsp;(0%) |
| 71 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 3&nbsp;(0%) | -4&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 72 | [HatboyWonder](https://github.com/bitcoin/bitcoin/pulls/HatboyWonder) | 2&nbsp;(0%) | -4&nbsp;(0%) | -2&nbsp;(-) | 2 | 1&nbsp;(0%) |
| 73 | [bpay](https://github.com/bitcoin/bitcoin/pulls/bpay) | 2&nbsp;(0%) | -2&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 74 | [seth586](https://github.com/bitcoin/bitcoin/pulls/seth586) | 2&nbsp;(0%) | -3&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 75 | [dooglus](https://github.com/bitcoin/bitcoin/pulls/dooglus) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 76 | [puchu](https://github.com/bitcoin/bitcoin/pulls/puchu) | 1&nbsp;(0%) | -1&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 77 | [sangaman](https://github.com/bitcoin/bitcoin/pulls/sangaman) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 78 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6&nbsp;(0%) | -6&nbsp;(-) | 2 | 1&nbsp;(0%) |

**Comment by fanquake** [comment]
Thanks 📈 📊 .
