### ISSUE TITLE
make check failure on x64 with MacOS 10.14.3, qt stable 5.12.1.

### ISSUE THREAD

**Issue by brentkearney** [bitcoin/bitcoin#15480]
I get this error, on x64 with MacOS 10.14.3, qt stable 5.12.1.

```
$ brew info qt | head -n1
qt: stable 5.12.1 (bottled), HEAD [keg-only]
$ uname -a
Darwin f008.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

```
$ make check
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
FAIL: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.17.99
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

Promag's comment in [#14011](https://github.com/bitcoin/bitcoin/pull/14011#issuecomment-431380010) to specify `-platform minimal` did not work for me:

```
$ src/qt/test/test_bitcoin-qt -platform minimal
-bash: src/qt/test/test_bitcoin-qt: Permission denied
$ sudo src/qt/test/test_bitcoin-qt -platform minimal
Password:
sudo: unable to execute src/qt/test/test_bitcoin-qt: Permission denied
```

Note that this is not a file permissions issue:
```
$ ls -l src/qt/test/test_bitcoin-qt 
-rwxr-xr-x  1 brent  staff  15815180 24 Feb 01:54 src/qt/test/test_bitcoin-qt
```

I also get "permission denied" when trying to copy the binary from the
https://bitcoincore.org/bin/bitcoin-core-0.17.1/bitcoin-0.17.1-osx.dmg image. Attempting to run it directly from the disk image produces the error message, "You can't open the application "Bitcoin Core" because it is not supported on this type of Mac."

_Originally posted by @brentkearney in https://github.com/bitcoin/bitcoin/issues/14349#issuecomment-466752995_

**Comment by fanquake** [comment]
@brentkearney What is in `src/test-suite.log` when `make check` fails?

**Comment by brentkearney** [comment]
```
$ cat src/test-suite.log 
==============================================
   Bitcoin Core 0.17.99: src/test-suite.log
==============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

../build-aux/test-driver: line 107: ./qt/test/test_bitcoin-qt: Permission denied
FAIL qt/test/test_bitcoin-qt (exit status: 126)
```

**Comment by brentkearney** [comment]
I finally discovered what was going on here: Sophos Anti-Virus blocks access to Bitcoin binaries!

It has a feature called on-access scanning, and one Scan option is "Adware and PUAs" ("potentially unwanted application"), and "When threat is found" was set to "Deny access". When I disabled it, `make check` worked, and I am now running the GUI client. The Sophos software does have an "Excluded Items" feature, so it can still be used with "wanted" applications.

**Comment by brentkearney** [comment]
I finally discovered what was going on here: Sophos Anti-Virus blocks access to Bitcoin binaries!

It has a feature called on-access scanning, and one Scan option is "Adware and PUAs" ("potentially unwanted application"), and "When threat is found" was set to "Deny access". When I disabled it, `make check` worked, and I am now running the GUI client. The Sophos software does have an "Excluded Items" feature, so it can still be used with "wanted" applications.

**Comment by Mobilunity-Com** [comment]
Hey! If you need help with Qt I know where you can find it. Let me share with you useful article about [Qt developer](https://mobilunity.com/blog/hire-qt-developer-for-the-project/) who easily can help you over here to solve all issues you have.
