### ISSUE TITLE
Importing an address that you have sent to does not update the corresponding transactions 

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#15498]
I sent from address X to address Y.  I already had X as a watch only address but not Y.  After the transaction was confirmed it my node did not change the transaction from a "sent to" to a "payment to yourself" and needed to restart Bitcoin Core to see the change.

**Comment by promag** [comment]
Please tag GUI.

Looks like the following isn't updated:
https://github.com/bitcoin/bitcoin/blob/6cf81b01b48e871a35072dd08e7735c3ba42528c/src/qt/transactionrecord.h#L118

**Comment by MarcoFalke** [comment]
Duplicate of #11477 ?

**Comment by hebasto** [comment]
Moved to bitcoin-core/gui#641.
