### ISSUE TITLE
Possible memory leak with DEBUG_LOCKORDER

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#1550]
About boost::thread_specific_ptr: "Note: on some platforms, cleanup of thread-specific data is not performed for threads created with the platform's native API. On those platforms such cleanup is only done for threads that are started with boost::thread unless boost::on_thread_exit() is called manually from that thread."
Thus the lockstack object in sync.cpp may never be deleted.  This is only really an issue due to recent RPC changes where long-running nodes may have seen many, many RPC threads.

**Comment by laanwj** [comment]
The number of RPC threads created by bitcoind is bounded at `-rpcthreads=<n>`. These are created during initialization and terminated at shutdown. The memory leak will be thus be bounded to that number too. I don't see this as a serious issue.
