### ISSUE TITLE
Why Bitcoin Core is a monolith?

### ISSUE THREAD

**Issue by CodersBrothers** [bitcoin/bitcoin#15515]
I don't understand why Bitcoin Core software was designed as a monolith and not as a microservices architecture.

Now the node, the gui, the cli, the wallet are all in one. 

For example, some people don't need the GUI, others don't need the CLI, or others don't need the wallet.

For example, some people can install a cli, set the node, and use it remotely, or some people can be take a wallet with a remote node.

So my question is, Why the core team deceided a monolith architecture? I don't find any reasonable fact for do this.

**Comment by luke-jr** [comment]
The goal is to eventually split it up, but it's not easy.

**Comment by practicalswift** [comment]
@CodersBrothers 

I'm not qualified to answer the question about the rationale behind design decisions made roughly ten years ago but these are some recent open pull requests that might be of interest:

* #6714: "A plan for abstracting out libconsensus"
* #10102: [Multiprocess Bitcoin](https://github.com/ryanofsky/bitcoin/blob/pr/ipc/doc/multiprocess.md)
* #10973: "Refactor: separate wallet from node"

AFAIK no one opposes the idea of splitting it up, but doing so is non-trivial.

**Comment by fanquake** [comment]
Closing. If you have more general/historical questions about the code base, the [bitcoin stack exchange](https://bitcoin.stackexchange.com) might be a better place to ask them.
