### ISSUE TITLE
RPC unloadwallet does not close wallet files.

### ISSUE THREAD

**Issue by AliceOJJm** [bitcoin/bitcoin#15526]
The only way to use over 500 wallets is to reload node or manually close file descryptors. Otherwise system does not cope with large amount of opened files. Should this work like that?
Would really appreciate suggestion on how to work with over 500 wallets (not at the same time), not having to reload node.

**Comment by promag** [comment]
What version are you using?

**Comment by AliceOJJm** [comment]
Bitcoin Core version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8 (release build)

**Comment by achow101** [comment]
I believe this was reported in #15291 and fixed by #15297.

**Comment by promag** [comment]
I can't tell if that version includes #15297.

**Comment by AliceOJJm** [comment]
I've built master as https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md says
How do I launch it?

**Comment by AliceOJJm** [comment]
I've tested it with Bitcoin Core version v0.18.99.0-14023c9 (release build) and everything works as described in #15297.
Thanks a lot!!

**Comment by promag** [comment]
Thanks, you can close this.
