### ISSUE TITLE
Make fails in osx 10.14.3

### ISSUE THREAD

**Issue by fireboyrocks** [bitcoin/bitcoin#15523]
Trying to compile Bitcoin on a new machine and followed the usual steps at [https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md](url).  `./autogen.sh` and `./configure` works fine. However, when attempting `make`, I get the following error:

`/opt/local/bin/ranlib: object: libbitcoin_server.a(libbitcoin_server_a-addrdb.o) malformed object (unknown load command 1)`
`/opt/local/bin/ar: internal ranlib command failed`
`make[2]: *** [libbitcoin_server.a] Error 1`
`make[1]: *** [all-recursive] Error 1`
`make: *** [all-recursive] Error 1`

I am attaching the config.log file. 

Kindly help.
[config.log](https://github.com/bitcoin/bitcoin/files/2926630/config.log)

**Comment by fanquake** [comment]
Try a `make clean`, or a `git clean -fx` and then re-run `./autogen.sh`, `./configure`, `make check`.

**Comment by fireboyrocks** [comment]
I did as you mentioned but the same error persists. 
[config.log](https://github.com/bitcoin/bitcoin/files/2926835/config.log)

**Comment by laanwj** [comment]
looks like there's lots of issues with  10.14.3, though #15480 seems to be a different error

**Comment by fireboyrocks** [comment]
I have successfully attempted `make`. Actually, both Homebrew and Macports were present in my laptop. I uninstalled Macports and, after that, everything was good. 

Thank you for your help.
