### ISSUE TITLE
For the value of the send and receive satoshi of the qt-wallet.

### ISSUE THREAD

**Issue by Ghrogy** [bitcoin/bitcoin#15540]
@jonasschnelli 
In the Send and Receive menus, the Amount value is displayed as blank.
This can confuse those who do not know the Satoshi unit.
Here are suggestions.

Default;
![image](https://user-images.githubusercontent.com/37474804/53825932-cef2db00-3fba-11e9-8e69-95e21ad7fb1c.png)

![image](https://user-images.githubusercontent.com/37474804/53825974-e5009b80-3fba-11e9-9698-96d000532e30.png)

Requires modification of the initial value as follows;
![image](https://user-images.githubusercontent.com/37474804/53826009-f8ac0200-3fba-11e9-8a24-4c48d8186cda.png)

**Comment by sipa** [comment]
wth is sugar?

**Comment by MarcoFalke** [comment]
This issue tracker is used to track technical issues related to the Bitcoin Core code base.

**Comment by cryptozeny** [comment]
@sipa 
Sorry to use the Sugar screenshot. I forgot to tell him to change to Bitcoin.

He is a designer who is developing Sugar with me. When I was developing GUI with him, I thought his idea was good.

He will upload his idea back to version with Bitcoin 0.18 (or 0.17). Then look at his ideas again.

**Comment by cryptozeny** [comment]
@MarcoFalke 
Thank you for your good feedback. But can not we make a QT GUI design proposal here?

**Comment by sipa** [comment]
I have no idea what you're suggesting.

**Comment by MarcoFalke** [comment]
> But can not we make a QT GUI design proposal here?

Not as an issue. Please propose your changes as a pull request

**Comment by Ghrogy** [comment]
The problem is that the starting value is not listed as '0.00000000'.
If it was written from the beginning, minor problems can disappear.

**Comment by cryptozeny** [comment]
The place to write down the amount is `blank`. If we change it to `0.00000000`, we can understand it more intuitively. Let's listen to him again for details. @Ghrogy

**Comment by MarcoFalke** [comment]
The default value should indeed be blank (as it is now) and you are supposed to type (or copy-paste) the value you want to send

**Comment by cryptozeny** [comment]
@MarcoFalke OK I understood. He will make a awesome PR with Photoshop :)

**Comment by Tanita2529** [comment]
reply@reply.github.com

**Comment by Tanita2529** [comment]
reply@reply.github.com

ในวันที่ พ. 6 มี.ค. 2019 00:50 Pieter Wuille <notifications@github.com>
เขียนว่า:
