### ISSUE TITLE
bitcoin-cli does'nt have "getnewaddress" method

### ISSUE THREAD

**Issue by altobenz** [bitcoin/bitcoin#15570]
I have installed bitcoin core running on my local machine.
I want to create a new address using bitcoin-cli, executing a command as follows then an error message was displayed.
How can I solve it?

```
$ bitcoin-cli getnewaddress
error code: -32601
error message:
Method not found
```

The version of bitcoin-core is as follows.
```
$ bitcoin-cli -version
Bitcoin Core RPC client version v0.18.0.0-742f7dd97
```

The machine running bitcoin core is virtual machine on VirtualBox on Windows7.
The guest OS is ubuntu server and version is as follows.
```
$ uname -a
Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fanquake** [comment]
How did you compile Core? My guess is that `Berkeley DB` wasn't available at compile time, or that you've inadvertently configured/run with `--disable-wallet`.

**Comment by promag** [comment]
What is the output of `$ bitcoin-cli listwallets`?

**Comment by altobenz** [comment]
```
$ bitcoin-cli listwallets
error code: -32601
error message:
Method not found

```
Thank you for your comment.
I will try recompile the source codes.
It seems that Berkeley DB wasn't available.

**Comment by promag** [comment]
@altobenz then I guess you can close this?
