### ISSUE TITLE
build: Default size for the LXC disk is no longer enough

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#15574]
My favorite configuration for gitian building is Linux Mint 19.1 (based on Ubuntu 18.04) with LXC 3.0.3.

Faced disk space issues. This `gitian-builder` patch works well:
```
diff --git a/bin/make-base-vm b/bin/make-base-vm
index 916c11f..152f8bc 100755
--- a/bin/make-base-vm
+++ b/bin/make-base-vm
@@ -264,7 +264,7 @@ if [ $LXC = "1" ]; then
       fi
     fi
   fi
-  dd if=/dev/zero of=$OUT-lxc bs=1M count=1 seek=10240
+  dd if=/dev/zero of=$OUT-lxc bs=1M count=1 seek=15360
   /sbin/mkfs.ext4 -F $OUT-lxc
   t=`mktemp -d gitian.XXXXXXXX`
   sudo mount $OUT-lxc $t
```

Refs:
- https://github.com/bitcoin/bitcoin/issues/15541#issuecomment-470160960 and https://github.com/bitcoin/bitcoin/pull/15549#issuecomment-470330012 by @laanwj 
- https://github.com/devrandom/gitian-builder/pull/172 by @luke-jr

**Comment by laanwj** [comment]
Tested ACK (well, I tested wih 12240 so this size should certainly be enough)

**Comment by luke-jr** [comment]
Eh? make-base-vm doesn't work with bionic at all though...

**Comment by hebasto** [comment]
@laanwj 
> Eh, why didn't you open this PR on the gitian repository, there's nothing we can do with this her

I cannot reproduce the issue reliably.
Is it ok to increase LXC disk just for safety?

**Comment by hebasto** [comment]
https://github.com/devrandom/gitian-builder/pull/212 has been merged now.
