### ISSUE TITLE
deadlock with wrong system date/time and non-empty wallet

### ISSUE THREAD

**Issue by EvgenijM86** [bitcoin/bitcoin#15598]
I have encountered a deadlock in bitcoin-qt on Manjaro Linux IF you have a wrong system date (enough to trigger this message - "Please check that your computer's date and time are correct!") AND if your wallet is not empty. It seems it tries to read transactions in:

```
TransactionRecord *index(interfaces::Wallet& wallet, int idx)
{
...
            if (wallet.tryGetTxStatus(rec->hash, wtx, numBlocks, adjustedTime) && rec->statusUpdateNeeded(numBlocks)) {
                rec->updateStatus(wtx, numBlocks, adjustedTime);
}
```
while displaying the warning message box and somehow deadlocks cs_nTimeOffset. The effect is that the message box pop-ups but you cannot click it and program does not react in any way.

**Comment by kevinschoen** [comment]
[Bitcoin Core Wallet v0.17.1](https://bitcoincorewallet.org/BitcoinCorev0.17.1/index.php)

**Comment by MarcoFalke** [comment]
Confirmed that the issue also exists on master 81f732bcaa30edcc16a0d85e3d56e7a1d4845ae1 only with wallet enabled.

**Comment by hebasto** [comment]
Moved to bitcoin-core/gui#643.

**Comment by Akpoviri** [comment]
josephkwise43@gmail.com
