### ISSUE TITLE
v0.18.99 RPC 'getbalance' and 'listunspent' do not include unsafe (change) outputs

### ISSUE THREAD

**Issue by AliceOJJm** [bitcoin/bitcoin#15599]
'getbalance' and 'listunspent' return values derive for v0.17.1 and new 0.18.99
Thus I can't spend unconfirmed change rightaway and balance is confusing. 'getunconfirmedbalance' is 0 at the same time.
Is it an intended change?

**Comment by MarcoFalke** [comment]
Could you elaborate a bit more on how to reproduce this and what the differences are?

How is the coin listed in listunspent? Is it in the mempool? Is the tx trusted? Does it spend third party coins? What are your bitcoin conf settings?
