### ISSUE TITLE
Remove `Broadcast`/`ResendWalletTransactions` from validation interface

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#15619]
The `Broadcast`/`ResendWalletTransactions` interface is strange:

- it's the node saying to the wallet "Try to submit your unconfirmed transactions to the mempool again"
- it's called in one place by the node, in `SendMessages()` here: https://github.com/bitcoin/bitcoin/blob/c033c4b5cef89a654e4d9d5c5f9bd823871b068b/src/net_processing.cpp#L3515. `SendMessages()` is called on the message handling thread on a loop.
- the actual scheduling of when the wallet sends messages is handled in the `ResendWalletTransactions()` function itself, using the `nNextResend` and `nLastResend` wallet globals (which could as easily be static variables in `ResendWalletTransactions()`).

Therefore the only use of `Broadcast()` is to periodically prod the wallet. The wallet itself decides whether it's time to resend transactions. This could be done by scheduling regular calls to `ResendWalletTransactions()`, in the same way that we schedule regular wallet flushes here: https://github.com/bitcoin/bitcoin/blob/c033c4b5cef89a654e4d9d5c5f9bd823871b068b/src/wallet/init.cpp#L215.

A couple of minor implementation details:

- the call to `Broadcast()` in `SendMessages()` is protected by an if statement `if (!fReindex && !fImporting && !IsInitialBlockDownload()) {`. Those tests could be moved into `ResendWalletTransactions()` (through the `Chain` interface).
- The `Broadcast` notification passes in the `nTimeBestReceived` time of the best block. That could be fetched by `ResendWalletTransactions()` through the `Chain` interface.

**Comment by jnewbery** [comment]
@ryanofsky attempted to remove this interface before in https://github.com/bitcoin/bitcoin/pull/10584. That PR was missing the wallet scheduling its own rebroadcasts.

We shouldn't do this before https://github.com/bitcoin/bitcoin/pull/10973, to avoid having to rebase that PR again.

**Comment by ryanofsky** [comment]
Overall I think this makes sense I don't see a reason why the wallet couldn't schedule resends itself. One minor point on

> the nNextResend and nLastResend wallet globals (which could as easily be static variables in ResendWalletTransactions())

These appear to be CWallet members and not global symbols:

https://github.com/bitcoin/bitcoin/blob/c033c4b5cef89a654e4d9d5c5f9bd823871b068b/src/wallet/wallet.h#L656-L657

I didn't look very closely but if they were static members or static variables inside the function instead of instance members, it could be a problem because they'd be shared across multiple `CWallet` instances and not work with multiple wallets loaded.

**Comment by jnewbery** [comment]
> if they were static members or static variables inside the function instead of instance members, it could be a problem because they'd be shared across multiple CWallet instances and not work with multiple wallets loaded.

Ah yes, you're right. Thanks for pointing this out.

**Comment by jnewbery** [comment]
Fixed in #15632

**Comment by promag** [comment]
ACK, actually I was surprised to see this in `SendMessages`
https://github.com/bitcoin/bitcoin/blob/656a15e5394d8d841619b5b186fa0f9c8be0322b/src/net_processing.cpp#L3538-L3544

**Comment by jnewbery** [comment]
>  I was surprised to see this in SendMessages

Yes, it's a violation of component separation. _Net processing_ is using the _validation_ interface to tell the _wallet_ to rebroadcast.
