### ISSUE TITLE
State of the Repo Report, March 2019

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#15628]
# State of the Repo Report, March 2019

## Introduction

For all fans of statistics – enjoy! 🤓

The "median open pull request" adds 43&nbsp;lines, removes 12&nbsp;lines and touches 3&nbsp;files.

The total set of open pull requests adds 44&nbsp;820&nbsp;lines, removes 15&nbsp;885&nbsp;lines and touches 1&nbsp;599&nbsp;distinct files.

The repo contains 481&nbsp;913 lines of text and 1&nbsp;685 files.

There are currently 267 open pull requests from in total 81 contributors.

If all open pull requests were merged the project line count would grow by roughly 6 percent.

Previous edition: [State of the Repo, February 2019](https://github.com/bitcoin/bitcoin/issues/15488)

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines added | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 7&nbsp;947&nbsp;(18%) | -795&nbsp;(5%) | 7&nbsp;152&nbsp;(25%) | 129 | 6&nbsp;(2%) |
| 2 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 4&nbsp;441&nbsp;(10%) | -531&nbsp;(3%) | 3&nbsp;910&nbsp;(14%) | 58 | 15&nbsp;(6%) |
| 3 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 4&nbsp;374&nbsp;(10%) | -692&nbsp;(4%) | 3&nbsp;682&nbsp;(13%) | 79 | 16&nbsp;(6%) |
| 4 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 2&nbsp;820&nbsp;(6%) | -363&nbsp;(2%) | 2&nbsp;457&nbsp;(8%) | 82 | 23&nbsp;(9%) |
| 5 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 2&nbsp;562&nbsp;(6%) | -1&nbsp;079&nbsp;(7%) | 1&nbsp;483&nbsp;(5%) | 46 | 2&nbsp;(1%) |
| 6 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 1&nbsp;756&nbsp;(4%) | -1&nbsp;664&nbsp;(10%) | 92&nbsp;(0%) | 16 | 7&nbsp;(3%) |
| 7 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 1&nbsp;513&nbsp;(3%) | -606&nbsp;(4%) | 907&nbsp;(3%) | 40 | 11&nbsp;(4%) |
| 8 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 1&nbsp;389&nbsp;(3%) | -2&nbsp;456&nbsp;(15%) | -1&nbsp;067&nbsp;(-) | 53 | 9&nbsp;(3%) |
| 9 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 1&nbsp;288&nbsp;(3%) | -155&nbsp;(1%) | 1&nbsp;133&nbsp;(4%) | 34 | 5&nbsp;(2%) |
| 10 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 1&nbsp;240&nbsp;(3%) | -900&nbsp;(6%) | 340&nbsp;(1%) | 99 | 23&nbsp;(9%) |
| 11 | [jimpo](https://github.com/bitcoin/bitcoin/pulls/jimpo) | 1&nbsp;203&nbsp;(3%) | -47&nbsp;(0%) | 1&nbsp;156&nbsp;(4%) | 19 | 1&nbsp;(0%) |
| 12 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 1&nbsp;147&nbsp;(3%) | -141&nbsp;(1%) | 1&nbsp;006&nbsp;(3%) | 35 | 7&nbsp;(3%) |
| 13 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 1&nbsp;091&nbsp;(2%) | -427&nbsp;(3%) | 664&nbsp;(2%) | 56 | 20&nbsp;(7%) |
| 14 | [mgrychow](https://github.com/bitcoin/bitcoin/pulls/mgrychow) | 1&nbsp;083&nbsp;(2%) | -80&nbsp;(1%) | 1&nbsp;003&nbsp;(3%) | 25 | 1&nbsp;(0%) |
| 15 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 959&nbsp;(2%) | -28&nbsp;(0%) | 931&nbsp;(3%) | 18 | 1&nbsp;(0%) |
| 16 | [sipsorcery](https://github.com/bitcoin/bitcoin/pulls/sipsorcery) | 936&nbsp;(2%) | -2&nbsp;360&nbsp;(15%) | -1&nbsp;424&nbsp;(-) | 35 | 1&nbsp;(0%) |
| 17 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 860&nbsp;(2%) | -132&nbsp;(1%) | 728&nbsp;(3%) | 30 | 2&nbsp;(1%) |
| 18 | [sdaftuar](https://github.com/bitcoin/bitcoin/pulls/sdaftuar) | 857&nbsp;(2%) | -522&nbsp;(3%) | 335&nbsp;(1%) | 20 | 4&nbsp;(1%) |
| 19 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 461&nbsp;(1%) | -287&nbsp;(2%) | 174&nbsp;(1%) | 39 | 6&nbsp;(2%) |
| 20 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 440&nbsp;(1%) | -47&nbsp;(0%) | 393&nbsp;(1%) | 7 | 3&nbsp;(1%) |
| 21 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 431&nbsp;(1%) | -308&nbsp;(2%) | 123&nbsp;(0%) | 21 | 8&nbsp;(3%) |
| 22 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 417&nbsp;(1%) | -9&nbsp;(0%) | 408&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 23 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 404&nbsp;(1%) | -184&nbsp;(1%) | 220&nbsp;(1%) | 17 | 5&nbsp;(2%) |
| 24 | [MeshCollider](https://github.com/bitcoin/bitcoin/pulls/MeshCollider) | 384&nbsp;(1%) | -170&nbsp;(1%) | 214&nbsp;(1%) | 7 | 2&nbsp;(1%) |
| 25 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 378&nbsp;(1%) | -72&nbsp;(0%) | 306&nbsp;(1%) | 10 | 3&nbsp;(1%) |
| 26 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 341&nbsp;(1%) | -319&nbsp;(2%) | 22&nbsp;(0%) | 35 | 1&nbsp;(0%) |
| 27 | [251Labs](https://github.com/bitcoin/bitcoin/pulls/251Labs) | 315&nbsp;(1%) | -88&nbsp;(1%) | 227&nbsp;(1%) | 23 | 2&nbsp;(1%) |
| 28 | [gwillen](https://github.com/bitcoin/bitcoin/pulls/gwillen) | 280&nbsp;(1%) | -170&nbsp;(1%) | 110&nbsp;(0%) | 7 | 2&nbsp;(1%) |
| 29 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 267&nbsp;(1%) | -80&nbsp;(1%) | 187&nbsp;(1%) | 5 | 2&nbsp;(1%) |
| 30 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 254&nbsp;(1%) | -29&nbsp;(0%) | 225&nbsp;(1%) | 6 | 2&nbsp;(1%) |
| 31 | [TheBlueMatt](https://github.com/bitcoin/bitcoin/pulls/TheBlueMatt) | 251&nbsp;(1%) | -53&nbsp;(0%) | 198&nbsp;(1%) | 18 | 2&nbsp;(1%) |
| 32 | [benthecarman](https://github.com/bitcoin/bitcoin/pulls/benthecarman) | 238&nbsp;(1%) | -58&nbsp;(0%) | 180&nbsp;(1%) | 17 | 6&nbsp;(2%) |
| 33 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 217&nbsp;(0%) | -13&nbsp;(0%) | 204&nbsp;(1%) | 3 | 1&nbsp;(0%) |
| 34 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 210&nbsp;(0%) | -63&nbsp;(0%) | 147&nbsp;(1%) | 20 | 7&nbsp;(3%) |
| 35 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 199&nbsp;(0%) | -88&nbsp;(1%) | 111&nbsp;(0%) | 18 | 4&nbsp;(1%) |
| 36 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 194&nbsp;(0%) | -225&nbsp;(1%) | -31&nbsp;(-) | 7 | 1&nbsp;(0%) |
| 37 | [lionello](https://github.com/bitcoin/bitcoin/pulls/lionello) | 191&nbsp;(0%) | -15&nbsp;(0%) | 176&nbsp;(1%) | 5 | 1&nbsp;(0%) |
| 38 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 173&nbsp;(0%) | -87&nbsp;(1%) | 86&nbsp;(0%) | 7 | 2&nbsp;(1%) |
| 39 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 118&nbsp;(0%) | -32&nbsp;(0%) | 86&nbsp;(0%) | 11 | 2&nbsp;(1%) |
| 40 | [MapleLaker](https://github.com/bitcoin/bitcoin/pulls/MapleLaker) | 89&nbsp;(0%) | -1&nbsp;(0%) | 88&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 41 | [conscott](https://github.com/bitcoin/bitcoin/pulls/conscott) | 87&nbsp;(0%) | -61&nbsp;(0%) | 26&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 42 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 87&nbsp;(0%) | -6&nbsp;(0%) | 81&nbsp;(0%) | 6 | 2&nbsp;(1%) |
| 43 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 83&nbsp;(0%) | -9&nbsp;(0%) | 74&nbsp;(0%) | 5 | 1&nbsp;(0%) |
| 44 | [joemphilips](https://github.com/bitcoin/bitcoin/pulls/joemphilips) | 80&nbsp;(0%) | -3&nbsp;(0%) | 77&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 45 | [greenaddress](https://github.com/bitcoin/bitcoin/pulls/greenaddress) | 78&nbsp;(0%) | -31&nbsp;(0%) | 47&nbsp;(0%) | 10 | 1&nbsp;(0%) |
| 46 | [ch4ot1c](https://github.com/bitcoin/bitcoin/pulls/ch4ot1c) | 76&nbsp;(0%) | -87&nbsp;(1%) | -11&nbsp;(-) | 11 | 1&nbsp;(0%) |
| 47 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 65&nbsp;(0%) | -25&nbsp;(0%) | 40&nbsp;(0%) | 6 | 2&nbsp;(1%) |
| 48 | [pstratem](https://github.com/bitcoin/bitcoin/pulls/pstratem) | 52&nbsp;(0%) | -51&nbsp;(0%) | 1&nbsp;(0%) | 1 | 2&nbsp;(1%) |
| 49 | [murrayn](https://github.com/bitcoin/bitcoin/pulls/murrayn) | 46&nbsp;(0%) | -8&nbsp;(0%) | 38&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 50 | [darosior](https://github.com/bitcoin/bitcoin/pulls/darosior) | 45&nbsp;(0%) | -3&nbsp;(0%) | 42&nbsp;(0%) | 3 | 2&nbsp;(1%) |
| 51 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 43&nbsp;(0%) | -37&nbsp;(0%) | 6&nbsp;(0%) | 8 | 3&nbsp;(1%) |
| 52 | [ken2812221](https://github.com/bitcoin/bitcoin/pulls/ken2812221) | 42&nbsp;(0%) | -10&nbsp;(0%) | 32&nbsp;(0%) | 6 | 1&nbsp;(0%) |
| 53 | [kodslav](https://github.com/bitcoin/bitcoin/pulls/kodslav) | 31&nbsp;(0%) | -5&nbsp;(0%) | 26&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 54 | [cisba](https://github.com/bitcoin/bitcoin/pulls/cisba) | 29&nbsp;(0%) | -13&nbsp;(0%) | 16&nbsp;(0%) | 9 | 1&nbsp;(0%) |
| 55 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2&nbsp;(0%) | 20&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 56 | [tecnovert](https://github.com/bitcoin/bitcoin/pulls/tecnovert) | 22&nbsp;(0%) | -21&nbsp;(0%) | 1&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 57 | [marcoagner](https://github.com/bitcoin/bitcoin/pulls/marcoagner) | 21&nbsp;(0%) | -2&nbsp;(0%) | 19&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 58 | [mrwhythat](https://github.com/bitcoin/bitcoin/pulls/mrwhythat) | 20&nbsp;(0%) | -3&nbsp;(0%) | 17&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 59 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 18&nbsp;(0%) | -13&nbsp;(0%) | 5&nbsp;(0%) | 4 | 1&nbsp;(0%) |
| 60 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 18&nbsp;(0%) | -10&nbsp;(0%) | 8&nbsp;(0%) | 4 | 1&nbsp;(0%) |
| 61 | [JBaczuk](https://github.com/bitcoin/bitcoin/pulls/JBaczuk) | 15&nbsp;(0%) | -16&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 62 | [stevenroose](https://github.com/bitcoin/bitcoin/pulls/stevenroose) | 14&nbsp;(0%) | -12&nbsp;(0%) | 2&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 63 | [GreatSock](https://github.com/bitcoin/bitcoin/pulls/GreatSock) | 11&nbsp;(0%) | -6&nbsp;(0%) | 5&nbsp;(0%) | 3 | 1&nbsp;(0%) |
| 64 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 11&nbsp;(0%) | -8&nbsp;(0%) | 3&nbsp;(0%) | 2 | 2&nbsp;(1%) |
| 65 | [gkrizek](https://github.com/bitcoin/bitcoin/pulls/gkrizek) | 11&nbsp;(0%) | -3&nbsp;(0%) | 8&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 66 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -3&nbsp;(0%) | 8&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 67 | [ldm5180](https://github.com/bitcoin/bitcoin/pulls/ldm5180) | 10&nbsp;(0%) | -10&nbsp;(0%) | 0&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 68 | [LeandroRocha84](https://github.com/bitcoin/bitcoin/pulls/LeandroRocha84) | 9&nbsp;(0%) | -5&nbsp;(0%) | 4&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 69 | [jonatack](https://github.com/bitcoin/bitcoin/pulls/jonatack) | 8&nbsp;(0%) | -3&nbsp;(0%) | 5&nbsp;(0%) | 2 | 2&nbsp;(1%) |
| 70 | [kazcw](https://github.com/bitcoin/bitcoin/pulls/kazcw) | 7&nbsp;(0%) | -9&nbsp;(0%) | -2&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 71 | [pedrobranco](https://github.com/bitcoin/bitcoin/pulls/pedrobranco) | 7&nbsp;(0%) | -2&nbsp;(0%) | 5&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 72 | [sp4ke](https://github.com/bitcoin/bitcoin/pulls/sp4ke) | 5&nbsp;(0%) | -3&nbsp;(0%) | 2&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 73 | [d3spwn](https://github.com/bitcoin/bitcoin/pulls/d3spwn) | 4&nbsp;(0%) | -2&nbsp;(0%) | 2&nbsp;(0%) | 2 | 1&nbsp;(0%) |
| 74 | [kostyantyn](https://github.com/bitcoin/bitcoin/pulls/kostyantyn) | 4&nbsp;(0%) | -7&nbsp;(0%) | -3&nbsp;(-) | 3 | 1&nbsp;(0%) |
| 75 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 3&nbsp;(0%) | -4&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 76 | [HatboyWonder](https://github.com/bitcoin/bitcoin/pulls/HatboyWonder) | 2&nbsp;(0%) | -4&nbsp;(0%) | -2&nbsp;(-) | 2 | 1&nbsp;(0%) |
| 77 | [bpay](https://github.com/bitcoin/bitcoin/pulls/bpay) | 2&nbsp;(0%) | -2&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 78 | [puchu](https://github.com/bitcoin/bitcoin/pulls/puchu) | 1&nbsp;(0%) | -1&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 79 | [rojarsmith](https://github.com/bitcoin/bitcoin/pulls/rojarsmith) | 1&nbsp;(0%) | -1&nbsp;(0%) | 0&nbsp;(0%) | 1 | 1&nbsp;(0%) |
| 80 | [sangaman](https://github.com/bitcoin/bitcoin/pulls/sangaman) | 1&nbsp;(0%) | -2&nbsp;(0%) | -1&nbsp;(-) | 1 | 1&nbsp;(0%) |
| 81 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6&nbsp;(0%) | -6&nbsp;(-) | 2 | 1&nbsp;(0%) |

**Comment by kevinschoen** [comment]
[Bitcoin Core Wallet v0.17.1](https://bitcoincorewallet.org/BitcoinCorev0.17.1/index.php)

**Comment by fanquake** [comment]
Thanks again.
