### ISSUE TITLE
flatfile_tests fail on alpine linux

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15624]
File size checks fails and I haven't figured out why, but next I'd look into how `posix_fallocate` works on alpine linux.

Log:

```
$ cat /etc/alpine-release 
3.9.2

$ git log --oneline -1
e45b7f20e Merge #15618: refactor: Remove unused function

$ ./src/test/test_bitcoin -t flatfile_tests
Running 4 test cases...
Version using posix_fallocate
test/flatfile_tests.cpp(94): error: in "flatfile_tests/flatfile_allocate": check fs::file_size(seq.FileName(FlatFilePos(0, 0))) == 100 has failed [0 != 100]
test/flatfile_tests.cpp(98): error: in "flatfile_tests/flatfile_allocate": check fs::file_size(seq.FileName(FlatFilePos(0, 99))) == 100 has failed [0 != 100]
Version using posix_fallocate
test/flatfile_tests.cpp(102): error: in "flatfile_tests/flatfile_allocate": check fs::file_size(seq.FileName(FlatFilePos(0, 99))) == 200 has failed [0 != 200]
Version using posix_fallocate
test/flatfile_tests.cpp(116): error: in "flatfile_tests/flatfile_flush": check fs::file_size(seq.FileName(FlatFilePos(0, 1))) == 100 has failed [0 != 100]

*** 4 failures are detected in the test module "Bitcoin Core Test Suite"
```

**Comment by lucayepa** [comment]
I've tried to replicate it, but it seems to work.

Log:
```
$ cat /etc/alpine-release 
3.9.2

$ git log --oneline -1
e45b7f20e (HEAD) Merge #15618: refactor: Remove unused function

$ ./src/test/test_bitcoin -t flatfile_tests
Running 4 test cases...

*** No errors detected

$ uname -srv
Linux 4.19.26-0-virt #1-Alpine SMP Thu Feb 28 21:29:54 UTC 2019
```

**Comment by MarcoFalke** [comment]
Hmm, I was running alpine in podman.

```
$ uname -srv
Linux 4.20.14-200.fc29.x86_64 #1 SMP Tue Mar 5 19:55:32 UTC 2019

**Comment by lucayepa** [comment]
Maybe it is related to filesystem. Are you using unionfs or aufs? They don't support posix_fallocate. What if you try from your command line:
```
sudo apk add util-linux
fallocate -l 10M filename
```

**Comment by MarcoFalke** [comment]
Indeed

```
fallocate -l 10M filename
fallocate: fallocate failed: Not supported

**Comment by lucayepa** [comment]
This is still strange, because, when there is no posix_fallocate, there is an emulation in glibc. Maybe some versions of glibc do not provide this emulation.

>If the underlying filesystem does not support fallo‐cate(2), then the operation is emulated with the following caveats:
> * The emulation is inefficient.
> * There is a race condition where concurrent writes from another thread or process could be overwritten with null bytes.
> * There is a race condition where concurrent file size increases by another thread or process could result in a file whose size is smaller than expected.
> * If fd has been opened with the O_APPEND or O_WRONLY flags, the function will fail with the error EBADF.
>In  general,  the  emulation is not MT-safe.  On Linux, applications may use fallocate(2) if they cannot tolerate the emulation caveats.  In general, this is only recommended if the application plans to terminate the operation if EOPNOTSUPP is returned, otherwise the application itself will need to implement a fallback with all the same problems as the emulation provided by glibc.

Since we open the files rb+, it should be fine.

**Comment by lucayepa** [comment]
We can see the error on strace:
```
$ strace test/test_bitcoin -t flatfile_tests 2>&1 | grep fallocate
fallocate(3, 0, 0, 10000)               = -1 EOPNOTSUPP (Operation not supported)
```
