### ISSUE TITLE
-wallet is a "network-only" option but -walletdir is not

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15630]
Any reason for this?

https://github.com/bitcoin/bitcoin/blob/2d46f1be0c3c8b7287aa1f62bb1f5b4a8d00ff6e/src/util/system.cpp#L316-L326

**Comment by kevinschoen** [comment]
[Bitcoin Core Wallet v0.17.1](https://bitcoincorewallet.org/BitcoinCorev0.17.1/index.php)

**Comment by promag** [comment]
#11862 (Network specific conf sections) came after #11466 (Specify custom wallet directory with -walletdir param) and in #11862 `-walletdir` is never mentioned.

I think it makes sense to add `-walletdir`.

**Comment by luke-jr** [comment]
It's not inherently broken to put wallets for different networks in the same directory, so it makes sense to allow a shared `-walletdir`...

**Comment by promag** [comment]
@luke-jr but wallets are relative to `-walletdir` so it could be confusing no?

**Comment by luke-jr** [comment]
Maybe. I suppose without `-walletdir` we do have network-separate wallet dirs.

**Comment by MarcoFalke** [comment]
See also discussion in " Wallet file should not be reused across chains #12805 "

**Comment by hebasto** [comment]
@MarcoFalke @meshcollider 
Could this issue also be labeled "Wallet"?
