### ISSUE TITLE
Expected property "0" of type ECPair, got p

### ISSUE THREAD

**Issue by ShabanGomaa** [bitcoin/bitcoin#15645]
When I'm trying to create a wallet in react app using the following code:
const seed = bip39.mnemonicToSeed(mnemonic);
const master = bitcoin.HDNode.fromSeedBuffer(seed, "testnet");

I got error: Expected property "0" of type ECPair, got p
![image](https://user-images.githubusercontent.com/20771931/54845111-39a55580-4ce1-11e9-8956-107300a52619.png)

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
