### ISSUE TITLE
test: Generating lcov line coverage does not fail when tests fail

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15648]
Generating coverage where the functional tests fail does not fail the coverage. The excerpt:

```
117/118 - feature_shutdown.py passed, Duration: 3 s
make: [functional_test.info] Error 1 (ignored)
```

See: https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#compiling-for-test-coverage

**Comment by crackercracked** [comment]
Can somebody elaborate on how to produce the error. It seems the coverage report is still generated fine even given individual functional tests failed

**Comment by MarcoFalke** [comment]
> It seems the coverage report is still generated fine even given individual functional tests failed

The file is generated, but is obviously missing the coverage of the remainder of the test that failed. So it should have never been generated in the first place.

**Comment by asood123** [comment]
I'd like to help with this issue. Fwiw, I'm a newbie to Bitcoin codebase. Was this fix https://github.com/bitcoin/bitcoin/pull/15812 incorrect or didn't get rebased in time?

**Comment by MarcoFalke** [comment]
Yeah, it was incorrect. That pull modified rpc coverage. This issue is about lcov, see https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#compiling-for-test-coverage

**Comment by asood123** [comment]
I'm new to makefiles and build systems, so appreciate pointers if this isn't correct.
