### ISSUE TITLE
depends: files missing from bitcoincore.org fallback

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#15658]
The following files are missing from the [bitcoincore.org depends fallback](https://bitcoincore.org/depends-sources):

* `expat-2.2.6.tar.bz2`
* `qtbase-opensource-src-5.9.7.tar.xz`
* `rapidcheck-10fc0cb.tar.gz`
* `zeromq-4.3.1.tar.gz`

**Comment by MarcoFalke** [comment]
We don't really need to mirror anything except the proprietary mac os stuff?

**Comment by hebasto** [comment]
The current list of missing files:
- `boost_1_70_0.tar.bz2`
- `expat-2.2.7.tar.bz2`
- `qtbase-opensource-src-5.9.7.tar.xz`
- `zeromq-4.3.1.tar.gz`

**Comment by MarcoFalke** [comment]
I am happy to host a fallback on https://drahtbot.space/

I don't really see why they'd need to be on bitcoincore.org

cc @theuni

**Comment by MarcoFalke** [comment]
https://drahtbot.space/depends_download_fallback/

**Comment by fanquake** [comment]
Thanks @MarcoFalke. Can you also add the `rapidcheck` package.

**Comment by MarcoFalke** [comment]
Good catch. Added rapidcheck

**Comment by fanquake** [comment]
@laanwj In regards to:

> [It should be updated to the newest depends downloads, if there's any missing files let me know.](https://github.com/bitcoin/bitcoin/pull/17704#issuecomment-563946257)

From a quick look there are still a few missing files:
```bash
Boost 1.70.0
libevent 2.1.11
qt 5.9.8
miniupnpc-2.0.20180203
zeromq-4.3.1
```

**Comment by TheBlueMatt** [comment]
I think it got stuck on verify-commits.py failing on master.

**Comment by MarcoFalke** [comment]
The mirror is still defunct as of 5 hours ago: https://travis-ci.org/bitcoin/bitcoin/jobs/623182811#L2225

**Comment by laanwj** [comment]
> I think it got stuck on verify-commits.py failing on master.

```
build-depends:~/depends$ ./update-sources.sh http://github.com/bitcoin/bitcoin.git 3d6752779f0504e6435fe682f0c06c60b5c4c33b /home/cory/depends-sources
From http://github.com/bitcoin/bitcoin
 * branch                  master     -> FETCH_HEAD
Using verify-commits data from /tmp/gitsync/work/contrib/verify-commits

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

apparently, on a git configuration thing, will try to get it to work …

**Comment by laanwj** [comment]
I thnk that did it, we have the following now:
```
boost_1_70_0.tar.bz2
release-2.1.11-stable.tar.gz
qtbase-opensource-src-5.9.8.tar.xz
qttools-opensource-src-5.9.8.tar.xz
qttranslations-opensource-src-5.9.8.tar.xz
miniupnpc-2.0.20180203.tar.gz
zeromq-4.3.1.tar.gz
```

**Comment by fanquake** [comment]
Going to close now. A `make download`, across all branches, using just bitcoincore.org works for me. The rapidcheck package is missing, but I'm not concerned about that.

**Comment by laanwj** [comment]
added `RAPIDCHECK=1` to the script, I hope it works

**Comment by laanwj** [comment]
Seems to have worked (the file is called d9482c683429fe79122e3dcab14c9655874aeb8e.tar.gz, though…)

**Comment by fanquake** [comment]
> Seems to have worked (the file is called d9482c683429fe79122e3dcab14c9655874aeb8e.tar.gz, though…)

That should be ok.
