### ISSUE TITLE
0.18.0 rc2 CPU spike in thread bitcoin-opencon

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15665]
https://github.com/bitcoin/bitcoin/issues/15555#issuecomment-476376796

**Comment by MarcoFalke** [comment]
Anyone who sees this, please do the following:

* Open a terminal window with `htop`
* Open another terminal window with `gdb --args ./bitcoin-qt`
** Type `run` in (gdb)
** Watch the CPU usage of the `opencon` thread in the htop window
** Hit `CTRL+C` in (gdb) when it is at 100%
** Type `thread apply all bt` in (gdb)

**Comment by MarcoFalke** [comment]
To enable thread names in htop,  select `F5` for tree view and `F2`-"Display options"-`[x] thread names` to get the thread names.

**Comment by perefeliu** [comment]
Having some problems with `gdb --args ./bitcoin-qt`
In my case, bitcoin-qt is located `/usr/local/bin/bitcoin-qt ` so I run  `gdb --args /usr/local/bin/bitcoin-qt`
and then `run`. I get what follows:
```
(gdb) run
Starting program: /usr/local/bin/bitcoin-qt
Cannot parse expression `.L1185 4@r4'.
warning: Probes-based dynamic linker interface failed.
Reverting to original interface.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
[Inferior 1 (process 3987) exited with code 01]

```

**Comment by MarcoFalke** [comment]
If you are not using the gui, but `bitcoind`, replace `bitcoin-qt` with `bitcoind`, please

**Comment by perefeliu** [comment]
Ok. That makes sense. Thanks.

**Comment by fanquake** [comment]
Closing in favour of #16004.
