### ISSUE TITLE
Transaction confirmation prompt too big - buttons not clickable

### ISSUE THREAD

**Issue by bitcoin101ch** [bitcoin/bitcoin#15667]
_Second try - first issue got deleted suddenly..._

When confirming too big transactions, depending on screen resolution with each output the buttons move lower and lower until they are not visible anymore on the screen.

Additionally randomly after a couple transactions the client starts to repeat its content in the confirmation prompt making even the smalest 1:1 transaction unusable as the buttons are not visible, again. (See screenshot)

I (A) would expect that the buttons are visible no matter how big the transaction content is (for example by making the content scrollable) and (B) don't understand why the content is repeating suddenly.

Using Bitcoin Knots 17 but have been directed by the developers that the issue belongs to bitcoin/bitcoin

![bug-NEW](https://user-images.githubusercontent.com/48955884/55005357-2396de00-4fdc-11e9-9c6c-2b869777e64e.png)

Windows 10
1920x1080
Intel i7

**Comment by MarcoFalke** [comment]
Does this happen in Bitcoin Core as well?

Otherwise: https://github.com/bitcoinknots/bitcoin/issues/new

**Comment by bitcoin101ch** [comment]
Yes also with bitcoin core @MarcoFalke

**Comment by MarcoFalke** [comment]
Thanks, then please include the version of Bitcoin Core that you are using to reproduce the issue and how to reproduce.

**Comment by Vasyo** [comment]
https://www.coinbase.com/join/5b5c3b96a2bc83110a3c5aa6

**Comment by bitcoin101ch** [comment]
@MarcoFalke Bitcoin Core Version 0.17.1

Easy to reproduce. Just make a transaction with 20 outputs. Result: The confirmation prompt will be too big for your screen and the buttons are not visible anymore.

**Comment by promag** [comment]
I think we can improve this while ditching `QDialog::exec` usages.

**Comment by bitcoin101ch** [comment]
Status remains closed?

**Comment by promag** [comment]
I'd reopen and tag 0.19.
