### ISSUE TITLE
[GUI] transaction status after load wallet

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#15675]
Running 0.18 the following can be observed:

- load a wallet
- create a transaction and submit to the network
- close wallet
- re-open wallet

when re-opened before the tx was included in a block, the GUI will show 

> Status: 0/unconfirmed, not in memory pool

for all unconfirmed transactions, even they are present in the mempool

**Comment by promag** [comment]
Fixed in #15652.
