### ISSUE TITLE
Renew Windows code-signing certificate

### ISSUE THREAD

**Issue by theuni** [bitcoin/bitcoin#15690]
See https://github.com/bitcoin/bitcoin/pull/15682 for the last update.

The current cert expires March 26, 2020.

**Comment by MarcoFalke** [comment]
Is the plan  to bump it for every release or is the short expiration time (compared to the previous cert) in hope that the RSA threshold sign scheme will get implemented in the meantime?

**Comment by theuni** [comment]
I don't think there was any particular reason for the 1year cert. We can certainly bump to a 3yr next time.

I just didn't want expiration sneaking up on us again. I assume 0.19 will be safe, but we'll probably be renewing for 0.20.

**Comment by laanwj** [comment]
This was closed by #18425, right?
