### ISSUE TITLE
Improve structure of documentation for RPC interface

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#15705]
**This issue has moved to https://github.com/bitcoin-dot-org/bitcoin.org/issues/2910**

When I Google for "bitcoin core rpc" I find a bunch of pages that are a bit confusing. What I am looking for is https://bitcoin.org/en/developer-reference#bitcoin-core-apis. But there are multiple others confusing matches and I suggest a few improvements for them:

1. The top result is https://bitcoincore.org/en/doc/. This has fairly little information and is, IMO, a distraction.
2. The second result is https://en.bitcoin.it/wiki/API_reference_(JSON-RPC). This is not about RPC commands at all. Rather, it is a (partial?) list of language clients. The page should be renamed. Also, it might help to place a link to the RPC calls documentation at the top of this page.
3. The third result is https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list which is entirely obsolete I think. Can this be deleted?
4. The fourth result is https://bitcoin.org/en/developer-reference which is the page I want but the wrong anchor. Not sure what can be done about this.
5. The next result is https://en.bitcoinwiki.org/wiki/Bitcoind which seems reasonable but has a lot of obsolete stuff on it as well.

I might be wrong about these points but I wanted to express my confusion as a normal developer just trying to find the documentation of all available commands. I hope this helps.

**Comment by GSPP** [comment]
I also notice that `getaddressinfo` is missing in https://bitcoin.org/en/developer-reference.

**Comment by jonatack** [comment]
Hi @GSPP, happy to be corrected if I'm wrong but I think https://github.com/bitcoin-dot-org/bitcoin.org/issues might be the right place to file this issue.

As for resources, in addition to the ones you mentioned, this one is pretty good: https://masonicboom.github.io/btcrpcapi/

**Comment by GSPP** [comment]
This issue has moved to bitcoin-dot-org/bitcoin.org#2910 @jonatack. That resource seems very useful. Thanks.
