### ISSUE TITLE
rpc: remove getbalance::minconf

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15702]
Seems to be undocumented and too confusing:

https://github.com/bitcoin/bitcoin/pull/15010#issuecomment-477824480

**Comment by xaaaak** [comment]
Can someone help me with this: how now to send unconfirmed transaction? (earlier with 'sendmany + minconf 0') and see total balance with unconfirmed coins (earlier with 'getbalance + minconf 0')?
Thank you, sorry if wrong place.

**Comment by MarcoFalke** [comment]
@xaaaak See the `spendzeroconfchange` command line option

**Comment by xaaaak** [comment]
@MarcoFalke Thank you for your answer. Yes, I tried that option, but it for some reason did not work.

**Comment by MarcoFalke** [comment]
You can never spend unconfirmed coins that someone else sent to you (only your own change)

**Comment by MarcoFalke** [comment]
If this is a bug, please open a new issue with steps to reproduce

**Comment by xaaaak** [comment]
> You can never spend unconfirmed coins that someone else sent to you (only your own change)

But how hardwallet Trezor do it?
