### ISSUE TITLE
Library source code organization

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15732]
(copied from https://github.com/bitcoin/bitcoin/pull/15638#issuecomment-479101494 by @ryanofsky) Here is how I am thinking about the organization:

- `libbitcoin_server.a`, `libbitcoin_wallet.a`, and `libbitcoinqt.a` should all be terminal dependencies. They should be able to depend on other symbols in other libraries, but no other libraries should depend on symbols in them (and they shouldn't depend on each other).

- `libbitcoin_consensus.a` should be a standalone library that doesn't depend on symbols in other libraries mentioned here

- `libbitcoin_common.a` and `libbitcoin_util.a` seem very interchangeable right now and mutually depend on each other. I think we should either merge them into one library, or create a new top-level `src/common/` directory complementing `src/util/`, and start to distinguish general purpose utility code (like argument parsing) from bitcoin-specific utility code (like formatting bip32 paths and using ChainParams). Both these libraries can be depended on by `libbitcoin_server.a`, `libbitcoin_wallet.a`, and `libbitcoinqt.a`, and they can depend on `libbitcoin_consensus.a`. If we want to split util and common up, as opposed to merging them together, then util shouldn't depend on libconsensus, but common should.

Over time, I think it'd be nice if source code organization reflected library organization . I think it'd be nice if all `libbitcoin_util` source files lived in `src/util`, all `libbitcoin_consensus.a` source files lived in `src/consensus`, and all `libbitcoin_server.a` code lived in `src/node` (and maybe the library was called `libbitcoin_node.a`).

**Comment by MarcoFalke** [comment]
See also:

*  Source code organization for standalone (util) functions and types #14721

**Comment by laanwj** [comment]
> libbitcoin_common.a and libbitcoin_util.a seem very interchangeable right now and mutually depend on each other

interesting—`util` is linked by:
```
bitcoind
bitcoin-cli
bitcoin-tx
bitcoin-wallet
bench/bench_bitcoin
qt/bitcoin-qt
qt/test/test_bitcoin-qt
test/test_bitcoin
```
whereas `common` is linked by:
```
bitcoind
bitcoin-tx
bitcoin-wallet
bench/bench_bitcoin
qt/bitcoin-qt
qt/test/test_bitcoin-qt
test/test_bitcoin
```
The only difference being `bitcoin-cli`. Yes, with this I'd say it makes sense to merge them, *unless* the current split avoids pulling in some dependencies for `bitcoin-cli` (@luke-jr might be able to comment w.r.t. gentoo). This can't be true if there are bidirectional dependencies between them.

**Comment by sipa** [comment]
Concept ACK on the organization plan above.

I feel that there is place for a distinction between common and util, through the question "bitcoin specific logic". For example, transaction signing seems to belong in a very different place than command-line handling logic, and bitcoin-cli shouldn't need to include the former.

However it seems that in practice this distinction isn't really followed, so it may be better to just merge common and util to remove the mutual dependency, and the later carve out the real "util" parts.

**Comment by hebasto** [comment]
> it'd be nice if source code organization reflected library organization

Concept ACK.

**Comment by practicalswift** [comment]
Concept ACK
