### ISSUE TITLE
"Travis early exit to cache current state" message unclear

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#15738]
It's unclear what "Travis early exit to cache current state" errors in travis output signify. They seem to be triggered when something times out, but it's unclear if this is an error, or an expected condition or has something to do with a cache?

I think we can probably change the message to make it more clear and obvious, whatever it means.

**Comment by MarcoFalke** [comment]
See  travis: Switch to ubuntu keyserver to avoid timeouts #15693
