### ISSUE TITLE
importtmulti help text typo

### ISSUE THREAD

**Issue by gwillen** [bitcoin/bitcoin#15737]
The importmulti help text reads, in part: 

```
{                                                          (json object) If a ranged descriptor is used, this specifies the start and end of the range to import
           "start": n,                                              (numeric, optional, default=0) Start of the range to import
           "end": n,                                                (numeric, required) End of the range to import (inclusive)
},
```

This is a value for which a key is missing; it should be "range": { ...

**Comment by fanquake** [comment]
Where is this in the Core codebase? I can't see the above in the `importmulti` help text.

**Comment by gwillen** [comment]
It's in importmulti in rpcdump.cpp, search for "If a ranged descriptor is used". But apparently it was not in 0.17, and the code I'm currently running is already different from HEAD, as this was refactored in #15497. I am very perplexed as to how the code I'm looking at is generating the help text I'm seeing, and I wonder if there's a bug in RPCHelpMan, but I don't know that it's worth chasing, since the code has changed at HEAD and I'm not willing to rebase up right now to see if that fixed it.

**Comment by MarcoFalke** [comment]
Is this a bug in 0.17 (any tag or branch) or 0.18 (any tag or branch) or master? If not, this issue should be closed.

**Comment by MarcoFalke** [comment]
"range" is not in 0.17 and the help text in master (should be the same for 0.18) reads:

```
           ...
         ],
         "range": n or [n,n],                                       (numeric or array) If a ranged descriptor is used, this specifies the end or the range (in the form [begin,end]) to import
         "internal": bool,                                          (boolean, op...
```

**Comment by MarcoFalke** [comment]
Thu bug report is still valid, though. Thanks for reporting!
