### ISSUE TITLE
Unable to importprivkey

### ISSUE THREAD

**Issue by 0x23212f** [bitcoin/bitcoin#15736]
Have been trying to import some recovered private keys into bitcoin core for the past 2 days. After syncing the entire bitcoin blockchain, I've verified the same using `bitcoin-cli getnetworkinfo`.

Then, I've tried to run `bitcoin-cli importprivkey the_key "" true` to enable a rescan after import (since I wanted to do one at a time, to verify spend-ability of balances).

However, while looking at the debug.log, I notice that the rescan is complete, yet the balances are not updated across my wallets.

Since I am unable to determine why the balances are not updating, I am trying to import the address into bitcoin core first before importing the private key.

Note, that the private key I tried to import starts with a K and has 52 characters. The beginning part of the recovered path is: `m/44'/0'/0'/0/427`.

I expect to be able to import these balances and make them spendable. However, I'm not even able to see the balances when running `bitcoin-cli getwalletinfo`.

**Comment by gwillen** [comment]
With the quantity of bitcoins you describe involved, you may wish to consider deleting this issue for the sake of your privacy, and finding a more private route to get assistance. (Regrettably, it's hard for me to recommend a specific one; the developers are generally available on Freenode IRC, but it's important not to trust anybody whose bonafides you can't verify, and -- you probably already know this, but to be sure -- in general do not trust _anybody_ with private keys, or any bitcoin output you aren't _completely sure_ does not contain or reveal private keys. The actual developers will be scrupulously careful to avoid asking you for anything that would reveal them.)

**Comment by 0x23212f** [comment]
Thank you for the suggestions gwillen. I'm already on #bitcoin on Freenode. I got this far through the inputs of users there. Have redacted the amount, and deleted the version of the post that contains it. I hope that redacts it. Want to leave this question here in hopes of getting the attention of any developers that can help.

**Comment by gwillen** [comment]
Did you solve your problem?

**Comment by 0x23212f** [comment]
Hey gwillen, no unfortunately not :( It turns out that the private key doesn't correspond to that address, nor any other address on the list.

**Comment by gwillen** [comment]
@MarcoFalke note that there was already some IRC discussion on this -- I can point you to logs if desired.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
