### ISSUE TITLE
Display sendable (effective) balance

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#15767]
Right now the wallet can overstate the amount of funds that the user can send, causing frustration when the user goes to actually make a payment and find themselves unable.

This case happens when the wallet consists primarily of a large amount of near dust outputs during higher fee periods.

The wallet should have  probably some kind of indicator that shows the amount that could be sent by a all-greater-than-zero-effective-value (probably a single P2WSH output for estimation purposes?) transaction, perhaps with a control to adjust the feerate and defaulting to the current default feerate  E.g.   "Spendable Balance: ~0.12345 at feerate [0.00001 BTC/kvb]↕"

**Comment by gmaxwell** [comment]
(wallet feature request)

**Comment by gmaxwell** [comment]
Making the downsides of creating really low value outputs more legible would also help people make better decisions in how they manage their wallets.

**Comment by promag** [comment]
I think is should be tagged GUI?

Anyway, this could cause distress/confusion like "How can I spend the remaining balance?!" and so I think we should first make sure:
 - near dust changes are avoided - or show a warning?
 - coin selection could include extra input(s) if it's worth it.

**Comment by gmaxwell** [comment]
Coin selection already does those things-- it tries to get change to be at least 0.01 btc... and it also tries to make changeless payments (essentially being willing to throw away up to the cost of spending the future change as extra fee).

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.
