### ISSUE TITLE
Should this code run even if tx is not new and not update?

### ISSUE THREAD

**Issue by mxaddict** [bitcoin/bitcoin#15781]
https://github.com/bitcoin/bitcoin/blob/a7b486d6f8df868ff5b93b7152e4f7ce810fca78/src/wallet/wallet.cpp#L977-L995

Shouldn't this be more like this:

```cpp
    // Need to write to disk?
    if (!fInsertedNew && !fUpdated)
        return false;
    // Write to disk
    if (!walletdb.WriteTx(wtx))
        return false;
```

**Comment by promag** [comment]
No, currently `NotifyTransactionChanged` and `-walletnotify` are called if `!fInsertedNew && !fUpdated`.

**Comment by mxaddict** [comment]
> No, currently `NotifyTransactionChanged` and `-walletnotify` are called if `!fInsertedNew && !fUpdated`.

May I know what the rationale for running notify would be if it's not a new and not an updated tx?

**Comment by promag** [comment]
I can think of one or two, but more importantly is that it would be a breaking change. It would be better to have an option to do what you want, for instance https://github.com/bitcoin/bitcoin/pull/16050.

**Comment by mxaddict** [comment]
I see, which particular feature would be broken? I'm guessing there is/are
parts of the wallet that expect a call from notify?

**Comment by promag** [comment]
I mean it could break existing systems, not the wallet itself.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
