### ISSUE TITLE
How to get onion addresses for seeds

### ISSUE THREAD

**Issue by Emzy** [bitcoin/bitcoin#15793]
thank you @Emzy!
however, your list doesn't have onion addresses at all

_Originally posted by @laanwj in https://github.com/bitcoin/bitcoin/pull/15791#issuecomment-482106576_

I have no idea why.
My comandline is: 
./dnsseed -h dnsseed.emzy.de -n node3.emzy.de -m emzy.emzy.de -p 5353

**Comment by Emzy** [comment]
I hat to use the -o option. And have the tor daemon running:
./dnsseed -h dnsseed.emzy.de -n node3.emzy.de -m emzy.emzy.de -o 127.0.0.1:9050 -p 5353

Now it works.

**Comment by Sjors** [comment]
Thanks, I'll enable this on my seeds as well soon (tm). cc @sipa, @petertodd, @jonasschnelli
