### ISSUE TITLE
Signing transactions locked with OP_CHECKLOCKTIMEVERIFY

### ISSUE THREAD

**Issue by nkostoulas** [bitcoin/bitcoin#15807]
I've been trying to send and sign a transaction paying to a multisig locked with `<locktime> OP_CHECKLOCKTIMEVERIFY OP_DROP` and noticed that this is considered nonstandard in bitcoin and thus not possible.

Are there any plans or interest in implementing something like this?

I've implemented this in a fork using a new transaction type (TX_LOCKED_MULTISIG), where the Solver first checks for the lock script above and then proceeds to "MatchMultisig". Similarly this new type can be recognised when signing the transaction by simply ignoring the preceding lock script, which is checked when verifying the script anyway. 

It would be quite straightforward to implement for the remaining standard transaction types as well or maybe even better with some manipulation use a single transaction type if possible.

**Comment by sipa** [comment]
Is your problem that (a) the signing logic doesn't support such transactions or (b) such outputs are nonstandard? These are independent things.

For (a), sure, signing more things is perfectly reasonable. I'm working myself on support a much larger class of scripts in the signing logic (I talked about it at SBC'19: https://www.youtube.com/watch?v=XM1lzN4Zfks).

For (b), you should just use P2SH/P2WSH, where such scripts are already standard. In raw scripts I doubt they'll ever be made standard.

**Comment by nkostoulas** [comment]
Problem is mostly (a) that I am not able to sign it with the bitcoin wallet. How can you do (a) and not (b) though, since with the current wallet API nonstandard transactions cannot be signed?

**Comment by sipa** [comment]
@nkostoulas That's a currently implementation detail; it's not hard to add more supported scripts to the signer without affecting mempool policy.

**Comment by nkostoulas** [comment]
@sipa Cool I'd be willing to do that. Would this be an extension to the signing step to handle the non-standard case or were you thinking of a different implementation?

What would be the reason though for allowing signing such transactions if they are going to be rejected anyway?

**Comment by sipa** [comment]
@nkostoulas They aren't nonstandard inside P2SH and P2WSH (as the "only known script templates are allowed" rule doesn't apply to them).

**Comment by nkostoulas** [comment]
@sipa right of course thanks :) I'll have a go

**Comment by sipa** [comment]
@nkostoulas I'm working on a larger project called miniscript that includes expanding signer's abilities to support more complex scripts, including ones with locktimes.

There is a demo for part of it on http://bitcoin.sipa.be/miniscript/miniscript.html; the idea is that any script you can construct using that simple policy language described there would be trivial to build a signer for.

**Comment by nkostoulas** [comment]
@sipa ah ok interesting! So I guess it wouldn't make much sense to add some specialised cases just for lock time right now?

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
