### ISSUE TITLE
Why bitcoin stop syncing if reached 2018?

### ISSUE THREAD

**Issue by Mannshoch** [bitcoin/bitcoin#15811]
I tried now for two times to get a synced Bitcoin walled but both time bitcoin stop syncing around a year ago.  Around 1Year and 30 Weks  bitcoin do not find any peers for syncing the Blockchain.

Bitcoin Core v0.17.1 and now with v0.17.99.0

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by fanquake** [comment]
Closing due to lack of followup, can be re-opened if more info is provided.
