### ISSUE TITLE
Suggestion: In-wallet hotswaps & exchange listings

### ISSUE THREAD

**Issue by leshacat** [bitcoin/bitcoin#15837]
Not sure why you use Stack Exchange, a closed & censored community... Should switch over to a crypto based or at least an open, uncensored community.

Anyways I have suggestion to increase bitcoin usefulness and value, "in-wallet exchange listings"

_Can we have something like LocalBitcoins.com built into the client?_ Localbitcoins allows you to place "ads" for buying or selling bitcoin in person, or over etransfer, etc. all sorted by Country/State/City -- but they recently changed to require KYC :-1: 

That way everyone can cash in and out of BTC/FIAT with either local meetups, or using email money transfer, etc. without having to provide identifications...

Used along with in-wallet hotswaps, this blows away need for exchanges / wash trading / fake volume / fees / etc

I think is good idea :+1: 

If not just close ticket. 

Thanks :)

**Comment by benthecarman** [comment]
NACK, this can be an idea for a separate wallet or service but should not be built into bitcoin core

**Comment by satoshe** [comment]
Thanks for sharing your idea, it's good. but more useful for reddit or a forum.

IMO we don't need any bloating add-ons on bitcoin core.

**Comment by fanquake** [comment]
Indeed, this is not something that would be built into Bitcoin Core.
