### ISSUE TITLE
Use of geteuid was removed from c_test.c

### ISSUE THREAD

**Issue by D3m0nKingx** [bitcoin/bitcoin#15857]
Use of geteuid was removed from c_test.c in https://github.com/google/leveldb/commit/623d014a54f8cf9b74ad6aaba9181ca1e65c43a1.

https://github.com/google/leveldb/issues/675#issuecomment-484967315

Albeit normal Linux compilation are successful. When trying to cross-compile for Win32/64 platforms it fails on compiling tests due to undefined reference to geteuid.  

Furthermore, leveldb has changed over to cmake build system as well with version 1.21. Is this something bitcoin will be updating to ?

**Comment by laanwj** [comment]
I don't know about your cross-compile issue. Can you be more specific what you're trying to do? It looks like the gitian cross-compile builds, nor the MSVC build suffer from this issue. `c_test.c` is not part of anything built as part of bitcoin.

> Furthermore, leveldb has changed over to cmake build system as well with version 1.21. Is this something bitcoin will be updating to ?

No, the build system will not be changed.

**Comment by MarcoFalke** [comment]
Please provide exact steps to reproduce, I will reopen when they are available.
