### ISSUE TITLE
feature request (disabling signrawtransaction

### ISSUE THREAD

**Issue by Devrandomuser** [bitcoin/bitcoin#15860]
Dear bitcoin developers,

is there a way to disable the 'input' check for the `signrawtransaction ` command?
I'm using many multisig based transactions, for some multisig verification process, it would be nice to disable the internal check of `signrawtransaction`, so I can make sure users are able to sign transactions with their provided public key, without spending satoshis (to create a valid input for a transaction, the user should sign).

Including a switch to disable the check would be fine for offline signing too I think.

Problem described already here:
[bitcointalk development section](https://bitcointalk.org/index.php?topic=5086620.msg48743108)

**Comment by uFire** [comment]
My vote for this feature. Sometimes I need to create and sign a chain of offline transactions but Bitcoin Core won't let me sign all of them because of no inputs found by internal check.

**Comment by MarcoFalke** [comment]
There is no `signrawtransaction` any more. I presume you mean `signrawtransactionwithwallet`? Could you include minimal steps to reproduce this in regtest?

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
