### ISSUE TITLE
Is "hdmasterkeyid" safe to share publicly?

### ISSUE THREAD

**Issue by mxaddict** [bitcoin/bitcoin#15879]
Is "hdmasterkeyid" safe to share publicly?

I'm referring to the "hdmasterkeyid" that is output with "getwalletinfo" command

**Comment by jonasschnelli** [comment]
Maybe you should define "safe" first...

But the `hdmasterkeyid` (now called `hdseedid`) is a hash160 (RIPEMD-160) of the HD master keys (*seed keys*) **public key**. An attacker would need to solve the discrete logarithm problem to spend your funds based on the id (same level of complexity if one tries to spend bitcoin by only knowing an address)... and, of course the attacker also would need to "reverse" RIPEMD-160 (there are AFAIK no known/published collisions).

If "safe" means that someone **having a really hard time** trying to spend your coins based on the `hdseedid`(`hdmasterkeyid`), then yes. It would say it's "safe".

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
