### ISSUE TITLE
How to return input address in getrawtransaction？

### ISSUE THREAD

**Issue by longfens** [bitcoin/bitcoin#15875]
**I am unable to get the information of the input address when I queried a transaction details.**

#
bitcoin-cli getrawtransaction data

`{
	"txid": "6a402d0bba117f3f49780c646d03b9ada1e92176328834f1327eac3bf7d5167f",
	"hash": "6a402d0bba117f3f49780c646d03b9ada1e92176328834f1327eac3bf7d5167f",
	"version": 1,
	"size": 191,
	"vsize": 191,
	"weight": 764,
	"locktime": 0,
	"vin": [{
		"txid": "f729fabb178cfe58fec7b7181a4a32a88afc40eea75845575fe3e621a417a234",
		"vout": 0,
		"scriptSig": {
			"asm": "304402205f040f4582e212ccdd185943dd9ed76b258061f03f6cd13c57304dbbeff38dc502206196d41f143bbce09887cf3a025453a26cd11e4a588320018fd86dcf51c496b7[ALL] 0365cd3b076fb1eb4e2e029108d621f7641c735b1f7bb190d21eab2f75293f5b36",
			"hex": "47304402205f040f4582e212ccdd185943dd9ed76b258061f03f6cd13c57304dbbeff38dc502206196d41f143bbce09887cf3a025453a26cd11e4a588320018fd86dcf51c496b701210365cd3b076fb1eb4e2e029108d621f7641c735b1f7bb190d21eab2f75293f5b36"
		},
		"sequence": 4294967295
	}],
	"vout": [{
		"value": "0.00755200",
		"n": 0,
		"scriptPubKey": {
			"asm": "OP_DUP OP_HASH160 c6dece7fd7e1e525b0e767e532876d3f5508ac42 OP_EQUALVERIFY OP_CHECKSIG",
			"hex": "76a914c6dece7fd7e1e525b0e767e532876d3f5508ac4288ac",
			"reqSigs": 1,
			"type": "pubkeyhash",
			"addresses": ["1K8Xhrpq6mLH9Ws1KoHKQc33Fz2G72mv3c"]
		}
	}],
	"hex": "010000000134a217a421e6e35f574558a7ee40fc8aa8324a1a18b7c7fe58fe8c17bbfa29f7000000006a47304402205f040f4582e212ccdd185943dd9ed76b258061f03f6cd13c57304dbbeff38dc502206196d41f143bbce09887cf3a025453a26cd11e4a588320018fd86dcf51c496b701210365cd3b076fb1eb4e2e029108d621f7641c735b1f7bb190d21eab2f75293f5b36ffffffff0100860b00000000001976a914c6dece7fd7e1e525b0e767e532876d3f5508ac4288ac00000000"
}`

[https://btc.com/6a402d0bba117f3f49780c646d03b9ada1e92176328834f1327eac3bf7d5167f](https://btc.com/6a402d0bba117f3f49780c646d03b9ada1e92176328834f1327eac3bf7d5167f)

Thank you very much

**Comment by longfens** [comment]
Ask for help... thanks

**Comment by sipa** [comment]
There are many answers to this question (and why it's a bad idea) on https://bitcoin.stackexchange.com.
