### ISSUE TITLE
Please support watching bar Multisig transaction for watch address

### ISSUE THREAD

**Issue by ytrezq** [bitcoin/bitcoin#15882]
If importing addresses like `18p4JBHP3EAKCc4jqN8XzuEJtvq8G9NAot` as watch only, no transaction appears whereas `18p4JBHP3EAKCc4jqN8XzuEJtvq8G9NAot` received coins in several bar MultiSig transactions like `5ed3694e8a4fa8d3ec5c75eb6789492c69e65511522b220e94ab51da2b6dd53f`.

So bare Multisig transaction aren’t affected by watch addresses. While I recognize the behaviour makes security sense for addresses with private keys, this doesn’t for watch addresses Please fix this !

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
