### ISSUE TITLE
Possible sendtoaddress improvement?

### ISSUE THREAD

**Issue by dufferzafar** [bitcoin/bitcoin#15885]
I've been going through all the code that runs to serve a "sendtoaddress" call, to find potential improvements.

One control flow path looks like: `sendtoaddress` -> `SendMoney` -> `CreateTransaction` -> `AvailableCoins` + `SelectCoins`

Now, `AvailableCoins` iterates upon all the txn entries in the wallet and stores usable ones into a list. This list is later trimmed down by `SelectCoins`.

So, we end up building a huge list every time `sendtoaddress` is called, only to trim it down later.

Wouldn't it be better if we could tell `AvailableCoins` to only select coins of required value? 

I think the `nMinimumSumAmount` parameter in `AvailableCoins` was made for this purpose only?

**Comment by MarcoFalke** [comment]
How expensive of an operation is it to create the list compared to running the selection logic and signing?

**Comment by promag** [comment]
> Wouldn't it be better if we could tell `AvailableCoins` to only select coins of required value?

`SelectCoins` needs all of them in order to select the best set for the target value.

> I think the `nMinimumSumAmount` parameter in `AvailableCoins` was made for this purpose only?

No, it was added for `listunspent`.

**Comment by MarcoFalke** [comment]
Closing for now. Though, improvements are definitely welcome as pull requests
