### ISSUE TITLE
I want all the error codes thrown by BTC transaction errors,where can i get them?

### ISSUE THREAD

**Issue by simplewhale** [bitcoin/bitcoin#15889]

**Comment by simplewhale** [comment]
I want all the error codes thrown by BTC transaction errors,where can i get them?

**Comment by simplewhale** [comment]
thanks

**Comment by AliceOJJm** [comment]
This might be what you are looking for https://github.com/bitcoin/bitcoin/blob/0.18/src/rpc/protocol.h
