### ISSUE TITLE
Bug related to blocknotify/walletnotify with Bitcoin Core on Windows.

### ISSUE THREAD

**Issue by EAFSC** [bitcoin/bitcoin#15883]
This was posted back in 2014 but still applies in 2019 with the latest stable Bitcoin Core: https://bitcoin.stackexchange.com/questions/23999/blocknotify-walletnotify-but-without-the-console-window

The blocknotify/walletnotify configuration directives, which call a command on the computer, force a brief, flickering window each time it's run which will drive anyone insane if exposed to it day after day. It's like Chinese water torture.

I've tried every trick in the book to attempt to bypass this, but it's just not possible without modifications to the Bitcoin Core source code. I ask you to fix this (a solution is apparently in the link) so that I can run my Bitcoin payment system while using the computer and not go insane from the little windows that keep flashing by!

**Comment by darosior** [comment]
What command did you set to be called ? I'm trying to fix it and wanted to test under the same conditions (i'll try in a W10 VM tomorrow, feel free to try on your system too https://github.com/darosior/bitcoin/tree/windows_blocknotify_blink).

**Comment by EAFSC** [comment]
This:

	blocknotify =	php "C:\blablabla\handler.php" blocknotify %s
	walletnotify =	php "C:\blablabla\handler.php" walletnotify %s

Some variants that have also been tried:

	blocknotify =	start /min php "C:\blablabla\handler.php" blocknotify %s
	blocknotify =	cmd.exe /C php "C:\blablabla\handler.php" blocknotify %s
	blocknotify =	start "" /MIN cmd.exe /C php "C:\blablabla\handler.php" blocknotify %s

**Comment by darosior** [comment]
This should be fixed in https://github.com/darosior/bitcoin/tree/windows_blocknotify_blink (I tested on a W10 32bits in VirtualBox with `bitcoind.exe -blocknotify=C:\Windows\System32\notepad.exe`). Could you give it a try ?

**Comment by EAFSC** [comment]
Well, I took a look and the changed code sure *looks* like it will work, but I can't figure out how to get a Windows binary from the Github repo. The latest file in "release" is v0.17.1 from late 2018. If it's implied that I have to build it locally, then sorry, I can't do it. Very thankful that you fixed (probably) this, though! I look forward to the next stable Bitcoin Core release!

**Comment by darosior** [comment]
You have to build it using Ubuntu https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

**Comment by EAFSC** [comment]
Shouldn't all of this be automated so that each release (or test release) is built for all platforms at the press of a button?

**Comment by darosior** [comment]
No the release process is very touchy. Aren't you able to compile the sources ?

**Comment by EAFSC** [comment]
I'm not a Bitcoin Core developer, so having to do a bunch of things is obviously unrealistic. I remember past experiences of trying to set up environments to build others' code, and it's a nightmare I will never deal with again in my life unless (maybe) under direct gun point. Still, thanks for (hopefully) fixing the bug.

**Comment by promag** [comment]
Does this happen with bitcoind, bitcoin-qt or both?

**Comment by EAFSC** [comment]
What do you mean?

**Comment by EAFSC** [comment]
I mean, I run Bitcoin Core as the normal GUI thing on Windows. It has a config. The config is where I have put the directives.

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/issues/15883#issuecomment-487293448
> I can't figure out how to get a Windows binary from the Github repo

I think @DrahtBot can create binaries (https://github.com/bitcoin/bitcoin/pull/13788#issuecomment-481606552), but I'm not sure how to trigger it.

**Comment by fanquake** [comment]
@ryanofsky AFAIU it's triggered by the addition of the "Needs gitian build" label.

**Comment by Shub77** [comment]
This fix point to fix the problem with the Qt version running under Windows. 

I fix it changing the way the external command is invoked.

In `src/util/system.cpp` , in the `runCommand` function, I changed:

    int nErr = ::_wsystem(std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>,wchar_t>().from_bytes(strCommand).c_str());

to:

    UINT nErr = WinExec(strCommand.c_str(), SW_SHOWDEFAULT);
    if (nErr > 31) {
        nErr = 0;
    }

Reference: [https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-winexec](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-winexec)

Now no more annoying black windows popping out when I call VLC to play a sound. But should be tested more. WARNING: surround the command with double quotes to prevent a security issue:

    blocknotify="c:\program files\dunno\whatever.exe" -A -B -C 

Note: no further include was necessary, it compiled right as it was under WSL with mingw toolchain and tested uner Windows 10 10.0.17763.615

**Comment by ryanofsky** [comment]
#15909 was closed, but if #15382 is merged, it should make this problem easy to solve without requiring windows-specific code or expertise. 

There don't appear to be any technical problems with #15382, just indecision about #15440 and whether to allow adding boost process as an optional dependency .

**Comment by luke-jr** [comment]
I noticed the problem case always launches php.exe, which I assume is a command line program. What happens if you launch a non-CL program instead?

**Comment by willcl-ark** [comment]
This feature request does not seem to have attracted much attention from other contributors. As such, it does not seem important enough to keep it sitting around idle in the list of open issues. Closing due to lack of interest.

Pull requests with improvements are always welcome.
