### ISSUE TITLE
если разбераешся подскажи я скопировал адрес кошелька и перевел на него деньги с обменника,потом пытался остановить загрузку блоков 220 гигов в биткоин коре и сбросил опции кошелька.придет мне транзакция или нет не укого спросить службы поддержки у них нет

### ISSUE THREAD

**Issue by Sosna28** [bitcoin/bitcoin#15892]

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by MarcoFalke** [comment]
For reference google translate is

"if you understand, tell me I copied the address of the wallet and transferred money from the exchanger to it, then I tried to stop loading blocks of 220 gigs in the bitcoin bark and reset the wallet options."
