### ISSUE TITLE
Unifiy network activity status and 'connect' command line option

### ISSUE THREAD

**Issue by anddam** [bitcoin/bitcoin#15900]
When starting `bitcoin-qt` with `-noconnect` or equivalently `-connect-0`, I expected the network activity icon in bottom right of the main windows to be in the `Network activity disabled`, with the `X` icon.
  
The network activity indicator has its active icon instead, while correctly reporting `0 active connections to Bitcoin network`.

I can always reproduce the issue.

Installed Bitcoin Core is version 0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8 (64-bit) from http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu PPA.
 
The operating system is elementary OS 5.0 on a Intel(R) Core(TM) i5-6200U, disk type is a SSD SATA2.

The network enabled status should be unified with the `connect` command line parameter.

Since the latter is not a boolean flag but a list of IP address and considering the behavior of `InterpretNegatedOption()`, I figure setting the network activity status to false if `connect` `0` could be enough.

**Comment by MarcoFalke** [comment]
Does noconnect disable listen?

**Comment by luke-jr** [comment]
It should. `-connect=`* (including =0) is supposed to only connect to specified peers.

**Comment by MarcoFalke** [comment]
Ok, so it seems that this feature request is based on the misunderstanding that those are not equal?

* connect: Only manual connections are made (via GUI console or RPC)
* network disabled in the GUI: No connections can be made at all

**Comment by luke-jr** [comment]
AIUI, the request is to make the "network disabled" mode of these equivalent.

So a node with `-connect=0` could have networking enabled via GUI.

**Comment by anddam** [comment]
@MarcoFalke 

> Ok, so it seems that this feature request is based on the misunderstanding that those are not equal?

No, that is well understood but since `-connect` seems the only argument to prevent network connection from CLI I'm suggesting to at least set network activity according to `-connect=0` at start.

I'm suggesting this due to what a `-noconnect` argument seems to imply.

@luke-jr 

> So a node with -connect=0 could have networking enabled via GUI.

Exactly, the network activity status would stay separated and could be manually switched on by the user.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Comment by MarcoFalke** [comment]
Implemented in #19473

**Comment by anddam** [comment]
Will check it, thanks!
