### ISSUE TITLE
Running Bitcoin on IPFS

### ISSUE THREAD

**Issue by hito** [bitcoin/bitcoin#15907]
Has anyone tried this? What is the performance like compared to a local SSD filesystem formatted in ext4 or XFS? What is the performance like compared to a NFS solution like LizardFS?

**Comment by terorie** [comment]
What exactly are you trying to achieve and why?

IPFS is not a file system despite the name. It's "a peer-to-peer hypermedia protocol" for accessing files over the network. It's useless and inevitably slower for just storing the data (blocks and chainstate) locally.

It's an interesting technology for accessing blockchain data over the network, though. The naive approach, sharing Bitcoin's LevelDB files on IPFS UnixFS ("uploading" the Bitcoin folder), isn't very useful.

By using IPLD however, one could directly traverse the Bitcoin blockchain over IPFS in its binary format even using the same hashes as on Bitcoin (albeit with prefixes) to address content.
It's a nice technology that could be used to (partially) replace the `inv` mechanism used to share Bitcoin data peer-to-peer.

Here's an example of an Ethereum block accessed over IPFS. It seems like Bitcoin bindings also exist. https://github.com/ipld/js-ipld-bitcoin
<img width="942" alt="Ethereum/IPFS" src="https://user-images.githubusercontent.com/21371810/56856592-43fce400-695e-11e9-92d3-171c5a11b9a6.png">

Read more at https://github.com/ipfs/ipfs/issues/263

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
