### ISSUE TITLE
[macOS] [GUI] log entries when hovering on / over File->Open Wallet

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#15912]
Was wondering where those millions of log entries `IsBerkeleyBtree: No such file or directory <walletdir/wallet>` come from. Figured out, whenever hovering over the menu, such an entry is made for each and every wallet in the wallet dir. 
That's not very helpful when frequently used...

apparently #15583 didn't fix that

**Comment by promag** [comment]
#15583 fixed a crash.

I think these log messages can be avoided when calling `listwalletdir`.
