### ISSUE TITLE
posix_fallocate deadlocks on ntfs if more than three nodes are started

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15910]
Starting four nodes will make them deadlock on the posix_fallocate call (and thus respond with  `Loading block index... (-28)` on the RPC forever)

Steps to reproduce:

* Create NTFS partition on hdd
* Run the test runner with `TMP=/path/to/the/ntfs/partition ./test/functional/test_runner.py -j 9`

posix_fallocate falls back to fallocate on ntfs according to http://man7.org/linux/man-pages/man3/posix_fallocate.3.html#NOTES, not sure if that is relevant

**Comment by hebasto** [comment]
@MarcoFalke 
What are the driver (kernel's `ntfs` or `ntfs-3g`) and mount options?

**Comment by MarcoFalke** [comment]
Not sure how to get them I use `files 3.32.0-stable` to mount it.

```
$ mount -l | grep 2CC35B3543E3A1E4
/dev/sda4 on /run/media/marco/2CC35B3543E3A1E4 type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)

**Comment by hebasto** [comment]
@MarcoFalke 
I cannot reproduce this issue on Linux Mint 19.1.
Maybe, it is dependent on distro? Assuming you are running Fedora ;)
My machine has only 4 cores. Can this affect the `test_runner.py` behavior?

Is it still an issue after merging PR #15650?

**Comment by MarcoFalke** [comment]
Looks like leveldb has issues with ntfs: E.g. #10787
