### ISSUE TITLE
getblock performance issue on verbosity

### ISSUE THREAD

**Issue by fanatid** [bitcoin/bitcoin#15925]
`getblock` is slow on verbosity, it's happened because `LOCK(cs_main)` applied for whole function including JSON generation
https://github.com/bitcoin/bitcoin/blob/ef70f9b52b851c7997a9f1a0834714e3eebc1fd8/src/rpc/blockchain.cpp#L810

I added few lines which print spent time:
```cpp
    LOCK(cs_main);
    auto t1 = std::chrono::high_resolution_clock::now();
...
    auto t2 = std::chrono::high_resolution_clock::now();
    auto ret = blockToJSON(block, pblockindex, verbosity >= 2);
    auto t3 = std::chrono::high_resolution_clock::now();
    std::cout << "blockToJSON " << pblockindex->nHeight << ": " << std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count() << " " << std::chrono::duration_cast<std::chrono::microseconds>(t3 - t1).count() << std::endl;
    return ret;
```

and numbers looks like:
```
blockToJSON 570019: 14727 201870
blockToJSON 570022: 16049 225224
blockToJSON 570021: 33776 217398
blockToJSON 570020: 21754 191669
blockToJSON 570023: 30949 236941
blockToJSON 570025: 23346 223673
blockToJSON 570024: 18732 203002
blockToJSON 570026: 17467 216213
blockToJSON 570027: 16658 217395
blockToJSON 570028: 19015 219183
```

i.e. everything before JSON generation takes 15-30ms, while JSON takes minimum 190ms and lock `cs_main` for all this time. As result it's possible extract only ~5 blocks per second.

Looking on the code I think it's possible copy data from `CBlockIndex` to extra structure, so in this case `cs_main` can be unlocked right after `GetBlockChecked`.
https://github.com/bitcoin/bitcoin/blob/ef70f9b52b851c7997a9f1a0834714e3eebc1fd8/src/rpc/blockchain.cpp#L828
As result `getblock` in verbosity mode should be much faster (in case if `-rpcthreads` will be adjusted too).

Does this make sense?

**Comment by jonasschnelli** [comment]
Reducing the usage of the `cs_main` lock is desirable. Though your approach "only" focuses on increasing the concurrency efficiency.

IMO the JSON RPC interface is not made for efficiency.

If you seek fast block fetches, you are much better off with using a) **the p2p API** or b) **the REST API** with binary or at least hex encoding.

**Comment by ryanofsky** [comment]
> If you seek fast block fetches, you are much better off with using a) the p2p API or b) the REST API with binary or at least hex encoding.

This is good advice, but it's still interesting to know how time is being spent in the RPC, and I don't think we'd reject a simple PR optimizing it.

**Comment by promag** [comment]
So JSON serialization takes around 10 times more than loading the block? 🙄

**Comment by MarcoFalke** [comment]
Yeah, could be the typical o2 complexity thing with univalue?

**Comment by sipa** [comment]
Adding UniValue functions with move semantics/rvalue refs would help a lot...

**Comment by promag** [comment]
> Yeah, could be the typical o2 complexity thing with univalue?

I don't think it's the case here.

**Comment by MarcoFalke** [comment]
Keeping this open since translating to json takes 100ms, which seems a bit extreme.

**Comment by jgarzik** [comment]
> Adding UniValue functions with move semantics/rvalue refs would help a lot...

Sounds good to me

**Comment by promag** [comment]
Just to have some idea of what's going on with `blockToJSON`, this is a rough (some of the fields are commented) benchmark with block 413567.
![Screenshot 2019-05-07 at 16 40 33](https://user-images.githubusercontent.com/3534524/57313149-e2b7dc00-70e6-11e9-80fa-8b18c4766650.png)
BTW, this was taken with some `std::moves` already implemented.

**Comment by fanatid** [comment]
@promag can you show you code for `BENCHMARK(BlockToJSON, 40)`? Thank you in advance!

**Comment by promag** [comment]
@fanatid sorry I've missed your comment 😞 thanks for the pull request!

**Comment by MarcoFalke** [comment]
Closing this for now. Translating to json is inherently more expensive than serving the raw block, but as you realized, with the cs_main lock removed, at least it can be done in parallel.
