### ISSUE TITLE
wallet will not sync it has been a week and I still do not have my money in the wallet. It took out my account.

### ISSUE THREAD

**Issue by samydonna** [bitcoin/bitcoin#15924]
wallet will not sync it has been a week and I still do not have my money in the wallet. It took out my account.

**Comment by promag** [comment]
You should ask in https://bitcoin.stackexchange.com while providing more details so someone can help.

**Comment by fanquake** [comment]
Indeed, this issue tracker is specifically for technical issues/discussion, not for general usage questions.
