### ISSUE TITLE
BanMan::IsBannedLevel should return an enum

### ISSUE THREAD

**Issue by jonnygrant** [bitcoin/bitcoin#15929]
Would a patch be supported to change this function to return enum?

This function is returning magic numbers [0, 1, 2}
bitcoin/src/banman.cpp
int BanMan::IsBannedLevel(CNetAddr net_addr)

Should use an enum. 

latest github trunk.

**Comment by promag** [comment]
The return value is explained in
https://github.com/bitcoin/bitcoin/blob/94daebf327e38ebb0c578bffbabe76961e11d9ee/src/banman.cpp#L72-L75

And `IsBannedLevel` return value is used here only
https://github.com/bitcoin/bitcoin/blob/94daebf327e38ebb0c578bffbabe76961e11d9ee/src/net.cpp#L940
https://github.com/bitcoin/bitcoin/blob/94daebf327e38ebb0c578bffbabe76961e11d9ee/src/net.cpp#L964
So in this case I don't see how just changing to `enum` improves it.

**Comment by jonnygrant** [comment]
Magic numbers are often bad. As you can see people had to use the magic number elsewhere. Why are you defending it?

**Comment by promag** [comment]
If your suggestion is not replacing `int` with `enum` then please open a PR with the actual suggestion and I'll happily review it.

**Comment by jonnygrant** [comment]
That's exactly my suggestion. Why do you feel a magic number is better?

**Comment by jonnygrant** [comment]
Feels like a difficult project to contribute to, is it really like this?
Actually found this little issue in the first file I opened specifically to see if Bitcoin Core team were receptive to improvements.

**Comment by dakk** [comment]
if you think it could be useful to migrate the bannedlevel from an int to an enum, I wrote the modification in this branch and I can open a pr: https://github.com/dakk/bitcoin/commits/ban-level-enum

**Comment by promag** [comment]
You can see my point in @dakk's commit b57206abfcc003176b093de7e68e2b73135dea41 where the `operator>` is used. Maybe that line should be
```cpp
pnode->m_prefer_evict = bannedlevel != NOT_BANNED;
```

**Comment by dakk** [comment]
I changed the code as you proposed, and transformed the enum to an enum class as suggested in the code guidelines

**Comment by jonnygrant** [comment]
A C++ Enum in CAPS is bad coding style. Have you seen Cpp Core Guidelines?

Also there are still bad hard coded numbers in comments, duplicating the
code. Those comments I would simply be removed. The code is self
explanatory.

I proposed this simple change. Can I simply implement it please?

Thanks
Jonny

**Comment by promag** [comment]
> Can I simply implement it please?

@jonnygrant you are free to implement and submit whatever you want without asking for permission.

**Comment by dakk** [comment]
> A C++ Enum in CAPS is bad coding style. Have you seen Cpp Core Guidelines?

btw in this repo guidelines there are no constraint for this, and most enums use uppercase names (if we consider enum values as constants, this rule will apply "Constant names are all uppercase, and use `_` to separate words.")

**Comment by jonnygrant** [comment]
Looks like some duplication of effort if you're making the same changes as me, after I propose a change.

Const isn't an enum.

I can submit my patch later. About the enum, it's kind of just common sense. The enum is not a pre-processor macro, they are the only things in all CAPS.


https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md
Enum.5: Don't use ALL_CAPS for enumerators

**Comment by jonnygrant** [comment]
@promag Would submit my changes, but saw see someone else duplicating my effort. Can we agree I'll implement my proposed change?

**Comment by jonnygrant** [comment]
I was going to make it as GetBannedLevel (not sure why it was IsBannedLevel)

**Comment by dakk** [comment]
@jonnygrant I wrote here I was working on it; I've no intention to duplicate work

**Comment by sdaftuar** [comment]
I think it's pointless to change this code around purely for style reasons; let's refactor it when the functionality is changed or extended in some way and it makes sense to adjust the implementation.

Concept NACK.
