### ISSUE TITLE
Path error messages while executing test_bitcoin

### ISSUE THREAD

**Issue by sumBTC** [bitcoin/bitcoin#15944]
Compiled bitcoin-0.18.0.tar.gz from https://bitcoin.org/bin/bitcoin-core-0.18.0/ on Ubuntu 18.04.2 LTS (using [this](http://Bitkoins.nl/maken.txt) (simple) bash script). The compilation went well (had to add doxygen to suppress a warning message). When running the test: `test_bitcoin` in `bitcoin-0.18.0/src/test/`, I get the following error messages (multiple times):

`Error: Specified -walletdir "/tmp/test_bitcoin/1556861148_943311758/tempdir/path_does_not_exist" does not exist`

and

`Error: Specified -walletdir "/tmp/test_bitcoin/1556861730_643733972/tempdir/not_a_directory.dat" is not a directory`

and

`Error: Specified -walletdir "wallets" is a relative path`

Note that at the end it still says: `*** No errors detected`

**Comment by MarcoFalke** [comment]
I believe this is an `InitError`, which are logged to the `debug.log` as well as stdout (or stderr, I don't recall).

To avoid the error to appear you could maybe disconnect the ui slot temporarily?

**Comment by practicalswift** [comment]
@sumBTC The repeated error messages were fixed in https://github.com/bitcoin/bitcoin/pull/15352 - after that you should only get one error message per error.

I agree that passing tests should be silent: this should be fixed :-)

**Comment by jonasnick** [comment]
Fwiw, I'm seeing the same output (repeated `does not exist`, `is not a directory`, `is a relative path`) when running `test_bitcoin` from the binary release on archlinux.

**Comment by sumBTC** [comment]
@practicalswift  

> agree that passing tests should be silent. 

that's indeed why I reported this :-), I don't think the errors are very serious but they are a bit "all over the screen". Thanks for the feedback!

**Comment by 0xB10C** [comment]
For context:

Comment on this from @PierreRochard in his PR that implemented the test cases https://github.com/bitcoin/bitcoin/pull/14146#issuecomment-421112726
