### ISSUE TITLE
Can't open wallet 

### ISSUE THREAD

**Issue by B5Happy** [bitcoin/bitcoin#15952]
Hello evryone, I get nothing when I click in open wallet, I am new to bitcoin and expect to show something.

![BitcoinIssue](https://user-images.githubusercontent.com/39341595/57179721-5024fc00-6e9e-11e9-80dd-af5e4345be48.png)

I'am using Bitcoin Core (both in testnet and mainnet, didn't work) 0.18 on window 10.

**Comment by promag** [comment]
The default wallet is already open. If you had more wallets then they would show on that submenu.

**Comment by debuggor** [comment]
i think, you should try some rpc order at the begining, to familiar with it
