### ISSUE TITLE
make bitcoin-cli a shared object

### ISSUE THREAD

**Issue by red0bear** [bitcoin/bitcoin#15961]
i see in this issue about old commands https://github.com/bitcoin/bitcoin/pull/12953 and 'm here thinking about what deprecatedrpc in 0.17 to transition to 0.18 impact to me developing a code in java .... since i don't need to worry about drastic changes . 

i wish do access it with JNA. Just a direct  call from native client to fain more time than dev a rpc protocol. But need know if dev team wish use this idea or have problems , security issues about use this. 

Just the idea .....

**Comment by jonasschnelli** [comment]
I don't understand your approach I think.
Bitcoin-cli is a bitcoind tailored RPC client. Not more.

If you want to communicate from Java with bitcoind, use a JAVA RPC library?

What benefits do you expect from using bitcoin-cli as a shared object?

**Comment by red0bear** [comment]
@jonasschnelli , At least a shared object i could do direct commands instead build a URL in java for example , and don't need to always wait updates from who build java prc commands, make forks to update or just look to another one in git hub.

You can use the same base in bitcoin-cli but just make a sharedobject where can return commands in string JSON. 

Well , you know what you could do. I just came here with a suggestion.

**Comment by red0bear** [comment]
@jonasschnelli , i just make a update from my project to see what happen . I make a command line via C++ to execute commands via bitcoin-cli : 
https://github.com/red0bear/wallet_manager_m/tree/master/command_cli

Using with JNA gave me possibility make progress more fast .... but still wish have a shared object in format in what i made now.
