### ISSUE TITLE
Ошибка создания адресов

### ISSUE THREAD

**Issue by dem10** [bitcoin/bitcoin#15972]
Почему то пропала возможность генерировать адреса.Открываю вкладку-адреса получения-там нет адреса и нет кнопки -новый адрес-.Кнопка -новый адрес-почему то появилась в адресах для отправки.В итоге пустой wallet.dat .Такое началось с релиза 0.17,на релизах 0.16 всё на месте и нормально создает адреса. win10

**Comment by fanquake** [comment]
Rough Google translate:
> For some reason, the opportunity to generate addresses is missing. I open the receiving addresses tab — there is no address and no new address button. With release 0.16, everything is in place and normally creates addresses. win10

<img width="863" alt="Screen Shot 2019-05-07 at 8 32 05 pm" src="https://user-images.githubusercontent.com/863730/57299554-75687300-7107-11e9-8018-bdf7193d108a.png">

**Comment by dem10** [comment]
receiving address-no buttons-new address
![Безымянный321](https://user-images.githubusercontent.com/24973894/57300346-52c26400-70df-11e9-8ae1-fad85b8a0eb9.png)
addresses to send
![Безымянный322](https://user-images.githubusercontent.com/24973894/57300595-d0866f80-70df-11e9-9f37-9cafe4da1339.png)

**Comment by MarcoFalke** [comment]
This has been moved to the "receive tab"

![Schermafdruk van 2019-05-07 12-06-58](https://user-images.githubusercontent.com/6399679/57314980-a7a2b200-70c0-11e9-9667-493a91939470.png)

**Comment by promag** [comment]
This was changed in #12721, you can close this.
