### ISSUE TITLE
RewindBlockIndex reads chainActive (via ChainActive()) without holding cs_main

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#15980]
`RewindBlockIndex` reads `chainActive` (via `ChainActive()`) without holding `cs_main`:

https://github.com/bitcoin/bitcoin/blob/b2a6b0216192b6e8428f1a80b47f5178fccb961a/src/validation.cpp#L4314-L4331

(Please note that callers of `RewindBlockIndex` are _not_ allowed to hold `cs_main` since `RewindBlockIndex` indirectly calls `LimitValidationInterfaceQueue`.)

**Comment by promag** [comment]
I think `g_chainstate.RewindBlockIndex(params)` could return `false` if `::ChainActive().Tip() == nullptr`, then L4319 could be removed.
