### ISSUE TITLE
GuessVerificationProgress not locking cs_main as expected

### ISSUE THREAD

**Issue by jasonbcox** [bitcoin/bitcoin#15994]
From the comment in GuessVerificationProgress():
`//! require cs_main if pindex has not been validated yet (because nChainTx might be unset)`

`/interfaces/node.cpp` does not have locks on cs_main for the three calls made to GuessVerificationProgress (see getVerificationProgress, handleNotifyBlockTip, handleNotifyHeaderTip).

I believe there are other calls to GuessVerificationProgress that need similar attention.

**Comment by adamjonas** [comment]
#16426 should close this

**Comment by ariard** [comment]
Yes lock is here now https://github.com/bitcoin/bitcoin/blob/3b1e289248dcda896aaa1c84995ee9c6077601e6/src/interfaces/chain.cpp#L255 ?
