### ISSUE TITLE
Balance and time in client 0.15.1 is not displayed correctly.

### ISSUE THREAD

**Issue by igorivachshenko** [bitcoin/bitcoin#16002]

**Comment by igorivachshenko** [comment]
I use client 0.15.1 and client 0.17.1 on two hard drives, the wallet.dat file is the same.
In client 0.15.1, after full synchronization, the balance is incorrectly displayed (decreased by 2 times)
at the same time, the transaction time is displayed incorrectly, which reduced the balance, half an hour later.
In the transaction description there was a transaction that I did not do,
I do not understand, under one hash of a real transaction, an address appeared,
to which half of the balance was sent. Help figure it out.
Client 0.17.1 is still syncing.

**Comment by pawan17kumar** [comment]
To many email, so pls unsubscribe me

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
