### ISSUE TITLE
Bitcoin resident memory usage

### ISSUE THREAD

**Issue by hito** [bitcoin/bitcoin#16005]
It would be possible for force `bitcoind` to use less resident memory through `cgroups` but I'd imagine it would instantly crash – as all programs really would.

I can see methods to determine average cache size, perhaps new flags for maximum cache size as well.

**Comment by gmaxwell** [comment]
The dbcache parameter is a maximum for the cache, not an average.  Of course, caches aren't the only users of memory-- but all the other limits (IIRC) are maximums as well.
