### ISSUE TITLE
Renamed bitcoind daemonized process

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#16007]
Running 0.18 `bitcoind -daemon` I can see the `bitcoind` process.

On master running `bitcoind -daemon` I found a process named `bitcoin-init`.

This behavior is unexpected.

My system: Linux Mint 19.1 (bionic code base).

**Comment by MarcoFalke** [comment]
I think that is the thread that waits for shutdown?

**Comment by hebasto** [comment]
I cannot reproduce this issue reliably. Closing.

**Comment by jamesob** [comment]
This is a consequence of https://github.com/bitcoin/bitcoin/pull/15849. Is the different process name causing you trouble @hebasto?

**Comment by hebasto** [comment]
@jamesob Thank you for your explanation. No troubles at all, if changes are explained ;)

**Comment by bvrulez** [comment]
So bitcoin-init is the same as bitcoind was? Sorry, i am not an expert, my node is trying to sync on a Raspberry. I think such a rename of a main process is important and should be explained clearly. I could not easily find it in the thread jamesob referred to.
