### ISSUE TITLE
Ban old Nakamoto addresses

### ISSUE THREAD

**Issue by jonnygrant** [bitcoin/bitcoin#16023]
This is not a support request. It's an offer to implement the banning of old addresses
Even Nakamoto's unspent initial account address 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

That would remove adopters worries about old wallets being spent (~ 1 Million old coins etc)

**Comment by fanquake** [comment]
This is not on topic here, nor something would ever be implemented.

**Comment by jonnygrant** [comment]
It's actually pretty simple C++ class, a software feature.
