### ISSUE TITLE
Is it possible to downgrade from 0.18.0 to 0.17.0?

### ISSUE THREAD

**Issue by superbmilkyway** [bitcoin/bitcoin#16032]
I am running a full node on a Ubuntu server.

Yesterday, I upgraded the bitcoin package from 0.17.0 to 0.18.0 using apt-get.
However, I really need the account RPCs.

Is it possible to get back to 0.17.0 without the full sync from the scratch?

**Comment by MarcoFalke** [comment]
I don't think this is possible. Also note that the ppa package is deprecated and won't be provided on Ubuntu Disco and later.

You might want to try the bitcoin-core snap package.

**Comment by sdaftuar** [comment]
To clarify - in general it is possible to downgrade the software just by running the older version and pointing it at the same datadir.

I am not myself familiar with the intricacies of the package-manager supplied version of the software, so I don't know (a) where the datadir would live, or (b) if it is possible to retrieve an older version of the software via apt-get.  But if you can locate the datadir and you can retrieve the software version you'd like to use somehow then you should be able to downgrade without a full synch from scratch.
