### ISSUE TITLE
Remove global whitelist flags and replace them with per-peer flags

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16058]
Global whitelist flags such as `-whitelistrelay` or `-whitelistforcerelay` should be removed in favour of per-peer flags `-whitelistrelay=$IP_ADDRESS` and `-whitelistforcerelay=$IP_ADDRESS`.

Otherwise it is not possible to make fine-grained peer-specific settings about whitelisting and it is either "all on" or "all off" for all whitelisted peers.

**Comment by NicolasDorier** [comment]
Please do not remove global. Not only this is a breaking change, but very often the global is intentional.

**Comment by MarcoFalke** [comment]
It makes debugging specific peer behaviour hard and unintuitive when you can only turn on or off all of the whitelist features for all peers. For example, you might want to whitelist a peer for bloom filters, but not for transaction relay (https://github.com/bitcoin/bitcoin/pull/16176#issuecomment-500310183).

**Comment by NicolasDorier** [comment]
I understand why you want peer specific, but this is not a good argument for removing flags widely used 
 in the wild. `whitebind` and `whitelist` are not counter intuitive and useful as it simplify the configuration.
