### ISSUE TITLE
what's the difference between txid and transaction hash?

### ISSUE THREAD

**Issue by qshuai** [bitcoin/bitcoin#16054]
The `getblocktemplate` RPC API will return `txid` and `hash` fields for every transaction entry.  But they are the same value. So I want to know what's the difference and whether these double fields are necessary or not .

**Comment by jonatack** [comment]
Hi @qshuai, have a look at the output of:

```
bitcoin-cli help getblocktemplate
```
and this link:

https://bitcoin.stackexchange.com/questions/77699/whats-the-difference-between-txid-and-hash-getrawtransaction-bitcoind

**Comment by qshuai** [comment]
@jonatack Get it. Thanks!
