### ISSUE TITLE
how can I get the balance of a label

### ISSUE THREAD

**Issue by peterPengDev** [bitcoin/bitcoin#16067]
how can I get the balance of a label

I am using 0.17, I upgrade to 0.18, the getbalance can no use anymore, please help me, thanks

**Comment by peterPengDev** [comment]
get getreceivedbylabel, can only get received , I want to know like old version getbalance  with account

**Comment by MarcoFalke** [comment]
> I want to know like old version getbalance with account

accounts have been removed. Please refer to the release notes of 0.17.0 and 0.18.0, as well as the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.17.0.md#label-and-account-apis-for-wallet

**Comment by peterPengDev** [comment]
> https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.17.0.md#label-and-account-apis-for-wallet

@MarcoFalke 

thanks for reply, I will check the link first
