### ISSUE TITLE
GUI: Actual graphical tests

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16075]
It is rather straightforward to write unit tests for C++ units or functional tests for the RPC interface. However graphical tests are done purely by hand. If anyone has any ideas to automate them, please leave a comment here.

**Comment by MarcoFalke** [comment]
OpenSuse is using OpenQA, which could be adapted to our use case?

Example: https://openqa.opensuse.org/tests/940238#step/bootloader/3

**Comment by ryanofsky** [comment]
I've written a few automated tests that test the GUI interface. https://github.com/bitcoin/bitcoin/blob/master/src/qt/test/wallettests.cpp sends a transaction with the send coins dialog, looks up the transaction in the transaction view, starts a fee bump, and confirms it. 
https://github.com/bitcoin/bitcoin/blob/master/src/qt/test/apptests.cpp runs a command on the RPC console.

The tests run in the background by default, but you can run them interactively and see the GUI windows using the `test_bitcoin-qt -platform xcb` option.

I'm also planning on writing a new test in #15936 that will test editing and loading the GUI's pruning and proxy settings.

**Comment by MarcoFalke** [comment]
I count the as "C++ unit tests", as they are not testing the `bitcoin-qt` binary.

**Comment by ryanofsky** [comment]
If we need ideas on how to extend the gui tests: https://github.com/bitcoin/bitcoin/issues/16075#issuecomment-494992881, a good one would probably be to focus on testing new, less stable code, like code for dynamically loading wallets. For example wallettests.cpp could be extended to list and load wallets wallets and able to detect regressions like https://github.com/bitcoin/bitcoin/pull/16118#issuecomment-503156728.

**Comment by promag** [comment]
I'll try your suggestion @ryanofsky.

**Comment by ryanofsky** [comment]
Looking a little more closely, wallettests.cpp is not really a great place to test listing wallets since it currently only tests creating individual application dialogs instead of the whole application window. I think [`AppTests::guiTests`](https://github.com/bitcoin/bitcoin/blob/e2182b02b5af13f0de38cf8b08bb81723387c570/src/qt/test/apptests.cpp#L85) would be a better place to add a wallet listing & loading test. It could start by opening the `m_open_wallet_action` menu, similar to how the existing code triggers the [`openRPCConsoleAction`](https://github.com/bitcoin/bitcoin/blob/e2182b02b5af13f0de38cf8b08bb81723387c570/src/qt/test/apptests.cpp#L88-L91) action.

**Comment by jarolrod** [comment]
One option is [Qt Test](https://doc.qt.io/qt-5/qtest-overview.html), there are extensions for testing [GUI Events](https://doc.qt.io/qt-5/qttestlib-tutorial3-example.html)

**Comment by ryanofsky** [comment]
re: https://github.com/bitcoin/bitcoin/issues/16075#issuecomment-759897117

> One option is [Qt Test](https://doc.qt.io/qt-5/qtest-overview.html), there are extensions for testing [GUI Events](https://doc.qt.io/qt-5/qttestlib-tutorial3-example.html)

This is actually what apptests.cpp and wallettests.cpp are based on and currently doing (even using the same lineedit trick in the example)

**Comment by jarolrod** [comment]
[sikulix](https://sikulix-2014.readthedocs.io/en/latest/index.html) is a FOSS tool for automated Graphical testing. It uses Tesseract OCR and OpenCV to verify that the GUI works as intended. Using this tool would allow us to write automated graphical tests in python. Additionally we can hook this with [robotframework](https://robotframework.org) and develop some BDD gherkin files for which will allow us to test user interaction flows throughout the GUI.
