### ISSUE TITLE
gui: app crashed while rescanning  Mac

### ISSUE THREAD

**Issue by ybaidiuk** [bitcoin/bitcoin#16087]
While rescanning  wenn i click File>open wallet  in time wenn mouse cursor touch "open wallet" item app just immediately crashed.
V0.18.0

**Comment by promag** [comment]
How was the rescan triggered?

**Comment by ybaidiuk** [comment]
I just copied full node from my brother. And start the app( with replaced wallet file

**Comment by promag** [comment]
@ybaidiuk thanks for the report, fix already submitted ☝️

**Comment by fanquake** [comment]
This is not limited to happening while re scanning, it looks like any File-> * Wallet related actions during start up will cause the crash. Stack trace here (attempting to open a wallet) for reference:

```shell
Process 86914 launched: '/Users/michael/github/bitcoin/src/qt/bitcoin-qt' (x86_64)
2019-05-29 09:53:43.153301-0400 bitcoin-qt[86914:933025] MessageTracer: Falling back to default whitelist
Process 86914 stopped
* thread #1, name = 'bitcoin-main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x38)
    frame #0: 0x0000000101c9db8e QtCore`QMutex::lock() + 14
QtCore`QMutex::lock:
->  0x101c9db8e <+14>: lock   
    0x101c9db8f <+15>: cmpxchgq %rcx, (%rdi)
    0x101c9db93 <+19>: je     0x101c9dba8               ; <+40>
    0x101c9db95 <+21>: movq   %rax, %rbx
Target 0: (bitcoin-qt) stopped.
```

**Comment by MarcoFalke** [comment]
The "File->" menu shouldn't even be there on startup, no?

**Comment by fanquake** [comment]
@MarcoFalke I think the approach of greying out the menus, like in #16118 should suffice?
