### ISSUE TITLE
State of the Repo Report, May 2019

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#16085]
# State of the Repo Report, May 2019

## Introduction

For all fans of statistics – enjoy! 🤓

The "median open pull request" adds 51&nbsp;lines, removes 17&nbsp;lines and touches 4&nbsp;files.

The total set of open pull requests adds 55&nbsp;802&nbsp;lines, removes 20&nbsp;371&nbsp;lines and touches 1&nbsp;969&nbsp;distinct files.

The repo contains 487&nbsp;553 lines of text and 1&nbsp;729 files.

20&nbsp;405 commits have been made of which 3&nbsp;838 are merge commits.

There are currently 295 open pull requests from in total 82 contributors.

If all open pull requests were merged the project line count would grow by roughly 7 percent.

Previous edition: [State of the Repo, April 2019](https://github.com/bitcoin/bitcoin/issues/15915)

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines added | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 10&nbsp;417&nbsp;(19%) | -1&nbsp;787 | 8&nbsp;630 | 137 | 10&nbsp;(3%) |
| 2 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 7&nbsp;016&nbsp;(13%) | -1&nbsp;069 | 5&nbsp;947 | 91 | 18&nbsp;(6%) |
| 3 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 3&nbsp;731&nbsp;(7%) | -2&nbsp;919 | 812 | 99 | 9&nbsp;(3%) |
| 4 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 3&nbsp;467&nbsp;(6%) | -484 | 2&nbsp;983 | 45 | 13&nbsp;(4%) |
| 5 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 3&nbsp;466&nbsp;(6%) | -2&nbsp;169 | 1&nbsp;297 | 86 | 15&nbsp;(5%) |
| 6 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 3&nbsp;257&nbsp;(6%) | -416 | 2&nbsp;841 | 96 | 25&nbsp;(8%) |
| 7 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 2&nbsp;970&nbsp;(5%) | -481 | 2&nbsp;489 | 50 | 8&nbsp;(3%) |
| 8 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 2&nbsp;893&nbsp;(5%) | -1&nbsp;109 | 1&nbsp;784 | 40 | 2&nbsp;(1%) |
| 9 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 1&nbsp;756&nbsp;(3%) | -1&nbsp;664 | 92 | 16 | 7&nbsp;(2%) |
| 10 | [MishraShivendra](https://github.com/bitcoin/bitcoin/pulls/MishraShivendra) | 1&nbsp;467&nbsp;(3%) | -41 | 1&nbsp;426 | 12 | 1&nbsp;(0%) |
| 11 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 1&nbsp;137&nbsp;(2%) | -839 | 298 | 95 | 21&nbsp;(7%) |
| 12 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 987&nbsp;(2%) | -195 | 792 | 37 | 8&nbsp;(3%) |
| 13 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 957&nbsp;(2%) | -27 | 930 | 18 | 1&nbsp;(0%) |
| 14 | [sipsorcery](https://github.com/bitcoin/bitcoin/pulls/sipsorcery) | 940&nbsp;(2%) | -2&nbsp;362 | -1&nbsp;422 | 36 | 2&nbsp;(1%) |
| 15 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 892&nbsp;(2%) | -129 | 763 | 31 | 6&nbsp;(2%) |
| 16 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 828&nbsp;(1%) | -101 | 727 | 30 | 2&nbsp;(1%) |
| 17 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 824&nbsp;(1%) | -831 | -7 | 61 | 4&nbsp;(1%) |
| 18 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 790&nbsp;(1%) | -436 | 354 | 52 | 24&nbsp;(8%) |
| 19 | [sdaftuar](https://github.com/bitcoin/bitcoin/pulls/sdaftuar) | 657&nbsp;(1%) | -398 | 259 | 16 | 5&nbsp;(2%) |
| 20 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 597&nbsp;(1%) | -78 | 519 | 12 | 4&nbsp;(1%) |
| 21 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 478&nbsp;(1%) | -381 | 97 | 37 | 10&nbsp;(3%) |
| 22 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 440&nbsp;(1%) | -47 | 393 | 7 | 3&nbsp;(1%) |
| 23 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 417&nbsp;(1%) | -9 | 408 | 5 | 1&nbsp;(0%) |
| 24 | [TheBlueMatt](https://github.com/bitcoin/bitcoin/pulls/TheBlueMatt) | 347&nbsp;(1%) | -57 | 290 | 19 | 3&nbsp;(1%) |
| 25 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 341&nbsp;(1%) | -319 | 22 | 35 | 1&nbsp;(0%) |
| 26 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 328&nbsp;(1%) | -158 | 170 | 13 | 3&nbsp;(1%) |
| 27 | [251Labs](https://github.com/bitcoin/bitcoin/pulls/251Labs) | 323&nbsp;(1%) | -96 | 227 | 23 | 2&nbsp;(1%) |
| 28 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 287&nbsp;(1%) | -82 | 205 | 7 | 2&nbsp;(1%) |
| 29 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 284&nbsp;(1%) | -144 | 140 | 47 | 9&nbsp;(3%) |
| 30 | [theuni](https://github.com/bitcoin/bitcoin/pulls/theuni) | 271&nbsp;(0%) | -33 | 238 | 14 | 1&nbsp;(0%) |
| 31 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 261&nbsp;(0%) | -43 | 218 | 3 | 1&nbsp;(0%) |
| 32 | [ariard](https://github.com/bitcoin/bitcoin/pulls/ariard) | 231&nbsp;(0%) | -248 | -17 | 12 | 2&nbsp;(1%) |
| 33 | [jonatack](https://github.com/bitcoin/bitcoin/pulls/jonatack) | 212&nbsp;(0%) | -81 | 131 | 11 | 3&nbsp;(1%) |
| 34 | [lionello](https://github.com/bitcoin/bitcoin/pulls/lionello) | 191&nbsp;(0%) | -15 | 176 | 5 | 1&nbsp;(0%) |
| 35 | [benthecarman](https://github.com/bitcoin/bitcoin/pulls/benthecarman) | 182&nbsp;(0%) | -21 | 161 | 13 | 4&nbsp;(1%) |
| 36 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 173&nbsp;(0%) | -87 | 86 | 7 | 2&nbsp;(1%) |
| 37 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 158&nbsp;(0%) | -86 | 72 | 3 | 2&nbsp;(1%) |
| 38 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 135&nbsp;(0%) | -101 | 34 | 4 | 1&nbsp;(0%) |
| 39 | [giulio92](https://github.com/bitcoin/bitcoin/pulls/giulio92) | 131&nbsp;(0%) | -133 | -2 | 1 | 1&nbsp;(0%) |
| 40 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 125&nbsp;(0%) | -57 | 68 | 13 | 5&nbsp;(2%) |
| 41 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 118&nbsp;(0%) | -32 | 86 | 11 | 2&nbsp;(1%) |
| 42 | [meshcollider](https://github.com/bitcoin/bitcoin/pulls/meshcollider) | 92&nbsp;(0%) | -32 | 60 | 6 | 2&nbsp;(1%) |
| 43 | [MapleLaker](https://github.com/bitcoin/bitcoin/pulls/MapleLaker) | 89&nbsp;(0%) | -1 | 88 | 1 | 1&nbsp;(0%) |
| 44 | [conscott](https://github.com/bitcoin/bitcoin/pulls/conscott) | 87&nbsp;(0%) | -61 | 26 | 3 | 1&nbsp;(0%) |
| 45 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 87&nbsp;(0%) | -6 | 81 | 6 | 2&nbsp;(1%) |
| 46 | [Bushstar](https://github.com/bitcoin/bitcoin/pulls/Bushstar) | 83&nbsp;(0%) | -65 | 18 | 10 | 3&nbsp;(1%) |
| 47 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 83&nbsp;(0%) | -9 | 74 | 5 | 1&nbsp;(0%) |
| 48 | [IntegralTeam](https://github.com/bitcoin/bitcoin/pulls/IntegralTeam) | 79&nbsp;(0%) | -3 | 76 | 3 | 1&nbsp;(0%) |
| 49 | [darosior](https://github.com/bitcoin/bitcoin/pulls/darosior) | 78&nbsp;(0%) | -17 | 61 | 6 | 4&nbsp;(1%) |
| 50 | [greenaddress](https://github.com/bitcoin/bitcoin/pulls/greenaddress) | 78&nbsp;(0%) | -31 | 47 | 10 | 1&nbsp;(0%) |
| 51 | [ch4ot1c](https://github.com/bitcoin/bitcoin/pulls/ch4ot1c) | 76&nbsp;(0%) | -87 | -11 | 11 | 1&nbsp;(0%) |
| 52 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 42&nbsp;(0%) | -15 | 27 | 15 | 1&nbsp;(0%) |
| 53 | [ken2812221](https://github.com/bitcoin/bitcoin/pulls/ken2812221) | 42&nbsp;(0%) | -10 | 32 | 6 | 1&nbsp;(0%) |
| 54 | [tryphe](https://github.com/bitcoin/bitcoin/pulls/tryphe) | 33&nbsp;(0%) | -38 | -5 | 3 | 2&nbsp;(1%) |
| 55 | [kodslav](https://github.com/bitcoin/bitcoin/pulls/kodslav) | 31&nbsp;(0%) | -5 | 26 | 1 | 1&nbsp;(0%) |
| 56 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 30&nbsp;(0%) | -25 | 5 | 4 | 1&nbsp;(0%) |
| 57 | [cisba](https://github.com/bitcoin/bitcoin/pulls/cisba) | 29&nbsp;(0%) | -13 | 16 | 9 | 1&nbsp;(0%) |
| 58 | [LeandroRocha84](https://github.com/bitcoin/bitcoin/pulls/LeandroRocha84) | 24&nbsp;(0%) | -14 | 10 | 4 | 1&nbsp;(0%) |
| 59 | [lucayepa](https://github.com/bitcoin/bitcoin/pulls/lucayepa) | 24&nbsp;(0%) | -14 | 10 | 1 | 1&nbsp;(0%) |
| 60 | [pstratem](https://github.com/bitcoin/bitcoin/pulls/pstratem) | 24&nbsp;(0%) | -46 | -22 | 1 | 1&nbsp;(0%) |
| 61 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2 | 20 | 2 | 1&nbsp;(0%) |
| 62 | [tecnovert](https://github.com/bitcoin/bitcoin/pulls/tecnovert) | 22&nbsp;(0%) | -21 | 1 | 3 | 1&nbsp;(0%) |
| 63 | [marcoagner](https://github.com/bitcoin/bitcoin/pulls/marcoagner) | 21&nbsp;(0%) | -2 | 19 | 1 | 1&nbsp;(0%) |
| 64 | [mrwhythat](https://github.com/bitcoin/bitcoin/pulls/mrwhythat) | 20&nbsp;(0%) | -3 | 17 | 3 | 1&nbsp;(0%) |
| 65 | [stevenroose](https://github.com/bitcoin/bitcoin/pulls/stevenroose) | 14&nbsp;(0%) | -12 | 2 | 1 | 1&nbsp;(0%) |
| 66 | [torkelrogstad](https://github.com/bitcoin/bitcoin/pulls/torkelrogstad) | 13&nbsp;(0%) | -1 | 12 | 1 | 1&nbsp;(0%) |
| 67 | [GreatSock](https://github.com/bitcoin/bitcoin/pulls/GreatSock) | 11&nbsp;(0%) | -6 | 5 | 3 | 1&nbsp;(0%) |
| 68 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 11&nbsp;(0%) | -8 | 3 | 2 | 2&nbsp;(1%) |
| 69 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 11&nbsp;(0%) | -8 | 3 | 4 | 2&nbsp;(1%) |
| 70 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -3 | 8 | 1 | 1&nbsp;(0%) |
| 71 | [amitiuttarwar](https://github.com/bitcoin/bitcoin/pulls/amitiuttarwar) | 9&nbsp;(0%) | -8 | 1 | 3 | 1&nbsp;(0%) |
| 72 | [shannon1916](https://github.com/bitcoin/bitcoin/pulls/shannon1916) | 9&nbsp;(0%) | -2 | 7 | 1 | 1&nbsp;(0%) |
| 73 | [kazcw](https://github.com/bitcoin/bitcoin/pulls/kazcw) | 7&nbsp;(0%) | -9 | -2 | 1 | 1&nbsp;(0%) |
| 74 | [ps1dr3x](https://github.com/bitcoin/bitcoin/pulls/ps1dr3x) | 7&nbsp;(0%) | -1 | 6 | 1 | 1&nbsp;(0%) |
| 75 | [sp4ke](https://github.com/bitcoin/bitcoin/pulls/sp4ke) | 5&nbsp;(0%) | -3 | 2 | 1 | 1&nbsp;(0%) |
| 76 | [d3spwn](https://github.com/bitcoin/bitcoin/pulls/d3spwn) | 4&nbsp;(0%) | -2 | 2 | 2 | 1&nbsp;(0%) |
| 77 | [kostyantyn](https://github.com/bitcoin/bitcoin/pulls/kostyantyn) | 4&nbsp;(0%) | -7 | -3 | 3 | 1&nbsp;(0%) |
| 78 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 3&nbsp;(0%) | -4 | -1 | 1 | 1&nbsp;(0%) |
| 79 | [bpay](https://github.com/bitcoin/bitcoin/pulls/bpay) | 2&nbsp;(0%) | -2 | 0 | 1 | 1&nbsp;(0%) |
| 80 | [zenosage](https://github.com/bitcoin/bitcoin/pulls/zenosage) | 2&nbsp;(0%) | -3 | -1 | 2 | 1&nbsp;(0%) |
| 81 | [rojarsmith](https://github.com/bitcoin/bitcoin/pulls/rojarsmith) | 1&nbsp;(0%) | -1 | 0 | 1 | 1&nbsp;(0%) |
| 82 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6 | -6 | 2 | 1&nbsp;(0%) |

**Comment by fanquake** [comment]
Thanks.
