### ISSUE TITLE
LogPrintf() fails due to premature call before InitLogging()

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#16098]
These pieces of code:
https://github.com/bitcoin/bitcoin/blob/8ab4f282c06d67074b872dbda0be37636fdd5186/src/util/system.cpp#L302
and
https://github.com/bitcoin/bitcoin/blob/8ab4f282c06d67074b872dbda0be37636fdd5186/src/util/system.cpp#L864
do not work as expected because they are called before the `InitLogging()` call.

**Comment by MarcoFalke** [comment]
Rebased the fix for this, which was written last year by @ajtowns
