### ISSUE TITLE
SubtractFeeFromAmount Inconsistency

### ISSUE THREAD

**Issue by VoxR4710** [bitcoin/bitcoin#16100]
Running bitcoind and bitcoin-cli with JSON RPC, 0.18.0 on testnet, having a nightmare trying to understand the inconsistency of this parameter's behaviour.

It works fine every time, until the remaining balance left in wallet will be lower than an undetermined amount. At that point, it decides to use all of the remainder as extra fees for the supposedly fee inclusive transaction, thereby failing to perform the subtractfeefromamount functionality.

Examples of my test results:

Balance 10000, sent 1000 - Balance 9000

Balance 3000, sent 1600 - Balance 1400

Balance 1400, sent 1300 - Balance 0

Balance 8700, sent 8400 - Balance 0

Balance 10000, sent 9500 - Balance 0

The format and values of all other parameters and code do not change between tests, only the amount for sending. I do not specify any parameters beyond subtractfee

There definitely seems to be some mechanism to use all the remainder for fees when the remainder is under a certain amount, but this is terrible and unpredictable, why does it happen and how can it be prevented?
Should be reproduceable!

Thanks

**Comment by VoxR4710** [comment]
To ensure it wasn't to do with json-rpc or my code:
bitcoin-cli getbalance
0.00009000
bitcoin-cli sendtoaddress n3qpExEQbF8orkqY7cpmJu6iUhNVHHcnk3 0.00008500 "" "" true
75800f6032ecf46f49b229a81d5ee17c9f5f49ffe1f0863ca148c7e3e42956ec
bitcoin-cli getbalance
0.00000000

What gives ?

**Comment by MarcoFalke** [comment]
Is `75800f6032ecf46f49b229a81d5ee17c9f5f49ffe1f0863ca148c7e3e42956ec` in the mempool?

**Comment by VoxR4710** [comment]
After a brief googling, I'm still not sure how to tell. Can you tell me? You can add my discord if it's easier. VoxR#1801

I Can tell you I've left it overnight after a bug transaction to make sure there was nothing about confirmations. That TXID is real by the way you can look up the transaction.

**Comment by MarcoFalke** [comment]
The mempool can only hold a chain of unconfirmed transactions that is of length 25, when you send more than than in a short period of time (i.e. before the txs get confirmed in a block), the mempool will reject them and the wallet is unable to determine the balance.

**Comment by mzumsande** [comment]
I'm new too, but this sounds as if in some of the tests the dust limit is reached, i.e. for p2pkh if the outstanding balance would be less than 546 satoshi, no change output is generated and the outstanding amount is instead added to the miner fee.

**Comment by MarcoFalke** [comment]
> Balance 10000, sent 1000 - Balance 9000

Is that in BTC or satoshis?

**Comment by mzumsande** [comment]
according to the rpc getbalance output in the second post it's satoshis.

**Comment by MarcoFalke** [comment]
Ok, closing under the assumption that the amounts are satoshis and that change smaller than the dust is added to the fee.

This is working as designed.

**Comment by promag** [comment]
Also looks ok to me. Eventually there's no point in creating a change output.

**Comment by VoxR4710** [comment]
Okay, I don't see the use of that and it's unhelpful to me but I'll find a way around it, I'm just glad to know what's going on at this stage!! I'll search for more info on this dust limit because it sounds exactly right. Thankyou and sorry for time waste (though I searched for days and never saw about dust limit )

**Comment by VoxR4710** [comment]
That actually was only part of the problem! I still have some issue with SubtractFeeFromAmount. It makes no sense at all, though. Stay with me on this for a moment , please:

Balance: 8000 satoshi
Received: 0.00118410
Balance: 126410
Sent: 0.00118292
Balance: 8000
Sent: 0.00001000
Balance: 7000
Received: 118410
Balance: 125410
Then to make sure once again that it was nothing about PHP or jsonRPC, I use bitcoin-cli directly:
bitcoin-cli sendtoaddress n3qpExEQbF8orkqY7cpmJu6iUhNVHHcnk3 0.00118292 "" "" true
50458050f042460ea7199a0d0327edbae153e4e0083cc5862ab64322b31819e9
Balance: 7000 (!)

How is it possible? Sometimes it works, sometimes it doesn't work? For a long time I thought I had written the parameters wrong for json-RPC, but unless the above command is also wrong, it's not me?
Please, if you can help in any way , I am literally a starving developer taking a shot on btc app :(

**Comment by MarcoFalke** [comment]
When Bitcoin Core tells you the Balance, it really means the sum of the values of all coins in your wallet.
When Bitcoin Core creates a transaction, it really goes through all coins in your wallet and selects a subset of them to use as inputs for the transaction.

Assume you have a balance of 0.00125410. This could be two coins (0.00007000 + 0.00118410). So sending an amount of 0.00118292 must select a subset that includes at least the coin with value 0.00118410. If it only includes that coin, there would be a change of less than the dust limit. Later on, instead of creating an expensive to spend change output, that dust is added to the tx fee.

**Comment by VoxR4710** [comment]
O_O i have much to learn still, clearly
Thank you so much for the response and sorry for making a mess in your board!
