### ISSUE TITLE
Coin Selector UI is Showing The OK Button on the Left Side.

### ISSUE THREAD

**Issue by igorgue** [bitcoin/bitcoin#16101]
BitcoinQT's Input selector is showing the `OK` button on the left side instead of the right side.

All the buttons in the app show on the right side, so they should be there, especially the `OK` button.

Ok button on the right.

Ok button on the left.
![image](https://user-images.githubusercontent.com/7014/58424329-2c03a780-8065-11e9-8515-3aafdf4a3923.png)

![image](https://user-images.githubusercontent.com/7014/58424402-4c336680-8065-11e9-9f0a-259dd5b0a2ae.png)

I'm using `0.18.0`. On a x86_64 GNU/Linux Ubuntu 19.04 Gnome 3.32.1.

**Comment by fanquake** [comment]
@igorgue There is a fix for this in #16113 if you'd like to test it.

**Comment by igorgue** [comment]
Thanks I’ll close this then.

**Comment by igorgue** [comment]
Oh it was for this issue. Apologize I’ll test.
