### ISSUE TITLE
gui: add tip for macOS users to disable auto suspend when display is off while plugged in

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#16125]
We've solved the App Nap problem in #12783 which caused Bitcoin QT to dramatically slow down syncing if it's in the background. This affect all (modern) macOS users.

There's another problem however, which is that by default MacBooks suspend when the display is off, even when plugged into a power socket. This causes IBD to pause, which is annoying if you're trying to sync at night.

https://support.apple.com/en-qa/HT202824

<img width="664" alt="Schermafbeelding 2019-05-30 om 13 00 49" src="https://user-images.githubusercontent.com/10217/58628856-14cdef80-82db-11e9-9896-44d251183f87.png">

Suggest solution: add a (macOS-only?) notice to the synchronization modal suggesting that laptop users turn on "Prevent computer from sleeping automatically when the display is off". It's not necessary to change the hard disk suspension default.

I don't know if Apple exposes an API to detect this setting. I'm generally not in favor of OS specific modifications, but initial block download is a painful enough issue that small hints like this really help.

**Comment by promag** [comment]
@Sjors it does and looks quite simple https://stackoverflow.com/a/8461182. I guess in windows it could also prevent sleep?

**Comment by luke-jr** [comment]
I could see this leading to laptops overheating in laptop bags, while the user assumes they will be asleep. Need some extra care.

**Comment by Sjors** [comment]
@luke-jr been there, done that :-)  But this macOS setting is exclusively for laptops that are plugged in (Power Adapter). I also suspect, but haven't tested, that when you close the lid, it will sleep.

**Comment by jonasschnelli** [comment]
Would it make sense to implement the `kIOPMAssertionTypeNoIdleSleep` flag?
Ideally, users can change that via the Bitcoin Core settings (ideally enabled by default).

**Comment by fanquake** [comment]
> Would it make sense to implement the kIOPMAssertionTypeNoIdleSleep flag?

There's some discussion on this in #16145.

**Comment by fanquake** [comment]
I think us adding code for macOS specific power-management is very unlikely. If we want to add a macOS specific tip/warning to the GUI, that can now be discussed in the [GUI repo](https://github.com/bitcoin-core/gui/). Can you port this issue over there is you'd like to follow up.
