### ISSUE TITLE
Sign a raw transaction to pay to Multisig address and get failed, does someone konw my problem?

### ISSUE THREAD

**Issue by FutureOfAI** [bitcoin/bitcoin#16126]
Recently I found my HD wallet can't pay to multisig address (start with '3'), it can pay to address start with '1', the raw transaction is: '0100000001b0e1a9cc83fbe8918a1cf20e0c72cf2fe3af252f228a3a0223943c2732f69bd8010000006b483045022100cf98600ba4f4d7bc748e36e4bb7eed48a26d7eab45bb813f65781ca7921a163702204f857a25574ba50c54373dc9fcdbba51ac1653b1007832b8314a7ccc2224d927012102534fd869124dff1cc99c430b97a5b6817b1f8343ce1e1de3ff71d4a3fc6c1592ffffffff02307500000000000017a9146cf00a2686081c15e931f7413b0f07561388c9c18764000000000000001976a914e093b1e8185d6b8136a80c8ab02e2f0bbfaf15c288ac00000000' 

Broadcast result: ”Error validating transaction: Transaction with hash c79024c644855f09c9799020dcbf669da6686d9a4526601fef2bbb6da43c895f already exists..“
, after I check my balance, the transaction failed, and The fee rate of this transaction is 50 satoshi/byte, so what's the problem? does some one know this? appreciate.

**Comment by MarcoFalke** [comment]
What software are you using? That doesn't look like Bitcoin Core.

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by FutureOfAI** [comment]
I follow the raw transaction rules then I build and sign this raw transaction myself, I have success in funding to address starts with '1' but failed funding to multisig address start with '3' , the only thing I change is output scriptpubkey from "op_dup op_hash160 <pubkey hash> op_equalverify op_checksig" to "op_hash160 <redeem scripthash> op_equal", am I miss some vital stepm
