### ISSUE TITLE
Why does Bitcoin not use `unittest` framework instead of custom framework?

### ISSUE THREAD

**Issue by Dentrax** [bitcoin/bitcoin#16121]
As we saw, Bitcoin is using a [test_framework](https://github.com/bitcoin/bitcoin/tree/master/test/functional/test_framework) of its own to testing thousands of cases. All the script files [here](https://github.com/bitcoin/bitcoin/tree/master/test/functional) are using `test_framework`.

The main question is: Why instead of use [unittest](https://docs.python.org/3/library/unittest.html), a special custom test system was written from the beginning? Is there a goal or plan of migrating whole testing system to the `unittest`?

Thank you, just wondering... :)

**Comment by jnewbery** [comment]
The tests in `/tests/functional` are integration tests of the built C++ bitcoind, not python unit tests.

**Comment by MarcoFalke** [comment]
While it could probably be translated to use unittest, a lot of the complexity of the test framwork is how to speak with bitcoind in many ways (startup/shutdown, rpc, p2p, create datadirs). So except for naming differences of some methods, it wouldn't make a huge difference to migrate, I believe. So probably not worth the effort.
