### ISSUE TITLE
test_bitcoin failure on arm-linux-gnueabihf

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#16132]
When running `0.18.0` `test_bitcoin` on debian stretch on `arm-linux-gnueabihf`, the following error message is repeated 32 times (printed to `stdout` so we know it's a test failure):

```
test/crypto_tests.cpp(561): error: in "crypto_tests/sha256d64": check memcmp(out1, out2, 32 * i) == 0 has failed
```

**Comment by fanquake** [comment]
Duplicate of #14580 ?

**Comment by dongcarl** [comment]
True!
