### ISSUE TITLE
GUI: Build unreproducible in the scenarios tested by the Debian Reproducible Builds project

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#16137]
Debian is >90% reproducible but unfortunately Bitcoin Core is one of the remaining unreproducible projects:

* https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/bitcoin.html

It would be nice if we were reproducible also in the scenarios tested by the Debian Reproducible Builds project.

**Comment by MarcoFalke** [comment]
Huh, I wasn't even aware that there is a Debian package

**Comment by fanquake** [comment]
I've emailed upstream about this. Looking at the diff I think the issue is not exporting `QT_RCC_SOURCE_DATE_OVERRIDE`=`1` at build time.

**Comment by practicalswift** [comment]
@fanquake Excellent! Thanks! Do you have a link to a mailing list archive where the thread can be followed?

**Comment by fanquake** [comment]
I emailed the team directly. If / when they reply I can post the response here.

**Comment by practicalswift** [comment]
@fanquake No response? :)

**Comment by fanquake** [comment]
No, I haven't seen anything. Can follow up again.

**Comment by practicalswift** [comment]
Closing due to lack of progress/interest :)

**Comment by practicalswift** [comment]
Great news: [Bitcoin Core is now flagged as a reproducible package  in Debian, openSUSE and ArchLinux](https://ismypackagereproducibleyet.org/?pkg=bitcoin&query=query) :)

Thanks @fanquake for making this happen (I guess `QT_RCC_SOURCE_DATE_OVERRIDE` was missing?).
