### ISSUE TITLE
build: packages that may be prunable from depends 

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16150]
Opening so that the we don't loose this discussion from #16041, as this needs following up.

cc @dongcarl @theuni
 
> In this PR we identify 4 secondary deps that should be built statically:
> 
> * dbus
> * expat
> * libXext
> * xtrans
> 
> However, only expat required being built `--with-pic` for depends builds to succeed, which is rather odd. Therefore, the rest of the deps must not be linked in, or are headers-only.
> 
> Results of my investigation (please verify these as I might be completely wrong):
> ### libXext
> 
> The only package that we declare as depending on libXext is qt, and it doesn't actually... Tested by removing the package definition and references to it, everything seems to compile fine.
> ### xtrans
> 
> It seems that xtrans is just code+headers and not a library that needs to be linked in. We can verify this by looking at the build outputs.
> 
> Its configure is very confused as to why we supply it with `--disable-{static,shared}`. It is, however, required as a build-time dependency for libX11.
> ### dbus
> 
> The only reference to dbus is in the configure options for qt: `-dbus-runtime`. Which indicates to qt to dynamically open libdbus-1 at runtime (with dlopen?). I believe this means that we don't actually use the dbus we build. (This one I'm the least sure about)

**Comment by dongcarl** [comment]
Started xtrans fixes here: https://github.com/bitcoin/bitcoin/pull/16183

**Comment by fanquake** [comment]
Opened #16352 in regards to pruning `D-Bus` from depends.

**Comment by dongcarl** [comment]
Here's something I found... There's now an `xorgproto` package, which, along with some qt XLib disabling I've been working on, can allow us to eliminate `xproto`, `xextproto`, `xtrans`, and `libX11`.

See the "provides" and "package contents" sections here: https://www.archlinux.org/packages/extra/any/xorgproto/

**Comment by dongcarl** [comment]
Some more digging:

We are unable to eliminate `libX11` because the `qt` requires `libX11` headers (e.g. `cursorfont.h` and `Xlib.h`) which are not provided by `xorgproto`. However, because we only need `libX11`'s headers, we can overwrite `libX11`'s `configure` file to a minimal one that only transforms `libX11`'s `include/Makefile.in` to `include/Makefile`. This allows us to eliminate all of `libX11`'s dependencies, as we have no use for them other than for the `configure` to pass.

**Comment by fanquake** [comment]
Going to close this now that #16408 has been merged. `d-bus`, `libXext` and `xtrans` have all been pruned.
