### ISSUE TITLE
User-facing string in GUI from untrusted source

### ISSUE THREAD

**Issue by cculianu** [bitcoin/bitcoin#16154]
See here: https://github.com/bitcoin/bitcoin/blob/758c6d784da0f191c408fda97b3071dd7e1fe8a0/src/qt/paymentserver.cpp#L718-L726

This string ends up in the wallet UI on a failed response form the payment request server.

IN light of recent phishing attempts on eg the Electrum network, it's probably not the best idea to show this error message in the GUI.

Granted this is a corner case and the attack surface is exceedingly small -- it still probably should be handled.

Best regards,

-Calin

**Comment by bddap** [comment]
Is is it useful to check `reply->errorString()` against a whitelist of valid error messages? Should the message simply not be displayed?

**Comment by fanquake** [comment]
This code no longer exists.
