### ISSUE TITLE
Bitcoin testnet rpc is binding to localhost 

### ISSUE THREAD

**Issue by emonazad** [bitcoin/bitcoin#16179]
Hello , Thanks for the efforts here . currently, i have installed couple of time and at different server bitcoind and i have even pull up github at server and compiled it still bitcoind rpc is binding to localhost even after i have added rpcallowip=0.0.0.0/0

i saw 

root@arraymachinetest-desktop:~/.bitcoin# sudo netstat --ip -lpa|grep bitcoin
tcp        0      0 localhost:29000         0.0.0.0:*               LISTEN      20921/bitcoind      
tcp        0      0 localhost:18332         0.0.0.0:*               LISTEN      20921/bitcoind      
tcp        0      0 0.0.0.0:18333           0.0.0.0:*               LISTEN      20921/bitcoind    

i used this config file :

server=1
testnet=1
rpcallowip=0.0.0.0/0
port=18332
rpcport=18333
rpcuser=foo
rpcpassword=bar

it was working for me before . any solution for this ?

**Comment by emilengler** [comment]
Try `rpcbind=YOURIP:YOURPORT`

**Comment by fanquake** [comment]
@emonazad has your issue been solved? Please close this if so.

You might also want to read the section on configuration option changes in the release notes for `v0.18.0`, assuming that is the version you are running: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#configuration-option-changes

**Comment by chanhosuh** [comment]
To be honest, the release notes were a bit confusing.  How I would put it is this, before if you put
`rpcallowip=0.0.0.0/0`, the value of `rpcbind` didn't need to be set as it defaulted to all interfaces.  

Now that is no longer the case.  So you need to do:

```
rpcallowip=0.0.0.0/0
rpcbind=127.0.0.1
rpcbind=<the IP you are trying to reach with RPC call>
rpcbind=<another such IP or local DNS name>
```

Hope this helps somebody...
