### ISSUE TITLE
getnewaddress always returns same type 

### ISSUE THREAD

**Issue by pfergi42** [bitcoin/bitcoin#16178]
When I run "getnewaddress legacy" I expect to get an address starting with a "1".
When I run "getnewaddress p2sh-segwit" I expect to get an address starting with a "3".
When I run "getnewaddress bech32" I expect to get an address starting with "bc1".

I always get an address starting a "3". Another user I know always gets an address starting with a "1".

![getnewaddress-screenshot](https://user-images.githubusercontent.com/4021240/59165441-7444b000-8ad0-11e9-892d-6e6ccc66a6c9.png)

This is reproducible both from command line running bitcoind, and also bitcoin-Qt. From bitcoind, I type:

bitcoin-cli getnewaddress legacy

Or from bitcoin-Qt I issue the commands from the debug window console, as shown in the screenshot above.
 

Running version 0.18 downloaded from https://bitcoin.org/en/download

I'm running on macOS Mojave Version 10.14.5, and I always get an address starting with "3".
The other user I know runs Ubuntu, and always gets an address starting with a "1".

N//a

**Comment by achow101** [comment]
Your are missing the label argument that goes between the command name and the type parameter. Bitcoin Core is interpreting your type parameter as the label name. Instead try `getnewaddress "" legacy`

**Comment by pfergi42** [comment]
@achow101 That worked! Thank you so much!

**Comment by pfergi42** [comment]
The documentation says that label should be optional, no?

https://bitcoincore.org/en/doc/0.18.0/rpc/wallet/getnewaddress/

**Comment by pfergi42** [comment]
Actually this problem is still not resolved. It could be something to do with the config file. If anyone else has this issue please comment.

**Comment by sipa** [comment]
Can you explain how it is not resolved? Everything looks correct in the screenshot above.

**Comment by MarcoFalke** [comment]
You need to type `getnewaddress label_foo bech32`

**Comment by pfergi42** [comment]
The screenshot I originally posted was from my tests on another box on a OSX. The problem we are still experiencing is on a Linux machine. 

I've posted a more clear description of the problem as it appears on the Linux machine here:
https://bitcoin.stackexchange.com/questions/93868/getnewaddress-wont-generate-bech32-or-p2sh-segwit-addresses

**Comment by pfergi42** [comment]
Thanks to @sipa we resolved this issue by upgrading our wallet.dat and then running getnewaddress a bunch of times. Issue resolved.
