### ISSUE TITLE
expose impact types of the transaction with mempool via ZeroMQ for transactions in the mempool

### ISSUE THREAD

**Issue by Tronglx** [bitcoin/bitcoin#16180]
Currently, when having the status change with a transaction in the mempool, bitcoin core will expose informations of the transaction via ZeroMQ.
https://github.com/bitcoin/bitcoin/blob/master/src/zmq/zmqnotificationinterface.cpp#L160-L195
Having 3 impact types of the transaction with mempool:
- added.
- blockConnected.
- blockDisconnected.

Informations about impact type is very important with the client that subscribes Zmq channels.
In some case, we only care about the new transactions that be accepted to mempool.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
