### ISSUE TITLE
How to compile and debug the latest version of bitcoin source code with Visual Studio 2015 or Visual Studio 2013

### ISSUE THREAD

**Issue by kevinelizabeth** [bitcoin/bitcoin#16198]
Hello, everyone, my question is how to compile and debug the latest version of bitcoin source code with Visual Studio 2015 or Visual Studio 2013

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin/bitcoin/tree/master/build_msvc#building-bitcoin-core-with-visual-studio
