### ISSUE TITLE
allow feerate argument in `bumpfee` in addition to confTarget

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#16203]
If someone has their own home-grown fee estimator, let's allow them to use it on command line.

**Comment by Sjors** [comment]
You may be able to borrow some code from `signerbumpfee` in #15876 which takes a `feeRate` argument.

**Comment by instagibbs** [comment]
Was hoping someone newer would tackle this, I think it's a pretty easy change :)

**Comment by ezegom** [comment]
> Was hoping someone newer would tackle this, I think it's a pretty easy change :)

I'll take a look into this issue :)

**Comment by instagibbs** [comment]
@ezegom I wasn't able to log in to my irc for a bit, sorry if I missed a message

**Comment by jonatack** [comment]
@ezegom are you still interested? If not, I can do it this weekend, along with updating the bumpfee tests to not use the deprecated totalFee argument.

**Comment by ezegom** [comment]
Hey, I'm almost done with this feature only thing missing is to write a couple of tests (draft PR should be up today). I'll add you as a reviewer so you can take a look.

**Comment by jonatack** [comment]
@ezegom thanks, sounds good.

**Comment by ezegom** [comment]
@instagibbs @Sjors @MarcoFalke 
_Quick question_
I was taking a look at @Sjors code for `signerbumpfee` which also allows the user to specify a feeRate. https://github.com/bitcoin/bitcoin/blob/428dfe0e670be210cb774877a04b24f117ff892f/src/wallet/rpcsigner.cpp#L161-L164 

The `signerbumpfee` rpc eventually calls `CreateRateBumpTransaction`, which calculates the feeRate to be used as the max between the feeRate passed (minFeeRate) and the old_fee + incrementalRelayFee (feeRate). Thus the feeRate provided by the user is only used if it is larger than `old_fee+incrementalRelayFee`https://github.com/bitcoin/bitcoin/blob/428dfe0e670be210cb774877a04b24f117ff892f/src/wallet/feebumper.cpp#L253-L257 

The implementation I've worked on, always creates the transaction using the feeRate passed in unless the feeRate is invalid. To check whether the feeRate passed in is valid or not, I've made a helper method that follows the same logic used to check the fee for when the TotalFee argument is used. 

My question is: **What is the desired behavior if the user entered a feeRate that is lower than the old_fee + incrementalRelayFee?** 
Should we: 
1. Display error notifying the user that the fee is too small
2. Use the old_fee + incrementalRelayFee as our feeRate (as @Sjors does)
3. Use the feeRate passed in by the user unless its less than the old_fee or greater than the wallet's maximum fee.

**Comment by instagibbs** [comment]
I'd have to understand more what the implementation looks like, but if a feerate is given, I'd expect it to either pass or fail, not do a fallback.

**Comment by MarcoFalke** [comment]
I think any option is fine, as long as it is documented and the behavior is the same in `signerbumpfee` and `bumpfee`

**Comment by ezegom** [comment]
@instagibbs, I've made a draft PR, Any feedback is greatly appreciated!

**Comment by Sjors** [comment]
> 1. Display error notifying the user that the fee is too small

This

> 2. Use the old_fee + incrementalRelayFee as our feeRate (as @Sjors does)

I shouldn't do that :-)

**Comment by instagibbs** [comment]
Now merged in master, slated for 0.19, closing
