### ISSUE TITLE
github-merge: fetch ACKS and show them before signing off

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#16200]
Currently it happens that I add a ACK comment while doing local testing before merge (so in the shell that it invokes) and this gets missed in the merge commit message.

This is because it fetches the comments from github immediately after invoking the command. I think it'd be better if it did so later.

Ideally, I'd like `github-merge.py` to fetch the ACKs and display them before confirming sign-off on the merge.

**Comment by fanquake** [comment]
It looks like the script is also still missing `ACKs` in some cases. i.e in the https://github.com/bitcoin/bitcoin/commit/afab1312c5e151b8688ef62da8c4e7c4f542a1f4 merge commit we've got:
```
ACKs for commit 75485e:
  jonasschnelli:
    utACK 75485ef
  ryanofsky:
    utACK 75485ef. It's a simple, sensible fix.
```

However looking at #16118 there are two other ACKs. A [`tACK`](https://github.com/bitcoin/bitcoin/pull/16118#issuecomment-497709833) from myself, and a [`concept ACK`](https://github.com/bitcoin/bitcoin/pull/16118#pullrequestreview-246907134) from PastaPastaPasta.

**Comment by MarcoFalke** [comment]
@fanquake No it does not. If you write ACK and some random commit (or no commit at all), it doesn't count as review.

**Comment by fanquake** [comment]
@MarcoFalke Right. A concept ACK with no commit hash isn't worth including. I also see why my ACK wasn't included. My top line included a commit hash from a different PR, wheres's as I used the correct commit hash in the review text.

**Comment by hebasto** [comment]
@fanquake 
> A concept ACK with no commit hash isn't worth including.

[CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#conceptual-review) does not mention any `BRANCH_COMMIT` following after `Concept ACK` or `Approach ACK`.

Should this be corrected?

**Comment by MarcoFalke** [comment]
Maybe it should mention that only `ACK`s followed by the commit hash are included in the merge commit, so the reviewer can decide whether it is included or not.
