### ISSUE TITLE
Can't bind rpcport inside docker

### ISSUE THREAD

**Issue by mrbianchi** [bitcoin/bitcoin#16209]
I dont really know if it is a bitcoin core problem or not , but I'm trying hard and I can't get it

> Binding RPC on address :: port 18332 failed.

More info: https://github.com/kylemanna/docker-bitcoind/issues/42

**Comment by mrbianchi** [comment]
and before :
> libevent: getaddrinfo: address family for nodename not supported

**Comment by fanquake** [comment]
@harding might be able to help here?

**Comment by mrbianchi** [comment]
Update:
With debug=1 I could verify that 127.0.0.0:18332 was being binded, not [::1]:18332 but I dont care
I could verify that local connection inside the docker with bitcoin-cli works
Now the problem is that I cant use the rpc outside the docker I don't know why
Probably isn't a Bitcoin issue

**Comment by mrbianchi** [comment]
Update:
Confirmed, not bitcoin problem, I tried with another docker image and seems working:
https://hub.docker.com/r/ruimarinho/bitcoin-core

**Comment by mrbianchi** [comment]
Maybe it was a bitcoin problem, the problem was binding 0.0.0.0 (all interfaces)
The first image that I used , used bitcoin 0.17.1 and it only binded 127.0.0.1 , no matters if the image had a hardcoded rpcallowip=0.0.0.0/0 , bitcoind even didn't tried to bind 0.0.0.0
The second image that I used , I used the tag 0.17.1 and it had the error "binding RPC on address 0.0.0.0 port 18332 failed."
Now I used the tag 0.18.0 and seems working well

**Comment by chanhosuh** [comment]
@mrbianchi The reason it's working is it's using version 0.16.  There was a change in version 0.18 that requires the use of `rpcbind` parameter.

Before 0.18,  if you put `rpcallowip=0.0.0.0/0`, the value of `rpcbind` didn't need to be set as it defaulted to all interfaces.  

Now that is no longer the case.  Here's my setup, for running bitcoind in a container through Docker compose:

```
rpcallowip=0.0.0.0/0
rpcbind=127.0.0.1
rpcbind=<local DNS name, such as the container name used in your Docker Compose file>
```

The first `rpcbind` is so I can make RPC calls from inside the container.  The second is so other containers can reach the bitcoind container.

**Comment by mrbianchi** [comment]
@chanhosuh you are right! I tested. Documentation should be updated.
Additionally, I had to add [test] section in bitcoin.conf because is mandatory for testnet
`testnet=1
server=1
rpcallowip=0.0.0.0/0
rpcuser=admin
rpcpassword=admin

[test]
rpcbind=127.0.0.1:18332
rpcbind=172.18.0.30:18332`

**Comment by caiyaonan** [comment]
Binding RPC on address xxx.xxx.xxx.xxx port 19914 failed.

**Comment by caiyaonan** [comment]
i write rpcport rpcallowip rpcallowip rpcbind, but system print error Binding RPC on address 116.21.17.197 port 19914 failed. @chanhosuh @mrbianchi  help

**Comment by abhyankar-amey** [comment]
> Update:
> Confirmed, not bitcoin problem, I tried with another docker image and seems working:
> https://hub.docker.com/r/ruimarinho/bitcoin-core

@mrbianchi I am trying from a while with 0.18.1 bitcoin-core version but RPC not working. My commands = 

1) Start docker conainer = docker run --rm --name bitcoin-server -it btc-19nov \
  -printtoconsole \
  -regtest=1 \
  -rpcbind=127.0.0.1 \
  -rpcauth=

2) Initiate RCP call from base Ubuntu 18.04 LTS machine = docker run -it --rm btc-19nov \
  bitcoin-cli \
  -rpcconnect=bitcoin-server \
  -regtest \
  -rpcuser=amey \
  -stdinrpcpass \
  getbalance

Error = error: Could not connect to the server bitcoin-server:18443

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.

Any hints how to solve this issue?
