### ISSUE TITLE
build: simplify tar commands in gitian descriptors

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16211]
cfields mentioned that it's likely possible to simplify our use of `find`, `sort`, `tar` and `gzip` inside our gitian descriptors by taking use of modern command line flags.

We currently chain multiple commands together like so:

https://github.com/bitcoin/bitcoin/blob/7524376a81a1955f4da4adb23005f2122b18a270/contrib/gitian-descriptors/gitian-linux.yml#L152

However it should be possible to drop `sort` by taking advantage of `tar`'s [--sort=name](http://man7.org/linux/man-pages/man1/tar.1.html) command line flag:
> --sort=ORDER
              Using --sort=name ensures the member ordering in the created
              archive is uniform and reproducible.

We should also be able to drop `gzip` and instead pass `--gzip` straight to `tar`:
> -z, --gzip, --gunzip, --ungzip
              Filter the archive through gzip(1).

or, we may need to use `-I` so we can pass `gzip -9n`:
> -I, --use-compress-program=COMMAND
              Filter data through COMMAND.  It must accept the -d option,
              for decompression.  The argument can contain command line
              options.

**Comment by MarcoFalke** [comment]
Is it worth it to make a single line command a bit shorter? Looks like this is working just fine, why change it?

**Comment by dongcarl** [comment]
Just for documentation, I've tried those methods and they seem to be less flexible than UNIX compose-ability with pipes. For example, the `--sort=name` for `tar` only applies to directory entries, and was a source of non-determinism in my Guix branch. Also, for `--use-compress-program=`, it's going to make it complicated if we need to pass options to `gzip` in the future that include `IFS` and needs escaping or something like that.

But overall, it's a good thought, and we should look for other places to optimize build time in our gitian descriptors.

**Comment by hebasto** [comment]
The Linux piping has clear syntax and robust behavior. It uses the UNIX principle "Do One Thing and Do It Well".

**Comment by MarcoFalke** [comment]
Ok, closing for now, unless there is evidence that this brings any advantage.
