### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [bitcoin/bitcoin#16216]
**Objective**: Implement and Support i2p in Bitcoin
**Description**: Explore the possibility of using the Bitcoin network over i2p.
**Why?**: Many reasons, mainly for privacy and security but also to support decentralized communications. 
**Related Projects**:
Kovri: https://kovri.io/

________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75531484-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75531484)](https://www.bountysource.com/issues/75531484-feature-support-i2p)

**Comment by MarcoFalke** [comment]
How is this different from  

* Binding to multiple anonymous networks (esp. I2P) #2091

**Comment by laanwj** [comment]
Yes, this would be nice, it is one of my goals with [BIP155](https://github.com/bitcoin/bips/pull/766) (addrv2).

**Comment by adamjonas** [comment]
It may be useful to close this to push discussion to #2091 whose progress can be tracked in #18884.
