### ISSUE TITLE
0.18.0   build  error   

### ISSUE THREAD

**Issue by sslazio2009** [bitcoin/bitcoin#16222]
info：
CXX      test/test_test_bitcoin-crypto_tests.o
test/base58_tests.cpp: In member function ‘void base58_tests::base58_EncodeBase58::test_method()’:
test/base58_tests.cpp:23:44: error: ‘json_tests’ was not declared in this scope
     UniValue tests = read_json(std::string(json_tests::base58_encode_decode, json_tests::base58_encode_decode + sizeof(json_tests::base58_encode_decode)));
                                            ^~~~~~~~~~

**Comment by MarcoFalke** [comment]
What are the steps to reproduce?

**Comment by MarcoFalke** [comment]
Also, provide the output of `git status` and maybe try `make distclean && ./configure ${your_options} && make`
