### ISSUE TITLE
Ownbit list on bitcoin.org

### ISSUE THREAD

**Issue by jtomtan** [bitcoin/bitcoin#16269]
Hi guys,

We want to apply for listing on bitcoin.org as one of the recommend Bitcoin Wallets. Ownbit has a long history back to 2013 which contributes a lot for Bitcoin growing up, especially in China. 

And now Ownbit is one the most featured Bitcoin Wallets, which supports SegWit, MultiSig, Customize UTXO, Offline Cold Wallet and etc. It has a very good reputation as the BEST Bitcoin Wallet in the community(If you try it , you will see).

And also Ownbit has been trusted by many other popular projects, and has been listed as their recommended 3rd wallets, like Litecoin, DASH and so on. And also Stellar will list Ownbit in their new website soon. All these can be checked and they are true.

 So, Ownbit as one of the modern Bitcoin Wallets apply for listing. Wish to get feedback from you soon.

Ownbit website: https://ownbit.io
Apps can be downloaded at Appsotre/Google Play searching: Ownbit.

**Comment by fanquake** [comment]
This is not the right repository, I assume you meant https://github.com/bitcoin-core/bitcoincore.org.

**Comment by jtomtan** [comment]
> This is not the right repository, I assume you meant https://github.com/bitcoin-core/bitcoincore.org.

Thank you, will open issue there.
