### ISSUE TITLE
Black debug window

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#16266]
![image](https://user-images.githubusercontent.com/32963518/59949099-cc899380-947a-11e9-8ba6-d72ed0d95f32.png)

Master (413e438ea9767710d4810c4400fd1242ca52cd1c) on Bionic + Qt 5.12.4.

Steps to reproduce the issue:
1) Window -> Information
2) close debug window
3) Window -> Information

**Comment by fanquake** [comment]
Do you think this is more likely a regression in Qt 5.12.4, or because you're running on bionic? 
I cannot reproduce with Qt 5.12.3 on macOS. Will setup a Bionic VM to try recreate.

**Comment by fanquake** [comment]
I setup a new Bionic VM (18.04.2 LTS), installed Qt 5.12.4 LTS using the [online installer](http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run) and was able to recreate. Note that resizing the debug window will show the correct contents.

![bionic_qt_5_12_4_debug](https://user-images.githubusercontent.com/863730/59960290-17e28700-94f9-11e9-8971-a6a279a47115.png)

**Comment by hebasto** [comment]
Tested Qt 5.12.0. No bug.
Yes, it seems a regression in Qt 5.12.4.

**Comment by hebasto** [comment]
@fanquake 
> I setup a new Bionic VM (18.04.2 LTS), installed Qt 5.12.4 LTS using the [online installer](http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run) and was able to recreate.

What `./configure` arguments do you use in such setup?

**Comment by fanquake** [comment]
> Something like QTBUG-76509.

Yea that looks like what it could be.

> What ./configure arguments do you use in such setup?

I just used `PKG_CONFIG_PATH=/path/to/Qt/5.12.4/gcc_64/lib/pkgconfig ./configure --with-incompatible-bdb`, and then used `LD_PRELOAD` at runtime to specify the `.so`s at runtime.

I've read some of your related notes + discussion upstream in the Qt bug tracker about issues with the online installer. I'm going to write up some notes for myself in [core-review](https://github.com/fanquake/core-review).

**Comment by hebasto** [comment]
Tested Qt 5.13.0. No bug.

**Comment by hebasto** [comment]
Update: https://bugreports.qt.io/browse/QTBUG-76509?focusedCommentId=466152&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-466152
