### ISSUE TITLE
bumpfee not returning hash of newly created transaction

### ISSUE THREAD

**Issue by PavelNiedoba** [bitcoin/bitcoin#16275]
I'm trying to implement replace by fee functionality with bictoind (v18) and bumpfee rpc call described here

It works by mean that new transaction is created with higher fee, but result should be:

```
{
  "txid":    "value",   (string)  The id of the new transaction
  "origfee":  n,         (numeric) Fee of the replaced transaction
  "fee":      n,         (numeric) Fee of the new transaction
  "errors":  [ str... ] (json array of strings) Errors encountered during processing (may be empty)
}
```

but I'm getting basically all null response

```
{
  "id": "BumpFeeRequest 1561247020661",
  "error": null,
  "txid": null,
  "origfee": null,
  "fee": null,
  "errors": null
}
```

Which makes it hard to identify the new transaction in down-steam system.

I believe that hash of newly created tx should be returned

I posted this also here:
https://bitcoin.stackexchange.com/questions/88560/bitcoind-jsonrpc-bumpfee-not-returning-hash-of-newly-created-transaction

**Comment by MarcoFalke** [comment]
Without steps to reproduce (and the exact versions of the software you are using), we can't help much here.

**Comment by promag** [comment]
@PavelNiedoba what are you using on the client side?

**Comment by PavelNiedoba** [comment]
Furnishing requested info:
wallet version 2019-06-22T22:13:57Z Bitcoin Core version v0.18.0 (release build) (latest to-day)

as client I'm using java HttpClient from Rescu library. I also tested it using curl.

below is json POST  requests and responses, skipping authentications, because its obviously working fine

first there is set fee call:
```
request:{"jsonrpc":"1.0","id":"SetFeeRequest 1561457471653","method":"settxfee","params":[0.000720]}
response:{"id":"SetFeeRequest 1561457471653","error":null,"result":true}
```

send many:
```
request:{"jsonrpc":"1.0","id":"SendRequest 1561457471707","method":"sendmany","params":["",{"tb1q6wedjc0st5c9nh8upd89gelv9tf5f9mttc2grh":0.01},1,"",null,true]}
response:{"id":"SendRequest 1561457471707","error":null,"result":"36a747bcffd1c4a4e24c0b5a767297358f21554ed7a24b9efdf1b97aba66a45b"}
```

get transaction by hash:

```
request:{"jsonrpc":"1.0","id":"GetTransactionRequest 1561457471856","method":"gettransaction","params":["36a747bcffd1c4a4e24c0b5a767297358f21554ed7a24b9efdf1b97aba66a45b",false]}
response:{"id":"GetTransactionRequest 1561457471856","error":null,"result":{"amount":-0.01000000,"confirmations":0,"blockhash":null,"blockindex":null,"blocktime":null,"txid":"36a747bcffd1c4a4e24c0b5a767297358f21554ed7a24b9efdf1b97aba66a45b","time":1561457470,"comment":null,"details":[{"account":null,"address":"tb1q6wedjc0st5c9nh8upd89gelv9tf5f9mttc2grh","category":"send","amount":-0.01000000,"label":null,"vout":0,"fee":-0.00054216,"abandoned":false}],"bip125-replaceable":"yes"}}
```

bump fee:

```
request:{"jsonrpc":"1.0","id":"BumpFeeRequest 1561457473892","method":"bumpfee","params":["36a747bcffd1c4a4e24c0b5a767297358f21554ed7a24b9efdf1b97aba66a45b"]}
response:{"id":"BumpFeeRequest 1561457473892","error":null,"txid":null,"origfee":null,"fee":null,"errors":null}
```

**Comment by MarcoFalke** [comment]
> as client I'm using java HttpClient from Rescu library. I also tested it using curl.

Could you include the command line and response when doing the bumpfee call with curl?

It looks like this is an upstream bug with the java library.

**Comment by PavelNiedoba** [comment]
You are right, my bad, sorry for wasting your time

**Comment by promag** [comment]
@paveljanik no problem, always try with `bitcoin-cli` to discard problems in third party clients.
