### ISSUE TITLE
State of the Repo Report, June 2019

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#16298]
# State of the Repo Report, June 2019

## Introduction

For all fans of statistics – enjoy! 🤓

785 authors have contributed to the project (merged contributions). Thank you! ❤️

The repo contains 487&nbsp;944 lines of text and 1&nbsp;738 files.

20&nbsp;612 commits have been made of which 3&nbsp;917 are merge commits.

There are currently 287 open pull requests from in total 87 contributors.

If all open pull requests were merged the project line count would grow by roughly 5 percent.

The total set of open pull requests adds 49&nbsp;360&nbsp;lines, removes 20&nbsp;320&nbsp;lines and touches 2&nbsp;267&nbsp;distinct files.

The "median open pull request" adds 53&nbsp;lines, removes 16&nbsp;lines and touches 4&nbsp;files.

Previous edition: [State of the Repo, May 2019](https://github.com/bitcoin/bitcoin/issues/16085)

## Compile-time memory consumption

| #  | File | Max memory usage (RSS) |
| -: | :--- | ---------------------: |
| 1 | `test/test_test_bitcoin-script_tests.o` | 1416 MB |
| 2 | `wallet/libbitcoin_wallet_a-wallet.o` | 1102 MB |
| 3 | `wallet/libbitcoin_wallet_a-rpcwallet.o` | 1059 MB |
| 4 | `libbitcoin_server_a-validation.o` | 953 MB |
| 5 | `test/test_test_bitcoin-util_tests.o` | 905 MB |
| 6 | `wallet/test/test_test_bitcoin-wallet_tests.o` | 905 MB |
| 7 | `wallet/test/test_test_bitcoin-coinselector_tests.o` | 897 MB |
| 8 | `libbitcoin_server_a-init.o` | 892 MB |
| 9 | `qt/test/qt_test_test_bitcoin_qt-wallettests.o` | 890 MB |
| 10 | `wallet/test/test_test_bitcoin-ismine_tests.o` | 874 MB |
| 11 | `qt/test/qt_test_test_bitcoin_qt-addressbooktests.o` | 863 MB |
| 12 | `libbitcoin_server_a-net_processing.o` | 857 MB |
| 13 | `wallet/test/test_test_bitcoin-psbt_wallet_tests.o` | 837 MB |
| 14 | `test/test_test_bitcoin-transaction_tests.o` | 813 MB |
| 15 | `qt/qt_libbitcoinqt_a-sendcoinsdialog.o` | 809 MB |
| 16 | `wallet/libbitcoin_wallet_a-rpcdump.o` | 800 MB |
| 17 | `test/test_test_bitcoin-rpc_tests.o` | 792 MB |
| 18 | `libbitcoin_server_a-validationinterface.o` | 770 MB |
| 19 | `test/test_bitcoin` | 752 MB |
| 20 | `rpc/libbitcoin_server_a-blockchain.o` | 745 MB |
| 21 | `qt/qt_libbitcoinqt_a-rpcconsole.o` | 741 MB |
| 22 | `test/test_test_bitcoin-sighash_tests.o` | 739 MB |
| 23 | `rpc/libbitcoin_server_a-rawtransaction.o` | 721 MB |
| 24 | `qt/qt_libbitcoinqt_a-walletmodel.o` | 721 MB |
| 25 | `wallet/libbitcoin_wallet_a-walletdb.o` | 720 MB |
| ... | ... | ... |
| 450 | `crypto/sha256_sse4.cpp` | 24 MB |
| 451 | `compat/libbitcoin_util_a-glibc_sanity.o` | 24 MB |
| 452 | `script/script_error.cpp` | 23 MB |
| 453 | `script/libbitcoin_consensus_a-script_error.o` | 23 MB |
| 454 | `compat/libbitcoin_util_a-strnlen.o` | 18 MB |

Accumulated memory use during a full build (454 compiler invocations): 142 GB (max RSS)
Average memory use: 320 MB (max RSS)
Measured using gcc 7.4.0

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines added | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 7&nbsp;355&nbsp;(15%) | -1&nbsp;793 | 5&nbsp;562 | 150 | 10&nbsp;(3%) |
| 2 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 5&nbsp;950&nbsp;(12%) | -829 | 5&nbsp;121 | 91 | 17&nbsp;(6%) |
| 3 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 4&nbsp;676&nbsp;(9%) | -2&nbsp;958 | 1&nbsp;718 | 121 | 15&nbsp;(5%) |
| 4 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 3&nbsp;263&nbsp;(7%) | -414 | 2&nbsp;849 | 97 | 25&nbsp;(9%) |
| 5 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 3&nbsp;027&nbsp;(6%) | -509 | 2&nbsp;518 | 34 | 12&nbsp;(4%) |
| 6 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 2&nbsp;646&nbsp;(5%) | -862 | 1&nbsp;784 | 40 | 2&nbsp;(1%) |
| 7 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 2&nbsp;435&nbsp;(5%) | -1&nbsp;148 | 1&nbsp;287 | 72 | 7&nbsp;(2%) |
| 8 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 1&nbsp;756&nbsp;(4%) | -1&nbsp;664 | 92 | 16 | 7&nbsp;(2%) |
| 9 | [MishraShivendra](https://github.com/bitcoin/bitcoin/pulls/MishraShivendra) | 1&nbsp;467&nbsp;(3%) | -41 | 1&nbsp;426 | 12 | 1&nbsp;(0%) |
| 10 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 1&nbsp;056&nbsp;(2%) | -933 | 123 | 48 | 6&nbsp;(2%) |
| 11 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 1&nbsp;005&nbsp;(2%) | -672 | 333 | 96 | 19&nbsp;(7%) |
| 12 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 957&nbsp;(2%) | -27 | 930 | 18 | 1&nbsp;(0%) |
| 13 | [sipsorcery](https://github.com/bitcoin/bitcoin/pulls/sipsorcery) | 942&nbsp;(2%) | -2&nbsp;366 | -1&nbsp;424 | 36 | 2&nbsp;(1%) |
| 14 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 883&nbsp;(2%) | -128 | 755 | 33 | 4&nbsp;(1%) |
| 15 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 842&nbsp;(2%) | -405 | 437 | 52 | 24&nbsp;(8%) |
| 16 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 828&nbsp;(2%) | -101 | 727 | 30 | 2&nbsp;(1%) |
| 17 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 765&nbsp;(2%) | -830 | -65 | 58 | 3&nbsp;(1%) |
| 18 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 733&nbsp;(1%) | -277 | 456 | 32 | 6&nbsp;(2%) |
| 19 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 660&nbsp;(1%) | -440 | 220 | 60 | 9&nbsp;(3%) |
| 20 | [sdaftuar](https://github.com/bitcoin/bitcoin/pulls/sdaftuar) | 563&nbsp;(1%) | -393 | 170 | 23 | 4&nbsp;(1%) |
| 21 | [NicolasDorier](https://github.com/bitcoin/bitcoin/pulls/NicolasDorier) | 545&nbsp;(1%) | -93 | 452 | 16 | 2&nbsp;(1%) |
| 22 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 541&nbsp;(1%) | -690 | -149 | 216 | 10&nbsp;(3%) |
| 23 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 491&nbsp;(1%) | -567 | -76 | 27 | 5&nbsp;(2%) |
| 24 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 478&nbsp;(1%) | -9 | 469 | 4 | 1&nbsp;(0%) |
| 25 | [TheBlueMatt](https://github.com/bitcoin/bitcoin/pulls/TheBlueMatt) | 450&nbsp;(1%) | -128 | 322 | 31 | 5&nbsp;(2%) |
| 26 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 440&nbsp;(1%) | -47 | 393 | 7 | 3&nbsp;(1%) |
| 27 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 351&nbsp;(1%) | -306 | 45 | 39 | 1&nbsp;(0%) |
| 28 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 328&nbsp;(1%) | -158 | 170 | 13 | 3&nbsp;(1%) |
| 29 | [l2a5b1](https://github.com/bitcoin/bitcoin/pulls/l2a5b1) | 322&nbsp;(1%) | -93 | 229 | 23 | 2&nbsp;(1%) |
| 30 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 287&nbsp;(1%) | -82 | 205 | 7 | 2&nbsp;(1%) |
| 31 | [theuni](https://github.com/bitcoin/bitcoin/pulls/theuni) | 271&nbsp;(1%) | -33 | 238 | 14 | 1&nbsp;(0%) |
| 32 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 261&nbsp;(1%) | -43 | 218 | 3 | 1&nbsp;(0%) |
| 33 | [ariard](https://github.com/bitcoin/bitcoin/pulls/ariard) | 231&nbsp;(0%) | -247 | -16 | 12 | 2&nbsp;(1%) |
| 34 | [gertjaap](https://github.com/bitcoin/bitcoin/pulls/gertjaap) | 184&nbsp;(0%) | -12 | 172 | 8 | 2&nbsp;(1%) |
| 35 | [benthecarman](https://github.com/bitcoin/bitcoin/pulls/benthecarman) | 182&nbsp;(0%) | -21 | 161 | 13 | 4&nbsp;(1%) |
| 36 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 155&nbsp;(0%) | -105 | 50 | 19 | 6&nbsp;(2%) |
| 37 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 135&nbsp;(0%) | -101 | 34 | 4 | 1&nbsp;(0%) |
| 38 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 131&nbsp;(0%) | -85 | 46 | 4 | 1&nbsp;(0%) |
| 39 | [giulio92](https://github.com/bitcoin/bitcoin/pulls/giulio92) | 131&nbsp;(0%) | -133 | -2 | 1 | 1&nbsp;(0%) |
| 40 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 117&nbsp;(0%) | -31 | 86 | 11 | 2&nbsp;(1%) |
| 41 | [mrwhythat](https://github.com/bitcoin/bitcoin/pulls/mrwhythat) | 116&nbsp;(0%) | -8 | 108 | 7 | 1&nbsp;(0%) |
| 42 | [LarryRuane](https://github.com/bitcoin/bitcoin/pulls/LarryRuane) | 112&nbsp;(0%) | -9 | 103 | 6 | 1&nbsp;(0%) |
| 43 | [jonatack](https://github.com/bitcoin/bitcoin/pulls/jonatack) | 99&nbsp;(0%) | -9 | 90 | 1 | 1&nbsp;(0%) |
| 44 | [MapleLaker](https://github.com/bitcoin/bitcoin/pulls/MapleLaker) | 89&nbsp;(0%) | -1 | 88 | 1 | 1&nbsp;(0%) |
| 45 | [conscott](https://github.com/bitcoin/bitcoin/pulls/conscott) | 87&nbsp;(0%) | -61 | 26 | 3 | 1&nbsp;(0%) |
| 46 | [darosior](https://github.com/bitcoin/bitcoin/pulls/darosior) | 86&nbsp;(0%) | -13 | 73 | 8 | 4&nbsp;(1%) |
| 47 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 83&nbsp;(0%) | -9 | 74 | 5 | 1&nbsp;(0%) |
| 48 | [IntegralTeam](https://github.com/bitcoin/bitcoin/pulls/IntegralTeam) | 79&nbsp;(0%) | -3 | 76 | 3 | 1&nbsp;(0%) |
| 49 | [greenaddress](https://github.com/bitcoin/bitcoin/pulls/greenaddress) | 78&nbsp;(0%) | -31 | 47 | 10 | 1&nbsp;(0%) |
| 50 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 42&nbsp;(0%) | -15 | 27 | 15 | 1&nbsp;(0%) |
| 51 | [ken2812221](https://github.com/bitcoin/bitcoin/pulls/ken2812221) | 42&nbsp;(0%) | -10 | 32 | 6 | 1&nbsp;(0%) |
| 52 | [meshcollider](https://github.com/bitcoin/bitcoin/pulls/meshcollider) | 41&nbsp;(0%) | -23 | 18 | 4 | 1&nbsp;(0%) |
| 53 | [fanatid](https://github.com/bitcoin/bitcoin/pulls/fanatid) | 40&nbsp;(0%) | -3 | 37 | 3 | 1&nbsp;(0%) |
| 54 | [shannon1916](https://github.com/bitcoin/bitcoin/pulls/shannon1916) | 39&nbsp;(0%) | -9 | 30 | 4 | 1&nbsp;(0%) |
| 55 | [tryphe](https://github.com/bitcoin/bitcoin/pulls/tryphe) | 33&nbsp;(0%) | -38 | -5 | 3 | 2&nbsp;(1%) |
| 56 | [Bushstar](https://github.com/bitcoin/bitcoin/pulls/Bushstar) | 31&nbsp;(0%) | -6 | 25 | 3 | 2&nbsp;(1%) |
| 57 | [kodslav](https://github.com/bitcoin/bitcoin/pulls/kodslav) | 31&nbsp;(0%) | -5 | 26 | 1 | 1&nbsp;(0%) |
| 58 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 30&nbsp;(0%) | -25 | 5 | 4 | 1&nbsp;(0%) |
| 59 | [pstratem](https://github.com/bitcoin/bitcoin/pulls/pstratem) | 27&nbsp;(0%) | -51 | -24 | 2 | 2&nbsp;(1%) |
| 60 | [jkczyz](https://github.com/bitcoin/bitcoin/pulls/jkczyz) | 25&nbsp;(0%) | -26 | -1 | 4 | 2&nbsp;(1%) |
| 61 | [LeandroRocha84](https://github.com/bitcoin/bitcoin/pulls/LeandroRocha84) | 24&nbsp;(0%) | -14 | 10 | 4 | 1&nbsp;(0%) |
| 62 | [lucayepa](https://github.com/bitcoin/bitcoin/pulls/lucayepa) | 24&nbsp;(0%) | -14 | 10 | 1 | 1&nbsp;(0%) |
| 63 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2 | 20 | 2 | 1&nbsp;(0%) |
| 64 | [tecnovert](https://github.com/bitcoin/bitcoin/pulls/tecnovert) | 22&nbsp;(0%) | -21 | 1 | 3 | 1&nbsp;(0%) |
| 65 | [torkelrogstad](https://github.com/bitcoin/bitcoin/pulls/torkelrogstad) | 22&nbsp;(0%) | -1 | 21 | 1 | 1&nbsp;(0%) |
| 66 | [marcoagner](https://github.com/bitcoin/bitcoin/pulls/marcoagner) | 21&nbsp;(0%) | -2 | 19 | 1 | 1&nbsp;(0%) |
| 67 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 17&nbsp;(0%) | -14 | 3 | 2 | 1&nbsp;(0%) |
| 68 | [asood123](https://github.com/bitcoin/bitcoin/pulls/asood123) | 17&nbsp;(0%) | -10 | 7 | 3 | 1&nbsp;(0%) |
| 69 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 17&nbsp;(0%) | -15 | 2 | 6 | 3&nbsp;(1%) |
| 70 | [real-or-random](https://github.com/bitcoin/bitcoin/pulls/real-or-random) | 16&nbsp;(0%) | -25 | -9 | 2 | 1&nbsp;(0%) |
| 71 | [JeremyRand](https://github.com/bitcoin/bitcoin/pulls/JeremyRand) | 15&nbsp;(0%) | -1 | 14 | 1 | 1&nbsp;(0%) |
| 72 | [icota](https://github.com/bitcoin/bitcoin/pulls/icota) | 14&nbsp;(0%) | -5 | 9 | 4 | 1&nbsp;(0%) |
| 73 | [stevenroose](https://github.com/bitcoin/bitcoin/pulls/stevenroose) | 14&nbsp;(0%) | -12 | 2 | 1 | 1&nbsp;(0%) |
| 74 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -3 | 8 | 1 | 1&nbsp;(0%) |
| 75 | [amitiuttarwar](https://github.com/bitcoin/bitcoin/pulls/amitiuttarwar) | 9&nbsp;(0%) | -8 | 1 | 3 | 1&nbsp;(0%) |
| 76 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 8&nbsp;(0%) | -3 | 5 | 3 | 1&nbsp;(0%) |
| 77 | [orientye](https://github.com/bitcoin/bitcoin/pulls/orientye) | 8&nbsp;(0%) | -2 | 6 | 2 | 1&nbsp;(0%) |
| 78 | [kazcw](https://github.com/bitcoin/bitcoin/pulls/kazcw) | 7&nbsp;(0%) | -9 | -2 | 1 | 1&nbsp;(0%) |
| 79 | [sp4ke](https://github.com/bitcoin/bitcoin/pulls/sp4ke) | 5&nbsp;(0%) | -3 | 2 | 1 | 1&nbsp;(0%) |
| 80 | [d3spwn](https://github.com/bitcoin/bitcoin/pulls/d3spwn) | 4&nbsp;(0%) | -2 | 2 | 2 | 1&nbsp;(0%) |
| 81 | [kostyantyn](https://github.com/bitcoin/bitcoin/pulls/kostyantyn) | 4&nbsp;(0%) | -7 | -3 | 3 | 1&nbsp;(0%) |
| 82 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 3&nbsp;(0%) | -4 | -1 | 1 | 1&nbsp;(0%) |
| 83 | [bpay](https://github.com/bitcoin/bitcoin/pulls/bpay) | 2&nbsp;(0%) | -2 | 0 | 1 | 1&nbsp;(0%) |
| 84 | [zenosage](https://github.com/bitcoin/bitcoin/pulls/zenosage) | 2&nbsp;(0%) | -3 | -1 | 2 | 1&nbsp;(0%) |
| 85 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 1&nbsp;(0%) | -2 | -1 | 1 | 1&nbsp;(0%) |
| 86 | [JosuGZ](https://github.com/bitcoin/bitcoin/pulls/JosuGZ) | 1&nbsp;(0%) | -1 | 0 | 1 | 1&nbsp;(0%) |
| 87 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6 | -6 | 2 | 1&nbsp;(0%) |

**Comment by fanquake** [comment]
Thanks.
