### ISSUE TITLE
Bitcoind does not respect rpcbind for testnet

### ISSUE THREAD

**Issue by michnovka** [bitcoin/bitcoin#16315]
Bitcoind does not respect rpcbind option for testnet in config unless specified inside [test] section.

Unless I specify [main] and [test] sections I expect all lines in config to apply to both testnet and main. My config has this:

```
rpcbind=127.0.0.1
rpcbind=10.18.0.1
rpcallowip=127.0.0.1
rpcallowip=10.18.0.0/24
```

under NO section

Bitcoin testnet process was bound to only localhost (and also on ipv6 which I never specified)
```
tcp        0      0 10.18.0.1:8332          0.0.0.0:*               LISTEN      582/bitcoind        
tcp        0      0 127.0.0.1:8332          0.0.0.0:*               LISTEN      582/bitcoind        
tcp        0      0 127.0.0.1:18332         0.0.0.0:*               LISTEN      581/bitcoind        
tcp6       0      0 ::1:18332               :::*                    LISTEN      581/bitcoind      
```

Create single bitcoin.conf file and specify rpcbind=NOT.LOCAL.HOST.IP

run then bitcoind and bitcoind -testnet one after another

website 0.18.0

Amazon EC2 instance running Debian 9

bitcoin.conf
```
# Accept command line and JSON-RPC commands
server=1

# Set database cache size in megabytes (4 to 16384, default: 450)
dbcache=1536

# Set the number of script verification threads (-6 to 16, 0 = auto, <0 = leave that many cores free, default: 0)
par=1

# Set to blocksonly mode, sends and receives no lose transactions, instead handles only complete blocks
#blocksonly=1
blocksonly=0
maxmempool=256

# Tries to keep outbound traffic under the given target (in MiB per 24h), 0 = no limit (default: 0)
maxuploadtarget=256

# Maintain at most <n> connections to peers (default: 125)
maxconnections=32

# Username for JSON-RPC connections
rpcuser=bitcoinrpc

# Password for JSON-RPC connections
rpcpassword=b956a61a2b6b8d30a744165384e3b61e

# Maintain a full transaction index, used by the getrawtransaction rpc call (default: 0)
txindex=1

# Make the wallet broadcast transactions (default: 1)
walletbroadcast=1

# Allow JSON-RPC connections from, by default only localhost are allowed
rpcbind=127.0.0.1
rpcbind=10.18.0.1
rpcallowip=127.0.0.1
rpcallowip=10.18.0.0/24

```

**Comment by gertjaap** [comment]
As per the comments from the [code](https://github.com/bitcoin/bitcoin/blob/master/src/util/system.cpp#L310):

```These options would cause cross-contamination if values for mainnet were used while running on regtest/testnet (or vice-versa). Setting them as section_only_args ensures that sharing a config file between mainnet and regtest/testnet won't cause problems due to these parameters by accident.```

So this behavior is by design. `rpcbind` and `rpcallowip`, amongst others, for networks other than mainnet are only read from the network specific config section or else fallback to its defaults.
