### ISSUE TITLE
Visual improvement across PC/MAC/Unix versions

### ISSUE THREAD

**Issue by NicolasChoukroun** [bitcoin/bitcoin#16318]
The PC version of the wallet is monochrome, and the frames are not showing.
The Wallet on Unix is the one looking best with the blue icons.

I have fixed these problems while working on the Kryptofranc, and I would like to update Bitcoin to be consistant across the desktop versions.

Here is what the PC wallet is looking right now.

![old-bitcoin-wallet](https://user-images.githubusercontent.com/40539492/60398124-08a9ac00-9b7f-11e9-9288-bb245552183c.jpg)

And that's how it will look after.

![new-wallet-800](https://user-images.githubusercontent.com/40539492/60398143-2c6cf200-9b7f-11e9-82a4-54dc93fa6b0a.jpg)

(sorry for the KYF stuff, the only changes are the frame and the icons)

The modifications are minimum. 
/src/qt/forms/overviewpage.ui
Has to be modified so that the frames are visible not only on Unix.

Otherwise it is just a pre-colored set of icons. They are compatible with the ones used today, that means that my tests are not showing a noticeable difference on Unix and MAC

The new icons are replacing all the current monochrome PNG icons located here:
/src/qt/res/icons/
 
Windows though which is the most used version is in my opinion much better.

Let me know if you want that I push these to master.

**Comment by jonasschnelli** [comment]
No strong opinion.

I think we intentionally keep the UI minimalistic due to the flexibility of themes/operating systems we want to reach.

A better UX would require someone really working on that. Also, since we are not (and don't want) using HTML/web technologies for the frontend display, designing a nice UI takes more effort than people think.

**Comment by NicolasChoukroun** [comment]
I think that you missunderstand the issue. The issue is not to improve the UI, it is to make it consistant on all the platform. The current UI on windows does not have colors, does not have frames. It is the most used wallet. The Unix one has colors and has frames. MAC version does not have color but not have frames.

Basically my changes will make the wallet identical on all the platforms. That means looking like the Unix version on all the version.

I think it is a very important update.

**Comment by ryanofsky** [comment]
> Basically my changes will make the wallet identical on all the platforms.

Where are these changes? Is there a PR open? This sounds like a good idea, depending on the details. You may want to see https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#contributor-workflow if you are unfamiliar with the process for submitting changes.

**Comment by promag** [comment]
Regarding the color I agree with @jonasschnelli, I think monochrome is the best option.

Personally I don't link (too many) frames/boxes, working out spaces/paddings/margins and fonts could give a better UI.

The icons could be improved to be more light/thin IMO.

> Let me know if you want that I push these to master.

You only have to push to a branch in your fork then let us know.

**Comment by NicolasChoukroun** [comment]
Fork that includes the changes, based on current master: https://github.com/NicolasChoukroun/bitcoin

Sorry for the delay, I have reworked the icons and also it is my first submission. The wallet should look the same apart some small details that could be fixed later (like the BTC in the icon bar at the bottom that is showing relatively to the OS palette, that means black everywhere and blue or orange or whatever on Unix).

The main changes are:
- same color for the Icons across the board (Unix, PC and MAC)
- PC version now looking as cool as the Unix version.
- Icon color fixed with BItcoin logo color on all version, all OS and all local Palettes.
- Text, and background untouched, other styles untouched.
- Forms are the same, no change in the UI apart some frames that were not showing for PC.

Reminder: here is the wallet on PC right now.
![image](https://user-images.githubusercontent.com/40539492/60735235-b8668b80-9f7c-11e9-9192-decac097e135.png)


After the change, it is looking like this.
![bitcoinpc01](https://user-images.githubusercontent.com/40539492/60734950-daabd980-9f7b-11e9-84c4-3eb5bb0a4855.jpg)
![bitcoinunix01](https://user-images.githubusercontent.com/40539492/60734949-da134300-9f7b-11e9-99a4-1f24fa6d4933.jpg)


Let me know if you want me to change anything. Also let me know if I did a mistake in the way I introduced this change, I am new, it is my first submission.

**Comment by JosuGZ** [comment]
> I think it is a very important update, look at what the look of the UI for windows. Did you run a windows wallet once? it is awful.

Awfulness is a very subjective matter. I don't like the frames, but I agree that something should be added. I like the elevation concept of Android, or some kind of "cards".

**Comment by laanwj** [comment]
I like the simple, monochrome icons. The 3D-ish shadowed icons seem a bit 1990'ish to me, personally.

For some perspective: this is serious, safety critical software, with potentially millions of dollars irrevocably at stake for a single wrong action. Having "a cool GUI" is not an aim. Like with industrial GUIs, boring is fine. The main aim of the GUI is to make common tasks easy and to prevent mistakes.

So for those wanting to improve the UI: please work on accessibility, usability and such.

**Comment by MarcoFalke** [comment]
There seems to be disagreement about those "visual improvements", so I am closing this for now.
