### ISSUE TITLE
Cross compilation bitcoin win64 on Ubuntu fail because QT5 headers missing

### ISSUE THREAD

**Issue by NicolasChoukroun** [bitcoin/bitcoin#16316]
Bitcoin 0.18 / Ubuntu 0.18.2
Trying to cross compile on Linux for Windows.

When I execute **configure** everything is fine except for QT

```
checking QtPlugin usability... no
checking QtPlugin presence... no
checking for QtPlugin... no
configure: WARNING: QtCore headers missing; bitcoin-qt frontend will not be built

```

The wallet cannot be compiled because of missing QT5. I have installed QT5 in many different ways, I have qmake in the path.

Is there anyone else with this problem? Is there a way to fix it?

**Comment by NicolasChoukroun** [comment]
I have found the problem.
Depending on the Linux install you chose, you may have QT5 and QT4 already installed

Doing

'sudo apt autoremove '.*qt5.*-dev'
sudo apt autoremove '.*qt4.*-dev'
'
Fixes the problem

**Comment by janus** [comment]
> I have found the problem.
> Depending on the Linux install you chose, you may have QT5 and QT4 already installed
> 
> Doing
> 
> ```
> sudo apt autoremove '.*qt5.*-dev'
> sudo apt autoremove '.*qt4.*-dev'
> ```
> 
> then install the depends fixes the problem

@NicolasChoukroun  Please I am having the same problem. And I tried the commands above , my system could not locate them.
