### ISSUE TITLE
systemd docs correctness 

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#16346]
It seems this part of [doc/init.md](https://github.com/bitcoin/bitcoin/blob/master/doc/init.md):
> At a bare minimum, bitcoind requires that the rpcpassword setting be set when running as a daemon. If the configuration file does not exist or this setting is not set, **bitcoind will shut down promptly after startup**.

is no longer the true. Or did I miss something?

**Comment by MarcoFalke** [comment]
You can check when the documentation was added (`git blame` or `git log -S 'some string'`), and then read the source code for that commit:

https://github.com/bitcoin/bitcoin/blob/234bfbf6a5fcba37e510e9cb6c1f2a629cd0290e/src/rpcserver.cpp#L542

To find out when that error was removed, you can run `git log -S 'some string'` again:

```sh
git log -S 'rpcpassword in the configuration f'
```

It will spit out 71cbeaad9a929ba6a7b62d9b37a09b214ae00c1a

**Comment by emilengler** [comment]
I setted up a bitcoind on systemd a week ago.
The server parameter was not enabled therefore an rpcpassword was not set and it worked like a charm (for systemd conditions)

**Comment by jkcd** [comment]
Raised a PR [18157](https://github.com/bitcoin/bitcoin/pull/18157) to fix it.
