### ISSUE TITLE
Unable to cross compile for Mac OS 

### ISSUE THREAD

**Issue by BlockMechanic** [bitcoin/bitcoin#16369]
On ubuntu 18.04 , After running 

make HOST=x86_64-apple-darwin11

 I get :- 

Configuring native_cdrkit...
Configuring Cdrkit, version 1.1.11
CMake Error at wodim/CMakeLists.txt:18 (MESSAGE):
  Error: found a Linux system but no libcap header.  Install libcap-dev.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

Any idea what may be going wrong?

**Comment by BlockMechanic** [comment]
Hello, anyone >?

I've tried various methods of install libcap and still no progress

**Comment by BlockMechanic** [comment]
Updated , anyone help, please !

**Comment by MarcoFalke** [comment]
Which commit/branch are you compiling?

**Comment by MarcoFalke** [comment]
Also, exact steps to reproduce

**Comment by BlockMechanic** [comment]
I was building from master 

sudo apt install ca-certificates curl g++ git pkg-config autoconf librsvg2-bin libtiff-tools libtool automake faketime bsdmainutils cmake imagemagick libcap-dev libz-dev libbz2-dev python3 python3-dev python3-setuptools fonts-tuffy libcap-dev
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
make HOST=x86_64-apple-darwin11 DARWIN_SDK_PATH=$PWD/MacOSX10.11.sdk -j4

It completely fails there .

**Comment by BlockMechanic** [comment]
Deleting the offending lines allowed the build to continue, will test later tonight if the binaries work without issue.

**Comment by BlockMechanic** [comment]
closing for lack of interest

**Comment by ongygy2000** [comment]
I DO NOT CARE
