### ISSUE TITLE
depends: File-based logging for individual packages

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#16368]
We should have file-based logging for each depends package so that:

1. We can diff logs to spot regressions when changing our build script / updating packages.
2. Travis has a line limit for output, so when running on Travis, we could withhold logs until we notice a non-zero exit code, then print `stdout`/`stderr`.

**Comment by dongcarl** [comment]
Related: https://github.com/bitcoin/bitcoin/issues/16354

**Comment by fanquake** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
@dongcarl This "good first issue" is open for almost a year. Maybe people are missing hints and pointers how this can be solved?

**Comment by MarcoFalke** [comment]
(Sorry, I just realized I made this a good first issue, not you)

**Comment by MarcoFalke** [comment]
If someone works on this issue, it might be good to also revert the hacky workaround in commit fa0cc02c0a029133f080680ae9186002a144738f

**Comment by hebasto** [comment]
@MarcoFalke 
> If someone works on this issue, it might be good to also revert the hacky workaround in commit [fa0cc02](https://github.com/bitcoin/bitcoin/commit/fa0cc02c0a029133f080680ae9186002a144738f)

Done in #19952.
