### ISSUE TITLE
Early shutdown results in freeze (torControlThread not stopping)

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#16376]
Using Ubuntu 18.04.2 LTS, with up-to-date, self-compiled master.
When I run
`./bitcoind -regtest -whitebind=bla`
I expect a clean shutdown with `Error: Cannot resolve -whitebind address: 'bla'`.
However sometimes my node doesn't stop and freezes (shutdown never finishes). 
This happens ~30% of the time for me, both on testnet and regtest. 

I believe that this is because `torControlThread.join();` never returns if it the thread is stopped right after its creation - it is started right before the whitebind part in `AppInitMain()`. If I insert a sleep before whitebind parameters are processed in Step 12 of `AppInitMain()` (or if I just disable the TorControl thread) the error does not occur.

Could someone try to reproduce? I encountered this testing #16248, but it is not restricted to this branch.

**Comment by ajtowns** [comment]
I've seen the "node gets stuck in shutdown" thing myself, caused by the "get dns peers" thread taking forever. If you check in debug.log, you should see "dnsseed thread start" without a corresponding "dnsseed thread exit". I think if you wait about 5 minutes you should see it finish up.

**Comment by mzumsande** [comment]
In my case it's not dnsseed, which has not been launched at the point of startup where the shutdown happens, plus I've been waiting for 30 minutes without anything happening. But of course the root cause could be related.

**Comment by ajtowns** [comment]
Yeah, I think there's a race if shutdown happens early:

    init                       torcontrol
    StartTor()
      event_base_new()
      std::thread()
    InterruptTor()
      event_base_loopbreak()
                               TorControlThread()
                                    TorController()
                                    event_base_dispatch()
    StopTorControl()
      torControlThread.join()    

If `_loopbreak` is called before `_dispatch` has started, it won't have any effect. Calling `event_base_loopexit(gBase,nullptr)` instead (or as well) seems like it fixes it.

**Comment by promag** [comment]
I also hit the "hang" regarding dnsseed thread: https://github.com/bitcoin/bitcoin/issues/15657#issuecomment-475965674

I'll try to reproduce the race.

**Comment by ajtowns** [comment]
I found it reproduced pretty easily on master by invoking bitcoind with `-proxy=127.0.0.1:9050 -listen=1 -bind=127.0.0.1 -whitebind=127.0.0.1:0` fwiw.

**Comment by sriharikapu** [comment]
thanks @ajtowns this works perfectly fine for me `bitcoind -proxy=127.0.0.1:9050 -listen=1 -bind=127.0.0.1 -whitebind=127.0.0.1:0`
