### ISSUE TITLE
Zmq Questions about Block Rollback

### ISSUE THREAD

**Issue by Rui2guo** [bitcoin/bitcoin#16372]
hello,
I'd like to ask ZMQ whether block monitoring for bitcoin will process rollback blocks into queues
for example：
 I found that ZMQ hashblock listener did not listen for the correct hash of the rollback block.
Original Chain： 590482 -->590483 --->590484
Normal occurrence block rollback chain:590482 -->590483(roll) --->590484(roll)-->590485--->(......)
ZMQ is not acquired the 590483(r) 590484(r) blockhash ,but the blockhash of 590485 is acquired. the old 590483 590484 is acquired
Does Bitcoin ZMQ not support this?

**Comment by FndNur1Labs** [comment]
Is this for fixed indexed or block check point?

**Comment by Rui2guo** [comment]
> Is this for fixed indexed or block check point?

yes,this is block index, imply put, the rollback block will not be retrieved via ZMQ

**Comment by promag** [comment]
I could be missing something but looking at `CChainState::ActivateBestChain` you can see that `NotifyBlockTip` is only called for the tip of the reorg. Maybe you should "walk backwards" from that new tip until you find an already known block?

**Comment by promag** [comment]
After all this behavior is expected and documented in https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md#remarks, quoting:

> Note that when the block chain tip changes, a reorganisation may occur and just the tip will be notified. It is up to the subscriber to retrieve the chain from the last known block to the new tip.

You can close this.

**Comment by promag** [comment]
FYI #16404.
