### ISSUE TITLE
[Feature] Get utxos for non-wallet addresses

### ISSUE THREAD

**Issue by mikemilla** [bitcoin/bitcoin#16388]
Hey team,

Adding a feature request here for the ability to query all utxos for a given address(s) regardless if it's in the nodes wallet or not.

I understand the reasoning here of why it's not included out-of-the-box as it could add a significant amount of overhead to the core requirements of running the node.

However, it's fairly concerning that the most of the articles about how to get this functionality just point to using an external api to fetch this info. Tutorials of how to get this functionality on the developer side are also painful when just trying to get this fairly common feature up and running. Isn't part of the point of running a full node to be able to get anything you need without the reliance of a third party? "Don't trust, verify"

I would imagine the best implementation for this would be to add a flag in the `bitcoin.conf` of something like `indexAddrs=1` or something like that.

Anyway, just putting the idea out there. Thanks

**Comment by achow101** [comment]
You can use the `scantxoutset` RPC to do this already.

**Comment by mikemilla** [comment]
> You can use the `scantxoutset` RPC to do this already. This will give you all UTXOs for an address or a descriptor. I **will not** scan the blockchain for all transactions or transaction outputs for it, just the UTXO set.

Ok sweet! How would I write something like this then? `bitcoin-cli scantxoutset  muXQpwvT2NNEXB5keSPmaPFnKpTnR2ZSNV`

I've tried many different ways of writing this command but can't seem to get it correct.

**Comment by jb55** [comment]
mikemilla:

`utxo () { bitcoin-cli scantxoutset start '["'"addr($1)"'"]'`

```
$ utxo 34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
[..]
  "total_amount": 165204.35005579
}
```

**Comment by mikemilla** [comment]
@jb55 looking for a basic command line example. Tried about 2 dozen different implementations of your snippet.

**Comment by promag** [comment]
Try
```
bitcoin-cli scantxoutset start '["addr(34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo)"]'
```

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by mikemilla** [comment]
@promag I tried that several times and it didn't return anything.

**Comment by promag** [comment]
Please open an issue in stackexchange and provide more detailed information, like version used, output of commands etc.

**Comment by mikemilla** [comment]
For those still curious about this. I was able to get a node running and connected to a javascript app. Here is the command that will work with bitcoin-core via javascript.

https://www.npmjs.com/package/bitcoin-core

```
const utxos = await client.command('scantxoutset', 'start', ['addr(some_valid_address), addr(some_valid_address)'])
```
