### ISSUE TITLE
sendrawtransaction maxfeerate is interpreted as absolute fee by default

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16382]
When the newly introduced `"maxfeerate"` option is not passed, the default fee rate is interpreted as an absolute amount. However, when it is passed, it is interpreted as a fee rate. Thus, the rpc will return different results when the value is explicitly set to the default.

See

https://github.com/bitcoin/bitcoin/blob/536590f358dc3d3e5821eba7f1009452ea93b205/src/rpc/rawtransaction.cpp#L797-L807

I think we should change it back to an absolute value in BTC (not a feerate)

This was changed to a feerate by @kallewoof, so ping him to see if there was a specific reason to switch.

**Comment by MarcoFalke** [comment]
I guess I don't feel strongly whether it should be a feerate or absolute amount. Most importantly it should be consistent.

**Comment by jasoncadahia** [comment]
Sorry, I'm new - how can you tell what happens when `maxfeerate` is not passed? I'm assuming `maxfeerate` is the same thing as `params[1]`, and that we'd need see what happens when `request.params[1].isNull()` is true to know this. Again, sorry I'm new (and not the most experienced programmer either).

**Comment by FndNur1Labs** [comment]
I think put not bigger. Except for faster confirmation.

**Comment by promag** [comment]
For reference #13541.

Good catch. By consistent you mean that in `testmempoolaccept` it should also be absolute amount?

**Comment by kallewoof** [comment]
I don't think it's inconsistent. There is a default max fee that is set in the system, and the user can override it with a fee rate. Forcing the user to guess the size of the transaction in order to hit 1 sat/byte (or whatever they're aiming for) is counterproductive.

**Comment by MarcoFalke** [comment]
> I don't think it's inconsistent.

@kallewoof The help text currently says that the default is `0.10 BTC/kB`, the code says that the default is `0.10 BTC`. This is clearly inconsistent.

```
2. maxfeerate    (numeric or string, optional, default=0.10) Reject transactions whose fee rate is higher than the specified value, expressed in BTC/kB.
                 Set to 0 to accept any fee rate.

**Comment by kallewoof** [comment]
You're correct, that is indeed inconsistent.
