### ISSUE TITLE
Properly handle sscanf return value in ./src/secp256k1/src/tests.c

### ISSUE THREAD

**Issue by mustaphaabiola** [bitcoin/bitcoin#16385]
A bug exists which allows the `sh` variable to be used uninitialized when sscanf returns EOF.

Observe:

https://github.com/bitcoin/bitcoin/blob/536590f358dc3d3e5821eba7f1009452ea93b205/src/secp256k1/src/tests.c#L5019-L5040

A simple fix would be to explicitly test if sscanf's return value is equal to 1.

**Comment by fanquake** [comment]
Please send any issues in relation to secp256k1 to the upstream repository: https://github.com/bitcoin-core/secp256k1.
