### ISSUE TITLE
test_runner: failfast option leaves orphaned bitcoind instances running

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#16395]
It seems that when test_runner is run with `--failfast` and fails, it leaves the bitcoinds it started running still.

**Comment by MarcoFalke** [comment]
Currently `--failfast` will kill the python subprocesses, so they don't have time to kill their subprocesses

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
