### ISSUE TITLE
build: configure doesn't pickup Qt if depends is built with DEBUG=1

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16391]
Using `master` (536590f358dc3d3e5821eba7f1009452ea93b205) and building depends using `DEBUG=1 make -j8`.

Configuring with `./autogen.sh && ./configure --prefix=/Users/michael/github/bitcoin/depends/x86_64-apple-darwin18.6.0` I'm seeing:
```bash
Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = yes
  with test     = yes
    with fuzz   = no
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  sanitizers    = 
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = darwin
  build os      = darwin
```

In `config.log`:
```bash
configure:27984: checking for static Qt plugins: -lqcocoa
ld: library not found for -lqcocoa
configure:27813: checking for static Qt plugins: -lqminimal
ld: library not found for -lqminimal
configure:27839: WARNING: Could not resolve: -lqminimal; bitcoin-qt frontend will not be built
```

Building depends without `DEBUG=1` works as expected.

**Comment by hebasto** [comment]
Tested on current `master` (646f0ada0205ae4b3952107e3b1542f06adda32b).

Can confirm such behavior on macOS 10.14:
```
$ clang --version | head -2
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.0.0
```

Everything works fine on Linux Mint 19.3:
```
$ gcc --version | head -1
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

It seems this issue is macOS-specific.

**Comment by hebasto** [comment]
@fanquake Mind looking into #18298?

**Comment by Sjors** [comment]
I can reproduce this is issue on macOS 10.15.5 (master: 265492723a6874abc542361e4693840240e7d2ef), will try @hebasto's PR.
