### ISSUE TITLE
fundrawtransaction returns "Insufficient funds" while it has funds in listunspent

### ISSUE THREAD

**Issue by stevenroose** [bitcoin/bitcoin#16396]
I've been struggling with this for a bit and decided to try it manually. Here are the steps I made:
https://gist.github.com/stevenroose/b7d60c44d5235ac4d98dbdbf4442210b

Relevant: https://github.com/bitcoin/bitcoin/issues/7879, https://github.com/bitcoin/bitcoin/issues/14405

**Comment by shesek** [comment]
I believe the address needs to be imported with its pubkey/spk in order to be `solvable` and to be used by `fundrawtransaction`.

**Comment by instagibbs** [comment]
that or import the pubkey as well using `importpubkey`.

**Comment by stevenroose** [comment]
I think clarifying that the pubkey is needed is enough: https://github.com/bitcoin/bitcoin/pull/16397

**Comment by MarcoFalke** [comment]
This has been fixed in 79aeed8e76e8bc70722e6178678b0b3840694d5c?
