### ISSUE TITLE
"privacy mode" in QT

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#16407]
Pulling up QT around other people can be quite revealing if the wallet is proudly displaying your balance by default.

I wonder if there could be a way to slightly obscure this, with an option to at least obscure the amounts until turned off.

I have no UI insights here, just opening this up to brainstorming.

**Comment by promag** [comment]
Concept ACK. Only in the overview?

**Comment by instagibbs** [comment]
That's my thought yes.

**Comment by jonasschnelli** [comment]
Concept ACK

**Comment by fanquake** [comment]
Concept ACK. There are a few different approaches we could try:

- A setting that obscures balances by default, unless moused over.
- A setting that blurs the entire overview page unless you are active in the window. Then you could mouse "out" from the view if you wanted a quickly blurred screen.

Qt has graphical effects, so maybe we could take advantage something like [FastBlur](https://doc.qt.io/qt-5/qml-qtgraphicaleffects-fastblur.html)? More effects info is available [here](https://doc.qt.io/qt-5/graphicaleffects.html).

**Comment by promag** [comment]
Those effects don't work with widgets.

**Comment by achow101** [comment]
Wasabi Wallet's privacy mode replaces everything with a fixed number of `#`s to hide the actual values. This mode is activated by a button in the main UI.

**Comment by hebasto** [comment]
Concept ACK
