### ISSUE TITLE
bitcoin-qt QXcbConnection: Could not connect to display (bitcoin ppa)

### ISSUE THREAD

**Issue by WalletCat** [bitcoin/bitcoin#16423]
After the installation process I receive a notification
```
"Warning: The home dir /var/lib/bitcoin you specified can't be accessed: No such file or directory
Adding system user `bitcoin' (UID 113) ...
Adding new group `bitcoin' (GID 122) ...
Adding new user `bitcoin' (UID 113) with group `bitcoin' ...
Not creating home directory `/var/lib/bitcoin'.
bitcoind.service is a disabled or a static unit, not starting it. "
```

I started opening bitcoin-qt unsuccessfully
```
" sudo bitcoin-qt
QXcbConnection: Could not connect to display
Aborted (core dumped)"
```

I'm using Ubuntu 16.04
user sudo but not root
Is there any way to solve this problem?

**Comment by hebasto** [comment]
@WalletCat What is the source of the package you installed?

**Comment by WalletCat** [comment]
> @WalletCat What is the source of the package you installed?
```
sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get install bitcoin-qt
```
I installed with PPA

**Comment by hebasto** [comment]
Cannot reproduce the issue:
```bash
$ bitcoin-qt -version | grep version
Bitcoin Core version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65 (64-bit)
```

@WalletCat Could you provide your output of `bitcoin-qt -version | grep version`?

**Comment by WalletCat** [comment]
> ```shell
> bitcoin-qt -version | grep version
> ```
Is there any other way to install new?
Pls help me

**Comment by hebasto** [comment]
@WalletCat 
> Is there any other way to install new?
> Pls help me

https://bitcoincore.org/en/download/

**Comment by hebasto** [comment]
@MarcoFalke It seems this could be closed.

**Comment by MarcoFalke** [comment]
@WalletCat The ppa is unmaintained (at least for now). You might want to try the Bitcoin Core snap or flatpak:

* https://snapcraft.io/bitcoin-core
* https://flathub.org/apps/details/org.bitcoincore.bitcoin-qt

**Comment by laanwj** [comment]
> " sudo bitcoin-qt

also it's a bad idea to run a X program with sudo, I don't think it passes through the DISPLAY and such, also there is no reason why you'd run bitcoind or -qt as root
