### ISSUE TITLE
New to Bitcoin Core

### ISSUE THREAD

**Issue by Jorgesanchez1984** [bitcoin/bitcoin#16446]
Hello there I'm a little lost here and wondering if you can help. 

I thought BitcoinCore was a plug and play set up for receiving BTC for validation of a bitcoin transaction between two people. 

However I did not know there was more steps to this. Wonder if anyone have insight and can lend me there time and helping me through this? Not sure where to look or what to read. 

I download BitcoinCore and downloaded the whole network. And obtained my wallet. What's next in order to validate BTC transactions?

I currently have this set up through windows 10

**Comment by fanquake** [comment]
Hi. This issue tracker is not for general questions about bitcoin, nor usage questions about Bitcoin Core. Depending on what questions you have, the [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) might be a good to find the answers.

**Comment by michaelfolkson** [comment]
Hey @Jorgesanchez1984. Agreed with @fanquake this isn't the right forum for these kind of questions. The Bitcoin Stack Exchange is a great resource for researching Bitcoin Core usage as is [bitcoin.org](https://bitcoin.org/en/bitcoin-core/) or the Bitcoin [wiki](https://en.bitcoin.it/wiki/Running_Bitcoin). I'm also happy to answer questions if you DM me on the Bitcoin Core Slack or IRC. You can join the Bitcoin Core Slack [here](https://bitcoincoreslack.herokuapp.com/).
