### ISSUE TITLE
build: Investigate building default lib XCB extensions

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16447]
As pointed out [here](https://github.com/bitcoin/bitcoin/pull/16370/files#r306442184):

> It seems that we build all of the default XCB Extensions, but the -qt-xcb option we supply to QT might cause it to build them as well. (source: https://doc.qt.io/qt-5.9/linux-requirements.html)

Investigate if there is build duplicate, if we should stop building them etc.

**Comment by theuni** [comment]
+1, looks like it should be fine to skip them.
