### ISSUE TITLE
BTC 0.18 Node

### ISSUE THREAD

**Issue by 1326633265** [bitcoin/bitcoin#16456]
Why can't docker use RPC commands directly through mount ports, as in previous versions? Does bitcoin.conf need special configuration?

**Comment by fanquake** [comment]
Likely related to configuration option changes in `v0.18.0`, please check the release notes: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#configuration-option-changes.

**Comment by 1326633265** [comment]
I checked it, but the document is not clear. I've tried to follow the documentation tips, but I haven't solved the problem.

**Comment by 1326633265** [comment]
I checked it, but the document is not clear. I've tried to follow the documentation tips, but I haven't solved the problem.

**Comment by MarcoFalke** [comment]
What are the steps to reproduce, what is the error message, have you seen #16209 ?

**Comment by fanquake** [comment]
@1326633265 Can you follow up here.

**Comment by MarcoFalke** [comment]
Closing for now, let me know if this is still an issue
