### ISSUE TITLE
Crashing on Linux (Raspberry Pi)

### ISSUE THREAD

**Issue by spogulis** [bitcoin/bitcoin#16473]
**What behavior did you expect?**
Bitcoin keeps running on my Raspberry Pi 4 (2GB RAM)

**What was the actual behavior (provide screenshots if the issue is GUI-related)?**
Every day it has to be rerun multiple times due to crashing with the error:
"terminate called without an active exception"

**How reliably can you reproduce the issue, what are the steps to do so?**
Just turn it on and wait for hours I guess.

**What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?**
Bitcoin Core version v0.18.0
Got it from https://bitcoin.org/en/bitcoin-core/

**What type of machine are you observing the error on (OS/CPU and disk type)?**
Raspberry Pi 4 with external 1TB HDD.
 
**For the GUI-related issue on Linux provide names and versions of a distro, a desktop environment and a graphical shell (if relevant).**
Latest Raspbian distributive.

**Comment by MarcoFalke** [comment]
Does it OOM?

You can check the tail of `dmesg` for something like `[3884669.536501] Killed process 1493 (bitcoin-init) total-vm:1494520kB, anon-rss:494564kB, file-rss:0kB`

**Comment by kristapsk** [comment]
You run Raspbian Lite (console only) or with a GUI? With Lite, without GUI, even RPi 3 with 1 GB RAM (+ swapfile on external HDD) should be ok ([here's one step-by-step guide](https://stadicus.github.io/RaspiBolt/)). With a GUI, RAM could be the issue, I assume, but you should see some messages about that by looking at the output of `dmesg` command, as was suggested above.

**Comment by spogulis** [comment]
Thanks a lot, I was running with GUI but now, after following that excellent guide, headless setup is working great!
