### ISSUE TITLE
Running './configure' on external hard drive fails

### ISSUE THREAD

**Issue by dannmat** [bitcoin/bitcoin#16478]
When cloning Bitcoin Core and trying to configure/build, I get the error:
`./configure: line 1: syntax error near unexpected token ('`

Building from the boot disk works as expected, but if I replicate these steps exactly on my external hard drive, I get the above error

I expected the configure file to generate a makefile

Try building with MacOS 10.15 beta (build 19A512f) on an external 1TB hard drive.

Running the latest clone from GitHub (latest commit 94df084)

2015 MacBook Pro 15"

**Comment by MarcoFalke** [comment]
Does the path have spaces in it?

**Comment by dannmat** [comment]
Tried again without any spaces in the path and still the same error.
The drive is partitioned as exFat.

**Comment by dannmat** [comment]
The error is also including: 
`./configure: line 1: m4trace:configure.ac:12: -1- AC_INIT([Bitcoin Core], [0.18.99], [https://github.com/bitcoin/bitcoin/issues], [bitcoin], [https://bitcoincore.org/])'`

I have tried running ./configure --without-gui however this brings back the same result.

**Comment by MarcoFalke** [comment]
What does the `config.log` say?

**Comment by MarcoFalke** [comment]
And have you (re-) run `./autogen.sh`?

**Comment by dannmat** [comment]
I have re-run that `./autogen.sh`. I have also tried completely wiping the drive and starting fresh but to no avail. Following the same steps on my boot drive works perfectly however.
It fails when I'm running ./configure (I'm following [Bitcoin Core MacOS tutorial](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md) )

I can't find any config.log or debug.log anywhere in the directory?

**Comment by MarcoFalke** [comment]
Hmm, maybe the `./config.log` isn't created yet. So what is the full output of `./autogen.sh && ./configure`?

**Comment by laanwj** [comment]
> The drive is partitioned as exFat

(ex)Fat is a very minimal file system, it likely misses some metadata, such as file permissions necessary to do the build.

**Comment by dannmat** [comment]
Running `./autogen.sh` give me the following output:

```
matt@Matts-MacBook-Pro bitcoin % ./autogen.sh 
matt@Matts-MacBook-Pro bitcoin % 
```

No errors occur, however when I then run `./configure` or `./configure --without-gui`, I get the following output:

```
matt@Matts-MacBook-Pro bitcoin % ./configure
./configure: line 1: syntax error near unexpected token `('
./configure: line 1: `m4trace:configure.ac:12: -1- AC_INIT([Bitcoin Core], [0.18.99], [https://github.com/bitcoin/bitcoin/issues], [bitcoin], [https://bitcoincore.org/])'
```

I have tried re-formatting the drive to FAT32 but still get the same issue.

I will try on a different Mac tonight and try to replicate the issue.

**Comment by laanwj** [comment]
FAT32 has the same problem, it's an older revision of FAT. You need a 'real' file system.

**Comment by dannmat** [comment]
I formatted using Mac OS Extended, and this works flawlessly now. Thanks for your help.

Is this something that should be looked into or is it beyond control?

**Comment by fanquake** [comment]
@dannmat This is likely something out of our control. Thanks for following up.
