### ISSUE TITLE
bitcoin 0.18 version rpc question

### ISSUE THREAD

**Issue by caiyaonan** [bitcoin/bitcoin#16482]
[config]
server=1
listen=1
rpcuser=myuser
rpcpassword=mypassword
rpcport=19914
rpcallowip=myip
rpcbind=127.0.0.1
rpcbind=myip
#paytxfee=0.0001

i write rpcport rpcallowip rpcallowip rpcbind, but system print error Binding RPC on address 116.21.17.197 port 19914 failed. @chanhosuh @mrbianchi help

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#configuration-option-changes

**Comment by caiyaonan** [comment]
i have try it, but wrong again, so i use 0.17 version,  Is ok. 

> https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#configuration-option-changes

**Comment by mrbianchi** [comment]
Why you tagged me?
You should allowip is de IP where you want to connect from(IP rpc client)
And bind should be the IP that is hosting the node (IP rpc server)

**Comment by laanwj** [comment]
Please use the bitcoin stack exchange or other forums for usage questions, not the github.

**Comment by caiyaonan** [comment]
bitcoin-core 0.1.8 version readme Indistinct expression
