### ISSUE TITLE
bumpfee.TotalFee removed without replacement

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16485]
https://github.com/bitcoin/bitcoin/pull/15996#issuecomment-515997520

**Comment by instagibbs** [comment]
`confTarget`? Or you mean more like https://github.com/bitcoin/bitcoin/issues/16203 ?
 
If we think it's a mistake to remove a feature, then it shouldn't matter if there's a direct feerate replacement anyways, and it should be reverted.

**Comment by instagibbs** [comment]
Probably the best point in favor of not removing it: https://github.com/bitcoin/bitcoin/pull/15996#issuecomment-501706266

to which I responded essentially "power users don't need that RPC call at all if they're manually calculating package rates"

**Comment by MarcoFalke** [comment]
> Probably the best point in favor of not removing it: #15996 (comment)

This overlaps a bit with 
*  Implement auto-fee leveling when spending unconfirmed outputs #15553 


I'd say it can be solved by an optional flag, that indicates if the target fee rate should be for the tx that is bumped or for the package

**Comment by Sjors** [comment]
I'm fine with removing `totalFee` once `feeRate` is there, see #16203.

Note that `totalFee` is deprecated, but not removed. Though I agree it's also odd to deprecate something before there's a replacement.

**Comment by MarcoFalke** [comment]
At the very least it should be possible to switch back and forth between two major releases without having to re-adjust the API every time. Deprecating something without replacement is breaking that.

**Comment by instagibbs** [comment]
I'll try to push to get #16492 in master then to avoid any issues or need for reversion.

**Comment by instagibbs** [comment]
https://github.com/bitcoin/bitcoin/pull/16727 is pretty much sitting there waiting for more review. Probably a little late for feature freeze, maybe not though? Might be able to get the band together to squeeze it in.

**Comment by instagibbs** [comment]
This has been resolved by https://github.com/bitcoin/bitcoin/pull/16727 which is now merged
