### ISSUE TITLE
build blockchain based on Mastering bitcoin book

### ISSUE THREAD

**Issue by cezarexi** [bitcoin/bitcoin#16480]
I started learning how to build a blockchain from Antonopoulos book using Git Bash and i have a problem. 

I used commands: 
git clone github.com/bitcoin/bitcoin.git 
cd bitcoin 
![scre](https://user-images.githubusercontent.com/39422375/62013027-aea40280-b18d-11e9-81b2-7925597556a6.png)

git tag 
git checkout v0.11.2 

and when i try to use command ./autogen.sh on the screen appear information:

 ./autogen.sh: line 9: autoreconf: command not found.

Where is the problem? What i do wrong? i need some libraries?

**Comment by fanquake** [comment]
See the [windows build notes](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md) for information about building on Windows. I'd also suggest building a more recent tag.
