### ISSUE TITLE
test_runner can't detect a breakpoint encountered in test

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#16495]
Sometimes I leave pdb breakpoints during test iteration and forget them, resulting in lots of `......` printed with no satisfaction until I grep and realize which test I left it in.

I think it'd be fine for a test to auto-fail if it hits `pdb.set_trace()`, for example.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by instagibbs** [comment]
test_runner.py now prints what tests are still running near the end, making this a lot simpler to diagnose and fix, closing is great :+1:
