### ISSUE TITLE
State of the Repo Report, July 2019

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#16506]
# State of the Repo Report, July 2019

## Introduction

For all fans of statistics – enjoy! 🤓

790 (+5) authors have contributed to the project (merged contributions). Thank you! ❤️

The repo contains 490&nbsp;143 (+2 199) lines of text and 1&nbsp;761 (+23) files.

20&nbsp;902 (+290) commits have been made of which 4&nbsp;020 (+103) are merge commits.

There are currently 277 (-10) open pull requests from in total 84 contributors.

If all open pull requests were merged the project line count would grow by roughly 6 percent.

The total set of open pull requests adds 54&nbsp;678&nbsp;lines, removes 20&nbsp;560&nbsp;lines and touches 2&nbsp;172&nbsp;distinct files.

The "median open pull request" adds 59&nbsp;lines, removes 18&nbsp;lines and touches 4&nbsp;files.

Previous edition: [State of the Repo, June 2019](https://github.com/bitcoin/bitcoin/issues/16298)

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines added | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 7&nbsp;910&nbsp;(14%) | -1&nbsp;894 | 6&nbsp;016 | 160 | 11&nbsp;(4%) |
| 2 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 5&nbsp;952&nbsp;(11%) | -785 | 5&nbsp;167 | 82 | 16&nbsp;(6%) |
| 3 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 4&nbsp;536&nbsp;(8%) | -2&nbsp;205 | 2&nbsp;331 | 70 | 6&nbsp;(2%) |
| 4 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 3&nbsp;642&nbsp;(7%) | -517 | 3&nbsp;125 | 38 | 11&nbsp;(4%) |
| 5 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 3&nbsp;263&nbsp;(6%) | -414 | 2&nbsp;849 | 97 | 25&nbsp;(9%) |
| 6 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 2&nbsp;559&nbsp;(5%) | -770 | 1&nbsp;789 | 39 | 3&nbsp;(1%) |
| 7 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 1&nbsp;986&nbsp;(4%) | -318 | 1&nbsp;668 | 65 | 6&nbsp;(2%) |
| 8 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 1&nbsp;794&nbsp;(3%) | -756 | 1&nbsp;038 | 53 | 13&nbsp;(5%) |
| 9 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 1&nbsp;738&nbsp;(3%) | -1&nbsp;642 | 96 | 12 | 6&nbsp;(2%) |
| 10 | [sdaftuar](https://github.com/bitcoin/bitcoin/pulls/sdaftuar) | 1&nbsp;669&nbsp;(3%) | -984 | 685 | 25 | 4&nbsp;(1%) |
| 11 | [TheBlueMatt](https://github.com/bitcoin/bitcoin/pulls/TheBlueMatt) | 1&nbsp;594&nbsp;(3%) | -603 | 991 | 33 | 6&nbsp;(2%) |
| 12 | [MishraShivendra](https://github.com/bitcoin/bitcoin/pulls/MishraShivendra) | 1&nbsp;467&nbsp;(3%) | -41 | 1&nbsp;426 | 12 | 1&nbsp;(0%) |
| 13 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 1&nbsp;413&nbsp;(3%) | -1&nbsp;210 | 203 | 65 | 11&nbsp;(4%) |
| 14 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 1&nbsp;060&nbsp;(2%) | -796 | 264 | 25 | 6&nbsp;(2%) |
| 15 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 1&nbsp;002&nbsp;(2%) | -670 | 332 | 96 | 19&nbsp;(7%) |
| 16 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 988&nbsp;(2%) | -24 | 964 | 18 | 1&nbsp;(0%) |
| 17 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 908&nbsp;(2%) | -864 | 44 | 39 | 5&nbsp;(2%) |
| 18 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 881&nbsp;(2%) | -432 | 449 | 50 | 25&nbsp;(9%) |
| 19 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 828&nbsp;(2%) | -101 | 727 | 30 | 2&nbsp;(1%) |
| 20 | [ariard](https://github.com/bitcoin/bitcoin/pulls/ariard) | 819&nbsp;(1%) | -1&nbsp;018 | -199 | 23 | 5&nbsp;(2%) |
| 21 | [jimpo](https://github.com/bitcoin/bitcoin/pulls/jimpo) | 802&nbsp;(1%) | -23 | 779 | 12 | 1&nbsp;(0%) |
| 22 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 785&nbsp;(1%) | -321 | 464 | 35 | 6&nbsp;(2%) |
| 23 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 776&nbsp;(1%) | -792 | -16 | 60 | 3&nbsp;(1%) |
| 24 | [sipsorcery](https://github.com/bitcoin/bitcoin/pulls/sipsorcery) | 515&nbsp;(1%) | -1&nbsp;102 | -587 | 9 | 2&nbsp;(1%) |
| 25 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 478&nbsp;(1%) | -9 | 469 | 4 | 1&nbsp;(0%) |
| 26 | [NicolasDorier](https://github.com/bitcoin/bitcoin/pulls/NicolasDorier) | 450&nbsp;(1%) | -79 | 371 | 13 | 1&nbsp;(0%) |
| 27 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 351&nbsp;(1%) | -306 | 45 | 39 | 1&nbsp;(0%) |
| 28 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 328&nbsp;(1%) | -158 | 170 | 13 | 3&nbsp;(1%) |
| 29 | [LarryRuane](https://github.com/bitcoin/bitcoin/pulls/LarryRuane) | 323&nbsp;(1%) | -192 | 131 | 18 | 2&nbsp;(1%) |
| 30 | [l2a5b1](https://github.com/bitcoin/bitcoin/pulls/l2a5b1) | 299&nbsp;(1%) | -93 | 206 | 22 | 2&nbsp;(1%) |
| 31 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 299&nbsp;(1%) | -461 | -162 | 175 | 7&nbsp;(3%) |
| 32 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 285&nbsp;(1%) | -78 | 207 | 7 | 2&nbsp;(1%) |
| 33 | [theuni](https://github.com/bitcoin/bitcoin/pulls/theuni) | 271&nbsp;(0%) | -33 | 238 | 14 | 1&nbsp;(0%) |
| 34 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 261&nbsp;(0%) | -43 | 218 | 3 | 1&nbsp;(0%) |
| 35 | [benthecarman](https://github.com/bitcoin/bitcoin/pulls/benthecarman) | 182&nbsp;(0%) | -21 | 161 | 13 | 4&nbsp;(1%) |
| 36 | [jb55](https://github.com/bitcoin/bitcoin/pulls/jb55) | 161&nbsp;(0%) | -29 | 132 | 4 | 1&nbsp;(0%) |
| 37 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 135&nbsp;(0%) | -101 | 34 | 4 | 1&nbsp;(0%) |
| 38 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 131&nbsp;(0%) | -85 | 46 | 4 | 1&nbsp;(0%) |
| 39 | [ezegom](https://github.com/bitcoin/bitcoin/pulls/ezegom) | 130&nbsp;(0%) | -52 | 78 | 3 | 1&nbsp;(0%) |
| 40 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 117&nbsp;(0%) | -31 | 86 | 11 | 2&nbsp;(1%) |
| 41 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 116&nbsp;(0%) | -79 | 37 | 9 | 3&nbsp;(1%) |
| 42 | [mrwhythat](https://github.com/bitcoin/bitcoin/pulls/mrwhythat) | 116&nbsp;(0%) | -8 | 108 | 7 | 1&nbsp;(0%) |
| 43 | [emilengler](https://github.com/bitcoin/bitcoin/pulls/emilengler) | 110&nbsp;(0%) | -3 | 107 | 3 | 1&nbsp;(0%) |
| 44 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 101&nbsp;(0%) | -20 | 81 | 5 | 2&nbsp;(1%) |
| 45 | [MapleLaker](https://github.com/bitcoin/bitcoin/pulls/MapleLaker) | 89&nbsp;(0%) | -1 | 88 | 1 | 1&nbsp;(0%) |
| 46 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 86&nbsp;(0%) | -9 | 77 | 5 | 1&nbsp;(0%) |
| 47 | [IntegralTeam](https://github.com/bitcoin/bitcoin/pulls/IntegralTeam) | 79&nbsp;(0%) | -3 | 76 | 3 | 1&nbsp;(0%) |
| 48 | [greenaddress](https://github.com/bitcoin/bitcoin/pulls/greenaddress) | 78&nbsp;(0%) | -31 | 47 | 10 | 1&nbsp;(0%) |
| 49 | [darosior](https://github.com/bitcoin/bitcoin/pulls/darosior) | 75&nbsp;(0%) | -10 | 65 | 6 | 3&nbsp;(1%) |
| 50 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 72&nbsp;(0%) | -1 | 71 | 1 | 1&nbsp;(0%) |
| 51 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 71&nbsp;(0%) | -16 | 55 | 4 | 1&nbsp;(0%) |
| 52 | [gertjaap](https://github.com/bitcoin/bitcoin/pulls/gertjaap) | 54&nbsp;(0%) | -6 | 48 | 3 | 1&nbsp;(0%) |
| 53 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 42&nbsp;(0%) | -15 | 27 | 15 | 1&nbsp;(0%) |
| 54 | [meshcollider](https://github.com/bitcoin/bitcoin/pulls/meshcollider) | 41&nbsp;(0%) | -23 | 18 | 4 | 1&nbsp;(0%) |
| 55 | [shannon1916](https://github.com/bitcoin/bitcoin/pulls/shannon1916) | 39&nbsp;(0%) | -9 | 30 | 4 | 1&nbsp;(0%) |
| 56 | [tryphe](https://github.com/bitcoin/bitcoin/pulls/tryphe) | 32&nbsp;(0%) | -37 | -5 | 3 | 2&nbsp;(1%) |
| 57 | [kodslav](https://github.com/bitcoin/bitcoin/pulls/kodslav) | 31&nbsp;(0%) | -5 | 26 | 1 | 1&nbsp;(0%) |
| 58 | [Bushstar](https://github.com/bitcoin/bitcoin/pulls/Bushstar) | 30&nbsp;(0%) | -4 | 26 | 3 | 1&nbsp;(0%) |
| 59 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 30&nbsp;(0%) | -25 | 5 | 4 | 1&nbsp;(0%) |
| 60 | [pstratem](https://github.com/bitcoin/bitcoin/pulls/pstratem) | 30&nbsp;(0%) | -51 | -21 | 2 | 2&nbsp;(1%) |
| 61 | [jkczyz](https://github.com/bitcoin/bitcoin/pulls/jkczyz) | 25&nbsp;(0%) | -26 | -1 | 4 | 2&nbsp;(1%) |
| 62 | [LeandroRocha84](https://github.com/bitcoin/bitcoin/pulls/LeandroRocha84) | 24&nbsp;(0%) | -14 | 10 | 4 | 1&nbsp;(0%) |
| 63 | [lucayepa](https://github.com/bitcoin/bitcoin/pulls/lucayepa) | 24&nbsp;(0%) | -14 | 10 | 1 | 1&nbsp;(0%) |
| 64 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2 | 20 | 2 | 1&nbsp;(0%) |
| 65 | [tecnovert](https://github.com/bitcoin/bitcoin/pulls/tecnovert) | 22&nbsp;(0%) | -21 | 1 | 3 | 1&nbsp;(0%) |
| 66 | [marcoagner](https://github.com/bitcoin/bitcoin/pulls/marcoagner) | 21&nbsp;(0%) | -2 | 19 | 1 | 1&nbsp;(0%) |
| 67 | [amitiuttarwar](https://github.com/bitcoin/bitcoin/pulls/amitiuttarwar) | 18&nbsp;(0%) | -11 | 7 | 5 | 1&nbsp;(0%) |
| 68 | [asood123](https://github.com/bitcoin/bitcoin/pulls/asood123) | 16&nbsp;(0%) | -10 | 6 | 3 | 1&nbsp;(0%) |
| 69 | [JeremyRand](https://github.com/bitcoin/bitcoin/pulls/JeremyRand) | 15&nbsp;(0%) | -1 | 14 | 1 | 1&nbsp;(0%) |
| 70 | [icota](https://github.com/bitcoin/bitcoin/pulls/icota) | 15&nbsp;(0%) | -5 | 10 | 4 | 1&nbsp;(0%) |
| 71 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -3 | 8 | 1 | 1&nbsp;(0%) |
| 72 | [cryptogopher](https://github.com/bitcoin/bitcoin/pulls/cryptogopher) | 10&nbsp;(0%) | -1 | 9 | 1 | 1&nbsp;(0%) |
| 73 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 8&nbsp;(0%) | -3 | 5 | 3 | 1&nbsp;(0%) |
| 74 | [orientye](https://github.com/bitcoin/bitcoin/pulls/orientye) | 8&nbsp;(0%) | -2 | 6 | 2 | 1&nbsp;(0%) |
| 75 | [jonatack](https://github.com/bitcoin/bitcoin/pulls/jonatack) | 5&nbsp;(0%) | -7 | -2 | 2 | 1&nbsp;(0%) |
| 76 | [sp4ke](https://github.com/bitcoin/bitcoin/pulls/sp4ke) | 5&nbsp;(0%) | -3 | 2 | 1 | 1&nbsp;(0%) |
| 77 | [THETCR](https://github.com/bitcoin/bitcoin/pulls/THETCR) | 4&nbsp;(0%) | -5 | -1 | 1 | 1&nbsp;(0%) |
| 78 | [d3spwn](https://github.com/bitcoin/bitcoin/pulls/d3spwn) | 4&nbsp;(0%) | -2 | 2 | 2 | 1&nbsp;(0%) |
| 79 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 3&nbsp;(0%) | -4 | -1 | 1 | 1&nbsp;(0%) |
| 80 | [stevenroose](https://github.com/bitcoin/bitcoin/pulls/stevenroose) | 3&nbsp;(0%) | -2 | 1 | 1 | 1&nbsp;(0%) |
| 81 | [bpay](https://github.com/bitcoin/bitcoin/pulls/bpay) | 2&nbsp;(0%) | -2 | 0 | 1 | 1&nbsp;(0%) |
| 82 | [zenosage](https://github.com/bitcoin/bitcoin/pulls/zenosage) | 2&nbsp;(0%) | -3 | -1 | 2 | 1&nbsp;(0%) |
| 83 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 1&nbsp;(0%) | -2 | -1 | 1 | 1&nbsp;(0%) |
| 84 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6 | -6 | 2 | 1&nbsp;(0%) |

**Comment by fanquake** [comment]
Thanks.
