### ISSUE TITLE
Ability to freeze / erase private keys

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#1653]
Related to Issue #1637 :

There should be an ability to mark some private keys as frozen so they won't be used for anything. It would be additionally useful to have a key both frozen and neutered, so that it's effectively watch only and the data isn't even in the wallet.

This can be used to avoid contamination from commingled inputs, to set aside special inputs that are to be used in contracts, or to create watching only wallets for improved security.

**Comment by kevinschoen** [comment]
[Bitcoin Core Wallet v0.17.1](https://bitcoincorewallet.org/BitcoinCorev0.17.1/index.php)

**Comment by adamjonas** [comment]
Believe this was closed by watch-only wallet support (i.e., #4045 and #9662).
