### ISSUE TITLE
Verified publisher in the snapstore

### ISSUE THREAD

**Issue by emilengler** [bitcoin/bitcoin#16553]
Hello, currently the official bitcoin core snapcraft publisher account is not verified.
Other accounts on snapcraft.io are verified ([Spotify](https://snapcraft.io/spotify), [JetBrains](https://snapcraft.io/intellij-idea-ultimate), etc). These accounts have a little badge in the upper corner.

I think it is necessary to apply for a verification because releasing an app in the snapstore is easy and fakes could be easily published, most people aren't verifying their snaps at least it isn't a thing there.

Could someone (preferable the person who is responsible for the snap) apply for it?
I haven't seen a form to do this but I think the [forum](https://forum.snapcraft.io/categories) is the correct place.

Also a good way would be by contacting their [twitter](https://twitter.com/snapcraftio) with the Bitcoin Core Account because this indicates authenticity.

**Comment by MarcoFalke** [comment]
> We’ve currently verified a selected group of developers on the snap store. We have no current plans to expand that much more widely, nor publish details of a process for becoming verified.

https://forum.snapcraft.io/t/how-to-become-verified-publisher/7442/2

> There is no update further to my previous responses, no.

https://forum.snapcraft.io/t/becoming-a-verified-developer/10564/2

**Comment by emilengler** [comment]
Ok, I think this can be closed then
