### ISSUE TITLE
How to find the current fee to update my node?

### ISSUE THREAD

**Issue by krtschmr** [bitcoin/bitcoin#16552]
i know how to set the TX fee, but what is actually the best way to figure out, how many sats/vbyte it should be?

**Comment by laanwj** [comment]
There's the RPC command `estimatesmartfee` (see `bitcoin-cli help estimatesmartfee`) to get the current fee estimation. Note that the result is in BTC/kB so needs a conversion step to get sat/vbyte.

In general, please direct usage questions to the [bitcoin stack exchange](https://bitcoin.stackexchange.com/). Issues are for reporting issues.
