### ISSUE TITLE
depends : aarch64 android including QT 

### ISSUE THREAD

**Issue by BlockMechanic** [bitcoin/bitcoin#16568]
**Concept**
Based on work from :- https://github.com/bitcoin/bitcoin/pull/16110 aarch64 builds bitcoind and  following this example :- https://github.com/bitcoin/bitcoin/pull/13604 , I'm trying to build bitcoin core to use on android devices, like phones and tablets. Recent devices seem to have adaquate power and storage. In some cases users may also have repurposed devices that run android (old laptop etc) and wish to run bitcoin core. 

Using `make HOST=aarch64-linux-android ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/user/Downloads/bitcoin/depends/android_ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin ANDROID_SDK=/home/user/android-sdk-linux ANDROID_NDK=/home/user/Downloads/bitcoin/depends/android_ndk/android-ndk-r20`

And `depends/hosts/android.mk` has this :- 

`android_AR=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)-ar`
`android_CXX=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)$(ANDROID_API_LEVEL)-clang++`
`android_CC=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)$(ANDROID_API_LEVEL)-clang`
`android_RANLIB=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)-ranlib`
`ANDROID_SDK=$(ANDROID_SDK)`
`ANDROID_NDK=$(ANDROID_NDK)`
`NDK_VERSION=4.9`
`ANDROID_API_LEVEL=$(ANDROID_API_LEVEL)`

I've added `qt_android_packages=qt` to `depends/packages/packages.mk` and `$(package)_config_opts_aarch64_android = -xplatform android-clang -android-sdk $(ANDROID_SDK) -android-ndk $(ANDROID_NDK) -android-ndk-platform android-$(ANDROID_API_LEVEL) -device-option CROSS_COMPILE="$(host)-" -egl -qpa xcb -no-eglfs -opengl es2 -system-freetype -fontconfig -L $(host_prefix)/lib -I $(host_prefix)/include` to `depends/packages/qt.mk` I also created a qmake.conf that resolves the problem mentioned here :- https://forum.qt.io/topic/103713/error-cannot-find-lc-qt-5-12-android/14 and here :- https://github.com/pocoproject/poco/issues/2491

**Errors**

`ERROR: Feature 'system-freetype' was enabled, but the pre-condition 'features.freetype && libs.freetype' failed.`

`ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.win32 && !config.darwin && features.system-freetype && libs.fontconfig' failed.`

This issue is related to :- https://github.com/bitcoin/bitcoin/issues/13495
and https://github.com/bitcoin/bitcoin/pull/13696

**Comment by BlockMechanic** [comment]
Progress appears to have been made , now it configures to build the QT dependency but appears to choke at the end giving this warning/error :- 

`ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.win32 && !config.darwin && features.system-freetype && libs.fontconfig' failed.`

**Comment by emilengler** [comment]
Could you post your `./configure` arguments

**Comment by BlockMechanic** [comment]
Hi

I'm using `make HOST=aarch64-linux-android ANDROID_API_LEVEL=28 ANDROID_TOOLCHAIN_BIN=/home/brandon/Downloads/bitcointalkcoin/depends/android_ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin ANDROID_SDK=/home/brandon/android-sdk-linux ANDROID_NDK=/home/brandon/Downloads/bitcointalkcoin/depends/android_ndk/android-ndk-r20`

the `depends/hosts/android.mk` has this :- 

android_AR=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)-ar
android_CXX=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)$(ANDROID_API_LEVEL)-clang++
android_CC=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)$(ANDROID_API_LEVEL)-clang
android_RANLIB=$(ANDROID_TOOLCHAIN_BIN)/$(HOST)-ranlib
ANDROID_SDK=$(ANDROID_SDK)
ANDROID_NDK=$(ANDROID_NDK)
NDK_VERSION=4.9
ANDROID_API_LEVEL=$(ANDROID_API_LEVEL)

**Comment by BlockMechanic** [comment]
So, according to this comment https://github.com/bitcoin/bitcoin/pull/16110#discussion_r287915792
The original patch for QT aarch64 here :- https://github.com/bitcoin/bitcoin/pull/13696 may not work with my setup. That is NDKr20 , even patches for an android-clang-libc++ here :- https://bugreports.qt.io/browse/QTBUG-60455 do not seem to be working (unless i'm doing it wrong), even worse, no gcc at all. I've considered going back to ndk 19, but  not sure if that is the best move as google has completely dropped gcc, placing an expiry date on the ndk19 method. 

So anyone with ideas or pointers ?

**Comment by BlockMechanic** [comment]
So, according to this comment https://github.com/bitcoin/bitcoin/pull/16110#discussion_r287915792
GCC is  out for android and this is reflected in ndk20. Qt allows building with android-clang but there seems to be a conflict with libc++, even patches for an android-clang-libc++ here :- https://bugreports.qt.io/browse/QTBUG-60455 do not seem to be working (unless i'm doing it wrong).

**Comment by BlockMechanic** [comment]
Updated, anyone have ideas ?

**Comment by Sjors** [comment]
@greenaddress have you ever tried this for ABCore?

**Comment by BlockMechanic** [comment]
@Sjors I managed to go all the way to making an apk for arm64-v8a just a few hours ago. I am trying to work out armeabi-v7a now to ensure that should this be accepted , Bitcoin core can be released on the google play market. How goes your iOS effort ?

**Comment by greenaddress** [comment]
@sjors it's not very different from what bitcoin_ndk for ABCore does, sets up toolchain and calls depends -  but it's not enough to support aarch64 - google as of recently mandates all supported platform of you provide native core - so that's armv7a, aarch64, 686 and amd64 - when you get to 32 bit builds you'll hit an issue with libevent that requires either latest stable libevent or a patch

for details see https://github.com/greenaddress/bitcoin_ndk

**Comment by BlockMechanic** [comment]
I think i've bumped into a 32bit issue with leveldb, :- `:-1: error: error: /home/user/bitcoin/src/leveldb/libleveldb.a(leveldb_libleveldb_a-env_posix.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC`

**Comment by BlockMechanic** [comment]
![Screenshot from 2019-09-09 17-51-21](https://user-images.githubusercontent.com/24528627/64546140-63534700-d32a-11e9-874d-383bc5a493e0.png)
 
I have it running now :) ,now  I need to mod to make it more touch friendly. Anyone interested in working on this with me?

**Comment by GCastilho** [comment]
I think your progress so far is awesome

But can it sync with the network? And how does that work? (SPV, full sync, etc)

**Comment by BlockMechanic** [comment]
It can though not advisable using mobile data. With spv option, core reference client becomes viable and available on mobile.

**Comment by Sjors** [comment]
Don't worry about looks too much. As long as everything works, we can just review and merge the build system changes. Your PR should include instructions or link to a Github project, so others can reproduce the GUI build during review. 

Ideally you would use the same QT version 5.9.8 as [depends](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk). If that's not (yet) possible, perhaps you can add `qt-android.mk` with the more recent version you need? Eventually we'll catch up and unite them. @theuni thoughts?

**Comment by icota** [comment]
Awesome work @BlockMechanic! Would be great to have your recipe leading up to a working APK. I followed (some) of your steps to build 5.9.8 but got stuck on:
```ERROR: Feature 'system-freetype' was enabled, but the pre-condition 'features.freetype && libs.freetype' failed.

ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.win32 && !config.darwin && features.system-freetype && libs.fontconfig' failed.```

When we figure this out I can add the necessary changes and patches to [PR 16110](https://github.com/bitcoin/bitcoin/pull/16110)

**Comment by icota** [comment]
I managed to build it by disabling `fontconfig` (which I belive serves no purpose on Android). I've rebased and updated [#16110](https://github.com/bitcoin/bitcoin/pull/16110).

**Comment by BlockMechanic** [comment]
Awesome i actually have regular builds already and had started working on modifying the wallet to for small screens and also a material theme to match android standards. I will have time in the morning tomorrow and will fork your branch and make a PR with my changes.

**Comment by icota** [comment]
@BlockMechanic what a coincidence. I have made a "mobile" PR as well but I'm aiming to use QtQuick rather than QtWidgets. But I think we are mostly on the same page - looking forward to your PR.

**Comment by BlockMechanic** [comment]
Lol, This is sooooo SOLVED.

**Comment by GCastilho** [comment]
It is? Why?

**Comment by BlockMechanic** [comment]
aarch64 builds + Qt are already a thing.
