### ISSUE TITLE
Feature Request: Add a GUI option for where the blockchain storage locations.

### ISSUE THREAD

**Issue by fresheneesz** [bitcoin/bitcoin#16579]
I currently tried upgrading Bitcoin Core to v0.18 and it filled up by primary drive somehow. I had previously had it configured to store the database on my primary harddrive and the blockchain on a secondary drive. It clearly has messed with that config. Looking at my configuration file, its just empty. And the blockchain is not being stored at %APPDATA%/Bitcoin (I'm on windows 7), so I have no idea where its going. 

Having a way to select where to store the blockchain is critical now that the chain is so huge. I don't want to put that thing on my primary drive that only has 225GB total. Yes I can edit the config file, but that's not user friendly. This is an important option and should be exposed where an unsophisticated user can change it. It would also help me if I could see where this thing is putting the blockchain so I don't have to an hour of my life looking for a suspiciously large directory.

**Comment by achow101** [comment]
> This is an important option and should be exposed where an unsophisticated user can change it.

The first time you start Bitcoin Core, it will prompt you to set the datadir. The assumption is that you won't be moving the datadir once it is set.

> It would also help me if I could see where this thing is putting the blockchain so I don't have to an hour of my life looking for a suspiciously large directory.

You already can. Go to Window > Information. It will be listed as `datadir`.

**Comment by emilengler** [comment]
At least on Unix systems you can take a look at the QSettings bitcoin-qt file.
There they are stored at `~/.config/Bitcoin` (IIRC).
On Windows it is probably in `%APPDATA%\Bitcoin`.
There is a string which says where the datadir is located

**Comment by achow101** [comment]
> On Windows it is probably in `%APPDATA%\Bitcoin`.
> There is a string which says where the datadir is located

QSettings saves things in the registry on Windows.

**Comment by emilengler** [comment]
Oh ok, according to the Qt Documentation it should be probably located somewhere in
`HKEY_CURRENT_USER\Software\Bitcoin\` and/or `HKEY_LOCAL_MACHINE\Software\Bitcoin\`
However I'm not 100% sure because I don't use Windows

**Comment by laanwj** [comment]
If you move the datadir out of the way, it will re-ask for the datadir location next time. If you simply give it the new location of the data dir, that will work.
