### ISSUE TITLE
Delete duplicate and unnecessary translations

### ISSUE THREAD

**Issue by GChuf** [bitcoin/bitcoin#16591]
There are too much choices in the bitcoin core translation list.

Some of them are duplicates and should be removed (like `italiano (it)` and `italiano - Italia (it_IT)
`, while some others do not add any value (like all the spanish translation on the screenshot below and some others).

I have selected some duplicates from the Transifex page that are also duplicates in the current Bitcoin Core v18.0 selection menu:

```
Belarusian (be) 4,718 strings to translate 0 strings to review no translators
Bulgarian (Bulgaria) (bg_BG) 3,731 strings to translate 987 strings to review
Greek (el) 4,588 strings to translate 130 strings to review
Spanish (Spain) (es_ES) 472 strings to translate 4,246 strings to review
Estonian (Estonia) (et_EE) 3,888 strings to translate 830 strings to review
French (France) (fr_FR) 2,034 strings to translate 2,684 strings to review
Italian (Italy) (it_IT) 3,464 strings to translate 1,254 strings to review
Romanian (ro) 3,210 strings to translate 1,508 strings to review
Russian (ru) 3,363 strings to translate 1,355 strings to review
Slovenian (sl) 4,703 strings to translate 15 strings to review
Vietnamese (Viet Nam) (vi_VN) 3,287 strings to translate 1,431 strings to review
```
These are the duplicate languages which have achieved a lower translation completion than their "counterparts" - for example `Belarusian (Belarus) (be_BY) 3,182 strings to translate` vs `Belarusian (be) 4,718 strings to translate`. `(be)` should therefore be removed so that other translators won't bother with translating one language two times, and so that people won't have to guess which language to select in Bitcoin Core.

This is just a small list - there's also languages like `French (Canada)`, `Italian (Switzerland)`, `English (Canada)`, `Russian (Ukraine)` and so on on Transifex (but not in bitcoin core) which also don't add any value.

These translations should be closed on Transifex and removed from Bitcoin Core. I am not sure if removing them from Transifex would automatically remove them from Bitcoin Core next time translations are pulled or if this has to be done manually.

![Screenshot_53](https://user-images.githubusercontent.com/42591821/62894584-81825300-bd3c-11e9-9e0a-7b547e285b67.png)

**Comment by hebasto** [comment]
@gapeman 

> This is just a small list - there's also languages like `French (Canada)`, `Italian (Switzerland)`, `English (Canada)`, `Russian (Ukraine)` and so on on Transifex (but not in bitcoin core) which also don't add any value.

They _do_ add value.

**Comment by gapeman** [comment]
@hebasto would you care to elaborate?
As far as I know, "English (Canada) is just a mixture between american and british english, and so I don't think it's necessary. I'm not sure about the Italian language in Switzerland but most likely the Italian language in these two countries is more or less the same - probably even more so when speaking about IT jargon. People in Ukraine do speak russian, but I am not aware of "their own version" of russian language (they do have their own ukrainian language).

What would be the reason to keep these?

Anyway, I'd rather focus on duplicates first and deal with other languages later.
