### ISSUE TITLE
Better command help for getblocktemplate

### ISSUE THREAD

**Issue by red0bear** [bitcoin/bitcoin#16594]
I'm testing command here but always get error. Following the help doesn't help too. Can you give me a good example how to build this command ? I already have command client working fine. 

bitcoin-cli getblocktemplate {"rules":["segwit"]} --> like in example but give error.

**Comment by MarcoFalke** [comment]
What is the error?

**Comment by red0bear** [comment]
@MarcoFalke , Error: Error parsing JSON:{

**Comment by MarcoFalke** [comment]
Oh, I see we are not quoting correctly in the rpc help

**Comment by emilengler** [comment]
@MarcoFalke Quoting correctly?
Do you mean that the brackets need to be quoted as well?

**Comment by emilengler** [comment]
See #16596

**Comment by Relaxo143** [comment]
why is there a new minor version (0.18.2) being developed?

**Comment by MarcoFalke** [comment]
See https://bitcoincore.org/en/lifecycle

**Comment by openGLnoob** [comment]
Hmm. When I have `bitcoin-cli getblocktemplate '{"rules":["segwit"]}'` I get error also:
```
error: Error parsing JSON:'{rules:[segwit]}'
```

**Comment by openGLnoob** [comment]
SOLVED!
On Win7 you need replace all `"` to `\"` and all `'` to `"`. That will work:
```
bitcoin-cli getblocktemplate "{\"rules\":[\"segwit\"]}"
```
The same goes for curl.

**Comment by emilengler** [comment]
Same on most Unix shells as well but this is more an issue/feature of your shell
