### ISSUE TITLE
installing Qt ubuntu proxy issue

### ISSUE THREAD

**Issue by Quantacoin-project** [bitcoin/bitcoin#16601]
I am trying to install``` Qt ```on ubuntu for ( build bitcoin ({ make } command) )  by steps :
```

sudo apt-get install build-essential

sudo apt-get install qtcreator

sudo apt-get install qt5-default
```
and I got :

```
0 upgraded, 186 newly installed, 0 to remove and 0 not upgraded.
Need to get 49.5 kB/52.9 MB of archives.
After this operation, 390 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libproxy1v5 amd64 0.4.15-1
  400  Bad URI [IP: 91.189.88.149 80]
Unable to correct missing packages.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libp/libproxy/libproxy1v5_0.4.15-1_amd64.deb  400  Bad URI [IP: 91.189.88.149 80]
E: Aborting install.
```
how can I solve this porblem ?
note : my location is syria , and I am runing ubuntu on windows ( WSL ) , without  ' Virtual Box ', and I tried to run " psiphon " but the problem still here !

**Comment by fanquake** [comment]
Nowhere in our [ubuntu build instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#ubuntu--debian) do we mention installing `qt5-default`. You might want to try installing the packages listed there instead, or you could try using the [depends system](https://github.com/bitcoin/bitcoin/tree/master/depends).

Regardless, if you are having issues related to internet censorship, this issue tracker is not really the place to discuss/solve them.
