### ISSUE TITLE
Technical Issue : ' rename ' command ..It is recognized as a file.

### ISSUE THREAD

**Issue by Quantacoin-project** [bitcoin/bitcoin#16616]
I am trying to rename files in src folder `bitcoin/src` by using :

`find . -exec rename 's/bitcoin/altcoin/' {} ";"`

also tried :

`find ./ -type f -readable -writable -exec rename -e 's/bitcoin/altcoin/g' {} \;`

and I got this :

`find: ‘rename’: No such file or directory`

I am trying to fork bitcoin to my own altcoin , using ubuntu 18.04 !
so What's the peoblem ? and how can I fix it !
thank you .

**Comment by fanquake** [comment]
I don't think anyone here is interested in helping you create your altcoin. Nor should you be using this issue tracker to ask questions about basic command line tool usage.

**Comment by Quantacoin-project** [comment]
> 
> 
> I don't think anyone here is interested in helping you create your altcoin. Nor should you be using this issue tracker to ask questions about basic command line tool usage.

and I don't think that YOU HAVE  to be disrespectful if you didn't want help you can just move on sweety .ok?
