### ISSUE TITLE
Functional test suite bottlenecks

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#16613]
After applying #15363, and configuring without debug, when I run the functional test suite on a 3 GB RAM disk with `--jobs=100 --cachedir=/Volumes/RAMDisk/cache --tmpdir=/Volumes/RAMDisk/tmp`:

* CPU usage hovers between 50 and 80% for the first 45 seconds and then drops.
* RAM usage peaks at about 12 GB in the same time period and then drops.
* test suite takes about 120 seconds

The above suggests that the total run time is determined by a handful of slow running tests:

* wallet_backup.py: ~120s~ 58s 
* feature_block.py: ~115s~ 85s
* wallet_address_types.py: ~102s~ 48s
* feature_maxuploadtarget.py: 85s
* p2p_segwit.py: ~83s~ 60s
* p2p_tx_download.py: 84s
* mining_getblocktemplate_longpoll.py: 70s
* feature_fee_estimation.py: ~68s~ 41s

Getting the above tests to run in under 60 seconds should therefore cut total run time in half for me. Whether this benefits slower systems depends on the reason for the bottleneck.

A bit more detail about the slow running tests:

## wallet_backup.py

"Creating transactions" takes almost a minute. Backup is nearly instant. "More transactions" takes another 50 seconds. The various restores take 22 seconds in total.

The test could be made faster by:
1. generating fewer transactions
2. put pre-generated the wallets, use extended test suite to verify their contents. However, it's useful to check that the backup feature actually works for a freshly generated wallet.
3. figuring out why 30 transactions are so slow. I tried setting `wait=0.1` for both sync_mempool and sync_blocks but that didn't help.

Fixed by #17121

##  feature_block.py

When running this test individually it took only 25 seconds (in contrast to the wallet_backup where running individually didn't make much difference). The slowest checks are `Reject a block with too many P2SH sigops` (7s)

This test could be split (in two). This requires moving some helper code into the test framework, as well as studying the sequence of checks for inter-dependencies.

See https://github.com/bitcoin/bitcoin/issues/16613#issuecomment-542252600

## wallet_address_types.py

Runs in 58 seconds individually.

This test seems trivial to split. But like `wallet_backup.py` it may be worth investigating why a just a few dozen transactions take so long.

Fixed by #17124

## feature_maxuploadtarget.py

Runs in 1 minute individually, could perhaps be split in two.

## p2p_segwit.py

TODO

## p2p_tx_download.py

TODO

## mining_getblocktemplate_longpoll.py

TODO

## feature_fee_estimation.py

Fixed by #16535

**Comment by MarcoFalke** [comment]
> p2p_tx_download.py

This is supposed to run 1 minute in real time. I didn't bother to (or could not) change the tx fallback timeout to mocktime.

**Comment by MarcoFalke** [comment]
> feature_fee_estimation.py

This has been fixed by #16535. The same could be applied to other tx-relay tests with a lot of txs.

**Comment by theStack** [comment]
> wallet_backup.py

The majority of the time for the "Creating transactions" / "More transactions" parts is spent in `sync_mempools()` (called 5 times each), i.e. the bottleneck is in relaying transactions. By whitelisting the peers (via `-whitelist`, like in https://github.com/bitcoin/bitcoin/pull/16535), the inventory is transmissioned immediately rather than on average every 5 seconds (see https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L105), speeding up the test by at least a factor of two:
```
$ time ./wallet_backup.py
real	2m2.523s
user	0m6.093s
sys	0m2.454s
```

```
$ time ./wallet_backup_with_whitelist.py
real	0m36.570s
user	0m5.365s
sys	0m1.696s
```

**Comment by theStack** [comment]
> wallet_address_types.py

Same as for `feature_fee_estimation.py` and `wallet_backup.py`, this one can be sped up significantly (>3x on my machine) by whitelisting peers: https://github.com/bitcoin/bitcoin/pull/17124
As far as I can see, there is no slow running test (>60 sec.) left now for which the bottleneck is mempool synchronization and a whitelisting could help.

**Comment by Sjors** [comment]
Thanks for all the improvement PRs @theStack! I updated the description above to link to them. I'll run my initial benchmark again when a few more have landed.

**Comment by theStack** [comment]
> 
> 
> Thanks for all the improvement PRs @theStack! I updated the description above to link to them. I'll run my initial benchmark again when a few more have landed.

You're welcome -- working on those tasks provided me a great way to learn more about the test systems as well as about the internals of bitcoind and I recommend them to every new contributor (like me) trying to get one's feet wet with Bitcoin Core development. Definitely deserves the label "good first issue". :+1: 

> feature_block.py

On my machine most of the time is spent for the check `Test a re-org of one week's worth of blocks (1088 blocks)` (57.64sec / 90.94 sec, or >60% of total time). Considering that a relatively large total block data amount over 1 GB (1088 full blocks, hence 1088 MB) is created and sent to bitcoind, the CPU is mostly occupied with hashing, signing and waiting for bitcoind to respond, as shown by profiler:

```
$ python3 -m cProfile -s time feature_block.py
         11216456 function calls (10853148 primitive calls) in 87.749 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1041   52.693    0.051   52.693    0.051 {built-in method time.sleep}
  1152256    8.820    0.000    8.820    0.000 key.py:112(double)
   572356    5.840    0.000    5.840    0.000 key.py:132(add_mixed)
   162592    4.093    0.000    4.093    0.000 {built-in method _hashlib.new}
      350    2.126    0.006   54.649    0.156 util.py:206(wait_until)
   105746    1.359    0.000    1.804    0.000 messages.py:338(serialize)
151641/115735    0.979    0.000    4.257    0.000 messages.py:136(ser_vector)
     4501    0.949    0.000   15.963    0.004 key.py:202(mul)
   143473    0.784    0.000    1.000    0.000 messages.py:101(ser_uint256)
     9001    0.711    0.000    0.711    0.000 key.py:11(modinv)

```
So I guess there is not much room for a performance improvement without changing parameters (like e.g. number of blocks to re-org).

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by Sjors** [comment]
I updated the measurements in the OP. Several tests are still > 60 seconds, e.g. `feature_block.py`. It seems non trivial to improve that, but not hopeless enough to close the issue either?

**Comment by jnewbery** [comment]
I think the best thing that can be done for feature_block is to split the week-long-reorg test into its own test file. That at least makes the test more tractable and easier to work with.

**Comment by theStack** [comment]
Now that several functional tests have been optimized recently, would it probably a good opportunity to update the order of the test script list (ordered descending by running time)?
https://github.com/bitcoin/bitcoin/blob/bc38bb9a6036d73f507e66a2f588547f3f17e4b1/test/functional/test_runner.py#L76-L218
Also the comments don't seem to be accurate anymore, "Tests less than 5m"/"Tests less than 2m" can probably be substitued by "Tests less than 2m"/"Tests less than 1m".

**Comment by jnewbery** [comment]
> would it probably a good opportunity to update the order of the test script list

Concept ACK. Seems reasonable to do this every so often.

**Comment by markblundeberg** [comment]
**p2p_feefilter** also can be made 10x faster by:
- whitelisting to remove relay delays.
- changing the sleep timer from 1 to 0.1 seconds.

(The test time is dominated by waiting for invs from nodes, which are subject to the trickle relay mechanism.)

I'm not sure if that is totally desired though, is there any chance that whitelisting will modify fee filter mechanism and cause an interaction?

In fact that test can rarely fail with a ~ 1-in-30000 chance because there is no upper bound on the trickle relay time. With a tx that is created on node1 and related node1 -> node0 -> mininode, the mean time to propagate is ~ 6.7 seconds (node1 and node0 are bidirectionally connected but mininode is only inbound). We actually got lucky and had such a failure recently in ABC. :D
