### ISSUE TITLE
doc: Move to new GitHub issue templates

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16627]
Apparently we're using the old version of the GitHub issue templates. Not sure if there are any advantages to switching to the new form or not. Info here: https://help.github.com/en/articles/about-issue-and-pull-request-templates.

![Screen Shot 2019-08-16 at 10 21 23 am](https://user-images.githubusercontent.com/863730/63139201-02c53880-c010-11e9-879a-5dd29679a955.png)

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by emilengler** [comment]
Concept ACK

**Comment by emilengler** [comment]
You need write access for this, it can be done it the Settings of this repository but you need privileges for this.

**Comment by MarcoFalke** [comment]
Now live: https://github.com/bitcoin/bitcoin/issues/new/choose
