### ISSUE TITLE
configure takes almost 10 minutes on some macs

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#16632]
Model: MacBook Pro (15-inch 2017)
OS: macOS High Sierra

```Bash
$ time ./configure
[...]
./configure  29.65s user 542.02s system 96% cpu 9:50.57 total
```

Same problem seems to be present on co-workers' mac. Linux (ubuntu) runs much faster, but I believe I have seen occasions where linux box slows down in this manner as well.

Update: antivirus software may have been a part of the reason for the slow-down. Still slow after uninstall, but still several minutes.

**Comment by Sjors** [comment]
Just 30 seconds real time on 2019 MacBook Pro, though faster is always nice:
```sh
time ./configure --disable-bip70 --with-miniupnpc=no --enable-debug
[...]
real	0m31.794s
user	0m18.778s
sys	0m10.819s
```

**Comment by kallewoof** [comment]
Yeah, this started happening awhile back for me. I'm not sure what the cause is, but it doesn't look like it's only me. It's not everyone, as you see.

**Comment by kallewoof** [comment]
Coworker:
```
real    7m1.310s
user    0m22.802s
sys    6m31.218s
```

**Comment by johnnynanjiang** [comment]
macOS Mojave
Version 10.14.5
MacBook Pro (Retina, 13-inch, Late 2013)

```
time ./configure

real	1m16.253s
user	0m34.910s
sys	0m29.537s
```

**Comment by za-kk** [comment]
Macbook Pro (13-inch, Late 2017) running macOS Mojave (Version 10.14.6), I get 43 seconds real time.

```
time ./configure

real	0m43.429s
user	0m24.560s
sys	0m15.737s
```

**Comment by RandyMcMillan** [comment]
Try running 

```
time ./configure
```

on a fresh clone of the repo. 

Compare to the problem repo.

It may be useful to create a new user and see if the problem exists under a new user. 
(also with a fresh clone of the repo)

**Comment by laanwj** [comment]
is there any specific step that takes so long? e.g. a configure.log with timestamps would be more useful to make any progress on this issue than overall times

in general, "configure" spawns a lot of subprocesses, such as compilers, which is fast on UNIX but can be slower on other OSes such as Windows, that's a conceptual issue that cannot really be fixed in the scope of this project

**Comment by kallewoof** [comment]
This happens for me on a fresh machine / install of macOS. I believe my company may be using some software (my guess is the antivirus software) that causes this, but I'm not sure.

Either case, I don't think this is bitcoin related, as so few others are experiencing it. Thanks for the feedback.

**Comment by kallewoof** [comment]
For the record, I narrowed this down to g++/gcc being super slow on some macs.

```Bash
# mac
$ echo "int main(){}" > tst.cpp; time ( for i in {1..10}; do
g++ -std=c++11 -c -g -O2 -g3 -O0  -DDEBUG -DDEBUG_LOCKORDER -DMAC_OSX tst.cpp; done )
( for i in {1..10}; do; g++ -std=c++11 -c -g -O2 -g3 -O0 -DDEBUG  -DMAC_OSX ;
   0.15s user 13.00s system 99% cpu 13.211 total

# linux
$ echo "int main(){}" > tst.cpp; time ( for i in {1..10}; do
g++ -std=c++11 -c -g -O2 -g3 -O0  -DDEBUG -DDEBUG_LOCKORDER -DMAC_OSX tst.cpp; done )
( for i in {1..10}; do; g++ -std=c++11 -c -g -O2 -g3 -O0 -DDEBUG  -DMAC_OSX ;
   0.24s user 0.16s system 100% cpu 0.400 total
```

**Comment by kallewoof** [comment]
For the record: this was caused by Cylance, some antivirus software that my IT dept installed on my machine. I thought I had turned it off but it apparently kept some unkillable process running that I didn't notice.
