### ISSUE TITLE
PPA repository security can not be verified on Ubuntu 19.04

### ISSUE THREAD

**Issue by lacksfish** [bitcoin/bitcoin#16637]
Recently running Ubuntu 19.04, I noticed the following when adding the official bitcoin PPA

After running:
```
$ sudo add-apt-repository ppa:bitcoin/bitcoin
$ sudo apt update
```

I get the following error:
```
...
W: The repository 'http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu disco Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I have to run the following to actually fetch the update information:
```
$ sudo apt-get update --allow-insecure-repositories
```

I think this is an easy fix given the right credentials for the PPA repo?

**Comment by lacksfish** [comment]
Even with the `--allow-insecure-repositories` param I can not seem to run:

```
sudo apt install bitcoind
```

It still doesn't find the package. :( I will compile it in the mean time, as I should anyway :P

**Comment by MarcoFalke** [comment]
The ppa is no longer supported. Where did you get those install instructions from?

**Comment by lacksfish** [comment]
By official, I mean "official". Or, assumed to be trustworthy by the community (literally any of the "install guides" out there)

**Comment by emilengler** [comment]
Use the snap instead if you want a release which is being updated by a package manager

**Comment by MarcoFalke** [comment]
Indeed, if you are running Ubuntu, you are better of with the snap package.

```sh
$ snap info bitcoin-core
