### ISSUE TITLE
Unable to stop bitcoin-qt. ThreadDNSAddressSeed hangs.

### ISSUE THREAD

**Issue by Nikolay-Po** [bitcoin/bitcoin#16642]
The problem:
Sometimes, usually after Internet connection disturbances, it is impossible to stop bitcoin-qt or daemon.

I'm expecting:
That on close command bitcoin-qt in GUI or daemon mode will finish it's operation in reasonable time and the database will contain the last synchronized blocks and is ready to continue the operation from it's current state.

Actual behavior:
Qt-interface is hanging on "Bitcoin Core is shutting down" window, daemon just remains as a process. None CPU or I/O load is created when the process stalls. None reads/writes to the storage, none percents of CPU load. Have confirmed by looking at htop and iotop terminals.
Bitcoin Core will running normally after WAN connection change or temporary problems. Newer peers are connected both way, the traffic is OK, all seems OK. But it will not stop operation normally any more. Only one way to stop is to send SIGQUIT to the process.
The worst thing is the loose of last Bitcoin Core session data. For example, if Bitcoin Core was running two weeks and was failed to stop correctly, at the next start it will continue only from two weeks ago state. The blocks need to be rescanned form HDD again. This taking rather long time.
After shutdown problem it may be impossible to perform shutdown even if there were none problems with WAN. I had to restart the client several times to get normal close. After it closed correctly, Bitcoin Core operating normally and shutting down normally.
Here is a log from unsuccessful shutdown:
```
2019-08-17T21:13:34Z GUI: requestShutdown : Requesting shutdown
2019-08-17T21:13:34Z GUI: shutdown : Running Shutdown in thread
2019-08-17T21:13:34Z Interrupting HTTP server
2019-08-17T21:13:34Z Interrupting HTTP RPC server
2019-08-17T21:13:34Z Interrupting RPC
2019-08-17T21:13:34Z Shutdown: In progress...
2019-08-17T21:13:34Z Stopping HTTP RPC server
2019-08-17T21:13:34Z addcon thread exit
2019-08-17T21:13:34Z opencon thread exit
2019-08-17T21:13:34Z Stopping RPC
2019-08-17T21:13:34Z Stopping HTTP server
2019-08-17T21:13:34Z Stopped HTTP server
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: [/media/nikolaypo/bitcoindb] Flush(false)
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: Flushing wallet.dat (refcount = 0)...
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: wallet.dat checkpoint
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: wallet.dat detach
2019-08-17T21:13:34Z net thread exit
2019-08-17T21:13:34Z msghand thread exit
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: wallet.dat closed
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: Flush(false) took              86ms
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: [/media/nikolaypo/bitcoindb] Flush(false)
2019-08-17T21:13:34Z BerkeleyEnvironment::Flush: Flush(false) took               0ms
2019-08-17T21:27:43Z Flushed 66639 addresses to peers.dat  656ms
2019-08-17T21:42:44Z Flushed 66639 addresses to peers.dat  635ms
2019-08-17T21:50:27Z Potential stale tip detected, will try using extra outbound peer (last tip update: 2260 seconds ago)
2019-08-17T21:50:27Z net: setting try another outbound peer=true
2019-08-17T21:57:44Z Flushed 66639 addresses to peers.dat  622ms
2019-08-17T22:00:57Z Potential stale tip detected, will try using extra outbound peer (last tip update: 2890 seconds ago)
2019-08-17T22:00:57Z net: setting try another outbound peer=true
2019-08-17T22:11:27Z Potential stale tip detected, will try using extra outbound peer (last tip update: 3520 seconds ago)
2019-08-17T22:11:27Z net: setting try another outbound peer=true
2019-08-17T22:12:45Z Flushed 66639 addresses to peers.dat  605ms
2019-08-17T22:21:57Z Potential stale tip detected, will try using extra outbound peer (last tip update: 4150 seconds ago)
2019-08-17T22:21:57Z net: setting try another outbound peer=true
2019-08-17T22:58:17Z
```

Again, when the client hangs, it does not producing CPU or storage load.

Reproduction:
Keep Bitcoin Core running normally. Then change WAN IP on upstream router by restarting PPTP interface. Let the client run some more to confirm normal behavior before stopping. Then try to close bitcoin-qt or send stop command to the daemon.

Sometimes the problem is not manifesting itself. But with about 10-30% of WAN connection disturbances or reconnects leads to impossibility of correct shutting down.

Have tried v0.18.0 and v0.18.1, have tried amd64 and arm architectures. Have tried GCC 6.3 and GCC 9.1.0 compilers. The problem persisting with different builds and on different machines. All sources was from bitcoin project on github.com, the place were I'm leaving this issue description. I have not tested pre-compiled versions.

1) Intel Core2Duo, Debian 9 Linux, amd64. 2) Rockchip  RK3399, Armbian Linux, aarch64-linux-gnu. With both machines I have used the same USB 3.0/SATA adapter with the same 3TB Seagate (rotating) HDD. EXT4.

I had to rescan the database three times because of hardware failures, two times after a power loss, one time after USB interface sudden disconnection. May be there are the problems with blocks but fsck with -P parameter doesn't found an errors.

As for me, I need more feedback from Bitcoin Core client in case of problems and more robustness. One time I had a problem with one chainstate file corruption on the media I had to rescan the data base again from block zero. It is a pity that single file corruption cannot be recovered automatically without spending a lot of IO operations and CPU power for rescanning.

Thank you for your attention!

Nikolay

**Comment by Mine8801** [comment]
gpg --refresh-keys

**Comment by MarcoFalke** [comment]
Are you sure this is due to the stale tip detection? It looks more like a thread that does not join on shutdown

**Comment by Nikolay-Po** [comment]
I have almost zero Bitcoin competence. I'm not sure in anything.
What can I do next to investigate the problem? Why Bitcoin Core rejects all information of whole running period if was shut down not gracefully? среда, 21 августа 2019г., 18:13 +03:00 от MarcoFalke  notifications@github.com :

**Comment by MarcoFalke** [comment]
Based on the debug.log, it is stuck in this line (or any later line):

https://github.com/bitcoin/bitcoin/blob/2472733a24a9364e4c6233ccd04166a26a68cc65/src/init.cpp#L221-L304

The `Flushed 66639 addresses to peers.dat` (happens inside of `CConnman::Stop`).

If you feel comfortable debugging this yourself, you can do that (for example) by adding log statements to the shutdown function. So maybe add `LogPrintf("%s: Passed %s\n", __func__, __LINE__);` in every other line after line `if (g_connman) g_connman->Stop();` and the next time this happens, at least you will see which line caused the deadlock.

**Comment by Nikolay-Po** [comment]
Have inserted additional debug printouts after each function call inside of Shutdown() function. The last line which is not reaching it's end is

`if (g_connman) g_connman->Stop();`

The log after this line execution looks like this:

`2019-08-24T20:08:17Z       - Connect 2576 transactions: 9925.32ms (3.853ms/tx, 2.221ms/txin) [199.79s (10515.11ms/blk)]
2019-08-24T20:08:17Z     - Verify 4468 txins: 9948.58ms (2.227ms/txin) [200.34s (10544.47ms/blk)]
2019-08-24T20:08:17Z     - Index writing: 0.40ms [0.01s (0.28ms/blk)]
2019-08-24T20:08:17Z     - Callbacks: 0.32ms [0.00s (0.09ms/blk)]
2019-08-24T20:08:17Z   - Connect total: 9964.71ms [200.75s (10565.71ms/blk)]
2019-08-24T20:08:17Z   - Flush: 35.89ms [0.38s (20.02ms/blk)]
2019-08-24T20:08:17Z   - Writing chainstate: 0.33ms [0.01s (0.33ms/blk)]
2019-08-24T20:08:17Z Blockpolicy estimates updated by 0 of 0 block txs, since last block 0 of 0 tracked, mempool map size 0, max target 39 from historical
2019-08-24T20:08:17Z UpdateTip: new best=000000000000000000195bb8347e4d48858145b696756b28e77843e6fcecf23c height=590456 version=0x20000000 log2_work=90.972688 tx=445847403 date='2019-08-17T00:28:39Z' progress=0.994447 cache=12.1MiB(91185txo)
2019-08-24T20:08:17Z   - Connect postprocess: 4.38ms [0.11s (5.81ms/blk)]
2019-08-24T20:08:17Z - Connect block: 10064.16ms [202.51s (10658.52ms/blk)]
2019-08-24T20:08:17Z msghand thread exit
2019-08-24T20:08:17Z sending version (102 bytes) peer=3
2019-08-24T20:08:17Z send version message: version 70015, blocks=590455, us=[::]:0, peer=3
2019-08-24T20:08:17Z opencon thread exit
2019-08-24T20:08:17Z WriteBatch memory usage: db=txindex, before=2.8MiB, after=3.0MiB
`

**Comment by Nikolay-Po** [comment]
Dug down to CConnman::Stop() method. It seems to me the core hangs at threadDNSAddressSeed.join() function.

`void CConnman::Stop()
{
    ...
    if (threadDNSAddressSeed.joinable())
        threadDNSAddressSeed.join();
`

**Comment by fanquake** [comment]
@promag is this similar to what you saw in #15657 ?

**Comment by promag** [comment]
@fanquake I was about to comment that but I don't think it is. In #15657 it eventually quits.

**Comment by Nikolay-Po** [comment]
Mine doesn't quit even being left for tonight.

**Comment by Nikolay-Po** [comment]
My C++ (and in general, OOP) understanding absence prevents further debugging. I can't find what is this "threadDNSAddressSeed" and where it's "join" thing. And why there is a "join" if I ask to stop. It should be "leave" but not "join". Do not understand. :(

**Comment by MarcoFalke** [comment]
Can you check the debug log for one of the following lines:

* `P2P peers available. Skipped DNS seeding`
* `Loading addresses from DNS seeds (could take a while)`
* `addresses found from DNS seeds`

**Comment by Nikolay-Po** [comment]
After deleting debug log, P2P word is present only one time: "init message: Loading P2P addresses...".
Word "DNS" two times: "dnsseed thread start" and "Loading addresses from DNS seeds (could take a while)".
Word "seed" only two times, the same places as "DNS".

**Comment by Nikolay-Po** [comment]
This is how looks process list from htop when close command was issued but not executed:
`  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  
19931 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:01.44 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19932 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19933 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19934 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19935 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19936 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19937 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19938 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.04 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19939 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:18.10 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19940 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6 14:41.51 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19941 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6 14:34.99 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19942 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6 14:34.51 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19943 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6 14:35.58 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19944 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6 14:37.79 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19945 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  2:08.95 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19994 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  1:46.61 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
20011 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
20073 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:00.00 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
20080 nikolaypo  20   0 6117M  993M  138M S  0.0 25.6  0:10.75 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
19930 nikolaypo  20   0 6117M  993M  138M S  0.6 25.6  2h05:14 bitcoin-qt -datadir=/media/nikolaypo/bitcoindb -debug -dbcache=1200
`

CPU is 6-core. Why there are so much processes?

**Comment by Nikolay-Po** [comment]
Before close command:
```
0 S  1000 30271  1609 30271  1  80   0 - 1118215 poll_s pts/0  00:00:28 bitcoin-qt
1 S  1000 30271  1609 30272  0  80   0 - 1118215 poll_s pts/0  00:00:00 QXcbEventReader
1 S  1000 30271  1609 30273  0  80   0 - 1118215 futex_ pts/0  00:00:00 llvmpipe-0
1 S  1000 30271  1609 30274  0  80   0 - 1118215 futex_ pts/0  00:00:00 llvmpipe-1
1 S  1000 30271  1609 30275  0  80   0 - 1118215 futex_ pts/0  00:00:00 llvmpipe-2
1 S  1000 30271  1609 30276  0  80   0 - 1118215 futex_ pts/0  00:00:00 llvmpipe-3
1 S  1000 30271  1609 30277  0  80   0 - 1118215 futex_ pts/0  00:00:00 llvmpipe-4
1 S  1000 30271  1609 30278  0  80   0 - 1118215 futex_ pts/0  00:00:00 llvmpipe-5
1 S  1000 30271  1609 30279  0  80   0 - 1118215 poll_s pts/0  00:00:00 QDBusConnection
1 S  1000 30271  1609 30280  1  80   0 - 1118215 poll_s pts/0  00:00:25 QThread
1 S  1000 30271  1609 30281  5  80   0 - 1118215 futex_ pts/0  00:02:04 bitcoin-scriptc
1 S  1000 30271  1609 30282  5  80   0 - 1118215 futex_ pts/0  00:02:03 bitcoin-scriptc
1 S  1000 30271  1609 30283  5  80   0 - 1118215 futex_ pts/0  00:02:03 bitcoin-scriptc
1 S  1000 30271  1609 30284  5  80   0 - 1118215 futex_ pts/0  00:02:05 bitcoin-scriptc
1 S  1000 30271  1609 30285  5  80   0 - 1118215 futex_ pts/0  00:02:05 bitcoin-scriptc
1 S  1000 30271  1609 30286  0  80   0 - 1118215 futex_ pts/0  00:00:09 bitcoin-schedul
1 S  1000 30271  1609 30288  0  80   0 - 1118215 futex_ pts/0  00:00:00 QThread
1 D  1000 30271  1609 30320  8  80   0 - 1118215 wait_o pts/0  00:02:44 bitcoin-loadblk
1 S  1000 30271  1609 30321  0  80   0 - 1118215 futex_ pts/0  00:00:03 bitcoin-net
1 S  1000 30271  1609 30322  0  80   0 - 1118215 sk_wai pts/0  00:00:00 bitcoin-dnsseed
1 S  1000 30271  1609 30323  0  80   0 - 1118215 futex_ pts/0  00:00:00 bitcoin-addcon
1 S  1000 30271  1609 30324  0  80   0 - 1118215 futex_ pts/0  00:00:00 bitcoin-opencon
1 S  1000 30271  1609 30325  0  80   0 - 1118215 futex_ pts/0  00:00:02 bitcoin-msghand
1 S  1000 30271  1609 30336  0  80   0 - 1118215 poll_s pts/0  00:00:00 QThread
1 S  1000 30271  1609 30339  0  80   0 - 1118215 poll_s pts/0  00:00:00 QThread
1 S  1000 30271  1609 30346  0  80   0 - 1118215 poll_s pts/0  00:00:00 Qt bearer threa
```
And after close hang:
```
0 S  1000 30271  1609 30271  1  80   0 - 1141085 poll_s pts/0  00:00:31 bitcoin-qt
1 S  1000 30271  1609 30272  0  80   0 - 1141085 poll_s pts/0  00:00:00 QXcbEventReader
1 S  1000 30271  1609 30273  0  80   0 - 1141085 futex_ pts/0  00:00:00 llvmpipe-0
1 S  1000 30271  1609 30274  0  80   0 - 1141085 futex_ pts/0  00:00:00 llvmpipe-1
1 S  1000 30271  1609 30275  0  80   0 - 1141085 futex_ pts/0  00:00:00 llvmpipe-2
1 S  1000 30271  1609 30276  0  80   0 - 1141085 futex_ pts/0  00:00:00 llvmpipe-3
1 S  1000 30271  1609 30277  0  80   0 - 1141085 futex_ pts/0  00:00:00 llvmpipe-4
1 S  1000 30271  1609 30278  0  80   0 - 1141085 futex_ pts/0  00:00:00 llvmpipe-5
1 S  1000 30271  1609 30279  0  80   0 - 1141085 poll_s pts/0  00:00:00 QDBusConnection
1 S  1000 30271  1609 30280  1  80   0 - 1141085 futex_ pts/0  00:00:25 bitcoin-shutoff
1 S  1000 30271  1609 30281  5  80   0 - 1141085 futex_ pts/0  00:02:25 bitcoin-scriptc
1 S  1000 30271  1609 30282  5  80   0 - 1141085 futex_ pts/0  00:02:23 bitcoin-scriptc
1 S  1000 30271  1609 30283  5  80   0 - 1141085 futex_ pts/0  00:02:23 bitcoin-scriptc
1 S  1000 30271  1609 30284  5  80   0 - 1141085 futex_ pts/0  00:02:26 bitcoin-scriptc
1 S  1000 30271  1609 30285  5  80   0 - 1141085 futex_ pts/0  00:02:25 bitcoin-scriptc
1 S  1000 30271  1609 30286  0  80   0 - 1141085 futex_ pts/0  00:00:11 bitcoin-schedul
1 S  1000 30271  1609 30288  0  80   0 - 1141085 futex_ pts/0  00:00:01 QThread
1 S  1000 30271  1609 30322  0  80   0 - 1141085 sk_wai pts/0  00:00:00 bitcoin-dnsseed
1 S  1000 30271  1609 30336  0  80   0 - 1141085 poll_s pts/0  00:00:00 QThread
1 S  1000 30271  1609 30346  0  80   0 - 1141085 poll_s pts/0  00:00:00 Qt bearer threa
```

Have tried to close PID 30322 "bitcoin-dnsseed" by sending to it the signal SIGQUIT from htop. All bitcoin threads are closing momentary. Restarted bitcoin-qt after some minutes. Have got:
```
************************
EXCEPTION: 15dbwrapper_error       
Fatal LevelDB error: IO error: /media/nikolaypo/bitcoindb/indexes/txindex/159773.ldb: Input/output error       
bitcoin in scheduler       

```

**Comment by Nikolay-Po** [comment]
Have to say my media have a problems. Any system I mentioned in this thread was using the same HDD connected though the same USB3.0-SATA adapter. Have started badblocks and got several of:
```
221404
221405
221406
221407
570580248
570580249
570580250
570580251
570582296
570582297
570582298
570582299
570582300
570582301
```

May be even more bads because the test was not finished.
So the cause of a problem may be the data corruption. Does DNSseed depends on data on disk somehow? May be these files need to be examined?
