### ISSUE TITLE
Entity Too Large 

### ISSUE THREAD

**Issue by jiyongieee** [bitcoin/bitcoin#16663]
Client error: POST <public IP address removed> resulted in a 413 Request Entity Too Large response:

I got error when using decoderawtransaction. I already set the post_max_size = 2G and upload_max_filesize = 2G in php.ini. In apache, I already set the LimitRequestBody 104857600.

Where do I need to change in order to pass this error? Thank you.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base, not to provide user support for apache or php. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
