### ISSUE TITLE
tests: Potential improvements to new CI setup

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16664]
Following #16582 and #16623, there are some potential improvements that could be made to the new CI setup:

* ~~[It'd be handy if the Docker containers were named. amd64_qt is more useful than peaceful_rubin once there are a bunch floating around.](https://github.com/bitcoin/bitcoin/pull/16623#pullrequestreview-275768283)~~ Done in #18081.
* [Maybe we could stop (although not destroy) containers automatically after successful completion of the tests?](https://github.com/bitcoin/bitcoin/pull/16623#pullrequestreview-275768283)
* [The ci is generally assuming the the folder is a fresh git clone. If needed, that can be changed later on, but better not part of this pull.](https://github.com/bitcoin/bitcoin/pull/16582#issuecomment-521628900)

**Comment by MarcoFalke** [comment]
See also #17544

**Comment by mackalex** [comment]
Is this issue still relevant after what I understand to be a switch from Travis CI to Cirrus CI? I'm a first-time contributor and would like to work on this issue if it's still of use.
