### ISSUE TITLE
Replace `-banscore` with `-ignoremisbehaviour`

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#16683]
While looking at #16682, @jnewbery noted to me in person that we should probably remove the `banscore` knob.

My thought is perhaps it could be replaced with a more useful debug flag like `-ignoremisbehaviour`.

**Comment by jnewbery** [comment]
concept ACK. `-banscore` seems to be not a very useful configuration option, especially since our own internal misbehaviour accounting can change between releases (eg #15141)

**Comment by fanquake** [comment]
`-banscore` was removed in #19464.

**Comment by MarcoFalke** [comment]
Is there a use case to allow a wildcard ignoremisbehaviour for all peers? It might be better to have a per-peer flag(s) that can be toggled (similar or identical to net permissions) for known peers or peers controlled by the user themselves.

**Comment by jnewbery** [comment]
@MarcoFalke I can't think of a usecase for that. I think we should just close this issue now that `banscore` has been removed.
