### ISSUE TITLE
missing destructor in classes, CLANG issue 

### ISSUE THREAD

**Issue by BlockMechanic** [bitcoin/bitcoin#16685]
When compiling with clang (android build, may also affect macOS), i get a repeated warning :- 
`warning: destructor called on non-final 'CBlockHeader' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]`

It can be reproduced using ndk 20 and all api above 24 so far. Unavoidable because google has deprecated use of GCC and only clang remains.

**Comment by sipa** [comment]
CBlockHeader does not have any virtual functions?

**Comment by BlockMechanic** [comment]
It has, and it is fine when i use native gcc on ubuntu , but all builds for android now require clang, and the latest ndk uses a recent version of which introduced `-Wdelete-non-virtual-dtor`

**Comment by sipa** [comment]
I don't see any virtual functions, and it shouldn't have any.

**Comment by BlockMechanic** [comment]
none declared yet for some reason the warning pops up. 

Build system is ubuntu 18.04 
using depends sytem to compile for android arch x86 
ndk 20 api level 24 & higher

**Comment by hebasto** [comment]
@BlockMechanic which version of Clang produces those warnings?

**Comment by laanwj** [comment]
Neither CBlockHeader nor anything derived from it should have virtual functions. If it does, that's a bug. Can you get more verbose output from your compiler somehow?

**Comment by fanquake** [comment]
Going to close this due to no followup. We can re-open here if/when more info is provided.
