### ISSUE TITLE
{Shutdown: In progress...} in init.cpp takes forever

### ISSUE THREAD

**Issue by naumenkogs** [bitcoin/bitcoin#16699]
I noticed that ```return false``` anywhere in ```AppInitMain``` after 1773 line (```connOptions.m_peer_connect_timeout = peer_connect_timeout;```) doesn't do what it's supposed to do: the process is never getting terminated, so I have to kill it manually.

You can reproduce it by manually inserting ```return false``` there, but we also rely on it to handle some errors, e.g. invalid ```whitebind```provided.

Noticed it in current master on MacOS.

**Comment by MarcoFalke** [comment]
I can not reproduce on current master on Ubuntu Bionic.

Could you try to bisect to check if this happens when you put the `return false` anywhere? Also, does `make check` and the functional tests pass?

**Comment by naumenkogs** [comment]
Okay, so this was not current master, but master from February. Closing for now, must have been fixed.
