### ISSUE TITLE
ADD_ONION assumes bitcoind to reside in hardcoded 127.0.0.1

### ISSUE THREAD

**Issue by henrikuittinen** [bitcoin/bitcoin#16693]
https://github.com/bitcoin/bitcoin/blob/d72758c3f6c34cd835f5de3efc230964f3b1ea56/src/torcontrol.cpp#L539

If a user is running Tor proxy outside localhost (perhaps on other host inside LAN or in containerised environment) , the automatic creation of onion services ends up creating an onion service listening to hardcored 127.0.0.1 address on the Tor proxy's host instead of the private address of the bitcoind – effectively running an empty onion service listening the Tor proxy's localhost.

**Comment by emilengler** [comment]
Good point but do people actually run Tor outside?
Everyone who really wants to protect his privacy through Tor would never do this

**Comment by henrikuittinen** [comment]
> Good point but do people actually run Tor outside?

I'd say it's relatively common to have a separate Tor proxy in your LAN somewhere, not necessarily on the same host. Especially if you're running stuff in containers.

**Comment by sipa** [comment]
@henrikuittinen Sure, but how would you be using the Tor control interface in that case?

**Comment by henrikuittinen** [comment]
> @henrikuittinen Sure, but how would you be using the Tor control interface in that case?

Through `-torcontrol=<ip>:<port>` and `-torpassword=<pass>`. It connects perfectly and creates a hidden service, but assumes the bitcoind is in `127.0.0.1` – which is of course hardcoded now.

**Comment by sipa** [comment]
Oh, interesting. That sounds like a bug.

**Comment by henrikuittinen** [comment]
Yeah, it's right here:
https://github.com/bitcoin/bitcoin/blob/d72758c3f6c34cd835f5de3efc230964f3b1ea56/src/torcontrol.cpp#L539

I reckon instead of hardcoding `127.0.0.1` it should take in `GetBindAddress()`.

**Comment by meeDamian** [comment]
Wow, I've spent so much time trying to figure out why the `bitcoind` I run in a container doesn't want to work with Tor on host, and inventing dirty hacks to go around that 😬.  Needless to say, glad this issue exists :).

**Comment by hebasto** [comment]
@henrikuittinen Mind testing #19991?

**Comment by henrikuittinen** [comment]
> @henrikuittinen Mind testing #19991?
Unfortunately I don't have this setup anymore. Thanks for the PR though!
