### ISSUE TITLE
Generate release tarball with git archive

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16734]
A lot of files are missing from the release tarball (see #6753), so it would probably be easier and more consistnet to just replace it with a simple call to `git archive` than to enumerate every single file and add it to the dist target in the Makefile.

**Comment by ch4ot1c** [comment]
So should we avoid `make dist` in the gitian builds, or put a `git archive` step in the dist-hook? The latter would make two tarballs & have issues with gitignore, which is undesirable. But at the same time, not using `make dist` goes against autotools principles.

Also, the generated build files are automatically added to the tarball in `make dist`. If we plan to `git archive` the original source, they'd still have to be generated and appended. `EXTRA_DIST` directories might just be easier for standard `make` targets.

Generated files that we want to include (I think):
```
aclocal.m4
Makefile.in
configure
config.guess
config.sub
(recursive)

ltmain.sh
install-sh
depcomp
(recursive)

src/config/bitcoin-config.h.in
src/secp2561/src/libsecp256k1-config.h.in
```

Related info:
https://www.gnu.org/software/automake/faq/autotools-faq.html#Which-files-are-hand_002dwritten-and-which-generated-_0028and-how_0029_003f

**Comment by MarcoFalke** [comment]
The autotools faq just say that `configure` (et al.) are "Generated on the developer system", but don't give a reason for it. I think it is fine and not too much to ask of a user that wishes to compile from source to call `./autogen.sh && ./configure && make` instead of `./configure && make`.

**Comment by ryanofsky** [comment]
> but don't give a reason for it

It's probably ok to require autogen. I think historically configure scripts were supposed to work on obscure unix systems that would just have a generic shell + make tool + c compiler, and not necessarily need gnu packages like m4 which are needed for autogen.

**Comment by laanwj** [comment]
Yes, concept ACK, I think. I also think it's fine to require autogen. What is one dependency more, if you're building from source.

I suppose the practical issue is: is `git archive` output deterministic?

**Comment by ch4ot1c** [comment]
@laanwj I think we'll still have to use `faketime`, even though the archive doesn't include the `.git` directory. Nearly deterministic.

Here's what I've come up with so far, based on above discussion:

```
dist-hook:
	- $(GIT) archive --format=tar HEAD -- src/clientversion.cpp | $(AMTAR) -C $(top_distdir) -xf -
	- $(GIT) rm ".gitignore"; $(GIT) add ".gitignore"; $(GIT) stash --all;
	- $(GIT) archive --prefix="$(PACKAGE)-$(VERSION)/" stash@{0} -- . >"$(PACKAGE)-$(VERSION)-archive.tar.gz
	- $(GIT) stash pop
	- $(GIT) checkout -- ".gitignore"
```

Remaining problems:

1. Creates two archives, since `make dist` creates one automatically (swallow somehow?). Therefore, for now the `git archive` output has `-archive` as a suffix.
2. Not deterministic
3. Compatibility with existing gitian descriptors

I'm less familiar with the Gitian system, so I'll read up on it, but feel free to run with this example.

**Comment by MarcoFalke** [comment]
The hook is run after dist, so you could just overwrite the previous archive?

**Comment by ch4ot1c** [comment]
Been trying - it seems to always make the *very* last step its tarball creation, so it's troublesome to overwrite.

Efforts at
https://github.com/bitcoin/bitcoin/pull/17104

**Comment by laanwj** [comment]
> The hook is run after dist, so you could just overwrite the previous archive?

I don't think it's desirable for it to do the work twice.

If it's too involved to override autotool's own machinery, an alternative would be to stop using `make dist` to generate the tarball and use `git archive` directly from the descriptors. That's where the tarballs for distribution are produced.
