### ISSUE TITLE
[Illumos] test/test_bitcoin_fuzzy fails, symbol errors

### ISSUE THREAD

**Issue by kayront** [bitcoin/bitcoin#16741]
Following up on #15708, in my local system everything is working up until this:

```
  CXXLD    test/test_bitcoin_fuzzy
Undefined                       first referenced
 symbol                             in file
getnameinfo                         libbitcoin_common.a(libbitcoin_common_a-netaddress.o)  (symbol belongs to implicit dependency /lib/amd64/libsocket.so.1)
ld: fatal: symbol referencing errors. No output written to test/.libs/test_bitcoin_fuzzy
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:4481: test/test_bitcoin_fuzzy] Error 1
```

With --disable-tests this error wouldn't happen, but while I'm working on this, why not leave everything working.

Could the above be easily fixed for Illumos (SmartOS in this case) systems?

**Comment by kayront** [comment]
Hey, sorry, I was in a bit of a hurry yesterday and wanted to get the ticket opened before leaving.

This is against bitcoin v0.17.1 release, with your patches for FD_ZERO added (they work, by the way).

Recall that in the previous issue, it begun with tests errors, and then devolved into something else (not tests related) where it stalled.

To clarify, this situation is different: it still fails in some sort of tests, but it's near the end of the whole process now and not related to not having hexdump around.

And the malfunctioning binary produced in the previous attempt was likely the result of having tried to compile one Empact's older branches.

I am working on patching the pkgsrc port so that bitcoin becomes available as a package for SmartOS - the current code without your patches will not even build, so I have already included said patches in the port, and now it's failing because of the error here.

It works with --disable-tests, but as I said, why not do it right from the start and try to get it to work already.

The problem to my naive C++ eyes seems to be that some symbol that causes no issues in other systems is already defined by some Solaris library and causes it to fail.

**Comment by MarcoFalke** [comment]
Does this also happen on the 0.18 release or current master?

**Comment by MarcoFalke** [comment]
#15146 was just merged, but probably unrelated to your issue

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
