### ISSUE TITLE
Transifex organization issues

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#16754]
So I've had issues with the transifex organization for a whlie.

A long time ago, the organization where the bitcoin project is under, [bitcoin](https://www.transifex.com/bitcoin/), was created by a person named seone. They gave me and @luke-jr maintainer access to the project, but not full control over the organization.

This means I'm unable to access the [teams](https://www.transifex.com/bitcoin/teams/) page, to make people translation coordinator and such, even though I get a lot of requests to do so.

I've tried to contact seone in different ways but never heard anything back from them. If anyone knows them IRL or by another handle, please help contact them so that they can transfer the organization.

If not, I think the only sane thing to do is moving the translations to the [bitcoincore](https://www.transifex.com/bitcoincore/) organization (for which I have full access to organization settings, and which also has the translations for the bitcoincore.org website) for 0.19.
This will mostly involve updating some links, I expect.

**Comment by laanwj** [comment]
FWIW 0.19 translations are scheduled to open in a few days (2019-09-01, see #15940), so we'll need a fairly quick decision here.

**Comment by GChuf** [comment]
I think in this case moving the translations somewhere else would be the best thing to do (bitcoincore link returns 404 for me - is the project private?). The sooner this is done, the better.
The fact that there are also translations for the website there makes it even better.

Moving all the translations could be done in less than a day (I can do it), but the issue would be to let the people know we've moved. Apart from updating the links we'd also have to let people know on social media and on the "old" transifex project as well. However, I believe that if some of us make an effort to let people know we moved (and that we need new translators), a lot of new people will join.

Staying on the old project without full access is only going to get worse with time.

**Comment by MarcoFalke** [comment]
> which also has the translations for the bitcoincore.org website

I know this is off-topic, but are the translations for the website synced regularly? If not, it doesn't seem worth it to keep them there.

**Comment by laanwj** [comment]
I have no idea really, maybe @harding knows.

**Comment by wtogami** [comment]
Thursday's meeting decided to "wait one week" while I attempt to ask the company for help. I found that I last conversed with them ~5 years ago. I sent an e-mail now. If I don't hear back by Monday I will try to call or drop by their office which is apparently near me.

**Comment by harding** [comment]
@marcofalke

> I know this is off-topic, but are the translations for the website synced regularly? If not, it doesn't seem worth it to keep them there.

BitcoinCore.org doesn't use the Transifex infrastructure currently (I'm not sure it ever did).  Translations for the website are currently submitted via normal PRs, which works for me, so I'm good with dropping them from Transifex.

**Comment by glezos** [comment]
I'm happy to help you guys on behalf of the Transifex team. What username should we add as an admin to the organization?

**Comment by glezos** [comment]
Fixed — Warren, I've added you as an admin. You can add more admins under https://www.transifex.com/bitcoin/settings/.

**Comment by wtogami** [comment]
Added @laanwj as admin. He can decide to add other admins.

**Comment by glezos** [comment]
Feel free to message our team at support@transifex.com if you need any similar help in the future, we're here listening. :-)

**Comment by glezos** [comment]
> Translations for the website are currently submitted via normal PRs, which works for me, so I'm good with dropping them from Transifex.

@harding In case it's helpful, there's a [GitHub integration](https://docs.transifex.com/transifex-github-integrations/github-tx-ui) that allows translators to work online and automatically create pull requests, in case it's of interest. Or simply you can use the command-line client to sync files during the build process or via continuous integration.

**Comment by fanquake** [comment]
Guess we can close this as fixed. @laanwj can follow up if he has any issues with the admin role.

**Comment by promag** [comment]
That was fast! Awesome @glezos! 👏

**Comment by laanwj** [comment]
Thank you so much @glezos. That was really fast. It works now.
