### ISSUE TITLE
Sweep up dust inputs when there is room

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#1675]
The coin selection should automatically sweep up excessive small / dust inputs in order to get them out of the txout set when there is room and the txn already has change. (e.g. excess priority before the txn loses freeness, or room before the next kiliobyte fee increment)

This can be done as a post-processing step after the existing selection.

Care should be taken to avoid reducing privacy by linking otherwise independent accounts. This can sometimes increase privacy by further disguising the values exchange.

**Comment by MarcoFalke** [comment]
@gmaxwell This can be closed. We finally got rid of rounding up to the next 1kB in #7103 (rebase of #6708) and it's really unlikely those changes get reverted.

**Comment by Empact** [comment]
@MarcoFalke I suppose you can close this now that you're a member?
