### ISSUE TITLE
Error: - 32 deprecatedrpc

### ISSUE THREAD

**Issue by sriharikapu** [bitcoin/bitcoin#16763]
I was using 0.18 V

My codes are based on default account system provided by bitcoin core 0.16. 

But I came to know that accounts are depricated in 0.18 and above. Now I am struck with the errors for all my cli commands and my scripts

Please let me know how to fix this. 

![IMG_20190830_110429](https://user-images.githubusercontent.com/6247133/64000063-f95ec480-cb15-11e9-8a19-2c37123b6794.jpg)

**Comment by leto** [comment]
Downgrade or do not use accounts. They never worked correctly or well which is why they were deprecated

**Comment by sriharikapu** [comment]
But @leto I had never faced any issue with the accounts previously. until this v0.18. Never mind, the solution is to `downgrade`. Thanks a lot.

**Comment by MarcoFalke** [comment]
What code are you using to speak with the rpc interface? You should report the issue to them.

**Comment by sriharikapu** [comment]
I was using NodeJS @MarcoFalke

**Comment by MarcoFalke** [comment]
Who wrote the code? Where did you get it from?

**Comment by sriharikapu** [comment]
@MarcoFalke I wrote the code. based on Bitcoin core 0.16 [API Call list](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list)

**Comment by MarcoFalke** [comment]
In that case there is nothing we can do. It is up to you to fix your code to make sure it only runs with versions you support (0.16 et al) or update it to also work with 0.18
