### ISSUE TITLE
Bech32 typo detection

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#16779]
It would be nice to have bech32 typo detection in both the RPC and GUI.

@sipa wrote a demo for this years ago:

<img width="754" alt="Schermafbeelding 2019-09-01 om 11 44 44" src="https://user-images.githubusercontent.com/10217/64074621-ed0d6f80-ccad-11e9-9dca-aedbbeff3fa4.png">

http://bitcoin.sipa.be/bech32/demo/demo.html

**Comment by emilengler** [comment]
The magic is happening [here](http://bitcoin.sipa.be/bech32/demo/demo.js)
@sipa Do you have a non obfuscated version of this?
The script could be ported to C++ very easily probably

**Comment by sipa** [comment]
https://github.com/sipa/bech32/blob/master/ecc/javascript/bech32_ecc.js

**Comment by Sjors** [comment]
RPC support just landed, thanks @meshcollider!

**Comment by fanquake** [comment]
Now that this issue is gui-only, I've moved it to the GUI repo: https://github.com/bitcoin-core/gui/issues/527.
