### ISSUE TITLE
Reindex Chainstate

### ISSUE THREAD

**Issue by CryptoSigmund** [bitcoin/bitcoin#16777]
Recently had problems with my chainstate running on my Raspbian Buster on a RaspiPi4. So I started a 

> -reindex-chainstate

 and now it's running for 1 1/2 days. Is there any possibility to see the actual progress?

I just found this also unaswered question here:
https://bitcoin.stackexchange.com/questions/60709/when-should-i-use-reindex-chainstate-and-when-reindex/60711

Regards

![Bildschirmfoto 2019-09-01 um 07 55 05](https://user-images.githubusercontent.com/44261656/64072405-e0791f00-cc8d-11e9-8221-13fbe7d701a3.png)

**Comment by sipa** [comment]
`bitcoin-cli getblockchaininfo` will show you the progress, I believe.

**Comment by sipa** [comment]
In the future, please direct questions about usage to https://bitcoin.stackexchange.com.
