### ISSUE TITLE
Recent update to boost m4 lost error reporting improvements

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#16803]
Back in 2014 I made some error reporting changes in 25333a26197b55c23debb38740ed875999aa795a (#3986), to do with reporting the exact boost library that was not being found. These were recently (unintentionally, I assume) removed in aa85dcf47288e86f283f38fe47c022ffcfa53d8b (#13095) by @fanquake.

I'm not sure how much of a problem this is, but wanted to create an issue nevertheless because these this error still gets reported all the time and for troubleshooting it was useful: https://github.com/bitcoin/bitcoin/issues/3219#issuecomment-527771749 .

If people feel this is worth it it'd be trivial to re-do the change.

**Comment by fanquake** [comment]
I've opened a PR upstream to improve the error reporting of all the Boost macros, and will pull the changes into our repository once they it has been merged.

**Comment by laanwj** [comment]
Thank you @fanquake
