### ISSUE TITLE
qt: Some translations have leading / trailing whitespace characters

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#16814]
I know translations are managed on Transifex, but I noticed an oddity: some translations contain untrimmed whitespace.

- https://github.com/bitcoin/bitcoin/blob/5e202382a987351a59d5cda98ea9f2aee99f61a5/src/qt/locale/bitcoin_ar.ts#L2729
- https://github.com/bitcoin/bitcoin/blob/5e202382a987351a59d5cda98ea9f2aee99f61a5/src/qt/locale/bitcoin_ro_RO.ts#L2315

Do we need a linter / script to handle these cases?

**Comment by promag** [comment]
> to handle these cases?

Handle how?

**Comment by ch4ot1c** [comment]
> > to handle these cases?
> 
> Handle how?

By trimming them. It could happen in Transifex, or when copied to the repo.

**Comment by fanquake** [comment]
Not sure if this is something that needs to be fixed or not. @laanwj is probably the right person to ask. In either case, any sort of trimming would probably be added to the [`update-translations.py` script](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/update-translations.py).

**Comment by laanwj** [comment]
Honestly I'd leave it alone unless it causes actual problems for users. Resist the temptation to fix what isn't broken and muck around with spaces.

**Comment by laanwj** [comment]
Closing this, I don't think this is really an issue.

**Comment by MarcoFalke** [comment]
I think this should be fixed, but on transifex via https://docs.transifex.com/setup/setting-translation-checks

**Comment by GChuf** [comment]
FWIW whitespaces were manually fixed on transifex by me (for a whopping 8kB of disk space gained) but I agree with Marco that we should set up translation checks on transifex.

**Comment by MarcoFalke** [comment]
Note that some *source* strings have trailing whitespace, so removing it will cause alignment issues for the translations.

**Comment by GChuf** [comment]
@MarcoFalke I found exactly one occurence in `bitcoin_en.ts`, and I'm thinking it's a typo. Alignments are done by `qt`, I believe?

![source](https://user-images.githubusercontent.com/42591821/67159447-59166680-f334-11e9-9a60-50b2f9b10964.png)

**Comment by GChuf** [comment]
I checked again and there are 3 trailing whitespaces in `bitcoin_en.ts` in branch `0.19`, as opposed to 1 trailing space in `master`. Your number 54 corresponds to all trailing spaces from all translation files in src/qt/locale in `master`.

Strings in question:
```
src/qt/locale/bitcoin_en.ts:        <source>Your wallet is about to be encrypted. </source>
src/qt/locale/bitcoin_en.ts:        <source>Your wallet is now encrypted. </source>
src/qt/locale/bitcoin_en.ts:        <source>Wallet: </source>
```

I see absolutely no reason to add a trailing whitespace to the first 2 strings, and as for _wallet_ - you'll notice there are actually 2 strings being translated: `wallet` and `wallet_`. So again, I'm guessing they're all typos.

Trailing whitespaces should never be translated and we should not rely on them for alignment - this could create multiple problems and is an overall bad idea, and I doubt anyone had this idea in mind when appending those 3 whitespaces.
Also, translators have no way of seeing trailing whitespaces on transifex (apart from selecting the source string with the mouse manually), which means noone was ever "translating" them.

**Comment by MarcoFalke** [comment]
They are not typos, but oversights of putting trailing whitespace used for formatting into the source message:

```
$ git grep 'Your wallet is about to be encrypted. "'
src/qt/askpassphrasedialog.cpp:                                         tr("Your wallet is about to be encrypted. ") + encryption_reminder +
```

There are two fixes needed here:

* A transifex check to enforce the trailing whitespace is preserved
* (optional) remove the trailing whitespace from the translation source message
