### ISSUE TITLE
doc: Consider adding README.md to build-aux/, share/, src/

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#16813]
All depth 1 directories, excluding `.github` and `.tx`, have `README.md` files except 3:

- `build-aux/`
- `share/`
- `src/`

Do they deserve one each, to match their siblings?

**Comment by MarcoFalke** [comment]
I think it makes sense to add a readme to `src/` and mention the code organization (#15732). Or is that better put in the existing developer notes?

**Comment by EricPonvelle** [comment]
I don't mind taking this.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
