### ISSUE TITLE
Follow ups from #15450

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16820]
There's a few small issues left over from #15450:

* [Focusing](https://github.com/bitcoin/bitcoin/pull/15450#pullrequestreview-282297760) on the `Encrypt Wallet` dialog after clicking `Create Wallet`.
> ```cpp
> m_passphrase_dialog->setWindowModality(Qt::ApplicationModal); 
> m_passphrase_dialog->show();
> ```

* Wallet [name escaping issue](https://github.com/bitcoin/bitcoin/pull/15450#pullrequestreview-282297760):
> This is at least one inconsistency where if you create a wallet with a HTML escaped character in the name, i.e Alice & Bob, then the & will not be shown in some menus / dialogs.

* Nits from this [review](https://github.com/bitcoin/bitcoin/pull/15450#pullrequestreview-284450044).

**Comment by jonatack** [comment]
On it.

**Comment by jonatack** [comment]
Possibly also point #5 of https://github.com/bitcoin/bitcoin/pull/15450#issuecomment-502497304, e.g. interactive passphrase match validation, or at least in the same dialog. Though this may be more involved/for later.

**Comment by jonatack** [comment]
Also found and fixing:
```
$ git grep askPasshprase
src/qt/walletcontroller.cpp:182:void CreateWalletActivity::askPasshprase()
src/qt/walletcontroller.cpp:250:            askPasshprase();
src/qt/walletcontroller.h:121:    void askPasshprase();
```

**Comment by jonatack** [comment]
Unable to reproduce the auto-focus issue in the Encrypt wallet dialog with Debian. Will test on macOS.

**Comment by jonatack** [comment]
Reproduced the auto-focus issue on macOS; the proposed fix resolves it.

**Comment by achow101** [comment]
For the most part, the HTML escaping issue doesn't seem to actually be due to HTML. The places where the wallet name is being rendered don't allow HTML for the name. The only place that seems to be having issues is the Open Wallet menu. The issue there appears to be because [QAction strips down the text](https://doc.qt.io/qt-5/qaction.html#QAction-1) so things like `&` get dropped.

I did find one instance of HTML actually needing to be escaped though.

**Comment by jonatack** [comment]
Makes sense. Noticed two things after starting to look at it:

- HTML escaping src/qt/bitcoingui.cpp::L378 like at src/qt/walletcontroller.cpp::L282 does display the ampersand (but obvs in HTML escaped format) so it's there but being dropped.

- Look like this issue predates #15450. Tried an earlier build to confirm.

**Comment by achow101** [comment]
I'm working on a fix for the HTML stuff.

**Comment by jonatack** [comment]
Cool. Removing it from the #16822 checklist.
