### ISSUE TITLE
[QT] Startup Rescan: Progress Bar

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#16823]
Bitcoin Core 0.18
Expected Behaviour: Progress bar. Console-initiated rescans have progress bars and are abortable after the following issue was closed: https://github.com/bitcoin/bitcoin/issues/10992
Actual behaviour: No progress bar.
Tested on Win64. 
![xgjgLHH](https://user-images.githubusercontent.com/50526615/64475214-fac86680-d17f-11e9-80d5-aa96fec406dc.png)

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

Also, you might want to consider using the rescan RPC instead (which is definitely abortable)
