### ISSUE TITLE
rpc: multi-wallet changes breaks backward compatibility

### ISSUE THREAD

**Issue by kristapsk** [bitcoin/bitcoin#16832]
On current master if you call `listaddressgroupings` or `getaddressesbylabel` you get error:
```
error code: -19
error message:
Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).
Try adding "-rpcwallet=<filename>" option to bitcoin-cli command line.
```
This currently breaks JoinMarket and possibly other software.

JoinMarket has internal wallets, imports addresses into Bitcoin Core wallet only for watch-only.

**Comment by MarcoFalke** [comment]
You could work around that by only loading one wallet when using JoinMarket?

**Comment by sipa** [comment]
Or can a different RPC URL be configured? The wallet name is passed in the URL to avoid this issue.

**Comment by kristapsk** [comment]
Ohh, I didn't know it depends on is multiple wallets loaded. Makes sense. Just tested, behaviour with v0.18 is the same. Yes, looks like something that should be handled in JoinMarket code.
