### ISSUE TITLE
depends: `sed` robustness

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#16838]
As seen in https://github.com/bitcoin/bitcoin/pull/16837, the `sed` calls in `depends` fail silently, and can result in silent, unwanted regressions when packages are updated.

It seems that a possible solution might be something like the following: https://askubuntu.com/a/1036918

**Comment by laanwj** [comment]
+1 for improving robustness here. Silently failing errors are horrible for troubleshooting.

**Comment by fanquake** [comment]
I spent some time looking at this today. Would it be ok if we required gnu `sed` in depends (there is some precedent as we require `glibtoolize` elsewhere in the build system)? Otherwise I'm not sure that the suggested approach would work out of the box on macOS (BSD sed).

I did have a look at the approach in https://stackoverflow.com/a/28966696, but that seemed a bit messy. Will revisit later on.

**Comment by laanwj** [comment]
Doesn't `sed -i` already rely on GNU sed? I don't remember seeing it in BSDs.

**Comment by MarcoFalke** [comment]
Couldn't we mock (or wrap) `sed` while doing depends? That way we can control the exit code.

A wrapper that does the following, should be good enough:
```
  - check that ${file}_BACKUP does not exist
  - run replacement with unmodified sed on $file, additionally passing `--in-place=_BACKUP`
  - assert that $file differs from $file_BACKUP
  - delete $file_BACKUP

**Comment by dongcarl** [comment]
> Couldn't we mock (or wrap) `sed` while doing depends? That way we can control the exit code.
> 
> A wrapper that does the following, should be good enough:
> 
> ```
>   - check that ${file}_BACKUP does not exist
>   - run replacement with unmodified sed on $file, additionally passing `--in-place=_BACKUP`
>   - assert that $file differs from $file_BACKUP
>   - delete $file_BACKUP
> ```

How would we make that wrapper accessible in the Makefile? Somethine like `SHELL = /usr/bin/env PATH=$(CURDIR)/wrappers:${PATH} sh`?

**Comment by MarcoFalke** [comment]
Yeah, something like that.

**Comment by fanquake** [comment]
I've removed "good first issue" here, as the remaining `sed` usage is basically contained to qt (1 in libxcb that we ), and is non-trivial to remove.
