### ISSUE TITLE
Encrypted RPC requests

### ISSUE THREAD

**Issue by 3s3s** [bitcoin/bitcoin#16862]
**Is your feature request related to a problem? Please describe.**

A virus on a computer can listen to unencrypted RPC traffic and an attacker can steal Bitcoins even from an encrypted wallet

**Describe the solution you'd like**

It is necessary to implement support for encrypted public key RPC calls in Bitcoin Core as it done in the https protocol

**Comment by emilengler** [comment]
IIRC RPC requests are over http (correct me if I am wrong).
Bit I agree that we need SSL support

**Comment by sipa** [comment]
A virus on the computer can replace the `bitcoind` binary with one that steals your coins regardless. There is no way around running Bitcoin on untrusted hardware.

**Comment by 3s3s** [comment]
We can easily authenticate bitcoind with hash or other checksum, but it’s much harder to learn about listening to traffic and to recognize the authenticity of RPC requests

How stunnel can help to prevent from sniffing RPC on localhost?

**Comment by sipa** [comment]
Again, if the attacker has that kind access to the machine that runs bitcoind, he can do lots of other things too. Overwriting the binary is just one. Another is just reading the decrypted keys from RAM.

**Comment by 3s3s** [comment]
I think that readig specific region of RAM from another process is too complicated operation by comparison with traffic listenig. Snoffing is the most common functionality of trajans, but RAM listenig should by designed for one specific process with one specific binary version

**Comment by sipa** [comment]
Sorry, that's nonsensical. All it needs is one smart guy to write a tool for hijacking wallets by running in a place with sufficient access to bitcoind. The threat model cannot possibly protect against that. Trying to use encrypted traffic to circumvent that will only contribute to a false sense of security.

Here is the discussion around removing it: https://github.com/bitcoin/bitcoin/pull/5677#issuecomment-71181146

**Comment by 3s3s** [comment]
That discussion is about "expose bitcoind RPC to a public accessible area"
But using encrypted RPC on localhost was not discussed. 
I think encrypting RPC on localhost will really increase security.

**Comment by sipa** [comment]
> I think encrypting RPC on localhost will really increasy security.

I've shown that it cannot.
