### ISSUE TITLE
armhf GUI: Permission denied: "/database/lost+found/wallet.dat" Aborted

### ISSUE THREAD

**Issue by Nikolay-Po** [bitcoin/bitcoin#16877]
Bitcoin Core version v0.18.99.0-4bfef0dae-dirty
Compiled natively on "Linux Debian-Desktop 4.4.185 #1 SMP Fri Jul 19 14:34:55 EDT 2019 aarch64 GNU/Linux"

```
./autogen.sh
./configure --disable-debug CFLAGS="-g0 -O3" CXXFLAGS="-g0 -O3" BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --enable-werror --with-qrencode --enable-cxx --disable-shared --with-pic --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
```
GUI runs OK. And noticeable faster than previously compiled (with debug enabled) v0.18.99.0-495db72ee-dirty. But both

- Bitcoin Core version v0.18.99.0-495db72ee-dirty (debug enabled, default optimization)
- Bitcoin Core version v0.18.99.0-4bfef0dae-dirty (debug disabled, -O3)

are crashing when mouse cursor is pointed to File/OpenWallet menu item. Starting parameters are the same:

bitcoin-qt -datadir=/bdb -nodebug -dbcache=1536

/bdb is dedicated RAID1 volume with bitcoin database inside. Console output:

```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Permission denied: "/bdb/lost+found/wallet.dat"
```
There is nothing about the crash in debug.log before sudden application abort.
I'm wondering for what purpose to access the wallets in lost+found folder? I thought there may be a problems with access rights for that folder. I have deleted lost+found and executed fsck -f /dev/md0 for /bdb directory volume. The problem still here.
While configuring the build, I had to add
```
--with-boost-libdir=/usr/lib/arm-linux-gnueabihf
```
because configure script was unable to find boost executables.

**Comment by MarcoFalke** [comment]
I'd suggest that you create a dedicated folder for the bitcoin core datadir, and not use the root of the storage. The root is often used by other processes, such as `fsck` in your case with the `lost+found` dir.

I don't think there is anything we can do here.

**Comment by Nikolay-Po** [comment]
Thanks! The move of the database to dedicated folder at the same volume have solved the problem!
