### ISSUE TITLE
doc: Consider installing doc/ with make install

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#16897]
Do we want to `make install` `doc/` into `/usr/local/share/doc/bitcoin/` (see `docdir` in https://www.gnu.org/prep/standards/html_node/Directory-Variables.html)? Currently, man pages are installed to `/usr/local/share/man/man1/bitcoin*`.

This describes `contrib/debian/copyright` being placed here as well: 
https://www.debian.org/doc/debian-policy/ch-archive.html#copyright-considerations

Furthermore, files like `README.md` and `INSTALL.md` could have their extensions removed in the dist-hook. 
 `automake --help` has a list of `Files automatically distributed if found` (e.g. `make dist` will include):
```
Files automatically distributed if found (always):
  ABOUT-GNU           INSTALL             config.rpath        ltconfig
  ABOUT-NLS           NEWS                config.sub          ltmain.sh
  AUTHORS             README              depcomp             mdate-sh
  BACKLOG             THANKS              install-sh          missing
  COPYING             TODO                libversion.in       mkinstalldirs
  COPYING.DOC         ar-lib              ltcf-c.sh           py-compile
  COPYING.LESSER      compile             ltcf-cxx.sh         texinfo.tex
  COPYING.LIB         config.guess        ltcf-gcj.sh         ylwrap
  ChangeLog
```

**Comment by ch4ot1c** [comment]
Some existing docs like [this](https://github.com/bitcoin/bitcoin/tree/master/doc#unix) expect binaries to be at `./bin/`, which isn't true for the source repo / distribution, nor if installed.

**Comment by emilengler** [comment]
Concept ACK, the manpages aren't really useful because they are just a help2man

**Comment by willcl-ark** [comment]
Is this something that we actually want to add? IMO adding a load of (mostly) markdown files to this dir would be clunky at best...

If we don't plan for this then I think we can close the issue.

If we do then it would probably make sense to wait until the cmake project has resolved one way or another before making (low priority) changes to the make process?

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.
