### ISSUE TITLE
AppVeyor CI: combine_logs.py fails to fetch debug logs

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#16894]
In case of failures of a functional test, the logs are not combined in the AppVeyor build, examples are
https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/27454958
https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/26931920
This makes it harder to investigate the root cause of the failures of the functional tests.
Some months ago it was still working (see linked logs in #14446).

 Error message from AppVeyor Log:
```
python test\functional\test_runner.py --ci --quiet --combinedlogslen=4000 --failfast
Traceback (most recent call last):
  File "C:\projects\bitcoin/test/functional/combine_logs.py", line 198, in <module>
    main()
  File "C:\projects\bitcoin/test/functional/combine_logs.py", line 65, in main
    log_events = read_logs(testdir)
  File "C:\projects\bitcoin/test/functional/combine_logs.py", line 84, in read_logs
    chain = re.search(r'node0/(.+?)/debug\.log$', chain).group(1)  # extract the chain name
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by MarcoFalke** [comment]
The regex should use `os.path.sep` instead of hardcoding the linux one

**Comment by renepickhardt** [comment]
hopefully this should have fixed the issue. couldn't test this though.
