### ISSUE TITLE
build: make deploy on MacOS creates multiple products

### ISSUE THREAD

**Issue by ch4ot1c** [bitcoin/bitcoin#16909]
On MacOS 10.15 Beta, I ran `make deploy`, expecting to have an output of `Bitcoin-Core.dmg` per `contrib/macdeploy/README`, but instead get 3 other products -

- `Bitcoin Core.app`
- `Bitcoin-Qt.dmg`
- `dist/Bitcoin Core.app`

Should the `.dmg` be renamed?

**Comment by za-kk** [comment]
Tested this on similar specs (macOS Mojave) and also getting the same 3 files when running `make deploy` (`Bitcoin Core.app`, `dist/Bitcoin Core.app` and `Bitcoin-Qt.dmg`).

Perhaps the `contrib/macdeploy/README` should be updated instead of renaming the `.dmg`?


Software Specs:
```
ProductName:    macOS Mojave
ProductVersion: 10.14.6
BuildVersion:   18G87
```
