### ISSUE TITLE
Centralization of BIP-0044 security risk.

### ISSUE THREAD

**Issue by hatchpay** [bitcoin/bitcoin#16903]
Hello!
There was a hidden centralization of BIP-0044 by Satoshilabs. I will try to write in detail.
Satoshilabs is the sole creator of SLIP-0044, which is required for integration into most hardware and software wallets and should be equal to BIP-0044. But one of the developers of the document requires choosing the SLIP-0044 address next in the numbering from their list, and if he wants to, he can allow the number to choose. At the moment, there is a situation in which the HATCH coin is denied the receipt of the SLIP-0044 number, the reason is that the document developer simply does not want to assign the SLIP-0044 number to the HATCH BIP-0044 number and requires changing the SLIP-0044 number, which will entail a change BIP-0044 https://github.com/satoshilabs/slips/pull/761. We do not plan to change the BIP-0044 number because it can lead to unforeseen consequences. Because of this, the HATCH coin cannot be integrated into most of the TOP3 hardware wallets. For example, the HATCH coin has already been denied integration due to the lack of the SLIP-0044 number in two https://github.com/trezor/trezor-firmware/pull/520 https://github.com/keepkey/keepkey-firmware/pull/167 of the TOP3 hardware wallets. Through his actions and inaction, Satoshilabs employee harms the development of the HATCH coin. Based on the foregoing, I recommend developing measures to counteract the centralization of BIP-0044.

**Comment by sipa** [comment]
I believe you're filing this in the wrong repository. This repository is for development of the Bitcoin Core implementation of the Bitcoin protocol. It does not even implement BIP 44.

**Comment by hatchpay** [comment]
> I believe you're filing this in the wrong repository. This repository is for development of the Bitcoin Core implementation of the Bitcoin protocol. It does not even implement BIP 44.

By posting this message here we want to draw attention to the current situation. Many Bitcoin wallets have a BIP-0044 and a SLIP-0044 address 0 = 0x80000000
