### ISSUE TITLE
An error occurred while encrypting the wallet

### ISSUE THREAD

**Issue by mishasaz** [bitcoin/bitcoin#16933]
An error occurred while encrypting the wallet:
 MinGW Runtime Assertion

Assertion Failed!
Program: W: \ Bitcoin \ Bitcoin-qt.exe
File: wallet / wallet.cpp, Line 663
Expression: false

[http://prntscr.com/p9a63n](url)

Run Bitcoin Core - Wallet
Go to Settings / Encrypt Wallet
Enter Passfrase (16 symbols, Only characters and numbers)
Then Error occured

Bitcoin core v. 0.16.3, got it on [https://bitcoincore.org/en/releases/0.16.3/](url)

> OS: Win 7-64
> CPU: Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz 2.60GHz
> RAM 16GB
> HDD KINGSTON SUV500480GB SCSI Disk Device

Size of wallet.dat is 513 699 840

debug.log

> 2019-09-22 02:41:19 Encrypting Wallet with an nDeriveIterations of 205299

**Comment by mishasaz** [comment]
Same issue on linux machine.

Run bitcoin server:  
> bitcoind
Answer: 
> Bitcoin server starting
Then:
>  bitcoin-cli encryptwallet "my_pass_phrase"

> error: Could not connect to the server 127.0.0.1:9998 (error code 1 - "EOF reached")

> Make sure the bitcoind server is running and that you are connecting to the correct RPC port.

And bitcoind server going down.

From debug.log

> [default wallet] Encrypting Wallet with an nDeriveIterations of 81268

Version of Bitcoin Core: Bitcoin Core version v0.17.1 (release build)

Got it on [https://bitcoincore.org/en/releases/0.17.1/](url)

Linux version:

> NAME="Ubuntu"
> VERSION="16.04.6 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.6 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

Machine params: 

> CPU Intel Xeon E3-1231v3
> RAM32GB DDR3 1333 MHz
> HDD2 x 480GB SSD SoftRAID

**Comment by wiranphowan** [comment]
wiranthphothiwan@gmail.com

ในวันที่ อา. 22 ก.ย. 2019 10:22 mishasaz <notifications@github.com> เขี

**Comment by MarcoFalke** [comment]
>  File: wallet / wallet.cpp, Line 663

Assertion is this: https://github.com/bitcoin/bitcoin/blob/f56c00b2345cd2e392ade4733e2ca9cb9b0af623/src/wallet/wallet.cpp#L663

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
