### ISSUE TITLE
p2p: monoculture of DNS seeder software

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16938]
A comment from @TheBlueMatt in #15558:

> One high-level concern with this is the monoculture of DNS seed software we have, if you select three at random you're almost certain to get three seeds serving from sipa's seeder implementation, whereas we should really be trying to diversify a little bit (not to mention get things like dnssec going, which I dont believe sipa's seeder support). Otherwise, Concept ACK.

From @jonasschnelli:
>  I think the risk of a single seeder codebase is orthogonal to this PR. Such risks could also be interpreted differently (diversity could also increase the risk based on the threat model).

**Comment by naumenkogs** [comment]
Somebody pointed me out to [Grin's DNS seeder](https://github.com/mimblewimble/seeder) in rust and told me that code quality is alright.
Perhaps it would be easy for @TheBlueMatt to review it and fork, rather than building from scratch?

Should we for once use a piece of software from altcoins? :)

**Comment by jonasschnelli** [comment]
From an architectural perspective, I think splitting the crawler from the dns server would be nice. One could use sipas crawler and use djbdns or bind or whatever to server the collected ips.

IMO the server part has more risks for critical vulnerabilities, therefore reusing existing software for that part would be nice, although unclear if existing dns server implementations have the required flexibility to serve dynamic data.

Unsure about the seeder from the Grin project. I couldn't find crawling code at all (maybe I overlooked it).

**Comment by kristapsk** [comment]
> From an architectural perspective, I think splitting the crawler from the dns server would be nice. One could use sipas crawler and use djbdns or bind or whatever to server the collected ips.

This sounds like a good idea. I could look at bind for this (as this is something I have experience with from administrator perspective for 10+ years).

> unclear if existing dns server implementations have the required flexibility to serve dynamic data

BIND has support for various database backends in addition to text configuration files, like LDAP, MySQL, PostgreSQL, Berkeley DB, ODBC, although it would be enough to just regularly update files and send `SIGHUP` to `named`.

**Comment by MarcoFalke** [comment]
Not sure how this can be fixed. Seems an issue unrelated to the code in this repo
