### ISSUE TITLE
ui: offline / multisig UX

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#16954]
Continued discussion from https://github.com/bitcoin/bitcoin/pull/16944#issuecomment-534538035, based on @gwillen's offline signing branch: https://github.com/gwillen/bitcoin/tree/feature-offline-v2

<img width="910" alt="Schermafbeelding 2019-09-24 om 14 09 54" src="https://user-images.githubusercontent.com/10217/65514592-e6090400-dedd-11e9-812b-614df2526946.png">

If we make the entire Send experience a modal, things might get a bit simpler.
  
![IMG_4970](https://user-images.githubusercontent.com/10217/65515874-4600aa00-dee0-11e9-89a3-4848c80540c5.jpg)

Sorry for the handwriting :-) There's 3 stages to a transaction:
1. Draft / compose: enter recipient, amount, fees, etc. (the current Send screen).

This step is skipped when loading a PSBT (e.g. via menu: Transaction -> Load, or a smart clipboard).

2. Sign: currently a popup which confirms the details. With hardware wallets (e.g. #16549) this should enumerate connected wallets and let you sign one by one. In a multisig situation it should detect if any signatures are missing, and rename the 3rd step to "Export".

3. Finish / Export: once again repeat the importantant details. For basic wallets with private keys in it, this should just show that the transaction has been broadcast. With a completed PSBT it should let the user choose between broadcasting or exporting (clipboard, save to disk).

**Comment by Sjors** [comment]
Some (not working) work in progress here to refactor the existing flow into this 3 step "wizard": https://github.com/Sjors/bitcoin/tree/2019/09/gui-send

**Comment by andronoob** [comment]
Might be off-topic, but as far as I know, Bitcoin Core currently generates privkeys through hardened derivation path, doesn't it? This seems to be an obstacle to watch-only wallet.

**Comment by jazzholicbae** [comment]
Would be great if we could support OP_CHECKLOCKTIMEVERIFY also ( like https://coinb.in/#newTimeLocked )

**Comment by fanquake** [comment]
I've moved this over to the GUI repo: https://github.com/bitcoin-core/gui/issues/56.
