### ISSUE TITLE
Incorrect work settxfee

### ISSUE THREAD

**Issue by M03G** [bitcoin/bitcoin#16958]
The transaction fee is transferred incorrectly.

I do
```
bitcoin-cli settxfee 0.00088496
true
```
or
```
$fee = '0.00088496';
if ($bitcoin->settxfee($fee)) {
```
and then
`$redeem = $b->sendtoaddress($address, 0.0001);`

And I expect payment in bytes will be equal to 88.496. And fee is approximately 0.00021 BTC. But it's not. Why?

Field | Val
-- | --
Size | 247 (bytes)
Weight | 661
Fees | 0.0001469 BTC
Fee per byte | 59.474 sat/B
Fee per weight unit | 22.224 sat/WU

```
2019-09-24T16:25:14Z [default wallet] Fee Calculation: Fee:14690 Bytes:166 Needed:14690 Tgt:0 (requested 0) Reason:"PayTxFee set" Decay 0.00000: Est
imation: (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out)
```
Ubuntu 16.04.3
Bitcoind 0.18.0

Previously, this problem was not. This started to happen after upgrading to version 0.18.0.

**Comment by MarcoFalke** [comment]
According to the line in the debug log, the fee is correctly calculated as:

```
0.00088496 BTC/kB * 0.168 kB = 0.00014867

**Comment by MarcoFalke** [comment]
Where did you get the numbers from that are not in the debug log?

**Comment by M03G** [comment]
> Where did you get the numbers from that are not in the debug log?

Sorry. Fixed.

**Comment by M03G** [comment]
> According to the line in the debug log, the fee is correctly calculated as:
> 
> ```
> 0.00088496 BTC/kB * 0.168 kB = 0.00014867
> ```

Now the weight of the transaction is considered differently? Why 0.168? Why not 0.247?

**Comment by MarcoFalke** [comment]
> Now the weight of the transaction is considered differently? Why 0.168 (0.166)? Why not 0.247?

The size of the transaction is measured in "virtual bytes" (0.166kB), which does not correspond to the size of the transaction serialized in bytes. The weight is approximately 4 * vbytes (+-3)

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).
