### ISSUE TITLE
appveyor should print boost test_suite log on failure

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16976]
See https://github.com/bitcoin/bitcoin/blob/a6c8aed1f140bef942b32af8aea78f0d5458cd17/.appveyor.yml#L63

However, it should use the `-l test_suite` log level and show the whole output on failure, similar to https://github.com/bitcoin/bitcoin/blob/a6c8aed1f140bef942b32af8aea78f0d5458cd17/src/Makefile.test.include#L371

**Comment by wiranphowan** [comment]
wiranthphothiwan@gmail.com

**Comment by gpstines** [comment]
I can give this a shot for Hacktoberfest

**Comment by gpstines** [comment]
I can give this a shot for Hacktoberfest

**Comment by GoelBiju** [comment]
Hi @MarcoFalke , I am quite new to this project and I wanted to help out. Should I add in the ```-l test_suite``` argument to the appveyor YAML file? Is there anything from the example mentioned in Makefile.test.include that I need to include after the -l argument, i.e. ```-t "`cat $< | grep -E "(BOOST_FIXTURE_TEST_SUITE\\(|BOOST_AUTO_TEST_SUITE\\()" | cut -d '(' -f 2 | cut -d ',' -f 1 | cut -d ')' -f 1`" > $<.log 2>&1 || (cat $<.log && false) ```?

**Comment by MarcoFalke** [comment]
I think you'd have to write `-l test_suite > some_log_name.foo || (cat some_log_name.foo && false)` in powershell or whatever language the appveyor thing is using
