### ISSUE TITLE
Allow sending to duplicate address in bitcoin rpc

### ISSUE THREAD

**Issue by ejose19** [bitcoin/bitcoin#16980]
**Is your feature request related to a problem? Please describe.**
See #2366 and #12538. Basically the only way to do this is using bitcoin-tx outputaddr command, but there's no native way using bitcoin-cli (RPC)

**Describe the solution you'd like**
There're are 2 solutions to this approach:
- (non breaking) Add "addoutputaddr" method to bitcoin-cli that accepts {"address":"value"} and does the same as outputaddr command
- (breaking) Using a different syntax for JSON in createrawtransaction that comply with JSON-RPC when sending to duplicate addresses
example: [{"address": "bitcoinAddress", "amount": "btcAmount"}, {..}, ..]

**Describe alternatives you've considered**
- Currently only alternative is using bitcoin-tx, which is not an option is one is communicating with the node using RPC only

**Comment by kristapsk** [comment]
What's the use case of having multiple outputs to the same address in a single transaction? That does not make any sense, you are definitely doing something wrong way. Bitcoin addresses aren't supposed to be reused at all.

**Comment by ejose19** [comment]
@kristapsk nobody is implying "address reuse", we're talking about being able to send to the same address twice or more in the same transaction, as you can receive as many times you want to the same address, the issue is when you keep receiving AFTER  spending (exposing your public key) Example possibility of this:

2 users in exchange withdraw to the same address, so exchange have either to:
 - withdraw in separate transactions (more congestion to the network and makes one of the user wait for next batch)
 - combine the amounts and send in a single output (however, the users may get confused why they received more than requested) 

Since this is possible with bitcoin-tx, I don't see any reason why we can't have the possibility to do it in rawtransaction (it's the tool that gives the flexibility to create the transaction as the user wants)

**Comment by promag** [comment]
> 2 users in exchange withdraw to the same address

Looks like the address is being reused?

**Comment by ejose19** [comment]
That's why I put "address reuse", I agree with not reusing addresses, however you can't control what the users request withdrawing to (they're free to withdraw to any address they want).

This feature request was more implying a functionality that's available through bitcoin-tx but not on bitcoin-cli (RPC). One of the proposed solution (add a new method) doesn't break anything and add the posibility to run the exact command from bitcoin-tx.

**Comment by achow101** [comment]
Concept NACK.

Why are there 2 users that are trying to withdraw to the same address? Presumably that's the same user.

> combine the amounts and send in a single output (however, the users may get confused why they received more than requested)

That doesn't make any sense. They will receive the exact same amount because it is the same address!

**Comment by ejose19** [comment]
> That doesn't make any sense. They will receive the exact same amount because it is the same address!

Yes, the total amount will be the same, but not the individual amount, if they're not aware anyone else is withdrawing to the same address, they will suppose something is wrong. This is a  very rare case anyways, since to have this happen either 
- They're the same user (as you mentioned)
- They're sharing the address for whatever reason
- They're withdrawing to a public address (donation?)

Thanks for the feedback everyone.

**Comment by promag** [comment]
This is already possible/acceptable - txo to same address.

The exchange can also split the "batch" in multiple transactions and spend the 1st change in the 2nd transactions (and so on).

So concept NACK.

**Comment by ejose19** [comment]
@promag can you point me how it's possible to do it without bitcoin-tx (or other way to manually creating the tx)

Regarding the exchange, yes it's a good idea indeed, however if it's a small exchange (where withdraws occurs a few times a day, if any) then doing a 2nd transaction JUST for the duplicate withdrawal is counter - productive (batching allow less signatures and small tx size)

Don't get me wrong, I'm not against your reasonale, just want to know why we restrain the user to create the transaction the way he want using the raw transaction way (which should be flexible)

**Comment by promag** [comment]
I meant that such transactions aren't rejected. You would have to create elsewhere.

**Comment by MarcoFalke** [comment]
Couldn't you sum the amounts and explain to your users that the amounts are going to be summed if they reuse addresses across accounts on your website?

This will result in the cheapest txs with regard to fees for both you and likely also for your users.
