### ISSUE TITLE
Using Cirrus CI

### ISSUE THREAD

**Issue by emilengler** [bitcoin/bitcoin#16985]
**Is your feature request related to a problem? Please describe.**
The problem is that Travis does not do any stuff for BSD operating systems.

**Describe the solution you'd like**
Looks like [Cirrus CI](https://cirrus-ci.org/) supports (at least) FreeBSD.
Could this be added as a separate service as well?

**Additional context**
In general the Bitcoin Core support on the BSD operating systems is bad because no one really maintains it. This could go one step further to make Bitcoin Core available on onther platforms.

**Comment by laanwj** [comment]
Might be useful, however:

> In general the Bitcoin Core support on the BSD operating systems is bad because no one really maintains it.

I don't think this is true. I maintain a FreeBSD node full time, and try OpenBSD support once a version. I'm also fairly sure @fanquake does.

**Comment by emilengler** [comment]
@laanwj That's good, didn't knew that. I used the docs for this 'statement' because there are by far not all build options listed (like building with a GUI or ZMQ).

But anyways, the curl project has this and it is pretty useful.
Here's an [example](https://cirrus-ci.com/task/5695814195740672)

**Comment by MarcoFalke** [comment]
This is already been done here: https://github.com/bitcoin/bitcoin/blob/master/.cirrus.yml (See e.g. https://cirrus-ci.com/github/MarcoFalke/bitcoin/master)

**Comment by emilengler** [comment]
@MarcoFalke Wow, thanks!
But why is it under your user space and not integrated in this repo?
I read that it costs money for github orgs but could we ask to get in for free because this is a non profit project and definitely not a small one.

**Comment by fkorotkov** [comment]
@emilengler Cirrus CI is free for OSS projects. There are [some limits](https://cirrus-ci.org/faq/#are-there-any-limits) but it should be enough for this repository. It seems Cirrus CI is already installed for `bitcoin` organization and there is `.cirrus.yml` in the root. Looks like one of the admins just need to enabled Cirrus CI for this particular repository here: https://github.com/apps/cirrus-ci

**Comment by fanquake** [comment]
> I'm also fairly sure @fanquake does occasional testing with BSDs.

@laanwj is right, I semi-reqularly test across Open/Net/Free BSD. I checked that OpenBSD 6.5 was working ok a [few days ago](https://github.com/fanquake/core-review/commit/2e055499c3c67bf44dc652a4724a9c96ae755f5d).

**Comment by MarcoFalke** [comment]
It appears that the pruning test fails (occasionally) because node0 runs into a socket error: https://cirrus-ci.com/task/5105663560122368?command=functional_test#L613

Ideally, this should be fixed before we enable Cirrus Ci for bitcoin/bitcoin

**Comment by laanwj** [comment]
> Ideally, this should be fixed before we enable Cirrus Ci for bitcoin/bitcoin

Yes, nothing specific to Cirrus: but in general, the rationale to not add more CIs is that currently the CI situation is already somewhat like a slot machine, with tests failing more often randomly than due to actual problems, we don't want to make it worse.
(Add to that that every CI has its own way to restart the build, and a different way of access control who gets to reset the build)

**Comment by fanquake** [comment]
Going to close this for now, as it's a fairly general issue. We have the `.cirrus.yml` file available, and as mentioned, there are multiple people regularly testing on BSDs.
