### ISSUE TITLE
reconsiderblock is prone to deadlocks when -checkblockindex=1

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#16998]
Steps to reproduce :

Configure with `--enable-debug` and run with `-checkblockindex=1` .

1. invalidateblock ...
2. reconsiderblock ...

Progress for reconsiderblock stops at some point, at least in the log. But CPU activity remains at 100%. It seems to happen shortly after it connects to new peers. Calling `setnetworkactive false` before reconsiderblock seems to prevent the issue.

ctrl + c will not stop bitcoind, it doesn't go beyond "addcon thread exit" and
"net thread exit".

When running QT, it becomes completely unresponsive.

`bitcoin-cli stop` will say "Bitcoin Core stopping", but that's a lie.

In addition, calling `reconsiderblock` very early after start, before you see `ERROR: AcceptBlockHeader: block 0000000000000000000212eb9b17aeb6e2a1527923ba79527cd8373f1d44307d is marked invalid`, will prevent the chain from moving until you force-quit.

Launching bitcoind without `-checkblockindex=1` doesn't seem to have this issue. 

Tried on master @ c3a8e097b1afe27bce2f71817fd23cb857236d9d.

**Comment by promag** [comment]
> `bitcoin-cli stop` will say "Bitcoin Core stopping", but that's a lie.

👮

**Comment by MarcoFalke** [comment]
Can you attach `gdb -p ${the_pid}` and run `thread apply all bt`?

**Comment by Sjors** [comment]
Closing because this is too long and too many refactors ago.
