### ISSUE TITLE
contrib/linearize scripts need tests

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17019]
The scripts under `contrib/linearize` do not have any tests.

It would be good to have functional tests for them, to assure that they keep working, and so that changes to them are not necessarily held up on manual testing.

**Comment by fjahr** [comment]
For reference: I am working on a test for the `-loadblock` option in #17044 and the scripts are implicitly tested in it. @laanwj do you have hints on configurations you think should be tested in particular?

**Comment by MarcoFalke** [comment]
It looks like the test can be submitted without the code changes and should still pass? If so, maybe do that as a first, separate, pull request?

**Comment by MarcoFalke** [comment]
I ran `git checkout 6a768e516e3bafe31bd8c0792cdc93986cabcc56 && ./test/functional/feature_loadblock.py` and it passed, so seems fine to do

**Comment by fjahr** [comment]
> It looks like the test can be submitted without the code changes and should still pass? If so, maybe do that as a first, separate, pull request?

Yeah, the test got much larger than the inital improvement of #15954  so makes sense: #17091
