### ISSUE TITLE
Unable to perform rpc call(curl) on bitcon RegTest mode.

### ISSUE THREAD

**Issue by codezeros-dev** [bitcoin/bitcoin#17017]
** Facing RPC error during curl call**
curl --user 'abc:xyzpwd' --data-binary '{"method": "getblockhash","params": [0],"id": "foo"}' --header 'Content-Type: text/plain;' localhost:18332

getting following error 
> curl: (56) Recv failure: Connection reset by peer

tried other rpc method but getting same error.

**System information**
./bitcoind

bitcoin.conf configuration 
printtoconsole=1
rpcuser=<abc>
rpcpassword=<xyz>
regtest=1
rest=1
txindex=1

**Note :**
Same rpc curl call working on testnet node(testnet=1).

Did this information enough.?

**Comment by laanwj** [comment]
```
  -rpcport=<port>
       Listen for JSON-RPC connections on <port> (default: 8332, testnet:
       18332, regtest: 18443)
```

regtest RPC is port `18443`
