### ISSUE TITLE
compilation error "Makefile:10430: recipe for target 'bench/bench_bench_bitcoin-data.o' failed"

### ISSUE THREAD

**Issue by askmike** [bitcoin/bitcoin#17021]
When trying to compile I run into:

    Makefile:10430: recipe for target 'bench/bench_bench_bitcoin-data.o' failed
    make[2]: *** [bench/bench_bench_bitcoin-data.o] Error 1
    make[2]: Leaving directory '/root/bitcoin/src'
    Makefile:13267: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/root/bitcoin/src'
    Makefile:774: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

**System information**

- bitcoin version: recent master (commit 1f40a91286662a9bf40737c34b4de2f5b5fa8b96)
- OS: Ubuntu 16.04.1 LTS
- gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
- system memory: 4GB

**Comment by MarcoFalke** [comment]
What are the steps to reproduce?

`./autogen.sh && ./configue && make`?

Have you tried `make distclean`?

**Comment by askmike** [comment]
> ./autogen.sh && ./configue && make?

Those are the steps I just performed to try and update my node. However I previously compiled (few months back) with a set of compilation flags that I do not have anymore.

> Have you tried make distclean?

This did the trick thanks!

PS. Apologies for filing this as an Github issue (and somehow adding the `bug` label?).

**Comment by laanwj** [comment]
> PS. Apologies for filing this as an Github issue (and somehow adding the bug label?). Didn't know the best place to ask for specific compile errors such as the one I got.

NP, but FWIW: the [bitcoin stack exchange](https://bitcoin.stackexchange.com/) is the best place for support questions.
