### ISSUE TITLE
the translations of Traditional Chinese in bitcoin_zh_TW.ts got clobbered to Simplified Chinese 

### ISSUE THREAD

**Issue by r8921039** [bitcoin/bitcoin#17027]
```
commit 977dd23e4023ac2f6cbbe86eb769db079b8018be
Author: Wladimir J. van der Laan <laanwj@protonmail.com>
Date:   Mon Sep 30 09:41:11 2019 +0200

    qt: Periodic translations update
    
    Pull new translations from Transifex and run `make translate`.

diff --git a/src/qt/locale/bitcoin_zh_TW.ts b/src/qt/locale/bitcoin_zh_TW.ts
index 635151bcc..0a6e5d605 100644
--- a/src/qt/locale/bitcoin_zh_TW.ts
+++ b/src/qt/locale/bitcoin_zh_TW.ts
@@ -3,487 +3,451 @@
     <name>AddressBookPage</name>
     <message>
         <source>Right-click to edit address or label</source>
-        <translation>右鍵點一下來修改位址或標記</translation>
+        <translation>鼠标右击编辑地址或标签</translation>
     </message>
     <message>
         <source>Create a new address</source>
-        <translation>產生一個新位址</translation>
+        <translation>创建新地址</translation>
     </message>
     <message>
```

**Comment by r8921039** [comment]
note: bitcoin_zh_TW.ts is for Taiwan

**Comment by MarcoFalke** [comment]
The translation is here: https://www.transifex.com/bitcoin/bitcoin/viewstrings/#zh_TW/qt-translation-019x/181450170

However, I am not a translator for this language, so I can't see any details

**Comment by r8921039** [comment]
> The translation is here: https://www.transifex.com/bitcoin/bitcoin/viewstrings/#zh_TW/qt-translation-019x/181450170

I just set up a Transifex account. Applying "filters" on the web shows the first/initial version is available since 2019-09-02 (nothing shows up with criteria 'translated_before: 2019-09-01') and most of the translations contain the incorrect simplified Chinese already in the first/initial version.  Wonder how the first/initial version was created? It would be correct if making v18 translations as default.

**Comment by r8921039** [comment]
the v18 zh_TW translation on Transifax is incorrect as well: https://www.transifex.com/bitcoin/bitcoin/viewstrings/#zh_TW/qt-translation-018x/163802850

however, the bitcoin-core v18 release is not affected (yet) as v18 translation hasn't been updated since Mar 14 2019 a01925c1502a4f74c01905b2b38d8f8a5ce975b1

**Comment by laanwj** [comment]
This needs to be fixed on transifex, then we can re-import the fixed translations.

**Comment by r8921039** [comment]
Is it possible to set/reset to the correct defaults first on Transifex? Or do we have to fix all translations manually for each release version (v18, v19 and future releases) on Transifex?

**Comment by r8921039** [comment]
BTW, v17 on Transifax looks much better and I see it is locked.

**Comment by r8921039** [comment]
the best case is that we can restore the correct transactions for v18 and then use it as the initial template for v19 and onward.

**Comment by MarcoFalke** [comment]
So is this an issue with transifex or with a translator or something else?

**Comment by MarcoFalke** [comment]
@laanwj Are you doing anything special importing the existing translations to new major versions?

**Comment by MarcoFalke** [comment]
Anyway, I don't speak Chinese nor Taiwanese, but the 0.17 translations shows up as a 101% match, so I went ahead and switched to it.


![Screenshot from 2019-10-03 13-56-58](https://user-images.githubusercontent.com/6399679/66151728-ec863280-e5e5-11e9-8724-7bdcecd7ac35.png)

**Comment by r8921039** [comment]
Thanks @MarcoFalke, the 2nd option looks legit!

**Comment by r8921039** [comment]
> Anyway, I don't speak Chinese nor Taiwanese, but the 0.17 translations shows up as a 101% match, so I went ahead and switched to it.
> 
> ![Screenshot from 2019-10-03 13-56-58](https://user-images.githubusercontent.com/6399679/66151728-ec863280-e5e5-11e9-8724-7bdcecd7ac35.png)

Somehow this only fixed one string, 921 to go... I wish there is a way to fix things wholesale.

**Comment by MarcoFalke** [comment]
Ouch, so pretty much all of these are incorrect: https://github.com/bitcoin/bitcoin/commit/977dd23e4023ac2f6cbbe86eb769db079b8018be#diff-08bf2442f2fcd6a33d39c5e6f48df61f

Hmm

**Comment by r8921039** [comment]
Yes, sorry I wasn't clear on the post.

**Comment by laanwj** [comment]
> @laanwj Are you doing anything special importing the existing translations to new major versions?

Yes, I have a clone-resource script that copies the translations as well as metadata to a new resource, so in this case from 0.18 to 0.19.

**Comment by laanwj** [comment]
As a brute-force approach you could try uploading the appropriate ts from the 0.18 branch to transifex for 0.19. This will erase all the translator metadata but will reset the translations for all the messages that were already present in 0.18.

**Comment by MarcoFalke** [comment]
Is that open source? There might be a bug in it

**Comment by MarcoFalke** [comment]
@GChuf Any idea why this happened?

**Comment by MarcoFalke** [comment]
I wonder if other languages are also affected

**Comment by r8921039** [comment]
Many thanks @laanwj @MarcoFalke, the file is looking great on Transifex for v18/v19 now.

**Comment by GChuf** [comment]
@MarcoFalke I can't say how/why it happened, but it must be a human mistake. Someone must have deleted the taiwanese v18 on transifex and upload chinese translation instead.
Honestly, it might have been me, although I don't remember deleting any chinese/taiwanese translations (except deleting _zh_CN.GB2312_ I think, and I chose to keep both _zh_ and _zh_CN_ unlike with any other language). So if I did, it was an error in the first place deleting the taiwanese translations, and another error when reuploading the wrong translations, so I don't think that was me ...

Anyway, I see laanwj already fixed it with reuploading v18 from github to transifex, which is what I would also have suggested.

The thing is, anyone could do this with any language, which is an issue. @laanwj right now any translator can delete all translations and reupload a file - do you think you could restrain that?

**Comment by laanwj** [comment]
> The thing is, anyone could do this with any language, which is an issue. @laanwj right now any translator can delete all translations and reupload a file - do you think you could restrain that?

The least dramatic way to restrict translation changes would be to require review.

**Comment by r8921039** [comment]
@laanwj @MarcoFalke Just did some git pull's. I see now it is fixed on v18/v19 release branches but the master is still having the incorrect one (just wanna make sure the master won't be used as v20 defaults).

**Comment by r8921039** [comment]
my concern on update master is discussed here #17049

**Comment by MarcoFalke** [comment]
I believe v19 will be used as default for v20, not master, but I will leave it to @laanwj whether to cherry-pick commit 6db76c6 to master or not.

**Comment by laanwj** [comment]
> I believe v19 will be used as default for v20, not master,

Yes. Translation updates should happen for major versions, not for master. Master has no active translations until the start of the next release window. At which start the current actual translations will be copied on transifex, not from the branch.

(I'm fine with cherry-picking a special case, if you're running master and it annoys you, but it's pointless to the release process)
