### ISSUE TITLE
Renaming main thread causes issues with UNIX utilities

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17036]
Renaming the main thread (e.g., the one the program spawns with) causes the name of the daemon in utilities such as "top" to show as "b-init" instead of bitcoind. This is surprising, as it doesn't show the other thread names (by default), you'd expect it to show program names.

This doesn't only affect top: killall does no longer recognize the program name
```
$ killall bitcoind
bitcoind: no process found
$ killall b-init
(no output, succesful)
```

~~In contrast to `bitcoin-qt`, which doesn't suffer from this problem because it has a separate init thread~~, initialization happens in the main thread in `bitcoind`, and it's renamed due to `util::ThreadRename("init");` in `AppInit`. If we want to name the init thread, this should only be done in `bitcoin-qt`.

(not sure when this was introduced, but #16984 made the issue more visible because ther's no bitcoin in the name anymore)

**Comment by sipa** [comment]
"killall bitcoind" hasn't worked for a while (before #16984 you had to use "killall bitcoin-init" or so, which was somewhat strange as well).

**Comment by laanwj** [comment]
Yes, I'm not sure when it was introduced, but I think this is clearly the wrong behavior.

**Comment by jonatack** [comment]
I've been seeing the same issue with bitcoind and bitcoin-qt. Reproduced the issue on master a689c119076c7b8dc5b4dea4539e4cbf5adfb72f.

**Comment by hebasto** [comment]
Also #16007
