### ISSUE TITLE
gui: some languages not displayed in bitcoin-qt language list

### ISSUE THREAD

**Issue by GChuf** [bitcoin/bitcoin#17047]
There are, for now, 4 languages which are not displayed in the windows/linux qt language list. I am not sure about macOS.

These languages are:
Esperanto, Latin, Silesian and Kapampangan.

Side note: My windows machine has the options to switch to Esperanto and Silesian languages, so they do "exist" somewhere in Windows.

Kurdish is also not displayed (correctly?), but I'm not sure if that's only a font issue or not.

QT fetches language names from OS itself, unless otherwise specified. Some info [here](https://wiki.qt.io/Locale_Support_in_Qt_5).
I tried to fix this issue with https://github.com/bitcoin/bitcoin/pull/16808.

On the image: Esperanto name not displayed -  **(eo)**.
![eo](https://user-images.githubusercontent.com/42591821/66200382-40098680-e6a1-11e9-9d30-ac43e358610f.png)

**Comment by syaifudin857** [comment]
Join

**Comment by fanquake** [comment]
I've moved this to the GUI repo: https://github.com/bitcoin-core/gui/issues/49.
