### ISSUE TITLE
test: Bump dummy scriptPubKey size after default address change

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17043]
fecc1be23143476b981352e8516cf9cce0450d62 changed the default addresstype, which means that functional tests that create tx sending to short scriptPubKeys such as `OP_TRUE` might violate the "tx-too-small" policy rule. See the added `TODO`s in the functional tests in that commit for reference.

The `TODO`s can be solved by defining a large enough dummy scriptPbuKey (maybe as a constant, 64 bytes should be long enough) and using that over `OP_TRUE` or hardcoded in-line `CScript([b'a' * 35])`.

**Comment by josephnicholas** [comment]
@MarcoFalke can I work on this task?

**Comment by MarcoFalke** [comment]
Sure, no need to ask for permission
