### ISSUE TITLE
rpc: load PSBT from file

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#17065]
**Is your feature request related to a problem? Please describe.**

It's not possible to inspect a binary PSBT file generated by e.g. ColdCard.

**Describe the solution you'd like**

RPC calls like `decodepsbt` and `analyzepsbt` should have a file path argument.

**Describe alternatives you've considered**

A new RPC call like `loadpsbt` could have a file argument and return the base64 encoded version, that the user can then copy-paste into the existing RPC calls.

cc @achow101

**Comment by emilengler** [comment]
I prefer the second solution. It is more modular which I personally prefer (Unix fanboy).

> the user can then copy-paste into the existing RPC calls.
Copy and pasting is not needed
```
decodepsbt(loadpsbt('foo.bar'))
```

**Comment by Sjors** [comment]
@emilengler we don't supported nested RPC calls like that. It's a bit more verbose:

```
bitcoin-cli getblockheader(getbestblockhash)
-bash: syntax error near unexpected token `('

bitcoin-cli getblockheader `bitcoin-cli getbestblockhash`
```

It's worse the inner RPC call returns a JSON object.

**Comment by promag** [comment]
This implies the file is on the server side, not very R(emote)PC friendly?

**Comment by emilengler** [comment]
@Sjors In the Qt console I can do
```
getblock(getblockhash(10))
```
Not sure about bitcoin-cli

**Comment by Sjors** [comment]
A good enough alternative might be to use `cat tx.psbt | bitcoin -stdin decodepsbt`
