### ISSUE TITLE
build: Linux man pages in Windows zip

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17077]
![Screenshot from 2019-10-08 20-37-53](https://user-images.githubusercontent.com/32963518/66418817-8c3f2880-ea0b-11e9-97c3-161c83a55b33.png)

What are benefits for Windows users?

**Comment by emilengler** [comment]
What is wrong with a zip archive?

**Comment by hebasto** [comment]
@emilengler 

> What is wrong with a zip archive?

Zip is ok ;) But is there a simple way to open `*.1` files on Windows?

**Comment by laanwj** [comment]
> Zip is ok ;) But is there a simple way to open *.1 files on Windows?

Simplest is:
- Open WSL terminal
- `man blabla.1`

But sure— manpages are kind of irrelevant for windows.
Although I don't think this is a serious issue (their size pales in comparison to binary sizes), it's fine to not include them at all.

**Comment by emilengler** [comment]
@laanwj 
The fastest way would be to download a Groff viewer or use an online tool.
But I agree it is probably useless to ship this for Windows Zip.

However I would continue to ship this as a zip because using `tar` is the same mystery as using `chmod` ;)

**Comment by GChuf** [comment]
Agree with laanwj.

**Comment by emilengler** [comment]
Would it be possible to deliver "untroffed" versions of the manpages?
This could be useful.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
