### ISSUE TITLE
GUI: rename "debug window"

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#17082]
The term "Debug Window" is not accurate IMO and we should consider renaming it to a more user-friendly term (only visible in the window title as well as from the tray menu).

**Comment by laanwj** [comment]
Instead of a debug window, it has pretty much become the Node UI (in contrast to the Wallet UI, that is the main window) over time.

**Comment by promag** [comment]
> pretty much become the Node UI

🤔 that could be the internal name `class NodeWidget` instead of `class RPCConsole`.

**Comment by Relaxo143** [comment]
> Instead of a debug window, it has pretty much become the Node UI (in contrast to the Wallet UI, that is the main window) over time. Neither of these are user-friendly terms but this is a concept ACK.

"Node Window" or "Node Menu" sound good to me.

**Comment by promag** [comment]
@Zero-1729 feel free to work on that.

**Comment by Zero-1729** [comment]
Awesome 👍 

> ... we should consider renaming it to a more user-friendly term (only visible in the window title as well as from the tray menu).

As per @jonasschnelli's original message above, should the change just be limited to changing where 'Debug window' is displayed to 'Node window', i.e:

in `src/qt/forms/debugWindow.ui`:

```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>RPCConsole</class>
 <widget class="QWidget" name="RPCConsole">
...
  <property name="windowTitle">
   <string>Node window</string> <- here
...
```

and in `src/qt/bitcoingui.cpp` :

```cpp
...
openNodeWidgetAction = new QAction(tr("&Node window"), this); <- here
    openNodeWidgetAction->setStatusTip(tr("Open node debugging and diagnostic console"));
...
```

or actually renaming `debugwindow`, `RPCConsole`, `openRPCConsoleAction`, etc?

**Comment by promag** [comment]
@Zero-1729 hard to tell, at least separate in commits:
 - change titles/labels/menus
 - class rename
 - filen rename

**Comment by Zero-1729** [comment]
Yeah, fair enough. I'll open a PR as soon as I am done.

Thanks for the clarification 👍

**Comment by Zero-1729** [comment]
I just opened the PR. 👍
