### ISSUE TITLE
doc, rpc: -rpcclienttimeout help string is wrong

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17117]
```
$ bitcoin-cli --help   
Bitcoin Core RPC client version v0.19.0rc1
...
  -rpcclienttimeout=<n>
       Timeout in seconds during HTTP requests, or 0 for no timeout. (default:
       900)
```

The _"0 for no timeout"_ part, added in #9903, is wrong:

```
$ time bitcoin-cli -rpcclienttimeout=0 gettxoutsetinfo
error: Could not connect to the server 127.0.0.1:8332 (error code 0 - "timeout reached")

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.

real	0m51.279s
user	0m0.005s
sys	0m0.019s
```

Both 0.18.0 and 0.19.0rc1 are affected.

**Comment by MarcoFalke** [comment]
According to https://github.com/bitcoin/bitcoin/pull/9903#issuecomment-283937055 it used to work at some point

**Comment by cryptohazard** [comment]
I just noticed on v0.19.0.1 that using:
`rpcclienttimeout=0`
I get in the logs:
`Ignoring unknown configuration value rpcclienttimeout`

**Comment by hebasto** [comment]
@cryptohazard 

> I just noticed on v0.19.0.1 that using:
> `rpcclienttimeout=0`
> I get in the logs:
> `Ignoring unknown configuration value rpcclienttimeout`

Please make sure that you provide the `rpcclienttimeout` option to the `bitcoin-cli` binary, not to `bitcoind` or `bitcoin-qt`.

**Comment by cryptohazard** [comment]
Understood! it was in the bitcoin.conf
