### ISSUE TITLE
log, doc: Confusing log message

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17139]
```
bitcoind -par=1
```

Excerpt from the `debug.log`:

```
Using 0 threads for script verification
```

Zero? I guess not ;)

**Comment by laanwj** [comment]
It's always been like that. It doesn't count the main thread in that message. "Threads" counts the *extra* threads. Feel free to change it to:

```
Using 0 additional threads for script verification
```

**Comment by hebasto** [comment]
> "Threads" counts the _extra_ threads.

But setting `-par=2` gets "Using 2 threads for script verification".

**Comment by laanwj** [comment]
Huh.

**Comment by jnewbery** [comment]
Here's the help message:

```
  -par=<n>
       Set the number of script verification threads (-4 to 16, 0 = auto, <0 =
       leave that many cores free, default: 0)
```

The behavior is confusing here:

- not having a `par` setting, setting `-par=0` or setting `-nopar`: defaults to starting GetNumCores() dedicated script-checking threads
- setting `-par=1`: starts no dedicated script-checking threads and does all script-checking on the main thread. This is confusing and undocumented!
- setting `-par=n` for n > 1: starts n dedicated script-checking threads (up to a max of 16)
- setting `-par=-n` for n > 1: starts GetNumCores() - n dedicated script-checking threads. This is weird but at least it's documented!

**Comment by sipa** [comment]
No, -par=N should start N-1 script checking threads, as the main thread always participates (so there should always be N threads in total doing script verification, for N>=1).
