### ISSUE TITLE
CExtKey::Unserialize and CExtPubKey::Unserialize throw std::runtime_error instead of the expected std::ios_base::failure

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#17130]
`CExtKey::Unserialize(...)` and `CExtPubKey::Unserialize(...)` throw `std::runtime_error` instead of the expected `std::ios_base::failure`.

Context (taken from an e-mail):

> When fuzzing some deserialization code I noticed that `CExtKey::Unserialize(...)` and `CExtPubKey::Unserialize(...)` throw `std::runtime_error` instead of the `std::ios_base::failure` I expected in case of deserialization errors.
>
> I saw that this code was written by you originally: do you remember if there was a particular reason to go with `std::runtime_error` instead of `std::ios_base::failure`? If not, do you think it would be safe to change it? :)

Code:

https://github.com/bitcoin/bitcoin/blob/376638afcf945ec43089625d115286594ce0ab16/src/key.h#L174-L183

https://github.com/bitcoin/bitcoin/blob/78dae8caccd82cfbfd76557f1fb7d7557c7b5edb/src/pubkey.h#L240-L249

FWIW the code paths in question are reachable by the fuzzers added in PR #17051 ("tests: Add deserialization fuzzing harnesses").

**Comment by practicalswift** [comment]
Friendly ping @jonasschnelli :)

Could you clarify? This is a fuzzing blocker I'd like to get rid of if possible :)

**Comment by MarcoFalke** [comment]
Those messages are not sent over p2p, so fuzzing is nice to have, but not going to harden the protocol layer.

I guess they might be written by the wallet? In that case, you might want to check if the wallet is handling those exceptions properly.

**Comment by practicalswift** [comment]
The only use of `CExt{Pub,}Key` serialisation/deserialisation appears to be in `bip32_tests`.

**Comment by MarcoFalke** [comment]
Maybe you can remove that logic then?

**Comment by achow101** [comment]
I'm pretty sure serialization is used by the wallet for the `dumpwallet` rpc. Also, both are being used in #16463

**Comment by practicalswift** [comment]
@achow101 `dumpwallet` is using `EncodeExtKey`, no? :)

https://github.com/bitcoin/bitcoin/blob/46d6930f8c7ba7cbcd7d86dd5d0117642fcbc819/src/wallet/rpcdump.cpp#L802-L813

**Comment by achow101** [comment]
Hmm, so the actual serialization happens in Encode/Decode, not Serialize/Unserialize, and that's what #16463 uses. So in that case, I think it is fine to get rid of Serialize/Unserialize.

**Comment by practicalswift** [comment]
@MarcoFalke 

> Maybe you can remove that logic then?

Since #15814 + https://github.com/bitcoin/bitcoin/pull/15814#issuecomment-506959457 I'm a bit hesitant to touch dead code :)

Perhaps we can put a "good first issue" tag on this one and let a newcomer take care of it.

**Comment by MarcoFalke** [comment]
Ok, will add "good first issue"

**Comment by MarcoFalke** [comment]
Removing is probably fine. If this will ever be needed, a simple `git revert $commit_that_removed_it` should restore it.

**Comment by practicalswift** [comment]
This was solved with the merge of #17212. Closing. Thanks @theStack! :)
