### ISSUE TITLE
Remove wallet access to node arguments

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#17137]
To better separate the wallet and node, and in preparation for full process separation, the wallet should not access any of the node's config arguments. Either config interaction should be handled outside the wallet, or the wallet should use a well-defined method in the `Chain` interface to access the values.

Currently, the wallet accesses global node arguments in the following locations:

- [ ] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/init.cpp#L87 (`blocksonly`)
- [ ] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/init.cpp#L103 (`persistmempool`)
- [ ] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/init.cpp#L123 (`sysperms`)
- [x] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/init.cpp#L125 (`prune`)
- [x] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/wallet.cpp#L2742 (`limitancestorcount`)
- [x] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/wallet.cpp#L2743 (`limitdescendantcount`)
- [ ] https://github.com/bitcoin/bitcoin/blob/b33c03b0cb82e57eb862542c9d331b7ceb8f3a62/src/wallet/wallet.cpp#L4488 (`minrelaytxfee`)

**Comment by ryanofsky** [comment]
>  in preparation for full process separation

In practice, there isn't an issue in #10102 because the node serializes `gArgs` and passes it to the wallet when it calls [`MakeWalletClient`](https://github.com/ryanofsky/bitcoin/blob/b6066d2b491fb32563b9b69a82f4736b68df9cc7/src/interfaces/capnp/init.capnp#L20). But giving the wallet and node separate arguments is cleaner and would remove the need for this workaround.

**Comment by jnewbery** [comment]
#17138 removed `-limitancestorcount`, `-limitdescendantcount` and `-prune`

**Comment by Kixunil** [comment]
Do I understand correctly that after this change Bitcoind will create all files with `77x` permissions?
