### ISSUE TITLE
Error: connect ECONNREFUSED v0.18.0

### ISSUE THREAD

**Issue by dsky1990** [bitcoin/bitcoin#17148]
my config is below, the Bitcoin Core version is v0.18.0
```
txindex=1
server=1
rpcuser=username
rpcpassword=password
rpcallowip= the ip I connect
rpcport=port
```

but I got error ` Error: connect ECONNREFUSED`

**Comment by laanwj** [comment]
it's not listening on the external interface; try `rpcbind=0.0.0.0`

**Comment by dsky1990** [comment]
@laanwj it works , the ip `rpcbind ` bind is which ip ? the `btcoin client` or the `client i request`

**Comment by laanwj** [comment]
it's the network interface to listen on

**Comment by dsky1990** [comment]
I'm not clear of it, eg:
the ip of client i request is `1.1.1.1 `
the bitcoin rpcport is `1234`
the rpcallowip ip is `1.1.1.1`
what should the `rpcbind` be?
@laanwj , please tell me, I'm confused

**Comment by laanwj** [comment]
Please don't ask support from me personally, definitely not for basic networking questions. For bitcoind related support questions you could try asking on the [bitcoin stack exchange](https://bitcoin.stackexchange.com/). But I'd recommend doing some of your own research.
