### ISSUE TITLE
GCC compiling on ARM host 

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17150]
ARM is one of the supported platforms for compiling and running Bitcoin Core.

Unfortunately, some ARM-related caveats are not documented:

- there is [a bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77728) in GCC 5 and 6

- the mentioned bug is [fixed](https://gcc.gnu.org/gcc-7/changes.html) in GCC 7, but the compiler emits tons of diagnostic notes on ARM host; passing `-Wno-psabi` option to the compiler could suppress these notes

**Comment by MarcoFalke** [comment]
How are we affected by the compiler bug? If affected, I hope we have a unit or configure test that fails when compiled with a buggy compiler?

Jup, the warnings can be ignored: https://github.com/bitcoin/bitcoin/blob/137b7a2af1aa3e19e543af68345c6e10dd27a6dc/ci/test/00_setup_env_arm.sh#L18

**Comment by laanwj** [comment]
FWIW I've been using bitcoin core on ARM (both 32 and 64) for years and never had any issues due to that GCC bug. This is a very general C++ bug and I don't think it's our responsibility to document it.

Also: the gitian-built executables are built with gcc 8, so it's fixed there.
