### ISSUE TITLE
gui: Hide or grey out used addresses

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17174]
The gui keeps track of some addresses in the "receiving addresses" and "sending addresses" tabs. In light of address reuse and accidental double-payments, it could make sense to hide or dull out addresses which have been used. Maybe even show the txid.

**Comment by za-kk** [comment]
Agreed, willing to work on this if consensus thinks it would be a valuable change.

**Comment by MarcoFalke** [comment]
The issue has three ":+1:", which means overall agreement, I guess

**Comment by za-kk** [comment]
Nice, will start working on this and open a PR once complete 👍

**Comment by promag** [comment]
Concept ACK. Do we already track used addresses in the wallet (beside keypool)? If not then I think we should start by doing it otherwise implementing this can hurt the GUI for big wallets. Or am I missing something?

**Comment by za-kk** [comment]
We already track used addresses in the address book via the `SetUsedDestinationState`, however this is only when the wallet has the `avoid_reuse` flag set.

**Comment by promag** [comment]
> only when the wallet has the `avoid_reuse` flag set.

Sounds reasonable to support just that for now.

**Comment by fanquake** [comment]
I've moved this over to the GUI repo: https://github.com/bitcoin-core/gui/issues/528.
