### ISSUE TITLE
gui: Explain what "message" means in the receive tab

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17173]
When creating a receiving address, there is the option to provide a "message". This "message" is shown in the table of all receiving addresses in the same tab.

The tooltip says that this message is attached to the "payment request" (presumably BIP 70). It is unclear to me if it ever was possible to receive payment requests with Bitcoin Core. And now that the payment request functionality is disabled by default and about to get removed, it could makes sense to cleanup this interface:

* The term "message" should go away, because there is nothing we send out to the Bitcoin network
* It should explain how this is different from a label, which is settable in the same tab
* It should explain how this is different from a comment, which exists in the RPC interface, but is not exposed in this tab

**Comment by dannmat** [comment]
I'd say remove this, it's confusing and unnecessary. I'll remove this and it's references if that is the consensus?

**Comment by MarcoFalke** [comment]
Removing sounds fine with me

**Comment by Danny-Scott** [comment]
ACK - seems useless to me
