### ISSUE TITLE
Windows installer properties and signing

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17170]
Downloaded [`bitcoin-0.19.0rc1-win64-setup.exe`](https://bitcoincore.org/bin/bitcoin-core-0.19.0/test.rc1/bitcoin-0.19.0rc1-win64-setup.exe).

The Properties - Details tab lacks "File description" and "Copyright" values:

![Screenshot from 2019-10-17 09-32-02](https://user-images.githubusercontent.com/32963518/66984452-6973da80-f0c3-11e9-933c-5d8161a3d3c8.png)

Also, the note that this `exe` file is signed by _Bitcoin Core Code Signing Association_ could be mentioned somewhere in our docs.

**Comment by MarcoFalke** [comment]
> The Properties - Details tab lacks "File description" and "Copyright" values:

See `FileDescription` in https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource


> Also, the note that this exe file is signed by Bitcoin Core Code Signing Association could be mentioned somewhere in our docs.

See here: #15682

**Comment by hebasto** [comment]
> See here: #15682

I knew it ;)

I mean providing info for an end user who downloads installer from bitcoincore.org; it could be readme.txt or release notes. No?

**Comment by MarcoFalke** [comment]
I think the name "Bitcoin Core Code Signing Association" is pretty self-explanatory and not surprising. No strong opinion, though.

**Comment by laanwj** [comment]
I'm not sure this an actual problem that affects users.

**Comment by MarcoFalke** [comment]
Agree with @laanwj . This can trivially be fixed by adding the `FileDescription` key to the rc files, no need to open a tracking issue.

**Comment by luke-jr** [comment]
> Also, the note that this exe file is signed by Bitcoin Core Code Signing Association could be mentioned somewhere in our docs.

That would tie the project to the association closer than it currently is. Right now, anyone can sign...
