### ISSUE TITLE
windows: Files installed by installer *-setup.exe

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17171]
The installer [`bitcoin-0.19.0rc1-win64-setup.exe`](https://bitcoincore.org/bin/bitcoin-core-0.19.0/test.rc1/bitcoin-0.19.0rc1-win64-setup.exe):

- lacks `test_bitcoin.exe` (is present in `zip`)

- bloats system with _full_ `doc` folder content:
![Screenshot from 2019-10-17 11-03-30](https://user-images.githubusercontent.com/32963518/66989836-c6748e00-f0cd-11e9-9845-3a5cbf6d3936.png)

**Comment by emilengler** [comment]
Was this always a thing under Windows?
I think including some docs is a good approach but there are lots of useless stuff like compile instructions for completely different operating systems

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core?

**Comment by 1440000bytes** [comment]
> Is this still an issue with a recent version of Bitcoin Core?

Yes
