### ISSUE TITLE
macos: shutdown on first run due to -psn_ parameter 

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17179]
When downloading and running Bitcoin core for the first time, after clicking through the "Are you sure you want to open. it?" screen, there's a possibility that macOS will pass an argument like `-psn_0_SOME_ID` to the application, which results in a shutdown as it's an invalid argument:

![v0 19 0rc1 args shutdown](https://user-images.githubusercontent.com/863730/67034964-b026fc00-f0e6-11e9-8462-70d0fcf613e6.png)

This only happens on the first run, subsequent opens will work fine, but we should filter these out, otherwise it's a poor and confusing first experience.

**Comment by hebasto** [comment]
Could this be related https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder ?

**Comment by jonasschnelli** [comment]
Nice catch!

I could not find documentation about this on apples site?
Anyone?

**Comment by hebasto** [comment]
Besides #17184, could a [native Objective-C command-line arguments parsing](https://developer.apple.com/documentation/foundation/nsprocessinfo/1415596-arguments?language=objc) be useful?

**Comment by laanwj** [comment]
> could a native Objective-C command-line arguments parsing be useful?

Unless absolutely necessary, please don't introduce any MacOS specific code.

**Comment by fanquake** [comment]
The filtering used to be done by Qt [here](https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/kernel/qguiapplication.cpp?h=5.9.8#n1377)

```cpp
#ifdef Q_OS_MAC
        } else if (strncmp(arg, "-psn_", 5) == 0) {
            // eat "-psn_xxxx" on Mac, which is passed when starting an app from Finder.
```

> Besides #17184, could a native Objective-C command-line arguments parsing be useful?

Yea, definitely NACK.
