### ISSUE TITLE
test: Debug travis macOS environment

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17178]
A travis run for native macOS has recently been added, but it required a hacky `cd` workaround. Someone experienced with macOS on travis (or a lot of time) might want to debug this workaround and either remove it or document and wrap it. See https://github.com/bitcoin/bitcoin/pull/16597/files#r336052676 for context.

**Comment by sadrasabouri** [comment]
@MarcoFalke May i handle this issue?

**Comment by fanquake** [comment]
@sadrasabouri yes, go ahead.

**Comment by MarcoFalke** [comment]
This can be fixed by upgrading rvm: See https://github.com/bitcoin/bitcoin/pull/17202#issuecomment-545455404

**Comment by Sjors** [comment]
I tried to upgrade RVM in 69612c4, but it seemed of no use: https://api.travis-ci.org/v3/job/615464864/log.txt

**Comment by MarcoFalke** [comment]
Fixed this by removing `cd` from all ci scripts.
