### ISSUE TITLE
Replace #16578 with a more specific solution

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17187]
The change in #16578, although necessary, was over-sweeping.

I was initially in favor of it, but never expected this. It is turning into a boondoggle, with repercussions from our testing process (#17013) to MacOS user experience (#17025, #17179). Even changes outside the GUI code itself (#17184). I feel this is getting out of hand. It creates a lot of work and we'll end up reverting all of this eventually.

**Comment by promag** [comment]
Perhaps there won't be more surprises? Otherwise I agree, we could revert and then blacklist some arguments instead.

**Comment by laanwj** [comment]
There is not even a need to blacklist any arguments.

I mean, it's only a potential problem for one specific OS, in one specific use of the executable.

**Comment by promag** [comment]
Another consequence was #17031.

**Comment by hebasto** [comment]
Considering https://github.com/bitcoin/bitcoin/pull/16578#issuecomment-810625233 is this still an issue?
