### ISSUE TITLE
Increase default -dbcache

### ISSUE THREAD

**Issue by GChuf** [bitcoin/bitcoin#17200]
I've noticed the default `-dbcache` used to be 600MiB, but got lowered to 450 in March 2017: https://github.com/bitcoin/bitcoin/commit/f33afd3b2be1bcabeb10168a53835359c9ff4a3e

We know this negatively affects performance on initial sync (and reindexing) and the average user most likely doesn't know they should increase the dbcache to make the sync faster.

I think it is safe to assume that the (advanced) users who have low amounts of RAM on their machines know about dbcache flag and how to use it appropriately. It would, therefore, be best to increase the default dbcache.

I'm not sure about the other parameters in `txdb.h`, but the blockchain is getting bigger every day and our computers are getting more and more capable. I'd like to propose to increase the dbcache size to 600MiB or higher, and if applicable, change the other parameters appropriately.

You should also take a look at this [comment ](https://github.com/bitcoin/bitcoin/pull/16957#issuecomment-536713463) and the PR which decreased the memory usage by 9% - so bumping the dbcache to at least 500 would be more than appropriate. Another PR by @martinus which also decreases mem usage: https://github.com/bitcoin/bitcoin/pull/16801

**Comment by emilengler** [comment]
See #10133

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
