### ISSUE TITLE
Move logging to background thread

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17216]
To increase parallelism, the logging could be moved to a background thread.

Currently, writing to the debug log is done in-line (synchronous) and unbuffered. See https://github.com/bitcoin/bitcoin/blob/a22b62481aae95747830bd3c0db3227860b12d8e/src/logging.cpp#L56
That means that on slow disks (non-ssd, mostly), calls to `LogPrint*()` are potentially expensive and blocking further execution of the calling thread (potentially the net processing or validation thread).

Moving logging to a background thread should be fine, except for some edge cases:
* We use `assert_debug_log` in the functional tests, which assume that a message is written to the debug log synchronous. However, the recently added polling to `assert_debug_log` should work around that.
* The logging thread should probably be started when logging is started and shut down when the node is shut down. Calls to logging during shutdown should probably be in-line.

**Comment by promag** [comment]
Like #13200?

**Comment by MarcoFalke** [comment]
Ah, yes. "Up for grabs" I guess.

**Comment by adamjonas** [comment]
I have [a branch](https://github.com/bitcoin/bitcoin/compare/master...adamjonas:async-log) of a rebased #13200. I could use some help benchmarking to make a good case for reopening.

**Comment by MarcoFalke** [comment]
The instructions on how to run bitcoinperf are here: https://github.com/chaincodelabs/bitcoinperf#example-local-usage-no-docker

I'd suggest to not run it on your normal machine, as it installs quite a bunch of crap.

**Comment by adamjonas** [comment]
Ran some benchmarks on an HDD machine:

In all, we saw a 2.6% speed-up from for the first 200,000 blocks and a 2% slow down for blocks 500,000 to 525,000, but with a 11% reduction in peak memory usage.

## First 200_000 blocks

### async-log vs. master (absolute)
|          bench name           |  # of runs  |        async-log         |         master          |
|-------------------------------|----:|--------------------------|-------------------------|
| ibd.local.200000.total_secs   |   2 | 179.3786 (± 0.2791)      | 184.0771 (± 1.5131)     |
| ibd.local.200000.peak_rss_KiB |   2 | 771078.0000 (± 322.0000) | 771026.0000 (± 82.0000) |

### async-log vs. master (relative)
|          bench name           |  # of runs  | async-log | master |
|-------------------------------|----:|----------:|-------:|
| ibd.local.200000.total_secs   |   2 |     1.000 |  1.026 |
| ibd.local.200000.peak_rss_KiB |   2 |     1.000 |  1.000 |

![ibd local 200000](https://user-images.githubusercontent.com/755825/67712216-f52a1880-f999-11e9-822a-d517cc088e7f.png)


## Blocks 500_000 to 525_000

### async-log vs. master (absolute)
|                 bench name                 |  # of runs  |         async-log         |          master           |
|--------------------------------------------|----:|---------------------------|---------------------------|
| ibd.local.range.500000.525000.total_secs   |   2 | 2619.9838 (± 2.5637)      | 2615.2636 (± 4.9015)      |
| ibd.local.range.500000.525000.peak_rss_KiB |   2 | 4489636.0000 (± 604.0000) | 4538482.0000 (± 910.0000) |
### async-log vs. master (relative)
|                 bench name                 |  # of runs  | async-log | master |
|--------------------------------------------|----:|----------:|-------:|
| ibd.local.range.500000.525000.total_secs   |   2 |     1.002 |  1.000 |
| ibd.local.range.500000.525000.peak_rss_KiB |   2 |     1.000 |  1.011 |

![ibd local range 500000 525000](https://user-images.githubusercontent.com/755825/67712372-3a4e4a80-f99a-11e9-96cd-bc2b376d6ea5.png)

Ran on:
```

**Comment by MarcoFalke** [comment]
There is evidence that logging slows down some tasks by a factor of 5 (500% overhead) on non-intel low-end machines:

* https://github.com/bitcoin/bitcoin/issues/18538#issuecomment-615208001

**Comment by willcl-ark** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Pull requests with improvements are always welcome.

**Comment by mmortal03** [comment]
> Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Isn't that a point of labels and milestones? You can leave issues open to accumulate various perspectives for reference, and just mark the particular issues being worked on for the current milestones?
