### ISSUE TITLE
doc: Add developer documentation to isminetype

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17217]
Stuff like `ISMINE_USED` is not self-explanatory and completely undocumented: https://dev.visucore.com/bitcoin/doxygen/ismine_8h.html#a050f9a1a807967a24bcbeebfc5952533

**Comment by HAOYUatHZ** [comment]
let me open a PR soon to address these in `ismine.h` and `ismine.cpp` 

I guess explaining the enumerators and the function logic  
will be sufficient?

**Comment by HAOYUatHZ** [comment]
> Stuff like `ISMINE_USED` is not self-explanatory and completely undocumented: https://dev.visucore.com/bitcoin/doxygen/ismine_8h.html#a050f9a1a807967a24bcbeebfc5952533


Just to double check:

+ `ISMINE_USED`: an output pays to my reused address
+ `ISMINE_NO`: the output doesn't pay to me
+ `ISMINE_WATCH_ONLY`: my pubkey is a member of the multi-sig address an output paying to 
+ ` ISMINE_SPENDABLE`: an output pays to me

**Comment by HAOYUatHZ** [comment]
sorry I haven't managed to add explanations directly shown in doxygen-ed html

was trying to add the explanations in the table

![Screenshot from 2019-10-30 14-04-44](https://user-images.githubusercontent.com/37070449/67832975-4c58f600-fb1e-11e9-9b53-82fd650c7ed1.png)

I guess i could just put it in the source ".h" / ".c" files?   people can navigate to page like "ismine_8h_source.html" when browsing.

**Comment by laanwj** [comment]
Closing this, as it seems controversial, an attempt was done in #17350 but it's not clear it will actually be merged. But discussion is over there.
