### ISSUE TITLE
How to ensure there is no version mismatch?

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#17236]
### Motivation

We would like to ship `bitcoind` with our software, however it's problematic if the user has already Bitcoin Core in her machine, because of the disk requirements.

In order to avoid API/database/etc incompatibilities and various potential disastrous scenarios we would like to prevent the user to use Bitcoin Core with our software if the version of her own Core and our shipped Core differs.  

### Question

How do similar software resolve this issue?

### Idea 1

Should I play a setup procedure with the user like this:

```
1. Do you want to use Bitcoin Core with Wasabi? Yes -> 2. / No -> END
2. Do you have already Bitcoin Core installed? Yes -> 3. / No -> GOOD
3. What version of Bitcoin Core do you have? ... -> Same -> 4. / Different -> BAD
4. Try to detect data folder automatically. Success -> GOOD / Fail -> 5.
5. What's your current Bitcoin Core's data folder? ... -> GOOD

- What if we update Bitcoin Core? Replay step 3.
- What if the user updates Bitcoin Core? It's a problem, there's no way we can detect it.
```

### Idea 2

What I can do is to try to detect Bitcoin Core's default data folder and also get some input from the user if she's using a custom data folder, but is there a way to acquire the version from the data folder somehow?  

### Idea 3

I could call `bitcoind --version`. In this case the user should tell us the location of `bitcoind`. In that case, is it possible to recognize programmatically her custom data folder if she's using one?

### Reiterating The Question

What are the common strategies of doing this? Is it possible to detect if Bitcoin Core is installed and what data folder is used?

**Comment by MarcoFalke** [comment]
All you need is the rpc auth (not the whole datadir), then you can get the version as described in https://github.com/bitcoin/bitcoin/blob/master/doc/JSON-RPC-interface.md#versioning

**Comment by laanwj** [comment]
If it is running *and* you know the datadir, and assuming they use cookie auth, you can use RPC to query the version. Other cases (not currently running, datadir unknown, custom user/password auth) are more difficult.

The version from RPC is useful for sanity-checking the version when your application launches (and is already installed and attuned to a bitcoin core installation), to detect whether the user has upgraded behind your back.

> but is there a way to acquire the version from the data folder somehow?

A datadir at rest doesn't have a version. Although there have been some incompatible changes with regard to data files, such as block index upgrades, usually they tend to be compatible through a range of versions.

I think it's more useful to look for installed version(s) of bitcoin core, and check their version, not to reason from the datadir.

> In that case, is it possible to recognize programmatically her custom data folder if she's using one?

Not in general, there are many ways to pass a custom data directory.

It's possible to mimic bitcoin d/-qt's`' own logic to find the default data directory. This is platform specific. E.g., for UNIX, default to `~/.bitcoin`, look for a `bitcoin.conf` there, there might be a `datadir=...` there that points somewhere else.

But it's not possible this way to find out if someone happens to specify a non-standard datadir through `-datadir=...` or `-conf=...` (with a custom datadir) on the command line from a script or init task.

As there is no 'perfect' way to detect this I think it'd be best to look at some of the hints and based on those, ask the user at install time, whether they provide an existing install of bitcoin core (specifying the data directory if it's not the default one, let them check the auto-detected values) or want to install a new one.

**Comment by emilengler** [comment]
> But it's not possible this way to find out if someone happens to specify a non-standard datadir through -datadir=... or -conf=... (with a custom datadir) on the command line from a script or init task.

A quirky way on UNIX systems would be to parse `ps aux | grep bitcoind`. Then you could get the -conf and -datadir parameter if you have sufficient permissions

**Comment by MarcoFalke** [comment]
It is possible to have multiple datadirs in different locations, so I'd advise against using an assumed datadir without asking the user

**Comment by laanwj** [comment]
to make things worse, if you go around looking for datadirs, here might be datadirs for altcoins that are difficult to distinguish from bitcoin's

**Comment by nopara73** [comment]
Thank you for the replies! In summary: there's no best practice, but numerous approaches and ideas with different tradeoffs, which if someone finds this thread should be able to evaluate. While I believe we did not fully exhausted the topic, we explored it to a reasonable degree and maybe it's better to not waste more time of this repo's devs with this, so closing.
