### ISSUE TITLE
i can't open config file

### ISSUE THREAD

**Issue by malahora** [bitcoin/bitcoin#17259]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by malahora** [comment]
Sorry for my inexperience, I will go to the places you indicate. Thank you
