### ISSUE TITLE
tech issues

### ISSUE THREAD

**Issue by niyog7** [bitcoin/bitcoin#17255]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by niyog7** [comment]
I FOUND SOME BUGS

**Comment by emilengler** [comment]
@niyog7 Hello and welcome to the project.
Could you please tell us which bugs you found and edit the original issue?
IF they are security relevant it should go as an E-Mail to `security@bitcoincore.org`. **SECURITY ONLY**

See: https://bitcoincore.org/en/contact/

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

**Comment by emilengler** [comment]
For some "easy" questions `#bitcoin` on freenode might be a better choice as you usually get faster replies there.
