### ISSUE TITLE
gui: "Increase transaction fee" label should be disabled for watch-only wallets 

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#17263]
It's not possible to bump the fee from the GUI in a watch-only wallet, yet the option is enabled:
 
<img width="344" alt="Schermafbeelding 2019-10-26 om 11 26 47" src="https://user-images.githubusercontent.com/10217/67617446-8e62fe80-f7e3-11e9-80a0-fcc70d683c09.png">

It's also thoroughly confused about the fee, but that's not a problem if we don't show the dialog:
<img width="348" alt="Schermafbeelding 2019-10-26 om 11 25 14" src="https://user-images.githubusercontent.com/10217/67617436-6ffd0300-f7e3-11e9-9931-05ab3b705c7f.png">

**Comment by andronoob** [comment]
I wish this feature will be eventually available for Bitcoin Core.

**Comment by Sjors** [comment]
Presumably #17492 will fix this (cc @instagibbs).

**Comment by instagibbs** [comment]
That's actually surprising. It should fail the `PreconditionChecks`?

**Comment by fanquake** [comment]
@Sjors was this fixed in #17492 (now merged?). If not, can you close and reopen in the [GUI repo](https://github.com/bitcoin-core/gui)? Otherwise, this can be closed.
