### ISSUE TITLE
MinGW Runtime Assertion - Assertion failed!

### ISSUE THREAD

**Issue by StevenLee-CG** [bitcoin/bitcoin#17298]
I got an error when I running bitcoin-qt on windows 10.

**MinGW Runtime Assertion**
Assertion failed!
Program: D:\Bitcoin Core (64-bit)\bitcoin-0.16.1\bin\bitcoin-qt.exe
File: script/interpreter.cpp, Line 1573
Expression:(flags & SCRIPT_VERIFY_P2SH) != 0

Abort Retry Ignore

The program crashes after that. I removed data and reinstalled it, but got same error. 

My PC is Windows 10 64-bit, m3-7Y30 CPU surface 4 with 4GB RAM. 

And I test at  another two PCs, Dell Inspiron  Core i5 4210U, 8 GB, SSD 240GB, and a Desktop with a Core i5 6500, 16GB, SSD 240GB+1TB. but also got this error.

**Comment by StevenLee-CG** [comment]
And in the debug.log, I got this:
```
2019-10-29 10:46:30 Potential stale tip detected, will try using extra outbound peer (last tip update: 2135 seconds ago)
```

**Comment by theStack** [comment]
@StevenLee-CG: Which version of Bitcoin Core do you use exactly? For v0.16.1 (as implied by the pathname) the line number doesn't match the expression.

**Comment by StevenLee-CG** [comment]
It's v0.17.1.

 I got this error on Windows PC and I open this issue on a macbook, so I paste the detail from another issue and change key words to my error, so I get a wrong version expression.

Sorry

**Comment by MarcoFalke** [comment]
So what is the file and line number, as well as the expression that fails?

**Comment by StevenLee-CG** [comment]
The file and line number as following:
```
File: script/interpreter.cpp, Line 1573
Expression:(flags & SCRIPT_VERIFY_P2SH) != 0
```

**Comment by StevenLee-CG** [comment]
This is the assertion it crashes on:
```
size_t CountWitnessSigOps(const CScript& scriptSig, const CScript& scriptPubKey, const CScriptWitness* witness, unsigned int flags)
{
    static const CScriptWitness witnessEmpty;

    if ((flags & SCRIPT_VERIFY_WITNESS) == 0) {
        return 0;
    }
    assert((flags & SCRIPT_VERIFY_P2SH) != 0);
    ......
}
```
When assert((flags & SCRIPT_VERIFY_P2SH) != 0) in script/interpreter.cpp

**Comment by theStack** [comment]
> It's v0.17.1.

For this version, there is also no assertion on line 1573:
https://github.com/bitcoin/bitcoin/blob/ef70f9b52b851c7997a9f1a0834714e3eebc1fd8/src/script/interpreter.cpp#L1573
Checking the successive tagged versions one by one, the earliest I found is v0.19.0rc1 (tag created on 4th of October, so not even a month ago) where line number and expression match:
https://github.com/bitcoin/bitcoin/blob/913972944b4f436a8afc1894352338db6b0f9561/src/script/interpreter.cpp#L1573
This also holds for the current master branch. Are you sure you didn't use one of the v0.19 release candidates or a very recent git build instead of v0.17.1?

**Comment by MarcoFalke** [comment]
Would you mind uploading your executable either as an attachment to a GitHub comment or firefox send or similar?

**Comment by MarcoFalke** [comment]
Alternatively, please let us know where you got the executable from

**Comment by StevenLee-CG** [comment]
After I reloaded the full node syncing, there was no similar problem. 
I will check my old full node. And I will try to reproduce the error and provide more details.
