### ISSUE TITLE
Missing block height in listsinceblock and gettransaction

### ISSUE THREAD

**Issue by BitBargain** [bitcoin/bitcoin#17296]
When using `listsinceblock` to fetch transactions since the last record observed, there is a relevant detail missed that I would like to record in the ledger: `blockheight`.

It is unreasonable for my wallet interface to do an RPC lookup for every new blockhash just to get the height number. There could be hundreds of transactions or even thousands and they could all be processed with a simple call to `listsinceblock` if it wasn't for the lack of `blockheight`.

Currently it looks like:

> "blockhash": "0000000000000000000549800794b27ab10d5e16ac6ad16a7c4a13dae756f80d",
> "blockindex": 1120,
> "blocktime": 1572073467,

I would like it to look like:

> "blockhash": "0000000000000000000549800794b27ab10d5e16ac6ad16a7c4a13dae756f80d",
> "blockindex": 1120,
> "blocktime": 1572073467,
> "blockheight": 601091,

I have the same request regarding the output of `gettransaction` also.

Thanks in advance.

**Comment by BitBargain** [comment]
I forgot to add: same request for `gettransaction` please. Thank you.

**Comment by ryanofsky** [comment]
This seems like a reasonable request, but it would definitely be interesting to know more about your use-case and what you'd use the heights for.

#15931 starts caching block heights, so this could be implemented efficiently in the future

**Comment by BitBargain** [comment]
My use case currently is to store and audit wallet transactions in a database. The columns include some basics such as: date, category, amount, tx_fee, block_height, block_hash, etc.

If `listsinceblock` resumes from an older state, many `getblock` transactions are done just to get the height where it's unknown (I do cache it, but when the wallet interface starts up and scans for any new tx's since the last block, there can be a couple of those). I think it's relevant to store as a basic attribute to any incoming transactions.

It would really be nice not have to do so many lookups unnecessarily. That's all.
