### ISSUE TITLE
code for blocksonly disagrees with documentation

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#17294]
The docs for `blocksonly` say that "Transactions from the wallet or RPC are not affected" but the code says:

    if (gArgs.GetBoolArg("-blocksonly", DEFAULT_BLOCKSONLY) && gArgs.SoftSetBoolArg("-walletbroadcast", false)) {
        LogPrintf("%s: parameter interaction: -blocksonly=1 -> setting -walletbroadcast=0\n", __func__);
    }

Here's the relevant documentation:

    -blocksonly
       Whether to reject transactions from network peers. Transactions from the
       wallet or RPC are not affected. (default: 0)

    -walletbroadcast
       Make the wallet broadcast transactions (default: 1)

Doesn't that imply that `blocksonly` *does* affect transactions from the wallet?

**Comment by MarcoFalke** [comment]
Correct. The documentation should be updated.

**Comment by MarcoFalke** [comment]
My bad in fa8ced32a60dea37ac169241cf9a1f708ef46c4b

**Comment by birtony** [comment]
Hey, I would be happy to work on this!

**Comment by glowang** [comment]
I will work on this!
