### ISSUE TITLE
Stop using `boost::thread_group`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17307]
`boost::thread_group` and its associated join/interrupt mechanism has no equivalent in any C++XX standard.

The interrupt mechanism is basically a condition variable, per thread group, that interrupts `boost::this_thread::sleep_for` and `boost::this_thread::sleep` and raises `boost::thread_interrupted` in the member thread when `group.interrupt()` is called.

Luckily, it's only used for three things:

- CScheduler
- ThreadImport
- Script checking threads

Both of these could have their own interrupt mechanism. Handling "join" for a thread group is trivial.

There's also a bit of usage in the tests, but I think it's related to the above main usages.

It's a blocker every time for changes such as #17253 and  #16117.

**Comment by MarcoFalke** [comment]
I believe this has been solved in #14464 and #14489. Those are up for grabs for someone to rebase and apply some nail polish to the diff :nail_care:

**Comment by laanwj** [comment]
It looks like there is already a helper class for interruptible sleeps:
```
/*
    A helper class for interruptible sleeps. Calling operator() will interrupt
    any current sleep, and after that point operator bool() will return true
    until reset.
*/
class CThreadInterrupt
```

So I think it's a matter of using these in the right places?

**Comment by Patil2099** [comment]
@laanwj  Can I work on this issue?

**Comment by laanwj** [comment]
> @laanwj Can I work on this issue?

Sure!

**Comment by hebasto** [comment]
@MarcoFalke 
> I believe this has been solved in #14464 and #14489. Those are up for grabs for someone to rebase and apply some nail polish to the diff

#14489 has no label "Up for grabs", though ;)

**Comment by adamjonas** [comment]
Note that I have a rebased #14464 branch, but haven't opened a PR based on the [close Boost → C++11 migration project for now](http://www.erisian.com.au/bitcoin-core-dev/log-2019-10-31.html) topic of the dev chat today.

**Comment by laanwj** [comment]
@adamjonas The point with closing the project was, from my side, to signal that all the low-hanging fruit is gone, or currently not worth picking (making our own versions of low-level string/date/time handling and such).

I'm leaving this issue open because I think this structural work is still worth doing. I think, that besides removing the boost dependency, that using traditional threading primitives instead of "thread groups" and "interruptible threads" could improve the code and make it more understandable.

**Comment by MarcoFalke** [comment]
I believe removing boost header includes should continue for the following reasons:

* `std::thread` in C++11 is mostly identical to `std::thread` in C++17. So when we reach C++17, we better have alreay dealt with removing `boost::thread*`, so that the only remaining things are fs and the optional/unique_ptr utils.
* Apart from `serialize.h`, the boost headers are the most memory and cpu hungry to compile
* Depending on less third party modules during the build is a "nice to have"

**Comment by laanwj** [comment]
Sure, I think "speed up the compile" might be an interesting project in itself. Removing unnecessary includes from include files is always a good thing, even without expicit 'move away from boost' rationale.

**Comment by MarcoFalke** [comment]
Please review #18710

**Comment by laanwj** [comment]
I don't think this should have been closed while `boost::thread_group` is still being used.
