### ISSUE TITLE
Re-thinking `bitcoin-cli -getinfo`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17314]
Now that `getinfo` is no longer part of the RPC API, and client-side implementation is not subject to API stability, it's possible to start thinking about making it more user friendly.

I've made a start in #17302 by adding some status fields.

Some other potential ideas:

- Remove noise: fields that users are unlikely to want to query often ~~`protocolversion`, `walletversion`, `keypoololdest`~~ (these three were done in #17650)
- Multiwallet: List balance per wallet
- List all proxies, at least if they're different from the IPv4 one
- Alternative, more human-friendly, format besides JSON? Colors, progress bars :smile:?

**Comment by MarcoFalke** [comment]
We also need more emojis, obviously

**Comment by malevolent** [comment]
Hi @laanwj ,
[This change](https://github.com/bitcoin/bitcoin/compare/master...malevolent:rethink_bitcoin_cli) removes the noisy unwanted fields listed under your first potential idea. I achieved this grand feat by opening vim and pressing dd. I am also in dire need of a rebase.

**Comment by jonatack** [comment]
Adding point 2 (Multiwallet: List balance per wallet). [Proposals here](https://github.com/bitcoin/bitcoin/pull/18453#issuecomment-605521801) if anyone would like to weigh in.

**Comment by jonatack** [comment]
Point 2 above (show balance per wallet) is now done in #18594 which has gone through several rounds of review. Review/ACKs welcome.

**Comment by klementtan** [comment]
Some ideas from #21832 to further improve `-getinfo`:
1. Refactor `ParseGetInfoResult()` to be a method of `ParseGetInfoResult` class
    -  https://github.com/bitcoin/bitcoin/pull/21832#issuecomment-844506315
2.   Allow ANSI color codes on WIN32 with [this command](https://www.codeproject.com/Tips/5255355/How-to-Put-Color-on-Windows-Console).
     - https://github.com/bitcoin/bitcoin/pull/21832#pullrequestreview-673668850
3. Display date/time of latest block verified (maybe even the delta to the current time, to immediately see how far one is behind during IBD, or how long ago the last block was received, respectively)
     - https://github.com/bitcoin/bitcoin/pull/21832#pullrequestreview-673668850
4. show on-disk size of the block chain (getblockchaininfo returns a field "size_on_disk")
    - https://github.com/bitcoin/bitcoin/pull/21832#pullrequestreview-682424334
5. show whether pruning is enabled
    - https://github.com/bitcoin/bitcoin/pull/21832#pullrequestreview-682424334
6. verification progress bar
    - https://github.com/bitcoin/bitcoin/pull/21832#pullrequestreview-682424334

**Comment by prayank23** [comment]
@klementtan `-getinfo` has no section for mempool

Should we add something from `getmempoolinfo` ?

Can start by adding `size`, `unbroadcast count` and `maxmempool`. Add below things later if enough people agree:

```
====================== | 1-5
==========             | 5-10
====                   | 10-50
=                      | 100-200

Size (vMB)             | Fee rate (sat/vByte)
```

**Comment by klementtan** [comment]
@prayank23 SGTM! 👍🏻

**Comment by prayank23** [comment]
Nothing is left. This issue can be closed.
