### ISSUE TITLE
Missing entry to install 

### ISSUE THREAD

**Issue by renepickhardt** [bitcoin/bitcoin#17337]
Bitcoin setup is not successfull on a clean ubuntu system following the install instructions https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md

**Expected behavior**

I would expect that installation to complete and that my setup is able to build bitcoin

**Actual behavior**

Apparently `./configure` gave this error: "configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)". next `make` does not work 

```
make
make: *** No targets specified and no makefile found.  Stop.
**System information**
```

**To reproduce**

The bitcoin version this happens is b54666c849bad258d92d6d1e45a051d36055681e

**Fix **
there are many solutions specified in  https://github.com/bitcoin/bitcoin/issues/2998 but for me the woking one was the comment https://github.com/bitcoin/bitcoin/issues/2998#issuecomment-356455033 from @bellaj 

```  
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
```

So I guess this could be added to the ubuntu section of https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md  ?

**Comment by hebasto** [comment]
> So I guess this could be added to the ubuntu section of https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md ?

From [build-unix.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md):

> Ubuntu and Debian have their own `libdb-dev` and `libdb++-dev` packages, but these will install BerkeleyDB 5.1 or later. This will break binary wallet compatibility with the distributed executables, which are based on BerkeleyDB 4.8. If you do not care about wallet compatibility, pass `--with-incompatible-bdb` to configure.
>
> Otherwise, you can build from self-compiled `depends` (see above).

**Comment by laanwj** [comment]
For the wallet you need some version of BerkeleyDB. On Debian I usually just install the `libdb++-dev`, but for if compatibility with the distributed binaries is important you need to use 4.8.

The supported cross-platform way to build BerkeleyDB 4.8 is to use the `contrib/install_db4.sh` script. This is mentioned in all the `build-*` files.

(the PPA is another option, but as this relies on a third-party source, this is intentionally not mentioned)

**Comment by MarcoFalke** [comment]
https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin says "NOT MAINTAINED (for new versions of Ubuntu)", so I'd rather not use that.
