### ISSUE TITLE
Bitcoin Core tries to connect to a wrong proxy

### ISSUE THREAD

**Issue by Relaxo143** [bitcoin/bitcoin#17333]
I'm trying to use Bitcoin Core with Tor. Tor is running on a separate machine. In the .conf file I have specified:
`proxy=192.168.0.106:9050`, but the logs show `2019-10-31T20:35:05Z tor: Error connecting to Tor control socket
2019-10-31T20:35:05Z tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
`
Why does it try to connect to localhost?

**Comment by qubenix** [comment]
You need to set `-torcontrol=<ip>:<port>` to use the remote control port.
