### ISSUE TITLE
Sign nonstandard input API

### ISSUE THREAD

**Issue by 3s3s** [bitcoin/bitcoin#17400]
**Is your feature request related to a problem? Please describe.**
Someone can send me P2SH transaction where redeem script should be non standard.
For spend bitcoins I can manually create RAW transaction with required redeem script but I can not to sign the input because **bitcoin client can not sign non standard inputs.**
scriptSig example
`<sig> <data>`

Redeem script
`<sig> <data>  OP_DROP OP_CHECKSIGVERIFY` 

When bitcoin core API sign raw transaction it output a new RAW transaction where signature part is included. 
I think this is reason why bitcoin core does not sign non standard inputs: core do not known about where to place signature in custom script. 

**Describe the solution you'd like**
I think it is possible create new API function like
`getsignature rawtx options [inputs1, input2 ...]`
rawtx - hex encoded unsigned raw transaction
options - optional. Default value SIGHASH_ALL 
inpit1, input2 - optional inputs for signing. (not shure about it)

Result: 
signature - hex encoded string that user can manualy place in RAW transaction

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
