### ISSUE TITLE
Accelerated SHA256 with ARM64 crypto extensions?

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17414]
Quite a lot of ARM64 SoC have cryptography extensions, in Linux look for `sha2` feature in `/proc/cpuinfo` or `getauxval(AT_HWCAP) & HWCAP_SHA2` .

Apparently some impressive speed-ups can be achieved, I've heard of 4× to 8× on some SoCs.

Here is some public domain code by Jeffrey Walton that demonstrates how to use it, using intrinsics (which are the best way to do this kind of thing on ARM): https://github.com/noloader/SHA-Intrinsics/blob/master/sha256-arm.c

(I'm creating this issue mostly as reminder to myself but if someone wants to pick it up, fine :smile: )

**Comment by Aa88s** [comment]
Android

**Comment by laanwj** [comment]
Seems a duplicate of #13401.
