### ISSUE TITLE
Use incomptaible BDB headers when newer are available withoun --with-incompatible-bdb on non releases

### ISSUE THREAD

**Issue by emilengler** [bitcoin/bitcoin#17419]
**Is your feature request related to a problem? Please describe.**
I, and lots of others probably, don't do any wallet development but still need a wallet for testing bitcoin-qt changes are other stuff for example so we install the headers from our distribution because it is easier. It is a bit annoying to always pass `--with-incompatible-bdb`

**Describe the solution you'd like**
If it is not a release, check for incompatible headers as well, if compatible were not found and use them without any other cli arg required. If it is a release, keep the current system for users who are compiling the release tarball to avoid wallet breaks.

**Additional context**
This is more a comfort issue and just a nice to have.

**Comment by laanwj** [comment]
Not sure I agree with this. I think having to sometimes specify it (on release branches) and sometimes not (on master) could make things even less comfortable. At least now you get used to always typing it.

Disclaimer: I always use `--with-incompatible-bdb` myself. I only build bitcoin from source (unless testing release binaries) and so don't care about compatibility of my wallets with those.

**Comment by emilengler** [comment]
@laanwj You probably know when you compile a release binary and this happens much less frequently (probably).
And also `--with-incompatible-bdb` should do nothing when compiling a non release

**Comment by fanquake** [comment]
> Not sure I agree with this.

I agree with laanwj. I don't think we need to change/complicate the build system further based on `It is a bit annoying to always pass --with-incompatible-bdb`. How often are you re-configuring? At least configure will remind you when it finds incompatible headers.

**Comment by laanwj** [comment]
It find that, generally in development of autotools-based software, it helps to make a script that wraps the `configure` call with the correct arguments in case you need to re-configure a clean tree for some reason.
