### ISSUE TITLE
Unable to start bitcoind after power failure

### ISSUE THREAD

**Issue by Grey007** [bitcoin/bitcoin#17441]
Hi,

I'm unable to restart bitcoind after a power failure: 

Here is the debug.log error I am getting:

> bitcoin@raspberrypi:~ $ tail -f /home/bitcoin/.bitcoin/debug.log 
> 2019-11-11T16:49:54Z Opening LevelDB in /home/bitcoin/.bitcoin/chainstate
> 2019-11-11T16:49:54Z Fatal LevelDB error: Corruption: CURRENT file does not end with newline
> 2019-11-11T16:49:54Z You can use -debug=leveldb to get more complete diagnostic messages
> 2019-11-11T16:49:54Z Fatal LevelDB error: Corruption: CURRENT file does not end with newline
> 2019-11-11T16:49:54Z : Error opening block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> 2019-11-11T16:49:54Z Aborted block database rebuild. Exiting.
> 2019-11-11T16:49:54Z Shutdown: In progress...
> 2019-11-11T16:49:54Z scheduler thread interrupt
> 2019-11-11T16:49:54Z Shutdown: done

I've tried running:

```
bitcoind -reindex 
bitcoin -reindex-chainstate
```

Not sure what I am doing wrong?

**Comment by MarcoFalke** [comment]
> bitcoind -reindex-chainstate

What is the error message or debug log you get when running this?

**Comment by Grey007** [comment]
> bitcoin@raspberrypi:~/.bitcoin/chainstate $ bitcoind --reindex-chainstate
> Bitcoin server starting
> bitcoin@raspberrypi:~/.bitcoin/chainstate $ tail -f /home/bitcoin/.bitcoin/debug.log 
> 2019-11-11T17:59:31Z Wiping LevelDB in /home/bitcoin/.bitcoin/chainstate
> 2019-11-11T17:59:31Z Fatal LevelDB error: IO error: /home/bitcoin/.bitcoin/chainstate/CURRENT: No such file or directory
> 2019-11-11T17:59:31Z You can use -debug=leveldb to get more complete diagnostic messages
> 2019-11-11T17:59:31Z Fatal LevelDB error: IO error: /home/bitcoin/.bitcoin/chainstate/CURRENT: No such file or directory
> 2019-11-11T17:59:31Z : Error opening block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> 2019-11-11T17:59:31Z Aborted block database rebuild. Exiting.
> 2019-11-11T17:59:31Z Shutdown: In progress...
> 2019-11-11T17:59:31Z scheduler thread interrupt
> 2019-11-11T17:59:31Z Shutdown: done

**Comment by laanwj** [comment]
This looks like low-level file system corruption. Might want to run a `fsck`, and if that doesn't solve it, move the `chainstate` directory out of the way and re-try.

**Comment by emilengler** [comment]
If it is not a problem for you, you can re download your blockchain by deleting your `.bitcoin` folder.
Consider backuping your wallet and `bitcoin.conf`
