### ISSUE TITLE
Have RPC help text refer to correct "network" address type

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#17465]
Currently in RPC help there's a mixture of "Bitcoin address" and "bitcoin address" references everywhere.

I think it'd be a slight improvement to have the test return the name of the network its running on, with `main`, `testnet3` aliased to their respective pet names "Bitcoin" and "testnet"(IIRC, might be wrong on the testnet point what the chain name is).

**Comment by MarcoFalke** [comment]
generally we avoid making the help text dynamic on command line arguments. Especially when it is only test related. So NACK from me.

**Comment by instagibbs** [comment]
ok.
