### ISSUE TITLE
Specifying a third party transaction URL crashes Bitcoin Qt

### ISSUE THREAD

**Issue by Relaxo143** [bitcoin/bitcoin#17467]
**Expected behavior**
Core should save the provided URL and use it for transaction look ups

**Actual behavior**
Core crashes and when started again the URL has not been saved.

**To reproduce**
Run Bitcoin qt with `disablewallet=0`. go to settings/options/display and specify a tx URL.

**System information**

 Running v0.18.1 downloaded from bitcoincore.org

Windows 10, AMD ryzen 2600, SSD

relevant debug logs:
`GUI: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
`

**Comment by fanquake** [comment]
I can't recreate this crash using master or 0.18.1, what URL are you using? I'm also not sure why `disablewallet` would make a difference here; is that the only time it happens?

**Comment by Relaxo143** [comment]
> I can't recreate this crash using master or 0.18.1, what URL are you using? I'm also not sure why `disablewallet` would make a difference here; is that the only time it happens?

You need to be using the wallet to access those settings, don`t you? First I tried removing an old url with an IP (aka leaving the field blank) and it crashed. Now I tried with http://bitchain.tk/ but literally any url crashes it.

**Comment by fanquake** [comment]
> You need to be using the wallet to access those settings, don`t you?

No, the third-party tx URL setting is always shown regardless of how Bitcoin Core is compiled / run. Can you run `bitcoin-qt` under lldb or gdb and get a backtrace?

**Comment by Relaxo143** [comment]
I don`t know what that means. I`ll look it up.

**Comment by laanwj** [comment]
I can't reproduce it no matter how nonsensical the data I enter into that field.

Are you sure it's related to transaction URL or does any change to the configuration dialog cause a crash? It might be that some other field got corrupted.

You might try running with `-resetguisettings` once to clear the GUI settings, and see if it keeps happening. If it solves the problem, I'd be interested in the backup `guisettings.ini.bak` that it writes to your data directory.

**Comment by Relaxo143** [comment]
@laanwj It didn't work. I can still give you the `guisettings.ini.bak` if you want to.

**Comment by laanwj** [comment]
Not necessary; it would only have been useful to know the settings that caused breakage, if a reset had fixed it.

**Comment by Relaxo143** [comment]
@laanwj You were right. It's not the URL field alone. If I open the settings and then click OK (without even changing any of them) to apply them, Core crashes. Sometimes it says "Bitcoin Core can no longer continue safely and will now exit", sometimes it doesn't.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
