### ISSUE TITLE
v0.19.0: Problem with variable m_absurd_fee

### ISSUE THREAD

**Issue by fujicoin** [bitcoin/bitcoin#17464]
The variable m_absurd_fee has only two lines written in the entire source code. It is the following two lines.
validation.cpp: L451
         const CAmount & m_absurd_fee;
     const CAmount & nAbsurdFee = args.m_absurd_fee; 

As a result, isn't nAbsurdFee indefinite?
This causes a problem with the following line:
validation.cpp: L717
     if (nAbsurdFee && nFees> nAbsurdFee)
         return state.Invalid (ValidationInvalidReason :: TX_NOT_STANDARD, false,
                 REJECT_HIGHFEE, "absurdly-high-fee",
                 strprintf ("% d>% d", nFees, nAbsurdFee));

As a result, may an error occur with the "sendrawtransaction" command?

**Comment by MarcoFalke** [comment]
No. The `const` makes the compiler enforce that the value is set on initialization.
