### ISSUE TITLE
v0.19.0: Problem with variable nAbsurdFee

### ISSUE THREAD

**Issue by fujicoin** [bitcoin/bitcoin#17475]
A RAW transaction with a fee exceeding DEFAULT_TRANSACTION_MAXFEE was created and tested. The tests were compared using windows Core v0.18.0 and v0.19.0. Core v0.19.0 was built on Ubuntu 18.04 by gitian build.
The response was confirmed using the sendrawtransaction command on the console. The variable with the following code is displayed in the response.
```
validation.cpp: L717
if (nAbsurdFee && nFees> nAbsurdFee)
return state.Invalid (ValidationInvalidReason :: TX_NOT_STANDARD, false,
REJECT_HIGHFEE, "absurdly-high-fee",
strprintf ("% d>% d", nFees, nAbsurdFee));
```
In the case of v0.18.0, the setting value of DEFAULT_TRANSACTION_MAXFEE or -maxtxfee was reflected in nAbsurdFee.
However, in the case of v0.19.0, the value of "v-size * x" was reflected. I did not know what x was.
However, the values ​​reflected in nAbsurdFee are certainly different between v0.18.0 and v0.19.0. 
For this reason, sendrawtransaction may fail in v0.19.0.

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.19.0.md#updated-rpcs

**Comment by MarcoFalke** [comment]
the static -maxtxfee has been replaced by a fee rate per call (passed in as rpc argument)

**Comment by fujicoin** [comment]
Thank you for answering. I understand. I should have read the release notes properly. (^^;
