### ISSUE TITLE
Use leveldb subtree from the repo instead of a local approach

### ISSUE THREAD

**Issue by emilengler** [bitcoin/bitcoin#17476]
Wouldn't it be a good idea to manually clone the leveldb subtree and use it for the compilation instead of always updating the leveldb/ directory in this repository?
For better security, a commit hash from the other repo could be hard coded into the build system so the leveldb subtree repo can't be corrupted.

The downside would be that it would not be possible to compile offline but the DL process could be done at a very early stage like the configure

**Comment by MarcoFalke** [comment]
I fail to see which problem that would solve, ignoring the problems it introduces

**Comment by fanquake** [comment]
> Wouldn't it be a good idea to

You haven't explained why you think this would be better. Regardless, we aren't about to change our use of sub-modules.

**Comment by emilengler** [comment]
Ok sorry forgot that.
The advantage would be that we don't need to always update the `leveldb` tree in this repository, we can directly use our fork.

**Comment by sipa** [comment]
How is updating the tree harder than updating the commit id of what the build system uses?

It's just an `git subtree merge` command.

**Comment by laanwj** [comment]
There's no reason to change this, so let's leave it alone. We have 757 open issues and 303 PRs, please don't create problems where there are none.
