### ISSUE TITLE
configure: error: No working boost sleep implementation found.

### ISSUE THREAD

**Issue by notmike-5** [bitcoin/bitcoin#17478]
Trying to compile origin/master on Arch, but ./configure is giving the error:

configure: error: No working boost sleep implementation found.

I definitely have boost installed, version is 1.71.0-2. I suspect I may need to statically link this somehow, but don't exactly know how I might do that.

**Comment by MarcoFalke** [comment]
What is your config.log? And the steps to reproduce?

**Comment by notmike-5** [comment]
Sure thing, thanks for the quick reply. On a working Arch install with boost/boost-libs installed I have...

pacman -S boost boost-libs
git clone https://github.com/bitcoin/bitcoin.git
cd bitcoin/
./autogen.sh
./configure      
[produces` configure: error: No working boost sleep implementation found.]

Have tried options: 
--with-boost-thread=/usr/lib/libboost_thread [couldn't link to this]
--with-boost=/usr/lib/libboost [this wasn't right either]

make -j$(nproc) [since I re-cloned the directory I don't even get to this step]

Here is the output of cat config.log | grep boost  https://termbin.com/0dxd

**Comment by MarcoFalke** [comment]
With a truncated config log there is not much we can do.

I followed https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#setup-and-build-example-arch-linux and it worked just fine for me

**Comment by fanquake** [comment]
@notmike-5 Can you provide any more info? Using 21ee676dd6a7d9704367b6412bf8e1e443ec2b5b and an `archlinux/base` Docker container I can't recreate this with `pacman` installed dependencies: `./configure --disable-wallet --without-gui --without-miniupnpc`, or the depends system: ` ./configure --prefix=/bitcoin/depends/x86_64-pc-linux-gnu`.

**Comment by hieunc278** [comment]
Hi @notmike-5 
I have just resolved this issue on my Mac OS Mojave, so I would like to share with you as a reference.

Here is my installation steps :
1. Installed dependencise 
brew install automake berkeley-db4 libtool boost miniupnpc openssl pkg-config python qt libevent qrencode
2. Git clone bitcoin
3. Ran ./autogen.sh successful
4. Ran ./configure, it show error messages 
checking for boostlib >= 1.47.0 (104700)... configure: We could not detect the boost libraries (version MINIMUM_REQUIRED_BOOST or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
checking whether the Boost::System library is available... no
checking whether the Boost::Filesystem library is available... no
checking whether the Boost::Thread library is available... no
checking whether the Boost::Chrono library is available... no
checking whether the Boost::Unit_Test_Framework library is available... no
checking for dynamic linked boost test... no
checking for mismatched boost c++11 scoped enums... ok
configure: error: No working boost sleep implementation found.
5. I checked dependencies installed log and found that 
Warning: boost 1.71.0 is already installed, it's just not linked
You can use `brew link boost` to link this version.
6. I saw that although that boost was installed, however, brew could not create link yet. So I created manually with command "brew link boost"
7. I ran ./configure again and saw that it ran successful.

Please check on your environment again.

**Comment by notmike-5** [comment]
@MarcoFalke here is a config.log: https://termbin.com/9gbq

@fanquake I've downgraded boost and boost-libs before to v1.68 and v1.69 (its all I can think of really). I have since reinstalled boost and boost-libs v1.72. I also went back and just deleted all the boost libs in /usr/lib/ and reinstalled v1.72

@hieunc278 thanks for the ref
 
I tried everyone's ./configure lines but each resulted in the same error: 
`configure: error: No working boost sleep implementation found`

**Comment by brakmic** [comment]
> @MarcoFalke here is a config.log: https://termbin.com/9gbq
> 
> @fanquake I've downgraded boost and boost-libs before to v1.68 and v1.69 (its all I can think of really). I have since reinstalled boost and boost-libs v1.72. I also went back and just deleted all the boost libs in /usr/lib/ and reinstalled v1.72
> 
> @hieunc278 thanks for the ref
> 
> I tried everyone's ./configure lines but each resulted in the same error:
> `configure: error: No working boost sleep implementation found`

Once I had a similar problem when compiling a version for Raspberry Pi and the solution that worked for me was the flag *--with-boost-libdir=PATH_WHERE_YOUR_BOOST_LIBS_ARE*

**Comment by laanwj** [comment]
I'm saddened that this issue comes up again, we've been chasing these kind of errors since 2012 or so, every time there's some subtle problem. If only we could get rid of `boost::sleep` use (but this turns out to be hard #17253 #16117  #17307…).

Aanyhow, this is what causes boost sleep to not be detected in your particular case, a linker error;
```
configure:26523: g++ -std=c++11 -o conftest -g -O2  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include  conftest.cpp -L/usr/lib64 -lboost_system -lboost_filesystem -lboost_thread -lpthread -lboost_chrono  >&5
/usr/bin/ld: /tmp/cck6yHgf.o: in function `boost::system::generic_category()':
/usr/local/include/boost/system/error_code.hpp:498: undefined reference to `boost::system::detail::generic_category_ncx()'
/usr/bin/ld: /usr/local/include/boost/system/error_code.hpp:498: undefined reference to `boost::system::detail::generic_category_ncx()'
/usr/bin/ld: /usr/local/include/boost/system/error_code.hpp:498: undefined reference to `boost::system::detail::generic_category_ncx()'
/usr/bin/ld: /usr/local/include/boost/system/error_code.hpp:498: undefined reference to `boost::system::detail::generic_category_ncx()'
/usr/bin/ld: /usr/local/include/boost/system/error_code.hpp:498: undefined reference to `boost::system::detail::generic_category_ncx()'
/usr/bin/ld: /tmp/cck6yHgf.o:/usr/local/include/boost/system/error_code.hpp:498: more undefined references to `boost::system::detail::generic_category_ncx()' follow
collect2: error: ld returned 1 exit status
```
I'm not sure where this value is supposed to be defined (it seems to be boost_system, which is linked!), whether your boost is miscompiled, or your specific version of boost needs another library to be linked.

**Comment by greenaddress** [comment]
abcore's bitcoin_ndk last working version is 0.18.1 - 0.19.0.1 breaks with boost sleep on all platforms (32/64 arm/x86) https://travis-ci.org/greenaddress/bitcoin_ndk/builds/624403892?utm_source=github_status&utm_medium=notification

I'm investigating, seems the same issue

**Comment by MarcoFalke** [comment]
Maybe it was something related to the m4/boost bump in #15461

**Comment by greenaddress** [comment]
@MarcoFalke thanks - maybe - i will try to see if the suggestions in https://github.com/bitcoin/bitcoin/issues/17010 work

**Comment by greenaddress** [comment]
maybe not the same issue - the android one is related to pthread being linked when not needed on android

**Comment by MarcoFalke** [comment]
Boost sleep has been removed in master/0.20

**Comment by sg-plus** [comment]
you can see this.[https://medium.com/@cavapoo2/setting-up-bitcoin-core-on-ubuntu-16-04-679d98a393bb](url)

**Comment by sg-plus** [comment]
it resolve my problem.[](https://medium.com/@cavapoo2/setting-up-bitcoin-core-on-ubuntu-16-04-679d98a393bb)

**Comment by sg-plus** [comment]
it resolve my problem.[url](https://medium.com/@cavapoo2/setting-up-bitcoin-core-on-ubuntu-16-04-679d98a393bb)
