### ISSUE TITLE
Extract ECDSA Parameters from Verify Function of ECDSA

### ISSUE THREAD

**Issue by tiagomendes7** [bitcoin/bitcoin#17496]
How do i extract ECDSA Parameters from Verify Function of ECDSA used in this tool ?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by laanwj** [comment]
You might want to look at the secp256k1 library instead which implements the ECDSA signing and verification. That said, the secp256k1 curve is well-documented, you shouldn't need to extract its parameters from source code.

**Comment by tiagomendes7** [comment]
In Bitcoin the ECDSA parameters are encoded in a specific way.

Not only that one parameter, the hash of the message, is actually
calculated when verifying ECDSA, which does not happen in "normal" ECDSA,
where you give the hash of the message and then he does the verification.

A segunda, 18/11/2019, 13:15, Wladimir J. van der Laan <
notifications@github.com> escreveu:
