### ISSUE TITLE
Should we still ship 32-bit x86 Linux binaries?

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#17504]
I don't think there's any hurry to do this, just opening an issue as #17503 made me wonder.

In general, running bitcoind in 64 bit is unarguably better. 64-bit registers result in better validation performance and it allows leveldb to use mmap without worrying about virtual memory usage.

Back in the day, the rationale for removing 32-bit x86 builds for Windows but not Linux was that some cheapo VPS still used x86-32 bit.

Is this still the case in the year of (almost) 2020? Is anyone running x86-32 VMs for other purposes than testing software on that architecture? Even with that, how much testing are these binaries getting?

(to be clear, I'm not arguing to *remove support for 32-bit*, just to stop building and providing binaries for it. I also think ARM is a different matter.)

**Comment by hebasto** [comment]
Agree to keep building and providing 32-bit binaries for ARM only.

**Comment by practicalswift** [comment]
Agreed. I think it makes sense to stop shipping 32-bit x84 Linux binaries.

More generally I think we should avoid providing binaries for obsolete or soon-to-be-obsolete platforms where we are uncertain about the amount of real world testing.

See some additional arguments in the somewhat related PR https://github.com/bitcoin/bitcoin/issues/16096 ("RFC: Improving testing under the remaining supported 32 bit platforms").

**Comment by emilengler** [comment]
I'm neutral on this.
I don't use Bitcoin Core on any 32-bit device but there might be some people who don't know how to compile something and wanna run a full node on a very old computer that is no longer in productive use and I think it should never be complicated to setup a full node.

**Comment by laanwj** [comment]
@emilengler The last 32-bit only *physical* Intel processor for general use was [introduced in 2006](https://nl.wikipedia.org/wiki/Lijst_van_Intel-processors). I don't think we have to worry that any are usable for running full validating nodes.
I'm only potentially worried about VPS here.

**Comment by MarcoFalke** [comment]
Freedesktop has stopped shipping 32bit runtimes for flatpak: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/commit/1fa7b7b9e590b31601c2091edcd6dc3ea2e4f132 , so we will be unable to distribute the 32 bit flatpak in the long term: https://github.com/flathub/org.bitcoincore.bitcoin-qt/pull/2#issuecomment-557953031

I think if someone really wants to run on 32 bit, they can simply compile from source.

**Comment by MarcoFalke** [comment]
Also, starting with Ubuntu Bionic 18.04 and Fedora 31, neither OS will ship 32 bit iso images.

**Comment by MarcoFalke** [comment]
Similar to windows XP, what about we send out a tweet and a post to the mailing list asking if it would significantly hinder someone from running Bitcoin Core if the i686 builds were removed?

**Comment by A6GibKm** [comment]
Independent of the choice, providing support for 32bit should also mean to provide a 32bit binary, and, of course, providing a binary means that there is support for it. So I don't much see space for 32bit support and no 32bit binary being shipped.

**Comment by laanwj** [comment]
> So I don't much see space for 32bit support and no 32bit binary being shipped.

I disagree. There are more or less orthogonal. There's plenty of architecture/OS combinations that can run bitcoin core, and we'd try to fix (or at least take PRs for) if it no longer worked, but don't ship executables for.

**Comment by greenaddress** [comment]
If this is about 'shipping' only then no feedback - but in terms of being able to build for linux 32 bit FYI I still use that to make NDK builds (requires arm, arm64, i686 and x86_64) - although I imagine not many new devices are i686 now

**Comment by laanwj** [comment]
This is only about shipping binaries.

**Comment by A6GibKm** [comment]
It would be still interesting to know how many clients are i686.

**Comment by luke-jr** [comment]
A 32-bit VPS is likely to be to reduce RAM usage (which is usually the bottleneck on cheap VPSs). So 32-bit users are also likely to not have the RAM to compile their own (on the VPS).

That being said, I don't know that it makes sense to support cheap VPSs: full nodes exist for providing trust/security, and cheap VPSs are generally insecure by nature.

**Comment by MarcoFalke** [comment]
I sent a note out to the mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2020-January/000085.html
Could someone do the same for our twitter, maybe?

**Comment by laanwj** [comment]
>  So 32-bit users are also likely to not have the RAM to compile their own (on the VPS).

OTOH compilation takes a lot less memory on 32 bit, too. But it's a good point.

**Comment by sha-265** [comment]
How much RAM do I need to compile 32-bit build? I'm using the 32-bit build and I'm trying to figure out if I'll be able to compile it myself.

**Comment by MarcoFalke** [comment]
With debug symbols disabled and clang, it should use less than 1 GB. See https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#memory-requirements

**Comment by sha-265** [comment]
Thanks, I think I will be able to compile by myself.

**Comment by cryptozeny** [comment]
> Should we still ship 32-bit x86 Linux binaries?

in case VPS, i guess nobody use linux32 binary.

> So 32-bit users are also likely to not have the RAM to compile their own (on the VPS).

good point

> In general, running bitcoind in 64 bit is unarguably better. 64-bit registers result in better validation performance and it allows leveldb to use mmap without worrying about virtual memory usage.

totally agreed

> Is anyone running x86-32 VMs for other purposes than testing software on that architecture? Even with that, how much testing are these binaries getting?

i feel nobody use linux32 on their VPS nowadays

> I also think ARM is a different matter.

yeah

**Comment by laanwj** [comment]
Okay, if it's anything to go by, I asked this on twitter a while ago:
https://twitter.com/orionwl/status/1215563281433341952

Two people (of 33541 impressions) told me they were using 32-bit x86 hardware *but not the binaries we ship*.

**Comment by emilengler** [comment]
Will we still run 32bit in CI?

**Comment by luke-jr** [comment]
We should, since 32-bit is still supported even if we're not providing binaries.

**Comment by MarcoFalke** [comment]
The link has been removed from the website: https://bitcoincore.org/en/download/
