### ISSUE TITLE
`make deploy` is failing on macOS

### ISSUE THREAD

**Issue by msafi** [bitcoin/bitcoin#17528]
Running `make deploy` on macOS fails as shown:

```
❯ make deploy
Making all in src
Making all in doc/man
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.
build-aux/install-sh -c -d Bitcoin-Qt.app/Contents/MacOS
STRIPPROG="/usr/bin/strip" /bin/sh /Users/mk/Code/github/bitcoin/bitcoin/build-aux/install-sh -c -s  ./src/qt/bitcoin-qt Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
sed 's/PACKAGE_NAME/Bitcoin Core/' < "contrib/macdeploy/background.svg" | rsvg-convert -f png -d 36 -p 36 -o background.tiff.png
/bin/sh: rsvg-convert: command not found
make: *** [background.tiff.png] Error 127
```

**Expected behavior**

I expect it to succeed.

**Actual behavior**

It succeeded the first time, and I was able to start the app by running `./src/qt/bitcoin-qt`, but after I did `CTRL+C` to quit the process and ran `make deploy` again, it failed and it keeps failing.

I looked at the suggested solutions in https://github.com/bitcoin/bitcoin/issues/8120. I tried running `make deploy` after doing `git clean -dxf`, after restarting my machine, and after deleting `/Applications/Bitcoin-Qt.app`. It still failed.

**To reproduce**

1. Using macOS, run `make deploy`
1. Once finished, run `./src/qt/bitcoin-qt`
1. CTRL+C to quit `bitcoin-qt` process
1. Run `make deploy` again

**System information**

I tried this on `master` branch, commit `30521302f90e4856a7516867b32a4576fa6d98b3` using a macOS 10.14.6 (Mojave)

**Comment by fanquake** [comment]
Install `librsvg`, as it says to do in the macOS [build docs](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md#dependencies) if you want to use `make deploy`.

**Comment by msafi** [comment]
@fanquake Oh, my bad! I missed that step. I installed `librsvg` and it works now!
