### ISSUE TITLE
qt: Fedora + Wayland warnings and issues

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17534]
Fedora 31 + Qt 5.12.5 (system)

Master (26744ae189af3285c5bbf5bfe34691186415f17a) rises some new warnings in `bitcoin-qt` log:
- always at startup
```
QSocketNotifier: Can only be used with threads started with QThread
```
- while working with menus:
```
GUI: Wayland does not support QWindow::requestActivate()
GUI: Non-toplevel surfaces can't request window states
```

**Comment by laanwj** [comment]
Thanks for testing on Wayland.

**Comment by hebasto** [comment]
Related: [SO: How to correctly configure Qt app to launch on wayland platform?](https://stackoverflow.com/questions/55651780/how-to-correctly-configure-qt-app-to-launch-on-wayland-platform)

**Comment by hebasto** [comment]
Another observing: any window cannot set/restore its position.

[QTBUG-80612](https://bugreports.qt.io/browse/QTBUG-80612):
> Then it works as it's supposed to work. Apps (windows) are not allowed to position themself in Wayland. This is a Wayland limitation, not a missing feature or broken behavior.

**Comment by fanquake** [comment]
I'm not exactly sure there's anything for us to fix here, and I'd assume support will improve with new versions of Qt? In any case, if this is something you'd like to keep tabs on, can you open a tracking issue on the [GUI repo](https://github.com/bitcoin-core/gui)?
