### ISSUE TITLE
Listunspent 0 0 doens't see zero conf tx from multisig address

### ISSUE THREAD

**Issue by LNAPI** [bitcoin/bitcoin#17572]
Listunspent 0 0 doens't see zero conf tx from **multisig** address.

**listunspent 0 0**

```
[
]
```

**getaddressinfo bc1q6l3v46phrvxdtlx0pdf68uf9nwx9z72sny02vx**

```
{
  "address": "bc1q6l3v46phrvxdtlx0pdf68uf9nwx9z72sny02vx",
  "scriptPubKey": "0014d7e2cae8371b0cd5fccf0b53a3f1259b8c517950",
  "ismine": true,
  "solvable": true,
  "desc": "wpkh([0d8be7bd/0'/0'/217']03f0c70e33e5b4f88a1b1880c16a12c676208bf04dff10ec516874f07548831c83)#236rd2nh",
  "iswatchonly": false,
  "isscript": false,
  "iswitness": true,
  "witness_version": 0,
  "witness_program": "d7e2cae8371b0cd5fccf0b53a3f1259b8c517950",
  "pubkey": "03f0c70e33e5b4f88a1b1880c16a12c676208bf04dff10ec516874f07548831c83",
  "ischange": true,
  "timestamp": 1558207863,
  "hdkeypath": "m/0'/0'/217'",
  "hdseedid": "8e4014d1943aee2f9b8375c90dfd22ac0200ffb7",
  "hdmasterfingerprint": "0d8be7bd",
  "labels": [
  ]
}
```

While other **non-multisig** tx at the same time is detected.

**listunspent 0 0**

```
[
  {
    "txid": "41057798ed0997920e4ddb9690f714d9c999ea5290f8bd3ddc630cbfd64435cf",
    "vout": 4,
    "address": "bc1q4s4al4nd5786kpj83tx2sw5m3430ulmd7nrr22",
    "scriptPubKey": "0014ac2bdfd66da78fab06478acca83a9b8d62fe7f6d",
    "amount": 0.02996526,
    "confirmations": 0,
    "spendable": true,
    "solvable": true,
    "desc": "wpkh([0d8be7bd/0'/0'/218']0251c8b3fb62f251421890819c927fa6d7580c9ef0bdb0d4336c1b9ba7ce2abbe5)#5j4fxm4c",
    "safe": false
  }
]
```

Latest Ubuntu instance.

**Comment by fjahr** [comment]
I don't think I am not able to reproduce the issue with the info you provided. First of all, the `getaddressinfo` output is not a multisig address but a P2WPKH address (visible in the `desc` field). Then, I also need more info on other commands you have run and what the background of the keys is. Are all the keys controlled by your wallet or not? Did you import the multisig address into your wallet?

In general you will probably want to to import the multisig address and then run `listunspent` with watchonly included. See this test as an example of how you can probably achieve what you are trying to do: https://github.com/bitcoin/bitcoin/blob/3e949380725ca32be6c9812a926727b0a45723a9/test/functional/wallet_listtransactions.py#L94. Also note there that this does wait for one confirmation but I if you remove this ([commenting out this line](https://github.com/bitcoin/bitcoin/blob/3e949380725ca32be6c9812a926727b0a45723a9/test/functional/wallet_listtransactions.py#L98)) then the test still succeeds.
