### ISSUE TITLE
Mempool fields in Debug Windows show "N/A"

### ISSUE THREAD

**Issue by Relaxo143** [bitcoin/bitcoin#17576]
**Expected behavior**
Show and update the number of txs in the mempool in real time

**Actual behavior**
Shows "N/A"

**To reproduce**
Tried restarting the node. reinstalling Core and running it without the .conf file. Issue persists. I'm not sure how to reproduce it.

**System information**

 v0.19.0.1 downloaded from bitcoincore.org

Win10, Ryzen 5 2600, SSD

It happened after upgrading from 0.18.1 to 0.19.0.1
getrawmempool returns transactions, so the mempool is working. It appears to be a GUI issue
![Screenshot_32](https://user-images.githubusercontent.com/42069389/69496398-837eb500-0eda-11ea-95df-182c1f90c28e.png)

**Comment by laanwj** [comment]
This will be fixed with #17427.

**Comment by mruddy** [comment]
I see the same issue with the new release `Bitcoin Core version v0.19.0.1 (release build)`. This is the command line that I used:

`bitcoin-qt -txindex -datadir=/redacted -persistmempool=0 -server -rpcuser=redacted -rpcpassword=redacted`

**Comment by mjlamb** [comment]
Hi reporting the same issue, both "Current number of transactions" and "Memory Usage" both = N/A, upgraded from v0.18.1 --> v0.19.0.1

**Comment by fanquake** [comment]
Closing this, as the fix has been backported to the 0.19 branch in 2aba76ce02dd86df1b7714ff839588b7b2657c0a and a284bbbee805cd03664fd27656795a9f7d3eeca7.
