### ISSUE TITLE
Bisq cannot connect to Bitcoin Core v0.19 in default settings

### ISSUE THREAD

**Issue by esackbauer** [bitcoin/bitcoin#17589]
Description of issue:
Since Bitcoin Core release 0.19,  BIP111 and BIP37 (peerbloomfilters) are deactivated by default.
Because of this, Bisq cannot connect to any node running on 0.19 in default config.

Expected outcome:
Bisq should connect to any Bitcoin core node with recent release.

Steps to reproduce:
1. Configure Bisq to use a certain node running v 0.19 (I used my own node)
2. Starting Bisq results in not getting connected.

Versions used:
Bisq 1.2.3

Bitcoin Core 0.19.0.1
from bitcoin core website

Link to change log describing new default settings for BIP111 and BIP37 (see "P2P changes"):
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.19.0.1.md

Workaround: Use a node which has "peerbloomfilters=1" set. Whitelisting did not work for me.

**Comment by TheBlueMatt** [comment]
This seems like an issue with release notes or whitelisting? How did you try to whitelist (whitebind? whitelist? etc).

**Comment by esackbauer** [comment]
> This seems like an issue with release notes or whitelisting? How did you try to whitelist (whitebind? whitelist? etc).

I couldn't find a hint in the Bisq documentation that BIP37 is mandatory. 
I tried now whitelisting my client network 192.168.1.0/24, it works with:
whitelist=bloomfilter@192.168.1.0/24

**Comment by lockhartheavyindustries** [comment]
FWIW, if you're running Bisq and bitcoind on the same box, I found that this worked fine also:

whitelist = bloomfilter@127.0.0.1

**Comment by Septem151** [comment]
Should this not be an issue in the Bisq repository rather than Bitcoin Core? It was known ahead of time that the v0.19 release would disable BIP37 & BIP111 by default, and this is an issue with Bisq not Bitcoin Core.

**Comment by laanwj** [comment]
Yes, it's a documentation issue at most, and I think that documentation belongs in BISQ's setup documentation. This repository is not a place it will be seen.

If this would have been reported to us (say, in the rc phase), that this would require a change of settings for BISQ, it could have been mentioned specifically in the release notes. It was of course mentioned that `-peerbloomfilters` is now disabled by default.
