### ISSUE TITLE
Update the merging policy

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17594]
After #17586 will be fixed, should we update the merging policy to require successful AppVeyor build?

From [IRC](http://www.erisian.com.au/bitcoin-core-dev/log-2019-11-25.html#l-156):
> \<wumpus\> I mean the reason that appveyor breaks all the time is because people ignore appveyor before merging, because it breaks all the time, we kind of need to break that circle *shrug*
> \<meshcollider\> true, appveyor has failed on pretty much every single open PR so it kinda just becomes cry-wolf
> \<meshcollider\> we need to fix it and then rebase every PR at once ;)

**Comment by MarcoFalke** [comment]
> we need to fix it and then rebase every PR at once ;)

While rebasing does fix this, a simple "re-run build" might be sufficient as well. Not sure who has the rights to re-run a build, but re-opening the pull request is a work around

> should we update the merging policy to require successful AppVeyor build?

That is already the merging policy. However, sometimes there are intermittent failures, so we can't enforce it.

Also, in this particular case the error came from a package that was upgraded below our feet. This has trade-offs:

* Either we not fetch the latest package and risk that the documentation (list of packages) goes stale
* or we check that the documentation is still up to date and risk that appveyor returns red

Pick one, but not both ;)

**Comment by MarcoFalke** [comment]
cc @sipsorcery

**Comment by laanwj** [comment]
True, that is already the merging policy. Sometimes the CIs break, it's a fact of life, adding words to a document won't change that. Although annoying, I also don't see it as particularly problematic, as long as people are motivated to fix it (which happened really quickly).

**Comment by sipsorcery** [comment]
For my 2 cents I find appveyor CI to be marginally beneficial. Mostly due to the build time and fragility or maintaining it. That being said for a project like Bitcoin Core where catching problems far outweighs rapid development cycles it does seem justified.

As I'm writing I have just succeeded in porting the appveyor job to Github Actions and have run a successful build (minus tests). It looks like build time and maintenance overhead will be approximately the same as appveyor but the [usage limits](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits) do look a lot more appealing. If it does support 20 concurrent CI jobs that could significantly improve the situation for Bitcoin Core PR writers waiting for the build results.

**Comment by MarcoFalke** [comment]
An alternative to GitHub actions would be CirrusCi, which at least gives twice the amount of parallel builds: https://cirrus-ci.org/faq/#are-there-any-limits
Another alternative would be to ask Appveyor to raise our limit.

Anyway, thanks for working on this. I am lacking the background on Windows to be of any use here.

**Comment by sipsorcery** [comment]
> An alternative to GitHub actions would be CirrusCi

Probably worth doing some benchmarking on. Once I've got GitHub actions working will take a look at CirrusCi.

> Another alternative would be to ask Appveyor to raise our limit.

+1 for that. There are currently 13 appveyor jobs queued for PR's. That's an improvement from about 20 at this time yesterday but at approx an hour a job that's a long wait.

**Comment by MarcoFalke** [comment]
Hmm, on https://www.appveyor.com/pricing/ it says that an additional machine is $25/month for FOSS. However, on the billing page they say 50$.

![Screenshot from 2019-11-26 10-39-12](https://user-images.githubusercontent.com/6399679/69648477-67455a00-1039-11ea-8247-59e375c8b97a.png)

**Comment by MarcoFalke** [comment]
Ok, we just sent them 50$ and there are now two parallel builds on https://ci.appveyor.com/project/DrahtBot/bitcoin/history

We can upgrade/downgrade as needed in the future.

**Comment by MarcoFalke** [comment]
Closing this for now. Let's revisit when a problem pops up in the future.

**Comment by sipsorcery** [comment]
I'm agnostic on CI but the Github Actions first impressions are that it will facilitate a lot higher loads than AppVeyor and is **free** (of course the load could suffer once usage increases and pricing could also change).

I was able to run 10 consecutive Bitcoin Core build jobs (before I stopped adding more).

![actions_running](https://user-images.githubusercontent.com/197660/69668303-8539ab80-1087-11ea-8be7-90b412654097.png)

The jobs are almost identical to appveyor except for the unit tests which I've had some problems with.

![ghactions_build](https://user-images.githubusercontent.com/197660/69668376-a9958800-1087-11ea-855a-3febac25842c.png)

A comparison of two jobs chosen at random for the `msbuild` stage:

github action: 16m 50s
appveyor:        38m 33s

![actions_completedjobs](https://user-images.githubusercontent.com/197660/69668605-26c0fd00-1088-11ea-8a71-4c6413d0b5cb.png)

The github action job is contained in a single yml file, same as appveyor. I have it configured in a branch on my fork and will leave it running. As far as I can tell it couldn't do any harm to enable it on the main Bitcoin repo. It doesn't need to be integrated into the PR workflow. It would be interesting to see how the build queue performed with a trigger for PR's. 

If there's interest I can create a PR for the job.

**Comment by laanwj** [comment]
Why I don't blame AppVeyor too much for these kind of temporary issues: today, it's again the turn for Travis CI to fail due to a dependency issue outside our control (#17626).

> If there's interest I can create a PR for the job.

Well, the "faster for free" part is kind of nice. The essential thing is that it tests the MSVC build system and runs the unit/functional tests.

**Comment by sipsorcery** [comment]
I'll submit a PR with the GitHub Actions job for consideration. Note that if it does get merged it will need an admin on the repo to manually create the action (once off task).
