### ISSUE TITLE
qt: Rename intro.* to introdialog.*

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17607]
... as suggested by [qt/README](https://github.com/bitcoin/bitcoin/tree/master/src/qt#dialoghcpp):

> ***dialog.(h/cpp)**
> Various dialogs, e.g. to open a URL. Inherit from QDialog.

**Comment by laanwj** [comment]
This seems to me to be renaming for the sake of renaming :smile: It's possible to defend shorter naming (in the absence of ambiguity) as well.

Doesn't seem worth keeping a tracking issue open for. I'm not sure why you open this as issue instead of a PR.

**Comment by hebasto** [comment]
@laanwj 
> This seems to me to be renaming for the sake of renaming :smile:

Not at all ;)
Objects of `QDialog` class and its subclasses could spin an additional event loop, that could block the main (GUI) event loop (#17145).

Following the naming convention, mentioned in OP, makes reasoning about possible the GUI event loop blockers easier.

>  I'm not sure why you open this as issue instead of a PR.

That was a deep night - just have fixed an idea before sleeping ;)

**Comment by laanwj** [comment]
It's fine, initially this file wasn't named after any particular class because it contained various utility functions that had to do with initial use of the program. I don't think this is true anymore.

**Comment by fanquake** [comment]
> Doesn't seem worth keeping a tracking issue open for. 

Agree.
