### ISSUE TITLE
Add Support for x32-bit/x86 Windows Devices

### ISSUE THREAD

**Issue by Zorono** [bitcoin/bitcoin#17609]

**Comment by laanwj** [comment]
Sorry, x86_32 is on the way out. The last release that shipped binaries for 32-bit x86 Windows was 0.17.1. It was removed in #15939. See https://github.com/bitcoin/bitcoin/pull/15939#issuecomment-489568065

> This was bound to be a somewhat controversial decision: however one architecture per platform is great for maintenance-heavy outlier platforms such as Windows (and MacOSX). This allows for more focus in testing and, and hopefully a better user experience and better security, in time. Cross-compilation to windows is fraught with some risks, and they're minimized by only having one toolchain (mingw-w64) to check.

It *might* still be possible to build your own binaries, but no guarantees on that either. Your best chance of running Bitcoin Core on x86-32 is using Linux or a Linux VM.

(x86-32 Linux builds might also be removed at some point in the future—#17504—though not for the same reason, so less urgently.)

**Comment by practicalswift** [comment]
@Zorono What Windows version are you using?

**Comment by Zorono** [comment]
@practicalswift  Windows 8.1 N Pro

**Comment by practicalswift** [comment]
@Zorono Are security updates still provided for Windows 8.1 (`x86_32` version)?

**Comment by Victorsueca** [comment]
According to [Microsoft's lifecycle sheet](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet), mainstream support for Windows 8.1 ended in January 9, 2018. However, it will still receive security updates as part of it's extended support up until January 10, 2023.

**Comment by Zorono** [comment]
@practicalswift yes
@Victorsueca that's sad news for me :(
