### ISSUE TITLE
Bitcoin is no longer experimental, it is a real currency.

### ISSUE THREAD

**Issue by growl360** [bitcoin/bitcoin#17608]
Replace the "experimental" part on the FAQ and other info pages (GitHub and the website). Bitcoin isn't experimental anymore.

**Comment by laanwj** [comment]
It's both a real currency and in some aspects, still very experimental and risky. In the same way an experimental medical treatment is very real.

Personally, I think it's better to over-warn than to create false trust. Hopefully it triggers people to do their own research and not take things at face value. Also, compared to other currencies which have their roots hundreds or thousands of years ago, things are very experimental.

I think this is a discussion that is mainly based on opinion and personal risk tolerances. There's a similar issue every few years. **Are we non-experimental yet?** If bitcoin survives, one day the answer will be obvious. But right now it's not so black or white, removing this word would be purely about signalling, but why?

**Comment by growl360** [comment]
Saying experimental means it isn't ready for use. I think we can safely say that Bitcoin is a pretty mature project.

I think it might drive new comers away from Bitcoin, they might think it's only for developers.

But I like your thinking with 

> Hopefully it triggers people to do their own research and not take things at face value. 

It should be fine as it is.
