### ISSUE TITLE
rpc: failure calling dumptxoutset with invalid filename

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17612]
```bash
src/bitcoin-cli dumptxoutset utxo.dat/

error code: -1
error message:
CAutoFile::operator<<: file handle is nullptr: unspecified iostream_category error
```

**Comment by brakmic** [comment]
Hi,

[These changes](https://github.com/brakmic/bitcoin/commit/b721eeef473d80a8520ede8b7a1383e12fd5a93a) add file name checking via fs::is_regular_file and return proper JSON-errors if not. Functional & Unit Tests introduced as well.

However, there are other alternatives like boost's [name_check](https://www.boost.org/doc/libs/1_71_0/libs/filesystem/doc/portability_guide.htm) functions, but I think that is_regular_file from C++ std is sufficient enough.

This of course needs more rigorous checking before opening a PR as I've only tested it under macOS Catalina. 

Regards,

**Comment by jamesob** [comment]
Hi @brakmic. Those changes look good to me! You should just go ahead and open the PR. Thanks for contributing.

**Comment by brakmic** [comment]
Ok, then I'll open a PR!

**Comment by petterhs** [comment]
Sorry @brakmic. My bad, didn't see that you had something proposed already. I'll close it

**Comment by brakmic** [comment]
No problem, @petterhs :)
Thanks!

**Comment by brakmic** [comment]
Moved the original PR to https://github.com/bitcoin/bitcoin/pull/17623

**Comment by johnson73A** [comment]
Hffjjhdf

**Comment by MarcoFalke** [comment]
@fanquake Any pointers on how this should be solved? I don't think this is a bug, but a feature.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core?

**Comment by fanquake** [comment]
Happy to close this.
