### ISSUE TITLE
Memory pool information update does not work

### ISSUE THREAD

**Issue by zeven74** [bitcoin/bitcoin#17610]
In the latest version v0.19.0.1, in Information window, the "Memory Pool" information says:
"Current number of transactions N/A"
and
"Memory usage N/A"

I am able to run comands to see transactions in mempool, so its there, so should not say "N/A"

"Current number of transactions" and "Memory usage" should show values.

See screenshot

I rebooted machine, I restarted Bitcoin Core several times. It still says "N/A".

 v0.19.0.1, downloaded from bitcoin.org website. Downloaded the 64bit EXE file

Windows 10, Intel Core i7-7700 @ 3.60 GHz, SSD for app and Samsung M2 for data.

See above

[debug.log](https://github.com/bitcoin/bitcoin/files/3891062/debug.log)
![Capture](https://user-images.githubusercontent.com/6368514/69617250-37498700-1038-11ea-9e85-1c8829268765.PNG)

I can be contacted at zeven74@gmail.com for any questions or information.

**Comment by zeven74** [comment]
PS: I just installed the new version v0.19.0.1 on top of previous version, v0.18.1, which was fully synced before install of the new version.

**Comment by zeven74** [comment]
I can see that this is already reported. It will be fixed with #17427

**Comment by laanwj** [comment]
Yes, i's been reported and will be fixed in next release. Where were all you people when testing the rcs :smile:
