### ISSUE TITLE
GUI: testmempoolaccept in console cuts the end of the txhex

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#17618]
How to reproduce: Build a transaction with ~190 inputs, get the hex and issue `testmempoolaccept [\"{txhex}\"]` in the GUI console. It'll give back a `TX decode failed (code -22)` with a stripped txhex where the end is cut down.

**Comment by 0xB10C** [comment]
How long (in chars) is the is your txhex? 
How many chars are cut off?
How long is the returned txhex?

**Comment by laanwj** [comment]
I think this is a known issue. Qt cannot handle very large data input, it cuts off at some point. Fixing this would mean implementing a "scalable" input field that still performs well with large amount of pasted data, so I've removed the "Good first issue" label.

Does this also happen if you use RPC through the cli? (if your shell runs into problems too, try input from stdin with `-stdin`, it's one reason that option was added)

**Comment by nopara73** [comment]
> Does this also happen if you use RPC through the cli? (if your shell runs into problems too, try input from stdin with -stdin, it's one reason that option was added)

Yes, I'm on Windows though. I tried it both with command line and powershell and both of them are cutting it.

@0xB10C After reading @laanwj's reply I think answers for your questions are irrelevant. If you think it's still helpful, I can dig it up and give you exact numbers.

Overall, it's a bit annoying, but oh well, if nobody feels like fixing it, it's not the end of the world, in that case just let the robot to autoclose the issue after it gets too old.

**Comment by instagibbs** [comment]
if you can share the exact setup/hex somewhere I can take a stab diagnosing at least. I'm not sure the Core wallet is even allowed to make something so large :)

**Comment by laanwj** [comment]
> Yes, I'm on Windows though. I tried it both with command line and powershell and both of them are cutting it.

At the same length?

> @0xB10C After reading @laanwj's reply I think answers for your questions are irrelevant.

If it also happens with `-cli`, even in `-stdin` mode (so when piping in arguments instead of on the command line). I don't think so. It may be something else than the GUI issue that I expected.

**Comment by 0xB10C** [comment]
Did some experimenting on Linux. Can't comment on Windows. 

---

- 95ba007be428dba2a4ec725a878437ce7033fb41e56a994a4174444106bffede 
- 202 inputs
- 59737 chars

```bash
bitcoin-cli testmempoolaccept [\"$(bitcoin-cli getrawtransaction 95ba007be428dba2a4ec725a878437ce7033fb41e56a994a4174444106bffede)\"]
```
works fine.

---
- 1324108af3d8193095b0b5e19bf3d4d678e976a12be28f0c7fcca303a1c9a586 
- 378 inputs 
- 111605 chars

```bash
bitcoin-cli testmempoolaccept [\"$(bitcoin-cli getrawtransaction 1324108af3d8193095b0b5e19bf3d4d678e976a12be28f0c7fcca303a1c9a586)\"]
```

works fine.

---


- 6723a56bdf434633315ae78acfd08ef8a2fb5ff15a84bf4c729f09d9e8eb9aac 
- 533 inputs
- 157277 chars

```bash
bitcoin-cli testmempoolaccept [\"$(bitcoin-cli getrawtransaction 6723a56bdf434633315ae78acfd08ef8a2fb5ff15a84bf4c729f09d9e8eb9aac)\"]
-bash: /usr/bin/bitcoin-cli: Argument list too long
```
Does not work, but that's a Linux kernel restriction. Works with `-stdin` as expected.

```bash
echo [\"$(bitcoin-cli getrawtransaction 6723a56bdf434633315ae78acfd08ef8a2fb5ff15a84bf4c729f09d9e8eb9aac)\"] | bitcoin-cli --stdin testmempoolaccept
```

**Comment by nopara73** [comment]
> At the same length?

No. That's why I did not report it in my original post, because the cut happens before the command is sent, so that has nothing to do with Core.

**Comment by laanwj** [comment]
According to the documentation of QLineEdit on the `maxLength` property (https://doc.qt.io/qt-5/qlineedit.html#maxLength-prop)
```
By default, this property contains a value of 32767.
```
It doesn't say that the value can't be increased to a larger number. Though, it would have to be tested that the GUI doesn't become unusably slow, which I expect to be the reason for the limit.
