### ISSUE TITLE
"2" address unexpectedly changed to "m" address in Testnet

### ISSUE THREAD

**Issue by wilsonpc** [bitcoin/bitcoin#17616]
Using Bitcoin Core 0.18

Testing a change I made to my local NOMP pool software.

- My Bitcoin Core **bitcoin-cli getnewaddress** gave me the address that NOMP used to communicate with the Bitcoin Test Network (2N5tv3gJzBD1zZ2hri2ffYbHsm1AEhpNQFz); 
- I began mining; 
- I found 6 blocks, but at the heights found, instead of having my "2" address, it showed all were found by the (random?) "m" address in the link below:

[Found these blocks on Testnet](https://tbtc.bitaps.com/mtAeMSyVpsdX3BrVdNMaKwA1G8G4GMWHpF) (other transactions shown are test transactions with faucet coins)

I have no idea where this "m" address came from or how or why it "changed" from my "2" address; it doesn't belong to my Bitcoin Core wallet and I have no access to the funds (not an issue but it would be nice to return faucet coins). 

Concern is whether something like this can occur on Mainnet.

**Comment by sipa** [comment]
This looks like whatever software interpreted the address does not support P2SH addresses, and even worse, treats them like P2PKH addresses (ignoring its version byte). This is potentially a serious bug, but I doubt it's related to Bitcoin Core.

**Comment by wilsonpc** [comment]
> treats them like P2PKH addresses (ignoring its version byte)

@sipa Please tell me what about the situation made you say the version byte might be ignored

**Comment by sipa** [comment]
Something (NOMP?) accepted a P2SH address (which was created by Bitcoin Core), but apparently interpreted it as a P2PKH address. This is a bug I've seen before in custom, undertested software. The symptom is that you see a transaction to a seemingly unrelated P2PKH address, which seems to be what is happening here.

The rest of your questions make no sense: the "2" in the address *is* the (encoding of) the version number.

**Comment by wilsonpc** [comment]
Thanks.
I misunderstood/misread your reference to version byte.  When I saw your comment it stood out because I previously noticed that the 4-byte version number in the block header was a 1 and I was wondering whether that was incompatible with a P2SH address.  I now see that you were referring to the address version byte.

**Comment by sipa** [comment]
Oh, yes, the address version byte, sorry?

**Comment by wilsonpc** [comment]
I found the same or very similar issue reported 2 times in other NOMP forks, so I agree that this is not related to Bitcoin Core.  Thanks for your help
