### ISSUE TITLE
doc: unify epoch time description in RPC output

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17613]
There are currently multiple different ways that we describe UNIX epoch time in the RPC documentation / output, including `since epoch`, `epoch (Jan 1 1970 GMT)`, `Unix seconds-since-epoch`, `since epoch (midnight Jan 1 1970 GMT)`, `(seconds since Unix epoch)` and likely more. These can all be unified to a single string, possibly just `UNIX epoch time`. See some related [IRC discussion (around 7:30)](http://gnusha.org/bitcoin-core-dev/2019-11-26.log).

**Comment by jonatack** [comment]
On it :)
