### ISSUE TITLE
[Question] Compiling only bitcoind, not others.

### ISSUE THREAD

**Issue by hyunsooda** [bitcoin/bitcoin#17622]
[Question]

Hi :) I'm working on bitcoind to write something to test locally.

When I type ```make``` In the working directory(top directory), the compile process(code) which is written in Makefile is very long time because others are compiled with.

So this is time-consuming in my current work. **I'd like to compile only bitcoind !**.

Can I get some guide? Thanks.

**Comment by fanquake** [comment]
```bash
make -C src/bitcoind
```

**Comment by emilengler** [comment]
You could also disable not needed components with the build system. For example you can disable `bitcoin-bench`, `bitcoin-qt` and `bitcoin-tx` with
```
./configure --disable-gui --disable-tx --disable-bench
```

**Comment by hyunsooda** [comment]
@fanquake, @emilengler  Thanks! have a nice day :)
