### ISSUE TITLE
Criteria to drop Trusty Travis

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#17628]
@emilengler attempted removing the Trusty Travis build in #16930, but this was considered premature. Currently this Travis machine is broken (#17626), hopefully temporarily. It seems useful to have a list of criteria ready for when it can safely be dropped:

As @MarcoFalke pointed out:
> This is still used to ensure we can build with the minimum required qt and boost versions

Minimum versions are defined here: https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md

Our minimum QT version is 5.5.1. Trusty ships with 5.2.1, Xenial ships with 5.5.1. So we don't need Trusty for QT.

Our minimum Boost version is 1.47.0. Trusty ships with 1.54 and Xenial ships with 1.58, so neither covers the oldest version. Discussion about the mimimum required boost version is in #8875. We shouldn't drop Trusty until we bump the minimum version to 1.58.

I did not look at other dependencies.

**Comment by laanwj** [comment]
Maybe it'd make sense to replace Ubuntu Trusty with Centos 7 as the "check ancient backward compatibililty" Travis run.
