### ISSUE TITLE
build: Caching for macOS on Travis

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17638]
It seems the following directories

https://github.com/bitcoin/bitcoin/blob/abb30de63f368c9875c3f2a4cfe91b1daf9412da/.travis.yml#L38-L40

are never cached on Travis macOS builds due to `tar` fail:

```
changes detected, packing new archive
tar: Failed to set default locale
```

E.g., https://travis-ci.org/bitcoin/bitcoin/jobs/618772348

**Comment by MarcoFalke** [comment]
Cleared the cache and this still happens. Please remove those two lines if they do nothing.

**Comment by rikur** [comment]
I wish there was a way to reproduce this locally.

I think caching is working fine, but as packages are updated in homebrew  `brew cleanup` removes the old cached package downloads to prevent the cache size from bloating up. In other words `changes detected, packing new archive` should not show up in very macOS build, but shouldn't be rare either.

Maybe @Sjors can confirm?

**Comment by Sjors** [comment]
I would prefer fixing the cache over dropping it. macOS Travis is incredibly buggy though.

Sounds like we should check if the tar part actually fails, or just throws a spurious error: `Failed to set default locale`

Try changing the locale to `en_US.UTF-8` (in `00_setup_mac_env_host.sh`) and/or explictly setting `LC_MESSAGES`.

Inspiration:
* https://stackoverflow.com/a/46445700
* http://www.janosgyerik.com/fixing-r-error-in-mac-os-x-tar-failed-to-set-default-locale/

**Comment by laanwj** [comment]
Are you sure "tar: Failed to set default locale" is a fatal error and not just a warning? Some tools (e.g. Perl) will print screenfuls of locale errors and still continue to do what they do.

**Comment by hebasto** [comment]
> ... we should check if the tar part actually fails...

The mentioned cache files are not uploaded, unlike xcode cache.

**Comment by MarcoFalke** [comment]
I think we shouldn't just blindly cache anything without reason. Are you sure caching this speeds up the build?

**Comment by Sjors** [comment]
We don't know until we fix it, but brew install seems to take about 80 seconds: https://travis-ci.org/bitcoin/bitcoin/jobs/618772348#L93

**Comment by MarcoFalke** [comment]
Huh, there it says that the packages were already downloaded (i.e. cached)? https://travis-ci.org/bitcoin/bitcoin/jobs/618772348#L138

**Comment by Sjors** [comment]
That suggests the error is spurious, i.e. the cache is working.
https://github.com/bitcoin/bitcoin/issues/17638#issuecomment-561556136

**Comment by hebasto** [comment]
> Huh, there it says that the packages were already downloaded (i.e. cached)?

Could this be verified by clearing the cache?

**Comment by Sjors** [comment]
@MarcoFalke do you have the logs to the first run after your restart? https://github.com/bitcoin/bitcoin/issues/17638#issuecomment-561341344

**Comment by MarcoFalke** [comment]
Yes, here:
* https://travis-ci.org/bitcoin/bitcoin/jobs/620547507#L78
* https://travis-ci.org/bitcoin/bitcoin/jobs/620547507#L335

**Comment by MarcoFalke** [comment]
Ok, so it is only a warning that can be ignored or maybe fixed with something like https://github.com/bitcoin/bitcoin/issues/17638#issuecomment-561544094
