### ISSUE TITLE
v0.19.0.1 makes mempool N/A

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#17646]
On Fedora 31 I have upgraded from v0.18.1 to v0.19.0.1 and found mempool now shows N/A in GUI for both Current number of transactions and Memory usage.

Restoring to the earlier version v0.18.1 resolves the issue.

**Comment by fanquake** [comment]
Thanks. This is a duplicate of #17576, and will be fixed in `0.19.1`.

**Comment by Willtech** [comment]
Thank you for pointing that out. I searched, nobody finds closed tickets but there is not much other process to handle them.
