### ISSUE TITLE
build: Discrepancy in Trusty Travis build

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17656]
https://github.com/bitcoin/bitcoin/blob/35eda631ed3bd23d4a41761a85a96f925d4a6337/ci/test/00_setup_env_native_trusty.sh#L10

https://github.com/bitcoin/bitcoin/blob/35eda631ed3bd23d4a41761a85a96f925d4a6337/ci/test/00_setup_env_native_trusty.sh#L14

Either Qt packages are redundant or `--with-gui=no` is unwanted.

Which one?

**Comment by MarcoFalke** [comment]
It can not build with the gui, because the qt5 version shipped in trusty is too old. I think it can be removed.

**Comment by hebasto** [comment]
Closing as trusty build has been removed in #17635.
