### ISSUE TITLE
Wallet: breaking cs_wallet into more fine-grained locks

### ISSUE THREAD

**Issue by ariard** [bitcoin/bitcoin#17667]
Once https://github.com/bitcoin/bitcoin/pull/16426 merged, splitting our big `cs_wallet` into multiple ones would make sense because multiple RPCs won't be in conflict anymore to hold `cs_main`.

New locks like `cs_mapWallet` and `cs_mapTxSpends`, while handling well cases like we don't want to commit twice a coin to different transactions or return twice an address to avoid key reuse. Multiple "read" RPCs like `listtransactions` or `listsinceblock` should work smoothly concurrently without stopping each other.

I don't know exactly what is possible but I think there is room for improvements and I don't plan to do it so feel free to dig into it.

See logs https://bitcoincore.reviews/16426.html for more context.

**Comment by ariard** [comment]
Yes don't have spent that much time thinking on it, so don't have any strong inclination, just wanted to raise the awareness than if `cs_main` get removed it's now worthy to do work to improve performance, either way with more fine-grained locks or short-lived, just-in-time mutex holding

**Comment by MarcoFalke** [comment]
`cs_main` was removed from the wallet. You may open a new issue if there is anything else to be done here.

**Comment by ariard** [comment]
@MarcoFalke FYI, the idea is about introducing more fine-grained wallet data structures locks, it's not about removing `cs_main`. We still have hundreds of lock taking of `cs_wallet` (though I don't plan to work on that).

**Comment by MarcoFalke** [comment]
Ok, I guess it is fine to just implement this if there is need, but not need to keep an issue open for it?

**Comment by furszy** [comment]
I started working on decoupling some responsibilities from `cs_wallet` without knowing about this issue. PR #25620 (open discussion there)

**Comment by ariard** [comment]
> Ok, I guess it is fine to just implement this if there is need, but not need to keep an issue open for it?

Yep no need to keep open. Nice we keep awareness as a project wallet refactors are welcome.
