### ISSUE TITLE
Balance is 0 after send transaction in testnet v0.19 and blocksonly flag enabled

### ISSUE THREAD

**Issue by webloft** [bitcoin/bitcoin#17662]
I tried to send 0.00469484 BTC from 0.02 BTC total in testnet3. The daemon reports a txid but this one is not visible in any explorer and the transaction is not processing it at all. Furthermore the balance is set to 0.00000000 (getbalance "*" 0). I can query the transaction via listtransactions. It is a transaction from and to the same wallet. Also maybe related, in regtest mode some invisible fee is reduced from total wallet balance but not logged in any receive-send info. The amount is just missing.

Just send a test transaction

**To reproduce**

**System information**

Bitcoin Core version v0.19.0.1 (release build) -blocksonly=1 -prune=1024

Linux  4.15 (Ubuntu 18.04.1 LTS)

There is nothing special logged:
```
2019-12-03T20:54:13Z [test] CommitTransaction:
CTransaction(hash=896cc84018, ver=2, vin.size=2, vout.size=2, nLockTime=1611085)
    CTxIn(COutPoint(21866e5057, 1), scriptSig=160014a5a09ce3f5f5d78d39, nSequence=4294967294)
    CTxIn(COutPoint(5a847af857, 0), scriptSig=160014a5a09ce3f5f5d78d39, nSequence=4294967294)
    CScriptWitness(304402207f290913ac2c796278b9ae2271f17c39e9039bbbfe6e37e6a3d9b97fd19d7928022004e46bceec87b3195ca0fe1477366ef21c9f9a11ffd7acec039a3dea8cf2839501, 02baab1863533372a82ced2b84009217fd81e83d3325d44e865970f3ffe9c7a162)
    CScriptWitness(304402206ba62fc2a8a37c59e7474f318021fd09c67e6b6b38aaf7ac10ec60125c04555c02204608cd5764f1c38f814b55f8e5629f0a69a2f07ac094505a1249d0524fa3ec0b01, 02baab1863533372a82ced2b84009217fd81e83d3325d44e865970f3ffe9c7a162)
    CTxOut(nValue=0.00469484, scriptPubKey=a914da26d8b5010fb615fe442b678c)
    CTxOut(nValue=0.01530260, scriptPubKey=a914fafbd45c56f6a2a593b115b0fa)

2019-12-03T20:54:13Z [test] AddToWallet 896cc8401843a2f7d0682a43faa180a5b2f722db96039a9d30b2158e3b7e97ea  new
```
```

{
    "address": "2ND8hqCu4r4Raj6paNk3FThSb9SZx8bad57",
    "category": "receive",
    "amount": 0.00469484,
    "label": "",
    "vout": 0,
    "confirmations": 0,
    "trusted": false,
    "txid": "896cc8401843a2f7d0682a43faa180a5b2f722db96039a9d30b2158e3b7e97ea",
    "walletconflicts": [
    ],
    "time": 1575406453,
    "timereceived": 1575406453,
    "bip125-replaceable": "unknown"
  },
  {
    "address": "2ND8hqCu4r4Raj6paNk3FThSb9SZx8bad57",
    "category": "send",
    "amount": -0.00469484,
    "label": "",
    "vout": 0,
    "fee": -0.00000256,
    "confirmations": 0,
    "trusted": false,
    "txid": "896cc8401843a2f7d0682a43faa180a5b2f722db96039a9d30b2158e3b7e97ea",
    "walletconflicts": [
    ],
    "time": 1575406453,
    "timereceived": 1575406453,
    "bip125-replaceable": "unknown",
    "abandoned": false
  }
```

Does maybe the peers do not accept my transaction? All peers have a lower version:
```
    "subver": "/Satoshi:0.18.0/",
    "subver": "/Satoshi:0.18.1/",
    "subver": "/Satoshi:0.16.0/",
    "subver": "/Satoshi:0.15.2/",
    "subver": "/Satoshi:0.17.0/",
    "subver": "/Satoshi:0.17.0/",
    "subver": "/Satoshi:0.18.0/",
    "subver": "/Satoshi:0.13.2/",
    "subver": "/Satoshi:0.14.2/",
```

**Comment by webloft** [comment]
@laanwj if you think that is not a bug that the core wipes my remaining balance and do not send the transaction could you please give me a hint whats going wrong here? thx

**Comment by webloft** [comment]
I have removed the -blocksonly flag and now my transaction is visible to the network (but was not before not even after some hours)

**Comment by laanwj** [comment]
due to miners messing around with it all the time, testnet is unreliable, there's work on "signet" that would provide for more reliable testing by generating blocks more predictably

`-blocksonly` is not a good combination with the wallet, it means transactions will only become visible after they end up in a block
this includes the change part to yourself, which explains why the balance is temporarily 0

**Comment by webloft** [comment]
@laanwj Thank you for your response

For public: I assume the transaction is silently rejected by the testnet because the core is unable to estimate the fee with -blocksonly (and tries to send with fee: 0?). In mainnet you will get an error about that. Conclusion: do not test with -blocksonly enabled in testmode.

**Comment by MarcoFalke** [comment]
`-blocksonly` interacts with `-walletbroadcast`. See also issue https://github.com/bitcoin/bitcoin/issues/17294#issuecomment-547414513
