### ISSUE TITLE
OSX Mojave (10.14.6) build fails compiling univalue

### ISSUE THREAD

**Issue by gr33k** [bitcoin/bitcoin#17664]
Git pull origin - go in to ./src/univalue

./autogen.sh
./configure
make

make clean and two different coins attempted with same results.
OSX 10.14.6 (Mojave)

Please advise if this is incompatibility or if I'm missing something :)

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Full output:
./autogen.sh
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
glibtoolize: copying file 'build-aux/m4/libtool.m4'
glibtoolize: copying file 'build-aux/m4/ltoptions.m4'
glibtoolize: copying file 'build-aux/m4/ltsugar.m4'
glibtoolize: copying file 'build-aux/m4/ltversion.m4'
glibtoolize: copying file 'build-aux/m4/lt~obsolete.m4'

./configure
configure.ac:45: installing 'build-aux/compile'
configure.ac:45: installing 'build-aux/config.guess'
configure.ac:45: installing 'build-aux/config.sub'
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
machecking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
kchecking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
echecking build system type...
x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/local/bin/nm -B
checking the name lister (/usr/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.7.0 file names to x86_64-apple-darwin18.7.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.7.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/local/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pc/libunivalue.pc
config.status: creating pc/libunivalue-uninstalled.pc
config.status: creating univalue-config.h
config.status: executing depfiles commands
config.status: executing libtool commands

make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CXX      test/object-object.o
  CXX      lib/libunivalue_la-univalue.lo
  CXX      lib/libunivalue_la-univalue_get.lo
  CXX      lib/libunivalue_la-univalue_read.lo
  CXX      lib/libunivalue_la-univalue_write.lo
  CXXLD    libunivalue.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    test/object
**ld: warning: ignoring file ./.libs/libunivalue.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:**
  "UniValue::push_backV(std::__1::vector<UniValue, std::__1::allocator<UniValue> > const&)", referenced from:
      univalue_array() in object-object.o
  "UniValue::read(char const*, unsigned long)", referenced from:
      univalue_typecheck() in object-object.o
      univalue_readwrite() in object-object.o
  "UniValue::clear()", referenced from:
      univalue_set() in object-object.o
      univalue_array() in object-object.o
      univalue_object() in object-object.o
  "UniValue::pushKV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, UniValue const&)", referenced from:
      univalue_object() in object-object.o
      UniValue::pushKV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in object-object.o
  "UniValue::setInt(long long)", referenced from:
      univalue_set() in object-object.o
      univalue_object() in object-object.o
      UniValue::UniValue(long long) in object-object.o
      UniValue::UniValue(int) in object-object.o
  "UniValue::setInt(unsigned long long)", referenced from:
      univalue_set() in object-object.o
      UniValue::UniValue(unsigned long long) in object-object.o
  "UniValue::setStr(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      univalue_set() in object-object.o
      univalue_array() in object-object.o
      UniValue::UniValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in object-object.o
      UniValue::UniValue(char const*) in object-object.o
  "UniValue::pushKVs(UniValue const&)", referenced from:
      univalue_object() in object-object.o
  "UniValue::setBool(bool)", referenced from:
      univalue_typecheck() in object-object.o
      univalue_set() in object-object.o
      UniValue::UniValue(bool) in object-object.o
  "UniValue::setNull()", referenced from:
      univalue_set() in object-object.o
  "UniValue::__pushKV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, UniValue const&)", referenced from:
      univalue_object() in object-object.o
  "UniValue::setArray()", referenced from:
      univalue_set() in object-object.o
  "UniValue::setFloat(double)", referenced from:
      univalue_set() in object-object.o
      UniValue::UniValue(double) in object-object.o
  "UniValue::push_back(UniValue const&)", referenced from:
      univalue_array() in object-object.o
      UniValue::push_back(char const*) in object-object.o
  "UniValue::setNumStr(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      univalue_constructor() in object-object.o
      univalue_typecheck() in object-object.o
      univalue_set() in object-object.o
  "UniValue::setObject()", referenced from:
      univalue_set() in object-object.o
      univalue_object() in object-object.o
  "UniValue::checkObject(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, UniValue::VType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, UniValue::VType> > > const&) const", referenced from:
      univalue_object() in object-object.o
  "UniValue::write(unsigned int, unsigned int) const", referenced from:
      univalue_readwrite() in object-object.o
  "UniValue::findKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&) const", referenced from:
      univalue_object() in object-object.o
  "UniValue::getKeys() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_int() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_obj() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_str() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_bool() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_real() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::getObjMap(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, UniValue, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, UniValue> > >&) const", referenced from:
      univalue_object() in object-object.o
  "UniValue::getValues() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_array() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::get_int64() const", referenced from:
      univalue_typecheck() in object-object.o
  "UniValue::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      univalue_object() in object-object.o
      univalue_readwrite() in object-object.o
  "UniValue::operator[](unsigned long) const", referenced from:
      univalue_array() in object-object.o
      univalue_readwrite() in object-object.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test/object] Error 1
make: *** [all] Error 2

**Comment by fanquake** [comment]
> two different coins attempted with same results.

We don't provide support for alt coins or other projects here.

> go in to ./src/univalue

You shouldn't be building univalue directly. It is built/configured as needed when you run Bitcoin Cores `./autogen.sh`, `./configure` and `make`.

**Comment by gr33k** [comment]
I am trying bitcoin here but it's also on an altcoin using univalue (feirm). However - that's interesting...I will build bitcoin fully and see if it errors out there. I am about to give up and just compile it using 10.12 in a VM ;) Only reason I try to compile univalue is to figure out where I get the error at the end when attempting to link the binaries it seems.

**Comment by laanwj** [comment]
Please direct questions about building univalue separately to the [univalue](https://github.com/jgarzik/univalue) upstream repository. The univalue subtree that is part of bitcoin is not supposed to be used like this.
