### ISSUE TITLE
Menu Bar not clickable when running Qt from terminal on MacOS Catalina

### ISSUE THREAD

**Issue by riordant** [bitcoin/bitcoin#17672]
As the title says.
Focus only occurs following a switch to another app and back again.
Related info: 
https://bugreports.qt.io/browse/QTBUG-48829

**Expected behavior**
Clickable menubar without switching out app

**To reproduce**
Compile and run `bitcoin-qt` in terminal.
The issue in constantly reproduced.

**System information**
MacOS Catalina 10.15.1
Bitcoin Core @ commit `5aee0e2163cc02cdf1cd6bec69bfbb513bb302d5`

**Comment by hebasto** [comment]
[QTBUG-48829#comment-295153](https://bugreports.qt.io/browse/QTBUG-48829?focusedCommentId=295153&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-295153):
> Not a bug. That's just how OS X is.

[QTBUG-48829?focusedCommentId=295165&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-295165](https://bugreports.qt.io/browse/QTBUG-48829?focusedCommentId=295165&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-295165):
> Anyway, applications don't fully get focus if they are opened from the terminal. To get full focus, it needs to be a bundle and opened from Finder.

I think this issue could be closed, no?

**Comment by laanwj** [comment]
Agree, if Qt upstream don't regard it as a bug "because it's how MacOS is", there's nothing we can do, either.
