### ISSUE TITLE
Don't display "Third party transaction URLs" setting when built with no wallet

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17683]
The part of the GUI that this setting is relevant for does not exist in a `--disable-wallet` build. 

![wallet_prefs](https://user-images.githubusercontent.com/863730/70331435-72547300-180d-11ea-842d-82f8529ae982.png)

**Comment by brakmic** [comment]
Hi,

Here's my [solution](https://github.com/brakmic/bitcoin/commit/29b22db3c7b71c818f71d78d6e36b014f747d655).

It's basically a series of C-style #ifdef / #endif's 

Have also deactivated the context menu stuff. Yes, I know,  there is no context menu at all, but just to be completely without any 3rd party Urls. 

Regards,

**Comment by brakmic** [comment]
As the previous variant of my solution was failing on some architectures/configurations, I have now simplified it a lot. There's now only one #ifdef/endif left that disables the label/textbox for non-wallet builds.
