### ISSUE TITLE
`avoid_reuse` support for non-`sendtoaddress` calls

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#17706]
`sendmany`, `bumpfee` and others should ideally contain something like this block:

```
    coin_control.m_avoid_address_reuse = GetAvoidReuseFlag(pwallet, request.params[8]);
    // We also enable partial spend avoidance if reuse avoidance is set.
    coin_control.m_avoid_partial_spends |= coin_control.m_avoid_address_reuse;
```
to avoid leakage

**Comment by instagibbs** [comment]
hmm this also has to be done for `*fund* RPCs.

beginning to think we should solve this more systematically than #17712 
cc @promag

**Comment by achow101** [comment]
Anything that uses `AvailableCoins` will already do this: https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L2037

**Comment by instagibbs** [comment]
huh, I guess `sendtoaddress` case is just indirection. Fairly confident we have coverage, just hard to read code.
