### ISSUE TITLE
Proposed PSBT sign/broadcast flow 

### ISSUE THREAD

**Issue by gwillen** [bitcoin/bitcoin#17717]
This is a followup to @sjors' PR #17509 . My goal is to propose a very simple initial dialog for the "Load PSBT..." menu item, to go one step beyond just "broadcast or nothing" as the functionality.

See attached -- the idea is to display a summary of what we know about the transaction and the workflow, and then offer relevant options based on that.

Thoughts? I want to keep this absolutely as simple as possible this time around (since last time my biggest mistake was trying to do too much at once, I think.)

![IMG_20191210_142555](https://user-images.githubusercontent.com/458997/70574744-ab684c80-1b59-11ea-8ebb-8285f23aedbc.jpg)

**Comment by achow101** [comment]
I suppose there should be a button for updating, or maybe update the transaction automatically?

**Comment by sipa** [comment]
I like the paper-like style of the interface.

**Comment by gwillen** [comment]
@achow101 my feeling is that the concept of updating is (1) not going to be obvious to most people what it's for, and (2) very rarely going to be needed as an explicit step in simple cases, because the Core instance generating the transaction will be online. So my feeling is that anytime you generate or load a PSBT in the GUI, we update it automatically before doing anything else.

Then if you _really_ need an explicit update on some node, you can accomplish it in the GUI with load -> do nothing -> save.

**Comment by instagibbs** [comment]
> So my feeling is that anytime you generate or load a PSBT in the GUI, we update it automatically before doing anything else.

Agreed. Perhaps there can be an update message of some kind when loaded if the data is updated.

**Comment by Sjors** [comment]
I would replace "Advanced..." with Save and Copy.

**Comment by Rspigler** [comment]
Can this be closed now with https://github.com/bitcoin/bitcoin/pull/18027 ?

**Comment by adamjonas** [comment]
Agree with rspigler that this can be closed now with #18027 merged.
