### ISSUE TITLE
gui: setting to make us default URI handler 

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#17734]
Bitcoin Core makes itself the default handler for BIP21 style `bitcoin:...` URIs. Other wallets also do this, so the default wallet often depends on whatever the user installed most recently.

In macOS the only way to change this setting is to [edit a plist file](https://superuser.com/a/548122) (to `org.bitcoin.BitcoinPayment`, requires reboot) or run some freeware program to do it. I don't know the situation on other operating systems.

We should add a button to the settings screen to make Bitcoin Core the default URI handler.

**Comment by laanwj** [comment]
Concept ACK, though this is going to bring in a lot of platform-specific code.

FYI I think this is what sets the handler on Windows (part of the installer https://github.com/bitcoin/bitcoin/blob/master/share/setup.nsi.in ):
```
    WriteRegStr HKCR "@PACKAGE_TARNAME@" "URL Protocol" ""
    WriteRegStr HKCR "@PACKAGE_TARNAME@" "" "URL:Bitcoin"
    WriteRegStr HKCR "@PACKAGE_TARNAME@\DefaultIcon" "" $INSTDIR\@BITCOIN_GUI_NAME@@EXEEXT@
    WriteRegStr HKCR "@PACKAGE_TARNAME@\shell\open\command" "" '"$INSTDIR\@BITCOIN_GUI_NAME@@EXEEXT@" "%1"'
```
I'm pretty sure it's possible to do this in the application instead, as many windows programs (at least historically) did this.

For Linux I don't think registering a protocol handler as a user/application is possible in general. If done at all, it's usually part of distribution packaging.

**Comment by fanquake** [comment]
I've moved this to the GUI repo: https://github.com/bitcoin-core/gui/issues/51.
