### ISSUE TITLE
Extract ECDSA parameters from Bitcoin Blockchain Block

### ISSUE THREAD

**Issue by tiagomendes7** [bitcoin/bitcoin#17745]
How do i extract ECDSA parameters from Bitcoin Block using Bitcoin Core ?

**Comment by tiagomendes7** [comment]
Extract ECDSA parameters from Bitcoin Blockchain Block

Hey could you help me with this ?

Obrigado,
os meus cumprimentos

Tiago Mendes
tiagovazmendes7@gmail.com

**Comment by laanwj** [comment]
This is an exact duplicate of #17496

This is not a help forum. Please use the bitcoin stack exchange (https://bitcoin.stackexchange.com/) for questions.
