### ISSUE TITLE
bitcoind won't send bitcoins from wallet

### ISSUE THREAD

**Issue by riksanches** [bitcoin/bitcoin#17755]
I'm using library for PHP https://github.com/aceat64/EasyBitcoin-PHP

I'm trying to unlock wallet using 

`<?php

require 'func/ezbtc.php';

$bitcoin = new Bitcoin('admin','admin', 'localhost', '7788');

$bitcoin->walletpassphrase('PASSWORD', '120');

?>`

Instead of PASSWORD there is real password for wallet.

But when I try to send some bitcoins to another wallet it just not working.
No errors, nothing.

What's wrong?

**Comment by fanquake** [comment]
You should open an issue on the https://github.com/aceat64/EasyBitcoin-PHP repository, not here.
