### ISSUE TITLE
ci: Combine 32 bit build with centos build

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17757]
There are a lot of ci builds run on travis for a single commit and some seem overlapping. I think we can turn the centos build into a 32-bit linux build and remove the 32-bit build to avoid travis bottlenecks.

Useful skills:

CentOS package manager, gcc cross-compilation

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

Want to work on this issue?

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by laanwj** [comment]
Concept ACK.

The ARM build is also 32 bit isn't it?

**Comment by MarcoFalke** [comment]
> The ARM build is also 32 bit isn't it?

Jup, but I think as long as we ship the i686 gitian package, it wouldn't hurt to also have one i686 cross compile

**Comment by theStack** [comment]
Should this be a depends or no-depends build? As discussed in https://github.com/bitcoin/bitcoin/pull/17900, neither/nor seems to be optimal: a depends build is against one of the major initial goals of the CentOS build (https://github.com/bitcoin/bitcoin/pull/17900#issuecomment-572666614, https://github.com/bitcoin/bitcoin/issues/17628#issuecomment-559448201), whereas a no-depends build is hardly possible considering that we would need all libraries already available in the desired target architecture, namely i686 (https://github.com/bitcoin/bitcoin/pull/17900#issuecomment-572697411).
