### ISSUE TITLE
ci/tests: Bump timeouts so all functional tests run on travis in valgrind

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17763]
The newly added valgrind ci run is also run on travis. However, due to the slowdown of valgrind, some tests time out. Fixing this issue might take some time, but it should be rather easy. First, remove this line:

https://github.com/bitcoin/bitcoin/blob/890eac8f8286496bbae664792cd2a1e56991c669/ci/test/00_setup_env_native_valgrind.sh#L12

Then, see which tests time out and bump their timeouts. Repeat.

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

Useful skills:

Basic skills (Bash, Python, docker, virtual machines, valgrind)

Want to work on this issue?

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
Example diff:

```diff
diff --git a/test/functional/wallet_dump.py b/test/functional/wallet_dump.py
index 53edf710b..8bd375fc3 100755
--- a/test/functional/wallet_dump.py
+++ b/test/functional/wallet_dump.py
@@ -137,7 +137,7 @@ class WalletDumpTest(BitcoinTestFramework):
 
         # encrypt wallet, restart, unlock and dump
         self.nodes[0].encryptwallet('test')
-        self.nodes[0].walletpassphrase('test', 10)
+        self.nodes[0].walletpassphrase('test', 60)
         # Should be a no-op:
         self.nodes[0].keypoolrefill()
         self.nodes[0].dumpwallet(wallet_enc_dump)

**Comment by michiboo** [comment]
Hi I am planning working on this!
