### ISSUE TITLE
Shared services

### ISSUE THREAD

**Issue by albypaul** [bitcoin/bitcoin#17778]
**Is your feature request related to a problem? Please describe.**
Will it run on a shared service?.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
