### ISSUE TITLE
Coordinating anti virus false positive reporting

### ISSUE THREAD

**Issue by MaxHillebrand** [bitcoin/bitcoin#17779]
**Current Problem**

As reported several times [#4069 #11852 #12320 #12777 #15156], Bitcoin Core binaries [including v0.19 [Win .exe](https://www.virustotal.com/gui/file/4abca9419e83581209a3654a33da504998cf2f470993ee6d71f6b47fefe631a0/detection), [Linux .tar.gz](https://www.virustotal.com/gui/file/732cc96ae2e5e25603edf76b8c8af976fe518dd925f7e674710c6c8ee5189204/detection), [OSX .dmg](https://www.virustotal.com/gui/file/1a8865ac84de9710633ad89b3f6b7c08281a0298d47e8ce7d4f5bb52f765f06e/detection)] are flagged as potentially unwanted program by several anti virus programs. This is confusing for users, and might deter them from running a full node.

There have already been several attempts [#6613 #6650 #16721] to obfuscate database so to not get flagged, but this has so far not solved the problem entirely. 

As I read in the above mentioned issues, this might [not really be of concern to this repository](https://github.com/bitcoin/bitcoin/issues/12320#issuecomment-370557246), so my issue might be misplaced, if that is the case please close it.

**Proposed Solution**
I am unsure about the best approach to solving this issue, thus I open this issue to discuss and coordinate. My idea is to contact the companies and developers of these anti virus programs and reporting the false positive flag, with the request to fix the wrong analysis for these binaries. This seems to be [the proper way of requesting a whitelist](https://support.avast.com/en-ww/article/229/).

If this is the proper way of doing so, I have curated online forms and email addresses where such a false positive can be reported. [I will edit this issue when I find further sources.]

** Online Forms **
[Antity](http://submit@antiy.com/), [Avast](https://www.avast.com/false-positive-file-form.php), [Avira](https://www.avira.com/en/analysis/submit), [AVG](https://www.avg.com/en-us/false-positive-file-form), [BitDefender](https://www.bitdefender.com/submit/), [Gdata](https://su.gdatasoftware.com/en/sample-submission), [eScan](http://support.mwti.net/support/index.php), [Fortinet](https://fortiguard.com/faq/onlinescanner), [F-Secure](https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample), [Kaspersky](https://virusdesk.kaspersky.com/), [e-Gambit](https://tehtris.com/en/fp-egambit/), [K7 Computing](https://www.k7computing.com/us/contact-us), [TrendMicro](https://www.trendmicro.com/en_us/about/legal/detection-reevaluation.html)

** Emails ** 
removespam@fortinet.com, support@cyren.com, virus@arcabit.com, virus@avira.com, virus_submission@bitdefender.com, info@cyren.com, samples@eset.com, samples@ikarus.at, fp@escanav.com, info@fireeye.com, submitvirus@fortinet.com, support@jiangmin.com, reportfp@k7computing.com, info@maxpcsecure.com

Here is a possible text as template for the report, it's important that the email subject line starts with the word `FALSE`.

```
To: mailof@antivirusvendor.here
Subject: FALSE: files being detected by {AntivirusVendorHere} - False Positive Report

Body: Dear [antivirus vendor],
I write this email to report as a false positives two different software.

Unfortunately, your antivirus reports two open source and safe Bitcoin software as malware; more specifically, they are categorized as "Bitcoin Miner". This claim is extremely incorrect.
The two software are, respectively, "Bitcoin Core" and "Wasabi Wallet".

Bitcoin Core, despite being one of the most (if not the most) highly scrutinized and maintained open-source software in existence, it is categorized as "Bitcoin Miner".
Bitcoin Core is considered to be Bitcoin's reference implementation, serves as a Bitcoin node and provides a Bitcoin wallet which fully verifies payments.
It is not possible to mine with this software, since the mining code was removed in 2013.

Wasabi Wallet is a open-source and non-custodial, Bitcoin wallet that integrates Bitcoin Core within it to validate transactions without having to connect to third party servers on the network, and for this reason, it is also reported as "Bitcoin Miner", when its only task is to allow users to manage bitcoins in a secure and user friendly way.
Again, Wasabi Wallet cannot in any way mine bitcoins (or any other cryptocurrency), as its sole purpose is to manage bitcoins.

(optional from here, edit according to your antivirus - The more information there is, the better)
Additional information:
Product - McAfee Security Center
Version - v16.0
Engine - 3181.0
Type of alert - ELF:BitCoinMiner-ET [PUP]

You can find the two files attached.
Looking forward to your kind reply, I wish you a good job.

Regards,
Name and Surname
```

**Additional context**
I bring this up now because with [Wasabi Wallet v1.1.10](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v1.1.10), the [included bitcoind and hwi binaries](https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi/Microservices/Binaries) are part of the reason why [Wasabi is now also flagged](https://github.com/zkSNACKs/WalletWasabi/pull/2858) as a potentially unwanted program.

**Comment by RiccardoMasutti** [comment]
The average user doesn't know what is the difference between a PUP (Potential Unwanted Program) and a malware, so I agree with that.

**Comment by fanquake** [comment]
Going to close this for now. I'm not sure there is anything more for this repository to coordinate, or that it should be happening in this issue tracker.

**Comment by RiccardoMasutti** [comment]
> Going to close this for now. I'm not sure there is anything more for this repository to coordinate, or that it should be happening in this issue tracker.

This might interest people wo will read this issue: https://bitcoinissafe.com/
