### ISSUE TITLE
TypeError: method.toLowerCase is not a function /bitcoin-core/dist/src/requester.js:35:21

### ISSUE THREAD

**Issue by cosmoarunn** [bitcoin/bitcoin#17782]
TypeError: method.toLowerCase is not a function
    at Requester.prepare (/home/googiWallet/wallet/node_modules/bitcoin-core/dist/src/requester.js:35:21)
    at Client.command (/home/googiWallet/wallet/node_modules/bitcoin-core/dist/src/index.js:163:29)
**Expected behavior**
-  method.toLowerCase() returning lowercase of method issued (tried with method name 'EstimateSmartFee' 

**Actual behavior**
Throwing a TypeError 

**To reproduce**
```
getSmartFee(conf,mode) { 
        var results;
        mode = "undefined" == typeof mode ? 'ECONOMICAL': mode;

        return client.command({ method: 'EstimateSmartFee', parameters: [conf, mode] }).then((results) => (results) ).catch((e) => (console.log(e)));

        setTimeout(function(){
            return results;
        }, 100);
    }
```

**System information**

**Comment by fanquake** [comment]
This looks like an issue with your Javascript, not Bitcoin Core.
