### ISSUE TITLE
ci: GitHub Actions update to Visual Studio 16.4.0

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17788]
On [2019-12-09](https://github.blog/changelog/2019-12-19-github-actions-updates-to-the-virtual-environments/) GitHub Actions virtual environments has been upgraded to Visual Studio 16.4.0.

This causes errors:
```
     6>LINK : fatal error C1047: The object or library file 'C:\vcpkg\installed\x64-windows-static\lib\libzmq-mt-s-4_3_3.lib' was created with an older compiler than other objects; rebuild old objects and libraries [D:\a\bitcoin\bitcoin\build_msvc\bitcoind\bitcoind.vcxproj]
     6>LINK : fatal error LNK1257: code generation failed [D:\a\bitcoin\bitcoin\build_msvc\bitcoind\bitcoind.vcxproj]
```

Updating Qt binaries (#17736) and removing `zeromq` package from `build_msvc/vcpkg-packages.txt` did not help.

**Comment by hebasto** [comment]
ping @sipsorcery

**Comment by Kaylee-Cole** [comment]
message me to know to make money off bitcoin
