### ISSUE TITLE
wrong privatekey given

### ISSUE THREAD

**Issue by jmburch921** [bitcoin/bitcoin#17818]
I am still running a full node (several weeks 31%)  I am trying to recover btc that was sent to my receive address.  when i importprivkey, i was given a new address as a result when i tried to import the address into another wallet.  original address now non spendable.  All i have is publickey. 
**Expected behavior**

to receive privatekey
**Actual behavior**
another address 

**To reproduce**

**System information**

just downloaded newest

windows / toshiba 

windows 10

**Comment by fanquake** [comment]
This issue tracker is for technical issues related only to Bitcoin Core, and should not be used for general questions / support. You might want to try the [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) instead.

**Comment by jmburch921** [comment]
How is this not a technical issue?  I cannot believe I have to become a coder now to get my bitcoins
