### ISSUE TITLE
build, qt: Possible unset bitcoin_cv_qt58 variable

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17821]
The `bitcoin_cv_qt58` variable is used in `_BITCOIN_QT_FIND_LIBS_WITHOUT_PKGCONFIG` and `_BITCOIN_QT_FIND_STATIC_PLUGINS` macros.

But it is set by `_BITCOIN_QT_CHECK_QT58` macro only if `else` branch is executed:
https://github.com/bitcoin/bitcoin/blob/b931f61b9ab098ea4ea8fbe4cbf0b03c566c3f63/build-aux/m4/bitcoin_qt.m4#L96-L100

**Comment by fanquake** [comment]
I think a PR with a fix/for discussion would be a better approach than having an issue open for this. Going to close for now.
