### ISSUE TITLE
State of the Repo Report, December 2019

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#17832]
# State of the Repo Report, December 2019

## Introduction

For all fans of statistics – enjoy! 🤓

849 authors (+6) have contributed to the project (merged contributions). Thank you! ❤️

The repo contains 517&nbsp;604 (+1&nbsp;851) lines of text and 1&nbsp;851 (+14) files.

22&nbsp;515 (+247) commits have been made of which 4&nbsp;599 (+87) are merge commits.

There are currently 343 (+19) open pull requests from in total 94 (+6) contributors.

If all open pull requests were merged the project line count would grow by roughly 35 percent.

The total set of open pull requests adds 212&nbsp;858&nbsp;lines, removes 31&nbsp;388&nbsp;lines and touches 3&nbsp;841&nbsp;distinct files.

The "median open pull request" adds 5&nbsp;lines, removes 19&nbsp;lines and touches 4&nbsp;files.

Previous edition: [State of the Repo, November 2019](https://github.com/bitcoin/bitcoin/issues/17632)

## Suggested code changes waiting for review (grouped by author)

| # | Username | Lines added | Lines removed | Net lines | Files chgd | Pull reqs |
| ---:| --- | ---:| ---:| ---:| ---:| ---:|
| 1 | [TheBlueMatt](https://github.com/bitcoin/bitcoin/pulls/TheBlueMatt) | 132&nbsp;097&nbsp;(62%) | -1&nbsp;526 | 130&nbsp;571 | 756 | 9&nbsp;(3%) |
| 2 | [Sjors](https://github.com/bitcoin/bitcoin/pulls/Sjors) | 14&nbsp;795&nbsp;(7%) | -2&nbsp;222 | 12&nbsp;573 | 136 | 19&nbsp;(6%) |
| 3 | [laanwj](https://github.com/bitcoin/bitcoin/pulls/laanwj) | 11&nbsp;653&nbsp;(5%) | -8&nbsp;318 | 3&nbsp;335 | 230 | 4&nbsp;(1%) |
| 4 | [ryanofsky](https://github.com/bitcoin/bitcoin/pulls/ryanofsky) | 7&nbsp;781&nbsp;(4%) | -1&nbsp;852 | 5&nbsp;929 | 164 | 17&nbsp;(5%) |
| 5 | [achow101](https://github.com/bitcoin/bitcoin/pulls/achow101) | 5&nbsp;370&nbsp;(3%) | -1&nbsp;798 | 3&nbsp;572 | 90 | 14&nbsp;(4%) |
| 6 | [MarcoFalke](https://github.com/bitcoin/bitcoin/pulls/MarcoFalke) | 3&nbsp;837&nbsp;(2%) | -2&nbsp;820 | 1&nbsp;017 | 400 | 13&nbsp;(4%) |
| 7 | [jonasschnelli](https://github.com/bitcoin/bitcoin/pulls/jonasschnelli) | 3&nbsp;515&nbsp;(2%) | -455 | 3&nbsp;060 | 38 | 9&nbsp;(3%) |
| 8 | [jamesob](https://github.com/bitcoin/bitcoin/pulls/jamesob) | 3&nbsp;285&nbsp;(2%) | -652 | 2&nbsp;633 | 32 | 5&nbsp;(1%) |
| 9 | [sipa](https://github.com/bitcoin/bitcoin/pulls/sipa) | 2&nbsp;841&nbsp;(1%) | -961 | 1&nbsp;880 | 49 | 4&nbsp;(1%) |
| 10 | [kallewoof](https://github.com/bitcoin/bitcoin/pulls/kallewoof) | 2&nbsp;454&nbsp;(1%) | -357 | 2&nbsp;097 | 67 | 6&nbsp;(2%) |
| 11 | [luke-jr](https://github.com/bitcoin/bitcoin/pulls/luke-jr) | 2&nbsp;034&nbsp;(1%) | -497 | 1&nbsp;537 | 97 | 21&nbsp;(6%) |
| 12 | [icota](https://github.com/bitcoin/bitcoin/pulls/icota) | 1&nbsp;705&nbsp;(1%) | -50 | 1&nbsp;655 | 25 | 3&nbsp;(1%) |
| 13 | [jl2012](https://github.com/bitcoin/bitcoin/pulls/jl2012) | 1&nbsp;620&nbsp;(1%) | -1&nbsp;537 | 83 | 9 | 2&nbsp;(1%) |
| 14 | [hebasto](https://github.com/bitcoin/bitcoin/pulls/hebasto) | 1&nbsp;458&nbsp;(1%) | -966 | 492 | 128 | 21&nbsp;(6%) |
| 15 | [dongcarl](https://github.com/bitcoin/bitcoin/pulls/dongcarl) | 1&nbsp;092&nbsp;(1%) | -652 | 440 | 31 | 5&nbsp;(1%) |
| 16 | [jonatack](https://github.com/bitcoin/bitcoin/pulls/jonatack) | 1&nbsp;004&nbsp;(0%) | -326 | 678 | 33 | 6&nbsp;(2%) |
| 17 | [Christewart](https://github.com/bitcoin/bitcoin/pulls/Christewart) | 991&nbsp;(0%) | -24 | 967 | 18 | 1&nbsp;(0%) |
| 18 | [promag](https://github.com/bitcoin/bitcoin/pulls/promag) | 838&nbsp;(0%) | -358 | 480 | 54 | 19&nbsp;(6%) |
| 19 | [jimpo](https://github.com/bitcoin/bitcoin/pulls/jimpo) | 813&nbsp;(0%) | -24 | 789 | 13 | 1&nbsp;(0%) |
| 20 | [marcinja](https://github.com/bitcoin/bitcoin/pulls/marcinja) | 808&nbsp;(0%) | -56 | 752 | 18 | 2&nbsp;(1%) |
| 21 | [LarryRuane](https://github.com/bitcoin/bitcoin/pulls/LarryRuane) | 768&nbsp;(0%) | -278 | 490 | 24 | 4&nbsp;(1%) |
| 22 | [jnewbery](https://github.com/bitcoin/bitcoin/pulls/jnewbery) | 701&nbsp;(0%) | -771 | -70 | 33 | 8&nbsp;(2%) |
| 23 | [Empact](https://github.com/bitcoin/bitcoin/pulls/Empact) | 675&nbsp;(0%) | -379 | 296 | 68 | 13&nbsp;(4%) |
| 24 | [amitiuttarwar](https://github.com/bitcoin/bitcoin/pulls/amitiuttarwar) | 667&nbsp;(0%) | -102 | 565 | 16 | 1&nbsp;(0%) |
| 25 | [ariard](https://github.com/bitcoin/bitcoin/pulls/ariard) | 645&nbsp;(0%) | -613 | 32 | 21 | 5&nbsp;(1%) |
| 26 | [ajtowns](https://github.com/bitcoin/bitcoin/pulls/ajtowns) | 637&nbsp;(0%) | -226 | 411 | 29 | 6&nbsp;(2%) |
| 27 | [naumenkogs](https://github.com/bitcoin/bitcoin/pulls/naumenkogs) | 632&nbsp;(0%) | -109 | 523 | 15 | 2&nbsp;(1%) |
| 28 | [darosior](https://github.com/bitcoin/bitcoin/pulls/darosior) | 579&nbsp;(0%) | -320 | 259 | 44 | 2&nbsp;(1%) |
| 29 | [practicalswift](https://github.com/bitcoin/bitcoin/pulls/practicalswift) | 563&nbsp;(0%) | -369 | 194 | 30 | 8&nbsp;(2%) |
| 30 | [meshcollider](https://github.com/bitcoin/bitcoin/pulls/meshcollider) | 559&nbsp;(0%) | -93 | 466 | 18 | 3&nbsp;(1%) |
| 31 | [JeremyRubin](https://github.com/bitcoin/bitcoin/pulls/JeremyRubin) | 539&nbsp;(0%) | -299 | 240 | 16 | 3&nbsp;(1%) |
| 32 | [sdaftuar](https://github.com/bitcoin/bitcoin/pulls/sdaftuar) | 528&nbsp;(0%) | -104 | 424 | 11 | 2&nbsp;(1%) |
| 33 | [andrewtoth](https://github.com/bitcoin/bitcoin/pulls/andrewtoth) | 508&nbsp;(0%) | -178 | 330 | 10 | 4&nbsp;(1%) |
| 34 | [fingera](https://github.com/bitcoin/bitcoin/pulls/fingera) | 478&nbsp;(0%) | -9 | 469 | 4 | 1&nbsp;(0%) |
| 35 | [vasild](https://github.com/bitcoin/bitcoin/pulls/vasild) | 345&nbsp;(0%) | -110 | 235 | 10 | 2&nbsp;(1%) |
| 36 | [jtimon](https://github.com/bitcoin/bitcoin/pulls/jtimon) | 318&nbsp;(0%) | -235 | 83 | 33 | 6&nbsp;(2%) |
| 37 | [brakmic](https://github.com/bitcoin/bitcoin/pulls/brakmic) | 287&nbsp;(0%) | -26 | 261 | 10 | 4&nbsp;(1%) |
| 38 | [jkczyz](https://github.com/bitcoin/bitcoin/pulls/jkczyz) | 285&nbsp;(0%) | -346 | -61 | 28 | 4&nbsp;(1%) |
| 39 | [domob1812](https://github.com/bitcoin/bitcoin/pulls/domob1812) | 269&nbsp;(0%) | -120 | 149 | 12 | 2&nbsp;(1%) |
| 40 | [instagibbs](https://github.com/bitcoin/bitcoin/pulls/instagibbs) | 269&nbsp;(0%) | -89 | 180 | 35 | 7&nbsp;(2%) |
| 41 | [hosseinamin](https://github.com/bitcoin/bitcoin/pulls/hosseinamin) | 261&nbsp;(0%) | -43 | 218 | 3 | 1&nbsp;(0%) |
| 42 | [fanquake](https://github.com/bitcoin/bitcoin/pulls/fanquake) | 203&nbsp;(0%) | -200 | 3 | 18 | 7&nbsp;(2%) |
| 43 | [martinus](https://github.com/bitcoin/bitcoin/pulls/martinus) | 199&nbsp;(0%) | -71 | 128 | 10 | 1&nbsp;(0%) |
| 44 | [benthecarman](https://github.com/bitcoin/bitcoin/pulls/benthecarman) | 173&nbsp;(0%) | -13 | 160 | 10 | 3&nbsp;(1%) |
| 45 | [emilengler](https://github.com/bitcoin/bitcoin/pulls/emilengler) | 166&nbsp;(0%) | -13 | 153 | 9 | 5&nbsp;(1%) |
| 46 | [mzumsande](https://github.com/bitcoin/bitcoin/pulls/mzumsande) | 136&nbsp;(0%) | -2 | 134 | 2 | 1&nbsp;(0%) |
| 47 | [FelixWeis](https://github.com/bitcoin/bitcoin/pulls/FelixWeis) | 135&nbsp;(0%) | -101 | 34 | 4 | 1&nbsp;(0%) |
| 48 | [AkioNak](https://github.com/bitcoin/bitcoin/pulls/AkioNak) | 133&nbsp;(0%) | -89 | 44 | 4 | 1&nbsp;(0%) |
| 49 | [ch4ot1c](https://github.com/bitcoin/bitcoin/pulls/ch4ot1c) | 120&nbsp;(0%) | -152 | -32 | 4 | 2&nbsp;(1%) |
| 50 | [metalicjames](https://github.com/bitcoin/bitcoin/pulls/metalicjames) | 98&nbsp;(0%) | -4 | 94 | 4 | 1&nbsp;(0%) |
| 51 | [theStack](https://github.com/bitcoin/bitcoin/pulls/theStack) | 96&nbsp;(0%) | -26 | 70 | 6 | 6&nbsp;(2%) |
| 52 | [n2yen](https://github.com/bitcoin/bitcoin/pulls/n2yen) | 86&nbsp;(0%) | -9 | 77 | 5 | 1&nbsp;(0%) |
| 53 | [RandyMcMillan](https://github.com/bitcoin/bitcoin/pulls/RandyMcMillan) | 80&nbsp;(0%) | -46 | 34 | 5 | 1&nbsp;(0%) |
| 54 | [IntegralTeam](https://github.com/bitcoin/bitcoin/pulls/IntegralTeam) | 79&nbsp;(0%) | -3 | 76 | 3 | 1&nbsp;(0%) |
| 55 | [mmachicao](https://github.com/bitcoin/bitcoin/pulls/mmachicao) | 51&nbsp;(0%) | -49 | 2 | 6 | 1&nbsp;(0%) |
| 56 | [IPGlider](https://github.com/bitcoin/bitcoin/pulls/IPGlider) | 40&nbsp;(0%) | -15 | 25 | 15 | 1&nbsp;(0%) |
| 57 | [shannon1916](https://github.com/bitcoin/bitcoin/pulls/shannon1916) | 39&nbsp;(0%) | -9 | 30 | 4 | 1&nbsp;(0%) |
| 58 | [davereikher](https://github.com/bitcoin/bitcoin/pulls/davereikher) | 37&nbsp;(0%) | -6 | 31 | 2 | 1&nbsp;(0%) |
| 59 | [ahook](https://github.com/bitcoin/bitcoin/pulls/ahook) | 36&nbsp;(0%) | -68 | -32 | 16 | 3&nbsp;(1%) |
| 60 | [Bushstar](https://github.com/bitcoin/bitcoin/pulls/Bushstar) | 32&nbsp;(0%) | -45 | -13 | 6 | 2&nbsp;(1%) |
| 61 | [fjahr](https://github.com/bitcoin/bitcoin/pulls/fjahr) | 32&nbsp;(0%) | -3 | 29 | 2 | 1&nbsp;(0%) |
| 62 | [adamjonas](https://github.com/bitcoin/bitcoin/pulls/adamjonas) | 31&nbsp;(0%) | -14 | 17 | 5 | 1&nbsp;(0%) |
| 63 | [btcdrak](https://github.com/bitcoin/bitcoin/pulls/btcdrak) | 30&nbsp;(0%) | -25 | 5 | 4 | 1&nbsp;(0%) |
| 64 | [Rjected](https://github.com/bitcoin/bitcoin/pulls/Rjected) | 28&nbsp;(0%) | -2 | 26 | 1 | 1&nbsp;(0%) |
| 65 | [carnhofdaki](https://github.com/bitcoin/bitcoin/pulls/carnhofdaki) | 25&nbsp;(0%) | -1 | 24 | 1 | 1&nbsp;(0%) |
| 66 | [lucayepa](https://github.com/bitcoin/bitcoin/pulls/lucayepa) | 24&nbsp;(0%) | -13 | 11 | 1 | 1&nbsp;(0%) |
| 67 | [michiboo](https://github.com/bitcoin/bitcoin/pulls/michiboo) | 22&nbsp;(0%) | -16 | 6 | 7 | 1&nbsp;(0%) |
| 68 | [mruddy](https://github.com/bitcoin/bitcoin/pulls/mruddy) | 22&nbsp;(0%) | -2 | 20 | 2 | 1&nbsp;(0%) |
| 69 | [sanjaykdragon](https://github.com/bitcoin/bitcoin/pulls/sanjaykdragon) | 19&nbsp;(0%) | -9 | 10 | 2 | 1&nbsp;(0%) |
| 70 | [shargon](https://github.com/bitcoin/bitcoin/pulls/shargon) | 16&nbsp;(0%) | -1 | 15 | 1 | 1&nbsp;(0%) |
| 71 | [sipsorcery](https://github.com/bitcoin/bitcoin/pulls/sipsorcery) | 16&nbsp;(0%) | -11 | 5 | 2 | 1&nbsp;(0%) |
| 72 | [tryphe](https://github.com/bitcoin/bitcoin/pulls/tryphe) | 15&nbsp;(0%) | -16 | -1 | 2 | 1&nbsp;(0%) |
| 73 | [lucash-dev](https://github.com/bitcoin/bitcoin/pulls/lucash-dev) | 14&nbsp;(0%) | -5 | 9 | 2 | 1&nbsp;(0%) |
| 74 | [candrews](https://github.com/bitcoin/bitcoin/pulls/candrews) | 13&nbsp;(0%) | -7 | 6 | 1 | 1&nbsp;(0%) |
| 75 | [za-kk](https://github.com/bitcoin/bitcoin/pulls/za-kk) | 13&nbsp;(0%) | -3 | 10 | 3 | 1&nbsp;(0%) |
| 76 | [KaanKC](https://github.com/bitcoin/bitcoin/pulls/KaanKC) | 11&nbsp;(0%) | -1 | 10 | 1 | 1&nbsp;(0%) |
| 77 | [Xekyo](https://github.com/bitcoin/bitcoin/pulls/Xekyo) | 11&nbsp;(0%) | -7 | 4 | 4 | 1&nbsp;(0%) |
| 78 | [jbampton](https://github.com/bitcoin/bitcoin/pulls/jbampton) | 11&nbsp;(0%) | -8 | 3 | 2 | 1&nbsp;(0%) |
| 79 | [sanket1729](https://github.com/bitcoin/bitcoin/pulls/sanket1729) | 11&nbsp;(0%) | -3 | 8 | 1 | 1&nbsp;(0%) |
| 80 | [jameshilliard](https://github.com/bitcoin/bitcoin/pulls/jameshilliard) | 8&nbsp;(0%) | -3 | 5 | 3 | 1&nbsp;(0%) |
| 81 | [HAOYUatHZ](https://github.com/bitcoin/bitcoin/pulls/HAOYUatHZ) | 7&nbsp;(0%) | -8 | -1 | 1 | 1&nbsp;(0%) |
| 82 | [pstratem](https://github.com/bitcoin/bitcoin/pulls/pstratem) | 6&nbsp;(0%) | -5 | 1 | 1 | 1&nbsp;(0%) |
| 83 | [gr0kchain](https://github.com/bitcoin/bitcoin/pulls/gr0kchain) | 5&nbsp;(0%) | -1 | 4 | 1 | 1&nbsp;(0%) |
| 84 | [asoltys](https://github.com/bitcoin/bitcoin/pulls/asoltys) | 4&nbsp;(0%) | -3 | 1 | 1 | 1&nbsp;(0%) |
| 85 | [d3spwn](https://github.com/bitcoin/bitcoin/pulls/d3spwn) | 4&nbsp;(0%) | -2 | 2 | 2 | 1&nbsp;(0%) |
| 86 | [Zero-1729](https://github.com/bitcoin/bitcoin/pulls/Zero-1729) | 3&nbsp;(0%) | -6 | -3 | 2 | 1&nbsp;(0%) |
| 87 | [birtony](https://github.com/bitcoin/bitcoin/pulls/birtony) | 3&nbsp;(0%) | -3 | 0 | 2 | 1&nbsp;(0%) |
| 88 | [elichai](https://github.com/bitcoin/bitcoin/pulls/elichai) | 3&nbsp;(0%) | -1 | 2 | 1 | 1&nbsp;(0%) |
| 89 | [qubenix](https://github.com/bitcoin/bitcoin/pulls/qubenix) | 3&nbsp;(0%) | -4 | -1 | 1 | 1&nbsp;(0%) |
| 90 | [mxaddict](https://github.com/bitcoin/bitcoin/pulls/mxaddict) | 2&nbsp;(0%) | -2 | 0 | 1 | 1&nbsp;(0%) |
| 91 | [HashUnlimited](https://github.com/bitcoin/bitcoin/pulls/HashUnlimited) | 1&nbsp;(0%) | -2 | -1 | 1 | 1&nbsp;(0%) |
| 92 | [ernestognw](https://github.com/bitcoin/bitcoin/pulls/ernestognw) | 1&nbsp;(0%) | -2 | -1 | 1 | 1&nbsp;(0%) |
| 93 | [priem19](https://github.com/bitcoin/bitcoin/pulls/priem19) | 1&nbsp;(0%) | -2 | -1 | 1 | 1&nbsp;(0%) |
| 94 | [wodry](https://github.com/bitcoin/bitcoin/pulls/wodry) | 0&nbsp;(0%) | -6 | -6 | 2 | 1&nbsp;(0%) |

**Comment by sanjaykdragon** [comment]
hey thats me at number 69 😎
