### ISSUE TITLE
getblock <hash> 2 does not return list of addresses anymore

### ISSUE THREAD

**Issue by streamofstars** [bitcoin/bitcoin#17835]
Since version bitcoin-core-0.19.0.1 the `bitcoin-cli getblock <hash> 2` command does not produce lists of addresses in tx, vout. It works fine in bitcoin-core-0.18.1.

**Expected behavior**
Verbose level json returned by bitcoin-cli getblock command for a given block hash should print a list of addresses in tx, vout.

**Actual behavior**
For each tx, vout: reqSigs and addresses are missing

**To reproduce**
```
bitcoin-cli getblockhash 0
000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
bitcoin-cli getblock "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f" 2
```

**System information**
Ubuntu 18.04.3 LTS x86_64, 4.15.0-72-generic, bash 4.4.20, Intel i5-8500B (4) @ 2.999GHz (virtual machine on VirtualBox 1.2). Tested: bitcoin-core-0.19.0.1, bitcoin-core-0.18.1, bitcoin-core-0.18.0.

**Example**
bitcoin-core-0.18.1 see [https://pastebin.com/pQApzMCK](https://pastebin.com/pQApzMCK) (tx, vout contains addresses array)
bitcoin-core-0.19.0.1 see [https://pastebin.com/JsDP6kqQ](https://pastebin.com/JsDP6kqQ) (addresses are not present)

**Notes**
I only checked a few old blocks (such as genesis block in examples above), I cannot confirm this is also the problem with the recent blocks (maybe for some reason it just doesn't work only with P2PK but it works fine with P2PKH?).

If this is by design please point me to the appropriate change documentation, I couldn't find any clear indication of addresses list removal from the command output.

**Comment by sipa** [comment]
This is indeed intentional: https://github.com/bitcoin/bitcoin/pull/16725

It was considered a bug that an address was shown for P2PK outputs (as the address shown was really one for the P2PKH output for the same key, and no address for the P2PK one exists).

**Comment by streamofstars** [comment]
Ah, ok, thank you. So I am closing this issue since it is not really a bug.
