### ISSUE TITLE
 Document how to run bitcoin unittests + functional tests with sanitizers

### ISSUE THREAD

**Issue by elichai** [bitcoin/bitcoin#17834]
A small guide from ground up on how to run sanitizers(asan/ubsan/msan) on core would be awesome :)

@practicalswift ;)

**Comment by elichai** [comment]
argh forgot it matters what kind of issue I click on (for labeling)

**Comment by jonatack** [comment]
Agreed!

I planned to write one about valgrind memcheck and might propose one for this as well if someone else doesn't do it. A recent newcomer perspective like mine combined with feedback from people like @practicalswift and @MarcoFalke would probably work well.

**Comment by jonatack** [comment]
This issue from https://github.com/bitcoin/bitcoin/issues/17620#issuecomment-559156227 might be a good starting point.

**Comment by practicalswift** [comment]
MSan setup is documented by the config in #18288 ("build: Add MemorySanitizer (MSan) in Travis to detect use of uninitialized memory").

@elichai @jonasnick Would you mind reviewing and/or Concept ACK:ing #18288? :)

**Comment by practicalswift** [comment]
A friendly reminder to anyone interested in this issue to review #18288 (a concept ACK would help!) which at least partly solves the issue at hand: it shows which commands to run to setup MSAN for the project :)

MSAN is by far the trickiest of the sanitizers to set-up, so that is a good start :)

**Comment by IMPranshu** [comment]
Yeah. It will also help beginners like me to understand the approach to writing new unit tests.

**Comment by MarcoFalke** [comment]
This is pretty simple:

* MSan: Compiling with MSan is quite involved. I'd suggest to just compile normally and use `valgrind ./src/test/test_bitcoin` or `./test/functional/test_runner.py --valgrind` instead. Alternatively you can use the `./ci/` system to run any sanitizer task.
* Other sanitizer: Just append `--with-sanitizers=undefined,integer CC=clang CXX=clang++` to your `./configure` call. (Or `--with-sanitizers=address`, ...). Then, run the tests normally, using the env vars as needed:

```
export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1:second_deadlock_stack=1"
export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1"

**Comment by jonatack** [comment]
Thanks @MarcoFalke! Updated https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests with that information, along with a link to https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#sanitizers.

**Comment by Sjors** [comment]
Anything left to do here?

Seems mostly a matter of `./configure with-sanitizers=…` and then the test suite runs as normal, albeit slower and more memory hungry.

**Comment by Sjors** [comment]
#27154 adds documentation about suppressions, which is useful.

Running the functional tests with valgrind - and otherwise normal compilation, though `with--enable-debug`, causes a bunch of failures for me. Compiling without legacy wallet helps, so we could document that. For the other failures I still need to check if they're deterministic.
