### ISSUE TITLE
 ￼ Error: Error parsing JSON

### ISSUE THREAD

**Issue by jmburch921** [bitcoin/bitcoin#17847]
i tried getblockhash in the console and got;  ￼ Error: Error parsing JSON

**Comment by fanquake** [comment]
This issue tracker is for technical issues related only to Bitcoin Core, and should not be used for general questions / usage / support. You might want to try the [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) instead.

**Comment by MarcoFalke** [comment]
Works for me just fine. If this still is an issue, please provide steps to reproduce.

![Screenshot from 2020-01-02 10-38-26](https://user-images.githubusercontent.com/6399679/71675611-23d2bf80-2d4c-11ea-8b6e-61eed3d4f94a.png)
