### ISSUE TITLE
My funds are locked... help (Base58 P2sh address)

### ISSUE THREAD

**Issue by jmburch921** [bitcoin/bitcoin#17846]
I got a private key in bitcoin core for one of my receiving addresses.  When I went     to import it, it imported another address and locked my funds as non spendable.  I have been trying to convert this WIF key but I cannot.  How o I find the corresponding key or sign or anything?????

**Comment by MarcoFalke** [comment]
Import in Bitcoin Core or a different software? What are the steps to reproduce?

**Comment by Crypto-Anarchist** [comment]
@MarcoFalke he said that he used Bitcoin core. @jmburch921 try to import it into Electrum: https://electrum.org I hope you are not trying to convert the private key somewhere online!

**Comment by Crypto-Anarchist** [comment]
Duplicated: https://github.com/bitcoin/bitcoin/issues/17818#issue-543268386 You can close this issue @MarcoFalke.
