### ISSUE TITLE
check std::to_string usage 

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17866]
#17851 added `std::to_string` to the list of locale dependent functions, along with a large number of usage exceptions. It was [pointed out](https://github.com/bitcoin/bitcoin/pull/17851#pullrequestreview-338239560) that some of these usages are actually likely bugs, and should be fixed rather than hidden as exceptions.

**Comment by practicalswift** [comment]
The reason for the `KNOWN_VIOLATIONS` list is to be able to guard against introduction of _new_ locale dependence by breaking the build if a new violation is introduced.

Thus the addition of an entry in `KNOWN_VIOLATIONS` should _not_ be seen as an approval of the use of a locale dependent function, or a way to "hide" such use.

FWIW I consider all entries in `KNOWN_VIOLATIONS` to be potential bugs :)  Ideally that list should empty.

**Comment by MarcoFalke** [comment]
C++17 comes with `std::to_chars` and `std::string_view`. Given that this bug should probably be fixed before we switch to C++17, we should add our own helper function for that. `std::string ToString(int*_t)` seems good enough?

**Comment by luke-jr** [comment]
@practicalswift At least a few of the ::to_string uses are *not* bugs, and *should* be locale-dependent... ;)

**Comment by m2709** [comment]
30460425898

**Comment by MarcoFalke** [comment]
Is there an example locale to test with where std::to_string does *not* return the desired result? I couldn't find one.

**Comment by practicalswift** [comment]
@MarcoFalke 

```
#include <cassert>
#include <clocale>
#include <string>

int main()
{
    std::setlocale(LC_ALL, "vi_VN");
    assert(std::to_string(1.23) == "1.23");
}
```

```
$ ./loc
loc: loc.cpp:8: int main(): Assertion `std::to_string(1.23) == "1.23"' failed.
Aborted (core dumped)
```

**Comment by MarcoFalke** [comment]
I don't think we use `std::to_string` for floats, only for ints. So the current usage should be fine?

**Comment by practicalswift** [comment]
@MarcoFalke 

Apart from formatting issues relying on the current locale might introduce threading gotchas. Note that concurrent calls to `std::to_string` from multiple threads may result in partial serialisation of calls :)

Personally I've given up on trying to divide unintentional locale dependence into the buckets "unsafe" and "safe": given the amount of gotchas I feel it safer to consider all unintentional locale dependence to be potentially unsafe :)

**Comment by practicalswift** [comment]
While waiting for the locale-independent `std::to_chars` (C++17)  we could perhaps use a local `ToChars(T)`? To make things simple we could limit ourselves to the `std::is_integral<T>::value` case.

`std::to_chars` implementations:
* [libstdc++](https://github.com/gcc-mirror/gcc/blob/a5d8a40617df40680cf7de6109925e4f1f1b9ae2/libstdc%2B%2B-v3/include/std/charconv#L102-L142)
* [libc++](https://github.com/llvm-mirror/libcxx/blob/ad464887b93526235ce06bbf97cd396ed6232b9a/include/charconv#L354-L380)
* [MSVC's STL](https://github.com/microsoft/STL/blob/19067f675253943eedc9d5894bb960f7c74d8471/stl/inc/charconv#L36-L146)

**Comment by practicalswift** [comment]
> I don't think we use `std::to_string` for floats, only for ints.

I'm afraid that is not correct :(

**Comment by sanjaykdragon** [comment]
> I don't think we use `std::to_string` for floats, only for ints. So the current usage should be fine?

Only usage I could find of something that isn't an int is twice for double:
https://github.com/bitcoin/bitcoin/blob/95ca6aeec7b8d9dbf39e3a036a5c238634ce3793/src/test/blockchain_tests.cpp#L33

**Comment by elichai** [comment]
> While waiting for the locale-independent `std::to_chars` (C++17) we could perhaps use a local `ToChars(T)`? To make things simple we could limit ourselves to the `std::is_integral<T>::value` case.

Is this our only option? can we use this instead? https://github.com/bitcoin/bitcoin/blob/master/src/tinyformat.h#L1070 (the only caveat is that it will require us to provide the right fmt string, altough if that's a big deal we can easily write specialization wrappers)

**Comment by sanjaykdragon** [comment]
> > While waiting for the locale-independent `std::to_chars` (C++17) we could perhaps use a local `ToChars(T)`? To make things simple we could limit ourselves to the `std::is_integral<T>::value` case.
> 
> Is this our only option? can we use this instead? https://github.com/bitcoin/bitcoin/blob/master/src/tinyformat.h#L1070 (the only caveat is that it will require us to provide the right fmt string, altough if that's a big deal we can easily write specialization wrappers)

my vote is on this, although I would prefer something more like:
https://github.com/fmtlib/fmt

**Comment by sipa** [comment]
Tinyformat is localized too, I believe. It uses the standard c++ stringstream interface.

**Comment by elichai** [comment]
> Tinyformat is localized too, I believe. It uses the standard c++ stringstream interface.

:( I wasn't sure but couldn't find the word "locale" in the repo. sucks.

**Comment by practicalswift** [comment]
Why not using something along the lines of …

```
template <typename T>
std::string ToString(const T t) {
  std::ostringstream oss;
  oss.imbue(std::locale::classic());
  oss << t;
  return oss.str();
}
```

… ? :)
