### ISSUE TITLE
PSBT file handler

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#17870]
#17509 introduces a Load PSBT menu option. It would be even easier if a user can double-click on a PSBT file, open it from an email, etc. For this we would need to register a file handler. 

This can be done by defining a [QAbstractFileEngineHandler](https://doc.qt.io/archives/qt-4.8/qabstractfileenginehandler.html) for `.psbt` files, which should then call the same code as "File" -> "Load PSBT".

One potential downside of a file handler, is that it encourages users to double-click on potentially untrusted files, which might be nasty executables.

**Comment by jonasschnelli** [comment]
Does the .psdb file format has a header/magic?

**Comment by Sjors** [comment]
I don't think so: https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#Encoding

On iOs I was able to register a filehandler on the .psbt extension, and then just try to decode it.

**Comment by practicalswift** [comment]
I don't think we should do this until the PSBT parsing issues reported in #17149 ("Potential PSBT issues found by the PSBT fuzzer") have been addressed. User safety first! :)

**Comment by fanquake** [comment]
Moved this to the GUI repo: https://github.com/bitcoin-core/gui/issues/52.
