### ISSUE TITLE
Bitcoin core copyright notices

### ISSUE THREAD

**Issue by Crypto-Anarchist** [bitcoin/bitcoin#17883]
@fanquake Can you replace Hyphen with En Dash in all files in Bitcoin core which includes a copyright notice? 

En Dash HEX: `&#x2013;`
En Dash is used **for ranges**.

Copyright (c) *-2019 The Bitcoin Core Developers, should be replaced with `Copyright (c) *–2020 The Bitcoin Core Developers`

Examples: 
Copyright (c) 2009–2010 Satoshi Nakamoto
Copyright (c) 2009–2020 The Bitcoin Core Developers

Related commit: https://github.com/bitcoin/bitcoin/commit/99813a9745fe10a58bedd7a4cb721faf14f907a4

**Comment by MarcoFalke** [comment]
I don't see a valid reason to do this. The code churn only has drawbacks.

**Comment by Crypto-Anarchist** [comment]
What drawback @MarcoFalke ? Tell me just one valid reason why we should use hyphen instead of the correct En Dash? Clarify for me that "drawback" if you can't come up with a reason than reopen the issue. 

Authoritarian decisions on the design, the source code or anything which is related to Bitcoin core is not welcome! 

I urge you to reopen the ticket and let the community to see and decide.

**Comment by MarcoFalke** [comment]
This stylistic change comes at a cost and risk for the project as a whole. The weak motivation for the change does not justify the burden that it places on the project. A burden could be any of the following:

* Time spent on review
* Accidental introduction of bugs
* (Silent) merge conflicts, either in the branch or a backport branch. Those conflicts demand further developer and reviewer time or introduce bugs.

For more information about refactoring changes and stylistic cleanup, see
* https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#refactoring
* https://github.com/bitcoin/bitcoin/blob/master/.github/PULL_REQUEST_TEMPLATE.md
* https://github.com/bitcoin/bitcoin/issues/15465

Generally, if the style is not mentioned nor enforced by the developer notes, we leave it up to the original author to pick whatever fits them best personally and then leave it that way.

Let me know if you have any questions.

**Comment by Crypto-Anarchist** [comment]
Since when cost anything to replace Hypen ( - ) with En Dash ( – ) how this poses any risk? :thinking:  In Germany if someone sees an – En Dash is like seeing U.S. armed drone in Ramstein? Scary? :fearful:

**Comment by Crypto-Anarchist** [comment]
@MarcoFalke I recommend you to read the **"Decision making process"** section: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#decision-making-process If you are not the project lead than be kind and re-open this issue.

**Comment by MarcoFalke** [comment]
See this section:

> In general, all pull requests must:
> *    Have a clear use case, fix a demonstrable bug or serve the greater good of the project (for example refactoring for modularisation);

Changing one dash with another dash that looks visually similar, but is a different utf-8 code does not fulfill any of the requirements for a pull request
