### ISSUE TITLE
docker image to build bitcoin with visual studio

### ISSUE THREAD

**Issue by MithrilMan** [bitcoin/bitcoin#17885]
https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md contains a description about how to build with Visual Studio.
It suggests a way to deal with external dependency libraries but still isn't a straightforward process and it's very time consuming to setup such an environment, as evidenced by https://github.com/bitcoin/bitcoin/issues/17864

would be nice to have an easy to use docker image that can be used to build bitcoin, with needed dependencies already there

it seems Visual Studio Code has an extension that allow you to develop inside a container, see https://code.visualstudio.com/docs/remote/containers , so this would be the perfect solution to have an easy to use environment to build bitcoin, would be possible to have such feature implemented?

(I'm not aware of something similar for Visual Studio 2019, would be nice to have it supported too)

**Comment by fanquake** [comment]
Concept NACK.

This has been proposed and turned down multiple times before: https://github.com/bitcoin/bitcoin/pull/10903, https://github.com/bitcoin/bitcoin/pull/13542, https://github.com/bitcoin/bitcoin/issues/11141.

Dockerfiles are not something we should have to maintain in this repository. If anything, a more suitable place might be https://github.com/bitcoin-core/packaging. Also see: https://github.com/bitcoin-core/packaging/pull/2.

**Comment by MithrilMan** [comment]
Generally speaking, I think that to have a broader audiance (if this is one of your goal) you'd need to create easier dev environment setup/bootstrap for people to work with, and my request was thoward that.
I'm not talking about having an image where you can run what you can run on your linux setup (just an example) but a way to attract and make productive people coming from other tool sets and environment like me.

e.g. having a docker image that embed a remote component that let you to develop with your local Visual Studio Code would be very attractive.

I always found the used environment requirements quite a barrier to me because I don't have lot of time nor will to invest in learning each of the different tools used here (I'm not talking about the C++ language) and I think others are in the same position and having a way to "easily" use my favourite and well known tools to compile from source would be really helpful and would have pros for the project too (more contributors).

P.S.
I asked here for this feature because you have already a `build_msvc` folder and I consider this an enhancement.

**Comment by sipsorcery** [comment]
IMHO the msvc build cannot be made much simpler. I appreciate you had issues installing `vcpkg` but in my experience that's unusual and it is now the de-facto Microsoft tool for installing msvc dependencies. My subjective opinion is that if anything docker adds another moving part and makes the build more complicated.

That all being said I know @NicolasDorier is a big fan of docker and maintains a lot of [images](https://hub.docker.com/u/nicolasdorier). He might have or know of one that can build Bitcoin Core.

**Comment by MithrilMan** [comment]
It's not me having these issues, I took that issue as example, anyway there's nothing easier than having a docker image that contains all the needed stuff with the steps listed there already done.

Thanks for poiting me the list of images there even if they are intended more to be used as runtime more than dev.

I'd start to think that it's not clear the advantage of what I asked for, maybe if you think about having a restore point of the environment machine you use to dev would be a fair comparison: if your pc go nuts you can restore it from an image with everything setup without the need to pass through the whole cycle of installing 3rd party libraries, compile them, etc...

moreover such an image should only be updated in case you update or add/remove 3rd party libraries because current bitcoin code could just checked out normally from the container itself like you would with your pc

**Comment by NicolasDorier** [comment]
Dockerfile are not useful for development time. You want to have everything installed locally as is already documented.

That said, the argument that Dockerfile do not belong here is in my opinion deeply flawed.

Right now there is tons of page explaining how to compile bitcoin in different environments.
Such documentation can be replaced by dockerfile and tested as part of CI. 
This is less maintenance rather than more.

**Comment by MithrilMan** [comment]
> Dockerfile are not useful for development time
Not sure what you mean, actually I'm using a custom image for my dev process, starting from https://github.com/freewil/bitcoin-testnet-box as a starting point and I've configured 3 regtest nodes to be up and running when I need them, this way I can easily test my client network implementation against a bitcoincore node (enabling -debug=net in my scenario on that testnet box)

So to me docker is very useful at development time, because I can start over from an image without the need to backup data folders or such.
I'm even thinking about using docker as part of integration tests

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
