### ISSUE TITLE
BIP 152 status

### ISSUE THREAD

**Issue by MithrilMan** [bitcoin/bitcoin#17903]
I'm not sure where to put this issue, anyway reading BIP 152, that's active in the protocol, I see it has a Status reported as Draft.

For someone like me that's trying to implement the protocol following the specification, it's already difficult to dodge the official dev documentation `https://en.bitcoin.it/wiki/Protocol_documentation` with its dated (and even wrong) informations and reading BIPS it's not clear if a BIP is included or not for sure in a protocol without checking the code.

I'd expect official BIPs having at least a correct Status reported, but as just said, BIP 152 is reported as Draft that sounds confusing (and probably wrong)
![image](https://user-images.githubusercontent.com/5107375/72162886-085a5b00-33c3-11ea-99a0-985bf6a23a79.png)

As a side note, what's the most updated reference (not mentioning "the code") currently available?
Thanks

**Comment by emilengler** [comment]
As a general note:
Only because there is a BIP for it it doesn't mean that it is generally in Bitcoin Core

**Comment by MithrilMan** [comment]
Let's talk about this specific case.
BIP 152 is described in the official developer reference
It's implemented in bitcoin core ( https://github.com/bitcoin/bitcoin/search?q=sendcmpct&type=Code )
And what's the BIP status for?

Draft to me is something that's not defined nor official and I wouldn't expect to have something draft implemented in core, draft to me means that it may be subject to changes.

I think there is a need of a review of current BIP in order to have at least their status updated correctly.
(I'd say there is a generic need of updated documentation in a broader sense, the official one contains lot of mistakes that instead of helping cause problems to developers)

**Comment by emilengler** [comment]
> I think there is a need of a review of current BIP in order to have at least their status updated correctly.

Please open an issue for this on [bitcoin/bips](https://github.com/bitcoin/bips)

**Comment by MithrilMan** [comment]
I don't see any Issue button there.

**Comment by sipa** [comment]
In general there is no such thing as "officially included in the protocol". Protocol BIPs are implemented by some software and not by others, and that's fine.

Information about what BIPs are implemented by Bitcoin Core specifically can be found in https://github.com/bitcoin/bitcoin/tree/master/doc/bips.md

That said, it does seem that the status here is outdated. I think the responsibility for progressing the status is on the author/champion, but without incentives it's perhaps expected that it will lag behind. The best place to discuss this is probably the bitcoin-dev mailinglist.

**Comment by MithrilMan** [comment]
thanks @sipa so the Status itself is something that's just indicative, correct?
And this mean even that bitcoin core may implement just a part of the BIP, or an older version?

(I tried to stay away from the ML because I'm already flooded by messages but at this point I think could be worth to join it)

**Comment by sipa** [comment]
Yeah, it's unclear to me what the actual function of BIP status is, given that there is no actual authority that determines what is part of an "official spec" or not. An exception is of course soft forks, where in general there is an unambiguous way of telling whether they are active on the network or not (and even that is debatable, see the rest ML discussion...), but in general BIPs are a every client chooses for themselves what to implement thing.

**Comment by sipa** [comment]
Ping @luke-jr, @TheBlueMatt.

**Comment by luke-jr** [comment]
The BIP Status field is for documentation: https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki#BIP_status_field

I agree this one should be bumped. Best if @TheBlueMatt opens the PR since he's the champion and needs to make the call that the BIP is completed.

**Comment by MarcoFalke** [comment]
Yes, someone should bump the status field. Anyone can open the pull request.

**Comment by MithrilMan** [comment]
shouldn't the issue stay open until status get bumped?

**Comment by MarcoFalke** [comment]
I'd say no. This is the issue tracker for the Bitcoin Core software, not for the BIPs repository.

As I said earlier anyone can open the pull request to the BIP to change it to `Final`. I don't see why this needs discussion here or why this issue needs to stay open.

**Comment by MithrilMan** [comment]
Why then you don't enable to open Issues on bitcoin/bips?
Would be a win-win.

**Comment by MarcoFalke** [comment]
I think the discussion forum for bips is the mailing list: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev

Simple issues, that are not worth to bring to the mailing list can be fixed right away by anyone
