### ISSUE TITLE
docs/fuzzing.md: mention that afl-clang(++) may be needed for MacOS builds

### ISSUE THREAD

**Issue by Crypt-iQ** [bitcoin/bitcoin#17914]
When fuzzing on my macOS Mojave laptop, I was unable to instrument the binaries with the command mentioned in the docs:
`
./configure --disable-ccache --disable-shared --enable-tests --enable-fuzz CC=${AFLPATH}/afl-gcc CXX=${AFLPATH}/afl-gcc++
`
This resulted in the following failure:
```
[-] On Apple systems, 'gcc' is usually just a wrapper for clang. Please use the
    'afl-clang' utility instead of 'afl-gcc'. If you really have GCC installed,
    set AFL_CC or AFL_CXX to specify the correct path to that compiler.

[-] PROGRAM ABORT : AFL_CC or AFL_CXX required on MacOS X
         Location : edit_params(), afl-gcc.c:159
```

When I replaced afl-gcc with afl-clang and afl-g++ with afl-clang++, the binaries were properly instrumented.  I made an issue instead of a PR as I wasn't sure whether others had run into this problem or if this was specific to my machine.  If this is reproducible on other Macs, then this should be documented in `fuzzing.md`.

**Comment by MarcoFalke** [comment]
Looks like a good-first-issue for someone with macOS.

#### Useful skills:

Basic build system skills

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
Similarly to afl, libFuzzer also needs some extra steps on macOS according to the second section of this comment: https://github.com/bitcoin/bitcoin/issues/17657#issuecomment-562869600

**Comment by jules23** [comment]
hi! I'll give this a go.
