### ISSUE TITLE
configure complains about boost-chrono if boost-test-dev is missing

### ISSUE THREAD

**Issue by ysangkok** [bitcoin/bitcoin#17922]
**Expected behavior**
Should complain about boost-test missing.
**Actual behavior**
Complains about boost-chrono missing.
**To reproduce**
I have all dependencies except boost-test-dev, as shown when I try to execute the apt line from build-unix:

```
% sudo apt install libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev 
[sudo] password for janus: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-filesystem-dev is already the newest version (1.65.1.0ubuntu1).
libboost-system-dev is already the newest version (1.65.1.0ubuntu1).
libboost-thread-dev is already the newest version (1.65.1.0ubuntu1).
libevent-dev is already the newest version (2.1.8-stable-4build1).
libboost-chrono-dev is already the newest version (1.65.1.0ubuntu1).
The following additional packages will be installed:
  libboost-test1.65-dev libboost-test1.65.1
The following NEW packages will be installed:
  libboost-test-dev libboost-test1.65-dev libboost-test1.65.1
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 532 kB of archives.
After this operation, 5,687 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

But when I run configure:

```
./configure --enable-debug --with-gui=no  --disable-hardening --with-incompatible-bdb
[...]
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: error: Could not link against boost_chrono !
```

This error message is misleading.

**System information**
Ubuntu 18.04, commit ceb789cf3a9075729efa07f5114ce0369d8606c3 of bitcoin.

**Comment by hebasto** [comment]
It seems an [upstream](https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_boost_unit_test_framework.m4) issue.

**Comment by ysangkok** [comment]
@hebasto I assume you link that file because you think it contains a bug. I thought it would be because it mentions Chrono in an error message instead of UnitTest, but that is not the case. Why did you link that file?

**Comment by hebasto** [comment]
`configure` messages
> checking whether the Boost::Unit_Test_Framework library is available... yes
> configure: error: Could not link against boost_chrono !

are generated by this macro
https://github.com/bitcoin/bitcoin/blob/002f9e9b4041e9b5bf8a91680ce980bf9ff15074/configure.ac#L1128

which is defined in [`ax_boost_unit_test_framework.m4`](https://github.com/bitcoin/bitcoin/blob/master/build-aux/m4/ax_boost_unit_test_framework.m4)

**Comment by ysangkok** [comment]
Closing because it is an upstream issue as mentioned.
