### ISSUE TITLE
Surface "general information" through RPC

### ISSUE THREAD

**Issue by msafi** [bitcoin/bitcoin#17952]
**Is your feature request related to a problem? Please describe.**

3rd party Bitcoin clients using `bitcoind` don't have an easy and reliable way to know the general info that's displayed in the Bitcoin Core GUI.

![image](https://user-images.githubusercontent.com/4027731/72632954-477d3480-390c-11ea-8b15-08e496c3b576.png)

I would like to be able to display this information on the Bitcoin client that I'm working on.

**Describe the solution you'd like**

How can we surface this information through RPC? Should we add a new RPC endpoint for it? Something like `getgeneralinfo` which would return the `clientversion`, `datadir`, `blocksdir`, and `startup` time?

**Comment by brakmic** [comment]
Hi,

I've implemented a possible solution to this feature request. This is how it looks like when executed in the console:

**bitcoin-cli -regtest getgeneralinfo**
```shell
{
  "clientversion": "v0.19.99.0-a654626f0-dirty",
  "useragent": "/Satoshi:0.19.99/",
  "datadir": "/Users/brakmic/Library/Application Support/Bitcoin/regtest",
  "blocksdir": "/Users/brakmic/Library/Application Support/Bitcoin/regtest/blocks",
  "startuptime": "2020-01-18T17:49:50Z"
}
```

**bitcoin-cli -regtest help getgeneralinfo**
```shell
getgeneralnfo

Returns data about the bitcoin daemon.

Result:
  {
    "clientversion": "version string",     (string) Client version
    "useragent":"client name",             (string) Client name
    "datadir":"datadir path",              (string) Data directory path
    "blocksdir":"blocksdir path",          (string) Blocks directory path
    "startuptime":"string",                (string) Startup time
  }

Examples:
> bitcoin-cli getgeneralinfo 
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getgeneralinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```

However, I am not sure about the **format of the startup time** as it is shown right now. Maybe there's a better convert function that I should be using.

We'll see after I have opened the PR. ;)

Regards,

**Comment by jonatack** [comment]
I'm not sure what the use case is here. Perhaps related to #17314, and more applicable to it than the RPC API, though the trend seems to be toward *removing* info like this, not adding it.

**Comment by msafi** [comment]
@jonatack the use case is basically enabling a separate GUI that's powered by `bitcoind` and that is as capable as Bitcoin Core GUI. Of course this `getgeneralinfo` end-point alone doesn't enable that, but it moves us a little bit closer.

I think there's a general desire to rearchitect the Bitcoin Core GUI so that it is not tightly coupled with the code outside of the `qt/` folder. In that case one obvious solution is to have a GUI that works asynchronously by using RPC with `bitcoind`, as described in [this comment](https://github.com/bitcoin/bitcoin/issues/17395#issuecomment-552166858).

**Comment by jonatack** [comment]
I'm not sure what the comment you cite has to do with this issue. I use the rpc interface as my primary one for interacting with bitcoind and don't understand the use case for this change. See https://github.com/bitcoin/bitcoin/pull/17958#pullrequestreview-344956750. Maybe other people will see value in adding this call.

**Comment by jonatack** [comment]
Thanks @msafi for the explanation.

**Comment by msafi** [comment]
@jonatack Sorry, I should've been more specific. I was referring to this line from the comment:

>If I would have some wishes open, one of them would be that the GUI works perfectly asynchronous over the RPC interface

Perhaps because you use RPC as the primary interface, you don't see the value in adding this call? I felt the need for this change when I tried to rebuild the Bitcoin Core GUI by only relying on `bitcoind` and RPC.

Based on my limited understanding of the code, it seems to me that the `getinfo` call is specific to `bitcoin-cli`. If you don't use `bitcoin-cli` and talk directly to RPC by using `curl` you don't have access to `getinfo`.

**Comment by jonatack** [comment]
Yes, agreed, I didn't understand what the motivation was. This makes more sense now. I'll defer to others' opinions here.

**Comment by MarcoFalke** [comment]
This information is already available:

* `uptime`
* `getnetworkinfo`

**Comment by msafi** [comment]
@MarcoFalke Please see this https://github.com/bitcoin/bitcoin/pull/17958#issuecomment-576023845

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
