### ISSUE TITLE
qt: Shadow ribbon at the bottom of QFrame

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#17967]
A semi-opaque ribbon is observed in the main window:

![DeepinScreenshot_bitcoin-qt_20200119212040](https://user-images.githubusercontent.com/32963518/72686984-752bce80-3b02-11ea-8e54-a4d0e6448c1f.png)

![DeepinScreenshot_bitcoin-qt_20200119212253](https://user-images.githubusercontent.com/32963518/72686986-7a891900-3b02-11ea-87b8-cb2a7ff5b791.png)

Tab switching does not remove it. Window moving does not remove it.
It vanishes after window resizing.

**To reproduce**
Run with `-regtest`, generate some blocks (200 in my case), then quit.
Remove `rev00000.dat` file to trigger an error.
Run with `-regtest` and in the dialog "Do you want to rebuild the block database now?" click "OK".

**System information**
Linux Mint 19.3 + Cinnamon 4.4.8

Both versions affected:
- 0.19.0.1 (gitian)
- master + system Qt 5.9.7

**Comment by jonasschnelli** [comment]
Can confirm the bug.
Looking into it.

**Comment by jonasschnelli** [comment]
The reason for this glitch is very likely two simultaneous running `QPropertyAnimations`.
