### ISSUE TITLE
Sign Message UI allows selection of keyless addresses

### ISSUE THREAD

**Issue by dscotese** [bitcoin/bitcoin#17969]
## What Happens
When you click File|Sign Message, the UI asks you to choose an address with which to sign.  You can enter one by hand, paste from clipboard, or "Choose a previously used address."  The third option provides a list of addresses that includes addresses for which there is no private key (P2SH addresses).  This is intimately related to #10542 but the fix _here_ is straightforward.

## Expected Behavior
I expect addresses for which no private key is known to be excluded from the list presented.  I realize that the same list is used to select an address to which to receive a payment, but that code could be adjusted to accept a filter, or the private-key-less addresses could be filtered out during display.

## To reproduce
Ensure that you have at least one P2SH address in your Bitcoin core wallet.
Select File | Sign Message
Click the address book.
Note that there are P2SH addresses offered for selection.

This is in Bitcoin Core 0.18.

**Comment by yozaam** [comment]
Hey should we check this exists:
 PKHash* pkhash = boost::get<PKHash>(&addressinlist); 
And then would we have to call the wallet().getPrivKey to check that as well or would the above be enough.
Actually would it not be more efficient to have a filtering bool value for the addresses, or is there another location we can fetch them from

**Comment by fanquake** [comment]
I've moved this over to the GUI repo: https://github.com/bitcoin-core/gui/issues/62.
