### ISSUE TITLE
./bitcoin-qt: symbol lookup error: ./bitcoin-qt: undefined symbol

### ISSUE THREAD

**Issue by Jiankun-Huang** [bitcoin/bitcoin#17970]
Hi, I am getting this error every time I run ./bitcoin-qt. I am using Ubuntu 18.04.3 LTS Bitcoin 0.14 source.
**./bitcoin-qt: symbol lookup error: ./bitcoin-qt: undefined symbol: _ZN5boost11this_thread5hiden9sleep_forERK8timespec**

Thanks

**Comment by fanquake** [comment]
> Bitcoin 0.14 source.

This version is well beyond it's end of life, and is no longer supported. See our [lifecycle documentation](https://bitcoincore.org/en/lifecycle/#schedule).
