### ISSUE TITLE
Paying bitcoin with banknotes

### ISSUE THREAD

**Issue by saintthor** [bitcoin/bitcoin#17983]
**I am considering a plan to pay bitcoin with banknotes.**

The banknotes is described [here](https://medium.com/@saintthor/the-decentralized-private-blockchains-and-the-advanced-cryptocurrency-3d5eef8475cb?source=friends_link&sk=70bb77d883ad90280760e7c90832dd85). 

Abstract:
1. Each banknote is an ownership-changeable private blockchain.
2. Only the owner can add blocks. The owner of a banknote can transfer it to others by adding blocks.
3. To carry payments of currencies by the banknotes, just like the paper banknotes, can achieve good decentralization without POW.
4. It can work for bitcoin.

**To transfer bitcoin to the banknotes is easy.**
There is no new feature needed.
Steps:
1. Create a banknote with its Id.
2. On the bitcoin's blockchain, transfer some bitcoin to the Id of the banknote as the receiving address. This part of bitcoin is frozen.
3. Add a block to the banknote which can contain the UTXO information generated in step 2. Then transfer the banknote to pay this part of bitcoin freely with good performance and power saving. 

**Return the part of bitcoin.**
Now we need some new feature to receive bitcoin from the banknotes.
Steps like:
1. Destroy the banknote by adding a destroy block that contains a wallet address.
2. On the bitcoin's blockchain, after verifying the whole banknote, transfer the frozen bitcoin to the address defined in step 1.

**In the future**
If for some reason, POW can not go on, bitcoin may reborn on the banknotes.

How do you think about this idea?  Feedback is highly appreciated.

Thanks.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by saintthor** [comment]
> Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

How can I get bitcoin developers to add this feature?
