### ISSUE TITLE
gui: 0.19.0.1 keeps hanging while syncing coins

### ISSUE THREAD

**Issue by gab81** [bitcoin/bitcoin#18005]
Since installing 0.19.0.1, i had issues while syncing coins.

This happens when Core is behind some days or blocks, if it is running all the time, it's OK.

0.19.0.1 64 bit
Win 10 64 bit home
ASUS VivoBook S15 S510UQ
Core chain runs on external HDD Maxtor 2TB on usb 3 (connection working up to 100 mb/sec)
Core installed on 256 GB SSD Sandisk - up to 300-400 mb/sec

While sync, HDD active time goes to 100% and transfer at about 1-3 mb/sec so hdd transfer speed over usb3 is NOT the issue.

During the sync, program goes to "Not responding" for around 15-20 seconds, if left as it is then it resumes properly and will eventually finish and working fine. **However an inexperienced user might get scared, close core and in that case I think that his coins would get compromised due to repeated syncing attempts (I am not 100% sure about that though)**

Issue confirmed by other users here: https://bitcointalk.org/index.php?topic=5215754.0

Checked core logs and didn't find anything pointing to this odd behaviour.

thanks

**Comment by minblock** [comment]
Check your paging file for a 2TB External drive, 8GB is a soft amount of RAM to handle that

**Comment by hebasto** [comment]
#17565 could be related.

**Comment by gab81** [comment]
my laptop has 8gb ram and pagefile is 1.25gb. this never happened much in version 0.18, maybe once when you start it, but this is like all the time on and off until synced.

**Comment by laanwj** [comment]
Yes, I've also noticed the GUI is still suffering from (temporary) hangs when catching up or during initial sync. Not sure if this is worse than it was with 0.18 though or not.
Main issue for this is #17145.

**Comment by gab81** [comment]
hello - any updates? is there going to be an interim version before 0.20 to address this? is really hanging badly at the minute, if I open the core now is really stuck, was 5 days not syncing.. thanks

**Comment by gab81** [comment]
hello everyone - i am still experiencing the very same issue up to this day, it has been months. anyone knows when the new release or a fix will be coming out? many thanks!

**Comment by MarcoFalke** [comment]
An experimental 0.20.0rc1 might be out soon. It doesn't fix the issue, but it might improve on it.

**Comment by gab81** [comment]
@MarcoFalke - thanks for the info, hopefully it's a bit better!

**Comment by hebasto** [comment]
> I am surprised that nobody is complaining about it since it's a confirmed bug.

Is #22745 the same?

Does this happen to v22.0? If so, please provide your `debug.log` file.

Also suggesting to move this issue into the dedicated repo: https://github.com/bitcoin-core/gui/issues.

**Comment by fanquake** [comment]
Closing this in favour of #17145 / opening an issue in the GUI repo.

**Comment by gab81** [comment]
hello - it does still happen but i live with it, syncing is usually relatively fast so i don't touch it while it's running it (because it hangs here and there). i updated to the latest one and i think it's better. honestly i ran it once recently and cannot tell if totally fixed or not but was better. thank you
