### ISSUE TITLE
travis: s390x ci build fails on travis because disk is too small

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18016]
Reported upstream a couple of months ago: https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954

**Comment by flack** [comment]
is it possible to add the build to `allow_failures` (https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail) while the upstream issue is unresolved? Then you'd get a green travis icon, but it still would run

**Comment by MarcoFalke** [comment]
Yes, that would be preferable to not running it at all

**Comment by MarcoFalke** [comment]
Adding good first issue. This can probably be fixed either:

* by changing the docker data dir: https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954/7?u=marco
* by adding `allow_failures` in the travis yaml

**Comment by MarcoFalke** [comment]
For now it has been removed:

*  test: Disable s390 build on travis #18106 

I think we should still try to change the docker data dir on travis, and then re-enable this

**Comment by MarcoFalke** [comment]
This is still an issue, even after #18569 

 https://travis-ci.org/github/bitcoin/bitcoin/jobs/681559037#L1965

**Comment by MarcoFalke** [comment]
If this continues, we should disable it again
