### ISSUE TITLE
Gitian-built unit tests fail on windows

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18015]
Current master:

```
test_bitcoin.exe

Running 389 test cases...

test/script_p2sh_tests.cpp(200): error: in "script_p2sh_tests/set": txTo[1].IsStandard

test/script_p2sh_tests.cpp(200): error: in "script_p2sh_tests/set": txTo[2].IsStandard

test/script_p2sh_tests.cpp(200): error: in "script_p2sh_tests/set": txTo[3].IsStandard
```

https://github.com/bitcoin/bitcoin/blame/master/src/test/script_p2sh_tests.cpp#L200

**Comment by MarcoFalke** [comment]
7dbc33f61 passes

**Comment by fanquake** [comment]
Confirmed it happens using a `test_bitcoin` cross-compiled in WSL. I only see the failure if all test cases are run, not if I use `.\test_bitcoin.exe --run_test=script_p2sh_tests`. 

The failure doesn't happen when you compile and test with MSVC.

**Comment by fanquake** [comment]
I've found the issue. Will open a PR to fix shortly.
