### ISSUE TITLE
tests: reset default arguments during test setup

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#18024]
Following up to #18018, we can rework the test setup so that default argument are reset/re-parsed as part of the setup for each test. 

> [This can be fixed by parsing the command line arguments when the TestingSetup is constructed. Calling AppInitParameterInteraction will reset them to the default.](https://github.com/bitcoin/bitcoin/pull/18018#issuecomment-579786714)

> [As a follow-up it could make sense to normalize argument parsing and have the TestingSetup re-parse the arguments to set them to the default. Though, I suspect that that would be a larger change.](https://github.com/bitcoin/bitcoin/pull/18018#issuecomment-579902625)

**Comment by MarcoFalke** [comment]
btw, the args are now parsed to some extent in the test setup, so if someone is interested here, this might be fixable

**Comment by MarcoFalke** [comment]
Longer term we should remove all globals anyway

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
