### ISSUE TITLE
wallet: walletprocesspsbt does not add input bip32_derivs when signing

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#18039]
Steps to reproduce:

1. Create PSBT without BIP32 derivation info: `bitcoin-cli -testnet walletcreatefundedpsbt '[]' '[{"mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt": 0.001}]' 0 '{"feeRate": 0.0001}' false`

2. Process, but don't sign: `walletprocesspsbt THE_PSBT false ALL true`

Notice that this PSBT has `bip32_derivs` set for all inputs.

2. Process and sign: `walletprocesspsbt THE_PSBT true ALL true`

Notice that this PSBT has `bip32_derivs` set for the change output, but not for the inputs.

**Comment by Sjors** [comment]
cc @achow101

**Comment by achow101** [comment]
Unable to replicate. The `bip32_derivs` for the inputs in my test tx are filled.

**Comment by Sjors** [comment]
TIL `walletprocesspsbt` is also a [Finalizer](https://github.com/bitcoin/bitcoin/blob/master/doc/psbt.md#rpcs). It's probably enough to just document the `bip32_derivs` argument to mention that it won't add that for complete inputs.
