### ISSUE TITLE
Make check FAIL: qt/test/test_bitcoin-qt

### ISSUE THREAD

**Issue by glaksmono** [bitcoin/bitcoin#18058]
Taking the `master` branch. I went thru the build process described here: https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md#build-bitcoin-core

and `make check` FAILED. Here's the output:

```
➜  bitcoin git:(bitcoin-17224) make check
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
../build-aux/test-driver: line 107: 45289 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.19.99
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
➜  bitcoin git:(bitcoin-17224)
```

**System information**

* Mac OS Catalina

**Comment by fanquake** [comment]
You will need to check/provide the actual logs. i.e `src/test-suite.log`.

**Comment by glaksmono** [comment]
@fanquake here you go:

```
➜  bitcoin git:(bitcoin-17224) cat src/test-suite.log
==============================================
   Bitcoin Core 0.19.99: src/test-suite.log
==============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/opt/libevent/lib/libevent_pthreads-2.1.6.dylib
  Reason: image not found
FAIL qt/test/test_bitcoin-qt (exit status: 134)
```

**Comment by fanquake** [comment]
I'd suggest `git clean -fxd` and rebuilding from scratch.

The dynamic loader is failing to load Openssl's `libcrypto`. That means you haven't actually built master, because in that branch we no longer use OpenSSL at all, or, you've probably got some old build artifacts lying around.

**Comment by glaksmono** [comment]
Just redo the whole thing, and still getting the same error @fanquake 

Ideas?

**Comment by fanquake** [comment]
Right. I see that the OpenSSL dependency is coming from libevent. What version do you have installed? Reinstalling it via brew should fix the issue, as it will install OpenSSL as one of it's dependencies.

**Comment by glaksmono** [comment]
So here's what I did to make it work:

1. Upgraded `homebrew`
2. Reinstall `openssl`
3. Re-do https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md#build-bitcoin-core
