### ISSUE TITLE
Fatal error when send after use removepruned

### ISSUE THREAD

**Issue by mrbabtc** [bitcoin/bitcoin#18074]
I made a transaction RBF sending BTC. I deleted this transaction before confirmation using 'removeprunedfunds {txid}'
When I make a new transaction RBF sending BTC , after to click to confirm the send I get 'Fatal error' and the client closes.

**Expected behavior**

Send a new transaction and different tx with success

**Actual behavior**

It crashes

**To reproduce**

Regtest, using the GUI on Windows, nothing wierd.

**System information**

v19

i5 notebook windows 10 last release updated

segwit native addresses

debug.log:
```
************************
EXCEPTION: St12out_of_range       
map::at       
C:\Program Files\Bitcoin\bitcoin-qt.exe in Runaway exception  
```

**Comment by MarcoFalke** [comment]
What are the steps to reproduce?

**Comment by adamjonas** [comment]
Closing based on lack of response for steps to reproduce. Can re-open if similar issues are observed in the future.
