### ISSUE TITLE
gui: deprecated QCharRef usage in splashscreen

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#18080]
Noticed today while building [master](8a56f79d491271120abc3843c46e9dda44edd308).

```bash
GUI: Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
```

From a quick look the issue is somewhere in [splashscreen.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/qt/splashscreen.cpp). 

You should see the warning if you quit while the splashscreen is still displayed. Likely requires a recent version of Qt (I'm using 5.14.1).

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by hebasto** [comment]
[QTBUG-80346](https://bugreports.qt.io/browse/QTBUG-80346) seems a bit similar.

**Comment by brakmic** [comment]
Hi,

I found [this bugfix](https://codereview.qt.nokia.com/c/qt/qtbase/+/277650/1/src/gui/text/qtextodfwriter.cpp) from Nokia/Qt that dealt with the same problem: an **index pointing outside the valid range** of a QString. 

Then I checked for any index referencing in splashscreen.cpp and found only this one here: https://github.com/bitcoin/bitcoin/blob/master/src/qt/splashscreen.cpp#L140

I know, it's a bit amateur way of trying to find a bug, but _pointing at index_ in a string could only mean something like this, if I am not mistaken. I have also searched for similar accesses like **.at(index)** but couldn't find any. 

I will now try to reproduce the bug. 

Regards,

**Comment by brakmic** [comment]
According to Qt's documentation the **text()** function could also return an empty string, which implies that one should check for them before indexing any chars within.

https://doc.qt.io/qt-5/qkeyevent.html#text

However, as I am still unable to reproduce the error mentioned by @fanquake I don't know if I should open a PR for that.

It would basically contain this:

**line 140, splashscreen.cpp**
```cpp
if(keyEvent->text().count() > 0 && keyEvent->text()[0] == 'q') {
    m_node.startShutdown();
}
```

**Comment by hebasto** [comment]
[`QCharRef QString::operator[](int position)`](https://doc.qt.io/qt-5/qstring.html#operator-5b-5d):

> **Note:** Before Qt 5.14 it was possible to use this operator to access a character at an out-of-bounds position in the string, and then assign to such a position, causing the string to be automatically resized. Furthermore, assigning a value to the returned `QCharRef` would cause a detach of the string, even if the string has been copied in the meanwhile (and the `QCharRef` kept alive while the copy was taken). These behaviors are deprecated, and will be changed in a future version of Qt.

**Comment by hebasto** [comment]
@fanquake 
> You should see the warning if you quit while the splashscreen is still displayed. Likely requires a recent version of Qt (I'm using 5.14.1).

Using Qt 5.14.0 on bionic and 5.14.1 on macOS 10.14.
Couldn't reproduce the issue.

**Comment by brakmic** [comment]
I'm using Qt 5.14.1 on macOS Catalina 10.14.3, but no warning to see.

**Comment by hebasto** [comment]
Actually a `QCharRef` warning is fired if any modifier key is pressed while the splashscreen is still displayed.

**Comment by brakmic** [comment]
> Actually a `QCharRef` warning is fired if any modifier key is pressed while the splashscreen is still displayed.

Thanks for the hint!

Yes, this is true. Just checked it. 
The small change in the **if**statement seems to prevent it from happening. 
Will then open new PR.

**Comment by hebasto** [comment]
> > Actually a `QCharRef` warning is fired if any modifier key is pressed while the splashscreen is still displayed.
> 
> Thanks for the hint!
> 
> Yes, this is true. Just checked it.
> The small change in the **if**-statement seems to prevent it from happening.
> Will then open new PR.

Please review #18101.

**Comment by brakmic** [comment]
> > > Actually a `QCharRef` warning is fired if any modifier key is pressed while the splashscreen is still displayed.
> > 
> > 
> > Thanks for the hint!
> > Yes, this is true. Just checked it.
> > The small change in the **if**-statement seems to prevent it from happening.
> > Will then open new PR.
> 
> Please review #18101.

Ah, OK, will do it! Thanks.
