### ISSUE TITLE
Can a Sybil attack get the node stuck?

### ISSUE THREAD

**Issue by zawy12** [bitcoin/bitcoin#18118]
If a Sybil attack on the node's peer time removes 70 minutes from local time right after the node sees a block with a timestamp that is 120 minutes in the future, does the node get "stuck" in some way?

Not requiring nodes to unilaterally decide world time and not requiring sequential timestamps both violate Byzantine fault tolerance requirements as shown in Lamport et al's original papers. Patches can't fix fundamental holes without doing the mathematical equivalence.  Artforz's Zeitgeist/GeistGeld, timespan limit, Culubas timejacking (this potential node problem is an example of it), and all other timestamp attacks are the result of not meeting basic requirements. They're not holes or errors in code, but errors in the design of the consensus mechanism's clock. 

https://github.com/bitcoin/bitcoin/commit/c9c017a

**Comment by gmaxwell** [comment]
Your link is code that compares the blockchain database to the system's local clock at startup as the database is connected and before any nodes are contacted. I don't see how it relates to your comment.

**Comment by zawy12** [comment]
Then the only attack I see is if a Sybil attack pushes the node time forward 70 minutes **and** then sends a block that has a timestamp that is 189 minutes into the future (that nodes outside of the attack will not approve) **and** if the a node restarts in 70 minutes. It seems like an unlikely scenario. I assume the Sybil attack an't motivate a restart.

**Comment by gmaxwell** [comment]
That is pretty fringe-- particularly because peer-time only lets a nodes initial peers tweak their time, and mostly serves the purpose of fixing DST handling on windows hosts--, but sure, that startup test could be relaxed by another 70 minutes and not really lose any of it intended sensitivity to misconfigured hosts while avoiding a refusal to start in your suggested oddball confluence of events.

**Comment by zawy12** [comment]
> peer-time ... mostly serves the purpose of fixing DST handling 

What other purpose does peer time serve?

**Comment by gmaxwell** [comment]
If it doesn't work, it fails right at node start. Making it fairly uninteresting to attack.

**Comment by zawy12** [comment]
I mean in general, why let a weak consensus mechanism, the median of peer time offset, be part of laying the foundation of POW consensus?  BFT requires a clock, so it seems clear the clock must be most secure than the consensus mechanism.

**Comment by adamjonas** [comment]
Closing due to lack of momentum in the discussion. Can re-open if future interest.
