### ISSUE TITLE
GUI: FlushStateToDisk freezes the GUI

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#18137]
Using a large `-dbcache` leads to "minutes" longs leveldb cache flushes. 
Right now, the GUI freezes during `FlushStateToDisk` which means one can't even bring the window to the front.

It would be great to either display a modal dialog "flushing database state" (and lock GUI interactions) or even allow interacting with the GUI during a flush (may be non trivial to solve).

**Comment by hebasto** [comment]
Also https://github.com/bitcoin/bitcoin/issues/17397

**Comment by hebasto** [comment]
Moved to bitcoin-core/gui#637.
