### ISSUE TITLE
GUI: make -reindex more explicit

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#18136]
When performing a -reindex with the GUI, it visually looks identical to a sync from peers.

It would be preferable to visually indicates the difference.

Things like "syncing with the network" are basically wrong.

**Comment by hebasto** [comment]
Testing `master` (470664f2b788e2cce9202991d11476a6fef00ef4) on Linux Mint 19.3:

![Screenshot from 2020-02-14 01-20-09](https://user-images.githubusercontent.com/32963518/74487567-74e7de80-4ec8-11ea-9f99-09c383791507.png)

Cannot confirm the issue.

@jonasschnelli 
Mind providing steps to reproduce "syncing with the network" with `-reindex` option?

**Comment by jonasschnelli** [comment]
I eventually ran into an edge case,... maybe when a corruption is detected and the GUI asks for a reindex.

**Comment by sipa** [comment]
Can you trigger the issue using -reindex-chainstate ?

**Comment by hebasto** [comment]
> Can you trigger the issue using -reindex-chainstate ?

![Screenshot from 2020-02-14 11-45-50](https://user-images.githubusercontent.com/32963518/74520156-acce4080-4f1f-11ea-8265-d0836d0e157a.png)

**Comment by jonasschnelli** [comment]
I can't reproduce it anymore either. I think I tried to enable txindex & had a corrupted chainstate. But manually reconstructing that doesn't reproduce it.
