### ISSUE TITLE
contrib/devtools/previous_release.sh should be rewritten to python

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18132]
Most of our test scripts are written in python. We don't have enough reviewers for bash scripts and they tend to be clumsy anyway. Especially when it comes to argument parsing.

Thus, contrib/devtools/previous_release.sh should be rewritten in python

#### Useful skills:

Experience with Bash and Python

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by bboot** [comment]
I am starting work on this today.

**Comment by theStack** [comment]
A description of the scripts purpose / usage examples etc. is missing in `contrib/devtools/README.md` as well.

**Comment by bboot** [comment]
Ok.

**Comment by bboot** [comment]
I have the code here:
https://github.com/bboot/bitcoin/tree/previous-release-py

Still going to update the README before making a pull request.  I would like to make a change to check file hash before untarring when using the binary download option, but not sure if this should just focus on conversion to python and keeping the logic the same.

**Comment by MarcoFalke** [comment]
No need to keep the logic 1:1 identical. You can do pretty much anything that makes the resulting python code look good.

**Comment by MarcoFalke** [comment]
@bboot are you still working on this?

**Comment by rja907** [comment]
@MarcoFalke, do you think this is a good first issue? 
I want to start contributing during weekends.

**Comment by MarcoFalke** [comment]
@bboot hasn't responded in two months, so the code from  https://github.com/bboot/bitcoin/tree/previous-release-py can be picked up (while keeping authorship attribution) and then submitted as a pull request here.

**Comment by bliotti** [comment]
I am going to try and add @bboot's idea to check the file hash.
