### ISSUE TITLE
Error: Config setting for -rpcport only applied on test network when in [test] section.

### ISSUE THREAD

**Issue by glaksmono** [bitcoin/bitcoin#18144]
1. Successfully built the code from `master` branch
2. Trying to run `Bitcoin Core.app`
3. The error appears, clicking OK will just close the entire app

![Bitcoin Core Error Message](https://i.ibb.co/SB5r5jB/Screen-Shot-2020-02-14-at-14-03-28.png)

Ideas?

**Comment by hebasto** [comment]
Please read [Network specific options](https://github.com/bitcoin/bitcoin/blob/master/doc/bitcoin-conf.md#network-specific-options). If it won't help, please provide `debug.log` file.
