### ISSUE TITLE
Has anyone thought of integrating a Mempool Visualizer into Bitcoin Core?

### ISSUE THREAD

**Issue by ImranLorgat** [bitcoin/bitcoin#18177]
**Is your feature request related to a problem? Please describe.**
When trying to estimate the fee I should pay in a congested mempool, I have frequently found Mempool Visualizers to be useful. Currently, Bitcoin Core allows you to track the size of the Mempool, but not the distribution of fees over time. There are many useful open-source Visualizers that could be integrated into Bitcoin Core.

**Describe the solution you'd like**
Two projects with clean and simple displays are Johoe's Mempool statistics (my personal favourite) and Mempool space. Both of these are open-source
https://jochen-hoenicke.de/queue/#1,24h
https://mempool.space/graphs
https://github.com/jhoenicke/mempool
https://github.com/mempool-space/mempool.space

**Describe alternatives you've considered**
I am not aware of good reasons why a feature like this wouldn't be included. For e.g. is it resource intensive to track the fee distribution of the mempool by time? I am not a developer but if it is an easy integration and someone can help me, I'm willing to take a stab at it, or at least assist to the degree I can.

**Additional context**
This is a pony :horse:

**Comment by uncleray95** [comment]
I would only say that something like this might be beyond the scope of a node on the network. Bitcoin Core is designed specifically to 1) validate transactions and blocks and 2) connect and share information over the P2P network. All of this is supposed to happen at the minimal cost to the hardware it is running on. That said, it looks like there are some interfaces already out there for monitoring fee distributions like you mentioned, and I'm not sure how important of a value add it is to all users that they have this feature.

**Comment by promag** [comment]
> This is a pony 🐴

🤣 

@uncleray95 also wallet.

I don't think we should track historical data.

**Comment by jonasschnelli** [comment]
See #8550

**Comment by ImranLorgat** [comment]
Thanks for taking the time to explain. I understand the rationale to keep the client as lightweight as possible. If I understand correctly, @jonasschnelli basically built this thing already, tried to get it merged, and it just didn't get over the line. Is that correct?

**Comment by jonasschnelli** [comment]
@ImranLorgat right. I have plans to pick this up soon.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Comment by luke-jr** [comment]
Note that Bitcoin Knots has had #8550 in it for years, for those who want it.
