### ISSUE TITLE
net, gui: -upnp option -- "override" vs "can be changed on-the-fly"

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#18184]
On master (68e841e0af223a220d1f037e4c5680c1b228aa3e) the `-upnp` option being set in the command line or in the configuration file overrides the GUI option _only_ on startup.

If a user (un)checks the "Map port using UPnP" checkbox in the "Network" tab of the "Options" window, the client does not take into account the fact that the `-upnp` option is set in the command line or in the configuration file.

There some ways to resolve an issue:
- document the current behavior
- deactivate the "Map port using UPnP" checkbox if the `-upnp` option is set in the command line or in the configuration file
- smth else

The brainstorm question is which way is the best?

---

This issue was initially raised by **luke-jr** in his [review](https://github.com/bitcoin/bitcoin/pull/18077#discussion_r381553831) of #18077.

**Comment by fanquake** [comment]
This looks like it's a GUI-only issue? So I think this should be moved to the GUI repository.

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/710.
