### ISSUE TITLE
rpc: sendtoaddress and sendmany should return PSBT for watch-only wallet 

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#18180]
Similar to `bumpfee` #16373, I would like `sendtoaddress` and `sendmany` to return a PSBT when used on a watch-only wallet. These methods are easier to use than `walletcreatefundedpsbt`.

I added this functionally as part of external signer support in #16546, which helps keep that PR short. But I think it makes sense as a standalone PR.

**Comment by Sjors** [comment]
Probably best built on top of #18115.

cc @instagibbs, @achow101: how does this fit in the (Legacy/Descriptor)ScriptPubKeyMan architecture? Right now these methods use an RPC helper `SendMoney`, which in turn calls `wallet->CreateTransaction` and `pwallet->CommitTransaction()`. What's the appropriate place to make it call either `FillPSBT()` or `SignTransaction()` on the `ScriptPubKeyMan`?

**Comment by Sjors** [comment]
For `sendtoaddress` the change is pretty straight-forward, see https://github.com/bitcoin/bitcoin/pull/16546/commits/2a04b969d8f97581f741798f57e4d80c6657ec4b

**Comment by promag** [comment]
From #16378

> This paves the way for deprecating sendtoaddress and sendmany though there's no rush. The only missing feature compared to these older methods is adding labels to a destination address.

But here you want to add more features to these RPC :sweat_smile:

**Comment by Sjors** [comment]
Things change quickly! Closing this.
