### ISSUE TITLE
New `maybe-uninitialized` warnings - probably false positives

### ISSUE THREAD

**Issue by elichai** [bitcoin/bitcoin#18198]
With GCC 9.2 and latest master(ab9de435880c9d77e4137b65050591ef2d14f809) I'm getting these warnings:
```
interfaces/chain.cpp: In member function 'virtual Optional<int> interfaces::{anonymous}::LockImpl::findFork(const uint256&, Optional<int>*)':                                                                                                                                   
interfaces/chain.cpp:140:16: warning: '*((void*)&<anonymous> +4)' may be used uninitialized in this function [-Wmaybe-uninitialized]                                                                                                                                            
  140 |         return nullopt;                                                                                                         
      |                ^~~~~~~                                     
interfaces/chain.cpp: In member function 'virtual Optional<int> interfaces::{anonymous}::LockImpl::getHeight()':                        
interfaces/chain.cpp:140:16: warning: '*((void*)&<anonymous> +4)' may be used uninitialized in this function [-Wmaybe-uninitialized]                                                                                                                                            
  140 |         return nullopt;                                                                                                         
      |                ^~~~~~~                                                                                                          
interfaces/chain.cpp: In member function 'virtual Optional<int> interfaces::{anonymous}::LockImpl::findLocatorFork(const CBlockLocator&)':
interfaces/chain.cpp:140:16: warning: '*((void*)&<anonymous> +4)' may be used uninitialized in this function [-Wmaybe-uninitialized]    
  140 |         return nullopt;                                  
      |                ^~~~~~~                                  
interfaces/chain.cpp: In member function 'virtual Optional<int> interfaces::{anonymous}::LockImpl::findFirstBlockWithTimeAndHeight(int64_t, int, uint256*)':
interfaces/chain.cpp:140:16: warning: '*((void*)&<anonymous> +4)' may be used uninitialized in this function [-Wmaybe-uninitialized]    
  140 |         return nullopt;                                    
```

Seems to be related to #18052 but with less clear fix (replacing `nullopt` with `MakeOptional(false...)` is a bad fix IMHO)

Note, I don't see these warnings when compiling with clang 9.0.1

**Comment by kristapsk** [comment]
Can't reproduce, don't have them with gcc (Gentoo 9.2.0-r2 p3) 9.2.0.

**Comment by elichai** [comment]
> Can't reproduce, don't have them with gcc (Gentoo 9.2.0-r2 p3) 9.2.0.

I have `gcc (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130` and tried full cleaning and I still get them

**Comment by hebasto** [comment]
@elichai 
> ... replacing `nullopt` with `MakeOptional(false...)` is a bad fix IMHO

What reasons for?

**Comment by elichai** [comment]
> What reasons for?

Because it's less obvious what it's doing.
`return nullopt;` is obvious. but `return MakeOptional(false, object{})` is less obvious, does it creates a value? does it calls the "object" constructor?.
When you read the docs you can understand it but it's one of those things that if you haven't done in a while you need to open the docs to check what's what. which IMHO is a decrease in readability.

**Comment by elichai** [comment]
This no longer happens on gcc 9.3.0(`gcc (Arch Linux 9.3.0-1) 9.3.0`)
Tested both master(af2ec6b03745cf408f169cfbd74e3380a69975e0) and the commit where I saw it last time and the warning is no longer there

I don't have GCC 9.2.0 to check with that, but because no-one else says they saw that warning I'll close this
