### ISSUE TITLE
Use the same wallet file with multiple wallet instances

### ISSUE THREAD

**Issue by kryvel** [bitcoin/bitcoin#18205]
Hi there!
Is there any way to share one wallet.dat file across different bitcoin wallet instances
My goal is to create failover wallet service, so I could manage my funds if main server with wallet is going down.
As I understand default HD wallet creates only 100 keypairs, so after I use all of them I should sync wallet.dat file with my backup server, is it true?

**Comment by MarcoFalke** [comment]
As the instances of the wallet.dat are not synchronized, at best loosely connected via the p2p transaction relay, this will lead to address and key-reuse if you are lucky. Double spends and loss of funds if you are less lucky.

I think we should document better than wallet files can not be copied and used at the same time.

**Comment by kryvel** [comment]
Thanks for explanation!
