### ISSUE TITLE
Not sending all block messages on regtest after generate a large amount of blocks

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#18203]
I am experiencing a bug where on regtest, when one generates a large number of blocks (more than 10) using the `generatetoaddress` CLI command, bitcoind does not send `headers` messages, but instead it sends `inv` messages for the generated blocks. However, the number of `inv` messages does not match the number of the generated blocks.

**Comment by mzumsande** [comment]
> However, the number of inv messages does not match the number of the generated blocks.

This effect was explained by @sdaftuar in #17451.

**Comment by benthecarman** [comment]
> > However, the number of inv messages does not match the number of the generated blocks.
> 
> This effect was explained by @sdaftuar in [#17451 (comment)](https://github.com/bitcoin/bitcoin/issues/17451#issuecomment-575898689).

Thank you
