### ISSUE TITLE
`blockfilterindex` Extensibility Proposal

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#18221]
https://github.com/bitcoin/bitcoin/pull/14121 implemented `blockfilterindex` in a way that it is extensible to different filter types, however there is only one single filter type so far, which is the default one, and combinations of these filter types aren't possible. In this proposal I describe how it is possible to add other filter types in a way that it is (1) backwards compatible and (2) all possible combinations of different filter types are possible.

### Having Different Filters In Parallel

As far as I understand the code it is already prepared and adding a new filter type does not require refactoring to achieve this. So one would be able to define

```
blockfilterindex=basic
blockfilterindex=p2wpkh
```

and the software will create both of those filters in parallel.

### Combinations of Filters

`blockfilterindex=basic`'s value maps to `uint8_t` values: 0 and 1. We can also represent `uint8_t` with a byte array that holds 8 octets. In case of `basic` it would be `00000000` (0) or `00000001` (1).  

![image](https://user-images.githubusercontent.com/9156103/75546298-8680c880-5a28-11ea-9880-b19b7d50a4ed.png)

The idea is to use the bytes to denote the next filter types. For example we can assign `00000010` (2) to `p2wpkh` and `00000100` (4) to `p2wsh`. Further as the need arises we can use a larger type `uint32_t` or something like that to be able to define larger number of types.

![image](https://user-images.githubusercontent.com/9156103/75546336-98fb0200-5a28-11ea-8b99-6e0542f9cb32.png)

But why not just go `1,2,3,4,5...` instead? Because this would enable us to also specify filter combinations. For example if I specify 6 (`00000110`) then I see that the `p2wpkh` and `p2wsh` octets are both flipped to true, so the software would add both to the filter:

![image](https://user-images.githubusercontent.com/9156103/75546383-af08c280-5a28-11ea-8c38-4167f310ba51.png)

```c++
// If blockfilterindex  is turned on.
foreach (var script in scripts) {

    if (no higher octets are flipped to true other than the basic filter type's) {
        filter.Add(script);
        continue;
    }
    // However for backwards compatibility if a higher octet is true then disregard the basic filter type's octet since currently both 0 and 1 are defined to be the basic octet type. This will result two numbers evaluating to the same combination (Alternatively config parsing can throw an error or whatever to disable one of the number.)

    if (p2wpkh octet is true AND script is p2wpkh) {
        filter.Add(script);
        continue;
    }

    if (p2wsh octet is true AND script is p2wsh) {
        filter.Add(script);
        continue;
    }

    // Add other types
}
```

### Not In a Hurry

Luckily whoever would add the next filter type wouldn't need to consider this proposal at all, because the next filter type would be `2` anyway, which lets us delay the decision until the 3rd filter type is added, of which according to this proposal should hold the value of `4` instead of `3` in order to facilitate the combinations of filter types.

**Comment by MarcoFalke** [comment]
As I read this, this is a BIP modification, which should go here: https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki#filter-types (after discussion on the mailing list)

**Comment by nopara73** [comment]
Thank you! I submitted it to the mailing list. Will progress forward of creating a PR for the BIP if consensus is reached.
