### ISSUE TITLE
What if i change nBits to 0x2100ffff, will other nodes accept it?

### ISSUE THREAD

**Issue by summer-wu** [bitcoin/bitcoin#18235]
If I change `nBits` to a hard code number `0x2100ffff` ( change `GetNextWorkRequired` method, always return `0x2100ffff`).
The `hashTarget` will be `ffff000000000000000000000000000000000000000000000000000000000000`.

This hashTarget means nealy every sha256 are valid! A slow PC can generate a block within a second, when I broadcast these blocks to other nodes, will they accept it ( treat it as a valid block)?

**Comment by MarcoFalke** [comment]
No, they shouldn't.

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by summer-wu** [comment]
I've found the code that reject these kind of attack.

The source that I investigating is `9d2174b (tag: v0.3.1rc1)`

in main.cpp , in CBlock::AcceptBlock() wrote:
```
    // Check proof of work
    if (nBits != GetNextWorkRequired(pindexPrev))
        return error("AcceptBlock() : incorrect proof of work");
```
