### ISSUE TITLE
code logic is wrong if no mining block is generated in 24 hours

### ISSUE THREAD

**Issue by MapleLaker** [bitcoin/bitcoin#18231]
i read code in IsInitialBlockDownload(), located in https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp.

if (m_chain.Tip()->GetBlockTime() < (GetTime() - nMaxTipAge))
        return true;

Let us image if someday somehow all miners are out of work for 1 day, all relay node's block will be 24 hours later than local time. Even they are always online. As a result all node becomes IBD status.

This logic/code above should be considered ... 
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by MarcoFalke** [comment]
No, it latches to false

**Comment by MapleLaker** [comment]
"latches to false" means "m_cached_finished_ibd"?
it is in memory data. what if node is restarted and it is so lucky that all miner was not work during the node's offline time ?
