### ISSUE TITLE
rpcdoc: Remove redundant type from description

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18258]
The RPC docs are now enforced to specify the json type of the args and results at compile time. However, some help texts contain the type twice. (E.g. https://github.com/bitcoin/bitcoin/pull/17809#discussion_r386295217 ). The duplicate type in the description should be removed.

Duplicates can be found with this command:

```sh
git grep --extended-regexp  'RPC.*(ARR|OBJ).*json (array|object)' src/rpc/ src/wallet/rpc*
```

#### Useful skills:

Basic understanding of how to compile and run Bitcoin Core.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by yashpatel20** [comment]
I am working on it
