### ISSUE TITLE
test: add option to functional test_runner to adjust test timeouts

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#18266]
It was [suggested](https://github.com/bitcoin/bitcoin/pull/18249#issuecomment-593944985) that we could have an additional argument for the [functional test_runner](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_runner.py) that modifies the timeouts by some factor. This would save having to randomly bump timeouts in the tests themselves, as users that require longer timeouts can opt in by `-factor=1.5` etc. 

Follow up to #18249.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by modfort** [comment]
I would like to work on this .

**Comment by MarcoFalke** [comment]
To find the timeouts that need to be reworked:

```
git grep 'def ' test/functional/test_framework/ | grep 'timeout='

git grep 'self.rpc_timeout = 60' test/functional/test_framework/

**Comment by modfort** [comment]
Hi , if you can help with a problem in configure , configure: error: LRELEASE not found , i have manjaro 64 .

**Comment by MarcoFalke** [comment]
@modfort Please file a separate issue with steps to reproduce about your build error

**Comment by brakmic** [comment]
Hi,

I'm not sure about the current state of this Issue, so in case my work "clashes" with @modfort 's , feel free to pilfer any parts that are valuable to you. I won't be opening a PR unless it's OK with everyone participating in this thread.

[My solution](https://github.com/brakmic/bitcoin/commit/f35acfc01c862fd0412f006d24e21bceaf2bf1ab) adds a [factor option](https://github.com/brakmic/bitcoin/blob/test-timeouts-with-factor/test/functional/test_framework/test_framework.py#L169) to `BitcoinTestMetaClass` in `test_framework`. First, I tried the same with `test_runner` but couldn't forward the factor arg to test cases (error: *the options object and/or factor arg were missing*...not sure why, I must be missing something important regarding the test framework's infrastructure). 

Therefore, I went to change `BitcointestMetaClass`.

The functions with `timeout`parameter that I updated are located in `authproxy`, `mininode` and `test_node`. I used @MarcoFalke 's grep commands (thanks for that!).  

I've seen many more functions that expect similar arguments but didn't want to change them without consultation.

Cheers,

**Comment by brakmic** [comment]
Maybe it's better to open a proper PR so that others can see that's something happening here? There are so many issues in the backlog and not everyone has enough time to go through all of them to check for changes. 

I will now open a PR, and then we can discuss. If there is anything speaking against it, please let me know.

Cheers,
