### ISSUE TITLE
Relay policy for small transactions

### ISSUE THREAD

**Issue by Saicere** [bitcoin/bitcoin#18296]
One (granted, fairly minor) issue I encountered lately was a "tx-size-small (code 64)" error when broadcasting a transaction to discard a small UTXO. The most efficient way to do this that I could see was to simply create a transaction with a single vout consisting of an empty OP_RETURN, but it turns out that such a transaction, while recognized as valid by decoderawtransaction, is below the MIN_STANDARD_TX_NONWITNESS_SIZE defined in policy.h and is therefore rejected for relaying.

You can of course just add ~30 bytes of junk data to OP_RETURN to reach the size limit, which makes the transaction relayable and mineable with the current policy. Similarly, in the case of any other otherwise-standard transaction that is valid for relaying outside of the limit defined in MIN_STANDARD_TX_NONWITNESS_SIZE , you could just pad the transaction with another OP_RETURN or similar vout. Therefore, this restriction seems both rather pointless and wasteful.

There are some valid reasons why you might want to junk a UTXO, such as if you do not want to combine it with other UTXOs for privacy reasons (say in the case of dust being sent to an address by a third party for de-anonymization purposes), or if the wallet is empty outside of said UTXO and it would be below the dust limit if you sent it elsewhere. You could of course just leave it, but many wallets do not have coin control or coin locking facilities, which means it might inadvertently be included in a transaction at a later point. As such, while I recognize that this is somewhat of an edge case, seeing as the size restriction does not really seem to fulfill its stated purpose of discouraging non-standard transactions anyway, would it not make sense to loosen this restriction to allow otherwise-standard transactions with just one single-byte vout?

**Comment by MarcoFalke** [comment]
If you sign the input with the appropriate script flags or use someone else's input with the appropriate script flags, you can combine them with no loss in privacy that would have otherwise existed. I think we lack the infrastructure to organize this exchange of inputs, but it shouldn't be too hard to write either.

In any case you posted on the issue list of the Bitcoin Core software. If you have questions about how Bitcoin works, you can ask on the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

If you want to suggest changes to Bitcoin, the `bitcoin-dev` mailing might be better suited.

**Comment by Saicere** [comment]
Thanks for the response, but it does not really seem to address the actual issue. Specifically, Bitcoin Core's default relay policy prevents a transaction with exactly one (P2WPKH) vin and exactly one OP_RETURN vout from being recognized as "standard" unless the OP_RETURN contains at least 30 bytes or so of (possibly junk) data, because of the minimum size limit for a transaction, and I believe this might be an oversight as this restriction was only committed [less than two years ago ](https://github.com/bitcoin/bitcoin/commit/7485488e907e236133a016ba7064c89bf9ab6da3).

**Comment by MarcoFalke** [comment]
This has not been an oversight; See #16885 for more information.

**Comment by instagibbs** [comment]
Now that it's public, can we not just make 64 byte stipped txns invalid?

cc @jl2012

**Comment by MarcoFalke** [comment]
The has been a discussion on the mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-June/016102.html
