### ISSUE TITLE
Running out of disk space forces pruned node to reindex

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#18301]
Was testing on a VM with less space than I expected. Node cleanly shutdown due to disk space low, but after resizing disk larger and restarting, it insisted on a reindex.

`-prune=550`

**Comment by MarcoFalke** [comment]
What is the error message that prompts the reindex? `checkblock`, `leveldb`, ... ?

**Comment by emilengler** [comment]
I'm currently trying to reproduce, what does prune option mean? Have you executed it after you resized your disk or was your node running the entire time with `-prune=550`?

**Comment by luke-jr** [comment]
It was `-prune=550` the entire time. After the clean out-of-space shutdown, the VM itself was rebooted to make the virtual disk larger.

**Comment by MarcoFalke** [comment]
Duplicate of #17392 ?

**Comment by fanquake** [comment]
> Duplicate of https://github.com/bitcoin/bitcoin/issues/17392 ?

I think so.
