### ISSUE TITLE
Add option to "archive" blocks

### ISSUE THREAD

**Issue by roshii** [bitcoin/bitcoin#18321]
**Is your feature request related to a problem? Please describe.**

I am currently running two nodes: one over clear net without a wallet, and on over tor which broadcast my transactions for the sake of privacy. As far as I know this requires keeping two copies of the blockchain for each node and while this is relevant for the last blocks, it doesn't make much sense for oldest ones.

**Describe the solution you'd like**

I'd like to see an option to move blocks to some sort of archive folder which could be shared across two or more nodes.

**Describe alternatives you've considered**

I could prune the tor connected node which has far less inbound client but this would prevent access to block history to tor connected users.
I could add a tor proxy to the clear net node to allow tor users to retrieve block history but it would add complexity to the setup.

**Additional context**

This option would not only save me 200 GB of storage but allows one to run all kind of different tailored bitcoin services with minimum storage requirements while still maintaining the full chain history.

**Comment by adamjonas** [comment]
Given this hasn't been picked up since 2020, closing due to lack of momentum/interest. Can re-open if future interest.
