### ISSUE TITLE
Full blocks are sent despite a filter being set

### ISSUE THREAD

**Issue by schildbach** [bitcoin/bitcoin#18324]
When downloading the block chain, some 0.19.0.1 nodes are sending full blocks rather than filtered blocks despite the peer having used `filterload` to set a filter. I'd expect to only send filtered blocks or drop the connection.

By sending full blocks, bitcoind is currently causing high phone bills to mobile users with metered data plans.

**Comment by MarcoFalke** [comment]
Can you explain the steps to reproduce or show a log excerpt? As I understand BIP 37, merely setting `filterload` does not make the node to send only filtered blocks. Blocks still need to be queried with a getdata that sets `MSG_FILTERED_BLOCK == 3`.

**Comment by MarcoFalke** [comment]
Also, if 0.19.0.1 is broken, is 0.18.* the last version that was working?

**Comment by schildbach** [comment]
At the current time I can't provide logs because I didn't see this on my own bitcoind. What I see is a massive number of txns per block (2000-3000) right from the beginning of the download from a checkpoint.

It's probably too early to talk about affected versions, but so far I only remember seeing 0.19.0.1.

**Comment by MarcoFalke** [comment]
With checkpoint do you mean wallet birthday?

And to double check, you only send getdata of type 3?

This is the function that sends out blocks: https://github.com/bitcoin/bitcoin/blob/v0.19.0.1/src/net_processing.cpp#L1357-L1510 . You can highlight the lines that have a `PushMessage` in it and can see that each of them is conditioned on the `inv.type`.

**Comment by MarcoFalke** [comment]
Is the type of the block message `block` or `merkleblock`?

**Comment by theStack** [comment]
@schildbach: Is there a possibility that the `filterload` command has not arrived at the node? Since TCP is used I think that's unlikely to not be discovered by the client, but maybe for whatever internal reasons the packet was not even transmitted by the client.
Due to the bug described in https://github.com/bitcoin/bitcoin/issues/18483, you would receive full blocks if you request `merkleblock`s, but no `filterload` was received by the node before.

**Comment by schildbach** [comment]
@theStack I can't say, because I don't have any bitcoind logs of the issue. Our code certainly sets a filter, but of course there could be subtle bugs. I must admit that I'm not super happy about the quality and maintainability of bitcoinj's network code. That said, I think bitcoind should just drop the connection if it detects an unexpected state. (Ideally send a `REJECT` first, but that's another topic.)

**Comment by MarcoFalke** [comment]
@theStack I don't think it is possible for Bitcoin Core to respond with a `block` to an inv that sets `MSG_FILTERED_BLOCK`. Even with the code mess from #18483.

**Comment by theStack** [comment]
Sorry for the confusion and my wrong conclusion, I was not reading thoroughly -- @MarcoFalke is right, I also definitely not see a way that regular `block`s are sent as reply to received `inv`s with `MSG_FILTERED_BLOCK` inside.

**Comment by MarcoFalke** [comment]
I'd suggest to close this issue. Absent any information on how to reproduce, or even what message types were sent in what order, this is hard to debug.

If you have the code available of the exact version of your client software you were using, I can take a look, but other than that I don't think we can solve this issue.

**Comment by schildbach** [comment]
Ok, fair enough. I'll keep an eye on it and try to produce better logs.
