### ISSUE TITLE
Hide the "Welcome" screen on bitcoin-qt

### ISSUE THREAD

**Issue by David-Lor** [bitcoin/bitcoin#18356]
**Is your feature request related to a problem? Please describe.**
I'm building a Docker image that runs bitcoin-qt with a VNC server using [this image](https://github.com/jlesage/docker-baseimage-gui) as base.

This works, but I'd like to hide the Welcome screen that opens when you start bitcoin-qt for the first time.

**Describe alternatives you've considered**
I'm creating a Bitcoin-Qt.conf file BEFORE starting bitcoin-qt itself, with the settings I'd like to use by default, so it should not open the Welcome screen to ask for them, since they are already set up. 

However, the Welcome screen still pops up. But it is reading some of my settings, at least the `strDataDir` that is set to my predefined location - but `bPrune` is not (the checkbox to enable/disable the blockchain prune).

**Question**
How does bitcoin-qt know that the Welcome screen was already setup?

**Comment by achow101** [comment]
You should not be creating a bitcoin-qt.conf file, or try to modify any settings within it. This file is created and handled by the Qt library and is not meant to be user modified. It's where the setting set in the GUI are saved. Instead you should be using a bitcoin.conf file in your datadir. Command line arguments and bitcoin.conf options will override any of the settings set from within the GUI (aka all the things in bitcoin-qt.conf).

bitcoin-qt checks for the existence of the datadir. So just make sure the datadir exists and the welcome dialog won't appear.

**Comment by David-Lor** [comment]
@achow101 Thanks for the clarification. I was modifying to bitcoin-qt.conf file to force set the data dir, but I could map it to the default directory in Home. I will try to keep it unaltered from the beginning.
