### ISSUE TITLE
min relay fee not met, 0 < 226 (code 66)

### ISSUE THREAD

**Issue by Maochengfag** [bitcoin/bitcoin#18365]
Hello everyOne,

I am developing an BTC wallet. During testing transaction  I get this problem. I add fee equal to 0.01 but I get this message.

Could you help me to solve this problem?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
