### ISSUE TITLE
SCRIPT_ERR_SIG_PUSHONLY error string is wrong

### ISSUE THREAD

**Issue by Coding-Enthusiast** [bitcoin/bitcoin#18411]
https://github.com/bitcoin/bitcoin/blob/57a8fa9c3b4452ef7a9d9ed4b957b3888f542fb0/src/script/script_error.cpp#L60-L61  
It should be `Non-push operators are not allowed in signatures` or `Only push operators allowed in signatures`.

**Comment by theStack** [comment]
Good catch! As far as I saw no test relies on the string, so it can simply be corrected -- I opened a PR (#18412) to solve this issue.
