### ISSUE TITLE
Add test for whitelisted peers' transactions when -blocksonly mode is on

### ISSUE THREAD

**Issue by glowang** [bitcoin/bitcoin#18428]
In #18391  we fixed the documentation issue for `-blocksonly` and how it interacts with other parameters. We would to extend the test in p2p_blocksonly.py for wallet transactions and maybe even whitelisted peers, to ensure that our understanding of the behavior is correct and our update in 18391 is accurate.

**Comment by glowang** [comment]
I would like to work on this issue, as a continuation of the work in the 18391 PR.

**Comment by MarcoFalke** [comment]
Fixed #18530
