### ISSUE TITLE
Add fuzzing harnesses

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18431]
Adding fuzz tests is a low hanging fruit. This is an open ended issue.

See previously contributed fuzz tests: https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+label%3ATests+is%3Aclosed+fuzz
See missing fuzz coverage: https://marcofalke.github.io/btc_cov/fuzz.coverage/index.html

#### Useful skills:

* Basic fuzzing background, see the quickstart guide: https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md#fuzzing-bitcoin-core-using-libfuzzer
* Basic C++ knowledge

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by pierreN** [comment]
Thank you for creating the issue, this looks interesting and I would not have thought about it. 

I was looking at other older `good first issue` too (namely #16419 , #15598, #17289) but this seems better. I'll try to have a look.

**Comment by pierreN** [comment]
I'm trying to help on this, could by any chance anyone pinpoint a nice harness to write to start with (maybe @practicalswift since you seem to do a lot of fuzzing?) ? Thanks

**Comment by MarcoFalke** [comment]
The fuzz target can literally be anything. You can use as much creativity as you want.

It can be a simple target like the constructor of `CMessageHeader(1,2,3)` (c.f. #16995) or advanced stateful classes like the mempool (tx acceptance and graph) or most validation datastructures (block header tree, ...).

**Comment by Angelika1920** [comment]
https://freebitco.in/?r=37278138
