### ISSUE TITLE
write tests for bloomfiltered connection

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18473]
There are some independent tests that can be added:

* <strike> Fix the TODO https://github.com/bitcoin/bitcoin/pull/18334/files#diff-a77567bbc57dc1bbc033560e5cdd3b7dR400 </strike> :heavy_check_mark:  Done in #18593
* Add a test for msg_mempool. (Create a tx before the peer connects, then connect, then send msg_mempool)
* Check that a new peer get's disconnected when Bitcoin Core doesn't have `-peerbloomfilter` set
* Run the `FilterTest` functional test with a second node that has `fRelay` set to false in the version message, see https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki#extensions-to-existing-messages
* ...

#### Useful skills:

Basic understanding of BIP 37 and the Bitcoin Core functional test framework

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by chanhosuh** [comment]
Hi Marco, I'd like to work on this.

**Comment by gzhao408** [comment]
@chanhosuh are you still working on this?

**Comment by chanhosuh** [comment]
@gzhao408 Nope, feel free to pick it up!

**Comment by gzhao408** [comment]
Thanks! I'm going to try to tackle this!

**Comment by gzhao408** [comment]
Made progress on Add a test for msg_mempool, working the issue here: https://github.com/gzhao408/bitcoin/tree/test-bloomfilter
I'll make a PR when I have more to show :)

**Comment by gzhao408** [comment]
#19083 
> * Check that a new peer get's disconnected when Bitcoin Core doesn't have `-peerbloomfilter` set

@MarcoFalke I'm not 100% sure I understand this correctly, what does it mean for Bitcoin Core to have this set? I grepped for `fDisconnect = true` looking for things related to `peerbloomfilters` and wrote tests for what I found. I'm not sure if that's what you're referring to though.

**Comment by MarcoFalke** [comment]
`-peerbloomfilter` is a command line setting to enable or disable the NODE_BLOOM service bit. If the NODE_BLOOM bit is not set, any light client will be disconnected immediately.

**Comment by gzhao408** [comment]
> If the NODE_BLOOM bit is not set, any light client will be disconnected immediately.

I think I got somewhere - So far, I have a test with `peerbloomfilters=0` and am adding a peer using `node.add_p2p_connection`. I'm making the peer a light client by omitting `NODE_NETWORK`. I'm able to verify through `getpeerinfo()` that services are getting set correctly, but it's not disconnecting as expected.

I think the logic I'm testing is [this line](https://github.com/bitcoin/bitcoin/blob/3657aee2d25ce1ffefc6817af3eead7120b1d755/src/net_processing.cpp#L2260) (am I looking in the right place?) and noticed that it checks that the node is an outbound peer. Is it possible that that's what I'm missing? I'm having trouble figuring out how inbound/outbound is distinguished in a functional test... am I going in the wrong direction?

**Comment by NicolasDorier** [comment]
> Check that a new peer get's disconnected when Bitcoin Core doesn't have -peerbloomfilter set

Of the peer is whitelisted, it should work

**Comment by MarcoFalke** [comment]
> I think the logic I'm testing is this line

I believe the disconnect happens here https://github.com/bitcoin/bitcoin/blob/3657aee2d25ce1ffefc6817af3eead7120b1d755/src/net_processing.cpp#L2222

**Comment by gzhao408** [comment]
Ah okay thank you! So it's only when they send a `msg_filteradd` or `msg_filterload`. It looks like they get disconnected no matter what, and additionally banned if they're on `NO_BLOOM_VERSION` or higher. I already test disconnect, but my trouble now is that I'm not sure how to test banning (I need to somehow non-manually connect a node and have it send a `filter` message)?

Additionally, I think that `filterclear` should also be one of the messages that we would disconnect/ban in this situation. It was removed in [#8709](https://github.com/bitcoin/bitcoin/pull/8709) but I don't think it's still applicable?

**Comment by MarcoFalke** [comment]
Don't worry about banning. I don't think that needs to be tested because an attacker can circumvent it in any case.

Longer term banning might even go away completely.

**Comment by gzhao408** [comment]
Er... how do I close this issue? 😅
