### ISSUE TITLE
Create test_fuzz library from ./src/test/fuzz/fuzz.cpp

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18527]
We have one wrapper file around the fuzzing engine (`src/test/fuzz/fuzz.cpp`), so that fuzz tests can be written independent of the engine. This file is compiled for each fuzz target (harness), so with currently more than 114 fuzz targets this is quite an overhead. All the wrapper does is provide the `main` function for the fuzz target.

I am not sure, but I believe the main function can also be provided by a library. Moving this file to a library would also compile it only once, thus speeding up compilation of the fuzz tests.

This issue can probably be solved similar to #17542 

#### Useful skills:

* Background in the autotools build system

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by brakmic** [comment]
Will look into it.
