### ISSUE TITLE
Tests fail intermittently on Windows (appveyor) "OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18548]
Example:

* https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/31988561#L4009

**Comment by hebasto** [comment]
It seems the following comment could be relevant:
https://github.com/bitcoin/bitcoin/blob/1b151e3ffce7c1a2ee46bf280cc1d96775d1f91e/test/functional/test_framework/authproxy.py#L102-L104

**Comment by ryanofsky** [comment]
I wonder if this is happening more frequently? Here is another case: https://cirrus-ci.com/task/4904963898867712?logs=functional_tests#L2583

**Comment by darosior** [comment]
Encountered this in https://github.com/bitcoin/bitcoin/pull/23074#issuecomment-926737249 too
