### ISSUE TITLE
QT abandoning open source LTS releases

### ISSUE THREAD

**Issue by jameshilliard** [bitcoin/bitcoin#18580]
Since we currently use QT LTS releases for building Bitcoin Core we may run into a problem as LTS releases are [being dropped](https://www.qt.io/blog/qt-offering-changes-2020) from the open source part of the QT project.

There are also [reports](https://mail.kde.org/pipermail/kde-community/2020q2/006098.html) that QT may end up entirely abandoning open source for all QT releases less than 12 months old.

Since it appears in both of these cases they will not be providing security fixes in a timely manner we may want to start planning how best to deal with these unfortunate changes.

From my understanding the QT parts of Bitcoin Core have minimal attack surface due to how we use QT but I'm not entirely sure.

**Comment by promag** [comment]
> We are making this change to encourage open-source users to quickly adopt new versions.

This might be OK for the GUI since desktop users are probably also using most recent versions of their favourite OS. Only concern I can see is Qt pushing the minimum GUI requirements.

**Comment by MarcoFalke** [comment]
I don't think we have a choice. Now that they dropped LTS, all we can do is follow their latest open source release.

**Comment by MarcoFalke** [comment]
Does anyone know how long the support for non-lts versions is? "Qt 5.15 is supported as usual for all our users" isn't helpful. https://www.qt.io/blog/qt-5.15-released

**Comment by fanquake** [comment]
> Does anyone know how long the support for non-lts versions is?

My understanding is that "standard support" is 1 year from release.
So the currently supported versions of Qt seem to be:

| Version | Release Date | Supported Until |
| ------- | ------------- | ---------------- |
| 5.9 (LTS) | 31/5/2017 | 31/5/2020 |
| 5.12 (LTS) | 31/1/2019 | 5/12/2021 |
| 5.13 | 19/6/2019 | 19/6/2020 |
| 5.14 | 12/12/2029 | 12/12/2020 |
| 5.15 (LTS Commercial license only) | 26/5/2020 | 26/5/2023 |

Annoyingly they have also stopped adding "Supported until" dates to their "Supported Platforms and Configurations" pages, like they did for [5.9](https://doc.qt.io/qt-5.9/supported-platforms-and-configurations.html). However I did find a presentation that seems to confirm the dates above:

<img width="753" alt="qt" src="https://user-images.githubusercontent.com/863730/83209751-9fb22600-a18b-11ea-807a-11446a3b8ae4.png">

**Comment by Sjors** [comment]
This could become an acute problem if they e.g. bump their minimum compiler version earlier than we're willing to.

**Comment by hebasto** [comment]
Should we keep this issue open?

**Comment by fanquake** [comment]
I don't think we need to. Not really anything we can do in regards to non LTS releases. If anyone wanted to discuss this further the gui repo is probably a better place anyways.
