### ISSUE TITLE
rpc: raw pointers should be replaced with shared_ptr

### ISSUE THREAD

**Issue by brakmic** [bitcoin/bitcoin#18590]
While working on this PR https://github.com/bitcoin/bitcoin/pull/18570 I ran into a bit confusing situation where in one function a **CWallet reference** was expected while two others dealt with **CWallet pointers**. My initial reaction was: `let's harmonize them by making them references`. However, not being part of the PR itself I did't change anything and completed the PR first.

Now, after having analyzed the `rpcwallet.cpp` code I came to the conclusion that:

* converting them all into references is not the solution as they're originally **shared_ptr**s
* but also: there is no (visible) reason why every RPC function should begin like this:

```cpp
std::shared_ptr<CWallet> const pwallet = GetWalletForJSONRPCRequest(request);
const CWallet* const pwallet = wallet.get();
```

This clearly defeats the purpose of shared pointers for no obvious reason. *Maybe I am missing something?*

In my (unpublished) [code changes](https://github.com/brakmic/bitcoin/commit/0b3ee615491edf6f542631bf6ae6f72eac406550) all raw pointers got replaced with **shared_ptr**s but kept their original names (that is, *pwallet*). In the end, they're pointers too, so the most of the original code remained untouched.

However, some of the helper functions couldn't be changed because external code is accessing them and I didn't want to make this task "virulent". So I introduced new ("Ref") variants that expect **shared_ptr** parameters, namely: 

```cpp
void EnsureWalletRefIsUnlocked(const std::shared_ptr<CWallet>);
bool EnsureWalletRefIsAvailable(const std::shared_ptr<CWallet>, bool avoidException);
```

I have tested the code, with python and boost-tests, and could not find any errors. 
But before opening a PR I would like to open a discussion about this. 

Is there any reason to keep on working with raw pointers when every function call actually begins with *shared_ptr*s?

Regards,

**Comment by promag** [comment]
See this thread https://github.com/bitcoin/bitcoin/pull/13063#discussion_r186740049. So feel free to submit that change.

In your commit you have:
```cpp
WalletRescanReserver reserver(pwallet.get());
```
IMO cases like this should be changed too - in this case to `*pwallet` - but it can be in another PR.

**Comment by brakmic** [comment]
> See this thread [#13063 (comment)](https://github.com/bitcoin/bitcoin/pull/13063#discussion_r186740049). So feel free to submit that change.
> 

Thanks.

Ok, will prepare it now.

> In your commit you have:
> 
> ```c++
> WalletRescanReserver reserver(pwallet.get());
> ```

Yes, and I tried to change it first, but then later realized that it affects various other code that's outside of rcpwallet.cpp. 

> 
> IMO cases like this should be changed too - in this case to `*pwallet` - but it can be in another PR.

Yes, maybe a PR dedicated to `WalletRescanReserver` only.

**Comment by promag** [comment]
This is not a bug.

**Comment by brakmic** [comment]
> This is not a bug.

True, but I found no better option for the issue. I'll gladly change it to something else.

**Comment by promag** [comment]
> IMO cases like this should be changed too - in this case to `*pwallet` - but it can be in another PR.

Done in #18601.
