### ISSUE TITLE
Organize the address types on the "Receiving addresses" tab

### ISSUE THREAD

**Issue by jonjonez** [bitcoin/bitcoin#18595]
As we generate new addresses, either bech32, p2sh-segwit, and legacy are all merged together into the receive address list. I'd be glad to divide the address types into options, as the following image suggests or something, if you have a better idea:
![bitcoin core](https://user-images.githubusercontent.com/23480437/79046873-b6a3b580-7be9-11ea-8a4e-4f38a36c550b.jpg)

e.g: when we use the command: importprivkey the bitcoin core will import the private key and the 3 address formats related to that private key in same window, it would be nicer if bitcoin core separated these addresses to make the interface cleaner. Do I just think that way?

Satoshi v0.19.1

**Comment by jonjonez** [comment]
Will this suggestion for improvement be taken into account or at least discussed?

**Comment by fanquake** [comment]
Moved to: https://github.com/bitcoin-core/gui/issues/646.
