### ISSUE TITLE
bitcoin-qt --help requires an X display even though it is not used

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#18602]
bitcoin-qt will fail if it does not have access to a functioning X display, even though when run with --help it doesn't need one.

(I'm having a go at fixing this today)

**Comment by rebroad** [comment]
The question is: should the command line instructions be displayed to stdout, or to the X display? Wasn't earlier functionality that it would be displayed in an X window?

**Comment by MarcoFalke** [comment]
You can click Help -> Command line options

**Comment by promag** [comment]
Why let it show the help without X if then it can't run? Just use `bitcoind`? 🙄

**Comment by jonasschnelli** [comment]
I think @rebroad is right that passing a -help via CMD should display the help in CMD **without** touching the window manager interface.

**Comment by fanquake** [comment]
I've moved this to the GUI repo: https://github.com/bitcoin-core/gui/issues/48.
