### ISSUE TITLE
test: Check hash in wait_for_get* helpers

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#18614]
Like it was done in 59d6249290, the `wait_for_get*` helpers should be extended to take in hashes and check them.

https://github.com/bitcoin/bitcoin/blob/59d62492900f6fc6ade2a780e75863ba3b254e06/test/functional/test_framework/mininode.py#L415

#### Useful skills:

Basic understanding of python and how to run the Bitcoin Core functional test suite

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by Nishikoh** [comment]
Could I tackle this issue?

**Comment by hebasto** [comment]
@Nishikoh 
> Could I tackle this issue?

Great!
> You do not need to request permission to start working on this.

**Comment by robot-visions** [comment]
Hi @Nishikoh , thanks for offering to tackle this!

Just checking, are you still interested in working on it?  If so, then I'll leave it to you :) but if not, I have some progress that I can upload.

**Comment by Nishikoh** [comment]
Hi @robot-visions
Sorry, this work is late. Would you upload it?  
Thanks.

**Comment by robot-visions** [comment]
Thanks @Nishikoh !  I uploaded some progress but it doesn't fully resolve the issue, so please feel free to continue working on this if you're still interested.

My first PR addresses the `wait_for_getdata` part.  However, there are still additional changes needed to fully resolve this issue:

- [ ] Update `wait_for_getheaders` to check the locator hash(es)
- [ ] Remove calls to `pop("getdata")` and `pop("getheaders")` that are no longer needed

I need to think more about the best way to identify the correct locator hash when calling `wait_for_getheaders`.  My initial attempt was to use the `getbestblockhash` RPC, but it seemed to cause too much of a slowdown.  I'd also welcome any discussion / suggestions about how best to approach this.

**Comment by Nishikoh** [comment]
I'm working on this issue, but I don't have a good idea and confidence.
Could you advise me on how to solve this issue?

**Comment by Nishikoh** [comment]
https://github.com/bitcoin/bitcoin/blob/9fb95ae8e3e4f10888a98fc99d704d97e2eb371f/test/functional/test_framework/mininode.py#L431

I'm working to modify `test_function` on `wait_for_getheaders`.
I'm thinking that I will modify it like the next code.

```.py
    def wait_for_getheaders(self, blockhash, timeout=60):
        """Waits for a getheaders message.

        Receiving any getheaders message will satisfy the predicate. the last_message["getheaders"]
        value must be explicitly cleared before calling this method, or this will return
        immediately with success. TODO: change this method to take a hash value and only
        return true if the correct block header has been requested."""

        def test_function():
            assert self.is_connected
            last_headers = self.last_message.get("getheaders")
            if not last_headers:
                return False
            return last_headers.hashstop == blockhash

        wait_until(test_function, timeout=timeout, lock=mininode_lock)
```
Is this idea correct?

**Comment by robot-visions** [comment]
Thanks for working on this @Nishikoh !  I think it's a good start.  To continue I would recommend:

- Look at [the protocol documentation for getheaders](https://en.bitcoin.it/wiki/Protocol_documentation#getheaders) to see what the various fields (including `hashstop`) are for
- Search for places where `wait_for_getheaders` is called and see what additional data you might pass in

**Comment by Nishikoh** [comment]
Thank you for your advice @robot-visions !
I will take your advice as a reference.

**Comment by Nishikoh** [comment]
I posted PR. What should I do anything else?
