### ISSUE TITLE
The gui doesn't handle exceptions very well

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18643]
The GUI crashes on exceptions such as `NonFatalCheckError`. I think it is more user friendly for a GUI to catch the exception and display it to the user, then abort the current action and leave the main window running.

I tested this by mutating the conditional in a `CHECK_NONFATAL`.

```
$ ./src/qt/bitcoin-qt 
QSocketNotifier: Can only be used with threads started with QThread


************************
EXCEPTION: 18NonFatalCheckError       
wallet/wallet.cpp:2636 (IsCurrentForAntiFeeSniping)
Internal bug detected: '!chain.findBlock(block_hash, FoundBlock().time(block_time))'
You may report this issue here: https://github.com/bitcoin/bitcoin/issues
       
bitcoin in Runaway exception       

terminate called after throwing an instance of 'NonFatalCheckError'
  what():  wallet/wallet.cpp:2636 (IsCurrentForAntiFeeSniping)
Internal bug detected: '!chain.findBlock(block_hash, FoundBlock().time(block_time))'
You may report this issue here: https://github.com/bitcoin/bitcoin/issues

Aborted (core dumped)
```

![Screenshot from 2020-04-14 21-11-32](https://user-images.githubusercontent.com/6399679/79288600-2a1d1f80-7e95-11ea-91f1-b91a633b05e8.png)

**Comment by MarcoFalke** [comment]
The RPC currently handles them nicely, by wrapping any exception into an JSONRPCError and returning from the call gracefully.

**Comment by MarcoFalke** [comment]
And unrelated: "Bitcoin can no longer continue safely" sounds interesting, but should probably be replaced by PACKAGE_NAME

**Comment by hebasto** [comment]
@MarcoFalke Mind looking into #18897?

**Comment by instagibbs** [comment]
Seems related: https://github.com/bitcoin/bitcoin/issues/18924

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/91.
