### ISSUE TITLE
Why is build_msvc separate from the doc folder?

### ISSUE THREAD

**Issue by saahilshangle** [bitcoin/bitcoin#18658]
**Is your feature request related to a problem? Please describe.**

As a new contributor, I was confused thinking that the build_msvc folder was the only source of build setup instructions.

**Describe the solution you'd like**

I think that moving the build_msvc README.md and related file set to the doc folder would make the setup process much clearer with all the options in one place.

**Describe alternatives you've considered**

Instead of moving build_msvc, retitling the doc folder to make it visually explicit that it contains build instructions would also be effective. 

**Additional context**

**Comment by MarcoFalke** [comment]
There is https://github.com/bitcoin/bitcoin/blob/master/INSTALL.md , but it is sort of hidden. 

I wouldn't mind if someone added a link to the main readme on how to build Bitcoin Core

**Comment by jasdeep9899** [comment]
I am doing a project and for that I need minimum 150 btc testnet coins... Can anyone help me please... My btc testnet wallet address is

mma9KKAAu32M5fJMchMoZJNB1xBJxJ5Z8c
