### ISSUE TITLE
Improve Windows CI experience

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18659]
Currently the Windows CI doesn't run the functional tests, see #18623 and fa50d11dd117eb6f91cbeac7476797f3885a6169

Also, it has been quite slow. On Linux a build with ccache finishes in a few minutes. On Windows it takes almost an hour, even with clcache. clcache apparently had no effect on the build time and has been removed in #18640 

If someone has background in Windows build systems, they could help us speed up the build or even enable the functional tests again.

Maybe the issue is with appveyor, so an option could be to port the appveyor yaml to travis or cirrus ci and see if that fixes the problem.

#### Useful skills:

Experience with Windows powershell and Windows build systems

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by hebasto** [comment]
Related reference: https://github.com/ccache/ccache/pull/506

**Comment by jasdeep9899** [comment]
I am doing a project and for that I need minimum 150 btc testnet coins... Can anyone help me please... My btc testnet wallet address is

mma9KKAAu32M5fJMchMoZJNB1xBJxJ5Z8c

**Comment by sipa** [comment]
@jasdeep9899 Stop spamming this repository.

**Comment by decryp2kanon** [comment]
> Maybe the issue is with appveyor, so an option could be to port the appveyor yaml to travis or cirrus ci and see if that fixes the problem.

agreed.
