### ISSUE TITLE
After a few clean shutdowns db always get corrupted

### ISSUE THREAD

**Issue by anoane** [bitcoin/bitcoin#18668]
Is there any improvements planned on db fault-tolerance ahead?

**Comment by MarcoFalke** [comment]
Bitcoin Core makes heavy use of CPU, RAM and disk IO. Hardware defects might only become visible when running Bitcoin Core. You might want to check your hardware for defects.

* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206

**Comment by jasdeep9899** [comment]
I am doing a project and for that I need minimum 150 btc testnet coins... Can anyone help me please... My btc testnet wallet address is

mma9KKAAu32M5fJMchMoZJNB1xBJxJ5Z8c

**Comment by adamjonas** [comment]
Closing since there has not been a follow-up and there haven't been other reports of this kind.
