### ISSUE TITLE
Rethink use of thread_local

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18678]
Merely compiling Bitcoin Core with thread_local seems to correlate with massively degraded performance for both the RPC and P2P interface on low-end machines. See for example:

* https://github.com/bitcoin/bitcoin/issues/18538#issuecomment-614885672
* Maybe #14669 
* Maybe #17247 

If thread_local really is the source of the performance degradation, it should be disabled by default and only enabled by `--enable-debug` (for use in lock order debugging).

**Comment by hebasto** [comment]
Could be relevant: https://stackoverflow.com/questions/13106049/what-is-the-performance-penalty-of-c11-thread-local-variables-in-gcc-4-8

**Comment by jasdeep9899** [comment]
I am doing a project and for that I need minimum 150 btc testnet coins... Can anyone help me ... My wallet address 

mma9KKAAu32M5fJMchMoZJNB1xBJxJ5Z8c

**Comment by laanwj** [comment]
Yes, it's onlly used in one place, given how static our thread setup is I think we could easily replace it with a map of thread id to name.

**Comment by MarcoFalke** [comment]
For some reason it seems to cause a slowdown from 6 minutes to 60 minutes. I don't know where that came from, but if caused by `thread_local`, this is unacceptable.

**Comment by laanwj** [comment]
It's only used in one place. Do we have statistics how often these are called?

Or does using `thread_local` at all, say, even in a place that is never called, add execution overhead throughout the entire program?

**Comment by laanwj** [comment]
Can someone suffering from (assumed) thread_local related performance issues please test  #18851?

**Comment by laanwj** [comment]
Closing as there is no thread_local issue (see https://github.com/bitcoin/bitcoin/issues/18538#issuecomment-623078397).
