### ISSUE TITLE
Allow a block to be "fully" reconsidered

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#18701]
Currently the reconsider logic doesn't fully reconsider a block it seems, at least not enough for the situation I created.

I was tinkering with the code, and I allowed ConnectBlock() to abort half-way through, but return true, so that ConnectTip() processed it as if ConnectBlock() was successful.

However, now the chain is being marked as invalid due to ConnectBlock() reporting inputs missing/spent on that same block.

I have tried marking it invalid (via RPC), asking it to be reconsidered, and even creating a new rpc to mark the block as not HAVE_DATA so that it got re-downloaded. All of these still end up with the inputs missing/spent issue.

Any ideas on how to allow the chain to continue downloading, aside from starting from genesis again?

Thank you!

**Comment by fjahr** [comment]
It sounds like you have created an inconsistent state, basically simulating corrupted data on disk. I would try to use `-reindex` first but I think that won't be enough and you need to delete the blk*.dat file that the block in question is in and then use `-reindex`.

**Comment by MarcoFalke** [comment]
This is not a support channel for modifications of Bitcoin Core.

**Comment by rebroad** [comment]
@MarcoFalke I think I discovered the cause. I was running v0.14.2, then ran a later version which upgraded the chainstate, and then when running v0.14.2 again it gives these errors.
