### ISSUE TITLE
Allow JSON RPC "batches" for multiwallet

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#18715]
Currently, batching RPC requests across wallets does not work due to the fact that each wallet has its own endpoint. This results in relatively slow processing speed if a client queries multiple wallets.

See discussion in #18453 ([this](https://github.com/bitcoin/bitcoin/pull/18453#issuecomment-611385534) and [this](https://github.com/bitcoin/bitcoin/pull/18453#issuecomment-616726869)).

There are probably multiple approaches how to improve that:
* The `foreachwallet` RPC meta call that takes the actual call/arguments as parameters.
* A `/foreachwallet` http endpoint
* Add `allwalletsXXX` rpc calls (like `getallwalletsbalance` or getwallet**s**balance
* ... (more?)

**Comment by jonatack** [comment]
Yes, I am looking at this and made a [twitter poll here](https://twitter.com/jonatack/status/1252357067181969416?s=20) for ideas; two suggestions were `-rpcwallet=*` by @harding [here](https://twitter.com/hrdng/status/1252386345550405634?s=20) and the ability to specify multiple wallets with -rpcwallet by @jb55 [here](https://twitter.com/jb55/status/1252368608237244429?s=20).

**Comment by jonatack** [comment]
As a first step, #18594 is also ready; it adds displaying multiwallet balances for all loaded wallets in `-getinfo` when more than one wallet is loaded (e.g. when you are in "multiwallet mode") and `-rpcwallet=` is not passed.

**Comment by jb55** [comment]
> * The `foreachwallet` RPC meta call that takes the actual call/arguments as parameters.
> * A `/foreachwallet` http endpoint

:+1: or even `/wallets` or `/allwallets` ?

> * Add `allwalletsXXX` rpc calls (like `getallwalletsbalance` or getwallet**s**balance

would this be necessary? I was thinking all you would need is to group the results in a object using the wallet name as a key.

if you wanted to get more fancy, you could define a way to aggregate the results of each command client-side (what the cool Haskell kids call a monoid/semigroup). Perhaps enabled with a switch.

**Comment by MarcoFalke** [comment]
If we add an RPC for this server side, my wish would be to make it a single one, and not duplicate every RPC method from foobar to allwallets_foobar. If there was a single `foreachwallet` RPC, the list of wallets could be passed in (otherwise it defaults to all wallets).
