### ISSUE TITLE
feature_fee_estimation is failing intermittently

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18737]
There are numerous intermittent failues, such as

* mempool sync failures
* Fee estimation logic errors such as `AssertionError: Estimated fee (0.000565) larger than last fee (0.000478) for lower number of confirms`
* ...

**Comment by practicalswift** [comment]
I'm afraid the intermittent larger than life^H^H^Hast fee issue in `feature_fee_estimation.py` is here again.

From https://cirrus-ci.com/task/4938320209772544?command=ci#L1376:

```
AssertionError: Estimated fee (0.000400) larger than last fee (0.000338) for lower number of confirms
```

**Comment by practicalswift** [comment]
Unfortunately this larger than life^H^H^Hast fee issue in `feature_fee_estimation.py` keeps popping up.

From https://cirrus-ci.com/task/4756253495787520:

```
AssertionError: Estimated fee (0.000400) larger than last fee (0.000338) for lower number of confirms
```

Should this issue be re-opened?

**Comment by MarcoFalke** [comment]
#20725 duplicate
