### ISSUE TITLE
Pick up "transaction fees in getblock" pull request

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18771]
#16083 has been abandoned, so it would be a good first issue to take the branch (https://github.com/bitcoin/bitcoin/pull/16083#issuecomment-570842798) and submit it as a new pull request.

#### Useful skills:

Understanding of undo data, the RPC interface and the functional tests.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by robot-visions** [comment]
I think this is a nice idea.  However, I spent some time looking into the details, and I'm leaning slightly towards Concept NACK for the following reasons:

- By using undo data, we would only be able to calculate and display fees for blocks that are on the active chain; a user might find this unintuitive

- The documentation for `getblock` says the transactions are "in the format of the getrawtransaction RPC":

	- If we don't update `getrawtransaction` then the API might become more confusing
	- If we do update `getrawtransaction`, the performance penalty could be high, since the cost of loading undo data is no longer amortized across many transactions in a block

What do you all think?  Is it still worth the benefit of showing fees for blocks on the active chain?

**Comment by robot-visions** [comment]
I've started working on this (see #18772); however, I have a question.

The documentation for `getblock` refers to the tx format of `getrawtransaction`.  What's the most reasonable approach here?

- Also update `getrawtransaction` (and the documentation) to calculate a fee if possible (this might be slow since the cost of loading undo data is no longer amortized over many transactions in a block)
- Update the `getblock` documentation to mention that it might also include fees (which aren't in `getrawtransaction`)
- Leave the documentation alone and let the unfortunate user figure out the semantics themselves :)

**Comment by RishabhBajaj97** [comment]
Hey! 
I would like to contribute here but since I am a first timer to open source projects i would need some guidance

**Comment by azsxcv11060** [comment]
https://github.com/bitcoin/bitcoin/issues/18771#issuecomment-620178477

**Comment by christiangirl41** [comment]
#19056

**Comment by monokh** [comment]
It would seem natural for `getrawtransaction` with `verbosity=true` to also return `fees`?

Is this something to be addressed in #18772 or a separate issue/PR? Just noticed that #13108 was merged into this issue but subsequently no reference to that aspect (`getrawtransaction`)

**Comment by ycshao** [comment]
@RishabhBajaj97 are you still working on this? If not, I can pick it up.

**Comment by ycshao** [comment]
Looks like @robot-visions is already working on this in #18772 .

**Comment by MarcoFalke** [comment]
verbosity=2 is still up for grabs here

**Comment by fyquah** [comment]
I'd look to look at this. @MarcoFalke , though, did you mean verbosity=3 ?

**Comment by MarcoFalke** [comment]
I mean the next verbosity level, whatever that may be

**Comment by fyquah** [comment]
Is there an issue referencing specifically what should be added to this verbosity level?

**Comment by niVelion** [comment]
Was this closed by https://github.com/bitcoin/bitcoin/pull/22918?

**Comment by jekyleee** [comment]
Thx
