### ISSUE TITLE
intermittent test failure "non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation) (-26)"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18803]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/680452476#L6107

**Comment by MarcoFalke** [comment]
Another one:

* https://travis-ci.org/github/bitcoin/bitcoin/jobs/686121971#L8152

**Comment by hebasto** [comment]
And more:
- https://travis-ci.org/github/bitcoin/bitcoin/jobs/700164858#L3375

**Comment by practicalswift** [comment]
Another fourth one - this time in `wallet_importdescriptors.py`:
* https://travis-ci.org/github/bitcoin/bitcoin/jobs/701586452

The error message in all four cases is:

```
JSONRPCException: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation) (-26)
```

**Comment by MarcoFalke** [comment]
Another one https://github.com/bitcoin/bitcoin/pull/16795#issuecomment-673205323 ...
