### ISSUE TITLE
depends: Evaluate potential improvements

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#18821]
There are a couple of things we can do to make our `depends` Makefile-based system more robust. A couple that have been in my head to potentially explore:

1. Some functionality that are not directly related to prerequisites producing targets could perhaps be simplified if delegated to scripts
2. Eliminating builtin rules and variables e.g. `MAKEFLAGS += --no-builtin-variables`: I've tried this, and it breaks libminiupnpc because it relies on builtin rules.
3. Require a recent-ish bash so that we can use `set -euo pipefail` and catch errors early

A lot of this is from: https://tech.davis-hansson.com/p/make/ (ignore the title)

**Comment by willcl-ark** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Pull requests with improvements are always welcome.

**Comment by hebasto** [comment]
>    2. Eliminating builtin rules and variables e.g. `MAKEFLAGS += --no-builtin-variables`: I've tried this, and it breaks libminiupnpc because it relies on builtin rules.

See https://github.com/bitcoin/bitcoin/pull/33045.
