### ISSUE TITLE
qt: Close All Wallets menu option should be available

### ISSUE THREAD

**Issue by brakmic** [bitcoin/bitcoin#18845]
**Currently, the File menu offers no option to close all loaded wallets at once.** 

In cases where users have many (+5) wallets loaded, the usual... 

*Open File Menu* **->** *Select Close Wallet* **->** *Answer MsgBox Question with YES* 

...can quickly become very unpleasant.

Therefore, I'd recommend to implement a new menu option, **Close All Wallets**, that can:

* Close all loaded wallets,
* but still offers the *do-you-want-to-close-this-wallet* option, in cases where only certain wallets should be closed,
* and is disabled, when there are no wallets loaded.

### UI

![close-all-wallets-menu-option](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/close-all-wallets-menu-option.png)

![close-all-wallets-automatically](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/close-all-wallets-query.png)

![close-all-wallets-disabled](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/close-all-wallets-disabled.png)

### Demo Code

I have implemented a [variant that's showcasing a possible solution](https://github.com/brakmic/bitcoin/commit/b9ffc52402e147a8e7550fcd95db2902fc2828cc), but because I:

* don't know about possible reasons to **not** include an option like this
* am not sure, if there are maybe similar solutions in the making (*have checked commit history a bit, but not thorough enough to be sure*)
* would like to know how to make a proper Qt test for it, before making a PR out of it.

Regards,

**Comment by fanquake** [comment]
This looks the same as #15202.

**Comment by hebasto** [comment]
> This looks the same as #15202.

While doing this, we should care about not creating new synchronous calls.

**Comment by brakmic** [comment]
> This looks the same as #15202.

Thanks, will then continue there.

**Comment by promag** [comment]
@brakmic thanks, didn't update/push my PR due to some lack of interest but I'll do it shortly then.

> we should care about not creating new synchronous calls.

@hebasto what do you mean?

**Comment by hebasto** [comment]
@promag 
> > we should care about not creating new synchronous calls.
> 
> @hebasto what do you mean?

I mean do not block/freeze the GUI :D
