### ISSUE TITLE
Ubuntu 20.04 BDB 4.8 compile issues 

### ISSUE THREAD

**Issue by BlockMechanic** [bitcoin/bitcoin#18846]
Hello

Decided to setup a new node on ubuntu 20.04 , build is impossible to continue because BDB 4.8 fails with 
`In file included from ../dist/../dbinc/mutex_int.h:12,
                 from ../dist/../dbinc/mutex.h:15,
                 from ./db_int.h:884,
                 from ../dist/../cxx/cxx_db.cpp:11:
../dist/../dbinc/atomic.h:179:19: error: definition of ‘int __atomic_compare_exchange(db_atomic_t*, atomic_value_t, atomic_value_t)’ ambiguates built-in declaration ‘bool __atomic_compare_exchange(long unsigned int, volatile void*, void*, void*, int, int)’
  179 | static inline int __atomic_compare_exchange( `

I was manually building with this command `cd db-4.8.30/build_unix; ../dist/configure --prefix=/usr/local --enable-cxx ; make`

**System information**
8 core 
16GB ram
Ubuntu 20.04
1TB SSD

**Comment by fanquake** [comment]
You'll need to apply the same patches that we do (for c++11) when building bdb: https://github.com/bitcoin/bitcoin/blob/master/depends/packages/bdb.mk#L17.

I'd suggest using the [install_db4.sh](https://github.com/bitcoin/bitcoin/blob/master/contrib/install_db4.sh) script, as this automates this process.

**Comment by BlockMechanic** [comment]
Oh, ok. Thanks
