### ISSUE TITLE
./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 erro

### ISSUE THREAD

**Issue by Vicentcoin** [bitcoin/bitcoin#18852]
checking whether the linker accepts -Wl,--exclude-libs,ALL... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
checking for dynamic linked boost test... no
checking openssl/crypto.h usability... no
checking openssl/crypto.h presence... no
checking for openssl/crypto.h... no
configure: error: libcrypto headers missing
please help me

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by hebasto** [comment]
@Vicentcoin 
Mind providing system details?

**Comment by nicebbs** [comment]
> 最新版本的Bitcoin Core还是这个问题吗？如果是，复制的步骤是什么？

The dependencies version is the latest, bitcoin's code is old

**Comment by nicebbs** [comment]
> @Vicentcoin
> Mind提供系统详细信息吗？

The dependencies version is the latest, bitcoin's code is old
