### ISSUE TITLE
s390x build fails on travis with "out of disk space"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18868]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/682858666#L336

I think it should be removed again

**Comment by MarcoFalke** [comment]
This has been happening for the last couple of days

**Comment by laanwj** [comment]
oh no not this again

**Comment by MarcoFalke** [comment]
Left a comment in the upstream issue, which is open since Nov'19

https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954/16

**Comment by MarcoFalke** [comment]
I recommend to remove the test in the next few days. I don't expect travis to respond to our issues.

**Comment by MarcoFalke** [comment]
I think we have 1 month left on our travis invoice. Longer term we should look into moving away from travis if they can't offer us the quality we need.
