### ISSUE TITLE
qt: function filterAcceptsRow seems to be unused

### ISSUE THREAD

**Issue by brakmic** [bitcoin/bitcoin#18860]
I have read in @practicalswift 's Issue https://github.com/bitcoin/bitcoin/issues/18858 that there was an unused function found, so I thought, I could maybe also run a few simple searches through the code. Just for the sake of learning. For that I used *cppcheck*.

```cpp
cppcheck --enable=unusedFunction src/qt
```

Of course, there are many false positives, but one function seems to be lying dormant for quite a long time: [filterAcceptsRow](https://github.com/bitcoin/bitcoin/blob/master/src/qt/transactionfilterproxy.h#L55) from **qt/transactionfilterproxy.cpp**.

Also, there is another one in [addressbookpage.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/qt/addressbookpage.cpp#L38). However, this one seems to have only a definition. I could not find its corresponding class member declaration. Not sure why, but there isn't one in [addressbookpage.h](https://github.com/bitcoin/bitcoin/blob/master/src/qt/addressbookpage.h).

Another interesting aspect is, that **filterAcceptsRow** from **transactionfilterproxy.cpp** was present since 0.15, without ever having been used, if I am not mistaken. And there were no changes until 0.17, when the other variant from **addressbookpage.cpp** got implemented. 

I don't understand the reasons, and it could be that I am simply missing the forest for the trees, but I could compile, run and also qt-test [my modified code](https://github.com/brakmic/bitcoin/commit/fa7f54c2dba75b8a81ed6e3d2bdeb8330942ff0b) without any failure. That is, without having compiled **filterAcceptsRow** in both of the classes.

However, before opening a PR, I would like to ask experienced people for advice. Is there anything that I might have been missed? Do these functions maybe exist for testing purposes only?

Regards,

**---EDIT:** 

_There are a few more of them, but I did not check them thoroughly. Will have to recompile/retest the code first._

```shell
src/qt/rpcconsole.cpp:123:0: style: The function 'Name' is never used. [unusedFunction]

^
src/qt/rpcconsole.cpp:124:0: style: The function 'NewTimer' is never used. [unusedFunction]

^
src/qt/bitcoinamountfield.cpp:45:0: style: The function 'fixup' is never used. [unusedFunction]

^
src/qt/bitcoinamountfield.cpp:67:0: style: The function 'stepBy' is never used. [unusedFunction]

^
src/qt/bitcoinamountfield.cpp:167:0: style: The function 'stepEnabled' is never used. [unusedFunction]
```

**Comment by MarcoFalke** [comment]
The function is virtual, see https://doc.qt.io/qt-5/qsortfilterproxymodel.html#filterAcceptsRow

**Comment by brakmic** [comment]
> The function is virtual, see https://doc.qt.io/qt-5/qsortfilterproxymodel.html#filterAcceptsRow

Ok, now I understand. 
Before C++11 there was no **override** keyword so it was a bit harder to distinguish between such functions and non-overridden ones.

**Comment by promag** [comment]
`TransactionFilterProxy::filterAcceptsRow` is called when any model filter is changed (when `invalidateFilter` is called). For instance see `TransactionFilterProxy::setSearchString`.

**Comment by brakmic** [comment]
> `TransactionFilterProxy::filterAcceptsRow` is called when any model filter is changed (when `invalidateFilter` is called). For instance see `TransactionFilterProxy::setSearchString`.

Yes, I see it. In several places. Qt Framework magic. 
Thanks for the explanation. 
Maybe it should be written down, somewhere, like a Qt/UI-doc.

**Comment by practicalswift** [comment]
@brakmic If you want to investigate unused functions generally in our code base then you might want to take a look at https://github.com/bitcoin/bitcoin/pull/18670#issuecomment-616422799 :)

**Comment by brakmic** [comment]
> @brakmic If you want to investigate unused functions generally in our code base then you might want to take a look at [#18670 (comment)](https://github.com/bitcoin/bitcoin/pull/18670#issuecomment-616422799) :)

Wow, that's an impressive collection you have there. :)
Many thanks!

**Comment by promag** [comment]
Having `override` would be nice. I think this can be closed.

**Comment by practicalswift** [comment]
@brakmic 

> Wow, that's an impressive collection you have there. :)

Please note that it only a subset all unused functions.

Proof: `CCoinsViewCache::GetValueIn(…)` was missed in the list :)

**Comment by hebasto** [comment]
@promag 
> Having `override` would be nice. I think this can be closed.

Do you mean #16710? :smiley:
