### ISSUE TITLE
On windows 10 most of the time the wallet is in the - (not responding) mode, please tell me what to do

### ISSUE THREAD

**Issue by Yoperok** [bitcoin/bitcoin#18886]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by Yoperok** [comment]
version 0.19.1

**Comment by promag** [comment]
Is this right after installing? Any previous version worked fine?

**Comment by Yoperok** [comment]
> Это сразу после установки? Любая предыдущая версия работала нормально?

version 0.18 worked well, on Windows 7, after upgrading to 0.19 and problems started, and when I switched from Windows 7 to 10 it generally became very slow, when I started troubleshooting compatibility issues, it indicates that the product is designed for Windows 8...

**Comment by bvbfan** [comment]
What's the size of wallet.dat, it's placed in bitcoin data directory.

**Comment by Yoperok** [comment]
> Каков размер wallet.dat, он находится в каталоге данных биткойнов.

1 585 340 bytes

**Comment by bvbfan** [comment]
Possible fix in #18904 
You can clone https://github.com/bvbfan/bitcoin/tree/lsn_reset_fix and follow instructions how to compile it.

**Comment by Yoperok** [comment]
I solved the problem by installing the previous version 0.18.1
everything works without problems, not knowing English and the programming language, I think it's hard to figure it out by following the instructions, thank you all for the feedback))

**Comment by bvbfan** [comment]
The code is same, issue present on 0.17.x as well. I don't want to bother you but using older unsupported version is not recommended.

**Comment by Yoperok** [comment]
> Код такой же, проблема присутствует и на 0.17.x. Я не хочу вас беспокоить, но использовать старую неподдерживаемую версию не рекомендуется.

what can go wrong when using the old version?

**Comment by bvbfan** [comment]
Many things can go wrong :) Since hard forks (the biggest stopper) are not often used, now days, using older version can lead to security risk, supported versions receive security fixes which may or may not present in older one.

**Comment by bitcoinlover2021** [comment]
Same here.. it's almost unusable.. Not responding most of the time.. same as previous version.
So now i'm gonna transfer to another wallet because i'm really pi.. off. Please fix this (for real)

**Comment by adamjonas** [comment]
@bitcoinlover2021 It would be easier to address the issue if you could provide the steps to reproduce. What version does this refer to? Is this right after installing? Have previous versions worked better? What is the size of the wallet?

**Comment by adamjonas** [comment]
Closing this issue for lack of response and reproducible steps.
