### ISSUE TITLE
Make guix build developer friendly

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18893]
The guix builds are primarily used for generating the release binaries. However, to make the version that is run by developers closer to the release binaries, and also to make it easier for developers to test different versions of dependencies, guix should be made more developer friendly. I think this mostly needs a folder mounted in to the guix container to propagate ccache results in and out.

Thoughts?

**Comment by dongcarl** [comment]
It is possible to create a `guix environment` without the restriction of containers... I have a branch I've been working on, will resurrect that and see how it works out!

Looking at an experience close to python's virtualenv:

```sh
./contrib/guix/env.sh  # builds environment, sets env vars, and execs $SHELL
./autogen.sh
./configure
make -j"$(nproc)" check
# Ctrl-D to exit environment
```

**Comment by monperrus** [comment]
Hi @dongcarl, all,

It seems that `curl` is missing in the guix environment, while it is required to run `bash contrib/guix/libexec/build.sh`.

In other terms, I cannot work with `guix environment --manifest=contrib/guix/manifest.scm --pure`, I have to rely on a curl binary provided by the host  (list of all pure binaries at https://gist.github.com/monperrus/815fdb95edceb6bf9aaba29ee549f189)

Am I missing something?

Thanks!
