### ISSUE TITLE
builds: Review use of `@`-prefixed lines in our Makefiles

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#18891]
From https://www.gnu.org/software/make/manual/make.html#Echoing:

> Normally `make` prints each line of the recipe before it is executed. We call this _echoing_ because it gives the appearance that you are typing the lines yourself.
> 
> When a line starts with ‘`@`’, the echoing of that line is suppressed. The ‘`@`’ is discarded before the line is passed to the shell. Typically you would use this for a command whose only effect is to print something, such as an `echo` command to indicate progress through the makefile:
> 
> ```Makefile
> @echo About to make distribution files
> ```

Since there is no way to turn off the `@`-prefix behaviour other than giving the `--just-print` flag (which puts `make` in dry-run mode and thus does not always work properly), we should make sure that we only put `@` where we mean to for debuggability's sake. **In practice, this probably means using `@`-prefix only when we're `@echo`-ing.**

-----

For example:
https://github.com/bitcoin/bitcoin/blob/fbd522721cb89ef0efea0c1bc912c00b268d1c2a/Makefile.am#L83-L85

Will silence the printing of `$(MAKENSIS) -V2 $(top_builddir)/share/setup.nsi`, which might be useful information. In fact, this whole snippet could just be:

```Makefile
	$(MAKENSIS) -V2 $(top_builddir)/share/setup.nsi
```

-----

Let me know what you think!

**Comment by ruhi1999** [comment]
I'd like to work on this!

**Comment by dongcarl** [comment]
@ruhi1999 Sounds good, I'd be happy to review once a PR is up.

**Comment by hebasto** [comment]
More exact link: https://www.gnu.org/software/make/manual/make.html#Echoing

:)

**Comment by development-lab** [comment]
So wonderful apps

**Comment by preeti13456** [comment]
I would be interested to work on this issue

**Comment by MarcoFalke** [comment]
@preeti13456 No need to ask for permission if you want to work on an issue. You can just go ahead and open a pull request once you are done.

**Comment by hebasto** [comment]
Related to #22283.

**Comment by annahubbard** [comment]
Hey! I am interested in solving this issue! I see a description of the @ and echo functionality within a makefile. Are you suggesting that the bitcoin/Makefile.am file remove the @ prefix for the test command since it seems to be best practice that @ is only used to preface echo? Any clarity would be great as I am looking to learn about bitcoin core and makefiles but am unclear on the issue at hand to be solved.

**Comment by TheCharlatan** [comment]
Related to #27041,

**Comment by TheCharlatan** [comment]
With #27041 merged, I checked the remaining few instances and think they all serve a purpose, so I think this could be closed now.
