### ISSUE TITLE
Bitcoin core 0.19.1 RPC, 'sendtoaddress' not working!

### ISSUE THREAD

**Issue by emonorg** [bitcoin/bitcoin#18906]
Suppose this scenario:

> There are 2 wallets called `wallet1` and `wallet1` on the same node in `testnet` blockchain.

> `wallet1` balance: 0.001 BTC

> `wallet2` balance: 0 BTC

I am trying to send 0.001 BTCs from `wallet1` to `wallet2`; so I use the `sendtoaddress` command like this:

`bitcoin-cli -testnet -rpcwallet=wallet1 sendtoaddress <wallet2 address> 0.001 "" "" true`.

This gives me a `txid` which none of the blockchain explorers like [live.blockcypher.com/btc-testnet][1] can't recognize it!

> It deducts the coin from `wallet1` and I don't know where does it go!?

For solving this, I tried to get the transaction hex to broadcast it via some other platforms to check if the raw transaction is correct and it was OK and after broadcasting it via the other platform, blockchain explorers could detect the transaction id. 

Here are my question:

1. Isn't just using `sendtoaddress` enough for sending coins?
2. Why the broadcasting process doesn't complete on my node?

Here is my `bitcoin.conf`: 
```
[test]
prune=600
blocksonly=1
maxconnections=15
testnet=1
regtest=0

deprecatedrpc=accounts
deprecatedrpc=addwitnessaddress
deprecatedrpc=signrawtransaction
deprecatedrpc=validateaddress

minrelaytxfee=0.0001
maxmempool=200
maxreceiverbuffer=2500
maxsendbuffer=500
dbcache=16000

rpcbind=0.0.0.0
rpcallowip=--

rpcuser=--
rpcpassword=--

server=1
rest=1
daemon=1

```

  [1]: https://live.blockcypher.com/btc-testnet

**Comment by brakmic** [comment]
@emonorg 

The entry `testnet=1` should be outside of `[testnet]` block.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
