### ISSUE TITLE
import* wallet RPCs don't "rescan" the mempool

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18954]
Steps to reproduce:

* Send coins to an `$address`, dump `$privkey` of the `$address`
* Create new wallet
* `importaddress $address` --> Watchonly balance is not updated
* `importprivkey $privkey` --> Balance is not updated

Needs a restart to get fixed. See also #11477

**Comment by promag** [comment]
Submitted #18964 to address this.
