### ISSUE TITLE
RPC gettransaction() wrong sending address on internal transaction

### ISSUE THREAD

**Issue by Nex4rius** [bitcoin/bitcoin#18951]
**Expected behavior**
The correct sending address in the transaction.

**Actual behavior**
I made a transaction between 2 address in my wallet and then checked it with the gettransaction() function and the txid. It reported that the receiving address also sent the coins.

I can see in the testnet block explorer that transaction did in fact happen correctly. https://live.blockcypher.com/btc-testnet/tx/37e37cb8add45cc234f0d8f530ddd1346404be5da14a4ce125748dd13094aaea/

I sent from
tb1qutv5a8vxthm6rqgfjexzvz3p49fyls74hj4zzu -> tb1q0yempvk7fwqz2k9j6utkkkuyt7fqznqjwplkhu

but the  gettransaction() function is reporting this: https://i.imgur.com/TwiYPiC.png
tb1q0yempvk7fwqz2k9j6utkkkuyt7fqznqjwplkhu -> tb1q0yempvk7fwqz2k9j6utkkkuyt7fqznqjwplkhu

**To reproduce**
Make an internal transaction and put the txid into this:
https://gist.github.com/Nex4rius/47f4c2959d1d29cf51bac6bd4054d323

**System information**

Bitcoin Core Version v0.19.0.1 (64-Bit)

Window 10

I've noticed that this also affects the listtransactions() function.

**Comment by MarcoFalke** [comment]
The receiving address (`tb1q0`) and the destination where the funds were sent to previously (`tb1qu`) are both controlled by your wallet, so it correctly tells you that this transaction involved a send as well as a receive.

**Comment by Nex4rius** [comment]
That's not what I mean. I know that it has a send aswell as a receive.

Both the send and receive address are shown to be (tb1q0) but the sending address is in reality (tb1qu).

The (tb1qu)  address isnt mention at all in this transaction from gettransaction().

**Comment by MarcoFalke** [comment]
There is no "send address" or "from address"

https://en.bitcoin.it/wiki/From_address

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
