### ISSUE TITLE
Is the text/plain header truly required?

### ISSUE THREAD

**Issue by trinityXmontoya** [bitcoin/bitcoin#18950]
I already asked this on https://bitcoin.stackexchange.com/ and was referred here.

The docs say "RPC HTTP requests must include a `Content-Type` header set to `text/plain`" (src: https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs). Calls to an RPC endpoint without this header succeed. Either way, the true `Content-Type` in this case is `application/json`. ~Every version of the docs published so far specifies this requirement.

Is it safe for me to remove it or could it cause unexpected behavior? I can imagine none. I am happy to open a PR removing this requirement from the docs if it's not needed.

**Comment by MarcoFalke** [comment]
https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs

The website is managed on https://github.com/bitcoin-dot-org/bitcoin.org or https://github.com/achow101/btcinformation.org

**Comment by MarcoFalke** [comment]
Is this also an issue with Bitcoin Core?

**Comment by trinityXmontoya** [comment]
Thanks for your speedy response!

The documentation at both links you provided also states this same header requirement ([here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_data/devdocs/en/bitcoin-core/rpcs/intro.md#remote-procedure-calls-rpcs) and [here](https://github.com/achow101/btcinformation.org/blob/master/_data/devdocs/en/bitcoin-core/rpcs/intro.md#remote-procedure-calls-rpcs)). I'm just trying to understand if it's actually a requirement, in practice it does not seem to be.

**Comment by laanwj** [comment]
No, there is no strict requirement for JSON-RPC to have `Content-Type` header set to `text/plain`. I think `application/json` is more common, and also more relevant.

FWIW bitcoin core uses `application/json` everywhere, at least in the server, I couldn't find any code in `bitcoin-cli` to set that header. In any case the server doesn't enforce any specific content type so it doesn't matter.

**Comment by MarcoFalke** [comment]
It might be best to report the bug upstream to the websites https://github.com/bitcoin-dot-org/bitcoin.org and/or https://github.com/achow101/btcinformation.org

**Comment by laanwj** [comment]
I don't think there's a need to keep this open. Things work, there's no actual issue.

If you have any further questions feel free to ask though.
