### ISSUE TITLE
Intermittent error in feature_backwards_compatibility: "Mempool sync timed out after 60s"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18969]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/685918202#L8806

**Comment by hebasto** [comment]
The same error on in `feature_notifications.py`:
https://travis-ci.org/github/bitcoin/bitcoin/jobs/696319863#L2988

**Comment by hebasto** [comment]
https://bitcoinbuilds.org/?job=7259a492-0e7a-45e1-af96-2d6d20c38862
