### ISSUE TITLE
build: improve build OS configure output

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#18966]
We include the target and build OS as part of our `Options used to compile and link:` which is printed after running `./configure` i.e:

Building for macOS on macOS
```bash
  target os     = darwin
  build os      = darwin
```

Building for Windows on Linux
```bash
  target os     = windows
  build os      = 
```

Building for Linux on Linux
```bash
  target os     = linux
  build os      = 
```

Notice `build os` is currently only ever set when building for darwin (host or cross-compile). This is because it's the only target for which we actually set the `$BUILD_OS` variable for in configure (It's used to set `BUILD_DARWIN` which is then used in our makefiles).

We could improve this so that a build and target os are always printed for all build combinations. Feel free to ping me if you have any Qs.

**Comment by RishabhBajaj97** [comment]
Heyy! I wanted to contribute to this repository! Can you tell me how exactly do i do that?

**Comment by sachinkm77** [comment]
@fanquake can I work on this one?

**Comment by fanquake** [comment]
> @fanquake can I work on this one?

Yes, go ahead.

**Comment by sachinkm77** [comment]
@fanquake had a quick question. I can see where we need to set the BUILD_OS at various places in configure ac, but not sure on what would be executed be if say BUILD_LINUX (new variable)  is set (in Makefile am) similar to BUILD_DARWIN (am conditional). do let me know if I'm on the right track

**Comment by fanquake** [comment]
> @fanquake had a quick question.

My thoughts were something a bit simpler, just swapping out the `$BUILD_OS` var here:

https://github.com/bitcoin/bitcoin/blob/9e8bd217cd2a3437ce7c8fc7f04a61a3aee5268c/configure.ac#L1755
 to use the `$build_os` variable that's set by config.guess/config.sub. Then we don't have to add any extra code, and will get more exact/informative build OS output than what we would create on our own.

**Comment by skmcontrib** [comment]
@fanquake thanks for your suggestion. here is what I tried and corresponding output of the 2 examples tried

https://github.com/skmcontrib/bitcoin/commit/7dcebec709c1d7ece15d48d42baf6a47132e47e2#diff-67e997bcfdac55191033d57a16d1408a

target windows and build linux
------------------------------------
target os     = windows
  build os      = linux
******************************
target linux build linux
------------------------
  target os     = linux
  build os      = linux

**Comment by fanquake** [comment]
@skmcontrib I may have been unclear, the change I'm suggesting is just:

```diff
diff --git a/configure.ac b/configure.ac
index 3d8291bf5..f2f053dab 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1752,7 +1752,7 @@ echo "  gprof enabled = $enable_gprof"
 echo "  werror        = $enable_werror"
 echo
 echo "  target os     = $TARGET_OS"
-echo "  build os      = $BUILD_OS"
+echo "  build os      = $build_os"
 echo
 echo "  CC            = $CC"
 echo "  CFLAGS        = $CFLAGS"
```

`config.sub` is already doing the work of figuring out the build OS, so we might as well use that. It will also give as more useful output  i.e `linux-gnu` or `linux-musl` rather than just `linux`.

**Comment by skmcontrib** [comment]
@fanquake thanks for the clarification, I see what you are saying now and that makes sense. Leveraging the existing config.sub is a good idea. Also outputting the whole build os makes it more useful.
Here is the output of the same cases tried earlier. Will raise a PR if you are ok.

--------------------------------
target os     = linux
  build os      = linux-gnu
--------------------------------
 target os     = windows
  build os      = linux-gnu

**Comment by fanquake** [comment]
> Will raise a PR if you are ok.

Yea that looks fine. Feel free to open a PR. Make sure you also check out [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md).
