### ISSUE TITLE
build: [0.22] Enable -Wdeprecated-copy warnings

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18967]
For 0.22 we should look into enabling the warning again, which has been disabled in #18738

**Comment by laanwj** [comment]
Is this still to be addressed before 22.0?

**Comment by MarcoFalke** [comment]
I haven't checked if Ubuntu fixed this in the meantime (looks like qt abandoned the backport), but maybe we can apply the warning only when suppress-external is set?

**Comment by hebasto** [comment]
> ... maybe we can apply the warning only when suppress-external is set?

Something like https://github.com/bitcoin/bitcoin/pull/21667/commits/ebe68bd4c5ca030ec601f9bd1e8ca20cf8d9356b?

**Comment by hebasto** [comment]
Done in #22240.
