### ISSUE TITLE
Add CI job that runs unit tests under rr's chaos mode

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#18979]
As noted in https://github.com/bitcoin/bitcoin/issues/16337#issuecomment-629041023 `rr`'s chaos mode can be used to trigger some classes of intermittent bugs in unit tests (such as bugs related to scheduling non-determinism).

It would be nice to have a CI job running under chaos mode to increase the likelihood of us finding such issues.

I think this is a "good first issue" :)

---

Context for those new to `rr` and its "chaos mode":

> rr aspires to be your primary C/C++ debugging tool for Linux, replacing — well, enhancing — gdb. You record a failure once, then debug the recording, deterministically, as many times as you want. The same execution is replayed every time. -- https://rr-project.org/

> Chaos mode to make intermittent bugs more reproducible. -- https://robert.ocallahan.org/2016/02/introducing-rr-chaos-mode.html

Personally I think `rr` is a **fantastic** piece of software which is right up there with projects such as `libFuzzer` and the sanitizers (ASan, MSan, TSan, UBSan) when it comes to its potential to help us produce robust and secure software. Highly recommended!

**Comment by ScaredIbis** [comment]
keen to give this a crack

**Comment by MarcoFalke** [comment]
I don't think this works. Is there any ci provider out there that comes with `rr` support?

```
dmesg | grep PMU
[    0.519557] Performance Events: unsupported p6 CPU model 63 no PMU driver, software events only.

**Comment by MarcoFalke** [comment]
Closing for now. `rr` is only supported on specific intel CPUs. AMD ryzen or any virtual CPU is not supported.
