### ISSUE TITLE
Investigate where std::string should be returned instead of "const char*"

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19000]
As noted by @MarcoFalke in https://github.com/bitcoin/bitcoin/pull/18994#discussion_r426250850 the case can be made that at least some of the functions in our code base returning `const char*` should return `std::string` instead.

Candidates:

```
$ git grep -E '^(static |inline |const |unsigned )*char *\*[^(<]*\(' ":(exclude)src/leveldb/" ":(exclude)src/univalue/" ":(exclude)src/serialize.h" ":(exclude)src/tinyformat.h"
src/bitcoin-cli.cpp:static const char *http_errorstring(int code)
src/script/script.cpp:const char* GetOpName(opcodetype opcode)
src/script/script.h:const char* GetOpName(opcodetype opcode);
src/script/script_error.cpp:const char* ScriptErrorString(const ScriptError serror)
src/script/script_error.h:const char* ScriptErrorString(const ScriptError error);
src/script/standard.cpp:const char* GetTxnOutputType(txnouttype t)
src/script/standard.h:const char* GetTxnOutputType(txnouttype t);
src/test/script_tests.cpp:static const char *FormatScriptError(ScriptError_t err)
```

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
`GetTxnOutputType` returns a `nullptr`, but none of the call sites check for that

**Comment by practicalswift** [comment]
@MarcoFalke Yes, returning `std::string{}` is probably the right thing to do where we return `nullptr` today.

@kcalvinalvin Would you mind tackling also `GetTxnOutputType` in your PR to make the change complete? :)

**Comment by MarcoFalke** [comment]
I don't think it should return an empty string. Either the case can not be hit, so an assert (or static_assert) is appropriate. Or it can be hit, in which case it should return an `Optional<>`, to force the caller to check.

An empty string combines the worst of both worlds: It doesn't ask the caller to check for the error condition or it silently pretends the case can not exist.

**Comment by kcalvinalvin** [comment]
> @kcalvinalvin Would you mind tackling also `GetTxnOutputType` in your PR to make the change complete? :)

Sure I'll get on that

**Comment by practicalswift** [comment]
> I don't think it should return an empty string. Either the case can not be hit, so an assert (or static_assert) is appropriate. Or it can be hit, in which case it should return an Optional<>, to force the caller to check.

Good point. `assert(false);` is probably the right thing to do in this case.
