### ISSUE TITLE
[RPC] Getting the spent transaction outputs of transactions in latest blocks

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#19003]
I am trying to gather some stats based on a recently mined block, that I need to update continuously.

One of the stat I am interested in is how many transaction are with round amount fees in the latest block.

To do this, I would need to `getblock` then for each transaction input, get the previous one via `getrawtransaction`. Now two problems with this:
1. This require an enormous amount of requests.
2. This need `txindex=1`

Would it be realistic instead, to just fetch the spent output data directly from the Block Undo data that is still stored in the disk? This data is guaranteed to be always around as we need it to handle reorg. It also contains all the information I would need for the whole block in one continuous storage area. (instead of querying around via txindex).

Is there any other way I am missing?

If I were to make a PR to add this feature, I think the easiest way would be to just expose the block undo data directly with a RPC method.

**Comment by MarcoFalke** [comment]
#16083

**Comment by NicolasDorier** [comment]
That's exactly what I need. Will ping @FelixWeis

**Comment by robot-dreams** [comment]
@NicolasDorier does #18772 fix this? It was extracted from #16083 and adds fees to the `getblock` RPC.

(Thanks @adamjonas for noticing this!)

**Comment by MarcoFalke** [comment]
@robot-dreams The pull by @robot-visions only reports the *total* fee, not "how many transaction are with round amount fees in the latest block". This is being worked on in https://github.com/bitcoin/bitcoin/issues/18771#issuecomment-754529930

**Comment by 0xB10C** [comment]
#21245 adds a `prevout` field to the transaction inputs in `getblock <hash> 3`.

**Comment by achow101** [comment]
#22918 added `getblock` verbosity level 3 which adds `prevout` to each tx input.
