### ISSUE TITLE
Bitcoind not using swap space

### ISSUE THREAD

**Issue by yakitorifoodie** [bitcoin/bitcoin#19012]
**Version** : 0.19.1

**Actual behavior** : Tried `verifychain` with `dbcache=400000` but after consuming RAM the bitcoind stopped.

**Expected behavior** : It should use swap space after using RAM.

**To reproduce** : Run `bitcoin-cli verifychain 4 0` and observe that bitcoind not using swap space.

**System information** : OS : Ubuntu 18.04, RAM : 16GB, swap space : 500GB

**slightly related** : #12256

**Comment by adamjonas** [comment]
Given this hasn't moved since 2020, closing due to lack of support. Can re-open if future interest.
