### ISSUE TITLE
windows rpc connect failure

### ISSUE THREAD

**Issue by anotherfriend** [bitcoin/bitcoin#19027]
Good afternoon! I am trying to remotely connect via rpc to the windows server where bitcoin core is running

my config
```
listen=1
maxconnections=15
server=1
daemon=1
rpcuser=rootrr
rpcpassword=1213
rpcallowip=(ip_remote, not local)
rpcport=8332
```

through the browser of the local server with bitcoin core installed, everything starts, and on the remote connection error with the host, the firewall is disabled

help me, plz =(

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
