### ISSUE TITLE
Close wallet in prunign mode

### ISSUE THREAD

**Issue by udovdh** [bitcoin/bitcoin#19039]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In prunign mode:
For more security, please close the wallet when closing down Bitcoin Core.
Upon startup ask for the wallet passphrase because the wallet was closed.
This will give more security.

**Describe alternatives you've considered**
We already have good locks on the doors.

**Additional context**

**Comment by MarcoFalke** [comment]
>  For more security, please close the wallet when closing down Bitcoin Core.

This is already the case. All wallets are closed when shutting down.

You will need to provide a passphrase the next time it reads private keys.

**Comment by udovdh** [comment]
Why is my wallet open after starting Bitocin Core?
Why is there a warning when I attempt to close the wallet manually?
Why am I never asked fro a passphrase when I do not close the wallet manually?

**Comment by MarcoFalke** [comment]
> Why is my wallet open after starting Bitocin Core?

Bitcoin Core has one default wallet, which is loaded by default (unless disabled)

>  Why is there a warning when I attempt to close the wallet manually?

What warning?

>  Why am I never asked for a passphrase when I do not close the wallet manually?

Closing the wallet does not require a passphrase

**Comment by udovdh** [comment]
The warning is about pruned mode and needing to resync when wallet is closed for too long.

**Comment by ryanofsky** [comment]
> Bitcoin Core has one default wallet, which is loaded by default (unless disabled)

Note: #15454 implements a nicer behavior here, loading the same wallets at startup that were loaded prevoiusly. The PR is a bit stale right now though and I want to integrate it with #15937 so wallet loading is the same with bitcoind and bitcoin-qt
