### ISSUE TITLE
test, ci: Use the documented way to test with ThreadSanitizer

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19038]
According to the [ThreadSanitizer docs](https://clang.llvm.org/docs/ThreadSanitizer.html#current-status):
>  C++11 threading is supported with **llvm libc++**.

To use the ThreadSanitizer in the documented way we should build from depends with `clang++ -stdlib=libc++` (see #18820).

Related to #19024.

**Comment by MarcoFalke** [comment]
Might also be useful to fix up the docs `doc/developer-notes.md`

**Comment by MarcoFalke** [comment]
So I guess there are two things to note:

* llvm-10 is required
* llvm libc++ is required

**Comment by hebasto** [comment]
Also the `--disable-wallet` `configure` option could be mentioned:
- https://github.com/bitcoin/bitcoin/issues/18823#issuecomment-626067525 
- https://github.com/bitcoin/bitcoin/issues/18916#issuecomment-632406409

**Comment by MarcoFalke** [comment]
So the gnu tsan seems to cover a subset of the tsan in the llvm libc++? While it is probably recommended to use llvm 10 libc++, it shouldn't be a requirement to just run with tsan. (It is only a requirement if you want to get the most sensitivity out of the tsan)

**Comment by fanquake** [comment]
What is left to be done here?
