### ISSUE TITLE
Pruning undo files?

### ISSUE THREAD

**Issue by jb55** [bitcoin/bitcoin#19040]
Currently these take up around 37GB on a full node, and as far as I can tell they are only used for stats and large reorgs. It would be nice if there was an option to prune these past a minimum of 288 (MIN_BLOCKS_TO_KEEP) blocks if the user:

- does not care for these stats
- is not worried about large reorgs
- doesn't want to prune blocks

As a side note: txindices currently use 10GB *less* space than this data.

It doesn't look like you can just delete these files either: https://bitcoin.stackexchange.com/questions/71272/are-old-rev-dat-file-safely-deletable

**Comment by vasild** [comment]
Related: https://bitcoincore.reviews/17994.html#l-214

**Comment by jb55** [comment]
yes a lot of those points by @sipa were brought up when the idea was mentioned awhile back. I'm not convinced that "just run a pruned node" is reasonable suggestion for people who want to keep the full chain for rescan. The added complexity is a downside, and loss of stats is a minor inconvenience.

**Comment by willcl-ark** [comment]
These files are used and useful in several places, and if there is a re-org they are vital.
