### ISSUE TITLE
testmempoolaccept should return the fee

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19057]
When testing a transaction for mempool acceptance, the fee must be calculated anyway. Thus, with minimal complexity overhead, the testmempoolaccept RPC could return the fee to the user.

#### Useful skills:

Basic understanding of the mempool, the Bitcoin Core RPC interface, and the functional test framework.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by rajarshimaitra** [comment]
This seems like graspable at my level. Willing to give this a try. 
One question:
What fee should the RPC return? The fee of the transaction or the minimum threshold fee for acceptance?

**Comment by MarcoFalke** [comment]
The motivation behind this is that any caller (wallet, rpc, ...) may want to know the fee of the transaction. Either for sanity checks or for bookkeeping.
