### ISSUE TITLE
Can no longer open wallet.dat without warnings

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19051]
After commit ccd85b57af60d7034db372b9501d059fbc5941e4 I can no longer open my wallet without warnings.

![Screenshot from 2020-05-22 10-45-35](https://user-images.githubusercontent.com/6399679/82679920-9704a180-9c19-11ea-8f55-4c935ced8fe2.png)

```
Warning: Error reading /home/marco/.bitcoin/regtest/wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.

**Comment by achow101** [comment]
There should be something in the debug.log with an error about what went wrong.

**Comment by MarcoFalke** [comment]
It says:

```
2020-05-22T16:19:35Z [qt-init] [default wallet] Error reading wallet database: keymeta found with unexpected path

**Comment by achow101** [comment]
Does the wallet contain any imports? Is it HD? Was it non-HD and then upgraded to HD?

Can you share the wallet file?

**Comment by MarcoFalke** [comment]
[wallet.dat.gpg.pptx](https://github.com/bitcoin/bitcoin/files/4669312/wallet.dat.gpg.pptx)


Please don't steal my regtest coins :pray:
