### ISSUE TITLE
Build/Docs: -help text references rpcauth script not present in binary release

### ISSUE THREAD

**Issue by harding** [bitcoin/bitcoin#19081]
The help text says "a canonical python script is included in `share/rpcauth`":

    $ bitcoind -help | grep -A3 rpcauth
      -rpcauth=<userpw>
           Username and HMAC-SHA-256 hashed password for JSON-RPC connections. The
           field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A
           canonical python script is included in share/rpcauth. The client
           then connects normally using the
           rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This
           option can be specified multiple times

This is true of the git repository and the source release, but that file is not available in the binary releases:

    $ wget https://bitcoincore.org/bin/bitcoin-core-0.19.1/bitcoin-0.19.1-x86_64-linux-gnu.tar.gz
    $ tar tzf bitcoin-0.19.1-x86_64-linux-gnu.tar.gz | grep -i rpcauth || echo FILE NOT FOUND
    FILE NOT FOUND

IMO, this file should either be included with the binary releases or it should not be mentioned in the help text.  I think this issue needs a decision from experienced contributors about which approach to take, and then can be tagged as a *good first issue* for possible implementation by a less experienced contributor.

Note: this issue is a deliberate duplicate of #14292 (by [request](https://github.com/bitcoin/bitcoin/issues/14292#issuecomment-634733333)).

**Comment by harding** [comment]
CC: original reporter of #14292, @bitstein

**Comment by MarcoFalke** [comment]
bitcoin-core/packaging might want to ship this as well

**Comment by vahidjalaliii** [comment]
Iove
