### ISSUE TITLE
test: Replace gobal wait_until with mininode.wait_until

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19080]
Using the global wait_until makes it impossible to adjust the timeout based on the hardware the test is running on.

This should be fixed by using the mininode member function.

See fa80b4788bbe3ef00c5d767c0d89ba9809d8707c for an example patch on how to fix it.

List of potential "offenders":

```
$ git grep -l --extended-regexp  '(import)? wait_until($|,)'
```

#### Useful skills:

Basic Python3

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by dboures** [comment]
Hi, I am planning to work on this.

**Comment by MarcoFalke** [comment]
#19134 is closed and thus, this issue is up for grabs again

**Comment by jules23** [comment]
I'll work on this.

**Comment by slmtpz** [comment]
I can also pick this up.

**Comment by jules23** [comment]
@slmtpz ok i leave this to you then!

**Comment by slmtpz** [comment]
@MarcoFalke @gzhao408 Hey guys! Just wanted to ping you about my PR which I believe covers the rest of "wait_until" usages, since you were the ones most involved in the previous closed PR.
