### ISSUE TITLE
Write linter to check that commit messages have a new line before the body (or no body)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19091]
This comes up really often: https://github.com/bitcoin/bitcoin/pull/19082#issuecomment-635404401

This can be based on the other lint scripts in `./test/lint`.

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by za-kk** [comment]
I will take a look at working on this one 👍

**Comment by sachinkm77** [comment]
@MarcoFalke can I work on this? So the ask is to write a linter to check the commit message for 70 characters and ensure it has a newline?

**Comment by MarcoFalke** [comment]
No, 70 characters should not be a requirement. Also, it looks like @za-kk is already working on this issue.

**Comment by Ghorbanian** [comment]
I would like to work on this issue if @za-kk is not actively working on it.

**Comment by yahiheb** [comment]
Should be closed since #19439 was merged.
