### ISSUE TITLE
doc: Document ALLOW_HOST_PACKAGES dependency option

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19113]
The `ALLOW_HOST_PACKAGES` dependency option is not documented in this repo at all, including https://github.com/bitcoin/bitcoin/blob/master/depends/README.md

**Comment by sachinkm77** [comment]
@hebasto can i work on this?

**Comment by hebasto** [comment]
> @hebasto can i work on this?

Sure! Thank you @sachinkm77 !

**Comment by sachinkm77** [comment]
thanks @hebasto. can you give me some pointers, since its my first contribution

**Comment by hebasto** [comment]
@sachinkm77 
> thanks @hebasto. can you give me some pointers, since its my first contribution

In general, the great list of resources for new contributors could be found in https://bitcoincore.reviews/

Particularly for this issue, describing of code behavior and use cases could be enough:
```
$ git grep -n -i ALLOW_HOST_PACKAGES
ci/test/00_setup_env_native_qt5.sh:11:export DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1"
depends/Makefile:183:            -e 's|@allow_host_packages@|$(ALLOW_HOST_PACKAGES)|' \
depends/config.site.in:68:if test -z "@allow_host_packages@"; then
```

Some knowledge of GNU Make and shell scripting is required.

**Comment by sachinkm77** [comment]
Thanks @hebasto . I will work on it.

**Comment by hebasto** [comment]
Closing via #19124.
