### ISSUE TITLE
Rename -rescan because it confuses people

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#1912]
It's now almost a daily event that I see people on IRC saying they used -rescan or telling people to use rescan when it makes no sense and should have no effect at all.  Because it takes a little while some things that just take time to resolve (e.g. confirmation count going up on transactions) is very aggressively believed to be the magical cure all.

Either that or there are a whole litany of nasty bugs all over the client, some totally unrelated to the wallet, which are cured by rescan which aren't being reported because people have a workaround.

Instead perhaps we should rename rescan to  -frobnicate-wallet-transaction-index.

**Comment by laanwj** [comment]
I agree with the sentiment, but deliberately renaming an option to prevent it from being overused (and break backwards compatibility) seems a step too far for me.
In practice I can only see this generate complaints, especially as we don't fail on unknown options (#1044), so I'm going to close this.

**Comment by TheComputerGenie** [comment]
> ...deliberately renaming an option to prevent it from being overused (and break backwards compatibility) seems a step too far for me.

Given the new changes, I guess no one cares about that idea anymore.

**Comment by TheComputerGenie** [comment]
> Why not prepend the scope of the commands. E.g. -wallet-rescan or -blockdb-reindex?

> ...deliberately renaming an option to prevent it from being overused (and break backwards compatibility) seems a step too far for me.

Given the new changes, I guess no one cares about that idea anymore.
