### ISSUE TITLE
[administrative] Resource Identifier

### ISSUE THREAD

**Issue by HashUnlimited** [bitcoin/bitcoin#19126]
bitcoin: is going to expire soon as a provisional protocol identifier (source: IANA). 
According to BIP21, @TheBlueMatt  is the last Action Hero on this topic.

**Comment by TheBlueMatt** [comment]
Hum, I don't recall being the one to do it, but its possible. I presume someone who knows what's going on should do some kind of re-registration dance?

**Comment by adamjonas** [comment]
I never got a response from Dave Thaler, nor did I find evidence that the provisional protocol identifier will expire. @HashUnlimited, maybe you could shed some more light but otherwise, closing for now.
