### ISSUE TITLE
bump boost test to 1.59?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19128]
To skip tests. See https://github.com/bitcoin/bitcoin/pull/16564#issuecomment-630478623

See https://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/tests_organization/enabling.html

https://packages.debian.org/jessie/libboost-all-dev is going to die in about a month https://wiki.debian.org/DebianReleases#Production_Releases

https://packages.ubuntu.com/xenial/libboost-all-dev is going to die in less than a year https://ubuntu.com/about/release-cycle

**Comment by fanquake** [comment]
We've just bumped Boost to 1.58.0, so this has missed the cut. If/when we bump it the next time, it'll likely be > 1.59.0, so we'll get the test features, however I'm not sure we need to keep a tracking issue open.

**Comment by hebasto** [comment]
Ok, after #22320 this issue was re-opened.

But its description seems outdated now. Maybe update it with more clear goals?

**Comment by hebasto** [comment]
To make `make check` compatible with https://www.boost.org/doc/libs/1_64_0/libs/test/doc/html/boost_test/tests_organization/enabling.html changes from #22757 are required.

**Comment by hebasto** [comment]
> To skip tests.

See https://github.com/hebasto/bitcoin/pull/272.
