### ISSUE TITLE
Matching bare-pubkey P2PK/P2MS (prev)txouts with 1-starting P2PKH address

### ISSUE THREAD

**Issue by andronoob** [bitcoin/bitcoin#19156]
**Is your feature request related to a problem? Please describe.**

Firstly it's not really an issue of Bitcoin Core only, it's about the entire bitcoin ecosystem :-)

I don't really know the historical context. I have learned that displaying P2PK/P2MS as 1-starting P2PKH address is criticized as "non-standard" or "incorrect" etc, so that some block explorers like Blockstream.info have refused to display these bare-pubkey (previous) transaction outputs as 1-starting P2PKH addresses.

IMHO this only creates confusion, that even the famous Satoshi genesis address cannot be clearly displayed.

**Describe the solution you'd like**

I think it's really reasonable to make a compromise, to make matching P2PK/P2MS with 1-starting P2PKH address possible.

The confusion/ambiguity between P2PKH and P2PK/P2MS has already been there. I agree that ambiguity is not good, but mentions/referrings (in the old historical posts/writtings etc) of those 1-starting addresses simply can't be eradicated :-( Therefore a compromise might be actually necessary.

However, I agree that the distinction between P2PKH and P2PK/P2MS should always be taken good care of, by means of displaying notes (on the web-based block explorer) and extending the functions of [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md).

**Describe alternatives you've considered**

Honestly I don't know... "keep the status quo", probably? :-)

**Additional context**

https://github.com/Blockstream/esplora/issues/14
https://btc.com/581d30e2a73a2db683ac2f15d53590bd0cd72de52555c2722d9d6a78e9fea510
https://www.blockchain.com/btc/block/0
https://btc.com/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
https://blockstream.info/block/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin discussions are best directed to the bitcoin-dev mailing list (if they are bitcoin development related) or the `#bitcoin` IRC channel on freenode.

**Comment by MarcoFalke** [comment]
As far as Bitcoin Core is affected by this, please see #16725.

**Comment by andronoob** [comment]
@MarcoFalke 

Actually it's not only about getrawtransaction/decoderawtransaction RPC calls (and besides, the [GUI](https://github.com/bitcoin/bitcoin/pull/16725#issuecomment-638602633)), it's also an usability issue of the output descriptor - to me it's so obvious that matching a P2PK output with P2PKH pubkey hash is totally viable, however I don't know how could the current output descriptors design cover this.

------

>Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. 

Obviously, Bitcoin Core itself is affected. I just meant it would be a good first step towards the appropriate handling of this problem - rather than simply *ignoring* or even *denying* it.

**Comment by MarcoFalke** [comment]
> by means of displaying notes (on the web-based block explorer) and extending the functions of output descriptors.

Bitcoin Core can't change what block explorers display. If you have any ideas on how to improve output descriptors, then please let us know. But the document you linked to shows that they already support raw pubkey destinations: https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#examples . So I am not sure what your feature request is.

**Comment by andronoob** [comment]
>Bitcoin Core can't change what block explorers display.

It's true, my apologies. However, maybe Bitcoin Core could change [how itself displays P2PK outputs in its GUI](https://github.com/bitcoin/bitcoin/pull/16725#issuecomment-638602633)?

----

>raw pubkey destinations

Honestly I'm not quite sure either... What I saw is as follows:
>`pk(KEY)` (anywhere): P2PK output for the given public key.

it seemed that only the public key, instead of the hash of the public key, could be placed in parentheses.

**Comment by andronoob** [comment]
I agree that ambiguity is not good. I'm also aware that P2PK is ancient thing, which is (almostly) not used any more. However, AFAIK, it has penetrated into the culture of Bitcoin community so deeply, and meanwhile it doesn't seem to be not as bad as "incorrect", as a P2PK output has exactly the same ownership with the corresponding P2PKH address.
