### ISSUE TITLE
estimatesmartfee returns error on testnet and mainnet

### ISSUE THREAD

**Issue by dragoonduel** [bitcoin/bitcoin#19150]
Issue 
unable to obtain any fee using estimatesmartfee on main net and test net
below response was using bitcoin-cli estimatesmartfee 6
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 0
}
Using bitcoin core version 0.19.1 downloaded from https://bitcoin.org/en/bitcoin-core/

System is running on AWS EC2 and using EFS

my AWS Linux ec2 is hosted in the private subnet to allow only outgoing transactions to pull in nodes information. it does not allow any incoming connections from external. does it required an incoming connections in order to build up the mempool as well as the fee_estimate? 

getmempoolinfo return this
{
  "loaded": true,
  "size": 0,
  "bytes": 0,
  "usage": 0,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000
}

file size of mempool.dat and fee_estimates.dat is below
-rw------- 1      17 Jun  3 02:54 mempool.dat
-rw------- 1   247985 Jun  3 02:54 fee_estimates.dat

referring to issue #15568 i tried to delete the same files and the blocks and chainstate folder to resync, but it is still not returning the fees.

**Comment by jonasschnelli** [comment]
Have you successfully synced (initial block download) you node?
What does `getblockchaininfo` tell you?

**Comment by dragoonduel** [comment]
Hi yes, my node height is the same as current testnet height
see below on getblockchaininfo
{
  "chain": "test",
  "blocks": 1747489,
  "headers": 1747489,
  "bestblockhash": "000000000000059078a5934fd8282244cd0061fb3b4c3e86f8e311e8ce982351",
  "difficulty": 2245782.832211968,
  "mediantime": 1591162574,
  "verificationprogress": 0.9999979350152886,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000000000015ba25328a7f2054319",
  "size_on_disk": 27385046763,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 21111
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 330776
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 581885
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 770112
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 834624
    }
  },
  "warnings": "Warning: unknown new rules activated (versionbit 28)"
}

**Comment by MarcoFalke** [comment]
>  hosted in the private subnet to allow only outgoing transactions

It is only possible to estimate fees when you have enough mempool transactions from the outside p2p network
