### ISSUE TITLE
Bitcoins have no intrinsic value, so let's fix that

### ISSUE THREAD

**Issue by dbsanfte** [bitcoin/bitcoin#19163]
**Is your feature request related to a problem? Please describe.**

Bitcoins currently have no intrinsic value. This sucks.

**Describe the solution you'd like**

Bitcoins should be redeemable on the network itself to buy compute cycles from miners, and miners should be able to run arbitrary compute tasks for users to earn their Bitcoin instead of mindlessly computing hashes.

**Describe alternatives you've considered**

I've considered that other coins might be easier to develop a system like this for, but I thought I would feature-request it to Bitcoin first.

**Additional context**

If Bitcoins had intrinsic value, backed by the compute resources available on the entire Bitcoin network, they could really compete with fiat currency. Almost everyone has a compute task they'd love to buy cycles for.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
