### ISSUE TITLE
Bitcoin Core GUI getrawtransaction implementation

### ISSUE THREAD

**Issue by zndtoshi** [bitcoin/bitcoin#19161]
Bitcoin Core offers sovereignty by people controlling their keys and validating those keys. But many users today hold their keys on hardware wallets or mobile wallets and it's a bit difficult to connect those wallets to a full node and validate them. 

The cli users have the option to "getrawtransaction _txid_ true" in order to find valuable information about a transaction that could be theirs. This is a very powerful api call that effectively eliminates the need of an Electrum server.

I think many users would find a lot of value in easily verifying their personal transaction directly from Bitcoin Core GUI! 

Something like Help -> Verify external txid. There would need to be an option to enable txindex also. This would greatly increase the use of Bitcoin Core for the ease of validating a transaction. Sure users could create a watch only wallet but these are extra steps that maybe many of the non technical users would get discouraged from doing.

**Comment by promag** [comment]
GUI users can use the RPC console. Anyway, Concept ACK

**Comment by Jssdr** [comment]
The easiest way to earn Bitcoins? Just change your browser to CryptoTab and receive payments to your balance every 10 minutes. You will get BTC for simply using it, even if just having CryptoTab browser window open. It takes less than 1 minute to start earning - https://cryptotabbrowser.com/15166435

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/645.
