### ISSUE TITLE
travis arm64 errors: sudo: unable to resolve host travis-job-bitcoin-bitcoin-694885469

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#19171]
Seeing "sudo: unable to resolve host travis-job-bitcoin-bitcoin-" errors two different PRs in the travis ARM build followed by timeouts:

https://travis-ci.org/github/bitcoin/bitcoin/jobs/694723263
https://travis-ci.org/github/bitcoin/bitcoin/jobs/694879056
https://travis-ci.org/github/bitcoin/bitcoin/jobs/694885469

I tried restarting the first job repeatedly (maybe 5 times) but it kept failing in the same way. Then I rebased and it happened again, and it happened again on another PR. It doesn't seem to happen on all PRs, even other PRs with the same base, but once it happens it seems to stick.

**Comment by fanquake** [comment]
Looks like this has been reported [upstream](https://travis-ci.community/t/sudo-unable-to-resolve-host/8841) (also arm) at least. However no replies yet.

**Comment by ryanofsky** [comment]
Thanks for the link. Another job failed this morning

https://travis-ci.org/github/bitcoin/bitcoin/jobs/695011338

**Comment by MarcoFalke** [comment]
I don't know why, but #19276 seems to work around the failure
