### ISSUE TITLE
qt: Broken QApplication::widgetAt() on Ubuntu Focal 20.04

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19186]
This report is separated from #18419.

On Ubuntu Focal 20.04 (both Qt 5.9.8 and system Qt 5.12.8) the `QApplication::widgetAt()` returns `nullptr` when it shouldn't. This upstream bug breaks our `GUIUtil::isObscured()`, and, as consequences, the `BitcoinGUI::toggleHidden()` and the "Show / Hide" menu item in the system tray icon menu.

Here are some possible answers for this Focal/Qt bug:
- drop the "Show / Hide" menu item
- replace the "Show / Hide" menu item with "Minimize / Restore" one
- another approach

What do you think?

**Comment by hebasto** [comment]
ping @promag @jonasschnelli @jonatack

**Comment by MarcoFalke** [comment]
> This upstream bug

Is there a link?

**Comment by hebasto** [comment]
> > This upstream bug
> 
> Is there a link?

Did not find yet.

**Comment by promag** [comment]
> On Ubuntu Focal 20.04 (both Qt 5.9.8 and system Qt 5.12.8) the `QApplication::widgetAt()` returns `nullptr` when it shouldn't.

In what case? Always? When the widget is minimized?

**Comment by hebasto** [comment]
@promag 
> > On Ubuntu Focal 20.04 (both Qt 5.9.8 and system Qt 5.12.8) the `QApplication::widgetAt()` returns `nullptr` when it shouldn't.
> 
> In what case? Always? When the widget is minimized?

When the main window is visible. The "Hide" command from the systray icon menu does not work.

**Comment by fanquake** [comment]
If this is still something you want to follow up with, can you reopen this in the [gui repo](https://github.com/bitcoin-core/gui).
