### ISSUE TITLE
Unidentified thread created in FlushStateToDisk()

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19199]
While testing #19197, a strange, at least for me, behavior has been [observed](https://github.com/bitcoin/bitcoin/pull/19197#issuecomment-640169081) during reindexing with:
```
$ ./src/bitcoind -testnet -reindex
```

When the dbcache reaches its maximum and the following lines appear in the log:
```
2020-06-07T13:24:37Z [loadblk] Cache size (761427872) exceeds total space (761373440)
2020-06-07T13:24:42Z [loadblk] FlushStateToDisk: write coins cache to disk (5389943 coins, 761427kB) started
2020-06-07T13:24:50Z [loadblk] FlushStateToDisk: write coins cache to disk (5389943 coins, 761427kB) completed (7.60s)
```

a _new_ thread has been created by the client.

The strange thing is that this thread is named "loadblk". I understand that it couldn't be the `ThreadImport` thread as it is guarded by `CImportingNow` instance.

In my tests this unidentified thread is mostly named "loadblk", but once I've noted "msghand" name.

It seems this thread is unjoined until the client shutdown.

---

Some screenshots:

![Screenshot from 2020-06-07 10-02-35](https://user-images.githubusercontent.com/32963518/83970531-cfc19d80-a8de-11ea-98a7-267db1c93521.png)

![Screenshot from 2020-06-07 16-51-13](https://user-images.githubusercontent.com/32963518/83970588-2038fb00-a8df-11ea-92cf-c1bf7272decc.png)

---

System:
x86_64, Linux Mint 19.3 (Ubuntu 18.04 code base)

**Comment by MarcoFalke** [comment]
Does leveldb start threads?

**Comment by sipa** [comment]
Yeah, I assume it's one of the LevelDB threads. I vaguely remember a PR recently to rename it.

**Comment by hebasto** [comment]
> Does leveldb start threads?

Yes, it does. From the [leveldb docs](https://github.com/google/leveldb/blob/master/doc/impl.md#compactions):
> When the size of level L exceeds its limit, we compact it in a _background thread_.

**Comment by hebasto** [comment]
> I vaguely remember a PR recently to rename it.

#18790. The "Name leveldb thread with its own name" commit was dropped.

**Comment by hebasto** [comment]
I verified. It is a leveldb background thread.
