### ISSUE TITLE
0.20.0 update broke symbolic link for blocks folder

### ISSUE THREAD

**Issue by siroccal** [bitcoin/bitcoin#19209]
### Describe the issue
After upgrading to 0.20.0, I can't use a symbolic link for the blocks folder anymore.

### What behavior did you expect?
I expect to be able to use a symbolic link for the blocks folder.

### What was the actual behavior (provide screenshots if the issue is GUI-related)?
Bitcoin Core closing with this error:
```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: File exists: "/home/user/.var/app/org.bitcoincore.bitcoin-qt/data/blocks"

bitcoin in Runaway exception
```

### How reliably can you reproduce the issue, what are the steps to do so?
Move the blocks folder to anywhere outside the bitcoin folder, like /media/data/blocks or /home/user/blocks, and make a symbolic link from the original data/blocks to the new location. Then try to start Bitcoin Core.

### What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
0.20.0 from Flathub.

### What type of machine are you observing the error on (OS/CPU and disk type)?
Fedora Linux.

**Comment by MarcoFalke** [comment]
@A6GibKm any idea why this could happen?

For reference (not sure if relevant):

* https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions
* https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override

Unclear to me, but maybe `flatpak override $APP --filesystem=$FOLDER` might do it?

**Comment by siroccal** [comment]
> @A6GibKm any idea why this could happen?
> 
> For reference (not sure if relevant):
> 
>     * https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions
> 
>     * https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override
> 
> 
> Unclear to me, but maybe `flatpak override $APP --filesystem=$FOLDER` might do it?
Oh, nice, that command makes it work fine.

**Comment by A6GibKm** [comment]
I don't know what might have triggered a change in behavior when updating, but not being able to access symlinks is to be expected when there are no explicit app permissions.

**Comment by MarcoFalke** [comment]
ok, closing then
