### ISSUE TITLE
boost::shared_lock - C++14

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19218]
```
$ git grep boost::shared_lock
src/script/sigcache.cpp:        boost::shared_lock<boost::shared_mutex> lock(cs_sigcache);
src/test/cuckoocache_tests.cpp:            boost::shared_lock<boost::shared_mutex> l(mtx);
```

Boost [1.47 docs](https://www.boost.org/doc/libs/1_47_0/doc/html/thread/synchronization.html#thread.synchronization.locks.shared_lock):
> Class template `shared_lock`

Boost [1.70 docs](https://www.boost.org/doc/libs/1_70_0/doc/html/thread/synchronization.html#thread.synchronization.locks.shared_lock):
> Class template `shared_lock` - **C++14**

Does "C++14" tag mean the `boost::shared_lock` requires C++14? Googling, docs reading and header reviewing did not help.

**Comment by MarcoFalke** [comment]
Probably means it that C++14 can be used instead of boost?
