### ISSUE TITLE
test: ConnectionRefusedError on consecutive runs the same test

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19234]
On Ubuntu Focal running the same test some times in a row
```
$ BITCOIND=/home/hebasto/bitcoin/src/qt/bitcoin-qt QT_QPA_PLATFORM=minimal ./test/functional/feature_versionbits_warning.py
```

I eventually got

```
AssertionError: [node 0] Node returned non-zero exit code (-11) when stopping
...
ConnectionRefusedError: [Errno 111] Connection refused
[node 0] Cleaning up leftover process
```

**Comment by MarcoFalke** [comment]
Related, but different: #18623

**Comment by willcl-ark** [comment]
I have just tried to reproduce this on 21.04 but have been unable to do so. `QT_QPA_PLATFORM=minimal` did not work on my system (plugin could not load application fonts) so I tested with `QT_QPA_PLATFORM=offscreen`, running the test 20 times:

```
will@ubuntu in bitcoin (032ceb1 🏷  v24.0rc2) [?] via 🐍 v3.6.12
❯ for i in (seq 1 20)
      BITCOIND=/home/will/src/bitcoin/src/qt/bitcoin-qt QT_QPA_PLATFORM=offscreen ./test/functional/feature_versionbits_warning.py
  end
```

It seems unlikely that this is related to the QPA platform, but do you think it's worth testing on a 20.04 VM too?

**Comment by hebasto** [comment]
> It seems unlikely that this is related to the QPA platform

Agree.

> but do you think it's worth testing on a 20.04 VM too?

It won't hurt :)

**Comment by MarcoFalke** [comment]
Can this be closed, given that the bug is fixed in recent version of Ubuntu?

**Comment by fanquake** [comment]
I think so. Is this even a bug in Bitcoin Core?
