### ISSUE TITLE
Create Wallet Version

### ISSUE THREAD

**Issue by ben29** [bitcoin/bitcoin#19244]
when creating wallet , I see on Debug Log:

```
2020-06-08T08:12:51Z [test] Wallet File Version = 10500
2020-06-08T08:12:51Z [test] Performing wallet upgrade to 169900
```
why creating old version and then upgrade?

how I can create wallet with the last version? instead of create and then upgrade...

Using bitcoin version:
v0.20.0.0

**Comment by achow101** [comment]
The first version number is just the default line that is reported when no wallet file is found. The wallet is actually being created with the latest version number. There isn't really an upgrade happening. 169900 is the latest wallet version.

**Comment by MarcoFalke** [comment]
Does the debug logging need to be fixed or can this be closed?

**Comment by achow101** [comment]
I think this can be closed. The debug logging technically isn't wrong, and it isn't possible to get a wallet created at version 10500 without killing bitcoind right before it actually gets to the bulk of the wallet creation.
