### ISSUE TITLE
doc: Enable doxygen on the test directory

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19248]
While it makes sense to exclude third party libraries in subtrees from doxygen, is there any reason to also exclude the fuzz and unit tests?

They both have frameworks and utility functions that I need to look up repeatedly.

Doxygen is meant to be developer documentation and not Bitcoin Core user documentation, so I see no downside of enabling the test directory in doxygen. Am I missing something?

**Comment by laanwj** [comment]
Concept ACK, I don't remember anymore why I disabled the test, but whatever reason I had is likely not valid anymore.
