### ISSUE TITLE
static FeeFilterRounder in net_processing needs a mutex (or documentation that concurrent access is not allowed)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19254]
The class uses a fast random context. The context is documented to be not thread-safe.

Currently, SendMessages is only called in a single thread, but in the future or in unit tests, this might change.

**Comment by sipa** [comment]
Thanks!

**Comment by hebasto** [comment]
@sipa @MarcoFalke 

Mind looking into #19268?
