### ISSUE TITLE
gui: calling txoutset commands broken in console

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#19255]
Calling `*txoutset` calls in the console has been broken since #19056. The addition of the `RpcInterruptionPoint()` calls means that any user running the GUI without passing `-server`, will just see ["Shutting down"](https://github.com/bitcoin/bitcoin/blob/b33136b6ba9887f7db651c4c5264ca7f2f601df7/src/rpc/server.cpp#L325) printed to the console:

![console](https://user-images.githubusercontent.com/863730/84460760-55599a80-ac9d-11ea-8720-a718edde75dd.png)

cc @MarcoFalke

**Comment by MarcoFalke** [comment]
Good catch. This needs to be fixed before the next major release.
