### ISSUE TITLE
display received payments for unspendable multisig addresses

### ISSUE THREAD

**Issue by freewil** [bitcoin/bitcoin#1928]
It seems to me that the usefulness of multisig addresses are severely limited if the current client implementation doesn't support showing received payments to a multisig address unless one has all the keys imported into their wallet.

I understand why it may be considered dangerous to show received payments if they aren't spendable (the wallet doesn't have all the required keys for the multisig address) but at the same time that is exactly the point of using multisig addresses.

It seems any rpc calls dealing with transactions (`listsince`, `listtransactions`, etc) should at least have an extra option to show transactions sent to multisig addresses that have been added with `addmultisigaddress` (ismine: true) even if all the keys haven't been imported into the wallet.

**Comment by laanwj** [comment]
This can be done using the watch-only functionality in 0.10+: Add the multisig address with `importaddress`.
