### ISSUE TITLE
Pruned node: (Re)download of pruned block

### ISSUE THREAD

**Issue by prusnak** [bitcoin/bitcoin#19312]
Now, when a pruned block is requested via `getblock` the answer is:

```
error code: -1
error message:
Block not available (pruned data)
```

Would it make sense to add a possibility to (re)download the block so a pruned node can give a meaningful answer in this case as well?

I can imagine two options on how to implement this:
a) automatic - the block is redownloaded automatically when `getblock` on a pruned block is requested
b) manual - new method `downloadblock` which will redownload the block and make it available to `getblock` again

The size of the LRU cache for (re)downloaded blocks could be controlled via `prunecache=X` in `bitcoin.conf` or we can decide that the node will use up to e.g. 10% of prune capacity for these older blocks.

**Comment by mahnunchik** [comment]
Related issues:

* https://github.com/bitcoin/bitcoin/pull/10794
* https://github.com/bitcoin/bitcoin/issues/10929
* https://github.com/bitcoin/bitcoin/pull/20295

**Comment by prusnak** [comment]
This was more or less implemented in https://github.com/bitcoin/bitcoin/pull/20295
