### ISSUE TITLE
ci: Cirrus CI logs availabilty

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19336]
To point a test failure on Travis it is sufficient to close-reopen the pull (in order to not re-write the log) and post the link to the build log (e.g., #19221, #19139, #18969).

From the Cirrus CI [docs](https://cirrus-ci.org/faq/#are-there-any-limits):
> By default Cirrus CI persists caches and logs for 90 days.

So we should post the Cirrus CI log itself rather the link to it.

But I'm unavailable to see or download the log even from yesterday (https://github.com/bitcoin/bitcoin/pull/19321#issuecomment-646515657).

**Comment by MarcoFalke** [comment]
Seems like an upstream bug?

**Comment by hebasto** [comment]
> Seems like an upstream bug?

Of course :)

I just wanted to mention about the necessity to copy the log.

**Comment by MarcoFalke** [comment]
Does this still happen? Setting `kvm:true` might have fixed this.

**Comment by MarcoFalke** [comment]
Can be documented if needed, but no need to keep an issue open about this
