### ISSUE TITLE
test: refactor restart_node

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19345]
For cleaning up the tests, `stop_node+start_node` should be changed to simply `restart_node`.

Potential candidates:

```
git grep -A1 'stop_node(' | grep -B1  'start_node('
```

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by ccdle12** [comment]
I would like to help on this issue
