### ISSUE TITLE
test: bump mypy

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19346]
version 0.700 is incompatible with python-3.8-dev, so at least this linter should be bumped. Maybe the other linters can be bumped, too?

```
git grep mypy==0.700
```

#### Useful skills:

Python, Bash

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by duncandean** [comment]
I'll take a look at this one.
