### ISSUE TITLE
doc: RPC command `getreceivedbyaddress` does not include mined coins

### ISSUE THREAD

**Issue by ben-kaufman** [bitcoin/bitcoin#19343]
The RPC commands `getreceivedbyaddress` and `getreceivedbylabel` do not return balance received as a mining reward (even after the 100 blocks maturing period).
I would expect the command to return the full UTXO balance on the address, including mining rewards, or the command documentation to clarify this is not returned.

I wanted to first ask here whatever this is indeed the expected behavior of the command, and if so, if it would be appropriate to mention it in the documentation as the issue suggests.
If this is either not the expected behavior, or is but should be documented, I would be happy to be assigned to this issue, otherwise, I think it will be fine to close this issue.

**Comment by MarcoFalke** [comment]
#14654

**Comment by Aonny112** [comment]
Wiphawee112#%
