### ISSUE TITLE
Intermittent CI failure: wallet_importdescriptors.py

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19376]
Intermittent CI failure: `wallet_importdescriptors.py`

See https://travis-ci.org/github/bitcoin/bitcoin/jobs/701586452 for details.

**Comment by MarcoFalke** [comment]
Duplicate of #18803 ?

**Comment by practicalswift** [comment]
Thanks! Closing this one.

**Comment by andrygreen777** [comment]
[]() #19374 @practicalswift 
Duplicate of #
