### ISSUE TITLE
Build fuzz tests by default

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19388]
Similar to all other tests (unit tests, bench tests, gui unit tests, ...), the fuzz tests should also be built by default.

So, `--enable-fuzz` should be changed to `--disable-fuzz`.

See https://github.com/bitcoin/bitcoin/pull/19366#issuecomment-648763070

#### Useful skills:

build system background

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by michaelfolkson** [comment]
Given that the [advice](https://diyhpl.us/wiki/transcripts/sydney-bitcoin-meetup/2020-05-19-socratic-seminar/) for those interested in running fuzz tests is arguably to run them on a Linux instance and not Mac OS is it wise for Mac OS users to be running all fuzz tests by default?

**Comment by sipa** [comment]
@michaelfolkson This is not about running them, but *building* the fuzz test code - without actual fuzzing enabled. The advantage is that you'd notice when a change you're making breaks the fuzz tests.

This is similar to why we build the benchmarks by default, even when you're not interested in benchmarking: even if you don't, the benchmarks shouldn't break.

Actual fuzzing requires re-building with a whole different set of compilation options (and possibly a different compiler). But the code that implements the tests should be buildable easily by anyone who can build the rest of the code.

**Comment by willcl-ark** [comment]
I'd like to take a stab at this to try and get a bit more familiar with the build system...

However at first glance it looks like compiling fuzz tests by default would require c++17 which might make this less desirable. For example, std::optional is c++17 only:

```
$ git grep -c "std::optional"
src/optional.h:1
src/test/fuzz/addrdb.cpp:1
src/test/fuzz/asmap_direct.cpp:1
src/test/fuzz/block_header.cpp:2
src/test/fuzz/blockfilter.cpp:1
src/test/fuzz/bloom_filter.cpp:3
src/test/fuzz/chain.cpp:1
src/test/fuzz/coins_view.cpp:4
src/test/fuzz/flatfile.cpp:2
src/test/fuzz/merkleblock.cpp:1
src/test/fuzz/policy_estimator.cpp:2
src/test/fuzz/pow.cpp:2
src/test/fuzz/primitives_transaction.cpp:3
src/test/fuzz/protocol.cpp:2
src/test/fuzz/rbf.cpp:2
src/test/fuzz/rolling_bloom_filter.cpp:1
src/test/fuzz/script.cpp:2
src/test/fuzz/script_interpreter.cpp:2
src/test/fuzz/script_sigcache.cpp:2
src/test/fuzz/script_sign.cpp:7
src/test/fuzz/util.h:1
```

It also increases my compile time by ~60% (from 440s to 730s), which might also not be desirable as the standard compile options.

Would this still be something that we would want to make the default based on the above?

**Comment by willcl-ark** [comment]
Ah I've now found the discussion in https://github.com/bitcoin/bitcoin/issues/16684 ...

So it seems like the question now is, is it more desirable to open a PR now and let it sit unmerged until c++17 becomes default, or just waiting?

**Comment by sipa** [comment]
How hard is it to revert the c++17isms in the fuzz tests? I would expect it's only minimal (use Optional instead of std::optional etc)

**Comment by willcl-ark** [comment]
I think based on discussion in https://github.com/bitcoin/bitcoin/pull/18901/ you are probably correct Sipa. I will take a crack at doing just that then.

**Comment by willcl-ark** [comment]
@MarcoFalke it looks like the issue I am seeing is that the fuzz-test flag is fundamentally incompatible with the wallet being built. If I configure with `--disable-wallet` then I don't see the linker errors (on my machine, travis still complains about other stuff sometimes). 

I was then easily able to find an issue about this already: https://github.com/bitcoin/bitcoin/issues/16094

I'm not sure how to reconcile building the wallet and the fuzz tests in this case, do you have any ideas on this front?

**Comment by MarcoFalke** [comment]
I believe the reason is that our lib_test is one library (with the wallet included), which is linked with the fuzz tests. Though, the wallet itself is never linked into the fuzz tests. I think this can be solved by splitting lib_test into lib_test and lib_wallet_test

**Comment by willcl-ark** [comment]
Ah OK thanks for the pointer. I shall investigate this further :)

**Comment by willcl-ark** [comment]
@MarcoFalke I've confirmed that building (most of) the travis configs work without `--disable-wallet` _or_ `--disable-tests`.

Re. lib_test: is this a file getting built by test/util/setup_common.cpp?

**Comment by MarcoFalke** [comment]
Yes everything in test/util is put into `libtest_util.a`

What is the link error you are seeing?

**Comment by willcl-ark** [comment]
This is the link error. I just wasn't sure where to look for lib_test to split it...

```
$ ./configure --enable-wallet --enable-fuzz --enable-zmq --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --enable-c++17 --enable-debug CFLAGS="-g0 -O2 -funsigned-char" CXXFLAGS="-g0 -O2 -funsigned-char"
  CXXLD    test/fuzz/block_filter_deserialize
/usr/bin/ld: libbitcoin_server.a(libbitcoin_server_a-init.o): in function `WalletInit::Construct(NodeContext&) const':
init.cpp:(.text+0x1f49): undefined reference to `interfaces::MakeWalletClient(interfaces::Chain&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:7913: test/fuzz/addrman_deserialize] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: libbitcoin_server.a(libbitcoin_server_a-init.o): in function `WalletInit::Construct(NodeContext&) const':
init.cpp:(.text+0x1f49): undefined reference to `interfaces::MakeWalletClient(interfaces::Chain&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:7949: test/fuzz/block] Error 1
make[2]: Leaving directory '/home/will/src/bitcoin/src'
make[1]: *** [Makefile:18288: all-recursive] Error 1
make[1]: Leaving directory '/home/will/src/bitcoin/src'
make: *** [Makefile:788: all-recursive] Error 1
```

**Comment by MarcoFalke** [comment]
Ah, ok. That is not test related.

**Comment by MarcoFalke** [comment]
It might be possible to fix by linking LIBBITCOIN_WALLET to the fuzz tests. `LIBBITCOIN_WALLET` should be empty when the wallet is disabled

**Comment by practicalswift** [comment]
@sipa 

> How hard is it to revert the c++17isms in the fuzz tests? I would expect it's only minimal (use Optional instead of std::optional etc)

That would be trivial :) 

Context: Rationale to the C++17-switch for the fuzzers: https://github.com/bitcoin/bitcoin/pull/18901#issuecomment-625469044 + https://github.com/bitcoin/bitcoin/pull/18901#pullrequestreview-408557865.

**Comment by willcl-ark** [comment]
@practicalswift I believe I have done that in this commit: https://github.com/willcl-ark/bitcoin/commit/b2df89483143cdfc47ae6db5bbbbb6e835f39fc8

**Comment by practicalswift** [comment]
@wilbown Ah, https://github.com/willcl-ark/bitcoin/commit/b2df89483143cdfc47ae6db5bbbbb6e835f39fc8 looks good :)

**Comment by willcl-ark** [comment]
@MarcoFalke taking another look at this now... Adding `LIBBITCOIN_WALLET` to `FUZZ_SUITE_LD_COMMON` if `WALLET_ENABLED` is set doesn't seem to fix the link issue. The errors I'm seeing look like this: https://termbin.com/fm6d

Do you think this means that we'll have to split test_bitcoin in two as you suggested earlier, or is there something else I might be missing here?

**Comment by MarcoFalke** [comment]
@willcl-ark Are you still working on this?

**Comment by willcl-ark** [comment]
> @willcl-ark Are you still working on this?

No @MarcoFalke I eventually gave up. I was trying to learn more about the build system by taking it on, but was a bit more than I could chew!

**Comment by sipa** [comment]
A suggestion I made a few days ago on IRC:

```
17:34:26< sipa> my biggest gripe with the fuzz builds is that it's impossible to even do any compilation of the fuzz
                code without a separate configure step
17:34:46< sipa> after merging them all in one binary it'd be easy to permit building the fuzz binary without fuzzing
                enabled, though
17:34:49< wumpus> making say the fuzz objects .fuzz.o would also prevent them accidentally being linked into a non-fuzz
                  binary (or the other wayr around)
17:35:44< wumpus> yes, that might help
17:41:41< sipa> it'd be great if we could have a .fuzz.o for everything
17:41:48< sipa> not sure how much work it is
17:43:44< wumpus> i trust cfields is right that this is hard to realize with auto* build system for some reason
17:49:21< sipa> we could even make a "dummy" fuzz binary when building without fuzzing that can only run existing seeds
                through the fuzz tests
17:49:50< sipa> which would mean you can do the CI fuzz things without separate build
17:52:44< aj> sipa: ooo! that's a good idea!
17:54:51 * sipa suggests calling it phonyfuzz
17:54:57< aj> phuzz
17:55:15< aj> faux+fuzz=fauzz?
17:55:23< fanquake> .PHONY
18:06:45< wumpus> let's try to merge #20560 soon then
```

**Comment by MarcoFalke** [comment]
Sounds like a good suggestion, but is probably best done as a separate follow-up to not scope creep this issue.

**Comment by sipa** [comment]
@MarcoFalke Sure.

**Comment by danben** [comment]
Hi,

I think I've got this working, though it was easy so I'm a little worried that I've done something wrong. I'll work on a pull request in a bit.

**Comment by danben** [comment]
So I'm down to [one failing CI test](https://github.com/bitcoin/bitcoin/pull/20936/checks?check_run_id=1754886735) and could use some assistance. The problem appears to be a type error in a single call to `swap` (cuckoocache.h:431). I can't reproduce this if I try to build/install manually using the arguments in ci/test/00_setup_env_native_qt5.sh, and I'm not sure where the difference is coming from. Furthermore, we only ever create CuckooCaches for primitive types so I don't understand the error.
