### ISSUE TITLE
[Feature] -balanceIndex switch

### ISSUE THREAD

**Issue by baso10** [bitcoin/bitcoin#19392]
Can we add switch -balanceIndex that would keep track of balances for all addresses?

I understand that it is not needed for Bitcoin to run, but so is -txindex not needed. 

Was this idea already dismissed or just nobody had time to do it?

**Comment by jonatack** [comment]
@baso10 would something like #19092 have met your need?

**Comment by baso10** [comment]
No. I would like to get balance of a random address. Without adding that address to my wallet or watchOnly list.

**Comment by jonatack** [comment]
See https://bitcoincore.reviews/14053.

**Comment by baso10** [comment]
Thanks
