### ISSUE TITLE
Using Bitcoin Core on a Mac mini + QNAP NAS Error

### ISSUE THREAD

**Issue by NckyDC** [bitcoin/bitcoin#19409]
Hello,

I would like some help, please.
I decided to run a full bitcoin node. I have a Mac mini server with Catalina 10.15.5 and a QNAP NAS (AFP) with 80TB as well as a very fast line.

I installed Bitcoin Core on the Mac Mini and experiencing a few issues.

1 - Why this application is not signed with an Apple certificate? Apple does not recognize it properly. I think it would be beneficial if it did. However, it can still be run by bypassing the security layer of Apple.

2 - When I launch it the first time it asks me to select a directory. This directory also will host the 300gigs for the block, so I created a BTC volume on the NAS (don't have that space available on the Mac mini) so I can save the ledger in its own dedicated space and it's here that I experience issues.

As soon as I select the directory I get a dialog error.

<img width="410" alt="85956961-291e6900-b981-11ea-9dbe-bf0d2ff45602" src="https://user-images.githubusercontent.com/63108238/86007166-f28f2f80-ba0e-11ea-9016-251c462571dd.png">

Error: Cannot obtain a lock on data directory /Volumes/BTC/Bitcoin Core. Bitcoin Core is probably already running.

The folder "blocks" gets created but also is unable to proceed and will quit the application once acknowledged and will no start again anymore unless I delete it.

Is it even possible to run the app and have the block saved on an external AFP volume?

Cheers

**Comment by jonasschnelli** [comment]
> 1 - Why this application is not signed with an Apple certificate? Apple does not recognize it properly. I think it would be beneficial if it did. However, it can still be run by bypassing the security layer of Apple.

It is signed but not notarized for privacy reasons (background infos #18187).
Right click and "open..." should allow you to start the app without issues.
Most (all?) contributors where in favour of that solution versus sacrificing privacy.

> 2 - When I launch it the first time it asks me to select a directory. This directory also will host the 300gigs for the block, so I created a BTC volume on the NAS (don't have that space available on the Mac mini) so I can save the ledger in its own dedicated space and it's here that I experience issues

**NAS are not supported.**. Bitcoin Core should be run with a fast and direct disk access.

**Comment by NckyDC** [comment]
Thanks for your reply. I understand NAS is not supported. However, i think you don't understand the speed of a top of the range QNAP NAS. These will copy 300GB in a few minutes and are on par with internal drives. 

Best

**Comment by ryanofsky** [comment]
> Thanks for your reply. I understand NAS is not supported. However, i think you don't understand the speed of a top of the range QNAP NAS. These will copy 300GB in a few minutes and are on par with internal drives.

I could be wrong, but I think bitcoin doesn't have any issues with NAS in general. It just has problems with AFP/NFS/SMB/CIFS and similar network filesystems. If you create an iSCSI volume on your NAS (https://www.qnap.com/en/how-to/tutorial/article/how-to-create-and-use-the-iscsi-target-service-on-a-qnap-nas/), and format and mount it with a regular filesystem on your mac mini, I don't think you should have any problems.
