### ISSUE TITLE
macOS Big Sur

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#19406]
New macOS releases have historically led to unpleasant surprises. I'm running the beta on an older machine, so I'll post testing progress here. Most problems deserver their own issue. See #16387 for Catalina beta testing last year.

I consider [Universal Apps](https://developer.apple.com/programs/universal/) out of scope for this issue.

I removed Homebrew and PyEnv first, installed Xcode 12 beta, before reinstalling them. This best represents what the actual OS will look like with a clean install. It also prevents Homebrew from installing Xcode 11 developer tools.

```
sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer
```

## Beta 1

Build: 20A4299v on Intel CPU, using Xcode 12 beta (without Universal App support).

Downloading 0.20 binary from bitcoincore.org works fine (with right-click install).

Tested master @ 19612ca2eb2e335c8ccc9c0f33421df22f1cc3b6

I didn't test ZMQ and libmultiprocess yet.

### Without depends

First I installed dependencies using homebrew 2.4.2. I use `--build-from-source` to see if there's any homebrew packages that probably need a Big Sure specific update . That revealed with a few problems.

Installing Python via PyEnv doesn't work yet (see https://github.com/pyenv/pyenv/issues/1643), but you can install the binary for now, or via homebrew.

Brew can't install `berkeley-db4` using `--build-from-source`, but it can use the Catalina bottle.

clang crashed for `test/test_bitcoin-scheduler_tests`; I sent a bug report to Apple, attached logs for @practicalswift and other compiler aficionados. I wasn't reproducible, not even after `git clean -dfx`.
[crash.zip](https://github.com/bitcoin/bitcoin/files/4844713/crash.zip)

### With depends

I was unable to build QT the first time, but can't reproduce that problem. BDB may need a patch (#19411). During blockchain download catchup, I got a `LevelDB read failure: Corruption: block checksum mismatch` error. I'll see if I can reproduce that. See #19410.

**Comment by MarcoFalke** [comment]
> clang crashed ... I wasn't reproducible

Usually that is OOM, or overheating, or some other hardware fault

**Comment by Sjors** [comment]
I ran with `-j6` on 8 GB of RAM, so it was OOM, then that itself was a probably bug. I've compiled Bitcoin Core countless times on that machine, and can't remember ever seeing an error like this (though perhaps it did happen, and of course it's older now).

**Comment by randolf** [comment]
> _Update:_ The spontaneously disappearing compile error for QT depends is one point in favour of broken hardware.

...as long as something updating Qt, one of its dependencies, or adding a needed #include somewhere didn't happen.
