### ISSUE TITLE
__builtin_clz[l[l]] not detected using clang

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#19402]
See this arbitrary macOS Travis job: https://travis-ci.org/github/bitcoin/bitcoin/jobs/702283632#L521

Somehow `AC_CHECK_DECLS` doesn't work for builtins for clang (it does work for GCC).

However, `__builtin_prefetch` (which is detected using `AC_COMPILE_IFELSE`) does work.

**Comment by sipa** [comment]
From `config.log`:

```

configure:21492: clang++-10 -std=c++11 -c -g -O2  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS conftest.cpp >&5
conftest.cpp:100:10: error: builtin functions must be directly called
  (void) __builtin_clz;
         ^
1 error generated.
```

**Comment by fanquake** [comment]
This is not specific to macOS, the configure checks currently fail with both LLVM and Apple Clang.

**Comment by sipa** [comment]
Yes, I detected it on Linux when building with clang.
