### ISSUE TITLE
bitcoin-qt 20. GUI opens empty

### ISSUE THREAD

**Issue by NinjaTurtle007** [bitcoin/bitcoin#19456]
After updating from 18. the GUI of bitcoin-qt opens up like this:
[https://imgur.com/AmRCLyZ](url)
The same with version 19.

18. still opens fine by the way
This is on Ubuntu 19.10

**Comment by promag** [comment]
Are building bitcoin-qt or using the available binary?

**Comment by NinjaTurtle007** [comment]
Using the binary

**Comment by hebasto** [comment]
@NinjaTurtle007 
Mind uploading a screenshot directly into this GitHub issue?

**Comment by hebasto** [comment]
@NinjaTurtle007 
... and there is a dedicated repo for the GUI related issues: https://github.com/bitcoin-core/gui/issues

:)

**Comment by hebasto** [comment]
@NinjaTurtle007 
> This is on Ubuntu 19.10

When you will reopen this issue in https://github.com/bitcoin-core/gui may I ask you to provide additional info about your system: desktop environment, window manager etc?

**Comment by hebasto** [comment]
As a first aid try to run with `-resetguisettings` option.

**Comment by NinjaTurtle007** [comment]
Ok I opened it there to the best of my abilities, thanks!

**Comment by hebasto** [comment]
@NinjaTurtle007 
> Ok I opened it there to the best of my abilities, thanks!

Thanks!

This issue should be closed in favor of https://github.com/bitcoin-core/gui/issues/28.
