### ISSUE TITLE
ADDR response to GETADDR only contains 1000 addresses at most

### ISSUE THREAD

**Issue by jpeisenbarth** [bitcoin/bitcoin#19458]
Hello,

There are two constants that set the number of addresses sent in an ADDR message to max(23% of the tables content 2500) : ADDRMAN_GETADDR_MAX_PCT and ADDRMAN_GETADDR_MAX

https://github.com/bitcoin/bitcoin/blob/b52e25cc1be3771cad26c6c3cdbc0b81f96597ec/src/addrman.h#L156-L160

They are used here, in the call `connman->GetAddresses();` and vAddr contains max(23% of the tables, 2500) elements.

https://github.com/bitcoin/bitcoin/blob/b52e25cc1be3771cad26c6c3cdbc0b81f96597ec/src/net_processing.cpp#L3326-L3332

But in the end, there are only 1000 addresses sent at most because of `pfrom.PushAddress(addr, insecure_rand);` 

https://github.com/bitcoin/bitcoin/blob/b52e25cc1be3771cad26c6c3cdbc0b81f96597ec/src/net.h#L952-L965

https://github.com/bitcoin/bitcoin/blob/b52e25cc1be3771cad26c6c3cdbc0b81f96597ec/src/net.h#L54

Why is there a selection of 23% of the tables new or tried (or 2500) when at the end it is cropped to 1000 ? or maybe did I miss something ?

**Comment by naumenkogs** [comment]
You are not missing anything, we were just discussing it [here](https://github.com/bitcoin/bitcoin/pull/18991#discussion_r449789621).

I think this was overlooked and never bothered anyone, because it doesn't introduce any issues beyond a slight inefficiency.
Unless we fix it in the PR I linked above, someone can make a separate PR addressing this specific issue.

**Comment by jpeisenbarth** [comment]
Oh yes, I didn't see this issue, thank you, I'll close this one and follow the one you linked

**Comment by naumenkogs** [comment]
That PR is not entirely about this issue, but yeah, perhaps making some decision there is better than spreading over several issues :)
