### ISSUE TITLE
LevelDB performance when running on microSD card

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19467]
Let's consider the following setup:
- the node is running on a single board computer (SBC)
- the blocksdir is located on external drive
- the datadir is located on system microSD card

As SD cards were initially made for pure sequential workloads the performance of LevelDB on average SD card is quite poor (as logs say). When the background LevelDB thread begins compaction the node becomes pretty unresponsive.

Do exist any LevelDB option tweaks that could trigger a compaction less frequently? It could be helpful during reindexing at least.

**Comment by fanquake** [comment]
Not sure there's anything to do here, and it's not exactly a "bug". Think we can close for now. If anyone has thoughts they can still leave them.
