### ISSUE TITLE
Question: PSBT and RBF

### ISSUE THREAD

**Issue by t-bast** [bitcoin/bitcoin#19481]
Hi all!

As part of the [anchor outputs](https://github.com/lightningnetwork/lightning-rfc/pull/688) work for Lightning (in the context of [eclair](https://github.com/acinq/eclair)), I'm wondering if it's possible to use psbts and the `bumpfee` RPC or if I'll have to implement a lot of fee bumping code myself outside of `bitcoind`.

A quick summary of the situation (a lot more details [here](https://github.com/t-bast/lightning-docs/blob/master/lightning-txs.md) if you're interested):

* we have a "commit tx" that represents the state of the channel
* this "commit tx" has an output for CPFP carve-out (called "anchor") that we use to bump the fee (through a "claim anchor tx")

```ascii
  commit tx
+--------------+
|   vout       |
| +----------+ |
| | output 1 | |
| +----------+ |
|     ...      |
| +----------+ |
| | anchor   | |-------+
| +----------+ |       |         claim anchor tx
|     ...      |       |       +-----------------------------------+
| +----------+ |       |       |   vin               vout          |
| | output n | |       |       | +-------------+   +-------------+ |
| +----------+ |       +------>| | anchor utxo |   | wallet utxo | |
+--------------+               | +-------------+   +-------------+ |
                               | +-------------+                   |
  unrelated tx         +------>| | wallet utxo |                   |
+--------------+       |       | +-------------+                   |
|   vout       |       |       +-----------------------------------+
| +----------+ |       |
| | output 1 | |-------+
| +----------+ |
|     ...      |
| +----------+ |
| | output m | |
| +----------+ |
+--------------+
```

The `bitcoind` wallet doesn't have the keys necessary to spend the "anchor"; these are handled by the lightning node.
But I'd like to let `bitcoind` chose what inputs and outputs to add to that transaction to achieve a given feerate.

This looks like a perfect use-case for PSBT:

* use `bitcoind`'s `walletcreatefundedpsbt` to obtain a wallet psbt
* create a lightning psbt with only the anchor utxo as input
* use `joinpsbts` to gather all inputs/outputs
* use `walletprocesspsbt` to get signatures for the wallet inputs
* add the signature for the anchor input and finalize the psbt

Once that's done, I can publish my "claim anchor tx".
However if it still doesn't confirm in time, I'd like to RBF that transaction.
But obviously `bumpfee` will not work out of the box because there's one input that it can't automatically re-sign.
What would be really great would be if `bumpfee` could replace all wallet inputs/outputs to bump the fee (abiding by all the BIP 125 rules) and then return a psbt with all the wallet inputs signed; I would then only need to re-sign the anchor input, finalize the psbt and broadcast it.

IIUC 0.20.0 has taken a first step in that direction (returning a psbt in `bumpfee`), but it looks like it will only do that with a watch-only wallet, whereas I'd like that behavior with normal wallet too. Does this request make sense, and if so is this being currently worked on?

**Comment by t-bast** [comment]
@instagibbs would you have some time to enlighten me regarding this (as the author of https://github.com/bitcoin/bitcoin/pull/16373 you're probably the most relevant point of contact)? Sorry for the ping, hope you don't mind :)

**Comment by achow101** [comment]
@t-bast You might be interested in #18654

**Comment by t-bast** [comment]
Great thanks @achow101, this definitely goes in the right direction for my usecase.

In my case where some inputs are signed by the `bitcoind` wallet and one input is signed with a lightning priv key, I'll be able to use `psbtbumpfee` to obtain a psbt where the `bitcoind` wallet's inputs/outputs will have been modified to bump the fee, and then use the other psbt RPC to complete the psbt into a complete transaction. That's great!

**Comment by instagibbs** [comment]
So one note is that the Core wallet will have to consider all the transaction inputs as its "own" to make the bump succeed. In the PSBT setting maybe this logic can/should be relaxed. @achow101 ?

**Comment by t-bast** [comment]
I may be missing edge cases, but it seems to me that as long as the `bitcoind` wallet has one input that it can modify (and ideally one output or the ability to add a change output) it should be able to do its fee bumping work, right?

**Comment by instagibbs** [comment]
I'm being descriptive of checks currently made. They may be more strict
than necessary.

**Comment by t-bast** [comment]
Gotcha, but do you think my suggestion makes sense? Or am I missing something?

**Comment by instagibbs** [comment]
I think it makes sense.

**Comment by t-bast** [comment]
I've been experimenting with `psbtbumpfee` on master, and it looks like it's still failing when the tx contains non-wallet inputs (for the reasons described above).

@achow101 do you think there is a chance to change that behaviour before 0.21?

**Comment by instagibbs** [comment]
Feature freeze is ~tomorrow so unlikely unfortunately.

**Comment by t-bast** [comment]
Thanks for the quick reply, too bad! I'll try dipping my toes in bitcoin core code to see if I can implement this myself.

**Comment by instagibbs** [comment]
Feel free to reach out for help.

**Comment by t-bast** [comment]
It seems to me that the reason why it wasn't completely trivial to implement is this line:

https://github.com/bitcoin/bitcoin/blob/99a1d572eabca89790216b3919a237e07063a376/src/wallet/feebumper.cpp#L188

The feebumper first calculates the old fee, then computes the new one from it and update inputs/outputs accordingly.
For non-wallet inputs, we won't have the input amounts cached in the wallet (obviously).

I'm leaning towards adding `origFee` as an optional input parameter to the `psbtbumpfee` RPC (and when you have non-wallet inputs, this parameter is in fact mandatory). A caller that works with PSBTs had the finalized PSBT at some point, which allowed him to easily calculate the old fee, so he should be able to provide that parameter to the RPC.

Do you think it's a reasonable way to implement this?

**Comment by instagibbs** [comment]
Remember to ping me in a couple weeks, forgot to mention I don't have time right now...

**Comment by t-bast** [comment]
I'd be very interested to know if someone is looking into this issue, as it's clearly too much for someone like me who doesn't know the wallet codebase.

Right now, I'm forced to do quite horrible hacks to implement CPFP/RBF in lightning and I believe that any application that deals with non-wallet inputs will run into the same problems (which is probably why most lightning implementations re-implemented a bitcoin wallet from scratch instead of using bitcoin-core's built-in one). I understand this may be a lot of work, but it seems beneficial to many projects in the long run.

**Comment by t-bast** [comment]
This has become much better with https://github.com/bitcoin/bitcoin/pull/23201 and future work (https://github.com/bitcoin/bitcoin/pull/23202), closing this issue.
