### ISSUE TITLE
creating a backup of blockchain and index

### ISSUE THREAD

**Issue by 3ntranced** [bitcoin/bitcoin#19487]
**Is your feature request related to a problem? Please describe.**

I changed my external hdd enclosure for an hdd which was storing bitcoin data directory and bitcoind said chainstate was corrupted upon restart. I had rsynced bitcoin data directory to try and back it up in the past while bitcoind was running and restoring that copy didnt work either. So I had to -reindex-chainstate which took 3 days. 

**Describe the solution you'd like**

Some way to backup the bitcoin data directory "live", without having to stop bitcoind. 

**Describe alternatives you've considered**

rsynced the directory while its running and starting bitcoind from that copy didnt work. 

**Additional context**

**Comment by sumBTC** [comment]
@3ntranced It's an important issue but will take a while to implement. In the meantime: I backup the Bitcoin blockchain without stopping bitcoind every month on my server (basically) like this:

```
bitcoin-0.20.0/src/bitcoin-cli savemempool
rsync -L --delete -av ".bitcoin/" /media/external/.bitcoin
rsync -L --delete -av ".bitcoin/" /media/external/.bitcoin
rsync -L --delete -av ".bitcoin/" /media/external/.bitcoin
rsync -L --delete -av ".bitcoin/" /media/external/.bitcoin
```
Usually rsync doesn't do anything anymore for the last 2 executions. I then run bitcoin-qt on a different computer (but you could run it on your server too) like this (connecting only to my own bitcoind):
`./bitcoin-qt -connect=192.168.178.20 -blocksonly=1 -listen=0 -datadir=/media/external/.bitcoin`

Bitcoin-qt always repairs the blockchain without problems and this way you'll know if the backup was successful.

**Comment by 3ntranced** [comment]
Ok thank you, I ll try to understand and give this a go!

**Comment by 3ntranced** [comment]
`bitcoin-qt -connect=192.168.178.20 -blocksonly=1 -listen=0 -datadir=/media/external/.bitcoin`
this step is purely to verify the backup correct? if the backup is ok, of course you dont know until you verify, then even if you dont verify, you can rsync the directory back and it will work, right?

**Comment by sumBTC** [comment]
> this step is purely to verify the backup correct? 

To verify and "repair" the blockchain. Bitcoin-qt will see that bitcoind wasn't first closed before  rsyncing the blockchain and will "repair" the blockchain.

Bitcoin-qt never had a problem "repairing" the blockchain so you could skip this step if you like to but it's more risky. 

You can always resync.

**Comment by 3ntranced** [comment]
rsync a bunch of times works really well.
