### ISSUE TITLE
Question: source code package release

### ISSUE THREAD

**Issue by margre8** [bitcoin/bitcoin#19484]
Dear Bitcoin developers,

in release page for version 0.20.0 you have in description:

> Preferably use the above download link, not the links provided by GitHub to download the source tarball, as the release tarballs are generated deterministically whereas GitHub's are not.

But Github tarball and tarball from your page has same hash.

Thank you for help

**Comment by MarcoFalke** [comment]
This is a coincidence for the 0.20.0 release only
