### ISSUE TITLE
`decodepsbt` fee overstated since #19215

### ISSUE THREAD

**Issue by bitcoinhodler** [bitcoin/bitcoin#19516]
Following commit 46004790588c24174a0bec49b540d158ce163ffd (@achow101), `decodepsbt` overstates the fee, apparently including both the `witness_utxo` and `non_witness_utxo` amounts in the inputs.

**Expected behavior**

The decoded fee should be the sum of the inputs, minus the sum of the outputs.

**Actual behavior**

The decoded fee is exactly twice the amount of the inputs, minus the sum of the outputs.

**To reproduce**

Build any PSBT using `createpsbt`, `walletprocesspsbt`, then decode it with `decodepsbt`. See the `fee` field in the JSON.

**System information**

I compiled myself from 5550fa5983ea59e7ccef6540b7ec49a1770fb3ca on Whonix 14.

Then I did `git revert 46004790588c24174a0bec49b540d158ce163ffd ` and the problem went away.

**Comment by practicalswift** [comment]
@bitcoinhodler Thanks a lot for reporting! May I ask how you discovered/encountered this issue? That is always interesting to know.

**Comment by bitcoinhodler** [comment]
I have my own [fork of Glacier Protocol](https://github.com/bitcoinhodler/GlacierProtocol) with a bunch of self-checking tests. They started freaking out after #19215 because the PSBTs had changed, and I noticed the incorrect fee by inspection of the reported mismatches.
