### ISSUE TITLE
test: add a test for decodepsbt fee behaviour

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#19523]
As requested in #19517. @bitcoinhodler may also have some suggestions given they opened the original issue (#19516), after it was flagged by some of their own tests.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by gimballock** [comment]
I would like to give this one a shot!
