### ISSUE TITLE
depends: libtapi build still builds a version 6.0.1 ClangBasic target

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#19540]
The [libtapi we build in depends](https://github.com/tpoechtrager/apple-libtapi) builds a ClangBasic target. This is currently LLVM Clang 6.0.1, as that repository has a copy of Apples swift-clang repository at this commit: https://github.com/apple/swift-clang/commit/3c8cb332b1fed69f67aecfd56675b0ff297f2a01. You'll also see in our depends build output:
```bash
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Clang version: 6.0.1
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Success
-- TAPI version: 10.0.0
-- Supported Architectures: i386;x86_64;x86_64h;armv4t;armv6;armv5;armv7;armv7s;armv7k;armv6m;armv7m;armv7em;arm64
-- Performing Test LINKER_SUPPORTS_NO_INITS
-- Performing Test LINKER_SUPPORTS_NO_INITS - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /bitcoin/depends/work/build/x86_64-apple-darwin16/native_cctools/55562e4073dea0fbfd0b20e0bf69ffe6390c7f97-8eb3b80cace/libtapi/build

## Building clangBasic ##
...
```

Given that we've just moved to Clang 8.0.0 in depends for macOS builds, and generally we like to keep all these things "in sync", we should check if anything needs to be done here. Updating this would require upstream to reintegrate it's repo with a newer LLVM,  which should be https://github.com/apple/llvm-project, given Apple has deprecated swift-clang.

Opening an issue to remind myself but if anyone else wants to take a look please do.

**Comment by fanquake** [comment]
Upstream has now been [updated](https://github.com/tpoechtrager/apple-libtapi/commit/b4f141a16c7c82f75973429c92242a8c7de3ddb1), and is using Clang 8.

**Comment by theuni** [comment]
Agree with keeping in sync, and concept ACK to bumping whenever this is ready upstream.

One thing to keep in mind, though, is that libtapi is only used to link .tbd stubs from our SDK, which is pinned. So technically it shouldn't matter which version of clang files we link against as long as the result is capable of linking our pre-determined SDK files. This would be much more likely to cause issues at the time of an SDK bump, if for example, the newer SDK's .tbd files used a newer syntax.
