### ISSUE TITLE
Build warning in `test/fuzz/addrdb.cpp`: unused variable

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#19549]
Seen both locally and in the Travis fuzz build:
```cpp
test/fuzz/addrdb.cpp:20:21: warning: unused variable 'ban_entry' [-Wunused-variable]
    const CBanEntry ban_entry = [&] {
                    ^
1 warning generated.
```

**Comment by jonatack** [comment]
This code was added in a8695db7... pinging @practicalswift :)

**Comment by practicalswift** [comment]
`(void)ban_entry` should be enough to silence this warning.

The point of the code is to exercise all `CBanEntry` ctors :)

**Comment by jonatack** [comment]
Oh right, just like #18664. Fixing. Tnanks!
