### ISSUE TITLE
Normalize fee units for RPC ("BTC/kB" and "sat/B)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19543]
This needs to happen before the next major release. Otherwise, it will be a breaking change.

Some more context: https://github.com/bitcoin/bitcoin/pull/11413#issuecomment-649730975

**Comment by MarcoFalke** [comment]
cc @instagibbs @jonatack @kallewoof (from original discussion)

**Comment by jonatack** [comment]
This is on my to-do list this month.

**Comment by jonatack** [comment]
https://github.com/jonatack/bitcoin/commits/explicit-feerate-follow-ups

**Comment by kallewoof** [comment]
Ping me when there's something reviewable and/or if help is needed.

**Comment by amirofski** [comment]
fun

**Comment by jonatack** [comment]
Am now targeting doing this after October 15 feature freeze, as ISTM it's a bugfix, for 0.21, but if that is incorrect please let me know. 

I just now noticed that has been labeled as Up For Grabs, so if anyone is working on it *please* advise here so that we don't both work on it.

**Comment by Xekyo** [comment]
I'd be interested in helping with this (feerates are something I have an idea about), but I am not sure how I would start. @jonatack would you be interested in pairing on this? Otherwise, I'd also be happy to review.

**Comment by kallewoof** [comment]
@jonatack I'm not working on it, but if you drop it, let us know.

**Comment by jonatack** [comment]
> I'd be interested in helping with this (feerates are something I have an idea about), but I am not sure how I would start. @jonatack would you be interested in pairing on this?

SGTM! My priorities for the next 6 days are reviewing PRs 19953 (BIPs 340-342), 19954 (BIP 155/Tor v3), and 19988 (tx relay logic). Then this on Oct 16 to propose it by Oct 19/20, will ping you and @kallewoof when starting. Have a look at the last week of comments on #11413; ISTM we need to (a) fill in the tests to have a regression spec, (b) catch up with changes since that merge, (c) design the change, (d) implement it.

**Comment by jonatack** [comment]
@Xekyo I'll get started on this tomorrow and message you on IRC.

**Comment by jonatack** [comment]
@kallewoof @MarcoFalke @Xekyo Moving forward on this. To be sure I'm understanding the desired result here, is this what you have in mind?

current master...
```bash
./src/bitcoin-cli -signet -named sendtoaddress address="tb1qga36nkpuy3f3qswy0ltrvcayj7wfrk48tfdrd9" \
amount=0.00001 conf_target=2 estimate_mode=sat/b
```

desired replacement...
```bash
./src/bitcoin-cli -signet -named sendtoaddress address="tb1qga36nkpuy3f3qswy0ltrvcayj7wfrk48tfdrd9" \
amount=0.00001 feerate="2 sat/vb"
```

e.g. a string with a numerical + optional space + "btc/vb" or "sat/vb" (case insensitive)

(applied to the same RPCs as in #11413 plus the new `send` rpc)

**Comment by jonatack** [comment]
@kallewoof @MarcoFalke @Xekyo Moving forward on this. To be sure I'm understanding the desired result here, is this what you have in mind?

current master...
```bash
./src/bitcoin-cli -signet -named sendtoaddress address="tb1qga36nkpuy3f3qswy0ltrvcayj7wfrk48tfdrd9" \
amount=0.00001 conf_target=2 estimate_mode=sat/b
```

desired replacement (no more overloading of `conf_target`)...
```bash
./src/bitcoin-cli -signet -named sendtoaddress address="tb1qga36nkpuy3f3qswy0ltrvcayj7wfrk48tfdrd9" \
amount=0.00001 feerate="2 sat/vb"
```

e.g. the `feerate` arg takes a string with a numerical + optional space + "btc/kvb" or "sat/vb" (case insensitive)

(applied to the same RPCs as #11413 plus the new `send` rpc)

**Comment by MarcoFalke** [comment]
Yes, I think that makes sense and is an improvement

**Comment by Xekyo** [comment]
I have read the last week of #11413 that @jonatack linked above, but I don't understand why overloading the parameter to take a string that includes the magnitude and unit is more desirable than having separate parameters for the two different inputs and only allow a single unit for either.

**Comment by MarcoFalke** [comment]
Not sure if I understood you correctly. Are you asking why `feerate="0.00 unit"` is better than `feerate_amount="0.00", feerate_unit="unit"`? I think either is fine to use.

**Comment by jonatack** [comment]
ISTM the main goal is to not overload `conf_target` and `estimate_mode`, and use `feerate` instead:

- `sendtoaddress`/`sendmany`/`send` don't yet have a feerate argument
- `fundrawtransaction` and `walletcreatefundedpsbt` have feeRate
- `bumpfee` has fee_rate

Murch made a good point in a message yesterday:
```
22:28 aren't the two spaces of the two allowed units non-overlapping anyway?
22:30 While sat/vB would goes from 1-10,000, BTC per kvB would go from 0.00001-0.1
22:31 So, would having a value smaller than 1 not generally only conform to BTC/kvB and
      a value 1 or greater generally only make sense in the context of sat/vB?
```

We could indeed leave off the units, if users don't find it too confusing or scary? e.g. `feerate=1` for 1 sat/vb.

**Comment by Xekyo** [comment]
> ISTM the main goal is to not overload conf_target and estimate_mode, and use feerate instead:

Oh great! Not sure why I got confused about that then.

> We could indeed leave off the units, if users don't find it too confusing or scary? e.g. feerate=1 for 1 sat/vb.

Adding the unit makes it much easier to input an incorrect value. In the comments here alone, I see `sat/vb`, `sat/vB`, sat/b`, while the title is `sat/B`. Would we allow all of these? ;)
I would also assume that parsing a string to magnitude and unit is more complicated than just parsing a float.

I just realized, though, if we make 1 sat/vB the cutoff, we may be in trouble when the `minRelayTxFeerate` gets lower under 1 sat/vB. My preference would actually be to just have one unit in the first place, and then I'd either go with `sat/vB` or `sat/kvB`.

**Comment by jonatack** [comment]
> I just realized, though, if we make 1 sat/vB the cutoff, we may be in trouble when the `minRelayTxFeerate` gets lower under 1 sat/vB. My preference would actually be to just have one unit in the first place, and then I'd either go with `sat/vB` or `sat/kvB`.

SGTM, I'll start the day tomorrow with running this by @kallewoof on IRC if he is around (~0300/0400 UTC might be a good hour to reach him) and move forward with proposing `feerate=`<integer value> in sats/kvb with no units. Simple and clean, can make it more complex if people want.

**Comment by jonatack** [comment]
> I just realized, though, if we make 1 sat/vB the cutoff, we may be in trouble when the `minRelayTxFeerate` gets lower under 1 sat/vB. My preference would actually be to just have one unit in the first place, and then I'd either go with `sat/vB` or `sat/kvB`.

SGTM, I'll start the day tomorrow with running this by @kallewoof on IRC if he is around (~0300 UTC wakey wakey for me might be a good hour to reach him) and move forward with proposing `feerate=`integer value in sats/vb with no units. Simple and clean, can make it more complex if people want.

**Comment by jonatack** [comment]
(unless you discuss with him before that or move forward on your end, which is all good)

**Comment by kallewoof** [comment]
Concept ACK

**Comment by laanwj** [comment]
> Are you asking why feerate="0.00 unit" is better than feerate_amount="0.00", feerate_unit="unit"? I think either is fine to use.

Please, don't encode the unit into the value. Definitely don't vary the unit for the same parameter. I have seen this in c-lightning and I think this is very inconvenient for RPC clients, as they have to evaluate units every time at parsing time (making parsing a two-step process too). Either put it in the key (e.g. `feerate_unit=x.xx`) or standardize it over the entire program, but it might be too late for that.

**Comment by jonatack** [comment]
First follow-up is #20220 to have a clean working base and test spec in place. Building on it for the next step.

**Comment by jonatack** [comment]
> This needs to happen before the next major release. Otherwise, it will be a breaking change.
> 
> Some more context: [#11413 (comment)](https://github.com/bitcoin/bitcoin/pull/11413#issuecomment-649730975)

Proposal in #20305.
