### ISSUE TITLE
CRYPTO not mentioned in unix build instructions

### ISSUE THREAD

**Issue by iljah** [bitcoin/bitcoin#19566]
<-- Describe the issue -->

Tried to configure bitcoin on fedora 32 but got:
```bash
$ ./configure
...
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
checking for dynamic linked boost test... yes
checking for mismatched boost c++11 scoped enums... ok
checking for CRYPTO... no
configure: error: libcrypto not found.
```

<--- What behavior did you expect? -->

Configure would work or unix build instructions would mention how / where from to install CRYPTO.

<--- What was the actual behavior (provide screenshots if the issue is GUI-related)? -->

See above

<--- How reliably can you reproduce the issue, what are the steps to do so? -->

`git clone --recursive https://github.com/bitcoin/bitcoin.git && cd bitcoin && ./autogen.sh && ./configure`, happens every time

<-- What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)? -->

See above, version from few mins ago.

<-- What type of machine are you observing the error on (OS/CPU and disk type)? -->

Fedora 32

**Comment by iljah** [comment]
Looks like libcrypto isn't mentioned in https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md either.

**Comment by MarcoFalke** [comment]
What does the `config.log` say?

**Comment by MarcoFalke** [comment]
Also, `git log -1`?

**Comment by fanquake** [comment]
> Looks like libcrypto isn't mentioned in 

The because it's no longer a dependency. If you're building an older version where it's still required, you should be looking at the build docs for the branch you are building. 

I'm assuming you're actually building an older branch, because configure is also still checking for Boost Chrono:
> checking whether the Boost::Chrono library is available... yes
> checking for exit in -lboost_chrono... yes

which is also no-longer required or checked for when building master.

**Comment by iljah** [comment]
Looks like you're right, fresh checkout on another system worked.
