### ISSUE TITLE
Bitcore 0.9 no synchronize anymore, I've BTCs mined, generated and several confirmations, so with out balance in blockchain

### ISSUE THREAD

**Issue by DG-Br** [bitcoin/bitcoin#19563]
I used bitcore version 0.9 to mine in 2019 and managed to mine some BTCs, they were validated and the balance appeared on the main screen, and in the full description this is generated and confirmed several times but since November 2019 I can't synchronize the system, it crashed in 37 weeks, and the problem is that when I copy this wallet and put it in a more current bitcore version it does not confirm the mined BTCs and there is no balance.

**Expected behavior**

 
Initially, there is a command that forces the system to synchronize, and another way to import the mined BTCs with the validations and information from the old version.

**Actual behavior**

 The system starts normally, at the bottom the synchronization message, but there is no change in the evolution bar, another thing that draws attention is that in the information tab there are only 10,746 blocks of 640,000 blocks, that is, some bug occurred that created this instability .

**To reproduce**

**System information**

 bitcore 0.9.0.0-g92d25e4-beta (win 32bits) - Qt version 5.2.0

**Comment by MarcoFalke** [comment]
* Make sure your wallet.dat is properly backed up
* Then, import or open it with a new version of Bitcoin Core

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

**Comment by DG-Br** [comment]
> * Make sure your wallet.dat is properly backed up
> * Then, import or open it with a new version of Bitcoin Core
> 
> Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

Tks, I will to try in IRC on free node. However, I tried import and open in a new version, and it's show the mined BTCs however the BTCs appear orphans in the new versions.

**Comment by DG-Br** [comment]
Good evening everyone. I understood perfectly the answers and doubts about the veracity of the operation, but I also found some articles talking about people who had BTCs in the same situation, so, aside from the criticisms and supposed arguments that it would be a fraud or maleware, someone in this group would have any idea , even if improbable, how could we move this over the network and get these credits for exchange?
