### ISSUE TITLE
Feature Request: Pause/Resume network activity

### ISSUE THREAD

**Issue by Azulan** [bitcoin/bitcoin#1958]
Sometimes, I want to play a game or watch an online video on my machine, and I find that often times the upload bandwidth being used by bitcoin can cause latency or other issues with these activities. I request a way to pause and resume all bitcoin related network traffic, preferably through the gui. Perhaps it can have an optional time component so that it restart automatically after an hour or so, so that the client is not wasting time if forgotten about. I think that this option would be preferable to having to quit the program and then restart it, which can take up quite some time and a great deal of disk activity by reloading the block chain.Thank you.

**Comment by jonasschnelli** [comment]
related to #5314

**Comment by jonasschnelli** [comment]
Is implemented in https://github.com/bitcoin/bitcoin/pull/5314 but needs update. In the "paused" mode, we should still broadcast transaction and maybe warn the user if he has paused over a couple of possible blocks.

**Comment by jonasschnelli** [comment]
Closing, solved by #8996.
