### ISSUE TITLE
doc: Update obsolete links to online reference

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19582]
Links `https://bitcoin.org/en/developer-reference#...` in the [`protocol.h`](https://github.com/bitcoin/bitcoin/blob/master/src/protocol.h) are obsolete and require to be updated with a scripted-diff.

#### Useful skills:

`bash` and basic knowledge of how to contribute patches via git on GitHub.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by ecurrencyhodler** [comment]
I'll try take this issue. Thanks for pointing it out!

**Comment by ecurrencyhodler** [comment]
Submitted a PR here: https://github.com/bitcoin/bitcoin/pull/19584

**Comment by MarcoFalke** [comment]
Fixed in commit a78742830aa35bf57bcb0a4730977a1e5a1876bc
