### ISSUE TITLE
Show the "<n> of the last 100 blocks have unexpected version" warning only when running -debug=validation?

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19603]
[Google search results](https://www.google.com/search?q=of+the+last+100+blocks+have+unexpected+version) suggest that our users are more confused than helped by the `<n> of the last 100 blocks
have unexpected version` warning we're printing.

As developers we know the unfortunate reason behind this warning and how "unexpected" should be interpreted in this context, and thus why it is safe to disregard this warning. However, I don't think it reasonable to expect our users to know the historical context here.

In order to not desensitize our users to potentially critical "real" warnings, would it make sense to move this message to the `-debug=validation` log category?

**Comment by marpme** [comment]
Maybe it would be really helpful to give the user of this node suggestion what it could possibly mean by referencing a wiki site or giving a short suggestion what can be done to validate if this warning.

`<n> of the last 100 blocks have unexpected version (possible implication see: https://developer.bitcoin.org/reference/xyz/XYZ.html)`

**OR**

`<n> of the last 100 blocks have unexpected version (refers to mining differences but make sure to run the latest bitcoin version)`

These might not be the best description but they might be more explicit for the user to handle this certain warning.

**Comment by n-thumann** [comment]
Addressed the issue in #19898. I´d be happy about any feedback ✌️

**Comment by artburkart** [comment]
Hi 👋 

> As developers we know the unfortunate reason behind this warning and how "unexpected" should be interpreted in this context, and thus why it is safe to disregard this warning. However, I don't think it reasonable to expect our users to know the historical context here.

Earlier, there was a suggestion to point folk to a wiki page. There's a comment that says #19898 addresses the OP issue. Was the explanation part also addressed?

**Comment by iemwill** [comment]
@marpme 

> Maybe it would be really helpful to give the user of this node suggestion what it could possibly mean

Yes!
