### ISSUE TITLE
rpc: argument name inconsistency

### ISSUE THREAD

**Issue by stylesuxx** [bitcoin/bitcoin#19616]
Most of the rpc commands that take a number of blocks as an argument have an argument name of **nblocks**, like:
* getchaintxstats
* verifychain
* generatetoaddress
* getnetworkhashps
* ...

but **generatetodescriptor** instead has an argument name of **num_blocks**.

Not sure if I am being to pedantic here, but I'll happily provide a PR.

**Comment by MarcoFalke** [comment]
Changing the naming would be a breaking change

**Comment by stylesuxx** [comment]
@MarcoFalke - I am not sure if I understand why it would be a breaking change - maybe I was not completely clear: https://github.com/bitcoin/bitcoin/blob/2f71a1ea35667b3873197201531e7ae198ec5bf4/src/rpc/mining.cpp#L209
vs.
https://github.com/bitcoin/bitcoin/blob/2f71a1ea35667b3873197201531e7ae198ec5bf4/src/rpc/mining.cpp#L244

Within the code itself both methods use **num_blocks**, which can stay as it is. And the RPC arguments are all positional, not named - right?

**Comment by MarcoFalke** [comment]
Both, positional as well as named args are supported

**Comment by stylesuxx** [comment]
Oh, I missed that. Then of course it makes no sense to change that.

**Comment by jonatack** [comment]
Yes, RPC API changes usually need to go through a deprecation process. Run `git log -S deprecat` for an idea.

**Comment by stylesuxx** [comment]
I see, thanks for the heads up, I guess this issue can be closed then.
