### ISSUE TITLE
freebsd 12.1 build broken

### ISSUE THREAD

**Issue by metacreo** [bitcoin/bitcoin#19633]
` ./configure --with-gui=no --disable-tests --disable-wallet MAKE=gmake`

`  CXXLD    bench/bench_bitcoin
/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7354: bitcoin-tx] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7350: bitcoin-cli] Error 1
/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7362: bitcoind] Error 1
/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7346: bench/bench_bitcoin] Error 1
gmake[2]: Leaving directory '/opt/bitcoin/bitcoin-0.20.0/src'
gmake[1]: *** [Makefile:17262: all-recursive] Error 1
gmake[1]: Leaving directory '/opt/bitcoin/bitcoin-0.20.0/src'
gmake: *** [Makefile:780: all-recursive] Error 1
`

**Comment by fanquake** [comment]
Can you try a `make clean` and recompiling? Are your Boost libraries installed and available? Can you provide any more information? 

I've just tested and can compile `v0.20.0` and master (a63a26f042134fa80356860c109edb25ac567552) on FreeBSD 12.1 with no issue following the instructions in [`build-freebsd.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/build-freebsd.md).

**Comment by metacreo** [comment]
`# pkg info | grep boost
boost-all-1.72.0               The "meta-port" for boost libraries
boost-docs-1.72.0              Documentation for libraries from boost.org
boost-jam-1.72.0               Build tool from the boost.org
boost-libs-1.72.0_2            Free portable C++ libraries (without Boost.Python)
boost_build-2.0.m12_13         Extensible cross-platform build tool suite
`
`# make clean
make: "/opt/bitcoin/bitcoin-0.20.0/Makefile" line 1216: Variable/Value missing from "export"
make: Fatal errors encountered -- cannot continue
make: stopped in /opt/bitcoin/bitcoin-0.20.0
`
Makefile" line 1216 "export PYTHONPATH" changed to  "export PYTHONPATH=/opt/bitcoin"

# make clean && gmake -j4

`/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7350: bitcoin-cli] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7354: bitcoin-tx] Error 1
/usr/local/bin/ld: libbitcoin_util.a(libbitcoin_util_a-system.o): in function `SetupEnvironment()':
/opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1103: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/usr/local/bin/ld: /opt/bitcoin/bitcoin-0.20.0/src/util/system.cpp:1105: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:7362: bitcoind] Error 1
gmake[2]: Leaving directory '/opt/bitcoin/bitcoin-0.20.0/src'
gmake[1]: *** [Makefile:17262: all-recursive] Error 1
gmake[1]: Leaving directory '/opt/bitcoin/bitcoin-0.20.0/src'
gmake: *** [Makefile:780: all-recursive] Error 1
`

**Comment by MarcoFalke** [comment]
Can you also try a `./autogen.sh` and then make the `distclean` target?

**Comment by metacreo** [comment]
# make distclean
make: "/opt/bitcoin/bitcoin-0.20.0/Makefile" line 1216: Variable/Value missing from "export"
make: Fatal errors encountered -- cannot continue
make: stopped in /opt/bitcoin/bitcoin-0.20.0

Makefile" line 1216 "export PYTHONPATH" changed to "export PYTHONPATH=/opt/bitcoin"

# make distclean
Making distclean in src
make[1]: "/opt/bitcoin/bitcoin-0.20.0/src/Makefile" line 19069: warning: duplicate script for target "%.raw.h" ignored
make[1]: "/opt/bitcoin/bitcoin-0.20.0/src/Makefile" line 19056: warning: using previous script for "%.raw.h" defined here
make[1]: "/opt/bitcoin/bitcoin-0.20.0/src/Makefile" line 19074: warning: duplicate script for target "%.raw.h" ignored
make[1]: "/opt/bitcoin/bitcoin-0.20.0/src/Makefile" line 19056: warning: using previous script for "%.raw.h" defined here
make[1]: "/opt/bitcoin/bitcoin-0.20.0/src/Makefile" line 19075: warning: duplicate script for target "%.raw.h" ignored
make[1]: "/opt/bitcoin/bitcoin-0.20.0/src/Makefile" line 19056: warning: using previous script for "%.raw.h" defined here
Making distclean in secp256k1
cd: secp256k1: No such file or directory
*** Error code 1

Stop.
make[1]: stopped in /opt/bitcoin/bitcoin-0.20.0/src
*** Error code 1

Stop.

**Comment by MarcoFalke** [comment]
does it also happen on a fresh clone of the repo/code?

**Comment by metacreo** [comment]
I tried this https://bitcoincore.org/bin/bitcoin-core-0.20.0/bitcoin-0.20.0.tar.gz
and tried git master https://github.com/bitcoin/bitcoin.git
the same

**Comment by MarcoFalke** [comment]
Does it happen on a fresh install of the operating system as well, if you have access to a fresh install?

**Comment by MarcoFalke** [comment]
Otherwise you could try to remove the boost libraries and reinstall them. This really sounds like a system issue on your end.

**Comment by metacreo** [comment]
Sorry, just now I only have real physical server with freebsd 12.1 mb a little later I can try to build on vm with freebsd 12.1

**Comment by metacreo** [comment]
OK. I will try reinstall boost-libs now.
What do you think? boost better install from ports or just install from pkg?

**Comment by metacreo** [comment]
BUILD SUCCESS

git clone https://github.com/bitcoin/bitcoin.git /opt/bitcoin/bitcoin

cd /opt/bitcoin/bitcoin

setenv CC /usr/bin/cc
setenv CXX /usr/bin/c++

./autogen.sh && ./configure --with-gui=no --disable-wallet MAKE=gmake && gmake clean && gmake -j4

gmake check
============================================================================
Testsuite summary for univalue 1.0.3
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

**Comment by MarcoFalke** [comment]
> BUILD SUCCESS

Good to hear. Closing
