### ISSUE TITLE
Provide skeleton bitcoin.conf during datadir generation

### ISSUE THREAD

**Issue by kcalvinalvin** [bitcoin/bitcoin#19641]
**Is your feature request related to a problem? Please describe.**

It would be helpful to provide the example bitcoin.conf provided in the source code to the users that just download the binary/install from their package manager. 

Secondly, a new bitcoind user may not be aware that bitcoin.conf file is an available option. While bitcoin.conf is mentioned in the man page, one would have to know what to look for or read a bit to get to the -conf section. By providing a skeleton file, a new user is more exposed to such an option.

**Describe the solution you'd like**

Automatically generate a skeleton bitcoin.conf with something like the one found at ```share/examples/bitcoin.conf``` when first starting bitcoind.

**Describe alternatives you've considered**

**Additional context**

**Comment by Ghorbanian** [comment]
Hello, @kcalvinalvin. Thank you for taking the time to submit this issue, however, I am having a hard time understanding how generating a skeleton conf file would help a user know about its existence. Wouldn't it be more practical to mention the option of using a conf file earlier in the man pages?

**Comment by kcalvinalvin** [comment]
I've updated the original post. Just providing the example bitcoin.conf file is beneficial to users in my opinion. If it was important enough to provide it in the source code, then it should also be important for it to be there for users that don't view the source code.

**Comment by RandyMcMillan** [comment]
I don't think setting up a scenario where a user is "tinkering" with their node configuration is advisable - changing default settings should be informed and intentional. 

With that said - people may find this useful as a learning tool...

https://jlopp.github.io/bitcoin-core-config-generator/

**Comment by adamjonas** [comment]
#13761 was an attempt at this. I think #10746 is close enough that this could be closed so that discussion is happening in one place.
