### ISSUE TITLE
Testnet reset?

### ISSUE THREAD

**Issue by Tech1k** [bitcoin/bitcoin#19666]
I was thinking, since it looks like the testnet is very hard to mine and has already had many halvings (I know they are faster). What are your thoughts on a testnet reset for the next release of Bitcoin Core? The testnet I believe should get a refresher as it's been many years since the launch of testnet3 and many altcoins are on testnet4. If you all like this, I'll submit a PR to reset the testnet.

**Comment by NicolasDorier** [comment]
I think testnet should be replaced by a signet @kallewoof

**Comment by Tech1k** [comment]
> I think testnet should be replaced by a signet @kallewoof

I think that would actually be better.

**Comment by kallewoof** [comment]
FTR, a few people do like having testnet around (I don't honestly see why, but there you have it).

Resetting it would remove all those quirky edge cases that we have piled up since last reset, for what it's worth.

**Comment by Tech1k** [comment]
> FTR, a few people do like having testnet around (I don't honestly see why, but there you have it).
> 
> Resetting it would remove all those quirky edge cases that we have piled up since last reset, for what it's worth.

I run a testnet faucet (https://testnet-faucet.com) and from knowledge, people love to hoard testnet coins. This is also another reason why I think a reset will be good. About those edge cases, all a testnet reset will do is create a new testnet chain from v0.21+. The other testnet will still be accessible until everyone upgrades from the lower versions.

**Comment by kallewoof** [comment]
Right. Question is if it stays that way for very long -- I don't know about testnet v1-2, but I assume (?) they're not syncable anymore.

**Comment by MarcoFalke** [comment]
Testnet being large is a feature, see also https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-June/017031.html and https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-August/016341.html

If you need/have control over all miners, then a private regtest is an alternative.

If you need a public network that is more predictable, then signet might be an alternative.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
