### ISSUE TITLE
Expose compact blocks high-bandwidth mode state through getpeerinfo

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#19676]
For every peer expose through `getpeerinfo` RPC whether or not we selected them as HB peers, and whether or not they selected us as HB peers.

Suggestion by @gmaxwell.

**Comment by theStack** [comment]
Wouldn't this be a tristate rather than a boolean value (Legacy/HB/LB relay), to also see if compact blocks are used at all for a peer?
