### ISSUE TITLE
Have estimatesmartfee return the max of estimate and mempool min rate

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#19699]
Seems a bit odd that you can query the block target, get a rate, make a transaction and get surprised at a 10x markup. 

https://github.com/bitcoin/bitcoin/issues/16072#issuecomment-672242785

**Comment by whitslack** [comment]
This could be good. Then front-ends that query the estimator to show a fee rate to the user would have a more accurate idea about what will happen when they actually submit a transaction using `sendtoaddress`/`sendmany`.

My concern would be for Lightning nodes, which need to agree with their peers about the current state of the fee market. If the responses from Bitcoin Core's fee estimator are being influenced by mempool memory constraints, this could trigger mass unilateral channel closures, which is **VERY** expensive.

**Comment by instagibbs** [comment]
@whitslack Any idea how your block estimator ended up giving you estimates lower than your set min mempool feerate? Seems to me this requires you to change your min rate *after* your estimator builds these estimates?

**Comment by whitslack** [comment]
> Any idea how your block estimator ended up giving you estimates lower than your set min mempool feerate? Seems to me this requires you to change your min rate _after_ your estimator builds these estimates?

@instagibbs: As I understand it, the fee estimator in Bitcoin Core uses statistical analysis of previous transaction confirmation times to build up its estimates. The `mempoolminfee` reacts to current mempool conditions.

Suppose that there is a sudden spike in transaction traffic. Fees had been low for a while; the mempool had been close to empty. Suddenly, someone drops a million transactions onto the network. This will have no immediate effect on Bitcoin Core's fee estimator (sadly), but it will absolutely bump up `mempoolminfee` immediately.

**Comment by adamjonas** [comment]
closed by #22722
