### ISSUE TITLE
New transaction created as abandoned

### ISSUE THREAD

**Issue by liorko87** [bitcoin/bitcoin#19703]
**Expected behavior**
Confirmed transaction will be added to a block

**Actual behavior**
I'm creating transaction using the RPC call `sendtoaddress`. When I'm debugging my code, I see that every new transaction get `true` value from `isAbandoned` from the wallet.

**To reproduce**
From a terminal run:
```
./bitcoind --datadir=/home/user/bitcoinNodes/node1 & ./bitcoind --datadir=/home/user/bitcoinNodes/node2 &
./bitcoin-cli --datadir=/home/user/bitcoinNodes/node1 sendtoaddress "address" 0.6
```
`getmempoolinfo` output:
```
{
  "loaded": true,
  "size": 22,
  "bytes": 3102,
  "usage": 26640,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000
}

```

**System information**
i'm usibg bitcoin v020.1 on Ubuntu 20.01 LTS

**Comment by MarcoFalke** [comment]
what is the return value from sendtoaddress?

**Comment by MarcoFalke** [comment]
what is the debug log when sendtoaddress is called? Also, `gettransaction` and `getmempoolentry`?


Sounds like the tx chain limit to me.

**Comment by liorko87** [comment]
I found the bug myself:  
The amount of the transaction was incorrect. After I fixed it the transaction were added.
