### ISSUE TITLE
qa: Intermittent failure in `p2p_permissions.py` "Unable to connect to bitcoind after 60s"

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19711]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/717591231#L2562

Similar to #18834.

**Comment by hebasto** [comment]
Sorry: forgot to re-open the pull instead of just job restarting...

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
