### ISSUE TITLE
test: Data race detected when running rpc_blockchain.py

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19712]
https://cirrus-ci.com/task/6068765160898560?command=ci#L5518

**Comment by MarcoFalke** [comment]
I can't make any sense of those data races. Now that we implement our own double lock detection in #19337, we should revert the broken clang tsan (#19041) and potentially provide  instructions how a non-broken tsan can be selected on systems that ship with the clang tsan by default (fedora, maybe freebsd?, ...)

**Comment by MarcoFalke** [comment]
Actually, I could (intermittently) reproduce on libc++ and libstdc++
