### ISSUE TITLE
Deprecate banlist.dat

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#19748]
`banlist.dat` was introduced in https://github.com/bitcoin/bitcoin/pull/6310, storing nodes that were automatically banned (due to exceeding the misbehavior threshold) and manually banned (through the `setban` RPC).

Automatic bans were removed in https://github.com/bitcoin/bitcoin/pull/19219 and replaced with a discouragement filter. That filter is not saved to disk/persisted over shutdown/startup. The `banlist.dat` therefore now only contains addresses that have been banned through the `setban` rpc.

Since https://github.com/bitcoin/bitcoin/pull/15935, we have a specific file for configuration that is updated through the RPC and persisted over shutdown/startup, namely `settings.json`. We should therefore move the manual ban configuration from `banlist.dat` to `settings.json`. Doing so has a couple of benefits:

- `settings.json` is human readable and easily analyzable by any json parser.
- we wouldn't need to maintain custom [de]serialization code for the `banlist.dat` file.

`banlist.dat` is expected to be fairly small and infrequently updated, so disk space/performance are not huge concerns.

**Comment by jnewbery** [comment]
@ryanofsky do you agree that this is a good use case for settings.json? The only unusual thing about the ban list is that items have expiry times, after which they should be removed from the config. Would that involve frequently reserializing the entire settings.json file?

**Comment by ryanofsky** [comment]
I think a json file would be a nice way to store this information (easy to read, write, and inspect), but that it would be better to use a different json file than settings.json if entries auto-expire and would be removed without user intervention. Also if there is a use-case for wanting to allow manual bans and run bitcoin with `-nosettings` or with the settings file in a read-only location, it could be another reason to use a different file.

But thinking of settings.json as storage more under user control is just my own inclination. Best to chose an approach based on concrete advantages and disadvantages.

**Comment by jnewbery** [comment]
Each ban entry has an expiry time set by the user (with a default of 24 hours in the future). The software doesn't make any autonomous decisions about expiring the ban. So one way to do this that is in line with the settings.json usage would be to only lazily remove the entries from the json either when the user bans/unbans an address or during shutdown.

**Comment by tryphe** [comment]
Concept ACK, could go either way on a separate/monolithic file, but favor a separate file. Also favor a super-lazy file writer.

**Comment by jonatack** [comment]
Concept ACK. Tend to agree with @ryanofsky on preferring keeping a separate `banlist.json` file. Keeping banned peers in their own file as a separate concern seems clearer and more convenient for users, the only observable change for them being the file format (a more convenient one).

**Comment by vasild** [comment]
Concept ACK.

This would make it possible to store ban entries of Torv3 addresses and would supersede #20904.

Given that we dump the banlist periodically, it may be easier to implement if data is saved to its own file, e.g. `banlist.json`, rather than in `settings.json`.

**Comment by vasild** [comment]
A tentative implementation is at https://github.com/bitcoin/bitcoin/pull/20966.
