### ISSUE TITLE
Intermittent CI failure: wallet_groups.py

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19749]
Intermittent CI failure: `wallet_groups.py`

Details:

* https://github.com/bitcoin/bitcoin/pull/19739/checks?check_run_id=993306684
* https://cirrus-ci.com/task/5395389866049536

**Comment by jonatack** [comment]
It's from just-merged 7f13dfb587dd6a7a5b7dfbfe689ae0ce818fe5c9 in #14582. A fix should be added in follow-up PR #19743. @kallewoof looks like a data race, may need a `sync_all()` call or something.

**Comment by jonatack** [comment]
It's from just-merged 7f13dfb587dd6a7a5b7dfbfe689ae0ce818fe5c9 in #14582. A potential fix may have been made in here: https://github.com/bitcoin/bitcoin/pull/19743#discussion_r471549351. Looks like a data race that hopefully a `self.sync_all()` can settle.

**Comment by MarcoFalke** [comment]
Another one: https://cirrus-ci.com/task/6413622110846976?command=ci#L4940

**Comment by ryanofsky** [comment]
Various PR's I've tried to update today seem to have this test failure, too

https://travis-ci.org/github/bitcoin-core/gui/jobs/718590689#L3324
https://cirrus-ci.com/task/5166287036874752?command=ci#L1393
https://cirrus-ci.com/task/4784155206615040?command=ci#L1411
https://travis-ci.org/github/bitcoin/bitcoin/jobs/718717501#L3327
https://cirrus-ci.com/task/4528049808998400?command=ci#L1451
https://cirrus-ci.com/task/6437719427514368?command=ci#L1238
https://travis-ci.org/github/bitcoin/bitcoin/jobs/718702350#L3326
https://cirrus-ci.com/task/6532119117692928?command=ci#L1411
https://cirrus-ci.com/task/5150897095311360?command=ci#L1126

**Comment by kallewoof** [comment]
Frustrating. None of my machines exhibit this no matter how many times I try. Focusing on this now.
