### ISSUE TITLE
Intermittent CI failure: rpc_psbt.py --descriptors

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19744]
Intermittent CI failure: `rpc_psbt.py --descriptors`

The PR in question ("tests: Add fuzzing harness for TorController", #19288) is not touching anything PSBT related :)

Details:

* https://github.com/bitcoin/bitcoin/pull/19288/checks?check_run_id=985814534
* https://cirrus-ci.com/task/5558273334050816

**Comment by MarcoFalke** [comment]
It says "OOM", but it didn't look like the 6GB were all used up. Nonetheless, you could try bumping it to 8GB to see if the issue re-appears.
