### ISSUE TITLE
Coins have not appeared in to my wallet what can I do

### ISSUE THREAD

**Issue by w3bst3r67** [bitcoin/bitcoin#19769]
#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by w3bst3r67** [comment]
Sorry I have no idea of anything coding I would just like to be able retrieve my money.

**Comment by laanwj** [comment]
This is not a support forum. You could try asking on the [bitcoin stack exchange](https://bitcoin.stackexchange.com/). But you'll have to provide more details.
