### ISSUE TITLE
Bitcoin Core does not immediately use the fixed seed nodes if DNS seeding is disabled (-dnsseed=0)

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19795]
**Expected behavior**: Disabling DNS seeding (`-dnsseed=0`) should make Bitcoin Core use the fixed seed nodes immediately on startup (assuming an empty `peers.dat`).

**Actual behavior**:  The fixed seed nodes are used but only after an unnecessary 60 second timeout, and a somewhat misleading log message ("Adding fixed seed nodes as DNS doesn't seem to be available.").

**To reproduce**: `rm ~/.bitcoin/peers.dat && src/bitcoind -dnsseed=0` and wait... 💤 

This issue is probably a "good first issue" :)

**Comment by dhruv** [comment]
I'll try to work on this and report back.

**Comment by practicalswift** [comment]
@dhruv That's great! Don't hesitate to ping me when you're ready for review :)
