### ISSUE TITLE
configure: error: Found Berkeley DB other than 4.8,

### ISSUE THREAD

**Issue by songproducer** [bitcoin/bitcoin#19798]
configure: error: Found Berkeley DB other than 4.8,

for configure to work

100% fail

latest

ubuntu

19.10

**Comment by jonatack** [comment]
See step 3 in https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests

**Comment by jonatack** [comment]
If you have another version of BDB already installed that you wish to use, add --with-incompatible-bdb to your ./configure options.

**Comment by MarcoFalke** [comment]
Without an error message there is nothing we can do other than guess. @jonatack 's suggestion might help you. If it doesn't please include more details.
