### ISSUE TITLE
rpc: pipe support for submitblock

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#19819]
If you use the `submitblock` RPC with a large enough block you'll run into "argument list too long". Using a pipe should fix this, at least on Linux / macOS.

The `submitblock` RPC can be useful to check validity of a stale block that never made it into the main chain (and that your node never fetched): call `invalidateblock` on its same-height-sibling and then feed it the raw block.

Easiest workaround is to use a library that connects directly to `bitcoind` via RPC (be careful to avoid a line break character at the end). Using the GUI console fails with "Block decode failed" for me, but haven't tested that extensively.

**Comment by MarcoFalke** [comment]
Previous reports:
* #14767

**Comment by ryanofsky** [comment]
Is ulimit any help? https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command

**Comment by Sjors** [comment]
Sadly not. The max macOS allows is `ulimit -s 65532` which doesn't make the error go away.

**Comment by laanwj** [comment]
Did you try `bitcoin-cli -stdin`?

**Comment by Sjors** [comment]
Genious!

```
cat block.txt | bitcoin-cli -stdin submitblock
```
