### ISSUE TITLE
Signrawtransactionwithwallet when using segwit and previous transactions provided

### ISSUE THREAD

**Issue by liorko87** [bitcoin/bitcoin#19814]
**Expected behavior**
The transaction will be sent to the other node.

**Actual behavior**
When calling `sendrawtransaction`, the provided output is:
```
error code: -26
error message:
non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)
```

**To reproduce**
```
./bitcoin-cli --datadir=/home/user/bitcoinNodes/node2 signrawtransactionwithwallet \
02000000018a0cd4d224a023fd8ee2cbc43451fb01a853c55ec009b34145c464da1e0c4b5a0000000000ffffffff02e00f9700000000001600140845db2986a7dba1f41bc3fac2617965da9d70e90000000000000000136a1149204b4e4f5720424c4f434b434841494e00000000 \
'[{"txid": "5a4b0c1eda64c44541b309c05ec553a801fb5134c4cbe28efd23a024d2d40c8a", "vout":0, "scriptPubKey": "00141b35076bfdb3e38c99dce3f73895009bd650191e", "amount":0.099}]'
```

**System information**
OS: Ubuntu 20.04.1 LTS
Bitcoin version: 0.20

**Comment by prayank23** [comment]
What happens if you don't mention the optional second argument and only mention serialized hex with 'signrawtransactionwithwallet' ?

**Comment by liorko87** [comment]
The same is happening when I'm don't mention the second argument.
Anyway, I solved it- the error relate to the amount of the transaction. I inserted the amount of the output transaction and not the input transaction.  
After I changed it the error disappeared. 
A clearer error message will help to debug this problem in the future.

**Comment by adamjonas** [comment]
Closing given the issue was filed based on switching the output and input transaction amount. Noting that a better error message would be helpful but closing for now.
