### ISSUE TITLE
Signing Transactions on Offline Computer without Blockchain

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#19810]
**Is your feature request related to a problem? Please describe.**
I am working with a team on Yeti (https://github.com/JWWeatherman/yeticold), which is a script for a UI for setting up offline, HD multisig with only minimal software beyond Bitcoin Core.  Only QR codes are used for transferring private keys.  As Core continues to merge PRs on offline, multisig, and UI work, Yeti will remove its own written code for the more peer reviewed Core releases.  The goal is that Yeti is eventually not needed at all.

Currently, Core needs a blockchain to sign transactions, even if the wallet is offline (and doesn't truly need a blockchain).  This means that although the wallet is getting the data it needs to sign from the QR code, the process now must look like this:

The computer needs to be online for days first in order to sync the blockchain (even though it'll never be used), then network access can be disabled, and descriptors generated.  This could be made much simpler without having to sync.

**Describe the solution you'd like**
I know there is a lot of work on making Core more modular (https://github.com/bitcoin/bitcoin/projects/10).  Once that project is finished, is it part of the plan to be able to sign transactions without a blockchain present?

**Comment by sipa** [comment]
PSBT signing works fine without the blockchain synced.

**Comment by MarcoFalke** [comment]
Offline signing should work out of the box. Please include the error message you encounter.

**Comment by willweatherman** [comment]
Hi, I am Will Weatherman, also working on yeti. The error I am running into is:
"error": "Input not found or already spent"
When signing a raw transaction with the key without the blockchain synced.

**Comment by willweatherman** [comment]
I have been able to sign a transaction with a blockchain out of sync by a couple of transactions by specifying the utxos in between but that would not work when you have 20 years of utxos to trace back to the original transaction.

**Comment by sipa** [comment]
You can't create a spending transaction without knowing the UTXOs that it spends, so that information has to come from somewhere - there is no way around that. It can come from the chainstate (built when syncing the blockchain), be passed as an RPC argument to `signrawtransaction*`, or come all together with the rest of the transaction to sign using PSBT.

If you don't have the blockchain, you'll need to pass it using one of the other methods.

**Comment by willweatherman** [comment]
Just figured out how to use the PSBTs and sign a transaction without the blockchain. This will save yeti users days of waiting for the blockchain to download. Thank you.

**Comment by Rspigler** [comment]
I misunderstood the error.  My apologies.  Thank you for your help!

Closing.
