### ISSUE TITLE
ci: previous_release.py fails for C++17 Travis job on forked repo

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19812]
https://travis-ci.org/github/hebasto/bitcoin/jobs/721269536

**Comment by MarcoFalke** [comment]
This is a know issue/oversight. See https://github.com/bitcoin/bitcoin/pull/19013#issuecomment-667087221

**Comment by hebasto** [comment]
In #19013 I found a workaround, but not the root of the issue :)

**Comment by MarcoFalke** [comment]
The issue is that gpg isn't installed. Even if it was installed, it would reject the signatures as untrusted because the keys haven't been marked trusted nor has gpg been told to use a different trust model.

**Comment by hebasto** [comment]
> The issue is that gpg isn't installed. Even if it was installed, it would reject the signatures as untrusted because the keys haven't been marked trusted nor has gpg been told to use a different trust model.

So why it works for the GUI repo which is also forked?

**Comment by MarcoFalke** [comment]
The script isn't run when the release folder already exists in the cache

**Comment by hebasto** [comment]
> The script isn't run when the release folder already exists in the cache

So if Travis cache were cleaned the builds would be broken even in this repo?
