### ISSUE TITLE
improve scripted-diff check

### ISSUE THREAD

**Issue by amitiuttarwar** [bitcoin/bitcoin#19815]
#### Context: 

[Scripted diffs](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#scripted-diffs) are a way to automate some types of reformatting or refactoring changes. When a commit message matches a specific format (begins with `scripted-diff:`), CI will run [commit-script-check.sh](https://github.com/bitcoin/bitcoin/blob/master/test/lint/commit-script-check.sh). 

`sed` is platform dependent. One significant difference is when using the `-i` flag. On BSD (eg. macOS), you have to insert an empty string, but with GNU sed (used by Travis), this is compatible. 

example of a working command for these two platforms- 
macOS: `sed -i '' 's/a oneshot/an addrfetch/g' src/chainparams.cpp`
Travis: `sed -i 's/a oneshot/an addrfetch/g' src/chainparams.cpp`

#### Task: 

Add logic to the `commit-script-check.sh` to detect if the scripted diff is using the BSD sed syntax and print a helpful error message.

#### Useful skills:

Bash

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by Z5483** [comment]
Another way to make `sed` portable is to just append `''` after `-i` like the following:

`sed -i'' 's/a oneshot/an addrfetch/g' src/chainparams.cpp`

Is it okay to use this instead of trying to detect which sed the script is using?

**Comment by Z5483** [comment]
You can also use append empty string directly after `-i` to make `sed -i` work on both GNU and BSD `sed`:

`sed -i'' 's/a oneshot/an addrfetch/g' src/chainparams.cpp`

I want to work on this, but I think it is good to recommend people to do the above for portability for now.

**Comment by amitiuttarwar** [comment]
@Z5483 hi! thanks for taking a look & opening a PR!

I tried this trick out locally (macOS), but got an error... actually, I'm getting different errors on each try 👀  
(but doing `-i ''` is working fine) 

<details><summary>my attempts, incase you're curious</summary>

example 1: `sed -i'' 's/MempoolUnbroadcastTest/LaLaLaTest/g' test/functional/mempool_unbroadcast.py`
error: `sed: 1: "test/functional/mempool ...": undefined label 'est/functional/mempool_unbroadcast.py'`

example 2: `sed -i'' 's/CMainParams/SuperImportantParams/g' src/chainparams.cpp`
error: `sed: 1: "src/chainparams.cpp": unterminated substitute in regular expression`

example 3: `sed -i'' 's/MAX_FEELER_CONNECTIONS/MAX_FEELS/g' src/net.h`
error `sed: 1: "src/net.h": unterminated substitute pattern`
</details>

but I see you've opened a patch to update the script, so I'll check that out :)

**Comment by m-s-32** [comment]
چقدر باحاله اینجا

**Comment by robot-dreams** [comment]
@Z5483 Thanks for working on this! I've ran into some `scripted-diff` issues as well, and I'm very excited to see that you're improving it :)

@amitiuttarwar I'm a MacOS user as well, and I ran into the following issue; did you ever encounter this as well?

```
$ ./test/lint/commit-script-check.sh 85165d4~..85165d4
sed: 1: "/^-BEGIN VERIFY SCRIPT- ...": unexpected EOF (pending }'s)
Error: missing script for: 85165d4332b0f72d30e0c584b476249b542338e6
Failed
```

I fixed it locally by installing `gsed` and creating a symbolic link. But do you think it would make sense to add something like the following to help future MacOS users?

<img width="905" alt="Screen Shot 2020-09-16 at 3 31 54 PM" src="https://user-images.githubusercontent.com/4276679/93399130-c2974180-f831-11ea-9459-dbd5e0425254.png">

After making this change, here's the new output:

```
$ ./test/lint/commit-script-check.sh 85165d4~..85165d4
sed: 1: "/^-BEGIN VERIFY SCRIPT- ...": unexpected EOF (pending }'s)
Error: Incompatible version of sed; MacOS users should install gsed
Failed
```

**Comment by ArtemVinter** [comment]
its nice)

**Comment by bitkarrot** [comment]
I'm signing up for this task because @bliotti wants me to work on it as "I'm way overdue for a bitcoin commit" as a Jimmy Song Alumni, using my public face here.

**Comment by bliotti** [comment]
Awesome! @bitkarrot looks like this one has not been touched for a while. IMO it is safe to grab for now.

**Comment by bliotti** [comment]
@bitkarrot Awesome! Looks like a good one, I wonder where this one stands now. @amitiuttarwar

**Comment by Z5483** [comment]
Feel free to work on this. I scrapped my PR because I didn't put time into it so it's horrible. I'm busy with schools for the rest of the school year so I don't think I will pick this up again anytime soon. I hope you guys can produce something better.

**Comment by wodry** [comment]
Catching sed syntax usage that leads to unexpected results is not a low hanging fruit I guess :)

Maybe you should pimp your own script like so:
```
kernel_name="$(uname -s)"

case "${kernel_name}" in
    Linux*)     sed_option='-i'
                ;;
    Darwin*)    sed_option='-i ""'
                ;;
    *)          echo "Unknown kernel name: '${kernel_name}'"
                exit 1
esac

sed $sed_option 's/a oneshot/an addrfetch/g' src/chainparams.cpp

```
With that, you can define all specialities needed for different environments. You could pimp it even more like checking the the version etc.

Maybe you could create a PR to add this as a template to https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#suggestions-and-examples

**Comment by bitkarrot** [comment]
Looking into it but also going on holiday vacation; will be back in the new year

**Comment by kvkenyon** [comment]
Anyone working on this now?  @bitkarrot @amitiuttarwar

**Comment by amitiuttarwar** [comment]
@kvkenyon looks like #21002 and #21020 are open as proposals to improve this. would be helpful to review those :)

**Comment by bliotti** [comment]
> @Z5483 Thanks for working on this! I've ran into some `scripted-diff` issues as well, and I'm very excited to see that you're improving it :)
> 
> @amitiuttarwar I'm a MacOS user as well, and I ran into the following issue; did you ever encounter this as well?
> 
> ```
> $ ./test/lint/commit-script-check.sh 85165d4~..85165d4
> sed: 1: "/^-BEGIN VERIFY SCRIPT- ...": unexpected EOF (pending }'s)
> Error: missing script for: 85165d4332b0f72d30e0c584b476249b542338e6
> Failed
> ```
> 
> I fixed it locally by installing `gsed` and creating a symbolic link. But do you think it would make sense to add something like the following to help future MacOS users?
> 
> <img alt="Screen Shot 2020-09-16 at 3 31 54 PM" width="905" src="https://user-images.githubusercontent.com/4276679/93399130-c2974180-f831-11ea-9459-dbd5e0425254.png">
> 
> After making this change, here's the new output:
> 
> ```
> $ ./test/lint/commit-script-check.sh 85165d4~..85165d4
> sed: 1: "/^-BEGIN VERIFY SCRIPT- ...": unexpected EOF (pending }'s)
> Error: Incompatible version of sed; MacOS users should install gsed
> Failed
> ```

What was wrong with solution, with a simple error message to use gsed? or will  #21002 ultimately replace this Issue.

**Comment by anouarkappitou** [comment]
Hello guys, i would love to work on this issue.
