### ISSUE TITLE
test: Remove confusing connect_nodes global

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#19821]
`connect_nodes(self.nodes[a], b)` is confusing because

* the types of the arguments differ
* the test framework is aware of all nodes, so solving `a` to `self.nodes[a]` can be done hidden from the caller

This should be fixed by replacing `connect_nodes(self.nodes[a], b)` with `self.connect_nodes(a, b)` and removing the global `connect_nodes`.

**Comment by slmtpz** [comment]
Can I also pick this up? Or do you have a "good second issue" for me that does not have a lot of bitcoin logic yet and could help me understand further?

**Comment by MarcoFalke** [comment]
@slmtpz You may also help with review, as explained in https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#contributing-to-bitcoin-core Currently there are about 400 open pull request, so I am sure there is something in for you.

If not, apart from the [good first issue](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)s, there are also ones that are [up for grabs](https://github.com/bitcoin/bitcoin/issues?utf8=%E2%9C%93&q=label%3A%22Up+for+grabs%22). Some of them might no longer be applicable. So if you are interested, but unsure, you might want to leave a comment on the issue first.

Generally, you can also write tests to improve the coverage. Any kind of test is welcome and coverage information can be obtained from a relatively recent [coverage report](https://marcofalke.github.io/btc_cov). If you are unsure, don't hesitate to check back first.

**Comment by prayank23** [comment]
So we just need to replace connect_nodes(self.nodes[a], b) with self.connect_nodes(a, b) and remove the global connect_nodes ?

https://github.com/search?l=&q=connect_nodes+repo%3Abitcoin%2Fbitcoin%2Ftest&type=Code

For example:

Remove line 42 https://github.com/bitcoin/bitcoin/blob/cb1ee1551cf39905ccb67e3d07b0e3aaaca18ce3/test/functional/wallet_backup.py#L42

And replace line 65,66 and 67 here: https://github.com/bitcoin/bitcoin/blob/cb1ee1551cf39905ccb67e3d07b0e3aaaca18ce3/test/functional/wallet_backup.py#L65

with following:

`self.connect_nodes([0], 3)`
`self.connect_nodes([1], 3)`
`self.connect_nodes([2], 3)`
`self.connect_nodes([2], 0)`

**Comment by MarcoFalke** [comment]
@prayank23 Yes

**Comment by prayank23** [comment]
@MarcoFalke Made the changes in 38 files

Commit: https://github.com/prayank23/bitcoin/commit/3c3074074e036aa7caa9474f51ea0db0af915460

Not sure if anything has to be changed in below files:

[/test/functional/mempool_unbroadcast.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/mempool_unbroadcast.py)
[/test/functional/test_framework/test_framework.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/test_framework.py)

**Comment by robot-dreams** [comment]
Thanks again for working on this, @prayank23 !

As mentioned in the #19945 discussion, in #19967 I've built on your work to use scripted-diff as suggested (while keeping you as the author for the relevant commit).

@MarcoFalke Do you have any additional context about why we might not want to update `disconnect_nodes` as well?
