### ISSUE TITLE
Improve thread safety annotation coverage

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19838]
Clang [Thread Safety Analysis](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html) (TSA) is a C++ language extension which warns about potential race conditions in code.

To improve our code base it is desirable to review all cases of `Mutex` (non-recursive) class/struct member mutexes, add TSA annotations to method declarations (including negative ones), and add corresponding lock assertions to method definitions.

#### Useful skills:

Clang compiler experience, basic understanding of Thread Safety Analysis.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by hebasto** [comment]
@MarcoFalke @fanquake Mind labeling this issue?

**Comment by n1rna** [comment]
I would like to take this issue as I think the required knowledge is not much far away from my level to grasp on.

For better understanding the desired changes, I have a few questions.

* I searched `^\s*Mutex\s*\w*;` on all files and found roughly 24 places where a `Mutex` is defined. Are these all the mutexes used throughout the code base? (You mentioned only non-recursive `Mutex`es)
* Should I review usage of each of these `Mutex`es and add annotations like `ACQUIRE` or `RELEASE` to declaration of methods that are utilizing a `Mutex`?
* Last question is regarding `WAIT_LOCK`, does this indicate the lock is being released?

**Comment by hebasto** [comment]
As currently some discussions about proper lock assertions get started (#19865, #19918, #19929), going to close this issue for now.

@n1rna 
>  - Last question is regarding `WAIT_LOCK`, does this indicate the lock is being released?

Yes, when the lock goes out of scope.
