### ISSUE TITLE
Intermittent failure in feature_fee_estimation.py "Estimated fee larger than last fee"

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19837]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/722332373#L3292

**Comment by instagibbs** [comment]
I don't see any failures in the link?

**Comment by hebasto** [comment]
Hmm... I'm sure I've made the "close PR - reopen PR" routine to conserve Travis build log.

Closing.
