### ISSUE TITLE
Script interpreter cleanups

### ISSUE THREAD

**Issue by ariard** [bitcoin/bitcoin#19875]
Extracting this topic from #17977 as during its review general cleanups of the script interpreter clean have been advocated.

Given that taproot implementation review is already far advanced, I think no one is proposing to address them now ? This issue is more to track interesting points raised.

I guess there is at least two different axis which have been under discussion (but they may overlap a bit):
* @theuni has a branch splitting consensus from policy : https://github.com/theuni/bitcoin/commits/policy-split2. As of today, it sounds like the distribution of consensus and policy checks is fairly arbitrary and may lead to confusion on expected behaviors (see https://github.com/bitcoin/bitcoin/pull/17977#discussion_r483335562)
* @JeremyRubin was proposing to split further interpreters (see https://github.com/bitcoin/bitcoin/pull/17977#issuecomment-667475959). Taproot is complexifying the script rules matrix thus making it hard to reason on in the prevision of future script softforks

If you have more comments worthy to be pinned please add them.

**Comment by JeremyRubin** [comment]
https://github.com/bitcoin/bitcoin/pull/15969 was a relevant PR where some of this was also discussed.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Comment by ariard** [comment]
Yeah I still think if it would be nice if we had a board of per-susbsytem (script, mempools, validation, net_processing, etc) refactoring suggestions (maybe in the wiki ?), that could serve as a source of inspirations for any contributors with the patience to do careful refactoring. We're still loosing a lot of low-level codebase context across the year and I would bet discussions about cleaning up the script interpreter are going to pop up again next time we do substantial modifications there :)
