### ISSUE TITLE
getblockstats RPC command has issues

### ISSUE THREAD

**Issue by denis2342** [bitcoin/bitcoin#19885]
the command "bitcoin-cli getblockstats 0000000000000000000c61ff8f761ce509fc8901d3c22d61fec89637042ea2ba" does not work.

It displays "error: Error parsing JSON:0000000000000000000c61ff8f761ce509fc8901d3c22d61fec89637042ea2ba"

but it should display the block stats like the documentation says.

also bitcoin-cli getblockstats 0 does not work. block number must be at least 1 to work. But blocks start at 0.

tested with 0.20.1 on freebsd, another user on IRC acknowledged the problem.

**Comment by n-thumann** [comment]
`bitcoin-cli getblockstats '"0000000000000000000c61ff8f761ce509fc8901d3c22d61fec89637042ea2ba"'`(notice the quotation marks) should work :)
`bitcoin-cli getblockstats 0` doesn´t work for me either 🤔

**Comment by fjahr** [comment]
Thanks for reporting this. The JSON parsing error is expected and @n-thumann shows how it should be formatted. I pushed a fix for the block height 0 issue in #19888.

**Comment by denis2342** [comment]
but the quotation marks for getblockstats  inconsistent with the other commands, this is very irritating

**Comment by fjahr** [comment]
> but the quotation marks for getblockstats are inconsistent with the other commands, this is very irritating.

I see what you mean. This is not an issue with this RPC in particular but with the `bitcoin-cli` itself. There is one approach to fix this pending here: https://github.com/bitcoin/bitcoin/pull/15448 but it seems to have stalled for over a year now. I have opened a fix using an alternative approach here https://github.com/bitcoin/bitcoin/pull/19949 which might be favored more by reviewers.
