### ISSUE TITLE
Fail to build on Fedora 32

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19892]
```
$ cat /etc/system-release
Fedora release 32 (Thirty Two)
$ gcc --version | grep gcc
gcc (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)
$ make --version
GNU Make 4.2.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ git rev-parse HEAD
03689317021a72431762c1974530f2a980a7fffa
$ ./autogen.sh 
$ ./configure
$ make clean
$ make
...
  CXX      libbitcoin_common_a-warnings.o
  AR       libbitcoin_common.a
bfd plugin: script/libbitcoin_common_a-descriptor.o: file too short

/usr/bin/ranlib: out of memory allocating 7701297037312 bytes after a total of 774144 bytes
make[2]: *** [Makefile:7481: libbitcoin_common.a] Error 1
make[2]: Leaving directory '/home/hebasto/bitcoin/src'
make[1]: *** [Makefile:18954: all-recursive] Error 1
make[1]: Leaving directory '/home/hebasto/bitcoin/src'
make: *** [Makefile:797: all-recursive] Error 1
```

**Comment by fanquake** [comment]
> /usr/bin/ranlib: out of memory allocating 7701297037312 bytes after a total of 774144 bytes

This looks like you ran out of memory. Building on Fedora 32 works fine.

**Comment by hebasto** [comment]
> > /usr/bin/ranlib: out of memory allocating 7701297037312 bytes after a total of 774144 bytes
> 
> This looks like you ran out of memory. Building on Fedora 32 works fine.

That was my first thought too. Monitoring with `watch free` did not show any problems.
It is a VM with 16 GB RAM, and `make` is running without `-j` option.

**Comment by MarcoFalke** [comment]
Could be a hard drive failure. Try `rm -r ./src && git restore ./src` (only if you have no changes in ./src that you want to keep!)

**Comment by hebasto** [comment]
> Could be a hard drive failure. Try `rm -r ./src && git restore ./src` (only if you have no changes in ./src that you want to keep!)

Did not help, unfortunately.

**Comment by MarcoFalke** [comment]
Does a fresh clone help? Does a fresh install of the OS help?

**Comment by hebasto** [comment]
> Does a fresh clone help?

No.

> Does a fresh install of the OS help?

Yes! Thank you @MarcoFalke!
