### ISSUE TITLE
Onion address in Bitcoin Core Wallet

### ISSUE THREAD

**Issue by prayank23** [bitcoin/bitcoin#19924]
**Is your feature request related to a problem? Please describe.**

I am not sure if there is a RPC method available to directly get the onion address used so I checked it in `localaddresses` returned by `getnetworkinfo` https://developer.bitcoin.org/reference/rpc/getnetworkinfo.html

It was also mentioned in debug.log file:

![image](https://user-images.githubusercontent.com/13405205/92579623-0e367200-f2ab-11ea-9815-f549f3a3756e.png)

**Describe the solution you'd like**

I would love to see an onion address and maybe qr code in the wallet if it is listening on Tor similar to [ABCore](https://github.com/greenaddress/abcore/blob/cc629a854f3083cf4bd1a743de80a254c72aa8ea/app/src/main/java/com/greenaddress/abcore/RPCIntentService.java#L134):

![image](https://user-images.githubusercontent.com/13405205/92579987-800ebb80-f2ab-11ea-9d02-fc8744a9c10c.png)

**Describe alternatives you've considered**

Check the onion address in debug.log or `localaddresses` returned for `getnetworkinfo`

**Additional context**

Linked to https://github.com/bitcoin/bitcoin/issues/19923 because if we add such option to check the onion address, it will have to be added in the [Tor documentation](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md).

**Comment by Willtech** [comment]
This would be kinda cool per the example.
> We can mention "How to check onion address"? : #19924

**Comment by jonatack** [comment]
I'm planning to propose an addition to `doc/tor.md` similar to this in #19961, among other changes. The PR is still in draft status but will be open soon.
```diff
+## Seeing feedback on your Tor configuration via Bitcoin Core
+
+From Bitcoin Core, you may see your local onion address:
+
+- in the debug log (grep for "AddLocal")
+- in the output of RPC `getnetworkinfo` in the "localaddresses" section
+- in the output of the CLI `-netinfo` peer connections dashboard
+
+Use the `-debug=tor` config logging option to see more information in the debug
+log about your onion configuration.
```

**Comment by Willtech** [comment]
Good Afternoon,

Thank-you for proposing to the groups consideration. You may find with
what you describe it is more fruitful to write up a Feature Request as
a type of [issues](https://github.com/bitcoin/bitcoin/issues) for each
function, though it should be useful to reference the existing FR
providing for renewal of .onion address.

KING JAMES HRMH 
Great British Empire

Regards,
The Australian
LORD HIS EXCELLENCY JAMES HRMH (& HMRH)
of Hougun Manor & Glencoe & British Empire
MR. Damian A. James Williamson
Wills

et al.

 
Willtech
www.willtech.com.au
www.go-overt.com
and other projects
 
earn.com/willtech
linkedin.com/in/damianwilliamson


m. 0487135719
f. 61261470192


--
