### ISSUE TITLE
Improve Tor support documentation

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#19923]
**Is your feature request related to a problem? Please describe.**

I think we can add few things in https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md to make it easier and better for users to use Bitcoin over Tor

**Describe the solution you'd like**
1. Add few examples to run Bitcoin as onion service: https://bitcoin.stackexchange.com/questions/98913/how-to-run-bitcoin-core-as-onion-service-on-windows-ubuntu-and-android

2. Add information about use of tor bridges and safe ways to connect over tor: https://bitcoin.stackexchange.com/questions/98772/what-are-the-safe-ways-to-connect-to-bitcoin-network-using-tor

3. If we can't add everything in [tor.md](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md), maybe add more docs for separate platforms and issues. Example: `tor-win`, `tor-linux`, `tor-privacy`

**Describe alternatives you've considered**
I have tried to experiment, research and share things on https://bitcoin.stackexchange.com to discuss about tor related setups involved in using Bitcoin

**Additional context**

I am only suggesting few ideas based on my research and observation. I am sure people who use or build things related to Tor and more experienced than me are involved in Bitcoin so maybe we can improve the docs related to 'Tor Support'.

**Comment by Willtech** [comment]
This request is really about Tor and not about Bitcoin since it is not even available programmatically to Bitcoin. There is already /doc/tor.md
> Examples to run Bitcoin as onion service, use of tor bridges and safe ways to connect over tor: #19923

**Comment by prayank23** [comment]
> There is already /doc/tor.md

It doesn't have any examples. Running Bitcoin as onion service is about Bitcoin and related to Tor, Privacy etc.

**Comment by jonatack** [comment]
On this topic, #19961 was merged but #20757 is open with ideas from @Saibato and myself and ready for review.
