### ISSUE TITLE
Need BTC Testnet (Faucet)

### ISSUE THREAD

**Issue by Droppix** [bitcoin/bitcoin#19925]
Hi,

I need to do advanced testing on testnet, but I would need between 10-15 BTC, could someone send me to the following address: tb1qs25dr4e8k29rwclxvnxedfdtprh5e89jtp5wle

Many thanks

**Comment by MarcoFalke** [comment]
If you haven't received testnet coins yet, you can ask on `#bitcoin` (freenode)

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base.
