### ISSUE TITLE
Fatal performance when importing 151M private keys

### ISSUE THREAD

**Issue by pbies** [bitcoin/bitcoin#19921]
Earlier I was importing several thousands of private keys to Bitcoin Core and it took much time, especially rescan of the blockchain. Few hours, >3 surely.

But now, when I am importing 151M private keys (10 GB file with keys) the import process is now taking 2 days and I have 65% for now.

How badly Bitcoin Core is written is unbelivable. There is no other way to scan such an amount of keys, because other apps are for private, limited use and do not offer scanning the blockchain with such a large amount of keys.

Will this be fixed or even rewritten?

**Comment by TheBlueMatt** [comment]
How are you importing these? Are you using the `importmulti` RPC?

**Comment by promag** [comment]
Looks like it can take around >3 hours times 1000 right? Do you know the "birth" timestamp of those keys?

**Comment by pbies** [comment]
I am importing via `importwallet`. Timestamp is not known so whole blockchain must be scanned.

**Comment by pstratem** [comment]
@pbies scanning with the block filter index can be much faster, still working on it though, https://github.com/bitcoin/bitcoin/pull/19116

**Comment by pstratem** [comment]
btw there's 1506642276 transaction outputs, so checking against 150million keys is 225 quadrillion operations, if that ever finishes it's because computers are magic

**Comment by pbies** [comment]
I wonder if making index for keys would improve the scan process. So if the key begins with few characters it would be faster to find it when all the keys beginning with the same characters would be indexed. All keys would be marked in index. It would be long to make index but much faster to find newly added keys.

**Comment by pbies** [comment]
Multithreading also would help. Seems like for 12 thread CPU Bitcoin Core is using maximally 10% of all CPUs.

**Comment by jonasschnelli** [comment]
IMO, the Bitcoin Core wallet is not designed to hold 151M private keys. It does probably work if you have the necessary RAM and disk requirements, but it's certainly not optimised for that case.

> How badly Bitcoin Core is written is unbelivable. There is no other way to scan such an amount of keys, because other apps are for private, limited use and do not offer scanning the blockchain with such a large amount of keys.
> 
> Will this be fixed or even rewritten?

This is up to you. It looks like you have strong interest that large amounts of keys work smoothly. I suggest you either start benchmarking and optimising Core or that you'll find and pay someone that is willing to do that.

**Comment by pbies** [comment]
Surely if someone would have to do that would be payed for that work.

But in case Bitcoin Core is still in development, it would be nice to think earlier about implementing multithreading to make use of multicore CPUs.

Just a little advice now, when it is not too late.

**Comment by pbies** [comment]
Statement of facts is not insulting people. Software should be efficient in all cases and this is one of them.

**Comment by promag** [comment]
Should? That's like saying software should have no bugs, ever.
