### ISSUE TITLE
"Good First Review" label

### ISSUE THREAD

**Issue by fjahr** [bitcoin/bitcoin#19941]
I would like to suggest a small idea that I had, to make it easier for beginner to review their first PRs. Analogous to the "Good first issue" label, I am suggesting a "Good first review" label.

As a general guideline, labeled pull requests should have some (ideally all) of the following characteristics:
- Complexity level low
- A tentative small change (<100 LoC)
- A detailed description of the PR background if needed
- General instructions/hints on how to test/reproduce

Examples of pulls that generally tend to be good first reviews:
- A newly added RPC that can be easily manually tested to verify functionality
- A PR that only adds new functional test coverage since these tend to be self-documenting
- A documentation change that can be verified to be correct with manual testing

Similar to other labels the creator of the pull could ask for the label to be applied or contributors with the power to give labels could apply the proactively.

**Comment by pinheadmz** [comment]
Great idea -- wanna pull some suggestions from the current open PRs as examples?

**Comment by michaelfolkson** [comment]
Concept ACK. Those characteristics are good too.

I would suggest some additions.

- PR opened by a (semi-) experienced reviewer (e.g. @fjahr, @pinheadmz) who can provide guidance on how to review the PR in the initial comment and answer questions. I don't know if a good first issue PR/new contributor's PR is a good candidate for this.
- PRs that people won't mind being noisier in the comments than most.
- PRs that can be left open for a sufficient time to give new reviewers time on them before being merged. Any PRs that are urgent or holding up other PRs being merged are obviously not good candidates for this.

**Comment by jonatack** [comment]
Perhaps:

- "A newly added or updated RPC or CLI option that can be easily tested to verify functionality and help documentation"

- "A PR in which the author provides clear information in the description to reviewers on how to test and review"

**Comment by fjahr** [comment]
> If a template is created, perhaps add links to `CONTRIBUTING.md` and possibly also `doc/developer_notes.md` and `doc/productivity.md`.

TBH, I didn't think of making it a template. We only have one pull template so far and a new one just for this label might be unnecessary. I will propose doc changes if the label gets created.

> I don't know if a good first issue PR/new contributor's PR is a good candidate for this.

Makes sense. My thought was that looking for a well-done description and guidance on how to test in the description would probably mean the pull is from someone with a little more experience. Generally, the label probably shouldn't be applied unless the author agrees or asks for it.

> wanna pull some suggestions from the current open PRs as examples?

I think these might be good candidates:
- #19877
- #19883
- #19253

**Comment by jonatack** [comment]
> TBH, I didn't think of making it a template. We only have one pull template so far and a new one just for this label might be unnecessary. I will propose doc changes if the label gets created.

Agree.

**Comment by michaelfolkson** [comment]
I wouldn't overcomplicate this. It is a very low risk experiment and we don't really know what will work until we try it. I agree that those PRs look like good candidates. Should probably stick to absolute maximum of 3 to begin with.

**Comment by pinheadmz** [comment]
Concept ACK -- are issue/PR labels something triage-level contributors can do? Does anyone on this thread have that permission? (out of curiosity) 

> I think these might be good candidates:
> 
> * #19877
> * #19883
> * #19253

Agree with all three of these - small changes in small number of files. Excellent comments by author, even just visually the diffs are simple and easy to look at. More python than C++ :-) and even in #19883 which is more C++, it's very simple.

**Comment by MarcoFalke** [comment]
I've created the label (used the color from the "Review club" label)

**Comment by fjahr** [comment]
Closed since we have the label now and I will make a brief announcement on IRC
