### ISSUE TITLE
Documentation request - Blockchain Fork

### ISSUE THREAD

**Issue by datalot-369** [bitcoin/bitcoin#19977]
I'm making a long article about the cryptocurrency forking, and currently, I have I problem:

Wherever I read, every time I find undefined assumptions about when exactly a blockchain diverges in two groups.

So, in this call to developers for strongly argumentative answers, I need to know these two basic questions:

1. When exactly occurs a fork in the Bitcoin blockchain?
2. When exactly does NOT occur a fork in the Bitcoin blockchain?

Some information that the answer should have is:

Major articles mention that in the case _"when half of the network says the block is OK and the other half says it is WRONG for a period of time, there could occur a fork"
- What "period of time" is it? Does it exist?
- What is the exact percentage of disparity that can produce a fork?
- Is that specified in the protocol or is something like _"the block verification was sent to all my compatible pairs so a new blockchain was written "_... And the same with the other side?

In a 2013 article from _arsTechnica.com_, [Major glitch in Bitcoin network sparks sell-off; price temporarily falls 23%](https://arstechnica.com/information-technology/2013/03/major-glitch-in-bitcoin-network-sparks-sell-off-price-temporarily-falls-23/), there was an affirmation:

> It's essential for all miners to enforce exactly the same rules about what counts as a valid block. If a client announces a block that half the network accepts and the other half rejects, the result could be a fork in the network. Different nodes could disagree about which transactions have occurred, potentially producing chaos.

At the point where it says _"`a fork in the network`"_, it doesn't appear to be speaking about blockchain (the whole history of transactions), what makes me think: What kind of fork? Is this true? What kind of chaos?  
That's because, until I know, the Bitcoin protocol was designed to disconnect non-compatible nodes.

I think this "time", "disparity" or other things are strongly related to the ~10 min rule and the moment in which the first block during-disparity should be written.  
Please, developers, gift me clarity on this topic to share real information. I will share with you my article when I finished this specific point on it. — I have read around 50 different articles with additional video consumption and there is no way. Just Bitcoins' developers can answer this.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
