### ISSUE TITLE
V.0.18.1. Regtest loses blocks after a crash. 

### ISSUE THREAD

**Issue by educob** [bitcoin/bitcoin#19989]
Hi.

Everything is working ok, bitcoin node records and notifies new txs and new blocks which I record in a database. But when I restart my laptop after a crash, my database has more blocks than the blockchain.This time a couple of extra blocks.
It happens almost everytime my computer crashes. 

What could be causing this? Maybe the latest blocks are not written to disk (kept in cache)?
If this happens with testnet and mainnet is not a problemn for my app cause any missing blocks on the node would be retrived from  the blockchain which is not the case in my solitary regtest. 

Thanks.

**Comment by MarcoFalke** [comment]
How did you observe the difference? Are there debug log lines or similar?

**Comment by educob** [comment]
Hi. When my app starts my app requests, by hash,from the node the last block on my database. If I shutdown my app when it restarts the node rturns the last block on my database. But after a crash the node says it doesn't have that node. I then send a getblockchaininfo to the node and realize that it has less blocks than my database (2 blocks the time I did it but sometimes more blocks).

As my node is regtest, no other node sends the missing block so I am forced to delete the last blocks from my database (which is left in an inconsisten state with invalid transactions).

Thanks.

**Comment by adamjonas** [comment]
Closing given 0.18 has reached EOL and we haven't seen further reports of this.
