### ISSUE TITLE
Bitcoin upgrade to version 0.20.1 remote access RPC error

### ISSUE THREAD

**Issue by chaonan1992** [bitcoin/bitcoin#20010]
Error message ：Failed connect to xxx.xx.xx.xx:8332; No route to host.

Troubleshoot firewall issues

My configuration file content：
#########################
#
server=1
#rpc user
rpcuser=user
#rpc pwd
rpcpassword=userpassword
#
rpcallowip=172.xx.xx.xx
rpcallowip=172.xx.xx.xx
#
#rpcbind=0.0.0.0
#rpc port
rpcport=8332
port=8555
#
txindex=1
########################

How can I solve the above problem？

**Comment by MarcoFalke** [comment]
What are the steps to reproduce?

**Comment by chaonan1992** [comment]
> What are the steps to reproduce?
Mainly use the files in the bin directory of the new version to overwrite the old version files
1.tar -zxvf bitcoin-0.21.1-x86_64-linux-gnu.tar.gz
2.sudo install -m 0755 -o root -g root -t /usr/local/bin /data/bitcoin-0.20.1/bin/*

**Comment by MarcoFalke** [comment]
How did you start the RPC server, how did you call the RPC client?

**Comment by chaonan1992** [comment]
> How did you start the RPC server, how did you call the RPC client?

1.start service: bitcoind -daemon -datadir=/data/bitcoinchaindata/ -conf=/root/.bitcoin/bitcoin.conf 
2.request method: curl command   and  java rpc client

**Comment by chaonan1992** [comment]
I checked the historical version update records, and did not find any special changes related to the bitcoin.conf configuration. The RPC port cannot be accessed. I am very confused.

**Comment by MarcoFalke** [comment]
Which version are you upgrading from?

https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md#configuration-option-changes

**Comment by benslaney** [comment]
I had the same issue on the master branch. Pulling the latest changes (from just the last few days) fixed whatever bug it was that was there
