### ISSUE TITLE
test: Convert amounts in testmempoolaccept test from float to decimal

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20011]
Float should not be used for currency amounts (not even in tests). Thus `float` should be converted to use `decimal`. See also https://github.com/bitcoin/bitcoin/pull/19940#pullrequestreview-491979459

#### Useful skills:

Python 3

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by prayank23** [comment]
This looks easy. Makes sense, decimal should be used for amount in bitcoin core for accuracy. 

Read the things mentioned in [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md)

Want to confirm if this is one of the changes we are trying to make?

 https://github.com/bitcoin/bitcoin/blob/ffaac6e6142a1cf61e8e12d7fc406fcb02300144/test/functional/wallet_send.py#L138


```python
assert_equal(from_balance_before - from_wallet.getbalance(), Decimal amount)
```

**Comment by hasmukhrawal** [comment]
I would like to do this one as this will be my first contribution. I see the status as open but the code already has Decimal implemented. Could you please update on this ?

**Comment by n-moria12** [comment]
import decimal
assert_equal(from_balance_before - from_wallet.getbalance(), decimal.Decimal(amount))

is this correct?

**Comment by MarcoFalke** [comment]
Converting a float to decimal where it is used doesn't help. It needs to be converted where it is defined, so that all calculations are done as decimal

**Comment by n-moria12** [comment]
okay
