### ISSUE TITLE
Not getting any ipv6 connections

### ISSUE THREAD

**Issue by sumBTC** [bitcoin/bitcoin#20021]
I restarted my Bitcoin full node yesterday after a cable repair outside my house. I'm using the latest version of the Bitcoin software (master branch) which has the (new) `-netinfo` rpc option (#19643). 

`bitcoin-cli -netinfo` shows:

```
Bitcoin Core v0.20.99.0-1b313cacc - 70016/Satoshi:0.20.99/

        ipv4    ipv6   onion   total  block-relay
in        61       0      13      74       7
out        5       0       5      10       2
total     66       0      18      84       9
```

Why are there no ipv6 connectoins?

System: Ubuntu 18.04.5 LTS

I'm on an ipv4 internet address myself but as far as I know that shouldn't matter.

`cat /proc/sys/net/ipv6/conf/all/disable_ipv6` gives `0`, so ipv6 is not disabled on my system. 

Turning off `ufw` didn't help.

`debug.log` tells me:

2020-09-25T13:40:53Z Bound to [::]:8333

2020-09-25T13:40:53Z Bound to 0.0.0.0:8333

`bitcoin-cli getnetworkinfo`

```
 "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    }
  ],
```
I tried adding 2 ipv6 outbound peers via rpc but they don't show up.

**Comment by n-thumann** [comment]
What was the command, you´ve added the IPv6 nodes with?

**Comment by sumBTC** [comment]
@n-thumann the command was:

`bitcoin-cli addnode "[2a01:4f8:10b:41::2]:8333" add`

`bitcoin-cli getaddednodeinfo` gives:

```
[
  {
    "addednode": "[2a01:4f8:161:7304::2]:8333",
    "connected": false,
    "addresses": [
    ]
  },
  {
    "addednode": "[2a01:4f8:10b:41::2]:8333",
    "connected": false,
    "addresses": [
    ]
  }
]
```

**Comment by n-thumann** [comment]
Hm, thought this could be related to https://github.com/bitcoin/bitcoin/pull/19643#discussion_r483576375, but doesn´t look like that. `getaddednodeinfo` says that the node isn´t connected at all, so is it even connected properly? Is the node in `getpeerinfo`?

**Comment by sumBTC** [comment]
It's not in `getpeerinfo`. For example;
`bitcoin-cli getpeerinfo | grep 4f8` returns nothing

**Comment by n-thumann** [comment]
Then the node isn´t connected at all and is therefore not shown in `-netinfo` or `getpeerinfo`.
Try having a look into `debug.log` if the connection is refused or something, or try Wireshark 😊

**Comment by sumBTC** [comment]
In `debug.log` I see:

`2020-09-26T06:59:08Z connect() to [2a01:4f8:161:7304::2]:8333 failed: Network is unreachable (101)`

**Comment by n-thumann** [comment]
Looks like your system has no idea how to route to this network. Do you have proper v6 connectivity? What do `traceroute 2a01:4f8:161:7304::2` or `ip -6 route` show?

**Comment by sumBTC** [comment]
`ip -6 route` give:
```
fe80::/64 dev eth0 proto kernel metric 100 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
```

**Comment by sumBTC** [comment]
`traceroute to 2a01:4f8:161:7304::2 (2a01:4f8:161:7304::2), 30 hops max, 80 byte packets
connect: Network is unreachable`

**Comment by n-thumann** [comment]
Yeah, you only have Link-Local IPv6 connectivity (so only within your local network), but not "the internet".
If your ISP actually provides you with v6 connectivity, you can add a default route manually. If not, there´s no way for you to reach this server via IPv6.

**Comment by sumBTC** [comment]
Ah, thanks a lot for all your help. For now, I'll close this issue. Nevertheless, it shows how useful the -netinfo rpc call is :-)
