### ISSUE TITLE
[Idea] Multiple ports for faster overall performance?

### ISSUE THREAD

**Issue by BenAlthauser** [bitcoin/bitcoin#20020]
I'm coming at this from the angle of overall throughput of the network. So it looks like the Bitcoin daemon listens on 8333 and 18333 for connections.

What if, Bitcoin used... say 50 ports, or maybe even just 20 on both sides.  I think you'd be able to receive multiple at the same time given they were operating in an asynchronous manner. I'm not sure of the overall code structure, but wouldn't it allow for more throughput overall if both sides were communicating and routing based on open sockets? 

I don't know the deep technicalities of ports and throughput and I know it's not your job to teach me, but I am curious if there's any possible gain here.

**Comment by sipa** [comment]
No, this won't have any effect. Multiple sockets on the same port or on different ports have the exact same performance.

Furthermore, in normal cases performance is not bottlenecked by network code or infrastructure, but by processing the incoming data.

**Comment by BenAlthauser** [comment]
Thanks for the reply sipa, 
So if you had 20 ports opened and were able to process 20 at once on different threads this wouldn't have an overall benefit?

**Comment by sipa** [comment]
If that was easy to do, we could also just split the 20 sockets into different threads just as easily.

This isn't done for a variety of reasons, but being the same port is not one of them.

**Comment by BenAlthauser** [comment]
Thanks for the explanation. Now that I think about it it'd be essentially the same as running 20 clients if they are threads.  Ah well, gonna keep bumbling ideas around.
