### ISSUE TITLE
Followup from #19969

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#20032]
In #19969 @kallewoof [mentioned](https://github.com/bitcoin/bitcoin/pull/19969#pullrequestreview-497181048):

> I find it weird that even though I used "1 sat/b" it complains about failing to do fee estimation. It shouldn't need fee estimation at all. Anyway, that's outside the scope of this nit-fix PR.

**Comment by kallewoof** [comment]
Thanks for creating an issue. I believe this problem does not only relate to the `send` RPC, but to all of them, including `sendtoaddress`, `sendmany`.

**Comment by MarcoFalke** [comment]
It is probably best to fix this as part of #19543

**Comment by jonatack** [comment]
@kallewoof any particular steps to reproduce? I've been using the explicit feerate frequently (not yet with the new `send` rpc though) and have not seen anything out of the ordinary.

**Comment by kallewoof** [comment]
Actually, I was wrong. It only applies to `send`:

```
$ ./bitcoind -regtest -daemon
Bitcoin Core starting
$ ./bitcoin-cli -regtest getnewaddress
bcrt1qkfveed8g8vnktsc3490aarzh302l2qc2ymhlge
$ ./bitcoin-cli -regtest sendtoaddress bcrt1qkfveed8g8vnktsc3490aarzh302l2qc2ymhlge 1 '' '' false true 1 sat/b
a93d1ccee5bdca288908a97f5a6801d91cc8a174a5ed3ad10c8cf22e84e9f6e8
$ ./bitcoin-cli -regtest send '[{"bcrt1qkfveed8g8vnktsc3490aarzh302l2qc2ymhlge":1}]' 1 sat/b
error code: -4
error message:
Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -fallbackfee.
```

**Comment by jonatack** [comment]
Thanks @kallewoof

**Comment by MarcoFalke** [comment]
Is this still an issue?
