### ISSUE TITLE
rpcauth command line arg does not work when there is no config file

### ISSUE THREAD

**Issue by bijeebuss** [bitcoin/bitcoin#20057]
**Expected behavior**

specifying the command line arg `-rpcauth={user}:{salt}${hash}` from the output of `rpcauth.py` should allow you to authenticate with the user and password even when there is not a config file

**Actual behavior**

rpc command returns `error: Authorization failed: Incorrect rpcuser or rpcpassword`

**To reproduce**

run bitcoind version 0.20.1 with the command line arg `-rpcauth={user}:{salt}${hash}` from the output of `rpcauth.py` without creating a bitcoin.conf file. Then try to connect to the rpc with the username and password. 

**System information**

bitcoind version 0.20.1 for linux downloaded from the website
OS: ubuntu

**Comment by bijeebuss** [comment]
if you then add a config file with `rpcauth={user}:{salt}${hash}` it works

**Comment by adaminsky** [comment]
The comment here https://github.com/bitcoin/bitcoin/issues/12209#issuecomment-358344493 about the dollar sign being consumed by the shell was the problem for me. To fix this, I just added a '\\' before the dollar sign in the rpcauth argument to bitcoind. I think this should ideally create a warning message if the rpcauth argument is not properly formatted.

**Comment by bijeebuss** [comment]
That would most likely explain it, thanks.
