### ISSUE TITLE
log always says Using default signet network

### ISSUE THREAD

**Issue by jsarenik** [bitcoin/bitcoin#20053]
When starting `bitcoind` it always says `Using default signet network`

```
$ timeout 1 bitcoind 2>&1 | grep -i signet
2020-10-01T13:20:59Z Using default signet network
2020-10-01T13:20:59Z Signet derived magic (message start): 0a03cf40
Terminated
```

No matter if started on mainnet, regtest, testnet.

**Expected behavior**

The non-signet `bitcoind` should not report about Signet in the log. It is confusing.

**Actual behavior**

It prints a message about Signet and should not.

**To reproduce**

```
$ bitcoind --version | head -1
Bitcoin Core version v0.20.99.0-40aab35e9
$ timeout 1 bitcoind 2>&1 | grep -i signet
2020-10-01T13:23:58Z Using default signet network
2020-10-01T13:23:58Z Signet derived magic (message start): 0a03cf40
Terminated
```

**System information**

Ubuntu 20.04 LTS x86_64

**Comment by jonatack** [comment]
Thanks for the report @jsarenik! This was fixed in #20048 today on latest master.

**Comment by jonatack** [comment]
Can you pull the latest master branch and report here if you still see the issue, or close it?

**Comment by jsarenik** [comment]
Sure, @jonatack

**Comment by jsarenik** [comment]
Fixed. Thank you!

```
$ bitcoind --version | head -1
Bitcoin Core version v0.20.99.0-9fc2f011b
$ timeout 1 bitcoind | grep -i signet
Terminated
```
