### ISSUE TITLE
wallet method is disabled because no wallet is loaded

### ISSUE THREAD

**Issue by jsarenik** [bitcoin/bitcoin#20051]
When I run a fresh regtest with an empty datadir and try to `getnewaddress`, `bitcoin-cli` fails with

```
error code: -32601
error message:
Method not found (wallet method is disabled because no wallet is loaded)
```

This happens with version 40aab35e9828427a800916ac15e3381332f4d0a6 (current `master`) of `bitcoind`.

**Expected behavior**

On bitcoin `0.20.1` it does not happen:

```
$ rm -rf ~/.bitcoin/regtest
$ bitcoind --version | head -1
Bitcoin Core version v0.20.1
$ bitcoind -regtest -daemon=1
Bitcoin Core starting
$ bitcoin-cli getnewaddress
bcrt1...
$ bitcoin-cli stop
Bitcoin Core stopping
```

**Actual behavior**

```
$ rm -rf ~/.bitcoin/regtest
$ bitcoind --version | head -1
Bitcoin Core version v0.20.99.0-40aab35e9
$ bitcoind -regtest -daemon=1
Bitcoin Core starting
$ bitcoin-cli getnewaddress
error code: -32601
error message:
Method not found (wallet method is disabled because no wallet is loaded)
$ bitcoin-cli stop
Bitcoin Core stopping
```

**To reproduce**

100%

**System information**

the `master` version is self-compiled, v0.20.1 is from bitcoincore.org Linux x86_64

Ubuntu 20.04 LTS

```
$ uname -mr
5.4.0-48-generic x86_64
```

**Comment by promag** [comment]
See #15454.

**Comment by gwillen** [comment]
I think the error messages for this need to be fixed, or there is going to be a huge flood of people with this same issue once #15454 makes it into a release. (Is there already a separate issue or proposal for that?)

**Comment by gwillen** [comment]
There was some discussion of this on IRC, and thus was born #20101 .
