### ISSUE TITLE
doc: manpages include version number are outdated in master branch

### ISSUE THREAD

**Issue by decryp2kanon** [bitcoin/bitcoin#20062]
https://github.com/bitcoin/bitcoin/blob/60ec57b3d73e5cef71ebf3c4cdf54a4474bf492b/doc/man/bitcoin-cli.1#L2

https://github.com/bitcoin/bitcoin/blob/60ec57b3d73e5cef71ebf3c4cdf54a4474bf492b/doc/man/bitcoin-qt.1#L2

https://github.com/bitcoin/bitcoin/blob/60ec57b3d73e5cef71ebf3c4cdf54a4474bf492b/doc/man/bitcoin-tx.1#L2

https://github.com/bitcoin/bitcoin/blob/60ec57b3d73e5cef71ebf3c4cdf54a4474bf492b/doc/man/bitcoin-wallet.1#L2

https://github.com/bitcoin/bitcoin/blob/60ec57b3d73e5cef71ebf3c4cdf54a4474bf492b/doc/man/bitcoind.1#L2

need to up to date?

but tagged version 0.20.1 looks fine.
https://github.com/bitcoin/bitcoin/blob/7ff64311bee570874c4f0dfa18f518552188df08/doc/man/bitcoind.1#L2

**Comment by MarcoFalke** [comment]
I think we can re-generate them once before branch-off in a couple of weeks, but generally, they will always be outdated by a bit, because master is the development branch and they are primarily generated for release branches.

**Comment by laanwj** [comment]
It's not generally necessary to open issues about this. When to do man page updates is specified in the release process.

**Comment by decryp2kanon** [comment]
> so we don't end up updating the manual pages there.

i understood. so we do not need to update this. closing issue.

**Comment by decryp2kanon** [comment]
re-open: however some users (build from source) can be little confused when they see the manpages.

**Comment by laanwj** [comment]
Another option would be to remove the pre-generated manpages from the master branchcompletely, forcing people to generate themselves if they want manpages.

**Comment by decryp2kanon** [comment]
> Another option would be to remove the pre-generated manpages from the master branch completely, forcing people to generate themselves if they want manpages.

ACK
