### ISSUE TITLE
BitcoinCore Fatal Internal Error when syncing

### ISSUE THREAD

**Issue by lo90oooo** [bitcoin/bitcoin#20063]
Hey guys!
So I just downloaded Bitcoin Core on my MacBook Air today and it was syncing. It synced up to 6% and now says: "Error: A fatal internal error occurred, see debug.log for details"

I don't know anything about coding so if some one can guide me through the process step by step it would be great.

Also I already transferred money into the wallet while it was syncing but now i cannot recover it and it never was even fully synced! Can someone please help me?

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

Please be aware that the debug log might contain personally identifying information.
