### ISSUE TITLE
CI: Appveyor builds failing

### ISSUE THREAD

**Issue by sipsorcery** [bitcoin/bitcoin#20066]
Appveyor builds started failing about 20 hours ago for no reason I can discern.

I cannot replicate the failures on my Windows 10 machine. I am able to install the vcpkg dependencies from scratch and successfully build Bitcoin Core using the `msvc` build config.

I am attempting to replicate the issue in the appveyor job on my Bitcoin Core fork but as yet have not been able to narrow it down.

If anyone reads this with admin privileges for appveyor could you use the **RE-BUILD COMMIT** option on the [last successful](https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/35532413) appveyor job. If that job now also fails it would point to something changing in the appveyor environment.

**Comment by MarcoFalke** [comment]
Done https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/35547909

**Comment by decryp2kanon** [comment]
oh i am late
https://github.com/bitcoin/bitcoin/issues/20068

**Comment by decryp2kanon** [comment]
i assume downloading issue.

```bash
         -- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
```

**Comment by sipsorcery** [comment]
The previously successful job [failed on the rebuild](https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/35547909) with the same error so as intimated above does seem to be a external issue.

I haven't seen the msys2 download error anywhere in my failure logs. I'm now trying with a completely fresh checkout of vcpkg.

The `repo.msys2.org` host does seem to be down so if one of the vcpkg dependencies requires it that would explain the failures. Actually just found this [link](https://gitter.im/msys2/msys2?at=5f772485aa7388396e8d84e4) on a vcpkg issue. Looks like the `msys2` guys are trying to get the host back up.

**Comment by sipsorcery** [comment]
This [vcpkg issue](https://github.com/microsoft/vcpkg/issues/13852) is exactly what we're experiencing. Once `repo.msys2.org` comes back up should be fixed.

**Comment by laanwj** [comment]
I hope it comes back up soon then.

Aside, it's to me somewhat curious that a "true MSVC" build depends on the msys repository. This used to be a mingw thing right?

**Comment by decryp2kanon** [comment]
> depends on the msys repository. This used to be a mingw thing right?

https://github.com/microsoft/vcpkg/blob/802c9c6aec1f6189e99b1fc8217977bc2995156a/scripts/cmake/vcpkg_find_acquire_program.cmake#L439

**Comment by sipsorcery** [comment]
Going off the Gitter chat seems like the repo2.msys2.org server might not be coming back until Monday at the earliest.

If it is desired to get he appveyor job working in a hurry then @decryp2kanon's suggestion of adjusting the `vcpkg` config to use a different mirror should work.  My feeling is that it's less back and forth to keep waiting, given each tweak to the appveyor job tweak requires a commit to `master`. 

> Aside, it's to me somewhat curious that a "true MSVC" build depends on the msys repository. This used to be a mingw thing right?

The Bitcoin Core build is done as a "pure" msvc toolchain build.

The dependencies, on the other hand, are built whichever way the `vcpkg` port specifies. Typically that's with `cmake` and `msvc` but it can also use different toolchains with emulation environments such as `msys2`.

**Comment by hebasto** [comment]
https://www.msys2.org/:
> The primary download server is currently (since Oct 2nd) down. We are working on bringing it back up. Pacman has preconfigured mirrors so package installations should work, albeit with timeouts. The setup package can be downloaded from SourceForge or GitHub.

**Comment by hebasto** [comment]
The problem seems recurring: https://stackoverflow.com/questions/60562004/cant-reach-repo-msys2-org

**Comment by MarcoFalke** [comment]
Isn't it possible to specify two mirrors and pick the one that works?

**Comment by decryp2kanon** [comment]
> Isn't it possible to specify two mirrors and pick the one that works?

I guess we can't in a simple way. Because the download URL is hard-coded in the repo microsoft/vcpkg

**Comment by sipa** [comment]
Unless this is expected to be fixed soon, should we consider removing the AppVeyor CI?

**Comment by sipa** [comment]
I've disabled the AppVeyor webhook. Please let me know when things are fixed, or we should try again.

**Comment by decryp2kanon** [comment]
@sipsorcery issue closed? appveyor fixed?

**Comment by sipa** [comment]
I assume he closed it because it's no longer an observable issue.

As the AppVeyor disabling is supposed to be temporary, maybe it's better to keep this open until it can be re-enbled?
