### ISSUE TITLE
bitcoin-cli needlessly creates empty ~/.bitcoin/wallets directory

### ISSUE THREAD

**Issue by Kixunil** [bitcoin/bitcoin#20070]
When `bitcoin-cli` is run, **it, not bitcoind** creates an empty `~/.bitcoin/wallets` direcctory with `~` bring home of currently running user. This is weird and leads to user confusion because it happens even in cases when `bitcoin-cli` connects to a `bitcoind` running under a different user or probably on other machine.

**Expected behavior**

`bitcoin-cli` never modifies filesystem, especially not things that the daemon should take care of.

**Actual behavior**

`bitcoin-cli creates empty directory`

**To reproduce**

0. make sure `~/.bitcoin` does **not** exist under user A
1. install `bitcoind` and run it under a user B
2. run `bitcoin-cli getblockchaininfo` under user A
3. `ls ~/.bitcoin` under user A

For quick setup, you can try to use [my project](https://deb.ln-ask.me) in a Debian VM or using provided Docker file. Just `apt install bitcoin-regtest bitcoin-cli`, it's already pre-configured to run under a different user, so then just running `sudo bitcoin-cli getblockchaininfo && sudo ls /root/.bitcoin` should reproduce the issue.

**System information**

0.20 official release downloaded from `https://bitcoin.org/bin/bitcoin-core-...`, verified GPG signature from Wladimir.

OS: Linux Debian Buster
CPU: Intel x86_64
Disk: NVMe SSD
FS: ext4

I don't think configuration is relevant since `bitcoin-cli` is **not** informed where to find it (via parameters or otherwise) and thus it can **not** access it. I also added `-rpcport` and `-rpccookiefile` parameters explicitly but I don't think it's relevant.

Loosely related to #16220, but not a duplicate.

**Comment by n-thumann** [comment]
Was able to reproduce and track it down to https://github.com/bitcoin/bitcoin/pull/11466, especially https://github.com/bitcoin/bitcoin/pull/11466/files#r150251905 (currently in `master` in https://github.com/bitcoin/bitcoin/blob/master/src/util/system.cpp#L722) :v:

**Comment by Kixunil** [comment]
Good find. My understanding is that the function is shared between daemon and client, that's why it happens. Not surprised, if the function is called `GetDatadir` but it doesn't just get the datadir, but also creates it. :)

**Comment by MarcoFalke** [comment]
>  I also added -rpcport and -rpccookiefile parameters explicitly but I don't think it's relevant.

As a temporary workaround, you can skip passing them and instead pass in the datadir to bitcoin-cli. It will then read those values from the conf file (or cookie file), but also skip creating the wallet dir (because it already exists).

**Comment by Kixunil** [comment]
Good idea. I can't skip them because of other reasons but adding `-datadir=/tmp/` disables creating the directory.
