### ISSUE TITLE
test: Convert non-wallet tests to use our python MiniWallet

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20078]
It is possible to compile Bitcoin Core without the wallet. Though, many tests require the Bitcoin Core wallet to create and sign transactions. Ideally, every non-wallet test (for example consensus tests) are run even with the Bitcoin Core wallet disabled. This ensures that users running without the wallet can test their Bitcoin Core with the functional test suite.

Thus, tests that use the Bitcoin Core wallet should be rewritten to use the python MiniWallet.

This is an open-ended issue. You can find candidate tests via `git grep 'self.skip_if_no_wallet()'`. Exclude the tests that start with `wallet_`, as those are tests that are meant to test the Bitcoin Core wallet.

Refer to #19922 and #19800 as examples on how to approach this issue.

Edit: See also https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1106586728

#### Useful skills:

* Familiarity with the RPC interface
* Familiarity with our functional test suite
* Good python3 skills

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by dboures** [comment]
Hey, I can give this issue a shot.

**Comment by MarcoFalke** [comment]
Sure. No need to ask on this one, as it is open ended. There should be enough tests for everyone to convert

**Comment by dboures** [comment]
Got it, following the example of #19922 it seems to me we should only convert one test per PR, so that the PRs are still manageable?

**Comment by stackman27** [comment]
hi there, does this issue still require work to be done on it?

**Comment by michaelfolkson** [comment]
@stackman27: As far as I can tell there are around 50 tests from `git grep 'self.skip_if_no_wallet()'` not including tests starting with `wallet_` (From Marco's [initial description](https://github.com/bitcoin/bitcoin/issues/20078#issue-714328682))

If you look at the above notifications it appears 4 test updates have been merged and 1 test update is open. So there are lots to tests to work on.

**Comment by stackman27** [comment]
How would I go about creating and sending tx using `miniwallet`  when the utxo generated doesnot have a key `value` in the output? Should I just manually append it or is there anything I'm missing? I found this issue while working on `mempool_limit.py` while creating utxo using `create_confirmed_utxos`

**Comment by michaelfolkson** [comment]
@stackman27: The [Miniwallet](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/wallet.py#L28) class defines `self._address` which is a `ADDRESS_BCRT1_P2WSH_OP_TRUE` from [address.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/address.py#L20). This OP_TRUE address can be spent with a witness stack of just OP_TRUE so it doesn't need any keys.

In [mempool_limit.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/mempool_limit.py) that should be fine for `create_confirmed_utxos`. I'm trying to work out if that is a challenge with `create_lots_of_big_transactions` later... I don't think it is if I understand what is going on with `splicing in "txouts" to each raw transaction`

**Comment by stackman27** [comment]
> @stackman27: The [Miniwallet](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/wallet.py#L28) class defines `self._address` which is a `ADDRESS_BCRT1_P2WSH_OP_TRUE` from [address.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/test_framework/address.py#L20). This OP_TRUE address can be spent with a witness stack of just OP_TRUE so it doesn't need any keys.
> 
> In [mempool_limit.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/mempool_limit.py) that should be fine for `create_confirmed_utxos`. I'm trying to work out if that is a challenge with `create_lots_of_big_transactions` later... I don't think it is if I understand what is going on with `splicing in "txouts" to each raw transaction`
> 
> For more info on OP_TRUE addresses (P2SH rather than P2WSH but may be useful): https://bitcoin.stackexchange.com/questions/72773/how-to-create-a-p2sh-transaction-with-a-scriptsig-of-op-true

@michaelfolkson  Thank you very much for the response however, i'm still a bit confused as to how `create_confirmed_utxos` can be used in the `send_self_transfer`. Currently, the utxo from `create_confirmed_utxo` looks something this; 
![oneutxo](https://user-images.githubusercontent.com/26356227/103419860-a6ea4980-4b49-11eb-859d-ef70bd29a5c9.PNG).   I have set up my transaction call as `txs = miniwallet.send_self_transfer(fee_rate = relayfee, from_node = node, utxo_to_spend = us0)`, where `us0` is the transaction from the image. 

The issue i face is that the key `value` within the dictionary array is not present, so i try to rewrite the key `amount` to `us0["value"] = us0.pop("amount")`. And i'm assuming the `value` and `amount` corresponds to the same thing.  Am i on the right track here because i'm approaching based on assumption and if its true, shouldn't it be referenced somewhere in `class MiniWallet` ? I really appreciate the help

**Comment by michaelfolkson** [comment]
Did you answer your question @stackman27? I think you deleted your latest post asking about `value` in wallet.py versus `amount` in mempool_limit.py. I think you can use `value` for `amount` unless I'm missing something.

**Comment by stackman27** [comment]
> Did you answer your question @stackman27? I think you deleted your latest post asking about `value` in wallet.py versus `amount` in mempool_limit.py. I think you can use `value` for `amount` unless I'm missing something.

I think so. I just generated utxos using `miniwallet.generate` rather than `create_confirmed_utxos`

**Comment by stackman27** [comment]
@michaelfolkson i'm sorry to bug you so much. But how would i setup `create_lots_of_big_transactions` without modifying the `send_self_transfer`? Here's what my setup looks like (https://ibb.co/WcMrBqB) but it's not returning the correct `mempoolminfee`. Any hints?

**Comment by practicalswift** [comment]
Concept ACK

**Comment by DariusParvin** [comment]
I'll have a go at `mempool_reorg.py`! Just putting it out there as it'll be my first commit so I'm not sure how long it'll take.

**Comment by stackman27** [comment]
Hi everyone, I'm working on `mempool_accept` but am having issue making transaction with 2 inputs ([codelink](https://github.com/bitcoin/bitcoin/blob/d0852f39a7a3bfbb36437ef20bf94c263cad632a/test/functional/mempool_accept.py#L168). Should i make two individual transactions or modify `send_self_transfer` to accept input `vin` lists? or is there a better way to do this? Thank you

**Comment by stackman27** [comment]
@MarcoFalke  is there a way to get information about a tx in `miniwallet` I tried doing `node.gettransaction(txid)` but got `Invalid or non-wallet transaction id (-5)` error?

**Comment by MarcoFalke** [comment]
miniwallet returns the transaction details when you create a transaction. If you need mempool info about the tx, you can use a mempool rpc. Note that the miniwallet itself doesn't track the mempool/chain as of now.

**Comment by stackman27** [comment]
hi @MarcoFalke, I was refactoring `mempool_accept` and felt the need to just sign an existing tx also in some parts of the code I only had to create a raw tx. So, I was wondering if it'd be good idea to break down `send_self_transfer` into `create, sign & spend` rather than just having to pass boolean `send_tx` or `create_tx` into the functional parameter? 

Also, how about the idea of accepting multiple inputs to spend like what's being done [here](https://github.com/bitcoin/bitcoin/blob/b401b093556f53023d1615f7cff3eb84807c6e8b/test/functional/mempool_accept.py#L167), I believe currently we can only spend one input utxo, but I think allowing multiple inputs to spend will prevent repetitions

**Comment by MarcoFalke** [comment]
Splitting creation and signing doesn't make too much sense, I think, because signing is just pushing OP_TRUE, which would complicate the interface to having to do manually or in a second step. Splitting up send_tx could make sense if it makes the interface clearer.

**Comment by MarcoFalke** [comment]
There a quite a few miniwallet prs open, and review is a bit more important than writing new code. So if everyone who contributed code could help with review of the other open prs, that'd be great. https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+miniwallet

**Comment by michaelfolkson** [comment]
> As far as I can tell there are around 40 tests from git grep 'self.skip_if_no_wallet()' excluding tests starting with wallet_ (From Marco's initial description)

Haven't looked through to see which of the tests still to be updated to use MiniWallet would benefit from having access to P2PK outputs but https://github.com/bitcoin/bitcoin/pull/21945 is introducing them.

**Comment by pg156** [comment]
I am working on `mempool_updatefromblock.py` and will open a PR once ready. It is a modified version of the closed PR #21999.

**Comment by hamzzy** [comment]
I'm working on rpc_signrawtransaction.py and will open a PR once ready.

**Comment by ayush933** [comment]
I'm working on `rpc_createmultisig.py`. Not sure how long it will take since it will be my first commit.

**Comment by danielabrozzoni** [comment]
I'm working on `rpc_rawtransaction.py`, I'll open a PR once it's ready :)

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/pull/21144 might be up for grabs

**Comment by MarcoFalke** [comment]
Also, a reminder to help with review of the currently open miniwallet pulls: https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+is%3Aopen+miniwallet+label%3ATests

**Comment by michaelfolkson** [comment]
Something also to consider for future Miniwallet PRs (as discussed in #24635) is if your test is run twice in the test runner ensure that it is only run once (could be done in same PR) once the dependence on the Core wallet is removed. I'll try to monitor these and do this if people forget.

**Comment by brunoerg** [comment]
We could have a list similar to #24783 to track the work. It would be easier to know what have been done and what is missing.

**Comment by shommel** [comment]
First timer here: Seems `tool_signet_miner.py` is up for grabs. Planning on picking it up.

Also would be happy to put together the list @brunoerg mentioned in the coming days 👍

**Comment by Eunoia1729** [comment]
Picking `feature_bip68_sequence.py`.

**Comment by shommel** [comment]
@MarcoFalke Apologies for ping. As per the comment above, here's a quick list of past, present, and future MiniWallet tests. Hope it helps!

List of remaining/non-converted functional tests:
[] `test/functional/example_test.py`
[] `test/functional/feature_backwards_compatibility.py`
[] `test/functional/feature_dbcrash.py`
[] `test/functional/feature_nulldummy.py`
[] `test/functional/feature_segwit.py`
[] `test/functional/feature_taproot.py`
[] `test/functional/mempool_packages.py`
[] `test/functional/mining_prioritisetransaction.py`
[] `test/functional/rpc_fundrawtransaction.py`
[] `test/functional/rpc_psbt.py`
[] `test/functional/rpc_rawtransaction.py`
[] `test/functional/rpc_signrawtransaction.py`
[] `test/functional/tool_wallet.py` 

List of started/finished tests:
[] `test/functional/tool_signet_signer.py` (in progress/shown interest [here](https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1105708448))
[] `test/functional/feature_bip68_sequence.py` (in progress/shown interest [here](https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1105967432))
[] `test/functional/mempool_updatefromblock.py` (in progress #24183)
[] `test/functional/mining_prioritisetransaction.py` (in progress #24839)
[x] `test/functional/p2p_leak_tx.py` (added in #20126)
[x] `test/functional/mining_getblocktemplate_longpoll.py` (added in #20159)
[x] `test/functional/mempool_expiry.py` (added in #20276)
[x] `test/functional/mempool_spend_coinbase.py` (added in #20385)
[x] `test/functional/mempool_compatibility.py` (added in #20688)
[x] `test/functional/mempool_resurrect.py` (added in #20692)
[x] `test/functional/mempool_reorg.py` (added in #21178)
[x] `test/functional/p2p_blocksonly.py` (added in #21867)
[x] `test/functional/feature_csv_activation.py` (added in #21900)
[x] `test/functional/mempool_limit.py` (added in #22543)
[x] `test/functional/rpc_signmessage.py` (added in #22641)
[x] `test/functional/p2p_filter.py` (added in #23079)
[x] `test/functional/rpc_generateblock.py` (added in #23558)
[x] `test/functional/rpc_scantxoutset.py` (added in #23866)
[x] `test/functional/p2p_compactblocks.py` (added in #23873)
[x] `test/functional/mining_basic.py` (added in #23978)
[x] `test/functional/mempool_accept.py` (added in #24035)
[x] `test/functional/interface_rest.py` (added in #24223)
[x] `test/functional/feature_maxuploadtarget.py` (added in #24533)
[x] `test/functional/mempool_package_onemore.py` (added in #24637)
[x] `test/functional/mempool_unbroadcast.py` (added in #24749)
[x] `test/functional/feature_fee_estimation.py` (added in #24817)
[x] `test/functional/p2p_segwit.py` (added in #24896)

**Comment by danielabrozzoni** [comment]
I would remove `example_test.py` from the list, I don't think it should really be "fixed", it's only showing how to skip a test if the module is missing :) 

Also, I'm still working on `raw_transaction.py` (see https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1073102719), I'm almost there :)

**Comment by shommel** [comment]
>I would remove example_test.py from the list, I don't think it should really be "fixed", it's only showing how to skip a test if the module is missing :)

Fixed @danielabrozzoni. Thanks for the context!

> Also, I'm still working on raw_transaction.py (see https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1073102719), I'm almost there :)

Added to the list, sorry, must've missed it. Thanks for pointing it out 👍

**Comment by michaelfolkson** [comment]
Thanks @shommel for the list! Didn't realize how much progress had been made, not many left now.

I was planning to play around with Taproot in Python at some point so I'll take feature_taproot.py (somewhat surprised it is still there). If someone wants to take it off me feel free though.

**Comment by kouloumos** [comment]
From the description of the issue

> This is an open-ended issue. You can find candidate tests via git grep 'self.skip_if_no_wallet()'

I understand why those tests are the obvious candidates for MiniWallet usage, but are those the only tests that could benefit from MiniWallet usage? 

During the process of converting tests to use the MiniWallet, a number of practical methods have been created thus enabling more readable tests by using the MiniWallet class. I am trying to understand if the usage of the MiniWallet to simplify tests that can already run with the Bitcoin Core wallet disabled (e.g. https://github.com/bitcoin/bitcoin/pull/25379) is something that could be considered beneficial.

**Comment by pablomartin4btc** [comment]
Considering segwit has been implemented long time ago... Is it worth it to convert `test/functional/feature_segwit.py` into MiniWallet?

**Comment by MarcoFalke** [comment]
Yes, anything without `[x]` in https://github.com/bitcoin/bitcoin/issues/20078#issuecomment-1106586728 is up for grabs

**Comment by MarcoFalke** [comment]
rpc_psbt looks like a wallet test, so maybe it can be renamed to `wallet_psbt.py`

**Comment by miles170** [comment]
Picking `test/functional/feature_segwit.py`.

**Comment by MarcoFalke** [comment]
Nice. Pull requests welcome, however I am going to close this issue for now. The remaining tests can not be trivially converted without also extending MiniWallet (I think), so it might be better to open specific threads/issues for each test.
