### ISSUE TITLE
signrawtransactionwithkey has misleading help text

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#20085]
"The third optional argument (may be null) is an array of previous transaction outputs that
this transaction depends on but may not yet be in the block chain."

This RPC call has no concept of blockchains. Does this third argument have to be mandatory? What should the help text say?

**Comment by instagibbs** [comment]
This could be a "good first issue"

**Comment by hebasto** [comment]
How this differs from #20084 ?

**Comment by instagibbs** [comment]
Oh I got a 404 and reapplied.... I'll close
