### ISSUE TITLE
Cirrus CI - unknown spurious failure

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#20093]
https://cirrus-ci.com/task/4642327564124160

I can't tell what happened, but re-running the job worked, so this seems like a spurious failure.  Opening this issue in case others see the same.

**Comment by MarcoFalke** [comment]
Not sure what is going on here. I assume it is a fault on the ci provider's side. I can try switching the virtualization to another one to see if it helps. If not, we might have to run the ci on our own hardware.
