### ISSUE TITLE
Followup with potential downstream breakage after #19339

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#20099]
> [Might be worth opening an issue on the topic because apparently the codes
aren't enough for downstream users. Recent breaks include LND, probably
more.](https://github.com/bitcoin/bitcoin/pull/19339#issuecomment-704894759)

**Comment by adamjonas** [comment]
@glozow @instagibbs was this addressed in https://github.com/bitcoin/bitcoin/pull/20109?

**Comment by instagibbs** [comment]
LGTM
