### ISSUE TITLE
[RFC] qt: Minimum required Qt5

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#20104]
As branching `0.21.0` off is [approaching](https://github.com/bitcoin/bitcoin/issues/18947) it seems a good time to discuss a possible bumping of the minimum required Qt5 version.

The current minimum required Qt is 5.5.1. Set in #15393. Recent discussion in #13478.

Distro support:
- stretch -- [5.7.1](https://packages.debian.org/stretch/libqt5core5a)
- buster -- [5.11.3](https://packages.debian.org/buster/libqt5core5a)
- bionic -- [5.9.5](https://packages.ubuntu.com/bionic/libqt5core5a)
- focal -- [5.12.8](https://packages.ubuntu.com/focal/libqt5core5a)
- centos 7 -- [5.9.7](http://mirror.centos.org/centos/7/os/x86_64/Packages/qt5-qtbase-5.9.7-2.el7.x86_64.rpm)
- centos 8 -- [5.12.5](http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/qt5-qtbase-5.12.5-4.el8.x86_64.rpm)

Bumping to 5.9 (LTS) is possible, but it won't be of much benefit to us. Also, its support [ended](https://www.qt.io/blog/2017/06/07/renewed-qt-support-services) on 2020-05-31.

5.10 could bring much more benefits to us, e.g.:
- functor-parameter overload of [`QMetaObject::invokeMethod`](https://doc.qt.io/qt-5/qmetaobject.html#invokeMethod-4)
- fixed https://bugreports.qt.io/browse/QTBUG-10907

**Comment by jarolrod** [comment]
I'm for bumping the minimum required Qt Version seeing as the last bump was over 2 years ago. Furthermore, Qt 5.5.1 is ANCIENT.

**Comment by MarcoFalke** [comment]
Bumping to 5.9 should be completely uncontroversial, now that all systems that ship a C++17 compiler also ship with qt5.9+
