### ISSUE TITLE
BITCOIN_SUBDIR_TO_INCLUDE no longer works

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#20118]
I haven't been able to figure out why yet, but it seems gcc/clang/g++/clang++ `-E` no longer does the same thing as `cpp`

**Comment by luke-jr** [comment]
0.20 seems unaffected, so something else is apparently going on.

**Comment by luke-jr** [comment]
Investigating further, it looks like 0.20 is indeed also broken, and only Knots 0.20 is fine... and it's because I already fixed this years ago in #5872 which nobody cared to review. Sigh.

(Apparently `g++ -E` only works with filename inputs, whereas `cpp` accepts stdin, but `BITCOIN_SUBDIR_TO_INCLUDE` uses a `conftest.cpp` file, so that turned out to be a non-issue)

**Comment by hebasto** [comment]
Maybe consider https://github.com/theuni/bitcoin/commit/2ef8a6fc3b1de989702adb04ebb066bd101350f0 ?

**Comment by fanquake** [comment]
I'm going to close this as wont-fix. 

`BITCOIN_SUBDIR_TO_INCLUDE` is only used for BDB detection, and only in certain cases. Given that using BDB is (being) deprecated, there is somewhat less reason to fix this. This is compunded by the fact that if this has indeed been broken for 2 years, and not a single other person has realised / opened an issue, clearly `BITCOIN_SUBDIR_TO_INCLUDE` is not getting much actual use, and isn't regularly breaking anyones ability to build (with BDB).

> Maybe consider https://github.com/theuni/bitcoin/commit/2ef8a6fc3b1de989702adb04ebb066bd101350f0 ?

Could be a (much simpler to review and grok) option, but so could just removing this code entirely, if it is completely broken, given the point above.
