### ISSUE TITLE
Document supported methods for backups and restore

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#20149]
Existing literature on backing up and restoring are on external sites and forums and may become outdated. They may also be recommending methods that could result in wallet file corruption. We should document the supported backup and restoration methods in repo or on the website so that people can refer to those as the officially supported methods. This also lets us update them as files and folder structures change.

**Comment by fanquake** [comment]
@achow101 were the additions in #22523 sufficient to close this?
