### ISSUE TITLE
Send raw transaction fails with   mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation) (code 16)

### ISSUE THREAD

**Issue by DHB94** [bitcoin/bitcoin#20144]
I try to send my transaction, but I receive this error message..
 mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation) (code 16)
It’s not a Multisignature Address.

For it to send and progagate.
Raw tx id

01000000017f5e04f7dbbc06cd88fd20e922960731594c7bbd5bfb8ab9c137d8c50ac7c4e5010000008b483045022100fc5e2ab560be4649b85511940daf8302cf2e2e06bfd60a75c8bae5f832da289c022045c4c9d548699bbc5f3484a2d6d59ac07ea3328a1deb6b2bb9f2f8f0727be1de014104d6597d465408e6e11264c116dd98b539740e802dc756d7eb88741696e20dfe7d3588695d2e7ad23cbf0aa056d42afada63036d66a1d9b97070dd6bc0c87ceb0dffffffff01e0919265170100001976a914963d18ef70ab28a0dbd15944721eb5673341db7a88ac00000000

Bitcoin core version 0.20
Windows 10
I’m creating my txs via btcpy library :)

**Comment by wpeckr** [comment]
Your $137M transaction is failing for the same reason your [$800M transaction](https://github.com/libbitcoin/libbitcoin-explorer/issues/672) failed, it is invalid, the money is not yours.

**Comment by DHB94** [comment]
No,
it’s definitely mine because It’s signed.
so that’s a bold accusation sir...
Do you have proof of your claim, because it’s slanderous..
To call someone a thief when they signed the transaction Is tantamount to calling anyone who has signed ever a thief.

**Comment by sipa** [comment]
This is a Bitcoin Core issue tracker. There is no issue here: you're giving it an invalid transaction and it is correctly reporting it as such.

**Comment by DHB94** [comment]
There is an issue though,
Because I’m using bitcoin core to send my transaction.
Furthermore
If it’s signed,
It’s not invalid..
![608EA0CA-B880-4102-BC64-788FCB54EAF9](https://user-images.githubusercontent.com/35415891/95939933-397d1700-0dab-11eb-96c9-e756b8940c90.jpeg)
