### ISSUE TITLE
Errors when Compiling

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#20208]
I am on Qubes OS (using a standalone Debian 10 qube with standard networking - this should mimic a standard system well).  I have attempted to use both GCC and Clang. I will start with GCC:

I install all dependencies without error. I clone the repo without error.  I change directories into my local copy, install Berkeley DB using the installation script included in the contrib directory, and take note of the export and configure paths (copy them, so I can't make mistakes).  I `export BDB_PREFIX='<PATH-TO>/db4'` from the BDB build previously.  `./autogen.sh` Then, copy the `./configure` command from the BDB build.  I get a configure error (sqlite3 not found) even though it is installed, which is weird.

Finally, `make`.  However, I keep getting the same error:

> make: ***No targets specified and no makefile found. Stop.

Restart machine, re-clone repo, doesn't matter.  Same outcome.

I talked with Jonatack , he suggested it might be a compiler issue.
Also talked with Bosch and JWweatherman, they suggested it might be a permissions issue, so:

GCC again, as root, and then I'll try with Clang as root:

GCC:

still have the `configure` error "sqlite3 not found"

still have the `make` error "No targets specified and no makefile found."

Clang:

after `sudo ./configure CC=clang CXX=clang++ BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"`:

> checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking whether the C++ compiler works... no
configure: error: in `/home/user/bitcoin':
configure: error: C++ compiler cannot create executables
See `config.log' for more details

Hmm, that is very weird.

I have a config.log in the following two places:

/home/user/bitcoin/db4/db-4.8.30.NC/build_unix/config.log
/home/user/bitcoin/config.log

The config files are about 5,000 lines and too much to paste here.

So, it seems this could be an issue with sqlite3 and/or Berkeley DB - perhaps something with the new wallet database?

**Comment by achow101** [comment]
If `configure` fails, then no `Makefile` is produced and `make` will fail. `configure` is failing because you are missing the `libsqlite3-dev` package.

**Comment by Rspigler** [comment]
Ah, I just had `sqlite3` installed, not `libsqlite3-dev`, thank you!
Thought it was much more complicated than that...
