### ISSUE TITLE
possible inconsistency in JSONRPCError

### ISSUE THREAD

**Issue by PiRK** [bitcoin/bitcoin#20209]
#16250 added a `JSONRPCError(RPC_INVALID_PARAMETER, "Missing redeemScript/witnessScript")` error in `src/rpc/rawtransaction_util.cpp` in case both the `redeemScript` and `witnessScript` are missing. Just before that, a `RPCTypeCheckObj()` is called with `fAllowNull=True`. If `fAllowNull` had been false, this function would have thrown a `JSONRPCError(RPC_TYPE_ERROR, "Missing redeemScript")`

I'm not sure which error is the right one for this case, between `RPC_INVALID_PARAMETER` and `RPC_TYPE_ERROR`, but I feel like it should be the same in both case.

**Comment by meshcollider** [comment]
From what I can tell, this isn't actually an issue, it is more a complaint about the code?

`RPCTypeCheckObj()` has `fAllowNull=True` set as a constant in the code, so the other error JSONRPCError can never be hit.

Closing this, but let me know if there is a real issue here.
