### ISSUE TITLE
Warning when linking libsecp256k1 exhaustive tests after building with depends

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#20225]
Just making a note of this, as I can't remember seeing it before. After building on macOS, when using depends, you may see:
```bash
  CC       src/exhaustive_tests-tests_exhaustive.o
  CCLD     exhaustive_tests
  CCLD     tests
ld: warning: dylib (/usr/local/Cellar/openssl@1.1/1.1.1h/lib/libcrypto.dylib) was built for newer macOS version (10.15) than being linked (10.12)
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: exhaustive_tests
PASS: tests
```

This is due to us passing `-mmacosx-version-min=10.12` when building depends, and the `libcrypto.dylib` on my machine being built for macOS 10.15. I say _may_  as this should depend on the version of the dylib on your machine, how it's been built by homebrew etc.

Can otherwise be replicated with:
```cpp
int main() {
    return 0;
}
```

```bash
clang++ test.cpp -lcrypto -L/usr/local/opt/openssl@1.1/lib -mmacosx-version-min=10.12
ld: warning: dylib (/usr/local/opt/openssl@1.1/lib/libcrypto.dylib) was built for newer macOS version (10.15) than being linked (10.12)
```

Note that `/usr/local/opt/openssl@1.1` is a symlink to `/usr/local/Cellar/openssl@1.1/1.1.1h`.

**Comment by willcl-ark** [comment]
@fanquake have you found this by building depends on 10.15? I just tried that and found a familiar error:

```
checking for mutexes... UNIX/fcntl
configure: WARNING: NO SHARED LATCH IMPLEMENTATION FOUND FOR THIS PLATFORM.
configure: error: Unable to find a mutex implementation
make: *** [/Users/will/src/bitcoin/depends/work/build/x86_64-apple-darwin20.1.0/bdb/4.8.30-8804e1a17bf/build_unix/.stamp_configured] Error 1
```

Related: https://github.com/bitcoin/bitcoin/pull/20195

**Comment by fanquake** [comment]
OpenSSL has been removed from the tests upstream, https://github.com/bitcoin-core/secp256k1/pull/983, so we can close this.
