### ISSUE TITLE
Fees

### ISSUE THREAD

**Issue by era-coder** [bitcoin/bitcoin#20261]
Is there a future plan to make the fees lower ? Will BTC block size increase after the 5G being rolled out in the world ? We could really use a Little bigger block while also developing lighting network . Please don't close this and let's have a conversation.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
