### ISSUE TITLE
The listtransactions command does not display transactions when restoring a wallet from a backup

### ISSUE THREAD

**Issue by du2zy** [bitcoin/bitcoin#20293]
In March, I made a backup of the wallet and continued using the node. In October, I restored my old backup. After restoring the backup, I found that the listtransactions command stopped displaying some transactions made during the period from March to October.

**Expected behavior**

The listtransactions command displays all transactions in the restored wallet.

**Actual behavior**

The listtransactions command in the restored wallet does not display some transactions since the backup.

**To reproduce**

1. Run bitcoin core in regtest mode
2. Create a new address A and generate 101 blocks with sending a reward to the created address A
3. Create a wallet backup
4. Create new address B
5. Send transaction to address B, write TXID
6. Generate 1 block with sending a reward to address A
7. View getaddressinfo B. Verify labels are not an empty list
8. View listtransactions. Make sure there is a TXID transaction present
9. Stop bitcoin core
10. Restore backup
11. Run bitcoin core
12. View getaddressinfo B and listtransactions. Detect that the address does not have a label set and that listtransactions does not contain a TXID transaction.

**System information**

Bitcoin Core 0.20.1 on Debian GNU / Linux.

**Comment by prayank23** [comment]
> 3. Create a wallet backup

Maybe 3 can be done after 8 

I was not able to reproduce this issue in bitcoin core (testnet). I followed the below steps:

1. Create new wallet (testnet)
2. Create new address with label: `testlabel`
3. Send 0.005 tBTC : https://blockstream.info/testnet/tx/6b9d739034c32d6480ca8ccac567d05226d948e85c8adddb06340c5ff3c32526
4. Check the transaction using `listtransactions`
5. Backup wallet
6. Exit bitcoin core and delete wallet folder from `testnet3/wallets`
4. Copy the backup file in wallets folder: `backuptest2.dat`
5. Start bitcoin core and check the transaction using `listtransactions`

![image](https://user-images.githubusercontent.com/13405205/98040574-7dad8580-1e46-11eb-80f3-99eab694eb62.png)

**Comment by du2zy** [comment]
My reproduce steps are correct.

First I make a backup, after that I use the wallet for a while, then I restore the backup. At the same time, the backup does not contain the last few addresses and transactions.
After restoring the backup, I expect to see all transactions for the entire period from the moment the wallet was created to the current moment. I really see that the last addresses and transactions have been restored, I can use the funds received.

However, there is a problem. I do not see in the output of listtransaction some transactions that were made after the backup was created. There are no transactions in the output that I make within my wallet (transferring funds from address to address).

Experimentally, I found out, when restoring from a backup, automatically generated addresses are created without a label. Perhaps this is the reason.

**Comment by Crypto2** [comment]
When you use getaddressinfo does the address say ischange: true? If so it's probably this same longstanding bug: https://github.com/bitcoin/bitcoin/issues/16160 - if so it's an easy fix and documented in that thread.

**Comment by du2zy** [comment]
Yes, it is the very same problem. Am I right that that this problem cannot be solved without bitcoin core compilation?

**Comment by Crypto2** [comment]
Correct, you do have to comment those lines out and recompile.

**Comment by du2zy** [comment]
Unfortunately, we don't have a possibility to compilate bitcoin-core from the source code. I tried to revive the discussion in that issue which you sent to me. I added links to bug descriptions and steps to reproduce the problem. But that issue is closed and it's possible that my message will be ignored. Is there some possible way to attract developers' attention to that problem?

**Comment by Crypto2** [comment]
You said you are on Linux, why can't you compile it? It's very easy to do.

**Comment by du2zy** [comment]
We use not only bitcoin-core, but also a lot of bitcoin-based forks (such as LiteCoin, DASH, OmniCore, etc.) Manually apply the patch to all the coins, and it is very consuming to maintain in future updates. Therefore, we hope to see the fix included into upstream.
