### ISSUE TITLE
Processblock not accepted, leveldb batch commit failure: IO error: unsufficient space

### ISSUE THREAD

**Issue by RagnarLothbrok25** [bitcoin/bitcoin#20327]
Fatal error has occurred, BAD_Alloc runaway exception error when starting bitcoin core

Debug log says error on processblock 
Then creates orphanblocks and finally ends with:

LevelDB batch commit failure: IO error: winmapfile.append::unmapcurrent region or mapnewregion : unsufficient memory available to process this task

Error AcceptBlock : Addtoblockindex failed
Error ProcessBlock : Acceptblock failed
Processblock, block not accepted

> Orphanblock

Can anyone help me with this issue?

I did fix the bad alloc runaway error with this memory issue before by configuring the configuration file adding the following:

Listen=1
Bind=0.0.0.0
Port=8333
Maxconnections=64
Maxmempool=32
Upnp=1
Dnsseed=1
Discover=1

Dbcache=18
Dblogsize=50
Par=1
Checkblocks=2000
Checklevel=6

Disablewallet=0

Rpcbind= 127.0.0.1
Rpcport=8333
Rpcallowip=127.0.0.1

Maxuploadtargets=32
Rescan=1

Maxorphanblocksmib=80

Testnet=0

Can anyone help me solve the issue?

It keeps coming back at the memory issue as the underlying problem but why does it not accept the block? 

I think I need to fix the memory issue first. This is done on the latest bitcoin core wallet

**Comment by MarcoFalke** [comment]
What hardware/OS are you running on?

**Comment by RagnarLothbrok25** [comment]
Windows 10 latest version, 8 gig Ramapo, also did chkdsk through command prompt

**Comment by MarcoFalke** [comment]
Does the error happen when you remove this line?

>  Checkblocks=2000

**Comment by RagnarLothbrok25** [comment]
Bad alloc error still occurs when removing that line

**Comment by MarcoFalke** [comment]
Without a debug log this is hard to debug

Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

Please be aware that the debug log might contain personally identifying information.

**Comment by MarcoFalke** [comment]
Regardless of the issue here, I suggest you clear you config of settings that aren't applicable. There is at least one setting misspelled and another one long removed from Bitcoin Core anyway.
