### ISSUE TITLE
Q: cs_main protection for referencing m_blockman/g_chainman?

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#20325]
While making my [de-globalize ChainstateManager](https://github.com/bitcoin/bitcoin/pull/20158) changes, I noticed something that I wasn't sure what to make of: both the global instance of `ChainstateManager` `g_chainman` and the `BlockManager` member of `g_chainman` are protected by `::cs_main`.

This means that changes like the following where I'm simply passing a `BlockManager` to a function have to add an awkward `WITH_LOCK` in order to appease thread safety analysis.

Examples:
1. [`d227dfe` (#20158)](https://github.com/bitcoin/bitcoin/pull/20158/commits/d227dfedfdfc5f8df05f13ee31a475a5a716c151#diff-ccc24453c13307f815879738d3bf00eec351417537fbf10dde1468180cacd2f1)
2. [`f8e91ed` (#20158)](https://github.com/bitcoin/bitcoin/pull/20158/commits/f8e91ed44a8f4deb9440e0c4d2829733399bcda2#diff-1ef3b6a1936b50f3d5ec4a1786d9e2d63d1a3e1815b103e67f20601995f355b4)

However, I'm not entirely sure if these `::cs_main` protections should be required for referencing these objects themselves, especially since `ChainstateManager` and `BlockManagers`'s member variables/functions are already well annotated w/re locks.

Any insights would be useful :-)

**Comment by MarcoFalke** [comment]
Is this still an issue?

**Comment by dongcarl** [comment]
Nope!

For context see: #24024
