### ISSUE TITLE
GUI-Feedback on calculating transaction fees 

### ISSUE THREAD

**Issue by pisjatblin** [bitcoin/bitcoin#20348]
I stumbled across fee calculation messing up units. 
Please take a look at this [discussion](https://bitcoin.stackexchange.com/questions/99915/bitcoin-qt-ignored-user-input-for-fee-calculation/99917#99917) which is related [to](https://github.com/bitcoin-core/gui/issues/64).

Therefore, I'd like to suggest the following use case: 
User selects manually editing fee and user asks for sending.
Next bitcoin-qt calculates the fee added to the transaction then GUI shows to user the calculated fee and ask for confirmation.
If ok, then send transaction else edit fee calculation and repeat.

**Comment by hebasto** [comment]
Please submit this issue into the proper repo: https://github.com/bitcoin-core/gui/issues, and close it here.

**Comment by pisjatblin** [comment]
Thanks for your hint hebasto. Please find my feature request [here](https://github.com/bitcoin-core/gui/issues/130).
