### ISSUE TITLE
test_bitcoin-qt shouldn't bind to regtest ports

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#20363]
`test_bitcoin-qt` binds to the regtest ports which causes it to hang if a regtest bitcoind or bitcoin-qt is already running. This causes `make check` to hang and be annoying to kill. So `test_bitcoin-qt` shouldn't bind to these ports to avoid conflicting with an active regtest instance. Or it should fail gracefully instead of just hanging and then timing out.

**Comment by jonatack** [comment]
Concept ACK. Thank you for bringing this up; it's been an annoyance for some time now.

**Comment by MarcoFalke** [comment]
Concept ACK, but duplicate of https://github.com/bitcoin-core/gui/issues/10

**Comment by achow101** [comment]
> Concept ACK, but duplicate of [bitcoin-core/gui#10](https://github.com/bitcoin-core/gui/issues/10)

lol, I thought I remembered opening this before but I couldn't find it.

**Comment by practicalswift** [comment]
Concept ACK
