### ISSUE TITLE
compile_commands.json generated ERROR with ccls under VIM mode

### ISSUE THREAD

**Issue by Yihen** [bitcoin/bitcoin#20369]
$ ./autogen.sh
$ ./configure -without-gui
$ compliedb -n make 

when I use vim to open the project , the are some warning information display as follow:
![WX20201111-174002](https://user-images.githubusercontent.com/7480459/98795824-a258bd00-2445-11eb-9936-ae5ca372700c.png)

which are all about c++ standard library. does it have relationship to Makefile which was auto generated by autopen.sh?
**Expected behavior**
NO ERROR DISPLAY

**Actual behavior**

**To reproduce**

**System information**
bitcoin version: commit-id  218fe60d91a9190aa0ee561479044df368214766

**Comment by fanquake** [comment]
This seems like a configuration issue with your editor, and not a problem with Bitcoin Core. I have used `compiledb` to generate a `compile_commands.json` before, see here: https://github.com/fanquake/core-review/blob/master/clang-tools.md#generating-a-compilation-database, however we have no official documentation relating to its usage, or for editor configuration.

**Comment by Yihen** [comment]
@fanquake thanks for your mention. I have solved this problem by following website:
https://stackoverflow.com/questions/61150687/how-to-add-include-path-for-language-servers-in-coc-settings-json-file

"initializationOptions": {                                                                                        
                                    "cache": {                                                                                                
                                            "directory": "/tmp/ccls"                
                                    },                                              
                                    "clang": {                                      
                                            "extraArgs": [                          
                                                    "-I",                           
                                                    "/opt/ros/kinetic/include/"     
                                            ]                                       
                                    }                                               
                            }

the MAIN REASON is coc.vim setting is incorrect about ccls;
