### ISSUE TITLE
Bitcoin core locks up when hovering over Open Wallet menu item

### ISSUE THREAD

**Issue by dikkedimi** [bitcoin/bitcoin#20397]
Issue description
Bitcoin Core locks when hovering over File - Open wallet  with the mouse pointer on macOS Catalina 10.15.7
expected behaviour
none, until actually clicking the menu item.

actual behaviour
spinning beach ball of death for an determinite amount of time. Force quit seems only option to escape loop.

reproduction
happens every time

version of Bitcoin Core 
0.20.1 from bitcoin.org

Hardware used
mac mini 2012

OS Version
macOS Catalina 10.15.7

Log is flooded with the following message:
`ListWalletDir: Operation not permitted /Volumes/Blockchain/.DocumentRevisions-V100`

**Comment by hebasto** [comment]
@dikkedimi 
Pleas move this issue into the https://github.com/bitcoin-core/gui/issues

**Comment by promag** [comment]
Like @hebasto says, this was fixed in #19502 which is already merged.
