### ISSUE TITLE
Bitcoin address format.

### ISSUE THREAD

**Issue by wc-codebase** [bitcoin/bitcoin#20433]
**Is your feature request related to a problem? Please describe.**

Dear everyone,
I'm working on cryptocurrency exchange platform newly.
I downloaded bitcoin-core and synchronized  full node.
I'm using JSON-RPC request to connect to bitcoind.
I created new wallet and it always returns  segwit address.
**Describe the solution you'd like**

There are 3 formats for bitcoin address.
P2PKH or Legacy Address Format (addresses start with “1”)
P2SH or Compatibility Address Format (addresses start with “3”)
Bech32 or Segwit Address Format (addresses start with “bc1”)
**Describe alternatives you've considered**

But Bech32 address is not recognized in several exchanges and I need get P2PKH or P2SH address.
**Additional context**
How can I get this type address by using JSON-RPC ?
Please help me !!!!!

**Comment by MarcoFalke** [comment]
Call `help the_rpc_you_are_using_to_get_the_new_address`

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
