### ISSUE TITLE
bitcoin-cli getbalance shows zero wallet balance after reindexing

### ISSUE THREAD

**Issue by cryptoqube777** [bitcoin/bitcoin#20453]
I have encountered the following issue while using Bitcoin Core 0.20.1

Initially I started bitcoind with **txindex=0** in configuration file
Later I changed this option to **txindex=1** and restartted bitcoind with **-reindex** key

After complete reindexing I have the following issue
**getbalance shows 0** (which makes impossible to use **sendtoaddress** resulting _"Insufficient funds"_ error message)
**getreceived by address shows correct amount of 0.604 BTC**

Before reindexing everything worked perfect. Only txindex option was changed in bitcoin.conf and -reindex key added to command line parameters. No other changes were made. Reindex was completed, since **getblockcount** shows correct blockchain block count. 

I am running Bitcoin Core v.0.20.1 on Debian 10 on Testnet3

**Comment by cryptoqube777** [comment]
Additional issue, which I suppose concerns previous:
I'm using single walletm but with several labels
Each label has only 1 address, generated by **bitcoin-cli getnewaddress label**
I have 0.0011 BTC on one address
After i send 0.0001 BTC to second address within my wallet I have the following output:
**bitcoin-cli getbalance** returns 0.0001
**bitcoin-cli listreceivedbyaddress "address" 0** for each of two addresses returns
0.0011 for the first one
0.0001 for the second one

And after this i can use sendtoaddress only within 0.0001 balance of second address.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
