### ISSUE TITLE
Move travis linter job to cirrus

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20467]
Travis is shutting down, so the last remaining job needs to be moved to cirrus ci. The others have been moved in #19179.

#### Useful skills:

Backround in:
* Travis CI, Cirrus CI
* python, bash
* linters

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by EddCS** [comment]
I can do this over the weekend.

**Comment by EddCS** [comment]
> I can do this over the weekend.

I said, naively. I can however definitely do it this week, and will take a look tonight.

**Comment by Humblya** [comment]
Xtrades member wins - What are you waiting for? [https://llurl.co/?RWjO2Ok
![Uploading MW_122.png…]()
](url)

**Comment by dhruv** [comment]
@EddCS I was looking to learn more about CI, so I tinkered with this and made #20658. Don't mean to take away from any progress you may have made. If you'd like to collaborate, let me know.
