### ISSUE TITLE
macOS 11 (Big Sur) visual bugs

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#20481]
Nighy build on Big Sur "dark mode":
![Screenshot 2020-11-24 at 20 13 04](https://user-images.githubusercontent.com/178464/100140847-cda1ca00-2e91-11eb-9cc7-f0afbf542df8.png)

Self compiled on Big Sur "night mode" with depends:
![Screenshot 2020-11-24 at 20 10 38](https://user-images.githubusercontent.com/178464/100141076-1e192780-2e92-11eb-88fc-fb0c8975d2bc.png)

Two major issues:
* [ ] disabling the night mode color palette or adopt it correctly (probably a QT upstream issue)
* [ ] get rid of the white glitch in the debug-window tab-bar-menu 

Qt upstream issue: https://bugreports.qt.io/browse/QTBUG-85546

**Comment by MarcoFalke** [comment]
Could be filed in the gui repo?

https://github.com/bitcoin-core/gui/issues/new?assignees=&labels=Bug&template=bug_report.md&title=macOS%2011%20(Big%20Sur)%20visual%20bugs&body=Nighy%20build%20on%20Big%20Sur%20%22dark%20mode%22:![Screenshot%202020-11-24%20at%2020%2013%2004](https://user-images.githubusercontent.com/178464/100140847-cda1ca00-2e91-11eb-9cc7-f0afbf542df8.png)Self%20compiled%20on%20Big%20Sur%20%22night%20mode%22%20with%20depends:![Screenshot%202020-11-24%20at%2020%2010%2038](https://user-images.githubusercontent.com/178464/100141076-1e192780-2e92-11eb-88fc-fb0c8975d2bc.png)Two%20major%20issues:*%20[%20]%20disabling%20the%20night%20mode%20color%20palette%20or%20adopt%20it%20correctly%20(probably%20a%20QT%20upstream%20issue)*%20[%20]%20get%20rid%20of%20the%20white%20glitch%20in%20the%20debug-window%20tab-bar-menuQt%20upstream%20issue:%20https://bugreports.qt.io/browse/QTBUG-85546

**Comment by jonasschnelli** [comment]
I wanted to open it there. Will move.

**Comment by jonasschnelli** [comment]
moved to https://github.com/bitcoin-core/gui/issues/136
