### ISSUE TITLE
Question: How to debug using docker & CI shell script?

### ISSUE THREAD

**Issue by kiminuo** [bitcoin/bitcoin#20488]
Hi,

my PR #19245 fails on several platforms so I have attempted to run on my Ubuntu 20.04:

```bash
FILE_ENV="./ci/test/00_setup_env_native_tsan.sh" ./ci/test_run_all.sh
```

as per instructions in https://github.com/bitcoin/bitcoin/tree/master/ci.

I can reproduce issue on CI which is great news. However, I would love to modify source code and re-run the `FILE_ENV="./ci/test/00_setup_env_native_tsan.sh" ./ci/test_run_all.sh` script or attach to docker to run a failing functional test again so that I can debug it easier.

Does anybody have a workflow for this? 

Notes:
* I've tried `docker attach <container ID>` but it's not possible to simply execute `test/functional/wallet_hd.py` as it fails in that docker instance because it is supposed to be run somehow differently (that's as much as I gather from studying `ci/test_run_all.sh`).

**Comment by MarcoFalke** [comment]
The CIs compile from a `make dist` tarball, so if you want to modify the code, you'll need to modify the one in `./ci/scratch/...` inside the docker

**Comment by promag** [comment]
Or you could write a Dockerfile with the desired environment and mount the source there.

**Comment by kiminuo** [comment]
I will tinker with it. Thank you for the help.
