### ISSUE TITLE
lifetimebound compile attribute

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20493]
(copied from https://github.com/bitcoin/bitcoin/pull/19387#issuecomment-652708587 ):

There are a lot more cases in the codebase where a data type stores a reference or pointer to another object provided to the constructor exist. For example:

* [ ] In `src/stream.h`: `OverrideStream`, `CVectorReader`, `BitStreamReader`, `BitStreamWriter`
* [x] In `src/script/sign.h`: `MutableTransactionSignatureCreator` (#19426).
* [ ] In `src/script/interpreter.h`: `GenericTransactionSignatureChecker`
* [ ] In `src/serialize.h`: `Wrapper`, `Using`
* [ ] In `src/wallet/rpcwallet.cpp`: `DescribeWalletAddressVisitor`
* [ ] In `src/key_io.cpp`: `DestinationEncoder`
* [ ] In `src/dbwrapper.h`: `CDBBatch`, `CDBIterator`
* [ ] In `src/flatfile.h`: `FlatFileSeq`
* [ ] In `src/hash.h`: `CHashVerifier`
* [ ] In `src/miner.h`: `CBlockAssembler`
* [ ] In `src/net_processing.h`: `PeerLogicValidation`
* [x] In `src/scheduler.h`: `SingleThreadedSchedulerClient` (#25040)
* [ ] In `src/sync.h`: `CSemaphoreGrant`
* [ ] In `src/validation.h`: `CScriptCheck`, `ChainstateManager`,  `CChainState`

Several of these accept const lvalue references, and store them, and are at risk already. Others take in a mutable lvalue reference or pointers, but would make sense to support rvalue/universal references as input (so that temporaries can be passed to it). In all those cases, having a `lifetimebound` attribute would be useful.

So I think that means we should just put it in attributes.h. There is plenty of potential for it.

**Comment by laanwj** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
Looks like `LIFETIMEBOUND` does not work for function parameters that are not references or pointers. So for example, it does not tie to `std::string_view`, but it does tie to `const std::string_view&`. However, it will then treat *any* temporary as a violation. For example, `TrimStringView(view.substr(6))` is a violation.

**Comment by MarcoFalke** [comment]
Closing for now, but improvements are welcome
