### ISSUE TITLE
use try_emplace on std::map with c++17

### ISSUE THREAD

**Issue by sidhujag** [bitcoin/bitcoin#20500]
Let's have a discussion and see if a structure change is warranted to many places std::maps/unsorted_maps are used in the code.

Now that we support c++17 as a minimum as of #[20413](https://github.com/bitcoin/bitcoin/blob/2f71a1ea35667b3873197201531e7ae198ec5bf4/src/coins.cpp#L42) we should consider using try_emplace to gain efficiency when objects are not added, it also leads to more expressive and safer code(prevents stealing from arguments during failed insertion). For example, it seems FetchCoin uses emplace but does a piecewise_construct however it can be replaced with try_emplace:

`CCoinsMap::iterator ret = cacheCoins.emplace(std::piecewise_construct, std::forward_as_tuple(outpoint), std::forward_as_tuple(std::move(tmp))).first;`

becomes
`
CCoinsMap::iterator ret = cacheCoins.try_emplace(outpoint, std::move(tmp)).first;`

I also noticed emplace was used on dir_locks which is a map to unique_ptrs which is generally discouraged. It is used [here](https://github.com/bitcoin/bitcoin/blob/5a6f3c5a01eaf904c42bd77dbed931b49a8fec74/src/util/system.cpp#L107) and should likely just look like this:

`dir_locks[pathLockFile.string()] = std::move(lock));`

**Comment by gloriashaw** [comment]
Hi everyone are you looking for a professional binary, forex and Bitcoin broker/manager who will guide and help manage your trade and help you earn meaningful profits all within seven days contact Mr Barry Silbert now for your investment plan. For he has helped me to earn 10,250 USD just with a little investment capital and with the aid of his trading software system that brings forth good trading signals i was able to trade and cash out on time and am still trading with him, if you need his assistance on how to recover your lost investment in bitcoin/binary Contact him now on whatsaap +447508298691. or contact him on his email address Email: Barrysilbert540 @ gmail com [WITH MR BARRY I BELIEVE THERE ARE STILL GOOD INDIVIDUALS WHO STILL HAVE GOOD INTENTION TO OTHERS. ONCE AGAIN THANKS MR BARRY.]

**Comment by IamShubhamGupto** [comment]
Hey, id like to work on this

**Comment by fanquake** [comment]
Going to close this for now. Feel free to open a PR with code changes. That is likely a better venue for discussion than opening an issue.
