### ISSUE TITLE
Partially Signed Bitcoin Transaction (PSBT) GUI for Bitcoin Core Request

### ISSUE THREAD

**Issue by robbie2121** [bitcoin/bitcoin#20515]
Dear Developers,

Do you fine people plan on adding a GUI to Bitcoin Core so that users can create a PSBT and  also sign a PSBT for cold storage users? I would love this feature!!!!! I think you can do this with command line but it's risky and not simple. I ask because I only use Bitcoin Core as my wallet and don't have easy cold storage spending method without bringing all online.

Thank you and I love you all!

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
an easy to use GUI to create a PSBT and to sign a PSBT for cold storage.

**Describe alternatives you've considered**

**Additional context**

**Comment by gloriashaw** [comment]
Hi everyone are you looking for a professional binary, forex and Bitcoin broker/manager who will guide and help manage your trade and help you earn meaningful profits all within seven days contact Mr Barry Silbert now for your investment plan. For he has helped me to earn 10,250 USD just with a little investment capital and with the aid of his trading software system that brings forth good trading signals i was able to trade and cash out on time and am still trading with him, if you need his assistance on how to recover your lost investment in bitcoin/binary Contact him now on whatsaap +447508298691. or contact him on his email address Email: Barrysilbert540 @ gmail com [WITH MR BARRY I BELIEVE THERE ARE STILL GOOD INDIVIDUALS WHO STILL HAVE GOOD INTENTION TO OTHERS. ONCE AGAIN THANKS MR BARRY.]

**Comment by mjdietzx** [comment]
Can't you already do this? In the `Send` tab, after you've set the `Pay To` address and `Amount` / all that stuff. Click `Create Unsigned` in the bottom left corner of the GUI after

Also assuming you already have created a watch-only wallet for your hardware wallet, and have that open ^

**Comment by robbie2121** [comment]
> Can't you already do this? In the `Send` tab, after you've set the `Pay To` address and `Amount` / all that stuff. Click `Create Unsigned` in the bottom left corner of the GUI after
> 
> Also assuming you already have created a watch-only wallet for your hardware wallet, and have that open ^

As far as I know you can't fully complete a PSBT with just Bitcoin Core using the GUI. I think you may be able to create an unsigned transaction with a watch-only Bitcoin Core but Bitcoin Core can't do the other half of completing the transaction using the GUI. I don't use hardware wallets. I only use Bitcoin Core wallet.

If i'm wrong please let me know and if you can let me know a guide I can follow. thank you

**Comment by achow101** [comment]
This has already been done in #18027 and it will be available in 0.21.

**Comment by robbie2121** [comment]
> This has already been done in #18027 and it will be available in 0.21.

omg thank you so much!

**Comment by MarcoFalke** [comment]
rc2 is now available:

   *  https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2020-November/000094.html

Be use caution when testing, as the release is not yet final

**Comment by robbie2121** [comment]
> rc2 is now available:
> 
> * https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2020-November/000094.html
> 
> Be use caution when testing, as the release is not yet final

Okay thank you! I'll check it out!!!

**Comment by adamjonas** [comment]
Believe this could be closed now with https://github.com/bitcoin/bitcoin/pull/18027 merged.
