### ISSUE TITLE
generatetoaddress blocks don't include tx'es from mempool

### ISSUE THREAD

**Issue by ivan386** [bitcoin/bitcoin#20518]
I mined in offline mode >101 test blocks. Then i try to send some test coins on other wallet. Coins stay unconfirmed even after 14 new blocks made by generatetoaddress command in console.

**Expected behavior**

Generated blocks by command generatetoaddress include tx'es from mempool.

**Actual behavior**

All new blocks made by generatetoaddress command have only one tx. It don't use mempool.

**To reproduce**

1. Run new installation of Bitcoin Core in offline mode
2. Generate > 101 blocks by command in console:
  ```generatetoaddress 102 getnewaddress() -1```
3. Create new Wallet and send some coins on it
4. Generate more blocks by command in console:
  ```generatetoaddress 10 getnewaddress() -1```

**System information**

v0.19.0.1

**Comment by MarcoFalke** [comment]
What is the output of `getmempoolinfo` and `getrawmempool` and what config settings have been used?

**Comment by ivan386** [comment]
getmempoolinfo

{
  "loaded": true,
  "size": 9,
  "bytes": 1809,
  "usage": 12368,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000
}

getrawmempool

 [
 "0902ab3cff6c1fad4f34bb9f282af6450c21cdd6f157c9a150c4743b4a85cd0f",   "3767516d3776e5de68799b26ae0709b020a1c85322dde5706a6dd889b3008dc5",   "feda0d2fe0b55507c50ff3ff3cf6a50bf1019c4509cded33e0e3ed68edad60fd",   "57d93edfb0918e9cbbb3f904f84e649b2263fc73e93d33fac1a0f64f291de449",   "30346094a2fe04238540fb458d1c2c562d2234f113277ed74db3dee0c11490ec",   "64a8caa2a907351fbcaffadb130da6760a4b0459a3ada9d72d71bfac8725e574",   "c2eab9d7e5c4d5494a362ec2df6b8d819f165b3971a4f8a6b213267b9602a456",   "13f2c780366e5829437f1cfbebfff8dfecc5c47596e6e1b6104b9c89da621130",   "ecf0bb4377d0a27fb052459f71eb81b1b517b95defb6a4afb22c9ea11e976f29"
 ]

bitcoin.conf empty

**Comment by MarcoFalke** [comment]
I can't reproduce

![Screenshot from 2020-11-27 14-47-52](https://user-images.githubusercontent.com/6399679/100455781-96b0fb80-30bf-11eb-8c6a-9b291590c1f4.png)

**Comment by ivan386** [comment]
How you generate block with that difficulty. I cant generate block without zeros in start of hash.

**Comment by kizoojun01** [comment]
Ki

**Comment by MarcoFalke** [comment]
> I cant generate block without zeros in start of hash.

What is the error message?

**Comment by ivan386** [comment]
No errors. Just empty array with default settings. And block with zeros in start of hash with -1.

**Comment by ivan386** [comment]
I guess i found what the problem. I use legacy adress for input, output and generate and then this one tx accepted in block. Maybe i need somehow turn on use of segwit and bench32 in blocks?

**Comment by MarcoFalke** [comment]
I suggest you test in regtest for faster blocks

**Comment by MarcoFalke** [comment]
Let me know if you can reproduce this in regtest
