### ISSUE TITLE
Write detection lacking

### ISSUE THREAD

**Issue by abergmeier** [bitcoin/bitcoin#20529]
I am trying to start `bitcoin-core.daemon` via

```
$ bitcoin-core.daemon -datadir=/home/user/.bitcoin -debug=1
```

**Expected behavior**

`bitcoin-core.daemon` should start. Or if it can't it should provide helpful output what the problem is

**Actual behavior**

Output is:
```
Error: Cannot write to data directory '/home/user/.bitcoin'; check permissions.
```

Looking on the filesystem everything seems fine:
```
$ ls -lah /home/user/.bitcoin
drwxrwx---  3 user user 4,0K Nov 29 16:44 .
$ mkdir /home/user/.bitcoin/foo
$ echo $?
0
```

So I took a look, where the error message is actually produced in the source.
Digging deeper into `DirIsWritable` there seems to be a lack of any tracing or debugging.
Same with `fsbridge` - there is no handling of `errno`.
So it seems like the bitcoin binary has no way of providing any helpful information about the actual problem 😞 .

Now , since `bitcoin-core` is installed via stable snap channel one could assume a problem with some sort of security confinement. Thus I double checked in snap and _bitcoin-core_ is allowed to modify the user directory (whatever this means in detail).
Since I am no expert in snap nor bitcoin I am not really sure how to get to any further.

**To reproduce**

- Install Ubuntu 20.04
- Install bitcoin-core via snap stable
- Try to start `bitcoin-core.daemon`
  `/home/user/.bitcoin` is preexisting

**System information**

```
$ bitcoin-core.daemon -version
Bitcoin Core version v0.20.1
```

Running a machine with x86_64

**Comment by MarcoFalke** [comment]
To solve permission errors while using the Bitcoin Core snap, see https://snapcraft.io/docs/removable-media-interface . I.e. `snap connect bitcoin-core:removable-media` or `snap connect bitcoin-core:home`.

On some systems, `snap` may not allow access to paths with `.` as first character.
