### ISSUE TITLE
sat/b values aren't validated to be in-range

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20534]
values smaller than 0.001 sat/B can't be represented by CFeeRate, but they are not rejected.

```
./src/bitcoin-cli -named sendtoaddress address=bcrt1qwkmhqum095zau5rf2velq55cq938vrd7uw8m4r amount=1.23 fee_rate=0.0009

error code: -6
error message:
Fee rate (0.000 sat/vB) is lower than the minimum fee rate setting (1.000 sat/vB)
```

```
./src/bitcoin-cli -named sendtoaddress address=bcrt1qwkmhqum095zau5rf2velq55cq938vrd7uw8m4r amount=1.23 fee_rate=0.000000000009

error code: -3
error message:
Invalid amount

**Comment by jonatack** [comment]
@MarcoFalke I'll look at this, unless you're on it already.

**Comment by MarcoFalke** [comment]
Not working on this right now

**Comment by jonatack** [comment]
Proposed fix in #20546.

**Comment by jonatack** [comment]
I think this issue is resolved in a nice and very well-tested way in the overhauled/reworked version of #20546. Otherwise this issue could be closed as wontfix.

**Comment by jonatack** [comment]
Proposed a larger solution in #21786.
