### ISSUE TITLE
intermittent issue in interface_zmq "assert_equal(struct.unpack('<I', seq)[-1], self.sequence)"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20538]
```
Traceback (most recent call last):
  File "./test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "./test/functional/interface_zmq.py", line 73, in run_test
    self.test_basic()
  File "./test/functional/interface_zmq.py", line 119, in test_basic
    txid = hashtx.receive()
  File "./test/functional/interface_zmq.py", line 41, in receive
    assert_equal(struct.unpack('<I', seq)[-1], self.sequence)
  File "./test/functional/test_framework/util.py", line 50, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(1 == 0)
```

* https://cirrus-ci.com/task/4797090746335232?command=ci#L4841
* https://cirrus-ci.com/task/5508595028590592?command=ci#L4902

**Comment by MarcoFalke** [comment]
I've seen this multiple times

cc @instagibbs

**Comment by instagibbs** [comment]
Which notifications are you listening to?

**Comment by instagibbs** [comment]
Ah sorry, email notification confusion.

I'll take a look and see if I can reason about it.

**Comment by instagibbs** [comment]
@MarcoFalke do you have access to logs? This is pretty cut and dry "shouldn't happen" territory.

**Comment by instagibbs** [comment]
Nothing fishy in the logs.

It's possible that this chunk of code isn't lenient enough under certain conditions, causing the first message to get lost:
```
        # Relax so that the subscriber is ready before publishing zmq messages
        sleep(0.2)
```

**Comment by MarcoFalke** [comment]
Removing the sleep gives `zmq.error.Again: Resource temporarily unavailable`, which I've also seen in some test failures. Generally, a hardcoded sleep is a recipe for intermittent failures.

Is it not possible for zmq to fully boot up (like the rpc interface) when the server is starting?

How is this dealt with in production?

**Comment by instagibbs** [comment]
In prod you don't "expect" any specific message so you start with whichever
one you get.

I think for tests we could just have a block making and zmq consumption
loop that "syncs up" the expected message then continues onto the rest of
the test?

**Comment by instagibbs** [comment]
E.g., make a block, try to read off zmq messages until you get it(with
timeout), if that fails with timeout do it again. Rinse repeat until you
get the message.
