### ISSUE TITLE
PSBT is not handling PSBT_GLOBAL_XPUB

### ISSUE THREAD

**Issue by benma** [bitcoin/bitcoin#20533]
The PSBT_GLOBAL_XPUB should be populated when creating PSBTs when using multisig, as offline signers such as the BitBox02 hardware wallet require it to register and retrieve a multisig account.

https://github.com/bitcoin/bitcoin/blob/817aeca57a4cc3c8b4b321dbc653bfc4a8d61b0c/src/psbt.h#L20 

Would there be any obstacles in implementing this?

**Comment by achow101** [comment]
See #16463

**Comment by fanquake** [comment]
#16463 was combined into #17034, which has been merged.
