### ISSUE TITLE
"Segmentation Fault: 11" on MacOS when "-rescan"

### ISSUE THREAD

**Issue by decryp2kanon** [bitcoin/bitcoin#20604]
Its a custom testnet based on `v0.21.0rc1` But I couldn't test on real bitcoin, because I do not have such large BTC wallet.dat. I may test on regtest soon.

- Reproduce
Run bitcoind with `-rescan` large wallet.dat (~1 GB mining wallet).

Strange thing is Linux64 is just fine, but MacOS and Win10 this error.
- MacOS
```
Segmentation Fault: 11
```
- Win10: Similar behavier like MacOS, but daemon just killed. No Segfault or any error log.

- FYI:
Win10 2cpu 4096ram
MacOS (High Sierra 10.13.3) 2cpu 4096ram (Macbook Air 13 Inch 2011)

- Related Issues
bitcoin/bitcoin#4607
bitcoin/bitcoin#12318
bitcoin/bitcoin#9816

**Comment by MarcoFalke** [comment]
So this is self-compiled?

Is it an OOM?

**Comment by decryp2kanon** [comment]
> So this is self-compiled?
Its gitian release

**Comment by decryp2kanon** [comment]
> Is it an OOM?

Possibly. Win10 is 2cpu4096ram. MacOS is 2cpu4096ram (Macbook Air 2011)

**Comment by sipa** [comment]
I'm surprised loading a 1 GB wallet file works at all with that amount of memory...

**Comment by decryp2kanon** [comment]
> I'm surprised loading a 1 GB wallet file works at all with that amount of memory...

Do you mean, is this just OOM?

**Comment by sipa** [comment]
> Do you mean, is this just OOM?

Yes, I assume so. Wallets are loaded entirely into memory, and the in-memory representation is often several times larger than the on-disk serialization.

**Comment by decryp2kanon** [comment]
> Wallets are loaded entirely into memory

How much RAM do I need if I wanna load 1GB wallet.dat?

**Comment by decryp2kanon** [comment]
Since its not a bitcoin issue, anyway I closing this for now.
