### ISSUE TITLE
RFC: Migrate from Qt5 to Qt6's Qt5 compat

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#20627]
It seems like migrating to Qt6 is a win for multiple efforts, and I want us to evaluate switching to it as an alternative to monkey-patching Qt5/qmake to make it work properly.

1. First class support for Apple Silicon for #20371 (see: https://bugreports.qt.io/browse/QTBUG-85279)
2. Transition from `qmake` to `cmake` (see: https://www.qt.io/blog/qt-6-build-system)
	1. We already use `cmake` in depends to build several other tools
	2. `cmake` is much better maintained than `qmake`
	3. This might make a native/build split possible for `qt`, the last holdout package of native/build mixing after `boost` was recently split
	4. For PRs like #20600, where we're trying to work around `qmake`'s jankiness, I don't want people to pour their heart and soul into making `qmake` work just to be completely replaced by `cmake` when we bump in the future

Supposedly, the switching cost is also minimal, as there's a Qt5Compat module (see: https://www.qt.io/blog/porting-from-qt-5-to-qt-6-using-qt5compat-library)

**Comment by MarcoFalke** [comment]
How is this going to affect our user? According to the qt blog:

> Qt has always been a cross-platform, and that will continue in Qt 6. Qt 6.0 supports

    Windows 10
    macOS 10.14 and newer
    Linux (Ubuntu 20.04, CentOS 8.1, OpenSuSE 15.1)
    iOS 13 or newer
    Android (API level 23 or newer)


Are these build requirements or runtime requirements?

**Comment by promag** [comment]
Are you suggesting to use Qt6 for depends but still use Qt5 as minimum supported? Or suggesting to bump minimum supported to Qt6?

I don't think Qt5Compat matters that much? We can easily update the code if we are affected by those breaking changes.

I think #20600 is not the way to go, as already discussed with @hebasto, @icota and @BlockMechanic. I'm actually working (I suck at build stuff) on reverting to single archive in qt depends (requires an additional patch for 5.9.8) and simplifies adding qtdeclarative and qtquickcontrols2 modules (remaining modules are skipped ofc) or even qtmultimedia in the future for qrcode scanning.

Also worth mentioning that Qt6 requires C++17, which we already enabled for next version (#20413).

**Comment by BlockMechanic** [comment]
Seems a lot of QT modules are still being adapted/fixed. The earliest estimate for a complete release is stated as 6.2.0 including all submodules. I agree with an eventual move to Qt6, however i think it's still a bit of a ways off. I have a branch that i was adapting to Qt 6.0.0, there are quite a few patches required.

**Comment by dongcarl** [comment]
> How is this going to affect our user?

From my reading, these aren't necessary requirements but are "blessed configurations" which are the most well-tested by their CI and testing. I do agree that we need more testing for the edge cases of our supported configurations though.

> I have a branch that i was adapting to Qt 6.0.0, there are quite a few patches required.

Oh very cool! Please do post on this thread if you ever push it up :-)

**Comment by fanquake** [comment]
I think dropping support for < Windows 10 is too aggressive for us to be building releases with Qt6. We should at least wait and see if there are significant complaints (due to #18956) with the release of 0.21. I'd like to think there are already very few XP / Vista users left, however Windows 7 only stopped receiving security updates at the start of this year.

**Comment by jonasschnelli** [comment]
I guess adding support for Qt6 builds (along with Qt5) is for sure a good thing. The main questions are if we should use Qt6 for depends/releases.
Would it be possible and would it make sense to use Qt6 for macOS and keep Qt5 for the rest?

**Comment by fanquake** [comment]
> The main questions are if we should use Qt6 for depends/releases.

No, not yet. For at least the reason I outlined above. That would also, as far as I can see, drop support for Ubuntu 18.04LTS, which is supported until 2023. It'd also make sense to wait for at least a point release or two before we fully commit to 6.x. I think using 5.15.x for the 22.0 release is the way to move  forward for now.

**Comment by jonasschnelli** [comment]
> No, not yet. For at least the reason I outlined above. That would also, as far as I can see, drop support for Ubuntu 18.04LTS, which is supported until 2023. It'd also make sense to wait for at least a point release or two before we fully commit to 6.x. I think using 5.15.x for the 22.0 release is the way to move forward for now.

I completely agree.
Though for macOS where 10.14 is our minimum (AFAIK), we could bump to Qt6 and also make it better support macOS Big Sur 10.16

**Comment by sipa** [comment]
If it's easy to have source code compatible with both, there wouldn't be much of an issue with using Qt5 in depends for Linux/Windows builds, and Qt6 for MacOS builds (or even just ARM MacOS builds).

**Comment by luke-jr** [comment]
> This might make a native/build split possible for qt

Just a note that it was always *possible* - embedded Qt systems have been doing it for a long time.

**Comment by drewpotter** [comment]
I am not sure how accurate this article is, but it claims that Qt LTS releases will be commercial only. I am not sure if this might be an issue? I just wanted to make people aware of this. Hopefully something positive can come from using Qt moving forwards. I have used Qt for many projects, so it would be a shame if that would be the end.

[The Register: Open-source contributors say they'll pull out of Qt as LTS release goes commercial-only](https://www.theregister.com/2021/01/05/qt_lts_goes_commercial_only/)

**Comment by BlockMechanic** [comment]
This has the potential to be a game changer. They could lose a lot of contributors and users.

**Comment by drewpotter** [comment]
@BlockMechanic there has been some talk online about forking Qt. However, that would be a very serious and time consuming endeavour. Of course it's a real shame if that would be a pathway which the community would have to choose. I am not sure what the best path would be going forwards, but I truly hope that sharing this information will help the Bitcoin community.

**Comment by fanquake** [comment]
One thing to note is that beginning with Qt 6, Qt is also no longer providing pkg-config files: https://bugreports.qt.io/browse/QTBUG-86080.

**Comment by BlockMechanic** [comment]
Checking in, 6.1.0 is out but still no resolution for the pkg-config issue.

**Comment by prusnak** [comment]
Qt 6.2.0 LTS was released https://www.qt.io/blog/qt-6.2-lts-released

**Comment by hebasto** [comment]
> I think using 5.15.x for the 22.0 release is the way to move forward for now.

Agree. See #23489.

**Comment by fanquake** [comment]
Looks like pkg-config support will return as of Qt 6.4.0: https://bugreports.qt.io/browse/QTBUG-86080/

Also note that recently an open source, non-commercial Qt 5.15.3 has been released: https://lists.qt-project.org/pipermail/development/2022-March/042262.html.

**Comment by prusnak** [comment]
> Also note that recently an open source, non-commercial Qt 5.15.3 has been released: https://lists.qt-project.org/pipermail/development/2022-March/042262.html.

PR in https://github.com/bitcoin-core/gui/pull/570

**Comment by hebasto** [comment]
> Looks like pkg-config support will return as of Qt 6.4.0: https://bugreports.qt.io/browse/QTBUG-86080/

Unfortunately, it is [disabled](https://github.com/qt/qtbase/blob/5b07f14a4ff6b08887473b1b583ee2f71dec6f76/cmake/QtPkgConfigHelpers.cmake#L24-L26) for static builds explicitly:
```cpp
    if(NOT BUILD_SHARED_LIBS)
        return()
    endif()
```

**Comment by fanquake** [comment]
Going to close this for now. It's not clear that we'll actually need the compat library, as it seems (non-build)code-wise, we've made all the changes needed to be able to use Qt 6 already. The discussion here has also morphed into more-general updating-qt-talk.

**Comment by hebasto** [comment]
> 2\. Transition from `qmake` to `cmake` (see: https://www.qt.io/blog/qt-6-build-system)

Also #25797.
