### ISSUE TITLE
unable to use connect option with hostname 

### ISSUE THREAD

**Issue by alexmat** [bitcoin/bitcoin#20625]
Using version 0.20.1

I am trying to have my node use the connect= option to connect to another host. If I use a hostname it doesn't attempt to connect (I don't see any attempts to connect on the remote host or the localhost). If I use the IP address of the host, it works as expected. I am able to get the ip on the localhost if I run the dig command, so it seems the hostname is resolving correctly.

**Comment by jadijadi** [comment]
Hi Alex. Have you tried with -dns=1 option? By default it should be 1, but please check in your config file / command line options. If still not working please share the debug.log / output.

**Comment by achow101** [comment]
Closing as this has not had any response in ~2 years.
