### ISSUE TITLE
Can we create a non proof-of-childs documentation to install and run properly this repo?

### ISSUE THREAD

**Issue by Chococoin** [bitcoin/bitcoin#20636]
I have tried several times to install and run this repo in a fresh ubuntu 20.04 operative system. 

All the documentation I have found is outdated. And there is not an evident clear path to successfully install this repo in at least an OS. 

I would like to suggest if possible, an exhaustive doc that explains how to install this repo in any Linux distribution.

**Comment by MarcoFalke** [comment]
`snap install bitcoin-core`

Alternatively, you can self-compile (`./doc/build-unix.md`) or use the flatpak https://flathub.org/apps/details/org.bitcoincore.bitcoin-qt
