### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Aisakk** [bitcoin/bitcoin#20645]
hello guys, I start with bitcoin, and I run in my terminal the code bitcoind then started compiling o start, and I don't know, what happed?, because my terminal have 1 hour or more in this. I'm would like to know, what is this and how much hour i have to waiting?. Because I would like work in my app, but is my first time with bitcoin. 
![image](https://user-images.githubusercontent.com/43797095/102025548-18b34c80-3d6f-11eb-8704-269114e91019.png)

**Comment by sipa** [comment]
Hours or days, depending on your hardware. Increasing the database cache size improves performance (see the -dbcache command line option, or dbcache= config file option).

The issue tracker isn't for support questions, though. Next time, please use https://bitcoin.stackexchange.org or other forums.
