### ISSUE TITLE
Advertised address where nobody is listening

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#20657]
Bug reported by @vasild here: (https://github.com/bitcoin-core/gui/pull/86#issuecomment-717789400)

`listen=0` will cause us not to listen on any port, so we would not accept any incoming connections, regardless of whether clearnet or Tor.

> $ bitcoind
...
2020-10-28T08:41:57Z Config file arg: listen="0"
2020-10-28T08:41:57Z Config file arg: listenonion="1"
2020-10-28T08:41:57Z Config file arg: rpcport="8332"
...
2020-10-28T08:42:19Z tor: Got service ID foo, advertising service foo.onion:8333
2020-10-28T08:42:19Z AddLocal(foo.onion:8333,4)

>$ netstat
tcp4       0      0 127.0.0.1.8332         *.*                    LISTEN     
(bitcoind is only listening on the RPC port)

> I guess this can be considered as a bug because it will (I guess) advertise `foo.onion:8333` where nobody is listening.

**Comment by vasild** [comment]
Should we automatically set `listenonion` to `0` if `listen` is set to `0`?

**Comment by jadijadi** [comment]
Hi guys, Sent this PR for this: https://github.com/bitcoin/bitcoin/pull/20769

**Comment by Rspigler** [comment]
Makes sense to me, as this was the assumed behavior
