### ISSUE TITLE
COMPACT_FILTERS should only be signalled when filter is in sync

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#20659]
I haven't tested this in detail but observed the following:
* peer is in sync (blockfilters disabled)
* stop peer
* start peer with `-blockfilters=1 -peerblockfilters`
* peer immediately sets service flag `COMPACT_FILTERS`
* filter has just started to sync

Probably not very crucial because AFAIK in case we get a `NetMsgType::GETCFILTERS` while not having the filter ready, we just don't response.

**Comment by ysangkok** [comment]
According to [PR 19070](https://github.com/bitcoin/bitcoin/pull/19070#issuecomment-634142901) it seems this was done on purpose. So is it really a bug?

**Comment by prusnak** [comment]
@jonasschnelli @jnewbery can you please comment on what is the intended behaviour?

**Comment by jnewbery** [comment]
Yes, this was done on purpose, as discussed in #19070 and other places.
