### ISSUE TITLE
contrib/install_db4.sh fetching a patch from gist.githubusercontent.com

### ISSUE THREAD

**Issue by alevchuk** [bitcoin/bitcoin#20722]
Berkeley DB installer in contrib makes a call over the internet to https://gist.githubusercontent.com to fetch a 141 line patch.

https://github.com/bitcoin/bitcoin/blob/f1dbf92ff0475a01d20170ea422c1d086acbbc57/contrib/install_db4.sh#L71

The gist has [multiple revisions](
https://gist.github.com/LnL7/5153b251fd525fe15de69b67e63a6075/revisions)

**Expected behavior**

One less call over the internet during the build process. One less website to depend on.

**To reproduce**

```
 ./contrib/install_db4.sh 
```

`install_db4.sh` is recommended by the `doc/build-*.md` for example https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#berkeley-db 

CC: @laanwj

**Comment by MarcoFalke** [comment]
#20665

**Comment by alevchuk** [comment]
dupliacte

**Comment by alevchuk** [comment]
Never-mind, #20665 isn't actually getting rid of the dependency.

**Comment by laanwj** [comment]
Yes I think #20665 would be better if it looked for the local patch.

That said, I'm not convinced that this is an actual issue. It *is* a download script after all and an additional, verified download won't make it noticeably slower or less efficient.

**Comment by alevchuk** [comment]
Any security concerns / what are implications if gist.githubusercontent.com compromised?

**Comment by laanwj** [comment]
> Any security concerns / what are implications if gist.githubusercontent.com compromised?

It would give an error as it validates the hash.
