### ISSUE TITLE
Forced shutdown on container stop

### ISSUE THREAD

**Issue by MazziaRick** [bitcoin/bitcoin#20732]
I'm experimenting an issue by running bitcoind inside a Docker container on Linux.

It appears that the only kernel signal allowing a gentle shutdown of the bitcoind daemon is a SIGINT, but docker engine send a SIGTERM to the main process running in the container after performing the "docker stop" command. Actually this docker behavior could not be changed at my knowledge.

The end result is that after the docker timer expires the bitcoind daemon is abruptly shut down by docker engine without a proper mempool dump and cache flush to disk. During next start, an inconsistent state of data on disk force a re-synchronization of the lost blocks.

Please is it possible to add a SIGTERM handler to initiate the daemon shutdown procedure ?

Thank you!

Kind Regards,
Riccardo

**Comment by jonatack** [comment]
Hi @MazziaRick, what version of bitcoind did you run?

**Comment by MazziaRick** [comment]
0.20.1 armfh

**Comment by MazziaRick** [comment]
I actually manually sent a SIGTERM signal with kill and it works, even in the source code I actually found the SIGTERM handler.. I just don't get why it doesn't wotk with "docker stop"...

**Comment by sipa** [comment]
SIGINT and SIGTERM are handled exactly the same way.

Is it possible this is due to shutdown taking too long, and docker forcibly killing it after some delay? That would also explain the replay on startup - if no signal was sent at all, and flushing wasn't started, the state wouldn't be inconsistent.

**Comment by MazziaRick** [comment]
Yep, this is not a bitcoind issue, sorry for writing here and thank you so much.
