### ISSUE TITLE
watch-only getwalletinfo returns some incorrect values (although the fields are deprecated)

### ISSUE THREAD

**Issue by mjdietzx** [bitcoin/bitcoin#20743]
I saw some unexpected behavior when testing for v0.21.0 release: https://github.com/bitcoin/bitcoin/issues/20555#issuecomment-749189264

After looking into it more:
  - confirmed that `getwalletinfo` returns items: `balance`, `unconfirmed_balance`, and `immature_balance` are always 0 for watch-only wallets (confirmed with a failing unit test) 
  - noticed that these fields had been deprecated in this commit https://github.com/bitcoin/bitcoin/commit/facfb4111d14a3b06c46690a2cca7ca91cea8a96

Is there anything we need to do here?
 - totally remove these fields from rpc response since they've been deprecate since v0.19.0
 - exclude fields unless a deprecated flag is passed
 - fix
 - do nothing since it's deprecated?

**Comment by sipa** [comment]
I think this is expected. They're reporting spendable balance, not watch-only balance.

**Comment by mjdietzx** [comment]
Ah yeah, only unexpected to me I guess.

I see that these fields are `Identical to getbalances().mine` in the `RPCHelpMan`. And that's the case for my watch-only wallet. `getbalances.mine` are all 0, and `getbalances.watchonly` are all the correct values ✅

Is there anything we should do with these deprecated fields? Or do we just leave as-is (and I'll close this issue)?

**Comment by jonatack** [comment]
See the discussion in #18451

**Comment by MarcoFalke** [comment]
The response is correct (`0`) according to the documentation: https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/getwalletinfo/

I don't think this is a bug.
