### ISSUE TITLE
gui: file>create wallet dialog is unreadable

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#20777]
Version v0.21.0rc3, built from source, on Linux, Debian 10. XFCE4, xfwm4.

Clicking file>create wallet shows me this:

![Screenshot_2020-12-26_10-51-09](https://user-images.githubusercontent.com/573356/103157972-ab8bb800-476d-11eb-99d1-1f84279fe6c8.png)

I increase the window size hoping it will fit better but it doesn't rearrange itself like the other windows do:

![Screenshot_2020-12-26_10-51-24](https://user-images.githubusercontent.com/573356/103157978-be05f180-476d-11eb-886f-85878193a03d.png)

It's probably happening because I've changed my fonts and display DPI settings but shouldn't the client adjust its layout to take that into account? All the other windows seem to.

**Comment by MarcoFalke** [comment]
Fixed in #20669

**Comment by dooglus** [comment]
I built the code in that pull request. It does show me more of the hidden text but not all of it:

![Screenshot_2020-12-30_21-22-35](https://user-images.githubusercontent.com/573356/103395887-3c072700-4ae5-11eb-86c9-0cb949b88a0b.png)

**Comment by hebasto** [comment]
@dooglus 

Mind testing https://github.com/bitcoin-core/gui/pull/171?

**Comment by dooglus** [comment]
Looks great now:

![Screenshot_2021-01-01_14-05-35](https://user-images.githubusercontent.com/573356/103447010-851cbf80-4c3a-11eb-94eb-0eb8c05f5e94.png)

When I resize the window it redraws like this:

![Screenshot_2021-01-01_14-05-52](https://user-images.githubusercontent.com/573356/103447015-906feb00-4c3a-11eb-818f-c00afb4e2777.png)

Since you appear to know your way around the layout engine maybe you'd also be interested in #20826 which I just opened.

**Comment by hebasto** [comment]
@dooglus 
> Looks great now

May I ask you to leave your comment in https://github.com/bitcoin-core/gui/pull/171?

**Comment by dooglus** [comment]
Sure.
