### ISSUE TITLE
When increase transaction fee three times in few minutes - transaction had an attempted double-spent?

### ISSUE THREAD

**Issue by jopeto2000** [bitcoin/bitcoin#20780]
I make transaction from my wallet - send BTC. 
After I send BTC, I increase transaction fee three times, in a few minutes. After this in block explorer I see that this transaction had an attempted double-spent. 
I use Bitcoin Core version v0.18.1 (64-bit)

What can do in my case?
Thanks in advance.

**Comment by tylerchambers** [comment]
It could just be the block explorer presenting a misleading message. Increasing transaction fee is not a double spend, but it could be misinterpreted by the block explorer as such.

**Comment by 0xB10C** [comment]
Which block explorer do you use? What is the exact message? I agree with @tylerchambers, this is very likely unrelated to Bitcoin Core. It's an issue on the block explorer side. For example, blockchain.com, shows this message for transactions that have been replaced:
>  Transaction invalid: some outputs that it attempts to spend have been already spent or are no longer valid.

Example: [ce0e69d9e38192663c70a01ef54450f15187d610ffab4eed8a74e1537505cab0](https://www.blockchain.com/btc/tx/ce0e69d9e38192663c70a01ef54450f15187d610ffab4eed8a74e1537505cab0)

**Comment by adamjonas** [comment]
This appears to be a third-party block explorer issue and not addressable by Bitcoin Core. Closing.
