### ISSUE TITLE
Can I make readme.md and other introduction files in another language?

### ISSUE THREAD

**Issue by programmer1017** [bitcoin/bitcoin#20793]
**Is your feature request related to a problem? Please describe.**

I think I can add the another version of readme.md and other introduction to Bitcoin files in another language. I think this can improve the accessibility of this project.
<br>
**Describe the solution you'd like**

I'll translate the documents, then other people can help

**etc.**
I'm Korean, so I'll translate this documents in Korean.

**Comment by jarolrod** [comment]
This sounds like a good idea. If this is to be done it should be done as a coordinated effort to include translations in other languages as well. One issue will be maintainability as documentation changes. I suppose one thing to ease that could be to include the docs on Transifex.

**Comment by jinCN** [comment]
I'd like to help.

> This sounds like a good idea. If this is to be done it should be done as a coordinated effort to include translations in other languages as well. One issue will be maintainability as documentation changes. I suppose one thing to ease that could be to include the docs on Transifex.

So what's the plan? How about adding README.xx.md besides README.md and doc_xx besides doc, with the help of Transifex?

**Comment by programmer1017** [comment]
Excuse me, how can I use Transifex? I have never used Transifex

**Comment by MrMebelMan** [comment]
> Excuse me, how can I use Transifex? I have never used Transifex

https://docs.transifex.com/getting-started-1/translators

Btw, I'm down to help with Russian and Ukrainian translations!

**Comment by MrMebelMan** [comment]
I guess this is the right team? https://www.transifex.com/bitcoin/bitcoin/

**Comment by programmer1017** [comment]
Yep I guess this is the right team

**Comment by programmer1017** [comment]
.... for translating bitcoin homepage. But we're just trying to translate readme.md on thie repo
