### ISSUE TITLE
Better errors for address use from wrong network

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#20809]
I spent too long to figure out I was putting mainnet addresses to regtest node, errors weren't helpful at `getaddressinfo` and `validateaddress`.

Seems like a good first issue to augment the error messages when prefix/hrp don't match current network.

**Comment by instagibbs** [comment]
hmm, not a bug, feature request.

**Comment by MarcoFalke** [comment]
#### Useful skills:

* Bitcoin Core RPC interface and tests
* bech32

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by michaelfolkson** [comment]
This may be useful for whoever picks this up. https://bitcoin.stackexchange.com/questions/100508/can-you-break-down-what-data-is-encoded-into-a-bech32-address

For all addresses (including pre bech32) or just bech32?

**Comment by prayank23** [comment]
<pre>
getaddressinfo "bc1qjjrlgl28uqjtv0at2n3pfv3qtuvrm85vr0am5v"

Invalid address (code -5)
</pre>

<pre>
validateaddress "bc1qjjrlgl28uqjtv0at2n3pfv3qtuvrm85vr0am5v"

{
  "isvalid": false
}
</pre>

@instagibbs I get these results for a 'mainnet' address used on testnet. What would you like to see in the new error messages? Address type mentioned in error based on prefix/hrp?

**Comment by instagibbs** [comment]
Yeah ideally the message would have appended the detail "wrong network" or
something like that.

**Comment by eilx2** [comment]
Hello! I would be interested in working on this feature as it seems a good way for a first contribution. I've already managed to add an additional property called "error_msg" inside "validateaddress" in case the address is not valid and set it when the address is invalid.

As for testing, I suppose I should add a functional test for this feature am I right?

**Comment by instagibbs** [comment]
@eilx2 Yes, check for `assert_raises_rpc_error` in the functional suite for inspiration on how to check these string returns.

**Comment by instagibbs** [comment]
When you open the PR feel free to tag me :+1:

**Comment by jarolrod** [comment]
This has been fixed by https://github.com/bitcoin/bitcoin/pull/20832 and can be closed.
