### ISSUE TITLE
Failed to start bitcoin daemon using Ubuntu 20.04

### ISSUE THREAD

**Issue by blainerb4** [bitcoin/bitcoin#20818]
Hey I keep getting this error everytime I run sudo systemctl enable --now bitcoind

Job for bitcoind.service failed because the control process exited with error code. See "systemctl status bitcoind.service" and "journalctl -xe" for details.

When I input sudo journalctl -xe --unit bitcoind I get this. bitcoind.service - Bitcoin daemon Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor pres> Active: failed (Result: exit-code) since Wed 2020-12-30 15:12:05 UTC; 23s > Process: 2411 ExecStartPre=/bin/chgrp admin /etc/bitcoin (code=exited, stat>

Here is how my bitcoind.service looks. I changed the user and group from bitcoin to admin. [Unit] Description=Bitcoin daemon After=network.target

[Service] ExecStart=/usr/bin/bitcoind -daemon
-pid=/run/bitcoind/bitcoind.pid
-conf=/etc/bitcoin/bitcoin.conf
-datadir=/var/lib/bitcoind

Make sure the config directory is readable by the service user
PermissionsStartOnly=true ExecStartPre=/bin/chgrp admin /etc/bitcoin

Process management
####################

Type=forking PIDFile=/run/bitcoind/bitcoind.pid Restart=on-failure TimeoutStopSec=600

Run as admin:admin
User=admin Group=admin

/run/bitcoind
RuntimeDirectory=bitcoind RuntimeDirectoryMode=0710

/etc/bitcoin
ConfigurationDirectory=bitcoin ConfigurationDirectoryMode=0710

/var/lib/bitcoind
StateDirectory=bitcoind StateDirectoryMode=0710

Hardening measures
####################

Provide a private /tmp and /var/tmp.
PrivateTmp=true

Deny access to /home, /root and /run/user
ProtectHome=true

Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

Disallow the process and all of its children to gain
new privileges through execve().
NoNewPrivileges=true

Use a new /dev namespace only populated with API pseudo devices
such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

[Install] WantedBy=multi-user.target

Here are the steps I made before: ~$ cd src ~/src$ git clone --depth 1 --branch v0.20.1 https://github.com/bitcoin/bitcoin.git ~/src$ cd bitcoin ~/src/bitcoin$ ./contrib/install_db4.sh pwd ~/src/bitcoin$ ./autogen.sh ~/src/bitcoin$ export BDB_PREFIX='/home/ubuntu/src/bitcoin/db4' ~/src/bitcoin$ ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" ~/src/bitcoin$ make ~/src/bitcoin$ sudo make install ~/src/bitcoin$ bitcoind -version vi bitcoin.conf server=1
rpcbind=127.0.0.1
whitelist=127.0.0.1
rpcallowip=127.0.0.1/32
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

~$ sudo mkdir -p /etc/bitcoin ~$ sudo cp bitcoin.conf /etc/bitcoin ~$ sudo chmod 644 /etc/bitcoin/bitcoin.conf

Utimately I got ubuntu systemd[1]: Failed to start Bitcoin daemon

**Comment by hebasto** [comment]
> Here is how my bitcoind.service looks. I changed the user and group from bitcoin to admin. [Unit] Description=Bitcoin daemon After=network.target
> 
> [Service] ExecStart=/usr/bin/bitcoind -daemon
> -pid=/run/bitcoind/bitcoind.pid
> -conf=/etc/bitcoin/bitcoin.conf
> -datadir=/var/lib/bitcoind
> 
> Make sure the config directory is readable by the service user
> PermissionsStartOnly=true ExecStartPre=/bin/chgrp admin /etc/bitcoin
> 
> Process management
> ####################
> 
> Type=forking PIDFile=/run/bitcoind/bitcoind.pid Restart=on-failure TimeoutStopSec=600
> 
> Run as admin:admin
> User=admin Group=admin
> 
> /run/bitcoind
> RuntimeDirectory=bitcoind RuntimeDirectoryMode=0710
> 
> /etc/bitcoin
> ConfigurationDirectory=bitcoin ConfigurationDirectoryMode=0710
> 
> /var/lib/bitcoind
> StateDirectory=bitcoind StateDirectoryMode=0710
> 
> Hardening measures
> ####################
> 
> Provide a private /tmp and /var/tmp.
> PrivateTmp=true
> 
> Deny access to /home, /root and /run/user
> ProtectHome=true
> 
> Mount /usr, /boot/ and /etc read-only for the process.
> ProtectSystem=full
> 
> Disallow the process and all of its children to gain
> new privileges through execve().
> NoNewPrivileges=true
> 
> Use a new /dev namespace only populated with API pseudo devices
> such as /dev/null, /dev/zero and /dev/random.
> PrivateDevices=true
> 
> Deny the creation of writable and executable memory mappings.
> MemoryDenyWriteExecute=true
> 
> [Install] WantedBy=multi-user.target

It looks like your `bitcoind.service` is broken a bit. Compare:
> Hardening measures
> ####################
> 
> Provide a private /tmp and /var/tmp.
> PrivateTmp=true

vs

https://github.com/bitcoin/bitcoin/blob/ae8f79713543d3db24a886cc27340b1570c2657d/contrib/init/bitcoind.service#L53-L57

**Comment by blainerb4** [comment]
I am still getting this error, I'm not sure why the formatting went wrong when I posted this:
 # Hardening measures 
 #################

 bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor pres>
     Active: failed (Result: exit-code) since Sat 2021-01-02 17:40:44 UTC; 8s a>
    Process: 2503 ExecStartPre=/bin/chgrp bitcoin /etc/bitcoin (code=exited, st>

**Comment by hebasto** [comment]
From your OP follows that this command
```
ExecStartPre=/bin/chgrp admin /etc/bitcoin
```
fails.

What is its output if you run it in your terminal manually?

---

To place apiece of code in the comment embrace it with two strings (before and after) each of them contains only three back quotes, i.e., ```

**Comment by blainerb4** [comment]
When I ran:
$ sudo /bin/chgrp admin /etc/bitcoin
I received the same error

**Comment by hebasto** [comment]
> When I ran:
> $ sudo /bin/chgrp admin /etc/bitcoin
> I received the same error

Maybe I missed it. Could you post the error message after `sudo /bin/chgrp admin /etc/bitcoin` command from terminal here again?

**Comment by blainerb4** [comment]
When I ran:
$ sudo /bin/chgrp admin /etc/bitcoin
nothing happened and I received the error 

Job for bitcoind.service failed because the control process exited with error code.
See "systemctl status bitcoind.service" and "journalctl -xe" for details.
after running
sudo systemctl enable --now bitcoind

Produced this error
● bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor pres>
     Active: failed (Result: exit-code) since Sat 2021-01-02 20:15:34 UTC; 38s >
    Process: 3405 ExecStartPre=/bin/chgrp bitcoin /etc/bitcoin (code=exited, st>

Jan 02 20:15:34 ubuntu systemd[1]: bitcoind.service: Scheduled restart job, res>
Jan 02 20:15:34 ubuntu systemd[1]: Stopped Bitcoin daemon.
Jan 02 20:15:34 ubuntu systemd[1]: bitcoind.service: Start request repeated too>
Jan 02 20:15:34 ubuntu systemd[1]: bitcoind.service: Failed with result 'exit-c>
Jan 02 20:15:34 ubuntu systemd[1]: Failed to start Bitcoin daemon.

I am also running my node on a raspberry pi 4 using the ubuntu 20.04 operating system. I have ruled out that is is a memory issue as well as I have a 1Tb SSD card connected.

**Comment by jarolrod** [comment]
@blainerb4 Is this still a problem for you? I cannot replicate on an Ubuntu 20.04 VM

**Comment by fyoudumas** [comment]
@blainerb4 Did you ever figure this out?  I am having the exact same issue.

**Comment by crabel99** [comment]
try the following:
```bash
journalctl -xr
```
This will reverse order the jouirnal, you then scroll down to get to the earlier events with the arrow keys. Because `systemctl` will attempt 5 restarts you may need to hit the space bar a few times to get to the first one, use the up/down arrows for fine control, like reading a `man` page. There look to see where the process is hanging.

Here is the default `bitcoind.service` I compiled from source `v0.21.0` and then upgraded to `v0.21.1` I've had no issues with this as its been running continuously on ubuntu server 20.04 since March.
```systemctl
# /lib/systemd/system/bitcoind.service
# It is not recommended to modify this file in-place, because it will
# be overwritten during package upgrades. If you want to add further
# options or overwrite existing ones then use
# $ systemctl edit bitcoind.service
# See "man systemd.service" for details.

# Note that almost all daemon options could be specified in
# /etc/bitcoin/bitcoin.conf, but keep in mind those explicitly
# specified as arguments in ExecStart= will override those in the
# config file.

[Unit]
Description=Bitcoin daemon
After=network.target

[Service]
ExecStart=/usr/local/bin/bitcoind -daemon \
                            -pid=/run/bitcoind/bitcoind.pid \
                            -conf=/etc/bitcoin/bitcoin.conf \
                            -datadir=/var/lib/bitcoind

# Make sure the config directory is readable by the service user
PermissionsStartOnly=true
ExecStartPre=/bin/chgrp bitcoin /etc/bitcoin

# Process management
####################

Type=forking
PIDFile=/run/bitcoind/bitcoind.pid
Restart=on-failure
TimeoutStopSec=600

# Directory creation and permissions
####################################

# Run as bitcoin:bitcoin
User=bitcoin
Group=bitcoin

# /run/bitcoind
RuntimeDirectory=bitcoind
RuntimeDirectoryMode=0710

# /etc/bitcoin
ConfigurationDirectory=bitcoin
ConfigurationDirectoryMode=0710

# /var/lib/bitcoind
StateDirectory=bitcoind
StateDirectoryMode=0710

# Hardening measures
####################

# Provide a private /tmp and /var/tmp.
PrivateTmp=true

# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

# Deny access to /home, /root and /run/user
ProtectHome=true

# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true

# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

# Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
```

**Comment by willcl-ark** [comment]
My intuition here is that @blainerb4 did not have a user called `admin` configured on their system (I'm not familiar with one of that name on stock Ubuntu, and it seems an odd one to create when you already have `root`), which caused the `sudo /bin/chgrp admin /etc/bitcoin` command to fail both inside their systemd unit file and on the command line.

The current unit file is working so long as a user `bitcoin` exists, and changing the user can be done pretty easily AFAICT, e.g. On Ubuntu 22.10 I can run as user `will` with the following patch to the contrib service file (provided that `/etc/bitcoin/bitcoin.conf` exists):

```diff
diff --git a/usr/lib/systemd/system/bitcoind.service b/home/will/src/bitcoin/contrib/init/bitcoind.service
index 2ad589b..93de353 100644
--- a/usr/lib/systemd/system/bitcoind.service
+++ b/home/will/src/bitcoin/contrib/init/bitcoind.service
@@ -25,7 +25,7 @@ ExecStart=/usr/bin/bitcoind -daemonwait \

 # Make sure the config directory is readable by the service user
 PermissionsStartOnly=true
-ExecStartPre=/bin/chgrp will /etc/bitcoin
+ExecStartPre=/bin/chgrp bitcoin /etc/bitcoin

 # Process management
 ####################
@@ -39,9 +39,9 @@ TimeoutStopSec=600
 # Directory creation and permissions
 ####################################

-# Run as will:will
-User=will
-Group=will
+# Run as bitcoin:bitcoin
+User=bitcoin
+Group=bitcoin

 # /run/bitcoind
 RuntimeDirectory=bitcoind

```

Unless there is more to go on, o rother reports, I think this could be closed?
