### ISSUE TITLE
GUI: recent transaction timestamps overlap amounts when watchonly addresses are in wallet

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#20826]
Version v0.21.0rc3, built from source, on Linux, Debian 10. XFCE4, xfwm4.

I've been noticing a layout issue with the main Window's "Overview" tab:

If the wallet has any "watch only" addresses in it then the "Overview" tab shows two columns of balances ("Spendable" and "Watch-only") and that seems to mess up the layout such that in the "Recent transactions" panel to the right of the balances each entry's timestamp overlaps its BTC amount when I shrink the window to its minimum width.

Here's a wallet without any watchonly addresses - it looks fine:

![Screenshot_2021-01-01_14-17-49](https://user-images.githubusercontent.com/573356/103447181-9ebf0680-4c3c-11eb-964f-492da3d6dfd3.png)

Then I run `bitcoin-cli importaddress 1BitcoinEaterAddressDontSendf59kuE eater false` and things turn ugly immediately - the date of the transaction is overlapping the amount of BTC in the transaction:

![Screenshot_2021-01-01_14-19-16](https://user-images.githubusercontent.com/573356/103447191-b26a6d00-4c3c-11eb-9d53-0ec6132cc0c2.png)

Restarting the client doesn't help. It seems the minimum width of the window isn't adjusted when its contents get wider.

**Comment by hebasto** [comment]
Mind reopening this issue in the https://github.com/bitcoin-core/gui repo (with closing here)?

**Comment by hebasto** [comment]
Fixed in https://github.com/bitcoin-core/gui/pull/176.

@dooglus Mind testing it?

**Comment by dooglus** [comment]
Did I open this in the wrong repository? I thought we used bitcoin/bitcoin for all bitcoin core issues. Did that change?

I'll test your change tomorrow. Thanks for it.

**Comment by hebasto** [comment]
> Did I open this in the wrong repository? I thought we used bitcoin/bitcoin for all bitcoin core issues. Did that change?

#19071

> I'll test your change tomorrow.

Thanks!

**Comment by dooglus** [comment]
I hadn't seen #19071. That makes sense now. :)

Your fix works for me - I replied in bitcoin-core/gui#176.

**Comment by fanquake** [comment]
Going to close this given discussion has now moved to the GUI repo (https://github.com/bitcoin-core/gui/pull/176).
