### ISSUE TITLE
Hello! I would be interested in working on this feature as it seems a good way for a first contribution. I've already managed to add an additional property called "error_msg" inside "validateaddress" in case the address is not valid and set it when the address is invalid.

### ISSUE THREAD

**Issue by FeliciaXmL** [bitcoin/bitcoin#20821]
Hello! I would be interested in working on this feature as it seems a good way for a first contribution. I've already managed to add an additional property called "error_msg" inside "validateaddress" in case the address is not valid and set it when the address is invalid.

As for testing, I suppose I should add a functional test for this feature am I right?

_Originally posted by @eilx2 in https://github.com/bitcoin/bitcoin/issues/20809#issuecomment-753246046_

**Comment by Saibato** [comment]
This is Bitcoin, no one ask or waits for permission, just dolt and hope to get some ACK's

https://github.com/Saibato/bitcoin/blob/master/doc/developer-notes.md

hope that helps. :woman_astronaut:
