### ISSUE TITLE
Cannot generate change address on descriptor wallets.

### ISSUE THREAD

**Issue by willweatherman** [bitcoin/bitcoin#20831]
I am trying to create an unsigned transaction in a wallet that contains a 3 of 7 public key descriptor.

**Expected behavior**

To be able to send half a UTXO and bitcoin core to handle the change address generation

**Actual behavior**

Instead, I get this error on clicking "create unsigned". "Transaction needs a change address, but we can't generate it. Please call keypoolrefill first."

**To reproduce**

*To create descriptor*
1. Create a standard wallet using bitcoin core 
2. Run "getnewaddress" to generate an address
3. Run "dumpprivkey" using the address previously generated to get a WIF key
4. XOR the WIF key with 256 "1"s to create a unique key(not to add security or randomness)
4. Create a new standard wallet and run "sethdseed" with the modified WIF key
5. Dump the second wallet to get the xpriv 
6. Repeat steps 2-5 to generate 7 xprivs
7. Using the xprivs create the 3 of 7 descriptor example below
wsh(multi(3,'xpriv1'/*,'xpriv2'/*,'xpriv3'/*,'xpriv4'/*,'xpriv5'/*,'xpriv6'/*,'xpriv7'/*))
Remove ' from the above string.
8. In the first wallet Run "getdescriptorinfo" to both generate the checksum for the xpriv descriptor and the xpub descriptor itself

*To reproduce error*
1. Create a descriptor wallet with disabled private keys
2. Import the public key descriptor with "importdescriptors" example bellow
importdescriptors '[{ "desc":"wsh(multi(3,'xpriv1'/*,'xpriv2'/*,'xpriv3'/*,'xpriv4'/*,'xpriv5'/*,'xpriv6'/*,'xpriv7'/*))#'checksum'", "timestamp": "now", "active": true}]'
Remove ' from the above string.
3. Click "Create new receiving address" in the bitcoin core UI
4. Send a small amount to the address
5. In the Send tab enter a recipient and then attempt to send half of the original amount sent to the address.
6. You should get an error "Transaction needs a change address, but we can't generate it. Please call keypoolrefill first."

**System info**
I am using ubuntu 20 with bitcoin core 0.21.0 rc3

**Comment by achow101** [comment]
You have only imported a descriptor for receiving address use. You must import another one for change address use. Otherwise there is no way for the wallet to generate change addresses.

**Comment by willweatherman** [comment]
How would you specify which one is for generating change addresses?

**Comment by achow101** [comment]
Include `"internal": true` in your import to specify that that descriptor is for change addresses only.

**Comment by willweatherman** [comment]
Awesome, that works thanks.

**Comment by willweatherman** [comment]
Hi, I noticed that by running this command to allow the creation of receiving addresses.
importdescriptors '[{ "desc": "wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/*,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/*,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/*,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/*,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/*,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/*,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/*))#9hky7ctt", "timestamp": "now", "active": true}]'

And then running this command to allow bitcoin core to generate change addresses from the same descriptor.
importdescriptors '[{ "desc": "wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/*,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/*,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/*,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/*,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/*,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/*,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/*))#9hky7ctt", "timestamp": "now", "active": true, "internal": true}]'

It will override the first command and disable the creation of external addresses. The whole point of having a descriptor wallet is a single descriptor that will handle everything as if it were an actual wallet. Is this a bug or was it done on purpose?

Thanks-
Will.

**Comment by achow101** [comment]
> The whole point of having a descriptor wallet is a single descriptor that will handle everything as if it were an actual wallet

No. The whole point of descriptor wallets is to have a descriptors handle everything in a wallet.

A single descriptor cannot be used for both receiving and change addresses. This is intentional.

**Comment by willweatherman** [comment]
Ok, thank you.
