### ISSUE TITLE
Libboost Dependency Pathing Issues with Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by AmateurPirate** [bitcoin/bitcoin#20841]
Ubuntu 20.04LTS

I already resolved this on my system, but want to share to prevent headaches in other devs.

`configure: error: Could not find a version of the boost_program_options library!`

Following the instructions in https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md got me stuck on this error. I resolved it by running `sudo apt-get autoremove libboost1.71-dev:amd64`, `sudo apt-get install libboost-all-dev` and then running configure with `./configure --disable-wallet --with-gui=no --with-boost-libdir=/usr/lib/x86_64-linux-gnu`

I couldn't get it to work with different installations of libboost or with any of the other flags for configure.

**Comment by fanquake** [comment]
Master (and 0.21) no longer use Boost Program Options, (I'm assuming that's what you're building given you've linked to the master branch) so I'm not sure why you would have run into that issue. If you're building a different branch, you should be referring to the build instructions for that branch, which will list all the required dependencies (including program options when it was required).
