### ISSUE TITLE
make check failure

### ISSUE THREAD

**Issue by pietdm** [bitcoin/bitcoin#20869]
I'm trying to set up the Bitcoin Core v20.1.
I'm using VM Workstation 16 with Ubuntu. I succeeded to configure en compile (make), but when I run "make check", I get an error regarding qt.

Anybody any idea on the cause of this. Could it be because I'm working on a virtual machine?

I started from a 'clean' Ubuntu install and used following commands:

sudo apt update
sudo apt upgrade
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git

git clone https://github.com/bitcoin/bitoin.git
cd bitcoin
git tag
git checkout v0.20.1
git status
sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
sudo apt-get install libevent-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev
sudo apt-get install libzmq3-dev
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools
sudo apt-get install libqrencode-dev
sudo apt-get install libdb++-dev
./contrib/install_db4.sh `pwd`
sudo apt-get install libminiupnpc-dev
./autogen.sh
export BDB_PREFIX='/home/piet/bitcoin/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"

make

make check

This is the log-file:
=============================================
   Bitcoin Core 0.20.1: src/test-suite.log
=============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

********* Start testing of AppTests *********
Config: Using QtTest library 5.12.8, Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
PASS   : AppTests::initTestCase()
QINFO  : AppTests::appTests() Backing up GUI settings to "/tmp/test_common_Bitcoin Core/6b5c2d36bbca46789414818445a899d44fd0055650b15350609fab539033a540/regtest/guisettings.ini.bak"
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QWARN  : AppTests::appTests() QFont::setPointSizeF: Point size <= 0 (-1.000000), must be greater than 0
QDEBUG : AppTests::appTests() requestInitialize : Requesting initialize
QDEBUG : AppTests::appTests() initialize : Running initialization in thread

=== Received signal at function time: 333ms, total time: 334ms, dumping stack ===
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 30936
(gdb) === End of stack trace ===
QFATAL : AppTests::appTests() Received signal 11
         Function time: 333ms Total time: 334ms
FAIL!  : AppTests::appTests() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 511ms

**Comment by hebasto** [comment]
> Could it be because I'm working on a virtual machine?

Yes, it could.

Try to run
```
$ QT_QPA_PLATFORM=xcb src/qt/test/test_bitcoin-qt
```

**Comment by pietdm** [comment]
I tried it and also received an error:

********* Start testing of AppTests *********
Config: Using QtTest library 5.12.8, Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
PASS   : AppTests::initTestCase()
QINFO  : AppTests::appTests() Backing up GUI settings to "/tmp/test_common_Bitcoin Core/3ced76e058c28a0fa0ddd48de2ccb9029a5c75d5265f2f5526c00e7e4cbf5a9d/regtest/guisettings.ini.bak"
QDEBUG : AppTests::appTests() requestInitialize : Requesting initialize
QDEBUG : AppTests::appTests() initialize : Running initialization in thread

=== Received signal at function time: 804ms, total time: 805ms, dumping stack ===
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 2477
(gdb) === End of stack trace ===
QFATAL : AppTests::appTests() Received signal 11
         Function time: 804ms Total time: 805ms
FAIL!  : AppTests::appTests() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 1314ms
********* Finished testing of AppTests *********
Aborted (core dumped)

**Comment by hebasto** [comment]
@pietdm IIUC, you have gdb attached. What if to run test without an attached debugger?

**Comment by hebasto** [comment]
FWIW, tested on VirtualBox 6.1.16 r140961 (Qt5.12.8) + Ubuntu 20.04.1 LTS image (Qt 5.12.8): v0.20.1 (and master) passed all checks.

**Comment by pietdm** [comment]
I did the exact same install sequence on VirtualBox, and it works like a charm. Don't know what the exact problem was on VM Workstation.
Thanks for the support! I will continue on this platform now.

**Comment by hebasto** [comment]
Having a clear installation of Linux Mint 20.1 (x86, Qt 5.12.8) on metal hw (not virtualized):
```
$ git rev-parse HEAD
7f653c3b22f0a5267822eec017aea6a16752c597
```
compiled with clang, and
```
$ src/qt/test/test_bitcoin-qt 
********* Start testing of AppTests *********
Config: Using QtTest library 5.12.8, Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
PASS   : AppTests::initTestCase()
QINFO  : AppTests::appTests() Backing up GUI settings to "/tmp/test_common_Bitcoin Core/5d4e9ae65d133481bcbbe11c7d8b2447b44b24f5645d077933b2e829f369ba7d/regtest/guisettings.ini.bak"

=== Received signal at function time: 147ms, total time: 147ms, dumping stack ===
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 368748
(gdb) === End of stack trace ===
QFATAL : AppTests::appTests() Received signal 11
         Function time: 147ms Total time: 147ms
FAIL!  : AppTests::appTests() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 190ms
********* Finished testing of AppTests *********
Aborted (core dumped)
```

The same hw with the previous OS (Linux Mint 20 on another disk) has no issues.

**Comment by MarcoFalke** [comment]
Is this due to https://github.com/bitcoin-core/gui/issues/10 ?

**Comment by hebasto** [comment]
> Is this due to [bitcoin-core/gui#10](https://github.com/bitcoin-core/gui/issues/10) ?

No. I'm getting ready the comment with description of problem and workarounds.

**Comment by hebasto** [comment]
The root of problem is the [`qt5ct`](https://packages.ubuntu.com/focal/qt5ct) package. It was a problem [earlier](https://github.com/bitcoin/bitcoin/pull/16366#issuecomment-511117287).

But with Qt 5.12.8 (the default on Focal codebase) only removing of `qt5ct` helps. The downside of that workaround is the dark theme does not affect the GUI look now ((
