### ISSUE TITLE
Make it possible to add a comment to a transaction

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#2086]
This is a UI-only change, the infrastructure for storing comments with transactions is already implemented (in tx.mapValue["comment").

In case of a Bitcoin URI, the comment should be filled in from the "message" field in the URI.

It is currently already possible to view the transaction comment in the Transaction Details window. However, it would be nice if it was more visible, maybe in the transaction list.

**Comment by jonasschnelli** [comment]
Implemented in https://github.com/bitcoin/bitcoin/pull/5905 (needs rebase and overhaul).

**Comment by musabi** [comment]
Can this be closed?

**Comment by jonasschnelli** [comment]
I think this would still be a valid and useful feature. #5905 was a humble try... and I think the UI concept should/must be better then 5905. Especially the feature of adding a comment after receiving or sending a tx would be very helpful IMO.

**Comment by Jssdr** [comment]
The easiest way to earn Bitcoins? Just change your browser to CryptoTab and receive payments to your balance every 10 minutes. You will get BTC for simply using it, even if just having CryptoTab browser window open. It takes less than 1 minute to start earning - https://cryptotabbrowser.com/15166435
