### ISSUE TITLE
lint-shell: Enable SC2046 and SC2086, prevent unintentional word-splitting

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#20879]
We currently disable the `shellcheck` rules SC2046 and SC2086 in our `lint-shell.sh` script, however, I think it is important that we enable them and make our scripts conformant and therefore more robust.

I have encountered many inscrutable build failures where the ultimate culprit was missing quoting, and from personal experience, I think word-splitting is the exception rather than the norm, and it would make our scripts easier to read if instances of word-splitting are pointed out by the shellcheck directives.

**Comment by laanwj** [comment]
Concept ACK, was just thinking about this in response to https://github.com/bitcoin/bitcoin/pull/19683/commits/80331107416b8a6cb487ee1c89a39c6a8bced27b
We've historically have a lot of word splitting issues, resulting in problems when building in a directory with a space in the name, for example, so this sounds like a useful lint.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by hebasto** [comment]
FWIW,

1. **SC2046** cases

```diff
--- a/test/lint/lint-shell.sh
+++ b/test/lint/lint-shell.sh
@@ -10,7 +10,6 @@ export LC_ALL=C
 
 # Disabled warnings:
 disabled=(
-    SC2046 # Quote this to prevent word splitting.
     SC2086 # Double quote to prevent globbing and word splitting.
     SC2162 # read without -r will mangle backslashes.
 )
```

```
$ test/lint/lint-shell.sh | grep SC2046 | wc -l
17
```

2. **SC2086** cases

```diff
--- a/test/lint/lint-shell.sh
+++ b/test/lint/lint-shell.sh
@@ -11,7 +11,6 @@ export LC_ALL=C
 # Disabled warnings:
 disabled=(
     SC2046 # Quote this to prevent word splitting.
-    SC2086 # Double quote to prevent globbing and word splitting.
     SC2162 # read without -r will mangle backslashes.
 )
 disabled_gitian=(
```

```
$ test/lint/lint-shell.sh | grep SC2086 | wc -l
371
```

**Comment by practicalswift** [comment]
Strong concept ACK

Shell scripting without the helping hand of `shellcheck` is a nightmare: more is more :)
