### ISSUE TITLE
build: `make deploy` fails on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#20878]
```
% make deploy
Making all in src
Making all in doc/man
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.
build-aux/install-sh -c -d Bitcoin-Qt.app/Contents/MacOS
STRIPPROG="/usr/bin/strip" /bin/sh /Users/hebasto1/bitcoin/build-aux/install-sh -c -s  ./src/qt/bitcoin-qt Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
/usr/local/bin/python3.9 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app Bitcoin-Core -translations-dir= -dmg
Traceback (most recent call last):
  File "/Users/hebasto1/bitcoin/./contrib/macdeploy/macdeployqtplus", line 22, in <module>
    from ds_store import DSStore
ModuleNotFoundError: No module named 'ds_store'
make: *** [Bitcoin-Core.dmg] Error 1
```

**Comment by hebasto** [comment]
It is easy fixed by `pip3 install ds_store`. The question is: is this a documentation flaw or a bug in the `Makefile.am`?

**Comment by jonasschnelli** [comment]
AFAIK there are more issue like the svg conversion tool... I went down that rabbit hole but couldn't find an exit. A fix would be great.

**Comment by hebasto** [comment]
@jonasschnelli 
>  A fix would be great.

There are to ways:
1) update our docs with `pip3 install ds_store`, or
2) or add `OSX_DEPLOY_SCRIPT` target to `Makefile.am`

> is this a documentation flaw or a bug in the `Makefile.am`?

**Comment by busi-reddy-karnati** [comment]
I want to contrubute, Can you assign me this.

**Comment by otech47** [comment]
> @otech47
> 
> Does [#20878 (comment)](https://github.com/bitcoin/bitcoin/issues/20878#issuecomment-756349310) work for you?


Sorry @hebasto I quickly deleted my comment to see if there was something in [this doc](https://github.com/bitcoin/bitcoin/tree/master/contrib/macdeploy) that may help before re-posting but no `pip3 install ds_store` did not work

Comment was:

> I'm still seeing this error after following the [build guide](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md)
> 
> ![Screen Shot 2022-03-16 at 5 55 36 PM](https://user-images.githubusercontent.com/4914611/158645593-fc2fa69f-dc72-4b0d-b003-d994bc0a3e79.png)
> ![Screen Shot 2022-03-16 at 5 56 20 PM](https://user-images.githubusercontent.com/4914611/158645603-bbdc4489-9d07-4223-a4db-c826ee7944df.png)
> 
> There may be an extra command/config I need that maybe could be added to the documentation... will try to figure it out

**Comment by hebasto** [comment]
> Sorry @hebasto I quickly deleted my comment to see if there was something in [this doc](https://github.com/bitcoin/bitcoin/tree/master/contrib/macdeploy) that may help before re-posting but no `pip3 install ds_store` did not work

Could you make another try in a new Terminal window?

**Comment by otech47** [comment]
> Could you make another try in a new Terminal window?

No luck unfortunately

**Comment by Dunya-8a** [comment]
@hebasto I'm having the same issue. Running on a Macbook Pro, Monterey 12.3. I installed python via brew as specified in the MacOS build docs but I also have an installation via conda (which is currently not working in my editor I should say). However, I just ran `python -version` and it gives me python not found. Odd.

Also I installed the required dependencies (ds_store and mac_alias) with pip3.
