### ISSUE TITLE
"Assertion Failed!" on Startup after Re-install

### ISSUE THREAD

**Issue by uugr33** [bitcoin/bitcoin#20905]
Asked this question in stackexchange and was directed here.

I have had Bitcoin Core on this computer before, and it worked fine for over a year with no trouble. I had recently uninstalled it, and today attempted to re-install, but, after running setup, on attempting to open bitcoin-qt.exe, the following error appears:

Assertion failed! Program: C:\Program Files\Bitcoin\bitcoin-qt.exe File: wallet/scriptpubkeyman.cpp, Line 720 Expression: mapKeys.empty()

...with three options, Abort, Retry, and Ignore. Running from the command prompt with -rescan does not help.

Any assistance would be very much appreciated.

**To reproduce**

This happens consistently when opening bitcoin-qt.exe, including after uninstalling and reinstalling further. I have tried installing on both a C:\ and D:\ drive, and the same error appears on both.

**System information**

I am running bitcoin-0.20.1-win64, Windows 10. Downloaded from bitcoincore.org.
C:\ is SSD, and D:\ is HDD.

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/blob/7ff64311bee570874c4f0dfa18f518552188df08/src/wallet/scriptpubkeyman.cpp#L720

**Comment by achow101** [comment]
The original stackexchange question is: https://bitcoin.stackexchange.com/questions/101369/re-installed-bitcoin-core-assertion-failed-on-startup

From the comment there, it seems that this is resolved?

**Comment by uugr33** [comment]
Yes, it's been resolved. The issue was with an old wallet.dat file which I did not realize the recent installation of Bitcoin Core still recognized.
