### ISSUE TITLE
Question:  Can the *.dat files be saved on a mounted storage drive?

### ISSUE THREAD

**Issue by rsthomas100** [bitcoin/bitcoin#20903]
I see the storage requirement for a new installation is about 350 GB.  Is there a way to redirect the files to be saved to a less expensive storage drive than on the main server drive?

i.e. storage_path = /media/storagedrive/data/

I hope this makes sense, and that there is a solution.

**Comment by sheffine** [comment]
Which one will work best for this file. I can get one shortly.

**Comment by rsthomas100** [comment]
"Which one will work best for this file. I can get one shortly."  What does that mean?

**Comment by sheffine** [comment]
Sorry error

**Comment by Samuel-Pedraza** [comment]
Hi @rsthomas100 - I think this page will give you what you need to accomplish this.

https://en.bitcoin.it/wiki/Data_directory

An excerpt:

> You can also store Bitcoin data files in any other drive or folder.
> If you have already downloaded the data then you will have to move the data to the new folder. If you want to store them in D:\BitcoinData then click on "Properties" of a shortcut to bitcoin-qt.exe and add -datadir=D:\BitcoinData at the end as an example:
> "C:\Program Files (x86)\Bitcoin\bitcoin-qt.exe" -datadir=d:\BitcoinData

**Comment by jonatack** [comment]
@rsthomas100 yes, as @Samuel-Pedraza mentions and to use your example path, you can add `datadir=/media/storagedrive/data` as configuration option in your `bitcoin.conf` file or launch bitcoind from the command line with `bitcoind -datadir=/media/storagedrive/data`

**Comment by MarcoFalke** [comment]
There is a specific `blocksdir` setting, which will only affect the *.dat files
