### ISSUE TITLE
Bitcoin Core slowly increase RAM use and RAM is not released on shutdown.

### ISSUE THREAD

**Issue by fmjensen** [bitcoin/bitcoin#20900]
Bitcoin Core slowly increase RAM use during first-run syncronization and RAM is not released on shutdown.
Only a cold reboot of the computer restore the RAM as unused.
Time will tell if the problem continues after initial syncronisation is completed.

**Expected behavior**

Bitcoin Core use a "resonable" amount of RAM during initial syncronation **and** completely releases the RAM on shutdown.

**Actual behavior**

![Skærmbillede 2021-01-10 162655](https://user-images.githubusercontent.com/3484684/104127196-feb25d00-5360-11eb-8431-190bfbd6cc4b.png)

**To reproduce**

I have shut the program down and restarted it several times and the problem persists.

**System information**

Bitcoin Core vc0.20.1 downloaded from bitcoincore.org
Windows 10 fully up to date. 32 Gb RAM, 512 Gb M.2 system disk

**Comment by sheffine** [comment]
I understand, thank you.

**Comment by MarcoFalke** [comment]
It is expected for the GUI to keep the memory until the small "shutdown in progress" window disappears. Do you see that window and which process does the task manager associate the memory with?

**Comment by fmjensen** [comment]
- I see the small window explaining that the computer shoud not be powered off before it dissapears. And i always wait for it to do it's thing before doing anything else.
- The taskmanager does **not** show wich process is hogging memory - that is what is really weird to me. It is however very clear to me that it *only* happens while I have Bitcoin Core running. The _bitcoin-qt.exe_  process is growing in memory use, but no where near what could explain that almost all of my 32 Gigs of RAM beeing used, and _bitcoin-qt.exe_ does in fact release what task manager show it is using.

To further explain the memory consumption is happening really really slowly - i changed the update speed of the task manager from normal to low hence the 4 minutes window is shown in screenshot above, to show it graphical there.
I don't know if this helps but here is a task manager screenshot ~10 minutes after i started bitcoin core today. It is 95% done with the initial sync. says it still got 15 hoursto go. I will see if i can remember to take a similar screenshot in a few hours to comparison.
![Skærmbillede 2021-01-11 105758](https://user-images.githubusercontent.com/3484684/104167034-f5c29980-53fb-11eb-961a-9e24638d83ac.png)

**Comment by MarcoFalke** [comment]
I don't know about Windows, but some operating systems will load read files in RAM (to optimistically speed up re-reads). Not sure how to find out whether that is the case here.

**Comment by fmjensen** [comment]
I do not know about that, but no matter what OS a program is running under, then it should release all used resources, RAM included, when the program is shut down... **_not_** require the computer to be rebooted to make the RAM avilable to other running programs!?

**Comment by fmjensen** [comment]
Following is a series of screenshots of what i saw in the last hours of initial syncronization. I _think_ the memory hogging was worse in the beginning of syncronization.
Unfortunately i haven't got any screenshots of the problem fraom the early part of syncronization when i realized something is off because almost all of my 32Gb RAM was in use and I started to see performance issues ;-)

![Skærmbillede 2021-01-11 105758](https://user-images.githubusercontent.com/3484684/104182493-d7b36400-5410-11eb-9793-8c852d88cfc3.png)
 - 20 minutes to go.
![Skærmbillede 2021-01-11 114854](https://user-images.githubusercontent.com/3484684/104182501-db46eb00-5410-11eb-9126-14a4f3062c91.png)
- 6 minutes to go.
![Skærmbillede 2021-01-11 120303](https://user-images.githubusercontent.com/3484684/104182512-deda7200-5410-11eb-8fbd-4285c5fcb672.png)
 - 3 minutes to go.
![Skærmbillede 2021-01-11 120651](https://user-images.githubusercontent.com/3484684/104182533-e568e980-5410-11eb-8423-d223cc4978a5.png)
 -  Initial syncronization just completed.
![Skærmbillede 2021-01-11 123846](https://user-images.githubusercontent.com/3484684/104182538-e732ad00-5410-11eb-9a66-45f877677391.png)
 - 4 minutes after sync. completed.
![Skærmbillede 2021-01-11 123954](https://user-images.githubusercontent.com/3484684/104182543-e863da00-5410-11eb-9a9a-1ee89d5a8216.png)
 - Shutting Bitcoin Core down:
![Skærmbillede 2021-01-11 125452](https://user-images.githubusercontent.com/3484684/104182562-f154ab80-5410-11eb-8338-49e6f3ecd841.png)
 - Graceful shutdown complete.
![Skærmbillede 2021-01-11 125514](https://user-images.githubusercontent.com/3484684/104182569-f3b70580-5410-11eb-8f06-f4633870b2df.png)
 - 
![Skærmbillede 2021-01-11 125624](https://user-images.githubusercontent.com/3484684/104182575-f580c900-5410-11eb-8623-69674a4f3fc9.png)
 - Computer was rebooted.
![Skærmbillede 2021-01-11 130122](https://user-images.githubusercontent.com/3484684/104182586-f74a8c80-5410-11eb-8541-eaf07c465b5f.png)
 - After reboot Bitcoin Core runs nicely and without any memory hogging going on.
![Skærmbillede 2021-01-11 134918](https://user-images.githubusercontent.com/3484684/104185109-c9674700-5414-11eb-9e64-03dacb9a7c23.png)

**Comment by jonasschnelli** [comment]
RAM management is up to the OS. Once an application has terminated, the OS gains full control back over the RAM. I guess what you see is released RAM but not necessary occupied by another process. Though that's said: I'm far away from being an MS Windows exert.

**Comment by prayank23** [comment]
I tried to reproduce this on a system with similar config but 8 GB RAM. Had no issues.

Before starting Bitcoin Core:
![image](https://user-images.githubusercontent.com/13405205/104231231-a3718f00-5474-11eb-905a-34afb3bcf5d0.png)

After starting Bitcoin Core(splash screen):
![image](https://user-images.githubusercontent.com/13405205/104231278-bc7a4000-5474-11eb-8b15-a61e32141969.png)

While sync is going on:
![image](https://user-images.githubusercontent.com/13405205/104231369-da47a500-5474-11eb-8634-a30e82c52e0b.png)

After sync is finished:
![image](https://user-images.githubusercontent.com/13405205/104232665-aec5ba00-5476-11eb-9a23-3fd6ffbb3e6c.png)

After closing Bitcoin Core:
![image](https://user-images.githubusercontent.com/13405205/104232540-80e07580-5476-11eb-8d97-f7428bf4bf90.png)

**Comment by fmjensen** [comment]
I just noticed in my screenshots above that the program caused 177.318.393 Page Faults. That is a LOT
But Ohkay - idk anyway - was just trying to be helpfull... I deeply apologise for wasting your time.
