### ISSUE TITLE
Time to increase the block size?

### ISSUE THREAD

**Issue by Crypto2** [bitcoin/bitcoin#20924]
SegWit has helped no doubt but it's clearly not enough, even an increase to 2 MB would be better than nothing if not 4 or 8 MB.

**Comment by Crypto2** [comment]
I'll take that as a big yes, not sure why it's 2021 and we're not bringing this up again?

**Comment by fanquake** [comment]
> I'll take that as a big yes,

No. You can take that as, "this is clearly not the right place to try and have this discussion". This issue tracker is primarily for reporting bugs in Bitcoin Core. Not for vague, opened-ended discussions about increasing block size.
