### ISSUE TITLE
We should remove MAX_BLOCK_BASE_SIZE in functional tests ?

### ISSUE THREAD

**Issue by tannguyen** [bitcoin/bitcoin#20940]
I can see that @gmaxwell  pushed a commit to `Remove confusing MAX_BLOCK_BASE_SIZE` (3babbcb48), by the way, I still can see the use of it in a lot of functional tests (p2p_segwit, mempool_accept...), do these test cases still make any sense? Should we remove them as well?

**Comment by adamjonas** [comment]
closed by https://github.com/bitcoin/bitcoin/pull/22378
