### ISSUE TITLE
Error while making

### ISSUE THREAD

**Issue by robinh007d** [bitcoin/bitcoin#20950]
I was making and an error came up
**Expected behavior**

no errors
**Actual behavior**

CXX      libbitcoin_server_a-txmempool.o
txmempool.cpp: In member function ‘CTxMemPool::setEntries CTxMemPool::GetIterSet(const std::set<uint256>&) const’:
txmempool.cpp:883:29: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  883 |     return Optional<txiter>{};

**To reproduce**

happens everytime
**System information**

github latest version

linux amd cpu nvme disk

CXX      libbitcoin_server_a-txmempool.o
txmempool.cpp: In member function ‘CTxMemPool::setEntries CTxMemPool::GetIterSet(const std::set<uint256>&) const’:
txmempool.cpp:883:29: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  883 |     return Optional<txiter>{};

**Comment by prusnak** [comment]
1. this is warning, not an error
2. i don't see `return Optional{};` on line 883 of master - are you sure you are on the latest commit?

**Comment by robinh007d** [comment]
phew, only 1 warning when i make

im not entirely sure...

git clone https://github.com/bitcoin/bitcoin.git 

this is what i used

**Comment by prusnak** [comment]
Type `git rev-parse HEAD` to get the commit you are on.

If it's not `30e664dcce1a9adb9ba9a29e4f0cf809767870dd` you are not on the latest commit and you need to do `git pull`.

**Comment by robinh007d** [comment]
Ok thanks alot
