### ISSUE TITLE
Interface is unresponsive while syncing with bitcoin-qt 0.21.0 

### ISSUE THREAD

**Issue by puchu** [bitcoin/bitcoin#20956]
The interface gets unresponsive while syncing the blockchain.

It sometimes takes minutes until the interface recognises the user input

**Expected behavior**

The interface is responsive and 0.20.* didn't have this massive lagging

**Actual behavior**

the interface responds at least in a few seconds

**To reproduce**

start bitcoin-qt with a not fully synced blockchain

**System information**

Bitcoin 0.21.0 compiled from source

Linux
KDE

**Comment by Saibato** [comment]
u might want to take a look at tyi.https://github.com/bitcoin-core/gui/issues/16

**Comment by laanwj** [comment]
Closing as duplicate. Non-responsiveness of the GUI during initial sync and while catching up is a well-known issue.
See also #17145.
