### ISSUE TITLE
Compilation fails on Debian 10 (libboost-1.67)

### ISSUE THREAD

**Issue by pdrobek** [bitcoin/bitcoin#20961]
I have tried compiling the code (0.18 and 0.19) and I get an error every time

CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Opuszczenie katalogu '/home/pdrobek/bitcoin/src/secp256k1'
  CXXLD    bitcoind
/usr/bin/ld: libbitcoin_wallet.a(libbitcoin_wallet_a-walletutil.o): in function `ListWalletDir()':
/usr/local/include/boost/filesystem/operations.hpp:1249: undefined reference to `boost::filesystem::detail::recur_dir_itr_imp::increment(boost::system::error_code*)'
collect2: error: ld returned 1 exit status

OS: Debian Buster
Libs: libboost-dev-all (1.67)

**Comment by mshalabi1990** [comment]
How do you guys even trust the people on here typing sending codes to put in

**Comment by mshalabi1990** [comment]
They could be Russian hackers

**Comment by decryp2kanon** [comment]
it seems just linker error. check your dependency location.

**Comment by samsungbiologics** [comment]
hahaha bug it

**Comment by pdrobek** [comment]
I have followed build-unix.md for reference. Configure give me no error so i assume there is no error on my side. I also tried libboost from previous Debian (jessie), no luck. 

`checking for boostlib >= 1.47.0 (104700)... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
checking for dynamic linked boost test... no
`

**Comment by jarolrod** [comment]
Cannot reproduce on a clean install Debian 10 VM following the [0.18](https://github.com/bitcoin/bitcoin/blob/0.18/doc/build-unix.md) and [0.19](https://github.com/bitcoin/bitcoin/blob/0.19/doc/build-unix.md) branch `build-unix.md` instructions

Can you run ` grep BOOST_LIB_VERSION /usr/include/boost/version.hpp` to confirm that you are using `Boost 1.6.7` and it is installed in a uniform path

What happens if you run: `./configure LDFLAGS="-L/usr/include"`

Boost Bug Reference: https://svn.boost.org/trac10/ticket/10038

**Comment by pdrobek** [comment]
grep BOOST_LIB_VERSION /usr/include/boost/version.hpp
```
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_67"
```
./configure LDFLAGS="-L/usr/include"

```
Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = no
  with test     = yes
    with fuzz   = no
  with bench    = yes
  with upnp     = auto
  use asm       = yes
  sanitizers    =
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = linux
  build os      =

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      =   -fstack-reuse=none -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wformat -Wvla -Wredundant-decls  -Wno-unused-parameter -Wno-implicit-fallthrough   -g -O2
  LDFLAGS       = -pthread  -Wl,-z,relro -Wl,-z,now -pie  -L/usr/include
  ARFLAGS       = cr
```
I dont know why libboost-filesystem is installed in /usr/locale/include (see line from output of make command -->/usr/local/include/boost/filesystem/operations.hpp)

**Comment by decryp2kanon** [comment]
it worked on debian 10 buster

```bash
make clean && \
./autogen.sh && \
./contrib/install_db4.sh `pwd` && \
export BDB_PREFIX=$PWD/db4 && \
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" && \
make j4
```

**Comment by hebasto** [comment]
@pdrobek 
> ./configure LDFLAGS="-L/usr/include"

Why `LDFLAGS` is passed?

**Comment by pdrobek** [comment]
I left it on Debian, move to newest Ubuntu and issue is now resolved. Thank you

**Comment by blackmennewstyle** [comment]
Sorry to jump into that closed issue but this issue has been reported on FIRO as well and the easy lazy fix i read so far is to execute:

```
apt-get install libboost-all-dev
```

It also has been added in the FIRO documentation building for UNIX.
Hope that will help anyone facing the issue in the future :)
