### ISSUE TITLE
RPC: Derive wallet addresses

### ISSUE THREAD

**Issue by monokh** [bitcoin/bitcoin#20991]
**Is your feature request related to a problem? Please describe.**
It is not possible to simply derive the wallet's addresses. I have a need to find the address inside the HD wallet at a given HD path.

**Describe the solution you'd like**
- Derive address using the node i.e. `derivewalletaddress(path)` that returns the same as `getaddressinfo`

**Describe alternatives you've considered**
- Export xpub - not possible
- Export the seed - `dumpwallet` only exports to file - cannot be used over network
- `deriveaddresses` - requires xpub/xprv
- `listaddressgroupings` + `getaddressinfo` for every address and find by `hdkeypath` - This is way too intensive

**Additional context**
Some context I found about xpub exporting explains that this is not possible: https://bitcoin.stackexchange.com/a/90149/106210

**Comment by achow101** [comment]
This is possible to do with descriptor wallets. `listdescriptors` can be used to get the descriptors for a descriptor wallet, and those can be used directly in `deriveaddresses`.
