### ISSUE TITLE
Unsigned integer wraparound in CCoinsViewCache::SpendCoin makes CCoinsViewCache::DynamicMemoryUsage() return bogus values

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#21001]
When running the fuzz tests under `-fsanitize=integer` I stumbled upon this:

```
coins.cpp:114:22: runtime error: unsigned integer overflow: 0 - 96 cannot be represented in type 'unsigned long'
```

https://github.com/bitcoin/bitcoin/blob/e31af1065e8a4a9dbb294e980047a135d4233962/src/coins.cpp#L111-L114

Note that `cachedCoinsUsage` is decreased despite being zero which causes it to wrap around. This in turn makes `CCoinsViewCache::DynamicMemoryUsage` start returning bogus values.

Nothing high priority of course, but perhaps worth fixing? :)

**Comment by sipa** [comment]
That would be a bug; it shouldn't be possible to hit a situation where the dynamic memory counter goes negative. What input/sequence of operations triggers this?

**Comment by practicalswift** [comment]
I think the problem is in `AddCoin`: AFAICT `cachedCoinsUsage` is decreased also in the case when we throw `std::logic_error("Attempted to overwrite an unspent coin (when possible_overwrite is false)")`.

This sequence triggers the problem:
* A successful `AddCoin(…, …, false)` call
* A failed `AddCoin(…, …, false)` call (`std::logic_error`)
* A `AddCoin(…, …, false)` call

Let me know if further details are needed.

**Comment by sipa** [comment]
@practicalswift logic_error triggered indicates incorrect usage, and outside of tests is equivalent to an assertion failure; after that no guarantees are expected to hold.

**Comment by practicalswift** [comment]
@sipa OK, thanks for clarifying. I'll make the fuzzing harness stop at the first `std::logic_error` then :)

**Comment by danben** [comment]
Is there still anything to be done here or can this be closed?
