### ISSUE TITLE
Decentralization is dead, issues go on to be deleted and maintainers do not care about the use case 

### ISSUE THREAD

**Issue by shopglobal** [bitcoin/bitcoin#21046]
My issue was closed without regard for decentralization. Why are you not willing to address the issues brought about by fellow bitcoiners?

Unattended issue here: https://github.com/bitcoin/bitcoin/issues/21044

You can't ban me and you also can't bar decentralization!!

**Comment by fanquake** [comment]
This issue tracker is used to track bugs in Bitcoin Core. Your issue was closed because it did not report a bug.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode. Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
