### ISSUE TITLE
Network fees too high && normies can't afford to use Bitcoin!

### ISSUE THREAD

**Issue by shopglobal** [bitcoin/bitcoin#21044]
Hi guys, I'm a developer working on a community driven altcoin network based on cryptonote called Electronero network, which consists of ETNX ETNXP LTNX GLDX and CRFI digital assets. 

The reason for my issue today is that normal users can't afford to move bitcoin as a means for payment. The problem is that bitcoin network fees are so high (currently rising above $14-$17 USDt per transaction) the issue is that normal users trying to pay for items are being stuck with paying exaggerated fees for moving small amounts of coin. Example: to transfer $100 will cost $14 and to transfer $14 will cost $14. I'm sure you see my point. If this is intended functionality of bitcoin platform to make the rich richer and keep the poor poor then by all means I apologise for wasting your time. Although on the other hand, if this is not the intended functionality and the Bitcoin core developers want to help the network use Bitcoin as a means of payment then please I urge you to lower the bitcoin network fees by at least 50%... Current rates are causing small amounts of bitcoin to be "frozen" where as wallets containing small outputs can't even move their coins because the fee would consume the amount in the transaction. This is a pain for those who have used many wallets (such as BitPay users whose wallet address changes on each deposit) think about it ... If a BitPay users has $150 in BTC on their BitPay wallet but it's spread across 10 wallet addresses now they can't move 33% of those funds and they have to pay another 20% in network fees to withdraw the remaining balance, then their left with merely $50-$60 in BTC. What that means is that BTC is not usable as a Currency! That is a bubble waiting to burst at the very least! I await your feedback

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode. Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
