### ISSUE TITLE
> let's make a pull request to reduce the network fees.

### ISSUE THREAD

**Issue by shopglobal** [bitcoin/bitcoin#21048]
> let's make a pull request to reduce the network fees.

That is not how that would work. Please stop opening these issues.

_Originally posted by @fanquake in https://github.com/bitcoin/bitcoin/issues/21047#issuecomment-770529201_

Why are you silencing my issues? Is this not the main repository for bitcoin? BTC can't keep charging $17 per transaction, and think that we're going to do any good here. Many users can't move hundreds of dollars frozen in wallets with small outputs at the current price...  To say that this isn't a bug is pretty much looking the other way... The price changed, let's lower the network fees accordingly. 

We're causing a bubble that's on its way to becoming an atom bomb 💣 if the price continues to rise the fees will not be manageable to many users and the fees are already causing problems for many users. We encourage users to buy fractions, and they can't move fractions of BTC without significant loss. 33% up to 50% will be lost for small output wallets and you think this isn't a bug? This is a problem that needs to be addressed.

**Comment by fanquake** [comment]
Discussion on proposals for changing Bitcoin's network rules affects more than just a single implementation, and belong on the bitcoin-dev mailing list: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev.

This issue tracker is for specific implementation issues with Bitcoin Core, not network-wide protocol changes.
