### ISSUE TITLE
Bitcoin core maintainers are not enabling decentralization

### ISSUE THREAD

**Issue by shopglobal** [bitcoin/bitcoin#21047]
I posted an issue regarding the network fee, the Bitcoin core maintainers have tried to silence my issues. I am now posting in another topic. I will post on feature request if necessary, I will not be silenced. This is bitcoin were talking about. We're supposedly able to offer advice and suggestions and see changes otherwise where is the decentralization? If you can close my issues without replying then that's centralization at it's finest. I am here asking for feedback about the network fees. I believe network fees are too large to continue to grow btc as a currency or means of payment. BTC is becoming less and less available for use as a form of payment, and that it not what we stand for! 

Here are my Unattended issues:  
Initial issue:
https://github.com/bitcoin/bitcoin/issues/21044

Follow up: https://github.com/bitcoin/bitcoin/issues/21046

Now what's next? If you continue to delete my issues you're against decentralization. Argue my point of network fees being too large, and if we agree let's make a pull request to reduce the network fees. To silence me is just you standing for centralization!!!!

**Comment by fanquake** [comment]
> let's make a pull request to reduce the network fees.

That is not how that would work. Please stop opening these issues.

**Comment by sipa** [comment]
Discussion on proposals for changing Bitcoin's network rules affects more than just a single implementation, and belong on the bitcoin-dev mailiglist: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev

This issue tracker is for specific implementation issues with Bitcoin Core, not network-wide protocol changes.
