### ISSUE TITLE
log: Add debug log category prefix

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#21058]
I wanted to log (especially incoming) onion connections.
Was unsure if category `net` or `tor` would do that.

In the debug log you do not see which debug message is of what category, or if it is of no debug category at all (standard log).

I would like if debug log categories are logged e.g. with a `[<debug log category>] ` prefix.
E.g. for `net` debug category log line, the line is currently logged like this (I hope I am right that this belongs to `net`category, so this is an example of the uncertainty that results in the current absence of the category logging):
`2021-02-01T19:33:08Z SOCKS5 connected zncs3yn6h4l7c3z7.onion`

My wish would be that it would be logged like this:

`2021-02-01T19:33:08Z [net] SOCKS5 connected zncs3yn6h4l7c3z7.onion`

If that would have any drawback like log gets bloated, an option to toggle debug log category prefix logging could be introduced, e.g. `debugcategorylogging=<1|0>`

**Comment by wodry** [comment]
I know log category logging e.g. from Bind DNS server log.

**Comment by x4e** [comment]
I'm not sure that would be very easy, a log's category is not a single category but rather a number that can represent many different categories by bitflags. 
I guess it could be possible to generate a comma seperated list of every category that the log is a part of, but that would probably be slow and complicated.

**Comment by laanwj** [comment]
Although strictly a bit flag, every message that is logged is only in one category so it should be possible to do this.

**Comment by jonatack** [comment]
This seems to have been closed/completed by #24464 and current follow-ups.
