### ISSUE TITLE
Setting a label on bitcoin-qt changes the label of all unlabeled transactions

### ISSUE THREAD

**Issue by surak** [bitcoin/bitcoin#21057]
**Expected behavior**

When selecting one transaction, and choosing "Edit Label", it changes the label of every single transaction which didn't have a label previously. 

**Actual behavior**

What happens is the aforementioned effect - all transactions get such label

<img width="325" alt="Screen Shot 2021-02-01 at 19 33 19" src="https://user-images.githubusercontent.com/878399/106502247-6cffc080-64c4-11eb-9b9e-df5ceb2e128e.png">

<img width="246" alt="Screen Shot 2021-02-01 at 19 33 36" src="https://user-images.githubusercontent.com/878399/106502415-9ddff580-64c4-11eb-890f-3c8ed68570b7.png">

** Expected behavior **

As one clicks one transaction and it says "edit label", I would expect that the label is transaction-related, not per receiving address. Either the GUI is misleading in the description or it's not behaving as it should.

**To reproduce**

Choose one transaction. Choose edit label with mouse right-button. All transactions to that receiving address will change to such label.

**System information**

Bitcoin-QT 0.21.0 from bitcoin.org

Mac OS Big Sur, whatever version came out last week

**Comment by jarolrod** [comment]
There is a GUI Repo here: https://github.com/bitcoin-core/gui. Do you mind closing this and re-opening this issue in the GUI Repo?

**Comment by hebasto** [comment]
@surak 
A label is an address' property, rather then individual transaction's one. If all affected transactions are associated with the single address, the described behavior is expected.

**Comment by MarcoFalke** [comment]
Closing as this is an expected feature

**Comment by sipa** [comment]
I think the issue here is not how it works, but the fact that it is misleading. Perhaps it's worth reopening something of that nature in the GUI repo?

**Comment by MarcoFalke** [comment]
See also #5905

**Comment by surak** [comment]
@sipa is correct. GUI is misleading. https://github.com/bitcoin-core/gui/issues/209
