### ISSUE TITLE
Use of testmempoolaccept is not clear. testmempoolaccept yields unexpected error.

### ISSUE THREAD

**Issue by Giszmo** [bitcoin/bitcoin#21069]
**Expected behavior**

I would expect to get no error message when using `testmempoolaccept` on a raw transaction that decodes just fine using `decoderawtransaction` or at least a hint at what went wrong.

**Actual behavior**

```
getrawtransaction ea369e4d7cbb9f2a2fd58dff4d0923112a00674faa1b35bfd6424f89c94ab653
0200000000010175c0e156c5c2545db4cf009a756a433677cce7d845f7626559329681379998950...
decoderawtransaction "0200000000010175c0e156c5c2545db4cf009a756a433677cce7d845..."
{
  "txid": "ea369e4d7cbb9f2a2fd58dff4d0923112a00674faa1b35bfd6424f89c94ab653",
  ...
testmempoolaccept ["0200000000010175c0e156c5c2545db4cf009a756a433677cce7d845f..."]
Error: Error parsing JSON: [0200000000010175c0e156c5c2545db4cf009a756a433677cce...
```

**To reproduce**

Probably always reproducible with confirmed transactions?

**System information**

bitcoin core 0.18.1 tgz, 0.20.0 snap and tgz

**Comment by MarcoFalke** [comment]
What are the exact steps to reproduce? GUI/CLI?

**Comment by Giszmo** [comment]
The above command-result-command-result sequence is copied from a freshly installed 0.21.0 (sorry. said 0.20.0 above) -> Window -> Console but with the other versions I used the bitcoin-core.cli equivalent.

![Screenshot from 2021-02-03 09-03-18](https://user-images.githubusercontent.com/96378/106744587-b5bb9480-65fe-11eb-9f35-42604a378983.png)

**Comment by MarcoFalke** [comment]
It is not the best UX, but you have to type `testmempoolaccept '["ffff"]'`

**Comment by Giszmo** [comment]
Thanks for clarifying. I now see how that makes sense. Maybe the help should be changed then??

![Screenshot from 2021-02-03 10-15-24](https://user-images.githubusercontent.com/96378/106752059-c6710800-6608-11eb-92f0-042c79649028.png)

**Comment by MarcoFalke** [comment]
the oneline help only shows you the types, not the "encoding". Usually the encoding is done by a json library, but the gui (or the command line) doesn't have a json interpreter. You can find example calls for the command line (and gui) if you scroll down.
