### ISSUE TITLE
Follow-ups to PR 19509 - Message Capture

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#21079]
This issue tracks follow-up actions from #19509

- [ ] Use 1 file = 1 session https://github.com/bitcoin/bitcoin/pull/19509#issuecomment-765625996
- [x] Update message type checking in p2p_message_capture.py: https://github.com/bitcoin/bitcoin/pull/19509#discussion_r568553627
- [x] Remove MakeUCharSpan https://github.com/bitcoin/bitcoin/pull/19509#discussion_r562515326
- [ ] Add RPC to enable/disable message capture per peer
- [x] Vulture warning about discarded value https://github.com/bitcoin/bitcoin/pull/19509/files#r571454691

**Comment by jnewbery** [comment]
@troygiorshev I think I've captures all the follow-ups here. Are you planning on implementing these or should I mark as up for grabs?

**Comment by flack** [comment]
see also: https://github.com/bitcoin/bitcoin/pull/19509/files#r571454691

**Comment by jnewbery** [comment]
> see also: #19509 (files)

added
