### ISSUE TITLE
Build fails on FreeBSD 12.2 due to libdb_cxx headers missing

### ISSUE THREAD

**Issue by bektar** [bitcoin/bitcoin#21072]
After following [the instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-freebsd.md#descriptor-wallet-support) I end up with the error:

    …
    configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

After running the command:

    ./configure --with-gui=no --without-bdb MAKE=gmake

If I instead run:

    ./contrib/install_db4.sh /usr/local/src/bitcoin-core
    setenv BDB_PREFIX "/usr/local/src/bitcoin-core/db4"

    ./configure --with-gui=no --without-bdb MAKE=gmake BDB_LIBS="-L\${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I\${BDB_PREFIX}/include"

It finishes without any errors.

**Comment by bektar** [comment]
This is after checking out the v.0.21.0 tag

**Comment by MarcoFalke** [comment]
The instructions are only valid for master. Though, we don't have instructions for 0.21.0 yet on how to build descriptor wallets.

**Comment by bektar** [comment]
Ah, right. Yeah everything works fine on master. Sorry for taking your time.
