### ISSUE TITLE
U.S. Navy Special Operations and Bitcoin

### ISSUE THREAD

**Issue by zoltan-konder** [bitcoin/bitcoin#21076]
I just noticed that here on GitHub there is a Bitcoin **contributor** from @usnavy who calls himself "Operation Specialist". Username: @RandyMcMillan 

His profile picture is strikingly similar to @laanwj's profile picture.

I personally consider the @usnavy here as a **security threat**. 

If someone from the Chinese navy would be contributor, there would be a public freakout. Until now nobody mentioned anywhere that the U.S. Navy involved in Bitcoin. 

**I'm wondering what the hell the U.S. Navy has to do with Bitcoin?**

**Comment by jonatack** [comment]
@zoltan-konder I have seen only helpful behavior from @RandyMcMillan here, who is an active contributor. The bio and logo don't matter? We could all be pseudonyms anyway.

**Comment by promag** [comment]
So where is the bug/issue?

**Comment by zoltan-konder** [comment]
Apparently he does work for U.S. Navy since 1993 until this day. So it does matter! A normal person would not call himself a member of the biggest terrorist organization in the world! 

His status is:  :artificial_satellite: Those who know - do not speak of it.

While on some other places he even claim to work for the **United States Space Force**. Switch from the U.S. navy to U.S. Space Force would be only possible if this guy is working for the NSA or the CIA.

**Comment by laanwj** [comment]
I'm very okay with other people using bees as avatars :slightly_smiling_face:  It's also clearly not a mimic of mine.

As for his stated affiliation, I don't see any reason to discriminate on that. If you distrust someone, all I can suggest is to review their contributions closely. Or everyone's. A clandestine saboteur would prooobably not be so open about their affiliation.

**Comment by zoltan-konder** [comment]
Show me any commit made by people who claims to be working for the Chine Navy. There is none.

**Comment by zoltan-konder** [comment]
@laanwj can you delete this issue. You can delete issues instead of just closing them.
