### ISSUE TITLE
mandatory-script-verify-flag-failed (Public key is neither compressed or uncompressed)

### ISSUE THREAD

**Issue by liuywme** [bitcoin/bitcoin#21098]
"txdata":"010000000001343414102f9b41a1c1269bc0301fb865bfa5d33eca9267f4216c59069a99b5d1b2010000004b483045022100eb67bf6fa2b71fded0b19198383eb4a45e75bee1f0207ea41378c986a212884302202d35ace9bc3b855b7b14c064e1914cddda053798ec184871937dc3a59b9bb32e010100fdffffff4a1d6a31aef67692923beaf5746c3e3177f7090719e5f26d5ae392b0c25b91d6010000004a47304402206d0125cbcf941fce57419ed19c22f4ee64e54fc4671bf31a0fc3aeeb5aceef0702206f44436c80d559e28de00311cac6b70cdc0bc53d9f3d78897cbaa8dcff5ded2a010100fdffffff2ab55faafba7a2c42e034ca958ac00cc0f7d0eb214cc13d1666eeb6d95eb6232010000004b483045022100ff6339a400f4f45ba9f7220a658818c2287b39e0c8d55ac5f48f1fa7cd12b54502202eec8739ca3f1ab26c3164773ad0cb7bc8d05a92c3af0dee21a3027a0b2fb304010100fdffffffaaaa313654b83474468b74b338bc93191ae16585b4976ec6c0df6d5e2803fbf3010000004b483045022100e1d8079e57572613047e5d0feaba154bd6b1ed4c115136bb487cab47fe6c720602204c7ec1be709da004fbba7ca35a007eaad8960067f9ecc3106fff7b982a946410010100fdffffffdb920ad4a0c484de3aab084807b671c23aad7eddf697b23a48bafdd9b696cc14010000004b483045022100877344baddacdffdecabd3a0c453b64072f89f373750f8c28fe1c9c794d09237022036fd6491cb104672e08447bfd2fb221adfc65eb962f57049e73423170d37ec01010100fdffffff6538903c67dc01a3c069fc45d1601660d91ff093ce9a5df6c4e0e53435bff996010000004a47304402204460f39b11f869bf34b51146e25f4eca39dcf41692c6c60684b47fea22b1f8a002206c82fe15607d34196f701bb4f1ab1d8a50f9afc00bf6e0bbb5ae25c0489c6b14010100fdffffff82ab5d8eb1aa3d2318702745637b1866a17f92fcd556992a3083d0e744e1ab7a010000004a47304402206fbd84d5bdfce1e64c16d4917063d9e5ba442992b715eebf225c7bae4c91572402200b2fc074a3aa1e750009102a4824d81c18491f27a45f2efa328148f6cdb662c6010100fdffffff195788a615893f7013970ec8a6ef8d01a032343b5130b50308824868ca04db73010000004a47304402203ccee315759c7adf49475f4f40ca13c7173c1eee709ba39fc4454aa76b3bc0b702205f610fd1e2148677b121b2d66f5433c50eb38b663900020abde4acdfbcc363f7010100fdffffff56faa9c6924e2221905c11bf455079dab94f0bc6b2ef243a599953f21a66b679010000004a473044022008dee895689f6f2009ab8e32f54ccfd65915eebee3ba3b1db2fddc6f6082caae022024371b490b9c13237a2ad810029732c007c6a59fb4a815f53ce18246bdb39476010100fdffffff32ad63ac36294719c323632ea3b0b87ac3a5d024cd23a6fecd45aa75f6fe01e8010000004a47304402203ad7371bfaf287992bc14df0df20d306db1125d96dc106d5df628e00ffe8f65f02203c2514a7e8b624200bac0f6a32b7518c9f9178f5ee001240590af8be52d48341010100fdffffff99a67d2830ad7f13e587e512a41896d319198a2db6acc4793715a95ebb752235010000004b483045022100a61b462ad9590cc7a082862aeb3b992f712bd97a0dec849f4b1f2a7be053ab0a02204601e8ca7dee8a254950cf6e6a5aa73db7535f8d7e28ff72846638c8a8a4227b010100fdffffff1e0d923adfe9af7059d345843003036af0a0a95e376eea2a6453d64afe8eaca8010000004a4730440220454cb3eb3aae42c131bb2ac6e24a946d7f3c48acd27a702533cc23748535991a0220501d279847931b39159e983f9fb69b2e0c8187edb67ef60d3e652598ce9b1b46010100fdffffff535a7dbb24c9faab83ffb0f8588a5a050a98324dff86cbc3c33736c429459bc2010000004b483045022100d1026f4fe67af62a98a50b24dc27e06d12b45ac012640cc4588e6b1321614b160220784b765f025d291c6608dddfdb5fee48a4c33ed65e0dfc06bba24d49f48911af010100fdffffff5d36731c4a2a964131d684c77e9f66026141827ca2f5ee07279c87b5e4672365010000004a47304402201a1b9cd5f3908aea7244d3f8042568fda3ecf9ecd99e717ae31bb895dcffa0ea0220113f91e67647345c3498981f458881411de3a844a8490ba0f59574a4ed6b435c010100fdffffff97409d520719545c620c4c29fb9589ee2c495beff2aa06157e7277b62ca6585d010000004a473044022038719f878aebf18393001337586c822ead4b9e919cb6c7182aac803b9481139d022053c61dc49cb3f57d833499fdf3f4e9347448c83c8e33f9de55a126f55e661850010100fdffffffbc56b136f0f43cfb21222a70671059175409e1b89d1e4843ea4572b4013ef26e010000004a4730440220557f4e3f7e6ae4133ed56515a1edfd179d999097f0bc829d3d152ca9c0cc47150220438612dfd61ca806e13c7f003b672cb82c22ec14aa402c5d07da566548244be1010100fdfffffff4ab39a44c3d85489d549dc18e4a3f9b090c60a55d96d0142cfc36ecbbadad19010000004a473044022032222d2f9c42812e097f29a86d66d7ad849c41fe92717cefc1e73d60695e4bd7022025f9cfeef77a213a75a174f42326bbb1f3b003f7211e6d4203d7dbd5c334b05d010100fdffffffc0ecbab3989807884bbcade2435ff5899c60cbebcc9bfe8f5b566bc878ef860f010000004b4830450221009f9aca7cf1e2ef4842b50386b23ff38a77706cf263625f3e90323e1cbfa4576102205e548d266309b0511e2b319c5c72f967d654ffe2e9d576cfc3980434e506e49d010100fdffffff32eff66cb81c7c95be5be7b712492a45a2e0925c9f3a1c56dc220f64b4990e22010000004a473044022020f190680ec06109ca0f38b0839965b4d594bb05d6b38c94be1ecca1fc3083a902205560dde76b7e8de3a117c2a01252515fec94e78b755035da891acf058ce7ff2c010100fdffffff0713f30faf3df3eecc36e0d470427c4ff75ee83c6c587800c83a285e6d9e207e010000004a473044022006f4b18b69e02e8a41561773b6f26349800415c4d40caa0a1e43f8b1e432ff6502200de75f2b12d97f5b403dcf251906270fe699b13cd522ca2a547f7502bbd76ca1010100fdffffffeb9abcc6b62b4a4502b39cf8e95bf1a8ed025de3e92cb0308ec9cac9f09d5f32010000004a473044022037059d74e09701b5da5db39c468975acdfada034b8a970f875e76843e0874a38022005671d6e42349e283850b9766b250dc0ab99df5662c772ca2e00f355f7fbc985010100fdffffff8cf19ee3d2a410202be825ab57b0d3296aba0ce830869717a4fa6a4d3f29dc84010000004a473044022020d2d681b7081a7291eb92b70168f5e9b76fbfb725cd1d7d5ace2639d626d9e002200a9229c35cbbb2dc572e1f9e7994d458d7abdae1b53188a555c67e863c088fb8010100fdfffffffb18c17a7c29237b5fd84774da48b2008f685648b1071023ae7edccfdd21462d010000004b483045022100efd8b5b3854a744863e43c9e235cf93a3eb17cb6061dde8f37535ea20d1945c702205aa93d4ef6e38b57d505072b251c096166ae993d83303e8710c3ed4772e8fba2010100fdffffffa7df914434ebd4bf85b2484e87844bc0d1a40476e9ef755638dedb87e5ac3ec7010000004a47304402201b9c8e96e4ff3927a48e5d0389937ad847c1b313b2d50edffef035cdfe18ccc402204307afba5a45aa2df3504e2d19e27b4ddb7c0b3a2c9f027bc658213e05d284e1010100fdffffff54073a38f6810e2df1d5f618ea1c6f304510e47a9901f1660c57bdb8dd6e25bd000000004b483045022100a42a8d2a29bf7d5d719363e222e5fd2bb5dc39b88bd411054ac5efc08a91a583022016362fd43e797f65530550d2ff4e16fd4226ac8ec8aba8232e00bb888785cde4010100fdffffffa671657e815be305aa65867ea96e0df76b3a6ba0f76ac4c46c353db1539492a1010000004b483045022100a022a65c6b5d7975dc4a908d9609eab81285cf02385221f612c668015133ca3f0220685565f45da55665488d340725af2272eaf0ebace667da3abae9d872f97c5dc4010100fdfffffff1a9960e1535bffed89f39d35633a0a101e15fd14134ae2f01d12ceaa5526c20000000004b483045022100e56c37899fa196ee44e36b7058f0f5614ec7a39394c87343e4ec8cce6fb7edb1022060d5a5bc32fd319fe29a6289a1c5a3fa7ab116458eb178bd4d5452d5a3d787c2010100fdffffff5428d5b891f26c68216b9f2e24509e3f850a1d02b785be4951ac6b52c6c203cd000000004a47304402202628b26b8d71cb3fea7babdfa4436681840af85699010ecc5364b75faec7e23602205bb3678f43c5725c815f64516eb73c94b027fbe93b0e2f16b5886b3b44939b62010100fdffffffc950908e94af4fb542e68b8f5486f98fbab4b79728e23640af42c5d997969d15010000004a47304402205639aff74dfbcf94381f51d3a5e06c2ca6b2667a7818e445f68e7a9e80043f760220549d3ceb1a19e9ed3d59ed79f68be9746e0422240247006b1d3b6012a13f407e010100fdffffff01e083b41bd3f1c78b4bb8d9ad44f76ba835646151ed20ed7702aeec9c730a1d000000004b483045022100a780da0591835c9228073582020aaa089ee8962a7a2a39091cb384ded0d80905022068bf1091d09326745ec544e1bd9fd856e30d1d394503f5ef367f1d6f7e0a3c70010100fdffffffd7b5033b444daad4950366855184e83c4125a6323c83c9e1fba3b64e6d332cdc010000004b48304502210083147402aff6d0682f4282199d3ee30b690c603d3b35f313c72c9a5b8d36630d02206549757777cffbb9becbedf31f304ba3c6e67d2d7820a85dcc126b81ae853d23010100fdffffff738f88b9ed5be2a59eb23d1042b6b645def6f7dcd7053ed8e6681657fe2668af010000004b4830450221008236806f3e8d23154e413f9848c1542673a7e8a700cf8a5cda2fe3091d82c57302200aec446be2fc7e3d19f819849632d97462f10f3a26190ada025ae546ea06981f010100fdffffffbec4f8414a0c3cc33ec64f0c0a08d422b1b885b320de4c59f7e487937147fba1010000004b483045022100c13a908fe1565ab752f1a6a2b6b37a2e2c154a1df1017781bf03f3f7a6fd57130220079670f3b1f1e79e7b6ac44c305fc4d3dc9632799bbbe30a096b3e767a79d6b4010100fdffffff738f88b9ed5be2a59eb23d1042b6b645def6f7dcd7053ed8e6681657fe2668af000000004a473044022059ce8dd4d05eb8eb037f3d2317b215a7e7c040ef8f182b88e106042100892e4002205de259afa7624b86a3ec427cd6b39192a5814190c1d09ebc27043d3718c39c00010100fdffffff73700f0e896a4071a4fabd6371c5ddf42744136d2e7cf5f09c7063a6817d9f1c000000004b4830450221009aca2aac4cefb2b168194a9d5396d39d531f50f2c9b4eee02ef28e829d1e1e470220493eba6f56a50fe6282b127f16946c7bd6525bb37143b06d4ca1e4469c803a0c010100fdffffffc8a41808b844520e46a7a9d5dc58ffd13941d013979916226b6a39beacf8feba000000004b483045022100e980ac919e371de45e107352b857c595b2bb03e1dee86fde1050eb37f66004eb02201089a4b359a08e7160bbe9d9beae86251f92ef3f02ac094cc2e1fe3135026b7a010100fdffffffb38c1c912373ab6b5ade53f634877fa3a851362e7e6d778b11e37b6b08248d34070000004b483045022100aaeb5f185653c51b9a88583fb1211ab4c4c75ad4d9a6bffb1a87fbf6b59d075402205fad99e1e0e00a46c7f3c610901f8e44ebc03e446da1a95887bcb88caa5f750c010100fdffffffc0f3a6705506403e2c1b36cff10b52765645fd25a1b07fd5405d93a1bf885981000000004a47304402205764f36473509eb6fa0e3239f6140a26b03410a3c9723e531157f0128bca75f0022071d2b16599217e5cd22727cacb9797f20f5522a3055af5b2f2884111b70deeb9010100fdffffffbee4a2188b524b97785b4b4123c3d0e0d2a8068387e7ca10e81b3004aef52bd7000000004b483045022100ab3872df421402b67754e3b56b92fc9f24faeea3aa8d7aa16e6272fcd11ace91022072812d10d21fe30ff951fae96e2bf7081fe7bd6eaebc3501dce7cd757ec67fdb010100fdffffff2887aee1bd96208b2bd05b43e17d4fc44c4db04834ea3f7472f7391ec55328e1120000004b483045022100b236d0f0c00b601cbcfa8367f890bbb5de62e29d5fa7d42649f03342edc1c5050220543ff8bbdaf7ad71eecf48b4b60984df8d95680fd67d756dece37256a2e53730010100fdffffff1f871d4a2d45ec14af5413af5aa0bdf658362aa94fe123fce3bdc609e6a1a5fc000000004a4730440220366773cf00b63f268bf95d8a2bde5a4a0a4ad43ff4709a611679fda37d5abc8c0220128f0009cfd40fd74ed698e589de6b5e20a43afcf0a4c497fc86bda048c4462f010100fdffffff6bb7ea26b9bdf4ae5d34d79c3e2e0d0c9f3f8b851150985125035605f8e1a288000000004b4830450221008003628c014d7130f6ea40754a98deb90b3fcf0aaff6a568c6a1c9b671cd3e760220249bb59d35fa56531e186461270cd3ea41ae8dcc985ff6e73b0bb91d592c4c16010100fdffffff08d90ec68db6646b07f61d5ee87d223deb8331594d0238c017f22a488835c39d000000004b483045022100fd53f61e54b108dc05527724ff71afed67d6d210b8afa4271e951f95130092fa02201320b754b012712feb157e97d1713e4977de81f5a56e2c97e5535d057b9cbf18010100fdffffff7b7b86363515b0f4f07a266e83e9f33aad0a34225e900c49ac6094d1154e1fec010000004a47304402204fd96c861d3a3d83f91a5394c6df933db7462b4eba6a6125c3051518be5844f802204238293ecf8a779300093de72756d295dba3758944d472d594b27567481e147c010100fdffffffa56afd6e38a987777a1ebcbec0430d94661f39941231eacf64a038c8730ed23b010000004a47304402203d1a853f8518173806a4f9cdf9b50f87b8912085737247b9d75afc6596ae44d7022044235843dd555ec08adcd85a548484b8c98490be49e507d525c5ee98d33c470b010100fdffffff2aa5e50dc9c51bd94d1065395505aae4f22b4717ef4729bc249183c3be5509fd00000000171600149f7fd096d37ed2c0e3f7f0cfc924beef4ffceb68fdffffff4b343ce2ebcd43be4f21d79f93ab4d20497fece1ac57c8b94f882698363e295600000000171600149f7fd096d37ed2c0e3f7f0cfc924beef4ffceb68fdffffff3dcf24194b9dd3f252f9544f236dfa6711349f409d0f68457e92cf29f9a7c3e7000000004b4830450221009f0df211d72443be2f60394de021513e74b74248e6ef57e8c9529736dd1ab61502202ab62e0a21dd75cad9bd866aaa8b9a5cca49156d6590794361301c8e6e3e033c010100fdffffffdb9ec8af478e3e35722db1ad1a21f844be7c0ba1cfc37243e3befe30f4b007ab000000004a473044022011d29748eccb00a163d31ca72de7a224905d1aa99eb456b3c33afd3f9820895d0220754131cd003af55462aab3d921beacab92253a8b80d032f52795e00fd50e7085010100fdffffff4eadceace3ede8948e8ca6bb6b439790f3c70591edae53f685196d3b5f3ec879020000004a473044022018853567387850ae6806a899e07d42875ba91a18027bd37b22a2956d72d5438002201f912918e27a871b310c1985517fe927104076190219cf97658d1fcbb9cffb76010100fdffffff8e00fd85b96618944c054eb71f14002d88a4aa0c4414fe3086966486f12ea85d020000004b483045022100c4f2c4e40291d59f911a73577ba5fce075ad9f706bbe0c462156c9bfd75a2bbf02201e8311d5311b4ce0d9eebb381e356657714378389c89814a4154d3d3de88dce9010100fdffffff09eb01207eec33aa780dbb3a92406c7df4d672a68cf4ef2aeea014e5de6eab04010000004a4730440220259f521ca028046b03957d49586352b55967f1ec43c133845dac2b6ac7cbdbbf0220523af29e56dc887dc0de794181eca29e009b53a744f443f6bf3618f5adce081f010100fdffffff016b761a160000000017a91480aa3c461c7633fc1ee1ce01397bf863330ce6c0870000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247304402203945c2e0d1784f2c2e482182d2ebf64f718ceed37a8a3283b683368f78fcb248022052bb37761ecb88f71cc3a83aecc99ca626f1157f3952e7ff332bd1856850299501010002483045022100d0fcc7854bc85b5edfb0c6910148a29fdc6a5b45c26c52a20d45b8cb4e310a2d022013e4f10363d58db4bb3ba3b0f5b04bfaf35a90a7fc1a858fcfe0731a441569f4010100000000000000000000","utxos":[{"tx_hash":"b2d1b5999a06596c21f46792ca3ed3a5bf65b81f30c09b26c1a1419b2f101434","vout_index":1},{"tx_hash":"d6915bc2b092e35a6df2e5190709f777313e6c74f5ea3b929276f6ae316a1d4a","vout_index":1},{"tx_hash":"3262eb956deb6e66d113cc14b20e7d0fcc00ac58a94c032ec4a2a7fbaa5fb52a","vout_index":1},{"tx_hash":"f3fb03285e6ddfc0c66e97b48565e11a1993bc38b3748b467434b8543631aaaa","vout_index":1},{"tx_hash":"14cc96b6d9fdba483ab297f6dd7ead3ac271b6074808ab3ade84c4a0d40a92db","vout_index":1},{"tx_hash":"96f9bf3534e5e0c4f65d9ace93f01fd9601660d145fc69c0a301dc673c903865","vout_index":1},{"tx_hash":"7aabe144e7d083302a9956d5fc927fa166187b6345277018233daab18e5dab82","vout_index":1},{"tx_hash":"73db04ca6848820803b530513b3432a0018defa6c80e9713703f8915a6885719","vout_index":1},{"tx_hash":"79b6661af25399593a24efb2c60b4fb9da795045bf115c9021224e92c6a9fa56","vout_index":1},{"tx_hash":"e801fef675aa45cdfea623cd24d0a5c37ab8b0a32e6323c319472936ac63ad32","vout_index":1},{"tx_hash":"352275bb5ea9153779c4acb62d8a1919d39618a412e587e5137fad30287da699","vout_index":1},{"tx_hash":"a8ac8efe4ad653642aea6e375ea9a0f06a0303308445d35970afe9df3a920d1e","vout_index":1},{"tx_hash":"c29b4529c43637c3c3cb86ff4d32980a055a8a58f8b0ff83abfac924bb7d5a53","vout_index":1},{"tx_hash":"652367e4b5879c2707eef5a27c82416102669f7ec784d63141962a4a1c73365d","vout_index":1},{"tx_hash":"5d58a62cb677727e1506aaf2ef5b492cee8995fb294c0c625c541907529d4097","vout_index":1},{"tx_hash":"6ef23e01b47245ea43481e9db8e1095417591067702a2221fb3cf4f036b156bc","vout_index":1},{"tx_hash":"19adadbbec36fc2c14d0965da5600c099b3f4a8ec19d549d48853d4ca439abf4","vout_index":1},{"tx_hash":"0f86ef78c86b565b8ffe9bccebcb609c89f55f43e2adbc4b88079898b3baecc0","vout_index":1},{"tx_hash":"220e99b4640f22dc561c3a9f5c92e0a2452a4912b7e75bbe957c1cb86cf6ef32","vout_index":1},{"tx_hash":"7e209e6d5e283ac80078586c3ce85ef74f7c4270d4e036cceef33daf0ff31307","vout_index":1},{"tx_hash":"325f9df0c9cac98e30b02ce9e35d02eda8f15be9f89cb302454a2bb6c6bc9aeb","vout_index":1},{"tx_hash":"84dc293f4d6afaa417978630e80cba6a29d3b057ab25e82b2010a4d2e39ef18c","vout_index":1},{"tx_hash":"2d4621ddcfdc7eae231007b14856688f00b248da7447d85f7b23297c7ac118fb","vout_index":1},{"tx_hash":"c73eace587dbde385675efe97604a4d1c04b84874e48b285bfd4eb344491dfa7","vout_index":1},{"tx_hash":"bd256eddb8bd570c66f101997ae41045306f1cea18f6d5f12d0e81f6383a0754","vout_index":0},{"tx_hash":"a1929453b13d356cc4c46af7a06b3a6bf70d6ea97e8665aa05e35b817e6571a6","vout_index":1},{"tx_hash":"206c52a5ea2cd1012fae3441d15fe101a1a03356d3399fd8febf35150e96a9f1","vout_index":0},{"tx_hash":"cd03c2c6526bac5149be85b7021d0a853f9e50242e9f6b21686cf291b8d52854","vout_index":0},{"tx_hash":"159d9697d9c542af4036e22897b7b4ba8ff986548f8be642b54faf948e9050c9","vout_index":1},{"tx_hash":"1d0a739cecae0277ed20ed51616435a86bf744add9b84b8bc7f1d31bb483e001","vout_index":0},{"tx_hash":"dc2c336d4eb6a3fbe1c9833c32a625413ce8845185660395d4aa4d443b03b5d7","vout_index":1},{"tx_hash":"af6826fe571668e6d83e05d7dcf7f6de45b6b642103db29ea5e25bedb9888f73","vout_index":1},{"tx_hash":"a1fb47719387e4f7594cde20b385b8b122d4080a0c4fc63ec33c0c4a41f8c4be","vout_index":1},{"tx_hash":"af6826fe571668e6d83e05d7dcf7f6de45b6b642103db29ea5e25bedb9888f73","vout_index":0},{"tx_hash":"1c9f7d81a663709cf0f57c2e6d134427f4ddc57163bdfaa471406a890e0f7073","vout_index":0},{"tx_hash":"bafef8acbe396a6b2216999713d04139d1ff58dcd5a9a7460e5244b80818a4c8","vout_index":0},{"tx_hash":"348d24086b7be3118b776d7e2e3651a8a37f8734f653de5a6bab7323911c8cb3","vout_index":7},{"tx_hash":"815988bfa1935d40d57fb0a125fd455676520bf1cf361b2c3e40065570a6f3c0","vout_index":0},{"tx_hash":"d72bf5ae04301be810cae7878306a8d2e0d0c323414b5b78974b528b18a2e4be","vout_index":0},{"tx_hash":"e12853c51e39f772743fea3448b04d4cc44f7de1435bd02b8b2096bde1ae8728","vout_index":18},{"tx_hash":"fca5a1e609c6bde3fc23e14fa92a3658f6bda05aaf1354af14ec452d4a1d871f","vout_index":0},{"tx_hash":"88a2e1f80556032551985011858b3f9f0c0d2e3e9cd7345daef4bdb926eab76b","vout_index":0},{"tx_hash":"9dc33588482af217c038024d593183eb3d227de85e1df6076b64b68dc60ed908","vout_index":0},{"tx_hash":"ec1f4e15d19460ac490c905e22340aad3af3e9836e267af0f4b0153536867b7b","vout_index":1},{"tx_hash":"3bd20e73c838a064cfea311294391f66940d43c0bebc1e7a7787a9386efd6aa5","vout_index":1},{"tx_hash":"fd0955bec3839124bc2947ef17472bf2e4aa05553965104dd91bc5c90de5a52a","vout_index":0},{"tx_hash":"56293e369826884fb9c857ace1ec7f49204dab939fd7214fbe43cdebe23c344b","vout_index":0},{"tx_hash":"e7c3a7f929cf927e45680f9d409f341167fa6d234f54f952f2d39d4b1924cf3d","vout_index":0},{"tx_hash":"ab07b0f430febee34372c3cfa10b7cbe44f8211aadb12d72353e8e47afc89edb","vout_index":0},{"tx_hash":"79c83e5f3b6d1985f653aeed9105c7f39097436bbba68c8e94e8ede3accead4e","vout_index":2},{"tx_hash":"5da82ef18664968630fe14440caaa4882d00141fb74e054c941866b985fd008e","vout_index":2},{"tx_hash":"04ab6edee514a0ee2aeff48ca672d6f47d6c40923abb0d78aa33ec7e2001eb09","vout_index":1}]}

**Comment by liuywme** [comment]
from_addr: 1FYMZEHnszCHKTBdFZ2DLrUuk3dGwYKQxh

**Comment by ToluAgabi** [comment]
@liuywme 
Any luck?

**Comment by MarcoFalke** [comment]
Not sure what your question is here. If you are asking what the function is that returns this error code, it is probably this one:


```
bool static IsCompressedOrUncompressedPubKey(const valtype &vchPubKey) {
    if (vchPubKey.size() < CPubKey::COMPRESSED_SIZE) {
        //  Non-canonical public key: too short
        return false;
    }
    if (vchPubKey[0] == 0x04) {
        if (vchPubKey.size() != CPubKey::SIZE) {
            //  Non-canonical public key: invalid length for uncompressed key
            return false;
        }
    } else if (vchPubKey[0] == 0x02 || vchPubKey[0] == 0x03) {
        if (vchPubKey.size() != CPubKey::COMPRESSED_SIZE) {
            //  Non-canonical public key: invalid length for compressed key
            return false;
        }
    } else {
        //  Non-canonical public key: neither compressed nor uncompressed
        return false;
    }
    return true;
}
```

**Comment by peterwillcn** [comment]
from_addr:  1HT7xU2Ngenf7D4yocz2SAcnNLW7rK8d4E same issues
