### ISSUE TITLE
Issue closed with no comment

### ISSUE THREAD

**Issue by blakelapierre** [bitcoin/bitcoin#21094]
https://github.com/bitcoin/bitcoin/issues/21093

sad

**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode. Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
