### ISSUE TITLE
problematic error reporting in sendtoaddress

### ISSUE THREAD

**Issue by mikegogulski** [bitcoin/bitcoin#211]
```
bitcoin@btcserver:~/bitcoin-0.3.21/bin/32$ ./bitcoind sendtoaddress 16bRQcbr1VcxxxxxZQxqGhi242eL 0.2 
error: {"code":-4,"message":"Error: This transaction requires a transaction fee of at least 0.01 because of its amount, complexity, or use of recently received funds  "}
```

Reminds me a bit of "Password incorrect or domain controller unavailable".

My "Errors and Error Messages: Handbook for Dungeon Masters" guidebook says:

§16(a)(vii): "Each and every error message shall describe the one, single, sole, only and unique error condition generating the message."

§16(a)(xix): "No error message shall contain any of the words 'or', 'nor', 'some', 'any', 'several', 'either' or 'neither', nor any of the collocations 'one of', 'some of', 'one or more of', and so on."

**Comment by laanwj** [comment]
As it is a bit absurd to have an issue about a message change open for 5 years, I'm going to close this issue. I haven't ever heard anyone else complain about this message. And yes, it's still there.
