### ISSUE TITLE
exited on signal 6 (core dumped)

### ISSUE THREAD

**Issue by nuxbsd** [bitcoin/bitcoin#21108]
**OS:** FreeBSD 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64 
**CPU**: AMD Phenom(tm) II X2 550 Processor (3100.07-MHz K8-class CPU)
**RAM:** real memory  = 5368709120 (5120 MB),  avail memory = 4874006528 (4648 MB)
**Version**: bitcoin-daemon-0.20.1_3
**Error:** /var/log/messages: exited on signal 6 (core dumped)
**Error:** /var/log/bitcoind.log: ReadRawBlockFromDisk: Block magic mismatch for FlatFilePos(nFile=0, nPos=6496176): c3291407 versus expected f9beb4d9

Hello, 
I share my experience of what I did and I would like to understand what this error is due to.
I got the entire blockchain on a hard drive that I have placed in the root at **/nfs2/blockchain**.  (this is not a nfs resource)
All the blocks were fine in this directory.
The problem was that I was running the bitcoind service as root.
Everything was going well.

I then configured the service to run as a bitcoin group and user.
I performed a **chown -R bitcoin:bitcoin /nfs2/blockchain**
I restarted the OS and the service ran for a few hours to give me the errors as indicated above.
I then restarted the service but the error always occurred after a few hours of execution.
Then I completely deleted the contents of the /nfs2/blockchain directory
I added the parameter to the bitcoind.conf file:  **debug=libevent, qt** 
I restarted the machine and since January 30 the service has not stopped.

I would like to understand so as not to have to take over the entire blockchain again, which is what it is recommended to do.
Why when we change the user do we have this type of error?
What should be done to stop having this type of error?
What is recommended to do when the machine suddenly shuts down?
Thank you.

**Comment by laanwj** [comment]
> Error: /var/log/bitcoind.log: ReadRawBlockFromDisk: Block magic mismatch for FlatFilePos(nFile=0, nPos=6496176): c3291407 versus expected f9beb4d9

This is an assertion hit due to disk data corruption. Usually this is a hardware problem (faulty RAM, overheating CPU, etc), though it might also be a combination of operating system / file system that has an edge case that is not handled (e.g. around flushing/synchronization).

It's really hard to say.

For what it's worth I run a node on FreeBSD and have never seen this.

**Comment by nuxbsd** [comment]
Thank you for your answer, 

I don't have this type of error at all now. 
The service has not stopped. 
The only errors I have are:
- **socket send error Broken pipe (32)**
- **socket error accept failed: Software caused connection abort (53)**
- **socket select error Bad file descriptor (9)**

Error **socket send error Broken pipe (32)**  is quite repetitive.

**Comment by nuxbsd** [comment]
Sorry, wrong button.

**Comment by laanwj** [comment]
>    socket send error Broken pipe (32)
>    socket error accept failed: Software caused connection abort (53)
>    socket select error Bad file descriptor (9)

Those are normal, remember that this is P2P software connecting to the internet and the internet is a messy place. Connection errors happen now and then.

So it's nothing to worry about. Closing this.
