### ISSUE TITLE
Watchonly descriptor wallets classifying funds as `mine`, are "spendable"

### ISSUE THREAD

**Issue by niftynei** [bitcoin/bitcoin#21104]
**Expected behavior**

I'd expect funds in a watchonly wallet to be shown as "watchonly", be unspendable.

**Actual behavior**

Funds are shown as "mine" in getbalances, can be "spent" (sendtoaddress completes without error, however transaction is unspent and fails to enter mempool. Balance is incorrectly decremented)

**To reproduce**

Make a watchonly descriptor wallet.

```
bitcoin-cli createwallet w2 true true "" true true false 
```

Load up a descriptor that's got some funds on it.

```
$ bitcoin-cli -rpcwallet=w2 importdescriptors '[{"desc":"wpkh(tpubD6NzVbkrYhZ4Wh1z2cvkzQsM12k9kvyMMrGXi7rdk5eyUYUFND1qhB1zEZ3pJwSSSGLYsKfZLKNvs4L7oqNb8vJj3zJTvxMRCKWsNhX9JXQ/*)#86kup682", "timestamp":"now","active":true,"range":100}]'

```

See the balance.

```
$ bitcoin-cli -rpcwallet=w2 getbalances
{
  "mine": {
    "trusted": 3.00000000,
    "untrusted_pending": 3.00000000,
    "immature": 0.00000000,
    "used": 0.00000000
  }
}
```

Spend the balance.

```
$ bitcoin-cli -rpcwallet=w2 sendtoaddress bcrt1qnk09yy5ayyhwvfydg2x58zwy443pjx5uesg9gw 3.0 "" "" true
90bce182f476376e6cf3552e234c686ce5bfee4d47739081f5cba90de374156b
```

See the balance update.

```
$ bitcoin-cli -rpcwallet=w2 getbalances
{
  "mine": {
    "trusted": 0.00000000,
    "untrusted_pending": 0.00000000,
    "immature": 0.00000000,
    "used": 3.00000000
  }
}
```

Not in the mempool though

```
$ bitcoin-cli getmempoolentry 90bce182f476376e6cf3552e234c686ce5bfee4d47739081f5cba90de374156b
error code: -5
error message:
Transaction not in mempool
```

**System information**

Bitcoin Core version v0.21.0

**Comment by fanquake** [comment]
cc @achow101

**Comment by danben** [comment]
I've started reading wallet code in order to hopefully fix this, but if it is or becomes urgent then someone who already knows how should do it instead.

**Comment by sipa** [comment]
I believe that the fact that the funds are listed as spendable is expected (descriptor wallets don't distinguish between watchonly and real funds; if you want separate balances, create separate wallets). I can't explain why sending doesn't error, or reduces available funds, though.

**Comment by sipa** [comment]
ping @achow101

**Comment by achow101** [comment]
The funds being shown as spendable is intended behavior. However `sendtoaddress` (and `sendmany`) should not actually be creating a transaction when private keys are not available. #21201 should fix this.

**Comment by sipa** [comment]
@achow101 What if you have a wallet that doesn't have private keys disabled, but has a descriptor without private keys (or with insufficient private keys) imported. Is there a risk that sendtoaddress would still "succeed"?

**Comment by achow101** [comment]
@sipa it shouldn't be possible to import a descriptor without private keys to a wallet with private keys enabled.
