### ISSUE TITLE
Unable to build or insufficient instructions to build

### ISSUE THREAD

**Issue by josephkniest** [bitcoin/bitcoin#21132]
According to the build instructions for *nix the first step is to execute a bash script, but this fails with the following error. There are missing steps in the documentation to get a fresh ubuntu box building the exchange software. This is on OS "Ubuntu 20.04.1 LTS" with gcc version "gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"

root@058f87446885:/bitcoin# ./autogen.sh
Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:8:   its definition is in aclocal's search path.
/usr/share/automake-1.16/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'                                                                                                 
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.16/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests                                                                                              
/usr/share/automake-1.16/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.16/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
Makefile.am: error: C++ source seen but 'CXX' is undefined
Makefile.am:   The usual way to define 'CXX' is to add 'AC_PROG_CXX'
Makefile.am:   to 'configure.ac' and run 'autoconf' again.

**Comment by fanquake** [comment]
My guess  is that you haven't  installed all of the [dependencies listed in the build doc](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions). I can create the same output as you're seeing, in a new Ubuntu Focal Docker container, if all I've apt installed is `git` & `autoconf`:
```bash
root@7d9c01515d89:/bitcoin# ./autogen.sh
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:8:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
/usr/share/automake-1.16/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.16/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.16/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.16/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
Makefile.am: error: C++ source seen but 'CXX' is undefined
Makefile.am:   The usual way to define 'CXX' is to add 'AC_PROG_CXX'
Makefile.am:   to 'configure.ac' and run 'autoconf' again.
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
```

Installing all of the build dependencies will likely fix your issue:
```bash
apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
```

**Comment by josephkniest** [comment]
That certainly got me a bit closer. Next up executing
"./configure"

leads to

"configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for BDB wallet support (--without-bdb to disable BDB wallet support)"

I ran "./configure" right after running "./autogen.sh" without error.

**Comment by fanquake** [comment]
Well if you need BDB wallet support, you should be following [the instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#berkeley-db) in the same build-unix documentation to install bdb. If you don't need it, pass `--without-bdb`.

**Comment by josephkniest** [comment]
Interesting. After running "./contrib/install_db4.sh `pwd`" I get the same error after configuring the make target
"./configure"

**Comment by MarcoFalke** [comment]
You'll need to follow the instructions that were printed once you ran the install_db4.sh script

Alternatively install `libdb++-dev` and pass `--with-incompatible-bdb`. See https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions

**Comment by jonatack** [comment]
Here is a guide that may be helpful:

https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests
