### ISSUE TITLE
The button "Create new receving address" is gryed out

### ISSUE THREAD

**Issue by Oberreiter** [bitcoin/bitcoin#21153]
**Expected behavior**
In the past, I was able to create a new receiving address with the button on the receiving tag. 

**Actual behavior**
Since I don't know when the button is grayed out. (I didn't receive Bitcoins for some years now.) Regardless of the Label, Message, or Checkbox values.
When I create a new Wallet I can create new addresses. 

**To reproduce**

I'm not able to reproduce this behavior with another Wallet.

**System information**

I was on version 0.18. So I upgraded to version 0.21. No change. 

The System is a PC with Windows 10 with an HDD for DB Storage.

I attached the debug.log shortened to on start and stop of the application.

![screenshot_20210211_123814](https://user-images.githubusercontent.com/12497441/107633654-ae346500-6c68-11eb-95b5-cf3f3c5a45b1.png)
[debugDefault.log](https://github.com/bitcoin/bitcoin/files/5965013/debugDefault.log)

**Comment by hebasto** [comment]
Is it the same as https://github.com/bitcoin-core/gui/issues/105?
Does #20230 fix it?

**Comment by Oberreiter** [comment]
Closing and reopening the wallet didn't change the behavior.
The console command "getnewaddress" returns the Error: This wallet has no available keys (code -4)
so I tried "keypoolrefill" no change so far.

**Comment by Oberreiter** [comment]
If I try "keypoolrefill 100" I get "Error refreshing keypool (code -4)"

**Comment by Oberreiter** [comment]
I'm trying to do a rescan and see if it solves the problem.
https://bitcoin.org/en/release/v0.15.0#rescanning-with-encrypted-wallets

**Comment by Oberreiter** [comment]
The rebuild didn't change the "bug".

**Comment by achow101** [comment]
What is the result of the `getwalletinfo` command?

**Comment by Oberreiter** [comment]
{
  "walletname": "",
  "walletversion": 169900,
  "format": "bdb",
  "balance": x.xxxx,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 41,
  "keypoololdest": 1613118171,
  "keypoolsize": 0,
  "keypoolsize_hd_internal": 0,
  "unlocked_until": 0,
  "paytxfee": 0.00000000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false,
  "descriptors": false
}

**Comment by achow101** [comment]
Try using the `upgradewallet` command. This seems to be a similar situation to #20871 where your wallet version indicates it should support HD, but there is no HD seed so it doesn't actually.

**Comment by Oberreiter** [comment]
`upgradewallet` did the trick.
thx a lot.

**Comment by OnlyFratelloD** [comment]
Hi... I have Bitcoin Core Version v0.21.0 installed and face this problem also with Bitcoin Knots. Any hint to resolve the problem would be greatly appreciated. Thanks!

**Comment by hebasto** [comment]
@OnlyFratelloD 
> Hi... I have Bitcoin Core Version v0.21.0 installed and face this problem also with Bitcoin Knots. Any hint to resolve the problem would be greatly appreciated. Thanks!

https://github.com/bitcoin/bitcoin/issues/21153#issuecomment-777428763 or https://github.com/bitcoin/bitcoin/issues/21153#issuecomment-778294465

**Comment by OnlyFratelloD** [comment]
Hebasto, wow - thanx for that swift response.
upgradewallet tells me: "already at latest version. Wallet version unchanged."
tried v0.21.0rc5 - problem does still exist.

**Comment by OnlyFratelloD** [comment]
v0.20.1 works... what would you recommend me to do now?
