### ISSUE TITLE
Bitcoins im jahr  2009 hier angelegt   komme nicht mehr  drauf zu

### ISSUE THREAD

**Issue by sb-immo** [bitcoin/bitcoin#21174]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by sb-immo** [comment]
Hello, in 2009 I bought BTC and saved it to the Bitcoin core wallet, I still have the SID ID screenshort, etc. However, I can no longer access the account. It can be that I have a new PC .. or some other reason .. I ask for help

**Comment by MarcoFalke** [comment]
Bitcoin Core doesn't have a "SID ID". Did you backup the `wallet.dat` or the data directory?
