### ISSUE TITLE
Create new receiving address greyed out

### ISSUE THREAD

**Issue by smallcuber** [bitcoin/bitcoin#21179]
**Expected behavior**

To be able to see the wallet address

**Actual behavior*
 Not able to see the wallet address since the create new receiving address button is greyed out.
![image](https://user-images.githubusercontent.com/12606285/107907453-bcf97100-6f21-11eb-8ab9-569af7ee5202.png)

**To reproduce**
Bitcoin Core version v0.21.0

00:01:08
￼
upgradewallet

00:01:08
￼
{
  "wallet_name": "",
  "previous_version": 169900,
  "current_version": 169900,
  "result": "Already at latest version. Wallet version unchanged."
}

**System information**

**Comment by jarolrod** [comment]
What is your system? 
Did you build from source or grab a binary?
Do you have a wallet loaded?

Note: If you chose `Make Blank Wallet` or `Disable Private Keys` during the wallet creation dialogue, then `Create new receiving address` would be blank because there are no private keys.
