### ISSUE TITLE
download hash does not match ?

### ISSUE THREAD

**Issue by rtoledo2002** [bitcoin/bitcoin#21172]
bitcoin-0.21.0-win64-setup.exe   hash is not the same as  SHA256SUMS.asc
 I expected  1d0052c4ce80227fb6d0bc1c4e673ba21033e219c1f935d25f130ef7f43360d4  bitcoin-0.21.0-win64.zip  as per what's inside the  sha256sum.asc file.

 and I get this :  F:\Downloads>certUtil -hashfile bitcoin-0.21.0-win64-setup.exe SHA256
SHA256 hash of bitcoin-0.21.0-win64-setup.exe:
54050748ef4d4f000ea1ece472491b3e5fd546efc74ed52119354b2893f6624b
CertUtil: -hashfile command completed successfully.

 every time

0.21.0-win64-setup.exe  downloaded 02/13/2021 

 win10 64 pro insider preview build 21301.rs_prerelease.210123-1645

  JUST WORRIED  is it legit  got it from https://bitcoincore.org/en/download/  and  later at https://bitcoin.org/bin/bitcoin-core-0.21.0/   just to double check

**Comment by laanwj** [comment]
```
$ sha256sum bitcoin-0.21.0-win64-setup.exe
54050748ef4d4f000ea1ece472491b3e5fd546efc74ed52119354b2893f6624b  bitcoin-0.21.0-win64-setup.exe
$ gpg < SHA256SUMS.asc |grep bitcoin-0.21.0-win64-setup.exe
54050748ef4d4f000ea1ece472491b3e5fd546efc74ed52119354b2893f6624b  bitcoin-0.21.0-win64-setup.exe
```
Your exe has the correct hash. You are comparing against the hash of the **.zip** which is `1d0052c4ce80227fb6d0bc1c4e673ba21033e219c1f935d25f130ef7f43360d4`.
