### ISSUE TITLE
Github <> Slack integration

### ISSUE THREAD

**Issue by lukerQuant** [bitcoin/bitcoin#21184]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can you add the slack github integration to this repo (https://slack.github.com/), so that changes can be easily tracked in slack

**Describe alternatives you've considered**
I understand that email notifications can be used, but in my opinion slack notifications provides easier team organisation.

**Additional context**
None

**Comment by jonatack** [comment]
Hi @lukerQuant, this exists, see https://bitcoincore.slack.com

**Comment by lukerQuant** [comment]
This is the bitcore core slack group? ... We are looking for bitcore core subscription notifications (e.g. new pulls, new releases etc) into our company slack using /github subscribe, see customise your notifications: https://slack.com/intl/en-gr/help/articles/232289568-GitHub-for-Slack

**Comment by laanwj** [comment]
I think that's a valid point it needs some webhook setup to get the notifications there.

**Comment by lukerQuant** [comment]
Ah ok, I thought it was simply adding the slack app to your repo. It is nice when it works. Our company works with different permissionless and permissioned DLTs and only a few DLT node repos currently have this type of integration. As an example, if you add the github app to your slack, you can type "/github subscribe corda/corda" to get corda repo updates. It would be nice to get bitcoin core notifications in the same way :-)

**Comment by MarcoFalke** [comment]
I don't think this will work. It will need a maintainer to sign up in your company's slack and then activate the app through that. (At least that is what I had to do to setup on the bitcoin design slack).

**Comment by lukerQuant** [comment]
Would a maintainer clicking on this https://github.com/apps/slack/installations/new , then selecting bitcoin not work?

**Comment by MarcoFalke** [comment]
That button is asking for "write access to deployments, issues, and pull requests". I don't think we want untrusted third parties rewrite our repo.

**Comment by lukerQuant** [comment]
Ok fair enough, annoying that it cannot be limited to read only then

**Comment by MarcoFalke** [comment]
Closing for now

**Comment by laanwj** [comment]
> That button is asking for "write access to deployments, issues, and pull requests". I don't think we want untrusted third parties rewrite our repo.

Agree that is too much. If you have tooling where it's only a matter of adding a notification webhook (this is how the IRC notification through [ghi](https://github.com/gkrizek/ghi) works) I'm open to it but giving away *any kind* of permission to our repository is out of the question.
