### ISSUE TITLE
Link to Bitcoin original white paper is broken

### ISSUE THREAD

**Issue by sandeep1995** [bitcoin/bitcoin#21183]
**Expected behaviour**

The mentioned original whitepaper link in readme should work

**Actual behaviour**

https://bitcoincore.org/bitcoin.pdf lands to `Page Not Found` page

**To reproduce**
Go to https://bitcoincore.org/bitcoin.pdf

**System information**
Any browser, any os

**Comment by rafid059** [comment]
duplicate https://github.com/bitcoin/bitcoin/pull/20976
