### ISSUE TITLE
Add Ranges to to Output Descriptors

### ISSUE THREAD

**Issue by prusnak** [bitcoin/bitcoin#21199]
[Output Descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#multisig) do not contain support for ranges.

BIP44/49/84 account uses two chains (for receiving addresses and for change addresses).

Having possibility to express ranges would allow us to capture the essence of BIP44/49/84 accounts in one Output Descriptor, e.g.

```
pkh([d34db33f/44'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/[0-1]/*)
```

(note the `[0-1]/*` at the end).

**Comment by Rspigler** [comment]
Concept ACK.  Would fix https://github.com/bitcoin/bitcoin/issues/17190

**Comment by sipa** [comment]
Conceptually, descriptors describe a list of scriptPubKey (along with information for spending from it). If you write xpub/[0-1]/*, do you mean:
* The list xpub/0/0, xpub/1/0, xpub/0/1, xpub/1/1, xpub/0/2, xpub/1/2, ... (just interleaving the lists)
* Changing descriptors to effectively be a description of multiple lists?
* A way of writing two descriptors; perhaps one which is implicitly imbued with the meaning "payment addresses" and a second with meaning "change addresses"?

The first, if there is a use case for it, would be fairly simple and fit will in the current design. The others are more invasively, and probably not desirable in all places were descriptors are used.

**Comment by prusnak** [comment]
Ah, I didn't know about https://github.com/bitcoin/bitcoin/issues/17190 - closing as duplicate of https://github.com/bitcoin/bitcoin/issues/17190
