### ISSUE TITLE
guix: gnutls-3.6.12 build failures when using `--bootstrap --no-substitutes`

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#21203]
Corresponding Guix Issue: https://issues.guix.gnu.org/44559

When supplying `--bootstrap --no-substitutes` and performing Guix builds with Guix v1.2.0, a build of `/gnu/store/vhphki5sg9xkdhh2pbc8gi6vhpfzryf0-gnutls-3.6.12.drv` will be attempted. The tests for this build will fail if your system clock is after 2020-10-24 as the certificates included in GnuTLS expires on that date ([GnuTLS ticket](https://gitlab.com/gnutls/gnutls/-/merge_requests/1230?commit_id=ed208fe55f31478732fd6cc394f9576b315a42cd)).

Although this has been fixed in Guix master some time ago, I believe a `--bootstrap --no-substitutes` `guix pull` will attempt to bootstrap the current Guix generation first (which means it will have to build the broken `gnutls`) before updating to a new generation.

Currently, there is [a workaround](https://issues.guix.gnu.org/44559#5) for this which involves stopping NTP and manually setting the time prior to the certificate expiry.

I have [posted](https://issues.guix.gnu.org/44559#6) on the corresponding Guix issues about this asking about alternative solutions to this. Will keep this thread posted on relevant updates.

**Comment by dongcarl** [comment]
Some updates here: https://issues.guix.gnu.org/44559#8

Guix maintainer has indicated that he thinks it would be a good idea to release Guix v1.2.1 with this "hotfix".

I'm also pushing for more powerful package transformation options [here](https://issues.guix.gnu.org/46650) so that we can sidestep spurious test problems in the future.

Thank you sipa and achow101 for testing my various solutions to this. I will get it sorted!

**Comment by dongcarl** [comment]
Release v1.2.1 is tentatively scheduled for April 18th. More info:
1. https://lists.gnu.org/archive/html/guix-devel/2021-03/msg00363.html
2. https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47297

**Comment by Sjors** [comment]
I guess they skipped to 1.3.0?

**Comment by dongcarl** [comment]
> I guess they skipped to 1.3.0?

Yes! (And this particular issue's solution is included in v1.3.0)

I think I'll just close this for now, as it'll be mentioned in the README.
