### ISSUE TITLE
iOS build support in macos bigsur 2020

### ISSUE THREAD

**Issue by congtung10t2** [bitcoin/bitcoin#21208]
I'm trying to build the bitcoin core for ios but it seems that the library only support for mac linux ubuntu and android so far. 

I have look at this repository https://github.com/Sjors/iOS-bitcoin-full-node. 

But it seems out of maintain for a long time. And when I call **make**, it still show out a lib for macos instead of iOS.

Can anyone help me for some instructions? 

I'm using Xcode12 and mac bigsur 11.2.1.

openssl for ios
https://github.com/x2on/OpenSSL-for-iPhone

(we can refer to https://github.com/leetal/ios-cmake for c++ xcode example for ios)

**Comment by fanquake** [comment]
This is probably a duplicate of #11720.

**Comment by congtung10t2** [comment]
> This is probably a duplicate of #11720.

I have refer the repo that he has built for iOS with the problem. 

The most recent build is from 2018-2019 and it's still no work solution. Sorry but can we keep it for the newer answer?

**Comment by fanquake** [comment]
> Sorry but can we keep it for the newer answer?

The answer is that we don't officially support building for iOS, and as far as I'm aware, no-one is actively working on it. If you'd like to contribute to that development, the best place to continue any discussion is in #11720.

**Comment by congtung10t2** [comment]
Ok I see, let me continue on that thread
