### ISSUE TITLE
Starting pruned node with `blockfilterindex=1` gives unhelpful error

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#21229]
After #15946 starting a pruned bitcoin-qt with `blockfilterindex=1` will give the error message

> Error: A fatal internal error occurred, see debug.log for details

It would be more helpful if it gave what's in the debug.log which is

> basic block filter index best block of the index goes beyond pruned data. Please disable the index or reindex (which will download the whole blockchain again)

**Comment by jonasschnelli** [comment]
Agree with @benthecarman.
However, this is not directly a #15946 issue. All fatal index errors lead to a generic error in the GUI: https://github.com/bitcoin/bitcoin/blob/master/src/index/base.cpp#L26

**Comment by ali-ahari-hashemi** [comment]
Interested in working on this as it seems simple enough for my first contribution. Do you think the best approach would be to use the `strMessage` within `AbortError`?

**Comment by ali-ahari-hashemi** [comment]
@benthecarman @jonasschnelli I have a fix and I have tested it, seems to be working fine. I will submit a PR later for you guys to check out.

**Comment by klementtan** [comment]
@ali-ahari-hashemi are you still working on this? I would like to pick this up if you re not

**Comment by MarcoFalke** [comment]
This is fixed as a by-product of #21796

**Comment by mzumsande** [comment]
@MarcoFalke #21796 was merged, this can be closed.
