### ISSUE TITLE
Refactor (move-only) into a "block storage" module

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#21220]
See:

* https://github.com/bitcoin/bitcoin/pull/15946/files#r281221080
* https://github.com/bitcoin/bitcoin/pull/21030#issuecomment-771384797

**Comment by laanwj** [comment]
Concept ACK (obviously), but think "storage" is too general as a name, would recommend to explicitly call it "block storage" (which also happens to match an existing label here :smile: ).
