### ISSUE TITLE
validation: -Wmaybe-uninitialized compiler warning thrown by CTxMempool::GetIterSet 

### ISSUE THREAD

**Issue by jarolrod** [bitcoin/bitcoin#21248]
When compiling from `master`, I get the following warning using GCC 10.2.1

```
txmempool.cpp: In member function ‘CTxMemPool::setEntries CTxMemPool::GetIterSet(const std::set<uint256>&) const’:
txmempool.cpp:894:29: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  894 |     return Optional<txiter>{};
      |                             ^
```

**System:**
OS: Debian Buster
Compiler: GCC 10.2.1

**Steps to reproduce:**
- grab master
- go through the compilation process
- get `-Wmaybe-uninitialized` compiler warning

**Comment by fanquake** [comment]
Thanks, however this is a false positive. See #20797, #20950, #20894.
