### ISSUE TITLE
Funds disappering

### ISSUE THREAD

**Issue by bigmicke** [bitcoin/bitcoin#21265]
The funds I sent ended up being 10% of the original fund. Transactions id show the sent BTC with an extra O, making it 90% lower

**Expected [behavior*](url
[](url)
)

Get The Total fund, not 10%

**Actual behavior**

**To reproduce**

I can possibly produce screenshots of tis strange process, I'm a noob so what's obvious to You is "Sanskrit" to Me , but I'll do my best

**System information**

Blockchain. info

W 10 Pro Intel® Core™ i3-5010U CPU @ 2.10GHz  SAMSUNG MZ7LN128HCHP-000L1

Edition
Microsoft Windows 10 Pro (64 bitar)
Version (Build)
2009 (10.0.19042)

]([url]([url]([url](url))))

**Comment by MarcoFalke** [comment]
Without more information there is nothing we can do.

If you type in the wrong amount, the software also can't fix that for you.

**Comment by bigmicke** [comment]
The last Thing i uploaded + all screenshots must tell You That something is wrong how can the funds sent diminish by 90%?
Sent amount 3.7972 mBTC according to transaction id 5619c756e56b2773e9ab73718c4c548ab7cc8c7c954468ef32d944c469c8f443
5619c756e56b2773e9ab73718c4c548ab7cc8c7c954468ef32d944c469c8f443	
18b3c6312f7a1aea3b58ad9463665c16f765bbde2b545c4c55ee4e4b4c93d08c:0
0.00273045 BTC
4a2a45c4ff2b29d2b70c7e37d1df6eb7d74aaf59fe7d70ea108742a8f0604f31:0
0.00105657 BTC
bbcb7dd6baa5f90b6fc8b65110b8bc58899fa86a0c110f2876fded2503f70c8a:0
0.00029692 BTC
365mnwYhY1sgSAaCK8sZdkjbV2DgBmQuds
0.0037972 BTC that is not  3.7972 m BTC. There is a 0 missing. In this case some 16000 SEK that has disappeared.
I do not understand the finer points of these transactions, but I can count and someone must have made a mistake or stolen
 these mBTC. I Thank You for Your reply and hopes that You or someone else will be able to explain how this happened
and if it is possible to recover the funds, as 16000SEK is a bit too much to lose.
Regards M L.

**Comment by MarcoFalke** [comment]
3 mBTC means milli BTC, aka 0.003 BTC, so everything looks right. I am not sure what the problem is.

**Comment by bigmicke** [comment]
The fund supposed to be transferred was 0.0408334 (3.7972 mBTC)17,920.SEK mins fees, so how they've arrived to that sum is strange
So I am sure what the problems´is, how they arrived to the sum of 0.003792 instead of 0.037972 mBTC
I really want You to explain how this looks right to You, not sure what the problem is?

**Comment by bigmicke** [comment]
3.7972 mBTC not 3mBTC

Den mån 22 feb. 2021 kl 15:54 skrev MarcoFalke <notifications@github.com>:
