### ISSUE TITLE
Sync between two nodes

### ISSUE THREAD

**Issue by liorko87** [bitcoin/bitcoin#21266]
I'm using the latest release of bitcoin (0.21.0) with private blockchain. I have two nodes running on localhost
When I'm generating a new block by using `generatetoaddress` I receivedthis error:
```
error: Could not connect to the server 127.0.0.1:18001 (error code 0 - "timeout reached")

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
```
When I'm looking at the log, I see the same error as #12291:
```
Timeout downloading headers from peer=1, disconnecting
```
When I'm trying to mine a new block again, in some cases it's working and the block is created but not confirmed by the second node.
The number of confirmations of the new block is 1.

In all cases the second node does not see new blocks.

**EDIT**: I checked the status of the rpc commands and it's still trying to create new blocks:
```
"active_commands": [
    {
      "method": "generatetoaddress",
      "duration": 7371995894
    },
    {
      "method": "getrpcinfo",
      "duration": 18
    }
  ]
```

**Comment by brunoerg** [comment]
What's your OS?

**Comment by liorko87** [comment]
Ubuntu 20.04.1 LTS

**Comment by MarcoFalke** [comment]
I recommend regtest for private chains, not testnet3.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
