### ISSUE TITLE
Unicode comment strings doesn't handled correctly in "move" API calls to bitcoind.

### ISSUE THREAD

**Issue by HandleX** [bitcoin/bitcoin#2127]
OS: Windows Server 2008 R2.
Call method: HTTP JSON RPC.
Stringification method: JSON.stringify().

When I execute "move" bitcoin API (handled by bitcoind.exe), some comment string characters supported correctly, some not.

As an example: I've executed "move" API with comment "฿иткоин", where first letter is unofficial unicode bitcoin sign, and others are russian characters. Then I've executed "listtransactions" API call, I've received comment string distorted: "฿и￿u0082коин". As we can see, some characters correct, some not.

I use bitcoind as an online wallet on my site. Transaction comments can be useful there, so I want to have correct JSON RPC unicode support in bitcoind.

**Comment by laanwj** [comment]
I wonder how this changed with the switch from json_spirit to univalue in 0.12.

I don't think it is completely fixed: there's one known issue with utf-8 handling at least: https://github.com/jgarzik/univalue/issues/16

**Comment by laanwj** [comment]
Closed by #7892
