### ISSUE TITLE
wallet: Multi-sig flow with descriptor wallets

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#21278]
It would be nice to have documentation on how to set up a basic M-of-N multisig between multiple people using descriptor wallets and PSBTs, as well as a signing flow.

E.g. (borrowed some steps from @jonasschnelli)

- First phase: generate and exchange `xpub`s:
  - Every participant generates an `xpub`: most straightforward is to create a new wallet, I guess, but how to get the `xpub` to share for a specific BIP32 path?
  - Maybe #21277 helps here *but* it might be putting the cart before the horse: do we want the default non-multisig descriptors at all here? I don't think so.
  - Share it with the other participants.
- Second phase: Every participant imports the following descriptors using `importdescriptors`:
  - Receiving  (`internal: false`) addresses are `wsh(sortedmulti(<M>,xpubA/0/*,xpubB/0/*,xpubC/0/*,…))`
  - Change (`internal: true`) addresses are `wsh(sortedmulti(<M>,xpubA/1/*,xpubB/1/*,xpubC/1/*,…))`
- Send funds to the resulting address (every participant should get the same addresses).
- When making a sending transaction create one using `walletcreatefundedpsbt` (everyone can initiate this)
  - Send the resulting PSBT to other users
  - At least M users checks it with `decodepsbt` then (if ok) signs it with `walletprocesspsbt`
  - Collect the signed PSBTs with `joinpsbts` then broadcast the resulting transaction

**Comment by Rspigler** [comment]
For the setup (First and second phase in OP): there is a current discussion of a secure multisignature setup standard here: (https://github.com/nunchuk-io/bips/pull/1)

I like how you wrote the xpubs/descriptors, compatible with the scheme proposed by @prusnak here: (https://github.com/bitcoin/bitcoin/issues/21197), which adds labels/groups, and hopefully also satisfies the people who wanted [ranges in the descriptor](https://github.com/bitcoin/bitcoin/issues/17190). The latter seems to have been [NACKed](https://github.com/bitcoin/bitcoin/issues/21199#issuecomment-780772418) by @sipa (and I agree, this seems cleaner).

I agree that PSBTs should be used.  @hugohn 's standard doesn't currently cover that (sending/creating).

**Comment by synctext** [comment]
> documentation on how to set up a basic M-of-N multisig between multiple people using descriptor wallets and PSBTs, as well as a signing flow.

+1. As part of our university research we are trying to integrate this into our Bitcoin multi-sig DAO. We have the bits and piece working. However, it currently only scales to 10-ish people, due to the need to include all public keys. Four students are currently trying to get Taproot to make it scale :+1:. https://github.com/Tribler/tribler/issues/5986
![robot economy](https://user-images.githubusercontent.com/4957928/108748805-4a9b1900-753f-11eb-98f1-2cc790c795ec.png)

**Comment by Rspigler** [comment]
There is now a proposed BIP standardizing a process for setting up multisignature wallets - https://github.com/bitcoin/bips/pull/1097
Also a proposed BIP for an updated hierarchy for cosigners in multisignature wallets - https://github.com/bitcoin/bips/pull/1089

This would include descriptor wallets, [PSBTs](https://github.com/bitcoin/bitcoin/pull/21283), and (hopefully) [QR codes](https://github.com/bitcoin/bitcoin/issues/9913).

Something that has also been discussed is possibly increasing the [checksum](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#checksums) in the descriptor language. See discussion [here](https://github.com/bitcoin/bips/pull/1097#issuecomment-817515315)

This would also be a significant/final part of my $1,500 bounty posted here - https://github.com/bitcoin/bitcoin/issues/21071

**Comment by vmenond** [comment]
We have the following multisig descriptor that is resulting in some weird behaviour on Bitcoin-Core.

```
"bitcoin-cli -rpcwallet=msig importdescriptors '[{"range": [0, 1000], "timestamp": "now", "desc": "wsh(multi(3,[ad812a29/84h/1h/0h]tpubDChVss7wefA63SZ7JsVdepCaoyo3qPojScTwPfpGZ6g9rVo3BRgTDabngF398egL578Ne99LyFkRE59BgSaQStK67PwtFRR47XXL1NhHEpu/0/*,[c2b507ce/84h/1h/0h]tpubDDY1HyiMDReMYtUrivMvZFNS2QLosJqL2p68vSXS1KaU3ASZSWDhDB1QGks6C9Gb3uuuhjQ6Pa2an32ak4soGBGpPzzu4jp6jfYzWVPPuUL/0/*,[bae7ef16/84h/1h/0h]tpubDCAgz23qpZQ7iNsU9tAnEkjihrPeNFLYvJ2CuzMSUdqiBKh3i9mEV6C1rJXBFdLE6YoaJoBkTJg2o8EzjLvwasNmDhTDVuqYFJo6piCPFZv/0/*))#kh6e0vw7", "internal": false},{"range": [0, 1000], "timestamp": "now","desc": "wsh(multi(3,[ad812a29/84h/1h/0h]tpubDChVss7wefA63SZ7JsVdepCaoyo3qPojScTwPfpGZ6g9rVo3BRgTDabngF398egL578Ne99LyFkRE59BgSaQStK67PwtFRR47XXL1NhHEpu/1/*,[c2b507ce/84h/1h/0h]tpubDDY1HyiMDReMYtUrivMvZFNS2QLosJqL2p68vSXS1KaU3ASZSWDhDB1QGks6C9Gb3uuuhjQ6Pa2an32ak4soGBGpPzzu4jp6jfYzWVPPuUL/1/*,[bae7ef16/84h/1h/0h]tpubDCAgz23qpZQ7iNsU9tAnEkjihrPeNFLYvJ2CuzMSUdqiBKh3i9mEV6C1rJXBFdLE6YoaJoBkTJg2o8EzjLvwasNmDhTDVuqYFJo6piCPFZv/1/*))#yzxdvr0a", "internal": true}]'"
```

This descriptor imports successfully and the following commands produce correct results:

`listtransactions` - shows the correct history

`walletcreatefundedpsbt` - creates a valid psbt that we were able to sign and broadcast

HOWEVER, 
`getnewaddress` produces this error:
```
error code: -4
error message:
Error: This wallet has no available keys
```

The same error occurs when we use `importmulti`

**Comment by vmenond** [comment]
bitcoind logs:

```
2021-04-17T10:58:24Z [sushi] Wallet File Version = 10500
2021-04-17T10:58:24Z [sushi] Keys: 0 plaintext, 0 encrypted, 0 w/ metadata, 0 total. Unknown wallet records: 0
2021-04-17T10:58:24Z [sushi] Performing wallet upgrade to 169900
2021-04-17T10:58:24Z [sushi] Wallet completed loading in              32ms
2021-04-17T10:58:24Z [sushi] setKeyPool.size() = 0
2021-04-17T10:58:24Z [sushi] mapWallet.size() = 0
2021-04-17T10:58:24Z [sushi] m_address_book.size() = 0
2021-04-17T10:58:25Z [sushi] RescanFromTime: Rescanning last 16 blocks
2021-04-17T10:58:25Z [sushi] Rescan started from block 000000000000000d9f908b4e00f92a8a495ec21e2591443e6850513ca8e21071...
2021-04-17T10:58:25Z [sushi] AddToWallet 846afdf0956e94f6831ab650e6703a5b268c1633d6961214c73a1948aaba16c0  new
2021-04-17T10:58:25Z [sushi] Rescan completed in 
.....
.....
2021-04-17T11:02:19Z [sushi] Already have script 532102ea3cf7d84387559e16532e1cae88e8d7f5b5857d58971c7443fcd5eecbbee4a42102675f0fcd50d99243ec8ffde921d1f0170e2089f8fd2c77b1e12d99372027d3e82102eaa9675a7b957ae3421bd9a902c4bbbcb16085a7c3a4b4c278d34b70e101141e53ae, skipping
```

**Comment by Sjors** [comment]
#22341 introduces a `getxpub` RPC which should useful for this

**Comment by laanwj** [comment]
No, I think this is done. Thanks @mjdietzx.
