### ISSUE TITLE
Solve for %51 attact

### ISSUE THREAD

**Issue by onuratakan** [bitcoin/bitcoin#21282]
**Is your feature request related to a problem? Please describe.**
Yes, this problem is security problem for pow consensus protocol.

**Describe the solution you'd like**
Solution is basic, the new consensus algorithm Safe Proof of Work, blocks will have a two hash block, and miner select from random, first hash mining or second hash mining. this is changed all mining proccess. And add into the hash, the merkle root of the blocks of the blockchain the miners wants to add. If first hash blocks merkler root not equal second hash blocks merkle root, all nodes and miners restart process.

**Describe alternatives you've considered**
If you want to know more, you can check the my github repository. (onuratakan/SPOW) I published with mozilla public license.

**Comment by CrommVardek** [comment]
So a miner can force a process to restart by adding an erroneous hash block ?

**Comment by sipa** [comment]
Discussions about fundamental changes to Bitcoin belong on the bitcoin-dev mailinglist, not the issue tracker of one single implememtation.
