### ISSUE TITLE
Transactions columns widths not remembered after quit

### ISSUE THREAD

**Issue by Geremia** [bitcoin/bitcoin#21306]
When I open bitcoin-qt, these are the default widths (note: I'm using the Interlingua language; I haven't tested with English as UI language):

Widths when starting bitcoin-qt:
[![default widths][1]][1]

My changed widths, which it doesn't remember after quit:
[![widths it doesn't remember][2]][2]

  [1]: https://i.stack.imgur.com/Z226s.png
  [2]: https://i.stack.imgur.com/Gf8Ts.png

**Comment by jonatack** [comment]
Hi @Geremia, I think the column widths are now saved and restored in current master since the merge of https://github.com/bitcoin-core/gui/pull/205. If you like, perhaps try building and testing on master branch and letting us know.

**Comment by Geremia** [comment]
@jonatack Applying [205.patch](https://patch-diff.githubusercontent.com/raw/bitcoin-core/gui/pull/205.patch) fixed it.
thanks

**Comment by hebasto** [comment]
> Also, "Requested payments history" and "Peers" column widths aren't remembered.

https://github.com/bitcoin-core/gui/pull/205#issuecomment-787095485

**Comment by hebasto** [comment]
I think this issue [could](https://github.com/bitcoin-core/gui/pull/205#issuecomment-787123798) be closed now.
