### ISSUE TITLE
Compiling on stock Fedora 35

### ISSUE THREAD

**Issue by Cinemacloud** [bitcoin/bitcoin#21309]
While compiling for Fedora 35 stock machine, I kept having failures due to code in the fuzz tests, I found that adding: 

#include &lt;stdexcept&gt;
#include &lt;limits&gt;

to the top of ./src/test/fuzz/FuzzedDataProvider.h  fixed the issue.

**Comment by practicalswift** [comment]
@Cinemacloud Thanks for reporting. Could you share the error message you get when compiling?

**Comment by hebasto** [comment]
Fedora 35 release [is about a half year from now](https://fedorapeople.org/groups/schedule/f-35/f-35-key-tasks.html).

It seems premature to bother about compiling issues.

Maybe close it for now?

**Comment by laanwj** [comment]
If it's a legitimate problem uncovered here (lacking an `#include`) I tend toward fixing it instead. But we need more information.

**Comment by MarcoFalke** [comment]
Fixed in https://reviews.llvm.org/D98057
