### ISSUE TITLE
Unable to compile bitcore core on WSL

### ISSUE THREAD

**Issue by ajgodfrey** [bitcoin/bitcoin#21332]
I'm unable to compile the bit core code on WSL

I get the error message:
 CC       buffer.lo
In file included from buffer.c:94:
util-internal.h:490:48: **error**: operator '<=' has no right operand
  490 | #if (EVENT__SIZEOF_SIZE_T <= EVENT__SIZEOF_LONG)
      |                                                ^
make[2]: *** [Makefile:1806: buffer.lo] Error 1

*
**System information**

git clone https://github.com/bitcoin/bitcoin.git

Windows 10 Running WSL running Ubantu

**Comment by ajgodfrey** [comment]
![image](https://user-images.githubusercontent.com/60384965/109619127-814ee000-7b8c-11eb-8e2d-fe3f557b9f8f.png)

**Comment by hebasto** [comment]
@ajgodfrey 
> Windows 10 Running WSL running Ubantu

Is your Ubuntu is 18.04 or 20.04?

**Comment by hebasto** [comment]
FWIW, successfully compiled the current master (b9f41df1ead4b6a83a51fc41966b111c8459c313) on Windows 10.0.19042.804 with WSL Ubuntu 20.04.

**Comment by ajgodfrey** [comment]
> @ajgodfrey
> 
> > Windows 10 Running WSL running Ubantu
> 
> What is the `wsl -l -v` command output in your Windows PowerShell?

Name              State           Version
Ubantu             Running     2

**Comment by ajgodfrey** [comment]
> FWIW, successfully compiled the current master ([b9f41df](https://github.com/bitcoin/bitcoin/commit/b9f41df1ead4b6a83a51fc41966b111c8459c313)) on Windows 10.0.19042.804 with WSL Ubuntu 20.04.

I'm running windows 10 with Ubantu 20.04.2 LTS

**Comment by sipa** [comment]
What is Ubantu?

**Comment by ajgodfrey** [comment]
> What is Ubantu?

sorry Ubuntu

**Comment by hebasto** [comment]
> > @ajgodfrey
> > > Windows 10 Running WSL running Ubantu
> > 
> > 
> > What is the `wsl -l -v` command output in your Windows PowerShell?
> 
> Name State Version
> Ubantu Running 2

Could you try to switch WSL version from 2 to 1?

**Comment by ajgodfrey** [comment]
Ubuntu 20.04

**Comment by hebasto** [comment]
@ajgodfrey 

Did you follow https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows:
```
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
sudo bash -c "echo 0 > /proc/sys/fs/binfmt_misc/status"
make -C depends HOST=x86_64-w64-mingw32
...
```

?

**Comment by ajgodfrey** [comment]
I did, thanks!

**Comment by ajgodfrey** [comment]
I will try running  Ubuntu as a VM using VM Player for Windows and see if I
get the same issue.

**Comment by ajgodfrey** [comment]
@hebasto    This bug can be closed.  I went back through the instructions and found that I had made a mistake with the following: 
# Set the default mingw32 g++ compiler option to posix.  I selected the default option (0) by mistake.
Thanks for your help.
