### ISSUE TITLE
guix: guix doesn't like x86_64-pc-linux-gnu

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#21347]
This has caught me out more than once. If you try and perform a Guix build with `HOSTS="x86_64-pc-linux-gnu" ./contrib/guix/guix-build.sh`, it doesn't work, and the build script just "dies". The problem is here:

https://github.com/bitcoin/bitcoin/blob/4f223e93e9c097c96a1655f9125aec463892da9c/contrib/guix/libexec/build.sh#L147-L158

There is no `x86_64-pc-linux-gnu` case, so we just exit. I ended up using `x86_64-pc-linux-gnu` after copy-pasting from the triplets listed in the [depends readme](https://github.com/bitcoin/bitcoin/blob/master/depends/README.md).

**Comment by dongcarl** [comment]
I don't believe we ever supported `x86_64-pc-linux-gnu` for Gitian builds... Perhaps we can just update the triplet in the depends `README`? Specifying `pc` as the vendor seems meaningless to me 🤷‍♂️

**Comment by fanquake** [comment]
> Perhaps we can just update the triplet in the depends README? Specifying pc as the vendor seems meaningless to me 🤷‍♂️

I'm not sure it's quite that simple, unless we make it a requirement to pass `HOST=x86_64-linux-gnu` when building depends on/for Linux.

When we construct `build_os` and `host_os`, we are using the vendor:
https://github.com/bitcoin/bitcoin/blob/47b99ab1a9e918022ea13f54765f5b4e6aad6140/depends/Makefile#L72-L74

https://github.com/bitcoin/bitcoin/blob/47b99ab1a9e918022ea13f54765f5b4e6aad6140/depends/Makefile#L82-L83

So anyone running make -C depends is still going to end up with `/bitcoin/depends/x86_64-pc-linux-gnu` if `HOST` isn't set.

Ultimately this comes from `config.guess`:
```bash
./depends/config.guess
x86_64-pc-linux-gnu
```

**Comment by fanquake** [comment]
Going to close this for now. No-longer that big of an issue.
