### ISSUE TITLE
windows: new -Wreturn-type warnings after #19203

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#21355]
We now get lots of compile time output like:
```bash
In file included from test/fuzz/addition_overflow.cpp:7:
./test/fuzz/util.h: In member function 'virtual SOCKET FuzzedSock::Get() const':
./test/fuzz/util.h:563:5: warning: no return statement in function returning non-void [-Wreturn-type]
  563 |     }
      |     ^
./test/fuzz/util.h: In member function 'virtual SOCKET FuzzedSock::Release()':
./test/fuzz/util.h:568:5: warning: no return statement in function returning non-void [-Wreturn-type]
  568 |     }
      |     ^
...
```
anywhere `test/fuzz/util.h` is included. Would be great to not have build logs filled with this spam.

This was all present in the CI. i.e https://cirrus-ci.com/task/5500626558779392?command=ci#L4283. 

cc @practicalswift @vasild

**Comment by MarcoFalke** [comment]
The compiler is broken, you may report this upstream.

#21247

**Comment by vasild** [comment]
Maybe this would silence the compiler to avoid spamming the build logs? Worth doing that even if it is a compiler bug?

```diff
--- i/src/test/fuzz/util.h
+++ w/src/test/fuzz/util.h
@@ -554,23 +554,23 @@ public:
     }
 
     ~FuzzedSock() override
     {
     }
 
-    SOCKET Get() const override
+    [[noreturn]] SOCKET Get() const override
     {
         assert(false && "Not implemented yet.");
     }
 
-    SOCKET Release() override
+    [[noreturn]] SOCKET Release() override
     {
         assert(false && "Not implemented yet.");
     }
 
-    void Reset() override
+    [[noreturn]] void Reset() override
     {
         assert(false && "Not implemented yet.");
     }
 
     ssize_t Send(const void* data, size_t len, int flags) const override
     {
```

**Comment by hebasto** [comment]
Related to #20586 ?

**Comment by practicalswift** [comment]
Oh, good catch.

We should probably just `return INVALID_SOCKET` in those cases (unreachable in practice of course).

**Comment by practicalswift** [comment]
`-Werror=return-type` would have caught this pre-merge.

More generally I think it would make sense to more liberally use of `-Werror`: among other things it would help us catch warnings that are only present or triggered in a subset of the three major compilers (GCC, Clang and MSVC).

If anyone wants to add `-Werror=return-type` (or `-Werror`:s more generally) I'd be glad to review :)

**Comment by fanquake** [comment]
> -Werror=return-type would have caught this pre-merge.

Looking at CI or build logs would also have caught this pre-merge. We can't just enable `-Werror=return-type` because the mingw-w64 compiler emits spurious warnings. In-fact we currently have -Werror disabled for Windows builds in the CI partly for that [exact reason](https://github.com/bitcoin/bitcoin/blob/master/ci/test/00_setup_env_win64.sh#L18). If you want to turn it on, you should start by reviewing #20586.

**Comment by practicalswift** [comment]
> > -Werror=return-type would have caught this pre-merge.
> 
> Looking at CI or build logs would also have caught this pre-merge. 

Oh, the point I was trying to make was that `-Werror=return-type` would have caught this _automatically_ :)

Sorry if that was unclear!

**Comment by hebasto** [comment]
@practicalswift _automaGically_ :)
