### ISSUE TITLE
net: No more v2 onion support in upstream Tor master

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#21351]
One of my nodes using `onlynet=tor` nodes is completely broken with current master as of 97a35f3ae5bff7f4a25d37d8961191fdbc8c5b67.

Tor is manually configured. Relevant `bitcoin.conf`:
```
onlynet=onion
proxy=127.0.0.1:9050
onion=127.0.0.1:9050
```

It does not manage to make any outgoing connections. The log has an endless stream of:
```
2021-03-03T13:42:13Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:13Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:14Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:14Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:15Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:15Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:16Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:16Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:17Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:17Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:18Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:18Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:19Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:19Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:20Z Socks5() connect to […].onion:8333 failed: general failure
2021-03-03T13:42:20Z Socks5() connect to […].onion:8333 failed: general failure
…
```
(multiple messages per second, all `[…]` are short v2 onion addresses)

```
$ systemctl status tor
● tor.service - Anonymizing overlay network for TCP
     Loaded: loaded (/etc/systemd/system/tor.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-03-03 14:45:24 CET; 3min 0s ago
    Process: 158931 ExecStartPre=/opt/tor/bin/tor -f /opt/tor/etc/tor/torrc --verify-config (code=exited, status=0/SUCCESS)
   Main PID: 158962 (tor)
      Tasks: 1 (limit: 9367)
     Memory: 38.4M
     CGroup: /system.slice/tor.service
             └─158962 /opt/tor/bin/tor -f /opt/tor/etc/tor/torrc

Mar 03 14:48:20 tor[158962]: Mar 03 14:48:20.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:20 tor[158962]: Mar 03 14:48:20.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:21 tor[158962]: Mar 03 14:48:21.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:21 tor[158962]: Mar 03 14:48:21.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:22 tor[158962]: Mar 03 14:48:22.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:22 tor[158962]: Mar 03 14:48:22.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:23 tor[158962]: Mar 03 14:48:23.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:23 tor[158962]: Mar 03 14:48:23.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:24 tor[158962]: Mar 03 14:48:24.000 [warn] Invalid hostname [scrubbed]; rejecting
Mar 03 14:48:24 tor[158962]: Mar 03 14:48:24.000 [warn] Invalid hostname [scrubbed]; rejecting
```

I'll try to see if I can figure out what it's sending. Tor (current master) is otherwise successfully able to connect to hidden services, at least v3 ones.

Did Tor completely remove v2 support?

```
$ /opt/tor/bin/tor --version
Tor version 0.4.6.0-alpha-dev (git-8020ae02abb105db).
Tor is running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1f, Zlib 1.2.11, Liblzma 5.2.4, Libzstd N/A and Glibc 2.31 as libc.
Tor compiled with GCC version 9.3.0
```

**Comment by laanwj** [comment]
Yes, it looks like Tor removed v2 support completely on the master branch:

https://github.com/torproject/tor/commit/c0a23303140fedce06e0b7d88ce475c39703717a
https://github.com/torproject/tor/commit/32fc8a116a3a88ad6e7269d5e9afb751e5d39e50

"It's all v3 now."

**Comment by jonatack** [comment]
Per https://gitlab.torproject.org/tpo/core/team/-/wikis/NetworkTeam/CoreTorReleases, tor 0.4.6 feature freeze is March 15, stable ready June 15.

Per https://blog.torproject.org/v2-deprecation-timeline:

"July 15th, 2021: 0.4.6.x: Tor will no longer support v2 and support will be removed from the code base. October 15th, 2021: We will release new Tor client stable versions for all supported series that will disable v2."

**Comment by Saibato** [comment]
RSA certificates (v2) is a broken lost case, the faster transition to v3 what ever that will hook in as final algo, since it's now perfect modular, the better. imho.

**Comment by laanwj** [comment]
Some further IRC discussion w.r.t. handling this
```
2021-03-04 10:15:35     vasild  wumpus: wrt torv2 - if torv2 addresses are non-operational on the tor network, then I think we want to stop trying to connect to such ones and maybe even purge them from addrman.
2021-03-04 10:29:48     wumpus  vasild: I'd agree--though the current situation seems more subtle: they still work on the tor network, but future Tor releases will no longer support them, I think with old tor versions they will still work for a while
2021-03-04 10:30:52     vasild  hmm, right
2021-03-04 10:31:11     wumpus  vasild: so we might want to make it an option first ! no strong preference though
2021-03-04 10:31:15     vasild  nothing can prevent old tor nodes from exchaning torv2 between themselves
2021-03-04 10:31:25     wumpus  if there is wider agreement to nuke v2 support completely for 0.22 that's ok with me
2021-03-04 10:32:14     vasild  I am not sure either, when is 22.0 freeze?
2021-03-04 10:32:42     vasild  "when is the 22.0 freeze"
2021-03-04 10:32:47     fanquake        #20851
2021-03-04 10:32:48     wumpus  currently planned for 2021-06-15
2021-03-04 10:32:48     gribble https://github.com/bitcoin/bitcoin/issues/20851 | Release schedule for 22.0 · Issue #20851 · bitcoin/bitcoin · GitHub
2021-03-04 10:35:31     vasild  lets see how connecting to torv2 nodes works in e.g. beginning of June and decide then what to do: 1. do nothing, 2. introduce an option --ignore-torv2 with default of false, 3. --ignore-torv2 with default of true, 4. unconditionally ignore torv2 without any new options
2021-03-04 10:36:37     wumpus  right, good summary of the options
2021-03-04 10:38:07     vasild  a test may be something like: run (old) tor node that supports torv2, pick e.g. 100 torv2 addresses from addrman and try to connect each one of them
```
I agree with @vasild here. Our options are:

1. do nothing
2. introduce an option `--ignore-torv2` with default of false
3. `--ignore-torv2` with default of true
4. unconditionally ignore torv2 without any new options

(we might also backport [3] to 0.21.0, while doing [4] for 0.22)

Doing [2] soon makes sense imo to work around this issue for people who like to run bleeding-edge Tor, and to have something to suggest when Tor 0.4.6.x comes out. As I describe in the OP, that's currently completely broken.

**Comment by Saibato** [comment]
option 2 seams reasonable.    
bcs, Some might still run and prefer kind of v2 in there ports with short addr formats in the wild and have there own directory's and infra, we can not be sure every port 9050/51 is a classic Tor socks5 proxy  (i.e could be. Tor-stealth-x)  we are not aware of, and in my view transitions should not be exclusive?

**Comment by jonatack** [comment]
Agree with starting with 2 and then likely graduating to 3 and 4.

**Comment by laanwj** [comment]
> we are not aware of, and in my view transitions should not be exclusive?

Just keep in mind that the Tor projects has been, both explicitly and reading between the lines, been very clear that v2 is broken.

**Comment by laanwj** [comment]
It looks like the underlying problem here is not the presence of old v2 peers in the peer manager, but that even though it knows 4555 onion peers, somehow the node does not  know any v3 addresses. There are also no hardcoded v3 onion addresses to add (#20239):
```python
>>> data=p.getnodeaddresses(0)
>>> len(data)
4555
>>> len([x for x in data if x['address'].endswith('.onion') and len(x['address']) <= 22])
4555
>>> len([x for x in data if x['address'].endswith('.onion') and len(x['address']) > 22])
0
```
Compared to another, more busy node that is not `-onlynet=onion`:
```python
>>> data=p.getnodeaddresses(0)
>>> len(data)
65357
>>> len([x for x in data if x['address'].endswith('.onion') and len(x['address']) <= 22])
4634
>>> len([x for x in data if x['address'].endswith('.onion') and len(x['address']) > 22])
17
```
Even 17 is surprisingly few.

**Comment by jonatack** [comment]
I guess that might explain why I've been able to run tor 0.4.6.1-alpha with `onlynet=onion` and `onlynet=i2p` and have it fill up quickly with tor v3 and i2p peers (seeing the reported warnings for the tor v2, but the frequency goes down quickly):

```bash
$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".onion")) | select(.address | length <= 22)) | .address' | uniq | wc -l
5886

$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".onion")) | select(.address | length > 22)) | .address' | uniq | wc -l
941

$ grep "peers.dat" ~/.bitcoin/debug.log
2021-03-30T18:04:05Z Loaded 60672 addresses from peers.dat  3162ms
```
That node doesn't have many peers; I restart it often for testing. It does have a couple dozen addnode peers in the conf file.

OTOH the peer rotation seems lower than usual. After 6.5 hours the highest peer id is only 88 with around 19 peers connected (1 inbound, and 18 outbound of which 8 are addnode and 2 are block relay).

**Comment by jonatack** [comment]
I guess that might explain why I've been able to run tor 0.4.6.1-alpha with `onlynet=onion` and `onlynet=i2p` and have it fill up quickly with tor v3 and i2p peers (seeing the reported warnings for the tor v2, but the frequency goes down quickly):

```bash
$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".onion")) | select(.address | length <= 22)) | .address' | wc -l
5886

$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".onion")) | select(.address | length > 22)) | .address' | wc -l
941

$ grep "peers.dat" ~/.bitcoin/debug.log
2021-03-30T18:04:05Z Loaded 60672 addresses from peers.dat  3162ms
```
That node doesn't have many peers; I restart it often for testing. It does have a couple dozen addnode peers in the conf file.

OTOH the peer rotation seems lower than usual (likely due to the tor v2 connection failures). After 6.5 hours the highest peer id is only 88 with around 19 peers connected (1 inbound, and 18 outbound of which 8 are addnode and 2 are block relay) and seeing around 20 tor v2 warnings in the last hour.

**Comment by jonatack** [comment]
What do your nodes stats look like now?

Update here after 14 hours:
```json
$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | .address' | wc -l
13027
$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".onion")) | select(.address | length <= 22)) | .address' | wc -l
5867
$ ./src/bitcoin-cli getnodeaddresses 0 | jq '.[] | (select(.address | contains(".onion")) | select(.address | length > 22)) | .address' | wc -l
1028
```

Highest peer id is now 44. Same number of peers connected. ~40 tor v2 warnings in the past hour.

**Comment by jonatack** [comment]
It seems we could be thinking about:
- v3 onion propagation improvements and seeding (#20231)
- maybe an opt-in `--ignore-torv2` config as discussed above, but indeed it won't suffice if a node doesn't know enough tor v3 addresses
- maybe an easy way (RPC) for people to see their address counts by network, with a tor v2/v3 breakdown

**Comment by vasild** [comment]
Here:
52375 total addresses, of which:
4443 tor v2
14 tor v3

**Comment by laanwj** [comment]
Agreed!

FWIW: #21560 solved my immediate problem.

> maybe an opt-in --ignore-torv2 config as discussed above, but indeed it won't suffice if a node doesn't know enough tor v3 addresses

I'm no longer convinced that this is necessary. At least in my case it would not have improved anything, and once it did know TorV3 addresses it was resolved quickly.

> An easy way (RPC) for people to see their address counts by network, with a tor v2/v3 breakdown

Could be fully client-side, `bitcoin-cli -getaddresstats` maybe?

**Comment by jonatack** [comment]
> Could be fully client-side, `bitcoin-cli -getaddresstats` maybe?

SGTM and right up my alley.

Latest stats on same node: 11405 total addresses, 5848 v2, 1084 v3. Total addresses and v2 are heading down, v3 heading up.

**Comment by jonatack** [comment]
Update, same node: total addresses and v2 addresses still dropping and v3 addresses have nearly doubled.

Total: 7573
Tor v2: 5546
Tor v3: 1835

**Comment by vasild** [comment]
Update:
55325 total addresses, of which:
3869 tor v2
242 tor v3

**Comment by jonatack** [comment]
I had 3600 v3 addresses after a month of running with tor master.

**Comment by laanwj** [comment]
Tor v2 support has been dropped in #22050, and 
- will no longer be in 22.0.
- 0.21.x will continue to support both (or we could backport this?).
- 0.20.x and before do not support Tor v3 so users of that will be unable to use hidden services when v2 support is dropped upstream (but can still use Tor otherwise).

**Comment by vasild** [comment]
> 0.20.x and before do not support Tor v3 so users of that will be unable to use hidden services when v2 support is dropped upstream (but can still use Tor otherwise).

Yeah, users of Bitcoin Core <=0.20.x can listen on Tor v3 service if it is configured in `torrc` with something like:
```
HiddenServiceDir /var/db/tor/bitcoin/
HiddenServiceVersion 3
HiddenServicePort 8333 127.0.0.1:8333
```

**Comment by jonatack** [comment]
ISTM this issue can now be closed.

**Comment by MarcoFalke** [comment]
Closing for now, can be reopened if something was forgotten.

**Comment by felipelalli** [comment]
If you are having issues on first connection, summing up:

Delete `peers.dat` and restart your node.
