### ISSUE TITLE
Suggestion : update qt.mk in depends/package. 5.2.1 URL has change

### ISSUE THREAD

**Issue by kunalbarchha** [bitcoin/bitcoin#21361]
The qt.mk contains the download URL that has been moved: 

new url:

    $(package)_download_path=https://download.qt.io/new_archive/qt/5.2/$($(package)_version)/single
    $(package)_file_name=$(package)-everywhere-opensource-src-$($(package)_version).tar.xz
    $(package)_sha256_hash=05559100acdff342e9965b8c27ef674d9106f76909c82f94280bbfd46ecf784e

**Comment by fanquake** [comment]
We don't currently use qt 5.2 in master, nor any other branch that is supported (even 0.16 was using 5.7).

**Comment by kunalbarchha** [comment]
Closed it. I was experimenting with old version. Sorry my bad ! Maybe it will help some Googlers in future.
