### ISSUE TITLE
build: Evaluate passing depend's build_{CC,{C,CPP,LD}FLAGS} to bitcoin's configure

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#21412]
`secp256k1` uses the native toolchain to do its ecmult static precomputation. Since depends users can specify their "build" (native) toolchain, we should put that in the resulting `config.site` so that bitcoin's configure can pick it up and pass it to `secp256k1` as `{CC,{C,CPP,LD}FLAGS}_FOR_BUILD` variables. Consistency FTW!

**Comment by fanquake** [comment]
> pass it to secp256k1 as {CC,{C,CPP,LD}FLAGS}_FOR_BUILD variables. Consistency FTW!

secp256k1 has removed it's `_FOR_BUILD` usage, i.e https://github.com/bitcoin-core/secp256k1/pull/988. Is this still relevant?

**Comment by dongcarl** [comment]
Guess not unless we reintroduce it in the future in our repo or vendored things somehow!

**Comment by hebasto** [comment]
Related PRs:
- #23571
- #23619
