### ISSUE TITLE
Get new address box grayed

### ISSUE THREAD

**Issue by CactusPete20** [bitcoin/bitcoin#21456]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

On March 11th, 2021, I completed my downloaded of the full node from Bitcoin Core, (Bitcoin-0.21.0-win64-setup), on my Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz - 16.0GB,  Windows 10Pro.

I created a new wallet with encryption and I named it.

The "get new address" box remains grayed out.

After unlocking with "passphrase" [] 100),

Console command "getnewaddress" was unsuccessful.  "update" says I'm wallet version 169900.

Node is fully synced and has remained in operation, with "check box" saying up to date, and with 10 active connections to Bitcoin network.

I haven't seen any new problems reported, with this issue, since 0.21.0 release.  I'm pretty sure I've tried and was unsuccessful with all other suggestions for the same issue.

Any ideas are greatly appreciated.  Further, I'm a boomer noob, who left programming after the mouse was introduced.

Uggh! Wondering if I should delete node and start over without encrypted wallet?

**Comment by CactusPete20** [comment]
20:31:52 ￼ getwalletinfo 20:31:52 ￼ { "walletname": "trlight", "walletversion": 169900, "format": "bdb", "balance": 0.00000000, "unconfirmed_balance": 0.00000000, "immature_balance": 0.00000000, "txcount": 0, "keypoololdest": 9223372036854775807, "keypoolsize": 0, "keypoolsize_hd_internal": 0, "unlocked_until": 0, "paytxfee": 0.00000000, "private_keys_enabled": true, "avoid_reuse": false, "scanning": false, "descriptors": false }

**Comment by CactusPete20** [comment]
09:25:44 ￼ walletpassphrase(…) 09:25:45 ￼ null 09:26:12 ￼ keypoolrefill 09:26:12 ￼ null 09:27:40 ￼ Executing command without any wallet 09:27:40 ￼ walletpassphrase(…) 09:27:40 ￼ null 09:28:13 ￼ keypoolrefill 09:28:13 ￼ null 09:29:02 ￼ getnewaddress 09:29:02 ￼ Error: This wallet has no available keys (code -4)

**Comment by jarolrod** [comment]
@CactusPete20 I assume you are referring to the `Get New Receiving Address` found in the receive tab of the GUI. This happens if you do not have any private keys. When creating the wallet, did you select `Make Blank Wallet`?

**Comment by CactusPete20** [comment]
I believe I did! I think I miss understood I could create seed after wallet creation.

**Comment by jarolrod** [comment]
@CactusPete20 If you don't select `Make Blank Wallet`, you'll start off with a private key and the button will no longer be blank. If you start off with `Make Blank Wallet`, you can later populate with a private key using `sethdseed`. If your issue is solved, please close this.

**Comment by CactusPete20** [comment]
Ty, ty. Solved!
