### ISSUE TITLE
getmempoolentry format differs from documentation

### ISSUE THREAD

**Issue by gchaincl** [bitcoin/bitcoin#21468]
There are divergences between the RPC reponse format and the documented response format.

**Actual behavior**

Here's the response I get from `bitcoin-cli getmempoolentry <txid>`:

```json
{
  "fees": {
    "base": 0.00000144,
    "modified": 0.00000144,
    "ancestor": 0.00000144,
    "descendant": 0.00000144
  },
  "vsize": 144,
  "weight": 573,
  "fee": 0.00000144,
  "modifiedfee": 0.00000144,
  "time": 1616083370,
  "height": 1940743,
  "descendantcount": 1,
  "descendantsize": 144,
  "descendantfees": 144,
  "ancestorcount": 1,
  "ancestorsize": 144,
  "ancestorfees": 144,
  "wtxid": "18fcf877a1677bcdc828d338170f3d416cf866b0029147853fef29185f55db53",
  "depends": [
  ],
  "spentby": [
  ],
  "bip125-replaceable": false,
  "unbroadcast": false
}
```

According to the [documentation](https://developer.bitcoin.org/reference/rpc/getmempoolentry.html) (`bitcoin-cli help getmempoolentry`)  I have encountered two divergences:
* `size` field described in the docs should be renamed to `vsize`
* docs should add the `unbroadcasted` field

Run `bitcoin-cli help getmempoolentry` and compare against the documentation hosted on bitcoin.org

**System information**
Tested on head (`v21.99.0-b972913c330a`)

**Comment by MarcoFalke** [comment]
You can fix that by clicking on " Edit Page " on the page you linked to. This repository is only about Bitcoin Core bugs, not bitcoin.org related bugs.
