### ISSUE TITLE
fuzz: Make it possible to execute each file in a directory without fuzz engine

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#21461]
This functionality is provided by libFuzzer, which is available on most platforms. However, libFuzzer is also missing on some platforms. E.g. https://github.com/google/sanitizers/issues/1165

Thus, it could make sense to implement this in our code to be able to execute the existing fuzz inputs.

The basic idea is to check if a folder was passed into `main` (https://github.com/bitcoin/bitcoin/blob/63314b8211d795b2bf0814e244d801e74f50b152/src/test/fuzz/fuzz.cpp#L75) and then iterate over the files and pass them into `test_one_input`.

#### Useful skills:

* C++17 std::filesystem
* https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
Idea by @sipa

**Comment by AnthonyRonning** [comment]
Took a stab at this here: https://github.com/bitcoin/bitcoin/pull/21496

Lemme know if the approach/code looks good, happy to make any changes.

**Comment by Modusto253** [comment]
https://api.blochair.com/bitcoin/dashboards/xpub/xpub6cuGRUonZSQ4TWtTMmzXdrXDtyPWKiKrhKo4egpiMZbpiaQL2jkwSB7icqYhZcfDfVxdx4df1890LKnC5fSwqPfgyP3hooxujYzAu3fDVmz?transaction_detaiks=true
https://api.blockkchair.com/multi/dashboards/address/{:{:addresses}.,...,{:address}μ endpoint

**Comment by bitcoininvestment73** [comment]
hello friends I'm here to give you people a good news our company is giving give away free Bitcoin come and get your own free bitcoin contact us through our company email bitcoininvestment733@gmail.com

**Comment by Davidbrizio** [comment]
🎤Author.Cordial greetings from Pungi.
I am a financial consultant and a wealth manager. I will Airdrop 100 BTC to the community. To Participate, Transfer 0.03 BTC - 5 BTC and you will Get 0.09 BTC - 15BTC back. and we will remove the Update when the 100 BTC is reached.

BTC ADDRESS:

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4

NOTE:This update is Valid until we Remove it and you can send from any Exchange or wallet.

Best RegardsMR.PUNGI

**Comment by AditiThirdEye** [comment]
Please assign me this issue if PR is not done yet

**Comment by MarcoFalke** [comment]
Done in #https://github.com/bitcoin/bitcoin/pull/24472

**Comment by MarcoFalke** [comment]
(Tomorrow this issue will turn 1️⃣ :birthday: )
