### ISSUE TITLE
change address uses previously used address

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#21480]
This issue occurred on v0.13.1, so apologies if it may have been fixed (I did a search of issues and pulls and didn't see anything obvious).

The issue is that the change address selected (by the software) was an address that had previously been used in the wallet, and so caused BTC to be sent to an address that had already been spent from (which I understand means reduced security of the bitcoins, as well as loss of privacy).

possibly fixed by #9377 - although rpc wasn't used in creating the tx (it was created using the usual send and coincontrol gui in bitcoin-qt)

**Comment by fanquake** [comment]
> This issue occurred on v0.13.1

If you're going to open an issue, please first make sure that the issue affects a recent version of the software. Provide concrete steps to recreate the issues. Provide all the other information asked for in the issue template etc.
