### ISSUE TITLE
passphrase

### ISSUE THREAD

**Issue by Parrotts8** [bitcoin/bitcoin#21494]
hi,
i dont remeber my passphrase of my wallet.
how can i recover it?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
