### ISSUE TITLE
BitCoinCore Wallet Naming

### ISSUE THREAD

**Issue by lutzd** [bitcoin/bitcoin#21501]
After creating full Block i had create New Wallet, i'd gave "DasOpiSeins"
After reread i had seen that Walletnaming goes wrong: the PopUpMenu shows " asOpiSeins" only.
May be the qt based container hide first Letter or the limit overlaying the 1st Letter<<
the Windows File Explorer shows correct naming.

I want to see identical mames for WalletName as same as given during Creating, Opening (both inside BTC Core) 
and Fileexplorer (outside BTC Core)

I c
![btc_wallet_naming_01](https://user-images.githubusercontent.com/10942632/111980062-14cd5e00-8b06-11eb-906f-dae099071441.jpg)
![btc_wallet_naming_02](https://user-images.githubusercontent.com/10942632/111980150-34648680-8b06-11eb-8e0a-4c23de5ba03d.jpg)

an can repeat this every time with every naming multiple times, same error 1st letter is hiding inside BTC Core Explorer

**System information**

**Comment by MarcoFalke** [comment]
Which version of Bitcoin Core?

**Comment by prayank23** [comment]
There was a similar issue earlier: https://github.com/bitcoin/bitcoin/issues/19928 which was fixed in https://github.com/bitcoin/bitcoin/pull/20080

**Comment by lutzd** [comment]
Oh thank you now i had reopen the created wallet and can watch that Core didnt find the wrong metered path
![btc_wallet_opening_03](https://user-images.githubusercontent.com/10942632/111986141-da67bf00-8b0d-11eb-9422-0022bdbaad6e.jpg)
![btc_wallet_opening_04](https://user-images.githubusercontent.com/10942632/111986173-e2bffa00-8b0d-11eb-8cd4-7cb70a1f7d6d.jpg)

**Comment by lutzd** [comment]
> 
> 
> There was a similar issue earlier: #19928 which was fixed in #20080

**Comment by prayank23** [comment]
@lutzd Is the issue resolved? How can we reproduce this?

**Comment by prayank23** [comment]
While testing this with Bitcoin Core v0.21.0 on Windows 10 something weird happened. I can't see one of the wallets I created in file explorer but its there in Bitcoin Qt:

![image](https://user-images.githubusercontent.com/13405205/112009612-8c25e080-8b4c-11eb-9d79-776df4f699ff.png)

Results for `getwalletinfo`:

```
{
  "walletname": "\\TestABC",
  "walletversion": 169900,
  "format": "bdb",
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1616424368,
  "keypoolsize": 1000,
  "hdseedid": "0e992c3e56cc25b649b5ba2247c978fe8b54e2ba",
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.00000000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false,
  "descriptors": false
}
```

**Comment by lutzd** [comment]
Yes i can repruce that issue. When creating a new Wallet, the first Letter seems to be ignored by the Userinterface AND by the Bitcoin core. Lets start telling you:
When creating the Wallet, the creation of the Filelink is OK. You can see the correct Directory name, rwefers to "DasOpi" 
![BitCoin 04](https://user-images.githubusercontent.com/10942632/112442580-459ed480-8d4c-11eb-9980-41203ce0e179.jpg)

But when reload the created Wallet with Name "DasOpi" Bitcoin Core ism looking for "asOpi" omnly. The first letter "D" is removed by Core read/open process

![](https://user-images.githubusercontent.com/10942632/111986141-da67bf00-8b0d-11eb-9422-0022bdbaad6e.jpg)



Hoever hope you can read mine



![](https://user-images.githubusercontent.com/10942632/111986173-e2bffa00-8b0d-11eb-8cd4-7cb70a1f7d6d.jpg)

I had never check with other Leterrs, i think first to solve this issue.
My System: WIN10x64, Build 19042.867, iCPU E5-1620 , 32GB Ram, ATI RX570 GraCa

**Comment by ryanofsky** [comment]
I haven't looked at all the posts above, it is pretty clear looking at wallet listing code how 
Lutz's first character bug could arise when `wallet_dir` ends in a slash. It looks like this bug was introduced in ed2e18398b3ab657e98e3e1fe135cbf8dd94fda3 and could probably be fixed by:

```diff
diff --git a/src/wallet/db.cpp b/src/wallet/db.cpp
index cd49baeb786..191e15c494a 100644
--- a/src/wallet/db.cpp
+++ b/src/wallet/db.cpp
@@ -12,7 +12,7 @@
 
 std::vector<fs::path> ListDatabases(const fs::path& wallet_dir)
 {
-    const size_t offset = wallet_dir.string().size() + 1;
+    const size_t offset = wallet_dir.string().size() + (wallet_dir.has_filename() ? 1 : 0);
     std::vector<fs::path> paths;
     boost::system::error_code ec;
 
```

**Comment by MarcoFalke** [comment]
Wasn't #20080 supposed to fix this?

**Comment by ryanofsky** [comment]
> Wasn't #20080 supposed to fix this?

I don't think #20080 covers the case where a `-walletdir` config option is set directly, instead of being derived from `-datadir`. Also, it looks like #20080 is just removing "." path elements not empty "" path elements which might result in trailing slashes. But I'm not sure about the details. Ideally the ListDatabases function should be able to list any path without caring how about the exact format. According to ed2e18398b3ab657e98e3e1fe135cbf8dd94fda3 it could be using `boost::filesystem::lexically_relative` but instead is using more fragile `size_t offset` approach for compatibility with an old version of Boost. C++17 apparently also has a `lexically_relative` method (https://en.cppreference.com/w/cpp/filesystem/path/lexically_normal)

**Comment by promag** [comment]
@ryanofsky looks like std lexically_relative fit the job.

**Comment by lutzd** [comment]
Hallo my dear, it looks like the fix is to use lexically_normal for compiler run?
Now i had to wait for a new build of bitcoin-core?
Let me know and thanks for so many helping services
lutz

**Comment by lutzd** [comment]
> 
> 
> @ryanofsky looks like std lexically_relative fit the job.
Hallo João, hallo Russell, it sounds good, but what i have to do to confirm the Core running properöly?
Ther first lketter Miising issue is not compiled correctly in newest version.
Pls let me know how to handle

**Comment by prayank23** [comment]
@lutzd I would suggest you to reopen this issue as it's not resolved. Also do you remember if you used any special characters while creating this wallet?
