### ISSUE TITLE
missing QT dependency

### ISSUE THREAD

**Issue by sgulls** [bitcoin/bitcoin#21511]
running `./configure --prefix=/Users/sgulls/src/bitcoin/depends/arm-apple-darwin20.3.0 --with-miniupnpc --with-natpmp --enable-natpmp-default --disable-silent-rules --with-gui=yes --disable-tests --disable-bench --enable-upnp --enable-experimental-asm --enable-static --disable-shared` after running `cd depends && make download -j8 && make && cd ..` results in 

```
checking for Qt5CglSupport... no
configure: error: Package requirements (Qt5CglSupport) were not met:

No package 'Qt5CglSupport' found
```

**Comment by fanquake** [comment]
Which version of the code are you trying to compile? Please link to the entirety of your `config.log`.

**Comment by sgulls** [comment]
the code from master as of `1c3a857`

[config.log](https://github.com/bitcoin/bitcoin/files/6187472/config.log)

**Comment by fanquake** [comment]
`bitcoin_qt.m4` in master no longer checks for `Qt5CglSupport` after the merge #21376, so your configure script is outdated. I'd suggest just fully cleaning your working directory, and re-running `./autogen.sh`, `./configure` etc.

**Comment by hebasto** [comment]
> the code from master as of `1c3a857`
> 
> [config.log](https://github.com/bitcoin/bitcoin/files/6187472/config.log)

The commit 1c3a8579c0a87cfb05a4090e50143cd932e9799e is dated 2021-03-23, that is _after_ 2021-03-11 when #21376 was merged.

**Comment by hebasto** [comment]
`make dist-clean` fixed the same issue for me.
