### ISSUE TITLE
GUI (seems to) locks up when reading chainstate (windows 7 home edition/usb drive)

### ISSUE THREAD

**Issue by SkybuckFlying** [bitcoin/bitcoin#21539]
GUI should react to button clicks, but it doesn't. 

For example in options I want to click "start bitcoin on startup" so far after clicking it and waiting for minutes it gets checkboxed.

Clicking OK also take multiple minutes before it reacts.

Smooth behaviour is to be expected not this freezing like behaviour.

Very reliable to reproduce this freezing behaviour.

bitcoin version 0.21

windows 7 home edition, toshiba laptop 2012 with 5 tb seagate usb drive connected, there bitcoin data is stored.

Bandwidth usages seems to be between 2 to 10 MB/sec from usb drive and others.

CPU usage is low only a few procent.

Thus I come to the conclusion that bitcoin is not reacting to signals from the GUI.

The gui is moveable, but the buttons dont react.

**Comment by SkybuckFlying** [comment]
IN THE MORNING WHEN I WAKE UP, I BOOT UP THE LAPTOP, IF I GO EAT I WANT BITCOIN TO WORK.

IF I NEED THE COMPUTER IMMEDIATELY I WANT TO STOP BITCOIN.

RIGHT NOW CAN'T DO IT BECAUSE IT FREEZES UP.

MY SUGGESTION IS TO BUILD IN TIME-OUT FOR WHEN BITCOIN STARTS.

PERHAPS 2 OR 5 MINUTES, THEN IT STARTS DOING IT'S THING.

THIS ALLOWS ME TO SHUTDOWN BITCOIN IMMEDIATELY.

**Comment by hebasto** [comment]
@SkybuckFlying 

Could you move this issue into the https://github.com/bitcoin-core/gui/issues, and provide your `debug.log` file?

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/445.
