### ISSUE TITLE
ci: Bump Qt version in msvc builds

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#21548]
Since #21376 merged, the following https://github.com/bitcoin/bitcoin/blob/1c7be9ab90af14d24f4668b02d9f07cec6f88a78/.appveyor.yml#L10-L12 is expected to be changed accordingly.

~Also, [build_msvc/README.md](https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md) lacks notes about external binaries usage.~

**Comment by hebasto** [comment]
@sipsorcery friendly ping :)

**Comment by sipsorcery** [comment]
@hebasto yes it's on my list. I'm expecting a few hiccups which will drag out the task to a few days so I've been putting it off until I have that amount of time.

Regarding the note about Qt binaries in the readme, there is:

> Some prebuilt x64 versions of Qt can be downloaded from here. Please be aware these downloads are NOT officially sanctioned by Bitcoin Core and are provided for developer convenience only. They should NOT be used for builds that will be used in a production environment or with real funds.

If you think it should be more prominent I would have no objection.

**Comment by hebasto** [comment]
> Regarding the note about Qt binaries in the readme, there is:
> 
> > Some prebuilt x64 versions of Qt can be downloaded from here. Please be aware these downloads are NOT officially sanctioned by Bitcoin Core and are provided for developer convenience only. They should NOT be used for builds that will be used in a production environment or with real funds.
> 
> If you think it should be more prominent I would have no objection.

Oh, I missed that. Sorry for noise about readme.

**Comment by hebasto** [comment]
Done in #21731.
