### ISSUE TITLE
Boost doesn't support building binaries that run with older kernel than the linux-headers is built against

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#21550]
We have various hacks to support older glibc, but I don't think we've considered Boost compatibility.

It appears building Boost with a modern linux-headers will not work on systems with a kernel older than the headers it was built with.

This de facto affects Bitcoin Core no later than Boost 1.75.0: https://github.com/boostorg/filesystem/issues/182

**Comment by MarcoFalke** [comment]
Let's just remove boost::fs before bumping to 1.75?

**Comment by luke-jr** [comment]
To be clear, I'm not sure if boost::fs is the only part affected.

**Comment by MarcoFalke** [comment]
Removing milestone, as this is not a regression. Absent any other known issues apart the boost::fs one, I think this can even be closed.

**Comment by fanquake** [comment]
I agree. Without more information this isn't really actionable. We've now also removed boost::fs (and even linking against any boost libs) in the interim. I think this can be reopened if/when more information is provided.
