### ISSUE TITLE
ERROR: AcceptBlockHeader: block is marked invalid

### ISSUE THREAD

**Issue by Pan7** [bitcoin/bitcoin#21568]
Compiled the latest git version (28.3.2021, Revision: c00852653f2bf9cd3ee53ab05d574fe4a9ff6dcc) with msvc 16.9 2019 of bitcoind (32bit) and get the following error:

> bitcoind -txindex=1
> ERROR: AcceptBlockHeader: block 000000000000000002bff65a2701c0b7f82d2d9c0a69bec94ca45f3fc4fdf4b6 is marked invalid

also getting:

> bitcoin-cli reconsiderblock
> ERROR: ConnectBlock: Consensus::CheckTxInputs: cb33f844ef77a7282389c515df3831d13771851a4cf2b63e5be406eebc578ceb, bad-txns-inputs-missingorspent, CheckTxInputs: inputs missing/spent
> InvalidChainFound: invalid block=000000000000000002bff65a2701c0b7f82d2d9c0a69bec94ca45f3fc4fdf4b6  height=445812  log2_work=85.747783  date=2016-12-30T13:52:38Z

> bitcoin-cli getblockchaininfo
> {
  "chain": "main",
  "blocks": 445811,
  "headers": 445811,
  "bestblockhash": "00000000000000000050987b914811f687096790995b9aba7abf9c5b2db64e8e",
  "difficulty": 317688400354.0338,
  "mediantime": 1483103061,
  "verificationprogress": 0.2916487827889263,
  "initialblockdownload": true,
  "chainwork": "00000000000000000000000000000000000000000035bbcd1e85726a7ac80c38",
  "size_on_disk": 110458261547,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 227931
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 363725
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 388381
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 419328
    },
    "segwit": {
      "type": "buried",
      "active": false,
      "height": 481824
    }
  },
  "warnings": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

Is 000000000000000002bff65a2701c0b7f82d2d9c0a69bec94ca45f3fc4fdf4b6 actually a valid hash?
What can i do now?

**Comment by MarcoFalke** [comment]
Which hardware are you using?



Bitcoin Core makes heavy use of CPU, RAM and disk IO. Hardware defects might only become visible when running Bitcoin Core. You might want to check your hardware for defects.

* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206

**Comment by Pan7** [comment]
After doing a reindex the problem is gone. No idea what happened.
