### ISSUE TITLE
A wrong deal： 0 / unacknowledged, not in memory pool

### ISSUE THREAD

**Issue by bigmyth** [bitcoin/bitcoin#21600]
This is a transaction of mine, which has not been sent successfully so far. How can I deal with it? Can you provide detailed operation steps?
Status: 0 / unacknowledged, not in memory pool
Date: 2021 / 3 / 8 12:31
To: coin an 1kgsxf7krv1ab99tex1wjm643tsilczbg6
Expenditure: - 0.05193365 BTC
Transaction fee: - 0.00120000 BTC
Net amount: - 0.05313365 BTC
Transaction ID: aceea84e8a72b24654cba7b1d042561d8a9d36f7828855b52012de8a5a0b9c12
Total transaction size: 11767 bytes
Transaction Virtual Size: 11767 bytes
Output index: 0

**Comment by fanquake** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode. Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
