### ISSUE TITLE
Fuzzer build "Timed out!"

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#21639]
Fuzzer build `[no depends, sanitizers: fuzzer,address,undefined,integer] [focal]` seems to timing out on master:

https://github.com/bitcoin/bitcoin/runs/2294417904

Also one of my PRs:

https://cirrus-ci.com/task/5980404822835200?logs=ci#L4543

From the output it seems like it is succeeding it takes two hours and the output ends in:

```
Done 12648 runs in 255 second(s)
Timed out!
```

There was a comment a few days ago about a fuzzer time out but I'm not sure it's related
https://github.com/bitcoin/bitcoin/pull/21609#issuecomment-813817656

**Comment by fanquake** [comment]
This should be fixed by #21445.

**Comment by ryanofsky** [comment]
Thanks!

I did see more recent "Timed out!" failures after this was merged. I wonder if this is expected or I need to rebase my PRs?

Apr 8, 2021, 9:53 PM EDT - #21445 Merged
Apr 8, 2021, 10:06 PM EDT - Timeout https://cirrus-ci.com/task/6394351371681792
Apr 8, 2021, 10:11 PM EDT - Timeout https://cirrus-ci.com/task/6058699123851264

**Comment by MarcoFalke** [comment]
The fix changes the task configuration, so re-running the same task won't fix it. Any way that changes the commit id of the pull request will update the task configuration.

**Comment by ryanofsky** [comment]
Thanks again, will retry. I did notice updated .cirrus.yml files merged in these runs https://cirrus-ci.com/task/6394351371681792?logs=merge_base#L389, but it makes sense that the merge might happen too late to affect task configuration.

**Comment by ryanofsky** [comment]
Actually, I'm curious why changing the commit id without rebasing will update the task configuration? Won't the task configuration still be pulled from `refs/pull/<pr>/head` not master?

**Comment by MarcoFalke** [comment]
For pull requests, Cirrus will merge with the target brach. See https://cirrus-ci.com/settings/repository/6264162542157824 which says "Merge for PRs".
