### ISSUE TITLE
Question regarding Bitcoin Seed Nodes

### ISSUE THREAD

**Issue by kodxana** [bitcoin/bitcoin#21650]
Hello guys.
I'm studing blockchain and I'm curently looking at how to DNS Seed Nodes work. I understand that crawler grabs nodes via magic messages but I can't figure out where one value came from Bitcoin source code.
```
#define BITCOIN_SEED_NONCE  0x0539a019ca550825ULL
```
Could you guys help me figure this out and point to correct place in source?
Thank you :)

**Comment by MarcoFalke** [comment]
I can't find this in our source code.

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
