### ISSUE TITLE
Cirrus CI hangs following "Agent process on a persistent worker exited unexpectedly!"

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#21673]
Seeing a weird issue where a cirrus job seems stuck in one of my PRs.

Created at 8:35:28 AM on Tue Apr 13 2021, Execution started at 10:53:11 AM, Failed in 00:21
Agent process on a persistent worker exited unexpectedly!
https://cirrus-ci.com/task/4628906121625600

Created at 10:57:11 AM on Tue Apr 13 2021, Aborted in 03:44:43
https://cirrus-ci.com/task/5366201883820032

Created at 2:41:57 PM on Tue Apr 13 2021, Aborted in 07:16:02
https://cirrus-ci.com/task/6052635301117952

Created at 9:58:35 PM on Tue Apr 13 2021, Scheduled
https://cirrus-ci.com/task/6228063525535744

The first job failed with the agent process error. The middle jobs I cancelled after a few hours and restarted. The last one is "Scheduled", and I'll leave it alone in case it magically starts working or can be debugged.

**Comment by MarcoFalke** [comment]
This particular task is run by @DrahtBot . I've doubled the compute for it, so scheduling should be faster now.

Let me know if this is still an issue.

**Comment by ryanofsky** [comment]
Thank you! Last task finally did run and now posted results.

(Created at 9:58:35 PM on Tue Apr 13 2021, Execution started at 1:48:55 AM, Failed in 23:56)
