### ISSUE TITLE
TXs with higher fees do not appear to be prioritised (via P2P) over lower fee TXs

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#21693]
After connecting a node with an empty mempool to the network I noticed that the mempool fills in such a way that it seems obvious that there is no prioritization of TXs based on their fee per byte.

Given that miners DO prioritize these TXs, then would it not make sense for the protocol to do so also?

**Comment by rebroad** [comment]
idea so far: expand the protocol so that a node can declare to another node what it's mempool size is so that nodes can provide TXs only from that upper portion of their mempool.

**Comment by ajtowns** [comment]
Nodes don't share their entire mempool, just new transactions that come in. Those transactions are prioritised by fee rate, see the code around `// Topologically and fee-rate sort the inventory we send for privacy and priority reasons.` in net_processing.cpp, though this will only have much effect when a lot of new transactions are being relayed at once.
