### ISSUE TITLE
TX fee estimation does not take into account time of day or day of week

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#21692]
There seem to be patterns regarding fee required based on time of day and day of week, which is not currently (last I checked) being factored into the fee estimation code. For example, rather than giving a duration, it perhaps ought to give a estimated day of the week or time of the day of anticipated inclusion into a block with a disclaimer that the estimate is based on patterns of the past (which do not predict the future).

In terms of specific development of a GUI wallet, it could be useful to have some visual representation of the minfees that were successful over the last 2 weeks to help the user decide on a suitable fee.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
