### ISSUE TITLE
Failed to start bitcoind using Ubuntu 20.10

### ISSUE THREAD

**Issue by la841** [bitcoin/bitcoin#21699]
Hey I keep getting this error when I run sudo systemctl start bitcoind.service

Job for bitcoind.service failed because the control process exited with error code.
See "systemctl status bitcoind.service" and "journalctl -xe" for details.

When I input sudo journalctl -xe I get this.

░░ The job identifier is 6033.
abr 15 16:16:36 sats-desktop bitcoind[7207]: Error: Error parsing command line arguments: Invalid parameter -daemonwait
abr 15 16:16:36 sats-desktop systemd[1]: bitcoind.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit bitcoind.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
abr 15 16:16:36 sats-desktop systemd[1]: bitcoind.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit bitcoind.service has entered the 'failed' state with result 'exit-code'.
abr 15 16:16:36 sats-desktop systemd[1]: Failed to start Bitcoin daemon.
░░ Subject: A start job for unit bitcoind.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit bitcoind.service has finished with a failure.
░░ 
░░ The job identifier is 6033 and the job result is failed.
abr 15 16:16:36 sats-desktop systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ Automatic restarting of the unit bitcoind.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
abr 15 16:16:36 sats-desktop systemd[1]: Stopped Bitcoin daemon.
░░ Subject: A stop job for unit bitcoind.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A stop job for unit bitcoind.service has finished.
░░ 
░░ The job identifier is 6113 and the job result is done.
abr 15 16:16:36 sats-desktop systemd[1]: bitcoind.service: Start request repeated too quickly.
abr 15 16:16:36 sats-desktop systemd[1]: bitcoind.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit bitcoind.service has entered the 'failed' state with result 'exit-code'.
abr 15 16:16:36 sats-desktop systemd[1]: Failed to start Bitcoin daemon.
░░ Subject: A start job for unit bitcoind.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit bitcoind.service has finished with a failure.
░░ 
░░ The job identifier is 6113 and the job result is failed.
lines 1841-1894/1894 (END)

When I input systemctl status bitcoind.service I get this:
bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-04-15 14:13:16 CEST; 21min ago
       Docs: https://github.com/bitcoin/bitcoin/blob/master/doc/init.md
    Process: 5604 ExecStart=/usr/local/bin/bitcoind -daemonwait -pid=/run/bitcoind/bitcoind.pid -conf=/home/sats/.bitcoin/bitcoin.conf -datadir=/home/sats/.bitcoin (code=exited, status=1/FAILURE)

abr 15 14:13:16 sats-desktop systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 5.
abr 15 14:13:16 sats-desktop systemd[1]: Stopped Bitcoin daemon.
abr 15 14:13:16 sats-desktop systemd[1]: bitcoind.service: Start request repeated too quickly.
abr 15 14:13:16 sats-desktop systemd[1]: bitcoind.service: Failed with result 'exit-code'.
abr 15 14:13:16 sats-desktop systemd[1]: Failed to start Bitcoin daemon.
~

Some idea how can I solve the problem??

**Comment by MarcoFalke** [comment]
you will need to use the service file for your version of Bitcoin Core, not from Bitcoin Core `master`

**Comment by la841** [comment]
Hi, I dont know what you mean by using the service file, could you explain further on that. 
On the other hand I see when I input systemctl status bitcoind.service I get as you see daemonwait. 
Should I edit ??
Service]
ExecStart=/usr/local/bin/bitcoind -daemonwait \
                            -pid=/run/bitcoind/bitcoind.pid \
                            -conf=/home/sats/.bitcoin/bitcoin.conf \
                            -datadir=/home/sats/.bitcoin**_


Thanks

**Comment by hebasto** [comment]
@la841 

> I dont know what you mean by using the service file

`bitcoind.service` is the service file.

If your Bitcoin Core version is v0.20.x, use https://github.com/bitcoin/bitcoin/blob/0.20/contrib/init/bitcoind.service

If your Bitcoin Core version is v0.21.x, use https://github.com/bitcoin/bitcoin/blob/0.21/contrib/init/bitcoind.service

**Comment by hebasto** [comment]
@la841 Is this issue resolved?

**Comment by danger89** [comment]
Yeah, but indeed they change the interface to `daemonwait`, which is a not valid parameter for the latest bitcoin core v0.20.1
