### ISSUE TITLE
Transaction needs a change address, but we can't generate it. 

### ISSUE THREAD

**Issue by ADCJustinH** [bitcoin/bitcoin#21698]
When I try and send btc I get this error:

**Transaction needs a change address, but we can't generate it. Please call keypoolrefill first**. I've called keypoolrefill from the console and it seems to run without error. However It has no effect and I remain unable to send.

I believe this has to do with using and old wallet (2010) which I added a passphrase to using 0.20.0 but otherwise remains untouched. Really would like to access these old funds but can't seem to figure out how.

Currently trying this on 0.21.0 on Windows 10.

**Comment by MarcoFalke** [comment]
Make sure to backup your wallet and share the output of `upgradewallet` RPC

**Comment by ADCJustinH** [comment]
{
  "wallet_name": "",
  "previous_version": 169900,
  "current_version": 169900,
  "result": "Already at latest version. Wallet version unchanged."
}

**Comment by MarcoFalke** [comment]
See also: https://github.com/bitcoin/bitcoin/issues/20871#issuecomment-756410847 and https://github.com/bitcoin/bitcoin/issues/16091#issuecomment-667079582

**Comment by ADCJustinH** [comment]
Thanks Marko, I got it working based on the first comment
