### ISSUE TITLE
I would love to work for bitcoing or get a full sponsorship! I believe I have the next upgrade to smart contracts

### ISSUE THREAD

**Issue by Bovicesdx25** [bitcoin/bitcoin#21704]
**Is your feature request related to a problem? Please describe.**
Yes- It will solve the massive wait time compared to all the other companies. This would allow bitcoin to potential maintain itself as the gold Standard but will also offer a more  feasible coin that will be copied buy all other. What makes me so sure about this well Ive been In all the top sales position for high networth individual and most important My mother was the top CPA of her class and I decided that I would become a back end developer or CPA. 

**Describe the solution you'd like**
I have found a way to save on massive computing power to run multiple transactions on the block chain and although yest it is still on the block chain the way that I invision this and have already see the most important technology needed to make this happen developed and we could make our own or use theirs

**Describe alternatives you've considered**
Clien (A) walks into Am/PM (C) daily and purvhases a coffee. At that point there are 3 Ledgers that every individual has 2 are perminenent and the 3rd one is created everytime client (A) meets a new individual. 

Here is the genious part client A and C will both have a credit and debit ledge Making sure that there is no discrepency. Once the agree to the transaction they each give a quick hand signature (for lower income folks I already have a cheap alternative covered by the state. Now The othern 2 Ledgers 1 is the Master ledger and that just shoes the amount of money that went out with the amount of money that went in ( I am leaving a secret on how to connect those two) Once they sign than a simple piece of code will be stored into a massive database that could easily be found .
Fraud- No fraud can occured be the 2 master ledger is the one thatis apporved by the client at the end of the day and then once that is approved with no problems than the syustem records the plus and minus  on the main accounting ledger.

CVC for you haters that will say but man how is everyone going to create a platform that validates ID. Well here is where you get that. You can do something like CVC or something like e-verify. This way no fraud can occurrr.

All fraud will be dealth by instead of the big banks now we call the Validators or Enforcers. Their are major compsanies of these enforcers and they get a commission from the individual that conducted the Fraud. 

Why would people want to use us, We will team up with bRave for  secure internet where advertisers pay our clients and our company. The faster that people validate their transaction and do x amount permonth at an early time they will get a coin.

Novalty Items depite everything being digital there will eventually have small writebands that can have the Face for the $100 bill as bitcoin, $50 ether etc. And that money will go aside for alternative devices to cell phones. 

Most importantly if you give me the team to work this out and you give me $75,000 to bribe some people in Mexico we will get rid of trans union and this will be the way of the future.

This is just one of the many Idea I have. I am 1/4 done with my Bootcamp and man I can promise you that if you give me a chance and we geta solid investor. I also Get a solid team of programers we will change the game for ever. I left some major points out on purpose and trust me There will not be any Information being sold to the tech giantes because I plan on making the CEO of this corporation a split between the founder of bitcoin/ Etherium or the On man that has demonstrated his qualifications are beyond. We will either use an existing crypto coin or start our own. I have 13 years of financial experience and have spent the last 2 years showing normal people how to sale FSBO alone.

Now if you guys want to make a company that will sale for no less than 50% if not more than what zillow is worth we can start there and Ill have it sold. Here is the rules we will all have to have equal pay and if not equal job security for as long as any company is in operation. I want to donate 10% of my salary to underprivileged kids and start programs for them to learn how to code , Help Mothers that are survivors of domestic violence get out of that situation, and last but not least I want to help a group of society that many frown upon and most of the time its not there fault and if its not there fault I will be using my own money and your welcome to help. I am a reborn Christian and Ill tell you what there is no way a sane individual with an average of 110 appointments a month and  50 closing  would make stuff up about the super natural and David Paulides, and Steve from how to hunt showed me  only the unknown can scare 3 hunters fully armed with 3 high capacity hunting riles and a slug that can stop an engine. So Id like to help with awareness on that issue. I know who created the pyramids, the orbs on the noaa bouys and much more. 

With that said you have a sense of who I am and know this money isnnt everything for me its starting something and seeing it through. At age 28 I passed on a chance to make 15 million in 6 months. Why? Because I helped a pension company make 5 million with the people I brought on. This could be the dream Team. If you go ahead and steal my idea just know I will not hate you for it because a group already stole an appraised 250k app from me. They are idiots though because  with that money they made and I heard they made 2.5 million they could have invested it with my family in mexico in a gold mine and sold it for 890 million.

**Additional context**
I know I am not your typical guy and I have not finished my Ruby training but this can not wait. If we simply work on the real estate app just to get some money going I know that I can sell it for over  100 million or collect that in ech monthly, If we nee more still we can takes western union out and this goes to the top where we will all go to LOS Pinos Mexico and They will pass a law for us. Bancomer will give use 50-70 million in sponsorship. Goodbye western union.

Than this app this is something I have been looking at a substitue to help cute down time on bit coing transactions and the gas price and make it as easy as using a debit card. BItcoin - You could be the Visa of Crypto just saying and ill tell you how they work with banks

urfinanceninsguy@protonmail.com

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
