### ISSUE TITLE
RAM usage issue

### ISSUE THREAD

**Issue by dzmitrykliapkou** [bitcoin/bitcoin#21703]
Hi there!
We are trying to run full-node on AWS EC2 r5.large instance with 16GB RAM but we are facing a strange issue. Despite any options listed here bitcoind memory usage constantly grows, so ~6min after start it uses 100% of RAM.

Here is the command we use to run bitcoind:
```
usr/local/bin/bitcoind -daemon \
-pid=/run/bitcoind/bitcoind.pid \
-conf=/etc/bitcoin/bitcoin.conf \
-datadir=/data/bitcoind \
-txindex=1 \
-sysperms=true \
-dbcache=5000 \
-maxmempool=100
```
How can we limit bitcoind memory usage? Thanks in advance

**Comment by jonatack** [comment]
Which version of bitcoin core are you running? (Did you try leaving -dbcache at the default value of 450?)

**Comment by dzmitrykliapkou** [comment]
Hi!
We use Bitcoin Core version v0.21.0
As for default dbcache value - yes, we've tried. Now it is running without -dbcache argument (as I understand default value is applied in this case), and it uses ~20GB of memory.

**Comment by dzmitrykliapkou** [comment]
Solved here
https://github.com/bitcoin/bitcoin/issues/22329
