### ISSUE TITLE
Develop watch-only wallet

### ISSUE THREAD

**Issue by 78bash** [bitcoin/bitcoin#21723]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a watch only wallet on bitcoin-qt with bitcoin core.

**Describe the solution you'd like**
Password/PIN protected, QR-code capability.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
