### ISSUE TITLE
Increase block size;  Show that BTC can retain top coin status;  Fix the mempool!

### ISSUE THREAD

**Issue by ryny24** [bitcoin/bitcoin#21739]
**Is your feature request related to a problem? Please describe.**
Yes, the mempool is a disaster. It won't be fixed for a while. OR... Increase the block size like many other coins have already. It works!

**Describe the solution you'd like**
Think outside the box. Let Bitcoin scale. Don't let Bitcoin fall into the cluster of junk coins (where it is heading...)

**Describe alternatives you've considered**
All other alternatives have failed.

Sorry if this is not the right spot for this, but someone has to do something. Soon!

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
