### ISSUE TITLE
gui: Node appears as `Unroutable` in peers list

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#21747]
![image](https://user-images.githubusercontent.com/15256660/115653691-3a13de80-a2f5-11eb-8464-96e4c109ab5d.png)

This is using the [bitcoin-s](https://github.com/bitcoin-s/bitcoin-s) node, I am unsure if this is something wrong on our end, or on bitcoin core's end. Messages are able to be passed back and forth just fine. This is shown for the node running on the local computer and one on a separate computer.

**Comment by sipa** [comment]
This is expected, albeit confusing. It just means that node can't be reached from the internet (127.0.0.1 is a non-public IP).

**Comment by benthecarman** [comment]
> This is expected, albeit confusing. It just means that node can't be reached from the internet (127.0.0.1 is a non-public IP).

How about for the `Type`?

**Comment by sipa** [comment]
What type?

**Comment by benthecarman** [comment]
> What type?

![image](https://user-images.githubusercontent.com/15256660/115654726-53b62580-a2f7-11eb-812c-a84636bf86a9.png)

**Comment by MarcoFalke** [comment]
Incoming peers don't have a type (other than "incoming"). Is this elided? What version are you using?

**Comment by jonatack** [comment]
Right, inbound peers have a connection direction but not type yet, as we can't infer full relay or block relay status from fRelay / fRelayTxes (`Wants Tx Relay` in the details area or RPC getpeerinfo `relaytxes`). These changes were made in January and aren't in a release yet.

**Comment by benthecarman** [comment]
> Incoming peers don't have a type (other than "incoming"). Is this elided? What version are you using?

This is on e7776e20ed0ddf41d15b3d2df87a92ea6666226c

**Comment by MarcoFalke** [comment]
Was this bug introduced in https://github.com/bitcoin-core/gui/commit/6fc72bd6f030c8b49e8b9f68188413766a239d73 ?

See also the tested ACKs, which show the empty string here: https://github.com/bitcoin-core/gui/pull/179#issuecomment-780585528

**Comment by jonatack** [comment]
What different behavior are you expecting?

**Comment by jonatack** [comment]
ISTM this is the expected behavior and the issue can be closed.

**Comment by MarcoFalke** [comment]
I think the type shouldn't be empty string but "Inbound", no?

**Comment by jonatack** [comment]
We do the same with `-netinfo` after this topic was discussed in January; direction and type are different columns. For users, inbound/outbound is a direction. I proposed a sortable "Direction" column immediately next to the "Type" column to display Inbound/Outbound rather than the current arrows, it had an enthusiastic reception with ACKs by @hebasto and @jarolrod IIRC, but was opposed by another contributor. I could propose it again, e.g. like https://github.com/bitcoin-core/gui/pull/179#pullrequestreview-564896296 and https://github.com/bitcoin-core/gui/pull/179#pullrequestreview-564822423.

**Comment by MarcoFalke** [comment]
Ok, closing for now.

If this is an issue, it might be good to file this in the gui repo instead.

**Comment by jonatack** [comment]
Yes, I'll have a look at this tomorrow over on the GUI repo.
