### ISSUE TITLE
CConnman::SocketEvents() may poll the wrong socket

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#21744]
Adverse scenario:

1. thread "net"
```
CConnman::ThreadSocketHandler()
  CConnman::SocketHandler()
    CConnman::SocketEvents()
      CConnman::GenerateSelectSet()
        Cycles through CConnman::vNodes and remembers some sockets to
        be polled for readiness later by CConnman::SocketEvents().
        Lets say socket (file descriptor) 10 is remembered.
```

2. thread "msghand"
```
CConnman::ThreadMessageHandler()
  PeerManagerImpl::ProcessMessages()
    PeerManagerImpl::ProcessMessage()
      PeerManagerImpl::PushNodeVersion()
        CConnman::PushMessage()
          CConnman::SocketSendData()
            CNode::CloseSocketDisconnect()
              Closes socket 10.
```

3. thread "opencon"
```
CConnman::ThreadOpenConnections()
  CConnman::OpenNetworkConnection()
    CConnman::ConnectNode()
      CreateSock()
        Creates a new socket, reusing file descriptor 10.
```

4. thread "net"
```
CConnman::ThreadSocketHandler()
  CConnman::SocketHandler()
    CConnman::SocketEvents()
      polls the remembered socket 10, which corresponds to a different
      connection now (bug)
```

As a result the following logic may not hold:

https://github.com/bitcoin/bitcoin/blob/e16f8720dca2de1040478968c9f3ca07644a04b7/src/net.cpp#L1306-L1315

I think the severity of this is low and that it has a low chance of happening. However the pattern of "remember a socket by its file descriptor number and use it later, concurrently with other threads that might close it" better be avoided. That pattern could lead to closing or writing to the wrong socket which would be more severe.

**Comment by vasild** [comment]
This is surprisingly difficult to fix (without doing huge amount of changes). I see two ways to address it:

1. Hold the socket mutex while `poll()`ing, so that other threads that want to close the socket would have to wait for the `poll()` to finish. Not acceptable IMO.
2. Lazy close with reference counting. Increment the reference count of the socket during `poll()`. Whenever a thread wants to close the socket (disconnect a peer) it should disable the socket for send/recv (e.g. `shutdown(2)`) but not `close(2)` it if reference count is >0 and somebody else should close all disabled sockets with reference count of 0.

**Comment by practicalswift** [comment]
@vasild 

Interesting find! Thanks for reporting.

May I ask how you found this issue?

Was it found as part of the `Sock` encapsulation project, or a related fuzzing find? :)

Impressive find either way.

**Comment by vasild** [comment]
> Was it found as part of the `Sock` encapsulation project...

Correct! :)

In https://github.com/bitcoin/bitcoin/pull/21878, while replacing `SOCKET` with `Sock` in `CConnman::SocketEvents()` one option was to keep pointers to the `Sock` objects and close the sockets by destroying those objects, but (because of this bug) this would have ended up with dangling pointers, pointing to possibly-deleted-by-other-threads objects.

This is the reason that PR keeps the `Sock` objects alive and calls `Sock::Reset()` from `CNode::CloseSocketDisconnect()` instead of something like `delete m_sock`.

**Comment by vasild** [comment]
Hmm, maybe the following changes in https://github.com/bitcoin/bitcoin/pull/21878 would fix this bug elegantly (doing the [lazy close](https://github.com/bitcoin/bitcoin/issues/21744#issuecomment-839619709) I mentioned above):
* Change `CNode::m_sock` from `std::unique_ptr<Sock>` to `std::shared_ptr<Sock>`.
* In `CNode::CloseSocketDisconnect()` do `m_sock.reset()` (reducing the ref count stored in the shared_ptr and destroying the `Sock` object if ref count is 0).
* Take a copy of `std::shared_ptr<Sock>` in `CConnman::SocketEvents()` or its replacement `Sock::WaitMany()`. The copy will automatically keep the ref count >0 during `poll()`.

I will consider this more carefully.

**Comment by vasild** [comment]
> maybe the following changes in #21878 would fix this bug elegantly...

Done. In addition to the above, `CConnman::ListenSocket::sock` also had to be changed from `unique_ptr` to `shared_ptr` because we feed those sockets to `Sock::WaitMany()` too.

This issue is now resolved by commit `net: use Sock::WaitMany() instead of CConnman::SocketEvents()` in https://github.com/bitcoin/bitcoin/pull/21878.
