### ISSUE TITLE
Error messages for invalid address

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#21741]
Can we add more information in error messages for invalid address especially the errors mentioned in PR: https://github.com/bitcoin/bitcoin/pull/20832/

Example: 

Change https://github.com/bitcoin/bitcoin/blob/f385ad765174afb02e60900581612a19c143cf83/src/key_io.cpp#L103

To

```C++
error_str = "Invalid prefix for Bech32 address. Valid Bech32 address starts with `bc1` (mainnet) or `tb1` (testnet)";
```

Context: https://github.com/bitcoin-core/gui/pull/280#issuecomment-820957002

**Comment by tylerchambers** [comment]
concept ack. error messages should be human readable and actionable. this is a good improvement.

**Comment by kristapsk** [comment]
Concept ACK

**Comment by brunoerg** [comment]
Concept ACK

**Comment by vincenzopalazzo** [comment]
Concept ack.

**Comment by prayank23** [comment]
4 Concept ACKs for this issue and few reviews in PR: https://github.com/bitcoin/bitcoin/pull/21755

Will be helpful if you could comment on changes proposed in https://github.com/bitcoin/bitcoin/pull/21755/commits/af9979837d1a9d4844d2701f4eeb7aed353d8af9

**Comment by brunoerg** [comment]
Going to review soon.

**Comment by MarcoFalke** [comment]
Not sure what the status is. I guess someone needs to rebase https://github.com/bitcoin/bitcoin/pull/21755?
