### ISSUE TITLE
followups: Various potential improvements arising out of chainman-deglobalizing review

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#21766]
There are a few potential improvements mentioned by various reviewers of the chainman-deglobalizing work that are deserving of a tracking ticket, but are perhaps either not crucial to the main thrust of the work or the flaws already existed before the work. Let's discuss and collate them here so that we don't lose track of them!

1. `m_chain` methods should perhaps require holding `cs_main`
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r613951719
2. `Ensure*()` in src/rpc should be called at the top of functions to fail as early as possible
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r613992845
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r613942578
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r613944794
3. IncrementExtraNonce does not need `cs_main`, and the locking scope can be limited
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r613967463
4. `CoinsDB.Cursor()` passes ownership to caller and should return a `std::unique_ptr`
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r614696860
5. Call to `GetNetworkHashPS` in `getnetworkhashps` contains many operators, which may increase risk of precedence bugs
    - https://github.com/bitcoin/bitcoin/pull/21391#discussion_r613953875
6. Avoid repeated calls to `ActiveChain()` where appropriate
    - https://github.com/bitcoin/bitcoin/pull/21270#discussion_r592357247
7. Review whether or not `m_blockman` member of `ChainstateManager` needs `cs_main` to be accessed
    - Various
8. Review whether or not to support running bitcoin without a chainman
    - https://github.com/bitcoin/bitcoin/pull/21767#discussion_r628905295
9. Investigate how indexing interacts with `CChainState`
    - https://github.com/bitcoin/bitcoin/pull/21767#discussion_r641791366

Please feel free to comment here for extra ones I've missed!

**Comment by jnewbery** [comment]
Concept ACK. Please tag me in any PR you open.

**Comment by MarcoFalke** [comment]
4 is addressed in #22263 (can be checked off in OP?)
