### ISSUE TITLE
i have my passphrase, but lost everything else. Not trying to be a dick, but can someone point me to tools??

### ISSUE THREAD

**Issue by cellurl3** [bitcoin/bitcoin#21769]
I have been using bitcoin-qt for 10 years. I lost everything but the key-phrase......
The passphrase doesn't seem like bip39, so  dunno what to do. One of my passphrase words is longer than the bip39 list....

Can anyone throw me a bone ??

Thanks guys! I wish I could write c++ half as well as you do!

JP
Bluff City USA

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
