### ISSUE TITLE
Release 0.21.0 Certificate Revoked

### ISSUE THREAD

**Issue by AlanCarlyle** [bitcoin/bitcoin#21772]
I just download Bitcoin for Windows from https://bitcoin.org/en/bitcoin-core/ and the executables signing certificate had been revoked.
Is the website I mentioned above valid or a scam one trying to get malware on my computer?

I noticed that 0.21.0 is not available here https://bitcoincore.org/en/download/ so suspect there is something up with the other location.

**Comment by achow101** [comment]
See https://github.com/bitcoin/bitcoin/issues/21725#issuecomment-823411723 and https://github.com/bitcoin-core/gui/issues/252#issuecomment-802591628
