### ISSUE TITLE
build: Static build behavior depends on the used compiler

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#21771]
The [`qt_mac_applicationIsInDarkMode`](https://github.com/qt/qtbase/blob/5.12.10/src/corelib/kernel/qcore_mac_objc.mm#L217-L227) function
```
bool qt_mac_applicationIsInDarkMode()
{
#if QT_MACOS_PLATFORM_SDK_EQUAL_OR_ABOVE(__MAC_10_14)
    if (__builtin_available(macOS 10.14, *)) {
        auto appearance = [NSApp.effectiveAppearance bestMatchFromAppearancesWithNames:
                @[ NSAppearanceNameAqua, NSAppearanceNameDarkAqua ]];
        return [appearance isEqualToString:NSAppearanceNameDarkAqua];
    }
#endif
    return false;
}
```

behavior depends on the compiler that was used for static build.

It returns `true` or `false` depending on OS appearance setting on old compilers:
- apple clang 10.0.1 on macOS Mojave 10.14.6 (18G8022)
- llvm clang 8.0.0 used in depends

It always returns `false` on newer compilers:
- apple clang 12.0.0 on macOS Catalina 10.15.7 (19H524) and Big Sur 11.2.3 (20D91)
- llvm clang 10.0.1 in depends, see https://github.com/bitcoin/bitcoin/pull/19817#issuecomment-810949389

**Comment by hebasto** [comment]
cc @dongcarl @fanquake @theuni

**Comment by hebasto** [comment]
Further debugging shows that being compiled with newer compilers the [`effectiveAppearance`](https://developer.apple.com/documentation/appkit/nsappearancecustomization/1535147-effectiveappearance?language=objc) returns [`NSAppearanceNameAqua`](https://developer.apple.com/documentation/appkit/nsappearancenameaqua?language=objc) regardless of the actual appearance setting.

**Comment by hebasto** [comment]
Additional info.

Old compilers set the `sdk` field explicitly:
- apple clang 10.0.1 on macOS Mojave 10.14.6 (18G8022)
```
$ otool -l src/qt/bitcoin-qt | grep -A 7 -B 1 BUILD_VERSION
Load command 9
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform macos
       sdk 10.14
     minos 10.14
    ntools 1
      tool ld
   version 450.3
```
- llvm clang 8.0.0 used in depends
```
$ depends/x86_64-apple-darwin18/native/bin/x86_64-apple-darwin18-otool -l src/qt/bitcoin-qt | grep -A 7 -B 1 BUILD_VERSION
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 10.14
      sdk 505.0
   ntools 1
     tool 3
  version 530.0
```

Newer compilers do not assign the `sdk` field value at all:
- apple clang 12.0.0 on Big Sur 11.2.3 (20D91)
```
% otool -l src/qt/bitcoin-qt | grep -A 7 -B 1 BUILD_VERSION
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 10.14
      sdk n/a
   ntools 1
     tool 3
  version 609.8
```
- llvm clang 10.0.1 in depends (https://github.com/bitcoin/bitcoin/pull/19817)
```
$ depends/x86_64-apple-darwin18/native/bin/x86_64-apple-darwin18-otool -l src/qt/bitcoin-qt | grep -A 7 -B 1 BUILD_VERSION
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 10.14
      sdk n/a
   ntools 1
     tool 3
  version 530.0
```

And [Qt doc](https://doc.qt.io/qt-5/macos.html#opting-out-of-macos-behavior-changes) states:
> ... macOS's system frameworks will sometimes decide whether or not to enable behavior changes _based on the SDK_ you built your application with.

**Comment by hebasto** [comment]
Ok, the root of the issue is the https://github.com/llvm/llvm-project/commit/25ce33a6e4f3b13732c0f851e68390dc2acb9123 commit since llvm clang 10.0.0.

**Comment by fanquake** [comment]
Closing now that #21793 is merged.
