### ISSUE TITLE
scantxoutset fails via javascript rpc call in mainnet (ok in testnet) with: OperationalError: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by educob** [bitcoin/bitcoin#21774]
Hi.

I can successfully  request utxos in mainnet with:
`bitcoin-cli -rpcport=8332 -rpcuser=xxxx -rpcpassword=xxxx scantxoutset start '["addr(bc1qnffp2jccqnwjwymkheqkkkrgdhslxyg3wpu0rq)"]'`

But 
```
const Client = require('bitcoin-core')
let btcNode = new Client( { host, username, password, port, timeout: 30000 } ) 
const address = { _id: 'bc1qnffp2jccqnwjwymkheqkkkrgdhslxyg3wpu0rq', ...}
const utxos = await btcNode.command('scantxoutset', 'start', [`addr(${address._id})`])
```
fails in mainnet (ok in testnet) with 

```
OperationalError: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/graphql/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at Socket.emitRequestTimeout (_http_client.js:717:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  cause: Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/graphql/node_modules/request/request.js:816:19)
      at Object.onceWrapper (events.js:421:28)
      at ClientRequest.emit (events.js:315:20)
      at ClientRequest.EventEmitter.emit (domain.js:485:12)
      at Socket.emitRequestTimeout (_http_client.js:717:9)
      at Object.onceWrapper (events.js:421:28)
      at Socket.emit (events.js:327:22)
      at Socket.EventEmitter.emit (domain.js:485:12)
      at Socket._onTimeout (net.js:481:8)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7) {
    code: 'ESOCKETTIMEDOUT',
    connect: false
  },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
```

Other commands like` btcNode.sendRawTransaction estimateSmartFee getBlockByHash` works ok.

Thanks.

update: in the server I opened a single btcNode connection that I reuse all the time.

**Comment by jonatack** [comment]
Hi @educob, do you see this issue when running the RPC manually on the command line?

**Comment by jonatack** [comment]
(Ok, the command line works. It looks like the issue here isn't with Bitcoin Core.)

**Comment by educob** [comment]
You mean with "bitcoin-cli"? It works ok with bitcoin-cli.
It only fails with rpc javascript.

**Comment by MarcoFalke** [comment]
Can you report the issue to the javascript library? This is the issue tracker for Bitcoin Core.

**Comment by educob** [comment]
I'll do that. I t hought it was a Bitcoin Core issue as it's the node giving a socket timeout.

**Comment by MarcoFalke** [comment]
What is `time bitcoin-cli -rpcport=8332 -rpcuser=xxxx -rpcpassword=xxxx scantxoutset start '["addr(bc1qnffp2jccqnwjwymkheqkkkrgdhslxyg3wpu0rq)"]'`?

**Comment by MarcoFalke** [comment]
Also, what is `-rpcservertimeout` (on the server)?

**Comment by educob** [comment]
It says time: not found.

I think this is a bitcoin core issue cause it works in testnet but not in mainet.

**Comment by MarcoFalke** [comment]
How long does it take to execute the bitcoin-cli command?

**Comment by sipa** [comment]
presumably the javascript library uses a timeout that is too low for how long the operation actually takes

Bitcoin Core doesn't know or care whether the client is js or bitcoin-cli.

**Comment by educob** [comment]
it takes 39 seconsd. An eternity.

**Comment by educob** [comment]
I haven't set rpcservertimeout on the server.

**Comment by MarcoFalke** [comment]
The default for `-rpcclienttimeout` on the client (bitcoin-cli) is 900. You set the timeout to 30000 (which I presume is 30 seconds)?

So you can fix your issue by increasing the timeout in your JavaScript code.

**Comment by educob** [comment]
Thanks.

But I am troubled by the fact that it takes 39 seconds to look up an address without a single utxo. 
It this normal?

**Comment by MarcoFalke** [comment]
The utxo set is several GB of data. scantxoutset is linear complexity in the size of the set, because the utxo set is not indexed by address (or scriptPubKey).

**Comment by MarcoFalke** [comment]
If you need faster performance you could try a (watch-only) wallet or an external service (see #14053 for discussion)

**Comment by educob** [comment]
Thanks for your help.

Have a nice day.
