### ISSUE TITLE
Remove -deprecatedrpc=addresses flag and corresponding code/logic

### ISSUE THREAD

**Issue by mjdietzx** [bitcoin/bitcoin#21797]
The following RPCs:  `gettxout`, `getrawtransaction`, `decoderawtransaction`,
   `decodescript`, `gettransaction`, and REST endpoints: `/rest/tx`,
   `/rest/getutxos`, `/rest/block` deprecated the following fields (which are no
   longer returned in the responses by default): `addresses`, `reqSigs`.
   The `-deprecatedrpc=addresses` flag must be passed for these fields to be
   included in the RPC response. This flag/option will be available until v23, at which
   point the deprecation will be removed entirely. Note that these fields are attributes of
   the `scriptPubKey` object returned in the RPC response. However, in the response
   of `decodescript` these fields are top-level attributes, and included again as attributes
   of the `scriptPubKey` object.

The original issue https://github.com/bitcoin/bitcoin/issues/20102 was resolved in this PR https://github.com/bitcoin/bitcoin/pull/20286, and from v23 ("addresses" and "reqSigs" deprecated) "ExtractDestinations" should be removed.

**Comment by mjdietzx** [comment]
Intent is to add this issue to milestone 23.0. Not sure how to do this or if I'm able to

**Comment by MarcoFalke** [comment]
Branch-off will be in about 60 days (#20851). Do you want to address this issue or did you file this for someone else to pick up?

**Comment by mjdietzx** [comment]
I'd be happy to address the issue myself. Just figured I'd create an issue to make sure it isn't forgotten. Anyways I'll aim to have it ready around branch-off and open the PR then

**Comment by MarcoFalke** [comment]
@mjdietzx Are you still working on this?

**Comment by mjdietzx** [comment]
Yessir, thanks for the heads up. Just opened the PR 😁
