### ISSUE TITLE
Ask for password after balance check when sending coins

### ISSUE THREAD

**Issue by subSTRATA** [bitcoin/bitcoin#2180]
If user has X bitcoins in encrypted wallet and wants to send them all, and transaction would require fee, here is how
application logic goes right now:

1. Put address and X bitcoins into appropriate fields then click on "Send" button.
2. Confirm send action.
3. Type password and proceed.
4. Bitcoin-qt will complain about not having enough bitcoins to pay fee.

Steps 3. and 4. should be reversed. Additionaly, step where client asks user if he or she is OK with paying extra fee
due to young coins and / or transaction size should come before typing password.

**Comment by jonasschnelli** [comment]
This was fixed by https://github.com/bitcoin/bitcoin/pull/2958. Closing.
