### ISSUE TITLE
Block synchronization

### ISSUE THREAD

**Issue by cloudjacky** [bitcoin/bitcoin#21801]
When a new node was established and started.

Sync blocks.

In func of PeerManagerImpl::ProcessMessage, 

I found the logic to handle the msg of 'GETBLOCKS',

But no code was found to request 'GETBLOCKS'? why?

**Comment by rebroad** [comment]
@cloudjacky that code is in older versions of bitcoin - https://bitcoin.stackexchange.com/ is a better place for these sorts of questions rather than assuming it's an issue ;)

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
