### ISSUE TITLE
User Display Language broken on 0.21.1

### ISSUE THREAD

**Issue by pcharest** [bitcoin/bitcoin#21847]
An old node was running with the french interface. When i updated it to 0.21.1 i notice the interface became in english. I checked the setting and 'français' was written. I tried to put it back in english to reput it in french but the interface is always in english. I tried spanish, the language interface change. So french language seem broken in bitcoin core qt with this release. I install the 0.21.0 version and the interface was working in french.

I tried with a new bitcoin core node on 2 others computers and same behavior (Windows 10 and Ubuntu 20.04).

I took the binary from https://bitcoincore.org/bin/bitcoin-core-0.21.1/ and validate the checksum.

**Comment by pcharest** [comment]
Do i need to write the issue in https://github.com/bitcoin-core/gui or it's okay here?

**Comment by michaelfolkson** [comment]
pcharest: Yes please. Open an issue in that repo and close this one. Thanks!

**Comment by pcharest** [comment]
Open in gui repo
