### ISSUE TITLE
Why don't we have more checkpoints?

### ISSUE THREAD

**Issue by abhiShandy** [bitcoin/bitcoin#21886]
**Is your feature request related to a problem? Please describe.**

`src/chainparams.cpp:146` has few checkpoints for the mainnet using a table of block and blockhash. Why does it end at block 295000?

**Describe the solution you'd like**

Either add a comment with an explanation for given number checkpoints or add checkpoints at an agreed block interval.

**Describe alternatives you've considered**

**Additional context**

![Screen Shot 2021-05-09 at 8 58 49 AM](https://user-images.githubusercontent.com/6998593/117559740-82791d80-b0a5-11eb-8ee7-3aeb0689c304.png)

**Comment by brunoerg** [comment]
See this answer on [bitcoin stackexchange](https://bitcoin.stackexchange.com/questions/1797/what-are-checkpoints).

I think they are not so useful and if we need to use them, it means the system is already broken.

**Comment by kristapsk** [comment]
It is not uncommon for people to add additional checkpoints to their nodes. For example, Bitcoin Knots, which is patched version of Bitcoin Core by @luke-jr, [adds additional checkpoints](https://github.com/bitcoinknots/bitcoin/commit/0ce55769950ab813a6d1cee378f42b1a606dca1f).

**Comment by MarcoFalke** [comment]
Could make sense to mention briefly in the code what https://bitcoin.stackexchange.com/a/70824/3576 says?

**Comment by brunoerg** [comment]
I think so, @MarcoFalke.

**Comment by abhiShandy** [comment]
@brunoerg Shall I remove the checkpoints (and the validation code) to avoid the confusion?

**Comment by sipa** [comment]
@abhiShandy No, they're still needed to prevent low-difficulty header spam. It's not a particularly strong attack, but without checkpoints it's trivial. The current checkpoints suffice to make it sufficiently expensive.

**Comment by adamjonas** [comment]
Closing since the questions seems to be answered sufficiently.

Checkpoints are currently required, but see https://github.com/bitcoin/bitcoin/pull/25725 for a glimpse into the future.
