### ISSUE TITLE
Enable reading of pchCommand before Complete()

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#21896]
I always found it useful to be able to see what message was incoming from another node as soon as the header had been received, but since #16202 it no longer appears to be possible to discern the pchCommand until the complete message has been received.

Is there a way to determine the message as soon as the header has been received? This could be useful functionality in order to be able to reduce bandwidth, and for logging and debugging.

**Comment by MarcoFalke** [comment]
> This could be useful functionality in order to be able to reduce bandwidth, and for logging and debugging.

The message type is already logged, so I am not sure what you are asking for. Also how would this save bandwidth?

**Comment by rebroad** [comment]
especially during IBD blocks can come in very slowly from peers. without being able to know what a message is until we've downloaded it, it makes it difficult to know if a peer is stalling block download / IBD, as a block may be coming in, but take a while to download each block. When it was possible to process the message header before the message arrived, I was using this to work out the stallers in a better way than the current stall logic.
