### ISSUE TITLE
Crash when opening wallet

### ISSUE THREAD

**Issue by Bix-Nood-Networks** [bitcoin/bitcoin#21904]
Bitcoin Core crashes when trying to open a wallet on Windows because your application logic is nonsensical. When Bitcoin Core was installed, I chose the root level of a dedicated volume (E:) for Bitcoin to store its data on. When I go to open a new wallet, it pegs one CPU core to 100%. Looking at the debug log, it is repeatedly trying to access E:\System Volume Information, and is getting an access denied message because this user doesnt have administrative rights, so it cant access this directory. Your application shouldnt be accessing this directory just to present an open file dialog, and it should be smart enough to throw an exception with an error message to the user and not get stuck in an infinite loop if it encounters problems with file permissions.

**Comment by hebasto** [comment]
Also #21136, #20081.

**Comment by promag** [comment]
What version are you running?

**Comment by hebasto** [comment]
@Bix-Nood-Networks 

Do you mind testing #21907?

**Comment by Bix-Nood-Networks** [comment]
Version 0.20 and 0.21, both exhibited the same issue. I realized that you guys finally support block pruning, so I ended up just enabling that and doing away with the external volume, so I cant really reproduce it easily anymore, but i'm guesing #21907 will likely fix it.
