### ISSUE TITLE
rpc: The RPC result contains '\n'

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#21916]
On master (e175a20769b5a7b98ee3082d89f9d4f31a4503d6):
```
$ src/bitcoin-cli createwallet "hww" true true "" true true true
{
  "name": "hww",
  "warning": "Empty string given as passphrase, wallet will not be encrypted.\nWallet is an experimental descriptor wallet"
}
```

Is it expected?

**Comment by laanwj** [comment]
There's no problem with JSON strings containing newlines. I'd agree a list of errors would have been more elegant, but I am not sure it is worth switching this around again now.

**Comment by MarcoFalke** [comment]
> I think it was first introduced #17070

This existed before for `createwallet`. 17070 changed the separator from "`; `" to "`\n`".
