### ISSUE TITLE
no response when spamming gettransaction

### ISSUE THREAD

**Issue by mrbianchi** [bitcoin/bitcoin#21923]
Hello, I'm using w10 64 bits and spamming gettransaction jsonrpc on differents txids
Rarely I get no rpc response but I don't know why

On ubuntu server works fine

**Comment by fanquake** [comment]
Given the lack of information provided (you haven't filled out the issue template, no version info, no logs, no example commands etc) there's not much that can be done here. Going to close for now. We can reopen if/when you provide more information.
