### ISSUE TITLE
listransactions : documentation missing : erasure of txs with negative confs

### ISSUE THREAD

**Issue by mrbianchi** [bitcoin/bitcoin#21924]
I figured out that conflicted transactions are erased from the list

How much many time is needed or in which conditions they are erased?

**Comment by mostafarahimifard** [comment]
🤏👍👍👍👍

**Comment by mrbianchi** [comment]
> > I figured out that conflicted transactions are erased from the list
> 
> How can I reproduce this issue?
> 
> What arguments did you use with `listtransactions` and the values for them?
> 
> Which version of Bitcoin Core are you using?
receive transactions , use replace by fee , the new tx should be confirmed , wait (i dont know how much confirmations or time, the replaced tx will dissapear)
"*" 1000 0 true

**Comment by mrbianchi** [comment]
I got confused, I'm sorry
