### ISSUE TITLE
Compiling macOS environment on Ubuntu 18.04

### ISSUE THREAD

**Issue by BlockGardener** [bitcoin/bitcoin#21938]
I have an issue compiling the macOS environment for Bitcoin 0.21 and Bitcoin 0.21.1 on Ubuntu 18.04.

I installed the following dependencies:

sudo apt-get install curl librsvg2-bin libtiff-tools bsdmainutils cmake imagemagick libcap-dev libz-dev libbz2-dev python3-setuptools libtinfo5
sudo apt-get install make automake cmake curl g++-multilib libtool binutils-gold bsdmainutils pkg-config python3 patch

The following commands where executed to compile the macOS environment:

wget https://github.com/bitcoin/bitcoin/archive/refs/tags/v0.21.0.tar.gz
tar -xzvf v0.21.0.tar.gz
cd bitcoin-0.21.0
mkdir -p depends/sdk-sources
mkdir -p depends/SDKs
curl https://bitcoincore.org/depends-sources/sdks/MacOSX10.14.sdk.tar.gz -o depends/sdk-sources/MacOSX10.14.sdk.tar.gz
tar -C depends/SDKs -xf depends/sdk-sources/MacOSX10.14.sdk.tar.gz
cd depends
make HOST=x86_64-apple-darwin16

The compiling results in multiple errors regarding "./boost/config/detail/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found", see attached txt file for the complete compiling output.

Compiling output: [output.txt](https://github.com/bitcoin/bitcoin/files/6470698/output.txt)

**Comment by fdoving** [comment]
You have the wrong SDK.

Here is the guide to create the correct one:
https://github.com/bitcoin/bitcoin/blob/0.21/contrib/macdeploy/README.md

And if you look at this, there are some hints about the filename and where the depends-system looks for it:
https://github.com/bitcoin/bitcoin/blob/0.21/depends/hosts/darwin.mk

**Comment by Original-Tasty** [comment]
> 
> 
> You have the wrong SDK.
> 
> Here is the guide to create the correct one:
> https://github.com/bitcoin/bitcoin/blob/0.21/contrib/macdeploy/README.md
> 
> And if you look at this, there are some hints about the filename and where the depends-system looks for it:
> https://github.com/bitcoin/bitcoin/blob/0.21/depends/hosts/darwin.mk

Hi!

The links you've mentioned requires at a certain step to have a paid membership (around $119 usd valid for 1 year) at apple.com

Do you know any other way to get that correct version of MacSDK?

I've tried with MacOSX10.15.sdk and it still does fail, while the hosts file mention the max version is 10.15.6, then the 10.15 should work as well, for what i've thought so. 

Thanks!

**Comment by sipa** [comment]
You need an Apple ID, but not a paid membership.

**Comment by Original-Tasty** [comment]
> 
> 
> You need an Apple ID, but not a paid membership.

Hi

Maybe they've changed how it works. I've created that account 1 year ago, have the apple ID already. But it wont let me get to the link above if i dont pay for it :(

**Comment by Original-Tasty** [comment]
I've managed to get several  version of Mac SDKs here: https://github.com/phracker/MacOSX-SDKs

But what to type to start the compilation of the depends on linux cross compile:


`make HOST=x86_64-apple-darwin18` as suggested in the readme
or perhaps `make HOST=x86_64-apple-darwin20`?

what defines the number at the end of that text, when the version of the SDKs was 10.11, we had to type: 
`make HOST=x86_64-apple-darwin11`

But when the version of the SDKs is for example  11.3, then was would it be?

**Comment by fdoving** [comment]
It is explained here:
https://github.com/bitcoin/bitcoin/blob/master/depends/README.md
https://github.com/bitcoin/bitcoin/blob/0.21/contrib/macdeploy/README.md
And
https://github.com/bitcoin/bitcoin/blob/0.21/depends/hosts/darwin.mk


You need to put the SDK in `depends/SDK/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers`
`depends/SDK/MacOSX11.3.sdk` or similar, does not work anymore. 
Paths relative to bitcoin root-directory.


Try `HOST=x86_64-apple-darwin14 `

To get the SDK legally from Apple, you need to register and agree to their terms, but you do not have to pay anything.

**Comment by Original-Tasty** [comment]
i've managed to make it work the other day

The problems remained on the .xip file which couldnt be available from apple. 
i kept trying but it was still telling me i had to pay for it.

Then i dont know why it suddendly stopped and ive finally be able to download it. Had to refresh the page like a thousand times lol
I suppose apple had some weird bugs
