### ISSUE TITLE
wallet: add destination (output) and bump fee

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#22007]
This would allow ad hoc transaction batching. When a wallet transaction is unconfirmed, I'd like to be able to add an additional destination / output. [BIP 125](https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki) requires that such a transaction also increases the fee rate.

One approach would be to create a new wallet RPC `addoutput, which takes a transaction hash, address, amount and fee rate (difference).

A better approach imo would be to add a new argument `extra_outputs` to `bumpfee` (and `psbtbumpfee`).  This would have the same format as `outputs` in [send](https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/send/).

Two complications come to mind:
1. If the original transaction used `subtract_fee_from_outputs` we don't store that information (see also #11122), so either:
   a) the user has to provide that array again for us to subtract the additional fee correctly; or
   b) the extra fee is paid entirely from change
2. If the previous transaction confirms, rather than the new one, the user has to figure this out and manually craft a new transaction

**Comment by prayank23** [comment]
Concept ACK

> A better approach imo would be to add a new argument extra_outputs to bumpfee (and psbtbumpfee). This would have the same format as outputs in send.

Approach ACK

> b) the extra fee is paid entirely from change

LGTM

Apart from outputs, not sure if someone is already working to add inputs in replacement transaction, would be great if if we had coin control in RBF. 

Also bumpfee RPC should not broadcast transaction, as a user I always want to check transaction details before broadcasting (including inputs)

**Comment by Sjors** [comment]
@prayank23 those last two things are definitely out of scope. But they are useful. Can you make separate issues for them? (do a search on "rbf" and "bumpfee" first, but I don't recall these having their own issue yet)

**Comment by 1440000bytes** [comment]
@Sjors do you have any opinion on https://github.com/bitcoin/bitcoin/pull/25344 which fixes this issue?

**Comment by Sjors** [comment]
I'll take look!

**Comment by furszy** [comment]
This can be closed. https://github.com/bitcoin/bitcoin/pull/25344 implemented the changes.
