### ISSUE TITLE
RPC Error

### ISSUE THREAD

**Issue by Gui1105** [bitcoin/bitcoin#22000]
An error occurred when I used RPC to connect the node

RPC Method
```
gettransaction
```

RPC Response Error
```
No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)
```

**Comment by fanquake** [comment]
> No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)

If you are making a wallet related RPC call, you need to have a wallet loaded.

**Comment by tutwidi** [comment]
Tray Use this setup on bitcoin.conf
disablewallet=0

**Comment by Gui1105** [comment]
> > No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)
> 
> If you are making a wallet related RPC call, you need to have a wallet loaded.

Can you tell me more about it? Like how to do it

**Comment by Gui1105** [comment]
> > No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)
> 
> If you are making a wallet related RPC call, you need to have a wallet loaded.

I tried to use RPC to query transactions and send transactions.

**Comment by sipa** [comment]
This issue tracker isn't a support forum. Try looking for answers on https://bitcoin.stackexchange.com, and if you can't find what you're looking for, ask a question.

**Comment by Gui1105** [comment]
> This issue tracker isn't a support forum. Try looking for answers on https://bitcoin.stackexchange.com, and if you can't find what you're looking for, ask a question.

ok, thanks
