### ISSUE TITLE
Bitcoin-Qt: ask user to rebuild database in case of db corruption

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#2202]
As the current "restart with -reindex" is fine for bitcoind, but very confusing for GUI users.

**Comment by MarcoFalke** [comment]
You mean instead of crashing during validation, the gui will ask you to reindex instead of the "A fatal internal error occurred" message?

**Comment by promag** [comment]
Please assign this to me.

**Comment by hebasto** [comment]
What is the actual status of this issue?

**Comment by MarcoFalke** [comment]
Closing for now. I think a reindex might not be the best choice in case of corruption anyway. Better to buy stable high-end hardware.
