### ISSUE TITLE
wallet: Bitcoin Core v0.21.1 issue with incoming transaction

### ISSUE THREAD

**Issue by wasisdn** [bitcoin/bitcoin#22024]
copy my posts from Bitcointalk forum since January, hope this is ok...

First
-Issue started beginning this year with v0.21.0 when open Bitcoin Core, after receiving payment from nicehash.
Always while loading the same block, I think the one in which the Nicehash transfer is located, Bitcoin Core was closed without an error message. After trying several times to reinitialize, even from an older backup of my wallet.dat, 

-Try to import my wallet.dat after finished synching with a new wallet, but during inilizing my old wallet the same issue comes back, Bitcoin Core just shutdown without an error message and at same pos in debug.log

-Reinstalling v0.20.1 and the problem was resolved. 

-Reinstall 0.21.0 again, clean dbug.log and start with -reindex and -rescan.
After synching for a couple of hours Bitcon Core was shutdown.
Restart 2 times with same resault, the programm crashes without any error messege while synching the transaction from nicehash
This was few months ago, after that I returned to v 0.20.1 and it works like a charm without problems an weekly ingoing tx from nicehash.

Then
Still the same problem with version 0.21.1 whenever a new transaction comes in from Nicehash.
Could it be possible the latest BitcoinCore versions has a bug? Or someone might have the same problem or can tell what exactly is the difference from latest to previous versions so this problem could occur.
Can't imagine that it is due to my hardware or SW, since the problem is only with the incoming transactions from Nicehash and that only since Januar this year and since v0.21.0. This is for sure because if I re-syncronize the entire chain with latest BitcoinCore Version, it runs through all the years (many transaction over the past 4 years also incom from NH) until Januar 2021 without any problems and then always crashes on the same transaction from Nicehash dad0f505c7c9697e1b7b79ecc7133701fd0a4424993ec27770191bfb6a290763 (as in my first post). reverting to v0.20.1, sync this transaction (no problem), after that revert again to v0.21 and run until next tx from Nicehash with same problem..
Could it have to do with the size of transactions, because those from Nicehash are much larger than other, 7kb compared to usually a few hundred bytes.

Now
just to confirm after I ran BitcoinCore 0.21.1 without any problems for the entire last week until the next transaction from Nicehash arrived yesterday.
After the crash and several attempts with the same error at the same position (program closes when synchronizing the Nicehash transaction without a message) I pushed v0.20.1 into the program directory, started it and synchronized everything without problems.
Then switched back to the current v0.21.1 and its up and running again.

If you are interested, you can have a look at the last two days below debug log, don't think I need to comment

Tx from NH 2021-05-21 01:12
af4b27fd3e6917ddf39a16e159d2c20a4703ebaeffc554d3e29a780855a29525

Debug log with first attempt to load the NH tx
[debug.log](https://github.com/bitcoin/bitcoin/files/6527448/debug.log)
 2021-05-21T02:34:15Z

**Comment by MarcoFalke** [comment]
Does it crash or is this a clean shutdown. I couldn't find any indication for a crash in the debug log.

**Comment by wasisdn** [comment]
no crash just close down at same position during sync. after restart it will resync from last clean shutdown, as you can see in debug.log

**Comment by MarcoFalke** [comment]
Oh, actually it does look like a crash:

```
2021-05-21T02:38:23Z UpdateTip: new best=000000000000000000076abd974283d6f1ac6ee46e6275289b919a0b72578fb9 height=684340 version=0x3fffe004 log2_work=92.890824 tx=643673329 date='2021-05-20T18:13:01Z' progress=0.999835 cache=22.4MiB(168883txo)
(missing shut-down here)




2021-05-21T02:42:22Z Bitcoin Core version v0.20.1 (release build)
```

Does your Windows OS notify you of the crash?

**Comment by wasisdn** [comment]
no nothing

**Comment by tutwidi** [comment]
btc success update v21.1 with low fee transaction, greet job !

But how about The exchange's fee still take a high fee more Then bitcoin fee, how we validating that?

**Comment by wasisdn** [comment]
the latest version 22.0 has fixed the wallet problem, no more crashes on incoming transactions from anywhere.
Thanks to everyone!
