### ISSUE TITLE
Don't block me，I just want to join or study

### ISSUE THREAD

**Issue by XmanXme** [bitcoin/bitcoin#22040]
#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by fanquake** [comment]
Spamming this repository with issues is not the way to do that. Issues are meant to be opened when reporting issues with the Bitcoin Core software. Anyone is free to study or contribute to the code base. You do not need to ask permission. I'd suggest reading through some of our contributing guides: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md & https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
