### ISSUE TITLE
Nulldata treated as nonstandard

### ISSUE THREAD

**Issue by tieugene** [bitcoin/bitcoin#22045]
bitcoind returns 'nonstandard' addresses from scripts started from OP_RETURN.
E.g. in first 300 kiloblocks (bk.tx.vout):

- 229712.129.1
- 257727.91.1
- 257727.93.1
- 283396.596.1
- 296195.12.0
- 299571.10.2

As an example - vout 229712.129.1 (block height 229712, tx 129, vout 1):

```json
{
  "value": 0.00000000,
  "n": 1,
  "scriptPubKey": {
    "asm": "OP_RETURN OP_DUP OP_HASH160 cd2b3298b7f455f39805377e5f213093df3cc09a OP_EQUALVERIFY OP_CHECKSIG",
    "hex": "6a76a914cd2b3298b7f455f39805377e5f213093df3cc09a88ac",
    "type": "nonstandard"
  }
}
```

**Comment by theStack** [comment]
Hi tieugene,

note that an output script has to satisfy two conditions to be classified as Nulldata:
* starts with OP_RETURN
* the remaining part *only* consists of push-operations (the corresponding checking method in the code is named `IsPushOnly`)

The seconds condition is not fulfilled in your given example, hence the scriptPubKey is "nonstandard".

(I didn't look at the other instances you listed though)

**Comment by tieugene** [comment]
> * starts with OP_RETURN
> * the remaining part _only_ consists of push-operations (the corresponding checking method in the code is named `IsPushOnly`)

But this means that '[OP_RETURN hello world](https://learnmeabitcoin.com/technical/nulldata)' is not proper nulldata?
Where I can find BIP or other RTFM that describes valid nulldata payload?
