### ISSUE TITLE
Blockchain squash

### ISSUE THREAD

**Issue by freehuntx** [bitcoin/bitcoin#22055]
**Is your feature request related to a problem? Please describe.**
Its not related to a open issue. But a growing blockchain with "useless informations" could be seen as a "problem".

**Describe the solution you'd like**
Since every transaction is transparent it would be possible to squash the blockchain regularly.  
By this i mean merging all transactions in the past to a new initial transaction. Something like a new Genesis block.  
In this block just wallets with a positive balance would be taken.  
This way the blockchain would shrink significantly. I could imagine a process similar to the halvening.  
For example on a monthly/yearly basis.

**Describe alternatives you've considered**
There are no alternatives i know of.

**Additional context**
Doing this the first time would take huge amount of time. Usually such a change would be done in a new fork or a new coin.  
I think it would be a huge change and i understand if this is not wanted.  
But this type of change would be no breaking change (i guess) since the blockchain would still have the same format and everything else works the same.  
  
PS: This is just a idea i had. I never worked on Bitcoin so dont be too mean if u dislike this idea :)

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.

**Comment by MarcoFalke** [comment]
Also, there is `-prune`.

**Comment by freehuntx** [comment]
Okay thanks.  
I know about prune but that is breaking network integration and you still have to download the entire chain first.
Also it breaks wallets that are old.
Thanks for the contact informations!
