### ISSUE TITLE
ci: wasted time in brew_install stage of macOS native build

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#22068]
Ever since #21663, which added a `brew update` command, >10% of the runtime of the macOS native CI is spent repetitively doing this update. For example, in this recent build, https://cirrus-ci.com/task/4631533593034752, the `brew_install` stage takes 8m26s to complete.. 

This seems like something we should be able to avoid. @fkorotkov is it possible for the CI images to be updated to contain a more up to date version of `brew` or similar?

**Comment by fkorotkov** [comment]
The images are immutable by it's nature and we don't usually update things for `xcode` versions of the images. We do update the `base` versions periodically. Is it ok to build with Xcode 12.5? `big-sur-xcode-12.5` was built on April 29th and should have brew formulas not pointing to bintray.
