### ISSUE TITLE
Error on "make deploy" on Linux for Windows wallets x64

### ISSUE THREAD

**Issue by Original-Tasty** [bitcoin/bitcoin#22066]
Hi, i got the following error:

```
Invalid command: Unicode
Error in script "stdin" on line 6 -- aborting creation process
```

After 'make deploy' on a linux system, after compiled Windows wallets.

It's suppose to create the .exe, but got that error which is stopping the process.

I've tried on linux 18.04 and 21.04

From google, people says that error is du to Chinese characters where they shouldn't be.

Not sure how to solve this, anyone know how? 

Thanks!

**Comment by fanquake** [comment]
> Invalid command: Unicode

You need to use NSIS 3.0 or later, as that was the first version to properly support unicode, [which we now use](https://github.com/bitcoin/bitcoin/blob/master/share/setup.nsi.in#L6).

**Comment by Original-Tasty** [comment]
> 
> 
> > Invalid command: Unicode
> 
> You need to use NSIS 3.0 or later, as that was the first version to properly support unicode, [which we now use](https://github.com/bitcoin/bitcoin/blob/master/share/setup.nsi.in#L6).

It worked like a charm thank you!
