### ISSUE TITLE
depends: qt build for HOST=aarch64-linux-android is broken for NDK 22+

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#22074]
On master (456c8d6cd80fc3461957a3553a0483756396b988):
```
$ echo $ANDROID_SDK 
/home/hebasto/Android/Sdk
$ make -C depends qt_configured HOST=aarch64-linux-android ANDROID_API_LEVEL=28 ANDROID_NDK=$ANDROID_SDK/ndk/22.0.7026061 ANDROID_TOOLCHAIN_BIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin
...
> clang++: error: no such file or directory: '/home/hebasto/Android/Sdk/ndk/22.0.7026061/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.so.28'
...
```
I seems related to this [change](https://github.com/android/ndk/wiki/Changelog-r22):
> The legacy libc++ linker scripts in `<NDK>/sources/cxx-stl/llvm-libc++` have been removed. The linkers scripts in the toolchain should be used instead as described by the Build System Maintainers Guide.

**Comment by hebasto** [comment]
cc @icota

**Comment by icota** [comment]
I think we should wait until r23 is released before taking any action. r21 is an LTS release and r22 is not

**Comment by hebasto** [comment]
> I think we should wait until r23 is released before taking any action. r21 is an LTS release and r22 is not

Fair enough.

Closing for now.

**Comment by hebasto** [comment]
From https://doc.qt.io/qt-5/android-getting-started.html#installing-the-prerequisites:
> NDK r20b or r21

**Comment by fanquake** [comment]
> I think we should wait until r23 is released before taking any action. r21 is an LTS release and r22 is not

I think if we'd like to keep supporting Android builds for 23.0, someone should look into making Qt and the Android build work with r22. I can't imagine we are going to block migrating to `std::filesystem` based on our Qt version being too old, to support building against a new enough version of the Android NDK to `support std::filesystem`. I'd rather just drop the Android build until we've moved on to a newer version of Qt.

I'd also assume that any of the Qt patching and build system changes that are going to be required will be very similar for r22 and r23 in any case (r23 support just being additional changes on top of r22 if any).

**Comment by icota** [comment]
Makes sense. @hebasto reopen?
