### ISSUE TITLE
TCP listern 127.0.0.1:8332

### ISSUE THREAD

**Issue by arulananth** [bitcoin/bitcoin#22104]
I want listern 111.90.159.92:8332

My bitcoin.conf

rpcuser=bitmarket
rpcpassword=Four6124
daemon=1
server=1
rpcbind=111.90.159.92
externalip=111.90.159.92
rpcallowip=111.90.159.92

**Comment by arulananth** [comment]
@fanquake can  you share example conf file

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
