### ISSUE TITLE
I can't access the bitcoin JSON PRC with IP address.

### ISSUE THREAD

**Issue by arulananth** [bitcoin/bitcoin#22114]
Here is my conf file

rpcuser=bitmarket1
rpcpassword=Four16124
server=1
rpcallowip=111.90.159.92
rpcconnect=111.90.159.92
allowreceivebyip=1

wget 111.90.159.92:8332 faliure
wget 127.0.0.1:8332  success

Any one help me to access bitcoin JSON RPC 111.90.159.92:8332 ???

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
