### ISSUE TITLE
EXCEPTION: N5boost10filesystem16filesystem_errorE

### ISSUE THREAD

**Issue by la841** [bitcoin/bitcoin#22148]
I got this message when I run bitcoind

EXCEPTION: N5boost10filesystem16filesystem_errorE
boost:: filesytem:: create_directory: File exists: "home/sats/.bitcoin"
bitcoind: chainparambase.cpp:36: const CBaseChainParams& Base Params() Assertion GlobalChainBaseParams failed
Aborted (core dumped)

Any ideas whats happening?

**Comment by MarcoFalke** [comment]
>  boost:: filesytem:: create_directory: File exists: "home/sats/.bitcoin"

What does `stat home/sats/.bitcoin` or `stat /home/sats/.bitcoin` print?

**Comment by MarcoFalke** [comment]
Which version of Bitcoin Core are you using, how do you start it?

**Comment by la841** [comment]
> > boost:: filesytem:: create_directory: File exists: "home/sats/.bitcoin"
> 
> What does `stat home/sats/.bitcoin` or `stat /home/sats/.bitcoin` print?

File: /home/sats/.bitcoin -> /mnt/blockchain/blockchain-fullnode
  Size: 35        	Blocks: 0          IO Block: 4096   symbolic link
Device: b302h/45826d	Inode: 388713      Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/    sats)   Gid: ( 1000/    sats)
Access: 2021-06-03 17:27:41.048495967 +0200
Modify: 2021-03-22 15:33:23.177814094 +0100
Change: 2021-05-26 13:50:05.686734097 +0200
 Birth: 2021-03-22 15:33:23.177814094 +0100

Bitcoin Core RPC client version v0.21.0

**Comment by MarcoFalke** [comment]
I am not sure if symbolic links for the datadir root are supported.

You may be able to work around by setting the datadir directly to `/mnt/blockchain/blockchain-fullnode`

**Comment by la841** [comment]
> Which version of Bitcoin Core are you using, how do you start it?

I have started with bitcoind command. Everthing works ok but I get the error message if I try to run it with micro SD from coldcard to open my wallet.

**Comment by la841** [comment]
> I am not sure if symbolic links for the datadir root are supported.
> 
> You may be able to work around by setting the datadir directly to `/mnt/blockchain/blockchain-fullnode`

I have been using it as it is, until now

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
