### ISSUE TITLE
Add Qt options for new switches

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#2214]
There are several new command-line switches which have no corresponding options in Qt:
 * -dbcache
 * -checkpoints
 * -par

These older switches can probably also use a config panel equivalent:
 * -checklevel / -checkblocks
 * -maxreceivebuffer / -maxsendbuffer
 * -maxsigcachesize
 * -timeout

**Comment by jonasschnelli** [comment]
`-Listen` and `-dbcache` are now changeable through the UI.
I would say `-par`, `checkpoints`, `-checklevel`, `-checkblocks`, `-maxreceivebuffer`, `-maxsigcachesize` belongs to a text-config-file (or cmd args) only.

**Comment by laanwj** [comment]
`-par` is also settable in the GUI

**Comment by laanwj** [comment]
`-par` is also settable in the GUI

**Comment by jonasschnelli** [comment]
@laanwj right. I oversaw that.
The question is if we should agree for adding UI settings for `checkpoints`, `checklevel`, `checkblocks`, `maxreceivebuffer`, `maxsigcachesize` or close this issue.

**Comment by laanwj** [comment]
I agree and see no value in that. So let's close this issue.
