### ISSUE TITLE
i need to get all addresses that has any transaction any time from start of bitcoin

### ISSUE THREAD

**Issue by mohammadAsadolahi** [bitcoin/bitcoin#22152]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

i need to get all addresses that has any transaction any time from start of bitcoin
for example i need to get any address on blockchain like "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa" and put them into a file
every address in one line and i need all empty addresses too any address in block chain

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
