### ISSUE TITLE
QT-related error in building dependencies for 0.21.1 release on Apple M1 architecture

### ISSUE THREAD

**Issue by ipa-tys** [bitcoin/bitcoin#22160]
Trying to compile 0.21.1 on Apple M1 architecture (Mac Mini M1 2020, Big Sur 11.3.1), I get the following error when running `make` in the `depends` directory:

```ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.```

The error also happens when I check out the head of `master`, instead of the `v0.21.1` tag.
It seems QT-related, since running `make NO_QT=1` in the `depends` succeeds.

Any advice?

**Comment by hebasto** [comment]
There were some changes wrt compiling on Apple M1 recently on the master branch.
So, you could try it.

**Comment by ipa-tys** [comment]
Thanks! I noticed that I had not run `git pull` for almost 3 weeks. This made the difference. On the current head  ( 8f5c9a7fd41d3ed56798a1c7c142db8d530ab1e2 ), I can now run `make` in the `depends` directory without any issues.
