### ISSUE TITLE
Boost::ASIO  (used by Boost::Process) uses (falsely?) deprecated std::allocator

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#22254]
Observed by @fanquake in https://github.com/bitcoin/bitcoin/pull/21935#pullrequestreview-683513857

> (depends build) Boost Process seems to use Boost ASIO, which uses `std::allocator<void>`, which was deprecated in C++17. This leads to a nice stack of warnings, at least on macOS:
> 
> ```shell
> bitcoin/depends/x86_64-apple-darwin20.5.0/include/boost/asio/associated_allocator.hpp:78:49: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
> template <typename T, typename Allocator = std::allocator<void> >
>                                                 ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:730:28: note: 'allocator<void>' has been explicitly marked deprecated here
> class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 allocator<void>
>                            ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1058:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
> #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
>                                       ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1035:48: note: expanded from macro '_LIBCPP_DEPRECATED'
> #    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
> ```
> 
> I'm also seeing unused-result warnings (from Boost) when building on my Ubuntu machine:
> 
> ```shell
> In file included from /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/detail/execute_impl.hpp:24,
>                  from /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/child.hpp:22,
>                  from /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/async_system.hpp:22,
>                  from /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process.hpp:24,
>                  from util/system.cpp:9:
> /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/detail/posix/executor.hpp: In member function ‘void boost::process::detail::posix::executor<Sequence>::write_error(const std::error_code&, const char*) [with Sequence = boost::fusion::joint_view<boost::fusion::tuple<boost::process::detail::posix::exe_cmd_init<char> >, boost::fusion::filter_view<const boost::fusion::tuple<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, boost::process::detail::posix::pipe_out<1, -1>&, boost::process::detail::posix::pipe_out<2, -1>&, boost::process::detail::posix::pipe_in&>, boost::process::detail::is_initializer<mpl_::arg<-1> > > >]’:
> /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/detail/posix/executor.hpp:156:16: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
>   156 |         ::write(_pipe_sink, &len, sizeof(int));
>       |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/detail/posix/executor.hpp:159:16: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
>   159 |         ::write(_pipe_sink, &len, sizeof(int));
>       |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/ubuntu/bitcoin/depends/x86_64-pc-linux-gnu/include/boost/process/detail/posix/executor.hpp:160:16: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
>   160 |         ::write(_pipe_sink, msg, len);
>       |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
>   AR       libbitcoin_util.a
> ```
> 

I tried with Boost 1.72 - 1.76 (most recent version on 2021-06-15) but to no avail.

Possible solutions:
* fix it upstream (using a patch in the mean time):
  * by fixing ASIO, but this has been tried since 2018: https://github.com/boostorg/asio/pull/76
  * by fixing Process to not use Asio perhaps
* refactoring `RunCommandParseJSON` to work without Boost::Process (sadly non trivial, see #15382)
* make llvm not complain: https://bugs.llvm.org/show_bug.cgi?id=50299

In addition to annoying warnings, this would require someone with a c++20 compiler to use `--disable-external-signer`.

**Comment by akhil14shukla** [comment]
I checked the repo for boost/asio dependency, and I didn't find any trace of it in the search results. It seems that while building we check the BOOST library thus also checking the boost/asio and leading to warnings. 
Adding a condition to skip this boost/asio should suppress the warnings.

**Comment by Sjors** [comment]
I tried removed boost/asio from depends with a [patch](https://github.com/Sjors/bitcoin/commit/b92f35780837b547533064c4e4cfd06d04aa19eb), but we do seem to need it:

```
In file included from util/system.cpp:14:
In file included from /Users/sjors/dev/bitcoin/depends/x86_64-apple-darwin20.5.0/include/boost/process.hpp:23:
/Users/sjors/dev/bitcoin/depends/x86_64-apple-darwin20.5.0/include/boost/process/async.hpp:35:10: fatal error: 'boost/asio/io_context.hpp' file not found
#include <boost/asio/io_context.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [util/libbitcoin_util_a-system.o] Error 1
```

**Comment by Sjors** [comment]
Hopefully we can replace Boost::Process altogether, see #24907

**Comment by fanquake** [comment]
`std::allocator<void>` was undeprecated in LLVM: https://github.com/llvm/llvm-project/commit/87784cc6fb3453a17e0e7826b943a1d93cbfeccf. There's no need for us to keep an issue open for this for now.
