### ISSUE TITLE
how to support Native SegWit (Bech32) address 

### ISSUE THREAD

**Issue by coininn-exchange** [bitcoin/bitcoin#22259]
I run the bitcoin node version is 0.17.1, and now we want to support the Native SegWit (Bech32) format, how do I need to upgrade the node or redeploy a new node, or what method can I use to convert the Nested SegWit (P2SH) format to Bech32 address

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.

Nonetheless some notes:

* The Bitcoin Core major version 0.17.x is officially no longer supported. See https://bitcoincore.org/en/lifecycle/#schedule . It is recommended to read the release notes of newer versions, test them in a test deployment and then move production to supported versions.
* "Converting" nested addresses to native ones is not supported either. It is recommended to ask the wallet to generate native addresses for you. I don't know how you produce addresses, but if you use `getnewaddress`, then https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/getnewaddress/ is the documentation.

**Comment by coininn-exchange** [comment]
> Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
> 
> Nonetheless some notes:
> 
> * The Bitcoin Core major version 0.17.x is officially no longer supported. See https://bitcoincore.org/en/lifecycle/#schedule . It is recommended to read the release notes of newer versions, test them in a test deployment and then move production to supported versions.
> * "Converting" nested addresses to native ones is not supported either. It is recommended to ask the wallet to generate native addresses for you. I don't know how you produce addresses, but if you use `getnewaddress`, then https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/getnewaddress/ is the documentation.

 ** I want to know how to create  Native SegWit (Bech32) address **

**Comment by MarcoFalke** [comment]
> I want to know how to create Native SegWit (Bech32) address

If you read my reply, you would have realized that I told you that getnewaddress can do that. https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/getnewaddress/
