### ISSUE TITLE
Access to private keys

### ISSUE THREAD

**Issue by Avanakitavra** [bitcoin/bitcoin#22264]
why is no one confused by the fact that no exchange in the world will provide you with a private key to your BTC address ?absolutely all exchanges, without exception, have access to all users ' private keys ,has anyone thought about it?if you ask technical support to provide you with your private key, you will be refused with 100% probability ,and if they do, then know that your private key is known by the exchange
What kind of security can we talk about then ?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
