### ISSUE TITLE
Empty blocks validated in Blockchain

### ISSUE THREAD

**Issue by mrctorres** [bitcoin/bitcoin#22262]
Sorry if this is not the correct channel to report this, but if there is another one please would like to know what it is.

What happens is that I've seen lately blocks being validated without containing transactions, just the reward of the miner for mining an empty block.

Wouldn't that be a bug?

The blocks are attached.

![Block 687842](https://user-images.githubusercontent.com/86022979/122286137-ecb38800-cec5-11eb-8c61-cedac3d6f2a9.jpg)
![Block 687712](https://user-images.githubusercontent.com/86022979/122286144-ede4b500-cec5-11eb-8f58-6e3a1a0bd40c.jpg)

**Comment by prayank23** [comment]
https://braiins.com/blog/why-pools-mine-empty-blocks-and-how-stratum-v2-fixes-this

https://bitcoinmagazine.com/business/decline-empty-blocks-has-increased-bitcoins-transaction-capacity

https://bitcoin.stackexchange.com/questions/46604/creating-empty-blocks-vs-creating-full-blocks

https://bitcoin.stackexchange.com/questions/99852/what-are-the-benefit-of-mining-an-empty-block

**Comment by ccdle12** [comment]
Mining empty blocks can happen, although the occurence of it seems to be dropping. If I'm not mistaken it usually occurs when mining pools begin preemptively mining the next block if they think they already late on the current one.

I think if the devs don't find the time between the blocks too alarming then Bitcoin Stack Exchange is a good place to discuss this: https://bitcoin.stackexchange.com/
