### ISSUE TITLE
Using Visual Studio 2019 complie bitcoin solution failed(many compile errors).

### ISSUE THREAD

**Issue by baimafeitu** [bitcoin/bitcoin#22293]
1. OS: Win10 home edition;
2. Build tool: VS2019 community;
3. solution location: bitcoin\build_msvc\bitcoin.sln;
4. Active solution config: Debug；
5. Active solution platform: x64；

When I use VS2019 to build bitcoin solution, there are many compiling errors:
![Errors](https://user-images.githubusercontent.com/85609765/122700837-9d32da80-d27e-11eb-8ff8-f06963eb4c34.jpg)

Thank you very much.

**Comment by baimafeitu** [comment]
Anyone can help me？ I'm stucked in here. Thanks very much.

**Comment by hebasto** [comment]
@baimafeitu 

The building process is described in [Building Bitcoin Core with Visual Studio](https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md).

In particular:
```
cd build_msvc
py -3 msvc-autogen.py
msbuild /m bitcoin.sln /p:Platform=x64 /p:Configuration=Release /t:build
```

Was `py -3 msvc-autogen.py` command successful for you?

**Comment by baimafeitu** [comment]
@hebasto

**Comment by baimafeitu** [comment]
@hebasto 
Yes! When I execute this command, compile sucessfully! Thank you very much.
Also thank you, @fanquake.
