### ISSUE TITLE
build: configure error related to boost:process when cross-compiling to windows

### ISSUE THREAD

**Issue by jarolrod** [bitcoin/bitcoin#22319]
When trying to cross-compile for Windows on Ubuntu 20.04.2 LTS I ran into the following configuration error:

```
checking for Boost Process... configure: error: Boost::Process is required for external signer support, but not available!
```

**Steps to reproduce:**
1.  depends build for windows 
    ```
     cd depends && make -jN HOST=x86_64-w64-mingw32
    ```
2. After work is built, try to configure:
   ```
     cd .. && ./autogen.sh && CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure
     ```
3. Run into configuration error

**System:**
- reproduced on VM with Ubuntu 20.04.2 LTS and desktop with Arch Linux

**Comment by jarolrod** [comment]
FWIW #22269 does not help

**Comment by hebasto** [comment]
Also gitian and guix builds for Windows are broken.
