### ISSUE TITLE
Help with debugging OSS-Fuzz issues

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#22315]
There are some outstanding OSS-Fuzz issues which I am unable to debug: "New" ones in https://bugs.chromium.org/p/oss-fuzz/issues/list?q=bitcoin-core

#### Useful skills:

* Background in OSS-Fuzz infra (https://google.github.io/oss-fuzz/advanced-topics/reproducing/)
* Background in Fuzzing (https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md)
* Strong debugging skills

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by bliotti** [comment]
I'll take this one for now.

**Comment by MarcoFalke** [comment]
Just noting, there are currently 4 open issues, so this should be enough for several people to work on it. You can just leave a comment in the respective issue or here if you found something useful to debug them.

**Comment by achirawi** [comment]
> There are some outstanding OSS-Fuzz issues which I am unable to debug: "New" ones in https://bugs.chromium.org/p/oss-fuzz/issues/list?q=bitcoin-core
> 
> #### Useful skills:
> * Background in OSS-Fuzz infra (https://google.github.io/oss-fuzz/advanced-topics/reproducing/)
> * Background in Fuzzing (https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md)
> * Strong debugging skills
> 
> #### Want to work on this issue?
> For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.
