### ISSUE TITLE
Peer table (node window) does not remain sorted on update

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#22328]
![image](https://user-images.githubusercontent.com/1530283/123112095-5c30f680-d435-11eb-9962-45eaa554ce3a.png)

This issue was introduced somewhere between 672870ab7ba51b1fc40f263a1c71ebcf165b1229 and c8571486364d6e9ca8c86bd1c81e230ca64f8904

**Comment by rebroad** [comment]
Currently bisecting this to identify where

**Comment by rebroad** [comment]
c8571486364d6e9ca8c86bd1c81e230ca64f8904 is also good

**Comment by hebasto** [comment]
@rebroad Could you move this issue into https://github.com/bitcoin-core/gui/issues?

**Comment by rebroad** [comment]
> @rebroad Could you move this issue into https://github.com/bitcoin-core/gui/issues?

I would if I knew how to... how does one move an issue please?

**Comment by rebroad** [comment]
Replaced with https://github.com/bitcoin-core/gui/issues/367
