### ISSUE TITLE
Add examples in tor.md

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#22356]
_What?_

[doc/tor.md](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md) : Add examples of using Bitcoin Core onion service in Linux(Ubuntu), Mac, Windows and Android 

_Why?_

1. **Make it easier** for newbies and power users to try Bitcoin Core onion service
2. Users should not search for proper documentation in different websites, forums, blogs etc. and everyone should be able to follow the things easily using **doc in this repository**. **Privacy** should not be hard to achieve or at least the first steps should be easy and encouraging enough to motivate the user in learning more later.
3. The examples will help in **skipping all the things** mentioned in doc. Run the commands and setup Bitcoin Core Onion Service in **few minutes**. Once the user can see that onion address and things working it will motivate him to read all the things mentioned in doc if interested to research more.
4. [Tor usage in Bitcoin Core](https://bitnodes.io/dashboard/?days=730) is 20-30%, I am sure everyone contributing in this repository wants to see this **number go up**. I personally want this to be above 50%. Using Bitcoin Core with Tor should be the default.

_How?_

1. I tried [adding 1 example for Ubuntu](https://github.com/bitcoin/bitcoin/pull/21157) to start with, however it looked like duplication of few things that were already mentioned in doc. So had to give up and look for other ways to add examples. ❌
2. I would prefer adding screenshots with the basic steps. I don't think people will agree to add screenshots in [doc/tor.md](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md) so the options are:

   2.1 Create a separate file for examples
   2.2 Enable wikis for the repository and create a page
   2.3 <mark>Add all examples in one Q&A on Bitcoin Stackexchange and use its link 🤔
   2.4 None of the above
3. How would the examples look like? [Basic steps](https://twitter.com/prayankgahlot/status/1407349275940605952) for [Operating Systems](https://gs.statcounter.com/os-market-share/desktop/worldwide) that are used more for desktop and mobile(Android).

Cc: @Rspigler

**Comment by jonatack** [comment]
Not sure about screenshots because they are more difficult to update as needed and are either dark or light mode, e.g. don't adapt to user settings.

It's possible that the longer `doc/tor.md` is to read, the more it may discourage new users.

(I'm not sure newbies often begin by reading `doc/tor.md` or other docs in the repo. They may be more likely to use a search engine to look for a blog post or article, and writing/hosting a good article seems like a good contribution. Of course, that is only speculation on my part.)

**Comment by Rspigler** [comment]
Thoughts:

I agree with the motivation behind this issue.  (Definitely 1,2, and 4 under `Why`, maybe not 3).

Re: `How` - I think this will be hard to process without seeing all 3 OS examples at one time, as seeing just the linux example looked like duplication.  Even with all 3, maybe we will want to remove the general installation instruction as we are adding specific instructions later in the document (or will the installation instructions come first? - See point 3 under `Why`)

I agree with @jonatack That screenshots shouldn't be used - they don't work perfectly for each user, and they make the document too long IMO.  As for his second point, hopefully tutorials start to point official docs.

**Comment by RandyMcMillan** [comment]
agree - bloating the repo with screenshots should be avoided - generally speaking...

**Comment by jonatack** [comment]
To give an example, I wrote an article to help new people build bitcoin core from source: 

https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests

I think it serves its purpose better where it is, outside of the repository.  Search engine results for it are (probably) better than for the build docs here in /doc and I think it serves its purpose better where it is outside of the repository. Maybe the same would be true for Tor. Also, examples may require continued updates and maintainance. This may be better done by an individual on their blog or website.

**Comment by Rspigler** [comment]
I've used that article many times :)

**Comment by prayank23** [comment]
> To give an example, I wrote an article to help new people build bitcoin core from source:
https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests

@jonatack I use this often and it's helpful. So do you think option 2.3 above makes sense?

Instead of blog post, we write a Q&A on Stackexchange and use it's link in `tor.md`:

```md
## Examples

https://bitcoin.stackexchange.com/community-wiki-tor

```

**Comment by Rspigler** [comment]
I don't think we should have official docs pointing to external websites either.

IMO, right now we have great linux instructions. I think it could be a good idea to add windows and mac instructions to the docs for those sections of our user base.

**Comment by Saviour1001** [comment]
@prayank23 I tried making the one stop article for setting up the Bitcoin Core Onion Service. I wrote in similar fashion as of @jonatack 's article. Check it out [here](https://github.com/Saviour1001/docs/blob/main/Articles/how_to_use_bitcoin_core_onion_service.md) and review.

**Comment by fanquake** [comment]
Going to close this for now. Anyone is welcome to expand documentation, but I don't think we need a generic "add more examples to x doc" type issues open.
