### ISSUE TITLE
conflicting documentation

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#22367]
productivity.md refers to git range-diff requiring a git version which is not available in Ubuntu 18.04 which is recommended by build-windows.md

Does productivity.md need to be updated to mention that this will be unavailable when developing for windows?

**Comment by MarcoFalke** [comment]
You can also use guix for cross compiling and 20.04 Ubuntu should work, too

**Comment by fanquake** [comment]
> Does productivity.md need to be updated to mention that this will be unavailable when developing for windows?

No. Windows development happens in environments other than Ubuntu 18.04. There's also the possibility of for you to install a newer version of git to use, using a number of different methods.

In any case, the sentence in the docs is `git range-diff (Git >= 2.19) can help solve this problem by diffing the diffs.` If you don't have git >= 2.19, then you just can't use the tool. It's not a hard requirement, and there's no reason for us to start mentioning where you might not be able to to use it.

**Comment by sipa** [comment]
FWIW, I'm pretty sure I've never once used `git range-diff`.

**Comment by MarcoFalke** [comment]
Once you find how useful it is you'll use it daily ;)
