### ISSUE TITLE
RPC usage for "logging" unclear

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#22377]
It's not clear how to enable/include or disable/exclude debug settings from within the console. The usage is not clear.

For example, I have tried

logging exclude mempool
logging exclude [ mempool ]
logging exclude [ "mempool" ]
logging exclude [\"mempool\"]
logging exclude "[\\"mempool\\"]"

none of them work!

**Comment by fanquake** [comment]
Try `help logging` and look at the example. 
If you want to turn mempool logging on do `logging "[\"mempool\"]"`. 
If you want to turn if off do `logging [] "[\"mempool\"]"`

**Comment by MarcoFalke** [comment]
In the gui: `logging '[]' '["mempool"]'`. In the future please include steps to reproduce (with the error message you are getting)

**Comment by rebroad** [comment]
@fanquake why did you close the issue? it's still an issue as of the latest master.

**Comment by MarcoFalke** [comment]
What is the issue then? With steps to reproduce, etc ...

**Comment by rebroad** [comment]
@MarcoFalke the issue is that the instructions for users are not clear - obviously I cannot "reproduce" the issue now that the correct syntax has been explained to me.

**Comment by sipa** [comment]
Read the documentation. It even has usage examples.
