### ISSUE TITLE
`onlynet=onion` for pruned node results in no peers

### ISSUE THREAD

**Issue by prayank23** [bitcoin/bitcoin#22384]
`onlynet=onion` doesn't work for pruned node. Even after waiting for few minutes couldn't see any peers. Initially I thought it must be an issue because less onion nodes on testnet but it works fine for non-pruned node.

**Expected behavior**

Onion peers

**Actual behavior**

No peers

**To reproduce**

Node A (pruned) with bitcoin.conf:

```
testnet=1
prune=1024

onlynet=onion
```

Node B (non-pruned) with bitcoin.conf:

```
testnet=1
txindex=1

onlynet=onion
```

**System information**

- Master Branch

- Pop!_OS

Peers for Node B:

![image](https://user-images.githubusercontent.com/13405205/124152685-5ed4c100-dab1-11eb-97f9-53065e2f6fc1.png)

Peers for Node A:

```
$ bitcoin-cli getpeerinfo

[
]
```

Is this a bug or expected behavior and I am missing something?

**Comment by MarcoFalke** [comment]
Please provide the relevant excerpts from the debug log with the appropriate logging enabled.

**Comment by prayank23** [comment]
I could finally see some peers in pruned node but it took some time. 

![image](https://user-images.githubusercontent.com/13405205/124160235-ae1eef80-dab9-11eb-9212-772a983f93cd.png)


Maybe they got connected after DNS seed query which waits for 300 seconds. So the issue is resolved I guess but still things work differently in pruned node for some reason:

`debug.log` for Node A(non-pruned): https://pastebin.com/1VrkvB52

`debug.log` for Node B(pruned): https://pastebin.com/W577CZXZ

**Comment by MarcoFalke** [comment]
bootstrapping is non-deterministic, so a small delay is expected when the randomly picked bootstrap peers are currently unreachable.
