### ISSUE TITLE
Installation via Bitcoin-Core.dmg is broken on macOS (Apple Silicon)

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#22403]
System: macOS Big Sur 11.4 (20F71), chip Apple M1.

On master (c609e10545492aba480ff17aff7eefc13a0b5cd8), after succesfull `make deploy` (without depends), the app installed from `Bitcoin-Core.dmg` fails to run.

`src/qt/bitcoin-qt` works flawlessly.

**Comment by jarolrod** [comment]
will test but I believe this was supposed to fix it? https://github.com/bitcoin/bitcoin/pull/21658

**Comment by hebasto** [comment]
> will test but I believe this was supposed to fix it? #21658

I've update the OP to mentioned the issue happens on master (c609e10545492aba480ff17aff7eefc13a0b5cd8).

**Comment by hebasto** [comment]
@jarolrod 

Building with depends, `make deploy`, and the following installation from `*.dmg` works fine.

**Comment by jarolrod** [comment]
ah right, that's the difference. Noted

**Comment by prusnak** [comment]
> Building with depends, `make deploy`, and the following installation from `*.dmg` works fine.

Shouldn't `make deploy` depend on depends then?

**Comment by ccr781** [comment]
***@***.***

ไชยวัฒน์ แก้วมณี

ในวันที่ อ. 6 ก.ค. 2021 17:18 Pavol Rusnak ***@***.***>
เขียนว่า:

**Comment by fanquake** [comment]
> the app installed from Bitcoin-Core.dmg fails to run.

Hard to debug anything here with such little information. For what it's worth, I've installed from the `.dmg` after a non depends builds, and from what I can see, the issue is related to us running `strip` & `install_name_tool` on libs while building the `.dmg`. This breaks some Apple code-signing requirement, and prevents the app from launching.

Looks like some other projects have run into a similar issue when doing the same thing. i.e: https://gitlab.kitware.com/cmake/cmake/-/issues/21854.

**Comment by hebasto** [comment]
According to https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes it looks like the binaries must be signed (at least with ad-hoc signatures):
```
codesign --sign - --deep --force dist/Bitcoin-Qt.app
```

**Comment by achow101** [comment]
signapple should already be able to make signatures for universal binaries, so we should be good for releases.

**Comment by hebasto** [comment]
> According to https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes it looks like the binaries must be signed (at least with ad-hoc signatures):
> 
> ```
> codesign --sign - --deep --force dist/Bitcoin-Qt.app
> ```

Done in #22546.
