### ISSUE TITLE
Increase trust through Wallet Aliases and Transfer Confirmations

### ISSUE THREAD

**Issue by erikblues** [bitcoin/bitcoin#22422]
**Is your feature request related to a problem? Please describe.**

Users still fear doing bitcoin transactions, scared that something might go wrong. This fear is based on 2 closely-related issues:
- First: "Is the account I am transferring to the correct one? Maybe I didn't copy it correctly, maybe I still have a previous address in my clipboard?
- Second: Users only know 100% that they transferred correctly AFTER the transaction has gone through.

**Describe the solution you'd like**
I think this could be greatly improved by implementing 2 solutions:

- Help users know where they are transferring to: Allow users to give their wallet's an Alias. Something like [ MyAmazingAlias ]. Then, when someone is preparing a transactions, after he fills out the wallet address, it could display:
`"transferring to id: [xxxxxxx] label: [ MyAmazingAlias ], confirm?`

- Allow the receiver to confirm his wallet BEFORE the transfer-confirmation: When the destination address and ammount are already filled out, already display the transaction in the receiver's wallet, but with the status "0 confirmations" or "Awaiting confirmation". This way, a user can ask "Did the transaction arrive at your wallet?" and only confirm after hearing from the receiver (but in this mode, the fee would probably have be paid, at least in part, even if the transaction is canceled).

Solutions but that would make people feel MUCH safer when using cryptocurrencies (even safer then when doing bank-transfers, that don't offer this), and would help with adoption not only for new users, but even for users that might still not use bitcoin for purchases, out of fear of doing something wrong at some point.

**Describe alternatives you've considered**
Implementing just the alias system would already solve most of this

**Additional context**

The chance of typing a wrong wallet address that works is very low, but still, users feel very uneasy when having to transfer funds through bitcoin, and questions about this can be found in most forums about bitcoin. Coming up with a solution for this issue could greatly increase trust and make people relax more when using bitcoin, which I believe is important for greater adoption.

And no one is perfect, people are bound to making mistakes, and bitcoin should not be the network where one day a story surfaces saying "...transferred 100million dollars to the wrong address and no way of recuperating them."

**Comment by MarcoFalke** [comment]
> Allow users to give their wallet's an Alias

Wallets already have a name, which is displayed in the GUI. For CLI usage you'll have to specify the wallet name, unless only a single wallet is loaded.

> Allow the receiver to confirm his wallet BEFORE the transfer-confirmation

This is already possible by just sending the raw transaction out-of-band of the P2P network. It can't be sent on the P2P network because miners would then claim the tx fee. The receiver could then broadcast the tx if everything checks out.

As an alternative you could use Lightning.

**Comment by CRYONE7** [comment]
WHAT IS GITHUB?
Re0iawPi8muiq6J36ZUZKwsKL2nwjCIm91on8wGoTUir1lyytulafA4JHMsIos2Ak3za2UKAEZrEfx0dXm/Ano ang BATAS? WHAT IS LAW? Phone Number: 63 928 3977 944/GOOGLE Search:Chrystopher C. Dizon,1670 Garcia Street,Balibago,Angeles City ,Pampanga PhilippinesZip20Code 2009/Bitcoin Transaction Id:5146ac5310133fbb01439666131588006543ab5364435b748ddfc95a8cb8d63f/blockchain.com/bitcoin.com/blockchair.com/etherscan.io/googleuser.com/wikipedia.org

**Comment by MarcoFalke** [comment]
Closing for now. Let us know if there are any other questions.
