### ISSUE TITLE
Make PrecomputedData hold references instead of pointers?

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#22438]
It would be a lot cleaner and get rid of a bunch of messy asserts/not asserted pointers if these were references.

In which situations would we need the API to allow us to not pass a precomputed data or a transaction into the checker?

https://github.com/bitcoin/bitcoin/pull/21702#discussion_r616858194

**Comment by JeremyRubin** [comment]
@sipa ^

**Comment by MarcoFalke** [comment]
Should be fine to do as long as you add `LIFETIMEBOUND` where needed. See also https://github.com/bitcoin/bitcoin/pull/19426

**Comment by MarcoFalke** [comment]
https://github.com/bitcoin/bitcoin/pull/22793 might fix this
