### ISSUE TITLE
Schnorr sig implementation diverges from the BIP340 standard

### ISSUE THREAD

**Issue by antonio-fr** [bitcoin/bitcoin#22435]
The [BIP340 SchrorrSig standard](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki) states that during the signature there is a verification step, aborting the signature if verification fails. It is not mandatory, "_it is recommended, but can be omitted if the computation cost is prohibitive_".

The underlying secp256k1 library is written in C and ASM is very very efficient on multiple platforms. I can't see so much case where this cost is prohibitive. The only cases I can see is on small connected devices, embedded systems, or security chips, which are running below 50 Mhz, without full crypto-accelerator. Also this library is the central security implementation in Bitcoin and many other blockchains, and it should should enforce best security practices. Plus the embedded small platforms would be the most vulnerable about the provoked computation errors to leak the private keys. But it is not an issue if the small devices has only a small amount in its private key.

The [reference implementation in Python](https://github.com/bitcoin/bips/blob/master/bip-0340/reference.py#L120) is performing this verification step, in accordance with the standard.

The [libsecp256k1 library code documentation used here](https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/secp256k1/include/secp256k1_schnorrsig.h#L63) explains that the _secp256k1_schnorrsig_sign_ method "_does not strictly follow BIP-340 because it does not verify the resulting signature. Instead, you can manually use secp256k1_schnorrsig_verify and abort if it fails._" So this is up to the secp256k1 library users, here the Bitcoin developers, to add the verification of the signature.

I propose the following change :

Adding the verification step [in src/key.cpp CKey::SignSchnorr method](https://github.com/bitcoin/bitcoin/blob/master/src/key.cpp#L277).
And make this optional with compilation flags, by default activated, and users of this consensus software can choose to disengage this security intentionally if they feel that can hurt the computation time over security when signing. For example a leaf key making hundred thousands small transactions a day, with small amount in the address balance, in a small slow embedding device.

At the very least, one should add a comment note in the SignSchnorr code (or header), explaining and justifying how the computation cost is prohibitive, so the verification step is omitted. For now the comment says SignSchnorr "_create a BIP-340 Schnorr signature_" and that builds an incorrect feeling of security like as it would follow the given standard.

An other way, can be to amend the standard, to relax the recommendation, and it could state the verification step is only a possibility to zealous user for stronger security.

From the security point of view, the verification step has to be added. We just need to discuss users experiences and usage of this software, if the removal of this security protection is a benefit for most users. And especially, from the standard statement, justify that the computation cost is prohibitive, so this security step can be omitted like it is now. The standard makes the choice to strengthen the security against some kind of attacks, and states this can be disabled if this security measure uses prohibitive resources in practice. The standard doesn't say this is an extra feature up to the implementation choice. Actually, this is _recommended_, but there are specific conditions covering the reasons when it can be omitted.

The optimizations to reduce the computation resources is focused on signatures checks, and should not be a matter over security for the signing process.

**Comment by tylerchambers** [comment]
We should definitely be verifying signatures, IMO. Is there any prior discussion on this that might indicate why it was left out?
Perhaps @sipa could provide some additional context here? (thanks in advance!)

**Comment by achow101** [comment]
It's unnecessary to verify the signature immediately after signing because a transaction's witness is fully verified after signing.

**Comment by sipa** [comment]
Hmm, but isn't it possible that a potentially corrupted signature ends up in PSBT?

**Comment by achow101** [comment]
> Hmm, but isn't it possible that a potentially corrupted signature ends up in PSBT?

But we still use `VerifyScript` at the end of `ProduceSignature`. Even so, if there is memory corruption which results in the signature copied into the PSBT being invalid, verifying immediately after signing wouldn't protect against that.

**Comment by sipa** [comment]
@achow101 The concern is a memory/CPU error _during_ signing, because those can leak private key information. If a correctly-created signature accidentally gets corrupted there is no issue.

**Comment by achow101** [comment]
That makes sense. We should do that for the ECDSA functions too then (`Sign` and `SignCompact`).

**Comment by sipa** [comment]
Yeah, I think so.
