### ISSUE TITLE
Cannot sign a transaction with P2WSH/P2SH while using signrawtransactionwithwallet

### ISSUE THREAD

**Issue by liorko87** [bitcoin/bitcoin#22451]
I'm creating a raw transaction using the RPC command `createrawtransaction`  When I'm signing the transaction with the RPC command `signrawtransactionwithwallet`- I'm receiving the following error: 
```
response code: 500 responseMessage Internal Server Error, response: {"result":null,"error":{"code":-8,"message":"redeemScript/witnessScript does not match scriptPubKey"},"id":"1"
```
When I'm using `signrawtransactionwithkey` the transaction signed (and sent) correctly.

Bitcoin version: 0.21
OS: Linux/Windows

**Comment by MarcoFalke** [comment]
What are the steps to reproduce (on regtest, if possible)?

**Comment by liorko87** [comment]
I tried it on mainnet, but I'm assume that the steps are identical for regtest.

1. Create a new address: 'getnewaddress`
2. Create raw transaction using `createrawtransaction`
3. Sign the transaction with `signrawtransactionwithwallet`

At the bitcoin.conf I added this line:
```
addresstype=p2sh-segwit
```

**Comment by prayank23** [comment]
> I tried it on mainnet, but I'm assume that the steps are identical for regtest.

@liorko87 Can you try this on testnet in a new wallet?

> 2. Create raw transaction using `createrawtransaction`

What parameters did you use with `createrawtransaction`? I am not able to reproduce this using the steps you mentioned

**Comment by liorko87** [comment]
@prayank23 I tried also on the testnet and the same happens to me.
I also generated new SegWit addresses and received this error after I called `signrawtransactionwithkey`:
`"error": "Witness program hash mismatch"`

**Comment by MarcoFalke** [comment]
We will need exact steps to reproduce (with arguments you provided to the calls)

**Comment by liorko87** [comment]
Steps to reproduce:
1. Generate two new addresses in different wallets 
```
./bitcoin-cli --datadir=~/bitcoinNodes/node1 getnewaddress
./bitcoin-cli --datadir=~/bitcoinNodes/node2 getnewaddress
```
2. Set transaction fee
```
./bitcoin-cli --datadir=~/bitcoinNodes/node1 settxfee 0.02
```
3.  Send money to address
```
./bitcoin-cli --datadir=~/bitcoinNodes/node1 sendtoaddress <wallet_2_address> 0.5
```
4. Create raw transaction
```
./bitcoin-cli --datadir=~/bitcoinNodes/node1 createrawtransaction \
 '[{"txid":"tx_id_stage#3","vout":0}]' \
 '[{"<wallet_1_address>": amount_available_after_transaction_completed}]
```
5. Signed the raw transaction- I tried with `signedrawtransactionwithwallet` and `signrawtransactionwithkey`
```
./bitcoin-cli --datadir=~/bitcoinNodes/node1/signrawtransactionwithkey signed_tx_hex \
 '[private_key_array]'
```

**Comment by liorko87** [comment]
Here is another insight- when I'm generating two SegWit addresses and remove the last stage (`signrawtransactionwithkey`), everything works perfectly.

**Comment by liorko87** [comment]
The issue was using an address that is not in the wallet.
Therefore, I could not sign the transaction.
