### ISSUE TITLE
[Question]how can i change maxfeerate in sendrawtransaction?

### ISSUE THREAD

**Issue by lpf763827726** [bitcoin/bitcoin#22466]
I follow the [developer.bitcoin.org](https://developer.bitcoin.org/reference/rpc/sendrawtransaction.html) and try JSON-RPC in golang, but i don't know how can i change maxfeerate,there is no Examples about this, only the "hexstring". i only have 0.002 test BTC, please help me how can i change the maxfeerate

the code in golang:
```
hexstring := "020000000001014d4e302ec3fbda1abb365****"
fee := 0.0001
str_fee := strconv.FormatFloat(fee, 'f', -1, 64)
reqJson := "{\"method\":\"sendrawtransaction\",\"params\":[\""+ hexstring +"\", "+ fee +"],\"id\":\"sendrawtransaction\"}";
returnJson, err := rpcClient.send(reqJson)
```

![2021-07-16_17-54](https://user-images.githubusercontent.com/43004977/125930769-f8f46d4e-e474-42cc-bcea-18ef4db193e7.png)
![2021-07-16_17-55](https://user-images.githubusercontent.com/43004977/125930787-6dbf68f6-4140-408a-9b23-2fac52928752.png)
![2021-07-16_17-57](https://user-images.githubusercontent.com/43004977/125930793-492a93b7-e20c-4065-8226-5f8a6f9d33f5.png)

**Comment by MarcoFalke** [comment]
bad-txns-in-belowout is telling you that the transaction is invalid (`hexstring` param), not the maxfeerate param.

Let us know if you have any other questions.

**Comment by lpf763827726** [comment]
i change fee in golang, it work, maybe i just don't understand what mean maxfeerate in the page,so i'm stuck
