### ISSUE TITLE
Assertion `nRndPos1 < vRandom.size() && nRndPos2 < vRandom.size()' failed

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#22467]
The problem was originally reported in https://github.com/bitcoin/bitcoin/issues/22450#issuecomment-880629375. This is a dedicated issue to track it independently because it is a different problem than the one reported in #22450 OP/description.

```
fuzz: addrman.cpp:149: void CAddrMan::SwapRandom(unsigned int, unsigned int): Assertion `nRndPos1 < vRandom.size() && nRndPos2 < vRandom.size()' failed.
```

To reproduce:
```sh
FUZZ=addrman_deserialize ./src/test/fuzz/fuzz /tmp/crash-ef7d4a4f940b8fdb4999f6a92969260cf8e1405f.log
```
[crash-ef7d4a4f940b8fdb4999f6a92969260cf8e1405f.log](https://github.com/bitcoin/bitcoin/files/6830072/crash-ef7d4a4f940b8fdb4999f6a92969260cf8e1405f.log)

**Comment by vasild** [comment]
Fix pending at https://github.com/bitcoin/bitcoin/pull/22468

**Comment by MarcoFalke** [comment]
OSS-Fuzz duplicate report from today: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36255
