### ISSUE TITLE
[Question]how can i use ip:host not localhost:port in RPC?

### ISSUE THREAD

**Issue by lpf763827726** [bitcoin/bitcoin#22477]
I want to use ip(LAN IP) in RPC, not 127.0.0.1 or localhost, but i try to change the configuration of conf with [this](https://github.com/bitcoin/bitcoin/blob/853ac47705c8abd9b8bda2da59eb043d9591491c/share/examples/bitcoin.conf) , but it didn't work

I have been try to close firewall, still not work, and try to add more rpcallowip one by one

my system is ubuntu 20.04

my conf now is:
```
server=1
testnet=1
rpcuser=test
rpcpassword=123456
rpcallowip=0.0.0.0
rpcallowip=127.0.0.1
rpcallowip=192.168.2.36
rpcallowip=192.168.2.36/255.255.255.0
```

command report:
```
2021/07/17 12:33:23 Post "http://192.168.2.36:18332": dial tcp 192.168.2.36:18332: connect: connection refused
```

(it work in localhost and 127.0.0.1)
what should i do?

**Comment by i5hi** [comment]
Try a conf like this:

```
server=1
testnet=1
[test]
rpcuser=test
rpcpassword=123456
rpcport=18333
rpcallowip=127.0.0.1
rpcallowip=192.168.2.36
rpcallowip=192.168.2.36/255.255.255.0
```

**Comment by lpf763827726** [comment]
> Try a conf like this:
> 
> ```
> server=1
> testnet=1
> [test]
> rpcuser=test
> rpcpassword=123456
> rpcport=18333
> rpcallowip=127.0.0.1
> rpcallowip=192.168.2.36
> rpcallowip=192.168.2.36/255.255.255.0
> ```

thanks for answer, but still not work,i try to connect :18332 and :18333,still no good

**Comment by i5hi** [comment]
This resource could be helpful 
https://jlopp.github.io/bitcoin-core-config-generator/#config=eyJjb3JlIjp7ImJsb2NrZmlsdGVyaW5kZXgiOiIxIn19

**Comment by lpf763827726** [comment]
I try to add `rpcbind=0.0.0.0` in conf, it work, if i want it use in mainnet, is it only delete [test] and change the port?

**Comment by i5hi** [comment]
or add [main] with different port and other settings

**Comment by lpf763827726** [comment]
ok, thank you so much, i will try it when i finish in testnet
