### ISSUE TITLE
Changing I2P ports in addrman may wrongly skip some entries from "new" buckets

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#22470]
The problem was originally reported in https://github.com/bitcoin/bitcoin/issues/22450#issuecomment-880602891. This is a dedicated issue to track it independently because it is a different problem than the one reported in #22450 OP/description.

> If the same I2P address appears in multiple new buckets, then the first time this loop finds that address, it'll update the port and reposition it in that bucket. Any subsequent times that the address is encountered, it will already have had its port updated so the inner loop will `continue` ...

Thanks, @jnewbery!

**Comment by vasild** [comment]
Fix pending at https://github.com/bitcoin/bitcoin/pull/22471

**Comment by jonatack** [comment]
Indeed, this was a good find by @jnewbery.
