### ISSUE TITLE
Why my bitcoin-qt records no such RPC "listtransactions"

### ISSUE THREAD

**Issue by lpf763827726** [bitcoin/bitcoin#22524]
I back up the database in qt, then i try to use `listtransactions "*" 500 0` search my all transactions (my transactions only about 50), but i can't search 2 txid in `listtransactions`

![2021-07-22_12-06](https://user-images.githubusercontent.com/43004977/126589014-74d3b34b-f1be-4e3b-b739-1be537a04872.png)
![2021-07-22_12-09](https://user-images.githubusercontent.com/43004977/126589172-b447e0f6-829a-435a-bae1-7fd15ab6248e.png)

Then i try to use `gettransaction` to search this two txid, i found it, but not any details

![2021-07-22_12-08](https://user-images.githubusercontent.com/43004977/126589160-85aba663-58eb-42bb-81a4-acdadb313114.png)
![2021-07-22_12-13](https://user-images.githubusercontent.com/43004977/126589169-db4f7482-8440-4752-bfd4-8e7b814813f7.png)

but i can check it in [here](https://live.blockcypher.com/btc-testnet/tx/0d45dacc0e50066a55c13b54cdcd6e365bb90be3a492c55bf4200b01d02fd748/) and [here](https://live.blockcypher.com/btc-testnet/tx/9e85595156e661a9748a52cd2fa6b3bd1e85a6bd6f4ba13c382db19baa8f2117/#9e85595156e661a9748a52cd2fa6b3bd1e85a6bd6f4ba13c382db19baa8f2117-readMore)

These two txids are: 
`0d45dacc0e50066a55c13b54cdcd6e365bb90be3a492c55bf4200b01d02fd748`
`9e85595156e661a9748a52cd2fa6b3bd1e85a6bd6f4ba13c382db19baa8f2117`

What happen is this? Did I use the wrong RPC method?

**Comment by lpf763827726** [comment]
I use `gettransaction` check other txid it have details, and they are all show in `listtransactions`

**Comment by prayank23** [comment]
> I back up the database in qt, then i try to use listtransactions "*" 500 0 search my all transactions (my transactions only about 50), but i can't search 2 txid in listtransactions

Not sure why you couldn't find 2 transactions in it but I have explained few things about `listtransactions` in this answer: https://bitcoin.stackexchange.com/a/106127/


> Then i try to use gettransaction to search this two txid, i found it, but not any details. These two txids are:
0d45dacc0e50066a55c13b54cdcd6e365bb90be3a492c55bf4200b01d02fd748
9e85595156e661a9748a52cd2fa6b3bd1e85a6bd6f4ba13c382db19baa8f2117

I have shared the steps which you can follow to get information about inputs and outputs for your transaction:

```
$ bitcoin-cli getrawtransaction 0d45dacc0e50066a55c13b54cdcd6e365bb90be3a492c55bf4200b01d02fd748
```
```
0200000000010102a174af0e050d47ab0d97de5061c1ff63039af1057fc0831caa908b5d5f5bb00100000000ffffffff02e803000000000000160014cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec2823000000000000160014dc5f9f8d627ae1d05b749bff299276b01fe65bf40247304402206bd02dc89ef5f85f6e67221ab75a00761f659357bfad4cbc2438e647ac8fefd40220507fe9d99035b62fc27a3475070ebbbd0d4c3bee5617175dbcba03170eab44f20121022a652d8f4bd0533797f8ce53aa40563eacf32c2d0a7c0a184aadb7504d960e6900000000
```
```
$ bitcoin-cli decoderawtransaction 0200000000010102a174af0e050d47ab0d97de5061c1ff63039af1057fc0831caa908b5d5f5bb00100000000ffffffff02e803000000000000160014cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec2823000000000000160014dc5f9f8d627ae1d05b749bff299276b01fe65bf40247304402206bd02dc89ef5f85f6e67221ab75a00761f659357bfad4cbc2438e647ac8fefd40220507fe9d99035b62fc27a3475070ebbbd0d4c3bee5617175dbcba03170eab44f20121022a652d8f4bd0533797f8ce53aa40563eacf32c2d0a7c0a184aadb7504d960e6900000000
```
```json
{
  "txid": "0d45dacc0e50066a55c13b54cdcd6e365bb90be3a492c55bf4200b01d02fd748",
  "hash": "0685132e0acb402814d26c9a67cb97658522bcd270658f748125155262abde08",
  "version": 2,
  "size": 222,
  "vsize": 141,
  "weight": 561,
  "locktime": 0,
  "vin": [
    {
      "txid": "b05b5f5d8b90aa1c83c07f05f19a0363ffc16150de970dab470d050eaf74a102",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "304402206bd02dc89ef5f85f6e67221ab75a00761f659357bfad4cbc2438e647ac8fefd40220507fe9d99035b62fc27a3475070ebbbd0d4c3bee5617175dbcba03170eab44f201",
        "022a652d8f4bd0533797f8ce53aa40563eacf32c2d0a7c0a184aadb7504d960e69"
      ],
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00001000,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec",
        "hex": "0014cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec",
        "address": "tb1qe5ky5qhpv8g4kkjq84d4ek7mmy5hrchvmcv90y",
        "type": "witness_v0_keyhash"
      }
    },
    {
      "value": 0.00009000,
      "n": 1,
      "scriptPubKey": {
        "asm": "0 dc5f9f8d627ae1d05b749bff299276b01fe65bf4",
        "hex": "0014dc5f9f8d627ae1d05b749bff299276b01fe65bf4",
        "address": "tb1qm30elrtz0tsaqkm5n0ljnynkkq07vkl5zfeuah",
        "type": "witness_v0_keyhash"
      }
    }
  ]
}
```
So we have this information from the above result:

| Inputs  | Outputs |
| ------------- | ------------- |
|       "txid": "b05b5f5d8b90aa1c83c07f05f19a0363ffc16150de970dab470d050eaf74a102", "vout": 1  | tb1qe5ky5qhpv8g4kkjq84d4ek7mmy5hrchvmcv90y (0.00001000)|
|   | tb1qm30elrtz0tsaqkm5n0ljnynkkq07vkl5zfeuah (0.00009000)|

To get  more information about inputs, run the following commands:

```
$ bitcoin-cli getrawtransaction b05b5f5d8b90aa1c83c07f05f19a0363ffc16150de970dab470d050eaf74a102
```

```
02000000000101de726d3e81ea2c3561dbd54d89e524bf697ef99869f89171b1c0e572ecfa7c5a0000000000ffffffff03204e000000000000160014cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec204e00000000000016001410d76e5811f766bf2767b439f29604e038ae199300000000000000001600149867e363621a530bc726d33cd076f914e8062fc20247304402203c34d2c3b5383026dba2b03d194ee8fe4c9d5e1e5bc63fedbe906f5b8066aa3c022063620470d11244d67cff605a3642b4569ccc1d918b2a9a949603947fb872c36e0121031c7a9f9443ff7e62c0685a31c24af4b810dbf09adbee6926db7d7d3b4b18a34b00000000
```

```
$ bitcoin-cli decoderawtransaction 02000000000101de726d3e81ea2c3561dbd54d89e524bf697ef99869f89171b1c0e572ecfa7c5a0000000000ffffffff03204e000000000000160014cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec204e00000000000016001410d76e5811f766bf2767b439f29604e038ae199300000000000000001600149867e363621a530bc726d33cd076f914e8062fc20247304402203c34d2c3b5383026dba2b03d194ee8fe4c9d5e1e5bc63fedbe906f5b8066aa3c022063620470d11244d67cff605a3642b4569ccc1d918b2a9a949603947fb872c36e0121031c7a9f9443ff7e62c0685a31c24af4b810dbf09adbee6926db7d7d3b4b18a34b00000000
```
Check `vout:1` in this transaction below:
```json
{
  "txid": "b05b5f5d8b90aa1c83c07f05f19a0363ffc16150de970dab470d050eaf74a102",
  "hash": "ef3f537f47465f58737a5fe81a2bb5688dc9e82f9d0472fdd86baac4375572e8",
  "version": 2,
  "size": 253,
  "vsize": 172,
  "weight": 685,
  "locktime": 0,
  "vin": [
    {
      "txid": "5a7cfaec72e5c0b17191f86998f97e69bf24e5894dd5db61352cea813e6d72de",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "304402203c34d2c3b5383026dba2b03d194ee8fe4c9d5e1e5bc63fedbe906f5b8066aa3c022063620470d11244d67cff605a3642b4569ccc1d918b2a9a949603947fb872c36e01",
        "031c7a9f9443ff7e62c0685a31c24af4b810dbf09adbee6926db7d7d3b4b18a34b"
      ],
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00020000,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec",
        "hex": "0014cd2c4a02e161d15b5a403d5b5cdbdbd92971e2ec",
        "address": "tb1qe5ky5qhpv8g4kkjq84d4ek7mmy5hrchvmcv90y",
        "type": "witness_v0_keyhash"
      }
    },
    {
      "value": 0.00020000,
      "n": 1,
      "scriptPubKey": {
        "asm": "0 10d76e5811f766bf2767b439f29604e038ae1993",
        "hex": "001410d76e5811f766bf2767b439f29604e038ae1993",
        "address": "tb1qzrtkukq37ant7fm8ksul99syuqu2uxvnk9lw45",
        "type": "witness_v0_keyhash"
      }
    },
    {
      "value": 0.00000000,
      "n": 2,
      "scriptPubKey": {
        "asm": "0 9867e363621a530bc726d33cd076f914e8062fc2",
        "hex": "00149867e363621a530bc726d33cd076f914e8062fc2",
        "address": "tb1qnpn7xcmzrffsh3ex6v7dqahezn5qvt7za39uhw",
        "type": "witness_v0_keyhash"
      }
    }
  ]
}
```
So finally we have all the information about inputs and outputs for your first transaction similar to block explorer:

| Inputs  | Outputs |
| ------------- | ------------- |
|       tb1qzrtkukq37ant7fm8ksul99syuqu2uxvnk9lw45 (0.00020000) | tb1qe5ky5qhpv8g4kkjq84d4ek7mmy5hrchvmcv90y (0.00001000)|
|   | tb1qm30elrtz0tsaqkm5n0ljnynkkq07vkl5zfeuah (0.00009000)|

**Comment by lpf763827726** [comment]
> I have shared the steps which you can follow to get information about inputs and outputs for your transaction:

thanks for your share, but now i can't find this two txid in `listtransactions`, i can't do anything with `getrawtransaction`, because i don't know whice one txid i lost if i use automation to search

now my transactionList is only use `listtransactions`

if there have some way to find all txid, can you teach me?

**Comment by prayank23** [comment]
> if there have some way to find all txid, can you teach me?

[`listtransactions`](https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/listtransactions/) should list all transactions IMO. If few transactions are missing, you can share all the details of your wallet, steps to reproduce, logs etc. and ask a question on [Bitcoin Stackexchange](https://bitcoin.stackexchange.com)

**Comment by lpf763827726** [comment]
> [`listtransactions`](https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/listtransactions/) should list all transactions IMO. If few transactions are missing, you can share all the details of your wallet, steps to reproduce, logs etc. and ask a question on [Bitcoin Stackexchange](https://bitcoin.stackexchange.com)

Although I also want to provide you with the wrong steps, But I'm so sorry, I don't know how it happened
I guess this error may occur because I sent the transaction to txid's current address?
Also, thank you very much for your help, I'll try to see if this problem will happen again
