### ISSUE TITLE
Please make GUI responsive while syncing with network, especially to stop sync 

### ISSUE THREAD

**Issue by gaga9999** [bitcoin/bitcoin#22535]
It is not possible to enter a transaction while the gui is syncing, because its lagging. 
sometimes it is important to enter a transaction and go away and the transaction will only be fullfilled after the blockchain sync is finished. for that there needs to be a responsive button to on/off the sync. i know the network symbol is there, but it does work that laggy..thanks
as a workaround i tried -connect=127.0.0.1

a simple fix would be a -startwithnosync option

same for "processing blocks on disk". everything is stuck.

**Comment by hebasto** [comment]
@gaga9999 It would be nice to move this issue into the GUI repo: https://github.com/bitcoin-core/gui/issues

**Comment by gaga9999** [comment]
I think thats a core feature request : give more regular cpu time to gui

**Comment by prayank23** [comment]
> I think thats a core feature request : give more regular cpu time to gui

Not sure how qt works but in .NET this is fixed by [multithreading](https://docs.microsoft.com/en-us/dotnet/standard/threading/threads-and-threading)

Maybe it is something related to [multithreading](https://doc.qt.io/qt-5/threads-technologies.html) in Bitcoin Core as well.

**Comment by prayank23** [comment]
There is one more thing which can make sync less boring once responsiveness issue is fixed. Share important pull requests from past that improved something in Bitcoin Core. Example: We can share PR 14618 while blocks from October 2018 are syncing.

![image](https://user-images.githubusercontent.com/13405205/126769599-6625385c-f1e1-40e1-8505-c1fe036e4b12.png)

**Comment by practicalswift** [comment]
@prayank23 As developers we might find information about historical issues interesting as technical learning opportunities, but I'm afraid our end-users would find the suggested information box boring/irrelevant at best and confusing/alarming at worst :)

**Comment by prayank23** [comment]
> our end-users would find the suggested information box boring/irrelevant at best and confusing/alarming at worst

Agree. Everyone may not find this information interesting. Maybe an option in `bitcoin.conf` can work. So if user is interested to try this feature can use `debug=prhistory`

**Comment by fanquake** [comment]
As suggested this belongs in the GUI repo. I'm certain we've got a generic "improve performance of the GUI" issue open there, but cannot find it now.

> There is one more thing which can make sync less boring once responsiveness issue is fixed. Share important pull requests from past that improved something in Bitcoin Core.

This isn't something we are going to do.

**Comment by prayank23** [comment]
> This isn't something we are going to do.

No problem. Code is open source and users can try different things if they are okay with it. I am going to add such feature in one of my project so suggested it here.

Here's the basic code one can use to try this in Bitcoin Core by adding in [`src/qt/modaloverlay.cpp`](https://github.com/bitcoin/bitcoin/blob/master/src/qt/modaloverlay.cpp):

```C++
    QString year = QLocale{QLocale::English}.toString(blockDate, "yyyy");
    
    switch (year.toInt())
    {
    
    case 2009:
        break;
    case 2010:
        break;
    case 2011:
        break;
    case 2012:
        break;
    case 2013:
        break;
    case 2014:
        break;
    case 2015:
        break;
    case 2016:
        break;
    case 2017:
        break;
    case 2018:
        break;
    case 2019:
        break;
    case 2020:
        break;
    case 2021: ui->infoText->setText(tr("PR #### (author)"));
               ui->infoTextStrong->setText(tr("Short Description"));
        break;
    }
```
