### ISSUE TITLE
Blocks are not including transactions with a fee below 1 Satoshi per byte

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#22540]
![image](https://user-images.githubusercontent.com/1530283/128313199-8d0fc57a-386c-448c-b7cc-4856058c765f.png)
The default settings of bitcoind are such that blocks are not including free transactions, as they used to.

Can the default settings be changed to allow this, given that there is now capacity to do so?

**Comment by jarolrod** [comment]
Why? What are the consequences of doing this? A change like this requires heavy supporting reasoning that is not included in this issue ...

Some context:
- https://github.com/bitcoin/bitcoin/pull/7022
- https://github.com/bitcoin/bitcoin/pull/7600

**Comment by MarcoFalke** [comment]
You can help by reviewing #13990

**Comment by rebroad** [comment]
> Why? What are the consequences of doing this? A change like this requires heavy supporting reasoning that is not included in this issue ...
> 
> Some context:
> 
> * [Change default block priority size to 0 #7022](https://github.com/bitcoin/bitcoin/pull/7022)
> * [Mining: Select transactions using feerate-with-ancestors #7600](https://github.com/bitcoin/bitcoin/pull/7600)

I've updated the issue as it's also not including transactions (as far as I can tell) with a fee below 1 satoshi per byte, so perhaps the argument for including these is much stronger than the argument to include free transactions.

**Comment by rebroad** [comment]
I no longer think this is an issue
