### ISSUE TITLE
gcc -Wtype-limits warnings in consensus/params.h

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#22587]
**Expected behavior**

Testing PR's, I build from source without errors.

**Actual behavior**

Occasionally, I get this repeated output:

> ./consensus/params.h: In function ‘constexpr bool Consensus::ValidDeployment(Consensus::BuriedDeployment)’:
> ./consensus/params.h:26:85: warning: comparison is always true due to limited range of data type [-Wtype-limits]
>  constexpr bool ValidDeployment(BuriedDeployment dep) { return DEPLOYMENT_HEIGHTINCB <= dep && dep <= DEPLOYMENT_SEGWIT; }
>                                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
> ./consensus/params.h: In function ‘constexpr bool Consensus::ValidDeployment(Consensus::DeploymentPos)’:
> ./consensus/params.h:34:81: warning: comparison is always true due to limited range of data type [-Wtype-limits]
>  constexpr bool ValidDeployment(DeploymentPos dep) { return DEPLOYMENT_TESTDUMMY <= dep && dep <= DEPLOYMENT_TAPROOT; }

**To reproduce**

This happens sporadically, and I have not been able to figure out how to reproduce

**System information**

Compiling master/testing various PR's.

Qubes 4.0.4, in a Debian-10 standalone-VM with normal networking.  Intel x86_64.  SSD

Nothing in debug file.  Bitcoin-qt still successfully compiles and opens.

**Comment by MarcoFalke** [comment]
What is the version of the compiler?

**Comment by tryphe** [comment]
This is to be expected, https://github.com/bitcoin/bitcoin/pull/19438 was merged recently which introduced these warnings.

When you are compiling other branches and you don't see the warning, you are compiling other branches that don't have the changes in https://github.com/bitcoin/bitcoin/pull/19438.

Also, note that a warning should not be considered an error. Warnings could indicate problems, but not necessarily.

**Comment by tryphe** [comment]
Fwiw, I'm also running Debian 10 using gcc 8.3 and can confirm the warning (I assumed other platforms would see it as well though)

**Comment by jonatack** [comment]
I'm not seeing it with clang 11 and 13. Trying with Debian gcc 10.2.1 now.

**Comment by Rspigler** [comment]
@MarcoFalke gcc 8.3.0

@tryphe That makes sense, thanks.  Weird that @jonatack does not see it as well.  I will wait for others to confirm before closing?

**Comment by tryphe** [comment]
I think it's okay to leave this open. A warning should be fixed, although the message is nothing to be concerned about. When the dummy value changes in the future, it could fix the warning.

**Comment by tryphe** [comment]
I'm not sure I can grok the purpose of a runtime check like `DEPLOYMENT_HEIGHTINCB <= dep`. If we want `DEPLOYMENT_HEIGHTINCB` to be the lowest value in the range, can't we just use some compile-time assertions?:

```
static_assert(DEPLOYMENT_HEIGHTINCB < DEPLOYMENT_CLTV, "DEPLOYMENT_HEIGHTINCB is not the lowest value in range");
static_assert(DEPLOYMENT_HEIGHTINCB < DEPLOYMENT_DERSIG, "DEPLOYMENT_HEIGHTINCB is not the lowest value in range");
static_assert(DEPLOYMENT_HEIGHTINCB < DEPLOYMENT_CSV, "DEPLOYMENT_HEIGHTINCB is not the lowest value in range");
static_assert(DEPLOYMENT_HEIGHTINCB < DEPLOYMENT_SEGWIT, "DEPLOYMENT_HEIGHTINCB is not the lowest value in range");
```

It's a bit heavy handed though and kind of redundant, but maybe I'm missing the point of the runtime comparison.

**Comment by tryphe** [comment]
ping @ajtowns :point_up:

**Comment by MarcoFalke** [comment]
> I'm not sure I can grok the purpose of the runtime check DEPLOYMENT_HEIGHTINCB <= dep here. 

enums are just integers and there is nothing that forbids out-of-range enum values in the C++ standard, so a check is needed here to avoid UB

**Comment by MarcoFalke** [comment]
This bug might be fixed in gcc 8.4, since I am not seeing it in the guix output, which uses gcc 8.4?

**Comment by ajtowns** [comment]
Yuck. gcc's giving a warning because the check is redundant since both TESTDUMMY and HEIGHTINCB have the minimum value for their corresponding underlying type, so there's no lower value possible.

Could avoid the problem by having `ValidDeployment` just check the upper bound `dep <= DEPLOYMENT_SEGWIT` and `dep < MAX_VERSION_BITS_DEPLOYMENTS`, and adding static asserts for the lower bounds in deploymentstatus.cpp something like:

```c++
#include <type_traits>

/* ValidDeployment only checks upper bounds for ensuring validity,
 * so check that we really start at the lowest possible value */

template<typename T, typename X, typename U=typename std::underlying_type<T>::type>
static constexpr bool is_minimum(const X x) { return std::is_same<T,X>::value && x == std::numeric_limits<U>::min(); }

static_assert(is_minimum<Consensus::BuriedDeployment>(Consensus::DEPLOYMENT_HEIGHTINCB), "heightincb is not minimum value for BuriedDeployment");
static_assert(is_minimum<Consensus::DeploymentPos>(Consensus::DEPLOYMENT_TESTDUMMY), "testdummy is not minimum value for DeploymentPos");
```

**Comment by tryphe** [comment]
Thanks for that! I am running the changes above and the warning is gone on gcc 8.3. Let me know if you want to create a PR. I can do it if you'd like.

> enums are just integers and there is nothing that forbids out-of-range enum values in the C++ standard, so a check is needed here to avoid UB

I'm not sure I understand. dep is 16 bits. `DEPLOYMENT_HEIGHTINCB` is -32768. If something is lower, it doesn't compile. How is it possible to be out of range?

**Comment by MarcoFalke** [comment]
> How is it possible to be out of range?

Sorry, didn't look close enough on the code. I commented on why this type of check is needed in general.

**Comment by ajtowns** [comment]
> Thanks for that! I am running the changes above and the warning is gone on gcc 8.3. Let me know if you want to create a PR. I can do it if you'd like.

See #22597

**Comment by katesalazar** [comment]
Once and if you fix this in the master branch, it'd be lovely if you backport to the 22.x branch, this is happening in the v22.0rc1 tag too.
