### ISSUE TITLE
`make install` creates files/folders with bad permissions if custom umask is used

### ISSUE THREAD

**Issue by xanoni** [bitcoin/bitcoin#22595]
The `make install` script, which most users would run via `sudo` to install into `/usr/local`, will use the current umask of the root user when creating certain files and directories. If one uses a restrictive umask by default (e.g. `umask 077`), this means that only the root user will be able to use the full Bitcoin package.

**Expected behavior**

The install script creates all directories and files, including man pages, etc., with permissions `644` / `755`.

**Actual behavior**

Certain folders are created using the default umask, e.g.:

- /usr/local/share/man/man1/
- /usr/local/lib/pkgconfig/
- [...]

This means that only root can access files in these folders and other users won't be able to read the man pages (for example).

**To reproduce**

```bash
$ ./autogen.sh
$ make
$ sudo -iu root
% umask 077
% make install
```

**System information**

OS: Linux
bitcoind version: HEAD

**Comment by hebasto** [comment]
@xanoni 

Does #17127 [fix](https://github.com/bitcoin/bitcoin/pull/17127#issuecomment-1344083458) this issue for you?

**Comment by willcl-ark** [comment]
It did on my system™ :)

**Comment by xanoni** [comment]
> @xanoni
> 
> Does #17127 [fix](https://github.com/bitcoin/bitcoin/pull/17127#issuecomment-1344083458) this issue for you?

I'm currently unable to test this, so please don't wait for my feedback. Thank you.
