### ISSUE TITLE
Continue improvement of flag parsing / validation.

### ISSUE THREAD

**Issue by tylerchambers** [bitcoin/bitcoin#22594]
I am interested in continuing the work started here: https://github.com/bitcoin/bitcoin/pull/16097
Basically, I would like to continue the expansion of util/system.cpp CheckValid for checking of additional types (e.g: ALLOW_STRING, etc) -> then start assigning and checking.

Is this already being undertaken? If not, I'd be more than happy to pick it up.

**Comment by ryanofsky** [comment]
Yes, there are a number of followups that have been stuck in review, and one way to help would be contributing review or working to fix issues came up in review comments! Followup PRs are:

- [#16545](https://github.com/bitcoin/bitcoin/pull/16545) - implements `ALLOW_INT` `ALLOW_STRING` `ALLOW_BOOL` settings validation
- [#17580](https://github.com/bitcoin/bitcoin/pull/17580) - based on [#16545](https://github.com/bitcoin/bitcoin/pull/16545), enforces consistent application of `ALLOW_LIST` flag internally
- [#17493](https://github.com/bitcoin/bitcoin/pull/17493) - based on [#17580](https://github.com/bitcoin/bitcoin/pull/17580), implements `ALLOW_LIST` validation, forbidding multiple ambiguous non-list settings in the config file, while still allowing non-list overrides on the command line.
- [#17581](https://github.com/bitcoin/bitcoin/pull/17581) - based on [#17493](https://github.com/bitcoin/bitcoin/pull/17493) just makes a code simplification enabled by the previous PRs
- [#17783](https://github.com/bitcoin/bitcoin/pull/17783) -  based on [#17580](https://github.com/bitcoin/bitcoin/pull/17580) fixes strange option interpretations when various list options are negated and adds a check to prevent this type of buggy option parsing in the future

Also may be interesting:

- [#17508](https://github.com/bitcoin/bitcoin/issues/17508) - issue suggesting more settings cleanups and fixes
- [#15936](https://github.com/bitcoin/bitcoin/pull/15936) - somewhat related PR switching `bitcoin-qt` to store node & wallet settings in settings.json so `bitcoin-qt` and `bitcoind` are not using different settings from each other
