### ISSUE TITLE
Remove txindex migration code

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#22615]
The txindex was moved to its own database in #13033. As part of that change, data migration functionality was added, allowing the txindex to be maintained across upgrade without having to rebuild the entire index from scratch:

https://github.com/bitcoin/bitcoin/blob/5cf28d5203a6203355283ea59f071af6a468d239/src/index/txindex.cpp#L75-L90

13033 was included in v0.17, released in October 2018 and EOL in August 2020. Anyone who hasn't upgraded at this point is running unsupported code, and shouldn't have expectations around upgrading their node without having to rebuild the index. We should simplify the code by removing the `MigrateData()` functionality.

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
I presume the cleanest solution would be to remove all code and document that users wishing to recover the disk space, can use a full reset (`-reindex`)?

**Comment by jnewbery** [comment]
> I presume the cleanest solution would be to remove all code and document that users wishing to recover the disk space, can use a full reset (-reindex)?

Sounds reasonable
