### ISSUE TITLE
Critical time check intermittent fail in blockfilter_index_tests.cpp

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#22614]
I encountered this while running `make check` on #21800 locally (stock x86_64 host w/ Ubuntu 20.04, nothing special). Making a separate issue because I don't think it's related to the changes there:
```
./test/blockfilter_index_tests.cpp(140): fatal error: in "blockfilter_index_tests/blockfilter_index_initial_sync": critical check time_start + timeout_ms > GetTimeMillis() has failed
pure virtual method called
terminate called without an active exception
```
I cannot reproduce it.

**Comment by MarcoFalke** [comment]
Duplicate of #16337 ?

**Comment by laanwj** [comment]
Looks like it!

**Comment by practicalswift** [comment]
@laanwj 

> I cannot reproduce it.

Note that this issue can be reproduced using the excellent tool `rr` in `--chaos` mode. See instructions in https://github.com/bitcoin/bitcoin/issues/16337#issuecomment-629360810 :)
