### ISSUE TITLE
Rename ./autogen to ./bootstrap?

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#22639]
As @dongcarl and I were figuring out my GUIX setup, one minor point of confusion was whether [AutoGen](https://www.gnu.org/software/autogen/) was present on my system. Not be confused with our `./autogen`. It might make sense to rename this to `./bootstrap` as several other projects have done.

**Comment by hebasto** [comment]
Are there any known (possible) drawbacks of renaming?

**Comment by fanquake** [comment]
NACK.

> Are there any known (possible) drawbacks of renaming?

Pointlessly breaking a bunch of downstream Bitcoin Core build scripts etc.

**Comment by Sjors** [comment]
That's indeed a good reason not to rename. Adding an alias won't really make the confusion go away.
