### ISSUE TITLE
createwallet with external signer always picks the first external signer, regardless of how many are connected

### ISSUE THREAD

**Issue by josibake** [bitcoin/bitcoin#22636]
**Is your feature request related to a problem? Please describe.**

While testing `22.0rc2` external signer feature, I noticed that if multiple HW wallets are connected to the computer, `createwallet` will always pick the first one without alerting the user in any way. This led to the following unexpected behavior:

1. attach a trezor and create a wallet using `bitcoin-cli createwallet`
2. attach a coldcard while the trezor is still connected and create a second wallet with `bitcoin-cli createwallet`

Both wallets were created fine with no errors, but on further inspection I realized both wallets were connected to the trezor, despite having different names. This is related to #22635 

**Describe the solution you'd like**

Ideally, if multiple external signers are returned from `enumeratesigners` and I then try to create a wallet, I would want `createwallet` to fail and warn me there are multiple external signers. Additionally, an option to specify the fingerprint of the device would be useful, but I think simply failing would be sufficient for now.

**Describe alternatives you've considered**

Granted, this is a rare case where a user would have multiple HW's connected while creating a single sig wallet, so perhaps just documenting that you should only have one connected at a time is a viable solution.

**Comment by Sjors** [comment]
#25235 adds an error message telling the user to only connect one at a time. I elaborated in a comment there how I think it should work longer term.
