### ISSUE TITLE
`i2pacceptincoming` Error;  Testing v22.0rc2

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#22656]
**Expected behavior**
Following the [i2p](https://github.com/bitcoin/bitcoin/blob/master/doc/i2p.md) documentation, you should be able to set `i2pacceptincoming` (along with `i2psam=<ip:port>`) in `bitcoin.conf`.

[Testing v22.0rc2](https://github.com/bitcoin/bitcoin/issues/22634)

**Actual behavior**
I receive the error:

> Error: Cannot parse configuration file: parse error on line 11: i2pacceptincoming.

Instead, I have to set it as a separate command line argument (don't yet have incoming i2p connections, still waiting).

**To reproduce**

Easy to reproduce, just try setting in `bitcoin.conf`.

**System information**
Self-compiled
Qubes 4.0.4, in a Debian-10 standalone-VM with normal networking. Intel x86_64. SSD

**Comment by sipa** [comment]
You need a `=1` after it (this is true for all arguments; the cmdline version defaults to 1 without = sign, but the config file does not have this).

**Comment by Rspigler** [comment]
Need to stop working this late in the night :grimacing:
