### ISSUE TITLE
More than 10 Outbound Peers

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#22655]
**Expected behavior**

10 outbound peers.

**Actual behavior**

I was playing around with Tor and i2p, testing [v22.0rc2](https://github.com/bitcoin/bitcoin/issues/22634), and while manually adding connections, I realized that I had 16 outbound peers.

**To reproduce**

Start v22.0rc2, add peers in this [guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/22.0-Release-Candidate-Testing-Guide) via `addnode`  Interestingly, it seems that having the `addnode=[peer:port]` in `bitcoin.conf` does not violate the 10 outbound peers limit, but if you add the node manually in the console, it does.  I also had the following in my configuration file:

> listen=1
> assumevalid=0
> dbcache=1000
> addresstype=bech32
> avoidpartialspends=1
> changetype=bech32
> maxapsfee=0.01
> i2psam=127.0.0.1:7656
> debug=tor
> debug=i2p

**System information**
Reproduces reliably following the above steps.

Self compiled Bitcoin Core, with `./configure --without-miniupnpc --without-natpmp --enable-hardening --without-bdb --with-qrencode --disable-zmq --with-sqlite=yes`

Qubes 4.0.4, in a Debian-10 standalone-VM with normal networking. Intel x86_64. SSD
Nothing weird in `debug.log`

**Comment by sipa** [comment]
addnode has a separate 8 connection limit, independent from the automatic connections one.

**Comment by Rspigler** [comment]
Ah sorry, wasn't aware.

Closing.
