### ISSUE TITLE
Is it possible to disable bind on onion network listening port?

### ISSUE THREAD

**Issue by josef-v** [bitcoin/bitcoin#22668]
This may also be a bug depending on understanding of `listenonion` option.

**What is happening:** 
We have upgraded bitcoin node from v0.19 to v0.21, bitcoind tries to bind to port 8334 (tor listening), which we use for another service.

**Possible solution:**
Move the port using `bind` option to some unused port.

**Preferred solution:**
Disable listening on this particular port. 

I have tried using `listenonion=0` but the only effect is that the tor service is not started, the port is however still used. Can binding of this port be disabled? And is `listenonion` working correctly?

**Comment by hebasto** [comment]
@josef-v 

```
$ ./bitcoind -version
Bitcoin Core version v0.21.1
Copyright (C) 2009-2020 The Bitcoin Core developers

Please contribute if you find Bitcoin Core useful. Visit
<https://bitcoincore.org/> for further information about the software.
The source code is available from <https://github.com/bitcoin/bitcoin>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

$ ./bitcoind -help | grep -A 6 -e '-bind'
  -bind=<addr>[:<port>][=onion]
       Bind to given address and always listen on it (default: 0.0.0.0). Use
       [host]:port notation for IPv6. Append =onion to tag any incoming
       connections to that address and port as incoming Tor connections
       (default: 127.0.0.1:8334=onion, testnet: 127.0.0.1:18334=onion,
       signet: 127.0.0.1:38334=onion, regtest: 127.0.0.1:18445=onion)

```

Does this work for you:
```
$ ./bitcoind -bind=127.0.0.1:"${YOUR_PORT}"=onion
```
?

**Comment by josef-v** [comment]
@hebasto
Thanks for your response! Yes, this works, we have already tried it and have as a backup solution. 
My goal was to find out if it is possible to disable this port at all. `listenonion` option looks like the way to go but it unfortunately only disables the service in the background and the port itself is still open.

**Comment by hebasto** [comment]
```
$ ./bitcoind -bind=127.0.0.1:8333 -bind=127.0.0.1:8333=onion
```
?

**Comment by hebasto** [comment]
> `listenonion` option looks like the way to go but it unfortunately only disables the service in the background...

Yes, it is documented:
```
$ ./bitcoind -help | grep -A 2 -e '-listenonion'
  -listenonion
       Automatically create Tor onion service (default: 1)

```

**Comment by josef-v** [comment]
> ./bitcoind -bind=127.0.0.1:8333 -bind=127.0.0.1:8333=onion

Thanks, that's what we needed. I didn't realize I can reuse the same port.


> > `listenonion` option looks like the way to go but it unfortunately only disables the service in the background...
> 
> Yes, it is documented:
> 
> ```
> $ ./bitcoind -help | grep -A 2 -e '-listenonion'
>   -listenonion
>        Automatically create Tor onion service (default: 1)
> ```

I know, but I have expected that turning this off will also turn off the listening port. And I am not the only one, two developers from my team suggested this option after reading the docs. The name is a little misleading.

Anyway, thanks for your help, I am closing this issue.
