### ISSUE TITLE
docs: add more examples and clarifications to external-signer.md

### ISSUE THREAD

**Issue by josibake** [bitcoin/bitcoin#22678]
proposing updates to `docs/external-signer.md`, specifically an explanation of how accounts are being used and examples of using the same device to create multiple wallets (motivation and discussion: #22635)

**Comment by fanquake** [comment]
cc @Sjors

**Comment by Sjors** [comment]
I guess the term "create" wallet is a bit confusing. When plugging in a hardware wallet, the wallet already exists, you're just loading keys from it.

There is a BIP 32 account feature buried in ExternalSignerPubkeyMan, which we could expose through the RPC and GUI. That would let you manage multiple wallets with separate address spaces.

**Comment by fanquake** [comment]
If someone wants to add more examples to the external signing docs they can do so, but I don't think need to keep a "add more examples to X optional feature docs" issue open.

**Comment by Rspigler** [comment]
https://github.com/bitcoin/bitcoin/pull/25882
