### ISSUE TITLE
Reduce boost dependency (boost/algorithm/string/split)

### ISSUE THREAD

**Issue by Purva-Chaudhari** [bitcoin/bitcoin#22683]
Proposing a method to remove the dependency of the boost/algorithm/string/split library. It can be done by including a small function in utils or adding a small alternative code patch in its use cases. The proposed method is much more efficient than the  boost/algorithm/string/split. Here is a small demonstration which performs the same task in just 11 microseconds compared to boost library which takes 30 microseconds. ([View here](https://gist.github.com/Purva-Chaudhari/7125b173f7cfba3a5995220ab6a75e89))
The suggested alternative would reduce boost dependency in the files and thus improve their compilation and execution efficiency.

Following reference states that over big data the boost split performs a lot slower compared to stl implementation:
https://stackoverflow.com/questions/5505965/fast-string-splitting-with-multiple-delimiters. 

I'm happy to open a PR with these changes, but currently looking for concept ACKs to confirm if this is a good direction.

**Comment by fanquake** [comment]
Boost removal is an eventual goal of the project. We've had similar proposals to remove these Boost components in the past, i.e #13751, you might want to read through that PR for some context. Note that there are also currently PR's open that remove Boost usage, i.e #18130, so you may also be interested in reviewing those.

**Comment by hebasto** [comment]
> Proposing a method to remove the dependency of the boost/algorithm/string/split library. It can be done by including a small function in utils or adding a small alternative code patch in its use cases.

... a comprehensive set of unit tests must be included as well. And all the new code must be maintained forever :)

> The proposed method is much more efficient than the boost/algorithm/string/split. Here is a small demonstration which performs the same task in just 11 microseconds compared to boost library which takes 30 microseconds.

I don't think the efficiency of the current code is an issue.

> Boost removal is an eventual goal of the project.

After adding `boost::process` it looks like a moving target :)

**Comment by MarcoFalke** [comment]
> After adding boost::process it looks like a moving target :)

At least `boost::process` is optional.

I think before looking into removing header-only boost dependencies, we should be looking into lower hanging fruits such as the filesystem library. See #20744.

**Comment by fanquake** [comment]
Going to close this for now. `boost/algorithm/string/split` has since been removed: #25057.
