### ISSUE TITLE
Fatal LevelDB error: 1 missing files 069071.ldb again.

### ISSUE THREAD

**Issue by openGLnoob** [bitcoin/bitcoin#22717]
I get this issue no once in the last two years on different HDD's. Reindexing works fine, but what if I want to start reindexing not from 0 but from special bloks/chainstate files?
For example, now I have an error:

> Fatal LevelDB error: 1 missing files 069071.ldb

069071.ldb is one from the last files in chainstate. How do I start reindexing starting from a specific file? Or LevelDB organized differently internally and it only makes sense to rebuild from scratch?

**Comment by laanwj** [comment]
If the missing file is for the `chainstate` and not the block index, you can do `-reindex-chainstate` instead of `-reindex` to skip part of the work. It does start from block 0 because the only way to reconstruct a potentially corrupted state is to re-apply all blocks, starting from genesis.
