### ISSUE TITLE
depends: `$(package)_*_env` settings only apply to the first command

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#22719]
For example, `$(package)_config_env` is prepended to `$(package)_config_cmds`, which means that if `$(package)_config_cmds` contains multiple commands chained by `&&`, only the first command would have its environment modified according to `$(package)_config_env`.

https://github.com/bitcoin/bitcoin/blob/b935abb9eb2eeaceb5621e110e1889c2ce1b7734/depends/funcs.mk#L212

Since `$(package)_*_env` settings contain crucial env vars such as `PATH` or `PKG_CONFIG_PATH`, its omission in subsequent commands is likely a bug:

https://github.com/bitcoin/bitcoin/blob/b935abb9eb2eeaceb5621e110e1889c2ce1b7734/depends/funcs.mk#L137-L142

This has lead to problems such as: https://github.com/bitcoin/bitcoin/pull/16883#issuecomment-683817472

A test-able demo of this problem: https://github.com/dongcarl/bitcoin/commit/e233c6d1e96ed35489c6be37f07bd01546083b9e

**Comment by hebasto** [comment]
As `export` (see #19882) looks pretty invasive, maybe `bash -c '...'`?

**Comment by dongcarl** [comment]
> As `export` (see #19882) looks pretty invasive, maybe `bash -c '...'`?

Wouldn't `bash -c '...'` have the same effect as `export`?

**Comment by hebasto** [comment]
> As `export` (see #19882) looks pretty invasive...

The assumption above is wrong.

As a [new sub-shell](https://www.gnu.org/software/make/manual/html_node/Execution.html#Execution) is invoked for each line of the recipe, there are no side effects of using `export` (#19882).

---

> Wouldn't `bash -c '...'` have the same effect as `export`?

Yes, it would.
