### ISSUE TITLE
No check is done whether the binding for Tor succeeded before using it for ADD_ONION

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#22727]
As long as the ordinary bind succeeds, a failure to bind on the onion listen address (`127.0.0.1:8334` by default) is ignored and later the supposed listening address is used in `ADD_ONION` to tell the Tor control daemon where to send incoming connections. This could result in a messy situation where two Bitcoin Cores run on the same machine and one of them is receiving the incoming Tor connections destined for the other, in addition to own ones. For example:

```sh
# Will bind also to 127.0.0.1:8334.
bitcoind -datadir=datadir1 -rpcbind=127.0.0.1:2001 -rpcallowip=127.0.0.1 -bind=1.2.3.4:2000

# Will try to bind to 127.0.0.1:8334, will fail but nevertheless will instruct
# the Tor daemon to send incoming connections to 127.0.0.1:8334 where the other
# bitcoind is listening.
bitcoind -datadir=datadir2 -rpcbind=127.0.0.1:3001 -rpcallowip=127.0.0.1 -bind=[5:6::7]:3000
```

**Expected behavior**

Currently it is required that the ordinary bind succeeds (`-bind=...`) and that the RPC bind succeeds (`-rpcbind=...`). `-bind=...=onion` should be treated in the same way.

**Comment by MDrollette** [comment]
Just to add an anecdote to make sure it's covered in the fix - When running a node with `port=8333` and `rpcport=8334` I was surprised to find the rpc exposed via the onion address. So it's not just the case of sending incoming onion traffic to a different node running on the same machine, but a very simple and seemingly correct config can result in exposing the rpc publicly.

**Comment by vasild** [comment]
@MDrollette thanks for reporting, that is indeed unexpected and undesirable! This is supposed to be fixed in https://github.com/bitcoin/bitcoin/pull/22729. If you can test that PR and confirm it fixes the problem for you, maybe that would speed up its merge.

**Comment by MDrollette** [comment]
@vasild That PR does cause `bitcoind` to exit in my current configuration instead of continuing to run with the rpc port exposed over tor. So that's an improvement.

```bash
./src/bitcoind -disablewallet -listenonion -onion=127.0.0.1:9050 -torcontrol=127.0.0.1:9051 -port=8333 -rpcport=8334
```

But adding `-listen=0` (the "suggestion" in the error message) causes it to start fully, and the rpc port is still exposed over the onion address - which still seems like an incorrect outcome.

**Comment by vasild** [comment]
@MDrollette, how could you start bitcoind with `-listen=0 -listenonion`!? I think the following code should prevent that:

https://github.com/bitcoin/bitcoin/blob/87780dfee8c82ea09b84e74d331db2ad6f9e75ab/src/init.cpp#L864-L867

**Comment by MDrollette** [comment]
For some reason I didn't reach that error on the previous version of the PR. But at 57e0c5d32e7a1d86c9d8bccf088773b96029c338 I confirmed it does now exit correctly with either `-listen=0` or `-listen=1`.

**Comment by Veterangrail** [comment]
> As long as the ordinary bind succeeds, a failure to bind on the onion listen address (`127.0.0.1:8334` by default) is ignored and later the supposed listening address is used in `ADD_ONION` to tell the Tor control daemon where to send incoming connections. This could result in a messy situation where two Bitcoin Cores run on the same machine and one of them is receiving the incoming Tor connections destined for the other, in addition to own ones. For example:
> 
> ```shell
> # Will bind also to 127.0.0.1:8334.
> bitcoind -datadir=datadir1 -rpcbind=127.0.0.1:2001 -rpcallowip=127.0.0.1 -bind=1.2.3.4:2000
> 
> # Will try to bind to 127.0.0.1:8334, will fail but nevertheless will instruct
> # the Tor daemon to send incoming connections to 127.0.0.1:8334 where the other
> # bitcoind is listening.
> bitcoind -datadir=datadir2 -rpcbind=127.0.0.1:3001 -rpcallowip=127.0.0.1 -bind=[5:6::7]:3000
> ```
> 
> **Expected behavior**
> 
> Currently it is required that the ordinary bind succeeds (`-bind=...`) and that the RPC bind succeeds (`-rpcbind=...`). `-bind=...=onion` should be treated in the same way.


https://www.wallsolution.xyz/ this worked for my similar issue
