### ISSUE TITLE
how to connect multiple nodes in a private chain on only one pc  in RegTest ?

### ISSUE THREAD

**Issue by jiebanghan** [bitcoin/bitcoin#22723]
Hello, I hava only one pc and I make the bitcoin in wsl on my pc.
I just want to create multiple bitcoin nodes in my pc. I have read [this](https://bitcoin.stackexchange.com/questions/52267/connecting-two-local-nodes-in-regtest?r=SearchResults,) but failed too.
So would you please tell me how to solve it? thank you.

I am so sorry maybe I mislead you above  . Actually, my aim is to create a private chain with multiple bitcoin nodes which can connect themselves in WSL on my only one PC. When one of these nodes mine a  block and this guy  can broadcast it to other nodes  then other nodes begin to try to mine next block on my PC and this is my aim. 
By the way, the WSL is Windows Subsystem for Linux.
Hence, would you please tell me how to solve it? thank you.

**Comment by i5hi** [comment]
Can you provide some more detail on the configs you are using for each?

**Comment by i5hi** [comment]
And logs.

**Comment by i5hi** [comment]
Also, have you tried [bitcoin-multi-node](https://github.com/FreekPaans/bitcoin-multi-node-regtest) referenced in the stack exchange thread?

**Comment by prayank23** [comment]
> Hello, I hava only one pc and I make the bitcoin in wsl on my pc.

I am assuming you are trying to run multiple nodes on Windows

> I just want to create multiple bitcoin nodes in my pc. I have read this but failed too.
So would you please tell me how to solve it? thank you.

Follow the below steps:

1. Create two directories (Node1 and Node2) and `bitcoin.conf` files in D: and E:

   _D:\Node1\bitcoin.conf_
   ```
     
   regtest.rpcport=18222
   rpcuser=user1
   rpcpassword=password1
   ```
   _E:\Node2\bitcoin.conf_
   ```
      
   regtest.rpcport=18666
   rpcuser=user2
   rpcpassword=password2
   ```

2. Once you run `make install DESTDIR=/mnt/c/workspace/bitcoin` mentioned in [doc/build-windows.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md), it will save the binaries in `C:\workspace\bitcoin\bin\`
3. Open 2 PowerShell sessions and run the below commands:

   ```
   cd "C:\workspace\bitcoin\bin\"
   .\bitcoind.exe -regtest=1 -port=18333 -rpcport=18222 -datadir="D:\Node1\" -conf="D:\Node1\bitcoin.conf"
   ```
   ```   
   cd "C:\workspace\bitcoin\bin\"
   .\bitcoind.exe -regtest=1 -port=18777 -rpcport=18666 -datadir="E:\Node2\" -conf="E:\Node2\bitcoin.conf"
   ```
4. Open a third PowerShell session and you can use `bitcoin-cli` to run any RPC for Node 1 & Node 2:

   
![image](https://user-images.githubusercontent.com/13405205/129726013-cde81e50-3629-4b0c-a372-dd5d5d363f5d.png)

**Comment by jiebanghan** [comment]
I am so sorry maybe I mislead you above . Actually, my aim is to create a private chain with multiple bitcoin nodes which can connect themselves in WSL on my only one PC. When one of these nodes mine a block and this guy can broadcast it to other nodes then other nodes begin to try to mine next block on my PC and this is my aim.
By the way, the WSL is Windows Subsystem for Linux.
Hence, would you please tell me how to solve it? thank you.

**Comment by MarcoFalke** [comment]
You can use `-connect=localhost:18666` (with the correct port of the running node) to connect the nodes. I presume that the `addnode` RPC would also work. Finally, you can look into the functional test, which also setup nodes and connect them.
