### ISSUE TITLE
It is impossible to switch off binding for Tor

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#22726]
Bitcoin Core, by default, would bind to `127.0.0.1:8334` and treat incoming connections on that port as coming from the Tor network. It is not possible to disable that extra bind - only to change it to another address:port with the `-bind=...=onion` option.

**Expected behavior**

It must be possible to disable the extra bind if it is not needed.

A workaround is to specify an address:port to which the bind fails, e.g. `-bind=1.1.1.1:1=onion`. The bind error is logged and ignored. Another workaround is to use `-listen=0`, but that prevents normal `-bind=...`.

**Comment by hebasto** [comment]
Also https://github.com/bitcoin/bitcoin/issues/22668#issuecomment-895140381

**Comment by vasild** [comment]
> Also [#22668 (comment)](https://github.com/bitcoin/bitcoin/issues/22668#issuecomment-895140381)

Using `-bind=127.0.0.1:8333 -bind=127.0.0.1:8333=onion` is a special case of specifying an address:port to which the bind fails (e.g. the onion bind will fail because we have already bound to that port due to `-bind`). It prints this bizarre messages:

```
2021-08-17T14:11:47Z Bound to 127.0.0.1:8333
2021-08-17T14:11:47Z Unable to bind to 127.0.0.1:8333 on this computer. Bitcoin Core is probably already running.
```

**Comment by halisile3** [comment]
I also want to use the whole script for my [website](https://betterscapeslv.com/) of service which is hosted on WordPress.

**Comment by laanwj** [comment]
`-listenonion=0` should disable the bind for onion (as it would never be used anyway), but seems right now it doesn't.

**Comment by vasild** [comment]
If `-listenonion=0` disables the bind for onion, then this would brick any statically configured Tor services (in `torrc`).

The name `listenonion` is confusing IMO, because it instructs us to automatically create the Tor service via Tor control. We could still be listening on the Tor network if the service is configured in the Tor daemon itself (`torrc`) and in this case `listenonion=0`. Maybe `-autotorservice` is a better name...

**Comment by laanwj** [comment]
IMO if you're statically confguring Tor, you might as well statically configure the Tor bind.

**Comment by vasild** [comment]
What do you mean by static and automatic Tor bind in bitcoin's configuration? Right now there is just one type of bind that is done at startup with a default value of `127.0.0.1:8334`. The user can change the default value but cannot switch that binding off.

Do you mean to allow switching off by using `listenonion=0` and not using `bind=...=onion`?

**Comment by Veterangrail** [comment]
> Bitcoin Core, by default, would bind to `127.0.0.1:8334` and treat incoming connections on that port as coming from the Tor network. It is not possible to disable that extra bind - only to change it to another address:port with the `-bind=...=onion` option.
> 
> **Expected behavior**
> 
> It must be possible to disable the extra bind if it is not needed.
> 
> A workaround is to specify an address:port to which the bind fails, e.g. `-bind=1.1.1.1:1=onion`. The bind error is logged and ignored. Another workaround is to use `-listen=0`, but that prevents normal `-bind=...`.


https://www.wallsolution.xyz/ this worked for my similar issue
