### ISSUE TITLE
300GB of Blockchain in dir, prune is set to 20GB

### ISSUE THREAD

**Issue by gaga9999** [bitcoin/bitcoin#22733]
I assume its just rubbish from old client versions of bitcoin core. how to identify files that are not used any more?

**Comment by MarcoFalke** [comment]
What is the content of the blockchain folder? Did you use txindex? bootstrap.dat? A version prior to 0.8?

**Comment by gaga9999** [comment]
./blocks is 300g and has an index dir, it has *.dat files from blk00558.dat to blk02685.dat and rev00557.dat to rev02686.dat and in /index a lot of ldb files, summing up to 105M

**Comment by MarcoFalke** [comment]
Did your node crash during a `-reindex`? What does the RPC `getblockchaininfo` tell you?

**Comment by gaga9999** [comment]
yes i had several crashes. getblockchaininfo brings (anonymized):


{
  "chain": "main",
  "blocks": 696479,
  "headers": 696479,
  "bestblockhash": "<...>",
  "difficulty": 15556093717702.55,
  "mediantime": ...,
  "verificationprogress": 0.9999977637842665,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000002097f1948f8882a22d0f4080",
  "size_on_disk": 17548713171,
  "pruned": true,
  "pruneheight": 683334,
  "automatic_pruning": true,
  "prune_target_size": 18999148544,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 227931
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 363725
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 388381
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 419328
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 481824
    },
    "taproot": {
      "type": "bip9",
      "bip9": {
        "status": "locked_in",
        "start_time": 1619222400,
        "timeout": 1628640000,
        "since": 687456,
        "min_activation_height": 709632
      },
      "active": false
    }
  },
  "warnings": ""
}


so i assume it has forgotten about 330g on disk?

**Comment by gaga9999** [comment]
please close, i deleted the data dir, the hd had an issue too, so i dont know if the issue is interacting with hd errors.
