### ISSUE TITLE
Bitcoin Core doesn't respond.

### ISSUE THREAD

**Issue by Loopite** [bitcoin/bitcoin#22745]
When I'm synchronizing the blockchain, the bitcoin core doesn't respond. CPU Temperature is low (62°C) and it used at 2%. My memory is used at 22% (I run other software on my PC).

**Expected behavior**

Nothing, I just would the software works. I would the node doesn't stuck.

**Actual behavior**
A low opacity applicated in all bitcoin core Qt (When a software doesn't respond). My mouse is loading. I can't do anything. Except close the software.

**To reproduce**
Idk, seriously it's realy strange...

Open the bitcoin core, and wait a connection to a pool is done (Wait when the state is "Synchronizing...").

**System information**

I'm using the Bitcoin Core version v0.21.1. I downloaded the software on this page for my OS (64bits) : https://bitcoin.org/en/download (windows). 

I'm using Windows 10 Pro (64bits). I've a Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz and 32 Go RAM (recently bought 2 months ago). For the disk, I've put the blockchain and all files onto my HDD 4 To (SEGATE) disk.

It's a Bitcoin's GUI problem. It doesn't repond. I've the latest windows 10 version.

//

https://pastebin.com/HjjvdxuY (EXPIRATION IN 1 WEEK).

**Comment by hebasto** [comment]
> It's a Bitcoin's GUI problem.

Suggesting to move this issue into the dedicated repo: https://github.com/bitcoin-core/gui/issues.

**Comment by hebasto** [comment]
> For the disk, I've put the blockchain and all files onto my HDD 4 To (SEGATE) disk.

Which interface is it connected via?

> Open the bitcoin core, and wait a connection to a pool is done (Wait when the state is "Synchronizing...").

If the GUI freezes each time in the same moment, could you provide a screenshot?

**Comment by Loopite** [comment]
Hi, sorry for the wait...
This is the screenshot of the problem which you asked. I've turned my bitcoin's language to french.
![image](https://user-images.githubusercontent.com/70860774/130196394-6e452fb3-9243-4c9e-a401-3788d4267e1f.png)

Otherwise, my disk of 4 To Seagate is connected to my alimentation (Pool 750 Watts Gold) in S-ATA.

**Comment by bitcoin-public-domain** [comment]
Very likely this is an IO. He uses a 4TB HDD. Pretty common issue, especially when sync it to internal drives while those drives also in use. External **SSD** are highly recommended.

**Comment by bitcoin-public-domain** [comment]
Very likely this is an IO. He uses an HDD. Pretty common issue, especially when sync it to internal drives while those drives also in use. External **SSD** are highly recommended.

**Comment by jarolrod** [comment]
Bitcoin Core can be quite a taxing application on the CPU, Storage, Memory, etc. The screenshot shows an application that is not responding most likely due to an issue with your computer itself and not `bitcoin-qt`.

**Comment by hebasto** [comment]
@Loopite 
> I'm using the Bitcoin Core version v0.21.1.

Does this happen to v22.0? If so, please provide your `debug.log` file.

And again:

> > It's a Bitcoin's GUI problem.
> 
> Suggesting to move this issue into the dedicated repo: https://github.com/bitcoin-core/gui/issues.

**Comment by fanquake** [comment]
Closing this in favour of #17145 / opening an issue in the GUI repo.
