### ISSUE TITLE
Script verification threads are idle during IBD

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#22743]
System: ODROID-HC1, ARM 32-bit, Armbian 21.05.8 Focal
Client [v22.0rc2](https://bitcoincore.org/bin/bitcoin-core-22.0/test.rc2/arm-linux-gnueabihf/bitcoin-22.0rc2-arm-linux-gnueabihf.tar.gz):
```
$ bitcoind -version
Bitcoin Core version v22.0.0-g873fbc745d037ad43570f81e58334c397bc95477
```

Started IBD from scratch (with `txindex=1`), now synced up to height ~510000.

According to data provided by `htop` tool, all additional script verification threads were idle since IBD started:

![Screenshot from 2021-08-19 12-01-05](https://user-images.githubusercontent.com/32963518/130040671-af0dd7f3-1ab1-4fbe-8157-c54ee5a15e70.png)

Is such behavior expected?

**Comment by MarcoFalke** [comment]
What is `grep assumevalid ~/.bitcoin/debug.log`?

**Comment by hebasto** [comment]
Of course! :man_facepalming: 

```
...
2021-08-16T13:00:55Z Assuming ancestors of block 00000000000000000008a89e854d57e5667df88f1cdef6fde2fbca1de5b639ad have valid signatures.
...
```

Nothing to do until block height 691719 :)
