### ISSUE TITLE
Setting minrelaytxfee to 1/10th of the default gives an error that it is "too high".

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#22756]
Setting minrelaytxfee=100 in bitcoin.conf gives the following error on start up:-

![image](https://user-images.githubusercontent.com/1530283/130250567-34f8e6f1-c604-46d0-9112-9a3ad5c100ef.png)

Not sure how setting it to LOWER than the default can cause a "too high" error.

**Comment by MarcoFalke** [comment]
100 BTC/kvB seems high

**Comment by rebroad** [comment]
> 100 BTC/kvB seems high

but the default is 1000 - and this surely does not mean 1000 BTC/kvB

**Comment by prayank23** [comment]
default value for `minrelaytxfee` is 0.00001

**Comment by prayank23** [comment]
```
minrelaytxfee is FormatMoney(DEFAULT_MIN_RELAY_TX_FEE))
```

https://github.com/bitcoin/bitcoin/blob/e9d6eb1b8071805cec1cc4e1352a13a7adc55ca8/src/init.cpp#L530

```
DEFAULT_MIN_RELAY_TX_FEE is 1000
```

https://github.com/bitcoin/bitcoin/blob/e9d6eb1b8071805cec1cc4e1352a13a7adc55ca8/src/validation.h#L63

```
FormatMoney(1000) is 0.00001
```

https://github.com/bitcoin/bitcoin/blob/e9d6eb1b8071805cec1cc4e1352a13a7adc55ca8/src/util/moneystr.cpp#L12

```
COIN = 100000000

quotient = 0
remainder = 1000

%08d = 00001000
%d = 0

Before trim = 0.00001000

After trim = 0.00001
```

**Comment by jonatack** [comment]
Right, the default is 0.0001 BTC/kvB
```
$ ./src/bitcoind -h | grep -A2 minrelay
  -minrelaytxfee=<amt>
       Fees (in BTC/kvB) smaller than this are considered zero fee for
       relaying, mining and transaction creation (default: 0.00001)
```
