### ISSUE TITLE
how to quicken the make process after modifing the codes?

### ISSUE THREAD

**Issue by jiebanghan** [bitcoin/bitcoin#22752]
Hello, I am just learning the bitcoin codes of version bitcoin-0.20. 
So I compiled the codes for a very long time to generate the bitcoind and so on.
After a period of learning , I want to modify some codes in order to verify some ideas. 
By the way , I run the bitcoin on my WSL of the windows10 . However, I found the makefile period is a very long time despite I only modify  one sentence codes. 
Hence, would you please tell me how to quicken the make process after modifing the bitcoin codes?
Thank you very much.

**Comment by fanquake** [comment]
Install and use [`ccache`](https://ccache.dev/). Pass -jX to `make`. Where X is the number of threads you want to use.

**Comment by hebasto** [comment]
`sudo apt install ccache`, then re-configure and make again.

Details: https://github.com/bitcoin/bitcoin/blob/master/doc/productivity.md#cache-compilations-with-ccache

**Comment by jiebanghan** [comment]
Thank you very much.
