### ISSUE TITLE
Redundant code inside validation.cpp

### ISSUE THREAD

**Issue by janus** [bitcoin/bitcoin#22761]
This is not an issue at all. But inside  `validation.cpp` some code line might need some clean up. Second `block.vtx.empty()` is not needed.  Check the code below.

```
// Size limits
    if (block.vtx.empty() || block.vtx.size() * WITNESS_SCALE_FACTOR > MAX_BLOCK_WEIGHT || ::GetSerializeSize(block, PROTOCOL_VERSION | SERIALIZE_TRANSACTION_NO_WITNESS) * WITNESS_SCALE_FACTOR > MAX_BLOCK_WEIGHT)
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "bad-blk-length", "size limits failed");

    // First transaction must be coinbase, the rest must not be
    if (block.vtx.empty() || !block.vtx[0]->IsCoinBase())
```

**Comment by jadijadi** [comment]
It seems the 2nd block.vtx.empty() is not needed. May I send a PR after fixing this and reviewing the file for other duplicates (and fixing them if any)?

**Comment by janus** [comment]
@jadijadi I found this issue, it would be great if I send the PR. However,  I would like to get involved in the code base .

**Comment by jadijadi** [comment]
> @jadijadi I found this issue, it would be great if I send the PR. However, I would like to get involved in the code base .

Yes sure! Please do. I thought you are not going to and just reporting it.

**Comment by fanquake** [comment]
@janus feel free to open a PR. In general, we don't need issues opened for things like this.

**Comment by janus** [comment]
> @janus feel free to open a PR. In general, we don't need issues opened for things like this.

@fanquake  I won't report stuff like this again.
