### ISSUE TITLE
autogen.sh fail because of pkg_config

### ISSUE THREAD

**Issue by soha1410** [bitcoin/bitcoin#22771]
Hi,  I wanna build bitcoin core on mac Os Big Sur.
I installed every dependency with brew but the ./autogen.sh generate this error .

build-aux/m4/ax_pthread.m4:89: AX_PTHREAD is expanded from...
configure.ac:811: the top level
configure.ac:15: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:261: error: possibly undefined macro: AC_DEFINE
configure.ac:653: error: possibly undefined macro: AC_MSG_WARN
autoreconf: error: /opt/local/bin/autoconf failed with exit status: 1

the actual error is for pkg_config not found . but I installed it .
appreciate any help.

**Comment by fanquake** [comment]
There's not much we can do here. Those errors mean that `pkg-config` is not available. Ensure that it is, and try re-running autogen.sh.

**Comment by hebasto** [comment]
@soha1410 
> the actual error is for pkg_config not found . but I installed it .

Via Homebrew?

What is output of the `which pkg-config` command in your terminal?
If it is empty, verify the `PATH` environment variable, to ensure it includes the path to `pkg-config` binary.

**Comment by soha1410** [comment]
> @soha1410
> 
> > the actual error is for pkg_config not found . but I installed it .
> 
> Via Homebrew?
> 
> What is output of the `which pkg-config` command in your terminal?
> If it is empty, verify the `PATH` environment variable, to ensure it includes the path to `pkg-config` binary.

which pkg-config
/usr/local/bin/pkg-config

**Comment by hebasto** [comment]
What is output of `printenv PATH` command?

Could you try to start from the clean repo using `git clean -xdff`?

**Comment by soha1410** [comment]
> Could you try to start from the clean repo using `git clean -xdff`?

I try that too , no success.

**Comment by fanquake** [comment]
I'm going to close this for now. Without more debugging information, there's not really anything we can do here. This is almost certainly an issue with your local environment. Can reopen if we get more info.
