### ISSUE TITLE
bitcoin-qt does not load bootstrap.dat if blocks are already there in /blocks, --loadblock=<dirto/bootstrap.dat> needed

### ISSUE THREAD

**Issue by gaga9999** [bitcoin/bitcoin#22773]
i start bitcoin core bitcoin-qt and it starts to download blocks. i end the program. copy bootstrap.dat to the data dir. startup. it does not proces blocks from disks but continues to download blockchain. only when i use the startup parameter --locadblock it does process blocks from disk.

**Comment by achow101** [comment]
bootstrap.dat is an outdated method of syncing which is slower (overall, as in time it takes to download and then load it) than the normal sync process. The autoloading behavior was removed intentionally, see #17044.
