### ISSUE TITLE
autogen.sh fails with message: macro 'AM_MAINTAINER_MODE' not found in library

### ISSUE THREAD

**Issue by fkrahe** [bitcoin/bitcoin#22785]
Running autogen.sh fails with message:

`configure.ac:49: warning: macro 'AM_MAINTAINER_MODE' not found in library
configure.ac:49: error: possibly undefined macro: AM_MAINTAINER_MODE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Expected behavior**

I expect the autogen to finish without errors

**Actual behavior**

autoreconf, called by autogen.sh exits with status 1

**To reproduce**

Checkout branch 0.21 on a Raspberry Pi 3 with Raspian OS (Debian) and call autogen.sh

**System information**

* Bitcoin Core branch 0.21 from github, self compiled
* Raspberry Pi 3 Model B
* Raspian OS: 2021-05-07-raspios-buster-armhf.img

I'm using shell to compile.

pkg-config (0.29-6)
autoconf (GNU Autoconf) 2.69

`
pi@raspberrypi3b:~/bitcoin $ ./autogen.sh
configure.ac:49: warning: macro 'AM_MAINTAINER_MODE' not found in library
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:45: installing 'build-aux/compile'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:15: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:49: warning: macro 'AM_MAINTAINER_MODE' not found in library
configure.ac:49: error: possibly undefined macro: AM_MAINTAINER_MODE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Comment by fkrahe** [comment]
**My current automake version is: automake-1.16**

My apt search show versions automake-1.15, automake1.11 and lesser versions.

**So I tried version automake-1.15**

sudo apt search automake
sudo apt install automake-1.15
sudo update-alternatives --config automake

./autogen.sh Failed with message

`
...
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:17: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:240: error: possibly undefined macro: AC_DEFINE
configure.ac:615: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Then I tried version automake-1.11**

sudo apt install automake1.11
sudo update-alternatives --config automake

.autogen.sh failed with message

`
pi@21m:~/bitcoin $ ./autogen.sh 
Prototype after '@' for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Illegal character in prototype for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Prototype mismatch: sub main::list_compare (address@hidden@) vs (\@\@) at /usr/bin/aclocal line 340.
Prototype after '@' for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Illegal character in prototype for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Prototype mismatch: sub main::list_compare (address@hidden@) vs (\@\@) at /usr/bin/aclocal line 340.
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
Prototype after '@' for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Illegal character in prototype for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Prototype mismatch: sub main::list_compare (address@hidden@) vs (\@\@) at /usr/bin/aclocal line 340.
configure.ac:28: installing `build-aux/missing'
Makefile.am: installing `build-aux/depcomp'
Prototype after '@' for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Illegal character in prototype for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Prototype mismatch: sub main::list_compare (address@hidden@) vs (\@\@) at /usr/bin/aclocal line 340.
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
Prototype after '@' for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Illegal character in prototype for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Prototype mismatch: sub main::list_compare (address@hidden@) vs (\@\@) at /usr/bin/aclocal line 340.
configure.ac:27: installing `build-aux/compile'
configure.ac:9: installing `build-aux/missing'
Makefile.am: installing `build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
Prototype after '@' for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Illegal character in prototype for main::list_compare : address@hidden@ at /usr/bin/aclocal line 162.
Prototype mismatch: sub main::list_compare (address@hidden@) vs (\@\@) at /usr/bin/aclocal line 340.
configure.ac:17: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:240: error: possibly undefined macro: AC_DEFINE
configure.ac:615: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Comment by laanwj** [comment]
Very strange. Automake 1.16.2 and autoconf 2.69 works fine here. `AM_MAINTAINER_MODE` is a very old setting that has been in automake for a long time. It has been in our `configure.ac` file since the beginning of the autotools build system in 2013, and as far as I know, never tripped anyone else.

Do you have all the [suggested build dependencies](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#ubuntu--debian) installed?

**Comment by fanquake** [comment]
> Then I tried version automake-1.11

We require automake 1.13 or later.

> Do you have all the suggested build dependencies installed?

Can you confirm this?

I'm going to close this for now. If we get some new information, maybe we can reopen and try and debug further, but this is almost certainly seems like an issue with your local environment.
