### ISSUE TITLE
combinerawtransaction fails to properly combine transactions containing taproot inputs

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#22784]
If `combinerawtransaction` is given a transaction containing completed taproot spends, it will drop the signatures from those inputs. For 0.21, `combinerawtransaction` would actually cause an assertion failure - this was fixed by #21330. This is not a regression as `combinerawtransaction` never worked with txs with taproot inputs anyways. AFAICT, either taproot was not yet implemented, it hit an assertion, or it is broken.

In any case, I don't think this is particularly important to fix since the recommended workflow is to use PSBTs. But I am opening this issue to document this in case someone does come across this bug.

Originally found by @roconnor-blockstream

**Comment by sipa** [comment]
At least the assertion fail should be fixed, I think. Backport #21330 to 0.21?

**Comment by jaysonmald35** [comment]
Thank u
