### ISSUE TITLE
make: CI Win64 build

### ISSUE THREAD

**Issue by kiminuo** [bitcoin/bitcoin#22854]
Hi,

I executed the following command:

```bash
MAKEJOBS="-j15" FILE_ENV="./ci/test/00_setup_env_win64.sh" ./ci/test_run_all.sh
```

and I got:

```
[...]
/usr/bin/x86_64-w64-mingw32-ar cr leveldb/libmemenv.a leveldb/helpers/memenv/libmemenv_a-memenv.o 
/usr/bin/x86_64-w64-mingw32-ranlib leveldb/libmemenv.a
make  -C secp256k1 libsecp256k1.la
make[3]: Entering directory '/home/user/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-w64-mingw32/src/secp256k1'
x86_64-w64-mingw32-gcc -O2  -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wcast-align=strict -fvisibility=hidden  -pipe -O2  -L/home/user/bitcoin/bitcoin/depends/x86_64-w64-mingw32/lib  gen_context.o -o gen_context
./gen_context
/bin/bash: ./gen_context: No such file or directory
make[3]: Leaving directory '/home/user/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-w64-mingw32/src/secp256k1'
make[3]: *** [Makefile:1785: src/ecmult_static_context.h] Error 127
make[2]: *** [Makefile:18108: secp256k1/libsecp256k1.la] Error 2
make[2]: Leaving directory '/home/user/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-w64-mingw32/src'
make[1]: *** [Makefile:16271: all-recursive] Error 1
make[1]: Leaving directory '/home/user/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-w64-mingw32/src'
make: *** [Makefile:823: all-recursive] Error 1
```

Am I doing something wrong or is something broken? Note the `/bin/bash: ./gen_context: No such file or directory` error.

For debugging purposes I did list the following directory:
```
ci/scratch/build/bitcoin-x86_64-w64-mingw32/src/secp256k1# ls -l
total 1732
-rw-rw-r-- 1 1000 1000   1057 Aug 28 07:26 COPYING
-rw-r--r-- 1 root root  74645 Aug 31 14:01 Makefile
-rw-rw-r-- 1 1000 1000   5426 Aug 28 07:26 Makefile.am
-rw-r--r-- 1 root root  79831 Aug 31 14:00 Makefile.in
-rw-r--r-- 1 root root  53198 Aug 31 14:00 aclocal.m4
-rwxrwxr-x 1 1000 1000     47 Aug 28 07:26 autogen.sh
drwxr-xr-x 3 root root   4096 Aug 31 14:01 build-aux
-rw-r--r-- 1 root root  66027 Aug 31 14:01 config.log
-rwxr-xr-x 1 root root  63237 Aug 31 14:01 config.status
-rwxr-xr-x 1 root root 531431 Aug 31 14:00 configure
-rw-rw-r-- 1 1000 1000  20668 Aug 28 07:26 configure.ac
drwxr-xr-x 2 root root   4096 Aug 31 14:01 contrib
-rwxr-xr-x 1 root root 397219 Aug 31 14:10 gen_context.exe
-rw-r--r-- 1 root root  82253 Aug 31 14:02 gen_context.o
drwxr-xr-x 2 root root   4096 Aug 31 14:01 include
-rw-r--r-- 1 root root    414 Aug 31 14:01 libsecp256k1.pc
-rw-rw-r-- 1 1000 1000    327 Aug 28 07:26 libsecp256k1.pc.in
-rwxr-xr-x 1 root root 343214 Aug 31 14:01 libtool
drwxr-xr-x 5 root root   4096 Aug 31 14:02 src
```

And one can see that `gen_context.exe` exists but not `gen_context`, so that makes me think that maybe there is some issue with `$(BUILD_EXEEXT)`.

Do you encounter the same error? Any idea how to fix it?

Environment:

* Ubuntu 20.04
* git commit: 33707a2a

**Comment by fanquake** [comment]
This is a known issue with libsecp256k1: https://github.com/bitcoin-core/secp256k1/issues/923#issuecomment-870162411.

**Comment by MarcoFalke** [comment]
Does this happen in a clean git dir? Focal is also used in the CI, but it hasn't hit this error yet, so I wonder what the difference here is.

**Comment by kiminuo** [comment]
@MarcoFalke Yes, I did try `git clean -xdf` and it did not help me.

>  Focal is also used in the CI, but it hasn't hit this error yet, so I wonder what the difference here is.

Same here. That's why I'm interested whether others see the error too or whether it's just me.

**Comment by hebasto** [comment]
Tested the recent master (16ccb3a1cd9125eb24a5b45a98099ff98660767a) on Linux Mint 20.2 (x86_64, Ubuntu 20.04 codebase):

```
$ make distclean
$ MAKEJOBS="-j9" FILE_ENV="./ci/test/00_setup_env_win64.sh" ./ci/test_run_all.sh
```

No errors.

Did another test with the clean repo. No errors.

**Comment by kiminuo** [comment]
I have tried again without any luck (16ccb3a1). Ubuntu

**Comment by fanquake** [comment]
The cause of this issue is having a machine with [`binfmt_misc`](https://access.redhat.com/solutions/1985633) enabled, and also have wine-binfmt installed. When we build configure gets confused, and thinks it isn't cross-compiling, when it is. It takes a path where `$(EXEEXT)` doesn't end up set, and thus tries to run `gen_context` when the executable is actually `gen_context.exe`. This is still an issue with latest upstream, however there are some PRs open that may fixup this problem.

For the moment, you could work around by disabling `binfmt_misc`, or uninstalling `wine-binfmt`.

**Comment by hebasto** [comment]
@kiminuo 

Would you mind testing #23722?

**Comment by kiminuo** [comment]
@hebasto 

Running `MAKEJOBS="-j15" FILE_ENV="./ci/test/00_setup_env_win64.sh" ./ci/test_run_all.sh` on Ubuntu 21.10 leads to the following compilation:

[23722.log](https://github.com/bitcoin/bitcoin/files/7683171/23722.log)

Unfortunately, it fails to build for me. 

(I can test more if you like.)

**Comment by fanquake** [comment]
> Unfortunately, it fails to build for me.

> x86_64-w64-mingw32-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.

That just looks like you've run out of memory.

**Comment by kiminuo** [comment]
> That just looks like you've run out of memory.

Weird, but seems so.

New log: [23722.log](https://github.com/bitcoin/bitcoin/files/7683509/23722.log)

**Comment by hebasto** [comment]
> > That just looks like you've run out of memory.
> 
> Weird, but it seems so.
> 
> New log: [23722.log](https://github.com/bitcoin/bitcoin/files/7683509/23722.log)

hmm,
```
checking for QWindowsIntegrationPlugin (-lqwindows)... no
configure: WARNING: QWindowsIntegrationPlugin not found.; bitcoin-qt frontend will not be built
```

**Comment by hebasto** [comment]
@kiminuo 

> New log: [23722.log](https://github.com/bitcoin/bitcoin/files/7683509/23722.log)

Have you `config.log` available?

**Comment by kiminuo** [comment]
I have these:

[bitcoin-x86_64-w64-mingw32_src_secp256k1_config.log](https://github.com/bitcoin/bitcoin/files/7685184/bitcoin-x86_64-w64-mingw32_src_secp
[src_secp256k1_config.log](https://github.com/bitcoin/bitcoin/files/7685186/src_secp256k1_config.log)
[bitcoin-x86_64-w64-mingw32_config.log](https://github.com/bitcoin/bitcoin/files/7685187/bitcoin-x86_64-w64-mingw32_config.log)
256k1_config.log)
[build_config.log](https://github.com/bitcoin/bitcoin/files/7685185/build_config.log)

**Comment by kiminuo** [comment]
[bitcoin-x86_64-w64-mingw32_config.log](https://github.com/bitcoin/bitcoin/files/7685191/bitcoin-x86_64-w64-mingw32_config.log)
[bitcoin-x86_64-w64-mingw32_src_secp256k1_config.log](https://github.com/bitcoin/bitcoin/files/7685192/bitcoin-x86_64-w64-mingw32_src_secp256k1_config.log)
[build_config.log](https://github.com/bitcoin/bitcoin/files/7685193/build_config.log)
[src_secp256k1_config.log](https://github.com/bitcoin/bitcoin/files/7685194/src_secp256k1_config.log)
