### ISSUE TITLE
Make ParseScript and friends threadsafe

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#22869]
Currently Parsescript and others build a map as a static and it's not threadsafe -- these fields should be behind a mutex or initialized at compile time or something else.

**Comment by MarcoFalke** [comment]
I don't understand this issue. I tried `git grep --function-context  'ParseScript('|grep static` and didn't find anything.

**Comment by kristapsk** [comment]
@MarcoFalke I found this one:

https://github.com/bitcoin/bitcoin/blob/458a345b0590fd2fa04c7d8d70beb8d57e34bbc8/src/core_read.cpp#L27

But as it's just a cache, why not just change it to `thread_local`?

**Comment by MarcoFalke** [comment]
That one seems to be addressed in #22875 already?

So I think this can be closed.

Also, in the future it would be good to use the good-first-issue template for good first issues.

**Comment by JeremyRubin** [comment]
sorry for the confusion here
