### ISSUE TITLE
bitcoin-cli -netinfo displays verison number of bitcoin-cli, not the running bitcoind

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#22873]
Running bitcoind version `Bitcoin Core version v22.99.0-952c37a31c39`

when I used `bitcoin-cli -netinfo` to check my network stats it displays

```
Bitcoin Core v22.0rc3 - 70016/Satoshi:22.99.0/
```

which is the version of my installed bitcoin-cli, not the running bitcoind

**Comment by benthecarman** [comment]
Doesn't seem like this might be easily fixable, I don't see a rpc command that returns the running bitcoind version

**Comment by jonatack** [comment]
Godd point. So, `-netinfo` uses the version returned by `getnetworkinfo` for the version check

```cpp
        const UniValue& networkinfo{batch[ID_NETWORKINFO]["result"]};
        if (networkinfo["version"].get_int() < 209900) {
            throw std::runtime_error("-netinfo requires bitcoind server to be running v0.21.0 and up");
        }
```

am now building 22.0rc3 from source ATM to look at updating the `-netinfo` header to return both client and server versions
```diff
-        std::string result{strprintf("%s %s%s - %i%s\n\n", PACKAGE_NAME, FormatFullVersion(), ChainToString(), networkinfo["protocolversion"].get_int(), networkinfo["subversion"].get_str())};
+        std::string result{strprintf("%s %s%s - %i%s\n\n", PACKAGE_NAME, networkinfo["version"].get_int(), ChainToString(), networkinfo["protocolversion"].get_int(), networkinfo["subversion"].get_str())};
```

**Comment by jonatack** [comment]
The server check functions as expected.

> ```
> Bitcoin Core v22.0rc3 - 70016/Satoshi:22.99.0/
> ```

The server version is reported in `70016/Satoshi:22.99.0/`. Would it be enough to add "client" and "server" to clarify? for example:
```
Bitcoin Core client v22.0rc3 - server 70016/Satoshi:22.99.0/
```

**Comment by jonatack** [comment]
#22894 clarifies that both the client and the server versions are provided.
