### ISSUE TITLE
QUESTION: relevance of the published `bitcoind` version string? Can it be removed?

### ISSUE THREAD

**Issue by xanoni** [bitcoin/bitcoin#22933]
I noticed that many node operators customize the version strings of their `bitoind`, usually by adding their nicknames after the `CLIENT_VERSION_BUILD`. This typically looks something like `70016/Satoshi:22.99.0(myalias)/` or `70016/Satoshi:22.99.0/myalias/`.

Given there are also other ways to personalize a node (e.g., by generating a vanity Tor / I2P address), I'm wondering if changing the version string is safe to do?

1) Is adding an alias compliant with the specs?
2) Does `bitcoind` check the version strings of its peers to decide whom to communicate with? If yes, which parts specifically are checked?
3) If not, is it safe to remove the version string completely for privacy/security reasons? I see one node that just displays the protocol (`70016`), for example, and another one shows nothing at all.

_(This is not a feature request, but I didn't know an easier place to find people who know the Bitcoin Core codebase ...)_

**Comment by prayank23** [comment]
> Is adding an alias compliant with the specs?

If this question is about following BIP, then I think yes it's implemented according to BIP 14.

There is a config option to add comments in User Agent string: [`uacomment`](https://github.com/bitcoin/bitcoin/blob/896649996bdaa80300fa20027a9789558233268d/src/init.cpp#L520)

According to this comment, fancy characters are removed from it: https://github.com/bitcoin/bitcoin/issues/15048#issuecomment-450345595 

Practicalswift had opened an issue to simplify UA string in which different parts of this string are shared: https://github.com/bitcoin/bitcoin/issues/21492#issuecomment-804174208

I agree with Marcofalke's comment here: https://github.com/bitcoin/bitcoin/issues/21492#issuecomment-804657428

> Given there are also other ways to personalize a node (e.g., by generating a vanity Tor / I2P address), I'm wondering if changing the version string is safe to do?

Such things affect privacy. For example if 3 people in this GitHub issue share their custom UA strings or vanity onion/i2p address:

1. Your privacy: everyone knows which node are you using and can spy on you.
2. Others privacy: if I have 8 out outbound connections, 2 are using UA strings shared in this issue, I can focus on other 6 for collecting information if I am not interested in spying on you. If UA strings were same or nothing extra added, I would have to assume all 8 are unknown users, collect, analyse more information.

Not sure about question 2 and 3. My guess is your node can connect to any version. Removing UA string completely might still affect few things.

**Comment by prayank23** [comment]
If looking in [shodan](https://www.shodan.io/search/facet?query=User-Agent%3A%2FSatoshi%2F+port%3A%228333%22&facet=product), most of the nodes are using 0.21.0 and 0.21.1. So best practice would be to use the same version node and don't use anything in `-uacomment`.

![image](https://user-images.githubusercontent.com/13405205/132754913-e9c21e24-4735-4807-9ed8-5670a01d246d.png)

**Comment by xanoni** [comment]
https://github.com/bitcoin/bitcoin/issues/21492#issuecomment-804584518

So based on this, the only reason why it's not dropped is "analytics"? I see the value of that, sure.

So far I have found no indication that deleting the version string or setting it to something absurd (like 13.33.7) causes any trouble.
