### ISSUE TITLE
Guide or notes

### ISSUE THREAD

**Issue by bitcoin-public-domain** [bitcoin/bitcoin#22945]
I noticed that some *-build.md in https://github.com/bitcoin/bitcoin/tree/master/doc called "Guide" while the Unix version "Notes"
In https://github.com/bitcoin/bitcoin/tree/master/doc#building however shows all of them as "Notes". 

I also noticed that https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md says: 
> This guide describes how to build bitcoind, command-line utilities, and GUI on macOS

Isn't that should say? : 
> This guide describes how to build Bitcoin Core on macOS

**Comment by MarcoFalke** [comment]
I think the docs are understandable in that regard at least, so I think there doesn't need to be a patch changing Notes to Guide or vice versa. Especially, there doesn't need to be an issue discussing the change. It didn't seem to attract any interest anyway so far.
