### ISSUE TITLE
Deployed on macOS 11 app fails to run on macOS 10.14.6

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#22963]
Steps to reproduce on master (7ecb309c4ed1bb9ae6b9a12cbb4f083328edc125):

1. On macOS 11 `make deploy`
2. Copy the resulted `Bitcoin-Core.dmg` to a macOS 10.14.6 system
3. Install it
4. Run it:
![Screenshot from 2021-09-13 19-29-06](https://user-images.githubusercontent.com/32963518/133125149-4fb31a52-f21f-40fa-8242-d26794e20d64.png)

**Comment by prayank23** [comment]
Weird error message:

"You have macOS **10.14.6**. The application requires macOS **10.14** or later"

Error should have 11 instead of 10.14 because 10.14.6 is obviously higher than 10.14

Is there any option in `make deploy` command to set the deployment target?

**Comment by jarolrod** [comment]
If you natively compile on macOS 12; at the configure stage, our `build os` is set to `darwin21.1.0`. Then we build and deploy. Is this executable expected to run on `darwin18`?

What you should do is run a depends build with a `darwin18` target and that executable is usable.

**Comment by jarolrod** [comment]
If you run `objdump -all-headers` on the built executable, I see:

```
platform macos
       sdk 11.3
     minos 11.3
```

**Comment by fanquake** [comment]
> Steps to reproduce on master (7ecb309):

Confusing error message aside, the most important point is missing here. Was this build done using depends or not?

I don't think it's unexpected that non-depends builds done on newer macOS versions wouldn't run on older versions. i.e when building macOS 11.x, ld64 is probably setting `platform_version` with a minimum required OS version of 11.0 or later.

If you look at the actual `Bitcoin-Qt` executable in the dmg, the min os is likely 11.0+.

**Comment by jarolrod** [comment]
@fanquake 
> "... Was this build done using depends or not?"

This was a native compile on macOS, non-depends build done by hebasto

> "If you look at the actual Bitcoin-Qt executable in the dmg, the min os is likely 11.0+."

Yep, that's correct. I pointed that out [here](https://github.com/bitcoin/bitcoin/issues/22963#issuecomment-918451702). The executable built natively on macOS 11 shouldn't be expected to run on 10.14
