### ISSUE TITLE
Unable to verify Bitcoin Core 22.0 with the latest SHASUM256.asc

### ISSUE THREAD

**Issue by flyingfaders** [bitcoin/bitcoin#22965]
Unable to verify Bitcoin Core 22.0 with the latest SHASUM256.asc when following the 'Verify your Download' guide from the bitcoincore.org website. It seems there's a formatting issue with the .asc file?

sha256sum --ignore-missing --check SHA256SUMS.asc
sha256sum: SHA256SUMS.asc: no properly formatted SHA256 checksum lines found

gpg --verify SHA256SUMS.asc
gpg: no signed data
gpg: can't hash datafile: No data

Tried verifying on both Arm Linux and MacOS, both throw the same error message.

**Comment by prusnak** [comment]
You need to download both SHA256SUMS and SHA256SUMS.asc.

Then to verify:

```
gpg --verify SHA256SUMS.asc
sha256sum --ignore-missing --check SHA256SUMS
```

**Comment by prusnak** [comment]
The instructions need to be adapted for 22.0 release which does not include hashes in asc file anymore.

You need to download both SHA256SUMS and SHA256SUMS.asc

Then:

```
gpg --verify SHA256SUMS.asc
sha256sum --ignore-missing --check SHA256SUMS
```

**Comment by davterra** [comment]
> The instructions need to be adapted for 22.0 release which does not include hashes in asc file anymore.
> 
> You need to download both `SHA256SUMS` and `SHA256SUMS.asc` and then:
> 
> ```
> gpg --verify SHA256SUMS.asc
> sha256sum --ignore-missing --check SHA256SUMS
> ```

Sorry if the answer is obvious, but I have SHA256SUMS.asc and I can't seem to find SHA256SUMS anywhere.

**Comment by flyingfaders** [comment]
You can find the `SHA256SUMS` file here: https://bitcoincore.org/bin/bitcoin-core-22.0/ @davterra

**Comment by davterra** [comment]
Yeah, should have been obvious. Thanks.

**Comment by blockskillally** [comment]
Err Cleartext_not_permited can't open page email link
