### ISSUE TITLE
R[v22.0] Font missing

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#22991]
Build [v22.0](https://github.com/bitcoin/bitcoin/tree/v22.0) on Fedora 34 with Berkley DB 4.8 (note Fedora people, despite newer versions being available Berkley DB 4.8 IS the standard as it is bug free and fully compatible.)it looks like the build is missing a font as the sizing is bad and in options, it gives the options of Embedded Roboto Mono or closest matching Source Code Pro that it does not use even when selected.

Also, the Berkley DB copyright/licence information is missing from About Bitcoin Core modal window.

The Berkley DB copyright/licence information has to be there all the places wherever it was before.

**Comment by fanquake** [comment]
As I said in my [last comment](https://github.com/bitcoin/bitcoin/issues/22990#issuecomment-920477460), this issue needs to be opened in a different repository: https://github.com/bitcoin-core/gui.

**Comment by Willtech** [comment]
Try and leave out the furbled buttons you do not wish to use.
![image](https://user-images.githubusercontent.com/1173622/133529560-cf7b0fed-b46c-4bd0-ac53-62beae09796a.png)
