### ISSUE TITLE
R[v22.0] Font missing

### ISSUE THREAD

**Issue by Willtech** [bitcoin/bitcoin#22990]
Build [v22.0](https://github.com/bitcoin/bitcoin/tree/v22.0) on Fedora 34 with Berkley DB 4.8 (note Fedora people, despite newer versions being available Berkley DB 4.8 IS the standard as it is bug free and fully compatible.)it looks like the build is missing a font as the sizing is bad and in options, it gives the options of Embedded Roboto Mono or closest matching Source Code Pro that it does not use even when selected.

Also, the Berkley DB copyright/licence information is missing from About Bitcoin Core modal window.

**Comment by Willtech** [comment]
The Berkley DB copyright/licence information has to be there wherever it was before.

**Comment by fanquake** [comment]
These both sound like GUI issues. Please open an issue on the GUI repo: https://github.com/bitcoin-core/gui.

**Comment by Willtech** [comment]
Sure, release issues, GUI issues..

**Comment by Willtech** [comment]
#22991 22991
