### ISSUE TITLE
Double-clicking bitcoin: URI link == duplicate Pay To's

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#2302]
I believe the correct behavior should be:

Second click on a URI that pays to address 'A' should remove the previous entry for A and add a new entry.

E.g. click on "Pay 2 BTC to XYZ", then click on "Pay 1 BTC to XYZ", the Send Coins should show the last one.

Click on "Pay 2 to XYZ", then click on "Pay 1 to VWX", Send Coins should show both recipients.

**Comment by laanwj** [comment]
Also vaguely related: #3266

**Comment by adamjonas** [comment]
This looks to have been closed by #17031.
