### ISSUE TITLE
Client receives and stores transactions while syncing

### ISSUE THREAD

**Issue by Belkaar** [bitcoin/bitcoin#2303]
My 0.8.0rc1 (self compiled from git tag) receives transactions from peers while syncing, which results in them beeing orphaned and the orphan-list filling up.

Suggestion: Do not request or handle incomming transaction while in initial sync or when the client knows its blockchain is old.
Also: Start connecting to peers only after every --loadblock entry has been processed

**Comment by laanwj** [comment]
This was implemented in #7164
