### ISSUE TITLE
Replace memset with memset_s

### ISSUE THREAD

**Issue by prayank23** [bitcoin/bitcoin#23034]
I was watching this video: https://www.youtube.com/watch?v=gHGMDFm2MVs in which it is suggested to use `memset_s()` to avoid any issues because of compiler optimizations.

![image](https://user-images.githubusercontent.com/13405205/133915878-da167d4e-99de-495a-91ed-8cfbee59c632.png)

Also explained here: https://stackoverflow.com/questions/56565539/memset-s-what-does-the-standard-mean-with-this-piece-of-text

It is used at lot of places: https://github.com/search?l=&q=memset+repo%3Abitcoin%2Fbitcoin&type=code

Should we replace it with `memset_s()` ?

**Comment by yesbox** [comment]
Bitcoin uses the memory_cleanse function in its stead.

**Comment by sipa** [comment]
The `memset_s` function is defined in C11. Bitcoin Core isn't written in C, but in C++. No C++ standard to date includes such a function.

Furthermore, it's an *optional* part of C11 which most compilers haven't implemented even; specifically, none of the compilers used for Bitcoin Core's release builds support it.
