### ISSUE TITLE
versioning format changed from 0.21.x to 22.0? 

### ISSUE THREAD

**Issue by petjal** [bitcoin/bitcoin#23040]
**Expected behavior**

expected version number more like 0.22.0, or a discussion about the versioning format change to 22.0

**Actual behavior**

see version 22.0

**To reproduce**

https://bitcoincore.org/en/releases/
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-22.0.md
https://bitcoincore.org/bin/

**System information**

 
22.0

**Comment by fanquake** [comment]
There was discussion. See #20223.
