### ISSUE TITLE
Auto-generate MSVC version information

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#23073]
Right now, bumping the version involves updating the version in two places:

- `configure.ac`
- `build_msvc/bitcoin_config.h` (in multiple places—see for example commit f277b1782c5aae0fab83e3d678189c150ae0f263)

I think it should be doable to parse the information from `configure.ac` in `msvc-autogen.py`, so that this is no longer something error-prone that has to be done manually.

If you do this, also update [the release process](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md).

#### Useful skills:

Python, MSVC

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by Ambarish07** [comment]
If nobody is on this, should I work on it?

**Comment by bugra44** [comment]
37i1vdSB4Na5SUSvMeBQd9jcgyd9cEF61Q

**Comment by beerzyp** [comment]
Can you assign me this issue?

**Comment by hebasto** [comment]
> Can you assign me this issue?

You do not need neither assignment nor permission. If you want to contribute, just submit a pull request.

And don't forget to follow our [Contributing Guide](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) :)

**Comment by Mdasgor** [comment]
f277b17
