### ISSUE TITLE
Handle disk-full more gracefully in functional tests

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#23099]
If you run the tests with too little disk space in  `/tmp` partition, e.g.
```bash
sudo mount -t tmpfs -o size=1M none /tmp
test/functional/test_runner.py
```
you get a huge log output with a lot of `-- Logging error --`, with the tests failing one by one, where it's not immediately clear why the tests are failing. It might be useful to exit immediately with a more specific message when even writing to the logs fails, and/or do an early check if the disk space need in the file system where the temporary files go can be estimated.

**Comment by katesalazar** [comment]
Beware some systems will auto start testing using /var/tmp/ if
they find /tmp/ completely filled up.

**Comment by laanwj** [comment]
That's also an idea. Though, could leave specifying an alternative up to the user. The thing I'm most afraid of here is that someone will end up in a wild goose chase to find what broke the tests and it turns out to be something simple as being out of disk space in `/tmp`.

**Comment by katesalazar** [comment]
[good first issue](https://github.com/bitcoin/bitcoin/labels/good%20first%20issue)

**Comment by katesalazar** [comment]
If anyone's needing this to be done urgently
and is willing to commit the necessary energy,
I'll be happy to let it go.
