### ISSUE TITLE
bitcoin-22.0-powerpc64le-linux-gnu tarball does not execute

### ISSUE THREAD

**Issue by flatcloud0b3** [bitcoin/bitcoin#23111]
Describe the issue

    I download the powerpc64le tarball, extract it and run bitcoind the same as I do with x86 and it doesnt run.

What behavior did you expect?

    I expected it to run.

What was the actual behavior (provide screenshots if the issue is GUI-related)?

    root@acde684805fd:~# ls
    bitcoin-22.0-powerpc64le-linux-gnu.tar.gz

    root@acde684805fd:~# tar -xzvf bitcoin-22.0-powerpc64le-linux-gnu.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt
    bitcoin-22.0/README.md
    bitcoin-22.0/bin/
    bitcoin-22.0/bin/bitcoin-cli
    bitcoin-22.0/bin/bitcoin-tx
    bitcoin-22.0/bin/bitcoin-util
    bitcoin-22.0/bin/bitcoin-wallet
    bitcoin-22.0/bin/bitcoind
    bitcoin-22.0/bin/test_bitcoin
    bitcoin-22.0/include/
    bitcoin-22.0/include/bitcoinconsensus.h
    bitcoin-22.0/lib/
    bitcoin-22.0/lib/libbitcoinconsensus.so
    bitcoin-22.0/lib/libbitcoinconsensus.so.0
    bitcoin-22.0/lib/libbitcoinconsensus.so.0.0.0
    bitcoin-22.0/share/
    bitcoin-22.0/share/man/
    bitcoin-22.0/share/man/man1/
    bitcoin-22.0/share/man/man1/bitcoin-cli.1
    bitcoin-22.0/share/man/man1/bitcoin-qt.1
    bitcoin-22.0/share/man/man1/bitcoin-tx.1
    bitcoin-22.0/share/man/man1/bitcoin-util.1
    bitcoin-22.0/share/man/man1/bitcoin-wallet.1
    bitcoin-22.0/share/man/man1/bitcoind.1
    
    root@acde684805fd:~# which bitcoind
    /usr/local/bin/bitcoind
    
    root@acde684805fd:~# bitcoind
    bash: /usr/local/bin/bitcoind: No such file or directory                       <-------------- ERROR !!
    
    root@acde684805fd:~# which bitcoin-cli
    /usr/local/bin/bitcoin-cli
    
    root@acde684805fd:~# bitcoin-cli getnetworkinfo
    bash: /usr/local/bin/bitcoin-cli: No such file or directory                    <--------------- ERROR !!
    
    root@acde684805fd:~#

What linux version ?

    root@acde684805fd:~# uname -a
    Linux acde684805fd 4.19.0-17-powerpc64le #1 SMP Debian 4.19.194-3 (2021-07-18) ppc64le GNU/Linux

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?

    https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0-powerpc64le-linux-gnu.tar.gz

What type of machine are you observing the error on (OS/CPU and disk type)?

    Headless Server running Debian Buster, 16 CPUs, NVMe Storage & too much RAM [ Talos™ II Secure Workstation by Raptor Computing Systems ]

GUI-related issue? What is your operating system and its version? If Linux, what is your desktop environment and graphical shell?

    GUI ? ? ? Nah . . .

**Comment by sipa** [comment]
If you want to be able to invoke the binaries, you need to install them in a standard PATH directory (/usr/bin etc).

If you just unpack, you need to invoke them by pathname (e.g. `./bitcoind`). This is true for all programs on Unix based systems.

**Comment by flatcloud0b3** [comment]
Tried that too, same error.
    
    root@a98891605b67:~# wget https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0-powerpc64le-linux-gnu.tar.gz
    
    --2021-09-27 18:47:11--  https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0-powerpc64le-linux-gnu.tar.gz
    Resolving bitcoincore.org (bitcoincore.org)... 198.251.83.116, 107.191.99.5
    Connecting to bitcoincore.org (bitcoincore.org)|198.251.83.116|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 38677732 (37M) [application/octet-stream]
    Saving to: 'bitcoin-22.0-powerpc64le-linux-gnu.tar.gz'

    bitcoin-22.0-powerpc64le-linux-gnu.tar.gz          100%[================================================================================================================>]  36.89M  2.41MB/s    in 28s     

    2021-09-27 18:47:40 (1.33 MB/s) - 'bitcoin-22.0-powerpc64le-linux-gnu.tar.gz' saved [38677732/38677732]

    
    root@a98891605b67:~# tar -xzvf bitcoin-22.0-powerpc64le-linux-gnu.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt
    bitcoin-22.0/README.md
    bitcoin-22.0/bin/
    bitcoin-22.0/bin/bitcoin-cli
    bitcoin-22.0/bin/bitcoin-tx
    bitcoin-22.0/bin/bitcoin-util
    bitcoin-22.0/bin/bitcoin-wallet
    bitcoin-22.0/bin/bitcoind
    bitcoin-22.0/bin/test_bitcoin
    bitcoin-22.0/include/
    bitcoin-22.0/include/bitcoinconsensus.h
    bitcoin-22.0/lib/
    bitcoin-22.0/lib/libbitcoinconsensus.so
    bitcoin-22.0/lib/libbitcoinconsensus.so.0
    bitcoin-22.0/lib/libbitcoinconsensus.so.0.0.0
    bitcoin-22.0/share/
    bitcoin-22.0/share/man/
    bitcoin-22.0/share/man/man1/
    bitcoin-22.0/share/man/man1/bitcoin-cli.1
    bitcoin-22.0/share/man/man1/bitcoin-qt.1
    bitcoin-22.0/share/man/man1/bitcoin-tx.1
    bitcoin-22.0/share/man/man1/bitcoin-util.1
    bitcoin-22.0/share/man/man1/bitcoin-wallet.1
    bitcoin-22.0/share/man/man1/bitcoind.1
    
    root@a98891605b67:~# which bitcoind                                  
    /usr/local/bin/bitcoind
    
    root@a98891605b67:~# bitcoind
    bash: /usr/local/bin/bitcoind: No such file or directory
    
    root@a98891605b67:~# cd /usr/local/bin/
    
    root@a98891605b67:/usr/local/bin# ls
    bitcoin-cli  bitcoin-tx  bitcoin-util  bitcoin-wallet  bitcoind  test_bitcoin
    
    root@a98891605b67:/usr/local/bin# ./bitcoind
    bash: ./bitcoind: No such file or directory
    
    root@a98891605b67:/usr/local/bin#

**Comment by dongcarl** [comment]
I've seen this somewhat frustrating error before, when the loader is not where the binary expects it. In `powerpc64le`'s case, we expect the loader to be located at `/lib/ld64.so.2`. Could you see if `/lib/ld64.so.2` exists?

**Comment by flatcloud0b3** [comment]
i see the loader located at `/lib/powerpc64le-linux-gnu#`

**Comment by dongcarl** [comment]
Interesting... Do you see anything that matches the glob `/lib64/ld64*`?

**Comment by flatcloud0b3** [comment]
I see the following :    

    root@d65d463b0ab3:/lib# ls
    init  lsb  powerpc64le-linux-gnu  systemd  terminfo  udev
    
    root@d65d463b0ab3:/lib# cd powerpc64le-linux-gnu/
    
    root@d65d463b0ab3:/lib/powerpc64le-linux-gnu# ls
    ld-2.31.so		 libbz2.so.1	     libcrypt.so.1	libgpg-error.so.0	libnsl-2.31.so	       libnss_hesiod.so.2     libpcre.so.3.13.3   libss.so.2	       libutil.so.1
    ld64.so.2		 libbz2.so.1.0	     libcrypt.so.1.1.0	libgpg-error.so.0.29.0	libnsl.so.1	       libpam.so.0	      libpthread-2.31.so  libss.so.2.0	       libz.so.1
    libBrokenLocale-2.31.so  libbz2.so.1.0.4     libdl-2.31.so	libkeyutils.so.1	libnss_compat-2.31.so  libpam.so.0.85.1       libpthread.so.0	  libthread_db-1.0.so  libz.so.1.2.11
    libBrokenLocale.so.1	 libc-2.31.so	     libdl.so.2		libkeyutils.so.1.9	libnss_compat.so.2     libpam_misc.so.0       libresolv-2.31.so   libthread_db.so.1    security
    libSegFault.so		 libc.so.6	     libe2p.so.2	liblzma.so.5		libnss_dns-2.31.so     libpam_misc.so.0.82.1  libresolv.so.2	  libtinfo.so.6
    libanl-2.31.so		 libcap-ng.so.0      libe2p.so.2.3	liblzma.so.5.2.5	libnss_dns.so.2        libpamc.so.0	      librt-2.31.so	  libtinfo.so.6.2
    libanl.so.1		 libcap-ng.so.0.0.0  libext2fs.so.2	libm-2.31.so		libnss_files-2.31.so   libpamc.so.0.82.1      librt.so.1	  libtirpc.so.3
    libaudit.so.1		 libcom_err.so.2     libext2fs.so.2.4	libm.so.6		libnss_files.so.2      libpcprofile.so	      libselinux.so.1	  libtirpc.so.3.0.0
    libaudit.so.1.0.0	 libcom_err.so.2.1   libgcc_s.so.1	libmemusage.so		libnss_hesiod-2.31.so  libpcre.so.3	      libsepol.so.1	  libutil-2.31.so
    
    root@d65d463b0ab3:/lib/powerpc64le-linux-gnu#

    root@d65d463b0ab3:/lib/powerpc64le-linux-gnu# cd /lib64
    
    root@d65d463b0ab3:/lib64# ls
    ld64.so.2
    
    root@d65d463b0ab3:/lib64# 

If i copy `ld64.so.2` from `/lib/powerpc64le-linux-gnu/ld64.so.2` to `/lib/ld64.so.2` bitcoind is able to execute.

**Comment by luke-jr** [comment]
FWIW, on my system, there is no `/lib/powerpc64le-linux-gnu/ld64.so.2`, and `/lib/ld64.so.2` resolves to `/lib64/ld64.so.2` due to `/lib` being symlinked to `lib64`
