### ISSUE TITLE
Self-compiled ended up with "22.99" instead of "0.22"

### ISSUE THREAD

**Issue by raymondclowe** [bitcoin/bitcoin#23125]
Compiled what I thought was the source code for 0.22 but end up with "22.99".

I expected to get a self-built version 0.22

$ bitcoind --version                       
Bitcoin Core version v22.99.0-f036c35e51fe

I have only compiled once, but I presume this is going to be the same every time.

As I needed to compile for myself (I needed 32 bit linux) I went to find the source code, as I realize the master branch is for development and not a release I looked at other brances :

https://github.com/bitcoin/bitcoin/branches

The only "22" I could see was:

https://github.com/bitcoin/bitcoin/tree/22.x

I git cloned that then compiled following the instructions in the build linux document.

That worked fine, seemed to be ok and ended up with an exectuable.

This is a 32 bit Linux Mint version 19

I presume I've taken the wrong source.  If so, where is the right one and how might I or indeed other people find it more easily?

It seems I'm not the only one to make this mistake as looking at stats show many nodes running "22.99":

https://bitnodes.io/nodes/leaderboard/?q=%2FSatoshi%3A22.99

**Comment by MarcoFalke** [comment]
You will need to specify the branch on clone or git checkout the branch after clone.

**Comment by raymondclowe** [comment]
Ok, thanks for explaining  My misunderstanding of the way github works - I thought that after switch branches the get code button would refer to that branch but no...  Looking at my history I can see I did:

git clone https://github.com/bitcoin/bitcoin.git

Which is wrong.

So now I should git checkout the correct branch.

Is it ok to just run "make install" again or do I have to do some clean up?

**Comment by MarcoFalke** [comment]
You'll have to call `make distclean` when switching branches, because the build system usually goes through major changes between releases.

**Comment by raymondclowe** [comment]
Thank you.  It works now.

I did:

```
git checkout 22.x
make distclean
./autogen.sh
./configure CXXFLAGS="-O2" --with-incompatible-bdb --without-bdb
make install
```

And the result is good:

$ bitcoind --version
Bitcoin Core version v22.0
