### ISSUE TITLE
Plumb "too-long-mempool-chain" to RPC error for send/sendtoaddress

### ISSUE THREAD

**Issue by JeremyRand** [bitcoin/bitcoin#23144]
**Is your feature request related to a problem? Please describe.**

If coin selection fails as part of `send` or `sendtoaddress`, the error message returned to the RPC client is `Insufficient funds`, even if the actual cause is due to `too-long-mempool-chain`.  This is likely to alarm users unnecessarily, as they will believe this means their funds have permanently vanished rather than being temporarily inaccessible.

**Describe the solution you'd like**

If coin selection fails due to `too-long-mempool-chain`, the `send` and `sendtoaddress` methods should pass that error back to the RPC client, instead of `Insufficient funds`.

**Describe alternatives you've considered**

It would be even nicer from a UX standpoint if the limit on mempool chain length were removed, but AIUI [that's a DoS vector](https://github.com/bitcoin/bitcoin/issues/9752#issuecomment-281464014), so is not going to happen.

**Additional context**

Apparently this is [already done for `sendrawtransaction`](https://github.com/bitcoin/bitcoin/pull/10015#issuecomment-288597075).  The discussion in https://github.com/bitcoin/bitcoin/pull/10015 is relevant (it appears that the PR was withdrawn for reasons unrelated to my request).

**Comment by jamesob** [comment]
The relevant code seems to be here: https://github.com/bitcoin/bitcoin/blob/master/src/wallet/rpc/spend.cpp#L73-L76

**Comment by JeremyRand** [comment]
> Seems to me that "insufficient funds" is the correct error message here if you cannot construct a transaction that the mempool would accept. Similarly, you may get "insufficient funds" if your coins are premature or nonfinal. If a user is interested in a more detailed breakdown of their coins, including whether things are spendable / safe to spend, they might want to use something like `listunspent`.

@glozow Why do you think the `too-long-mempool-chain` error code exists if it shouldn't be used here?

**Comment by glozow** [comment]
`too-long-mempool-chain` corresponds to the reason a transaction is rejected from mempool. It's helpful, for example, to debug a transaction you submitted through `sendrawtransaction` or `testmempoolaccept`. It's also logged for rejected p2p transactions.

**Comment by JeremyRand** [comment]
@glozow Okay, so given your description, I don't understand why that code wouldn't be intuitively applicable to `send` when the method fails because the transaction would be rejected from the mempool.  The status quo is confusing to nontechnical users (source: personal experience providing tech support to users who think their funds have been stolen after seeing this error code).

FWIW I agree with @achow101 in https://github.com/bitcoin/bitcoin/pull/24502#issuecomment-1061742337 : 

> I think "insufficient funds" is too generic of an error message for coin selection failures as there are a ton of different reasons why coin selection might fail. I would like to have more granular error messages

**Comment by achow101** [comment]
We can have errors that contain more explanation than just a few words. For example, this error could be "Insufficient funds: Too long mempool chain. Creating this transaction would require creating a chain of unconfirmed transaction that will currently be rejected by the mempool."

**Comment by JeremyRand** [comment]
> We can have errors that contain more explanation than just a few words. For example, this error could be "Insufficient funds: Too long mempool chain. Creating this transaction would require creating a chain of unconfirmed transaction that will currently be rejected by the mempool."

@achow101 I have no objection to this suggestion.

**Comment by glozow** [comment]
> "Insufficient funds: Too long mempool chain. Creating this transaction would require creating a chain of unconfirmed transaction that will currently be rejected by the mempool."

I might prefer something like "insufficient funds: unconfirmed UTXOs are available, but spending them creates a chain of transactions that will be rejected by the mempool. These funds will become available when the transaction confirms" or something.

In general, I'm not saying I'm against more specific error messages. I'm saying that, since the user was not responsible for creating the transaction in the first place, it seems unhelpful to tell them the transaction was too-long-mempool-chain, as they can't do anything differently to change this. The information that would be helpful to them is "you have money, but it's in unconfirmed UTXOs and I can't create a valid transaction right now."
