### ISSUE TITLE
i got an compiling issue playing arround to get to know the bitcoin core code | issue src/secp256k1'

### ISSUE THREAD

**Issue by bartgevers013** [bitcoin/bitcoin#23166]
i got this when compiling 

 CXX      leveldb/util/libleveldb_a-histogram.o
  CXX      leveldb/util/libleveldb_a-logging.o
  CXX      leveldb/util/libleveldb_a-options.o
  CXX      leveldb/util/libleveldb_a-status.o
  CXX      leveldb/util/libleveldb_a-env_posix.o
  AR       leveldb/libleveldb.a
  CXX      crc32c/src/libcrc32c_a-crc32c.o
  CXX      crc32c/src/libcrc32c_a-crc32c_portable.o
  AR       crc32c/libcrc32c.a
  CXX      crc32c/src/libcrc32c_sse42_a-crc32c_sse42.o
  AR       crc32c/libcrc32c_sse42.a
  CXX      leveldb/helpers/memenv/libmemenv_a-memenv.o
  AR       leveldb/libmemenv.a
make[3]: Entering directory '/home/bartoshi/Desktop/dollscoin1/src/secp256k1'
gcc -DHAVE_CONFIG_H -I. -I./src -O2  -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wcast-align=strict -fvisibility=hidden  -g -O2 -c src/gen_context.c -o gen_context.o
gcc -O2  -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wcast-align=strict -fvisibility=hidden  -g -O2  gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[3]: Leaving directory '/home/bartoshi/Desktop/dollscoin1/src/secp256k1'
  CXXLD    dollscoind
  CXX      dollscoin_cli-dollscoin-cli.o
  CXX      compat/libdollscoin_cli_a-stdin.o
  CXX      rpc/libdollscoin_cli_a-client.o
  AR       libdollscoin_cli.a

any help to give me the direction of this problem is welcome 
i use a VM virtualbox ubuntu .
kindest regards

**Comment by fanquake** [comment]
I don't see any error output here.

**Comment by bartgevers013** [comment]
@fanquake ok ok so the whole 
make[3]: Entering directory '/home/bartoshi/Desktop/dollscoin1/src/secp256k1'
gcc -DHAVE_CONFIG_H -I. -I./src -O2 -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wcast-align=strict -fvisibility=hidden -g -O2 -c src/gen_context.c -o gen_context.o
gcc -O2 -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wcast-align=strict -fvisibility=hidden -g -O2 gen_context.o -o gen_context
./gen_context

is normal for a clean compile? 
because i really thought i did not see this when compiling original bitcoin core .

**Comment by fanquake** [comment]
> is normal for a clean compile?

Yes.

**Comment by bartgevers013** [comment]
@fanquake ok ok im sorry for taking your time if this is the case maybe you can remove this post?
and i have another question for playing around with the code .
if inserting and generating an new genesis hash .
i need to put the merkle / genesis /time / nonce in the code but also the bits right or are the bits not needed .
because i get an hash fail dumped message today when trying .
and maybe you can point me in the right direction of how to generate the genesis hash the right way .
i know used this tool .
https://github.com/hashcrack256/node-genesis-block.git

kindest regards

**Comment by fanquake** [comment]
Not sure what you are trying to achieve, but it's off-topic here.

**Comment by sipa** [comment]
This is not dollcoin support.
