### ISSUE TITLE
make getaccountaddress default to ""

### ISSUE THREAD

**Issue by anarcat** [bitcoin/bitcoin#2317]
It seems that `""` is the default account, but that a few RPC commands do not really recognize that. It seems to me that the account should be optional for commands like `getaccountaddress`. This probably applies to `getaddressesbyaccount` and `getreceivedbyaccounttoo`.

**Comment by laanwj** [comment]
The account system has now been deprecated for a long time (see #3816), so I am closing feature requests involving it.
