### ISSUE TITLE
RPC: Allow user to supply weight of external input

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#23187]
This would allow wallet operations like funding transactions with smart contract-based inputs such as LN, or any input the Core wallet doesn't know how to sign for.

https://github.com/bitcoin/bitcoin/pull/17211#issuecomment-933674310

**Comment by achow101** [comment]
The easiest way to do this is to add another field to the input object (in the inputs array) that specifies the input weight. However this is not possible to do with `fundrawtransaction` as it does not have an inputs array, but this would work for `walletcreatefundedpsbt` and `send`.

**Comment by michaelfolkson** [comment]
Some additional clarification on this issue after the [PR review club](https://bitcoincore.reviews/23201) (and @achow101, @t-bast can correct me if this wrong!).

> any input the Core wallet doesn't know how to sign for

It isn't not that the Core wallet doesn't know how to sign for these inputs (there is a dummy signer if the Core wallet doesn't have the key(s) to spend it), it is that the Core wallet doesn't understand how to work out the weight of an external input and hence the required transaction fee. An example would be spending from a Lightning non-cooperative close or HTLC. The Core wallet would understand a Lightning cooperative close as that it is just spending from a 2-of-2 multisig which the Core currently understands (covered by descriptors). Any scripts not covered by descriptors (e.g. scripts covered by Miniscript or Lightning HTLCs that aren't covered by Miniscript) the Core wallet doesn't understand at the present time and needs the user to supply the weight of the external input.

**Comment by achow101** [comment]
> It isn't that the Core wallet doesn't know how to sign for these inputs (there is a dummy signer if the Core wallet doesn't have the key(s) to spend it), it is that the Core wallet doesn't understand how to work out the weight of an external input and hence the required transaction fee.

"Doesn't know how to sign for" includes the case where solving data is missing. If the wallet is missing keys, it is also unable to determine the weight of an external input. Standard scripts still have solving data, and if they are unknown, the wallet will be unable to estimate their sizes.

**Comment by michaelfolkson** [comment]
Because ECDSA signatures (not Schnorr, they are fixed weight so you know the weight of a Schnorr signature) vary in weight so even for a standard script that only requires a single signature you don't know the weight of the signature if you don't have the key right?

**Comment by achow101** [comment]
No. Signatures have a max size and the variation is only a one or two bytes, so it doesn't really matter. Keys and scripts are needed because they can vary. For P2PKH, the key may be either compressed or uncompressed. The spending size cannot be determined without knowing what the key is. For P2SH and P2WSH, obviously you need the script. P2WPKH could be computed without any solving data, but currently we do not. This behavior is at least consistent with the other output types.
