### ISSUE TITLE
Failed assertion during shutdown

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#23186]
On master (9013f23b0a6e0e450c4603f9d0f050ff10d552f6) observed a failed assertion after trying to quit immediately after the GUI open:

```
$ src/qt/bitcoin-qt
bitcoin-qt: init.cpp:183: auto Shutdown(NodeContext &)::(anonymous class)::operator()() const: Assertion `"node.args" && check' failed.
Aborted (core dumped)
```

**Comment by hebasto** [comment]
cc @ryanofsky

**Comment by ryanofsky** [comment]
Looks like this assert(node.arg) is running

https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/init.cpp#L183

before node.args is assigned

https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/init/bitcoin-node.cpp#L27

https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/qt/bitcoin.cpp#L468

Unclear how this would happen or if it is a new problem

**Comment by ryanofsky** [comment]
Probably stack trace for the assert is 

Shutdown()
https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/init.cpp#L183

NodeImpl::appShutdown()
https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/node/interfaces.cpp#L92

InitExecutor::shutdown
https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/qt/initexecutor.cpp#L62

So initexecutor is somehow shutting down before MakeNodeInit is called?

**Comment by ryanofsky** [comment]
> So initexecutor is somehow shutting down before MakeNodeInit is called?

This seems impossible actually. More likely might be that Shutdown() is being called twice, and the second time it fails because the first call reset args to null:

https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/init.cpp#L298

**Comment by ryanofsky** [comment]
If the problem is that Shutdown() is being called twice, it would be good to figure out why Shutdown is being called twice, and whether that is happening in a thread safe way, and whether GUI shutdown logic can be simplified so this doesn't happen.

But whether or not you actually want the GUI to call Shutdown multiple times, it would probably be good to make the Shutdown function idempotent and just delete the `node.args = nullptr;` line since it doesn't really belong there anyway:

https://github.com/bitcoin/bitcoin/blob/9013f23b0a6e0e450c4603f9d0f050ff10d552f6/src/init.cpp#L298

**Comment by hebasto** [comment]
This bug is 100% reproducible in my [Qt 6 branch](https://github.com/bitcoin/bitcoin/pull/24798).

> If the problem is that Shutdown() is being called twice

No. `Shutdown()` is being called once.

**Comment by ryanofsky** [comment]
> Confirmed. It is being called twice.

I don't remember all the details here but it does seem like making it idempotent and deleting the `node.args = nullptr;` line could be a good fix

**Comment by ryanofsky** [comment]
Deleting that line also fixed a test crash in 76343aa03f0c66de8ef4b5eebe4ba65743d63d2d from #15936

**Comment by hebasto** [comment]
> This bug is 100% reproducible in my [Qt 6 branch](https://github.com/bitcoin/bitcoin/pull/24798).

It's unrelated to the [initial](https://github.com/bitcoin/bitcoin/issues/23186#issue-1016333273) issue, as it appears Qt 6 [specific](https://github.com/bitcoin-core/gui/pull/586).

**Comment by fanquake** [comment]
Is this still an issue? If yes. How is it reproduced? If it's GUI/qt only, then move it to the GUI repo?

**Comment by hebasto** [comment]
Closing for now. Will reopen after being able to reproduce.
