### ISSUE TITLE
bitcoin-cli getaddressofwallet 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [bitcoin/bitcoin#23256]
sorry to ask for this feature 

i have created a regtest  network on ubuntu but  when i create a bitcoin wallet i can not get the address of that with bitcoin-cli 
please provide a method to get the current wallet address

**Comment by Johnsavadkuhi** [comment]
add getcurrentaddress

**Comment by sipa** [comment]
There is no concept of a "current address". You can request a new address using the `getnewaddress` RPC.

**Comment by prayank23** [comment]
> getnewaddress is address of loaded wallet ?

You can mention the wallet with `-rpcwallet` followed by command trying to execute for this wallet

Example: 

If there are two wallets w1 and w2 and I want to get a new address from w1 wallet, the command will be:

```
$ bitcoin-cli -rpcwallet=w1 getnewaddress
```

If the wallet is not loaded it will return error and you will have to load the wallet first with [`loadwallet`](https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/loadwallet/)
