### ISSUE TITLE
Issue on the github page

### ISSUE THREAD

**Issue by NGUmonster** [bitcoin/bitcoin#23419]
Sorry wasn't sure who else to contact. This GitHub page tells you to check out the Bitcoin Wiki at https://en.bitcoin.it/

I was reading through JSON-RPC API reference and there's the PHP section, which links to a "JSON-RPC PHP" library, but the link then redirects to a completely different and malicious website (Blocked by Malwarebytes):

https://en.bitcoin.it/wiki/API\_reference\_(JSON-RPC)#PHP

I'm just a messenger,  the person who found it just posted the text above at Reddit https://www.reddit.com/r/Bitcoin/comments/qlc98c/who_should_i_contact_if_the_bitcoin_core_docs/

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. This is not an issue tracker for unrelated third-party websites. Maybe try https://en.bitcoin.it/wiki/Bitcoin_Wiki:About or the `#bitcoin` IRC channel on Libera Chat?
