### ISSUE TITLE
sendtoaddress, transactions stuck in pending state

### ISSUE THREAD

**Issue by ytytgo** [bitcoin/bitcoin#23459]
#node2
address=$(./bitcoin-cli getnewaddress)

#node1
./bitcoin-cli sendtoaddress $address 1

#node2
./bitcoin-cli getwalletinfo  

 "unconfirmed_balance": 23.60000000,

coin is stuck in unconfirmed_balance, never move to balance.

minings are running on node1 & node2.

**Comment by MarcoFalke** [comment]
> minings are running on node1 & node2.

You will need to make sure that the transaction is included into a block on either node.

`sendtoaddress` returns a txid, which you can look for in the block.
