### ISSUE TITLE
Standardized documentation to a single way of disabling GUI

### ISSUE THREAD

**Issue by shaavan** [bitcoin/bitcoin#23472]
While configuring bitcoin. One can specify not to compile GUI in 2 ways:

- `./configure --without-gui`
- `./configure --with-gui=no`

The issue is that there is no `--help` documentation for the --without-gui command.
I am not aware of this, but it seems like `--with-gui=no` is the latest way of specifying the settings. But some documentation is still using the `--without-gui` convention.

There is a need to standardize the docs to one of these options.

Now we can proceed on these in 2 ways:
1. **Standardize to** `without-gui`. Then we should add --help docs for this command. But the problem with this method is we have two ways of doing the same thing. This increases the number of redundant commands without providing any actual benefit.
2. **Standardize to** `with-gui=no`. In this case, we could go as extreme as to remove the `without-gui` command entirely. This will decrease redundant commands and will allow having a single command to either enable or disable GUI.

I would like to listen to other contributors’ valuable suggestions on this matter.

**Comment by fanquake** [comment]
> One can specify not to compile GUI in 2 ways:

` --without-gui` and `--with-gui=no` are the same thing (`./configure --help`):

```bash
Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
```

> I am not aware of this, but it seems like --with-gui=no is the latest way of specifying the settings. 
> In this case, we could go as extreme as to remove the without-gui command entirely.

I'd suggest you read up on how autotools works, as it is responsible for generating these options. We can't just "remove" the `--without-gui` option.

**Comment by shaavan** [comment]
> I'd suggest you read up on how autotools works, as it is responsible for generating these options. We can't just "remove" the --without-gui option.

I was not aware of this. Let me do some read-ups. Thanks for clarifying!
(Closing this issue)
