### ISSUE TITLE
Any report, issue or feature request related to the GUI should be reported at https://github.com/bitcoin-core/gui/issues/

### ISSUE THREAD

**Issue by SICKID0** [bitcoin/bitcoin#23485]
Im using the BITCOIN Core Version 0.21 and got an problem with creating a reveiving adress. The Button for Creating a new reveiving adress is grey and not usable so i wonder how i can create a reveiving adress in Bitcoin Core? What is the Issue? 

Any report, issue or feature request related to the GUI should be reported at
https://github.com/bitcoin-core/gui/issues/

**Comment by hebasto** [comment]
Please make the issue title more descriptive.

Is your issue similar to https://github.com/bitcoin-core/gui/issues/105 or https://bitcoin.stackexchange.com/questions/100812/create-a-new-receiving-address-is-greyed-out-why?

**Comment by SICKID0** [comment]
My issue was similar to the secound link. Thanks for your help. Now the Reveiving Button is functional. Wish ya a great evening :)

**Comment by MarcoFalke** [comment]
Ok, good to hear it is working now.
