### ISSUE TITLE
A network rule is not requiring a hard fork. Network rules are not about miners, they are about network nodes. AFAIK (source included)

### ISSUE THREAD

**Issue by satoshi0x** [bitcoin/bitcoin#23490]
https://github.com/bitcoin/bitcoin/blob/3038eb63e8a674b4818cb5d5e461f1ccf4b2932f/src/consensus/consensus.h#L10

Increasing the value in L10 of consensus.h `MAX_BLOCK_SIZE = 1000000` wouldn't create a hard fork per Bitcoin Wiki (.it ccTLD version, en subdomain). The Original Bitcoin Wiki by Mark Karpeles - this would apply to original Bitcoin rule sets about hard forking. The removal of consensus rules requires a hard fork. Adding consensus rules usually done as softfork. However making the block size bigger is a network protocol change and that is NOT consensus. This should not be in the consensus.h file, and the entire concept of Bitcoin (BTC) having "hardforked" for bigger blocks if this is the code that was changed (this one line according to Bitcoin Core's bitcoincore.org website) - then this was not a consensus change other "forks" made for bigger block size, and they did not even hard fork/chain split at all. For that reason, the only reason for the hard forking of chains would be the changing of actual consensus rules. A clear list of those in this entry below would make sense of this once and for all:

Source: https://en.bitcoin.it/wiki/Consensus (edited last by [Theymos](https://en.bitcoin.it/wiki/User:Theymos))

> Consensus rules
> The consensus rules are the specific set of rules that all Bitcoin full nodes will unfailingly enforce when considering the validity of a block and its transactions. For example, the Bitcoin consensus rules require that blocks only create a certain number of bitcoins. If a block creates more bitcoins than is allowed, all full nodes will reject this block, even if every other node and miner in the world accepts it. Adding new consensus rules can generally be done as a softfork, while removing any consensus rule requires a hardfork. Rules regarding the behavior of the mere network protocol are not consensus rules, even if a change to the network protocol behavior breaks backward-compatibility. The consensus rules are only concerned with the validity of blocks and transactions.

Changes on Network level protocol are NOT hard forks due to consensus. If there was a hard fork this reason was a sham to influence a vote due to naive/ambiguous lack of definition. We need this clarified. This is too long to have overlooked this simple line of code and its terminology. It's clear as day to me.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
