### ISSUE TITLE
Wrong link for mac os dmg on homepage

### ISSUE THREAD

**Issue by surak** [bitcoin/bitcoin#23527]
The page https://bitcoin.org/en/download

points to https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-osx.dmg

which does not exist. The file is called 

https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-osx-signed.dmg

**Comment by MarcoFalke** [comment]
Wrong repo. You can try https://github.com/bitcoin-dot-org/Bitcoin.org
