### ISSUE TITLE
v22.0 fundrawtransaction Insufficient funds error 

### ISSUE THREAD

**Issue by DevMinJong** [bitcoin/bitcoin#23533]
Wallet's balance was sufficient to pay a fee, and we used "subractFeeFromOutputs" as a "fundrawtransaction" option to transfer all of the money from the account.
However, if the feeRate is set high, the amount to pay the fee is sufficient, but an "Insufficient Funds" error occurs.

## v0.17.1

./bitcoin-cli getbalance 
`0.02747781`

./bitcoin-cli createrawtransaction [] "[{\"1BoN7fHjtdufAL4ZjVnbW38SsAMbQwPK4R\":0.02747781}]"
`02000000000185ed2900000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000`

**[high feeRate case]**
./bitcoin-cli fundrawtransaction "02000000000185ed2900000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000" "{\"subtractFeeFromOutputs\":[0], \"feeRate\":0.01016711}"
```
{
  "hex": "020000001183fb588c5ceae790f627fd76278fefbe7ecb414ae3c83678746b5a7c32b9b5b70000000000fdffffff1dc5e5d10a325c739924ee0f990171eb1660ca24f6038dec6c69799721590ba90000000000fdffffffda529a6edd29c32b1f746ac39d1b28776543a6aed5c330007b0756743ee2f8420000000000fdfffffff3dd6ea5b7fc0540a179162cbd1b9c25e82d7d5c0ad6a7e086dcba4f4f9798760100000000fdffffff57afa33e56d3cdcc752cfae9e0b44b8e9608400d07e5ddd122669426b29ea9c80100000000fdffffffccee315e4800d7ac0696c8f8845d9985573882f1483d95572c3465226fd872d40000000000fdffffff4ed7188988b48dcd81723fed788cd72811173c88557dc0e807867b2c116cbf640000000000fdffffff342d28a62a5f005adcb1bbc8eae7640377c78b643e5cb2642235e58498047b200000000000fdffffff4ffdff99026432d641b7be05979661088f74ea5304649102c090cebb552e1e1e0000000000fdffffffc39083c8b187b4feec0c93a64d7e0b3377dbb4d436d5b869f42a8c863af685b50000000000fdffffff4ae03f15b3f1ccfe1d1672e94098bb56add36bbd7d6cfba187c7ec61af42aa830000000000fdfffffff9c4284c741c018136e588b921a3dc365c9a3d93f2b788f523dced9a3f3b53ff0100000000fdffffff90c43d6d07ce04c8676376cbabdd9293cc251320d3dfa065ffe22524f14207150100000000fdffffffae5ba3902ba27be221261ec4a19e88cebec6e7d37c7264170a0b4304b3f94fd50000000000fdffffffc579ad3661c6999eeff283f97d3b2bd119d449c18e46fa28fb4d344493d3ce280100000000fdffffff3db96066d514891dececeadf3cc9f75cec457aa78cc5dbd2f7f6c8254674df950000000000fdffffff69a8eeeefbc5912636d3c715c73581525db4de907556e1c132c1d4436030cf700100000000fdffffff01147c0300000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000",
  "fee": 0.02519409,
  "changepos": -1
}
```

./bicoin-cli decderawtransaction "020000001183fb588c5ceae790f627fd76278fefbe7ecb414ae3c83678746b5a7c32b9b5b70000000000fdffffff1dc5e5d10a325c739924ee0f990171eb1660ca24f6038dec6c69799721590ba90000000000fdffffffda529a6edd29c32b1f746ac39d1b28776543a6aed5c330007b0756743ee2f8420000000000fdfffffff3dd6ea5b7fc0540a179162cbd1b9c25e82d7d5c0ad6a7e086dcba4f4f9798760100000000fdffffff57afa33e56d3cdcc752cfae9e0b44b8e9608400d07e5ddd122669426b29ea9c80100000000fdffffffccee315e4800d7ac0696c8f8845d9985573882f1483d95572c3465226fd872d40000000000fdffffff4ed7188988b48dcd81723fed788cd72811173c88557dc0e807867b2c116cbf640000000000fdffffff342d28a62a5f005adcb1bbc8eae7640377c78b643e5cb2642235e58498047b200000000000fdffffff4ffdff99026432d641b7be05979661088f74ea5304649102c090cebb552e1e1e0000000000fdffffffc39083c8b187b4feec0c93a64d7e0b3377dbb4d436d5b869f42a8c863af685b50000000000fdffffff4ae03f15b3f1ccfe1d1672e94098bb56add36bbd7d6cfba187c7ec61af42aa830000000000fdfffffff9c4284c741c018136e588b921a3dc365c9a3d93f2b788f523dced9a3f3b53ff0100000000fdffffff90c43d6d07ce04c8676376cbabdd9293cc251320d3dfa065ffe22524f14207150100000000fdffffffae5ba3902ba27be221261ec4a19e88cebec6e7d37c7264170a0b4304b3f94fd50000000000fdffffffc579ad3661c6999eeff283f97d3b2bd119d449c18e46fa28fb4d344493d3ce280100000000fdffffff3db96066d514891dececeadf3cc9f75cec457aa78cc5dbd2f7f6c8254674df950000000000fdffffff69a8eeeefbc5912636d3c715c73581525db4de907556e1c132c1d4436030cf700100000000fdffffff01147c0300000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000"
```
{
  "txid": "2e6d8121885968861261a9473f889af0abfccd32f784178eb20dc62ec6bad8e4",
  "hash": "2e6d8121885968861261a9473f889af0abfccd32f784178eb20dc62ec6bad8e4",
  "version": 2,
  "size": 741,
  "vsize": 741,
  "weight": 2964,
  "locktime": 0,
  "vin": [
    {
      "txid": "b7b5b9327c5a6b747836c8e34a41cb7ebeef8f2776fd27f690e7ea5c8c58fb83",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "sequence": 4294967293
    },
    {
      "txid": "a90b59219779696cec8d03f624ca6016eb7101990fee2499735c320ad1e5c51d",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "sequence": 4294967293
    }

....
  ],
  "vout": [
    {
      "value": 0.00228372,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 76760491fdf2f1dc5428c79058c49e93fc432b81 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "1BoN7fHjtdufAL4ZjVnbW38SsAMbQwPK4R"
        ]
      }
    }
  ]
}
```

## v22.0

./bitcoin-cli getbalance 
`0.02747781`

./bitcoin-cli createrawtransaction [] "[{\"1BoN7fHjtdufAL4ZjVnbW38SsAMbQwPK4R\":0.02747781}]"
`02000000000185ed2900000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000`

**[Appropriate fee case]**
./bitcoin-cli fundrawtransaction "02000000000185ed2900000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000" "{\"subtractFeeFromOutputs\":[0], \"feeRate\":0.00006711}"
```
{
  "hex": "020000001190c43d6d07ce04c8676376cbabdd9293cc251320d3dfa065ffe22524f14207150100000000fdffffff83fb588c5ceae790f627fd76278fefbe7ecb414ae3c83678746b5a7c32b9b5b70000000000fdffffff69a8eeeefbc5912636d3c715c73581525db4de907556e1c132c1d4436030cf700100000000fdffffff4ed7188988b48dcd81723fed788cd72811173c88557dc0e807867b2c116cbf640000000000fdffffff4ffdff99026432d641b7be05979661088f74ea5304649102c090cebb552e1e1e0000000000fdffffff3db96066d514891dececeadf3cc9f75cec457aa78cc5dbd2f7f6c8254674df950000000000fdffffff342d28a62a5f005adcb1bbc8eae7640377c78b643e5cb2642235e58498047b200000000000fdffffffda529a6edd29c32b1f746ac39d1b28776543a6aed5c330007b0756743ee2f8420000000000fdffffffae5ba3902ba27be221261ec4a19e88cebec6e7d37c7264170a0b4304b3f94fd50000000000fdffffff57afa33e56d3cdcc752cfae9e0b44b8e9608400d07e5ddd122669426b29ea9c80100000000fdffffff1dc5e5d10a325c739924ee0f990171eb1660ca24f6038dec6c69799721590ba90000000000fdfffffff3dd6ea5b7fc0540a179162cbd1b9c25e82d7d5c0ad6a7e086dcba4f4f9798760100000000fdffffffccee315e4800d7ac0696c8f8845d9985573882f1483d95572c3465226fd872d40000000000fdffffff4ae03f15b3f1ccfe1d1672e94098bb56add36bbd7d6cfba187c7ec61af42aa830000000000fdffffffc39083c8b187b4feec0c93a64d7e0b3377dbb4d436d5b869f42a8c863af685b50000000000fdfffffff9c4284c741c018136e588b921a3dc365c9a3d93f2b788f523dced9a3f3b53ff0100000000fdffffffc579ad3661c6999eeff283f97d3b2bd119d449c18e46fa28fb4d344493d3ce280100000000fdffffff0190ac2900000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000",
  "fee": 0.00016629,
  "changepos": -1
}
```

 **[high fee case]** 
./bitcoin-cli fundrawtransaction "02000000000185ed2900000000001976a91476760491fdf2f1dc5428c79058c49e93fc432b8188ac00000000" "
{\"subtractFeeFromOutputs\":[0], \"feeRate\":0.00006712}"
```
error code: -4
error message:
Insufficient funds
```

##.
**In the above case, v22.0 shows a normal response if the feeRate is 0.00006711 or less, and an error if it is 0.00006712 or higher. Can I know why?**

**Comment by MarcoFalke** [comment]
How is this different from https://github.com/bitcoin/bitcoin/issues/23026#issuecomment-971123270 ?
