### ISSUE TITLE
Descriptor Checksum Inconsistency

### ISSUE THREAD

**Issue by SachinMeier** [bitcoin/bitcoin#23539]
Issue:

The Checksum generated by `getdescriptorinfo` is not accepted when I use it in `importdescriptors`. The two RPC calls calculate a different checksum for the same descriptor. 

I ran the following commands on MacOS with bitcoind v0.21.1 installed. Since my descriptor lacked a checksum, I used `getdescriptorinfo` to generate one, as I read here: https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#checksums
```
The checksum for a descriptor without one can be computed using the getdescriptorinfo RPC.
```

I expected the checksum generated by `getdescriptorinfo` to be accepted by `importdescriptors`. It was not. 

The actual behavior is below. I am redacting the actual descriptors/hashes for personal privacy.

```bash
$ bitcoin-cli --version
Bitcoin Core RPC client version v0.21.1
# getdescriptorinfo generates a checksum beginning with 3a.
$ bitcoin-cli getdescriptorinfo "<DESCRIPTOR>"
{
  "descriptor": "<DESCRIPTOR>#3a...",
  "checksum": "3a...",
  "isrange": false,
  "issolvable": true,
  "hasprivatekeys": false
}
# importdescriptors rejects the checksum generated by getdescriptorinfo and calculates its own different one
$ bitcoin-cli -rpcwallet=my_wallet importdescriptors '[{ "desc": "<DESCRIPTOR>#3a...", "timestamp": "now" }]'
[
  {
    "success": false,
    "error": {
      "code": -5,
      "message": "Provided checksum '3a...' does not match computed checksum '6z...'"
    }
  }
]
# importdescriptors properly accepts the checksum provided by itself.
$ bitcoin-cli -rpcwallet=my_wallet importdescriptors '[{ "desc": "<DESCRIPTOR>#6z...", "timestamp": "now" }]' 
[
  {
    "success": true
  }
]
# Using checksum expected by importdescriptors throws an error when used in getdescriptorinfo cmd
$ bitcoin-cli getdescriptorinfo "<DESCRIPTOR>#6z..."
error code: -5
error message:
Provided checksum '6z40f68x' does not match computed checksum '3av8evsc'
```

**System information**

Bitcoin Core info:
Bitcoin Core RPC client version v0.21.1 Downloaded from Bitcoin.org binary. Not compiled from source.

Machine/OS: 
MacOS Catalina 10.15.6 
Memory 16GB

**Comment by sipa** [comment]
Are you sure the checksum in the "descriptor" field and the one in the "checksum" field are the same?

They can differ, because the echoed-back descriptor is normalized (and e.g. lacks private keys), and the checksum there is computed over the echoed-back form. The "checksum" field is supposed to be for exactly your input descriptor as you provided it.

**Comment by SachinMeier** [comment]
Yes, I just double checked this now. I am using a descriptor of the form `wpkh([fp/1'/0']xpub.../2)`. The output of `getdescriptorinfo` is exactly the same as my input.

**Comment by achow101** [comment]
This shouldn't be possible since they use the exact same code.

Can you share exactly the descriptors that you used (or generate descriptors that exhibit the same issue that you are willing to share)?

**Comment by sipa** [comment]
Your issue is that bash is eating the `'` characters in the second command.

**Comment by SachinMeier** [comment]
Yep, that's it. Sorry for the waste of time.

**Comment by sipa** [comment]
no worries
