### ISSUE TITLE
add benchmark to test large scale of hardware

### ISSUE THREAD

**Issue by elkimek** [bitcoin/bitcoin#23537]
I'm not sure if there are any benchmarks that could be easily used to test large scale of hardware wrt type of bottleneck (CPU/SSD bound). I recall I saw something on Twitter mentioned by @sipa but not sure now what it was about.

Benching CPUs, RAMs and SSDs is my daily job and I've been wanting to have some Bitcoin related benchmarks in my suite. Last month I was rebenching 14 CPUs and I wish I had relevant data on their performance in bitcoin software.

It would be best if we could have such benchmarks as part of https://github.com/phoronix-test-suite/phoronix-test-suite and https://openbenchmarking.org/ so we could bench all kind of hardware and different versions of bitcoin core with single command. That way we could have a lot of open data which I'm sure could be useful to development.

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin/bitcoin/blob/2ef186a1400c1c7f498549dd97c227819456245e/doc/benchmarking.md

**Comment by elkimek** [comment]
Thank you, I wasn't aware of this :)

**Comment by sipa** [comment]
Note that those benchmarks are primary microbenchmarks that aren't necessarily indicative of real-world performance. @jamesob does run some benchmarking infrastructure that does larger things (like fully synchronizing a node), but is hard to throw into a tool, because it depends on far more infrastructure.

**Comment by MarcoFalke** [comment]
Jup, that's also mentioned in the doc ;)

> To monitor Bitcoin Core performance more in depth (like reindex or IBD): https://github.com/chaincodelabs/bitcoinperf

**Comment by fanquake** [comment]
Closing, there doesn't actually seem to be anything for us to do here.
