### ISSUE TITLE
Secure bitcoin storage (e.g. offline wallets) not available to non-technical people

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#2355]
Given this is the most-used bitcoin client, I think it's about time that instructions existed so that the average non-I.T. person can buy bitcoins and store them sufficiently safely from theft. Bitcoin is still being adopted mostly by I.T. professionals, and it's surely time that it become available to the wider population. For this to happen, there needs to be a "storing bitcoin safely for dummies" sort of document - and associated software changes to automate this as much as possible.

**Comment by laanwj** [comment]
The documentation available improved a lot since 2013. Not so much as part of bitcoin core source repository, but certainly in the rest of the ecosystem. I don't think it is useful to keep this issue open.
