### ISSUE TITLE
rpc: getnetworkinfo subversion has spurious trailing 0

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#23615]
Reported by @k9ert: https://github.com/cryptoadvance/specter-desktop/pull/1482#discussion_r756783512

Confirmed on the 22.0x branch:

```
bitcoin-cli getnetworkinfo
{
  "version": 220000,
  "subversion": "/Satoshi:22.0.0/",
...
```

cc @achow101

**Comment by ComplaintID** [comment]
Message them on Twitter about your complaints. Send them a direct message to get your issues resolved. I also had the same issues. 
https://twitter.com/messages/compose?recipient_id=884210741347332100

**Comment by MarcoFalke** [comment]
This should be the build id, which is always displayed now for clarity?

**Comment by MarcoFalke** [comment]
At some point someone asked the same thing about the `--version`, but I can't find the thread.

Cf.

```
$ bitcoin-core.cli --version 
Bitcoin Core RPC client version v22.0.0

**Comment by laanwj** [comment]
I'm not sure it is spurious. It's padded to have all the potential version numbers. In the past we had four-number versions in some cases (e.g. a small platform-specific update) so wouldn't entirely rule out an e.g. `23.0.1`.

**Comment by Sjors** [comment]
I guess if it's intentional then it's not a bug. The binary archive name can always be derived from the `version` field instead, if you know the rules. Or we could add yet another result to this RPC like `version_rounded`.

**Comment by MarcoFalke** [comment]
The binary name could also be changed to include the build id?

**Comment by Sjors** [comment]
I stopped caring :-)
