### ISSUE TITLE
Calling `upgradewallet` on a legacy wallet causes Bitcoin Core to crash

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#23610]
I have 2 legacy wallets and on both if I run `upgradewallet` it will cause bitcoin core to crash. This should just return me an error string

Currenl result from `getwalletinfo`:
```
{
  "walletname": "Wallet",
  "walletversion": 169900,
  "format": "bdb",
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 80,
  "keypoololdest": 1613078825,
  "keypoolsize": 941,
  "keypoolsize_hd_internal": 941,
  "paytxfee": 0.00000000,
  "private_keys_enabled": false,
  "avoid_reuse": true,
  "scanning": false,
  "descriptors": false
}
```

**Comment by MarcoFalke** [comment]
Can you run this in valgrind or gdb to get a stack trace? Also, which version of Bitcoin Core?

**Comment by benthecarman** [comment]
> Can you run this in valgrind or gdb to get a stack trace? Also, which version of Bitcoin Core?

version is 22.0

**Comment by ComplaintID** [comment]
Message them on Twitter about your complaints. Send them a direct message to get your issues resolved. I also had the same issues.
https://twitter.com/messages/compose?recipient_id=884210741347332100

**Comment by achow101** [comment]
Do you have a backup of the wallets? If so, can you load them and do `getwalletinfo`?

**Comment by benthecarman** [comment]
Only logs I get is
```
2021-12-21T16:13:24Z [Wallet] Performing wallet upgrade to 169900
2021-12-21T16:13:24Z [Wallet] Upgrading wallet to HD
```

this is a watch only wallet so that may be the case
