### ISSUE TITLE
i feel like a failure

### ISSUE THREAD

**Issue by petjal** [bitcoin/bitcoin#23623]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/3526136/143797422-408c76ae-0f69-4931-a9e1-49cb7361d2f4.png)

Logs are full of various kinds of "fail".  I'm a beginner.  Is this thing working at all?  Am I wasting my and everyone else's time?  I'm probably doing something wrong.  If not, perhaps it would be nice if the logs said something to the effect that "all is reasonably good". 

**Describe the solution you'd like**

Perhaps it would be nice if the logs periodically said something to the effect that "all is reasonably good.  You have some node-connectivity failures, but this level of those is to be expected.". 
Or indicate some of those fails as INFO.
Or for each kind of "fail", add a link to an explainer. 
Or, catch that error; test if have enough good connections; if enough, say INFO OK; if not, throw ERROR. 
Something like that. 

**Describe alternatives you've considered**

Ethereum.   (Just kidding.)

**Additional context**

Note, I'm not looking for any feedback on these errors.  I'll google them and figure it out.

**Comment by prayank23** [comment]
> Ethereum. (Just kidding.)
Note, I'm not looking for any feedback on these errors. I'll google them and figure it out.

Why did you create the issue?

**Comment by petjal** [comment]
The logs have a high preponderance of "fail". This new person thinks those are probably spurious.  The Feature Request was to periodically log some indicator of relative health of the node.
