### ISSUE TITLE
Discussion: Improving the current source code to support full cross-platform.

### ISSUE THREAD

**Issue by KambizAsadzadeh** [bitcoin/bitcoin#23669]
### Hello friends,
Depending on the current source, it is possible to get output for different platforms in a responsive mode!

- I know you have worked hard and this is admirable. In my opinion, we need to improve the bitcoin wallet, especially the user interface part.
- I know that the C++ community has a great deal of expertise in this area and can provide the best output for the bitcoin community that it deserves!

**Therefore, we can work together to improve it as much as possible, and I, as a member of C++ community, have some suggestions:**

1. Reviewing and Redesigning the codes of the bitcoin core wallet, especially the UI and improving the UX according to [this process](https://github.com/BitcoinDesign/Bitcoin-Core-App).
2. Reviewing and improving the modern user interface in a completely responsive way for desktop, mobile and even web assembly platforms in the future! According to [this discuss](https://github.com/bitcoin-core/gui-qml) based on Qt Quick technology.
3. This [concept of design](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App-Main?node-id=1035%3A1883) designed by friends is very admirable and we can start developing it based on QML according to this concept. I prefer a single implementation of components for cross-platform and responsive UI. It is a better choice because:

**This offer has advantages:**
- Fast and comprehensive updates.
- Fast improvement and avoiding waste of time on multi-platform development
- Providing stable and reliable output on all platforms.

4. Adding support for CMake tool as a fast and reliable tool. Build with CMake. Build with Confidence ([CMake](https://cmake.org/) slogan!). It helps us to provide fast and synchronized output on target platforms.
5. Upgrading Interface codes to Qt6 and also core codes to C++20 in the future as a goal.
6. It is important for me to pay attention to the support of new technologies such as web assembly (WASM).

At last, I thank my friends for their valuable efforts and hope that I can contribute to improve the project.

_**Sincerely Kambiz!**_

**Comment by hebasto** [comment]
> **Therefore, we can work together to improve it as much as possible, and I, as a member of C++ community, have some suggestions:**
> 
>     1. Reviewing and Redesigning the codes of the bitcoin core wallet, especially the UI and improving the UX according to [this process](https://github.com/BitcoinDesign/Bitcoin-Core-App).
> 
>     2. Reviewing and improving the modern user interface in a completely responsive way for desktop, mobile and even web assembly platforms in the future! According to [this discuss](https://github.com/bitcoin-core/gui-qml) based on Qt Quick technology.
> 
>     3. This [concept of design](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App-Main?node-id=1035%3A1883) designed by friends is very admirable and we can start developing it based on QML according to this concept. I prefer a single implementation of components for cross-platform and responsive UI. It is a better choice because:

Did you see https://github.com/bitcoin-core/gui-qml/blob/main/src/qml/README.md? Please join us :)

**Comment by KambizAsadzadeh** [comment]
> > **Therefore, we can work together to improve it as much as possible, and I, as a member of C++ community, have some suggestions:**
> > ```
> > 1. Reviewing and Redesigning the codes of the bitcoin core wallet, especially the UI and improving the UX according to [this process](https://github.com/BitcoinDesign/Bitcoin-Core-App).
> > 
> > 2. Reviewing and improving the modern user interface in a completely responsive way for desktop, mobile and even web assembly platforms in the future! According to [this discuss](https://github.com/bitcoin-core/gui-qml) based on Qt Quick technology.
> > 
> > 3. This [concept of design](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App-Main?node-id=1035%3A1883) designed by friends is very admirable and we can start developing it based on QML according to this concept. I prefer a single implementation of components for cross-platform and responsive UI. It is a better choice because:
> > ```
> 
> Did you see https://github.com/bitcoin-core/gui-qml/blob/main/src/qml/README.md? Please join us :)

Yes, I have seen this repository before and I'll take steps to improve it.

> EDIT: The QML repo has a common commit history with this repo, and, therefore, it can be merged in whenever it is considered useful.

Okay.

And what is your idea about other suggestion @hebasto? 

>4. Adding support for CMake tool as a fast and reliable tool. Build with CMake. Build with Confidence (CMake slogan!). It helps us to provide fast and synchronized output on target platforms.
>5. Upgrading Interface codes to Qt6 and also core codes to C++20 in the future as a goal.
>6. It is important for me to pay attention to the support of new technologies such as web assembly (WASM).

**Comment by hebasto** [comment]
> And what is your idea about other suggestion @hebasto?
> 
> > 4. Adding support for CMake tool as a fast and reliable tool. Build with CMake. Build with Confidence (CMake slogan!). It helps us to provide fast and synchronized output on target platforms.

Our build system, which is based on the Autotools, works just fine. There are should be very compelling reasons to move from Autotools to CMake.

> > 5. Upgrading Interface codes to Qt6 and also core codes to C++20 in the future as a goal.

Yes, in the future. Also see #23363.

> > 6. It is important for me to pay attention to the support of new technologies such as web assembly (WASM).

I know nothing about WASM.

**Comment by fanquake** [comment]
Thanks, however I don't think there's much value in keeping this issue open. It's a collection of generic points/improvements, most of which are already being worked on, or which have their own tracking issues.
