### ISSUE TITLE
Consider reducing 'getblocks' limit below 500

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#2368]
500 blocks is quite a lot of data.  I wonder if we shouldn't target a byte size rather than block count, between requests.  e.g. 32MB or somesuch.

**Comment by dcousens** [comment]
@laanwj no longer an issue?

**Comment by sipa** [comment]
"getblocks" is no longer user in headers-first sync. And the results of
"getheaders" (2000 at once!) are dealt with differently.

**Comment by dcousens** [comment]
Thanks @sipa

**Comment by laanwj** [comment]
This issue confused me: 'getblocks' returns 'invs', not actual block data. The problem was always in how we handled block invs, not so much getblocks itself. But as @sipa says, that too has been solved with the new mechanism.
