### ISSUE TITLE
Cannot build v22 on Ubuntu 20.04

### ISSUE THREAD

**Issue by ludirium** [bitcoin/bitcoin#23746]
Hello there I'm getting an error when trying to build the bitcore v22 repo.

I run 
`export BDB_PREFIX='/home/ubuntu/bitcoin/db4' && ./autogen.sh && ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" CXXFLAGS="-O0" --with-gui=no && make `

After installing all unix dependencies as stated in docs.

`
..
  CXX      leveldb/util/libleveldb_a-filter_policy.o
  CXX      leveldb/util/libleveldb_a-hash.o
  CXX      leveldb/util/libleveldb_a-histogram.o
  CXX      leveldb/util/libleveldb_a-logging.o
  CXX      leveldb/util/libleveldb_a-options.o
  CXX      leveldb/util/libleveldb_a-status.o
  CXX      leveldb/util/libleveldb_a-env_posix.o
  AR       leveldb/libleveldb.a
  CXX      crc32c/src/libcrc32c_a-crc32c.o
  CXX      crc32c/src/libcrc32c_a-crc32c_portable.o
  AR       crc32c/libcrc32c.a
  CXX      crc32c/src/libcrc32c_sse42_a-crc32c_sse42.o
  AR       crc32c/libcrc32c_sse42.a
  CXX      leveldb/helpers/memenv/libmemenv_a-memenv.o
  AR       leveldb/libmemenv.a
make[3]: Entering directory '/home/ubuntu/bitcoin/src/secp256k1'
gcc -I. -I./src -O2 -fvisibility=hidden -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-unused-function -Wno-long-long -Wno-overlength-strings -W -g -c src/gen_context.c -o gen_context.o
gcc -O2 -fvisibility=hidden -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-unused-function -Wno-long-long -Wno-overlength-strings -W -g  gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[3]: Leaving directory '/home/ubuntu/bitcoin/src/secp256k1'
  CXXLD    bitcoind
  CXX      bitcoin_cli-bitcoin-cli.o
  CXX      compat/libbitcoin_cli_a-stdin.o
compat/stdin.cpp: In function ‘bool StdinTerminal()’:
compat/stdin.cpp:52:12: error: ‘ikenty’ was not declared in this scope
   52 |     return ikenty(fileno(stdin));
      |            ^~~~~~
make[2]: *** [Makefile:8021: compat/libbitcoin_cli_a-stdin.o] Error 1
make[2]: Leaving directory '/home/ubuntu/bitcoin/src'
make[1]: *** [Makefile:16202: all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/bitcoin/src'
make: *** [Makefile:821: all-recursive] Error 1

`

Not sure if anyone else is having this issue or knows how to get past it, thank you!

**Comment by hebasto** [comment]
@ludirium 

What is your `./configure` output?
