### ISSUE TITLE
Cannot make deploy Mac OS dmg

### ISSUE THREAD

**Issue by guyeatspants** [bitcoin/bitcoin#23754]
Hello there everyone i am trying to make deploy the Bitcoin Core wallet, and it looks as if it's almost there but i came across a python error.  Any help would be appreciated all packages and dependencies installed

>   CXX      script/libbitcoinconsensus_la-script_error.lo
>   CXX      libbitcoinconsensus_la-uint256.lo
>   CXX      util/libbitcoinconsensus_la-strencodings.lo
>   CXXLD    libbitcoinconsensus.la
> Making all in doc/man
> make[1]: Nothing to be done for `all'.
> make[1]: Nothing to be done for `all-am'.
> /usr/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/MacOS
> STRIPPROG="/usr/bin/strip" /bin/sh /Users/alex/bitcoin/build-aux/install-sh -c -s  ./src/qt/bitcoin-qt Bitcoin-Qt.app/Contents/MacOS/Lu-Qt
> /usr/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/Resources/Base.lproj
> echo '{	CFBundleDisplayName = "Bitcoin Core"; CFBundleName = "Bitcoin Core"; }' > Bitcoin-Qt.app/Contents/Resources/Base.lproj/InfoPlist.strings
> sed 's/PACKAGE_NAME/Bitcoin Core/' < "contrib/macdeploy/background.svg" | /usr/local/bin/rsvg-convert -f png -d 36 -p 36 -o background.tiff.png
> sed 's/PACKAGE_NAME/Bitcoin Core/' < "contrib/macdeploy/background.svg" | /usr/local/bin/rsvg-convert -f png -d 72 -p 72 -o background.tiff@2x.png
> tiffutil -cathidpicheck background.tiff.png background.tiff@2x.png -out background.tiff
> 2 images written to background.tiff.
> /usr/local/bin/python3.9 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app Bitcoin-Core -translations-dir= -dmg
> + Copying source bundle +
> + Deploying frameworks +
> Processing libboost_filesystem.dylib ...
> Processing QtNetwork.framework ...
> Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/Current -> 5
> Processing QtCore.framework ...
> Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtCore.framework/Versions/Current -> 5
> Processing QtWidgets.framework ...
> Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/Current -> 5
> Processing QtGui.framework ...
> Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtGui.framework/Versions/Current -> 5
> Processing QtDBus.framework ...
> Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/Current -> 5
> Processing libqrencode.4.dylib ...
> Processing libdb_cxx-4.8.dylib ...
> Processing libminiupnpc.17.dylib ...
> Processing libnatpmp.1.dylib ...
> Processing libevent_pthreads-2.1.7.dylib ...
> Processing libevent-2.1.7.dylib ...
> Processing libsqlite3.0.dylib ...
> Processing QtCore.framework ...
> Processing QtGui.framework ...
> + Deploying plugins +
> Processing plugin platforms/libqminimal.dylib ...
> Processing plugin platforms/libqcocoa.dylib ...
> Processing QtPrintSupport.framework ...
> Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current -> 5
> Processing plugin styles/libqmacstyle.dylib ...
> + Adding Qt translations +
> + Installing qt.conf +
> + Generating .DS_Store +
> Traceback (most recent call last):
>   File "/Users/alex/bitcoin/./contrib/macdeploy/macdeployqtplus", line 530, in <module>
>     alias = Alias().from_bytes(icvp['backgroundImageAlias'])
>   File "/usr/local/lib/python3.9/site-packages/mac_alias/alias.py", line 377, in from_bytes
>     return cls._from_fd(b)
>   File "/usr/local/lib/python3.9/site-packages/mac_alias/alias.py", line 363, in _from_fd
>     alias.volume.disk_image_alias = Alias.from_bytes(value)
>   File "/usr/local/lib/python3.9/site-packages/mac_alias/alias.py", line 377, in from_bytes
>     return cls._from_fd(b)
>   File "/usr/local/lib/python3.9/site-packages/mac_alias/alias.py", line 322, in _from_fd
>     alias.target.folder_name = value.decode().replace('/',':')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 5: invalid start byte

Thank you

**Comment by hebasto** [comment]
@diagraphic 

Is your hardware based on Intel or Apple Silicon?
What is your macOS version exactly?
Did you use `make -C depends` or Homebrew to get dependency packages?

**Comment by diagraphic** [comment]
2.6 GHz Dual-Core Intel Core i5
10.15.7

**Comment by hebasto** [comment]
hmm, cannot reproduce on my macOS 10.15.7 (19H1519).

**Comment by diagraphic** [comment]
Still got the same error after trying to compile the dmg.

**Comment by diagraphic** [comment]
Mac OS 10.15.7 19H1323

**Comment by diagraphic** [comment]
@hebasto what version of python do you have on your system?

I have 3.9

**Comment by hebasto** [comment]
> @hebasto what version of python do you have on your system?
> 
> I have 3.9

```
% python3 --version
Python 3.9.9
```

**Comment by hebasto** [comment]
@diagraphic 

Could you try to `make deploy` for commits 1a9fa4c5ba27f5e32b547a77264ca0d4462bd168 and 16b31cc4c516cdcaf6d2eb2dd1255cc3e6973ba1 to figure out if the problem has been introduced in #20422?

**Comment by diagraphic** [comment]
@hebasto Absolutely.

**Comment by diagraphic** [comment]
Seems as if even though i had that error, the DMG was actually created, syncing and everything is looking fine.  Odd.

**Comment by RandyMcMillan** [comment]
@hebasto - this PR should be closed.
