### ISSUE TITLE
allow positional and named arguments in `bitcoin-cli`

### ISSUE THREAD

**Issue by antonilol** [bitcoin/bitcoin#23786]
**Is your feature request related to a problem? Please describe.**
`bitcoin-cli sendtoaddress "bc1q09vm5lfy0j5reeulh4x5752q25uqqvz34hufdl" 0.1 "" "" true false 0 unset true 1 true`
or
`bitcoin-cli -named sendtoaddress address="bc1q09vm5lfy0j5reeulh4x5752q25uqqvz34hufdl" amount=0.1 verbose=true`
?

**Describe the solution you'd like**
`bitcoin-cli sendtoaddress bc1q09vm5lfy0j5reeulh4x5752q25uqqvz34hufdl 0.1 verbose=true`

add the ability to use positional and named arguments in one rpc call

**Comment by achow101** [comment]
See #19762

**Comment by pablomartin4btc** [comment]
@antonilol, have you seen #19762? do you still have this issue?

**Comment by antonilol** [comment]
i think this resolved this issue, but it got merged after 24.x was split off, so i cant test it right now on the v24.0.1 i have running
closing for now because the bitcoin-cli commands mentioned in that pr look good to me
