### ISSUE TITLE
qt, wallet: wallet does not lock after first send

### ISSUE THREAD

**Issue by willyko** [bitcoin/bitcoin#23790]
QT wallet does not lock the wallet after initial send.

**Expected behavior**

In Bitcoin Core 22.0, using the bitcoin-qt, password prompt shows up every time you click "Send"

**Actual behavior**

In current master branch latest (c09b41), using a self-compiled bitcoin-qt, after entering password to send once, subsequent "Send" no longer requires a password

**To reproduce**

1. Pull master branch latest (or c09b41dc665bcc7d6dcc464f1d279e8eca598c8d).  
2. Compiled with qt option and run bitcoin-qt in regtest mode.
3. Create an encrypted wallet and mine some blocks for test funds
4. Using the send tab in qt, enter any address and any amount and then click "Send".  Password prompt should show up.
5. Enter password and click "Ok".  The prompt disappears and nothing happens. (This is also a different behavior than expected)
6. Click on "Send" again and the review transaction prompt shows up.  
7. Click on "Sign and Send" to complete this transaction.
8. Now, using the send tab and attempt to "Send" again will show the review transaction prompt instantly instead of showing the password prompt.  Clicking on "Sign and Send" can also complete this transaction successfully.

**System information**

Self-compiled master branch
```
commit c09b41dc665bcc7d6dcc464f1d279e8eca598c8d (HEAD -> master, origin/master, origin/HEAD)
Merge: b8cc75435 faf2614f6
Author: MarcoFalke <falke.marco@gmail.com>
Date:   Wed Dec 15 16:10:17 2021 +0100
```

Tested on MacOS 11.6

**Comment by achow101** [comment]
Are you able to do a `git bisect` to identify what commit caused this change?

**Comment by willyko** [comment]
> Are you able to do a `git bisect` to identify what commit caused this change?

Yes.  This is what I got
```
7fa91e831227e556bd8a7ae3da64bd59d4f30d5f is the first bad commit
```
7fa91e831227e556bd8a7ae3da64bd59d4f30d5f

**Comment by hebasto** [comment]
@willyko 

Thank you for reporting this regression!

A fix has been suggested in https://github.com/bitcoin-core/gui/pull/509.
