### ISSUE TITLE
Improve Test Framework Time With Run Order Directive

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#23808]
If you could leave a directive in one of the commits in your tree, e.g.

```
> run-priority: feature_blah.py
```

and we could use that to instruct the CI to run that test _first_, that would be pretty helpful in speeding up CI if there's a particular e.g. new or impacted test that should see failures before others.

It won't help with passing, but it could help with 'fail fast'.

**Comment by MarcoFalke** [comment]
If you write a new test or modify one, the fastest way to get a result is to run the test locally. No objection, but I am also dubious that this feature will be used/useful (if ever implemented).

**Comment by JeremyRubin** [comment]
looks like limited interest given a closed pr, closing.
