### ISSUE TITLE
Bitcoin core error after disabling block chain pruning and then restarting the application,  error:opening block database

### ISSUE THREAD

**Issue by nuketown3** [bitcoin/bitcoin#23816]
I have attempted to turn of block chain pruning in the options menu, which has required the application to restart.
When I have restarted the application I'm faced with this error message and then the program closes.

This now happens every time I open the application and wont load to the wallet, It also persists even after I uninstall the entire bitcoin core and re install the bit coin core program and when I go to initial launch the program this again pops up. 

Was working previous but with a pruned block  chain and had no problems, but as soon as I went to options and disabled block chain pruning this was the resulting error I received.

"you need to rebuild the data base using -reindex to go back to unpruned mode. This will redownload the entire blockchain. 
do you want to rebuild the block database now?

ok

error:opening block database

ok 

program closes"

If someone knows what I can do to fix this, many thanks

**Comment by Davidson-Souza** [comment]
Did you start core with `-reindex=1`?

**Comment by hebasto** [comment]
Is it the same as #22964?

**Comment by Dog-Pack** [comment]
> Did you start core with `-reindex=1`?

I had the same issue goggled, it found this thread tried the above and then it started ok.


and yes i believe its the same as 22964

**Comment by hebasto** [comment]
> yes i believe its the same as 22964

Could be closed as #22964 has been resolved.
