### ISSUE TITLE
ArgsManager::GetIntArg should error on out-of-bounds value

### ISSUE THREAD

**Issue by jamesob** [bitcoin/bitcoin#23843]
Currently, if an out-of-bounds value for the underlying `int64_t` type is passed to `ArgsManager::GetIntArg()` (e.g. `-maxtipage=9999999999999999`), the returned value will silently saturate (similar to [the specification of `strtoll()`](https://man7.org/linux/man-pages/man3/strtol.3.html)). Instead it would be better to detect this out-of-range value and throw an `InitError` during initialization, explicitly warning the user.

See also: https://github.com/bitcoin/bitcoin/pull/23841

#### Useful skills:

Basic C++

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
See also #17385 (stale)

**Comment by jamesob** [comment]
Instead of throwing an error immediately, it would probably be good to print a deprecation message for one release.

**Comment by vincenzopalazzo** [comment]
if there is no one that are working on it, I can work on that

**Comment by luke-jr** [comment]
Concept NACK. It's a pain to specify max values exactly. It should remain valid to just set `=999999999999` and not worry about the specifics.

**Comment by jamesob** [comment]
> Concept NACK. It's a pain to specify max values exactly. It should remain valid to just set `=999999999999` and not worry about the specifics.

FWIW, I agree. I'll close the issue unless anyone feels differently.
