### ISSUE TITLE
udefined reference to SignatureHashSchnorr

### ISSUE THREAD

**Issue by techy2** [bitcoin/bitcoin#23856]
> 

> 

building from GIT source failure occurs in downloaded TAR file
as well as GIT pull and build 22.x branch

expected successful build

  CXXLD    bitcoin-tx
libbitcoin_common.a(libbitcoin_common_a-sign.o): In function `MutableTransactionSignatureCreator::CreateSchnorrSig(SigningProvider const&, std::vector<unsigned char, std::allocator<unsigned char> >&, XOnlyPubKey const&, uint256 const*, uint256 const*, SigVersion) const':
sign.cpp:(.text+0x220d): undefined reference to `bool SignatureHashSchnorr<CMutableTransaction>(uint256&, ScriptExecutionData const&, CMutableTransaction const&, unsigned int, unsigned char, SigVersion, PrecomputedTransactionData const&, MissingDataBehavior)'
collect2: error: ld returned 1 exit status
Makefile:5270: recipe for target 'bitcoin-tx' failed
make[2]: *** [bitcoin-tx] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/master/gitrepo/bitcoin/src'
Makefile:15532: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/master/gitrepo/bitcoin/src'
Makefile:821: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

happens exactly the same every time 

git clone https://github.com/bitcoin/bitcoin
cd bitcoin/depends
make
(is successful)
cd ../
./autogen.sh
./configure --enable-glibc-back-compat --prefix=$(pwd)/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++" --enable-cxx --enable-static --disable-shared --disable-debug --disable-tests --disable-bench --with-pic CPPFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" CXXFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768"

make -j3
produces error above every time
looks to me like there is a dependency missing
did you forget to put the Schnorr library in "depends"?

24 core Xeon + 192GB memory, 1T managed high speed disk array
4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

no GUI issues

All previous versions for the last couple of years have built successfully
many other coins both dash based and pivx based build successfully, only this particular distro has a problem.

configuration log from this build
[config.log](https://github.com/bitcoin/bitcoin/files/7772062/config.log)

**Comment by achow101** [comment]
This is an issue with your build environment. `SignatureHashSchnorr` is a function within this project itself and others do not experience this issue.

Are you building with a clean repo every time or are build artifacts from earlier builds still present?

Try doing `make clean` before `make -j3`.

**Comment by MarcoFalke** [comment]
I can reproduce on a fresh install of Ubuntu Bionic:

`( cd depends && make -j $(nproc) ) &&  ./autogen.sh && ./configure --enable-glibc-back-compat --prefix=$(pwd)/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++" --enable-cxx --enable-static --disable-shared --disable-debug --disable-tests --disable-bench --with-pic CPPFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" CXXFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" && make -j $(nproc)`


```
  CXX      crc32c/src/crc32c_libcrc32c_a-crc32c.o
  CXX      crc32c/src/crc32c_libcrc32c_a-crc32c_portable.o
  AR       crc32c/libcrc32c_sse42.a
  CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
  AR       libbitcoin_cli.a
  GEN      qt/bitcoinamountfield.moc
  AR       libbitcoin_wallet_tool.a
  GEN      qt/intro.moc
  GEN      qt/overviewpage.moc
  GEN      qt/rpcconsole.moc
  GEN      qt/qrc_bitcoin_locale.cpp
  CXXLD    libbitcoinconsensus.la
  AR       libbitcoin_server.a
  AR       libbitcoin_util.a
  AR       libbitcoin_zmq.a
  AR       crc32c/libcrc32c.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    bitcoin-cli
  CXXLD    bitcoin-tx
  CXXLD    bitcoin-util
  CXX      qt/qt_bitcoin_qt-main.o
libbitcoin_common.a(libbitcoin_common_a-sign.o): In function `MutableTransactionSignatureCreator::CreateSchnorrSig(SigningProvider const&, std::vector<unsigned char, std::allocator<unsigned char> >&, XOnlyPubKey const&, uint256 const*, uint256 const*, SigVersion) const':
sign.cpp:(.text+0x220d): undefined reference to `bool SignatureHashSchnorr<CMutableTransaction>(uint256&, ScriptExecutionData const&, CMutableTransaction const&, unsigned int, unsigned char, SigVersion, PrecomputedTransactionData const&, MissingDataBehavior)'
collect2: error: ld returned 1 exit status
Makefile:5270: recipe for target 'bitcoin-tx' failed
make[2]: *** [bitcoin-tx] Error 1
make[2]: *** Waiting for unfinished jobs....
  CXX      qt/qt_libbitcoinqt_a-bantablemodel.o
make[2]: Leaving directory '/bitcoin-core/src'
Makefile:15532: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/bitcoin-core/src'
Makefile:821: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by MarcoFalke** [comment]
```
git log -1 --oneline
56156a1f0 (HEAD -> 22.x, origin/22.x) Merge bitcoin/bitcoin#23315: [22.x] build: explicitly disable libsecp256k1 openssl based tests

**Comment by MarcoFalke** [comment]
Likely a compiler bug

**Comment by MarcoFalke** [comment]
You can fix this by replacing O3 with O2

**Comment by MarcoFalke** [comment]
Alternatively you can use a compiler (version) that doesn't have this bug

**Comment by techy2** [comment]
Changed optimization to O2 and got exactly the same error

**Comment by techy2** [comment]
g++ version 7.50 from ubuntu 18.04 distro repository

**Comment by hebasto** [comment]
@techy2 

Does this patch
```diff
--- a/src/script/sign.cpp
+++ b/src/script/sign.cpp
@@ -9,6 +9,7 @@
 #include <key.h>
 #include <policy/policy.h>
 #include <primitives/transaction.h>
+#include <script/interpreter.h>
 #include <script/keyorigin.h>
 #include <script/signingprovider.h>
 #include <script/standard.h>
```
help?

**Comment by MarcoFalke** [comment]
> Changed optimization to O2 and got exactly the same error

That's odd. It was working for me yesterday. Did you run `make clean` in between?

**Comment by techy2** [comment]
don't remember, will repeat

**Comment by techy2** [comment]
don't remember if I did a make clean so removed the local repository and did a fresh pull from github
build depends
coinfigure with O2
get this error right away,
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
In file included from primitives/transaction.cpp:11:0:
./util/strencodings.h:16:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~

**Comment by techy2** [comment]
configuration command line is same as above except O2 in 2 places instead of O3

**Comment by fanquake** [comment]
> g++ version 7.50 from ubuntu 18.04 distro repository
> did a fresh pull from github
> ./util/strencodings.h:16:10: fatal error: charconv: No such file or directory

Did you forget to checkout the 22.x branch? Looks like you're now building master, and you need to use GCC 8.1 or newer to do that. See https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md.

**Comment by techy2** [comment]
build complete without errors on 22.x branch with -O2
g++ 7.50
Thanks for the help fellas
