### ISSUE TITLE
allow duplicate output addresses `createrawtransaction`

### ISSUE THREAD

**Issue by antonilol** [bitcoin/bitcoin#23877]
**Is your feature request related to a problem? Please describe.**

`Invalid parameter, duplicated address: tb1qcum5rgwvzmtfvtwk80y4zp7mv5mgg384ygfsn3`

**Describe the solution you'd like**

remove the duplicate address check or add an optional argument to remove the check

**Describe alternatives you've considered**

hex editing

**Additional context**

[40ac7fcef6a918e0c073f74cf79bb97b043f311e9f3b6e3d5067b0e6f2b6be5a](https://mempool.space/testnet/tx/40ac7fcef6a918e0c073f74cf79bb97b043f311e9f3b6e3d5067b0e6f2b6be5a)

**Comment by prayank23** [comment]
Any usecases for this feature?

**Comment by kristapsk** [comment]
I don't see any point in doing this, just unnecessary increases global UTXO set.

**Comment by antonilol** [comment]
> I don't see any point in doing this, just unnecessary increases global UTXO set.

it makes no difference when either using 2 different addresses or using 2 outputs with the same address
advantage: you only have to get 1 new address, not 2. for 2 new addresses it doesn't matter but if you needed 2000 addresses because duplicate addresses are blocked by `createrawtransaction` it costs a lot of time creating 2000 new addresses

**Comment by kristapsk** [comment]
> it makes no difference when either using 2 different addresses or using 2 outputs with the same address

Why not just sum amounts and use one TXO instead? What is the use case?

> it costs a lot of time creating 2000 new addresses

On my laptop:
```
$ time for i in $(seq 1 2000); do bitcoin-cli -signet -rpcwallet=signet getnewaddress > /dev/null; done

real	0m39,460s
user	0m9,583s
sys	0m6,962s
```

Address reuse has never been recommended practice in Bitcoin. It actually works by accident, not by design. https://en.bitcoin.it/wiki/Address_reuse

**Comment by antonilol** [comment]
`createrawtransaction` must be a tool to create a raw transaction without having to make the TX hex yourself. if multiple of the same outputs is allowed in a raw TX, why can't `createrawtransaction` do it for me?

**Comment by MarcoFalke** [comment]
Agree that there is no need to add this feature, since there is no use case

**Comment by antonilol** [comment]
> `createrawtransaction` must be a tool to create a raw transaction without having to make the TX hex yourself. if multiple of the same outputs is allowed in a raw TX, why can't `createrawtransaction` do it for me?

**Comment by Thanayaby** [comment]
Off want min you're

**Comment by antonilol** [comment]
> Off want min you're

?
