### ISSUE TITLE
Error while windows build.

### ISSUE THREAD

**Issue by geranium-coin** [bitcoin/bitcoin#23930]
root@geraniumd:~/bitcoin# make deploy
CXXLD    bitcoind.exe
/usr/bin/x86_64-w64-mingw32-ld: /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/../../../../x86_64-w64-mingw32/lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
./build/x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:5949: bitcoin.exe] Error 1
make[2]: Leaving directory '/root/bitcoin/src'
make[1]: *** [Makefile:16202: all-recursive] Error 1
make[1]: Leaving directory '/root/bitcoin/src'
make: *** [Makefile:821: all-recursive] Error 1
root@geraniumd:~/bitcoin# make dep                                  make: *** No rule to make target 'dep'.  Stop.

Having such error.

**Comment by MarcoFalke** [comment]
What are the steps to reproduce on a fresh system?
