### ISSUE TITLE
importprivkey - This type of wallet does not support this command

### ISSUE THREAD

**Issue by ethermachine** [bitcoin/bitcoin#23946]
When I run importprivkey it returns unsupported wallet instead of importing. Code:

bitcoin-cli importprivkey "priv_key" "label" false
error code: -4
error message:
**This type of wallet does not support this command**

Version
bitcoin-cli -version
**Bitcoin Core RPC client version v22.99.0-9d099b02d8f0**

Node fully synced (full node)
Chain: main
Blocks: 716934
Headers: 716934
Verification progress: 99.9999%
Difficulty: 24272331996979.97

![image](https://user-images.githubusercontent.com/75843061/147893495-3d5724ab-f727-44f8-8451-9d027e9d6a08.png)

**Comment by achow101** [comment]
This occurs when your wallet is a descriptor wallet. It is expected behavior.

**Comment by gologo13** [comment]
Hi there, I came across the same error. With legacy wallets, I can get UTXOs of watch_only addresses from `listunspent` after executing `importaddress`, but how can I get balances using descriptors.
sorry, I know this could be a different topic, but I hope someone could answer my question.

**Comment by achow101** [comment]
@gologo13 Create descriptors for your addresses and import them with `importdescriptors`.
