### ISSUE TITLE
Crash while keypoolrefill is running

### ISSUE THREAD

**Issue by Belkaar** [bitcoin/bitcoin#2394]
with an encyrpted wallet my client (0.8.1 compiled myself) crashes, if the walletpassphrase timeout occurs before the keypoolrefill has finished.
It just closes, no error/crash log messages. The last line in the log is one of these:

keypool added key 100, size=100

to reproduce do
bitcoind walletpassphrase pass 10 && bitcoind keypoolrefill on a machine with no cpu cycles to spare at the moment

**Comment by laanwj** [comment]
Thanks for the offer, but I don't have time to dive deep into berkeleydb specifics.

For anyone else coming to this issue, what may work is to run with the option `-salvagewallet`. This dumps the underlying database structure and rebuilds the wallet. Do make sure that you back up your wallet first, as with any every recovery tool) it may make things worse as well.
