### ISSUE TITLE
test_runner.py issue

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#23990]
https://github.com/bitcoin/bitcoin/pull/23799/files?w=1#r779568858

**Comment by sogoagain** [comment]
Hello, I think it can be solved by adding logic to check if 'job_queue' is empty in the outer loop conditional statement. Would it be okay if I fix it and create a pr?

**Comment by MarcoFalke** [comment]
@sogoagain Have you seen #23995?

**Comment by sogoagain** [comment]
> @sogoagain Have you seen #23995?

Oh, I am sorry I missed this PR. Thank you. Have a nice day. :)

**Comment by MarcoFalke** [comment]
No worries. If you feel confident, you may review the pull request.
