### ISSUE TITLE
missing transactions bitcoin core 22

### ISSUE THREAD

**Issue by blockchainbitcoin** [bitcoin/bitcoin#24000]
I have a wallet and I miss transactions from 2019 2021 2021 ..

bitcoin core 22

disagree balance bitcoin core 22

**Comment by fanquake** [comment]
This issue tracker is for technical issues related only to Bitcoin Core, and should not be used for general questions / support. You might want to try the [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) instead.
