### ISSUE TITLE
Can't Unlock Bitcoin Wallet With Correct Password 

### ISSUE THREAD

**Issue by David67821** [bitcoin/bitcoin#24015]
I encrypted my wallet. used special characters in the password. And now the password doesn't work (exactly correct). Maybe the problem is in special characters?

the first character of the password is - !
and the body of the password contains - ~

**Comment by MarcoFalke** [comment]
What software are you using to send the password to Bitcoin Core? You may have to quote the string with `'`s.

**Comment by David67821** [comment]
used Bitcoin Core 0.21.1

**Comment by MarcoFalke** [comment]
The GUI, the CLI, or the RPC with a third party software?

**Comment by David67821** [comment]
The GUI, the CLI

**Comment by MarcoFalke** [comment]
I can neither reproduce with the GUI, nor the CLI on current master.

```
./bitcoin-cli walletpassphrase  '!a~b' 1
```

works for me.

How did you set the passphrase and how did you verify that it was set correctly?

**Comment by David67821** [comment]
> ./bitcoin-cli walletpassphrase  '!a~b' 1

did on command line, reports:
error: Could not connect to the server 127.0.0.1:8332 (error code 1 - "EOF reached")
Make sure the bitcoind server is running and that you are connecting to the correct RPC port.


> How did you set the passphrase and how did you verify that it was set correctly?
copy - paste

**Comment by David67821** [comment]
after running bitcoind.exe
reports:
C:\Program Files\Bitcoin8\daemon>bitcoin-cli walletpassphrase  '!xxxx~xxxxx' 1
error code: -15
error message:
Error: running with an unencrypted wallet, but walletpassphrase was called.

**Comment by MarcoFalke** [comment]
>  Error: running with an unencrypted wallet, but walletpassphrase was called.

The error says you are running with an unencrypted wallet
