### ISSUE TITLE
RPC generateblock doesn't mine a block

### ISSUE THREAD

**Issue by ghostcompute** [bitcoin/bitcoin#24027]
Here's what the Bitcoin generateblock RPC  documentation says.

_Mine a block with a set of ordered transactions immediately to a specified address or descriptor (before the RPC call returns)_

_Argument #1
The address or descriptor to send the newly generated bitcoin to._

https://developer.bitcoin.org/reference/rpc/generateblock.html

I deployed a full node, downloaded the entire Blockchain and sent a generateblock request with 1 transaction from getrawmempool to avoid sorting issues.

The generic error was "Failed to make a block" and the Bitcoin wasn't sent.

I also made a video of the bug.

https://www.tiktok.com/@ghostcompute/video/7051701541996268846?sender_device=mobile&sender_web_id=7042509351429473798&is_from_webapp=v1&is_copy_url=0

**Comment by sipa** [comment]
generatetoblock is an RPC for testing purposes. It is only expected to reliably work on test networks.

On the actual Bitcoin network, BTC cannot be mined using commodity hardware, and Bitcoin Core does not support doing so. You need custom hardware (called ASICs) to do that.

**Comment by ghostcompute** [comment]
@sipa The documentation doesn't say it's for testing and the transactions are already confirmed in the mempool.

There seems to be nothing to test with generateblock, especially since the error messages are generic with multiple points of failure in GenerateBlock().

https://github.com/bitcoin/bitcoin/blob/master/src/rpc/mining.cpp#L112

**Comment by sipa** [comment]
Fair point, it's not clear from the RPC documentation. I've opened https://github.com/bitcoin/bitcoin/pull/24028 to improve it.

To be clear: what this RPC does is perform 1000000 attempts at creating a valid block. If it can't succeed with that, it returns an error. It "works" perfectly fine on mainnet too, it's just an incredible waste of time to try. You'd need 171 trillion calls on average to this RPC on average to construct a block.

**Comment by ghostcompute** [comment]
> To be clear: what this RPC does is perform 1000000 attempts at creating a valid block. If it can't succeed with that, it returns an error. It "works" the same way on mainnet too, it's just an incredible waste of time to try. You'd need 171 trillion calls on average to this RPC on average to construct a block at the current difficulty.

That makes sense, but it seems that ShutdownRequested() is the reason for the error since it returns immediately with **false** without 1000000 tries.

> You won't ever mine any coins with this RPC or with PHP code, on mainnet.

Why? That's a whole lot different than saying the Bitcoin Core doesn't allow CPU mining by throwing errors in the absense of an ASIC.

This code is incredibly efficient with optimizations such as avoiding greater / less than comparisons on each iteration and decreasing memory usage with 1-digit numeric variable names.

The hard part is forming a valid block with the documentation available.

Is the RPC block submission process broken? Is mining resource usage an excuse to force proof-of-stake instead of proof-of-work? Is someone going to stop me before I mine a block? Will I win the lottery and lose interest in code? Why will I never do it?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.

**Comment by MarcoFalke** [comment]
Thanks for the report. The documentation will be updated in #24028. Though, I think general mining questions not related to the Bitcoin Core software are better answered elsewhere.
