### ISSUE TITLE
RFC: Boost Process requires boost::filesystem when compiling with mingw

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#24036]
Working on "Use std::filesystem. Remove Boost Filesystem & System" #20744, I found an unfortunate [pitfall](https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-946046666) -- `boost/process.hpp` depends on `boost::filesystem` when cross-compiling for Windows. It happens in Guix environment as well.

The goal of this issue is to discuss and find a solution to get rid of `boost::filesystem`.

**Comment by laanwj** [comment]
Is it a problem that *something* uses `boost::filesystem`? Does it conflicts with our own (non-use), or is it a lot of extra code to build? At least it could be specifically gated for the windows build.

In the longer run `boost::process` could be replaced with another library, or some own solution. It doesn't seem like rocket science though it is tricky to get right in a cross-platform way (especially windows, I guess :smile:)

**Comment by hebasto** [comment]
Cross-compiling is successful only when a build system has been configured with `--disable-external-signer`.
