### ISSUE TITLE
dbbatchsize parameter is missing from bitcoind documentation

### ISSUE THREAD

**Issue by ghostcompute** [bitcoin/bitcoin#24030]
The dbbatchsize parameter is missing from the bitcoind documentation.

Initial block download is slower and more problematic without this setting due to download batches exceeding the dbbatchsize.

Multiple connections are factored into batch size estimates, so it seems the optimal default setting is ((16 << 20) * 8) to avoid erroneously clearing batches here:

https://github.com/bitcoin/bitcoin/blob/master/src/txdb.cpp#L143

**Comment by MarcoFalke** [comment]
The option is hidden, but the documentation is there. You can find it with `-help -help-debug`.

```
./src/qt/bitcoin-qt -help -help-debug |grep -A2 dbbatchsize

**Comment by ghostcompute** [comment]
The documentation is hidden for bitcoind.

sudo bitcoind -h | grep dbbatchsize

I also suggested the default value is problematic.

> Initial block download is slower and more problematic without this setting due to download batches exceeding the dbbatchsize.

> Multiple connections are factored into batch size estimates, so it seems the optimal default setting is ((16 << 20) * 8) to avoid erroneously clearing batches here:

> https://github.com/bitcoin/bitcoin/blob/master/src/txdb.cpp#L143

Would it be wrong to document this as the recommended dbbatchsize value during initial block download?

Initial block download took about 4 days with no issues using less than the minimum required spec.
