### ISSUE TITLE
Unclear error when pkg-config is not installed

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#24037]
While running `autogen.sh` on a newly intalled debian 11.2 system, I got the following error:
```
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:16: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:261: error: possibly undefined macro: AC_DEFINE
configure.ac:662: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
The problem turned out to be that the `pkg-config` package was missing (`autoconf automake libtool` were installed). I could not guess this from the error message. It might make sense to add an explicit check to give a more specific error.

**Comment by hebasto** [comment]
Fixed in #24048.
