### ISSUE TITLE
guix time-machine: error: Git error: object not found - no match for id (fa17abf1af09570708daa28dd40ffbc932ebe25c)

### ISSUE THREAD

**Issue by psgreco** [bitcoin/bitcoin#24040]
https://github.com/bitcoin/bitcoin/pull/23778 pointed guix time machine to commit fa17abf1af09570708daa28dd40ffbc932ebe25c, which was working initially, but that commit seems to have disappeared upstream generating the following error
```
Updating channel 'guix' from Git repository at 'https://git.savannah.gnu.org/git/guix.git'...
guix time-machine: error: Git error: object not found - no match for id (fa17abf1af09570708daa28dd40ffbc932ebe25c)
```

**Comment by hebasto** [comment]
https://git.savannah.gnu.org/gitweb/?p=guix.git;a=commit;h=fa17abf1af09570708daa28dd40ffbc932ebe25c looks ok, but locally:
```
$ git checkout fa17abf1af09570708daa28dd40ffbc932ebe25c
fatal: reference is not a tree: fa17abf1af09570708daa28dd40ffbc932ebe25c
```
