### ISSUE TITLE
Separate monotree repository for the wallet?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#24045]
Now that the GUI has been split up into its own monotree about 2 years ago (https://github.com/bitcoin/bitcoin/pull/19071), it could make sense to start a discussion to do the same to the wallet.

Just like the GUI, the wallet is speaking with the node via internal interfaces. However, the wallet is still "baked into" large parts of the codebase that shouldn't really depend on it. (E.g. the tests: #20078). Also, if people think that splitting the GUI (#19071) had negative effects, we should hold back on doing the same to the wallet and circle back.

Other than that, the goals and considerations remain largely the same (see #19071 for details):

* Separate issue and patch management
* More focused review and interests
* Maintain high quality assurance
* The wallet *is* Bitcoin Core

**Comment by hebasto** [comment]
I see a maintenance problem with the current situation. Within a GUI repo there are no @DrahtBot comments about conflicts with PRs in the main repo that touch both qt and non-qt code.

**Comment by MarcoFalke** [comment]
Good point. I'll look into updating DrahtBot to predict cross-repo conflicts.

**Comment by Veterangrail** [comment]
> Now that the GUI has been split up into its own monotree about 2 years ago (#19071), it could make sense to start a discussion to do the same to the wallet.
> 
> Just like the GUI, the wallet is speaking with the node via internal interfaces. However, the wallet is still "baked into" large parts of the codebase that shouldn't really depend on it. (E.g. the tests: #20078). Also, if people think that splitting the GUI (#19071) had negative effects, we should hold back on doing the same to the wallet and circle back.
> 
> Other than that, the goals and considerations remain largely the same (see #19071 for details):
> 
> * Separate issue and patch management
> * More focused review and interests
> * Maintain high quality assurance
> * The wallet _is_ Bitcoin Core


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by MarcoFalke** [comment]
Closing for now
