### ISSUE TITLE
doc: add a brief description to each namespace

### ISSUE THREAD

**Issue by niVelion** [bitcoin/bitcoin#24073]
**Is your feature request related to a problem? Please describe.**

Many namespaces are as yet un-annotated with a brief description, as used by Doxygen to generate developer documentation, locally or at https://doxygen.bitcoincore.org/namespaces.html.

Incomplete developer documentation may affect developer onboarding time, and this seems like low-hanging fruit.

**Describe the solution you'd like**

To add annotations to each of these namespaces. There may be existing descriptions elsewhere, if not I or someone else could attempt to describe each namespace, and reviewers could suggest improvements or alternatives.

**Describe alternatives you've considered**

Ideally each description would be committed by its author, so perhaps handling this with one PR that is then squashed isn't the best solution.

On the other hand, if this would ease developer onboarding perhaps that's more important.

**Additional context**

Documentation at time of opening 14/12/2022:

![doxygen-namespaces-20211214](https://user-images.githubusercontent.com/97605837/149532363-fc8e7c16-a253-417b-92bd-5a3b8419a2af.png)

**Comment by MarcoFalke** [comment]
I think the namespace names are pretty self-explanatory. For example `bech32` holds utility functions and code related to bech32. If you want to learn more details about something in a namespace, I recommend reading the class or function documentation.
