### ISSUE TITLE
Getting [Errno 32] Broken pipe after the page reloading several times ! using Django app with nginx for Bitcoin core gateway

### ISSUE THREAD

**Issue by mimo6090** [bitcoin/bitcoin#24070]
I have Django app trying to make bitcoin payment page using local bitcoin core node but I keep getting ([Errno 32] Broken pipe) when the page refresh to check the incoming transactions the error looks like timeout error but I tried several methods to resolve timeout errors using uWsgi and Nginx params but didn't work and didn't got any benfet from logs only from journalctl got `SIGPIPE: writing to a closed pipe/socket/fd`

The debug mode showing this

`

Traceback (most recent call last):
  File "./wallet/models.py", line 235, in updatedeposit_btc
    unconf_amount = self.bitcoind.unconf_by_addr(address)
  File "./wallet/bitcoind.py", line 70, in unconf_by_addr
    return self.proxy.getreceivedbyaddress(addr, minconf=0)
  File "/project/env/lib/python3.9/site-packages/bitcoin/rpc.py", line 600, in getreceivedbyaddress
    r = self._call('getreceivedbyaddress', str(addr), minconf)
  File "/project/env/lib/python3.9/site-packages/bitcoin/rpc.py", line 231, in _call
    self.__conn.request('POST', self.__url.path, postdata, headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.9/http/client.py", line 971, in send
    self.sock.sendall(data)
During handling of the above exception ([Errno 32] Broken pipe), another exception occurred:

`
And I have in bitcoind connection setting .py
`
from django.conf import settings
from decimal import Decimal
from .rates import rate
import bitcoin
import bitcoin.rpc
from bitcoin.wallet import CBitcoinAddress, CBitcoinAddressError
from django.core.exceptions import ValidationError

try:
    network = settings.BTC_NETWORK
except:
    network = None

if network:
    bitcoin.SelectParams(network)

class Bitcoind:

    MINCONF = settings.BTC_MIN_CONFIRMATIONS
    VIEW_URL = settings.BTC_VIEW_URL
    URL = settings.BITCOIND_URL

    def __init__(self):
        try:
            url = self.URL
        except:
            url = None
            
        self.proxy = bitcoin.rpc.Proxy(service_url=url)
    @staticmethod
    def usd_to_btc(usd):
        return rate.usd_to_btc(usd)

    @staticmethod
    def btc_to_usd(btc):
        return rate.btc_to_usd(btc)

    @staticmethod
    def sats_to_usd(sats):
        return rate.btc_to_usd(Bitcoind.sats_to_btc(sats))

    @staticmethod
    def usd_to_sats(usd):
        return Bitcoind.btc_to_sats(rate.usd_to_btc(usd))

    @staticmethod
    def sats_to_btc(sats):
        return Decimal(sats) / Decimal(1e8)

    @staticmethod
    def btc_to_sats(btc):
        return Decimal(btc) * Decimal(1e8)

    def create_address(self):
        return self.proxy.getnewaddress(account=self.ACC)

    def unconf_by_addr(self, addr):
        return self.proxy.getreceivedbyaddress(addr, minconf=0)

    def conf_by_addr(self, addr):
        return self.proxy.getreceivedbyaddress(addr, minconf=self.MINCONF)

    @staticmethod
    def validate(addr):
        try:
            return CBitcoinAddress(addr)
        except CBitcoinAddressError:
            raise ValidationError(_('BTC address is invalid'), code='invalid_btc_address')
        return None

def btc_address_validator(address):
    return Bitcoind.validate(address)

`
And my models.py
`
def updatedeposit(self, dp):
        if dp.coin == Coins.BTC:
            return self.updatedeposit_btc(dp)
        else:
            raise WalletException('No such deposit option')

        if dp.status not in STATUS_TO_UPDATE:
            return dp

        try:
            address = self.bitcoind.validate(dp.recv_address)
        except:
            raise WalletException("Invalid BTC address")
        try:
            unconf_amount = self.bitcoind.unconf_by_addr(address)
            conf_amount = self.bitcoind.conf_by_addr(address)
        except:
            raise WalletException('Bitcoind error')

        if unconf_amount > conf_amount:
            dp.status = Status.UNCONFIRMED
            dp.sats_amount = unconf_amount
            dp.save()
            return dp
        if conf_amount == 0:
            delta = timedelta(minutes=settings.DEPOSIT_EXPIRATION)
            if dp.date < timezone.now() - delta:
                dp.status = Status.EXPIRED
                dp.save()
                return dp
            delta = timedelta(minutes=settings.DEPOSIT_EXPIRATION+40)
            if dp.date < timezone.now() - delta:
                dp.status = Status.CANCELLED
                dp.save()
                return dp
            dp.status = Status.WAITING
            dp.sats_amount = 0
            dp.save()
            return dp
`
please help me out

this my nginx conf and uwsgi ini

`
[uwsgi]
chdir           = /dir/
module          = core.wsgi
env             = DJANGO_SETTINGS_MODULE=core.settings
home            = /dir/env
master          = true
processes       = 10
socket          = /dir/uwsgi.sock
chmod-socket    = 666
vacuum          = true
harakiri        = 200
post-buffering  = 1
max-requests    = 5000
journalctl
safe-pidfile    = /dir/uwsgi-master.pid
ignore-sigpipe
socket-timeout  =300
http-timeout    =300
server {
    listen      80;
    charset     utf-8;
    server_name _;
    client_max_body_size 20M;
    keepalive_timeout  300;
    sendfile        on;

server
    location /media  {
        alias /dir/media;
    }

    location /static {
        alias /dir/static;
    }

    location / {
        uwsgi_pass  django;
        include     /dir/uwsgi_params;
        proxy_http_version 1.1;
        proxy_connect_timeout 1200s;
        proxy_read_timeout 1000s;
        uwsgi_connect_timeout 2000s;
        uwsgi_read_timeout 2000s;
        uwsgi_send_timeout 2000s;

    }
}
`

**Comment by fanquake** [comment]
This issue tracker is for technical issues related only to Bitcoin Core, and should not be used for your django / nginx configuration questions.
