### ISSUE TITLE
doc: update productivity docs with mention of github compare view

### ISSUE THREAD

**Issue by niVelion** [bitcoin/bitcoin#24071]
**Is your feature request related to a problem? Please describe.**

`git range-diff` suggested by [Productivity: Diff the diffs with git range-diff](https://github.com/bitcoin/bitcoin/blob/master/doc/productivity.md#diff-the-diffs-with-git-range-diff) requires some configuration beyond cloning `bitcoin/bitcoin`, as discussed [here](https://github.com/bitcoin/bitcoin/pull/22235#issuecomment-1012188440).

**Describe the solution you'd like**

Updating the [Productivity: Diff the diffs with git range-diff](https://github.com/bitcoin/bitcoin/blob/master/doc/productivity.md#diff-the-diffs-with-git-range-diff) documentation to also suggest GitHub's Compare View functionality (e.g. https://github.com/josibake/bitcoin/compare/3b0ef90..120fbba) seems like it could be helpful.

I can work on this myself if there's support for it, but am equally happy for someone else to pick it up as a `good first issue`.

**Useful skills**

* Git
* Markdown
* GitHub

**Want to work on this issue?**

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
GitHub is known to serve corrupt metadata and sometimes code. Also, it refuses to disclose any details about their git backend.

So strong NACK putting more eggs into this proprietary basket.

**Comment by niVelion** [comment]
> GitHub is known to serve corrupt metadata and sometimes code. Also, it refuses to disclose any details about their git backend.

I've read some of the related discussion https://github.com/bitcoin/bitcoin/issues/20227 and https://github.com/bitcoin-core/bitcoin-devwiki/wiki/GitHub-alternatives-for-Bitcoin-Core since seeing your response, OK I wasn't aware.

> So strong NACK putting more eggs into this proprietary basket.

In that case, I could try and reproduce using `git range-diff` from a fresh clone of `bitcoin/bitcoin`, and update the documentation to mention any prerequisites it has?

So far, I've just tried the following, will close this issue for now until I figure out what steps got this working previously.

```
$ git clone git@github.com:bitcoin/bitcoin.git
$ cd bitcoin
$ cat >> .git/config << 'EOF'
[remote "upstream-pull"]
        fetch = +refs/pull/*/head:refs/remotes/upstream-pull/*
        url = git@github.com:bitcoin/bitcoin.git
EOF
$ git fetch --all
$ git range-diff 3b0ef90...120fbba
fatal: ambiguous argument '120fbba..3b0ef90': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: could not parse log for '120fbba..3b0ef90'
```
