### ISSUE TITLE
Error Compiling Bitcoin Core v22.0 on MacOS

### ISSUE THREAD

**Issue by Stolpmann** [bitcoin/bitcoin#24087]
Hello, I am trying to install Bitcoin Core version 22.0 on MacOS Catalina 10.15.7. I am following the build for macOS tutorial in the [official Bitcoin repo]([https://github.com/bitcoin/bitcoin/blob/216f4ca9e7ccb1f0fcb9bab0f9940992a87ae55f/doc/build-osx.md]). 

I have been running into issues when compiling.

```
(base) Evans-MacBook-Pro:bitcoin Evan$ make

Making all in src
  
CXXLD    bitcoind

ld: archive has no table of contents file 'libbitcoin_server.a' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [bitcoind] Error 1

make[1]: *** [all-recursive] Error 1

make: *** [all-recursive] Error 1
(base) Evans-MacBook-Pro:bitcoin Evan$ 
```

I do not know if there is a way to reproduce the issue I followed the tutorial exactly.

 

I cloned Bitcoin core v22.0 from the [repo]([https://github.com/bitcoin)

**Comment by RandyMcMillan** [comment]
```
cd ~/bitcoin
make clean
git checkout a0988140b71485ad12c3c3a4a9573f7c21b1eff8
 ./autogen.sh
./configure --disable-tests --disable-bench
 make appbundle
```

This worked for me on 10.15.7 (19H1519)

**Comment by Stolpmann** [comment]
> ```
> cd ~/bitcoin
> make clean
> git checkout a0988140b71485ad12c3c3a4a9573f7c21b1eff8
>  ./autogen.sh
> ./configure --disable-tests --disable-bench
>  make appbundle
> ```
> 
> This worked for me on 10.15.7 (19H1519)

Worked for me!
Thank You!

**Comment by fanquake** [comment]
I'm assuming the `make clean` is what has fixed your issue here. There shouldn't be able need to disable the tests or benchmarks. Calling `make appbundle` is also an obscure target to pick, `make` or `make check` should work fine.

**Comment by brunoerg** [comment]
Got same issue here and `make clean` fixed it
