### ISSUE TITLE
Mac OS latest Bitcoin core latest release will not run as Mac OS can't check it for malicious malware, instructed to contact developer ongoing now for at least two months what gives guys I am sure that I'm not the only one to have reported this.

### ISSUE THREAD

**Issue by jgb211** [bitcoin/bitcoin#24140]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by MarcoFalke** [comment]
There is nothing we can do without any details

**Comment by jgb211** [comment]
Thank you for closing this issue, Mac Pro 6,1 Mac OS 12.1 error message
![Screen Shot 2022-01-24 at 11 21 16](https://user-images.githubusercontent.com/18145286/150822175-429af594-9421-474a-a18f-cf7d6b9b3940.png)

**Comment by hebasto** [comment]
@jgb211 

> Thank you for closing this issue, Mac Pro 6,1 Mac OS 12.1 error message

Which Bitcoin Core version did you download? Please check its compatibility with your Mac OS 12.1 (see release notes).

**Comment by jgb211** [comment]
The latest bitcoin release at your web site as of today, this issue has been going on since the release of Mac OS 12 last years release of Mac OS 12 I am reporting it today because I find hard that no other Mac OS has not reported this issue, I am using it on a Mac Pro 6,1 os 12.1 Bitcoin core was fully synced and running until the Mac OS 12 last year it resides on my hard drive useless now for months.
Thanks in advance

**Comment by hebasto** [comment]
@jgb211 
> The latest bitcoin release at your web site as of today,

If you mean [v22.0](https://bitcoincore.org/en/releases/22.0/) -- it is not compatible with macOS 10.12 Sierra.

The latest version which is compatible with macOS 10.12 Sierra is [v0.21.2](https://bitcoincore.org/en/releases/0.21.2/). Going to reproduce the issue you reported.

**Comment by jgb211** [comment]
This issue has been ongoing the release of Montery last year and you folks have not addressed it

**Comment by hebasto** [comment]
Sorry, I confused macOS 10.12 with macOS 12.1.

**Comment by jgb211** [comment]
here I am replying to you here Mr. Stepanov it is Mac OS Monterey since it was released last year
![Screen Shot 2022-01-24 at 11 21 16](https://user-images.githubusercontent.com/18145286/150836867-bf12b072-b3d7-4f05-b31d-f6a8de1b48f0.png)
![Screen Shot 2022-01-24 at 12 28 06](https://user-images.githubusercontent.com/18145286/150836884-cbdeaf2b-5255-4720-a26f-5c8de8e9be32.png)

.

**Comment by hebasto** [comment]
This issue can be closed as it effectively duplicates #15774.

**Comment by jgb211** [comment]
I apologize for any confusion it is Mac OS Monterey 12.0-and 12.1 not Sierra Mac OS latest release since last year I find it hard to believe that this is the first time that the bitcoin dev. Have heard of this issue

**Comment by jgb211** [comment]
you can do what ever you choose but I still can't use bitcoin core on Mac OS Monterey.

**Comment by fanquake** [comment]
> you can do what ever you choose but I still can't use bitcoin core on Mac OS Monterey.

We are aware of the issue, and will work to improve the situation for 23.0. Closing this as a duplicate.

**Comment by hebasto** [comment]
@jgb211 

To run Bitcoin Core 22.0 on macOS Monterey you can use a work-around using a context menu:

1. 

![Screenshot from 2022-01-25 12-51-42](https://user-images.githubusercontent.com/32963518/150963971-d12d14b1-519a-4c9a-81b0-f5d8f38d6669.png)

2. Click "Show in Finder"
3. Open context menu for "Bitcoin Core"
![Screenshot from 2022-01-25 12-52-04](https://user-images.githubusercontent.com/32963518/150964160-662d9de6-68ca-4cc5-be83-7b469df7d47b.png)
4. Click "Open"
5. 
![Screenshot from 2022-01-25 12-52-23](https://user-images.githubusercontent.com/32963518/150964297-11380be5-2cb5-4d62-be94-09adbd75c270.png)
6. Click "Open"

Tested on macOS Monterey 12.2 (21D48, Intel).

**Comment by ErgoTechKG** [comment]
I followed the steps as following. It works on one of my MacBook Air, but not my MacBook Pro. The screenshot is here

<img width="778" alt="Screen Shot 2022-08-12 at 9 08 16 PM" src="https://user-images.githubusercontent.com/83173948/184465557-9820c0dc-90c3-466b-87f2-e6de20498f7b.png">
<img width="881" alt="Screen Shot 2022-08-12 at 9 08 30 PM" src="https://user-images.githubusercontent.com/83173948/184465558-d8b749ed-cf18-43a6-af15-c378b84588fa.png">
<img width="648" alt="Screen Shot 2022-08-12 at 9 08 46 PM" src="https://user-images.githubusercontent.com/83173948/184465560-9f0c6675-49e0-4b3d-8653-c2501fb390cd.png">



> @jgb211
> 
> To run Bitcoin Core 22.0 on macOS Monterey you can use a work-around using a context menu:
> 
> 
> ![Screenshot from 2022-01-25 12-51-42](https://user-images.githubusercontent.com/32963518/150963971-d12d14b1-519a-4c9a-81b0-f5d8f38d6669.png)
> 
> 2. Click "Show in Finder"
> 3. Open context menu for "Bitcoin Core"
>    ![Screenshot from 2022-01-25 12-52-04](https://user-images.githubusercontent.com/32963518/150964160-662d9de6-68ca-4cc5-be83-7b469df7d47b.png)
> 4. Click "Open"
> 
> ![Screenshot from 2022-01-25 12-52-23](https://user-images.githubusercontent.com/32963518/150964297-11380be5-2cb5-4d62-be94-09adbd75c270.png) 6. Click "Open" 7. ![Screenshot from 2022-01-25 13-00-23](https://user-images.githubusercontent.com/32963518/150964814-8cc7fb17-526a-41be-820f-484dd6ea8f79.png)
> 
> Tested on macOS Monterey 12.2 (21D48, Intel).
