### ISSUE TITLE
"Fee too high" CI error in wallet_send.py

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#24151]
`wallet_send.py --legacy-wallet` line 332

https://cirrus-ci.com/task/6260771733635072

```
2022-01-25T13:05:06.243000Z TestFramework (INFO): Test setting explicit fee rate
2022-01-25T13:05:06.666000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_send.py", line 332, in run_test
    assert_fee_amount(fee, Decimal(len(res["hex"]) / 2), Decimal("0.00004531"))
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 45, in assert_fee_amount
    raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
AssertionError: Fee of 0.00000993 BTC too high! (Should be 0.00000983 BTC)
```

Haven't seen it fail yet locally on the same branch while running:
```
(for i in {1..1000}; do test/functional/wallet_send.py --legacy-wallet --pdbonfailure ; done)
```

This test assertion was added in October 2020 (603c0050837) and the `get_fee()` test utility helper in October 2021 (80dc829be7f), so if the error is new then it might stem from a more recent change.

**Comment by jonatack** [comment]
Another one, this time `wallet_send.py --descriptors ` and line 559 instead of 332

https://cirrus-ci.com/task/5115109138759680

```
 test  2022-01-26T10:42:21.513000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_send.py", line 559, in run_test
                                       assert_fee_amount(testres["fees"]["base"], testres["vsize"], Decimal(0.0001))
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 45, in assert_fee_amount
                                       raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
                                   AssertionError: Fee of 0.00003160 BTC too high! (Should be 0.00003130 BTC)
```

**Comment by sdaftuar** [comment]
I'm seeing it as well, I think: https://github.com/bitcoin/bitcoin/runs/4969391918

**Comment by YashPolu** [comment]
@jonatack I would like to work on this. Can I?

**Comment by jonatack** [comment]
@YashPolu yes, of course, a fix would be great.

**Comment by YashPolu** [comment]
@jonatack great thank you so much, any suggestions on how to approach this problem

**Comment by mzumsande** [comment]
See #24239 for a fix for the first failure in `wallet_send.py --legacy-wallet` line 332.

The other failures in `wallet_send.py --descriptors`  line 559 unfortunately cannot be explained by this: Looking at the numbers, it seems that for some reason the actual tx size deviates by 3 bytes from the one calculated by the wallet (only 2 bytes are tolerated), but I have no idea why.

**Comment by fanquake** [comment]
What is the status of this? Seems like 1 of the 2 issues is fixed, but the other is intermittent, and hasn't been seen again. Does this issue still need to be one the 23.0 milestone?

**Comment by MarcoFalke** [comment]
I am still running into this issue daily.

https://cirrus-ci.com/task/6564823138828288?logs=ci#L3673

**Comment by Sjors** [comment]
Seeing it at line 560 now:

https://github.com/bitcoin/bitcoin/blob/8add59d77dd621be57059229f378822e4b707318/test/functional/wallet_send.py#L543-L560

**Comment by fanquake** [comment]
After consulting with @achow101 I'm removing this from the 23.0 milestone. This isn't a blocker, and is a test-only problem.

**Comment by MarcoFalke** [comment]
Ehh? This means the tests won't pass on the release branch. This will be flagging backports and users will be running into issues. But I guess no one is running the test outside the CI?

I presume that this is caused by the "rounding up" thing. So just increasing the range by 1 byte for now might fix this?

**Comment by achow101** [comment]
> Maybe the `input_weight` calculation is wrong? Or perhaps too pessimistic, triggering the upper bound in the assert.
> 
> The `test_send()` function picks a new destination address every time its called, which means we can't predict the length of the ECDSA signature(s) in advance. And this particular test uses multiple inputs. So we should probably increase the tolerance, or use a Taproot wallet so the signature length is fixed.

I believe this is the case. I think the `input_weight` calculation is wrong which is putting it at the upper bound of the assert. Then we are occasionally using a signature that is one byte shorter than what the estimator uses, so the final transaction ends up 3 bytes smaller than estimated, which is outside of the `assert_approx` bounds.

I will have open a PR fixing the calculation.

**Comment by MarcoFalke** [comment]
This was my fix:

```diff
diff --git a/test/functional/test_framework/util.py b/test/functional/test_framework/util.py
index 210025104e..82a4967e7e 100644
--- a/test/functional/test_framework/util.py
+++ b/test/functional/test_framework/util.py
@@ -40,8 +40,8 @@ def assert_fee_amount(fee, tx_size, feerate_BTC_kvB):
     target_fee = get_fee(tx_size, feerate_BTC_kvB)
     if fee < target_fee:
         raise AssertionError("Fee of %s BTC too low! (Should be %s BTC)" % (str(fee), str(target_fee)))
-    # allow the wallet's estimation to be at most 2 bytes off
-    high_fee = get_fee(tx_size + 2, feerate_BTC_kvB)
+    # allow the wallet's estimation to be at most 3 bytes off
+    high_fee = get_fee(tx_size + 3, feerate_BTC_kvB)
     if fee > high_fee:
         raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))

**Comment by achow101** [comment]
#24454 should fix this.

**Comment by cryptowalletr** [comment]
> @jonatack great thank you so much, any suggestions on how to approach this problem

Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by cryptowalletr** [comment]
> What is the status of this? Seems like 1 of the 2 issues is fixed, but the other is intermittent, and hasn't been seen again. Does this issue still need to be one the 23.0 milestone?

Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by cryptowalletr** [comment]
> I am still running into this issue daily.
> 
> 
> 
> https://cirrus-ci.com/task/6564823138828288?logs=ci#L3673

Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by jonatack** [comment]
Keep seeing this, even several times today like https://cirrus-ci.com/task/5823757662027776.

**Comment by jonatack** [comment]
Still seeing this fail in CI: https://cirrus-ci.com/task/4565158969212928
