### ISSUE TITLE
Moderation required for BitcoinCore in the Microsoft winget package repository

### ISSUE THREAD

**Issue by brianddk** [bitcoin/bitcoin#24174]
BitcoinCore is showing up in the [winget package repo](
https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/BitcoinCoreProject
).  It's great to see the packages there, but you might want to take over the PR submission for your ORG.  The packages there seem legit, but technically, anyone could contribute any package there and call it "BitcoinCore".  Your dev team may want to take over these submissions, or request you appear on the PR approval list for your ORG.

* [BitcoinCore Products on Microsoft Repo](https://github.com/microsoft/winget-pkgs/search?q=bitcoincoreproject&type=issues)
* [Package Contributing Guidelines](https://github.com/microsoft/winget-pkgs#contributing)
* [Open Discussion on Microsoft Moderation Practices](https://github.com/microsoft/winget-pkgs/discussions/15607)

**Comment by fanquake** [comment]
Thanks for letting us know. We can keep an eye on the repository.
