### ISSUE TITLE
Avoid InitError when downgrading peers.dat

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#24188]
See https://github.com/bitcoin/bitcoin/pull/22762#issuecomment-951063826

This can be fixed by creating a new exception type and catching it in the right place.

#### Useful skills:

* C++ exceptions
* Addrman serialization
* Functional tests

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by junderw** [comment]
I have proposed a fix for this in #24201
