### ISSUE TITLE
[RPC] Removal of signmessage and verifymessage

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#24186]
Those two features are present for a long in Bitcoin Core, but has been scarcely used over the years.

However, this is going to change with [AOPP](https://gitlab.com/aopp/address-ownership-proof-protocol/-/blob/master/wallet_guide.md) who directly link at [this code](https://github.com/bitcoin/bitcoin/blob/13d27b452d4b60010c54d4f80757dea9805076be/src/util/message.cpp) in the protocol's implementation.

**Comment by prayank23** [comment]
Bitcoin Core will have better signing of messages once https://github.com/bitcoin/bitcoin/pull/24058 is merged

I don't think there is anything wrong with this feature. If one or more exchanges use it differently users can avoid using those exchanges.

Signing messages has lot of usecases and sometimes even helps in verification without KYC. I have shared some examples in https://github.com/bitcoin/bitcoin/issues/10542#issuecomment-818045408

**Comment by Sjors** [comment]
NACK. Given the lack of SegWit / Taproot support in this feature, we should not assume the lack of usage is due to a lack of legitimate interest. Also we can't measure if it really is used "scarcely"; we could only infer that, indirectly, if for example _nobody_ uses P2PKH addresses anymore.

That said, we should probably never implement `aopp` URI support, at least not any `VASP` specific features of it (and calling external URL's is also problematic).

**Comment by NicolasDorier** [comment]
What about stop supporting the Legacy format after #24058 is merged then?

**Comment by Sjors** [comment]
I think we should maintain that legacy functionality for compatibility with old wallets, but it doesn't matter in the context of AOPP-style initiatives: they can trivially add BIP-322 support.

**Comment by DennisAMenace** [comment]
We use the feature to verify if someone is an owner of an address to register nodes. It would be sad if this was removed and not supported any longer.

**Comment by sipa** [comment]
I don't think we should even be *talking* about dropping support for these until a replacement exists, works, and is adopted.

**Comment by Gabriel-x42** [comment]
Dennis is correct, other projects have been using this function quite extensively, x42 Protocol being just one of them.

**Comment by NicolasDorier** [comment]
@Sjors technically they can, but the fact that nothing support yet BIP322 will make their adoption way harder.
