### ISSUE TITLE
Autotools dependency version undocumented

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#24209]
We document the versions of most dependencies in `doc/dependencies.md`, but not autotools, which is required to build Bitcoin Core for several releases now since we never fully merged #18818.

~~#24169 mentions autotools currently doesn't support C++20, so it seems like we should figure out and start tracking what minimum version is actually needed so this doesn't catch us by surprise later.~~

**Comment by MarcoFalke** [comment]
Sorry, I meant `s/autotools/GNU Autoconf Archive/g`

**Comment by luke-jr** [comment]
Oh, that's good - means we can safely bump it sooner :)

IMO still should get documented ideally tho

**Comment by Veterangrail** [comment]
> We document the versions of most dependencies in `doc/dependencies.md`, but not autotools, which is required to build Bitcoin Core for several releases now since we never fully merged #18818.
> 
> ~#24169 mentions autotools currently doesn't support C++20, so it seems like we should figure out and start tracking what minimum version is actually needed so this doesn't catch us by surprise later.~


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by Veterangrail** [comment]
> We document the versions of most dependencies in `doc/dependencies.md`, but not autotools, which is required to build Bitcoin Core for several releases now since we never fully merged #18818.
> 
> ~#24169 mentions autotools currently doesn't support C++20, so it seems like we should figure out and start tracking what minimum version is actually needed so this doesn't catch us by surprise later.~


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by Veterangrail** [comment]
> We document the versions of most dependencies in `doc/dependencies.md`, but not autotools, which is required to build Bitcoin Core for several releases now since we never fully merged #18818.
> 
> ~#24169 mentions autotools currently doesn't support C++20, so it seems like we should figure out and start tracking what minimum version is actually needed so this doesn't catch us by surprise later.~


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by MarcoFalke** [comment]
Anything left to do after the previous comment?
