### ISSUE TITLE
bitcoin-22.0-win64-setup.exe - installed on Windows 11 - BTC wallet created - wallet loaded - Windows.Node.Launcher.exe install. ->> no wallet left and I can't activate the wallet in Windows.Node.Launcher Setup

### ISSUE THREAD

**Issue by madbob12** [bitcoin/bitcoin#24221]
Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.9

Error information:

bitcoin-22.0-win64-setup.exe - installed on Windows 11 - BTC wallet created - wallet loaded - Windows.Node.Launcher.exe install. ->> no wallet left and I can't activate the wallet in Windows.Node.Launcher Setup

here is the error code:

'BitcoinTab' object has no attribute 'update_config'
File "node_launcher\gui\system_tray_widgets\settings\bitcoin_tab.py", line 30, in 
--

I have already installed bitcoincore 22.0 and Windows.Node.Launcher 3 times. no result -- no more wallet and I no longer have any functions to generate a new wallet in bitcoincore 22.0

I would like to run a full note and lighting nodes - but I'm a newbie I'm looking forward to some help

**Comment by fanquake** [comment]
Windows.Node.Launcher.exe is not software developed / distributed by this repository. You need to open the bug with (I'm assuming) https://github.com/lightning-power-users/node-launcher.
