### ISSUE TITLE
Invalid SHA256SUMS.asc

### ISSUE THREAD

**Issue by ronaldpetty** [bitcoin/bitcoin#24233]
https://bitcoincore.org/bin/bitcoin-core-22.0/SHA256SUMS.asc doesn't seem valid (no hashes or files included).

```
~$ curl -sLO https://bitcoincore.org/bin/bitcoin-core-22.0/SHA256SUMS.asc
~$ cat SHA256SUMS.asc 
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEDMuq/Xai7OLM0xQd4v/VsdiMqX0FAmE7QY0ACgkQ4v/VsdiM
...
n+msw3Q5hoYG/c9VlV/Am4NM8lxEM9BWz/6XbPvOFBKICQ8D3A0=
=MC+w
-----END PGP SIGNATURE-----
-----BEGIN PGP SIGNATURE-----
...
```

Compared to 0.21 and prior.

```
~$ curl -sLO https://bitcoin.org/bin/bitcoin-core-0.21.0/SHA256SUMS.asc
~$ cat SHA256SUMS.asc 
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

43416854330914992bbba2d0e9adf2a6fff4130be9af8ae2ef1186e743d9a3fe  bitcoin-0.21.0-aarch64-linux-gnu.tar.gz
..
da7766775e3f9c98d7a9145429f2be8297c2672fe5b118fd3dc2411fb48e0032  bitcoin-0.21.0-x86_64-linux-gnu.tar.gz
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQIcBAEBCAAGBQJgADqTAAoJEJDIAZ42wulkjtkQAJwlSTDinKsxZIMky3MeVhwB
...
ka8Z9KLt/N0ziabBexAw
=bi4p
-----END PGP SIGNATURE-----
```

Maybe related (or not), it seems to verify the v22 file above, you need laanwj.asc and not laanwj-releases.asc (not that it matters because I think the SHA256SUMS.asc is incorrect).

**Comment by sipa** [comment]
The mechanism for attesting and verifying release builds changed completely with v22.0. Read the instructions for verifications on https://bitcoincore.org/en/download/.

**Comment by ronaldpetty** [comment]
Thank you @sipa , my bad, I was starting here https://bitcoin.org/en/download as it was talking about Core. Maybe that page could be clearer.  Thanks again, will close.
