### ISSUE TITLE
Feature request: automatically upgrade legacy to HD wallet

### ISSUE THREAD

**Issue by losh11** [bitcoin/bitcoin#24234]
Since Bitcoin Core 0.17 the startup option `upgradewallet` has been available, allowing users to upgrade old legacy wallets to HD wallets. 
However many users with non-HD wallets are yet to upgrade their wallet, to reduce complexity, and or various issues related to non-HD wallets, I am wondering if it may be a good idea to require users to upgrade.

Two different ways of implementing this (off the top of my head):
- when all addresses in a keypool are marked used, automatically upgrade wallet and notify user to make a backup.
- on startup upgrade wallet and notify user to make a backup

Are there any reasons for why Bitcoin Core doesn't already do this?

**Comment by achow101** [comment]
Not all users want to upgrade. There are tradeoffs and risks associated with upgrading, we are not in the business of forcing things onto users that they do not want.

**Comment by jamesob** [comment]
Anything else to discuss here? Worth closing?
