### ISSUE TITLE
Cross Compiling bitcoind fails with fatal error with Ubuntu 18.04 on Windows

### ISSUE THREAD

**Issue by BTCFranky** [bitcoin/bitcoin#24248]
:~/bitcoin$ make HOST=x86_64-w64-mingw32
Making all in src
make[1]: Entering directory '/home/frank/bitcoin/src'
make[2]: Entering directory '/home/frank/bitcoin/src'
make[3]: Entering directory '/home/frank/bitcoin'
make[3]: Leaving directory '/home/frank/bitcoin'
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
In file included from primitives/transaction.cpp:11:0:
./util/strencodings.h:16:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
Makefile:12722: recipe for target 'primitives/libbitcoinconsensus_la-transaction.lo' failed
make[2]: *** [primitives/libbitcoinconsensus_la-transaction.lo] Error 1
make[2]: Leaving directory '/home/frank/bitcoin/src'
Makefile:16761: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/frank/bitcoin/src'
Makefile:817: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by MarcoFalke** [comment]
What are the steps to reproduce? Are you using build-windows.md?

**Comment by fanquake** [comment]
> ./util/strencodings.h:16:10: fatal error: charconv: No such file or directory

This means you aren't using a C++17 compiler. [g++-mingw-w64](https://packages.ubuntu.com/bionic/g++-mingw-w64) in Bionic is backed by GCC 7.3.0, which doesn't meet the [requirements](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md) (GCC 8.1+) to build master (I assume that's what you're building).
