### ISSUE TITLE
`getblocktemplate` returns a standard P2PKH with 0 sigops (testnet)

### ISSUE THREAD

**Issue by antonilol** [bitcoin/bitcoin#24255]
i noticed a standard 0 sigops transaction when calling getblocktemplate, but that transaction turned out to be P2PKH of course **with** `OP_CHECKSIG`

**Expected behavior**

`"sigops": 36,` in block template json

**Actual behavior**

```
      ...
      "txid": "54eee291ec73fcc3faf496cf90ffc9b6faa57940234802bdae58c51540016853",
      "hash": "54eee291ec73fcc3faf496cf90ffc9b6faa57940234802bdae58c51540016853",
      "depends": [
      ],
      "fee": 1404,
      "sigops": 0,   <-- here
      "weight": 5472
      ...
```

**To reproduce**

somehow get the sigop count of `54eee291ec73fcc3faf496cf90ffc9b6faa57940234802bdae58c51540016853` (testnet)

**System information**

bitcoin.org binary v22.0.0

**Comment by pinheadmz** [comment]
It's not unusual for a transaction to have 0 block-limit sigops.

The tx in your example has 9 inputs which all spend from legacy p2pkh UTXOs. In each of those spends, the `OP_CHECKSIG` is literally in the output of the previous transaction, and the sigop cost was "paid for" by the funding transactions. The inputs only contain public keys and signatures (no sigops). The single output of that tx is a P2WPKH. The signature operation required to spend that output will be "paid for" by the *spending* transaction: https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#user-content-Sigops


I ran `getblocktemplate` from my mainnet node and it built a block with 83 0-sigop transactions:

```
$ bitcoin/src/bitcoin-cli getblocktemplate '{"rules":["segwit"]}' | grep -e  '"sigops": 0' | wc -l
83
```

... most of these are P2TR transactions like https://blockstream.info/tx/0b3caca257f483715bccf70274179f78d8043a88b65df07f295dba40fe0a89f0?expand and in BIP342 it is documented that these sigops do not count towards the block limit at all: https://github.com/bitcoin/bips/blob/master/bip-0342.mediawiki#resource-limits
