### ISSUE TITLE
CI testing with minimum supported versions

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#24325]
It would be nice if we could get a CI that always tests our minimum supported versions. Maybe we can use Guix for it?

**Comment by MarcoFalke** [comment]
Not sure if it is worth it inside this repo's CI. I am currently doing it on my own infrastructure.

**Comment by Veterangrail** [comment]
> It would be nice if we could get a CI that always tests our minimum supported versions. Maybe we can use Guix for it?


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by MarcoFalke** [comment]
Closing due to lack of reply for now
