### ISSUE TITLE
Build broken when enabling fuzzing on Apple M1 hw using homebrew llvm.

### ISSUE THREAD

**Issue by john-difool** [bitcoin/bitcoin#24386]
Enabling fuzzing on macos (Monterey) with Apple M1 hw (arm64) breaks the build:

- I did the steps required to use llvm with homebrew (brew install llvm). Then passed CC & CXX env vars pointing their new respective binaries. Most fuzz tests compiled till I got to crc32c.

./configure --enable-fuzz --with-sanitizers=fuzzer,address,undefined CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++ --disable-asm

  CXXLD    test/fuzz/fuzz
Undefined symbols for architecture arm64:
  "crc32c::ExtendArm64(unsigned int, unsigned char const*, unsigned long)", referenced from:
      crc32c::Extend(unsigned int, unsigned char const*, unsigned long) in libcrc32c.a(libcrc32c_a-crc32c.o)
ld: symbol(s) not found for architecture arm64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/fuzz/fuzz] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by fanquake** [comment]
@hebasto @jarolrod can either of you confirm this failure? I don't currently have access to an M1 box.

**Comment by hebasto** [comment]
Tested the recent master branch (0a76bf848c72211f986a6cc5b1c13de820b861dd) on Mac mini (M1, 2020) + macOS Monterey 12.2.1 (21D62):
```
% brew info llvm | head -1
llvm: stable 13.0.1 (bottled), HEAD [keg-only]
% ./autogen.sh
% ./configure --enable-fuzz --with-sanitizers=fuzzer,address,undefined --enable-suppress-external-warnings CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++
% make clean
% make  # no errors
```

**Comment by fanquake** [comment]
Going to close for now. @john-difool if this is still broken for you can you provide any more info?
