### ISSUE TITLE
clang-14 ubsan

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#24394]
New thread to continue the discussion from https://github.com/bitcoin/bitcoin/pull/24347#issuecomment-1045207127

**Comment by LarryRuane** [comment]
I am now able to reproduce it, by replacing the `address` sanitizer with `integer`, as  you suggested. Thanks for your help.
```
./configure CC=clang-14 CXX=clang++-14 --enable-fuzz --with-sanitizers=integer,fuzzer,undefined
```
