### ISSUE TITLE
[brainstorm] Improving `makeseeds.py`

### ISSUE THREAD

**Issue by prayank23** [bitcoin/bitcoin#24422]
A. Filtering hosts with multiple ports can be removed IMO:

https://github.com/bitcoin/bitcoin/blob/c44e734dca64a15fae92255a5d848c04adaad2fa/contrib/seeds/makeseeds.py#L215

B. Tor v3 can also be included in the results.

C. Recent observation which can be confirmed with:

```
wget https://gitlab.com/api/v4/projects/33695681/packages/generic/nrich/0.1.1/nrich_0.1.1_amd64.deb
sudo dpkg -i nrich_0.1.1_amd64.deb
host -t a seed.bitcoin.sipa.be | sed -e 's/seed.bitcoin.sipa.be has address //g' | nrich -
```

Possible reasons for vulnerable machines used for bitcoin nodes:

1. False positives
2. Users not aware or don't care
3. Attackers prefer using these for better results
4. Honeypots
5. Other reasons

Leaving 1 which won't be true for all the results, filtering such nodes in `makeseeds.py` should make sense. Below is an example for one IP copied from [`suspicious_hosts.txt`](https://github.com/bitcoin/bitcoin/blob/master/contrib/seeds/suspicious_hosts.txt)

```python
ip = '88.198.17.7'

url = 'https://internetdb.shodan.io/' + ip
response = requests.get(url)

if response.text.find('CVE') != -1:
    print('vulnerable')
```

**Comment by MarcoFalke** [comment]
#17020, #7398

**Comment by fanquake** [comment]
Discussion can continue in #17020. No need for a new issue.
