### ISSUE TITLE
secp256k1 contains 1 to 2 megabyte source files leading to analysis problems.

### ISSUE THREAD

**Issue by SkybuckFlying** [bitcoin/bitcoin#24473]
Take a local look at the source code in this folder:

https://github.com/bitcoin/bitcoin/tree/master/src/secp256k1/src

Notice the 1 and 2 megabyte source files.

This leads to analysis problems. Long wait times.

My suggestion/request is that this source code is changed such that these big look-up tables are read from disk instead of dumped into c and h files.

This would reduce the source files considerably and would solve analysis problems. Right now only way to solve analysis problems is to delete this particular folder.

**Comment by fanquake** [comment]
This is an [upstream project](https://github.com/bitcoin-core/secp256k1/), so we can't solve this problem here. In any case I doubt we are going to start re-arranging our source code to work around whichever tools of yours cannot handle large files.
