### ISSUE TITLE
About frequently calling the function GetBoolArg  to get parameters

### ISSUE THREAD

**Issue by guoyl** [bitcoin/bitcoin#24475]
In the /src/net.cpp, the functoin void CConnman::PushMessage(CNode* pnode, CSerializedNetMsg&& msg) will be called frequently. 
The following code used inside function:
......
if (gArgs.GetBoolArg("-capturemessages", false)) {
        CaptureMessage(pnode->addr, msg.m_type, msg.data, /*is_incoming=*/false);
    }
......
My question is : the GetBoolArg can be called once when the class is initialized.

**Comment by MarcoFalke** [comment]
Yes, it can be called once. However, the impact should be minimal, as writing to disk takes more time than a map lookup.
