### ISSUE TITLE
Apple T2 Security Chip private key grabbers

### ISSUE THREAD

**Issue by anthony19114** [bitcoin/bitcoin#24517]
See GitHub post 

**System information**

All wallets all full nodes etc

All apple devices with a t2 chip

I’m here to tell you first hand any device with an Apple T2 chip is vulnerable to snatching your private keys for it has immutable control over your operating system.
Here is my experience 
https://github.com/anthony19114/MacT2Vuln

This isn’t a spam, and would like to see a fix for apple t2 chip private key grabbers.

**Comment by MarcoFalke** [comment]
This is the issue tracker for the Bitcoin Core Software project. Issues with Apple hardware or software need to be reported to Apple.
