### ISSUE TITLE
remove explicit `descriptors=true` parameter for createwallet RPCs in functional tests

### ISSUE THREAD

**Issue by theStack** [bitcoin/bitcoin#24550]
Since the default wallet type was changed to descriptor wallets in https://github.com/bitcoin/bitcoin/pull/23002, there is no need to explicitly pass the `descriptors=true` parameter to `createwallet` RPCs anymore. All of those instances in functional tests should be identified and simplified by omitting the parameter (there is already a PR doing the same for documentation, see #24519).

#### Useful skills:
- Basic Python3 knowledge

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by theStack** [comment]
(Not sure if I have to explicitly mention this here or maintainers see it by the template I selected: this should get the "good first issue" tag).

**Comment by prusnak** [comment]
Implemented in https://github.com/bitcoin/bitcoin/pull/24551

**Comment by theStack** [comment]
My assumption that those parameters can be removed also in the test framework was wrong (see https://github.com/bitcoin/bitcoin/pull/24551#issuecomment-1066623263 and https://github.com/bitcoin/bitcoin/pull/24551#issuecomment-1066817874), i.e. will close this now. Sorry for the noise!
