### ISSUE TITLE
Option for receive events with all networks, but send transactions and/or blocks only with anonymous network[s]?

### ISSUE THREAD

**Issue by Farxial** [bitcoin/bitcoin#24557]
Hi everyone :-)
Which startup option is for receive events with all networks (IP, Tor, I2P), but send transactions and/or blocks only with anonymous network[s]?
If there is no such option, can we have one? :-)

**Comment by MarcoFalke** [comment]
* https://github.com/bitcoin/bitcoin/issues/14692
* https://github.com/bitcoin/bitcoin/issues/21876
* https://github.com/bitcoin/bitcoin/issues/19042
* https://github.com/bitcoin/bitcoin/issues/3828
