### ISSUE TITLE
guix: Linker warning for darwin builds

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#24591]
```
  CXXLD    libbitcoinconsensus.la
ld: warning: double slash removed from -install_name (//lib/libbitcoinconsensus.0.dylib)
```

**Comment by fanquake** [comment]
Going to close this 

The double slash actually occurs across all HOSTS, not just darwin i.e:
```bash
libtool: install: /root/.guix-profile/bin/install -c .libs/libbitcoinconsensus.so.0.0.0 /distsrc-base/distsrc-4a2c60b57c4d-x86_64-linux-gnu/installed/bitcoin-4a2c60b57c4d//lib/libbitcoinconsensus.so.0.0.0
```

It's that ld64 is the only linker that warns, [see here in cctools](https://github.com/tpoechtrager/cctools-port/blob/04663295d0425abfac90a42440a7ec02d7155fea/cctools/ld64/src/ld/Options.cpp#L2816) (I think this will disappear when we migrate to lld). I dont think this is something we need to fix, or have an open issue for, and just comes down to $rpath being empty inside the Guix env. Everything still ends up inside `installed/` as expected.
