### ISSUE TITLE
IsStandard should check the witnessprogram is a valid point on the field

### ISSUE THREAD

**Issue by junderw** [bitcoin/bitcoin#24631]
**Is your feature request related to a problem? Please describe.**
A v1 taproot witness program must be a valid point on secp256k1 otherwise it is essentially a black hole.

**Describe the solution you'd like**
Add a check in IsStandard that will check the witnessprogram in the case where WITNESS_V1 is returned. If the witness program is not the X value of a valid point, return false. (https://github.com/bitcoin/bitcoin/blob/v22.0/src/policy/policy.cpp#L53-L74)

**Comment by theStack** [comment]
There has been a pull request with that policy change already (#24106), but it was rejected with quite convincing reasons, e.g. potential problems in batching transactions for exchanges. See in particular the answers https://github.com/bitcoin/bitcoin/pull/24106#issuecomment-1017498437, https://github.com/bitcoin/bitcoin/pull/24106#issuecomment-1017500023 and https://github.com/bitcoin/bitcoin/pull/24106#issuecomment-1018660851.
