### ISSUE TITLE
util/check.h Assert/Assume: namespacing issues

### ISSUE THREAD

**Issue by ajtowns** [bitcoin/bitcoin#24654]
The `Assert`/`Assume` macros are implemented via lambda functions to allow the result of the assertion to both be evaluated (and trigger an abort) and be returned without having the expression be evaluated twice.

This causes some ugly namespacing issues though. Because there's a function call, clang's thread safety annotations don't get passed through (as the lambda is unannotated), possibly causing an unnecessary compiler error because the compiler loses track that a mutex is held when a guarded variable is accessed.

It also seems that gcc (but not clang) gets confused about member functions (but not member variables), eg:

```c++
class TestAssert
{
public:
    int variable = 3;
    int test_1(void) { return variable; }
    int test_2(void) {
        auto x = [&]() {
            Assert(test_1() == 3);
        };
        x();
        return ++variable;
    }
};
```

results in:

```
test/util_tests.cpp:91:26: error: cannot call member function ‘int util_tests::TestAssert::test_1()’ without object
   91 |             Assert(test_1() == 3);
```

requiring you to write `Assert(this->test_1() == 3)` instead.

**Comment by ajtowns** [comment]
Changing the `Assert` macro to something like:

```c++
void assertion_fail(const char* file, int line, const char* func, const char* assertion)
{
    auto str = strprintf("%s:%s %s: Assertion `%s' failed.\n", file, line, func, assertion);
    fwrite(str.data(), 1, str.size(), stderr);
    std::abort();
}

template <typename T>
inline T inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
{
    if (!val) assertion_fail(file, line, func, assertion);
    return std::forward<T>(val);
}

#define Assert(val) inline_assertion_check(val, __FILE__, __LINE__, __func__, #val)
```

might work to avoid this -- that way `val` is evaluated in the original context where all the locks and this pointers are already known about. I'm not sure if this handles all C++'s various copy/move rules as well as the current Assert does though.

**Comment by sipa** [comment]
@ajtowns I think the return type should be `T&&` for the forwarding to work.

**Comment by MarcoFalke** [comment]
Related: #21596

**Comment by ajtowns** [comment]
@sipa I can't convince myself that returning `T&&` wouldn't mess up lifetimes somehow and return a dangling reference... Trying it out, it seems like `T` as the return-type might invoke the move constructor while `T&&` might not, so what you say at least seems plausible. I think the current approach (with a lambda) also invokes the move constructor; though destruction happens in a different order...

**Comment by sipa** [comment]
@ajtowns I'm happy to reason through a specific case you're concerned about if you have one. But perhaps this helps: `std::forward<T>` has as return type also `T&&` (note that (A&)&& = A&, so if T=A&, the return type is A&, not A&&).

**Comment by ajtowns** [comment]
@sipa I think my concern is that `f(1+2) + 4` might be interpreted as "pass 3 to f, then destruct 3, then add 4 to whatever  f returned" which would cause a problem if f were returning the 3 object that was just destructed. But I think "[All temporary objects are destroyed as the last step in evaluating the full-expression that (lexically) contains the point where they were created,](https://en.cppreference.com/w/cpp/language/lifetime)" means that's not allowed?

**Comment by sipa** [comment]
@ajtowns So I think the only concern in that regard is something like:

```c++
auto&& x = f(1+2);
return x + 4;
```

where the `x` is a dangling reference to the temporary created by `1 + 2`.

However, that's just as dangerous as doing the same with `auto&& x = std::forward<int>(1+2)`, e.g.

**Comment by ajtowns** [comment]
https://github.com/ajtowns/bitcoin/commits/202203-assume has a couple of commits implementing this approach if anyone wants to take a look

**Comment by ajtowns** [comment]
PR'd as #24714
