### ISSUE TITLE
test: minisketch decode returns empty optional 

### ISSUE THREAD

**Issue by omkar-mohanty** [bitcoin/bitcoin#24664]
Running  ```src/test/minisketch_test.cpp``` gives fatal error.

What behavior did you expect?
All tests pass 

What was the actual behavior (provide screenshots if the issue is GUI-related)?
```
./test_bitcoin --run_test=minisketch_tests
Running 1 test case...
unknown location(0): fatal error: in "minisketch_tests/minisketch_test": C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\optional(370) : Assertion failed: Cannot access value of empty optional
```

 How reliably can you reproduce the issue, what are the steps to do so?
1. Build ```test_bitcoin``` project using visual studio 2022.
2. run  ```
./test_bitcoin --run_test=minisketch_tests ```

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
compiled ```src/tests/minisketch_tests.cpp``` from ```master``` branch using msvc compiler from Visual Studio 2022.

What type of machine are you observing the error on (OS/CPU and disk type)?
OS: Windows 10 Home
Disk: 500GB SSD
RAM: 16GB

**Comment by MarcoFalke** [comment]
What commit are you on? Can you try to get a traceback or at least the line number where this happens?

**Comment by omkar-mohanty** [comment]
Hello @MarcoFalke I suspect this happens in ``` BOOST_CHECK(dec.has_value());``` in ```src/test/minisketch_tests.cpp```  
In commit: ```98e9d8e8e2e3e65e6f1e14be26457a9f9090c092```

**Comment by MarcoFalke** [comment]
No, it looks like the assertion happens inside the msvc `optional` header. `has_value` shouldn't assert nor throw, so this should be a `value()` call (or the `*`/`->` operator).

**Comment by omkar-mohanty** [comment]
Yeah error happens in the msvc header more specifically this ```fatal error: in "minisketch_tests/minisketch_test": C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\optional(370) : Assertion failed: Cannot access value of empty optional``` occurs

**Comment by oborona-kyiv** [comment]
There is  war in Ukraine now. The enemy is already close to Kyiv. We are a group of activists who organized fundraising for our guys  to provide them with equipment, protection facilities(body armor, helmets) and everything they are in need now. 
We ask everybody from crypto-society who cares to help us in collecting necessary funds

Thank you in advance for your help


BTC   3JdS1E9Evga2dSFpxLYZzLSfAH8Xj6PyLk
LTC   MSvkd1JD8CKUFPb3cfoWkiUcb8drWohu2x
ETH   0x5095689fc3f339d1278f40ba97156bd2a196a972
DASH  XbeKxx7BhqkBdDdMiLzUCkGqTczyfXuia5

**Comment by MarcoFalke** [comment]
We recently bumped our docs to Windows 2022 and CI is passing on those. So is this still an issue with a recent version of Bitcoin Core?

**Comment by fanquake** [comment]
@sipsorcery can you confirm that this is fixed / can be closed?

**Comment by sipsorcery** [comment]
Seems fixed:

```
build_msvc\x64\Release>test_bitcoin --run_test=minisketch_tests
Running 1 test case...
*** No errors detected  
```

Test fails on a debug build but as far as I recall the tests have always failed on Windows debug builds and anyway that would be a different issue to the one posted here.
