### ISSUE TITLE
getaddednodeinfo should return an array

### ISSUE THREAD

**Issue by clanie** [bitcoin/bitcoin#2467]
When getaddednodeinfo is called with dns=false it returns something like this:
{"result":{"addednode":"faucet.bitcoin.st","addednode":"faucet.bitxcoin.st"},"error":null,"id":null}

I expected restult to be an array, and when calling with dns=true that is also what I get. Isn't it supposed to always return an array?

I'm trying to deserialize this in Java, and that would be much easier if it always returned an array.

**Comment by laanwj** [comment]
Would probably have been easier if this had been done when designing the API. However at this point, changing the interface is going to cause more trouble than it solves.
