### ISSUE TITLE
Put undocumented JSON failure mode behind a runtime flag

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#24695]
Following the merge of https://github.com/bitcoin/bitcoin/pull/23083, we'll throw a non-fatal error at runtime if the documentation for an RPC is incorrect. This behaviour has found numerous issues over a very short period (of the PR being opened). However, this is not something that we want in production / release builds, instead, we want the ability to have it enabled in the CI and when running tests. A runtime option could be added, which controls this behaviour (disabled by default).

#### Useful skills:

- C++
- Understanding of Bitcoin Core's initialization sequence
- Understanding of Bitcoin Core's RPC interface

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by Bella70** [comment]
> Following the merge of https://github.com/bitcoin/bitcoin/pull/23083, we'll throw a non-fatal error at runtime if the documentation for an RPC is incorrect. This behaviour has found numerous issues over a very short period (of the PR being opened). However, this is not something that we want in production / release builds, instead, we want the ability to have it enabled in the CI and when running tests. A runtime option could be added, which controls this behaviour (disabled by default).
> 
> #### Useful skills:
> 
> - C++
> - Understanding of Bitcoin Core's initialization sequence
> - Understanding of Bitcoin Core's RPC interface
> 
> #### Want to work on this issue?
> 
> For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.
> 

SUN DeFi: anti-regulatory, anti-censorship, most secure DeFi financial products, peace of mind highly effective and most profitable 
 Click the link for details: https://www.funawealth.com?share_address=0xF6C7F67c2CfB3eaf5f7F6f740163B787d3818B32

**Comment by Bella70** [comment]
SUN DeFi: anti-regulatory, anti-censorship, most secure DeFi financial products, peace of mind highly effective and most profitable 
 Click the link for details: https://www.funawealth.com?share_address=0xF6C7F67c2CfB3eaf5f7F6f740163B787d3818B32

**Comment by AMILY2809** [comment]
SUN DEFI digital currency financial trader with an average annual income of up to 1440% is a safe and highly secure product profitable daily and profits will be transferred directly to the wallet of investors to join hands to get rich
Click here for more details
https://www.funawealth.com?share_address=0x38a67A3C8113636c2123E673Fc6161A85bc06B2d

**Comment by laanwj** [comment]
Concept ACK. 

> It would be undesirable to crash a production system intermittently if there is a typo in the doc.

Right. See #24716 for such a case that was luckily found by testing, not in production.

I also think the assertion is pretty uninformative. It would be great if it logged what the difference from the doc is (though out of scope here).

**Comment by MarcoFalke** [comment]
I use the following hack locally, which can be improved by returning the last error only.


```diff
diff --git a/src/rpc/util.cpp b/src/rpc/util.cpp
index 9c9e6e9f11..9371ea3421 100644
--- a/src/rpc/util.cpp
+++ b/src/rpc/util.cpp
@@ -918,20 +918,25 @@ bool RPCResult::MatchesType(const UniValue& result) const
         std::map<std::string, UniValue> result_obj;
         result.getObjMap(result_obj);
         for (const auto& result_entry : result_obj) {
+            std::cout << "r_ " << result_entry.first << std::endl; // ----------------
             if (doc_keys.find(result_entry.first) == doc_keys.end()) {
+                std::cout << "missing doc" << std::endl; // -------------
                 return false; // missing documentation
             }
         }
 
         for (const auto& doc_entry : m_inner) {
+            std::cout << doc_entry.m_key_name << std::endl; // ---------------
             const auto result_it{result_obj.find(doc_entry.m_key_name)};
             if (result_it == result_obj.end()) {
                 if (!doc_entry.m_optional) {
+                    std::cout << "missing a required key" << std::endl; // -------------
                     return false; // result is missing a required key
                 }
                 continue;
             }
             if (!doc_entry.MatchesType(result_it->second)) {
+                std::cout << "wrong type" << std::endl; // --------------
                 return false; // wrong type
             }
         }

**Comment by suhailsaqan** [comment]
Is this still open? If so, could someone provide context on what is left?
