### ISSUE TITLE
23.0 RC Testing Guide Feedback

### ISSUE THREAD

**Issue by stickies-v** [bitcoin/bitcoin#24706]
This issue is to discuss the [23.0 Release Candidate Testing Guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide). If you have any issues with or feedback on the document, please leave a comment here.

Note: this is for feedback on the _document_, not on Bitcoin Core or on the 23.0 changes. Please see the [v23.0 testing ticket](https://github.com/bitcoin/bitcoin/issues/24501) for instructions on how to report bug/results.

Thank you for your testing efforts!

**Comment by jonatack** [comment]
s/cd hyperboria-peerstats/cd hyperboria-peers/

**Comment by stickies-v** [comment]
> s/cd hyperboria-peerstats/cd hyperboria-peers/

Oh whoops fixed, thanks!

**Comment by jonatack** [comment]
"find the corresponding full config in `/hyperboria-peers/peers`" -> for me, there is no `/peers` dir but instead directories by continent (af, as, eu), within which you have further dirs by country.

**Comment by stickies-v** [comment]
You're right, changed it to:
> and find the corresponding full config in `/hyperboria-peers/<continent/<country>/...` folder

**Comment by jonatack** [comment]
`./configure --with-gui=yes --with-sqlite=yes` -> IIRC normally those flags aren't necessary, as default is auto = yes if the deps are installed and the wallet isn't disabled. Run: `./configure -h | grep -A2 "with-sqlite\|with-gui\|disable-wallet"`

In their place perhaps add the `--enable-suppress-external-warnings` flag to avoid users reporting build warnings from third-party libraries in the v23 testing.

**Comment by brunoerg** [comment]
Nice guide, @stickies-v! 

I think the script to test the non-default ports could stop bitcoind in the end. What do you think?

**Comment by stickies-v** [comment]
> IIRC normally those flags aren't necessary, as default is auto = yes if the deps are installed and the wallet isn't disabled.

I think it's important for this test that we're sure people are compiling with sqlite and gui, so then it's helpful to catch missing dependencies earlier as opposed to after the build process? For that reason, I'd prefer to keep the explicit flags in.

> I think the script to test the non-default ports could stop bitcoind in the end. What do you think?

I had it like that for a while, but the downside is that the monitoring script stops working as soon as bitcoind terminates, and I think it's nice to be able to look at that (at least briefly) after the test finishes, hence I took it out. So far that reason I think it's better to keep it this way? Thanks for going through the guide!

**Comment by danielabrozzoni** [comment]
In the script for testing non default ports, you declare `DISCONNECTFREQ=5`, but then through the test you use `FREQ` instead. I think it should be:
```diff
-echo "Starting test, disconnecting outbound peers on :8333 every $FREQ seconds..."
+echo "Starting test, disconnecting outbound peers on :8333 every $DISCONNECTFREQ seconds..."
 until [[ "$(getNonDefaultNode)" != "null" ]] > /dev/null;
 do $BINARY_PATH/bitcoin-cli -datadir=$DATA_DIR getpeerinfo | jq 'map(select(.inbound == false and (.addr | endswith(":8333")))) | .[] | .id' | xargs -L 1 $BINARY_PATH/bitcoin-cli -datadir=$DATA_DIR disconnectnode "" > /dev/null
-sleep $FREQ;
+sleep $DISCONNECTFREQ;
 done;
 
 echo "Test successful: connected to non-default peer on $(getNonDefaultNode | jq '.addr')"
```

**Comment by stickies-v** [comment]
Oh my, yes thank you Daniela, [fixed](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide/_compare/71382eb5abc684ace5b7da69661558c4b2542c2d...a7167d1313906d880d354e4c4e988948a2f6c141) that!

**Comment by jonatack** [comment]
Might be good to add the --enable-suppress-external-warnings flag to avoid testers reporting build warnings from third-party libraries.

**Comment by stickies-v** [comment]
Sorry I skipped that, yes I agree with that suggestion: [updated](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide/_compare/a7167d1313906d880d354e4c4e988948a2f6c141...44c25bb73dd8fa693b6698e38a8c6e55a97a2995)

**Comment by hebasto** [comment]
@stickies-v 

https://github.com/bitcoin/bitcoin/issues/24501#issuecomment-1085456985

**Comment by stickies-v** [comment]
> #24501 (comment)

[Added `SHA256 implementation test`](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide/_compare/b1d7e746a9f99fb198197340f3c5f8ccaba8e9e3...9bbb877a80d2704b308dc7edd9683996e7791562)  (and [updated rc2 -> rc3](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide/_compare/44c25bb73dd8fa693b6698e38a8c6e55a97a2995...b1d7e746a9f99fb198197340f3c5f8ccaba8e9e3))

**Comment by dunxen** [comment]
Great guide, stickies!

Should it not be encouraged to send back previously loved signet coins to the faucet before wiping the data directory?

**Comment by stickies-v** [comment]
Oh that's a good point, I hadn't considered that, thank you. [Updated](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide/_compare/2d8638c5751087812642e07420035f08c7240bc9...f983be175b3d13d47b330af59e9fc9d4f90356be) with instructions to return coins.

**Comment by hebasto** [comment]
@stickies-v 

https://github.com/bitcoin/bitcoin/issues/24501#issuecomment-1088394978
