### ISSUE TITLE
fuzz: enable BDB in the MSAN CI jobs

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#24703]
Currently, our [MSAN](https://clang.llvm.org/docs/MemorySanitizer.html) and MSAN fuzz CI jobs [build depends without BDB](https://github.com/bitcoin/bitcoin/blob/2a3e8fb3592e42300ec96c9f6724e15346e30ea7/ci/test/00_setup_env_native_msan.sh#L17) (i.e `NO_BDB=1`). Ideally, these jobs would be building Bitcoin Core with BDB enabled (via depends). Previously BDB was being compiled in one of the jobs, [but not actually used](https://github.com/bitcoin/bitcoin/pull/24522).

Re-enabling BDB may require using newer (clang) tools; see #23008.

Testing / debugging is possible by [running the CI locally](https://github.com/bitcoin/bitcoin/tree/master/ci#readme). i.e `FILE_ENV="./ci/test/00_setup_env_native_msan.sh" ./ci/test_run_all.sh`.

If BDB is re-enabled in our MSAN CI, it may also be possible to use it in our OSS-FUZZ job, see: https://github.com/google/oss-fuzz/blob/1abbd8bf089660da96367b0370855f99e3aa2df6/projects/bitcoin-core/build.sh#L32.

#### Useful skills:

* CI
* Sanitizers / Fuzzing

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
I don't think there are any bdb fuzz tests, so this will have no benefit for fuzzing. And given that bdb will be removed, this will also have limited benefit for the other stuff?

**Comment by fanquake** [comment]
> And given that bdb will be removed, this will also have limited benefit for the other stuff?

I'm less interested in the fuzzing, and more in the MSAN job. If we don't care that BDB isn't included in that build, because it's going away in the future, I'm happy to close this, and note why it's not enabled in the CI jobs themselves. Otherwise it is unclear why certain dependencies are enabled vs not.

**Comment by MarcoFalke** [comment]
Yeah, no objection to a comment why it is disabled.
