### ISSUE TITLE
Cross-compiled `bitcoind -signet` silently fails on Windows

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#24726]
The issue was [discovered](https://github.com/bitcoin/bitcoin/issues/24501#issuecomment-1079738588) during 23.0rc2 testing.

MSVC build works flawlessly.

`bitcoind -testnet` also works flawlessly.

**Comment by MarcoFalke** [comment]
22.0 also works fine?

**Comment by laanwj** [comment]
FWIW, we've managed to trace at least @fanquake's crash to the avx2 implementation of sha256sum:
```
$ addr2line -e bin/bitcoin.exe.dbg -aipfC 0x14051cc65
0x000000014051cc65: sha256d64_avx2::Transform_8way(unsigned char*, unsigned char const*) at /distsrc-base/distsrc-23.0rc2-x86_64-w64-mingw32/src/crypto/sha256_avx2.cpp:316
```
This probably explains why I couldn't reproduce it in wine. The computer I was using doesn't have either instruction set.

According to @sipa you might need a AVX2 capable CPU which doesn't support SHA-NI to get this code path.

It could be a compiler bug around AVX2 intrinsics or something.

**Comment by laanwj** [comment]
It's probably: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412

The stack is 16 byte aligned according to the ABI, but gcc assumes 32 byte alignment (doesn't re-align the stack pointer), resulting in ~50% chance of a crash.

Looks like we'll have to disable AVX2 (anything that uses 256 bit types) on mingw builds. Probably least impact to disable it in during detection in `configure.ac`.
