### ISSUE TITLE
ci: add lint job to run clang-tidy check for named args

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#24747]
After #24661, we should be able to enable [`clang-tidy`](https://clang.llvm.org/extra/clang-tidy/) named argument checking in the CI lint job. The simplest way to invoke this checking, is something like `./autogen.sh && ./configure CC=clang-12 CXX=clang++-12 && make clean && bear make -j9 && ( cd ./src/ && run-clang-tidy-12 -j9 )`, which invokes clang-tidy using our [`.clang-tidy` config](https://github.com/bitcoin/bitcoin/blob/master/src/.clang-tidy).

Dependencies, like `clang-tidy` would need to be installed in the [linting container](https://github.com/bitcoin/bitcoin/blob/master/ci/lint/04_install.sh), and a linting job could be added to https://github.com/bitcoin/bitcoin/tree/master/test/lint.

It is possible to work on this now, by just basing your changes on the #24661 branch.

#### Useful skills:

* Bash
* CI

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
I think this requires a "mock" compilation so this will probably be a normal task, separate from the lint task.
