### ISSUE TITLE
no separate source code tarball download available

### ISSUE THREAD

**Issue by rofl0r** [bitcoin/bitcoin#2476]
on http://sourceforge.net/projects/bitcoin/files/Bitcoin/bitcoin-0.8.1/
there's no source code tarball which i need to get reproducible results on my build-it-yourself distro (package management system is laid out for source tarballs with checksums, not git checkouts)

apparently the linux download has the source included, but also comes with prebuilt binaries (unusable in my case, since i use a different libc).
this bloats up the tarball to twice the needed size or more, which affects download time and hd usage.

the argument that 18 MB is nothing compared to 7G of blockdata, is not valid for people who just fetch all tarballs in one go (so they have them already in case they need it), but in the end do not use the bitcoin client.

the other argument that github provides downloads is also <b>not valid</b>, since
1) they generate tarballs on the fly so the checksum changes whenever it is removed from cache (gz uses a random seed, so every archive produced is unique, even with the same content)
2) github redirects from http to http<b>s</b>, making it impossible to download anything with busybox' wget program. they did not even reply to my complaints about that.
3) github has no redundancy, when the frontend server(s) is down, everything is down
4) SF.net (which is already used for binary downloads) has at least 20 mirrors in different countries, and provides much better download speeds. additionally it lets the user choose if he wants HTTP or HTTPS downloads.

so please in the future release a separate source code tarball and make it available from the default download page.
thanks.

please also consider using the .xz compressor since it's about 40-60% better in compression and only slightly slower in decompression speed than .gz (but 3-4x as fast as bz2) and available on any linux distribution that came out in the last 5 years. even busybox supports it by default.

**Comment by laanwj** [comment]
Tarballs can be found along with the rest of the downloads, e.g. https://bitcoin.org/bin/bitcoin-core-0.10.1/bitcoin-0.10.1.tar.gz

**Comment by rofl0r** [comment]
the /bin/ in the URL suggests its a binary (compiled). this issue is about *source* tarballs

**Comment by laanwj** [comment]
Now that's a dumb comment. `/bin/` is just the internal site structure used for uploading releases and has no relevance here. The file I linked to is a source tarball. Please in the future try to do the minimum amount of research before you comment.
