### ISSUE TITLE
CI, tracing: run tracepoint interface tests in the CI

### ISSUE THREAD

**Issue by 0xB10C** [bitcoin/bitcoin#24782]
The first tracepoint tests were merged in #24358. However, they are skipped in the CI. I've already done some experiments running them in the CI in https://github.com/bitcoin/bitcoin/issues/23296, however I haven't been successful with it yet. The main issue was the limited capabilities inside the CirrusCI docker container.

An option would be to ask CirrusCI for help, another would be to run this part in a VM, if it's not to much overhead.

**Comment by MarcoFalke** [comment]
Did you try to "recycle" the arm or macos tasks? They might already be using a "full" VM. (ref https://github.com/bitcoin/bitcoin/issues/23296#issuecomment-1024922859)

Otherwise it should be possible to turn an existing task into using a fuller VM.

**Comment by 0xB10C** [comment]
I've looked at and experimented with the ARM tasks. Our ARM tasks run in an `arm_container`. https://github.com/bitcoin/bitcoin/blob/f3e35633690c71ebb69ec2ed08998565cade1522/.cirrus.yml#L190-L196

The [CirrusCI docs](https://cirrus-ci.org/guide/linux/#linux-containers) mention that `arm_container` tasks run on Graviton2 (ARM processor) instances in AWS via Kubernetes (`container` runs via Kubernetes in the Google Cloud). We can't use the macOS tasks as the tracepoints are Linux only..

I'll look into converting an existing task into a VM.

**Comment by 0xB10C** [comment]
> https://cirrus-ci.org/guide/custom-vms/ could work, though.

That worked! I've used a `compute_engine_instance` to build and test the tracepoints. We have the required privileges there.
```
task:
  name: '[usdt] [VM]'
  << : *GLOBAL_TASK_TEMPLATE
  compute_engine_instance:
    image_project: ubuntu-os-cloud
    image: family/ubuntu-minimal-2204-lts
```
However, the Ubuntu [`bpf-tools`](https://packages.ubuntu.com/jammy/bpfcc-tools) package is quite outdated (v0.18 (Jan 05, 2021) vs v0.24 (Jan 14, 2022)). It prints a warning about `warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined` to stderr when compiling to BPF bytecode. This has been fixed with https://github.com/iovisor/bcc/pull/3391 ([May 1, 2021](https://github.com/iovisor/bcc/pull/3391#event-4672496859)).

Printing to stderr let's interface tests in `test_runner.py` fail.

I don't really want to build bcc from source in the CI, but also didn't have any luck installing it from their [PPA](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary). Might give it another shot, though. This could probably be removed with the next Ubuntu release.

**Comment by MarcoFalke** [comment]
You could use Debian: https://packages.debian.org/bookworm/bpfcc-tools

**Comment by 0xB10C** [comment]
I think the debian `bookworm` image is not yet available in GCE. https://cirrus-ci.com/task/6440165211111424

Google requires you to have a credit card linked to your account to check.. https://cloud.google.com/compute/docs/images#os-compute-support

**Comment by 0xB10C** [comment]
The up coming Ubuntu 23.04 seems to be shipping with an up-to-date bpfcc: https://packages.ubuntu.com/lunar/python3-bpfcc
