### ISSUE TITLE
Add an option to create taproot descriptor for old descriptor wallets

### ISSUE THREAD

**Issue by Tracachang** [bitcoin/bitcoin#24801]
**Is your feature request related to a problem? Please describe.**

New wallets created with Bitcoin Core  v 23.0 RC3 have by default descriptors=true and taproot descriptor is generated.

**Describe the solution you'd like**

Using a wallet created with descriptors=true with the precedent version 22.0 does not allow me to create receiving Bech32taproot address (which is normal, since by that time "desc": "tr was not present).

I've tried to upgrade wallet with the command "upgradewallet" but it is already at latest version:
{
  "wallet_name": "wallet_22.0",
  "previous_version": 169900,
  "current_version": 169900,
  "result": "Already at latest version. Wallet version unchanged."
}

 I think it would be great a way to upgrade/add taproot descriptors to the wallet instead of having to create a new one.

**Comment by achow101** [comment]
We're working on it. #23417 is required, then a followup will be opened that actually adds the ability to add the descriptor.
