### ISSUE TITLE
Intermittent failure in feature_fee_estimation.py

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#24828]
Observed in #24827 (https://cirrus-ci.com/task/6466255107391488) but very likely unrelated.
Looks to me that a testmempoolaccept RPC call issued by the mini-wallet timed out - so it seems that it occurs after the #24817 rework but has a root cause in bitcoind?

```
 node1 2022-04-11T17:04:58.456117Z [httpworker.3] [rpc/request.cpp:179] [parse] ThreadRPCServer method=testmempoolaccept user=__cookie__ 
 node1 2022-04-11T17:05:25.635870Z [msghand] [net.cpp:3041] [PushMessage] sending ping (8 bytes) peer=0 
 node1 2022-04-11T17:06:50.669591Z [scheduler] [random.cpp:520] [SeedPeriodic] Feeding 32422 bytes of dynamic environment data into RNG 
 node0 2022-04-11T17:06:50.669699Z [net] [net.cpp:1651] [SocketHandlerConnected] socket closed for peer=1 
 node0 2022-04-11T17:06:50.671075Z [net] [net.cpp:567] [CloseSocketDisconnect] disconnecting peer=1 
```

**Comment by MarcoFalke** [comment]
I think node2 and node1 got sniped by the OS

>     Container errored with 'OOMKilled'

**Comment by MarcoFalke** [comment]
Yes, it is likely unrelated to a specific test, but the functional tests are still responsible for the OOM.

The last four runs:

https://cirrus-ci.com/task/5923607833477120
https://cirrus-ci.com/task/6107969036222464
https://cirrus-ci.com/task/6231558163005440
https://cirrus-ci.com/task/6674314664607744

The memory usage is (obviously) not deterministic, but never exceeds 8 GB. Though, it can get pretty close to it (7.4).

Not sure how to fix that. Increasing the memory isn't possible without increasing the CPU as well, which means that CI task scheduling may take longer.

Decreasing the MAKEJOBS for the functional tests may help, but obviously means they run slower.

**Comment by mzumsande** [comment]
ok, makes sense, thanks. If this starts to happens more frequently, it would be best discussed in another issue not related to a specific test. Closed.

**Comment by mzumsande** [comment]
I'm seeing this a lot currently:
https://cirrus-ci.com/task/4740331357863936
https://cirrus-ci.com/task/6471327732203520
https://cirrus-ci.com/task/5180616776876032

**Comment by MarcoFalke** [comment]
If the runtime is the "cause", maybe reshuffling the test list a bit could help?

**Comment by MarcoFalke** [comment]
Looks like the run-time doubled after commit 494455f8a56c93cef4162a0cedc792901577314e

**Comment by mzumsande** [comment]
Yes, it's twice as slow for me too. Plus it has 3 parallel nodes.
Shuffling the tests might work as a short-term solution.
Would it make sense to parallelize (`-jobs` option of the testrunner) not by restricting the number of functional tests that may run at the same time, but by restricting the number of nodes that may run at the same time?

**Comment by samahanas** [comment]
#24828
