### ISSUE TITLE
Compiling atlcoin based on BitCoin Ubuntu LTS 18.04 (windows)

### ISSUE THREAD

**Issue by mironkraft** [bitcoin/bitcoin#24825]
Hello there, 

While I am trying to compile I am facing this error/problem:

With the compile code:
`make HOST=x86_64-w64-mingw32`

`...failed updating 30 targets...
...skipped 15 targets...
funcs.mk:280: recipe for target '/home/mironkraft/AxxxxCoin/depends/work/build/x86_64-w64-mingw32/boost/1_71_0-578d369335e/./.stamp_built' failed
make: *** [/home/mironkraft/AxxxxCoin/depends/work/build/x86_64-w64-mingw32/boost/1_71_0-578d369335e/./.stamp_built] Error 1`

I am following this tutorial and some related issue about in github:

[https://bitcointalk.org/index.php?topic=5309100.0](url)

[https://github.com/bitcoin/bitcoin/issues/12515](url)

**Actual behavior**

It does not work the compile 

**System information**

BitCoin core 0.22
OS Windows 10
Using terminal Ubuntu LTS 18.04 on windows

If you have any questions, please do not hesitate to ask

PS: sorry if I am anykind wrong, first time posting here

**Comment by MarcoFalke** [comment]
The docs should be in `/doc/build-windows`, we don't support third party tutorials here.
