### ISSUE TITLE
Symbol not found: __ZN5boost10filesystem4pathdVEPKc

### ISSUE THREAD

**Issue by john-difool** [bitcoin/bitcoin#24850]
➜  brew install bitcoin 
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 4 taps (hashicorp/tap, homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
werf
==> Updated Formulae
Updated 44 formulae.
==> Updated Casks
Updated 15 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/bitcoin/manifests/22.0_1
Already downloaded: /Users/lorenzo/Library/Caches/Homebrew/downloads/126382fbc73a2195f2c4734f01d8f83e44660e875c09f49bf0062ac856d5a84c--bitcoin-22.0_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/bitcoin/blobs/sha256:d24ab4ebd9a10d882f5c577722c60d6c8994a6aa657824bdd26cb134a02a270b
Already downloaded: /Users/lorenzo/Library/Caches/Homebrew/downloads/bb4887749867b741e1ead80b31ff2dd425e63140c9a35ae67214164d3173bb93--bitcoin--22.0_1.arm64_monterey.bottle.tar.gz
==> Pouring bitcoin--22.0_1.arm64_monterey.bottle.tar.gz
==> Caveats
To restart bitcoin after an upgrade:
  brew services restart bitcoin
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/bitcoin/bin/bitcoind
==> Summary
🍺  /opt/homebrew/Cellar/bitcoin/22.0_1: 25 files, 32.8MB
==> Running `brew cleanup bitcoin`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  bitcoind
dyld[84611]: Symbol not found: __ZN5boost10filesystem4pathdVEPKc
  Referenced from: /usr/local/bin/bitcoind
  Expected in: /opt/homebrew/Cellar/boost/1.78.0_1/lib/libboost_filesystem.dylib
[1]    84611 abort      bitcoind

➜  ls /opt/homebrew/Cellar/boost/1.78.0_1/lib/libboost_filesystem.dylib                                           
/opt/homebrew/Cellar/boost/1.78.0_1/lib/libboost_filesystem.dylib
➜  nm -gU /opt/homebrew/Cellar/boost/1.78.0_1/lib/libboost_filesystem.dylib | grep ZN5boost10filesystem4pathdVEPKc

**Comment by jarolrod** [comment]
the manifest specifies boost 1.76, it shouldn't be looking into the boost 1.78 package. Please check your system configuration, this is not an issue with Bitcoin Core.

**Comment by fanquake** [comment]
> brew install bitcoin

You should open this issue at https://github.com/Homebrew/homebrew-core/.
