### ISSUE TITLE
RFC: Replacing Boost Process

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#24907]
Boost Process is currently relatively poorly maintained; bugs are remaining unfixed for multiple Boost releases, the code and issue tracking is [confusingly](https://github.com/boostorg/process/pull/243) spread across multiple repositories, see https://github.com/boostorg/process/ and https://github.com/klemens-morgenstern/boost-process), which themselves each have different versions of the code.

There's been no recent "modernization" of the module, i.e an option use `std::filesystem` over `boost::filesystem`, like other Boost modules, which is why we no-longer support external signing on Windows, see #24065. 

It's inclusion in our project is also a downside to our Boost consolidation / removal, i.e #24742, as Process's own dependencies (filesystem, system, win-api, + others) pull in even more Boost modules (i.e asio), which in turn pull in further modules..

If we are going to continue to use/expand our usage of it, I think we need some sort of plan, addressing the above, rather than leaving it ignored while we start accumulating workarounds, i.e #24523, in our own code to support it, and it's presence potentially blocks other project goals.

One potential alternative is https://github.com/arun11299/cpp-subprocess.

**Comment by prusnak** [comment]
> One potential alternative is https://github.com/arun11299/cpp-subprocess.

The suggested alternative looks quite nice:
* small codebase (~2K LOC)
* header-only template library
* interface similar to Python subprocess module

Pinging @Sjors as the only place where we use `boost::process` via `RunCommandParseJSON` is the `ExternalSigner`.

**Comment by laanwj** [comment]
> One potential alternative is https://github.com/arun11299/cpp-subprocess.

Concept ACK
It looks like modern c++, only depends on the standard library, and the license matches (MIT). 
If it provides the needed functionality it seems like a good idea.

> Pinging @Sjors as the only place where we use boost::process via RunCommandParseJSON is the ExternalSigner.

At the moment, yes. Though ideally we'd use whatever subprocess library we choose for the `*notify` commands as well, to be consistent.

**Comment by Sjors** [comment]
The main use case for `RunCommandParseJSON` is making the GUI work with hardware wallets. RPC could in principle also call HWI manually. So one alternative to look at could be [QT process](https://doc.qt.io/qt-5/qprocess.html). That said, the RPC code also serves to maintain good test coverage, and we wouldn't want to pull a QT dependency into bitcoind. But maybe the QT relevant code can be extracted?

**Comment by prusnak** [comment]
> So one alternative to look at could be [QT process](https://doc.qt.io/qt-5/qprocess.html).

We already use QProcess on macOS to workaround for a specific behavior (see https://github.com/bitcoin/bitcoin/pull/24668#issuecomment-1079106029 and subsequent comments for context) and it seemed to me that the sentiment was to get rid of QProcess completely.

**Comment by Rspigler** [comment]
Concept ACK.  Further removal of Boost is good, especially if bugs aren't being fixed.

**Comment by theStack** [comment]
Strong Concept ACK

**Comment by hebasto** [comment]
> the code and issue tracking is [confusingly](https://github.com/boostorg/process/pull/243) spread across multiple repositories, see https://github.com/boostorg/process/ and https://github.com/klemens-morgenstern/boost-process), which themselves each have different versions of the code

This is no longer the case.

And Boost [Process V2](https://www.boost.org/doc/libs/1_80_0_beta1/doc/html/boost_process/v2.html) is coming.

**Comment by fanquake** [comment]
> And Boost [Process V2](https://www.boost.org/doc/libs/1_80_0_beta1/doc/html/boost_process/v2.html) is coming.

I don't think that's any improvement on the Boost Process front.

Process V2 is now fully dependant on Boost ASIO:
> Since asio added pipes in boost 1.78, boost process V2 is fully asio based and uses it's pipes and file-handles for the subprocess.

This is another Boost (sub-)dependency we do not want.

**Comment by willcl-ark** [comment]
> FWIW, I started working on replacing boost::process with cpp-subprocess on the following branch: 

Does cpp-subprocess ok work on OpenBSD?

**Comment by theStack** [comment]
> > FWIW, I started working on replacing boost::process with cpp-subprocess on the following branch:
> 
> Does cpp-subprocess ok work on OpenBSD?

Yes, at least the corresponding unit tests and functional tests pass both on Linux (Ubuntu 22.04.1 LTS, Kernel 5.15.0) and OpenBSD (7.2). Would be nice if someone could test the branch (https://github.com/theStack/bitcoin/tree/nuke_boost_process) on MacOS.

**Comment by willcl-ark** [comment]
@theStack Just tested on MacOS 13.1 (without BDB and QT) and all functional and unit tests passed ✅

**Comment by hebasto** [comment]
> FWIW, I started working on replacing boost::process with cpp-subprocess on the following branch: [theStack/bitcoin@`nuke_boost_process`](https://github.com/theStack/bitcoin/tree/nuke_boost_process?rgh-link-date=2023-03-13T12%3A51%3A33Z)

I've picked up that branch. It appears that the upstream project requires a few patches to meet all our needs. The first one is https://github.com/arun11299/cpp-subprocess/pull/94.
