### ISSUE TITLE
Trivial: Update text spacing in modaloverlay.ui

### ISSUE THREAD

**Issue by hoganri** [bitcoin/bitcoin#24939]
The letter spacing in modaloverlay.ui appears to be broken in OSX Catalina or later due to a bug in QT that affects versions <5.15 (currently core uses 5.12.11). Here is the relevant QT bug report: https://bugreports.qt.io/browse/QTBUG-88495

<img width="1088" alt="modaloverlay-text-spacing" src="https://user-images.githubusercontent.com/36215881/164508454-80314a67-9b27-4fd8-830c-3759b6e47ee8.png">

**Comment by hebasto** [comment]
> currently core uses 5.12.11

Actually, 5.15.3

See https://github.com/bitcoin/bitcoin/pull/24668

**Comment by hebasto** [comment]
Could this issue be closed?
