### ISSUE TITLE
RPC `getblockfrompeer` returns an error with bitcoin-cli

### ISSUE THREAD

**Issue by mbh86** [bitcoin/bitcoin#24943]
I encounter an error with new command `getblockfrompeer`.

```
bitcoin-cli getblockfrompeer "000000000000034a7dedef4a161fa058a2d67a173a90155f3a2fe6fc132e0ebf" 0
error code: -1
error message:
JSON value is not an integer as expected
 ```

It's working with curl:
```
curl -v --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockfrompeer", "params": ["000000000000034a7dedef4a161fa058a2d67a173a90155f3a2fe6fc132e0ebf", 0] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```

I use the version bitcoin-core-23.0/test.rc5/bitcoin-23.0rc5-arm64-apple-darwin.dmg

**Comment by jonatack** [comment]
Looks like an RPCTypeCheck is missing, will fix.

**Comment by jonatack** [comment]
@mbh86 can you try with #24944?

**Comment by jonatack** [comment]
@mbh86

A couple possible issues:
- maybe you didn't run the CLI command from the right directory (e.g. I can reproduce your issue by running it in v0.18, whereas in v23.0 you should see "Block already downloaded")
- the error message itself isn't ideal for a bitcoin-cli call; #24944 improves that and adds test coverage for invalid arguments

**Comment by MarcoFalke** [comment]
What is `bitcoin-cli -version`?

**Comment by matthieu-ppz** [comment]
Hi @jonatack,
Thanks a lot for your feedback and helpful info!

Yes you are right, I have the wrong version of bitcoind:
```
$ bitcoin-cli -version
Bitcoin Core RPC client version v22.0.0
```
It seems there are no bitcoin-cli built in the dmg file.
So either I have to configure & build it for v23 for now or wait for official release with homebrew for example.

**Comment by mbh86** [comment]
Hi @jonatack, Thanks a lot for your feedback and helpful info!

Yes you are right, I have the wrong version of bitcoind:

```
$ bitcoin-cli -version
Bitcoin Core RPC client version v22.0.0
```

It seems there are no bitcoin-cli built in the dmg file. 
So either I have to configure & build it for v23 for now or wait for official release with homebrew for example.

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by MarcoFalke** [comment]
Can this be closed, given that we have no influence over homebrew?

**Comment by fanquake** [comment]
> over homebrew?

Looks like it has been bumped to 23.0 there now in any case: https://github.com/Homebrew/homebrew-core/pull/100174.

**Comment by mbh86** [comment]
Thanks @fanquake and all of you, solved as expected :)
