### ISSUE TITLE
fs::create_directories causes crashes in multiple places when lacking write permission

### ISSUE THREAD

**Issue by mruddy** [bitcoin/bitcoin#24953]
**Expected behavior**

I expected for the program to keep executing, or to shutdown gracefully, after having displayed and/or logged messages/warnings telling me that write permissions are lacking on the involved filesystem resources. This can affect attempting to write to directories outside of the normal bitcoin data directory and/or blocks directory, as seen in my second example below. The nastier crashes are like the ones in the GUI settings that could happen concurrent to data modification. Those could lead to data corruption when files are not flushed, and/or data gets out of synch.

**Actual behavior**

The program logged a runaway exception and immediately aborted.

**To reproduce**

This can be reproduced in multiple ways since there are many references to `fs::create_directories`. Also, crashes can result from restrictive `umask` settings too since some calls attempt to create directories multiple levels deep.

Here are two easy ways:

1. bitcoind "-blocksdir not writable"
    1. start with the command line: `mkdir /tmp/blocks && chmod 0500 /tmp/blocks && ./src/bitcoind -blocksdir=/tmp/blocks`
    2. the program will immediately crash with this logged in the console:
```
************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Permission denied [/tmp/blocks/blocks]       
bitcoin in AppInit()
```
2. bitcoin-qt "Start Bitcoin Core on system login
    1. start with the command line: `mkdir -p /tmp/btc && mkdir -p /tmp/crash && chmod 0500 /tmp/crash && XDG_CONFIG_HOME=/tmp/crash ./src/qt/bitcoin-qt -debug -datadir=/tmp/btc -connect=0`
    4. in the GUI go to the `Settings` menu and select `Options...`
    5. check `Start Bitcoin Core on system login`
![settings](https://user-images.githubusercontent.com/6440430/164890624-f335ed11-96c1-460a-b6eb-7204c079b3d9.png)
    6. click OK. you will be presented with the exception as:
![exception](https://user-images.githubusercontent.com/6440430/164890658-393a5303-6924-494c-a955-a3f2cc2d870c.png)
    7. the console will show:
```
************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Permission denied [/tmp/crash/autostart]       
bitcoin in Runaway exception       

bitcoin-qt: ./checkqueue.h:204: CCheckQueue<T>::~CCheckQueue() [with T = CScriptCheck]: Assertion `m_worker_threads.empty()' failed.
Aborted (core dumped)
```

**System information**

This affects current master branch as of at least be7a5f2fc400e7a3ef72dedbdcf49dd6c96d4f9e. Tested on Ubuntu 21.10.

**Comment by laanwj** [comment]
I wouldn't consider these as bugs. The error, and even the cause of the error "permission denied" is logged or printed, right? Sure, messages could always be nicer, but there's an infinite amount of things that can be wrong with the file system, or underlying assumptions that could be broken, it's not possible to special-case all of them.

**Comment by mruddy** [comment]
I think the 2nd example (the one in the GUI) is a good example that this is a bug because: 1) the crash can cause data loss, 2) it goes beyond the scope of thinking that everything in the data directory has to be writable by the node because it deals with a directory outside of the bitcoin node's data directory. For that one, if you don't set the env var `XDG_CONFIG_HOME`, like I did to make the test easily reproducible and lightweight, then the default will try to create `$HOME/.config/autostart`, if it does not exist. If this ends up not being considered a bug, then we should definitely document that having write permissions available on `$HOME/.config` is a prereq for bitcoin-qt to not crash suddenly.
