### ISSUE TITLE
-onlynet=onion plus -onlynet=ipv4/etc, without -onion=, in spite of -torcontrol= specified, incorrectly kills startup

### ISSUE THREAD

**Issue by midnightmagic** [bitcoin/bitcoin#24980]
In v22, using the options: -onlynet=onion -onlynet=ipv4 -onlynet=ipv6, combined with the options -torcontrol= (etc) functioned and bitcoind correctly pulled the onion socks address via a probe to tor. In v23, that combination of options no longer functions and -onion= is required.

** expected **

Using -onlynet=onion (and ipv4 and ipv6) if -torcontrol= is specified should still work.

**Actual behavior**

bitcoind refuses to start up due to commitid e53a8505db preventing it from doing so in init.cpp.

**To reproduce**

Run as per above.

**System information**

Sources built from fcf6c8f4eb217763545ede1766831a6b93f583bd (tag v23.0 as of this writing I .. think?)

Error message in debug.log is:

Error: Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is not provided
(no -proxy= and no -onion= given) or it is explicitly forbidden (-onion=0)
Shutdown: In progress...
scheduler thread exit
Shutdown: done

**Comment by vasild** [comment]
Actually, the relevant setting here is `-listenonion=1`, not `-torcontrol=...`: if `-listenonion=1`, then we would connect to "Tor control" (using `-torcontrol=` if given or the default `127.0.0.1:9051`) and may retrieve a Tor proxy from there.

Working on a fix.

**Comment by vasild** [comment]
A fix is in https://github.com/bitcoin/bitcoin/pull/24991. @midnightmagic does it resolve the problem for you?

**Comment by midnightmagic** [comment]
Oh, you totally pinged me. I didn't receive it. I did notice the recent commentary and fiddlings in PR#24991. Would you like me to wait until that's resolved before testing?

**Comment by vasild** [comment]
Would be nice if you can test whether that PR resolves the issue for you. The PR is good to go IMO.

**Comment by schildbach** [comment]
Unfortunately, bitcoind 24.0rc4 doesn't completely fix this issue for me. See https://github.com/bitcoin/bitcoin/issues/26478
