### ISSUE TITLE
Multiplication result may overflow

### ISSUE THREAD

**Issue by ImanSharaf** [bitcoin/bitcoin#24990]
I believe there is chance of overflow due to multiplication in [this](https://github.com/bitcoin/bitcoin/blob/master/src/crypto/muhash.cpp#L49) line of code.

**Comment by MarcoFalke** [comment]
I haven't looked at this line, but unsigned integer overflow is very common and intentional in `src/crypto`.

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by MarcoFalke** [comment]
See also https://github.com/bitcoin/bitcoin/blob/bd616bc16a3a7f70f60ca5034b5a91e5ac89ac9d/src/test/crypto_tests.cpp#L940
