### ISSUE TITLE
The problem of repeated calls

### ISSUE THREAD

**Issue by guoyl** [bitcoin/bitcoin#24996]
In the https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp
void PeerManagerImpl::FindNextBlocksToDownload(.....)
......
for (const CBlockIndex* pindex : vToFetch) {
            if (!pindex->IsValid(BLOCK_VALID_TREE)) {
                // We consider the chain that this peer is on invalid.
                return;
            }
            if (!State(nodeid)->fHaveWitness && DeploymentActiveAt(*pindex, consensusParams, Consensus::DEPLOYMENT_SEGWIT)) {
                // We wouldn't download this block or its descendants from this peer.
                return;
            }
......
In fact, the State(nodeid) returns variable is already initialized at the beginning of the function, there is no need to repeat the call here.   In addition, the fHaveWitness is only set in the NetMsgType::VERSION phase.

**Comment by MarcoFalke** [comment]
Pretty sure this will be fixed as part of #19398
