### ISSUE TITLE
wallet: Sync progress not saved if interrupted

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#25010]
_Originally posted by @S3RK in https://github.com/bitcoin/bitcoin/pull/24984#pullrequestreview-952900468_

> With current implementation we don't save the rescan progress and on the next load we will have to start from scratch. Is it possible to save the last processed blocked at shutdown?

It would be nice if wallet code would call `WriteBestBlock` and save the last scan position if it is interrupted during a sync. This could be implemented by trying to save the scan position during the shutdown, or by just periodically saving the scan position after an interval, similar to indexing code which saves sync position once every 30 seconds:

https://github.com/bitcoin/bitcoin/blob/f0a834e2f10a0aa60c7cc76e9f3eb090168a32e5/src/index/base.cpp#L170-L175

**Comment by Ghtdtyfugi0gpuc** [comment]
https://github.com/bitcoin/bitcoin/pull/25036#issue-1221629003

**Comment by Ghtdtyfugi0gpuc** [comment]
100

**Comment by Ghtdtyfugi0gpuc** [comment]
2

**Comment by Ghtdtyfugi0gpuc** [comment]
Yaghoob
