### ISSUE TITLE
On node startup, load mempool from peers ?

### ISSUE THREAD

**Issue by mbh86** [bitcoin/bitcoin#25018]
Let's say I shutdown my bitcoin node for one hour, the default behaviour at the startup is to load the file mempool.dat but all transactions that were broadcasted during this outage will not appear.
I tried to disable the saving and loading with `persistmempool=0` but it starts with an empty mempool on startup.
How can I get the full list of unconfirmed transactions on a restart?

**Comment by sipa** [comment]
There is no way to do that with the protocol currently implemented by Bitcoin Core. There is the BIP35 "mempool" message, but it is currently only available when explicitly enabling peer filtering (BIP111), because of its enormous DoS risk.

**Comment by MarcoFalke** [comment]
Maybe this is best solved outside of the P2P protocol. It shouldn't be too hard to write a script to dump the mempool on one of your other nodes (or a centralized service, if you don't have other nodes) and then import the dump?

**Comment by sipa** [comment]
@MarcoFalke Well, or copy the mempool.dat file.

**Comment by mbh86** [comment]
Thanks a lot @sipa @MarcoFalke.
