### ISSUE TITLE
BUG  ./configure  /install

### ISSUE THREAD

**Issue by mahyariiii** [bitcoin/bitcoin#25035]
After the latest update
Can not be installed
In the ./configure section with the following problem

 ./configure

.
.
.
checking dependency style of g++... gcc3
checking whether g++ supports C++17 features with -std=c++17... yes
checking whether std::atomic can be used without link library... yes
checking whether std::filesystem can be used without link library... no
checking whether std::filesystem needs -lstdc++fs... no
checking whether std::filesystem needs -lc++fs... configure: error: in `/home/bi                                                                             tcoin':
configure: error: cannot figure out how to use std::filesystem
See `config.log' for more details

**Comment by MarcoFalke** [comment]
What OS/gcc version?

**Comment by mahyariiii** [comment]
> OS/gcc version?

Ubuntu 18.04

**Comment by MarcoFalke** [comment]
You'll need to install gcc-8 or clang-10 and pass them to configure.


CC=gcc-8 CXX=g++-8 ./configure
or
CC=clang-10 CXX=clang++-10 ./configure

**Comment by mahyariiii** [comment]
> You'll need to install gcc-8 or clang-10 and pass them to configure.
> 
> CC=gcc-8 CXX=g++-8 ./configure or CC=clang-10 CXX=clang++-10 ./configure


Hello
I installed both and again the same problem when requesting ./configure

**Comment by sipa** [comment]
You need to run `CC=gcc-8 CXX=g++-8 ./configure`

**Comment by mahyariiii** [comment]
thank you  after install  gcc-8  g++-8 ......
this problem was solved with this command

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 40

**Comment by BitcoinMechanic** [comment]
Having the same issue on Mac OS 10.14.x - intel processor.

`CC=gcc-8 CXX=g++-8 ./configure` does not work.

error:

```
checking whether std::atomic can be used without link library... yes
checking whether std::filesystem can be used without link library... no
checking whether std::filesystem needs -lstdc++fs... no
checking whether std::filesystem needs -lc++fs... configure: error: in `/Users/xxx/bitcoin/bitcoin':
configure: error: cannot figure out how to use std::filesystem
```
