### ISSUE TITLE
version `GLIBC_2.18' not found at BTC core 23.0

### ISSUE THREAD

**Issue by paperfrog95** [bitcoin/bitcoin#25059]
We manage BTC core with dockers,

But the 23.0 version of the container doesn't work.

```
Starting bitcoin ... done
Attaching to bitcoin
bitcoin              | ./bin/bitcoind: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./bin/bitcoind)
bitcoin              | Invalid config file
bitcoin exited with code 0
```

We have used 23.0 version without any problems.
We used the file we received from the address below,
[bitcoin-23.0-x86_64-linux-gnu.tar.gz](https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-x86_64-linux-gnu.tar.gz)

Is there a change in the specifications required by 23.0?

**Comment by fanquake** [comment]
The minimum required version of glibc to run `bitcoind` is now 2.18 after https://github.com/bitcoin/bitcoin/pull/23511. Looks like that change never ended up making it into the 23.0 release notes.

**Comment by prusnak** [comment]
> We manage BTC core with dockers,

What do you use as a base image for your Docker containers?

**Comment by paperfrog95** [comment]
@prusnak  
https://bitcoincore.org/bin/bitcoin-core-23.0/
Use the file that Bitcoin provides!

**Comment by paperfrog95** [comment]
@fanquake Is there going to be any further updates on this?

**Comment by MarcoFalke** [comment]
I recommend to fix the issue on your side by upgrading your docker base OS.

**Comment by fanquake** [comment]
> @fanquake Is there going to be any further updates on this?

No. If you run bitcoind in Docker, then as mentioned, you should use a more recent OS in your container.
