### ISSUE TITLE
Guix build w/o substitutes failing at libgit2 check

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#25082]
This is an upstream Guix issue ([55273](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=55273)), but they seem to be planning to resolve it with a version bump, and either way we have versions pinned I think.

```
building /gnu/store/myai2xf4f0z2nr331mx2y4xr4jv1lwid-libgit2-1.3.0.drv...
| 'unpack' phaseild-log 356 178
`/gnu/store/xa8yg9nvawhfvk6hv8lhif9z5pybzan5-libgit2-1.3.0-checkout/tests/resources/status/staged_delete_modified_file' -> `./tests/resources/status/staged_delete_modified_file'
 17% [########################                                                                                                                           ]ild-log 356 189
/tmp/guix-build-libgit2-1.3.0.drv-0/source/src/regexp.c:148:5: warning: ?error? may be used uninitialized in this function [-Wmaybe-uninitialized]
  148 |  if (error < 0)
      |     ^
 17% [########################                                                                                                                           ]ild-log 356 72
[ 18%] Building C object src/CMakeFiles/git2internal.dir/repository.c.o
| 'check' phasenote: keeping build directory `/tmp/guix-build-libgit2-1.3.0.drv-0'
builder for `/gnu/store/myai2xf4f0z2nr331mx2y4xr4jv1lwid-libgit2-1.3.0.drv' failed with exit code 1
build of /gnu/store/myai2xf4f0z2nr331mx2y4xr4jv1lwid-libgit2-1.3.0.drv failed
```

```
refs::revparse.................F

  1) Failure:
refs::revparse::date [/tmp/guix-build-libgit2-1.3.0.drv-0/source/tests/refs/revparse.c:31]
  Function call succeeded: error
  no error, expected non-zero return
```

**Comment by luke-jr** [comment]
Workaround for now:

```
guix build --without-tests=libgit2 libgit2
```

**Comment by dongcarl** [comment]
Found the problem: https://github.com/libgit2/libgit2/pull/6299

Will think about the right solution for us...

**Comment by dongcarl** [comment]
Looks like the Guix devs got to it first... https://issues.guix.gnu.org/55326

Curious why that was allowed in master since I'd assume it'll cause a mass rebuild...

**Comment by dongcarl** [comment]
Urgh I shoulda checked `guix refresh --list-dependent libgit2`, bumping `libgit2` would only cause 70 packages to be rebuilt

**Comment by luke-jr** [comment]
Workaround: Setting the system clock back to 2021-05-11, touching all files under the bitcoin source dir, and running guix-build until libgit2 completes. (Afterward, for sanity, I Ctrl-C'd it, set a correct clock back, re-touched all the files, and ran guix-build again to complete)

Hopefully we can figure out a real fix eventually.

**Comment by luke-jr** [comment]
Workaround: Setting the system clock back to 2021-05-11, touching all files under the bitcoin source dir, and running guix-build until libgit2 completes. (Afterward, for sanity, I Ctrl-C'd it, set a correct clock back, re-touched all the files, and ran guix-build again to complete)

Hopefully we can figure out a real fix eventually.

**Comment by luke-jr** [comment]
This should probably remain open until there's a clean way to build existing tags

**Comment by Sjors** [comment]
Ran into this when trying to build v23.1rc2 (on a machine that so far only has the Guix version used by v24.0).

As mentioned above, it can be worked around by messing with the system clock:

```
sudo timedatectl set-ntp no
sudo date --set "21 may 2021 00:00:00"
# as your guix user
guix build --cores=1 /gnu/store/myai2xf4f0z2nr331mx2y4xr4jv1lwid-libgit2-1.3.0.drv

sudo timedatectl set-ntp yes
```
