### ISSUE TITLE
walletpassphrase gives error "must request wallet RPC through /wallet/<filename>"

### ISSUE THREAD

**Issue by dynamo-foundation** [bitcoin/bitcoin#25080]
When issuing an RPC for walletpassphrase, the following error is returned:

_{\"result\":null,\"error\":{\"code\":-19,\"message\":\"Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).\"},\"id\":0}_

Documentation from here:
_https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/walletpassphrase/_
states sample call looks like this:
_As a JSON-RPC call
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "walletpassphrase", "params": ["my pass phrase", 60]}' -H 'content-type: text/plain;' http://127.0.0.1:8332/_
(e.g. no /wallet/<filename> in the RPC)

Further, my issue stems from wallet names with embedded spaces, for example "encrypted with space".  QT allows for the creation of wallet names with spaces (and other characters), which are not valid in a URI, at least as plain text.

The CLI functions as expected when issued with the rpcwallet parameter, and allows for spaces because the wallet name is enclosed in double quotes.

At a minimum the docs should reflect the proper usage of the RPC call, however its unclear how support for wallet names with internal spaces would be supported at all given the current design.  A better design would be to add the wallet name as a parameter in the array to avoid using different URIs which is inconsistent with the usage of all other RPCs in core.

BTC 0.21

**Comment by dynamo-foundation** [comment]
I'm going to have to disagree with you.  This is not a question or help.  The RPC does not support URL encoded wallet names with spaces.  If you have a wallet name with an embedded space and you issue an RPC like 

_http://192.168.4.48:6433/wallet/encrypted+with+space_

It fails with "wallet not found", which is a bug.  The wallet does exist; the RPC doesnt properly handle embedded spaces.  I will highlight the RPC code issues shortly.

**Comment by achow101** [comment]
I believe you can percent encode the spaces.

**Comment by dynamo-foundation** [comment]
%20 did it - still feels very hacky - this is not really a URI - thats a data parameter

line 14 of url.cpp, parameter 2 should be "true" not "false" - to allow support for + to space translation of what is clearly a data param and not a URI
