### ISSUE TITLE
when can use tap root ? is there any document for tap root developer ?

### ISSUE THREAD

**Issue by dnsdev9** [bitcoin/bitcoin#25105]
when can use tap root ? is there any document for tap root developer ?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
