### ISSUE TITLE
when running ./autogen.sh with newest 

### ISSUE THREAD

**Issue by Casper0513** [bitcoin/bitcoin#25138]
root@gemoneycoin-GL75-Leopard-10SDK:/home/gemoneycoin/bitcoin# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:35: installing 'build-aux/compile'
configure.ac:30: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:15: error: possibly undefined macro: PKG_CHECK_MODULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:3149: error: possibly undefined macro: _PKG_ERRORS
autoreconf: /usr/bin/autoconf failed with exit status: 1

Ubuntu 20.04 LTS
m4 (GNU M4) 1.4.18

**Comment by fanquake** [comment]
Is pkg-config installed?

**Comment by Casper0513** [comment]
yes its definitely installed everything that's supposed is installed

**Comment by Casper0513** [comment]
is this possible from name changes configure.ca file

**Comment by Casper0513** [comment]
> yes its definitely installed everything that's supposed is installed
