### ISSUE TITLE
 when running ./autogen.sh I keep getting errors even though pkg-config IS installed

### ISSUE THREAD

**Issue by Casper0513** [bitcoin/bitcoin#25139]
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:35: installing 'build-aux/compile'
configure.ac:30: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:1352: error: possibly undefined macro: PKG_CHECK_MODULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by fanquake** [comment]
There was no need to open a new issue. You'll need to provide more information. Are you building master? On what OS? What version(s) of our build dependencies?

**Comment by Casper0513** [comment]
> There was no need to open a new issue. You'll need to provide more information. Are you building master? On what OS? What version(s) of our build dependencies?

yea I know I hit the closed button by accident. 
Ubuntu 20.04 LTS 
autoconf (GNU Autoconf) 2.69

**Comment by MarcoFalke** [comment]
What commit are you building?

**Comment by Casper0513** [comment]
> What commit are you building?

I know its the master build

**Comment by MarcoFalke** [comment]
Which commit in the master branch?


```
git status && git log -1

**Comment by hebasto** [comment]
@Casper0513 

What is the content of `config.log`?

**Comment by Casper0513** [comment]
> git status && git log -1

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
commit e0fa0b8dea5c817d8f7d9e995b50fc410272a73a (HEAD -> master, origin/master)
Author: Casper0513 <brian_cass102@hotmail.com>
Date:   Mon May 16 06:00:29 2022 -0600

    first commit

**Comment by Casper0513** [comment]
> @Casper0513
> 
> What is the content of `config.log`?

[config.log](https://github.com/bitcoin/bitcoin/files/8704113/config.log)

**Comment by Casper0513** [comment]
root@gemoneycoin-GL75-Leopard-10SDK:/home/gemoneycoin/bitcoin# dpkg -l | grep pkg-config
ii  libextutils-pkgconfig-perl                     1.16-1                              all          Perl interface to the pkg-config utility
ii  librust-pkg-config-dev:amd64                   0.3.17-2                            amd64        Run pkg-config at build time Cargo build scripts - Rust source code
ii  librust-pq-sys+pkg-config-dev:amd64            0.4.6-1                             amd64        Auto-generated rust bindings for libpq - feature "pkg-config"
ii  pkg-config                                     0.29.1-0ubuntu4                     amd64        manage compile and link flags for libraries
ii  pkg-config-aarch64-linux-gnu                   4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for arm64 architecture
ii  pkg-config-alpha-linux-gnu                     4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for alpha architecture
ii  pkg-config-arm-linux-gnueabi                   4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for armel architecture
ii  pkg-config-arm-linux-gnueabihf                 4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for armhf architecture
ii  pkg-config-hppa-linux-gnu                      4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for hppa architecture
ii  pkg-config-i686-linux-gnu                      4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for i386 architecture
ii  pkg-config-m68k-linux-gnu                      4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for m68k architecture
ii  pkg-config-powerpc-linux-gnu                   4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for powerpc architecture
ii  pkg-config-powerpc64-linux-gnu                 4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for ppc64 architecture
ii  pkg-config-powerpc64le-linux-gnu               4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for ppc64el architecture
ii  pkg-config-riscv64-linux-gnu                   4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for riscv64 architecture
ii  pkg-config-s390x-linux-gnu                     4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for s390x architecture
ii  pkg-config-sh4-linux-gnu                       4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for sh4 architecture
ii  pkg-config-sparc64-linux-gnu                   4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for sparc64 architecture
ii  pkg-config-x86-64-linux-gnu:i386               4:9.3.0-1ubuntu2                    i386         manage compile and link flags for libraries for amd64 architecture
ii  pkg-config-x86-64-linux-gnux32                 4:9.3.0-1ubuntu2                    amd64        manage compile and link flags for libraries for x32 architecture

**Comment by MarcoFalke** [comment]
e0fa0b8dea5c817d8f7d9e995b50fc410272a73a is not a Bitcoin Core commit
