### ISSUE TITLE
gettransaction does not contain the field "abandoned" for abandoned receiving tx

### ISSUE THREAD

**Issue by relativisticelectron** [bitcoin/bitcoin#25130]
In specter https://github.com/cryptoadvance/specter-desktop/issues/1491#issuecomment-1126145011  a user can abandon an **receiving** tx that was evicted from the mempool (for example because it was double spent). The tx is marked via [abandontransaction](https://github.com/bitcoin-dot-org/developer.bitcoin.org/blob/master/reference/rpc/abandontransaction.rst) as abandoned in bitcoin core.

However [gettransaction](https://github.com/bitcoin-dot-org/developer.bitcoin.org/blob/master/reference/rpc/gettransaction.rst) and [listtransactions](https://github.com/bitcoin-dot-org/developer.bitcoin.org/blob/master/reference/rpc/listtransactions.rst) do not return the field `abandoned`, even though this is visible in the GUI:

![image](https://user-images.githubusercontent.com/60378539/168316171-45c1aa29-de52-4d9a-ae2b-3293aeadd663.png)

**Consequence**: Specter cannot get the `abandoned` information from bitcoin rpc, and will fetch the abandoned tx back again via [listtransactions](https://github.com/bitcoin-dot-org/developer.bitcoin.org/blob/master/reference/rpc/listtransactions.rst) after it was deleted in specter.   

**Describe the solution you'd like**
Always return the `abandoned` field in https://github.com/bitcoin/bitcoin/blob/225e5b57b2ee2bc1acd7f09c89ccccc15ef8c85f/src/wallet/rpc/transactions.cpp#L345  and not only in this special case https://github.com/bitcoin/bitcoin/blob/225e5b57b2ee2bc1acd7f09c89ccccc15ef8c85f/src/wallet/rpc/transactions.cpp#L375
That should then automatically solve  [gettransaction](https://github.com/bitcoin-dot-org/developer.bitcoin.org/blob/master/reference/rpc/gettransaction.rst)  via https://github.com/bitcoin/bitcoin/blob/225e5b57b2ee2bc1acd7f09c89ccccc15ef8c85f/src/wallet/rpc/transactions.cpp#L795

**Describe alternatives you've considered**
If specter can't get the information about abandoned tx from bitcoin, it would have to keep an internal list. That is possible, but redundant and can lead to many edge cases.

**Steps to reproduce**

- Wallet A:  Send 1 BTC to Wallet B  (rbf)
- Wallet A:  Replace tx with rbf to send all funds to wallet A
- Wallet B: Abandon tx (because no longer in mempool)
- Wallet B:  [gettransaction](https://github.com/bitcoin-dot-org/developer.bitcoin.org/blob/master/reference/rpc/gettransaction.rst) will not show the  `abandoned` field

**Comment by brunoerg** [comment]
I can work on it!

**Comment by relativisticelectron** [comment]
> I can work on it if it gets some concept ACKs

Wow, that would be great. Thanks!

**Comment by luke-jr** [comment]
"Abandoned" means the wallet in question will attempt to re-use the inputs of the transaction, but that doesn't make any sense for transactions that aren't sent from the wallet...

**Comment by brunoerg** [comment]
@luke-jr so, why this is visible in the GUI? Do you know?

**Comment by luke-jr** [comment]
Likely it just checks the abandoned flag without checking if it was sent or received.

The real bug here is probably that `abandontransaction` should fail.

**Comment by sipa** [comment]
Abandoning also means it won't be rebroadcasted anymore, I think? If so, that does make sense for received transactions too.

**Comment by brunoerg** [comment]
> "Abandoned" means the wallet in question will attempt to re-use the inputs of the transaction

I am not sure if I agree with this definition of "abandoned".

**Comment by luke-jr** [comment]
Perhaps #25158 should change the description as well then ;)

**Comment by Mama54y** [comment]
Feature label
