### ISSUE TITLE
`make check` freeze

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#25185]
I am compiling Bitcoin Core:

`make`
`make check`

gets stuck on:

> Running bench/bench_bitcoin (one iteration sanity check)...
> bench/bench_bitcoin --sanity-check > /dev/null

I interrupt the process:

> make[3]: *** [Makefile:20873: check-local] Interrupt
> make[2]: *** [Makefile:18979: check-am] Interrupt
> make[1]: *** [Makefile:18636: check-recursive] Interrupt
> make: *** [Makefile:818: check-recursive] Interrupt

However, I then successfully can run all functional and util tests:

`test/functional/python3 test_runner.py --extended`

`test/util/python3 test_runner.py -v`

Happens every time.

master (640eb772e55671c5dab29843cebe42ec35cb703f), self-compiled

Qubes 4.0, Debian 11 Standard VM, x86

**Comment by hebasto** [comment]
It's a known issue with WalletLoad benchmark. See #24924.

**Comment by Rspigler** [comment]
Ah, my apologies.
