### ISSUE TITLE
Bitcoin core will not compile on Windows 11

### ISSUE THREAD

**Issue by LordOfDisdain** [bitcoin/bitcoin#25195]
I have ran into several issues during my compiling of Bitcoin. I have tried to compile this thing but each time I try to do so, there is a new issue. For reference I am using Ubuntu Bash terminal to compile Bitcoin. My operating system is Windows 11 and I have tried everything I know to troubleshoot this issue. I have downloaded clang, mingw g++ and I will attach the a photo to explain this issue. Each time I try to use the ./configure, ./autogen.sh and sudo make, there seems to be issues and this will not compile at all. Any help will be greatly appreciated. Thank you! PS. I have also created a virtual environment and I have installed the necessary tools for it as well. 
![Bitcoin Error](https://user-images.githubusercontent.com/42873006/169974755-3155d988-6051-426b-b339-d0a7a326a9d4.png)

 I expected the Bitcoin Core to compile.

 

 The version of Bitcoin core is version 23.0 I have forked it from the bitcoin GitHub Bitcoin page.

 I am using an ASUS X555Y series Laptop.

 My operating system is Windows 11.

[config.log](https://github.com/bitcoin/bitcoin/files/8760431/config.log)

**Comment by hebasto** [comment]
> I have also created a virtual environment

Do you mean WSL?

**Comment by LordOfDisdain** [comment]
WSL? I'm lost with the acronyms at times.

> > I have also created a virtual environment
> 
> Do you mean WSL?

**Comment by hebasto** [comment]
@LordOfDisdain 

I mean, there are two [supported ways](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md) to build Bitcoin Core on a Windows:
- using Windows Subsystem for Linux (WSL)
- using Microsoft VS tools

I was trying to understand what does "using Ubuntu Bash terminal to compile Bitcoin" mean exactly...

**Comment by LordOfDisdain** [comment]
> @LordOfDisdain
> 
> I mean, there are two [supported ways](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md) to build Bitcoin Core on Windows:
> 
>     * using Windows Subsystem for Linux (WSL)
> 
>     * using Microsoft VS tools
> 
> 
> I was trying to understand what does "using Ubuntu Bash terminal to compile Bitcoin" mean exactly...

I understand now. I was using the WSL because my OS is Windows 11.

**Comment by hebasto** [comment]
Ok. From you screenshot it is not clear if you follow https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows, especially, building depends
```
cd depends
make HOST=x86_64-w64-mingw32
cd ..
```
?

**Comment by LordOfDisdain** [comment]
> Ok. From you screenshot it is not clear if you follow https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows, especially, building depends
> 
> ```
> cd depends
> make HOST=x86_64-w64-mingw32
> cd ..
> ```
> 
> ?

I did not follow that. I will look into that and if I have some issues I will update this issue list. Thanks!

**Comment by hebasto** [comment]
Closing for now. Feel free to reopen this issue at anytime.

**Comment by LordOfDisdain** [comment]
Here is the config log! My apologizes for not attaching it in the prior message.
[Uploading config.log…]()
