### ISSUE TITLE
"rpc.cpp:3956" "internal bug detected 'unique'"

### ISSUE THREAD

**Issue by etherx-dev** [bitcoin/bitcoin#25206]
I loaded the wallet in a different format, seen this happen before with i loaded in regtesy and label was over written. I do suspect it might be from loading keys wallet data from a dogecoin wallet file. 

**Actual behavior** getaddressesbylabel ""

Camera shy
**To reproduce**

I have an issue with my key pool, cant figure out why i have this change address STILL SHOWING UP, but keypool cannot return it. Oh well ill finally learn c++
**System information**

**Comment by MarcoFalke** [comment]
Please provide the exact commit or version you are using. Otherwise there is nothing we can do
