### ISSUE TITLE
Issues with compiling Bitcoin using the Depends folder Bitcoin Core version 23.0

### ISSUE THREAD

**Issue by LordOfDisdain** [bitcoin/bitcoin#25209]
Hello everyone. I have ran into a make host issue while doing the steps needed to compile Bitcoin on my computer. Below is a screenshot of the situation and the steps detailed I used to get this program working. For another reference, I followed the steps to compile Bitcoin from these links: 
https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows

https://github.com/bitcoin/bitcoin/blob/master/depends/README.md
The screen shot below shows everything else. Thank you for your time.
![New Bitcoin issue](https://user-images.githubusercontent.com/42873006/170236050-1605460f-15b5-4ebc-9ee3-507762db8693.png)

**Expected behavior**
To compile normally to finish compiling the core on my laptop

**Actual behavior**
A makefile error

**To reproduce**

**System information**

I am using Bitcoin Core 23.0

I am using Windows 11 as my operating system and WSL for the terminal.

**Comment by LordOfDisdain** [comment]
Am I missing things that I need to add to fix this error?

**Comment by LordOfDisdain** [comment]
Do I need to add any more snapshots?

**Comment by MarcoFalke** [comment]
What version of Ubuntu are you using?

**Comment by LordOfDisdain** [comment]
> What version of Ubuntu are you using?

I am using Ubuntu version 18.04.5. I have moved the file to the Linux subsystem on my computer and more issues sprang up. For starters I cannot change my directory to the subsystem because the file does not exist, which is nonsense because I have checked the official forums by Microsoft and I followed the verbiage to the letter. For some reason, I am unable to build bitcoin on my computer due to it having issues working on a windows environment. So I am completely lost on how to proceed at this point.

**Comment by MarcoFalke** [comment]
I am pretty sure 18.04 is no longer supported to cross compile for windows. Our CI uses Ubuntu Jammy, but Ubuntu Focal may also work (?), though I haven't checked that.

Alternatively you may try the msvc config or download the release binaries.

**Comment by LordOfDisdain** [comment]
> I am pretty sure 18.04 is no longer supported to cross compile for windows. Our CI uses Ubuntu Jammy, but Ubuntu Focal may also work (?), though I haven't checked that.
> 
> Alternatively you may try the msvc config or download the release binaries.

MSVC config? I'm lost. Ubuntu Jammy? How would I get that?

**Comment by MarcoFalke** [comment]
I haven't touched Windows in a decade, so I can't help you here.

**Comment by LordOfDisdain** [comment]
> I haven't touched Windows in a decade, so I can't help you here.

Is there anyone who can? I've had spare to no success on figuring this out on my own.

**Comment by hebasto** [comment]
> Alternatively you may try the msvc config

https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md

**Comment by Geoge1** [comment]
> > What version of Ubuntu are you using?
> 
> I am using Ubuntu version 18.04.5. I have moved the file to the Linux subsystem on my computer and more issues sprang up. For starters I cannot change my directory to the subsystem because the file does not exist, which is nonsense because I have checked the official forums by Microsoft and I followed the verbiage to the letter. For some reason, I am unable to build bitcoin on my computer due to it having issues working on a windows environment. So I am completely lost on how to proceed at this point. 

Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by Geoge1** [comment]
> > I haven't touched Windows in a decade, so I can't help you here.
> 
> Is there anyone who can? I've had spare to no success on figuring this out on my own.

Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by MarcoFalke** [comment]
Also Focal and Jammy seem to be available, after 30 seconds of searching: https://apps.microsoft.com/store/search/Ubuntu
