### ISSUE TITLE
nlocktime bug

### ISSUE THREAD

**Issue by namecoindeveloper** [bitcoin/bitcoin#25225]
**Block height** for `nlocktime` doesn't work.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
