### ISSUE TITLE
Run Bitcoin as Genesis Node in LAN

### ISSUE THREAD

**Issue by UEFI-code** [bitcoin/bitcoin#25347]
Hello, I'm testing my Mining Software, and I want to let this Bitcoin Node run as Genesis Node.

I also want to put 2 Bitcoin Nodes into my LAN, and experiment how it's block difficult changes.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
