### ISSUE TITLE
Mac: app GUI freezes when synchronizing with network

### ISSUE THREAD

**Issue by gen1lee** [bitcoin/bitcoin#25362]
When app is synchronising with network, often app becomes not responsive: Its window is not focused when you press the app icon and it doesn't handle mouse clicks, always showing loader instead of mouse arrow.

It still has some progress loading blocks though. After some time while being focused using F3 button on Mac, it may become responsive.

**Expected behavior**

It should always be responsive.

**Actual behavior**

It is not responsive.

**To reproduce**

Just start synchronizing, probably reproduced better on the last percents.

**System information**

Bitocoin Core 23.0
MacBook Air (M1, 2020)
Mac 12.4

**Comment by jarolrod** [comment]
The qt widgets gui has a problem with locks, especially when doing computationally expensive tasks like syncing. This has been an ongoing issue for a while. This is being worked on as part of the [qml-gui](https://github.com/bitcoin-core/gui-qml) project. 

Additionally, gui related issues should be opened here: https://github.com/bitcoin-core/gui

**Comment by laanwj** [comment]
Yes, this is a well-known issue that has existing for a long time, see #17145.
