### ISSUE TITLE
Upgrade Whole-Wallet Encryption PQ-E and Hard-Code PK to Whole-Wallet Encryption

### ISSUE THREAD

**Issue by Gapcoin1** [bitcoin/bitcoin#25372]
Is your feature request related to a problem? Please describe.

Post-Quantum Encryption Proposal:

    The Problem is that Quantum Computers are forcing upgrades to Encryption Standards

    Upgrading is complicated from code and hardware integration

    There are currently significant serious problems with the current Whole Wallet Encryption that needs upgraded at the same time

    The main problem is that Whole Wallet Encryption is easily by-passed if a PK is broken, Whole Wallet Encryption only protects against "Hot Wallets", the second problem is that AES is very bad Encryption standard to use

Describe the solution you'd like

I came up with a perfect idea to Soft-Fork Bitcoin into PQ-E without a Hard-Forking the Private Key or Hashing Algo, by tieing the Bitcoin Address Private Key Hard-Coded to the Whole-Wallet Encryption, wheras currently the Whole-wallet encryption is not tied to the Private Key and is easily By-Passed if Quantum Computers Hack a Private Key

    Hard-Code the Whole-Wallet Encryption to Protect all Private Keys held by a Wallet instead of the current form only protecting "Hot Wallets"

    Upgrade the Whole-Wallet Encryption to Post-Quantum Falcon-1024 Bit Encryption

    This is the perfect way to soft-fork PQ-E by first upgrading the Whole-Wallet Encryption while at the same time fixing the Gap in it's current form

    If Hard-Coded with a Whole-Wallet PQ-E Algo even a BROKEN Private Key will not be Spendable from the wallet unless the Whole-Wallet PQ-E approves

Describe alternatives you've considered

I have brainstormed the intricacies of upgrading the Private Key system and Hash Algo for Bitcoin

Additional context

This is a unique and strategic way to upgrade Bitcoin and protect against threat actors First Strike against Bitcoin

However Older Cold Wallets that cannot upgrade to PQ-E Whole-Wallet Encryption is still at risk of being hacked and crashing Bitcoin for a period, but this soft-fix makes the Network retain First Mover Dominance

Posting this here for Discussion before a BIP

**Comment by MarcoFalke** [comment]
Discussion about BIPs also happens on the mailing list. Please stop re-creating this issue.
