### ISSUE TITLE
benchmarks: "skip slow benchmarks" option?

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#25377]
Often I'd like to do some quick benchmarks on a slower platform (e.g. RISC-V, ARM32). Various `Wallet*` benchmarks are extremely slow even on state of the art hardware. I think an option to skip slow benchmarks would be useful.

It might be possible with a `-filter=` expression, I'm not sure.

**Comment by saranshisatgit** [comment]
I think this option is already there? isn't it? -- check benchmarking.md 

```
To print the various options, like listing the benchmarks without running them
or using a regex filter to only run certain benchmarks.
```

**Comment by kouloumos** [comment]
This seems to not be an issue as `-filter` accepts a regular expression, which means that something like 
```shell
bench_bitcoin -filter='^(?!Wallet).*'
```
could be used to skip the various `Wallet*` benchmarks.

**Comment by fanquake** [comment]
I agree. I think we can close this for now.
