### ISSUE TITLE
Upgrade Whole-Wallet Encryption PQ-E and Hard-Code PK to Whole-Wallet Encryption

### ISSUE THREAD

**Issue by Gapcoin1** [bitcoin/bitcoin#25371]
**Is your feature request related to a problem? Please describe.**

Post-Quantum Encryption Proposal:

1) The Problem is that Quantum Computers are forcing upgrades to Encryption Standards

2) Upgrading is complicated from code and hardware integration

3) There are currently significant serious problems with the current Whole Wallet Encryption that needs upgraded at the same time

4) The main problem is that Whole Wallet Encryption is easily by-passed if a PK is broken, Whole Wallet Encryption only protects against "Hot Wallets", the second problem is that AES is very bad Encryption standard to use

**Describe the solution you'd like**

I came up with a perfect idea to Soft-Fork Bitcoin into PQ-E without a Hard-Forking the Private Key or Hashing Algo, by tieing the Bitcoin Address Private Key Hard-Coded to the Whole-Wallet Encryption, wheras currently the Whole-wallet encryption is not tied to the Private Key and is easily By-Passed if Quantum Computers Hack a Private Key

1) Hard-Code the Whole-Wallet Encryption to Protect all Private Keys held by a Wallet instead of the current form only protecting "Hot Wallets"

2) Upgrade the Whole-Wallet Encryption to Post-Quantum Falcon-1024 Bit Encryption

3) This is the perfect way to soft-fork PQ-E by first upgrading the Whole-Wallet Encryption while at the same time fixing the Gap in it's current form

4) If Hard-Coded with a Whole-Wallet PQ-E Algo even a BROKEN Private Key will not be Spendable from the wallet unless the Whole-Wallet PQ-E approves

**Describe alternatives you've considered**

I have brainstormed the intricacies of upgrading the Private Key system and Hash Algo for Bitcoin

**Additional context**

This is a unique and strategic way to upgrade Bitcoin and protect against threat actors First Strike against Bitcoin

However Older Cold Wallets that cannot upgrade to PQ-E Whole-Wallet Encryption is still at risk of being hacked and crashing Bitcoin for a period, but this soft-fix makes the Network retain First Mover Dominance

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.
