### ISSUE TITLE
Reproducible Test Failures

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#25385]
I've been having issues performing tests on PRs, so I've tried it multiple times now on master, deleting the directory and starting fresh. This is what I get each time:

`make`

> ...
> ...
> AR       minisketch/libminisketch_clmul.a
>   CXXLD    test/test_bitcoin
> collect2: fatal error: ld terminated with signal 9 [Killed]
> compilation terminated.
> make[2]: *** [Makefile:7539: test/test_bitcoin] Error 1
> make[2]: Leaving directory '/home/user/bitcoin/src'
> make[1]: *** [Makefile:18626: all-recursive] Error 1
> make[1]: Leaving directory '/home/user/bitcoin/src'
> make: *** [Makefile:818: all-recursive] Error 1

`make` a second time, successful

> ...
> ...
> CXX      util/libbitcoinconsensus_la-strencodings.lo
>   CXXLD    libbitcoinconsensus.la
> make[2]: Leaving directory '/home/user/bitcoin/src'
> make[1]: Leaving directory '/home/user/bitcoin/src'
> Making all in doc/man
> make[1]: Entering directory '/home/user/bitcoin/doc/man'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/user/bitcoin/doc/man'
> make[1]: Entering directory '/home/user/bitcoin'
> make[1]: Nothing to be done for 'all-am'.
> make[1]: Leaving directory '/home/user/bitcoin'

user@localhost:~/bitcoin$ `make check`

>  Making check in src
> make[1]: Entering directory '/home/user/bitcoin/src'
> make[2]: Entering directory '/home/user/bitcoin/src'
> make[3]: Entering directory '/home/user/bitcoin'
> make[3]: Leaving directory '/home/user/bitcoin'
> make  check-TESTS check-local
> make[3]: Entering directory '/home/user/bitcoin/src'
> make[4]: Entering directory '/home/user/bitcoin/src'
> PASS: minisketch/test
> PASS: univalue/test/object
> PASS: univalue/test/unitester
> PASS: univalue/test/no_nul
> make[5]: Entering directory '/home/user/bitcoin'
> make[5]: Leaving directory '/home/user/bitcoin'
> PASS: qt/test/test_bitcoin-qt
> Testsuite summary for Bitcoin Core 23.99.0
> '# TOTAL: 5
> '# PASS:  5
> '# SKIP:  0
> '# XFAIL: 0
> '# FAIL:  0
> '# XPASS: 0
> '# ERROR: 0
> make[4]: Leaving directory '/home/user/bitcoin/src'
> Running tests: addrman_tests from test/addrman_tests.cpp
> /bin/bash: line 2: test/test_bitcoin: Permission denied
> make[3]: *** [Makefile:20866: test/addrman_tests.cpp.test] Error 1
> make[3]: Leaving directory '/home/user/bitcoin/src'
> make[2]: *** [Makefile:18969: check-am] Error 2
> make[2]: Leaving directory '/home/user/bitcoin/src'
> make[1]: *** [Makefile:18626: check-recursive] Error 1
> make[1]: Leaving directory '/home/user/bitcoin/src'
> make: *** [Makefile:818: check-recursive] Error 1

Errors also.

user@localhost:~/bitcoin$ `sudo make install`

(No issues).

user@localhost:~/bitcoin/test/functional$ `python3 test_runner.py --extended`

> feature_block.py                                   | ✖ Failed  | 83 s
> feature_dbcrash.py                                 | ✖ Failed  | 2812 s
> feature_pruning.py                                 | ✖ Failed  | 582 s

Details for each failed test:

> 9/245 - feature_block.py failed, Duration: 83 s 

> stdout:
> 2022-06-16T00:32:59.996000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20220615_202813/feature_block_235
> 2022-06-16T00:33:02.154000Z TestFramework (INFO): Reject block with invalid tx: OutputMissing
> 2022-06-16T00:33:02.380000Z TestFramework (INFO): Reject block with invalid tx: InputMissing
> 2022-06-16T00:33:02.587000Z TestFramework (INFO): Reject block with invalid tx: BadInputOutpointIndex
> 2022-06-16T00:33:02.800000Z TestFramework (INFO): Reject block with invalid tx: DuplicateInput
> 2022-06-16T00:33:03.025000Z TestFramework (INFO): Reject block with invalid tx: PrevoutNullInput
> 2022-06-16T00:33:03.195000Z TestFramework (INFO): Reject block with invalid tx: NonexistentInput
> 2022-06-16T00:33:03.411000Z TestFramework (INFO): Reject block with invalid tx: SpendTooMuch
> 2022-06-16T00:33:03.593000Z TestFramework (INFO): Reject block with invalid tx: CreateNegative
> 2022-06-16T00:33:03.769000Z TestFramework (INFO): Reject block with invalid tx: CreateTooLarge
> 2022-06-16T00:33:03.980000Z TestFramework (INFO): Reject block with invalid tx: CreateSumTooLarge
> 2022-06-16T00:33:04.192000Z TestFramework (INFO): Reject block with invalid tx: TooManySigops
> 2022-06-16T00:33:04.464000Z TestFramework (INFO): Don't reorg to a chain of the same length
> 2022-06-16T00:33:04.571000Z TestFramework (INFO): Reorg to a longer chain
> 2022-06-16T00:33:04.724000Z TestFramework (INFO): Reorg back to the original chain
> 2022-06-16T00:33:05.109000Z TestFramework (INFO): Reject a chain with a double spend, even if it is longer
> 2022-06-16T00:33:05.454000Z TestFramework (INFO): Reject a block where the miner creates too much coinbase reward
> 2022-06-16T00:33:05.665000Z TestFramework (INFO): Reject a chain where the miner creates too much coinbase reward, even if the chain is longer
> 2022-06-16T00:33:06.023000Z TestFramework (INFO): Reject a chain where the miner creates too much coinbase reward, even if the chain is longer (on a forked chain)
> 2022-06-16T00:33:06.314000Z TestFramework (INFO): Accept a block with lots of checksigs
> 2022-06-16T00:33:06.442000Z TestFramework (INFO): Reject a block with too many checksigs
> 2022-06-16T00:33:06.698000Z TestFramework (INFO): Reject a block with a spend from a re-org'ed out tx
> 2022-06-16T00:33:06.908000Z TestFramework (INFO): Reject a block with a spend from a re-org'ed out tx (on a forked chain)
> 2022-06-16T00:33:07.227000Z TestFramework (INFO): Reject a block spending an immature coinbase.
> 2022-06-16T00:33:07.440000Z TestFramework (INFO): Reject a block spending an immature coinbase (on a forked chain)
> 2022-06-16T00:33:07.715000Z TestFramework (INFO): Accept a block of weight MAX_BLOCK_WEIGHT
> 2022-06-16T00:33:07.983000Z TestFramework (INFO): Reject a block of weight MAX_BLOCK_WEIGHT + 4
> 2022-06-16T00:33:08.378000Z TestFramework (INFO): Reject a block with coinbase input script size out of range
> 2022-06-16T00:33:09.150000Z TestFramework (INFO): Accept a block with the max number of OP_CHECKMULTISIG sigops
> 2022-06-16T00:33:09.277000Z TestFramework (INFO): Reject a block with too many OP_CHECKMULTISIG sigops
> 2022-06-16T00:33:09.447000Z TestFramework (INFO): Accept a block with the max number of OP_CHECKMULTISIGVERIFY sigops
> 2022-06-16T00:33:09.509000Z TestFramework (INFO): Reject a block with too many OP_CHECKMULTISIGVERIFY sigops
> 2022-06-16T00:33:09.741000Z TestFramework (INFO): Accept a block with the max number of OP_CHECKSIGVERIFY sigops
> 2022-06-16T00:33:09.818000Z TestFramework (INFO): Reject a block with too many OP_CHECKSIGVERIFY sigops
> 2022-06-16T00:33:10.069000Z TestFramework (INFO): Reject a block spending transaction from a block which failed to connect
> 2022-06-16T00:33:10.434000Z TestFramework (INFO): Check P2SH SIGOPS are correctly counted
> 2022-06-16T00:33:18.330000Z TestFramework (INFO): Reject a block with too many P2SH sigops
> 2022-06-16T00:33:57.687000Z TestFramework (INFO): Accept a block with the max number of P2SH sigops
> 2022-06-16T00:34:01.161000Z TestFramework (INFO): Build block 44 manually
> 2022-06-16T00:34:01.182000Z TestFramework (INFO): Reject a block with a non-coinbase as the first tx
> 2022-06-16T00:34:01.393000Z TestFramework (INFO): Reject a block with no transactions
> 2022-06-16T00:34:01.605000Z TestFramework (INFO): Reject a block with invalid work
> 2022-06-16T00:34:01.835000Z TestFramework (INFO): Reject a block with a timestamp >2 hours in the future
> 2022-06-16T00:34:01.897000Z TestFramework (INFO): Reject a block with invalid merkle hash
> 2022-06-16T00:34:02.059000Z TestFramework (INFO): Reject a block with incorrect POW limit
> 2022-06-16T00:34:02.271000Z TestFramework (INFO): Reject a block with two coinbase transactions
> 2022-06-16T00:34:02.478000Z TestFramework (INFO): Reject a block with duplicate transactions
> 2022-06-16T00:34:02.800000Z TestFramework (INFO): Reject a block with timestamp before MedianTimePast
> 2022-06-16T00:34:03.020000Z TestFramework (INFO): Accept a previously rejected future block at a later time
> 2022-06-16T00:34:03.150000Z TestFramework (INFO): Reject a block with a duplicate transaction in the Merkle Tree (but with a valid Merkle Root)
> 2022-06-16T00:34:03.371000Z TestFramework (INFO): Reject a block with two duplicate transactions in the Merkle Tree (but with a valid Merkle Root)
> 2022-06-16T00:34:03.797000Z TestFramework (INFO): Reject a block with a transaction with prevout.n out of range
> 2022-06-16T00:34:04.011000Z TestFramework (INFO): Reject a block with a transaction with outputs > inputs
> 2022-06-16T00:34:04.325000Z TestFramework (INFO): Reject a block with a transaction with a duplicate hash of a previous transaction (BIP30)
> 2022-06-16T00:34:04.656000Z TestFramework (INFO): Reject a block with a transaction with a nonfinal locktime
> 2022-06-16T00:34:04.865000Z TestFramework (INFO): Reject a block with a coinbase transaction with a nonfinal locktime
> 2022-06-16T00:34:05.073000Z TestFramework (INFO): Accept a valid block even if a bloated version of the block has previously been sent
> 2022-06-16T00:34:05.450000Z TestFramework (INFO): Accept a block with a transaction spending an output created in the same block
> 2022-06-16T00:34:05.558000Z TestFramework (INFO): Reject a block with a transaction spending an output created later in the same block
> 2022-06-16T00:34:05.773000Z TestFramework (INFO): Reject a block with a transaction double spending a transaction created in the same block
> 2022-06-16T00:34:05.991000Z TestFramework (INFO): Reject a block trying to claim too much subsidy in the coinbase transaction
> 2022-06-16T00:34:06.204000Z TestFramework (INFO): Accept a block claiming the correct subsidy in the coinbase transaction
> 2022-06-16T00:34:06.310000Z TestFramework (INFO): Reject a block containing a transaction spending from a non-existent input
> 2022-06-16T00:34:06.523000Z TestFramework (INFO): Reject a block containing a duplicate transaction but with the same Merkle root (Merkle tree malleability
> 2022-06-16T00:34:06.857000Z TestFramework (INFO): Reject a block containing too many sigops after a large script element
> 2022-06-16T00:34:07.248000Z TestFramework (INFO): Check sigops are counted correctly after an invalid script element
> 2022-06-16T00:34:07.732000Z TestFramework (INFO): Test transaction resurrection during a re-org
> 2022-06-16T00:34:08.332000Z TestFramework (INFO): Accept a block with invalid opcodes in dead execution paths
> 2022-06-16T00:34:08.450000Z TestFramework (INFO): Test re-orging blocks with OP_RETURN in them
> 2022-06-16T00:34:09.177000Z TestFramework (INFO): Test a re-org of one week's worth of blocks (1088 blocks)
> 
> 
> stderr:

> 21/245 - feature_pruning.py failed, Duration: 582 s

    

> stdout:
> 2022-06-16T00:28:16.191000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20220615_202813/feature_pruning_244
> 2022-06-16T00:28:29.460000Z TestFramework (INFO): Warning! This test requires 4GB of disk space
> 2022-06-16T00:28:29.502000Z TestFramework (INFO): Mining a big blockchain of 995 blocks
> 2022-06-16T00:33:30.483000Z TestFramework (INFO): Check that we haven't started pruning yet because we're below PruneAfterHeight
> 2022-06-16T00:33:30.605000Z TestFramework (INFO): Success
> 2022-06-16T00:33:30.617000Z TestFramework (INFO): Though we're already using more than 550MiB, current usage: 592.1861438751221
> 2022-06-16T00:33:30.617000Z TestFramework (INFO): Mining 25 more blocks should cause the first block file to be pruned
> 2022-06-16T00:33:39.588000Z TestFramework (INFO): Success
> 2022-06-16T00:33:39.589000Z TestFramework (INFO): Usage should be below target: 480.31389808654785
> 2022-06-16T00:33:39.592000Z TestFramework (INFO): Check that we'll exceed disk space target if we have a very high stale block rate
> 2022-06-16T00:33:39.597000Z TestFramework (INFO): Mine 24 (stale) blocks on Node 1, followed by 25 (main chain) block reorg from Node 0, for 12 rounds
> 2022-06-16T00:35:52.780000Z TestFramework (INFO): Usage can be over target because of high stale rate: 512.3138980865479
> 2022-06-16T00:35:52.845000Z TestFramework (INFO): Check that we can survive a 288 block reorg still
> 2022-06-16T00:35:52.849000Z TestFramework (INFO): Current block height: 1320
> 2022-06-16T00:35:52.850000Z TestFramework (INFO): Invalidating block 44af5766f16112c8b04c19385700828e5ac236f42808804330eaf46e1312f4fb at height 1033
> 2022-06-16T00:35:57.785000Z TestFramework (INFO): New best height: 1032
> 2022-06-16T00:35:57.901000Z TestFramework (INFO): Generating new longer chain of 300 more blocks
> 2022-06-16T00:35:59.900000Z TestFramework (INFO): Reconnect nodes
> 2022-06-16T00:37:25.231000Z TestFramework (ERROR): JSONRPC error
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 166, in _get_response
>     http_response = self.__conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 307, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 133, in main
>     self.run_test()
>   File "/home/user/bitcoin/test/functional/feature_pruning.py", line 418, in run_test
>     self.reorg_test()  # (1033, )
>   File "/home/user/bitcoin/test/functional/feature_pruning.py", line 217, in reorg_test
>     self.sync_blocks(self.nodes[0:3], timeout=120)
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 676, in sync_blocks
>     best_hash = [x.getbestblockhash() for x in rpc_connections]
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 676, in <listcomp>
>     best_hash = [x.getbestblockhash() for x in rpc_connections]
>   File "/home/user/bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 142, in __call__
>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 108, in _request
>     return self._get_response()
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 168, in _get_response
>     raise JSONRPCException({
> test_framework.authproxy.JSONRPCException: 'getbestblockhash' RPC took longer than 60.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
> 2022-06-16T00:37:50.789000Z TestFramework (INFO): Stopping nodes
> 2022-06-16T00:37:50.808000Z TestFramework.node0 (ERROR): Unable to stop node.
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 336, in stop_node
>     self.stop(wait=wait)
>   File "/home/user/bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 142, in __call__
>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 107, in _request
>     self.__conn.request(method, path, postdata, headers)
>   File "/usr/lib/python3.9/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1266, in _send_request
>     self.putrequest(method, url, **skips)
>   File "/usr/lib/python3.9/http/client.py", line 1092, in putrequest
>     raise CannotSendRequest(self.__state)
> http.client.CannotSendRequest: Request-sent
> [node 5] Cleaning up leftover process
> [node 2] Cleaning up leftover process
> [node 1] Cleaning up leftover process
> [node 0] Cleaning up leftover process
> 
> 
> stderr:
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/feature_pruning.py", line 486, in <module>
>     PruneTest().main()
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 156, in main
>     exit_code = self.shutdown()
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 311, in shutdown
>     self.stop_nodes()
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 571, in stop_nodes
>     node.wait_until_stopped()
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 382, in wait_until_stopped
>     wait_until_helper(self.is_node_stopped, timeout=timeout, timeout_factor=self.timeout_factor)
>   File "/home/user/bitcoin/test/functional/test_framework/util.py", line 265, in wait_until_helper
>     if predicate():
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 372, in is_node_stopped
>     assert return_code == 0, self._node_msg(
> AssertionError: [node 0] Node returned non-zero exit code (-9) when stopping

> 245/245 - feature_dbcrash.py failed, Duration: 2812 s

                  

> stdout:
> 2022-06-16T00:28:16.295000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20220615_202813/feature_dbcrash_243
> 2022-06-16T00:28:46.954000Z TestFramework (INFO): Prepped 5000 utxo entries
> 2022-06-16T00:28:50.396000Z TestFramework (INFO): Iteration 0, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:31:57.072000Z TestFramework (INFO): Iteration 1, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:34:58.594000Z TestFramework (INFO): Iteration 2, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:38:52.851000Z TestFramework (INFO): Iteration 3, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:40:32.251000Z TestFramework (INFO): Iteration 4, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:42:39.525000Z TestFramework (INFO): Iteration 5, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:47:05.828000Z TestFramework (INFO): Iteration 6, generating 2500 transactions [0, 0, 0]
> 2022-06-16T00:48:43.793000Z TestFramework (INFO): Iteration 7, generating 2500 transactions [1, 1, 0]
> 2022-06-16T00:50:17.816000Z TestFramework (INFO): Iteration 8, generating 2500 transactions [2, 1, 0]
> 2022-06-16T00:51:41.498000Z TestFramework (INFO): Iteration 9, generating 2500 transactions [3, 1, 0]
> 2022-06-16T00:52:50.168000Z TestFramework (INFO): Iteration 10, generating 2500 transactions [4, 1, 0]
> 2022-06-16T00:53:23.849000Z TestFramework (INFO): Iteration 11, generating 2500 transactions [4, 1, 0]
> 2022-06-16T00:54:00.627000Z TestFramework (INFO): Iteration 12, generating 2500 transactions [4, 1, 0]
> 2022-06-16T00:54:38.547000Z TestFramework (INFO): Iteration 13, generating 2500 transactions [4, 1, 0]
> 2022-06-16T00:55:19.742000Z TestFramework (INFO): Iteration 14, generating 2500 transactions [5, 2, 0]
> 2022-06-16T00:55:58.554000Z TestFramework (INFO): Iteration 15, generating 2500 transactions [5, 2, 0]
> 2022-06-16T00:56:40.740000Z TestFramework (INFO): Iteration 16, generating 2500 transactions [5, 3, 0]
> 2022-06-16T00:57:20.679000Z TestFramework (INFO): Iteration 17, generating 2500 transactions [6, 3, 0]
> 2022-06-16T00:57:59.576000Z TestFramework (INFO): Iteration 18, generating 2500 transactions [6, 3, 0]
> 2022-06-16T00:58:38.372000Z TestFramework (INFO): Iteration 19, generating 2500 transactions [6, 3, 0]
> 2022-06-16T00:59:17.384000Z TestFramework (INFO): Iteration 20, generating 2500 transactions [6, 3, 0]
> 2022-06-16T00:59:56.572000Z TestFramework (INFO): Iteration 21, generating 2500 transactions [6, 3, 0]
> 2022-06-16T01:00:38.183000Z TestFramework (INFO): Iteration 22, generating 2500 transactions [6, 4, 0]
> 2022-06-16T01:01:19.304000Z TestFramework (INFO): Iteration 23, generating 2500 transactions [7, 4, 0]
> 2022-06-16T01:02:01.291000Z TestFramework (INFO): Iteration 24, generating 2500 transactions [7, 5, 0]
> 2022-06-16T01:02:44.272000Z TestFramework (INFO): Iteration 25, generating 2500 transactions [7, 5, 0]
> 2022-06-16T01:03:30.375000Z TestFramework (INFO): Iteration 26, generating 2500 transactions [8, 6, 0]
> 2022-06-16T01:04:14.778000Z TestFramework (INFO): Iteration 27, generating 2500 transactions [8, 6, 0]
> 2022-06-16T01:05:05.355000Z TestFramework (INFO): Iteration 28, generating 2500 transactions [9, 7, 0]
> 2022-06-16T01:05:49.274000Z TestFramework (INFO): Iteration 29, generating 2500 transactions [9, 7, 0]
> 2022-06-16T01:06:36.106000Z TestFramework (INFO): Iteration 30, generating 2500 transactions [9, 7, 0]
> 2022-06-16T01:07:23.495000Z TestFramework (INFO): Iteration 31, generating 2500 transactions [10, 7, 0]
> 2022-06-16T01:08:13.103000Z TestFramework (INFO): Iteration 32, generating 2500 transactions [10, 8, 0]
> 2022-06-16T01:09:02.471000Z TestFramework (INFO): Iteration 33, generating 2500 transactions [10, 8, 0]
> 2022-06-16T01:09:54.083000Z TestFramework (INFO): Iteration 34, generating 2500 transactions [11, 8, 0]
> 2022-06-16T01:10:46.416000Z TestFramework (INFO): Iteration 35, generating 2500 transactions [12, 8, 0]
> 2022-06-16T01:11:35.339000Z TestFramework (INFO): Iteration 36, generating 2500 transactions [12, 8, 0]
> 2022-06-16T01:12:24.634000Z TestFramework (INFO): Iteration 37, generating 2500 transactions [12, 8, 0]
> 2022-06-16T01:13:19.854000Z TestFramework (INFO): Iteration 38, generating 2500 transactions [12, 8, 0]
> 2022-06-16T01:14:13.032000Z TestFramework (INFO): Iteration 39, generating 2500 transactions [12, 8, 0]
> 2022-06-16T01:15:00.597000Z TestFramework (ERROR): Unexpected exception caught during testing
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 108, in _request
>     return self._get_response()
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 166, in _get_response
>     http_response = self.__conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 307, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 133, in main
>     self.run_test()
>   File "/home/user/bitcoin/test/functional/feature_dbcrash.py", line 263, in run_test
>     self.wallet.rescan_utxos()
>   File "/home/user/bitcoin/test/functional/test_framework/wallet.py", line 106, in rescan_utxos
>     res = self._test_node.scantxoutset(action="start", scanobjects=[self.get_descriptor()])
>   File "/home/user/bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 142, in __call__
>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 113, in _request
>     self.__conn.request(method, path, postdata, headers)
>   File "/usr/lib/python3.9/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.9/http/client.py", line 950, in send
>     self.connect()
>   File "/usr/lib/python3.9/http/client.py", line 921, in connect
>     self.sock = self._create_connection(
>   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
>     raise err
>   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 2022-06-16T01:15:05.618000Z TestFramework (INFO): Stopping nodes
> 2022-06-16T01:15:05.743000Z TestFramework.node3 (ERROR): Unable to stop node.
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 336, in stop_node
>     self.stop(wait=wait)
>   File "/home/user/bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 142, in __call__
>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
>   File "/home/user/bitcoin/test/functional/test_framework/authproxy.py", line 107, in _request
>     self.__conn.request(method, path, postdata, headers)
>   File "/usr/lib/python3.9/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1266, in _send_request
>     self.putrequest(method, url, **skips)
>   File "/usr/lib/python3.9/http/client.py", line 1092, in putrequest
>     raise CannotSendRequest(self.__state)
> http.client.CannotSendRequest: Request-sent
> [node 3] Cleaning up leftover process
> 
> 
> stderr:
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/feature_dbcrash.py", line 288, in <module>
>     ChainstateWriteCrashTest().main()
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 156, in main
>     exit_code = self.shutdown()
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 311, in shutdown
>     self.stop_nodes()
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 571, in stop_nodes
>     node.wait_until_stopped()
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 382, in wait_until_stopped
>     wait_until_helper(self.is_node_stopped, timeout=timeout, timeout_factor=self.timeout_factor)
>   File "/home/user/bitcoin/test/functional/test_framework/util.py", line 265, in wait_until_helper
>     if predicate():
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 372, in is_node_stopped
>     assert return_code == 0, self._node_msg(
> AssertionError: [node 3] Node returned non-zero exit code (-9) when stopping

Try failed tests individually:

user@localhost:~/bitcoin/test/functional$ `python3 feature_block.py`

> ...
> ...
> 2022-06-16T01:48:03.457000Z TestFramework (INFO): Test re-orging blocks with OP_RETURN in them
> 2022-06-16T01:48:04.208000Z TestFramework (INFO): Test a re-org of one week's worth of blocks (1088 blocks)
> Killed

I didn't terminate, not sure why this was killed.

user@localhost:~/bitcoin/test/functional$ `python3 feature_dbcrash.py`

> ...
> ...
> 2022-06-16T02:22:04.399000Z TestFramework (INFO): Iteration 39, generating 2500 transactions [14, 6, 5]
> 2022-06-16T02:22:45.148000Z TestFramework (INFO): Verifying utxo hash matches for all nodes
> 2022-06-16T02:22:45.611000Z TestFramework (INFO): Restarted nodes: [14, 6, 5]; crashes on restart: 19
> 2022-06-16T02:22:45.735000Z TestFramework (INFO): Stopping nodes
> 2022-06-16T02:22:46.082000Z TestFramework (INFO): Cleaning up /tmp/bitcoin_func_test_dlvz7p5v on exit
> 2022-06-16T02:22:46.084000Z TestFramework (INFO): Tests successful

This succeeds when tested individually

user@localhost:~/bitcoin/test/functional$ `python3 feature_pruning.py`

> ...
> ...
> 2022-06-16T02:30:49.127000Z TestFramework (INFO): Done
> 2022-06-16T02:30:49.208000Z TestFramework (INFO): Stopping nodes
> 2022-06-16T02:30:49.584000Z TestFramework (INFO): Cleaning up /tmp/bitcoin_func_test_l2tv3kpn on exit
> 2022-06-16T02:30:49.584000Z TestFramework (INFO): Tests successful

This also succeeds

user@localhost:~/bitcoin/test/util$ `python3 test_runner.py`

Successful

`bitcoin-qt` opens as expected

Machine details:

Qubes 4.1
Up to date Debian 11 Standard VM
Coreboot 4.14
x86

**Comment by MarcoFalke** [comment]
Looks like OOM in the linker. What is the available memory? `free -h`

**Comment by Rspigler** [comment]
Ah my apologies. I thought it was a memory issue - I had paused my other qubes and allocated more memory towards it. I guess I just needed to restart and shut some other qubes down.  Sorry
