### ISSUE TITLE
Depends build does not use ccache on macOS 12.4

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#25387]
I have ccache version 4.6.1 via homebrew. On master @ d6832217ef45ea0c858e3fcdec5d4fe87097c839:

```sh
ccache -C
ccache --zero-stats
cd depends
make NO_QT=1 NO_ZMQ=1 NO_BDB=1 NO_UPMP=1 NO_NATPMP=1
ccache --show-stats
```

This builds a bunch of stuff, but nothing ends up in the ccache:

```
Summary:
  Hits:               0 /     0
    Direct:           0 /     0
    Preprocessed:     0 /     0
  Misses:             0
    Direct:           0
    Preprocessed:     0
Primary storage:
  Hits:               0 /     0
  Misses:             0
  Cache size (GB): 0.00 / 10.00 (0.00 %)
```

Possibly related to #21552, but no cross-compilation is involved here.

This may have the case forever; I only noticed today while experimenting with `distcc`. This uses `$CCACHE_PREFIX=distcc` (which I disabled above) in order to first check the cache and only then distribute a compilation job. I noticed no jobs got distributed when building depends, which is annoying, because that's by far the slowest compilation task (part of why I rarely use it).

**Comment by Sjors** [comment]
@fanquake TIL. We should probably mention that in the [productivity notes](https://github.com/bitcoin/bitcoin/blob/master/doc/productivity.md#cache-compilations-with-ccache). Any particular reason for that? Was it causing problems?

**Comment by laanwj** [comment]
> Any particular reason for that? Was it causing problems?

I guess we assume that a depends build is a rare enough thing that using ccache doesn't really matter, it's not worth the extra complexity of detecting it and passing to to all sub-build systems.

**Comment by Sjors** [comment]
It happens a bit more often when switching branches for review, but for other use cases it won't. Just having the right instructions in the productivity notes is probably enough. Not sure if my guess above is enough.

**Comment by fanquake** [comment]
Closing for now, as this isn't a bug or an issue. Feel free to open a PR to add some documentation if you want.
