### ISSUE TITLE
LoadWalletInternal logic check

### ISSUE THREAD

**Issue by guoyl** [bitcoin/bitcoin#25418]
In the RPC method:
https://github.com/bitcoin/bitcoin/blob/master/src/wallet/rpc/wallet.cpp
When the RPC method "loadwallet" is called, it will call loadwallet(https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp)
and LoadWalletInternal.  When the user repeatedly call the loadwallet with same wallet name. In the LoadWalletInternal funcntion, although it does not call  Addwallet repeatedly to add to context.wallets and avoid open SQLite database repeatedly. But it will make new SQLiteDatabase unique_ptr and do some series checks.  
Is it better to use GetWallet to determine if the wallet is already loaded before calling LoadWalletInternal?

**Comment by furszy** [comment]
The "name" parameter in `loadwallet` isn't just a simple name. Could be a:
1. Path where a directory can be created.
2. Path to an existing directory.
3. Path to a symlink to a directory.
4. The name of a data file in `-walletdir`.

So, depends on how the wallet was initially loaded (from which of those options), the stored "wallet name" inside the wallet class will be different. So, only a `GetWallet(name)` check before loading the db wouldn't work if you load the same wallet in two different ways. Eg: load a wallet by name first (location inside `-walletdir`), then load it by its path.

**Comment by adamjonas** [comment]
Closing based on furszy response.
