### ISSUE TITLE
importdescriptors does not scan the mempool

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#25453]
Just noticed this while debugging a watch-only wallet.

Step 1: create watch-only wallet
Step 2: import some descriptor
Step 3: notice that if a transaction is currently in the mempool, it won't show up in the wallet
Step 4: restart Bitcoin Core, it'll show up

cc @achow101

**Comment by achow101** [comment]
#25351

**Comment by Sjors** [comment]
It's a duplicate of #18954, #25351 is a potential fix.
