### ISSUE TITLE
build: autoconf 2.71 warns that `%.raw.h` was already defined

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#25501]
The master branch (cc22bd7f708fc3f5e793bf0138cd340f71c0feb9) on Ubuntu 22.04:
```
$ ./autogen.sh 
...
src/Makefile.bench.include:97: warning: %.raw.h was already defined in condition TRUE, which includes condition ENABLE_BENCH ...
src/Makefile.am:1065:   'src/Makefile.bench.include' included from here
src/Makefile.test.include:420: ... '%.raw.h' previously defined here
src/Makefile.am:1062:   'src/Makefile.test.include' included from here
...
```

**Comment by MarcoFalke** [comment]
likely b1a824dd06aa58618947783edee2dd891b5204dc :sweat_smile:

**Comment by laanwj** [comment]
I've also noticed this, but thought it was some local issue.

**Comment by MarcoFalke** [comment]
Maybe this can be fixed by moving the raw generation to  libtest util (or the check that builds libtest_util if it is needed) to avoid a duplicate build?

**Comment by Veterangrail** [comment]
> The master branch ([cc22bd7](https://github.com/bitcoin/bitcoin/commit/cc22bd7f708fc3f5e793bf0138cd340f71c0feb9)) on Ubuntu 22.04:
> 
> ```
> $ ./autogen.sh 
> ...
> src/Makefile.bench.include:97: warning: %.raw.h was already defined in condition TRUE, which includes condition ENABLE_BENCH ...
> src/Makefile.am:1065:   'src/Makefile.bench.include' included from here
> src/Makefile.test.include:420: ... '%.raw.h' previously defined here
> src/Makefile.am:1062:   'src/Makefile.test.include' included from here
> ...
> ```


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked
