### ISSUE TITLE
Progress for opening wallet

### ISSUE THREAD

**Issue by pbies** [bitcoin/bitcoin#25531]
While there is progress for importing private keys and rescanning, there is good reason to also add progress for wallet opening.
Now you need to look into debug.log and trace it for progress, so adding a progress bar for opening wallet (it is rescan in the end) would be a very nice feature.

**Comment by Veterangrail** [comment]
> While there is progress for importing private keys and rescanning, there is good reason to also add progress for wallet opening. Now you need to look into debug.log and trace it for progress, so adding a progress bar for opening wallet (it is rescan in the end) would be a very nice feature.

             https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Veterangrail** [comment]
> While there is progress for importing private keys and rescanning, there is good reason to also add progress for wallet opening. Now you need to look into debug.log and trace it for progress, so adding a progress bar for opening wallet (it is rescan in the end) would be a very nice feature.

 https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Veterangrail** [comment]
> While there is progress for importing private keys and rescanning, there is good reason to also add progress for wallet opening. Now you need to look into debug.log and trace it for progress, so adding a progress bar for opening wallet (it is rescan in the end) would be a very nice feature.

 https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by fanquake** [comment]
@pbies is this related to the GUI? If so, we should move the issue to https://github.com/bitcoin-core/gui.

**Comment by pbies** [comment]
It is between backend and GUI, as backend need to inform GUI about the progress. I am not sure how it is made inside, but it might not be only GUI.

**Comment by fanquake** [comment]
I meant is the issue related to showing a progress bar in the GUI, which it seems like it is, so we can move the issue to https://github.com/bitcoin-core/gui.

**Comment by pbies** [comment]
I understand your question but I don't have specific answer. Backend could not have implemented giving progress of opening wallet to GUI, so it would be both. In result I think you can move the issue to GUI, but some changes in backend would have also be made to solve the ticket.

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/651.
