### ISSUE TITLE
Build failing on Ubuntu 22.04

### ISSUE THREAD

**Issue by IMPranshu** [bitcoin/bitcoin#25534]
**Expected behavior**
To run bitcoin-core in Ubuntu 22.04 after following all the steps in [build-unix.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#linux-distribution-specific-instructions)

**Actual behavior**

Even after carefully following all the steps the build is failing in Ubuntu 22.04 version but by following the same steps again in Ubuntu 20.04 and 18.04 I am able to successfully run bitcoin-core.

**To reproduce**

To verify this first follow all the instructions in the [build-unix.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#linux-distribution-specific-instructions) in Ubuntu 22.04 and then try to run the following command:

```
python3 test/functional/feature_taproot.py
```

You will be met with the following error of some sort:
```
 2022-06-11T19:04:12.075000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_2wz38651
2022-06-11T19:04:16.476000Z TestFramework (INFO): Post-activation tests...
2022-06-11T19:04:16.832000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported
```

This error is not in particular for running tests but shows a problem with the installation of bitcoin-core in general.

I searched for the issues and came across a few articles and conversations regarding this particular issue in Ubuntu 22.04. Will be providing links to them.

**Comment by MarcoFalke** [comment]
Which commit are you compiling?

**Comment by IMPranshu** [comment]
```
git checkout v0.21.2rc2
```

**Comment by MarcoFalke** [comment]
This will need d2e0c27e45abd802849e3bf6006f495fc6055adb backported

**Comment by MarcoFalke** [comment]
There is no 0.21 milestone, so I think this can be closed? cc @fanquake 

Maybe we could still push a backport to the branch nonetheless?

@IMPranshu According to https://bitcoincore.org/en/lifecycle/ 0.21 will be EOL by end of this year, so if possible, use a more recent version.
