### ISSUE TITLE
lmdb or mdbx for db/wallet storage

### ISSUE THREAD

**Issue by dimapv** [bitcoin/bitcoin#25593]
There exist better choice than SQLite for wallet, example is LMDB or libmdbx.

**Comment by fanquake** [comment]
We have no plans to migrate from SQLite. In fact the migration from bdb is not even complete.

**Comment by achow101** [comment]
lmdb was considered as an option when we were looking at alternative databases to BDB, however it was ruled out due to it's non-portable nature. SQLite was chosen as it was better suited for our targeted use case.
