### ISSUE TITLE
Possible savings in `dumptxoutset` serialization format (~20%)

### ISSUE THREAD

**Issue by RCasatta** [bitcoin/bitcoin#25675]
**Is your feature request related to a problem? Please describe.**

Size of the serialized UTXO set

**Describe the solution you'd like**

The serialization format of the serialized UTXO set from `dumptxoutset` is a list of `(COutPoint, Coin)`.

However, many out points refer to the same transaction so we can group by `Txid` with:
`list(Txid, list((vout,Coin))`

Since the cursor is already iterating through sorted `Txid` this doesn't add complexity to the serialization code.

Considering the UTXO at height 745995:
```
serialized_size: ~5.3Gb
total_elements: 83_082_178
uniques_txids: 49_517_483
bytes_lost: total_elements // due to the additional byte for the length of the inner list
bytes_savings: (total_elements-unique_txids)*32 - bytes_lost ~= 1Gb
```

**Describe alternatives you've considered**

Additional bytes could be saved by leveraging the duplications in scripts (address reuse). However, this is not considered worthy because the format would lose the streaming property and also because we don't want to optimize on something which is not recommended.

The byte lost for expressing the length of the inner list could be optimized with a special byte containing both the length of the list and the first vout, since usually both vout and this value are very small they should fit on a single byte most of the time having a fallback for edge cases.

**Additional context**

Tagging @jamesob author of https://github.com/bitcoin/bitcoin/pull/16899
assumeutxo summary https://github.com/bitcoin/bitcoin/pull/15606

**Comment by Ghost345x** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Size of the serialized UTXO set
> 
> **Describe the solution you'd like**
> 
> The serialization format of the serialized UTXO set from `dumptxoutset` is a list of `(COutPoint, Coin)`.
> 
> However, many out points refer to the same transaction so we can group by `Txid` with:
> `list(Txid, list((vout,Coin))`
> 
> Since the cursor is already iterating through sorted `Txid` this doesn't add complexity to the serialization code.
> 
> Considering the UTXO at height 745995:
> ```
> serialized_size: ~5.3Gb
> total_elements: 83_082_178
> uniques_txids: 49_517_483
> bytes_lost: total_elements // due to the additional byte for the length of the inner list
> bytes_savings: (total_elements-unique_txids)*32 - bytes_lost ~= 1Gb
> ```
> 
> **Describe alternatives you've considered**
> 
> Additional bytes could be saved by leveraging the duplications in scripts (address reuse). However, this is not considered worthy because the format would lose the streaming property and also because we don't want to optimize on something which is not recommended.
> 
> The byte lost for expressing the length of the inner list could be optimized with a special byte containing both the length of the list and the first vout, since usually both vout and this value are very small they should fit on a single byte most of the time having a fallback for edge cases.
> 
> **Additional context**
> 
> Tagging @jamesob author of https://github.com/bitcoin/bitcoin/pull/16899
> assumeutxo summary https://github.com/bitcoin/bitcoin/pull/15606
> 

**Talk to btc dev team via Live chat  https://direct.lc.chat/14345826/**

**Comment by luke-jr** [comment]
Outputs are also created sequentially, so it seems likely `list(Txid, list(Coin,...)` might improve things too?

**Comment by RCasatta** [comment]
Shouldn't be `list(Txid, list(Option<Coin>,...)` to recompute the vout?
In this case I don't think so because it needs a byte for every `None`?
