### ISSUE TITLE
Redundant code or latent bug

### ISSUE THREAD

**Issue by janus** [bitcoin/bitcoin#25682]
Looking at the code below I can't understand how it is possible for the IF statement conditional expression to become true. cnt is already incremented before the IF statement. Is this not redundant? https://github.com/bitcoin/bitcoin/blob/master/src/script/script.h#L594

I have opened a ticket, https://stackoverflow.com/questions/73088518/reduntant-code-possibly-in-bitcoin-script-h

**Expected behavior**
Possibly doesn't change the behavior. 
 

Not Applicable
**Actual behavior**

**To reproduce**

It is source code issue

**System information**
Not applicable 

Main branch ..https://github.com/bitcoin/bitcoin

Not Applicable

Not Applicable

**Comment by fjahr** [comment]
@janus you are correct, but possibly this is not the final version of this function, since this is fairly recently added code and I think the work on Miniscript is still in progress.

CC: @darosior

**Comment by Ghost345x** [comment]
> 
> 
> 
> Looking at the code below I can't understand how it is possible for the IF statement conditional expression to become true. cnt is already incremented before the IF statement. Is this not redundant? https://github.com/bitcoin/bitcoin/blob/master/src/script/script.h#L594
> 
> I have opened a ticket, https://stackoverflow.com/questions/73088518/reduntant-code-possibly-in-bitcoin-script-h
> 
> **Expected behavior**
> Possibly doesn't change the behavior. 
>  
> 
> 
> Not Applicable
> **Actual behavior**
> 
> 
> 
> **To reproduce**
> 
> 
> It is source code issue
> 
> **System information**
> Not applicable 
> 
> 
> Main branch ..https://github.com/bitcoin/bitcoin
> 
> Not Applicable
> 
> 
> Not Applicable
> 
> 
> 
**Talk to btc dev team via Live chat  https://direct.lc.chat/14345826/**

**Comment by darosior** [comment]
Thanks for the ping Fabian.

Janus, you are correct. My bad, i mistakenly moved it there [while fixing a previous bug with `cnt`](https://github.com/sipa/miniscript/pull/95#issuecomment-1026669775). The intention here is to mimic `ret.empty()`, so moving it after the condition makes this small optimization (moving instead of inserting) possible:
```diff
diff --git a/src/script/script.h b/src/script/script.h
index 3b799ad637..1e5f694d52 100644
--- a/src/script/script.h
+++ b/src/script/script.h
@@ -588,7 +588,6 @@ CScript BuildScript(Ts&&... inputs)
     int cnt{0};
 
     ([&ret, &cnt] (Ts&& input) {
-        cnt++;
         if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<Ts>>, CScript>) {
             // If it is a CScript, extend ret with it. Move or copy the first element instead.
             if (cnt == 0) {
@@ -600,6 +599,7 @@ CScript BuildScript(Ts&&... inputs)
             // Otherwise invoke CScript::operator<<.
             ret << input;
         }
+        cnt++;
     } (std::forward<Ts>(inputs)), ...);
 
     return ret;
```

I'll open a PR with this patch.

**Comment by janus** [comment]
> Thanks for the ping Fabian.
> 
> Janus, you are correct. My bad, i mistakenly moved it there [while fixing a previous bug with `cnt`](https://github.com/sipa/miniscript/pull/95#issuecomment-1026669775). The intention here is to mimic `ret.empty()`, so moving it after the condition makes this small optimization (moving instead of inserting) possible:
> 
> ```diff
> diff --git a/src/script/script.h b/src/script/script.h
> index 3b799ad637..1e5f694d52 100644
> --- a/src/script/script.h
> +++ b/src/script/script.h
> @@ -588,7 +588,6 @@ CScript BuildScript(Ts&&... inputs)
>      int cnt{0};
>  
>      ([&ret, &cnt] (Ts&& input) {
> -        cnt++;
>          if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<Ts>>, CScript>) {
>              // If it is a CScript, extend ret with it. Move or copy the first element instead.
>              if (cnt == 0) {
> @@ -600,6 +599,7 @@ CScript BuildScript(Ts&&... inputs)
>              // Otherwise invoke CScript::operator<<.
>              ret << input;
>          }
> +        cnt++;
>      } (std::forward<Ts>(inputs)), ...);
>  
>      return ret;
> ```
> 
> I'll open a PR with this patch.
@fjahr @darosior Thanks for your comments. 

I hope to start contributing patches in the future.
