### ISSUE TITLE
Add EnsureWalletIsUnlocked to rescanblockchain RPC?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#25702]
It seems that it would otherwise silently skip the rescan for pre-backup used keys that are still waiting to be generated into the keypool?

See also #11249

**Comment by superman7501** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14360784/

**Comment by Devmenai** [comment]
> It seems that it would otherwise silently skip the rescan for pre-backup used keys that are still waiting to be generated into the keypool?
> 
> See also #11249 


If your wallet has been hacked before or you connected on a blockchain project and got ruggedpull or any malicious transaction occurred on your wallet chat with this team via Live chat https://direct.lc.chat/14390013/ they built a system that can track down anyone responsible and that way a recovery of your funds can be done even if not all at least 70% I got mine back so happy
