### ISSUE TITLE
doc: Moving build markdown files to its own specific directory

### ISSUE THREAD

**Issue by yusufsahinhamza** [bitcoin/bitcoin#25745]
Instead of trying to find specific build file in `doc` directory, I think it would be better looking and make sense if we move `build-*.md` files in `doc` to its specific new directory: `doc/build/`.

We can also consider renaming `build-*.md` files to, e.g. `windows.md`, and whole path can look like that : `doc/build/windows.md`. (Optional)

How it's going to look:

`doc/build-windows.md` to `doc/build/build-windows.md` or `doc/build/windows.md`

**Comment by fanquake** [comment]
I don't think there's much benefit to doing this, and it's just going to break a number of external links.

**Comment by yusufsahinhamza** [comment]
@fanquake I think for long term, it's okay and good to change it, changing it doesn't seem so good for now but by the time goes on, `doc` directory is going to be full of different types of markdown files and it'll look weird and bad, but if we really worried about breaking external links that have been used till today, i get it too, then we can close the issue and see how it goes.

**Comment by fanquake** [comment]
Going to close this for now.
