### ISSUE TITLE
install Server Ubuntu 20.04

### ISSUE THREAD

**Issue by david739** [bitcoin/bitcoin#25746]
hi can someone please give me a working installation procedure. I tried this post failed

sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
sudo apt install libevent-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev
sudo apt install libsqlite3-dev

./autogen.sh
./configure
make
sudo make install

./autogen.sh
n TRUE, which includes condition ENABLE_BENCH ...
src/Makefile.am:1076:   'src/Makefile.bench.include' included from here
src/Makefile.test.include:418: ... '%.raw.h' previously defined here
src/Makefile.am:1073:   'src/Makefile.test.include' included from here
src/Makefile.am: installing 'build-aux/depcomp'

**Comment by fanquake** [comment]
You need to run ./configure after autogen.sh. There are build instructions in the docs folder in this repository.

**Comment by david739** [comment]
the problem is still the same

**Comment by fanquake** [comment]
You'll need to provide some information that actually indicates what is happening/the error (ie config.log, make output). Otherwise there is nothing for us to debug here.

**Comment by david739** [comment]
ok, I'm still reinstalling it, it's taking a long time, I'll let you know as soon as I have more data

**Comment by MarcoFalke** [comment]
See #25501

**Comment by david739** [comment]
make

  CXXLD    libbitcoinconsensus.la
make[2]: Leaving directory '/home/pool/bitcoin/src'
make[1]: Leaving directory '/home/pool/bitcoin/src'
Making all in doc/man
make[1]: Entering directory '/home/pool/bitcoin/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pool/bitcoin/doc/man'
make[1]: Entering directory '/home/pool/bitcoin'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/pool/bitcoin'

**Comment by fanquake** [comment]
Nothing you have posted indicates any errors.

**Comment by MarcoFalke** [comment]
Closing for now. Let us know if there are any errors and the steps to reproduce.

**Comment by david739** [comment]
sudo make install


 /usr/bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool --preserve-dup-deps  --mode=install /usr/bin/install -c bitcoind bitcoin-cli bitcoin-tx bitcoin-wallet bitcoin-util test/test_bitcoin bench/bench_bitcoin '/usr/local/bin'
libtool: install: /usr/bin/install -c bitcoind /usr/local/bin/bitcoind
libtool: install: /usr/bin/install -c bitcoin-cli /usr/local/bin/bitcoin-cli
libtool: install: /usr/bin/install -c bitcoin-tx /usr/local/bin/bitcoin-tx
libtool: install: /usr/bin/install -c bitcoin-wallet /usr/local/bin/bitcoin-wallet
libtool: install: /usr/bin/install -c bitcoin-util /usr/local/bin/bitcoin-util
libtool: install: /usr/bin/install -c test/test_bitcoin /usr/local/bin/test_bitcoin
libtool: install: /usr/bin/install -c bench/bench_bitcoin /usr/local/bin/bench_bitcoin
 /usr/bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 script/bitcoinconsensus.h '/usr/local/include'
make[3]: Leaving directory '/home/pool/bitcoin/src'
make[2]: Leaving directory '/home/pool/bitcoin/src'
make[1]: Leaving directory '/home/pool/bitcoin/src'
Making install in doc/man
make[1]: Entering directory '/home/pool/bitcoin/doc/man'
make[2]: Entering directory '/home/pool/bitcoin/doc/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 bitcoind.1 bitcoin-cli.1 bitcoin-tx.1 bitcoin-util.1 bitcoin-wallet.1 '/usr/local/share/man/man1'
make[2]: Leaving directory '/home/pool/bitcoin/doc/man'
make[1]: Leaving directory '/home/pool/bitcoin/doc/man'
make[1]: Entering directory '/home/pool/bitcoin'
make[2]: Entering directory '/home/pool/bitcoin'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libbitcoinconsensus.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/pool/bitcoin'
make[1]: Leaving directory '/home/pool/bitcoin'

**Comment by david739** [comment]
bitcoind --version


This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

**Comment by david739** [comment]
it doesn't show the installed version, I thought it was stupidly installed

**Comment by MarcoFalke** [comment]
What is `git log -1` (or the source you got this from)?

**Comment by david739** [comment]
what I sent were the endings from the installation, the new ubuntu 20.04 is installed there with the commands I used on the mountain, I didn't add anything else

**Comment by david739** [comment]
now we added a few more steps to make it completely complete

**Comment by MarcoFalke** [comment]
What is `strings "$(which bitcoind)" | grep '\.99\.'`?

**Comment by david739** [comment]
I don't know what it is, how I wrote the complete procedure, what I did is on the mountain, I didn't add anything, I should reinstall ubuntu and try it again

**Comment by david739** [comment]
can you please send me a link to the commands how to create a wallet etc. i'll try maybe it's ok
