### ISSUE TITLE
feature_config_args.py failure

### ISSUE THREAD

**Issue by Rspigler** [bitcoin/bitcoin#25767]
Run test: `python3 feature_config_args.py`

Results in error:

> 
> 2022-08-01T21:05:29.574000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_die2tixp
> 2022-08-01T21:05:30.306000Z TestFramework (INFO): Test config args logging
> 2022-08-01T21:05:30.564000Z TestFramework (INFO): Test seed peers
> 2022-08-01T21:05:40.697000Z TestFramework (ERROR): Assertion failed
> Traceback (most recent call last):
>   File "/home/user/bitcoin/test/functional/test_framework/test_framework.py", line 133, in main
>     self.run_test()
>   File "/home/user/bitcoin/test/functional/feature_config_args.py", line 229, in run_test
>     self.test_seed_peers()
>   File "/home/user/bitcoin/test/functional/feature_config_args.py", line 175, in test_seed_peers
>     self.start_node(0, extra_args=['-dnsseed=1', '-fixedseeds=1', f'-mocktime={start}'])
>   File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
>     next(self.gen)
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 423, in assert_debug_log
>     self._raise_assertion_error('Expected messages "{}" does not partially match log:\n\n{}\n\n'.format(str(expected_msgs), print_log))
>   File "/home/user/bitcoin/test/functional/test_framework/test_node.py", line 167, in _raise_assertion_error
>     raise AssertionError(self._node_msg(msg))
> AssertionError: [node 0] Expected messages "['Loaded 0 addresses from peers.dat', '0 addresses found from DNS seeds', 'opencon thread start']" does not partially match log:
> 
>  
>   
>   
>   
>  
>  2022-08-01T21:05:30.776965Z [init] [init/common.cpp:127] [LogPackageVersion] Bitcoin Core version v23.99.0-ce3b75690d10 (release build)
>  2022-08-01T21:05:30.777017Z [init] [init.cpp:657] [InitParameterInteraction] InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1
>  2022-08-01T21:05:30.777088Z [init] [init.cpp:922] [AppInitParameterInteraction] Validating signatures for all blocks.
>  2022-08-01T21:05:30.777094Z [init] [init.cpp:933] [AppInitParameterInteraction] Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
>  2022-08-01T21:05:30.777164Z (mocktime: 2022-08-01T21:05:30Z) [init] [kernel/context.cpp:21] [Context] Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
> 2022-08-01T21:05:30.777175Z (mocktime: 2022-08-01T21:05:30Z) [init] [random.cpp:100] [ReportHardwareRand] Using RdSeed as an additional entropy source
>  2022-08-01T21:05:30.777180Z (mocktime: 2022-08-01T21:05:30Z) [init] [random.cpp:103] [ReportHardwareRand] Using RdRand as an additional entropy source
>  2022-08-01T21:05:30.778975Z (mocktime: 2022-08-01T21:05:30Z) [init] [init/common.cpp:98] [StartLogging] Default data directory /home/user/.bitcoin
>  2022-08-01T21:05:30.778985Z (mocktime: 2022-08-01T21:05:30Z) [init] [init/common.cpp:99] [StartLogging] Using data directory /tmp/bitcoin_func_test_die2tixp/node0/regtest
>   2022-08-01T21:05:30.778998Z (mocktime: 2022-08-01T21:05:30Z) [init] [init/common.cpp:104] [StartLogging] Config file: /tmp/bitcoin_func_test_die2tixp/node0/bitcoin.conf
>   2022-08-01T21:05:30.779015Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: regtest="1"
>   2022-08-01T21:05:30.779025Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] bind="127.0.0.1"
>   2022-08-01T21:05:30.779032Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] discover="0"
>   2022-08-01T21:05:30.779039Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] dnsseed="0"
>   2022-08-01T21:05:30.779047Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] fallbackfee="0.0002"
>   2022-08-01T21:05:30.779053Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] fixedseeds="0"
>   2022-08-01T21:05:30.779060Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] keypool="1"
>   2022-08-01T21:05:30.779067Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] listenonion="0"
>   2022-08-01T21:05:30.779074Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] natpmp="0"
>   2022-08-01T21:05:30.779082Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] peertimeout="999999999"
>   2022-08-01T21:05:30.779089Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] port="11093"
>   2022-08-01T21:05:30.779096Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] printtoconsole="0"
>   2022-08-01T21:05:30.779104Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] rpcdoccheck="1"
>   2022-08-01T21:05:30.779112Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] rpcport="16093"
>   2022-08-01T21:05:30.779119Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] server="1"
>   2022-08-01T21:05:30.779127Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] shrinkdebugfile="0"
>   2022-08-01T21:05:30.779134Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] unsafesqlitesync="1"
>   2022-08-01T21:05:30.779141Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Config file arg: [regtest] upnp="0"
>   2022-08-01T21:05:30.779149Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: datadir="/tmp/bitcoin_func_test_die2tixp/node0"
>   2022-08-01T21:05:30.779156Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: debug=""
>   2022-08-01T21:05:30.779164Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: debugexclude="libevent"
>   2022-08-01T21:05:30.779171Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: debugexclude="leveldb"
>   2022-08-01T21:05:30.779178Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: dnsseed="1"
>   2022-08-01T21:05:30.779184Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: fixedseeds="1"
>   2022-08-01T21:05:30.779192Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: logsourcelocations=""
>   2022-08-01T21:05:30.779199Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: logthreadnames=""
>   2022-08-01T21:05:30.779206Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: logtimemicros=""
>   2022-08-01T21:05:30.779213Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: mocktime="1659387930"
>   2022-08-01T21:05:30.779224Z (mocktime: 2022-08-01T21:05:30Z) [init] [util/system.cpp:1118] [logArgsPrefix] Command-line arg: uacomment="testnode0"
>   2022-08-01T21:05:30.779232Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1148] [AppInitMain] Using at most 125 automatic connections (1024 file descriptors available)
>   2022-08-01T21:05:30.788089Z (mocktime: 2022-08-01T21:05:30Z) [init] [script/sigcache.cpp:101] [InitSignatureCache] Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
>   2022-08-01T21:05:30.796940Z (mocktime: 2022-08-01T21:05:30Z) [init] [validation.cpp:1669] [InitScriptExecutionCache] Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
>   2022-08-01T21:05:30.796987Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1175] [AppInitMain] Script verification uses 1 additional threads
>   2022-08-01T21:05:30.797361Z (mocktime: 2022-08-01T21:05:30Z) [scheduler] [util/thread.cpp:18] [TraceThread] scheduler thread start
>   2022-08-01T21:05:30.806770Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:184] [InitHTTPAllowList] [http] Allowing HTTP connections from: 127.0.0.0/8 ::1/128 
>   2022-08-01T21:05:30.806890Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:321] [HTTPBindAddresses] [http] Binding RPC on address ::1 port 16093
>   2022-08-01T21:05:30.807109Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:321] [HTTPBindAddresses] [http] Binding RPC on address 127.0.0.1 port 16093
>   2022-08-01T21:05:30.807155Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:401] [InitHTTPServer] [http] Initialized HTTP server
>   2022-08-01T21:05:30.807167Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:403] [InitHTTPServer] [http] creating work queue of depth 16
>   2022-08-01T21:05:30.807177Z (mocktime: 2022-08-01T21:05:30Z) [init] [rpc/server.cpp:291] [StartRPC] [rpc] Starting RPC
>   2022-08-01T21:05:30.807193Z (mocktime: 2022-08-01T21:05:30Z) [init] [httprpc.cpp:296] [StartHTTPRPC] [rpc] Starting HTTP RPC server
>   2022-08-01T21:05:30.807201Z (mocktime: 2022-08-01T21:05:30Z) [init] [httprpc.cpp:245] [InitRPCAuthentication] Using random cookie authentication.
>   2022-08-01T21:05:30.807297Z (mocktime: 2022-08-01T21:05:30Z) [init] [rpc/request.cpp:106] [GenerateAuthCookie] Generated RPC authentication cookie /tmp/bitcoin_func_test_die2tixp/node0/regtest/.cookie
>   2022-08-01T21:05:30.807312Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:676] [RegisterHTTPHandler] [http] Registering HTTP handler for / (exactmatch 1)
>   2022-08-01T21:05:30.807321Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:676] [RegisterHTTPHandler] [http] Registering HTTP handler for /wallet/ (exactmatch 0)
>   2022-08-01T21:05:30.807335Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:425] [StartHTTPServer] [http] Starting HTTP server
>   2022-08-01T21:05:30.807343Z (mocktime: 2022-08-01T21:05:30Z) [init] [httpserver.cpp:427] [StartHTTPServer] [http] starting 4 worker threads
>   2022-08-01T21:05:30.807552Z (mocktime: 2022-08-01T21:05:30Z) [http] [httpserver.cpp:287] [ThreadHTTP] [http] Entering http event loop
>   2022-08-01T21:05:30.807784Z (mocktime: 2022-08-01T21:05:30Z) [init] [wallet/load.cpp:51] [VerifyWallets] Using wallet directory /tmp/bitcoin_func_test_die2tixp/node0/regtest/wallets
>   2022-08-01T21:05:30.807801Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Verifying wallet(s)…
>   2022-08-01T21:05:30.807840Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1261] [AppInitMain] Using /16 prefix for IP bucketing
>   2022-08-01T21:05:30.807850Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Loading P2P addresses…
>   2022-08-01T21:05:30.808116Z (mocktime: 2022-08-01T21:05:30Z) [init] [logging/timer.h:57] [Log] [addrman] CheckAddrman: new 0, tried 0, total 0 started
>   2022-08-01T21:05:30.808228Z (mocktime: 2022-08-01T21:05:30Z) [init] [logging/timer.h:57] [Log] [addrman] CheckAddrman: completed (0.00ms)
>   2022-08-01T21:05:30.808242Z (mocktime: 2022-08-01T21:05:30Z) [init] [addrdb.cpp:194] [LoadAddrman] Loaded 0 addresses from peers.dat  0ms
>   2022-08-01T21:05:30.808586Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Loading banlist…
>   2022-08-01T21:05:30.808626Z (mocktime: 2022-08-01T21:05:30Z) [init] [banman.cpp:38] [LoadBanlist] [net] Loaded 0 banned node addresses/subnets  0ms
>   2022-08-01T21:05:30.808645Z (mocktime: 2022-08-01T21:05:30Z) [init] [net.cpp:1523] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
>   2022-08-01T21:05:30.808654Z (mocktime: 2022-08-01T21:05:30Z) [init] [net.cpp:2170] [SetNetworkActive] SetNetworkActive: true
>   2022-08-01T21:05:30.810409Z (mocktime: 2022-08-01T21:05:30Z) [init] [policy/fees.cpp:455] [Read] [estimatefee] Reading estimates: 190 buckets counting confirms up to 48 blocks
>   2022-08-01T21:05:30.810608Z (mocktime: 2022-08-01T21:05:30Z) [init] [policy/fees.cpp:455] [Read] [estimatefee] Reading estimates: 190 buckets counting confirms up to 12 blocks
>   2022-08-01T21:05:30.811134Z (mocktime: 2022-08-01T21:05:30Z) [init] [policy/fees.cpp:455] [Read] [estimatefee] Reading estimates: 190 buckets counting confirms up to 1008 blocks
>   2022-08-01T21:05:30.811253Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1403] [AppInitMain] Cache configuration:
>   2022-08-01T21:05:30.811267Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1404] [AppInitMain] * Using 2.0 MiB for block index database
>   2022-08-01T21:05:30.811276Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1412] [AppInitMain] * Using 8.0 MiB for chain state database
>   2022-08-01T21:05:30.811290Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1428] [AppInitMain] * Using 440.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
>   2022-08-01T21:05:30.811315Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Loading block index…
>   2022-08-01T21:05:30.811330Z (mocktime: 2022-08-01T21:05:30Z) [init] [validation.cpp:4710] [InitializeChainstate] Switching active chainstate to Chainstate [ibd] @ height -1 (null)
>   2022-08-01T21:05:30.811367Z (mocktime: 2022-08-01T21:05:30Z) [init] [dbwrapper.cpp:150] [CDBWrapper] Opening LevelDB in /tmp/bitcoin_func_test_die2tixp/node0/regtest/blocks/index
>   2022-08-01T21:05:30.826887Z (mocktime: 2022-08-01T21:05:30Z) [init] [dbwrapper.cpp:158] [CDBWrapper] Opened LevelDB successfully
>   2022-08-01T21:05:30.826920Z (mocktime: 2022-08-01T21:05:30Z) [init] [dbwrapper.cpp:183] [CDBWrapper] Using obfuscation key for /tmp/bitcoin_func_test_die2tixp/node0/regtest/blocks/index: 0000000000000000
>   2022-08-01T21:05:30.827091Z (mocktime: 2022-08-01T21:05:30Z) [init] [node/blockstorage.cpp:331] [LoadBlockIndexDB] LoadBlockIndexDB: last block file = 0
>   2022-08-01T21:05:30.827110Z (mocktime: 2022-08-01T21:05:30Z) [init] [node/blockstorage.cpp:335] [LoadBlockIndexDB] LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=1, size=293, heights=0...0, time=2011-02-02...2011-02-02)
>   2022-08-01T21:05:30.827119Z (mocktime: 2022-08-01T21:05:30Z) [init] [node/blockstorage.cpp:346] [LoadBlockIndexDB] Checking all blk files are present...
>   2022-08-01T21:05:30.827164Z (mocktime: 2022-08-01T21:05:30Z) [init] [dbwrapper.cpp:150] [CDBWrapper] Opening LevelDB in /tmp/bitcoin_func_test_die2tixp/node0/regtest/chainstate
>   2022-08-01T21:05:30.846337Z (mocktime: 2022-08-01T21:05:30Z) [init] [dbwrapper.cpp:158] [CDBWrapper] Opened LevelDB successfully
>   2022-08-01T21:05:30.846444Z (mocktime: 2022-08-01T21:05:30Z) [init] [dbwrapper.cpp:183] [CDBWrapper] Using obfuscation key for /tmp/bitcoin_func_test_die2tixp/node0/regtest/chainstate: 223bb69586684f13
>   2022-08-01T21:05:30.846548Z (mocktime: 2022-08-01T21:05:30Z) [init] [validation.cpp:3894] [LoadChainTip] Loaded best chain: hashBestChain=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 height=0 date=2011-02-02T23:16:42Z progress=1.000000
>   2022-08-01T21:05:30.846567Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Verifying blocks…
>   2022-08-01T21:05:30.846583Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1474] [AppInitMain]  block index              35ms
>   2022-08-01T21:05:30.847557Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1631] [AppInitMain] block tree size = 1
>   2022-08-01T21:05:30.847581Z (mocktime: 2022-08-01T21:05:30Z) [init] [init.cpp:1643] [AppInitMain] nBestHeight = 0
>   2022-08-01T21:05:30.847637Z (mocktime: 2022-08-01T21:05:30Z) [loadblk] [util/thread.cpp:18] [TraceThread] loadblk thread start
>   2022-08-01T21:05:30.847728Z (mocktime: 2022-08-01T21:05:30Z) [loadblk] [kernel/mempool_persist.cpp:121] [LoadMempool] Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
>   2022-08-01T21:05:30.847748Z (mocktime: 2022-08-01T21:05:30Z) [loadblk] [util/thread.cpp:20] [TraceThread] loadblk thread exit
>   2022-08-01T21:05:30.847790Z (mocktime: 2022-08-01T21:05:30Z) [init] [net.cpp:2103] [BindListenPort] Bound to 127.0.0.1:11093
>   2022-08-01T21:05:30.847830Z (mocktime: 2022-08-01T21:05:30Z) [init] [net.cpp:2103] [BindListenPort] Bound to 127.0.0.1:18445
>   2022-08-01T21:05:30.847866Z (mocktime: 2022-08-01T21:05:30Z) [init] [addrdb.cpp:228] [ReadAnchors] Loaded 0 addresses from "anchors.dat"
>   2022-08-01T21:05:30.847936Z (mocktime: 2022-08-01T21:05:30Z) [init] [net.cpp:2277] [Start] 0 block-relay-only anchors will be tried for connections.
>   2022-08-01T21:05:30.847950Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Starting network threads…
>   2022-08-01T21:05:30.848029Z (mocktime: 2022-08-01T21:05:30Z) [net] [util/thread.cpp:18] [TraceThread] net thread start
>   2022-08-01T21:05:30.848098Z (mocktime: 2022-08-01T21:05:30Z) [addcon] [util/thread.cpp:18] [TraceThread] addcon thread start
>   2022-08-01T21:05:30.848236Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [util/thread.cpp:18] [TraceThread] opencon thread start
>   2022-08-01T21:05:30.848301Z (mocktime: 2022-08-01T21:05:30Z) [msghand] [util/thread.cpp:18] [TraceThread] msghand thread start
>   2022-08-01T21:05:30.848322Z (mocktime: 2022-08-01T21:05:30Z) [init] [noui.cpp:56] [noui_InitMessage] init message: Done loading
>   2022-08-01T21:05:30.848394Z (mocktime: 2022-08-01T21:05:30Z) [dnsseed] [util/thread.cpp:18] [TraceThread] dnsseed thread start
>   2022-08-01T21:05:30.848416Z (mocktime: 2022-08-01T21:05:30Z) [dnsseed] [net.cpp:1456] [ThreadDNSAddressSeed] Loading addresses from DNS seed dummySeed.invalid.
>   2022-08-01T21:05:30.857530Z (mocktime: 2022-08-01T21:05:30Z) [dnsseed] [addrman.cpp:612] [AddSingle] [addrman] Added 1.0.0.1:18444 mapped to AS0 to new[81][35]
>   2022-08-01T21:05:30.857563Z (mocktime: 2022-08-01T21:05:30Z) [dnsseed] [addrman.cpp:684] [Add_] [addrman] Added 1 addresses (of 1) from jzva5xo5xttqfkfm.internal: 0 tried, 1 new
>   2022-08-01T21:05:30.857575Z (mocktime: 2022-08-01T21:05:30Z) [dnsseed] [net.cpp:1485] [ThreadDNSAddressSeed] 1 addresses found from DNS seeds
>   2022-08-01T21:05:30.857585Z (mocktime: 2022-08-01T21:05:30Z) [dnsseed] [util/thread.cpp:20] [TraceThread] dnsseed thread exit
>   2022-08-01T21:05:30.921809Z (mocktime: 2022-08-01T21:05:30Z) [http] [httpserver.cpp:240] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:43440
>   2022-08-01T21:05:30.921886Z (mocktime: 2022-08-01T21:05:30Z) [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getblockcount user=__cookie__
>   2022-08-01T21:05:30.923628Z (mocktime: 2022-08-01T21:05:30Z) [http] [httpserver.cpp:240] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:43440
>   2022-08-01T21:05:30.923856Z (mocktime: 2022-08-01T21:05:30Z) [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getmempoolinfo user=__cookie__
>   2022-08-01T21:05:31.349127Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:31.349201Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [net.cpp:455] [ConnectNode] [net:debug] trying connection 1.0.0.1:18444 lastseen=146.9hrs
>   2022-08-01T21:05:31.354156Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [net.cpp:2729] [CNode] [net] Added connection peer=0
>   2022-08-01T21:05:31.354233Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [net.cpp:2745] [PushMessage] [net] sending version (114 bytes) peer=0
>   2022-08-01T21:05:31.354306Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [net_processing.cpp:1303] [PushNodeVersion] [net] send version message: version 70016, blocks=0, txrelay=1, peer=0
>   2022-08-01T21:05:31.854950Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:32.356882Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:32.857649Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:33.359252Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:33.860731Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:34.361696Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:34.863290Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:35.364832Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:35.867734Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:36.369805Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:36.870817Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:37.372111Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:37.873116Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:38.374390Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:38.875975Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:39.377264Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:39.878563Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
>   2022-08-01T21:05:40.380302Z (mocktime: 2022-08-01T21:05:30Z) [opencon] [addrman.cpp:769] [Select_] [addrman] Selected 1.0.0.1:18444 from new
> 
> 
> 2022-08-01T21:05:40.709000Z TestFramework (INFO): Stopping nodes
> 2022-08-01T21:05:40.862000Z TestFramework (WARNING): Not cleaning up dir /tmp/bitcoin_func_test_die2tixp
> 2022-08-01T21:05:40.862000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/bitcoin_func_test_die2tixp/test_framework.log
> 2022-08-01T21:05:40.862000Z TestFramework (ERROR): 
> 2022-08-01T21:05:40.862000Z TestFramework (ERROR): Hint: Call /home/user/bitcoin/test/functional/combine_logs.py '/tmp/bitcoin_func_test_die2tixp' to consolidate all logs
> 2022-08-01T21:05:40.863000Z TestFramework (ERROR): 
> 2022-08-01T21:05:40.863000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
> 2022-08-01T21:05:40.863000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
> 2022-08-01T21:05:40.863000Z TestFramework (ERROR):

Logs:
`python3 /home/user/bitcoin/test/functional/combine_logs.py '/tmp/bitcoin_func_test_die2tixp'`

Pasted here:
https://pastebin.com/SZtnGvEK

**Comment by mzumsande** [comment]
Looks like the regtest DNS seed `dummySeed.invalid.` (which is meant to be invalid, see https://github.com/bitcoin/bitcoin/pull/22098#issuecomment-888648789 for original motivation) resolves to `1.0.0.1` on your system for some reason.

**Comment by fanquake** [comment]
@Rspigler can you confirm / comment on @mzumsande's comment?

**Comment by MarcoFalke** [comment]
Closing for now, but feel free to continue discussion or reopen if there is more info

**Comment by Rspigler** [comment]
I think that is the issue, yes.

> [dnsseed] [addrman.cpp:612] [AddSingle] [addrman] Added 1.0.0.1:18444

**Comment by Rspigler** [comment]
Can this be reopened? Thanks

**Comment by Rspigler** [comment]
I don't have this issue on a fresh install of Debian on a new laptop, so it's either Qubes specific, or my-machine specific, so I'm closing.
