### ISSUE TITLE
no test coverage for -datacarrier and -datacarriersize

### ISSUE THREAD

**Issue by glozow** [bitcoin/bitcoin#25787]
The `-datacarrier` and `-datacarriersize` options were added in #3715 and #5077. Seems like those PRs did not add tests and we still don't have tests for them...? It should be easier to test things like this now with functional tests. I see `-datacarriersize` used in some places to create large transactions by stuffing outputs with lots of data but that's not very thorough. We should probably add a functional test that checks these options do what they're supposed to.

**Comment by w0xlt** [comment]
https://github.com/bitcoin/bitcoin/pull/25792 proposes a test implementation.
