### ISSUE TITLE
Wallet file verification failed error

### ISSUE THREAD

**Issue by furkandamar-ox** [bitcoin/bitcoin#25807]
Hello,
"bitcoin-cli createwallet adminwallet" ran on ubuntu server and admin_wallet folder was created in "~/.bitcoin/" directory.
Then when I type "bitcoin-cli loadwallet adminwallet" I get this error:

error code: -4
error message:
Wallet file verification failed. SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another instance of Bitcoin Core?

 `ps-aux | grep bitcoin

root 56945 116 16.0 4178224 1308340 ? Ssl Aug08 1205:58 bitcoind --daemon

root 61210 0.0 0.0 8168 724 pts/1 S+ 07:39 0:00 grep --color=auto bitcoin`

**Comment by 1440000bytes** [comment]
When you create a wallet it's automatically loaded so `loadwallet` isn't required in this case.

You can check list of loaded wallets with `listwallets`
