### ISSUE TITLE
Persist "mask values" to prevent shoulder surfing

### ISSUE THREAD

**Issue by BenWestgate** [bitcoin/bitcoin#25826]
Current Behavior: "Mask values" mode is off each launch and must be manually re-enabled.
If a wallet loads on startup from `settings.json` this leaves user vulnerable to shoulder surfing.

Solution: This mode should persist across restarts of bitcoin-qt by being saved in `Bitcoin-Qt.conf`.
Exactly how `nDisplayUnit=0` will persist the unit to show amounts in.

Expected Behavior: If I shutdown Bitcoin core with it on, I'd expect it to be on when I restart and vice versa.

_Originally posted by @BenWestgate in https://github.com/bitcoin/bitcoin/issues/16432#issuecomment-1212622753_

**Comment by hebasto** [comment]
@BenWestgate 

Could you move this issue into the dedicated [GUI repo](https://github.com/bitcoin-core/gui) please?

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/652.
