### ISSUE TITLE
[meta] Handle feature requests in Github Discussions?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#25823]
While it is possible for feature requests in issues to receive "thumbs up", it isn't possible to easily discover them by upvotes. So maybe enabling the "Discussions" tab could solve that? This way, devs could prioritize highly requested features and de-prioritize less requested ones.

**Comment by 1440000bytes** [comment]
I don't have any opinion on 'discussions' tab although this tweet looks relevant looking at the recent trend of issues being closed:

https://twitter.com/0xabad1dea/status/1458018801405120515

Closed issues in open source projects are more important for several organizations including 3 letter agencies keeping an eye on this repository for privacy and security related issues. Closing them doesn't improve anything.

**Comment by MarcoFalke** [comment]
> recent trend of issues being closed

This is not a recent trend. Issues have always been closed. For example the first issue (a feature request) has been closed: https://github.com/bitcoin/bitcoin/issues/1 . Generally I think it makes sense to drop off feature requests after a few years of inactivity. Inactivity can mean that no one wants the feature, or the feature doesn't make sense, or the implementation is impossible/too hard.

If there was a rule to keep all feature request open forever, it would be impossible to browse the issues list for bugs (including security related ones). The number of bugs a program can have is limited, however the number of features one can request are unlimited.

> 3 letter agencies keeping an eye on this repository for privacy and security related issues. Closing them doesn't improve anything.

I am not aware of a security related issue that was closed without a valid rationale and without a fix. Issues are closed on a case-by-case basis, and if needed they can also be re-opened on a case-by-case basis. Also, keep in mind that a closed issue doesn't mean the discussion has been banned from the repo forever. No one is holding anyone back to request an issue to be reopened, or create a new issue (maybe with additional context, or a summary of previous issues, or with history/recent changes relevant to the issue elaborated).

**Comment by 1440000bytes** [comment]
> Generally I think it makes sense to drop off feature requests after a few years of inactivity. Inactivity can mean that no one wants the feature, or the feature doesn't make sense, or the implementation is impossible/too hard.

Interesting. I still see lot of issues open with feature requests and some of them are more than 5 years old.

Example: https://github.com/bitcoin/bitcoin/issues/6569

**Comment by MarcoFalke** [comment]
> Example

Thx, closed it. Let us know if there any other issues that can be closed.

**Comment by ytrezq** [comment]
Some feature requests about performance can typically become a performance bug if for example, it’s no longer possible to catch up sync.
