### ISSUE TITLE
Error while running nmake.

### ISSUE THREAD

**Issue by prakhar728** [bitcoin/bitcoin#25837]
I was following the instructions given on [Readme to build on windows](https://github.com/bitcoin/bitcoin/tree/master/build_msvc). I download the qt zip installer, extracted it to a folder and ran configure command. It didn't cause any error. 
When I rank `nmake` it throws an error 
`Error opening .moc\release\moc_qaction.cpp.json for reading`.
I don't understand how to deal with this.

To actually run through so I could follow the next steps.

![image](https://user-images.githubusercontent.com/68009969/184495833-1514fdf5-8a62-4e40-a5f8-7bc9eef31daf.png)

I am running it on Windows 10, and using MS VS 2022.

**Comment by hebasto** [comment]
> I was following the instructions given on [Readme to build on windows](https://github.com/bitcoin/bitcoin/tree/master/build_msvc). I download the qt zip installer, extracted it to a folder and ran configure command. It didn't cause any error.
> When I rank `cmake` it throws an error

Could you please specify your steps more exactly, as https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md does not contain advises about "zip _installer_" and to run `cmake`?

**Comment by prakhar728** [comment]
> > I was following the instructions given on [Readme to build on windows](https://github.com/bitcoin/bitcoin/tree/master/build_msvc). I download the qt zip installer, extracted it to a folder and ran configure command. It didn't cause any error.
> > When I rank `cmake` it throws an error
> 
> Could you please specify your steps more exactly, as https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md does not contain advises about "zip _installer_" and to run `cmake`?

Sorry for the typo I ran `name`.
The exact steps I was following are :- 
1. In the Preqrequisites section I installed vcpkg first.
2. Under the section header **QT** I downloaded the single zip archive of QT source code. And extracted it to a folder namely **qt-everywhere-src-5.15.5\**. 
3. I made a build directory using `mkdir build` and changed into it. 
4. Following the instructions I ran the `..\configure -release -silent -opensource -c ....` command as mentioned there. 
5. Finally I ran `nmake` and after running some processes for a while it threw the above error.

**Comment by hebasto** [comment]
@prakhar728

Are you sure you are using ""x64 Native Tools Command Prompt for VS 2022" for compiling?

**Comment by prakhar728** [comment]
> @prakhar728
> 
> Are you sure you are using ""x64 Native Tools Command Prompt for VS 2022" for compiling?

![image](https://user-images.githubusercontent.com/68009969/184497231-c79513e7-9724-4305-a9bb-509258501751.png)
Yeah.

**Comment by hebasto** [comment]
Did you change the `-prefix` option in the `..\configure` command?

**Comment by prakhar728** [comment]
> Did you change the `-prefix` option in the `..\configure` command?

No. I just copy pasted the entire thing. 
`..\configure -release -silent -opensource -confirm-license -opengl desktop -static -static-runtime -mp -qt-zlib -qt-pcre -qt-libpng -nomake examples -nomake tests -nomake tools -no-angle -no-dbus -no-gif -no-gtk -no-ico -no-icu -no-libjpeg -no-libudev -no-sql-sqlite -no-sql-odbc -no-sqlite -no-vulkan -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip doc -skip qtdoc -skip qtgamepad -skip qtgraphicaleffects -skip qtimageformats -skip qtlocation -skip qtlottie -skip qtmacextras -skip qtmultimedia -skip qtnetworkauth -skip qtpurchasing -skip qtquick3d -skip qtquickcontrols -skip qtquickcontrols2 -skip qtquicktimeline -skip qtremoteobjects -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech -skip qtsvg -skip qtvirtualkeyboard -skip qtwayland -skip qtwebchannel -skip qtwebengine -skip qtwebglplugin -skip qtwebsockets -skip qtwebview -skip qtx11extras -skip qtxmlpatterns -no-openssl -no-feature-bearermanagement -no-feature-printdialog -no-feature-printer -no-feature-printpreviewdialog -no-feature-printpreviewwidget -no-feature-sql -no-feature-sqlmodel -no-feature-textbrowser -no-feature-textmarkdownwriter -no-feature-textodfwriter -no-feature-xml -prefix C:\Qt_static`

**Comment by hebasto** [comment]
And there are no filesystem restrictions to access the `C:\Qt_static` folder on your system, aren't there?

**Comment by prakhar728** [comment]
> And there are no filesystem restrictions to access the `C:\Qt_static` folder on your system, aren't there?

Nope. Also, I ran the cmd as Admin so I don't think that would be a problem.

**Comment by hebasto** [comment]
> I ran the cmd as Admin

Can you try without elevated rights?

**Comment by prakhar728** [comment]
> > I ran the cmd as Admin
> 
> Can you try without elevated rights?

Already did. That was the first thing I tried. After this error I thought might be some user error or something so I ran it with admin.

**Comment by prakhar728** [comment]
Also, there an online installer for Windows QT. Should I try that? If yes, what packages etc should I choose?

**Comment by fanquake** [comment]
Not sure what to do here, now that this has turned into a thread about how to compile Qt from source on Windows, which is not something we should be debugging in this issue tracker. We should probably remove the "how to compile qt from scratch" instructions from https://github.com/bitcoin/bitcoin/tree/master/build_msvc and point to some Qt docs instead.

**Comment by 1440000bytes** [comment]
@prakhar728 alternatively you could try building with WSL

**Comment by fanquake** [comment]
Moved to the GUI repo: https://github.com/bitcoin-core/gui/issues/659. Can be debugged further there if anyone wants to followup.
