### ISSUE TITLE
Compile new releases with sqlite by default

### ISSUE THREAD

**Issue by positiveblue** [bitcoin/bitcoin#25847]
**Is your feature request related to a problem? Please describe.**

I downloaded the x86 linux binaries for bitcoin v23.0 from [bitcoincore.org](https://bitcoincore.org/bin/bitcoin-core-23.0/) and I wasn't able to use the wallet descriptors because it was not compiled with sqlite support. These changes broke my test environment because I was fetching the binary to create a docker image for regtest.

**Describe the solution you'd like**

Compile the binaries with sqlite support by default, or have to versions for each release.

**Describe alternatives you've considered**

The fix was easy, compile from source with sqlite support so I have the right binaries for my docker image but I am not sure why it is not done in this way for the release binaries.

**Additional context**

Maybe there is a good reason for not compiling it directly with sqlite, so if I am missing something just let me know

**Comment by hebasto** [comment]
> Compile the binaries with sqlite support by default,

It does already.

```
$ ./bitcoin-cli -named createwallet wallet_name=sql-wallet descriptors=true
$ ./bitcoin-cli -rpcwallet=sql-wallet getwalletinfo | grep format
  "format": "sqlite",
```
