### ISSUE TITLE
Bitcoin failed to build with error MSB3073, error MSB8020 on MSVC

### ISSUE THREAD

**Issue by fangzhouxia** [bitcoin/bitcoin#25860]
**Expected behavior**
build successfully.

**Actual behavior**
Hi all,
Bitcoin fails to build on MSVC due to error MSB3073, error MSB8020. Could you help look?

**To reproduce**
error message:
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoinconsensus\libbitcoinconsensus.vcxproj]
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". 

**System information**
VS version: VS2019 (16.11.11)
Operating system:  windows server 2019
the commit of Azerothcore_wotlk we use is 5174a13

**Comment by fanquake** [comment]
https://github.com/bitcoin/bitcoin/tree/master/build_msvc

> Visual Studio 2022 is minimum required to build Bitcoin Core.

**Comment by fangzhouxia** [comment]
> https://github.com/bitcoin/bitcoin/tree/master/build_msvc
> 
> > Visual Studio 2022 is minimum required to build Bitcoin Core.

This is an internal test of MSVC, using the latest compiler.
