### ISSUE TITLE
Call for Maintainer: P2P & Networking

### ISSUE THREAD

**Issue by JeremyRubin** [bitcoin/bitcoin#25870]
As per https://github.com/bitcoin/bitcoin/pull/25560, I suggested that new maintainers should be added with a call for maintainer process as outlined below.

> "Call for Maintainer" (C4M)  by one of the existing maintainers or regular contributors. C4Ms should specify
 if the call is for a General Maintainer, or for a Scoped Maintainer. If the
 role is for a Scoped Maintainer, the C4M should describe the need for a new
 maintainer, and link to some Pull Requests (or other material) that would be
 relevant for such a maintainer to be responsible for.

The doc has not been adopted. However, bitcoin is a permissionless project, so I am opening a C4M that is just of my own personal initiative.

----------

## Do we need a new scoped maintainer?

From IRC on August 12th, 2022, where @laanwj also stepped down:

```
<bytes1440000> I see a need for "janitorial maintainer" who understands the importance of privacy in core and privacy of contributors. Since #25560 is still open and intent of reviewers doesn't look they want to improve anything in the process, there is no "call for maintainers" thing.
<bytes1440000> I would prefer someone who has already contributed to bitcoin privacy and privacy in general, not living in first world countries and not funded by brink.
<vasild> #proposedmeetingtopic vasild for a new maintainer with a focus on P2P/networking 
<vasild> I volunteer, if there is a perceived need for that.
<bytes1440000> vasild: thanks for volunteering and i think you are the best candidate for p2p/privacy. I wish we had one for mempool/privacy and wallet/privacy as well.
```

In Today's IRC Meeting, August 18th 2022. For the sake of the new process, please consider that ACKs here are ACKs on the person but are included here as demonstrating ACKs on the need for such a new maintainer & the role. Note also that vasild is not explicitly stating privacy, as bytes1440000 requested initially, which has been clarified below in this discussion to be out-of-scope for this proposed maintainer. (Please see the complete logs for all discussion, this is not a full excerpy).

```
<vasild_> Two maintainers stepped down recently (sipa and laanwj) and there is no dedicated maintainer for P2P/networking. So I step in coz I think I can help the project in that way. That's it.
<laanwj> i think it would make some sense, you've been the most active in P2P development for quite a while
<jarolrod> concept ack, i think vasild_ is very qualified for such a role. And has contributed important changes to the p2p code. He also has done extensive reviews, and catching issues others don't catch
<michaelfolkson> +1
<hebasto> concept ack
<achow101> ack
<lightlike> ack vasild
<jonatack> a thought: the past few years vasild, laanwj, and myself have been working on or reviewing a large-ish chunk of net code that few others have been. i believe sipa knows the code well, too, along with (maybe) a couple others. laanwj has been merging these changes. so it makes sense to me that one of these would maintain.
```

## Relevant Evamples of PRs such a maintainer might focus on

- https://github.com/bitcoin/bitcoin/pull/25421
- https://github.com/bitcoin/bitcoin/pull/25717
- https://github.com/bitcoin/bitcoin/pull/25688

which includes things that impact privacy in P2P
- https://github.com/bitcoin/bitcoin/pull/19860

But does not include non P2P/Networking Privacy code like:

- https://github.com/bitcoin/bitcoin/issues/23372

## Nominees

I will keep this synced with nominees from the below thread / other maintainers feel free to edit to keep synchronized.  Feel free to self nominate. As per #25560, nomination period + Q&A is "open" for 2 weeks, after which a decision may be made if desired.

Current Nominees:

- @vasild (nomination accepted, self)
- @jonatack (nomination acceptance pending)

**Comment by JeremyRubin** [comment]
noting @vasild for a self-nomination, see IRC Logs from August 12th and 18th, 2022.

**Comment by JeremyRubin** [comment]
I'm nominating @jonatack as a viable candidate for a maintainership position with this specific focus.

I feel that @jonatack is a high quality reviewer who I feel has given thorough attention to the code I have authored when he has reviewed it. As he noted in IRC, these are also areas of the codebase with which he is familiar with.

**Comment by JeremyRubin** [comment]
To all candidates I pose the following question, including later nominees:

What do you see as the current state of the P2P & Networking system, and what goals would you be hoping to accomplish in particular in your tenure as a P2P & Networking focused maintainer? What should the general goals of Bitcoin Core (not Bitcoin) with respect to P2P & Networking?

I ask because as per bitcoincore.org, 

> Project maintainers have commit access and are responsible for merging patches from contributors. They perform a janitorial role merging patches that the team agrees should be merged. They also act as a final check to ensure that patches are safe and in line with the project goals. The maintainers’ role is by agreement of project contributors.

So I think it is interesting to know what you think the project goals should be in this regard.

Thanks,

Jeremy

**Comment by 1440000bytes** [comment]
ACK for @vasild as P2P/Privacy maintainer
ACK for @jonatack as wallet/Privacy maintainer

**Comment by 1440000bytes** [comment]
> bytes1440000 can you clarify if things like the below should be included?

Yes

**Comment by achow101** [comment]
> as Wallet/Privacy maintainer

I don't think wallet privacy is the scope being discussed here. Furthermore, I do not think @jonatack would be a good fit for wallet privacy either.

In terms of scope, privacy is not a well defined scope so I don't think it is useful to have a "privacy maintainer". It is not clear what that means. This is in contrast to things like networking, p2p, mempool, build system, wallet, etc. where you can point to specific files and go "these are the files that cover that area'. No such module exists for privacy.

**Comment by 1440000bytes** [comment]
> > as Wallet/Privacy maintainer
> 
> I don't think wallet privacy is the scope being discussed here. Furthermore, I do not think @jonatack would be a good fit for wallet privacy either.
> 
> In terms of scope, privacy is not a well defined scope so I don't think it is useful to have a "privacy maintainer". It is not clear what that means. This is in contrast to things like networking, p2p, mempool, build system, wallet, etc. where you can point to specific files and go "these are the files that cover that area'. No such module exists for privacy.

This is based on the pull requests that I checked in which they were authors and improved privacy.

Privacy is a submodule in P2P, Mempool, Wallet etc.

**Comment by achow101** [comment]
> Privacy is a submodule in P2P, Mempool, Wallet etc.

There are a number of components where privacy is an aspect. That does not make it a submodule. The examples you provide are three wildly different things. There is no single "privacy" module that is used by or applies to all of them.

**Comment by michaelfolkson** [comment]
So neither of you @JeremyRubin or @1440000bytes are opposing @vasild to be added as a maintainer. As discussed in today's [IRC meeting](https://gnusha.org/bitcoin-core-dev/2022-08-18.log) the next step is for @vasild to open a PR adding his trusted keys and further discussion can be had there (if it is needed). I will post a summary of the ACKs so far on that PR when it is opened.

Regarding proposing additional maintainers after @vasild (assuming he is added as a maintainer which hasn't yet happened) you are free to propose them in a future Core dev IRC meeting where they can be discussed and considered.

Beyond that I don't know what the point of this issue is.

**Comment by 1440000bytes** [comment]
> That does not make it a submodule. The examples you provide are three wildly different things.

Sorry I did not share any examples yet.

I would be okay with any of them becoming maintainer or both. Irrespective of scope defined by me as long as they provide the scope in the pull request.

Because I can only share my opinion, @vasild and @jonatack know what they are good at and would want to contribute as maintainer.

**Comment by 1440000bytes** [comment]
> Beyond that I don't know what the point of this issue is.

Everyone is not waiting for IRC meetings in the channel which already feels suffocated so some people would get noticed by the issue. Also there can be other nominations which may or may not get the opposite to be a maintainer.

**Comment by JeremyRubin** [comment]
The reason I asked is because @1440000bytes proposed a privacy maintainer and @vasild seemed to respond by self-nominating for P2P issues. I wanted to be sure that it was correct to understand those as the same or different. Bringing it up here has clarified there was some miscommunication.


I agree with @achow101  that privacy is not the scope for this role. @1440000bytes perhaps you can make (maybe after seeing this C4M through?) a C4M for a Privacy Maintainer? It would be good to spec out what exactly such a role would entail as a maintainer given that it is not a module-defined topic. Where I disagree with @achow101 is that I think it would be very good to have a privacy maintainer, because it would be great to ensure that when we merge any PRs that have a privacy impact, we have someone who is well versed in how to analyze privacy & the goals of the project w.r.t. privacy checking it over. @1440000bytes as a concrete next step maybe you can lead a separate discussion and build out more merit for the idea of having a privacy maintainer and what/how they might do that role, and open a C4M when it seems more fleshed out?

**Comment by 1440000bytes** [comment]
Privacy by wiki definition: 

> Privacy is the ability of an individual or group to seclude themselves or information about themselves, and thereby express themselves selectively.

This is applicable for P2P, Mempool, Wallet etc.

Some developers are passionate and care to improve privacy regularly in each module. Others focus on different things as privacy isn't the only thing you look at when creating or merging a pull request. There is nothing wrong in being focused on one module and ignore privacy however reviewers may look at different things.

The reason I ACKed for @vasild and @jonatack is they have either authored pull requests that improved privacy or reviewed and been passionate about it in general.

I could certainly open another issue with only privacy maintainers that everyone ignores and is closed in a few days. However, we could look at privacy as 'submodule' that exists in everything and being improved over years.

Wallet is just another part of core and used by lot of other projects with JSON-RPC so privacy would be important.

@laanwj did a good job at reviewing pull requests with different modules.

If a pull request improved privacy and security of bitcoin core who cares if they are documented or accepted modules? I do not.

**Comment by michaelfolkson** [comment]
As is becoming customary for recent pull requests/issues from you two I will be ignoring this from now on and not commenting again. Andrew has explained why a privacy maintainer across P2P and wallet doesn't make sense. For that reason I would NACK a "privacy" maintainer and presumably Andrew would too.

**Comment by MarcoFalke** [comment]
I've removed the "call for maintainer" label, as it seemed too specific, duplicating the title. Let me know if I should add it back. Though, if we start adding very specific labels, we might end up with too many. For example, there could be a "Sanitizer" label, etc...

**Comment by JeremyRubin** [comment]
@MarcoFalke fair enough, although I think labels / titles serve different purposes (e.g., labels don't get sent in emails), labels are structured metadata that make querying easier. We can  re-introduce a label should it become relevant.

**Comment by MarcoFalke** [comment]
> labels are structured metadata that make querying easier.

Ok, happy to re-add the label if this search returns more than two results for https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue++%22call+for+maintainer%22+

**Comment by Rspigler** [comment]
ACK @vasild, he has been demonstrating his expertise in this area for a while now

**Comment by JeremyRubin** [comment]
i don't think there is popular support among contributors for core to run such processes, so closing this.
