### ISSUE TITLE
I can't define bitcoin.conf file in different folder as default

### ISSUE THREAD

**Issue by furkandamar-ox** [bitcoin/bitcoin#25886]
I installed the bitcoin libraries on /mnt/volume_fra1_02, ran it via the following setting

bitcoind -datadir=/mnt/volume_fra1_02/.bitcoin -conf=/mnt/volume_fra1_02/.bitcoin/bitcoin.conf

i get an error when i want to create a new wallet

bitcoin-cli createwallet adminwallet

response : 
No authentication cookie could be found, and RPC password is not set. See -rpcpassword and -stdinrpcpass. Configuration file: (/root/.bitcoin/bitcoin.conf)

Probably still based on "/root/.bitcoin/bitcoin.conf" directory.

Could you help?

**Comment by MarcoFalke** [comment]
You'll need to tell bitcoin-cli the auth credentials in one way or another.

If you use cookie-auth, the -datadir should be enough to specify.
If you use rpcauth in the conf file, the -conf should be enough to specify.
If you don't know, you can pass both (the same you passed to bitcoind).

See also `bitcoin-cli -help`.

**Comment by furkandamar-ox** [comment]
it shows as "Configuration file: (/root/.bitcoin/bitcoin.conf)" in the error message, but I specified the location differently.

**Comment by furkandamar-ox** [comment]
bitcoin.conf file :
daemon=1
server=1
rpcuser=*****
rpcpassword=****
rpcallowip=0.0.0.0
rpcport=8332

**Comment by kouloumos** [comment]
> it shows as "Configuration file: (/root/.bitcoin/bitcoin.conf)" in the error message, but I specified the location differently.

How did you specify the location? What shows in the error message is the location in which it looks for the configuration file. `/root/.bitcoin/bitcoin.conf` looks like the default location which means that you didn't specify `/mnt/volume_fra1_02/.bitcoin` correctly.

What MarcoFalke has suggested is to try and run
```bitcoin-cli -datadir=/mnt/volume_fra1_02/.bitcoin -conf=/mnt/volume_fra1_02/.bitcoin/bitcoin.conf createwallet adminwallet```

If you are using a non-default path (in this case `/mnt/volume_fra1_02/.bitcoin` ) you'll need to append the appropriate `-datadir`/`-conf` flag on every command.
