### ISSUE TITLE
It is possible Bitcoin core be rewarded?

### ISSUE THREAD

**Issue by Rom-sp** [bitcoin/bitcoin#25890]
Theoretically, a reward for running a full node can be useful to the network.
Possibly more people will join efforts and the the network will become stronger.
Run a full node 24 hours and 7 days per week, can be expensive (price of electricity, internet and computer available).
Why not reward the fullnoders whit Sats?

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Network-wide consensus and/or P2P changes first need to be discussed with the greater community, e.g. the `bitcoin-dev` mailing list. Also, they need a BIP to be implemented in Bitcoin Core and other software that connects to the bitcoin P2P network.

**Comment by 1440000bytes** [comment]
> 

No. Running a full node has these benefits:

1. No dependency on anyone, like some API  and verifying everything.
2. Ensuring your privacy because not using someone's node who can track lot of details about your usage.
3. Enforcing consensus rules, if an economic node.

**Comment by 1440000bytes** [comment]
> Run a full node 24 hours and 7 days per week, can be expensive (price of electricity, internet and computer available).
Why not reward the fullnoders whit Sats?

I could reward everyone with sats if they were some points I earned for free in a game. Sats is currency and you are basically asking for donations to run nodes. This is something developers can not enforce in this repository, however some users may donate voluntarily.
