### ISSUE TITLE
Update chainparams pre 24.0 branch-off

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#25921]
This should be done before the branch-off, and can be done by anyone, as the steps are easily reproducible and reviewable.

#### Useful skills:

* Building Bitcoin Core
* Follow the documentation: https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#before-branch-off

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by coreyberla** [comment]
Can you assign this to me please.

**Comment by 1440000bytes** [comment]
@coreyberla you can open a pull request and no assignment is required

Example (previous release): https://github.com/bitcoin/bitcoin/pull/24418

**Comment by coreyberla** [comment]
Will do. Just didn't want to overlap with someone else. Thanks!
