### ISSUE TITLE
qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by techy2** [bitcoin/bitcoin#25926]
ubuntu 20.04 desktop with necessary build tools for bitcoin core

QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3" since plugins are disabled in static builds
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found

bitcoin core v23.0 built using depends on ubuntu 20.04
NOTE: same issue is present with 22.0 binaries built on ubuntu 18.04
the binaries run just fine on the 18.04 server

This appears to be a dependency issue in the build tree

**Expected behavior**

bitcoin-qt to start
**Actual behavior**
bitcoin-qt failed to start, error message above

**To reproduce**
install fresh ubuntu 20.04 or lubuntu 20.04 desktop
apt-get install ..... the build stuff for bitcoin core
cd depends
make
cd ..
./autogen.sh
configure --- with lots of stuff normally used
run binary with normal config

100% every time
**System information**
lubuntu 20.04 and ubuntu 20.04

github
checkout tag v23.0

proliant GL380-G7  192G/ram 2T disk

see above

tried all the solutions found with google, about a half dozen of them
The error message about platforms not included in static build appears to be the key,
do not know how to resolve that.

**Comment by techy2** [comment]
config parameters
./configure --enable-glibc-back-compat --prefix=$(pwd)/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++" --enable-cxx --enable-static --disable-shared --disable-debug --disable-tests --disable-bench --with-pic CPPFLAGS="-fPIC -O2 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" CXXFLAGS="-fPIC -O2 --param ggc-min-expand=1 --param ggc-min-heapsize=32768"

**Comment by hebasto** [comment]
@techy2 

Please move this issue int the dedicated https://github.com/bitcoin-core/gui repo.

What is Qt configure summary when you built Qt package in your depends?

**Comment by hebasto** [comment]
Building with depends requires to use `CONFIG_SITE` variable. Mind trying to follow the [docs](https://github.com/bitcoin/bitcoin/blob/master/depends/README.md)?

**Comment by fanquake** [comment]
https://github.com/bitcoin-core/gui/issues/656
