### ISSUE TITLE
Is there an alternative to the -blockmaxsize option available in the client?

### ISSUE THREAD

**Issue by amritabithi** [bitcoin/bitcoin#25944]
The -blockmaxsize option for bitcoind was removed with issue #12640, and I need to be able to limit my block creation size, is there an alternative setting that will accomplish this or is there no control of this now beyond restricting my mempool with fees?

**Comment by achow101** [comment]
As noted in the mentioned issue, the replacement is `blockmaxweight`. Block weight is the unit used for block size, not physical size in bytes.

**Comment by amritabithi** [comment]
Oh perfect, thank you !  That is what I needed.
