### ISSUE TITLE
Compilation / build failed - Mac 12.4 M1 - ld: unknown option: -soname - make[2]: *** [libbitcoinconsensus.la] Error 1

### ISSUE THREAD

**Issue by slice-amit** [bitcoin/bitcoin#25956]
**Expected behavior**
Build should not failed 

**Actual behavior**
Build is failing

**To reproduce**
M1 - Mac OS Monterey - version 12.4
XCODE Version 13.4.1 (13F100)

1.   sh ./autogen.sh ( working fine)
2. ./configure --prefix=/Users/amit/Downloads/androidProject/wow/doit/bitcoin/depends/aarch64-linux-android --without-gui --disable-zmq --with-miniupnpc=no --with-incompatible-bdb --disable-bench --disable-tests --enable-module-ecdh CC=/opt/homebrew/Cellar/llvm/14.0.6_1/bin/clang CXX=/opt/homebrew/Cellar/llvm/14.0.6_1/bin/clang++

**./configure is failing with following errors 
ld: unknown option: -soname - make[2]: *** [libbitcoinconsensus.la] Error 1**

Making all in src
  CXX      node/libbitcoin_node_a-interface_ui.o
  CXX      node/libbitcoin_node_a-interfaces.o
  CXX      node/libbitcoin_node_a-miner.o
  CXX      node/libbitcoin_node_a-mempool_persist_args.o
  CXX      node/libbitcoin_node_a-transaction.o
  CXX      libbitcoin_node_a-noui.o
  CXX      policy/libbitcoin_node_a-fees.o
  CXX      policy/libbitcoin_node_a-rbf.o
  CXX      libbitcoin_node_a-rest.o
  CXX      rpc/libbitcoin_node_a-blockchain.o
  CXX      rpc/libbitcoin_node_a-fees.o
  CXX      rpc/libbitcoin_node_a-mempool.o
  CXX      rpc/libbitcoin_node_a-mining.o
  CXX      rpc/libbitcoin_node_a-net.o
  CXX      rpc/libbitcoin_node_a-rawtransaction.o
  CXX      rpc/libbitcoin_node_a-server.o
  CXX      rpc/libbitcoin_node_a-server_util.o
  CXX      rpc/libbitcoin_node_a-txoutproof.o
  CXX      libbitcoin_node_a-torcontrol.o
  CXX      libbitcoin_node_a-txmempool.o
  CXX      libbitcoin_node_a-txrequest.o
  CXX      libbitcoin_node_a-validation.o
  CXX      wallet/libbitcoin_node_a-init.o
  CXX      wallet/libbitcoin_wallet_a-dump.o
  CXX      wallet/libbitcoin_wallet_a-external_signer_scriptpubkeyman.o
  CXX      wallet/libbitcoin_wallet_a-feebumper.o
  CXX      wallet/libbitcoin_wallet_a-fees.o
  CXX      wallet/libbitcoin_wallet_a-interfaces.o
  CXX      wallet/libbitcoin_wallet_a-load.o
  CXX      wallet/libbitcoin_wallet_a-receive.o
  CXX      wallet/rpc/libbitcoin_wallet_a-addresses.o
  CXX      wallet/rpc/libbitcoin_wallet_a-backup.o
  CXX      wallet/rpc/libbitcoin_wallet_a-coins.o
  CXX      wallet/rpc/libbitcoin_wallet_a-encrypt.o
  CXX      wallet/rpc/libbitcoin_wallet_a-spend.o
  CXX      wallet/rpc/libbitcoin_wallet_a-signmessage.o
  CXX      wallet/rpc/libbitcoin_wallet_a-transactions.o
  CXX      wallet/rpc/libbitcoin_wallet_a-util.o
  CXX      wallet/rpc/libbitcoin_wallet_a-wallet.o
  CXX      wallet/libbitcoin_wallet_a-scriptpubkeyman.o
  CXX      wallet/libbitcoin_wallet_a-spend.o
  CXX      wallet/libbitcoin_wallet_a-wallet.o
  CXX      wallet/libbitcoin_wallet_a-walletdb.o
  CXX      wallet/libbitcoin_wallet_a-sqlite.o
  CXX      wallet/libbitcoin_wallet_a-bdb.o
  CXX      wallet/libbitcoin_wallet_a-salvage.o
  CXX      interfaces/libbitcoin_util_a-handler.o
  CXX      util/libbitcoin_util_a-system.o
  CXX      util/libbitcoin_util_a-time.o
  CXX      util/libbitcoin_util_a-url.o
  CXX      bitcoin_cli-bitcoin-cli.o
  CXX      bitcoin_tx-bitcoin-tx.o
  CXX      wallet/libbitcoin_wallet_tool_a-wallettool.o
  CXX      wallet/test/fuzz/test_fuzz_fuzz-coinselection.o
  CXX      wallet/test/fuzz/test_fuzz_fuzz-notifications.o
  CXX      test/fuzz/fuzz-addition_overflow.o
  CXX      test/fuzz/fuzz-addrman.o
  CXX      test/fuzz/fuzz-autofile.o
  CXX      test/fuzz/fuzz-banman.o
  CXX      test/fuzz/fuzz-block.o
  CXX      test/fuzz/fuzz-block_header.o
  CXX      test/fuzz/fuzz-blockfilter.o
  CXX      test/fuzz/fuzz-bloom_filter.o
  CXX      test/fuzz/fuzz-buffered_file.o
  CXX      test/fuzz/fuzz-chain.o
  CXX      test/fuzz/fuzz-checkqueue.o
  CXX      test/fuzz/fuzz-coins_view.o
  CXX      test/fuzz/fuzz-connman.o
  CXX      test/fuzz/fuzz-crypto.o
  CXX      test/fuzz/fuzz-crypto_aes256.o
  CXX      test/fuzz/fuzz-crypto_aes256cbc.o
  CXX      test/fuzz/fuzz-crypto_chacha20.o
  CXX      test/fuzz/fuzz-crypto_chacha20_poly1305_aead.o
  CXX      test/fuzz/fuzz-crypto_common.o
  CXX      test/fuzz/fuzz-crypto_diff_fuzz_chacha20.o
  CXX      test/fuzz/fuzz-crypto_hkdf_hmac_sha256_l32.o
  CXX      test/fuzz/fuzz-crypto_poly1305.o
  CXX      test/fuzz/fuzz-cuckoocache.o
  CXX      test/fuzz/fuzz-deserialize.o
  CXX      test/fuzz/fuzz-fee_rate.o
  CXX      test/fuzz/fuzz-fees.o
  CXX      test/fuzz/fuzz-flatfile.o
  CXX      test/fuzz/fuzz-float.o
  CXX      test/fuzz/fuzz-golomb_rice.o
  CXX      test/fuzz/fuzz-http_request.o
  CXX      test/fuzz/fuzz-i2p.o
  CXX      test/fuzz/fuzz-integer.o
  CXX      test/fuzz/fuzz-kitchen_sink.o
  CXX      test/fuzz/fuzz-load_external_block_file.o
  CXX      test/fuzz/fuzz-merkleblock.o
  CXX      test/fuzz/fuzz-message.o
  CXX      test/fuzz/fuzz-miniscript.o
  CXX      test/fuzz/fuzz-minisketch.o
  CXX      test/fuzz/fuzz-muhash.o
  CXX      test/fuzz/fuzz-multiplication_overflow.o
  CXX      test/fuzz/fuzz-net.o
  CXX      test/fuzz/fuzz-net_permissions.o
  CXX      test/fuzz/fuzz-netaddress.o
  CXX      test/fuzz/fuzz-netbase_dns_lookup.o
  CXX      test/fuzz/fuzz-node_eviction.o
  CXX      test/fuzz/fuzz-parse_hd_keypath.o
  CXX      test/fuzz/fuzz-policy_estimator.o
  CXX      test/fuzz/fuzz-policy_estimator_io.o
  CXX      test/fuzz/fuzz-pow.o
  CXX      test/fuzz/fuzz-primitives_transaction.o
  CXX      test/fuzz/fuzz-process_message.o
  CXX      test/fuzz/fuzz-process_messages.o
  CXX      test/fuzz/fuzz-protocol.o
  CXX      test/fuzz/fuzz-random.o
  CXX      test/fuzz/fuzz-rbf.o
  CXX      test/fuzz/fuzz-rolling_bloom_filter.o
  CXX      test/fuzz/fuzz-rpc.o
  CXX      test/fuzz/fuzz-script.o
  CXX      test/fuzz/fuzz-script_bitcoin_consensus.o
  CXX      test/fuzz/fuzz-script_descriptor_cache.o
  CXX      test/fuzz/fuzz-script_format.o
  CXX      test/fuzz/fuzz-script_interpreter.o
  CXX      test/fuzz/fuzz-script_ops.o
  CXX      test/fuzz/fuzz-script_sigcache.o
  CXX      test/fuzz/fuzz-script_sign.o
  CXX      test/fuzz/fuzz-scriptnum_ops.o
  CXX      test/fuzz/fuzz-secp256k1_ec_seckey_import_export_der.o
  CXX      test/fuzz/fuzz-secp256k1_ecdsa_signature_parse_der_lax.o
  CXX      test/fuzz/fuzz-signature_checker.o
  CXX      test/fuzz/fuzz-signet.o
  CXX      test/fuzz/fuzz-socks5.o
  CXX      test/fuzz/fuzz-span.o
  CXX      test/fuzz/fuzz-string.o
  CXX      test/fuzz/fuzz-strprintf.o
  CXX      test/fuzz/fuzz-system.o
  CXX      test/fuzz/fuzz-timedata.o
  CXX      test/fuzz/fuzz-torcontrol.o
  CXX      test/fuzz/fuzz-transaction.o
  CXX      test/fuzz/fuzz-tx_pool.o
  CXX      test/fuzz/fuzz-txorphan.o
  CXX      test/fuzz/fuzz-utxo_snapshot.o
  CXX      test/fuzz/fuzz-validation_load_mempool.o
  CXX      test/fuzz/fuzz-versionbits.o
  CXX      test/util/libtest_util_a-blockfilter.o
  CXX      test/util/libtest_util_a-mining.o
  CXX      test/util/libtest_util_a-setup_common.o
  CXX      test/util/libtest_util_a-validation.o
  CXX      test/util/libtest_util_a-wallet.o
  CXX      test/fuzz/libtest_fuzz_a-fuzz.o
  CXX      test/fuzz/libtest_fuzz_a-util.o
  **CXXLD    libbitcoinconsensus.la
  CXX      libbitcoin_node_a-blockencodings.o
ld: unknown option: -soname
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1**

  

**System information**

M1 - Mac OS Monterey - version 12.4 
XCODE Version 13.4.1 (13F100)

**Comment by MarcoFalke** [comment]
> aarch64-linux-android

Is it supported to use apple clang to cross compile to aarch64-linux-android ? If yes, it might also be good if you shared how you compiled the aarch64-linux-android depends.

**Comment by fanquake** [comment]
This is missing the make invocation you used for depends. In any case, I'm pretty sure you need to use the Android SDK, and the clang / linker that comes bundled with it. As the output says, `ld` (`ld64`) on macos, does not support the `-soname` option, which is present in GNU ld.

**Comment by fanquake** [comment]
Closing for now. Can reopen if/when the missing information is posted. However the error message is clear, you're trying to use the macOS ld64 with GNU ld options, which isn't going to work.
