### ISSUE TITLE
remove create_child_with_parents, make_chain, and create_raw_chain from test_framework/wallet

### ISSUE THREAD

**Issue by glozow** [bitcoin/bitcoin#25965]
These 3 functions create packages of transactions without broadcasting: https://github.com/bitcoin/bitcoin/blob/01e1627e25bc5477c40f51da03c3c31b609a85c9/test/functional/test_framework/wallet.py#L393 

They were introduced in #20833 and #21800 to avoid using the wallet in non-wallet functional tests.

Since then, wonderful people have created the same functionality in `MiniWallet`, so these are now redundant. I'm rewriting my branches to avoid using them. It would be a good cleanup to (1) refactor the call sites in rpc_packages.py to use MiniWallet instead, and (2) remove these 3 functions from wallet.py.

This is very similar to #20078.

#### Useful skills:

* Familiarity with our functional test suite
* Good python3 skills

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by amovfx** [comment]
Ill take a stab at this

**Comment by fanquake** [comment]
> Ill take a stab at this

There is already a PR open for this: #25986.

**Comment by amovfx** [comment]
oh ty.

**Comment by glozow** [comment]
@amovfx Your help in reviewing #25986 would be greatly appreciated :)
