### ISSUE TITLE
sendall creates tx that fails tx-size mempool check

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#26011]
Steps to reproduce:
* Create many inputs
* Call `sendall`

Error: `2022-09-05T09:07:57Z [httpworker.1] [wallet/wallet.h:827] [WalletLogPrintf] [default wallet] CommitTransaction(): Transaction cannot be broadcast immediately, tx-size`

**Comment by achow101** [comment]
Fixed by #26024
