### ISSUE TITLE
[MSVC] Bitcoin failed to build with waring c4858 on MSVC 

### ISSUE THREAD

**Issue by fangzhouxia** [bitcoin/bitcoin#26017]
**Describe**
Hi all,
Bitcoin fails to build on MSVC due to waring c4858. Could you help look?
**Expected behavior**
Build successfully.

**Actual behavior**
F:\gitP\bitcoin\bitcoin\src\sync.h(168): error C2220: the following warning is treated as an error
F:\gitP\bitcoin\bitcoin\src\sync.h(166): note: while compiling class template member function 'bool UniqueLock<_Ty,std::unique_lock<PARENT>>::TryEnter(const char *,const char *,int)'
        with
        [
            _Ty=RecursiveMutex,
            PARENT=std::recursive_mutex
        ]
F:\gitP\bitcoin\bitcoin\src\sync.h(179): note: see reference to function template instantiation 'bool UniqueLock<_Ty,std::unique_lock<PARENT>>::TryEnter(const char *,const char *,int)' being compiled
        with
        [
            _Ty=RecursiveMutex,
            PARENT=std::recursive_mutex
        ]
F:\gitP\bitcoin\bitcoin\src\net.h(822): note: see reference to class template instantiation 'UniqueLock<_Ty,std::unique_lock<PARENT>>' being compiled
        with
        [
            _Ty=RecursiveMutex,
            PARENT=std::recursive_mutex
        ]
F:\gitP\bitcoin\bitcoin\src\sync.h(168): warning C4858: discarding return value: This function returns whether the operation succeeded in modifying object state. It is dangerous to ignore the return value.
**Detail log**
[Uploading build (3).log…]()

**To reproduce**
1. git clone https://github.com/bitcoin/bitcoin F:\gitP\bitcoin\bitcoin
2. cd F:\gitP\bitcoin\bitcoin\build_msvc
3. py -3 msvc-autogen.py
4. cd F:\gitP\bitcoin\tools\vcpkg
5. git -C "F:\gitP\bitcoin\tools\vcpkg" clean -xdf 2>&1
6. bootstrap-vcpkg.bat 2>&1
7.  set path=%cd%;%path%
8. cd F:\gitP\bitcoin\bitcoin\build_msvc
9.  msbuild /m /p:Platform=x64 /p:Configuration=Release bitcoin.sln /t:Rebuild 2>&1

**System information**
VS version: VS2019 (16.11.11)
Operating system: windows server 2019
the commit of Bitcoin we use is 5174a13

**workaround**
I modified the common.init.vcxproj.in file of this text like below to solve this issue:
\<DisableSpecificWarnings\>4018;4244;4267;4334;4715;4805;4834\</DisableSpecificWarnings\>
to be:
\<DisableSpecificWarnings\>4018;4244;4267;4334;4715;4805;4834;4858\</DisableSpecificWarnings\>

**Comment by fanquake** [comment]
> VS version: VS2019 (16.11.11)

> [Visual Studio 2022 is minimum required to build Bitcoin Core.](https://github.com/bitcoin/bitcoin/tree/master/build_msvc)

**Comment by fangzhouxia** [comment]
This is an internal test of MSVC, using the latest compiler

**Comment by MarcoFalke** [comment]
> This is an internal test of MSVC, using the latest compiler

Which version? In any case, bugs in internal tests against msvc should likely be reported to microsoft.

**Comment by hebasto** [comment]
> F:\gitP\bitcoin\bitcoin\src\sync.h(168): warning C4858: discarding return value: This function returns whether the operation succeeded in modifying object state. It is dangerous to ignore the return value.

[Docs](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-170) do not mention "C4858", but "C4834", which is fixed in #25819.

**Comment by fangzhouxia** [comment]
> Which version? In any case, bugs in internal tests against msvc should likely be reported to microsoft.

The version used is as follows：
![Screenshot 2022-09-07 095124](https://user-images.githubusercontent.com/109721669/188771583-020363f6-beb7-452b-9a8a-86d3b1c33753.png)

**Comment by hebasto** [comment]
@fangzhouxia Would you mind testing https://github.com/bitcoin/bitcoin/pull/25819/commits/31168dd9b823573c7941adf27d24f6ece98cf5ea?

**Comment by fangzhouxia** [comment]
OK, I will try using this https://github.com/bitcoin/bitcoin/commit/31168dd9b823573c7941adf27d24f6ece98cf5ea

**Comment by fangzhouxia** [comment]
Thank you, I use the method you provided, it is ok.
