### ISSUE TITLE
bitcoin-cli: Compiled without bdb support (required for legacy wallets)

### ISSUE THREAD

**Issue by Sudz24** [bitcoin/bitcoin#26019]
I have installed Bitcoin Core following the official Github docs. (https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md) 
I have the berkeley-db4 installed.

However, when I run this command 
`./bitcoin-cli -named createwallet wallet_name=alice descriptors=false passphrase=alice`

I get this error:

```
error code: -4
error message:
Compiled without bdb support (required for legacy wallets)
```

Can someone help me understand what is being missed here?

**Comment by MarcoFalke** [comment]
Some notes:

* sqlite/descriptor wallets are recommended over bdb/legacy ones, so unless you have a reason to use bdb I would not recommend it
* To debug this we'll need the configure output `config.log` or steps to reproduce

**Comment by amovfx** [comment]
it sounds like you ran 
`
./configure --without-bdb
`

**Comment by MarcoFalke** [comment]
Closing for now. Can be reopened once there are answers to https://github.com/bitcoin/bitcoin/issues/26019#issuecomment-1238089807
