### ISSUE TITLE
Conan build system

### ISSUE THREAD

**Issue by liorko87** [bitcoin/bitcoin#26013]
Does bitcoin support building with conan (https://conan.io/) build system?
Is there a way to build bitcoin and the `depends` library with conan?

**Comment by MarcoFalke** [comment]
I don't think this is possible, unless someone implements it. It might be best to explain why you need this and why the existing tools are insufficient.

**Comment by liorko87** [comment]
I know this is not possible right now, I'm suggesting it as a feature request.
The reason for it is to manage it at a remote repository for developers who will use it like other libraries (OpenSSL, OpenCV...) without the need to compile bitcoin on their own station.

**Comment by MarcoFalke** [comment]
Bitcoin Core is not a library. Are you referring to libbitcoinconsensus or libbitcoinkernel?

You can download Bitcoin Core without compiling from https://bitcoincore.org/en/download/, which also links to https://snapcraft.io/bitcoin-core and https://flathub.org/apps/details/org.bitcoincore.bitcoin-qt
