### ISSUE TITLE
-march=armv8-a+crc+crypto detected as "yes" on ppc64 clang

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#26025]
Building with clang for ppc64, configure detects

```
checking whether C++ compiler accepts -march=armv8-a+crc+crypto... yes
```

But the following intrinsic checks still fail, so this is mostly harmless.

Upstream LLVM issue: https://github.com/llvm/llvm-project/issues/57587

**Comment by fanquake** [comment]
Going to close this for now, as there isn't really anything here for us to do. Upstream now has a change open to fix the problem: https://reviews.llvm.org/D145141, that should land in LLVM/Clang 17.x.
