### ISSUE TITLE
Finding peers to connect to after -onlynet changes may be problematic

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#26035]
**Expected behavior**

Bitcoin Core, ideally, should always have peers to try to connect to just like when started for the very first time (empty `peers.dat`). It should not be more difficult to find possible peers if it was ran before with a different `-onlynet=` setting.

**Actual behavior**

If addrman has some entries, even to only unreachable networks, due to previous runs and changes in `-onlynet`, then the fixed seeds will not be used.

**To reproduce**

Run with `-onlynet=ipv4`, change to `-onlynet=i2p`.

**To fix**

This problem is two-fold:

1. Fixed seeds should be used if we have 0 reachable peers in addrman. I guess this condition should be relaxed, like discussed in https://github.com/bitcoin/bitcoin/pull/25678#issuecomment-1238542029

https://github.com/bitcoin/bitcoin/blob/fc44d1796e4df5824423d7d13de3082fe204db7d/src/net.cpp#L1628

2. Even if there are a few reachable peers in addrman, e.g. 0.1% it will take a long time before they are tried. The address selection logic can be improved. It is, simplified, like this (see lines [1797](https://github.com/bitcoin/bitcoin/blob/fc44d1796e4df5824423d7d13de3082fe204db7d/src/net.cpp#L1797) and [1810](https://github.com/bitcoin/bitcoin/blob/fc44d1796e4df5824423d7d13de3082fe204db7d/src/net.cpp#L1810)):

```
select random address
if not reachable then try another random address
```

Can be improved to "select random address, but only from reachable networks".

This problem is amplified by the fact that we do not save non-reachable addresses in addrman during p2p gossip (and also see https://github.com/bitcoin/bitcoin/pull/25678). Maybe we should reconsider that as a 3rd fixup, in addition to the above 2 - save even unreachable addresses in addrman during p2p gossip and fixed seeds loadup? What is the worst that can happen? We will have some wasted space in addrman if `onlynet` is never altered?

**Comment by 1440000bytes** [comment]
> I solved issue by manually adding some known Tor v3 peer, but some less tech savvy user could have got stuck there.

Yes using `onlynet`, different combinations and fixing these issues is not easy for less tech savvy users.

**Comment by vasild** [comment]
A blatant way to workaround this is to delete `peers.dat`, but that is more for the brave and again not for the less tech savvy users. And has the obvious problem that all the addresses collected so far are lost.

**Comment by Tomrolla** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue

https://direct.lc.chat/14503671/

**Comment by vasild** [comment]
A possible improvement very much related to this: try to maintain at least 1 outbound connection to each reachable network.

Currently the chance of selecting a peer from network X to connect to depends on how many such peers are in addrman, compared to all addrman entries. It is dominated by IPv4 peers.

**Comment by jonatack** [comment]
Maybe related, and also to today's bitcoin-core-dev IRC discussion that I'm reading, last week I synced up a new node from scratch, ran it with clearnet/tor/i2p services enabled, all listening, and didn't see any I2P peers organically for several days until adding some manually with addnode.

**Comment by jonatack** [comment]
> have a separate addrman for each network

Yes, this idea has been around for years. I recall @TheBlueMatt [mentioning it](https://bitcoincore.reviews/16702#l-131) as an aside in a review club session on ASMap in 2019 and @sipa on IRC after another session as well.

**Comment by kristapsk** [comment]
Trying to maintain at least 1 outbound connection to each reachable network sounds good idea to me. Not only because of this but also because of redundancy (imagine node configured as Tor and I2P only and Tor network is under heavy attack and not working normally at some moment, then you will have at least one I2P connection all the time and will continue to receive new blocks).

**Comment by Rspigler** [comment]
> try to maintain at least 1 outbound connection to each reachable network.

Concept ACK

> last week I synced up a new node from scratch, ran it with clearnet/tor/i2p services enabled, all listening, and didn't see any I2P peers organically for several days until adding some manually with addnode.

Yes, this is exactly what I did earlier this week and posted my issue on bitcoin-core-dev IRC.  For network diversity I think this is a good idea

**Comment by Rspigler** [comment]
For the possible 3rd fixup: 

> save even unreachable addresses in addrman during p2p gossip

Would this mean that for example, i2p addresses are gossiped for nodes that only have ipv4 addresses? That would make incoming i2p connections easier to make

**Comment by vasild** [comment]
> Would this mean that for example, i2p addresses are gossiped for nodes that only have ipv4 addresses?

I am not sure I understand the question, but there are a few things here, when we receive an address gossiped by somebody to us:

1. Whether we gossip it to others
1.1. We do regardless of the address of the recipient, i.e. we could gossip I2P address to IPv4 peer (we do not know if that IPv4 peer has I2P connectivity or not)
1.2. If the address being gossiped is of unreachable network (from our point of view), then we [gossip it less](https://github.com/bitcoin/bitcoin/blob/a9ffebddbe7d3e5a21f8c794dc1c61ceb649f345/src/net_processing.cpp#L2042-L2043)
2. Whether we save it to our addrman
2.1. We only [save addresses from reachable networks](https://github.com/bitcoin/bitcoin/blob/a9ffebddbe7d3e5a21f8c794dc1c61ceb649f345/src/net_processing.cpp#L3535-L3537)

**Comment by Rspigler** [comment]
Thank you for the explanation.

What is the reasoning behind 1.2? Would it not benefit the network to have better gossiped addresses, especially for networks like I2P and CJDNS?

**Comment by mzumsande** [comment]
> What is the reasoning behind 1.2? Would it not benefit the network to have better gossiped addresses, especially for networks like I2P and CJDNS?

The general idea that addresses are more strongly gossiped among those nodes that actually can make use of them makes sense to me. Having all the clearnet-only nodes constantly exchanging I2P or onion addresses on the same scale as IPv4 seems a bit wasteful.

**Comment by CocolinoFan** [comment]
100% agree my node is running for 5 days now on IPv4, i2p, cjdns and Tor.
I have 75 in peers for IPv4 but 0 for the rest.
I can manually add peers for i2p, cjdns and Tor but in my mind it should work like [vasild] said, maintain at least one connection to every available network.

**Comment by vasild** [comment]
This has been fixed by:

https://github.com/bitcoin/bitcoin/pull/26847
https://github.com/bitcoin/bitcoin/pull/27213

closing as resolved.
