### ISSUE TITLE
dumpprivkey doesn't work in descriptor wallet

### ISSUE THREAD

**Issue by Crypto2** [bitcoin/bitcoin#26046]
In a descriptor wallet it returns "This type of wallet does not support this command" instead of the private key. Even though the wallet doesn't store the key directly it obviously knows how to build it since it can spend the funds so it should do that and return it. There are just too many cases where a private key needs to be dumped and it shouldn't be a nightmare of RPC calls and 3rd party scripts to try to get it, that just doesn't make sense usability-wise.

Just a common case point for us for example, we still use p2sh-segwit for our users since too many places still don't support  bech32 and pretty regularly people still send LTC to our BTC addresses (smh, I know) and we need to easily be able to dump the key to recover it for them.

**Comment by Crypto2** [comment]
I've read a bit there may be some worry about people leaking their xpub and an address's key since it's using non-hardened derivation. I would argue that making dumpprivkey function would actually be a much safer scenario than making less technical or just unlucky people "figure it out" with their xpriv and descriptors since:

Option 1) dumprivkey - maximum leaked data is the private key of one address

Option 2) listdescriptors + derivation - copy/pasting xprv into unknown 3rd party software which may be malicious (compromising entire wallet), them asking people for "help" and getting scammed, etc.

There are also things like clipboard monitoring viruses, which again the potential damage there is the private key of one address versus the xprv of the entire wallet.

Overall I think it's actually much safer to make dumpprivkey work normally.

**Comment by achow101** [comment]
> Option 1) dumprivkey - maximum leaked data is the private key of one address

No, it is not. The maximum leaked data is the xprv of the parent. It sounds like you misunderstand the concern with the parent xpub and child private key - given a parent xpub and a child private key derived with unhardened derivation, the parent xprv can be computed. It is far less obvious that this is the case, and therefore far more dangerous than retrieving the xprv. The xprv is more obviously something that is meant to be kept secret.

**Comment by Crypto2** [comment]
It sounds like you misunderstood? dumpprivkey doesn't return the xpub as well; that would have to be leaked separately.

**Comment by achow101** [comment]
The point is that users will have to both know that they can't share the xpub with anyone they may have shared a child private key with, or vice versa, and remember this at a future time when they may wish to share such information with others. Furthermore, just with your example of clipboard malware, the malware that steals the child private key can also now get the entire xprv as xpubs are not encrypted - it can get the private key from the clipboard, and the xpub by reading the wallet database from disk. And since users are unlikely to know about this possibility, we should make it harder for users to shoot themselves in the foot.

> In crypto it's not even really acceptable have a user running their own wallet and want the private key to their own address and be like "Nah, we don't trust you with that" lol.

We give them the xprv. That's way more information than just a single private key. Frankly, the biggest threat to a user's Bitcoin is the user themselves.

**Comment by Crypto2** [comment]
Exactly, that's why dumpprivkey is the better solution since it minimizes those risks. Yes, give them warnings and/or force them to add a config option; but at the end of the day it's safer than having people who don't know what they are doing playing around with their xprv's with much less warning than that about the dangers of it.

**Comment by 1440000bytes** [comment]
A lot of new wallets don't support

Example: You cannot use it for 2 of 3 multisig

Example script: https://github.com/1440000bytes/p2p 

I never said anything because lot of open pull request changing things and achow101 understands issues

**Comment by w0xlt** [comment]
I proposed the https://github.com/bitcoin/bitcoin/pull/25366 to address this issue,  but there are risks that are also mentioned here.

**Comment by Crypto2** [comment]
There are just too many cases where you need a private key to correct an error or otherwise as I mentioned above - and it's just wrong in general to tell users "sorry you can't have your private key because we say so, so go dump your xprv and do some potentially even more risky stuff to figure it out". I fully support a requirement of an extra parameter or config entry to enable the RPC to work, so the user has to specifically acknowledge the risk that way before it works for them.

**Comment by Tonystark423** [comment]
> 

Well put my friend

**Comment by Tonystark423** [comment]
@crypto2

**Comment by Tonystark423** [comment]
@crypto2 if u give a man a fish he will eat for a night but if you teach him and show him how to catch his own fish he will eat for life

**Comment by Tonystark423** [comment]
I mean there's a serious undertone in crypto where there is just this imherint distrust I understand why but obviously this particular situation does not fit that bill. I mean ironically they couldnt have picked a more genuine person. I can only imagine what he's going through trying to do right by the crypto community, the world, not to mention his family and friends are on his ass too. What a predicament he is probably ready to throw his hands up and walk away, I mean this guy's character is being questioned about things that aren't even in his character

**Comment by achow101** [comment]
Closing as there is a lack of support for this feature.

**Comment by Crypto2** [comment]
There is a ton of support for it, just not from the Bitcoin devs :(
