### ISSUE TITLE
Node stuck in "Pruning BlockStore" mode over 24 hours now?

### ISSUE THREAD

**Issue by Rlavington** [bitcoin/bitcoin#26072]
**Is your feature request related to a problem? Please describe.**

Error: 

2022-09-08T05:53:01Z Fatal LevelDB error: Corruption: 40 missing files; e.g.: C:\Users\ozlav.DESKTOP-PQL90HA\AppData\Roaming\Bitcoin\chainstate

its missing 40 files some how??

**Describe the solution you'd like**

I have already "reindex-chainstate" in command prompt. 

To rebuild the blockchain from where the error occurred. 

**Describe alternatives you've considered**

I have already "reindex-chainstate" in command prompt. 

**Additional context**

Still stuck in Pruning blockstore. 

I have a 2T HDD and bandwidth of 50mbps. 

Thanks

![20220912_192510.jpg](https://user-images.githubusercontent.com/70559445/189792817-72c92149-0c2f-43b7-9bc1-96cbdf86579f.jpg)

**Comment by MarcoFalke** [comment]
When did this issue first occur?

Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

Please be aware that the debug log might contain personally identifying information.

**Comment by Rlavington** [comment]
I have already looked at my log. It's an Error where 40 files are missing. This happen a few days ago. 

So I'm trying to repare it from where it left off. But the question is how long will it take to repare??

**Comment by aureleoules** [comment]
Do you mind sharing your `debug.log` though? It would be helpful to debug your situation.
Also, was your node fully synced before running into this problem?

**Comment by Rlavington** [comment]
> Do you mind sharing your `debug.log` though? It would be helpful to debug your situation.
> Also, was your node fully synced before running into this problem? 


Error:

2022-09-08T05:53:01Z Fatal LevelDB error: Corruption: 40 missing files; e.g.: C:\Users\ozlav.DESKTOP-PQL90HA\AppData\Roaming\Bitcoin\chainstate

There, it lost 40 files some how??

Yes I was fully synced up and work fine for a few days before this happened.

**Comment by hebasto** [comment]
This issue looks like a continuation of #26042 after applying of https://github.com/bitcoin/bitcoin/issues/26042#issuecomment-1240707358:

> **Describe the solution you'd like**
> 
> I have already "reindex-chainstate" in command prompt.
> 
> To rebuild the blockchain from where the error occurred.
> 
> **Describe alternatives you've considered**
> 
> I have already "reindex-chainstate" in command prompt.

**Comment by Rlavington** [comment]
Just an update date on how it all went. I had to delete all of the blocks. 

Then just by change the Bitcoincore version 24.0 became available.

I download the new version 24.0 then I had to re-sync it all again. 

Now it works. 

Also made a back on my portable HDD.
