### ISSUE TITLE
macOS glibtoolize (confusingly) complains of missing gm4 / gnum4 / m4

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#26155]
Just ran into this when trying to build v24.0rc1 from scratch on macOS 12.6 (two separate machines).

```
git clean -dfx
% ./autogen.sh  
glibtoolize:   error: One of these is required:
glibtoolize:                 gm4 gnum4 m4
glibtoolize:   error: Please install GNU M4, or 'export M4=/path/to/gnu/m4'.
autoreconf: error: /usr/local/bin/glibtoolize failed with exit status: 1
```

There's no new dependency mentioned in [build-osx](https://github.com/bitcoin/bitcoin/commits/master/doc/build-osx.md).

Turns out I just had to reinstall the Xcode command line tools after the update to macOS 12.6 apparently silently nuked them. This shouldn't affect actually new users, because we tell them to install Xcode. See also #13601.

**Comment by Sjors** [comment]
Self closing, I'm sure Google will find this when others search the error message.

**Comment by fanquake** [comment]
>  This shouldn't affect actually new users, because we tell them to install Xcode.

No we don't? You only need the command line tools, which is what we tell users to install. There is no reason nor requirement to install Xcode in it's entierity to compile Bitcoin Core.

**Comment by Sjors** [comment]
> You only need the command line tools

That's what I meant. I wonder if those also get nuked macOS updates, or this only happens when you install the command line tools from Xcode.
