### ISSUE TITLE
CI: Old versions of git can't handle merges

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#26163]
It appears git versions older than 2.33 can't handle some simple merges, and many of our CI tasks use such old versions.

The simplest fix is probably to just use GitHub's generated merge branch rather than trying to merge in each CI instance, but I haven't tested it.

**Comment by MarcoFalke** [comment]
We'll probably need to set the merge strategy: https://github.blog/changelog/2022-09-12-merge-commits-now-created-using-the-merge-ort-strategy/

**Comment by MarcoFalke** [comment]
Though, I am not sure if the added complexity to the CI system is worth the rare edge cases.

**Comment by luke-jr** [comment]
If it's simply a matter of using origin-pull/N/merge instead of origin-pull/N/head, it doesn't seem that complex?

**Comment by MarcoFalke** [comment]
what is the ref called? This doesn't work:

```diff
diff --git a/.cirrus.yml b/.cirrus.yml
index ae962f2906..6cb7253162 100644
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -30,8 +30,8 @@ base_template: &BASE_TEMPLATE
     - git config --global user.email "ci@ci.ci"
     - git config --global user.name "ci"
     - if [ "$CIRRUS_PR" = "" ]; then exit 0; fi
-    - git fetch $CIRRUS_REPO_CLONE_URL $CIRRUS_BASE_BRANCH
-    - git merge FETCH_HEAD  # Merge base to detect silent merge conflicts
+    - git fetch $CIRRUS_REPO_CLONE_URL "${CIRRUS_PR}/merge"
+    - git checkout FETCH_HEAD  # Use merged changes to detect silent merge conflicts
 
 main_template: &MAIN_TEMPLATE
   timeout_in: 120m  # https://cirrus-ci.org/faq/#instance-timed-out

**Comment by luke-jr** [comment]
Try `"pull/${CIRRUS_PR}/merge"`
