### ISSUE TITLE
Question: consensus on the moving average

### ISSUE THREAD

**Issue by davejakenic** [bitcoin/bitcoin#26181]
Hi,

I research on consensus and need a forced delay between submittability of new blocks.
In bitcoin you use stochastics + processor clock speed. This allows you to choose an expected forced delay, which you chose to be 10min.

Quote from White Paper:
"To compensate for increasing hardware speed and varying interest in running nodes over time, the proof-of-work difficulty is determined by a moving average targeting an average number of blocks per hour. If they're generated too fast, the difficulty increases."

I do not see a way to find consensus on the present value of the moving average without yet implementing another consensus mechanism. But it appears necessary to have a very accurate global consensus on the exact value of the average because this value determines the mining difficulty. ***So how do you do it?*** Please give all the details in a novice-comprehensible way.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
