### ISSUE TITLE
Add german translation for "Restore Wallet..."

### ISSUE THREAD

**Issue by martinschwarz** [bitcoin/bitcoin#26187]
Using the german locale, the file menu item "Restore Wallet..." is missing a translation.

Instead of "Restore Wallet..." I would expect the german translation "Wallet wiederherstellen..."

Windows 7, 64-bit, German 

bitcoin-24.0rc1-win64-setup.exe binary from bitcoincore.org/bin

**Comment by hebasto** [comment]
24.0rc1 misses the recent translations. They will be pulled into 24.0rc2 in #26141.

Also you could check whether any particular string has already been translated on https://www.transifex.com/bitcoin/. If something is wrong and you are a native/fluent German speaker, don't hesitate to contribute your translations via Transifex web-editor.
