### ISSUE TITLE
bitcoin-cli does'nt have any method. Error -32601

### ISSUE THREAD

**Issue by OstapKonchevych** [bitcoin/bitcoin#26193]
I have installed bitcoin core running on my local machine. (Linux Ubuntu 20.04 LTS)
I want to create a new address,wallet  using bitcoin-cli, executing a command as follows then an error message was displayed.
How can I solve it?

bitcoin-cli createwallet(or etc...)
error code: -32601
error message:
Method not found

I try to use bitcoin-cli and RPC curl, but nothing

**Comment by aureleoules** [comment]
How did you install Bitcoin Core? 
You may not have the wallet compiled or disabled the wallet feature in `bitcoin.conf`.

**Comment by Naviruiz** [comment]
??

**Comment by OstapKonchevych** [comment]
> How did you install Bitcoin Core? You may not have the wallet compiled or disabled the wallet feature in `bitcoin.conf`.

I downloaded the kernel source code from github, and installed using autoget.sh , make and make install
At first I had problems due to missing packages, but later I installed the missing packages

**Comment by MarcoFalke** [comment]
What was the `./configure` summary?

**Comment by OstapKonchevych** [comment]
> What was the `./configure` summary?

Is it possible to check this?

**Comment by MarcoFalke** [comment]
Yes, it will be printed to your terminal or saved in the `config.log` file

**Comment by 1440000bytes** [comment]
> I have installed bitcoin core running on my local machine. (Linux Ubuntu 20.04 LTS) I want to create a new address,wallet using bitcoin-cli, executing a command as follows then an error message was displayed. How can I solve it?
> 
> bitcoin-cli createwallet(or etc...) error code: -32601 error message: Method not found
> 
> I try to use bitcoin-cli and RPC curl, but nothing

Please install https://github.com/bitcoin/bitcoin/issues/26193 and if this works fine, there was something wrong when you tried to build bitcoin core. Easiest thing in the world, takes some times and docs are available.

**Comment by OstapKonchevych** [comment]
> Yes, it will be printed to your terminal or saved in the `config.log` file

config.log - https://pastebin.com/S6TAdd6w

Also, ./configure after running shows:

Options used to compile and link:
  external signer = yes
  multiprocess    = no
  with experimental syscall sandbox support = yes
  with libs       = yes
  with wallet     = no
  with gui / qt   = no
  with zmq        = no
  with test       = yes
  with fuzz binary = yes
  with bench      = yes
  with upnp       = no
  with natpmp     = no
  use asm         = yes
  USDT tracing    = no
  sanitizers      = 
  debug enabled   = no
  gprof enabled   = no
  werror          = no
  LTO             = no

  target os       = linux-gnu
  build os        = linux-gnu

  CC              = gcc
  CFLAGS          = -pthread -g -O2
  CPPFLAGS        =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION 
  CXX             = g++ -std=c++17
  CXXFLAGS        =    -fstack-reuse=none -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection  -Wall -Wextra -Wformat -Wformat-security -Wvla -Wredundant-decls -Wdate-time -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Woverloaded-virtual -Wsuggest-override -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-deprecated-copy    -fno-extended-identifiers -g -O2
  LDFLAGS         =  -lpthread  -Wl,-z,relro -Wl,-z,now -Wl,-z,separate-code -pie   
  AR              = /usr/bin/ar
  ARFLAGS         = cr

**Comment by aureleoules** [comment]
>  with wallet = no

You're missing the SQLite or BDB dependency to compile the wallet. See https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions.

**Comment by OstapKonchevych** [comment]
> > No package 'sqlite3' found
> > ...
> > with wallet = no
> 
> You're missing the SQLite or BDB dependency to compile the wallet. See https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions.

What to do after installation?
Need to recompile the kernel?

**Comment by MarcoFalke** [comment]
If sqlite is missing you'll need to install it with `sudo apt install libsqlite3-dev`, see https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions

**Comment by kouloumos** [comment]
> What to do after installation? Need to recompile the bitcoin core?

Yes, you'll need recompile following the steps you done before (`./configure`, `make`, etc.)
When you run `./configure` make sure that summary shows `with wallet = yes`.

**Comment by OstapKonchevych** [comment]
> If sqlite is missing you'll need to install it with `sudo apt install libsqlite3-dev`, see https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions



> > What to do after installation? Need to recompile the bitcoin core?
> 
> Yes, you'll need recompile following the steps you done before (`./configure`, `make`, etc.) When you run `./configure` make sure that summary shows `with wallet = yes`.

Thank you, guys. It`s work :)
