### ISSUE TITLE
Adjust RPCTypeCheckObj error string

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#26214]
the json type check error strings were recently unified, however one instance was forgotten, see https://github.com/bitcoin/bitcoin/pull/25737#discussion_r971066880 

It would be good to unify the last string as well.

#### Useful skills:

* Compiling Bitcoin Core
* Background in JSON, C++, Python
* Running the functional tests

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by araujo88** [comment]
Hello. I'm new to the Bitcoin Core. I would like to work on this issue.

**Comment by fanquake** [comment]
Closed by #26240 ?
