### ISSUE TITLE
bitcoin core's  sync has stop for days!

### ISSUE THREAD

**Issue by Reisen1969** [bitcoin/bitcoin#26225]
![image](https://user-images.githubusercontent.com/76834109/193436303-1e58832f-9dc5-4b00-a7de-005beba69019.png)

![image](https://user-images.githubusercontent.com/76834109/193436350-b6f248a6-af6c-48d4-89c0-a44b43d523f1.png)

![image](https://user-images.githubusercontent.com/76834109/193436357-36b56a3a-b59d-4bc7-99c0-e23c0b5084e3.png)

OS info:
windows11  21H2

what should i do?

**Comment by MarcoFalke** [comment]
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

Please be aware that the debug log might contain personally identifying information.

**Comment by live-suppo** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by fanquake** [comment]
ping @Reisen1969
