### ISSUE TITLE
Error code -4. How to fix is?

### ISSUE THREAD

**Issue by OstapKonchevych** [bitcoin/bitcoin#26239]
Hi there. 
I installed bitcoin core version v.24.99.0 from source code, then create test wallet:
`bitcoin-cli createwallet "TestWallet"`
It worked, wallet created. But, when i trying using command dumpwallet, sethdseed ...etc it's not work.
I see error:
`error code: -4
error message:
Only legacy wallets are supported by this command`
Why i see this error, and how to fix it?

**Comment by MarcoFalke** [comment]
Descriptor wallets (the new wallet format enabled by default) do not support those commands. A freshly created descriptor wallet is HD by default, so there is no need to call `sethdseed`

**Comment by Jezz12-cloud** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by OstapKonchevych** [comment]
> dumpwallet

Ok. OK. And if dumpwallet doesn't work either? How do I save my wallet?
Can I just copy it from the wallets folder?

**Comment by MarcoFalke** [comment]
See also https://github.com/bitcoin/bitcoin/blob/master/doc/managing-wallets.md#14-backing-up-the-wallet

**Comment by OstapKonchevych** [comment]
> See also https://github.com/bitcoin/bitcoin/blob/master/doc/managing-wallets.md#14-backing-up-the-wallet

Thank you. That is all :)
