### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#2626]
I think it would be good the the ecosystem if at least the GUI client had client version update checker to notify users when a new version is released. Doesnt have to be a full on auto-update, just an update checker and notify user new version is available.

Suggestion is to use the RAW feature of github to host the latest version at github.com/bitcoin.org, something this:

https://raw.github.com/bitcoin/bitcoin.org/master/README.md which makes use of both SSL and git versioning (which makes it not only difficult to change, but tamper evident).

**Comment by MarcoFalke** [comment]
Bitcoin Core is probably not the right place to put this functionality and there already exist a bunch of solutions outside of Bitcoin Core:

* You can subscribe to a mailing list that notifies of new Bitcoin Core releases. E.g. https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-core-dev, https://bitcoinops.org/en/newsletters/ or any other website that does it
* You can ask your package manager for updates. E.g. the Ubuntu ppa would update on your request. However, the ppa has been discontinued in favor of the snap package https://snapcraft.io/bitcoin-core, which allows you to set specific update rules. Or the flathub package https://flathub.org/apps/details/org.bitcoincore.bitcoin-qt
* Something else I missed to mention

**Comment by MarcoFalke** [comment]
Unless there are objections, I am going to close this issue as out-of-scope in about four weeks.
