### ISSUE TITLE
setminrelayfee

### ISSUE THREAD

**Issue by amovfx** [bitcoin/bitcoin#26269]
I think this is something within my ability to add.

**Is your feature request related to a problem? Please describe.**

The ability to change minrelaytxfee without restarting. 

**Describe the solution you'd like**

I would like the ability to set the relayfee by a bitcoin-cli rpc call.
```
setminrelayfee amount

Set the transaction fee rate in BTC/kvB for this wallet. Overrides the global -setminrelayfee config parameter.
Can be deactivated by passing 0 as the fee. In that case automatic default min fee will be used.

Arguments:
1. amount    (numeric or string, required) The transaction fee rate in BTC/kvB

Result:
true|false    (boolean) Returns true if successful

Examples:
> bitcoin-cli setminrelayfee 0.00001
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "setminrelayfee", "params": [0.00001]}' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```

**Describe alternatives you've considered**

**Additional context**

I encountered this while hooking up a lightning network node. My relay fee was too high from bad conf settings and was blocking funding transactions. I wasn't able to change this value and had to restart bitcoind instead of just making  an rpc call.

**Comment by glozow** [comment]
This policy is already configurable using `-minrelaytxfee`.

**Comment by kouloumos** [comment]
> This policy is already configurable using `-minrelaytxfee`.

But can you change that without restarting? Not arguing about its necessity, but that's what the feature request is about.

**Comment by stickies-v** [comment]
Are there any real use cases for needing to change this value on-the-fly? If it's just a matter of "I forgot to set this value when launching bitcoind", then the appropriate solution would be to just restart bitcoind with the correct value and we shouldn't be adding extra complexity to the RPC imo.

**Comment by glozow** [comment]
I would generally concept NACK to making mempool policies dynamically configurable while the node is running, as
- I haven't heard any use case for this other than "I forgot to set it."
- You'd need to re-validate all your mempool transactions to adhere to this policy. Best way to do that is to restart for a dump/load.

**Comment by glozow** [comment]
> This feature would be a good learning exercise for me but if the consensus is that it's not a solid win for a software, let's just close this?

Thank you for your interest in contributing. I'd recommend issues/PRs labeled "good first issues" as they are usually conceptually non-controversial. PR review is both greatly needed on the repository and a fantastic way to learn the codebase. The [contributing guide](https://githu,b.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#getting-started) has more tips on getting started. Testing v24.0rc1 would also be greatly appreciated right now.

> Maybe I'll propose to lnd to check what the minrelaytxfee is on startup to throw a warning that bitcoin isn't configured properly.

Seems appropriate to check that an assumption is true before proceeding.

**Comment by amovfx** [comment]
ty!
