### ISSUE TITLE
Website is not fully Responsive

### ISSUE THREAD

**Issue by Vanshika7902** [bitcoin/bitcoin#26276]
**Issue:**
Website is not fully Responsive

I want to make the website fully Responsive.

![Screenshot (116)](https://user-images.githubusercontent.com/92636041/194475189-49f68396-c945-4213-905b-9a4fec238f3e.png)

**Comment by carlgiroux23071979** [comment]
Le ven. 7 oct. 2022, 1 h 42 a.m., Vanshika ***@***.***> a
écrit :

**Comment by aureleoules** [comment]
The repository for the website is this one: https://github.com/bitcoin-core/bitcoincore.org.
