### ISSUE TITLE
CentOS compilation error-  No rule to make target

### ISSUE THREAD

**Issue by liorwavebl** [bitcoin/bitcoin#26273]
I'm trying to compile bitcoin v23.0 tag (commit id: `fcf6c8f`). During the compilation I received this error:
```
make[2]: *** No rule to make target '%reldir%/lib/univalue.cpp', needed by '%reldir%/lib/libunivalue_la-univalue.lo'.  Stop.
```

OS: CentOS 7
Compiler GCC 11.2.0

**Comment by MarcoFalke** [comment]
Did you run `make distclean` before `./configure`?

What are the exact steps to reproduce from a fresh install of CentOS 7?

**Comment by liorwavebl** [comment]
Steps to reproduce:

1. Install gcc 11.2.0
2. Clone bitcoin and checkout v23.0
3. Compile bitcoin dependencies- `make -C ./deploy NO_QT=1`
4. Run `./configure`
5. Run `make`

**Comment by liorwavebl** [comment]
I updated my original response.

**Comment by hebasto** [comment]
It does not look correct:
> 4\. Compile bitcoin dependencies- `make -C ./deploy NO_QT=1`

Should be: `make -C ./depends NO_QT=1`

**Comment by hebasto** [comment]
Also building with depends require to the `CONFIG_SITE` variable when running `./configure` script.

**Comment by hebasto** [comment]
Assuming a clean repository, you also need to run the `./autogen.sh` script before configuring.

**Comment by MarcoFalke** [comment]
Can you upgrade your operating system? This might be the easiest solution, given that you'll have to do it anyway before CentOS 7 is EOL.

**Comment by MarcoFalke** [comment]
Even if you managed to compile this, it wouldn't run:

```
./bitcoin-23.0/bin/bitcoind: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./bitcoin-23.0/bin/bitcoind)
