### ISSUE TITLE
why createwallet command not work in compiled bitcoin core 

### ISSUE THREAD

**Issue by vnxz** [bitcoin/bitcoin#26285]
i compiled bitcoin core version 24.99 with BerkeleyDB 4.8.30
when i call ./bitcoin-cli createwallet mywallet .
it show method not found .
am i missing wallet support ?
why?

**Comment by achow101** [comment]
You are probably missing wallet dependencies and so the wallet was not enabled. See #26193 for a user who did the same thing.

Otherwise post your `./configure` summary.

**Comment by vnxz** [comment]
> You are probably missing wallet dependencies and so the wallet was not enabled. See #26193 for a user who did the same thing.
> 
> Otherwise post your `./configure` summary.

```
Options used to compile and link:
  external signer = yes
  multiprocess    = no
  with experimental syscall sandbox support = yes
  with libs       = yes
  with wallet     = yes
    with sqlite   = yes
    with bdb      = no
  with gui / qt   = no
  with zmq        = no
  with test       = yes
  with fuzz binary = yes
  with bench      = yes
  with upnp       = no
  with natpmp     = no
  use asm         = yes
  USDT tracing    = no
  sanitizers      =
  debug enabled   = no
  gprof enabled   = no
  werror          = no
  LTO             = no

  target os       = linux-gnu
  build os        = linux-gnu

  CC              = gcc
  CFLAGS          = -pthread -g -O2
  CPPFLAGS        =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION
  CXX             = g++ -std=c++17
  CXXFLAGS        =    -fstack-reuse=none -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection  -Wall -Wextra -Wformat -Wformat-security -Wvla -Wredundant-decls -Wdate-time -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Woverloaded-virtual -Wsuggest-override -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-deprecated-copy    -fno-extended-identifiers -g -O2
  LDFLAGS         =  -lpthread  -Wl,-z,relro -Wl,-z,now -Wl,-z,separate-code -pie
  AR              = /usr/bin/ar
  ARFLAGS         = cr

```
in configure 
with wallet =yes .

**Comment by fanquake** [comment]
> i compiled bitcoin core version 24.99 with BerkeleyDB 4.8.30

>   with wallet     = yes
    with sqlite   = yes
    with bdb      = no

BDB isn't being found by configure. Ensure it is actually installed, and pass any paths/flags to configure as required. If that doesn't work, check in config.log, to see what is causing the BDB check to fail.

**Comment by MarcoFalke** [comment]
`createwallet` should succeed, since you have descriptor wallets compiled in. Are you sure you are running the binary you have compiled?

There should be no need for you to compile with BDB, which is only used for legacy wallets.

**Comment by fanquake** [comment]
ping @vnxz.

**Comment by MarcoFalke** [comment]
Closing for now. Let us know if you have any other questions.
