### ISSUE TITLE
estimatesmartfee returns 50 sat/vB on an empty mempool for inclusion in 1008 blocks

### ISSUE THREAD

**Issue by antonilol** [bitcoin/bitcoin#26304]
**Expected behavior**

when the mempool is empty, i expect something really low, at least smaller than 3 sat/vB, but not 50 sat/vB

**Actual behavior**

```
$ bitcoin-cli -testnet estimatesmartfee 1
{
  "feerate": 0.00050106,
  "blocks": 2
}
```
```
$ bitcoin-cli -testnet estimatesmartfee 1008
{
  "feerate": 0.00050106,
  "blocks": 111
}
```

**To reproduce**

run `bitcoin-cli -testnet estimatesmartfee` on the testnet when the difficulty drops to 1 (happens every few months or so i dont know why)

**System information**

bitcoincore.org download v23

**Any extra information that might be useful in the debugging process.**

blocks were *flowing* in like every few seconds a block got mined

**Comment by aureleoules** [comment]
> when the difficulty drops to 1 (happens every few months or so i dont know why)

See the fresh new #26303.

**Comment by MarcoFalke** [comment]
I don't think anything can be done here. Seems overkill to adjust estimatesmartfee to accommodate a broken test network. Have you tried signet?

**Comment by antonilol** [comment]
> Have you tried signet?

it works fine on the signet, empty mempool there and it almost always stays close to 1 sat/vB, just like the testnet when block speed is normal
it just feels really counter-intuitive to get a high fee estimation when blocks are mined really fast and the mempool is empty

**Comment by adamjonas** [comment]
> I don't think anything can be done here

This appears to be something that isn't going to be picked up in the near future.
