### ISSUE TITLE
Testnet difficulty was reset at height 2350655

### ISSUE THREAD

**Issue by leevlad** [bitcoin/bitcoin#26303]
It appears that the testnet difficulty was reset from `83,269,806.51979084` at block height [2350654](https://www.blockchain.com/explorer/blocks/btc-testnet/2350654) down to `1.00` in the next block at height [2350655](https://www.blockchain.com/explorer/blocks/btc-testnet/2350655).

I'm seeing this on my own testnet nodes (`v23.0`) as well as on several blockchain explorers (e.g. [blockchain.com](https://www.blockchain.com/explorer/blocks/btc-testnet/2350655) and [blockchair](https://blockchair.com/bitcoin/testnet/block/2350655))

At the time of writing this post, the network has produced about 16k blocks in 6 hours, while the difficulty is crawling back up slowly (it's at `65,536.00` at the time of writing).

Was this a scheduled testnet reset of some kind or maybe a bug?

**Comment by aureleoules** [comment]
> if no block has been found in 20 minutes, the difficulty automatically resets back to the minimum for a single block

from https://en.bitcoin.it/wiki/Testnet

Block 2350654 was mined on Oct 13, 2022, 9:54:51 AM
Block 2350655 was mined on Oct 13, 2022, 10:15:06 AM

**Comment by leevlad** [comment]
Thank you, I was unaware of this behavior on the Testnet.

**Comment by leevlad** [comment]
After reading the above wiki link, the following statement is also made: 
> if no block has been found in 20 minutes, the difficulty automatically resets back to the minimum for a single block, after which it returns to its previous value

I don't see the difficulty returning to its previous value in subsequent blocks. Is that an error in the wiki?

**Comment by leevlad** [comment]
TIL. Thank you.
