### ISSUE TITLE
Bitcoin failed to build with error MSB3073 on MSVC

### ISSUE THREAD

**Issue by fangzhouxia** [bitcoin/bitcoin#26324]
**Expected behavior**
Build successfully.

**Actual behavior**
Hi all,
Bitcoin fails to build on MSVC due to error MSB3073, the same problem also appeared in vs2019, I mentioned a same issue but it was closed. Could you help look?

**error message**
23>F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj(161,5): error MSB3073: The command "C:\Qt_static\bin\moc.exe  "..\..\src\qt\bitcoinamountfield.cpp" -o .\QtGeneratedFiles\qt\bitcoinamountfield.moc" exited with code 3.
23>Done Building Project "F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj" (Rebuild target(s)) -- FAILED.
**detail log**
[build (27).log](https://github.com/bitcoin/bitcoin/files/9798888/build.27.log)

**To reproduce**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 
2. git clone https://github.com/bitcoin/bitcoin F:\bitcoin\bitcoin 
3. cd F:\bitcoin\bitcoin\build_msvc  
4. py -3 msvc-autogen.py
5. cd F:\bitcoin
6.  mkdir tools\vcpkg
7.  git clone https://github.com/microsoft/vcpkg F:\bitcoin\tools\vcpkg
8. cd F:\bitcoin\tools\vcpkg
9. bootstrap-vcpkg.bat 2>&1
10. set path=%cd%;%path%
11. vcpkg integrate install 2>&1
12. cd F:\bitcoin\bitcoin\build_msvc
13. msbuild /m /p:Platform=x64 /p:Configuration=Release bitcoin.sln /t:Rebuild 2>&1

**System information**
VS version: VS2022(17.3.6)
Operating system: windows server 2019
the commit of Bitcoin we use is 5174a13

**Comment by hebasto** [comment]
Also it would be useful to see a log after building with the `-verbosity:diag` command-line switch.

**Comment by fangzhouxia** [comment]
After taking the above method, this error still exists.
![image](https://user-images.githubusercontent.com/109721669/196848185-a179a11c-a6ea-4549-a50d-fdc0376552e2.png)

**Comment by hebasto** [comment]
@fangzhouxia 

Mind posting some logs, not only errors?

Mind providing more details, in particular mentioned in https://github.com/bitcoin/bitcoin/issues/26324#issuecomment-1280659909?

Our CI follows https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md, and builds Windows binaries just fine. So my guess is the problem is with your building environment. I doubt if we can help with no or little details which could at least help us to reproduce the issue.

**Comment by fangzhouxia** [comment]
Below are my steps to reproduce:
1. Open VS2022 x64 Native Tools command.
2. git clone https://github.com/bitcoin/bitcoin F:\bitcoin\bitcoin
3. cd F:\bitcoin\bitcoin\build_msvc
4. py -3 msvc-autogen.py
5. cd F:\bitcoin
6. mkdir tools\vcpkg
7. git clone https://github.com/microsoft/vcpkg F:\bitcoin\tools\vcpkg
8. cd F:\bitcoin\tools\vcpkg
9. bootstrap-vcpkg.bat 
10. set path=%cd%;%path%
11. vcpkg integrate install 
12. cd F:\bitcoin\bitcoin\build_msvc
13. msbuild /m /p:Platform=x64 /p:Configuration=Release bitcoin.sln /t:Rebuild

**Comment by hebasto** [comment]
@fangzhouxia 
> You must ensure that Qt static library and the `bitcoin.sln` are been built with the same toolchain.

Could you try to re-build your Qt static library from scratch using VS2022?

**Comment by fanquake** [comment]
@fangzhouxia did the above work for you? Is this still an issue?
