### ISSUE TITLE
guix: unable to build powerpc64-linux-gnu host on recent time machines

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#26354]
When trying to make a guix build with a more recent Guix master branch commit, I encounter a somewhat cryptic exception. I'm able to build all the other hosts. Tried with v24.0rc2 (plus a patch to bump the time machine) as well as recent master. I tried with Guix commit 39dcbc7fa3c02ff5c9682f25e1c29667dbfe7827 (the oldest I'm able to build without substitutes) and the most recent 00ff6f7c399670a76efffb91276dea2633cc130c. I also reproduced the issue on my older Guix machine, which I've used to sign the rc2 before.

See https://github.com/bitcoin/bitcoin/pull/26351#issuecomment-1285742288 for error log. Not sure how to make it more verbose.

**Comment by fanquake** [comment]
This was already known, and doesn't need a standalone issue, it doesn't currently affect our build. If it's a blocker for #26351, which I don't think is a good idea (randomly bumping things rarely is), then it will be solved as part of that.
