### ISSUE TITLE
Need help with old wallet on software

### ISSUE THREAD

**Issue by pameladuff** [bitcoin/bitcoin#26367]
#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by pameladuff** [comment]
It’s been along time need a little help with getting back on my original wallet on the core I had to get my old computer with windows 10 because my new one has windows 11. If anyone can help I would be great Ful thanks

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
