### ISSUE TITLE
Cannot obtain a lock on data directory

### ISSUE THREAD

**Issue by zx0922** [bitcoin/bitcoin#26397]
I got error while launch bitcoin core 23.0 on macos after I set data loction on my remote NAS,
Error: Cannot obtain a lock on data directory /Volumes/Bitcoin Core Data. Bitcoin Core is probably already running.

It's still error after I reinstall. And I can not find setting file at ~/Library/Application Support/Bitcoin/

**Comment by hebasto** [comment]
> on macos after I set data loction on my remote NAS,

I doubt such a setup is supported.

**Comment by zx0922** [comment]
> > on macos after I set data loction on my remote NAS,
> 
> I doubt such a setup is supported.

yes. But I can't set a new path

**Comment by hebasto** [comment]
Try to remove the `.lock` file from your data directory.

If the problem still persists, it is related to macOS's `fctnl()` implementation, not to Bitcoin Core code.

Going to close this issue.
