### ISSUE TITLE
The “Bitcoin peers implement a reputation-based protocol” are exists?

### ISSUE THREAD

**Issue by m1crofan** [bitcoin/bitcoin#26407]
When I reading the paper 《Bitcoin over Tor isn’t a good idea》founding some introudce about Bitcoin policy for anti-Dos。

In this paper，seeing that Bitcoin peers implement a reputation-based protocol with eachnode keeping a penalty score for every other Bitcoin peer(identified by its IP address). Whenever a malformed message is sent to the node, the latter increases the penalty score of the sender and bans the “misbehaving” IP address for 24 hours when the penalty reaches the value of 100.

This paper published by 2015. I want konw it are outdated at now？

Thanks bro！

**Comment by MarcoFalke** [comment]
Misbehavior ban has been replaced by peer discouragment.

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
