### ISSUE TITLE
v22.0 wallet freezes on Mac OS Ventura on arm64

### ISSUE THREAD

**Issue by cryptodc1** [bitcoin/bitcoin#26400]
I upgraded to the newest Mac OS Ventura. The Bitcoin Core application was deleted automatically from my computer. I downloaded Bitcoin core again fro my Mac. and when I tried to open Bitcoin core it has been stuck on Verifying Wallet(s) for over an hour. 

<img width="476" alt="Screenshot 2022-10-27 at 08 39 24" src="https://user-images.githubusercontent.com/116812829/198286720-66e119e2-1c2b-453d-928c-9b4abc794240.png">

**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by cryptodc1** [comment]
M2 Chip

**Comment by cryptodc1** [comment]
[debug.log](https://github.com/bitcoin/bitcoin/files/9879775/debug.log)

**Comment by aureleoules** [comment]
> Flushing block file to disk failed. This is likely the result of an I/O error.

Do you have enough disk space?

**Comment by hebasto** [comment]
@cryptodc1 

Bitcoin Core v22.0 was built for `x86_64` architecture only, which means your macOS uses [Rosetta Translation Environment](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment) to run it on Apple silicon hardware.

Perhaps, macOS Venture somehow broke this setup.

Suggesting to use Bitcoin Core v23+ built specifically for `arm64`. For example, https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-arm64-apple-darwin.dmg

**Comment by Sjors** [comment]
Fwiw my v23.0 and v24.0rc2 installations were not touched by the upgrade.

But I've seen macOS spontaneously delete Bitcoin Core on earlier upgrades (it leaves the data directory and wallet intact).

From your log I can see that you were using v22.0 before the macOS upgrade, as well as after.

I think we can narrow the issue title down a bit, based on what @hebasto found, e.g. "v22.0 wallet freezes on Ventura on arm64"?

**Comment by hebasto** [comment]
Tbh, I doubt if it's worth to put efforts into fixing a configuration like "macOS Ventura, M2 + Rosetta + Bitcoin Core v22.0 x86_64", especially when we have release builds specifically for `arm64`.

**Comment by cryptodc1** [comment]
I just version v23 but that had the same issue
keeps saying "Verifying Wallet(s)"

**Comment by cryptodc1** [comment]
[debug-1.log](https://github.com/bitcoin/bitcoin/files/9880036/debug-1.log)

**Comment by cryptodc1** [comment]
> > Flushing block file to disk failed. This is likely the result of an I/O error.
> 
> Do you have enough disk space?

YES i do

**Comment by cryptodc1** [comment]
> @cryptodc1
> 
> Bitcoin Core v22.0 was built for `x86_64` architecture only, which means your macOS uses [Rosetta Translation Environment](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment) to run it on Apple silicon hardware.
> 
> Perhaps, macOS Venture somehow broke this setup.
> 
> Suggesting to use Bitcoin Core v23+ built specifically for `arm64`. For example, https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-arm64-apple-darwin.dmg

I just used version v23 but that had the same issue
keeps saying "Verifying Wallet(s)"

**Comment by Sjors** [comment]
@cryptodc1 can you start from a Terminal using the `-nowallet` option, to see if it's only the wallet loading that's stuck?

```sh
/Applications/Bitcoin\ Core.app/Contents/MacOS/Bitcoin-Qt -nowallet
```

**Comment by Sjors** [comment]
Note the `\ ` in the path, but maybe it's installed in a slightly different place.

**Comment by Sjors** [comment]
Odd. Try `Command + T` to open the Console window and then type: `listwalletdir`. Don't copy the result, but just let us know if it shows a list of wallets or not.

**Comment by cryptodc1** [comment]
> Odd. Try `Command + T` to open the Console window and then type: `listwalletdir`. Don't copy the result, but just let us know if it shows a list of wallets or not.
> 
> If it does, then you can load a wallet like so: `loadwallet NAME`

This is the console window that opens but does not allow me to type anywhere
<img width="940" alt="Screenshot 2022-10-27 at 10 21 19" src="https://user-images.githubusercontent.com/116812829/198312354-d060ffe9-6550-476d-afaf-b80eea27dfe4.png">

**Comment by Sjors** [comment]
Normally you can type in the bottom field next to the `>`. If that doesn't work, that's another odd bug.

**Comment by Smithbull001** [comment]
> > Odd. Try `Command + T` to open the Console window and then type: `listwalletdir`. Don't copy the result, but just let us know if it shows a list of wallets or not.
> > If it does, then you can load a wallet like so: `loadwallet NAME`
> 
> This is the console window that opens but does not allow me to type anywhere <img alt="Screenshot 2022-10-27 at 10 21 19" width="940" src="https://user-images.githubusercontent.com/116812829/198312354-d060ffe9-6550-476d-afaf-b80eea27dfe4.png">

**Comment by cryptodc1** [comment]
> > Odd. Try `Command + T` to open the Console window and then type: `listwalletdir`. Don't copy the result, but just let us know if it shows a list of wallets or not.
> > If it does, then you can load a wallet like so: `loadwallet NAME`
> 
> This is the console window that opens but does not allow me to type anywhere <img alt="Screenshot 2022-10-27 at 10 21 19" width="940" src="https://user-images.githubusercontent.com/116812829/198312354-d060ffe9-6550-476d-afaf-b80eea27dfe4.png">

It will not allow me to type in the box at all

**Comment by cryptodc1** [comment]
> Normally you can type in the bottom field next to the `>`. If that doesn't work, that's another odd bug.

yes. I tried to type there and nothing happens. There is not a flashing cursor.

**Comment by cryptodc1** [comment]
> Tbh, I doubt if it's worth to put efforts into fixing a configuration like "macOS Ventura, M2 + Rosetta + Bitcoin Core v22.0 x86_64", especially when we have release builds specifically for `arm64`.

Thank you for your assistance. However, I tried your suggestion and still no success.

**Comment by cryptodc1** [comment]
> > @cryptodc1 can you start from a Terminal using the `-nowallet` option, to see if it's only the wallet loading that's stuck?
> > ```shell
> > /Applications/Bitcoin\ Core.app/Contents/MacOS/Bitcoin-Qt -nowallet
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And if that works, try loading your wallet(s) one at a time from the "File -> Open wallet" menu. In particular, it's interesting to know if it's a Sqlite (descriptor) or BerkeleyDB (legacy) wallet that gets stuck.
> 
> FWIW, on my system (mini M1 + macOS Ventura) the path to the executable binary is as follows:
> 
> ```
> % /Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
> ```
What version of Bitcoincore are you using?
I tried to reinstall a fresh bitcoin core app on my MacBook Air M2 Ventura and after about 20 minutes  of downloading the blocks the Bitcoin core crashed saying “fatal error”. I tried several times and got the same result each time.  This happened with both V22 and V23.

**Comment by hebasto** [comment]
> What version of Bitcoincore are you using?

It is [v23.0](https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-arm64-apple-darwin.dmg) right now. Also testing [v24.0](https://bitcoincore.org/bin/bitcoin-core-24.0/test.rc2/bitcoin-24.0rc2-arm64-apple-darwin.dmg).

> I tried to reinstall a fresh bitcoin core app on my MacBook Air M2 Ventura and after about 20 minutes of downloading the blocks the Bitcoin core crashed saying “fatal error”. I tried several times and got the same result each time. This happened with both V22 and V23.

So the [issue](https://github.com/bitcoin/bitcoin/issues/26400#issue-1425571542) is not longer reproducible with a fresh installation, right?

Also just "fatal error" is not very useful to reproduce/debug an issue.

**Comment by cryptodc1** [comment]
> > What version of Bitcoincore are you using?
> 
> It is [v23.0](https://bitcoincore.org/bin/bitcoin-core-23.0/bitcoin-23.0-arm64-apple-darwin.dmg) right now. Also testing [v24.0](https://bitcoincore.org/bin/bitcoin-core-24.0/test.rc2/bitcoin-24.0rc2-arm64-apple-darwin.dmg). My hardware is mac mini M1.
> 
> > I tried to reinstall a fresh bitcoin core app on my MacBook Air M2 Ventura and after about 20 minutes of downloading the blocks the Bitcoin core crashed saying “fatal error”. I tried several times and got the same result each time. This happened with both V22 and V23.
> 
> So the [issue](https://github.com/bitcoin/bitcoin/issues/26400#issue-1425571542) is not longer reproducible with a fresh installation, right?
> 
> Also just "fatal error" is not very useful to reproduce/debug an issue.

I can reproduce it when I use the external Drive that has Bitcoin core on it. It has for both V22 and V23. 
However I was trying to do a fresh install on a new external drive and I get the "fatal error". I will upload the debug log when I get back home. 
thank you for your help in this matter.

**Comment by hebasto** [comment]
> I can reproduce it when I use the external Drive that has Bitcoin core on it.

Using external drives is not a configuration which is extensively tested and guaranteed to work in all circumstances. For example, https://github.com/bitcoin/bitcoin/issues/26397#issuecomment-1292300303.

Please try to reproduce the issue while using local drives only. You could use pruning to limit block storage space.

**Comment by cryptodc1** [comment]
> > I can reproduce it when I use the external Drive that has Bitcoin core on it.
> 
> Using external drives is not a configuration which is extensively tested and guaranteed to work in all circumstances. For example, [#26397 (comment)](https://github.com/bitcoin/bitcoin/issues/26397#issuecomment-1292300303).
> 
> Please try to reproduce the issue while using local drives only. You could use pruning to limit block storage space.

Understood. It just seems weird that i have been using this configuration for years and now with the upgrade to Mac OS Ventura this all happened.

**Comment by hebasto** [comment]
> Understood. It just seems weird that i have been using this configuration for years and now with the upgrade to Mac OS Ventura this all happened.

Going to close this issue for now.
