### ISSUE TITLE
`prevector` is basically doing UB if on C++17

### ISSUE THREAD

**Issue by cculianu** [bitcoin/bitcoin#26427]
Things like this are technically UB in C++17: https://github.com/bitcoin/bitcoin/blob/4766cd198172225c66a0adb01f6cb9513c3d0e66/src/prevector.h#L187

- You cannot start the lifetime of an array like this. You need to do some compiler magic (such as perhaps call `std::launder`? Or actually some weird placement-new that does nothing?) here to properly start the lifetime of the `T` array object, as far as the C++ abstract machine is concerned.  See: https://www.youtube.com/watch?v=pbkQG09grFw
  -  C++20 does *now* allows this -- implicit lifetimes can be started when you use some backing store in this way for trivial types only, but in C++17 this is technically UB.
  - The fact that this works is a happy accident because most major compiler support such (mis)-use of the language for trivial types owing to its C roots. So much so that they actually changed the standard for C++20 to support this, but for '17 this is UB (but works in practice on all major compilers).  
- The following is not fixed in C++20 though: Memory is not guaranteed to be aligned to whatever T requires here. (This is not fixed by C++20 -- unaligned access is UB, even if it happens to work on your platform). So `prevector` only really works without UB for `uint8_t` and similar types, if on C++20.

**Comment by MarcoFalke** [comment]
My guess would be that is already fixed in 07cb4dee5d12657e9cf33c442678e9a1cd2cec4a

**Comment by cculianu** [comment]
Yeah that should do it.  I closed this because actually the C++ spec is confusing on this. I thought more was UB but yes it should be enough to check if trivial.  And yes, removing that branch that does nothing is a good idea in https://github.com/bitcoin/bitcoin/commit/07cb4dee5d12657e9cf33c442678e9a1cd2cec4a
