### ISSUE TITLE
Unable to cross compile Zeromq Dependency for arm64-apple-darwin

### ISSUE THREAD

**Issue by BlockMechanic** [bitcoin/bitcoin#26420]
Trying to compile starting with dependencies fails with 

checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `arm64-apple-darwin': machine `arm64-apple' not recognized
configure: error: /bin/bash config/config.sub arm64-apple-darwin failed

**Expected behavior**

**Actual behavior**

checking for arm64-apple-darwin-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for xmlto... no
checking for asciidoc... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `arm64-apple-darwin': machine `arm64-apple' not recognized
configure: error: /bin/bash config/config.sub arm64-apple-darwin failed
make: *** [funcs.mk:289: /home/bitcoin/Downloads/bitcoin-master/depends/work/build/arm64-apple-darwin/zeromq/4.3.4-0f6f30942e0/./.stamp_configured] Error 1

**To reproduce**

command : make HOST=arm64-apple-darwin -j 8

**System information**

Master Branch
Ubuntu 20.04 
Core i5 intel 16GB RAM

**Comment by fanquake** [comment]
Depends has it's own config.guess and config.sub, that does recognise `arm64-apple-darwin` (which it converts to `aarch64-apple-darwin`), which we [copy and use](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/zeromq.mk#L24) when building zeromq. I can't recreate your issue using the details you've provided, so you'll have to provide more information.

**Comment by BlockMechanic** [comment]
Not sure what other info i can possibly provide. I just cloned the git, go into depends and run 

``` make HOST=arm64-apple-darwin ```

With the optional -j 8 for number of threads to use.

**Comment by fanquake** [comment]
> Not sure what other info i can possibly provide.

I see the problem now. I couldn't recreate before, because I needed to use a slightly older verison of Ubuntu. Should be fixed by #26421.

**Comment by BlockMechanic** [comment]
Awesome, thank you !

**Comment by BlockMechanic** [comment]
Thank you. Finally. Depends built OK, but now running ``` CONFIG_SITE=$PWD/depends/arm64-apple-darwin/share/config.site ./configure ``` fails with 

```
configure: loading site script /home/bitcoin/Downloads/bitcoin-master/depends/arm64-apple-darwin/share/config.site
checking for arm64-apple-darwin-pkg-config... /usr/bin/pkg-config --static
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `arm64-apple-darwin': machine `arm64-apple' not recognized
configure: error: /bin/bash build-aux/config.sub arm64-apple-darwin failed
make: *** No targets specified and no makefile found.  Stop.

```

**Comment by hebasto** [comment]
> I looked at the generated config.guess and config.sub in build-aux , they seem dated. Replacing them worked.

Fixed in #26422.

**Comment by ShoelessTom** [comment]
is it fixed tho? the  issue is still present 4 me, mine need to update some files

**Comment by luke-jr** [comment]
Seems like a distro bug. I'm not sure it makes sense to try too hard to workaround those, especially for something like cross compiling where it makes more sense to just say "use a non-broken distro"...?

**Comment by hebasto** [comment]
> Seems like a distro bug.

Is age a bug?

**Comment by luke-jr** [comment]
Or absence of a feature, if you prefer.

(But failing for no reason because of an unknown platform seems like a bug IMO.)
