### ISSUE TITLE
getblockchaininfo.verificationprogress never reaching 1.0

### ISSUE THREAD

**Issue by sander2** [bitcoin/bitcoin#26433]
**Expected behavior**

`getblockchaininfo.verificationprogress` is 1.0 when it is done syncing

**Actual behavior**

The highest value that `getblockchaininfo.verificationprogress` gets to is something like `0.9999976273867589`. As a result, we can not rely on this value to determine if syncing is complete. We can not rely on `getblockchaininfo.initialblockdownload` either due to https://github.com/bitcoin/bitcoin/issues/26432

**To reproduce**

Call `getblockchaininfo` on a synced node and observe that `verificationprogress` is < 1.0. 

**System information**

Version 22 of the bitcoin core binary, downloaded from the website

**Comment by MarcoFalke** [comment]
As per the documentation, the field is only an estimate. The guess will take into account the duration since the timepoint of your tip block and the estimate of the rate of transactions.

Maybe you are better off crafting your own estimate, based on your needs?

**Comment by sander2** [comment]
> As per the documentation, the field is only an estimate. The guess will take into account the duration since the timepoint of your tip block and the estimate of the rate of transactions.
> 
> Maybe you are better off crafting your own estimate, based on your needs?

Hmm that's not very useful then for our needs. After some googling, I found https://bitcoin.stackexchange.com/questions/96452/how-to-detect-that-full-node-is-in-sync-using-jsonrpc . Can you confirm that if `getblockchaininfo.headers` is equal to `getblockchaininfo.blocks`, the sync is complete?

**Comment by MarcoFalke** [comment]
Again, it might be better if you stated your problem/use-case and designed a estimate function for your problem/use-case. It is not possible to design a "sync" function without knowing what is should do.

Note, usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.

**Comment by MarcoFalke** [comment]
Closing for now. Let us know if you have any other questions.
