### ISSUE TITLE
Add ability to ignore `SCRIPT_VERIFY_DISCOURAGE_x` flags when broadcasting transactions on test networks.

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#26439]
After bugs like: https://github.com/btcsuite/btcd/issues/1906 it would be useful to be able to reproduce these bugs in regtest. Currently to do so you would need to manually edit the code and comment out the script flag, then compile your self. It would be beneficial if we could disable these flags to create more reproducible tests.

**Comment by MarcoFalke** [comment]
This should be trivial to reproduce on regtest by simply generating a block with the transaction.

Unrelated to your question, I think it would be beneficial if there was a direct (non-p2p) interface for devs to send nonstandard transactions to a miner on signet. Signet intentionally uses a policy similar to the one on mainnet, however, this also makes it hard to test regtest-y tests on signet.

**Comment by benthecarman** [comment]
> This should be trivial to reproduce on regtest by simply generating a block with the transaction

My understanding the main way to do this is to is broadcast it, then call generatetoaddress. Is there another way?

**Comment by MarcoFalke** [comment]
`generateblock`

**Comment by MarcoFalke** [comment]
cc @ajtowns Any thoughts about my signet question?

**Comment by ajtowns** [comment]
> Unrelated to your question, I think it would be beneficial if there was a direct (non-p2p) interface for devs to send nonstandard transactions to a miner on signet. Signet intentionally uses a policy similar to the one on mainnet, however, this also makes it hard to test regtest-y tests on signet.

I think for custom signets, contrib/signet/miner should definitely allow specifying transactions manually.

For the global signet, I've seen people say they want it to be reliable for integration testing -- so, eg, having it include txs that would break btcd which breaks lnd which then stops them from being able to test the software they're building on top of lnd until a fix is rolled out would be annoyingly disruptive (albeit not as annoying as it happening on mainnet). Not sure what a good approach is -- maybe something like "mine proposed non-standard txs in a secret closed network that includes btcd, rust-bitcoin, etc; if any of those nodes lose sync or crash, raise it as a security issue with those devs; only mine the proposed tx on signet proper if nothing crashes" ? Probably better discussed on the list or somewhere than here though.
