### ISSUE TITLE
[MSVC] Bitcoin build failed due to bitcoin\src\fs.h(75,39): error C2039: 'u8string': is not a member of 'std' with msvc option /c++latest

### ISSUE THREAD

**Issue by Zhaojun-Liu** [bitcoin/bitcoin#26444]
Recently, we updated the commit of bitcoin for MSVC RWC testing, it failed to build due to the error like below with option /c++latest, could you please help take a look? Thanks.
```
bitcoin\src\fs.h(75,39): error C2039: 'u8string': is not a member of 'std' [F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\filesystem(39,1): message : see declaration of 'std' [F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj]
```

**Expected behavior**

Build successfully.

**Actual behavior**

```
bitcoin\src\fs.h(75,39): error C2039: 'u8string': is not a member of 'std' [F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\filesystem(39,1): message : see declaration of 'std' [F:\gitP\bitcoin\bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj]
```
**To reproduce**

1. git clone https://github.com/bitcoin/bitcoin F:\gitP\bitcoin\bitcoin
2. git -C "F:\gitP\bitcoin\bitcoin" fetch --recurse-submodules=no --force
3. git -C "F:\gitP\bitcoin\bitcoin" reset --hard 43e813cab266eef42e622519836f171f6a18d426
4. set _CL_= /std:c++latest 
5. cd F:\gitP\bitcoin\bitcoin\build_msvc
6. py -3 msvc-autogen.py
7. set _CL_=%_CL_% /D_HAS_DEPRECATED_ALLOCATOR_MEMBERS /D_SILENCE_CXX20_U8PATH_DEPRECATION_WARNING /Zc:char8_t- /D_SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING
8. set the vcpkg info and run `bootstrap-vcpkg.bat` and` vcpkg integrate install`, in my environment, as follows:
    cd F:\gitP\bitcoin\tools\vcpkg
    git -C "F:\gitP\bitcoin\tools\vcpkg" clean -xdf 
    bootstrap-vcpkg.bat 
    set path=%cd%;%path%
    vcpkg integrate install 
9. switch to the directory: cd F:\gitP\bitcoin\bitcoin\build_msvc
10. msbuild /m /p:Platform=x64 /p:Configuration=Release /p:PlatformToolset=v142 bitcoin.sln /t:Rebuild

**System information**

the commit of Bitcoin: 43e813cab266eef42e622519836f171f6a18d426

OS: Windows Server 2022 Datacenter 21H2

Detailed log: 
[build.log](https://github.com/bitcoin/bitcoin/files/9917851/build.log)

**Comment by MarcoFalke** [comment]
The only supported option right now is C++20, which is already set in https://github.com/bitcoin/bitcoin/blob/39f026b1ec17ef8100457ef46a1e4980767c0fe2/build_msvc/common.init.vcxproj.in#L90

**Comment by MarcoFalke** [comment]
Closing for now. Let us know if you have any other questions.

**Comment by Zhaojun-Liu** [comment]
@MarcoFalke You mean that bitcoin doesn't support /c++latest, right?

**Comment by hebasto** [comment]
> Detailed log:
> [build.log](https://github.com/bitcoin/bitcoin/files/9917851/build.log)

> ** Visual Studio 2019 Developer Command Prompt v16.11.20

From https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md:
> Visual Studio 2022 is minimum required to build Bitcoin Core.

**Comment by MarcoFalke** [comment]
> @MarcoFalke You mean that bitcoin doesn't support /c++latest, right?

It may happen to work, but the only supported C++ version is the one listed in ` build_msvc/common.init.vcxproj.in `

**Comment by Zhaojun-Liu** [comment]
@MarcoFalke Ok, I got it. Thanks for the reply.

**Comment by Zhaojun-Liu** [comment]
@hebasto I noticed that your reply in other issues mentioned that Visual Studio 2022 is minimum required to build Bitcoin Core. In fact, although we are using VS2019, we will use the latest build of msvc to replace the corresponding msvc related files in the vs path before build the code. We will upgrade VS recently, and I will try to build under vs2022 at then, if there are still problems, I will ask for help here again. Thank you for your reply.

**Comment by Zhaojun-Liu** [comment]
> 

Ok, I got it.

**Comment by Zhaojun-Liu** [comment]
> > We will upgrade VS recently, and I will try to build under vs2022 at then
> 
> To avoid linker errors, please ensure that dependencies are also built with VS 2022, including Qt stuff.

Ok, I got it.
