### ISSUE TITLE
Flushing block file to disk failed when using external drive on macOS Ventura

### ISSUE THREAD

**Issue by aureliusltd** [bitcoin/bitcoin#26455]
I kept getting an error regarding Flushing Block to disk. I've tried to use bitcoin core V0.23 and it doesn't help; although V0.22 was better at loading the backup file, but I couldn't send any of my bitcoin out. I can't seem to load the wallet or the backup file properly. Not a coder and hoping someone can help. I don't think it's an issue with the hard drive. Any suggestion? I'm on MacOSx Ventura 13.0. 

Debug.log file:

2022-11-04T20:34:28Z Using wallet /Volumes/Extreme SSD/bruceltd wallet.dat
2022-11-04T20:34:28Z BerkeleyEnvironment::Open: LogDir=/Volumes/Extreme SSD/database ErrorFile=/Volumes/Extreme SSD/db.log
.
.
.
2022-11-04T20:58:16Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-04T20:58:16Z ERROR: SerializeFileDB: Failed to flush file /Volumes/Extreme SSD/peers.176f

db.log file:
fsync: Inappropriate ioctl for device
PANIC: Inappropriate ioctl for device
txn_checkpoint: failed to flush the buffer cache: DB_RUNRECOVERY: Fatal error, run database recovery

**Comment by brl4n** [comment]
also getting similar internal errors for the past few days. MacOS DiskUtility doesn't report any problems. No other apps are having file IO issues. Tried v24.0.0rc3 and same issue. Able to check blocks for a few minutes then crashes.


Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0100000100000012 -> 0x0000000100000012 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x0100000100000012

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [37021]

VM Region Info: 0x100000012 is not in any region.  Bytes before following region: 15368174
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100ea8000-10282c000    [ 25.5M] r-x/r-x SM=COW  ...OS/Bitcoin-Qt

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage

**Comment by aureliusltd** [comment]
Update on the issue. The current Bitcoin Core software, V0.22 & V0.23, are not working well with the new Mac Software update 13.0 Ventura. I went back to the previous version, Monterey 12.6, and the software works just fine. How can i help to make the new bitcoin core version, V0.24, more compatible with Mac? Thank you!

**Comment by hebasto** [comment]
> Update on the issue. The current Bitcoin Core software, V0.22 & V0.23, are not working well with the new Mac Software update 13.0 Ventura.

Looks similar to #26400.

https://github.com/bitcoin/bitcoin/issues/26400#issuecomment-1294866176:

> Using external drives is not a configuration which is extensively tested and guaranteed to work in all circumstances. For example, https://github.com/bitcoin/bitcoin/issues/26397#issuecomment-1292300303.
>
> Please try to reproduce the issue while using local drives only. You could use pruning to limit block storage space.

**Comment by hebasto** [comment]
@aureliusltd @mateusgalasso

What are filesystems on your external drives?

**Comment by mateusgalasso** [comment]
> @aureliusltd @mateusgalasso
> 
> What are filesystems on your external drives?

ExFAT

**Comment by john-moffett** [comment]
It looks like other projects ([LevelDB](https://github.com/google/leveldb/commit/296de8d5b8e4e57bd1e46c981114dfbe58a8c4fa), [SQLite](https://sqlite.org/src/file?name=src/os_unix.c&ci=5c669f5f399fe899#:~:text=If%20the%20FULLFSYNC%20failed%2C%20fall%20back%20to%20attempting%20an%20fsync()), etc.) have had similar issues with `fcntl` using `F_FULLFSYNC`. Apparently there are certain external drives / filesystems that don't support it, so they return an error. I can only speculate why it seems to be only showing up on macOS Ventura. 

Those projects have all used the same strategy: fallback to `fsync` on error (see previous links or this [helpful twitter thread](https://twitter.com/TigerBeetleDB/status/1422855270716293123)). It seems like the error is specifically `ENOTTY` in this case, so we could check for that and try `fsync`.

I've created a branch that does that. Happy to submit as a PR if this approach seems sound.

https://github.com/john-moffett/bitcoin/blob/d99a8bee66656d29017b42fb2c0935de768ccd70/src/util/system.cpp#L1187-L1200

**Comment by hebasto** [comment]
> I've created a branch that does that. Happy to submit as a PR if this approach seems sound.

A well motivated PR is better than a comment in an issue :)

**Comment by hebasto** [comment]
Apparently, it is an macOS 13 issue. Upgrading to 13.1 should fix it:
- https://github.com/bitcoin/bitcoin/pull/26534#issuecomment-1331409133
- https://github.com/bitcoin/bitcoin/pull/26534#issuecomment-1331470901

Close?

**Comment by mateusgalasso** [comment]
> Apparently, it is an macOS 13 issue. Upgrading to 13.1 should fix it:
> 
> * [Fix macOS failing to flush blockfiles to disk for certain external drives #26534 (comment)](https://github.com/bitcoin/bitcoin/pull/26534#issuecomment-1331409133)
> * [Fix macOS failing to flush blockfiles to disk for certain external drives #26534 (comment)](https://github.com/bitcoin/bitcoin/pull/26534#issuecomment-1331470901)
> 
> Close?

There is no 13.1
<img width="240" alt="image" src="https://user-images.githubusercontent.com/3990028/204834882-15e8bb41-a2f4-496d-86f0-b5497353eeb6.png">

**Comment by john-moffett** [comment]
13.1 is available as a public beta: https://beta.apple.com/sp/betaprogram/welcome

**Comment by asylejmani** [comment]
I can confirm it works in 13.1! Had v24.0.0 running all night without any issues.
