### ISSUE TITLE
[wallet] when unloading a wallet which still rescans the wallet, the command should fail but bitcoind gets in a buggy state

### ISSUE THREAD

**Issue by ziggie1984** [bitcoin/bitcoin#26463]
I am loading descriptors into bitcoind using the rpcclient with the function: `importdescriptors`, it automatically starts rescanning the blockchain. Now when I try to unload the wallet, bitcoin-cli will allow me to do it (wallet disappears from the `listwallet` section, but it will not abort the rescan. Thats a problem bc now when trying to reload the wallet, the wallet sqlite db is locked by bitcoind and this wallet is unusable unitl the rescan is over. `abortrescan` will not work bc the wallet is not loaded anymore according to `bitcoin-cli listwallets`. The only solution for me was to delete the wallet dir and create a new wallet with the same name. Now everything works as expected, but as soon as I want to unload the wallet again, bitcoind crashes

The `unloadwallet` function should internally abort the rescan and unload the wallet, so that it can be reloaded afterwards without waiting for the rescan. Or it should fail and leading the user to abort the rescan with `abortrescan`

* Create a descriptor wallet
* Import a descriptor and unload the walllet while bitcoind is still rescanning
* Now you are stuck bc abortrescan will not work bc wallet is not loaded and the only solution is to delete the wallet dir
* Now Create a new wallet with the same name and import the descriptors again. When the wallet is faster synced then the old process still syncing, and you unload the wallet, bitcoind crashes

` Linux 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux`

bitcoind v.23.0 (release binary for raspberry pi)

**Comment by ziggie1984** [comment]
@achow101 maybe it works as expected, but according to my feeling `unloadwallet` should not do anything before the user did not abort the rescan

**Comment by promag** [comment]
> I am loading descriptors into bitcoind using the rpcclient with the function: importdescriptors, it automatically starts rescanning the blockchain. Now when I try to unload the wallet,

you interrupted `bitcoin-cli` right?

> The unloadwallet function should internally abort the rescan and unload the wallet, so that it can be reloaded afterwards without waiting for the rescan. Or it should fail and leading the user to abort the rescan with abortrescan

IMO it should just fail.

**Comment by ziggie1984** [comment]
Yes and Yes.

Yes I think we maybe should just fail as long as the wallet in rescanning. Otherwise the is no option to escape and the `unloadwallet` command is not recoverable. So definitely on your side.
