### ISSUE TITLE
Release schedule for 25.0

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#26549]
Here is a proposed release schedule for 25.0, the next major release of Bitcoin Core. I've aimed for a release *7* months [1] after the (planned) release of the last (#24987).

[1] Usually it would be 6 months, but due to delays in the previous release, there is one additional month this time.

## 2023-03-01 :heavy_check_mark:    
- Open Transifex translations for 25.0
- Soft translation string freeze (no large or non-critical string changes until release)
- Finalize and close translations for 23.0

## 2023-04-01 :heavy_check_mark:
- Feature freeze (bug fixes only until release)
- Translation string freeze (no more source language changes until release)

## 2023-04-14 :heavy_check_mark:
- Anything needed before branch-off, see https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md
- Split off `25.x` branch from `master`
- Start RC cycle, tag and release `25.0rc1`
- Start merging for `26.x` on `master` branch

## 2023-05-15 :construction: 
- Release 25.0 (aim)

If any specific dates are a problem for you, please leave a comment.

**Comment by GregTonoski** [comment]
What is the "23.0" in the sentence: "Finalize and close translations for 23.0"? Isn't it a typo, perhaps?

**Comment by hebasto** [comment]
> ## 2023-03-01 construction
> 
>    - Open Transifex translations for 25.0

See #27169.

---

@GregTonoski 
> What is the "23.0" in the sentence: "Finalize and close translations for 23.0"? Isn't it a typo, perhaps?

That's correct. See https://www.transifex.com/bitcoin/bitcoin/content/.

**Comment by hebasto** [comment]
> ## 2023-03-01 construction
> 
>    * Open Transifex translations for 25.0
> 
>    * Soft translation string freeze (no large or non-critical string changes until release)
> 
>    * Finalize and close translations for 23.0

Done. See an [announcement](https://www.transifex.com/bitcoin/communication/d:ef30e8c2-e635-4ad7-b899-b723c6394011/?q=project%3Abitcoin) on the Transifex website (one needs to log in Transifex to read it).

**Comment by donatocayurin** [comment]
https://github.com/bitcoin/bitcoin/pull/27223

**Comment by donatocayurin** [comment]
❤️🙏

**Comment by izlan90** [comment]
What hepn


Pada Ahd, 12 Mac 2023 11:22 PG donatocayurin ***@***.***>
menulis:

**Comment by hebasto** [comment]
> ## 2023-04-01 :construction:
> 
>    * Translation string freeze (no more source language changes until release)

See https://github.com/bitcoin-core/gui/pull/724.

**Comment by fanquake** [comment]
25.x has now been branched off: https://github.com/bitcoin/bitcoin/tree/25.x.

**Comment by fanquake** [comment]
> Start RC cycle, tag and release 25.0rc1

`rc1` binarie are now available: https://bitcoincore.org/bin/bitcoin-core-25.0/test.rc1/.

**Comment by hebasto** [comment]
[Here](https://github.com/bitcoin/bitcoin/issues/27621) is an umbrella issue for 25.0 testing.

**Comment by fanquake** [comment]
`rc2` binaries are available: https://bitcoincore.org/bin/bitcoin-core-25.0/test.rc2/.

**Comment by fanquake** [comment]
`v25.0` has been tagged: https://github.com/bitcoin/bitcoin/releases/tag/v25.0.
