### ISSUE TITLE
Include estimated time to synchronize blockchain in bitcoind

### ISSUE THREAD

**Issue by araujo88** [bitcoin/bitcoin#26540]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, the estimated time to synchronize to the Bitcoin blockchain is only shown in the Qt GUI. It would be useful to display the estimated remaining time to synchronize to the blockchain via the Bitcoin daemon's logs as well.

**Describe alternatives you've considered**
Display estimated time in the Bitcoin daemon synchronizing logs.

**Comment by GodLovesme324** [comment]
Kindly contact the Support team to fix the issue below is their livechat link https://direct.lc.chat/14756535/

**Comment by 1440000bytes** [comment]
It should be removed from `bitcoin-qt` because it is misleading most of the time with [current logic](https://github.com/bitcoin/bitcoin/blob/d0b1f613c2a20b2de2878be2de19f827347dcc24/src/qt/modaloverlay.cpp#L110)

**Comment by araujo88** [comment]
> It should be removed from `bitcoin-qt` because it is misleading most of the time with [current logic](https://github.com/bitcoin/bitcoin/blob/d0b1f613c2a20b2de2878be2de19f827347dcc24/src/qt/modaloverlay.cpp#L110)

Instead of removing, shouldn't it be improved? It is useful information.

**Comment by 1440000bytes** [comment]
> > It should be removed from `bitcoin-qt` because it is misleading most of the time with [current logic](https://github.com/bitcoin/bitcoin/blob/d0b1f613c2a20b2de2878be2de19f827347dcc24/src/qt/modaloverlay.cpp#L110)
> 
> Instead of removing, shouldn't it be improved? It is useful information.

Yes it could be improved. I couldn't find anything helpful last I tried. 

Even if there is a better logic it will be difficult to change in `bitcoin-qt` and then include in `bitcoind` considering the review process. Estimations do not work properly in bitcoin core in lot of things. Example: Fee estimation and users just switch to [alternatives](https://nitter.net/dannydiekroeger/status/1593616752721948672)

**Comment by pinheadmz** [comment]
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.
