### ISSUE TITLE
Keep seed phrase/mnemonic on cold encrypted

### ISSUE THREAD

**Issue by cryptoplatz-vault** [bitcoin/bitcoin#26550]
**Is your feature request related to a problem? Please describe.**

It is not safe to keep the seed phrase or private keys on the computer or smartphones. 

**Describe the solution you'd like**

Need to have an option to user save the seed phrase or private keys encripted on NFC Card or USB device, like a cold wallet integrated with Bitcoin core.

So every time user wants to withdraw Bitcoin, need to have the USB "pendrive" connected on PC or tap the NFC Card.

**Describe alternatives you've considered**

I have checked and there is another wallets using this solution.

**Additional context**

I already have this working without integration with Bitcoin Core.

**Comment by kouloumos** [comment]
The [Bitcoin Hardware Wallet Interface (HWI)](https://github.com/bitcoin-core/HWI) can be used to interact with hardware wallets and in that repository you will also [find a guide](https://github.com/bitcoin-core/HWI#using-with-bitcoin-core) on using Bitcoin Core with the supported hardware wallets.

AFAIK there is no support for NFC cards, you can see [here](https://hwi.readthedocs.io/en/latest/devices/index.html#support-matrix) the supported devices.

**Comment by cryptoplatz-vault** [comment]
Thank you! How to add our device CryptoPlatz Vault to the supported devices?

**Comment by cryptoplatz-vault** [comment]
Thank you! CryptoPlatz Vault is open source too. If someone that reads this comment, wants to help the project, is opened!
