### ISSUE TITLE
[meta] Distinguish concept/wip/review/rfm for active/high-priority PRs?

### ISSUE THREAD

**Issue by ajtowns** [bitcoin/bitcoin#26556]
What do people think of more clearly distinguishing [high-priority PRs](https://github.com/orgs/bitcoin/projects/1/views/1) into different phases? Perhaps something like:

 * concept: here's a rough draft, what do people think? looking for concept acks, or different approaches
 * wip: here's something the author thinks works; please try it out. the author's happy to make major changes to the PR, fix nits, etc.
 * final: this is pretty well baked. now is the time for final review; anything that's not a bug fix will go in a followup PR so as not to invalidate ACKs. everything on here is an implicit review beg!
 * rfm: this is (hopefully) ready for merge -- all the questions/complaints have been addressed (either directly or deferred to a followup pr), and there's been some meaningful review resulting in acks. should just be up to maintainers to check everything looks sensible, and either merge it, or bump it back to review with some explanation as to what's up

I think we could track those states via the new "projects" -- I've setup a quick demo at https://github.com/users/ajtowns/projects/2/views/1 . I've added a couple of views that seem like they'd be helpful: one for "RFM" PRs (helpful for maintainers?) and one so you can see the PRs that you personally haven't reviewed, split up by whether they're wip/final.

I believe we could make it pretty low effort:

 * can setup permissions so anyone who's an frequent contributor can add/move PRs themselves, so tweaking it doesn't need to be limited to maintainers
 * can use the default workflows so that PRs that get closed automatically get removed from the project, and set it up to automatically move PRs out of "rfm" if a "changes requested" review comes in. could presumably setup even cleverer workflows via actions or drahtbot or similar too.

:+1:/:-1:/?

**Comment by dergoegge** [comment]
Concept ACK

I don't see a downside to this as long as it isn't an additional burden on the maintainers (as you said frequent contributors would be able to maintain), so I think we could just add this experimentally and see if it takes off. We can always remove the board later on if it isn't utilized.

I wouldn't be surprised if this ends up in a similar state as the current high-prio board (i.e. a bit under utilized). The "problem" doesn't seem to be the visibility of (high-prio) PRs to review but rather that contributors follow their own interest in choosing what to review. The new board you are suggesting might solve this dilemma as it's not on the maintainers to maintain it and contributors can curate it with all the high-prio PRs they find interesting.

Is there a way to change the ordering on these boards? For example, ordering by "how long has this been open" or "most recently active" would seem more useful than letting contributors pick the order.

**Comment by amitiuttarwar** [comment]
concept ACK. I regularly look at recent activity on the repo & really like the view that "my unreviewed" gives. I also think having a similar (but opposite) "my reviews" tab could be helpful for keeping track of those long-tail PRs you've previously reviewed, where authors are trying to get more attention. 

one question I have is around how PRs are added to the high priority set. if it's up to individuals to add & remove from the board, I wonder how populated it would get. it'd be cool if there was some programatic way to maintain, and some of this seems viable (eg. making sure PRs that need rebase aren't on there). however, there's no programatic way to identify which PRs are more significant in the author's POV, so individual contributors adding their own PRs might be a requirement. 

> I don't see a downside to this as long as it isn't an additional burden on the maintainers (as you said frequent contributors would be able to maintain), so I think we could just add this experimentally and see if it takes off. We can always remove the board later on if it isn't utilized.

generally agreed, seems worth a try to see if the community ends up using it & getting value.

**Comment by willcl-ark** [comment]
Closing as completed. Feel free to comment if incorrect.
