### ISSUE TITLE
`28E72909F1717FE9607754F8A7BEB2621678D37D` key not specified in builder keys and `24.0` release signed with it

### ISSUE THREAD

**Issue by scgbckbone** [bitcoin/bitcoin#26566]
I would expect each key that signs new release to be included in `contrib/builder-keys/keys.txt` - am I wrong? `24.0` is signed with `28E72909F1717FE9607754F8A7BEB2621678D37D` <vertion@protonmail.com> but this key is not included in `keys.txt`.

If above is not true, where does one find all the keys that sign new releases ?

**Comment by willcl-ark** [comment]
@scgbckbone anybody can sign new builds using the Guix build system. If you sign 3 or more releases then you can open a PR to have your key added to `builder-keys/keys.txt`.

You can find "missing" keys on keyservers, e.g. [openpgp](https://keys.openpgp.org/search?q=28E72909F1717FE9607754F8A7BEB2621678D37D) or [ubuntu](keyserver.ubuntu.com).

**Comment by MarcoFalke** [comment]
It is not required to find *all* keys. Only the keys of the people you (want to) trust.

**Comment by scgbckbone** [comment]
thanks for your answers!
