### ISSUE TITLE
builder-keys: unable to find A2FD494D0021AA9B4FA58F759102B7AE654A4A5A

### ISSUE THREAD

**Issue by RandyMcMillan** [bitcoin/bitcoin#26563]
https://github.com/bitcoin/bitcoin/blob/38d06e1561013f4ca845fd5ba6ffcc64de67f9c0/contrib/builder-keys/keys.txt#L25

https://github.com/bitcoin/bitcoin/commit/2b4cfb44bd75d6e51eb9e7ca692b2fa32250ad04#diff-0538084c53da5acd80bd796d75b10246d7346231643b3f4b1e136204bc829f56R21

Please post which key server this is available on.

cc: @IlyasRidhuan

**Comment by MarcoFalke** [comment]
Closing for now. Let's continue discussion in the pull request.
