### ISSUE TITLE
CJDNS doesn't resolve inbound/outbound to same addr, resulting in duplicated connections

### ISSUE THREAD

**Issue by andrewtoth** [bitcoin/bitcoin#26587]
For two peers connecting to each other over CJDNS via `addnode`, it results in 2 connections. We would expect them to determine they are connecting to each other and not duplicate the connection. `getpeerinfo` gives the following:
inbound connection - `"addr": "[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:<port>]:<random_port>",`, 
outbound connection - `"addr": "xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:<port>",`

Not sure if it would be possible to determine that the inbound connection is the same as our outbound, and don't make an outbound if requested with that same cjdns address.

**Comment by willcl-ark** [comment]
See https://github.com/bitcoin/bitcoin/issues/26537

**Comment by vasild** [comment]
`addnode` overrides the [is already connected to](https://github.com/bitcoin/bitcoin/blob/c239d3dac9ced786b41410e54243a50b7a9dc304/src/net.cpp#L406) check. Here is the same with IPv4 - I ran two nodes, one listening on `5.5.5.5:5555` and another on `6.6.6.6:6666`, then `addnode` each one to the other:

```sh
$ bitcoin-cli ... getpeerinfo |jq 'map({addr: .addr, addrlocal: .addrlocal, connection_type: .connection_type})'
[
  {
    "addr": "5.5.5.5:59064",
    "addrlocal": "5.5.5.5:5555",
    "connection_type": "inbound"
  },
  {
    "addr": "6.6.6.6:6666",
    "addrlocal": "6.6.6.6:45341",
    "connection_type": "manual"
  }
]

$ bitcoin-cli ... getpeerinfo |jq 'map({addr: .addr, addrlocal: .addrlocal, connection_type: .connection_type})'
[
  {
    "addr": "5.5.5.5:5555",
    "addrlocal": "5.5.5.5:59064",
    "connection_type": "manual"
  },
  {
    "addr": "6.6.6.6:45341",
    "addrlocal": "6.6.6.6:6666",
    "connection_type": "inbound"
  }
]
```

I think this is expected. However the following looks like a bug:

> inbound connection - `"addr": "[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:<port>]:<random_port>"`

Are you sure that there is a port inside `[]` and that it is not just part of the address?

**Comment by jonatack** [comment]
> > inbound connection - `"addr": "[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:<port>]:<random_port>"`
> 
> Are you sure that there is a port inside `[]` and that it is not just part of the address?

Perhaps the OP had a typo. For CJDNS peer addresses, I see:
- `[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:<port>` for inbound
- ` xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx` for outbound

**Comment by andrewtoth** [comment]
> Are you sure that there is a port inside [] and that it is not just part of the address?

Ahh yes tried it again and it is indeed just part of the address. Not a typo but misread. If overriding the `is already connected to check` for manual connections is expected behavior then this is not an issue.
