### ISSUE TITLE
 The BTC module is not working with the latest Magento php 8.1 version 

### ISSUE THREAD

**Issue by chiragit0007** [bitcoin/bitcoin#26608]
Hello Team,
Hope that you are doing well!
We are facing an issue with the BTC modules not working with the latest Magento PHP version 8.1. Kindly please check and let us know on this how we can use the module with PHP version 8.1. 
Looking forward to hearing from you soon. 
Thank you!

**Comment by MarcoFalke** [comment]
We don't write or ship any PHP software, so you'll need to look elsewhere for help.

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
