### ISSUE TITLE
Intermittent failure in validation_chainstatemanager unit test

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#26613]
https://cirrus-ci.com/task/4951273196224512?logs=ci#L3217

`test_bitcoin: ./chain.h:266: uint256 CBlockIndex::GetBlockHash() const: Assertion phashBlock != nullptr failed.`

Observed in #26584, but I don't see how this crash (which looks related to AssumeUTXO loading of a chainstate) could be related to the changes from that PR. 
FYI @jamesob

**Comment by pinheadmz** [comment]
@mzumsande I pushed a noop rebase to #26584 and the tests all passed

**Comment by MarcoFalke** [comment]
Not sure what to do here. Maybe it was a cosmic ray?
