### ISSUE TITLE
Removal of binaries of version 24.0 is against transaprency, security and best practices - please bring them back to Releases in the GitHub repository

### ISSUE THREAD

**Issue by GregTonoski** [bitcoin/bitcoin#26652]
Compare: 
- the current: 
![image](https://user-images.githubusercontent.com/111286121/206149326-55502831-15ba-4722-8e29-180e2fbfca8c.png)
- the former:
![image](https://user-images.githubusercontent.com/111286121/206149410-827d4bae-27e6-4663-95cf-d58c13d749d7.png)

Let's not attempt to rewrite the history, please.

**Comment by fanquake** [comment]
The release is shortly to be replaced with the 24.0.1 release. This is the same that happened with the 0.19.0 and 0.19.0.1 release. The binaries have not been *removed* in any case, as they are not actually downloadable from the GH release. The Github release only contains links to the same tagged source code (which is still available), and a pointer to bitcoincore.org, which is the only place that binaries are available for download.

**Comment by GregTonoski** [comment]
> The release is shortly to be replaced with the 24.0.1 release. This is the same that happened with the 0.19.0 and 0.19.0.1 release. The binaries have not been _removed_ in any case, as they are not actually downloadable from the GH release. The Github release only contains links to the same tagged source code (which is still available), and a pointer to bitcoincore.org, which is the only place that binaries are available for download.

Is there more confidence in superior quality of the incoming 24.0.1 over 24.0? I would guess that the incoming binaries haven't been tested enough yet they would be promoted as improvement.

**Comment by MarcoFalke** [comment]
It is always recommended to test a new binary with your code or use case before deploying it to production. It is also possible to review the changes or list them locally with `git` or on GitHub https://github.com/bitcoin/bitcoin/compare/v24.0...v24.0.1

**Comment by GregTonoski** [comment]
> The release tag was not removed, it is available and will continue to be so, see https://github.com/bitcoin/bitcoin/releases/tag/v24.0 .

There is the tag for 24.0. However, I'm reporting de-listing Bitcoin Core 24.0 in the Releases section (there isn't Bitcoin Core 24.0 unlike Bitcoin Core 23.0, 22.0 and previous ones):
![image](https://user-images.githubusercontent.com/111286121/206160757-63ab6fcc-dcce-4b25-ab9e-bb36d55eb180.png)

**Comment by fanquake** [comment]
> However, I'm reporting a different issue,

We understand what you're reporting, and have already explained why it's been removed. The existance of a GitHub release is symbolic, and it doesn't contain any content that isn't otherwise easily available, and will remain available.

This is the same process that was used for 0.19.0, and 0.19.0.1. You'll note that there is no "GitHub release" for 0.19.0, even though a [tag exists](https://github.com/bitcoin/bitcoin/releases/tag/v0.19.0), and there is only a GitHub release for 0.19.0.1.

**Comment by brijananand** [comment]
> The release is shortly to be replaced with the 24.0.1 release. This is the same that happened with the 0.19.0 and 0.19.0.1 release. The binaries have not been _removed_ in any case, as they are not actually downloadable from the GH release. The Github release only contains links to the same tagged source code (which is still available), and a pointer to bitcoincore.org, which is the only place that binaries are available for download.

Visiting https://bitcoincore.org/en/download/ lists Bitcoin Core 23.0 for download and not 24.0. I however understand that 24.0.1 is tagged and will be available soon with its binaries, wouldn't it be good to have version 24.0 listed on Bitcoincore.org's download page if not on the Github releases? Is there a way to create a request to have release 24.0 listed there for easy download and access? 

The same applies for the Blog https://bitcoincore.org/en/blog/. I am unable to currently find an entry showing an update for 24.0 'Bitcoin Core 24.0 released'. I'm not sure if this was not published or not.

After some digging I was able to find https://bitcoincore.org/bin/bitcoin-core-24.0/ where the Binaries are available thanks to my browsers history.

**Comment by MarcoFalke** [comment]
Questions about the website are handled in the website repo. You can find the current 24.0.1 pull in the website repo: https://github.com/bitcoin-core/bitcoincore.org/pull/929
