### ISSUE TITLE
Bring back the zap (zaptransaction RPC)

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#26669]
It can be useful to completely remove a transaction from a wallet rather than just abandon it. See e.g. #26667.

The original `-zapwallettxes` startup option was removed in #19671. It was perhaps overkill, but a simple `zaptransaction` RPC would be nice.

**Comment by achow101** [comment]
See `removeprunedfunds`

**Comment by Sjors** [comment]
Ah, that does the trick!
