### ISSUE TITLE
assert in chain.cpp

### ISSUE THREAD

**Issue by bartoli** [bitcoin/bitcoin#26678]
This is just a FYI that an assert has been triggered on a release build of bitcoin core 22 by a user (not me):
https://www.reddit.com/r/BitcoinBeginners/comments/zgykrj/my_second_attempt_at_setting_up_a_bitcoin_node/
This seems to be the assert that is now at chain.cpp:116, added 7 years ago.
Hopefully this can hint someone of a scenario where it occurs to avoid crashing the process in the future?

**Comment by 1440000bytes** [comment]
> This seems to be the assert that is now at chain.cpp:116, added 7 years ago.

Its at Line 112:

https://github.com/bitcoin/bitcoin/blob/9e229a542ff2107be43eff2e4b992841367f0366/src/chain.cpp#L112

I am not sure how to reproduce this error however removing `assert` and checking if the previous block exists before trying to access it should fix the error.

**Comment by MarcoFalke** [comment]
Bitcoin Core makes heavy use of CPU, RAM and disk IO. Hardware defects might only become visible when running Bitcoin Core. You might want to check your hardware for defects.

* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206
