### ISSUE TITLE
Run coverage functional tests in parallel

### ISSUE THREAD

**Issue by aureleoules** [bitcoin/bitcoin#26736]
**Is your feature request related to a problem? Please describe.**
It currently does not seem possible to execute the functional tests in parallel when running `make cov`.
Thus it makes running this command very slow.

https://github.com/bitcoin/bitcoin/blob/6d40a1a7e7f09ff2c32e53237f968adf8300d028/Makefile.am#L215-L247

**Describe the solution you'd like**
Run test coverage functional tests with `make cov -j8` or `FUNCTIONAL_TESTS_JOBS=8 make cov` ?

**Comment by MarcoFalke** [comment]
Maybe we could replace `--enable-extended-functional-tests` with a `TEST_RUNNER_EXTRA` env var, similar to the one in `./ci/`?

Locally I use an ugly sed hack for now:

```
sed -i 's|functional/test_runner.py |functional/test_runner.py --timeout-factor=10 --exclude=feature_dbcrash |g' ./Makefile.am

**Comment by willcl-ark** [comment]
This was probably resolved by `cmake`.

If this is not the case then please leave a message here and we can reopen it.

**Comment by hebasto** [comment]
> This was probably resolved by `cmake`.

From the "Compiling for test coverage" section of [Developer Notes](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#compiling-for-test-coverage):
> To enable test parallelism:
>
>     cmake -DJOBS=$(nproc) -P build/Coverage.cmake
