### ISSUE TITLE
Unable to open descriptor wallets that are not in a wallet directory

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#26739]
A user reported on IRC that they were unable to open a descriptor wallet that they had in their walletdir as a file, not as a wallet directory. Since we expect descriptor wallets to always be in a wallet directory, this resulted in them being unable to use their wallet until they moved it into a directory. IIRC the it was an intentional decision to impose this restriction for descriptor wallets because we would only be creating new wallets which would create wallets in the expected directories following the expected wallet directory format. Since descriptor wallets were wholly new, there was no expectation that we would need the backwards compatibility feature of being able to open wallets that are not contained within a wallet directory.

But given that this has had an impact on some users, should we allow users to specify wallets in this way?

It's important to remember that this feature only exists for legacy wallets because of how multiwallet was originally implemented. The intention was only to not remove backwards compatibility for wallets created with the original multiwallet implementation, not as a proper feature. But it seems that some users (and third party application developers) are using this as if it were an intended and expected feature.

I'm pretty sure there was some discussion in #19077 about this, but it's a big PR and I can't find the comments.

**Comment by pablomartin4btc** [comment]
I think it could be [this](https://github.com/bitcoin/bitcoin/pull/19077#pullrequestreview-504980287) one? Commented by @ryanofsky, "Future flexibility" bullet point, and your response to him [here](https://github.com/bitcoin/bitcoin/pull/19077#issuecomment-705777007). I could work on it if you both are happy with it since I do also agree with that feature. Cheers!

**Comment by pablomartin4btc** [comment]
> I'm not sure that this is something that we should implement. This issue is primarily for brainstorming and comment gathering.

I understand, and just for my own sake, I'd need to play around with the code and see how it behaves respect to the issues described above in @ryanofsky's comment, plus the "downgrading issues" discussion between both of you, and also the conversations around situations detailed on both PRs #1889 and #11687.
