### ISSUE TITLE
Roles and procedures around adding a bitcoin core maintainer

### ISSUE THREAD

**Issue by 1440000bytes** [bitcoin/bitcoin#26751]
Same as https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-December/021293.html although I am banned in IRC so need to discuss it on GitHub:

List of present bitcoin core maintainers:

|   Username    |    Focus Area   |
| ------------- | -------------   |
|  MarcoFalke   | General, QA     | 
|  fanquake     | General, Build  |
|  hebasto      | General, UI/UX  |
|  achow101     | General, Wallet |
|  glozow       | General, Mempool|

Last 2 developers that stepped down as bitcoin core maintainer:

|   Username    | 
| ------------- | 
|     sipa      | 
|     laanwj    | 

Process followed in adding last maintainer:

1) fanquake [nominated][0] glowzow as rbf/mempool/validation maintainer. 
2) It was discussed in an IRC [meeting][1] and most of the developers agreed to add her as new maintainer except mild NACK from Jeremy Rubin. Some contributors did not like different opinions being shared in the meeting.
3) A [pull request][2] was opened by glowzow to add keys. There were several ACKs, 2 NACKs and 1 meta concept NACK.
   My NACK: https://github.com/bitcoin/bitcoin/pull/25524#issuecomment-1172518409
   NACK by jamesob: https://github.com/bitcoin/bitcoin/pull/25524#issuecomment-1172570635
   Meta concept NACK by luke-jr: https://github.com/bitcoin/bitcoin/pull/25524#issuecomment-1175625779

   Eventually everyone agreed to add glowzow as maintainer and improve the process of adding maintainers. Pull request was merged by MarcoFalke.

Initiatives to improve the process and documentation:

1) Jeremy opened a [pull request][3] and there were lot of disagreements with the documentation. It was closed since a related PR with less changes could be easy to agree upon. 
2) Related [pull request][4] with minimal documentation was also closed by Jeremy with a comment that desire to improve docs seems to be missing based on reviews.
3) Jeremy opened an [issue][5] with title 'Call for Maintainer: P2P & Networking + Privacy' which was changed later and 'Privacy' was removed. He nominated jonatack and vasild was already self nominated so mentioned in the pull request. Nobody appreciated this effort to nominate self or others for a new maintainer. Later this was closed.
4) I had opened an [issue][6] with title Call for Maintainer: Privacy'. This even involved privacy of contributors and not just bitcoin core. It received some comments that made no sense and I eventually closed the issue. 

Process being followed for adding vasild as maintainer:

1) vasild volunteered to be a new maintainer on [IRC][7]
2) It was discussed in IRC [meeting][8], some developers ACKed it and there were no issues.
3) A [pull request][9] was opened by vasild to add keys which is still open and its been 4 months. There were already some ACKs from the IRC meeting and pull request also received some ACKs (16 until now). fanquake, dergoegge and JeremyRubin had some disagreements. Jeremy had recently withdrawn all ACK/NACK from bitcoin core repository for some reasons, fanquake has not replied yet and dergoegge had some new disagreements although don't mind if the pull request is merged.
4) Earlier disagreements were related to scoping and it was changed by vasild
4) There was even a comment that disrespected vasild's contributions in bitcoin core and we had to literally share pull requests in which vasild has improved bitcoin core.
5) I tried adding the topic for a bitcoin core dev weekly meeting but did not achieve anything.

Since Bitcoin Core is the reference implementation for Bitcoin and used by 90% nodes, what should be the ideal process or changes you would expect in roles, procedures etc.?

- 'Call for maintainers' issue should be opened if contributors or maintainers need a new maintainer.
- Discussion about nominated contributors in an IRC meeting where everyone is allowed to share their opinion.
- One of the nominated contributor that gets most ACKs could open pull request to add keys. Everyone can ACK/NACK this PR with reasons.
- Maintainers should be unbiased in merging these pull requests.
- New maintainer should not be funded by the organization that already does it for most of the maintainers.
- Long term contributors that are not living in a first world country should be encouraged.
- Either we should agree every maintainer is a general maintainer that can merge pull request from different modules or define scope for present and new maintainers. We can't do both.
- Self merging pull requests should be avoided.

Let me know if you have any thoughts that could improve this process and involve less politics. 
   

[0]: https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-06-28#826651
[1]: https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-06-30#827695
[2]: https://github.com/bitcoin/bitcoin/pull/25524
[3]: https://github.com/bitcoin/bitcoin/pull/25560
[4]: https://github.com/bitcoin/bitcoin/pull/25839
[5]: https://github.com/bitcoin/bitcoin/issues/25870
[6]: https://github.com/bitcoin/bitcoin/issues/25875
[7]: https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-08-12#842847;
[8]: https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2022-08-18#844523
[9]: https://github.com/bitcoin/bitcoin/pull/25871

**Comment by 1440000bytes** [comment]
I had to ask lot of people, dont care. If we could tx.  Please saved us. Thank you..

**Comment by 1440000bytes** [comment]
@

**Comment by 1440000bytes** [comment]
@ do not use any peers

if at at all full peer works we are successful although do no knot.

**Comment by MarcoFalke** [comment]
I don't think it makes sense to re-hash the same discussion over and over. If anyone wanted to contribute to it, they could have done in the countless previous threads. Closing for now, but anyone can still leave a comment here, and this can also be reopened if needed. Finally, https://github.com/bitcoin/bitcoin/pull/25839 was closed by the author, and is up for grabs. So if anyone wants to roll a ball, it could make more sense to pick it up than to ask others for more input, which was already provided in many places, most of which you already link to in your post.

**Comment by 1440000bytes** [comment]
@MarcoFalke Can you share a reason why you are unable to merge https://github.com/bitcoin/bitcoin/pull/25871 as you had merged the pull request to add last maintainer's keys?

**Comment by MarcoFalke** [comment]
I Concept ACKed the pull because personally I am not too active in the low level net scope, so I won't be actively helping with maintaining that scope from my side and I think that vasild could maintain it. In theory I can merge the pull request, however I don't have the Admin role to cement the change, so it might be easier for an Admin to merge it. See https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role for more details on the roles.
