### ISSUE TITLE
Building or Loading the MS Visual Studio Project issue

### ISSUE THREAD

**Issue by tunerji** [bitcoin/bitcoin#26760]
To build MsVS 2022, in the folder of source "build_msvc" cannot load or locate projects.
Common error for all project files :   bitcoin-tx\bitcoin-tx.vcxproj : error  : Project "" does not contain any configuration.

![image](https://user-images.githubusercontent.com/121049274/209743097-0102eab2-9197-4fd1-88d3-a3c142c76dec.png)

**Comment by MarcoFalke** [comment]
The documentation is here: https://github.com/bitcoin/bitcoin/tree/master/build_msvc#building-bitcoin-core-with-visual-studio

What are the steps to reproduce your issue?

**Comment by tunerji** [comment]
Thank you for prompt reply,
I was simply download the source code and started the MSVS Project file. I will follow the guide that you have sent.

**Comment by MarcoFalke** [comment]
Ok, let us know if you have any other questions or issues
