### ISSUE TITLE
Pathing Guide for Installation using macOS

### ISSUE THREAD

**Issue by Bhaney44** [bitcoin/bitcoin#26778]
**Is your feature request related to a problem? Please describe.**

Yes. One common problem with software setups is the pathing is corrupted. Proper pathing is one of the most important parts of getting started with any new software because if the path is depreciated the software will not properly run. This is the problem I am currently working on with Bitcoin. I downloaded the software but am unable to interact with the network.

```
# In
bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'
# Out
zsh: command not found: bitcoin-cli
```

**Describe the solution you'd like**

Ideally, there would be clear instructions on how to install and get started using Bitcoin software that did not require extensive knowledge of software systems architecture and pathing. A great installation method would automatically install the software along the right path to prevent the pathing problem. A generalized solution would be really good, providing a clear guide to solving the pathing problem on any machine.

**Describe alternatives you've considered**

I've researched solving the problem in the [Bitcoin Forum](https://bitcointalk.org/index.php?topic=5365321.0) and on [StackOverflow](https://bitcoin.stackexchange.com/questions/43148/bitcoin-cli-not-found-on-osx). However, because this common problem is so unique to each local machine, a clear or generalized solution is hard to develop. One specific solution I tried from my research was to add additional context to the command.

```
# In
> curl --user username --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "getblocktemplate", "params": [{"rules": ["segwit"]}]}' -H 'content-type: text/plain;' http://127.0.0.1:8332/
# Out
> curl: (7) Failed to connect to 127.0.0.1 port 8332: Connection refused
```

However, the command resulted in a connection refusal. I found a possible solution in the [Bitcoin Forum](https://bitcointalk.org/index.php?topic=5155612.0), but the problem with the proposed solution is that there is no `bitcoin.conf` file in the main Bitcoin repository. I found a `config` folder in the `src` directory, but there is no `bitcoin.conf` file. 

**Additional context**

I am running on MacOS. Thank you in advance for your attention and advice.

**Comment by w0xlt** [comment]
Regarding `bitcoin.conf`, https://github.com/bitcoin/bitcoin/pull/22235 added a script that generates `bitcoin.conf`.
You can run `contrib/devtools/gen-bitcoin-conf.sh` and `bitcoin.conf` will be generated in `share/examples/`.

**Comment by Bhaney44** [comment]
> contrib/devtools/gen-bitcoin-conf.sh

Hi, thank you very much for your suggestion. I saw #[22235](https://github.com/bitcoin/bitcoin/pull/22235) was merged on May 4th, but I am working on a download of bitcoin core from yesterday, so my download should be completely up to date. I ran your code.

In:
`% contrib/devtools/gen-bitcoin-conf.sh`

Out:
```
fatal: not a git repository (or any of the parent directories): .git
/src/bitcoind not found or not executable.
```

Moving forward: 
1) I think it makes more sense to have `bitcoin.conf` in the main repository rather than being buried deep in the `share/examples/` directory because burying it would make it difficult to call and add complexity; and
2) It probably makes sense to focus on a solution to the core pathing problem, rather than doing a work around.

**Comment by 1440000bytes** [comment]
> I think it makes more sense to have bitcoin.conf in the main repository rather than being buried deep in the share/examples/ directory because burying it would make it difficult to call and add complexity; and

There is an abandoned [pull request](https://github.com/bitcoin/bitcoin/pull/13761) which would create `bitcoin.conf` automatically when bitcoind runs for the first time. However, everyone who reviewed #22235 believe users will discover hidden examples and create a `bitcoin.conf` for themselves.

**Comment by Bhaney44** [comment]
> pull request

Thank you very much for the keen insight. I still have not run `bitcoind` for the first time. 

1. How would you suggest going about running `bitcoind` from the command line?
2. Could you please explain more by what you mean when you say, "everyone who reviewed [#22235](https://github.com/bitcoin/bitcoin/pull/22235) believe users will discover hidden examples and create a bitcoin.conf for themselves."?

**Comment by Bhaney44** [comment]
> Regarding `bitcoin.conf`, #22235 added a script that generates `bitcoin.conf`. You can run `contrib/devtools/gen-bitcoin-conf.sh` and `bitcoin.conf` will be generated in `share/examples/`.

1. Could you please explain further `bitcoin.conf`, what it is and why it matters?
2. What is the reason `bitcoin.conf` would be generated in `share/examples/`?

**Comment by hebasto** [comment]
> I downloaded the software but am unable to interact with the network.

> I am running on MacOS.

There are two artefacts for each macOS architecture, i.e.,  `x86_64` and `arm64`, available for [downloading](https://bitcoincore.org/bin/bitcoin-core-24.0.1/). Which one have you downloaded?

> ... but am unable to interact with the network.
> 
> ```
> # In
> bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'
> # Out
> zsh: command not found: bitcoin-cli
> ```

The `bitcoin-cli` binary is supposed to interact with your local Bitcoin Core running in tne "server" mode:
- `bitcoind`, or
- `bitcoin-qt -server` (runs with GUI)

Assuming your intention to use the `bitcoin-cli` tool, I'd suggest to use `bitcoind` which is available in the following archives:
- https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-arm64-apple-darwin.tar.gz, or
- https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-apple-darwin.tar.gz

As for any other UNIX/Linux-based system, to run a binary one must either provide a full path to the binary or assure that it is available in the `PATH` environment variable.

**Comment by Bhaney44** [comment]
> > I downloaded the software but am unable to interact with the network.
> 
> > I am running on MacOS.
> 
> There are two artefacts for each macOS architecture, i.e., `x86_64` and `arm64`, available for [downloading](https://bitcoincore.org/bin/bitcoin-core-24.0.1/). Which one have you downloaded?
> 
> > ... but am unable to interact with the network.
> > ```
> > # In
> > bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'
> > # Out
> > zsh: command not found: bitcoin-cli
> > ```
> 
> The `bitcoin-cli` binary is supposed to interact with your local Bitcoin Core running in tne "server" mode:
> 
> * `bitcoind`, or
> * `bitcoin-qt -server` (runs with GUI)
> 
> Assuming your intention to use the `bitcoin-cli` tool, I'd suggest to use `bitcoind`. Both `bitcoind` and `bitcoin-cli` are available in the following archives:
> 
> * https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-arm64-apple-darwin.tar.gz, or
> * https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-apple-darwin.tar.gz
> 
> As for any other UNIX/Linux-based system, to run a binary one must either provide a full path to the binary or assure that it is available in the `PATH` environment variable.

Thank you very much for your help; you are appreciated. I downloaded the [bitcoin](https://github.com/bitcoin/bitcoin) repo from GitHub. I have yet to make sense of the download list.

<img width="780" alt="Screen Shot 2022-12-31 at 3 18 47 AM" src="https://user-images.githubusercontent.com/43055154/210134931-29450e45-39e0-4b52-9893-131342e3a69c.png">

1. What are the main differences between the two MacOS artifacts, `x86_64` and `arm64`?
2. What is the difference between the `darwin.dmg` and `darwin.tar.gz` extensions?
3. How can we assign appropriate descriptions to the links in the download?

**Comment by hebasto** [comment]
> I downloaded the [bitcoin](https://github.com/bitcoin/bitcoin) repo from GitHub.

Then you're supposed to build binaries from the downloaded sources as described in the [macOS Build Guide](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md).

> What are the main differences between the two MacOS artifacts, `x86_64` and `arm64`?

The supported hardware architecture.

> What is the difference between the `darwin.dmg` and `darwin.tar.gz` extensions

The former provides a convenient way to install Bitcoin Core GUI and integrate it into your macOS. The latter is just an archive, but it contains all set of the binaries, not GUI only.

**Comment by Bhaney44** [comment]
Thank you. I went through the macOS Build Guide. The first instruction suggests macOS comes with a built in terminal.

`/Applications/Utilities/Terminal.app`

When I ran the command from the home directory, I got an error.

IN:
`cd /Applications/Utilities/Terminal.app`

OUT:
`cd: no such file or directory: Applications/Utilities/Terminal.app
`

After digging through the GUI on my machine, I found that `terminal.app` is visible in the `Utilities` folder, which is not showing to exist when I run from the terminal in VSCode.

I went ahead with the build instructions anyway and found `./src/bitcoind`. The macOS Build Guide says it could take days to download the blockchain, but I have already completed this download. However, I downloaded Bitcoin Core earlier this year and have the GUI from the [Bitcoin Core Website](https://bitcoincore.org/en/download/). It is located in my `Applications` folder, but I have yet to find a way to access it from the terminal or interact with the underlying software. 

1. Is it necessary to download the blockchain twice to make software contributions?
2. What is the reason that the `Applications` folder appears empty through the terminal, but full of applications through the GUI?
3. How do I access Bitcoin Core in the `Applications` folder for the purpose of software development?

**Comment by Bhaney44** [comment]
> bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'

**M1 Chip Download**
https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-arm64-apple-darwin.tar.gz
**Intel Chip Download**
https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-apple-darwin.tar.gz

I downloaded both files and found `bitcoind` and `bitcoin-cli` in `bin`. However, I did not put them in the `Applications` directory. Conceptually, I do not think there is any good justification for requiring or even suggesting having to run Bitcoin software from the Applications directory.

I am going to move forward assuming no because I do not want to start working on solving bugs in macOS core code that are creating the problems I ran into. Please let me know, do you know of any technical reasons for this requirement? Otherwise, I completed PR #26787 to solve **2** and **3** above.

Regarding **1** the solution is still not clear. I ran the bitcoin-cli command in `bitcoin-24.0.1/bin` to get the same error as initially described.

IN:
`bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`

OUT:
`zsh: command not found: bitcoin-cli`

How can we program the machine to recognize the software in a local directory to properly run from the command line?

**Comment by Bhaney44** [comment]
> macOS Build Guide

The solution to **1** and to the question above can be found on [StackExchange](https://bitcoin.stackexchange.com/questions/43148/bitcoin-cli-not-found-on-osx).

**Comment by Bhaney44** [comment]
Moving forward, I am still working toward getting the proper path set up and building with Bitcoin. I am making progress, but I ran into another error caused by macOS. Essentially, macOS by default blocks Bitcoin software applications, such as `bitcoind` and `bitcoin-cli`. So, to use these applications, developers will need to override their privacy settings and opening manually. Another issue I discovered is that to get an output from the command line, it is necessary to put `./` in front of any command. I completed this step and have now moved on to another error.

IN:
`./bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`

OUT:
`zsh: killed     ./bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`

**Comment by Bhaney44** [comment]
The problem was that I was working in a download incompatible with the M1 chip. I was able to move to the correct download version and successfully run `bitcoind`. However, I am now working through a new error.

```
2023-01-02T01:26:11Z Checking all blk files are present...
2023-01-02T01:26:11Z LoadBlockIndexDB(): Block files have previously been pruned
2023-01-02T01:26:12Z : You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
Please restart with -reindex or -reindex-chainstate to recover.
: You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
Please restart with -reindex or -reindex-chainstate to recover.
2023-01-02T01:26:12Z Aborted block database rebuild. Exiting.
2023-01-02T01:26:12Z Shutdown: In progress...
2023-01-02T01:26:12Z scheduler thread exit
2023-01-02T01:26:12Z Shutdown: done
```

I have begun researching regarding pruning on [StackExchange](https://bitcoin.stackexchange.com/questions/37496/how-can-i-run-bitcoind-in-pruning-mode).

**Comment by hebasto** [comment]
> OUT: `zsh: killed ./bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`

On M1/M2, the downloaded binaries need to be signed, for example, like [that](https://github.com/bitcoin/bitcoin/pull/26694#issuecomment-1348887186).

> However, I am now working through a new error.
> 
> ```
> 2023-01-02T01:26:11Z Checking all blk files are present...
> 2023-01-02T01:26:11Z LoadBlockIndexDB(): Block files have previously been pruned
> 2023-01-02T01:26:12Z : You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
> Please restart with -reindex or -reindex-chainstate to recover.
> : You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
> Please restart with -reindex or -reindex-chainstate to recover.
> 2023-01-02T01:26:12Z Aborted block database rebuild. Exiting.
> 2023-01-02T01:26:12Z Shutdown: In progress...
> 2023-01-02T01:26:12Z scheduler thread exit
> 2023-01-02T01:26:12Z Shutdown: done
> ```

Log messages describe a state of your local blockchain and suggest the following steps clearly. It is not an error.

**Comment by Bhaney44** [comment]
> ./bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'

Thank you very much. I found your example:

`codesign -s - ./releases/v23.0/bin/bitcoind`

1. What is self-signing? 
2. What `codesign`?
3. What demands this requirement?

The log messages state:

```
You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
Please restart with -reindex or -reindex-chainstate to recover.
```

1. How does one use `-reindex`?
2. What is unpruned mode?
3. How does one restart with `-reindex`?

**Comment by Bhaney44** [comment]
> > OUT: `zsh: killed ./bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`
> 
> On M1/M2, the downloaded binaries need to be signed, for example, like [that](https://github.com/bitcoin/bitcoin/pull/26694#issuecomment-1348887186).
> 
> > However, I am now working through a new error.
> > ```
> > 2023-01-02T01:26:11Z Checking all blk files are present...
> > 2023-01-02T01:26:11Z LoadBlockIndexDB(): Block files have previously been pruned
> > 2023-01-02T01:26:12Z : You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
> > Please restart with -reindex or -reindex-chainstate to recover.
> > : You need to rebuild the database using -reindex to go back to unpruned mode.  This will redownload the entire blockchain.
> > Please restart with -reindex or -reindex-chainstate to recover.
> > 2023-01-02T01:26:12Z Aborted block database rebuild. Exiting.
> > 2023-01-02T01:26:12Z Shutdown: In progress...
> > 2023-01-02T01:26:12Z scheduler thread exit
> > 2023-01-02T01:26:12Z Shutdown: done
> > ```
> 
> Log messages describe a state of your local blockchain and suggest the following steps clearly. It is not an error.

IN:
`codesign -s ./bitcoind`
OUT:
`error: The specified item could not be found in the keychain.`

IN:
`./codesign -s -bitcoind`
OUT:
`zsh: no such file or directory: ./codesign`

IN:
`./codesign -s - ./bitcoind`
OUT:
`zsh: no such file or directory: ./codesign`

**Comment by Bhaney44** [comment]
> As for the other questions, this is not a support site; it's for reporting bugs. If you have questions about usage, try https://bitcoin.stackexchange.com.

This is for a feature request which I opened according to the guidelines.

**Comment by Bhaney44** [comment]
> Are you trying to install self-compiled binaries? If you use the installer from the website you should get binaries that are signed already.

No. My intention is to properly install bitcoin core on macOS to contribute code.

**Comment by Bhaney44** [comment]
> 

Regarding the three errors. I think the first one is the best to proceed with debugging. I found the error report in a [macOS developer forum](https://developer.apple.com/forums/thread/701696).

**Comment by Bhaney44** [comment]
> As for the other questions, this is not a support site; it's for reporting bugs. If you have questions about usage, try https://bitcoin.stackexchange.com.

1. What is the difference between support and usage? 
2. What is the difference between a bug and an error?
3. Are you an owner of the Bitcoin GitHub?

**Comment by Bhaney44** [comment]
> reindex-chainstate

Thank you. The problem was I had no frame of reference for `-reindex`, what it was or how to use it. I found a reference on [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/questions/60709/when-should-i-use-reindex-chainstate-and-when-reindex), as you suggested.

**Comment by Bhaney44** [comment]
The solution is:

`./bitcoind -reindex`

I documented the solution on [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/questions/116605/how-to-use-reindex).

**Comment by fanquake** [comment]
> zsh: command not found: bitcoin-cli
> This is for a feature request which I opened according to the guidelines.

It's not clear what the feature request is. You can solve the initial "pathing problem" by actually installing the software. There is 

> No. My intention is to properly install bitcoin core on macOS to contribute code.

If your intention is to contribute code, you should clone this repository and compile from source, rather than install the release binaries.

This thread is now mish-mash of generic (some not even specific to bitcoin core) software questions. As mentioned above, this isn't a support forum, and there are other places better suited to solving your issues. It's not clear when this would be "resolved", and unless there is a specific error you are running into, we can close this.

**Comment by Bhaney44** [comment]
> > zsh: command not found: bitcoin-cli
> > This is for a feature request which I opened according to the guidelines.
> 
> It's not clear what the feature request is. You can solve the initial "pathing problem" by actually installing the software.
> 
> > No. My intention is to properly install bitcoin core on macOS to contribute code.
> 
> If your intention is to contribute code, you should clone this repository and compile from source, rather than install the release binaries.
> 
> This thread is now a mish-mash of generic (some not even specific to bitcoin core) software questions. As mentioned above, this isn't a support forum, and there are other places better suited to solving your issues. It's not clear when this would be "resolved", and unless there is a specific error you are running into, we can close this.

Thanks for your feedback. To be clear, the pathing problem refers to problems in installing the software with a proper path for running and contributing code. I did my best to describe the problem, so if you're still having issues on clarity or the words seem like a mish-mash, you may want to get checked for [dyslexia](https://en.wikipedia.org/wiki/Dyslexia), a disease a lot of really smart people have that makes it difficult to derive clear meaning from otherwise cogent text.

The text of this thread is designed to create a clear path, address problems, and ultimately a solution for proper installation on macOS. The request will be resolved when I have added the feature and made the proper contribution. Ultimately, this thread adds a lot of value to the network by identifying and addressing core software problems face by new developers and contributors to Bitcoin Core. Thanks!

**Comment by Bhaney44** [comment]
The problem I am running into now is that running `-reindex` is taking re-downloading the blockchain and it's taking up all the storage on my machine. One solution I am considering is first deleting the blockchain from my machine and running the installation on an external hard drive.

**Comment by Bhaney44** [comment]
> > The problem I am running into now is that running -reindex is taking re-downloading the blockchain and it's taking up all the storage on my machine. One solution I am considering is first deleting the blockchain from my machine and running the installation on an external hard drive.
> 
> That has nothing to do with this issue.

Thanks! The reason this is important for the issue of installation is because the storage capacity requirements are a critical consideration for how and where to install the software.

**Comment by Bhaney44** [comment]
> > The problem I am running into now is that running -reindex is taking re-downloading the blockchain and it's taking up all the storage on my machine. One solution I am considering is first deleting the blockchain from my machine and running the installation on an external hard drive.
> 
> That has nothing to do with this issue.

Do you know where I may be able to find uninstall instructions to remove the software from my machine? I am having trouble finding where the download is happening. Is there a specific command? Thank You!

**Comment by Bhaney44** [comment]
> > Do you know where I may be able to find uninstall instructions to remove the software from my machine? I am having trouble finding where the download is happening. Is there a specific command? Thank You!
> 
> That's a question about usage. As explained, this is not a support forum.
> 
> Please stick to the issue at hand (something about installation paths being unclear, is that it?).

Right. And, I asked what the difference was between usage and support? Without knowing how you define the words, I don't know what you think they mean. 

Yes. The issue is that there is no clear way to correctly install the bitcoin software with clear pathing on macOS. The issue stems from issues in downloading software to macOS generally, especially with the new M1 chip. The goal is to provide a clear download mechanism to allow developers to get started building faster. I've been working on this problem for about four days now and still am not able to run `./bitcoind`.

**Comment by Bhaney44** [comment]
> > As for the other questions, this is not a support site; it's for reporting bugs. If you have questions about usage, try https://bitcoin.stackexchange.com.
> 
> 1. What is the difference between support and usage?
> 2. What is the difference between a bug and an error?
> 3. Are you an owner of the Bitcoin GitHub?

Here ^ @sipa - thank you again for your kind assistance.

**Comment by Bhaney44** [comment]
> > Do you know where I may be able to find uninstall instructions to remove the software from my machine? I am having trouble finding where the download is happening. Is there a specific command? Thank You!
> 
> That's a question about usage. As explained, this is not a support forum. See https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location
> 
> Please stick to the issue at hand (something about installation paths being unclear, is that it?).

The issue is the path provided in the link you gave is corrupted.

`Library/Application Support/Bitcoin/`

does not exist. Moreover, there is a noticeable space between `Application` and `Support`, which is not proper convention on macOS.

**Comment by Bhaney44** [comment]
> > Right. And, I asked what the difference was between usage and support? Without knowing how you define the words, I don't know what you think they mean.
> 
> This is not the place to ask for support, or ask questions about usage. It's for reporting bugs.
> 
> > What is the difference between a bug and an error?
> 
> Errors are reported to inform the user about conditions under which the software can't operate. Bugs are when the software is not working as intended.
> 
> As you've been told, the software is working as intended ([#26778 (comment)](https://github.com/bitcoin/bitcoin/issues/26778#issuecomment-1368892763)).
> 
> > Are you an owner of the Bitcoin GitHub?
> 
> I used to be a maintainer of the Bitcoin Core software repository.
> 
> > Yes. The issue is that there is no clear way to correctly install the bitcoin software with clear pathing on macOS.
> 
> Are you?
> 
> * Trying to run the DMG installer, and is this a problem with it? If so, that's a bug that we should fix. You shouldn't need to mess with certificates in this case.
> * Trying to install the binaries from the tgz by hand, and it's not clear where to put it? That's unrelated to the Bitcoin Core software, and generic for your OS.
> * Trying to build the software from source, and running into problems with that?
> 
> If it's any of these, please clarify.
> 
> If you're having other unrelated problems, please look in the appropriate places for help with usage, or if you believe there is another issue, open another issue.

This is very helpful, thank you. I think the answer to the first two questions is no. The answer to the third question is maybe. I want to install Bitcoin Core, so I can receive information on new blocks and submit information to the network to help validate blocks. To do that, I think I have to download the blockchain and then run programs from the CLI as defined in the [Bitcoin Core Documentation](https://bitcoincore.org/en/doc/0.21.0/rpc/blockchain/getbestblockhash/). I could be wrong. 

The problem I am running into is with installation on macOS because the path is consistently corrupted. Now, the broader problem is a lack of storage on my machine. So, I may move forward with an external hard drive next, which I think may help to prevent the problem generally. 

Yes. I agree and I think the recent updates with the M1 chip cause additional problems and they are generally incompatible with many other OSS libraries. So, one goal for this request is to help fix the current documentation. I will check my home directory to explore possible alternatives and identify the root cause for this issue. Once I have more information, I will report back here. Thank you again.

**Comment by Bhaney44** [comment]
Thank you to everyone for your help here. Unfortunately, I think the only reasonable path forward is to clear my hard drive and start again from scratch on an external hard drive. I have no other way to remove the blockchain form my machine or identify the root cause of the problem. The benefit here is that we will be able to develop a complete guide for installing bitcoin on macOS without the possibility of any external corruption.

**Comment by Bhaney44** [comment]
I have to assume I made a mistake in running `bitcoind` locally and the storage requirements are too great for my machine. So, I am going to close this Issue and then re-open another after I get the new setup going to provide a more cogent guide.
