### ISSUE TITLE
Bitcoin Core startup is interrupted if there is the setting mintxfee=0 in bitcoin.conf

### ISSUE THREAD

**Issue by GregTonoski** [bitcoin/bitcoin#26797]
**Expected behavior**
It is expected that Bitcoin Core is not shutdown automatically during startup. Moreover, it should be possible to set transaction fee at 0.

**Actual behavior**
![Bitcoin Core Error mintxfee](https://user-images.githubusercontent.com/111286121/210274894-e91adf7f-43f7-4c3f-b799-222c00dc34a0.png)

**To reproduce**

1) Click bitcoin-qt.exe.

**System information**

1) A wallet that contained unspent funds was opened previously.
2) The bitcoin.conf file contains "mintxfee=0".
3) Bitcoin Core 24.0.1 official binary for Windows (portable).

**Comment by MarcoFalke** [comment]
Looks like the `0` check was added in 000dc55181f77cd96076c76b2cc13f8bcbe4146e for no reason?

(Maybe it was added as belt-and-suspenders for calls that set `GMF_BLOCK`, but none exist at that commit :man_shrugging: )

**Comment by willcl-ark** [comment]
@GregTonoski I made the change which would fix this issue for you linked in my commit above, but I am curious about the use-case you have for this? If you are not mining then you generally don't want to have `-mintxfee` set much differently than what the wider network is using for `-minrelaytxfee` (and that miners are using for `-blockmintxfee`).

If something like https://github.com/bitcoin/bitcoin/pull/26933 is merged, then this even extends to packages too.

That being said, I somewhat agree that setting the feerate to `0` should not cause the program to exit.

**Comment by MarcoFalke** [comment]
Even if this is only useful for testing, handling `0` different from `0.00000001` (or so) seems odd

**Comment by willcl-ark** [comment]
Sure, that I agree with too! I'll open that one-line fix then so we can close this out.

**Comment by achow101** [comment]
> Creation of a 0-fee basic (movement of funds - nothing new or inventive) transaction is the use-case. (There were a few transactions recorded free-of-charge in Bitcoin last month).

We generally don't allow the creation of 0-fee transactions since they are unlikely to be relayed, nor accepted by our own mempool. The existence of 0-fee transactions in a block does not mean that they will propagate - these are often transactions made by the miners themselves (some pools do this for their payouts), or otherwise given to miners out of band.
