### ISSUE TITLE
Request support for HRNG on ARM using their new RNDR / RNDRRS instructions.

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [bitcoin/bitcoin#26796]
Bitcoin Core currently only support to using RDRAND / RDSEED instruction on x86 architecture when requiring to generate a ultra high quality random numbers. For example, a private key.
https://github.com/bitcoin/bitcoin/blob/master/src/random.h
https://github.com/bitcoin/bitcoin/blob/master/src/random.cpp

ARM later added two new similar instructions as well, RNDR (similar to RDRAND) / RNDRRS (similar to RDSEED).
https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/RNDR--Random-Number
https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/RNDRRS--Reseeded-Random-Number

OpenSSL also had a similar feature request on last year. (Implemented)
https://github.com/openssl/openssl/issues/15627
https://github.com/openssl/openssl/pull/15361
https://github.com/openssl/openssl/blob/master/providers/implementations/rands/seeding/rand_cpu_arm64.c

I hope this feature is also available on Bitcoin Core as Bitcoin Core also can using on ARM machine (E.g. A Mac computer using Apple silicon, Raspberry Pi...).

**Comment by john-moffett** [comment]
It appears that these extensions aren’t supported by many [hardware implementations](https://marcin.juszkiewicz.com.pl/download/tables/arm-socs.html) yet (look under the ’rng’ column), including any Apple product or Raspberry Pi. 

That said, it would be a useful addition once they become more common.

**Comment by TysonsTech** [comment]
Hope this helps and is a correct example of using the RNDR and RNDRRS instructions in ARM assembly language for bitcoin mining:

mov     x0, #0
mrs     x1, cntpct_el0
mov     x2, #32
rndr    x3, x0, x1, x2

; Use the generated random number as a nonce in a hash function
mov     x4, x3
bl      hash_function

; Compare the resulting hash with the target difficulty
mov     x5, TARGET_DIFFICULTY
cmp     x4, x5
bgt     retry

; If the hash is less than the target, it is a valid solution
; and can be submitted to the network
mov     x6, x3
bl      submit_solution

retry:
; Increment the nonce and repeat the process
add     x3, x3, #1
b       start

hash_function:
; Implementation of the hash function, such as SHA-256
; ...

submit_solution:
; Submit the solution to the network
; ...

In this example, the rndr instruction generates a 32-byte random number that is used as the nonce in a hash function. The hash function is implemented in the hash_function label, and the submit_solution label is used to submit the solution to the network. The code retries the process by incrementing the nonce and repeating the hash function until a valid solution is found.

Note that this is just a simple example, and in actual practice, the hash function used for bitcoin mining is more complex and requires more processing power. Additionally, you should take steps to ensure that the random numbers generated by the RNDR / RNDRRS instructions are of sufficient quality for the bitcoin core cryptographic calculation.
