### ISSUE TITLE
origin ip leaked 

### ISSUE THREAD

**Issue by Adityasingh4180** [bitcoin/bitcoin#26790]
It is possible to access origin IP servers served by service  and not cloudflare.
Even though these IP's don't serve a functional version of the app it is possible to enable DDoS attacks by bypassing cloudflare protections

### step to reproduce:~
1. navigate the [shodan.io](http://shodan.io/) and search https://www.shodan.io/search?query=ssl.cert.subject.CN%3Abitcoin.org%2B200 
3. Scroll Down below you found Original IP Revealed
4. This Link have Cloudflare WAF :- https://wallet.bitcoin.org/#      &  https://developer.bitcoin.org/#
5. This Link bypass Cloudflare WAF :~ https://161.35.101.78/        & https://142.93.194.8/
 
### Impact:~
cloudflare  bypass and find origin ip means attacker  remove shield of these website now attacker bypass every cloudflare rules , now attacker do dos , clickjacking , internal service scanning ,ssl bypass means mitm and many other things 

### note:~ 
when i scan private ip i found dozens of cve 

![Screenshot_2023-01-01_13_11_51](https://user-images.githubusercontent.com/84119876/210173851-f667dba5-b401-490f-9dad-af1c1c03331d.png)

![Screenshot_2023-01-01_13_30_31](https://user-images.githubusercontent.com/84119876/210173872-9e9f6616-5abe-4277-87be-bdc37d80d35d.png)

![Screenshot_2023-01-01_13_52_48](https://user-images.githubusercontent.com/84119876/210173885-55840529-7e05-47fd-9b98-677bce4c32bb.png)

### now see this nmap result 
[aditya.txt](https://github.com/bitcoin-core/bitcoincore.org/files/10328897/aditya.txt)
[dev1.txt](https://github.com/bitcoin-core/bitcoincore.org/files/10328899/dev1.txt)

**Comment by 1440000bytes** [comment]
@Adityasingh4180 Bitcoin Core's website https://bitcoincore.org does not use cloudflare.

You should report the issue in https://bitcoin.org website's repository: https://github.com/bitcoin-dot-org/Bitcoin.org
