### ISSUE TITLE
Crypto community

### ISSUE THREAD

**Issue by IlyaGazman** [bitcoin/bitcoin#26885]
I may be asking this on the wrong channel, but where can I find a crypto dev community to talk with? 
There are communities around individual coins, but I can find a place to discuss new crypto projects.

I wrote a new [consensus algorithm](https://confidence-coin.com/Flash-Consensus-algorithm/) for which I am desperately trying to get feedback.

Can you please point me in a direction where posting this question will feel like spam?

**Comment by achow101** [comment]
Try https://bitcointalk.org/. This github repo is not a general discussion board nor is it a place to discuss altcoins.
