### ISSUE TITLE
ci: Use containerfiles?

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#26918]
containerfiles have the advantage that they can be cached locally, so for example an `apt` operation in an image layer is faster to retrieve from the (local) cache than to run vanilla.

Converting the ci system to those is non-trivial, because it uses a lot of env vars, different configs, and numerous per-config hacks.

My understanding of docker is limited, but to pass env vars into a containerfile would require using `ARG` in the file, as well as code to pass in the ARG at runtime via the command line. For hundreds of args, this should be possible, but verbose, which is why I haven't looked at it yet.

**Comment by MarcoFalke** [comment]
Also, I wonder, if we use `ARG`, how this would integrate into Cirrus CI? If it can't be integrated, containerfiles would only benefit a few devs running locally?

**Comment by MarcoFalke** [comment]
Finally, I wonder, if this needs a complete re-write of the ci system, given that we use `source` to run everything in one context (https://github.com/bitcoin/bitcoin/blob/master/ci/test_run_all.sh), and splitting this into several layers wouldn't work, as docker does not retain the `env` across layers.

**Comment by aureleoules** [comment]
Concept ACK on converting the CI to Dockerfiles. This would allow developers to run the CI easily and locally. #26906 is a good step towards this goal. 
I tried to run the CI with the Cirrus CLI but it never worked.

Though, I wonder how ccache and depends_cache can be integrated with Docker and Cirrus. Simple mount volumes maybe?
Because I think this is the most important bottleneck, not the apt install overhead.

**Comment by fanquake** [comment]
> This would allow developers to run the CI easily and locally. 

Just noting, it's already possible to run the CI easily and locally, and this already uses Docker. See https://github.com/bitcoin/bitcoin/blob/master/ci/README.md.

i.e on my Ubuntu machine, I can just run `FILE_ENV="./ci/test/00_setup_env_native_tidy.sh" ./ci/test_run_all.sh` and this spins up the tidy CI job locally, using Docker.

**Comment by MarcoFalke** [comment]
> Though, I wonder how ccache and depends_cache can be integrated with Docker and Cirrus. Simple mount volumes maybe?

It may be possible to do that via `CCACHE_DIR=/ccache_dir` or so? See also https://github.com/bitcoin/bitcoin/blob/b5c88a547996776dbdc2e101bae9b67ac639fd02/.cirrus.yml#L7

I don't think that approach will be changing.

**Comment by achow101** [comment]
> Also, I wonder, if we use `ARG`, how this would integrate into Cirrus CI?

`ARG` values can be provided with a `docker_arguments` section: https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment

**Comment by MarcoFalke** [comment]
Maybe we could build a tool to persist and preserve ci `env` vars between layers?

**Comment by MarcoFalke** [comment]
Did something in https://github.com/bitcoin/bitcoin/pull/26976

**Comment by MarcoFalke** [comment]
Is there something other than `apt` that can be cached in an image layer? If not, closing for now.
