### ISSUE TITLE
Follow ups to #25877

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#26928]
Potential follow ups after #25877.

Request for a test case: https://github.com/bitcoin/bitcoin/pull/25877#discussion_r1073738125

Remove some redundant constructors: https://github.com/bitcoin/bitcoin/pull/25877#issuecomment-1324260342

cc @instagibbs @ajtowns

**Comment by ajtowns** [comment]
> Request for a test case: [#25877 (comment)](https://github.com/bitcoin/bitcoin/pull/25877#discussion_r1073738125)

Done in #26934

**Comment by fanquake** [comment]
Less concerned about the redundant constructors. Close this for now.
