### ISSUE TITLE
Bitcoin-QT grandfather - father - son wallet backup built in?

### ISSUE THREAD

**Issue by saltmaster** [bitcoin/bitcoin#2692]
Having recently suffered a fairly minor loss due to wallet corruption, and being a _little_ lax with backups (hence the only minor loss), I was wondering if anyone would be inspired to build a simple backup system into the QT client, i.e. whenever a spend transaction is made and a new change address is generated, a copy of the wallet.dat is made named for example wallet.dat.backup, and a copy of any pre-existing wallet.dat.backup is renamed as wallet.dat.old deleting any previous wallet.dat.old file. I know some people may see this as 'your fault, you should back up properly', but in the real world how many people do this every single time a new keypair is made?

**Comment by MarcoFalke** [comment]
Closing. Now that all newly created wallets are HD, I think a feature like this is no longer required.
