### ISSUE TITLE
Bitcoin core needs a serious over haul.

### ISSUE THREAD

**Issue by Jazz811** [bitcoin/bitcoin#26959]
Ok so I have been in Bitcoin for an extremely long time and even though it might not reflect to some. But the truth is I am seeing things that need to be addressed in a more cooperative manner like in the beginning. Such as the addition and removal of certain versions or the extreme changes in the scripts resulting in older keys not working or other previous good Ideas being completely ignored. I understand we are a community of people who believe we all know best and we could never grow without one another. But there are things that should be discussed and changed under a collective understanding as done in previous years.

I would like it if there is a way we could contact one another by using the emails here and not these issues. I would like to see such communication because as someone who has the option to modify certain aspects that others cannot it could be more beneficial if someone was to understand and take this issue with more seriousness by emailing me.

I want nothing more than to see bitcoin continue to grow and believe that this is the most beneficial alternative as a serious member of this community. I would appreciate a response and look forward to communicating properly about these things.

**Comment by MarcoFalke** [comment]
Yes, it is possible to discuss network wide consensus or P2P changes by email. See the `bitcoin-dev` mailing list. Bitcoin Core issues are tracked here. While you can not create an issue by email, it is possible to reply to one in your email inbox.
