### ISSUE TITLE
RPC request gives an exception on more than two wallet has been loaded. 

### ISSUE THREAD

**Issue by tunerji** [bitcoin/bitcoin#26980]
RPC request gives an exception on more than two wallet has been loaded.  But it is working as normal when only one of them opened. Therefore, it makes it difficult to operate using multiple api on Bitcoincore. 
**Expected behavior**
working with no exception when we call the wallet using API.

**Actual behavior**
 the exception message : Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path). || 27-Jan-23 15:21:46

**To reproduce**

**System information**

**Comment by achow101** [comment]
There are multiple wallets loaded, so you need to specify which one you want to interact with. The error message says everything you need to know.

**Comment by tunerji** [comment]
I did not see the way of specifying using rpc. Could you give me an example like getbalance, listlabels or listunspent ?

**Comment by achow101** [comment]
Instead of sending your request to `http://127.0.0.1:8332/`, you should send it to `http://127.0.0.1:8332/wallet/mywallet` in order to interact with the wallet named `mywallet`. If you are using `bitcoin-cli`, you would use the `-rpcwallet=` option, e.g. `bitcoin-cli -rpcwallet=mywallet`.

**Comment by tunerji** [comment]
I will try. Thank you very much.
