### ISSUE TITLE
Sender always unknown on the laatest version.

### ISSUE THREAD

**Issue by tunerji** [bitcoin/bitcoin#26984]
Sender always show unknown. is there any way to see senders in order to make our own accounting?

**Expected behavior**
to see sender too.

**Actual behavior**

**To reproduce**

**System information**

**Comment by MarcoFalke** [comment]
Yes, you can set a label for an address.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
