### ISSUE TITLE
How to interpret the asm section of scriptSig

### ISSUE THREAD

**Issue by alex-lt-kong** [bitcoin/bitcoin#26993]
I tried asking the question in [this post](https://bitcoin.stackexchange.com/questions/116947/the-asm-section-of-scriptsig) on bitcoin.stackexchange.com but got no answer. The question is this:

I am trying to understand the output from `bitcoin-cli`. The sample transaction's txid is `061959f1a3360d3781a870b2d43f73f7105b194b22f3765fcb9b8f545f9c8317`, from block 222,222.

The `asm` section of `scriptPubKey` (i.e., `OP_DUP OP_HASH160 28dce60cf7ba4d749afce5fd9781a403d293b74a OP_EQUALVERIFY OP_CHECKSIG`) is more understandable, it decodes `hex` and shows the assembly in a (sort of) human-readable format:
```
"vout": [
    {
      "value": 0.63918136,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 28dce60cf7ba4d749afce5fd9781a403d293b74a OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a91428dce60cf7ba4d749afce5fd9781a403d293b74a88ac",
        "address": "14j4eyoxaAwA4SHj9YcEyVJ7FsqyWvUh9B",
        "type": "pubkeyhash"
      }
    },
...
]
```
The question arises when it comes to the `asm` section of `scriptSig`:
```
{
  "txid": "b66e78c919e36a6c563ceb1b29cfec26f7dec3c3fc1b3631c84056f3ae147f2f",
  "vout": 1,
  "scriptSig": {
    "asm": "3045022100dceb566dec99cf195aba5d6313f1e95eb7bfc74c93a794c4bfd6dd9f4082d8a002203b495b70b917b3dffdcbe70fc6ff7de910d1697efccc14f3eea6944bda87d21c[ALL] 0445554717c4d3240d818f400ab66fd4de438f2fd9174641ea76480b95cd6e883ec274a10b0691d85ac2cb87dcb9eef58b3abb8ee4bd277c8d6fea09eace2bc24a",
    "hex": "483045022100dceb566dec99cf195aba5d6313f1e95eb7bfc74c93a794c4bfd6dd9f4082d8a002203b495b70b917b3dffdcbe70fc6ff7de910d1697efccc14f3eea6944bda87d21c01410445554717c4d3240d818f400ab66fd4de438f2fd9174641ea76480b95cd6e883ec274a10b0691d85ac2cb87dcb9eef58b3abb8ee4bd277c8d6fea09eace2bc24a"
}
```
As you can see, it is `304502206ee08c76923816e4ba287142e9f147fe9cd0f26e6bd58b9a43f2283b1c614f46022100d5de298b627407bc7d5ac0a40259cafb865c30c6a67db926c7284da96ff71abd[ALL] 040841958a405ca1c05de4dcf04dfdfd6e7de5e7cb106744977e3d99eab3e59a2b5bc2441e0ad179055c14200745feb2da2d1b4485087e3a9a2a88a6531a6d6b02`, which isn't really decoded.

I checked the same transaction from [blockstream.info](
https://blockstream.info/api/block/00000000000000b8b49d0b61b14994b5c0a511c4b48a1e251ff2b479b2e6f678/txs/725). It's result is: `OP_PUSHBYTES_72 304502206ee08c76923816e4ba287142e9f147fe9cd0f26e6bd58b9a43f2283b1c614f46022100d5de298b627407bc7d5ac0a40259cafb865c30c6a67db926c7284da96ff71abd01 OP_PUSHBYTES_65 040841958a405ca1c05de4dcf04dfdfd6e7de5e7cb106744977e3d99eab3e59a2b5bc2441e0ad179055c14200745feb2da2d1b4485087e3a9a2a88a6531a6d6b02`
which looks more readable and I can understand that this `scriptSig` pushes two byte arrays into the Bitcoin VM's stack.

So the questions are:
1. Why `bitcoin-cli`'s output is like this?
1. How to interpret it? Especially, how to understand the `[ALL]` part in its `asm`? (Perhaps you can just give me a RTFM link?)

**Comment by alex-lt-kong** [comment]
@willcl-ark :
After reading your post it is a bit more clear to me. However, I am still learning the Bitcoin's serialization protocol (and I am still at the stage of serializing/deserializing byte code for Bitcoin's VM), I have a rather naive question...

Can I summarize your 2nd point as below?:

1. if a byte array ends with `0x01`, it will be replaced by `[ALL]`; Or
2. if `bitcoin-cli`'s `scriptSig`.`asm` contains `[ALL]`, I can assume it is from `0x01`.

The point of the question is, I want to cross-check my bitcoin library's serialization/deserialization output with `bitcoin-cli`'s, so I want follow the convention used by `bitcoin-cli`.

**Comment by willcl-ark** [comment]
You can see roughly how the text is inserted between the square brackets here: 

https://github.com/bitcoin/bitcoin/blob/82903a7a8dc327f94eff0bbbb97d8a0eb04e9044/src/core_write.cpp#L127-L128

And find the sighash type string casts here:

https://github.com/bitcoin/bitcoin/blob/82903a7a8dc327f94eff0bbbb97d8a0eb04e9044/src/core_write.cpp#L75-L82

And finally the sighash flags here:

https://github.com/bitcoin/bitcoin/blob/82903a7a8dc327f94eff0bbbb97d8a0eb04e9044/src/script/interpreter.h#L25-L36

**Comment by alex-lt-kong** [comment]
ah yes, this solves my issue. Thanks!
