### ISSUE TITLE
Concerns about the Impacts of Ordinals Transactions on the Bitcoin Network

### ISSUE THREAD

**Issue by B35363** [bitcoin/bitcoin#26995]
## Problem

Dear Bitcoin Developers,

I am writing to bring to your attention some concerns about the impact of Ordinals transactions on the Bitcoin network. I understand that Ordinals is a new NFT protocol that takes advantage of Tapscript to bypass the size limit imposed by the OP_RETURN function.

However, as it turns out, Ordinals transactions have some unintended consequences that may affect the performance and security of the Bitcoin network. For example, by passing through the cookie data, Ordinals transactions are cheaper than using the OP_RETURN function, and they may occupy all the space in a block, leaving no room for other types of financial transactions.

These issues raise questions about the scalability, fairness, and security of the Bitcoin network. It is crucial that the Bitcoin network remains accessible, secure, and fair for all users, regardless of their use case.

I kindly request that you consider these concerns and take appropriate action to ensure that the Bitcoin network remains accessible, secure, and fair for all users.

As Satoshi Nakamoto once said, something that could relate about BitDNS 

> Stacking all the proof-of-work quorum systems in the world into one dataset does not scale. Bitcoin and BitDNS can be used separately. Users shouldn't have to download the entire set of both to use either one.

## Solution that could work

To address these issues, Instead of storing these data onchain, I propose the introduction of a new feature that would allow users to store their NFTs off-chain, in a decentralized and secure way. This would significantly reduce the data size impact on the Bitcoin network, as NFT data would no longer need to be included in every transaction.

To implement this feature, I suggest using a decentralized data storage system, such as IPFS or similar, to store NFT data in a secure and decentralized manner. Users could then create a transaction that references the IPFS hash of their NFT, which would be included in the blockchain and serve as a proof of ownership.

This solution would not only reduce the data size impact on the Bitcoin network but also increase its scalability, security, and efficiency.

## Conclusion

Bitcoin shouldn't be used to store anything else than monetary transactions and small references.

**Comment by fanquake** [comment]
I'm sure most of the developers here are aware of Ordinals, however this (Bitcoin Core) bug tracker is not the right place to have this discussion.

**Comment by B35363** [comment]
> I'm sure most of the developers here are aware of Ordinals, however this (Bitcoin Core) bug tracker is not the right place to have this discussion.

I may have chosen the wrong place then, the latest Taproot upgrade was Bitcoin's core modification, I'll remove it

**Comment by MarcoFalke** [comment]
I don't know where you got your information about Taproot and Tapscript, but it is wrong. Witness data is discounted since segwit.

If you have general bitcoin question, for example about feerates or witness data, they are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.

**Comment by GregTonoski** [comment]
The most serious issue reported in years and immediately neglected. Why not reopening this issue in order to search for a solution/fix?
