### ISSUE TITLE
MSan CI failure in psbt_wallet_tests and feebumper_tests

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#27001]
"SUMMARY: MemorySanitizer: use-of-uninitialized-value (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x319da5b) in sqlite3Strlen30"

https://cirrus-ci.com/task/5119169004306432?logs=ci#L3638
and
https://cirrus-ci.com/task/5119169004306432?logs=ci#L3762

**Comment by fanquake** [comment]
This is fixed in #26998

**Comment by jonatack** [comment]
also https://cirrus-ci.com/task/6734922547724288?logs=ci#L3639

**Comment by jonatack** [comment]
> This is fixed in #26998

Thanks!

**Comment by pinheadmz** [comment]
Testing webhooks don't mind me
