### ISSUE TITLE
BitCoin BlockChain Download Alternate

### ISSUE THREAD

**Issue by ahmed-naeem1012** [bitcoin/bitcoin#27026]
please anyone out there having knowledge help me that **How can I deploy a node and start transactions on BTC Core without downloading the complete blockchain**, as its more than 350GB Right now.

I want to know if there is any possible solution to it?
<img width="659" alt="Screenshot 2023-02-02 at 8 06 19 PM" src="https://user-images.githubusercontent.com/101569763/216361805-d200b047-e4c9-47fa-8494-826c267f0177.png">

**Comment by jarolrod** [comment]
Pruning is enabled in your screenshot of the gui intro window. You’ll go through an IBD’s worth of network bandwidth, but storage on disk will be limited to your prune target.

**Comment by ahmed-naeem1012** [comment]
does this mean that just only the data indicated in pruning will be downloaded or will it initially download the complete history and then proceed?

**Comment by jarolrod** [comment]
@ahmed-naeem1012 storage on disk will not exceed the prune target.

**Comment by ahmed-naeem1012** [comment]
@jarolrod  what about the time period and what work structure does that follow to not exceed the prune target and still run our nodes?

**Comment by john-moffett** [comment]
@ahmed-naeem1012 Roughly speaking, the node will download less than 2 GB worth of blocks starting from the Genesis block, and while it downloads newer ones, it will delete the older ones it already downloaded and processed. When the node processes a block, it maintains the things it needs to fully validate new blocks (the UTXO set), so it no longer needs the full original blocks. It will only keep several days' worth of original blocks in your storage, not to exceed 2 GB.

The entire process will take a while to reach the current chaintip -- the exact time depends on many factors including your network speed and specific hardware. It generally ranges from several hours to a couple days.

I agree that the message is a bit ambiguous about exactly when the data gets deleted. To be clear, it does not _store_ all ~450 GB and only then delete all but 2 GB. It will delete them as it goes.
