### ISSUE TITLE
macos depends build does not cache in the CI

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27031]
At least in the CI, the depends build does not cache. E.g. https://cirrus-ci.com/task/5094611354386432?logs=ci#L789

This causes the build to take an hour when it should be done in less than 10 minutes witch a ccache.

**Comment by MarcoFalke** [comment]
ccache doesn't cache either, https://cirrus-ci.com/task/5094611354386432?logs=ci#L3103

**Comment by fanquake** [comment]
See also #21552

**Comment by MarcoFalke** [comment]
At least locally this does not occur after #27028 :shrug: ?
