### ISSUE TITLE
[SECURITY] data carrier transactions (OP_RETURN outputs) should not be relayed by default so that mempools are not overcrowded with non-transfer transactions

### ISSUE THREAD

**Issue by GregTonoski** [bitcoin/bitcoin#27032]
By default, (big e.g. 4MB, full block size) data carrier transactions should not be relayed in order not to fill the default 300MB capacity of mempool with fewer than 100 transactions and give space/priority to standard (non-data carrier, transfer) transactions.

**Expected behavior**
datacarrier parameter is set to false by default (if not set in bitcoin.conf otherwise)

**Actual behavior**

datacarrier=0 must be set in bitcoin.conf in order not to relay data carrier transactions like for example: [0301e0480b374b32851a9462db29dc19fe830a7f7d7a88b81612b9d42099c0ae](https://mempool.space/tx/0301e0480b374b32851a9462db29dc19fe830a7f7d7a88b81612b9d42099c0ae)

**To reproduce**

Just run Bitcoin Core without modifying default settings.

**System information**

Bitcoin Core 24.0.1.

**Comment by MarcoFalke** [comment]
The transaction you are referring to is already non-standard and was not relayed by Bitcoin Core by default. Bitcoin Core policy and policy changes have no effect if miners ignore them.

If you have more bitcoin questions and/or support requests, please use [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.

**Comment by GregTonoski** [comment]
Thanks for the clarification.

**Comment by fujicoin** [comment]
@MarcoFalke 
This could be a Taproot related bug.
The size of this TX should be very small.
https://btc1.trezor.io/tx/0301e0480b374b32851a9462db29dc19fe830a7f7d7a88b81612b9d42099c0ae
As you can see, there is only one input and one output.
Note that the fee is 0.
Could the problem lie in the inability to interpret the Raw Transaction?
