### ISSUE TITLE
feature: lock inscriptions automatically

### ISSUE THREAD

**Issue by 1440000bytes** [bitcoin/bitcoin#27046]
Bitcoin Core is used a lot for inscriptions but they could be spent accidentally so lets freeze it.

We could not do it in past but  @meshcollider helped fix it in https://github.com/bitcoin/bitcoin/pull/23065

Lets lock inscriptions with by default it to help users

**Comment by kristapsk** [comment]
Should Bitcoin Core care about L2 protocols built on top of Bitcoin? I don't think so.

**Comment by 1440000bytes** [comment]
> Should Bitcoin Core care about L2 protocols built on top of Bitcoin? I don't think so.

Why does it care about lightning in so many pull requests?

**Comment by 1440000bytes** [comment]
Although there is no L2 in OP

**Comment by kristapsk** [comment]
> > Should Bitcoin Core care about L2 protocols built on top of Bitcoin? I don't think so.
> 
> Why does it care about lightning in so many pull requests?

Examples?

And one thing would be optimizing something for popular use cases, but automatically freezing UTXOs because of some script patterns seems wrong. Auto-freezing forced address reuse ("dust attack") UTXOs then could be first to be discussed.

**Comment by 1440000bytes** [comment]
> > > Should Bitcoin Core care about L2 protocols built on top of Bitcoin? I don't think so.
> > 
> > 
> > Why does it care about lightning in so many pull requests?
> 
> Examples?
> 
> And one thing would be optimizing something for popular use cases, but automatically freezing UTXOs because of some script patterns seems wrong. Auto-freezing forced address reuse ("dust attack") UTXOs then could be first to be discussed.

I respect you although don't understand it.
