### ISSUE TITLE
migratewallet help is misleading about encrypted wallets

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#27048]
The help tells me I should unlock my encrypted wallet:

```
> help migratewallet

...
Requires wallet passphrase to be set with walletpassphrase call if wallet is encrypted.
```

But when I do so and attempt to migrate the wallet I'm told that I've entered my password for needlessly:

```
> migratewallet

Error: migratewallet on encrypted wallets is currently unsupported.
```

v24.0.1

**Comment by furszy** [comment]
Covered in #26595

**Comment by dooglus** [comment]
I read that issue before reporting this one and it didn't seem to be talking about the same issue. I'm attempting to migrate the currently loaded and unlocked wallet, not trying to migrate an unloaded wallet or specify a passphrase on the command line.

**Comment by achow101** [comment]
The issue is that `walletpassphrase` wouldn't work anyways. The help text is indeed wrong.
