### ISSUE TITLE
Add configuration option that will allow for setting the upper bound on transaction size for relaying

### ISSUE THREAD

**Issue by pantadeusz** [bitcoin/bitcoin#27055]
The recent events, where people store big data on the blockchain in the witness (like images) showed that the dispute about this topic was not settled during OP_RETURN discussion. Some people like the idea that every payed transaction is not a spam, some don't.   

I suggest that users could set the transaction size limit in the configuration file that will make node drop transactions from the memory pool that are larger. This way node operators would decide what kind of transactions gets relayed via their node.
 
Alternatively this limit could be on the consensus layer, but I don't think it is a good idea.

If I would get some help, I can try to implement this feature (no guarantee of success, because i don't know the Bitcoin Core codebase yet, however I have some experience in programming).

**Comment by petertodd** [comment]
NACK

Coinjoins are very large transactions that ~no-one believes are illegitimate. The existing standardness size limit already unnecessarily limits of the size of them (as Wasabi has pointed out); any further limitation would be undesirable.

Also, per-node limits are pretty much pointless when the goal is censorship. It only takes a small % of nodes to get transactions to miners reliably (as shown by the [success of full-RBF](https://petertodd.org/2022/bitcoin-core-nodes-running-fullrbf)).

**Comment by pantadeusz** [comment]
Thank you for clarification and a good argument against. Should I be the one to close issue?

**Comment by petertodd** [comment]
Go ahead and close it, thanks!
