### ISSUE TITLE
RPC getdescriptorinfo shouldn't output undefined value of the "descriptor"

### ISSUE THREAD

**Issue by GregTonoski** [bitcoin/bitcoin#27078]
**Expected behavior**

```
{
  "descriptor": "tr(cUTFbLPUaBAPmTKwjcDs4rWHUSEUbUBfkPMogrbTmQFnJA3vgrLE)#tdkpah70",
  "checksum": "tdkpah70",
  "isrange": false,
  "issolvable": true,
  "hasprivatekeys": true
}
```

**Actual behavior**

{
  "descriptor": "tr(**967a9c6e1e189a8390e8ed870b918cc64742bebc372625071c410ac96b1aa580)#x9af7q5s**",
  "checksum": "tdkpah70",
  "isrange": false,
  "issolvable": true,
  "hasprivatekeys": true
}

**To reproduce**

Execure the RPC command, e.g.: `getdescriptorinfo "tr(cUTFbLPUaBAPmTKwjcDs4rWHUSEUbUBfkPMogrbTmQFnJA3vgrLE)"`

**System information**

Bitcoin 24.0.1

**Comment by achow101** [comment]
This is intended behavior, see the help text:

```
"descriptor" : "str",             (string) The descriptor in canonical form, without private keys
```

**Comment by GregTonoski** [comment]
I understand that the value "967a9c6e1e189a8390e8ed870b918cc64742bebc372625071c410ac96b1aa580" is a public key. If there is a private key in a descriptor which is argument to getdescriptorinfo then another descriptor with a corresponding public key is output as a "descriptor". Otherwise, same descriptor is output. 

- Both getdescriptorinfo `"tr(cUTFbLPUaBAPmTKwjcDs4rWHUSEUbUBfkPMogrbTmQFnJA3vgrLE)"`
- and getdescriptorinfo `"tr(967a9c6e1e189a8390e8ed870b918cc64742bebc372625071c410ac96b1aa580)"`

output the same "descriptor" value:  "`tr(967a9c6e1e189a8390e8ed870b918cc64742bebc372625071c410ac96b1aa580)"`

I would suggest adding more explanation in the help text.
