### ISSUE TITLE
RPC importdescriptors shouldn't fail with the error code -5, "Missing checksum"

### ISSUE THREAD

**Issue by GregTonoski** [bitcoin/bitcoin#27075]
**Expected behavior**

Descriptor is imported successfully.

**Actual behavior**

Descriptor is not imported. There is the error:
```
[
  {
    "success": false,
    "error": {
      "code": -5,
      "message": "Missing checksum"
    }
  }
]
```
**To reproduce**

1. Execute the RPC command, e.g.: `importdescriptors '[{"desc": "tr(cUTFbLPUaBAPmTKwjcDs4rWHUSEUbUBfkPMogrbTmQFnJA3vgrLE)", "timestamp": "now"}]'`

**System information**

Bitcoin Core 24.0.1

Excerpt from the BIP-380 specification: 

> The top level expression is a SCRIPT. This expression **may** be followed by #CHECKSUM, where CHECKSUM is an 8 character alphanumeric descriptor checksum.

**Comment by achow101** [comment]
This is intended behavior. While a descriptor in general may have a checksum, descriptors being imported must have a checksum in order to ensure that the user did not make a typo or other transcription error.

**Comment by kristapsk** [comment]
You can compute checksum and get descriptor with checksum added with `bitcoin-cli getdescriptorinfo`.

**Comment by GregTonoski** [comment]
> This is intended behavior. (...) descriptors being imported must have a checksum in order to ensure that the user did not make a typo or other transcription error.
The implemented behaviour is against the specified one. Presumably, the BIP-380 specifies the inteded behaviour.

Besides, there already is "typo or other transcription error" prevention checksum (base58check) in input string.

**Comment by achow101** [comment]
> The implemented behaviour is against the specified one. Presumably, the BIP-380 specifies the inteded behaviour.

The intended behavior is for parsers. `importdescriptors` is applying additional rules on top of the parser.

> Besides, there already is "typo or other transcription error" prevention checksum (base58check) in the input string in the example.

Not always, and not everything. Hex pubkeys are checksumless, and the checsums for WIF keys and extended keys do not cover all parts of the descriptor. They can miss important things such as multisig thresholds. Furthermore, with miniscript, there are many parts of the descriptor that are only covered by the descriptor checksum.

**Comment by GregTonoski** [comment]
I think that the issue is still open.

**Comment by achow101** [comment]
Perhaps the BIP text could be updated to clarify, but this _is_ intended behavior for the RPC.

**Comment by GregTonoski** [comment]
> Perhaps the BIP text could be updated to clarify, but this _is_ intended behavior for the RPC, so there's no issue here. See #15368.
> 
> Considering that I an a co-author of BIP 380 and the original implementer of `importdescriptors`, I would say that I know exactly what was intended behavior for both.

Changes are not impossible. Another checksum on top of base58check seems to be redundant and degrades user expierence in the case of importing a private key, doesn't it?

**Comment by achow101** [comment]
> Changes are not impossible. Another checksum on top of base58check seems to be redundant and degrades user expierence in the case of importing a private key, doesn't it?

No, it is not redundant. There are more to descriptors than just private keys. The checksum is also a better checksum since it is error finding too, although that is not implemented yet.
