### ISSUE TITLE
Failing to fetch `cfheader` corresponding to block header in `headers` message

### ISSUE THREAD

**Issue by Christewart** [bitcoin/bitcoin#27085]
Occasionally when I receive a `headers` message on the p2p network, and attempt to fetch the `cfheader` that corresponds to a block header inside of a `headers`, i get this error message inside of my `debug.log`

>2023-02-07T16:47:15Z [net] Failed to find block filter hashes in index: filter_type=basic, start_height=150, stop_hash=3ca9030aeb6c2721cfbab0116b8d96e2d3c7e00738238010e0bc622566dc2aed

**Expected behavior**

I should be able to fetch a `cfheader` for a block after the block has been relayed to me over the p2p network via `headers` p2p message.

**Actual behavior**

It fails to fetch the `cfheader` that corresponds to the block.

**To reproduce**

I am unable to reproduce reliably, but this does occur ~1/5 times when running test suites on bitcoin-s. 

**System information**

24.0 (although i have seen this behavior for awhile and believe this issue exists in older versions of `bitcoind`)

The OS/CPU arch does not seem to be a factor in this bug. I can reproduce on Linux/mac machines with older/newer versions of bitcoind

I've attached the `debug.log` for my `bitcoind` instance. The block hash in question is `3ca9030aeb6c2721cfbab0116b8d96e2d3c7e00738238010e0bc622566dc2aed`.

[debug.log](https://github.com/bitcoin/bitcoin/files/10714034/debug.log)

This is related to: https://github.com/bitcoin-s/bitcoin-s/issues/4976

**Comment by furszy** [comment]
Even when the peer sent the `headers` message, the block filter index could still be processing the block signals.
If possible on your tests, call `syncwithvalidationinterfacequeue` to empty the validation interface queue prior to request the `cfheader`s.

**Comment by Christewart** [comment]
Thanks for pointing me in the right direction, this seems to be the equivalent in the bitcoin core python test harness https://github.com/bitcoin/bitcoin/pull/22311

**Comment by Christewart** [comment]
This still seems to be an issue on 24.2 . I'm going to try and upgrade my nodes used for test harnesses in to use 25.x and 26.x. From a quick look through release notes, it doesn't seem like there was anything in those releases that would fix this bug. 

Note, i am not calling `syncwithvalidationinterface` explicitly after generating blocks on regtest and waiting for that rpc call to complete before continuing with testing logic. This doesn't seem to happen as much on slower machines (x86_64), but on apple silicon it seems fairly reproducible.

**Comment by Christewart** [comment]
> > Note, i am not calling `syncwithvalidationinterfacequeue` explicitly

Massive apologies, that was a typo. I _am_ calling `syncwithvalidationinterfacequeue` explicitly. [I _always_ call it in conjunction with `generatetoaddress`](https://github.com/bitcoin-s/bitcoin-s/blob/ff8376ceb664436e9d56da02b1f7598da1dbc459/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MiningRpc.scala#L33)

**Comment by Christewart** [comment]
> > I am calling syncwithvalidationinterfacequeue explicitly.
> 
> Are you sure, because the debug log you shared does not mention it?

I've modified the OP to add those logs and i've attached the full `debug.log`.

**Comment by Christewart** [comment]
> Ok, it is called, but you also have to wait for it to complete and return from the RPC, before continuing the test. Currently it looks like it is called, and processes the block events, but at the same time the P2P interface is asked for the filters.
> 
> It may be best to only use a single thread for the test logic.

This is the behavior of this code snippet in Scala

https://github.com/bitcoin-s/bitcoin-s/blob/ff8376ceb664436e9d56da02b1f7598da1dbc459/bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MiningRpc.scala#L33 

The `<-` operator corresponds to `wait for this async computation to complete`. On the line before 

```scala
    //make the rpc call to `generatetoaddress`
    val hashesF = bitcoindCall[Vector[DoubleSha256DigestBE]](
      "generatetoaddress",
      List(JsNumber(blocks), JsString(address.toString), JsNumber(maxTries)))

    for {
      hashes <- hashesF //this waits for `generatetoaddress` to complete, and gives me the hashes store in the `hashes` variable
      _ <- syncWithValidationInterfaceQueue() // do the same with this RPC call, this doesn't let execution continue until bitcoind gives us a response
    } yield hashes
```

**Comment by Christewart** [comment]
> There was a previous discussion (I can't find it now)

Do you recall the venue of where it was discussed? Some PR/issue on github or elsewhere? I may go digging.

In general, should I leave this issue open? It seems like this will not be resolved in the short term (or ever maybe).

**Comment by mzumsande** [comment]
This doesn't happen normally, see https://github.com/bitcoin/bitcoin/issues/29655#issuecomment-4178924307 - we usually only advertise a new block after having built the filter. 

However, it can happen in a rare race situation: A new peer connects to the node and sends a `getheaders`/gets the new header while the blockfilter is still being constructed and then asks for it. That way, it doesn't need to wait for the regular `header` message from the `UpdatedBlockTip` signal. This is what's happening in the log given above. It could also happen with clients that regularly send `getheaders` themselves instead of waiting for `headers` messages sent by the node triggered by a tip update without a prior request.

**Comment by randomlogin** [comment]
I have experienced the same problem and tried to fix it in this PR: https://github.com/bitcoin/bitcoin/pull/35262
