### ISSUE TITLE
Ability to hide/delete receive addressess

### ISSUE THREAD

**Issue by Suffice** [bitcoin/bitcoin#2710]
This list can become very clustered with abandoned addresses, and can make finding specific addresses more difficult.

Deleting addresses should require the password if the wallet is encrypted.

Hiding an address would be preferable, just in case a person receives a transaction to one.

**Comment by LaudaM** [comment]
More than 1 year has passed and we still don't have this feature?

**Comment by laanwj** [comment]
As long as no one is interested in implementing it, it won't happen.

Making suggestions here is just an idea box, it does not obligate anyone to take action of any kind.

**Comment by laanwj** [comment]
Similar to #1653 and #3314 (but not a duplicate)

**Comment by promag** [comment]
Not sure if I understand the feature correctly:
 1. Add a "visible" column where each row has a checkbox and then an option "[x] show visible only", or
 2. automatically hide what **doesn't matter** and an option to toggle that.

**Comment by promag** [comment]
> Hiding an address would be preferable, just in case a person receives a transaction to one.

Same as 17174.

**Comment by promag** [comment]
By supporting multiple labels we could have internal labels like "__hidden"? `getaddressinfo` already returns `labels: []`.

**Comment by MarcoFalke** [comment]
Let's continue discussion in #17174
