### ISSUE TITLE
Why is Bitcoin Core structured as a wallet? I know that it began as a wallet, but is it possible to make it like a GUI block explorer instead?

### ISSUE THREAD

**Issue by yanagawak** [bitcoin/bitcoin#27110]
I'm always frustrated when I open up Bitcoin Core, and then all I get is an empty wallet GUI. I see no information about the block-chain itself. When I want to see on-chain data, I have to go to centralized websites instead.

I would like to see Bitcoin Core be restructured as a GUI block explorer. Delete all the wallet features. Bitcoin Core is a really, really bad wallet, to be honest. Didn't Core developer Luke Dash Junior just lose his entire stash of 300 coins because he was using a internet-connected Bitcoin core as a hot wallet? 

It is very bad practice to run a hot wallet, period. Private key information should never ever touch a internet connected computer. I use Electrum on TAILS for signing transactions, and I use Electrum on Windows as a watch only wallet. 

I would like to see Bitcoin Core be a locally run self sovereign version of blockchain.com/explorer or mempool.space.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
