### ISSUE TITLE
on OSX, bitcoind chooses different data directory than Bitcoin-Qt

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#27119]
bitcoind uses `~/Library/Application Support/Bitcoin` as base data directory path but Bitcoin-Qt uses `~/.bitcoin`

I actually much prefer the latter since it is more UNIX-like and I assume users running the daemon from the command line probably do as well. It might make sense if this behavior was swapped and the GUI chose the user-friendly library/support path, but my preference would be using `~/.bitcoin` on OSX all the time.

The issue most likely comes down to this logic in system.cpp:

https://github.com/bitcoin/bitcoin/blob/fe1b3256888bd0e70d0c9655f565e139ec87b606/src/util/system.cpp#L859-L864

... but I have no idea why Bitcoin-Qt would be compiled without the `MAC_OSX` flag while bitcoind would be. I confirmed the behavior building bitcoind and -Qt both from master and also by downloading the v24.0.1 GUI for OSX from bitcoincore.org

It's also possible that this issue only affects M1 (arm64) Macs like mine:

```
--> uname -a
Darwin   21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
```

**Comment by willcl-ark** [comment]
FWIW I could not replicate this on my 2017 Intel MBP on master. Choosing "Use Default Datadir" on QT setup screen saw it use "Library/Application Support/Bitcoin" as the datadir.

**Comment by pinheadmz** [comment]
This is my fault, there were old Qt preferences saved and the custom directory was recalled from there
