### ISSUE TITLE
Received BTC not showing in ( btc core ) address nor private key

### ISSUE THREAD

**Issue by PrivateJetLife** [bitcoin/bitcoin#27115]
I have created a new BTC Core wallet and had a receiving address of ( 38pV5yBHYBcizDotzhaVPVspT1veYTYRHV ) for which i used Trust Wallet to send 0.00012018 test BTC to my Core, but balance is not showing in my Core dashboard.
The same balance is visible successfully on Trust Wallet, Blockchain, BlockChare, Bitref, and everywhere.
I even tried to import the private key to Electrum and get the balance, y
![Capture](https://user-images.githubusercontent.com/125639620/219576816-5f2638f5-3211-433a-b8c3-a31672dbe45d.PNG)
et it did not work.
I suspect a bug here in BTC Core that has not updated the received BTCs in my account ( address & private key ).
Appreciate looking into this.
 
![Capture](https://user-images.githubusercontent.com/125639620/219577024-afeb8e06-5731-4c80-854f-cf73060603a0.PNG)
![Capture](https://user-images.githubusercontent.com/125639620/219577477-8f0f87ce-b14c-43a4-98a2-91213c1843c9.PNG)

**Comment by Calvinn097** [comment]
your btccore is synchronizing, 4 years and 16 weeks behind
