### ISSUE TITLE
Bitcoin Core very slow sync

### ISSUE THREAD

**Issue by popkian** [bitcoin/bitcoin#27134]
I understand that it is not a new issue but I could not find any answer to my problem in previous threads. 
I am syncing the bitcoin core for the first time , it has already past 48 hours and the progress is at 80%.

The issue that I am trying to figure out is that why it is not using the full resources of my computer. 
My computer is about 6 years old. 
I have a 5G internet and I tested my download speed which is about 50 mbps . I have increased the dbcache to 8000, threads to -1 and I have disabled windows antivirus. No other program is running but still my connectivity to peers are very slow. 
I can see that my CPU usage is at about 2% to 10% . memory usage is also very low. so I dont know what else to do to speed it it up. 
some times it speeds up but again it slows down.  Please let me know if you have any suggestion

**Comment by fanquake** [comment]
> My computer is about 6 years old.

What sort of harddrive do you have? 

Going to close for now in any case. It's not possible for us to debug this, or provide any suggestions until you provide further information. Can be reopened if that happens.

**Comment by helpau** [comment]
Please reopen the issue, I will try to give logs with lock conflicts later. Probably related #776
