### ISSUE TITLE
miniscript_stable fuzz timeout

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27147]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56270

**Comment by fanquake** [comment]
Verified as fixed: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56332#c3

**Comment by fanquake** [comment]
> Wrong issue, actually;

Whoops. Yes, both ended up being addressed here.
