### ISSUE TITLE
Add support for all networks in `deserialize_v2` in test_framework

### ISSUE THREAD

**Issue by brunoerg** [bitcoin/bitcoin#27140]
`deserialize_v2` function (`test_framework`) should be able to deseriablize all networks presented in BIP155 (e.g. onion, ipv6, etc), however, it only works for ipv4 and i2p. I noticed that when I was using `message-capture-parser` and realized that most `addrv2` messages weren't able to be deserialized.

**Comment by brunoerg** [comment]
ooops, it added `feature` label but i think it should be `bug`

**Comment by fanquake** [comment]
Can probably just be done when some code is added that would actually use the functionality? Going to close this for now.

**Comment by brunoerg** [comment]
> Can probably just be done when some code is added that would actually use the functionality? Going to close this for now.

Sorry for not specifying but 'message-capture-parser' is not able to deserialize some addrv2 messages because of it. So, could we leave this issue opened?
