### ISSUE TITLE
interpreter: split PrecomputedTransactionData::Init() or rename `force`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#27152]
Potential followup from https://github.com/bitcoin/bitcoin/pull/27122#pullrequestreview-1307630323:

> I do wonder if it makes sense to rename force to something like signing_context or even more drastically split Init up into two obvious types ConsensusInit/SigningInit to make things clearer to future readers.

Seems like there might also be scope to make some of the `Init()` inline commentary clearer, given other review comments in #27122.

cc @instagibbs @ajtowns @roconnor-blockstream. If there is agreement on doing this, lets open a change, otherwise we can close this issue.

**Comment by instagibbs** [comment]
I obviously agree with myself, will let others chime in

**Comment by Metapolitan22** [comment]
Hello gents, we are searching for a Bitcoin dev which has some knowledge  in ordinals and inscribing specific stats. Sorry for the message out of context.

**Comment by willcl-ark** [comment]
Closing this as it has not had any activity in a while. If you are interested in continuing discussion on this, or you feel that it is sufficiently important, please leave a comment so that it can be reopened.
