### ISSUE TITLE
Bitcoin core full node with S3 bucket

### ISSUE THREAD

**Issue by Tharsanan1** [bitcoin/bitcoin#27168]
**Is your feature request related to a problem? Please describe.**
I am trying to run a bitcoin full node on a aws ec2 instance. The problem is when allocating ssd, the cost is too much. The cost for S3 storage is really low. Since bitcoin total block chain size is increasing every day it is better if we can use these kind of services. As I understand frequency for a full node to get the old data is relatively low. 

**Describe the solution you'd like**
I suggest, we should be able to configure how we store the blocks. One possible way is storing the data and fetching the data using REST calls. In this approach bitcoin core will not worry about how blocks are stored and where. Whenever it gets a new block it will invoke a POST http call to the confgured url and save it. Whenever it needs a old block data it will do a GET call to the server using the configured url. This way individuals can develop their own version of servers that will use different type of storage services. The REST approach is just a suggestion we can implement anything that let us configure to use different type of storage mechanisms. 

One of the main argument against bitcoin is: Because of the growing blockchain size it will become impossible to run a full node by an average individual. With this kind of feature we can use very cost effective solutions for data storage.

**Comment by ponury1990** [comment]
Ja to bym chciał w końcu poczuć ze mam coś a nie tylko się patrzyć nie da sie chociaż 1 BTC na portfel przelać trzeba się prosić o swoje szczęscie ?

**Comment by hebasto** [comment]
NACK on any feature which allows to delegate a block storage to a third-party.

It will create an opportunity for an adversary to alter block data, which being served to other peers will create a spam network traffic. That is, essentially, an attack on the Bitcoin network.

---

In addition to the [mentioned](https://github.com/bitcoin/bitcoin/issues/27168#issuecomment-1445884569) option, one can use `-blocksdir` to manage block storage location.
