### ISSUE TITLE
Feature request: alert PR author in case of CI failure

### ISSUE THREAD

**Issue by stickies-v** [bitcoin/bitcoin#27178]
Would be nice to have a means of quickly getting alerted about the CI failing on a PR you authored. It's a bit cumbersome to keep an eye out on it manually, and a freshly created PR typically gets more eyes on it so having it in failing state is a bit of a waste of everyone's time. Creating this issue after brief [IRC discussion](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2023-02-28#1677593689-1677599148;).

I think the main requirements are:
- be able to opt out or easily ignore/hide
- only get a single notification per run, not for every single job failing
- low-touch, easy to maintain

Some potential approaches I see:
1. Use GitHub actions as [recommended](https://cirrus-ci.org/guide/notifications/) by Cirrus CI documention, e.g. here's a [sample email workflow](https://github.com/cirrus-actions/email)
  - can we get this to work so the PR author is notified?
2. Use [`bitcoin-git`](https://github.com/gkrizek/ghi) IRC bot to DM the nickname that corresponds to the PR author's GitHub nickname
  - people with a different username on IRC and GitHub would not get notifications
  - to opt-out, I think users could simply use `/ignore bitcoin-git`?
3. Use [drahtbot](https://github.com/marcofalke/drahtbot) to tag the author as assignee when CI fails (and remove them as assignee upon force push)
  - haven't come up with an elegant way for people to opt-out of this, but arguably it's also the least intrusive option and e.g. could be filtered on the mailbox level?

**Comment by fanquake** [comment]
> enable check suites for the webhook in all repos, please?

Should be available now.

**Comment by fanquake** [comment]
> Use [drahtbot](https://github.com/marcofalke/drahtbot) to tag the author as assignee when CI fails (and remove them as assignee upon force push)

Let's not do this, because it makes assignment potentially useless otherwise.

**Comment by stickies-v** [comment]
Nice! Thank you for adding this to Drahtbot. Looks good, just looked at a PR with a recent CI failure and seeing this:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/69010457/233084088-76c05ac7-6e0a-4da1-b3ec-cb1efe82a945.png">

Don't think this needs anything more - closing.
