### ISSUE TITLE
libevent: event_enable_debug_logging() not to be used after creating event base

### ISSUE THREAD

**Issue by stickies-v** [bitcoin/bitcoin#27182]
Raising this issue on behalf of @hebasto who identified the potential problem as well as dug into the docs.

The `logging` RPC method, through [`UpdateHTTPServerLogging()`](https://github.com/bitcoin/bitcoin/blob/cb40639bdf04bab31bcdceb3bf941e9bade8317a/src/httpserver.cpp#L410-L416) calls the libevent function `event_enable_debug_logging()`. The libevent documentation [states](https://libevent.org/libevent-book/Ref1_libsetup.html) that "You must make any changes to these settings before you call any other part of the Libevent library. If you don’t, Libevent could wind up in an inconsistent state.", and the [headers](https://github.com/libevent/libevent/blob/bcefdbc67a4b18c5dce4420dfa3e83b3dfa16f6f/include/event2/event.h#L791-L806) similarly state that "This is a global setting; if you are going to call it, you must call this before any calls that create an event-base.  You must call it before any multithreaded use of Libevent."

It was introduced in https://github.com/bitcoin/bitcoin/pull/10150, where [reference is made](https://github.com/bitcoin/bitcoin/pull/10150#discussion_r110255587) to the libevent 2.1 release notes that [state](https://github.com/libevent/libevent/blob/2e52bace9f9998826bd3819af328efc8d18decf9/whatsnew-2.1.txt#L269) that "You can now turn on debug logs at runtime using a new function, event_enable_debug_logging().", making this a seemingly safe implementation.

It appears that:
1. Bitcoin Core's usage of `event_enable_debug_logging()` violates the current libevent documentation
2. either there is inconsistency between the libevent 2.1 release notes and the documentation, or the behaviour of `event_enable_debug_logging()` has been changed after 2.1 in a backwards-incompatible way
3. this currently does not seem to be causing any real-world issues

Even though it seems like there are currently no actual problems, it's probably something to be mindful of and ideally resolve, either by disabling toggling libevent debug logging at runtime or verifying that our current usage is indeed safe and will not lead to issues now or in the future.

**Comment by fanquake** [comment]
Looks like, [according to the upstream reply](https://github.com/libevent/libevent/issues/1426#issuecomment-1455189774), this is not actually a problem at all, and the documentation is incorrect/outdated:

> I don't see any possible issues with calling `event_enable_debug_logging` after creating of `event_base`, and basically anytime (except for maybe a TSan warning, since the code is not uses proper atomics, but this should not be a problem, but it can leads to loosing few messages before/after calling `event_enable_debug_logging` if you have concurrent libevent loop)
> That said that you are safe to use it in anytime.

So I think we can close this, and potentially follow up with documentation updates upstream?

**Comment by hebasto** [comment]
> So I think we can close this, and potentially follow up with documentation updates upstream?

Agree.

**Comment by hebasto** [comment]
@stickies-v Thanks for making this issue clear!

**Comment by stickies-v** [comment]
Agreed, looks like we don't need to take any further action. I'll follow up upstream next week. Closed.
