### ISSUE TITLE
Coin Controll for Unconfirmed Outputs

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#27190]
I would like to be able to select unconfined outputs in coin-control.  For example allowing me to make a child-pays-for-parent transaction.

**Comment by pinheadmz** [comment]
I didn't have any trouble spending 0-confirmation inputs using Bitcoin-Qt (on regtest) by enabling the coin selection options


![Screen Shot 2023-03-02 at 11 30 49 AM](https://user-images.githubusercontent.com/2084648/222491819-dca4b237-97df-4a9f-bbf3-62411d82e6b0.png)


![Screen Shot 2023-03-02 at 11 31 12 AM](https://user-images.githubusercontent.com/2084648/222491839-b49070e0-c67e-42a5-916f-05fefa3f2bd5.png)

**Comment by pinheadmz** [comment]
> I think the question is about untrusted inputs, not unconfirmed change

Aha, yes I see those inputs are not listed in the GUI, I can look in to adding this as a feature

**Comment by 1440000bytes** [comment]
> > I think the question is about untrusted inputs, not unconfirmed change
> 
> Aha, yes I see those inputs are not listed in the GUI, I can look in to adding this as a feature

Its not considered safe and I doubt reviewers would ACK it

**Comment by pinheadmz** [comment]
@da2ce7 I recommend you follow https://github.com/bitcoin-core/gui/issues/242 or add your feedback to that issue
