### ISSUE TITLE
Full Support for Spending Untrusted Unconfirmed Outputs

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#27202]
Spending untrusted unconfirmed outputs should be supported and robust.

Key feature:

1. Calculation of the appropriate fee based upon the transaction package.
2. When a dependent transaction is modified, (for example RBF increase), the dependent transaction should be updated appropriately. Users can optionally automate this process, and keep the appropriate signing keys online until the transaction package confirms (as this involves decreasing the transaction fee as the dependent transaction has been replaced with a larger fee version).
3. When a conflicting unconfirmed-transaction package gets a higher fee, the user should be able to compare the transactions, and provided an option to increase the fee, change the funding inputs, or abandon the transaction all-together.
4. When the unconfirmed input goes out-of-scope (a conflicting transaction is confirmed in it's place), the dependent transactions should become "unfunded" and the user will need to select new inputs to fund the transaction, or abandon it.

New concepts:
Unfunded, Partiality, and Fully Funded Transactions, and supporting the lifecycle between these states.

Related Issues:
[policy: allow RBF descendant carveout whenever conflicts exist, #16819 ](https://github.com/bitcoin/bitcoin/issues/16819)
[Enable CPFP via GUI #242 ](https://github.com/bitcoin-core/gui/issues/242)
[Coin Controll for Unconfirmed Outputs #27190](https://github.com/bitcoin/bitcoin/issues/27190)

**Comment by achow101** [comment]
Concept NACK

It's unsafe to spend untrusted unconfirmed outputs. I don't think we should add this, nor does there appear to be interest to add this feature.
