### ISSUE TITLE
Permission to comment on closed PRs

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#27234]
I noticed recently I couldn't comment on two closed PRs. One is #27103 which was closed without an explanation. I wanted to ask why it was closed and whether #27125 might be a replacement for it. The other was my own PR #18608, which I wanted to reopen, but couldn't (even though the branch commit was unchanged at the time), so I opened another PR #27224, and now I can't comment on #18608 to say that it's been replaced by #27224.

I'm guessing the restrictions on comments are an anti-spam measure, so I wonder if there is a technical fix that would allow ordinary project members to comment on closed PRs like these?

FWIW the messages I see on these two PRs are "fanquake locked and limited conversation to collaborators 3 weeks ago" and "DrahtBot locked as resolved and limited conversation to collaborators on Aug 16, 2022"

**Comment by fanquake** [comment]
Yea. Threads are locked to combat spam (and/or when it's clear that the PRs are accidental, wrong repo etc). I've unlocked both now, if you'd like to comment. We can look at if there is some permissions change we can make.

**Comment by achow101** [comment]
> We can look at if there is some permissions change we can make.

IIRC it requires the "write" permission, which only maintainers have.

**Comment by ryanofsky** [comment]
Thanks for unlocking the PRs.

That is a good point that ability to comment on a locked PR is not really useful because relevant people won't be able to respond. Maybe ideally there would be a way to request that DrahtBot unlocks the PR, and then subsequently relocks it after a period of idle time (like a week or month).

Meantime, I guess I can use this issue to request things to be unlocked if the need arises. (At least until this issue itself is locked :grin:)

**Comment by ryanofsky** [comment]
Could a maintainers unlock an old PR of mine #21353? I wanted to add a note on [#21353 `f5ba424c`](https://github.com/bitcoin/bitcoin/pull/21353/commits/f5ba424cd44619d9b9be88b8593d69a7ba96db26) line 3774 that there was an unintented change of behavior in that commit.

**Comment by fanquake** [comment]
> Could a maintainers unlock an old PR of mine https://github.com/bitcoin/bitcoin/pull/21353?

Done.
