### ISSUE TITLE
Adding interprocess onion access instead local ip

### ISSUE THREAD

**Issue by red0bear** [bitcoin/bitcoin#27252]
### Please describe the feature you'd like to see added.

- onion uses 127.0.0.1:9050 and i would like to set it to use unix:path_to_variable used by tor

### Is your feature related to a problem, if so please describe it.

Avoid people try access local ips or 127.0.0.1 with miss configured torcc.

**Comment by red0bear** [comment]
Just run a node using  tor . there is away to set SocksPort to unix ... but bitcoin seems dont have this way to set it . Just in case i resolved ask to be sure if is possible or not do that.

**Comment by pinheadmz** [comment]
Ok I have a working implementation of this: https://github.com/bitcoin/bitcoin/pull/27375

**Comment by pinheadmz** [comment]
I'm just experimenting with the code. If you can review the pull request that will help get move it towards release.

**Comment by red0bear** [comment]
OK ... i dont know how to do it.

**Comment by willcl-ark** [comment]
Oh nice work @pinheadmz! I will help test #27375 too.

I have a small bash script which uses `socat` to pipe between an inet and unix socket, but native support is much better:

```bash
#!/usr/bin/env bash

# default tor sock on debian
socat -v tcp-l:9050,reuseaddr,fork unix:/run/tor/socks 2>&1/dev/null & disown
socat_pid=$!

while true; do
    sleep 5 # check every 5 seconds
    if ! pgrep -x "bitcoind" >/dev/null; then
        # bitcoind not found, terminate socat and exit loop
        kill "$socat_pid"
        break
    fi
done
```

(this can be run by bitcoind using `-startupnotify=/path/to/the/script.sh`)
