### ISSUE TITLE
Blocks remaining falls offscreen with dutch language setting.

### ISSUE THREAD

**Issue by SkybuckFlying** [bitcoin/bitcoin#27266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

It's difficult to see how many blocks remain to be downloaded.

### Expected behaviour

It should be possible to see how many blocks are remaining.

Possible solution1:

1. Make message re-sizeable.
2. Make message screen larger in width.
3. Make message description shorter.
4. Make it possible to copy & paste the text so the user can paste it elsewhere to get a better idea.
5. Make the text scrollable, perhaps by using an edit box instead of label.
6. Display the number of blocks remaining in a special control/edit box so that even if the text is long and overwrites it it will go under it and now over it.

![BlocksRemainingFallsOffScreenWithDutchLanguageSetting](https://user-images.githubusercontent.com/34254801/225494300-739155f5-4ebe-4be3-84a5-bea30d307f32.png)

### Steps to reproduce

Method 1:
1. Install bitcoin on a dutch Microsoft Windows version.
2. Start bitcoin to download new blocks.

Method 2:
1. Change bitcoin language settings to dutch.
2. Restart bitcoin.
3. Try and download new blocks.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

22.0

### Operating system and version

Windows 7 Home Edition

### Machine specifications

Toshiba Laptop L670

**Comment by fanquake** [comment]
Please move this issue to the GUI repo: https://github.com/bitcoin-core/gui.

**Comment by SkybuckFlying** [comment]
Thx. Done. With one additional screenshot ! ;)
