### ISSUE TITLE
Increase fuzz coverage in the wallet

### ISSUE THREAD

**Issue by dergoegge** [bitcoin/bitcoin#27272]
The wallet has (almost) no coverage: https://maflcko.github.io/b-c-cov/fuzz.coverage/src/wallet/index-sort-l.html. We should change that!

Issues like https://github.com/bitcoin/bitcoin/pull/27271 should be quite easy for high level fuzz targets to find.

(For people that are interested but unfamiliar with the wallet (like me): I suspect that looking at the unit tests could be helpful for figuring out where to start)

**Comment by brunoerg** [comment]
I'm working on increasing fuzz coverage in the wallet. Just to track:

- #27647 - for `wallet/fees` stuff
- #27585 - add more coverage for coin selection

**Comment by brunoerg** [comment]
> Was https://github.com/bitcoin/bitcoin/pull/28578 supposed to be a regression test for this? cc @brunoerg

No since the issue is not related to the `ScriptPubKeyMan` stuff.

**Comment by dergoegge** [comment]
@brunoerg is planning on opening a new issue which will keep better track of the progress on wallet fuzzing.
