### ISSUE TITLE
Inappropriate Spam Flag

### ISSUE THREAD

**Issue by Bhaney44** [bitcoin/bitcoin#27293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I made [PR 27042](https://github.com/bitcoin/bitcoin/pull/27042) with a dataset I built as a product of meticulous labor. I think it is relatively clear that the dataset adds value to Bitcoin as an information technology by provided data for research and development. However, the PR was flagged as spam and comments were blocked. 

If there is a valid reason for why the PR was rejected, I think that is fine. However, the PR was certainly not spam.

### Expected behaviour

I expected the PR to merged.

### Steps to reproduce

I am not sure there is a way to reproduce the bug because it is on the maintainers Bitcoin Core. I am not sure whether there is an automated system that created this bug or whether it is the product of human error. @andrewchow

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

Bitcoin Core

### Operating system and version

Mac

**Comment by fanquake** [comment]
Unfortunately for you, your PR looked exactly like spam:
* Nondescript PR title
* No PR description
* Completely unmergable, nonsense commit list.

Putting that aside. A "CSV dataset of blockheaders" is obviously not something that belongs in this repository, or that we would want to merge.

**Comment by Bhaney44** [comment]
> Unfortunately for you, your PR looked exactly like spam:
> 
> * Nondescript PR title
> * No PR description
> * Completely unmergable, nonsense commit list.
> 
> Putting that aside. A "CSV dataset of blockheaders" is obviously not something that belongs in this repository, or that we would want to merge.

Alright. No problem. It was my honest attempt to add real value to the network. Thank you for your time and consideration.
