### ISSUE TITLE
issue with bug reports - censorship - issue deletion

### ISSUE THREAD

**Issue by visualbasic6** [bitcoin/bitcoin#27292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

https://github.com/bitcoin/bitcoin/issues/27291

wat

more info: https://www.reddit.com/r/hacking/comments/11xlis0/bitcoin_dos_github_issue_with_attack_code_written/

![image](https://user-images.githubusercontent.com/38997186/226676383-2a108fae-1ce2-4573-bc8e-e03f0d85a1a5.png)

![image](https://user-images.githubusercontent.com/38997186/226676286-f5f993e5-e473-4785-8118-1eb335b7ffb0.png)

### Expected behaviour

i expected the core team to not delete a dos bug issue on github

### Steps to reproduce

i'm probably reproducing it right now

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

dwai

### Operating system and version

dwai

**Comment by visualbasic6** [comment]
much open source very cypherpunk mucho decentralization

**Comment by fanquake** [comment]
You must have missed: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md.

**Comment by visualbasic6** [comment]
you must have missed where idc - but thanks
