### ISSUE TITLE
Millisecond log timestamp (option)

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#27313]
### Please describe the feature you'd like to see added.

For some events, like two blocks at the same height being announced by multiple peers at the same time, it's nice to have millisecond precision on the log entries.

### Is your feature related to a problem, if so please describe it.

E.g. one of the ForkMonitor nodes saw two blocks at height 782,129 within the same second: https://twitter.com/BitMEXResearch/status/1638875082943520769

Other nodes saw those blocks in the opposite order.

### Describe the solution you'd like

Something like `-logtimestampprecision=` which would `second` by default, with `millisecond` as an option.

Log entries would look like:

```
2023-03-22T15:53:29Z
```

### Describe any alternatives you've considered

A more fancy solution would allow a custom date formatter.

**Comment by fanquake** [comment]
Does `-logtimemicros` not work

**Comment by Sjors** [comment]
Ah oops, I only searched for documented options. Yes that works.

**Comment by Sjors** [comment]
Might be worth promoting this from `OptionsCategory::DEBUG_TEST` to `OptionsCategory::OPTIONS`, since it's useful beyond debugging the software.
