### ISSUE TITLE
ci: Cleanup ci/test/01_base_install.sh

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27321]
### Motivation

Currently `ci/test/01_base_install.sh` has the following issues:

* Two names to alias `bash -c`: `CI_EXEC_ROOT`, and `CI_EXEC`
* The aliases are not needed, as explained in the comment in the file

Thus, they should be removed, or at least de-duplicated. The whole file is already run in bash, so the only place where `bash -c "..."` is needed is in the `apt install` step to properly pass the packages string with spaces.

### Possible solution

* Remove or de-duplicate `CI_EXEC_ROOT`, and `CI_EXEC`

### Useful Skills

* Bash
* Docker or Podman
* The Bitcoin Core `./ci/` system (see Readme there). For testing I recommend to set up a fresh Linux VM.

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by Ayush170-Future** [comment]
Hello @MarcoFalke!
I'm new to Bitcoin Core development as well as Bash scripting. But, based on the requirements and the script, I believe I can tackle this.

I only have a few questions:
1) I discovered other files in the test directory, such as ci/test/04_install, also contain the CI_EXEC_ROOT and CI_EXEC alias. So, are they also to be modified?

2) After reading your comment in the script, I believe I can just remove the CI_EXEC_ROOT and CI_EXEC parts of different commands in the script and it will run just fine, as it is already run in bash. Except, for the apt install parts where I have to remove the alias and replace it with bash -c, as you said. 
So, am I thinking in the right place?

I can start working on this from Monday. So, if this is urgent or anyone else thinks they are more qualified than me to work on this, I would love to do a code review on their PR as well. I just want to get started and be involved.

**Comment by vstoyanov** [comment]
Hello,

I think I just completed this one. My understanding was that it only covers 01_base_install.sh and not instances after test/04_install.sh as from there on it also redefines $PATH and current directory.

Best,
Vasil Stoyanov

**Comment by Ayush170-Future** [comment]
Hey @vstoyanov!
No problem at all. You seem to understand this far better than I do, so no worries. I will at the very least do a code review for your PR (as I mentioned in my comment). And will look for some other issues to contribute to.

P.S. Thanks for clearing my test/04_install.sh doubt. I got a little confused there.

**Comment by vstoyanov** [comment]
@Ayush170-Future Thanks for understanding. Also thanks for the complement, but maybe this is not the case :) - I got to the point where `$CI_BASE_PACKAGES `and `$CI_PACKAGES` should pass lint. This means either convert them to bash arrays or use SuppressWarnings to switch lint of. The first seems much cleaner to do, the second is a smaller change and I am confused as to what to do with that.

In about 45 minutes I will push the array conversion in a second commit I could squash later if we decide to go that way. Otherwise we could just Suppress Warnings for `  ${CI_RETRY_EXE} dnf -y --allowerasing install "${CI_BASE_PACKAGES[@]}" "${PACKAGES[@]}"
`

**Comment by Ferrydh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vstoyanov** [comment]
False alarm. The `bash -c` hack also worked for dnf the same way it did for apt, so now it is both not a big change and has no SuppressWarnings BS. I could still push the arrayification of $PACKAGES and $CI_BASE_PACKAGES though?

**Comment by Ayush170-Future** [comment]
I guess SuppressWarnings was not a good practice. It's great that you found a workaround.

Instead of giving package strings as an array, I believe the bash -c technique should be sufficient here. @MarcoFalke, I think you wanted it that way as well.
