### ISSUE TITLE
Bitcoin-qt Sign Message Feature -- Put header/footer around message.

### ISSUE THREAD

**Issue by monohydroxy** [bitcoin/bitcoin#2737]
It seems to me the Bitcoin-qt 'Sign Message' feature is a little harder to use than it should be.  Once all of the fields are filled in, it would be more convenient to output a block of text that contains all of the information that should be pasted in to a message.  Also a simple parser that expects this format should be put into the Verify Message side of things.

It's worth a note that Armory and MultiBit are working on this feature.  It would be nice if they all were compatible.

Here's an example (taken from a PGP Signed message):

-----BEGIN BITCOIN SIGNED MESSAGE-----
Address:  1Bitcoinasdfasdfsadfsadfsadf

Because anyone can claim to be me. There's no validation of the user
name or email address when someone posts a comment. While I do try to
remove imposters, some may slip through. By signing my comments using
this technique, anyone can independently verify that I was the author of
the message by validating the signature.
-----BEGIN BITCOIN SIGNATURE-----
Version: Bitcoin-qt (1.0)

iD8DBQFFxqRFCMEe9B/8oqERAqA2AJ91Tx4RziVzY4eR4Ms4MFsKAMqOoQCgg7y6e5AJIRuLUIUikjNWQIW
-----END BITCOIN SIGNATURE-----

**Comment by laanwj** [comment]
Closing this, as it is extremely unlikely the signed message format will be changed anymore after all those years.

If you do intend to do this, it would make sense as a BIP proposal, especially as the goal is to coordinate between different software.
