### ISSUE TITLE
Add parallelism for downloading the blockchain

### ISSUE THREAD

**Issue by Farxial** [bitcoin/bitcoin#27442]
Please add parallelism (at least, multithreading; multithreading + some kind of clustering are better) for downloading blockchain by client/wallet (required by `getblocktemplate`).
**The speed of downloading the blockchain of Bitcoin is very slow, so much time is required, it's absolutely awful. And the further, the worse.**
As I can understand, it happens because of nature of blockchain processing: first, client must check block N contents (transactions), then it can proceed to check of block N+1.
But we can behave like modern CPUs branch predictors. Why not? Just pretend block N is correct for thread M and let thread M+1 check block N+1. Then let thread M+1 pass necessary information to thread M+2 for checking block N+2. And so on. So all threads can check it's blocks, doing CPUs utilization. Threads can be reused as they become free. Just break processing at some points and do rollback, if some previous blocks (N, N+1, ...) gets corrupted.
As far I can see by CPUs usage, Bitcoin Core/Wallet does not behave like that. My Internet connection is not such slow and unstable; I once experimented with connection limit options, it didn't work for me.
The behavior I suggest has some performance risk, so it can be explicitly controlled by the user with launch option[s] (command line, ...).
<details>
<summary>A little spoiler ;)</summary>
It wouldn't be a problem at all, if the user could just download the blockchain (full or pruned) from some popular (so popular to be found) websites he trust.

(I aware about the security considerations, but this is not a issue if the user just wants to try mining or something.)
</details>

**Comment by pinheadmz** [comment]
This might be a better question for https://bitcoin.stackexchange.com, I think if you search that knowledgebase for topics like `assumevalid` and `headers first sync` (download blocks from multiple peers) you'll find that IBD already has many optimizations of the kind you are describing. Assume valid in particular is *optional* because it skips validation on most blocks in the chain "even though" that carries a security compromise with it.

**Comment by Farxial** [comment]
@pinheadmz
Sometime I tried `assumevalid`, but it didn't help me. May be I tried wrong? OK then, I will try this on next full synching, if you insist. _Does this work with **prune** blockchain synching?_
I can't find how to download from multiple peers on request `headers first sync`. Can you tell a launch option, please?
And, of course, it would be nice to find such an option in the output of `bitcoind --help`.

@sipa
I see...

Thanks for the info both of you.

**Comment by pinheadmz** [comment]
By default, the first `751565` blocks are assumed valid, without any user setting:

https://github.com/bitcoin/bitcoin/blob/db720b5a703c90625fa7a4773bd2db5672427cbe/src/kernel/chainparams.cpp#L107

Parallel download is also the default, see `FindNextBlocksToDownload()`:

https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L1298
