### ISSUE TITLE
Bitcoin Core v22.0.0 crashes while syncronizing the first local wallet transaction

### ISSUE THREAD

**Issue by ilbarillo2014** [bitcoin/bitcoin#27533]
Hi all,
I'm running Bitcoin Core v22.0.0 and I'm syncronizing all the full blocks.
When it arrives exactly at processing the transaction when I received on 3-01-2018 my first small amount of bitcoin in my wallet, it crashes.

In debug.log I can see only this last message:
2023-04-26T19:01:29Z UpdateTip: new best=000000000000000000667c6320fa787dbd80768f3a9babcf7d7b5b36956f918b height=502410 version=0x20000000 log2_work=87.792928 tx=288732313 date='2018-01-03T19:34:24Z' progress=0.364601 cache=135.9MiB(997593txo)

No errors into the log.
Restarting Bitcoin Core, it crashes every time at the same point.

What do you suggest to check ? Is there a problem updating/accessing my local encrypted wallet to register the transaction ?
Thanks in advance for your support

**Comment by pinheadmz** [comment]
Could you try again with the latest release? (24.0.1) Also, what is the story with this wallet? Was it created with Bitcoin Core back in 2018? How did you load it into your v22.0 node?

**Comment by ilbarillo2014** [comment]
Problem solved installing 24.0.1.
THANKS !
