### ISSUE TITLE
Cannot disable RBF with walletrbf configuration option

### ISSUE THREAD

**Issue by karask** [bitcoin/bitcoin#27532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I am creating a tx using:

$ bitcoin-cli createrawtransaction '''                                         
[{"txid":"7b6412a0eed56338731e83c606f13ebb7a3756b3e4e1dbbe43a7db8d09106e56","vout": 1}]
''' '''{"mtVHHCqCECGwiMbMoZe8ayhJHuTdDbYWdJ": 0.00004}'''
0200000001566e10098ddba743bedbe1e4b356377abb3ef106c6831e733863d5eea012647b0100000000`fdffffff`01a00f0000000000001976a9148e48a6c5108efac226d33018b5347bb24adec37a88ac00000000

The nSequence (highlighted above) has RBF enabled. This is the default behaviour. I have stopped the node, added `walletrbf=0` to `bitcoin.conf` in order to disable RBF, restarted, but it does not work (result of `createrawtransaction` is identical). 

### Expected behaviour

I expected the nSequence field to be `ffffffff`.

### Steps to reproduce

$ bitcoin-cli createrawtransaction '''
[{"txid":"7b6412a0eed56338731e83c606f13ebb7a3756b3e4e1dbbe43a7db8d09106e56","vout": 1}]
''' '''{"mtVHHCqCECGwiMbMoZe8ayhJHuTdDbYWdJ": 0.00004}'''

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v24.0.1

### Operating system and version

Linux, Tuxedo OS 2.0.2

### Machine specifications

20 × 12th Gen Intel® Core™ i7-12700H
62,5 GiB of RAM

**Comment by furszy** [comment]
`createrawtransaction` does not interact with the wallet. Use the `replaceable` arg to enable/disable RBF.
```
createrawtransaction <inputs> <outputs> <locktime> <replaceable>
```

**Comment by karask** [comment]
Ah, missed that.  Thanks!
