### ISSUE TITLE
coreTORwin64.zip

### ISSUE THREAD

**Issue by Sataur** [bitcoin/bitcoin#27567]
### Please describe the feature you'd like to see added.

There should be additional/optional bitcoin-24.0.1-[win](https://bitcoincore.org/en/download/)64.zip with TOR

### Is your feature related to a problem, if so please describe it.

Some users may be confused by that browser:
_So, you are trying to use the bundled Tor from Tor [Browser](https://twitter.com/spectre135/status/1284452766186909700) rather than a dedicated Tor daemon?  This is not recommended._

### Describe the solution you'd like

_These packages are intended for developers who need to [bundle](https://www.torproject.org/download/tor/) tor with their applications._

_Do not use the links provided by GitHub, rather use the above download links, they are guaranteed to be..._

### Describe any alternatives you've considered

_Note on 2022: This project that executes Tor service on Windows with the above interface, and display an icon on the taskbar is called Tor Vidalia Bundle and it's not maintained anymore, deprecated and not recommended. To see how to configure Tor service on **Linx** or.._

**Comment by pinheadmz** [comment]
This is unlikely to be fixed in Bitcoin Core, users can install and update Tor on their own and that is outside the responsibility of this project.
