### ISSUE TITLE
CPU DoS on mainnet in debug mode

### ISSUE THREAD

**Issue by ajtowns** [bitcoin/bitcoin#27586]
I've been seeing 100% cpu usage on one of my bitcoind nodes recently, with transactions taking >60s to be accepted into the mempool. Digging into it, the problem seems to be `BOOST_MULTI_INDEX_ENABLE_SAFE_MODE`  which was introduced in #24395. That results in iterator destruction taking O(n) time (in the number of other active iterators on the same multi-index) in the worst case, rather than O(1) time, due to keeping the iterators in a [singly linked list](https://www.boost.org/doc/libs/1_82_0/boost/multi_index/detail/safe_mode.hpp):

```
 * Iterators are chained in a single attached list, whose header is
 * kept by the container. More elaborate data structures would yield better
 * performance, but I decided to keep complexity to a minimum since
 * speed is not an issue here.
```

Speed does become an issue here though, as we keep an iterator around for every mempool entry (in `vTxHashes`).

This isn't always a problem: presumably in the normal case new iterators are added to the head of the list then removed while they're still roughly at the head of the list, giving O(1) timing; but somehow having a full mempool (and hence TrimToSize actually doing things) triggers worst case behaviour?

**Comment by darosior** [comment]
I experienced this as well.

**Comment by ArmchairCryptologist** [comment]
Been seeing this on my 24.0.1 public nodes as well, it's not 100% CPU usage as such, but a single CPU core is spinning at 100%. One 24.0.1 node with listen=0 did not seem affected.

I noticed that after a node restart, the CPU usage went back to normal (and is still normal after a day) even though the mempool was loaded from disk - though it might be because it's not entirely full.

**Comment by darosior** [comment]
Just to confirm, yours was in debug mode as well? Otherwise it'd be concerning.

-------- Original Message --------

**Comment by ArmchairCryptologist** [comment]
> Just to confirm, yours was in debug mode as well? Otherwise it'd be concerning.

My nodes are NOT in debug mode, no. I run four public nodes (24.0.1) with different server hosts, and all four of them were spinning a CPU core at 100% and experiencing slowness with block/transaction handling when I checked them yesterday, two to the point where they started occasionally dropping connectivity to my private nodes. Like I mentioned, one 24.0.1 node which does not accept incoming connections (but is connected to untrusted nodes) did not have this issue. The other private nodes still run 23.0.0 and also do not have any issues, though these only connect through my own public nodes so they aren't directly exposed to untrusted nodes.

**Comment by ajtowns** [comment]
> PS: These nodes do **not** run in debug mode.

With the issue I described here patched around, I see a different problem that also results in b-msghand using ~100% of a single cpu. It seems to be spent in `make_heap` in `net_processing.cpp` which in turn seems to be due to the internal queues for which txs need to be INVed to which peers growing much too large (I've observed >60,000 entries in each of 6 peers, eg). It seems to be exacerbated by a combination of inbound peers that aren't really relaying transactions (so the queue is only being cleared when we send things, so effectively half or a third of the rate compared to if they were sending INVs as well) and other peers sending txs to us at a rate much faster than the network can actually support.

That's a different bug though, so I'll open it up as a different issue after getting some better data...

**Comment by ajtowns** [comment]
Oh, if anyone wants to mitigate the `make_heap` thing; I think something like:

```sh
$ bitcoin-cli getpeerinfo | jq -j '.[] | (.bytessent_per_msg.inv, " ", .bytesrecv_per_msg.inv, " ", .addr, "\n")' | grep ' null ' | sort -n
```

should list the nodes where you're sending lots of inv data, without receiving anything in return. Doing a temporary "setban" on those to disconnect them will clear their inv queue and should speed things up temporarily.

**Comment by ArmchairCryptologist** [comment]
Of the four nodes, the one that was restarted on May 6th is now back to spinning 100% of a CPU core (60% average CPU usage on a two-core VM the last hour) while the three that were restarted yesterday are also seeing high CPU usage but not 100% all the time (between 30% and 38% average CPU usage on a two-core VM), so it's building back up relatively quickly. I also verified that the mempool is not fully committed (usage is at 251217552).

There were around 15 peers with bytessent_per_msg.inv over 100000 without any received ones, but even after doing setban on them and verifying that they have been disconnected, the CPU usage did not drop noticeably if at all. This is probably because the node has 180 connected peers, and 140+ of those have both bytessent_per_msg.inv and bytesrecv_per_msg.inv over 100000, so disconnecting 15 of them for not sending any probably doesn't do much..

Based on what you say about it being a different bug I assume that it is not an issue introduced with 24.0, but I reverted one of the nodes to 23.0.

**Comment by willcl-ark** [comment]
> What is debug mode? A binary compiled with `--enable-debug` option or `debug=1` saved in bitcoin.conf?
> 
> 

Compiled with `--enable-debug`

**Comment by disappointed72** [comment]
Same issue with 24.0.1 node today and went back to normal after daemon reload. My node do NOT run in debug mode too.

**Comment by poiuty** [comment]
I have the same problem. `bitcoind` started using 100% cpu (single thread) on my servers. I used the binary from https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz

<img src="https://img.poiuty.com/a/3c/c68204e690ae2d605cfd60e03eee0f3c.jpg">

Built bitcoind from source (v24.0.1.tar.gz). Works fine for an hour now.
```
./configure --without-gui --disable-zmq --disable-wallet
```

<img src="https://img.poiuty.com/a/7b/5234d849fcf5248c4a1adaf5011bc57b.jpg">

**Comment by golden-guy** [comment]
> Same issue with 24.0.1 node today and went back to normal after daemon reload. My node do NOT run in debug mode too.

Same here using the 24.0.1 binaries NOT running in debug mode  since yesterday. (Binaries from https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz)  I didn't restart the node, but used the setban approach as pointed out here https://github.com/bitcoin/bitcoin/issues/27586#issuecomment-1537784340

Since then, the single core load has decreased to 45% without restart and made the node cli and RPC calls responsive again, regardless of mempool allocation peaking at 300MB. So this has brought relief to some extent.

Using this command to identify those peers: `bitcoin-cli getpeerinfo | jq -r '.[] | if (.bytessent_per_msg.inv > 100000 and .bytesrecv_per_msg.inv == null) then .addr else empty end'`

**Comment by Sjors** [comment]
The above command on my listening node (running a mess of commits on top of master from ~March) returns localhost (probably my mempool instance) plus about 11 other peers. CPU use looks normal to me, it's not compiled with --enable-debug nor does it run with -debug. Last restart was 3 days ago.

**Comment by ArmchairCryptologist** [comment]
Just to confirm, after a day or so I'm seeing the same kind of CPU load increasing over time with the node I downgraded to 23.0.0, so this other issue probably was not introduced with 24.0.1.

Reducing maxconnections to a low-ish number (100 or less) seems to at least significantly delay the problem, though I can't say yet whether it'll mitigate it entirely.

> I didn't restart the node, but used the setban approach as pointed out here https://github.com/bitcoin/bitcoin/issues/27586#issuecomment-1537784340

That comment was actually a reply to a comment by @ajtowns who pointed that out as a possible mitigation to a potential issue he identified, but said comment seems to have been removed (too much information?), so it probably seems somewhat out-of-context.

**Comment by Sjors** [comment]
@ArmchairCryptologist do you have `peerbloomfilters` on?

**Comment by ArmchairCryptologist** [comment]
> @ArmchairCryptologist do you have peerbloomfilters on?

Nope. The nodes are pretty much running with the default settings except for maxconnections.

**Comment by theStack** [comment]
For the reporters using [htop](https://htop.dev/) to analyze CPU usage (which is the case for at least @poiuty @gits7r, according to the posted screenshots): could you go to the display settings (reachable via key F2) and activate "tree view" and the global option "show custom thread names"? This would show the CPU usage per thread, which could be interesting for further investigation, e.g.:

![image](https://github.com/bitcoin/bitcoin/assets/91535/3b20748f-86db-4f4c-a185-496135d3b5ec)

(FWIW I'm running a listening pruned node on some quite lame dual-core virtual server, have rarely seen more than 10-15% CPU usage the last few days; will tinker around with higher maxmempool/maxconnections settings to see if I can reproduce the issue reported above).

**Comment by ajtowns** [comment]
I think #27610 should improve the non-debug cpu usage in b-msghand. Both commits should cleanly cherry-pick for on top of v24.x; and the first commit (the "CompareDepthAndScore" one) should cleanly cherry-pick for v23.x.

**Comment by ayeowch** [comment]
> Using this command to identify those peers: `bitcoin-cli getpeerinfo | jq -r '.[] | if (.bytessent_per_msg.inv > 100000 and .bytesrecv_per_msg.inv == null) then .addr else empty end'`

Someone posted https://news.ycombinator.com/item?id=35824998 linking to a DoS script https://github.com/visualbasic6/drain/blob/c8373b55d83832f95fb0a77aca56436adeffb58d/drain-btc.py a day before this issue. It's possible someone may be using the script targeting public nodes. 

Check your `bytessent_per_msg.headers` for anomalous hits. I'm seeing `bytessent_per_msg.headers=2542689711` and 100% CPU util on `b-msghand` thread when testing the DoS script for 10s with single thread on my localhost node.

**Comment by ArmchairCryptologist** [comment]
> It's possible someone may be using the script targeting public nodes.

FWIW, I was not seeing any ridiculous bytessent_per_msg.inv numbers on any of my nodes. In fact the highest counts on all of my public nodes is my private nodes, but not by much.

A notable change happened yesterday (May 9th) around 14:25 UTC where the CPU load on all the public nodes dropped drastically at the same time, and they all look normal at present. The high-fee BRC-20 token spam we were seeing also appear to have quieted down a bit, so it seems likely that the issues were simply related to that. Unless it starts back up it might be hard to diagnose this further without artificially generating a similar traffic pattern.

Incidentally, the command originally provided by @ajtowns which lists the peer addresses with the inv numbers was:

`bitcoin-cli getpeerinfo | jq -j '.[] | (.bytessent_per_msg.inv, " ", .bytesrecv_per_msg.inv, " ", .addr, "\n")' | grep ' null ' | sort -n`

**Comment by Sjors** [comment]
My highest `bytessent_per_msg` is 65 MB (mostly to the university nodes and Bitnodes), i.e. a lot less than the 2.5 GB @ayeowch is seeing. CPU still calm. My node has 114 inbound connections (and 10 out).

**Comment by Sjors** [comment]
@ayeowch running that particular script against a modest Intel i5-8400 with 6 cores, either from another computer on the LAN or from the machine itself, I don't see any noticeable CPU difference (compared to all the other stuff its running). Even when downloading 10GB of headers in a few minutes, which is probably a faster download rate than you experienced given the total (though you tally disconnected peers too I suppose).

**Comment by willcl-ark** [comment]
FWIW I am also seeing some sustained high CPU usage on a listening (non debug mode) 24.0.1 node from the `b-msghand` thread:

![htop ~_001](https://github.com/bitcoin/bitcoin/assets/6606587/93b2d011-8af5-4b0e-81d5-5bda540cfbc8)

I am used to seeing this thread at ~1% on this machine:

![htop ~_002](https://github.com/bitcoin/bitcoin/assets/6606587/8f31aa77-98ea-4aac-9ed9-ba6a466de9cd)


I also have a number of these "hungry" peers:

```fish
bitcoin in ~ took 53s ➜ bitcoin-cli getpeerinfo | jq -j '.[] | (.bytessent_per_msg.inv, " ", .bytesrecv_per_msg.inv, " ", .addr, "\n")' | grep ' null ' | sort -n
2501 null xx.xx.xx.xx:xxxx
6379589 null xx.xx.xx.xx:xxxx
19839661 null xx.xx.xx.xx:xxxx
24468696 null xx.xx.xx.xx:xxxx
38336458 null xx.xx.xx.xx:xxxx
62889263 null xx.xx.xx.xx:xxxx
79513965 null xx.xx.xx.xx:xxxx
80910412 null xx.xx.xx.xx:xxxx
80972609 null xx.xx.xx.xx:xxxx
82147824 null xx.xx.xx.xx:xxxx
343710563 null xx.xx.xx.xx:xxxx
484505648 null xx.xx.xx.xx:xxxx
484552023 null xx.xx.xx.xx:xxxx
484575864 null xx.xx.xx.xx:xxxx
```

This hardware usually deals with `bitcoind` pretty easily and has been running with maxconnections for a while:

```fish
bitcoin in ~ ➜ bitcoin-cli getnettotals
{
  "totalbytesrecv": 49382137900,
  "totalbytessent": 1290284641863,
  "timemillis": 1683631908883,
  "uploadtarget": {
    "timeframe": 86400,
    "target": 0,
    "target_reached": false,
    "serve_historical_blocks": true,
    "bytes_left_in_cycle": 0,
    "time_left_in_cycle": 0
  }
}
```

I will cherry-pick https://github.com/bitcoin/bitcoin/pull/27610 on top of 24.0.1 and see how it fares.

**Comment by josibake** [comment]
> > Using this command to identify those peers: `bitcoin-cli getpeerinfo | jq -r '.[] | if (.bytessent_per_msg.inv > 100000 and .bytesrecv_per_msg.inv == null) then .addr else empty end'`
> 
> Someone posted https://news.ycombinator.com/item?id=35824998 linking to a DoS script https://github.com/visualbasic6/drain/blob/c8373b55d83832f95fb0a77aca56436adeffb58d/drain-btc.py a day before this issue. It's possible someone may be using the script targeting public nodes.
> 
> Check your `bytessent_per_msg.headers` for anomalous hits. I'm seeing `bytessent_per_msg.headers=2542689711` and 100% CPU util on `b-msghand` thread when testing the DoS script for 10s with single thread on my localhost node.

I haven't tested this, but can't you mitigate the damage done by the script by setting `-maxuploadtarget` ?

**Comment by ArmchairCryptologist** [comment]
> I presume this is still an issue?

I haven't seen any notable issues since the BRC-20 spam died down a few days ago, one node with 412 incoming connections is currently sitting at ~16% average CPU usage.

> I'm also seeing the same issue.. The load average suddenly increased from 0.25 to 1+.

You probably need to restart the node to clear it up after it's started spinning, a few days ago I had one node still spinning even after dropping to <80 connections due to timeouts/disconnects.

**Comment by ajtowns** [comment]
Maybe we can move the boost option into a new `--enable-slow-debug` option, and just enable that for fuzzing and perhaps one of the CI tasks?

```diff
diff --git a/configure.ac b/configure.ac
index cbbf8d6172..fbf7a72e7b 100644
--- a/configure.ac
+++ b/configure.ac
@@ -306,6 +306,13 @@ AC_ARG_ENABLE([debug],
     [enable_debug=$enableval],
     [enable_debug=no])
 
+dnl Enable slow debug
+AC_ARG_ENABLE([slow-debug],
+    [AS_HELP_STRING([--enable-slow-debug],
+                    [use compiler flags and macros suited for debugging that may cause slowdown (default is no)])],
+    [enable_slow_debug=$enableval],
+    [enable_slow_debug=no])
+
 dnl Enable different -fsanitize options
 AC_ARG_WITH([sanitizers],
     [AS_HELP_STRING([--with-sanitizers],
@@ -1482,7 +1489,7 @@ if test "$use_boost" = "yes"; then
   AX_CHECK_PREPROC_FLAG([-DBOOST_NO_CXX98_FUNCTION_BASE], [BOOST_CPPFLAGS="$BOOST_CPPFLAGS -DBOOST_NO_CXX98_FUNCTION_BASE"], [], [$CXXFLAG_WERROR],
                         [AC_LANG_PROGRAM([[#include <boost/config.hpp>]])])
 
-  if test "$enable_debug" = "yes" || test "$enable_fuzz" = "yes"; then
+  if (test "$enable_debug" = "yes" && test "$enable_slow_debug" = "yes") || test "$enable_fuzz" = "yes"; then
     BOOST_CPPFLAGS="$BOOST_CPPFLAGS -DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE"
   fi
```
