### ISSUE TITLE
provide optional RPC parameter to not scramble sendmany transactions

### ISSUE THREAD

**Issue by embiimob** [bitcoin/bitcoin#27592]
### Please describe the feature you'd like to see added.

passed bitcoin core 16.X  the order of sendmany transactions is scrambled via RPC command forcing projects that utilizing the order of transactions to use older wallets.  

### Describe the solution you'd like

add an optional parameter to the sendmany RPC command that allows for the sendmany transaction to work as it did before.   giving the option to scramble or not to scramble the order of a sendmany transaction back to bitcoin users.

**Comment by furszy** [comment]
If your project requires control over the tx, could move to something like:
```python
raw_tx = wallet.createrawtransaction(inputs=[], outputs=["add outputs here"])
funded_tx = wallet.fundrawtranasction(raw_tx)
signed_tx = wallet.signrawtransactionwithwallet(funded_tx['hex'])
wallet.sendrawtransaction(signed_tx['hex'])
```

**Comment by willcl-ark** [comment]
There doesn't seem to be much action on implementing this feature.

Please feel free to submit a pull request if this is something that you still want.
