### ISSUE TITLE
rpc: Allow importing wallets by data instead of by filename

### ISSUE THREAD

**Issue by brandonpille** [bitcoin/bitcoin#27597]
### Please describe the feature you'd like to see added.

Right now we can only import wallets by filename. This means you can only execute that rpc if you are executing it from the system where the bitcoin node is running. But it could be that you are sending the rpc request from outside the node. In that case you don't have access to the file system. So it would be handy to allow passing the content of a wallet dump file instead and also allowing dumping the content not in a file but in the rpc result. 

It might be a good idea to check for other cases where the same is being done.

**Comment by kouloumos** [comment]
Is there a specific reason that you need to pass around the whole wallet? You might be able to do a work-around with descriptor wallets (default wallet type since [23.0](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-23.0.md#wallet)) using the `{list,import}descriptors` RPCs.

**Comment by kouloumos** [comment]
I might be missing something here, as I cannot understand how your latest question is related to your initial feature request.
It is common for backups to be in files, hence importing/restoring from a file. I understand the over-the-wire scenario, but if there is no strong use-case for such a feature, it makes it more difficult to gather interest.

Note that `importwallet` and the related `dumpwallet` RPC are only compatible with legacy wallets, and as there is a [proposed timeline for their removal](https://github.com/bitcoin/bitcoin/issues/20160), it is not very likely for improvements to happen. If your use-case is not legacy-wallet related, you should probably be looking at `backupwallet` and `restorewallet` RPCs.

**Comment by pinheadmz** [comment]
> No not specifically. I was just wondering why there is an import_wallet rpc that accepts a filename where the file is on the system itself.

@brandonpille is this still an issue for  you?

**Comment by brandonpille** [comment]
No it's ok
