### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by Jackwumingjie** [bitcoin/bitcoin#27617]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

<img width="1018" alt="企业微信截图_958a8dcb-6942-407e-a01b-14eee3df3e14" src="https://github.com/bitcoin/bitcoin/assets/39093109/8059bcd8-967f-41b9-9eb6-3a9425f97b2e">
I build the node with ubuntu20.04 and 24.0.1. But some api return the error as the picture. The run command "bitcoind -datadir=/data2/.btc/data -rpcuser="xxxx" -rpcpassword="xxx" -server -txindex=1"

**Comment by fanquake** [comment]
Did you compile with wallet support?

**Comment by kouloumos** [comment]
You are probably missing the SQLite or BDB dependency to compile the wallet.  When you run `./configure` make sure that summary (that's in your `config.log`) shows `with wallet = yes`.

If that's the case, you'll need to install the dependencies and then recompile following the steps you done before (`./configure`, `make`, etc.)

See also https://github.com/bitcoin/bitcoin/issues/26193.

**Comment by Jackwumingjie** [comment]
@fanquake I have installed the sqlite, but other error display:
<img width="1078" alt="image" src="https://github.com/bitcoin/bitcoin/assets/39093109/a989acd1-9867-4dd4-b2c2-e1ebc9822660">

**Comment by willcl-ark** [comment]
@Jackwumingjie now that you have the wallet compiled in the error message is telling you what to do to: i) either create a wallet (if you don't have one already) or ii) load a wallet (if you do have one).

If you run `bitcoin-cli help createwallet` or `bitcoin-cli help loadwallet` you will find more detailed instructions on how to use these RPCs.

Also see https://github.com/bitcoin/bitcoin/blob/master/doc/managing-wallets.md for more information.
