### ISSUE TITLE
Keep it simple

### ISSUE THREAD

**Issue by adastreamer** [bitcoin/bitcoin#27618]
### Please describe the feature you'd like to see added.

Dear community,

On my opinion Bitcoin network should not contain anything except BTC transfer transactions. BTC network is absolutely organic and all economic rules are totally balanced - fee/rate/complexity.

All application-level business logic such as tokens and custom data, should be moved to shard/side-chains to keep the main network simple and light as possible. Great example - Lightning network, or the design of Polka/TON networks.

Bitcoin is not a data lake storage. Moreover, it becomes harder and harder to launch any p2p node with huge (useless in most cases) data inside blockchain, it's a path to nowhere.

Do you think it's possible to avoid (by design) all custom transactions except the transfer of bitcoins to avoid network stuck?

Thank you.

### Is your feature related to a problem, if so please describe it.

The main problem is scalability, we're working on new Bitcoin addresses and signature types to keep the network as light as possible, but it doesn't make any sense if we put useless information in Bitcoin transactions except BTC transfers.

### Describe the solution you'd like

The possible solution is to hard code transactions analyzer before acceptance in mempool or making a separate network which doesn't affect the main network in terms of load.

**Comment by willcl-ark** [comment]
@adastreamer This project's issue tracker is not the right place for this sort of discussion.

I'd recommend asking conceptual/theoretical questions like this either on the bitcoin-dev mailing list or on bitcoin.stackexchange.com.
