### ISSUE TITLE
v25.0 testing

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#27621]
Umbrella issue for 25.0 testing. Please help testing on a wide variety of supported platforms, as well as interaction with different software.

Let us know which version you tested on which operating system.

If you find an issue, please search Github for known issues first and then open a new Github issue.

*This meta issue should not be used to report bugs, as a single thread makes it impossible to track more than one topic.*

See [25.0 Draft Release Notes](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Notes-draft) for a list of changes, and testing reports for earlier releases (#26175, #24501, #22634), for an idea what to test.

https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Candidate-Testing-Guide

**Comment by brunoerg** [comment]
@hebasto I got an error when trying to access [25.0 Draft Release Notes](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Notes-draft)

**Comment by willcl-ark** [comment]
You could query the repo with curl?

```sh
$ curl -s "https://api.github.com/repos/bitcoin-core/guix.sigs/contents/25.0rc2" | jq -r '.[] | select(.type=="dir") | .name'
CoinForensics
Emzy
Sjors
TheCharlatan
achow101
benthecarman
cfields
darosior
fanquake
glozow
guggero
hebasto
jackielove4u
josibake
laanwj
svanstaa
theStack
vertiond
```

**Comment by pinheadmz** [comment]
Question about the guide @ismaelsadeeq 

https://github.com/bitcoin-core/bitcoin-devwiki/wiki/25.0-Release-Candidate-Testing-Guide#test-finalizing-a-psbt-with-inputs-spending-miniscript-compatible-p2wsh-scripts-and-test-spending-the-coin

Is the explanation of the descriptor correct?

it looks to me like simplified its `or(tprv8Zgx, and(tprv8Zgx, and(tprv8iF7, older(10))))` which IIUC means "either the first key OR all three of the remaining conditions (the two other keys and the timelock)"

**Comment by pinheadmz** [comment]
Other feedback about the guide:

- You can add `-named` and `-minconf=100` to `listunspent` to find the mature coinbase coins more easily

- If testers download a binary, it may be GUI only (e.g. macOS) which is fine but may require a few extra params for example I ran this:
` .../Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt -server -regtest -printtoconsole=1`

**Comment by chippsmith** [comment]
I downloaded the binaries on a System76 machine running Pop!OS 22.04 LTS.  I ran all the tests in the testing guide(except the last one about verifying binaries) and got expected results.   More detailed notes can be found here.  https://github.com/chippsmith/bitcoinnotes/tree/main/bitcoin25.0rc.

**Comment by schjonhaug** [comment]
Looks like `>>` is missing after `"maxconnections=2"` in

```
$  cd $DATA_DIR && echo "signet=1" >> bitcoin.conf && echo "maxconnections=2" bitcoin.conf  && cd ~
```

Also, it’s easier to copy the commands using the (hover) copy icon <img width="46" alt="image" src="https://github.com/bitcoin/bitcoin/assets/84225/ea868344-91f5-4e4b-b82c-5628f05a88bc"> on Github if you remove the `$` in front.

**Comment by schjonhaug** [comment]
A comment on the following paragraphs:

> To create a non-witness transaction of 64 bytes or so, You can generate an OP_RETURN output with the following dummy data in hexadecimal format: 6a00000000.

> Get a new change address
> $ bcli -regtest getnewaddress
> You should create a transaction with two outputs: one that sends Bitcoin to the address you generated, and the other that is an OP_RETURN output with the hex value of 6a00000000

> $ bcli -regtest createrawtransaction '[{"txid":"04b1a84bce28b2c989d53689404db5e3e22a2ca1875678e20286edd74dc11ace","vout":0}]' '{"data":"6a00000000"}'
> You will get an unsigned transaction hex.

It’s not clear how the change address should be used in the creation of the raw transaction.

**Comment by D33r-Gee** [comment]
Tested up to "Finalizing a PSBT..." (no bonus test yet). 

They all executed successfully!

25.0rc2 compiled from source

Hardware Info:

- Memory: 15.5 GiB
- Processor: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8
- OS: Ubuntu 20.04.5 LTS 64-bit

**Comment by fanquake** [comment]
`25.0` has been tagged.

**Comment by evansmj** [comment]
- MacOS 13.3.1
- 25.0rc2 compiled from source
- tested through the entire guide, including bonus and verifying binaries test.
- everything worked, documented a test guide comment in the test guide [issue](https://github.com/bitcoin/bitcoin/issues/27736) as we discussed in irc.
