### ISSUE TITLE
One core in CPU usage rate remains at 100% for a long time, causing serious delays in new blocks and forks

### ISSUE THREAD

**Issue by huzhenyuan** [bitcoin/bitcoin#27623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

We are the technical team from AntPool. We found that when the Bitcoin wallet node processes the process message recently, the single-threaded CPU 100% causes block parsing delays, resulting in serious technical failures.
Our version number is the latest version 24.0.1。
Not only antpool, we also asked other mining pools and found this problem. This will lead to increasingly serious orphan blocks and forks.

### Expected behaviour

Run ProcessMessage with multiple threads to reduce the performance problem of CPU single-thread ProcessMessage.
Or are there other configurations that can alleviate this problem?

### Steps to reproduce

Run the wallet, synchronize to the latest height, and then observe the CPU usage. You can see that there is a single-core CPU usage that remains at 100% for a long time

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v24.0.1

### Operating system and version

Ubuntu 22.04 LTC

**Comment by willcl-ark** [comment]
Hello @huzhenyuan, thank you for the report.

There is a possible fix for similar symptoms currently open in https://github.com/bitcoin/bitcoin/pull/27610, but note that this is to alleviate high CPU usage originating from `SendMessages()`, not `ProcessMessages()` as you describe you have found in your case. However, both of these functions are run in the same thread `b-msghand` so they could be related or difficult to discern from one another.

If you are able and willing, you could try cherry-picking the two commits from #27610 on top of the v24.0.1 tag and see if that reduces the CPU load you are seeing, e.g.:

```sh
git fetch --tags
git checkout v24.0.1
git fetch upstream pull/27610/head
git cherry-pick 228e9201efb5574b1b96bb924de1d2e8dd1317f3
git cherry-pick 5b3406094f2679dfb3763de4414257268565b943

# Compile as usual
```

**Comment by localbool** [comment]
@huzhenyuan bitcoin core developers are working on your issue. They are serious and would refund any money you lost on this stake block drama reported by bitmex research.

You can read read the logs , how much they care about you:

https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2023-05-11

**Comment by fanquake** [comment]
@huzhenyuan Thanks for reporting. As mentioned, Bitcoin Core version 24.1 will be available shortly, and contains some mitigations for the issues you are seeing. I'm going to close this issue for now, as similar/related-to #27586.

**Comment by fanquake** [comment]
@huzhenyuan v24.1 is now available: https://github.com/bitcoin/bitcoin/releases/tag/v24.1.
