### ISSUE TITLE
--with-sanitizers=float-divide-by-zero crash with -debug=bench in Chainstate::ConnectTip

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27635]
Not sure if this UB causes issues with any compiler. clang is fine, see:

* `-fsanitize=float-divide-by-zero`: Floating point division by zero. This is undefined per the C and C++ standards, but is defined by Clang (and by ISO/IEC/IEEE 60559 / IEEE 754) as producing either an infinity or NaN value, so is not included in `-fsanitize=undefined`.

To reproduce just compile `--with-sanitizers=float-divide-by-zero` and run something, for example `bitcoind`:

```
UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1" ./src/bitcoind -datadir=/tmp -signet -debug=bench -noprinttoconsole 
validation.cpp:2839:5: runtime error: division by zero
```

`float-divide-by-zero` is enabled by OSS-Fuzz, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58887

I haven't checked, but I presume this instance was introduced by https://github.com/bitcoin/bitcoin/pull/24216

**Comment by dergoegge** [comment]
cc @Sjors @jonatack @theStack

**Comment by Sjors** [comment]
The potential divide by zero was introduced here:

https://github.com/bitcoin/bitcoin/pull/24216/files#diff-97c3a52bc5fad452d82670a7fd291800bae20c7bc35bb82686c2c0a4ea7b5b98L2607-R2612

Let me see if I remember why…

**Comment by Sjors** [comment]
Opened #27673 which drops the offending metric.
