### ISSUE TITLE
BIP 39 words update

### ISSUE THREAD

**Issue by random9brat** [bitcoin/bitcoin#27649]
### Please describe the feature you'd like to see added.

Would it be possible to update bip39 words somehow to contain Serbian words (would be much useful for people from Balkan). I know this github is just btc repo but where would be the best place for this conversation to start?

### Is your feature related to a problem, if so please describe it.

Brain wallet would be much easier for at least 50.000.000 people (Balkans+outside who uses that language).

### Describe the solution you'd like

Add new 2048 bip39 words that would be on the other language

**Comment by achow101** [comment]
Bitcoin Core does not support BIP 39. Discussion of changes to BIPs should be made on the [bitcoin-dev mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev) or the [bips repo](https://github.com/bitcoin/bips).
