### ISSUE TITLE
Can't start bitcoin-qt by double-click on Debian 11

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoin/bitcoin#27655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When I double-click the bitcoin-qt executable file in the graphical file manager, Bitcoin Core doesn't start and this message pops up:

![Screenshot from 2023-05-13 10-39-57](https://github.com/bitcoin/bitcoin/assets/1530071/a0e956e3-7a13-4288-a7fc-96738667c63c)

I think this issue is the same as described at https://fostips.com/double-click-run-elf-ubuntu/
The Bitcoin Core build process seems to set some properties on the ELF file so that Debian 11 thinks the file has mime type `application/x-sharedlib`, and the file is thus treated as a shared library file. For Bitcoin Core 0.8.6, on the other hand Debian 11 shows the mime type to be `application/x-executable`, and I'm able to start it by double-clicking it. The workaround mentioned in the link above makes modern Bitcoin Core versions double-clickable.

Yes, the file has the executable flag set:

```
$ ls -l
total 95944
-rwxr-xr-x 1 demo demo  2412928 dec  6 16:53 bitcoin-cli
-rwxr-xr-x 1 demo demo 15339968 dec  6 16:53 bitcoind
-rwxr-xr-x 1 demo demo 39586776 dec  6 16:53 bitcoin-qt
-rwxr-xr-x 1 demo demo  4112824 dec  6 16:53 bitcoin-tx
-rwxr-xr-x 1 demo demo  2199488 dec  6 16:53 bitcoin-util
-rwxr-xr-x 1 demo demo  9686216 dec  6 16:53 bitcoin-wallet
-rwxr-xr-x 1 demo demo 24893312 dec  6 16:53 test_bitcoin
```

### Expected behaviour

I expected Bitcoin Core to start in GUI mode

### Steps to reproduce

Download bitcoin-24.0.1-x86_64-linux-gnu.tar.gz and unpack it. In the graphical file manager, I navigate to the bin folder and double-click on the bitcoin-qt file.

I tried also version 0.18.1, 0.20.0,  22.1 which all behaved the same.

I tried ancient version 0.8.6 and it worked as I would expect.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v24.0.1

### Operating system and version

Debian 11

### Machine specifications

x86_64

**Comment by kallerosenbaum** [comment]
I also tested Bitcoin Core 24.0.1 on Ubuntu 22.04.2 LTS, and I could double click bitcoin-qt to start it there.

**Comment by hebasto** [comment]
It seems like a Debian-specific problem, as I have no such an issue on Ubuntu (22.04, 23.04) with the downloaded binaries (v24.01, v25.0rc2).

Going to investigate further.

**Comment by hebasto** [comment]
Well, I have:
```
$ file -i bitcoin-24.0.1/bin/bitcoin-qt 
bitcoin-24.0.1/bin/bitcoin-qt: application/x-pie-executable; charset=binary
```

The mime type looks correct.

**Comment by hebasto** [comment]
Just to double check, do you have the [`libxcb-xinerama0`](https://packages.debian.org/bullseye/libxcb-xinerama0) package installed on your system?

**Comment by hebasto** [comment]
Could be related:
- https://github.com/mate-desktop/caja/issues/1164

**Comment by kallerosenbaum** [comment]
You should right click it and view options in the graphical file manager. What does the mime type say for you there? Here's mine:
![image](https://github.com/bitcoin/bitcoin/assets/1530071/7ee08b71-f966-4a9e-9510-53d5063b7733)

And I have the same result as you using `file`:
```
$ file -i bitcoin-qt 
bitcoin-qt: application/x-pie-executable; charset=binary
```

> do you have the [libxcb-xinerama0](https://packages.debian.org/bullseye/libxcb-xinerama0) package installed on your system?

yes

**Comment by hebasto** [comment]
On Ubuntu 22.04:
![image](https://github.com/bitcoin/bitcoin/assets/32963518/7142ab98-6bcf-4190-8f67-732ceb547bbd)

---

FWIW, there were two PRs that aimed improving `bitcoin-qt` launch UX improvements:
- https://github.com/bitcoin/bitcoin/pull/15068
- https://github.com/bitcoin-core/gui/pull/38

**Comment by fanquake** [comment]
Not sure what else we can do here? I think this should be moved over to the GUI repo: https://github.com/bitcoin-core/gui, in any case, and maybe someone can follow up there?

**Comment by hebasto** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/730.
