### ISSUE TITLE
Option to prevent sleep

### ISSUE THREAD

**Issue by Sataur** [bitcoin/bitcoin#27692]
### Please describe the feature you'd like to see added.

There should be option to start Core which enable system to sleep only when net. act. is disabled!

### Describe the solution you'd like

_To [notify](https://learn.microsoft.com/en-us/windows/win32/power/system-sleep-criteria) the system that your application is busy, use the.._

### Describe any alternatives you've considered

_constant disk activity about 5_ _MB/sec, occasionally it may drop to a smaller value but in general this 50 MB/sec_ [activity](https://github.com/bitcoin/bitcoin/issues/26063#issuecomment-1339086411) continues for very long periods of time._

_Creating a customized power plan_ is also not option because that would affect system even when Core is not running:
_More hours would be better, and best of all would be if you can run your node continuously._

**Comment by sinetek** [comment]
I don't think we should start messing with the user's sleep settings, it will just be confusing if every app did that. They can set themselves the power/conservative profile depending on their needs.

**Comment by fanquake** [comment]
Thanks. We've had similar proposals in the past, i.e #16145, and it's unlikely we are going to implement this kind of functionality. You can use your own scripts / external tools etc to acheive what you need.
