### ISSUE TITLE
QStandardPaths: runtime directory '/mnt/wslg/runtime-dir' is not owned by UID 0

### ISSUE THREAD

**Issue by GregTonoski** [bitcoin/bitcoin#27694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

There is the message after launching bitcoin-qt in Windows Subsystem for Linux:
```
# /usr/local/bin/b25/bitcoin-qt
QStandardPaths: runtime directory '/mnt/wslg/runtime-dir' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
```

Bitcoin-qt is launched successfully and runs smoothly despite the message.

### Expected behaviour

There isn't the unexpected message: "QStandardPaths: runtime directory '/mnt/wslg/runtime-dir' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000".

### Steps to reproduce

Launch bitcoin-qt from a command line.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

25.0 rc2

### Operating system and version

Windows 11 WSL v. 2, Ubuntu-22.04

### Machine specifications

Intel x64.

**Comment by fanquake** [comment]
Should also be moved to the GUI repo.
