### ISSUE TITLE
dumpprivkey - This type of wallet does not support this command (code -4)

### ISSUE THREAD

**Issue by faca5** [bitcoin/bitcoin#27693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Hello.

When I try export private key for bitcoin address i got:
This type of wallet does not support this command (code -4)

I tried on all 4 types of bitcoin address base58 and bech32 (legacy, segwit...).

I'm using ZIP version of Bitcoin Core v23.1.0 downloaded from:
https://bitcoincore.org/bin/bitcoin-core-23.1/bitcoin-23.1-win64.zip

### Expected behaviour

It should display private key.

Bitcoin address cannot be found?!

If I insert random value for bitcoin address i got this error.

### Steps to reproduce

1. Run Bitcoin Core v23.1.0
2. Select Help >Console
3. Insert command and press enter
dumpprivkey <bitcoin_address>

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

Bitcoin Core v23.1.0

### Operating system and version

Windows

### Machine specifications

/

**Comment by willcl-ark** [comment]
Are you using a descriptor wallet? If so see conversation here: https://github.com/bitcoin/bitcoin/issues/26046

**Comment by faca5** [comment]
Looks like.

I just downloaded latest version for Windows, created Bitcoin address and like to export private keys.

None of bitcoin address types any more works to export private keys:
Base58 (Legacy)
Base58 (P2SH-SegWit)
Bech32 (SegWit)
Back32m (Taproot)

When you are owner of bitcoin address you expect to get PRIVATE and PUBLIC keys.

In latest version of Bitcoin core I haven't found any settings to set bitcoin address as descriptor or normal one.

Any idea how to create bitcoin address in latest version of Bitcoin core which can be exported PRIVATE key?

I tried use RPC but i got error rpcuser and password is not set/valid.


I have found already issue #26046 but there is not any solution how to export private keys for own bitcoin address.

**Comment by faca5** [comment]
On Bitcoin Core version v0.14.2 works without problem.

**Comment by GregTonoski** [comment]
> I have already found issue #26046 but there is not any solution on how to export private keys for my own bitcoin address.

Does the RPC `listdescriptors true ` instead of `dumpprivkey` gives you the information, perhaps?

**Comment by faca5** [comment]
Yes. It show list of descriptors.

**Comment by GregTonoski** [comment]
You will find the information about how to use the command at https://bitcoin.stackexchange.com/ and https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md
It is not simple enough to summarize in a sentence or two here.

**Comment by faca5** [comment]
Thank you.
