### ISSUE TITLE
Release schedule for 26.0

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#27758]
Here is a proposed release schedule for `v26.0`, the next major release of Bitcoin Core. I've aimed for a release roughly 6 months after the planned release of `v25.0` (#26549).

## 2023-09-01 :heavy_check_mark:     
- Open Transifex translations for `26.0`
- Soft translation string freeze (no large or non-critical string changes until release)
- Finalize and close translations for `24.0`

## 2023-10-08 :heavy_check_mark: 
- Feature freeze (bug fixes only until release)
- Translation string freeze (no more source language changes until release)

## 2023-10-24 :heavy_check_mark: 
- Anything needed before branch-off, see https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md
- Split off `26.x` branch from `master`
- Start RC cycle, tag and release `26.0rc1`
- Start merging for `27.x` on `master` branch

## 2023-12-04 :heavy_check_mark:
- Release `26.0` (aim)

If any specific dates are a problem for you, please leave a comment.

**Comment by antlsdl1** [comment]
0xEb0Ddc0579CF3894C78ae2C4A7d5ec3B36bFa13A 같은 **chrome-native://recent-tabs/**

**Comment by hebasto** [comment]
> ## 2023-09-01 🚧
> 
>    * Open Transifex translations for `26.0`

See: https://github.com/bitcoin/bitcoin/pull/28383.

**Comment by hebasto** [comment]
> ## 2023-09-01 🚧
> 
>    * Open Transifex translations for `26.0`
> 
>    * Soft translation string freeze (no large or non-critical string changes until release)
> 
>    * Finalize and close translations for `24.0`

Done.

See the announcement on the Transifex: https://app.transifex.com/bitcoin/communication/d:162e2c23-831d-463c-b4c7-0c3f1006774c/?q=project%3Abitcoin

**Comment by achow101** [comment]
Discussed during the meeting today that we should push feature freeze back a week, so new date should be 2023-10-07.

**Comment by hebasto** [comment]
> Discussed during the meeting today that we should push feature freeze back a week, so new date should be 2023-10-07.

And the following dates should be changed accordingly, right?

**Comment by achow101** [comment]
> And the following dates should be changed accordingly, right?

Yes, already done.

**Comment by hebasto** [comment]
> ## 2023-10-08 🚧
> 
>    * Translation string freeze (no more source language changes until release)

See https://github.com/bitcoin-core/gui/pull/767.

**Comment by fanquake** [comment]
v26.0rc1 was basically dead on arrival due to an issue with the macos codesigned binary. This has been fixed, and a number of other bugfixes were also backported. [v26.0rc2](https://github.com/bitcoin/bitcoin/releases/tag/v26.0rc2) has now been tagged.

**Comment by maaku** [comment]
It is now 2023-11-23. Should the release schedule be updated?

**Comment by fanquake** [comment]
> Should the release schedule be updated?

Yes. An [rc3](https://github.com/bitcoin/bitcoin/releases/tag/v26.0rc3) was just tagged, so it will need to be pushed back a week or two.

**Comment by fanquake** [comment]
https://github.com/bitcoin/bitcoin/releases/tag/v26.0 has now been tagged.

**Comment by fanquake** [comment]
Closing this now, will open a new timeline for 27.0.
