### ISSUE TITLE
fuzz: mini_miner: Timeout in mini_miner

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27799]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59285

_Originally posted by @MarcoFalke in https://github.com/bitcoin/bitcoin/issues/27021#issuecomment-1568242621_

**Comment by fanquake** [comment]
cc @Xekyo

**Comment by Xekyo** [comment]
Yeah, it’s a grandfather paradox, in this fuzz seed, a transaction is it’s own great-grandparent. Looking into the fix.

**Comment by Xekyo** [comment]
Letting the timeout fuzz seed run longer results in it terminating eventually. I propose a fix in #27803
