### ISSUE TITLE
depriortisetransaction

### ISSUE THREAD

**Issue by kevkevinpal** [bitcoin/bitcoin#27807]
### Please describe the feature you'd like to see added.

Let me know if this is a wanted change and I can work on it but,

If a user had already prioritized a transaction to be mined there would be no way to get it deprioritized until after this PR
https://github.com/bitcoin/bitcoin/pull/27501 which adds a new RPC call to getpriotisationmap. There should be a way to remove the prioritization entirely and set it to zero without calling two separate RPCs.

### Is your feature related to a problem, if so please describe it.

If a miner wants to deprioritize a transaction then they need to call two RPC methods instead of just one which would simplify things

### Describe the solution you'd like

Add new RPC deprioritisetransaction(txid) this will set the delta to 0 and remove the txid from the delta map

### Describe any alternatives you've considered

Change prioritisetransaction(txid, 0, fee_delta=0) (may cause breakage)
where if fee_delta=0 then we set the delta to zero instead of modifying it 0

or

Add new param prioritisetransaction(txid, 0, fee_delta(optional), hardset_delta(optional))
Where now fee_delta and hardset_delta are both optional but at least one is needed

### Please leave any additional context

This idea mentioned here towards the end in PR review club
https://bitcoincore.reviews/27501

Related PR
https://github.com/bitcoin/bitcoin/pull/27501

**Comment by pinheadmz** [comment]
rpc `prioritizetransaction` can be called with a negative delta already, right?

**Comment by kevkevinpal** [comment]
> rpc `prioritizetransaction` can be called with a negative delta already, right?

Yea exactly but that requires the user to track the txid and its delta or after https://github.com/bitcoin/bitcoin/pull/27501 is merged track the txid call getpriotisationmap and then use the negative delta from there

was thinking it would be easier if the user could just specify the txid they want to remove

**Comment by willcl-ark** [comment]
`getmempoolentry` RPC also shows you the modified fee, which includes the priotirization delta (although still requires reverse calculation).

**Comment by pinheadmz** [comment]
> was thinking it would be easier if the user could just specify the txid they want to remove

can't you just call prioritisetransaction with txid and, like, `-999999` ?

**Comment by kevkevinpal** [comment]
> > was thinking it would be easier if the user could just specify the txid they want to remove
> 
> can't you just call prioritisetransaction with txid and, like, `-999999` ?

wouldn't this make the map delta never include that txid, maybe depriortisetransaction isn't the best naming but instead removing any preference on a txid. Removing it from the mapdeltas. Goal is to set the mapdelta for a txid to 0.

maybe `removepriortisation` instead?

**Comment by kevkevinpal** [comment]
> `getmempoolentry` RPC also shows you the modified fee, which includes the priotirization delta (although still requires reverse calculation).

didn't know that thanks, but ya still reverse calculation still required

**Comment by pinheadmz** [comment]
> maybe `removepriortisation` instead?

GOTCHA, well maybe instead of a new rpc, maybe `priotirisetransaction <txid> 0` could be a magic word for reset like you want

**Comment by kevkevinpal** [comment]
> 

ya that could work and we wouldn't need to add a whole new rpc. That would require us to make the fee_delta param optional and if priotirisetransaction(<txid>, 0) we can check if no fee_delta and the param = 0 we set the map delta to 0

not sure if its forbidden to modify that dummy param not exactly sure it is a dummy param or its history

**Comment by instagibbs** [comment]
> Yea exactly but that requires the user to track the txid and its delta or after https://github.com/bitcoin/bitcoin/pull/27501 is merged track the txid call getpriotisationmap and then use the negative delta from there
> was thinking it would be easier if the user could just specify the txid they want to remove

I tend to think that 27501 is enough? prioritization is a very advanced feature in itself, seems to be sufficient to me.

**Comment by kevkevinpal** [comment]
> > Yea exactly but that requires the user to track the txid and its delta or after #27501 is merged track the txid call getpriotisationmap and then use the negative delta from there
> > was thinking it would be easier if the user could just specify the txid they want to remove
> 
> I tend to think that 27501 is enough? prioritization is a very advanced feature in itself, seems to be sufficient to me.

ok yea makes sense and doesn't seem like anyone strongly wants this feature either, so I can close this issue and if anyone wants to reopen they can!
