### ISSUE TITLE
Build fails on Fedora 36 - configure failed for src/secp256k1

### ISSUE THREAD

**Issue by desibitcoiner** [bitcoin/bitcoin#27808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Found a recent similar issue but didn't help:
https://github.com/bitcoin/bitcoin/issues/27550

I'm trying to run a build on Fedora 36 and I'm seeing the same error.
When I run ./configure I see the following:

configure: WARNING: Bitcoin Core requires this library for BDB (legacy) wallet support
configure: WARNING: Passing --without-bdb will suppress this warning
checking for SQLITE... yes
checking whether to build wallet with support for sqlite... yes
checking whether Userspace, Statically Defined Tracing tracepoints are supported... no
checking for natpmp.h... yes
checking for initnatpmp in -lnatpmp... yes
checking for boostlib >= 1.64.0 (106400)... yes
checking whether Boost.Process can be used... yes
checking for seccomp-bpf (Linux x86-64)... yes
checking for EVENT... yes
checking for EVENT_PTHREADS... yes
checking if evhttp_connection_get_peer expects const char**... no
checking for ZMQ... yes
checking for LIBMULTIPROCESS... no
checking whether to build bitcoind... yes
checking whether to build bitcoin-cli... yes
checking whether to build bitcoin-tx... yes
checking whether to build bitcoin-wallet... yes
checking whether to build bitcoin-util... yes
checking whether to build experimental bitcoin-chainstate... no
checking whether to build libraries... yes
checking if ccache should be used... yes
checking whether C compiler accepts -fdebug-prefix-map=A=B... yes
checking whether C preprocessor accepts -fmacro-prefix-map=A=B... yes
checking if wallet should be enabled... yes
checking whether to build with support for UPnP... no
checking whether to build with support for NAT-PMP... yes
checking whether to build with NAT-PMP enabled by default... no
checking whether to build test_bitcoin... yes
checking whether to reduce exports... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libbitcoinconsensus.pc
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/man/Makefile
config.status: creating share/setup.nsi
config.status: creating share/qt/Info.plist
config.status: creating test/config.ini
config.status: creating contrib/devtools/split-debug.sh
config.status: creating src/config/bitcoin-config.h
config.status: src/config/bitcoin-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in src/secp256k1 (/home/kau/Code/Bitcoin/bitcoin/src/secp256k1)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local' '--without-miniupnpc' '--disable-bench' '--without-gui' '--disable-shared' '--with-pic' '--enable-benchmark=no' '--enable-module-recovery' '--enable-module-schnorrsig' --cache-file=/dev/null --srcdir=.
configure: error: cannot find required auxiliary files: compile missing
configure: error: ./configure failed for src/secp256k1

Would be appreciate if you can guide if this error is because of a recent change.

### Expected behaviour

Configure script completes successfully. 

### Steps to reproduce

run the following on master:

./configure --without-miniupnpc --disable-bench --without-gui

### Relevant log output

Already pasted above

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@ba616b9

### Operating system and version

Fedora 36

**Comment by fanquake** [comment]
Clsoing for now. This is more than likely a local issue. Can be re-opened if actionable information is provided.
