### ISSUE TITLE
Use semantic analysis in lint-logs.py

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#27825]
### Please describe the feature you'd like to see added.

Currently `test/lint/lint-logs.py` tries to parse the C++ manually which is prone to flaws. For example it does not support expressions that span more than one line and would be happy if there is `\n"` anywhere (on the single line it checks). For example:

```cpp
        LogPrintLevel(BCLog::PROXY, 
                      BCLog::Level::Debug, 
                      "This is fine, but lint-logs.py will report error\n");
```

```cpp
        LogPrintLevel(BCLog::PROXY, BCLog::Level::Debug, "Not ok\n"
                      " but will be reported as ok");
```

```cpp
        LogPrintLevel(BCLog::PROXY, BCLog::Level::Debug, "even more /* Continued */ no newline, but is ok");
```

```cpp
        /* LogPrintLevel() inside comment causes an error */
```

### Is your feature related to a problem, if so please describe it.

`lint-logs.py` requires to either write everything on line line or add `/* Continued */` comment.

### Describe the solution you'd like

It should be possible to use [libclang](https://pypi.org/project/libclang/) to properly parse the C++ code. Then the check should be something like:

```
for each call to `LogPrintLevel()`:
    get the third argument:
        it should be a string
        its last two chars should be `\` and `n`
```

**Comment by theuni** [comment]
Hah, I [implemented this as a clang-tidy check](https://github.com/theuni/bitcoin-tidy-experiments/blob/main/LogPrintfCheck.cpp) a while back.

I'll work on getting it hooked up.

**Comment by theuni** [comment]
Still working on getting the plugin cleaned up, but in the meantime it pointed out what seems to have found a buggy case [here](https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L5433). Will PR a trivial fix for that.

**Comment by vasild** [comment]
That looks more native than the sh or py scripts, excellent!

**Comment by theuni** [comment]
Just wanted to document this somewhere before I forget...

I attempted to make an "ideal" plugin, which wouldn't require us to hard-code parts of our code, but I ran into a few issues.

@aaronballman was nice enough to explain the status quo to me on IRC:

> \<cfields\> I'm working on a clang plugin that registers a custom attribute,  and for parsing I'm finding myself copy/pasting several static functions from SemaDeclAttr.cpp (for example checkUInt32Argument).  I'm now needing the equivalent of checkFunctionOrMethodParameterIndex,  but that comes with lots of dependencies.  Is there maybe something I'm missing? Some better supported api for checking attribute arguments from plugins?
> \<AaronBallman\> cfields: you're not missing anything, attribute plugin support is relatively recent and so it still has quite a few sharp edges
> \<cfields\> AaronBallman: ah,  ok,  that alone is a huge hint.  Thanks :)
> \<AaronBallman\> cfields: you're welcome! We definitely could stand to make some of that stuff easier for folks writing plugins.
> \<cfields\> AaronBallman: anything I can do to help move it along? I've been waiting quite eager for this functionality so I'd be happy to contribute. .. 
> \<cfields\> AaronBallman: for reference, my motivation: It would allow our codebase (bitcoin core) to use custom meaningfull annotations (the second parameter of this function must be of a certain subset of something something) as opposed to having plugins that contains hard-coded knowledge of our types/functions/etc.  Imo the former is _far_ more maintainable :)
> \<AaronBallman\> cfields: for this, I think it's mostly a matter of figuring out where those functions should live and which ones to expose. They're static to SemaDeclAttr.cpp and they might not all be reasonable to expose more widely (due to weird implementation details like how to index parameters, etc).

---

So I'll just stick with the approach of hard-coding our function names for now.

**Comment by theuni** [comment]
See [here](https://github.com/theuni/bitcoin-core-clang-plugin/commit/05fb23f21df32df4445951123d281172b12ee61b) for an example of this implemented as a `clang` plugin rather than `clang-tidy`. As noted above, it's pretty rough because LLVM does not yet expose several useful helpers.

Advantages:
- We can invent our own attributes, which is way nicer for future-proofing. See [here](https://github.com/theuni/bitcoin-tidy-experiments/pull/1) for an example of the kind of synchronization problems we'll have otherwise.
- Use is a side-effect of typical compilation

Disadvantages:
- More complicated to write
- Jobs with a static-analysis `clang-tidy` step may be preferred

**Comment by theuni** [comment]
Sure. Now that I think about it, we could just keep|copy the test suite in Core rather than|in addition to the plugin repo.

**Comment by vasild** [comment]
Fixed by https://github.com/bitcoin/bitcoin/pull/26296, thanks!
