### ISSUE TITLE
Alternative read only paths for -blocksdir

### ISSUE THREAD

**Issue by Brotcrunsher** [bitcoin/bitcoin#27833]
### Please describe the feature you'd like to see added.

The Blockchain is growing in size over the years. It would be nice to be able to store it accross multiple hard drives and specify additional blocksdirs that are meant for validation in full nodes. When the client writes a file, it is still written to the -blocksdir, always. When reading a file, it is first looked up in the -blocksdir. When it's not present there, it is looked up in the additional blocksdirs, in order as they are specified by the command line arguments. 

### Describe any alternatives you've considered

Combining multiple hard drives is possible using a RAID, but these are prone to failure and would force the user to format their drives, which is possibly something that the user doesn't want to do.

### Please leave any additional context

I think I would be able to implement this myself. However, I want to know if this feature is wanted or if I might have overlooked some existing possibility to achieve this and generally want to collect some feedback on this.

**Comment by fanquake** [comment]
Agree with Marco. You can use something like LVM to combine your drives, and then point to a single blocksdir. There's no need for us to introduce complexity to mange this into Bitcoin Core.
