### ISSUE TITLE
Yeah, good point. I'll do a follow-up on this since it's out of scope for the already large change.

### ISSUE THREAD

**Issue by Dadudidas** [bitcoin/bitcoin#27842]
Yeah, good point. I'll do a follow-up on this since it's out of scope for the already large change.

_Originally posted by @jamesob in https://github.com/bitcoin/bitcoin/pull/24232#discussion_r923829116_

**Comment by willcl-ark** [comment]
Please try and open clear and descriptive issues, not like this.

If you want to open an issue that `PopulateAndValidateSnapshot()` should be better documented, then please feel free.
