### ISSUE TITLE
Stuck chainstate when utxo_snapshot.sh fails

### ISSUE THREAD

**Issue by hazeycode** [bitcoin/bitcoin#27841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

IBD/chainstate gets stuck if utxo_snapshot.sh fails. No new blocks are downloaded. Restarting bitcoind does not help. Taking another snapshot __at an earlier height__ or reindex is required to repair.

utxo_snapshot.sh output:
```
Rewinding chain back to height 788440 (by invalidating 000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7); this may take a while
Generating UTXO snapshot...
error code: -8
error message:
/home/chris/Desktop/assumeutxo/test/utxo-788440.dat already exists. If you are sure this is what you want, move it out of the way first
```

Note that moving the file or choosing another filename and rerunning does not fix. But taking another snapshot at an earlier height will.

### Expected behaviour

If utxo_snapshot.sh fails, bitcoind should cancel rewind and recover.

Also, if a filepath that already exists is passed to utxosnapshot.sh, it should early exit before rewinding. This could perhaps be considered a separate issue.

### Steps to reproduce

1. Create a dummy file for the purpose of the test e.g. `echo "some bytes so file is not empty" > ./utxo-788440.dat`
2. Run bitcoind and wait for it to sync
3. Run utxosnapshot.sh with some blockheight and a filepath __that already exists__ e.g. `./contrib/devtools/utxo_snapshot.sh 788440 ./utxo-788440.dat ./src/bitcoin-cli`
4. Wait for chain rewind to happen, snapshot to be generated and write to disk fail
5. Observe bitcoind is now stuck with an invalid block at the rewind height

### Relevant log output

```
2023-06-08T23:51:50Z [httpworker.3] UpdateTip: new best=000000000000000000014a9d36f6a19aca593f0c228ae1b1b6fe33361fa67be1 height=788440 version=0x2001e000 log2_work=94.162204 tx=832727241 date='2023-05-06T02:54:13Z' progress=0.987258 cache=790.3MiB(1245160txo)
2023-06-08T23:51:50Z [httpworker.3] InvalidChainFound: invalid block=000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7  height=788441  log2_work=94.162217  date=2023-05-06T02:55:43Z
2023-06-08T23:51:50Z [httpworker.3] InvalidChainFound:  current best=000000000000000000014a9d36f6a19aca593f0c228ae1b1b6fe33361fa67be1  height=788440  log2_work=94.162204  date=2023-05-06T02:54:13Z
```

```
Rewinding chain back to height 788440 (by invalidating 000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7); this may take a while
Generating UTXO snapshot...
error code: -8
error message:
/home/chris/Desktop/assumeutxo/test/utxo-788440.dat already exists. If you are sure this is what you want, move it out of the way first
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v25.99.0-3dc6fd620e28

### Operating system and version

Linux 6.3.1-arch2-1

**Comment by hazeycode** [comment]
Another way to repair is to run another snapshot at an earlier height.

**Comment by jamesob** [comment]
Thanks for the report. I think to solve this without a reindex, you just need to run `reconsiderblock 000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7`. We should probably amend the script to catch failures or interrupts and do this automatically.

**Comment by hazeycode** [comment]
Thanks @jamesob. I can confirm that `reconsiderblock` works as you expected. I'll have a go at updating the script with error handing.
