### ISSUE TITLE
arm64 CI failure

### ISSUE THREAD

**Issue by ajtowns** [bitcoin/bitcoin#27879]
arm64 CI is failing with:

```
FAIL: minisketch/test
=====================

../build-aux/test-driver: line 109: ./minisketch/test: cannot execute binary file: Exec format error
FAIL minisketch/test (exit status: 126)

FAIL: univalue/test/object
==========================

../build-aux/test-driver: line 109: ./univalue/test/object: cannot execute binary file: Exec format error
FAIL univalue/test/object (exit status: 126)

FAIL: univalue/test/unitester
=============================

../build-aux/test-driver: line 109: ./univalue/test/unitester: cannot execute binary file: Exec format error
FAIL univalue/test/unitester (exit status: 126)

FAIL: qt/test/test_bitcoin-qt
=============================

../build-aux/test-driver: line 109: ./qt/test/test_bitcoin-qt: cannot execute binary file: Exec format error
FAIL qt/test/test_bitcoin-qt (exit status: 126)
```

See eg https://github.com/bitcoin/bitcoin/pull/27647/checks?check_run_id=14232303009 or https://github.com/bitcoin/bitcoin/pull/27746/checks?check_run_id=14231876127

I tried re-running the arm64 task for #27675 which had succeeded yesterday, and it now fails too ([before](https://cirrus-ci.com/task/6152515125772288) vs [after](https://cirrus-ci.com/task/6688015473442816)), which suggests either that the bug was introduced after commit fbe48f97dfec3138b06b5f00b75655da0c985008 up to commit 427853ab49f610e971b73ea4cc1d5366747e52b1 (nothing seemed likely to break minisketch/test there) or is an infrastructure issue (bad cache or bad hardware?).

**Comment by ajtowns** [comment]
Maybe worth adding `git show FETCH_HEAD` at the end of `base_template:` in `.cirrus.yml` so it's easier to see which version of master a CI run was merged against?

**Comment by ajtowns** [comment]
> I think you can check the output of `merge_base` to see what was used? For example, https://cirrus-ci.com/task/6628961686388736?logs=merge_base#L18

I looked at that and somehow didn't see it. Weird.

**Comment by hebasto** [comment]
> There is certainly something sketchy going on with the upstream hardware/software. I've had to reset the pre-build of the image thrice: https://cirrus-ci.com/task/4729934984249344. Also, once that passes, the actual build fails half the time with `curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443 ` https://cirrus-ci.com/task/5920692756021248?logs=ci#L208
> 
> 
> 
> 

@fkorotkov What do you think?

**Comment by hebasto** [comment]
> There is certainly something sketchy going on with the upstream hardware...

It looks like the underlying hardware stopped to support running ARM-32bit binaries on `arm64` hardware. Actually, there was not such a promise from Cirrus Labs about that.

> My suggestion would be to wait 24 hours to see if the issue fixes itself. If not, replace the arm64 hardware with amd64, and run everything in qemu-arm again.

Another option is to build `aarch64` binaries using an `arm_container` in this task.

**Comment by hebasto** [comment]
> do you mind updating the CI task config for aarch64?

I'll do it. No need to [wait](https://github.com/bitcoin/bitcoin/issues/27879#issuecomment-1590963200) a happy self fix? :)

**Comment by pinheadmz** [comment]
> arm32 release builds

meaning `bitcoin-25.0-arm-linux-gnueabihf.tar.gz` 😬 that's the Raspberry Pi binary

**Comment by pinheadmz** [comment]
the hardware has been 64 bit since Pi3 I think but the OS itself has only been 64 bit for a year or so:

https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by fkorotkov** [comment]
The only Arm related change yesterday was that we switched from AWS using Graviton2 CPUs to [GCP using Ampere CPUs](https://cloud.google.com/compute/docs/instances/arm-on-compute). Both Graviton2 and [Ampere Alta support EL0 AArch32](https://solutions-portal-cms-prod-bucket.s3.amazonaws.com/Altra_Max_Rev_A1_DS_v1_05_20220728_5bf985da35.pdf).

**Comment by fanquake** [comment]
> Both Graviton2 and [Ampere Alta support EL0 AArch32](https://solutions-portal-cms-prod-bucket.s3.amazonaws.com/Altra_Max_Rev_A1_DS_v1_05_20220728_5bf985da35.pdf).

Yes, however GCP [explicitly doesn't](https://cloud.google.com/compute/docs/general-purpose-machines#t2a_limitations) support 32-bit mode?
> The Tau T2A machine series does not support:
> 32-bit mode ELO (guest userspace support)

**Comment by hebasto** [comment]
> I think a third alternative for us, if we want minimal changes, would be to unset `QEMU_USER_CMD` and run qemu on aarch64 for now?

I've been [testing](https://cirrus-ci.com/task/5385268543356928) this change since morning. CI constantly timed out for some reasons.
