### ISSUE TITLE
test: Cleanup is_node_stopped

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27893]
### Motivation

See https://github.com/bitcoin/bitcoin/pull/27708/files#r1227794716 and https://github.com/bitcoin/bitcoin/pull/27708/files#r1226949554

### Possible solution

(see above)

### Useful Skills

* Compile Bitcoin Core and run the tests
* Python 3 and the Bitcoin Core functional tests

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by dimitaracev** [comment]
I can take this.
