### ISSUE TITLE
Nodes are not published after Bitcoin Code process done 

### ISSUE THREAD

**Issue by vkhalaburskiy** [bitcoin/bitcoin#27901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Dear support, 
 
Recently I created 2 clients and opened the port 8333 for them: 
64.250.182.133 - BTC Core Ubuntu
64.250.182.138 - BTC Core Windows

The BTC core syncronization process is already completed but I don't see these nodes are published on the https://bitnodes.io/ when I try to Check the node. 

Here are screenshots: https://drive.google.com/drive/folders/1atsXL-94GOqrrq-6yly5b9PK6Xfovx1Q?usp=sharing

Can you please assist me with that? 

Thank you in advance! 

### Expected behaviour

I want these nodes with the port 8333 to be published on the https://bitnodes.io/ 
64.250.182.133 - BTC Core Ubuntu
64.250.182.138 - BTC Core Windows

### Steps to reproduce

1. Go to https://bitnodes.io/
2. Insert 64.250.182.133 and port 8333
3. Check node 
4. See the node published 

1. Go to https://bitnodes.io/
2. Insert 64.250.182.138 and port 8333
3. Check node 
4. See the node published 

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

Version 25 for Windows, v22.0 for Ubuntu

### Operating system and version

Windows 10 Pro 22H2, Ubuntu 22.04.2 LTS

### Machine specifications

Intel Xeon CPU (2 vCPU) / 16 Gb RAM Standard HDD for Windows 
Intel Xeon CPU (4vCPU) / 4 Gb RAM / Standard HDD for Ubuntu

**Comment by willcl-ark** [comment]
That website presumably runs a full node or other crawler which will collect addresses from the p2p network. Without knowing how that website works, I'd assume that your nodes will appear there at some point if they are configured correctly and connected to other nodes in the network.

Perhaps you need open the p2p port (default: 8333) on your router (i.e. "listening")? If that doesn't help I'd recommend contacting the owner of the website with your query.

Either way, this issue tracker is not a support forum for unaffiliated websites, so I'm going to close this issue out.

**Comment by vkhalaburskiy** [comment]
@willcl-ark, thanks for your explanations! 
Probably it's also important that we're running pruned nodes, not full, do you think the reason can be in that as well? 

The last question, do you know the contact info of  https://bitnodes.io/ maybe? They don't have a support there (

**Comment by willcl-ark** [comment]
Sorry I don't know anyone there. 

Looks like it only has listening nodes so ensure you have listen=1 in your bitcoin config, and 8333 forwarded on your router to the node.

Then wait I guess?

**Comment by vkhalaburskiy** [comment]
@willcl-ark got you! 
Appreciate it.
