### ISSUE TITLE
Failure running CI locally: "#0 15.01 Error: Unable to find a match: glibc-devel.x86_64 libstdc++-devel.x86_64 glibc-devel.i686 libstdc++-devel.i686"

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#27910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I'm following the guide in `ci/README.md` but I can't get any of the environments to run successfully.

### Expected behaviour

Run CI locally

### Steps to reproduce

macOS:
```
--> docker -v
Docker version 24.0.2, build cb74dfc
--> uname -a
Darwin   21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:10:19 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T8101 arm64
```

command:
`FILE_ENV="./ci/test/00_setup_env_i686_centos.sh" ./ci/test_run_all.sh`

### Relevant log output

Full log: https://gist.github.com/pinheadmz/912bbb8dc55bc9e95ca8dda660f3800b

end of log:
```
#0 7.735 + bash -c 'dnf -y --allowerasing install gcc-c++ glibc-devel.x86_64 libstdc++-devel.x86_64 glibc-devel.i686 libstdc++-devel.i686 ccache libtool make git python3 python3-pip which patch lbzip2 xz procps-ng dash rsync coreutils bison util-linux '
#0 25.06 Extra Packages for Enterprise Linux 9 - aarch64 1.0 MB/s |  18 MB     00:17    
#0 30.34 Extra Packages for Enterprise Linux 9 - Next -  448 kB/s | 606 kB     00:01    
#0 30.75 Last metadata expiration check: 0:00:01 ago on Sat Jun 17 16:06:48 2023.
#0 31.46 No match for argument: glibc-devel.x86_64
#0 31.47 No match for argument: libstdc++-devel.x86_64
#0 31.47 No match for argument: glibc-devel.i686
#0 31.48 No match for argument: libstdc++-devel.i686
#0 31.48 Package python3-3.9.16-2.el9.aarch64 is already installed.
#0 31.53 Error: Unable to find a match: glibc-devel.x86_64 libstdc++-devel.x86_64 glibc-devel.i686 libstdc++-devel.i686
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master 
f0758d8a6696657269d9c057e7aa079ffa9e1c16                                                                                                                                                                        

### Operating system and version

macOS 12.6.5

**Comment by pinheadmz** [comment]
macos env failure:

`--> FILE_ENV="./ci/test/00_setup_env_mac.sh" ./ci/test_run_all.sh`

full log: https://gist.github.com/pinheadmz/cb57f51857812b9e78360648f5431c28

error:
```
2 warnings and 1 error generated.
make[1]: *** [Makefile:1814: mut_pthread.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1514: bt_compare.o] Error 1
In file included from ../dist/./../btree/bt_compress.c:9:
In file included from ./db_int.h:884:
In file included from ../dist/./../dbinc/mutex.h:15:
../dist/./../dbinc/mutex_int.h:932:2: error: unknown type name 'pthread_rwlock_t'
```

**Comment by pinheadmz** [comment]
This one succeeded: `--> FILE_ENV="./ci/test/00_setup_env_native_asan.sh" ./ci/test_run_all.sh`

**Comment by fanquake** [comment]
> macos env failure:
> ../dist/./../dbinc/mutex_int.h:932:2: error: unknown type name 'pthread_rwlock_t'

Does the change from #26073 fix this for you?

**Comment by pinheadmz** [comment]
> I'd recommend to use a x86 machine.

Ok thanks, I'm having better luck on Ubuntu on x86 I'll open a new issue if I run into problems there.
