### ISSUE TITLE
This app cant run on your PC, to find a version for your PC, check with the software publisher. 

### ISSUE THREAD

**Issue by Rlavington** [bitcoin/bitcoin#27911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I download this new program to my HDD where version 24.0 Bitcoin Blockchain is fully synced up and downloaded, I click on the "exe" to set it up and i get this message below: 

'This app can't run on your PC, to find a version for your PC, check with the software publisher". 

### Expected behaviour

i expect that when i click "exe" that it starts to install the new software and that the new program runs. 

### Steps to reproduce

![thumbnail jpg 1](https://github.com/bitcoin/bitcoin/assets/70559445/b5bc44bc-1da0-4d5f-bd99-bf5d2a820229)

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

V24.0 

### Operating system and version

Windows 10 

### Machine specifications

intel core i5 11500 6 core LGA 2.7Ghz
16Gb (2x 8GB) 3200MHz Ram 
4Tb HDD.

**Comment by hernanmarino** [comment]
Are you sure you are not trying to run the 64 bit version of Bitcoin Core on a 32 bit Windows 10 ? This might be one of the explanations for that error. In any case, it looks like a windows error. Did you try downloading the binaries instead of compiling to see if it's not a compiling issue ?

**Comment by 0xB10C** [comment]
> I download this new program to my HDD where version 24.0 Bitcoin Blockchain is fully synced up and downloaded, I click on the "exe" to set it up and i get this message below:

Where did you download that program? What program did you download?

**Comment by Rlavington** [comment]
> Are you sure you are not trying to run the 64 bit version of Bitcoin Core on a 32 bit Windows 10 ? This might be one of the explanations for that error. In any case, it looks like a windows error. Did you try downloading the binaries instead of compiling to see if it's not a compiling issue ?

64-bit operating system, x64-based processor

my Windows operating system is the 64 bit version

 "did i download the binaries instead of compiling", sorry what do you mean???

**Comment by Rlavington** [comment]
> > I download this new program to my HDD where version 24.0 Bitcoin Blockchain is fully synced up and downloaded, I click on the "exe" to set it up and i get this message below:
> 
> Where did you download that program? What program did you download?

I downloaded it off of GitHub, version 25.0, here : 

https://github.com/bitcoin/bitcoin/releases/tag/v25.0

**Comment by Rlavington** [comment]
> Also, you claim 24.0 in the opening post, but then say 25.0 later. Which one was it? Or is it both?

I'm currently running version 24.0, but the new version 25.0 is the one that is not working.

**Comment by Rlavington** [comment]
> > "did i download the binaries instead of compiling", sorry what do you mean???
> 
> In your issue above, you say "How did you obtain Bitcoin Core? Compiled from source". It seems you downloaded the binary, and did not compile it yourself from source.

I downloaded the "Binary"?? 
All I have done is select "win exe", version 25.0 and this is the one that does not work on my Windows 10 machine (64 bit version).

**Comment by Satoshin-Btc** [comment]
Try downloading the zip of the version then unzip and run. It's sometimes a
way around the installation program not working.

Plus, with the zip installer it's a little better in my opinion.

**Comment by Satoshin-Btc** [comment]
Also try the Bitcoin core webpage where they have the versions up if I'm
not mistaken. Bitcoincore.org

**Comment by Rlavington** [comment]
> Bitcoin core

Bitcoin core only has version 22.0, so they are 3 versions behind version 25.0. When i download both:

 [bitcoin-25.0-win64.zip](https://bitcoincore.org/bin/bitcoin-core-25.0/bitcoin-25.0-win64.zip)

or:

[bitcoin-25.0-win64-setup.exe](https://bitcoincore.org/bin/bitcoin-core-25.0/bitcoin-25.0-win64-setup.exe)

they "both" fail to download. Im using FireFox browser.

**Comment by Rlavington** [comment]
ah!! i think i see the problem. My portal HDD is full lol 

No worries i get a new HDD soon with bigger space. 

I will try on downloading it on that once i get it. 

thanks for your trouble shooting guys!

**Comment by Rlavington** [comment]
ok, yes problem solved! totally my fault, there was not enough space on my portal HDD. Since i deleted a load of files from there i now have version 25.0 for my Bitcoin Node running well. 

Thanks for your help and troubleshooting!

Please close this case.
