### ISSUE TITLE
Different versions

### ISSUE THREAD

**Issue by F0rsX** [bitcoin/bitcoin#27936]
Just wondering why bitcoin.org and bitcoincore.org have different versions to download? bitcoin.org version has not been updated since 2021, although it is the official site of the project...

**Comment by achow101** [comment]
bitcoincore.org is the official site of the project, not bitcoin.org. bitcoin.org is a separate project with its own contributors and maintainers, we have no say on what they host/mirror on their site.

**Comment by F0rsX** [comment]
Strange that the wikipedia link is to bitcoin.org https://en.wikipedia.org/wiki/Bitcoin
