### ISSUE TITLE
Bitcoin Core not responding

### ISSUE THREAD

**Issue by Zencsy** [bitcoin/bitcoin#27964]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

I've just started bitcoin mining a few months ago and I've chosen bitcoin core as the app to store my bitcoins, after 2 days of synchronizing with the network i've 18 weeks left and suddenly my bitcoin core application keeps freezing and not responding. I tried to look for solutions to fix the problem online but most of them said to go on github and ask for help. I'm new to all of this and I have no idea what to do, can someone help?

![image_2023-06-25_182649102](https://github.com/bitcoin/bitcoin/assets/137690983/1ce9dad3-7f8b-4b96-a0d9-b1e4b112b785)

**Comment by hebasto** [comment]
> Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

Mind moving this issue into the [GUI repo](https://github.com/bitcoin-core/gui) (closing this one and opening a new issue there)?

> my bitcoin core application keeps freezing and not responding.

If it keeps freezing after restarting, more details are welcome, for instance `debug.log` content (NOTE: make sure no private details will leaked).
