### ISSUE TITLE
Wallet not loaded

### ISSUE THREAD

**Issue by n1kcha** [bitcoin/bitcoin#27982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Suddenly wallet not loaded. I was resyncing blockchain (now synced). The wallet is old and has balance. Yesterday there was no problem. 
Recently updated for V24 to V25. All was working ok until today. Node is not pruned.

Disk that blocks are stored is external Toshiba with USB connection, i have just a soft link between .bitcoin/blocks to blocks at Toshiba. I have repaired this disk a couple of times using windows disk tools. I did a repair because bitcoincore wanted to reindex blockchain. After the repair bitcoinore was ok (not asking for reindex) and continue syncing.
Tried this command: bitcoin-cli listaccounts and get error code: -32601/ Method not found error message

### Expected behaviour

load my wallet

### Steps to reproduce

run bitcoin-qt or bitcoind, all working ok except wallet loading

### Relevant log output

"Wallet disabled!" from bitcoind running messages

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v25.0

### Operating system and version

Fedora Linux 38

### Machine specifications

intel 8265U i5 cpu/16g ram/samsung evo 850 ssd drive/ external usb  disk for blocks storage

**Comment by carnhofdaki** [comment]
I think this behavior is expected. Have a look at f0758d8a66 and maybe some older related changes when the default wallet creation and loading is disabled.

It makes sense for nodes that run the released binary but do not operate their own wallet (or do it differently than using the Bitcoin Core's wallet - straight via RPC calls, for example `scantxoutset` to get the list of UTXOs).

**Comment by n1kcha** [comment]
I have another full node v25 (similarly recently updated  from v24) to a different computer. No problems there. But how to see my wallet again, downgrade to v24?

**Comment by n1kcha** [comment]
i did nothing different, nothing changed in configuration file. Just open a termianl an run bitcoin-qt as i am doing for years... How this -disablewallet parameter is passed?

**Comment by n1kcha** [comment]
ok thanks, i will check conf file
