### ISSUE TITLE
libsecp256k1 not instrumented when building with sanitizers

### ISSUE THREAD

**Issue by dergoegge** [bitcoin/bitcoin#27990]
Our libsecp256k1 builds are not instrumented when building with sanitizers (using `--with-sanitizers`).

For example building with:
```
./configure --enable-fuzz --with-sanitizers=fuzzer
make
```
will not instrument secp code paths for fuzzing. Can be checked with `objdump`, e.g. `objdump --disassemble-symbols=secp256k1_xonly_pubkey_serialize src/test/fuzz/fuzz`.

As a workaround it is possible to set `CFLAGS` to use the desired sanitizers (e.g. CFLAGS=`-fsanitize=fuzzer-no-link`) but ideally our `--with-sanitizers` configure option would do this automatically.

**Comment by hebasto** [comment]
FWIW, the libsecp256k1 is instrumented properly when using the CMake-based build system (see the full prototype [branch](https://github.com/hebasto/bitcoin/tree/pr25797.69) from https://github.com/bitcoin/bitcoin/pull/25797):
```
$ objdump --disassemble=secp256k1_xonly_pubkey_serialize build/src/test/fuzz/fuzz | grep __sanitizer_cov
  d42e90:  e8 8b 23 c0 ff         call   945220 <__sanitizer_cov_trace_const_cmp8>
  d42ff2:  e8 39 21 c0 ff         call   945130 <__sanitizer_cov_trace_pc_indir>
  d43018:  e8 13 21 c0 ff         call   945130 <__sanitizer_cov_trace_pc_indir>
  d43042:  e8 e9 20 c0 ff         call   945130 <__sanitizer_cov_trace_pc_indir>
```
