### ISSUE TITLE
rpc: doc: RPCHelpMan missing request parameters for getblocktemplate

### ISSUE THREAD

**Issue by stickies-v** [bitcoin/bitcoin#27998]
### Motivation

The `getblocktemplate` help currently shows these available request parameters (as part of the `template_request` object):

<details>
<summary> $ ./bitcoin-cli help getblocktemplate</summary>

```
$ ./bitcoin-cli help getblocktemplate

...

Arguments:
1. template_request         (json object, optional, default={}) Format of the template
     {
       "mode": "str",       (string, optional) This must be set to "template", "proposal" (see BIP 23), or omitted
       "capabilities": [    (json array, optional) A list of strings
         "str",             (string) client side supported feature, 'longpoll', 'coinbasevalue', 'proposal', 'serverlist', 'workid'
         ...
       ],
       "rules": [           (json array, required) A list of strings
         "segwit",          (string, required) (literal) indicates client side segwit support
         "str",             (string) other client side supported softfork deployment
         ...
       ],
     }
...
```
</details>

It seems two (optional) parameters are missing: [`longpollid`](https://github.com/bitcoin/bitcoin/blob/d4018f0b6cbff43a1b8d2d57c5df2286f4d6e9d5/src/rpc/mining.cpp#L658) and [`data`](https://github.com/bitcoin/bitcoin/blob/d4018f0b6cbff43a1b8d2d57c5df2286f4d6e9d5/src/rpc/mining.cpp#L662).

### Possible solution

Seems like a good first issue to me:
1. Understand what both parameters do, their type etc.
2. Add two entries to the `template_request` object, with a helpful concise description, and consider their optional status
3. Verify output is correct by calling `./bitcoin-cli help getblocktemplate`

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by ItIsOHM** [comment]
Hey there, I'm a beginner contributor and would like to contribute to this, but it'd take me some time to understand what this issue is about. Is that alright?

**Comment by stickies-v** [comment]
Absolutely, just open the PR whenever you feel ready, or ask away here if you have any problems you can't figure out.

**Comment by ItIsOHM** [comment]
> Absolutely, just open the PR whenever you feel ready, or ask away here if you have any problems you can't figure out.

Hey @stickies-v! So as a starter, I don't have bitcoin-cli working, so to do that I'm building the core with Visual Studio by following this guide : https://github.com/bitcoin/bitcoin/blob/master/build_msvc/README.md, is that alright or do I need to follow some other step to use `bitcoin-cli`?

**Comment by ItIsOHM** [comment]
Update: I downloaded and installed `Bitcoin Core`, which then helped me to run `bitcoind` and `bitcoin-cli`. I'll try to make the changes to a new branch :D

**Comment by ItIsOHM** [comment]
> MSVC is one option, WSL another. See also https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md.
> 
> Build questions are a bit out of scope for this issue though, there's a fair amount of documentation online. Just downloading the binaries isn't enough to work on this, you need to compile it yourself to verify the changes are correct.

Before using `Bitcoin Core` I actually used `build_msvc` which gave me a bunch folders with `*.vcxproj` files, however I was unsure where to head after that so I went and downloaded `Bitcoin Core`.

And to compile it what am I supposed to use? My guess would be building it again using `msvc-autogen.py` after making the changes?

**Comment by ItIsOHM** [comment]
Hello @stickies-v, I added these two entries after `rules` in `template_request`:
![image](https://github.com/bitcoin/bitcoin/assets/62976081/27350458-8c08-49ce-a0fa-b8685b0ac68e)

Is this correct? I'm sorry if it's wrong, I'm just a beginner with this.

**Comment by stickies-v** [comment]
The description for "data" is wrong, copy-pasting from another (unrelated) data field is not a good approach here. I would suggest digging into the code to understand what "data" is used for, and/or reading the spec of [BIP22](https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki) and [BIP23](https://github.com/bitcoin/bips/blob/master/bip-0023.mediawiki)

**Comment by ItIsOHM** [comment]
> The description for "data" is wrong, copy-pasting from another (unrelated) data field is not a good approach here. I would suggest digging into the code to understand what "data" is used for, and/or reading the spec of [BIP22](https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki) and [BIP23](https://github.com/bitcoin/bips/blob/master/bip-0023.mediawiki)

Oh yes I agree, I'll read more about it and change the descriptions. I was asking in terms of syntax and usage, if it was correct to implement it in this way or If I needed to do something else.

**Comment by stickies-v** [comment]
Yeah the approach is good. Great, have a look and then for further implementation feedback I'd suggest you open a PR with the code changes (definitely worth going through [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) first).

**Comment by ItIsOHM** [comment]
Hello @stickies-v, sorry for the delay. I recently made a PR (https://github.com/bitcoin/bitcoin/pull/28056) and changed the description of the parameters, taking help from BIP 22 and BIP 23 as you suggested. But I am still unsure if it's a totally correct description or not, hence I have marked it as WIP.

I apologize if these changes aren't correct as I'm just a beginner here.

**Comment by ItIsOHM** [comment]
> > hey i am a newbie can anyone guide me what to do next to become a first contributor (this is my first project)
> 
> Hi @iemafzalhassan (and other future contributors), I suggest the articles section of https://jonatack.github.io.

Thanks a lot for this @jonatack!
