### ISSUE TITLE
Bitcoin core hidden services link down/doesnt work

### ISSUE THREAD

**Issue by TNTBOMBOM** [bitcoin/bitcoin#28054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Bitcoin core hidden services website entry not functional.

### Expected behaviour

It should work/connect.

### Steps to reproduce

Just visit the URL with your TB. or you can test the [onion URL](http://6hasakffvppilxgehrswmffqurlcjjjhd76jgvaqmsg6ul25s7t3rzyd.onion/) here:

https://onions.danwin1210.de/test.php

Output: `No, the service is offline!`

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

na

### Operating system and version

na

**Comment by willcl-ark** [comment]
Thanks for the report @TNTBOMBOM.

I am going to close this issue here as it's more appropriate for the bitcoincore.org repo, and I've taken the liberty of opening an equivalent issue over there on your behalf: https://github.com/bitcoin-core/bitcoincore.org/issues/985
