### ISSUE TITLE
Internal bug detected: "isValid == error_msg.empty()" when validateaddress(bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v07qwwzcrf)

### ISSUE THREAD

**Issue by meglio** [bitcoin/bitcoin#28064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

validateaddress(bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v07qwwzcrf)

when calling through rpc api, throws an error:

```
Internal bug detected: "isValid == error_msg.empty()"
rpc/output_script.cpp:64 (operator())
Bitcoin Core v25.0.0
Please report this issue here: https://github.com/bitcoin/bitcoin/issues
```

### Expected behaviour

Address validation to return is_valid=false in the rpc api result.

This address `bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v07qwwzcrf` is taken from the test vectors found here:

https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki

### Steps to reproduce

Call RPC API: validateaddress(bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7v07qwwzcrf)

### Relevant log output

```
Internal bug detected: "isValid == error_msg.empty()"
rpc/output_script.cpp:64 (operator())
Bitcoin Core v25.0.0
Please report this issue here: https://github.com/bitcoin/bitcoin/issues
```

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v25.0.0

### Operating system and version

MacOS Ventura 13.4 (22F66)

**Comment by fanquake** [comment]
Closing, given the fix has been backported. @meglio if you're able to compile the 25.x branch, and confirm this fixes your issue, please do.
