### ISSUE TITLE
libsecp CI failure [no wallet, libbitcoinkernel] [focal]

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#28079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

CI failure: https://cirrus-ci.com/task/5453591138271232

### Relevant log output

```
FAIL: tests
===========

test count = 64
random seed = 81af32fd7ab8c9cbc2e62a689f642106
src/modules/ellswift/tests_impl.h:396: test condition failed: secp256k1_memcmp_var(share32_bad, share32a, 32) != 0
FAIL tests (exit status: 134)
```

**Comment by Realrobwoodx** [comment]
Can someone tell me why this contract took all my Op tokens and how I can get them back without the feds?

**Comment by jonasnick** [comment]
Thanks for reporting. This is an actual bug in the secp256k1 test harness. https://github.com/bitcoin-core/secp256k1/pull/1378
