### ISSUE TITLE
Error: This wallet has no available keys (code -4)

### ISSUE THREAD

**Issue by JaviVald10** [bitcoin/bitcoin#28117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I am new and I just installed Bitcoin core, so I'm learning. However, I cannot get a new receiving address and I don't know why!!
![bitcoin core bug 1](https://github.com/bitcoin/bitcoin/assets/140161334/3c7a14ab-c6e2-4387-9537-89f531151831)
I also tried to use the command 
/getnewaddress but then it pops up an error saying "this wallet has no available keys (code -4)". I also tried the command /importprivkey but nothing happend. My english is not the best so it is a little bit hard for me to understand everithing (I'm spanish) 
![image](https://github.com/bitcoin/bitcoin/assets/140161334/7fe64338-2c46-469a-a05d-d711b1414a3b)
Please, I'm going crazy with this issue.

### Expected behaviour

I thought that I would get a new receiving address but the button was greyed out

### Steps to reproduce

Tbh Idk how to produce this I only know what happened to me.
![image](https://github.com/bitcoin/bitcoin/assets/140161334/437397aa-f64c-402e-9b8d-d975eb881833)

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

Bitcoin Core version v22.0.0

### Operating system and version

Microsoft Windows version 22H2

**Comment by pinheadmz** [comment]
How did you create the wallet? There is an option to disable private keys. Don't use it!


<img width="426" alt="Screen Shot 2023-07-21 at 7 25 43 AM" src="https://github.com/bitcoin/bitcoin/assets/2084648/4494846d-168e-4cb7-84b3-275aa822b505">

**Comment by JaviVald10** [comment]
I do not remember, I'm gonna try to create another one

**Comment by JaviVald10** [comment]
OMG NOW I CAN THANK YOU SO MUCH

**Comment by pinheadmz** [comment]
🎯
