### ISSUE TITLE
"missing operand" assembler warnings on Windows

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#28111]
On the master branch @673acab223c0f896767b1ae784659df9f95452ae on Ubuntu 23.04:

```
$ make -C depends HOST=x86_64-w64-mingw32 NO_QT=1 DEBUG=1 NO_HARDEN=1
$ ./configure CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site
$ make
...
  CXX      crypto/libbitcoin_crypto_base_la-aes.lo
  CXX      crypto/libbitcoin_crypto_base_la-chacha_poly_aead.lo
  CXX      crypto/libbitcoin_crypto_base_la-chacha20.lo
  CXX      crypto/libbitcoin_crypto_base_la-hkdf_sha256_32.lo
  CXX      crypto/libbitcoin_crypto_base_la-hmac_sha256.lo
  CXX      crypto/libbitcoin_crypto_base_la-hmac_sha512.lo
  CXX      crypto/libbitcoin_crypto_base_la-poly1305.lo
  CXX      crypto/libbitcoin_crypto_base_la-muhash.lo
  CXX      crypto/libbitcoin_crypto_base_la-ripemd160.lo
  CXX      crypto/libbitcoin_crypto_base_la-sha1.lo
  CXX      crypto/libbitcoin_crypto_base_la-sha256.lo
  CXX      crypto/libbitcoin_crypto_base_la-sha3.lo
  CXX      crypto/libbitcoin_crypto_base_la-sha512.lo
  CXX      crypto/libbitcoin_crypto_base_la-siphash.lo
  CXX      crypto/libbitcoin_crypto_base_la-sha256_sse4.lo
{standard input}: Assembler messages:
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
  CXXLD    crypto/libbitcoin_crypto_base.la
...
```

Having a non-hardened build, the actual reason for the warnings is the absence of the `-fstack-protector-all` flag.

cc @sipa

**Comment by fanquake** [comment]
I don't understand what the actual problem is, or what is broken? Can you elaborate?

**Comment by fanquake** [comment]
Probably needs some actual investigation then:
i.e what code + combination of compiler flags is causing the issue, produce a minimal test case.
Is this a "new" issue, or have the warnings existed in our codebase "forever".
Is it related to the fact that you're using ubuntu mantic (devel) and/or compiler/binutils versions etc.

**Comment by fanquake** [comment]
> Try this:
> (replace "+m" with "+o" at the end of the line)

The same warnings occur with that diff:
```bash
# git diff
diff --git a/src/crypto/sha256_sse4.cpp b/src/crypto/sha256_sse4.cpp
index f4557291c..ebc99aa64 100644
--- a/src/crypto/sha256_sse4.cpp
+++ b/src/crypto/sha256_sse4.cpp
@@ -949,7 +949,7 @@ void Transform(uint32_t* s, const unsigned char* chunk, size_t blocks)
 
         "Ldone_hash_%=:"
 
-        : "+r"(s), "+r"(chunk), "+r"(blocks), "=r"(a), "=r"(b), "=r"(c), "=r"(d), /* e = chunk */ "=r"(f), "=r"(g), "=r"(h), "=r"(y0), "=r"(y1), "=r"(y2), "=r"(tbl), "+m"(inp_end), "+m"(inp), "+m"(xfer)
+        : "+r"(s), "+r"(chunk), "+r"(blocks), "=r"(a), "=r"(b), "=r"(c), "=r"(d), /* e = chunk */ "=r"(f), "=r"(g), "=r"(h), "=r"(y0), "=r"(y1), "=r"(y2), "=r"(tbl), "+m"(inp_end), "+m"(inp), "+o"(xfer)
         : "m"(K256), "m"(FLIP_MASK), "m"(SHUF_00BA), "m"(SHUF_DC00)
         : "cc", "memory", "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8", "xmm9", "xmm10", "xmm11", "xmm12"
    );

# make -C src crypto/libbitcoin_crypto_base_la-sha256_sse4.lo
make: Entering directory '/bitcoin/src'
  CXX      crypto/libbitcoin_crypto_base_la-sha256_sse4.lo
{standard input}: Assembler messages:
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
{standard input}:42: Warning: missing operand; zero assumed
make: Leaving directory '/bitcoin/src'
```

**Comment by hebasto** [comment]
> Can someone compile with `-save-temps` and get me the sha256_sse4.s file?

For the master branch:
- https://github.com/hebasto/artefacts/blob/master/issue-28111/asm-master/sha256_sse4.s

Master branch + the [patch](https://github.com/bitcoin/bitcoin/issues/28111#issuecomment-1644167053):
- https://github.com/hebasto/artefacts/blob/master/issue-28111/asm-patched/sha256_sse4.s

**Comment by hebasto** [comment]
> So... can you try if that (substitute `+%16` everywhere with `+0%16`) works?

It compiles. Going to run tests.

**Comment by hebasto** [comment]
The `crypto_tests` test suit passes as well.

To ensure that the SSE4 implementation is being tested, `ENABLE_X86_SHANI`, `ENABLE_SSE41` and `ENABLE_AVX2` were disabled manually, that was confirmed in `debug.log`:
```
2023-07-20T18:38:31Z Using the 'sse4(1way)' SHA256 implementation
```

**Comment by hebasto** [comment]
@sipa
> Ok so what seems to be happening is that in your build, `%16` gets mapped to `(%rsp)` (aka the memory address stored in the stack pointer), which in a few places gets used as e.g. `8+%16`, which results in `8+(%rsp)`, and that appears to be invalid asm code.
> 
> On my system (and presumably ~every build we have since this code was introduced), `%16` is mapped to `16(%rsp)` (16 bytes further than the memory address stored in the stack pointer), and thus `8+%16` becomes `8+16(%rsp)`, which is 24 bytes further than the memory address stored in the stack pointer.

Is there any reasonable explanation why the `-fstack-protector-all` compiler flag affects that mapping?

**Comment by fanquake** [comment]
I don't actually think it even prevents compilation, and only warns? Unclear from the issue.

**Comment by hebasto** [comment]
> I don't actually think it even prevents compilation, and only warns? Unclear from the issue.

Only warnings. Compilation succeeds.

**Comment by hebasto** [comment]
> Errr, if it doesn't prevent compilation it's possible that the result is wrong (when the warning is emitted). Do tests pass?

They do.

**Comment by fanquake** [comment]
Ok, going to close this for now then. Looks like next steps are to open an issue upstream with binutils, and report the (potential) false positive.

**Comment by fanquake** [comment]
@hebasto did you open an issue to track this upstream? Can you link it here?

**Comment by fanquake** [comment]
Run into this again recently. Did it ever get reported upstream?
