### ISSUE TITLE
Raise maximum -dbcache setting

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#28249]
### Please describe the feature you'd like to see added.

`nMaxDbCache` was set to 16 GB back in 2015:  https://github.com/bitcoin/bitcoin/commit/b3ed4236beb7f68e1720ceb3da15e0c3682ef629#diff-d102b6032635ce90158c1e6e614f03b50e4449aa46ce23370da5387a658342fd

The UTXO set has been growing significantly over the past few months so we should probably raise it.

### Is your feature related to a problem, if so please describe it.

Doing IBD without flushing dbcache is faster. That said, I'm not sure how much one single flush matters.

### Describe the solution you'd like

Make `nMaxDbCache` bigger.

### Please leave any additional context

Much growth recently:
https://statoshi.info/d/000000009/unspent-transaction-output-set?orgId=1&from=now%2Fy&to=now&refresh=5s&viewPanel=8

**Comment by Sjors** [comment]
cc @sipa

**Comment by russeree** [comment]
Would the eBPF USDT tracepoints for the UTXO cache be of use here as a way to measure the overall impact of these flush operations during and IBD?

https://github.com/bitcoin/bitcoin/tree/master/contrib/tracing#log_utxocache_flushpy

**Comment by Sjors** [comment]
@sipa I ran an IBD as part of testing #27596. Since I did a restart after the cache initially hit 1 GB, the data is not accurate, but the cache reached 13,334 MiB at block at block 798,000. A month earlier at 794,000 the log shows it as 12,766 MiB. So the memory footprint is growing ~7 GB per year (and that's not even the worst month, see [chart I linked to above](https://statoshi.info/d/000000009/unspent-transaction-output-set?orgId=1&from=now%2Fy&to=now&refresh=5s&viewPanel=8)).

**Comment by Sjors** [comment]
Opened a PR to double it.
