### ISSUE TITLE
Make it very obvious to the new people that the Bitcoin Core program first needs to be installed and run on the "C" drive. 

### ISSUE THREAD

**Issue by Rlavington** [bitcoin/bitcoin#28268]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

Hello developers,

I know that you probably think that this is so obvious and basic but it needs to be said. 

When a new person wants to run a full BTC node on their computer for the first time can you make it very obvious to that person that the Bitcoin Core program needs to be downloaded and installed onto their "C" drive of their computer first.  

Then that person will have the ability to sync up and store the BTC blockchain to what every drive they intend, whether that be the "D" drive of their computer or an external HDD or SSD so that they can carry around the node with them. 

The problem i had was that i had downloaded and installed the Bitcoin Core program onto an external HDD, then i plugged that external HDD into my laptop thinking that it would just carry on syncing up, it did not because the Bitcoin Core program needs to be already installed on to the C drive of the laptop first, then i would need to point the program as to where it needs to sync up the data to (in this case my external HDD or that I'm not using up all of the space on the laptop). 

Thanks !

**Comment by samyan** [comment]
Anyways you can install the program in C and put the node database in other drive.

**Comment by Rlavington** [comment]
> Anyways you can install the program in C and put the node database in other drive.

That's exactly what I do. Because I don't want to use up all of the space on my computer's hard drive. 

Untill the price of SSDs come down, I will upgrade.

**Comment by samyan** [comment]
> > Anyways you can install the program in C and put the node database in other drive.
> 
> That's exactly what I do. Because I don't want to use up all of the space on my computer's hard drive.
> 
> Untill the price of SSDs come down, I will upgrade.

Well, I think you are doing something wrong because I have both windows and linux (debian 11) and it works perfectly.

**Comment by Rlavington** [comment]
> > I guess your issue is about the GUI choose-direcory dialog?
> 
> FWIW, this dialog is enabled by default during the first run of the Bitcoin Core GUI.

Yes, it does. However, I made the mistake of having the Bitcoincore Program on the HDD itself. 

When it should have been on the "C" drive of the computer, with the OS as well. 

Then I have the option of syncing the Bitcoin data onto another drive. So that I'm not using up all of the space on the "C" drive.

**Comment by russeree** [comment]
> Yes, it does. However, I made the mistake of having the Bitcoin core Program on the portable HDD itself.

Bitcoin Core was still able to run from your external HDD/SSD correct?

**Comment by Rlavington** [comment]
> > Yes, it does. However, I made the mistake of having the Bitcoin core Program on the portable HDD itself.
> 
> Bitcoin Core was still able to run from your external HDD/SSD correct?

It was able to run yes. 

However, it kept on wanting to re-sync up again from 0.0%

Even when the full block file of 530gb was already on the HDD. 

It was as if it wasn't detecting that the full Bitcoin Blockchain was already there on the HDD. 

But when I installed the Bitcoin Core program on to the "C" drive. Then told it where it should write the new Bitcoin Data it then started at 95% synced, and followed further with 100% synced. 

Problems solved.

**Comment by russeree** [comment]
So the issue originates with the default search location for the bitcoin.conf file. That file likely didn't contain the datadir flag when it was first installed to the external drive. By reinstalling to C: you triggered the prompt that requests location of the datadir and then writes that to bitcoin.conf after the confirm. As such after completing the dialog the location of your blocks was stored.

[See this wiki about the bitcoin data directory](https://en.bitcoin.it/wiki/Data_directory)

As a test could you reinstall to the external drive in a fresh directory and let me know if the data directory popup shows on the first launch?

**Comment by willcl-ark** [comment]
Your issue seems out of scope for the bitcoin core codebase, see StackExchange for help with usage.
