### ISSUE TITLE
Any JavaScript functional test for this repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [bitcoin/bitcoin#28270]
### Motivation

Hi,
I am learning Bitcoin using this repo, and I have some experience with JavaScript, but my level with Python is very limited.  I want to run some tests using JavaScript, but I found that all the functional tests are in Python.  I want to know if it is possible to have the same functional tests in JavaScript.
Or give me some ideas on how can I do this with JavaScript?
For example for test_node.py and test_framework.py; if I want to use JavaScript with Bitcoin-core npm package, can I do the same as test_node.py & test_framework.py using JavaScript.  I can rewrite all the Python code in JavaScript with help of AI.  But give me some ideas on how to setup the environment: like setup 2 bitcoin core nodes (Alice & Bob) in a docker image with regest mode, so later I can use JavaScript to mine some BTCs in Alice node and send half of the mined BTCs to Bob.  In short, how to setup environment and run some tests in JavaScript like what the test_node.py & test_framework.py (under functional/test_frawmwork/ folder) can do?

### Possible solution

Need some advice

### Useful Skills

JavaScript

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by russeree** [comment]
This would not be possible without a large refactor. The Bitcoin-core npm package is very good for communicating with the bitcoind server to run RPC commands, the internal testing suite of python code spins up various instances of bitcoind with different flags and executes commands against those instances. 

All in all the npm Bitcoin core package would not  be a good candidate as a wrapper for test_runner.py  

This issue should be closed.
