### ISSUE TITLE
bitcoin-wallet reported as Wacatac malware

### ISSUE THREAD

**Issue by xdemiansmithx** [bitcoin/bitcoin#28415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Running gpg verified binaries leads to "An active 'Wacatac' malware was prevented"

### Expected behaviour

Not triggering the incident

### Steps to reproduce

Follow https://bitcoin.org/en/full-node#mac-os-x-yosemite-1010x:

- curl -O https://bitcoin.org/bin/bitcoin-core-25.0/ar -zxf bitcoin-25.0-arm64-apple-darwin.tar.gz
- cd Downloads && gpg --verify SHA256SUMS.asc
- tar -zxf bitcoin-25.0-arm64-apple-darwin.tar.gz
- sudo cp bitcoin-25.0/bin/bitcoin* /usr/local/bin/.
- run bitcoind

### Relevant log output

An active 'Wacatac' malware was prevented

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

25.0-arm64-apple-darwin

### Operating system and version

macOS Ventura 13.5.1

### Machine specifications

apple silicone chip

**Comment by fanquake** [comment]
> In this instance this was Microsoft Defender. 

Ok. Only thing to do here is report the issue to Microsoft, maybe using https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/air-report-false-positives-negatives?view=o365-worldwide#report-a-false-positivenegative-to-microsoft-for-analysis.

Closing this issue, as there's nothing further for us to do.
