### ISSUE TITLE
Proof of work change

### ISSUE THREAD

**Issue by cezar1** [bitcoin/bitcoin#28420]
### Please describe the feature you'd like to see added.

Maybe I am naive about it but I'd like to ask nonetheless. Could the hash algorithm be modified in following way:

- transactions are valid (every address that wants to send something actually has that something)
- block template is ready (list of all transactions available to that mining node)
- the hash of each nonce should have an *additional* final hash that is based on a lookup in the blockchain raw data itself

The idea is to bring the PoW back to a machine that has resources similar to a PC (which may be closer to Satoshi's original vision), namely a lot of RAM or HDD.

For example if the hash of the block is :
SHA-256 Hash: d1bde2f3a4b5d8df0b556b256abf479f9a0f0a9ec2071a1d1e2d2ea21e5ce10d

Then each of the characters above like d , 1, b , d ... etc would have to do some lookup that goes in binary mode through the entire blockchain content (500+ GB at the moment).

ChatGPT's take on it https://chat.openai.com/share/6264dca8-644e-402b-ae5b-f3382f8fbc8f

**Comment by mkohlhaas** [comment]
Bitcoin uses a flawed concept. Don't change it!
