### ISSUE TITLE
test: Intermittent issue in wallet_resendwallettransactions "Unable to create transaction. Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate) (-4)"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#28491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

https://github.com/bitcoin/bitcoin/actions/runs/6198134719/job/16828006466#step:28:2207

```
  node0 2023-09-15T14:01:45.132127Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\validation.cpp:1102] [Finalize] [mempool] replacing tx bda7041b708336708a9df4bb8c2b5d934439736285253d33820923aaca732b59 (wtxid=f380f631e37abd715addb85cf8a76f27f2df70e7098ba1678cab9bc1f910fb68) with 7c0c53abb2cb5ae0918e761e53bbf1f3fef2b1a1fcb9531fcdbf1642c3cbbef4 (wtxid=183c420f88d2fd222b82c5bb0e5d4aefc51312453c94753f409abad0e0c2d594) for 0.03254028 additional fees, 0 delta bytes 
 node0 2023-09-15T14:01:45.132212Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\validationinterface.cpp:223] [TransactionRemovedFromMempool] [validation] Enqueuing TransactionRemovedFromMempool: txid=bda7041b708336708a9df4bb8c2b5d934439736285253d33820923aaca732b59 wtxid=f380f631e37abd715addb85cf8a76f27f2df70e7098ba1678cab9bc1f910fb68 reason=replaced 
 node0 2023-09-15T14:01:45.132315Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\txmempool.cpp:1029] [RemoveUnbroadcastTx] [mempool] Removed bda7041b708336708a9df4bb8c2b5d934439736285253d33820923aaca732b59 from set of unbroadcast txns before confirmation that txn was sent out 
 node0 2023-09-15T14:01:45.132414Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\validationinterface.cpp:213] [TransactionAddedToMempool] [validation] Enqueuing TransactionAddedToMempool: txid=7c0c53abb2cb5ae0918e761e53bbf1f3fef2b1a1fcb9531fcdbf1642c3cbbef4 wtxid=183c420f88d2fd222b82c5bb0e5d4aefc51312453c94753f409abad0e0c2d594 
 node0 2023-09-15T14:01:45.132505Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\txmempool.cpp:660] [check] [mempool] Checking mempool with 2 transactions and 2 inputs 
 node0 2023-09-15T14:01:45.132776Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\wallet\sqlite.cpp:53] [TraceSqlCallback] [D:\a\_temp\test_runner_₿_🏃_20230915_132301\wallet_resendwallettransactions_69\node0\regtest\default_wallet\wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
 node0 2023-09-15T14:01:45.133944Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\httpserver.cpp:255] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54896 
 node0 2023-09-15T14:01:45.134128Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\rpc\request.cpp:181] [parse] [rpc] ThreadRPCServer method=syncwithvalidationinterfacequeue user=__cookie__ 
 node0 2023-09-15T14:01:45.134317Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\validationinterface.cpp:223] [operator ()] [validation] TransactionRemovedFromMempool: txid=bda7041b708336708a9df4bb8c2b5d934439736285253d33820923aaca732b59 wtxid=f380f631e37abd715addb85cf8a76f27f2df70e7098ba1678cab9bc1f910fb68 reason=replaced 
 node0 2023-09-15T14:01:45.134416Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\validationinterface.cpp:213] [operator ()] [validation] TransactionAddedToMempool: txid=7c0c53abb2cb5ae0918e761e53bbf1f3fef2b1a1fcb9531fcdbf1642c3cbbef4 wtxid=183c420f88d2fd222b82c5bb0e5d4aefc51312453c94753f409abad0e0c2d594 
 node0 2023-09-15T14:01:45.136375Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\wallet\sqlite.cpp:53] [TraceSqlCallback] [D:\a\_temp\test_runner_₿_🏃_20230915_132301\wallet_resendwallettransactions_69\node0\regtest\default_wallet\wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
 node0 2023-09-15T14:01:45.139157Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\wallet\sqlite.cpp:53] [TraceSqlCallback] [D:\a\_temp\test_runner_₿_🏃_20230915_132301\wallet_resendwallettransactions_69\node0\regtest\default_wallet\wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
 node0 2023-09-15T14:01:45.139450Z (mocktime: 2023-09-17T02:11:43Z) [D:\a\bitcoin\bitcoin\src\wallet\wallet.h:918] [WalletLogPrintf] [default_wallet] AddToWallet 7c0c53abb2cb5ae0918e761e53bbf1f3fef2b1a1fcb9531fcdbf1642c3cbbef4 
 test  2023-09-15T14:01:45.140000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 131, in main
                                       self.run_test()
                                     File "D:\a\bitcoin\bitcoin/test/functional/wallet_resendwallettransactions.py", line 94, in run_test
                                       bumped = node.bumpfee(child_txid)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\coverage.py", line 50, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\authproxy.py", line 129, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: Unable to create transaction. Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate) (-4)
```

### Expected behaviour

-

### Steps to reproduce

-

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

-

### Operating system and version

-

**Comment by hebasto** [comment]
Another failure on 32-bit Centos: https://cirrus-ci.com/task/6154898278973440

**Comment by mzumsande** [comment]
> In a first glance, might be happening because we brute force the child tx position in the wallet's map using `bumpfee`. So, might be the case we bumped the tx a large number of times and surpassed the wallet's `-maxtxfee`.

Looks like before 2e35e944dab09eff30952233f8dfc0b12c4553d5 we could bump the tx thousands of times without getting this error, whereas after that commit we get the error exactly after the 10th bump (you can see that the fee more than doubles in each iteration when you print the result of `bumpfee`). Accordingly, the intermittent failures started after #26152 was merged (fyi @murchandamus) I didn't review that PR, so the question is if that doubling is expected, and, if so, does that mean the trick of using `bumpfee` / `removeprunedfunds` to ensure an order in `mapWallet` is no longer feasible?

**Comment by murchandamus** [comment]
Oh, I think I see why the fee is now growing exponentially:

Let’s say we have a parent transaction `p` and a child transaction `c` that both start at a feerate of 1 ṩ/vB. When we replace `c` with `c₂`. The feerate of `c₂` must exceed the feerate of `c` by at least one incremental feerate, i.e. be 1 ṩ/vB higher than that of `c`. However, to ensure that `c₂` actually achieves a feerate of 2 ṩ/vB, we’d also add fees to bump the parent to 2 ṩ/vB. Assuming `p`, `c`, and `c₂` are all the same size, `c₂` now has a feerate of 3 ṩ/vB so that `{p, c₂}` have an effective feerate of 2 ṩ/vB.

Now, we try to replace `c₂` with `c₃`. To exceed the feerate of `c₂` by 1 ṩ/vB, `c₃` must pay 4 ṩ/vB. To bump `p` to 4 ṩ/vB, `c₃` needs to pay 7 ṩ/vB.  
To replace `c₃` with `c₄`, we aim for a feerate of 8 ṩ/vB, but to bump `p` to 8 ṩ/vB, `c₄` needs to pay `15 ṩ/vB, etc.…

While this is the behavior we would want when we create a new transaction that should achieve the given feerate or when using RBF to reprioritize the child transaction, we might not want to bump the parent to the same feerate when we only replace the latest child to update its recipients. We might need to revisit this question more generally in the context of `bumpfee`.

**Comment by murchandamus** [comment]
In the context of this test, would it perhaps be possible to first grind the parent transaction a bit to make it deliberately sort further back in the mempool? That might sufficiently increase the chances of the child to sort to the front with fewer attempts.

**Comment by achow101** [comment]
> In the context of this test, would it perhaps be possible to first grind the parent transaction a bit to make it deliberately sort further back in the mempool? That might sufficiently increase the chances of the child to sort to the front with fewer attempts.

It's not about mempool sorting, it's about sorting within the wallet's `mapWallet`.

However this does seem like there may be a bug in calculating the ancestor bump fees. I don't think it should be going up exponentially.
