### ISSUE TITLE
build: `libbitcoin_util` unexpected(?)/undocumented dependencies

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#28548]
According to our design [docs](https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md):
> _libbitcoin_util_ ... should not depend on other internal libraries.

However, it effectively depends on the following internal libraries:
1. _libbitcoin_crypto_, which provides symbols as follows:
	- `CSHA256`
	- `CSHA512`
	- `CSipHasher`
	- ...

2. _libbitcoin_consensus_, which provides symbols as follows:
	- `CPubKey::RecoverCompact`

3. _libbitcoin_common_, which provides symbols as follows:
	- `PKHash(const CPubKey&)`
	- `ArgsManager::AddArg`
	- `ArgsManager::SelectConfigNetwork`
	- `DecodeDestination`
	- `IsValidDestination`
	- `CKey::SignCompact`

However, _libbitcoin_crypto_ and _libbitcoin_common_ themselves depend on _libbitcoin_util_.

The diverging from our design goals does not break builds because at the link stage, all dependent libraries are passed to the linker.

**Comment by hebasto** [comment]
cc @ryanofsky @TheCharlatan

**Comment by ryanofsky** [comment]
It's be helpful to know which compilation units in libbitcoin_util are using the symbols in libbitcoin_consensus and libbitcoin_common, but I'd guess probably that code should just be moved out of libbitcoin_util into one of those libraries.

I think the libbitcoin_crypto dependencies are probably not a concern. The [libraries document](https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md) doesn't even mention  libbitcoin_crypto, so I it could be added as depenency of libbitcoin_util.

**Comment by hebasto** [comment]
> It's be helpful to know which compilation units in libbitcoin_util are using the symbols in libbitcoin_consensus...

It is the `CPubKey::RecoverCompact` symbol in `message.cpp`. Please see #28549,

**Comment by hebasto** [comment]
> It's be helpful to know which compilation units in libbitcoin_util are using the symbols in ... libbitcoin_common...

I'll provide mode details shortly.

**Comment by hebasto** [comment]
> > It's be helpful to know which compilation units in libbitcoin_util are using the symbols in ... libbitcoin_common...
> 
> I'll provide mode details shortly.

- `src/chainparamsbase.cpp`
- `src/clientversion.cpp`
- `src/util/error.cpp`
- `src/util/message.cpp`

**Comment by ryanofsky** [comment]
Looks like this issue should be resolved by #28548, which makes util no longer depend on common or consensus libraries. It does still depend on the crypto library, which #28548 handles by just documenting the dependency. Another option could be to move RNG and hashing functionality out of util so it does not depend on the crypto library anymore, but for now there does not seem to be a reason to do this.

**Comment by willcl-ark** [comment]
Seems that we can close this now that #29015 has been merged.

Let me know if this is a mistake and this shouldn't be closed until `libbitcoin_util` doesn't depend on `libbitcoin_crypto`.
