### ISSUE TITLE
How should I debug this error?

### ISSUE THREAD

**Issue by zzylmt** [bitcoin/bitcoin#28568]
I modified some parameters in chainparams.cpp and then when I recompile I get the error below, can anyone help me with that? How should I fix this error?

BTW,I have already got new genesis block hash,but the error appeared at the end.

key.cpp:238: bool CKey::Sign(const uint256&, std::vector&, bool, uint32_t) const: Assertion `ret' failed. core has been dump

**Comment by willcl-ark** [comment]
Please ask questions about developing an altcoin elsewhere.

This issue tracker is used to track technical issues related to the Bitcoin Core code base.

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on the [Libera Chat](https://libera.chat/) network.

For proposed protocol changes you can post to the bitcoin-dev [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev).

For general bitcoin discussion you can try [bitcointalk](bitcointalk.org) or [reddit.com/r/bitcoin](reddit.com/r/bitcoin)
