### ISSUE TITLE
Add a new parameter to "listaccounts" - "includeempty=false"?

### ISSUE THREAD

**Issue by ThePiachu** [bitcoin/bitcoin#2858]
In a few API calls (like "listreceivedbyaccount") we have a parameter "includeempty=false", which I think if a pretty useful flag to have when requesting various lists. This way the amount of data transferred in an API call can be truncated to something meaningful for users that are not interested in empty accounts (which most of them probably wouldn't be) and it would make this API call more consistent with other API calls.

**Comment by laanwj** [comment]
The account system has now been deprecated for a long time (see #3816), so I am closing feature requests involving it.
