### ISSUE TITLE
Gathering Priorities for 27.0

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#28599]
Please nominate projects that could become priorities for the next ~6 months (until the 27.0 release). We (frequent contributors) will vote on which projects will be priorities next week in a separate issue.

Project priorities are those which the frequent contributors to this project have voted on to have more focused review on for the next ~6 months. This issue is to list what projects are ongoing that can be voted on. Voting will occur in a separate issue that will be opened next week.

Nominations will close at the start of the IRC meeting on October 12th at 14:00 UTC. The issue for voting will be opened at that time as well.

Nominations and voting is limited to those who are part of the bitcoin github organization. Comments in this issue from those outside of the organization will be ignored, and may be deleted. If you are not part of the organization and believe that you should be, please send me an email or message me on IRC.

Initial list from recent CoreDev:

* Multiprocess #10102 
* Silent payments #28536
* Package Relay #27463
* Legacy wallet (BDB) removal #20160
* Erlay #21515
* Cmake #28607
* Kernel #27587
* Logging Migration #25203
* Stratum V2 #27854
* Cluster mempool #27677

AssumeUTXO and BIP 324 were on this list originally, but they seem to be done now?

**Comment by josibake** [comment]
Tracking issue for silent payments: https://github.com/bitcoin/bitcoin/issues/28536

**Comment by jamesob** [comment]
I'd say "getting mainnet UTXO snapshot chainparams" committed would be a pretty valuable target, but given that's only about 6 added lines maybe it doesn't merit a place on this list...

**Comment by ajtowns** [comment]
Is anyone working on musig2 support? see #23326 #24861 ; presumably needs musig to be merged into libsecp256k1 from libsecp256k1-zkp ; [musig descriptors](https://gist.github.com/sipa/06c5c844df155d4e5044c2c8cac9c05e) ; ...?

Suggested links for some of the things that don't have tracking issues:

 * erlay: #21515
 * cmake: https://github.com/hebasto/bitcoin/pull/31 or #25797
 * cluster mempool: https://btctranscripts.com/bitcoin-core-dev-tech/2023-04/2023-04-25-mempool-clustering/

**Comment by hebasto** [comment]
> Suggested links for some of the things that don't have tracking issues:
> 
>     * cmake: [Rebased `cmake-staging` branch (post PRs 17, 18, 19) hebasto/bitcoin#31](https://github.com/hebasto/bitcoin/pull/31) or [build: Add CMake-based build system #25797](https://github.com/bitcoin/bitcoin/pull/25797)

I've opened one for CMake project: https://github.com/bitcoin/bitcoin/issues/28607.

**Comment by glozow** [comment]
for stratum v2, maybe link #27854 ?
