### ISSUE TITLE
How to communicate with the web service

### ISSUE THREAD

**Issue by Hossein-Teimouri** [bitcoin/bitcoin#28596]
I am currently connecting to my bitcoin node via the command line
for example :
```
bitcoin-cli -named -rpcuser=admin -rpcpassword=1475963-test -rpcport=8332 -rpcwallet=test-01 sendtoaddress address=DMvWAyQUNJeeKr6xJpeXybVYZLi9nT2oze amount=0.1
```

And now I want to do this through the web service
```
curl --user admin:1475963-test --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "sendtoaddress", "params": ["DMvWAyQUNJeeKr6xJpeXybVYZLi9nT2oze ", 0.1] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```
-How should I use -rpcwallet with web service(curl)?

**Comment by pinheadmz** [comment]
The wallet name is part of the endpoint URL.

You may have seen an error message like this:
```
Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).
```

and so your solution is going to look like this:

```
$ curl u:p@127.0.0.1:18443/wallet/test-01 --data '{"method":"getbalance"}'
{"result":0.00000000,"error":null,"id":null}
```

**Comment by fanquake** [comment]
@Hossein-Teimouri Any followup here? Otherwise I think this can be closed.

**Comment by pinheadmz** [comment]
Closing for now, @Hossein-Teimouri feel free to add comments if you are still having trouble. Or ask a question on https://bitcoin.stackexchange.com/
