### ISSUE TITLE
Extend feature_init.py file perturbations

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#28603]
### Motivation

`feature_init.py` is a functional test that perturbs various files in the data directory (simulation data corruption), and checks the response during startup.

Recently, this test was improved in #27823, but there were some open suggestions in, in particular https://github.com/bitcoin/bitcoin/pull/27823#discussion_r1267289758, to extend and/or randomize the way files are perturbed.

There is also the possibility that more sophisticated perturbations could potentially uncover other unhandled exceptions/assert crashes like the one fixed in #27823.  

### Useful Skills

* Python
* Debugging the bitcoin core C++ file parsing code in order to understand why certain perturbation lead to certain errors.

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by cosmicbutterglue** [comment]
I'll look into this

**Comment by L0laL33tz** [comment]
Created #28612 to address this. @furszy let me know if the randomizations are as you had in mind!
