### ISSUE TITLE
ERROR: ProcessNewblock: ActivateBestChain failed (Failed to read block)

### ISSUE THREAD

**Issue by ozziekanga** [bitcoin/bitcoin#28613]
I have a 13 inch MacBook Pro, M1, 2020, with 16MB RAM, running OS Sonoma 14.0.  A few months ago I had successfully downloaded the entire Bitcoin Core (V25) blockchain and I was updating daily without any issues.  I had my Sparrow wallet connected to Bitcoin Core and the blockchain was reflecting my BTC in my Sparrow wallet.  However, three days ago I received the fatal internal message pop-up message and Bitcoin Core froze completely.  I then deleted/removed Bitcoin Core from my Applications and from the external SDD. 

For the past two days I have attempted to re-install Bitcoin Core (V25) on an external SDD (Lacie 2TB) after deleting/removing from my Applications and from the external SDD. After all the blocks headers have indexed, the blocks begin to download.  

Yesterday (October 7, 2023) I was accessing the internet via wireless and the download reached block height 222995 before I received the fatal internal message pop-up box: 
<img width="1099" alt="Screenshot 2023-10-07 at 4 46 18 PM" src="https://github.com/bitcoin/bitcoin/assets/147281390/d9060837-223b-4ed3-9ffe-8aff7b9997e0">

<img width="1208" alt="Screenshot 2023-10-07 at 4 47 00 PM" src="https://github.com/bitcoin/bitcoin/assets/147281390/1ba2e91e-734b-47b7-9fba-4d60e32ee828">

The debug log from October 7 stated:
<img width="644" alt="Screenshot 2023-10-07 at 4 51 44 PM" src="https://github.com/bitcoin/bitcoin/assets/147281390/0c562c21-0ee8-4a1f-ac19-bb4e0f1cf915">

Today (October 8, 2024) I was accessing the internet via a wired connection and the download reached block height 196461 before giving the same fatal internal error message pop-up message from yesterday:
<img width="739" alt="Screenshot 2023-10-08 at 11 41 10 AM" src="https://github.com/bitcoin/bitcoin/assets/147281390/af143cc9-bd46-49f4-90f7-2eab49d42e36">

The debug log from today stated:
<img width="650" alt="Screenshot 2023-10-08 at 11 39 39 AM" src="https://github.com/bitcoin/bitcoin/assets/147281390/be19bc3e-1814-493f-9f75-6155cb0b7ffa">

Yesterday I ran Apple Diagnostics on my Mac and there are no issues with the internal SDD.  I also believe there are no issues with the external SDD.

Any guidance on overcoming this issue will be greatly appreciated as I want to make sure I'm running my Sparrow wallet with my Bitcoin Core node.

Thank you, Phil

**Comment by ozziekanga** [comment]
Many thanks - appreciated.  I will format the external SDD with APFS.  After reading the threads in the link you provided, looks like APFS will fix the issue and I can then load Bitcoin Core without any issues.

**Comment by fanquake** [comment]
Closing for now then. If you have further issues, let us know, and we can reopen.
