### ISSUE TITLE
rpc: loadtxoutset should return errors that currently go to logs

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#28621]
### Please describe the feature you'd like to see added.

`loadtxoutset` should return (more of) the errors that currently only appear in the log.

### Is your feature related to a problem, if so please describe it.

Currently most errors encountered during `loadtxoutset` can only be found via the log.

### Please leave any additional context

Errors could be shown by `loadtxoutset status` if the method is made async (see #28620), otherwise just returned.

**Comment by pablomartin4btc** [comment]
Concept ACK.

eg. currently when re-try already processed and completed `loadtxoutset` on mainnet the returned error message is:
```
./src/bitcoin-cli -datadir=${AU_DATADIR} loadtxoutset ${AU_DATADIR}/utxo-800000.dat
error code: -32603
error message:
Unable to load UTXO snapshot .../.test_utxo_2/utxo-800000.dat
```
While in the logs a user would see:
```
2023-10-09T20:26:13Z [httpworker.2] [snapshot] waiting to see blockheader 00000000000000000002a7c4c1e48d76c5a37902165a270156b7a8d72728a054 in headers chain before snapshot activation
2023-10-09T20:26:13Z [httpworker.2] [snapshot] can't activate a snapshot-based chainstate more than once
```


I like also the idea to extend the `rpc` command with the `status` param:  `loadtxoutset status`, in order to see percentage of processing, errors or warnings, especially if we manage to make it async.

**Comment by brunoerg** [comment]
Good first issue?

**Comment by Sjors** [comment]
This shouldn't be closed yet. #28652 only fixes one failure mode.

**Comment by Sarsilmazxx02** [comment]
[devcontainer (1).json](https://github.com/user-attachments/files/16969910/devcontainer.1.json)
![Image](https://github.com/user-attachments/assets/eb2f7701-0981-40de-859e-11a3e6504091)
![Image](https://github.com/user-attachments/assets/7bb10417-fdaf-4c49-b490-a61f0b006f4b)
![Image](https://github.com/user-attachments/assets/d869acd9-502b-4ed2-b80e-ddcd1d237e61)
[settings.json](https://github.com/user-attachments/files/16969911/settings.json)
