### ISSUE TITLE
Voting on Priority Projects for 27.0

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#28642]
Please leave your votes for project priorities for the next ~6 months (until the 27.0 feature freeze).

Project priorities are those which the frequent contributors to this project have voted on to have more focused review on until the next feature freeze (or until they are completed). They will become permanent topics in our weekly IRC meetings so that we can get updates on the progress of each project and determine the next step to move them forward.

Voting will close at the start of the IRC meeting on October 19th at 14:00 UTC. To vote, please leave a comment containing the three projects from the list below that you would like to be the priority projects. The priority projects will be the three with the most votes.

Voting is limited to those who are part of the bitcoin github organization. Comments in this issue from those outside of the organization will be ignored, and may be deleted. If you are not part of the organization and believe that you should be, please send me an email or message me on IRC.

The projects to vote on are:
* Multiprocess #10102 
* Silent payments #28536
* Package Relay #27463
* Legacy wallet (BDB) removal #20160
* Erlay #28646
* Cmake #28607
* ~~Kernel #27587~~ (removed by request of the author)
* ~~Logging Migration #25203~~ (removed by request of the author)
* Stratum V2 #27854
* ~~cluster mempool #27677~~ (removed by request of the author)

**Comment by luke-jr** [comment]
* Stratum V2
* Cmake

**Comment by dergoegge** [comment]
* multiprocess
* kernel
* package relay

**Comment by theStack** [comment]
* Silent payments
* Package relay
* Legacy wallet removal

**Comment by hebasto** [comment]
- Multiprocess
- Cmake
- Kernel

**Comment by pinheadmz** [comment]
- legacy wallet removal
- silent payments
- stratumV2

**Comment by brunoerg** [comment]
- legacy wallet removal
- multiprocess
- package relay

**Comment by willcl-ark** [comment]
* cmake
* silent payments
* stratumv2

**Comment by TheCharlatan** [comment]
* cmake
* multiprocess
* legacy wallet removal

**Comment by instagibbs** [comment]
I can't actually tell which projects have active/committed champions for the next 6 months, aside from personally speaking to some. 

That said...

- Package Relay
- Erlay (if there's a committed champion)

**Comment by stickies-v** [comment]
- kernel
- cmake
- multiprocess

**Comment by ismaelsadeeq** [comment]
silent payment
package relay
kernel

**Comment by josibake** [comment]
* Silent payments
* Kernel
* Package Relay

**Comment by aureleoules** [comment]
* Legacy Wallet Removal
* Silent Payments
* Package Relay

**Comment by red0bear** [comment]
Changing algo mining seems missing , inter process tor addition and  payment module where you can pay less 1000 satoshi making wallet good to use.

**Comment by red0bear** [comment]
Quite sad censorshi is around here  too. Bitcoin is less democratic nowdays. You should be money not a creditcard machine. Sad community act more to scam people .

**Comment by murchandamus** [comment]
Package Relay
Legacy wallet (BDB) removal
Silent payments

**Comment by ajtowns** [comment]
* Package Relay
 * Erlay
 * Cmake / musig2 descriptors/psbt

Would be good to have a tracking issue for multiprocess if there's going to be progress on it?

**Comment by fjahr** [comment]
Package Relay
Kernel
Silent Payments

**Comment by w0xlt** [comment]
Silent Payments
CMake
Stratum V2

**Comment by glozow** [comment]
- Package relay
- Legacy wallet removal
- Multiprocess

**Comment by ccdle12** [comment]
This is just a note on the stratumv2 work as suggested by jonatack https://github.com/bitcoin/bitcoin/pull/27854#issuecomment-1765050943

Given that we've already implemented most (if not all) of the features, a six-month window for refactoring, adding a lot more tests and structuring the proposed changes in a way that is easier for contributors to review sounds doable to me.

And yep, both myself and other contributors involved with this project can definitely attend the weekly #bitcoin-core-dev IRC meetings to provide updates and field any questions.

**Comment by naumenkogs** [comment]
- erlay
- multiprocess
- package relay

**Comment by pablomartin4btc** [comment]
- Package Relay
- Erlay
- CMake

**Comment by vasild** [comment]
The initial idea of the priority projects was to not merge other PRs that are otherwise ready if they conflict with a priority project if that would slow down the priority project ([unwanted rebase](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-301) and re-review). But:

> voting == "i'm aiming to review" [[1]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-310)

> this isnt a vote of "what would you like to see in bitcoin core" and more signaling "i will prioritise working on and reviewing x" [[2]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-308)

> "I want to not make them rebase" + "I will review" [[3]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-312)

> which projects have the most reviewer interest, so are likely to make the most progress, and are least likely to spend a long time unmerged, and hence will only cause minimal rebasing in conflicting PRs [[4]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-319)

> the priority projects help break the cyclic dependency in decisions of the form "i'd like to work/help on X, but only if sufficient other people think the same" [[5]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-328)

> one being "what should be priority" and another being "what will i actively contribute to" [[6]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-316)

> two different votes thing of "priority" and "review" ... for deciding the actual priority, I think having each person vote for 3 is still good [[7]](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-349)

Seems that the initial idea has evolved to two possible meanings:

1. **I will personally work on that** ("vote" is not the most appropriate word for that - "I vote that I will work on that" does not sound right. This is more expressing intent and aggregating people's intentions)

2. **I think it would be nice to have that in 27.0** ("vote" is the right word for that)

So, what are we "voting for" here?

I am expressing intent to work on the following (mostly by review and testing):

* Package relay
* Erlay
* Cmake

I think it would be nice to have in 27.0:

* Silent payments
* Legacy wallet (BDB) removal
* Cmake

**Comment by red0bear** [comment]
> https://github.com/red0bear this issue only affects people who perform regular, frequent review that is needed for technical progress. You can freely become one over time by doing consistent and helpful review on this project, which is generally much appreciated. You can also open a pull request to implement changes that you would like to propose. Some resources for both steps are [here](https://jonatack.github.io/articles).

censoring people will not help much. Anyways seems personal choices ... not community choices.

**Comment by red0bear** [comment]
Crypto has zero chance if you keep doing selfish things like delete post of people. Community wants manipulate people ? This is 100% wrong .

**Comment by darosior** [comment]
Signaling my intention to help with package relay as time permits. Don't have an opinion/vote on what other people should be doing.

**Comment by ajtowns** [comment]
> The initial idea of the priority projects was to not merge other PRs that are otherwise ready if they conflict with a priority project if that would slow down the priority project ([unwanted rebase](https://www.erisian.com.au/bitcoin-core-dev/log-2023-09-28.html#l-301) and re-review).

FWIW, I'd still say that's what the *effect* of making a project a priority is; but you still want to pick the projects that are getting lots of prompt review, not ones that would be good, but no one is actually reviewing, so PRs aren't actually able to get merged quickly. It's also not like other PRs won't get merged, just that they'll tend to be the ones that get held up and need to be rebased more often. YMMV, just my opinion, etc.

**Comment by ariard** [comment]
speaking on my own only: erlay, cluster mempool and package relay (the p2p part)

**Comment by murchandamus** [comment]
Per the opening post, voting closed about three hours ago, @achow101 announced the final tally in the meeting:

> achow101   10:03:
> The final count for the voting is Package relay - 19, Silent payments - 11, Multiprocess - 9, Legacy wallet removal - 9, cmake - 8, erlay - 7 stratum v2 - 4

It seems to me that your vote would have not changed the outcome though: Cluster mempool was removed per request of the champion, Package Relay will be a priority project, and Erlay wouldn’t have made the top three even with your additional vote.

**Comment by achow101** [comment]
The priority projects are package relay, silent payments, and multiprocess.

**Comment by ariard** [comment]
i like multiprocess

**Comment by quinteiroh** [comment]
Hi everyone,

I really believe that´s important to advance with the Stratum V2. Especially after this recent situation with F2pool and the transaction censorship

https://www.nobsbitcoin.com/f2pool-is-filtering-transactions-from-ofac-sanctioned-address-report/

The owner admits on Twitter (he deleted the post after)

![download](https://github.com/bitcoin/bitcoin/assets/55174516/66d75b1a-ee96-4166-9ddc-ab229b75315f)

The original link was: https://twitter.com/satofishi/status/1727220109780136287
