### ISSUE TITLE
Bitcoin Compressed WIF (Starting with K and L) Issue

### ISSUE THREAD

**Issue by Beingsaifu** [bitcoin/bitcoin#28654]
I am new to coding and blockchain. I have 2 private keys starting with K and L which are 52 characters and the address corresponding to these keys saved as screenshot when they were created using Electrum years back but when i try to convert these address to the actual address it keeps giving a different address, also tried to import the keys to a new wallet it keeps generating wrong bitcoin addresses. what could be the issue and is there a python script to generate the correct address? any help will be appreciated.

I have tried multiple scripts found on forums but nothing works but I can confirm the address and its keys are correct without any missing characters and they belong to an actual bitcoin address

**Comment by achow101** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
