### ISSUE TITLE
Bitcoin config explained documentation

### ISSUE THREAD

**Issue by gkucmierz** [bitcoin/bitcoin#28712]
### Please describe the feature you'd like to see added.

Where can I find bitcoin.conf docs?

**Comment by fanquake** [comment]
> Where can I find bitcoin.conf docs?

You could look in the example bitcoin.conf, that ships with each release, i.e: https://github.com/bitcoin/bitcoin/blob/25.x/share/examples/bitcoin.conf.

**Comment by gkucmierz** [comment]
Thank you I missed it somehow.
