### ISSUE TITLE
test: Replace random_bytes() with random.randbytes()

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#28720]
### Motivation

Now that Python3.9 is available, the `random_bytes` helper function can be removed.

### Useful Skills

* Compiling Bitcoin Core from source
* Running the C++ unit tests and the Python functional tests
* Python 3.9

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by ns-xvrn** [comment]
I can take care of this, if I understand correctly remove the `random_bytes` function in the util and instead utilize the `randbytes` from Python 3.9
