### ISSUE TITLE
Empty Witness Data, although transaction has witness populated in other full-nodes

### ISSUE THREAD

**Issue by ziggie1984** [bitcoin/bitcoin#28730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Writing this issue on behalf of several reported cases (see below), so the exact bitcoind specifications are different in each case.

All lightning implementation scan for the preimage in case an HTLC as to be resolved onchain. Doing this we analyse the witness data of related outputs because we know what to expect. Example for this is an offered HTLC we have to resolve onchain. Let's imagine that we locally force-closed a channel, this would lead to the following Witnessscript for the offered [HTLC](https://github.com/lightning/bolts/blob/master/03-transactions.md#offered-htlc-outputs):

```
# To remote node with revocation key
OP_DUP OP_HASH160 <RIPEMD160(SHA256(revocationpubkey))> OP_EQUAL
OP_IF
    OP_CHECKSIG
OP_ELSE
    <remote_htlcpubkey> OP_SWAP OP_SIZE 32 OP_EQUAL
    OP_NOTIF
        # To local node via HTLC-timeout transaction (timelocked).
        OP_DROP 2 OP_SWAP <local_htlcpubkey> 2 OP_CHECKMULTISIG
    OP_ELSE
        # To remote node with preimage.
        OP_HASH160 <RIPEMD160(payment_hash)> OP_EQUALVERIFY
        OP_CHECKSIG
    OP_ENDIF
OP_ENDIF
```
This Script can only be unlocked by the following 3 types of [witness data](https://github.com/lightningnetwork/lnd/blob/master/contractcourt/htlc_timeout_resolver.go#L368-L370):

```
//  SENDR: <0> <sendr sig>  <recvr sig> <0> (2nd level timeout)
//  RECVR: <recvr sig>  <preimage>
//  REVOK: <revoke sig> <revoke key>
```

So we can conclude that the witness data will be at least of size 2. In lnd we therefore do a check for the second witness element to be a 32 byte preimage.

Now comes the problem. People reported now several times, that their lightning-node was crashing because of this behaviour. And when queried their backend with `bitcoin-cli getrawtransaction` their output did also not have the witness data populated. A reindexing of the blockchain helped I think in all cases which reported this behaviour. I am reporting this issue here because I have the feeling that somehow bitcoind might have an edge case for this behaviour (in case the hardware is not the problem).

Reported cases:
1.https://github.com/lightningnetwork/lnd/issues/8028#issuecomment-1778777711
2.https://github.com/lightningnetwork/lnd/issues/7803
3.https://github.com/lightningnetwork/lnd/issues/5977
4.https://github.com/lightningnetwork/lnd/issues/6381

Wondering whether some of you have an idea where to look at. Can I assume that a bitcoin node could only report this transaction (hence accepting it via a block) if the witness data was not provided? Otherwise we would have failed the block verification I guess?

Happy to get your thoughts on this.

Thank you in advance!

### Expected behaviour

Not sure whether this is just a hardware failure which manifests itself via the above described behaviour. So no expected behaviour yet.

### Steps to reproduce

TBD.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

-

### Operating system and version

-

**Comment by ziggie1984** [comment]
Ahh ok I see what this flag does, you can tell bitcoind to only return the non-segwit serialization, meaning that `getrawtransaction` will never return any witness data, right ?  The case I was investigating today had already several force-closes onchain (with htlcs-involved) so then it would have crashed earlier in the past but hasn't happened before to him at least.

**Comment by ziggie1984** [comment]
> Are there logs available when the transaction first entered their Bitcoin Core node (either via RPC or via P2P), either as a mempool transaction or a transaction inside a block?

can you provide us with some logs for your case (bitcoind logs) @sanjay-shah

**Comment by sanjay-shah** [comment]
> Looking at the conf in [lightningnetwork/lnd#7803 (comment)](https://github.com/lightningnetwork/lnd/issues/7803#issuecomment-1629619642) and given that a reindex fixed it here [lightningnetwork/lnd#5977 (comment)](https://github.com/lightningnetwork/lnd/issues/5977#issuecomment-971090110), it seems unlikely to be caused by `-rpcserialversion=0`, but still possible?


cat .bitcoin/bitcoin.conf
server=1
rpcuser=xxxxxxxxx
rpcpassword=xxxxxxxxxx
txindex=1
listen=1
rpcserialversion=0
maxorphantx=1
banscore=1
bind=0.0.0.0:8333
rpcallowip=143.198.140.93
rpcallowip=10.124.0.2
rpcallowip=10.48.0.5
rpcallowip=127.0.0.1
rpcbind=0.0.0.0
rpcport=8332

**Comment by ziggie1984** [comment]
I am wondering whether my bitcoin-core node will accept tx relays from non-segwit enabled nodes into my mempool (because they cannot supply the relevant witness data?)

**Comment by ziggie1984** [comment]
> Those nodes can only provide you with transactions whose witness and non-witness serialization is identical, that is, transactions that do not have any witness data.

But how do non-witness enabled nodes know this, because they have only the non-witness serialized tx in there store? So I think they will try to relay the tx but we would reject it ?

**Comment by ziggie1984** [comment]
> I can't help you with questions about lnd, but if your question is whether it is possible to have an HTLC (via P2WSH) transaction in the mempool without witness, then the answer is no, because that'd be rejected by validation by all supported versions of Bitcoin Core.

Perfect, that was exactly my question (having a transaction which in reality  a segwit transaction but received from a non-segwit enabled fullnode in the mempool) . Wondering because we are talking about the mempool here, whether this validation can be considered as Policy or Consensus ?

**Comment by sanjay-shah** [comment]
> @sanjay-shah Was there a reason why you set `-rpcserialversion=0`? Was this generated automatically by a config generator?

@maflcko I really don't remember, this was very old node that I kept upgrading, maybe I generated the config using lopp's generator, or the config got inherited from very old version of bitcoind where I might have needed it in the past.

**Comment by ziggie1984** [comment]
Ok I also found the problem to https://github.com/lightningnetwork/lnd/issues/7803

This node was running in pruned node, what lnd does when not finding the block locally it asks its peers via the iventory messages  to provide the data. The old version of the library used: [`InvTypeBlock`] (https://github.com/btcsuite/btcwallet/blob/f33c42289bafd785ff9516fc651ff84a55374ba9/chain/pruned_block_dispatcher.go#L546)  which according to the description only responds with the non-witness block data (https://github.com/btcsuite/btcd/blob/master/wire/invvect.go#L32-L38 - maybe you can verify whether bitcoin-core really strips the data when set)

In the newer version of the library we switched to [`InvTypeWitnessBlock`](https://github.com/btcsuite/btcwallet/blob/master/chain/pruned_block_dispatcher.go#L546) but this will only be available in the next lnd release (18).

I will close this issue, because bitcoin-core is not the source of the problem ok. Thanks a lot for your help :) @maflcko
