### ISSUE TITLE
sendrawtransaction takes too long

### ISSUE THREAD

**Issue by toolsopen** [bitcoin/bitcoin#28745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

tx:https://mempool.space/zh/tx/93cce12faca9fbbc51916852ae7d690769cd4812a0834b9b323defa7a5265f46
sendrawtransaction calling time: Oct 26, 2023 @ 11:37:31.268
bitcoin-conf:
  listen=1
  port=8433
  rpcport=8432
  addressindex=1
  rpcthreads=1000
  rpcworkqueue=4000
  server=1
  txindex=1
  coinstatsindex=1
  keypool=0
  stake=0
  staking=0
  gen=0
bitcoind logs:
2023-10-26T13:18:36Z UpdateTip: new best=000000000000000000032cf9d0ad42da7dcdeb87ea80a36c8b2406d3b9ebbb95 height=813929 version=0x26f26000 log2_work=94.499899 tx=909456202 date='2023-1
0-26T13:17:42Z' progress=1.000000 cache=121.5MiB(713411txo)
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z [main] AddToWallet c4d3b5ddfcd40c3751123a18f48952749acab526f2d0b2754b1dc64331b82c2a  update
2023-10-26T13:18:36Z [main] AddToWallet 51e8c45598bcde01c639e8f2a345172e7c8bd33c0c5dc1688c3d1547f4191642  update
2023-10-26T13:21:48Z [main] AddToWallet 93cce12faca9fbbc51916852ae7d690769cd4812a0834b9b323defa7a5265f46  new

### Expected behaviour

Expected to return in seconds, but actually took more than 3 minutes

### Steps to reproduce

This situation occurs from time to time. Randomly checking the last two log records, it seems that it happened near the block generation log.

### Relevant log output

2023-10-26T13:18:36Z UpdateTip: new best=000000000000000000032cf9d0ad42da7dcdeb87ea80a36c8b2406d3b9ebbb95 height=813929 version=0x26f26000 log2_work=94.499899 tx=909456202 date='2023-1
0-26T13:17:42Z' progress=1.000000 cache=121.5MiB(713411txo)
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2023-10-26T13:18:36Z [main] AddToWallet c4d3b5ddfcd40c3751123a18f48952749acab526f2d0b2754b1dc64331b82c2a  update
2023-10-26T13:18:36Z [main] AddToWallet 51e8c45598bcde01c639e8f2a345172e7c8bd33c0c5dc1688c3d1547f4191642  update
2023-10-26T13:21:48Z [main] AddToWallet 93cce12faca9fbbc51916852ae7d690769cd4812a0834b9b323defa7a5265f46  new

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

Bitcoin Core 22.0

### Operating system and version

Ubuntu 18.04.5 LTS

### Machine specifications

OS:Ubuntu 18.04.5 LTS
machine:aws m5 2xlarge
cpu:8 cores
Memory:32GB
disk:SSD 1 TB

**Comment by toolsopen** [comment]
> > rpcthreads=1000
> > rpcworkqueue=4000
> 
> Yes, it is possible that all CPUs are busy if many threads are running, and possibly working.



> > rpcthreads=1000
> > rpcworkqueue=4000
> 
> Yes, it is possible that all CPUs are busy if many threads are running, and possibly working.

Observe that the machine performance indicators are not full, but the current memory usage is 20GB.

**Comment by toolsopen** [comment]
> > Bitcoin Core 22.0
> 
> Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?



> > Bitcoin Core 22.0
> 
> Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

Currently I don’t know how to reproduce it, it only happens from time to time in the prod environment.

**Comment by toolsopen** [comment]
There are currently about 3,000 utxos available. A large number of transactions have been generated in history, and transaction reception and sending are also very active.

**Comment by toolsopen** [comment]
> How large is your wallet, roughly?
There are currently about 3,000 utxos available. A large number of transactions have been generated in history, and transaction reception and sending are also very active.

**Comment by toolsopen** [comment]
> background

Is it related to the fact that the historical transaction data of the wallet is too large? The total number of transactions in our wallet is 1,170,364

**Comment by toolsopen** [comment]
> What is the approximate size of the BDB wallet? What is the SSD read/write usage around the slowdown?
> 
> If this is the cause, I think you can try an sqlite descriptor wallet, whose flush is less expensive on the storage read/write usage.

9.3G Oct 31 03:55 wallet.dat
![image](https://github.com/bitcoin/bitcoin/assets/21998212/d34778d6-684c-424a-824c-8b3681418108)
![image](https://github.com/bitcoin/bitcoin/assets/21998212/a9383fcf-45f1-4c32-aa90-2258ba9fc7f3)

**Comment by toolsopen** [comment]
One thing I need to state is that all transactions in my wallet are sent and received from the same address, and the read-only wallet mode used is only for broadcast transactions and utxo queries.

**Comment by toolsopen** [comment]
> sqlite

I tried to use sqlite, but it was prompted that read-only import addresses are not supported.

**Comment by willcl-ark** [comment]
Hi @toolsopen 

Bitcoin Core v22 is outside of maintenance window now, you should probably consider upgrading (to at least 24.2, or better still 25.1)

A few questions:

1) what do these config values do?
  
  ```
  stake=0
  staking=0
  gen=0
  ```
  
2) How are you creating the sqlite wallet?


I can create a (new) sqlite descriptor wallet and import a wpkh pubkey on v25.1, after compiling with sqlite like this:

```sh
will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest -named createwallet wallet_name="toolsopen" disable_private_keys=true blank=true descriptors=true
{
  "name": "toolsopen"
}

will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest getdescriptorinfo "wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)"
{
  "descriptor": "wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)#8zl0zxma",
  "checksum": "8zl0zxma",
  "isrange": false,
  "issolvable": true,
  "hasprivatekeys": false
}

# import descriptor
# NOTE: this will import as inactive so `getnewaddress` on this wallet won't work natively
will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍 
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest importdescriptors '[{ "desc": "wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)#8zl0zxma", "timestamp": 0, "internal": true  }]'
[
  {
    "success": true
  }
]

# derive the address
will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍 on ☁️  (europe-west1)
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest deriveaddresses "wpkh(02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9)#8zl0zxma"
[
  "bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj"
]

# load wallet with funds to send from

# send coins and check balance
will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍 on ☁️  (europe-west1)
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest -rpcwallet=descriptor sendtoaddress bcrt1q0ht9tyks4vh7p5p904t340cr9nvahy7uevmqwj 1
dac907862d74fb45afc9dd174794a0132b3a8a59c35e67229d670fb241e4e1e5

will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍 on ☁️  (europe-west1)
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest -rpcwallet=descriptor -generate 1
{
  "address": "bcrt1qf4ps9gxeperfnszz7c25ls9yupmt45d6x9pvea",
  "blocks": [
    "3a4ae953cac8b899b36293e0f45892bec804588f721e47e5b30529c276fc74b8"
  ]
}

will@ubuntu in ~/src/bitcoin on master [$?⇡] : C v16.0.6-clang : 🐍 on ☁️  (europe-west1)
$ /home/will/src/bitcoin/src/bitcoin-cli -regtest -rpcwallet=toolsopen getbalance
1.00000000


```

This will rescan the blockchain for historical transactions but you would lose transaction metadata. There does exist a migration tool which should be released in v26.0 which _may_ also handle metadata too, if this is important to you (unsure about this).

> @maflcko Will wallet.dat 9.3G affect performance? Is there any way to clear the used transactions in it?

If you import the descriptor as above and use `"timestamp": "now"` then it won't rescan for historical transactions. Although if any time in the future you happened to rescan your chain, these would be picked back up by the wallet. But AFAIK you can't "clear" them from the wallet.

You could create a new wallet with a new address and use that? Each transaction should use a unique address. Address re-use is terrible for sender and receiver privacy.

**Comment by toolsopen** [comment]
> If you import the descriptor as above and use `"timestamp": "now"` then it won't rescan for historical transactions. Although if any time in the future you happened to rescan your chain, these would be picked back up by the wallet. But AFAIK you can't "clear" them from the wallet.

1.is to turn off some mining settings
2.The following versions and commands were used for testing
 > https://bitcoincore.org/bin/bitcoin-core-25.1/bitcoin-25.1-x86_64-linux-gnu.tar.gz
 > curl -X POST 'http://test:test@127.0.0.1:8432' -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"createwallet","params":["main",true,true,null,false,true,true],"id":"1"}'
 > curl -X POST 'http://test:test@127.0.0.1:8432' -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"importaddress","params":[ "bc1qmxxxxxxxxxxxxxxxxx", "main", true],"id":"1"}'
 
 One address is easier to maintain

**Comment by toolsopen** [comment]
> > Will wallet.dat 9.3G affect performance?
> 
> Yes, significantly.
> 
> > Is there any way to clear the used transactions in it?
> 
> Not automatically. However you can use `removeprunedfunds` and delete old transactions manually.

This helps, let me write a script and try it out

**Comment by toolsopen** [comment]
https://github.com/bitcoin/bitcoin/issues/12115
<img width="921" alt="image" src="https://github.com/bitcoin/bitcoin/assets/21998212/eb9c1ef3-bb33-4600-a5d7-f9fd0dcddfbe">

@achow101 @maflcko @willcl-ark @gregwebs  I saw that this issue was raised in 2018, but no attention was paid to it

**Comment by toolsopen** [comment]
This proves that it would be a very good way if bitcoind can self-isolate expired transactions.

**Comment by willcl-ark** [comment]
Thanks for the update. Wallet performance is something that's being continually worked on.

Did you end up upgrading versions (too), or still running on V22?

**Comment by toolsopen** [comment]
> Thanks for the update. Wallet performance is something that's being continually worked on.
> 
> Did you end up upgrading versions (too), or still running on V22?

I also updated the final version to 25.1

**Comment by toolsopen** [comment]
> Assuming this is a bdb wallet (can be checked via `getwalletinfo()[format]`), I don't think it is worth to spend time on optimizing the code, given that it will be removed in the future.

I use it for utxo maintenance and transaction broadcasting, but an overly large wallet will definitely have a great impact on performance.
