### ISSUE TITLE
Strange error code on bitcoin cli with descriptor wallet

### ISSUE THREAD

**Issue by DmytroShalaiev** [bitcoin/bitcoin#28744]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

I use the descriptor wallet and seems to be that the error should be related to descriptor mode, same for importaddress
NOTE: for not descriptor address importaddress || importpubkey works well with same data

`importpubkey "03234573021d48ba91f2fab9e210c32c5dbf2a132e701d117dce21ec5de362107d" "test_import_with_same_label" false
Only legacy wallets are supported by this command (code -4)`
<img width="1591" alt="Снимок экрана 2023-10-27 в 16 01 56" 
src="https://github.com/bitcoin/bitcoin/assets/26797262/82877e6d-8382-46f3-a240-af76a01cf91c">

**Comment by achow101** [comment]
Which error are you asking about? The "Only legacy wallets" error or the "method not found"?

Both should be expected. Descriptor wallets explicitly disable `importpubkey`, `importaddress`, and a few other RPCs. It looks like you later typed in `-` which is not a valid RPC.

**Comment by DmytroShalaiev** [comment]
Yes, I am about `importpubkey` & `importaddress` and 'Only legacy wallets' - A non-obvious message if in fact the point is that I have a descriptor wallet, `-` i used as a delimiter(sry) on the screenshot.
