### ISSUE TITLE
macOS qt QTimer::stop crash on v26.0rc2

### ISSUE THREAD

**Issue by jb55** [bitcoin/bitcoin#28867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

It crashed

### Expected behaviour

Not to crash

### Steps to reproduce

I believe I was closing the application (according to the stacktrace)

### Relevant log output

https://cdn.jb55.com/s/adcf1a349cdfc36d.txt

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v26.0rc2

### Operating system and version

macOS Ventura 13.6

### Machine specifications

apple m2 max
macbook pro 2023
external usb-c m.2 full node

**Comment by hebasto** [comment]
> I believe I was closing the application (according to the stacktrace)

Is it reproducible?

**Comment by jb55** [comment]
I haven't been able to reproduce it since it happened

**Comment by fanquake** [comment]
I've moved the issue to the Qt repo, but without steps to reproduce, not sure there's much that can be done here.
