### ISSUE TITLE
ci: failure in Windows MSVC build

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#28901]
https://github.com/bitcoin/bitcoin/actions/runs/6902633477/job/18779735457#step:20:2859:
```bash
 LINK : fatal error C1900: Il mismatch between 'P1' version '20230904' and 'P2' version '20221215' [D:\a\bitcoin\bitcoin\build_msvc\test_bitcoin\test_bitcoin.vcxproj]
LINK : fatal error LNK1257: code generation failed [D:\a\bitcoin\bitcoin\build_msvc\test_bitcoin\test_bitcoin.vcxproj]
LINK : fatal error LNK1327: failure during running link.exe [D:\a\bitcoin\bitcoin\build_msvc\test_bitcoin\test_bitcoin.vcxproj]
```

**Comment by hebasto** [comment]
I'll look into it.

**Comment by hebasto** [comment]
The new windows-2022 image version 20231115.2.0 is being rolling out by GHA at the moment. However, in the [release notes](https://github.com/actions/runner-images/releases/tag/win22%2F20231115.2), I did not spot any breaking changes for now. Keep investigating further.

**Comment by hebasto** [comment]
> Is this still an issue?

Yes. Testing a fix at the moment.

**Comment by hebasto** [comment]
> Ok, I was asking because the latest build passed: [bitcoin/bitcoin/actions/runs/6903309087/job/18781736984](https://github.com/bitcoin/bitcoin/actions/runs/6903309087/job/18781736984) So I guess GitHub only pushes out the new image to some tasks?

It passed because the job was using the old image:
```
Runner Image
  Image: windows-2022
  Version: 20231029.1.0
```

The new version 20231115 is still problematic. The current rollout [progress](https://github.com/actions/runner-images#available-images) looks like that:

![image](https://github.com/bitcoin/bitcoin/assets/32963518/260d0269-a64b-4541-b778-790a898c53f0)

**Comment by hebasto** [comment]
Fixed in https://github.com/bitcoin/bitcoin/pull/28905.
