### ISSUE TITLE
`AddrManSelectByNetwork` benchmark fails on Windows

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#28940]
When compiling without external signer support, the resulted `bench_bitcoin.exe` fails on Windows:
```
>.\bench_bitcoin.exe -filter=AddrManSelectByNetwork
Error: bad optional access
```

Steps to reproduce the failure:
- cross compiling on Ubuntu 22.04:
```
$ make -j $(nproc) -C depends HOST=x86_64-w64-mingw32 NO_QT=1
$ ./autogen.sh
$ ./configure CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site --disable-external-signer
$ make -j $(nproc)
```
- compiling natively on Windows:

Apply the diff as follows:
```diff
--- a/build_msvc/bitcoin_config.h.in
+++ b/build_msvc/bitcoin_config.h.in
@@ -41,9 +41,6 @@
 /* Define this symbol to enable ZMQ functions */
 #define ENABLE_ZMQ 1
 
-/* define if external signer support is enabled (requires Boost::Process) */
-#define ENABLE_EXTERNAL_SIGNER /**/
-
 /* Define to 1 if you have the declaration of `be16toh', and to 0 if you
    don't. */
 #define HAVE_DECL_BE16TOH 0
```
Then
```
>py -3 build_msvc\msvc-autogen.py
>msbuild build_msvc\bitcoin.sln -property:Configuration=Release -verbosity:minimal
>src\bench_bitcoin.exe -filter=AddrManSelectByNetwork
Error: bad optional access
```

---

The failure does not manifest itself when running `bench_bitcoin.exe` using Wine on Linux.

**Comment by theuni** [comment]
Yep, this makes sense to me.

See boost asio: https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/impl/winsock_init.ipp#L39

And a static instance of that is created here: https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/winsock_init.hpp#L116

And I see those being included by`<boost/process.hpp>` from `run_command.cpp`. So I'm guessing boost has been quietly initializing our network stack :(

**Comment by fanquake** [comment]
YUCK.

**Comment by fanquake** [comment]
I think the only logical thing to do here is to disable external signer for windows, and fixup our code. Looking upstream at Boost Process, maintainence cetainly hasn't improved, and it looks like it's only leaning further into using Boost ASIO.
