### ISSUE TITLE
`capnp`  fails when cross-compiling

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#28993]
On the master branch @ 160d23677ad799cf9b493eaa923b2ac080c3fb8e, the `native/bin/capnp` fails when cross-compiling with `MULTIPROCESS=1`:
```
  GEN      /home/hebasto/git/bitcoin/depends/x86_64-pc-linux-gnu/include/mp/proxy.capnp.h
/home/hebasto/git/bitcoin/depends/x86_64-pc-linux-gnu/include/mp/proxy.capnp: File is not in the current directory and does not match any prefix defined with --src-prefix. Please pass an appropriate --src-prefix so I can figure out where to write the output for this file.
/home/hebasto/git/bitcoin/depends/x86_64-apple-darwin/native/bin/capnp compile: /home/hebasto/git/bitcoin/depends/x86_64-pc-linux-gnu/include/mp/proxy.capnp: no such file
Try '/home/hebasto/git/bitcoin/depends/x86_64-apple-darwin/native/bin/capnp compile --help' for more information.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invoking /home/hebasto/git/bitcoin/depends/x86_64-apple-darwin/native/bin/capnp failed
make[2]: *** [/home/hebasto/git/bitcoin/depends/x86_64-apple-darwin/native/include/mpgen.mk:4: /home/hebasto/git/bitcoin/depends/x86_64-pc-linux-gnu/include/mp/proxy.capnp.h] Aborted (core dumped)
```

Please note, that it looks for `x86_64-pc-linux-gnu` subdirectory, while `HOST=x86_64-apple-darwin`.

UPDATE: The bug happens on Ubuntu 23.10, but not on Ubuntu 22.04.

**Comment by hebasto** [comment]
cc @ryanofsky

**Comment by ryanofsky** [comment]
I'm struggling to get darwin build working locally, but I will try docker to reproduce this. Do you know if this might be a recent regression, or when was the last time it might have worked?

**Comment by hebasto** [comment]
Another detail. The bug happens on Ubuntu 23.10, but not on Ubuntu 22.04.

**Comment by ryanofsky** [comment]
I'm still working on this and not having any luck reproducing it. Can you give more complete steps to reproduce? I'm using the CI docker container and running:

```shell
cd /ci_container_base
make -C depends HOST=x86_64-apple-darwin MULTIPROCESS=1 NO_QT=1 V=1
mkdir build
cd build
CONFIG_SITE=$PWD/../depends/x86_64-apple-darwin/share/config.site ../configure
make
```

It looks like you're doing something different, but I'm not sure what exactly. Alternately if you could run make with V=1 that would be helpful to see command line mpgen is invoked with

**Comment by hebasto** [comment]
I fail to reproduce the bug in clean docker environment. Perhaps, my machine has a broken environment.

Closing.

**Comment by ryanofsky** [comment]
That makes more sense. Thanks for the bug report in any case!

**Comment by hebasto** [comment]
> That makes more sense. Thanks for the bug report in any case!

I was careless and didn't run `make distclean`.
