### ISSUE TITLE
test: Add TestNode wait_until helper

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#29029]
### Motivation

Currently, inside TestNode, the global `wait_until_helper_internal` must be used, and each time the timeout factor must be passed.

See https://github.com/bitcoin/bitcoin/pull/29006#discussion_r1416891272

### Possible solution

It would be nice to have a method `wait_until` that wraps the `wait_until_helper_internal` call, like in other classes.

### Useful Skills

* Compiling Bitcoin Core from source
* Running the C++ unit tests and the Python functional tests
* Python 3

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by nikodemas** [comment]
Hi, I would like to work on this

**Comment by mohamedawnallah** [comment]
Hey, @nikodemas Are you still working on this issue? If not I’d like to pick it up. Thanks

**Comment by nikodemas** [comment]
Hi @mohamedawnallah , still working :)
