### ISSUE TITLE
Obscure problem with sent transactions and wallet balance

### ISSUE THREAD

**Issue by FacehuggerCZ** [bitcoin/bitcoin#29024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Hello,

I need help explaining this problem:
![bitcoin core balance](https://github.com/bitcoin/bitcoin/assets/153189455/63b8d934-0974-447c-965b-1bc74607a347)
![bitcoin core transactions](https://github.com/bitcoin/bitcoin/assets/153189455/747d30a2-9ff7-4ceb-b9f6-b01763b78a5f)
![transactions](https://github.com/bitcoin/bitcoin/assets/153189455/d425fb83-a980-41da-83c5-9279a72f93c4)

when I sent two transactions from my bitcoincore wallet, it created other transactions with different amounts in them and sent them to unknown addresses. But the bitcoincore wallet shows me the correct balance, but the public address of the wallet shows me a smaller amount. What is the problem or has the bitcoincore wallet created another public address of my wallet and everything is as it should be? TX transactions: https://mempool.space/tx/f5b121348993c768a898f93f8935c93df002565378b438fb87298de60bb51430
https://mempool.space/tx/464982c71089773479b8e1bd5af9f9d62c6f08d3873511b093f31b9c8607cf2a

I had bitcoin core version 22 when I submitted, now I have reinstalled it to version 25.1.0

### Expected behaviour

I expected it to send only one transaction and the original wallet balance would be lower even with the sent transaction fee.

### Steps to reproduce

when I sent two transactions from my bitcoincore wallet, it created other transactions with different amounts in them and sent them to unknown addresses. But the bitcoincore wallet shows me the correct balance, but the public address of the wallet shows me a smaller amount. What is the problem or has the bitcoincore wallet created another public address of my wallet and everything is as it should be? TX transactions: https://mempool.space/tx/f5b121348993c768a898f93f8935c93df002565378b438fb87298de60bb51430
https://mempool.space/tx/464982c71089773479b8e1bd5af9f9d62c6f08d3873511b093f31b9c8607cf2a

![bitcoin core balance](https://github.com/bitcoin/bitcoin/assets/153189455/edc2f13f-d6f0-49ca-9df7-9b1b4ebc12d0)
![bitcoin core transactions](https://github.com/bitcoin/bitcoin/assets/153189455/e0b881cb-c8fd-4947-b509-7023a2a8e9dc)
![transactions](https://github.com/bitcoin/bitcoin/assets/153189455/258a977a-24e8-44eb-9275-ba834890f9bf)

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v 25.1.0

### Operating system and version

Windows 10 pro 64bit 21H2

**Comment by MarnixCroes** [comment]
@FacehuggerCZ 
In Bitcoin Core the outgoing amount of a transaction is the amount you entered to send + mining fee.
So that's why you see on an explorer that the address received 0.1, but the outgoing tx amount in Bitcoin core is 0.10061201.
0.1 plus the fee add up to the tx outgoing amount.
![image](https://github.com/bitcoin/bitcoin/assets/93143998/cc0bf9c8-6546-41c3-9072-0c456311040c)

The second questions "What are these addresses", those are the change addresses. It's how Bitcoin works.
That money is "back" in your wallet. But to a new unused address instead of the 1MomRR... address.
that is by design.

**Comment by FacehuggerCZ** [comment]
Thanks for the replies, I just wanted to make sure that I didn't happen to have my bitcoin core hacked...
