### ISSUE TITLE
Nit: Inconsistency in the docs regarding block-relay-only connections

### ISSUE THREAD

**Issue by ArmchairCryptologist** [bitcoin/bitcoin#29046]
I was looking into why my node was frequently opening new block-relay-only connections even though it already had two such nodes connected, and while this appears to be intended behavior to counter eclipse attacks, while searching the codebase for this I encountered a minor contradiction in the docs.

Specifically, [doc/reduce-memory.md](https://github.com/bitcoin/bitcoin/blob/3e691258d8789a4a89cce42e7e71b130491594d7/doc/reduce-memory.md?plain=1#L29) says:

```
- `-maxconnections=<n>` - the maximum number of connections, which defaults to 125. Each active connection takes up some
  memory. This option applies only if inbound connections are enabled; otherwise, the number of connections will not
  be more than 11. Of the 11 outbound peers, there can be 8 full-relay connections, 2 block-relay-only ones,
  and occasionally 1 short-lived feeler or extra outbound block-relay-only connection.
```

While [doc/reduce-traffic.md](https://github.com/bitcoin/bitcoin/blob/3e691258d8789a4a89cce42e7e71b130491594d7/doc/reduce-traffic.md?plain=1#L9) says:

```
By default, Bitcoin Core allows up to 125 connections to different peers, 10 of
which are outbound. You can therefore, have at most 115 inbound connections.
Of the 10 outbound peers, there can be 8 full-relay connections and 2
block-relay-only ones.
```

I'm not sure if the extra feeler/block-relay-only connection takes up one of the maxconnections slots or not, but the latter should probably be updated to reflect this behavior.

**Comment by willcl-ark** [comment]
The short-lived feeler connections are not counted against the full outbound count:

https://github.com/bitcoin/bitcoin/blob/09ab9d4fa731866802a6a9f9aa00d92536a8b420/src/net.cpp#L2349-L2355

...so reduce-traffic.md could be updated to mention that there are occasionally up to 11 outbound nodes, which it appears @MarnixCroes has just done :)
