### ISSUE TITLE
Bitcoin's systemic flaw

### ISSUE THREAD

**Issue by ChrisMartl** [bitcoin/bitcoin#29089]
“Bitcoin” doesn’t have a government (a coercion power), and thus must really on **market processes** i.e. on prices, which are determined by supply and demand. Consumer's wants and needs are signaled through prices, which are in turn satisfied by producers, who want to make a **profit**.

In this sense, it seems to be a “Bitcoin” systemic flaw, that a valuable information like the “**timechain**” is not provided to the consumer in exchange for Sats; i.e. no market, no price mechanism and thus no profit or economic calculation in Sat terms for archival full node operators.

How could storage devices be **allocated** in the “Bitcoin”-Network in a <**decentralized**> and thus sustainable way without a market for the “timechain file”? A market emerging ideally via enabled exchanges of the “timechain file” and Sats on “Bitcoin”-protocol level.

PS: "timechain file" to be understood as abstraction for the different database files used and needed by the IBD phase and resynchronization of a full node.

**Comment by fanquake** [comment]
This would be better suited as a post to the mailing list. This issue tracker is used to track technical issues relating to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.
