### ISSUE TITLE
ci: failure in `wallet_basic.py --descriptors`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#29110]
https://cirrus-ci.com/task/5898005006516224?logs=ci#L2515:
```bash
_20231218_134952/wallet_basic_259/node0/regtest/wallets/default_wallet/wallet.dat] SQLite Statement: ROLLBACK TRANSACTION 
 node0 2023-12-18T13:53:29.193915Z [scheduler] [wallet/sqlite.cpp:400] [Close] SQLiteBatch: Batch closed unexpectedly without the transaction being explicitly committed or aborted 
 node0 2023-12-18T13:53:29.194038Z [scheduler] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/zeroconf/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
 node0 2023-12-18T13:53:29.194122Z [scheduler] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/zeroconf/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
 test  2023-12-18T13:53:29.196000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
                                       self.run_test()
                                     File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_basic.py", line 786, in run_test
                                       self.test_chain_listunspent()
                                     File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_basic.py", line 792, in test_chain_listunspent
                                       self.nodes[0].get_wallet_rpc(self.default_wallet_name).sendtoaddress(self.wallet.get_address(), "5")
                                     File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/coverage.py", line 50, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 129, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: Error during descriptors keypool top up. Cannot commit changes for wallet [default_wallet] (-1)
 node0 2023-12-18T13:53:29.196028Z [httpworker.2] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/default_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
 test  2023-12-18T13:53:29.198000Z TestFramework (DEBUG): Closing down network thread 
 test  2023-12-18T13:53:29.248000Z TestFramework (INFO): Stopping nodes 
 test  2023-12-18T13:53:29.248000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by achow101** [comment]
It looks like the `SQLiteBatch` being used to write data to disk is being destroyed unexpectedly, which causes subsequent writes using the same object(??) to have the wrong db transaction state that triggers this error.

**Comment by furszy** [comment]
Yeah. The description is accurate achow. I had something for this in the past for #25297. We currently support a single db connection at time; when multiple `WalletBatch` are created on different threads, the first one destructed has priority over the others.

IIRC, I had a database manager class providing the db references, mapping the thread id to the db ref. So different threads can wait until other processes finish dumping data, acting accordantly, before making use of the db.
I think I never pushed it because I wanted to go further, make the manager class provide db txns at the software level (not db engine level), enabling real parallelism and also letting us batch writes even across data from different processes.

**Comment by Farnoosh85** [comment]
> https://cirrus-ci.com/task/5898005006516224?logs=ci#L2515:
> 
> ```bash
> 
> _20231218_134952/wallet_basic_259/node0/regtest/wallets/default_wallet/wallet.dat] SQLite Statement: ROLLBACK TRANSACTION 
> 
>  node0 2023-12-18T13:53:29.193915Z [scheduler] [wallet/sqlite.cpp:400] [Close] SQLiteBatch: Batch closed unexpectedly without the transaction being explicitly committed or aborted 
> 
>  node0 2023-12-18T13:53:29.194038Z [scheduler] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/zeroconf/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
> 
>  node0 2023-12-18T13:53:29.194122Z [scheduler] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/zeroconf/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
> 
>  test  2023-12-18T13:53:29.196000Z TestFramework (ERROR): JSONRPC error 
> 
>                                    Traceback (most recent call last):
> 
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
> 
>                                        self.run_test()
> 
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_basic.py", line 786, in run_test
> 
>                                        self.test_chain_listunspent()
> 
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_basic.py", line 792, in test_chain_listunspent
> 
>                                        self.nodes[0].get_wallet_rpc(self.default_wallet_name).sendtoaddress(self.wallet.get_address(), "5")
> 
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/coverage.py", line 50, in __call__
> 
>                                        return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
> 
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 129, in __call__
> 
>                                        raise JSONRPCException(response['error'], status)
> 
>                                    test_framework.authproxy.JSONRPCException: Error during descriptors keypool top up. Cannot commit changes for wallet [default_wallet] (-1)
> 
>  node0 2023-12-18T13:53:29.196028Z [httpworker.2] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/default_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
> 
>  test  2023-12-18T13:53:29.198000Z TestFramework (DEBUG): Closing down network thread 
> 
>  test  2023-12-18T13:53:29.248000Z TestFramework (INFO): Stopping nodes 
> 
>  test  2023-12-18T13:53:29.248000Z TestFramework.node0 (DEBUG): Stopping node 
> 
> ```

**Comment by Lajandra** [comment]
> https://cirrus-ci.com/task/5898005006516224?logs=ci#L2515 :
> 
> ```shell
> _20231218_134952/wallet_basic_259/node0/regtest/wallets/default_wallet/wallet.dat] SQLite Statement: ROLLBACK TRANSACTION 
>  node0 2023-12-18T13:53:29.193915Z [scheduler] [wallet/sqlite.cpp:400] [Close] SQLiteBatch: Batch closed unexpectedly without the transaction being explicitly committed or aborted 
>  node0 2023-12-18T13:53:29.194038Z [scheduler] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/zeroconf/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
>  node0 2023-12-18T13:53:29.194122Z [scheduler] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/zeroconf/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
>  test  2023-12-18T13:53:29.196000Z TestFramework (ERROR): JSONRPC error 
>                                    Traceback (most recent call last):
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
>                                        self.run_test()
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_basic.py", line 786, in run_test
>                                        self.test_chain_listunspent()
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_basic.py", line 792, in test_chain_listunspent
>                                        self.nodes[0].get_wallet_rpc(self.default_wallet_name).sendtoaddress(self.wallet.get_address(), "5")
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/coverage.py", line 50, in __call__
>                                        return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
>                                      File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 129, in __call__
>                                        raise JSONRPCException(response['error'], status)
>                                    test_framework.authproxy.JSONRPCException: Error during descriptors keypool top up. Cannot commit changes for wallet [default_wallet] (-1)
>  node0 2023-12-18T13:53:29.196028Z [httpworker.2] [wallet/sqlite.cpp:53] [TraceSqlCallback] [/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20231218_134952/wallet_basic_259/node0/regtest/wallets/default_wallet/wallet.dat] SQLite Statement: INSERT or REPLACE into main values(?, ?) 
>  test  2023-12-18T13:53:29.198000Z TestFramework (DEBUG): Closing down network thread 
>  test  2023-12-18T13:53:29.248000Z TestFramework (INFO): Stopping nodes 
>  test  2023-12-18T13:53:29.248000Z TestFramework.node0 (DEBUG): Stopping node 
> ```

**Comment by Farnoosh85** [comment]
0xE7cF1C52C9f179B855D7a31eA79997882269057A send your bnb bep20 address my

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/6509037848625152?logs=ci#L2502
