### ISSUE TITLE
Transfer from closed coinbase acc.

### ISSUE THREAD

**Issue by FUSION9999** [bitcoin/bitcoin#29126]
My coinbase acc was closed for unknown reason, called and dowloaded bitcoin wallet transfered funds but was 13hrs to sync. Now its only 15% in 24hrs. WHF  I have no idea what to do need help.

**Comment by achow101** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
