### ISSUE TITLE
Spam Filter Code in Tx Relay & Mempool Acceptance Ignores OFAC SDN Sanctions

### ISSUE THREAD

**Issue by derekm** [bitcoin/bitcoin#29137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

As an American Bitcoin miner,
New transactions' inputs and outputs are not checked for OFAC SDN Sanctions against XBT,
Therefore I am exposed to the risk of imprisonment should I mine a block containing txns for specially designated nationals and blocked persons.

### Expected behaviour

As an American Bitcoin miner,
I should be able to configure my node to check incoming transactions for OFAC SDN Sanctions against XBT,
Because I cannot legally mine a block containing txns for specially designated nationals and blocked persons.

### Steps to reproduce

1. Submit a standard transaction involving a specially designated national or blocked person
2. Watch it be accepted by any and all Bitcoin nodes
3. ???
4. PROFIT!

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@c840dea27e

### Operating system and version

MINGW64 MSYS2

### Machine specifications

Surface Laptop Go 2

**Comment by derekm** [comment]
What XBT sanctions all American citizens must implement can be found here: https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml

**Comment by tshev** [comment]
Thank you for highlighting the issue!

**Comment by derekm** [comment]
@fanquake -- Bitcoin Core's spam filter code already has this `Solver` utility which provides a `vSolutionsRet` output parameter that contains exactly the data that needs to be matched against OFAC SDN sactions against XBT: https://github.com/bitcoin/bitcoin/blob/master/src/script/solver.cpp#L140

I am working on a PR to implement enforcement of these Sanctions, which enforcement is required of every U.S. person or foreign persons working for U.S. persons.

With this Issue being posted to the official repository for Bitcoin and with this Issue being closed by an official representative of Bitcoin Core, sanctions violations on Bitcoin have now moved from "negligent" to "culpable mental state greater than negligence." Thank you for your service.
