### ISSUE TITLE
is a getBlockTemplate transactions's bug?

### ISSUE THREAD

**Issue by zhaocaipeng** [bitcoin/bitcoin#29166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I invoke the getBlockTemplate interface using SegWit. The sum of weights in the returned transactions data is 3991625, and the sum of SigOps is 20037. Each time, I package all the transactions returned by getBlockTemplate into a block. I observe that the weight limit is 4000000, and the data returned complies with this requirement. However, I notice that the SigOp limit is 80000, and it is said that the sum of SigOps in transactions needs to be multiplied by 4, which in this case, 20037 * 4, exceeds 80000. I would like to know if mining a block in such a situation where SigOps exceed the limit will still be considered valid. Will it have any impact on the Coinbase reward and transaction fees?

### Expected behaviour

If this is indeed a bug, we hope for a prompt resolution.

### Steps to reproduce

bitcoind25.0 mainnet

### Relevant log output

![bug](https://github.com/bitcoin/bitcoin/assets/5387430/0645c2e3-7791-47c0-bf05-13d92ae7f7d5)

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v25.0

### Operating system and version

Macos 12.4

**Comment by glozow** [comment]
If you have a general question, consider asking on [stack exchange](https://bitcoin.stackexchange.com/).

If this is a bug report, what was the JSON result returned from `getblocktemplate` when this happened?

**Comment by zhaocaipeng** [comment]
> If you have a general question, consider asking on [stack exchange](https://bitcoin.stackexchange.com/).
> 
> If this is a bug report, what was the JSON result returned from `getblocktemplate` when this happened?

I'm not entirely sure if this is a bug. Is the sum of sigops in the transaction details returned by getBlockTemplate not allowed to exceed 2000?
