### ISSUE TITLE
v26 release not available via HomeBrew

### ISSUE THREAD

**Issue by so7ow** [bitcoin/bitcoin#29190]
I'm just curious how that works. Is there some reason v26 still isn't available on HomeBrew?

https://formulae.brew.sh/formula/bitcoin

**Comment by fanquake** [comment]
See https://github.com/Homebrew/homebrew-core/pull/156745. That PR is currently blocked on test-failures in the brew (Linux) CI.

**Comment by so7ow** [comment]
> See [Homebrew/homebrew-core#156745](https://github.com/Homebrew/homebrew-core/pull/156745). That PR is currently blocked on test-failures in the brew (Linux) CI.

Thanks for the pointer!
