### ISSUE TITLE
Enable `maxfeerate` and `maxburnamount` as startup config options.

### ISSUE THREAD

**Issue by ismaelsadeeq** [bitcoin/bitcoin#29217]
### Please describe the feature you'd like to see added.

`maxfeerate` is a sanity check optional parameter used by clients to ensure transactions submitted to the mempool and relayed to the network by a node with`sendrawtransaction`, `testmempoolaccept` and now possibly `submitpackage` #28950 does not exceed the `maxfeerate` value. 
Node will reject transactions whose fee rate is higher than `maxfeerate`. 

`maxburnamount` is also a sanity check optional parameter used by `sendrawtransaction` now possibly `submitpackage` #28950 to reject all transactions with `OP_RETURN` outputs greater than the `maxburnamount`. 

---
Should we enable passing `maxburnamount` and `maxfeerate`  as startup-config options to be used by those RPC calls instead?

### Is your feature related to a problem, if so please describe it.

Requested here https://github.com/bitcoin/bitcoin/pull/28950#discussion_r1444456650

### Describe the solution you'd like

Add startup config options `maxfeerate`, and `maxburnamount` as a sanity check for transactions entering the mempool and relayed to the network.

**Comment by cecuabin** [comment]
2(d11ts1)/1^-b^^-2/9 + ddx(Ass.V).dmb
R2 = rm^2 + 2/1 (oh^-eipi^n2-2*mf.rsc
n^3x.u'/ r^2, 64pi rnt?d3/4*.int
-L^2 = 0rc . g3/2pi / Am^-pu.u*.lk
z = r^2 v^2 - 2*.zip
3+1/2Nmf = -Aq' . 1/2hco.dnc
Trc . dt^2 = oH
OH = 5Tu' . 3/5q^2
dryHe = Frv^vu^2
10KT = / . 2/1 Api/-pu.ucc
DM = ds^5/4 - pu^-2mû'. -hu!
arcsen^2 = Apu'-mf'/1
5/0- . Mo - ddt^2E = GEo . Q^nk . pEc - Ec2
dt = 3/2j - dc2 . t^h + KPR+-4/27
mu^2 = -t^2 + arcsen r^216pirsc^-2/1
s = -2/1 rsc^2 - TKqu' +DEc
o = -pmiEc't^3/2
a = d-pmu . QPRRct
q = +- -2/1dp (-R)
cos159 = ^8pi^KPR 24/7 + 2/3 pidrt^2ms / r^2arsen3/0
FRmo = Amu + KP445 -r^2h
gcr =dt^3 . -1/2dt

**Comment by glozow** [comment]
fwiw I'm concept -0 on adding a global `maxburnamount` option. I think it's less footgunny for the default to always be 0 and for users specify explicitly each time they want to burn money. But if people really want this then ok.

**Comment by ismaelsadeeq** [comment]
Closing this, after @glozow feedback here https://github.com/bitcoin/bitcoin/pull/29278#discussion_r1459131869
