### ISSUE TITLE
clang-format returns error

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#29214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

clang-format is curently broken for me (possibly related to #29056, fyi @maflcko  )
I'm using Ubuntu clang-format version 14.0.0-1ubuntu1.1

### Expected behaviour

no error

### Steps to reproduce

Add a newline anywhere in e.g. `addrman.cpp`, commit, then `git diff -U0 HEAD~1.. | ./contrib/devtools/clang-format-diff.py -p1 -i -v` as described in `contrib/README.md`

### Relevant log output

```
Formatting src/addrman.cpp
/home/martin/bitcoin/28956_adjusted/src/.clang-format:46:33: error: invalid boolean
BreakBeforeConceptDeclarations: Always
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master

### Operating system and version

Ubuntu 22.04.3 LTS

**Comment by mzumsande** [comment]
> Not sure why that happens, maybe the setting was a boolean before?

Yes, that's the case, [14.0.0 doc](https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html)

The other added option, `RequiresExpressionIndentation`, also leads to an error since it was only added in clang-format 16 (https://clang.llvm.org/docs/ClangFormatStyleOptions.html) so I would need to upgrade to that. 
Happy to upgrade if this not a problem for anyone else, I usually use gcc anyway.

**Comment by fanquake** [comment]
@mzumsande I'm guessing you switched to using a newer Clang here? Note that our minimum required Clang is also now 15, which would "solve" the original issue, however not the `RequiresExpressionIndentation` issue, but my suggestion would be to use clang-16+ if possible.

**Comment by TheCharlatan** [comment]
Might be good to note that since #29251 it is also possible to manually specify a clang format binary with the `-binary` option. It should be trivial to install a newer clang format on ubuntu, so I think this can be closed?

**Comment by mzumsande** [comment]
>  I'm guessing you switched to using a newer Clang here?

Well, lets's say I could have switched to a newer Clang if I wasn't so lazy about these kind of things and if I used clang-format more often...
But that's on me, and since there are multiple workarounds like the one by @TheCharlatan , I'll close.
