### ISSUE TITLE
Update nChainTx to 64bit type

### ISSUE THREAD

**Issue by ajtowns** [bitcoin/bitcoin#29258]
https://github.com/bitcoin/bitcoin/blob/8106b268cde8e97a7c330afdda39b6bb55e5574a/src/chain.h#L178-L186

Hey, it's 2024! `nChainTx` seems to currently be 953368191 (height 826100), which is hex `38d3 3e7f`, so we're only 22% of the way to an overflow, and would still need another 200k blocks (~ four years) full of 60 byte transactions to get there.

**Comment by ajtowns** [comment]
Background: https://github.com/bitcoin/bitcoin/pull/13875 and https://github.com/bitcoin/bitcoin/pull/1677

**Comment by russeree** [comment]
Would this be a hard fork because it would be loosening the conditions for validation?

**Comment by mzumsande** [comment]
> Would this be a hard fork because it would be loosening the conditions for validation?

I don't think so, since I don't think the value of `nChainTx` is used in validation (or do you see a spot where it is?). It's used for logging (progress estimation), and whether it is 0 is used in `HaveNumChainTxs`. The latter could become problematic in case of an overflow, since if the `unsigned int` would overflow exactly to zero (which is a bit unlikely given that there are a few thousand txns in each block but ceratainly possible) the node would crash in https://github.com/bitcoin/bitcoin/blob/478ac185be49feffd1231366c07e06068683f941/src/validation.cpp#L3017.

**Comment by russeree** [comment]
^^^ The above was the line that I was referencing. Thank you.

**Comment by Sjors** [comment]
There was also the idea of dropping this number entirely: https://github.com/bitcoin/bitcoin/pull/13875#issuecomment-410472259

**Comment by ryanofsky** [comment]
> This leads to an alternative solution to not increase the memory footprint: Move the 32+32 bits used for nTx and nChainTx into a single 64-bit blob, where the 16 bit are for nTx and the remaining for nChainTx. But, again, the overall heap memory usage shouldn't change much, either way.

This does seem like an nice and easy solution. Would be good to incorporate in #29331

As a tangent, I was thinking along the same lines last week before implementing #29370 and came up with worse solution, taking advantage of the fact that when `nChainTx` is set, you can derive `nTx` by subtracting `nChainTx - pprev->nChainTx`. In case it's interesting:

<details><summary>nChainTx hack</summary>
<p>

```c++
class CBlockIndex
{
public:
    CBlockIndex* pprev{nullptr};

    // Indicate whether num_tx_value contains total number of transactions in
    // this block, or total number of transactions in the chain up and including
    // this block.
    enum NumTxType { UNSET = 0, BLOCK_TX = 1, CHAIN_TX = 2 };
    NumTxType num_tx_type : 4 {UNSET};
    uint64_t num_tx_value : 60;

    uint64_t NumBlockTx()
    {
        if (num_tx_type == BLOCK_TX) return num_tx_value;
        if (num_tx_type == CHAIN_TX) {
            assert(pprev && pprev->num_tx_type == CHAIN_TX);
            return num_tx_value - pprev->num_tx_value;
        }
        return 0;
    }

    uint64_t NumChainTx()
    {
        return num_tx_type == CHAIN_TX ? num_tx_value : 0;
    }
};
```

**Comment by ryanofsky** [comment]
> Not sure if it so easy. On 32-bit platforms, `nTx` currently starts at byte 60, so making it 16-bit will still eat 32-bit with padding.

I didn't test on a 32-bit platform, but aren't bitfields a good solution to this? The following seems to work for me, increasing `nChainTx` range without increasing `CBlockIndex` size on x86_64 (144 bytes):


<details><summary>diff</summary>
<p>

```diff
--- a/src/chain.h
+++ b/src/chain.h
@@ -178,7 +178,7 @@ public:
     //! Note: this value is faked during UTXO snapshot load to ensure that
     //! LoadBlockIndex() will load index entries for blocks that we lack data for.
     //! @sa ActivateSnapshot
-    unsigned int nTx{0};
+    uint16_t nTx : 16 {0};
 
     //! (memory only) Number of transactions in the chain up to and including this block.
     //! This value will be non-zero only if and only if transactions for this block and all its parents are available.
@@ -188,7 +188,7 @@ public:
     //! have the underlying block data available during snapshot load.
     //! @sa AssumeutxoData
     //! @sa ActivateSnapshot
-    unsigned int nChainTx{0};
+    uint64_t nChainTx : 48 {0};
 
     //! Verification status of this block. See enum BlockStatus
     //!
@@ -412,7 +412,12 @@ public:
 
         READWRITE(VARINT_MODE(obj.nHeight, VarIntMode::NONNEGATIVE_SIGNED));
         READWRITE(VARINT(obj.nStatus));
-        READWRITE(VARINT(obj.nTx));
+
+        uint64_t num_tx;
+        SER_WRITE(obj, num_tx = obj.nTx);
+        READWRITE(VARINT(num_tx));
+        SER_READ(obj, obj.nTx = num_tx);
+
         if (obj.nStatus & (BLOCK_HAVE_DATA | BLOCK_HAVE_UNDO)) READWRITE(VARINT_MODE(obj.nFile, VarIntMode::NONNEGATIVE_SIGNED));
         if (obj.nStatus & BLOCK_HAVE_DATA) READWRITE(VARINT(obj.nDataPos));
         if (obj.nStatus & BLOCK_HAVE_UNDO) READWRITE(VARINT(obj.nUndoPos));
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -5119,7 +5119,7 @@ double GuessVerificationProgress(const ChainTxData& data, const CBlockIndex *pin
 
     double fTxTotal;
 
-    if (pindex->nChainTx <= data.nTxCount) {
+    if (static_cast<int64_t>(pindex->nChainTx) <= data.nTxCount) {
         fTxTotal = data.nTxCount + (nNow - data.nTime) * data.dTxRate;
     } else {
         fTxTotal = pindex->nChainTx + (nNow - pindex->GetBlockTime()) * data.dTxRate;
```

**Comment by ryanofsky** [comment]
> Jup, that didn't work for me. Or maybe I did something wrong. See https://godbolt.org/z/z6EoWKbjY

It's not that surprising that the compiler adds padding so the struct member with uint64_t type is inside a field aligned to 8 bytes. But if you move the two bitfield members to begin on an 8 byte boundary (like between the nDataPos and nUndoPos fields, or to the beginning of the struct, it does get packed without extra padding). So I think the diff above is an easy way to avoid consuming extra memory on 64 bit platforms, even though we could go further with more changes to get the same optimization on 32 bit.

**Comment by ajtowns** [comment]
> > bitfields
> 
> Jup, that didn't work for me. Or maybe I did something wrong. See https://godbolt.org/z/z6EoWKbjY
> 
> ```
>    60:0-15 |   int16_t nTx
>    64:0-47 |   int64_t nChainTx
> ```
> 
> (nTx eats byte 60-64, even though it is only a two byte bitfield)

Enclosing `nTx` and `nChainTx` in a sub-struct `struct hack { int16_t nTx : 16 {0}; int64_t nChainTx : 48 {0}; };` seems to fix this for me, fwiw.

**Comment by ajtowns** [comment]
> > bitfields
> 
> Jup, that didn't work for me. Or maybe I did something wrong. See https://godbolt.org/z/z6EoWKbjY
> 
> ```
>    60:0-15 |   int16_t nTx
>    64:0-47 |   int64_t nChainTx
> ```
> 
> (nTx eats byte 60-64, even though it is only a two byte bitfield)

I think the problem here is you have an odd number of 32-bit pointers prior to `nTx`, so it's misaligned to be combined with `nChainTx`. So you end up with `nTx [4B-6B padding] nChainTx nStatus [4B padding]`. Moving `nStatus` prior to `nTx` gives an even number of 32-bit objects prior to `nTx`, so drops the size back down.
