### ISSUE TITLE
UPNP is not disabled when tor-only settings are in effect. 

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#2927]
With the following enabled, UPNP *should not* attempt to open a port at the router for 8333, however in the latest stable the port is uselessly opened. At best it's doing nothing productive, at worst it's just advertising the existence of a bitcoin client. 

    onlynet=tor
    tor=127.0.0.1:9050
    discover=0
    listen=0

Compiling with USE_UPNP=- works as a temporary solution, but is by no means ideal.

**Comment by laanwj** [comment]
Foremost, if your goal is to hide completely behind a proxy you should use `-proxy`, not `-tor`. `-tor` is *only* meant for hyrid Tor/clearnet nodes.

Given that, see #6153 for fix.
