### ISSUE TITLE
Build error on macOS, tag v26.0 builds fine

### ISSUE THREAD

**Issue by mjdietzx** [bitcoin/bitcoin#29289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I can't build master on macOS

### Expected behaviour

Builds fine when I checkout tag v26.0. I don't remember getting this error in the past

### Steps to reproduce

The build commands I've tried result in this error:

```sh
./autogen.sh &&./configure --with-gui=yes && make clean && make -j 4
```

```sh
./autogen.sh && ./configure CC=clang CXX=clang++ --without-bdb --with-gui=yes && make clean && make -j 4
```

```sh
./autogen.sh && ./configure CC=clang CXX=clang++ --with-incompatible-bdb --enable-suppress-external-warnings --with-gui=yes && make clean && make -j 4
```

### Relevant log output

```CXX      wallet/rpc/libbitcoin_wallet_a-addresses.o
wallet/interfaces.cpp:611:20: error: call to implicitly-deleted copy constructor of 'util::Result<std::unique_ptr<interfaces::Wallet>>::T' (aka 'std::unique_ptr<interfaces::Wallet>')
            return wallet;
                   ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:1584:3: note: copy constructor is implicitly deleted because 'unique_ptr<interfaces::Wallet>' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
./util/result.h:47:14: note: passing argument to parameter 'obj' here
    Result(T obj) : m_variant{std::in_place_index_t<1>{}, std::move(obj)} {}
             ^
wallet/interfaces.cpp:625:20: error: call to implicitly-deleted copy constructor of 'util::Result<std::unique_ptr<interfaces::Wallet>>::T' (aka 'std::unique_ptr<interfaces::Wallet>')
            return wallet;
                   ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:1584:3: note: copy constructor is implicitly deleted because 'unique_ptr<interfaces::Wallet>' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
./util/result.h:47:14: note: passing argument to parameter 'obj' here
    Result(T obj) : m_variant{std::in_place_index_t<1>{}, std::move(obj)} {}
             ^
wallet/interfaces.cpp:636:20: error: call to implicitly-deleted copy constructor of 'util::Result<std::unique_ptr<interfaces::Wallet>>::T' (aka 'std::unique_ptr<interfaces::Wallet>')
            return wallet;
                   ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:1584:3: note: copy constructor is implicitly deleted because 'unique_ptr<interfaces::Wallet>' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
./util/result.h:47:14: note: passing argument to parameter 'obj' here
    Result(T obj) : m_variant{std::in_place_index_t<1>{}, std::move(obj)} {}
             ^
wallet/interfaces.cpp:651:16: error: call to implicitly-deleted copy constructor of 'util::Result<interfaces::WalletMigrationResult>::T' (aka 'interfaces::WalletMigrationResult')
        return out;
               ^~~
./interfaces/wallet.h:435:29: note: copy constructor of 'WalletMigrationResult' is implicitly deleted because field 'wallet' has a deleted copy constructor
    std::unique_ptr<Wallet> wallet;
                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:1584:3: note: copy constructor is implicitly deleted because 'unique_ptr<interfaces::Wallet>' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
./util/result.h:47:14: note: passing argument to parameter 'obj' here
    Result(T obj) : m_variant{std::in_place_index_t<1>{}, std::move(obj)} {}
             ^
4 errors generated.
make[2]: *** [wallet/libbitcoin_wallet_a-interfaces.o] Error 1
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@03752444cd

### Operating system and version

macOS Monterey 12.0.1

**Comment by edilmedeiros** [comment]
How are you getting your dependencies?

I just compiled it in a box with Brew following the official instructions, and I could build it.
When using a box with Macports, the build breaks too.

Both have Apple clang version 15.0.0 (clang-1500.1.0.2.5) in Sonoma 14.2.

**Comment by jarolrod** [comment]
I would check the clang version on your system, in any case the [dependencies doc](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md) now states that the minimum required clang is 14.

Cannot replicate on a fresh install of macOS 12.0.1 which has Apple Clang version 13.1.6 and the command line developers tools script installed Xcode 13.4. Note that, according to [this](https://trac.macports.org/wiki/XcodeVersionInfo#Xcode12.5.1), It does seem that depending on when you had installed macOS 12.0.1 and when you had setup the environment, that it would have came with clang 12.0.0.

**Comment by mjdietzx** [comment]
> Which version of clang are you using?

```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I tried building master @ f1ab078ed7742c3350438f0315846948cf317e67 on my newer MacBook Pro. Builds properly with no errors. Where clang version is:
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

> in any case the [dependencies doc](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md) now states that the minimum required clang is 14.

I did not realize this. That explains it. 

> How are you getting the dependencies?

In both cases I install/update dependencies with brew, eg: `brew install automake boost ccache git libevent libnatpmp libtool llvm miniupnpc pkg-config python qrencode qt@5 sqlite zeromq`. The PITA is clang (because it is installed by Xcode)

I think the conclusion is that I'm on clang 13 and need to upgrade. I'll close this issue (I don't have the will power to upgrade Xcode/clang on that machine right now and verify, but if it doesn't resolve the issue when I get to this I'll report back)
