### ISSUE TITLE
Mac App UI is freezed most of the time, with no active peers

### ISSUE THREAD

**Issue by gentlee** [bitcoin/bitcoin#29293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

App is not responding most of the time, mouse is spinning. It is totally unusable.
And also there is no stable active peers - there is almost no progress for 2 weeks.

Seems that "connecting to peers" and the beginning of "synchronizing with network" operation block UI thread.

![btc](https://github.com/bitcoin/bitcoin/assets/2361140/3ab5f708-808f-427b-bda9-8885a82969c8)

If start loading from the beginning, progress is going but also pretty slow, and slows down with time.

### Expected behaviour

1. App never freezes UI and is always responsive.
2. There are active working peers without the need of manually adding them.

### Steps to reproduce

Run the app while having 80.78% progress, on HDD.

### Relevant log output

![Screenshot 2024-01-23 at 03 28 56](https://github.com/bitcoin/bitcoin/assets/2361140/1e383bfe-0da4-4571-b935-d5467a518439)

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v26.0.0

### Operating system and version

MacOS 13.6 (22G120)

### Machine specifications

Macbook Air M1
16Gb
External HDD 2Tb

### Advice for developers

Never block threads in the app's code, it is an antipattern, especially the main thread when doing IO operations. It shows a very low level of competence.

1. Use non-blocking synchronization when needed - like serial queues, instead of mutexes. Check Grand Central Dispatch (GCD) lib (not sure if it can be used in C++, or what is its analog).
2. Use non-blocking apis for IO operations.

**Comment by fanquake** [comment]
cc @hebasto

**Comment by furszy** [comment]
I briefly started working on this in the past but stopped because of the new GUI development.
Depending on the new GUI progress, I could (slowly but steady) start improving this situation.
