### ISSUE TITLE
Clang 14 emits `-Wunreachable-code` warnings

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#29334]
```
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
...
CXX      wallet/libbitcoin_wallet_a-walletdb.o
wallet/walletdb.cpp:1518:15: warning: code will never be executed [-Wunreachable-code]
        error = Untranslated(strprintf("Failed to open database path '%s'. Build does not support Berkeley DB database format.", fs::PathToString(path)));
              ^
wallet/walletdb.cpp:1513:19: note: silence by adding parentheses to mark code as explicitly dead
    if constexpr (true) {
                  ^
                  /* DISABLES CODE */ ( )
wallet/walletdb.cpp:1506:19: warning: code will never be executed [-Wunreachable-code]
            error = Untranslated(strprintf("Failed to open database path '%s'. Build does not support SQLite database format.", fs::PathToString(path)));
                  ^
wallet/walletdb.cpp:1501:23: note: silence by adding parentheses to mark code as explicitly dead
        if constexpr (true) {
                      ^
                      /* DISABLES CODE */ ( )
2 warnings generated.
...
```

Seems related to https://github.com/bitcoin/bitcoin/pull/29315.

Not happening with Clang 15 in the macOS CI job.

**Comment by hebasto** [comment]
> It is sometimes possible for older compilers to print false positive warnings.

I agree.

> This warning can safely be ignored.

It might require some efforts if building routines involve `-Werror`.

**Comment by fanquake** [comment]
> It might require some efforts if building routines involve -Werror.

Wouldn't you just pass `-Wno-unreachable-code` ?

In any case, I don't think there's anything else we can do here, other than suggest using a fixed compiler and/or stop using `-Werror`.

**Comment by fanquake** [comment]
Closing as upgrade compiler / pass a flag to disable the false positive / don't pass error flags to turn known false positives into compile failures.

**Comment by vasild** [comment]
I see, commented in https://github.com/bitcoin/bitcoin/pull/29315#issuecomment-1948486081
