### ISSUE TITLE
bitcoin core v.26 shuts down without warning - Doesnt save blocks downloaded

### ISSUE THREAD

**Issue by Rucade** [bitcoin/bitcoin#29348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

bitcoin core v.26 shuts down all the time unexpectedly, crashes and asks to Force Quit or wait so it does not save the blocks downloaded unless I shut it down first which is a terrible task every few minutes. I am at June 22nd 2023 for days trying to download the rest of the blocks. How do I fix this "bug"?

### Expected behaviour

to get the core loading properly I need to fix this bug or ERROR
REPLY from Canonical: Please open a bug using this link: https://help.ubuntu.com/stable/ubuntu-help/report-ubuntu-bug.html.en

### Steps to reproduce

Emailed Canonical and Qt.io

### Relevant log output

I cant open the debug log

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v.26 run on bitcoin Qt

### Operating system and version

Ubuntu 

### Machine specifications

HP intel core i5

**Comment by Rucade** [comment]
debug log
[debug.log](https://github.com/bitcoin/bitcoin/files/14097165/debug.log)

**Comment by Rucade** [comment]
> Please check your debug.log for possible causes; Alternatively you can upload it here.
> 
> You can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).
> 
> Please be aware that the debug log might contain personally identifying information.

[debug.log](https://github.com/bitcoin/bitcoin/files/14097173/debug.log)

**Comment by fanquake** [comment]
> 2024-01-19T10:49:39Z Bitcoin Core version v22.0.0 (release build)

Are you sure you are running 26.0? Your logs claim 22.0.

**Comment by Rucade** [comment]
> > 2024-01-19T10:49:39Z Bitcoin Core version v22.0.0 (release build)
> 
> Are you sure you are running 26.0? Your logs claim 22.0.

You may be right there. I had v.22 but I downloaded v.26 later because of serious errors and it may have kept the debug log from 22 but I did erase all the blockdir and started again fresh. So, should I erase everything delete all the files in .bitcoin linux ubuntu and start fresh on windows?

**Comment by willcl-ark** [comment]
This sounds most likely like a hardware malfunction to me too.

In any case you could try rotating your debug log (to start a fresh one) and this time be sure to use v26.0, then upload _that_ debug log here if the problem persists? Something like:

```bash
# rotate debug log
$ mv ~/.bitcoin/debug.log ~/.bitcoin/debug.log.1

# check that you are going to run v26.0
$ bitcoind --version
Bitcoin Core version v26.0
Copyright (C) 2009-2023 The Bitcoin Core developers

# Start v26.0
$ bitcoind
```

This might not tell us much more if the issue _is_ hardware-related, with a few checks you can do to try and determine that detailed above by maflcko.

Can you provide any additional hardware details?

*Careful running the following `sudo` commands below if you are not sure what they do*

* CPU: model (can check with `lscpu | grep "Model name"`
* HDD: type e.g. SSD, spinning disk (check with `sudo lshw -class disk -class storage` or `smartctl` as described above)
* RAM: size (GB), type (e.g. DDR4) (check with `sudo dmidecode --type memory`)

> So, should I erase everything delete all the files in .bitcoin linux ubuntu and start fresh on windows?

If it's a hardware issue and you have both OSes on the same machine, I wouldn't expect this to help much. If these OSes are different machines, then I would expect this to help.

**Comment by willcl-ark** [comment]
Hey @Rucade, I'm going to close this now as I don't think there's anything to be done on the Bitcoin Core side.

Feel free to open a new issue if this re-occurs fo you using v26.0
