### ISSUE TITLE
loadtxoutset fails to recognize assumeutxo blockhash

### ISSUE THREAD

**Issue by techy2** [bitcoin/bitcoin#29340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Unable to load UTXO snapshot, assumeutxo block hash in snapshot metadata not
 recognized (00000000000000000000d4041fe771edd9dcb945bb85dfa739af1d2724a464e8)
 (code -32603)

### Expected behaviour

expect txoutset to load properly

after researching issues, can't tell if this is new or has been recently fixed, so reporting as new

### Steps to reproduce

on 64 bit ubuntu bionic bitcoin-qt v26.0
dumptxoutset /path/to/txoutsetsave

transfer file to 32 bit focal  bitcoin-qt v26.0, then:
loadtxoutset /path to/txoutsetsave

### Relevant log output

n/a

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v26.0 64bit compiled on target host, 32 cross compiled on ubuntu 20.04, details below

### Operating system and version

see below

### Machine specifications

Sending end, v26.0 64 bit
Linux mn128 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 
x86_64 x86_64 x86_64 GNU/Linux
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

gcc (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
g++ (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0

 dumptxoutset /root/txoutset
{
  "coins_written": 160267297,
  "base_hash": "00000000000000000000d4041fe771edd9dcb945bb85dfa739af1d2724a464e8",
  "base_height": 827848,
  "path": "/root/txoutset",
  "txoutset_hash": "45e02b1822285f0d1643d9e94492eb0fb7f0db74fc62f39ddc7345b28b98bb92",
  "nchaintx": 958978137
}

receiving end, 
14:29:45

Linux bitcoinKB 5.4.81-pup32 #1 SMP Fri Dec 4 10:09:29 GMT 2020 
 i686 i686 i686 GNU/Linux (focal32 20.12)

bitcoin built 
5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022
 x86_64 x86_64 x86_64 GNU/Linux
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

#
loadtxoutset /mnt/sda2/txoutset

14:29:46
#
Unable to load UTXO snapshot, assumeutxo block hash in snapshot metadata not
 recognized (00000000000000000000d4041fe771edd9dcb945bb85dfa739af1d2724a464e8)
 (code -32603)

**Comment by achow101** [comment]
Loaded utxo sets need to match hardcoded utxo set and block hashes. These are currently not set for mainnet and so `loadtxoutset` is not expected to work on mainnet.

**Comment by techy2** [comment]
The release notes indicate this is a new feature, it does not mention that it is not expected to work. Looks like a nice feature. You should clarify the release notes PLEASE.

[bitcoin](https://github.com/bitcoin/bitcoin/tree/master)/[doc](https://github.com/bitcoin/bitcoin/tree/master/doc)/[release-notes](https://github.com/bitcoin/bitcoin/tree/master/doc/release-notes)

/release-notes-26.0.md
New RPCs

    loadtxoutset has been added, which allows loading a UTXO snapshot of the format generated by dumptxoutset. Once this snapshot is loaded, its contents will be deserialized into a second chainstate data structure, which is then used to sync to the network's tip.

    Meanwhile, the original chainstate will complete the initial block download process in the background, eventually validating up to the block that the snapshot is based upon.

    The result is a usable bitcoind instance that is current with the network tip in a matter of minutes rather than hours. UTXO snapshot are typically obtained via third-party sources (HTTP, torrent, etc.) which is reasonable since their contents are always checked by hash.
