### ISSUE TITLE
Please help me figure out why this transaction is not confirmed?

### ISSUE THREAD

**Issue by Wwwwwwuuuuu** [bitcoin/bitcoin#29351]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

Please help me figure out why this transaction is not confirmed?8f62acf0f0ddc3e38db2e8ec2755f4e54aa5bf616d685e2f3361155fc9d44125

**Comment by willcl-ark** [comment]
(It looks like the fee is a bit low for current mempool conditions.)

This issue tracker is used to track technical issues related to the Bitcoin Core code base.

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on the [Libera Chat](https://libera.chat/) network.

For proposed protocol changes you can post to the bitcoin-dev [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev).

For general bitcoin discussion you can try [bitcointalk](bitcointalk.org) or [reddit.com/r/bitcoin](reddit.com/r/bitcoin)
