### ISSUE TITLE
PaymentRequest GUI bugs

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#2936]
I consider these low priority, for two reasons:

1) I think the vast majority of payment requests will be signed and will involve payment to just one merchant.

2) I think the whole "send" GUI needs a redesign; I tried to do the absolute minimum amount of GUI work to demonstrate payment protocol functionality (I'm a terrible GUI designer).

From michagogo:

Binary used: http://jenkins.bluematt.me/pull-tester/a41d5fe01947f2f878c055670986a165af800f9a/bitcoin/bitcoin-qt.exe

On the unsigned payment request test, even though the address and amount _are_ editable, editing them doesn't have any effect -- the address and value entered into the web form are what ends up getting sent regardless of what's entered into those boxes.

In the Signed payment request test: I don't know if this is intentional, but if clicking on more CLICK TO PAY links before confirming the first send causes the other payments to be added as outputs to the transaction, with no way to remove individual transactions without using the Clear All button.

When sending multiple PaymentACKs, the dialog boxes are modal on top of each other, and out of order.

A signed request, even one with multiple outputs, will show up in the Send tab as one entry, while an unsigned request with multiple outputs shows up as one entry per output.

Either unsigned requests cannot expire and the request generator just doesn't make that clear, or expiration is ignored in unsigned requests.

I'm not sure if I like the behavior of "unsigned payment requests add the address to your address book with the contents of the memo field if it's not already there"... I'd maybe make it a checkbox or something, if not remove it completely -- oh, just realized it's because it uses the "Label" field. Seems like a bad idea to me, since payment-protocol addresses are probably not going to be reused...

**Comment by laanwj** [comment]
Closing payment protocol specific issues; as that functionality is going to be deprecated in the near future it's not worth working on.
