### ISSUE TITLE
Bitcoin Core changed to Bitcoin locked..

### ISSUE THREAD

**Issue by A420mfer** [bitcoin/bitcoin#29382]
I'm not a very smart person and I published my http in thinking that was the place to ask for help and it seems someone changed it to Bitcoin locked..and now when I try to go to the server the page won't load and the server was to my JS anywhere app..can anyone help me? I also opened an app called node and when I did all of a sudden it gave me a new http. I'm not sure what to do but I need help badly..it's been years since I set up my node and recently had been trying to set it up in a new phone. I've all of this code in my phone and I'm not sure what I'm supposed to do with it either..

**Comment by willcl-ark** [comment]
This issue tracker is used to track technical issues related to the Bitcoin Core code base.

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on the [Libera Chat](https://libera.chat/) network.

For proposed protocol changes you can post to the bitcoin-dev [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev).

For general bitcoin discussion you can try [bitcointalk](bitcointalk.org) or [reddit.com/r/bitcoin](reddit.com/r/bitcoin)

**Comment by A420mfer** [comment]
Thank you!
