### ISSUE TITLE
build: `CPPFLAGS` usage in OSS-Fuzz

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#29385]
In OSS-Fuzz, dependencies are built with `DEBUG=1`, which implies usage of the additional preprocessor definitions:

```
$ make -C depends print-host_debug_CPPFLAGS HOST=x86_64-pc-linux-gnu DEBUG=1
...
host_debug_CPPFLAGS=-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_LIBCPP_ENABLE_DEBUG_MODE=1
```

However, explicit setting `CPPFLAGS` breaks this assumption:
```
$ make -C depends print-host_debug_CPPFLAGS HOST=x86_64-pc-linux-gnu DEBUG=1 CPPFLAGS="-DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE"
...
host_debug_CPPFLAGS=-DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE
```

Is this expected/desired behaviour?

**Comment by fanquake** [comment]
Should be closed after https://github.com/google/oss-fuzz/pull/11725.
