### ISSUE TITLE
Update security.md with all PGP fingerprints (version 2)

### ISSUE THREAD

**Issue by ariard** [bitcoin/bitcoin#29383]
https://github.com/bitcoin/bitcoin/issues/29366

> You didn't ask one, you made a statement, which I think is sufficiently addressed by encrypting directly to the people who you want to share the information with.

I’m not satisfied by this answer achow101. Let me know what should be the public communication venue to submit such concern.
If one is not satisfied to be on security@bitcoincore.org list whatever the reason, one can resign.

**Comment by achow101** [comment]
Don't open duplicate issues. If you think an issue should be reopened, then say so in that issue.

**Comment by ariard** [comment]
> Don't open duplicate issues. If you think an issue should be reopened, then say so in that issue.

Always making my own assumptions on online behavior of anyone in this space. Thanks.
Saying this, with respect I have for GH maintenance work.
