### ISSUE TITLE
Gathering Priorities of 28.0

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#29439]
Please nominate projects that you are the champion of that could become priorities for the next ~6 months (until the 28.0 release). We (frequent contributors) will vote on which projects will be priorities next week in a separate issue.

There were concerns in the voting of previous priority projects that some projects nominated did not have champions who were willing to have their project be a priority project. To ensure that all nominated projects have champions who want their project to be a priority project, nominations are limited to self-nominations only.

Project priorities are those which the frequent contributors to this project have voted on to have more focused review on for the next ~6 months. This issue is to list what projects are ongoing that can be voted on. Voting will occur in a separate issue that will be opened next week.

Nominations will close at the start of the IRC meeting on February 22nd at 14:00 UTC. The issue for voting will be opened at that time as well.

Nominations and voting is limited to those who are part of the bitcoin github organization. Comments in this issue from those outside of the organization will be ignored, and may be deleted. If you are not part of the organization and believe that you should be, please send me an email or message me on IRC.

**Comment by achow101** [comment]
Legacy wallet removal #20160

**Comment by TheCharlatan** [comment]
libbitcoinkernel #27587

**Comment by josibake** [comment]
Silent payments (BIP352) #28536

**Comment by fjahr** [comment]
Default ASMap #28794

There isn't so much left to do in terms of code/review within the repo but it needs some more focus from reviewers to finish it up. Until recently I considered file creation creation and tooling outside of Bitcoin Core a blocker, which I why I didn't propose it for v27. Now I think we got that out of the way with a simple process that has been demonstrated to work with many contributors involved: https://delvingbitcoin.org/t/asmap-creation-process/548

**Comment by furszy** [comment]
Prune node rescan #29183.

Mid-size functionality. Mentioning in response to requests from users and contributors.

**Comment by glozow** [comment]
Package Relay #27463

**Comment by vasild** [comment]
Broadcast own transactions only via short-lived Tor or I2P connections https://github.com/bitcoin/bitcoin/pull/29415

**Comment by sdaftuar** [comment]
Cluster mempool

**Comment by naumenkogs** [comment]
Erlay #28646
