### ISSUE TITLE
Voting on Priority Projects for 28.0

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#29465]
Please leave your votes for project priorities for the next ~6 months (until the 28.0 feature freeze).

Project priorities are those which the frequent contributors to this project have voted on to have more focused review on until the next feature freeze (or until they are completed). They will become permanent topics in our weekly IRC meetings so that we can get updates on the progress of each project and determine the next step to move them forward.

Voting will close at the start of the IRC meeting on February 29th at 14:00 UTC. To vote, please leave a comment containing the three projects from the list below that you would like to be the priority projects. The priority projects will be the three with the most votes.

Voting is limited to those who are part of the bitcoin github organization, Comments in this issue from those outside of the organization will be ignored, and may be deleted. If you are not part of the organization and believe that you should be, please send me an email or message me on IRC.

The projects to vote on are:

* Silent payments (BIP352) #28536 @josibake 
* Prune node rescan #29183 @furszy 
* Default ASMap #28794 @fjahr 
* Broadcast own transactions only via short-lived Tor or I2P connections #29415 @vasild 
* Cluster mempool #27677 @sdaftuar 
* Package Relay #27463 @glozow 
* Erlay #28646 @naumenkogs 
* libbitcoinkernel #27587 @TheCharlatan 
* Legacy wallet removal #20160 @achow101

**Comment by fjahr** [comment]
Cluster mempool, Silent payments, Default ASMap

**Comment by josibake** [comment]
* Silent payments
* Package Relay
* libbitcoinkernel

**Comment by achow101** [comment]
* legacy wallet removal
* silent payments
* package relay

**Comment by glozow** [comment]
- cluster mempool
- package relay

**Comment by ariard** [comment]
in order of review priorities:
- erlay
- cluster mempool

btw on feature freeze, i believe it could be wise to start to think to introduce “subsystem-dependent” timeline, e.g for mempool it could be far earlier than the project-global feature freeze. that avoids last minute merge as some senior reviewers (apparently showing some sign of “process fatigue") justified recently the merge of #28948 (a controversial change). idea is not new, makes that grief originally in 2021 in the context of tx-relay workshops (cf. [2nd irc meetings notes](https://github.com/ariard/L2-zoology/blob/master/discussions/l2-support-philosophy.md)).

**Comment by instagibbs** [comment]
package relay
cluster mempool

**Comment by pinheadmz** [comment]
- Silent payments (BIP352)

- Prune node rescan

- Broadcast own transactions only via short-lived Tor or I2P connections

**Comment by murchandamus** [comment]
• Cluster Mempool
• Package Relay

**Comment by TheCharlatan** [comment]
* Legacy wallet removal
* Cluster mempool
* Libbitcoinkernel

**Comment by ismaelsadeeq** [comment]
* Package relay
* Cluster mempool
* Silent payment

**Comment by voskhod6** [comment]
Silent payments
Package relay
Legacy wallet removal

**Comment by S3RK** [comment]
- package relay
- legacy wallet removal
- silent payments

**Comment by BrandonOdiwuor** [comment]
- legacy wallet removal
- silent payments
- package relay

**Comment by hebasto** [comment]
- Cluster mempool
- libbitcoinkernel

**Comment by hernanmarino** [comment]
Silent payments (BIP352)
Prune node rescan
Legacy wallet removal

**Comment by sdaftuar** [comment]
cluster mempool
package relay

**Comment by naumenkogs** [comment]
Cluster mempool
Package Relay
Erlay

**Comment by vasild** [comment]
* Broadcast own transactions only via short-lived Tor or I2P connections
* Erlay
* libbitcoinkernel

**Comment by pablomartin4btc** [comment]
- Package Relay
- Default ASMap
- Erlay

**Comment by voskhod6** [comment]
> * Package Relay
> * Default ASMap
> * Erlay

YEP

**Comment by stratospher** [comment]
- Erlay
- Broadcast own transactions only via short-lived Tor or I2P connections

**Comment by ajtowns** [comment]
* Cluster mempool
* Legacy wallet removal
* libbitcoinkernel

**Comment by furszy** [comment]
* Legacy wallet removal
* Prune node rescan
* Silent payments

**Comment by dergoegge** [comment]
* package relay
* cluster mempool
* libbitcoinkernel

**Comment by achow101** [comment]
Final counts:
* Package relay - 14
* Cluster Mempool - 12
* Silent Payments - 10
* legacy wallet removal - 9
* Erlay - 7
* libbitcoinkernel - 6
* Prune node rescan - 4
* Broadcast own transactions only via short-lived Tor or I2P connections - 4
* Default ASMap - 3

**Comment by dergoegge** [comment]
Silent payments was removed as priority project in the last irc meeting an replaced with the legacy wallet removal without asking the silent payment voters if they would like to recast their votes.

If I'm counting correctly, there were 25 voters of which 18 used all three of their votes, including all 10 silent payment voters. This means that the outcome of the vote could be quite different if these votes would be recast.

@fjahr @josibake @achow101 @pinheadmz @theStack @ismaelsadeeq @S3RK @furszy @hernanmarino @BrandonOdiwuor you are the SP voters and should recast your third vote or indicate that you are willing to drop it.

**Comment by hernanmarino** [comment]
I'm ok with dropping my vote for Silent Payments.

**Comment by achow101** [comment]
I will drop my vote as well.

**Comment by furszy** [comment]
Drop my vote too.

**Comment by pinheadmz** [comment]
drop

**Comment by fjahr** [comment]
dropping as well

**Comment by BrandonOdiwuor** [comment]
Drop my vote for Silent Payments

**Comment by TheCharlatan** [comment]
Dropping too.

**Comment by ismaelsadeeq** [comment]
Yes @dergoegge I drop mine as well.
