### ISSUE TITLE
Partial protection against a quantum computer

### ISSUE THREAD

**Issue by Rothschildiuk** [bitcoin/bitcoin#29545]
Since in theory a quantum computer can be much more efficient in mining, it is necessary to protect the blockchain from possible rewriting of transaction history. I would prohibit nodes from switching to a longer chain of transactions if it differs by more than one week, i.e. 1008 blocks, i.e. consider new blocks with a difference of 1008 blocks from the last found to be invalid. This will protect the network from this theoretical attack

**Comment by Rothschildiuk** [comment]
I think it is possible to make 144 blocks instead of 1008, or even 6. But this can and should be discussed.

**Comment by fanquake** [comment]
> But this can and should be discussed.

Feel free to open a thread on the mailing list, or maybe even delving-bitcoin. However, this issue tracker is the wrong place for this high-level discussion.
