### ISSUE TITLE
SEE ALSO section for all man pages

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [bitcoin/bitcoin#29558]
It would be useful to see the related tools in the man page with the typical **SEE ALSO** section

```text
SEE ALSO
    bitcoin-cli(1), bitcoin-tx(1), bitcoin-wallet(1), bitcoin-qt(1), bitcoin-util(1), bitcoind(1)
```

For bitcoind it may also be useful to list **systemctl(1)** and **rcctl(1)**

**Comment by fanquake** [comment]
> For bitcoind it may also be useful to list systemctl(1) and rcctl(1)

While listing our other utilities could be useful, I don't think we need to pick and list other system/service management tools.
