### ISSUE TITLE
Setting-up Bitcoin-core has deprecated libraries or procedures.

### ISSUE THREAD

**Issue by Muniru0** [bitcoin/bitcoin#29554]
Although it may be something minor but when setting-up bitcoin-core I runned into deprecated libraries and procedures. Like below.
![First](https://github.com/bitcoin/bitcoin/assets/34800075/e7ba6826-762f-4316-a4ab-3f5f111eb9d6)

And with this I had to install the Boost headers separately using sudo apt-get install libboost-all-dev.
```
checking for Boost headers >= 1.73.0 (107300)... configure: We could not detect the boost libraries (version 1.73.0 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: Boost is not available!
```

**Comment by hebasto** [comment]
@Muniru0 

What is your system?

**Comment by Muniru0** [comment]
> @Muniru0
> 
> What is your system?

It is WSL(Windows Subsystem for Linux).

**Comment by Muniru0** [comment]
I can correct it and submit a PR if necessary. And I am on Windows 11 Ubuntu-22.04 LTS.

**Comment by hebasto** [comment]
> ... Ubuntu-22.04 LTS.

https://packages.ubuntu.com/jammy/bsdmainutils

**Comment by fanquake** [comment]
I can't recreate youre issue using vanilla `Ubuntu:22.04` and `apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git`. This is either a local issue, or a Windows Subsystem for Linux problem? Closing for now, but feel free to debug further, and let us know if there is something bitcoin core specific that needs fixing here.
