### ISSUE TITLE
Unused variables in RIPEMD160 namespace

### ISSUE THREAD

**Issue by Loopite** [bitcoin/bitcoin#29550]
### Please describe the feature you'd like to see added.

Remove the variables "b" and "d" in the ``Round`` function:
```
void inline Round(uint32_t& a, uint32_t b, uint32_t& c, uint32_t d, uint32_t e, uint32_t f, uint32_t x, uint32_t k, int r)
{
    a = rol(a + f + x + k, r) + e;
    c = rol(c, 10);
}
```

**Comment by araujo88** [comment]
I believe these unused variables are there for standardization purposes, since there are multiple definitions of this inline function across the crypto module.

**Comment by fanquake** [comment]
Thanks. However we are unlikely to make the refactor you are suggesting.
In future, I'd also suggest that opening a PR is a better way to demo a suggested code change, as opposed to an issue. In this case it'd become clear that the change is more involved than just dropping b & d from the function signature.
