### ISSUE TITLE
bitcoin-cli help does not display help

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [bitcoin/bitcoin#29555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The general help command is not helpful.

```sh
$ bitcoin-cli help 
error: timeout on transient error: Could not connect to the server 127.0.0.1:8332

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
```

Specific command help is not helpful.

```sh
$ bitcoin-cli help -addrinfo
error: timeout on transient error: Could not connect to the server 127.0.0.1:8332

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
```

### Expected behaviour

I expect the general help to display something useful.

I expect the help for a specific command to display helpful information about that command.

The man page states that the help has these command input options.

```text
     bitcoin-cli [options] help                List commands
     bitcoin-cli [options] help <command>      Get help for a command
```

I do not expect to have to connect to the remote node to receive help. In fact, the help command should not be doing any networking.

### Steps to reproduce

Ensure that bitcoin-cli cannot connect to a bitcoind node.

Run `bitcoin-cli help`

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

v25.0.0

### Operating system and version

OpenBSD 7.4

**Comment by araujo88** [comment]
@maflcko possible good first issue?

**Comment by araujo88** [comment]
> If you want help _about_ bitcoin-cli, use `bitcoin-cli -help`. Any non-`-` argument to bitcoin-cli is interpreted as a command to send. `bitcoin-cli help` sends the `help` command to the server.

Shouldn't `help` be handled as an exception? Some cli tools are very flexible in that regard.

**Comment by kristapsk** [comment]
> > Shouldn't `help` be handled as an exception to this rule? Some cli tools are very flexible in that regard.
> 
> I think that would be more confusing, actually, by muddying the distinction between local and remote operation. It's also not clear to me how to actually do that as `help` _is_ a valid server command (it gets information about the supported commands).

Also `bitcoin-cli` and `bitcoind`/`bitcoin-qt` could be running different versions, then `bitcoin-cli help something` handled by client could output wrong information regarding RPC server you are trying to connect.

**Comment by Sjors** [comment]
Perhaps the  `Could not connect` error could be expanded with "Use bitcoin-cli -help for more info."

Either always, or only if "help" was passed.
