### ISSUE TITLE
where to find the official tutorial config file guide

### ISSUE THREAD

**Issue by hongda3141** [bitcoin/bitcoin#29674]
Hi, I load a bitcoin core in my desktop, and I confused about how the config file rules the node.
I have found a tutorial from network, that's real helpful,
but I worried weather there is other fake web to deceive newers, considered to do that is so profitable with the bitcoin price nowdays.
So, could I find the official tutorial somewhere like official link?

**Comment by hongda3141** [comment]
> You don't need a website to read the help. With the `--help` option, all options will be printed and explained by the executable binary.

Thanks, But I tried that in the bitcoin command line and return "Method not found", if there a way on how to check config file's rule in the bitcoin core ware, that will be nice.

**Comment by willcl-ark** [comment]
I think we can close this now for the reasons given by @maflcko .

> Thanks, But I tried that in the bitcoin command line and return "Method not found", if there a way on how to check config file's rule in the bitcoin core ware, that will be nice.

The command to list options is: `bitcoind --help`.

You can check which config options are being actively used by the node by checking [the debug log](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location) on startup. If you have a copy of the source code you can run the `contrib/devtools/gen-bitcoin-conf.sh` script, which will generate a skeleton bitcoin.conf with all available options relevant to your current version of the software. If you grabbed a binary dsitribution then `bitcoin.conf` is included at the top level of the directory.

Be sure to check the end of the example config file for guidance on how to use sections properly in the config -- a common source of mistakes :)

Any more usage questions you can ask on StackExchange, libera.chat#bitcoin, reddit etc.

**Comment by hongda3141** [comment]
> I think we can close this now for the reasons given by @maflcko .
> 
> > Thanks, But I tried that in the bitcoin command line and return "Method not found", if there a way on how to check config file's rule in the bitcoin core ware, that will be nice.
> 
> The command to list options is: `bitcoind --help`.
> 
> You can check which config options are being actively used by the node by checking [the debug log](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location) on startup. If you have a copy of the source code you can run the `contrib/devtools/gen-bitcoin-conf.sh` script, which will generate a skeleton bitcoin.conf with all available options relevant to your current version of the software. If you grabbed a binary dsitribution then `bitcoin.conf` is included at the top level of the directory.
> 
> Be sure to check the end of the example config file for guidance on how to use sections properly in the config -- a common source of mistakes :)
> 
> Any more usage questions you can ask on StackExchange, libera.chat#bitcoin, reddit etc.

thanks a lot, that's really helpful
