### ISSUE TITLE
Make it possible to determine fee before sending transaction (RPC)

### ISSUE THREAD

**Issue by Mezrin** [bitcoin/bitcoin#2971]
Due to "https://en.bitcoin.it/wiki/Transaction_fees" there are two types of fees.
Logic for the mandatory comission is not so clear. Also it's difficult to check via existing api will whether the mandatory fee be charged or not. So the command to check will whether the mandatory fee be charged or not will be useful.

Edit: clarified issue title

**Comment by laanwj** [comment]
> It would be nice if the raw transactions API provided access to the coin selection and fee determination logic of the wallet.

This has become possible with `fundrawtransaction`.
