### ISSUE TITLE
Fee estimation disabled

### ISSUE THREAD

**Issue by ray2cycle** [bitcoin/bitcoin#29737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

rpc call and bitcoin-cli estimatesmartfee 6  command return error: 
```
error code: -32603
error message:
Fee estimation disabled
```

bitcoin.conf: 
```
fallbackfee=0.00001
paytxfee=0.0002
maxapsfee=0.0001
```

### Expected behaviour

estimatesmartfee success.

### Steps to reproduce

bitcoin-cli estimatesmartfee 6 

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

Bitcoin Core version v25.0.0

### Operating system and version

Ubuntu 22.04.3 LTS

**Comment by ismaelsadeeq** [comment]
Hi @ray2cycle which options did you start bitcoind with?

Fee estimation is disabled when you start up with `-blocksonly`

It is likely the reason why you are getting this error.

**Comment by ray2cycle** [comment]
> Hi @ray2cycle which options did you start bitcoind with?
> 
> Fee estimation is disabled when you start up with `-blocksonly`
> 
> It is likely the reason why you are getting this error.

Hi, thanks for your replay, my start cmd just : ` ./bitcoind -conf=./bitcoind.conf ` ,   without  `-blocksonly`

**Comment by ray2cycle** [comment]
I changed the startup command to: `bitcoind -blocksonly=false` and the new error was: 

```
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 0
}
```

**Comment by ray2cycle** [comment]
> Insufficient data or no feerate found"

Got it, thank you very much!

**Comment by ray2cycle** [comment]
> In order to get fee estimation for a target of N blocks, you need to have been running for around 2N blocks to gather data.

Got it, thank you very much

**Comment by ismaelsadeeq** [comment]
Built v25.0 to try to recreate this

Fee estimation is working as expected on mainnet.

I think this can be closed cc @willcl-ark
