### ISSUE TITLE
doc: A recipe in `build-unix.md` does not work

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#29755]
This does not work anymore:

>Alternatively, or in addition, debugging information can be skipped for compilation. The default compile flags are
`-g -O2`, and can be changed with:
>
>```
>./configure CXXFLAGS="-O2"
>```

However, I don't think that an immediate action should be taken. Anyway, it will be changed after migration to CMake.

**Comment by TheCharlatan** [comment]
Mmh, just needs a note to override the debug flag?

**Comment by fanquake** [comment]
> This does not work 

Exactly why doesn't work?

> Anyway, it will be changed after migration to CMake.

This is irrelevant. We have to maintain the autotools branches for years into the future, and aren't going to leave them broken/with incorrect docs just because something else might exist.

**Comment by hebasto** [comment]
> > This does not work
> 
> Exactly what doesn't work?

The resulted flags still contain the `-g` flag.

> > Anyway, it will be changed after migration to CMake.
> 
> This is irrelevant. We have to maintain the autotools branches for years into the future, and aren't going to leave them broken/with incorrect docs just because something else might exist.

Right.

**Comment by fanquake** [comment]
> Mmh, just needs a note to override the debug flag?

Yep, looks like that's all that's required.

**Comment by hebasto** [comment]
> > Mmh, just needs a note to override the debug flag?
> 
> Yep, looks like that's all that's required.

Ok. Done in https://github.com/bitcoin/bitcoin/pull/29756.
