### ISSUE TITLE
IBD performance regression in 27.0rc1 on Windows

### ISSUE THREAD

**Issue by vostrnad** [bitcoin/bitcoin#29785]
While investigating the variance in IBD when synchronizing from network nodes and comparing it to synchronizing from a local node, I noticed a significant slowdown when I switched the synchronizing node to 27.0rc1. When connected to a local node (also 27.0rc1), it reaches block 120,000 about 10% slower on average than 26.0, with a much higher variance. I measured around 100 runs of each, alternating between the versions every time. Headers (pre-)sync is not included in the measurement. OS is Windows 10, I'm using pre-built binaries for both versions.

26.0:
![ibd26corrected](https://github.com/bitcoin/bitcoin/assets/43024885/e3b3c7de-ebe8-4620-8ad2-b60ce3375551)

27.0rc1:
![ibd27rc1corrected](https://github.com/bitcoin/bitcoin/assets/43024885/02aa6e7b-5fd0-46f3-bf1e-0be30f1bdcf7)

EDIT: The issue seems to be only with the pre-built release binary for Windows. Tests with a pre-built Linux binary on WSL and a self-built MSVC binary don't show the regression (see later posts).

**Comment by vostrnad** [comment]
I haven't tested it with a different operating system. I can try WSL.

**Comment by vostrnad** [comment]
Tested pre-built binaries on Debian 12 WSL on the same system, measured 45 runs of each. No performance regression, 27.0rc1 is slightly faster on average.

26.0:
![ibdwsl26](https://github.com/bitcoin/bitcoin/assets/43024885/1bc174c9-f88c-410a-aa7a-4a6f683c98d3)

27.0rc1:
![ibdwsl27rc1](https://github.com/bitcoin/bitcoin/assets/43024885/259f84fc-a637-4ba7-8dc7-80e732f353bb)

**Comment by fanquake** [comment]
> Tested pre-built binaries on Debian 12 WSL on the same system, measured 45 runs of each. No performance regression,
> Tested self-built MSVC binaries for 26.0 and 27.0rc1, definitely no regression.

It's not clear to me if there is still an issue here or not. Or is there still a regression when comparing our 26.x and 27.x Windows release binaries?

If the only issue is in relation to self-compiled MSVC binaries, then this isn't a blocker for 27.x.

**Comment by hebasto** [comment]
Speaking of MSVC builds, it's worth noting that they still don't have a hardware-accelerated SHA256 implementation (see https://github.com/bitcoin/bitcoin/pull/24773).

**Comment by vostrnad** [comment]
@maflcko

> I forgot to mention that optimization was enabled in commit https://github.com/bitcoin/bitcoin/commit/41e378a0a1f0729b423034f47c28a4e83287a1e8. So for a fair comparison, one would have to backport https://github.com/bitcoin/bitcoin/commit/41e378a0a1f0729b423034f47c28a4e83287a1e8 to 26.0.

The original regression is also in variance which doesn't appear with the MSVC binary, so I don't think it's necessary to test the backport.

@fanquake

> It's not clear to me if there is still an issue here or not. Or is there still a regression when comparing our 26.x and 27.x Windows release binaries?

The regression is in the pre-built 27.0rc1 binary for Windows (which isn't MSVC), see original post. Pre-built binary for Linux tested on WSL and self-built MSVC binary for Windows don't have the regression, see later posts.

**Comment by m3dwards** [comment]
I can try and recreate this. @vostrnad do you have a script that records / plots the graphs?

**Comment by vostrnad** [comment]
> Can you also let us know if you're using any particular config options etc.

Beyond the bare minimum (`-connect`, `-datadir`, RPC user/pass etc.) I'm just increasing dbcache and enabling pruning, but neither of those should kick in at this block height. I'll test again using the defaults just to be sure.

> how are you able to perform so many runs in such a short amount of time? Do you have access to a lot of compute?

I'm not doing full IBD, just to block 120,000. As much as I'd like to benchmark hundreds of full IBD runs, I don't have that kind of compute.

**Comment by mzumsande** [comment]
Does it also appear with `-reindex` (without a second node)?

**Comment by vostrnad** [comment]
I've set up a benchmark that performs a partial IBD and then runs `-reindex`, however the reindexing takes about ten times as long as the IBD, with CPU and disk usage sitting near zero. Same for `-reindex-chainstate`. Is this normal? Even if it is, is it even worth benchmarking for a difference between 27.0rc1 and 26.0? At first glance it seems about as slow.

**Comment by vostrnad** [comment]
Ran the original benchmark again (pre-built binaries on Windows) with only these configuration options:

- `-connect`
- `-datadir`
- `-port`
- `-rpcport`
- `-rpcuser`
- `-rpcpassword`

This time 27.0rc1 was about 5% slower on average than 26.0, still with a much higher variance. Measured around 250 runs of each.

26.0:
![ibd26noconfig](https://github.com/bitcoin/bitcoin/assets/43024885/58e5239c-edd6-426c-84b7-39de5cc69ccd)

27.0rc1:
![ibd27rc1noconfig](https://github.com/bitcoin/bitcoin/assets/43024885/8bf9217e-7e34-4179-8e10-975c17ccf687)

**Comment by vostrnad** [comment]
@maflcko Just to clarify, what didn't regress was the release binary for Linux (which I assume is built with guix, not WSL) running in WSL.

**Comment by fanquake** [comment]
> which I assume is built with guix

All of the release binaries are built using Guix. Windows is produced in Guix using GCC+Mingw-w64. We don't produce any release binaries using WSL or MSVC.

**Comment by achow101** [comment]
I'm not really seeing the same issue on my WIndows machine, although IBD is generally a lot slower

(50 runs each, sync to 120,000)

* On 26.1:
  * Median 359.9265245
  * Mean 374.7166118
  * Std. Dev. 24.05475889010843

* On 27.0rc1:
  * Median 375.675126
  * Mean 375.79323382
  * Std. Dev. 2.7244149066583287

Considering that this is rather difficult to figure out what is wrong, and it seems to not be happening for everyone, I think it would be okay for us to move forward with the 27.0 final release.

**Comment by m3dwards** [comment]
> Did someone with Windows try to enable the benchmarks in guix and compile them, and run them?

I can do

**Comment by achow101** [comment]
> Did someone with Windows try to enable the benchmarks in guix and compile them, and run them?

Yes, I did that. I could not find any benchmark that had a significant difference.

**Comment by m3dwards** [comment]
I did get a bit of variation but hard to know what's important. `BlockAssemblerAddPackageTxns` was about 10-15% slower on `27.0rc1` vs `26.0`. The bench also throws a filesystem error on 27.0rc1 but completes on 26.0.

[Full bench results](`BlockAssemblerAddPackageTxns`)

**Comment by vostrnad** [comment]
After seeing the same high variance in 27.0 and 27.1, it seems to have gone away in 28.0rc1. I'll close the issue for now and will look out for future regressions.

Last set of graphs for your enjoyment:

27.0:
![27.0](https://github.com/user-attachments/assets/01eb27b3-768d-4a18-b356-8a292316dc56)

27.1:
![27.1](https://github.com/user-attachments/assets/52ab5547-56c5-48d3-b4de-22af43a84529)

28.0rc1:
![28.0rc1](https://github.com/user-attachments/assets/080ad441-ad5b-4ca8-af42-dca34319bc48)
