### ISSUE TITLE
depens: bdb build fails on Intel macOS 13.6.6 

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#29792]
### Current behaviour

Building BDB as part of depends fails with a permission denied error for creating a temporary directory. The directory exists after `make` fails. Deleting it and running `make` once more, creates it again and the same error is shown.

Does not happen on my newer Intel macOS 14.4.1 machine.

### Expected behaviour

`make` succeeds 

### Steps to reproduce

```sh
cd depends
make NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
```

### Relevant log output

```
depends % make NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
Fetching db-4.8.30.NC.tar.gz from https://download.oracle.com/berkeley-db
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.7M  100 21.7M    0     0  15.4M      0  0:00:01  0:00:01 --:--:-- 15.4M
/.../bitcoin-depends/depends/work/download/bdb-4.8.30/db-4.8.30.NC.tar.gz.temp: OK
Extracting bdb...
/.../bitcoin-depends/depends/sources/db-4.8.30.NC.tar.gz: OK
Preprocessing bdb...
patching file 'dbinc/atomic.h'
Can't create '/var/folders/qp/bskkps293_v5w198m17h7zrm0000gn/T/patcho2C1xcCJMLh', output is in '/var/folders/qp/bskkps293_v5w198m17h7zrm0000gn/T/patcho2C1xcCJMLh': Permission denied
patch: **** can't create '/var/folders/qp/bskkps293_v5w198m17h7zrm0000gn/T/patcho2C1xcCJMLh': Permission denied
make: *** [/.../bitcoin-depends/depends/work/build/x86_64-apple-darwin22.6.0/bdb/4.8.30-c4f10ceb835/.stamp_preprocessed] Error 2
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@3b12fc7bcd94cf214984911f68612feb468d5404

### Operating system and version

macOS 13.6.6

Apple clang version 15.0.0

### Machine specifications

Intel iMac 2017.

**Comment by Sjors** [comment]
Fixing the legacy wallet for old macOS versions doesn't seem high priority, but `release-notes-empty-template.md` mentions "macOS 11.0+" as the minimum we test on. My iMac from 2017 can't run anything newer than macOS 13.

**Comment by fanquake** [comment]
Are you sure this isn't a local (permissions/filesystem/something else) issue. Works fine for me on macOS 13.6.6.

**Comment by Sjors** [comment]
That's certainly possible, though it happens at different commits, which use different temp directories. And it happens for only with bdb while the other packages build fine. I'll try a reboot and wiping more temp stuff.

**Comment by Sjors** [comment]
patch 2.0-12u11-Apple

**Comment by fanquake** [comment]
Can you produce a more minified set of steps/environment to reproduce. i.e does running the same set of build steps outside of depends also fail?

**Comment by Sjors** [comment]
On todays master 5a5ab1d5446693ee2655860c2f2920bcc3389c83:

```sh
git clean -dfx
cd depends
make NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
```

Immediately fails:
```
Fetching db-4.8.30.NC.tar.gz from https://download.oracle.com/berkeley-db
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.7M  100 21.7M    0     0  19.2M      0  0:00:01  0:00:01 --:--:-- 19.2M
/Volumes/SSD/Dev/bitcoin-depends/depends/work/download/bdb-4.8.30/db-4.8.30.NC.tar.gz.temp: OK
Extracting bdb...
/Volumes/SSD/Dev/bitcoin-depends/depends/sources/db-4.8.30.NC.tar.gz: OK
Preprocessing bdb...
patching file 'dbinc/atomic.h'
Can't create '/var/folders/qp/bskkps293_v5w198m17h7zrm0000gn/T/patcho3S2H7ZTq3e', output is in '/var/folders/qp/bskkps293_v5w198m17h7zrm0000gn/T/patcho3S2H7ZTq3e': Permission denied
patch: **** can't create '/var/folders/qp/bskkps293_v5w198m17h7zrm0000gn/T/patcho3S2H7ZTq3e': Permission denied
make: *** [/Volumes/SSD/Dev/bitcoin-depends/depends/work/build/x86_64-apple-darwin22.6.0/bdb/4.8.30-b84f0e92434/.stamp_preprocessed] Error 2
```

Starting from scratch:

* `make download-osx NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1`
* `cd sources`, `tar -xzf db-4.8.30.NC.tar.gz`, `cd db-4.8.30.NC`
* `patch -p1 < ../../patches/bdb/clang_cxx_11.patch`

That indeed fails the same way. Tried again by deleting `db-4.8.30.NC` and the temp folder (which does not require `sudo`).

I then installed [gpatch](https://formulae.brew.sh/formula/gpatch) 2.7.6 (`brew install gpatch && brew link gpatch --force --overwrite`, open new terminal)

This time it patches all the files:

```
File dbinc/atomic.h is read-only; trying to patch anyway
patching file dbinc/atomic.h
File mp/mp_fget.c is read-only; trying to patch anyway
patching file mp/mp_fget.c
File mp/mp_mvcc.c is read-only; trying to patch anyway
patching file mp/mp_mvcc.c
File mp/mp_region.c is read-only; trying to patch anyway
patching file mp/mp_region.c
File mutex/mut_method.c is read-only; trying to patch anyway
patching file mutex/mut_method.c
File mutex/mut_tas.c is read-only; trying to patch anyway
patching file mutex/mut_tas.c
```

And indeed `make depends` works once this is in place, albeit with a flood of warnings:

```
../dist/./../txn/txn_util.c:360:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
__txn_record_fname(env, txn, fname)
```

Installing gnu patch seems like an acceptable workaround, but if it's silently ignoring failed patch attempts because something is read-only that's not good.

On the newer macOS machine the patch command (Apple built in) does not throw warnings:

```
 patch -p1 < ../../patches/bdb/clang_cxx_11.patch
patching file 'dbinc/atomic.h'
patching file 'mp/mp_fget.c'
patching file 'mp/mp_mvcc.c'
patching file 'mp/mp_region.c'
patching file 'mutex/mut_method.c'
patching file 'mutex/mut_tas.c'
```

Turns out these files are indeed read-only, but that's the case on both versions of macOS:

```
% ls -al dbinc/atomic.h
-r--r--r--  1 sjors  staff  6583 12 apr  2010 dbinc/atomic.h
```

**Comment by Sjors** [comment]
I'm still running the test suite to see if it's not broken. The machine is quite slow.

At minimum we should add gnu patch to the list of requirements / recommendations, at least for macOS < 14.

**Comment by laanwj** [comment]
Looks like it's resolved? As a rare issue with a dependency that's going away anyhow, i think this can be closed.

**Comment by Sjors** [comment]
I wiped the disk and reinstalled macOS 13.6.6. Still getting the permission denied error.

I narrowed it down further: this only happens when I clone the repo on my external SSD drive, not when it's on the built in disk.

```
Preprocessing bdb...
patching file 'dbinc/atomic.h'
Can't create '/var/folders/6c/n_bj8h8s0212j2tdtk_c_93m0000gn/T/patchogFOtRafNrn', output is in '/var/folders/6c/n_bj8h8s0212j2tdtk_c_93m0000gn/T/patchogFOtRafNrn': Permission denied
patch: **** can't create '/var/folders/6c/n_bj8h8s0212j2tdtk_c_93m0000gn/T/patchogFOtRafNrn': Permission denied
make: *** [/Volumes/SSD/test/bitcoin/depends/work/build/x86_64-apple-darwin22.6.0/bdb/4.8.30-0de9a3a86cb/.stamp_preprocessed] Error 2
```

* `/var` is on the internal disk
* `/Volumes/SSD` is the external SSD drive (encrypted APFS)

I can always debug it further if we encounter it in _another_ dependency.

**Comment by Sjors** [comment]
It seems to:

```
mkdir /tmp/test

% TMPDIR=/tmp/test  make NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_UPNP=1 NO_NATPMP=1 NO_USDT=1
Preprocessing bdb...
patching file 'dbinc/atomic.h'
Can't create '/tmp/test/patchoSHQPQFIlmq', output is in '/tmp/test/patchoSHQPQFIlmq': Permission denied
patch: **** can't create '/tmp/test/patchoSHQPQFIlmq': Permission denied
make: *** [/Volumes/SSD/test/bitcoin/depends/work/build/x86_64-apple-darwin22.6.0/bdb/4.8.30-0de9a3a86cb/.stamp_preprocessed] Error 2
```

It seems to want the temp dir to live on the same volume:

```
TMPDIR=/Volumes/SSD/temp/test  make ...
```

^ works
