### ISSUE TITLE
ci: Enable bpfcc-tools

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#29804]
Two recommended pull requests:

* Revert fac012c7262f036e9b6f5800e57dcd63870a871c
* Wait for 24.04 GHA image, Move the task over to that image

**Comment by hebasto** [comment]
> > Wait for 24.04 GHA image, Move the task over to that image
> 
> Still waiting for it to appear here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

The wait is over: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240430.1

**Comment by 0xB10C** [comment]
https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/

**Comment by m3dwards** [comment]
> Is someone interested in moving the asan task over to GHA now?

Happy to look at this early next week.

**Comment by m3dwards** [comment]
@maflcko WIP on moving ASAN task over to GHA: https://github.com/m3dwards/bitcoin/actions/runs/9178831587/job/25239590853
