### ISSUE TITLE
`WalletCreate{Encrypted/Plain}` benchmark crash on Windows

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#29816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

After modifying the guix build script for 27.0rc1 to produce the benchmark binary, when `bench_bitcoin` is run on Windows, it crashes on the `WalletCreateEncrypted` and `WalletCreatePlain` benchmarks with

```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot remove all: Broken pipe [C:\Users\ava\AppData\Local\Temp\test_common_Bitcoin Core\3429246d6bc3edb33b654eaa193f00685cbc45e5b8e31d04b784a4139314cbf9] [C:\Users\ava\AppData\Local\Temp\test_common_Bitcoin Core\3429246d6bc3edb33b654eaa193f00685cbc45e5b8e31d04b784a4139314cbf9\test_wallet_4003727542\wallet.dat]
```

I have not tested with a MSVC build.

### Expected behaviour

Shouldn't crash

### Steps to reproduce

1. Checkout 27.0rc1
2. Remove `--disable-bench` from guix's configure
3. Do guix build
4. Extract `bench_bitcoin.exe`
5. `bench_bitcoin.exe -filter="WalletCreateEncrypted"` and/or `bench_bitcoin.exe -filter="WalletCreatePlain"`
6. Crash

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

27.0rc1

### Operating system and version

Windows 10

**Comment by hebasto** [comment]
Does your Windows user have a OS permission to create symbolic links?

**Comment by hebasto** [comment]
It seems the same issue as I [noticed](https://github.com/bitcoin/bitcoin/pull/29773#issuecomment-2028619063) in https://github.com/bitcoin/bitcoin/pull/29773.

From @sipsorcery's [comment](https://github.com/bitcoin/bitcoin/pull/29773#issuecomment-2040668052):
> only guessing but I've always found Windows fairly average at releasing file and socket handles. Maybe that's the cause of the test failure rather than anything code related.
>
> In my other life I work with SIP (telecoms protocol) with lots of socket handles flying around. If it's only for testing then I generally just add a 5 second wait and try again for handle in use errors.

**Comment by hebasto** [comment]
I wonder if SQLite bothers to call [`CloseHandle()`](https://learn.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-closehandle) on Windows?

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$17.74 USD** for a successful merge request of this issue via contributions such as **19.500 MATIC** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)

**Comment by michaelwklein** [comment]
Hi @hebasto, @achow101 thanks for moderating the repository. @joinfuel is a project that assigns rewards to GitHub issues, developers simply to connect their GitHub via joinfuel.io to obtain the rewards. Is there someone we can talk to in Developer relations to have these comments approved? The community and the project itself and assign rewards to GitHub issues to promote open source projects.

**Comment by hebasto** [comment]
cc @furszy as an author of https://github.com/bitcoin/bitcoin/pull/28894.

**Comment by furszy** [comment]
@hebasto, #30122

**Comment by hebasto** [comment]
My research shows that https://github.com/bitcoin/bitcoin/blob/dd42a5ddea6a72e1e9cad54f8352c76b0b701973/src/bench/wallet_create.cpp#L43-L44 does not trigger the `shared_ptr<CWallet>` deleter, which is `ReleaseWallet()`, because `wallet.use_count() == 3`.

**Comment by furszy** [comment]
> My research shows that
> 
> https://github.com/bitcoin/bitcoin/blob/dd42a5ddea6a72e1e9cad54f8352c76b0b701973/src/bench/wallet_create.cpp#L43-L44
> 
> does not trigger the `shared_ptr<CWallet>` deleter, which is `ReleaseWallet()`, because `wallet.use_count() == 3`.

Great 👍🏼 . #30122 releases the wallet too.

**Comment by hebasto** [comment]
Can be closed as fixed by https://github.com/bitcoin/bitcoin/pull/30122.
