### ISSUE TITLE
Where is the transactionAddedToMempool function ultimately interpreted

### ISSUE THREAD

**Issue by Wang-jiong-han** [bitcoin/bitcoin#29829]
### Motivation

when  I read and check the code of AcceptSingleTransaction function,I noticed that the transactionAddedToMempool function is not being constructed properly; existing code related to the transactionAddedToMempool function is either overloaded or repeatedly called. I haven't found where this functionality is ultimately interpreted and executed。
Is it that I'm missing some part of the code, or that some third-party library is being called? I hope to get an answer from the developers

### Useful Skills

* Compiling Bitcoin Core from source
* Running the C++ unit tests and the Python functional tests
* ...

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by glozow** [comment]
This seems like a misunderstanding of how `CValidationInterface` works? https://github.com/bitcoin/bitcoin/blob/master/src/validationinterface.h. Clients of that interface implement `transactionAddedToMempool`.

Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base.

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on Libera Chat, or one of the Bitcoin subreddits, or any other place that you feel is well suited.
