### ISSUE TITLE
Release Schedule for 28.0

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#29891]
Here is a proposed release schedule for `v28.0`, the next major release of Bitcoin Core. The dates are set to target a release in early October as was previously discussed.

## 2024-08-01 :heavy_check_mark:
- Open Transifex translations for `v28.0`
- Soft translation string freeze (no large or non-critical string changes until release)
- Finalize and close translations for `v26.0`

## 2024-08-12 :heavy_check_mark:
- Feature freeze (bug fixes only until release)
- Translation string freeze (no more source language changes until release)

## 2024-08-27 :heavy_check_mark: :
- Anything needed before branch-off, see https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md
- Split off `28.x` branch from `master`
- Start RC cycle, tag and release `v28.0rc1`
- Start merging for `29.x` on `master` branch

## 2024-09-30 :heavy_check_mark: : 
- Tag `v28.0` (aim).

If any specific dates are a problem for you, please leave a comment.

**Comment by Sapo07** [comment]
Pago de servicios

**Comment by Sapo07** [comment]
Calendario de lanzamiento para 28.0 #29891 aceptable estable aplica

**Comment by Ridvan8899** [comment]
[]()ننثخق

**Comment by yener35** [comment]
****

**Comment by hebasto** [comment]
> ## 2024-08-01 🚧
> 
>    * Open Transifex translations for `v28.0`
> 
>    * Soft translation string freeze (no large or non-critical string changes until release)
> 
>    * Finalize and close translations for `v26.0`

Done.

See the announcement on the Transifex: https://app.transifex.com/bitcoin/communication/d:df052ee8-69d4-4739-a529-ba835673a9f0/

**Comment by Albroheem** [comment]
tar xf bitcoin-osx-unsigned.tar.gz
./detached-sig-create.sh /path/to/codesign.p12
Enter the keychain password and authorize the signature
signature-osx.tar.gz will be created

**Comment by fanquake** [comment]
RC1 test binaries: https://bitcoincore.org/bin/bitcoin-core-28.0/test.rc1/.

**Comment by Chrcelalles** [comment]
Hola saludos desde Argentina
