### ISSUE TITLE
Peers can cause incorrect warning about time and date

### ISSUE THREAD

**Issue by kuzetsa** [bitcoin/bitcoin#2990]
![bitcoin-0 8 5_nagbug](https://f.cloud.github.com/assets/2875851/1138715/02c77de0-1c7c-11e3-83c4-055f97ba78ea.png)

Time is set correctly. System time is accurate to within 250ms of several stratum 2 / stratum 3 NTP servers.

(Local NY timezone selected under windows control panel, hardware clock is NOT set to UTC because that's not how NT 6.1, 6.0, 5.1, 5.0, 4.0 or any version of windows handles such things)

This bug probably also affects other versions of windows as well.

Edit @laanwj: renamed to make clear this is not a problem with timezone detection or windows

**Comment by MarcoFalke** [comment]
Is this even a bug on our side? The only thing I see that can be done is to change the warning message http://bitcoinstats.com/irc/bitcoin-dev/logs/2014/07/14#l1405352477.0

**Comment by kuzetsa** [comment]
I don't actually know if this is an ongoing issue, since I haven't used bitcoin in a long time (*been something like 2 years now*)

If someone has additional information about the issue or knows if there was a change made to the behavior, feel free to update or close #2990 as appropriate. I don't have any relevant/recent knowledge, regardless of what happens here.
