### ISSUE TITLE
help i think my core is hacked

### ISSUE THREAD

**Issue by HaSan1y** [bitcoin/bitcoin#29944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

https://explorer.btc.com/btc/transaction/c5069dd52612dd07cfff6a2c587356497a2f8e7489923376a92420850fe27d09

i only did an 0.01 transfer to freebitco.in but somehow it puts an additional 0.027 btc transfer to an unintend address in there how can i cancel it pls help fast

### Expected behaviour

https://explorer.btc.com/btc/transaction/c5069dd52612dd07cfff6a2c587356497a2f8e7489923376a92420850fe27d09

i only did an 0.01 transfer to freebitco.in but somehow it puts an additional 0.027 btc transfer to an unintend address in there how can i cancel it pls help fast

### Steps to reproduce

bitcoin core send balance 0.01

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

v25.0.0

### Operating system and version

windows 11

**Comment by pinheadmz** [comment]
This is your change output. Look for more information on https://bitcoin.stackexchange.com

**Comment by HaSan1y** [comment]
> This is your change output. Look for more information on https://bitcoin.stackexchange.com
i dont understand? what do you mean with 'change output'?? what do you mean with look for more information?
elaborate please?
 anyway who are you? did you even read my problem? 
i know what is inside that link https://explorer.btc.com/btc/transaction/c5069dd52612dd07cfff6a2c587356497a2f8e7489923376a92420850fe27d09 
im saying something is wrong with the transaction. did you perheps programm to steal money, is this your and your friends doing?and now you guys try to hide it?
