### ISSUE TITLE
"Migrate Wallet" is unclear to translators

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#29979]
Going through translations, I'm seeing things that suggest "migration" is being misinterpreted in the sense of animals migrating (moving/relocating). We could clarify with translator comments (assuming translators actually see them), but that won't help if non-native English speakers are using Bitcoin Core in English, so maybe a better approach is to come up with another word for this?

**Comment by laanwj** [comment]
A better user-facing word would be just "upgrade wallet"--but for technical reasons we use a different word, as we already had a concept of upgrading inside the wallet format.

**Comment by willcl-ark** [comment]
Some other suggestions, none I'm particularly favourable towards vs "migration" from an English standpoint tbh:

- transition
- convertion
- transformation

Of these IMO only "transition" is likely to have any chance at being _more_ clear (than "migration" apparently is) when translating into other languages.

**Comment by flack** [comment]
FWIW "migrate" has a definition as a computer (or information system) term in common dictionaries, e.g.:

https://www.merriam-webster.com/dictionary/migrate

https://www.dictionary.com/browse/migrate

It's also not a Bitcoin-specific invention, but used in many projects (although probably not so often in end user communication). Could it be that those translators simply used some machine translation that was missing the context?

That being said, "upgrade wallet" would definitely be easier to understand.

**Comment by achow101** [comment]
Migrate is a term that is used in other computer related contexts, e.g. "database migration". It was chosen because of the process's similarities to a database migration, and particularly in a way similar to how Django [uses it](https://docs.djangoproject.com/en/5.0/topics/migrations/). Since Django has similar usage of the term with translations, perhaps we can point translators to there?

While "upgrade" was considered, we're already using that to mean something else, and I don't think overloading that term would be helpful.

**Comment by willcl-ark** [comment]
Can we close this now then? We're not going to find a more appropriate word than "migrate" for this context, and it seems like there's therefore no action to be taken here.

**Comment by willcl-ark** [comment]
Oh ok, great! I wasn't aware that we could add context like that.

**Comment by laanwj** [comment]
> Can we close this now then? We're not going to find a more appropriate word than "migrate" for this context, and it seems like there's therefore no action to be taken here.

Agree, i don't think using any another word is a substitute for good explanation in this case, and changing it at this point after having used 'migration' for years would only add to the confusion.
