### ISSUE TITLE
depends: Cross-compiling `qt` for `arm-linux-gnueabihf` fails

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#29980]
On Ubuntu 24.04 with glibc 2.39:
```
compiling ../3rdparty/zlib/src/gzclose.c
In file included from /usr/arm-linux-gnueabihf/include/features.h:394,
                 from /usr/arm-linux-gnueabihf/include/bits/libc-header-start.h:33,
                 from /usr/arm-linux-gnueabihf/include/stdio.h:28,
                 from ../3rdparty/zlib/src/gzguts.h:40,
                 from ../3rdparty/zlib/src/gzclose.c:6:
/usr/arm-linux-gnueabihf/include/features-time64.h:26:5: error: #error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
   26 | #   error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
      |     ^~~~~
```

Some similar issues in https://bugreports.qt.io suggest to switch from the builtin `zlib` to a system one. But that doesn't look like an option for us.

**Comment by laanwj** [comment]
This is caused by the 32 to 64 bit time_t transition (for the 2038 epoch problem). It will affect all 32-bit systems.

I would guess solving this requires a minimal patch to the zlib inside Qt to make the right combination of defines. i'll take a look at it.
