### ISSUE TITLE
Objdump can't parse our Linux debug information

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#30016]
Upstream issue: https://sourceware.org/bugzilla/show_bug.cgi?id=31692

The debug information in the shipped `.dbg` artifacts seems to be unusable for objdump. The `.debug_info` section is corrupt:
```sh
$ tar -zxvf bitcoin-27.0-x86_64-linux-gnu-debug.tar.gz
$ objdump -Wi bitcoin-27.0/bin/bitcoin-cli.dbg

Section '.debug_info' has an invalid size: 0.

bitcoin-27.0/bin/bitcoin-cli.dbg:     file format elf64-x86-64

Section '.debug_info' has an invalid size: 0.
```
i've checked various Linux architectures (at least x86_64, ARM, RISC-V) and the same issue exists there. Interestingly, the Windows build is unaffected. Maybe because of a different gcc/binutils? Builds outside guix seem unaffected.

My first thought is that something goes wrong while splitting the debug symbols. However, the unsplitted binaries suffer from the same problem:
```sh
$ objdump -Wi guix-build-27.0/distsrc-27.0-x86_64-linux-gnu/src/bitcoind

Section '.debug_info' has an invalid size: 0
```

This issue affects at least release `27.0` and current master.

Edit: Looks like there is a `.debug_info` section in the files. `objdump -s -j .debug_info bitcoin-27.0/bin/bitcoind.dbg` shows contents, so it's not really size 0. But it can't be parsed somehow.

**Comment by laanwj** [comment]
Okay, may be a `objdump` bug actually? 

`readelf -wi` (which should be equivalent to `objdump -Wi`) parses the same section fine. So does `gdb` it seems? 

(FWIW i did try various versions of `objdump` before reporting this)

**Comment by laanwj** [comment]
Closing for now.

**Comment by laanwj** [comment]
Reopening with more accurate title (phew).

Filed upstream issue: https://sourceware.org/bugzilla/show_bug.cgi?id=31692

**Comment by fanquake** [comment]
> Interestingly, the Windows build is unaffected. Maybe because of a different gcc/binutils?

This is probably because the Windows Binutils is configured without support for compressed debug sections, as it was, iirc, causing other windows build issues.

**Comment by laanwj** [comment]
> This is probably because the Windows Binutils is configured without support for compressed debug sections, as it was, iirc, causing other windows build issues.

Right, that makes sense. DWARF in PE binaires is a quite peculiar concept in the first place--heck, GNU even has its own way to encode the long section names needed: lief-project/LIEF#1043. i'm not surprised it's not set up to handle compressed sections.
