### ISSUE TITLE
configure error on OSX: No working boost sleep implementation found

### ISSUE THREAD

**Issue by BugAndNewsReporter** [bitcoin/bitcoin#3003]
Trying to compile git head on OSX 10.7.5 with ```./configure --without-qt --disable-tests --disable-debug```, it fails with:

    checking whether the Boost::Chrono library is available... yes
    checking for exit in -lboost_chrono-mt... yes
    configure: error: No working boost sleep implementation found

I have boost installed with MacPorts:

    > port installed | grep boost
    boost @1.54.0_0+no_single+no_static+python27 (active)

**Comment by fanquake** [comment]
@laanwj Fixes for this were pulled. Discussion tailed away from OSX towards Ubuntu and #4704 should have taken care of that. /close

**Comment by Azulan** [comment]
Just got this error on Elementary OS using the 10rc3 source tarball. Installing libboost-all-dev to see if it fixes it.

**Comment by Azulan** [comment]
It did.

**Comment by pdxrod** [comment]
Having done

git clone https://github.com/bitcoin/bitcoin.git

cd bitcoin

and 

brew install https://raw.github.com/mxcl/homebrew/master/Library/Formula/berkeley-db4.rb -–without-java 

then 

./autogen.sh

I found

brew install boost 

enabled 

./configure 

to finish successfully.
