### ISSUE TITLE
build: Unaligned libsecp256k1 flags in debug builds

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#30055]
When configured with `--enable-debug`, C++ code compiles with `-O0 -g3`.

However, libsecp256k1 code compiles with `-g -O2`.

**Comment by theuni** [comment]
I'm not sure this is a problem? It's hard to imagine a use-case where we'd want to be debugging Core with an un-optimized secp.

**Comment by fanquake** [comment]
What's the status of this? Can you explain the use-case where this is an issue for you, or the other motivation?
