### ISSUE TITLE
libxcb-xinerama0 Library required by bitcoin-qt

### ISSUE THREAD

**Issue by nimrare** [bitcoin/bitcoin#30061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I installed bitcoin core 26.1 on a Raspberry 5 (ARM Architecture) running Ubuntu 23.1. Upon running bitcoin-qt, I got the error that the library libxcb-xinerama0 is required but not installed.

It's easily fixed by installing it from the repositories (apt install libxcb-xinerama0), however, for a security conscious person this is a bit unsatisfying. Is there a reason this library is not packaged with the bitcoin core binaries?

After all you go through the hassle of verifying and cross checking all signatures of the binaries and then you have to install a third party untrusted library to run everything.

### Expected behaviour

Bitcoin core comes packaged with all required libraries.

### Steps to reproduce

See current behavior.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

26.1

### Operating system and version

Ubuntu 23.1 

### Machine specifications

Raspberry 5 ARM

**Comment by hebasto** [comment]
> It's easily fixed by installing it from the repositories (apt install libxcb-xinerama0), however, for a security conscious person this is a bit unsatisfying.

It is expected: https://github.com/bitcoin/bitcoin/blob/43a66c55ec8770cf7c21112aac9b997f3f2fb704/contrib/devtools/symbol-check.py#L125

**Comment by laanwj** [comment]
> @laanwj Does https://github.com/bitcoin/bitcoin/pull/29923 address this?

Potentially it could make the dependency on xcb-xinerama optional. There's only a few functions used from that library, for a specific purpose (multiple monitor support), if the library can't be loaded, it can be assumed that this functionality isn't needed. This does mean patching Qt though.

)i've handled the xcb/wayland switch in that way--if X libraries can't be found, don't exit, but fail loading the XCB platform and go on to the next one)

**Comment by nimrare** [comment]
@sipa @laanwj Okay, thank you for your response on this. I see your points and also agree that btc core can't and shouldn't deal with os related graphics peculiarities. Just from a UX/security perspective, I was a bit surprised about it when first encountered. Maybe it could be made optional at some point or a more verbose error message can be printed. In any case, no big issue. I'll close this!

**Comment by libreisaac** [comment]
> Okay, thank you for your response on this. I see your points and also agree that btc core can't and shouldn't deal with os related graphics peculiarities. Just from a UX/security perspective, I was a bit surprised about it when first encountered. Maybe it could be made optional at some point or a more verbose error message can be printed. In any case, no big issue. I'll close this!

If you're concerned about trusting binaries installed by your OS' package manager, consider Gentoo. But fundamentally, unless you bootstrap your own C compiler from assembly, you're going to have to trust at least a compiler binary and the env to execute it as your root.
