### ISSUE TITLE
Wrong block mined time in testnet

### ISSUE THREAD

**Issue by jplix7k** [bitcoin/bitcoin#30121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Currently, all block mined time in testnet could be about 1 hour earlier than current time.
 
<img width="1285" alt="testnet" src="https://github.com/bitcoin/bitcoin/assets/51077262/4df52a40-7b45-4a4d-8535-f1564e9a8705">
link: https://blockexplorer.one/bitcoin/testnet

Timestamp in UpdateTip is wrong. 
```
│ app-generic 2024-05-16T06:57:48Z Saw new header hash=000000000000000ba2e0919b2ab27d045c41bd4e6115667c2ef453e405db01da height=2815696             │
│ app-generic 2024-05-16T06:57:48Z [net] Saw new cmpctblock header hash=000000000000000ba2e0919b2ab27d045c41bd4e6115667c2ef453e405db01da peer=11   │
│ app-generic 2024-05-16T06:57:48Z UpdateTip: new best=000000000000000ba2e0919b2ab27d045c41bd4e6115667c2ef453e405db01da height=2815696 version=0x2 │
│ 235c000 log2_work=75.782354 tx=135221647 date='2024-05-16T07:51:39Z' progress=1.000000 cache=209.9MiB(1241814txo)
```

Looks like wrong stamp is derived from getblocktemplate response? 'curtime' and 'mintime' is always quite earlier than current time.  

### Expected behaviour

Block mined time should be close to current time. 

### Steps to reproduce

Execute `bitcoin-cli getblocktemplate '{"rules": ["segwit"]}'`, check 'curtime' and 'mintime'. 

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

v25.0

### Operating system and version

Ubuntu18

**Comment by achow101** [comment]
This is expected behavior. `UpdateTip` logs the timestamp stored in the block header, which can be in the future and not actually match the time the block was mined. Testnet miners are known to be messing around and doing weird things like this.
