### ISSUE TITLE
dumpprivkey error

### ISSUE THREAD

**Issue by ygcool** [bitcoin/bitcoin#30129]
bitcoin-core version:27.0

execute:

`bitcoin-cli createwallet "wallet1" false false pass`

`bitcoin-cli getnewaddress`

`bitcoin-cli walletpassphrase pass 100`

`bitcoin-cli dumpprivkey "address"`

dumpprivkey Return error:

```
error code: -4
error message:
Only legacy wallets are supported by this command
```

Is there any solution to export the private key of the address?
If I must use dumpprivkey which version of bitcoin core should I use?

thanks

**Comment by edilmedeiros** [comment]
Newer version of bitcoin core use [descriptor wallets](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md).

You can see them using:
```
bitcoin-cli listdescriptors true
```

The `true` argument mean to export the private descriptors, the equivalent of private keys. 

I usually use the tool `jq` to extract them to an environment variable like so:
```
DESCRIPTORS=$(bitcoin-cli listdescriptors true | jq -r .descriptors)
```

I import the descriptors to my wallet with:
```
bitcoin-cli importdescriptors "$DESCRIPTORS"
```

**Comment by ygcool** [comment]
@edilmedeiros Hi, I tried and it still doesn't work, which version of bitcoin core still works with dumpprivkey?

**Comment by edilmedeiros** [comment]
V27 works with `dumpprivkey`.

The problem is that you are creating a newer descriptor wallet and are trying to use an rpc which is compatible with legacy wallets only.

Can you be more specific about what you tried?

**Comment by achow101** [comment]
As the error message says, your wallet is not compatible with the `dumpprivkey` command. @edilmedeiros has already laid out your alternatives, but there is no way to make your specific wallet work with `dumpprivkey`.

**Comment by ygcool** [comment]
thank.
Solved it:

`bitcoind -deprecatedrpc=create_bdb -daemon`

`bitcoin-cli -named createwallet "walletname" descriptors=false`

`bitcoin-cli getnewaddress`

`bitcoin-cli dumpprivkey "address"`
