### ISSUE TITLE
VM disk for OS (Debian 12.x) gets smaller and smaller - NOT the same disk i used for .bitdoin data directory which is mounted on another disk

### ISSUE THREAD

**Issue by kosuodhmwa** [bitcoin/bitcoin#30191]
I ask me why? Now i added the txindex=1 option to bitcoin.conf file and it's the OS disk that gets smaller and smaller - NOT the disk where .bitcoin data directory is located... that's very, very confusing i.m.o

B: = bitcoin data disk where .bitcoin data directory is
I: = disk where the virtualbox bitcoind VM (Debian 12.x) is.

![image](https://github.com/bitcoin/bitcoin/assets/24782840/baf29916-9c8b-45ba-8759-91026a2839f8)

**Comment by kosuodhmwa** [comment]
maybe it saves tons of logs in /var/ log ??

**Comment by laanwj** [comment]
> maybe it saves tons of logs in /var/ log ??

Bitcoin core itself doesn't write anything to `/var` or anywhere but the data directory. Of course, it may be that some other process is doing that. You'd want to figure out what files use the disk space. i don't know what's a good tool for that in windows but in Linux you'd typically use  `du -h`.

**Comment by kosuodhmwa** [comment]
the bitcoin application directory seems to be also very big... now i'm confused, i was thinking the bitcoind saves all its volatile data in ~/.bitcoin [data] - not in ~/bitcoin [application]

![image](https://github.com/bitcoin/bitcoin/assets/24782840/1b79dc79-07a0-492d-af05-cc3a79c6abe5)

**Comment by kosuodhmwa** [comment]
Here the drive used for ~/.bitcoin (data) symlink


/dev/sda1      1054729716 650342244 350736480   65% /mnt/btcdrive

**Comment by kosuodhmwa** [comment]
Thank you very much - will look on it ASAP

**Comment by kosuodhmwa** [comment]
(Now the VM was completely fu**ed up, because 0.0gb left)
