### ISSUE TITLE
Make Transport independent of CNetMessage and CSerializedNetMsg

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#30209]
Currently `class Transport` uses `CNetMessage` in one place:

https://github.com/bitcoin/bitcoin/blob/62f7f59ff495fbcbfc10c25e97bb0dc032647abf/src/net.h#L278-L285

And `CSerializedNetMsg` here:

https://github.com/bitcoin/bitcoin/blob/62f7f59ff495fbcbfc10c25e97bb0dc032647abf/src/net.h#L287-L295

This creates a problem in my Stratum v2 Template Provider implementation in #29432 which introduces `class Sv2Transport : Transport`. Because the sv2 noise protocol (#29346) is very similar to BIP324 I simply copied `V2Transport` and modified the state machine a little bit. The test and fuzz code was also very reusable.

But the above two methods don't fit because of their use of `CNetMessage` and `CSerializedNetMsg`. Stratum v2 messages (`Sv2NetMsg` in #29432) don't inherit from `CNetMessage` and I don't think they should.

So I'd like to refactor `Transport` to just return (decrypted) bytes and have the caller interpret them (as `CNetMessage` or `Sv2NetMsg`).

Additionally I'm not sure what to do with the `std::chrono::microseconds time, bool& reject_message` arguments. So far I don't use them in `Sv2Transport`.

* `reject_message`: in v1 the transport sets this if the checksum fails. In v2 it's used for the v1 fallback, but also for unrecognized msg types. This can be done by the caller after my proposed refactor, so the argument can go away.
* `time`: this is passed into `GetReceivedMessage` by the caller and used to set `msg.m_time = time;`, so can also go away.

From IRC I understand @sipa had some ideas on how to tackle this. I can take a stab at it myself, but if someone else does it I'm happy to review.

**Comment by Sjors** [comment]
Easier said than done... very rough draft in #30213

**Comment by Sjors** [comment]
Perhaps a third approach is to shoehorn `Sv2MsgType` into `CNetMessage`. I haven't tried that yet. In terms of elegance it's probably no worse than option (1) above.

**Comment by Sjors** [comment]
By "command" you mean "m_type"?

```cpp
class CNetMessage
{
public:
    DataStream m_recv;                   //!< received message data
    std::chrono::microseconds m_time{0}; //!< time of message receipt
    uint32_t m_message_size{0};          //!< size of the payload
    uint32_t m_raw_message_size{0};      //!< used wire size of the message (including header/checksum)
    std::string m_type;

    ...
};
```

`Sv2Transport` could set `m_type` to the empty string. The Template Provider can construct an `Sv2NetMsg` from a serialized `Sv2NetHeader` and `std::vector<std::uint8_t> payload`. Since the header is fixed length, `m_recv` can have both header and payload.

**Comment by rocholojavinar** [comment]
![IMG](https://img.youtube.com/vi/6m5L856DsdU/maxresdefault.jpg)
![IMG](https://img.youtube.com/vi/CyD8hAjj8L8/maxresdefault.jpg)
![IMG](https://img.youtube.com/vi/yHU6g3-35IU/maxresdefault.jpg)
![IMG](https://img.youtube.com/vi/fzNMd3Tu1Zw/maxresdefault.jpg)
![IMG](https://img.youtube.com/vi/1pOBa1Cf1k8/maxresdefault.jpg)

**Comment by vasild** [comment]
Concept ACK

**Comment by Sjors** [comment]
This is no longer a concern with the sidecar IPC approach for Stratum v2 Template Provider, see https://github.com/Sjors/bitcoin/pull/48.
