### ISSUE TITLE
fuzz: timeout/oom in package_rbf

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30241]
I stumbled upon a fuzz seed that oom'ed in CI for `package_rbf`. Since the seed appears to be too big to paste, I provide the output of `$ base64 95a3b1b42d43ac7190f24ff116b2cd6515e7a566 > /tmp/base64-95a3b1b4-oom.txt`:
[base64-95a3b1b4-oom.txt](https://github.com/user-attachments/files/15685350/base64-95a3b1b4-oom.txt)

If the prior format is unsatisfactory, the problematic seed `95a3b1b42d43ac7190f24ff116b2cd6515e7a566` is also in this commit to qa-assets: https://github.com/bitcoin-core/qa-assets/pull/186/commits/8d624b44419f46bcb5117baa16047dbf4bdb339f

_Originally posted by @murchandamus in https://github.com/bitcoin/bitcoin/issues/28812#issuecomment-2153274374_

**Comment by instagibbs** [comment]
opened https://github.com/bitcoin/bitcoin/pull/30300, I think this should resolve it?
