### ISSUE TITLE
automake script error building 32 bit depends libevent-2.1.12

### ISSUE THREAD

**Issue by techy2** [bitcoin/bitcoin#30311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

building depends for native platform
configure fails to find usable gcc version because of -V -qversion, etc... confusion
this looks like a scripting error

### Expected behaviour

finds current version of gcc on this host of 10.5.0

### Steps to reproduce

on focal32 host
git clone https://github.com/bitcoin/bitcoin
cd bitcoin
git checkout v27.1
cd depends
make

### Relevant log output

[config.log](https://github.com/user-attachments/files/15906540/config.log)

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v27.1

### Operating system and version

focal32

### Machine specifications

ubuntu focal32
intel Atom N280
2 gigs ram
1T disk
autoconf	2.69
automake	1.16.1
gcc		10.5.0
python3		3.9.5

**Comment by techy2** [comment]
Did all that, does not make any difference
executing this command line for depends
make HOST=i686-pc-linux-gnu -j8

however, config.log says this, see attached
configure:3745: $? = 0
configure:3734: gcc -m32 -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.3.0-1ubuntu1~18.04~1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-xgJY7J/gcc-10-10.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-xgJY7J/gcc-10-10.3.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu

Note last line, all say x86_64-linux-gnu
config.log attached 
[config.log](https://github.com/user-attachments/files/15945514/config.log)

The error remains the same, can not determine version of compiler

**Comment by Andredreyer1** [comment]
Thanks

**Comment by techy2** [comment]
Last run was attempt at cross compile on ubuntu 18.04 64 bit host attempting cross compile
Xeon X5690
192 gigs memory
1 T disk
autoconf 2.69
automake 1.16.1
gcc 10.3.0
python3 3.6.9

seems like a no-win situation, X64 won't do the 32 bit build and the focal-32 system gcc-10.5 can not find 'cc1'   gcc -print-prog-name=cc1 does not provide a path

suggestions?

**Comment by techy2** [comment]
taking a look at focal32 expected path for cc1, it is not there. Installed gcc 10.5.0 once again and succeeded in populating /usr/lib/gcc/i686-linux-gnu/10/cc1
works now on focal32

However the failure to cross compile on the x64 platform is an issue

 --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
from the config log does not look right to me for an 1686 cross build

**Comment by hebasto** [comment]
@techy2 

> taking a look at focal32 expected path for cc1, it is not there. Installed gcc 10.5.0 once again and succeeded in populating /usr/lib/gcc/i686-linux-gnu/10/cc1 works now on focal32
> 
> However the failure to cross compile on the x64 platform is an issue
> 
> --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu from the config log does not look right to me for an 1686 cross build

Do I understand correctly that you has resolved the initial issue mentioned in the top comment and faced another one?

If so, please close this issue and open a new one.

**Comment by techy2** [comment]
Ok, will open new issue cross compiling X64 => i686 32 bit
