### ISSUE TITLE
I want to set up a node quickly, do you have a snapshot？

### ISSUE THREAD

**Issue by dg123lzk** [bitcoin/bitcoin#30382]
I want to set up a node quickly, do you have a snapshot？

**Comment by willcl-ark** [comment]
Hi @dg123lzk 

General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the `#bitcoin` IRC channel on the [Libera Chat](https://libera.chat/) network.

For proposed protocol changes you can post to the [bitcoindev mailing list](https://groups.google.com/g/bitcoindev) or the [Delving Bitcoin](https://delvingbitcoin.org/) Discorse forum.

For general bitcoin discussion you can try [bitcointalk](bitcointalk.org) or [reddit.com/r/bitcoin](reddit.com/r/bitcoin).

There are some **unofficial, unrelated to this project** assumeutxo snapshots on https://bitcoin-snapshots.jaonoctus.dev/
Make sure you understand how [assumeutxo](https://github.com/bitcoin/bitcoin/blob/master/doc/design/assumeutxo.md) works before using these!
