### ISSUE TITLE
scriptPubKey no address

### ISSUE THREAD

**Issue by dg123lzk** [bitcoin/bitcoin#30450]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

There is no scriptPubKey in the transaction vin, how can I get the address of the transaction vin

{
  "txid": "061b6336b2f7720193b389e2fe1a7f1e64eff8ff601a79665713a7104ec902fd",
  "hash": "b2053bb14c98c16aecffa26999974041daffcffbd02d099a477893df807de82b",
  "version": 2,
  "size": 247,
  "vsize": 166,
  "weight": 661,
  "locktime": 560008,
  "vin": [
    {
      "txid": "724a6b3efd099953b62ae30d1916546350a819b81d29870388576910508a4e3c",
      "vout": 0,
      "scriptSig": {
        "asm": "0014df020f379e85bb2e17518fdc78052c89ca8b3f1b",
        "hex": "160014df020f379e85bb2e17518fdc78052c89ca8b3f1b"
      },
      "txinwitness": [
        "3044022051dcf66a9c85bf341c7caf64f1ab831d337f74fe77c61ed5035e29a866448610022042230b482246f95181f03509ef0df942b0b7d8da59a84d6e9cc52919d4cf1bd701",
        "03a35f985939e9f22e8bd647cf514fbe6334a2cd048aa7a829544625e285596da1"
      ],
      "sequence": 4294967294
    }
  ],
  "vout": [
    {
      "value": 0.01906842,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 a4c94d0ce0e0e6d108f1e8d9253b75d28ca8a263 OP_EQUAL",
        "desc": "addr(3GiKte8qyR9N5PQSo6Z7RykJGxXb13LCf7)#vfk7cuyd",
        "hex": "a914a4c94d0ce0e0e6d108f1e8d9253b75d28ca8a26387",
        "address": "3GiKte8qyR9N5PQSo6Z7RykJGxXb13LCf7",
        "type": "scripthash"
      }
    },
    {
      "value": 0.00010000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_HASH160 0868a1be348461be289349542f9fb9c1885f3b1c OP_EQUAL",
        "desc": "addr(32TUg2LfzZbaCzPAWbrRrf5ben4NkaBg5X)#2kjett53",
        "hex": "a9140868a1be348461be289349542f9fb9c1885f3b1c87",
        "address": "32TUg2LfzZbaCzPAWbrRrf5ben4NkaBg5X",
        "type": "scripthash"
      }
    }
  ],
  "hex": "020000000001013c4e8a50106957880387291db819a850635416190de32ab6539909fd3e6b4a720000000017160014df020f379e85bb2e17518fdc78052c89ca8b3f1bfeffffff029a181d000000000017a914a4c94d0ce0e0e6d108f1e8d9253b75d28ca8a26387102700000000000017a9140868a1be348461be289349542f9fb9c1885f3b1c8702473044022051dcf66a9c85bf341c7caf64f1ab831d337f74fe77c61ed5035e29a866448610022042230b482246f95181f03509ef0df942b0b7d8da59a84d6e9cc52919d4cf1bd7012103a35f985939e9f22e8bd647cf514fbe6334a2cd048aa7a829544625e285596da1888b0800",
  "blockhash": "00000000000000000013c0e71833d36470b534426b14d9a8515f6b239589f274",
  "confirmations": 292247,
  "time": 1548395223,
  "blocktime": 1548395223
}

**Comment by 1440000bytes** [comment]
https://github.com/bitcoin/bitcoin/issues/22524#issuecomment-884663685

**Comment by achow101** [comment]
Inputs do not have scriptPubKeys.

**Comment by www222fff** [comment]
yes, only output need scriptPubKeys
