### ISSUE TITLE
`scantxoutset` should output the block hash instead of block height

### ISSUE THREAD

**Issue by luisschwab** [bitcoin/bitcoin#30478]
### Please describe the feature you'd like to see added.

When using the `scantxoutset` RPC, the current behaviour is to show the block **height** of the UTXO. This is not optimal, as block height is ambiguous, especially in the case of a block reorganization happening at the same instant of the query. In this case, an UTXO that does not exist would be assumed to exist, unless the chain's tip hash is recorded before the scan, and make sure it still exists after, as per [this](https://github.com/bitcoindevkit/bdk/issues/895#issuecomment-1475766797) comment by @evanlinjin.

The optimal behaviour should be instead to show block **hash**:

```diff
~$ bitcoin-cli scantxoutset start "[\"addr(bc1q5q9344vdyjkcgv79ve3tldz4jmx4lf7knmnx6r)\"]"
{
  "success": true,
  "txouts": 185261159,
  "height": 852742,
  "bestblock": "000000000000000000004bf6339c59b5c789c8bfd00efc1a4d77d948f1ea328a",
  "unspents": [
    {
      "txid": "fae435084345fe26e464994aebc6544875bca0b897bf4ce52a65901ae28ace92",
      "vout": 0,
      "scriptPubKey": "0014a00b1ad58d24ad8433c56662bfb45596cd5fa7d6",
      "desc": "addr(bc1q5q9344vdyjkcgv79ve3tldz4jmx4lf7knmnx6r)#smk4xmt7",
      "amount": 0.00091190,
      "coinbase": false,
      "height": 852741
+     "blockhash": 000000000000000000004bf6339c59b5c789c8bfd00efc1a4d77d948f1ea328a
    }
  ],
  "total_amount": 0.00091190
}
```

**Comment by luisschwab** [comment]
> So I don't think there is a strong benefit in removing it?

Yes, I agree.

**Comment by luisschwab** [comment]
Sure, should also be trivial to add.

**Comment by jbesraa** [comment]
I am interested in taking a look at this issue if nobody else is working on it already

**Comment by luisschwab** [comment]
@jbesraa I'm currently working on a PR for this issue.

**Comment by luisschwab** [comment]
PR is up, reviews are appreciated.
