### ISSUE TITLE
fuzz: crypter timeout

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30503]
Found by oss-fuzz

[clusterfuzz-testcase-crypter-4690510954954752.bin.not.txt](https://github.com/user-attachments/files/16347247/clusterfuzz-testcase-crypter-4690510954954752.bin.not.txt)

```
FUZZ=crypter perf record -g --call-graph dwarf  ./src/test/fuzz/fuzz  ./clusterfuzz-testcase-crypter-4690510954954752
... half a minute ...
hotspot ./perf.data
```

![Screenshot from 2024-07-23 12-16-34](https://github.com/user-attachments/assets/f37f17e9-2b38-475a-8f59-caedf29c30c8)

**Comment by brunoerg** [comment]
> My recommendation would be to limit the number of iterations to something reasonable, but still enough to cover all cases.

Agreed, I just reproduced it and it executes 9176 ones. No need for this number.
