### ISSUE TITLE
implicit-integer-sign-change in ActivateSnapshot

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30514]
```
$ echo 'dXR4b/8BAPq/tdph' | base64 --decode > ./crash

$ UBSAN_OPTIONS="suppressions=$PWD/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1" FUZZ=utxo_snapshot ./src/test/fuzz/fuzz ./crash
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2946336184
INFO: Loaded 1 modules   (625551 inline 8-bit counters): 625551 [0x572ffe28af78, 0x572ffe323b07), 
INFO: Loaded 1 PC tables (625551 PCs): 625551 [0x572ffe323b08,0x572ffecaf3f8), 
./src/test/fuzz/fuzz: Running 1 inputs 1 time(s) each.
Running: ./crash
validation.cpp:5657:28: runtime error: implicit conversion from type 'uint32_t' (aka 'unsigned int') of value 3275262676 (32-bit, unsigned) to type 'int' changed the value to -1019704620 (32-bit, signed)
    #0 0x572ffc2f8a69 in ChainstateManager::ActivateSnapshot(AutoFile&, node::SnapshotMetadata const&, bool) src/validation.cpp:5657:28
    #1 0x572ffb5b93ac in (anonymous namespace)::utxo_snapshot_fuzz_target(std::span<unsigned char const, 18446744073709551615ul>)::$_0::operator()() const src/test/fuzz/utxo_snapshot.cpp:83:27
    #2 0x572ffb5b6896 in (anonymous namespace)::utxo_snapshot_fuzz_target(std::span<unsigned char const, 18446744073709551615ul>) src/test/fuzz/utxo_snapshot.cpp:96:9
    #3 0x572ffb73ac5d in std::function<void (std::span<unsigned char const, 18446744073709551615ul>)>::operator()(std::span<unsigned char const, 18446744073709551615ul>) const /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:591:9
    #4 0x572ffb73ac5d in LLVMFuzzerTestOneInput src/test/fuzz/fuzz.cpp:209:5

SUMMARY: UndefinedBehaviorSanitizer: implicit-integer-sign-change validation.cpp:5657:28 
```

The reason is that metadata is untrusted input, but it isn't sanitized at that point. I presume it can also be reproduced with the integer sanitizer and:

```diff
diff --git a/test/functional/feature_assumeutxo.py b/test/functional/feature_assumeutxo.py
index 943862f8cf..fcb894c924 100755
--- a/test/functional/feature_assumeutxo.py
+++ b/test/functional/feature_assumeutxo.py
@@ -113,10 +113,10 @@ class AssumeutxoTest(BitcoinTestFramework):
         bogus_block_hash = "0" * 64  # Represents any unknown block hash
         # The height is not used for anything critical currently, so we just
         # confirm the manipulation in the error message
-        bogus_height = 1337
+        bogus_height = -1019704620
         for bad_block_hash in [bogus_block_hash, prev_block_hash]:
             with open(bad_snapshot_path, 'wb') as f:
-                f.write(valid_snapshot_contents[:11] + bogus_height.to_bytes(4, "little") + bytes.fromhex(bad_block_hash)[::-1] + valid_snapshot_contents[47:])
+                f.write(valid_snapshot_contents[:11] + bogus_height.to_bytes(4, "little", signed=True) + bytes.fromhex(bad_block_hash)[::-1] + valid_snapshot_contents[47:])
 
             msg = f"Unable to load UTXO snapshot: assumeutxo block hash in snapshot metadata not recognized (hash: {bad_block_hash}, height: {bogus_height}). The following snapshot heights are available: 110, 200, 299."
             assert_raises_rpc_error(-32603, msg, node.loadtxoutset, bad_snapshot_path)
```

**Comment by fjahr** [comment]
Nice find, thanks for reporting!

I think it is worth keeping the block height around even if it seems completely redundant in the base case. The additional information can be helpful to us in certain failure cases, especially if we discuss issues like in #30288 seriously. So, I am suggesting to keep the block height and sanitize it in #30516.

> I presume it can also be reproduced with the integer sanitizer and:

Not quite, I have added the test to reproduce the failure in the first commit: https://github.com/bitcoin/bitcoin/pull/30516/commits/98e119da35c4f7e74f0c423974d497e350c8e9fa

**Comment by fjahr** [comment]
> Can you clarify what you mean with "not quite"? Locally, if I compile with undefined,integer,float-divide-by-zero and run my diff with: UBSAN_OPTIONS="suppressions=$PWD/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1"  ./test/functional/feature_assumeutxo.py, I get the same crash.

Ah, it wasn't clear to me that the I would have to run it with the sanitizer. That's why it didn't fail for me.

You can reproduce the issue and make the test fail with the following edit on master and without needing sanitizers:

```diff
-        bogus_height = 1337
+        bogus_height = 3275262676
```

That's a simplified version of the test I linked to in https://github.com/bitcoin/bitcoin/commit/98e119da35c4f7e74f0c423974d497e350c8e9fa, I just wanted to keep the old bogus number around too.

This produces:
```
substring: 'Unable to load UTXO snapshot: assumeutxo block hash in snapshot metadata not recognized (hash: 0000000000000000000000000000000000000000000000000000000000000000, height: 3275262676). The following snapshot heights are available: 110, 200, 299.'
error message: 'Unable to load UTXO snapshot: assumeutxo block hash in snapshot metadata not recognized (hash: 0000000000000000000000000000000000000000000000000000000000000000, height: -1019704620). The following snapshot heights are available: 110, 200, 299. (/var/folders/9z/n7rz_6cj3bq__11k5kcrsvvm0000gn/T/bitcoin_func_test_e19uh_0n/node0/regtest/utxos.dat.mod)'.
```

And I think that's a tick closer to what the fuzzer did if I interpret the error correctly. I think it handed in 3275262676 as the block height as well.

**Comment by Sjors** [comment]
As mentioned in https://github.com/bitcoin/bitcoin/pull/30598#issuecomment-2273333251 I also prefer to keep height around and just check it.

Maybe make it a `uint64` if you have to touch it anyway.

**Comment by Sjors** [comment]
There's two things I'd like to be able to do in the future. One doesn't require having the height in the metadata, but the other does.

1. I'd like to keep the option to improve the `The base block header (%s) must appear in the headers chain.` message by checking the snapshot height.

In the normal case, where header sync is still in progress, we can change it to:

```
The base block header (%s) must appear in the headers chain at height %d (currently synced to %d).
```

If we already have a header at that height, it suggest there's a large fork, see #30288. In that case a different message could warn about that.

But since the height is hardcoded in `m_assumeutxo_data`, we can get it from there. It doesn't need to be in the metadata file.

2. As we add new snapshots in future releases, a user might download a recent snapshot and try to use it in an older release. That won't work, and the current message "The base block header (%s) must appear in the headers chain." is too cryptic. 

Instead, if we keep the height in the metadata we can do something like:

```
if (metadata.height > latest_known_snapshot.height) {
   // "Unsupported snapshot for height %d, considering downloading a more recent Bitcoin Core release."
} else {
   // Probably a malicious snapshot
}
```

**Comment by Sjors** [comment]
I haven't tested the error message.

> list the available blocks in the params

That would be better, but it's too vague for the user to realize they need to install a newer version.

> Not sure about error messages to urge users to upgrade

I agree that needs more thinking. But if we don't show the message, the "handy tutorial" written by the attacker will.

> it correctly says currently: "Make sure all headers are syncing"

That's not correct in the event of a large fork, where this message would be shown forever.

**Comment by Sjors** [comment]
> I fail to see how adding the block height to the metadata in this case helps, when the height is already hardcoded in m_assumeutxo_data.

When the user loads a recent snapshot into an older version of Bitcoin Core the height won't be in `m_assumeutxo_data`. That's why we should hold on to the metadata (even if we need to be careful on how to render the error).
