### ISSUE TITLE
scriptpubkeyman fuzz target TopUp is slow (2/N)

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30541]
Follow-up to https://github.com/bitcoin/bitcoin/issues/30476

Found by OSS-Fuzz / https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70780 

Seems wasteful to spend time in `TopUp` while fuzzing, so my recommendation would be to limit TopUp iterations a bit.

Context: [clusterfuzz-testcase-scriptpubkeyman-5934021442338816.bin.txt](https://github.com/user-attachments/files/16409466/clusterfuzz-testcase-scriptpubkeyman-5934021442338816.bin.txt)

```
$ FUZZ=scriptpubkeyman perf record -g --call-graph dwarf  ./src/test/fuzz/fuzz -runs=1 ./clusterfuzz-testcase-scriptpubkeyman-5934021442338816.bin.txt
$ hotspot  ./perf.data 
```

![Screenshot from 2024-07-29 10-05-27](https://github.com/user-attachments/assets/9ad1e830-c24d-436a-8772-cb6c8fccf892)

**Comment by brunoerg** [comment]
I'm working on some improvements for this target. Reducing the keypool improves it but doesn't solve the problem entirely.
