### ISSUE TITLE
Why i get 403 error for http rpc access when permission in bitcoin.conf seems to be well

### ISSUE THREAD

**Issue by kosuodhmwa** [bitcoin/bitcoin#30557]
https://github.com/sparrowwallet/sparrow/issues/1471 

![image](https://github.com/user-attachments/assets/f75f83c0-0e37-41b9-8e44-793bf304ae2b)

Neither sparrowwallet (https://github.com/sparrowwallet/sparrow/issues/1471) nor cryptoadvance (https://github.com/cryptoadvance/specter-desktop/issues/2465) is working with REMOTE access from other IP while "miro bitcoin manager" is working on same vm as bitcoind stack (via 127.0.0.1)

**Comment by kosuodhmwa** [comment]
does not make sense with that config params imo. 

and username and password is 100% correctly

**Comment by kosuodhmwa** [comment]
i also added disablewallet=0, does not solve problem

maybe problem is that it runs via tor? but miro bitcoin manager web gui also runs... (???)

bitcoin stack i use is Satoshi:27.99.0

**Comment by kosuodhmwa** [comment]
this 
![image](https://github.com/user-attachments/assets/73cdfeee-beb1-4840-aca3-e1ff369ca5e1)

**Comment by kosuodhmwa** [comment]
![image](https://github.com/user-attachments/assets/a3e86af4-67d8-4720-b13b-72022d9f60c6)

**Comment by kosuodhmwa** [comment]
same here 
![image](https://github.com/user-attachments/assets/08d41237-8871-4754-a369-a59371b24f50)

**Comment by pinheadmz** [comment]
You need to set rpcuser and rpcpassword in bitcoin.conf

**Comment by kosuodhmwa** [comment]
its set you lil genious, otherwise would also not run on 127.0.0.1/localhost wtf 

Self-cite: _<but miro bitcoin manager web gui also runs... (???)>_

**Comment by kosuodhmwa** [comment]
txindex = 1

proxy = 127.0.0.1:9050
listen = 1
bind = 0.0.0.0

server = 1
rpcallowip = 0.0.0.0
rpcbind = 0.0.0.0
rpcport = 8332

rpcuser = .....
rpcusername = .....

rpcpass = .....
rpcpassword = .....

wallet = mywallet
disablewallet=0

**Comment by pinheadmz** [comment]
Cool. I didn't see it in your screenshot in the original post and 403 is an authentication error. Since you are getting personal for some reason I am going to have to stop helping you and if you violate the comment policy at bitcoin-core/meta again you may be temporarily blocked from the repository.

**Comment by kosuodhmwa** [comment]
sorry but that s**t really sucks

**Comment by mariosanchezgarcia** [comment]
Hola sigo vivo.... SatoshiNakamoto es español

**Comment by willcl-ark** [comment]
Closing this as this issue tracker is not for support questions.

The [comment above](https://github.com/bitcoin/bitcoin/issues/30557#issuecomment-2260269755) indicates some more appropriate venues to ask such support questions.

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
Maybe the problem is a bug in master branch i've compiled from
