### ISSUE TITLE
rpcallowip = 192.168.254.0/24, 192.168.1.0/24, 192.168.0.0/24 is not accepted. How to do that?

### ISSUE THREAD

**Issue by kosuodhmwa** [bitcoin/bitcoin#30585]
rpcallowip = 192.168.254.0/24, 192.168.1.0/24, 192.168.0.0/24 is not accepted. How to do that?

**Comment by kosuodhmwa** [comment]
Only one way is this?

192.168.0.0/16

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
FYI: There seems to be nothing: https://github.com/bitcoin/bitcoin/issues/bitcointalk.org

**Comment by willcl-ark** [comment]
Oh, I updated my saved response, thanks. Didn't realise GH was interpreting the link like that!

The correct link is https://bitcointalk.org/

**Comment by kosuodhmwa** [comment]
thank you very much for your feedback :-)
