### ISSUE TITLE
Improve python scripts with type hints for function parameters/return value(s)

### ISSUE THREAD

**Issue by rockett-m** [bitcoin/bitcoin#30589]
### Please describe the feature you'd like to see added.

Many of the python scripts could use edits to the functions.
- type hints to the function params
![fn-type-hints](https://github.com/user-attachments/assets/17fccf6d-f0a6-42e5-86bd-3d777781be41)

- type hints for the return value(s)
For example, 38/40 instances of `def main()` do not specify a return type. 
![def-main](https://github.com/user-attachments/assets/4f2b4f57-06c8-487d-b0fa-369cf434b892)

### Describe the solution you'd like

The function definition `def main():` has equivalence to `def main() -> None:`, so explicit `None` return defines are the least important to me. Leaving up to discussion.
Would more strongly advocate for return types that are not `None` to be explicitly defined, plus all function parameters.

Example: If a main function returns an exit code, I'd propose using an explicit `def main() -> int:`

### Please leave any additional context

"Use [type hints](https://docs.python.org/3/library/typing.html) in your code to improve code readability and to detect possible bugs earlier."
(https://github.com/bitcoin/bitcoin/blob/master/test/functional/README.md)

https://peps.python.org/pep-0484/

**Comment by brunoerg** [comment]
Concept NACK on changes just to add type hints. I don't see any strong benefit on type hints that would overcome the malefits (e.g. conflicts with other PRs) of this kind of change. It is already in the documentation, so we can expect every new code to adopt type hints. Also, I don't see any problem on adding type hints when already touching an existing code.
