### ISSUE TITLE
doc: deduplicate list of chain/network strings in RPC/parameter help texts

### ISSUE THREAD

**Issue by theStack** [bitcoin/bitcoin#30645]
### Motivation

Many command line parameter and RPC help texts currently contain the list of chain/network names hardcoded ("main, test, testnet4, signet, regtest"), which is error-prone as it can easily happen to miss an instance if the list ever changes again. 

### Possible solution

For better maintainability, the list should be deduplicated, either with a constant string or a function creating that string like `ListChainTypes`. See the suggestions https://github.com/bitcoin/bitcoin/pull/30642#discussion_r1714711575 and https://github.com/bitcoin/bitcoin/pull/30642#discussion_r1715195404.

### Useful Skills

* Compiling Bitcoin Core from source
* Basic C++ skills

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by martinsaposnic** [comment]
working on this 🙂

**Comment by martinsaposnic** [comment]
new PR with possible solution: https://github.com/bitcoin/bitcoin/pull/30648

**Comment by willcl-ark** [comment]
Closing since https://github.com/bitcoin/bitcoin/pull/30648 was merged
