### ISSUE TITLE
Question on Changing Bitcoin Blockchain Data Directory in Linux Without Redownloading

### ISSUE THREAD

**Issue by bitcoinchunk** [bitcoin/bitcoin#30672]
Hello Bitcoin Community,

I’m looking for some guidance on how to change the default data directory for the Bitcoin blockchain on a Linux system. I want to move the blockchain data to a different drive with more space, but I’d prefer not to download the entire blockchain from scratch.

Could someone walk me through the steps to move the data seamlessly, ensuring that all configurations are correctly updated? Any tips to avoid issues during the process would be greatly appreciated.

Thanks in advance for your help!

**Comment by achow101** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.
