### ISSUE TITLE
prunemode is incompatible with -blockfilter index

### ISSUE THREAD

**Issue by LemoneyF** [bitcoin/bitcoin#30781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

![litecoin](https://github.com/user-attachments/assets/fc931ca9-f1eb-4c5b-b839-adacca47ba15)

### Expected behaviour

Successful start and access to funds.  

### Steps to reproduce

I was running out of disk space (christ it needs some space) and stupidly selected to run in prune mode while still downloading the ledger.  I have tried the fix mentioned in this thread without luck.   I do however, have a backup of the wallet.  Could it be worth nuking litecoin on my computer and trying to load the backup? 

https://gist.github.com/losh11/2d4ee89cdb4965bec4c2128cbc579e31

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

0.21.3

### Operating system and version

Windows 10 19045.4780

### Machine specifications

Good specs just default install pathway is on a 480GB SSD so space ran out.

**Comment by i-am-yuvi** [comment]
"@LemoneyF, sorry, we cannot answer this as it is not related to Bitcoin Core!"
