### ISSUE TITLE
guix: Build fails for `x86_64-apple-darwin`

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#30810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Guix build for `x86_64-apple-darwin` fails.

### Expected behaviour

The build succeeds.

### Steps to reproduce

```
$ git checkout 94c307b3c0746a08c6135ff38d6f1ad1ed6693bb
$ env SDK_PATH=/home/hebasto HOSTS=x86_64-apple-darwin ./contrib/guix/guix-build
```

### Relevant log output

```
$ env SDK_PATH=/home/hebasto HOSTS=x86_64-apple-darwin ./contrib/guix/guix-build
Found macOS SDK at '/home/hebasto/Xcode-15.0-15A240d-extracted-SDK-with-libcxx-headers', using...
Checking that we can connect to the guix-daemon...

Hint: If this hangs, you may want to try turning your guix-daemon off and on
      again.

make: Entering directory '/home/hebasto/git/bitcoin/depends'
make[1]: Entering directory '/home/hebasto/git/bitcoin/depends'
make[1]: Leaving directory '/home/hebasto/git/bitcoin/depends'
make: Leaving directory '/home/hebasto/git/bitcoin/depends'
INFO: Building 94c307b3c074 for platform triple x86_64-apple-darwin:
      ...using reference timestamp: 1725398870
      ...running at most 4 jobs
      ...from worktree directory: '/home/hebasto/git/bitcoin'
          ...bind-mounted in container to: '/bitcoin'
      ...in build directory: '/home/hebasto/git/bitcoin/guix-build-94c307b3c074/distsrc-94c307b3c074-x86_64-apple-darwin'
          ...bind-mounted in container to: '/distsrc-base/distsrc-94c307b3c074-x86_64-apple-darwin'
      ...outputting in: '/home/hebasto/git/bitcoin/guix-build-94c307b3c074/output/x86_64-apple-darwin'
          ...bind-mounted in container to: '/outdir-base/x86_64-apple-darwin'
      ADDITIONAL FLAGS (if set)
          ADDITIONAL_GUIX_COMMON_FLAGS: 
          ADDITIONAL_GUIX_ENVIRONMENT_FLAGS: 
          ADDITIONAL_GUIX_TIMEMACHINE_FLAGS: 
guix shell: error: cannot link profile: '/home/hebasto/.guix-profile' already exists within container
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@94c307b3c0746a08c6135ff38d6f1ad1ed6693bb

### Operating system and version

Debian Bookworm

### Machine specifications

RISC-V SBC.

**Comment by hebasto** [comment]
> Has this ever worked on your system? `guix shell: error` sounds like it is an error unrelated to Bitcoin Core?
> 
> Can you use guix and guix shell normally?

Both command work just fine. For example:
```
$ guix package -i hello
$ guix shell python -- python3
```

Moreover, every other non-Darwin host is built successfully with `./contrib/guix/guix-build`.

**Comment by fanquake** [comment]
I think you'll need to debug this further. It's odd that building for all HOSTS (except one) would work, but building for `x86_64-apple-darwin` currently works fine, as far as I'm aware (just tested on two different systems).

> Both command work just fine. For example:

It's not clear that those are actually invoking the issue-causing behaviour. The error message points to `guix container`. i.e `guix shell --container`

**Comment by hebasto** [comment]
```
$ uname -m
riscv64
$ guix shell --container --pure hello
$ hello
Hello, world!
$ exit
exit
```

The issue happens when switch to/form Darwin host. For both invocations
```
$ env SDK_PATH=/home/hebasto HOSTS="x86_64-w64-mingw32 x86_64-apple-darwin" ./contrib/guix/guix-build
```
and
```
$ env SDK_PATH=/home/hebasto HOSTS="x86_64-apple-darwin x86_64-w64-mingw32" ./contrib/guix/guix-build
```
build for the former host succeeds, then the error happens:
```
guix shell: error: cannot link profile: '/home/hebasto/.guix-profile' already exists within container
```

**Comment by fanquake** [comment]
You'll need to try with all the options we pass to shell/container.

**Comment by hebasto** [comment]
The problem was `env SDK_PATH=/home/hebasto`, which effectively shared my home directory with a Guix container.
