### ISSUE TITLE
Misleading index error message

### ISSUE THREAD

**Issue by jlest01** [bitcoin/bitcoin#30836]
When running node with the `txindex` parameter for the first time, we see the following message in the log:
```ERROR: Commit: Failed to commit latest txindex state```

This misleads the user into believing that something is wrong, but the indexing process normally begins shortly thereafter.
It appears that the reason for this message is that there is no index yet. Since `src/index/base.h` is common to all indexes, this message may appear in all indexes.

**Comment by mzumsande** [comment]
This should be fixed already in master and for v28: See #29671.

**Comment by jlest01** [comment]
Indeed. Thanks.
