### ISSUE TITLE
No ZMQ `sequence` notifications on Regtest

### ISSUE THREAD

**Issue by ouziel-slama** [bitcoin/bitcoin#30853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

No message received in the `sequence` feed when a transaction is added to the mempool.

### Expected behaviour

We should receive a ZMQ notification when a new transaction enters the mempool. This works fine on mainnet.

### Steps to reproduce

configure Bictoin Core with:
```
[regtest]
zmqpubrawtx=tcp://0.0.0.0:29332
zmqpubhashtx=tcp://0.0.0.0:29332
zmqpubsequence=tcp://0.0.0.0:29332
zmqpubrawblock=tcp://0.0.0.0:29333
```
Connect to ZMQ and broadcast a transaction.
Here is the code used: https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/lib/follow.py

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v27.0

### Operating system and version

Ubuntu 22.04.4 LTS

**Comment by pinheadmz** [comment]
There is a test for zmq sequence (`interface_zmq.py`) so it must be working on regtest. Compare your code to the `test_sequence()` block?

**Comment by ouziel-slama** [comment]
Thanks for the link! actually it works fine, the error comes from elsewhere! sorry for the false alarm!
