### ISSUE TITLE
Race condition between ZMQ UpdateTip and getblocktemplate

### ISSUE THREAD

**Issue by mcelrath** [bitcoin/bitcoin#30862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When ZMQ announces a new chain tip via "sequence" "C" message, if `getblocktemplate` is called immediately, it can return a block template that does not reflect the new chain tip.

This is important for Braidpool, which needs to switch to a new chain tip as quickly as possible when a new block comes in.

### Expected behaviour

`getblocktemplate` should return a result consistent with the information announced via ZMQ and correctly reflect the current chain tip.

### Steps to reproduce

This was seen on the `cpunet` testnet fork (which does not touch any of the consensus or ZMQ code). The bug report there is: https://github.com/braidpool/bitcoin/issues/1#issuecomment-2341397203

This occurs infrequently and it may be necessary to run the miner script for a day or more to see it.

The script that receives the ZMQ messages and calls `getblocktemplate` is here: https://github.com/braidpool/bitcoin/blob/cpunet/contrib/cpunet/miner

### Relevant log output

Please see https://github.com/braidpool/bitcoin/issues/1#issuecomment-2341397203 for log output.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

Bitcoin Core version v27.99.0-e8b157f687eb-dirty

### Operating system and version

Arch Linux 6.10.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC

### Machine specifications

8 core Ryzen, SSD.

**Comment by mzumsande** [comment]
can you rule out that someone else on the network just mined a block, and the inconclusive `getblocktemplate` result belongs to a previous call that was sent off before that new block was connected?

**Comment by mcelrath** [comment]
I believe that's answered positively by the timestamps and structure of the
calling code.

A better test would be to reproduce this with regtest which I'll create a
script to demonstrate soon.

But at the same time it seems there should be a mutex around the chain tip.
If there isn't this is basically guaranteed to happen. I haven't looked yet.

**Comment by mzumsande** [comment]
> I believe that's answered positively by the timestamps and structure of the calling code.

not really. I don't see a `"Calling bitcoin-cli: getblocktemplate"` entry in the [log](https://github.com/braidpool/bitcoin/issues/1#issuecomment-2341397203) excerpt, but I do see a `DEBUG     result =` log entry. 

Both logs are part of `async def bitcoin_cli(self, *args, input=b""):` in your script. That's why I thought the rpc call may have happened before the block was connected by bitcoind.

**Comment by mcelrath** [comment]
Not yet. I've been running my morning script all week and haven't seen it
happen again.

**Comment by mcelrath** [comment]
Why cannot these results be consistent? Isn't that the purpose of a mutex on the Chainstate? It's not clear to me why there "obviously can't" be multi-threaded consistency on the chain state. The (apparent) order of operations here is:
1. Chain tip received
2. ZMQ broadcast
3. RPC call getblocktemplate

If 3 were reversed with 1 or 2 I would agree with the "can't" statement, but that doesn't seem to be what's happening.

It seems to me that the ZMQ message is being sent while that mutex is not being held, and the fix should be simple -- make sure that mutex is held until the ZMQ alert is finished. A new RPC call that comes in should block until the Chainstate update (including announcement over ZMQ) is complete.

**Comment by mcelrath** [comment]
Working on a stale block is exactly the problem here, because of inconsistent responses. I think we have a miscommunication here... It sound like you're saying there's no way to avoid working on a stale block...

**Comment by mcelrath** [comment]
@sipa we're planning on switching to the new IPC mechanism anyway, that StratumV2 is also using. Do you have any comments about synchronicity in that context?

FWIW I think I'm the only person ever to have used ZMQ. My `contrib/zmq/zmq_sub.py`  file no longer works due to python async changes. I'm also planning on submitting a PR to update it. But maybe I agree ZMQ might be a mistake. OTOH I think polling in the 21st century is also a mistake.

**Comment by mzumsande** [comment]
Would be nice to respond to my prior message: Why doesn't your [Miner log](https://github.com/braidpool/bitcoin/issues/1#issuecomment-2341397203) show a timestamped "[Calling bitcoin-cli](https://github.com/braidpool/bitcoin/blob/29c38babfb83f8520a882bad6b25d1851b7b4a41/contrib/cpunet/miner#L108) (...) getblocktemplate" entry, if, supposedly, the relevant call to `getblocktemplate` call was sent off after the zmq notification for the new tip was received?

Without an explanation for that, it just looks to me that you get the delayed result of an older `getblocktemplate` invocation, and there is no issue at all.

**Comment by mcelrath** [comment]
@mzumsande you are right. Apparently I failed to scroll up in the log. There was several tips announced simultaneously and this is absolutely due to a previous invocation of `getblocktemplate`. I'm going to close issue this now, as I've also failed to reproduce it since.

Log with more context attached.

[miner.log](https://github.com/user-attachments/files/17061890/miner.log)
