### ISSUE TITLE
translations: `28.x` update pulled in random strings?

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#30897]
Translations were updated for 28.x in #30715.

Looks like that update pulled in things that are not translations. i.e:

https://github.com/bitcoin/bitcoin/blob/e43ce250c6fb65cc0c8903296c8ab228539d2204/src/qt/locale/bitcoin_gl_ES.ts#L6

?

**Comment by hebasto** [comment]
> Transations were updated for 28.x in #30715.
> 
> Looks like that update pulled in things that are not translations. i.e:
> 
> https://github.com/bitcoin/bitcoin/blob/e43ce250c6fb65cc0c8903296c8ab228539d2204/src/qt/locale/bitcoin_gl_ES.ts#L6
> 
> ?

This is a poor / malicious translation.

https://app.transifex.com/bitcoin/bitcoin/translate/#gl_ES/qt-translation-028x/508593963:
![image](https://github.com/user-attachments/assets/2189dde4-c996-4399-acda-992bcced1f99)

**Comment by pablomartin4btc** [comment]
In the meantime, is it too ugly to add a regex into `update-translations.py`? (or a function like the existent ones that already parse the strings and validate their format)

```
# regex patterns for malicious content and symbols (just an example)
MALICIOUS_PATTERN = re.compile(r'[\x00-\x1F\x7F-\x9F<>&\'";`\\\xFFFD]|'
                               r'(\.\./|\.\.\\|\%2e%2e/|\%2e%2e\\|'
                               r'\$HOME/|\%USERPROFILE\%|\%APPDATA\%|\$USER|\$PATH|'
                               r';|&&|\|\||\||&|\\|>|--)', re.UNICODE | re.IGNORECASE)
```

It won't detect random non-sense translations but at least it's a step forward while we find the 4o-mini alternative.
