### ISSUE TITLE
`test_bitcoin` from pre-built 28.0rc2 tarball is failing for JSON parsing

### ISSUE THREAD

**Issue by bitcoin-tools** [bitcoin/bitcoin#30938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Tested the 28.0rc2 packages from [bitcoincore.org/bin](https://bitcoincore.org/bin/bitcoin-core-28.0/test.rc2/) for Linux x86_64, Darwin x86_64, and Darwin arm64.

Seeing consistent failures in the rc2 `test_bitcoin` binary running:
- Docker with base image of Arch ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429843131), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430967365), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430986135))
- Docker with base image of Debian ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429843761), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430967880), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430987569)), Ubuntu ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429845402), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430970232), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430989907)), and Kali ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429844197), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430968471), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430988323))
- Docker with base image of openSUSE Leap ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429845604), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430970512), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430990207)), openSUSE Tumbleweed ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429845803), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430970806), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430990490)), and SUSE Enterprise ([1](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958688270/job/30429845217), [2](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10958998680/job/30430969917), [3](https://github.com/bitcoin-tools/nodebuilder/actions/runs/10959033329/job/30430989693))

rc2 `test_bitcoin` is consistently NOT failing on the following:
- Ubuntu running on bare metal github CI runner (not in Docker)
- macOS 13 x86_64 and macOS 14 arm64 on bare metal github CI runner
- Docker with base image of Alpine, Clear Linux, Fedora, Manjaro, Oracle Linux, RHEL, and Rocky Linux

Also, `test_bitcoin` was consistently NOT failing like this on 28.0rc1.

### Expected behaviour

`test_bitcoin` from pre-built package should return exit status 0 when run inside a Docker container.

### Steps to reproduce

To reproduce the `test_bitcoin` failures on 28.0rc2:

```sh
git clone https://github.com/bitcoin-tools/nodebuilder
cd nodebuilder/docker/
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 -f Dockerfile_archlinux .
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 -f Dockerfile_debian .
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 -f Dockerfile_kali .
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 -f Dockerfile_openususe-leap .
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 -f Dockerfile_opensuse-tumbleweed .
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 -f Dockerfile_sles .
docker build --build-arg NODEBUILDER_VERSION=f0194173557c364d929148952c6a28e2a8965f97 .
```

To reproduce the expected behavior on 28.0rc1:

```sh
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb -f Dockerfile_archlinux .
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb -f Dockerfile_debian .
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb -f Dockerfile_kali .
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb -f Dockerfile_openususe-leap .
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb -f Dockerfile_opensuse-tumbleweed .
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb -f Dockerfile_sles .
docker build --build-arg NODEBUILDER_VERSION=f453fb64c665beabfce70fe037625215ea0e96bb .
```

Commit hashes are taken from [this PR](https://github.com/bitcoin-tools/nodebuilder/pull/1539/commits).

### Relevant log output

```text
[2024-09-20T13:36:14]  INFO: Running the unit tests.

Running 630 test cases...
test/system_tests.cpp(61): error: in "system_tests/run_command": check what.find(tfm::format("RunCommandParseJSON error: process(%s) returned", command)) != std::string::npos has failed
test/system_tests.cpp(62): error: in "system_tests/run_command": check what.find(expected) != std::string::npos has failed

*** 2 failures are detected in the test module "Bitcoin Core Test Suite"

[2024-09-20T13:39:42] ERROR: Unit tests failed.
[2024-09-20T13:39:42] ERROR: Unhandled error at line 1.
The command '/bin/sh -c /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"' returned a non-zero code: 1
```

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

28.0rc2

### Operating system and version

Docker on Ubuntu 24

### Machine specifications

- Inside a Docker container on GitHub Actions CI
- Inside docker on my Ubuntu 24 local environment.

**Comment by bitcoin-tools** [comment]
> worked around by installing python3

That explains why it doesn't run on certain docker base images. Is python3 considered a runtime dependency for test_bitcoin?

**Comment by fanquake** [comment]
I think the bug is that commit introduced a (silent) runtime dependency that isn't actually checked/enforced in anyway.

**Comment by fanquake** [comment]
Yea. Even if `ctest`/development likely requires it, the `test_bitcoin` release binary we are shipping to end users shouldn't have a (undocumented) dependency on invoking Python.

**Comment by bitcoin-tools** [comment]
Can it be simplified to `const std::string command{"echo err 1>&2 && false"};` or is `sh -c '...'` necessary to ensure portability?

**Comment by bitcoin-tools** [comment]
Researching it deeper, it may be better to wrap the command in `sh -c '...'`, since that would run `echo` and `false` as shell built-ins, rather than depending on coreutils binaries. But I agree with your reasoning regarding `ls`.

**Comment by hebasto** [comment]
> I think the bug is that commit introduced a (silent) runtime dependency that isn't actually checked/enforced in anyway.

I [agree](https://github.com/bitcoin/bitcoin/pull/30788#issuecomment-2331243915).

I'd suggest reverting 199bb09d88e28d951c5068eb65643390dbedd066, as workarounds for https://github.com/bitcoin/bitcoin/issues/30601 and https://github.com/bitcoin/bitcoin/issues/30608 are available.

Additionally, I suspect there is a bug in `src/util/subprocess.h` that needs to be investigated and fixed, along with the test fixes.

**Comment by achow101** [comment]
> The cleanest fix would probably be https://github.com/bitcoin/bitcoin/pull/29868/files#diff-4ea52ba9a5642d6946fb0016ca168b6647a8c6403d9e15e2a7197e72022824d4R87 `const std::string command{"sh -c 'echo err 1>&2 && false'"};`.

Done in #30952 

> I'd suggest reverting [199bb09](https://github.com/bitcoin/bitcoin/commit/199bb09d88e28d951c5068eb65643390dbedd066), as workarounds for #30601 and #30608 are available.

If @maflcko's suggestion is good enough, I'd prefer to use that rather than reverting.

**Comment by hebasto** [comment]
> This can be worked around by installing python3. An alternative would be something like done here: https://github.com/bitcoin/bitcoin/pull/29868/files#r1747435819 (but that diff currently does not compile, as can be seen in the CI output)

I’ve revisited this and now think it’s reasonable for a test of a feature that itself depends on Python (HWI) to use Python directly. The only requirement is a runtime check ensuring that Python is available in `PATH`.

The dependency on `coreutils` may not be the only one. For example, the `bitcoin-core` Guix package [depends](https://codeberg.org/guix/guix/src/commit/ac3499aaec06ed61de31d17018c8647fc4e3df49/gnu/packages/finance.scm#L195-L196) on both `coreutils` and `bash`.
