### ISSUE TITLE
rpc auth fails 'Error parsing command line arguments: Invalid parameter -rpcpasssword=password

### ISSUE THREAD

**Issue by kegdeg** [bitcoin/bitcoin#30939]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

After providing rpc credentials using bitcoin-cli, the following error appears:

'Error parsing command line arguments: Invalid parameter -rpcpasssword=password'

telnet to localhost connects with bitcoind running

### Expected behaviour

no error

### Steps to reproduce

This is how the bitcoin.conf looks like:

\# Enable RPC server
server=1

\# RPC settings
rpcuser=user
rpcpassword=password

\# Optional: Set the RPC port (default is 8332)
rpcport=8332

\# Optional: Allow connections from specific IP addresses
\# If you want to allow connections from any IP address, uncomment the next line
\#rpcallowip=0.0.0.0/0

\# If you want to restrict to a specific IP address or subnet
\#rpcallowip=

bitcoin-cli  -rpcuser=user -rpcpasssword='password' start

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

27.0

### Operating system and version

Ubuntu 20.04.6 LTS

**Comment by pinheadmz** [comment]
"rpcpasssword" with 3 S's or 2?

**Comment by kegdeg** [comment]
Oh wow, it should be 2 's'. Although I also had that error when using another password which I copy/pasted (maybe there was a spacing error cannot check now), just used password for the example. Those commands and bitcoin.conf are the correct ones, right? Will check it back again when I am back in front of the terminal.

**Comment by kegdeg** [comment]
This is the bitcoin.conf
![Screenshot from 2024-09-20 18-07-52](https://github.com/user-attachments/assets/0d9cae5f-86f7-42a4-bbce-1c3e955daa1e)

I removed the triple S, now getting the following error from the following command:

bitcoin-cli -rpcuser=user -rpcpassword -stdinrpcpass start

RPC password> 
error: Authorization failed: Incorrect rpcuser or rpcpassword

(i type password)

**Comment by pinheadmz** [comment]
try removing `-rpcpassword` ?

**Comment by pinheadmz** [comment]
also what is `start` for?

**Comment by kegdeg** [comment]
changed it to ./bitcoin-cli -rpcuser=user -stdinrpcpass -netinfo, 'error: Authorization failed: Incorrect rpcuser or rpcpassword

Also trying:
curl --user user:password --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockchaininfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/

the server shows 
2024-09-21T20:21:44Z ThreadRPCServer incorrect password attempt from 127.0.0.1:44938

**Comment by kegdeg** [comment]
steps to reproduce

start bitcoind:
bitcoind -datadir='/path/to/node'

the bitcoin.conf file is located in ~/.bitcoin/bitcoin.conf

server=1
rpcuser=user
rpcpassword=password
rpcport=8332

I try checking rpc connectivity with 

'curl --user 'user' --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getinfo","params":[]}' -H 'content-type:text/plain;' http://127.0.0.1:8332'

there is no response and the node returns:
'2024-09-22T18:01:11Z ThreadRPCServer incorrect password attempt from 127.0.0.1:42004'

**Comment by kegdeg** [comment]
yes, that solved it, thanks!

**Comment by kegdeg** [comment]
-datadir specified, must use bitcoin.conf in datadir
