### ISSUE TITLE
Warn about / refuse unsupported clang version

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#30947]
On an older Intel macOS 13.7 machine:

```
cmake -B build
-- The CXX compiler identification is AppleClang 14.0.3.14030022

...

cmake --build build -j7

...

In file included from /Users/sjors/dev/bitcoin/src/crypto/muhash.h:9:
/Users/sjors/dev/bitcoin/src/uint256.h:133:19: error: call to consteval function 'util::ConstevalHexDigit' is not a constant expression
        auto lo = util::ConstevalHexDigit(*(str_it++));
                  ^

(etc)
```

Our minimum required clang is 16 so this is no surprise.

It would be good if `cmake -B build` checks the minimum version and at least throws a warning.

**Comment by Sjors** [comment]
The documentation says "For macOS 11 (Big Sur) and 12 (Monterey) you need to install a more recent version of llvm". That should include macOS 13 and 14 now as well, see https://trac.macports.org/wiki/XcodeVersionInfo#macOS14

But I think as long as cmake warns about llvm being too old, anyone reading `build-osx.md` will probably figure out that they need to install a newer version via llvm.

**Comment by fanquake** [comment]
>  From googling around I get the impression this check isn't reliable, and you have to check for specific features. E.g. https://stackoverflow.com/questions/75296149/cmake-set-project-to-c-20#comment132865328_75296149

That is what CMake does behind the scenes, i.e the tests in https://github.com/Kitware/CMake/tree/master/Tests/CompileFeatures. So if they are missing coverage for a certain compiler/cxx std combo, it's a bug they should address, not something we should have to test ourselves.

**Comment by Sjors** [comment]
@fanquake do you mean this file? https://github.com/Kitware/CMake/blob/master/Tests/CompileFeatures/cxx_std_20.cpp

**Comment by fanquake** [comment]
It seems like they add cpp feature checks for various compilers if it's otherwise broken/doesn't always report the right version, i.e https://github.com/Kitware/CMake/blob/master/Modules/CMakeCXXCompilerId.cpp.in#L46, maybe they need to do the same for Apple Clang.

**Comment by polespinasa** [comment]
I'm not able to run fuzzing tests also because of this:
```
$ cmake --build build_fuzz
....
/bitcoin/src/uint256.h:133:19: error: call to consteval function 'util::ConstevalHexDigit' is not a constant expression
        auto lo = util::ConstevalHexDigit(*(str_it++));
```
Which clang version are we suposed to use?
```
$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1.1
```

**Comment by fanquake** [comment]
> Which clang version are we suposed to use?

https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md
