### ISSUE TITLE
p2p_headers_presync fuzz target times out when FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION isn't set

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30950]
The target runs slowly on macOS/Windows, so it would be good if someone benchmarked it. At least the macOS 14 CI ran into timeouts consistently.

I've removed the fuzz inputs temporarily in https://github.com/bitcoin-core/qa-assets/commit/84cea7068728bc2c765b9da680eedcb85f9f3c1b in the meantime.

_Originally posted by @maflcko in https://github.com/bitcoin/bitcoin/issues/30661#issuecomment-2363634967_

**Comment by marcofleon** [comment]
Looking into this.

**Comment by marcofleon** [comment]
The `BUILD_FOR_FUZZING` flag isn't on for Windows and macOS CI, so the `ABORT_ON_FAILED_ASSUME` and `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` macros aren't defined. The `p2p_headers_sync` target is doing actual PoW in `CheckProofOfWorkImpl` and timing out.

On the Linux CI those macros are here: https://cirrus-ci.com/task/6411626390224896?logs=ci#L831

Temporary solution would be excluding this harness for Windows and mac in the test runner. Long term we should probably separate out the CI jobs?

**Comment by marcofleon** [comment]
Is that better than adding `-x p2p_headers_presync` to the Windows and macOS test runner calls in the CI?

Using the exclude flag, as opposed to altering the harness, feels cleaner to me. Afaik they would both accomplish the same thing, so ultimately I'm okay with either.

**Comment by marcofleon** [comment]
Wouldn't a developer looking to fuzz test set `-DBUILD_FOR_FUZZING=ON`? In which case, that macro is automatically set (along with `ABORT_ON_FAILED_ASSUME`) and there would be no timeout. Would future harnesses relying on `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` also do an early return?

Also, sorry I'm misunderstanding your point. I'm not too familiar with what the best practice would be here.

**Comment by marcofleon** [comment]
I see what you're saying. I initially thought BUILD_FOR_FUZZING was set as default (when fuzzing).

I've addressed it in https://github.com/bitcoin/bitcoin/pull/31028.
