### ISSUE TITLE
ci: Intermittent issue in feature_fee_estimation.py in sanity_check_rbf_estimates (Block sync timed out after 2400s)

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#30990]
A quick skim of the log looks like there are two blocks at the same height, but I haven't looked too closely yet.

https://cirrus-ci.com/task/6299307458953216?logs=ci#L4251

**Comment by mzumsande** [comment]
Looks like a sync was missing, see #31016 for a fix.
