### ISSUE TITLE
rfc: DATUM mining interface requirements

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#31002]
The Mining interface is designed with Stratum v2 in mind, and can likely also be used to incrementally improve Statum "v1" applications.

Ocean recently announced [DATUM](https://ocean.xyz/docs/datum). So far it's proprietary and undocumented, but hopefully that changes. It could be a good test for the generality of the Mining interface to see if the DATUM gateway requires any additional methods.

Here's the current interface:

https://github.com/bitcoin/bitcoin/blob/d812cf11896a2214467b6fa72d7b763bac6077c5/src/interfaces/mining.h#L47-L106

Where `createNewBlock` returns:

https://github.com/bitcoin/bitcoin/blob/d812cf11896a2214467b6fa72d7b763bac6077c5/src/interfaces/mining.h#L30-L45

Additionally #30955 proposes to add `getCoinbaseMerklePath()` and `submitSolution()`, and https://github.com/Sjors/bitcoin/pull/52 proposes to add `waitFeesChanged`.

cc @luke-jr

**Comment by luke-jr** [comment]
Bitcoin Core has been working toward trying to centrally dictate mining policy, so should really not be used for mining. OCEAN/DATUM's goal is to decentralise mining, not merely switch the central dictator from Bitmain/Foundry to Bitcoin Core.

That being said, there is already a generic/standard mining interface: getblocktemplate. It has worked for years and nothing additional is needed for DATUM.

**Comment by Sjors** [comment]
From casual reading of the [DATUM Gateway README](https://github.com/OCEAN-xyz/datum_gateway) (since there's still no spec), the Mining interface could be useful in a few places:

1. No need to tell users to manually set `-blockmaxsize` and `-blockmaxweight`, because `createNewBlock()` can pass a custom coinbase weight reservation through its `BlockCreateOptions` argument. On a related note, https://github.com/bitcoin/bitcoin/pull/31384#issuecomment-2530503262 discusses the idea of adding `-maxcoinbaseweight`, and the README suggests Knots will do something similar.

2. No need to use `-blocknotify` (which launches `datum_gateway` and presumable then calls `getblocktemplate`). Instead `datum_gateway` could run as a deamon and call `waitTipChanged()` and `waitNext()` https://github.com/bitcoin/bitcoin/pull/31283 which return when there's a new block or better fees. Also easier to setup between two machines.

Looking at the "Template/Share Requirements for Pooled Mining" I don't see any blocking issues at first glance.

> Must include generation transaction outputs provided by the pool in the order provided

> Must include the primary coinbase tag as provided by the pool

> Must include the unique identifier provided by the pool

I'm assuming the `datum_gateway` adds these to the template? (since `getblocktemplate` doesn't include a coinbase transaction)

**Comment by luke-jr** [comment]
> No need to tell users to manually set -blockmaxsize and -blockmaxweight, because createNewBlock() can pass a custom coinbase weight reservation through its BlockCreateOptions argument.

Seems like it would be trivial to add this to GBT. The current approach in Knots isn't ideal (since it would override blockmaxsize/weight if the miner intentionally sets them lower).

> No need to use -blocknotify (which launches datum_gateway and presumable then calls getblocktemplate)

It only sends a signal to the already-running DATUM gateway, but yes, it's not ideal to require the additional configuration. GBT does already support longpolling, however, it's just not implemented in DATUM Gateway yet (see https://github.com/OCEAN-xyz/datum_gateway/issues/3)

> [list of stuff] I'm assuming the datum_gateway adds these to the template?

Yes, it creates the generation transaction.

>the Mining interface could be useful in a few places:

Seems like this would be better suited to a PR on the datum_gateway repo.

**Comment by Sjors** [comment]
> Seems like it would be trivial to add this to GBT.

Agreed.

> Seems like this would be better suited to a PR on the datum_gateway repo.

My only goal here is to figure out if the Mining interface needs anything for Datum that it doesn't need for Stratum v2. Whether you actually use it is up to you of course.
