### ISSUE TITLE
Support transaction broadcast in REST interface

### ISSUE THREAD

**Issue by RCasatta** [bitcoin/bitcoin#31017]
### Please describe the feature you'd like to see added.

I would like to have the possibility to broadcast a transaction via the REST interface which is currently not possible https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md

### Is your feature related to a problem, if so please describe it.

An indexer like the ones for the electrum protocol should work without having access to the RPC interface, I think the only missing method from the REST interface is the tx broadcast.

### Describe the solution you'd like

I would like another REST end point like the following:

`POST /tx`

Broadcast a raw transaction to the network.

The transaction should be provided as hex in the request body. The txid will be returned on success. 

(hex is used for similarity with esplora [API](https://github.com/blockstream/esplora/blob/master/API.md#post-tx), binary would be ok)

### Describe any alternatives you've considered

Using RPC requires an authenticated connection.
Using the p2p network requires to know an additional endpoint and the peering from the indexer

### Please leave any additional context

The REST interface already has risks https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md#risks and I don't think would be more risky to have tx broadcast

Transaction packages may be added in another endpoint

**Comment by stickies-v** [comment]
> Using RPC requires an authenticated connection.

Could you please elaborate on why RPC or authentication is not a feasible option for your use case?

**Comment by stickies-v** [comment]
The "should work without having access to the RPC interface" is the part that I'd like to understand better. For example, the electrs docs specifically mention the bitcoind jsonrpc authentication: https://github.com/romanz/electrs/blob/master/doc/config.md#electrs-configuration

**Comment by brunoerg** [comment]
> The "should work without having access to the RPC interface" is the part that I'd like to understand better. For example, the electrs docs specifically mention the bitcoind jsonrpc authentication: https://github.com/romanz/electrs/blob/master/doc/config.md#electrs-configuration

It's not clear to me as well. Maybe they need it to start using the REST interface?

**Comment by RCasatta** [comment]
Please see https://github.com/bitcoin/bitcoin/pull/31065#issuecomment-2417141803 for details

**Comment by stickies-v** [comment]
Note: #31065 was closed because of lack of conceptual support to implement this feature.

**Comment by fanquake** [comment]
Closing for now, given the PR was closed. Feel free to discuss further. cc @laanwj @0xB10C

**Comment by laanwj** [comment]
We're kind of having the conceptual discussion over in #31065. Probably not a good idea to split it. But in retrospect it should have been done here, and sooner, before someone started working on it.
