### ISSUE TITLE
bitcoin.service issue for a noob like me

### ISSUE THREAD

**Issue by nulladoses** [bitcoin/bitcoin#31021]
### Motivation

Hi i don't know if i'm in the right section but i have a problem installing contrib/init/bitcoind.service. i'm a noob so please if someone can help me. I downloaded bitcoin core full node and Tor. Now i installed the service to start bitcoin core on boot of my machine that is Linux Mint on an old macbook pro.
When i make sudo systemctl start bitcoind show like this
![Schermata del 2024-10-02 19-15-59](https://github.com/user-attachments/assets/b781e7c5-9a29-440e-9492-03cf329e3543)
but when i reboot the system don't start automatically and show this:
![Schermata del 2024-10-02 19-18-17](https://github.com/user-attachments/assets/685b279b-0732-454d-9ff1-820b1321847b)
if i do journalctl -e give me this
![Schermata del 2024-10-02 19-22-00](https://github.com/user-attachments/assets/c8bc770e-a4fa-4bb6-8f17-0f2b685c6667)
the service file is this:
![Schermata del 2024-10-02 19-24-18](https://github.com/user-attachments/assets/a44d461c-ba51-4535-9d84-5de3348fcfb7)
![Schermata del 2024-10-02 19-24-55](https://github.com/user-attachments/assets/b6bf3964-961c-4628-84b2-7a761845da99)
![Schermata del 2024-10-02 19-25-22](https://github.com/user-attachments/assets/195d8548-7d34-4372-942a-c7aa763a5b42)

Thank you in advance to whom can help me.

### Useful Skills

* Compiling Bitcoin Core from source
* Running the C++ unit tests and the Python functional tests
* ...

### Guidance for new contributors

Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by luisschwab** [comment]
FWIW, this is my `bitcoind.service` config, running on Ubuntu 24.04:
```service
[Unit]
Description=Bitcoin Core Daemon
After=network-online.target

[Service]
User=bitcoin
Type=simple
Restart=on-failure
ExecStart=/usr/local/bin/bitcoind

[Install]
WantedBy=multi-user.target
```

Then I enabled it:
```shell
~$ sudo systemctl enable bitcoind.service
```

Never had any issues with it.

**Comment by nulladoses** [comment]
thank you for your answer. i found also this looking around

[Unit]
Description=Bitcoin Daemon
After=network.target
[Service]
User=ubuntu
PIDFile=/home/ubuntu/.bitcoin/bitcoind.pid
ExecStart=/usr/local/bin/bitcoind
Restart=always
TimeoutSec=120
RestartSec=30
[Install]
WantedBy=multi-user.target

and give me one error when i boot the pc but restart anyway and then is ok
thank you
``

**Comment by willcl-ark** [comment]
I think we can close this now as it's resolved.

In the future please be aware that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the `#bitcoin` IRC channel on the [Libera Chat](https://libera.chat/) network.
