### ISSUE TITLE
RPC breakage with v28.0

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#31039]
If you're experiencing issues with Bitcoin Core 28.x, and using RPC, please report them here.

* https://x.com/ketominer/status/1842592989488771531

**Comment by pinheadmz** [comment]
The value for "version" was never checked and still is not. The value for "jsonrpc" since @27101 MUST be a string. If that string is "1.0" then the old JSONRPC behavior is followed (since some old documentation incorrectly recommended this). If that string is "2.0" then the new JSONRPC behavior is followed.

Sending any other string or value type for "jsonrpc" returns a parsing error.

**Comment by dr-orlovsky** [comment]
I do experience.

Basically mempool electrs v3.0.0 in combination with Bitcoin Core v28.0 kill each other once Bitcoin core stops IBS and mempool load

**Comment by ketominer** [comment]
> The `bitcoin-rpc` NPM package seems to be incompatible with Bitcoin Core 28.0 due to sending an incorrect version type: [vansergen/rpc-bitcoin#65](https://github.com/vansergen/rpc-bitcoin/pull/65).

Which FWIW in turn affects Dojo which uses this library. Dojo Coder is aware of the issue and working on changing the RPC client library or fixing rpc-bitcoin but it seems pretty much unmaintained.

**Comment by epiccurious** [comment]
Saw someone's tweet about having to increase `rpcworkqueue`.

https://x.com/_behodler/status/1842657622018683198

**Comment by dr-orlovsky** [comment]
@sipa yes, it fixed! However this arg is undocumented. Also, I believe that without it Bitcoin Core should not crash but just disconnect the client.

Anyway, I have a solution for the urgent problem, the rest waits. Thank you!

**Comment by achow101** [comment]
> Basically mempool electrs v3.0.0 in combination with Bitcoin Core v28.0 kill each other once Bitcoin core stops IBS and mempool load

I'm not observing any RPC issues yet with https://github.com/mempool/electrs/commit/055aba1e8d0d8f4cf7080014c89e3b3055e3d0b7, except for it not handling xor'd blocks, but that's a different problem.

>  However this arg is undocumented.

It's in the help for `getblockchaininfo`, and also in the release notes.

> Bitcoin Core still crashes right after loading the mempool txes

That sounds like it's independent of electrs, and of the RPC issue. Can you open a new issue for that and post the debug.log?

**Comment by dr-orlovsky** [comment]
I just attached a screenshot to my previous comment: systemd restarts the node, and reports its crash:

```
Oct 06 17:54:18 core bitcoind[16532]: 2024-10-06T17:54:18Z initload thread exit
Oct 06 17:55:43 core systemd[1]: bitcoind.service: A process of this unit has been killed by the OOM killer.
░░ Subject: A process of bitcoind.service unit has been killed by the OOM killer.
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A process of unit @UNIT has been killed by the Linux kernel out-of-memory (OOM)
░░ killer logic. This usually indicates that the system is low on memory and that
░░ memory needed to be freed. A process associated with bitcoind.service has been determined
░░ as the best process to terminate and has been forcibly terminated by the
░░ kernel.
░░ 
░░ Note that the memory pressure might or might not have been caused by bitcoind.service.
Oct 06 17:55:43 core systemd[1]: bitcoind.service: Main process exited, code=killed, status=9/KILL
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit bitcoind.service has exited.
░░ 
░░ The process' exit code is 'killed' and its exit status is 9.
Oct 06 17:55:43 core systemd[1]: bitcoind.service: Failed with result 'oom-kill'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitcoind.service has entered the 'failed' state with result 'oom-kill'.
Oct 06 17:55:43 core systemd[1]: bitcoind.service: Consumed 3min 18.749s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit bitcoind.service completed and consumed the indicated resources.
Oct 06 17:55:43 core systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ Automatic restarting of the unit bitcoind.service has been scheduled, as the result for
```

**Comment by achow101** [comment]
> Seems bitcoin core tries to allocate a lot of memory invalidly reading RPC data.

Do you know which RPC it is using that's causing the memory allocation? If you turn on `debug=rpc`, it will be logged in the debug.log.

This sounds like it could be related to #24542 but that should've been fixed by #30094 which is in this release.

Were previous releases working on this machine?

**Comment by dr-orlovsky** [comment]
@achow101 created issue as requested: https://github.com/bitcoin/bitcoin/issues/31041

Will add RPC info with `debug=rpc` there

**Comment by fanquake** [comment]
Going to leave this open a little longer to see if anything else comes up that might warrant a backport or other action.

**Comment by fanquake** [comment]
Possibly relevant: https://github.com/mempool/electrs/issues/102.

**Comment by fanquake** [comment]
Closing this now. Anything left to do can be tracked in individual issues. A number of things have been merged / resolved downstream. It looks like some wont be, i.e https://github.com/vansergen/rpc-bitcoin/pull/65, but that package in particular is essentially unmaintained at this point.
