### ISSUE TITLE
macOS 15.0.1 can't build Qt (Intel, without Xcode)

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#31054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

`make` in `depends` fails

This is very recent, will try to find an earlier commit where it works.

### Expected behaviour

To work.

### Steps to reproduce

```
cd depends
make NO_WALLET=1 NO_UPNP=1 NO_ZMQ=1 
```

### Relevant log output

```
...
Configuring qt...
Creating qmake...
In file included from /Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/qmake/main.cpp:30:
In file included from /Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/qmake/project.h:32:
In file included from /Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/qmake/library/qmakeevaluator.h:36:
In file included from /Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/qmake/library/qmakeparser.h:32:
In file included from /Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/qmake/library/qmake_global.h:32:
In file included from /Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/include/QtCore/qglobal.h:1:
/Users/sjors/dev/bitcoin2/depends/work/build/x86_64-apple-darwin24.0.0/qt/5.15.14-3f2e53999e5/qtbase/include/QtCore/../../src/corelib/global/qglobal.h:45:12: fatal error: 'type_traits' file not found
   45 | #  include <type_traits>
      |            ^~~~~~~~~~~~~
1 error generated.
make[1]: *** [main.o] Error 1
make: *** [/Users/sjors/dev/bitcoin2/depends/x86_64-apple-darwin24.0.0/.qt_stamp_configured] Error 2
```

I also still get https://github.com/bitcoin/bitcoin/issues/30978, in case that's related.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@62e4516722115c2d5aeb6c197abc73ca7c078b23

### Operating system and version

macOS 15.0.1

```
clang --version
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: x86_64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
xcode-select -p
/Library/Developer/CommandLineTools
```

### Machine specifications

Intel MBP from 2019.

**Comment by Sjors** [comment]
It happens even on d71ac768424333b65a6d88c9752cc9c7fdb276f3, so it's not a recent change in the code. Will try some variations with Xcode, etc.

**Comment by Sjors** [comment]
When I install XCode 16 and build depends for master @ 62e4516722115c2d5aeb6c197abc73ca7c078b23 it's happy.

`brew install llvm` (currently at 19.1.1) does not help. I used:

```
export PATH="$(brew --prefix llvm)/bin:$PATH"
export LDFLAGS="-L$(brew --prefix llvm)/lib"
export CPPFLAGS="-I$(brew --prefix llvm)/include"
```

Doesn't work on d71ac768424333b65a6d88c9752cc9c7fdb276f3 either.

I went back as far as ef20add4c98674183720d9631ac780f9a248b487 and still getting this error. 

I always had Xcode installed on that machine, so it's possible I just never noticed it. But it's also possible this machine is just in a weird state.

**Comment by hebasto** [comment]
I cannot neither confirm nor reproduce the issue on my MacBook Pro (2019, Intel).

The following scenarios were tested:
- Sonoma 14.6.1 + Command-Line Tools 15.0.
- Sonoma 14.7 + Command-Line Tools 16.0.
- Sequoia 15.0.1 + Command-Line Tools 16.0.
- Sequoia 15.0.1 + Xcode 16.0.
- Sequoia 15.0.1 + Xcode 16.0 installed and then deleted.

For all scenarios, here is the list of the installed Homebrew's packages:
```
% brew list
==> Formulae
cmake		pkg-config

==> Casks
```

> But it's also possible this machine is just in a weird state.

It seems like that.

Did you try to reinstall command-line tools?

**Comment by Sjors** [comment]
Going to close this for now, since you can't reproduce on Intel.
