### ISSUE TITLE
Bitcoin Core "not opened" after software update to macOS  Sequoia 15.0.1 (24A348)

### ISSUE THREAD

**Issue by diivvy** [bitcoin/bitcoin#31069]
Hello, 
I have a macbook pro 2021 (1 TB) and this has been my primary device to store my bitcoins. I had downloaded bitcoin core wallet on this mac about 2-3 years ago ( I don't exactly remember when). It was working fine all this while but after this new mac update to Sequoia 15.0.1, I am unable to see the bitcoin core wallet on my mac. I can't see it on the "applications" or in the "finder" or in the "launchpad" of my mac. 

I can see that the storage is still occupied in my mac worth about 720 GB and I don't have any other applications on this mac so it is somewhere on my mac. 

I contacted Apple Support and they told me to make a backup of my mac. They tried everything on their end and they couldn't find why the application is not showing. They told me that "it might not be compatible with the new macOS, so contact the application developer". 

Now since there is no "About us" on the bitcoin core page or anywhere, my option is to ask for help over here. Please if somebody can look into this and help me out. I had all of my life savings in this application. 

Update: It gives me an error called "bitcoin core: not opened" .

**Comment by Troy-ling** [comment]
Hey there @diivvy !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **BTCC7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Bitcoin Core coin Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by Julietnacy** [comment]
@diivvy If your Bitcoin Core wallet is still taking up space but isn’t showing up,Try downloading and reinstalling Bitcoin Core from the official site. It might detect your existing data.

**Comment by hebasto** [comment]
@diivvy 

Before taking any further action, ensure that your wallet file(s) are properly backed up. If you were using the default settings, they reside in the [data directory](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).

**Comment by sweep-the-lotus** [comment]
I also have had difficulty finding my Bitcoin folder- I did this : open a terminal type.     cd ~/Library
then if you type ls you will see the Application Support folder.  type   cd "Application Support"
that will put you inside the Application Support folder or directory, type.  ls   ,you should then see the Bitcoin folder ( directory ).   type   cd  Bitcoin  you will now be inside the Bitcoin folder you will now have 
access to your files.   Unix and Linux  you need to put " " when there is a space between 2 words.
hope that helps  from there you can use other simple commands  to copy or move your files or folders
to another folder that you could access more easily ie to back up to an external drive your wallet.
cd ~/Library
cd "Application Support"
cd Bitcoin
ls    to see whats inside

**Comment by sweep-the-lotus** [comment]
there is an easier way ,  found this at stackexchange :   

"On the new Mac OS X you can't see the Bitcoin folder in the library under /application support/. You have to use Finder and in the menu look for GO and then GO TO type ~/Library in the box. After that you can see the Bitcoin folder under /application support/. "  so open a folder and in the right hand upper corner click on the magnifing glass ie  search and paste in or type      ~/Library     hit enter
from there it will beclear what to do by following the above directions from stackexchange

**Comment by diivvy** [comment]
Okay so I have figured out that bitcoin core doesn't work with the macbook's latest software update. So backing up my data and transferring it to another mac with an older software version should load the wallet along with the funds right?

**Comment by diivvy** [comment]
@hebasto Could you check if there is any version of bitcoin core that works with macOS 15.0.1 Sequoia? I tried version 28 and it gives me the "Bitcoin core 'not opened' " error. Contacted Apple regarding this, they said there's nothing they can do. Contact the application devs to ask or check for an update.

**Comment by Julietnacy** [comment]
@diivvy Yes, transferring your data to another Mac with an older software version should help you load the wallet along with the funds. Just make sure to back up all your wallet data carefully before making the transfer. This should include your wallet.dat file and any other relevant data. Once transferred, you should be able to access your wallet and funds on the older Mac.

**Comment by diivvy** [comment]
@Julietnacy Great, I have ordered a new mac and I'll write a final note if it is all successfully completed. Appreciate the info!

**Comment by Julietnacy** [comment]
@diivvy Good luck with the setup, and feel free to share a final note once everything’s up and running! Appreciate you keeping me in the loop. 😊

**Comment by achow101** [comment]
Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. General bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on Libera Chat.

**Comment by achow101** [comment]
Highly likely this is related to MacOS notarization requirements. See #15774

**Comment by jonatack** [comment]
@diivvy I am running current Bitcoin Core with macOS 15.0.1 without issues. I can see the wallets via either the Finder or the command line (i.e. with Terminal, iTerm2, etc.)

**Comment by diivvy** [comment]
@jonatack which version of bitcoin core are you using?

**Comment by Sjors** [comment]
@sipa afaik self-signing should only be needed for the tar download, which has bitcoind, bitcoin-qt, etc. It should not be needed for the main zip release. I'm also unable to start the downloaded version on my new M4 mac. Looks like #15774 got a lot worse as of macOS 15.1.

The way to work around it now is to go to Security Settings. It will show you Bitcoin Core was blocked from starting, and you can click Open Anyway. This really requires being careful about how you go the binary obviously.
