### ISSUE TITLE
Please....Big Noob here..(this right place?)

### ISSUE THREAD

**Issue by DpTheSaint** [bitcoin/bitcoin#31075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

 Hello, Big noob here. I appreciate you taking the time to read this. I have tried scouring the internet including Github for issues similar to what I am experiencing while Syncing The blockchain on my Host Machine. This is not my first time syncing Core to my Pc, but it is the first time I'm experiencing an issue. The same issue arises both on my Linux OS (same machine) and on my Windows OS. Somewhere in the early stages of syncing (Progress %3.68) i get an error called : System error while flushing: Fatal LevelDB error: Corruption: Block checksum mismatch: C:\users\amazi\appdata\local\bitcoin\chainstate\001325.ldb

### Expected behaviour

I expected to be able to to sync the blockchain without any errors, especially early in. it doesn't happen right away but it does happen.

### Steps to reproduce

I just downloaded the Bitcoin Core 28.0 Version and verified Via Gpg keys for matching hash, then proceeded to sync with bitcoin-qt GUI on windows.

### Relevant log output

2024-10-11T23:13:01Z UpdateTip: new best=00000000000000003563a19a8a0d96a2ca0bf6bb7b4e4ac9df94eab68ba22b56 height=304711 version=0x00000002 log2_work=79.042624 tx=40297150 date='2014-06-07T21:28:52Z' progress=0.036862 cache=716.4MiB(5836705txo)
2024-10-11T23:13:03Z Fatal LevelDB error: Corruption: block checksum mismatch: C:\Users\amazi\AppData\Local\Bitcoin\chainstate/001325.ldb
2024-10-11T23:13:03Z You can use -debug=leveldb to get more complete diagnostic messages
2024-10-11T23:13:03Z [error] A fatal internal error occurred, see debug.log for details: System error while flushing: Fatal LevelDB error: Corruption: block checksum mismatch: C:\Users\amazi\AppData\Local\Bitcoin\chainstate/001325.ldb

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

28.0

### Operating system and version

windows 11, 64bit

### Machine specifications

11th gen Intel core i7-11700k @ 3.60 ghz
32 gig ram 

dx12

3070ti 

windows 11, 64 bit

**Comment by DpTheSaint** [comment]
i got another popup when i tried to exit QT.

Microsoft Visual C++ Runtime Library:

Assertion failed!
Program c:\Program Files\Bitcoin\bitcoin-qt.exe
file: txdb.cpp
Line: 105

expression: old_heads[0] == hashBlock

for information on how your program can cause an assertion failure, see the visual c++ docs

not sure if this is relevant but thought i'd share it . it popped up after the original error pop-up.

**Comment by DpTheSaint** [comment]
Tried again, This time when i exited i didn't get the Microsoft Visual C++ Error but it still gave me Fatal leveldb error, but this time instead of 001325, it was 001355, not the same block, why is this happening?

**Comment by DpTheSaint** [comment]
hmm running with 1 ram stick appears to have fixed the issue........ what a pain in the a@#

**Comment by achow101** [comment]
Bitcoin Core makes heavy use of CPU, RAM and disk IO. Hardware defects might only become visible when running Bitcoin Core. You might want to check your hardware for defects.

* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206
