### ISSUE TITLE
Tx blockout

### ISSUE THREAD

**Issue by paboum** [bitcoin/bitcoin#31077]
### Please describe the feature you'd like to see added.

Maybe it's silly, but I suppose Bitcoin protocol could introduce via soft fork a possibility (a new script opcode) for specifying that the new transaction should either be mined in block number less than X or void (X is an user-defined value). Miners could, perhaps, demand more fee for X values significantly larger than the current block number.

I understand this would be a huge change in blockchain whatsoever and expect complex analysis before even discussing technical implementation. Also I believe such idea should have been discussed before, just couldn't find it myself.

### Describe the solution you'd like

I observe huge amounts (80 vMB most of the time) of transactions in mempool that have no more than 5 sat/vB fee included. This feature could probably lead to flushing that out.

Another benefit would be for users that buy something online and are presented with time-limited PoS forms where they're supposed to transfer funds in e.g. 60 minutes or purchase is cancelled. Since users try to set minimal tx fee, sometimes it just doesn't suffice to wait for 6 blocks. In such case, instead of replace-by-fee, it would better suit them to have such transaction simply void.

### Describe any alternatives you've considered

Just leave it as it is or mark ticket as duplicate.

### Please leave any additional context

Blockout is a puzzle video game, published in 1989 by California Dreams, developed in Poland by Aleksander Ustaszewski and Mirosław Zabłocki. The term is also a portmanteau of words "timeout" and "block", obviously.

**Comment by pinheadmz** [comment]
See relevant discussions:

https://delvingbitcoin.org/t/op-checkmaxtimeverify/581/8

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-October/022042.html


I'm going to close this issue since it is not relevant to bitcoin core as a software project. Protocol ideas like this are better expressed on the mailing list or Delving.
