### ISSUE TITLE
Why does `submitpackage` require at least two transactions

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#31085]
### Please describe the feature you'd like to see added.

I want to call `submitpackage` and I don't want to have to check if I have more than one transaction to do it. I'm lazy but that restriction seems arbitrary.

**Comment by ismaelsadeeq** [comment]
It won't hurt to broadcast a single transaction if it passes consensus and policy checks via `submitpackage` RPC.

From the [package relay BIP](https://github.com/bitcoin/bips/blob/632f143fadaed8c91bba12d096e62feb2a308054/bip-0331.mediawiki#definitions) and the [policy documentation](https://github.com/bitcoin/bitcoin/blob/master/doc/policy/packages.md), I see that a package is defined as a child transaction with its unconfirmed ancestors, topologically sorted.

I think the intent of the check is to be strict and ensure that what's being broadcast is a package.
As such RPC behavior is correct, as an individual transaction doesn't qualify as a package based on this definition.

**Comment by stickies-v** [comment]
> I want to call `submitpackage` and I don't want to have to check if I have more than one transaction to do it. I'm lazy but that restriction seems arbitrary.

I had similar thoughts when reviewing `submitpackage` a while ago. Forcing the user to use different RPCs based on the number of transactions in a package feels arbitrary and not ergonomic to me. A package with size 1 should be a valid package and accepted as such in the relevant RPCs (slowly obsoleting their single-tx alternatives over time, but that's a different discussion).

> I see that a package is defined as a child transaction with its unconfirmed ancestors, topologically sorted.

A tx without unconfirmed ancestors would make for a valid package according to that definition. though.

**Comment by instagibbs** [comment]
I think it's reasonable to support. I'll take a look.

**Comment by instagibbs** [comment]
Opened #31096
