### ISSUE TITLE
Building libsecp256k1 fails on OpenBSD 7.6

### ISSUE THREAD

**Issue by davemiketony** [bitcoin/bitcoin#31106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Building libsecp256k1 by following the instructions located within `src/secp256k1` fails on OpenBSD 7.6 (the latest OpenBSD release).

The instructions fail during the autogen step with errors mentioning libtool.

### Expected behaviour

A successful build of a libsecp256k1 is possible by strictly following the instructions found within `src/secp256k1/README.md`.

### Steps to reproduce

```
$ export AUTOCONF_VERSION=2.72
$ export AUTOMAKE_VERSION=1.16
$ ./autogen.sh
```

### Relevant log output

Failure Output
```
$ ./autogen.sh                                                                       
Makefile.am:7: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:7:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:7:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:7:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:7:   its definition is in aclocal's search path.
autoreconf-2.72: error: automake failed with exit status: 1
```
Installed Packages
```
$ pkg_info -m
autoconf-2.72p0     automatically configure source code on many Un*x platforms
automake-1.16.5     GNU Standards-compliant Makefile generator
bash-5.2.32         GNU Bourne Again Shell
boost-1.84.0p4v0    free peer-reviewed portable C++ source libraries
cmake-3.30.1v1      portable build system
git-2.46.1          distributed version control system
gmake-4.4.1         GNU make
gtar-1.35p0         GNU version of the traditional tape archiver
libevent-2.1.12p1   event notification library
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v28.0

### Operating system and version

OpenBSD 7.6 amd64

**Comment by hebasto** [comment]
> ### Expected behaviour
> 
> A successful build of a libsecp256k1 is possible by strictly following the instructions found within `src/secp256k1/README.md`.

I think you should move this issue upstream to https://github.com/bitcoin-core/secp256k1/issues.

**Comment by hebasto** [comment]
Also try:
```
pkg_add libtool
```

**Comment by fanquake** [comment]
Yes, please move this upstream. Building libsecp standalone isn't supported inside this repository.
