### ISSUE TITLE
Using multiple wallet files with bitcoind

### ISSUE THREAD

**Issue by ISibboI** [bitcoin/bitcoin#3113]
It should be possible to make bitcoind use multiple different wallet files without having to restart, so that public and private eWallet services don't have to put everything into one big bucket. Especially for private eWallets, that'd be useful, because you can easily seperate which coins belong to which person without having to use a DB or something like that.

**Comment by luke-jr** [comment]
Implemented in #8694 (but note that it is NOT a good practice to use multiple wallets for each user in an eWallet setting)

**Comment by markasoftware** [comment]
@luke-jr what makes it bad to use a separate wallet for each user in a web wallet?
