### ISSUE TITLE
net: Tor service target port collides when running multiple nodes, making bitcoind error out

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#31133]
Various people have reported this on IRC after the 28.0 release, but have not created a GH issue, so i'm creating one.

To be able to distinguish incoming localhost connections from connections on the Tor hidden (onion) service, we automatically create a separate "Tor service target" P2P port. This port is always opened, even if `-listenonion=0`, because the user might manually configure a Tor hidden service and wants the same behavior.

[DefaultOnionServiceTarget()](https://github.com/bitcoin/bitcoin/blob/master/src/torcontrol.cpp#L714) creates the CService for the Tor service target port. This number is fixed in the chainparams to [8334](https://github.com/bitcoin/bitcoin/blob/master/src/chainparamsbase.cpp#L44) for mainnet, on localhost.

Normally, this is no problem. However a common scenario is to run multiple bitcoin nodes on one machine (usually for testing) with different P2P and RPC ports. In this case, they will all try to bind to port 8334 and the latter ones will fail. This problem has existed since the Tor service port was introduced, however it became visible in v0.28 with #22729. After that PR it becomes a crash issue.
(it *was* a problem before because multiple `bitcoind` instances would try to bind on port `8334` while ignoring failures, but still have the wrong internal knowledge that they bound on port 8334, passing this to Tor. So all of Tor's connections would go to the first node)

*The current suggested workaround* is to manually set `-bind=...`. This removes the automatic onion binds (although explicit `-bind=.....=onion` can be used to create new ones). i have tagged this issue with milestone 28.1 as it could be considered a regression and would be nice to have this automatically work again (especially in cases where the user doesn't care  about Tor, like in regtest harnesses).

Various ideas to resolve this have been discussed, among which:

1. Revert #22729: i strongly dislike this, as it would only bury the problem again. Explicit failures are always better than having to debug silent loss of functionality.
2. Instead of hardcoding port 8334, make it `P2P_port + 1`:  When overriding the `-port`, the Tor service target port changes at the same time. This resolves the problem automatically, except in the edge case where the different `bitcoind` instances' P2P ports are specified very closely together (and maybe it's just better to avoid that in the first place).
3. Disable the Tor service port binding when `-listenonion=0`: This avoids the problem when the user doesn't care about Onion binds, however it means that an extra option has to be set, it's still not nice automatic behavior. Might as well set `-bind=` then.
4. Disable the Tor service port binding when `-regtest`: In case of regtest, it's uncommon to care about Tor. However not always; this would interfere with out own tests when we want to test interaction with Tor. It also doesn't solve the issue in case of sigtest/mainnet.

(some more, from @mzumsande in #31134)

5. Do nothing and tell affected users to switch to `-bind` - maybe even deprecate `-port`
6.  if `-port` is given, don't attempt to bind to the default onion port
7. disable the automatic tor binding silently if the port is already used

i personally prefer 2. It keeps the current behavior, except when port is overridden, and doesn't require any special workarounds.

**Comment by fanquake** [comment]
cc @stevenroose

**Comment by mzumsande** [comment]
I do think that keeping `-port` around could be helpful, especially for users less knowledgeable about networking, who aren't sure which address to put in an equivalent `-bind` command.

I also like option 2, provided that the behavior will be well-documented, so that users specifying `-port` values for multiple nodes don't pick consecutive ones by accident (which would then again lead to collisions). Otherwise I don't see a downside.

I would also be ok with option 6, if I specify a port like that I probably wouldn't necessarily expect another bind to a fixed port for onion.

**Comment by Christewart** [comment]
I'm in the camp of deprecating and then removing the `-port` setting. It seems we should should just get people to migrate to bind. Is `-port` strictly a subset of `-bind` functionality? If so it seems simplifying the config options would make sense.

**Comment by mzumsande** [comment]
I opened #31223 to move this forward (it seems to be consensus that we should fix this either now or not at all).

**Comment by mzumsande** [comment]
> (yes, I think it is a subset of bind=, somebody correct me if I am wrong)

As far as I understand it, one difference is that `-bind` disables self-discovery of addresses because `connOptions.bind_on_any` will not be set - whereas `-port` will work together with bind-on-any. So if you want to use `Discover()` together with a non-default port, `-port` is the only option.

**Comment by vasild** [comment]
Right! Looks like for `Discover()` to run `-discover` must be enabled and `-bind` not used. It is tough to explain what a config like `-discover=1 -bind=1.2.3.4:5555` would do. Seems that this is another thing that can be simplified.

Also, this has another flaw: `bind_on_any` will be `false` if `-bind=0.0.0.0:5555` is used, but it should really be `true` :-/

**Comment by mzumsande** [comment]
> Also, this has another flaw: `bind_on_any` will be `false` if `-bind=0.0.0.0:5555` is used, but it should really be `true` :-/

I agree, setting `bind_on_any` (and thus making `Discover()` possible unless disabled) if the user specified bind-on-all explicitly via `-bind=0.0.0.0` seems like a bug that should be fixed in master, regardless of this issue.

**Comment by vasild** [comment]
Opened https://github.com/bitcoin/bitcoin/issues/31293 just that we don't forget about it.
