### ISSUE TITLE
Stop at header

### ISSUE THREAD

**Issue by carnhofdaki** [bitcoin/bitcoin#31162]
### Please describe the feature you'd like to see added.

While preparing the little ter.gz file for https://github.com/fjahr/test_chain_init/issues/1 I stumbled upon the fact that one is unable to download just a couple of blocks in the beginning without synchronizing the full header chain.

I would be happy if the `stopatheight` option was respected also header-wise. This is a feature request.

Using 28.0 x86_64 Linux release binaries from bitcoincore.org

```
$ bitcoind -help -help-debug | grep -A 2 stopatheight
  -stopatheight
       Stop running after reaching the given height in the main chain (default:
       0)
```

Version tested:

```
 bitcoind -version
Bitcoin Core version v28.0.0
Copyright (C) 2009-2024 The Bitcoin Core developers

Please contribute if you find Bitcoin Core useful. Visit
<https://bitcoincore.org/> for further information about the software.
The source code is available from <https://github.com/bitcoin/bitcoin>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>
```

Thank you!

**Comment by mzumsande** [comment]
For what would you need to use this kind of feature? This probably wouldn't be as simple to implement as current `-stopatheight` (one would need to keep downloading blocks after the last header was received but not accept any more headers), so I think that there should be a serious use case.

**Comment by carnhofdaki** [comment]
Thank you @maflcko ! The `minimumchainwork=0` does exactly what I was looking for.

Closing as solved.
