### ISSUE TITLE
`Wunused-member-function` in test each commit

### ISSUE THREAD

**Issue by sr-gi** [bitcoin/bitcoin#31180]
#31045 introduced `-werror` to test each commit, which makes things like `Wunused-member-function` an error now. 

This feels pretty aggressive in the cases where some methods may be defined in isolation in commit A, and then used elsewhere in commit B (following A).

**Comment by jonatack** [comment]
As a reviewer, my preference is for the member or method to be used in the commit where it is added. This helps to more easily understand why it was added, and aids in reviewing the change without needing to flip repeatedly between the commits or git rebasing to squash them together.

**Comment by sr-gi** [comment]
> It may be trivial to suppress either way by using https://en.cppreference.com/w/cpp/language/attributes/maybe_unused in the commit?
> 
> It should also be trivial to remove the error completely from the CI task by specifying `Wno-error=unused-member-function`?

Agreed on both. The purpose of the issue was mostly to agree on what the expectations are for methods that may be used within the same PR but not within the commit they were defined in.

Will open a PR adding `Wno-error=unused-member-function` to test each commit and see if there is consensus on this
