### ISSUE TITLE
Adding an Interactive RPC Client.

### ISSUE THREAD

**Issue by super3** [bitcoin/bitcoin#3122]
Just trying to fork off the discussion from #3082. Seems like the is an interest for an RPC client with "like tab completion, and inline help, and batch processing, and pipelines of queries, etc"

My biased vote goes toward building it with Python, because there are plenty of existing libs for that. Would the script in contrib/bitrpc/ be a good start?

Other questions involve feature set, and how to manage the executable. I've leave those for discussion though.

**Comment by laanwj** [comment]
@super3 This issue has been open for more than a year. Do you still intend to work on this? If no, please close it.
