### ISSUE TITLE
depends build fails - libevent not in CMakeLists

### ISSUE THREAD

**Issue by techy2** [bitcoin/bitcoin#31299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

CMake Error: The source directory "/master/gitrepo/bitcoin/depends/work/build/x86_64-pc-linux-gnu/libevent/2.1.12-stable-9d8e3ddea5c/build" does not appear to contain CMakeLists.txt.

### Expected behaviour

expect it to build

### Steps to reproduce

git clone https://github.com/bitcoin/bitcoin
cd bitcoin
git checkout v28.0
cd depends
make

### Relevant log output

/master/gitrepo/bitcoin/depends/work/download/libevent-2.1.12-stable/libevent-2.1.12-stable.tar.gz.temp: OK
Extracting libevent...
/master/gitrepo/bitcoin/depends/sources/libevent-2.1.12-stable.tar.gz: OK
Preprocessing libevent...
patching file CMakeLists.txt
patching file cmake/AddEventLibrary.cmake
patching file CMakeLists.txt
Configuring libevent...
CMake Error: The source directory "/master/gitrepo/bitcoin/depends/work/build/x86_64-pc-linux-gnu/libevent/2.1.12-stable-9d8e3ddea5c/build" does not appear to contain CMakeLists.txt.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v28.0

### Operating system and version

ubuntu 18.04

### Machine specifications

model name      : Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz x2
2T disk
128M ram

cmake version 3.10.2
gcc version 10.3.0
g++ version 10.3.0

**Comment by techy2** [comment]
that's 128 G ram

**Comment by hebasto** [comment]
> cmake version 3.10.2

This CMake version does not understand the `-S` and `-B` command line options, which were introduced in the version 3.13.

@techy2 

You can download CMake 3.22 or newer, which is required for the main build system, from https://cmake.org/download/.

**Comment by techy2** [comment]
installed 3.22, works now
Thank you
