### ISSUE TITLE
ci: how to run native arm job on Apple silicon?

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#31344]
I'm trying to run the `arm64` worker job (ARM, unit tests, no functional tests) on my M4 mac, because that should be lot faster than emulating it in Qemu on my x86_64 machine.

Unfortunately so far it fails:

```
[10:34:36.739] Test project /ci_container_base/ci/scratch/build-arm-linux-gnueabihf
[10:34:36.742]         Start   2: util_rpcauth_test
[10:34:36.744]         Start   4: univalue_object_test
[10:34:36.747]         Start   6: secp256k1_tests
[10:34:36.751]         Start   8: test_bitcoin-qt
[10:34:36.754]         Start  10: addrman_tests
[10:34:36.756]   2/141 Test   #4: univalue_object_test .................***Failed    0.01 sec
[10:34:36.756] /ci_container_base/ci/scratch/build-arm-linux-gnueabihf/src/univalue/object: 1: Syntax error: word unexpected (expecting ")")
[10:34:36.756] 
[10:34:36.769]   9/141 Test   #2: util_rpcauth_test ....................   Passed    0.03 sec
[10:34:36.888]  10/141 Test   #1: util_test_runner .....................***Failed    0.15 sec
[10:34:36.888] 2024-11-22 10:34:36,767 - ERROR - OSError, Failed to execute /ci_container_base/ci/scratch/build-arm-linux-gnueabihf/src/bitcoin-util 
```

https://cirrus-ci.com/task/4863394807808000

This is running https://github.com/Sjors/bitcoin/pull/67 which is based on master @ 2638fdb4f934be96b7c798dbac38ea5ab8a6374a.

My current setup:
* MacBook Pro with M4 Pro chip
* UTM to run a VM: https://mac.getutm.app
* Ubuntu Server 24.0.1 for ARM: https://ubuntu.com/download/server/arm
* UTM machine settings:
  * ARM64 (aarch64)
  * System: QEMU 7.2 ARM virt-8.2
  * 14 GB RAM
  * 10 CPU cores
  * haven't touched other default settings

For `.cirrus.yaml` I use:

```yaml
name: MBP24-I
token: ...

labels:
  type: arm64
```

I start the worker with:

```sh
RESTART_CI_DOCKER_BEFORE_RUN=1 cirrus worker run -f ~/.cirrus.yaml
```

I also tried running the cirrus worker outside a VM, with `cirrus` installed via Homebrew. For setup that I used Podman Desktop with the Docker extension.

It fails with the same error. Here's the log for that:

https://cirrus-ci.com/task/4838331626815488

For comparison here's the same job (still) running on x86_64 with qemu:

https://cirrus-ci.com/task/4837454681735168

**Comment by l0rinc** [comment]
Not sure it helps, but I have tried reproducing it on my M4 Max, emulating an s390x platform (as I've done in https://github.com/bitcoin/bitcoin/pull/31144#issuecomment-2453108430) - while it's still very (very) slow:

<details>
<summary>docker setup</summary>

```bash
brew install podman pigz
softwareupdate --install-rosetta
podman machine init
podman machine start
docker run --platform linux/s390x -it ubuntu:22.04 /bin/bash
```

</details>

```bash
apt update && apt install -y git build-essential cmake ccache pkg-config libevent-dev libboost-dev libssl-dev libsqlite3-dev python3 && \
cd /mnt && git clone https://github.com/bitcoin/bitcoin.git && cd bitcoin && git remote add Sjors https://github.com/Sjors/bitcoin.git && git fetch --all && git checkout sv2-transport && \
cmake -B build -DBUILD_TESTS=ON && cmake --build build --target test_bitcoin -j$(nproc) && \
ctest --test-dir build -j$(nproc)
```

I think I've reproduced the error you got:
```bash
...
 util_test_runner .....................***Failed
...
96% tests passed, 5 tests failed out of 136

Total Test time (real) = 278.88 sec

The following tests FAILED:
          1 - univalue_test (Not Run)
          2 - univalue_object_test (Not Run)
          3 - secp256k1_noverify_tests (Not Run)
          4 - secp256k1_tests (Not Run)
          5 - secp256k1_exhaustive_tests (Not Run)
```

Maybe it's easier to debug this way.

**Comment by Sjors** [comment]
> It is not possible to run 32-bit arm binaries on a CPU that only supports 64-bit mode.

Ah, in that case it's probably pointless for a performance improvement.

> select qemu-arm in UTM. (Is there a reason why you haven't done this in the first place?)

My initial goal for that Ubuntu VM was to make Guix builds.

I could spin up a separate machine in 32 bit mode, but that seems like a world of pain on its own. Closing for now.

**Comment by Sjors** [comment]
I guess my confusion came from the use of `arm64` as the label for cirrus.

**Comment by Sjors** [comment]
> It was also intentionally selected to support 32-bit mode. 

That's useful to know.
