### ISSUE TITLE
Automatic filter should be delayed until input is paused

### ISSUE THREAD

**Issue by kroese** [bitcoin/bitcoin#3141]
When searching for transactions, the grid begins to query the database while typing, which is fine. But when using very large wallets, this will freeze the interface so much that it becomes impossible to finish typing. Adding a very small delay would solve this issue, since it would allow me to finish my input before the client freezes.

For example, when I try to look up transactions greater than 999 BTC, it will first start searching for all transactions > 9 BTC, and then > 99 BTC, and finally 999 BTC, even though I'm typing 999 as fast as I possibly can.

**Comment by jonasschnelli** [comment]
Solved by #11015. Closing.
