### ISSUE TITLE
Bitcoin Core crashes when importing a wallet file

### ISSUE THREAD

**Issue by NexusGKSoftwares** [bitcoin/bitcoin#31505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Bitcoin Core crashes unexpectedly when attempting to import a wallet file. The crash occurs immediately after executing the import command, and no further operations can be performed. The application closes without providing an error message or logs visible in the GUI.

The node stops responding before completing the wallet import process.
The wallet file being imported is valid and works in previous versions of Bitcoin Core.

### Expected behaviour

The wallet file should be imported successfully, and the node should continue functioning normally.

### Steps to reproduce

Start Bitcoin Core version X.X.X.
Attempt to import a wallet file using the GUI or the RPC command (e.g., importwallet <filename>).
Describe exactly what happens, including any error messages (if applicable).

### Relevant log output

Include debug logs from debug.log if available (found in the Bitcoin Core data directory).
If no logs are generated, mention this as well.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

25.0.0

### Operating system and version

Ubuntu 22.04

### Machine specifications

Was it generated by a different Bitcoin version? What format is it in?

**Comment by furszy** [comment]
> The application closes without providing an error message or logs visible in the GUI.

Please open the `debug.log` file in your data directory, check for any error messages, and share them.

**Comment by NexusGKSoftwares** [comment]
i will share them

**Comment by Kjpl0916** [comment]
[72979456999014.pdf](https://github.com/user-attachments/files/18145909/72979456999014.pdf)
