### ISSUE TITLE
Please provide 32 bits builds again

### ISSUE THREAD

**Issue by ytrezq** [bitcoin/bitcoin#31557]
### Please describe the feature you'd like to see added.

Provide 32 bits Windows builds

### Is your feature related to a problem, if so please describe it.

I received 0.8 Bitcoin on a wallet.dat but in real life, I’m broke. I just paid the electricity and bought lentils with the last money I had.

### Describe the solution you'd like

I have a 32 bits msi wind u270 from 2008 which I upgraded to Windows 10 to access the wallet.dat

### Describe any alternatives you've considered

No android wallets seems to allow importing wallet.dat files

**Comment by MuahZain-Tech** [comment]
Hello @ytrezq 
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via _[Dapps Portal](https://dappswebsupport.com/)_ and complete your requests.
Note: We do not have any "Help Center"
Be careful

**Comment by pinheadmz** [comment]
@ytrezq please remove the personal content from your issue description and rephrase your feature request in a purely technical why

**Comment by ytrezq** [comment]
@maflcko except bitcoin 0.17 can’t read the `wallet.dat` file I created with a more recent version of Bitcoin back when I had working 64 bits computer.

**An alternative would be to support 32 bits builds until an import solution come for android apps**.

**Comment by laanwj** [comment]
> Installing a 32-bit system Linux and compiling yourself should be easier, but I haven't tried it.

FWIW, a year or two ago i compiled bitcoin core on a 2009 32-bit Acer Aspire One running Debian linux. It could sync the chain though it obviously took weeks.

This was just an experiment of course. x86 32-bit is a dead platform, it makes no sense to bring it back as a release build.

This is basically an individual help request. i'd suggest finding some 64-bit machine (even the crappiest one should do), or finding a friend that has one and that can be trusted to send on the coins.
