### ISSUE TITLE
Bootstrap new node test

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#3171]
We should have test infrastructure that bootstraps a new node (both on mainnet and on testnet).  People (e.g. myself) have been doing this less formally prior to release, but we should be doing it continuously.

Should also probably test bootstrapping over tor.

Collecting some metrics like time to bootstrap (both to some specified heights as well as to completion) along the way would probably be useful.

**Comment by glaksmono** [comment]
@gmaxwell would like to take a stab on this

1. I presume we don't want to integrate this to travis as it will significantly slow things down?
2. Is there a defined **Release Process** documented? (i.e. step by step documentation on what do you do when releasing a new version to the mainnet)

**Comment by fanquake** [comment]
@glaksmono 
1. Unlikely this is something that would run on Travis.
2. The release process is documented in [release-process.md](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md).

**Comment by glaksmono** [comment]
@fanquake @gmaxwell what were you guys thinking of using for the infrastructure?

**Comment by Sjors** [comment]
I suppose it could be run on volunteer funded paid cloud services? Or, for more representative results, their home computer.

Maybe it could be an optional flag for Gitian builds to do an IBD when the build is finished and collect some stats?

**Comment by glaksmono** [comment]
Sorry, haven't had a chance to work on this. Feel free to take over @tylerdmace

**Comment by tylerdmace** [comment]
Awesome, thank you for letting me know!

**Comment by jamesob** [comment]
I'm currently working on this with @MarcoFalke over at https://github.com/chaincodelabs/bitcoin-perfmonitor, hosted at https://bitcoinperf.com.

We're in the early stages at the moment, but plan on doing nightly benchmarks of master for IBD, reindex, microbenchmarks, and build/test duration. Eventually, we'll allow contributors to kick off benchmark runs for specific PRs to allow easy comparison with master and tagged releases.
