### ISSUE TITLE
Tesetnet ping-ponger test

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#3172]
We should be running a testnet node+wallet on a daily build that performs some kind of stupid ping-pong transactions, both open to the general public as well as self ping-ponging once an hour or so.

This would give a system level test of the RPC interface, listtransactions, sendmany, keeping up with the chain, signing, etc.

It would also give people trying things on testnet something they can transact with, and create some traffic so that fewer blocks are empty.

**Comment by laanwj** [comment]
Is this still relevant?

**Comment by jeffrade** [comment]
`We should be running a testnet node+wallet on a daily build...`

Is the idea to have these "ping-pong" transactions sent from a developer's build when `bitcoind` is running locally with the flag `testnet=1` and introduce a new flag to enable the "ping-pong" transactions?

**Comment by promag** [comment]
@gmaxwell close?

**Comment by MarcoFalke** [comment]
Even though this issue was opened some weeks after regtest was merged (c.f.  #2632), most of this is now covered by our functional tests.

Closing for now. Everyone is free to run such a service on testnet as a personal pet project. No need to keep this issue open any longer.
