### ISSUE TITLE
add checksum to transactions?

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#3181]
In https://bitcointalk.org/index.php?topic=298545.msg3198434#msg3198434, gmaxwell wrote about the danger of sending large numbers of Bitcoins in a single transaction:

> One bitflip while making a transaction with these fat
> txouts and its $10 million in paper value down the drain.

Is this a real concern?  If a bit gets flipped when broadcasting a transaction, could it cause the transacted coins to become unspendable forever?

If so, would it be better if transactions contained a checksum, much like bitcoin addresses do, such that random bitflips are detectable?

**Comment by promag** [comment]
Some many bitflips can happen.. Isn't the txid *almost* the transaction checksum?

> someone puts 100k btc in a single coin and then makes a bunch of small payments with ~100k change each time. It's taking a small but unnecessary risk to move huge amounts of coins when the actual amount being moved is small.

What do you suggest then? Warn the user if the input/(output-change) ratio is too high (even with coin selection)?

**Comment by MarcoFalke** [comment]
If I understand this issue correct, it is about bitflips in *outputs*, so nValue or scriptPubKey.

The wallet, as well as the rpc should reject absurdly high fees, so at least a bit flip in a higher bit of nValue is checked by Bitcoin Core.

For the other cases I don't see how Bitcoin Core can prevent them from happening. The best solution would be to store the address/value pairs and verify them when the signed transaction comes back?

The GUI does this by showing each address/value pair.
For the RPC, I think the end user has to implement this, so closing for now unless there are specific improvements to take.
