### ISSUE TITLE
getreceivedbyaddress and listreceivedbyaddress inconsistent when dealing with multisignature addresses

### ISSUE THREAD

**Issue by ThePiachu** [bitcoin/bitcoin#3217]
Calling listreceivedbyaddress I receive:

{
  "result": [
    {
      "address": "2NAdAGFnhk5qvFQNiFVMNuK59QzPLvn3zAv",
      "account": "MultiTest1",
      "amount": 1.0,
      "confirmations": 1
    }
  ],
  "error": null,
  "id": "1"
}

Calling getreceivedbyaddress (2NAdAGFnhk5qvFQNiFVMNuK59QzPLvn3zAv), I get

{
  "result": 0.0,
  "error": null,
  "id": "1"
}

Those two functions should return similar results but they don't, at least for multisignature addresses.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
