### ISSUE TITLE
Implement deterministic wallets

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#3250]
No need to implement full support for BIP0032, but key generation using the private derivation should be the default.

I'm sick and tired of worrying about backup up after enough keys have been used (and reading stories about people that lose their coins because of that), and the consensus seems to be against #2841 (noautofillkeypool), so let's do this.

**Comment by rnicoll** [comment]
I presume there's still no-one working on this? Looking at tackling this later in the year, if anyone is working on HD wallets in Core please let me know so we're not duplicating effort. I'm aware a fair chunk of the code is already in place.

**Comment by jonasschnelli** [comment]
Some weeks ago i pushed a PR for the current master that enables HD for the existing wallet: https://github.com/bitcoin/bitcoin/pull/6265

I'm also completely rewriting the wallet and soon also the UI level:
https://github.com/jonasschnelli/bitcoin

Corewallet aims to be a counterweight against the current wallet movement towards "SPV" and "Web-Centralized" solutions. If we can download 6GB movies over iTunes and play CPU/GPU intensive 3D games we can also run a full node (pruned) on a standard computer. It's just a matter of user-friendliness (by throttling bandwidth and cpu usage).

At the moment it's *experimental*, thought, you can use it in parallel to the existing wallet.
Main features:
- Multiwallet support (**implemented**)
- Flexible RPC parameterizing (**implemented**)
- HD wallets with support for multiple bip32 chains per wallet (**implemented**)
- Append only filestore, separated files for private keys and wtx/pubkey (**implemented**)
- HDM (in progress)

**Comment by rnicoll** [comment]
@jonasschnelli Great - I'll take a more in depth look when I have time (soon, TM)

**Comment by jonasschnelli** [comment]
Probably solved by https://github.com/bitcoin/bitcoin/pull/8035.

**Comment by laanwj** [comment]
Yes, thank you!
