### ISSUE TITLE
[Qt] minor coin control GUI issues

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#3269]
1. Why was there such a strange and different font choosen for displaying BTC and copyable texts in the coin control address selection window?
2. Coin control address selection window doesn't catch up (on the fly) when changing display unit in the options.
3. IMHO there should be an easier way to set mode back to automatic coin selection, whithout the need to leave sendcoins and switch to coin control address selection window and choose unselect there.

**Comment by MarcoFalke** [comment]
Closing per discussion. Please open a new issue if any of the problems are still there.
