### ISSUE TITLE
getrawtransaction fails/behaves differently on command line and rpc

### ISSUE THREAD

**Issue by arnuschky** [bitcoin/bitcoin#3298]
Hey,

what I am trying to do it pretty simple: poll for new, unconfirmed transactions and stick them into a database. My problem is that sometimes, I can't get the raw transaction using the getrawtransaction RPC call. This is the error:

    {u'message': u'No information available about transaction', u'code': -5}

I am running  bitcoind 0.8.5 with txindex=1 set, and I used reindex for rebulding the db long time ago. I also verified this on two different machines, one mainnet, one testnet.

This happens a few times a day. When it does, it fails continuously for a few minutes for one specific transaction. Some of these transactions have been created by myself, so no chance that they are orphaned. (or is a transaction that uses the input of an orphaned transaction orphaned itself?)

Even if they are orphaned, I do not understand why (sometimes) I cannot retrieve the transaction using the RPC call, while I can get the raw transaction from the command line. Shouldn't use this the same internal calls?

**Comment by laanwj** [comment]
There is not enough information to troubleshoot this, also the report relates to an ancient version, so closing.
