### ISSUE TITLE
Getrawtransaction does not work for genesis block coinbase transaction

### ISSUE THREAD

**Issue by ThePiachu** [bitcoin/bitcoin#3303]
While testing a few things on testnet, I called

getrawtransaction("4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b", 1)

(coinbase for block 0 on testnet3) and got a response of

{'message': 'No information available about transaction', 'code': -5}

Calling

getrawtransaction("f0315ffc38709d70ad5647e22048358dd3745f3ce3874223c80a7c92fab0c8ba", 1)

(coinbase for block 1 on testnet4) gives a response of

{'blockhash': '00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206', 'vout': [{'scriptPubKey': {'reqSigs': 1, 'hex': '21021aeaf2f8638a129a3156fbe7e5ef635226b0bafd495ff03afe2c843d7e3a4b51ac', 'addresses': ['n3GNqMveyvaPvUbH469vDRadqpJMPc84JA'], 'asm': '021aeaf2f8638a129a3156fbe7e5ef635226b0bafd495ff03afe2c843d7e3a4b51 OP_CHECKSIG', 'type': 'pubkey'}, 'value': 50.0, 'n': 0}], 'hex': '01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0e0420e7494d017f062f503253482fffffffff0100f2052a010000002321021aeaf2f8638a129a3156fbe7e5ef635226b0bafd495ff03afe2c843d7e3a4b51ac00000000', 'vin': [{'coinbase': '0420e7494d017f062f503253482f', 'sequence': 4294967295L}], 'txid': 'f0315ffc38709d70ad5647e22048358dd3745f3ce3874223c80a7c92fab0c8ba', 'blocktime': 1296688928, 'version': 1, 'confirmations': 147738, 'time': 1296688928, 'locktime': 0}

Which indicates that getrawtransaction has problems returning genesis block coinbase information. My bitcoind has been set up with -txindex=1 -reindex=1, so it should know all of the transactions.

**Comment by ZKVCRYPTO0022** [comment]
.........do not try, 50 btc per block ,,,,,,to reach 21mill!,,,,which block?

**Comment by h4x3rotab** [comment]
It’s not indexed and thus not included in the coin supply. Even satoshi
can’t spend it

**Comment by ZKVCRYPTO0022** [comment]
Correct, and it will stay like that

Dana četvrtak, 21. veljače 2019. h4x3rotab <notifications@github.com> piše:
