### ISSUE TITLE
Separate directories for blockchain and personal data on multi-user systems

### ISSUE THREAD

**Issue by renne** [bitcoin/bitcoin#3337]
Currently Bitcoin-QT stores personal data (wallet, etc.) and blockchain in a user-specific directory (HOME-directory). Considering size and growth of the blockchain, it makes no sense to store a copy of the blockchain for each user on a multi-user system.

So I suggest to store the blockchain in a system-wide directory shared by all users.

**Comment by MarcoFalke** [comment]
`-blocksdir` is now an option
