### ISSUE TITLE
Confirmed is always true in export file

### ISSUE THREAD

**Issue by kapiteined** [bitcoin/bitcoin#3455]
When using the export function in the transactions tab, the Confirmed status is always set to "true", even when the real status is "unconfirmed"

Example:
In transaction details you see:
Status: 0/unconfirmed
Date: 12/22/13 01:25
To: 15FJt8Upr2AADDQor1uCt8FKUEVxQTNgfp
Debit: -0.062 BTC
Transaction fee: -0.0005 BTC
Net amount: -0.0625 BTC
Transaction ID: 8ef37cd1d9a31a95fe9f0629fc83a16618b19c7ae38d7dde1ccd492b5b73a3b3

And in the csv file you see:
"Confirmed","Date","Type","Label","Address","Amount","ID"
"true","2013-12-22T01:25:53","Sent to","","15FJt8Upr2AADDQor1uCt8FKUEVxQTNgfp","-0.0625","8ef37cd1d9a31a95fe9f0629fc83a16618b19c7ae38d7dde1ccd492b5b73a3b3-000"

Good luck with this issue!

**Comment by laanwj** [comment]
I think the confusion here is that what the "confirmed" column shows is really "does this transaction count toward confirmed balance".

It contains ConfirmedRole for the record, which is `tx.IsTrusted() && !(wtx.GetBlocksToMaturity() > 0)`. What `IsTrusted` does check if the output of the transaction will be spent. This certainly applies to confirmed transactions, but also to, say, unconfirmed transactions that you sent yourself.

Something more concrete like "number of confirms" would probably be more useful for an export format than this internal flag.

**Comment by hebasto** [comment]
I cannot reproduce this bug both on master and on 0.17.0 (even with "Payment to yourself").

**Comment by MarcoFalke** [comment]
What is the status of this? Is it reproducible? Does https://github.com/bitcoin/bitcoin/pull/14988#issuecomment-448247912 fix it?

**Comment by MarcoFalke** [comment]
This one should be fixed. See https://github.com/bitcoin/bitcoin/pull/14988#issuecomment-635970060
