### ISSUE TITLE
Localization and translation issue

### ISSUE THREAD

**Issue by jacwah** [bitcoin/bitcoin#3470]
According to output of `bitcoin-qt --help`, the default language, if none is specified with `--lang` is the "system locale". On my Linux Mint system text erroneously is translated into swedish. It is not in any other program I've ran so far. Here is my output from running `locale`:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

**Comment by Leviathn** [comment]
@jacwah does this issue persist?

**Comment by jacwah** [comment]
@Leviathn It was a long time I reported this, and I don't have the original system any more (nor any other Linux box. I don't know.
