### ISSUE TITLE
build: CLIENT_VERSION etc settings now duplicated in two places

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#3539]
Since the autotools switch, the values for build-time constants `CLIENT_VERSION_*` and `COPYRIGHT_YEAR` are now defined in two places.
- https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L3
- https://github.com/bitcoin/bitcoin/blob/master/src/clientversion.h#L11

This seems a bit pointless to me. If both places have to be updated for every release, this only gives more values to update (and potentially forget). Or am I misunderstanding something?

Can we settle on one? If so, which one?

**Comment by fanquake** [comment]
This was fixed in #10155.
