### ISSUE TITLE
Bitcoind malloc error after build Mac

### ISSUE THREAD

**Issue by jfbolus** [bitcoin/bitcoin#3611]
I've successfully built bitcoin in OS X 10.8.3 using the instructions provided in /doc/build-osx.md, while using MacPorts. Both make and make check run without any errors. However, when I try to run bitcoind, it crashes immediately with a malloc error:

[jfbolus@desktop bitcoin]$ ./src/bitcoind
bitcoind(27208) malloc: *** error for object 0x7fff7695d570: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by paveljanik** [comment]
No new information, I'd close this.
