### ISSUE TITLE
Set client to low IO priority on Win7

### ISSUE THREAD

**Issue by OldDeath** [bitcoin/bitcoin#3618]
Windows 7 offers the possibility for a process to set its IO priority to "background". This is something the bitcoin client would certainly profit from, as it tends to read/write lots of data at times and while it does, it shouldn't interfere with other (more important) processes, like media players etc.

See:
http://superuser.com/questions/136021/how-to-change-i-o-priority-of-a-process-or-thread-in-win7

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
