### ISSUE TITLE
[BIP 70] submit payment ignores expire time

### ISSUE THREAD

**Issue by rvzanten** [bitcoin/bitcoin#3665]
When an user loads up a Bitcoin Payment Request and the current time has past the expire time of the BPR you get the message: 'Payment request expired'. Right.
But when an user loads the BPR in time and wants to submit the payment when the time of the BPR has expired the user is not prevented from sending.

The user should be prevented or at least get a warning he is about to send funds to an address of a expired BPR.

**Comment by musalbas** [comment]
Fixed in https://github.com/bitcoin/bitcoin/commit/6715efb9ca5cabeb07ae4ba8390a6e1b7638f66c - should be closed.

**Comment by laanwj** [comment]
Thanks @musalbas
