### ISSUE TITLE
doc/build-unix.md contains contradictory instructions for installing libboost

### ISSUE THREAD

**Issue by ian-kelling** [bitcoin/bitcoin#3756]
doc/build-unix.md says "for Ubuntu 12.04 and later: libboost-all-dev"
A few lines later, it says "for Ubuntu 13.10: libboost1.54-all-dev will not work. Remove libboost1.54-all-dev and install libboost1.53-all-dev" This is contradictory.

**Comment by fanquake** [comment]
@laanwj These lines no longer exist in build-unix.md.This can be closed
