### ISSUE TITLE
client can unknowingly reuse addresses when restoring old backup

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#3791]
I am requesting a receive address, but I keep getting addresses that have been previously used. This may be facilitated by the fact I am using a wallet.dat that was previously used as a backup, but nevertheless, even so, this is not ideal and is misleading the user into thinking they will be using an unused address. I propose that bitcoin-qt could check that the address hasn't been previously used and keep looking until it finds an actually unused one.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
