### ISSUE TITLE
zapunconfirmed RPC

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#3795]
Both salvagewallet and zapwallettxes are often much more rough than needed, when recovering from bad wallet state.

How about an RPC/option that only removes unconfirmed transactions from the wallet? Doing so wouldn't even require any rescan afterwards.

**Comment by laanwj** [comment]
Following the discussion in #3845 there doesn't actually seem to be any demand for this feature, and implementing it correctly is difficult, there are lots of edge cases with regard to updating internal bookkeeping. Closing.
