### ISSUE TITLE
Local Node Discovery Mechanism

### ISSUE THREAD

**Issue by spinza** [bitcoin/bitcoin#3802]
I have seen in lots of guys on forums needing a second node at home and complaining about the massive download time it will take to add that node.  Now, if they thought that far, most of them could manually add an existing LAN node to their conf, but the truth is not many people dig under the hood enough.  Plus the ip changes etc etc.

I'm not sure what the security implications would be of a node broadcasting it's availability on the LAN and hooking up with other nodes automatically.  I'd be happy as long as the node also has a connection with other nodes on the greater internet to make sure it's not being sent a bunch of lies locally.  

Surely this will have savings for the network in general as some of the bandwidth usage gets moved to the LAN rather than the greater internet.  This should also save individual users' bandwidth.

Perhaps using something like Simple Service Discovery Protocol.  

If I were a coder I'd submit some more details but my skills are limited.

**Comment by Azulan** [comment]
I would like to endorse the idea that local nodes should have precedence over others. I try to get my machines to talk to each other and they only stay connected for a short while. One is open to the internet and the other is not. Would really like there to be a config setting or something that induces a local priority mode or something to that effect.

**Comment by spinza** [comment]
@Azulan you can add something like connect=[ip of online machine] in the bitcoin.conf of the offline machine. That way the offline machine will only connect to online machine.  Probably also whitelist=[ip] on both bitcoin.conf so that they whitelist connections from the other.

**Comment by sipa** [comment]
@Azulan Use -addnode=IP on the command line or addnode=IP in bitcoin.conf

**Comment by spinza** [comment]
>@lrossouw it may make sense to have ultimately, but right now it likely wouldn't make any difference at all in the behavior. To get faster syncup you really need to connect exclusively to a local node.

With headers-first sync this does make a difference now.  The node will sync mostly with the faster LAN node.

**Comment by Azulan** [comment]
@spinza I thought so too, but as I reported earlier, it never seems to prefer staying connected to the local peer, which is why I asked for local peer preference in the first place.

**Comment by jgarzik** [comment]
Although not _directly_ related, it seems useful to reference NODE_EXT_SERVICES, PR #4657

**Comment by spinza** [comment]
@Azulan I'll test that out at some point.  I'll addnode a local peer on a new install and see if it pulls over the inet or from the local node mainly.

**Comment by Azulan** [comment]
@spinza I am currently running one up to date 10.2 node and one new 11.0rc node on my lan. They are peers, but the new node continues to prefer other nodes instead of the local and up to date node. The 10.2 node is port forwarded to the internet, the 11.0rc node is not.

**Comment by rebroad** [comment]
@bardiharborow I think we might be talking about different features. Just because a node is on the LAN doesn't mean it is necessarily to be trusted. For example with a trusted node, headers received could be regarded as checkpointed and therefore it could skip the validation that the trusted node has already done.

**Comment by laanwj** [comment]
The point of local node discovery would be that a LAN node is probably faster, and less costly to use (no external bandwidth usage). Trust should be separate from it.

**Comment by Azulan** [comment]
Just want to comment that I am once again having a problem with local nodes not talking to each other and therefore not syncing faster over a local network. This is a very frustrating experience, even for an advanced user like me.

**Comment by Azulan** [comment]
I got it to work! I just had to change from a bitcoin core node to a bitcoin unlimited node. Much better!

**Comment by rebroad** [comment]
@Azulan What does unlimited do differently in this regard?

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
