### ISSUE TITLE
Smarter "double spending" detection

### ISSUE THREAD

**Issue by olalonde** [bitcoin/bitcoin#3853]
One issue I see over and over is new users worrying about their transactions not getting confirmed after a few hours/days due to a low transaction fee. They typically panic a little and wonder if they lost their bitcoin or wonder when it will safe to send a new transaction again. Bitcointalk.org and /r/bitcoin are full of those posts.

This could be solved by having a "Resend with higher transaction fee" option in bitcoin wallets. This option would simply create a new transaction identical to the previous one but where the user could chose to assign a higher fee.

This could be implemented by adding new TXIN(s)/TXOUT (change address) to the transaction without changing anything else. Of course, this option would only be available when the wallet has spendable outputs that were not spent by the original transaction.

One problem with this solution is that even if a bitcoin wallet wanted to implement it, the second transaction would be detected as a double spend and would not be relayed by the network.

Would it be possible to have smarter double spend detection where a transaction wouldn't be considered as a double spend if it sends the same amounts to the same TXOUTs as the original (in other words, if it is a superset of the original transaction)? 

Also, any thoughts on the proposed solution?

Related: https://github.com/spesmilo/electrum/issues/615

**Comment by meshcollider** [comment]
I think this is fixed/made redundant by RBF and bumpfee support
