### ISSUE TITLE
Debug console + RPC: problems with very large transactions

### ISSUE THREAD

**Issue by dexX7** [bitcoin/bitcoin#3896]
I created a valid, signed transaction with nearly 28 kb length and faced several problems.

Within the -Qt debug window of v0.9.0.0-gd6e0e17-beta (64-bit):

 - decoderawtransaction with "hex-of-unsigned-transaction* worked fine.

 - decoderawtransaction with *hex-of-signed-transaction* failed with error "TX decode failed (code -22)". I noticed that the input textbox only allows a text length of 32767 characters at most.

 - sendrawtransaction with *hex-of-signed-transaction* failed for the same reason.

Then I tried to broadcast the transaction via RPC:

 - decoderawtransaction with *hex-of-signed-transaction* worked.

 - sendrawtransaction with *hex-of-signed-transaction* failed with the error "TX rejected (code -22)", if I remember correctly. I'm unable to replicate the error, because I already broadcasted the transaction otherwise.

The same problem appeared on [Eligius' pushtx box](http://eligius.st/~wizkid057/newstats/pushtxn.php).

I was able to broadcast the transaction successfully via the console of Electrum v1.9.8 (connected to electrum.no-ip.org:50002).

Fetching the broadcasted transaction with "getrawtransaction 16a41567e402b9d6fdede7f56eabf2ca64036b9c4b95f063c27bd5713ca72e74" works like a charm both in -Qt as well as via RPC.

**Comment by jonasschnelli** [comment]
I also think it's a debug console and large amount of text (even real stuff) needs to go in over bitcoin-cli or another RPC client.

Can be closed IMO.
