### ISSUE TITLE
Idea: Bitcoin.conf created by default

### ISSUE THREAD

**Issue by i-rme** [bitcoin/bitcoin#3902]
If you want to change the default settings of Bitcoin Core you have to:

1. Go to %appdata%/Bitcoin
2. Copy "Sample Bitcoin.conf" from https://en.bitcoin.it/wiki/Running_Bitcoin
3. Search about the newer configuration options (ie. disablewallet is not listed in the wiki)
4. Finally edit the file with your settings

I believe that on installing Bitcoin Core, if no bitcoin.conf exists in %appdata%/Bitcoin a new one should be created with all options available in that release and some comments about every setting (like the wiki sample file).

I dont know how to make a pull request for this idea.

**Comment by rebroad** [comment]
I think this is a great idea.

**Comment by laanwj** [comment]
Indirectly implemented by #6388
