### ISSUE TITLE
Request: Re-scan external IP at intervals

### ISSUE THREAD

**Issue by daemonazazel** [bitcoin/bitcoin#3915]
My DSL provider in Germany drops and rebuilds my internet connection once every 24h giving me a new IP to prevent me from using my private line for commerical purposes.

Would it be possible to re-check the external IP at intervals so that this change of external IP can be re-broadcast and my client stays reachable?

Otherwise my client is unable to help the network until I manually restart it.

**Comment by laanwj** [comment]
In #3088 the external IP check was removed and other heuristics are used to advertise the address, so probably this is better now.

**Comment by sanktk** [comment]
I am still experiencing the same problem @daemonazazel had. 

I also live in Germany and have a IPv4-IPv6 dual stack connection. Running Bitcoin 0.12.0 on day 1 i have ~20 connections (2 of them IPv6). After the nightly change of both IPv4 and IPv6 i loose all incoming connections. 

The node still performs well and is up-to-date on blocks, but it seems that noone can see my node except the 8 nodes i connect to myself.

bitnodes says my node "is currently accepting incoming connections from other nodes", but when i activate the "node status" is says "pending" or after some minutes "down". See #13 where @geremia describes the same problem.

My setup: Xubuntu 14.04 on an Asus eeepc 1000he netbook with 2GB Ram

**Comment by laanwj** [comment]
Weird. It can take a while to advertise the new address, but it should happen. If not there is some other bug...

**Comment by sanktk** [comment]
bitcoind runs now properly for 2 days with: onlynet=ipv4 AND disablewallet=1

There might just be a problem handling ipv4 and ipv6 simultaniously.
