### ISSUE TITLE
source build non 4.8 Bdb headers issue

### ISSUE THREAD

**Issue by anantshri** [bitcoin/bitcoin#3943]
4.8 Bdb headers were not found however 4.8 so is found and hence the build still uses 4.8 so and hence making it incompatible with 5.1 db wallet.

found below in ./configure output.

configure: WARNING: Found Berkeley DB other than 4.8; wallets opened by this build will not be portable!
checking for main in -ldb_cxx-4.8... yes

I suppose the header files and so files should be of same version and in case its made for incompatible bdb then not to check for cxx.

took me 2 day to figure out the issue.

**Comment by laanwj** [comment]
Duplicate of #3921. Would still be nice to have explicit options to set the path to BDB, especially as the recommended version 4.8 is nowhere available as system version anymore.
