### ISSUE TITLE
[Feature] Unspent Transaction Outputs Index

### ISSUE THREAD

**Issue by kyledrake** [bitcoin/bitcoin#4007]
As per the conversation started in #3383, I am submitting a feature proposal for `bitcoind`.

The proposal is pretty straightforward (to describe, anyways): Implement an unspent transaction outputs index, and allow users to query it via the RPC API.

This is very similar in design to the `txindex`. It would be disabled by default, and enabled via the config file with something like `utxoindex=1`.

Then the user could query the daemon for all the unspent transactions available on any address at any time, on demand:

```
getutxo [minconf=1] [maxconf=9999999] ["address",...]
```

And receive an array response of the utxo objects (perhaps with a few more niceties for people building wallets, such as the date the utxo was received):

```
[
    {
        "txid" : "00003b2f320f9618162d209c67d2c29a812a8644f321093adc6b8f4a925f430e",
        "vout" : 0,
        "address" : "mhZFsQJddG5jGNEmwQgwzeKeiqVT2XgX84",
        "scriptPubKey" : "2102224f4fd0ce5aeb19b7212218f6fdf86f6cd0cef870537294d277014bcc4bcf09ac",
        "amount" : 50.00000000,
        "confirmations" : 5332
    }
]
```

I have spent a lot of time promoting the adoption of the watchonly address patch, but I believe this would provide essentially the same resource that don't-trust-the-server wallet developers need to implement. The transaction information can easily be stored in a ledger on the wallet developer's end, and this complements the goal of separating bitcoind from the wallet code so that it can focus on its primary goal as a listener node that provides information to developers from the network.

I think this is potentially a very important feature to add. Right now, developers solve this by building their own custom blockchain parser, that duplicates (often poorly) a lot of the same business logic that's already in bitcoind. It's really slow to have to do this, it's easy to screw things up, and it's more stuff you need to install/manage.

With this functionality, developers could easily spawn a pool of bitcoind servers to request data and not have to worry about "priming" the daemons with the needed addresses to listen on. It also (relatively) increases privacy/security, because an attacker cannot use bitcoind to find which addresses are associated with it (sans a packet sniffer or something like that).

**Comment by MarcoFalke** [comment]
This has been implemented in the following RPCs: `scantxoutset`. (Alternatively, `dumptxoutset` with #18689)

Because address index was also mentioned in this thread (but seems unrelated to utxoset index), the address index pull request is here: #14053 

Let us know if there is a feature for a use case we are still missing.

**Comment by pierreN** [comment]
Yes it seems that `scantxoutset` and `dumptxoutset` with #18689 fill that purpose.

If anyone sees additional features to add to #18689 I'd be happy to add them to the PR.

**Comment by mikemilla** [comment]
@MarcoFalke @pierreN Apologies if I am missing something here, but will this constantly maintain an index of all the utxos? For example if I run this once, when it completes do I ever need to run this again to get the latest utxos for an address?

**Comment by MarcoFalke** [comment]
`scantxoutset` and `dumptxoutset` do not retain state in Bitcoin Core after the call has finished. Those calls operate by iterating over the *current unspent transaction outputs*. This set changes with every newly connected or disconnected block. txouts can be added or removed, and only *unspent* txouts are iterated over.

I think there was also discussion about an index of all addresses used in the chain. Assuming no reorgs, such an index is *append-only*. We have a txindex in current master. There are also plans to have an address index #14053

**Comment by pierreN** [comment]
Note also that #18689 should be fast enough on decent hardware to dump the UTXO set every block mined.
A (really non-optimal) way could be to dump the UTXO set into tmpfs every time a block is mined and then diff the file.

**Comment by mikemilla** [comment]
@pierreN that would work, but the use case I'm working on currently needs the outputs after a transaction is broadcasted (similar to apis like https://blockchair.com/ and https://bitaps.com/).

Does bitcoin-core have something similar to this or is https://github.com/bitcoin/bitcoin/pull/18689 as close as it gets?

If this doesn't exist, to anyone that sees this, it would be nice if this could be added easily by having a bitcoin.conf property like `indexoutputs=1` and a simple rpc like `getoutputs address`

**Comment by pierreN** [comment]
I guess that if you want to scan the utxo with respect to an address you should use `scantxoutset` (and then parse the json since the output shouldn't be that big)?

`dumptxoutset` use case is if you want to **dump all elements** in the UTXO set  with at least `A` confs and no more than `B` confs (took 3mns on my machine):

```
$ bitcoin-cli utxo.dat '["height","txid"]' false ' '
$ awk -v cur_height=$(bitcoin-cli getblockcount) '{num_conf=cur_height-$1; if(num_conf>A && num_conf<B) print num_conf,$2}' utxo.dat
```

**Comment by MarcoFalke** [comment]
> outputs after a transaction is broadcasted and may not be confirmed at all 

mempool entries are not in the utxo set (via `scanttxoutset` etc), since they are not yet included in a block and confirmed in the chain. You will need to get them with the mempool related RPCs

**Comment by pierreN** [comment]
(related to OP's request:) Note that we could also add a field `addresses` [here](https://github.com/bitcoin/bitcoin/pull/18689/files#diff-a0c8f511d90e83aa9b5857e819ced344R2252) but then why not also add all the outputs of ` ScriptPubKeyToUniv`... this looks like spam to me (and you could easily script that calling `gettxout`) so I'm not sure it's a great idea. I guess it's best to leave it up to the user.
