### ISSUE TITLE
-connect to unreachable node seems to slow down wallet after a while

### ISSUE THREAD

**Issue by Joukehofman** [bitcoin/bitcoin#4034]
I had a wallet connect to a node on "localhost" (ssh tunnel).  The tunnelled node became unreachable and over time the wallet seemed to slow down. And by slowing down I mean I was getting time-outs on RPC requests over ssl.

I noticed the time outs were gone after restarting the wallet once, but gradually came back. Now that I restarted the wallet without the -connect to the unreachable node I have not had a time out since.

(version 0.9.-something)

**Comment by MeshCollider** [comment]
Seems like either the issue is fixed or at least hasn't provoked any discussion for nearly 4 years, closing now...
