### ISSUE TITLE
Double spends do not create a reject message

### ISSUE THREAD

**Issue by mikehearn** [bitcoin/bitcoin#4057]
I wrote an app that sends two transactions which double spend the same output in a row. The second never generates a reject message, because we end up in the dead "replace tx" codepath which returns false and doesn't even log anything, so the tx disappears silently. I think if that codepath is taken out or just #defined out so it's clear where the fixed code should go once done, then it will fall through to the other checks below.

However then we have a second problem, which is that if all the tx outputs are spent already, it also won't trigger a reject message because it will hit the block starting with

```
    // do all inputs exist?
```

and end up failing to find the CCoins, so again, no reject message.

**Comment by laanwj** [comment]
As of #6519 there is a REJECT_CONFLICT `txn-mempool-conflict`, however it is not sent over the P2P network, only over RPC, as no reject code has been defined in the BIP. Exposing this would require updating or creating a supplement to bip-0061.

**Comment by MarcoFalke** [comment]
I believe reject messages have been deprecated? If so, this feature request is no longer applicable and could potentially be closed.
