### ISSUE TITLE
Convert QA Bash Test to Python

### ISSUE THREAD

**Issue by super3** [bitcoin/bitcoin#4071]
Out of the [RPC-Test README](https://github.com/bitcoin/bitcoin/tree/master/qa/rpc-tests).

### Bash-based tests, to be ported to Python:
- wallet.sh : Exercise wallet send/receive code.
- walletbackup.sh : Exercise wallet backup / dump / import
- txnmall.sh : Test proper accounting of malleable transactions
- conflictedbalance.sh : More testing of malleable transaction handling

**Comment by laanwj** [comment]
As noticed by @fanquake, only one remains to be done:
- conflictedbalance.sh : More testing of malleable transaction handling
