### ISSUE TITLE
Add self-tests at startup

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#4081]
The idea would be to test basic sanity of the execution environment and dependencies. for example:

- check std::list and the functions overridden in the compatibility wrappers for older glibc/glibc++
- test basic secp256k operations
- test hash functions

This idea was brought up by @sipa in issue #4042. The tests should run very quickly (&lt;0.1 second).

**Comment by laanwj** [comment]
Implemented by #4339

**Comment by dcousens** [comment]
@laanwj what about `libsecp256k` and the hash functions?

**Comment by laanwj** [comment]
Sure, you could do that...
