### ISSUE TITLE
Text selection highlight disappears when user right clicks on it

### ISSUE THREAD

**Issue by XP1** [bitcoin/bitcoin#4095]
Text selection highlight disappears when user right clicks on it

Bitcoin Core 0.9.1.0-g026a939-beta (64-bit)
Windows 8

# Steps:
1) Select text. For example, select your available BTC.
2) Right click on the text selection.

# What happens:
The right click context menu appears, but the text selection highlight disappears.

# What should happen:
The text selection highlight should not disappear when the right click context menu appears.

**Comment by laanwj** [comment]
I've never seen this behavior, either it was solved after 0.9.1 or it was a specific issue with this user's environment:
![untitled](https://cloud.githubusercontent.com/assets/126646/16264327/359aa000-3879-11e6-935b-c7f789f0ca22.png)
