### ISSUE TITLE
In SENDING ADDRESSES after pressing DELETE highlighting disappears, but can still delete anyway. 

### ISSUE THREAD

**Issue by DobZombie** [bitcoin/bitcoin#4112]
This is just a GUI issue I noticed.  

When in "Sending Addresses" I wanted to delete a bunch of addresses.  I then clicked delete, then I thought I had to highlight the area again to delete another.  I then realised that I could just keep clicking DELETE and delete more addresses even though no address was highlighted.

I realised that a user could keep clicking DELETE and delete the wrong contact by mistake.

This is my first Issue report.  Be kind :)

**Comment by laanwj** [comment]
That indeed sounds like a bug. Delete without a selection should not delete anything.

**Comment by achow101** [comment]
This is no longer an issue. A new address is selected after one is deleted, and that is deleted if you click deleted.
