### ISSUE TITLE
Bitcoind as system background service

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#4124]
When using bitcoind as a wallet-less full node, it would be useful to be able to run it as a system service, so that it starts automatically at startup and can be controlled though the OS's normal service start and stop functionality.

For the Debian/Ubuntu side of things see hippich and fungus' posts here: https://bitcointalk.org/?topic=965.0 . It'd make most sense to integrate this into the PPA. There are two different systems in use here: old-style sysv init scripts, and upstart.

For Windows/OSX I'm not sure what is necessary. At least we'd need new installer packages, separate from the normal "Bitcoin Core Wallet" which provide a node and nothing more.

The installer would also need to create user credentials to run under.

Edit: for the service install, this would also imply moving the configuration to a system-wide instead of user location, for example `/etc/bitcoin.conf` as well as default the data directory to a system-scope location (probably `/var/lib/bitcoin`).

**Comment by laanwj** [comment]
This is sufficiently done now (`doc/init.md`), thanks everyone, closing the issue

**Comment by rebroad** [comment]
What about running it as a service on Microsoft Windows? This doesn't seem to have been addressed.

**Comment by laanwj** [comment]
We don't have any active windows developers, so none of us will do that. But feel free to write a guide on that.
