### ISSUE TITLE
Locale should default to C / Posix Environment

### ISSUE THREAD

**Issue by itoffshore** [bitcoin/bitcoin#4147]
Busybox does not use locales - bitcoin should set a default C / Posix environment. The following locale error:

    EXCEPTION: St13runtime_error       
    locale::facet::_S_create_c_locale name not valid       
    bitcoin in AppInit()       

    terminate called after throwing an instance of 'std::runtime_error'
      what():  locale::facet::_S_create_c_locale name not valid

Can be fixed with the following patch https://github.com/bitcoin/bitcoin/issues/4147#issuecomment-42763464

The above patch is almost identical to the patch I proposed for Namecoin to fix this issue (Windows builds are unaffected):https://github.com/namecoin/namecoin/issues/72#issuecomment-42520429

**Comment by adattudos** [comment]
This is still an open issue in 0.10.1rc2 even though 0.10.0 was fine in the same environment:
```************************
EXCEPTION: St13runtime_error       
locale::facet::_S_create_c_locale name not valid       
bitcoin in AppInit()       

terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
```

**Comment by itoffshore** [comment]
Testing [0.10.1](https://github.com/bitcoin/bitcoin/releases/tag/v0.10.1) there is no longer any `environment` regression.

 0.10.1 should also be patched as [shown here](https://github.com/bitcoin/bitcoin/issues/6113#issuecomment-99620775) to fix a segfault introduced in 0.10

**Comment by Diapolo** [comment]
@laanwj Not sure where to post, but AFAIK some change to locale handling was revert, which reintroduces a crash when chaning -txindex and aborting or when trying to abort Qt startup during init phase in splash screen... too bad this is unfixed again :-/.

**Comment by laanwj** [comment]
Is this issue fixed or still present in 0.12 / master?

There have been more changes to this code since, so I suppose it is, but as the locale initialization is complex voodoo code there could always be an edge case.

**Comment by itoffshore** [comment]
This issue has been fixed since `0.10.1` in Alpine Linux & also with `0.11.x` too. 

I will try building `0.12`

**Comment by laanwj** [comment]
Oh! If it was fixed back then I doubt it has come back now. Just wonder why the issue was never closed then.
But if you want to try on 0.12 just in case, thanks :)

**Comment by jl2035** [comment]
I no longer run a full node, so I never reported back.

**Comment by itoffshore** [comment]
`0.12` is fine too - this issue can be closed
