### ISSUE TITLE
RPC introspection

### ISSUE THREAD

**Issue by d3rrial** [bitcoin/bitcoin#4157]
Enable the bitcoin rpc server to return structured information about the rpc commands it accepts, such as parameters, datatypes, requiredness and maybe a description or parameter bounds

A static example of this can be found here: https://github.com/d3rrial/bitcoin/blob/getrpcinfo_rpc_command/src/rpcserver.cpp

Ideal would be something more dynamic, so that developers, should rpc methods be added or removed don't have to crawl through that list of rpc commands.

**Comment by promag** [comment]
See also http://jsonrpc.org/historical/json-schema-service-descriptor.html.

**Comment by jnewbery** [comment]
Is anyone working on this? I suggest we close as an up-for-grabs issue if it's not actively being worked on.

**Comment by MarcoFalke** [comment]
This can be easily implemented with RPCMan (or RPCHelpMan)
