### ISSUE TITLE
Verify transaction without propagating

### ISSUE THREAD

**Issue by sidazhang** [bitcoin/bitcoin#4162]
### Current Behaviour

If I use RPC command `sendrawtransaction` and supply an tx hex that is not acceptable (e.g. 1. if a signature is invalid, 2. contains a double spend) bitcoind will reject it, and if the transaction is verified, bitcoind will then propagate the transaction
### Feature Request

It would be great if there could be a RPC call that allows `verifyrawtransaction`, which means it will only verify the transaction without propagating.

**Comment by dexX7** [comment]
I agree with the general idea, and think this could be pretty useful.

While `"decoderawtransaction"` can be used to check the structure of transactions, and in a hacky way `"signrawtransaction"` can be used to verify scripts and signatures, it's feels more like an incomplete workaround.

A few random use cases that come to my mind, more or less related to this topic:

- User doesn't want to run a node (for whatever reason), and instead uses a third party API provider; Bitcoin Core could be used to double check the results, at least to some degree

- User wants to know which inputs are signed in a partially signed transaction

- User signs a raw transaction offline, and wants to verify the signatures on another machine, before moving the signing keys on paper back to a vault

- User receives a time-locked refund transaction, say for example from greenaddress.it, and wants to ensure the refund transaction is valid

- Someone fools blockchain.info' pushtx API and "spoofs" a transaction, seemingly spending Satoshi's coins; Bitcoin Core could again be used to double check, whether it really may have happened

Related to the first point is a discussion over at https://github.com/CryptoConsortium/CCSS/issues/15, which indicates that relying on external API providers seems to be pretty common.

It should probably be differentiated between stateless and stateful verification (e.g. consider the mempool).

**Comment by laanwj** [comment]
We've discussed this on IRC a while ago, and this still seems useful.

> One thing such a feature should have is the ability to take a list of transactions— since you may need to also provide the parents which you also don't want to broadcast yet.

Yes, it should definitely be able to take a list of transactions. 

> An interesting question is should it be validating against the blockchain or against the memorypool?

Probably either - should be a parameter, like for `gettxout`.

**Comment by dcousens** [comment]
What is intended by:

> validating against the mempool

Do we mean simply checking policy?

**Comment by NicolasDorier** [comment]
For information, such feature would be very useful for LN.
There is several rule (like dust one) which can make a tx commitment unbroadcastable. This would result into theft.

If such function existed, a LN node would just have to check verifyrawtransaction before releasing the revocation hash of the previous commitment.

**Comment by laanwj** [comment]
> Do we mean simply checking it against policy? (no double spends, RBF, yada yada)

See it as the difference between 'take into account 0conf' (blockchain+mempool) and 'don't take into account 0-conf' (blockchain).

**Comment by laanwj** [comment]
See #7552

**Comment by MarcoFalke** [comment]
See #11742
