### ISSUE TITLE
When issuing bitcoind the `stop` rpc command, it waits forever for existing clients to disconnect

### ISSUE THREAD

**Issue by ryancdotorg** [bitcoin/bitcoin#4235]
Also, oddly, it continues serving RPC commands to them.

I found this using bitcoinrpc.authproxy in python. Open up a process that polls bitcoind in a loop from python, then issue a `stop` command from a different client. bitcoind does not stop until the python script is closed.

**Comment by sipa** [comment]
I believe this is no longer the case since at least #5677 or earlier.

**Comment by dcousens** [comment]
Could not reproduce with master.

``` bash
while true; do ./src/bitcoin-cli getinfo && sleep 0.1; done
```

``` bash
./src/bitcoin-cli stop
```

Loop dumped out the following immediately after the server stopped (as expected).
```
(make sure server is running and you are connecting to the correct RPC port)
error: couldn't connect to server: unknown (code -1)
```
