### ISSUE TITLE
regtest: setgenerate true assert failure

### ISSUE THREAD

**Issue by wtogami** [bitcoin/bitcoin#4242]
If you run ```setgenerate true``` too rapidly in regtest mode, bitcoind can crash with
```
/home/ubuntu/install/include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
```

This was reproduced with the Linux 64bit gitian binary.

**Comment by laanwj** [comment]
This is resolved by now. Don't use `setgenerate` on regtest, use `generate`.
