### ISSUE TITLE
Insane fee check doesn't return clear error to the sendrawtransaction RPC

### ISSUE THREAD

**Issue by Michagogo** [bitcoin/bitcoin#4341]
Rather than a message that's readable, it just returns this:
$ bitcoin-cli sendrawtransaction 01000000018368ead3c8677725a71ba7d17dc181ef41ebafcddd833dc67842ed155e6620780000000049483045022100a62a6379db25aada0c0252c3bcac95038992327d851f85f455c85d12fc935b0a022020d01881135a35f173c7d58dc98cb09017e23bbbc182d8c993e10da6ebb8a68a01ffffffff0100301a1e010000001976a914c04b7b7d1d6de24c83a77dd229e1f4488b09ee9f88ac00000000
error: {"code":-25,"message":""}

**Comment by priiduneemre** [comment]
Still... in the long run, maybe a more descriptive error message could be returned when bouncing against the 'insane fee' check in `sendrawtransaction(..)? 

Took me quite a while to figure out what was wrong with my raw transaction and the generic error response wasn't really helping either: `{"result":null,"error":{"code":-25,"message":""},"id":"e7040c392ccb4adb92770dc168d97ae6"}`

**Comment by sipa** [comment]
See #5913.

**Comment by paveljanik** [comment]
Fixed now?

**Comment by laanwj** [comment]
Yes.
