### ISSUE TITLE
-listen has stopped being set to 0 when -connect present

### ISSUE THREAD

**Issue by dgenr8** [bitcoin/bitcoin#4433]
It is now necessary to set -listen=0 even when setting -connect= (and not setting -bind=). 

This does not match documentation for -listen: "Accept connections from outside (default: 1 if no -proxy or -connect)".

**Comment by sipa** [comment]
Is this still the case?

**Comment by dgenr8** [comment]
I tried this on 12.0 and did not see the problem as described.  Strangely though, it was not listening, even with no connect or proxy.  Having this issue around does not seem useful so I'll close it.
