### ISSUE TITLE
Question: Dos Test Timestamps/nBits

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#4442]
Looking at the Dos_tests, there is a list of timestamps and nbits for the first 9 blockchain checkpoints. However only the first two match the actual timestamp/bits of the blocks. The next 7 have timestamps/bits that don't match the checkpoints. Is this intentional? If so, why has it been done?

11111 (1239852051,486604799)   Y matching
33333 (1262749024,486594666)   Y matching
74000 (1279305360,469854461)   N 1281678674,469809688
105000 (1280200847,469830746) N 1296207707, 453179945
134444 (1281678674,469809688) N 1309640330, 437004818
168000 (1296207707,453179945) N 1329946277, 437006492
193000 (1302624061,453036989) N 1344491921, 436747465
210000 (1309640330,437004818) N 1354116278, 436527338
216116 (1313172719,436789733) N 1357902690, 436545969

**Comment by laanwj** [comment]
Closing this as it is not an open issue (and I don't know the answer either, but I think this is supposed to be the case - the test points don't have to match checkpoints).
