### ISSUE TITLE
getnewaddress return used address

### ISSUE THREAD

**Issue by mgosk** [bitcoin/bitcoin#4509]
Function get new addres return previously used address.

To reproduce:
1. Make withdraw. (coins go from address A to address  B, change go to C)
2. Call getnewaddress (it return C)

Example:
On 03.07.2014 I make withdraw to address: 1GCS7HGigMY3nsNvDdEQB332kHeNvnpiS6
TxId:
db48c0e7f4d41ead6976cd24aba8668a76a8881a790694125f3e399a461a67c7
Change return to: https://blockchain.info/pl/address/1Bo5aiyzN2gkusA4kDeNFXZ94LiAcch6og

Today I call getnewaddress and recive same 1Bo5aiyzN2gkusA4kDeNFXZ94LiAcch6og

Bitcoind version: 90000
all calls maked via json-rpc API

**Comment by MarcoFalke** [comment]
@mgosk Could you reproduce this issue another time?

**Comment by MeshCollider** [comment]
Issue seems stale, closing unless anyone can reproduce
