### ISSUE TITLE
AddTimeData will never update nTimeOffset past 199 samples

### ISSUE THREAD

**Issue by jprupp** [bitcoin/bitcoin#4521]
Reading the function AddTimeData, I came to notice two things:
- The structure vTimeOffsets contains up to 200 elements, after which any new element added to it will not increase its size, replacing the oldest element.
- The condition to update nTimeOffset includes checking whether the number of elements in vTimeOffsets is odd, which will never happen after there are 200 elements.

This will lead to nTimeOffset not updating past 199 calls to AddTimeData, remaining forever stuck in whatever value it had then. I don't believe this is the inteded behaviour. I would suggest removing the oddness check, since vTimeOffsets is capable of returning the median value of an even list according to the median method of the CMedianFilter type.

In current master, the offending code is in src/timedata.cpp, line 52, columns 34-64:

``` c++
if (vTimeOffsets.size() >= 5 && vTimeOffsets.size() % 2 == 1)
```

This should better be:

``` c++
if (vTimeOffsets.size() >= 5)
```

**Comment by hno** [comment]
A side effect of this bug is that a node that has a drifting clock can will keep on drifting with no warning shown until bitcoind is restarted.

Node starts up at reasonaly correct time.
Collects 199 time offsets from other peers.
Local clock drifts. bitcoind silently keeps on using local time + previously calculated network adjustment, not at all compensating for it's local clock drift or even giving a warning/error when the difference gets too large.

**Comment by hno** [comment]
The above is an attempt to address the concerns raised here by adding an option to trust the local clock source, and rework warning conditions somewhat. Please review if you are interested.

**Comment by paveljanik** [comment]
-trustlocalclock: Why not just return 0 in GetTimeOffset? And warn about the peers offset being higher?

**Comment by paveljanik** [comment]
But in general, I like -trustlocalclock. It allows the user to choose the "take one" part of the "Never go to the sea..." comment in https://github.com/bitcoin/bitcoin/blob/master/src/timedata.cpp#L21.
Of course when using NTP, you could still be in bad network partition. Or your other time source could be compromised etc. But you can at least select such option.

**Comment by MarcoFalke** [comment]
Related PR: #6545

**Comment by laanwj** [comment]
"We're using SPV peer's time to compute our network offset P2P #6071" is another time correction related issue.

**Comment by laanwj** [comment]
Another issue:
https://github.com/bitcoin/bitcoin/pull/7573#issuecomment-202973041

> I like this approach much better. But the implementation has an odd non-monotonicity. E.g. if you have 5 peers claiming ten seconds off, then six more connect claiming 80 minutes. You'll apply a correction of 0 instead of 10 seconds. Perhaps better to just fix in another PR, since it was an existing misbehavior (though more likely to be triggered when the time is cut down to small numbers).

**Comment by MarcoFalke** [comment]
I wonder if it wouldn't be better to remove the use of GetAdjustedTime. While it works well to cover some cases of misconfigured clocks, it fails to detect others.

Then, replace it with a stronger warning mechanism that also triggers when the time is off by more than ~10 minutes? Currently it only triggers after 70 minutes.

Maybe even add setting (off by default) that shuts down the node if outbound nodes report a different time than ours?
