### ISSUE TITLE
Reject behavior does not coincide with BIP0061

### ISSUE THREAD

**Issue by davecgh** [bitcoin/bitcoin#4538]
[This](https://github.com/bitcoin/bitcoin/blob/master/src/main.cpp#L1004-L1006) code in the `AcceptToMemoryPool` function for rejecting transactions with missing and/or fully spent transactions sends a reject code of `0x12` which, according to [BIP0061](http://github.com/bitcoin/bips/blob/master/bip-0061.mediawiki) is `Duplicate version message received`.

I suspect it is probably easier to fix the BIP at this point, but I did want to point out the implementation does not match the BIP.

**Comment by laanwj** [comment]
The BIP was fixed by @NicolasDorier in https://github.com/bitcoin/bips/pull/148
