### ISSUE TITLE
Reverted double spend relaying (for now)

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#4550]
The double spend relaying stuff isn't quite baked fully yet.

Links: #4484 #4450 #3883 

Related FLOSS principle:  Make it socially OK to revert a recently applied change.  It is easy to "pull the trigger" and merge.  The side effect of that policy is sometimes a change is pulled too soon, and needs reverting.

It can be merged again later once fully analyzed and tested.

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by laanwj** [comment]
No, there are no plans in this regard anymore, let's close this.

**Comment by rebroad** [comment]
I'm confused - although I originally ACKed this it seems that it might still be beneficial to have some double spend notification ability in the client - but to ensure that the UI mentions that not every double spend will necessarily be noticed by the software.

**Comment by laanwj** [comment]
> How long is "for now" going to be?

Forever, I suspect. Please notice that this issue is more than two years old. Plans and priorities changed.
