### ISSUE TITLE
Selective tor usage

### ISSUE THREAD

**Issue by kazcw** [bitcoin/bitcoin#4564]
Tor can obscure the relationship between a wallet and an IP address, but has high overhead. For a full node, none of the network-intensive activity leaks privacy; it seems like the ideal application of tor in many situations would be to perform all non-wallet network functions normally via direct connections, but use a tor connection for privacy-leaking operations like pushing wallet transactions.

**Comment by laanwj** [comment]
As of #5951, this use case can now be addressed using `walletbroadcast=0` then taking care of the transaction broadcast manually or through an external script.
