### ISSUE TITLE
whitelisting outbound connections

### ISSUE THREAD

**Issue by kazcw** [bitcoin/bitcoin#4565]
It is currently impossible for an outbound connection to be whitelisted; this should be available, either explicitly or implicitly, to prevent situations like a node DoS-banning its sole connect= node.

Should the whitebind/whitelist criteria be applied to outgoing connections?

**Comment by laanwj** [comment]
Yes, it makes sense to be able to whitelist nodes that are connected to explicitly.

**Comment by MarcoFalke** [comment]
Let's discuss this in #9923
