### ISSUE TITLE
Filter out useless addresses from "addr" peer exchange

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#4609]
addrman blindly provides a bunch of addresses, even ones that
- have been banned
- have been tried, and failed (multiple times, even)

This is apparent in two cases,
- Bogon peers are returned in "addr" messages, thereby ensuring these zombies live on
- Tries to connect to known-failed addresses over and over again, if total peer db is low on addresses.  Never seen on mainnet, but sometimes seen on testnet.

In general, we should provide a way for the network and local nodes to slowly forget ancient/dead/failed addresses.

**Comment by rebroad** [comment]
But, how do nodes remember which nodes they have forgotten?

**Comment by jgarzik** [comment]
Still applicable - closing due to no-action
