### ISSUE TITLE
fee estimates file sanity check too strict

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#4639]
Reported by Alex Morcos:

txid 5430b159cf662ce21e06a41ec1280ebcce8ed6a52f14b21dad394b0fba3227e7 has a fee rate which is so high it triggers this check.  So when bitcoind is restarted after this transaction has been recorded: in the original code the history is cut off after 10 blocks (it took 11 to get confirmed) or in my new code, which just got merged, the fee_estimates.dat file is ignored and we start with a clean history.

**Comment by jlopp** [comment]
I suspect this issue is no longer relevant given the rewrite - I'm not seeing any sanity checks against the fee levels when reading the file. Can you confirm, @morcos?
