### ISSUE TITLE
Follow standard Unix daemon practices

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#4676]
fork() + setsid() is too minimal, and does not follow standard daemonize protocol.  Normal steps include http://stackoverflow.com/questions/3095566/linux-daemonize

Implementation comments:
- we do output data to stdout/stderr upon some error conditions, so /dev/null might not be the best choice (or it might be, if we just change a few things!)
- would be nice to achieve chroot-ability.  That would likely break anybody with crazy symlinking schemes.

Code ref: https://github.com/bitcoin/bitcoin/blob/master/src/bitcoind.cpp#L122

**Comment by jwilkins** [comment]
https://lkml.org/lkml/2007/9/25/434
and
http://misc.openbsd.narkive.com/UrTwzZcc/chroot-ssh-users#post17

**Comment by cheako** [comment]
@jwilkins Chaining root requires UID zero.  Using chroot against a file breaks the root user out of the chroot, but for normal users it does not.  If the chroot has no files or no suid root binaries then it can be an effective jail for processes with EUID && UID != 0.  Though it was never intended to do so, it's just a by-product.

@all
Bitcoin and chroot has other issues, the ability to write to files and even worse write permissions on a directory.  The effectiveness of a chroot is limited until these are addressed.

Though it's not entirely necessary to have daemons support changing euid/uid/root/ect.  I use [daemon](http://libslack.org/daemon/) for that.

Closing the terminal(pty/tty) is important as not doing so can cause ssh sessions to be unable to close cleanly.

I also suggest looking at http://libslack.org/daemon/manpages/daemon.1.html as [1] looks a little barren in comparison.

**Comment by Sjors** [comment]
Did #8813 fix this?

**Comment by jgarzik** [comment]
> Did #8813 fix this?

@Sjors Did not fix, but moved the needle forward, at least.   Closing as sufficient + probably won't see further action.
