### ISSUE TITLE
dynamic IP change -> silent network disconnect

### ISSUE THREAD

**Issue by molecular** [bitcoin/bitcoin#48]
to reproduce:
1.) run bitcoin, wait for it to connect to net
2.) recycle your dynamic IP (get a new one)
3.) wait for next block
4.) see that new blocks don't show up in your client

expected behaviour:
bitcoin should detect that it's disconnected from the network and reconnect.

notes:
1.) the client still shows connection count after the IP change
2.) the connection count will slowly drop to 0
3.) then it will just sit there with 0 connections

**Comment by pstratem** [comment]
@molecular Is this still an issue?

**Comment by MorphRipley** [comment]
Patrick, I need something back from you that is mine.
And yes, it is STILL an issue.
Johannes van Gerwen

**Comment by molecular** [comment]
I can't easily retest at this point. I'm just going to close the issue. If that's not appropriate, please reopen.
