### ISSUE TITLE
Mouse pointer jumps to "default" element when clicking to another tab

### ISSUE THREAD

**Issue by francwalter** [bitcoin/bitcoin#4840]
Hello
On Windows 8.1 (64-bit) I notice in Bitcoin Core 0.9.2.1 the following behaviour which is not helpful:
When I click onto the Tab "Send", the mouse pointer jumps to the (default) CmdButton 'Send'.
When I click onto the Tab "Receive" the mouse pointer jumps to the (not default but disabled) CmdButton 'Show'.
When I click on "Overview" (coming from "Send") it jumps to some empty space where there could be a CommandButton but isn't.
All works well when I click on "Transactions".
All works well when I click on "Receive", but coming from "Transactions"

This is a bit annoying and surely a very little bug in the design view.
thank
frank

**Comment by jonasschnelli** [comment]
solved by #4853 
needs close.
