### ISSUE TITLE
Deprecate wallet-less signrawtransaction?

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#4844]
Since we now have a tool (bitcoin-tx) that can perform sign/create raw transaction and other things without a wallet present, I wonder whether the corresponding RPCs in bitcoind can't be made require-wallet. That would get rid of the macro conditionals in the implementation.

**Comment by achow101** [comment]
#10579 is kind of doing this.

**Comment by sipa** [comment]
Closing, as I think #10579 sufficiently addressed this.
