### ISSUE TITLE
Bitcoin-Qt OS X 10.8 new user crashes on startup since 0.9.2

### ISSUE THREAD

**Issue by akkornel** [bitcoin/bitcoin#4877]
Hello!

I'm a new Bitcoin user, and I am unable to get Bitcoin-Qt to work on my Mac OS X 10.8.5 system:  When I start the client, it crashes during the "Loading Addresses" part of the startup process.

I've tried 0.9.2, 0.9.2.1, and 0.9.3rc1, all of which crash.  Versions 0.8.6, 0.9.0, and 0.9.1 all work:  It was able to start up, it recognized bootstrap.dat, and it started importing blocks from disk.  Here's what I did to test:

1) Delete the contents of the ~/Library/Application Support/Bitcoin directory, except for bootstrap.dat.
2) Download the Bitcoin-Qt .dmg image, and copy to /Applications
3) Launch Bitcoin-Qt.

At this point, the splash screen appears for ~30 seconds, and then one of two things will happen:  Either the app will bring up the Wallet window, and start loading transactions from disk, or the app will crash.  Normally, the splash screen says "Loading Addresses" at the time of the crash.

FYI, my bootstrap.dat was download via torrent less than two hours ago.  I get the same crash-y behavior without bootstrap.dat.

**Comment by laanwj** [comment]
Issue has been resolved a long time ago - thanks for cooporating to fix it
