### ISSUE TITLE
Enable tests/functional from configure

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#4905]
Is there a way to enable qa/rpc-tests from configure? For some time I had been assuming we're running those by default, but that doesn't seem to be the case (and would probably be annoyingly slow to do by default)?

**Comment by laanwj** [comment]
Partially resolved by #4905. You can run them with `qa/pull-tester/rpc-tests.sh`.
Not sure if the plan is still to include the RPC tests in `make check`,

**Comment by MarcoFalke** [comment]
If someone plans to implement this, having configure detect the python-zmq version would help to get rid of https://github.com/bitcoin/bitcoin/blob/8844ef15ded02d5ed86fb95aaf251235fcef2396/qa/pull-tester/rpc-tests.py#L92

**Comment by adamjonas** [comment]
This was closed by moving to Travis, yes?

**Comment by MarcoFalke** [comment]
No.

We have a bunch of tests:

* unit tests
* util tests written in python
* bench runner
* subtree tests

All of them are run when you type `make check`.

However, for running the functional tests, one has to type `./test/functional/test_runner.py`

**Comment by MarcoFalke** [comment]
Closing, because every comment in here is 6 years old and does not reflect the current state. This is confusing. I will open a new issue to start a fresh discussion thread.
