### ISSUE TITLE
BIP 70 protocol not prompting user to specify payment amount when `outputs` amount field is 0.

### ISSUE THREAD

**Issue by derrend** [bitcoin/bitcoin#4908]
`Requested payment amount of 0.00 BTC is too small (considered dust).` is the error message displayed in this case.

I know I could capture the amount using `raw_input()` but this would be cumbersome and inefficient.
Would be great to see this problem fixed or some kind of workaround if possible.

Coinbase uses this protocol, was this an issue for them and if so does anyone know how they dealt with it?

Thanks

**Comment by essofluffy** [comment]
Any update on this?

**Comment by laanwj** [comment]
Closing payment protocol specific issues; as that functionality is going to be deprecated in the near future it's not worth working on.
