### ISSUE TITLE
Update Debian (Ubuntu) package with bitcoind init scripts

### ISSUE THREAD

**Issue by msgilligan** [bitcoin/bitcoin#4935]
Given Issue #4124 (bitcoind as system service) and now that PR #4611 (init scripts and docs for Upstart and OpenRC) is merged, it would be nice to see some updates to the Debian packaging (in `contrib/debian`, right?) to properly install `bitcoind` as a system service.

It would also be nice to see better documentation on the Debian/Ubuntu package:
- Where it lives (source and binary)
- Better build instructions
- etc

(I've done a little bit of work in this area on my own, but am an Debian/Ubuntu newb. I'm definitely willing to help with testing and documentation.)

References:
- [Debian contrib directory](https://github.com/bitcoin/bitcoin/tree/master/contrib/debian)
- [Bitcoin LaunchPad page](https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin)

**Comment by nullhack** [comment]
@msgilligan I'm new to the bitcoin world and would like to help, If someone guide me I think I can do this job

**Comment by msgilligan** [comment]
@nullhack Have you made Debian packages before?

**Comment by nullhack** [comment]
@msgilligan not yet, but I read a little about it

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, please report the issue in https://github.com/bitcoin-core/packaging
