### ISSUE TITLE
Encapsulate policy

### ISSUE THREAD

**Issue by jtimon** [bitcoin/bitcoin#4943]
Main currently mixes protocol rules with policy rules like standard transactions check or minimum fees.
All policy things should be encapsulated and moved out of main so that it's easier to implement alternative policies without adding complexity to core protocol code, for example, the replace by fee policy implemented in #4298.
Since there are currently several PRs that greatly affect main (#4468 among others) and are a bigger priority than this, we should probably wait, but we can start collecting ideas on where to start with this refactor.

**Comment by jtimon** [comment]
#5071 #5595 #5114 and #5180 are related to this issue.

**Comment by MeshCollider** [comment]
I believe this is sufficiently reworked to close this PR now?
