### ISSUE TITLE
bitcoin-qt keeps freezing every ~10 seconds

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#5037]
There seems to have been introduced recently some sort of sleep of 10 seconds into a loop somewhere because now the debug.log keeps sleeping for 10 seconds regularly. This is causing problems with timeouts that I'm trying to test, with 2 being triggered together, when they should be 5 seconds apart.

**Comment by fanquake** [comment]
@rebroad Are you still seeing this behaviour after the merge of #5168 ?

**Comment by jonasschnelli** [comment]
Closed because fixed with #5168 and no feedback from @rebroad.
