### ISSUE TITLE
Getchaintips is kinda slow

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#5070]
Not terribly important but if someone is looking for something to optimize, this is noticaby slow and varrious monitoring might like to call it a lot.

**Comment by casey** [comment]
The way to optimize this would be to maintain a set of current chain tips, updating it every time we see a new block. Easy enough to do, but would it be worth it to speed this up? If there's user interest in `getchaintips` being faster, I can do it.

**Comment by laanwj** [comment]
A potential fix was posted for this: Speed up getchaintips. #7827

**Comment by sipa** [comment]
utACK
