### ISSUE TITLE
Syncing of chains with different height depends on "connection direction"

### ISSUE THREAD

**Issue by domob1812** [bitcoin/bitcoin#5113]
Experimenting with a private `-regtest` network, I found the following behaviour that seems wrong:  I've got two nodes, A and B.  They are initially disconnected and A has a chain of height 210 while B has one of height 220 - they are forked at block 200.  Now I want to connect the nodes and expect that A switches to B's longer chain.

When I connect *A to B* (`addnode` call on A), this is precisely what happens.  However, when I connect *B to A* (`addnode` called on B), both keep their chains.  This seems very odd to me.  I seem to recall that "a few days ago" both alternatives resulted in the nodes syncing to the same chain.  (And can try to find out more about this / give more details if necessary.)

**Comment by laanwj** [comment]
Should be fixed by #5157
