### ISSUE TITLE
Should a warning be thrown when using -port that nodes are very unlikely to get any incoming connections? 

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#5150]
It's surprising that using a non-standard listening port will cause peers to actively avoid connecting to you, is it sensible to add this to the help message and the warnings on startup if people have changed the default? I can't find this behavior mentioned anywhere except for the comments in net.cpp. 

```
// do not allow non-default ports, unless after 50 invalid addresses selected already
if (addr.GetPort() != Params().GetDefaultPort() && nTries < 50)
continue;
```

https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L1369

**Comment by vasild** [comment]
> No, it's to prevent spamming addr messages with eg IP:80 to the network, and have the entire Bitcoin network DoS attack that service.

I don't see how such a DoS could be carried out.

* Assume 50k nodes.
* Each node has around 50k addresses in their addrman (everybody knows about mostly everybody else).
* One of the 50k addresses is `victim:80`, gossiped by a malicious actor.
* Lets assume all 50k nodes try to open a new connection to a random address from their addrman (size 50k), how many nodes will attempt to connect to `victim:80`? One (1/50k chance, multiplied by 50k attempts).
* How often will this happen? Assuming all nodes keep trying to open new connections all the time, then this will happen once per 0.5s:
https://github.com/bitcoin/bitcoin/blob/8837f1ebde0537b0fdfa1353d06ae8e61a259982/src/net.cpp#L1813
* Is one connection per 0.5s DoS? Probably not.
* Note that the above assumption of all nodes trying to open new connections all the time is not correct. Once a node has 8 (is configurable) outbound connections, it will stop opening new connections. So the above 0.5s is maybe a few seconds or even higher in practice.

This can be confirmed by observing a node that is listening on port 8333 and whose address is well propagated (has been online for a long time) and seeing how often it receives incoming connections. I have a long-running node but it is listening on non-default port, so I can't confirm that myself.

Did I oversimplify or get something wrong?
