### ISSUE TITLE
MsgAlert - relaying other full node's alerts

### ISSUE THREAD

**Issue by dajohi** [bitcoin/bitcoin#5160]
If I read the code correctly, when Bitcoin Core receives a msgalert, it checks the signature, and if that fails, increases the misbehaving score for the peer.

If another full node author/team wanted to create their own keypair to send their own msgalerts across the network, either Bitcoin Core would have to import the public key or at least not mark it as misbehaving.

My initial thought would be Bitcoin Core add a configuration option to specify additional pubkeys to trust in alert messages <b>AND</b> drop the misbehaving peer code and just silently discard it if the signature doesn't match any of the pubkeys.

This would stop other full node implementations from getting banned for sending msgalerts signed by unknown keys.

Any thoughts on this?

**Comment by jonasschnelli** [comment]
The p2p alert system has been removed in #6260. Inactivity since one year,... closing.

**Comment by davecgh** [comment]
For the record, #6260 was never merged.

**Comment by jonasschnelli** [comment]
Correct. I mixed it up with the opt out (`-alert`) https://github.com/bitcoin/bitcoin/pull/6274.

**Comment by laanwj** [comment]
But you're right in closing it. Progress on the alert system (even toward removing it!), or any new ideas regarding it have pretty much faded out without any interest. Using the alert key is extremely controversial at the moment. E.g. for the critical UPnP bug we decided against using it.

I don't personally expect it to ever be used again (barring extreme failures). There are plenty of other, more speciic, notification channels for both implementation and network-level issues.
