### ISSUE TITLE
Suboptimal Block Checks

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#5163]
Every valid block Proccess(ed) is CheckBlock(ed) three times:
- [x] 1. ProcessBlock -> CheckBlock
- [ ] 2. ProcessBlock -> AcceptBlock -> CheckBlock
- [ ] 3. ProcessBlock -> ActivateBestChain -> ActivateBestChainStep -> ConnectTip -> ConnectBlock -> CheckBlock

'Tis is an opportunity to optimize.

**Comment by laanwj** [comment]
"Eliminate unnecessary call to CheckBlock #7225" fixes one of these

**Comment by 21E14** [comment]
Great: #7225 eliminates the first call referenced (1. ProcessBlock -> CheckBlock).

**Comment by adamjonas** [comment]
ref https://github.com/bitcoin/bitcoin/pull/9765 which effectively reverted #7225

**Comment by MarcoFalke** [comment]
What is the issue here? Performance can't be the issue because of the cache:


```cpp
bool CheckBlock(const CBlock& block, BlockValidationState& state, const Consensus::Params& consensusParams, bool fCheckPOW, bool fCheckMerkleRoot)
{
    // These are checks that are independent of context.

    if (block.fChecked)
        return true;

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
