### ISSUE TITLE
Still have unicode character displaying issue in Mac OS X

### ISSUE THREAD

**Issue by victorlin** [bitcoin/bitcoin#5165]
Bitcoin-QT Version 0.9.3
Mac OS X version Yosemite 10.10
Language: Traditional Chinese

![2014-10-28 9 20 38](https://cloud.githubusercontent.com/assets/201615/4821038/feb0fa66-5f22-11e4-958d-9a650bf0bf11.png)

**Comment by jonasschnelli** [comment]
Issue still present in 0.10.0rc3 and should be addressed in 0.10.
Somehow its a GUI blocker.

osx 10.10 with bitcoin-qt 0.10.0rc3:
![bildschirmfoto 2015-01-14 um 09 26 03](https://cloud.githubusercontent.com/assets/178464/5735956/7b2e94fc-9bcf-11e4-893a-a887cf74ca2b.png)

**Comment by laanwj** [comment]
Solved by #5671
