### ISSUE TITLE
High fee warnings need to be reworked

### ISSUE THREAD

**Issue by morcos** [bitcoin/bitcoin#5202]
The code had 3 separate places where high fee values are hard coded. 
1. `WalletModel::prepareTransaction` in qt/walletmodel.cpp rejects transactions with a fee over .1 BTC initiated from QT.
2. `nHighTransactionFeeWarning` defined in wallet.h generates a warning in init.cpp if a fee amount over .01 BTC is set with `-paytxfee`
3. `AcceptToMemoryPool` in main.cpp rejects a transaction unless the override is set if the fee is greater than 10,000 times the minRelayTxFee (= ~.023 BTC for a simple 1 input, 2 output tx). 

It seems like it would make sense to consolidate to one warning level and it should be significantly lower. (maybe 1,000 times the minRelayTxFee or just a fixed amount).

From the standpoint of reworking the UI (#5200) there should be a warning that you could click through to allow the higher fee.   This would help address @petertodd's concerns in #4250.  

Also it seems like `AcceptToMemoryPool` is an odd place to have this check, perhaps we could move it somewhere else to handle an rpc initiated transaction?

**Comment by MarcoFalke** [comment]
Addressing `1.` in #6951.

**Comment by MarcoFalke** [comment]
Addressed 3. in #7084. I will fix the remaining nits hopefully next week.

**Comment by MarcoFalke** [comment]
Anything left to do here?

@morcos
