### ISSUE TITLE
[Qt] Payment request via Tor and BitPay - a NO go

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#5204]
Most likely this is a no-issue for us, because we can't solve it, but perhaps we can brainstorm some ideas if we can extend error messages or reporting stuff to users.

This is what happened, I tried to pay via BitPay using my Bitcoin Core wallet while connected to the network via Tor. After clicking the payment button on the BitPay site I got this warning displayed to me (this is from my debug.log):
`GUI: PaymentServer::netRequestFinished :  "Kommunikationsfehler mit https://bitpay.com/i/XYZ: Error downloading https://bitpay.com/i/XYZ - server replied: Forbidden"`

I know that BitPay is using Cloudflare as hoster or technical base and that Cloudflare is blocking Tor exit nodes! This is "only" annoying if visiting their site via browser, as they offer a (stupid) captcha. But it get's totally stupid if using payment requests on their site, because of not being able to proceed.

I had to reconnect with Tor disabled to do my payment, which sucked! Any ideas, for how we could handle such a case or error situation from a UX view?

**Comment by laanwj** [comment]
I think this is still an issue?

**Comment by laanwj** [comment]
I've heard reports that this is still an issue, and it became more serious now that bitpay has no way to manually specify address/amount anymore. Even when not using tor the cloudflare protection might trigger.

**Comment by TheBlueMatt** [comment]
I think the appropriate fix is to encourage more wallets to use tor to send payment requests and default to using tor if there is a tor proxy configured ourselves. Not being able to send a payment request over Tor is an issue the provider needs to fix, not us.

**Comment by iamvinny** [comment]
They have started using "Payment Protocol" (BIP 70) recently, it's hurting my business, because my customers can't pay without a specific wallet, I'll be switching to another payment processor. BitPay is only getting worse and worse...

**Comment by iamvinny** [comment]
They have published an article today, explaining why this issue happen for TOR users and a possible workaround, worth reading.

https://support.bitpay.com/hc/en-us/articles/115003014566-Why-can-t-I-pay-a-BitPay-invoice-in-my-Tor-browser-

**Comment by Stefanie80** [comment]
New problem: even payments using a supported wallet do not work anymore. Obviously has something to do with the cloudflare DDoS protection, wich prevents wallets from getting the payment details. R.I.P BitPay.
I have now installed the wallet from bitpay itself, going to test if that works. And will also reccomend to the merchant to switch to another payment processor. This is a major setback to bitcoin as a whole, because many merchants used BitPay.

**Comment by laanwj** [comment]
Closing payment protocol specific issues; as that functionality is going to be deprecated in the near future it's not worth working on.
