### ISSUE TITLE
Ubuntu Bitcoin Indicator on the top left

### ISSUE THREAD

**Issue by elichai** [bitcoin/bitcoin#5260]
The Bitcoin indicator icon is stuck on the top left on Ubuntu. But the PPA version Indicator is fine and it's on the right with all the others indicators.
and the Menu(Right click on the indicator) is more nice in the PPA version.

Git 0.9.3 version.
PPA version: v0.9.3.0-g40d2041-beta

**Comment by fanquake** [comment]
Related https://bugreports.qt.io/browse/QTBUG-31762

**Comment by fanquake** [comment]
Is this still an issue? Looks like it could be fixed with Qt 5.5

**Comment by jonasschnelli** [comment]
It's fixed in Qt5.5 which we use over the static dependencies builds ("official releases"). Closing.
