### ISSUE TITLE
walletencryption password strength (only QT)

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#5278]
I'm could not find any github-discussion about password strength of the wallet encryption passphrase.
By default all types of weak passwords are allowed (even without warning) to encrypt your wallet.

Would it not be possible to add a password strength police to the RPC command as well to the GUI form?

Suggestion:
RPC: the `encryptwallet` RPC command should reject a weak passphrase unless a `-force` arg is given (or we could even drop the -force arg and/or only allow weak passphrase if a startup-arg `-allowweakpassphrase` was set).

GUI: while entering a encryption passphrase there could be a green/orange/red icon to show the password strength. Using a "orange" or "red" password is forbidden unless he clicks through warnings or had `-allowweakpassphrase` enabled.

**Comment by MarcoFalke** [comment]
Currently, there are already suggestions on what a strong password looks like:

![screenshot from 2016-06-01 11-50-30](https://cloud.githubusercontent.com/assets/6399679/15705335/25ca1df8-27ef-11e6-90cf-ec21fedd4621.png)


I think before forcing strong passwords, we should make sure there is a convenient way to have a backup/emergency recovery passphrase. E.g printed QR-Code + small nonce written down by hand on the QR-Code. (This was suggested in in Zürich)

**Comment by MarcoFalke** [comment]
Is this still relevant after #17950 ?
