### ISSUE TITLE
Connecting to self

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#5352]
Connecting to self results in a not utterly graceful sequence of events:

Send version
Got version
connected to self at 127.0.0.1:[port #], disconnecting [ProcessMessage  main.cpp    3491]
Send ping
Send getheaders
socket send error Bad file descriptor ([#])   [SocketSendData   net.cpp 664]

Why connect to self? By mistake of course!

**Comment by MarcoFalke** [comment]
This has been fixed in 960cf2e4058a9c195bf64e1aecb46024f9ef022a, no?

Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
