### ISSUE TITLE
Before 0.10 release cleanup source with clang-style-script

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#5377]
I've been told that is the right thing to do and would like to remind for it :).

**Comment by Diapolo** [comment]
Ping, what's up with this?

**Comment by paveljanik** [comment]
Close this?

**Comment by MarcoFalke** [comment]
Or rebase #5387?

**Comment by Diapolo** [comment]
There needs something to be done, I don't and never will be understanding, why this can be such a problem...

**Comment by jonasschnelli** [comment]
@Diapolo: Pleas read https://github.com/bitcoin/bitcoin/pull/5387#issuecomment-64884398. No need to post such comments.
