### ISSUE TITLE
translations on Transifex for 0.11

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#5378]
@laanwj The last time you created a new resource for 0.10 on Transifex it was a real mess (at least for the german translation) as already translated strings got changed by unknown translators which did more harm than good because they don't know how to properly translate, as there is missing knowledge of our client and where we use strings for example.

After that I started using checked translations, so that only untranslated or unckecked/unverified translations could be edited by guest translators. Is there a way to KEEP these for 0.11 without the need for me to re-check every single translations by hand?

**Comment by laanwj** [comment]
@diapolo I used a new way to copy the translations for 0.11.x, that copies reviewer information as well
using https://gist.github.com/laanwj/5c2edf683c68697cf7f6 based on a script by @mapapage
Please verify that the settings are correct for the new resource (it currently doesn't accept translations yet).

**Comment by laanwj** [comment]
Closing this - it is done.
