### ISSUE TITLE
sendfrom fails while using zero-confirmation transaction

### ISSUE THREAD

**Issue by alpdeniz** [bitcoin/bitcoin#5383]
Bitcoind 0.9.3 cannot select zero-confirmation transaction output for sendfrom ["account" "addr" 0].

It should be free to use new transactions' inputs when explicitly defined.

**Comment by laanwj** [comment]
Bitcoin Core's wallet regards outputs of its own outgoing zero-conf transactions as spendable (unless `-spendzeroconfchange=0`), but not those of incoming transactions.

Spending the outputs of other people's transactions before they are confirmed is, in general, unsafe. Various malleability issues make that unreliable.

**Comment by promag** [comment]
@laanwj And `fundrawtransaction` should be able to select those zero-conf UTXOs? Even if they are watch only?

**Comment by laanwj** [comment]
@promag Wouldn't be against making it configurable, but by default it should have the same behavior as the other send* options I'd say.
