### ISSUE TITLE
Usage of CheckProofOfWork for block generation

### ISSUE THREAD

**Issue by 21E14** [bitcoin/bitcoin#5405]
The recent (expansion of) usage of CheckProofOfWork (pow.cpp +78) for block generation (#5275, rpcmining.cpp +181) needs an adjustment to its error output/conditions. As it stands now, every occurrence of a nonce that results in an insufficient hash is LogPrint-ed: as "CheckProofOfWork() : hash doesn't match nBits", a valuable insight when validating proof of work, but not so much when generating it.

**Comment by 21E14** [comment]
Update: #4793 reduces the (error) probability, but not to 0.

**Comment by MarcoFalke** [comment]
@21E14 Is this still an issue?

**Comment by laanwj** [comment]
CheckProofOfWork doesn't log that message anymore since #7962, a pull by the same author as this PR.
So yes we can close this.

**Comment by 21E14** [comment]
@MarcoFalke @laanwj ACK.
