### ISSUE TITLE
getaddressesbyaccount vs getaccountaddress

### ISSUE THREAD

**Issue by philsong** [bitcoin/bitcoin#5447]
I found there are 2 functions: getaddressesbyaccount, getaccountaddress,
for me, I call getaccountaddress then get one account name's bitcoin address, and then call getaddressesbyaccount(account) to get the address in next time, but when I change the address book name of that address, then getaddressesbyaccount(original name) return empty, so why design these 2 function? what's their design purpose? If I need a account to map in my own system, which one should I use?

**Comment by laanwj** [comment]
The issue for tracking the removal of the account system would be #3816. Note that there doesn't seem to be any active work in this direction: there is no real replacement, the account system keeps on existing in a state of semi-unmaintained limbo.
