### ISSUE TITLE
internal RPC/REST http server has no timeout-implementation

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#5526]
There is no connection timeout for the internal http server (REST/RPC).
Malfunction clients could produce zombi-idling rpc threads.
I had a look at it and there would be need to change the current implementation to do it async (something like boost::asio async). Currently it's a `getline()` on the raw stream.

A good starting point could be: http://www.boost.org/doc/libs/1_45_0/doc/html/boost_asio/example/timeouts/async_tcp_client.cpp

**Comment by luke-jr** [comment]
Malfunctioning clients? There's nothing wrong with clients keeping a connection open to keep-alive HTTP servers...

**Comment by kanzure** [comment]
Could be closed now that #5677 is merged? see https://github.com/bitcoin/bitcoin/pull/5677#issuecomment-78061333

@jonasschnelli @laanwj

**Comment by paveljanik** [comment]
ping :-)

**Comment by jonasschnelli** [comment]
Solved with #5677, closing.
