### ISSUE TITLE
Error initializing wallet database environment

### ISSUE THREAD

**Issue by leongaban** [bitcoin/bitcoin#5567]
Hi, I'm not sure how to debug this error.

I got Bitcoin compiled and ran sudo make install. Next I tried to run bitcoind and got the following error:

    ___________________    | ~/bitcoin @ Leons-MBP (leongaban)
    | => which bitcoind
    /usr/local/bin/bitcoind
    ___________________    | ~/bitcoin @ Leons-MBP (leongaban)
    | => which bitcoin-cli
    /usr/local/bin/bitcoin-cli
    ___________________    | ~/bitcoin @ Leons-MBP (leongaban)
    | => bitcoind
    : Error initializing wallet database environment /Users/leongaban/Library/Application Support/Bitcoin!
    ___________________    | ~/bitcoin @ Leons-MBP (leongaban)

Below is the full print out I'm getting after using `sudo make install`

    | => sudo make install
    Password:
    Making install in src
    Making install in .
     ../src/build-aux/install-sh -c -d '/usr/local/bin'
      /usr/bin/install -c bitcoind bitcoin-cli '/usr/local/bin'
    make[3]: Nothing to be done for `install-data-am'.
    Making install in qt
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
    Making install in .
     ../../src/build-aux/install-sh -c -d '/usr/local/bin'
      /usr/bin/install -c bitcoin-qt '/usr/local/bin'
    make[5]: Nothing to be done for `install-data-am'.
    Making install in test
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
     ../../../src/build-aux/install-sh -c -d '/usr/local/bin'
      /usr/bin/install -c test_bitcoin-qt '/usr/local/bin'
    make[6]: Nothing to be done for `install-data-am'.
    Making install in test
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
      CXXLD    test_bitcoin
    clang: warning: argument unused during compilation: '-pthread'
    clang: warning: argument unused during compilation: '-pie'
    ld: entry point (_main) undefined. for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[3]: *** [test_bitcoin] Error 1
    make[2]: *** [install] Error 2
    make[1]: *** [install-recursive] Error 1
    make: *** [install-recursive] Error 1

I also went back to the bitcoin folder and ran make check here is the printout:

    | => make check
    Making check in src
    Making check in .
      CXX      version.o
      AR       libbitcoin_common.a
      CXXLD    bitcoind
    clang: warning: argument unused during compilation: '-pthread'
    clang: warning: argument unused during compilation: '-pie'
      CXXLD    bitcoin-cli
    clang: warning: argument unused during compilation: '-pthread'
    clang: warning: argument unused during compilation: '-pie'
    Making check in qt
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-recursive
    Making check in .
      OBJCXXLD bitcoin-qt
    clang: warning: argument unused during compilation: '-pie'
    Making check in test
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
      CXXLD    test_bitcoin-qt
    clang: warning: argument unused during compilation: '-pie'
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
    PASS: test_bitcoin-qt
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
    make[9]: Nothing to be done for `all-am'.
    ============================================================================
    Testsuite summary for Bitcoin Core 0.9.3
    ============================================================================
    # TOTAL: 1
    # PASS:  1
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  0
    # XPASS: 0
    # ERROR: 0
    ============================================================================
    Making check in test
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
      CXXLD    test_bitcoin
    clang: warning: argument unused during compilation: '-pthread'
    clang: warning: argument unused during compilation: '-pie'
    ld: entry point (_main) undefined. for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[3]: *** [test_bitcoin] Error 1
    make[2]: *** [check] Error 2
    make[1]: *** [check-recursive] Error 1
    make: *** [check-recursive] Error 1

**Comment by jonasschnelli** [comment]
Did you follow the file `docs/build-osx.md`?
Did you change the `bitcoin.conf` or gave any starup arguments?
Did you try to remove `/Users/leongaban/Library/Application Support/Bitcoin` to get a fresh start?

**Comment by leongaban** [comment]
No, I gave up.... will trash everything and start over again. This can be closed...
