### ISSUE TITLE
wallet RPC to get in/out transaction count

### ISSUE THREAD

**Issue by bitcreditscc** [bitcoin/bitcoin#5572]
can we please have gettxincount and gettxoutcount as wallet rpc commands, as adoption increases, more and more specific data is required from the application, and since the majority won't have the coding skills to do it, it would be nice if it came with the reference client.

**Comment by luke-jr** [comment]
Might make more sense to add these to getwalletinfo?

**Comment by bitcreditscc** [comment]
Makes sense, yes.

**Comment by luke-jr** [comment]
Note: This would currently require counting every single transaction.

**Comment by bitcreditscc** [comment]
doesn't list transactions already count every tx? this would be a more detailed response.

**Comment by sipa** [comment]
How is it more detailed if you can already derive the result from
listtransaction's output?

**Comment by bitcreditscc** [comment]
listtransactions output is just the TOTAL, the request is for a separate count that tells me how many sent and how many received. I think with accounts going out  and more emphasis on one time use of addresses, this is something worth thinking about .

**Comment by sipa** [comment]
My point is that listtransactions already lists the incoming and outgoing transactions - you can compute the counts by just looking at the output of it. So it is not 'more detailed'.

**Comment by bitcreditscc** [comment]
i'm asking for something like this to be added to getwalletinfo

21:01:25
￼
getwalletinfo


21:01:25
￼
{
"walletversion" : 
"balance" : 
"txcount" : ,
"txincount":
"txoutcount":
"keypoololdest" : 
"keypoolsize" : 
}


or something along those lines.
