### ISSUE TITLE
Ability to examine, save locked-UTXO state

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#5584]
RPCs `lockunspent` and `listlockunspent` will freeze specific unspent outputs, preventing their use in automatic coin selection.

This state needs to be saved between restarts.  Separate balances for locked/unlocked should be indicated in RPC.

See issue #1637 comments, and related discussions.

**Comment by btcdrak** [comment]
+1

**Comment by jgarzik** [comment]
Still applicable - closing due to not-likely-to-see-action
