### ISSUE TITLE
std::bad_alloc crashes while processing blocks

### ISSUE THREAD

**Issue by patrikr** [bitcoin/bitcoin#5596]
Bitcoin Core v 0.10.0rc1
OS: Windows XP (32 bit)
Memory: 2 GB

While catching up with the blockchain, I get this crash every few hours:

![bc_crash1](https://cloud.githubusercontent.com/assets/802611/5604596/6d2a536c-93cf-11e4-9256-985287e8b97e.png)

debug.log:

    2015-01-03 23:59:09 UpdateTip: new best=0000000000000000096d8fc77a645408571f25104d2b596041c5c2a037038e6f  height=334892  log2_work=81.779496  tx=54399674  date=2014-12-19 00:22:26 progress=0.963288  cache=170409
    2015-01-03 23:59:32 

    ************************
    EXCEPTION: St9bad_alloc       
    std::bad_alloc       
    D:\programs\bitcoin-0.10.0rc1\bitcoin-qt.exe in ProcessMessages()       

    2015-01-03 23:59:32 ProcessMessage(block, 999803 bytes) FAILED peer=16

I've noticed that this occurs when the "cache=" part of the "UpdateTip" lines is about to go from 170k+ back to zero. When I restart it then starts over from the last block where cache=0, which means I lose about half an hour of work. (The time it takes this computer to go from cache=0 to cache=170000.)

**Comment by sipa** [comment]
How much is your dbcache set to? This looks like out-of-memory...

**Comment by patrikr** [comment]
I have not changed the dbcache, AFAIK, so it should have the default value.

**Comment by patrikr** [comment]
I tried dbcache=50, and that helped: I was able to sync the last 2 weeks of the blockchain without crashes.

**Comment by patrikr** [comment]
Closed? Is the bug fixed?

**Comment by patrikr** [comment]
Running out of memory is not a bug, but crashing and losing a lot of work when you run out of memory, that is a bug.

**Comment by laanwj** [comment]
Continuous work is underway to e.g. reduce bitcoind's memory footprint. But that doesn't warrant keeping open this issue.

As for losing work, syncing to disk only once per hour (or once the cache is full) is a conscious choice for performance. If you want more frequent flushes, you can reduce the dbsize, which you did. Hey at least it picks up again and it doesn't have to start over from scratch.
