### ISSUE TITLE
need a working payment request generator

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#5630]
@gavinandresen Could you rework your generator under https://bitcoincore.org/~gavin/createpaymentrequest.php to allow zero amounts and also add some possibility to allow creating a valid authenticated testnet payment request?

I'm mostly using your site to test changes I make to our implementation, but can't get any valid authenticated request from it because of ``GUI: PaymentRequestPlus::getMerchant: Payment request: certificate chain empty``.

I'd also like to be able to implement and test setting the (as per BIP70 optional) amount field to zero and query the user for an amount, which I can't because your page doesn't allow it :).

Thanks!

**Comment by laanwj** [comment]
See here for source of Gavin's payment request generator: https://github.com/gavinandresen/paymentrequest
Any feature requests would also belong there.
