### ISSUE TITLE
List in the QT interface all addresses in the listaccounts console command

### ISSUE THREAD

**Issue by FabioCarpi** [bitcoin/bitcoin#5641]
List in the QT interface all addresses in the listaccounts console command

**Comment by luke-jr** [comment]
listaccounts does not show addresses, and accounts are going to be deprecated entirely shortly.

**Comment by FabioCarpi** [comment]
i see. i use the new command addmultisigaddress hoping the address shows in the interface...

**Comment by luke-jr** [comment]
Lists of addresses aren't particularly useful, since addresses should only ever be used once. Last I checked (0.8.x), however, addmultisigaddress *did* in fact put them in the address list...

**Comment by laanwj** [comment]
In general, the RPC account system and the GUI label system are not designed to interact. Due to historical mess-up, they use the same backend storage for different purposes.

Although it shouldn't be that any addresses that are in active use stay hidden in the UI.

**Comment by FabioCarpi** [comment]
so... please enable the field address in interface to add watch only addresses
