### ISSUE TITLE
"Large valid fork found" , stuck at block 322082

### ISSUE THREAD

**Issue by kuerzn** [bitcoin/bitcoin#5645]
I get this error:

    2015-01-12 05:00:27 CheckForkWarningConditions: Warning: Large valid fork found
    forking the 
    chain at height 322082
    (00000000000000001e6da8c11a8669fa7353cb5f56d5679591b10072f49e5cd2)
    lasting to height 322582
    (0000000000000000132f055726222e5936e01c0bf933521defb57836aa32e423).
    Chain state database corruption likely. ````

I use the following Bitcoin Core version from the Arch Linux Repository

    v0.9.3.0-g40d2041-beta (64-bit)

I tried the following:

A) Sync complete blockchain from network
B) Bootstrap with torrent from Block 317000
C) reindex
D) Quad-core Intel i5
E) Dual-core Intel Core 2 Duo
F) txindex=1
G) txindex=0
H) Extract clean blocks with linearize and use that to bootstrap
I) par=1

in these combinations:

A,E,G
C,D,G
C,D,F
C,D,F
C,H,F
B,D,F

Right now I am trying
C,D,F,I

Also, there are six other nodes stuck at this block:
https://getaddr.bitnodes.io/nodes/?q=322082

Why is this process so error prone? Other people have similar problems:

#4125
#2726
#4064

And I think there are many more out there, who simply stop trying after DAYS of waiting and reindexing.

I also think that the argument "if this was a common problem we would have heard about it from more people" is wrong:

The number of full nodes is small and shrinking. So there are not that many nodes using a certain version of the software trying to get the whole blockchain working from 0. In my example the Block is from Sept 22, 2014, which implies that all nodes that updated to 0.9.3 (released Sept 27) did not even have to deal with this block. Furthermore, there are many possible combinations of different systems and configuration options, that might affect this kind of problem. We need to accept, that these bugs would be hard to spot! And as a consequence, we have to take people reporting these kinds of problems more seriously!

I bet, that if every node out there were to reindex its blockchain with 0.9.3 there would be a major fork!

**Comment by laanwj** [comment]
No need to rant. What version of OpenSSL?
Could be this issue: http://sourceforge.net/p/bitcoin/mailman/message/33222029/

In that case, you need to upgrade to 0.9.4.

**Comment by kuerzn** [comment]
Yes its OpenSSL 1.0.1k.

Thank you very much for pointing this out!
I used the binaries from bitcoin.org and it works now.

Sorry for the rant

**Comment by gavinandresen** [comment]
Please rant at your distro maintainer; we have been preaching the "You Must Ship Statically Linked BItcoin Binaries" gospel for a long time, but we run up against the "Thou Shalt Not Ship Statically Linked Binaries" religion.

**Comment by kuerzn** [comment]
Ok! When will distro maintainers understand that bitcoin is a special case?
Please keep up the good work!

**Comment by nkubarelov** [comment]
Stuck at the same block (322082). Bitcoin-qt installed from package, i'm running Debian sid.

**Comment by laanwj** [comment]
Push your distro maintainer to upgrade their package to 0.9.4.

**Comment by airgapped** [comment]
I have first experienced the same problem with 0.9.3.
Having the same problem with 0.10.0 node I have build from source:

$ /usr/local/bin/bitcoin-cli getinfo
{
    "version" : 100000,
    "protocolversion" : 70002,
    "blocks" : 322082,
    "timeoffset" : -1,
    "connections" : 14,
    "proxy" : "",
    "difficulty" : 29829733124.04041672,
    "testnet" : false,
    "relayfee" : 0.00001000,
    "errors" : ""
}

Running:
OpenSSL 1.0.1e 11 Feb 2013
Debian

**Comment by rebroad** [comment]
I am also having this problem. I'm using bitcoin-qt compiled myself. Perhaps the build instructions need updating?
