### ISSUE TITLE
RC3 - Missing "Open URI..." icon - 

### ISSUE THREAD

**Issue by HostFat** [bitcoin/bitcoin#5646]
I'm running this build now:
http://luke.dashjr.org/programs/bitcoin/files/bitcoind/0.10.0/test/rc3/

Actual OS:
Windows 7 x64

http://i.imgur.com/rWnCzoB.png

**Comment by Diapolo** [comment]
@HostFat This IS the default icon for URIs, I wonder why you see that icon set... thought we changed this with 0.10 (@laanwj)?

**Comment by luke-jr** [comment]
@Diapolo the new icons were merged for 0.11, not 0.10

**Comment by Diapolo** [comment]
@luke-jr Right, so this is a no-issue, as I can confirm the icon shown is indeed the icon I got the whole time on Windows.

@HostFat Can you close the issue please?
