### ISSUE TITLE
[Qt] Linux/Ubuntu: icon colors in tray-like context menu on ubuntu default theme looks bad

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#5653]
Would it not somehow be possible to use the same icon color like in the main window?

![bildschirmfoto 2015-01-13 um 08 52 10](https://cloud.githubusercontent.com/assets/178464/5717470/7c44a7f6-9b01-11e4-80a1-16c9530d7593.png)

**Comment by jonasschnelli** [comment]
@luke-jr maybe also something you could have a look at?

**Comment by luke-jr** [comment]
No, the button icon colour is highlight-colour. Which means it would match the colour of the selection when the item is hovered over (assuming a working menu). The solution to this would be to find some way to determine the non-standard systray-menu-text-colour and match it for the systray-menu icons..

**Comment by jonasschnelli** [comment]
Maybe a different color (maybe windows title bar background color) is always the same.
Okay, will have a look at this... in near future...

**Comment by MeshCollider** [comment]
Colour of the icon seems relatively unimportant to leave open for nearly 3 years, @jonasschnelli is this stale and to-be-closed?
