### ISSUE TITLE
Building on SmartOS (Solaris/illumos derivative)

### ISSUE THREAD

**Issue by epipenau** [bitcoin/bitcoin#5659]
edited build-aux/m4/bitcoin_find_bdb48.m4 by editing line 56 to read:

for searchlib in db_cxx-4.8 db_cxx db4_cxx-4.8 db4_cxx; do

in configure.ac I replaced all instances of HEXDUMP and hexdump with OD and od respectively.

edited the HEXDUMP test which was in a Makefile which I now can't seem to find, changed @HEXDUMP@ to @OD@, hexdump to od, left the -v flag and changed the -e flag to -t.

(it has been suggested to me that the change to OD over HEXDUMP should be preferred because OD is POSIX compliant and HEXDUMP is not.)

in src/compat.h line 39 before #include <net/if.h> i added #define map junkmap
and on line 41 after #include <net/if.h> i added #undef map
---- this is because net/if.h has a struct map which makes the std map ambiguous. ----

there is still another ambiguous map in rpcserver that i haven't fixed yet.  i'll keep trying and if i do i'll post here otherwise i'm sure someone else can handle it.

**Comment by wtogami** [comment]
I suspect cfields can figure out how to fix your OS build from what you described above.  It might be faster if you can figure out how to patch configure.ac yourself.  If you do so, please test it on Linux and other supported OS's to be sure it doesn't break other users.

**Comment by theuni** [comment]
hexdump/od change seems sane. likewise for the bdb change.

For the ambiguous maps, don't mess with defines, just replace them with std::map. That needs to be done anyway.

**Comment by epipenau** [comment]
yeah, on my way home i was thinking i would write a post suggesting just that changing map to std::map.
that's what I originally did with the 0.8 code, but when porting numerous coin's to smartos, i found it was much quicker to just redefine map, but i have found with 0.10 the reference to net/if.h via boost is a lot more complicated to work around and can't be accomplised by a simple redefine.
I will do the changes and submit a pull request by Monday at the latest.

Date: Thu, 15 Jan 2015 19:11:23 -0800

**Comment by laanwj** [comment]
>  I will do the changes and submit a pull request by Monday at the latest.

Ping :)

**Comment by epipenau** [comment]
I got otherwise occupied from this, but given all that was left to do was change map to std::map.  i thought someone else would have taken care of this by now.  however, having said that if it really is down to me, i might be able to find time to do it but on certainly no given schedule.

**Comment by laanwj** [comment]
It was just a reminder, I"m not trying to pressure you into doing anything. I think you're the only person caring about this OS. If you no longer do, I'm also fine with just closing this and forgetting about it.

**Comment by epipenau** [comment]
well 'theuni' is correct, 

all that needs to be done is change map to std::map, the way it should be anyway.

it's better tidier practice to neaten them up now that wat they wont grow into being a bigger problem down the track.

having said that i dont know if you're a coder or just a thread moderator.

if you still choose not to do it, i will probably revisit this in the future.
