### ISSUE TITLE
getrawtransaction code 5

### ISSUE THREAD

**Issue by FabioCarpi** [bitcoin/bitcoin#5661]
in bitcoin-qt 0.10rc1

17:55:17 ￼ getrawtransaction f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16
17:55:17 ￼ No information available about transaction (code -5)

https://blockchain.info/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16

**Comment by jonasschnelli** [comment]
Did you use the `-txindex` arg?

From the `getrawtransaction` help:
> ... To make it always work, you need to maintain a transaction index, using the -txindex command line option...

**Comment by FabioCarpi** [comment]
ty
