### ISSUE TITLE
getrawtransaction fails

### ISSUE THREAD

**Issue by FabioCarpi** [bitcoin/bitcoin#5667]
16:07:31￼getrawtransaction 1d37eb24cc04fd20a68d1bf9a8ceec42cf5e4e3be5bf3768bcc3339bbd2c05c2
16:07:31￼No information available about transaction (code -5)

https://blockchain.info/tx/1d37eb24cc04fd20a68d1bf9a8ceec42cf5e4e3be5bf3768bcc3339bbd2c05c2

bitcoin-qt 0.10rc1
txindex=1 in bitcoin.conf

**Comment by jonasschnelli** [comment]
did you use `-txindex=1` together with `-reindex=1`?

**Comment by FabioCarpi** [comment]
when i put the txindex=1 in conf, the program re-download all blocks

**Comment by jonasschnelli** [comment]
@FabioCarpi no, that should not be the case.
you must run once with `-txindex=1` `-reindex=1` to rebuild your blockchain indices.
This will take =time= but will not download the blocks again.
