### ISSUE TITLE
RC3 startup is much slower than RC1

### ISSUE THREAD

**Issue by patrikr** [bitcoin/bitcoin#5672]
The "Verifying last 288 blocks at level 3" phase takes much longer in RC3 than it did in RC1. RC1 was about 3-4 minutes. I've now started RC3 twice, and it took 13 and 18 minutes. This is about as bad as 0.9.3, which sometimes took over 20 minutes.

OS: Windows XP 32-bit

**Comment by sipa** [comment]
Nothing changed between rc1 and rc3 related to that. Are you sure it's not a disk cache issue or a change in -dbcache between the two attempts (a *lower* dbcache value is actually faster, as the expensive part of the validation is only done until the dbcache fills up; with a lower value it effectively doesn't verify as much).

**Comment by patrikr** [comment]
Hm. I shut down a background program (data logger for a USB thermometer) and that solved the problem. Weird. The data logger was using a bit of CPU, but I don't see how it could have slowed Bitcoin Core down by a factor of 5. I wonder if it's got something to do with the fact that I keep the Bitcoin data directory on an external USB drive. Maybe the data logger was spamming the USB controller or something?

**Comment by laanwj** [comment]
You can exactly control how much work the startup check will do using -checkblocks=X and -checkblocksverify=X.

Leveldb generates quite a lot of I/O traffic during the check. If you add more devices that consume bandwidth on the bus it's thus going to be slower.

**Comment by patrikr** [comment]
After some more testing I actually think the slowness was due to Windows being low on memory. I got the slow startup also while the USB thermometer program wasn't running, but after killing off a bunch of Google Chrome processes to get the memory usage down, Bitcoin started quickly again. I wonder if I never tested RC1 with Chrome being quite as bloated, or if something is different in RC3...
