### ISSUE TITLE
Errors on building from source 

### ISSUE THREAD

**Issue by bitcreditscc** [bitcoin/bitcoin#5676]
configure.ac:202: error: possibly undefined macro: AC_CHECK_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:680: error: possibly undefined macro: PKG_CHECK_MODULES
configure.ac:691: error: possibly undefined macro: AC_CHECK_HEADER
autoreconf: /usr/bin/autoconf-2.68 failed with exit status: 1

Not sure what is causing this, i can source from last week, but this week's spits errors.

**Comment by fanquake** [comment]
@bitcreditscc Is pkg-config installed?

**Comment by bitcreditscc** [comment]
@fanquake yes it is,

**Comment by lucayepa** [comment]
#5688 has modified this. Can you check if now is ok?
