### ISSUE TITLE
Missing cs_main lock in ProcessMessage()

### ISSUE THREAD

**Issue by johannes87** [bitcoin/bitcoin#5678]
ProcessMessage() in net.cpp calls "Misbehaving()", which requires the cs_main lock. However, the lock is not aquired in ProcessMessage.

**Comment by laanwj** [comment]
Good catch.

The most straightforward solution would be for the function to do the locking itself, e.g. add a LOCK(cs_main) at the top of that function.

**Comment by johannes87** [comment]
On a side note: wouldn't it be better, performance-wise, to use a separate lock for the mapNodeState data structure, instead of using the global cs_main lock?

**Comment by laanwj** [comment]
Yes, more granular locking would help performance. The cs_main lock is heavily contended. But be careful not to introduce deadlocks. Which is easier if the locks are properly encapsulated inside data structures, which is the direction things should be moving anyhow.

**Comment by johannes87** [comment]
It looks like the lock in "ProcessBlockAvailability()" is missing, too?

**Comment by fanquake** [comment]
Closing as fixed in #7942
