### ISSUE TITLE
Stuck on block 339768

### ISSUE THREAD

**Issue by welshjf** [bitcoin/bitcoin#5687]
I've been running 0.10.0rc1 for a couple weeks with no problems until now. It's stuck on block 339768, hash 0000000000000000160483c084b185b87e974467e0f684a1b26cc555174b59c7, currently about 7 hours old. I have 34 peer connections and ~33k transactions in my mempool. In debug.log I'm seeing a lot of AcceptToMemoryPool errors; not sure what else to look for.

This is on Linux x86_64, using the binary downloaded from bitcoin.org. I've confirmed I'm not out of disk space.

I notice there's an rc3 up now, but I'll hold off on restarting or upgrading in case there's anything you want me to try first.

**Comment by sipa** [comment]
Thanks for reporting. AcceptToMemoryPool errors are expected if you're not receiving new blocks.

Can you just try restarting? If this is a case of the (known) problem with rc1 that is fixed by rc3, restarting should also fix it.

**Comment by welshjf** [comment]
Restarted, and it synced up right away.
