### ISSUE TITLE
export wallet in plain text

### ISSUE THREAD

**Issue by cjeanneret** [bitcoin/bitcoin#5690]
Hello,

would be great if there were a way to export the wallet as plain text or, at least, get the wallet seed in order to re-import it in some other application.

I tried to find something in the GUI and CLI options but didn't see anything like that…

Thank you!

**Comment by jonasschnelli** [comment]
Did you try the rpc command `dumpwallet`. There you can have a dump of your keys. But remind that the dump contains no metadata.

**Comment by cjeanneret** [comment]
Hmm, not really used to RPC, any example using curl? not really convenient -.-…

**Comment by cjeanneret** [comment]
ah, got it. For the records:
```Bash
bitcoin-qt -server -rpcuser=USERNAME -rpcpassword=PASSWORD -rpcport=9001 -rpcallowip=127.0.0.1

curl -X POST -d '{"jsonrpc":"1.0", "id":"curl","method": "dumpwallet", "params": ["output.txt"]}' -H "Content-Type: text/plain" -u USERNAME:PASSWORD localhost:9001
```

You might as well dump only the private key like this:
```Bash
curl -X POST -d '{"jsonrpc":"1.0", "id":"curl","method": "dumpprivkey", "params": ["public_key"]}' -H "Content-Type: text/plain" -u USERNAME:PASSWORD localhost:9001
```

**Comment by jonasschnelli** [comment]
@cjeanneret don't make it to complicate. Try to use the `bitcoin-cli`.

**Comment by cjeanneret** [comment]
hmm, not included in bitcoin-qt package (on debian), seems I need "bitcoind" package instead. Nevermind, I could at least get the keys… but it seems I'm unable to import them in some other app. Will dig a bit more.
