### ISSUE TITLE
Coin Control first column label is "1"?

### ISSUE THREAD

**Issue by wtogami** [bitcoin/bitcoin#5716]
Coin Control's first column label is simply "1".  What is that supposed to mean?

![screenshot from 2015-01-26 20 09 27](https://cloud.githubusercontent.com/assets/93665/5914309/69783264-a597-11e4-8dbf-7c9126d12c4a.png)

**Comment by cozz** [comment]
The label is supposed to be empty.
See https://github.com/bitcoin/bitcoin/blob/master/src/qt/forms/coincontroldialog.ui#L444

It was empty before, dont know which change let appear the "1" there and why, seems weird.

**Comment by jonasschnelli** [comment]
This is a linux only bug.
I assume setting a empty string or even a 1 char whitespace (" ") could fix this issue.
@wtogami: mind creating a fix for this?

Win/OSX OK:
![bildschirmfoto 2015-01-28 um 20 16 05](https://cloud.githubusercontent.com/assets/178464/5944869/909fbe90-a72a-11e4-90d5-cf4ab72a6643.png)
![bildschirmfoto 2015-01-28 um 20 13 21](https://cloud.githubusercontent.com/assets/178464/5944872/9c533884-a72a-11e4-8b3b-3658aa8b491f.png)

Linux/Ubuntu NOK:
![bildschirmfoto 2015-01-28 um 20 14 51](https://cloud.githubusercontent.com/assets/178464/5944873/a099f5d6-a72a-11e4-826a-ccce10290279.png)

**Comment by fsb4000** [comment]
**jonasschnelli:**
>This is a linux only bug.

Not only. For reproducing on Windows simple compile with Qt 4.8.6. I think it is a Qt4 bug...

**Comment by jonasschnelli** [comment]
@fsb4000 Truly!

**Comment by laanwj** [comment]
fixed by #5720
