### ISSUE TITLE
Payment protocol: Can change amount displayed using scroll wheel

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#5724]
I can't type in numbers, but the scroll wheel will change the amount displayed just fine. Sending seems to ignore the changed value, though, so this is mostly cosmetic (although users might get annoyed if they try to send 0.01 BTC and end up sending the original 0.10 BTC amount...)

**Comment by jonasschnelli** [comment]
I tried this with last nights nighty build and cannot reproduce this issue. I tried with the mouse-scroll wheel as well by pressing the up/down button. I could not change the value in the field.

Tested on OSX, Windows 7 and Ubuntu.

![bildschirmfoto 2015-01-30 um 13 46 41](https://cloud.githubusercontent.com/assets/178464/5975899/80640e60-a887-11e4-91fd-15148bd6ef79.png)
![bildschirmfoto 2015-01-30 um 13 51 20](https://cloud.githubusercontent.com/assets/178464/5975900/80838bdc-a887-11e4-9f5d-d59a0d1cec7b.png)

![bildschirmfoto 2015-01-30 um 13 54 27](https://cloud.githubusercontent.com/assets/178464/5975903/88cd5a52-a887-11e4-8b3f-a05012bb354f.png)

**Comment by luke-jr** [comment]
It affects at least c5044bc1693ced50ed070a27e7d2f3174202ace5 for me.

**Comment by jonasschnelli** [comment]
I did a test with 9fe53a85e0e50ca82e369b7d29485a0a6f0f8dbf.
Maybe you find time to retest with current master or https://builds.jonasschnelli.ch/nightlybuilds/2015-01-30/.

**Comment by luke-jr** [comment]
Confirmed this is fixed in d781d4725cf49dff8408e61e09dbc8b8db621e75, so maybe just needs a 0.10 backport.

**Comment by jonasschnelli** [comment]
If it's not a 0.10 blocker it might be better to take this into the next release?
Nevertheless we first need to find the fixing commit.

**Comment by luke-jr** [comment]
Confirmed this was fixed by 0fd9e2bf43d217d9a76003476661c8ab53606548 [Qt] don't allow amount changes when AmountSpinBox is read-only

**Comment by laanwj** [comment]
Backported that commit to 0.10 as 6a02ef8
