### ISSUE TITLE
Payment protocol: Cannot change display unit for amount

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#5725]
While it makes sense to lock the amount, it does not make sense to lock the unit being used to display it.

**Comment by jonasschnelli** [comment]
You can change the unit at the status bar of the window (bottom right). But yes. I would also see the unit dropdown as not read-only.

**Comment by Diapolo** [comment]
@luke-jr See referenced pull.

**Comment by jonasschnelli** [comment]
fixed by #5729.
Can be closed.
