### ISSUE TITLE
How to build the application on Windows 7

### ISSUE THREAD

**Issue by alexvornoffice** [bitcoin/bitcoin#5748]
HI! How to create the application on Windows?
I downloaded all source files and extracted into a folder, what should I do next?
Do I need to have Linux to compile the application?

(I created this ticket because I think there is poor information on this topic. More docs need to be added to address this issue.)

Thanks.

**Comment by luke-jr** [comment]
You may need to contribute such documentation. There is no supported method to compile Bitcoin Core on Windows at this time (other than running a Linux VM).

**Comment by luke-jr** [comment]
Maybe @Diapolo can assist with this (AFAIK he is the only dev who runs Windows), but IIRC he uses some qmake-based hack.

**Comment by laanwj** [comment]
If you feel like messing around with msys2/mingw-w64 you could probably get it to work, but the easiest way to create windows executables is to cross-compile from Linux.
Closing this, as it is not really an issue.
