### ISSUE TITLE
rpc method to get address for private key

### ISSUE THREAD

**Issue by y** [bitcoin/bitcoin#5763]
I need the inverse of dumpprivkey. Given a private key, I need to get the corresponding address.

**Comment by paveljanik** [comment]
> I need the inverse of dumpprivkey. Given a private key, I need to get the corresponding address.

If you have the private key, you can use several utilities to get the address (google for sx, ku, pybitcointools, ...). This surely doesn’t belong to RPC. Private key is cryptographic material!!!

Please close this issue.

**Comment by laanwj** [comment]
Agree with @paveljanik . What you are proposing is a pure utility function, which does not require any of bitcoind's state. A better place for it would be in a library, and indeed there are various such libraries available for different programming languages (e.g. bitcoin-pythonlib for python). There is no advantage (and insecurity through potential interception) to using RPC, and also bottleneck issues.

**Comment by y** [comment]
I disagree. I'm trying to implement a script that sweeps cold storage private keys and am using the rpc methods createrawtransaction/signrawtransaction. You might as well argue that signrawtransaction belongs outside of bitcoind because the same reasoning applies.

**Comment by theuni** [comment]
Agree with @paveljanik and @laanwj above.

signrawtransaction has logic to pick the correct private key based on the transaction and the available keys. privkey -> pubkey is a state-less calculation.

If anything (not actually suggesting, only an example), a separate bitcoin-util cli app would make more sense for these types of simple conversions, similar to pycoin's ku.
