### ISSUE TITLE
compile error: Error: no such instruction: `b128 0x1e3'

### ISSUE THREAD

**Issue by eN0Rm** [bitcoin/bitcoin#5767]
```
make
Making all in src
make[1]: Entering directory `/home/fredrik/bitcoin.node/bitcoin/src'
make[2]: Entering directory `/home/fredrik/bitcoin.node/bitcoin/src'
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      libbitcoinconsensus_la-eccryptoverify.lo
  CXX      libbitcoinconsensus_la-ecwrapper.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
  CXXLD    libbitcoinconsensus.la
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-leveldbwrapper.o
  CXX      libbitcoin_server_a-main.o
/tmp/ccHyCCui.s: Assembler messages:
/tmp/ccHyCCui.s:1426669: Error: no such instruction: `b128 0x1e3'
/tmp/ccHyCCui.s:1701893: Error: junk at end of line, first unrecognized character is `5'
make[2]: *** [libbitcoin_server_a-main.o] Error 1
make[2]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin/src'
make: *** [all-recursive] Error 1
```

cpuinfo from guest 
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel Xeon E312xx (Sandy Bridge)
stepping        : 1
microcode       : 0x1
cpu MHz         : 1895.614
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm xsaveopt
bogomips        : 3791.22
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

This is cpuinfo from host

```
cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping        : 1
microcode       : 0x16
cpu MHz         : 2039.011
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 3791.32
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping        : 1
microcode       : 0x16
cpu MHz         : 1562.898
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 3791.32
clflush size    : 64
cache_alignment : 64
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 3791.32
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
stepping        : 1
microcode       : 0x16
cpu MHz         : 1412.753
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
bogomips        : 3791.32
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

Ubuntu 14.10 Host, Ubuntu 14.04 Guest.

**Comment by paveljanik** [comment]
The question will look strange but: do you have enough disk space?

**Comment by eN0Rm** [comment]
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        98G   36G   57G  39% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            487M  4.0K  487M   1% /dev
tmpfs           100M  396K  100M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            497M   72K  497M   1% /run/shm
none            100M     0  100M   0% /run/user
```

On Sat, Feb 7, 2015 at 9:19 PM, paveljanik <notifications@github.com> wrote:

> The question will look strange but: do you have enough disk space?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin/issues/5767#issuecomment-73381057>.
>



-- 
Mvh
-fredrik-normann-

Sent from my Gmail Account

**Comment by eN0Rm** [comment]
Host
```
Linux BigBrother 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Guest 
```
Linux bitNORm 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by paveljanik** [comment]
Is it repeatable? If so, can you please run `make V=1` and paste the command building the `main.cpp`?
It would be nice to save assembler output (`gcc -S`?) and upload it somewhere.
What versions of `gcc`/`as` do you have?

**Comment by paveljanik** [comment]
Any `-march` or other `-m` option on the cmdline?

**Comment by eN0Rm** [comment]
no -march or -m options. 


```
4 fredrik@bitNORm:~> as -V
GNU assembler version 2.24 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.24
^C

4 fredrik@bitNORm:~> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by eN0Rm** [comment]
running make V=1 now so fare so good

On Sat, Feb 7, 2015 at 9:35 PM, paveljanik <notifications@github.com> wrote:

> Is it repeatable? If so, can you please run make V=1 and paste the
> command building the main.cpp?
> It would be nice to save assembler output (gcc -S?) and upload it
> somewhere.
> What versions of gcc/as do you have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin/issues/5767#issuecomment-73381783>.
>



-- 
Mvh
-fredrik-normann-

Sent from my Gmail Account

**Comment by paveljanik** [comment]
V=1 makes it only verbose, nothing else. So it seems to be non-repeatable.

**Comment by eN0Rm** [comment]
g++ -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread
-I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv
-I./secp256k1/include  -I./test/ -DBOOST_TEST_DYN_LINK
-DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -g -O2 -Wall -Wextra -Wformat
-Wformat-security -Wno-unused-parameter  -Wstack-protector
-fstack-protector-all -fPIE -fvisibility=hidden -MT
test/test_test_bitcoin-rpc_wallet_tests.o -MD -MP -MF
test/.deps/test_test_bitcoin-rpc_wallet_tests.Tpo -c -o
test/test_test_bitcoin-rpc_wallet_tests.o `test -f
'test/rpc_wallet_tests.cpp' || echo './'`test/rpc_wallet_tests.cpp
mv -f test/.deps/test_test_bitcoin-rpc_wallet_tests.Tpo
test/.deps/test_test_bitcoin-rpc_wallet_tests.Po
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -Wall -Wextra
-Wformat -Wformat-security -Wno-unused-parameter  -Wstack-protector
-fstack-protector-all -fPIE -fvisibility=hidden -Wl,--exclude-libs,ALL
-pthread   -static -Wl,-z,relro -Wl,-z,now -pie -o test/test_bitcoin
test/test_test_bitcoin-arith_uint256_tests.o
test/test_test_bitcoin-alert_tests.o
test/test_test_bitcoin-allocator_tests.o
test/test_test_bitcoin-base32_tests.o test/test_test_bitcoin-base58_tests.o
test/test_test_bitcoin-base64_tests.o test/test_test_bitcoin-bloom_tests.o
test/test_test_bitcoin-checkblock_tests.o
test/test_test_bitcoin-Checkpoints_tests.o
test/test_test_bitcoin-coins_tests.o
test/test_test_bitcoin-compress_tests.o
test/test_test_bitcoin-crypto_tests.o test/test_test_bitcoin-DoS_tests.o
test/test_test_bitcoin-getarg_tests.o test/test_test_bitcoin-hash_tests.o
test/test_test_bitcoin-key_tests.o test/test_test_bitcoin-main_tests.o
test/test_test_bitcoin-miner_tests.o test/test_test_bitcoin-mruset_tests.o
test/test_test_bitcoin-multisig_tests.o
test/test_test_bitcoin-netbase_tests.o test/test_test_bitcoin-pmt_tests.o
test/test_test_bitcoin-rpc_tests.o test/test_test_bitcoin-sanity_tests.o
test/test_test_bitcoin-script_P2SH_tests.o
test/test_test_bitcoin-script_tests.o
test/test_test_bitcoin-scriptnum_tests.o
test/test_test_bitcoin-serialize_tests.o
test/test_test_bitcoin-sighash_tests.o
test/test_test_bitcoin-sigopcount_tests.o
test/test_test_bitcoin-skiplist_tests.o
test/test_test_bitcoin-test_bitcoin.o
test/test_test_bitcoin-timedata_tests.o
test/test_test_bitcoin-transaction_tests.o
test/test_test_bitcoin-uint256_tests.o
test/test_test_bitcoin-univalue_tests.o test/test_test_bitcoin-util_tests.o
test/test_test_bitcoin-accounting_tests.o
test/test_test_bitcoin-wallet_tests.o
test/test_test_bitcoin-rpc_wallet_tests.o     libbitcoin_server.a
libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a
crypto/libbitcoin_crypto.a univalue/libbitcoin_univalue.a
./leveldb/libleveldb.a ./leveldb/libmemenv.a -L/usr/lib/x86_64-linux-gnu
-lboost_system -lboost_filesystem -lboost_program_options -lboost_thread
-lboost_chrono -lboost_unit_test_framework secp256k1/libsecp256k1.la
libbitcoin_wallet.a libbitcoinconsensus.la -ldb_cxx -lssl -lcrypto
-lcrypto    -lanl
libtool: link: g++ -g -O2 -Wall -Wextra -Wformat -Wformat-security
-Wno-unused-parameter -Wstack-protector -fstack-protector-all -fPIE
-fvisibility=hidden -Wl,--exclude-libs -Wl,ALL -pthread -Wl,-z -Wl,relro
-Wl,-z -Wl,now -pie -o test/test_bitcoin
test/test_test_bitcoin-arith_uint256_tests.o
test/test_test_bitcoin-alert_tests.o
test/test_test_bitcoin-allocator_tests.o
test/test_test_bitcoin-base32_tests.o test/test_test_bitcoin-base58_tests.o
test/test_test_bitcoin-base64_tests.o test/test_test_bitcoin-bloom_tests.o
test/test_test_bitcoin-checkblock_tests.o
test/test_test_bitcoin-Checkpoints_tests.o
test/test_test_bitcoin-coins_tests.o
test/test_test_bitcoin-compress_tests.o
test/test_test_bitcoin-crypto_tests.o test/test_test_bitcoin-DoS_tests.o
test/test_test_bitcoin-getarg_tests.o test/test_test_bitcoin-hash_tests.o
test/test_test_bitcoin-key_tests.o test/test_test_bitcoin-main_tests.o
test/test_test_bitcoin-miner_tests.o test/test_test_bitcoin-mruset_tests.o
test/test_test_bitcoin-multisig_tests.o
test/test_test_bitcoin-netbase_tests.o test/test_test_bitcoin-pmt_tests.o
test/test_test_bitcoin-rpc_tests.o test/test_test_bitcoin-sanity_tests.o
test/test_test_bitcoin-script_P2SH_tests.o
test/test_test_bitcoin-script_tests.o
test/test_test_bitcoin-scriptnum_tests.o
test/test_test_bitcoin-serialize_tests.o
test/test_test_bitcoin-sighash_tests.o
test/test_test_bitcoin-sigopcount_tests.o
test/test_test_bitcoin-skiplist_tests.o
test/test_test_bitcoin-test_bitcoin.o
test/test_test_bitcoin-timedata_tests.o
test/test_test_bitcoin-transaction_tests.o
test/test_test_bitcoin-uint256_tests.o
test/test_test_bitcoin-univalue_tests.o test/test_test_bitcoin-util_tests.o
test/test_test_bitcoin-accounting_tests.o
test/test_test_bitcoin-wallet_tests.o
test/test_test_bitcoin-rpc_wallet_tests.o  libbitcoin_server.a
libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a
crypto/libbitcoin_crypto.a univalue/libbitcoin_univalue.a
./leveldb/libleveldb.a ./leveldb/libmemenv.a -L/usr/lib/x86_64-linux-gnu
-lboost_system -lboost_filesystem -lboost_program_options -lboost_thread
-lboost_chrono -lboost_unit_test_framework secp256k1/.libs/libsecp256k1.a
libbitcoin_wallet.a ./.libs/libbitcoinconsensus.a -ldb_cxx -lssl -lcrypto
-lanl -pthread
/usr/bin/ld: error in
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o)(.eh_frame); no
.eh_frame_hdr table will be created.
make[2]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin/src'
make[1]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin/src'
make[1]: Entering directory `/home/fredrik/bitcoin.node/bitcoin'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin'


On Sat, Feb 7, 2015 at 9:57 PM, fredrik.normann@gmail.com <
fredrik.normann@gmail.com> wrote:

> running make V=1 now so fare so good
>
> On Sat, Feb 7, 2015 at 9:35 PM, paveljanik <notifications@github.com>
> wrote:
>
>> Is it repeatable? If so, can you please run make V=1 and paste the
>> command building the main.cpp?
>> It would be nice to save assembler output (gcc -S?) and upload it
>> somewhere.
>> What versions of gcc/as do you have?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitcoin/bitcoin/issues/5767#issuecomment-73381783>.
>>
>
>
>
> --
> Mvh
> -fredrik-normann-
>
> Sent from my Gmail Account
>



-- 
Mvh
-fredrik-normann-

Sent from my Gmail Account

**Comment by eN0Rm** [comment]
bitcoind
Segmentation fault (core dumped)


On Sat, Feb 7, 2015 at 10:09 PM, fredrik.normann@gmail.com <
fredrik.normann@gmail.com> wrote:

> g++ -DHAVE_CONFIG_H -I. -I../src/config  -I. -I./obj -pthread
> -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv
> -I./secp256k1/include  -I./test/ -DBOOST_TEST_DYN_LINK
> -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
>  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -g -O2 -Wall -Wextra -Wformat
> -Wformat-security -Wno-unused-parameter  -Wstack-protector
> -fstack-protector-all -fPIE -fvisibility=hidden -MT
> test/test_test_bitcoin-rpc_wallet_tests.o -MD -MP -MF
> test/.deps/test_test_bitcoin-rpc_wallet_tests.Tpo -c -o
> test/test_test_bitcoin-rpc_wallet_tests.o `test -f
> 'test/rpc_wallet_tests.cpp' || echo './'`test/rpc_wallet_tests.cpp
> mv -f test/.deps/test_test_bitcoin-rpc_wallet_tests.Tpo
> test/.deps/test_test_bitcoin-rpc_wallet_tests.Po
> /bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -Wall -Wextra
> -Wformat -Wformat-security -Wno-unused-parameter  -Wstack-protector
> -fstack-protector-all -fPIE -fvisibility=hidden -Wl,--exclude-libs,ALL
> -pthread   -static -Wl,-z,relro -Wl,-z,now -pie -o test/test_bitcoin
> test/test_test_bitcoin-arith_uint256_tests.o
> test/test_test_bitcoin-alert_tests.o
> test/test_test_bitcoin-allocator_tests.o
> test/test_test_bitcoin-base32_tests.o test/test_test_bitcoin-base58_tests.o
> test/test_test_bitcoin-base64_tests.o test/test_test_bitcoin-bloom_tests.o
> test/test_test_bitcoin-checkblock_tests.o
> test/test_test_bitcoin-Checkpoints_tests.o
> test/test_test_bitcoin-coins_tests.o
> test/test_test_bitcoin-compress_tests.o
> test/test_test_bitcoin-crypto_tests.o test/test_test_bitcoin-DoS_tests.o
> test/test_test_bitcoin-getarg_tests.o test/test_test_bitcoin-hash_tests.o
> test/test_test_bitcoin-key_tests.o test/test_test_bitcoin-main_tests.o
> test/test_test_bitcoin-miner_tests.o test/test_test_bitcoin-mruset_tests.o
> test/test_test_bitcoin-multisig_tests.o
> test/test_test_bitcoin-netbase_tests.o test/test_test_bitcoin-pmt_tests.o
> test/test_test_bitcoin-rpc_tests.o test/test_test_bitcoin-sanity_tests.o
> test/test_test_bitcoin-script_P2SH_tests.o
> test/test_test_bitcoin-script_tests.o
> test/test_test_bitcoin-scriptnum_tests.o
> test/test_test_bitcoin-serialize_tests.o
> test/test_test_bitcoin-sighash_tests.o
> test/test_test_bitcoin-sigopcount_tests.o
> test/test_test_bitcoin-skiplist_tests.o
> test/test_test_bitcoin-test_bitcoin.o
> test/test_test_bitcoin-timedata_tests.o
> test/test_test_bitcoin-transaction_tests.o
> test/test_test_bitcoin-uint256_tests.o
> test/test_test_bitcoin-univalue_tests.o test/test_test_bitcoin-util_tests.o
> test/test_test_bitcoin-accounting_tests.o
> test/test_test_bitcoin-wallet_tests.o
> test/test_test_bitcoin-rpc_wallet_tests.o     libbitcoin_server.a
> libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a
> crypto/libbitcoin_crypto.a univalue/libbitcoin_univalue.a
> ./leveldb/libleveldb.a ./leveldb/libmemenv.a -L/usr/lib/x86_64-linux-gnu
> -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread
> -lboost_chrono -lboost_unit_test_framework secp256k1/libsecp256k1.la
> libbitcoin_wallet.a libbitcoinconsensus.la -ldb_cxx -lssl -lcrypto
> -lcrypto    -lanl
> libtool: link: g++ -g -O2 -Wall -Wextra -Wformat -Wformat-security
> -Wno-unused-parameter -Wstack-protector -fstack-protector-all -fPIE
> -fvisibility=hidden -Wl,--exclude-libs -Wl,ALL -pthread -Wl,-z -Wl,relro
> -Wl,-z -Wl,now -pie -o test/test_bitcoin
> test/test_test_bitcoin-arith_uint256_tests.o
> test/test_test_bitcoin-alert_tests.o
> test/test_test_bitcoin-allocator_tests.o
> test/test_test_bitcoin-base32_tests.o test/test_test_bitcoin-base58_tests.o
> test/test_test_bitcoin-base64_tests.o test/test_test_bitcoin-bloom_tests.o
> test/test_test_bitcoin-checkblock_tests.o
> test/test_test_bitcoin-Checkpoints_tests.o
> test/test_test_bitcoin-coins_tests.o
> test/test_test_bitcoin-compress_tests.o
> test/test_test_bitcoin-crypto_tests.o test/test_test_bitcoin-DoS_tests.o
> test/test_test_bitcoin-getarg_tests.o test/test_test_bitcoin-hash_tests.o
> test/test_test_bitcoin-key_tests.o test/test_test_bitcoin-main_tests.o
> test/test_test_bitcoin-miner_tests.o test/test_test_bitcoin-mruset_tests.o
> test/test_test_bitcoin-multisig_tests.o
> test/test_test_bitcoin-netbase_tests.o test/test_test_bitcoin-pmt_tests.o
> test/test_test_bitcoin-rpc_tests.o test/test_test_bitcoin-sanity_tests.o
> test/test_test_bitcoin-script_P2SH_tests.o
> test/test_test_bitcoin-script_tests.o
> test/test_test_bitcoin-scriptnum_tests.o
> test/test_test_bitcoin-serialize_tests.o
> test/test_test_bitcoin-sighash_tests.o
> test/test_test_bitcoin-sigopcount_tests.o
> test/test_test_bitcoin-skiplist_tests.o
> test/test_test_bitcoin-test_bitcoin.o
> test/test_test_bitcoin-timedata_tests.o
> test/test_test_bitcoin-transaction_tests.o
> test/test_test_bitcoin-uint256_tests.o
> test/test_test_bitcoin-univalue_tests.o test/test_test_bitcoin-util_tests.o
> test/test_test_bitcoin-accounting_tests.o
> test/test_test_bitcoin-wallet_tests.o
> test/test_test_bitcoin-rpc_wallet_tests.o  libbitcoin_server.a
> libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a
> crypto/libbitcoin_crypto.a univalue/libbitcoin_univalue.a
> ./leveldb/libleveldb.a ./leveldb/libmemenv.a -L/usr/lib/x86_64-linux-gnu
> -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread
> -lboost_chrono -lboost_unit_test_framework secp256k1/.libs/libsecp256k1.a
> libbitcoin_wallet.a ./.libs/libbitcoinconsensus.a -ldb_cxx -lssl -lcrypto
> -lanl -pthread
> /usr/bin/ld: error in
> libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o)(.eh_frame); no
> .eh_frame_hdr table will be created.
> make[2]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin/src'
> make[1]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin/src'
> make[1]: Entering directory `/home/fredrik/bitcoin.node/bitcoin'
> make[1]: Nothing to be done for `all-am'.
> make[1]: Leaving directory `/home/fredrik/bitcoin.node/bitcoin'
>
>
> On Sat, Feb 7, 2015 at 9:57 PM, fredrik.normann@gmail.com <
> fredrik.normann@gmail.com> wrote:
>
>> running make V=1 now so fare so good
>>
>> On Sat, Feb 7, 2015 at 9:35 PM, paveljanik <notifications@github.com>
>> wrote:
>>
>>> Is it repeatable? If so, can you please run make V=1 and paste the
>>> command building the main.cpp?
>>> It would be nice to save assembler output (gcc -S?) and upload it
>>> somewhere.
>>> What versions of gcc/as do you have?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/bitcoin/bitcoin/issues/5767#issuecomment-73381783>.
>>>
>>
>>
>>
>> --
>> Mvh
>> -fredrik-normann-
>>
>> Sent from my Gmail Account
>>
>
>
>
> --
> Mvh
> -fredrik-normann-
>
> Sent from my Gmail Account
>



-- 
Mvh
-fredrik-normann-

Sent from my Gmail Account

**Comment by paveljanik** [comment]
I suspect your HW or virtualization environment... Can you try 100-kernel test, ie. compile Linux kernel many times and compare log files? Can you do the same on the host itself?

**Comment by eN0Rm** [comment]
Finally bitcoind compiled and started. Did not do any thing.... So things are pointing to the hardware. 

I'll close this now.

**Comment by theuni** [comment]
Looks like corruption to me as well.
