### ISSUE TITLE
autostart shortcut should honor -testnet

### ISSUE THREAD

**Issue by tykling** [bitcoin/bitcoin#5778]
When checking "Start Bitcoin on system login" the shortcut created doesn't include -testnet. This means that the shortcut created by the bitcoin-core testnet program starts a mainnet client.

**Comment by Diapolo** [comment]
Agreed

**Comment by Diapolo** [comment]
@tykling If you are able to, please help testing the patch :).

**Comment by Diapolo** [comment]
@tykling Ping again :)... mind testing?

**Comment by tykling** [comment]
oh, I accidently left my comment on the first commit, not on the issue :) doh! Here it is:

------------------------------
hello,
I don't have an easy way of building it so I can't really test it but I do have a couple of comments from looking over the code myself.

1) I think you need to look at the name of the shortcut created as well, since they have the same name so the testnet autostart shortcut will overwrite the mainnet one, since they are both just named "bitcoin.lnk" - perhaps call one "bitcoin - testnet.lnk" ?

2) I think the code that makes the autostart stuff for linux around line 690 needs the same fix as the one in your patch.

Thanks!
------------------------------

It looks like you handled 1) but doesn't 2) need fixing as well? 

Thanks!

**Comment by Diapolo** [comment]
@tykling There are 2 commits, one for Windows and the other for Linux :).
