### ISSUE TITLE
Only 64 bits

### ISSUE THREAD

**Issue by terrylai** [bitcoin/bitcoin#5786]
Hello all,

How to configure the gitian so that only 64 bits version is built so as to save time?

BR,
Terry

**Comment by sipa** [comment]
Gitian is only necessary if you want to replicate building the exact binary
releases that others build. Though probably possible, if you're only
building for one platform, that's likely not what you're interested in.

If you want to build for one specific platform, and don't care about exact
byte-for-byte identical results, you can just use the depends/ system. See
the readmes in the depends subdirectory.

**Comment by terrylai** [comment]
Hello all,

I am going to test for code change and 64 bits windows and 64 bits linux binaries are required.

BR,
Terry

**Comment by devrandom** [comment]
@terrylai - I'm curious about what you are trying to achieve.  What do you mean by "test for code changes"?

**Comment by laanwj** [comment]
If your goal is to compare binaries, you don't need to use gitian. You just need to make sure that you use the same toolchain for both builds you are trying to compare, and you need to make sure that no spurious differences creep in.

I use the following script for binary compares here:
```
    git reset --hard
    git clean -f -x -d
    git checkout ${COMMIT}
    git apply ../stripbuildinfo2.patch
    ./autogen.sh
    ./configure --disable-hardening --with-incompatible-bdb --without-gui --without-cli --disable-tests --disable-ccache CPPFLAGS="-DNDEBUG" CFLAGS="${OPTFLAGS}" CXXFLAGS="${OPTFLAGS}" LDFLAGS="${OPTFLAGS}"
    make -j3 src/bitcoind 
    cp src/bitcoind ${TGTDIR}/bitcoind.${COMMIT}
    strip -o ${TGTDIR}/bitcoind.${COMMIT}.stripped -R.note.gnu.build-id ${TGTDIR}/bitcoind.${COMMIT}
```

stripbuildinfo2.patch is a simple patch that removes commit-specific information as well as line number information from ending up in the executable

See here for my complete setup, https://gist.github.com/laanwj/7f21a36dab0dbdfb3c49

It's quite hacky but you can use it as a starting point. I'm going to close this issue, as it is more like a help request and this is not meant as a help forum.
