### ISSUE TITLE
Downgrade ERROR to something less less terrifying?

### ISSUE THREAD

**Issue by brsq** [bitcoin/bitcoin#5794]
A pretty frequent source of confusion is the "errors" that appear in debug.log that really shouldn't be, is there any reason that these shouldn't be changed to warnings or just informational prints? "Error" just comes on a bit too strong for my liking and doesn't really reflect what the log print is talking about (rejected transaction, not someone hitting the self destruct button).

Propose:

    ERROR: AcceptToMemoryPool : non-final

Becomes:

    INFO: AcceptToMemoryPool : non-final

**Comment by paveljanik** [comment]
I haven't heard any discussion about such confusion myself. But I agree that ERROR is too strong here because this is part of `AcceptToMemoryPool` standard behaviour and doesn't need user's attention.
One or two days `debug.log` contains the following here:
```
ERROR: AcceptToMemoryPool: inputs already spent
ERROR: AcceptToMemoryPool: nonstandard transaction: dust
ERROR: AcceptToMemoryPool: free transaction rejected by rate limiter
```
None of these messages is an error, but standard information message about tx not being accepted to mempool. Looking at other `AcceptToMemoryPool` log messages in `debug.log`, I'd drop "category/level" prefix (ERROR: here) completely and change the message to contain "not accepted".

**Comment by laanwj** [comment]
Agreed, would be better if these are not ERROR.  I do remember discussions about this before.

**Comment by sipa** [comment]
I think we should get rid of all validation failure messages, and only
report thing when the final result of validation (in accepttomempool or
processblock) is available, and report there based on debug settings.

**Comment by redpola** [comment]
+1 from me. Just set up my first node (headless, no wallet) to contribute to the bitcoin movement and saw this in my logs. As someone said, this kind of error is terrifying when I'm investing masses of bandwidth downloading the blockchain and I'm too naive/inexperienced to know whether my install is screwing itself and/or the bitcoin network.

**Comment by laanwj** [comment]
@sipa Agreed. Going by the number of complaints about `ERROR: AcceptToMemoryPool: nonstandard transaction: dust` floods, I think we should stop logging messages for incoming transactions by default, whether accepted or rejected. Then add a debug flag for logging these.

**Comment by skarra** [comment]
Even for optional logging, wouldn't it be more useful to also log some additional information? For a developer trying to get into Bitcoin these messages make no sense (either as an error or as Info). What does having 2000 of these INFO messages tell you veterans?

**Comment by dcousens** [comment]
+1 for replacing with `INFO`,  I think the removal should be in a separate pull request.
