### ISSUE TITLE
getbalance gives weird results

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#5802]
```
bitcoin-cli getbalance "*" 0
0.12820000
bitcoin-cli getbalance "" 0
0.12830000
```

The * gives less results than "". I guess that's a bug.

Also weird:
```
bitcoin-cli getbalance
0.12820000
bitcoin-cli getbalance '*' 1
0.12810000
```

When you would expect those two commands are identical. (probably due to unconfirmed change)

**Comment by dexX7** [comment]
Hey @RHavar,

the difference between `"*"` and `""` is that the first one sums all unspent outputs, while the second one considers only those with the account label `""`. Even though `""` appears to be the default label, you probably have at least one with a different label.

`getbalance` and `getbalance "*" 0` should return the same result.
`getbalance "*"` should return the sum of unspent outputs, but with at least one confirmation.

**Comment by RHavar** [comment]
@dexX7 I don't think that explains the behavior at all. If you look at my original post, the balance of '*' is **LESS** than the balance of "". If I had two accounts, it would be more. Running `bitcoind listaccounts` also shows I only have a single account "". Right now everything looks sane, but only because I have no unconfirmed funds/change.

**Comment by dexX7** [comment]
@RHavar: account balances can be negative. Would that explain this behavior?

You'd likely have to use `listaccounts 0` to include unconfirmed ones.

That being said, this call is tagged as deprecated, which might not explain this behavior, but signal to avoid the account system, if possible.

**Comment by sipa** [comment]
Accounts can go negative, if you send more from them than to them.

Accounts have nothing to do with actual coins in the bitcoin transaction
sense. They're just bean counters.

Use listaccounts (iirc) to see all of them.

**Comment by RHavar** [comment]
To be clear, I'm *only* using the default account. The problem here is that the rpc call is returning wrong information, and appears to be how it treats unconfirmed transactions/change.

**Comment by laanwj** [comment]
We really, really need to get rid of this broken, inconsistent account system. It must be doing more harm than good overall.
