### ISSUE TITLE
Please put back the RPC function 'getwork'

### ISSUE THREAD

**Issue by ajcj151** [bitcoin/bitcoin#5808]
Much good miners do not use the gbt call, only 'getwork', please put it back.

**Comment by sipa** [comment]
Examples of such miners?

**Comment by ajcj151** [comment]
Poclbm
DiabloMiner
PhoenixMiner 2

**Comment by sipa** [comment]
All of those are GPU miners, as far as I know, which are totally irrelevant now.

**Comment by ajcj151** [comment]
Well, much people mines bitcoin only for fun and study, why can't put 'getwork' back? Because bitcoin core will be 1kb bigger?

**Comment by sipa** [comment]
No, because of review and maintenance time to keep old code working.

For fun and study you can use regtest mode, which has built-in mining.

**Comment by luke-jr** [comment]
@ajcj151 BFGMiner also supports CPU/GPU  mining if you really need that. If you prefer the older/unmaintained GPU miners, you can also run BFGMiner in a getwork-proxy mode to serve as a "middle man" between Bitcoin Core and getwork miners.
