### ISSUE TITLE
Gitian building doc out of date

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#5814]
The gitian building doc states that one should download this, or any minor version update. This link no longer works, and I can only find 7.8 builds on that website.

http://cdimage.debian.org/debian-cd/7.7.0/amd64/iso-cd/debian-7.7.0-amd64-netinst.iso

in https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md

**Comment by theuni** [comment]
This is pending in the trivial tree: https://github.com/theuni/bitcoin/commit/124e5c5a7feca1a83535651493a165bfd47df154 . 7.8 is fine.

**Comment by instagibbs** [comment]
thanks
