### ISSUE TITLE
C++ standard

### ISSUE THREAD

**Issue by 21E14** [bitcoin/bitcoin#5816]
The C++ standard used remains undocumented in developer-notes.md.

**Comment by sipa** [comment]
Patches welcome.

**Comment by 21E14** [comment]
;-) So far, the circumstantial evidence points to gnu99 for secp256k1, C++11/C++0x for leveldb and gnu++98/C++98 for bitcoind yet to be switched to C++11.

**Comment by laanwj** [comment]
Feel free to do this, I don't  see this as an issue.

**Comment by luke-jr** [comment]
AIUI, libsecp256k1 is supposed to be C89, and Bitcoin Core requires at least C++98. Note that C++98 and C++11 are ABI incompatible, so you must use the same one the rest of your OS is compiled with.

**Comment by 21E14** [comment]
@laanwj That's a curious choice.

@luke-jr Take a look at /src/secp256k1/configure.ac:25

AC_PROG_CC_C99
if test x"$ac_cv_prog_cc_c99" = x"no"; then
  AC_MSG_ERROR([c99 compiler support required])
fi

**Comment by sipa** [comment]
Libsecp256k1 upstream used to be c99, but was converted to strict c89
recently. The copy inside in bitcoin source tree is still c99.

**Comment by laanwj** [comment]
@21E14 See it from an organizational perspective: there is an infinity of possible improvements possible to the documentation, if there were to be issues for all of them we wouldn't see the forest for the trees.
