### ISSUE TITLE
No error message for wrong command and endless loop

### ISSUE THREAD

**Issue by benjyz** [bitcoin/bitcoin#5821]
If bitcoind is misconfigured this line produces an endless loop without information to the user what the problem is: https://github.com/bitcoin/bitcoin/blob/master/src/bitcoin-cli.cpp#L213

An appropriate behaviour would be throwing an error: request not allowed or not known something like that.

**Comment by ajweiss** [comment]
The purpose of the rpcwait argument is to ask the command line client to wait until it can connect to a running bitcoind so that way test scripts and whatnot don't have to worry about how long it takes a fresh bitcoind to warm up.

What is the exact misconfiguration you are referring to?

**Comment by benjyz** [comment]
From the user's perspective it's a very bad, no let's call it horrible or atrocious, way of dealing with inputs. What I'm supposed to do with this output information? That's what output is there for: to inform a user about the internal state. With no output, I have no way to know what is going on, no way of fixing it. It's typical of the CLI - it is not designed for users, but for developers.

**Comment by laanwj** [comment]
Can you specify the exact command line you're using? I've tried various combinations of rpcwait and invalid commands, and cannot reproduce an infinite loop.

    src/bitcoin-cli -testnet -rpcwait test
    error: {"code":-32601,"message":"Method not found"}

**Comment by benjyz** [comment]
On Ubuntu 14, tag 0.10.0, if the conf does not contain server=1
```
bitcoin-cli getinfo
```

In this case I'd expect an error like "error: server not set." or something like it.

**Comment by paveljanik** [comment]
Do you run `bitcoind` or `bitcoin-qt` (which requires server=1 to enable RPC at all...)?

**Comment by benjyz** [comment]
Running bitcoind.

If I try to reproduce I get an appropriate error message. So I can't reproduce. Strange - I thought this is default behaviour, because it happened many times.
```
bitcoin-cli getinfo
error: {"code":-28,"message":"Verifying blocks..."}
```

and if server is down, also a correct error message:
```
./bitcoin-cli getinfo
error: couldn't connect to server
```

**Comment by paveljanik** [comment]
I can reproduce endless loop with
```
bitcoind -server=0 &
bitcoin-cli -rpcwait test
```
but... Ugh. Is it the case you are reporting?

**Comment by benjyz** [comment]
That might be the bug, but without the -rpcwait flag. But you misunderstand some things here: server=0 is not set in versions before 0.10. So it breaks compatibility. Also an error like this, is the responsibility of the person who writes the software, not the user. Blaming users for bad inputs, is something you can allow yourself to do in your personal projects, but not here.

**Comment by laanwj** [comment]
Right: The point of `-rpcwait` is to wait indefinitely until the server comes up. If you didn't start the server then it will wait and wait and wait. It cannot print errors because that will interfere with script usage. Scripts just expect the output, not intermediate status messages.

*Without* the `-rpcwait` flag it should never end up in an infinite loop, though. Anyone else that reproduce this without rpcwait?
