### ISSUE TITLE
[core dump] When running the command "loadblock"

### ISSUE THREAD

**Issue by lekanovic** [bitcoin/bitcoin#5822]
When I try to import an boostrap.dat file for an faster blockchain update I get an core dump in the bitcoind. However when I restart the command "bitcoind -server" after the core dump it works just fine and it starts at the same block where the crash occured.

Background

* Using bitcoind v0.9.4 that is locally compiled
   git clone git@github.com:bitcoin/bitcoin.git
   cd bitcoin
   git checkout v0.9.4
   ./autogen
   ./configure -with-incompatible-bdb 
   make

* Machine used: 
   - Ubuntu 12.04
   - Architecture: x86_64

How to reproduce the core dump

1. Download bootstrap.dat from http://sourceforge.net/projects/bitcoin/files/Bitcoin/blockchain/bootstrap.dat.torrent/download

2. Run the command:
 ./bitcoind -loadblock=~/path_to_blocklist/bootstrap.dat

3. Wait for a long time and the result is pasted below

core dump
./bitcoind -loadblock=~/Downloads/bootstrap.dat
*** glibc detected *** ./bitcoind: free(): invalid pointer: 0x00007f28ba091532 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7e846)[0x7f2931d42846]
./bitcoind(+0x886e0)[0x7f2933fcb6e0]
./bitcoind(+0xc22cc)[0x7f29340052cc]
./bitcoind(+0x1758ad)[0x7f29340b88ad]
./bitcoind(+0x17480e)[0x7f29340b780e]
./bitcoind(+0xa783a)[0x7f2933fea83a]
./bitcoind(+0xa8b18)[0x7f2933febb18]
./bitcoind(+0xa96b7)[0x7f2933fec6b7]
./bitcoind(+0xaacfa)[0x7f2933fedcfa]
./bitcoind(+0xb130d)[0x7f2933ff430d]
./bitcoind(+0xb447a)[0x7f2933ff747a]
./bitcoind(+0x11d825)[0x7f2934060825]
./bitcoind(+0x10a08f)[0x7f293404d08f]
./bitcoind(_Z11TraceThreadIPFvvEEvPKcT_+0x4a)[0x7f2934057a6a]
/usr/lib/libboost_thread.so.1.46.1(thread_proxy+0x69)[0x7f293348ace9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a)[0x7f293208ae9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f2931db82ed]

======= Memory map: ========
7f2880000000-7f2887ffe000 rw-p 00000000 00:00 0 
7f2887ffe000-7f2888000000 ---p 00000000 00:00 0 
7f2888000000-7f288c000000 rw-p 00000000 00:00 0 
7f2890000000-7f2894000000 rw-p 00000000 00:00 0 
7f2898000000-7f289c000000 rw-p 00000000 00:00 0 
7f28a0000000-7f28a4000000 rw-p 00000000 00:00 0 
7f28a8000000-7f28ac000000 rw-p 00000000 00:00 0 
7f28b0000000-7f28b3ffd000 rw-p 00000000 00:00 0 
7f28b3ffd000-7f28b4000000 ---p 00000000 00:00 0 
7f28b8000000-7f28bbf8b000 rw-p 00000000 00:00 0 
7f28bbf8b000-7f28bc000000 ---p 00000000 00:00 0 
7f28be36e000-7f28be581000 r--s 00000000 08:21 3541770                    /home/user/.bitcoin/blocks/index/023417.ldb
7f28be581000-7f28be794000 r--s 00000000 08:21 3541225                    /home/user/.bitcoin/blocks/index/023412.ldb
7f28be794000-7f28be9a7000 r--s 00000000 08:21 3541061                    /home/user/.bitcoin/blocks/index/023411.ldb
7f28bedb3000-7f28befc6000 r--s 00000000 08:21 3540606                    /home/user/.bitcoin/blocks/index/023416.ldb
7f28befc6000-7f28bf1d9000 r--s 00000000 08:21 3540386                    /home/user/.bitcoin/blocks/index/023410.ldb
7f28bf5e2000-7f28bf7f1000 r--s 00000000 08:21 3541019                    /home/user/.bitcoin/chainstate/119228.ldb
7f28bfa06000-7f28bfc3e000 r--s 00000000 08:21 3539925                    /home/user/.bitcoin/blocks/index/023427.ldb
7f28bfe50000-7f28c0060000 r--s 00000000 08:21 3541036                    /home/user/.bitcoin/chainstate/119155.ldb
7f28c0060000-7f28c026c000 r--s 00000000 08:21 3541396                    /home/user/.bitcoin/chainstate/118789.ldb
7f28c026c000-7f28c047f000 r--s 00000000 08:21 3541901                    /home/user/.bitcoin/blocks/index/023424.ldb
7f28c0a7c000-7f28c0cb3000 r--s 00000000 08:21 3541559                    /home/user/.bitcoin/blocks/index/023429.ldb
7f28c0cb3000-7f28c0ec6000 r--s 00000000 08:21 3540295                    /home/user/.bitcoin/blocks/index/023338.ldb
7f28c10cc000-7f28c12db000 r--s 00000000 08:21 3540678                    /home/user/.bitcoin/blocks/index/008326.ldb
7f28c12db000-7f28c14ee000 r--s 00000000 08:21 3540191                    /home/user/.bitcoin/blocks/index/023334.ldb
7f28c190b000-7f28c1b1a000 r--s 00000000 08:21 3541146                    /home/user/.bitcoin/chainstate/118975.ldb
7f28c1b1a000-7f28c1d25000 r--s 00000000 08:21 3540589                    /home/user/.bitcoin/chainstate/119318.ldb
7f28c1d25000-7f28c1f38000 r--s 00000000 08:21 3540994                    /home/user/.bitcoin/blocks/index/023402.ldb
7f28c1f38000-7f28c2142000 r--s 00000000 08:21 3540254                    /home/user/.bitcoin/chainstate/119242.ldb
7f28c2142000-7f28c234d000 r--s 00000000 08:21 3541180                    /home/user/.bitcoin/chainstate/119184.ldb
7f28c2558000-7f28c2764000 r--s 00000000 08:21 3541205                    /home/user/.bitcoin/chainstate/118977.ldb
7f28c2764000-7f28c296e000 r--s 00000000 08:21 3541708                    /home/user/.bitcoin/chainstate/119135.ldb
7f28c296e000-7f28c2b81000 r--s 00000000 08:21 3541952                    /home/user/.bitcoin/blocks/index/023419.ldb
7f28c2b81000-7f28c2d94000 r--s 00000000 08:21 3540449                    /home/user/.bitcoin/blocks/index/023401.ldb
7f28c2f78000-7f28c31ae000 r--s 00000000 08:21 3540711                    /home/user/.bitcoin/blocks/index/023431.ldb
7f28c31af000-7f28c33bc000 r--s 00000000 08:21 3541664                    /home/user/.bitcoin/chainstate/119110.ldb
7f28c33bc000-7f28c35c6000 r--s 00000000 08:21 3540941                    /home/user/.bitcoin/chainstate/119227.ldb
7f28c35c6000-7f28c37d0000 r--s 00000000 08:21 3541769                    /home/user/.bitcoin/chainstate/119207.ldb
7f28c37d0000-7f28c39da000 r--s 00000000 08:21 3540948                    /home/user/.bitcoin/chainstate/119194.ldb
7f28c39da000-7f28c3bed000 r--s 00000000 08:21 3541342                    /home/user/.bitcoin/blocks/index/023406.ldb
7f28c3df5000-7f28c4000000 r--s 00000000 08:21 3540717                    /home/user/.bitcoin/chainstate/119171.ldb
7f28c4000000-7f28c4021000 rw-p 00000000 00:00 0 
7f28c4021000-7f28c8000000 ---p 00000000 00:00 0 
7f28c8000000-7f28cbfc7000 rw-p 00000000 00:00 0 
7f28cbfc7000-7f28cc000000 ---p 00000000 00:00 0 
7f28cc000000-7f28cc021000 rw-p 00000000 00:00 0 
7f28cc021000-7f28d0000000 ---p 00000000 00:00 0 
7f28d0000000-7f28d0021000 rw-p 00000000 00:00 0 
7f28d0021000-7f28d4000000 ---p 00000000 00:00 0 
7f28d41f6000-7f28d4400000 r--s 00000000 08:21 3540050                    /home/user/.bitcoin/chainstate/119239.ldb
7f28d4400000-7f28d460b000 r--s 00000000 08:21 3540921                    /home/user/.bitcoin/chainstate/119128.ldb
7f28d460b000-7f28d4815000 r--s 00000000 08:21 3540629                    /home/user/.bitcoin/chainstate/119321.ldb
7f28d4816000-7f28d4a22000 r--s 00000000 08:21 3541085                    /home/user/.bitcoin/chainstate/119327.ldb
7f28d4a22000-7f28d4c2c000 r--s 00000000 08:21 3541270                    /home/user/.bitcoin/chainstate/119144.ldb
7f28d4e37000-7f28d5042000 r--s 00000000 08:21 3540695                    /home/user/.bitcoin/chainstate/118988.ldb
7f28d5042000-7f28d5248000 r--s 00000000 08:21 3542103                    /home/user/.bitcoin/chainstate/119044.ldb
7f28d5249000-7f28d5452000 r--s 00000000 08:21 3540892                    /home/user/.bitcoin/chainstate/119326.ldb
7f28d5452000-7f28d565c000 r--s 00000000 08:21 3541655                    /home/user/.bitcoin/chainstate/119133.ldb
7f28d565c000-7f28d586f000 r--s 00000000 08:21 3540222                    /home/user/.bitcoin/blocks/index/023405.ldb
7f28d586f000-7f28d5a47000 r--s 00000000 08:21 3540259                    /home/user/.bitcoin/blocks/index/023373.ldb
7f28d5c17000-7f28d5de4000 r--s 00000000 08:21 3540175                    /home/user/.bitcoin/blocks/index/023371.ldb
7f28d5f96000-7f28d61a0000 r--s 00000000 08:21 3541204                    /home/user/.bitcoin/chainstate/118976.ldb
7f28d61a0000-7f28d63ab000 r--s 00000000 08:21 3541312                    /home/user/.bitcoin/chainstate/119132.ldb
7f28d63ac000-7f28d65b6000 r--s 00000000 08:21 3541116                    /home/user/.bitcoin/chainstate/118974.ldb
7f28d65b6000-7f28d67c0000 r--s 00000000 08:21 3541364                    /home/user/.bitcoin/chainstate/118760.ldb
7f28d67c0000-7f28d69ca000 r--s 00000000 08:21 3541301                    /home/user/.bitcoin/chainstate/119122.ldb
7f28d69ca000-7f28d6bd3000 r--s 00000000 08:21 3541295                    /home/user/.bitcoin/chainstate/119230.ldb
7f28d6bd3000-7f28d6de6000 r--s 00000000 08:21 3541773                    /home/user/.bitcoin/blocks/index/023422.ldb
7f28d6de6000-7f28d6ff9000 r--s 00000000 08:21 3540594                    /home/user/.bitcoin/blocks/index/023415.ldb
7f28d6ff9000-7f28d7204000 r--s 00000000 08:21 3542129                    /home/user/.bitcoin/chainstate/119071.ldb
7f28d7204000-7f28d73bc000 r--s 00000000 08:21 3541491                    /home/user/.bitcoin/blocks/index/023318.ldb
7f28d7418000-7f28d762b000 r--s 00000000 08:21 3540545                    /home/user/.bitcoin/blocks/index/023421.ldb
7f28d763e000-7f28d7848000 r--s 00000000 08:21 3542020                    /home/user/.bitcoin/chainstate/119264.ldb
7f28d7848000-7f28d7a51000 r--s 00000000 08:21 3542077                    /home/user/.bitcoin/chainstate/119179.ldb
7f28d7a51000-7f28d7c5b000 r--s 00000000 08:21 3541123                    /home/user/.bitcoin/chainstate/119216.ldb
7f28d7c5b000-7f28d7df6000 r--s 00000000 08:21 3541510                    /home/user/.bitcoin/blocks/index/023381.ldb
7f28d7df7000-7f28d8000000 r--s 00000000 08:21 3541360                    /home/user/.bitcoin/chainstate/119232.ldb
7f28d8000000-7f28d8021000 rw-p 00000000 00:00 0 
7f28d8021000-7f28dc000000 ---p 00000000 00:00 0 
7f28dc000000-7f28dc021000 rw-p 00000000 00:00 0 
7f28dc021000-7f28e0000000 ---p 00000000 00:00 0 
7f28e0000000-7f28e0021000 rw-p 00000000 00:00 0 
7f28e0021000-7f28e4000000 ---p 00000000 00:00 0 
7f28e4000000-7f28e8000000 rw-p 00000000 00:00 0 
7f28e8000000-7f28e81f1000 rw-p 00000000 00:00 0 
7f28e81f1000-7f28ec000000 ---p 00000000 00:00 0 
7f28ec000000-7f28ecbd2000 rw-p 00000000 00:00 0 
7f28ecbd2000-7f28f0000000 ---p 00000000 00:00 0 
7f28f0000000-7f28f0021000 rw-p 00000000 00:00 0 
7f28f0021000-7f28f4000000 ---p 00000000 00:00 0 
7f28f4000000-7f28f4021000 rw-p 00000000 00:00 0 
7f28f4021000-7f28f8000000 ---p 00000000 00:00 0 
7f28f802b000-7f28f8235000 r--s 00000000 08:21 3541813                    /home/user/.bitcoin/chainstate/119209.ldb
7f28f8235000-7f28f8437000 r--s 00000000 08:21 3541939                    /home/user/.bitcoin/blocks/index/023367.ldb
7f28f8466000-7f28f85ef000 r--s 00000000 08:21 3540328                    /home/user/.bitcoin/blocks/index/023311.ldb
7f28f85ef000-7f28f87f9000 r--s 00000000 08:21 3540904                    /home/user/.bitcoin/chainstate/119182.ldb
7f28f87f9000-7f28f87fa000 ---p 00000000 00:00 0 
7f28f87fa000-7f28f8ffa000 rw-p 00000000 00:00 0                          [stack:18524]
7f28f8ffa000-7f28f8ffb000 ---p 00000000 00:00 0 
7f28f8ffb000-7f28f97fb000 rw-p 00000000 00:00 0                          [stack:18523]
7f28f97fb000-7f28f97fc000 ---p 00000000 00:00 0 
7f28f97fc000-7f28f9ffc000 rw-p 00000000 00:00 0                          [stack:18522]
7f28f9ffc000-7f28f9ffd000 ---p 00000000 00:00 0 
7f28f9ffd000-7f28fa7fd000 rw-p 00000000 00:00 0                          [stack:18521]
7f28fa7fd000-7f28fa7fe000 ---p 00000000 00:00 0 
7f28fa7fe000-7f28faffe000 rw-p 00000000 00:00 0                          [stack:18520]
7f28faffe000-7f28fafff000 ---p 00000000 00:00 0 
7f28fafff000-7f28fb7ff000 rw-p 00000000 00:00 0                          [stack:18519]
7f28fb7ff000-7f28fb800000 ---p 00000000 00:00 0 
7f28fb800000-7f28fc000000 rw-p 00000000 00:00 0                          [stack:18518]
7f28fc000000-7f28fc021000 rw-p 00000000 00:00 0 
7f28fc021000-7f2900000000 ---p 00000000 00:00 0 
7f29000a2000-7f29002b5000 r--s 00000000 08:21 3541930                    /home/user/.bitcoin/blocks/index/023407.ldb
7f29004a6000-7f29006b0000 r--s 00000000 08:21 3540276                    /home/user/.bitcoin/chainstate/119272.ldb
7f29006b0000-7f29006b1000 ---p 00000000 00:00 0 
7f29006b1000-7f2900eb1000 rw-p 00000000 00:00 0                          [stack:18517]
7f2900eb1000-7f2900eb2000 ---p 00000000 00:00 0 
7f2900eb2000-7f29016b2000 rw-p 00000000 00:00 0                          [stack:18516]
7f29016b2000-7f29016b3000 ---p 00000000 00:00 0 
7f29016b3000-7f2901eb3000 rw-p 00000000 00:00 0                          [stack:18515]
7f2901eb3000-7f2901eb4000 ---p 00000000 00:00 0 
7f2901eb4000-7f29026b4000 rw-p 00000000 00:00 0 
7f29026b5000-7f2902792000 r--s 00000000 08:21 3541933                    /home/user/.bitcoin/blocks/index/023396.ldb
7f2902793000-7f2902992000 r--s 00000000 08:21 3542100                    /home/user/.bitcoin/chainstate/119041.ldb
7f2902992000-7f2902b9e000 r--s 00000000 08:21 3541287                    /home/user/.bitcoin/chainstate/119197.ldb
7f2902b9e000-7f2902da9000 r--s 00000000 08:21 3541924                    /home/user/.bitcoin/chainstate/119248.ldb
7f2902daa000-7f2902fb4000 r--s 00000000 08:21 3541062                    /home/user/.bitcoin/chainstate/119090.ldb
7f2902fb4000-7f29031be000 r--s 00000000 08:21 3541466                    /home/user/.bitcoin/chainstate/119168.ldb
7f29031be000-7f29033c8000 r--s 00000000 08:21 3541026                    /home/user/.bitcoin/chainstate/119154.ldb
7f29033c8000-7f29035cf000 r--s 00000000 08:21 3541992                    /home/user/.bitcoin/chainstate/119018.ldb
7f29035d0000-7f29037d9000 r--s 00000000 08:21 3542066                    /home/user/.bitcoin/chainstate/119029.ldb
7f29037dc000-7f29039e5000 r--s 00000000 08:21 3540582                    /home/user/.bitcoin/chainstate/118986.ldb
7f2903df6000-7f2904000000 r--s 00000000 08:21 3540842                    /home/user/.bitcoin/chainstate/119325.ldb
7f2904000000-7f2904021000 rw-p 00000000 00:00 0 
7f2904021000-7f2908000000 ---p 00000000 00:00 0 
7f2908000000-7f29082e6000 rw-p 00000000 00:00 0 
7f29082e6000-7f290c000000 ---p 00000000 00:00 0 
7f290c000000-7f290c021000 rw-p 00000000 00:00 0 
7f290c021000-7f2910000000 ---p 00000000 00:00 0 
7f2910000000-7f2910021000 rw-p 00000000 00:00 0 
7f2910021000-7f2914000000 ---p 00000000 00:00 0 
7f2914000000-7f2914021000 rw-p 00000000 00:00 0 
7f2914021000-7f2918000000 ---p 00000000 00:00 0 
7f2918000000-7f2918021000 rw-p 00000000 00:00 0 
7f2918021000-7f291c000000 ---p 00000000 00:00 0 
7f291c000000-7f291c021000 rw-p 00000000 00:00 0 
7f291c021000-7f2920000000 ---p 00000000 00:00 0 
7f2920081000-7f292028b000 r--s 00000000 08:21 3540705                    /home/user/.bitcoin/chainstate/118973.ldb
7f292028b000-7f2920494000 r--s 00000000 08:21 3541950                    /home/user/.bitcoin/chainstate/119256.ldb
7f2920494000-7f2920495000 ---p 00000000 00:00 0 
7f2920495000-7f2920c95000 rw-p 00000000 00:00 0 
7f2920c95000-7f2920c96000 ---p 00000000 00:00 0 
7f2920c96000-7f2921496000 rw-p 00000000 00:00 0 
7f292150d000-7f292162c000 r--s 00000000 08:21 3541921                    /home/user/.bitcoin/blocks/index/023395.ldb
7f292162c000-7f29217a6000 r--s 00000000 08:21 3541502                    /home/user/.bitcoin/blocks/index/023384.ldb
7f29217a6000-7f29219b0000 r--s 00000000 08:21 3540068                    /home/user/.bitcoin/chainstate/119117.ldb
7f29219b0000-7f2921b5f000 r--s 00000000 08:21 3541460                    /home/user/.bitcoin/blocks/index/023379.ldb
7f2921b60000-7f2921d69000 r--s 00000000 08:21 3540527                    /home/user/.bitcoin/chainstate/119096.ldb
7f2921d69000-7f2921d6a000 ---p 00000000 00:00 0 
7f2921d6a000-7f292256a000 rw-p 00000000 00:00 0                          [stack:18508]
7f2922586000-7f2922790000 r--s 00000000 08:21 3542052                    /home/user/.bitcoin/chainstate/119295.ldb
7f2922790000-7f292299a000 r--s 00000000 08:21 3542019                    /home/user/.bitcoin/chainstate/119263.ldb
7f292299b000-7f2922ba5000 r--s 00000000 08:21 3541037                    /home/user/.bitcoin/chainstate/119196.ldb
7f2922ba5000-7f2922cda000 r--s 00000000 08:21 3541561                    /home/user/.bitcoin/blocks/index/023390.ldb
7f2922cda000-7f2922ee4000 r--s 00000000 08:21 3542128                    /home/user/.bitcoin/chainstate/119070.ldb
7f2922ee5000-7f29230ee000 r--s 00000000 08:21 3540836                    /home/user/.bitcoin/chainstate/119324.ldb
7f29230ee000-7f29232a5000 r--s 00000000 08:21 3540096                    /home/user/.bitcoin/blocks/index/023369.ldb
7f2923328000-7f29234b0000 r--s 00000000 08:21 3541261                    /home/user/.bitcoin/blocks/index/023378.ldb
7f2923621000-7f292382b000 r--s 00000000 08:21 3541183                    /home/user/.bitcoin/chainstate/119328.ldb
7f292382b000-7f2923a35000 r--s 00000000 08:21 3540388                    /home/user/.bitcoin/chainstate/119274.ldb
7f2923a35000-7f2923c3e000 r--s 00000000 08:21 3542066                    /home/user/.bitcoin/chainstate/119029.ldbAborted (core dumped)

**Comment by ajweiss** [comment]
Would you mind doing the following?

1) Ensure that the data directory being accessed by this bitcoind has no wallet with real funds.  If it does, STOP and do not continue with step 2.
2) Run the following command, with paths to the bincoin binary and core file, and paste the results either here or in a pastebin?

gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" BITCOINBINARY COREFILE 

Thanks!

**Comment by lekanovic** [comment]
Hi Adam,

Thanks for your quick reply. It looks like the that this core dump was
related to an HW problem on my desktop. I have changed the motherboard on
my desktop and I wil try to reproduce it the core dump again. If I cannot
reproduce this issue with my new motherboard then we can consider this one
solved.

Regards,
Radovan






Radovan Lekanovic

Senior Software Engineer
m:+17602747148 | e:lekanovic@gmail.com
