### ISSUE TITLE
Static Initialization Risk Mitigation

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#5827]
Note to ourselves: Migrate from static/implicit (à la CInit, few more... instance(s)_of_) to explicit initialization/shutdown sequences. Provide a rationale where this is not desirable.

**Comment by laanwj** [comment]
Luckily the foremost of these is the OpenSSL initialization, which we will eventually rid of anyway.

**Comment by MarcoFalke** [comment]
OpenSSL was removed. Is this still an issue?
