### ISSUE TITLE
Bitcoin-QT Peer sort by Address/Hostname

### ISSUE THREAD

**Issue by PRabahy** [bitcoin/bitcoin#5867]
Right now the if I click the Address/Hostname column, it sorts it in lexographic order instead of numeric order.

For example if I have 3 connections: 1.1.1.1, 2.2.2.2,100.100.100.100, right now it will sort them
1.1.1.1
100.100.100.100
2.2.2.2

I would like to see them sorted
1.1.1.1
2.2.2.2
100.100.100.100

**Comment by jonasschnelli** [comment]
I'm not sure if we should say this is a Bug.

Look at this screen:
![bildschirmfoto 2015-03-11 um 16 40 14](https://cloud.githubusercontent.com/assets/178464/6600025/529b174e-c80d-11e4-87f5-121b9710c07c.png)

I personally like this kind of sorting.
If peer 24.113.5.237 would be on top that would irritate me.
But i don't know how other think about this.

However. This is certainly low prio.

**Comment by laanwj** [comment]
You could achieve lexicographic order by sorting by binary address instead of text. But as said, this is just a matter of preference. It's certainly not a bug. If you implement this we could compare the behavior in practice, but without code it doesn't make sense to have an issue open about this.
