### ISSUE TITLE
Building bitcoin in OS X

### ISSUE THREAD

**Issue by mikach** [bitcoin/bitcoin#5869]
Hello!

I'm trying to build bitcoin in OS X Yosemite, but after `make` I got errors like that: 
```
./qt/paymentrequest.pb.h:837:74: error: no member named 'kEmptyString' in namespace 'google::protobuf::internal'; did you mean 'GetEmptyString'?
    script_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
                                                                         GetEmptyString
```

Same thing for `make check`.

Any suggestions how to solve it?

**Comment by fanquake** [comment]
@mikach Have you recently updated protobuf? Try running "make clean", and then running make again. That will regenerate your protobuf files, and more than likely fix this issue.

**Comment by mikach** [comment]
@fanquake After `make clean && make` still have the same issue...

**Comment by fanquake** [comment]
Can you post more information. 
Which version of protobuf, and how is it installed (brew/macports)? Can you pastebin a full build log, including your ./configure and make output.

**Comment by mikach** [comment]
All tools installed with Homebrew.
Here is `make` output: https://gist.github.com/mikach/a1951216c981c73a347d
Protobuf version `2.6.1`

**Comment by jonasschnelli** [comment]
@mikach: could you also post a ./configure log?

**Comment by mikach** [comment]
./configure log https://gist.github.com/mikach/dfd6efd9998e116b4b01

**Comment by fanquake** [comment]
The error is shown in the build log..

./qt/paymentrequest.pb.h:17:2: error: This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc. 

You need to either remove the paymentrequest.pb.h file, so it will be regenerated, or regenerate it manually with protoc

**Comment by mikach** [comment]
@fanquake After removing `./qt/paymentrequest.pb.h` and `make` I got this problem again. How can I regenerate it manually?

**Comment by jonasschnelli** [comment]
@mikach: Check line 251 in your configure log. It looks like protoc has be taken from a different path than you potential homebrew installed protobuf.
Try removing the one detected by configure (line 251) and install protobuf through homebrew. 

Don't forget a make clean afterwards.

Works?

**Comment by mikach** [comment]
@jonasschnelli oh, my bad. now it works. thanks!
