### ISSUE TITLE
RPC registration and management of notification hooks, callbacks, etc.

### ISSUE THREAD

**Issue by kanzure** [bitcoin/bitcoin#5873]
As discussed recently in #bitcoin-dev (in tandem with the webhooks conversation), there may be some benefit to using remote procedure calls for registering notification hooks rather than loading the values from config.

Perhaps the notification system could become more defined. With the upcoming zeromq patch, and the existing statoshi (statsd (metrics)) branch, and the existing notification hooks (blocknotify, walletnotify, alertnotify), there may be an increase in the number of events or the number of actions to dispatch upon their occurrence. Managing these details through RPC seems reasonable. I don't really see the existing config file working forever on this front.

There was also a recent proposal regarding webhooks, which ideally would be registered using the same RPCs. Most of the situations where there is an HTTP server available are also situations where a small dispatch wrapper script can be written, so I don't really have a good reason for proposing this other than it may reduce integration friction for others. But should that ever happen, then sandboxing the webhook HTTP client into a separate process would be prudent.

**Comment by MarcoFalke** [comment]
Closing for now due to lack of interest.
