### ISSUE TITLE
getunconfirmedbalance doesn't take change into account, bitcoin will spend unconfirmed change.

### ISSUE THREAD

**Issue by cheako** [bitcoin/bitcoin#5874]
bitcoin-cli getinfo
{
    "version" : 100000,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 1.29695909,
    "blocks" : 346942,
    "timeoffset" : -1,
    "connections" : 113,
    "proxy" : "",
    "difficulty" : 47427554950.64830017,
    "testnet" : false,
    "keypoololdest" : 1425248678,
    "keypoolsize" : 101,
    "paytxfee" : 0.00052631,
    "relayfee" : 0.00001000,
    "errors" : ""
}
bitcoin-cli listunspent 0 0|tail -n 41
    {
        "txid" : "c928999a42a92d14efd2b256e6c5ce5dd70e18a07099a035148b71429ca77c8d",
        "vout" : 1,
        "address" : "1Exca117ik6cR2mySwfpz4GGrUGRx5p3Eh",
        "account" : "",
        "scriptPubKey" : "76a914991e345e6224f04fbd74cfd0db2191decbe4510988ac",
        "amount" : 0.00100000,
        "confirmations" : 0,
        "spendable" : true
    },
    {
        "txid" : "c9f59a6f5527b746d90bbb28631f586c86616deef439857a53c238ef4a2f68f5",
        "vout" : 1,
        "address" : "1Exca117ik6cR2mySwfpz4GGrUGRx5p3Eh",
        "account" : "",
        "scriptPubKey" : "76a914991e345e6224f04fbd74cfd0db2191decbe4510988ac",
        "amount" : 0.00100000,
        "confirmations" : 0,
        "spendable" : true
    },
    {
        "txid" : "ce9ba77a1d625d32ce788c59689de7d2237d2c3da47a4d8d982ca2507c87d9ac",
        "vout" : 0,
        "address" : "1Exca117ik6cR2mySwfpz4GGrUGRx5p3Eh",
        "account" : "",
        "scriptPubKey" : "76a914991e345e6224f04fbd74cfd0db2191decbe4510988ac",
        "amount" : 0.00100000,
        "confirmations" : 0,
        "spendable" : true
    },
    {
        "txid" : "d7ed6065ab1ff253dc1053d7b1babcb1f085f24eab82968b6eef93cf498688ca",
        "vout" : 0,
        "address" : "1Exca117ik6cR2mySwfpz4GGrUGRx5p3Eh",
        "account" : "",
        "scriptPubKey" : "76a914991e345e6224f04fbd74cfd0db2191decbe4510988ac",
        "amount" : 0.00100000,
        "confirmations" : 0,
        "spendable" : true
    }
bitcoin-cli getunconfirmedbalance
0.00000000

**Comment by laanwj** [comment]
Did you pass `-spendzeroconfchange=0`? If not, this is expected behavior.
