### ISSUE TITLE
Closed window doesn't show when clicking dock icon

### ISSUE THREAD

**Issue by mikez302** [bitcoin/bitcoin#5878]
I am using Bitcoin Core version v0.10.0 on OS X Yosemite 10.10.2. If I click the red close button on the window, it disappears as I would expect. But if I click the icon in the dock, the window does not show. I do not remember seeing this behavior in v0.9.

**Comment by jonasschnelli** [comment]
Hmmm... dejavu of https://github.com/bitcoin/bitcoin/pull/2530?
Will have look at it.

**Comment by fanquake** [comment]
I can see the same behaviour. If you close the window using the red close button, you have to use Show/Hide to bring it back.
