### ISSUE TITLE
git-revlist output in travis log

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#5882]
This appears in the travis logs a few times:
```
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
limiting output:
--max-count=<n>
--max-age=<epoch>
--min-age=<epoch>
--sparse
--no-merges
--min-parents=<n>
--no-min-parents
--max-parents=<n>
--no-max-parents
--remove-empty
--all
--branches
--tags
--remotes
--stdin
--quiet
```
(see for example https://travis-ci.org/bitcoin/bitcoin/jobs/54052269 )
Doesn't appear to break anything, but makes it even harder to find the real problem.

**Comment by dexX7** [comment]
This appears to be related to [share/genbuild.sh#L24-L25](https://github.com/bitcoin/bitcoin/blob/70d80cc7bf89211a5aa157cb624fff3b7097c48e/share/genbuild.sh#L24-L25), and it's dumped when `RAWDESC` is empty.
