### ISSUE TITLE
font size too small in debug console.

### ISSUE THREAD

**Issue by microcai** [bitcoin/bitcoin#5897]
I build with Qt5.

UI is fine with Qt5. normal UI works out-of-box for HIDPI monitor, except debug console.
the font is very small, and can not by adjusted by Ctr+mousewheel or Ctr+Key_Plus

because Mac uses pixel scale, so the UI might be usable on retina mac, but on Linux, there is no PixelRatio ( aka , always = 1.0) so the font should not be specified in fixed pixel size. but use QFontMetrics, or, just just use "points" .

**Comment by jonasschnelli** [comment]
@microcai could you post a screenshot? You are saying that you run on an HiDPI enabled linux window manager?
Qt should handle the pixel ration (>=Qt5) for HiDPI... but never checked in detail because HiDPI is still not widely used on linux.

**Comment by microcai** [comment]
NO,  Qt does not use pixel ratio on linux, even on HiDPI windows. this only for Mac.
mornal app should best just use "point" to specify the font size.

![screenshot_bitcoin](https://cloud.githubusercontent.com/assets/172208/6651477/c7f2fcc8-ca7e-11e4-8076-6b761f43a111.png)

**Comment by jonasschnelli** [comment]
It looks like you are running 0.10 not the master. But this should not make a big difference.
I just see other HiDPI issues which might need to take upstream to Qt. Example: scrollbar-width, icon-size.
Could you post some more screenshots of other screen situations like sending coins, etc.?

**Comment by jonasschnelli** [comment]
Maybe try running the master branch by compiling bitcoin-qt yourself or using a nightly-build: https://builds.jonasschnelli.ch/nightlybuilds/2015-03-14/

**Comment by jonasschnelli** [comment]
found the potential issue. At least it was marked as //todo.
https://github.com/bitcoin/bitcoin/blob/master/src/qt/rpcconsole.cpp#L360
I think it could be changed to `font-size: 1em;` or similar.
But strange that OSX does blow up the font to 24px (on screen; non HiDPI converted) but linux not.

**Comment by microcai** [comment]
other screens are perfectly fine with hidpi settings. font size are all normal. the rpcconsole is currently the only place I see small font.
btw, the splash screen is also not DPI-aware, but that is completely fine.

**Comment by jonasschnelli** [comment]
Thanks for reporting!
The splash screen is not DPI aware in 0.10 but it is in master. Could you try master for a splash-screen check on HiDPI linux (maybe post the screenshot)?

**Comment by microcai** [comment]
I'm trying 0.10 with the mentioned line *removed*
![screenshot_bitcoin1](https://cloud.githubusercontent.com/assets/172208/6651550/689d1f0c-ca82-11e4-8e02-636fde7008a7.png)

now it works fine.

**Comment by jonasschnelli** [comment]
okay...nice. you might also check #5898.

**Comment by luke-jr** [comment]
What does font-size:1em do? Isn't that the same as not setting it?
