### ISSUE TITLE
importx / importprivkey (rescan=last block) RPC command?

### ISSUE THREAD

**Issue by jprichardson** [bitcoin/bitcoin#5899]
Thoughts on adding a new RPC command like `importx` that imports a known transaction ID directly into the wallet? Or, when calling `importprivkey`, add another parameter that tells the rescan to only go as far back as the block specified? e.g. (`importprivkey <privkey> rescan=true xxxxxx`) Maybe both?

My use case:

I've been experimenting with stealth addresses and as the receiver of a stealth payment, you don't know the private key in advance to redeem your funds. This is calculated using data from one of the null outputs (OP_RETURN). When you find a match and the associated private key, you need to import it into your wallet. Since the transaction ID is already known, this makes a rescan unnecessary and a waste of resources, unfortunately it must be done though if you want the balance and transaction to be added to the wallet.

**Comment by luke-jr** [comment]
A transaction id wouldn't necessarily help here if it's already spent (you do want to include past transactions, right?). Why not just add the stealth address support into Bitcoin Core directly?

**Comment by jprichardson** [comment]
@luke-jr There are no past transactions since it's a new address that's calculated at the time of the stealth payment. I'd think that Stealth support would be great, but that's like moving mountains compared to what I'm asking for.

Either:

1. Expose `rescan` to rpc and startup `-rescan` flag and a parameter to accept the start block. By default, it's the genesis block. In other words, just expose the method `ScanForWalletTransactions` as seen here https://github.com/bitcoin/bitcoin/blob/v0.10.0/src/wallet.cpp#L930 (Would probably want to modify `importprivkey` then to have a parameter for starting block as well)

2. Expose a method to add the transaction to the wallet i.e. `AddToWalletIfInvolvingMe` via RPC.

Even better, add both changes.

**Comment by sipa** [comment]
You can use `importwallet`, which can multiple keys at once, with birth time information, and will rescan whatever is necessary.

**Comment by jprichardson** [comment]
@sipa I don't see how `importwallet` would help solve this problem since (as far as I can tell) with the `importwallet` format I can only specify keys. A rescan will still be necessary. I'm trying to avoid doing the rescan as much as possible since I already know the transaction ID that I need to add to the wallet.

**Comment by jprichardson** [comment]
Sorry, I just missed this important part `with birth time information` I assume this may solve the problem... hehehe

**Comment by jprichardson** [comment]
OK, after experimenting more with this, it looks like `importwallet` should be satisfactory for now. It'll be a minor inconvenience for the user if the `birth time` is really old, but it still won't be as bad as scanning the entire blockchain. I think the other requests are valid, but there are no doubt other higher priorities that you must take care of (and understandably so). Closing for now. Thanks for the suggestion and help.

**Comment by neocogent** [comment]
Having a rescan for starting at a specific block would also be very useful for joinmarket and similar uses. When first starting it adds a ton of new addresses to the wallet but since newly created we are sure they have no previous trxs. Currently it has to rescan from block 0, which takes for friggin ever.

**Comment by sipa** [comment]
Use dumpwallet/importwallet if you don't want to rescan everything. It is
far more efficient, and supports timestamped keys. It will rescan multiple
keys at once, and only the necessary part of the blockchain.
