### ISSUE TITLE
small initial dialog size in transactiondescdialog.ui

### ISSUE THREAD

**Issue by microcai** [bitcoin/bitcoin#5906]
When in HiDPI settings, transactiondescdialog is too small initially, though it is re-sizable. 
the reason is that it uses hard-coded size in .ui file. hard-coded to have size

```
<width>620</width>
<height>250</height>
```

That's problematic on platform that don't use pixel ratio, but just pre-monitor DPI settings, like windows >= 8  and Linux.

initial size should be set by  overloadding sizeHint() and use this->fontMetrics() to calculate a proper size.

**Comment by microcai** [comment]
initial size:
![qq 20150316133024](https://cloud.githubusercontent.com/assets/172208/6661036/70dedd18-cbe0-11e4-99b2-3872d780d8f2.png)

well,  it should be
![qq 20150316133104](https://cloud.githubusercontent.com/assets/172208/6661037/71650fb4-cbe0-11e4-841b-20f55b52bbf7.png)

**Comment by Diapolo** [comment]
@jonasschnelli Mind having a look? You're the HiDPI expert ^^.

**Comment by jonasschnelli** [comment]
Yes. There are serval HiDPI issues on Linux. But IMO its mostly a upstream Qt issue. HiDPI works fine on mac and it should also work fine on Linux and Win (if Qts HiDPI behavior would be platform independent). I strongly discourage from adding linux specific HiDPI fixes (especially #ifdefs!). Well, there are some things like font size definitions which should/could be changed to allow more flexible size calculations (like https://github.com/bitcoin/bitcoin/pull/5898).

I have a Linux/Ubuntu HiDPI setup ready and i'd like to test soon a bitcoin-qt with Qt5.4. If there are still things on "our side" to cure, i'd like to see them fixed together in on PR.

**Comment by laanwj** [comment]
The issue for tracking this is #6472
