### ISSUE TITLE
Close button missing on the debug window.

### ISSUE THREAD

**Issue by tuxmaster** [bitcoin/bitcoin#5908]
![close mising](https://cloud.githubusercontent.com/assets/6240474/6663935/94c732f8-cbcb-11e4-89b2-1a52fd626ac4.png)
See the picture for more information.
This is the German version of the dialog, but for the missing button the language is irrelevant.

**Comment by Diapolo** [comment]
What OS is that?

**Comment by fsb4000** [comment]
I have the button at current master
![close](http://i.imgur.com/z71ouq7.png)

**Comment by jonasschnelli** [comment]
Could you give us some more information about your environment?
OS, Window Manager, etc.

Just tested 0.10.0 on ubuntu. Looks good.
It seems like your window manager is removing the standard window buttons.

![bildschirmfoto 2015-03-16 um 11 11 44](https://cloud.githubusercontent.com/assets/178464/6664113/56a9f512-cbcd-11e4-96c8-06a8db64483a.png)

**Comment by tuxmaster** [comment]
No, all dialog's has an extra close/ok button. But only her it will be missing.
For example the the about bitcoin dialog, there exits an button which close the dialog.
![ok](https://cloud.githubusercontent.com/assets/6240474/6664384/845ec56c-cbcf-11e4-8421-cd7f882ca1d3.png)

I don't mean the button at the dialog title box.
Because it is Qt default, that this don't exits an button must be added.
See:
 http://doc.qt.io/qt-4.8/qt.html#WindowType-enum
Part Qt::Dialog
By default no button are shown on the title bar.

OS: Fedora 20/21 using Gnome.

**Comment by jonasschnelli** [comment]
Agreed with @tuxmaster. The rpcconsole should be a QWindow currently it is a QWidget.

**Comment by jonasschnelli** [comment]
@tuxmaster: would you mind retesting this issue with #6155 on top? http://builds.jonasschnelli.ch/pulls/6155/

**Comment by tuxmaster** [comment]
Tested, now the debug window is part of the main window?
![bildschirmfoto von 2015-05-19 08 51 39](https://cloud.githubusercontent.com/assets/6240474/7697087/5daa78fa-fe04-11e4-8387-b373016f807f.png)

**Comment by jonasschnelli** [comment]
@tuxmaster: did you used `--disable_wallet` during `.configure` or `-disablewallet=1` as startup arg?
Also mind that i'll probably add another change to #6155 (change from QDialog to QWindow).

**Comment by tuxmaster** [comment]
Hi,  I used: -disablewallet like shown in the help:
Wallet options:
  -disablewallet
       Do not load the wallet and disable wallet RPC calls

**Comment by jonasschnelli** [comment]
@tuxmaster: I just tested this (nightly build) on Fedora Workstation 21. Looks all good also without #6155. Are you sure this is a real issue? Can you try again with the official 0.10.2 release: https://bitcoin.org/bin/bitcoin-core-0.10.2/?

**Comment by tuxmaster** [comment]
Tested with 0.10.2. The same error as the original. No close button.
![bildschirmfoto von 2015-05-19 17 53 27](https://cloud.githubusercontent.com/assets/6240474/7707467/377afbb8-fe50-11e4-9aec-6a91848daf0d.png)

**Comment by jonasschnelli** [comment]
@tuxmaster: Right. I could reproduce the issue on Fedora 21. 
The current master looks okay.

Do you mind retesting this with a nightly build: https://builds.jonasschnelli.ch/nightlybuilds/2015-05-19/?

**Comment by tuxmaster** [comment]
Yes the nightly looks ok.
Tested on F20.
![bildschirmfoto von 2015-05-20 08 38 10](https://cloud.githubusercontent.com/assets/6240474/7720281/c05cc634-fecb-11e4-9f96-470389eee0a9.png)

**Comment by jonasschnelli** [comment]
@theuni: was there a Qt version change between 0.10.X and current master?

**Comment by tuxmaster** [comment]
As far I can see, from 4.8.6 to 5.x.x.

**Comment by jonasschnelli** [comment]
Okay. Than it was a probably Qt4.X "bug".
@tuxmaster: If you like you can build bitcoin-qt yourself with Qt4. Add #6155 on top and see if it fixes your issue.

**Comment by tuxmaster** [comment]
Result of rebuild with Qt4 of F20 (using my own openssl)
So I think is no Qt bug.
build openssl with: ./config --prefix=/tmp/openssl --openssldir=/tmp/openssl enable-ec enable-ecdh enable-ecds -fPIC shared
And run with:
LD_PRELOAD=/tmp/openssl/lib/libssl.so:/tmp/openssl/lib/libcrypto.so ./bitcoin-qt
![bildschirmfoto von 2015-05-20 12 05 50](https://cloud.githubusercontent.com/assets/6240474/7723429/c82401d0-fee8-11e4-916e-8159ef3bef55.png)

**Comment by jonasschnelli** [comment]
Before closing this i'd like to find the change which fixes this bug.
Maybe someone can help by checking the changes between 0.10.0 and 0.10.2. I couldn't find anything related to this issues behavior.

https://github.com/bitcoin/bitcoin/compare/master...v0.10.2

**Comment by laanwj** [comment]
Closing (inactivity)
