### ISSUE TITLE
CWalletDB LoadWallet : possibly incorrect version check

### ISSUE THREAD

**Issue by retroman** [bitcoin/bitcoin#5914]
In the latest trunk, and versions dating back to at least a month ago, in the file
walletdb.cpp, 
function CWalletDB::LoadWallet,

there is a test near line 617
if (nMinVersion > CLIENT_VERSION)

that seems like it should be checking against FEATURE_LATEST instead.  I discovered this when attempting to run an altcoin that has a CLIENT_VERSION that's less than 60000.

**Comment by theuni** [comment]
Code looks fine to me. Why would CLIENT_VERSION ever be lower than FEATURE_LATEST?

**Comment by laanwj** [comment]
It looks to me too that this code is correct. The wallet versions are based on CLIENT_VERSIONs. 

Client versions are defined as
```c++
static const int CLIENT_VERSION =
                           1000000 * CLIENT_VERSION_MAJOR
                         +   10000 * CLIENT_VERSION_MINOR
                         +     100 * CLIENT_VERSION_REVISION
                         +       1 * CLIENT_VERSION_BUILD;
```

Looking at `wallet.h` there are various threshold versions defined based on the first version that introduced them:
```c++
FEATURE_WALLETCRYPT = 40000    # 0.4.0
FEATURE_COMPRPUBKEY = 60000  # 0.6.0
FEATURE_LATEST = 60000    # 0.6.0, this is max(FEATURE_*)
```

As @theuni says, it makes no sense for FEATURE_LATEST to be higher than the current version. 

If your altcoin uses an alternative versioning scheme you need to change `FEATURE_*` as well. Or get rid of them completely as it will support all features from the beginning.
