### ISSUE TITLE
Documentation of accounts deprecation

### ISSUE THREAD

**Issue by benjyz** [bitcoin/bitcoin#5921]
Accounts is deprecated in the master branch (future 0.11 version). Some relevant documentation that could need an update:

The wiki: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_Calls_list

The RPC is also documented here: https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs

**Comment by jonasschnelli** [comment]
@benjyz you might take this to https://github.com/bitcoin/bitcoin.org.
The wiki is not maintained by the bitcoin-core-developers.
It's also outdated and you should probably use: https://bitcoin.org/en/developer-reference#rpcs

**Comment by paveljanik** [comment]
`git grep "account.*DEPRECATED"` prints a lot of entries. Please close this issue.
