### ISSUE TITLE
Event notification hooks for indexing

### ISSUE THREAD

**Issue by lvella** [bitcoin/bitcoin#5955]
I found myself many times trying to recover some information from the blockchain that were not easily found in the indexed calls from JSON-RPC. So I thought of a solution that is somewhat related to issue #5873, of event notification hooks one would register on the configuration file. So this hooks would get called for the relevant node events, like new block acceptance, and users could implement their own indexed database for whatever information they want. If a new hook is inserted on the configuration to be called on every new block accepted, there should be an option for it to be called with the historical data, in chronological order, so that the user's index would be complete. This issue seems different from issue #5873 that I am concerned with keeping user's database consistent and complete, and an ephemeral notification registration would not give such guarantees.

**Comment by gavinandresen** [comment]
I vote no; you can already get notifications of new blocks with -blocknotify, and can get historical blocks with the RPC getblock call.

I don't like breaking the pattern of "notify calls just tell you of new stuff, use RPC if you need historical information."

**Comment by MarcoFalke** [comment]
This is implemented. See `./src/index/base.h`
