### ISSUE TITLE
Pieter Wuille (sipa) is signing commits with an unverifiable PGP key

### ISSUE THREAD

**Issue by b6393ce9-d324-4fe1-996b-acf82dbc3d53** [bitcoin/bitcoin#5956]
Apparently, [Pieter Wuille (sipa)](https://github.com/sipa) is signing commits with RSA key ID F8F0B657, the public key of which is not listed anywhere meaningful (if anywhere at all).

In particular, at this location:

* https://bitcoin.org/en/development

there is listed (among other developers' PGP keys) Pieter Wuille's key with ID [1DAAC974](https://pgp.mit.edu/pks/lookup?search=Pieter+Wuille&op=index), which is also mirrored by MIT's PGP keyserver. However, this is *not* what he's using to make the signatures for objects in Bitcoin's git repository.

**Comment by fanquake** [comment]
F8F0B657 is one of the subkeys of 1DAAC974
![screen shot 3](https://cloud.githubusercontent.com/assets/863730/6912599/34f5b87c-d7a6-11e4-9a7b-b9d6d5548432.png)

It's also listed here http://pgp.mit.edu/pks/lookup?op=vindex&search=0xB9A408E71DAAC974

**Comment by b6393ce9-d324-4fe1-996b-acf82dbc3d53** [comment]
Thanks! I imported the key provided by MIT's keyserver:

* https://pgp.mit.edu/pks/lookup?op=get&search=0xB9A408E71DAAC974

Now, I have that subkey; apparently, `bitcoin.org` needs to update this file:

* https://bitcoin.org/pieterwuille.asc
