### ISSUE TITLE
[Suggestion] Use a decreasing difficulty depending on the time from last block to smooth the time between blocks

### ISSUE THREAD

**Issue by tuxayo** [bitcoin/bitcoin#5974]
There would be a base difficulty which would work like the actual difficulty.
And there would be a decreasing coefficient to reduce the variance.
Take an example with a base difficulty of 100:
When the last block is 5min old, the network would not accept a block with a difficulty less than 200
When the last block is 10min old, the network would not accept a block with a difficulty less than 100
When the last block is 15min old, the network would not accept a block with a difficulty less than 50

Can someone confirm if this looks correct or would it break everything?

**Comment by TheBlueMatt** [comment]
Miners pick the timestamp, its not strictly enforced, so this proposal would essentially let miners pick their difficulty.

**Comment by tuxayo** [comment]
> Miners pick the timestamp, its not strictly enforced, so this proposal would essentially let miners pick their difficulty.

You mean they could pick a timestamp from future and solve and easier challenge?
Is the network currently accepting blocks with a timestamp from future?

**Comment by laanwj** [comment]
This is not the place to discuss or decide such network-wide changes, use the bitcoin-development mailing list for that. Although I have to warn you, the chance that anyone will go along with this change is very small.
