### ISSUE TITLE
[Suggestion] separate application layers from main.cpp

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#5977]
src/main.cpp deals with p2p protocol, storage, wallet, etc. (src/main.cpp has more than 4500 lines..)

what do you think about moving the code to proper files/classes?

**Comment by luke-jr** [comment]
Check out the git log, this has been a work in progress. Feel free to help out...

**Comment by promag** [comment]
next simple change would be #5979

**Comment by laanwj** [comment]
Yes, this is in progress.

**Comment by CryptAxe** [comment]
I think this could be closed now.

**Comment by jonasschnelli** [comment]
mostly solved with #9260. Closing.
