### ISSUE TITLE
Private testnet mining is broken in version 0.10.0

### ISSUE THREAD

**Issue by apoloval** [bitcoin/bitcoin#5984]
We are experimenting issues while mining using RPC API in version 0.10.0 

Scenario: private testnet, not connected to the public testnet with a custom genesis block. We use it to run integration tests of our software. To reduce the testing time, we restore the blockchain to a known state every time the tests are run. 

The whole system were working perfectly. After upgrading `bitcoind` to version 0.10.0, we cannot mine anymore. `bitcoind` responds with an error 500 with the error message _Bitcoin is downloading blocks..._, even when the daemon has fully reindexed the contents and using the flag `-checkpoints=0`. 

Reading the source code of Bitcoin, we realized there is a check that is causing the daemon to consider it is downloading blocks even when it is not. In `src/rpcmining.cpp` we have this guard:

```c++
    if (IsInitialBlockDownload())
        throw JSONRPCError(RPC_CLIENT_IN_INITIAL_DOWNLOAD, "Bitcoin is downloading blocks...");
```

So the result of `IsInitialBlockDownload()` is the clue. We have the following implementation.

```c++
bool IsInitialBlockDownload()
{
    LOCK(cs_main);
    if (fImporting || fReindex || chainActive.Height() < Checkpoints::GetTotalBlocksEstimate())
        return true;
    static bool lockIBDState = false;
    if (lockIBDState)
        return false;
    bool state = (chainActive.Height() < pindexBestHeader->nHeight - 24 * 6 ||
            pindexBestHeader->GetBlockTime() < GetTime() - 24 * 60 * 60);
    if (!state)
        lockIBDState = true;
    return state;
}
```

After some debugging, we found out the problem is caused by the following expression.

```c++
pindexBestHeader->GetBlockTime() < GetTime() - 24 * 60 * 60
```

If we understand it well, a best header mined before 24 hours ago means the initial block is being downloading. That could make sense for mainnet and public testnet, but breaks the possibility to have a private testnet with private miners that had interrupted the mining process at some instant for more than 24 hours. 

We recompiled `bitcoind` with the following expression for `state` variable and the miner succeed to connect to the daemon and is mining without problems. 

```c++
    bool state = (chainActive.Height() < pindexBestHeader->nHeight - 24 * 6);
```

We don't understand perfectly what's the purpose of this state calculation and what would be the effect to remove this guard. So we cannot provide a patch to fix it. Any idea on how to fix this issue?

**Comment by luke-jr** [comment]
It should be safe to remove the check for testing. I have an incomplete fix for this locally, but it adds the tip expiry time as a chain param.

**Comment by laanwj** [comment]
See #5987

**Comment by apoloval** [comment]
Perfect! #5987 should fix the issue!

**Comment by laanwj** [comment]
Note that in 0.12, this no longer comes automatically with `-testnet`, but you need to set the tip age manually to a large number, say `-maxtipage=99999999`.
