### ISSUE TITLE
EXCEPTION: St9bad_alloc       

### ISSUE THREAD

**Issue by kaotisk-hund** [bitcoin/bitcoin#6001]
The following occurred today on Ubuntu 14.04 LTS 64bit, bitcoind v0.10

************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
bitcoin in ProcessMessages()       

bitcoind: main.cpp:1647: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
Aborted (core dumped)

**Comment by sipa** [comment]
bad_alloc almost certainly means you ran out of memory.

**Comment by luke-jr** [comment]
Just address space, actually. Try:
```
sysctl vm.overcommit_memory=1
```
(this is temporary and will be lost at reboot)

If you don't have enough memory, it won't help much though.

**Comment by kaotisk-hund** [comment]
Thank you very much both :)
