### ISSUE TITLE
[Notification] r/bitcoin donated > $450 to the devs of this repo, please claim your share

### ISSUE THREAD

**Issue by patricksavalle** [bitcoin/bitcoin#6005]
For those that have missed [this discussion](http://www.reddit.com/r/Bitcoin/comments/3240ro/im_now_funding_all_the_devs_in_the_world_who_are/): it is now possible to directly reward the devs that participate in this (and other) repo(s) based on actual participation levels. The r/bitcoin community already donated so as a courtesy to them, please accept their support. The donations can be [found and claimed here](https://mobbr.com/#/task/aHR0cHM6Ly9naXRodWIuY29tL2JpdGNvaW4vYml0Y29pbg==). Those that have public email addresses have received mail, those that have not need to be notified by other means, such as this.

### Claiming your share

[Sign up](https://mobbr.com/#/join) to the platform, goto to -> `settings` -> `authenticated ID's` [here](https://mobbr.com/#/settings/ids) and authenticate your Github account (by OAUTH). The reward will be in your Mobbr wallet. Short explainer [here](https://www.youtube.com/watch?v=uZ2beq1hBwE).

### Some explanation on how the rewards are divided

On Github only a few types of participation are measured/rated. In that regard it is not a very social platform (yet). Our current algorithm uses those statistics to distribute rewards among participants. Instead of just using LOC, the algorithm weighs: 
- the number of commits accepted into main branch
- number of lines added
- number of lines deleted
- recentness of a contribution. 

It does some normalisation to reduce extremes. Not perfect, but generally fair enough to be useable. 'Kinda mostly reasonable...' as [Gavin said](http://www.reddit.com/r/Bitcoin/comments/3240ro/im_now_funding_all_the_devs_in_the_world_who_are/cq82k0l). 

Remember that repos are moderated by means of pull-request. So there is quality control before the algorithm does its thing. Ideally Github should measure more types of participation and have additional mechanisms and more 'passive factors' (like voting). This would make the algorithm more optimal.

We are open to suggestions on perfecting the algorithm, but in the end this part should be implemented in the collaboration platform itself, not on our end. We can imagine having a dashboard to tune the algorithm to the needs of the project. This would make social collaboration steerable.

### crowdfunding issues and milestones

It is possible to pay repo's, issues and milestones. As long as the issues or milestones are still open, they are being crowdfunded. Once they are closed, the funds are distributed. These options can be used to allow crowds to 'vote' on features, by means of donations. Etc.

----------------------- list of contributors

![mobbr crowdpayment system](https://cloud.githubusercontent.com/assets/701331/7105097/d6af2990-e107-11e4-9a5b-07a231c1f780.jpg)

**Comment by patricksavalle** [comment]
Almost $600 now.

**Comment by Diapolo** [comment]
@patricksavalle Tried it, but seems I'm not even listed within MOBBR?

**Comment by patricksavalle** [comment]
@diapolo Everything ok now? I can see your profile in Mobbr, I also see others changing their privacy settings. I have too admit their are still slight discrepancies between the AngularsJS frontend and our API on the settings screen. If you like, you could report issues here: https://github.com/mobbr/mobbr-frontend
