### ISSUE TITLE
Ability to configure an arbitrary testnet genesis block

### ISSUE THREAD

**Issue by davout** [bitcoin/bitcoin#6015]
It would be very useful to be able to easily generate/configure an arbitrary testnet genesis block.

It would help a lot with regards to people pointing ASICs to testnet, ruining it for everyone else on one hand. On the other hand, if that problem is solved, it would allow testnet to behave _exactly_ like main net (it would be possible to remove the weird "if no block has been mined for 20 minutes, accept blocks at diff 1").

That would make seeding peers impossible unless you specify them, but it would make testing so much easier in a lot of cases.

**Comment by MarcoFalke** [comment]
This is probably solved by #2632

**Comment by MeshCollider** [comment]
Also relevant is #8994 which does a similar thing with more flexibility
