### ISSUE TITLE
[ Bitcoin-Qt ] Linux client can't read directories with an @ in its name

### ISSUE THREAD

**Issue by msx** [bitcoin/bitcoin#6018]
Hi all,
I'm trying to use a Btrfs subvolume for storing the blockchain and the wallet, however the Qt client seems to be unable to access a directory which its name is prefixed with an @.
This is the error message I got:
"A fatal error occurred. Bitcoin can no longer continue safely and will quit.
EXCEPTION: N5boost12interprocess22interprocess_exceptionE       
No such file or directory       
bitcoin in Runaway exception"

I already tried "./bitcoin-qt -debug" and "./bitcoin-qt --help-debug" to no avail as the window with the error message pops up and there isn't anything else I can do.

Regards.

**Comment by dexX7** [comment]
Hey @msx: are you using Bitcoin Core 0.10 or a build based on the current master?

**Comment by msx** [comment]
Oops, I apologize for my very n00bish report :P

Hello @dexX7,
Yes, I tried bitcoin-0.10.0 which I downloaded from the website, on this system:
OS: Fedora 21 x86_64 up-to-date
kernel: 3.19.3
btrfs-progs: 3.18.1

```
cat ~/.config/Bitcoin/Bitcoin-Qt.conf 
[General]
strDataDir=/home/@somedir/another_dir/@pretended_target_dir
fRestartRequired=false
fMinimizeToTray=false
fMinimizeOnClose=false
nDisplayUnit=0
strThirdPartyTxUrls=
fCoinControlFeatures=false
nDatabaseCache=100
nThreadsScriptVerif=0
bSpendZeroConfChange=true
fUseUPnP=true
fListen=true
fUseProxy=false
addrProxy=127.0.0.1:9050
language=
nHelpMessageDialogWindowPos=@Point(400 250)
nHelpMessageDialogWindowSize=@Size(800 400)
```

I would be delighted to help you nail down this bug, let me know if I can be of further assistance.

**Comment by ajweiss** [comment]
Hi @msx,

Qt's settings module gives special meaning to the at (@) symbol if it appears as the first character in a settings value.  If you look at the configuration snippet you posted here, you can see it in the last two lines.

Does the real string that you're attempting to use for your datadir meet this criteria?

**Comment by gappleto97** [comment]
If someone can give me an idea of what's going on, and where the definition is, I can work on a pull request for this.

**Comment by ajweiss** [comment]
Nevermind, the at symbols are fine.

I was able to reproduce this...  Check the permissions on your subvolume.

Cheers!

FWIW: btrfs subvolumes are really awesome for testing bitcoin.  I use them for rollbacks and testing sync all the time.

**Comment by gappleto97** [comment]
So you're thinking that it was a permissions issue and not a definitions issue? Just trying to make sure I understand.

**Comment by ajweiss** [comment]
Yup.

    adam@viktor:~/dev/bitcoin-dist-0.10/bitcoin-0.10.0/bin$ sudo btrfs subvolume create /archive/@test
    Create subvolume '/archive/@test'
    adam@viktor:~/dev/bitcoin-dist-0.10/bitcoin-0.10.0/bin$ ./bitcoin-qt 
    
    
    ************************
    EXCEPTION: N5boost12interprocess22interprocess_exceptionE        
    No such file or directory        
    bitcoin in Runaway exception       
    
    adam@viktor:~/dev/bitcoin-dist-0.10/bitcoin-0.10.0/bin$ sudo chmod 777 /archive/@test/
    adam@viktor:~/dev/bitcoin-dist-0.10/bitcoin-0.10.0/bin$ ./bitcoin-qt

**Comment by gappleto97** [comment]
Very odd. Is there no way to just have a permissions check before QT launches? You'd think that would be useful.

**Comment by gappleto97** [comment]
For microsoft versions there's a quick test method. Otherwise we should just create a test file on open, and if that throws an error, then notify the user.

**Comment by msx** [comment]
## I'M A TARD ##

Effectively, I forgot to own the subvolume after creating it :clap: 
That's what happens when you are half-sleep, half-stupid.

Sorry 4 the noise everyone, I'm closing this shameful ticket.
