### ISSUE TITLE
Bitcoin size is over 35GB now. This MUST be fixed or anyone will stop using your client...

### ISSUE THREAD

**Issue by stupnserg** [bitcoin/bitcoin#6027]
So, I waited for DAYS to download all the blockchain which also slows down my work a lot and now my PC don't have any free space and I have to uninstall your client... Do you guys really think we have nothing better to do than waste our entire disk space for your client and wait forever to download bitcoin history??? You can be sure that in a year when it will be more than 100 GB in size - NO ONE EVER except freaks will use your client because it will become absolutely unusable...

**Comment by luke-jr** [comment]
The disk space required for Bitcoin Core (about 48 GB) costs about $2 today, and the initial download only needs to be done once. If the node sync makes your computer unusable, this is a problem with your operating system managing resources poorly - you may wish to try upgrading it.

It is not our problem if you don't want to use Bitcoin: other "clients" are *not* Bitcoin; they only remotely access Bitcoin Core nodes, and compromise your security and privacy to varying degrees by trusting those other nodes.

That being said, the huge conceptual to-do list does include at least making the wallet work as a remote/trusting node while it does the sync in the background - but it isn't a high priority item for anyone AFAIK. If that is important to you, you may wish to create a bounty to fund its development.

**Comment by sipa** [comment]
Maybe this isn't clear from Luke's response, but Bitcoin Core is not the
only program interacting with the Bitcoin network, and certainly not the
only way to send and receive coins.

Bitcoin was designed to support different security/trust models. One of
them is running a full node, like Bitcoin Core implements. This gives you
the highest level of protection and security against fraudulent
transactions. In addition, it helps other clients get their data. The
downside is that this requires verifying and storing all transactions
(though a reduced mode where they are still downloaded and verified, but
not stored forever, is in the works).

As said, if you're trade in some security for convenience, other software
is likely a better choice for you. See the bitcoin.org website.

**Comment by laanwj** [comment]
Please don't reply to rude comments like this, they have no place here and it sets a bad precedent.
