### ISSUE TITLE
Imported addresses do not trigger a walletnotify

### ISSUE THREAD

**Issue by drupalnomad** [bitcoin/bitcoin#6040]
walletnotify is really useful because you can respond as soon as a transaction is broadcast or confirmed, but it only works for addresses in the bitcoind wallet. If you import an address from an xpub, for example, walletnotify does not seem to trigger.

Can walletnotify be extended to work with imported addresses?

**Comment by laanwj** [comment]
I think it can be considered a bug if `-walletnotify` doesn't trigger for transactions on watch-only addresses.

**Comment by jonasschnelli** [comment]
Agreed with @laanwj. At first sight (https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L743) i was assuming that watch-only  addresses also triggering the -walletnotify script.
Will test in detail soon.

**Comment by drupalnomad** [comment]
Sorry - my mistake. It does trigger a wallet notify.

The problem I was encountering was that when I called gettransaction on a payment to a watch address the details section was empty. I suppose this section is specifically for actual wallet transactions.
