### ISSUE TITLE
Don't redo script validation in re-reorg

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#6046]
In case a block was already validated, and BLOCK_VALID_SCRIPT was set on it, don't redo script validation. This probably hardly ever happens in practice (it would require validating a block, reorging away from it, and reorging back to it), but it's the more sane thing to do - do validation when we don't already know it's done.

This may mean that the reconsiderblock RPC needs to changed to unset that validation flag.

**Comment by MarcoFalke** [comment]
Seems like a obscure edge case to keep a feature request open

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
