### ISSUE TITLE
Decouple frontend GUI & backend daemon

### ISSUE THREAD

**Issue by cpengr** [bitcoin/bitcoin#6069]
This is a suggestion(s) for improvement.

It would be nice to be able to have a single blockchain collector daemon (bitcoind) running on an always-on server, and to be able to connect to it with various clients (bitcoin-qt, bitcoin-cli, new clients yet to be developed) on various machines on my home network. Then I can have the advantages of the GUI, without having to worry about running it all the time, just to catch up with the blockchain.

On Windows, you could still have the unified Bitcoin Core installer, but you'd be able to point it to a remote instance of the daemon. Ideally, you'd be able to run the daemon as a service on Windows, or headless on Linux. (I think the latter is already happening with bitcoind, but IDK which clients can connect to it.)

Sorry I'm not totally clear yet on which aspects of this are already implemented, but it isn't all yet.

**Comment by sipa** [comment]
Well, you can already connect any SPV wallet to Bitcoin Core, and have this behaviour.

**Comment by sipa** [comment]
It's a very common request though, but the plan (which we are only very slowly working towards) is disconnecting the wallet from the blockchain code, rather than disconnecting the gui from the backend. This means, rather than have multiple GUIs connect to one backend, you could connect multiple independent wallets to a background node service. This has significant security advantages too, as the different wallets would manage their own keys and ledgers.

**Comment by cpengr** [comment]
Thanks for the quick response.

> Well, you can already connect any SPV wallet to Bitcoin Core, and have this behaviour.

Well for me, I'd want to run a headless backend on Linux, so that would be bitcoind, not Bitcoin Core, meaning not possible yet - right?

And *any* SPV client?

> the plan (which we are only very slowly working towards) is disconnecting the wallet from the blockchain code, rather than disconnecting the gui from the backend.

This sounds like the same basic thing I'm suggesting, except that you're specifying where the wallet lives, i.e. where the keys live (frontend, not backend). Am I understanding correctly?

**Comment by sipa** [comment]
bitcoind is the headless version of Bitcoin Core.

Yes, any SPV client.

**Comment by cpengr** [comment]
So from the POV of my suggestion, it seems that all that's missing is for Bitcoin Core GUI (whatever it's called) to be able to act as an SPV client. Correct?

Also, can you answer this one?

> This ["the plan..."] sounds like the same basic thing I'm suggesting, except that you're specifying where the wallet lives, i.e. where the keys live (frontend, not backend). Am I understanding correctly?

**Comment by laanwj** [comment]
> So from the POV of my suggestion, it seems that all that's missing is for Bitcoin Core GUI (whatever it's called) to be able to act as an SPV client. Correct?

That's likely to happen at some point.

**Comment by promag** [comment]
Maybe only after #10102?

**Comment by MarcoFalke** [comment]
Yes, multiprocess goes into that direction. You can help by reviewing #10102  . But this feature request from 2015  seems not important enough right now to keep it sitting around idle in the list of open issues.
