### ISSUE TITLE
We're using SPV peer's time to compute our network offset

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#6071]
They seem to be more frequently off than full nodes.

Maybe we should ignore those?

**Comment by laanwj** [comment]
I've never liked adapting our time to the network at all, but this might make sense. This would avoid inadvertent problems. SPV clients have a weaker requirement to have a correct date than full nodes.

**Comment by dgenr8** [comment]
@sipa That's not intuitive to me.  Where did you observe it?  I would think any peer running on a mobile device has an accurate time.

Anyhow, I agree with @laanwj, network-recommended adjustment should be used only to warn the user to check his clock.

The original code said NTP was planned as the "3rd chronometer" but it would be a bad idea to turn bitcoind into an NTP client.  Leave it to the system operator to decide how to set his clock well.

The network will still "vote" on the correct time particularly with respect to blockTime validation -- but a remote attack vector against our clock is eliminated.

**Comment by dcousens** [comment]
Is the client currently adjusting the system clock?

**Comment by davecgh** [comment]
It does not adjust the system clock directly, however the time provided by the system clock is adjusted based upon the time data provided by other nodes on the network before its use.

**Comment by TheBlueMatt** [comment]
I'd say the solution is to only use the network-time-offset in cases where your network time is off from your peers by eg > 1 minute, or so.
