### ISSUE TITLE
Edit Balance

### ISSUE THREAD

**Issue by MaxiBillion** [bitcoin/bitcoin#6087]
Anybody know how to edit Bitcoin balance via settings or API as I would like this feature for my program.

**Comment by sipa** [comment]
Eh, you can increase your balance by receiving BTC and you can decrease it by sending BTC...

I'm not sure what else you're looking for. Just being able to change the amount of BTC you have would not result in anything you can spend on the network.

**Comment by luke-jr** [comment]
You can use "move" to change the balance in your accounts, but note that accounts are deprecated...

**Comment by laanwj** [comment]
Hehe. Don't we all.
