### ISSUE TITLE
Different values of a single TX in the wallet Core 0.10.1 and in blockchain?

### ISSUE THREAD

**Issue by capitalDIGI** [bitcoin/bitcoin#6090]
I can see different value of my last transaction in the wallet Bitcoin Core 0.10.1 and in the Blockchain.
Look at the screenshot from the wallet (the attachment) and compare it to:
https://blockchain.info/tx/923edf4f1e0a5da5e0995f0dcca04152c06af094e67d5d49571ba7984bbe0e15

The difference is strange and I can't understand why (over 1.5 year in Bitcoin network and I can see first time something similar). I didn't ask yet our technicians, firstly I would like to have your opinion about it. I turned off the wallet immediately (after first confirmation) when i saw that in Blockchain.org the value is completely different. I'm more a Bitcoin investor than a Bitcoin programmer, but I take care seriously about security on my computers.  

Does have anyone an idea what is it (an error in Blockchain or a theft) and what to do with it? 
![transaction-on-the-wallet-clear](https://cloud.githubusercontent.com/assets/10259280/7425228/4602cdf2-efad-11e4-81fb-d88a14eb9b21.png)

**Comment by paveljanik** [comment]
Please explain "the different values". What is different? Do you know what change address is?

**Comment by capitalDIGI** [comment]
Thank you for you are interested in the case. Yes, you are right - it could be a reason of a change address.

What can I do - my wallet seems different summary amount of BTC than a summary of my existing addresses from blockchain? 
I'm interested is this one of described situations in http://bitzuma.com/posts/five-ways-to-lose-money-with-bitcoin-change-addresses/? 

I have a backup from of the wallet from yesterday. How do you think - what I should do - I turned off the wallet after first confirmation.

**Comment by paveljanik** [comment]
Turn your Bitcoin Core client again to sync. But it should show the change in unconfirmed balance anyway (Pending)...

**Comment by capitalDIGI** [comment]
Thanks for the info, should it be made from a backup or from an existing wallet?

Does it mean "the change in unconfirmed balance anyway (Pending)..." that is this change amount of BTC as permanently lost? 
Will it be always "pending" or should it be synced in several minutes and the outstanding change value will be cleared in several minutes?

**Comment by paveljanik** [comment]
Do not replace the wallet.dat with the backup (this is one of the five above mentioned ways to lose money!). The change was sent to 1ES6r... and has 55 confirmations in the network, so it should be almost immediately shown in your balance (in your wallet not in your address)...

**Comment by capitalDIGI** [comment]
Sure, Thank you, I was thinking that it can't be run from a backup (as described in the article) - and you confirmed me it. I will try in minutes and I will let you know about results.

**Comment by paveljanik** [comment]
If it is OK, please close the issue.

**Comment by capitalDIGI** [comment]
Sure, I will do it, Currently I'm starting the machine, than before sync I'll be checking carefully the wallet by such commands like listreceivedbyaddress, etc. before starting sync. 
If everything is well presented through API (without sync) then I will try to sync. 
So it will take about 20-40 minutes and I will let you know about results for sure.

**Comment by capitalDIGI** [comment]
The command listaddressgroupings returns the address  of 1ES6r... in my wallet, so I am trying the sync.

**Comment by capitalDIGI** [comment]
Everything is OK now, thank you very much. 
How can I make you are honoured (donated with BTC) by me for your support ?

**Comment by paveljanik** [comment]
Great, thanks for confirmation. Can you please close the issue now?

If you want to support the Bitcoin Core development, you can donate at

185eoqaHDLiW2nNA2x9EJCH78ireoB4oRb

Thanks!

**Comment by capitalDIGI** [comment]
Thank you for your engagement once again! 
Obviously I will make a pledge for the Bitcoin Core development and this address will be very helpful.

Regards,

Mario
