### ISSUE TITLE
"out of sync" message causes confusion

### ISSUE THREAD

**Issue by essofluffy** [bitcoin/bitcoin#6106]
The red "out of sync" message when synchronizing with the Bitcoin network does not convey enough information for the user to understand nothing is wrong with the wallet.

See the multiple posts new users of Bitcoin Core have posted:

http://www.reddit.com/r/Bitcoin/comments/34c0xu/so_i_decided_to_try_out_bitcoin_im_guessing_this/

http://www.quora.com/How-long-should-I-wait-for-my-Bitcoin-core-wallet-to-sync-before-giving-up-and-trying-a-different-Bitcoin-wallet

http://bitcoin.stackexchange.com/questions/32528/i-cant-find-my-bitcoin-address-and-my-bitcoin-core-is-out-of-sync-by-3-years

http://bitcoin.stackexchange.com/questions/11029/how-long-should-synchronizing-your-wallet-for-the-first-time-take

http://www.makeuseof.com/answers/how-long-does-it-take-a-bitcoin-wallet-to-sync/

http://bitcoin.stackexchange.com/questions/32802/my-bitcoin-wallet-is-out-of-sync-after-connecting-for-the-first-time

https://bitcointalk.org/index.php?topic=55235.0

**Comment by Diapolo** [comment]
Seems mouseovers aren't read ;)... anyway, @jonasschnelli has a nice solution IMHO, but that won't stop such complaints from happening I guess.

**Comment by laanwj** [comment]
Should be solved by #6110
