### ISSUE TITLE
use a recommended size (550?) when using arg `-prune` or `-prune=1`

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#6120]
If you start bitcoind (current master) with cmd arg `-prune` (without any `=value`) it won't prune because value ~~1~~0 is below the minimum size.

Why not using a recommended size (550MB) when giving no value (0)?

EDIT: `-prune` without a value maps to 0.

**Comment by laanwj** [comment]
I'd rather have people specify the amount explicitly

**Comment by fanquake** [comment]
I agree, anyone who knows enough to be using autoprune should have their own pruning amount in mind when doing so. Probably better for us to force the user to decide than to pick an arbitrary amount and face any possible issues because of it.

**Comment by jonasschnelli** [comment]
Yes. The error-message is helpful.
Right. I Agree.
