### ISSUE TITLE
openssl build fails on Windows 8

### ISSUE THREAD

**Issue by yasamanG** [bitcoin/bitcoin#6127]
Following the instructions for W64, I get fatal error executing  "nmake -f ms\ntdll.mak", where it complains about ml64 not being recognized as a command. Below is the last lines of compilation message:
        cl /Fotmp32dll\fips_ers.obj  -Iinc32 -Itmp32dll /MD /Ox -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0
ENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DO
 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM
_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DOPENSSL_USE_APPLINK -I. -D
DOPENSSL_NO_MD2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_STATIC_ENGINE /Zi /Fdtmp32dll/lib -D_W
_BUILD_SHLIBCRYPTO -c .\crypto\fips_ers.c
fips_ers.c
        set ASM=ml64 /c /Cp /Cx /Zi
        perl crypto\x86_64cpuid.pl tmp32dll\x86_64cpuid.asm
no assembler found on %PATH at crypto\perlasm/x86_64-xlate.pl line 93.
        ml64 /c /Cp /Cx /Zi /Fotmp32dll\x86_64cpuid.obj tmp32dll\x86_64cpuid.asm
'ml64' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'ml64' : return code '0x1'
Stop.

Any idea what I may be missing in my environment? Googling didn't help either :(

**Comment by laanwj** [comment]
I don't know - as you may have noticed, we do the Windows and MacOSX release builds with a cross-compiler. So this problem does not occur.
All I can see is that you are missing the command `ml64`.
I suggest asking this question in a more appropriate forum for questions about OpenSSL.
