### ISSUE TITLE
Team > Git > Clone

### ISSUE THREAD

**Issue by hennyC** [bitcoin/bitcoin#6139]
Hi,

I selected Team>Git>Clone and clicked finish.
The project download successfully, however there are issues after that.

The menu show as follows :

Do you want to create an ide project from the cloned sources ?
(I Click) -> Create Project

The "New Project" screen appears but shows no option ?

Thanks
Hendrik

**Comment by Diapolo** [comment]
Seems more like a GitHub issue and not a bitcoin one?

**Comment by laanwj** [comment]
You should contact github for issues with the site, there is nothing we can do here.
