### ISSUE TITLE
Cannot -rescan or -reindex directory junction [Windows 7]

### ISSUE THREAD

**Issue by evanram** [bitcoin/bitcoin#6151]
I accidentally launched bitcoin-qt after moving my Bitcoin/blocks directory just before creating directory junction. This wrote over my database folder.

Then I made the link:
```
C:\>mklink /J "%APPDATA%\Bitcoin\blocks" "E:\Bitcoin\blocks"
Junction created for [...]
```

Bitcoin-qt immediately exits with same N5boost10filesystem16filesystem_errorE exception.

Rescanning fails:
```
C:\Program Files\Bitcoin\daemon>bitcoind -rescan
```
```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: Cannot create a file when that file already
 exists: "C:\Users\Admin\AppData\Roaming\Bitcoin\blocks"
C:\Program Files\Bitcoin\daemon\bitcoind.exe in AppInit()
```

Reindexing fails with error "Error opening block database"

**Comment by laanwj** [comment]
Instead of creating a junction, pass a `-datadir=` argument to bitcoind (or put it in bitcoin.conf) to tell it of the new location.
