### ISSUE TITLE
0.10.1 cli RPC createrawtransaction creates txn type 1 which it will itself reject very soon

### ISSUE THREAD

**Issue by kanoi** [bitcoin/bitcoin#6157]
This one seems rather urgent for a fix/release:
The cli RPC createrawtransaction is creating type 1 transactions by default that it will itself reject shortly

https://github.com/bitcoin/bitcoin/blob/master/src/primitives/transaction.h#L184

Simple test - use bitcoin-cli RPC createrawtransaction - and look at the first 4 hex bytes output.

**Comment by sipa** [comment]
Why would v1 transactions be rejected?

**Comment by kanoi** [comment]
Isn't that the point of the old debug message in 0.9.* that was removed?
e.g. SetBestChain: 17 of last 100 blocks above version 2
re: BIP 66?
Or have I misunderstood it :P

**Comment by luke-jr** [comment]
Version 2 *blocks*, not transactions, will "soon" be rejected. 0.10.x always makes version 3 blocks.

**Comment by laanwj** [comment]
The plan about v2/v3 transactions is in BIP62, not BIP66. With the note however that "v1 (and v2) transactions remain valid forever." There are no plans to reject any version of transaction, ever.

@sipa go away, you're on holiday  :astonished:

**Comment by kanoi** [comment]
Thanks - yep - I misunderstood :)
