### ISSUE TITLE
Missing bitcoin.conf and wallet.dat while bitcoind was running

### ISSUE THREAD

**Issue by book89** [bitcoin/bitcoin#6170]
My wallet and .conf disapeared out of nothing, cheking linux ubuntu logs i found out that bitcoind crashed hours before i noticed the files were missing. May it be caused by the crash? Can i recover the files? Every other files were preserved.

**Comment by jonasschnelli** [comment]
This can hardly done by bitcoind. You might have malware on your system. I hope you did (a) backup(s) of your wallet.dat at least?

**Comment by book89** [comment]
i did not :/

**Comment by jonasschnelli** [comment]
If you don't have a backup of your private keys (wallet.dat backup, dump) you probably have lost your coins (if you had received bitcoins with your wallet).
Consider reinstalling your system because IMO it could be possible that a tool or someone did remove your wallet and config.

**Comment by book89** [comment]
It is on a rented privated server, i could not find any suspect login on auth.log but could the host provider manage to do it anyway?

**Comment by jonasschnelli** [comment]
I don't want to say your system is compromised. But this would be the first thing i would think that it happend if my wallet.dat and bitcoin.conf are gone. And do you think a tool or a intruder would leave traces in auth.log etc.?

IMO it's a bad setup to have a wallet on a rented private server. Maybe use a local SPV wallet connected to your private server full node or – if you like the challenge – use `bitcoin-tx` or `bitcoind` RPC rawtransactions functions **locally** to create transactions while running a watch-only wallet on your rented private servers full node.

**Comment by laanwj** [comment]
Bitcoind contains no code for deleting your wallet, nor your bitcoind.conf file.

It could be unfortunate random disk corruption (check your system log for filesystem errors), but I agree with @jonasschnelli that disappearance of these two specific files is very suspicious and I"d too recommend reinstalling the server, or hosting it somewhere else if you don't trust the hoster (mind that hot bitcoin walets on VPS have been popular targets, e.g. the linode 'hacks').

**Comment by book89** [comment]
I'm still investigating, i have no traces of an intruder. But if only those two files are missing it also makes it hard to think of anything else other than a intruder and a bitcoind crash/fail. My private server was not in a cloud, could the DC manage to get in anyway?

**Comment by jonasschnelli** [comment]
@book89 if you use a standard non-hardened linux-disto without any form of disk encryption, etc. everyone who can physically access your server can steal / delete your files. And most hosting/housing companies have their own linux disk images (for faster installation and quicker setup) sometime even own package repositories (mirrors), sometimes bypassing the package key/verify system. There are many ways of compromising your system in a such environment.

**Comment by laanwj** [comment]
To be clear: a bitcoind crash *cannot* cause this. It is possible for the wallet to be corrupted (which can often be salvaged with `-salvagewallet`) but not deleted. It is not possible for `bitcoind.conf` to be corrupted or deleted in a crash as that file is never written by the code at all, just read at start.

**Comment by book89** [comment]
Thanks, so it is likely an inside job from the data center :(

**Comment by gabridome** [comment]
Maybe a stupid consideration but the name of the configuration file has changed from bitcoin.conf to bitcoind.conf. Funny enough I have not found any mention of this in release notes and also in the title @book89 seems to look for the old file name. Just saying...

Nothing to say about wallet.dat.

**Comment by yokesh351** [comment]
Experiencing this same issue on AWS server, any solution? Conf file gets deleted automatically, same happens for me for LTC and BCH sometimes
