### ISSUE TITLE
Assertion failed! hashPrevBlock == view.GetBestBlock()

### ISSUE THREAD

**Issue by stijnsanders** [bitcoin/bitcoin#6196]
I installed bitcoin-qt 0.10.2 on a Windows XP, but started it with a wallet.dat from an older version from a computer that crashed before. It runs, syncing the block chain, but halts after a while with this message:

    ---------------------------
    MinGW Runtime Assertion
    ---------------------------
    Assertion failed!
    
    Program: C:\Program Files\Bitcoin\bitcoin-qt.exe
    File: main.cpp, Line 1660
    
    Expression: hashPrevBlock == view.GetBestBlock()
    ---------------------------
    Abort   Retry   Ignore   
    ---------------------------

**Comment by luke-jr** [comment]
Your blockchain is probably corrupt, and Bitcoin Core only checks it when a peer asks to download the block.

**Comment by luke-jr** [comment]
Actually, disregard that: I was thinking of a different assert.

**Comment by fresheneesz** [comment]
I'm seeing the exact same assertion failure on windows 8.1. I disconnected the drive the database is on while it was downloading for the first time. Oops. The program should have a better way to recover from this.

**Comment by fanquake** [comment]
Are you sure you haven't run out of memory? see #5670 and #6001. 
That was the issue on both occasions.

**Comment by stijnsanders** [comment]
I was running out of space on the harddisk, but have moved the data dir to another drive with ample free space. It worked, then found the block data corrupt, restarted the block sync, and then trows this again at about 28 weeks behind.

**Comment by fresheneesz** [comment]
Definitely not running out of memory over here.

**Comment by laanwj** [comment]
You could try using the option (or in bitcoin.conf) `-dbcache=16`. There are other tips to reduce memory usage of bitcoind here: https://gist.github.com/laanwj/efe29c7661ce9b6620a7

**Comment by stijnsanders** [comment]
I've found out the computer had 'default' power usage settings, so it would suspend after *x* hours of inactivity, but this was invisible to me by connecting to the machine via remote desktop... If the process was getting stalled or killed by this, it may explain why data got corrupt. I expect the system to run smoothly now, so am closing this issue. Thanks for your input.
