### ISSUE TITLE
Run failure client 0.10.2 , after I compile it succeed

### ISSUE THREAD

**Issue by feathercoin2** [bitcoin/bitcoin#6252]
I  have download bitcoin-0.10.2.tar.gz, then I  have compiled client 0.10.2 succee. But I double-click bitcoin-qt.exe , It automatic quit without warning or error message.
I can not start. No window .I need your help ,thank you in advance .

bitcoin\debug.log  no changed, nothing been writed into it.
see https://bitcointalk.org/index.php?topic=1074737.0

**Comment by laanwj** [comment]
Do the pre-built binaries work on your system?

What are you using to build it?

**Comment by feathercoin2** [comment]
Yes. I pre-built all .on mingw 4.9

CPPFLAGS="-I/D/BTC/Dev/miniupnpc \
-I/D/BTC/Dev/boost_1_57_0 \
-I/D/FTC/dev/db-4.8.30.NC/build_unix \
-I/D/BTC/Dev/openssl-1.0.1l/include \
-I/D/BTC/Dev \
-I/D/BTC/Dev/protobuf-2.5.0/src \
-I/D/BTC/Dev/libpng-1.6.12 \
-I/D/BTC/Dev/qrencode-3.4.4 \
-I/D/FTC/dev/ZebraCrossing-master/src/libsrc \
-I/D/BTC/Dev/gmp-6.0.0 \
-DSTATICLIB " \
LDFLAGS="-L/D/BTC/Dev/boost_1_57_0/stage/lib \
-L/D/FTC/dev/db-4.8.30.NC/build_unix \
-L/D/BTC/Dev/openssl-1.0.1l \
-L/D/BTC/Dev/miniupnpc \
-L/D/BTC/Dev/protobuf-2.5.0/src/.libs \
-L/D/BTC/Dev/libpng-1.6.12/.libs \
-L/D/BTC/Dev/qrencode-3.4.4/.libs \
-L/D/BTC/Dev/gmp-6.0.0/.libs \
-L/D/FTC/dev/ZebraCrossing-master/build32/Release " \
BOOST_ROOT=/D/BTC/Dev/boost_1_57_0 \
./configure \
--disable-upnp-default \
--disable-tests \
--with-qt-incdir=/D/BTC/Dev/QT/5.3.1/include \
--with-qt-libdir=/D/BTC/Dev/QT/5.3.1/lib \
--with-qt-bindir=/D/BTC/Dev/QT/5.3.1/bin \
--with-qt-plugindir=/D/BTC/Dev/QT/5.3.1/plugins \
--with-boost-system=mgw49-mt-s-1_57 \
--with-boost-filesystem=mgw49-mt-s-1_57 \
--with-boost-program-options=mgw49-mt-s-1_57 \
--with-boost-thread=mgw49-mt-s-1_57 \
--with-boost-chrono=mgw49-mt-s-1_57 \
--with-protoc-bindir=/D/BTC/Dev/protobuf-2.5.0/src \
--with-boost=/D/BTC/Dev/boost_1_57_0/stage \
--with-boost-libdir=/D/BTC/Dev/boost_1_57_0/stage/lib

make

**Comment by feathercoin2** [comment]
After I  uncompre official bitcoin-0.10.2-win32.zip , I can start bitcoin-qt.exe.  But my bitcoin-qt.exe still can not start .

**Comment by jonasschnelli** [comment]
@feathercoin2: if you still wish help, please post more compile details (log output of make).
If you have a linux setup (VM) available, try to setup gitian (see docs/gitian) and build your sources over gitian. This will give you the possibility of building the binaries (even with modificated sources) the same way as the official binaries are built.
