### ISSUE TITLE
why not update berkeley-db from 4.8.30 to 6.1 ?

### ISSUE THREAD

**Issue by LongShao007** [bitcoin/bitcoin#6253]
bitcoin core use berkeley-db 4.8.30, but the latest version of berkeley-db is 6.1.23, why not update it ?

**Comment by jonasschnelli** [comment]
bdb 4.8.30 is still in use because of backward compatibility. See @luke-jrs comment: https://github.com/bitcoin/bitcoin/issues/3686#issuecomment-74836708

Using BDB as wallet filebackend is maybe not the best idea (as we see above, backward compatibility, integrity, compile-issues, etc.). I hope once I can finish https://github.com/bitcoin/bitcoin/pull/5686 which would introduce a  new custom fileformat that only appends data and uses hashing to harden the integrity.

**Comment by LongShao007** [comment]
well done, I have seen #5686, i am very interesting in it, i will see the code of logdb today.

**Comment by laanwj** [comment]
4.8 was used for backward compatibility reasons. Using a newer versions makes the wallet incompatible with older versions, making downgrade impossible (or at least difficult).

If we break compatibility anyway we want to get rid of berkeleydb. When we do so, having to support only one version for the migration script is a plus.

**Comment by LongShao007** [comment]
@laanwj btcoin core team have any plan to solve this problem ?

**Comment by jonasschnelli** [comment]
@LongShao007: bdb4.8.3 will be required anyway within the next releases to support a migration tool if we would switch to logdb. But if so, one could disable the build of the migration tool and so get rid of the bdb dependency.

However, this first needs a testes and finished version of #5686.

**Comment by LongShao007** [comment]
@jonasschnelli Have you done a migration tool ? using python ? I am debugging your logdb code.

**Comment by jonasschnelli** [comment]
@LongShao007: no. I did not investigate in the migration tool. But it should be c++ to use the same database-libray that is used to produce the current wallet.dat file IMO. Once we where taking about having a `bitcoin-wallet` binary (next to `bitcoin-cli` and `bitcoin-tx`). A user could use this tool `bitcoin-wallet -migrate wallet.dat wallet.logdb`. Other operations could also be possible over the `bitcoi-wallet` tool (zaptx, salvagewallet, upgradewallet).

**Comment by sipa** [comment]
Once the primary wallet format is no longer bdb, the conversion code can be
upgraded to use whatever bdb is available, as they are backwards compatible
for reading. Though there may be problems when replaying log entries if
using it after unclean shutdown.

**Comment by LongShao007** [comment]
@jonasschnelli I have seen your logdb code, and debug it, i think it's very good, do you have any uncompleted work need to do about logdb? why not bitcoin core team merge it ？

**Comment by jonasschnelli** [comment]
@LongShao007: this pr would break compatibility between older wallets. And there is no migration tool yet. My plan is, to create a completely new wallet (core-wallet) which can run in parallel to the existing wallet (https://github.com/jonasschnelli/bitcoin/tree/2015/05/corewallet). This would guarantee a save transition.

**Comment by LongShao007** [comment]
@jonasschnelli I will see the code of core-wallet. I want to know the difference between core-wallet and logdb ? Wallet parallel is mean berkely-db and logdb ?

**Comment by jonasschnelli** [comment]
@LongShao007: the new, parallel runnable wallet should also include other changes, like HD, multi-wallet , mailability-, RBF-handling, and – as already said, should use logdb as file storage.

**Comment by LongShao007** [comment]
@jonasschnelli very good, it seems powerful, i see code first, and then talk about it with you.

**Comment by LongShao007** [comment]
@jonasschnelli I have downloaded corewallet, compile it, and run bitcoin-qt, but report: No wallet has been loaded. 
compile command:
autogen.sh
configure
make
How can i create new wallet ?

**Comment by ShapeShifter499** [comment]
> 4.8 was used for backward compatibility reasons. Using a newer versions makes the wallet incompatible with older versions, making downgrade impossible (or at least difficult).
> 
> If we break compatibility anyway we want to get rid of berkeleydb. When we do so, having to support only one version for the migration script is a plus.

@laanwj 

I'm sorry for replying to such a old issue but I have question.  Does this mean the current version will be not compatible with wallet files made with older versions OR newer wallet files created will not be compatible with older versions?
