### ISSUE TITLE
strange peer in Qt debug console

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#6273]
I had a connection to the peer (using version 0.10.2 Windows x64 official client) in the screenshot and I'm asking myself how that service bits should be interpreted:
![strange-peer](https://cloud.githubusercontent.com/assets/1419649/8127891/931a3c38-10fa-11e5-838a-693c04dab285.png)

They are ``network & unknown[2]`` in english!

Edit: The values are parsed via ``formatServicesStr()`` in guiutil.cpp.

**Comment by laanwj** [comment]
Wait, why are those network flags translated? That makes no sense.

**Comment by laanwj** [comment]
Ok - that's simply NODE_GETUTXO:

    NODE_GETUTXO = (1 << 1),

That wasn't added in 0.10 yet.
