### ISSUE TITLE
Warn users about insane maxconnections. 

### ISSUE THREAD

**Issue by chronicbitcoin** [bitcoin/bitcoin#6289]
There's [some comments](https://www.reddit.com/r/Bitcoin/comments/3a0qnj/the_decline_in_bitcoins_full_nodes/cs88051)  where users make statements about how they set their `maxconnections` to stupid levels (1000+) believing that they will contribute to the network or be safer accepting zero confirmation transactions. Should the client be warning them about how crazy that is, or enforcing some sort of hard cap for the configuration? It seems unlikely that any node is actually able to sustain that number of connections without either becoming unusably slow or running out of file descriptors.

**Comment by laanwj** [comment]
Running out of file descriptors is avoided, see https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L727 . It tries to compensate and print a warning to the log, but if not possible it given an error at startup.

**Comment by chronicbitcoin** [comment]
Fair enough.
