### ISSUE TITLE
get spending transaction hash and input index

### ISSUE THREAD

**Issue by vdidonato** [bitcoin/bitcoin#6295]
Hello, 
I need to navigate the tx-graph forward. Namely: given a txo, if it is spent, I would like to get the spending transaction hash and the input index of such txo. Is there any way to achieve this with bitcoind? I went through the whole documentation without success.

Thanks in advance.

**Comment by sipa** [comment]
Bitcoin Core does not track this, as it is not necessary for its intended purpose (validation transactions) and comes at a cost.

You'll need to build an external database.

I'm going to close this, as I don't think this is something people contributing to Bitcoin Core should be working on. If someone has an actual patch to do so, we can always re-evaluate of course.
