### ISSUE TITLE
RPC doesn't accept scientific notation for amounts

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6297]
Reported by @morcos on IRC.

Since the univalue conversion, JSON no longer accepts e.g. 1e-5 as monetary amount. This is required by the JSON standard.

![Parsing diagram numbers](https://usercontent.irccloud-cdn.com/file/Y2aSQLis/IMG_2694.GIF)

This breaks e.g. the `smartfees.py` test. This needs to be fixed in `AmountFromValue` or `ParseMoney`.

**Comment by jonasschnelli** [comment]
Thanks @morcos for reporting. Will have a look at this soon.

**Comment by laanwj** [comment]
It's a matter of writing our own fixed-point parser that accepts the full JSON number syntax. Not rocket science, but will need a lot of testing, interpreting monetary amounts wrongly would be an extremely serious bug (that's why I hoped the time-tested `ParseMoney` would do... maybe adding eE* isn't that involved, I don't know).

**Comment by MrKrzYch00** [comment]
This makes PHP scripts unable to "talk" with Bitcoin RPC correctly when using values <0.0001BTC.

**Comment by laanwj** [comment]
Working on this now.

**Comment by laanwj** [comment]
Fixed by #6379
