### ISSUE TITLE
wallet de-anonymization

### ISSUE THREAD

**Issue by mrcoins** [bitcoin/bitcoin#6304]
Walletexplorer.com is able de-anonymize any wallets, your personal wallet to big known services. The accuracy is average/good. Elliptic just released a service that does the same but i guess it has very high accuracy.

I may say it is a bug? Individual addresses were not supposed to be linked to any wallet or entity. Privacy was Satoshi's priority.

**Comment by laanwj** [comment]
I am nto sure what that specific site uses, but there are various ways in which wallets reveal themselves directly:
- Sending change back to a known address
- Having the change output at a fixed position, ie first or last.

Bitcoin Core wallets suffers from neither of these, but many other wallets do.

But also more subtle ways:
- The assumption that there is only one change output
- Revealing the change output as it is not a 'round' number
- Address reuse by end-users

Privacy in Bitcoin is an ongoing process.

**Comment by jgarzik** [comment]
See also Confidential Transactions from Blockstream, which hide amounts: https://bitcointalk.org/index.php?topic=1085273.0

**Comment by laanwj** [comment]
Or, CoinJoin which merges people's transaction to make it harder to determine who sent to who. A(though amounts can still give it away, which brings us back to @jgarzik's link.

(There's an issue open to support CoinJoin in Bitcoin Core's wallet, #3226, but no one picked it up yet)

**Comment by chris-belcher** [comment]
These services are a systemic risk to bitcoin. Any currency has to be fungible, bitcoin could not survive a split between 'black-market' coins and 'clean AML' coins. As well as a major part of bitcoin's value proposition being uncensorable financial transactions.

Walletexplorer.com works by using combined inputs as evidence of common ownership. I assume Elliptic is doing something similar. Specifically it can usually tell change addresses by the fact that they're combined again. I have been in contact with the developer Aleš Janda who believes CoinJoin would render his website blind.

I'm working on a CoinJoin implementation called JoinMarket, which is working today and producing mainnet CoinJoin transactions with up to about 14 participants and amounts up to 25btc. https://bitcointalk.org/index.php?topic=919116.msg10096489

**Comment by ABISprotocol** [comment]
It's never been a great mystery that bitcoin is transparent.  To me this has always been something that has needed more priority, although the last time I spent much time attempting to address this in detail, I recall that it seemed (at the time) that [unit testing seemed to be identified as a higher priority](https://bitcoinfoundation.org/forum/index.php?/topic/1024-a-clear-and-present-danger/#entry11507) which is something that came up in discussions of the subject of privacy issues.  Additionally, [funding is there](https://github.com/bitcoin/bitcoin/issues/3226#issuecomment-58226430) but it's not known to me when these funds will be released for a proposal.  The latest privacy proposal I've seen that looks like it would merit funds being released for it, would be @gmaxwell's [Confidential Transactions](https://bitcointalk.org/index.php?topic=1085273.0), I think.

**Comment by ABISprotocol** [comment]
Something else which I had earlier forgot to mention here, which was mentioned in #3226 and which seems important to bring up, is that there are other parties which have already made a claim on the funding source I mentioned in my previous comment.  The [reference to this matter is here](https://lists.dyne.org/lurker/message/20141009.110555.21bae56d.en.html).

**Comment by chris-belcher** [comment]
@ABISprotocol I've also made a claim on the coinjoin bountry for the work on JoinMarket.

**Comment by ABISprotocol** [comment]
@chris-belcher How is this to be resolved?  I suppose all the parties (e.g., all the persons who are co-signers on the multisignature account from which the funds would be disbursed) and also the people mentioned in the e-mail I linked to above, should be contacted in one single e-mail, so that they are contacted together on the matter?

**Comment by MeshCollider** [comment]
Privacy in bitcoin is more of a meta-issue rather than a specific issue with Core, so this doesn't need to remain open here

**Comment by tonio12345** [comment]
Unfortunately, even the most popular blockchain explorers (think of walletexplorer.com, ethplorer.io etc.) cannot give that info, if not for some publicly known addresses such as crypto exchanges.  :-\ Even more advanced blockchain investigation tools such as c-hound.ai do not have public address labeling. In most cases, you need to google it, and then create your own label.
