### ISSUE TITLE
Wanted: Mar12Fork.dat

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6320]
This file is mentioned here https://github.com/bitcoin/bitcoin/blob/master/src/test/checkblock_tests.cpp#L48 . 
We should re-host this file on elsewhere, but I don't have the file and the downloads have been removed from sourceforge (as well as all mirrors).
The other alternative, if it is no longer relevant, would be to remove the `May15` testcase.

**Comment by prestotron** [comment]
I don't have the file, sadly :(

**Comment by NicolasDorier** [comment]
Since I replicate the unit tests of core in NBitcoin, I had the problem, now I'm download on :

http://webbtc.com/block/0000000000000024b58eeb1134432f00497a6a860412996e7a260f47126eed07.bin

**Comment by laanwj** [comment]
@NicolasDorier That seems to work, thanks. I just had to change the read offset in `read_block` to 0 instead of 8.

But I'm going to remove this test, I don't think it is useful anymore.
