### ISSUE TITLE
Minor bug: hardcoded base58 alphabet character

### ISSUE THREAD

**Issue by vinniefalco** [bitcoin/bitcoin#6321]
Sorry for not creating a pull request but this line:
https://github.com/bitcoin/bitcoin/blob/master/src/base58.cpp#L96
should read:
```
str.assign(zeroes, pszBase58[0]);
```

**Comment by luke-jr** [comment]
Looks fine to me...

**Comment by prestotron** [comment]
Looks fine, but it is more efficient.

Funny though because I spotted this and sent a pull request for fixing it about 30 minutes before finding this :P

**Comment by paveljanik** [comment]
Please close this and continue the discussion in the PR #6323.

**Comment by sipa** [comment]
I don't understand how a vector lookup (which requires at least
dereferencing a pointer and reading from memory) can be faster than using a
constant.

I agree with Wladimir though; not for or against, but pointless.

**Comment by paveljanik** [comment]
In this case, the vector is const. It could be interesting to compare the actual output of compilers in both cases... But this is something completely different. This issue is really pointless.

**Comment by vinniefalco** [comment]
If someone were to change the alphabet, the function would no longer produce the correct result. For Bitcoin's purposes, its unlikely that the string would ever change. I did say this was minor.

**Comment by luke-jr** [comment]
@vinniefalco To be extremely blunt: Bitcoin Core does not exist to make Ripple (or anything non-Bitcoin) produce the correct results.
