### ISSUE TITLE
Why the block size can't be adjusted dynamically like the difficulty?

### ISSUE THREAD

**Issue by moldcraft** [bitcoin/bitcoin#6325]
http://www.reddit.com/r/Bitcoin/comments/3atq5g

**Comment by prestotron** [comment]
You technically can. But I highly doubt anybody will merge that if you make a pull request.

Unless we're talking about a fork :P

**Comment by jgarzik** [comment]
* Today, the block size may be adjusted dynamically _down_ from 1MB by any miner.
* There are several proposals to dynamically adjust block size.  Almost all of these require an all-network upgrade ("hard fork").

**Comment by prestotron** [comment]
@jgarzik Are you saying it can't be dynamically changed? Or am I reading that wrong.

I'm pretty sure it is possible. Maybe some hard coding, but I know it has to be possible somehow.

If I am wrong, which I do not believe I am, please address it. I'm still in my learning process currently.

**Comment by jgarzik** [comment]
@prestotron This is not the place to teach you bitcoin :)

Miners may choose any block size -- within the limit of 1MB.  It cannot be adjusted dynamically beyond that.

**Comment by prestotron** [comment]
@jgarzik I know, I didn't ask for you to teach me. I just mean, if I say something incorrect, please address it.

But I was sort of correct, I know you couldn't go passed the 1MB limit, but it is still kinda dynamic.

Thanks anyways :)
