### ISSUE TITLE
Allow sendrawtransaction validation override

### ISSUE THREAD

**Issue by aakilfernandes** [bitcoin/bitcoin#6326]
I'm working on a project that uses 3rd party APIs to reference blockchain data, so the user doesn't have to download the entire blockchain to their client. However I'd like to have them broadcast transactions via bitcoind. Unfortunately, bitcoind will refuse to broadcast transactions it can't personally validate.

It would be nice to have a way to override these internal checks.

**Comment by essofluffy** [comment]
Why would you rather broadcast with Bitcoind as opposed to using a third party API for the transactions as well?

**Comment by jonasschnelli** [comment]
I think this is related to https://github.com/bitcoin/bitcoin/pull/6240. But i have to say the patch is more a ugly hack. Is there a use case for broadcasting transaction that are not valid for broadcasting? If you have one, you probably should go by patching/changing your local bitcoin-core source.

**Comment by paveljanik** [comment]
@jonasschnelli It is only useful if you want to test other nodes banning you...

**Comment by aakilfernandes** [comment]
@jonasschnelli the transactions are valid, they just cant be validated by the node you're sending it from without downloading the entire blockchain.

@essofluffy (ps fancy seeing you here!) there are plenty of 3rd party apis that allow you to grab blockchain data. There's relatively few that allow you to broadcast raw data through their node (especially without an API key).

**Comment by sipa** [comment]
Bitcoin Core is really not intended to be used without synchronization. There are several other projects out there to implement just the P2P protocol, which is enough to broadcast a transaction, though it also means you won't be able to know whether they're valid.

**Comment by jonasschnelli** [comment]
Agree with @sipa: unless there is a SPV mode, broadcasting a transaction with a full node implementation should always validate before sending.
You could modify bitcoin core to fit your use case. But this should not bother the mainline here on github.

**Comment by aakilfernandes** [comment]
Fair enough. @sipa can you point me towards some of those projects?

**Comment by jonasschnelli** [comment]
@aakilfernandes what about @laanwj tool: https://github.com/laanwj/bitcoin-submittx

**Comment by prestotron** [comment]
I think @sipa, and @jonasschnelli explained it very well.

**Comment by essofluffy** [comment]
Haha I was surprised to see you here. I think sipa and jonasschnelli gave you what you need so I just look forward to what you've made. I'd be happy to check anything out for you.

**Comment by prestotron** [comment]
Seems like everyone is on board with @sipa and @jonasschnelli haha.
