### ISSUE TITLE
Add P2P Pool donation address to reference client

### ISSUE THREAD

**Issue by pennyfx** [bitcoin/bitcoin#6330]
What if, right along side miner fees, there was a way to donate to P2P Pool to encourage more nodes and decentralized mining?  

This donation would always be paid to P2P Pool no matter which pool won the block.  Maybe these fees can be held in a multsig address and release to P2P Pool once they win and the donations are distributed the same way the reward is distributed today.   Who would control this address?   Bitcoin Foundation?  MIT? 

The donation amount could be a percentage or fixed amount.

This sort of functionality could be expanded further to include charities, non-profits, and other causes you wish to support.

**Comment by luke-jr** [comment]
NACK, shouldn't endorse a single specific pool. Charities can post Bitcoin URIs on their websites like anyone else.

**Comment by jonasschnelli** [comment]
Related to https://github.com/bitcoin/bitcoin/issues/5783 and already discussed there.

**Comment by pennyfx** [comment]
I thought that P2P Pool is a neutral pool that we always wanted more miners to use.  Setting up a charity field in the reference client would help the idea propagate to other wallets.   

If we want certain behavior,  we need incentives.  Just like fees and block rewards.

**Comment by wtogami** [comment]
P2Pool is a neutral pool, but there is no technical reason to hard code a donation address in the reference client.

Please close.
