### ISSUE TITLE
Segmentation fault on bitcoind or bitcoin-qt startup (64bit Linux)

### ISSUE THREAD

**Issue by primezeta** [bitcoin/bitcoin#6332]
I cannot start the application due to a segmentation fault on 64 bit Linux (Ubuntu 14.04). This applies to both bitcoind or bitcoin-qt. For reference, 'uname -a' outputs '3.16.0-41-generic'.

The issue happens with the current binary download of bitcoin core from bitcoin.org and from my own compiled version, in which --enable-hardened was the only ./configure flag I used. Using the compiled version I collected the following backtraces from bitcoind and bitcoin-qt.

Here are the gdb bt results following the seg fault for bitcoind:
#0  CBlockIndex::GetAncestor (this=<optimized out>, height=29985) at chain.cpp:85
#1  0x00005555556b5864 in CBlockIndex::BuildSkip (this=this@entry=0x555556b5d980) at chain.cpp:108
#2  0x00005555555ddeb2 in LoadBlockIndexDB () at main.cpp:3190
#3  0x00005555555deb05 in LoadBlockIndex () at main.cpp:3381
#4  0x00005555555a9955 in AppInit2 (threadGroup=..., scheduler=...) at init.cpp:1142
#5  0x000055555558f07d in AppInit (argc=<optimized out>, argv=<optimized out>) at bitcoind.cpp:147
#6  0x000055555558667f in main (argc=1, argv=0x7fffffffe068) at bitcoind.cpp:176

And here are the gdb bt results following the seg fault for bitcoin-qt
#0  CBlockIndex::GetAncestor (this=<optimized out>, height=29985) at chain.cpp:85
#1  0x00005555557b4064 in CBlockIndex::BuildSkip (this=this@entry=0x7fffc50857b0) at chain.cpp:108
#2  0x00005555556e96c2 in LoadBlockIndexDB () at main.cpp:3190
#3  0x00005555556ea315 in LoadBlockIndex () at main.cpp:3381
#4  0x00005555556bf235 in AppInit2 (threadGroup=..., scheduler=...) at init.cpp:1142
#5  0x00005555555c8fa7 in BitcoinCore::initialize (this=0x5555567c2390) at qt/bitcoin.cpp:263
#6  0x00005555555c93f8 in BitcoinCore::qt_static_metacall (_o=0x5555567c2390, _id=<optimized out>, _a=0x5555567c2af0, _c=<optimized out>) at qt/bitcoin.moc:58
#7  0x00007ffff5d6fc1e in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff684be2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007ffff68524a0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007ffff5d574dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#11 0x00007ffff5d5ab3d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007ffff5d84f83 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff31cae04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff31cb048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff31cb0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff5d847a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#17 0x00007ffff5d560af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007ffff5d563a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#19 0x00007ffff5c52c5f in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007ffff5c5532f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff54b6182 in start_thread (arg=0x7fffd5fef700) at pthread_create.c:312
#22 0x00007ffff3be047d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

For bitcoind, the seg fault occurs right after this output explaining the RPC password:
If the file does not exist, create it with owner-readable-only file permissions.
It is also recommended to set alertnotify so you are notified of problems;
for example: alertnotify=echo %s | mail -s "Bitcoin Alert" admin@foo.com

**Comment by laanwj** [comment]
Which version?

Does the segfault still happen if you set a RPC password?

**Comment by primezeta** [comment]
It was from the head revision from around the time of my post. Unfortunately I can't find the hash of that revision, but I just cloned the latest and the resulting binary does not have a segmentation fault.
