### ISSUE TITLE
Update doc/bips.md for 0.11

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#6340]

**Comment by laanwj** [comment]
Can you be more specific? What needs to be added?

**Comment by luke-jr** [comment]
At least the first line (saying what version it is updated to) needs to be bumped. I can't think of any BIPs to add to the list.

**Comment by sipa** [comment]
Should also be added to the release process documentation, I guess.

**Comment by daryltucker** [comment]
Is this why `bitcoin-cli getinfo` still returns `"version" : 100000,`?

**Comment by fanquake** [comment]
Can be closed now that #6652 has been merged

**Comment by ongygy2000** [comment]
yes 


     On Saturday, September 26, 2015 7:55 AM, Michael <notifications@github.com> wrote:
   

 Can be closed now that #6652 has been merged—

**Comment by MarcoFalke** [comment]
@sipa mentioned "add[ing] to the release process documentation". Is this done?
