### ISSUE TITLE
error

### ISSUE THREAD

**Issue by drunkwolfs** [bitcoin/bitcoin#6348]
My hard drive was accidentally disabled.
I restarted bitcoind:
```bash
# kill -9 pid
# bitcoind -daemon
```

I waited 5 minutes.
```bash
# bitcoin-cli getinfo
error: {"code":-28,"message":"Activating best chain..."}
```
I kill bitcoind and deleted the last downloaded block /bitcoins/block/blk00261.dat and /bitcoins/block/rev00261.dat
I launched the client
```bash
# bitcoind -reindex -rescan -daemon
bitcoind: main.cpp:2834: bool AcceptBlockHeader(const CBlockHeader&, CValidationState&, CBlockIndex**): Assertion `pindexPrev' failed.
```

please help me

**Comment by D9B4BEF9** [comment]
If you want your node to operate correctly, don't delete files it depends on and don't ever SIGKILL it. 

    bitcoind -reindex

This will download and rebuild the database from scratch.

**Comment by drunkwolfs** [comment]
bitcoind -reindex
bitcoind: main.cpp:2834: bool AcceptBlockHeader(const CBlockHeader&, CValidationState&, CBlockIndex**): Assertion `pindexPrev' failed.

**Comment by drunkwolfs** [comment]
>If you want your node to operate correctly, don't delete files it depends on and don't ever SIGKILL it.
Если вам интересны причины то переводите это сами.
У меня отключился жесткий диск, биткоин завис, черезcli был не доступен хотя висел в процессах. Пришлось его убить.
Ошбика error: {"code":-28,"message":"Activating best chain..."} не проходила, остановить снова не получалось, пришлось убивать.
Мне не нужны ваши советы как работать с биткоином, мне нужно исправление этого бага.

**Comment by laanwj** [comment]
What version? On master, reindex was broken until shortly.

**Comment by drunkwolfs** [comment]
"version": 119900, pre-release test build
I had to delete all files from blocks & chainstate.
Now works, but download blocks again.

**Comment by laanwj** [comment]
That's indeed the master branch. Probably, updating to a newer commit would have solved your reindexing problem too.
