### ISSUE TITLE
Ability to 'disable' an address

### ISSUE THREAD

**Issue by chriswheeler** [bitcoin/bitcoin#6360]
This is just an idea - if this isn't the right place for it let me know :)

We've seen cases (e.g. bitstamp) where a hot wallet has been compromised by an attacher, and the attack has been much more effective because the address continues to have coins sent to it even once it is known to be compromised.

With the alert system it is possible for someone to sign a special message with their private key to make it known that their key has been compromised. Could a similar function be implemented for addresses?

It could work something like this:

- A company creates an address and their customers send regular payments to this account
- Hacker gets access to the private key for this address, and withdraws coins
- The company notices, and alerts customers not to use this address 
- The company signs a 'compromised' transaction using their private key
- Any new transactions which spend to Address X are rejected

Existing coins would still be able to be transferred out of the compromised address.

**Comment by fanquake** [comment]
Similar discussion in #6175

**Comment by chriswheeler** [comment]
Thanks, I've read through that and it has some great comments, I guess this isn't the right place for high level ideas too, sorry about that. I'll put some more through into it and close this issue.
