### ISSUE TITLE
Upgrading bitcoin core version after a fork does not validate previous blocks

### ISSUE THREAD

**Issue by Gabrola** [bitcoin/bitcoin#6376]
I was running bitcoin core version 0.9 which accepted an invalid chain not adhering to the BIP66 protocol changes. This prompted me to upgrade immediately, however the new version is taking the already accepted blocks as already verified.

I suggest some kind of check to be made on the first run of the new version which checks if the version that was last used was one that did not adhere to some protocol changes, it would revalidate the last x-blocks on the disk.

Not a major issue, but could cause some minor problems in later forks.

**Comment by laanwj** [comment]
You can do the following:
- RPC `invalidateblock` with the first invalid block
- RPC `invalidateblock` then `reconsiderblock` of the last valid block (or one before there), this will cause the blocks after that to be rechecked

**Comment by Gabrola** [comment]
I'm aware of being able to do this manually. My proposal is to automatically run something similar to `verifychain` on the first-run of a new version following a fork.

**Comment by laanwj** [comment]
Right - there's obviously a limit to automatically detecting forks which are already behind you, but maybe functionality like that could be added to the startup checkblocks check, which already descends a certain depth into the chain.

**Comment by Sjors** [comment]
This was handled better with SegWit IIRC, @sdaftuar?

**Comment by sdaftuar** [comment]
Yes I think we can close this issue now.  A comment memorializing this concern was added in https://github.com/bitcoin/bitcoin/pull/11737.
