### ISSUE TITLE
CScript() << OP_RETURN << data produces up to 82 bytes

### ISSUE THREAD

**Issue by haraldh** [bitcoin/bitcoin#6392]
https://github.com/bitcoin/bitcoin/blob/master/src/test/transaction_tests.cpp#L354

produces:
6a4c5004678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef3804678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38

which is OP_RETURN + OP_PUSHDATA1 + LEN + DATA

so effectively OP_RETURN + 82 bytes

This passes IsStandardTx(), but a OP_RETURN + 80 random chars does not.

**Comment by haraldh** [comment]
Maybe I miss some documentation, but most resources are outdated.

**Comment by luke-jr** [comment]
Scripts aren't random data. Without a push-data opcode, your "random chars" will be interpreted as opcodes, and count against miners' sigop limits.

**Comment by haraldh** [comment]
Maybe someone should change some wiki pages explaining, that OP_RETURN is only allowed to be followed by standard PUSHDATA.

**Comment by luke-jr** [comment]
Sounds like a good idea. Go for it.
