### ISSUE TITLE
Potential nullptr dereference in getblockchaininfo

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#6393]
`getblockchaininfo` has the following code:

```
        CBlockIndex *block = chainActive.Tip();
        while (block && block->pprev && (block->pprev->nStatus & BLOCK_HAVE_DATA))
            block = block->pprev;

        obj.push_back(Pair("pruneheight",        block->nHeight));
```

This code assumes that `block` can be null. After the loop `block` can still be null if `block` was initially null or if `block->pprev` was null.

Then, `block->nHeight` leads to a null pointer dereference which is UB.

**Comment by jonasschnelli** [comment]
IMO block->prev can't be NULL because we do && block->prev in the while condition.

I'm not sure if a chainActive.Tip() can ever be NULL but I also would say it requires a if(block) before accessing nHeight.

**Comment by GSPP** [comment]
True.

**Comment by sipa** [comment]
chainActive.Tip() can only be NULL when you're reindexing, and haven't processed the on-disk genesis block.

**Comment by GSPP** [comment]
OK, I understand. Maybe this should be a runtime assertion. Even the slightest potential for Undefined Behavior in a Bitcoin software is reason for concern.

**Comment by laanwj** [comment]
It's set up such that the control flow will never leave AppInit2 without a genesis block set. So it is in practice impossible to hit this.
Feel free to add an assertion if that makes you feel better, though.
