### ISSUE TITLE
Race condition in CScheduler::serviceQueue

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#6394]
`CScheduler::serviceQueue` has the following code:

```
+            lock.unlock();
+            f();
+            lock.lock();
+        } catch (...) {
+            --nThreadsServicingQueue;
+            throw;
+        }
```

In case `f` throws the statement `--nThreadsServicingQueue;` will run while not protected by the lock. This is a race condition and UB.

**Comment by laanwj** [comment]
Good catch. The code in general doesn't look very exception-safe, though. E.g. if f() throws, the lock will never be released.
