### ISSUE TITLE
broadcasted transactions are not getting confirmed and doublespend both occurring and bugging my addresses.. 11 bitcoins stuck need some help

### ISSUE THREAD

**Issue by tarzanious** [bitcoin/bitcoin#6399]
My address https://blockchain.info/address/1CHEEZe2w7u4hsT25KuJsj2mdXhd6QrLtU has been bugged for approximately the past 16 hours.. it all started when I tried to send 0.00006848 btc to an HD wallet of mine last night that would never get confirmations. the transaction broadcasted from my mycelium wallet and was recognized by my ledger wallet, but it was never recognized on the blockchain.. 

so I then tried to remedy this by sending bitcoins to the address and to try and send more coins overall as an output, but from new inputs.. i was essentially able to doublespend on the 0.00006848 btc originally sent by using blockchain.com as the wallet for the private key.. but effectively bugging other addresses involved, most currently https://blockchain.info/tx/66de49feba2cdafcb3fdd8a25eec6b4969efb5e381e8254c50496672b8a864b6 this transaction has been stuck for a number of hours now.. 

but the worst part of all this, for me, is that my ledger wallet is now bugged as well. i keep all my bitcoins there and its truly screwing me up that i cannot move or access these bitcoins.. i hope someone can help

**Comment by TheBlueMatt** [comment]
This is not a support forum for mycelium or ledger. You should contact them for help. Still, looks like your transactions confirmed.
