### ISSUE TITLE
Annual purge of testnet blockchain.

### ISSUE THREAD

**Issue by embiimob** [bitcoin/bitcoin#6404]
Purging the testnet blockchain's annually makes them viable temp data stores for non permanent data.  This will also lead to less bloating and spamming of the production blockchain as only truly permanent data will be placed there.

**Comment by luke-jr** [comment]
Sounds like a reason not to do it. Blockchains are not data storage at all.

**Comment by embiimob** [comment]
A blockchain **is** data storage.
The miners need something to do in 2140.

**Comment by sipa** [comment]
You can wipe old data by enabling pruning.

You can fully reset the chain and its resource requirements by creating a new testnet chain.

Both are easy to do.
