### ISSUE TITLE
connection limit calculation for select() is overly ambitious with -txindex

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#6411]
Running an unmodified 0.10.2 node I got this fail, seeming to indicate that it was trying to add an fd which was higher than the max for select. Node has -txindex and usually has a ton of connections (it has the max fd count set higher than default st. its maxconnections is limited by its select limits, not by max fd count limits).

Core was generated by `/home/matt/bitcoind'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f327f0c0528 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f327f0c0528 in raise () from /usr/lib/libc.so.6
#1  0x00007f327f0c193a in abort () from /usr/lib/libc.so.6
#2  0x00007f327f0febb2 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f327f184ff7 in __fortify_fail () from /usr/lib/libc.so.6
#4  0x00007f327f1831c0 in __chk_fail () from /usr/lib/libc.so.6
#5  0x00007f327f184f67 in __fdelt_warn () from /usr/lib/libc.so.6
#6  0x00007f328199fa5e in ThreadSocketHandler () at net.cpp:820
#7  0x00007f32819a7c11 in TraceThread<void (*)()> (name=0x7f3281b857a1 "net", func=0x7f328199eff0 <ThreadSocketHandler()>) at util.h:214
#8  0x00007f3280ddfa85 in ?? () from /usr/lib/libboost_thread.so.1.58.0
#9  0x00007f327f436354 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f327f174bfd in clone () from /usr/lib/libc.so.6
(gdb)

**Comment by TheBlueMatt** [comment]
Solution is probably to switch to libevent or something else which means we dont have to call select directly.

**Comment by theuni** [comment]
@TheBlueMatt That's something I'm working on at the moment.

**Comment by sipa** [comment]
See #6412 for a rough fix.
