### ISSUE TITLE
std::getline() in rpcprotocol.cpp should be replaced by an alternative with a length limit 

### ISSUE THREAD

**Issue by SergioDemianLerner** [bitcoin/bitcoin#6425]
By using the unbounded getline() RPC/REST clients are able to (slowly) fill server heap address space until core dump.
Also limiting line length protects attacks on further processing on the URI by REST methods.
The HTTP/1.1 standard seems to limit it to 8000 bytes, although any number < 32 Mb could be used in bitcoind.
See http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by lontivero** [comment]
8kb limit has been chosen as a de-facto limit by many web servers (and web clients too) but it is standard. Having said this, you are right and even more important for the unathenticated rest client.

**Comment by jonasschnelli** [comment]
Agreed with @SergioDemianLerner.
I would say it's not worth touching/re-checking this until https://github.com/bitcoin/bitcoin/pull/5677/files is merged.

**Comment by laanwj** [comment]
evhttp allows setting the maximum size of method+URI+headers with `evhttp_connection_set_max_headers_size`, we should definitely use that after #5677.
