### ISSUE TITLE
Missed icon in notification area

### ISSUE THREAD

**Issue by annaparker** [bitcoin/bitcoin#6426]
I'm not affected by this [potential - not checked by me] issue, but one guy said he lost icon in notification area on his Ubuntu Mate:

https://www.reddit.com/r/Bitcoin/comments/3d0uhg/bitcoin_core_version_0110_released/ct0rw8p

Bitcoin Core version 0.11.0, Linux

**Comment by laanwj** [comment]
Thanks for reporting here.
I *think* this is the same issue as reported here: Static Qt5 in Linux builds #6267

**Comment by tuxmaster** [comment]
Same for F21.
See picture.
The red arrow area is the icon .:(
![bildschirmfoto von 2015-07-13 09 55 39](https://cloud.githubusercontent.com/assets/6240474/8645204/8e45cbc4-2945-11e5-88b5-a25cc031727b.png)

**Comment by moldcraft** [comment]
Ubuntu 15.04

![s](https://static.md/83f3a9e7123917836af30eb4685ebab3.png)

**Comment by laanwj** [comment]
For Ubuntu, the PPA version (https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin — expected to be available tomorrow) will likely not have this problem.

**Comment by jonasschnelli** [comment]
Issue confirmed.
It is a Qt5.2 upstream issue (related to https://bugreports.qt.io/browse/QTBUG-31762?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel).
Version 0.10.2 as well as 0.11.0 and the current master are affected.
**Building against Qt5.4.2 does solves the problem**. Just tested on Ubuntu 15.04.

Ubuntu 15.04 / `libqt5gui5 5.4.1+dfsg-2ubuntu4`
Bitcoin-Qt 0.10.2:
<img width="1358" alt="bildschirmfoto 2015-07-13 um 13 13 33" src="https://cloud.githubusercontent.com/assets/178464/8648750/99acb45a-2963-11e5-886e-662ff9178d0c.png">

Bitcoin-Qt – current master:
<img width="1467" alt="bildschirmfoto 2015-07-13 um 13 29 59" src="https://cloud.githubusercontent.com/assets/178464/8648760/a534576a-2963-11e5-9678-baca53e540ac.png">

**Comment by laanwj** [comment]
> Building against Qt5.4.2 does solves the problem. Just tested on Ubuntu 15.04.

But did you test with a gitian (or depends) build, or did you build against Ubuntu's Qt? In the latter case you won't see the issue at all. This only happens for static builds.

**Comment by theuni** [comment]
I can confirm that the tray icon was working with my brief tests with static 5.4/5.5 builds from #6314.

**Comment by moldcraft** [comment]
https://github.com/bitcoin/bitcoin/issues/6426#issuecomment-120847417
[Ubuntu PPA](https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin) version 0.11 works fine

![](http://static.md/e2c8de533e8f8d6ac8a65686b4344382.png)
![](http://static.md/cbd66d67547cf142288d8f4700798841.png)

**Comment by laanwj** [comment]
Qt 5 has been bumped, fixed in next 0.11 release
