### ISSUE TITLE
Core dumped when running with -prune=N option

### ISSUE THREAD

**Issue by maraoz** [bitcoin/bitcoin#6436]
I couldn't reproduce this again, but I'll post it in case it helps. Feel free to close the issue if not useful.

I just installed v0.11.0 and ran it with the following config:
```
rpcuser=user
rpcpassword=pass

server=1
txindex=1
```
I then wanted to test the new `-prune=N` option, so I ran:
```sh
$ ./bitcoin-qt -testnet -prune=2048
```
I got a UI error saying `-txindex` is incompatible with `-prune`, so I went and deleted the `txindex=1` line from my config. When I ran it again I got:

```sh
$ ./bitcoin-qt -testnet -prune=2048
Auto configuration failed
139732253796224:error:02001002:system library:fopen:No such file or directory:bss_file.c:169:fopen('/home/ubuntu/build/bitcoin/depends/x86_64-unknown-linux-gnu/etc/openssl/openssl.cnf','rb')
139732253796224:error:2006D002:BIO routines:BIO_new_file:system lib:bss_file.c:174:
139732253796224:error:0E078002:configuration file routines:DEF_LOAD:system lib:conf_def.c:199:
bitcoin-qt: /home/ubuntu/build/bitcoin/depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/recursive_mutex.hpp:110: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Aborted (core dumped)
```
Here's my debug.log file for today: http://pastebin.com/n90GTrmY (filtered with `cat 2015-07-14-debug.log | grep -v 'UpdateTip'`)
When I ran it again, it worked. I wasn't able to reproduce this behavior again. Any other info I can provide?

**Comment by jonasschnelli** [comment]
This has probably nothing todo with pruning. It seams a openssl config issue (https://github.com/bitcoin/bitcoin/pull/6438).

@maraoz: mind testing this issue with https://github.com/bitcoin/bitcoin/pull/6438?

Upgrading openssl to 1.0.1+ would also cure the issue.
