### ISSUE TITLE
Recommended Transaction Fee Slider: non-monotonic behavior

### ISSUE THREAD

**Issue by tl121** [bitcoin/bitcoin#6437]
Bitcoin Core version v0.11.0 (64-bit)  on Windows 7.

The recommended button in the Transaction Fee section of the Send window was selected.  Moving the slider from left to right slowly, the recommended transaction fee increases as slider is moved to the right, up to about 95% of the slider action.  The transaction fee increases to .0.00015101 BTC, estimated time of 2 blocks. This is as expected.

Moving the slider all the way to the right reduces the recommended fee to 0.0001 with the message: "Smart fee not initialized yet. This usually takes a few blocks". This was not expected. The changing estimate is confusing, but this is cosmetic.  However, having the recommended fees decrease when moving the slider to the right is incorrect.  The relationship should be monotonic.The user should not experience worse performance as a result of requesting higher performance, as would happen when the fees revert to the default.

**Comment by morcos** [comment]
Yes I agree entirely.  #6134 was created to address this, although it's probably not the best implementation.    Perhaps someone with a bit more QT experience should tackle it.

**Comment by MeshCollider** [comment]
The fee slider was removed in #10769 so this is irrelevant now
