### ISSUE TITLE
Compile error on OSX

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#6441]
The symptom:
```
In file included from primitives/transaction.cpp:6:
In file included from ./primitives/transaction.h:10:
./memusage.h:14:10: fatal error: 'boost/foreach.hpp' file not found
#include <boost/foreach.hpp>
         ^
1 error generated.
```

Cause is transaction.h including memusage.h, which includes boost headers... but libbitcoinconsensus is supposed to be boost-free.

@sipa will be working on a fix.

@theuni : it'd be nice if one of the Travis builds had a pristine build environment for libbitcoinconsensus to make sure no extra dependencies crept in.

**Comment by theuni** [comment]
Yes, I'll work on a type of namespacing that will prevent this.
