### ISSUE TITLE
ParseDouble() is faulty, depending on locale

### ISSUE THREAD

**Issue by dexX7** [bitcoin/bitcoin#6443]
I tested the current master, and when I used the QT client, then a lot of RPC calls returned errors with "JSON double out of range". This wasn't the case, when using bitcoind however, at least for me.

It turns out this seems to be another locale related issue: https://github.com/bitcoin/bitcoin/commit/7e98a3c642222edc0813ced945d4b6e548cb8ca8 added [ParseDouble()](https://github.com/bitcoin/bitcoin/blob/7e98a3c642222edc0813ced945d4b6e548cb8ca8/src/utilstrencodings.cpp#L461), which uses `strtod`.

`strtod` is locale dependent, and with a locale, where the decial point isn't `.`, the resulting numbers are unexpected, and `ParseDouble()` fails, due to it's check, whether there are [trailing characters](https://github.com/bitcoin/bitcoin/blob/7e98a3c642222edc0813ced945d4b6e548cb8ca8/src/utilstrencodings.cpp#L471) left.

When using QT, then it looks like `LC_NUMERIC` (and friends) are based on the user's locale, while bitcoind appears to use the `"C"` locale for all `LC_xxxx`.

The configuration option `"-lang"` seems to have no effect here.

**Comment by laanwj** [comment]
Can you try replacing in UniValue::write
```
    case VREAL:
        {
            std::stringstream ss;
            ss << std::showpoint << std::fixed << std::setprecision(8) << get_real();
            s += ss.str();
        }
        break;
    case VNUM:
        s += val;
        break;
```
with
```
    case VREAL:
    case VNUM:
        s += val;
        break;
```
There is no need to parse and re-format the value via a double when outputting...

`get_real` is only used in one place apart from that, prioritisetransaction, so if this is a problem with ParseDouble this should avoid your issue.

**Comment by dexX7** [comment]
> Can you try replacing in UniValue::write ...

It looks like the numbers are parsed and re-formatted to normalize the values to `%d.%8d`:
```java
{
  "version": 119900,
  "protocolversion": 70002,
  "walletversion": 60000,
  "balance": 11.56061, // <-- would be 11.56061000
  "blocks": 1046,
  "timeoffset": 0,
  "connections": 0,
  "proxy": "",
  "difficulty": 4.656542373906925e-10, // <-- would be 0.00000000
  "testnet": false,
  "keypoololdest": 1436225389,
  "keypoolsize": 101,
  "paytxfee": 0.0001, // <-- would be 0.00010000
  "relayfee": 0.00001, // <-- would be 0.00001000
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}
```

> get_real is only used in one place apart from that, prioritisetransaction, so if this is a problem with ParseDouble this should avoid your issue.

Just to quickly clarify with an example: I didn't mess with my locale settings, but I live in Europe, and as per system default, `,` is used as decimal point:
```c++
double n;
bool success = ParseDouble("1.2345", &n);

// => n == 1.0
// => success == false
```
The unit tests pass, because it seems that only the QT client is affected. The [QT documenation](http://doc.qt.io/qt-5/qcoreapplication.html#locale-settings) actually addresses this pitfall and suggests to reset `LC_NUMERIC`, once the application is initialized. This works, though I think it would probably best to avoid the use of locale-dependent functions altogether, or reset the numeric locale directly in `ParseDouble()`, if `strtod` should be kept.

**Comment by laanwj** [comment]
> It looks like the numbers are parsed and re-formatted to normalize the values to %d.%8d:

If that kind of formatting is desired for non-monetary values, this can also be done in `setFloat` directly. My point was not that the above is a good fix, but it works around the issue to isolate the problem.
Does it stop the issue from happening in qt if you do that?

**Comment by laanwj** [comment]
Working on a fix...

**Comment by laanwj** [comment]
See #6456
