### ISSUE TITLE
Enourage pruning for first time desktop users

### ISSUE THREAD

**Issue by sime** [bitcoin/bitcoin#6460]
With a pruned wallet possible in master I believe we should encourage desktop/GUI users to use pruning. Decreasing the initial barrier to entry to using Bitcoin.

On first load, the user will be presented with two options:
1. Basic: 1.5G disk space
2. Advanced: Full node. Minimum 50G disk space
<img width="480" alt="first_run" src="https://cloud.githubusercontent.com/assets/216917/8766145/6e94cb22-2e2c-11e5-9bcd-be66ad6e8d87.png">

If the first option is chosen, set pruning to 550MB: `prune=550`.

Since the user has the ability decide what type of node they wish to run, they should have the ability change their mind later. The Main tab in preferences will offer a chance to toggle the node type and size.
<img width="612" alt="pruning_gui_off" src="https://cloud.githubusercontent.com/assets/216917/8766147/834fb842-2e2c-11e5-94b0-c342132243bf.png">
<img width="612" alt="pruning_gui_on" src="https://cloud.githubusercontent.com/assets/216917/8766148/8351a0c6-2e2c-11e5-841b-af02fd77ff44.png">

The prune size UI should not permit sizes less than 550.

PS I have a layered GIMP file if someone would like to refine the UI.

**Comment by JustinDrake** [comment]
+1 for pruning as the default for new users.

**Comment by 2083236893** [comment]
"Quick start"? If anything `prune` takes slightly longer than not.

**Comment by sime** [comment]
I haven't benchmarked pruning, but it was my assumption that it would be quicker than syncing the whole blockchain.

Possible then the Advanced button could be relabeled describe an avenue for restoring an old wallet?

**Comment by jonasschnelli** [comment]
@sime: It is not quicker (maybe a little bit because you don't relay blocks). It only reduces the required diskspace. I like the mockups but i'm unsure if we should encourage users to prune by default. At the moment – especially without relay option (#6148, which somehow requires better service-bit handling) – pruning node don't really proactive participate in the distribution of the blockchain.

**Comment by luke-jr** [comment]
If anything, the question should be "Contribute" or "Leech". Definitely not Leech by default...

**Comment by sime** [comment]
Running bitcoind on my small disk VPS for the first time and assumed the resource hogging was normal. But it settled a few hours ago and now I realise an empty pruned node talks a long time.

I see now that pruning doesn't introduce any notion of a quick start.

**Comment by jonasschnelli** [comment]
Mind that pruning still downloads and verifies the whole blockchain. Pruning will only deleted blocks and undos above (=older) the given threshold (prune target in MB).

**Comment by laanwj** [comment]
Not against exposing this in the UI, but I disagree it's quite time to encourage it yet.  The feature, especially in combination with the wallet, is experimental.

> I haven't benchmarked pruning, but it was my assumption that it would be quicker than syncing the whole blockchain.

No, it's not any faster. It just conserves disk space, and upload bandwidth by not serving archived blocks.

**Comment by sime** [comment]
I'll close this and make a new issue suggesting exposing the prune option.

**Comment by laanwj** [comment]
You can also just edit this issue :)

**Comment by sime** [comment]
Replaced by #6461
