### ISSUE TITLE
CI run on big-endian platform

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6466]
Let's add a travis build/test run (testing could be done using qemu-user) on a big endian platform to avoid breaking without us noticing.
(I'd suggest MIPS as we already have an ARM platform run, for most diverse testing)

**Comment by sipa** [comment]
ACK.

**Comment by jonasschnelli** [comment]
Concept ACK. I think focusing BE on CI is important if we won't keep it maintained. The only thing i fear a tiny bit is the required time to fully compile on a qemu BE system (or would it cross compile and only run the tests over qemu)?

**Comment by sipa** [comment]
Yes, cross compile + run on BE emulator.

**Comment by theuni** [comment]
ACK. This will take some flips and twists, but should be do-able. Adding it to my list.

**Comment by laanwj** [comment]
@jonasschnelli Cross-compiling to BE is easy. We could start with just that. Although I expect most issues to be found while running.
Even if just a
```
qemu-mips src/test/test_bitcoin
```
(did this locally while developing)
One step further would be to run the Python QA tests  - these don't have to run in BE themselves - just the bitcoinds that they launch.

**Comment by jeking3** [comment]
This is something that I recently added as an option to the Boost CI framework that some libraries in the boost project use:

1. Build a multiarch Dockerfile, for example https://github.com/jeking3/bdde/blob/master/Dockerfile.red-ppc64

2. Modify the Travis CI build job to include needed bits (basically, add qemu-user-static package and docker service): https://github.com/boostorg/boost-ci/commit/ceb7055bde4337fa5434a3fb4575b1cced07d312#diff-1b73ee3d35c55099866134b4ab3115eaR49

3. Invoke your build command with docker:  https://github.com/jeking3/bdde/blob/master/bin/linux/bdde#L24

This allowed me to run boostorg/uuid in big-endian, track down and fix an issue.  Build time is at least 10x slower than normal however...

**Comment by MarcoFalke** [comment]
This should be easy to solve, in the same fashion as #17089.

I checked that Bionic has the package available:

```
$ qemu-mips --version
qemu-mips version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.19)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

**Comment by laanwj** [comment]
:tada: :tada: :tada:
