### ISSUE TITLE
Raise and regulate max block size like difficulty 

### ISSUE THREAD

**Issue by Rav3nPL** [bitcoin/bitcoin#6467]
Because there is no consensus how and how much raise max block size (we need raise ASAP anyway) maybe make it like difficulty regulation is working?
My proposal on bitcointalk https://bitcointalk.org/index.php?topic=1128357

**Comment by laanwj** [comment]
Network-wide proposals such as block size hardfork proposals and discussions belong on the bitcoin-dev mailing list, not here.
