### ISSUE TITLE
How to extract btcaddress from Txin ?

### ISSUE THREAD

**Issue by mclycan** [bitcoin/bitcoin#6474]
I can use this code to extract btcaddress from Txout, but I don't know how to extract address from Txin:
```    
BOOST_FOREACH(const CTxOut& txout, tx.vout) {
      if(ExtractDestination(txout.scriptPubKey, addressRetout)){
                std::string bitaddrout = CBitcoinAddress(addressRetout).ToString();
       }
}
```
And I have try this code to extract address from Txin, but it not work:
```
 BOOST_FOREACH(const CTxIn& txin, tx.vin)   
{ 
    COutPoint prevout = txin.prevout;
    CCoins prev;
    if(pcoinsTip->GetCoins(prevout.hash, prev))
    {
        if (prevout.n < prev.vout.size()){
            const CTxOut &vout = prev.vout[prevout.n];   
            if (ExtractDestination(vout.scriptPubKey, addressRetin))
            {
                std::string bitaddrin = CBitcoinAddress(addressRetin).ToString();     
             }
         }
    }   
}
```
the function "ExtractDestination(vout.scriptPubKey, addressRetin)" always return 0.

**Comment by jonasschnelli** [comment]
@mclycan: Please mind that this in an issue tracker not a help forum. For individual help please use the appropriate channels.
1) http://bitcoin.stackexchange.com
2) irc.feeenode.com #bitcoin or maybe #bitcoin-dev

**Comment by laanwj** [comment]
In the general case you can't do that. An address is an user representation of an output script. Input scripts contain solely the input data necessary to satisfy the output script they spend from.
So refer back to the output that they spend from to get the output script, which may have an corresponding address.

I agree with @jonasschnelli that this basic bitcoin question doesn't belong here.
