### ISSUE TITLE
Running tests with `make check` is not working

### ISSUE THREAD

**Issue by erikvold** [bitcoin/bitcoin#6478]
When I run `$ make check` after checking out this repo I get this error message "make: *** No rule to make target `check'.  Stop."

**Comment by jonasschnelli** [comment]
Did you run `./autogen` followed by a `./configure`? It's also recommended to have a look in the build docs (https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md / https://github.com/bitcoin/bitcoin/blob/master/doc).

**Comment by laanwj** [comment]
Works fine here. You must have forgotten to run autogen.sh.
