### ISSUE TITLE
GUI accessibility issues in MacOSX and Linux

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6493]
As of 0.11, Qt accessibility is no longer working in MacOSX and Linux, but does work in Windows. Reported via mail:

> Can you, if you can, enable all accessibility features in core
> client? Version 0.11 is not accessible especially in MacOs and Linux,
> the last accessible version for these osses is 0.9.X. The last version
> is accessible in Windows platform, but I prefer Mac to Windows. Can you
> enable accessibility features for screen reader support? If you want, I
> can test it with my iMac and Ubuntu laptop.
> 
> In windows, all accessibility features are working, but after upgrading
> to qt 5, the accessibility features didn't work in Mac and Linux. IN
> Linux and Mac, I can hear window names only, for example when BitCoin
> core is launched for a first time, I can hear welcome, but I can't
> navigate the radio buttons and buttons for selecting, where to use
> BitCoin folder. If I have prepared folder from Windows, I can hear Bit
> Con Core, but I can not navigate the app. In Mac, I can navigate menus
> only, in Linux, I can do nothing. So try to check qt-at-spi integration
> and other accessibility modules / accessibility vidgets, but maybe there
> is a problem with the accessibility module in qt 5 mac / linux version.
> If the team changes something, in accessibility, please let me know and
> I will test changes and report it.

It is possible that this improved with the switch to Qt 5.5.

**Comment by jonasschnelli** [comment]
Just testes this with our Qt5.5 binary on osx 10.11. Works as expected. Accessibility hints could be more precise. But it's usable. We could ask the user for a retest over email.

**Comment by MarcoFalke** [comment]
Closing, since no new issues popped up and this should work as per last comment.
