### ISSUE TITLE
Better validation on `amount` with sendtoaddress

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#6510]
Just accidentally double-pasted a bitcoin address:

```
bitcoin-cli sendtoaddress 1bitcoinaddress 1bitcoinaddress
```
and it dutifully sent 1 bitcoin to 1bitcoinaddress (even though i reflexively hit ctrl+c in a few ms). While I'm just glad the bitcoin address didn't start with 2 leading numbers, it seems like better validation in this case would be rather useful

**Comment by laanwj** [comment]
Duplicate of #6223, already fixed by #6226
