### ISSUE TITLE
WHY MY WALLET DON'T RECEIVE ANY BITCOIN?

### ISSUE THREAD

**Issue by ponlapak** [bitcoin/bitcoin#6513]
Dear Experts,

I have sent bitcoin to address 1AmLnHeHwJN4iEy9rwPG1BLNGZXF1Vdpbj on 2015-07-03 but the wallet didn't recievie any bitcoin. 

When i checked balance from https://blockchain.info/address/1AmLnHeHwJN4iEy9rwPG1BLNGZXF1Vdpbj , I found existing balance.

Please explain and advise .
![capture-1](https://cloud.githubusercontent.com/assets/13637501/9054922/224b5af2-3ab0-11e5-98d7-a5620c29b275.PNG)
![capture-2](https://cloud.githubusercontent.com/assets/13637501/9054923/225dd038-3ab0-11e5-9917-051b04d448d1.PNG)

**Comment by jonasschnelli** [comment]
Can you please open the "Debug Window" -> "Console" and enter `getblockchaininfo` and post your output here?

**Comment by ponlapak** [comment]
Here is the result.
￼
{
"chain" : "main",
"blocks" : 368353,
"headers" : 368353,
"bestblockhash" : "000000000000000013ccf3a864e786b5ec3aae0a52fffe1e5151c76f87b99a7e",
"difficulty" : 52278304845.59168200,
"verificationprogress" : 0.99998254,
"chainwork" : "00000000000000000000000000000000000000000008fb3d92019b27e89bbb1a",
"pruned" : false
}

**Comment by jonasschnelli** [comment]
Try to start Bitcoin-Qt or bitcoind with the -rescan argument.

**Option A**
`bitcoin-qt.exe -rescan`

**Option B**
`bitcoind.exe -rescan`
stop bitcoind and restart bitcoin-qt after rescan has complete

**Option C**
add `rescan=1` in your `bitcoin.conf` remove it after your bitcoin-qt has successfully rescanned.

**Comment by ponlapak** [comment]
Great !  
It's work now. 
Thank you for the solution.
