### ISSUE TITLE
Do -rescan automatically when necessary

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#6514]
#6513 is still one of the more or less popular issues with bitcoin. Less technically gifted users may lose bitcoins due to this.

Is it possible to gather some causes for this and decide if bitcoin core can solve those on it's own?

**Comment by jonasschnelli** [comment]
Losing bitcoins would be hard,.. but i agree. It might drive people to a point where they accidentally could delete keys.

I think a option "rescan for wallet transaction" in the GUI would solve most issues... most wallet apps support a similar function.

**Comment by laanwj** [comment]
`-rescan` should never be automatically necessary. Not sure how it's possible that a transaction was missed in your case. But if it is necessary at all it's a bug, so that'd be virtually impossible to detect.

**Comment by MarcoFalke** [comment]
What happens if I load my n month old wallet.dat into my bitcoin core I use daily? I am assuming there is a rescan happening for all block of the last n months?

**Comment by sipa** [comment]
That is correct.

The wallet file stores up to which block it has "seen" the chain. At
startup, an automatic rescan happens for exactly the missing part.

A manual rescan should only be necessary when you use
importprivkey/importwallet with the rescan option set to false, if you are
loading an extremely old wallet file (several years), or when you manually
tweak the wallet file using external utilities.
