### ISSUE TITLE
Intermittent travis failures due to potential_deadlock_detected

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6515]
```
Running 161 test cases...
test_bitcoin: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `onlyMaybeDeadlock' failed.
unknown location(0): fatal error in "rpc_wallet": signal: SIGABRT (application abort requested)
test/rpc_wallet_tests.cpp(64): last checkpoint
test_bitcoin: key.cpp:198: void ECC_Start(): Assertion `secp256k1_context == __null' failed.
unknown location(0): fatal error in "script_CHECKMULTISIG23": signal: SIGABRT (application abort requested)
test/rpc_wallet_tests.cpp(64): last checkpoint
test_bitcoin: key.cpp:198: void ECC_Start(): Assertion `secp256k1_context == __null' failed.
unknown location(0): fatal error in "script_valid": signal: SIGABRT (application abort requested)
test/rpc_wallet_tests.cpp(64): last checkpoint
test_bitcoin: key.cpp:198: void ECC_Start(): Assertion `secp256k1_context == __null' failed.
unknown location(0): fatal error in "script_PushData": signal: SIGABRT (application abort requested)
test/rpc_wallet_tests.cpp(64): last checkpoint
```

**Comment by casey** [comment]
For reference, here are some travis builds that failed:

https://travis-ci.org/bitcoin/bitcoin/builds/73939528
https://travis-ci.org/bitcoin/bitcoin/builds/73941114
https://travis-ci.org/bitcoin/bitcoin/builds/73943358
https://travis-ci.org/bitcoin/bitcoin/builds/73953014

All the changes look pretty harmless. And I can't reproduce it locally. It would be nice to have the debug log from travis runs, but that doesn't seem to be available.

**Comment by TheBlueMatt** [comment]
Probably a good idea to print the deadlock error to stderr instead of debug.log to make these kinds of issues easier to debug.

**Comment by casey** [comment]
Do you happen to know where debug.log is on the travis build?

We could add the following to `.travis.yml`:

```
after_failure:
   - cat /home/travis/.bitcoin/debug.log
```

And the logs would be printed after every test failure. I'm not sure that's where debug.log will wind up though, only guessing.

**Comment by theuni** [comment]
This is easy to reproduce locally via ```./configure --enable-debug```. I haven't looked into it yet, but it appears to be a static initialization issue, likely some uninteresting change upset the init order. I'll dive in tomorrow.

**Comment by laanwj** [comment]
Almost all Travis runs were failing. I've disabled a4fe57da6207c1e5691a1e843d22db571f3f0186 for now.
