### ISSUE TITLE
ERROR: AcceptToMemoryPool: non-final

### ISSUE THREAD

**Issue by Drakonadrgora** [bitcoin/bitcoin#6518]
while trying to sync with the network and after it gets about 6-8 weeks sync'd it crashes and says there was an internal failure check debug log. when I do the only error it ever shows is that. It shows nothing else but I have to close client and restart. and then it happens again around the same amount of time syncing. It has been taking me several days just to get from the start down to just 2 years 48 weeks left because of this.

I have the latest bitcoin client installed. 0.11.0 64 bit version on my windows 7 64 bit laptop.

**Comment by laanwj** [comment]
Usually these kind of issues are CPU overheating issues. Can you try specifying `par=1` in your bitcoin.conf?

**Comment by Drakonadrgora** [comment]
Hmm.. I do have a laptop cooling pad so did not think it would be overheating. I will try the suggestion as asked and see how it works at that point.

**Comment by rickycrand** [comment]
Please excuse me, I'm a complete newcommer to Bitcoin and also to this forum.
Looks like I have a similar problem. Installed Bitcoin core earlier today and it immediately started to download the block chain. When I returned to my computer a couple of hours later the program appeared to have crashed and would not restart until I restarted windows. It starts fine now but there is no longer and progress.
The log shows pages of:
2015-08-22 15:28:32 ERROR: AcceptToMemoryPool: non-final
2015-08-22 15:28:39 ERROR: AcceptToMemoryPool: non-final
2015-08-22 15:28:41 ERROR: AcceptToMemoryPool: non-final
every few seconds and there is minimal network traffic.
I'm running Core v0.11.0 and Windows 7.
Any advice will be welcome

**Comment by dcousens** [comment]
> 2015-08-22 15:28:32 ERROR: AcceptToMemoryPool: non-final

@rickycrand this just translates to:

> Error,  there was a transaction attempting to add itself to the memory pool that was non-final.  (It was not signed, had an nLockTime constraint etc).

It it is by no means an issue,  and is typical.

**Comment by rickycrand** [comment]
Dear Daniel

Thank you for the reply but I really think there is a problem either with bitcoin-qt or my computer.
(Having said that my computer has been/is generally working very well.)

I have now run bitcoin-qt 4 times and installed it twice (including clearing the data directory), but the problem persists (see attached).

Are there any know issues with this version of bitcoin-qt on windows 7 (64bit).

Is it worth me trying the 32bit version of bitcoin-qt?

Looks like some kind of lock issue to me (just guessing)?
If that could be possible how might I go about clearing any locks?

Any other suggestion or further information please let me know.

Regards
Ricky Rand


  ----- Original Message -----

**Comment by miguelmorales85** [comment]
I am having the same issue using Ubuntu 14.04 64 bits. I checked debug.log and theres only the message "ERROR: AcceptToMemoryPool: non-final" over and over again

**Comment by laanwj** [comment]
Closing this, there doesn't seem to be a clear way forward
Again, for anyone googling this, "ERROR: AcceptToMemoryPool: non-final" just means that you're receiving transactions that aren't final yet. It's not an error on your side.

**Comment by bluikko** [comment]
Why would you log something that seems to be mostly "cosmetic" with "ERROR" loglevel? "ERROR" implies that something is wrong. No wonder you are getting newbies all riled up. It should be info/notice, warning at *most*.

**Comment by laanwj** [comment]
@bluikko Agreed, that has been solved in git master https://github.com/bitcoin/bitcoin/pull/6519
