### ISSUE TITLE
Get rid of Merkle branches in the wallet

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#6536]
They don't currently serve any purpose, except as an expensive sanity check.

However, removing them would result in old clients to no longer treat such transactions as confirmed (until reindexed).

Is this a compatibility break we're willing to make for 0.12?

**Comment by sipa** [comment]
Also see #6508.

**Comment by jonasschnelli** [comment]
+1 removing the merkle branches. Maybe fully remove `CMerkleTx`.
Would a auto-rescan at first start after upgrading to a non-CMerkleTx version of bitcoin-cores wallet solve the compatibility issue?

**Comment by dcousens** [comment]
concept ACK,  could you link to the relevant code that will be removed?

**Comment by sipa** [comment]
@jonasschnelli Awesome idea! We can just change the name of the block locator, and overwrite the old one with one for the genesis block whenever we upgrade.
