### ISSUE TITLE
Unable to compile master branch on Windows 7

### ISSUE THREAD

**Issue by ptschip** [bitcoin/bitcoin#6549]
I'm able to compile v0.11.0 but not the current master branch

Compiling in windows 7, using mingw32
I'm getting the following error

Making all in src
make[1]: Entering directory `/c/bitcoin/src'
make[2]: Entering directory `/c/bitcoin/src'
  CXX    crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX    crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX    crypto/libbitcoinconsensus_la-sha1.lo
  CXX    crypto/libbitcoinconsensus_la-sha256.lo
  CXX    crypto/libbitcoinconsensus_la-sha512.lo
  CXX    libbitcoinconsensus_la-eccryptoverify.lo
  CXX    libbitcoinconsensus_la-ecwrapper.lo
  CXX    libbitcoinconsensus_la-hash.lo
  CXX    primitives/libbitcoinconsensus_la-transaction.lo
  CXX    libbitcoinconsensus_la-pubkey.lo
  CXX    script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX    script/libbitcoinconsensus_la-interpreter.lo
  CXX    script/libbitcoinconsensus_la-script.lo
  CXX    libbitcoinconsensus_la-uint256.lo
  CXX    libbitcoinconsensus_la-utilstrencodings.lo
  CXXLD  libbitcoinconsensus.la
.libs/libbitcoinconsensus_la-ecwrapper.o: In function `ZN6CECKeyC2Ev':
c:\bitcoin\src/ecwrapper.cpp:95: undefined reference to `EC_KEY_new_by_curve_nam
e'
.libs/libbitcoinconsensus_la-ecwrapper.o: In function `ZN6CECKeyD2Ev':
c:\bitcoin\src/ecwrapper.cpp:100: undefined reference to `EC_KEY_free'
.libs/libbitcoinconsensus_la-ecwrapper.o: In function `ZN6CECKey9SetPubKeyEPKhj'
:
c:\bitcoin\src/ecwrapper.cpp:116: undefined reference to `o2i_ECPublicKey'
.libs/libbitcoinconsensus_la-ecwrapper.o: In function `ZN6CECKey6VerifyERK7uint2

**Comment by sipa** [comment]
Looks like you're not linking libbitcoinconsensus against openssl?

**Comment by ptschip** [comment]
Is that a new dependency or am I supposed to compile openssl with that 
support?

Here's the configure script I am using.

CPPFLAGS="-I/c/deps/db-4.8.30.NC/build_unix \
-I/c/deps/openssl-1.0.1k/include \
-I/c/deps \
-I/c/deps/protobuf-2.6.1/src \
-I/c/deps/libpng-1.6.16 \
-I/c/deps/qrencode-3.4.4 \
-I/c/deps/gmp-6.0.0" \
LDFLAGS="-L/c/deps/db-4.8.30.NC/build_unix \
-L/c/deps/openssl-1.0.1k \
-L/c/deps/miniupnpc \
-L/c/deps/protobuf-2.6.1/src/.libs \
-L/c/deps/libpng-1.6.16/.libs \
-L/c/deps/qrencode-3.4.4/.libs \
-L/c/deps/gmp-6.0.0/.libs" \
BOOST_ROOT=/c/deps/boost_1_57_0 \
./configure \
--disable-upnp-default \
--disable-tests \
--with-qt-incdir=/c/Qt/5.3.2/include \
--with-qt-libdir=/c/Qt/5.3.2/lib \
--with-qt-plugindir=/c/Qt/5.3.2/plugins \
--with-qt-bindir=/c/Qt/5.3.2/bin \
--with-protoc-bindir=/c/deps/protobuf-2.6.1/src

**Comment by sipa** [comment]
No, it has always been necessary. I don't know anything about Windows or its development environment, so this is not a suggestion for fixing your issue. I'm only clarifying that the problem seems to be that libbitcoinconsensus is not being linked against OpenSSL.

**Comment by theuni** [comment]
Judging by the symbols the linker is complaining about, I'd guess that you built OpenSSL without EC/ECDSA support.

**Comment by ptschip** [comment]
well, i hear you but i don't think so ... here are my compile flags for 
openssl

./Configure no-zlib no-shared no-dso no-krb5 no-camellia no-capieng 
no-cast no-cms no-dtls1 no-gost no-gmp no-heartbeats no-idea no-jpake 
no-md2 no-mdc2 no-rc5 no-rdrand no-rfc3779 no-rsax no-sctp no-seed 
no-sha0 no-static_engine no-whirlpool no-rc2 no-rc4 no-ssl2 no-ssl3 mingw


But in the end, the problem is the same,  I can compile v10.2 and v11 of 
Bitcoin Core, just not the current master branch.

I'll keep poking around...

**Comment by ptschip** [comment]
It looks like this is the same issue as  issue #6458.   I had just 
forgotten to re-run ./autogen.sh after adding the pkg.m4 file and 
modifying configure.ac.

Build ran and completed now on the master branch
