### ISSUE TITLE
There's no TUI (text-based user interface) to stand side-by-side with bitcoin-cli

### ISSUE THREAD

**Issue by demagumd** [bitcoin/bitcoin#6552]
Please consider adding curses interface to bridge the gap between fully fledged GUI and CLI. bitcoin-tui maybe?

**Comment by sipa** [comment]
Pull requests welcome!

**Comment by jonasschnelli** [comment]
Not sure it we would like to maintain another fronted. There is a bitcoin ncurses project already: https://github.com/azeteki/bitcoind-ncurses

**Comment by demagumd** [comment]
@jonasschnelli Before disregarding this request as a burden please consider that many significant projects in the software world (Linux kernel, NetworkManager, VIM) ship with TUI as one of the three industry-standard ways to interact with users. Yes, there's the separate bitcoind-ncurses project there but so are other parallel implementations of bitcoind. What I'm trying to say is that I believe that bitcoin-tui should at least have a chance to be discussed on ideological level by the developers and not to be dismissed on a whim.

**Comment by jonasschnelli** [comment]
Not really dismissing it. Personally i would love to have a ncurses CLI fronted. I'm just not sure if we want to burden this project by adding another module which requires maintenance within this repository.
But sure, pull request are welcome!

**Comment by rnicoll** [comment]
Agreed; I'd love an ncurses frontend, but equally I think we have higher priorities, and the existence of a wrapper UI should satisfy this for now.

**Comment by TheBlueMatt** [comment]
I think we'd rather move towards splitting the bitcoin-qt gui out into a separate process, rather than keeping it in one monolithic one. So adding a CLI interface that is in-process sounds like a bad idea. Though maybe something non-JSON-RPC could be used in the future, I'd think the RPC-based one linked above should be sufficient for most tasks, and the JSON-RPC interface should be extended to make it more full-featured, rather than thinking about how to add a curses TUI to bitcoind.

**Comment by TheBlueMatt** [comment]
We could, of course, move the curses repo linked above into github.com/bitcoin/, if there was a really strong push to do so, though I'm not sure where we want to draw the line on such things.

**Comment by demagumd** [comment]
@TheBlueMatt +1 on the logistics how it should be done. Regarding the 'strong push' - I think there will never be a very strong push to include TUI from public at large the same way for example that most Firefox users don't push for Firefox Developers Tools to be included in their browser. But those niche groups who push for it are as important for the survival of the ecosystem as the big groups are; as those, most of the times, will be power users and developers themselves.

**Comment by venzen** [comment]
Having a curses interface is always good, especially on a headless server where the RPC interface can be more cumbersome. The question is about timing - before or after the splitting the -QT gui? Third party interfaces seems a good option, but let the competition run - choosing the only one out there may be premature?

**Comment by luke-jr** [comment]
There is no need to choose one, or treat "third-party" as "lesser". When it comes to UIs, there is no "privileged position".

**Comment by ajweiss** [comment]
Just to clarify, @TheBlueMatt is suggesting cloning the full ncurses python gui repository and having it stand alone as a separate repository in the bitcoin namespace/organization on github, as opposed to actually moving it into the specific bitcoin/bitcoin repository, correct?

**Comment by TheBlueMatt** [comment]
@ajweiss More of a "we could....if we wanted to..." than a suggestion. I dont actually think we should, but I brought it up to point out an alternative I'd prefer than putting something else in the bitcoind/bitcoin-qt/bitcoin-tui binary.

**Comment by TheBlueMatt** [comment]
@ajweiss and we could do either one, bitcoin/bitcoin or bitcoin/*.

**Comment by laanwj** [comment]
Closing this. As mentioned, there is already a project that does this (and it's pretty nice! I've been using it for quite a while). Feel free to contribute there. There is no need for it to be taken up here. I'd like to lessen the scope of Bitcoin Core, not extend it further.

**Comment by esotericnonsense** [comment]
azeteki reporting in, I've had a busy year, apologies.

I agree with others in that there is no real need for Bitcoin Core itself to include a TUI interface. The opposite in fact - with a good enough API bitcoin-qt could be seperated out and function in much the same way as bitcoind-ncurses.

I also think that the current state of the code is simply not sufficient to be included with bitcoind. There exists no way to make payments without using the console, for example.

**Comment by laanwj** [comment]
@esotericnonsense Right! Bundling is not the only, or even best way. Having everything in one repository makes things harder/slower to maintain.

Instead of packaging it with bitcoin repository, we could put the project as a project under the 'bitcoin-core' organization. E.g. leaving it as a separate project but with the 'blessing' of the bitcoin core project. Or refer to it in the documentation.
