### ISSUE TITLE
Gitian-building instructions need updating

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#6555]
Opening this issue to hopefully save somebody else a lot of frustration:

The git HEAD version of gitian-builder uses `lxc-start --version` which is a new option that doesn't exist in the version of LXC you get with Debian 7; specific error is:
```
$ make-clean-vm --suite precise --arch amd64
lxc-start: unrecognized option '--version'
```

The doc/gitian-building.md instructions should either be updated to recommend using a specific commit of gitian-builder (2bcc06e6b75b3f7a0167cde7237331757dd559c6 worked for me), or somebody should work through using Debian 8 as the host operating system (I started down that path but don't understand LXC deeply enough to figure out how to make it all work).

**Comment by fanquake** [comment]
The upgrade to Debian 8.1 has been started in #6419. I'll PR some of the
changes there shortly.
