### ISSUE TITLE
Implement BIP101: Increase maximum blocksize

### ISSUE THREAD

**Issue by stevenroose** [bitcoin/bitcoin#6559]
I was surprised that there was no Issue or PR for this yet.

So here it is, please implement [BIP101](https://github.com/gavinandresen/bips/blob/blocksize/bip-0101.mediawiki). 

It should be possible to do this just by merging [this branch](https://github.com/bitcoinxt/bitcoinxt/tree/only-bigblocks) into the Bitcoin repo.

**Comment by MarcoFalke** [comment]
The PR is #6341 (currently closed).

**Comment by paveljanik** [comment]
No need to create issues for implementing BIPs. An author/anyone else will create PR once the code is ready.
Please close this issue.
