### ISSUE TITLE
Clean up code in AcceptConnection

### ISSUE THREAD

**Issue by dcousens** [bitcoin/bitcoin#6560]
See comments in https://github.com/bitcoin/bitcoin/pull/6374.

**Comment by Diapolo** [comment]
Agreed, I think that totally makes sense!

**Comment by laanwj** [comment]
Not convinced that this is really an issue :p

**Comment by dcousens** [comment]
@laanwj feel free to close.  I just typically make issues for things as a form of TODO using https://github.com/issues

**Comment by Diapolo** [comment]
Feel free to create a pulls... I don't feel like creating new ones currently.

**Comment by dcousens** [comment]
No longer relevant
