### ISSUE TITLE
listunspent running slowly (and also balance and transaction building)

### ISSUE THREAD

**Issue by AdvancedStyle** [bitcoin/bitcoin#6573]
Currently using bitcoind 0.11 headless on Debian (although had the same issue with all previously bitcoind versions).

The wallet info:
Wallet.dat size: 160MB
Number of addresses: ~16,000
Unspent outputs: (varies but around: 20-40)

Load on the server seems fairly low, and CPU usage is very low.
Memory: 4GB
load average: 0.39, 0.43, 0.35
Drive is SSD

"listunspent" function is extremely slow; and by extension this seems to affect getbalance and sendmany/sendtoaddress functions.

Here are some specific examples of this sluggishness:

```
$ time /path/to/my/bitcoin/bitcoin-cli getbalance "" 3
real    0m3.398s
user    0m0.008s
sys     0m0.004s

$ time /path/to/my/bitcoin/bitcoin-cli listunspent
real    0m4.213s
user    0m0.008s
sys     0m0.004s
```

The times are consistently 3-4 seconds every time

But then some commands are much quicker:

```
$ time /path/to/my/bitcoin/bitcoin-cli getinfo
real    0m0.039s
user    0m0.004s
sys     0m0.004s
```

**Comment by jonasschnelli** [comment]
@AdvancedStyle: balance calculation is pretty unoptimized in the current wallet.
You could try compiling your own bitcoin-core with #6550 on top. In theory this should be faster (but still lacks of other optimizations). I think it's mostly slow because of multiply calls to `CMerkleTx::GetDepthInMainChain()`.

**Comment by AdvancedStyle** [comment]
@jonasschnelli I compiled bitcoin-core master with the #6550 patch applied, but it makes no difference to the load times of *listunspent* or *getbalance* CLI calls.

**listunspent** just took 6 seconds to run.

**Comment by sipa** [comment]
The running time of those RPCs depends on the number of transactions in the
wallet, not the number of unspent outputs. We should add an index for
that...

**Comment by AdvancedStyle** [comment]
@sipa the work-around we have right now is to externally cache the listunspent in our own software (after sending or receiving anything) and then build the transactions manually and sign via bitcoin-core (which cuts total time to send down to milliseconds).  It would be very useful if some kind of caching or indexing of the unspend was built into bitcoin-core though.

Sorry I do not have C++ skills so cannot create any suggested patch.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
