### ISSUE TITLE
Miners should prioritise transactions in forked chains

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#6574]
It would be nice if there was an option to download non-best blockchains and prioritise (even replacing existing mempool txns) anything confirmed in them. This would make confirmed transactions somewhat stronger.

**Comment by casey** [comment]
What's the rationale for this feature? So that if a user sees that a transaction is confirmed in a block that is then orphaned, it's likely to get reconfirmed quickly?

**Comment by dcousens** [comment]
@casey at least,  ideally,  that seems to be the intended effect.   Although no incentive exists,  defaults can be powerful enough that this is worth doing.

**Comment by TheBlueMatt** [comment]
I wouldnt consider it "stronger" unless its also rational to prioritise those transactions, which it is not.

**Comment by luke-jr** [comment]
Fraudulent double-spending clearly harms the Bitcoin economy, so I would say miners have a light incentive to make an attempt to prevent it when practical. (Non-fraudulent double-spending does not, AFAIK, have any case harmed by this behaviour.)

There is a subtle risk to this behaviour I should document: if a transaction is the *cause* of the stale chain being non-best, we would not want to re-mine that transaction. I don't know if there's a good way to determine and prevent this.

**Comment by dcousens** [comment]
> There is a subtle risk to this behaviour I should document: if a transaction is the cause of the stale chain being non-best, we would not want to re-mine that transaction. I don't know if there's a good way to determine and prevent this.

@luke-jr wouldn't you just be pulling the sub-set of transactions out of your own (already validated) mempool?
Or are you thinking of another situation where several miners are essentially validating an older version of the network,  and this would encourage them to select similar sets?

**Comment by TheBlueMatt** [comment]
I would have no problem with this as long as the transactions you are replacing have lower fee rates, and if you never prioritize transactions above others which have a higher fee rate (making the decision to do so irrational). I really dont think we should be adding new behavior which is not in a rational miner's best interest, we should be moving the other way (ie eventual RBF, etc).

**Comment by Sjors** [comment]
Doesn't the fact that transactions are mostly ordered by fee provide enough likeliness that a replacement block has mostly the same transactions?

**Comment by MarcoFalke** [comment]
Discussion should probably move to the mailing list
