### ISSUE TITLE
Block size possible solution - to set minimum size

### ISSUE THREAD

**Issue by bdimych** [bitcoin/bitcoin#6581]
Hi,
As I understand the main problem of the fork Core<->XT is possibility of double spending:
-I run XT and spend my coins
-it is written in 8mb block
-Core does not accept this block
-I run Core and spend my coins again
-it is written in 1mb block
-but XT accepts this block too
so
-in the XT blockchain both blocks [8] and [1] contain my coins

I thought that possible solution can be to set minimum block size
i.e.
2016: 1mb <= blockSize < 2mb
2017: 2mb <= blockSize < 3mb
2018: 3mb <= blockSize < 4mb
etc

Free space could be filled with zeroes and compressed.

That's all, just an idea.

**Comment by laanwj** [comment]
Please, no block size proposals here. The right place is the mailing list.

(Also: most of the blocksize BIPs already feature automatic scaling of the block size over time. The problem is that you cannot predict the future so any automatic growth may be problematic at some point)
