### ISSUE TITLE
Runing bitcoind through a tor proxy does not hide my ipv6 address

### ISSUE THREAD

**Issue by lunokhod** [bitcoin/bitcoin#6585]
I am running bitcoind through a tor proxy, and everything seems to be working fine for my hidden service, as well as nodes that are being connected to via ipv4. I've verified (via getpeerinfo) that my real ipv4 address does not show up when inspecting the nodes I'm connected to. However, I was very surprised to see that I have a single incoming connection from ipv6 that is connected to my real ipv6 address.

Here is the info I am using in my bitcoin configuration file:
~~~~
proxy=127.0.0.1:9050
onion=127.0.0.1:9050
externalip=myhiddenservice.onion
listen=1
discover=0
~~~~
Here is the getpeerinfo on the node:
~~~~
  {
    "id": 21,
    "addr": "[2a01:4f8:202:81b1::2]:4834",
    "addrlocal": "[my:ipv6:address:xxx:xxx:xxx:xxx:xxx]:8333",
    "services": "0000000000000000",
    "lastsend": 1440404xxx,
    "lastrecv": 1440403xxx,
    "bytessent": 2081xxx,
    "bytesrecv": 39xxx,
    "conntime": 1440367xxx,
    "timeoffset": 0,
    "pingtime": 0.043xxx,
    "version": 70002,
    "subver": "/Satoshi:0.9.3/",
    "inbound": true,
    "startingheight": 371217,
    "banscore": 0,
    "synced_headers": 371273,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false
  },
~~~~
And here is the relevant getnetwork output
~~~~
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": false,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": false,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    }, 
    {
      "name": "onion",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    }
  ],
~~~~
For info, I am running this on OSX 10.10.5, bitcoin v0.11.99.0-49793fb and tor 0.2.6.10.

**Comment by laanwj** [comment]
That's curious. If you specify `-proxy` and/or `-externalip`, `-discover` will be automatically disabled. It will not advertize any other addresses.
Have you run bitcoind before without this setup? Might an old node still have known your IPv6 address?

**Comment by lunokhod** [comment]
I probably have run bitcond on clearnet before, so it is possible that someone knows my ipv6 address. However, shouldn't discover=0 preclude them from connecting to my node?

**Comment by laanwj** [comment]
It does this:
```
  -discover
       Discover own IP addresses (default: 1 when listening and no -externalip
       or -proxy)
```
It has no effect on what interfaces are listened on by `-listen` (note that `-listen` is disabled by default if `-proxy` is given).
If you want to only bind to a specific interface, use e.g. `-bind=127.0.0.1`.

**Comment by lunokhod** [comment]
Thanks for the help, but this still appears to be a bug to me. 

* The client is telling me that reachable=false for ipv6, yet I have an inbound connection on ipv6. 
* Listen needs to be set to 1 in order to run a hidden service.

**Comment by laanwj** [comment]
I'm still not convinced that this is a bug.
`reachable=false` means as much as "cannot connect to this network". It does not mean that connections cannot come in.  It is completely independent of listening functionality.

Yes, you need `-listen` for a hidden service. By default if you listen, it listens on every interface. If you want to restrict that, as said above, use `-bind`.

(it would ofc be possible to automatically restrict the binding interfaces based on e.g. `-onlynet`, but I think such parameter interaction will only result in further confusion)

**Comment by lunokhod** [comment]
Just to follow up, using

    onlynet=ipv4
    onlynet=onion

does not fix this problem: I still get an incoming connection from ipv6. Using

    bind=127.0.0.1

however does work. Thanks!

**Comment by sipa** [comment]
Yes, onlynet only restricts outgoing connections.
