### ISSUE TITLE
Dynamic MAX_BLOCK_SIZE using SMA or EMA + 1 StdDev

### ISSUE THREAD

**Issue by medisoft** [bitcoin/bitcoin#6587]
Hello! I want to suggest to set an automatic MAX_BLOCK_SIZE using Simple Moving Average or Exponential Moving Average of the latest 1440 blocks (10 days) plus 1 standard deviation.

With the minimum value of it equal to 1,000,000 bytes. This way it can grow indefinitely but it will adapt to the market demands and the adaptation is not so fast to be used for spam, but fast enough to adapt to the moves of the market.

**Comment by laanwj** [comment]
For block size proposals you should use the mailing list: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev
This tracker is just for technical software issues.
