### ISSUE TITLE
RPC: Add support for pub key auth

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#6598]
Nice to see progress in improving the RPC server (#5677).
A dorn in the flesh is still the http base auth.

What about supporting (as addition or by replacing the http base auth.) something similar to bitpays BitAuth?

Single user auth could work like this:

* The `bitcoin.conf` could hold a `-rpcpubkey=<pubkeyhex>`.
* Each request would need to have a `x-signature: <sig>` http header containing a signature of the URL+http-body.

**Comment by dcousens** [comment]
An symmetric token scheme would probably work just as well IMHO.

**Comment by jonasschnelli** [comment]
IMO asym cypher auth. has advantages over a sym auth. No need to preshare secrets. ECDSA is essential for bitcoin-core so it would be a small change to support pub key auth over ECDSA. And, ... if we once manage to make the RPC server stable and exposable to insecure environments, having a asym. auth process would be better.

**Comment by dcousens** [comment]
@jonasschnelli granted it also puts a much larger burden on the RPC caller to have an ECDSA library on hand,  hopefully not making any mistakes.

**Comment by jonasschnelli** [comment]
Agreed. Client side this can be a burden. Because of that, supporting ECDSA auth as addition to base auth. could make sense. On the other hand, I think, lots of client applications are already using a ec stack somehow.

**Comment by jonasschnelli** [comment]
Implementation #6604.
Is a controversial change, closing.
