### ISSUE TITLE
Send tab: "Amount" field hidden by scrollbar with coin control enabled

### ISSUE THREAD

**Issue by plato-cambrian** [bitcoin/bitcoin#6601]
My original problem:
Given I start with a brand new wallet,
And I receive 1BTC to Address A,
And I receive 0.08 BTC to Address B,
And I have checked "Enable coin control features" in the options:

When I go to the send tab,
And I click "Inputs" in the coin control section,
And I check only Address B,

Then the "Amount" field on the Send page vanishes, and a non-editable Amount displays 0.08.

How do I send less than the full balance (say, 0.04 BTC) to Address C from Address B?
![bitcoin-uncensored](https://cloud.githubusercontent.com/assets/7917920/9570297/764d01aa-4f55-11e5-996e-74348656cbed.PNG)

**Comment by plato-cambrian** [comment]
>(20:22:32) PRab: therealplato: The middle group has a scroll bar. Have you tried scrolling down? (Real question, I haven't used core wallet in a while)

Good lord please just make my window 20px bigger! this is awful UX!

**Comment by luke-jr** [comment]
Well, your window is smaller than the default size...

**Comment by jonasschnelli** [comment]
I think that is a reasonable behavior. If you open "coin control" (expert feature) and extend the transaction fee frame, the only place where the height can be reduced if the "pay to" part. You can decide then to hide the transaction fee frame, enlarge the window or scroll within the tiny space.
And mind, the screenshot you have posted will not be visible to standard user at first sight. Only if one enables "coin control" and extend the fee screen.

**Comment by plato-cambrian** [comment]
I missed the tiny scrollbar in the middle because years of convention have taught my eye to check for scrollbar cues at the lower right edge of the content area (which in this case is everything between the tabs at the top and the Send button at the bottom.)

I did try scrolling with my mousewheel, but the cursor was in the wrong place - with my screenshot there are only 70 vertical pixels out of 428 where the mousewheel can successfully scroll the Amount field into view.

It would be better to put the scrollbar along the right edge and scroll the *entire container*, instead of independently scrolling the child UI component.

i.e with my selected features and window size, the entire Coin Control Features and Pay To areas would be visible, the top half of Transaction Fee would be visible, and scrolling down would scroll Transaction Fee in and Coin Control Features out.

**Comment by MarcoFalke** [comment]
I cannot reproduce on `master` running with `-resetguisettings` and then expand all widgets:

![untitled](https://cloud.githubusercontent.com/assets/6399679/13755734/e557d2b6-ea1c-11e5-8939-00babe160749.png)

**Comment by laanwj** [comment]
This may well depend on OS and screen settings. 
It may help that the "send as zero fee" line is going away with #7686, creates a little bit more room for the content area.

**Comment by MarcoFalke** [comment]
> This may well depend on OS and screen settings. 

I don't think  this is the case for gitian biniaries. I think, it primarily depends on what the user set the size to. Or, when the gui settings contain the size as an artefact of a previous version, which was more compact like 0.9.
