### ISSUE TITLE
configure.ac:902: error: possibly undefined macro: PKG_CONFIG_LIBDIR

### ISSUE THREAD

**Issue by maiiz** [bitcoin/bitcoin#6602]
###### [root@11 bitcoin-31bfc272c7b2d1ff45d70bd19047bfe866296589]# cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m

###### [root@11 bitcoin-31bfc272c7b2d1ff45d70bd19047bfe866296589]# whereis pkgconfig
pkgconfig: /usr/lib/pkgconfig /usr/lib64/pkgconfig /usr/local/lib/pkgconfig /usr/share/pkgconfig

###### [root@11 bitcoin-31bfc272c7b2d1ff45d70bd19047bfe866296589]# sh autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
libtoolize: copying file `build-aux/m4/libtool.m4'
libtoolize: copying file `build-aux/m4/ltoptions.m4'
libtoolize: copying file `build-aux/m4/ltsugar.m4'
libtoolize: copying file `build-aux/m4/ltversion.m4'
libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
libtoolize: copying file `build-aux/m4/libtool.m4'
libtoolize: copying file `build-aux/m4/ltoptions.m4'
libtoolize: copying file `build-aux/m4/ltsugar.m4'
libtoolize: copying file `build-aux/m4/ltversion.m4'
libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
configure.ac:902: error: possibly undefined macro: PKG_CONFIG_LIBDIR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by jonasschnelli** [comment]
Did you install pkg-config? Check also: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md

**Comment by maiiz** [comment]
yes i have install the pkg-config
[root@11 bitcoin-31bfc272c7b2d1ff45d70bd19047bfe866296589]# yum install pkgconfig
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
Package 1:pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version
Nothing to do

**Comment by jonasschnelli** [comment]
@maiiz could you once try and add `m4_pattern_allow(PKG_CONFIG_LIBDIR)` to configure.ac and see if this cures your issue?

**Comment by maiiz** [comment]
@jonasschnelli 
###### add m4_pattern_allow(PKG_CONFIG_LIBDIR) is ok,thx

**Comment by maiiz** [comment]
@jasonlewicki  but i have compiled old version 0.9.3

**Comment by jonasschnelli** [comment]
@maiiz: for the records: did m4_pattern_allow() solved you issue?

**Comment by maiiz** [comment]
@jonasschnelli  
no solve completely ! just solve "autogen.sh" no error.
there other error when "configure"
I don't try any more,because old version is enougth!

**Comment by peterwillcn** [comment]
configure.ac:966: error: possibly undefined macro: PKG_CONFIG_LIBDIR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by laanwj** [comment]
@peterwillcn I think you need to install pkgconfig
Though there have been other issues as well on CentOS, see #6432
