### ISSUE TITLE
RPC: add support to change the block size soft limit

### ISSUE THREAD

**Issue by kanoi** [bitcoin/bitcoin#6605]
Having to stop and restart a bitcoind to change the blocksize soft limit would be better handled by an RPC interface command to change it, to avoid the need for a restart.

**Comment by luke-jr** [comment]
Agreed. I wonder if there should simply be a RPC method to change any of the command-line options? (and only officially support it for a specific set that is known to react to changes in mapArgs)

**Comment by jameshilliard** [comment]
Maybe just a RPC command to reload settings from bitcoin.conf without a restart? This would certainly be handy as I've had to change some settings to handle the transaction spam attacks and restarting bitcoin core is not something that is easy to do on an active pool.

**Comment by MeshCollider** [comment]
Related: https://github.com/bitcoin/bitcoin/issues/309

**Comment by jnewbery** [comment]
No-one appears to be working on this, and it's been untouched for over 2 years. Close with 'up for grabs'?

**Comment by MarcoFalke** [comment]
I think this goes under the general topic of "Allow command line args to be overridden at run-time". Making it safely possible for a single arg is probably as much effort as the general case.
