### ISSUE TITLE
Rcvd TXs not showing amount

### ISSUE THREAD

**Issue by misterdna** [bitcoin/bitcoin#6614]
I'm a GitHub noob and not a technical person, so I apologize if this has been dealt with, or I'm not presenting this right.

I'm running Core v0.11.0 (64-bit) on Mac.

My entire "requested payments history" shows "(no amount)" for every transaction, which is inaccurate. I never noticed this with the previous version.

The transactions view appears to show all transactions accurately.

**Comment by fanquake** [comment]
@misterdna Are you still having this issue? If so, can you provide any more information?

**Comment by laanwj** [comment]
Right - I think this is a misunderstanding, if you didn't put an amount when creating the payment requests, they will be listed as (no amount)

**Comment by misterdna** [comment]
Yes, sorry, I didn’t understand this screen didn’t reflect actual status of the addresses.

I think I’ll make some suggestions on ways I think this screen could be more useful.
