### ISSUE TITLE
bitcoin-cli RPC client doesn't support HTTP chunked encoding.

### ISSUE THREAD

**Issue by msgilligan** [bitcoin/bitcoin#6623]
I'm working on a bitcoinj-based Bitcoin JSON-RPC server and discovered that `bitcoin-cli` will return:

    error: no response from server

when the JSON-RPC server returns an HTTP chunked response. `curl` and my Java client work correctly with the server -- and if I modify the server to not send chunked responses `bitcoin-cli` works.

I can provide links to more info or to a test server if needed.

p.s. I tested on Mac OS X with a client built from source that reports `v0.10.2.0-390ea20`

**Comment by msgilligan** [comment]
For reference here is the issue I opened against `jsonrpc4j` which shows the workaround code I used to get `bitcoin-cli` to work: https://github.com/briandilley/jsonrpc4j/issues/80

**Comment by msgilligan** [comment]
To reproduce make sure you have JDK 8+ installed, then download and run an early version of `bitcoinj-daemon`:

    curl -O -L https://bintray.com/artifact/download/msgilligan/maven/com/msgilligan/bitcoinj-daemon/0.0.2/bitcoinj-daemon-0.0.2.jar
    java -jar bitcoinj-daemon-0.0.2.jar

Then run the client:

    bitcoin-cli -rpcport=8080 getblockcount

You should get the following output:

    error: no response from server

**Comment by laanwj** [comment]
As bitcoind doesn't ever send chunked encoding, that's not really a design goal either.

Having said that, try the bitcoin-cli from #5677, it is based on a more extensive HTTP implementation.

**Comment by msgilligan** [comment]
Thanks @laanwj 

I'm developing a Bitcoin JSON-RPC server in Java (using bitcoinj) and my plan is to help make the server-side library (jsonrpc4j) configurable to not send chunked encoding. But I thought I'd open this issue to at least document it. I was using `bitcoin-cli` to test the Java server when I discovered this issue.

**Comment by laanwj** [comment]
It's been merged. I think it should work now.

**Comment by msgilligan** [comment]
I pulled the latest `master`, built and ran `bitcoin-cli` against `bitcoinj-daemon` and it worked!

Thanks!
