### ISSUE TITLE
bitcoin.org binary for 0.11 doesn't work on gentoo hardened

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6628]
(reported by phantomcircuit on IRC)
```
./bitcoin-0.11.0/bin/bitcoind: symbol __chk_fail, version GLIBC_2.3.4 not defined in file libc.so.6 with link time reference
```
Glibc version is 2.20 so it shouldn't complain about missing a 2.3.4 symbol.
But Gentoo hardened uses different compile settings, so it's probably related to that.
Not sure if this is worth fixing, but reporting anyway...

From glibc_compat.cpp
```c++
extern "C" void __chk_fail(void) __attribute__((__noreturn__));
```
Could even be that our compatibility wrapper is causing this issue, as it uses __chk_fail.

**Comment by luke-jr** [comment]
Why was this closed?
