### ISSUE TITLE
Issues in master after libevent merge

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#6655]
Not sure I completely understand this yet, so opening an issue for now:

After #5677, I believe it is now the case that the rpc tests may fail if there's inactivity for more than 30 seconds after opening a connection.  I'm getting repeatable failures locally on some of the longer-running tests (such as bipdersig.py), which I seem to be able to fix by either increasing the rpctimeout on all the nodes in the test, or by keeping the rpc connections warm with more rpc calls.

I think some travis jobs may be failing for this reason as well: https://travis-ci.org/bitcoin/bitcoin/builds/79514930

I'm not sure what the right solution is -- should the rpc test framework change somehow to allow for the connection to be re-established?  Or should we just be defaulting the timeout to a longer value in the tests that need it?

**Comment by morcos** [comment]
Additional issues:


- Sometimes this error is printed to stderr on startup, node appears to still work:
[warn] getaddrinfo: address family for nodename not supported

- rpcbind_test.py does not work

**Comment by jonasschnelli** [comment]
+ SIGPIPE (when reading a closed socket) needs to be handled as well

**Comment by ptschip** [comment]
I'm seeing also a slightly different message on Native Windows when
nodes startup but the node seems to run fine.

[warn] getaddrinfo: no address associated with nodename

**Comment by laanwj** [comment]
I noticed that `rpcbind.py` works with master libevent. So I bisected the `rpcbind.py` hang to libevent commit https://github.com/libevent/libevent/commit/71e709c7829275a594f767b27468b1b52e8b5bb9

This is a bug in libevent which will be fixed in a next release, thus not something that can be fixed on our side.

**Comment by dcousens** [comment]
On another note,  is this symptomatic of just not enough testing being done for such a large change?
Any ideas on how we could avoid this in future?
Obviously blocking a PR for the sake of people not willing to test until it is merged is not a solution,  but,  just a thought.

**Comment by laanwj** [comment]
@dcousens Using master implies that there can be temporary risks from merges. If you can't tolerate that, use one of the stable relases.

**Comment by jgarzik** [comment]
Sometimes you have to merge something for it to get wide testing and review.  "release early, release often"

Better to iterate quickly - merge quickly, get code out to the biggest test lab in the world, The Internet.  We can always revert or fix just as quickly.

**Comment by laanwj** [comment]
I'm trying to get the libevent http ipv6 fix backported to 2.2: https://github.com/libevent/libevent/pull/287
In the meantime it would make sense to disable the IPv6 bind test, at least when libevent 2.2 is detected.

**Comment by laanwj** [comment]
Closing this. Upstream libevent has merged the fix into their stable branch. Until that version is released, the test has been commented out (#6837).
