### ISSUE TITLE
bitcoind exits with SIGPIPE after Ctrl+C in bitcoin-cli

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#6660]
Current master, OS X self built.

`bitcoind` exits after I press Ctrl+C in the other terminal after running the command

```
bitcoin-cli getrawmempool true
```

The output of the command is quite large right now... When I press Ctrl+C, the `bitcoind` running in the other terminal window will exit. The exit code is 141 (141-128 = 13, SIGPIPE).

When the mempool gets large enough, ie. cca 30000 txs, I can reproduce with cca 30% probability.

Looks like new `libevent` based webserver doesn't handle SIGPIPE correctly.

**Comment by jonasschnelli** [comment]
Confirmed.
Needs fixing.
