### ISSUE TITLE
rescanning uses incorrect date for old transactions

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#6662]
I had a few conflicted transactions in my wallet, so I ran:

```
bitcoind -zapwallettxes=2
```

to delete them. After doing so, all my transactions from before January 2014 had a date of January 2014.

Upon checking the source code, I see this line in `CWallet::AddToWallet()` in `wallet/wallet.cpp`:

```
wtx.nTimeSmart = std::max(latestEntry, std::min(blocktime, latestNow));
```

`blocktime` is the time I want to see in my transactions, `latestNow` is much bigger, and so the `min()` returns the time I want, but `latestEntry` is January 2014, and so that's the time that is used for all my old transactions.

I'm not entirely clear how the Jan 2014 date is being found, since `-zapwallettxes` is meant to delete all the transactions and rescan to find them again, but it seems that

```
TxItems txOrdered = OrderedTxItems(acentries);
```

is finding a transaction from 2014, even after all transactions have been deleted.

I tried replacing the nTimeSmart = max(min()) code with this:

```
wtx.nTimeSmart = std::min(blocktime, latestNow);
```

then re-ran with the -zap flag, and now I see the correct dates next to all of my transactions.

**Comment by bitcartel** [comment]
Does this still need fixing?
 https://github.com/bitcoin/bitcoin/blob/df91e11ae1e9d7af55a549b597a73d01e3a646c7/src/wallet/wallet.cpp#L3700

**Comment by ryanofsky** [comment]
It doesn't look like that line of code has changed since it was added in 2012 c3f95ef13f48d21db53992984976eac93e7a08fc.

It sounds like dooglus had to remove the max with `latestEntry` part to avoid the problem.

**Comment by thejohnha** [comment]
I believe this is the issue causing older transactions to have incorrect dates when using the Export function out of the bitcoin-core client (GUI). It would be nice if the export function worked correctly... Many thanks 🙏🙏🙏

**Comment by kouloumos** [comment]
The logic mentioned here was initially extracted to `ComputeTimeSmart` with https://github.com/bitcoin/bitcoin/pull/9369 and the issue was later fixed with https://github.com/bitcoin/bitcoin/pull/20591. See https://github.com/bitcoin/bitcoin/issues/11703#issuecomment-1205701710 for more details.

**Comment by MarcoFalke** [comment]
Ok, closing for now. Can be reopened if the fix didn't work.
