### ISSUE TITLE
Remove TX priority and free transaction area from mempool, block creator

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#6675]
It was noted on #bitcoin-dev that many simplifications arise from removing the complex, dual-policy aspects of priority-based low fee transactions on policy estimation, block template creation and mempool code. This change updates Bitcoin Core to relay purely based on fee/kb rate, removing the concepts of priority and free transactions from the codebase.

fSendFreeTransactions, fLimitFree and similar controls have been operating in the field defaulting to fee-based choices already.

This change should make other changes such as @pstratem 's work to cap the mempool size dynamically much easier.

An example implementation exists (#6405) at https://github.com/jgarzik/bitcoin/tree/2015_remove_tx_priority
with the following notes/caveats:
- Status: A large change, lightly tested
- Transaction fee deltas are preserved - thus TX "priority" remains to some extent
- Arbitrary policies may be implemented via fee deltas
- prioritisetransaction RPC call continues to work, by adjusting the fee.
- needs focused review in the area of wallet, to ensure IsMine() transactions work fine through reorgs

**Comment by ABISprotocol** [comment]
Note: please see [this comment](https://github.com/bitcoin/bitcoin/pull/6584#issuecomment-140925164), related... am hoping that #6557 stuff gets merged along (including, I hope, https://github.com/sipa/bitcoin/commit/6498673f99da9976df170052648ff2f0026210d2) before this issue goes to pull request, etc.

**Comment by morcos** [comment]
I'm in favor of simplification, but I'd want to think carefully before totally abandoning priority as a useful metric.  For instance, unlike fees, its not something miners can produce freely if its required in order to stuff blocks (obviously a different usage than at present).

**Comment by jonathancross** [comment]
FYI: I believe @morcos has completed most of this in https://github.com/bitcoin/bitcoin/pull/7730

The concept of free / "priority" transactions is [deprecated in 0.14.0](https://github.com/bitcoin/bitcoin/pull/9179).

**Comment by luke-jr** [comment]
@jonathancross Hard NACK on removing from block creator. It is still used today, and should be encouraged for more miners to use tomorrow. (Note that it is no longer about "free" transactions.)

**Comment by morcos** [comment]
@jonathancross Correct that priority transactions are deprecated in 0.14.0.  But vestigal functionality still remains and can be optionally enabled.   This is scheduled to be removed completely for 0.15.0.
