### ISSUE TITLE
PROCESSMESSAGE: INVALID MESSAGESTART 44version 

### ISSUE THREAD

**Issue by Rav3nPL** [bitcoin/bitcoin#6676]
I have alot of it in my log.
I added:
```
pfrom->fDisconnect = true;
Misbehaving(pfrom->GetId(), 100);
```
in main.cpp where this error is thrown (so I ban those nodes), but nodes still try to connect.

**Comment by laanwj** [comment]
You get this error if nodes send an invalid packet. It's harmless, though spammy.

**Comment by sonmailphan1102** [comment]
![image](https://cloud.githubusercontent.com/assets/14301245/10125760/c07ebec4-65aa-11e5-81cb-64b24904bf59.jpg)

**Comment by laanwj** [comment]
See #6809
