### ISSUE TITLE
ZMQ fails to static link on Windows

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#6681]
See https://github.com/bitcoin/bitcoin/pull/6103#issuecomment-99272898 by @theuni 

"Note, however, that the windows build currently fails because zeromq refuses to static-link with mingw. I chose to leave this broken rather than disabling the windows build because we'll have to come up with a plan, even if it's just to explicitly disable it there."

**Comment by fanquake** [comment]
Should have been fixed in #8238
