### ISSUE TITLE
ZMQ depends build not working

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#6682]
"another issue with that 0mq commit is the depends build for zmq is not working ...
 packages_linux variaable inside packages.mk has not been passe through to depends/Makefile
 neither packages_darwin ... but I didn't test that as I'm on linux" - moa on IRC

**Comment by jonasschnelli** [comment]
Confirmed. Travis builds without zmq support: https://builds.jonasschnelli.ch/pulls/6103/ https://builds.jonasschnelli.ch/pulls/6103/build-linux.log
