### ISSUE TITLE
'Confirm send coins' dialog shows incorrect amount

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#6683]
I tried sending 50 BTC. The confirmation dialog told me that was 000 025 uBTC. It seems to be missing the first two digits:

![screenshot from 2015-09-16 11 49 33](https://cloud.githubusercontent.com/assets/573356/9914976/5c9c080c-5c69-11e5-942d-47bcb9cab70d.png)

I built from commit 536207f3167daad1fa3d60a1de7d9cb55db28ac9
Date:   Fri Sep 4 17:03:24 2015 +0200

Edit: it appears to work fine for smaller amounts:

![screenshot from 2015-09-16 11 58 41](https://cloud.githubusercontent.com/assets/573356/9915155/58d09ff2-5c6a-11e5-8ceb-27378fd88da8.png)

**Comment by laanwj** [comment]
Ugh.

**Comment by jonasschnelli** [comment]
Confirmed.
Will work on a fix soon.

<img width="540" alt="bildschirmfoto 2015-09-18 um 09 41 13" src="https://cloud.githubusercontent.com/assets/178464/9954446/7a01c5fe-5de9-11e5-8ba1-ffc04d8600a2.png">
<img width="540" alt="bildschirmfoto 2015-09-18 um 09 41 34" src="https://cloud.githubusercontent.com/assets/178464/9954447/7a36823a-5de9-11e5-9799-bdd992379ecf.png">
<img width="540" alt="bildschirmfoto 2015-09-18 um 09 41 00" src="https://cloud.githubusercontent.com/assets/178464/9954450/7a43b19e-5de9-11e5-8f41-bb56001db4fd.png">
<img width="540" alt="bildschirmfoto 2015-09-18 um 09 40 30" src="https://cloud.githubusercontent.com/assets/178464/9954449/7a3ddcd8-5de9-11e5-8213-373d8e9f3642.png">

**Comment by jonasschnelli** [comment]
Bug introduced in https://github.com/bitcoin/bitcoin/pull/4167
It's very likely a QT/display bug. You can copy'n'paste the text out of the QMessageBox and you will see the missing number in the pasted text.

**Comment by laanwj** [comment]
Fixed by #6694 (also backported for next 0.10/0.11 release)

**Comment by ongygy2000** [comment]
ESTE GRESALA
