### ISSUE TITLE
LoadExternalBlockFile is missing locking

### ISSUE THREAD

**Issue by morcos** [bitcoin/bitcoin#6691]
LoadExternalBlockFile accesses mapBlockIndex without any locks.  But mapBlockIndex could be in the process of being modified.  The fImporting flag should protect from a p2p message causing a modification, but submitblock can be modifying mapBlockIndex at the same time as LoadExternalBlockFile is reading it.

In addition LoadExternalBlockFile calls ReadBlockFromDisk which really needs some of the variables in CBlockIndex which are accessed by GetBlockPos to be protected.  All other reads of them happen to be protected by cs_main.

**Comment by morcos** [comment]
A related, but somewhat separate issue is that during reindexing it should not be possible to write data to the block files. The database of which files contain which blocks and where space exists for new blocks to be written is still in the process of being created. A submitblock RPC call during a reindexing seems like it would cause significant problems.

**Comment by MeshCollider** [comment]
I believe this was resolved in https://github.com/bitcoin/bitcoin/pull/11041
@morcos is your second comment still an issue, and if so would you like to open it as a separate issue thread and close this one?
