### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by dcousens** [bitcoin/bitcoin#6697]
Thoughts on adding https://github.com/blog/2051-protected-branches-and-required-status-checks?

**Comment by dexX7** [comment]
That's a really cool feature!

After a (legit) forced push, there is even a hint:

![remember](https://cloud.githubusercontent.com/assets/5836089/9975555/12ea6100-5ec0-11e5-89dd-b48988f655a5.png)

And once the guard is enabled, it's visible to anyone:

![lock](https://cloud.githubusercontent.com/assets/5836089/9975542/c0ad8ba6-5ebf-11e5-8e13-ca97e21acc6e.png)

This is the message returned, when trying to force a push to a locked branch:
```
/tmp/protected-branch-test$ git push origin master -f
Counting objects: 1, done.
Writing objects: 100% (1/1), 205 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to a protected branch
To https://github.com/dexX7/protected-branch-test.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/dexX7/protected-branch-test.git'
```

And if the CI tests fail, merges via git web, or command-line are blocked as expected.

I tested it with the `github-merge.sh` script:
```
Type 'push' to push the result to git@github.com:dexX7/protected-branch-test, branch master. push
Counting objects: 1, done.
Writing objects: 100% (1/1), 910 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is failing
To git@github.com:dexX7/protected-branch-test
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:dexX7/protected-branch-test'
```

The guard can be disabled at any time.

**Comment by laanwj** [comment]
Ok, tried enabling this for all branches.

**Comment by dcousens** [comment]
@laanwj awesome!
Out of interest, did you just stop force pushing or did you enable status checking also?

![all the boxes](https://cloud.githubusercontent.com/assets/121766/9998836/1859280e-6048-11e5-8c5f-721175d15a51.png)

**Comment by gmaxwell** [comment]
We do not use github infrastructure for merging as it is incompatible with digital signatures (for the obvious reasons.)

**Comment by laanwj** [comment]
I only blocked force-pushing for now. I'm not convinced that making status checks mandatory will work with our custom merge script, as @gmaxwell says.

**Comment by dcousens** [comment]
@laanwj :+1:
