### ISSUE TITLE
GetTempPath is insecure

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#6701]
A number of standards (C89, POSIX, etc) had similar functions and people quickly learned it is not secure to generate temporary filenames until they are confirmed created (not merely opened). For example, an attacker may create symlinks in a race pointing to an arbitrary file the user owns that he wishes to corrupt. Boost may guarantee a unique filename, but there is a split-second before we open that file for an attacker to set up a link.

This was fixed by mkstemp which ensures the file is newly created securely. We should do something similar.

**Comment by fanquake** [comment]
Should have been closed by #7667 ?

**Comment by laanwj** [comment]
Well we still use the function, albeit only in testing. Interfering with test results on a multi-user system is such a minor concern I agree it doesn't really warrant keeping open an issue.
