### ISSUE TITLE
Assertion failure in MemPool / UpdateState during shallow reorganisation

### ISSUE THREAD

**Issue by 0x9F** [bitcoin/bitcoin#6716]
Running master at head e59d2a80f9167031521d882394a08b02fa9d0343 

During some bug hunting, a block at depth 8 is invalidated. 

    $ bitcoin-cli invalidateblock 00000000000000000d977244d6c63a17b94ec8a9795a3cbb9c8d10a25e4783bb
    'bitcoind..' terminated by signal SIGABRT (Abort)

debug.log:

    UpdateTip: new best=000000000000000011aa05dca2667cc82d039b43d6177265890e0008e7cd3d26  height=375883  log2_work=83.385907  tx=85158798  date=2015-09-24 06:07:30 progress=0.999985  cache=3.3MiB(1021tx)
    UpdateTip: new best=00000000000000001026cf3108930888f16819de33eb59135bf61016174bf7f5  height=375882  log2_work=83.385877  tx=85158797  date=2015-09-24 06:06:54 progress=0.999984  cache=3.3MiB(1022tx)
    UpdateTip: new best=000000000000000010f255445ce069afea63a80d48aae4ab7a26465a4cb5742e  height=375881  log2_work=83.385848  tx=85158704  date=2015-09-24 06:06:37 progress=0.999984  cache=9.9MiB(1365tx)
    UpdateTip: new best=00000000000000000a6df102f64d76fada6c31f5a3cdc8a20412a5625944789d  height=375880  log2_work=83.385819  tx=85158125  date=2015-09-24 05:59:52 progress=0.999979  cache=22.3MiB(3277tx)
    Assertion failed: (int64_t(nSizeWithDescendants) > 0), function UpdateState, file txmempool.cpp, line 279.

**Comment by sipa** [comment]
Try #6715 please?

**Comment by 0x9F** [comment]
That works.
