### ISSUE TITLE
Block index corruption

### ISSUE THREAD

**Issue by gerbilOFdoom** [bitcoin/bitcoin#6727]
If a computer shuts down while bitcoin core is running the entire block index is corrupted and requires reindexing from day 0. This process, at least for my computer, takes more than 10 hours.

I'm not familiar with the code involving the filesystem, however there are methods that could be used to cache data temporarily and  write to the disk in a safe way such as that only a small portion of data might be corrupted during power loss.

This could be related to issue #5865

**Comment by sipa** [comment]
Bryson: we very extensively use caching, and only write data to disk when
all data it depends on is also written, synchronously.

When this error occurs, it is LevelDB (the low-level key value store we
use) that reports a corruption, which is something that it is designed to
withstand. Either this means a bug in LevelDB, in the operating system, or
in the hardware.

Or something we don't know of course...

Just to make it clear: the software is designed to not cause corruption
during crashing. Personally, I have never ever seen a corruption, even when
power loss occurs during synchronization. That doesn't mean there is no bug
of course in some situations, but it's not as simple as changing the write
pattern.

**Comment by gerbilOFdoom** [comment]
Okay. What information can I provide to help diagnose the cause?

**Comment by sipa** [comment]
First of all: what error are you getting, or what problem do you observe?

**Comment by gerbilOFdoom** [comment]
When I restart bitcoin core after a system crash (usually power outage), the block chain must be reindexed - an overnight process.

Next time it happens I'll leave all the files as they are and zip them up for you to look at, if you'd like.

**Comment by laanwj** [comment]
Does this happen on Windows? If so, this issue is a duplicate of #5610.

**Comment by gerbilOFdoom** [comment]
This happens on Windows 10, yes

**Comment by gerbilOFdoom** [comment]
Duplicate of #5610
