### ISSUE TITLE
OS X Build on Travis fails on downloading Clang

### ISSUE THREAD

**Issue by JeremyRand** [bitcoin/bitcoin#6738]
Steps to Reproduce:

1. Make a fork of Bitcoin's repo.
2. Enable Travis CI on that fork.
3. Push the latest Bitcoin code in master to that fork.
4. Wait for build to finish.

Expected Results:

The builds should all pass.

Observed Results:

The OS X build script tries to download https://bitcoincore.org/depends-sources/clang+llvm-3.3-amd64-Ubuntu-12.04.2.tar.gz .  This file doesn't exist on the https://bitcoincore.org server, and the resulting HTTP 404 error causes the build to fail.

Notes:

I suspect that this file is cached by Travis, which is why the builds appear to pass on the official repo's Travis (i.e. the file probably was there in the past and got cached).

A full example build where it failed is at https://travis-ci.org/JeremyRand/namecore/builds/82854029 .  (If it's not clear, this repo is a Namecoin repo but the branch in question is identical to upstream Bitcoin.  It happened to be easier for me to push a new branch to the Namecoin repo than to enable Travis CI on a new Bitcoin fork repo.)

**Comment by theuni** [comment]
Fixed. Thanks for the report. Looks like the llvm site is having trouble today.

Though this would've been a problem for Bitcoin as well eventually, Namecoin shouldn't depend on Bitcoin's internal hosting. Ideally you'd be good neighbors and setup your own mirror :)

**Comment by JeremyRand** [comment]
@theuni Namecoin generally tries to keep as few differences between itself and Bitcoin's code as possible -- diverging widely from Bitcoin's code was responsible for problems a couple years ago.  Is there documentation on how to change the mirror URL without making any invasive changes to the build scripts?  We definitely would like to be good neighbors, we just weren't sure of how to go about doing it.  (If this is too off-topic for this ticket, let me know and I'll bring it up somewhere else.)

**Comment by theuni** [comment]
@JeremyRand It's off-topic, but I won't hold it against you since you're being helpful :)

See: [here](https://github.com/bitcoin/bitcoin/blob/master/depends/README.md), specifically ```FALLBACK_DOWNLOAD_PATH```.

Since it's overridable, you should be able to export a new value in your travis config. Something like:

```yaml
env:
  global:
    - FALLBACK_DOWNLOAD_PATH = https://namecoincore.org/depends-sources
```

**Comment by JeremyRand** [comment]
Thanks @theuni.  I'll see if we can do that.  (Can't make promises on how quickly it will get done, as we're kind of overbooked lately -- but hopefully soon.)

**Comment by laanwj** [comment]
Looks solved, closing
