### ISSUE TITLE
EXCEPTION: NSt8ios_base7failureE non-canonical ReadCompactSize() bitcoin in ProcessMessages()  

### ISSUE THREAD

**Issue by mkabatek** [bitcoin/bitcoin#6746]
I have a standard build of bitcoin core 11.0. It has been running for months, and all the sudden it is throwing the following exception. What causes the following error?

    {
    "version" : 110000,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 0.01182943,
    "blocks" : 377077,
    "timeoffset" : 2,
    "connections" : 43,
    "proxy" : "",
    "difficulty" : 60813224039.44034576,
    "testnet" : false,
    "keypoololdest" : 1415846170,
    "keypoolsize" : 100,
    "unlocked_until" : 0,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    "errors" : "EXCEPTION: NSt8ios_base7failureE       \nnon-canonical ReadCompactSize()       \nbitcoin in ProcessMessages()       \n"
    }

**Comment by pstratem** [comment]
One of the peers you are connected to sent you garbage.

There's no actual error.

**Comment by mkabatek** [comment]
Thank you.

**Comment by dexX7** [comment]
I was notified about this exception, and I think this issue should be reopened.

Even if it is not a bad state, it appears to cause quite a bit of confusion, and a more user-faced message should be written to the log.
