### ISSUE TITLE
Setting an invalid proxy in GUI settings prevents program from starting

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#6749]
Catch 22:
```
<arnep> hey guys i need some help, pls.
<arnep> trying to open bitcore, "error proxy adress 0.0.0.0 3888
<arnep> so i can't open the damn program
<buZz> oh you're using a proxy?
<buZz> maybe try disabling that
<arnep> can't get in the program, where i put it o
```

**Comment by sipa** [comment]
Bitcoin Core or bitcore?

**Comment by laanwj** [comment]
Bitcoin Core.

Resolved this by making him remove the Bitcoin-Qt structure using regedit. Would be handy to have a command-line flag to reset the options at start.

**Comment by MarcoFalke** [comment]
> Resolved this by making him remove the Bitcoin-Qt structure using regedit. Would be handy to have a command-line flag to reset the options at start.

Wouldn't `-proxy=127.0.0.1:19999` overwrite the option at start?

**Comment by jonasschnelli** [comment]
>> Resolved this by making him remove the Bitcoin-Qt structure using regedit. Would be handy to have a command-line flag to reset the options at start.

> Wouldn't -proxy=127.0.0.1:19999 overwrite the option at start?

Good point. It would not overwrite the setting (different layer), but temporarily allow to start bitcoin-qt and allow to change/reset the setting over the GUI.

**Comment by MarcoFalke** [comment]
Is there any priority when qt parses the args and config and overwrites the other?

E.g.

* `-paytxfee` **is overwritten** by qt
* `-proxy` **overwrites** qt

**Comment by jonasschnelli** [comment]
It uses `SetSoftArg()` = `Set an argument if it doesn't already have a value` for some shared parameters like `-dbcache`, `-par`, `-spendzeroconfchange`, `-upnp`, `-listen`, `-proxy`, `-onion` and `-lang`.

This means, the GUI settings *can't* override the command line startup or bitcoin.conf arguments.

**Comment by MarcoFalke** [comment]
Oh, it's `updateGlobalFeeVariables()` which does the overwrite. (Which it shouldn't do)

**Comment by laanwj** [comment]
The priority for settings is *supposed* to be (from highest to lowest priority):

- Command line
- `bitcoin.conf`
- QSettings (in case of UI)
- Base defaults

**Comment by laanwj** [comment]
For anyone who ends up here looking for the registry keys used by bitcoin-qt's settings, these are the following:
```
HKEY_CURRENT_USER\Software\Bitcoin\Bitcoin-Qt
HKEY_CURRENT_USER\Software\Bitcoin\Bitcoin-Qt-testnet
```
