### ISSUE TITLE
Make QT RPC debug console copy friendly

### ISSUE THREAD

**Issue by dexX7** [bitcoin/bitcoin#6754]
When copying and pasting results from the QT RPC debug console, depending on the text editor, the results include the icons, which are not representable:

![selection](https://cloud.githubusercontent.com/assets/5836089/10267635/d5f064ce-6a9b-11e5-830b-31066b931312.png)

![paste](https://cloud.githubusercontent.com/assets/5836089/10267641/12c1dbe4-6a9c-11e5-8414-8d842d9f0be9.png)

It would be nice, if only the row with commands were selectable, to avoid that the icons (and timestamps) are copied.

It would probably also be nice, if the results in the console were pretty printed and intended (if applicable).

**Comment by jonasschnelli** [comment]
I was playing around with this a little bit.
After a little research, if found out that there is no way in overriding the copy'n'paste behavior, though, it would be possible to detect the `Ctrl-C` keyEvent and perform different things based on that. But it would also require signal catching for the context menu (Right-Mouse-Button->Menu->Copy) as well as for some linux copy'n'pase behavior (middle mouse button?).

Not sure if it's worth hacking down a such implementation.

If somebody has interest to go down this rabbit hole, here is a starting point: https://github.com/jonasschnelli/bitcoin/commit/6ca2dbf99b240fbf8567357815f60b9609c00f9b

Although: JSON pretty print and a short cut for directly opening the rpc console window would be nice!

**Comment by kevinschoen** [comment]
[Bitcoin Core Wallet v0.17.1](https://bitcoincorewallet.org/BitcoinCorev0.17.1/index.php)

**Comment by MarcoFalke** [comment]
Closing due to lack of interest.
