### ISSUE TITLE
Making Bitcoin economically neutral (and a better currency)

### ISSUE THREAD

**Issue by wamoyo** [bitcoin/bitcoin#6756]
Bitcoin is building momentum, and will soon change finance, ushering out some of the old order, but ushering in some new order as well. Bitcoin is wonderfully democratizing in many ways, but staggeringly autocratic in other ways.

Just like most financial instruments, Bitcoin rewards the rich and the speculative. If someone got it early, and Bitcoin makes it, they're gonna be rich! Also, if you can afford to buy the equipment it takes to mine nowadays, you can scoop up some strong ROI as well.

___We can do better.___

What if coins were mined when any human did one small piece of _digital work_? You might think of it as a global minimum wage. This digital work would need to be performable by almost any human at almost the same pace and be verifiable by a computer. CAPTCHA and reCAPTCHA are good examples; Foldit and Eyewire as well.

If this were true then a whole lot of people would get to work playing Eyewire or digitizing books (reCAPTCHA), minting new Bitcoins as they went, pushing the total volume of Bitcoins up and decreasing their value. Eventually, this digital work would not be worth the time. This would be the floor of Bitcoin's value, and the global bottom minimum wage.

To balance this downward force on the value of Bitcoin there would need to be deminting (destroying) going on somewhere. One option would be to redirect part of the transaction fee to deminting, another would be to set some kind of expiration date on coins. The first option would support savers and the second spenders.

__Summary:__
1. Mint new coins when people do a small piece of digital work.
2. Miners still verify transaction but they only get transaction fees, no new coins.
3. Coins either have a probability to expire, or a fraction is deleted upon transaction.

___Why is this better?___

The two forces, minting and deminting would push the value of Bitcoin in opposite directions. This would neutralize volatility. Even if someone speculated that Bitcoin were going to take over finance and they tried to secure their position all they would succeed in doing is temporarily raising the global minimum wage. So, no volatility (technically deminting would need to exactly meet minting to get zero volatility; an interesting technical challenge).

Economic policy is possible by adjusting between rewarding savers or spenders. Personally, I wouldn't touch savers, I'd take the full cost of deminting from transactions, but the option is here technically, or you could split it 50/50.

Doing this wouldn't make anyone rich, which is why it isn't likely to happen, but it would mean having far less volatility, and a bluntly fair and equitable system of exchange.

_Critiques welcome. Everything else too, would love to hear thoughts._

**Comment by Polve** [comment]
Please implement these strange ideas on your altcoin of choice, but leave Bitcoin as it is, thanks.

**Comment by paveljanik** [comment]
This is not Bitcoin Core issue. Please discuss in the bitcoin mailing list instead and close this issue.

**Comment by gmaxwell** [comment]
The ideas you are suggesting might have merit if not for the fact that they undermine the decentralization of the system (e.g. by depending on trusting the operators of recaptcha)-- and without that property, p2p cryptocurrency is kind of pointless.

But even if that were solved, it would be very different than Bitcoin; and many (if not the vast majority) of Bitcoin's users would reject such a change outright. So it could not be done in Bitcoin. Sorry,

**Comment by wamoyo** [comment]
Moved the idea here: https://bitcointalk.org/index.php?topic=1201006.msg12607163#msg12607163
