### ISSUE TITLE
Ubuntu PPA is missing 15.10 version

### ISSUE THREAD

**Issue by nextgenthemes** [bitcoin/bitcoin#6757]
Ubuntu 15.10 is currently in beta and will be released in a few days at the 22. October. It would be nice to have a Bitcoin version in the PPA for it.

**Comment by paveljanik** [comment]
Please report to Ubuntu.

**Comment by TheBlueMatt** [comment]
This is not an ubuntu bug - we actively encourage people to not use the Ubuntu packages due to Debian packaging guidelines often requiring that they ship old versions that break consensus.

**Comment by nextgenthemes** [comment]
Why should I report to Ubuntu, its some Bitcoin guy who maintains this PPA I guess. I think I even reported a similar thing a long time ago.

**Comment by nextgenthemes** [comment]
Indeed I did in #5129 and it got fixed. Ping @TheBlueMatt as he might still be the maintainer.

**Comment by TheBlueMatt** [comment]
I didnt want to do this too early in the beta phase, not to mention kept forgetting when I was at the computer with my PGP key on it...anyway, its building now, should be available for sync very soon.

**Comment by nextgenthemes** [comment]
@TheBlueMatt Thanks.

I am not a expert, I am not sure how Beta Freeze, User Interface Freezy, Final Freezy relate to Bitcoin. Not necessary wanted you to do it immediately. You may indeed should have waited till the Final Freeze at the 15. and take this as a heads up https://wiki.ubuntu.com/WilyWerewolf/ReleaseSchedule I don't know.

Anyway, I installed it from the PPA and its working and does not have the floating tray icon bug the manual downloaded version has. Thanks.

**Comment by laanwj** [comment]
Looks like these are available now: https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin
