### ISSUE TITLE
Build: circular dependency for libunivalue

### ISSUE THREAD

**Issue by theuni** [bitcoin/bitcoin#6778]
To get this fixed, we first need a change in upstream univalue. See https://github.com/jgarzik/univalue/pull/13

Assuming that's accepted, next time we sync up with univalue, we'll need this change:
https://github.com/theuni/bitcoin/commit/c2bfdddf6ccdecd78fc09c262bab247cf9b29165

That should take care of the problem.

**Comment by jonasschnelli** [comment]
Thanks for looking at this.
ACK @ https://github.com/theuni/bitcoin/commit/c2bfdddf6ccdecd78fc09c262bab247cf9b29165

**Comment by jamesob** [comment]
+1, seeing this issue also:
```
 $ make

Making all in src
make[1]: Entering directory `/home/job/Dropbox/code/bitcoin/src'
make[2]: Entering directory `/home/job/Dropbox/code/bitcoin/src'
make[3]: Entering directory `/home/job/Dropbox/code/bitcoin/src/univalue'
make[3]: *** No targets specified and no makefile found.  Stop.
make[3]: Leaving directory `/home/job/Dropbox/code/bitcoin/src/univalue'
make[2]: *** [univalue/lib/libunivalue.la] Error 2
make[2]: Leaving directory `/home/job/Dropbox/code/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/job/Dropbox/code/bitcoin/src'
make: *** [all-recursive] Error 1
```

**Comment by laanwj** [comment]
@jamesob that's a matter of re-running ./autoconf.sh and ./configure
