### ISSUE TITLE
0.11.0-win64 unresponsive ("Focus + Enter" workaround)

### ISSUE THREAD

**Issue by vayvanne** [bitcoin/bitcoin#6784]
Hi,
just noticed that my 0.11.0-win64 full node running on laptop becomes unresponsive, drops connections (both p2p and rpc), hogs memory (may take up to 4GB out of total 6).
![bitcoind](https://cloud.githubusercontent.com/assets/12157216/10380123/ee88bc9a-6e09-11e5-9df1-dcfd6d3ac8a1.png)
It restores normal operation after a while but then again becomes unresponsive. I restarted bitcoind and even spent a few days to reindex DB, with no luck. Does this mean that my laptops 5400 RPM HDD is not fast enough to run full node? Or does it mean that it is a bug? bitcoin.conf is almost empty. Only rpc username, password and non-standard network port number there. Thanks for any clues.
vay

**Comment by Diapolo** [comment]
IMHO a 5400 RPM HDD is not ideal to be honest... it was smoother with versions before 0.11?

**Comment by vayvanne** [comment]
It was fine until few days ago. I notice that hangup happens when bitcoind begin to read chainstate .ldb files on about 500Kb/s speed. That takes a long, processor is not loaded much, no response to p2p connections, rpc connects timing out... Another scenario is when bitcoind starts to write to .ldb files and becomes unresposive until finished. In that case it fully loads one of processor cores and memory use drops at the end of this process.
I am solo mining using cgminer 4.9.2, so this may be also the involved though no changes if I switch to the backup pool temporarily.
Will set DB cache size relatively small just for the case if the reason is that my laptop processor core is not fast enough to deal with huge buffered data timely.
Thanks for response.

**Comment by sipa** [comment]
I expect that the problems now are from having a huge mempool. You can
increase the minimum relay fee, or help test the mempool limiting patches
(whicb likely will go into 0.12).

**Comment by vayvanne** [comment]
@sipa getmempoolinfo gives 271MB on my laptop so far and increasing. I see a lot of "inputs already spent" and "free transaction rejected by rate limiter" in the debug.log. on the other server machine it is more than 1GB. really seems as a DDoS to network.

**Comment by laanwj** [comment]
Do you still get this with 0.11.1?

**Comment by vayvanne** [comment]
No. Thank you.

**Comment by vayvanne** [comment]
I am recalling my last answer. I did run with default relay fee and it freezes just like the 0.11.0. Restarting now with -minrelaytxfee=0.0001 will report back after a while.

**Comment by vayvanne** [comment]
With -minrelaytxfee=0.0001 flight is normal so far. -getmempoolinfo gives:
{
    "size" : 2130,
    "bytes" : 33420250
}

**Comment by vayvanne** [comment]
Increased -minrelaytxfee to 0.0003, as the issue persisted (with 0.0001).

**Comment by vayvanne** [comment]
The issue still persists even with .0003 :) Right now it is reading through all .ldb-s with total 300-500 kB/s which is not a lot for laptop HDD but the daemon is unresponsive to bitcoin-cli getinfo nor to API calls from cgminer. Mem usage is 1.448 GB (started with -dbcachesize=1024). It returns to normal operation only after a while. And then hangs again. I may be wrong and this is just accidental but always when I see it hanged up I see a connection from host naval.nvcube.net which is XT:0.11.0B with an incoming traffic more that from other hosts. Just a blind suspicion, nothing more.

**Comment by NicolasDorier** [comment]
Not sure if related, but I also have time to time unresponsive node.
If you are running bitcoind in a command line windows, can you go on the windows and hit "Enter" ?

Agreed, this sound very stupid, but it happened to me several time where hitting Enter in the command line windows of bitcoind just unstuck it... I suspect it was a hardware problem though, I could not replicate on another box.

For information, yestersday a 0.11 node of mine with 1000 satoshi of txminrelayfee crashed after climbing astronomically high in memory. Using 0.0005 btc fixed the issue though.

**Comment by vayvanne** [comment]
Today it hanged up for not a long time on the dedicated server with 8 core xeon and 16GB RAM. Increased minrelaytxfee to 0.0003 from 0.0001. Seems DDoS is increasing.

**Comment by NicolasDorier** [comment]
I'm happy I'm not alone where the "Focus + Enter" unstuck the node, just can't get my head around how it might be possible... AFAIK bitcoind does not read the keyboard input at all...

**Comment by vayvanne** [comment]
Issue still persist even with 0.0005. Not that long as in the past and less frequently (once in a few days) though. Increasing to 0.0008.
