### ISSUE TITLE
Whats up with the trivial tree, with style and the UI?

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#6786]
IMHO our codebase get's uglier with nearly every single (bigger) pull... why is no one focused anymore on the style/readability? Is it all about features? Is there no review time? Is the Linux kernel also that ugly in terms of include ordering, silly new-lines, wrong header naming in the ifdefs or as header end comments, wrong or missing indentations, wrong style for functions (where brackets aren't in a new line) etc... at least I've lost my motivation to contribute to that "mess" as even simple GUI pulls take forever to get in :-/.

**Comment by jonasschnelli** [comment]
@Diapolo: code style is something that can be done by `clang-format` and co. and does therefore not get the main attention. Bitcoin core code gets cleaner and not uglier IMO.

I appreciate your cleanup pulls. But you often mix code-style changes with functional changes. That makes it hard(er) to review. And if you are working on other PRs, you need to decide if you do review one of your code-cleanup-PR or work on scalability-, feature- or refactoring-PRs. I think contributors often decide for the later.

I would appreciate keeping "drama"-issues on a minimum. Working on a project like Bitcoin-Core requires extrem patience and a total focus on "emotion-free" tech-debate/contribution and discussions.

**Comment by laanwj** [comment]
The goal of peer review is to find critical issues, bugs, unexpected behavior, serious documentation issues.

You seem to be looking at everything through a magnifying lens. These have been a drama-filled months, and no, small code style details don't rate very highly in my list of priorities.

Code organization on a higher level, e.g. modularization and such is an important concern and  there is some work in that direction (eg see #6714).

> at least I've lost my motivation to contribute to that "mess" as even simple GUI pulls take forever to get in :-/.

Changes can go in very quickly if:

- They are focused on one goal
- They solve a clear issue, preferably one that has been filed on github, which there is interest in
- Code changes are localized and self-contained (small chance of regressions, minimizing conflict with other patches)
- Tests are added, and/or the OP if the issue confirm that his problem is solved

Many of your pulls have tended to be muddy, agree with what @jonasschnelli says. These that were clear and focused have been merged almost immediately.
