### ISSUE TITLE
onlynet=tor still using exits for seeds is confusing

### ISSUE THREAD

**Issue by zw** [bitcoin/bitcoin#6808]
I run some wallet-less listening nodes behind Tor, for fuzzies and occasional somewhat-private TX submission.  In this setup, minimising load on exits seems more important than having clearnet peers, so I use `onlynet=tor`.  To minimise room for leaks their network configuration also makes Tor their only window to the world.  They do get inbound connections through their onion services.  For reasons probably not relevant, they may be atypically peer-starved at times.

I see outbound connections to the seeds via exits:

```
2015-10-XX XX:XX:XX Bitcoin version v0.11.0.0-(the 0.11.0 tag from Github)
    (omit OpenSSL, directories)
2015-10-XX XX:XX:XX Using at most 125 connections (1024 file descriptors available)
2015-10-XX XX:XX:XX Using 0 threads for script verification
2015-10-XX XX:XX:XX scheduler thread start
    (omit RPC)
2015-10-XX XX:XX:XX Bound to X.X.X.X:8333
2015-10-XX XX:XX:XX AddLocal(XXXXXXXXXXXXXXXX.onion:8333,4)
    (omit cache config, LevelDB lines)
2015-10-XX XX:XX:XX No wallet support compiled in!
    (omit best chain)
2015-10-XX XX:XX:XX init message: Loading addresses...
2015-10-XX XX:XX:XX Loaded (several hundred) addresses from peers.dat  9ms
2015-10-XX XX:XX:XX init message: Done loading
2015-10-XX XX:XX:XX msghand thread start
2015-10-XX XX:XX:XX opencon thread start
2015-10-XX XX:XX:XX addcon thread start
2015-10-XX XX:XX:XX net thread start
2015-10-XX XX:XX:XX dnsseed thread start
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX Loading addresses from DNS seeds (could take a while)
2015-10-XX XX:XX:XX 0 addresses found from DNS seeds
2015-10-XX XX:XX:XX dnsseed thread exit
    (omit interspersed "receive version message", both with
     us=XXXXXXXXXXXXXXXX.onion:8333 and us=dotted quad)
2015-10-XX XX:XX:XX SOCKS5 connecting seed.bitcoin.sipa.be
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting dnsseed.bluematt.me
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting dnsseed.bitcoin.dashjr.org
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting seed.bitcoinstats.com
2015-10-XX XX:XX:XX SOCKS5 connected seed.bitcoinstats.com
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting bitseed.xf2.org
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting seed.bitcoin.jonasschnelli.ch
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting seed.bitcoin.sipa.be
2015-10-XX XX:XX:XX SOCKS5 connected seed.bitcoin.sipa.be
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting dnsseed.bluematt.me
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting dnsseed.bitcoin.dashjr.org
2015-10-XX XX:XX:XX SOCKS5 connected dnsseed.bitcoin.dashjr.org
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting bitseed.xf2.org
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting seed.bitcoin.jonasschnelli.ch
2015-10-XX XX:XX:XX SOCKS5 connected seed.bitcoin.jonasschnelli.ch
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connecting dnsseed.bluematt.me
2015-10-XX XX:XX:XX SOCKS5 connected dnsseed.bluematt.me
2015-10-XX XX:XX:XX SOCKS5 connecting bitseed.xf2.org
2015-10-XX XX:XX:XX SOCKS5 connecting XXXXXXXXXXXXXXXX.onion
2015-10-XX XX:XX:XX SOCKS5 connected XXXXXXXXXXXXXXXX.onion
    (usually stops attempting seeds ~30m after startup)
```

@laanwj says "if you have a proxy it [still] does AddOneShot(seed.host)" and I dimly recall something about an exception being required for bootstrap before Core had an onion seed list, otherwise bootstrap would go nowhere.  Even if the user is aware of that, the persistent attempted connections to the seeds for a while _after_ apparent `dnsseed thread exit` cause confusion (although maybe that peer starvation I mentioned is a prerequisite for getting confused).

Having healthy peer lists on these nodes already, I'm sure I can just use `dnsseed=0`, but I think it's worth making my existing configuration less surprising.  `onlynet=tor` really should mean "just onion peers", or be renamed, or have clearly documented exceptions, because smells like the the sort of thing that bites you down the road when new code or an unexpected use case comes along.

**Comment by TheBlueMatt** [comment]
You still have to bootstrap somehow. If your addrman has entries, it should be waiting 11 seconds before it bothers running the dnsseed connect stuff. We could maybe extend the 11 seconds if you set onlynet=tor, but I'm not sure what else you're suggesting be done?

**Comment by laanwj** [comment]
Right - it shouldn't connect to ipv4/ipv6 dnsseeds if `onlynet=tor`. That's surprising behavior.

It's also unnecessary, there are some hardcoded onion seeds in `src/chainparamsseeds.h` that it can use.

**Comment by TheBlueMatt** [comment]
I'm not actually sure we shouldn't connect to them - its rather easy for the hardcoded onion seeds to go down, then we're stuck with never being able to sync? We should maybe use the hardcoded nodes first and give ourselves more time to find a connection, but I'm not sure it should be turned off entirely.

**Comment by laanwj** [comment]
People *choose* to use onlynet=tor. It's not a default in any circumstances.
Yes, the consequence may be that it's harder to find peers, but the user should take that into account.

An preferable option would be to have one or more 'DNS seeds' (a misnomer in this case as no DNS is used, it's a one-shot node connection) on .onion as hidden service.

**Comment by TheBlueMatt** [comment]
Yea, a one-shot onion address is much better.

**Comment by laanwj** [comment]
I know at least some of the DNS seeds have Tor running (to scan .onion peers) - so adding a hidden service that redirects to their 8333 port would be a small step.
Ping @sipa @jonasschnelli

**Comment by TheBlueMatt** [comment]
Huh? You mean doing DNS-over-TCP to a .onion? Or do you suggest a new service for such a thing?

**Comment by sipa** [comment]
I think he means using a oneshot P2P connection to the onion address
(connecf, getaddr, wait for addr response, disconnect).

**Comment by TheBlueMatt** [comment]
Yes, but he said you connect to the DNS Seed over Tor. That makes no sense - the DNS Seeds are not designed to listen or provide addr message responses. Are y'all suggesting adding this?

**Comment by sipa** [comment]
If you 'connect' to a DNS seed over Tor, your exit node will resolve the
name for you, and forward the connection there, so you actually get a
connection to one of the *results* of the seed, not to the seeder itself.

**Comment by sipa** [comment]
... so the suggestion here is to just do oneshot connections to a few
hardcoded .onion addresses instead of actually using a seeder.

**Comment by TheBlueMatt** [comment]
Yes, that is what I thought we were talking about, hence why I was confused by @laanwj's mention of DNS seeds exposing their 8333 port...

**Comment by gits7r** [comment]
I agree we should make onlynet=tor do what it says: connect only to onion peers. If it cannot because it doesn't find any, or because the Tor instance is broken, or because the clock is skewed, or whatever, so be it. onlynet=tor is not on by default and it has a clear name, so whoever is using it knows what he's doing. 

@laanwj I am running 3 onlynet=tor full nodes for quite some time, and they have never connected to a clearnet peer as far as I was able to see. I use addnode=foo.onion in bitcoin.conf along with onlynet=tor so I am guessing that is why it has no problems bootstrapping.

Unfortunately Tor only supports resolving anonymously DNS A records at Exit node end. If it supported looking up of more types of records and validating DNSSEC signatures, we could add hostnames of onion peers in TXT records to the main hardocded clearnet (normal DNS) seed nodes and an onlynet=tor node would just take the onion hostnames from there and connect to them without actually establishing connections to the clearnet seed nodes. There is a proposal for this so this shouldn't happen too far way in the future, hopefully. Let me know if my onion nodes can help in any way.

**Comment by laanwj** [comment]
> If you 'connect' to a DNS seed over Tor, your exit node will resolve the name for you, and forward the connection there, so you actually get a connection to one of the *results* of the seed, not to the seeder itself.

OK I didn't know that. So it does a oneshot to a random peer.
Whoa, that certainly shouldn't bypass onlynet=tor.

**Comment by wodry** [comment]
At least, out of my point of view as a user, this dozens of messages in debug.log while bootstrapping are confusing/disturbing because they seem to be senseless when using onlynet=onion:
```
SOCKS5 connecting bitseed.xf2.org
ERROR: Proxy error: connection refused
```

**Comment by wodry** [comment]
Running 0.13.2 with onlynet=tor there are still these debug messages on startup.
AFAIK with onlynet=tor the node can only connect to .onion addresses, so it's obviously that connection attempts to hostnames of other TLDs fail.

```
12:34:26 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:34:47 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:34:54 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:34:59 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:35:19 ERROR: Error reading proxy response
12:35:33 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:35:53 ERROR: Error reading proxy response
12:35:56 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:36:12 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:36:27 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:36:47 ERROR: Error reading proxy response
12:36:50 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:36:56 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:37:11 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:37:27 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:37:31 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:37:52 ERROR: Error reading proxy response
12:38:12 Socks5() connect to dnsseed.bluematt.me:8333 failed: host unreachable
12:38:33 ERROR: Error reading proxy response
```

**Comment by Sjors** [comment]
With Tor v2 deprecation there's no longer any point in polling DNS seeds with `-onlynet=tor`, since they don't return v3 onion services.
