### ISSUE TITLE
Bitcoin seems to leak dynamic memory big time

### ISSUE THREAD

**Issue by wwortel** [bitcoin/bitcoin#6833]
After starting bitcoin as a daemon it takes about 1 GB of memory from the 3 GB my VPS has available.
But some 3 hours later is has occupied an additional 1 GB and this continues creeping down until only hardly anything has been left available.
Five hours after start: only 59MB left of initial free 2 GB. 

Environment:
VPS with 64 bit hardware and 32 bit Debian, compiler gcc 4.9.3
Recent libboost and libevent. No GUI as it runs on a Virtual Private Server.
Includes one wallet. Is limited to 50 external connections.
Home compiled bitcoin-master (12/10/2015, v 119900, protocol v 70011).
Have also tried the current 32 bit binary release. Same effect.
Is current in having the database with blocks (379012 15/10/2015).

Have seen reports in this sense before but it was discarded as an effect of getting the block database current. But that cannot be it. Are others seeing this and what can be done?

**Comment by sipa** [comment]
This is likely due to the recent high volume of transactions filling the
memory pool.

The recently released 0.11.1 versio  changes the default relay limit to
temporarily combat this. You can also change this in the config file or
command line.

For 0.12, a more thorough solution that limits the size of the mempool is
being worked on.

**Comment by MarcoFalke** [comment]
You can check the mempool with `getmempoolinfo`.

**Comment by dcousens** [comment]
If you don't want to upgrade (for whatever reason), AFAIK `-minrelaytxfee=5000` as a CLI or config option should put you line with https://github.com/bitcoin/bitcoin/pull/6793 as @sipa mentioned.

**Comment by wwortel** [comment]
thanks for your reactions and tips.
My setting was 'minrelaytxfee = 0.00001'. Will study the effect of increasing that and report.

**Comment by wwortel** [comment]
Have now for experiment restarted bitcoind with the option '-disablewallet'. Now memory usage is stable at ~ 6 % ! So something to do with the wallet is leaking memory it seems. Better than leaking BTCs but still quite unpleasant :-) Would like to use the wallet though.

**Comment by wwortel** [comment]
Have been experimenting with setting the option '-disablewallet' when restarting bitcoind.
With the wallet disabled have tried the tx relay fee at 1000 Satoshi and at 5000.
Effects:
In both cases memory usage stays in the 5-7  %MEM range as reported by 'top'. 
With 1000 S. setting CPU % time goes crazy, with 5000S. it stays at a few percent CPU after the initial minutes of resyncing. Will look again in a few hours but if memory creeps up it is at a much much slower rate than with the wallet active. So is the wallet software leaking memory?

**Comment by dcousens** [comment]
@wwortel probably best just to data dump of memory usage over time to show case if this is an actual issue,  and maybe compare with the different options.

**Comment by wwortel** [comment]
@dcousens:
Tnx. Have just written a little script and started it as 1 minute interval cron job to log %cpu,%mem,rss,size,sz,vsz  as defined in ps. Currently with 1 wallet and min. tx relay fee of 5.0E-5. Will later do the same without the wallet and show the results here.

**Comment by dcousens** [comment]
It looks like the graphs above don't agree with your initial statement?

> After starting bitcoin as a daemon it takes about 1 GB of memory from the 3 GB my VPS has available.
> But some 3 hours later is has occupied an additional 1 GB and this continues creeping down until only hardly anything has been left available.

3 hours later, only 1GB is still in use (~30%)?

**Comment by wwortel** [comment]
It depends on the amount of memory becoming available after having stopped bitcoind. That was more the first time than later times. As the VPS is live for other processes cannot / do not want to do a reboot all the time. First time it started from 2 GB given as available. Or is there a command to make any unused memory available again without a reboot? Doubt that it makes any difference. 1, 2, or three GB, bitcoind will eat it all. Setting the min. tx relay fee to 5.0 E-5 has not stopped this memory hunger.

**Comment by dcousens** [comment]
> Doubt that it makes any difference. 1, 2, or three GB, bitcoind will eat it all.

How are you setting these caps?   Can you show the data for the 3 GB case?  I'm not seeing this behaviour on my instance at all.

**Comment by wwortel** [comment]
Have just rebooted the VPS and it reports 2.9 GB free memory now with everything (httpd, bind9, sendmail, stunnel, saslauth) running except bitcoind. That 2.9 value is stable. W.r.t. the caps: did not set anything. 3 GB is what the VPS is provided with by the company that rents it to me. But it seems that running bitcoind, apart from taking all that memory, also creates a situation in which not all memory that bitcoind is reported to be using is released afterwards. It becomes like orphan memory. 
Will start bitcoind again and the %MEM will be logged every minute.

**Comment by wwortel** [comment]
Have restarted bitcoind without the start-stop-daemon option --background and am watching the messages it gives out. There are continuously messages of the kind:
receive version message: /BitCoinJ:0.12-SNAPSHOT/Satoshi:0.11.0/: version 70001, blocks=379431, us=127.0.0.1:8333, peer=308
and sometimes things like:
receive version message: /bitcoin-seeder:0.01/: version 60000, blocks=230000, us=<my-external-ip>:8333, peer=323
2015-10-18 10:53:37 receive version message: /bitnodes.21.co:0.1/: version 70002, blocks=379431, us=<my-external-ip>:8333, peer=324
After ~40 minutes it has already passed peer=400.
Is this normal behaviour or is something running away?

**Comment by pstratem** [comment]
did you modify the dbcache parameter?

**Comment by wwortel** [comment]
@pstratem: no, dbcache is unset in the .conf and hence its default. What puzzles me is the localhost origin of all these /BitCoinJ:0.12-SNAPSHOT/Satoshi:0.11.0/ 'receive version' messages. The ones that originate from my external ip address have varying names, the 127.0.0.1 ones always the same and very many of them.  
After 1 hour the %MEM is at 12%, starting from 5.8. and peer= has passed the 600 mark.

**Comment by wwortel** [comment]
As I cannot reproduce the original problem (after closing bitcoind all cache can be released and reused) I close this issue. It must have been an anomaly in the VPS.
