### ISSUE TITLE
Unable to build bitcoin in a VirtualBox running Debian

### ISSUE THREAD

**Issue by kapiliitr** [bitcoin/bitcoin#6869]
When I run ./bin/gbuild -c bitcoin=HEAD ../bitcoin/contrib/gitian-descriptors/gitian-linux.yml, I get the following error-
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:137:in `build_one_configuration'
        from ./bin/gbuild:270:in `block (2 levels) in <main>'
        from ./bin/gbuild:265:in `each'
        from ./bin/gbuild:265:in `block in <main>'
        from ./bin/gbuild:263:in `each'
        from ./bin/gbuild:263:in `<main>'

The following is the content var/build.log file-
+ set -e
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ umask 002
+ export OUTDIR=/home/ubuntu/out
+ OUTDIR=/home/ubuntu/out
+ GBUILD_BITS=64
+ GBUILD_CACHE_ENABLED=1
+ GBUILD_PACKAGE_CACHE=/home/ubuntu/cache/bitcoin-linux-0.12
+ GBUILD_COMMON_CACHE=/home/ubuntu/cache/common
+ MAKEOPTS=(-j2)
+ REFERENCE_DATETIME='2015-06-01 00:00:00'
+ REFERENCE_DATE=2015-06-01
+ REFERENCE_TIME=00:00:00
+ cd build/bitcoin
+ git reset -q --hard
+ git clean -q -f -d
+ cd build
+ WRAP_DIR=/home/ubuntu/wrapped
+ HOSTS='i686-pc-linux-gnu x86_64-unknown-linux-gnu'
+ CONFIGFLAGS='--enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++'
+ FAKETIME_HOST_PROGS=
+ FAKETIME_PROGS='date ar ranlib nm strip'
+ export QT_RCC_TEST=1
+ QT_RCC_TEST=1
+ export GZIP=-9n
+ GZIP=-9n
+ export 'TAR_OPTIONS=--mtime=2015-06-01\ 00:00:00'
+ TAR_OPTIONS='--mtime=2015-06-01\ 00:00:00'
+ export TZ=UTC
+ TZ=UTC
++ pwd
+ export BUILD_DIR=/home/ubuntu/build
+ BUILD_DIR=/home/ubuntu/build
+ mkdir -p /home/ubuntu/wrapped
+ test -n 1
+ export SOURCES_PATH=/home/ubuntu/cache/common
+ SOURCES_PATH=/home/ubuntu/cache/common
+ export BASE_CACHE=/home/ubuntu/cache/bitcoin-linux-0.12
+ BASE_CACHE=/home/ubuntu/cache/bitcoin-linux-0.12
+ mkdir -p /home/ubuntu/cache/bitcoin-linux-0.12 /home/ubuntu/cache/common
+ for prog in '${FAKETIME_PROGS}'
+ echo '#!/bin/bash'
+ echo 'REAL=`which -a date | grep -v /home/ubuntu/wrapped/date | head -1`'
+ echo 'export LD_PRELOAD=/usr/lib/faketime/libfaketime.so.1'
+ echo 'export FAKETIME="2015-06-01 00:00:00"'
+ echo '$REAL $@'
+ chmod +x /home/ubuntu/wrapped/date
+ for prog in '${FAKETIME_PROGS}'
+ echo '#!/bin/bash'
+ echo 'REAL=`which -a ar | grep -v /home/ubuntu/wrapped/ar | head -1`'
+ echo 'export LD_PRELOAD=/usr/lib/faketime/libfaketime.so.1'
+ echo 'export FAKETIME="2015-06-01 00:00:00"'
+ echo '$REAL $@'
+ chmod +x /home/ubuntu/wrapped/strip
+ for i in '$HOSTS'
+ for i in '$HOSTS'
+ export PATH=/home/ubuntu/wrapped:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/home/ubuntu/wrapped:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ cd bitcoin
++ pwd
+ BASEPREFIX=/home/ubuntu/build/bitcoin/depends
+ for i in '$HOSTS'
+ make -j2 -C /home/ubuntu/build/bitcoin/depends HOST=i686-pc-linux-gnu
make: *** /home/ubuntu/build/bitcoin/depends: No such file or directory.  Stop.

**Comment by josephbisch** [comment]
Can you provide any more information? Are you using KVM or LXC? What commit are you using for Gitian?

Did you try deleting and recreating the KVM or LXC image?

I wasn't able to reproduce this issue with KVM.

**Comment by kapiliitr** [comment]
ᐧ

On Thu, Oct 22, 2015 at 11:30 PM, Joseph Bisch <notifications@github.com>
wrote:

> Can you provide any more information? Are you using KVM or LXC? What
> commit are you using for Gitian?
>

I am using LXC as explained here
https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md#setting-up-the-gitian-image



> Did you try deleting and recreating the KVM or LXC image?
>
Yes, it doesn't work

**Comment by josephbisch** [comment]
I can't reproduce the issue with LXC either.

what happens if you run `ls inputs/bitcoin/` from your gitian-builder directory? Do you see `depends` listed among the files and directories listed?

**Comment by kapiliitr** [comment]
No
There is no depends directory in gitian-builder/inputs/bitcoin/
ᐧ

Regards,
Kapil Agarwal

**Comment by josephbisch** [comment]
What happens if you delete the bitcoin directory under inputs and try running gbuild again?

**Comment by kapiliitr** [comment]
Just to be sure, I have the following external packages in inputs directory

miniupnpc-1.5.tar.gz  osslsigncode-1.7.1.tar.gz
 wxWidgets-2.9.1.tar.bz2
miniupnpc-1.6.tar.gz  osslsigncode-Backports-to-1.7.1.patch
 wxWidgets-2.9.2.tar.bz2

Not sure if they are ever used or built or I am missing some package or
anything.

So, I removed the bitcoin folder, rebult the base-precise-amd64 image
and then ran ./bin/gbuild -c bitcoin=HEAD
../bitcoin/contrib/gitian-descriptors/gitian-linux.yml

Now I get the error-

make: Entering directory `/home/ubuntu/build/bitcoin/depends'
/bin/sh: 1: test: qtbase-opensource-src-5.5.0.tar.gz: unexpected operator
Fetching native_ccache...
wget: unable to resolve host address `samba.org'
wget: unable to resolve host address `bitcoincore.org'
make: ***
[/home/ubuntu/cache/common/download-stamps/.stamp_fetched-native_ccache-ccache-3.2.3.tar.bz2.hash]
Error 4
make: Leaving directory `/home/ubuntu/build/bitcoin/depends'

ᐧ

Regards,
Kapil Agarwal

**Comment by josephbisch** [comment]
I'm not sure about the miniupnpc, osslsigncode, or wxWidgets stuff. I think Bitcoin Core moved from wxWidgets to Qt a long time ago.

It does look like you are making progress though, because now you are able to enter the depends directory. But it appears you have networking problems in the LXC image, hence the unable to resolve host address messages.

You need to seed the sources cache before running gbuild. You download the sources on your host system (Debian running in VirtualBox in your case) and Gitian transfers the sources to your LXC image, so that you don't need Internet access from your LXC image during the build process. Here are [the instructions for doing this](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#optional-seed-the-gitian-sources-cache-and-offline-git-repositories). The command you run from the gitian-builder directory is:

```
make -C ../bitcoin/depends download SOURCES_PATH=`pwd`/cache/common
```

**Comment by kapiliitr** [comment]
make -C ../bitcoin/depends download SOURCES_PATH=`pwd`/cache/common

This doesn't work. It is trying to fetch boost but isn't able to.

ᐧ

Regards,
Kapil Agarwal

**Comment by kapiliitr** [comment]
Okay, so it worked when I logged into the VM from the host machine but it
didn't when I logged in from a remote machine.

Thanks

Regards,
Kapil Agarwal
