### ISSUE TITLE
Bitcoin-cli addnode remove - not functional

### ISSUE THREAD

**Issue by IvanaSu** [bitcoin/bitcoin#6901]
Example:
bitcoin-cli addnode 52.7.106.177:8333 remove
error: {"code":-24,"message":"Error: Node has not been added."}

**Comment by jonasschnelli** [comment]
Just tested. Works:

```
./src/bitcoin-cli -regtest addnode 52.7.106.177:8333 add
:~/node/bitcoin$ ./src/bitcoin-cli -regtest getaddednodeinfo true
[
  {
    "addednode": "52.7.106.177:8333",
    "connected": false,
    "addresses": [
      {
        "address": "52.7.106.177:8333",
        "connected": "false"
      }
    ]
  }
]
:~/node/bitcoin$ ./src/bitcoin-cli -regtest addnode 52.7.106.177:8333 remove
:~/node/bitcoin$ ./src/bitcoin-cli -regtest getaddednodeinfo true
[
]
```

**Comment by paveljanik** [comment]
@IvanaSu have you added that node before of do you simply want to disconnect some node?

**Comment by jonasschnelli** [comment]
@paveljanik: good point. If you wan't to just disconnect a node use `setban <ip> add <bantime>(default 86400 sec.)`.

**Comment by IvanaSu** [comment]
@paveljanik: yes, i simply wanted to disconnect a node (which I didn't add before)
@jonasschnelli: thank you!

**Comment by paveljanik** [comment]
@IvanaSu Great. Can you please close this issue now?
