### ISSUE TITLE
activate best chain crash

### ISSUE THREAD

**Issue by arisAlexis** [bitcoin/bitcoin#6947]
I got this error after starting the client but pointing to a directory that already had my data (wallet, some of the chain). I got stuck on "activating best chain". I used the -rescan method but nothing happened.

Then I deleted everything except my wallet and tried to download again the blockchain.

I got this error in the debug.log after crashing

2015-11-04 22:59:11 *** System error while flushing: CDB: Error -30974, can't open database 
2015-11-04 22:59:34 ERROR: ProcessNewBlock: ActivateBestChain failed
2015-11-04 22:59:34 addcon thread interrupt
2015-11-04 22:59:34 opencon thread interrupt
2015-11-04 22:59:34 net thread interrupt
2015-11-04 22:59:34 scheduler thread interrupt
2015-11-04 22:59:34 msghand thread interrupt
2015-11-04 22:59:34 Shutdown: In progress...
2015-11-04 22:59:34 StopNode()
2015-11-04 22:59:35 *** System error while flushing: CDB: Error -30974, can't open database 

file wallet.dat has LSN 1/5930, past end of log at 1/476
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
DB_ENV->log_flush: LSN of 1/5930 past current end-of-log of 1/476
Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
PANIC: DB_RUNRECOVERY: Fatal error, run database recovery
wallet.dat: unable to flush page: 53
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
File handles still open at environment close
Open file handle: /media/aris/DATA/bitcoinData/database/log.0000000001
PANIC: fatal region error detected; run recovery

**Comment by pstratem** [comment]
rescan is for the wallet
the option you want is reindex

**Comment by laanwj** [comment]
That is a really scary error. Your wallet is corrupted. Are you perhaps trying to use a wallet from a bitcoin core version bulit with another version of berkeleydb? (built with `--with-incompatible-bdb`). 

If not, and you have a recent backup, try restoring that. If not, make a backup as soon as possible and try  `-salvagewallet`.

**Comment by paveljanik** [comment]
@arisAlexis `/media/...` - is this some form of removable storage or similar?

**Comment by arisAlexis** [comment]
wallet was ok , everything is working after deleting all the chains folder and downloading it all over
