### ISSUE TITLE
Warnings and errors building with -std=c++11

### ISSUE THREAD

**Issue by 6coind** [bitcoin/bitcoin#6957]
Is there a reason we still use auto_ptr in CreateNewBlock function ? Also there is a warning while building levelDB

util/bloom.cc:50:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < n; i++) {
                          ^

and 

util/logging.cc:58:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           (v == kMaxUint64/10 && delta > kMaxUint64%10)) {

Is it meant to remain this way for any reason?

**Comment by laanwj** [comment]
What error do you get? 

Using an alternative to std:auto_ptr is OK with me, although it should be backward compatible with non-C++11 for now.

Warnings may indicate a problem or may be (usually) harmless, should be checked on a per-case basis.

**Comment by laanwj** [comment]
Closing this. LevelDB warnings should be solved upstream. They are not concerning enough to keep this open.

**Comment by 6coind** [comment]
yeah, i eventually resolved thanks. On careful consideration perhaps it may be best left with full backwards compatibility.
