### ISSUE TITLE
Mempool trimming regression: removes local wallet transactions

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#6959]
#6722 introduces the possibility of removing transactions generated by the local wallet from its mempool, but fails to update CMerkleTx::GetDepthInMainChain which assumes a transaction neither in the blockchain nor the mempool must be conflicted. Since the wallet transaction is now assumed to be conflicted, the wallet will happily produce a double-spend using the same inputs again.

**Comment by jonasschnelli** [comment]
During another case i was also stumbling over a `GetDepthInMainChain()` inconsistency. IMO the wallet should keep it's own height cache or even it's own headers-only-chain (anyways required in case of process separation).

But anyways; the bitcoin-core local wallet (and other wallets) need to find a way to handle removed transactions from the mempool without marking them as conflicted.

But you are saying using inputs from a conflicted transaction results in a double-spend? The transaction was removed from the mempool and is not in the chain,... that means it's available again for coin selection, isn't it?

**Comment by luke-jr** [comment]
In most cases, it means the wallet wishes to keep it in the mempool and rebroadcast until it is mined.

**Comment by jonasschnelli** [comment]
Yes. Such use cases, together with the FSS-RBF (or CPFP) need to be handled by the wallet.

**Comment by jgarzik** [comment]
Yes - this problem was the same one that merge-blocked mempool janitor...  Need to solve for local wallet

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
