### ISSUE TITLE
typo in 0.11.2 release notes: may vs must

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#7009]
> The consensus rules also specify that valid blocks *may* have a header time greater than that of the median of the 11 previous blocks

Replace 'may' with 'must'.

**Comment by luke-jr** [comment]
Too late? it's released :/

**Comment by laanwj** [comment]
There's still a few places where it could be updated:

- bitcoin.org
- the historical release notes (where 0.11.2 hasn't been added yet)

Agree with @luke-jr that changing it on the branch at this point is pointless.
