### ISSUE TITLE
RPC: decodescript RPC call holds cs_main

### ISSUE THREAD

**Issue by pstratem** [bitcoin/bitcoin#7012]
There doesn't seem to be any reason for it to hold this lock.

Thoughts?

**Comment by pstratem** [comment]
@CodeShark 4401b2d7 why?

**Comment by pstratem** [comment]
@petertodd ping

**Comment by petertodd** [comment]
Fixed in #7013

**Comment by CodeShark** [comment]
@pstratem I didn't actually go through every single call and check whether it was actually thread-safe.

**Comment by petertodd** [comment]
@CodeShark I just did that, although I'm in a bit of a rush so I may have missed something!

**Comment by CodeShark** [comment]
@petertodd thanks. The purpose of https://github.com/bitcoin/bitcoin/commit/4401b2d7c52e0f3841225369fb0d10767c51aaa2 wasn't to completely fix the locks - it was just to remove dependencies and provide for the ability to make the locks more granular without changing any behavior. There's still plenty that could be done to improve concurrency.

**Comment by pstratem** [comment]
@CodeShark ah i see

**Comment by laanwj** [comment]
> @pstratem I didn't actually go through every single call and check whether it was actually thread-safe.

This was the longer-term goal of pushing down the locks in #5711, but for the first step it was *much* easier to review when doing a simple mechanical step, keeping the functionality the same. If it changed the locking for every single RPC call it would probably never have been merged.

**Comment by laanwj** [comment]
Solved by #7013
