### ISSUE TITLE
Receive screen: add new column for "received per address"

### ISSUE THREAD

**Issue by misterdna** [bitcoin/bitcoin#7014]
BACKGROUND:
I didn't understand the Receive screen on the Mac client at first. That's partially because, when I create new pay-to addresses, I usually do so just to copy the address. I don't typically include (or create) a payment amount, particularly when creating a tipping address for content. So when I went to the Receive screen, I thought there was a bug because every address just had "(no amount)" listed, rather than the payments I knew I had received to various address.

SIMPLE SUGGESTION:
Change the header for the column to "Bitcoin Requested" or "Requested Amount (BTC)" and that will make it more clear what the column is displaying.

BIGGER SUGGESTION:
Add a new column that lists the total that's been received by each address, with a column header like "Bitcoin Received" or "Total Received (BTC). This is very helpful if you're a content creator, and you assign different addresses to different content. The new column would really help me quickly see the relative tipping amounts for different content. I'm sure there are other uses for this additional info, and there's definitely room for another column (or two) on that screen.

Perhaps a third column could be added, with a header that says "Bitcoin Balance" or "Balance (BTC)" for each address, largely as a way to make it clear that the "Bitcoin Received" column is not necessarily the balance held by that address. I also think a clear way to view every balance-holding address in the wallet would be handy (or at least interesting), so this is a step in that direction.

Please note I'm not a technical person, and this is my first Bitcoin Pull Request. I have no clue how much work it is to add these columns, but I think it would really improve the usefulness of this software. Thanks!

**Comment by sipa** [comment]
Bitcoin Core wallet does not treat addresses as holding individual balances
- that's just an interpretation, and it doesn't work well with the use of
random fresh change addresses. Instead, all addresses are seen as entry
points into the whole wallet, but after that, all funds are shared. If you
want to see the actual low-level state of your wallet, you can enable coin
control.

The idea to show received per address may make sense, I think.

**Comment by misterdna** [comment]
I apparently need to learn a lot more about how the wallet works!

Glad you kind of agree on the “received per address" column. But since you don’t seem 100% convinced…

Let’s say I’ve created 10 tipping addresses for 10 pieces of content I’ve created. And each entry in the Core client is labeled, so it’s clear at a glance which content each address is associated with. If I could see the total sent to each address in a newly-created column, that would make the software much more useful. Maybe the additional info would be useful to others too.

Thanks for considering it!

**Comment by MarcoFalke** [comment]
@misterdna You may type into the console in the "debug window" something like

```
getreceivedbyaddress $ADDRESS
```

But keep in mind the result may be faulty in some cases (#3217).

**Comment by misterdna** [comment]
Thanks for that info. But can that only show if for one address at a time? The ability to view multiple addresses simultaneously is what would be especially helpful for me. I typically visit a web-based block explorer to view info for one address at a time.

**Comment by MeshCollider** [comment]
The "simple suggestion" change was made in https://github.com/bitcoin/bitcoin/pull/7383, so I've updated the PR title to make it clearer this is a suggestion for the "received per address" column

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
