### ISSUE TITLE
Showing very tiny font in the Debug console tab

### ISSUE THREAD

**Issue by ptschip** [bitcoin/bitcoin#7017]
on Windows 7, 32bit

![consoletab](https://cloud.githubusercontent.com/assets/12862928/11164414/26296fbc-8aa4-11e5-86a4-6392f31b9c42.png)

**Comment by MarcoFalke** [comment]
Someone should revert 268b79ef0c54a3bff0b50e093b98b943e49a4939 ...

**Comment by jonasschnelli** [comment]
Thanks @ptschip for reporting. At first sight, i agree, it's small or lets say smaller then before. But if I compare it with other text elements like "Information" (tab), it looks reasonable.

Will compare font sized on windows within the next days.

**Comment by MarcoFalke** [comment]
> it's small or lets say smaller than before

It's about 95% of the previous size ( 268b79ef0c54a3bff0b50e093b98b943e49a4939 ). The reason this looks so tiny is that the windows monospace font is more wide than tall.

**Comment by ptschip** [comment]
Size aside, why isn't it the same font as in the other tabs?  The other
tabs look like Helvetica and only in this tab it's using some other font
which makes it only harder to read.

**Comment by jonasschnelli** [comment]
@ptschip This was changed in #6864. RPC output should use a fixed-pitch font (line in a terminal) for best readability.
Do you think it's harder to read because of the fixed-pitch font or because of the size?

**Comment by ptschip** [comment]
@jonasschnelli  It's the font style that is hard to read.  Fixed pitch is fine when it's bigger but when it's small I find the edges of each letter start to blurr and I have to make more effort to view it especially on a 15" screen or less. With Helvetica you don't have that problem, it has clear edges.

**Comment by jonasschnelli** [comment]
I agree that this is suboptimal. It feels like, that the terminals font and size is a matter of taste (and also depending on what OS is used). A nice solution would be to allow changing the font and size over the GUI settings.

**Comment by ptschip** [comment]
@jonasschnelli  Yes, I agree, it would be great if we could select our own font type and size.  With all the different sized terminals and differences in vision, personal taste etc,  it's hard to find a one size fits all approach.

**Comment by ptschip** [comment]
@jonasschnelli Feel free to close this issue if it's not something that needs fixing but rather, requires an enhancement.

**Comment by jonasschnelli** [comment]
Lets keep it open for now because other users might also find this problematic and i'd like to get more feedback for this.

**Comment by MarcoFalke** [comment]
Agree with @jonasschnelli to leave this open. The windows font really looks odd. On OSX (and linux) it looks much better.

**Comment by ptschip** [comment]
you'll get no argument from me...

**Comment by laanwj** [comment]
As I said before #6864, I think it would have been better to stick with proportional font. Getting monospace fonts consistent on all platforms turns out, again, to be a time sink.

**Comment by MarcoFalke** [comment]
@jonasschnelli suggested to bundle a monospace font so we get the same flavor across platforms. I start liking this idea but I haven't yet found a suitable MIT/PD monospace font.

**Comment by jonasschnelli** [comment]
Not sure if bundling a font for this purpose is a good solution. I would recommend that we add a feature that allows to switch/choose a custom font (over http://doc.qt.io/qt-4.8/qfontdialog.html). Either over the setting panel or – hidden as "expert features" – over a context menu of the console textview.

**Comment by luke-jr** [comment]
Requested MIT licensing on https://quickgit.kde.org/?p=trojita.git&a=blob&h=019204e33d1ef2c2311795064195bc0b41a376fa&hb=652835c867bec9a4aa31c1bd44ed2220852f8013&f=src%2FGui%2FUtil.cpp

At the very least, note Qt5 has a way to do this nicely.

**Comment by laanwj** [comment]
IMO bundling a font is overkill. This is getting out of hand, the debug console is just a developer feature, it doesn't need all this design effort.

**Comment by veqtrus** [comment]
This is still a problem in 0.12rc1.

![image](https://cloud.githubusercontent.com/assets/3521837/12378474/581936bc-bd47-11e5-8671-d6c064de6ac6.png)

**Comment by MarcoFalke** [comment]
Too many users complain about this. Let's make the workaround a bit more dirty because no one liked it in the first place. Please see #7364.

**Comment by laanwj** [comment]
I still think we should simply revert to a proportional font. This is getting crazy.

**Comment by jonasschnelli** [comment]
Agree with @laanwj.

**Comment by MarcoFalke** [comment]
Ok with me but I'd rather schedule this after the 0.12.0 release. #7364 as a Windows only fix for 0.12.0 is ugly but acceptable?

**Comment by jonasschnelli** [comment]
I think we should not introduce a monospace font in 0.12 and remove it in 0.12.1 (or 0.13). IMO best solution would be to revert and go back to the original behavior. What was the original issue to switch over to the monospace font?

**Comment by MarcoFalke** [comment]
Your pretty-print pull "introduced" the issue ;)

**Comment by laanwj** [comment]
The pretty-printing looked somewhat better with monospaced font. However, getting *one* font to work well over platforms already seems to be problematic. Every time you think you got it right, some new issue turns up (e.g. #7341). So let alone two...
