### ISSUE TITLE
Unable to Build on Debian 8.2 (3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux)

### ISSUE THREAD

**Issue by bigcoinme** [bitcoin/bitcoin#7024]
Hi,
I've installed all the dependencies listed on https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md, but when I run ./autogen.sh I get these errors :

> Makefile.am:5: warning: user variable 'GZIP_ENV' defined here ...
> /usr/share/automake-1.14/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
> Makefile.am:55: warning: user target 'distcleancheck' defined here ...
> /usr/share/automake-1.14/am/distdir.am: ... overrides Automake target 'distcleancheck' defined here
> src/Makefile.am:417: warning: user target '.mm.o' defined here ...
> /usr/share/automake-1.14/am/depend2.am: ... overrides Automake target '.mm.o' defined here

**Comment by jonasschnelli** [comment]
These are not errors, "just" warnings. I also encounter them regularly on debian and i agree, that fixing the warnings would be nice.
But it shouldn't lead to compile problems.

**Comment by bigcoinme** [comment]
Oh OK, thanks for the information.
Agreed
> fixing the warnings would be nice.
