### ISSUE TITLE
Set port from the GUI settings

### ISSUE THREAD

**Issue by Matthias84** [bitcoin/bitcoin#7039]
Hi, UPNP doesn't work for me, so I managed to get an port-forwarding by my admins. Currently it means to fire up btc core via --port to apply this custom settings. It would be nice, to set (and forget) it via the GUI.

**Comment by parazyd** [comment]
If you are starting bitcoin-qt with a shortcut, you can add the `--port` argument to the shortcut and you needn't think about it anymore.

**Comment by jonasschnelli** [comment]
I think an option to set the port over the UI (like the SOCKS/TOR proxys) would be nice.

**Comment by laanwj** [comment]
> If you are starting bitcoin-qt with a shortcut, you can add the --port argument to the shortcut and you needn't think about it anymore.

Or just set it in `bitcoin.conf` in the data directory. That's what it is for.

But yes this would be a feature for the 'would be nice' list.

**Comment by MarcoFalke** [comment]
Maybe expose `bitcoin.conf` just like `debug.log` in the GUI? Not sure if mapping every arg to the GUI makes sense.

**Comment by parazyd** [comment]
Exposing bitcoin.conf doesn't make sense. If people want to change core vars, they should be able to find their bitcoin.conf by themselves.

**Comment by jarolrod** [comment]
@matthias-g @jonasschnelli Can this be closed since you can currently set the `SOCKS/TOR` proxy in the GUI under `Settings`->`Options`->`Network`
