### ISSUE TITLE
return values for rpc calls

### ISSUE THREAD

**Issue by kalgecin** [bitcoin/bitcoin#7043]
Currently calling rpc commands does not return any values. They need to return at minimum true or false. true if the command was successful, false otherwise. 
For example, I have a script that imports private keys. I'd like to know whether the key i just tried importing imported or not, flag it if it hasn't move on if it was.

**Comment by sipa** [comment]
This seems very reasonable to me, but I'm not sure it's worth changing the API over. Traditionally, RPCs that have a stateful effect return Null (or an error if they fail), and only RPCs that request data return actual values.

**Comment by kalgecin** [comment]
ok, but there is no error returned if say the private key is wrong, it still returns null. there needs to be a way to know if the command you just sent was completed successfuly

**Comment by sipa** [comment]
No, an error should definitely be returned in that case: https://github.com/bitcoin/bitcoin/blob/v0.11.2/src/wallet/rpcdump.cpp#L115

If that isn't working, there is definitely a bug.

**Comment by sipa** [comment]
Note that errors are returned as JSON-RPC errors, not as return values.

**Comment by kalgecin** [comment]
i receive null in either case

**Comment by sipa** [comment]
The return value will be Null in both cases. But one should have a JSON-RPC
error code and the other shouldn't.

**Comment by kalgecin** [comment]
when using the client, yes, but when calling using external programs, it does not. try with the example using curl

**Comment by luke-jr** [comment]
Works for me

````
$ curl -u 'bitcoinrpc' http://localhost:8332 -d '{"method":"importprivkey","params":["invalid"],"id":0}'
Enter host password for user 'bitcoinrpc':
{"result":null,"error":{"code":-5,"message":"Invalid private key encoding"},"id":0}
````

**Comment by sipa** [comment]
You need to look at the returned header to see the error status. Curl is
not a full JSON-RPC client.

**Comment by jonasschnelli** [comment]
Works for me here:

```
jonasschnelli$ curl -v --user bitcoin --data-binary '{"method":"importprivkey","params":["invalid"],"id":0}' -H 'content-type: text/plain;' http://127.0.0.1:18332/

*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 18332 (#0)
* Server auth using Basic with user 'bitcoin'
> POST / HTTP/1.1
> Host: 127.0.0.1:18332
> Authorization: Basic Yml0Y29pbjp0ZXN0
> User-Agent: curl/7.43.0
> Accept: */*
> content-type: text/plain;
> Content-Length: 54
> 
* upload completely sent off: 54 out of 54 bytes
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Wed, 18 Nov 2015 09:42:12 GMT
< Content-Length: 84
< 
{"result":null,"error":{"code":-5,"message":"Invalid private key encoding"},"id":0}
```

**Comment by laanwj** [comment]
Works fine for me.

**Comment by MarcoFalke** [comment]
> Traditionally, RPCs that have a stateful effect return Null (or an error if they fail), and only RPCs that request data return actual values.

So `settxfee` etc. should not return true?
