### ISSUE TITLE
Difference in getbalance and sum(listtransactions) amounts (testnet)

### ISSUE THREAD

**Issue by asfin** [bitcoin/bitcoin#7054]
I have bunch of wallets which i import in fresh and empty bitcoind via `importwallet`. After this i issue `getbalance`, which shows me `0.00000000`, but if i perform `listtransactions` and sum all amounts and fees(single fee per tx) i've got `0.00004137`. Why?

```
Bitcoin Core Daemon version v0.11.1.0-gcf33f19
```
[check_tx.py.txt](https://github.com/bitcoin/bitcoin/files/37932/check_tx.py.txt)
[listtransactions.json.txt](https://github.com/bitcoin/bitcoin/files/37931/listtransactions.json.txt)
[unspent.json.txt](https://github.com/bitcoin/bitcoin/files/37930/unspent.json.txt)

**Comment by jonasschnelli** [comment]
I shortly checked your receiving addresses over an testnet API, seems to be 0 balance.
Could be a mistake in your script (fees correctly handled?!) or a missing transaction in your listtransaction.txt

**Comment by asfin** [comment]
I've checked again, listtransactions.txt is fine. Script also should be ok, but i'll be glad if someone more experienced check it.

**Comment by laanwj** [comment]
Some transactions have negative "fee", that's weird.

**Comment by asfin** [comment]
I'm think it happens because this addresses are part of larger wallet, and positive fees are "change", am i right?

**Comment by MarcoFalke** [comment]
No, change is already considered in the "amount" value.

@asfin I guess you forgot to import some keys of some of the transactions. (Maybe coinjoin?) Could you try again and assert that you have all addresses in you wallet?

**Comment by sipa** [comment]
Fee is computed as (sum of outputs)-(sum of inputs that are ours)... that is meaningless if not all inputs are ours.

**Comment by MarcoFalke** [comment]
@sipa Yes, and it's in there since at least 2011™

**Comment by asfin** [comment]
@MarcoFalke OK, I'll try to import complete wallet and attach result. But i've found this problem on it, and after this tried to split wallet on small parts, to isolate error.
It seems to be weird, if after importing privkey my balance doesn't match transaction history.

**Comment by MarcoFalke** [comment]
@asfin Yes, if you don't import all private key related to all transactions, you will get a difference when summing up the values reported by `listtransactions` in current versions of bitcoin.

**Comment by asfin** [comment]
Replaced wallet.dat with backup of original, and performed reindex. Script reports:
```
unspent     :   12.33503283
total income:   12.34391710
total fee   :   -0.00884290
diff        :   12.33507420
```
but in attached version of script, `diff` doesn't include unspent balance so `diff-unspent=error; 12.33507420-12.33503283=0.00004137`. How correctly find tx, which broke this?

[listtransactions.json.txt](https://github.com/bitcoin/bitcoin/files/39904/listtransactions.json.txt)
[unspent.json.txt](https://github.com/bitcoin/bitcoin/files/39903/unspent.json.txt)

**Comment by MarcoFalke** [comment]
> How correctly find tx, which broke this?

Should be at least all those with negative fee

**Comment by asfin** [comment]
But here all fees < 0.

**Comment by MarcoFalke** [comment]
Yes, `listtransactions` always *should* return a negative fee. (Internally they are handled positive)

**Comment by MarcoFalke** [comment]
Not clear this is an issue
