### ISSUE TITLE
Coinjoin transactions show up inconsistently in bitcoin-qt

### ISSUE THREAD

**Issue by raedah** [bitcoin/bitcoin#7073]
Coinjoin transactions in bitcoin-qt are showing up inconsistently in the transaction tab. These are watch addresses. Some show up as a single line and others as two lines. 

The transactions that show up as two lines, both show the same transaction ID in the details. The type for these say 'Received with'. No where does it show that the inputs (or Debits) for this transaction that came from this wallet. The Amount column shows the received balance. These transactions are the ones which have a slightly different balance then the inputs, because of a cost paid to the maker by the other parties in the coinjoin.

The transactions that show up as a single line, have the Type field empty. They are showing a single Debit and two Credits in the details. I have not verified a case where multiple Debits are present. The Amount column shows the Net amount correctly. These transactions have a Net that is either 0 or equal to the mining fee contributed by this party of the transaction. No cost was charged to the other parties for coin joining.

**Comment by jonasschnelli** [comment]
Looks like a duplicate of https://github.com/bitcoin/bitcoin/issues/6814.

**Comment by raedah** [comment]
true, will go there.
