### ISSUE TITLE
Mac Gatekeeper security prompt every time

### ISSUE THREAD

**Issue by oliverdowling** [bitcoin/bitcoin#7085]
## Environment:

Mac OS X 10.11.1 El Capitan
Bitcoin Core 0.11.2

## Problem:

Every time I open Bitcoin Core, I get prompted by Apple's Gatekeeper security:

![screen shot 2015-11-24 at 10 27 13](https://cloud.githubusercontent.com/assets/431047/11353337/5ad11dba-9296-11e5-8423-bbab2068b0ec.png)

### Option 1

Specifically remove the app from quarantine:

```
sudo xattr -d com.apple.quarantine /Applications/Bitcoin-Qt.app
```

### Option 2

Disable Gatekeeper.

### Option 3

Edit permissions.

## Cause:

I believe the actual cause is the permissions on the file. Bitcoin Core has 0555 permissions, but all the other applications I have installed myself have 0755 permissions.

I verified, by changing the permissions to 0755, opening Bitcoin Core, clicking "open", quitting Bitcoin Core, and opening Bitcoin Core again, and I no longer receive the Gatekeeper security prompt.

~~**However**, Bitcoin Core is now prompting me that I "need to rebuild the databse using -reindex to change -txindex", but I'm guessing this is because it may not be reading my bitcoin.conf properly anymore because of a permissions issue that I have caused.~~ Edit: I think this is user error.

**Comment by laanwj** [comment]
@theuni can you take a look here?

**Comment by jonasschnelli** [comment]
Just tested on OSX 10.11. Confirmed.
Executing `chmod -Rf 755 Bitcoin-Qt.app` cured the issue.

**Comment by jonasschnelli** [comment]
Only the application folder needs 755 (`drwxr-xr-x`; requires owner write permission) permissions: `chmod 755 Bitcoin-Qt.app/.`
The folder has 555 (`dr-xr-xr-x`).

**Comment by jonasschnelli** [comment]
I think the first mkdir is accountable for the 555 permission. Maybe a gitian umask issue?
https://github.com/bitcoin/bitcoin/blob/master/Makefile.am#L71
But i'll wait for @theuni before i try a fix.

**Comment by theuni** [comment]
Odd. Looking now.

**Comment by martinoconnor** [comment]
This issue has been reintroduced in v0.12.1

**Comment by jonasschnelli** [comment]
Yes. Confirmed. Just double checked v0.12.1 from https://bitcoin.org/bin/bitcoin-core-0.12.1/ and Indeed the problem is still present.

Although the issue is not present with a gitian nightly build  https://bitcoin.jonasschnelli.ch/nightlybuilds/2016-06-07

"Official" v0.12.1 release has:
```
$ ls -la ~/Desktop/Bitcoin-Qt.app
total 0
dr-xr-xr-x@  3 jonasschnelli  staff   102  1 Jan 01:00 .
drwxr-xr-x+ 42 jonasschnelli  staff  1428  8 Jun 13:15 ..
dr-xr-xr-x@  7 jonasschnelli  staff   238  1 Jan 01:00 Contents
```

Nightly build:
```
$ ls -la ~/Desktop/Bitcoin-Qt.app
total 0
drwxr-xr-x@  3 jonasschnelli  staff   102  1 Jan 01:00 .
drwxr-xr-x+ 42 jonasschnelli  staff  1428  8 Jun 13:14 ..
drwxr-xr-x@  6 jonasschnelli  staff   204  1 Jan 01:00 Contents
```

**Comment by jonasschnelli** [comment]
@theuni: is it possible that the gitian detatched signer accidentally changes the `Bitcoin-Qt.app` folders permission?
Because the nightly build I have compared against is unsigned.
