### ISSUE TITLE
Addrman only contains seed nodes when there's no externally bound address

### ISSUE THREAD

**Issue by theuni** [bitcoin/bitcoin#7098]
This seems really nasty.

ipv4/ipv6 are not set as reachable by default. We only end up setting them to reachable if we've discovered an external address. This is extra worrisome now that upnp discovery is off by default.

The result is that addrman only ever contains dns seeds and possibly static seeds in many common use-cases.

Possible fixes:
- Always set ipv4 to reachable. In practice we treat it this way anyway.
- Set ipv4/ipv6 reachable once bound, regardless of whether it's routable.
- Set ipv4/ipv6 to reachable once a respective connection attempt succeeds.

**Comment by laanwj** [comment]
> Always set ipv4 to reachable. In practice we treat it this way anyway.

Yes, determining connectivity is a difficult problem in general. I remember libevent has some code for 'guessing' if it's on ipv4/ipv6 network by looking at OS-specific things like interfaces, and it's not pretty, and it gets things wrong sometimes.

(if you make any default assumptions, don't forget honoring -onlynet, it can disallow connecting over specific networks)

> Set ipv4/ipv6 reachable once bound, regardless of whether it's routable.

I don't think binding should influence it - reachable for outgoing connections is something else than reachable for incoming connections. Thinking of it, I have a similar issue with Tor/Onion, where being reachable on an .onion is interpreted as being able to connect to onions.

We don't do so at the moment, but ideally we'd distinguish between 'we are reachable on X' and 'we can reach out on X'.

**Comment by laanwj** [comment]
Also,  doing this determination once at startup is not really correct either. Networking status can very well change during runtime.
(see e.g. #6030)

**Comment by pstratem** [comment]
@laanwj indeed, we really dont know whether we have netgroup connectivity (except for tor)

**Comment by adamjonas** [comment]
[Based on the discussion](https://github.com/bitcoin/bitcoin/pull/7553#issuecomment-185639380), this looks to have been closed by #7553.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
