### ISSUE TITLE
Error while compiling bitcoin with qt support

### ISSUE THREAD

**Issue by wilsonwang371** [bitcoin/bitcoin#7138]
The error details are:

    In file included from qt/clientmodel.cpp:5:0:
    qt/clientmodel.h: In function ‘void BlockTipChanged(ClientModel*, bool, const CBlockIndex*)’:
    qt/clientmodel.h:92:10: error: ‘void ClientModel::numBlocksChanged(int, const QDateTime&, double)’ is protected
         void numBlocksChanged(int count, const QDateTime& blockDate, double nVerificationProgress);
              ^
    qt/clientmodel.cpp:256:154: error: within this context
             Q_EMIT clientmodel->numBlocksChanged(pIndex->nHeight, QDateTime::fromTime_t(pIndex->GetBlockTime()), clientmodel->getVerificationProgress(pIndex));
                                                                                                                                                          ^

It looks like a static function is trying to call a private method of ClientModel. There are two ways to fix this problem:

1. Declare numBlocksChanged as a friend of class ClientModel.
2. Add another public method to call line 256 instead of putting it in a static method outside class. 

I tried two approaches and both of them work. Which one is better?

Btw, I am new here. I am trying to join bitcoin community and hope I can make more contributions.

**Comment by jonasschnelli** [comment]
Thanks for reporting. This was introduced with: https://github.com/bitcoin/bitcoin/pull/7112

Methods 1) would be preferred I guess.

**Comment by laanwj** [comment]
Strange, why did none of our testing / Travis builds reveal this?

**Comment by laanwj** [comment]
See #7143
