### ISSUE TITLE
bug, bitcoin-qt take clicking away from desktop

### ISSUE THREAD

**Issue by raedah** [bitcoin/bitcoin#7139]
I am running bitcoin-qt from master. I use openbox which lets me access my app menu by right clicking on my desktop. Often times when bitcoin-qt is running, i cant access my desktop right click menu anymore. It doesnt happen right away, but after bitcoin-qt is running for a while. I know it is bitcoin-qt that is doing it because as soon as I close it my desktop menu is accessible again. I know this is a hard one to track since I cant duplicate it every time, but I thought I would report it so we can start verifying if others are experiencing it.

**Comment by jonasschnelli** [comment]
Very likely this happens because of high CPU usage during IBD. @raedah: Is your client "in-sync"? What is your best-blocks height?

**Comment by laanwj** [comment]
Yes, most likely lock contention or high CPU usage during IBD blocking the GUI thread
#7138 (merged for 0.12) likely makes this better

**Comment by raedah** [comment]
Its not high CPU. My machine is idle. It seems to kick in after left running for some time. So I leave bitcoin-qt running overnight, and come back the next day and I can no longer right click my desktop until I close bitcoin-qt and reopen it.

**Comment by laanwj** [comment]
You haven't mentioned what OS

**Comment by raedah** [comment]
Arch Linux

**Comment by raedah** [comment]
Tested on v0.12.0rc2 and I still have this issue. I dot not get this issue with v0.11.2.

**Comment by laanwj** [comment]
@readah Both built in the same way?
(if you are comparing an executable from bitcoin.org with a self-built one, or one from your Linux distro, that may be the source of the issue, as they are linked to different versions of Qt under different circumstances)

**Comment by raedah** [comment]
only happens on self-built, so that could be.

**Comment by laanwj** [comment]
What version of qt are you building against?

**Comment by raedah** [comment]
My system has  qt4 4.8.7-6  and  qt5-base 5.5.1-9
