### ISSUE TITLE
Option for disabling the system tray

### ISSUE THREAD

**Issue by fturco** [bitcoin/bitcoin#7160]
It would be cool if there was an option in Bitcoin Core for disabling the system tray entirely.

**Comment by jonasschnelli** [comment]
I think this could be useful. Also we could allow the tray function on OSX (Global Menu Bar) and hide it by default.

**Comment by laanwj** [comment]
I tend to agree. At some point that may even be the default, it looks like system trays (at least for application use) are on their way out?

**Comment by jonasschnelli** [comment]
> At some point that may even be the default, it looks like system trays (at least for application use) are on their way out?

Hah. Right. Users and app devs probably figured out that the Windows Tray and the OSX Global Menu slowly mutates towards a application launcher...

**Comment by fturco** [comment]
I can't speak for people using either Windows or Mac OS. I use GNOME under GNU/Linux and I find the system tray annoying. Instead I keep each application window opened in a separate workspace.

**Comment by MarcoFalke** [comment]
@jonasschnelli Anything left to do here?

**Comment by jonasschnelli** [comment]
Fixed by #8006.

**Comment by fturco** [comment]
It's strange, but I can't see any option in the Window tab or elsewhere for disabling the system tray with Bitcoin v0.12.1.0-g9779e1e. I also tried adding the `hideTrayIcon=1` in `~/.bitcoin/bitcoin.conf` but it doesn't work. The system tray icon is still there.

**Comment by jonasschnelli** [comment]
@fturco: the system tray features is not included in 0.12.1, its a 0.13 features (you maybe want to test the 0.13.0rc2 binaries: https://bitcoin.org/bin/bitcoin-core-0.13.0/test.rc2/).

**Comment by fturco** [comment]
Sorry, I didn't know that. Anyway I think I'll wait for the 0.13 release to be included with my Linux distribution updates. I'm not in a hurry :)
