### ISSUE TITLE
Replace OpenSSL PRNG

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7162]
(As part of getting rid of OpenSSL dependency)
See discussion in #5885.
What remains to be done: factor @sipa's code in that pull out into an external library like secp256k1, univalue.

**Comment by MarcoFalke** [comment]
@laanwj I have removed the 0.13.0 milestone and added 0.14 instead, as it seems unlikely this will happen within the next two days.

**Comment by laanwj** [comment]
Right, this has no urgency.

**Comment by laanwj** [comment]
Closing this. I opened this to track ongoing work, but it looks like development priorities have changed. It's not terribly important anyway, OpenSSL's random combined with external entropy as we do now is good enough.
