### ISSUE TITLE
error from Boost

### ISSUE THREAD

**Issue by angjelo** [bitcoin/bitcoin#7172]
After I type any bitcoind command i get this error:
Assertion failed: (pthread_mutex_lock(&m_) == 0), function lock, file /usr/local/include/boost/signals2/detail/lwm_pthreads.hpp, line 60.
Abort trap: 6

Any suggestions? 
Thanks

**Comment by parazyd** [comment]
What's your version of boost? What OS? Which binaries?

**Comment by angjelo** [comment]
i am using the last version and I am using osx yosemite 10.10.5... what are binaries ?

**Comment by parazyd** [comment]
Well, your bitcoin binaries. Where did you get bitcoind from?
Did you compile it yourself?

**Comment by angjelo** [comment]
this is how i got it 
 git clone https://github.com/bitcoin/bitcoin.git

**Comment by parazyd** [comment]
Follow the guide for compiling on Mac OSX:  
[README_osx.txt](https://github.com/bitcoin/bitcoin/blob/master/doc/README_osx.txt)  
[build-osx.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md)

You can also try the static binaries from: https://bitcoin.org/en/download  
They should work with no issues.

**Comment by angjelo** [comment]
Ok cool thank you... do you think that it would be easier if I use linux? Cause I can install it pretty quick in a virtual machine..

**Comment by parazyd** [comment]
It really depends on how you want to use it. Try it out yourself and see what you prefer.

**Comment by angjelo** [comment]
ok thanks mate !

**Comment by jonasschnelli** [comment]
@angjelo: did you had luck compiling bitcoin-core? It looks like that you are missing parts of the boost library.

I guess you need to install/upgrade (to) the newest version of homebrew (`brew upgrade`) and install all the dependencies (`brew install autoconf automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf qt5 libevent`); check this https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md.

Bitcoin-core compiles fine on osx 10.10, 10.11.

**Comment by angjelo** [comment]
ok yeah i think i miss stuff ... i am going to try and reinstall it... i tried it in linux it worked fine I did not have any issues. Thanks although , appreciated !
