### ISSUE TITLE
when will delete "This is experimental software" ?

### ISSUE THREAD

**Issue by LongShao007** [bitcoin/bitcoin#7173]
Bitcoin is experimental software, But lots of people think bitcoin is successful, so we should delete "This is experimental software" ? Do you have any time point to this ? after block expansion ? or other ?

**Comment by jonasschnelli** [comment]
I think this is the wrong place to discuss that particular topic. At the moment most people would probably agree that bitcoin is in a experimental "beta" phase. Closing.

**Comment by laanwj** [comment]
Don't really have a strong opinion on this. Something could be said for keeping it or removing it. Even though the base system seems to have settled down a lot of experimentation is still happening at the edges, e.g. handling of fees, mempool policy, spam prevention, wallet security/reliability, privacy, scaling. Even the basic question "is distributed consensus robust" has not been answered decisively yet. It's far from a done deal. Also there are no guarantees, that is important to keep in mind. As a disclaimer I think it makes sense.

**Comment by LongShao007** [comment]
@jonasschnelli 
where is the right place to discuss the topic? reddit?

**Comment by jonasschnelli** [comment]
@LongShao007: I think the bitcoin-discuss mailing list is the right place for a such discussion: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-discuss

**Comment by LongShao007** [comment]
@laanwj
Do you have the problem list need to be resolved.

**Comment by laanwj** [comment]
@LongShao007 No. It's not up to me to set a list of requirements anyway.

The point at which the label 'experimental' can go is something that will become clear in itself, culturally.
It can be removed when no one wonders about whether it is experimental anymore.

**Comment by MarcoFalke** [comment]
@LongShao007 I think you can remove the experimental when it is clear that bitcoin core is secure and scalable without the need of a(nother) blockchain fork. You may have a look at the mailing list to see which issues and solutions are being discussed right now.
