### ISSUE TITLE
OSX El Capitan build issues

### ISSUE THREAD

**Issue by eliot1785** [bitcoin/bitcoin#7175]
I'm new to GitHub and this project, so I apologize if this isn't helpful. I have a new laptop with OS X and followed the instructions in doc/build-osx.md but can't get it to work.

There are some export issues, but I think they've already been reported in a pull request: http://fdecollibus.blogspot.com/2015/11/building-bitcoinlitecoin-on-mac-os-x.html

After following that, however, I have a new issue where build.h cannot be found (see below). I hesitated to report this because maybe I am just doing it wrong, but in that case maybe the instructions could be improved?

    My-MacBook-Pro:bitcoin myuser$ make
    Making all in src
    ../share/genbuild.sh: line 3: cd: Source/bitcoin/src/obj/build.h: No such file or directory
      CXX      libbitcoin_util_a-clientversion.o
    clientversion.cpp:42:10: fatal error: 'build.h' file not found
    #include "build.h"
             ^
    1 error generated.
    make[2]: *** [libbitcoin_util_a-clientversion.o] Error 1
    make[1]: *** [all-recursive] Error 1
    make: *** [all-recursive] Error 1

**Comment by jonasschnelli** [comment]
Could you post your `config.log` somewhere and the output of `brew info openssl` as well as `brew -v`?

**Comment by eliot1785** [comment]
Sure, here you go:
[config.log.txt](https://github.com/bitcoin/bitcoin/files/60227/config.log.txt)



    Stephens-MacBook-Pro:bitcoin stephen$ brew -v
    Homebrew 0.9.5 (git revision 911a; last commit 2015-12-05)


    Stephens-MacBook-Pro:bitcoin stephen$ brew info openssl
    openssl: stable 1.0.2e (bottled) [keg-only]
    OpenSSL SSL/TLS cryptography library
    https://openssl.org/
    /usr/local/Cellar/openssl/1.0.2d_1 (464 files, 17M)
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/openssl.rb
    ==> Dependencies
    Build: makedepend ✘
    ==> Options
    --universal
        	Build a universal binary
    --without-check
	    Skip build-time tests (not recommended)
    ==> Caveats
    A CA file has been bootstrapped using certificates from the system
    keychain. To add additional certificates, place .pem files in
      /usr/local/etc/openssl/certs

    and run
      /usr/local/opt/openssl/bin/c_rehash
    This formula is keg-only, which means it was not symlinked into /usr/local.
    Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

**Comment by tnull** [comment]
I can reproduce this. When I link OpenSSL via `brew link openssl`, configure finds the header and all is fine. When not, conftest does not find them. See [config.txt](https://github.com/bitcoin/bitcoin/files/65377/config.txt). The corresponding line in the configure-script is: 

    ac_fn_cxx_check_header_mongrel "$LINENO" "openssl/ec.h" "ac_cv_header_openssl_ec_h" "$ac_includes_default"

Which may be generated by https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L749 ?
And maybe this ignores the `$openssl_prefix`?

**Comment by laanwj** [comment]
Any progress here?
