### ISSUE TITLE
Default limitfreerelay value

### ISSUE THREAD

**Issue by bitcoinfees** [bitcoin/bitcoin#7178]
I haven't been following too closely the developments around coin age priority, but my understanding is that it is being phased out (hence `DEFAULT_BLOCK_PRIORITY_SIZE` being set to 0).

Shouldn't `DEFAULT_LIMITFREERELAY` be set to zero as well, then?  If priority block space is being phased out, then free transactions are going to have a much harder time getting into blocks (according to what I'm observing as well), so to prevent a bunch of un-mineable txs from piling up we should discourage limitfreerelay.

Also, it makes it easier for people to double-spend their zero-fee transactions, if those transactions weren't hanging around in a bunch of mempools because of high priority, yet not being able to be confirmed.

**Comment by pstratem** [comment]
limitfreerelay is effectively made obsolete by the mempool limiter which is based entirely on feerate

**Comment by MeshCollider** [comment]
This was made obsolete by https://github.com/bitcoin/bitcoin/pull/9602 I believe, can be closed

**Comment by Leviathn** [comment]
Agree with @pstratem & @meshcollider -- definitely closeable.
