### ISSUE TITLE
Obsolete continuation of inner loop in ApproximateBestSubset

### ISSUE THREAD

**Issue by Xekyo** [bitcoin/bitcoin#7182]
[`vValue` is sorted](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L1704) into [ascending order](http://www.cplusplus.com/reference/algorithm/sort/) before [ApproximateBestSubset(...)](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L1591) is called. 

Currently, after a new best set is found, the final element that was added [gets removed from the set](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L1629), and the [inner loop](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L1608) continues to search through the remainder of `vValue` for a better set. It is however impossible for a better set to be achieved with a later element in `vValue`: As `vValue` is sorted in ascending order, any set formed with a later element will be of same size or bigger.

Therefore, the lines [1628](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L1628) & [1629](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L1629) are obsolete, and the inner loop should also stop on `fReachedTarget`.

**Comment by Xekyo** [comment]
I have created a pull request here: https://github.com/bitcoin/bitcoin/pull/7183

**Comment by MarcoFalke** [comment]
@Xekyo I think you can close this issue, as the PR now covers the details.

**Comment by laanwj** [comment]
Agree, this is covered by the PR
