### ISSUE TITLE
i sent 0.131 bitcoin with max fee from wallet and no confirmation with 3 days 

### ISSUE THREAD

**Issue by ovidiu26claudiu** [bitcoin/bitcoin#7191]
transaction id: 6050f3f71e7878b737aa49ce034c7a297ebb0a1ff8acbe1bda023b336fbb0b09

**Comment by laanwj** [comment]
That doesn't look like anything generated by Bitcoin Core? If it is, what settings did you use?
- It doesn't pay enough fee for the size of the transaction
- It includes an output below the dust threshold

**Comment by ovidiu26claudiu** [comment]
i have set my wallet for max fee for fast confirmation

**Comment by laanwj** [comment]
Which wallet?

**Comment by ovidiu26claudiu** [comment]
Nucleul Bitcoin versiunea v0.11.0 (32-bit)

**Comment by ovidiu26claudiu** [comment]
i have my wallet set for max fee for fast confirmation  


    On Wednesday, December 9, 2015 11:34 AM, Wladimir J. van der Laan <notifications@github.com> wrote:
 

 Which wallet?—

**Comment by ovidiu26claudiu** [comment]
anather transaction id: e9220f5ffb47c535f54a75d490232218841d1b9e5e00c59cfeb77d4ce8dee548 
not confirmed with 6 blocks why?

**Comment by laanwj** [comment]
Have you changed any settings in bitcoin.conf, or on the command line?

> i have set my wallet for max fee for fast confirmation

Can you describe exactly how you did this, if it was in the GUI possibly include a screenshot?

**Comment by ovidiu26claudiu** [comment]
http://s1.postimg.org/6lxpmz2in/bitcoin.jpg
no setings in bitcoin.conf and no setings in comand line

**Comment by MarcoFalke** [comment]
@ovidiu26claudiu Can you paste a screenshot of the settings you used to create the transaction? ("Trimite"-tab)

**Comment by ovidiu26claudiu** [comment]
http://s24.postimg.org/n4bxl8ld1/bitcoin3.jpg

**Comment by MarcoFalke** [comment]
Right, it did fall back to max(minRelayTxFee, minTxFee) as smart fee is not yet initialized. (This needs quite a few blocks to get proper results)

**Comment by MarcoFalke** [comment]
I remember @morcos did some work in #6134 but I haven't reviewed this yet and I don't think this fixes this issue.

**Comment by MarcoFalke** [comment]
@ovidiu26claudiu I think you can update to the latest 0.11 binary (0.11.2). As this is running with higher minRelayTxFee, it will reject those transactions you created and you can do a double spend with higher fee.

**Comment by ovidiu26claudiu** [comment]
e9220f5ffb47c535f54a75d490232218841d1b9e5e00c59cfeb77d4ce8dee548
6050f3f71e7878b737aa49ce034c7a297ebb0a1ff8acbe1bda023b336fbb0b09
last one i w8 3 day and nothing first more 10 block 
i send only with max fee

**Comment by ovidiu26claudiu** [comment]
what i need to do now?
in how many time i have this 2 transaction confirmed?
what is duble spend?

**Comment by MarcoFalke** [comment]
@ovidiu26claudiu No worries.
* Try to update your software: https://bitcoin.org/en/download
* Send the transactions again (Make sure the receiver knows that you are sending them again, otherwise they may get confused by this)

If you can't send the transaction again, let us know.

**Comment by MarcoFalke** [comment]
@ovidiu26claudiu You may close the issue if it is resolved now.
