### ISSUE TITLE
compile error on Ubuntu 12.04

### ISSUE THREAD

**Issue by feathercoin2** [bitcoin/bitcoin#7204]
When I make 0.11.1 ,I'm getting a problem.
In file included from bitcoind.cpp:11:0:
scheduler.h:14:35: fatal error: boost/chrono/chrono.hpp: No such file or directory
compilation terminated.

**Comment by jonasschnelli** [comment]
Did you follow the doc (https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian)?
What boost version do you have installed?
Could you post your `config.log`?

**Comment by laanwj** [comment]
On 12.04 you probably need libboost-all-dev installed

**Comment by feathercoin2** [comment]
I'm install boost1.58 by manual 

tar xvfz boost_1_58_0.tar.gz
cd /usr/local/boost_1_58_0
./bootstrap.sh --with-libraries=thread,chrono,date_time,system --prefix=/usr/
./b2 install

then I  compile bitcoind.cpp success.

final, I'm getting a link error:

bitcoind-bitcoind.o: In function `is_directory':
/usr/include/boost/filesystem/operations.hpp:409: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `directory_iterator':
/usr/include/boost/filesystem/operations.hpp:806: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `path<boost::filesystem::directory_entry>':
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `is_regular_file':
/usr/include/boost/filesystem/operations.hpp:414: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `CleanupBlockRevFiles()':
/data/ftc11/ftc0.11.1b/src/init.cpp:499: undefined reference to `boost::filesystem::path::filename() const'
/data/ftc11/ftc0.11.1b/src/init.cpp:500: undefined reference to `boost::filesystem::path::filename() const'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `boost::iterators::detail::iterator_facade_base<boost::filesystem::directory_iterator, boost::filesystem::directory_entry, boost::iterators::single_pass_traversal_tag, boost::filesystem::directory_entry&, long, false, false>::operator++()':
/usr/include/boost/filesystem/operations.hpp:842: undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `CleanupBlockRevFiles()':
/data/ftc11/ftc0.11.1b/src/init.cpp:501: undefined reference to `boost::filesystem::path::filename() const'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `remove':
/usr/include/boost/filesystem/operations.hpp:620: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `CleanupBlockRevFiles()':
/data/ftc11/ftc0.11.1b/src/init.cpp:496: undefined reference to `boost::filesystem::path::filename() const'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `remove':
/usr/include/boost/filesystem/operations.hpp:620: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `CleanupBlockRevFiles()':
/data/ftc11/ftc0.11.1b/src/init.cpp:497: undefined reference to `boost::filesystem::path::filename() const'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `remove':
/usr/include/boost/filesystem/operations.hpp:620: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `extension':
/usr/include/boost/filesystem/convenience.hpp:36: undefined reference to `boost::filesystem::path::extension() const'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `basename':
/usr/include/boost/filesystem/convenience.hpp:41: undefined reference to `boost::filesystem::path::stem() const'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `create_directories':
/usr/include/boost/filesystem/operations.hpp:523: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `create_hard_link':
/usr/include/boost/filesystem/operations.hpp:541: undefined reference to `boost::filesystem::detail::create_hard_link(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `~dir_itr_imp':
/usr/include/boost/filesystem/operations.hpp:775: undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `~dir_itr_imp':
/usr/include/boost/filesystem/operations.hpp:775: undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
libbitcoin_server.a(libbitcoin_server_a-main.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_server.a(libbitcoin_server_a-main.o): In function `OpenDiskFile(CDiskBlockPos const&, char const*, bool)':
/data/ftc11/ftc0.11.1b/src/main.cpp:3172: undefined reference to `boost::filesystem::path::parent_path() const'
libbitcoin_server.a(libbitcoin_server_a-main.o): In function `create_directories':
/usr/include/boost/filesystem/operations.hpp:523: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-main.o): In function `remove':
/usr/include/boost/filesystem/operations.hpp:620: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
/usr/include/boost/filesystem/operations.hpp:620: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-main.o): In function `space':
/usr/include/boost/filesystem/operations.hpp:644: undefined reference to `boost::filesystem::detail::space(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-net.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_server.a(libbitcoin_server_a-net.o): In function `file_size':
/usr/include/boost/filesystem/operations.hpp:571: undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `boost::filesystem::path::has_root_directory() const':
/usr/include/boost/filesystem/path.hpp:488: undefined reference to `boost::filesystem::path::root_directory() const'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `boost::filesystem::path::has_root_directory() const':
/usr/include/boost/filesystem/path.hpp:488: undefined reference to `boost::filesystem::path::root_directory() const'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_server.a(libbitcoin_server_a-txdb.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_common.a(libbitcoin_common_a-scheduler.o): In function `wait_until<boost::chrono::duration<long int, boost::ratio<1l, 1000000000l> > >':
/usr/include/boost/thread/pthread/condition_variable_fwd.hpp:169: undefined reference to `boost::chrono::system_clock::now()'
libbitcoin_common.a(libbitcoin_common_a-scheduler.o): In function `CScheduler::scheduleFromNow(boost::function<void ()>, long)':
/data/ftc11/ftc0.11.1b/src/scheduler.cpp:107: undefined reference to `boost::chrono::system_clock::now()'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `create_directory':
/usr/include/boost/filesystem/operations.hpp:529: undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `is_directory':
/usr/include/boost/filesystem/operations.hpp:409: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `temp_directory_path':
/usr/include/boost/filesystem/operations.hpp:661: undefined reference to `boost::filesystem::detail::temp_directory_path(boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `SetupEnvironment()':
/data/ftc11/ftc0.11.1b/src/util.cpp:751: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
/data/ftc11/ftc0.11.1b/src/util.cpp:752: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::filesystem::path::operator/=(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/boost/filesystem/path.hpp:325: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `create_directories':
/usr/include/boost/filesystem/operations.hpp:523: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `system_complete':
/usr/include/boost/filesystem/operations.hpp:655: undefined reference to `boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `is_directory':
/usr/include/boost/filesystem/operations.hpp:409: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `file_size':
/usr/include/boost/filesystem/operations.hpp:571: undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::filesystem::path::has_root_directory() const':
/usr/include/boost/filesystem/path.hpp:488: undefined reference to `boost::filesystem::path::root_directory() const'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::filesystem::path::has_root_directory() const':
/usr/include/boost/filesystem/path.hpp:488: undefined reference to `boost::filesystem::path::root_directory() const'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-db.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-db.o): In function `remove_all':
/usr/include/boost/filesystem/operations.hpp:626: undefined reference to `boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `rename':
/usr/include/boost/filesystem/operations.hpp:632: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `exists':
/usr/include/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `operator/':
/usr/include/boost/filesystem/path.hpp:696: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `is_directory':
/usr/include/boost/filesystem/operations.hpp:409: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:497: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `boost::filesystem::path::operator/=(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/boost/filesystem/path.hpp:325: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
collect2: ld returned 1 exit status
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory `/data/ftc11/ftc0.11.1b/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/ftc11/ftc0.11.1b/src'
make: *** [all-recursive] Error 1

**Comment by jonasschnelli** [comment]
Try adding `filesystem` to `--with-libraries=` and don't forget to re-run `./configure` afterwards.

**Comment by feathercoin2** [comment]
Yes, You are right .  I compile all codes success.

**Comment by MarcoFalke** [comment]
Don't forget to close the issue when it is resolved
