### ISSUE TITLE
bitcoin.org releases feed contains no content

### ISSUE THREAD

**Issue by Dreamsorcerer** [bitcoin/bitcoin#7210]
Not sure this is the right place to report, but can't see anywhere more appropriate.

The releases feed does not contain the contents of the posts, only the title, making the feed somewhat useless.

https://bitcoin.org/en/rss/releases.rss

Please put the content of posts into the feed so that we can read about new releases in a RSS feed reader.

**Comment by jonasschnelli** [comment]
Should be reported here: https://github.com/bitcoin-dot-org/bitcoin.org
This repository does focus on core development.
