### ISSUE TITLE
CPU and network are loaded synchronously while synchronizing with network

### ISSUE THREAD

**Issue by polkovnikov-ph** [bitcoin/bitcoin#7211]
When running Bitcoin Core for the first time I've found that network and CPU are loaded alternately. Couldn't we use resources more effectively?

Network usage graph:
![debug](https://cloud.githubusercontent.com/assets/2983969/11785511/2284abea-a27a-11e5-8308-62b0a76b75d0.png)

CPU graph (not as graphic; the last drop in the graph correlates with increased network load):
![cpu](https://cloud.githubusercontent.com/assets/2983969/11785588/6d6e8810-a27a-11e5-9679-b74ffcadf232.png)

**Comment by laanwj** [comment]
Where do you get "alternately" from?

What would be expected when your network is able to download the blocks faster than your CPU can validate them (the usual case) is that the CPU is continuously loaded and the network usage goes on/off.

**Comment by polkovnikov-ph** [comment]
@laanwj As you can see from the graphs neither CPU nor network is continuously loaded. I would rather expect it to load data as fast as it can, and validate data as they get available.

**Comment by Kimax89** [comment]
would it be possible to queue the blocks. so when you need to download the blockchain it will download and queue the second block while the first block is being verified.

**Comment by sipa** [comment]
We already do that.

But there is a limit to how far downloading is allowed to go further than
synchronization (it's a fixed number of blocks, but I forget the number).
