### ISSUE TITLE
Master IBD -prune + clean shutdown + restart -> Wallet ahead of chain

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#7223]

**Comment by jonasschnelli** [comment]
Did you use a fresh wallet or did you place a existing wallet.dat?

**Comment by laanwj** [comment]
Strange. I've had cases where the wallet had to catch up, but never it was ahead of the chain.
Any details?

**Comment by sipa** [comment]
I believe this was due to a wallet.dat being already present on the 21 computer, and me not realizing that.
