### ISSUE TITLE
Bitcoin Core is unstable in the presence of sudden OS crashes

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#7233]
Bitcoin Core is unstable in the presence of sudden OS crashes. There are two scenarios that cause problems which I experienced:
1. Sudden power loss
2. Stopping a Virtual Machine suddenly

The symptoms are:
1. A lengthy "verification" operation on the next startup
2. Sometimes, reindexing of blocks is necessary because some "corruption" is reported (this is so slow that deleting all blocks and syncing from the network is faster)

Are Bitcoin Core databases not crash consistent? I'm used to the situation that databases tolerate sudden power loss without loss of data or consistency. This is a core feature of "Enterprise" RDBMSes for example, and it does work as advertised in practice. Could we have crash consistency for Bitcoin Core, too?

I imagine this can be a problem for automated operations because during the "reprocessing" phase the software is unavailable.

In case this is considered a bug, maybe there should be automated tests for crash consistency (e.g. powering off a VM suddenly).

This was version v0.10.2, run both on real hardware as well as virtualized on VMWare.

**Comment by luke-jr** [comment]
The first step to reporting any bug, is to see if it's already fixed. Do you still have this problem with 0.10.4 or 0.11.2?

**Comment by GSPP** [comment]
I'll test that and report back.

**Comment by sipa** [comment]
0.11.something fixed some LevelDB consistency errors for Windows systems.
If you're on Windows, you should certainly try that.

The long catch-up after a crash is due to very aggressive caching, and
delayed writing.

Lastly, -reindex should always be faster than downloading from scratch, as
it is performing the exact same operations, only fron disk instead of from
network.

**Comment by GSPP** [comment]
Yeah, I do not understand why reindex was slower. This is on magnetic disks. Maybe I hit fragmentation or otherwise unfortunate IO patterns.

**Comment by MarcoFalke** [comment]
@jonasschnelli Dis some tests in a windows VM: https://github.com/bitcoin/bitcoin/pull/6917#issuecomment-153701710

**Comment by GSPP** [comment]
I just performed the simplest possible test: Kill the VMWare VM while syncing from the network:

![eruheiruhgaer](https://cloud.githubusercontent.com/assets/12032350/11963639/a55e5dc6-a8e8-11e5-96e1-4a4b63d424f7.PNG)

So I would propose that automated tests for crash scenarios are added. Note, that killing the bitcoin process might not be enough to detect such problems because killing a process does not discard OS-level write back data. Killing a VM should be a much better test.

**Comment by hamiltino** [comment]
hey i get the same problems on linux its so annoying!

**Comment by NicolasDorier** [comment]
I'm surprised, on my side did not have this problem for a while, @GSPP can you wait for the sync to be complete, and they shutdown the VM as you have done and see if the block database fail ?

**Comment by EthanBianchi** [comment]
I have tried this on Windows 8/10 and have experienced the same bug. 
When my block database is completely synchronized and caught up it doesn't seem to occur. 

However, when my QT client is "catching up", or synchronizing (Whether it's from scratch, or just updating since a reboot) it gives me the message that it is corrupted and needs to be re-built. 

So it seems to only occur during synchronization, but not when completely sync'd.

**Comment by GSPP** [comment]
I just caught Bitcoin Core in the act:

![dnrtjrtj](https://cloud.githubusercontent.com/assets/12032350/12518333/4dd26c60-c138-11e5-9c5d-357ba1a9b332.PNG)

Data is not flushed and exposed to OS crashes and power losses.

Repro steps:

1. Put the software into a syncing state
2. Exit cleanly
3. Confirm program is existed using task manager
4. Use RAMMap to see the unflushed data

I would expect Bitcoin to always flush files to disk to obtain crash consistency.

Also, I wonder what happens in case of power loss *during* flushing. The software must tolerate partial writes as well.

@sipa

**Comment by GSPP** [comment]
Turns out after cleanly shutting down the VM Bitcoin Core wants to verify the blocks on the next startup. I see no reason this is necessary. I suspect there's at least one more issue here besides the missing flushing because this time I did ensure flushing.

To summarize the scenario:

- Latest Core version, upgraded from 0.10
- VMWare Workstation 11.1.3
- Windows 7 x64 SP1
- 6GB RAM, 8 of 8 CPU cores

Also during syncing, without shutting down I found this particular state:

![a](https://cloud.githubusercontent.com/assets/12032350/12519125/2cbb43e4-c13d-11e5-88d0-5afb468882e1.PNG)

Doesn't this mean that in case of power loss the blocks and the chainstate index might become out-of-sync? Maybe the block makes it to disk but the index does not. Or, the other way around. Or, only some of the disk blocks of each make it and the other ones are zeroes.

Maybe, the wallet is also not properly flushed: https://github.com/bitcoin/bitcoin/issues/7249#issuecomment-166962314

**Comment by GSPP** [comment]
https://news.ycombinator.com/item?id=2526311

This sounds like without `sync == true` random corruption and inconsistency can occur. But even *with* syncing different leveldb databases can become inconsistent with respect to each other. Not sure if this is the case here. Just mentioning the possibility.

https://github.com/bitcoin/bitcoin/search?utf8=%E2%9C%93&q=WriteOptions Looks like `sync` is not set in cases.

**Comment by laanwj** [comment]
See also #5610

**Comment by GSPP** [comment]
I just experienced this on Bitcoin Core version v0.12.1 (64-bit). This problem is significant because when it strikes Bitcoin Core becomes unusable for most purposes for a few days while the database rebuilds.

Can anyone else reproduce this? Steps are above (https://github.com/bitcoin/bitcoin/issues/7233#issuecomment-166707144).

I imagine fixing this is not too hard (?) because most database systems are built with crash consistency in mind. Maybe all that is needed is changing some LevelDB settings?

Also note, that quite a few people are being affected by this: https://www.google.com/webhp?complete=1&hl=en#q=bitcoin+core+database+corrupted&complete=1&hl=en&start=0

**Comment by GSPP** [comment]
I repeatedly killed Bitcoin Core 0.13 which did not cause corruption. The issue might have gone away. But I'm not quite certain of that yet.

**Comment by NicolasDorier** [comment]
on my side I got a corruption my USB drive unplugged because of bad cable when I moved it. It was in the block verification phase when it happened.
Anyway, it is not as frequent as before, first time it happens to me since several months.

**Comment by GSPP** [comment]
I can reproduce this quite reliably:

1. Delete the chainstate.
2. Let the software sync for a while (e.g. 10 minutes or until "4-3 years behind"). Sync from the blocks on disk, not from the network. Possibly, this is required to reproduce (if only because of increased load).
3. Power of (not shut down) the VMware Workstation VM
4. In 1/2 cases the database becomes corrupted and must be rebuilt

This is Bitcoin Core version v0.13.0 (64-bit) on Win7 x64.

Syncing just a few seconds does not cause this.

**Comment by GSPP** [comment]
Now I had a new phenomenon: I let it catch up to 33 weeks behind, then exited Bitcoin Core normally. When the process had naturally exited, the chainstate folder was just a few KB in size and indeed after starting the software it is now re-syncing from disk. This is new.

Trying it now on a completely fresh Win7 SP1 x64 VM with just Bitcoin Core installed: Killing the process 6 times never caused corruption. Powering off the VM frequently causes corruption. This is on a magnetic disk now and the corruption comes about 1 in 3 times. So this test shows that the Windows instance is not somehow messed up.

I unplugged my SSD once. Also caused corruption.

Just checked the NTFS file systems in all test VMs: No corruption. This is evidence against the disks violating their durability guarantees.

Tonight I experienced a blue screen. The old VM became corrupt. The new VM did not report corruption but reindexing started at block zero.

I can only encourage you to experiment with different ways of interrupting Bitcoin Core. You will find "unexplained phenomena".

**Comment by gmaxwell** [comment]
I believe this issue should be closed.  We purposefully do not sync during initial block download for performance reasons, this is known and intentional and I believe also documented.

**Comment by marienuac** [comment]
This has nothing to do with initial block download... i too get this problem, the client is too sensitive to poweroutages, or NAS timeouts.

**Comment by GSPP** [comment]
@gmaxwell would there be a way to at least not create corruption during initial sync? Some kind of periodic checkpointing maybe.

Syncing can take a *very* long time (such as days depending on hardware).
