### ISSUE TITLE
Wallet.dat consistency check

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#7239]
Not sure if i should ask it here but it is the only place i know of i could securely ask.

Does Bitcoin Core UI/Client check for wallet.dat consistency on every startup? Does it check on startup if wallet.dat has all the correct private keys for every public key it contains? More importantly the private keys of those public keys listed in the UI on demand of "Request payment" button.
(Does it also check when pressing that button?) 

I've been afraid of the hypothesis of sending coins to some address that i don't really have the private key due to some system failure.

**Comment by jonasschnelli** [comment]
Every keypair that was loaded from the `wallet.dat` file, will be checked thought a EC sign/verify operation. So it's probably impossible to have a public key in your wallet where you don't have the corresponding private key (unless you use `impogrtaddress` or `importpubkey`).

But – if you assume your computer is compromised – nothing can stop an attack that would end up in lost/stolen coins. If you want to prevent from such attacks, create a cold storage (simple way: use a trusted offline computer, run Bitcoin-Core there, use it to keep private keys and use it for signing transactions) or use a hardware wallet.

My personal recommendation: don't keep private keys on your standard computer, even if encrypted.

**Comment by LongShao007** [comment]
Bitcoin-Core generate a public key from a private key

**Comment by louzada1** [comment]
>Every keypair that was loaded from the wallet.dat file, will be checked thought a EC sign/verify operation.

I suppose it is only done when the public keys are created? So the private keys should be always correct. But what if in some system failure, bug or harmful malicious attack the private key gets corrupted or missing after its creation and before you can do a backup? Will the wallet still start up as if everything was fine?

**Comment by pstratem** [comment]
@louzada1 every key pair is checked on ever load

**Comment by louzada1** [comment]
@pstratem is it loaded on every startup? 
If a wallet is encrypted how is possible that the key pair would be checked?

**Comment by pstratem** [comment]
@louzada1 encrypted wallets are checked when the password is entered the first time.

This really isn't an issue at all.

**Comment by laanwj** [comment]
The question has been answered, and the original poster has gone *poof* from github.

Closing this.
