### ISSUE TITLE
-keypool don't change wallet.dat size 

### ISSUE THREAD

**Issue by bom64** [bitcoin/bitcoin#7240]
It look as -keypool is not working if the wallet.dat exist in Windows 10.

Eg. the wallet.dat file is 88 kbyte.  

Close bitcoin-qt.exe
Run 
bitcoin-qt.exe -keypool=20000

Expected that the size of wallet.dat file will expend, but is it still 88 kbyte.

Close bitcoin-qt.exe
Rename wallet.dat to wallet_org.dat
Run
bitcoin-qt.exe -keypool=20000

Now a new wallet.dat file is created and the file grow to 12,5 MB.

Bug:
It look as -keypool only work when creating a new wallet.dat 
Tested when the  wallet.dat have pwd and without pwd.

Maybe some user believe that the have created a big key pool and believe that they have backup of the prv keys.... Let os hope that they don't need the backup...

Donation: 1AcJkAqNNLa2MrLLQdN5oq5CBVX91hTicZ

**Comment by jonasschnelli** [comment]
Not sure if we should call this a bug. Once your wallet is created, the keypool can only be refilled by retrieving more address/keys than the pool holds OR by calling `keypoolrefill` (RPC).

Also keep in mind, that wallets can be encrypted, auto-keypool-topup would not work for encrypted wallets (users need to enter the password first).

But we could change the `-keypool` info text (current: `Set key pool size to <n> (default: %u)`, new maybe something like: `Set key pool size to <n> (default: %u, does not refill keypool if wallet already exists)`.

**Comment by bom64** [comment]
And some info text to the user when using -keypool when the wallet exist.

**Comment by MarcoFalke** [comment]
You can type  `keypoolrefill` into the console (`Help`->`Debug window`->`Console`).

I agree with @jonasschnelli , the help text needs adjustment.

@bom64 Could you create a pull request fixing the help text?

**Comment by bom64** [comment]
I have created a pull request fixing and added keys to my wallet.dat:
getwalletinfo
{
"walletversion" : 60000,
"balance" : 0.00039900,
"unconfirmed_balance" : 0.00000000,
"immature_balance" : 0.00000000,
"txcount" : 4,
"keypoololdest" : 1450683114,
"keypoolsize" : 20001,
"unlocked_until" : 0
}
