### ISSUE TITLE
Sendrawtransaction doesn't have a way to override certain types of transaction rejections

### ISSUE THREAD

**Issue by jameshilliard** [bitcoin/bitcoin#7241]
I was attempting to add a pool payout directly to my mining pool's mempool using sendrawtransaction, however I had generated the payout with a wallet with a different dust threshold due to the pool running a significantly higher minrelaytxfee(to filter spam) than the cold wallet I use to generate batched payouts from. 

I got this error when I tried to send the transaction using the rpc interface and haven't found a way to override it other than adjusting minrelaytxfee on the pool's node(which isn't really a solution since CNB/GBT performance degrades significantly when the mempool gets too big). I saw there was an override but it only appeared to do anything for high fees checks.

> error: {"code":-26,"message":"64: dust"}

I think there should be a flag to only run the base validity checks on the transaction when sent through sendrawtransaction and skip the is-standard checks so that nonstandard transactions can be added to the mempool manually, maybe a way to adjust the dust thresholds independently from minrelaytxfee would also be good to have.

**Comment by MarcoFalke** [comment]
Related: #6824

**Comment by laanwj** [comment]
The basic idea here is not to send transactions that we'd not accept ourselves. Given no other information that's a realistic assumption in a P2P network.

I wouldn't be against a way to force a transaction into the mempool, but it should be made clear that this is only useful if you're a miner.

**Comment by jameshilliard** [comment]
@laanwj Yeah, the intention here is that this would mainly for use by pools, the only other use case I can see this being good for would be for situations were a node's local policy is more restrictive due to some other config option than the the rest of the network, which seems to be the case here since the dust limit is tied to minrelaytxfee(I can see the logic in this but I think we should have a way to manually override it). I think the best way to do this would be to also have a flag to set the submitted transaction to maximum priority when being submitted through sendrawtransaction.

**Comment by pstratem** [comment]
@jameshilliard this can be accomplished by calling proritizetransaction before sendrawtransaction

**Comment by jameshilliard** [comment]
I tried that and it didn't help.

**Comment by pstratem** [comment]
@jameshilliard What was the rejection message?

Possibly the transaction had no fees at all so hit the "free" transaction code before being checked against the fee deltas map.

**Comment by jameshilliard** [comment]
It was the dust error in the OP. Transaction did have a fee so don't think it was that.

**Comment by pstratem** [comment]
@jameshilliard oh right... yeah the deltamap doesn't override the dust limit

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
