### ISSUE TITLE
Loading a wallet using an incompatible BDB version gives a non-specific error in Bitcoin Core

### ISSUE THREAD

**Issue by tulip0** [bitcoin/bitcoin#7247]
![error](https://cloud.githubusercontent.com/assets/15009664/11968962/c03c4454-a966-11e5-9362-4357b2556208.png)

Crashing is the expected response, but the error dialog should give more detail.

**Comment by sipa** [comment]
Non-specific is a mild understatement.

**Comment by jonasschnelli** [comment]
Hah. Nice error message. Will take a look at it.

**Comment by jonasschnelli** [comment]
Bug confirmed with 0.11.2, fixed in current master:

<img width="488" alt="bildschirmfoto 2015-12-23 um 10 06 29" src="https://cloud.githubusercontent.com/assets/178464/11973675/e56b819a-a95c-11e5-9ffe-c2f6fa1a2cbd.png">

Closing.
