### ISSUE TITLE
bitcoin-qt -rescan does nothing

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#7254]
It appears that I'm stuck in a situation where `-rescan` does nothing. I assume it did nothing because it happened so quickly. I'm just 19 hours behind the network, so there should be a lot of data to scan.

The log reads:

2015-12-25 20:07:50 init message: Rescanning...
2015-12-25 20:07:50 Rescanning last 390031 blocks (from block 0)...
2015-12-25 20:07:50  rescan                   47ms
2015-12-25 20:07:50 init message: Activating best chain...

And command line was:

    bitcoin-qt.exe -rescan

I'm rescanning as part of a wallet salvage operation. The wallet file might be broken. It underwent salvage.

This is 0.11.2.

**Comment by pstratem** [comment]
@GSPP looks kind of like you dont have any keys in your wallet...

**Comment by GSPP** [comment]
`dumpwallet` dumps tons of keys. One of them is not `reserve=1`.

**Comment by MarcoFalke** [comment]
@GSPP Can you check if `-salvagewallet` failed? (Pick an address from the old wallet and do `dupmprivkey $oldAdd` in the debugwindow when your new wallet is loaded.)

**Comment by MarcoFalke** [comment]
It is expected to not do a rescan when all your old keys are "gone" and you have a fresh wallet.

**Comment by GSPP** [comment]
@MarcoFalke that makes sense.

The system in question has meanwhile been destroyed so I can no longer perform experiments on it. If it's not possible to make progress on this issue feel free to close it.
