### ISSUE TITLE
Wallet creattransaction is not clean code, should be revised

### ISSUE THREAD

**Issue by sidhujag** [bitcoin/bitcoin#7260]
Specifically the fee part and the fact that you wait until the end to check enough fees or continue. Needs revision.. Seems like it was added on over time and resulted in code thats not clean to a new developer

**Comment by jonasschnelli** [comment]
Can you be more specific? 

Do you think the way of how core's wallet calculate the fee (endless iteration until we have enough fee) is suboptimal? What would be your approach? 

Keep in mind that increasing the fee might require an additional input which enlarges the transaction (which requires more fee).

**Comment by laanwj** [comment]
You're always welcome to improve this.
But this is too aspecitic to be an open issue, so closing.
