### ISSUE TITLE
undefined reference to `secp256k1_ecdsa_sign_recoverable'

### ISSUE THREAD

**Issue by doged** [bitcoin/bitcoin#7261]
going through the make process, i run into this error:
(i tried running a git clean)

testb0x@testb0x-VirtualBox:~/bitcoin$ make
Making all in src
make[1]: Entering directory '/home/testb0x/bitcoin/src'
make[2]: Entering directory '/home/testb0x/bitcoin/src'
make[3]: Entering directory '/home/testb0x/bitcoin/src/secp256k1'
make[3]: Leaving directory '/home/testb0x/bitcoin/src/secp256k1'
  CXXLD    bitcoind
libbitcoin_common.a(libbitcoin_common_a-key.o): In function `CKey::SignCompact(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> >&) const':
/home/testb0x/bitcoin/src/key.cpp:204: undefined reference to `secp256k1_ecdsa_sign_recoverable'
/home/testb0x/bitcoin/src/key.cpp:206: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
libbitcoin_common.a(libbitcoin_common_a-pubkey.o): In function `CPubKey::RecoverCompact(uint256 const&, std::vector<unsigned char, std::allocator<unsigned char> > const&)':
/home/testb0x/bitcoin/src/pubkey.cpp:194: undefined reference to `secp256k1_ecdsa_recoverable_signature_parse_compact'
/home/testb0x/bitcoin/src/pubkey.cpp:197: undefined reference to `secp256k1_ecdsa_recover'
collect2: error: ld returned 1 exit status
Makefile:2759: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory '/home/testb0x/bitcoin/src'
Makefile:6870: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/testb0x/bitcoin/src'
Makefile:636: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
testb0x@testb0x-VirtualBox:~/bitcoin$

**Comment by sipa** [comment]
This is a problem resulting from linking against an older build result of
libsecp256k1.

Try `make clean`. If that doesn't work, try `make clean` inside
src/secp256k1 directory. If that doesn't work, use `git clean -dfx` (which
deletes all non-committed files; be careful if you have other work in the
working directory).

**Comment by luke-jr** [comment]
Our build system is broken, so you will need to re-run autogen.sh and/or configure manually. :(

**Comment by doged** [comment]
@sipa yeah that just took me back to the beginning, make clean didnt work, make clean in secp256k1 didnt work, and git clean -dfx just brought me back in a circle lol

**Comment by doged** [comment]
after trying to do it manually in secp256k1 dir:

testb0x@testb0x-VirtualBox:~/bitcoin/src/secp256k1$ make
./gen_context
/bin/bash: ./gen_context: cannot execute binary file: Exec format error
Makefile:1507: recipe for target 'src/ecmult_static_context.h' failed
make: *** [src/ecmult_static_context.h] Error 126

**Comment by MarcoFalke** [comment]
@doged What is `git log --oneline -1`?

**Comment by doged** [comment]
@MarcoFalke 
be9a9a3 Merge pull request #7214

not sure how that helps.

**Comment by doged** [comment]
@MarcoFalke ?

**Comment by MarcoFalke** [comment]
I just wanted to make sure you are not running an odd commit. And your OS is latest Ubuntu?

**Comment by doged** [comment]
@MarcoFalke correct, ubuntu 15

**Comment by doged** [comment]
been getting alot of permission errors along the way, that might have something to do with it. for some reason i had to chmod+x build_detect_platform in leveldb, etc

**Comment by MarcoFalke** [comment]
I don't think `chmod +x` will solve any issues here. It may even create some. Not sure why people keep doing those...

I can try to revive my Ubuntu box tomorrow and have a look. If you are bored in the meantime. You could try:

```
git reset --hard be9a9a3
git clean -dfx
./autogen.sh
./configure
make
```

and dump the output to some pastebin.

**Comment by doged** [comment]
@luke-jr i keep getting stuck here, which is odd because i can gcc gen_context in the dir, but even still it breaks on build

configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: src/libsecp256k1-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
I. -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
/bin/bash: I.: command not found
Makefile:1497: recipe for target 'gen_context.o' failed
make[3]: [gen_context.o] Error 127 (ignored)
gen_context.o -o gen_context
/bin/bash: gen_context.o: command not found
Makefile:1500: recipe for target 'gen_context' failed
make[3]: *** [gen_context] Error 127
make[3]: Leaving directory '/home/testb0x/bitcoin/src/secp256k1'
Makefile:7378: recipe for target 'secp256k1/libsecp256k1.la' failed
make[2]: *** [secp256k1/libsecp256k1.la] Error 2
make[2]: Leaving directory '/home/testb0x/bitcoin/src'
Makefile:6882: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/testb0x/bitcoin/src'
Makefile:636: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
testb0x@testb0x-VirtualBox:~/bitcoin$ 

why isnt it showing gcc before the -I. ?
is there an easy command line fix for this?

**Comment by MarcoFalke** [comment]
@doged I can't reproduce on a fresh Ubuntu 15.10:

```
$ sudo apt-get install git vim build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
$ sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
$ sudo apt-get install libdb-dev libdb++-dev 
$ sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
$ git clone https://github.com/bitcoin/bitcoin.git
$ cd bitcoin/
$ git log -1 --oneline 
be9a9a3 Merge pull request #7214
$ ./autogen.sh ;./configure --with-incompatible-bdb; make

**Comment by theuni** [comment]
@doged sounds like it's not finding your native gcc. Try exporting CC_FOR_BUILD=gcc

**Comment by doged** [comment]
@theuni that fixed it. submitting pull request and closing. i hope this helps anyone else who runs into this issue on a fresh install.
