### ISSUE TITLE
Why is OP_CHECKLOCKTIMEVERIFY using a signed value?

### ISSUE THREAD

**Issue by ciyam** [bitcoin/bitcoin#7275]
I was able to successfully create a "regtest" CLTV redeem script for a P2SH address using the block number 0x7f but if I change it to 0xff (which I thought should be block 255) it won't work (giving me a "Negative locktime" error).

As nLockTime is unsigned I don't understand why the op code is reading a signed value and testing for it being negative.

Did I miss something?

**Comment by sipa** [comment]
In Bitcoin Script, all numbers are signed, and CLTV uses that mechanism.

**Comment by ciyam** [comment]
then how to check for block 255?

**Comment by ciyam** [comment]
(if I use 0x02ff00 it won't work)

**Comment by ciyam** [comment]
(as it thinks I am adding zeroes when I shouldn't)

**Comment by sipa** [comment]
What error do you get, exactly?

**Comment by ciyam** [comment]
Negative locktime

**Comment by sipa** [comment]
What error do you get when pushing FF 00?

**Comment by ciyam** [comment]
SCRIPT_ERR_NEGATIVE_LOCKTIME

**Comment by ciyam** [comment]
oh - no error

**Comment by ciyam** [comment]
but doesn't work

**Comment by ciyam** [comment]
error: {"code":-26,"message":"64: non-mandatory-script-verify-flag (No error)"}

**Comment by ciyam** [comment]
(so literally it told me "No error")
as the error :D

**Comment by sipa** [comment]
Nice catch, that's a bug in the reporting. I'll fix that.

**Comment by ciyam** [comment]
so - how should I redeem with block 255?
use 0x02ff00 or something else?

**Comment by ciyam** [comment]
btw - you can't send "coinbase' to P2SH using regtest either

**Comment by ciyam** [comment]
(it screws up the sigScriptPub)

**Comment by sipa** [comment]
One issue at a time please.

0xFF00 is indeed how you'd encode 255.

**Comment by ciyam** [comment]
thanks - I can create another issue for the other problem - should I do that?

**Comment by sipa** [comment]
Yes.

See https://github.com/bitcoin/bitcoin/pull/7276/files

**Comment by ciyam** [comment]
Will this work correctly with 3 byte blocks also?

**Comment by luke-jr** [comment]
@ciyam @sipa's change seems to fix the bug where you got "No error" rather than the actual error message. Please redo your test with his patch and report what the real error is.

**Comment by ciyam** [comment]
Actually I think you are right - and I assume that the "Negative locktime" error will still happen.

**Comment by ciyam** [comment]
the relevant code in "interpreter.cpp" is this:
                    // In the rare event that the argument may be < 0 due to
                    // some arithmetic being done first, you can always use
                    // 0 MAX CHECKLOCKTIMEVERIFY.
                    if (nLockTime < 0)
                        return set_error(serror, SCRIPT_ERR_NEGATIVE_LOCKTIME);

**Comment by sipa** [comment]
@ciyam If you pass in a negative number (0x01FF is negative 127), you will get an error about a negative number.

It would be nice if you can redo your test with #7276 merged (that should fix the "No error" reporting when there is a clear failure nonetheless).

**Comment by ciyam** [comment]
Unfortunately I don't have the time to set up an environment for doing testing with Bitcoin but hopefully others that are playing around with the new OP_CHECKLOCKTIMEVERIFY will. I think the issue is easily enough repeated for others to show.

**Comment by ciyam** [comment]
If the rule is that all values for Bitcoin scripts are "signed" then I guess there is perhaps a fundamental problem here (as nLockTime is unsigned).

**Comment by sipa** [comment]
@ciyam You are confusing two things. The fact that all script numbers are signed does not prevent you from creating values that are in range for CLTV. In fact, the input numbers to CLTV can be up to 5 bytes (instead of 4) to account for exactly that.

**Comment by ciyam** [comment]
okay - but does your change allow for 5 bytes?

**Comment by sipa** [comment]
My change? The patch I'm linking to just fixes a bug so it stops reporting
"No error" but reports the actual error.

**Comment by laanwj** [comment]
Closed by  #7276
