### ISSUE TITLE
Cannot send "coinbase" values to P2SH addresses in "regtest"

### ISSUE THREAD

**Issue by ciyam** [bitcoin/bitcoin#7277]
When I try it screws up the scriptPubKey - rather than:OP_HASH160 "hash value" OP_EQUAL
I see this:
"hash value" OP_CHECKSIG

**Comment by sipa** [comment]
Can you elaborate a bit on what you're doing exactly?

**Comment by ciyam** [comment]
sending funds to a P2SH address (that are from "coinbase") using "regtest"

**Comment by sipa** [comment]
Using RPC? What is the expected result, what is the actual result?

**Comment by ciyam** [comment]
I was only able to get things to work correctly when I first sent the funds to another testnet address

**Comment by ciyam** [comment]
literally the UTXO when I sent the funds to the P2SH was this:
"public key hash" OP_CHECKSIG
rather than the usual:
OP_HASH160 "script hash" OP_EQUAL

**Comment by ciyam** [comment]
all I had done was sent funds to a P2SH address (i.e. starting with 2 for testnet)

**Comment by sipa** [comment]
Using sendtoaddress or a similar RPC?

**Comment by ciyam** [comment]
yes

**Comment by ciyam** [comment]
so I first did:
generate 101
then I did:
sendtoaddress 2XXX

**Comment by sipa** [comment]
That type of output is usually only created for coinbase outputs.

**Comment by ciyam** [comment]
so it is done on purpose?
is there a reason for that?

**Comment by ciyam** [comment]
(the output was not supposed to be coinbase as it was supposed to be spending coinbase)

**Comment by sipa** [comment]
How do you notice the produced transaction is wrong?

Can you paste the output of `decoderawtransaction [txid]` where txid is the txid reported by sendtoaddress?

**Comment by ciyam** [comment]
I didn't keep it but for sure it looks like this:
"public key hash" OP_CHECKSIG
rather than this:
OP_HASH160 "script hash" OP_EQUAL

**Comment by ciyam** [comment]
just try and send any coinbase to a P2SH using regtest

**Comment by sipa** [comment]
Are you sure you were looking at the right transaction?

**Comment by ciyam** [comment]
yes - I repeated this many times today
(wasted many hours)

**Comment by ciyam** [comment]
you cannot send to a P2SH address using "regtest" from "coinbase"

**Comment by sipa** [comment]
Can you then please paste the output of getrawtransaction on it?

**Comment by ciyam** [comment]
Hmm.. this is very weird. All day I was having this problem but now when I try and repeat it no such problem. :(

**Comment by ciyam** [comment]
I'm pretty sure there is an issue but of course if I can't repeat it then I understand it can't be looked into.

**Comment by ciyam** [comment]
(now I am very confused as to why this caused me problems today)

**Comment by sipa** [comment]
Feel free to reopen when you can reproduce.
