### ISSUE TITLE
Using "-regtest" for the first time shows silly progress widget

### ISSUE THREAD

**Issue by ciyam** [bitcoin/bitcoin#7279]
Not overly important but it looks a bit silly to see the progress widget saying it is years behind when you are using "-regtest" for the first time.

**Comment by MarcoFalke** [comment]
The (time of the) first block is hard-coded: https://github.com/bitcoin/bitcoin/blob/be9a9a3d2253ceccf123572b97a890c489a5a9be/src/chainparams.cpp#L239

**Comment by ciyam** [comment]
Understood - but it seems to know to hide the progress widget as soon as you generate even one block so why show the widget at all if it is known that you are using "regtest"?

**Comment by MarcoFalke** [comment]
> know to hide the progress widget as soon as you generate even one block

Normally, the time of the second block is the time you create the second block. As long as the time of the last block is less than 90 minutes in the past, there will be no progress bar: https://github.com/bitcoin/bitcoin/blob/be9a9a3d2253ceccf123572b97a890c489a5a9be/src/qt/bitcoingui.cpp#L719

**Comment by ciyam** [comment]
Again - I understand - but if it knows it is running with "-regtest" then why not just hide the progress widget "full stop"?

**Comment by MarcoFalke** [comment]
Regtest is for development only and I don't see how this information could harm.

**Comment by ciyam** [comment]
Sure - as I stated it is just "ugly" so I fully understand if no-one cares to change it - just was reporting.

**Comment by jonasschnelli** [comment]
Agree that it could be confusing. But because this is a dev's/researchers only feature, I think it's not worth changing it / keeping an issue open for it. @ciyam: If you agree, please close the issue.

**Comment by laanwj** [comment]
Regtest is not meant for normal users. It's even hidden in `--help` without `--help-debug`. So minor UI issues that could confuse novice users are not relevant enough to keep open an issue, IMO.
