### ISSUE TITLE
Qt client does not build on Fedora

### ISSUE THREAD

**Issue by stevenroose** [bitcoin/bitcoin#7284]
I tried to map alle the Debian dependencies mentioned in the docs to a Fedora equivalent, but seemingly something is missing.

These are the ones I installed (for the GUI only, `bitcoind` builds fine):

 - `qt5-qtbase-gui` (for `libqt5gui5`)
 - `qt5-qtbase`, `qt5-qtbase-common` and `qt5-qtbase-devel` (for `libqt5dbus5`) ([source](https://rpmfind.net/linux/rpm2html/search.php?query=libQt5DBus.so.5()(64bit)))
 - `qt5-qttools`, `qt5-qttools-devel` and `qt5-qttools-common` (for `qttools5-dev` and `qttools5-dev-tools`)
 - `protobuf-devel` (for `libprotobuf-dev`)
 - `protobuf-compiler` (for `protobuf-compiler`)

The only one explicitly missing is `libqt5core5a`, however since it is the core Qt5 module, I would believe `qt5-qtbase` would have to be good...

These are the outputs of the compilation steps:
https://gist.github.com/stevenroose/cd681bcdaf1ae5b701d8

It might be relevant to note that I have KDE Plasma 5 installed, so I use Qt for almost all my applications.

**Comment by jonasschnelli** [comment]
@stevenroose: I just checked your `make` output. All good... everything was built correctly:

```
---snip---
CXXLD    bitcoind
---snip---
OBJCXXLD qt/bitcoin-qt
---snip---
```

Or what exactly is the problem here?

**Comment by stevenroose** [comment]
Ok, I read documentation that suggested the qt client would be in the `src/` directoy instead of in a separate one. Ok I close this, thanks!
