### ISSUE TITLE
compile  0.11.1 error on Ubuntu 12.04 with boost 1.58

### ISSUE THREAD

**Issue by cqtenq** [bitcoin/bitcoin#7285]
When I compile core 0.11.1, I'm getting a error ," SSLv3_method?.has not been declared"

 CXX    bitcoind-bitcoind.o
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from rpcprotocol.h:16,
                 from rpcserver.h:10,
                 from bitcoind.cpp:7:
/usr/include/boost/asio/ssl/impl/context.ipp: In constructor ?.oost::asio::ssl::context::context(boost::asio::ssl::context_base::method)?.
/usr/include/boost/asio/ssl/impl/context.ipp:93:29: error: ?.:SSLv3_method?.has not been declared
/usr/include/boost/asio/ssl/impl/context.ipp:96:29: error: ?.:SSLv3_client_method?.has not been declared
/usr/include/boost/asio/ssl/impl/context.ipp:99:29: error: ?.:SSLv3_server_method?.has not been declared
bitcoind.cpp: In function ?.ool AppInit(int, char**)?.
bitcoind.cpp:68:30: warning: format ?.s?.expects argument of type ?.har*?. but argument 2 has type ?.har**?.[-Wformat]
make[2]: *** [bitcoind-bitcoind.o] Error 1

**Comment by jonasschnelli** [comment]
This looks like a boost issue. How did you install boost (manually compiled)?

**Comment by unsystemizer** [comment]
Fixed in boost v1.58

**Comment by laanwj** [comment]
Seems like a conflict between openssl and boost versions / compile options. `SSLv3_method` was probably deprecated/removed for security reasons and your version of boost still assumes it present. Also suggest upgrading boost.

As this happens outside of the bitcoin core source base there's nothing that we can do here.
