### ISSUE TITLE
Inconsistency with the way that OP_CHECKLOCKTIMEVERIFY redeem behaves

### ISSUE THREAD

**Issue by ciyam** [bitcoin/bitcoin#7294]
What I have discovered using regtest is that when the locktime is a block number an attempt to redeem will fail before that height is reached (i.e. it won't let you send a tx that has a future block number), however, when the locktime value is a unix timestamp then it will let you send the tx immediately (the tx just won't appear as confirmed).

Perhaps this is intentional - am mostly just reporting because it confused me (I had expected it to behave in the same manner as when the value is a block height).

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
