### ISSUE TITLE
Another miner orphaning all of my blocks 

### ISSUE THREAD

**Issue by mmitech** [bitcoin/bitcoin#7299]
How can someone achieve that ? I am running a pool which represents 70% of the coin's  network hashrate (altcoin of course), I can find few sequential blocks then this miner will mine the next block and orphan all of my previous blocks!

Looked into:

- My blocks are broadcasted/propagated fine (checked that) until the said miner broadcast his blocks.
- Tried changing IPs (thought my node was banned ?!), Changed daemon versions but nothing.
- Made a separate network that gets connected to the mainnet once every few hours, and this also didn't help !!! 

How the heck did this miner achieve this and what can I do about it ?

**Comment by mmitech** [comment]
[More info here](https://bitcointalk.org/index.php?topic=1316339.0)

**Comment by luke-jr** [comment]
This is about Bitcoin?

**Comment by pstratem** [comment]
@luke-jr no it's not

**Comment by jonasschnelli** [comment]
Please don't open issue for altcoins here.
