### ISSUE TITLE
Cannot obtain lock on folder - fixed and was a permissions problem, repeatable

### ISSUE THREAD

**Issue by timb999** [bitcoin/bitcoin#7303]
Hi,

I recently installed BitCoinCore 0.11.2 on my Windows 7 64bit Pro machine.

The first time I ran the program, all was fine, and the blockchain started to sync. I left this for several hours, but needed to turn my PC off so I shut the program down which was successful.

When I rebooted and ran the program again, I received an error saying...

"Cannot obtain a lock on data directory (location here) Bitcoin Core is probably already running"

I have fixed this issue myself and can inform you that this problem arose because the HDD that I am using for BitCoinCore is not C, but a different internal HDD. This HDD was used on a previous PC installation - I then had to reinstall my PC and I am reusing this same HDD. Because this HDD was used on a previous installation, there are permissions problems. I simply went to the folder that BitCoinCore is using and used the 'sharing' tab to give me full permission and this fixed the problem.

Therefore you might want to check this, or implement this into the error message...

Thanks
Tim

**Comment by jonasschnelli** [comment]
I think the `boost::interprocess::file_lock` could not be acquired (file `<datadir>/.lock`) because you had permission issue (maybe occurred with a improper shutdown or a HDD failure or because you used the HDD which was previously used with another computer).

Looks after a local problem to me.

**Comment by MarcoFalke** [comment]
Indeed a local problem, but we could still extend the error message, if appropriate: https://github.com/bitcoin/bitcoin/blob/7b0a9a80400495e263c779d6ddd6c33641f27716/src/init.cpp#L1028

**Comment by jonasschnelli** [comment]
Seems to be a local issue. Feel free to improve the error output. Closing.
