### ISSUE TITLE
walletpassphrase timeout doesn't work in bitcoin-qt

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#7316]
If I am running `bitcoind` then `bitcoin-cli walletpassphrase $pass 5` will unlock my wallet for 5 seconds.

But if I am running `bitcoin-qt` then the same command will unlock my wallet indefinitely, and show an error in the debug.log:

    GUI: QObject::startTimer: Timers can only be used with threads started with QThread

I built from the master branch, commit b1cf0058d9b3d3e218f1dc31ee688e5beb21f573.

**Comment by jonasschnelli** [comment]
Tested and can confirm the issue. Marked a "Priority High" because this can leave a wallet unlocked while expecting it's locked... 
Fortunately this can only happen when running Bitcoin-Qt with `-server` and using `walletpassphrase` over the RPC server (not the GUI rpc console).

**Comment by jonasschnelli** [comment]
@dooglus: Thanks for reporting. Should be fixed with #7317 (#7318).

**Comment by dooglus** [comment]
Thanks for the quick fix. I was surprised to find my wallet still unlocked hours after I had unlocked it for a quick spend, but it's fine again now.
