### ISSUE TITLE
libevent should be optional

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#7325]
non-bitcoind (GUI, tests, etc) should not require libevent to build

**Comment by jonasschnelli** [comment]
Agree. This should work. But when building the GUI without libevent, it should disable the `-server` option.

**Comment by laanwj** [comment]
We are going to use libevent for the P2P code too, so the scope for this is very small.

Potentially the tests and bitcoin-tx could be compiled without it, but it seems not worth the trouble of complicating the build system.
