### ISSUE TITLE
Please sign your statements.

### ISSUE THREAD

**Issue by zookozcash** [bitcoin/bitcoin#7330]
(I already sent this to bitcoin-dev and it was rejected by the moderator with a nice letter saying that they appreciated it and would forward it to the appropriate parties. Since I don't know who the appropriate parties are or how to communicate with them, and since I want to have a public, linkable, and permanent copy of this request, I'm opening this ticket. I hope you don't mind the use of the issue tracker for this purpose. I feel that it is borderline but is an appropriate use of the issue tracker.)

Dear Bitcoin Core folks:

I really appreciate
https://bitcoin.org/en/bitcoin-core/2016-01-07-statement, and
https://bitcoin.org/en/bitcoin-core/capacity-increases-faq, and
https://bitcoin.org/en/bitcoin-core/capacity-increases.

I feel that having succinct and specific statements like this are very
helpful, for users and potential collaborators. I feel like that even,
or especially, when I personally disagree with some of the assertions
or strategies stated therein. So thank you very much for taking the
effort to do it!

I do have one request: would you please disclose the names of the
authors? I understand that the statement has been ACKed by a number of
people, but that's not the same thing. I also understand that there
are presumably multiple authors, and a grey area of people who
contributed a little, but perhaps not enough to be counted as
co-authors. Despite all those difficulties, having the names of
authors of statements like this is important, both for evaluation, for
facilitating communication, and for the historical record.

If for some reason you're uncomfortable publicly claiming your
authorship of a document like this, then please pick a persistent nom
de plume for this purpose.

I feel that this is important, and that by publicly signing your name
to your words you can significantly increase the positive impact that
your words can have.

Sincerely,

Zooko

**Comment by zookozcash** [comment]
Here is the note I got from the bitcoin-dev moderators denying my post:

"""
 Zooko, thank you for your post and the suggestions.

Obviously the post is not intended or appropriate content for the
bitcoin-dev list but be sure to know your email will be forwarded on
to the correct people and that it is appreciated.
"""

**Comment by kanzure** [comment]
@zookozcash, you say,

> and since I want to have a public, linkable, and permanent copy of this request

This looks like a bug to me. Rejected emails should appear here:

https://lists.ozlabs.org/pipermail/bitcoin-dev-moderation/

Since your email does not appear there, this seems like a bug you should have reported to the moderators, instead of the Bitcoin Core issue tracker.

**Comment by jonasschnelli** [comment]
This is the wrong place for discussions of that type. Closing.

**Comment by zookozcash** [comment]
The problem is, what's the right place? :-( How can I communicate with you, if 1. I don't know your names, 2. I can't write to the -dev mailing list, 3. I can't open a ticket on the issue tracker. What's left?

**Comment by NicolasDorier** [comment]
maybe https://github.com/bitcoin-dot-org/bitcoin.org/issues

**Comment by jonasschnelli** [comment]
IRC?

**Comment by zooko** [comment]
FWIW: https://botbot.me/freenode/bitcoin-core-dev/2016-01-12/?msg=57806833&page=4
