### ISSUE TITLE
Amount parser is too strict

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#7331]
{"mvjWntqo6nos9XuskZPyvnWUqR69SqAJsh": 5.4750000000000005, "mugHAcC484RLgqNS8hr1aBk7fhMMaFxuUY": 5.495}

JSONRPC error: Invalid amount

Many JSON serialisers do not give people the freedom to choose exact precision of Numbers.

**Comment by pstratem** [comment]
Disagree, this is dealing with money.

Precision is important.

**Comment by MarcoFalke** [comment]
There seems to be some disagreement within the code:

* "**rounded** to the nearest 0.00000001" https://github.com/bitcoin/bitcoin/blob/dd1304ec216c7d4bdb302195e184b15503819f67/src/wallet/rpcwallet.cpp#L391
* "**return false**; // cannot represent values smaller than 10^-8" https://github.com/bitcoin/bitcoin/blob/dd1304ec216c7d4bdb302195e184b15503819f67/src/wallet/rpcwallet.cpp#L391

**Comment by MarcoFalke** [comment]
I think we already had this and the workaround was to use strings. Still, something needs to be done to solve this issue.

**Comment by jonasschnelli** [comment]
I agree with @pstratem.

The parser is not affected IMO. You probably mean the client side JSON encoder. Because bitcoind RPCs input structures are relatively simple, you could - in case of problematic rounding/percicions -  easily write your one JSON encoding.

A solution to this "problem" would be to change every monetary amount to int32 satoshis. But to do this, it would require a v2/ RPC API, which is a overkill IMO.

**Comment by MarcoFalke** [comment]
@jonasschnelli You can represent every *valid* amount of bitcoins as a double. In case the exact representation is not possible, you can get back the original amount by rounding. There will never be an issue up to 21e6. I think the first off-by-one satoshi rounding error is somewhere in the order of 60e6.

I see no reason to drop support for floating point. Especially given that the documentation indicates that rounding was intended and probably working in earlier versions of core. Can someone test this with 0.9, etc?

**Comment by laanwj** [comment]
We've explicitly decided not to use rounding in the parser. Amounts that cannot be represented in our number format (.8 decimal fixed point) are rejected.

**Comment by MarcoFalke** [comment]
@laanwj So the documentation needs update?

**Comment by laanwj** [comment]
Yes
