### ISSUE TITLE
Add NoRBF to URI Scheme 

### ISSUE THREAD

**Issue by seweso** [bitcoin/bitcoin#7343]
Before Opt-In RBF is deployed it is probably wise to be able to indicated that RBF is not supposed to be used in a payment.

This might have the added benefit of showing that RBF does not actually kill zero-conf (which many people wrongfully believe).

**Comment by luke-jr** [comment]
Core's wallet never sets the RBF flag anyway, so there is literally nothing to add here.

**Comment by seweso** [comment]
It is not even going to be an option?  Or is that something which will only be added when there is also the option to actually manage RBF transactions? 

Know anything about other wallets who are preparing to enable RBF transactions/management? Would they be able to define a new NoRBF flag amongst themselves?

**Comment by jonasschnelli** [comment]
There are two open RBF related PRs:
* https://github.com/bitcoin/bitcoin/pull/7159 ([RPC] Add RBF opt-in possibilities to rawtx functions)
* https://github.com/bitcoin/bitcoin/pull/7132 (Add option to opt into full-RBF when sending funds)

I'm also working on a QT RBF option.

**Comment by laanwj** [comment]
Which URI scheme?

**Comment by sipa** [comment]
I guess this would require an extension to BIP21.

**Comment by seweso** [comment]
@sipa Yes. It only needs to be a "if you do this, then do it this way please" kind of thing. If Core doesn't ever opt-in to RBF then this doesn't need to be implemented yet. But would be nice if it would get implemented eventually. (But that needs it's own issue)

**Comment by dcousens** [comment]
@seweso maybe follow up `BIP21` with an extension?

**Comment by seweso** [comment]
https://github.com/bitcoin/bips/compare/master...seweso:patch-1

Although maybe it should be fullrbf=0, because parameter names with "no" in it are weird.

**Comment by laanwj** [comment]
Ah, you mean BIP21. You can't just change BIP21, it would need to be a new BIP that extends it, like BIP72.

At which point you'll probably get the question 'why add the flag to the URI, not to the Payment Protocol'?

**Comment by seweso** [comment]
@laanwj I know what I want, not the how. That's why. Wouldn't an issue tracker for Bip's be handy? For mere mortals I mean

**Comment by laanwj** [comment]
> Wouldn't an issue tracker for Bip's be handy? For mere mortals I mean

A central tracker wouldn't work for that. There is no one responsible for BIPs *in general*. Everyone can submit a BIP and becomes the author of that.

The most that you can do is mail the author of the specific BIP with your concerns/issues. But as said, be aware that BIPs like BIP22 are set in stone by sake of being implemented by a lot of different software. So the only way to propose an extension is to create a new BIP (see https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki for information on creating BIPs), not by changing the old one.

**Comment by seweso** [comment]
@laanwj Well some kind of naming convention for extension BIP's would be nice (like BIP21E01). And having the entire scheme in one place is handy. Is there something like that? 

Is the name "NoRBF" at least reasonable?

**Comment by dcousens** [comment]
`seweso` URI's benefit from being compact,  at the most I'd say `rbf=0/1` would be better.

**Comment by laanwj** [comment]
You don't need a new naming convention. BIPs have a number, not a name. There is no issue heree, you can just refer to the original BIP. I've given an example above of another BIP that extends the URI scheme.

Would be better to discuss this on the -dev mailing list instead.

**Comment by laanwj** [comment]
As said above, this needs a BIP with an URI extension proposal, this cannot be considered before that. Closing as this is the wrong place.
