### ISSUE TITLE
gettxoutsetinfo returns empty dict on Raspberry Pi 2

### ISSUE THREAD

**Issue by oriste** [bitcoin/bitcoin#7344]
It takes from 5 (shortest) to almost 40 (longest) minutes for `bitcoin-cli gettxoutsetinfo` to return an *empty* dict. I noticed this first whilst configuring the Statoshi branch of Bitcoin Core, but went back to install Bitcoin Core (git clone -b v0.11.2 https://github.com/bitcoin/bitcoin.git) to find the same results.
```
20:10 pi@raspinode:~/bin/bitcoin.orig $ bitcoin-cli gettxoutsetinfo
{
}
20:12 pi@raspinode:~/bin/bitcoin.orig $ bitcoin-cli getinfo
{
    "version" : 110200,
    "protocolversion" : 70002,
    "blocks" : 393193,
    "timeoffset" : 0,
    "connections" : 12,
    "proxy" : "",
    "difficulty" : 113354299801.47113037,
    "testnet" : false,
    "relayfee" : 0.00005000,
    "errors" : ""
}
20:17 pi@raspinode:~/bin/bitcoin.orig $
```
Raspberry Pi 2 - 1GB memory - 4 core CPU 900MHz - Blockchain on SanDisk Ultra Android microSDXC 128GB up to 80 MB/Sec Class 10

All other RPC calls through bitcoin-cli are answered promptly and correctly.
See also issue on jlopp/statoshi https://github.com/jlopp/statoshi/issues/19#issuecomment-171350739

**Comment by unsystemizer** [comment]
Same bitcoin version, same h/w, ran 4 times, the first time I didn't measure, but the other three were all 7 mins. Don't see a problem.
```
$ bitcoin-cli getinfo
{
    "version" : 110200,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 393556,
    "timeoffset" : -3,
    "connections" : 4,
    "proxy" : "",
    "difficulty" : 113354299801.47113037,
    "testnet" : false,
    "keypoololdest" : 1446923210,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : "WARNING: check your network connection, 5 blocks received in the last 4 hours (24 expected)"
}

$ time bitcoin-cli gettxoutsetinfo; time bitcoin-cli gettxoutsetinfo;time bitcoin-cli gettxoutsetinfo;
{
    "height" : 393552,
    "bestblock" : "000000000000000008b1f531b928c1d27d61581d49f672de1b67d1c15330e2b8",
    "transactions" : 8491980,
    "txouts" : 33700542,
    "bytes_serialized" : 1142479068,
    "hash_serialized" : "6e9f737f9b893f06ce833e609407082c9ca0d35b6ce3d68cf8332df25fb0930c",
    "total_amount" : 15088661.13371732
}

real    7m21.845s
user    0m0.030s
sys     0m0.020s
{
    "height" : 393552,
    "bestblock" : "000000000000000008b1f531b928c1d27d61581d49f672de1b67d1c15330e2b8",
    "transactions" : 8491980,
    "txouts" : 33700542,
    "bytes_serialized" : 1142479068,
    "hash_serialized" : "6e9f737f9b893f06ce833e609407082c9ca0d35b6ce3d68cf8332df25fb0930c",
    "total_amount" : 15088661.13371732
}

real    7m20.363s
user    0m0.050s
sys     0m0.010s
{
    "height" : 393552,
    "bestblock" : "000000000000000008b1f531b928c1d27d61581d49f672de1b67d1c15330e2b8",
    "transactions" : 8491980,
    "txouts" : 33700542,
    "bytes_serialized" : 1142479068,
    "hash_serialized" : "6e9f737f9b893f06ce833e609407082c9ca0d35b6ce3d68cf8332df25fb0930c",
    "total_amount" : 15088661.13371732
}

real    7m23.635s
user    0m0.030s
sys     0m0.020s

```

**Comment by oriste** [comment]
Interesting. Thanks for taking the trouble. I tried 3 more times your way and got times between 9m56s and 12m34s. Each time with an empty dict as result.
The only difference I can see is that my version is compiled with the --disable-wallet option. I'll try tonight to recompile with the wallet option.

**Comment by unsystemizer** [comment]
Yeah, I should mention that I watched IO and it's usually around 1.6 to 3.6 MB/s with only abuot 100 or  so IO requests per second and that I use an actual external SANDisk SSD. Maybe there's better performance consistency on that device for this type of workload. 
I run both mainnet and testnet on this Pi, both with wallet enabled.

**Comment by laanwj** [comment]
This RPC call is expected to take a lot of time.
It may be that a timeout happens. Try setting this to a higher value when calling bitcoin-cli (option only on 0.12.x and master):
```
  -rpcclienttimeout=<n>
       Timeout during HTTP requests (default: 900)
```

**Comment by laanwj** [comment]
I think the timeout issue is a red herring here. An empty `gettxoutsetinfo` indicates that `GetUTXOStats()` failed. In that case an error will have been logged, check your debug.log. Most likely there is corruption and you need to reindex.
