### ISSUE TITLE
Daemon server error,OpenBlockFile failed

### ISSUE THREAD

**Issue by cqtenq** [bitcoin/bitcoin#7355]
I run core 0.11.1 daemon about a week ,today I'm getting a error, can not read block from disk.

Debug.log
ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)
ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)

**Comment by jonasschnelli** [comment]
What operating system do you use? Virtualized?
What type of disk? SSD, spinning?

**Comment by cqtenq** [comment]
Ubuntu 12.04.5,   Virtualized

**Comment by laanwj** [comment]
This is a different issue from your run-of-the-mill disk corruption.

I wonder what makes `nFile==-1` get passed to OpenBlockFIle.

- Does this happen on startup?
- Do you have pruning enabled?

**Comment by tarakanbg** [comment]
I started getting the exact same error happening intermittently after upgrading to v. 0.12 and enabling pruning (prune=3000) on Ubuntu 14.04 SSD (Digital Ocean Droplet). It happens 1-2 times per day when receiving a transaction, on 0 confirmations and then again on 1st confirmation. Most transactions are received and processed normally. When this error occurs I don't get a `wallet_notify` event for the transaction in question, however its balance and details appear in the wallet.

**Comment by MarcoFalke** [comment]
Bitcoin Core makes heavy use of CPU, RAM and disk IO. Hardware defects might only become visible when running Bitcoin Core. You might want to check your hardware for defects.

* memtest86 to check your RAM
* to check the CPU behaviour under load, use linpack or Prime95
* to test your storage device use smartctl or CrystalDiskInfo

Source: https://bitcoin.stackexchange.com/a/12206

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
