### ISSUE TITLE
autogen failure 

### ISSUE THREAD

**Issue by bitcreditscc** [bitcoin/bitcoin#7357]
configure.ac:219: error: possibly undefined macro: AC_CHECK_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:725: error: possibly undefined macro: PKG_CHECK_MODULES
configure.ac:753: error: possibly undefined macro: AC_CHECK_HEADER
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by luke-jr** [comment]
You're missing dependencies; it sounds like pkg-config/pkgconf and automake

**Comment by bitcreditscc** [comment]
I don't think so, unless there are new dependencies unannounced 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
automake is already the newest version.
automake set to manually installed.
autotools-dev is already the newest version.
bsdmainutils is already the newest version.
build-essential is already the newest version.
libtool is already the newest version.
pkg-config is already the newest version.

**Comment by bitcreditscc** [comment]
never mind , must have been some sort of corruption
clean git clone worked

**Comment by jonasschnelli** [comment]
Thanks for the report. Closing.
