### ISSUE TITLE
Unable to get some inputs for gitian building

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#7358]
I am attempting to build the signed binaries for 0.12.0rc1 on a new machine, and part of the release process instructions says to download this file: https://bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch. However I keep getting a 404 error and that file does not seem to exist anymore. Where can I get the patch?

**Comment by fanquake** [comment]
Try
https://dev.bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch
<https://bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch>,
that should work ok.

**Comment by achow101** [comment]
That works. submitted PR #7360 for fix
