### ISSUE TITLE
 	 EXCEPTION: St9bad_alloc std::bad_alloc bitcoin in ProcessMessages() 

### ISSUE THREAD

**Issue by btcid** [bitcoin/bitcoin#7361]
my wallet blockchain was crashed and I unable to start it back with -reindex

it already synced to block num 340870, and it will be crashed every 5-10 blocks:

``` ************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
bitcoin in ProcessMessages()       

2016-01-17 02:12:03 ProcessMessages(block, 749055 bytes) FAILED peer=6

```

config:

```server=1
daemon=1
rpcport=12345
rpcuser=xxx
rpcpassword=xxxx

maxconnections=8
paytxfee=0.0001

minrelaytxfee=0.0001
limitfreerelay=5
```

the server has 16gb of RAM and 10gb of swap.

the wallet has 100k of addresses

any help would be very appreciated.

thanks

**Comment by btcid** [comment]
i tried
``` export MALLOC_ARENA_MAX=1 ```
still crashing 1-2 minutes after bitcoind up

```    "version" : 110200,
    "protocolversion" : 70002,
    "walletversion" : 60000, ```

**Comment by pstratem** [comment]
sounds like you're running out of memory

**Comment by btcid** [comment]
memory is 16gb and 10gb of swap. i monitor when the crash happened, only 3gb of memory being used.

**Comment by btcid** [comment]
debug.log

```
2016-01-17 06:44:39 

************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
bitcoin in ProcessMessages()
```
memory stats:
```
time       total       used       free     shared    buffers     cached
2016-01-17 06:44:39          16174       7017       9157          0         33       3993
```

**Comment by laanwj** [comment]
std::bad_alloc is raised only for one reason: out of memory. Are you perhaps running a 32-bit version of bitcoind? Lots of GB of memory won't help if the application cannot address it.

**Comment by btcid** [comment]
sorry for not updating. yes it turned out it was a 32 bit box. no wonder it kept running out of memory.
