### ISSUE TITLE
Manual pruning via RPC pruneblock

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#7365]
An idea I don't have time for right now: disable automatic pruning of blocks, but otherwise leave the node in pruned mode. Add a new RPC method pruneblock or pruneblockchain that allows the user to explicitly prune.

The benefit of this approach is enabling pruning to be used with external software such as Armory which needs to parse blocks itself.

**Comment by jonasschnelli** [comment]
+1

**Comment by GIJensen** [comment]
+1

**Comment by laanwj** [comment]
Yes, I think supporting manual pruning policy makes sense.

**Comment by mrbandrews** [comment]
I'm working on this and should have a PR for it soon.

**Comment by achow101** [comment]
This can be closed now that #7871 has been merged.
