### ISSUE TITLE
maxuploadtarget Should be in the Network section of QT

### ISSUE THREAD

**Issue by Transisto** [bitcoin/bitcoin#7369]
Why is it not in the UI ?
This is a setting many people with capped internet would want to use.

**Comment by laanwj** [comment]
I don't think there is a 'why not' apart from that no one implemented this yet.

**Comment by jonasschnelli** [comment]
Agree. It should be accessible though the UI (as setting as well a way of inspecting the current stats)

**Comment by jonasschnelli** [comment]
It's addresses in https://github.com/bitcoin/bitcoin/pull/7510. Extracting the `-maxuploadtarget` changes from that PR would be good IMO.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
