### ISSUE TITLE
0.12: Avast doesn't like it

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#7375]
https://www.reddit.com/r/Bitcoin/comments/41czc2/wladimir_on_twitter_binaries_for_bitcoin_core/cz1uw86

**Comment by laanwj** [comment]
That's weird.
Can anyone verify that the windows signature is correct?

**Comment by jonasschnelli** [comment]
Just checked, 32/64 signatures are correct.

**Comment by PRabahy** [comment]
bitcoin-0.12.0rc1-win64-setup.exe looks clean except for McAfee-GW-Edition.

https://www.virustotal.com/en/file/b1a1082d638f712767bb0ae3ceca3e7b1d75e86d1ce08b63c0fb24a2d7e4482b/analysis/

**Comment by MarcoFalke** [comment]
@PRabahy You'd have to install it to reproduce the issue, I guess.

**Comment by paveljanik** [comment]
@MarcoFalke virustotal (see the link) does that for you.

The same applies to win32.

**Comment by MarcoFalke** [comment]
@paveljanik Do you have sources to support your claim? (Keep in mind installing is different from executing the installer)

**Comment by MarcoFalke** [comment]
Can't reproduce the reported bug "Avast had suspicion on the exe and made him run on a sandbox."

![screenshot from 2016-01-19 16-44-06](https://cloud.githubusercontent.com/assets/6399679/12423516/28e2d354-becc-11e5-818b-f4c19f92c383.png)

**Comment by craig131** [comment]
Could it be the Avast Firewall? Have you tried disabling only that?

**Comment by laanwj** [comment]
I don't think we had any further reports of this issue. May have been a local misconfiguration, or maybe AVAST keeps statistics on how many times a certain executable has been run with their scanner installed and balks if it's only seen it very few times.

Neither do I see any solution at our side to this. Something to consider in the future may be to code-sign the bitcoin-qt.exe executable as we do the installer, but this would be hard to integrate into the gitian process. And I'm not sure it would solve this.
