### ISSUE TITLE
makeseeds.py error line 134

### ISSUE THREAD

**Issue by Zwilla** [bitcoin/bitcoin#7393]
curl -s http://bitcoin.sipa.be/seeds.txt | ./makeseeds.py

File "./makeseeds.py", line 134
    result.extend(ips_onion)
    ^
IndentationError: unexpected indent
curl: (23) Failed writing body (1444 != 8688)

file: makeseeds.py 
132:   # Add back non-IPv4
133:   result.extend(ips_ipv6)
134:   result.extend(ips_onion)
135:   return result

Any idea?

**Comment by laanwj** [comment]
Can't reproduce this on master:
```
$ curl -s http://bitcoin.sipa.be/seeds.txt > a.txt
$ ./makeseeds.py < a.txt > b.txt
$ wc b.txt
  941   941 23723 b.txt
```
Perhaps a python2/3 conflict?
Can you try explicitly using python 2 eg
```
$ curl -s http://bitcoin.sipa.be/seeds.txt | python2 ./makeseeds.py
```

**Comment by jonasschnelli** [comment]
Works here:
```bash
$ curl -s http://bitcoin.sipa.be/seeds.txt | ./seeds/makeseeds.py 
5.2.145.201:8333
5.22.142.214:8333
---------snip---------
```

You error on line 134 could indicate that you are parsing a 404/403 or similar page. Maybe you have a proxy in between. Do you get the seeders db file with just calling `curl -s http://bitcoin.sipa.be/seeds.txt`?

**Comment by Zwilla** [comment]
with 
curl -s http://bitcoin.sipa.be/seeds.txt > a.txt
I get the a.txt
with vi I can see that the content is valid, but with
./makeseeds.py < a.txt > b.txt
I got the same error
also with
python2 makeseeds.py < a.txt > b.txt

Error:
  File "makeseeds.py", line 134
    result.extend(ips_onion)
    ^
IndentationError: unexpected indent

**Comment by laanwj** [comment]
What version of python?

**Comment by jonasschnelli** [comment]
@Zwilla: are you sure you have a unchanged version of https://github.com/bitcoin/bitcoin/blob/master/contrib/seeds/makeseeds.py?

It look like you are missing (or should remove) a \t at line 134.

**Comment by Zwilla** [comment]
I checked my makeseeds.py:

# Add back non-IPv4
result.extend(ips_ipv6)
    result.extend(ips_onion)
    return result

This is c+p from source, the different is only the empty space (makeseeds.py)
    # Add back non-IPv4
    result.extend(ips_ipv6)
    result.extend(ips_onion)
    return result

Now it is working!

only the empty spaces in front of the line 132 and 133 fixed the problem.

I don not know what I will do now. Cackling or jumping from a skyscraper.
Ok I do no1 at first and then no2

thx a lot guys, but I cant believe that empty spaces will fix the problem.

thx an have an nice weekend
