### ISSUE TITLE
Qt/OS X: Ctrl-L mentioned to clear screen and doesn't work

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#7397]
On OS X:

<img width="726" alt="screen shot 2016-01-22 at 20 40 47" src="https://cloud.githubusercontent.com/assets/6848764/12521074/aa076bb0-c148-11e5-98ed-e7cb2ac695fd.png">

Ctrl-L mentioned and doesn't work anyway (Cmd should be used and should work).

The X in the circle button works OK though.

**Comment by jonasschnelli** [comment]
Works here.
Did you tested it over a build that included #7396? There I accidentally disabled the behavior (now fixed).

**Comment by paveljanik** [comment]
Ah, yes ;-) Will close this after retest ;-)

**Comment by achow101** [comment]
Just tested that PR on Ubuntu 15.10 and I see the same behavior. Ctrl+L doesn't clear the console.

**Comment by paveljanik** [comment]
Cmd+L works in current master build. Doesn't work in #7396, yes.

**Comment by paveljanik** [comment]
Master is OK.
Ctrl vs Cmd is probably not work the effort.

**Comment by jonasschnelli** [comment]
Works also on Ubuntu 15.04.
