### ISSUE TITLE
Core needs to distance itself from attacks made "in its support"

### ISSUE THREAD

**Issue by dskloet** [bitcoin/bitcoin#7406]
People are doing vile things, supposedly in support of Bitcoin Core. These attacks reflect very badly on Core. Some examples:

Censoring large forums to hide the existing of other teams/clients.
DDoS'ing Bitcoin XT nodes and pools.
DDoS'ing Coinbase.
Removing Coinbase from bitcoin.org

Since these things reflect very badly on the Core team, it would be good to have a public announcement, distancing the team from such attacks and discouraging those attacks since they are not helping anyone.

**Comment by jonasschnelli** [comment]
Check this: https://github.com/bitcoin-core/website/pull/58/files

**Comment by benjyz** [comment]
see also:

https://www.reddit.com/r/btc/comments/42j4px/til_that_blockstream_coretechengineer_patrick/

**Comment by laanwj** [comment]
Don't open non-code-related issues here

**Comment by dskloet** [comment]
Where should non code related issues be filed?

**Comment by MarcoFalke** [comment]
>  Where should non code related issues be filed?


It really depends on the issue but yours best matches https://github.com/bitcoin-core/website

**Comment by dskloet** [comment]
Thanks! Done https://github.com/bitcoin-core/website/issues/75
