### ISSUE TITLE
segnet: bitcoin-qt does not show correct amounts in transaction history

### ISSUE THREAD

**Issue by nomnombtc** [bitcoin/bitcoin#7407]
Hello,

not sure this is the right place to report it, but in github.com/sipa/bitcoin there is no "issues" section.

If I send something on segnet, it only seems to show the transaction fee in the gui.
See screenshot: https://i.imgur.com/t00uMKD.png
https://segnet.metaco.com/transactions/0b1f74319681a13f46d696329e838cc8ac0295aeb77df6afb0a081420ebaf65c

**Comment by laanwj** [comment]
Not sure either what is the right place for this
@sipa?

**Comment by bityogi** [comment]
For mere mortals like me who are trying to keep up with all the development happening in bitcoin, my suggestion would be to keep it all here. 

Segregated Witness is an important part of the road-map that core has adopted and everyone following this development can be kept in the loop more easily right here.

**Comment by MarcoFalke** [comment]
Imo it is reasonable to collect issues for segwit code considering that it is planned to merge soon™.

In any case, I don't think @sipa will address GUI-only related issues, so another reason to have them here.

@nomnombtc Could you also post `getrawtransaction $` or `decoderawtransaction $`?

**Comment by nomnombtc** [comment]
Sure no problem, here is getrawtransaction:
    
    0100000009098c859b07bac3327107bfab471a5ff7700d53106786d0e21c2b7f05223e7967000000006b483045022100c613442cc7318f16141eef12d2b2c99e4db6796845b68b9a1873f03fc376131202201baad8bb3f8d0e441aa92dcfadb1376604610b8ee315b144b9fcf413dc2f0e36012103d0a23b56b5c24b1cdcddd703f7f21837b51226e65078438928be14be0bb9f9b5feffffff31a0d7a9ca0278715be4a4ff5ce83c45a3939d67a70578871d5b2d963d0ab3e4010000006b483045022100e1c99baa1cee2bc2da9cfefa4373c72fbb2db7d347dfcdb62419518a9d51dbb2022017dc750b354917192adf1b15618ff431ead59dcabc9a359962ce3e6eabc04b97012103caf156567165b7e2ee77d518242ff32517bf3e6ed57e7a77c73e2b8fdca125e4feffffff50552d7aabbdc168e017403a0bbbb57d67b0570bae991282d2995810329d7036010000006a473044022044b909b004bf157774448e3fed009acebc6e324d70b93114481cb5793f62f5c40220314d6ba2111c9d3b34d7f4d92f305df47041d909fd2b514bb33b0f8a638c854f01210209fc67cd9c1373052309cfe404fd1177365db3b6f79cca4ee24fa1972f068354feffffff71f19442c7b2f873491156bf1af0efff4973602bbde16e71155b4b4971331d7b000000006b483045022100932ab56c95b4311443e51cce23d588305727c763def77334d657c61e1cce711a02201d74d66390099d36c094d5ac7b05e9ab467b42179c2bea7d05ab49980121673501210209fc67cd9c1373052309cfe404fd1177365db3b6f79cca4ee24fa1972f068354feffffff71f19442c7b2f873491156bf1af0efff4973602bbde16e71155b4b4971331d7b010000006b483045022100eb7374e42355d23cdca1602573e2f0e631a25cf7696c13fd16eb1056bcddaacc02203d5a9b96105d7b0fd62a93bdc8308147f05288548afaea1e0ef5a1963880b92601210355da01b7348745845f13a9cbfdde47037964230a24b617b9c9461c573ede6f3dfeffffff7d0f0b069501b30be1ce325ceac3d755cfa1e1b4b8e3f5b92e07f43b1f577719010000006a47304402204eb3040835f99c09cd11b7c93a7eb2bd17fa3cffdf7bc63f8a1fbed84584062f02204cb02f7f88b33667ebae7871865012683cc36acb0824523e74230fa9d9ba81fb012103b6cbedf997089faf739245a964c586c1e15661fc768f69f375b5b3e8a7274050feffffff877695bddfbb8d8e47b412e86c2dc2ae806aa86554ddff1c4df918a7991ae8f6010000006a47304402200e1105f8086ef7f19ae4c58a21f62917133a15ca653c4c49cd85e88d4b889ed8022049907ff7a4e78190b0896fd5c4fae25d83936293be3fe7af9e21da0cf819bccb012102aa019ce6dbc9f983b08f2b468c98b00080f109f61e9ede6a4dcd8d6b64547f49feffffffa5049bfd3498aa5384e60092512e7e0c6fb99cf0cf9e4c0e21424d0a5d409a24000000006b483045022100dbd2fa14e322d432bb079a55d466786bc2a52409c65f00696876cab345a4ce9d02202bbd4dbf425fde1efbfe52ed35258cdf7516fdb4686dfb5ee0b474f5d4085633012102e55039be67a91c17fe6bacb1bb8fd4c5a5b2c51c5a52fc999f680d42d5d4a878feffffffff2703d089188c29ef1b1055757ba580808a0afe73434a4ae9cac4a7c9b42a9e000000006a47304402207828b7dd913bce54760c49f79e7e7ebcd5827946e21fba22e28750d0921ea7a10220059e3e9681cd3759b12dc9018f6a66c57676dea6dfd6d0a44f7947d34e8ac543012102aa180c38086a69d672868345c5536fc5f871c343b6330db7c7741a42f2a368a8feffffff0200e1f505000000001976a914374175c8eb3053133cfb851786f139a39dbd75f188aca4600f00000000001976a91423d47b4af39d89a09f3f19bdff98010b8352dec488aca20a0000

I think it is just a display issue, if I do `bitcoin-cli -segnet listtransactions` it seems fine.

**Comment by jonasschnelli** [comment]
@nomnombtc: Mind doing a retest of this "bug" with the newest segwit PR?

**Comment by nomnombtc** [comment]
@jonasschnelli Hello. I tried it again with a built from: https://github.com/sipa/bitcoin/commits/segwit

I noticed this behaviour only happens if I send to an address from the same wallet.dat (Payment to yourself), in this case it only shows the transaction fee - maybe this is even expected behaviour? If that is the case, the "bug" can be closed and I am sorry for causing confusion :(

Receiving/Sending from/to external addresses seems to work just fine :+1: 

```
Send to address from same wallet.dat:
Status: 6 confirmations
Date: 22 Jun 2016 08:33
Total debit: -0.80085000 BTC
Total credit: 0.80085000 BTC
Transaction fee: -0.00004520 BTC
Net amount: -0.00004520 BTC
Transaction ID: 1825f0ef7def1f74d2dd136039ad1695cab458fe60ac13959d98894304e1368a-000

Send to external address:
Status: 4/unconfirmed, broadcast through 1 node(s)
Date: 22 Jun 2016 08:52
To: externaladdress D9drvKYD9S2QtbAsdL43VY8CeqLWheY7Rq
Debit: -0.80085000 BTC
Transaction fee: -0.00007460 BTC
Net amount: -0.80092460 BTC
Transaction ID: 0704c365980642d9addeaa034b91d2af331b2abd37a2fc3a4481ad78fde61557-000

```

**Comment by sipa** [comment]
That's the correct behaviour. The 'transaction' ledger entries in the GUI
show the net effect of each transaction on your wallet, not the total
amount moved.

**Comment by nomnombtc** [comment]
Ok thank you for explaining, I've used bitcoin-qt a lot in the past but didn't know it does this :)
Really thought I had found some bug there hmm ... closing here then, sorry for confusion.
