### ISSUE TITLE
 Bitcoin crisis : How to update with strong sedimentation customers?

### ISSUE THREAD

**Issue by Speed2016X2** [bitcoin/bitcoin#7414]
http://btcnodes.org/agent

**Comment by MarcoFalke** [comment]
Could someone please block @Speed2016X2 after they dumped several russian text blobs unrelated to Bitcoin Core development?

**Comment by Speed2016X2** [comment]
Вопрос можете удалить если считаете нужным, тут писать не буду , MarcoFalke  похож на расиста (не нравится русский , не пожет браузером перевести) , у биткоина вижу оптимизируют , но не состоянии договорится и масштабировать сеть, и даже если захотят сильно много клиентов разных версий , мож что получится когда настанет критический момент. хз.

**Comment by MarcoFalke** [comment]
@Speed2016X2 The Bitcoin Core GitHub issue tracker is the wrong place for discussing bitcoin improvements/meta analysis. You are welcome to write a BIP, post to the developer mailing list or one of the numerous bitcoin forums/reddit.
