### ISSUE TITLE
Can't ctrl + tab off of peers tab

### ISSUE THREAD

**Issue by PRabahy** [bitcoin/bitcoin#7418]
I can navigate between the tabs (in disablewallet=1 mode) with just ctrl + tab and ctrl + shift + tab, but once I go to the peers tab, I get stuck there until I use the mouse or a more complex key combination.

I only noticed this in 0.12.0rc2, so I don't know if this was existing or a regression.

**Comment by achow101** [comment]
Make sure that you don't have a peer selected when you hit ctrl+tab or ctrl+shift+tab as that will only move the cursor among the peer entries

**Comment by PRabahy** [comment]
I don't even know how I would describe the current ctrl + tab behavior when I have a peer entry selected. It appears that if I push and hold it it moves down the list, but if I just press it once, sometimes it moves it and sometimes it doesn't. Whatever its trying to do is very unintuitive and I would rather just use up/down arrow to move around the grid (works properly).


I'm not sure if this matters, but I'm on Win7 64bit.

**Comment by achow101** [comment]
I see that same weird movement too on Ubuntu 12.10. I
