### ISSUE TITLE
bitcoin-cli not working on Ubuntu 12.04 due to glibc 2.17 dependency

### ISSUE THREAD

**Issue by dlogemann** [bitcoin/bitcoin#7420]
I tested the 0.12.0rc2 release on my server running Ubuntu 12.04.5 LTS and got the following error:
```
bitcoin@server:~$ ~bitcoin/bitcoin-0.12.0/bin/bitcoin-cli
/home/bitcoin/bitcoin-0.12.0/bin/bitcoin-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/bitcoin/bitcoin-0.12.0/bin/bitcoin-cli)
```

Ubuntu 12.04 is currently shipped with this glibc version:
```
bitcoin@server:~$ ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.12) 2.15
```

Unfortunately I am not very familiar with linker dependencies to resolve this myself, but this might help:
```
bitcoin@server:~$ objdump -T ~bitcoin/bitcoin-0.12.0/bin/bitcoin-cli |grep GLIBC_2.17
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.17  clock_gettime
```

Ubuntu 12.04 is still actively maintained and I cannot switch to a current Ubuntu release in the near future so I hope this issue can be resolved. 

bitcoind seems to be OK, could be started and is running.

**Comment by theuni** [comment]
Grr, these checks never got added to the buildsystem. That's my fault, doing that now.
