### ISSUE TITLE
Sudden database corruption in v.0.11.2

### ISSUE THREAD

**Issue by simplex409** [bitcoin/bitcoin#7426]
2016-01-27 13:16:53 UpdateTip: new best=0000000000000021c0fe0496cd1943e7bf25f8c12a212cbc497d88ef006d9e06  height=257552  log2_work=71.857863  tx=23690925  date=2013-09-12 15:27:46 progress=0.101313  cache=64.3MiB(57504tx)
2016-01-27 13:16:54 Corruption: block checksum mismatch
2016-01-27 13:16:54 **\* System error while flushing: Database corrupted

**Comment by jonasschnelli** [comment]
Please give us some details.. :)

OS?
Virtualized?
storage: spinning / SSD / sdcard?

**Comment by simplex409** [comment]
Windows 10 pro
not virtual
spinning drive

**Comment by simplex409** [comment]
------------------
System Information
------------------
      Time of this report: 1/27/2016, 13:33:18
             Machine name: WIBBLE
         Operating System: Windows 10 Pro 64-bit (10.0, Build 10240) (10240.th1.160104-1507)
                 Language: English (Regional Setting: English)
      System Manufacturer: System manufacturer
             System Model: System Product Name
                     BIOS: BIOS Date: 03/08/11 11:43:42 Ver: 08.00.15
                Processor: AMD Phenom(tm) II X4 955 Processor (4 CPUs), ~3.2GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16382MB RAM
                Page File: 3876MB used, 28890MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: 11.2
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Not Available
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.10240.16384 64bit Unicode

**Comment by pstratem** [comment]
is it overclocked?

**Comment by simplex409** [comment]
Nope, just running normally

**Comment by unsystemizer** [comment]
You could have a corrupt filesystem or malfunctioning disk.
