### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [bitcoin/bitcoin#7432]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [PaymentRequestPlus::getMerchant](https://github.com/bitcoin/bitcoin/blob/fa24439ff3d8ab5b9efaf66ef4dae6713b88cb35/src/qt/paymentrequestplus.cpp#L187 "PaymentRequestPlus::getMerchant function")
* [Table::Open](https://github.com/bitcoin/bitcoin/blob/5b9f8425a515739e2149bf5bfb2ae6ed60bfbaf2/src/leveldb/table/table.cc#L85 "Table::Open function")

I reported this issue for [another evolving software](https://github.com/Electric-Coin-Company/zcash/issues/676 "Update candidate") before.

**Comment by jonasschnelli** [comment]
At least a `if NULL` check does not hurt.
But I agree. Feel free do open a PR.

**Comment by elfring** [comment]
Would you also like to [update another software library](https://github.com/google/leveldb/issues/338 "Update candidate")?

**Comment by laanwj** [comment]
In Bitcoin Core we believe in belt-and-suspenders checks. A small change to the code can turn a 'unnecessary' NULL pointer check into the only thing that prevents a horrible security issue. Checking, even though not strictly necessary, may add some robustness to the API.

Also it may be hard to prove that a check is unnecessary, evaluating the code paths is a lot of review work while there are tons of more serious issues.

So let's just leave this as it is. If you can quantify that it saves time in a critical path, feel free to remove an unnecessary check, but don't do so indiscriminately.

**Comment by elfring** [comment]
>Checking, even though not strictly necessary, may add some robustness to the API.

Do you imagine any special case for the eventual handling of C++ compilers with a standard-incompliant implementation of [the delete operator](http://stackoverflow.com/questions/4190703/is-it-safe-to-delete-a-null-pointer "Is it safe to delete a NULL pointer?")?

**Comment by laanwj** [comment]
Sure, if you encounter the code
```
if (x)
    delete x;
```
Then, according to the C++ standard, you can replace it with
```
    delete x;
```
But don't do so if there is more code in the `if ()`.

**Comment by elfring** [comment]
Why did you close this issue already?

**Comment by laanwj** [comment]
I don't see this as a serious issue.
A few extra checks won't cause bugs, nor (likely) affect performance.

**Comment by elfring** [comment]
I suggested just another small software optimisation here.

**Comment by jonasschnelli** [comment]
Please no bikeshedding on small pointer check. No need to create an issue for that (create a PR instead if you want to improve things).

**Comment by MarcoFalke** [comment]
Isn't the compiler taking care of such?
