### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [bitcoin/bitcoin#7433]
The variables "[fReopenDebugLog](https://github.com/bitcoin/bitcoin/blob/fa24439ff3d8ab5b9efaf66ef4dae6713b88cb35/src/util.h#L53)" and "[fRequestShutdown](https://github.com/bitcoin/bitcoin/blob/fae78fa81802b5387054715c339f286ef436408e/src/init.cpp#L128)" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.") (instead of "bool").

I reported this issue for [another evolving software](https://github.com/Electric-Coin-Company/zcash/issues/678 "Update candidate") before.

**Comment by jonasschnelli** [comment]
Related to https://github.com/Electric-Coin-Company/zcash/issues/678

**Comment by laanwj** [comment]
ACK.
Why not make the code change instead of raising an issue?

**Comment by elfring** [comment]
There might be more implementation details to reconsider than a change for the data type of two variables.
Do you see the need for any more source code fine-tuning for such an use case?

**Comment by laanwj** [comment]
I don't think so. Also, any such (code review) issues can be discussed on a PR that makes this change just as well :)

**Comment by catilac** [comment]
Is anyone working on this? I'm looking for a first task :)

**Comment by MarcoFalke** [comment]
@catilac There is no open pull for this, so I don't think so. Go ahead :+1:
