### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [bitcoin/bitcoin#7434]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [CreatePidFile](https://github.com/bitcoin/bitcoin/blob/605c17844ea32b6d237db6d83871164dc7d59dab/src/util.cpp#L565)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html) ⇒ [AppInit2](https://github.com/bitcoin/bitcoin/blob/473ad1bb026986db2569fff278d8957363f758f8/src/init.cpp#L832)

How do you think improve this issue together with [another evolving software](https://github.com/Electric-Coin-Company/zcash/issues/677)?

**Comment by laanwj** [comment]
Sure, makes sense.

**Comment by laanwj** [comment]
Related issue: #6702
