### ISSUE TITLE
Input-from-stdin mode for bitcoin-cli

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7442]
Some information passed to bitcoin-cli may be too sensitive to pass on the command line, as that can (usually) be seen by other users on the system in the `ps` output.

The most straightforward solution for an alternative is to add an option to `bitcoin-cli` that takes the input (or part of the input, e.g. the passphrase argument to `walletpassphrase`) from stdin instead of the command line. In contrast to a fully-fledged interactive shell (which would also be nice to have, see #3122), this can also be useful in scripts.

See https://github.com/bitcoin/bitcoin/pull/7122#issuecomment-162578480 for discussion.

**Comment by dcousens** [comment]
concept ACK :+1:

**Comment by jgarzik** [comment]
concept ACK

**Comment by luke-jr** [comment]
concept ACK

**Comment by paveljanik** [comment]
Would be great, concept ACK

**Comment by jonasschnelli** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
@laanwj Looks like this is fixed. Anything left to do here other than #3122?

**Comment by laanwj** [comment]
No, this is done, thanks for the reminder
