### ISSUE TITLE
Include src/secp256k1 and src/univalue as submodules

### ISSUE THREAD

**Issue by prusnak** [bitcoin/bitcoin#7446]
It seems that src/secp256k1 and src/univalue are in-tree copies of respective libraries that live as a separate repositories. It would be wise to include them as a submodules to reduce maintenance work and to avoid possible change in bitcoin tree while not updating the library tree.

**Comment by pstratem** [comment]
@prusnak git subtree

**Comment by MarcoFalke** [comment]
Right now they are subtrees so you can do a simple and single `git clone ...` or download the comple source code zip for any commit off of GitHub. The downside is that anyone must not edit them.

**Comment by jonasschnelli** [comment]
It's a subtree and subtree seems to be the preferred way here:
https://github.com/bitcoin/bitcoin/pull/2616#issuecomment-18556431
https://github.com/bitcoin/bitcoin/pull/6047#issuecomment-95851709

**Comment by prusnak** [comment]
Ok, then. Closing.
