### ISSUE TITLE
build options for OpenBSD incomplete/out-of-date

### ISSUE THREAD

**Issue by truism69** [bitcoin/bitcoin#7447]
Trying the instructions in build-openbsd.md on OpenBSD 5.7 fails with

    In file included from addrman.h:14:0,
                     from init.cpp:12:
    init.cpp: In function 'bool AppInit2(boost::thread_group&, CScheduler&)':
    init.cpp:1076:61: error: 'OPENSSL_VERSION' was not declared in this scope
         LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));

Apparently, this is due to OpenSSL no longer being present on recent versions of OpenBSD. To fix this, I had to `pkg_add openssl` (which installs the `eopenssl` package, which is a kind of wrapper for libressl afaik) and replace the configure command given in the instructions by

`./configure --with-gui=no --with-boost=$BOOST_PREFIX CC=egcc CXX=eg++ CPP=ecpp LDFLAGS="-L${BDB_PREFIX}/lib/ -L/usr/local/lib/eopenssl/" CPPFLAGS="-I${BDB_PREFIX}/include/ -I/usr/local/include/eopenssl/"`

Perhaps the documentation could be updated to reflect that.

**Comment by paveljanik** [comment]
Can you please check the fix suggested in #7520, ie. do not install eopenssl, do not add ...eopenssl... paths and use the change added there?
