### ISSUE TITLE
bitcoin-qt transaction view no sorting by transaction status.

### ISSUE THREAD

**Issue by raedah** [bitcoin/bitcoin#7448]
This is related to an closed issue about a previous version. #7198

Running 0.12rc2, and noticed that conflicted transaction are now not appearing at the top. They are appearing in Date order. But this appears to be erroneous as, as its still the first column (transaction status) that is the selected sort order. Potentially more problematic, is that even clicking the first column will not sort the conflicted transactions to the top of the list, so manually going through the list is the only way to locate them. This became apparent only after doing a -rescan.

After reverting back to 0.11.2, with the automatic rescan completing, the behavior now remains the same in 0.11.2 as it was in 0.12rc2. But this behavior didnt occur until after having tested 0.12rc2. I did many rescans when on 0.11.2 and the behavior was never like this before. The conflicted transaction was sitting at the top of my transaction list for the last two months, and now it is no longer at the top.

**Comment by Tyler-Hardin** [comment]
This is intentional. https://github.com/bitcoin/bitcoin/pull/8014

**Comment by MarcoFalke** [comment]
You can get them like this

![Screenshot from 2020-04-25 20-35-30](https://user-images.githubusercontent.com/6399679/80294146-59088080-8734-11ea-880e-3a0d1daac4bc.png)
