### ISSUE TITLE
Feature request: Separate MAX_OUTBOUND_CONNECTIONS for each IPv4 and IPv6

### ISSUE THREAD

**Issue by anto** [bitcoin/bitcoin#7449]
The current implementation limits the maximum outbound connection to only 8 connections, i.e. MAX_OUTBOUND_CONNECTIONS = 8, regardless how many IP addresses that a node has.  A part from obsolete implementation, i.e. based on only IPv4 network, I think the intention is possibly also to avoid bad nodes with multiple IP addresses flooding the network. But regardless to that, at least the limitation should be changed per IP address types, so that each IPv4 and IPv6 addresses individually get maximum 8 outbound connections as they are clearly on separate networks.

**Comment by subSTRATA** [comment]
Or at least make it possible to externaly (bitcoin.conf) specify maximum number of outgoing connections. Gavin said that nodes which does not accept incoming connections are not solution but a problem but I disagree with that, on countless occassions my node connected to some other nodes and those other nodes started syncing with my node. So a node that can accept incoming connections synced from my node which can't accept incoming connections. If I could specify maxoutgoingconnections=16 or 64 that means my node would have a higher chance to sync other nodes.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
