### ISSUE TITLE
Turning off the blockchain downloading

### ISSUE THREAD

**Issue by RegZi** [bitcoin/bitcoin#7450]
Shouldn't there be a prompt at the first starting and a button in the GUI, that allows turning off or on the blockchain downloading. It's not a big problem, but it would be useful.

**Comment by laanwj** [comment]
This feature request seems to be fully covered by another one, #6461 "Exposing prune option in GUI"

Unless you mean literally interrupting the download, in which case this is covered by #1958 "Pause/Resume network activity"
