### ISSUE TITLE
Clarification on versions vulnerable to upnp flaw

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#7454]
https://bitcoin.org/en/alert/2015-10-12-upnp-vulnerability mentions that users should upgrade to  0.10.3 or 0.11.1, but doesn't explain whether versions between these two versions are vulnerable or not. Do users running 0.11.0 need to upgrade or downgrade for example?

**Comment by laanwj** [comment]
Yes.
For 0.10.x, you should upgrade to 0.10.3
For 0.11.x, you should upgrade to 0.11.1
(but only if you use the binaries or statically build using the depends system)
