### ISSUE TITLE
Suggestion: Marking of commits that fix vulnerabilities

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#7456]
I've seen discussions where forks of the bitcoin code is missing important fixes to vulnerabilities, and I'm wondering if it can be made more obvious which commits are the important ones. Can this be addressed?

**Comment by MarcoFalke** [comment]
What about https://github.com/bitcoin/bitcoin/pulls?q=is%3Apr+label%3A%22Priority+High%22+is%3Aclosed

**Comment by laanwj** [comment]
Not against this, but I don't think this can be practically enforced.
Though we could try adding a "security" category and adding it to security-related issues.

**Comment by luke-jr** [comment]
The ideal way IMO would be to flag the commits on the applicable CVE wiki page. This allows post-hoc addition of the information.

**Comment by laanwj** [comment]
For critical issues @luke-jr's suggestion is certainly the way to go. This is similar to what other projects do.

**Comment by MarcoFalke** [comment]
Fixed here: https://en.bitcoin.it/wiki/Common_Vulnerabilities_and_Exposures
