### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by twepl** [bitcoin/bitcoin#7457]
https://blockchain.info/ru/block/00000000000000000233ba0eca74198e0152b91c75d082d6240497b2bacd0aa9
https://blockchain.info/ru/block/000000000000000001879f26997dbc9e69c6edffc144ea5d2eda3d802f200919

Someone creates an empty block. In general, no transactions

**Comment by sipa** [comment]
This is not a Bitcoin Core issue, but a question. It's more appropriate for places like the Bitcoin stackexchange website: http://bitcoin.stackexchange.com/ . You'll find several related questions and answers there.
