### ISSUE TITLE
feature request: bitcoin-qt gui - transactions list - right click menu - copy full details

### ISSUE THREAD

**Issue by bdimych** [bitcoin/bitcoin#7484]
all together
date + status + address + label + amount
convenient if I want to save transaction details somewhere

**Comment by jonasschnelli** [comment]
Agree. This would be useful.

**Comment by ericshawlinux** [comment]
Currently working on this. Before I finish and before I try to submit it, I was wondering if you guys thought writing a template for the copyEntryData() method would be a good idea? I was going to write it so you could optionally send a list of roles to copy and concatenate the strings before setting the clipboard.

**Comment by jonasschnelli** [comment]
I think I would create another role (`TxPlainTextRole`) and add a return a nice formatted string in `TransactionTableModel::data()`.

**Comment by ericshawlinux** [comment]
ok, I made the new role like you said. Much simpler that way. Before I make the pull request, I Just need to sync the testnet chain and try it out.
Also please don't mind the first commit that is linked in this thread, I made mistakes in trying to upload.

**Comment by paveljanik** [comment]
Is this fixed by #7628? If so, please close this issue.
