### ISSUE TITLE
False positives in `-alertnotify`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7488]
Services are using `-alertnotify` to be notified of critical problems. Some have pagers connected, or even shut off the service automatically.

Some of the messages based on heuristics, such as the "abnormally high number of blocks" one seem to appear a lot despite there being no real issue:
https://www.reddit.com/r/Bitcoin/comments/3ydwg2/warning_abnormally_high_number_of_blocks/

As well as wasting time and resources, after the zillionth time users start ignoring the messages completely, and thus miss a serious problem.

Another issue is that some of the warnings don't go away when the (temporary) problem goes away, the only way to turn them off is to restart bitcoind.

**Comment by petertodd** [comment]
Agreed - if this isn't fixed soon we should just remove it to avoid the false-positive effect.

Also, I'm kinda unconvinced about the rational for the "blocks too fast" alert - the definition of Bitcoin is that you're on the most-work valid chain after all. Hard to think of cases where you'd actually see that in an attack, at least after you've synced up the first time.

**Comment by dcousens** [comment]
@petertodd maybe those who are concerned about breaking SHA256?  You're right though,  it does seem a bit unnecessary.

**Comment by sipa** [comment]
I assume the reasoning was: if hashrate slowly moves to a different chain,
your difficulty drops, and then that hashrate returns suddenly, it's a sign
of an economic situation that isn't very secure.

**Comment by laanwj** [comment]
Related: Falsely triggered "check your network connection" error while catching up. #6251

**Comment by laanwj** [comment]
The most urgent part of this was solved with #8275, removing the milestone
