### ISSUE TITLE
gitian linking problem for Windows cross-compile

### ISSUE THREAD

**Issue by midnightmagic** [bitcoin/bitcoin#7492]
Attempting to build the Windows gitian build for any of the following tags fails on my system:

v0.12.0rc{1,2}

**VM Host Details:**
Linux sentinel 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ii  python-vm-builder                      0.12.4+bzr489-0ubuntu2                     all          VM builder

DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

Tail from var/build.log prior to error:

  CXXLD    test/test_bitcoin.exe
  CXXLD    bench/bench_bitcoin.exe
/home/ubuntu/build/bitcoin/depends/x86_64-w64-mingw32/lib/libdb_cxx-4.8.a(cxx_env.o):cxx_env.cpp:(.data$_ZTISt9exception[_ZTISt9exception]+0x0): multiple definition of `typeinfo for std::exception'
bitcoind-bitcoind.o:bitcoind.cpp:(.rdata$_ZTISt9exception[_ZTISt9exception]+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [bitcoind.exe] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ubuntu/build/bitcoin/depends/x86_64-w64-mingw32/lib/libdb_cxx-4.8.a(cxx_env.o):cxx_env.cpp:(.data$_ZTISt9exception[_ZTISt9exception]+0x0): multiple definition of `typeinfo for std::exception'
test/test_test_bitcoin-arith_uint256_tests.o:arith_uint256_tests.cpp:(.rdata$_ZTISt9exception[_ZTISt9exception]+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_bitcoin.exe] Error 1
make[2]: Leaving directory `/home/ubuntu/build/bitcoin/distsrc-x86_64-w64-mingw32/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/build/bitcoin/distsrc-x86_64-w64-mingw32/src'
make: *** [all-recursive] Error 1

**Comment by laanwj** [comment]
Strange - no one else reported this. I wonder what is different about your setup.

**Comment by laanwj** [comment]
Can you try wiping the cache and building again? (preferably rc5)
There were issues with a toolchain change in Ubuntu at approximately the same time that this happened, see also https://github.com/bitcoin/gitian.sigs/pull/305

**Comment by midnightmagic** [comment]
Success in 6d307c73881220f49728ede094f4ee65f0600849
PR: https://github.com/bitcoin/gitian.sigs/pull/313
Cleared my cache and added that to my build script logic; I believe cfields said something about fixing the problem so it's no longer a problem in IRC.

In any event, all's well with rc5. Thanks!

**Comment by laanwj** [comment]
Awesome, closing this issue then
