### ISSUE TITLE
wrong zmq argument causes core dump or infinite loop

### ISSUE THREAD

**Issue by jafaber** [bitcoin/bitcoin#7496]
`bitcoin-0.12.0/bin/bitcoin-qt -testnet -server -zmqpubhashblock=127.0.0.1`

It's very unclear what the format of "address" should be, so I just tried a bunch. This is 0.12rc3.

The above causes an infinite loop at startup. "Verifying wallet" and when quitting the scary window "Do not shut down the computer until this window disappears." Luckily nothing is corrupted by just killing it and trying again.

Missing .// in the address causes assertion + core dump. At least less scary/confusing than above.

```
bitcoin-0.12.0/bin/bitcoin-qt -testnet -server -debug=1 -zmqpubhashblock=tcp://127.0.0.1:28332 -zmqpuawtx=tcp://127.0.0.1:28332 -zmqpubhashtx=tcp://127.0.0.1:28332 -zmqpubrawblock=tcp:127.0.0.1:28332
bitcoin-qt: zmq/zmqpublishnotifier.cpp:92: virtual void CZMQAbstractPublishNotifier::Shutdown(): Assertion `psocket' failed.
Aborted (core dumped)
```

**Comment by dcousens** [comment]
> -zmqpuawtx

**Comment by jafaber** [comment]
Hmm.. Or that. Not sure which is the cause. Not able to test today unfortunately.

**Comment by unsystemizer** [comment]
> It's very unclear what the format of "address" should be, so I just tried a bunch.

https://github.com/bitcoin/bitcoin/blob/fc41278e96890473c14916e2f7e0aa61e99c9849/doc/zmq.md

**Comment by mrbandrews** [comment]
In PublishNotifier, if it fails to bind the address, it leaves the socket open which causes zmq_destroy() to hang later on.  I'll submit a fix.
