### ISSUE TITLE
missing menu bar and tray icon in v0.12-rc4 (gnome linux)

### ISSUE THREAD

**Issue by themighty1** [bitcoin/bitcoin#7497]
For comparison, when i run v0.11.1 both the menu and the tray icon are present.

**Comment by laanwj** [comment]
Are you perhaps comparing the binary executable from bitcoin.org to the PPA (or other distro-built) version?

**Comment by themighty1** [comment]
I compiled v012-rc4 but v011.1 was downloaded from bitcoin.org when it was released

**Comment by laanwj** [comment]
OK. Can you try compiling 0.11.1 from source as well and see if there is the same issue?

**Comment by themighty1** [comment]
I just built 0.11.1 and the menu was missing as well. So, must be a misconfiguration of sorts on my end.

**Comment by themighty1** [comment]
For reference, removing appmenu-qt5 solved it for me
https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

**Comment by laanwj** [comment]
Ah, another appmenu-qt issue. Thanks for letting us know how you solved it.
