### ISSUE TITLE
v012-rc4 qt has some weird extra characters in  txid

### ISSUE THREAD

**Issue by themighty1** [bitcoin/bitcoin#7499]
Transactions->Transaction details shows txid with e-000 at the end, hmm.

**Comment by sipa** [comment]
That's been the case since 0.5, I think. The 000 is the output index of the payment in the transaction.

**Comment by laanwj** [comment]
That's been always the case. A Qt "transaction record" is not really a transaction but an output. So the output index uniquely qualifies it.

**Comment by themighty1** [comment]
Just a note, when I right-click in the tx list and select "Copy transaction ID", it still copies with the e-000 suffix. This is super counter-intuitive when all i needed is copy-paste the txid in a blockexplorer.

**Comment by sipa** [comment]
The e is part of the txid. It's not exponential number notation; it's just [txid]-[index].

It would have been more intuitive to use [txid]:[index], I think.

**Comment by laanwj** [comment]
It definitely shouldn't be adding an 'e'.
