### ISSUE TITLE
SHA256 is no longer considered safe by the NSA

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#7505]
https://www.deepdotweb.com/2016/02/08/nsa-switches-to-quantum-resistant-cryptography/

According to the NSA, SHA256 is no longer considered safe. Will bitcoin be changing to a safer algorithm?

**Comment by laanwj** [comment]
This is not the place for this kind of implementation independent discussion. As with the PoW change proposals we can't change this unilaterally, even if we wanted. Use the mailing list.
