### ISSUE TITLE
Build issue with 0.12

### ISSUE THREAD

**Issue by mkabatek** [bitcoin/bitcoin#7508]
I'm attempting to build bitcoin 0.12 on Ubuntu 14.04 LTS using the same configuration found [here](http://bitzuma.com/posts/compile-bitcoin-core-from-source-on-ubuntu/). 0.11 builds correctly.

```
configure: error: Qt dependencies not found
make: *** [config.status] Error 1
```

**Comment by achow101** [comment]
You are missing the Qt dependency. 0.12 uses Qt 5 instead of Qt 4 which was in previous versions. Follow the up to date instructions at https://github.com/bitcoin/bitcoin/blob/0.12/doc/build-unix.md to get a proper build.

**Comment by luke-jr** [comment]
Qt4 should work fine as it always has... this looks like a bug somewhere.

@mkabatek Can you post config.log somewhere?

**Comment by mkabatek** [comment]
@luke-jr sorry I don't have the original config.log. I ended up installing the Qt 5 dependencies. 

Then it complained about `libevent-dev` so I installed that now it appears to be building. Maybe 0.12 does not automatically fall back on Qt 4? I was also lacking libevent which looks like a change from 0.11. Sorry I can't provide more details I've mucked around with the system since I got stuck.

**Comment by laanwj** [comment]
This indeed the case, and a known issue:  #7189

As a workaround you can specify to build with qt4 specifically (`--with-gui=qt4`).
