### ISSUE TITLE
wrong brackets

### ISSUE THREAD

**Issue by dragosbdi** [bitcoin/bitcoin#7519]
https://github.com/bitcoin/bitcoin/blob/master/build-aux/m4/bitcoin_qt.m4#L223

AC_MSG_CHECKING(whether to build ]AC_PACKAGE_NAME[ GUI)
AC_MSG_CHECKING(whether to build [AC_PACKAGE_NAME] GUI)

**Comment by laanwj** [comment]
What problem does this cause in practice?

**Comment by dragosbdi** [comment]
None, just a wrong message. Could also be ignored.

**Comment by paveljanik** [comment]
What is wrong with the message?
```
checking whether to build Bitcoin Core GUI... yes (Qt5)
```

But well, this is interesting ;-)

**Comment by laanwj** [comment]
Indeed, I've never noticed anything wrong with the message. And I don't know enough about autotools internals to know if this is worrying, or expected behavior.

**Comment by laanwj** [comment]
This is done on purpose, to have the variable substitution outside the quotes. See discussion in #7559.
