### ISSUE TITLE
Add txindex=1 option to QA tests

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#7538]
I'd find it useful for workload testing if `txindex=` was an option in QA tests.  
For example, related to indexing, there's the `reindex` test but it takes just 2-3 seconds to run. (I'm not even sure if it any actual indexing takes place, but even if it does, it's meaningless from a workload testing perspective). 
It would be nice to be able to enable indexing. I tried inserting `-txindex=1` in files such as qa/pull-tester/run-bitcoind-for-test.sh and qa/rpc-tests/test_framework/util.py, but I am still missing something because sooner or later I get this.
```
Running testscript listtransactions.py...
Initializing test directory /blockchain/tmp
: You need to rebuild the database using -reindex to change -txindex.

Do you want to rebuild the block database now?
```

**Comment by laanwj** [comment]
> For example, related to indexing, there's the reindex test but it takes just 2-3 seconds to run.

Tests running quickly is an advantage, not a problem.
If there is no test for `-txindex`, it makes sense to add one. On the other hand I see no point to enable it for all tests.

>  I am still missing something because sooner or later I get this.

Try wiping any 'cache' directories.

**Comment by unsystemizer** [comment]
> On the other hand I see no point to enable it for all tests.
> Tests running quickly is an advantage, not a problem

Yes, I agree, I meant for all tests where it makes sense. For example invalidateblock.py seems different from reindex.py (the former is "dynamic", a real life situation during a reorg, while the latter is "static" and not something that's often used) so it'd be nice to have the option in applicable tests.

I had wiped the cache dir and retried several times - it seems the initial config file can't have the option. I looked at the code again and it seems I can enable it across the board by changing only one line here: https://github.com/bitcoin/bitcoin/blob/0.11/qa/rpc-tests/test_framework/util.py#L94 (not great, but that's what works for me now).

**Comment by laanwj** [comment]
> I had wiped the cache (temp) dir and retried several times. I'll keep trying.

Not sure how you intend this but: 'cache' is not the tmp directory, it gets created in the current directory IIRC, the tmp directory is copied from it, to not have to generate a new chain for every test

**Comment by unsystemizer** [comment]
Well you referred to it as "cache", I wasn't sure whether that's the same so I followed that with the term I saw in order to make sure we're on the same page.
The tests by default use $TMP (`/tmp/temp*` in tests I ran) and a way to override that is `qa/pull-tester/rpc-tests.sh -extended --tmpdir=/blockchain/tmp`.
What I do between different runs of extended tests is `rm -rf /blockchain/tmp/*`, that clears everything in there. That appears to be the default unless one uses `--nocleanup` (https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/test_framework/test_framework.py#L101)

**Comment by MarcoFalke** [comment]
> I  tried inserting -txindex=1 in files such as qa/pull-tester/run-bitcoind-for-test.sh and qa/rpc-tests/test_framework/util.py

I'd prefer not to change defaults for *all* tests. What you could do, is to create a test similar to reindex.py

**Comment by unsystemizer** [comment]
That's fine, whatever is reasonable.

**Comment by laanwj** [comment]
Closing this. I think having a test for transaction index would be good, but there's no need to keep this issue open.
