### ISSUE TITLE
rc5 release note typo?

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#7546]
https://github.com/bitcoin/bitcoin/blob/0.12/doc/release-notes.md

> Bitcoin Core will never create transactions smaller than the current minimum relay fee

This seems like a meaningless comparison. How can a transaction be smaller than a fee? The only meaningful interpretation I can think of for the size of a transaction is its size in bytes, but then we can't compare that with a fee, which isn't in bytes.

**Comment by laanwj** [comment]
Wasn't fixed in time for 0.12.0, pretty much  too late now, so closing.
