### ISSUE TITLE
Bitcoin Core Roadmap - HF to 2mb reasonable ?

### ISSUE THREAD

**Issue by karek314** [bitcoin/bitcoin#7572]
I just saw bitcoin "roundtable" - funny by the way, good joke :)  announcement, as community wants higher block size by now, this problem should be first priority now. I have few concerns about it. I think it's the best place to talk about this, since most of threads started on /r/Bitcoin become censored very fast, not sure why not sure by who exactly. But let's move strictly to my questions if we all want Bitcoin to succeed and not be only source of income for Chinese miners with cheap technology and electricity. We all must agree that block size is mostly full by now, and in case any dynamical price change or/and new users boom - bitcoins will be very hard to transfer with reasonable fee, also bitcoin may lose chance to be adopted and used by new users.

1.Why force SW before changing blocksize to 2mb as temporary fix ? HF code to 2mb is already created, implemented and tested in Bitcoin Classic, it's very simple change, I think SegWit needs much more time to test and reveal potential bugs and risks.
2.If core team, really needs so much time to implement HF, why static solution - which will only change date when block size problem re-occur. We should implement dynamic solution for instance based on previous blocks (but there are some few other interesting bips also) And please don't say anything about disk space and centralization, disk space is cheap, and become cheaper and cheaper from year to year. Internet connection speed also shouldn't be a problem, just look back what we had few years ago. Satoshi couple times mentioned that bitcoin wouldn't grow faster than technology will, and nothing currently points that's not true.

And to make it clear, seg wit is great but it's not mainly scaleability benefits, it's much more complicated change than simply change blocksize (even it's HF) and more reasonably would be do HF with dynamic block size solution, and then very carefully without hurry test and release segwit.

**Comment by p3yot3** [comment]
> We all must agree that block size is mostly full by now....

Apart from the empty ones mined by some of the largest pools. I'd like to see empty mined blocks rejected by the network - this would ensure that ALL mined blocks carry tx's & help speed up transactions.

**Comment by luke-jr** [comment]
The right place for this kind of conversation is https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-discuss

**Comment by ak9250** [comment]
linuxfoundation website could really use a UI/UX developer

**Comment by jonasschnelli** [comment]
Closing because this is not the right place for a such discussion. Agree with @luke-jr, this should be moved to the mailing list or to IRC.
