### ISSUE TITLE
0.12.0 Precise PPA builds failing: error: Could not find a version of the boost_program_options library!

### ISSUE THREAD

**Issue by jonathancross** [bitcoin/bitcoin#7587]
I'm guessing @TheBlueMatt is already on this, but just in case...

Log:
https://launchpadlibrarian.net/242423468/buildlog_ubuntu-precise-i386.bitcoin_0.12.0-precise5_BUILDING.txt.gz

    checking whether the Boost::Program_Options library is available... yes
    configure: error: Could not find a version of the boost_program_options library!
    make[1]: *** [override_dh_auto_configure] Error 1
    make[1]: Leaving directory `/«PKGBUILDDIR»'
    make: *** [build] Error 2
    dpkg-buildpackage: error: debian/rules build gave error exit status 2

The [build instructions](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian) are a bit unclear to me, they seem to indicate that `libboost-program-options-dev` is only required for Ubuntu `14.04+`, but it seems to be breaking here in `12.04`.

**Comment by laanwj** [comment]
To build bitcoin core you need libboost-program-options development headers, period. The only difference between Ubuntu versions is whether that library is only available as part of an overall package `libboost-all-dev`, or *also* available partitioned into separate packages such as `libboost-program-options-dev`. So you need to install either, and depending on what is available you may prefer the finer-grained one.

**Comment by laanwj** [comment]
Also for the Qt build you need `--with-gui=qt4` if only qt4 is available, this is a regression (see #7189).

**Comment by laanwj** [comment]
Closing after #7590
