### ISSUE TITLE
BITCOIN CORE 0.12.0  CRASH  - help!

### ISSUE THREAD

**Issue by boondogger** [bitcoin/bitcoin#7593]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	bitcoin-qt.exe
  Application Version:	0.12.0.0
  Application Timestamp:	5685c180
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.18146
  Fault Module Timestamp:	5650b9bb
  Exception Code:	c0000005
  Exception Offset:	00000000000549e1
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	4105
  Additional Information 1:	8d87
  Additional Information 2:	8d87034a163c40feab242f45101699c1
  Additional Information 3:	4221
  Additional Information 4:	42219bc5a67200dab51ac3dfbb7dcaa7

**Comment by jonasschnelli** [comment]
Can you give us a little bit more information?
What CPU, Windows Version, etc. are you using?
Can you run bitcoin-qt 0.11.2 (https://bitcoin.org/bin/bitcoin-core-0.11.2/) without problems?
Anything in you debug.log?

**Comment by boondogger** [comment]
Win 8.1
Core i5
Last version worked fine.
Upgrade to 0.12.0 caused this problem in regestry...cant find ntdl.dll ......
Antivirus and malewarebyte show no issues...no issues with any other software....unistalled from control panel before installing new botcoincore version.

**Comment by unsystemizer** [comment]
The question was if you can uninstall 0.12 and install 0.11.2 *now*, to see if 0.11.2 is causing the same issue when nothing else changes.

**Comment by MarcoFalke** [comment]
You may also take a look at http://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/programs-close-faulting-module-ntdlldll/54aaaec5-2b53-4e9f-b9a7-b7889a1cd4b6 or http://pcsupport.about.com/od/fixtheproblem/a/ntdlldll.htm.

**Comment by dragongem45** [comment]
i know what error type it is it's trying to access memory that isn't premited to see.

a cause i know is negative array refrences

**Comment by d3spwn** [comment]
I had the same issue. Turned out to be an issue with my memory (or other hardware?). MemTest86 found many errors. I solved it by moving the memory module to another slot on the motherboard.
