### ISSUE TITLE
Should release-process.md still mention verify.sh?

### ISSUE THREAD

**Issue by JeremyRand** [bitcoin/bitcoin#7595]
As far as I can tell, verify.sh hasn't been updated for new Bitcoin releases in quite some time.  https://github.com/bitcoin/bitcoin/issues/2504 states that verify.sh isn't supposed to guess what version to download anyway; I'm not sure if that's the current situation.  However, release-process.md lists verify.sh under "Bitcoin maintainers/release engineers, update (commit) version in sources".  Is that still part of the release process?  If not, should release-process.md be amended to not mention verify.sh?

**Comment by MarcoFalke** [comment]
This is as trivial as bumping the two occurrences of `10.4` in https://github.com/bitcoin/bitcoin/commit/141c44ed6549acdc7f49fe039f017c020490ccf1 . If the script is still desired it would be better to create a python tool which automates such kind of trivial stuff, part of the release process.

**Comment by laanwj** [comment]
Can't we just add a VERSION parameter and tell the user to pass that in? 
Instead of relying it to be bumped in the source code with every release, which will be forgotten anyway.

**Comment by MarcoFalke** [comment]
It already does. You could use it like

```
$ contrib/verifysfbinaries/verify.sh bitcoin-core-0.10.4-rc1
$ contrib/verifysfbinaries/verify.sh bitcoin-core-0.11.2
$ contrib/verifysfbinaries/verify.sh bitcoin-core-0.12.0
```

Please note that it does not work for other `rc`s because their respective folder has been removed from https://bitcoin.org/bin/. (Interestingly, for 0.10.4 there are only rc binaries: https://bitcoin.org/bin/bitcoin-core-0.10.4/)

**Comment by laanwj** [comment]
OK, that's awesome, so we just remove the hardcoded value and update the documentation to call it in that way.

Yes, rcs are removed from the server after the final release. There is very limited room on the server.  0.10.4 never left rc, and you're actually the first person to notice this.
