### ISSUE TITLE
0.12 getbalance behavior

### ISSUE THREAD

**Issue by message** [bitcoin/bitcoin#7597]
Is this correct behavior? 

```
$ ~/bitcoin/src/bitcoin-cli getbalance
6.60409702

$ ~/bitcoin/src/bitcoin-cli getbalance "*" 0
-13.05526813

$ ~/bitcoin/src/bitcoin-cli getbalance "*" 1
-13.05578512
```

As i understood from [documentation](https://bitcoin.org/en/developer-reference#getbalance), `getbalance` == `getbalance "*" 1`

**Comment by jonasschnelli** [comment]
Do you have WatchOnly addresses?
`getbalance` should return the same as `getbalance "*" 1 true`, although, internal two code-paths are used for the calculation. There could be a bug/difference.

**Comment by message** [comment]
Sorry, since it was issue on a production server, i've rolled back to **0.11.2** with `-reindex`. I'm not going to be able to run `getbalance "*" 1 true` at the moment.

**Comment by MarcoFalke** [comment]
I think this issue was already in 0.8 or even earlier. I can't check right now, though.

**Comment by message** [comment]
With 0.11.2
```
$ ~/bitcoin/src/bitcoin-cli getbalance
8.13576857
$ ~/bitcoin/src/bitcoin-cli getbalance "*"
8.13576857
$ ~/bitcoin/src/bitcoin-cli getbalance "*" 0
8.13576857
$ ~/bitcoin/src/bitcoin-cli getbalance "*" 1
8.13576857
$ ~/bitcoin/src/bitcoin-cli getbalance "*" 1 true
8.13576857
```

**Comment by MarcoFalke** [comment]
(Related pull: #6276)
