### ISSUE TITLE
Could not enter decoderawtransaction command equal or larger than 32KB in Bitcoin-Qt console window

### ISSUE THREAD

**Issue by johnjacksonbtc** [bitcoin/bitcoin#7599]
I am using Bitcoin Core 0.12.0 Windows (zip) x64 version downloaded from https://bitcoin.org/en/download and with -txindex option. I received some unconfirmed bitcoins with [this](https://blockexplorer.com/tx/98394ab84c8c1c1194a3e40523186677d710bd28a986bc1eb65963d0a57dcf30) transaction. I was able retrieve it using getrawtransaction. But it gets truncated when entered into GUI textbox for decoderawtransaction command. File attached below.

[98394ab84c8c1c1194a3e40523186677d710bd28a986bc1eb65963d0a57dcf30-000.txt](https://github.com/bitcoin/bitcoin/files/147052/98394ab84c8c1c1194a3e40523186677d710bd28a986bc1eb65963d0a57dcf30-000.txt)

**Comment by johnjacksonbtc** [comment]
We could additionally stress test Bitcoin-Qt GUI with largest transaction ever mined
[bb41a757f405890fb0f5856228e23b715702d714d59bf2b1feb70d8b2b4e3e08.txt](https://github.com/bitcoin/bitcoin/files/147083/bb41a757f405890fb0f5856228e23b715702d714d59bf2b1feb70d8b2b4e3e08.txt)

**Comment by laanwj** [comment]
This is a known issue. 
Qt, the library that is used for the GUI, used to become unusably slow with long lines in input fields.
Apparently an safety measure now prevents the string from growing further.
I don't think that's Qt specific GUIs aren't really meant to handle these amounts of data.

I'd recommend using bitcoin-cli.

**Comment by jonasschnelli** [comment]
I agree with @laanwj. A GUI is probably not meant to paste in a 32kb plaintext. A such use-case could be handled by a "File Open" dialog (open a hex/text/bin/json file). But this seems not to be a priority.

**Comment by laanwj** [comment]
Interestingly, 32kB of text isn't any kind of problem if it's distributed over multiple lines in a multi-line editor widget.

I recommended bitcoin-cli above but just realized that there you have to be careful; I'm fairly sure shells, or terminals, don't support such long lines either. Storing it in an intermediate variable would work:
```bash
TXHEX=$((bitcoin-cli getrawtransaction HEX))
bitcoin-cli decoderawtransaction $TXHEX
```
Would be nice if the debug console supported intermediate variables, I guess...

**Comment by adamjonas** [comment]
Believe a potential GUI solution to this was introduced by https://github.com/bitcoin/bitcoin/pull/7783 where a user can insert the output of a previous command into a new one. Alternatively, `bitcoin-cli` and `-server` could be used as recommended above. Can this be closed?
