### ISSUE TITLE
0.12 RPC Error: Work queue depth exceeded

### ISSUE THREAD

**Issue by Chaz27** [bitcoin/bitcoin#7611]
Upgraded to 0.12.0 from 0.11.2 and currently experiencing this error: https://github.com/bitcoin/bitcoin/blob/62f2d769e45043c1f262ed45babb70fe237ad2bb/src/httpserver.cpp#L296

I have many threads calling getRawTransaction when a new block arrives and it seems to just bomb out randomly.

Is there any setting I am missing in the new release I can tweak?

**Comment by pstratem** [comment]
@Chaz27 You can increase the depth of the queue by changing rpcworkqueue

However you would probably be better off batching the requests

**Comment by Chaz27** [comment]
@pstratem thankyou, increased that a bit and the problem has gone away. :+1:

**Comment by laanwj** [comment]
Hm I guess you are increasing the number of threads, but not the workqueue depth which is new for 0.12.
Maybe it should warn and/or increase the work queue depth automatically with larger number of threads.
