### ISSUE TITLE
blocksonly help message

### ISSUE THREAD

**Issue by raedah** [bitcoin/bitcoin#7618]
-blocksonly didnt make it into init.cpp HelpMessage
or rather, it only shows up if debug is enabled? https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L323-L324

No information about -blocksonly in reduce-traffic.md either.
https://github.com/bitcoin/bitcoin/blob/v0.12.0/doc/reduce-traffic.md

**Comment by raedah** [comment]
I am seeing in notes on pull 7046 that it was intentionally undocumented.

**Comment by gmaxwell** [comment]
We don't have service bits to describe this operation yet. After we do it'll be more reasonable as a mainstream feature.
