### ISSUE TITLE
Warning if unable to connect to proxy

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#763]
If bitcoin is unable to connect to the proxy as specified in the configuration, we should display a banner at the bottom of the window warning ‘unable to connect to proxy, check configuarion’

**Comment by paveljanik** [comment]
@jonasschnelli Something for you to implement?

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
