### ISSUE TITLE
mempool min fee not met when using sendrawtransaction

### ISSUE THREAD

**Issue by grue0** [bitcoin/bitcoin#7630]
I'm currently using 0.12.0.

When I attempt to broadcast a 0 fee, non-dust output transaction using sendrawtransaction, I get the following error message:

```
error code: -26
error message:
66: mempool min fee not met
```

After restarting the node, the transaction broadcasts just fine. Shouldn't local RPC calls be excluded from the memory pool's fee policy?

**Comment by pstratem** [comment]
@gruez there's no bug here

local transactions are treated exactly the same way that outside transactions are treated to avoid fingerprinting attacks

**Comment by gruez** [comment]
I believe that contradicts the intention for the `whitelistforcerelay` flag. Here's the relevant comment for it.

```
                // Always relay transactions received from whitelisted peers, even
                // if they were already in the mempool or rejected from it due
                // to policy, allowing the node to function as a gateway for
                // nodes hidden behind it.
```

My interpretation of this is that the transaction should be relayed, even if it was rejected for not meeting the min mempool fee. I checked for when the check for mempool min happens, and it's after the check for `whitelistforcerelay`, which means the same transaction will also not be relayed, even if it was from a whitelisted node, which appears to contradict what was intended according to the comment.

**Comment by pstratem** [comment]
There should probably be a flag for sendrawtransaction to act as if whitelisted, default to off.

**Comment by jameshilliard** [comment]
Maybe it would be simpler to just have a "force" flag for sendrawtransaction that will override everything except consensus rules.

**Comment by luke-jr** [comment]
@pstratem @jameshilliard See #7533

**Comment by RHavar** [comment]
I ran into this other day, and an easy work around is to first call `prioritisetransaction` on the transaction setting it a high virtual fee, then sending it

**Comment by gmaxwell** [comment]
Thats a waste of time in any case, generally-- after all, if your own node wouldn't relay it because the fee is too low, then none of your peers likely will either.

The whitelist relay stuff is mostly intended to handle rebroadcasts for transactions which weren't correctly relayed the first time because you had few/no peers up at the time.

**Comment by grr** [comment]
I'm also using 0.12, but calling prioritisetransaction with a high fee doesn't work for me. I also tried to deprioritize all other transactions in the mempool with negative values, but that that didn't work either.  I have to restart bitcoind to get it accepted.

**Comment by MarcoFalke** [comment]
Not sure this is a bug. Also, a "workaround" exists.
