### ISSUE TITLE
0.12 default mintxfee too low to slow confirm & how to speed up confirm ?

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin/bitcoin#7634]
Hi , I upgrade bitcoin core to 0.12 , but 0.12 default tx fee too low to slow confirm transaction (tx fee => 0.00002260 without set mintxfee [0.11.2 : paytxfee , 0.12 : mintxfee]) ... like this

http://block.oklink.com/btc/tx/9d59d22c9c2e1a703dfafd215bf1c0eb63bc583539bcc66b6003d43cebad40d8

and the transaction is too slow and reject from blockchain.org : [[ Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database. ]]

and I fixed mintxfee and downgrade to 0.11.2 , now okay for another transactions , but is possible fast to confirm the transaction like use miner software to assign the transaction or add more txfee ? ( ...... same blockchain BTCs all been sent ... )

**Comment by jonasschnelli** [comment]
I guess your problem is not the fee.
Your transaction is trying to spend a unconfirmed input:
`https://blockexplorer.com/tx/9d59d22c9c2e1a703dfafd215bf1c0eb63bc583539bcc66b6003d43cebad40d8`

**Comment by jonasschnelli** [comment]
Your input had a extrem low static fee:
https://blockexplorer.com/tx/55ff007f89e0f1fc34a3e00664427c072afcdedff4f803ee39d1045eb1e4ed2e

That's why your `9d59d22c9c2e1a703dfafd215bf1c0eb63bc583539bcc66b6003d43cebad40d8` is not confirming.

**Comment by JokerCatz** [comment]
Hi , I show you what the happen and I use bitcoin core 0.12 and please don't close this ticket

original wallet is here

https://blockchain.info/address/1DYVzqkz1sJ5nvd3Yr5d7PUSMWtjLyGTxF

it receive 200 BTCs and 1 confirm so I start send to me customer , start with here

https://blockchain.info/tx/7f8b99f67ce1866f203bab8386b8df09f5943d0464bf08cc1cb0309d6d127232

send from 2016-02-29 14:46:42 and confirm 2016-03-01 05:43:47 (897 minutes)

and you can trace next transaction

https://blockchain.info/tx/64b3597f3119ca422b141816f7cbd14c5967553c638b997f98ac297deed89f89

and next , and next .... over 200 transaction , you can trace to like here

https://blockchain.info/tx/8f4ca81be4bd423fc203c10639f11babbd9e89623372d9828759d8b0486b6ee2

I send 200+ transaction where I receive 200 BTCs , 20+ in ver 0.12 , 180+ in ver 0.11.2

so it's not "Your transaction is trying to spend a unconfirmed input" or "Your input had a extrem low static fee" , I use default value of ver 0.12 , if default value too low , it's a bug

**Comment by jonasschnelli** [comment]
Sorry. Didn't meant to close. Re-opening.

**Comment by MarcoFalke** [comment]
@JokerCatz You can refer to the release notes on how to set transaction fees: https://github.com/bitcoin/bitcoin/blob/v0.12.0/doc/release-notes.md#wallet-transaction-fees . Please note that `-paytxfee` and `-mintxfee` are fee rates (BTC/kB) which do not take into account current network conditions.

Personally, I'd recommend using floating fees by setting `-txconfirmtarget=25` or `-txconfirmtarget=2` (based on your needs).

**Comment by JokerCatz** [comment]
@MarcoFalke okay , I got it , many thanx , dev team :) , and my ver0.12 transactions all confirmed , I don't know who help me , many...many...many thanx :D

**Comment by jonasschnelli** [comment]
Closing now. Thanks for response.

**Comment by MarcoFalke** [comment]
> transactions all confirmed

I think there is some benevolent miner crawling the web for reports of unconfirmed low-fee transactions to bump their priority locally and spread happiness. :)

(At least, having a txid showing up on GitHub or reddit is a good indicator that it is not spam)

**Comment by JokerCatz** [comment]
<del> my boss say he know who has 1/4 global bitcoin mining computing power in China and help us to confirm it ... another detail I don't know , it's very magic & social engineering , I just a developer to keep our service running ... </del>
