### ISSUE TITLE
TX fee safety

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [bitcoin/bitcoin#7638]
https://blockchain.info/tx/6fe69404e6c12b25b60fcd56cc6dc9fb169b24608943def6dbe1eb0a9388ed08

15 BTC transaction fee.

If / When the HF is done for 2 MB blocks, that would be a good time to add something to the consensus rules that prevent that kind of mistake.

For example, TX fee may not be more than the sum of the outputs. Or may not be more than 4x the largest fee in the previous block.

Or whatever makes sense.

**Comment by paveljanik** [comment]
How do you know it was a mistake?

**Comment by AliceWonderMiscreations** [comment]
A 15 BTC fee for under 7 BTC in outputs - my guess is whoever it was is using a client that does not auto adjust fees and wanted to make sure the transaction got past the spam attack and meant 15 mBTC or something similar.

Given that no pool has 50% of the network it does not seem rational or likely that the person making the transaction had a high probability of being the miner to retrieve it.

The most logical explanation is a mistake. Safety against those kind of mistakes can help grow confidence in the general population that often is afraid of making those kind of mistakes because computers to them are hard.

**Comment by jonasschnelli** [comment]
Fee handholding, safety-checks should be done by the wallets and *maybe* by the mempool acceptance (policy, miners will very likely use different policies). A change in the consensus protocol would be overblown.

**Comment by paveljanik** [comment]
Current Bitcoin Core settings:
```
  -maxtxfee=<amt>
       Maximum total fees (in BTC) to use in a single wallet transaction or raw
       transaction; setting this too low may abort large transactions
       (default: 0.10)
```

You can change this settings yourself.

If you want to propose consensus change like this, please use the mailing list for this.

**Comment by AliceWonderMiscreations** [comment]
There also is precedence for user safety with transactions. A bitcoin public address contains a four byte hash of the ripemd160 to add safety against a typo in the address being sent to.

So some safety against accidental monster TX fees because of a typo isn't without precedence.

**Comment by AliceWonderMiscreations** [comment]
@paveljanik okay I will do the mailing list

**Comment by laanwj** [comment]
We actually do this already!

It's called the "absurd fee check". It's both invoked when the transaction comes from the raw transaction API (`sendrawtransaction`), as well as when a transaction comes from the local wallet. It is enabled by default, and defaults to rejecting transactions with more than 0.1 BTC. This can be configured with `-maxtxfee`.

As long as you submit transactions through Bitcoin Core, this will protect you. Other software for submitting transactions could add a similar check.

I disagree with adding anything like this to the consensus rules. There could be legitimate reasons for donating a miner 15 BTC. But yes this is the wrong place for such a proposal.
