### ISSUE TITLE
Segmentation fault in v0.12.0

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#7639]
It dies before it even makes any network connections.

**Comment by jonasschnelli** [comment]
Some infos?
Self compiled, platform, etc.?
If the debug.log was written before the crash, can you share it?
Crash report?

**Comment by laanwj** [comment]
This is a completely un-actionable issue without more information.

Can you get a traceback (e.g. with gdb)?

**Comment by rebroad** [comment]
This is running the .exe provided by bitcoin.org on MS Windows. It seems to happen more when it has to rescan the wallet, and seems to stop after having rescanned the wallet from block 0. I am doing further testing. Please let me know if there are any specific tests you would like me to do.

**Comment by rebroad** [comment]
Being addressed by #7674
