### ISSUE TITLE
Soft Fork activation with <95% miner support

### ISSUE THREAD

**Issue by chriswheeler** [bitcoin/bitcoin#7641]
If >5% of blocks are produced by miners or pools who not running Core or another implementation which is signalling support for the soft fork, how will the soft forks be activated?

**Comment by laanwj** [comment]
If the threshold is not reached, for no matter which reason, the soft fork won't activate.

**Comment by chriswheeler** [comment]
OK but that doesn't really solve the issue. If there is not miner support at 95%, will the threshold be reduced, or is 95% set in stone?

**Comment by laanwj** [comment]
I don't expect the threshold to be reduced. Enforcing the rules of a new block version without almost-complete miner support would be irresponsible.

Take a look at BIP9 (versionbits): it allows for soft-forks to fail if they don't achieve enough support within their scheduled time allocation.
