### ISSUE TITLE
Unexpected handling of wallet.(timestamp).bak file

### ISSUE THREAD

**Issue by subSTRATA** [bitcoin/bitcoin#7647]
For some reason wallet.(timestamp).bak file which was created after user messed with wallet.dat file name WHILE Bitcoin Core was running is missing, any traces of file are gone. It is actualy more complicated so please check the thread at https://bitcointalk.org/index.php?topic=1389123.0 and follow procedure at https://bitcointalk.org/index.php?topic=1389123.msg14114474#msg14114474 to replicate the issue.

**Comment by MarcoFalke** [comment]
I can't reproduce...

Indeed, moving the wallet file to another destination while Bitcoin Core *is running* will cause

```
2016-03-06 15:07:22 Shutdown: In progress...
2016-03-06 15:07:22 StopNode()
2016-03-06 15:07:22 *** System error while flushing: CDB: Error 2, can't open database 
2016-03-06 15:07:27 CDBEnv::EnvShutdown: Error 2 shutting down database environment: No such file or directory
2016-03-06 15:07:27 Shutdown: done
```

in the debug log on shutdown. Though, I fail to see how someone could lose the wallet file by this: The wallet file should still be at the location you moved it to. (Even though it might be slightly corrupt)

**Comment by MarcoFalke** [comment]
@subSTRATA Please provide *exact* steps to reproduce, preferably from the command line. Something like 

```
>bitcoin-qt.exe -regtest -datadir=New_folder
>move "New_folder\regtest\wallet.dat" New_folder\regtest\wallet.dat_bak
        1 file(s) moved.

**Comment by subSTRATA** [comment]
Follow https://bitcointalk.org/index.php?topic=1389123.msg14114474#msg14114474 very carefuly, it is not about moving wallet.dat file while Bitcoin Core is running.

**Comment by subSTRATA** [comment]
Issue occurs only if newly created wallet.dat is renamed within the same session. If Bitcoin Core was restarted between creation of a new wallet.dat file and renaming it no problems occur, see step 2b. and consequently different outcome at step 5.

1. Shutdown Bitcoin Core then move existing wallet.dat to some other directory.
2. Start Bitcoin Core, it will create a new wallet.dat file.
2b. Shutdown Bitcoin Core then start it again.
3. While Bitcoin Core is running, rename newly created wallet.dat to whatever else.
4. Shutdown Bitcoin Core, it will throw an error and exit.
5. Rename file back to wallet.dat and start Bitcoin Core again, no problems whatsoever.

**Comment by MarcoFalke** [comment]
I see; This is not reproducible always. Pretty much you rename a corrupt `wallet.(timestamp).bak` file to `wallet.dat` until you get a `__db*` file, which will be deleted on the next start. I could reproduce once but I forgot to save the `wallet.(ts).bak` file. Would you mind uploading one? (Make sure it is for testnet/regnet or does not contain any relevant keys)

**Comment by subSTRATA** [comment]
I can reproduce it always, just follow linked procedure exactly. Just in case it realy does not work for you here is .bak I just created, mainnet private keys but no worries, it is created just for this test.

[https://mega.nz/#!yAZzSQbZ!mZK0q43dm1BIXvIQAx2ZiuCXZRk3_o9shiv2pTcTmrk](https://mega.nz/#!yAZzSQbZ!mZK0q43dm1BIXvIQAx2ZiuCXZRk3_o9shiv2pTcTmrk)

**Comment by MeshCollider** [comment]
I've tried to reproduce this following the steps from the bitcointalk thread on 0.16 and using the downloadable wallet above, and cannot reproduce, so this can be closed

**Comment by jwhitehead91** [comment]
This is still an issue apparently. 
https://www.reddit.com/r/btc/comments/a1kr9z/huge_problem_with_reward_100btc_serious/
