### ISSUE TITLE
bitcoin-qt v0.12.0 crash on Settings menuitem select

### ISSUE THREAD

**Issue by CraniumDad** [bitcoin/bitcoin#7672]
I'm new (newbie) to using Bitcoin Core software.  I'm running Bitcoin Core v0.12.0.0-g188ca9c on Ubuntu "14.04.4 LTS, Trusty Tahr" Linux with all updates installed.  X-windows manager is XFCE4.

When I try to open the Settings feature in the bitcoin-qt GUI in X-windows, the program crashes with one line in the debug log:
`GUI: ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt4/QtCore/qlist.h, line 469`

I'm starting the bitcoin-qt process from my personal user account with the following start command:
`sudo -i -u btcusr bitcoin-qt`

My /home/btcusr/.bitcoin/bitcoin.conf file is as follows:
`rpcuser=bitcoinrpc`
`rpcpassword=`*secret*
`server=1`
`onlynet=ipv4`
`bind=10.2.31.16`
`timeout=15000`
`listen=1`
`maxconnections=32`

/home/btcusr/.bitcoin/ looks like this:
`drwxr-x--- 6 btcusr btcgrp    4096 Mar 12 11:36 ./`
`drwxr-xr-x 5 root    btcgrp    4096 Mar 11 17:30 ../`
`-rw------- 1 btcusr btcgrp     199 Mar 11 18:55 bitcoin.conf`
`-rw------- 1 btcusr btcgrp      76 Feb 27 22:13 bitcoin.conf.bak`
`-rw------- 1 btcusr btcgrp       5 Mar 11 21:06 bitcoind.pid`
`drwx------ 3 btcusr btcgrp   36864 Mar 11 21:37 blocks/`
`drwx------ 2 btcusr btcgrp   36864 Mar 12 11:44 chainstate/`
`drwx------ 2 btcusr btcgrp    4096 Mar 11 18:56 database/`
`-rw------- 1 btcusr btcgrp       0 Feb  4 21:36 db.log`
`-rw------- 1 btcusr btcgrp 4043923 Mar 12 11:50 debug.log`
`-rw------- 1 btcusr btcgrp   24726 Mar 11 18:53 fee_estimates.dat`
`drwx------ 3 btcusr btcgrp    4096 Mar 11 17:29 .local/`
`-rw------- 1 btcusr btcgrp       0 Feb  5 21:14 .lock`
`-rw------- 1 btcusr btcgrp   81290 Mar 12 11:36 peers.dat`
`-rw------- 1 btcusr btcgrp   61440 Mar 12 11:37 wallet.dat`

**Comment by MarcoFalke** [comment]
Did `btcusr` run a previous version of Bitcoin Core?

**Comment by MarcoFalke** [comment]
Anyway, you may want to try `-resetguisettings` or https://github.com/bitcoin/bitcoin/issues/7366#issuecomment-175740988

**Comment by CraniumDad** [comment]
Yes, `btcusr` ran previous version of Bitcoin Core.  Tried command `sudo -i -u btcusr bitcoin-qt -resetguisettings' and still got crash on selecting Settings.  

Seems from [#7366 ](https://github.com/bitcoin/bitcoin/issues/7366#issuecomment-175740988) may have a permission issue but not clear what file or sudo issue.

**Comment by laanwj** [comment]
@CraniumDad in that issue, `~/.config/Bitcoin/Bitcoin-Qt.conf` was (or the directory it was in) was owned by the wrong user

**Comment by CraniumDad** [comment]
Here was the cause of the error...

/home/btcusr/.bitcoin/ included:
`drwxr-xr-x 5 root btcgrp 4096 Mar 11 17:30 ../ `

I chmod'ed /home/btcusr to g+w (775) instead of 755 and problem fixed.

It would be better for bitcoin-qt to gracefully produce an error message instead of full crash of the process.

**Comment by jonasschnelli** [comment]
Can't reproduce this issue on my OSX machine (a chown to `root` and a chmod to `500`) did not gave me the described error.
@CraniumDad: mind doing a retest with the current master?

**Comment by CraniumDad** [comment]
Permissions issue on parent folder in Linux.
