### ISSUE TITLE
Qt GUI Feature Request: Load wallet file

### ISSUE THREAD

**Issue by kristovatlas** [bitcoin/bitcoin#7675]
I would like there to be a an option in the File menu of Bitcoin-Qt to load a previously exported wallet.dat file. Selecting this option would present the user with a file selection dialog. Once the user selects the file, the wallet should be reloaded with the new wallet to ensure that no previous network connections are reused, for privacy reasons.

This would facilitate much easier switching between wallets. As Bitcoin-Qt has no hierarchical account support, this would help users better segregate funds for their multiple online identities without a lot of accounting and Coin Control use.

**Comment by kristovatlas** [comment]
Tagging @gmaxwell as this is something we've talked about before.

**Comment by laanwj** [comment]
I think it would be better to implement "Using multiple wallet files with bitcoind #3113" instead

**Comment by laanwj** [comment]
The easy way to do this - without implementing full multi-wallet support at runtime - would be to check if there are multiple wallets in the data directory at start-up.
If there are, show a selection menu. Then start with the selected wallet as if passing the following option:
```
  -wallet=<file>
       Specify wallet file (within data directory) (default: wallet.dat)
```
Restarting the client would also do "ensure that no previous network connections are reused".

To make client restart fast, skip the block check (e.g. `-checklevel=0`).

**Comment by luke-jr** [comment]
It's actually easier to do multiwallet than hot-load/unload (see #8694). Additionally, you really want to have all the wallets loaded all the time to avoid rescanning...

**Comment by Sjors** [comment]
The latest multiwallet action is at  #11383 & #12610. Dynamic wallet loading WIP at #10740.

**Comment by promag** [comment]
Also related #11687.

**Comment by fanquake** [comment]
Going to close this now that #15153 has been merged. The remaining wallet load/unload progress is likely better tracked in #13059 or https://github.com/bitcoin/bitcoin/projects/2.
