### ISSUE TITLE
Never create uneconomical output

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#7677]
I noticed that [wallet.cpp](https://github.com/bitcoin/bitcoin/blob/86a1ec5b2c9778660768ea9fe0037381b29883d2/src/wallet/wallet.cpp#L2133) and [coincontroldialog.cpp](https://github.com/bitcoin/bitcoin/blob/e1060c56cca7eeab8e217eb7b416c16487fd175e/src/qt/coincontroldialog.cpp#L568) try to not produce dust output.

The original intention of "dust" is to not create uneconomical output. However, using minTxRelayFee as the basis for minimum output value we don't ensure uneconomical output, we only ensure that the transaction is not rejected by our own node policy.

A change of default minTxRelayFee as done in https://github.com/bitcoin/bitcoin/pull/6793 can suddenly mean that a transaction created by a wallet will not be accepted by other nodes because you are still using the old minTxRelayFee when creating your transactions.

Using estimatedFee instead of minTxRelayFee in wallet code would not only make sure that the creation of an output is economically profitable, but also ensure that a sudden change of minTxRelayFee by other nodes don't impact the confirmation time of transaction created by the wallet. It has the indirect advantage to make the UTXO smaller.

I will probably try to implement that, I just want your thoughts about the idea first.

**Comment by chris-belcher** [comment]
This requires predicting future prices.

Previously economical outputs might become uneconomical because of a rise in miner fees. Previously uneconomical outputs might become economical because of a rise in bitcoin's exchange rate or new technology (CoinJoin, OP_SCHNORR)

Probably the best that can be done is to make them economical today.

**Comment by NicolasDorier** [comment]
> Probably the best that can be done is to make them economical today.

Indeed estimatefee indeed take the decision based on today's price which is the best we can do. This is still closer to reality than using minTxRelayFee.

**Comment by Xekyo** [comment]
@NicolasDorier: AFAIK dust calculates from the size of a P2PKH input (148 bytes) plus the size of a P2PKH output (34 bytes). The 148 bytes seem to be hardcoded:

        size_t nSize = GetSerializeSize(SER_DISK, 0);
        int witnessversion = 0;
        std::vector<unsigned char> witnessprogram;

        if (scriptPubKey.IsWitnessProgram(witnessversion, witnessprogram)) {
            // sum the sizes of the parts of a transaction input
            // with 75% segwit discount applied to the script size.
            nSize += (32 + 4 + 1 + (107 / WITNESS_SCALE_FACTOR) + 4);
        } else {
            nSize += (32 + 4 + 1 + 107 + 4); // the 148 mentioned above
        }

Not sure whether that's what you said. ;)

**Comment by Leviathn** [comment]
@nicholasdorier is this still pending? Not sure whether resolvable, may be closeable.

**Comment by Leviathn** [comment]
@nicolasdorier

**Comment by MarcoFalke** [comment]
Related pulls: #10817, #10637

**Comment by NicolasDorier** [comment]
I think #10817 is meant to fix it, but there is still the problem on QT I think  https://github.com/bitcoin/bitcoin/blob/e1060c56cca7eeab8e217eb7b416c16487fd175e/src/qt/coincontroldialog.cpp#L572 ping @morcos

**Comment by morcos** [comment]
I believe this can be closed.

For a long time Core has tried not to produce change below .01 BTC.

In the edge cases where we can't create change that high, the rate at which we'll throw away a change output has been increased by 10/3 to the discard rate.

But at the end of the day its still possible to have an output just above the dust rate if you ask to pay someone that.

**Comment by NicolasDorier** [comment]
Ok, closing that, will reopen if I encounter the problem again.
