### ISSUE TITLE
End support for Windows XP and older

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7681]
Drop support for Windows XP and older - at some point. 

Microsoft support for Windows XP ended April 8th, 2014 (https://www.microsoft.com/en-us/WindowsForBusiness/end-of-xp-support). This means that not even critical security updates are being released anymore. This makes it dangerous to run a wallet on this OS.

There are also some strange, apparently random crashes on WinXP with 0.12, see #7674 and #7639.

I haven't heard of any reports of this happening on other versions of windows.

I hope it is possible to debug and fix this, but if not, and it turns out to be truly a WinXP only issue, we'll have to announce this through the appropriate channels.

**Comment by rebroad** [comment]
I agree that XP should certainly not be used for wallets, but it would be a shame not to be able to utilise older hardware running XP for use as a full-node.

**Comment by coinyBit2** [comment]
XP can be used as "safe" as newer versions of Windows if one takes the appropriate precautions. Most vulnerabilities stem from insecure internet browsing using standard configurations. (Btw. XP fixes are still available, coming from sales terminal WinXP, which has not reached EOL.)

The great advantage of WinXP is that it consumes far less resources than newer versions and is highly stable as well. Great for running full nodes on weaker computers.

**Comment by laanwj** [comment]
I agree, for now I'll let this depend on whether #7674 gets resolved.

We've always had a problem with the windows version not being as actively supported as the linux/osx versions, as most developers use one of those. I doubt anyone is actively developing on XP. But surprise me.

**Comment by btcdrak** [comment]
@coinyBit2 XP is not officially supported by Microsoft. It's a 3rd party, independent developer called [harkaz](http://www.ryanvm.net/forum/viewtopic.php?t=10321), [source](http://www.forbes.com/sites/gordonkelly/2014/09/03/unofficial-windows-xp-sp4-launched-microsoft-os-lives-on/#3ce5c8ff56bf).

Bitcoin Core is financial software so unfortunately cannot responsibly keep supporting a vulnerable platform, regardless of well meaning 3rd party support.

**Comment by jonathancross** [comment]
As someone who had to retire an old XP system recently, I understand how you feel, but I agree with @laanwj and @btcdrak on this one.

> utilise older hardware running XP...

The hardware would be much better utilized with [Xubuntu](http://xubuntu.org/) or [Lubuntu](http://lubuntu.net/) for example.  I'd recommend taking the plunge and trying it out.

If the goal is to benefit to the Bitcoin network (rather than running a wallet), then we might call into question the benefit such an old system will bring to the network.

**Comment by laanwj** [comment]
Nicely said @jonathancross

**Comment by tzofeolam** [comment]
There seems to be no Windows XP related problem in the Bitcoin Core code itself but in the QT library it uses. And the QT project still supports Windows XP and fixes backward compatibility bugs related to Windows XP. Please read me comment in #7674 and consider either upgrading to the latest QT version or using a custom QT (older version that is currently in use) build with -no-directwrite flag.

**Comment by diegoviola** [comment]
Qt is spelled Qt.

**Comment by diegoviola** [comment]
Just run Linux.

**Comment by HenryBarton** [comment]
I'm with tzofeolam: Let's upgrade QT in 0.13. XP is very much alive and I hate to see great software drop support for it "just 'cause", even when the program doesn't require modern API's.
