### ISSUE TITLE
Get hidden service address

### ISSUE THREAD

**Issue by Levino** [bitcoin/bitcoin#7700]
I could not find anything on how to get the hidden services address when running with "listenonion=1". Can I get it from the logs?

**Comment by laanwj** [comment]
`getnetworkinfo` should have it under "localaddresses"

**Comment by Levino** [comment]
Most helpful.

But the localaddresses array is empty... This is what I get

```bash
{
  "version": 120000,
  "subversion": "/Classic:0.12.0/",
  "protocolversion": 70012,
  "localservices": "0000000000000005",
  "timeoffset": 0,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00005000,
  "localaddresses": [
  ],
  "warnings": ""
}
```
When I look into the debug.log I see this:
```bash
2016-03-17 08:09:04 tor: Connected to Tor version 0.2.7.6
2016-03-17 08:09:04 tor: Supported authentication method: COOKIE
2016-03-17 08:09:04 tor: Supported authentication method: HASHEDPASSWORD
2016-03-17 08:09:04 tor: Supported authentication method: SAFECOOKIE
2016-03-17 08:09:04 tor: Using SAFECOOKIE authentication, reading cookie authentication from /var/run/tor/control.authcookie
2016-03-17 08:09:04 tor: Authentication cookie /var/run/tor/control.authcookie could not be opened (check permissions)
```
I put in the password for the control service with "torpassword=password". I do not want to use cookieauthentication. Is the setup actually failing?

**Comment by Levino** [comment]
Sorry, I have to add one thing: I am still reindexing. Maybe that is the issue.

**Comment by laanwj** [comment]
Yes, the setup is failing. If it's not actually authenticating to tor it won't get a hidden service address.
Disabling cookie authentication at the Tor side should solve this.
Reindexing doesnn't have to do with it.

**Comment by laanwj** [comment]
BTW, for issues with classic you should use this issue tracker: https://github.com/bitcoinclassic/bitcoinclassic/issues

**Comment by Levino** [comment]
:) I understand your point @laanwj But this is such a basic part of the code that I hope it is okay that I put the issue where I would assume it might have come from.

Thanks for the feedback.

**Comment by Levino** [comment]
@laanwj Verified the fix. For anyone else having issues: I actuallty had to set 
```
CookieAuthentication 0
```
in the ```/etc/tor/torrc``` to make it work.

**Comment by laanwj** [comment]
See also #7703

> :) I understand your point @laanwj But this is such a basic part of the code that I hope it is okay that I put the issue where I would assume it might have come from.

Principally we can't support custom changes on top of the code, it's not our responsibility and also makes it impossible to determine what bug comes from our code or from other's changes. So - before reporting here at least make sure that you tested that it also happens with the code from here.
(in this case that was clear, sure)

**Comment by Levino** [comment]
One last thing @laanwj if you dont mind. How can I make the bitcoind accept connections on tor AND ipv4 AND ipv6. I am trying this:
```sh
# bitcoin.conf configuration file. Lines beginning with # are comments.
daemon=1
listen=1
rpcpassword=bbbbb
minrelaytxfee=0.00005
torpassword=xxxxx
discover=1
```
but get this:
```bash
bitcoin-cli getnetworkinfo
{
  "version": 120000,
  "subversion": "/Classic:0.12.0/",
  "protocolversion": 70012,
  "localservices": "0000000000000005",
  "timeoffset": -1,
  "connections": 13,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    }
  ],
  "relayfee": 0.00005000,
  "localaddresses": [
    {
      "address": "kljhw4txgqymrcer.onion",
      "port": 8333,
      "score": 4
    }
  ],
  "warnings": ""
}
```
Looks to me as if the local ipv4 and ipv6 is not being used / propagated to the network...

**Comment by laanwj** [comment]
Yes, that is supported - if you're not using either `-onlynet` or `-proxy` explicitly, it should use tor/onion as additional network, so that should be ok.

**Comment by Levino** [comment]
Should it then not list my ip addresses in the "localaddresses" array?
