### ISSUE TITLE
Starting with boot on raspberry pi 3 leads to error on rpc bind

### ISSUE THREAD

**Issue by Levino** [bitcoin/bitcoin#7701]
I get this

```
2016-03-16 17:17:08 libevent: getaddrinfo: address family for nodename not supported
2016-03-16 17:17:08 Binding RPC on address 127.0.0.1 port 8332 failed.
```

When I start bitcoind not during boot but later with the same script it works.

**Comment by Levino** [comment]
Related / same issue? https://github.com/bitcoin/bitcoin/issues/6655

**Comment by laanwj** [comment]
How are you starting it during boot?
You've added a dependency that at least networking is up by the time bitcoind is started?

**Comment by Levino** [comment]
I use this script: https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service

Following this: https://github.com/bitcoin/bitcoin/blob/master/doc/init.md#4-installing-service-configuration Step 4a)

**Comment by ayeowch** [comment]
I have used `@reboot bitcoind -daemon` cron entry in the past and found the same issue on my Raspberry Pi. Updating the entry to `@reboot sleep 5; bitcoind -daemon` seems to have resolved the issue for me.
