### ISSUE TITLE
Pending issues for `abandontransaction`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7704]
#7312 introduced the RPC call `abandontransaction` last minute before 0.12, there was still some work to be done:
- [x] Return abandoned status in listtransactions
- [x] Return abandoned status in GUI
- [x] Fix any issues with how abandoned txs should sort
- [x] Add a way to abandon transactions from GUI
- [ ] abandontransaction may not work in some cases for conflicted transactions imported from old wallets (see #7690)

**Comment by jonasschnelli** [comment]
Woking on 1 and 2.

**Comment by jonasschnelli** [comment]
- Return abandoned status in list transactions
- Return abandoned status in GUI
- Add a way to abandon transactions from GUI

... are addressed in https://github.com/bitcoin/bitcoin/pull/7707

**Comment by jonasschnelli** [comment]
I guess points 1-4 are solved? Not sure about 5.

**Comment by laanwj** [comment]
Thanks, updated the OP

NOt sure about 5 either.

**Comment by jonasschnelli** [comment]
@morcos regarding point 5 `abandontransaction may not work in some cases for conflicted transactions imported from old wallets`, I guess the special abandoned hash can't be the problem?

**Comment by morcos** [comment]
@jonasschnelli I think this can be closed.  The issue mentioned in #7690 was fixed to the degree possible by #7715.   There are some minor outstanding issues around conflicted transactions documented in #7315 and #8692 but I don't see them getting fixed any time soon and they aren't really caused by abandontransaction.

**Comment by jonasschnelli** [comment]
@morcos: Thanks for the infos. Closing.
