### ISSUE TITLE
After unexpected shutdown (From power loss) got an error re downloaded getting another error

### ISSUE THREAD

**Issue by jbakis** [bitcoin/bitcoin#7719]
![untitled](https://cloud.githubusercontent.com/assets/17947938/13898626/cfc0ccac-edad-11e5-899c-1ddde2f6e835.jpg)

This is the error i am getting can anyone help me out?

**Comment by sipa** [comment]
Which version is this?

**Comment by jbakis** [comment]
uhh its 11.2 but i just updated still getting the same error only difference is it says line 1977 instead

**Comment by MarcoFalke** [comment]
Could you share what settings you change in `.conf` or via command line options? Other than that, I'd guess you have corrupt data. You may want to try `-reindex` to read all block files from disk again.

**Comment by jbakis** [comment]
Okay well im just gunna simply say im not sure how to do those things :/ sorry but its a fresh install i cant even get into the app to reload my wallet backup

**Comment by MarcoFalke** [comment]
You can find the `wallet.dat` in the datadir: https://en.bitcoin.it/wiki/Data_directory#Windows

If you don't know how to tell bitcoin core to reindex, you can create a file in the datadir: `bitcoin.conf` with the content `reindex=1` and then start bitcoin core once. Exit bitcoin core. Finally, remove the line from the `.conf` again.

**Comment by jbakis** [comment]
Yes that has worked! Thank you soo much! Now to sync back with the network!

**Comment by MarcoFalke** [comment]
Good to hear! You may want to close this issue if you no longer see problems.
