### ISSUE TITLE
unable to start & sync bitcoin qt 

### ISSUE THREAD

**Issue by luzuluzu** [bitcoin/bitcoin#7724]
Bitcoin qt stopped block sync at ~3year behind, and did not progressed forward, after restarting client , loading window keeps showing "Activating best chain", one cpu core is loaded to max, debug log is filling only with:
"ERROR: CheckBlock(): hashMerkleRoot mismatch
ERROR: ConnectTip(): ConnectBlock 000000000000001ac44abd9ad8f45f7078299da4e877b00c30cb9fb90d86bc4e failed"

I tried syncing earlier this day but I had same issue when sync stopped ~6y behind, I deleted all data to start syncing again from zero.

Bitcoin 12.0 64bit version, windows

**Comment by luzuluzu** [comment]
after deleting all data and starting sync from zero last entry before errors in log file:

UpdateTip: new best=000000000000002e6d20ae6ff73f7ee3d22c3c62bf48e562238add377c19febc  height=252682  log2_work=71.272041  tx=22241462  date=2013-08-17 18:27:50 progress=0.089024  cache=768.7MiB(2045157tx)

and after that:

2016-03-20 21:15:34 ERROR: CheckBlock(): hashMerkleRoot mismatch
2016-03-20 21:15:34 Misbehaving: 173.56.108.53:8333 (0 -> 100) BAN THRESHOLD EXCEEDED
2016-03-20 21:15:34 ERROR: ConnectTip(): ConnectBlock 000000000000003499e5f23dc8213d6ba514b55cc37ea82e507c3b95f460c965 failed
2016-03-20 21:15:34 ERROR: CheckBlock(): hashMerkleRoot mismatch
2016-03-20 21:15:34 Misbehaving: 173.56.108.53:8333 (100 -> 200)
2016-03-20 21:15:34 ERROR: ConnectTip(): ConnectBlock 000000000000003499e5f23dc8213d6ba514b55cc37ea82e507c3b95f460c965 failed
2016-03-20 21:15:34 ERROR: CheckBlock(): hashMerkleRoot mismatch
2016-03-20 21:15:34 Misbehaving: 173.56.108.53:8333 (200 -> 300)
2016-03-20 21:15:34 ERROR: ConnectTip(): ConnectBlock 000000000000003499e5f23dc8213d6ba514b55cc37ea82e507c3b95f460c965 failed


and it keeps filling same pattern , "Misbehaving" entry number in () is increasing by 100, nothing else happens, 1 cpu core usage 100%, Ram usage 1GB

**Comment by sipa** [comment]
That looks like corrupted memory or overheated CPU.

Bitcoin Core, especially during initial sync, is far more resource heavy
than most programs, and can cause problems to appear in systems that are
normally behaving fine. In addition, it's also extraordinarily susceptible
to very small errors.

What you're seeing is a validation failure of the blockchain. Bitcoin Core
assumes it's being fed an invalid chain by its peers, and disconnects them
as a result.

Usually when this happens, it helps to run with lower parallellism (setting
par=1 in bitcoin.conf), however, your failure occurs so early in the chain
that I doubt that will have an influence.

**Comment by jorijnsmit** [comment]
For me this appears to be a memory overload problem. Even though bitcoind is saying to only use 30% over memory it is using a huge piece of cache too:
```
top - 13:39:53 up 6 days, 21:58,  1 user,  load average: 1.30, 1.26, 1.18
Tasks: 122 total,   2 running, 120 sleeping,   0 stopped,   0 zombie
%Cpu(s): 79.5 us, 20.5 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  869.703 total,   74.281 free,  284.324 used,  511.098 buff/cache
MiB Swap:  895.996 total,  860.285 free,   35.711 used.  439.270 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                     
 6385 root      20   0  439468 273964   5576 S 72.8 30.8   9:02.49 bitcoind                                                                    
  390 root      20   0    5580   2084   1972 S 16.2  0.2 217:31.33 systemd-journal                                                             
  836 syslog    20   0   30728   2380   1520 S 11.3  0.3 138:39.41 rsyslogd                                                                    
    7 root      20   0       0      0      0 R  0.7  0.0  10:46.16 rcu_sched                                                                   
 8667 jorijns+  20   0    8020   3584   3056 R  0.3  0.4   0:00.19 top                                                                         
32697 jorijns+  20   0   13312   1548   1436 S  0.3  0.2   0:18.73 sshd                                                                        
    1 root      20   0    6644   3940   3004 S  0.0  0.4   3:35.91 systemd                                                                     
    2 root      20   0       0      0      0 S  0.0  0.0   0:00.15 kthreadd                                                                    

```
