### ISSUE TITLE
Sync takes too long

### ISSUE THREAD

**Issue by destenson** [bitcoin/bitcoin#7725]
Version 0.12.0 is unusable for me on Windows 10. I started using it shortly after it came out & after downloading hundreds of GB in that time, it's never gotten the blockchain caught up to live. The problem is not my computer's performance (i7-2600 @ 3.7GHz, 16GB RAM & multiple SSD drives). I have tried on this PC & a laptop (who's non-SSD hard drive ended up failing from all the thrashing). I have tried starting from a clean %HOME%/AppData/Roaming/Bitcoin directory multiple times and it takes dozens of hours to download and in that time, closes unexpectedly (with no indication except it's no longer running) or crashes, corrupting the blockchain requiring a restart from scratch, or an equivalently lengthy reindex.

I'm now using git to version control my %HOME%/AppData/Roaming/Bitcoin so that I can restore the blockchain when it crashes and requires reindex. But that's extremely tedious and inefficient (yet faster than letting bitcoin attempt to reindex).

And today, I tried to uninstall it and reinstall v0.11.2 (which did not suffer from this). But when I run it, Windows says that the program exited unexpectedly, with no other information useful for troubleshooting. So, I just have to put up with this extraordinary inefficiency from now on? What? Do you not want people to use bitcoin anymore?

**Comment by luke-jr** [comment]
You sound like you're familiar with both developer tools and Windows. Can you get more information on the "closes unexpectedly" problem you're encountering with 0.12?

> And today, I tried to uninstall it and reinstall v0.11.2 (which did not suffer from this). But when I run it, Windows says that the program exited unexpectedly, with no other information useful for troubleshooting. 

Did you follow the downgrade instructions that specifically say you must run with -reindex?

> Do you not want people to use bitcoin anymore?

None of the current Bitcoin Core developers (AFAIK) use Windows, and it gets tested mainly by users during the release-candidate stage. So until someone reports a Windows-specific issue, we probably won't know about it.

**Comment by luzuluzu** [comment]
Maybe you see something like I see in debug log file #7724 ?

**Comment by destenson** [comment]
I did also have the problem today noted in #7724, that's what prompted me to abandon v0.12.0 altogether & try v0.11.2 again.

I did not follow the downgrade instructions. Instead, I removed the contents of %HOME%/AppData/Roaming/Bitcoin altogether so it would start from scratch & not try to reuse the blocks downloaded by v0.12.0. That should've worked no matter what unless there are registry entries or other configuration files I'm not aware of that didn't get deleted by the v0.12.0 uninstall.

I cannot get anymore information about the "program has exited unexpectedly" message from Windows. It's literally one of the most useless messages I've seen windows display. It contains no useful information at all. (I am a developer so I know what useful information looks like.) The actual error message is:

> Microsoft Visual C++ Runtime Library
> 
> Runtime Error!
> 
> Program: C:\Users\deste\Apps\BitcoinCore\bitcoin-qt.exe
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.

**Comment by destenson** [comment]
OK, I ran v0.11.2 from the command line & found that the unusual termination was due to having an uninitialized %HOME%\AppData\Roaming\Bitcoin directory. The error was:

> terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
>  what():  boost::filesystem::create_directory: Cannot create a file when that file already exists: "C:\Users\deste\AppData\Roaming\Bitcoin"

I will give that a go again to download the blockchain & verify that it behaves as it used to.

**Comment by laanwj** [comment]
> lost a customer

Now that's funny. How much were you paying us?

Please be civil here, or just stay away.
