### ISSUE TITLE
Feat Request (Qt/GUI): Tor status indicator icon in bottom right

### ISSUE THREAD

**Issue by kristovatlas** [bitcoin/bitcoin#7734]
The current QT GUI shows some network status indicators in the bottom right.

I'd like someone to add one for Tor. It might be the Tor onion logo that is either green, yellow (if going through some not-quite-ready stage) or with a circle and line striking through it when not connected via Tor.

This would complement the Tor-related improvements in 0.12.0 and make it easier for users to determine whether they are connected via Tor without doing additional investigatory steps, such as using the  `-debug=tor` switch.

**Comment by kristovatlas** [comment]
Side note: OBPP currently has two criteria relevant to this https://github.com/OpenBitcoinPrivacyProject/wallet-ratings/blob/master/report-02/criteria.md

> Client provides a visual indication if the balance information is not being obtained through an anonymizing network, including IP address information (2.142%)
> Client provides a visual indication if outgoing transactions are not being routed through an anonymizing network, including IP address information (1.713%)

**Comment by laanwj** [comment]
Makes sense.
I think in general we need a proxy indicator. Having a specific Tor icon as a special case would be nice, of course.
See also #763 ("Warning if unable to connect to proxy")

**Comment by kristovatlas** [comment]
If there is conceptual support but no one else eager to implement, I might take a stab at this.

**Comment by jonasschnelli** [comment]
@kristovatlas Concept ACK. I'm ready to support, review and test a PR.

**Comment by gmaxwell** [comment]
A fine thing to do, BUT--

> Side note: OBPP currently has two criteria relevant to this https://github.com/OpenBitcoinPrivacyProject/wallet-ratings/blob/master/report-02/criteria.md
>  Client provides a visual indication if the balance information is not being obtained through an anonymizing network, including IP address information (2.142%)

Bitcoin Core never contacts a third party for balance information.

**Comment by kristovatlas** [comment]
@gmaxwell: ah, completely true. there may be some benefits to putting all traffic through Tor, though.

**Comment by sipa** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
Implementation could be done similar to #8517

**Comment by Leviathn** [comment]
Concept ACK - would be very useful for GUI users..

**Comment by drbsci** [comment]
Hi. I'm trying this as a first issue. I'm thinking of using just the Tor onion for disconnected, the whole Tor symbol with the onion in the middle for connected and the Tor symbol with purple -> yellow for connecting (attached).
![tor2](https://user-images.githubusercontent.com/11467954/32138625-e74103e4-bc03-11e7-89ab-9a88f3bcf95f.jpg)
.
![onion](https://user-images.githubusercontent.com/11467954/32138609-ab6c116a-bc03-11e7-9102-f6f1283f0d6f.jpg)
![tor png](https://user-images.githubusercontent.com/11467954/32138620-c4a5cd7e-bc03-11e7-8bea-dcd0d9ac526c.jpg)
I was hoping I could make this change mostly within Qt Creator, but the bitcoin-qt.pro file in contrib somehow wasn't able to find main in bitcoin/src/qt. Possibly adding the Tor symbols should be done within the qt source code? Anyway, I'm stuck and wondering whether you could point me in the right direction without too much difficulty.
I've read something about signals and slots. Presume the state of Tor (connected, etc.) is the signal and the image display is the slot, and I'd use the "connect" syntax to link them.
As you can see, I'm very new to Qt. Please let me know whether this still looks like a good first issue for me.

**Comment by jonasschnelli** [comment]
The main point I'm worried about the "Is-tor-enabled" icon is, if we can signal that reliable from our layer. Just checking if a proxy is active in 127.0.0.1:9050 seems not enough,... 
A positive-false signalling here could have wide consequences.

**Comment by lmlsna** [comment]
A possible kludgey check if tor is up and running is to just send a dummy HTTP request directly to the tor socks proxy port. If tor is running, it will politely respond with a `HTTP/1.0 501 Tor is not an HTTP Proxy`, if it isn't, it won't. 

This misses the possibility that the tor client is running but unable to connect, however that would result in a broken connection (as opposed to an accidental clearnet connection). However, I can't think of any way to verify tor is actually working other than either asking `tor-arm` (which might not be there) or requesting https://check.torproject.org/ through the proxy (like the TBB does).

**Comment by fanquake** [comment]
Moved this over to the GUI repo: https://github.com/bitcoin-core/gui/issues/58.
