### ISSUE TITLE
Drop the leading 0. in version numbers

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#7735]
Why don't we just drop the leading 0. in version numbers? AFAICT that field will never be used anyways. The versions would still be the same thing and have the same meaning, just that they wouldn't have the 0. in front of it.

**Comment by luke-jr** [comment]
It will be used when we reach 1.0. There's still a long way to go before we get there.

**Comment by achow101** [comment]
well based on this email: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011323.html (and some of the stuff that follows), it looks like Bitcoin Core will never reach 1.0.

**Comment by laanwj** [comment]
Like other open source software, we use a standard `MAJOR.MINOR.PATCH` versioning scheme. Not worth the bother to change this.

**Comment by MarcoFalke** [comment]
@achow101 Please find further information on https://bitcoincore.org/en/lifecycle/#versioning
