### ISSUE TITLE
Client/networking too slow to receive peer identification

### ISSUE THREAD

**Issue by FabioCarpi** [bitcoin/bitcoin#7738]
My cliente is taking too long to receive the servers identification :(
![capturar](https://cloud.githubusercontent.com/assets/6897978/13986697/99f877ae-f0e2-11e5-9de8-b759f6a9be44.PNG)

**Comment by paveljanik** [comment]
@FabioCarpi what version do you use? Can't reproduce here with the current master.

**Comment by laanwj** [comment]
Looks like a problem with his ISP, to be honest.
