### ISSUE TITLE
test: wallet reindex test has a race

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7745]
It doesn't actually wait for the reindex to complete - so sometimes one gets this error, where there's no balance yet:
```
check -reindex
Assertion failed: [Decimal('33.99911100'), Decimal('5649.99796160'), Decimal('59.99974800')] != [Decimal('33.99911100'), Decimal('5649.99796160'), Decimal('0E-8')]
  File "/data/src/bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "./wallet.py", line 296, in run_test
    assert_equal(balance_nodes, [self.nodes[i].getbalance() for i in range(3)])
  File "/data/src/bitcoin/qa/rpc-tests/test_framework/util.py", line 428, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
Stopping nodes
Cleaning up
Failed
```
The error is kind of rare as reindexing of the regtest chain is very fast.
It does seem to happen more after #7744, as it has less delay in the startup.

**Comment by MarcoFalke** [comment]
I wasn't really sure what is required here but it seems connecting the nodes is too much, so I removed that in fad7dc8a6c0ca9c067a249cf8896dd2e64703e48.

**Comment by laanwj** [comment]
Most straightforward would be to get the block height before the maintenance tests, store it, then after the reindex poll and wait for the block height to be that again.

**Comment by MarcoFalke** [comment]
Shouldn't the call fail instead and indicate that the node is still "loading"?

```sh
$ src/bitcoin-cli -testnet getbalance
error code: -28
error message:
Loading block index...
```

**Comment by laanwj** [comment]
When?

**Comment by MarcoFalke** [comment]
> It doesn't actually wait for the reindex to complete

> waits for the warmup phase (code -28) to finish.


So reindex is not counted as "warmup" but should be, instead?

**Comment by sipa** [comment]
I'm not sure. Reindex is not really special, as the node is fully up and
running (apart from block sync), it's just simultaneously importing blocks
from disk.

**Comment by laanwj** [comment]
> So reindex is not counted as "warmup" but should be, instead?

No, I don't think so.
Remember reindex can take a long time on the main chain, we have no reason for RPC to be available in the mean time. The warmup phase exists because it would be **unsafe** to offer RPC functionality (e.g. everything expects pcoinsTip to be populated).

I wouldn't be against adding a `reindex_in_progress` status field to some RPC call though.
