### ISSUE TITLE
Mining doesn't working in my altcoin

### ISSUE THREAD

**Issue by stas730** [bitcoin/bitcoin#7746]
I created an Altcoin. I want to mine 1 or more blocks (I created this coin just for testing). I typing generate 1 in console (GUI). Response:
[
]
Regtest network working normally. How to mine main/testnet coins?
P. S. Genesis block not changed

**Comment by stas730** [comment]
P. P. S. Console (GUI) means console in Qt client. CLI not working (or I incorrectly configured it).

**Comment by MarcoFalke** [comment]
Could you explain which of the consensus/non-consensus code you have changed?

**Comment by stas730** [comment]
Code from this repository.

**Comment by stas730** [comment]
This changes (I am Russian, sorry). I needed to find some files. https://m.habrahabr.ru/post/263367/
I don't have access to the computer now.

**Comment by sipa** [comment]
This is not a helpdesk for making your own altcoin.

Perhaps you want to learn more about how the current code works first, but there are places for that than an issue tracker, like IRC.

**Comment by stas730** [comment]
P. S. I not changed address first symbol and { website }.
