### ISSUE TITLE
Request - Send Raw Transaction Shortcut

### ISSUE THREAD

**Issue by hasanhuseyincakir** [bitcoin/bitcoin#7752]
Hi everyone. 
Is it possible to add an option as "Rebroadcast Transaction" on the right click menu
First of all, yes I know Bitcoin Core rebroadcasts all unconfirmed transactions every 12 minutes. (Time sequence might be different on different clients, on 0.12.0 it's 12 minutes). 
For inexperienced users who doesn't know how to use console commands it can be really hard. 
What's suggested to rebroadcast tx manually? (All you know it but I'll repeat it :) )
Go Transactions tab
Find transaction
Right click 
*Rebroadcast tx* (Rest of it currently needed, This is what I suggest)
Copy tx id
Go Help Menu
Click Console
Type "getrawtransaction txid"
Copy response.
Type "sendrawtransaction pasteResponse"
![sendraw](https://cloud.githubusercontent.com/assets/757853/14065666/aab08c88-f43b-11e5-8590-e53155cf459d.png)

**Comment by sipa** [comment]
I don't think it would be advisable to have this in GUI, as it should not
be needed for normal users, may cause misunderstanding (people may think
they need to use this option to resubmit while it happens automatically),
and may hurt privacy.

**Comment by jonasschnelli** [comment]
I agree with @sipa. The current GUI is already over-complex and such edge-use-cases should be done over the (RPC)Console.

But nothing holds you back from writing this feature (should be relatively simple) and use it in your own/local branch.

**Comment by paveljanik** [comment]
NACK for the reasons already specified above.

**Comment by jonasschnelli** [comment]
Closing because it looks like that this feature will not be accepted.
