### ISSUE TITLE
0.12: Transaction fee slider - User feedback: "normal" fee means confirmation time 4h ? Slider does not default to value of txconfirmtarget ?

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#7754]
Yesterday I did my first transaction with Core 0.12, so I can give You a fresh user feedback:

Being in the transaction window, I entered the address and amount and looked at the fee slider. It was set to "Suggestion: normal" (estimated begin of confirmation in 25 blocks).

I looked at https://bitcoinfees.21.co/ to check the suggestion there.

First, it is not user friendly to compare the values, since on bitcoinfees.21.co the default unit is "Satoshis per Byte" (what the hack, who can deal with this as normal user???) but one can work around with changing the unit to "mBTC per Byte", so one can compare easily with the unit "BTC per kB" in Core GUI, which is the same value.

But then, as if that would not be enough, there is also the unit "Fee per transaction", so one needs the size of the transaction (in kBytes), if one wants to know what she is doing :) Very complicated.
I am missing the information of the estimated size of a new transaction to be made. and also the size value in the transaction history of the wallet GUI.

So, I saw there was big difference in fee suggestion. I did just want to make an easy transfirmation without needing to compute too much, so I trusted the word "normal" on the confirmation time slider, since I was not in a hurry, but did not want to take half an hour longer for hazzeling with fee estimation computing.

Now in the next hour, while the transaction did not confirm, I got more in the details of fees. I saw, that I had the default _txconfirmtarget_ value of 2. So I would suggest to have an additional radio button Saying "Use the estimated needed fee for default target of confirmation in X blocks".

Also, I would suggest to change the labels of the slider from "normal(25)...fast(2)" to "default(2)...slow(25)"
(given _txconfirmtarget_ = 2)

If estimated confirmation starts in 25 blocks, doesn't that mean an estimated waiting time of 250 minutes ~= 4h ? Is that "normal" confirmation time?

While waiting, I tried to watch the transaction on blockchain.info, but pasting the transation-id, it said "Unrecognized search pattern". I learned, one has to remove the trailing "-000" of the transaction id. Same deleting needed on blockexplorer.com.

Transaction confirmed after 17 blocks, as I saw on the next day...

So, my user experience was not very good: The user is left in uncertainty, computing of BTC/Byte/transaction size is too complicated, and the default confirmation time in the slider of 25 blocks seems to be too slow, while the user trusts the label "normal". Why is the default of the slider not the value of _txconfirmtarget_ ?

**Comment by MarcoFalke** [comment]
> Why is the default of the slider not the value of txconfirmtarget ?

This is a know bug (among others) of the tx-GUI

**Comment by laanwj** [comment]
Yes, thanks for the feedback, we're unfortunately already aware of most of these problems.

I agree the user experience for the fee selection is baffling for most people, but it's still an ongoing process to figure out how such an UI should work in the first place.

**Comment by wodry** [comment]
Nice to hear :) Did not find a fitting open issue with the word "fee" before posting this.

**Comment by jonasschnelli** [comment]
Agree that this is not very user friendly.

Maybe a segmented control that allows you to select "Slow (10) | Normal (6) | Fast (2)" would make more sense. Maybe even the confirmation target in brackets could be removed and only visible if one has enabled "CoinControl".

**Comment by MarcoFalke** [comment]
Anything left to do here after #8989 and #9036?
