### ISSUE TITLE
Merkleize the utxo set dump (was: `gettxoutsetinfo` serializedhash doesn't contain the keys?)

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7758]
I've stared at the code of https://github.com/bitcoin/bitcoin/blob/master/src/txdb.cpp#L114 for a while, and can't seem to discover where the key (transaction id for the following outputs) is serialized to the HashWriter. I don't think this is happening at all.

As I see it, but I could be confused, is that this is a problem as it means different transactions in the same position with the same outputs will potentially result in the same hash.

Another slight issue (but more of a naming/documentation one) is that `nSerializedSize` is confusing: it's not the size of the data hashed to `hashSerialized`, but a differently computed quantity.

**Comment by sipa** [comment]
It seems that the old commit of mine (3499ce1e1ad87a86598d00b7124072c91ddad833) broke this in the chainstate obfuscation PR.

Shows how often people actually use that function...

**Comment by laanwj** [comment]
Heh, I only noticed because I actually started using the hashed data in #7759.

**Comment by paveljanik** [comment]
Maybe we can remove it completely? Or every developer keeps the old tree with unobfuscated chain data because of already existing tooling to parse files? ;-)

**Comment by laanwj** [comment]
You're not serious on removing utxo set stats I hope?

**Comment by paveljanik** [comment]
I'd like to found out the reason why none noticed ;-) I actually use it myself...

**Comment by laanwj** [comment]
I do I use the hash sometimes to compare multiple nodes for correctness, especially after experimenting.
Though I must admit running (almost) master everywhere, so I could easily miss this change.

The RPC test isn't helpful for detecting this either :dragon_face:

> assert_equal(len(res[u'hash_serialized']), 64)

**Comment by laanwj** [comment]
Discussed on IRC:
```
<sipa> wumpus: if we need to fix the serialization for gettxoutsetinfo... maybe we can replace it with a merkleized version?
<wumpus> sipa: you mean a 6-month masters project for someone? :) or isn't it that bad to do?
<sipa> wumpus: i don't mean UTXO commitments
<wumpus> ohh!
<wumpus> sure, would be good to have a better format
<wumpus> I'm everything but married to the current one, and apparently we already broke it once without anyone noticing, so (as long as we mention it in the release notes) I'm not against breaking it again
<sipa> but we can iterate over the utxo entries in order like now, but use an incremental merkle tree hasher (similar to the algorithm used by ComputeMerkleRoot and friends now)
<wumpus> cool
<sipa> the overhead would be the same, and you could make it answer queries for specific entries... and it could later just be converted to a commitment structure
<wumpus> yes, after  the memory improvement for the merkle tree hasher it doesn't have to store all the data in meory
```
I think this makes sense, as we'll have to break the compatibility anyway, let's move to a better format.
