### ISSUE TITLE
Version 0.12.0 Repeated crash on OSX El Captain

### ISSUE THREAD

**Issue by MichelChouinard** [bitcoin/bitcoin#7765]
Preceding version did the same thing...  Simply crash after some time...  Updated to 0.12.0 and it became worst...  Took a backup of my wallet file, cleaned bitcoin folders and started all over again...  At some point during synchronisation bitcoin-core looked like working but synchro was stalled.  Had to reboot my mac for a critical update.  Started bitcoin-core app after reboot, synchronisation worked well and finished, received latest transactions in my wallet.  This was Saturday.

Today, crash again doing nothing and won't reload.  It start but crash again on block verification...

First time I think, ok something corrupted the chainstate files somehow but this time I do think that it's caused by the app.

So here's the crash report and debug log
[bitcoin-core_crash-report.txt](https://github.com/bitcoin/bitcoin/files/194005/bitcoin-core_crash-report.txt)
[debug.log.txt](https://github.com/bitcoin/bitcoin/files/194011/debug.log.txt)

**Comment by jonasschnelli** [comment]
I'm constantly running and testing Bitcoin Core on a Mac Mini with the most recent OSX version.

Did you recently did a hardware test (RAM)?
I guess you don't overclock your mac?
What disk are you using? External USB/TB/FW? Internal? Spinning or SSD?
How many RAM do you have in total?
What CPU / Mac modal are you using?

<img width="557" alt="bildschirmfoto 2016-03-29 um 20 09 35" src="https://cloud.githubusercontent.com/assets/178464/14118528/31884728-f5ea-11e5-904b-f6d0bd335539.png">

**Comment by MichelChouinard** [comment]
Did you recently did a hardware test (RAM)? 
- NO ( Never had trouble with anything else on my Mac )
- RAM was tested last year on installation.

I guess you don't overclock your mac? 
- Never!!!!!!!!!  I find that a bad practice!

What disk are you using? External USB/TB/FW? Internal? Spinning or SSD?
- Internal spinning. 2x500Go mounted in raid
![capture d ecran 2016-03-29 a 14 26 16](https://cloud.githubusercontent.com/assets/433727/14119024/3d28283a-f5ba-11e5-88c9-ea102a8234d9.png)

How many RAM do you have in total?
- 16GB

What CPU / Mac modal are you using?
![capture d ecran 2016-03-29 a 14 18 38](https://cloud.githubusercontent.com/assets/433727/14118817/32b87cb6-f5b9-11e5-93b1-3b5664a0d087.png)

**Comment by laanwj** [comment]
@jonasschnelli  any idea how we can get symbols here?
```
11  org.bitcoinfoundation.Bitcoin-Qt	0x00000001076493f0 0x1071aa000 + 4846576
12  org.bitcoinfoundation.Bitcoin-Qt	0x0000000107e1b69d 0x1071aa000 + 13047453
13  org.bitcoinfoundation.Bitcoin-Qt	0x0000000107e1e455 0x1071aa000 + 13059157
14  org.bitcoinfoundation.Bitcoin-Qt	0x00000001071bf50c 0x1071aa000 + 87308
15  org.bitcoinfoundation.Bitcoin-Qt	0x00000001071bc874 0x1071aa000 + 75892
```
With linux and windows build I can do a gitian build injecting `-g` into the C[XX]FLAGS, then use addr2line and such to convert the (relative) addresses to functions manually.
But I have no clue how to do a similar thing for MacOSX.

**Comment by fanquake** [comment]
@MichelChouinard Does the issue still happen with 0.13.0 ?

**Comment by fanquake** [comment]
Closing for now, hard to debug without any more information. Can re-open if we see it happening again.

**Comment by MichelChouinard** [comment]
Hi,

Everything is working fine and the update when well.

Sorry for the late reply.  

Michel Chouinard
michel.chouinard@gmail.com

1068 AV FOURNIER
QUÉBEC  QC  G1V 3M2
CANADA

+1 418-651-4484 Maison
+1 418-255-9364 Cellulaire
