### ISSUE TITLE
Expose information on whether transaction relayed is enabled in getnetworkinfo

### ISSUE THREAD

**Issue by chris-belcher** [bitcoin/bitcoin#7771]
For software that interfaces with Bitcoin Core via RPC, it can be useful to know whether the fRelayTxes flag is set. It could be added to `getnetworkinfo`.

**Comment by laanwj** [comment]
I think the name 'localrelay' next to 'localservices' (the service bits) would make sense as name, so we include all information sent to other peers in version messages.

**Comment by dragongem45** [comment]
i have made a patch/pull req at https://github.com/bitcoin/bitcoin/pull/7839/files
