### ISSUE TITLE
Wallet problem when TX has three receive addresses

### ISSUE THREAD

**Issue by trevelocity** [bitcoin/bitcoin#7777]
This is with Bitcoind 0.11.2 on Linux x86_64.
I used the Receive tab in bicoin-qt to generate three addresses.
I then created a raw transaction sending bitcoins to those three addresses.
>> bitcoin-cli  getrawtransaction 796ce009e1f146d3cc296adf94a69c19faf415adb73b0ffdd78acb74418e48d1 1
....
"vout" : [
        {
            "value" : 0.00110000,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 39b932cd29f9f1ad6f9fafe30fc332f603c86713 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a91439b932cd29f9f1ad6f9fafe30fc332f603c8671388ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "16GDNkNR4kG9VqcwWYWfZEtSBQ4PhNBq5r"
                ]
            }
        },
        {
            "value" : 0.00120000,
            "n" : 1,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 66e4f7fb49135e280cb9e3985b055f644baaafe4 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a91466e4f7fb49135e280cb9e3985b055f644baaafe488ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1AP4DbBbuLjuSMku8RG6P4cu7q9sHzSjmB"
                ]
            }
        },
        {
            "value" : 0.00130000,
            "n" : 2,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 9a83cc700afd2237e50eff4f3647301cc48b4c86 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a9149a83cc700afd2237e50eff4f3647301cc48b4c8688ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1F5zx4x3htK36uvXqHscmY9u91nGy6qNYe"
                ]
            }
        },
....
When I check the wallet to see if the bitcoins have been received I get this:
bitcoin-cli  getreceivedbyaddress 16GDNkNR4kG9VqcwWYWfZEtSBQ4PhNBq5r
0.00000000
bitcoin-cli  getreceivedbyaddress 1AP4DbBbuLjuSMku8RG6P4cu7q9sHzSjmB
0.00120000
bitcoin-cli  getreceivedbyaddress 1F5zx4x3htK36uvXqHscmY9u91nGy6qNYe
0.00130000

The first issue is that vout0 is not reported as being received (i.e. the 0.0011 is not shown).
The second issue is that in the bitcoin-qt Transaction tab, it shows vout1 and vout2, but in
"Show transaction details" for vout1 and vout2 it shows, in both cases, "Net amount: +0.00250000 BTC". The total for the TX is 0.0036, but it would be better if it displayed the total for the "address" rather than the TX in the pop-up window.

**Comment by trevelocity** [comment]
Apologies for wasting your time if you read this. There is a bug in the
script that built the raw transaction; it put a wrong hash160 into vout0.
Looks like the 0.0011 is lost.

**Comment by sipa** [comment]
Good that it is solved :)
