### ISSUE TITLE
configure: error: libprotobuf not found. and can not use apt-get to install libprotobuf-dev on Mac os 10.11.1

### ISSUE THREAD

**Issue by mizhang** [bitcoin/bitcoin#7782]
Error is

configure: error: libprotobuf not found.

I am using Mac os 10.11.1.

Tried to download apt-get through port

sudo port dpkg; sudo port apt;

apt-get install libprotobuf-dev, get following error:

Reading Package Lists... Done
Building Dependency Tree... Done
W: Couldn't stat source package list http://www.example.com stable/main Packages (/opt/local/var/db/apt/state/lists/www.example.com_packages_dists_stable_main_binary-darwin-i386_Packages) - stat (2 No such file or directory)
W: Couldn't stat source package list http://www.example.com stable/contrib Packages (/opt/local/var/db/apt/state/lists/www.example.com_packages_dists_stable_contrib_binary-darwin-i386_Packages) - stat (2 No such file or directory)
W: Couldn't stat source package list http://www.example.com stable/non-free Packages (/opt/local/var/db/apt/state/lists/www.example.com_packages_dists_stable_non-free_binary-darwin-i386_Packages) - stat (2 No such file or directory)
W: You may want to run apt-get update to correct these problems
E: Couldn't find package libprotobuf-dev

**Comment by paveljanik** [comment]
Use `port install protobuf-cpp`

**Comment by mizhang** [comment]
It works thanks.

**Comment by paveljanik** [comment]
Please read the the OS X build guide (https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md). This time `port install libevent` should fix your problem.

**Comment by paveljanik** [comment]
BTW - what do you use `port`, `brew` or both? ;-)

**Comment by mizhang** [comment]
@paveljanik    your suggestion works like a charm.   Brew uninstall libevent; sudo port install libevent, then problem fixed.   thanks a lot

I am using both port or brew.  Some of the packages seems to only in one of those.
