### ISSUE TITLE
No GUI notification when needing to rescan wallet

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#7790]
Currently it seems that Bitcoin-Qt gives no indication to the user that it is rescanning a wallet, other than to output to debug.log. If the node needs to catch up with the blockchain, it displays the GUI and lets the user know that it is syncing - why doesn't this same functionality exist for when it needs to rescan the wallet?

**Comment by jonasschnelli** [comment]
Where do you test this? Mainnet or Regtest?
IIRC, there is a rescan dialog in the GUI when you – as an example – import an address or pubkey.

**Comment by MarcoFalke** [comment]
Can you provide exact steps to reproduce, please?

Works locally:

![screenshot from 2016-04-03 10-44-22](https://cloud.githubusercontent.com/assets/6399679/14231581/40f5e902-f989-11e5-87a8-8369ebbcef7c.png)

![screenshot from 2016-04-03 10-47-11](https://cloud.githubusercontent.com/assets/6399679/14231584/75c3bd6c-f989-11e5-815a-4279b969a040.png)

**Comment by laanwj** [comment]
I'm sure rescan progress in the GUI was added in #3928, two years ago - and after that, various improvements have been made.

**Comment by rebroad** [comment]
@laanwj Using Version v0.12, I was not getting this rescan dialog. Perhaps an issue with Gnome?

**Comment by kirkalx** [comment]
What about the status message at the bottom of the splashscreen?

**Comment by MarcoFalke** [comment]
Jup, the rescan dialog I posted above was a child of the debug window, not a child of the splashscreen. (The splash screen already shows it in the status message)

@rebroad If you don't provide exact steps to reproduce and preferably screenshots, there is nothing we could do, as it is not reproducible.
