### ISSUE TITLE
2 repositories, one can compile, the other can not

### ISSUE THREAD

**Issue by mizhang** [bitcoin/bitcoin#7808]
I downloaded 2 repositories, bitcoin/bitcoin and sipa/bitcoin.  

I can compile fine with bitcoin/bitcoin, but not sipa/bitcoin/

Here is the steps:
./autogen.sh
./configure

Here is the error message got form sipa/bitcoin:
checking if qt should be enabled... configure: error: "qt support requested but qt could not be located. use --without-qt"

I am using online free licensed QT Creator.  After I saw the error, I deleted QT Creator and reinstalled it.  

I am using Mac OS 10.11.1.

any suggestion/comment is appreciated.  thanks.

**Comment by jonasschnelli** [comment]
Why do you want to compile `sipa/bitcoin`(it's full of bugs anyways. :P)?
If you checkout sipas bitcoin repository, checkout an active branch (maybe `segwit4`).
His master branch is not really in-sync (`This branch is 114 commits ahead, 619 commits behind bitcoin:master.`)

**Comment by mizhang** [comment]
Yes,  switched to segwit4.   There is no problem compiling then.  

I am trying to read code change for segwit4.  Thanks a lot for your help.

**Comment by MarcoFalke** [comment]
@mizhang Good to hear. You may want to close the issue, if there are no further problems.

Just a note: You can run `git branch -v` to see which commit git has checked out for you.

**Comment by mizhang** [comment]
Thanks a lot.  Closing the issue now
