### ISSUE TITLE
Open OS X app bundle with parameters

### ISSUE THREAD

**Issue by alexreg** [bitcoin/bitcoin#7836]
The build for Mac OS X of course produces an app bundle (`Bitcoin Qt.app`). However, I was wondering if there is a way to pass parameters to this app by default when it launches, rather than just manually on the command line. I looked at the `configure` script, but I don't think it has the capabilities for this.

**Comment by paveljanik** [comment]
Yes, use its config file - see https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md#running

Please close this issue.

**Comment by alexreg** [comment]
What if the config file is in a non-standard location?

**Comment by theuni** [comment]
What params do you want to pass? If you're looking in configure, I assume you want to hard-code something for all runs?

**Comment by alexreg** [comment]
Yeah. -conf, -datadir, and -pid are teh params I want to “hard-code” for the app bundle.

**Comment by theuni** [comment]
Hmm, that's a pretty scary idea. I'd rather not make it easier for some altcoin to clobber our data. What's the rationale behind changing those?

**Comment by alexreg** [comment]
Because I’m getting MacPorts to install Bitcoine core and the daemon to /opt/local, and a launchd plist to /Library/LaunchDaemons. The data dir / log file / pid file will be under standard Unix directories in /opt/local (the MacPorts prefix). I want the GUI to recognise this, and thus get the correct config to connect to the daemon… unless the GUI is meant to have different data dir / log file / pid paths from the daemon?

**Comment by jonasschnelli** [comment]
Hardcode parameters is not something we want in master. It could make sense that you patch bitcoin-core/-qt if you plan to deploy it over a package manager like MacPorts. Maybe you can patch the Info.plist and pass some argument without actually modifying the bitcoin-qt binary.

Closing.

**Comment by alexreg** [comment]
Yeah, that’s my solution in the end. Thanks.
