### ISSUE TITLE
`getpeerinfo` should report minping differently if there never was a ping

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7837]
See discussion in #6636.
Currently, an implementation detail leaks here:

>  "minping": 9223372036854.775,

This is `std::numeric_limits<int64_t>::max()` milliseconds, or approximately 300,000 years. What we really want to communicate here is that the information is missing. So it would be better to report it as `null`.

>  "minping": null,

**Comment by paveljanik** [comment]
Thinking about this a bit, we have a precedent already for not producing some entity based on its value. `pingwait` is documented:
```
    "pingwait": n,             (numeric) ping wait
```

and is not present in the output sometimes based on its value:

```c
        if (stats.dPingWait > 0.0)
            obj.push_back(Pair("pingwait", stats.dPingWait));
```

So far we have not received comments about this property missing from output...

So what about doing the same with `minping`? ;-)

**Comment by laanwj** [comment]
I didn't really want to start a discussion here.
I'm happy as long as you document it.
