### ISSUE TITLE
Force user to wait before clicking OK to send coins

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#785]
As a part of #593 Gmaxwell suggested that the send coins confirmation dialog delay several seconds before it allows the user to click OK, similar to the way firefox does plugin installation.  Though I found it to fall outside the scope of #593, it is still a good suggestion that should be implemented if someone has the free time and motivation.

**Comment by MarcoFalke** [comment]
Fixed by  @Tyler-Hardin in #8012.
