### ISSUE TITLE
Improving key.py in qa/rpc-tests/test_framework

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#7859]
Our test framework's EC key wrapper (`qa/rpc-tests/test_framwork/key.py`) doesn't support a way to enforce low-S use in signatures.  This is an annoyance when writing tests for mempool acceptance, as our standardness rules now enforce low-S.

If someone wants to improve this, it would be nice to add an interface that would allow us to explicitly choose a low-S or high-S signature (either when signing, or as a separate function that would do the conversion).

**Comment by jonasschnelli** [comment]
It's implemented upstream: https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/core/key.py#L272

Somebody needs to update the test framework.

**Comment by sdaftuar** [comment]
@jonasschnelli: I believe that if we want to use that code, we'd need the author to submit it here, as python-bitcoinlib is now LGPL, which isn't compatible with this project (sigh).

**Comment by laanwj** [comment]
Yes, we can't do that unless we want to depend on an external library for the test framework.

**Comment by MarcoFalke** [comment]
@rnicoll are you interested in submitting [this pull](https://github.com/petertodd/python-bitcoinlib/pull/53) here as well?

**Comment by btcdrak** [comment]
@sdaftuar How is LGPLv3 not compatible with MIT exactly?

**Comment by wumpus** [comment]
wrong @wumpus

**Comment by luke-jr** [comment]
@btcdrak That's not true. Your code can remain MIT-licensed and use GPL code, so long as it's distributed under the terms of the GPL. This still allows others to rip out the GPL dependency and use your code without following the GPL terms. We don't want to have this kind of thing in the repository, but it's not a legal problem.

**Comment by sipa** [comment]
#8499 also has a commit that adds support for lowS signatures.

**Comment by MarcoFalke** [comment]
Ok, closing for now, as this is part of #8499.
