### ISSUE TITLE
Bitcoin Core Wallet window is not shown

### ISSUE THREAD

**Issue by jabware** [bitcoin/bitcoin#7869]
Installed new 0.12.0. 
Re-indexed with  server=1 and txindex=1 options.
All works fine but after windows(Server 2012 R2) rebooting wallet windows is not show.
When I start BitcoinCore I see

![bitcore](https://cloud.githubusercontent.com/assets/5579219/14485284/c762a674-015e-11e6-94a5-5706124a839b.png) 
and after it verified wallet not shown.

![botcoin2](https://cloud.githubusercontent.com/assets/5579219/14485358/33a8270a-015f-11e6-8117-8b9c44810484.png)

Window is minimized and blank but not possible to open it.
Options from bottom right tray does not work also.

I've re-install everything.
Changed data folder destination.
Installed 0.11.* version.
All time result is the same - wallet windows is empty and minimized.
But it still is synchronizing and can be queried.

Do someone have any idea how to make it working properly?

**Comment by jonasschnelli** [comment]
Can you start Bitcoin-Qt.exe with `--resetguisettings`?
1. Start "cmd.exe"
2. cd to your bitcoin-qt.exe install directory
3. Enter `bitcoin-qt.exe --resetguisettings`

**Comment by jabware** [comment]
WORKS!
Thank you!

**Comment by mhamaddaher** [comment]
im having the same problem on ubuntu 17.04 . how to fix it ? please

**Comment by MarcoFalke** [comment]
@mhamaddaher You might want to try running with `bitcoin-qt -resetguisettings`. Alternatively, updating to 0.15.0.2 might fix it. (Will be released in about a week or so)
