### ISSUE TITLE
Reindex is slow due to signature checks.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#7875]
Headers aren't read first during reindex (as that would require multiple passes over the data). As a result the script bypass at
        if (pindexLastCheckpoint && pindexLastCheckpoint->GetAncestor(pindex->nHeight) == pindex) {

Doesn't work correctly. With libsecp256k1 this doesn't matter _that_ much, though it does make reindex noticeably slower than initial sync if your network is fast.

**Comment by sipa** [comment]
Should be fixed by #7917.
