### ISSUE TITLE
can't 'signmessage' without wallet support compiled in

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#7895]
I would like to be able to sign messages using 'signmessage' by providing the private key to the RPC, just like I can 'signrawtransaction'.

If I move 'signmessage' into the 'util' category alongside 'verifymessage' and allow it to take an optional private key parameter would my change stand a chance of being merged?

Currently 'signmessage' isn't even available when I don't build with wallet support since it is considered a wallet function.

**Comment by achow101** [comment]
Go ahead and try, it doesn't hurt to try.

**Comment by btcdrak** [comment]
Seems like a reasonable ask to me. Concept ACK.

**Comment by dooglus** [comment]
#7898 adds the optional parameter to signmessage but leaves signmessage in the wallet category.

**Comment by luke-jr** [comment]
I don't see why a server is needed for this. Should just be a library function.

**Comment by laanwj** [comment]
#7953 Create signmessagewithprivkey rpc
