### ISSUE TITLE
WARNING: generated for both stdio.h and select.h

### ISSUE THREAD

**Issue by blue-onyx** [bitcoin/bitcoin#7902]
Please forgive me if I'm not reporting this correctly -- I'm following directions generated by "./configure" and I've never reported an issue to github before...

Software:
   Mac OS X Version 10.6.8 Snow Leopard
Hardware:
   2.66GHz Intel Core i7
   4GB 1067 MHz DDR3

I attempted to install the binary of Bitcoin Core 0.12.1 but it failed and said I'd need to update my OS before I could install the binary.  I am currently limited to Snow Leopard due to requirements for other projects, etc.  Therefore, I decided to try my hand at building from source.

When I run "./configure", I receive the following errors:

```
configure: WARNING:  stdio.h: present but cannot be compiled
configure: WARNING:  stdio.h:     check for missing prerequisite headers?
configure: WARNING:  stdio.h: see the Autoconf documentation
configure: WARNING:  stdio.h:     section "Present But Cannot Be Compiled"
configure: WARNING:  stdio.h: proceeding with the compiler's result
configure: WARNING:      ## -------------------------------------------------------- ##
configure: WARNING:      ## Report this to https://github.com/bitcoin/bitcoin/issues ##
configure: WARNING:      ## -------------------------------------------------------- ##

configure: WARNING:  sys/select.h: present but cannot be compiled
configure: WARNING:  sys/select.h:     check for missing prerequisite headers?
configure: WARNING:  sys/select.h: see the Autoconf documentation
configure: WARNING:  sys/select.h:     section "Present But Cannot Be Compiled"
configure: WARNING:  sys/select.h: proceeding with the compiler's result
configure: WARNING:      ## -------------------------------------------------------- ##
configure: WARNING:      ## Report this to https://github.com/bitcoin/bitcoin/issues ##
configure: WARNING:      ## -------------------------------------------------------- ##
```
Thanks to all of you for the amazing work you do for the community, I don't know if there is a way for an official binary to still be available for Snow Leopard, but that too, would be greatly appreciated  =)  Or if someone wants to help me learn how to create the binary installer for Snow Leopard, perhaps I could contribute that back?  It is only difficult the first time, right?

If there is anything more you need from me, I'd be happy to help.  Please understand that you may have to help me help you because building from source is something that I have knowledge of, but not much understanding of.  I'm reasonably comfortable with the CLI, I just don't know if I can answer some questions you may have.

Warm regards,
blue-onyx

**Comment by kirkalx** [comment]
Can't be more help yet sorry, but this is the autconf documentation it is referring to (for latest version of autoconf):
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Present-But-Cannot-Be-Compiled.html#Present-But-Cannot-Be-Compiled

**Comment by jonasschnelli** [comment]
Active support for compiling < OSX10.7 has been dropped, though, it should work.
Can you double-check that your Xcode installation (including command line tools) is correct?
Can you check what you get when typing `xcode-select -p`?

**Comment by laanwj** [comment]
OSX has huge, incompatible changes between versions, which makes it a large burden to support older versions and still do e.g. code signing correctly - and our experience is that, due to the fast churn, (almost) no one cares about support for old versions of MacOSX.

Building it from source should work though. The error about `stdio.h` looks like a base issue with your build environment and not something related to bitcoin itself. Can you compile other c/c++ code?

**Comment by paveljanik** [comment]
Please paste `config.log` file somewhere.

**Comment by blue-onyx** [comment]
jonasschnelli,
     When typing `xcode-select -p`, I receive the following output:

```
<user>$ xcode-select -p
Usage: xcode-select -print-path
   or: xcode-select -switch <xcode_folder_path>
   or: xcode-select -version
Arguments:
   -print-path                     Prints the path of the current Xcode folder
   -switch <xcode_folder_path>     Sets the path for the current Xcode folder
   -version                        Prints xcode-select version information
```

I wasn't sure what you were looking for, so I include the following in anticipation of your needs, `xcode-select -version`:

`xcode-select -version 895.`

-----
laanwj,
     Thank you for the background.  I do understand how this could be a challenge for the team, and I certainly am not trying to create work.  Unfortunately, at this time, I am pretty locked into Snow Leopard.  I hope to be able to move forward (perhaps through the use of virtual machines?) at some point during the next 12 months, but I would need a working installation of Bitcoin Core long before then.  For me, it isn't a matter of just dragging my feet or not wanting to upgrade, I'd prefer to be on El Cap, if for no other reason than security patches.  I just have to be patient for the time being.
     You asked if I can "compile other c/c++ code?", to which I say, "I'm not sure".  I haven't had need to do so recently.  Does anyone have a recommendation as to a simple build I could try to test this?  My only requirements are...

1. Needs to be a trusted code base -- I can not afford to add any security vulnerabilities, and
2. Needs to be easy to build...  I'm not afraid of the CLI, but I don't live there.  I can follow a well written "how to" but following instructions and understanding what one is doing are two completely different things.

Thank you, Mr. van der Laan

-----
paveljanik,

Hopefully the below file is what you are looking for...

[config.log.txt](https://github.com/bitcoin/bitcoin/files/224390/config.log.txt)

-----

I appreciate the work that you all do for the community.  As before, please let me know if there is more that I can do to help...
Regards

**Comment by paveljanik** [comment]
The crucial thing is:
```
cc1plus: error: unrecognized command line option "-Wno-self-assign"
```

**Comment by blue-onyx** [comment]
paveljanik,

Thanks, I think we are making progress...

Running `./autogen.sh` after the edit of `configure.ac` threw the following warning:

```
configure.ac:25: warning: The macro `AC_FOREACH' is obsolete.
configure.ac:25: You should run autoupdate.
```

I then ran `autoupdate configure.ac` and then `./autogen.sh` again.

The autogen.sh warning is still there.  HOWEVER, now when I run `./configure`, the initial issue I posted is not displayed.

The last line output after running `./configure` now says:

`configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`

For this installation, I will need wallet functionality.

Question...  What does the `"-Wno-self-assign"` flag do?

Continued thanks...
Regards

**Comment by paveljanik** [comment]
OK, you can start to follow the instructions at https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md

**Comment by blue-onyx** [comment]
This has kind of migrated from filing a bug report as prompted by the software, to personal help, for which I'm sorry.  However, I'm not figuring this out...

The latest (as I follow the `build-osx.md` instructions above) is that I get the following error:

`configure: error: pkg-config not found.`

Yet, when I try a `which pkg-config` I receive the following:

```
<user>$ which pkg-config
/usr/local/bin/pkg-config
```

And FYI...

```
<user>$ pkg-config --version
0.29.1
```
I don't remember now where I stumbled upon the following information:

`Please set GLIB_CFLAGS and GLIB_LIBS to the correct values`

Referring to `./configure -h` as well as the internet at large, I can't seem to figure out the format to pass these values.  Is that even the problem I need solved???

Again, I seem to be stumped...  Thanks folks,
Regards

**Comment by paveljanik** [comment]
You should try `configure` from the new shell already containing `/usr/local/bin` in your PATH. It should work.

E.g. `configure --enable-wallet`.

**Comment by laanwj** [comment]
> cc1plus: error: unrecognized command line option "-Wno-self-assign"

Why is that an error? Normally unrecognized -W command line options should raise a warning.

**Comment by paveljanik** [comment]
This is probably because of the old system he is running. gcc is used there, not clang.

**Comment by paveljanik** [comment]
```
$ g++ -c q.c -Wno-self-assign
cc1plus: error: unrecognized command line option "-Wno-self-assign"
$
```

**Comment by laanwj** [comment]
Should be the same for gcc though...

**Comment by blue-onyx** [comment]
paveljanik wrote:

> 
> You should try configure from the new shell already containing /usr/local/bin in your PATH. It should work.
> 
> E.g. configure --enable-wallet.

```
<user>$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin

<user>$ which pkg-config
/usr/local/bin/pkg-config
```

Then, when I run `./configure --enable-wallet` it throws:

`configure: error: pkg-config not found.`

**Comment by paveljanik** [comment]
Can you run `pkg-config`? What do you have in `config.log` now?

**Comment by blue-onyx** [comment]
```
<user>$ pkg-config
Must specify package names on the command line
```

[config.log.txt](https://github.com/bitcoin/bitcoin/files/226469/config.log.txt)

**Comment by paveljanik** [comment]
```
configure:17146: checking for pkg-config
configure:17179: result: no
configure:18412: checking for port
configure:18442: result: no
configure:18458: checking for brew
configure:18488: result: no
```

Do you use `port` or `brew`? Please fix this first...

**Comment by paveljanik** [comment]
It is quite difficult to debug such old system for us... Isn't it time to update your system? ;-) Using Bitcoin Core on such system is not recommended because there are no updates from Apple.

**Comment by blue-onyx** [comment]
```
<user>$ which brew
/usr/local/bin/brew
```
This doesn't make any sense to me...  It is present but the system doesn't think it is there.  Though I apparently don't have port installed (at least for this user).

**Comment by blue-onyx** [comment]
Perhaps I'm going about this all wrong...

- If I run an older version of Bitcoin Core, are there security risks?
- Are there trustworthy BTC apps for the iOS platform?
- If I run one on iOS will it consume gigabytes of storage in order to maintain a copy of the blockchain?
- Does Apple accept BTC for me to buy a "new" system which will run current software?  =-$

**Comment by achow101** [comment]
> If I run an older version (say 0.11.2) of Bitcoin Core, are there security risks?

Probably not, but you should check the release notes of releases since that one to see if any critical vulnerabilities have been patched. Sometimes security vulnerabilities are found and are fixed in later versions

> Are there trustworthy BTC apps for the iOS platform?

Yes, but Bitcoin Core does not run on iOS.

> If I run one on iOS will it consume gigabytes of storage in order to maintain a copy of the blockchain?

It depends on the software. Most mobile software will be either an SPV wallet or web wallet so it won't download the entire blockchain.

> Does Apple accept BTC for me to buy a "new" system which will run current software? =-$

No. Apple does not accept Bitcoin

**Comment by laanwj** [comment]
@blue-onyx 

> Does Apple accept BTC for me to buy a "new" system which will run current software? =-$

Hah you should balance your (and other's) time spent getting this to work with the price of just buying new hardware - although it may be a learning experience, I think it's pretty easy to come out in favor of just giving this up.

**Comment by paveljanik** [comment]
@blue-onyx Please close this issue, we can't help you unfortunately.
