### ISSUE TITLE
how to create a fork of Bitcoin

### ISSUE THREAD

**Issue by twepl** [bitcoin/bitcoin#7908]
fork of bitcoin without changing anything
you may want to do it all in one file in source code

**Comment by twepl** [comment]
I suggest to make something similar to the config in the CMS

**Comment by MarcoFalke** [comment]
I may not understand your issue but you can create a fork without changing anything by clicking on the button "fork" https://help.github.com/articles/fork-a-repo/

**Comment by twepl** [comment]
I mean create a new crypto currency based on bitcoin, you may want to optimize it

**Comment by twepl** [comment]
For example.
If a person wants to create a new crypto currency, then he won't need to dig into the code it will go to config will introduce changes and compile.
Convenient and easy.

**Comment by sipa** [comment]
I don't think you should be creating a cryptocurrency without understanding how it works.

**Comment by twepl** [comment]
@sipa not I create a people will create

**Comment by twepl** [comment]
or you do not care?

**Comment by laanwj** [comment]
This is a tracker for issues in the Bitcoin Core code base.
This is not a questions and answers forum for cryptocurrency development.
Please go somewhere else.

**Comment by twepl** [comment]
@laanwj OK
