### ISSUE TITLE
invalid hostname in onion/proxy

### ISSUE THREAD

**Issue by chpio** [bitcoin/bitcoin#7909]
> Error: Invalid -onion address: 'tor:9050'

tried with `dns` `1`and `0`

**Comment by MarcoFalke** [comment]
`tor` is not an ip address. You may have a look at https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md to see some sample command lines and adjust yours accordingly.

**Comment by chpio** [comment]
im using docker, so there is no "ip address" of the bitcoind container

**Comment by laanwj** [comment]
proxy does not do a DNS lookup, you'll have to specify the IP. This is to avoid DNS leaks.
