### ISSUE TITLE
Better comments to describe walletdb.cpp & wallet.cpp

### ISSUE THREAD

**Issue by theochino** [bitcoin/bitcoin#7929]
Can we clearly add to the Wallet module that it is used for Testing and it is not part of Bitcoin core functionality? Like at line 28 in "walletdb.cpp"

The reason is in point 14 of [Dean Affirmation 4 22 16.pdf](https://github.com/bitcoin/bitcoin/files/233118/Dean.Affirmation.4.22.16.pdf) and page 6 of [Memornadum of Law in Support of the Cross-motion to dismiss 4 22 16.pdf](https://github.com/bitcoin/bitcoin/files/233119/Memornadum.of.Law.in.Support.of.the.Cross-motion.to.dismiss.4.22.16.pdf)

The rest of the documentation is here:
https://www.dropbox.com/sh/p6dbxos5y7iwxag/AADNEd6m0S3wMgNHrPqmaoxma

**Comment by btcdrak** [comment]
@theochino So you have a specific wording in mind?

**Comment by kirkalx** [comment]
I'm not sure what point you are trying to make here, but please make it somewhere more appropriate e.g. Reddit?

**Comment by laanwj** [comment]
Feel free to add better comments - no need to have a issue open for it.

Not clicking any of your weird PDF links, and going to edit them out for security/spambait fighting reasons.
