### ISSUE TITLE
Remaining minor issues for out-of-tree build

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7937]
Copied from #7911.
There are a few other fixes needed for out-of-tree builds.

- [ ] RCC is particularly unhappy with separate paths, so we have a hackish copy in there right now. I'm sure there's a better way.
- [ ] We do some leveldb copying at the top-level make that should no longer be necessary.
- [ ] Travis and Gitian descriptors should be switched to out-of-tree rather than copying to subtree as they are now

**Comment by laanwj** [comment]
I noticed another small thing: running `make check` leaves a `src/test/__pycache__/bctest.cpython-34.pyc` in the source directory instead of the build directory. Not sure whether this is really a problem, but thought to mention it.

**Comment by theuni** [comment]
@laanwj yes, ```make distcheck``` yells about that as well. We'll probably want to move that to the build dir for the sake of purity, or just disable the pycache for tests.

**Comment by laanwj** [comment]
This was done in #8133.
