### ISSUE TITLE
No ZMQ on windows

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#7943]
I'm trying to use ZMQ notifications on windows but they don't seem to work. Even with using the zmq_sub.py script, it still doesn't work. I noticed that the help message doesn't contain the zmq stuff. Is this intentional?

**Comment by jonasschnelli** [comment]
ZMQ is not available on Windows if you are using the "official" Bitcoin-Core binaries. If you wish to use it there, you need to compile Bitcoin-Core yourself.

**Comment by achow101** [comment]
Ok.

Why isn't ZMQ available in the official binaries then?

**Comment by jonasschnelli** [comment]
Our official binaries are completely static linked. IIRC, it would require some work to allow cross compile of libzmq with MinGW. But maybe @theuni can clarify that...

**Comment by laanwj** [comment]
See this pull request: WIP: force zeromq to work with static linking+mingw #6819

Feel free to pick it up.

**Comment by laanwj** [comment]
Another related issue: ZMQ fails to static link on Windows #6681

**Comment by theuni** [comment]
Looks like zmq has been fixed upstream since then: https://github.com/zeromq/libzmq/pull/1615, but it hasn't made it into a release yet. It's unclear if that change is dependent on some prior fixes, or if it just always worked. I suppose we can backport the patch and test.

**Comment by fanquake** [comment]
Should have been fixed in #8238
