### ISSUE TITLE
-Qunused-arguments lost for libbitcoinconsensus

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#7961]
OS X:

```
g++ -dynamiclib  -o .libs/libbitcoinconsensus.0.dylib  crypto/.libs/libbitcoinconsensus_la-hmac_sha256.o crypto/.libs/libbitcoinconsensus_la-hmac_sha512.o crypto/.libs/libbitcoinconsensus_la-ripemd160.o crypto/.libs/libbitcoinconsensus_la-sha1.o crypto/.libs/libbitcoinconsensus_la-sha256.o crypto/.libs/libbitcoinconsensus_la-sha512.o .libs/libbitcoinconsensus_la-arith_uint256.o consensus/.libs/libbitcoinconsensus_la-merkle.o .libs/libbitcoinconsensus_la-hash.o primitives/.libs/libbitcoinconsensus_la-block.o primitives/.libs/libbitcoinconsensus_la-transaction.o .libs/libbitcoinconsensus_la-pubkey.o script/.libs/libbitcoinconsensus_la-bitcoinconsensus.o script/.libs/libbitcoinconsensus_la-interpreter.o script/.libs/libbitcoinconsensus_la-script.o script/.libs/libbitcoinconsensus_la-script_error.o .libs/libbitcoinconsensus_la-uint256.o .libs/libbitcoinconsensus_la-utilstrencodings.o   secp256k1/.libs/libsecp256k1.a -L/opt/local/lib -L/opt/local/lib/db48  -fstack-protector-all -g -O2 -pthread -Wl,-headerpad_max_install_names -Wl,-dead_strip   -pthread -install_name  /usr/local/lib/libbitcoinconsensus.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
```

`-Qunused-arguments` got lost for `libbitcoinconsensus` somehow... Adding it to this cmdline silenced the warning again. Other link phases are OK and this is the only one emitting this warning.

configure output contains:

```
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... -Qunused-arguments
```

@theuni Any idea why it is missing?

**Comment by theuni** [comment]
@paveljanik the CPPFLAGS aren't applied on the link-line, so this makes sense.

The issue here is actually that it's trying to use -pthread for libbitcoinconsensus, so the warning is actually legitimate. I think there's a new upstream macro that probably fixes that, I'll give that a shot.

**Comment by fanquake** [comment]
I've tried with dropping in the latest ax_pthread serial (23, we currently use 22), and the output still seems to be the same.

Relevant discussion https://savannah.gnu.org/patch/?8186

**Comment by MarcoFalke** [comment]
Is this still an issue?

**Comment by fanquake** [comment]
Just did:
```
./autogen.sh
./configure
make check -j5
```
with macOS 10.13.6 at (4a3e8c5.
Didn't see any unused argument warnings.
Upstream pthread is also serial 24, which is just doc changes from our 23.
I think we can close this for now.
