### ISSUE TITLE
AcceptToMemoryPool errors are too alarming

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#7969]
A lot of times when I am helping people with Bitcoin Core, they will report that the debug.log is full of

    ERROR: AcceptToMemoryPool :

type errors. The caps ERROR makes this seem extremely alarming when it isn't important at all. Can this error be made to look less alarming, perhaps lowercase or maybe a warning?

I would try to fix this myself, but I don't know where such changes should be made.

**Comment by gmaxwell** [comment]
You're running an old version, it no longer does this.

**Comment by achow101** [comment]
Oh. oops. When was this fixed?

**Comment by laanwj** [comment]
0.12
