### ISSUE TITLE
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality...

### ISSUE THREAD

**Issue by redfly001** [bitcoin/bitcoin#7970]
I download the Bitcoin code and compile at windows.
win7 64bit, using the msys and mingW compile the Bitcoin code.
c:/MinGW32
c:/Mingw
The msys is in Mingw.
Bitcoin code is at h:/vm/bitcoin.sys.
Before this, I compiled db-4.8.30.NC(at h:/vm/libs) already, in msys comand line window:

`cd db-4.8.30.NC/build_unix
../dist/configure --enable-mingw --enable-cxx --disable-shared --disable-replication
make
`
then I find the db_cxx.h from build_unix folder.

Compile Bitcoin in the msys command line window：

`cd h:
cd vm/bitcoin.sys
./autogen.sh CPPFLAGS="-I/c/deps/boost_1_55_0 \
-I/h/vm/db-4.8.30.NC/build_unix \
... (autogen other's parameters)
./configure ...(confiture parameters)
`

about 20minutes later, the error appeared:
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality(--disable-wallet to disable wallet functionality)

I try these ways: [https://github.com/bitcoin/bitcoin/issues/2998](url)
and [https://bitcointalk.org/index.php?topic=588032](url)
The error still over there.
Note: in msys, there is no apt-get command, so I cannot do "apt-get install libdb++-dev".

I found the followings in the config.log file:

> 
PATH: .
PATH: /usr/local/bin
PATH: /mingw/bin
PATH: /bin
PATH: /c/MinGW32/bin
...
> 

So, I copy the db_cxx.h and related .h file to:
c:/mingw/msys/1.0/include/
c:/mingw/msys/1.0/local/include/
c:/mingw/msys/1.0/db48/
c:/mingw/bin/db48/
c:/mingw32/bin/db48/
h:/vm/bitcoin.sys/src/

There is no effect.
I change bdbdirlist in configure file to `bdbdirlist="/h/vm/libs/db-4.8.30.NC/build_unix"` and change the include in confdefs.cpp to:
`#include "/h/vm/libs/db-4.8.30.NC/build_unix/db_cxx.h"`

All the work is no effect.
How do I?

**Comment by jonasschnelli** [comment]
Did you pass in the correct include path. You `./configure` command could be wrong. I think it should be `-I/h/vm/db-4.8.30.NC/build_unix/include/` (append the **`include/`**).

Also, maybe you manage it to install a newer version over a mingw package manager (mingw-get or something), though I'm not familiar with mingw package managers.
You can always pass `--with-incompatible-bdb` in `./configure` to allow compilation against newer versions of berkley db (which results in wallet files that are incompatible with bitcoin version compiled with bdb 4.8).

**Comment by redfly001** [comment]
Thanks jonasschnelli  !
I sure the db_cxx.h file is in the build_unix folder(ps, there is no sub-dir in the build_unix folder).

` --with-incompatible-bdb ` option is no useful for this error.

Another question, sometimes configure shows missing library -lssp or -lcomctl32 or -lwinmm , but not everytime shows the error.

I think a good idea is understand the configure core grammer or the most important functiones to debug the configure file, but I cannot understand them.

**Comment by joshafest** [comment]
You need to build leveldb in local directory

**Comment by chenluyong** [comment]
Why close the Issue

**Comment by sakurashiki** [comment]
How to resolve this problem???

**Comment by lukassaul** [comment]
for me it was helpful to install libboost-all-dev :)

**Comment by averissimo** [comment]
this did it for me: `export CPPFLAGS="$CPPFLAGS -I/usr/local/BerkeleyDB.4.8/include/`

**Comment by scottie** [comment]
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

;)

**Comment by bboot** [comment]
Beware, add-apt-repository ppa:bitcoin/bitcoin has this message:
Note that you should prefer to use the official binaries, where possible, to limit trust in Launchpad/the PPA owner.

**Comment by ccd888** [comment]
Scottie's worked for me.
Thx!

**Comment by jasonzhouu** [comment]
@scottie 's method don't work for me.

```
> sudo add-apt-repository ppa:bitcoin/bitcoin
gpg: keybox '/tmp/tmpygiedx54/pubring.gpg' created
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/tmpygiedx54/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

**Comment by agbhanu** [comment]
> sudo add-apt-repository ppa:bitcoin/bitcoin
> sudo apt-get update
> sudo apt-get install libdb4.8-dev libdb4.8++-dev
> 
> ;)

Thanks, worked for me Scottie.

**Comment by r3lik** [comment]
> @scottie 's method don't work for me.
> OS: Debian 9.9
> 
> ```
> > sudo add-apt-repository ppa:bitcoin/bitcoin
> gpg: keybox '/tmp/tmpygiedx54/pubring.gpg' created
> gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
> gpg: connecting dirmngr at '/tmp/tmpygiedx54/S.dirmngr' failed: No such file or directory
> gpg: keyserver receive failed: No dirmngr
> ```
> 
> if build Bitcoin Core without wallet, it will not emit this error
> 
> ```
> ./configure --disable-wallet
> ```
> 
> ref: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#ubuntu--debian

`apt-get install dirmngr` to fix the gpg issue

**Comment by flipkickmedia** [comment]
This is still an issue for me on a newly installed Ubuntu 20 box.

**Comment by rustyx** [comment]
Just follow the [build docs](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#berkeley-db):

The Bitcoin Core source contains a script `contrib/install_db4.sh` that downloads and compiles bdb4.8 locally.

```
cd bitcoin
./contrib/install_db4.sh `pwd`
```

Then configure bitcoin core with

```
./configure BDB_LIBS="-L`pwd`/db4/lib -ldb_cxx-4.8" BDB_CFLAGS="-I`pwd`/db4/include"  ...
```

**Comment by Cyclone14089** [comment]
sudo apt update && sudo apt install libdb5.3++ libdb5.3++-dev

**Comment by visualbasic6** [comment]
The solution, at least for Ubuntu 21.10, in 2021, is:

```
wget http://download.oracle.com/berkeley-db/db-4.8.30.zip
unzip db-4.8.30.zip
cd db-4.8.30
cd build_unix/
../dist/configure --prefix=/usr/local --enable-cxx
```

then running `sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' db-4.8.30.NC/dbinc/atomic.h`

**Comment by aelagrassa** [comment]
> The solution, at least for Ubuntu 21.10, at the time of writing is:
> 
> ```
> wget http://download.oracle.com/berkeley-db/db-4.8.30.zip
> unzip db-4.8.30.zip
> cd db-4.8.30
> cd build_unix/
> ../dist/configure --prefix=/usr/local --enable-cxx
> ```
> 
> then running `sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' db-4.8.30.NC/dbinc/atomic.h`

Thanks, this worked for me, also had to run make and make install.

**Comment by mahyariiii** [comment]
i have add coin in yiimp  
command line daemonbuilder
At the time of installation 

configure: error: libdb_cxx headers missing, Bitcoin ABC requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

How can I fix this problem, please help me

**Comment by amritabithi** [comment]
Run this script to install Berkeley DB:
`./contrib/install_db4.sh `pwd``

Do not run the commands below, they are examples of what you will enter.  When you run that script, at the very end it will output 2 more lines for you to run, that will look like this:
```
export BDB_PREFIX='/home/youruser/Feathercoin/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" ...
```

**REMOVE THE THREE DOTS** from the end of the second command, and run both commands in your terminal as your custom ./configure step.

Now you should be able to build with the wallet features.

**Comment by amritabithi** [comment]
Run this script to install Berkeley DB:
**./contrib/install_db4.sh \`pwd\`**

**Do not run the commands below**, they are examples of what you will enter.  When you run the above script, at the very end it will output 2 more lines for you to run, that will look like this:
**export BDB_PREFIX='/home/youruser/Bitcoin/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" ...**

**REMOVE THE THREE DOTS** from the end of the second command, and run both commands in your terminal as your custom ./configure step.

Now you should be able to build with the wallet features.
