### ISSUE TITLE
Decreased size of mempool causes higher incoming traffic and node overload

### ISSUE THREAD

**Issue by johnjacksonbtc** [bitcoin/bitcoin#7973]
Problem becomes apparent when `-maxmempool` is decreased below 100 and problematic at 32. Sometimes incoming traffic is constantly around 100 KB/s randomly between one hour and ten minutes and GUI is lagging. Then lag stops and incoming traffic drops strongly below 100 KB/s line to about 10-20 KB/s. Node is fully synced (there are short bursts of incoming traffic above 100 KB/s), other settings are unchanged. Bitcoin Core 0.12.1 Windows version is used.
Edit: There are less lags when `-maxmempool` is left to default 300.

**Comment by jonasschnelli** [comment]
@TheBlueMatt (or others): If the mempool is relatively small (let's assume 10MB), are there more `cs_main` locks per seconds or any other reason why small mempools could result in more freezes?

**Comment by rebroad** [comment]
Why is the mempool defaulting to 300MB? How was this figure arrived at? Assuming blocks are 1MB each, is 300MB allowing for txs that might make it into the next 300 blocks?

**Comment by sipa** [comment]
@rebroad 300 MB of memory usage; it corresponds to approximately 150 MB worth of actual block data (CTxMemPoolEntry uses much more memory than just the serialized transaction), or one day worth of blocks. Given a daily peak and trough of transaction volume, this is the minimum needed to get low-fee transaction in with some chance within a day.

**Comment by hebasto** [comment]
Is this still an issue?

**Comment by MarcoFalke** [comment]
Closing for now. Let us know if this still happens.
