### ISSUE TITLE
news of bitcoin core project on weibo(chinese twitter)

### ISSUE THREAD

**Issue by LongShao007** [bitcoin/bitcoin#7979]
Weibo(http://www.weibo.com) is the biggest microblog in china, it's like twitter.
I just registered an account. the account name is Bitcoin Core Project.(http://weibo.com/bitcoincore), but I didn't say anything.
I want to publish some news of the project, the news is from GitHub, dev-maillist, bitcoincore.org and twitter (@bitcoincoreorg).
Let the Chinese know everything about the project more easily.
Maybe i will translate the news headlines into Chinese.

**Comment by btcdrak** [comment]
Thank you. Please join us on Slack at https://slack.bitcoincore.org/ or IRC in #bitcoin-core-dev and connect with @jl2012 who is a Chinese speaking developer.

**Comment by jl2012** [comment]
Please send me an email : jl2012 at xbt.hk , thanks!

**Comment by LongShao007** [comment]
@btcdrak 		
I just joined the team on Slack. my name is 007longshao.

@jl2012 
I have just sent you an e-mail.(from 007longshao@gmail.com)

**Comment by LongShao007** [comment]
I sent the first micro-blog.it's from twitter(@bitcoincoreorg)
> There is currently no publicly available cryptographic proof that anyone in particular is Bitcoin's creator. -- Bitcoin Core

I will try to operate.

**Comment by sipa** [comment]
Is there anything left to do here?

**Comment by LongShao007** [comment]
No, i will community with jl2012 via email and wechat.
