### ISSUE TITLE
Current number of blocks are not updating in the GUI

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#7988]
Just started to sync a new node over the GUI on Ubuntu 16.04 with `dbcache=3500` and got this:

<img width="942" alt="bildschirmfoto 2016-05-02 um 15 41 44" src="https://cloud.githubusercontent.com/assets/178464/14955764/752a45f6-107c-11e6-827c-bd7755c0fa93.png">

**Comment by laanwj** [comment]
Known issue: see https://github.com/bitcoin/bitcoin/issues/5851#issuecomment-106713148

I think if the cs_main lock is really contended, the GUI doesn't get the chance to update the block number (as this happens through try_locks now - it's better than hanging).

**Comment by jonasschnelli** [comment]
Sorry. I was running master with #7917 on top. Resetting to master cures the issue. It's a #7917 specific issue.
