### ISSUE TITLE
Windows installer launches GUI as Admin

### ISSUE THREAD

**Issue by Michagogo** [bitcoin/bitcoin#7990]
When installing the GUI with the Windows installer, there's a checkbox at the end of the process that launches the software. However, when the installer launches a process, it runs at the same Integrity Level (privilege) as the installer. As the installer is, well, installing software, it needs to run at the High (elevated/admin) privilege/Integrity Level, and hence the node/GUI will be launched at that same level. I've confirmed this using [Sysinternals Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) -- launching Bitcoin Core from the Start menu results in an Integrity Level of Medium, as expected, while closing the installer without deselecting the checkbox results in the process being started at the High level.

A quick search does turn up ways to work around the issue (such as [this plugin](http://nsis.sourceforge.net/ShellExecAsUser_plug-in) in combination with [this trick](http://nsis.sourceforge.net/Run_an_application_shortcut_after_an_install)), but I wonder if we really need that checkbox there at all. I know nothing about NSIS and how easy that is (what a plugin is, what would be involved in using it, or what other ways there are to do the same thing, etc.), but it seems to me that if it's not trivial to fix this we may as well just drop the box altogether.

**Comment by PRabahy** [comment]
Related to https://github.com/bitcoin/bitcoin/issues/5798

**Comment by Michagogo** [comment]
Yeah, though what I saw didn't quite match what appears there. I'm pretty
sure it asked me to elevate right at the beginning. However, when launching
with elevated privileges at the end, it did still seem to be launching as
me. Didn't ask for a different datadir.
