### ISSUE TITLE
Bitcoin core still work on windows XP ? 

### ISSUE THREAD

**Issue by b3mb4m** [bitcoin/bitcoin#8008]
I just installed core wallet and thats throw me several error(multiple times) and closed immediately.But now(after 1-2 close) its working without any error.Is that normal or should i change to w7 ? 

Will install error screenshots soon if its required ..

**Comment by sipa** [comment]
See #7674.

**Comment by b3mb4m** [comment]
Thats what i guess .. thank you :disappointed: :disappointed:
