### ISSUE TITLE
rpc-tests.py --help

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#8017]
```
pull-tester bitcoin$ ./rpc-tests.py  --help | head -1
Usage: bip68-112-113-p2p.py [options]
pull-tester bitcoin$ 
```

**Comment by paveljanik** [comment]
`-extended` is also not shown in the `--help` output.

**Comment by MarcoFalke** [comment]
This is by design: In theory args with only one hypen should go into the pull tester and args with two hypen should go into the specific test.

You may want to look at #7971, which clarifies the docs, hopefully.

**Comment by paveljanik** [comment]
I'm on it right now.

**Comment by fanquake** [comment]
@paveljanik What's the status of this now that #7971 has been merged?

**Comment by paveljanik** [comment]
```
pavel$ ./rpc-tests.py --help
Usage: p2p-fullblocktest.py [options]
```

**Comment by MarcoFalke** [comment]
@paveljanik Make sure to select only the rpc test you want the help for. (default=select all quick tests)

The script will only print help of the first script and exit: https://github.com/bitcoin/bitcoin/blob/9e45ef1ef0314d23938c200bd357b2a069acde9b/qa/pull-tester/rpc-tests.py#L182

**Comment by MarcoFalke** [comment]
> -extended is also not shown in the --help output.


I will try to clean up the doc further when we got rid of the `-win` option.

**Comment by paveljanik** [comment]
I think --help should help me to select tests I would like to run and not print the first help available :-) Of course I know I can run selected scripts directly.

**Comment by MarcoFalke** [comment]
If you need help selecting tests, the intention was to look at https://github.com/bitcoin/bitcoin/blob/9f1807af2422e3ac2d3702242b4a47c8df0be262/qa/README.md#running-tests

**Comment by paveljanik** [comment]
Sure, or I can read the source ;-) Or execute --help...

**Comment by MarcoFalke** [comment]
> -extended is also not shown in the --help output.

> I think --help should help me to select tests I would like to run

@paveljanik I believe this is fixed on master.

**Comment by paveljanik** [comment]
Yup, `./test_runner.py --help` works as expected, closing.
