### ISSUE TITLE
[Test Framework] Support setting the p2p/RPC port range over the cmd line

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8022]
"For supporting multiple tests running in parallel, I think it might make sense to add support to the test framework for specifying a range of ports to use for the p2p and rpc ports on the command line, which the rpc_tests.py script could use. The logic now of hoping that pid's don't collide modulo some big number is not sufficiently robust in my opinion."

Original comment from @sdaftuar [here](https://github.com/bitcoin/bitcoin/pull/7971#issuecomment-217537126).

**Comment by MarcoFalke** [comment]
#7972 includes a patch (ccccc59) to pass in a seed instead of relying on `os.getpid()`. Not sure if more than that is required/wanted.
