### ISSUE TITLE
Add 'how to squash several fixup commits' to our coding guideline

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#8032]
Adding this to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md helps to not have it copy paste in every comment: https://github.com/bitcoin/bitcoin/pull/8004#issuecomment-217810102

**Comment by Tyler-Hardin** [comment]
Yes, can confirm this would be helpful. I've been `git reset --soft HEAD~n`ing to do this, where n is the number of commits I've made in total. The right was is less tedious.
