### ISSUE TITLE
bitcoin core 0.12.1.0-g9779e1e crashing when opening debug window during startup

### ISSUE THREAD

**Issue by mkae** [bitcoin/bitcoin#8040]
MacPorts-installed Bitcoin Core's version v0.12.1.0g9779e1e crashes on OSX when trying to open the debug window while the app is verifying the blocks at startup.

**Comment by Tyler-Hardin** [comment]
Describe the process. Do you mean you try to open the debug window during the splash screen? How? What keys?

**Comment by mkae** [comment]
Yes, that's what I did. On OSX the global menu is active and I can thus click on the corresponding menu item in the Help menu while the splash window is shown.

I figure that this isn't intended, right.

**Comment by jonasschnelli** [comment]
Thanks for reporting!
I can confirm the bug. I think opening the debug window during splash-screen state is only possible on OSX.
Will work on a fix.
