### ISSUE TITLE
Missing Tray menu on Ubuntu

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#8043]
I have tested the official gitian build from 0.12.1 on Ubuntu 16.04 as well as self-compiled on 15.04 and came to the same error-behavior: 
Clicking on the tray icon reveals no or an empty menu.

Could be an Qt upstream bug.

<img width="912" alt="bildschirmfoto 2016-05-11 um 21 41 27" src="https://cloud.githubusercontent.com/assets/178464/15194514/8a2d4a7c-17c3-11e6-8531-86d329e7646d.png">
<img width="1066" alt="bildschirmfoto 2016-05-11 um 20 28 23" src="https://cloud.githubusercontent.com/assets/178464/15194516/8a53b2f2-17c3-11e6-8ebf-66e19563b17f.png">

**Comment by MarcoFalke** [comment]
Works fine on fedora both with self-compiled and gitian releases.

**Comment by MarcoFalke** [comment]
Relevant comment: https://github.com/bitcoin/bitcoin/issues/7497#issuecomment-182341185

**Comment by laanwj** [comment]
I don't have a tray icon either on Ubuntu 16.04. 

It looks like tray icons for individual applications are dying out. On windows 10 they are grouped together in a popup menu in the task bar. On MacOSX I'm fairly sure we already disable the tray as it is simply the docker icon. 

Ubuntu prefers showing a few hardcoded groups like 'network', 'language', 'messages', 'sound', and so on. It should show them for 'legacy' applications though but support is clearly flaky.

**Comment by Pawcio88** [comment]
Looks like a problem with initial rendering the tray. You can solve this issue by first hiding it (Options/Window/Hide tray) and then showing it again. From now on the tray should render properly.

**Comment by MarcoFalke** [comment]
I believe this can be closed, since it should work on Ubuntu 17.10 and later.

Yes, having this bug on xenial is an annoyance, but pretty much an upstream bug, so I doubt we could do anything here.
