### ISSUE TITLE
Unsynced wallet status should be more apparent

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8060]
Currently the wallet shows warning triangles on the "Overview" page when the client is not synced.

Looking at the volume of mail I receive from people confused by unsynced client behavior, as well as issues like #7235 this is not enough.

I think it would make sense to:

- Make the warning look more serious. E.g. make the icons red or yellow instead of the same color as the rest.
- The warning should appear on every page, not just Overview but also when receiving or sending transactions. Possibly on the bottom bar.
- Mouseover should warn that:
  - Transactions are not up to date -  most notably, received transactions more recent than the current synchronization time are not yet visible. This should be made really, really clear.
  - Balance is not up to date - it does already say this implicitly by showing the triangle next to the balance and recent transactions, but not everyone picks up this hint.
  - Fee estimation is not up to date/incomplete - maybe we need a separate warning for this on the "Send" page.

**Comment by jonasschnelli** [comment]
Agree with @laanwj. I pick this up.

**Comment by Tyler-Hardin** [comment]
@laanwj how do you envision this? I'm interested in implementing it, but I don't see a way that's not massively redundant. We already have the sync progress bar and the text warning to the left of it.

What do you think about adding a red or yellow caution to the right of the warning text, to draw attention to it? That seems to best fit with what already exists. Augmenting instead of duplicating. I could change the mouse over text from the sync bar/text to reflect the extra warnings you describe, and add this mouse over to the new warning icon as well.

How does all that sound?

**Comment by laanwj** [comment]
@Tyler-Hardin sounds good to me!

**Comment by jonasschnelli** [comment]
I have a different approach:
If you start, or getting in a state where your Bitcoin-Core GUI is "out-of-sync", we could overlay the MainWindow with an info-layer (maybe slightly semi-transparent) that could inform about the out-of-sync state (warning with some text), the required blocks to catch up, maybe current blocks-per-seconds rate, etc.

Users could "click-away" that modal information layer. But at least a click-away action is required. Once the layer has been clicked away, we could go back to the current state where we show the exclamation mark warning icons

**Comment by MarcoFalke** [comment]
Sound good as well. Make sure to include a "[ ] Never show this again" toggle.

**Comment by MarcoFalke** [comment]
Most of this was done in #8371. Not sure if those should be addressed:

(copied from OP)
  - Transactions are not up to date -  most notably, received transactions more recent than the current synchronization time are not yet visible. This should be made really, really clear.
  - Balance is not up to date - it does already say this implicitly by showing the triangle next to the balance and recent transactions, but not everyone picks up this hint.
  - Fee estimation is not up to date/incomplete - maybe we need a separate warning for this on the "Send" page.

**Comment by laanwj** [comment]
Hm, doesn't the overlay take care of all of those? I don't mind that they're not specifically implemented as mentioned there, that was just an idea.

**Comment by MarcoFalke** [comment]
It is missing the fee estimation part, but I think this can be done later.
