### ISSUE TITLE
test_bitcoin failing in travis without log output

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8071]
Travis no-wallet build of master fails unit tests, it is unclear why:
```
FAIL: test/test_bitcoin
PASS: qt/test/test_bitcoin-qt
```
https://travis-ci.org/bitcoin/bitcoin/jobs/131336729

For some reason there is no detailed output.

**Comment by laanwj** [comment]
Merging #8070 to see if this fixes the issue.

However I still wonder why there is no detailed test output anymore? Did one of the recent test changes accidentally remove this? @theuni @MarcoFalke

**Comment by theuni** [comment]
@laanwj It's the newer automake that comes with Trusty that changes the log behavior.
