### ISSUE TITLE
bitcoin core can not visual balance on bitcoin core

### ISSUE THREAD

**Issue by waipot11** [bitcoin/bitcoin#8091]
i downloaded bitcoin core for 2years until now it not can not visual balance on bitcoin core.

    it found error as below link.
    http://imgur.com/l2XdKxn

    how to it can quickly complete?

**Comment by MarcoFalke** [comment]
Duplicate of #8060?

**Comment by jonasschnelli** [comment]
@waipot11: you need to wait until your node is fully synced (see progress bar). This can take a couple of days.

Similar to #8060.
