### ISSUE TITLE
RPC Mining Impossible 

### ISSUE THREAD

**Issue by bitcreditscc** [bitcoin/bitcoin#8093]
I recently tried solo mining , with a dragon 1 TH miner, when that failed i tried a USB miner, cpuminer and an older cgminer. 

Also tried using latest minerd...

./minerd --algo=sha256d --url 127.0.0.1:8332 --user=blah --pass=blahblah

following in bitcoin.conf:
rpcuser=blah
rpcpass=blahblah
rpcallowip:127.0.0.1
server=1
rpcport=8332

...gives me 'connection refused'

Does this have anything to do with the removal of Json in favour of Univalue?

**Comment by MarcoFalke** [comment]
I am not sure if anyone can help you here. We don't use the issue tracker to provide support for 3rd party software and/or hardware.

**Comment by jonasschnelli** [comment]
This seems to be unrelated to our codebase. Please open an issue at your miners software repository.

**Comment by luke-jr** [comment]
Those miners only support Stratum. Use BFGMiner to act as a proxy between bitcoind and stratum (see the --stratum-port option). Note that GBT is broken in 0.12.1, so you will need to downgrade to 0.12.0 temporarily for this to work.

**Comment by gmaxwell** [comment]
> Note that GBT is broken in 0.12.1,

WTF Luke, doesn't implement some corner case flags that are not required in any widely used situation does not mean "broken".

**Comment by luke-jr** [comment]
@gmaxwell Any GBT-compatible client will fail to work with 0.12.1 (the spec requires it), including the particular usage scenario that I was describing.

**Comment by sipa** [comment]
@luke-jr And in practice, hardly any mining follows that spec. The default
behaviour may not be something we want for all future softforks (and I'm
glad you're working on a fix for that), but it is exactly what we want
here. Mining with 0.12.1 will work just fine, and downgrading because of it
is inadvisable.

**Comment by bitcreditscc** [comment]
@MarcoFalke Well, seeing as someone had the bright idea to remove the internal miner.....

Anyway i resolved the issue, thanks to all. On a side note, is Univalue, completely compatible with any app that used Json calls ?

**Comment by sipa** [comment]
@bitcreditscc UniValue should be completely compatible with the JSON-RPC spec. If it isn't, that would be a bug, but it wouldn't result in a "connection refused".

**Comment by luke-jr** [comment]
@sipa De facto, if he attempts to mine with 0.12.1 using BFGMiner, it will not work at all, as BFGMiner/libblkmaker correctly refuses to mine blocks with an unrecognised version. Downgrading is literally the only simple option people have right now (the alternatives being either: 1] they modify and recompile 0.12.1 by hand; or 2] setting up a full pool server that ignores the GBT spec, which is much more complicated than just running BFGMiner).

**Comment by sipa** [comment]
@luke-jr Not everyone uses BFGminer.

**Comment by luke-jr** [comment]
That is beside the point.
