### ISSUE TITLE
how to get non-walllet transaction confirmations? and single wallet all transactions?

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin/bitcoin#8100]
Hi , all , I want to build a service like blockchain.org , I used `txindex=1` and `-rescan` ( ... take few days ... ) 

now I can get any txid details , like use

    bitcoin-cli getrawtransaction TXID 1

but not include confirmations , so how to get it , and can I get any wallet all transactions ?

or I need another [type , kind] full node solution to help me to get another information?

**Comment by djpnewton** [comment]
try using the zeromq interface https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md

**Comment by JokerCatz** [comment]
hmm ... zeromq look like useless to get confirmations , and I will try to use "toshi" ......

**Comment by jonasschnelli** [comment]
You can use the REST interface.
If you have enabled the -txindex you can get every tx (including confirmations if already mined) over `GET /rest/tx/<TX-HASH>.<bin|hex|json>`.

https://github.com/bitcoin/bitcoin/blob/master/doc/REST-interface.md
