### ISSUE TITLE
Testnet/mainnet cross-reading of settings

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#8106]
In the settings, the Testnet seems to be reading from and setting some options for mainnet and not testnet. I have noticed this with at least the strDataDir option.

Replication steps on Ubuntu 15.10
1. Tail ~/.config/Bitcoin-Qt.conf and ~/.config/Bitcoin-Qt-testnet.conf
2. Reset the testnet settings by going to Settings > Reset Options. Notice how the testnet conf file changes.
3. Now start Bitcoin core with `-choosedatadir -testnet`.

After the third step, you will see that the strDataDir setting is not added to the testnet conf but is added/changed in the normal conf file.

**Comment by jonasschnelli** [comment]
The settings overwritten by the GUI (`QSettings`) are stored/managed by QT. The filename is handled by Qt. I guess chaining the app name (using testnet switched the application name somewhere in init) could lead to a mixed settings read/write behavior.

**Comment by MarcoFalke** [comment]
Are you starting with `-choosedatadir` or `-choosedatadir -testnet`?

**Comment by achow101** [comment]
`-choosedatadir -testnet`

**Comment by beirut-boop** [comment]
Perhaps it would work as intended if we would use the NetworkStyle app name when locating QSettings. E.g.:

```diff
    /// 3. Application identification
    // must be set before OptionsModel is initialized or translations are loaded,
    // as it is used to locate QSettings
    QApplication::setOrganizationName(QAPP_ORG_NAME);
    QApplication::setOrganizationDomain(QAPP_ORG_DOMAIN);
-    QApplication::setApplicationName(QAPP_APP_NAME_DEFAULT);
+    QApplication::setApplicationName(networkStyle->getAppName());
```

But I am not confident this is all there is to it.

https://github.com/bitcoin/bitcoin/blob/8e1913ae025ad8912457abe24ae5c61da02fc17a/src/qt/bitcoin.cpp#L496-L501
https://github.com/bitcoin-core/gui/issues/212

**Comment by achow101** [comment]
Moved to GUI repo: https://github.com/bitcoin-core/gui/issues/759
