### ISSUE TITLE
Replace-By-Fee is part of the code already?

### ISSUE THREAD

**Issue by elichai** [bitcoin/bitcoin#8114]
I saw this here:
https://en.bitcoin.it/wiki/Transaction_replacement
And it doesn't really clarify if it got inserted into the official code or not.
So did it?

(P.S. I think it's a bad idea but just wanted to know :) )

**Comment by elichai** [comment]
Is this what's inside the official code now?
https://bitcoincore.org/en/faq/optin_rbf/

**Comment by sipa** [comment]
The wiki is (always) outdated.

Yes, transactions that explicitly indicate so are replaceable in the mempool. See https://www.reddit.com/r/Bitcoin/comments/3urm8o/optin_rbf_is_misunderstood_ask_questions_about_it/ and https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki.

If you think it's a bad idea, that's fine; you don't need to use it.

**Comment by elichai** [comment]
Thank You,
As you said someone should really update the wiki :)
One thing I just didn't understood in the BIP is this line:
`Inherited signaling: Transactions that don't explicitly signal replaceability are replaceable under this policy for as long as any one of their ancestors signals replaceability and remains unconfirmed.

Does it mean you can RBF a transaction without setting the nSequence to UNIT_MAX-1?

**Comment by luke-jr** [comment]
Feel free to update the wiki yourself...
