### ISSUE TITLE
[OSX] `make deploy` is currently failing

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8120]
OS X 10.11.5, Python 3.5.1
After building as usual.

```
$ make deploy
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
/usr/local/bin/python3 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -translations-dir= -dmg -fancy ./contrib/macdeploy/fancy.plist -verbose 2 -volname Bitcoin-Core
Error: Could not find background picture at "background.tiff" or "./contrib/macdeploy/background.tiff"
make: *** [Bitcoin-Core.dmg] Error 1
```

The instructions in [macdeploy/README.md](https://github.com/bitcoin/bitcoin/blob/master/contrib/macdeploy/README.md) might also need updating.

**Comment by MarcoFalke** [comment]
Have you tried with `git clean -dfx` (make sure to move any untracked files out of the way) or try in a fresh worktree: https://git-scm.com/docs/git-worktree#_examples

**Comment by fanquake** [comment]
Yes, same result after running `git clean -dxf`

**Comment by luke-jr** [comment]
Do you have rsvg-convert, ImageMagick, and tiffcp?  These are required for `make deploy` now.

**Comment by fanquake** [comment]
Yes, all installed via brew
```
librsvg
imagemagick
libtiff
```

**Comment by luke-jr** [comment]
Does configure find them? Post config.log

**Comment by fanquake** [comment]
Looks like it doesn't
```
IMAGEMAGICK_CONVERT=''
RSVG_CONVERT=''
TIFFCP=''
```
Full [config.log](http://pastebin.com/6azu493s)

**Comment by luke-jr** [comment]
Has this ever worked? All the `make deploy` program checks are only for non-Mac build systems in configure...

**Comment by jonasschnelli** [comment]
There are serval problems with the "make deploy" target on OSX.
The `Makefile.am`'s image/background generation only runs when not compiling on OSX (bug).
Also the `configure.ac` scrips only looks for imagemagick & co. if not compiling on OSX (bug).
On top of that, `configure.ac` looks for python3 in the first place which is incompatible with the current make deploy `macdeployplus.py` script.

Will fix soon.

**Comment by theuni** [comment]
@jonasschnelli on native osx, the macdeploy script uses the "-fancy" option, which uses native osx tools rather than requiring the same ones needed for cross builds. This was done because at the time, there was no way to generate everything using open tools.

When the svg stuff was added and the static images were removed, the native side wasn't updated.

So here's what I'd propose: Switch to the open tools as much as possible. For everything that requires python2, use the native OSX tools until they're updated. At that point, we can switch away.

**Comment by theuni** [comment]
Meh, now that I have it done up, I'm not sure that I care for it. Changes here: https://github.com/theuni/bitcoin/commit/c622254170d4bd8c5ca75077214105cef666f4c4
Compared to the approach in #8135:

Pros:
- Doesn't require python2
- Doesn't require imagemagick

Cons
- Uses system utils and doesn't match the way we do releases

**Comment by laanwj** [comment]
@theuni Whatever we do, we should not make python2 a dependency in the cases where it is not explicitly needed (e.g. native macosx build).

**Comment by laanwj** [comment]
Is this still the case?

**Comment by sgeron** [comment]
I got the same message today :"Error: Could not find background picture at "background.tiff" or "./contrib/macdeploy/background.tiff"

**Comment by jguitton** [comment]
If someone want to do the pull request to close this issue :

```
diff --git a/contrib/macdeploy/fancy.plist b/contrib/macdeploy/fancy.plist
index ef277a7..a6a1c31 100644
--- a/contrib/macdeploy/fancy.plist
+++ b/contrib/macdeploy/fancy.plist
@@ -10,7 +10,7 @@
                <integer>620</integer>
        </array>
        <key>background_picture</key>
-       <string>background.tiff</string>
+       <string>background.svg</string>
        <key>icon_size</key>
        <integer>96</integer>
        <key>applications_symlink</key>
```

**Comment by jonasschnelli** [comment]
@jguitton thanks. Yes. Your solution could work,.. I guess macdeploy calls imagemagicks `convert` (if compiled with SVG support, this should work).
I think https://github.com/theuni/bitcoin/commit/c622254170d4bd8c5ca75077214105cef666f4c4 is more stable and should be PRed (ping @theuni ).

**Comment by jguitton** [comment]
@jonasschnelli i don't see any tiff, png or psd in the repo. @theuni pr is partly about converting png files.
now that only the svg file is present, references to tiff or png are not relevant anymore.

**Comment by jonasschnelli** [comment]
Right. You have to convert the SVG anyways. The question is, how the PR should look like that it works on most OSX setups. AFAIK The plus of @theunis PR is, that the required tools are checked during configure-level.

**Comment by Sjors** [comment]
I just ran `make deploy` on a fresh OSX machine with running `make` first (yes, ignoring the instruction). I get the same error as @sgeron and both icons are missing:

<img width="512" alt="schermafbeelding 2017-12-12 om 18 47 15" src="https://user-images.githubusercontent.com/10217/33899804-e3f80930-df6c-11e7-864c-9cf29abc9bf1.png">

Apart from running `make`, I had to eject `/Volumes/Bitcoin Core` (which isn't obvious as it's not visible on the desktop).

Anyway, I should just follow instructions :-)

**Comment by Sjors** [comment]
Actually that didn't work. The preview while running `make deploy` did show the icons, but the end product doesn't. I'll look a bit more.

**Comment by Sjors** [comment]
It went away after a reboot, sigh.
