### ISSUE TITLE
[GUI] Way to add an OP_RETURN output(s) to a transaction.

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#8124]
When sending a transaction sometimes a user may wish to add a OP_RETURN value to a transaction they are creating.

There is an 'Add Precipitant' button to add another normal output. I suggest there should be an "add OP_RETURN message" button.

I think that it should have the option to enter either: hex, unicode utf-8, ascii format.

I think that this feature should be hidden by default in the same way the coin-control feature is.

**Comment by jonasschnelli** [comment]
Adding a OP_RETURN output is not something we should encourage/support on the GUI level IMO. There is not even an (non raw) function on the RPC layer.

**Comment by da2ce7** [comment]
I made this issue because this is something that I wanted to do today.

I wanted to included the hash of something; I was making another transaction anyway, so adding a op-return would have been the most simple.

But alas, I didn't include this OP_RETURN output since I realised that it would be a pain-in-the-ass to do it with my Bitcoin Core wallet.

**Comment by luke-jr** [comment]
NACK, OP_RETURN is not for spam, nor should spam be encouraged or supported.

> But alas, I didn't include this OP_RETURN output since I realised that it would be a pain-in-the-ass to do it with my Bitcoin Core wallet.

Sounds like exactly the desirable outcome.

**Comment by da2ce7** [comment]
@luke-jr 
You have absolutely no idea why I wanted to include a hash in a OP_RETURN output.

Please show me how you could know that this OP_RETURN output indeed was spam; otherwise please withdraw the statement that I wished to spam the network.

**Comment by luke-jr** [comment]
The comment on encouraging spam related to:

> I think that it should have the option to enter either: hex, unicode utf-8, ascii format.

**Comment by da2ce7** [comment]
Well if you regard there are valid purposes for making custom OP_RETURN outputs; then would not a selection of encodings be helpful.

Only having one encoding option would be fine also; however that would be inconvenient.


However, I more fundamentally don't understand you the objection to 'OP_RETURN' being used for spam. OP_RETURN only takes up block space (it isn't expensive to verify, and doesn't create UTXO bloat); something that is far under-priced.  If transactions fees are increased to 50c because people are writing messages in the blockchain with OP_RETURN, that would not bother me; nor I suspect, the miners that would get the extra fees.

I think that it would increase the utility of Bitcoin.

**Comment by luke-jr** [comment]
There are no valid purposes I can think of for unicode/ascii OP_RETURN. Block space is a burden for more than just you and miners.

**Comment by da2ce7** [comment]
Block spaces is a largely used finite resource. Users preferring to make OP_RETURN outputs will only compete with other uses of the block chain space.

Considering that there always be enough spam to fill the remaining space of any block. I think that spam consisting of OP_RETURN is far preferable to junk transactions that are expensive to verify and create UTXO bloat.

Suggesting that blocks will be _more_ full because of the option to add custom OP_RETURN outputs to transactions is somewhat unreasonable.  People who make them quite well could have far more 'valid purposes' than those who spam the network to create false evidence that the block size needs to increase.

**Comment by midnightmagic** [comment]
The proportion of economic:spam is greater the more we encourage or allow OP_RETURN to flourish. OP_RETURN does not make bitcoin valuable; OP_RETURN is not something nearly any full-node operator wants to bear nor did we agree to store OP_RETURN data that did not represent legitimate economic transaction-based activity. It is an error to encourage anyone to do this who can't discover how to do it themselves.

**Comment by jonasschnelli** [comment]
Closing for now because it seems to be that this feature will be controversial. Feel free to give it a try with a concrete PR.
