### ISSUE TITLE
[GUI] Show transction size in transaction window.

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#8125]
The user of-course can already implicitly work out this information from comparing the fee-rate with the actual fee.

I think that it would be useful for people not wanting to do this arithmetic in their head.

**Comment by jonasschnelli** [comment]
Yes. Why not.
Concept ACK.

**Comment by laanwj** [comment]
Another (circuitous) way they can already figure it out is by copying the raw transaction then counting the hex digits, dividing by two.

But yes it'd make sense
