### ISSUE TITLE
Doesn't compile on OpenBSD - missing macros

### ISSUE THREAD

**Issue by ChoHag** [bitcoin/bitcoin#8127]
The same issue and fix as described on https://github.com/google/leveldb/issues/143

**Comment by laanwj** [comment]
Yes, would make sense to port that over.

**Comment by laanwj** [comment]
This change was in leveldb 0.18 (https://github.com/google/leveldb/commit/803d69203a62faf50f1b77897310a3a1fcae712b), was imported into our repository in 4b0e2d7.
https://github.com/bitcoin/bitcoin/commit/4b0e2d75d78036e7e76fd9584e17b0379ba08d24#diff-e263d9644682fa4799e1a4b299b680a2
So this should be in 0.11 at least.
What version are you trying to build?

**Comment by fanquake** [comment]
@ChoHag Can you follow up here? The changes you reference should be in at least bitcoin-core 0.11.0.

**Comment by ChoHag** [comment]
The instructions at https://github.com/bitcoin/bitcoin/blob/master/doc/build-openbsd.md now work without any extra patching for 0.11.3 (apart from dealing with https://github.com/bitcoin/bitcoin/issues/8269, a totally seperate issue) and 0.12.1.

**Comment by laanwj** [comment]
Closed by #8604
