### ISSUE TITLE
Post CSV softfork trigger TODOs

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8131]
- [x] Update bips.md
- [x] #7540: Rename OP_NOP3 to OP_CHECKSEQUENCEVERIFY

**Comment by sipa** [comment]
Note: as suggested here: https://github.com/bitcoin/bitcoin/pull/8121#issuecomment-222679945

**Comment by laanwj** [comment]
Also #7540: Rename OP_NOP3 to OP_CHECKSEQUENCEVERIFY

**Comment by laanwj** [comment]
Both issues have been handled, closing
