### ISSUE TITLE
Native ds_store python package is not python3 compatible

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#8134]
This tools is required to build a OSX disk image (`make deploy`).
https://github.com/bitcoin/bitcoin/blob/a6a860796a44a2805a58391a009ba22752f64e32/depends/packages/native_ds_store.mk

The tool is currently not python3 compatible (uses `basestring`).

Upstream:
https://bitbucket.org/al45tair/ds_store/

**Comment by laanwj** [comment]
I did submit this upstream: https://bitbucket.org/al45tair/mac_alias/pull-requests/4/further-python-3-compatiblity/diff

ds_store needed no changes by me, at least.

**Comment by thijstriemstra** [comment]
The repository has been moved to github: https://github.com/al45tair/ds_store and the master branch there contains Python 3 fixes.

**Comment by droark** [comment]
Hello. My patch that @thijstriemstra referenced was just pulled. I don't think there's a new release out yet, though. I'm going to go ahead and make a PR that deletes this patch from the Core repo and updates the depends. I don't expect or want it to be deleted just yet. It'll just be there for when it's needed.

**Comment by MeshCollider** [comment]
Looks like this was addressed in https://github.com/bitcoin/bitcoin/pull/12417, closing issue now
