### ISSUE TITLE
SEGV on RPC client crash

### ISSUE THREAD

**Issue by dcousens** [bitcoin/bitcoin#8140]
When using a [custom] RPC client,  and upon that client crashing (that is,  ungracefully dropping a connection), I am somewhat consistently having `bitcoind` SEGV.

I'll see if I can't create a simple test case...

**edit:** not as consistently as I'd hoped

**Comment by dcousens** [comment]
Will re-open if I can reproduce consistently,   I can't seem to re-create it suddenly despite having what felt like I had a minimal test case...  Debugging woes :+1:

**Comment by laanwj** [comment]
We'd at least need a stack trace from gdb (for the http threads) to troubleshoot this.
