### ISSUE TITLE
Core v0.12.1 database error

### ISSUE THREAD

**Issue by Lat6819** [bitcoin/bitcoin#8146]
My OS is ubuntu 14.04.1 Linux 4.2.0.37, HDD Western Digital Red 1TB. I have performed extensive surface testing through SMART, it has taken 3 hours /with linux distro Parted Magic "DISK HEALTH"/ - no problem was found. I do not use encryption. I think my hardware is O.K. I have performed reindex but in "16-th weeks" the reindex was extreme slow my debug log files was growing and growing and now it has more than 57 MB size.

2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing transaction
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing output
2016-06-01 17:13:57 ERROR: ApplyTxInUndo: undo data overwriting existing output

When I started bitcoin-qt again without reindex then reindex was not continue, I had to reindex again from first block. I plan  to unnistall bitcoin 12.1 and its dependencies. I know, that in last version the libraries was updated and optimalized for bitcoin - and bitcoin should run much more quicker - it was true - bitcoin-qt was quicker but after last sync I am not able to perform full reindex. More over I always do backup of entire blockchain to second partition on the same WD RED. I use ext4 filesystem. I always do backup and when "copy" is finished I always type in terminal command "sync". Then I ran litecoin 10.4 without any problem.
So I feel really frustrated by this "bitcoin-qt" problem.

So something is bad, but I think not with my hardware. Please let me give some advice. I wish to have full blockchain on my computer.

UPDATE:
So my system: 4GB RAM, WD 1TB, 2 partitions exclusively for blockchain. I do not use default bitcoin-qt directory .bitcoin. I have it on separate partition. The second "blockchain" partition is for backup purpose.
My OS is Xubuntu 14.04.1 64bit. I have tested RAM with memmtest /running 4 hours/ - no problem. I have tested WD 1TB with utility "DISK HEALTH", which I have found in Parted Magic distro /running 3 hours 33 minutes/, this test has examined disk surface - so called built in SMART test - no problem was found. My PSU is Seasonic so the voltage stability is great. My motherboard is is Gigabyte with ULTRA DURABLE 4. So my hardware is O.K.

Bitcoin-qt client 12.01. I have not problem with previous version. I have installed bitcoin-qt in linux with PPA.

I have reinstalled bitcoin-qt client 12.01 with all dependencies with apt-get. My last reindex after reinstallation was successfull. But problem was with RAM. Bitcoin-qt has consumed 3340 MB of RAM. My settings for "SIZE OF DATABASE CACHE" was 2000MB. My PC was slow such as old 486 with Win95. I have stopped bitcoin-qt in standard way. The next start ended with message: "Database is corrupted, do you wish rebuilt". I have pressed yes and now I am reindexing. But my new settings for "SIZE OF DATABASE" is now only 500MB. So now I am reindexing. I will write here the result. When someone has similar problem please let us to know about it, maybe together find some solution. But I can not imagine the situation, when the blockchain grows after years for example over 300 GB and then I  need to do reindex with HDD spinner and with my celeron cpu.

I always perform HDD optimalization. I run bitcoin-qt with "custom blockchain directory", which is on separate partition. The synchronization with network is done - I close bitcoin-qt. Then I reboot PC with Parted Magic. I format the second "blockchain partition" and copy all data from updated "blockchain partition" to second formated "blockchain partition". I copy data with standard file manager and then I type in terminal sync.

When this operation is done. I format the first updated "blockchain partition" and copy data back from second "blockchain partition" and type sync in terminal. The main reason is: I have fresh ex4 file system without fragments. This solutions worked perfectly up to 12.01 bitcoin-qt  /database is corrupted/. I have litecoin 10.4 which has its default directory on my "blockchain partition", too and it works perfectly without any problem.

blockchain partition = is the partition in which I have all files which should be in default .bitcoin directory located in /home directory. I have of course in this partition directories such as "BITCOIN BLOCKS", "LITECOIN BLOCKS" and so on.  

UPDATE: I have performed full reindex. My last sync with bitcoin network was 16 weeks ago. My settings for RAM ussage by database cache in bitcoin-qt is 1000MB. My total RAM 4096MB - 128MB for graphic memmory. I was 33 hours behind with bitcoin-qt client, and suddenly error occured and bitcoin-qt closed unexpectedly, due to small amount of free RAM the problem could not be analysed and sent to developers. So with bitcoin-qt 12.1 is something wrong.

Now, when I imagine, that buggy bitcoin-qt client reindexed my entire blockchain 4 times - wau maybe I will need to download entire blockchain once again. Next time I will wait with update

More over, I am not alone with this problem. On bitcointalk.org is opened thread tittled Re: Core v0.12.1 database error. There one user has "blockchain" directory on separate external HDD with encryption and has the same problem. https://bitcointalk.org/index.php?topic=1454836.msg15048321#msg15048321. Please help. Now I am reindexing with 4GB RAM and celeron CPU /1400 scores on cpubenchmark.org/ without AES instructions this is the fiveth reindexing. Actually I reindex non-stop entire  week. When it help or not. My wallet is locked. I have started to build my blockchain in Windows XP on another PC. I have coppied data in my linux machine. I performed complet reindexing before one year. Since that operation I had not any problem - until bitcoin-qt 12.1 has been installed via PPA in my XUBUNTU. I mention once again. I have installed litecoin 10.4 not via PPA, I use litecoin without any errors. I know, that once comes situation, when blockchain will have a few TB, but upto this fenomen. I want to have main own blockchain on my own hardware. Please help. 

PS: I am thinking about my RAM. It is non-ECC. Maybe bitcoin-qt with high RAM usage is the best RAM test, which we have ever seen. Memtest86 tests RAM for few hours. But bitcoin-qt has tested my RAM non-stop 48 hours. Bitcoin-qt creates hashes from blockchain in which every bits count. Maybe I am experiencing bitflips errors? I am just considering. RAM are dirty cheap, but question is how reliable they are - I mean standard home users non-ECC RAM.

**Comment by fanquake** [comment]
@Lat6819 In regards to running Bitcoin-Core on a Windows XP machine, as of the 0.13.0 release this will no longer be supported, see #7681
Has your RAM testing turned up any more insights?

**Comment by fanquake** [comment]
Closing this due to lack of response. If the issues are persisting (on a supported OS), please re-open this issue.
