### ISSUE TITLE
"Tell other nodes to filter invs to us by our mempool min fee" message is too technical

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8150]
`-feefilter` should either be turned a debug option (whose help is not translated), or we should come up with a (translation) friendlier help message for the option:
https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L322

Reported on transifex by yahoe.001.

**Comment by laanwj** [comment]
This was introduced in PR #7542. @morcos what is the best way forward here?

**Comment by MarcoFalke** [comment]
I can't imagine a reason for the average user to turn it off. I think this is mostly useful for debug purposes and can be hidden.

**Comment by sipa** [comment]
I don't think there are good reasons for disabling this in production, so a
debug option is perhaps best?

**Comment by morcos** [comment]
It makes sense to me to hide it as a debug option.
