### ISSUE TITLE
Unable to specify bitcoin.conf via command line

### ISSUE THREAD

**Issue by davidmanheim** [bitcoin/bitcoin#8156]
When running bitcoind, the -conf=/directory/bitcoin.conf does not work for an arbitrary location for the config file.

It does allow me to specify the data directory containing the bitcoin.conf file, which causes it to use the file. (Ownership isn't a problem)

Please confirm that others can replicate this behavior. I am running linux, and bitcoin 0.12.

**Comment by laanwj** [comment]
I've used `-conf` many times to use other config files. It should have precedence before `-datadir`, so you can specify a datadir in the config file.

**Comment by laanwj** [comment]
Just verified that this works on master, at least:
```bash
$ cat > /tmp/bitcoin.conf
datadir=/store/tmp/testbtc
printtoconsole=1
^D
$ src/bitcoind -conf=/tmp/bitcoin.conf
2016-06-07 07:28:38 Bitcoin version v0.12.99.0-e20e782 (2016-06-07 09:08:13 +0200)
2016-06-07 07:28:38 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2016-06-07 07:28:38 Default data directory /home/orion/.bitcoin
2016-06-07 07:28:38 Using data directory /store/tmp/testbtc
2016-06-07 07:28:38 Using config file /tmp/bitcoin.conf
...
```

**Comment by davidmanheim** [comment]
OK, so I can confirm that:
1) Command line arguments for -datadir override the one specified in the
bitcoin.conf file.
2) The bitcoin.conf command line argument seems to work, at least when done
the way you listed.

I'll do some digging to see if I can find what the exact user error (or
failure mode) I saw earlier was.

Thanks!

**Comment by MarcoFalke** [comment]
Closing, as this seems to be solved.
