### ISSUE TITLE
Binary release tarballs should come with a README

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8160]
A typical release tarball (or zipball) currently contains the following:

```
bitcoin-0.12.1/
bitcoin-0.12.1/bin/
bitcoin-0.12.1/bin/bitcoin-cli
bitcoin-0.12.1/bin/bitcoind
bitcoin-0.12.1/bin/bitcoin-qt
bitcoin-0.12.1/bin/bitcoin-tx
bitcoin-0.12.1/bin/test_bitcoin
bitcoin-0.12.1/include/
bitcoin-0.12.1/include/bitcoinconsensus.h
bitcoin-0.12.1/lib/
bitcoin-0.12.1/lib/libbitcoinconsensus.so
bitcoin-0.12.1/lib/libbitcoinconsensus.so.0
bitcoin-0.12.1/lib/libbitcoinconsensus.so.0.0.0
```

I think we should add a README.md with the release that describes how to get started, and what every file is for.

For windows we have `doc/README_windows.txt` which gets packaged as part of the installer. It is not packaged as part of the windows zips though.

**Comment by fanquake** [comment]
From #8161:
"The README should also include a link to this repository. This makes it easier to find the source code for potential contributors, as well as avoids awkward questions like #8157."

**Comment by Varunram** [comment]
I notice that we still don't bundle READMEs with tar balls. May I put in a PR for this?

**Comment by fanquake** [comment]
@Varunram No need to ask for permission, feel free to open a PR to fix any open issue.
