### ISSUE TITLE
Binary release doesn't make it easy to find the source code

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8161]
This has been suggested before, but I cannot find an issue for it.

I think we should include a link to this repository in various places. At least:
- [x] The "About" dialog in the GUI [done in #8207]
- [ ] A README that comes with release tarballs (see #8160)

This makes it easier to find the source code for potential contributors, as well as avoids awkward questions like #8157.

**Comment by fanquake** [comment]
Merging the other half of this issue into #8160
