### ISSUE TITLE
ARM binary builds

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8162]
Let's add binary tarballs for:

- ` arm-linux-gnueabihf`: most common modern ARM 32-bit platform
- `aarch64-linux-gnu`: AARCH64

These platforms are used increasingly often for running full nodes.

Adding ARM platform to gitian was attempted before in #7659 but never finished.

**Comment by theuni** [comment]
ACK. I'm working on this and #7770 today.

**Comment by laanwj** [comment]
Implemented by @theuni in #8188
