### ISSUE TITLE
Improvement: Show active command line options / parameters values in GUI

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#8165]
I think it would be very professional and inspiring confidence, if the user could verify the settings from the command line/the config file(bitcoin.conf), in the running instance in the GUI.

Maybe in the GUI window "help"->"command line options" for every option that sets a parameter, there could be a line inserted, that shows the current active value of this parameter.

E.g. if one has set
onlynet=tor
in bitcoin.conf
it would be nice IMHO, if the user could verify that this setting is active, in some window.

Maybe even with a reason (e.g. state "listen=0 because proxy parameter is set")

**Comment by laanwj** [comment]
I agree adding a list of options in another place would be useful, but the settings that were overridden from bitcoin.conf or the command line are already shown at  the bottom of the options dialog.

**Comment by MarcoFalke** [comment]
Right, but this only covers stuff that you can set via the gui.

It would be helpful to have a 'show all opts that were changed from their
default value' or a list with all options and highlighting those that were
changed from their default values.

**Comment by laanwj** [comment]
Sure.
That'd require some registration mechanism for options, though.
(which is way overdue for other reasons too, such as #1044)

**Comment by fanquake** [comment]
Moved to https://github.com/bitcoin-core/gui/issues/649.
