### ISSUE TITLE
getbalance comment incorrect

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#8183]
https://github.com/bitcoin/bitcoin/blob/master/src/wallet/rpcwallet.cpp#L693  

> // getbalance and "getbalance \* 1 true" should return the same number

This appears to not true at least in two cases, at least in regtest:
- You send funds to yourself
- You send funds to anyone with -spendzeroconfchange=0

For for first case, `getbalance` includes the zero conf change.

In the latter case, it seems to differ by the fee amount and coinbase subsidy. Perhaps due to how it accounts coinbase values?

I unfortunately don't understand the 2nd case well enough to make a proper edit to the comment. Is this known behavior?

May be best to simply remove the line.

**Comment by laanwj** [comment]
I think in time we need to get rid of all those different ways to get the balance.

**Comment by MarcoFalke** [comment]
Agree, we should just remove the opts to `getbalance` rpc call and return a dict, such that the keys denote how the balance was calculated and the value denotes the balance. (Similar to the emoji chart in #7715.)

**Comment by molxyz** [comment]
Hi, in NTumbleBit the "Watch-only" part of Core wallet is used for escrowed multisig timelocked coins, they are part of the total balance but not spendable until later.  So I saw @instagibbs mentioned this PR on IRC and out of curiosity I found that, from my wallet, "getbalance" only shows balance of the "Spendable" coins, but "getbalance * 1 true" returns the true balance of the wallet.  Attached is a screenshot of the wallet:
  
![getbalance](https://cloud.githubusercontent.com/assets/21127776/21952072/d6cdc598-d9e0-11e6-9d95-29f51548c783.png)

**Comment by TheBlueMatt** [comment]
Can we kill getbalance "*" for 0.14? It seems super broken (and is broken further by bumpfee, whether that makes it for 0.14 or not).

**Comment by TheBlueMatt** [comment]
Oops, indeed, the 3rd parameter is include_watchonly - this seems to be the only way to get balance of watchonly addresses, so even if we remove the accounts stuff some part of it needs to stay.

**Comment by sipa** [comment]
Can we make 'getbalance' an alias for 'getbalance "*"', and use the old 'getbalance' algorithm for account="*"?

**Comment by morcos** [comment]
+1 for @sipa's idea...

i think the question is whether its a bit late to be mucking around with this for 0.14 and risk something accidentally being worse

**Comment by morcos** [comment]
After further review, I'm not sure there was any further regression in 0.14 even with #8456, so lets just fix this properly for 0.15, but perhaps throw an even bigger warning on it for 0.14?

I'd suggest also making simple new RPC's for `getwatchonlybalance` and `getunconfirmedwatchonlybalance` , similar to the existing `getunconfirmedbalance`.

**Comment by ryanofsky** [comment]
> Agree, we should just remove the opts to getbalance rpc call and return a dict, such that the keys denote how the balance was calculated and the value denotes the balance. (Similar to the emoji chart in #7715.)

The getwalletinfo RPC returns a dict with balance, unconfirmed balance, and immature balance. Maybe we should deprecate getbalance and getunconfirmedbalance RPCs in favor of this.

**Comment by instagibbs** [comment]
closing this since accounts are getting nuked
