### ISSUE TITLE
Error when I compile

### ISSUE THREAD

**Issue by Frederic94500** [bitcoin/bitcoin#8190]
# Hello!

I have a error when I compile bitcoin with "make check"

[http://pastebin.com/JDyEAS7C](url)

The error says: Cannot execute the binaries file : Error of format for exec()

NOTE: I try to compile for Windows (x86_64-w64-mingw32)

**Comment by theuni** [comment]
Assuming you're on Linux/OSX, you need to install Wine and make sure binfmt is setup and working. Your distro should take care of that.

**Comment by Frederic94500** [comment]
@theuni Oh okay i going to test this

**Comment by Frederic94500** [comment]
Okay all right, but, why compile with version 0.12.99?

**Comment by sipa** [comment]
0.12.99 is the temporary version number currently used in the master branch. Once the featureset for 0.13 is frozen, it will be renamed to 0.13.0.
