### ISSUE TITLE
Bitcoind Internal Server Error

### ISSUE THREAD

**Issue by macdasi** [bitcoin/bitcoin#8211]
I'm trying to call bitcoind sendtoaddress with params :

18et8yw71yfxsQz99c5sHHEgYtR32kkfw 0.15161962

and there is an exception "(500) Internal Server Error."

The wallet has sufficient funds ~30 bitcoins
The same call to different address works good
The same call with different amount (0.001bitcoin) works good
It started to fail with internal errors since 0.12.11 bitcoin core version and qt-5.5.0
I don't understand why only this call failed ?

I set the fee to 0.0002 before calling sendtoaddress , the problem is that the call sendtoaddress one time works and sometimes return internal error, Is there some kind of log ?

**Comment by laanwj** [comment]
> Is there some kind of log

Anything in `debug.log`?

**Comment by laanwj** [comment]
Could be some problem with your wallet? I don't know. No problem here (I obviously tried with a wallet without funds):
```
$ src/bitcoin-cli -datadir=/store/tmp/testbtc sendtoaddress 18et8yw71yfxsQz99c5sHHEgYtR32kkfw 0.15161962
error code: -6
error message:
Insufficient funds
```

**Comment by macdasi** [comment]
Can I set the debug to only log info for sending transactions ?

**Comment by laanwj** [comment]
Not using command line options. You could temporarily add extra logging in `wallet/rpcwallet.cpp` in the implementation of `sendtoadress`.

**Comment by macdasi** [comment]
Output debugging information (default: 0, supplying <category> is optional). If <category> is not supplied or if <category> = 1, output all debugging information.<category> can be: addrman, alert, bench, coindb, db, lock, rand, rpc, selectcoins, mempool, mempoolrej, net, proxy, prune, http, libevent, tor, zmq, qt.
should I use -debug=rpc ?

**Comment by laanwj** [comment]
Yes you can use debug=rpc (what I suggested, `debug=1` enables all categories including `rpc`) which does some logging per call. I doubt it will help you much with debugging this specific issue though.

**Comment by macdasi** [comment]
I found that this addresses causing the problem "internal server error" 
18et8yw71yfxsQz99c5sHHEgYtR32kkfw
1L9WbTM5XHYAwtpzcSV1gRuSK41aEu2MQg
1BPB3ZG9NJVJNeaAZnJ4itoUBVNEkGMS5c
13s5QivQPeeABXQUYhUxrucULbR4KaBLm6
16RE1uKkg1wH2a4q1r2DvWMg2p4CSXiJqr
191nZhtTosUBSDU6Qjr3A83ajeFV3Qc91g
1JeXoQ6bsHTW465aLBhFj2azRcim1ckYav
14PkPcCSY7iuFo4D21z57EAKygFfbk1QDF
1Ewwe4XuXn9XPCPQUFns9YsVBMFviahx8D
1LoB79zHbhbqMTcEwxWV7FDfUEXUYr6syG
19Yc4Ht9MdxEQ2rTN3hqGZXpDSdJq14xYJ
35JJ6dfGKAaW15SP2RLZbJUa9gZTPZBABq
1FjQm9zwEo5u8pMAbrwfRLMQWYkQUQGYV1
Does it help ?

**Comment by MarcoFalke** [comment]
@macdasi Any information in the relevant parts of debug.log (You may also use `-printtoconsole`)

**Comment by macdasi** [comment]
@MarcoFalke , what should I look for ? the error happens on sendtoaddress call
