### ISSUE TITLE
LXC gitian linux build fails due to wrong password

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8212]
I'm not sure whether this is LXC specific, or whether this is some specific VM setting I should have configured differently. From `var/build.log`:
```
[sudo] password for ubuntu: Sorry, try again.
[sudo] password for ubuntu: 
sudo: 1 incorrect password attempt
```
This is due to the following, introduced in #8188
```bash
echo "ubuntu" | sudo -S true
sudo mkdir -p /usr/include/i386-linux-gnu/
sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/i386-linux-gnu/asm
```
I don't think gitian base image setup ever gave me the chance to configure a password. Looking at `/etc/shadow` confirms this, there isn't one:
```
ubuntu:x:1000:1000:ubuntu,,,:/home/ubuntu:/bin/bash
```
I think we need to find an alternative solution to this.

Possibly a change to gitian descriptors: a preparation script that is executed as root? This works fine:
```bash
LXC_ARCH=amd64 LXC_SUITE=trusty libexec/on-target -u root
root@gitian:~# 
```

**Comment by theuni** [comment]
Dammit, sorry.

I was afraid of some regression here. See my notes in
https://github.com/bitcoin/bitcoin/commit/9d253620874087d96d64d0c4c771a582d9774657

Bottom line is that we need some way to be root in gitian scripts. Whether
that means launching as root, or fixing sudo to be passwordless, I don't
care either way.

**Comment by laanwj** [comment]
> Bottom line is that we need some way to be root in gitian scripts. Whether
> that means launching as root, or fixing sudo to be passwordless, I don't
> care either way.

What about my suggestion: have a section in the descriptor that is run as root, after installing the packages, but before running the rest?

**Comment by theuni** [comment]
Ah sorry, I missed the "preparation script" keywords there. I thought you
were simply suggesting to run as root.

Yes, that makes perfect sense.

**Comment by laanwj** [comment]
Hm yes. Running everything as root inside a container isn't *that* crazy either, though I do prefer some separation of privileges there still.

> Yes, that makes perfect sense.

I'll give it a try (while wishing `gitian` was Python and not Ruby...)

**Comment by laanwj** [comment]
See #8213 and https://github.com/devrandom/gitian-builder/issues/123
