### ISSUE TITLE
negative confirm? (-74)

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin/bitcoin#8219]
I got a transaction & -74 confirm , why? , it's a bug?
    
    bitcoin-cli getinfo
    {
      "version": 120100,
      "protocolversion": 70012,
      "walletversion": 60000,
      "balance": SKIP,
      "blocks": 416879,
      "timeoffset": 0,
      "connections": 8,
      "proxy": "",
      "difficulty": 196061423939.65,
      "testnet": false,
      "keypoololdest": 1463720570,
      "keypoolsize": 301,
      "paytxfee": 0.00050000,
      "relayfee": 0.00001000,
      "errors": ""
    }
    bitcoin-cli gettransaction 5a9bb3d2ee132448d4b24d1a1effe5a711b2b6f595e077a3caa4abd39d5195cf
    {
      "amount": 0.00030010,
      "confirmations": -74,
      "trusted": false,
      "txid": "5a9bb3d2ee132448d4b24d1a1effe5a711b2b6f595e077a3caa4abd39d5195cf",
      "walletconflicts": [],
      "time": 1465869964,
      "timereceived": 1465869964,
      "bip125-replaceable": "unknown",
      "details": [],
      "hex":"0100000002981e07a626707cc7729fd4023420b811f256fd52a3d8a3874c0e89614ebf9a162a0000006b483045022100d220305c4098988a9b2cb8a1f4a9ef660a971bad0bc8de6fadd2fb0901370cfc02205d9ddfca64a9beffa1e3b8893a9c1d10de612777ae8ec35c256d0424dde1551d012102bfa9f400aa72b827e97cf700fd0095ef58427b3722a8864e146739597e4da7b6ffffffffa5a8579881cedb7633a98ee97526ef26e5b945e7d2024b439b8595c4a02ee28c210000006b483045022100be8893c24b95b50cc40de9e40c5eadcb7d17bc0d29e65df574165dca03a37e27022064f52a28fa694bbd1ac689d314295150ca725c9f6f3b9d28e1afe1f2cb16bd0d012103cf6e28873194db825a83e86317963d1e834ed14abd1e1b6a2856097576888dfdffffffff2ee64b0000000000001976a914ccf13f12f21b0a6f66bf98dd1ced1a097cbf22f988aca8610000000000001976a91433cc5360e5d9ccf0ade63eff24ff4fcde44c338b88aca8610000000000001976a91434050245003f41bc464862fcd3c283ae00829eb988aca8610000000000001976a91486a909361339d42d15a4bf4df52f71e5e96b30d388aca8610000000000001976a9148cdb9d55b7d96bbe885a6c22afd972ec6d3957a688aca8610000000000001976a91494af80827fa5d6d67340ee96a08c07f7505a9fdd88aca8610000000000001976a9149d5ceff3768f85516cd15941a30f1f01e943ded988aca86100000000000017a91412964afd0c4960d4d67ec0853335404e36ea524f87a86100000000000017a914ae1ddeb7299abacaff95b46de4aa4ee1d8486b3487c8610000000000001976a9144192ebed91c5b3b8524fb5714c2f1247b9c3e9cf88ac0c620000000000001976a914246a15436fa947c76cf3db6b9697c4233fb50bea88ac0c620000000000001976a9143aab4406348162e6aa2d012d171ad099f703145b88ac0c620000000000001976a91452d6406fe062187ee1cea0d2b497ab90afdb7bc988ac0c620000000000001976a914a4568ee57500f641bdb7519be9bb210f4741263788ac1a620000000000001976a914e68b129f100a77180f3b238f90f5d682ea2f4ff988ac70620000000000001976a91435d29a2e3de959fc0d0d9586f7469b0cc7ef71bf88ac70620000000000001976a914cecea162e464b9d4f6046c0d9ed5a185b54b9cd288ac706200000000000017a914230bfd31430a00d6bbf739313cca63b0975d0d5887b0620000000000001976a9147df4f68f810e0766170dd2cf10792c81fbbc24b588acd46200000000000017a9142062386753718a9b4bd17178fe6a6af60fdb3df887fc620000000000001976a914eaef5c6a6d4ef4e4133a232452f7f7b4832f68c488ac32630000000000001976a9144354540cb9215bf0776d02f7c1fbcedf7a72ff9c88ac38630000000000001976a91469de7cc13b86c3edc74d49ee1cb4187e73ddf00988ac38630000000000001976a914840ad3a71aa58a008866f9b084a1c5969c2d629d88ac926300000000000017a914ceaa6fd65c7c9ffb5a30326ff9c5af90761f93808700640000000000001976a914e2c3212ab21a3858e13d69de14d1a810013146fd88ac54650000000000001976a91417dcff63f14ee2e92ac6cae70b56a0441a058cd288ac20670000000000001976a9143d80a1e3572f9497863a3e18fe54c061fbf4daae88acd8680000000000001976a91424dbda5d136051fff11824013fd8a096fcf749a988acb06b0000000000001976a9141e7f794cc2dd2f27950c2a342c27c4062fb6068788ac986c0000000000001976a9144abbb557e37513fe9d91da3a8be6502af63548e588acf66d00000000000017a91436e9de2b06f5f3ebcc0a56d46f60f4b6330eb47687dc6e0000000000001976a914aedb4c9c5e60019e9c7020bed377fa05d4f7df0b88acf06e0000000000001976a91486440ba701e98a8c059e4efcbc8c7a494b8c245288ac3a750000000000001976a914c78ee3655f1fc2531d5dc8fdb178a8fecaf484f888acce760000000000001976a914bb9a7f88b1b60d160c74ae592bc60b850e3cb27988ac90790000000000001976a914915326412debb4d80deb8b39b7a2b3b604b2197988ac007d00000000000017a914493c5ebdcbac090d9cc7437e438efc861b6921e487088400000000000017a914c587112c855a70f9e4b082e5cc83e1bc2e6b7c1587609a0000000000001976a914049509b37a29dd951529bb9da9d0209c0acf3d7688accca60000000000001976a9142d59df209cee7e60f06013cd3c1894a3fc26cc6488acbfbd0000000000001976a914ade7be737c24f291d339b809665f631d78abc09a88acdcc30000000000001976a91424bc3f2992926713912a754a60b469801b6d6e4088ac80c500000000000017a914d2f698d9f8985a71808f5bd1bed46cd689b6ad0387bcca0000000000001976a914b4578fcee922191393a311bbb8d8907dde146dd388acf4fb0000000000001976a9149b1bc11d9f71c42c91ff208ead7e07600b41605b88ac00000000"
    }

**Comment by sipa** [comment]
See https://bitcoin.org/en/release/v0.12.0#wallet-negative-confirmations-and-conflict-detection

**Comment by JokerCatz** [comment]
okay~ I got it and many thanx : )
