### ISSUE TITLE
bitcoin-config.h.in is not automatically regenerated when necessary

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#8221]
All the dependencies on bitcoin-config.h.in are in src/Makefile, while the build rule for it is in ./Makefile. Since ./Makefile has no interest in bitcoin-config.h.in, it never rebuilds it; and since src/Makefile doesn't know how, it assumes it is a static file. Thus, it is only ever rebuilt when autogen is run manually.

I don't know a good way to fix this.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
