### ISSUE TITLE
Minimise/close and startup bugs

### ISSUE THREAD

**Issue by merceyz** [bitcoin/bitcoin#8225]
Having enabled "Minimise to the tray instead of the task bar" and having "Minimise on close" disabled it still minimises to the tray when hitting close.

Having disabled "Minimise to the tray instead of the task bar" and enabling "Minimise on close" it minimises to the tray, it should minimise to the task bar.

Having enabled "Minimise to the tray instead of the task bar" and hitting the minimise button it minimises to the tray, but when clicking the icon to have it come back it is actually minimised to the task bar, instead of showing up like it was when it got minimised to the tray

When shutting down the bitcoin core with the window as maximised it doesn't start up as maximised again. Instead it's slightly bigger and outside the workspace

**Comment by adlawren** [comment]
Todo:

- [ ] Close when "Minimize on close" is disabled and "Minimize to the tray instead of the taskbar" is enabled
- [ ] Minimize to the taskbar when "Minimize on close" is enabled and "Minimize to the tray instead of the taskbar" is disabled
- [ ] Minimize to the tray properly when "Minimize to the tray instead of the taskbar" is enabled
- [ ] Ensure window is maximized upon restart, after window was maximized before shutdown

**Comment by adlawren** [comment]
I can't seem to reproduce the third and forth items on Ubuntu 16.04, @merceyz can you comment on the environment in which you saw these issues?

**Comment by merceyz** [comment]
Windows 7 64-bit Ultimate edition Service pack 1

**Comment by mmortal03** [comment]
I also see the third issue on Windows 10 64-bit in 0.13.1rc2. A user, PRab, mentioned it in the dev channel on IRC, and I can confirm.

**Comment by fanquake** [comment]
I'm seeing a minimise related issue on OS X. If you run with "Minimize to the tray" enabled, it minimises correctly on start, but then un-minimises when the "Recent transactions may not be visible.." overlay appears.

**Comment by laanwj** [comment]
@fanquake Should OSX even have a "minimize to tray" option? I thought we don't use a tray icon there?

**Comment by jonasschnelli** [comment]
Yes. Tray-Icon is not supported on OSX, though, I think by changing the -uiplatform it may be possible.

**Comment by fanquake** [comment]
I guess instead of tray, I mean "Dock" on OS X.

**Comment by GSPP** [comment]
I have issue "Ensure window is maximized upon restart, after window was maximized before shutdown" on v0.13.1 (64-bit) Windows 7. In fact the window is sized as if the window was maximized but it's not. The maximize button is available on the upper right. I believe there are two bugs:

1. Not remembering the maximized state.
2. Remembering the maximized window size as the restored size.

**Comment by vajdaz** [comment]
I played a bit and found an issue when restoring the window from the system tray on Windows. After minimizing or closing into the tray, the window always restores to minimized state. I think, I have a fix for this. Would be my first contribution ever, any help/advice about how to proceede is welcoeme. I have to test my fix on Linux before publishing into my fork.

**Comment by MarcoFalke** [comment]
@vajdaz Pull request are welcome. If you need help/advice, you might want to check the README.md and CONTRIBUTING.md or ask on the bitcoin-core-dev irc.

**Comment by hebasto** [comment]
Is this still an issue?

**Comment by MarcoFalke** [comment]
Closing for now. This is a list of issues, where all (or at least some of them) have been fixed. If any of the issues still persist or resurfaced, please open a new report, referencing this one.
