### ISSUE TITLE
No error reporting when pkg-config missing in depends build

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8228]
I was building on a fresh Ubuntu 14.04 VM. Apparently I forgot to install PKG_CONFIG.

```
cd depends
make HOST=x86_64-w64-mingw32 NO_QT=1 NO_UPNP=1 -j6
cd ..
./automake.sh
./configure --enable-reduce-exports --prefix=`pwd`/depends/x86_64-w64-mingw32
make -j10
```

The linking step subsequently failed with an error about missing symbols. The immediate cause was trivial: ` -levent -lopenssl` wasn't being passed to the linker.

After investigating somewhat deeper it appears this is a result from missing `pkg-config`.
AFAIK the only indication of an error was during configure:
```
./configure: line 17775: PKG_PROG_PKG_CONFIG: command not found
```
However, this was not fatal so I missed it the first time around. It should be a fatal error.

After installing the `pkg-config` package and re-running `autogen.sh` and `configure`, everything is working as expected.

**Comment by paveljanik** [comment]
I'll take care of this, together with libtool checks (#7530).

**Comment by paveljanik** [comment]
```
PKG_PROG_PKG_CONFIG: command not found
```
means that the `pkg-config`'s `pkg.m4` was not installed when running `autoreconf`. This means that we have to check for `pkg-config` in the `./autogen.sh` step (in addition to the PKG_PROG_PKG_CONFIG macro itself in the `configure.ac`). How do you like this one-liner?

```
diff --git a/configure.ac b/configure.ac
index 97af58b..6007861 100644
--- a/configure.ac
+++ b/configure.ac
@@ -81,6 +81,7 @@ AC_ARG_VAR(PYTHONPATH, Augments the default search path for python module files)
 
 dnl pkg-config check.
 PKG_PROG_PKG_CONFIG
+m4_pattern_forbid([^PKG_PROG_PKG_CONFIG], [PKG_PROG_PKG_CONFIG macro not expanded, please install pkg-config])
 
 # Enable wallet
 AC_ARG_ENABLE([wallet],
```
