### ISSUE TITLE
Include more information sources in BIP152 decoding implementation

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#8243]
Right now only the memory pool is considered. But often some of the missing transactions are in the orphan pool, and could simply be used.

During reorgs, the to-be-disconnected blocks are not used, making BIP152 ineffective where it could instead be almost perfectly effective.

Mempool conflicts are also a source of misses in BIP152 currently. A simple small memory of recent mempool conflicts (perhaps feerate sorted) would greatly increase the rate of blocks with no missing transactions.

I'm just opening this issue so we don't forget to add these sources. More sources should probably be added before miss prediction, since they'll lead to better prediction of genuinely unknown transactions.

(This should be tagged p2p enhancement)

**Comment by glozow** [comment]
AFAICT this has been implemented now! `vExtraTxnForCompact` contains replaced transactions, orphans, etc.
