### ISSUE TITLE
Tx index option

### ISSUE THREAD

**Issue by benjyz** [bitcoin/bitcoin#8255]
Starting with txindex option produces a bug continually printing "y".

```
sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update
bitcoind -daemon -txindex=1 -server=1 &
root@btc:~# Bitcoin server starting
: You need to rebuild the database using -reindex to change -txindex.

Do you want to rebuild the block database now?
yes
y
y
y
y
y
```

**Comment by sipa** [comment]
You need to start again with the -reindex option passed on the command land.

It should not ask "Do you want to reindex now?", as it quits immediately
and runs in the background anyway.

Typing 'yes' in the shell runs the command yes, which has nothing to do
with Bitcoin, and just produces an infinite sequence of 'y' lines.

**Comment by benjyz** [comment]
thanks. ```bitcoind -daemon -server=1 -reindex &``` worked for me.

**Comment by laanwj** [comment]
> Typing 'yes' in the shell runs the command yes, which has nothing to do
> with Bitcoin, and just produces an infinite sequence of 'y' lines.

Hah, this is a very recognizable mistake. We should change the message in case of non-GUI somehow.
