### ISSUE TITLE
Qt 4.x EOL

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8263]
At some point we likely want to drop support for Qt4, to be able to use new Qt5 features without worrying about backwards compatibility.

Not sure when: there is no real hurry. Just wanted to have a issue open for this. This doesn't have to be 0.14. Although the number of people still testing with Qt4 is likely very low. 

The only article I could find on Qt's EOL policy was: https://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/ which is pretty old.

**Comment by luke-jr** [comment]
IMO anything like this should wait for KDE 5 to be mostly viable as an upgrade for KDE 4. At least, last I checked, that is still a bit off (but coming up fast, maybe within a year).

**Comment by laanwj** [comment]
You can't use Qt5 applications on KDE4?

**Comment by luke-jr** [comment]
Not without using native platform integration, unfortunately. :(

**Comment by luke-jr** [comment]
losing*

**Comment by laanwj** [comment]
Ok let's wait for that then.

**Comment by TheBlueMatt** [comment]
See-also #9038. The PPA was forced to revert to Qt4.

**Comment by laanwj** [comment]
> See-also #9038. The PPA was forced to revert to Qt4.

As it is a Qt upstream issue w/ Unity that is hopefully solved by now, do you know if this issue still exists for newer Ubuntu?

**Comment by da2ce7** [comment]
I think that post Bitcoin 0.16, dropping support for QT4 can be seriously reconsidered.

**Comment by Sjors** [comment]
@luke-jr what's the KDE situation these days?

**Comment by luke-jr** [comment]
KDE 4 is basically dead nowadays.

AFAIK the only reasons to keep Qt4 support are "because why not" and some PPA issue (unless that's been resolved?).

**Comment by TheBlueMatt** [comment]
I'm not aware of any changes that would allow us to reconsider dropping Qt4 support. Ultimately we probably can't do that until we drop the tray bar icon (which is probably a thing we should do anyway, its a pretty strange thing to have anymore, AFAIU).

**Comment by flack** [comment]
Maybe I'm old-fashioned, but I seem to have a number of tray icons from apps on all the OSes I use, and I never had any real issues with them. Is the problem specific to Unity and/or a particular version? I can't quite make that out from the linked tickets

**Comment by laanwj** [comment]
Yes, it is specific to the interaction of unity and tray icons (which requires a plugin to work properly, which has been broken for a long time and will never be fixed). With any other window manager there should be no problem.

If that's really the only thing holding this back, maybe we should add a configure option so that @TheBlueMatt can disable the tray icon for PPA builds.

**Comment by laanwj** [comment]
Tentatively moving this to 0.17.0, given that we can address @TheBlueMatt 's issue in one way or another.

**Comment by TheBlueMatt** [comment]
Well we can at least deprecate it in 2021 when 16.04 LTS isnt supported anymore :/.

**Comment by laanwj** [comment]
That's fine, whatever you want, but we're not going to wait that long to deprecate Qt4, just because of a minor annoyance with a small detail in the GUI on some distros.

**Comment by laanwj** [comment]
From what I read in the quassel IRC channel, apparently Gentoo is going to drop Qt4 support very soon.
Other distros will likely follow.

**Comment by Sjors** [comment]
Given how few people are working on QT, not having to think about Qt4 would probably speed up UI development. It's still a cause for confusion e.g. https://github.com/bitcoin/bitcoin/pull/12723#issuecomment-396656176 

I'd also prefer to kill it in 0.17 and deal with "minor annoyance with a small detail in the GUI on some distros" directly if someone can turn those into Github issues.

**Comment by jonasschnelli** [comment]
I'm in favour of dropping Qt4 support completely (for 0.17). It may restrict the possible OS set. The try icon issue (https://github.com/bitcoin/bitcoin/issues/9038) seems to be fixed.

Since this obviously only affects the GUI part (and not bitcoind), I think limiting (very little to none in future) the possible OSes seems acceptable.
