### ISSUE TITLE
Versionbits should have an ignore button

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#8266]
It should be possible to configure a node to ignore particular versionbit activations and not warn about them-- because they're not relevant to you.

Config could be something like:
vbaddignore=5:806400   # bit:height 

It should also be possible to preset ignores as network parameters.

Testnet now has a testcase for this as there a long run of blocks with undefined bit 28 set.

It'll be useful to have this in place ahead of the wallet making use of VB warnings in the future (e.g. hiding unconfirmed txn and delaying confirmation indicators when a warning is active).

**Comment by dcousens** [comment]
Does the `height` exactly correlate with the BIP9's `starttime` or is it a generic parameter to ignore only from a particular point in time?

**Comment by gmaxwell** [comment]
It must be either the lock-in time or activation time (I don't care which, they're the same but for the 2016 block offset). It would ignore only that particular use of the bit, if the same bit is recycled and used again, it should still warn.

So it's more like a "not after" rather than a not before. Right now the bip9 logic warns forever once an unknown bit is activated. So this proposes the ability to ignore a specific activation event (which is a height/bit or blockhash/bit pair), but continue to warn on future activation events using that bit.

This lets you look at it and go "oh, this is OP_CHECKSPATULAVERIFY, I don't care about that, won't impact my usage... ignore"   but later when MULCHBABIES softfork happens on the same bit, you'll get warned again and be able to respond with a pitchfork.

**Comment by pinheadmz** [comment]
I think this issue can be closed since the warnings were removed in https://github.com/bitcoin/bitcoin/pull/15471
