### ISSUE TITLE
Feature Request: Multisig transactions

### ISSUE THREAD

**Issue by destenson** [bitcoin/bitcoin#8267]
I would like to propose that Bitcoin add the concept of multi-signature transactions (in addition to multisig wallets). A multi-signature transaction would be a transaction that requires the valid signature of all parties involved before it is actually committed to the blockchain as a valid transaction. A requester or recipient could be any valid address, not just multi-signature wallets. The transaction can be initiated by either the payer or the payee.

Requests for payment can be initiated by party A with a valid signature (or all required signatures if initiated by a multisig wallet) & when party B also signs the request, the actual transfer of funds from B to A will occur like a normal transaction. This will add invoicing as an intrinsic feature to Bitcoin.

Outgoing payments to a third-party can also be multisig. In that case, the request is for acceptance of payment, and the transfer is completed when the recipient signs the transaction. Since the transfer is not valid until all parties sign, this allows the funds for the transaction not to be committed until the recipient accepts the payment. If funds are not available when the transaction is adequately signed, it will be rejected by the blockchain due to insufficient funds. A signatory can also rescind their signature before the transaction is accepted by all parties. This allows a fund transfer to be cancelled before payment is accepted. This is a feature that is missing from all major cryptocurrencies.

**Comment by MarcoFalke** [comment]
Usually the issue tracker is used to track issues related to the Bitcoin Core code base. You may reach more people via a mailing list: https://github.com/bitcoin/bitcoin#development-process.

**Comment by jonasschnelli** [comment]
Thanks for submitting your multisig transaction idea. The place to discuss such changes is the bitcoin-dev [mailing list](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev).
Closing.
