### ISSUE TITLE
libressl is detected even if openssl is selected on openbsd w/ 0.11

### ISSUE THREAD

**Issue by ChoHag** [bitcoin/bitcoin#8269]
https://github.com/bitcoin/bitcoin/pull/6729/commits/88458c5d747dd2d474d0deba4352702fde99d90f was not merged into 0.11 and ./configure aborted due to detecting libressl even though I'd installed and pointed ./configure to openssl (by abusing configure.ac's pkg-config detection in my case though setting SSL_(CFLAGS|LIBS) would have the same effect).

**Comment by MarcoFalke** [comment]
If #6732 qualifies as bugfix, you can try to backport it and open a pull

**Comment by luke-jr** [comment]
@MarcoFalke It doesn't. 0.11 cannot work with LibreSSL.

@ChoHag I don't think we have any BSD devs on the project. Care to contribute more information and/or a fix?

**Comment by sipa** [comment]
Since BIP66 I am much less worried about LibreSSL vs OpenSSL, though.

**Comment by laanwj** [comment]
Oh do it refuses to configure with libressl? Ok, yes, definitely backport #6732
