### ISSUE TITLE
bench_bitcoin: Build system updates needed

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#8292]
bench_bitcoin isn't checked for in at least one important point: determining boost necessity.

Symptom is that a lib+bench build will fail due to not having a boost sleep implementation.

**Comment by laanwj** [comment]
Would be nice to have a script that checks all combinations of configure flags and builds for them.
Nah, we already have that, called @luke-jr :-)

**Comment by laanwj** [comment]
Closed by #8310
