### ISSUE TITLE
Mining updates for 0.13.0

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#8294]
There's a few mining-related to-do's that I thought we should track for the 0.13.0 release, so that we hopefully can avoid dealing with last-minute surprises.

* [x] Segwit's merge has disabled the ancestor feerate mining algorithm by default, unless miners start using the new `-blockmaxcost` argument instead of `-blockmaxsize` or set `-blockmaxsize > 3999000`.  This is because the size-accounting required by `-blockmaxsize` hasn't been added to the package-selection code yet (which is optimized for fee per "block cost", aka "virtual size").   I plan to address this in a PR shortly by adding the size-accounting to the package-selection code. [#8295]
* [x] I noticed that `-blockminsize` is not supported by the package selection code.  This is something that of course could be added, but this seems like a feature that may not be relevant to anyone anymore.  Can we just remove this command line argument?
 EDIT: from discussion on IRC, seems like the best path forward will be to get rid of the argument, but warn users if they try to set it. [#8295]

* [x] Should we remove the old transaction selection algorithm, `addScoreTxs()`?  I believe that the new package selection algorithm is strictly superior to the old algorithm, but it is of course new code that has not received the battle-testing in production environments that the old algorithm has received.  Nevertheless, if we don't plan to add a way to enable the old algorithm, it seems to me like there's little reason to leave the dead code lying around -- we can always resurrect it from git history if we need to.  
My suggestion would be to remove it, but if someone else is interested in adding support to enable it from the command line, that seems fine too. [#8295]

* [x] We need to update the release notes -- description of the ancestor feerate mining algorithm and command line option changes (`-blockmaxcost` and its interaction with `-blockmaxsize`, and removal of `-blockminsize` if we choose to remove it). [#8374]

* [x] Improve the `--help` text for the `-blockmaxcost` option.
  Maybe we can cite the BIP where this is defined, perhaps combined with not translating the term "block cost" which is defined in the BIP? [#8363, #8359]

**Comment by luke-jr** [comment]
Why does CPFP depend on size/cost limits? I would think it would work just the same, simply with the block creation finishing at a different point?

**Comment by sipa** [comment]
@luke-jr Simply because ancestor accounting for vsize/cost is implemented, but not for bytes. It's easy to fix, and if we want to, we should.

**Comment by sdaftuar** [comment]
I attempted to address the first 3 items in #8295.

If we do end up removing `addScoreTxs()` then we can also remove the "mining_score" index from the mempool's multi_index, mapTx.  Anyone have thoughts on that?  Also it's not clear to me whether anyone has a preference on removing code like this for 0.13, or after 0.13 is branched off (I don't feel strongly either way).

**Comment by mcccs** [comment]
> Speaking of hard forks, wonder how /u/luke-jr is doing on the 2MB hard fork code that was promised to miners within the next 10 days. Greg Maxwell incredibly hasn't the slightest idea about the progress of one of Blockstream's contractors and his fellow developer.
This was promised to miners many months ago. Can't wait to see another empty promise broken.

[Reddit Comment](https://www.reddit.com/r/btc/comments/4tvw5y/hardforks_did_you_know/d5kr222)

@luke-jr Is that correct or just rumor? Will 2 MB blocksize come in 13.0 update?

**Comment by sipa** [comment]
Anyone is free to make proposals about hard forks, and Bitcoin Core will
adopt proposals that are uncontroversial to the community.

This discussion should be held with a wider audience (for example, the next
Scaling Bitcoin conference that was recently announced), but is off topic
on the issue tracker for a single implementation.

**Comment by sdaftuar** [comment]
Closing now that all tasks have been completed.
