### ISSUE TITLE
"Activating best chain..." issue is back (implied fixed in #7038)

### ISSUE THREAD

**Issue by clovermebitcoin** [bitcoin/bitcoin#8299]
This issue has returned: https://github.com/bitcoin/bitcoin/issues/7038
It was implied it was fixed by moving the function to ThreadImport

However, in v0.12.1, "Activating best chain..." appears on the splash screen and can take upwards of 20 minutes before the wallet screen appears.

**Comment by MarcoFalke** [comment]
You will see #7917 in the upcoming release 0.13.0: https://github.com/bitcoin/bitcoin/issues/7679#issue-140647661

This feature won't be included in the 0.12 branch.

**Comment by laanwj** [comment]
Yes, it was never fixed in the 0.12 series, and will not be either - it was not a simple fix but a restructure of the code.
