### ISSUE TITLE
Network Traffic while starting

### ISSUE THREAD

**Issue by mcccs** [bitcoin/bitcoin#8301]
https://drive.google.com/open?id=0B4tqQioIpV0yYWUtRDRKTnhQRzQ

You see, if you click Network Traffic while the client is starting, it crashes.

**Comment by pstratem** [comment]
Hello please do not link to google docs, it's been used heavily for phishing in the past.

Images can be directly uploaded.

**Comment by mcccs** [comment]
It's an MP4 file, how about YouTube?
https://youtu.be/433Lqm09k8o

**Comment by MarcoFalke** [comment]
This was fixed in #8042
