### ISSUE TITLE
[wallet] {dump,import}wallet incompatible with HD

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#8308]
I am assuming dumpwallet and importwallet no longer work when `-usehd` is set. This should be mentioned somewhere because it may not be obvious.

**Comment by MarcoFalke** [comment]
Apparently there is already something ready for review: #8206

**Comment by laanwj** [comment]
That's a good point.

`importwallet` could somewhat-work, I don't think the hd wallet forbids importing keys?

**Comment by jonasschnelli** [comment]
`importwallet` works in conjunction with HD and IMO it does exactly what it should (importing a wallet/keys but not importing the hd seed). The later could be discussed.

One could "import" multiple wallets and I think re-activatig the HD seed would be wrong in this case.

**Comment by MarcoFalke** [comment]
> One could "import" multiple wallets and I think re-activatig the HD seed would be wrong in this case.

I feel like it should be at least documented that HD-seeds are not activated. This may not be obvious to everyone.


Something nice to have for 0.14: Warn when importwallet finds a HD seed, because it can not be activated in neither case. Having your current wallet be a legacy wallet, it would be not intuitive to suddenly switch to a HD wallet; And having your current wallet be a HD wallet, you can not import another HD seed...

**Comment by sipa** [comment]
We could also just write the HD seed to the dump...

**Comment by jonasschnelli** [comment]
> We could also just write the HD seed to the dump...

https://github.com/bitcoin/bitcoin/pull/8206 does that.
