### ISSUE TITLE
Allow removing/expiring or firewalling bitcoin addresses

### ISSUE THREAD

**Issue by RHavar** [bitcoin/bitcoin#8338]
Having un-needed bitcoin addresses presents a privacy problem in bitcoin core's wallet, because they can be sprinkled with (possibly dust) amounts of money, and when that money gets (automatically)  spent, it provides lots a lot of extra information that can be used to cluster/analyze the wallet.

Bitcoin services that need extra privacy (and use bitcoin core) tend to get around this by periodically rebuilding an entire new wallet (which is a pain in the ass). My preferred solution to the problem would be a simple: `bitcoin-cli removeaddress $addr` which could both tackle the privacy problem as well as wallet bloating over time

**Comment by laanwj** [comment]
There has been much previous discussion on this topic, for anyone starting on an implementation I'd suggest reading these first:

- #1653 Ability to freeze / erase private keys
- #3314 Exposed / Compromised (must sweep) / Used / Imported (?) flags on addresses
- #8338 Ability to hide/delete receive addressess
- #5525 Add removeaddress RPC call (remove watch-only address)
