### ISSUE TITLE
Outstanding cpp11 refactors

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#8350]
There <strike>are some</strike> is one place in the code:
- https://github.com/bitcoin/bitcoin/blob/559fbae8c658c779a423201df6d5850fce3cd3b1/src/scheduler.h#L10

Just going to drop this here as "easy to implement".

**Comment by yurizhykin** [comment]
There's also this note in `scheduler.h`:
https://github.com/bitcoin/bitcoin/blob/559fbae8c658c779a423201df6d5850fce3cd3b1/src/scheduler.h#L10
Should it be included too?

**Comment by MarcoFalke** [comment]
Sure, go ahead.

**Comment by yurizhykin** [comment]
@MarcoFalke Grepped a bit and I think it should be moved to a separate issue, as it seems to require lots of changes throughout the codebase.

**Comment by opg7371** [comment]
Is this issue still open...can you give me more details of what i need to do? I am new to bitcoin

**Comment by MarcoFalke** [comment]
I think there is already a pull open to fix those

**Comment by fanquake** [comment]
Closing this, as it will be taken care of in #8631
