### ISSUE TITLE
zombie coins - an issue with my old unconfirmed transaction

### ISSUE THREAD

**Issue by altar13** [bitcoin/bitcoin#8368]
When you check my wallet: https://blockchain.info/address/13XPgmeBu1dFWwXM321L5V3qKDLR7CP3Qd I should own some money but in reality all this bitcoins are locked in never ending unconfirmed transaction. How to deal with this kind of issues in the bitcoin core app? Is there any way to cancel unconfirmed transactions, edit, double spend or mine it by myself, anything that could help me to restore the control of my bitcoins? Is there any expiration time or my zombie coins can hang forever in the network? btw, I created this tx one month ago but receiving time from the network is fresh: https://www.localbitcoinschain.com/tx/33cfd21d6003acb420be90e6692e7bb75b6fc86e54ff0c97dc429afba64645e5 wtf? The bitcoin core automatically rebroadcast it or what?

![btcmain](https://cloud.githubusercontent.com/assets/20534833/16947294/94e4a426-4dae-11e6-8722-94bf47301beb.jpg)
![tx](https://cloud.githubusercontent.com/assets/20534833/16945960/aa429230-4da7-11e6-9eaf-97d097647f22.jpg)

**Comment by MarcoFalke** [comment]
A fee rate less than minRelayTxFee is usually <sub>(always)</sub> rejected by miners on mainnet.

**Comment by altar13** [comment]
But what exactly it means, your money are lost forever? If you have to much money than instead of burning it you can send it to bitcoin network with 0fee?

**Comment by MarcoFalke** [comment]
No, the transaction likely only exists in your local mempool and the mempools of some block explorers. 

You can just send out a double spend with proper fee.

**Comment by altar13** [comment]
but how to make this double spend in the bitcoin core app, is there any tutorial available, command line hack, anything? Whenever I try to make a new transaction I've got an error: "The amount exceeds your balance"  :/

**Comment by jpdffonseca** [comment]
Instead of double-spending the tx, wouldn't `abandontransaction 33cfd21d6003acb420be90e6692e7bb75b6fc86e54ff0c97dc429afba64645e5` and then restart the wallet make this coins available again?

**Comment by MarcoFalke** [comment]
abandontransaction only works on transactions which are not included in a block and are not currently in the mempool.

**Comment by MarcoFalke** [comment]
@altar13 You could try [zapwallettxes](http://bitcoin.stackexchange.com/a/22365).

**Comment by rebroad** [comment]
I think this issue helps to highlight that this could be made far easier for users to resolve. The fact that people keep raising issues for this suggests that a long-term fix (in terms of user experience) still needs to be made.

**Comment by MarcoFalke** [comment]
@rebroad You can help by reviewing #8456, which is a small step towards solving the problem.
