### ISSUE TITLE
Build with selfrando ASLP enabled

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8370]
See the tweet from isislovecruft - https://twitter.com/isislovecruft/status/755385447585546241

https://www.ics.uci.edu/~perl/pets16_selfrando.pdf

https://github.com/immunant/selfrando

**Comment by laanwj** [comment]
Yes, this would be a good thing. Above all on Windows where I've noticed that the current ASLR does a bad job (#8248)

**Comment by yurizhykin** [comment]
Tested building manually, simply wrapping `make` invocation with `srenv` and used some hardening checks, but maybe something specific needed? And also, should it be integrated into build system, (e.g. `./configure --with-selfrando=/path/to/selfrando/tools/srenv`)?

**Comment by laanwj** [comment]
For comparison, these are the gitian descriptors that Tor uses:

https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitian/descriptors/linux?h=hardened-builds

**Comment by theuni** [comment]
Mmm, hesitant concept ACK. The tooling looks pretty unsophisticated. Maybe we could hack this in for windows/linux64 as a first step. If there's interest here, I could ping upstream and see if they're interested in helping to improve it. A gold plugin, maybe?

**Comment by fanquake** [comment]
Going to close for now. It's not clear that selfrando is being actively worked on / maintained: https://github.com/runsafesecurity/selfrando.

tor has also removed it from their build system: https://gitweb.torproject.org/user/gk/tor-browser-build.git/commit/?h=bug_30377_v2&id=9f2de1690a822e1933356065010378f60ea2cf2c.
