### ISSUE TITLE
High CPU usage (50%-70%+) in 0.13.0rc1 as compared to 0.12.1

### ISSUE THREAD

**Issue by mmortal03** [bitcoin/bitcoin#8398]
I've been experiencing an onset of very high, constant CPU usage of 50%-70%+ when running bitcoin-qt.exe (0.13.0rc1) on Windows 10 64-bit after letting it run for a few hours, which is much more than what I believe I was experiencing with 0.12.1. 

This is on a netbook with an AMD E-350 processor, 6 GB RAM, so it's not a fast machine at all, but I'm pretty sure I didn't see such high CPU usage on this machine with 0.12.1. I discovered the issue after running 0.13.0rc1 for a while, then noticing the netbook's fan going into overdrive.

To rule out a growing memory pool as a possibility, I tested 0.13.0rc1 with and without blocksonly, but both produced the same result. After reproducing the issue over multiple sessions running Core over the past few days (restarting Core was the only way I found to temporarily help the problem), I rolled the machine back to 0.12.1 to see if I wasn't just imagining things about 0.12.1. 

I've been running 0.12.1 again for the past couple of hours, and I've only seen the bitcoin-qt.exe process produce transient spikes up to 20%, with most process activity staying under 7%. I'll continue running this instance of 0.12.1 for another few hours to see if it eventually creeps higher like with 0.13.0rc1.

As far as any non-default settings that I'm using, I have maxuploadtarget set to 144. Everything else is set to defaults. I can disable maxuploadtarget=144 to rule it out as an issue, if necessary.

The copy of 0.13.0rc1 that I installed was the unsigned version from https://bitcoin.jonasschnelli.ch/releasebuilds/v0.13.0rc1/bitcoin-0.13.0-win64-setup-unsigned.exe
(2016-07-19 14:49)

If I can't produce the issue on 0.12.1, I'll re-install 0.13.0rc1 using the official binary, if you think that will make any difference.

**Comment by mmortal03** [comment]
Ha, so two hours and 30 minutes in, and 0.12.1 is doing it, too. Well, I guess I was just imagining things.

**Comment by sipa** [comment]
During initial synchronization, the aim is that the software uses 100% CPU.
If it is using less, it means it's not working as fast as it can (perhaps
due to not being able to downloads blocks fast enough from the network, or
the access to the database on disk is slow.

**Comment by mmortal03** [comment]
This is actually on an already synced client, but, like I said, now I'm seeing it on 0.12.1 as well. 
I don't know if such CPU use is to be expected once synced, and now I'm just surprised that I hadn't noticed it sooner. I'll have to run some further tests and see if I can narrow down when the higher CPU usage kicks in.
