### ISSUE TITLE
Cookie auth picks passwords which are incompatible with some URL parsers

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#8399]
Looks like the python bitcoinrpc authproxy stuff uses python "urlparse" that chokes on "/" in passwords.

AFAICT (?) it's python that is in the wrong here, but broken httpauth handling is common.

I used base58 encoding for the old code that would provide a suggested rpcpassword when you tried to run the daemon without one.  I think base58 is free of any characters that will screw up url handling... and there are no compatibility issues with just changing what cookieauth uses.

**Comment by laanwj** [comment]
This is very odd.
The password is encoded as base64 before sending it in a HTTP header.
It should *never* end up in an URL. Where are you seeing this? Can you provide a traceback?

**Comment by laanwj** [comment]
Hmm I think I get the URL part; it's not about the HTTP protocol itself, but the endpoint is encoded in the form `http://user:pass@127.0.0.1/`.
In this case you need to url-encode the password. So this doesn't work:

    http://user:/PASS/@127.0.0.1/`

But this should:

    http://user:%2FPASS%2F@127.0.0.1/`

It can be dangerous to skip this quoting step (use `urllib.quote('/PASS/','')`).

**Comment by laanwj** [comment]
GAH, even the %2F escaping doesn't work, as Python urlparse, which is used inside that `AuthServiceProxy` constructor won't unescape it:
```python
>>> x=urlparse.urlparse("http://1234:%2F4567%2F@t%3Fest.com")
>>> x.password
'%2F4567%2F'
```
