### ISSUE TITLE
RPC getmininginfo error: integer out of range

### ISSUE THREAD

**Issue by jlopp** [bitcoin/bitcoin#8402]
Just a guess, but I think that the new 'currentblockweight' data that is returned by this endpoint may be causing issues. When I call the endpoint against a recent build from master:

```
curl --user myrpcuser --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getmininginfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
Enter host password for user 'myrpcuser':

{"result":null,"error":{"code":-1,"message":"JSON integer out of range"},"id":"curltest"}
```
Similarly, "bitcoin-cli getmininginfo" returns:
```
error code: -1
error message:
JSON integer out of range
```

**Comment by laanwj** [comment]
An overflow error during generation of JSON instead of parsing?
That's odd.

**Comment by platedodev** [comment]
> The master branch is regularly built and tested, but is not guaranteed to be completely stable. Tags are created regularly to indicate new official, stable release versions of Bitcoin Core.

**Comment by laanwj** [comment]
I've been unable to reproduce this:
```bash
$ curl --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getmininginfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
Enter host password for user '__cookie__':
{"result":{"blocks":423636,"currentblocksize":0,"currentblockweight":0,"currentblocktx":0,"difficulty":201893210853.059,"errors":"This is a pre-release test build - use at your own risk - do not use for mining or merchant applications","networkhashps":1.506995848235919e+18,"pooledtx":13390,"testnet":false,"chain":"main"},"error":null,"id":"curltest"}
```
Also I still don't fully understand how this can happen. The error `JSON integer out of range` is raised in `UniValue::get_int()` and `UniValue::get_int64()`, neither of which is called in `getmininginfo` - as it has no arguments to parse.

The only `get_int()` that is not part of a specific RPC command its input parsing is the one in `JSONErrorReply`. I suppose if something inside the call raises a JSONRPCError with an invalid "code" field, this could happen, it would be internally unable to parse its own error value. I don't see where/how this could happen though.

**Comment by jlopp** [comment]
You're right; it wasn't a bug - it was a compatibility issue with my own code. I'll be posting a related trivial documentation fix shortly.
