### ISSUE TITLE
No block sources available. Cannot find peers to sync with.

### ISSUE THREAD

**Issue by wkbaran** [bitcoin/bitcoin#8404]
Running on Windows 10. Tried re-indexing. 
Seeing this from all peers:
2016-07-25 19:26:13 ERROR: AcceptBlockHeader: block is marked invalid
2016-07-25 19:26:13 ERROR: invalid header received
2016-07-25 19:26:13 ProcessMessages(headers, 162003 bytes) FAILED peer=7
2016-07-25 19:26:16 ERROR: AcceptBlockHeader: block is marked invalid

At a loss as what else to do.

./bitcoin-cli.exe getchaintips
[
  {
    "height": 348252,
    "hash": "000000000000000005638f0a958f0f0b3ef6c490c616905dc8b5d9db6efb3f03",
    "branchlen": 1,
    "status": "invalid"
  },
  {
    "height": 348251,
    "hash": "0000000000000000074e2fda8c5aab7c36d1955cdbb22285ffb0aeddff52ed71",
    "branchlen": 0,
    "status": "active"
  }
]

./bitcoin-cli.exe getinfo
{
  "version": 120100,
  "protocolversion": 70012,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 348251,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 47427554950.6483,
  "testnet": false,
  "keypoololdest": 1469296192,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}

Can you point me in any direction at all? Thanks.

**Comment by NicolasDorier** [comment]
This can happen if you initially synched with one version of bitcoind which rejected this block, then tried again with another version.

Were you always using the same version of bitcoind on your data folder ?

**Comment by NicolasDorier** [comment]
Also, did you built bitcoind yourself or is just using the binaries of bitcoin.org ?

**Comment by wkbaran** [comment]
Oh that might explain it. I'm just using binaries but I started with Bitcoin Unlimited. I don't think I switched over to Core until after BU seemed stuck.
I'll nuke my data, restart with core and follow up. Thanks.

**Comment by jl2012** [comment]
interesting. Why BU would reject 000000000000000005638f0a958f0f0b3ef6c490c616905dc8b5d9db6efb3f03 ? Do they have a consensus bug?

**Comment by wkbaran** [comment]
I've restarted fresh with core and I'm back to my original problem of being stuck due to no block sources being available. I'm at 320025, Sep 10 '14, 11:57:39
I've confirmed that upnp is working and I can be connected to externally.
I've tried ejecting peers slower than 500ms and then all to try and get a fresh list.
Debug log is only reporting peer connections.
I think I'm seeing the issue tho. The peers are either not starting at block 0, or are providing no services.
All I found online told me to reindex which is what started this.

**Comment by sipa** [comment]
Can you try deleting your peers.dat file, and restart?

**Comment by wkbaran** [comment]
Same. The peers that provide services report a starting block of 422393 or later.

**Comment by sipa** [comment]
Note that starting block means "Block height this peer reported when this
connection started". It does not mean "first block this peer has". Peers
with NODE_NETWORK can provide all blocks, the rest can't provide any.

**Comment by NicolasDorier** [comment]
I think this problem of not finding peer is different from the previous problem. The previous problem might have been a consensus bug from BU, this one seems of different nature.

@wkbaran do you still see the error
```
2016-07-25 19:26:13 ProcessMessages(headers, 162003 bytes) FAILED peer=7
2016-07-25 19:26:16 ERROR: AcceptBlockHeader: block is marked invalid
```

**Comment by wkbaran** [comment]
Yes @NicolasDorier this is a different issue. Should I create a different ticket?

@sipa Thanks for the explanation. I don't see any peers with NODE_NETWORK, just NETWORK. Is this the same? I'm slowly making my through the dev docs.
I started from scratch with 0.12.0 and am now stuck at block 294294
Would it be worth trying 0.11.x?

**Comment by NicolasDorier** [comment]
I think you should create a new ticket, people reading this issue will get confused.

**Comment by wkbaran** [comment]
Done.
https://github.com/bitcoin/bitcoin/issues/8411
