### ISSUE TITLE
User-friendly way to import backupped wallet

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8405]
We have a 'backup wallet' option in the menu. However, we don't have a 'restore wallet'.

There are some difficulties here:
- Requires a partial rescan (= trouble with pruning)
- If no keys have been used in the current wallet, it could simply replace the current wallet. However if the current wallet was already used, it is more complicated:
  - It could refuse in this case
  - Move the old wallet out of the way
  - Or try to perform a merge

This may have be easier with multi-wallet support, where it could copy the backup into the data directory and open it as extra wallet.

See also #7675.

**Comment by jonasschnelli** [comment]
Its getting even more complex if you "restore" a HD wallet. What you need to do is generating an undefined amount of pubkey/addresses (lookup window) and rescan the blockchain (maybe only from block ~430'000 where we have launched 0.13). If one of the last 10 addresses where still be used for receiving funds, you probably should add another 1000 addresses and rescan again.

Or let the user configure/select how many addresses he wants to restore...

**Comment by MarcoFalke** [comment]
@laanwj Is this still an issue, now that we have multiwallet?

**Comment by laanwj** [comment]
No, not specifically. I think there's still ways that wallet management can be improved, but I don't think this is an issue worth keeping open.
