### ISSUE TITLE
0.13.0rc1: bitcoin-qt db cache not increased to 300 MB on upgrade from 0.12.1

### ISSUE THREAD

**Issue by harding** [bitcoin/bitcoin#8406]
When upgrading from 0.12.1 to 0.13.0rc1, bitcoin-qt continues to use a db cache of 100 MB although the [release notes](https://github.com/bitcoin/bitcoin/blob/0.13/doc/release-notes.md#database-cache-memory-increased) lead me to expect that it should be set to 300 MB:

![2016-07-26-05_15_43_281919898](https://cloud.githubusercontent.com/assets/61096/17132560/50cd79ce-52f0-11e6-8058-b9711f804caa.png)

**Steps to reproduce**

Platform: Debian 8 guest on Xen (QubesOS) host; uname: `Linux debian-8-dvm 4.1.13-9.pvops.qubes.x86_64 #1 SMP Thu Feb 11 15:46:02 UTC 2016 x86_64 GNU/Linux`

1. On a fresh Debian 8 install
1. Download https://bitcoin.org/bin/bitcoin-core-0.12.1/bitcoin-0.12.1-linux64.tar.gz
1. Untar and run `bitcoin-0.12.1/bin/bitcoin-qt -maxconnections=0`
1. Open settings screen; note that db cache set to 100 MB (as expected for 0.12.1)
1. Close 0.12.1
1. Download https://bitcoin.org/bin/bitcoin-core-0.13.0/test.rc1/bitcoin-0.13.0rc1-x86_64-linux-gnu.tar.gz
1. Untar and run `bitcoin-0.13.0/bin/bitcoin-qt -maxconnections=0`
1. Open settings screen; note that db cache still set to 100 MB (see screenshot above)

**Expected behavior**

Since I never changed any settings in 0.12.1 away from their defaults, I'd expect them to be upgraded to the new defaults.

**Notes**

I suppose there's a case to be made for not automatically changing any setting specified in the configuration dialog once the user has seen it.  If that's the intended behavior, then please feel free to close this issue (and accept my apologies for taking up your time).

**Comment by sipa** [comment]
I assume this is due to the dbcache setting being overridden by the setting
in the GUI.

I wonder how. I guess it would require an explicit "if previous setting was
100, change it to $default instead... but keep storing it as 100".

**Comment by jonasschnelli** [comment]
I'll check this.
In the meantime @harding: could you try running the Bitcoin-Qt with `--resetguisettings` and see if it sets back the dbache to 300?

**Comment by harding** [comment]
@jonasschnelli Restarting with `bitcoin-0.13.0/bin/bitcoin-qt -maxconnections=0 --resetguisettings` does indeed set the dbcache to 300.

**Comment by jonasschnelli** [comment]
Unfortunately, the GUI stores the default values in its own GUI settings file (managed through Qt).
https://github.com/bitcoin/bitcoin/blob/0.13/src/qt/optionsmodel.cpp#L90

Changing the default value of `-dbcache`, `-par`, `-upnp`, `-listen` will not make its way into the GUI.

We could (and probably should) add some simple migration code where we explicit check if the dbcache value is 100 during the first start of 0.13 GUI, if so, we bump to the new default and remember that the check/firststart has been done.

**Comment by laanwj** [comment]
Fixed by #8407
