### ISSUE TITLE
Cannot complete sync for new node. Reporting no block sources available.

### ISSUE THREAD

**Issue by wkbaran** [bitcoin/bitcoin#8411]
I've tried with version 0.12.1 and 0.12.0 cannot finish sync. It keeps getting stuck with about 2.5 to 1.5 years to go. This is using the Windows 64bit binaries.
I've verified upnp is working and I can be connected to externally.
I've attempted to eject slow peers and the entire list to get new ones. I've also deleted my peers.dat to get it regenerated.
I've reindexed.
The debug log file doesn't report anything negative and generally only includes notifications of peers connecting.
I have peers that provide the services NETWORK and BLOOM.
Is there anything else I can try?

**Comment by sipa** [comment]
Can you post the output from RPCs `getchaintips` and `getpeerinfo`? You can
use bitcoin-cli if you're running bitcoind or bitcoin-qt in server mode, or
the debug console in bitcoin-qt.

**Comment by wkbaran** [comment]
Fwiw, I've restarted the node multiple times now.
Wouldn't let me attach as json. Let me know if you'd like them zipped.
`[
  {
    "height": 422512,
    "hash": "000000000000000001d4563054004ac901876bff14c5a6a97e01c02664198bf7",
    "branchlen": 128216,
    "status": "headers-only"
  }, 
  {
    "height": 294296,
    "hash": "0000000000000000b7a12a4c2e77b71d6938ce3489eb44a36757d362ac2705ac",
    "branchlen": 0,
    "status": "active"
  }
`

`[
  {
    "id": 1,
    "addr": "84.125.96.47:8333",
    "addrlocal": "67.60.48.28:50396",
    "services": "0000000000000005",
    "relaytxes": true,
    "lastsend": 1469650181,
    "lastrecv": 1469650181,
    "bytessent": 17426,
    "bytesrecv": 204513,
    "conntime": 1469649962,
    "timeoffset": -1,
    "pingtime": 0.563988,
    "minping": 0.563988,
    "version": 70012,
    "subver": "/Classic:1.1.0/",
    "inbound": false,
    "startingheight": 422511,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": 294296,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 3,
    "addr": "91.121.25.211:8333",
    "addrlocal": "67.60.48.28:50401",
    "services": "0000000000000001",
    "relaytxes": true,
    "lastsend": 1469650179,
    "lastrecv": 1469650179,
    "bytessent": 14511,
    "bytesrecv": 144843,
    "conntime": 1469649969,
    "timeoffset": -238,
    "pingtime": 0.205452,
    "minping": 0.205452,
    "version": 70002,
    "subver": "/Satoshi:0.10.2/",
    "inbound": false,
    "startingheight": 422511,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": 294296,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 4,
    "addr": "142.4.211.100:8333",
    "addrlocal": "67.60.48.28:50402",
    "services": "0000000000000005",
    "relaytxes": true,
    "lastsend": 1469650180,
    "lastrecv": 1469650180,
    "bytessent": 20340,
    "bytesrecv": 198927,
    "conntime": 1469649970,
    "timeoffset": -72,
    "pingtime": 0.165906,
    "minping": 0.165906,
    "version": 70012,
    "subver": "/Satoshi:0.12.0/",
    "inbound": false,
    "startingheight": 422511,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": 294296,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 5,
    "addr": "192.99.5.100:8333",
    "addrlocal": "67.60.48.28:50405",
    "services": "0000000000000005",
    "relaytxes": true,
    "lastsend": 1469650169,
    "lastrecv": 1469650169,
    "bytessent": 2010,
    "bytesrecv": 92290,
    "conntime": 1469649976,
    "timeoffset": -13,
    "pingtime": 36.757002,
    "minping": 0.848646,
    "version": 70012,
    "subver": "/Satoshi:0.12.1(bitcore)/",
    "inbound": false,
    "startingheight": 392313,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 6,
    "addr": "91.134.235.4:8333",
    "addrlocal": "67.60.48.28:50406",
    "services": "0000000000000004",
    "relaytxes": true,
    "lastsend": 1469650180,
    "lastrecv": 1469650181,
    "bytessent": 28050,
    "bytesrecv": 5097278,
    "conntime": 1469649977,
    "timeoffset": 1,
    "pingtime": 0.344844,
    "minping": 0.344844,
    "version": 70012,
    "subver": "/Satoshi:0.12.1/",
    "inbound": false,
    "startingheight": 422511,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 7,
    "addr": "198.143.186.3:8333",
    "addrlocal": "67.60.48.28:50443",
    "services": "0000000000000015",
    "relaytxes": true,
    "lastsend": 1469650179,
    "lastrecv": 1469650179,
    "bytessent": 15449,
    "bytesrecv": 1196902,
    "conntime": 1469650011,
    "timeoffset": -2,
    "pingtime": 0.068954,
    "minping": 0.068954,
    "version": 80001,
    "subver": "/BitcoinUnlimited:0.12.0(EB16; AD4)/",
    "inbound": false,
    "startingheight": 422511,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": 294296,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 8,
    "addr": "54.200.14.112:8333",
    "addrlocal": "67.60.48.28:50450",
    "services": "0000000000000001",
    "relaytxes": true,
    "lastsend": 1469650180,
    "lastrecv": 1469650180,
    "bytessent": 13948,
    "bytesrecv": 97861,
    "conntime": 1469650028,
    "timeoffset": -1,
    "pingtime": 0.032364,
    "minping": 0.032364,
    "version": 70002,
    "subver": "/Satoshi:0.11.0/",
    "inbound": false,
    "startingheight": 422511,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": 294296,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 10,
    "addr": "180.150.226.116:8333",
    "addrlocal": "67.60.48.28:50469",
    "services": "0000000000000005",
    "relaytxes": true,
    "lastsend": 1469650181,
    "lastrecv": 1469650181,
    "bytessent": 2096,
    "bytesrecv": 9397,
    "conntime": 1469650142,
    "timeoffset": -1,
    "pingtime": 0.243645,
    "minping": 0.243645,
    "version": 70012,
    "subver": "/Satoshi:0.12.1/",
    "inbound": false,
    "startingheight": 422512,
    "banscore": 0,
    "synced_headers": 422512,
    "synced_blocks": 294296,
    "inflight": [
    ],
    "whitelisted": false
  }
]`

**Comment by wkbaran** [comment]
Still reporting no block sources available.

**Comment by NicolasDorier** [comment]
Can you start with `-debug=net` and check in the lock if you have better information about the messages received ?

**Comment by wkbaran** [comment]
Thanks. Net log shows plenty of traffic and some but not many rejections.
Attached is log from startup for today.
[nettrace_wkbaran_2016aug06.txt](https://github.com/bitcoin/bitcoin/files/405110/nettrace_wkbaran_2016aug06.txt)

**Comment by NicolasDorier** [comment]
Your node does not even ask for new blocks interesting, but it seems to know about the biggest chain still. Will check out.

**Comment by rebroad** [comment]
@wkbaran You're running an old (v0.12) version.. does this problem still exist with the latest (v0.13) version?

**Comment by MarcoFalke** [comment]
@rebroad 0.12.1 is currently the latest stable version. Also running an "old" version shouldn't cause any problems. I think you can get 0.8 and still sync by just letting it run long enough.

**Comment by wkbaran** [comment]
@rebroad Yes. I moved to 0.12 to see if that would fix the issue.
I'll give 0.8 a try. Thanks @MarcoFalke

**Comment by MarcoFalke** [comment]
@wkbaran Please don't. Version 0.8 is no longer supported. I solely mentioned it to illustrate the point that "old" software should still work.

**Comment by wkbaran** [comment]
Oh ok.

**Comment by brandondahler** [comment]
I'm having the same symptoms with v0.12.1-g9779e1e1 on linux (4.4.6-gentoo).  Reindexing only previously downloaded blocks.

Special installation - the blocks dir is symlinked to a NFS drive.

```
getchaintips
[
  {
    "height": 425668,
    "hash": "0000000000000000019a7e0c25edb9e81493c88fec69a326fa3e435b7fe28a77",
    "branchlen": 81611,
    "status": "headers-only"
  }, 
  {
    "height": 344057,
    "hash": "0000000000000000021cb18ec216ff9522b0ac87895041c56153cfa352f5e261",
    "branchlen": 0,
    "status": "active"
  }, 
  {
    "height": 336554,
    "hash": "00000000000000000c68c54e767c945f3e08d77208ad6ea01e3c4b41fe0778b0",
    "branchlen": 1,
    "status": "valid-headers"
  }, 
  {
    "height": 335742,
    "hash": "00000000000000000c40362958d0f1193cfb4501d17d36f31e18a1b63a772f24",
    "branchlen": 1,
    "status": "valid-headers"
  }, 
  {
    "height": 335644,
    "hash": "00000000000000001b2f46a8b4c7c0619338db4ea5643810962b961ed2a5d44a",
    "branchlen": 1,
    "status": "valid-fork"
  }, 
  {
    "height": 335464,
    "hash": "00000000000000001a131ce2cf11f52b64155de1bc8adef22a57c297f0c1d6bc",
    "branchlen": 1,
    "status": "valid-fork"
  }, 
  {
    "height": 325691,
    "hash": "00000000000000001dca095a71642fb5fa3ead2e965870451ffdf025b8ad9242",
    "branchlen": 1,
    "status": "valid-headers"
  }, 
  {
    "height": 304822,
    "hash": "0000000000000000326712413c774d233eed4cfeb97facd3c66dca7b143fd41a",
    "branchlen": 1,
    "status": "valid-headers"
  }, 
  {
    "height": 110,
    "hash": "00000000f251625ddf6d11ce65aff673129d5464418d5d26542acb0bf18590ca",
    "branchlen": 110,
    "status": "valid-fork"
  }
]

getpeerinfo
[
  {
    "id": 2,
    "addr": "195.56.63.10:8333",
    "addrlocal": "xxxxxxxxxxxx",
    "services": "0000000000000005",
    "relaytxes": true,
    "lastsend": 1471492300,
    "lastrecv": 1471492300,
    "bytessent": 19792,
    "bytesrecv": 196206,
    "conntime": 1471492029,
    "timeoffset": 13,
    "pingtime": 0.373318,
    "minping": 0.310643,
    "version": 70012,
    "subver": "/Satoshi:0.12.1/",
    "inbound": false,
    "startingheight": 425670,
    "banscore": 0,
    "synced_headers": 425670,
    "synced_blocks": 344057,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 3,
    "addr": "67.167.88.176:8333",
    "addrlocal": "xxxxxxxxxxxx",
    "services": "0000000000000017",
    "relaytxes": true,
    "lastsend": 1471492300,
    "lastrecv": 1471492300,
    "bytessent": 20149,
    "bytesrecv": 359644,
    "conntime": 1471492074,
    "timeoffset": -1,
    "pingtime": 0.134369,
    "minping": 0.134369,
    "version": 70011,
    "subver": "/Bitcoin XT:0.11.0F(Windows; x86_64)/",
    "inbound": false,
    "startingheight": 425670,
    "banscore": 0,
    "synced_headers": 425670,
    "synced_blocks": 344057,
    "inflight": [
    ],
    "whitelisted": false
  }, 
  {
    "id": 4,
    "addr": "87.236.196.222:8333",
    "addrlocal": "xxxxxxxxxxxx",
    "services": "0000000000000001",
    "relaytxes": true,
    "lastsend": 1471492297,
    "lastrecv": 1471492298,
    "bytessent": 6491,
    "bytesrecv": 72922,
    "conntime": 1471492246,
    "timeoffset": 0,
    "pingtime": 0.300367,
    "minping": 0.300367,
    "version": 70002,
    "subver": "/Satoshi:0.11.1/",
    "inbound": false,
    "startingheight": 425670,
    "banscore": 0,
    "synced_headers": 425670,
    "synced_blocks": 344057,
    "inflight": [
    ],
    "whitelisted": false
  }
]

```

**Comment by GSPP** [comment]
I just had this issue on 0.12.1. Upgrading to 0.13 did not change anything. I fixed it with `reconsiderblock "0000000000000000011c672f3731a6ba1a390331fb154d470eaf76419801d384"`. I also needed to restart the software after executing that statement. By itself it only synced one more block. Might be a bug.

**Comment by chumlee06** [comment]
i want to install the 32 bit or classic but then after verifying block it will say internal error see debug.log i don't know what to do. please fix. at first it went through until syncing process but then it shut down now that's the error.
