### ISSUE TITLE
Protocol Buffers v3.0.0 has been released

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8430]
```
v3.0.0 is the first API stable release of the v3.x series. We do not expect any future API breaking changes.
For C++, Java Lite and Objective-C, source level compatibility is guaranteed. 
Upgrading from v3.0.0 to newer minor version releases will be source compatible.
For example, if your code compiles against protobuf v3.0.0, it will continue to compile after you upgrade protobuf library to v3.1.0.
```

[Release notes](https://github.com/google/protobuf/releases/tag/v3.0.0)

**Comment by laanwj** [comment]
There seems to be no urgent reason to upgrade the depends to this, although compatibility with newer versions would be useful - if something special has to be done for that.

**Comment by GSPP** [comment]
Serialization formats implemented in unmanaged code are prone to security issues. It seems best to wait for stabilization.

**Comment by laanwj** [comment]
In case we can't support protobuf 3 (for now) it would be a good idea to add an explicit error to the build system. People keep stumbling on this, as currently there is no clear indication what is the problem, see e.g. #8869.

**Comment by fanquake** [comment]
Going to close this now.

Protobuf 3.x is supported in master, after #9366, and the build-docs were updated to reflect that in #9467.

The 0.13.x branch is still Protobuf 2.6 only (at least on OS X, and build-docs reflect that (changes made in #8754).
