### ISSUE TITLE
nLockTime option

### ISSUE THREAD

**Issue by Mendeleyef** [bitcoin/bitcoin#8431]
> nLockTime is a parameter that can be attached to a transaction, that mandates a minimal time (specified in either unix time or block height), that before this time, the transaction cannot be accepted into a block.

~ [Wiki](https://en.bitcoin.it/wiki/NLockTime)

It would be good if Core had this feature.

There should be an option in BTC Core that enables `nLockTime`.
However, it is not an often-used feature and should be enabled like this:
![screen shot 2016-07-30 at 19 15 02](https://cloud.githubusercontent.com/assets/20167871/17271654/2a364c3a-568a-11e6-8d2f-fa0b70b387f5.png)
(Typo, locktime, not lockdown)

It should ask you a date or a block height to set, if enabled.
NOTE: Also my idea: It should warn you if the block or date is a past date/block.

**Comment by gercio** [comment]
Hi :)

This option could look like below on "Send" screen:
![image](https://cloud.githubusercontent.com/assets/4302362/18002742/f186a4ce-6b89-11e6-93b4-28e11059e98e.png)

After pressing "Choose..." user will get details:
![image](https://cloud.githubusercontent.com/assets/4302362/18002785/3e4315fe-6b8a-11e6-877a-266c54213f86.png)

Rules:
1. This "Delay payment..." panel will be only visible when option **locktime** will be checked.
2. User always (in respect to 1) can chose to enable/disable delay on "Send" screen by check box.
3. On details panel it is possible to chose date/time or block number.

What do you think guys?

**Comment by mcccs** [comment]
@gercio Yes, nice idea.

**Comment by gercio** [comment]
OK, then let's do it :)

**Comment by Sjors** [comment]
Problem with nLockTime is that it's hard to broadcast these transactions, so you'd have to leave your Bitcoin node running, which seems unlikely for QT users.

It might be more useful to have a way to send coins to yourself with [CheckSequenceVerify](https://en.bitcoin.it/wiki/Timelock#CheckSequenceVerify) such that they are locked until a certain date. Obviously with plenty of warning.

**Comment by MeshCollider** [comment]
As @Sjors says, this is probably not a sensible feature for inclusion in Qt, and can be accomplished via the RPC anyway for more advanced users. By default transactions are created with a locktime set to avoid fee-sniping anyway. IMO this issue should be closed and a new one opened as a feature request to add relative locktime support to the GUI if that is something users would use
