### ISSUE TITLE
Persist mempool, arrival times, and prioritisetransaction across restarts

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#8433]
Currently the mempool isn't persisted across restarts. The historical argument against doing this is that it would make transactions immortal. Expiration now addresses that issue.

Without preserving the mempool node behavior changes drastically across restarts which complicates production use (e.g. mining overly small/low fee blocks) as well as development testing. The lack of retention also causes the loss of txn priority modifications made with prioritisetransaction which makes the API less reliable.

**Comment by dcousens** [comment]
Would it be worth doing this a constant memory-disk synchronisation effort?
Or simply as an action performed upon a user-initiated shutdown?

**Comment by gmaxwell** [comment]
I'd suggest implementing it just on shutdown and see how long it takes. If its fast with a default mempool size, I'd call that done. I think it's not critical enough to maintain that we need to sync more often, I can solicit more input from some of the other folks who mentioned wanting it.

**Comment by laanwj** [comment]
> Would it be worth doing this as a constant memory-disk synchronisation effort?

That gets closer to "mempool-on-disk" which is a completely different project with different scope.

> Or simply as an action performed upon a user-initiated shutdown?

Much less hassle to implement and low-impact. I'd say go for that.
