### ISSUE TITLE
>99% of addresses being advertised are unreachable

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8470]
According to https://bitnodes.21.co/nodes/leaderboard/#peer-index, more than 99% of the addresses my node is advertising are unreachable.  I am running the latest master (last commit ced6c940da35fcf33160d1c7f2f54a99dc7eedb1), but this seems to have been a problem for quite some time now.

**Comment by MarcoFalke** [comment]
I think @EthanHeilman already fixes this in  #8282

**Comment by rebroad** [comment]
I've made some tweaks to the code, and as a result, I managed to get my node quite easily to first place on bitnodes leaderboard despite having a less-than-ideal ASN - https://bitnodes.21.co/nodes/leaderboard/
