### ISSUE TITLE
IPv6 - Network is unreachable

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8491]
On all my servers running bitcoin core, I see that all IPv6 addresses are "network is unreachable", and I'm not sure how to fix this - is there a bug, or is this there some documentation that could be included on how to set up IPv6?

**Comment by mcccs** [comment]
If you're sure that you have ipv6 connection, you can force IPv6 using `-bind [host]:port`.

**Comment by rebroad** [comment]
Can't my node determine whether I have ipv6 by testing some ipv6 addresses that it knows will be up and if it doesn't have ipv6 then it shouldn't even be wasting time trying to connect to them.

**Comment by pstratem** [comment]
The best way to discover whether an address is reachable is to simply try.

Other mechanisms tend to return false negatives.

**Comment by rebroad** [comment]
@pstratem I agree with that statement. My suggestion is that if a type of address (e.g. IPv6, Onion) always comes back as unreachable (not connection refused), then would it not be apt to recognise that it is the network type that is unsupported rather than it simply being a coincidence. I.e. the node can learn which network types are working and therefore cease attempts to connect to network types currently unavailable.

**Comment by rebroad** [comment]
I'll explain further why I think this is an issue. Currently more than 99% of addresses advertised are unreachable and I foresee that we need to add better logic for pruning these unreachable addresses. I have various ideas in mind, but once this code is added then this would cause addressed from whole networks to be lost between nodes due to them not being able to determine that the node itself is not connected to the network (e.g. IPv6). The node therefore needs to be able to distinguish between whether the node it's trying to connect to is down, or whether it's unable to connect to all types of that address.

**Comment by pinheadmz** [comment]
I'm getting a log full of `Network is unreachable` for ipv6 addresses, as well. It would be nice if there was a `-noipv6` option.

**Comment by sipa** [comment]
@pinheadmz Try `-onlynet=ipv4`.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
