### ISSUE TITLE
In a wallet in pruned mode, show balance of imported (watch only and active) addresses.

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#8497]
If a user is not interested in the history (metadata) of his transactions, "importaddress" and "importprivkey" don't require a wallet with pruned blockchain to download the whole blockchain again (the utxo set is enough). 

As I have checked, it is possible in pruned mode to import addresses but they will only show new incoming transactions not the last UTXO value. 

When this feature is available, it becomes possible in pruned mode to import the private keys of a paper wallet into a hot wallet.

I have first discussed this issue with experts on Reddit here: https://redd.it/4w9s6q

**Comment by jonasschnelli** [comment]
But I think we should really use clear terms here.
* **"Pruned Blockchain"** is what we currently support in Bitcoin-Core with the `-prune` option.
* **"Pruned wallet"** IMO is something that would remove old wallet transaction with the goal to increase the wallet load and displayer performance (currently not implemented in Bitcoin Core)

This feature request is under the term "Pruned blockchain". I think it would be possible to use an initial balance calculated through the UTXO set. Although I'm not sure if we want to support a such feature in Bitcoin-Core. Also the missing history could confuse users, it would lead to districting imported key during pruned blockchains, labeling them different on RPC as well as on the GUI level.

**Comment by laanwj** [comment]
I think this would be a useful feature. If the user doesn't have a need for history, then a scan over the UTXO set suffices to get the balance correct for an imported/watch-only address. This is faster and works with a pruned block chain.

Agree with @jonasschnelli on the clear use of terms. And please, don't all it a "pruned wallet", the word "prune" is already over-used in bitcoin-land (ultra-prune #1677, pruned blockchains, ....). Let's find another name for limited-history wallets.

**Comment by sumBTC** [comment]
Thanks a lot and I'll be looking forward for this feature! I agree, wallet in pruned mode or limited-history wallet sounds already much better. Groeten uit Oegstgeest!

**Comment by sumBTC** [comment]
This new wallet feature would be perfect in combination with Jonas Schnelli's proposal:

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-February/012478.html

**Comment by sangaman** [comment]
I think this would be a desirable feature and would love to see it in a future release.

**Comment by sumBTC** [comment]
I get the impression this has been inplemented in version 0.17.0. Can this issue can be closed?

**Comment by gdistasi** [comment]
This is a fundamental feature. History is optional, the important thing is being able to get accurate balance and being able to spend the coins.

**Comment by jb55** [comment]
Importing wallets into pruned nodes would be an awesome feature. Surprised this issue doesn't have more activity. Going to look into what it take to code this up.

**Comment by achow101** [comment]
The current structure of the wallet does allow for this to be done. It would require a pretty significant rewrite of transaction and UTXO handling that is currently basically infeasible. As such, closing this as not planned.
