### ISSUE TITLE
Crash during synchronization after reindexing with txindex

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#8522]
I just experienced a crash:

![image](https://cloud.githubusercontent.com/assets/12032350/17698613/73a3ad74-63bc-11e6-8e05-e8635f58704b.png)

It is possibly out of memory related. Hopefully, the assertion condition can help you find the problem.

I was reindexing my blocks because I needed `txindex`. The reindex is complete at the time of the crash. The GUI shows "synchronizing with network..." at 17 weeks behind. The blocks that I was reindexing were copied from v0.11 into v0.12.1 (64-bit). The command line is `bitcoin-qt.exe  -server -rpcuser=xxx -rpcpassword=xxx -rpcbind=xxx -rpcallowip=xxx -txindex -reindex`. Before running that command I deleted `chainstate`, `database` and `db.log`.

The log shows:

```
************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
C:\Program Files\Bitcoin\bitcoin-qt.exe in ProcessMessages()       
```

So it looks like an OOM condition triggers this bug. It would be helpful if Bitcoin Core supported low memory conditions gracefully.

And now:

![image](https://cloud.githubusercontent.com/assets/12032350/17698822/8c237694-63bd-11e6-910a-ae53a0ae9640.png)

Looks like I will be rebuilding for 2 days _again_ :( For a week now I am doing nothing else because the database gets corrupted so easily. I really wish Bitcoin Core was crash consistent. This is running on a clean VM so I don't think the machine is somehow messed up.

**Comment by jonasschnelli** [comment]
I have also encountered issues when running on a windows VM and abruptly closing the VM.
IMO we should address these corruption issues with something like https://github.com/bitcoin/bitcoin/issues/8037.

**Comment by GSPP** [comment]
@jonasschnelli why is there *any* inconsistency caused by crashes at all? Crash consistency is a 101 feature of most databases. Is it misconfigured? Or should Bitcoin Core use transactions to make related actions atomic? Crashes normally are totally harmless (and that's true in the real world, not just on paper).

**Comment by sipa** [comment]
@GSPP I can't tell for sure, as I have never seen a database inconsistency on my own hardware at all, but you are not taking into account that Bitcoin Core does not use a single database.

Storing all block, transaction and UTXO data in a single database has abysmal performance, so instead data with different access patterns are stored separately. The block data (~80 GB) goes into blk* files (append-only raw disk files), the block index (63 MB) goes into a write-only leveldb database (which is loaded into memory entirely at startup), and the UTXO set (1.6 GB) goes into a leveldb database with an application caching layer on top. LevelDB internally is designed to be crash-consistent, and we enable the features that are needed for this (batch writes, which are atomic, and rollback of incomplete transactions on crash recovery).

The problem occurs across the three datasets and cached. Bitcoin Core is designed to keep them perfectly consistent with eachother: we never write to the block index without flushing writes to the blk* files, and we never write UTXO entries to the chainstate database before the block index entries are flushed to their database.

Presumably, there is a bug in the handling of fatal errors (low disk is one of those), which causes an inconsistency to occur. That's bad, and should be fixed, but it's not nearly as easy as enabling a feature on a database.

As @jonasschnelli, some of the code dealing with this was changed significantly in the 0.13 codebase (which is likely to be released within a few days). It would be helpful if you can see if the problem persists.

**Comment by sipa** [comment]
@GSPP I just realized you are experiencing an OOM, not a low disk, which aborts the application immediately. In that case, I have no answer, as that's purely an issue within LevelDB. Perhaps the Windows backend for LevelDB we're using has bugs, or there is a bug in how the VM deals with ordering of disk writes and flushing them.

**Comment by GSPP** [comment]
OK. It sounds like each database itself should be crash consistent and by always writing in the correct order there never should be any inconsistency even in the face of power loss. Is that understanding correct (modulo bugs)?

Did you have a chance to try to reproduce https://github.com/bitcoin/bitcoin/issues/7233? For me the repro is really easy and it might surface the same underlying bug.

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
