### ISSUE TITLE
Prioritize Transaction Simplification Wrapper

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#8529]
Several miners and pool operators have, at various times, requested a prioritizetransaction API, or have requested that the current one be made more accessible. Right now the flow to use it requires that you write a program which interogates mempool and finds transactions to prioritize for some use-cases.

While I think the API is sufficient, it would be nice to have a simple python wrapper which could, for example, completely emulate the old priority mechanism (then we could remove it wholesale :p).

We might also add a way to prioritize while submitting a transaction, but this wrapper could easily provide that as well as a demonstration (IIRC you can currently do it by prioritizing the hash and then submitting the transaction).

**Comment by laanwj** [comment]
How is this different from the `prioritisetransaction` RPC call?

**Comment by sipa** [comment]
I'm confused about the use case.

Prioritizetransaction maps perfectly to a model where a small number of transactions are paid for out of band - not something that requiring inspecting the mempool for all transactions and recalculating things. If someone feels the need to do that, they're obviously using it in a way that's not currently being discussed here, so I'd like to know the goal.

I also think that trying to reimplement the old prioritization mechanism would be hard and pointless. It would need to query the mempool, create an in-memory copy of it, sort it by alternative criteria, then bend over backwards to undo the effects of CPFP, and continuously call prioritizetransaction.

Providing a helper script to automate some higher-level behaviour would be useful if we know what that behaviour is, but emulating the old priority-based sorting would be bending over backwards, complicated, inefficient, and giving a bad example.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
