### ISSUE TITLE
Remove `from` field

### ISSUE THREAD

**Issue by mcccs** [bitcoin/bitcoin#8530]
When I RClick a transaction and choose "Show transaction details" you know, transaction detail window opens and there's a line like this: `From: Unknown`.
I asked why it is so [on this](http://bitcoin.stackexchange.com/q/48049/38618) bitcoin StackExchange page, and @sipa told me that, it is for IP transactions, which is removed in v0.8.0.

If IP transactions are removed, why does the "From" line still exists? Isn't this junk code?

**Comment by jonasschnelli** [comment]
Indeed. We should remove the "from:" part from the `transactiondesc.cpp` Dialog.

**Comment by luke-jr** [comment]
Is there any chance it might be useful for payment protocol stuff in the future? I suppose it can always be added back.

otoh, at least "From: Unknown" helps combat the myth that there is a from address though...

**Comment by laanwj** [comment]
Heh the transactiondesc.cpp HTML generation is the only part from the original Satoshi GUI that is still standing, and has pretty much not been touched since then.
(once for the payment requests I think, but that was just bolted on)

The code checking for 'online' IP transactions can be removed.

However as @luke-jr says, I don't think having it, as an extra hint that 'from' information is unknown, hurts.

**Comment by mcccs** [comment]
Is it possible to add something that finds the address? A transaction details window without 'from' address looks weird to [new] users.

**Comment by sipa** [comment]
@mcccs Transactions do not have a "from" address. That is not how Bitcoin works.

Individual inputs refer to a previous output, and that previous output may have been sent to a recognizable address. This is what block explorers show you, but it is very bad practice. In particular:
* **You can't use it to identify the sender**. Many wallets do not necessarily send from a known address, and CoinJoin intentionally makes it impossible.
* **You can't use it to send money back to the sender**. Not every wallet expects money back, and shared wallet may credit the wrong user if you do. You need to ask for a new address.
* **There may be multiple address**. Every input can have one. Which one do you show? What if there are different amounts for each.
* **There may be no addresses**. For example in the case of more complicated transactions and contracts, there may not be any address at all.
* **It may be your own address**. In some cases (such a 2-of-2 escrow between sender and receiver), one of the "sender addresses" may even be yourself.

If you want to know who sent you money, give them an individualized address and label the address with the name of that person or entity. Bitcoin Core will correctly show it.

**Comment by laanwj** [comment]
Closing this; this is not an issue, it's a repetition of information you could have found in tons of other information sources. Discussions about the from address are as old as bitcoin itself.
