### ISSUE TITLE
Different recommendations for "maxuploadtarget" in docs vs. 13.0rc3 debug.log

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#8555]
Using 13.0rc3
Here
https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-traffic.md
is written, regarding -maxuploadtarget: _"The recommended minimum is 144 blocks per day (max. 144MB per day)"_.

Using -maxuploadtarget=200 leads to the following message in debug.log:
_"Max outbound target is very small (209715200 bytes) and will be overshot. Recommended minimum is 576000000 bytes."_

The different recommendations should be harmonized.

I would also suggest to consistentley use "MiB". E.g. no "MB".

Instead of _"Recommended minimum is 576000000 bytes."_ I would suggest to write "Recommended minimum is 550 MiB." (rounded up)

Instead of _"Max outbound target is very small (209715200 bytes) ..."_ should be written _"Max outbound target is very small (200 MiB) ..."_

**Comment by jonasschnelli** [comment]
Thanks for the report. I'll have a look at that.

**Comment by MarcoFalke** [comment]
This was missed in 2b1f6f9cc

**Comment by MarcoFalke** [comment]
This was missed in 2b1f6f9cc, should be easy to fix.

**Comment by sipa** [comment]
Fix for 0.13.0?

**Comment by jonasschnelli** [comment]
Its just a warning, the miscalculation is a little bit ugly, but I think a fix in 0.13.1 is okay.

**Comment by laanwj** [comment]
Closed by #8712
