### ISSUE TITLE
txindex stops working?

### ISSUE THREAD

**Issue by petertodd** [bitcoin/bitcoin#8556]
Not sure if I can reproduce this yet, but on one of my v0.13.0rc3 nodes (specifically w/ full-rbf patches) with -txindex=1 set my txindex seemed to stop working, with all transactions being reported as "not found"

After restarting, it seems to be working again unfortunately, and I haven't been able to reproduce the error yet.

**Comment by webdeli** [comment]
How do we debug something like this?

Does Bitcoind create logging around txindex events?

Julian Smith

**Comment by sipa** [comment]
Hard to say without a way to reproduce...

**Comment by petertodd** [comment]
Closing this as unreproducible.

**Comment by MarcoFalke** [comment]
Hmm, wondering if this is related: #3298

**Comment by laanwj** [comment]
> Hmm, wondering if this is related: #3298

I doubt it, that seems to have been just someone that is using the API wrongly in one way or another.
