### ISSUE TITLE
Makefile dependencies missing

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8562]
I have just checked out the latest 0.13 (which had some changed made to bytespersigop recenly added). Make fails with:-

```
  CXX      libbitcoin_server_a-miner.o
init.cpp: In function ‘bool AppInit2(boost::thread_group&, CScheduler&)’:
init.cpp:950:5: error: ‘nBytesPerSigOp’ was not declared in this scope
     nBytesPerSigOp = GetArg("-bytespersigop", nBytesPerSigOp);
     ^
  CXX      policy/libbitcoin_server_a-fees.o
Makefile:5049: recipe for target 'libbitcoin_server_a-init.o' failed
make[1]: *** [libbitcoin_server_a-init.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```
I did not "make clean" first and would prefer not to for such small changes. Why isn't make picking up the dependencies and ensuring all necessary files are recompiled?

**Comment by sipa** [comment]
This is not a dependency problem. It is failing at compile time, not at
link time.

Are you building 0.13.0 without modifications? What compiler version? Any
other compilation errors?

**Comment by rebroad** [comment]
sorry, "make clean" doesn't fix this. I jumped a gun... closing for now :-s
