### ISSUE TITLE
block structure

### ISSUE THREAD

**Issue by LongShao007** [bitcoin/bitcoin#8570]
the current block structure is :
{
    blockheader
    vtx[]
}
the vtx[0] is include miner payout and miner pool information, can we take vtx[0] as a separate structure.
{
    blockheader
    miner
            {
                  pool info
                  out
                  ...... 
            }
    vtx[]
}
what do you think of it?

**Comment by sipa** [comment]
What are you trying to do?

**Comment by jonasschnelli** [comment]
I think @LongShao007 is trying to add private data (or lets say mining pool data) in one of the core primitives (block).

This isn't the right place to discuss this.
Please use the bitcoin-dev mailing list for consensus change proposals:
https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev

Closing.

**Comment by LongShao007** [comment]
vtx[0] is special tx, vin used to add private data by some pool, so i think take vtx[0] as a single struture, it is better than vtx[0] as tx, i only want to talk about it with you!
