### ISSUE TITLE
[GUI] [0.13] Wallet tab content not switching to appropriate tab

### ISSUE THREAD

**Issue by JornC** [bitcoin/bitcoin#8586]
### Describe the issue
Bitcoin-qt wallet tabs not displaying their content (stuck on overview tab)

### Is the issue reproducible?
Probably platform/compilation specific.

### Expected behavior
Wallet should display appropriate tab.

### Actual behavior
Wallet is stuck on Overview tab.

### Any information in the debug.log file related to this issue?
2016-08-25 07:37:54 GUI: Platform customization: "other" 
2016-08-25 07:37:54 GUI: PaymentServer::LoadRootCAs: Loaded  173  root certificates 
2016-08-25 07:37:54 GUI: Object::connect: No such slot BitcoinGUI::gotoHistoryPage() in qt/walletview.cpp:91
2016-08-25 07:37:54 GUI: Object::connect:  (sender name:   'OverviewPage')
2016-08-25 07:37:54 GUI: Object::connect: No such slot BitcoinGUI::setEncryptionStatus(int) in qt/walletview.cpp:97
2016-08-25 07:37:54 GUI: Object::connect: No such slot BitcoinGUI::incomingTransaction(QString,int,CAmount,QString,QString,QString) in qt/walletview.cpp:100
2016-08-25 07:37:54 GUI: Object::connect: No such slot BitcoinGUI::handlePaymentRequest(SendCoinsRecipient) in qt/bitcoin.cpp:478

### Screenshots (if available)

![image](https://cloud.githubusercontent.com/assets/1552366/17960692/e5c3cb54-6aa7-11e6-9443-f4fefab071ce.png)

![image](https://cloud.githubusercontent.com/assets/1552366/17960700/ee0e32cc-6aa7-11e6-94eb-7c818afef180.png)

### What binary version was used (official or self compiled)

Self-compiled out of the 0.13 tag configured with `--with-incompatible-bdb`

Pruned at 550, no prior (legacy) wallet imported

### Machine specs: CPU, RAM, Disk space & OS (Windows, OS X, Linux) 

Ubuntu 14.04
Intel i7 2600K
16GB RAM
256GB SSD, ~50GB free

**Comment by jonasschnelli** [comment]
Nice description!
Can you tell us what Qt version you have compiled against?
Maybe pasetbin the configure.log somewhere (maybe PM on IRC in case you care about privacy).

**Comment by jonasschnelli** [comment]
You have probably compiled against Qt4.
Qt4 is no longer supported (actively maintained) for Bitcoin-Core. Try to install Qt5.

We should maybe refuse compiling against Qt4.

**Comment by JornC** [comment]
Compiling with Qt5 now - this is probably it. Thanks for the quick response!

**Comment by MarcoFalke** [comment]
> We should maybe refuse compiling against Qt4.

Hmm,  #8263 mentions that we still support qt4 to some extend. However, if things are know to be broken and no one maintains/tests them, it would be better to disable qt4 right now.

**Comment by JornC** [comment]
Confirming that tabs work on Qt5.

**Comment by luke-jr** [comment]
@JornC Can you help troubleshoot this more? Was your initial build in a pre-existing git clone, or a fresh one? Did you `make clean` before the problem build? Did you use the same checkout when you recompiled with Qt5?

**Comment by JornC** [comment]
@Luke-Jr

- It was a preexisting clone. Fetched and checked out on the 0.13tag.

- I did not make clean before building the problem build, though I don't
think I compiled on that repo before. (Originally cloned a couple months
ago)

- Used same checkout on working Qt5 build and did make clean on this build.

I will do another compilation attempt on qt4 and report back whether the
problem can be reproduced as soon as I get back to the machine in question
(2 hours)

**Comment by JornC** [comment]
@luke-jr I cannot reproduce it, reattempted Qt4 build works.

The config.logs are identical in the non-working Qt4 build and working Qt4 build, so I'm guessing this was some fluke because there was no make clean - though I'm quite confident I didn't make on that repo before.
