### ISSUE TITLE
Disable building against Qt4

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#8588]
Maintaining compatibility with Qt4 seems to be "lost efforts".

We should disable the `--with-gui=qt4` option and also disable the auto-detect of qt4 in `bitcoin_qt.m4`.

**Comment by MarcoFalke** [comment]
#8263

**Comment by MarcoFalke** [comment]
Conclusion:

```
jonasschnelli:  If someone really wants to compile against qt4, we could keep --with-gui=qt4 but disable the autodetect
wumpus:  jonasschnelli: good idea; you can still force using it if you know what you're doing, but it wil never choose it by default
luke-jr:  jonasschnelli: that sounds reasonable; maybe a message to make noises if they want Qt4 support to stay?

**Comment by laanwj** [comment]
So the conclusion here is to stop auto-detecting qt4, but allow it to be chosen?

Yea, maybe, though that means we can still get complaints that qt4 doesn't work. That meeting was a month ago and I've seen zero pull requests fixing qt4 issues.

**Comment by luke-jr** [comment]
> So the conclusion here is to stop auto-detecting qt4, but allow it to be chosen?

IIRC yes.

> That meeting was a month ago and I've seen zero pull requests fixing qt4 issues.

I found no issues when testing with Qt4.  It just works.

**Comment by laanwj** [comment]
So #8586 (the tab switching problem that makes qt4 unusable) was false alarm? Okay, strange.

**Comment by laanwj** [comment]
Closing this then in favor of #8263, apparently there is no immediate problem, one issue for Qt4 EOL should be enough.

**Comment by luke-jr** [comment]
Right, neither I nor the original reporter could reproduce the problem in #8586
