### ISSUE TITLE
Bitcoin-qt's default send speed is "normal"

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin#8615]
On a fresh install/run of bitcoin-qt, the default send speed when the user chooses to open the fee slider is "normal", which is 25 blocks.  

This is in contrast to default in bitcoin-cli, which is 2.  

This is not intuitive, and I'm not sure an average of 250 minutes to confirmation is considered "normal" to many users of wallets.  

I'd prefer -cli and -qt match behavior at a minimum, and perhaps a slightly better name than "normal" to give a hint that it's meant to take some additional time.

**Comment by luke-jr** [comment]
Confirmation always takes at least 60 minutes (6 blocks) on average. 250 minutes on top of that isn't typically a noteworthy difference (both 1 and 5 hours are within the same day, and too long to wait around for).

**Comment by instagibbs** [comment]
@luke-jr well, "fast" and "normal" being roughly the same is an argument for removing both.

**Comment by jonasschnelli** [comment]
Agree with @instagibbs

**Comment by laanwj** [comment]
> I'd prefer -cli and -qt match behavior at a minimum, and perhaps a slightly better name than "normal" to give a hint that it's meant to take some additional time.

See [Qt] overhaul smart-fee slider, adjust default confirmation target #8989, which aims to unify these

**Comment by MarcoFalke** [comment]
Anything left to do here after #8989 and #9036?
