### ISSUE TITLE
Blockchain download duplication

### ISSUE THREAD

**Issue by alkulp** [bitcoin/bitcoin#8627]
[Bitcoin Core 0.13.0 blockchain download.docx](https://github.com/bitcoin/bitcoin/files/444614/Bitcoin.Core.0.13.0.blockchain.download.docx)

### Describe the issue
I have a Windows 2012 R2 Server running on VMware VM that I just installed Bitcoin Core 0.13.0 on.  I wanted to store the blockchain on D:  I allocated 120Gb for this drive.  The blockchain initially downloaded through blk00559,dat  into the folder D:\blocks.  For some reason the server restarted and upon restart of Bitcoin-QT the software appears to be downloading the blockchain again in the directory D:\blocks\blocks 

### Is the issue reproducible?
Yes, I had this problem initially and uninstalled software, deleted all data from D: and c:\program files\Bitcoin.  I then reinstalled software and tried again.  The setting for D:\blocks for the data directory seemed to survive the uninstall however.
#### List steps to reproduce below:
1. 
2. 
3. 

### Expected behavior
Tell us what should happen
I expected blockchain to download and run off D:\blocks

### Actual behavior
Tell us what happens instead
Initial download through blk00559.dat in D:\blocks....   Machine restart (unknown why)...  Restart of Bitcoin-QT - Download of blockchain again in D:\blocks\blocks...  

### Any information in the debug.log file related to this issue?
I do not find the %appdata% directory!  I have 0.12.0 running on another machine (windows 10) that contains this directory but not on the windows 2012 server.  

### Screenshots (if available)
see attached docx file

### What binary version was used (official or self compiled)
Windows 64 bit 0.13.0

### Machine specs: CPU, RAM, Disk space & OS (Windows, OS X, Linux) 
VMware V5.5 VM (ver 8), 8 GB ram, 1 CPU, 2 disk drives (C: for OS/apps 40Gb, D: for blockchain 120Gb), Windows 2012 R2 Server.

**Comment by achow101** [comment]
Your datadir is either D:\ or D:\blocks. The first run it seems it was
D:\ so blocks were downloaded to D:\blocks. The second run it looks like
the datadir is D:\blocks so blocks were downloaded to D:\blocks\blocks.
There should be a debug.log file in both D:\ and D:\blocks. Please
provide those.

Did you change any settings between runs? What is your startup command?

**Comment by alkulp** [comment]
I don't have a startup command - I'm using bitcoin-qt.exe in windows.  

It does seem like I changed the datadir from D;\ to D:\blocks.  So now I've changed it back and restarted the program.  It appears to be validating the blocks from disk rather than re-downloading them.  So I guess that is the problem.  Thanks so much.
