### ISSUE TITLE
No notifications for transactions

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#8628]
Apparently it's an issue: https://bitcointalk.org/index.php?topic=1594650.msg16084238#msg16084238

From the comments below the one I linked, it seems that it has been reproduced. I have not tested this myself yet.

**Comment by jonasschnelli** [comment]
We are using `QSystemTray` notifications. Maybe in Windows 10 you have to explicit enable it?

**Comment by laanwj** [comment]
Curious that this is reported as new for 0.13 - nothing should have changed there. Maybe the bump from qt 5.5.0 to 5.6.1? (#8210)

Easiest way to test it without actually creating transactions would be to add a 'Dummy notification' button to the debug window, and see if that creates a notification.

It may also be a false alarm: some people don't realize that transactions don't generate notifications if the chain is not caught up.

**Comment by achow101** [comment]
I'm unable to reproduce it, so I'll close this for now.

**Comment by MarcoFalke** [comment]
@achow101 Running on windows 10?

**Comment by achow101** [comment]
Yes.
