### ISSUE TITLE
configure: *error: * A compiler with support for C++11 language features is required.***

### ISSUE THREAD

**Issue by CannotCompileBitcoinOnDebian** [bitcoin/bitcoin#8630]
Hi!

I am trying to compile bitcoin from scratch which for some reason does not work as well as it used to when I compiled v0.12 a few months ago. This whole Berkley compatible-thingy have always been a strange thing. I am not sure I even use the command. Would appreicate a lot if a solid guide would be put up online at Github or so, created by Linux pros :+1:  :) It should be much easier than it is today to compile bitcoin from source.

This is how it looks like.

> /home/bitcoin-0.13# ./configure --enable-hardening CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib"
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether to enable maintainer-specific portions of Makefiles... yes
> checking whether make supports nested variables... yes
> checking for g++... g++
> checking whether the C++ compiler works... yes
> checking for C++ compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking for style of include used by make... GNU
> checking dependency style of g++... gcc3
> checking for g++... g++
> checking whether we are using the GNU Objective C++ compiler... no
> checking whether g++ accepts -g... no
> checking whether g++ supports C++11 features by default... no
> checking whether g++ supports C++11 features with -std=c++11... no
> checking whether g++ supports C++11 features with -std=c++0x... no
> checking whether g++ supports C++11 features with +std=c++11... no
> checking whether g++ supports C++11 features with -h std=c++11... no
> **configure: error: *** A compiler with support for C++11 language features is required.**
> /home/bitcoin-0.13#

gcc --version
gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

How do I solve this?! 
Thanks a ton in advance.

**Comment by CannotCompileBitcoinOnDebian** [comment]
Compling v0.12 works without this error message. But would love to try 0.13 out. Anyone has aaany idea how to bypass this?

**Comment by jonasschnelli** [comment]
0.13 requires C++11 (where 0.12 does not). It looks like, that you gcc does not support it (although I thought 4.7 supports C++11). You should probably try to upgrade gcc.

**Comment by laanwj** [comment]
Your compiler doesn't support C++11. C++11 support is a requirement since version 0.13, quoting the release notes:

> Various code modernizations have been done. The Bitcoin Core code base has
started using C++11. This means that a C++11-capable compiler is now needed for
building. Effectively this means GCC 4.7 or higher, or Clang 3.3 or higher.

> When cross-compiling for a target that doesn't have C++11 libraries, configure with
`./configure --enable-glibc-back-compat ... LDFLAGS=-static-libstdc++`.

The suggestion would be to use the executables from bitcoin.org, or upgrade your compiler, or cross-compile on another machine with a newer compiler.

**Comment by jcomeauictx** [comment]
"Effectively this means GCC 4.7 or higher"... the OP stated he's using 4.7.2, as am I. so what version really *is* good enough?

**Comment by fanquake** [comment]
The current minimum required version of GCC is 4.8. See [dependencies](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md)

**Comment by jcomeauictx** [comment]
thanks, man!
