### ISSUE TITLE
Can bitcoind memory usage be reduced?

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8641]
I am thinking that the current minimum memory requirements mentioned in the documentation is too high and discourages hardware that could helpfully provide historical block data from being deployed. Why is the current memory recommendation so high (i.e. 2GB)?

What would be the best way forward to determine where this memory is currently being utilized?

**Comment by laanwj** [comment]
Generally it is a compromise between performance and memory usage.

As I've said before, please use the bitcoin stack exchange for questions such as this. Do not use the github repository to ask user questions.

Anyhow, here is a gist with some tips on how to reduce memory usage: https://gist.github.com/laanwj/efe29c7661ce9b6620a7
