### ISSUE TITLE
[qa] Cleanup doesn't get top level directory

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#8647]
I think after #8098, the cleanup that happens at the end of an rpc test no longer deletes the temp datadir created by default.  (I have a whole bunch of directories in /tmp/ now that I didn't use to have, so I think that's the cause...)

Would be nice for cleanup to work as it used to, at least in the situation where no datadir is being passed in as an argument.

**Comment by yurizhykin** [comment]
This can be fixed either with @sdaftuar's suggestion in #8098 discussion, or by backing up `tmpdir` to some other variable for removal in case it is empty at that point. Which one is more appropriate?

**Comment by MarcoFalke** [comment]
Thanks for creating the issue. We also have a cleanup problem where at least one bak file is left after the test passed. (Probably wallet-dump.py, trivial to fix). As well as a problem with not cleaning up the temp folder when creating the cache dirs.

**Comment by MarcoFalke** [comment]
I think the linked pulls should be backported
