### ISSUE TITLE
importaddress rejects valid bitcoin address in regtest mode

### ISSUE THREAD

**Issue by knaperek** [bitcoin/bitcoin#8657]
### Describe the issue
`importaddress` RPC rejects a valid bitcoin address in **regtest mode**

### Is the issue reproducible?
Yes, 100% reproducible in regtest mode
#### List steps to reproduce below:
1. Run bitcoind in the regtest mode
2. Run `bitcoin-cli importaddress 1vvcqEWV4pGdiYeN6DM2sJzJfsHewHjTt`
3. Result: Invalid Bitcoin address or script (error code -5)

### Expected behavior
Since this is a valid address, it should get imported without raising errors.

### Actual behavior
```
error code: -5
error message:
Invalid Bitcoin address or script
```
**In the main mode (regtest=0) it works OK!**

### Any information in the debug.log file related to this issue?
Nothing much (having debug=1), just this:
```
2016-09-02 18:33:49 Received a POST request for / from 127.0.0.1:43952
2016-09-02 18:33:49 ThreadRPCServer method=importaddress
```
### What binary version was used (official or self compiled)
Binaries from **ppa:bitcoin/bitcoin**
```
$ bitcoin-cli --version
Bitcoin Core RPC client version v0.12.1.0-g9779e1e

$ bitcoind --version
Bitcoin Core Daemon version v0.12.1.0-g9779e1e
```
### Machine specs: CPU, RAM, Disk space & OS (Windows, OS X, Linux) 
Easibly reproducible via Docker using [this image](https://hub.docker.com/r/freewil/bitcoin-testnet-box/) (Ubuntu 14.04 under the hood).
Tested on Linux, more than 80GB free disk space and at least 4 GiB available memory.

**Comment by paveljanik** [comment]
This address is not valid in regtest... Use testnet' addresses there.

**Comment by knaperek** [comment]
Oh, I thought I could use the normal addresses in regtest - that would be quite obvious if you want to test a production-ready code... Is there any way how to enable this? Thanks.

**Comment by paveljanik** [comment]
No, sorry.

**Comment by knaperek** [comment]
OK, I'm gonna cry now. But thanks for such a quick response :-)
