### ISSUE TITLE
whitebind ought not to make a node stop listening on other interfaces

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8666]
Surely it would make more sense for whitebind to simply mean bind "whiteness" to the chosen interface rather than behave like the "bind" option also The bind option could then be used in addition to whitebind if the desire is to exclude listening on other interfaces.

**Comment by fanquake** [comment]
Is this a question, suggestion, random musing?

@laanwj [already said](https://github.com/bitcoin/bitcoin/issues/8641#issuecomment-244078192) that general questions should be directed to the [bitcoin stackexchange](https://bitcoin.stackexchange.com).

**Comment by rebroad** [comment]
@fanquake It's (in decending order): an issue, a suggestion (bug/features are always subjective). It's not a question nor a random musing, therefore stackexchange doesn't seem an appropriate place for this to be reported.

**Comment by sipa** [comment]
I don't understand your suggestion.

`-whitebind` works exactly like `-bind`, except it makes all connections to the bound interface whitelisted.

**Comment by laanwj** [comment]
Agree with fanquake, please stop doing this.

**Comment by rebroad** [comment]
("-whitebind=<addr>", _("Bind to given address and whitelist peers connecting to it. Use [host]:port notation for IPv6"));
("-whitelist=<netmask>", _("Whitelist peers connecting from the given netmask or IP address. Can be specified multiple times.") +

@laanwj I'm not sure what you are referring to. I felt this was a genuine issue given that I had mistakenly used the whitebind option to make all connections connecting to an interface be whitelisted - it was only after realising my node had been uncontactable from the internet for 5 days that I realised this command line options causes all other interfaces to stop listening. This is (given my experience) obviously not clear (to at least 1 person, I suspect I am not alone).

This issue was raised to earmark a resolution to this. Not sure why you have closed it considering it is still outstanding.

**Comment by nopara73** [comment]
> this command line option [`whitebind`] causes all other interfaces to stop listening

Is this true? If so, is this still the case?
