### ISSUE TITLE
Feature Request: -rescan pruned blockchain

### ISSUE THREAD

**Issue by bitcoincoltd** [bitcoin/bitcoin#8668]
Currently when using a pruned node the -rescan option is unavailable, and only can -reindex and download the entire blockchain again.

Ideally you should be able to -rescan the part of the blockchain that you do have (so if you have the last 5000 blocks, then node should rescan those for transaction).

This is primarily useful if you need to import addresses into a pruned node; where the addresses have recent transactions that would be within your node's dataset, so should no need to do an entire reindex.

**Comment by luke-jr** [comment]
See #7061 and #7551 (at least the former of which is available today via [Bitcoin Knots](http://bitcoinknots.org/))

**Comment by adamjonas** [comment]
Closed by #7061.
