### ISSUE TITLE
Can't build 0.13 on RHEL 7.2 bcos enabled libevent debuging 

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#8691]
Download v0.13 to RHEL 7.2, install deps, get libevent RPMs from EPEL, build 

```
...
leveldb/util/logging.cc:58:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
                                                     ^
  CXX      leveldb/util/leveldb_libleveldb_a-options.o
  CXX      leveldb/util/leveldb_libleveldb_a-status.o
  CXX      leveldb/port/leveldb_libleveldb_a-port_posix.o
  AR       leveldb/libleveldb.a
  CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
  AR       leveldb/libmemenv.a
  CXXLD    bitcoind
libbitcoin_server.a(libbitcoin_server_a-httpserver.o): In function `InitHTTPServer()':
/source/bitcoin-0.13.0/src/httpserver.cpp:394: undefined reference to `event_enable_debug_logging'
/source/bitcoin-0.13.0/src/httpserver.cpp:396: undefined reference to `event_enable_debug_logging'
collect2: error: ld returned 1 exit status
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory `/source/bitcoin-0.13.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/source/bitcoin-0.13.0/src'
make: *** [all-recursive] Error 1

# rpm -qa | grep libevent
libevent-2.0.21-4.el7.x86_64
libevent-devel-2.0.21-4.el7.x86_64
```
* Bitcoin v0.13 (release)
* OS: RHEL7.2; kernel 3.10.0-327.28.3.el7.x86_64

Poor man's workaround: I couldn't find the proper way in docs, so I went to the 2 offending locations in `src/httpserver.cpp` and removed libevent debugging (left only `event_enable_debug_logging(EVENT_DBG_NONE);`

**Comment by jonasschnelli** [comment]
hmm.. we should probably wrap the `event_enable_debug_logging` with a preprocessor #ifdef.

**Comment by jonasschnelli** [comment]
Can you try to get the version number form your installed libevent?

**Comment by laanwj** [comment]
We already fixed this issue once by putting a preprocessor ifdef around it:
```
 #if LIBEVENT_VERSION_NUMBER >= 0x02010100
... stuff with libevent debugging
#endif
```
It is strange that you get this as a *linker* error instead of a compilation error. If the function is not in the headers you'd get an error while compiling httpserver.cpp.

Which makes me conclude that the ibevent headers found by the build system don't match the library you're linking against. Do you have multiple versions of libevent installed?

**Comment by unsystemizer** [comment]
The problem is there's no libevent-develop package for RHEL 7.2 so I built one from source.
I installed the EPEL RPM for libevent itself, but there's no devel RPM so I uninstalled and built everything from 2.02 (IIRC) source. Maybe that's where the mismatch happened.
Unfortunately the docs are for Fedora only so while I try to screw around with ./configure parameters I couldn't make it work. Maybe it'd be better to try with Fedora RPMs. I'll try that next.

**Comment by unsystemizer** [comment]
The corresponding version of Fedora is long dead. Ended up getting these 2 from CentOS 7.2 and then it worked:
```
wget ftp://rpmfind.net/linux/centos/7.2.1511/os/x86_64/Packages/libevent-devel-2.0.21-4.el7.x86_64.rpm
wget ftp://rpmfind.net/linux/centos/7.2.1511/os/x86_64/Packages/libevent-2.0.21-4.el7.x86_64.rpm
rpm -i libevent-2.0.21-4.el7.x86_64.rpm libevent-devel-2.0.21-4.el7.x86_64.rpm
```
