### ISSUE TITLE
[Compact blocks] Decoding of prefilledtxn is wrong

### ISSUE THREAD

**Issue by dagurval** [bitcoin/bitcoin#8705]
It looks to me like decoding of prefilled transactions is incorrect in Bitcoin Core 0.13. The error is in PartiallyDownloadedBlock::InitData where it decodes CBlockHeaderAndShortTxIDs incorrectly.

Given a block with 5 transactions, where transactions 3 and 5 are prefilled (+ coinbase). Prefilled transactions are encoded like this:

TX | Prefilled? | Encoded ID
---| --- | ---
0    |  YES    |    0
1| |
2| |
3    |  YES    |    3
4| |
5   |   YES   |     2

However in lines [60](https://github.com/bitcoin/bitcoin/blob/master/src/blockencodings.cpp#L60) to 75, this is decoded like this:

Prefilled index | Decoded index
---| ---
0                 |              0 (-1 + 0 + 1)
1                  |             4 (0 + 3 + 1)
2                 |              7  (4 + 2 + 1)

If you change line 60 from:

    int32_t lastprefilledindex = -1;

to 

    int32_t lastprefilledindex = 0;

and line 65 from 

        lastprefilledindex += cmpctblock.prefilledtxn[i].index + 1; //index is a uint16_t, so cant overflow here

to 

        lastprefilledindex += cmpctblock.prefilledtxn[i].index; //index is a uint16_t, so cant overflow here

The decoding would become:

| Prefilled index | Decoded index |
|---| --- |
| 0                 |              0 (0 + 0)|
| 1                 |              3 (0 + 3)|
| 2                  |             5  (3 + 2)|

This would match the original index in the block.

Since shortids depend on prefilledtxn being decoded correctly, these also will also decode incorrectly.

**Comment by dagurval** [comment]
The consequence of this bug is that Bitcoin Core cannot receive more than 1 prefilled transaction (only coinbase).

**Comment by sdaftuar** [comment]
I think you're misreading the BIP for how indexes are encoded; also I'm pretty sure the compact blocks p2p test exercises the case of Bitcoin core receiving a block with multiple pre filled transactions. From the bip:

> Several uses of CompactSize below are "differentially encoded". For these, instead of using raw indexes, the number encoded is the difference between the current index and the previous index, minus one. For example, a first index of 0 implies a real index of 0, a second index of 0 thereafter refers to a real index of 1, etc.

**Comment by dagurval** [comment]
Yes, you're correct, it is my misunderstanding of the encoding. The example above should be 


| TX | Prefilled | Encoded ID
| --- | --- | --- |
| 0 | YES | 0 
| 1 | | 
| 2 | | 
| 3 | YES | 2
| 4 | | 
| 5 | YES| 1

In this case the decoding logic is correct.

**Comment by MarcoFalke** [comment]
> In this case the decoding logic is correct.

Closing.
