### ISSUE TITLE
Duplicate man pages

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#8711]
#8608 added man pages to doc/man, however we already have a bunch of man pages in contrib/debian/manpages. These should be unified to only exist in one place.

**Comment by TheBlueMatt** [comment]
Some discussion also in (unrelated) pull #8568.

**Comment by laanwj** [comment]
The reason for not using the man pages under contrib/debian is uncertainty about their licensing. Probably they should be removed in favor of the new ones, but no one has dared to.

**Comment by MarcoFalke** [comment]
> Probably they should be removed in favor of the new ones, but no one has dared to.

Having a look, it does not seem the ones in contrib/debian contain useful information.

+1 removing them.

**Comment by MarcoFalke** [comment]
Also, it should be added next to "update translations" in https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#release-process

**Comment by TheBlueMatt** [comment]
Yea, I dont think removing the debian ones is a bad idea, just need to make sure to update the contrib/debian/*.manpages pointers when that happens.

**Comment by laanwj** [comment]
Closed in #8743
