### ISSUE TITLE
Replace BOOST_FOREACH with C++11's for loop

### ISSUE THREAD

**Issue by yurizhykin** [bitcoin/bitcoin#8718]
As there is a general movement towards c++11, can `BOOST_FOREACH` macro be replaced with c++11's `for(<variable> : <container>)` syntax everywhere throughout the codebase? Did some replacements with sed on my laptop and everything seems to work fine. Be glad to submit PR for this in couple of hours, if everything is ok.

**Comment by JeremyRubin** [comment]
@yurizhykin people are usually opposed to such batch changes as they make a big diff which is likely to step on the toes of a lot of other works in progress.

The flow I usually see is incrementally removing such parts until a few remain, then removing them all.

(If you look, no recently modified code should be using BOOST_FOREACH)

**Comment by jonasschnelli** [comment]
Agree with @JeremyRubin

**Comment by laanwj** [comment]
It make sense to do this only after the other, more involved parts of boost have been replaced.

If you want to help with that please help with testing and reviewing pulls such as #8631 (threading) and #8670/#8650 (replacing the test framework).

I agree with @JeremyRubin and @jonasschnelli that this can wait. At this point it'll just break patches and make backporting more annoying.
