### ISSUE TITLE
New file format for Xcode 8 and beyond  (Affects SDK extraction)

### ISSUE THREAD

**Issue by droark** [bitcoin/bitcoin#8748]
Hello. This is more of an FYI than anything else. It's not a bug that needs to be fixed right away since Xcode 7.3.1's SDK can be extracted just fine.

Starting with Xcode 8, Apple has moved over to a .xip file format. This is, AFAIK, a [ZIP file with a signature and some other metadata](http://apple.stackexchange.com/questions/242948/what-is-the-format-of-a-xip-file). This throws off the script in #8617 which is used to extract the SDK. 7-zip can still extract the contents. However, it extracts three files: _Content_ (the actual content), _Metadata_ (plist stuff wrapped in XML), and _[TOC].xml_ (includes the signature, certificates, and other data, and lists where to find the data in the contents). If you try to extract anything from _Content_, the program will probably choke since there's metadata at the front of it (and the end too, I think). Offhand, I'm not aware of any Linux tools that support XIP files, even though it should be relatively trivial with _[TOC].xml_ providing guidance. Apple has a _xip_ binary that can extract but that's not a realistic solution, [even if it were open source](https://github.com/sparkle-project/Sparkle/issues/821#issuecomment-242902676).

Anyway, I just wanted to bring this to everybody's attention. It might be worthwhile to add a note in the docs that people should stick to Xcode 7 for now. I'm happy to do that if it's okay.

Thanks.

**Comment by josephbisch** [comment]
I was able to get an Xcode.app out of the .xip file by more or less following [this guide](https://asciinema.org/a/85723). That guide shows the process on a Mac, but 7zip can be used on Linux if you don't have xar. Here is a link to the [script used in the video](https://gist.github.com/pudquick/ff412bcb29c9c1fa4b8d).

I imagine it is easy from there to get the SDK once you have the Xcode.app. But still, people should stick with Xcode 7 until this process is formalized into the SDK extraction script and it has had testing to verify this works.

**Comment by droark** [comment]
Thanks. Didn't know about any of that. Looks like it should work fine if anybody wants to go down that route. I'm sure the Core script will get upgraded eventually. For now, I just wanted to point it out so that people know it's a thing. The Core script can be revisited in a year or so. :) I'm just curious if it's worth pointing any of this out in the documentation.

**Comment by luke-jr** [comment]
The docs at least assume a specific Xcode version to extract from. I have no idea if you'd even get the same output if you tried to use a different version (I assume not).

**Comment by droark** [comment]
Yeah, I'm certain you wouldn't get the same output. Xcode 8 has a new SDK.
