### ISSUE TITLE
Could not link against boost_filesystem

### ISSUE THREAD

**Issue by masaoliou** [bitcoin/bitcoin#8749]
Debian Jessie

I have been linking boost_filesystem with my own project without problem.

config.log:

    It was created by Bitcoin Core configure 0.13.99, which was
    generated by GNU Autoconf 2.69.  Invocation command line was
    
    $ ./configure --with-incompatible-bdb
    
    hostname = terarows.biz
    uname -m = x86_64
    uname -r = 4.6.0
    uname -s = Linux
    uname -v = #7 SMP Thu May 26 17:08:55 CST 2016
    ...
    
    #define HAVE_VISIBILITY_ATTRIBUTE 1
    #define HAVE_BOOST /**/
    #define HAVE_BOOST_SYSTEM /**/
    #define HAVE_BOOST_FILESYSTEM /**/
    #define HAVE_BOOST_PROGRAM_OPTIONS /**/
    
    configure: exit 1
    
output:

    checking for boostlib >= 1.20.0... yes
    checking whether the Boost::System library is available... yes
    checking for exit in -lboost_system... yes
    checking whether the Boost::Filesystem library is available... yes
    checking for exit in -lboost_filesystem... yes
    checking whether the Boost::Program_Options library is available... yes
    configure: error: Could not link against boost_filesystem !

**Comment by paveljanik** [comment]
Please upload `config.log` somewhere for investigation.

**Comment by masaoliou** [comment]
Please download it from [here](https://dl.dropboxusercontent.com/u/20612585/config.log).

**Comment by paveljanik** [comment]
Strange. Can you please upload `sh -x ./configure .... 2>&1` output?
What version of the sources do you use?
The next line in `configure` output here is:
```
checking for exit in -lboost_program_options-mt... yes
```

**Comment by masaoliou** [comment]
@paraipan It seems that `sh -x ./configure --with-incompatible-bdb 2>&1` outputs everything to screen but files.

`sh -x ./configure --with-incompatible-bdb 2>&1 >/tmp/config.log2` produces [this](https://dl.dropboxusercontent.com/u/20612585/config1.log)
and
`./configure --with-incompatible-bdb 2>&1 >/tmp/config.log2` produces [this](https://dl.dropboxusercontent.com/u/20612585/config2.log)

**Comment by masaoliou** [comment]
@paraipan Aha... `configure` stops complaining that problem after I installed `libboost-program-options-dev`.
I will close this issue at this moment although `configure` resports another problem.

**Comment by paveljanik** [comment]
please use `./something >log 2>&1` (redirect stdout to file first, then stderr to stdout) to collect both stdout and stderr.

**Comment by paveljanik** [comment]
Good that you solved this yourself. Thank you!

**Comment by masaoliou** [comment]
@paveljanik Many thanks for your big help!

**Comment by paveljanik** [comment]
@theuni Can you reproduce the described problem (just uninstalling `libboost-program-options-dev` and running `configure` again)? Do we have to report something to `ax_boost*` upstream or do we use something in the wrong way?

**Comment by JustinTArthur** [comment]
Was able to reproduce this on Debian Jessie, Debian Stretch and Ubuntu Bionic Beaver using the bitcoin-0.16.2.tar.gz sources. libboost-program-options-dev was not pulled in as a dependency or recommendation from any of the packages recommended in docs/build-unix.md

**Comment by JustinTArthur** [comment]
@ken2812221 You're right, build-unix.md instructions work in v0.16.2. Thanks
