### ISSUE TITLE
rpc `listsinceblock hash` is not correctly filtering double-spends

### ISSUE THREAD

**Issue by FrozenPrincess** [bitcoin/bitcoin#8752]
### Describe the issue

Testing in bitcoin 0.13.0, calling `bitcoin-cli listsinceblock x` is outputting all double-spent transactions that are in the wallet, even those that were double-spent well and truly before x.
### Is the issue reproducible?

Yes
#### List steps to reproduce below:
1.   Create a double-spend send to your wallet (easiest using bip125)
2.   Wait until one confirms, and then wait a few more blocks
3.   Run `bitcoin-cli listsinceblock $(bitcoin-cli getbestblockhash)` and it will output the double spent transaction
### Expected behavior

The double-spent transaction that was conflicted before the block hash should be filtered

**Comment by jonasschnelli** [comment]
#8757 should fix this, though, AFAIK, `bitcoin-cli listsinceblock <getbestblockhash>` will list nothing (expect the currently wrongly listed conflicted tx), the block(hash) your targeting will not be part of the output.

**Comment by sipa** [comment]
I think it would be unexpected that transaction ever disappear from RPC
output. If you want to stop seeing a transaction, use `abandontransaction`.

**Comment by FrozenPrincess** [comment]
> I think it would be unexpected that transaction ever disappear from RPC
output. If you want to stop seeing a transaction, use `abandontransaction`.

Yeah, I don't think a transaction should ever completely disappear either. However `listsinceblock` takes a filter (since a block hash), which should filter both old confirmed transactions and old double-spends. 

The normal usage of `listsinceblock` is you want to see what has happened since the last time you processed the transactions. So you should see all the double-spends that were attempted against you, and all the transactions that have confirmed, and all the unconfirmed transactions.  It's just you don't want to see the double-spends *forever*

**Comment by sipa** [comment]
Sorry, I missed that this was about listsinceblock. I agree.

**Comment by mchrostowski** [comment]
@FrozenPrincess Could you elaborate on how you do step 1 (the double spend), I've been trying to reproduce and have had no luck so far. Thank you.

**Comment by FrozenPrincess** [comment]
@mchrostowski  Easiest way is to use bip125. You can use a list like https://coinb.in or add `walletrbf=1` in your config and then send money to yourself and then use `bumpfee` to generate a conflicting transaction.

**Comment by adamjonas** [comment]
Confirmed this is still an issue and opened #17258 to address.
