### ISSUE TITLE
configure: error: Could not find a version of the boost_chrono library! CENT OS

### ISSUE THREAD

**Issue by racan01** [bitcoin/bitcoin#8761]
I get this error when I'm trying to configure build

**Comment by racan01** [comment]
Fixed it but now this happens:

configure: error: Could not find a version of the boost_chrono library!

**Comment by unsystemizer** [comment]
https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md - install the dependencies

**Comment by laanwj** [comment]
Yes, so did you install the boost chrono library and its development headers?
