### ISSUE TITLE
Bitcoin-QT not showing in tray in Ubuntu

### ISSUE THREAD

**Issue by elichai** [bitcoin/bitcoin#8767]
#### List steps to reproduce below:
1. Self-Compile Bitcoin-qt on Ubuntu
2. minimize it

### Expected behavior
Should be at the tray

### Actual behavior
Gone but process still running

### What binary version was used (official or self compiled)
self compiled, v0.13.0.0-e158bc5
### Machine specs: CPU, RAM, Disk space & OS (Windows, OS X, Linux) 
Ubuntu 16.04 (i7, 12GB RAM)

**Comment by achow101** [comment]
See https://github.com/bitcoin/bitcoin/issues/7497#issuecomment-182341185

**Comment by MarcoFalke** [comment]
See #8043

**Comment by MarcoFalke** [comment]
Closing as duplicate per my previous comment.
