### ISSUE TITLE
Compiling 0.13.0 on Banana Pi stops

### ISSUE THREAD

**Issue by Real-Duke** [bitcoin/bitcoin#8778]
### Describe the issue
Try compiling stops everytime after ~30min at the same position

### Is the issue reproducible?
Yepp everytime the same issue

### Any information in the debug.log file related to this issue?
The last moments before the error occours:

 CXX      script/libbitcoinconsensus_la-script_error.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/root/bitcoin/bitcoin/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[3]: Leaving directory '/root/bitcoin/bitcoin/src/secp256k1'
  CXXLD    libbitcoinconsensus.la
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-main.o
g++: internal compiler error: Getötet (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:5064: recipe for target 'libbitcoin_server_a-main.o' failed
make[2]: *** [libbitcoin_server_a-main.o] Error 4
make[2]: Leaving directory '/root/bitcoin/bitcoin/src'
Makefile:8338: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/bitcoin/bitcoin/src'
Makefile:667: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
make  1552,75s user 54,73s system 98% cpu 27:05,93 total
2 root@bitcoinnode ~/bitcoin/bitcoin (git)-[v0.13.0] #  

### Machine specs: CPU, RAM, Disk space & OS (Windows, OS X, Linux) 
Banana PI M1, OS: Bananian, 4GB SD Card, 250GB Sata HDD
Compiler Info:

root@bitcoinnode ~ # g++ --version
g++ (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

1 root@bitcoinnode ~ # gcc -v                                                Sad
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 

Settings: ./configure --disable-wallet --without-miniupnpc

**Comment by sipa** [comment]
Most likely you're running out of memory. There are notes in the build
documentation on how to reduce the memory requirements of the compiler, but
if that doesn't help you'll need to cross compile.

**Comment by Real-Duke** [comment]
Hi sipa
have tried to increase swap from 512MB to 2048MB but still the same behavior.
Does more swap help?

**Comment by MarcoFalke** [comment]
Did you try https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#memory-requirements

**Comment by Real-Duke** [comment]
Yepp!
Thats the way it works! Thanks to you guys.
./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768" --disable-wallet --without-gui --without-miniupnpc

Now running on 0.13.0
