### ISSUE TITLE
Bitcoin issue

### ISSUE THREAD

**Issue by bukkymbo** [bitcoin/bitcoin#8792]
Pls friends I HV issue with my bitcoin wallet
1.I do know how to get the private key of my wallet address in other to help me transfer my bitcoin from my watchonly address to my default wallet address  thanks

**Comment by laanwj** [comment]
This issue tracker is meant to keep track of bugs in the the application, not as a question&answer helpdesk. Please use the bitcoin stack exchange instead: https://bitcoin.stackexchange.com/

**Comment by rebroad** [comment]
@laanwj I think it would help to have something for questions that is Bitcoin Core specific. that stackexschange is for _anything_ bitcoin.

**Comment by laanwj** [comment]
That would theoretically be a good idea, but there's just no critical mass for that.
