### ISSUE TITLE
My apologies

### ISSUE THREAD

**Issue by knoxcard** [bitcoin/bitcoin#8799]
My apologies for this entire thread, I do not think there was a problem with openssl and the Bitcoin core after further review.   It appears I had deleted a critical folder and had to do a custom repair job.  It's actually a bit more complex than that.  I will monitor this thread and help others in any way possible, based on the knowledge I have acquired.

**Comment by dcousens** [comment]
Related https://github.com/bitcoin/bitcoin/issues/8706
