### ISSUE TITLE
Windows wakes up from sleep

### ISSUE THREAD

**Issue by drake127** [bitcoin/bitcoin#8806]
After installing the latest version of Bitcoin Core, the computer won't stay in sleep mode for more that a minute or so. It goes to sleep just fine but it is woken up by bitcoin-qt.exe soon afterwards.
I believe the issue is reproducible with any modern Windows OS.

### Steps to reproduce below:
2. Install BitCoin Core 0.13.0 x64
3. Wait for it to sync with network and have active connections.
4. Hide BitCoin Core to tray.
5. Put the computer to sleep.

### Expected behavior
Computer stays in sleep

### Actual behavior
Computer is awoken soon afterwards with following event:
[bitcoin.zip](https://github.com/bitcoin/bitcoin/files/491570/bitcoin.zip)

### What binary version was used (official or self compiled)
0.13.0 x64 official

### Machine specs: CPU, RAM, Disk space & OS (Windows, OS X, Linux) 
Windows 8.1 Pro x64

**Comment by laanwj** [comment]
This may help: http://answers.microsoft.com/en-us/windows/forum/windows_7-performance/machine-keeps-resuming-from-sleep/c132b6b4-bd8b-4642-aacb-7dd5155c0128

No idea why it would point at bitcoin-qt.exe as wake-source, there is no code to wake on activity or take a wake-lock or such.

**Comment by drake127** [comment]
If I turn Bitcoin off, the sleep starts to work. IIRC there used to be similar bug in Boost libraries where simple sleep (or was it wait_for()) was able to wake up the PC.

**Comment by laanwj** [comment]
Ok, yes, currently building using 1.59, we should probably bump boost to 1.61 for 0.14

**Comment by fanquake** [comment]
Now that depends Boost has been bumped in master, is this enough of an issue that it needs back-porting for 0.13.1 ?

**Comment by drake127** [comment]
I certainly wouldn't mind. It's quite annoying bug if one turns off his computer at night.

**Comment by laanwj** [comment]
@fanquake in that case the specific change should be backported in boost and tested, I think it's a bad idea to just do a blanket update of boost on a backport release.

**Comment by achow101** [comment]
I can't replicate this. It may be be due to the Wi-Fi on my laptop shutting off on sleep. Or it could be that I am not synced yet, but I don't think that should be a problem.

**Comment by MarcoFalke** [comment]
I am assuming this is fixed after #8899?

**Comment by achow101** [comment]
Yes, this is fixed now.
