### ISSUE TITLE
NSIS 3 released

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#8825]
> Long-awaited version 3 of NSIS is finally ready. It comes with optional Unicode support, still works on all the same versions of Windows, **supports Windows 10**, and adds a lot of other small features and fixes.

Nothing security-related in the release notes, but do we need this for Windows 10?

**Comment by laanwj** [comment]
We don't strictly *need* it for Windows 10, the current installer works there. 
But if it has better support (in some way) may still be good to switch at some point.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
