### ISSUE TITLE
Make regtest use 210000 block reward-halving schedule

### ISSUE THREAD

**Issue by gabegattis** [bitcoin/bitcoin#8833]
Regtest uses 150 blocks for the reward-halving schedule. Testnet and mainnet use 210000. Why? I thought the whole point of regtest was to have a network that was essentially identical to testnet but without proof of work. If so, it does not make sense to have this parameter be different from testnet.

Is there a reason that this was set to 150?

https://github.com/bitcoin/bitcoin/blob/05e1c85fb687c82ae477c72d4a7e2d6b0c692167/src/chainparams.cpp#L247

**Comment by MarcoFalke** [comment]
Related: #8623

**Comment by laanwj** [comment]
Regtest was, as the name implies, added for the regression tests. The interval was set to a lower number for more efficient testing of the reward halving logic. Generating 210000 blocks would take ages even at the low difficulty of regtest.

**Comment by laanwj** [comment]
If you need something else you could use #8623, patch the number in chainparams.cpp, or even add an additional chain definition.
