### ISSUE TITLE
debug bitcoind, the gdb notice "unhandled dyld version" msg.

### ISSUE THREAD

**Issue by lovecodelc** [bitcoin/bitcoin#8847]
i work on mac os, i compile source code with "./configure --enable-debug", when use gdb attach bitcoind's pid , it shows:
"warning: unhandled dyld version (15)
 0x00007fffe026ac8a in ?? ()" 

i break at 0x00007fffe026ac8a, it actually break "main" function?
and it show "?? ()" ??
but i file bitcoind symbol tables, it does not work.

do you have such problems when develop program on mac os?
thank you.

**Comment by laanwj** [comment]
This looks like a local problem on your system, or a general issue with MacOSX debugging. Do you have success debugging any other locally compiled code?

**Comment by fanquake** [comment]
GDB itself seems to be somewhat broken on the latest version of OS X (10.11), which seems to be Apple's fault. Try googling "During startup program terminated with signal SIG113, Real-time event 113", or for issues with "GDB OS X Sierra".

If I run GDB with bitcoin-qt
```
Reading symbols from src/qt/bitcoin-qt...
warning: can't find symbol '_Z10ParseHexUVRK8UniValueRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE' in minsymtab
warning: can't find symbol 'BIP70_MAX_PAYMENTREQUEST_SIZE' in minsymtab
done.
(gdb) run
Starting program: /Users/michael/Github/bitcoin/src/qt/bitcoin-qt 
During startup program terminated with signal SIG113, Real-time event 113.
```

Trying to attach to an already running bitcoin-qt process I see the same error as you.
```
Attaching to process 47564
[New Thread 0x1403 of process 47564]
...
[New Thread 0x2903 of process 47564]
Reading symbols from /Users/michael/Github/bitcoin/src/qt/bitcoin-qt...
warning: can't find symbol '_Z10ParseHexUVRK8UniValueRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE' in minsymtab
warning: can't find symbol 'BIP70_MAX_PAYMENTREQUEST_SIZE' in minsymtab done.
warning: unhandled dyld version (15)
0x00007fffc736641a in ?? ()
```

[This](https://apple.stackexchange.com/questions/246245/macos-sierra-gdb-not-codesigned) Apple StackExchange answer suggests that disabling SIP is required, but I haven't tested it yet.

**Comment by lovecodelc** [comment]
@laanwj 
Thank you.
I have write a program with boost lib and debug it successfull. this problem bothers me several days.

**Comment by lovecodelc** [comment]
@fanquake 
thank you.
i think there is something wrong with third-party library(maybe gdb version is low?) when debug bitcoin program, i write and debug another test programs successful.
see here: https://github.com/bitcoin/bitcoin/issues/8812

**Comment by fanquake** [comment]
Closing this for similar reasons as #8812
