### ISSUE TITLE
(reserved for DNS seed issues)

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8861]
As of 2017-12-17
```
* Mainnet
OK   seed.bitcoin.sipa.be (40 results)
OK   dnsseed.bluematt.me (33 results)
OK   dnsseed.bitcoin.dashjr.org (38 results)
OK   seed.bitcoinstats.com (50 results)
OK   bitseed.xf2.org (13 results)
FAIL seed.bitcoin.jonasschnelli.ch

* Testnet
FAIL testnet-seed.bitcoin.jonasschnelli.ch
OK   seed.tbtc.petertodd.org (38 results)
OK   testnet-seed.bluematt.me (3 results)
```

Edit: the utility used to check these is now in https://github.com/bitcoin-core/bitcoin-maintainer-tools

**Comment by jonasschnelli** [comment]
Thanks for the report.
Had to restart the bitcoin-seeder, though it was running (and reporting to the longs)...

**Comment by laanwj** [comment]
Thanks for fixing, updated the issue.

**Comment by petertodd** [comment]
That should be fixed now; had to restart the server.

**Comment by laanwj** [comment]
Thanks. Yes yours is fixed now, @jonasschnelli 's broken again :p

**Comment by petertodd** [comment]
Well, I guess you don't have to change the title at least...

**Comment by laanwj** [comment]
Both are not giving me any results at this time:
```
FAIL testnet-seed.bitcoin.jonasschnelli.ch
FAIL seed.tbtc.petertodd.org
```

**Comment by rebroad** [comment]
@laanwj Currently dnsseed.bluematt.me is failing, adding (it seems) >4 minutes to the time needed to shutdown bitcoind.

**Comment by TheBlueMatt** [comment]
It is? Seems to work fine for me. Which server is failing for you?

**Comment by laanwj** [comment]
@TheBlueMatt 's is working fine, the other ones are still having problems (return no results).

**Comment by petertodd** [comment]
seed.tbtc.petertodd.org should be working again.

**Comment by jgarzik** [comment]
IMO bitseed.xf2.org is low value and can be removed.  (it will continue to stay up and resolvable ad infinitum)

**Comment by sipa** [comment]
seed.bitcoin.sipa.be should be working again (firewall issue).

**Comment by laanwj** [comment]
Everything is okay now, congrats everyone.

**Comment by laanwj** [comment]
@jonasschnelli Your DNS seeds (both testnet and mainnet) are experiencing issues at the moment.

**Comment by jonasschnelli** [comment]
Mainnet seed seems running fine.
There was a strange issue on the testnet seed (now resolved, currently investigating).

**Comment by s-tikhomirov** [comment]
`seed.tbtc.petertodd.org` seems to be down.

**Comment by petertodd** [comment]
@s-tikhomirov Thanks! Looks like something was down on my server; rebooted and it seems to be working fine now.

**Comment by sysmanalex** [comment]
** server can't find seed.tbtc.petertodd.org: SERVFAIL gain...

**Comment by petertodd** [comment]
@sysmanalex Fixed.

**Comment by cdecker** [comment]
seed.bitcoinstats.com has auto recovered as well ☺
