### ISSUE TITLE
Multiple peer operations via GUI

### ISSUE THREAD

**Issue by laudaa** [bitcoin/bitcoin#8864]
Currently if somebody wants to do some peer operations (for whatever reason) via the GUI, they have to select 1-by-1 and do them individually. This is just very inefficient when the same operation has to be carried out on multiple peers. It would be nice to be able to select multiple peer at once and e.g. ban them all.

**Comment by laanwj** [comment]
Agree, otherwise banning e.g. the annoying 52.* spy nodes is like a whack-a-mole minigame.

**Comment by jonasschnelli** [comment]
Agree. This could be implemented after the GUI ban fix: https://github.com/bitcoin/bitcoin/pull/8885.
