### ISSUE TITLE
Move to Libevent 2.1.x

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8867]
Libevent 2.1.6-beta was released in July this year.
The current stable build (2.0.22) was released in Jan 2015, the same time as the previous beta.

Not using 2.1.x is affecting atleast
- [WIP] rest: Stream entire utxo set #7759
- bitcoin-cli: More detailed error reporting #8722
- Compatibility logic in [bitcoin-cli.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/bitcoin-cli.cpp#L129)

There are also compatibility issues with 2.0.22 and recent mingw-w64 gcc versions, see #8730

Optimistically tagged this as something for 0.14.0

**Comment by laanwj** [comment]
Some further backstory here: libevent's release process is **slow**. Maintenance is in no means standing still, many improvements have been made in the 2009-now timeframe. However, these have not ended up in the stable versions (2.0.x). Even some bugfixes have not, I had to push to get a basic IPv6 http fix in at some point (which had been in 2.1.x for a long time).

Branch 2.1.x had been in alpha for years, and has entered beta 2015-01-05 with 2.1.5. Despite not officially being called stable yet it seems rock-stable overall.

As you can see with #8722 and  #7759 I've been starting to bump against the restrictions of 2.0.x. So I'm in favor for this.

**Comment by MarcoFalke** [comment]
(Note: This issue should be reopened, as the tasks in op are not yet
addressed, I think)
