### ISSUE TITLE
You need to increase minimal required Boost version (or fix the issue)

### ISSUE THREAD

**Issue by Zenitur** [bitcoin/bitcoin#8868]
Trying to compile Bitcoin Core 0.13 from source code, I saw this error:

`[  141s] checking for boostlib >= 1.20.0... yes`
`[  141s] checking whether the Boost::System library is available... yes`
`[  141s] checking for exit in -lboost_system... yes`
`[  142s] checking whether the Boost::Filesystem library is available... no`
`[  143s] checking whether the Boost::Program_Options library is available... yes`
`[  143s] checking for exit in -lboost_program_options-mt... yes`
`[  144s] checking whether the Boost::Thread library is available... no`
`[  144s] checking whether the Boost::Chrono library is available... no`
`[  145s] checking whether the Boost::Unit_Test_Framework library is available... yes`
`[  145s] checking for dynamic linked boost test... yes`
`[  146s] checking for mismatched boost c++11 scoped enums... ok`
`[  149s] configure: error: No working boost sleep implementation found.`
`[  149s] error: Bad exit status from /var/tmp/rpm-tmp.50778 (%build)`

I'll upload new Boost in my repository to fix that. You need to increase minimal required Boost version, or make "if old version" code.

OS: SUSE Linux Enterprise SP4 32-bit and 64-bit, GCC 4.8.2, Qt 5.6, Autoconf 2.69, Boost 1.36

My Boost package info: https://www.suse.com/LinuxPackages/packageRouter.jsp?product=server&version=11&service_pack=sp3&architecture=x86_64&package_name=boost-license

My repository: https://build.opensuse.org/package/show/home:linux4humans:qt5.6/bitcoin

RPM SPEC file: https://build.opensuse.org/package/view_file/home:linux4humans:qt5.6/bitcoin/bitcoin.spec?expand=1

Full build log is attached

**Comment by Zenitur** [comment]
[bitcoin-0.13-build_log_on-SLES_11.zip](https://github.com/bitcoin/bitcoin/files/505943/bitcoin-0.13-build_log_on-SLES_11.zip)

**Comment by laanwj** [comment]
Are you sure this is a boost version issue? Does it go away with a different boost version?
Can you show the relevant part of config.log? (or pastebin/upload the whole thing)

**Comment by laanwj** [comment]
Upending the minimum boost version sounds like a good idea though (1.20 wtf), but I'm not aware 1.36 doesn't work.

**Comment by paveljanik** [comment]
Can you please upload `config.log`?

**Comment by Zenitur** [comment]
I don't know how to get `config.log` from OBS repository. I'll search how to do that, after this I'll upload this config file.

**Comment by sipa** [comment]
If you build locally, don't you get a similar error?

**Comment by laanwj** [comment]
It looks like a few of the required boost libraries are missing:
```
[ 142s] checking whether the Boost::Filesystem library is available... no
[ 144s] checking whether the Boost::Thread library is available... no
[ 144s] checking whether the Boost::Chrono library is available... no
```
A similar problem could be causing the boost::sleep issue.

These are the boost components required (from `depends/packages/boost.mk`): `chrono,filesystem,program_options,system,thread,test`

I'm still unconvinced that this is a version issue at all, unless you can confirm that using a different boost version solved the problem.

**Comment by theuni** [comment]
Boost 1.36 doesn't include chrono. You'll need a newer one.

And yes, we should bump the minimum.

**Comment by laanwj** [comment]
```
Version 1.36.0  August 14th, 2008 12:00 GMT
```
Boost 1.36.0 is 8 years old(!). It predates bitcoin completely. I didn't realize this in my response above, I think I  had the version number wires crossed in my head.

**Comment by Zenitur** [comment]
Okay guys, I cannot get 'config.log' from a build farm. So I have been installed this Linux distribution on Virtualbox. I'll give you log file in a few hours...

**Comment by Zenitur** [comment]
[config.zip](https://github.com/bitcoin/bitcoin/files/508519/config.zip)

**Comment by Zenitur** [comment]
There is the build log. I'll upgrade system Boost step by step to detect lower version needed by Bitcoin Core

**Comment by Zenitur** [comment]
[config_boost_1.44.zip](https://github.com/bitcoin/bitcoin/files/508563/config_boost_1.44.zip)

Still no.

**Comment by paveljanik** [comment]
Does this answer your problem?

http://stackoverflow.com/questions/8297652/error-boost-disable-threads

**Comment by Zenitur** [comment]
paveljanik, I don't know how to define BOOST_DISABLE_THREADS. Do I need to define something in RPM SPEC file? Or in Bitcoin Core source? Maybe in bitcoin-0.13.0/build-aux/m4/ax_boost_thread.m4?

**Comment by paveljanik** [comment]
No. Your boost looks like it was compiled *without* threads for some reason...

**Comment by Zenitur** [comment]
The SUSE Enterprise developers are not as foolish as I thought. They're put Boost 1.49 as a "boost49" package, without removing Boost 1.36. I've found that suddenly: https://www.suse.com/support/update/announcement/2015/suse-ou-20150656-1.html
![sles_boost](https://cloud.githubusercontent.com/assets/3435752/19210615/356d2482-8d5a-11e6-8c29-830ea3b5a812.png)

**Comment by Zenitur** [comment]
Error message when build with Boost 1.49: http://pastebin.com/b2JHAE01

**Comment by laanwj** [comment]
Closing in favor of  #8875, I think one issue about boosting the boost version is enough.
