### ISSUE TITLE
[MacOSX] Unable to build on 'macOS Sierra' version 10.12

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#8869]
Build error after: ./autogen.sh ; ./configure ; make -j8

https://paste.fedoraproject.org/442517/75481833/

bitcoin/master at: eafc5f4fae52a16ad7343f7fb13bfecf9b62310a

**Comment by fanquake** [comment]
`brew uninstall protobuf`
`brew install homebrew/versions/protobuf260 --c++11`

You still need to use Protobuf 2.6, the OS X build docs were only recently updated.

**Comment by laanwj** [comment]
It didn't look like a protobuf incompatibility issue to me but something with atomics / endian swapping compat. But I think you're right, it looks like it happens in the qt files that also include protobuf.

**Comment by da2ce7** [comment]
@fanquake you are quite correct, after downgrading protobuf it compiles without error.  It would be great if configure step would detect this and refuse to proceed.

I'll close this issue.
