### ISSUE TITLE
Bump minimum required Boost version

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#8875]
After discussion in #8868, this is to track bumping the minimum required Boost version.

The current minimum required Boost version is [1.47.0](https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L887).
The long term goal is to move away from Boost entirely, and is tracked in the [Boost -> C++11 Project](https://github.com/bitcoin/bitcoin/projects/3). 

We currently use the following Boost [components](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/boost.mk#L22):
- Chrono, Filesystem, System, Thread, Test

### Filesystem:
V1 - (boost version) [1.30.0](http://www.boost.org/users/history/version_1_30_0.html)
V2 - [1.34.0](http://www.boost.org/users/history/version_1_34_0.html)
V3 - [1.44.0](http://www.boost.org/users/history/version_1_44_0.html)

### Chrono:
V2.0.0 - [1.52.0](http://www.boost.org/users/history/version_1_52_0.html)
- [#7381](http://svn.boost.org/trac/boost/ticket/7381) C++11 compliance: unresolved symbol when assigning a constexpr duration to a non-const local variable.

V1.2.3 - [1.51.0](http://www.boost.org/users/history/version_1_51_0.html)
- Documentation & C++11

### Thread:
V4.1.0 - [1.54.0](http://www.boost.org/users/history/version_1_54_0.html)
- [#7285](http://svn.boost.org/trac/boost/ticket/7285) C++11 compliance: Allow to pass movable arguments for call_once.

Thread is on the way out in #8631.

### Test:
Work has started on replacing this in #8670.

**Comment by laanwj** [comment]
Great overview, thanks!

Regarding `boost::filesystem`, this means that if we require at least 1.44 we can rid of some compatibility logic here:
```
src/qt/guiutil.cpp:#if BOOST_FILESYSTEM_VERSION >= 3
src/qt/guiutil.cpp:#if BOOST_FILESYSTEM_VERSION >= 3
src/qt/guiutil.cpp:#if BOOST_FILESYSTEM_VERSION >= 3
src/test/testutil.cpp:#if BOOST_FILESYSTEM_VERSION == 3
```
Most notably the GUI thing: "Conversion between boost path and QString can use invalid character encoding with boost_filesystem v2 and older"

C++11 compliance is a good point and means we *need* to require a recent boost.

**Comment by Zenitur** [comment]
[config_boost_1.44.zip](https://github.com/bitcoin/bitcoin/files/508575/config_boost_1.44.zip)
Build log with Boost 1.44

**Comment by fanquake** [comment]
Two possible scenarios:
#### Bump to 1.44.0 (released August 2010)
Require Filesystem V3
 - Remove compatibility logic in [testutil.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/test/testutil.cpp)

- Remove compatibility logic in guiutil.cpp [here](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L40), [here](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L69) and [here](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L867). As well as a warning [here](https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L878).

Downside: No C++11 compliance in Chrono or Thread 
- However Thread may be gone shortly anyways (see #8631), and would require a bump to 1.54.0, which is probably too recent a version.

#### Bump to 1.52.0 (released November 2013)
Require Filesystem V3
C++11 compliance in Chrono
- Remove checks for Boost < 1.49 & reduced exports in [configure](https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L616).

- Possibly remove configure checks for broken Boost sleep in Boost < 1.52 ? [here](https://github.com/bitcoin/bitcoin/blob/master/configure.ac#L699).

- Remove Boost < 1.50 compatibility logic in [scheduler.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/scheduler.cpp#L48).

- Issue with Boost < 1.46.0 on 32-bit systems in [coins.h](https://github.com/bitcoin/bitcoin/blob/master/src/coins.h#L277)
- Clang workaround for Boost < 1.46 in [util.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/util.cpp#L88)

I had a feeling there was some Boost 1.36.0 logic somewhere, but I can't seem to find it now.

**Comment by laanwj** [comment]
Thanks for the extensive research.
For another data point we need to bisect boost to find out what release still works with the current code.

**Comment by fanquake** [comment]
Chrono Version 1.0.0 was released in [January 2011](http://www.boost.org/doc/libs/1_62_0/doc/html/chrono/appendices.html#chrono.appendices.history), so I'm guessing it made it into the next Boost release 1.46.0 (March 2011). That would make our minimum version atleast 1.46.0 ?

**Comment by Zenitur** [comment]
Guys, you don't need to support Boost 1.36 or something like that. I've found that all long-time supported Linux distributions are have fresh Boost builds. In CentOS 5 and 6 there are in EPEL repository. In SUSE Enterprise there is in boost49 package.

I didn't saw boost49 when tried to build package. I'm sorry that I've misled you.
![sles_boost](https://cloud.githubusercontent.com/assets/3435752/19210677/6e52dd44-8d5c-11e6-9a7b-4c13e25182ba.png)

**Comment by laanwj** [comment]
The minimum boost version was bumped to 1.47.0 in #8920. 

Maybe we should keep this open to determine when to bump the minimum version again in the future as it has an excellent analysis, I don't know.

**Comment by luke-jr** [comment]
Note boost 1.53 is the most recent supported in Debian stable.

**Comment by Zenitur** [comment]
There is not only Debian in the Linux world. CentOS 6 is using Boost 1.48. Digia uses this distribution as a build farm to make official Qt5 Linux builds.

**Comment by TheBlueMatt** [comment]
Wow, something ships older software than Debian? Thats rather impressive.

**Comment by luke-jr** [comment]
CentOS 7 is out now. I don't think we need to support CentOS 6...

**Comment by Zenitur** [comment]
Supporting only newest Linux distributions is like supporting only Windows 10. Let me tell about RHEL/CentOS (sorry for my bad English). Before DEB-based becomes the most popular, Red Hat makes a backwards compability for their system. I mean LSB, the Linux Standard Base. So the true way is making builds for previous CentOS version for cover the maximum range. What Digia does, so only one Qt5 build works in a few CentOS releases, as well as in other Linux distributions. 99% of Linuxes has LSB compability, including Debian.

**Comment by laanwj** [comment]
Some companies are dedicated to supporting old versions of software, nothing wrong with that. The question here is whether that maintenance and testing burden should fall to us as developers of the upstream code. Someone could always (say) argue **I want this to compile on my DOS machine with Turbo C++ 3.0!** Well if you want that, it's up to you to make and maintain a patch-set. There is a point at which too many fallbacks and workarounds and conditional features accumulate that it isn't realistic to support a certain dependency library version anymore.

Though in the specific case of boost we can stick with 1.47.0 for a while. I'm not aware of any terrible issues, the worst ones were with Boost Filesystem v1/2.  In addition to the general stuff @fanquake mentions in the OP there's only three post-1.47 conditionals:
```
src/scheduler.cpp:#if BOOST_VERSION < 105000
src/scheduler.cpp:#if BOOST_VERSION < 105000
src/util.cpp:#if BOOST_VERSION >= 105600
```
The first two have to do with time handling, which will be changed to std::chrono soon anyway (#9566). The latter has to do with detecting "hyperthread" cores or not for -par, which is a bit unfortunate but not critical.

So I think we can stop the discussion about boost versions here. Maybe we can even postpone bumping the minimum boost version until we remove the dependency completely.

**Comment by jameshilliard** [comment]
@luke-jr At least one major mining pool is known to use Centos 6, however they already use a more up to date compiler due to the lack of c++11 support in the shipped gcc.

**Comment by fanquake** [comment]
Agree with @laanwj here.

I'm optimistic Boost will be gone before we HAVE to bump it again. If anyone would like to follow that progress see https://github.com/bitcoin/bitcoin/projects/3.

Let's leave this open for now to track some of the remaining changes.

**Comment by MarcoFalke** [comment]
In the OP you mention

> The current minimum required Boost version is [1.20.0](https://github.com/bitcoin/bitcoin/blob/master/build-aux/m4/ax_boost_base.m4#L75).

This is still the case, even though #8920 was merged. Does this need to be changed?

**Comment by laanwj** [comment]
yes:
```
| Boost | [1.64.0](http://www.boost.org/users/download/) | [1.47.0](https://github.com/bitcoin/bitcoin/pull/8920) | No |  |  |
```
```m4
dnl Minimum required Boost version
define(MINIMUM_REQUIRED_BOOST, 1.47.0)
```

**Comment by adamjonas** [comment]
Given the minimum required Boost version was bumped to 1.58.0 in https://github.com/bitcoin/bitcoin/pull/19667, it seems like this issue is outdated and can be closed.

**Comment by fanquake** [comment]
Yep I agree there's probably limited value left in having this open.
