### ISSUE TITLE
Commit 6423116 broke ban node list functionality in bitcoin-qt debug window

### ISSUE THREAD

**Issue by randy-waterhouse** [bitcoin/bitcoin#8876]
### Describe the issue
bitcoin-qt: Debug pop-up window, Peers tab, right-click ban node for 1 hour, day, week, year does nothing. Disconnect node still works.

### Is the issue reproducible?
Yes.

#### List steps to reproduce below:
1. build master branch after commit https://github.com/bitcoin/bitcoin/commit/6423116741de2144872389cf63a621539ae79aaa
2. launch bitcoin-qt (on testnet is advisable)
3. test ban node list right-click functionality on Menu->Help->Debug pop-up window, Peers tab.

**Comment by achow101** [comment]
I've been able to reproduce this.
