### ISSUE TITLE
Needing an FAQ

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#8878]
I am noticing a fair number of github issues which are being closed quite quickly, either because they are being identified as "questions", or because they are deemed to be not appropriate issues for github. I think an FAQ that could form part of the bitcoin core distrubution needs to be created so that github stops being used for out-of-scope issues - and the scope is documented, ideally along with links to where are the correct areas for asking questions. Raising this issue to hopefully kickstart that process.

**Comment by fanquake** [comment]
Something other than http://bitcoin.stackexchange.com/ ?

**Comment by MarcoFalke** [comment]
I think the issue template clearly shows that the issue tracker is meant to track issues regarding the software only.

**Comment by laanwj** [comment]
Yes, the [issue template](https://github.com/bitcoin/bitcoin/blob/master/.github/ISSUE_TEMPLATE.md) would be a good place to mention this, although it's already reasonably clear I'd say.
