### ISSUE TITLE
Updatable minimum unpruned block height for use w/ external databases

### ISSUE THREAD

**Issue by petertodd** [bitcoin/bitcoin#8917]
Currently if you are trying to synchronize a new, pruned, node with the network while simultaneously updating an external database of some kind - e.g. a address index service - you can easily end up in the situation where the block data you need has been pruned due to the external database being unable to keep up. Equally, it's possible to run into this problem in general - my own OpenTimestamps Server can theoretically have problems with overly aggressive pruning.

It'd be good if there was an explicit mechanism to tell a node in initial sync what's the minimum block height that it can prune - updatability via RPC - with the behavior being to stop downloading new blocks if that height would otherwise be pruned.

**Comment by sdaftuar** [comment]
I think #7871 would help here, perhaps?

**Comment by petertodd** [comment]
Ah, nice! That's exactly what I need I think.
