### ISSUE TITLE
Need documentation on minimum supported dependency versions

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#8923]
We've always skirted on this, but it'd be useful for anyone building to define what are minimally supported versions of dependency libraries.
This should probably be a new file in `doc/`, as it is not specific to any one platform.
Also checks in `configure.ac` would need to be added to check if these versions are present.

Ref: Bump minimum required Boost version #8875

Known minimums:
- Compiler: gcc 4.7+, clang 3.3+ (source: 0.13.0 release notes)
- For QA tests: Python 3.4 (source: 0.13.0 release notes)
- Boost 1.47 (after  #8920)
- For GUI: Qt 4.7+ or 5.?+ - to be researched, do we have a minimum 5.x version?
- Wallet: BerkeleyDB 4.8 (5.x and 6.x works too)

**Comment by fanquake** [comment]
I'm going to merge this into #8639.
