### ISSUE TITLE
Arm compilations give a "Illegal instruction" on a Raspberry Pi 2

### ISSUE THREAD

**Issue by jdevora** [bitcoin/bitcoin#8924]
I have a Raspberry Pi 2 running Raspbian 

My understating is that I should be able to run the ARM 32 bits compilation on it.

I follow those steps but at the end it will throw an Illegal Instruction error.

    $ wget https://bitcoin.org/bin/bitcoin-core-0.13.0/SHA256SUMS.asc
    $ wget https://bitcoin.org/bin/bitcoin-core-0.13.0/bitcoin-0.13.0-arm-linux-gnueabihf.tar.gz
    $ sha256sum bitcoin-0.13.0-arm-linux-gnueabihf.tar.gz|grep -f SHA256SUMS.asc
      7c657ec6f6a5dbb93b9394da510d5dff8dd461df8b80a9410f994bc53c876303  bitcoin-0.13.0-arm-linux-gnueabihf.tar.gz
    $ tar -zxf bitcoin-0.13.0-arm-linux-gnueabihf.tar.gz
    $ bitcoin-0.13.0/bin/bitcoind
      Illegal instruction

    $ lsb_release -a
     No LSB modules are available.
     Distributor ID: Raspbian
     Description:    Raspbian GNU/Linux 8.0 (jessie)
     Release:        8.0
     Codename:       jessie
    $ uname -a
     Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

Was it never intended to work on a Raspberry Pi 2  or is there something missing on my part or at the compilation options?

**Comment by mruddy** [comment]
Quick question, are you sure that you're using a Raspberry Pi 2 Model B and not a Raspberry Pi Model B+? https://www.element14.com/community/docs/DOC-78141/l/identifying-your-model-of-raspberry-pi

Your uname output shows armv6l and not armv7l. Raspberry Pi 1 used ARMv6.

What does this show you: `egrep -i 'model|hardware' /proc/cpuinfo`?

**Comment by jdevora** [comment]
Sorry, my mistake, I inserted the SD card in my Pi B+ instead of the Pi 2.

**Comment by laanwj** [comment]
Yes, the binary targets ARMv7. Should arguably have mentioned that in the release notes. It is also news to me taht RPI1 was only ARMv6.

**Comment by mruddy** [comment]
@laanwj we could add a quick note to the 0.13.0 and/or 0.13.1 release notes. Something about the binaries being built for ARMv7-A and thus being able to be run on platforms backwards compatible to that architecture. I know we probably don't want to list all the products that might work, but giving the example of RasPi 2 & 3 vs RasPi 1 would probably be helpful to people.

**Comment by laanwj** [comment]
@mruddy Yes, that'd be a good idea
