### ISSUE TITLE
About debug "<optimized out>"

### ISSUE THREAD

**Issue by lovecodelc** [bitcoin/bitcoin#8926]
Hi, I have build Bitcoin Core with "./configure --enable-debug --prefix=...", when in debug model, i print some var, but notice "<optimized out>", i want to modify Makefile's compiler option(-O0), is there a easy way to modify it, how about modify "configure" ?
thanks.

**Comment by laanwj** [comment]
```
./configure CFLAGS="-O0 -g" CXXFLAGS="-O0 -g"
```
