### ISSUE TITLE
getblocktemplate help text should report BIP9 'rules'

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#8945]
### Describe the issue

The `getblocktemplate` RPC output does not list the 'rules' field in the template request object, as described in BIP9.

### What version of bitcoin-core are you using?

0.13.1rc1

**Comment by sipa** [comment]
As reported on IRC by @laanwj:
```
22:43:56 < Lightsword> sipa, how do I do that with bitcoin-cli?
22:45:27 < sipa> $ ./bitcoin-cli -testnet getblocktemplate '{"rules":["segwit"]}'
22:46:17 < wumpus> seems that's not documented in the help for the request
22:46:44 < wumpus> just 'capabilities' and 'mode'; 'rules' is only shown as a reply field
```

**Comment by MarcoFalke** [comment]
per @laanwj : Also the type of `jsonrequestobject` is mentioned to be a string, but it is a JSON object that needs to be passed in.
