### ISSUE TITLE
Fee script calculator 

### ISSUE THREAD

**Issue by diadal** [bitcoin/bitcoin#8978]
am working on bitcoin project am stock at fee i want user to know and see their fee before sending bitcoin i will be glad if anyone can help me with the script to use or follow am using bitcoin core 13 for the project thanks

**Comment by jonasschnelli** [comment]
`createrawtransaction` -> `fundrawtransaction` -> **check fee, show it to user** -> `signrawtransaction `-> `sendrawtransaction`

Maybe consider a max-delay time for "**check fee, show it to user**".

**Comment by jonasschnelli** [comment]
Also, this question is more about *using* bitcoin-core, try IRC #bitcoin or bitcoin.stackexchange.com, etc.

**Comment by diadal** [comment]
have done a lot of research most say is bad idea to create createrawtransaction -> fundrawtransaction -> check fee, show it to user -> signrawtransaction-> sendrawtransaction is there any other way to do this or script that can help

**Comment by jonasschnelli** [comment]
@diadal: Can you elaborate why it would be a bad idea?

**Comment by diadal** [comment]
@jonasschnelli am not saying is bad i said most people said is bad idea i chat @ IRC #bitcoin like you advice i reply need help me this

**Comment by jonasschnelli** [comment]
It probably depends on your use-case. But in general I think it's a good idea to...

1. Set outputs with `createrawtransaction`
2. Run coin selection and add inputs with `fundrawtransaction`
3. Maybe use `decoderawtransaction` to get json compatible output
4. Check transaction size, check fees
5. Maybe adjust the feerate (`fundrawtransaction` has a feerate option in master)
6. If you accept the transaction, use `signrawtransaction`.
7. Eventually use `sendrawtransaction`

This would also allow to decouple the signing/privatkey from your node. `fundrawtransaction` can work with watch-only-addresses and supports a custom change address (in master), `signrawtransaction` could be done on an offline-machine.

**Comment by diadal** [comment]
thanks so much for your brake down i will work with this and get back to you

**Comment by diadal** [comment]
to create 

> createrawtransaction

[{"txid":"id","vout":n},...] {"address":amount,"data":"hex",...} ( lock time ) how do i know the txid

**Comment by jnewbery** [comment]
@diadal - I recommend you move this discussion to [bitcoin.stackexchange.com](bitcoin.stackexchange.com), where there are plenty of people who are happy to help answer technical questions. You can also message me directly with the link to your question on stackexchange and I'll be happy to answer there (I've done some work on `getrawtransaction` and `bitcoin-tx` recently so I'm quite familiar with the code).

> how do i know the txid

The first argument for getrawtransaction is list of objects representing the inputs. `txid` here is the transaction id of the transaction containing the input that your new transaction is spending.

**Comment by diadal** [comment]
@ jnewbery what is your username @ bitcoin.stackexchange.com

**Comment by jnewbery** [comment]
http://bitcoin.stackexchange.com/users/26940/jonnynewbs . Put a link to your question in this issue and I'll be happy to help you.

**Comment by diadal** [comment]
ok thanks but don't know what send you msg my id on there is bitotm

**Comment by sipa** [comment]
Just ask your question on SE, no need to specifically ask for one person to
answer.

**Comment by jnewbery** [comment]
Sorry - I caused confusion by suggesting you message me. Just ask the question on SE (and optionally put a link to it here).

**Comment by diadal** [comment]
if you can fixed this if you are on Skype i don't mind paying for your service
