### ISSUE TITLE
PPA Broken for Ubuntu 16.10

### ISSUE THREAD

**Issue by bclermont** [bitcoin/bitcoin#9003]
Affect PPA version: `0.13.0-yakkety1`

Ubuntu 16.10 (yakkety) package dependencies are invalid.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bitcoin-qt : Depends: libprotobuf9v5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

That package is only available for Xenial (16.04).

http://packages.ubuntu.com/search?keywords=libprotobuf9v5&searchon=names&suite=all&section=all

Ubuntu 16.10 updated protobuf C lib to 1.0: http://packages.ubuntu.com/yakkety/libprotobuf10

**Comment by TheBlueMatt** [comment]
Yea, they updated the package name out from under me after I uploaded the package pre-release. This will be fixed automatically when 0.13.1 is built hopefully in a week or so.

**Comment by fanquake** [comment]
Can this be closed now? Looks like updates have been made for yakkety.
https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin

**Comment by bclermont** [comment]
confirm it's fixed
