### ISSUE TITLE
gitian building not working

### ISSUE THREAD

**Issue by 3s3s** [bitcoin/bitcoin#9006]
I followed this instructions https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md
but on this step: https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md#setting-up-the-gitian-image
i have got an error:

```
cp: cannot stat ‘base-trusty-amd64-bootstrap/usr/lib/x86_64-linux-gnu/lxc/lxc-init’: No such file or directory
debian@debian:~/gitian-builder$ 
```

**Comment by achow101** [comment]
See https://github.com/devrandom/gitian-builder/pull/135 They fixed the issue upstream, you should pull gitian-builder again and retry.
