### ISSUE TITLE
Rpc boolean consistency

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9024]
getblock needs a "true" for its verbose argument, while getrawtransaction needs a "1".

all these should be consistent.

**Comment by jnewbery** [comment]
I agree. This is confusing for users.

I've had a look through the RPCs, and as far as I can tell, getrawtransaction is the only call which takes an int for verbose.

I've opened https://github.com/bitcoin/bitcoin/pull/9025 to change getrawtransaction to take a bool for verbose. It will still take a num for backward compatibility, but will issue a warning to the user that using a num is deprecated.

**Comment by laanwj** [comment]
@gmaxwell can you test (and if's what you expect, ACK) #9025?

**Comment by laanwj** [comment]
Closed by #9025.
