### ISSUE TITLE
getrawtransaction is error

### ISSUE THREAD

**Issue by Vagabondtq** [bitcoin/bitcoin#9040]
I use VPS centos 7, and i install bitcoind follow: https://www.ringingliberty.com/bitcoin/

this is file bitcoin.conf:

```
rpcuser=bitcoinrpc
rpcpassword=My_password
daemon=1
rpctimeout=30
rpcport=8332
gen=0
txindex=1
keypool=100
```

Then i ran: `bitcoind -reindex -deamon`then ran:
`bitcoin-cli getrawtransaction string_txid`

i get error: 

```
error code: -5
error message:
No information available about transaction
```

I use: **Bitcoin Core Daemon version v0.13.0.0-ga402396**

I don't know wrong?

**Comment by MarcoFalke** [comment]
Unrelated thought: We should include in the error message if txindex is set.

**Comment by Vagabondtq** [comment]
> Unrelated thought: We should include in the error message if txindex is set.
e62b1af87637cf2d9e6444c450b1069c7cf0220707d8e08b3940923f93d313f6

**Comment by sipa** [comment]
getrawtransaction only works for unconfirmed transactions, unless you're
running in -txindex mode.

**Comment by MarcoFalke** [comment]
@Vagabondtq What is the length of the string_txid? Did you accidentally remove or add chars to the string?

**Comment by knoxcard** [comment]
Did you run the command exactly as "bitcoin-cli getrawtransaction string_txid"

**string_txid** must be a hexadecimal string.

**Comment by MarcoFalke** [comment]
@Vagabondtq Can you try with current master again or provide further information to my previous question, please?

**Comment by dougstrong77** [comment]
Can some one help me i dont under stand any thing i must be stupid how do i know that a transaction ia mine im looking at when i log into the block chain
