### ISSUE TITLE
New Bitcoin Methodology or Crypto Currency Proposal

### ISSUE THREAD

**Issue by knoxcard** [bitcoin/bitcoin#9044]
Hopefully this is the right place to post this....if not, simply leave a comment and I will place it somewhere else.

**Why do we need a blockchain or miners?**

Why dont we simply create 21 million "Bitcoins" that cannot be duplicated? Some sort of ridiculously long hash key that a computer generates. Those millions of "Bitcoins" are then sold at auction online, immediate cash is generated to further fund the project.

Everyone would agree to this hash, so all the coins could be VERIFIED with a computer code.
As long as no one can duplicate the coins, this model works, correct?

Inflation would not occur, only 21 million coins were issued. Works just like the Bitcoin model and you don't have to wait till 2032 or whatever!

Also transactions are now instant! PROBLEM SOLVED

**Comment by sipa** [comment]
"Why dont we simply create 21 million "Bitcoins" that cannot be duplicated?". That's what we did, and the blockchain is part of the system to guarantee that duplication is prevented.
