### ISSUE TITLE
Berkeley DB Version

### ISSUE THREAD

**Issue by knoxcard** [bitcoin/bitcoin#9046]
I compiled my Bitcoin installation with Berkeley DB 4.8.30, is there any way to use the latest version? (6.2.23)

http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html

**Comment by jonasschnelli** [comment]
Yes.
Use `--with-incompatible-bdb` during `./configure`

**Comment by knoxcard** [comment]
Oh Awesome! I will do that as soon as possible.  I feel more secure using the most up to date software.  Hopefully there will not be any issues.  Thank you!

**Comment by jonasschnelli** [comment]
Closing...

**Comment by luke-jr** [comment]
@knoxcard Do note that BDB 6 is under the AGPL license, which you will likely be infringing if you make any source code modifications to your Bitcoin node. And once upgraded, you cannot easily downgrade.

Disclaimer: IANAL

**Comment by knoxcard** [comment]
I ended up deciding NOT to upgrade. I am about to launch my startup and do not need anymore server headaches...thanks for all your input!
