### ISSUE TITLE
Documentation required re mapInFlight

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9054]
I've raised a few queries over the last few months regarding the use of mapInFlight but so far these haven't been answered and I am unaware of documentation that clarifies these queries. The code as it is seems vague and counter-intuitive regarding the current variable and function names, so I think clarification would to help to avoid potential future bugs. Plus, I notice there are currently three open issues relating to InFlight.

When should MarkBlockAsReceived() be run? As soon as the block/cmpctblock/blocktxns is received?

When should MarkBlockAsInFlight() be run? Just before or after pushing the getdata message?

What does "in flight" mean exactly? My understanding was that it is blocks that have been requested and are yet to be received, however, lines in main.cpp say, for example "Blocks that are in flight, and that are in the queue to be downloaded", which seems to be a contradiction, as if they are in a queue this would imply they have not yet been requested.

I am not familiar enough with the various coding methodologies out there, but I would have thought the current naming and usage of these functions would not comply with at least one of them... perhaps not, but even so, I continue to be confused by these functions (I hope I am not too unique in this regard).

I hope this issue can also serve to set in motion (if it is not already) some form of process for ensuring functions like these are documented in some way. I am assuming that the current code is not intentionally obfuscated, but please correct me if this is a false assumption.

**Comment by laanwj** [comment]
Please don't open specific "documentation needed" issues. We all know documentation is lacking, there's no end to this. If you discover any of these things, feel free to write documentation.
