### ISSUE TITLE
Runtime error!

### ISSUE THREAD

**Issue by Hanslo** [bitcoin/bitcoin#9057]
Runtime Error!

Program C:\Program Files\Bitcoin\bitcoin-qt.exe

This application has requested the Runtime to terminate it an
unusal way.
Please contact the application's support for more information.

### Machine specs:
- OS: 14393.351
- CPU: AMD FX(tm)-4100 Quad-Core Processor
- RAM: 10
- Disk size: 1,72 TB
- Disk Type (HD/SDD): SDD

Last end of debug:

2016-11-01 09:37:33 UpdateTip: new best=0000000000000000aa4723eda973954ef2d6731278af0279d07dfe629a29f658 height=276286 version=0x00000002 log2_work=75.017646 tx=29690651 date='2013-12-22 00:12:54' progress=0.093516 cache=88.3MiB(115165tx)
2016-11-01 09:37:33 LevelDB read failure: Corruption: block checksum mismatch
2016-11-01 09:37:33 Corruption: block checksum mismatch
2016-11-01 09:37:40 Error reading from database: Database corrupted

**Comment by joshafest** [comment]
You can try rerun by cleaning app data/bitcoin except wallet.dat 
I think it will help , please keep wallet.dat safe

**Comment by kazcw** [comment]
Was the previous run of bitcoin-core shut down uncleanly? (E.g. crashed for some other reason, power went out, terminated from Task Manager, etc.) If you're not sure, we might be able to tell that if you posted the full debug.log.

**Comment by Hanslo** [comment]
Thanks, but I have done that many times. I suspect it can be my Norton Firewall doing the problems.

Best regards,
Hans N .Løvbræk

Tirsdag 1. November 2016 16:18 CET skrev joshafest <notifications@github.com>:
 
You can try rerun by cleaning app data/bitcoin except wallet.dat
I think it will help , please keep wallet.dat safe

**Comment by Hanslo** [comment]
I suspect now it's maybe my Norton Firewall doing the problems

Best regards,
Hans N. Løvbræk

Tirsdag 1. November 2016 17:30 CET skrev kazcw <notifications@github.com>:
 
Was the previous run of bitcoin-core shut down uncleanly? (E.g. crashed for some other reason, power went out, terminated from Task Manager, etc.) If you're not sure, we might be able to tell that if you posted the full debug.log.

**Comment by Hanslo** [comment]
My Bitcoin Core no more crash, but when I copied my backup wallet inside it stopped to sync.

**Comment by fanquake** [comment]
Closing this as the original issue is fixed. @Hanslo If there is a second different problem, can you please open a new Issue, with more information.
