### ISSUE TITLE
Timeout for headers fetch

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#9068]
When we request headers from a peer (something we do only for one peer when we're in IBD, to avoid duplicating it), there is no timeout. If the peer we're asking it from does not respond, we're stuck.

Fix this by adding a timeout, and integrating it in the block fetch timeout logic (because, when we already have outstanding block download requests, we can't header to appear quickly).

**Comment by rebroad** [comment]
I coded this back in 2013 but it never got merged... I can rebase it if it's now wanted.... It wasn't a fixed timeout but was calculated based on overall latency.

**Comment by fanquake** [comment]
Closing after #10345.
