### ISSUE TITLE
Has SegWit activated?

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9072]
#9051 is one example of a current issue due to SegWit features apparently starting too early. Until SegWit is voted in (at 95% of the mining vote), I would expect that there should not be any rejecting of non-SegWit nodes, such as preferential peering or rejection of standard blocks - both of which seem to have already started happening with recent releases of Bitcoin Core.

What does the function IsWitnessEnabled() mean, for example? I would have thought this means that the 95% mining vote has been reached, but according to recent news articles this hasn't happened yet, so why is this function returning true?

**Comment by laanwj** [comment]
On mainnet: no. On testnet: yes.

**Comment by rebroad** [comment]
@laanwj Thanks for the clarification. Would you be willing to elaborate on why it would be too late to do so at activation?

**Comment by sipa** [comment]
@rebroad https://bitcoin.stackexchange.com and I'll answer there.

**Comment by rebroad** [comment]
@sipa https://bitcoin.stackexchange.com/questions/49452/why-are-0-13-1-core-nodes-connecting-only-to-other-0-13-1-nodes
