### ISSUE TITLE
ambiguous message: "spending bitcoins may not be possible"

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9079]
There is a warning message that says "spending bitcoins may not be possible" which leaves the user unsure whether spending bitcoins will be possible or not. It would be better if it was clear whether the user can or cannot spend bitcoins and what this is dependent upon.

**Comment by MarcoFalke** [comment]
I think this boils down to two cases:

* Spending of bitcoins which are *not yet received* is not possible right now. -> Wait until sync passes the block which includes your transaction.
* Spending of bitcoins which are *already spent* is impossible. -> Wait until sync passes the block which includes your transaction.

**Comment by MarcoFalke** [comment]
@rebroad Obviously pulls to improve the message are welcome
