### ISSUE TITLE
Plans for quantum safe addresses

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9084]
https://bitcoinmagazine.com/articles/bitcoin-is-not-quantum-safe-and-how-we-can-fix-1375242150

This article is recommending Lamport signatures as the solution, and that wallets need to be able to create 1-of-2 multisignature transactions between an unused, old-style Bitcoin address, and an address generated with the new Lamport scheme.

If this information is correct, then Core needs to develop this Lamport patch. This needs to be done in advance of quantum computing becoming a threat to avoid the centralized trust-based scenario mentioned in the article.

**Comment by jonasschnelli** [comment]
Please no future visions on our github issue tracker. Such stuff could be discusses on the bitcoin-discuss mailing list (or maybe bitcoin-dev).
Closing.

**Comment by rebroad** [comment]
@jonasschnelli Not sure what you mean by "future visions", I presume you mean things that haven't happened yet, but then based on this logic we should not code any DoS protection until it happens first, which I hope you are not advocating.

**Comment by dcousens** [comment]
@rebroad mailing list, not here.  This is bitcoin core.

**Comment by sipa** [comment]
@rebroad This is research level stuff that impacts the whole Bitcoin ecosystem, and anyone - including, but not limited to, Bitcoin Core contributors can work on that. Once there is a clear developed solution and design, feel free to bring it to the Bitcoin Core project to include it.
