### ISSUE TITLE
Datadir field displays incorrectly

### ISSUE THREAD

**Issue by Victorsueca** [bitcoin/bitcoin#9089]
### Issue description
The datadir field on the debug window displays incorrectly if the profile folder name is accented.

### How to reproduce
1. Create a profile with accented profile folder name (àèìòùáéíóú)
2. Run bitcoin core with the default datadir
3. Go to the debug window and look at the datadir field

### Expected behaviour
The datadir folder path should display correctly.

### Actual behaviour
Accented characters display as a unknown character question mark.

### Screenshots
![Debug Window](https://cloud.githubusercontent.com/assets/11365204/20029647/41dee90e-a352-11e6-8784-e5a48798d62e.png)

### Confirmed affected versions
The bug has been tested on the following implementations:

- v0.13.1 from source cross-compiled for Windows x64 on a Ubuntu 14.04 enviroment
- 0.13.0 official Windows x64 binary

### Additional debug info
Copying and pasting the text into a program that is known to support accented characters (Such as Notepad++) still displays unknown character symbols.

**Comment by laanwj** [comment]
Should be a one-line patch. Can you try #9094?

**Comment by paveljanik** [comment]
I can't reproduce on OS X with the current master...

**Comment by MarcoFalke** [comment]
@paveljanik I think this only happens on Windows.

Tested with https://bitcoin.jonasschnelli.ch/nightlybuilds/2016-10-18/ 


![6l5r2xgm](https://cloud.githubusercontent.com/assets/6399679/20057944/985419ce-a4ee-11e6-9d4c-54d25af49c1f.png)
