### ISSUE TITLE
GetBlockTemplate + Template doesn't work correctly

### ISSUE THREAD

**Issue by JohnDoesnt** [bitcoin/bitcoin#9092]
Hello, 
tried to retrieve the coinbasetxn but always bitcoind 13.0.1 give me back template without it.

method: "getblocktemplate", params : "capabilities": ["coinbasetxn", "workid", "coinbase/append"]

**Comment by luke-jr** [comment]
Yes, bitcoind only supports coinbasevalue.

**Comment by JohnDoesnt** [comment]
> Yes, bitcoind only supports coinbasevalue.

Thank you for your answer. 

How I can find a correct coinbasetxn ? I need it for your python-blkmaker

**Comment by luke-jr** [comment]
Use address_to_script and init_generation3.

**Comment by luke-jr** [comment]
(Also don't forget append_coinbase_safe2 if necessary to avoid having multiple systems doing duplicate work.)

**Comment by JohnDoesnt** [comment]
Thank you again luke, I still try eloipool software for a full gbt template.
