### ISSUE TITLE
fee estimation: UNLIKELY_PCT is declared but never used

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#9104]
https://github.com/bitcoin/bitcoin/pull/7730 removed priority estimation and so the declaration of UNLIKELY_PCT can now be removed.

Similarly `TxConfirmStats::EstimateMedianVal()` is now only called with `requireGreater` set to `true`, so that logic that function argument can be removed, along with the logic which depends on its value.

I can submit a pull request for this if it's something that would be useful.

**Comment by laanwj** [comment]
Fixed by #9111

**Comment by dooglus** [comment]
#9111 doesn't fix this:

> Similarly TxConfirmStats::EstimateMedianVal() is now only called with requireGreater set to true, so that logic that function argument can be removed, along with the logic which depends on its value.

**Comment by laanwj** [comment]
Ok, why not just file a patch to remove those then.

**Comment by dooglus** [comment]
OK, done. (#9118)

**Comment by laanwj** [comment]
Sorry for making you do this, we should have discussed with @morcos first.
