### ISSUE TITLE
Help pliz release-process

### ISSUE THREAD

**Issue by twepl** [bitcoin/bitcoin#9105]
Can't collect :(

https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md
https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#fetch-and-create-inputs-first-time-or-when-dependency-versions-change

#./bin/gbuild --memory 3000 --commit bitcoin=v0.13.1 ../bitcoin/contrib/gitian-descriptors/gitian-linux.yml

```
--- Building for trusty amd64 ---
Stopping target if it is up
Making a new image copy
qemu-img: target-trusty-amd64.qcow2: Could not open 'base-trusty-amd64.qcow2': No such file or directory
./bin/gbuild:21:in `system!': failed to run make-clean-vm --suite trusty --arch amd64 (RuntimeError)
	from ./bin/gbuild:57:in `build_one_configuration'
	from ./bin/gbuild:285:in `block (2 levels) in <main>'
	from ./bin/gbuild:280:in `each'
	from ./bin/gbuild:280:in `block in <main>'
	from ./bin/gbuild:278:in `each'
	from ./bin/gbuild:278:in `<main>'


```

**Comment by MarcoFalke** [comment]
Make sure to setup the base vm. There is a [guide for Gitian builds using a Debian VM or physical system and LXC](https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md), alternatively you can try the (somewhat spartanic) notes to [set up a KVM](https://github.com/bitcoin/bitcoin/blob/924de0bd75a7f75df65d7d15f9d1587a2e794abf/contrib/gitian-descriptors/README.md).

**Comment by twepl** [comment]
Possibly install without KVM?
I did everything according to instructions, I have this error permanently

`************* WARNING: kvm not loaded, this will probably not work out

--- Building for precise amd64 ---
Stopping target if it is up
Making a new image copy
qemu-img: target-precise-amd64.qcow2: Could not open 'base-precise-amd64.qcow2': Could not open 'base-precise-amd64.qcow2': No such file or directory: No such file or directory
./bin/gbuild:21:in `system!': failed to run make-clean-vm --suite precise --arch amd64 (RuntimeError)
        from ./bin/gbuild:57:in `build_one_configuration'
        from ./bin/gbuild:285:in `block (2 levels) in <main>'
        from ./bin/gbuild:280:in `each'
        from ./bin/gbuild:280:in `block in <main>'
        from ./bin/gbuild:278:in `each'
        from ./bin/gbuild:278:in `<main>'`

**Comment by achow101** [comment]
@twepl Did you follow the instructions to setup gitian building? If so, it uses lxc, not kvm. You need to run `export USE_LXC=1` first.

**Comment by twepl** [comment]
@achow101  Please give detailed instructions

**Comment by achow101** [comment]
Follow the instructions in the gitian-building.md doc to properly setup gitian. If it is too confusing for you, then run the following command from the bitcoin root directory. It's for the automated script which will setup and build everything for you for 0.13.1

```
contrib/gitian-build.sh --setup -b twepl 0.13.1
```

**Comment by twepl** [comment]
@MarcoFalke  Trying to implementation
https://github.com/bitcoin/bitcoin/blob/924de0bd75a7f75df65d7d15f9d1587a2e794abf/contrib/gitian-descriptors/README.md

cd gitian-builder
bin/make-base-vm --suite trusty --arch amd64


```
invoke-rc.d: policy-rc.d denied execution of restart.

Configuration file '/etc/sudoers'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** sudoers (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package sudo (--configure):
 EOF on stdin at conffile prompt
Errors were encountered while processing:
 sudo
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by twepl** [comment]
@achow101 which means tweel?

`contrib/gitian-build.sh --setup -b twepl 0.13.1`

**Comment by achow101** [comment]
The name for the gpg key that you will be signing with.

**Comment by twepl** [comment]
@achow101 
I'm doing the right thing?

cd bitcoin
contrib/gitian-build.sh --setup -b twepl 0.13.1

```
Compiling 0.13.1 Linux

/usr/lib/ruby/2.3.0/psych.rb:471:in `initialize': No such file or directory @ rb_sysopen - ../bitcoin/contrib/gitian-descriptors/gitian-linux.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/psych.rb:471:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:471:in `load_file'
	from ./bin/gbuild:201:in `<main>'
./bin/gsign:52:in `<main>': invalid option: --detach-sign (OptionParser::InvalidOption)
mv: не удалось выполнить stat для 'build/out/bitcoin-*.tar.gz': Нет такого файла или каталога
mv: не удалось выполнить stat для 'build/out/src/bitcoin-*.tar.gz': Нет такого файла или каталога

Compiling 0.13.1 Windows

/usr/lib/ruby/2.3.0/psych.rb:471:in `initialize': No such file or directory @ rb_sysopen - ../bitcoin/contrib/gitian-descriptors/gitian-win.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/psych.rb:471:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:471:in `load_file'
	from ./bin/gbuild:201:in `<main>'
./bin/gsign:52:in `<main>': invalid option: --detach-sign (OptionParser::InvalidOption)
mv: не удалось выполнить stat для 'build/out/bitcoin-*-win-unsigned.tar.gz': Нет такого файла или каталога
mv: не удалось выполнить stat для 'build/out/bitcoin-*.zip': Нет такого файла или каталога
mv: не удалось выполнить stat для 'build/out/bitcoin-*.exe': Нет такого файла или каталога
~/bitcoin

Committing 0.13.1 Unsigned Sigs

~/bitcoin/gitian.sigs ~/bitcoin
fatal: спецификация пути «0.13.1-linux/twepl» не соответствует ни одному файлу
fatal: спецификация пути «0.13.1-win-unsigned/twepl» не соответствует ни одному файлу
fatal: спецификация пути «0.13.1-osx-unsigned/twepl» не соответствует ни одному файлу

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <(null)>) not allowed
~/bitcoin
```

**Comment by MarcoFalke** [comment]
@twepl The convenience script by @achow101 still requires you to go through https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md step by step until in mentions that you can use it.

If there is a particular step that caused problems, please let us know.

**Comment by laanwj** [comment]
I'm pretty sure this is a problem with your local setup, so closing this.

**Comment by legends420** [comment]
Try this even tho its old i got this error and this helped me 
mknod /dev/kvm c 10 232

**Comment by brackmayhall** [comment]
@MarcoFalke see the following links for your error. Essentially there is a bug in the VMbuilder python scripts named dapper.py

https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1618899
https://github.com/devrandom/gitian-builder/issues/139
https://www.reddit.com/r/Bitcoin_Classic/comments/5ms06k/im_having_trouble_replicating_gitian_build/

**Comment by MarcoFalke** [comment]
It seems you can work around that bug by applying the patch that is given in the launchpad as workaround.
