### ISSUE TITLE
CInv::GetCommand(): type=1373179482 unknown type

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9110]
It seems that bitcoin{d,-qt} can be crashed by being sent an inv of an unknown type. At least, it caused mine to:-

```
2016-11-08 00:45:36.470 ProcessMessages(getdata, 397 bytes): CHECKSUM ERROR expected=6d9dbcdf was=a1046737 peer=39585
2016-11-08 00:45:36.481 

************************
EXCEPTION: St12out_of_range       
CInv::GetCommand(): type=1373179482 unknown type       
bitcoin in ProcessMessages()       

2016-11-08 00:45:36.482 ProcessMessages(getdata, 397 bytes) FAILED peer=39585
2016-11-08 00:45:36.487 

************************
EXCEPTION: St12out_of_range       
CInv::GetCommand(): type=1373179482 unknown type       
bitcoin in msghand       

```

If the `throw std::out_of_range(strprintf("CInv::GetCommand(): type=%d unknown type", type));` in protocol.cpp supposed to cause the program to end?

**Comment by laanwj** [comment]
I'm able to reproduce this error in the log by enabling `debug=net` and sending an invalid inv type:
```
2016-11-09 09:40:27 

************************
EXCEPTION: St12out_of_range       
CInv::GetCommand(): type=666 unknown type       
bitcoin in ProcessMessages()       

2016-11-09 09:40:27 ProcessMessages(inv, 37 bytes) FAILED peer=7
```
However the exception is caught and printed, the process does not crash.

**Comment by paveljanik** [comment]
@rebroad: so what "to cause the program to end?"? Was it some local change on your side? Did `bitcoind` really stopped at all?
