### ISSUE TITLE
Error building on Mac Sierra 10.12.1

### ISSUE THREAD

**Issue by DhinNeGeNe** [bitcoin/bitcoin#9127]
Attempting to build Bitcoin on Mac Sierra 10.12.1, and get the following error:
  CXXLD    bitcoind
Undefined symbols for architecture x86_64:
  "Db::verify(char const*, char const*, std::basic_ostream<char, std::char_traits<char> >*, unsigned int)", referenced from:
      CDBEnv::Verify(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool (*)(CDBEnv&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)) in libbitcoin_wallet.a(libbitcoin_wallet_a-db.o)
....
      "boost::filesystem::path::imbue(std::locale const&)", referenced from:
      SetupEnvironment()     in libbitcoin_util.a(libbitcoin_util_a-util.o)
ld: symbol(s) not found for architecture x86_64

I use homebrew and have boost. I uninstalled and reinstalled boost, but not had more luck.

Any pointers on how to fix the error?

**Comment by fanquake** [comment]
Looks like the same issue as #3228.

What version of Boost is installed via brew?
Have you run make clean and retried building?

**Comment by DhinNeGeNe** [comment]
Boost version 1.62.0 is installed. I tried clean/rebuild, same error.

**Comment by laanwj** [comment]
What version of bitcoin are you trying to build?

**Comment by DhinNeGeNe** [comment]
I am building the master.

**Comment by wujun** [comment]
I installed boost by brew and check the info of the package but get the same error:
boost: stable 1.64.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.64.0_1 (12,628 files, 395.7MB)
  Poured from bottle on 2017-07-19 at 15:08:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Options
--c++11
        Build using C++11 mode
--with-icu4c
        Build regexp engine with icu support
--without-single
        Disable building single-threading variant
--without-static
        Disable building static library variant
--HEAD
        Install HEAD version
