### ISSUE TITLE
Failed to run on-target setarch

### ISSUE THREAD

**Issue by twepl** [bitcoin/bitcoin#9134]
I use this manual

https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md

https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#fetch-and-create-inputs-first-time-or-when-dependency-versions-change

How can I solve the problem?

```
Creating build script (var/build-script)
Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:149:in `build_one_configuration'
        from ./bin/gbuild:285:in `block (2 levels) in <main>'
        from ./bin/gbuild:280:in `each'
        from ./bin/gbuild:280:in `block in <main>'
        from ./bin/gbuild:278:in `each'
        from ./bin/gbuild:278:in `<main>'

```
tail -f var/build.log

```
libtool: install: /usr/bin/install -c .libs/libprotoc.a /home/ubuntu/build/bitcoin/depends/work/staging/arm-linux-gnueabihf/native_protobuf/2.6.1-70c104d3b77/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/native/lib/libprotoc.a
libtool: install: strip --strip-debug /home/ubuntu/build/bitcoin/depends/work/staging/arm-linux-gnueabihf/native_protobuf/2.6.1-70c104d3b77/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/native/lib/libprotoc.a
libtool: install: chmod 644 /home/ubuntu/build/bitcoin/depends/work/staging/arm-linux-gnueabihf/native_protobuf/2.6.1-70c104d3b77/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/native/lib/libprotoc.a
libtool: install: ranlib /home/ubuntu/build/bitcoin/depends/work/staging/arm-linux-gnueabihf/native_protobuf/2.6.1-70c104d3b77/home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/native/lib/libprotoc.a
libtool: install: warning: remember to run `libtool --finish /home/ubuntu/build/bitcoin/depends/arm-linux-gnueabihf/native/lib'
 /bin/mkdir -p '/home/ubuntu/build/bitcoin/depends/work/staging/arm-linux-gnueabihf/native_p
```

**Comment by unsystemizer** [comment]
I think the scripts are broken, I tried to work by that document last week and it doesn't work (the doc has bugs, but the scripts may be buggy and the current gitian may have some bugs as well). 
I think you should try the manual procedure and then compare with the scripts. Or wait for someone to tell us what exact environment they use and when they tried (maybe it worked with some older version of gitian).

**Comment by twepl** [comment]
I tried to change the username on ubuntu
Did not help

**Comment by unsystemizer** [comment]
If it were only that simple... As I said I think it's likely multiple bugs in the docs and the code (either the script or gitian or most likely both).

**Comment by twepl** [comment]
**This is the solution!**
The error occurs because of lack of memory

**Comment by MarcoFalke** [comment]
Thanks for letting us know. I will close the issue now.

**Comment by aniket-kumar** [comment]
I don't think that is the solution. I am also facing the same issue. I have sufficient memory on my system. I am just trying to create windows binary file using gitian-build. Any help will be appreciated.

**Comment by twepl** [comment]
I made a small guide for you


https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md

Install VirtualBox VM and debian-8.5.0-amd64-netinst.iso

Writing to the console

```
sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

/etc/init.d/ssh restart

apt-get install git ruby sudo apt-cacher-ng qemu-utils debootstrap lxc python-cheetah parted kpartx bridge-utils make ubuntu-archive-keyring curl

adduser debian sudo

# the version of lxc-start in Debian needs to run as root, so make sure
# that the build script can execute it without providing a password
echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-start" > /etc/sudoers.d/gitian-lxc
echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-execute" >> /etc/sudoers.d/gitian-lxc
# make /etc/rc.local script that sets up bridge between guest and host
echo '#!/bin/sh -e' > /etc/rc.local
echo 'brctl addbr br0' >> /etc/rc.local
echo 'ifconfig br0 10.0.3.2/24 up' >> /etc/rc.local
echo 'iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE' >> /etc/rc.local
echo 'echo 1 > /proc/sys/net/ipv4/ip_forward' >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local
# make sure that USE_LXC is always set when logging in as debian,
# and configure LXC IP addresses
echo 'export USE_LXC=1' >> /home/debian/.profile
echo 'export GITIAN_HOST_IP=10.0.3.2' >> /home/debian/.profile
echo 'export LXC_GUEST_IP=10.0.3.5' >> /home/debian/.profile
reboot
```

**SSH Putty** localhost 22222
user debian

```
sudo apt-get update

sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils

sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler

wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz
echo "76cbf8c52c391160b2641e7120dbade5afded713afaa6032f733a261f13e6a8e  vm-builder_0.12.4+bzr494.orig.tar.gz" | sha256sum -c
# (verification -- must return OK)
tar -zxvf vm-builder_0.12.4+bzr494.orig.tar.gz
cd vm-builder-0.12.4+bzr494
sudo python setup.py install
cd ..

reboot
```

Create a clone VirtualBox VM debian 2

**SSH Putty** localhost 22222
user debian

Writing to the console

```
git clone https://github.com/devrandom/gitian-builder.git
git clone https://github.com/bitcoin/bitcoin
git clone https://github.com/bitcoin-core/gitian.sigs.git

cd gitian-builder
bin/make-base-vm --lxc --arch amd64 --suite trusty

pushd ./gitian-builder
mkdir -p inputs
wget -P inputs https://bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch
wget -P inputs http://downloads.sourceforge.net/project/osslsigncode/osslsigncode/osslsigncode-1.7.1.tar.gz
popd

pushd ./gitian-builder
make -C ../bitcoin/depends download SOURCES_PATH=`pwd`/cache/common
popd
```

**LINUX OS**
```
pushd ./gitian-builder
./bin/gbuild --memory 3000 --commit bitcoin=master ../bitcoin/contrib/gitian-descriptors/gitian-linux.yml
./bin/gsign --signer $SIGNER --release ${VERSION}-linux --destination ../gitian.sigs/ ../bitcoin/contrib/gitian-descriptors/gitian-linux.yml
mv build/out/bitcoin-*.tar.gz build/out/src/bitcoin-*.tar.gz ../
popd
```

**Windows OS**
```
pushd ./gitian-builder
./bin/gbuild --memory 3000 --commit bitcoin=master  ../bitcoin/contrib/gitian-descriptors/gitian-win.yml
./bin/gsign --signer $SIGNER --release ${VERSION}-win-unsigned --destination ../gitian.sigs/ ../bitcoin/contrib/gitian-descriptors/gitian-win.yml
mv build/out/bitcoin-*-win-unsigned.tar.gz inputs/bitcoin-win-unsigned.tar.gz
mv build/out/bitcoin-*.zip build/out/bitcoin-*.exe ../
popd
```

**Mac OS X**

```
pushd ./gitian-builder
./bin/gbuild --memory 3000 --commit bitcoin=master  ../bitcoin/contrib/gitian-descriptors/gitian-osx.yml
./bin/gsign --signer $SIGNER --release ${VERSION}-osx-unsigned --destination ../gitian.sigs/ ../bitcoin/contrib/gitian-descriptors/gitian-osx.yml
mv build/out/bitcoin-*-osx-unsigned.tar.gz inputs/bitcoin-osx-unsigned.tar.gz
mv build/out/bitcoin-*.tar.gz build/out/bitcoin-*.dmg ../
popd
```

**Comment by aniket-kumar** [comment]
I am not using any VM. I am doing this on my machine.I have executed all other commands , only the windows binary build command is throwing error. I applied the changes in my command according to your answer. I am still getting the same error : 
Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
	from ./bin/gbuild:149:in `build_one_configuration'
	from ./bin/gbuild:285:in `block (2 levels) in <main>'
	from ./bin/gbuild:280:in `each'
	from ./bin/gbuild:280:in `block in <main>'
	from ./bin/gbuild:278:in `each'
	from ./bin/gbuild:278:in `<main>'

**Comment by marvic41** [comment]
@aniket-kumar I tried for mac it flashes errors. do you have a procedure to build for mac.
For Linux and Win (32,64) i able to create binaries.

**Comment by DataSaverCoin** [comment]
same issue when i tried to clone a coin. linux wallet works but I cannot compile the damn windows wallet

**Comment by DataSaverCoin** [comment]
OK well i figured out how to fix it in my case.

I was trying to compile deps-win32.yml and keps getting stuck but i took a look at that file.


complated the file: to the ones listed in the inputs folder and zlib-1.2.8.tar.gz was showing a different version  zlib-1.2.11.tar.gz I had to change the reference name in 3 places in this document. then I noticed its checking the sha256sum of the files. I ran them on each and zlib-1.2.11.tar.gz did not match so i replaced it. ran the code again and it completed.....I finally have a folder named "out" in gitian-builder/build


to check the sha256 sum on linux go to the inputs folder and run :  sha256sum filename.tar.gz...good luck man. if you need help hit me up. support@datasaver.org

**Comment by gwpreggae** [comment]
> @twepl I don't think that is the solution. I am also facing the same issue. I have sufficient memory on my system. I am just trying to create windows binary file using gitian-build. Any help will be appreciated.

Did you figure this out? I am stuck here too.

**Comment by caesar-ski** [comment]
> > @twepl I don't think that is the solution. I am also facing the same issue. I have sufficient memory on my system. I am just trying to create windows binary file using gitian-build. Any help will be appreciated.
> 
> Did you figure this out? I am stuck here too.

Did you?? same problem here!

**Comment by caesar-ski** [comment]
Anyone solved this "failed to run on-target setarch x86_64 bash" problem?  I tried a lot of combinations even differnt boost-win32 versions but no success.

**Comment by gwpreggae** [comment]
I really tried to figure it out to no avail. I got linux version working
fine but can't get windows to compile. I've moved on for now to work on
other things.

**Comment by Limecoin-LIME** [comment]
Same Problem here... hours of research so far without success. I will keep you updated and communicate as soon as I have a solution.

**Comment by realcaesar** [comment]
I somehow fixed it but it was so long ago i cant remember sorry.
But there was an solution.
Ps : i made like 6 diffrent Vms till it worked (or just use snapshots)
