### ISSUE TITLE
Outdated information on non-english bitcoin core download page?

### ISSUE THREAD

**Issue by sakamoto1255** [bitcoin/bitcoin#9146]
Hi. I'm Korean Bitcoin core user.
I think information on the download page(https://bitcoin.org/ko/download) that translated to korean guides users 'In order to speed up sync blockchain data, bootstrap.dat (which is linked to torrent file attached in bitcoin.org) might help.'
I've heard that version 0.7.1 and later supports fast synchronization than using bootstrap.dat. 
Therefore, In order to prevent Korean users not to struggle with outdated information, administer of the homepage should edit the page.

**Comment by achow101** [comment]
That is an issue with bitcoin.org and their translations. Go to https://github.com/bitcoin-dot-org/bitcoin.org/issues for issues about their site and https://www.transifex.com/bitcoinorg/bitcoinorg/ for translation issues.

**Comment by sakamoto1255** [comment]
Sorry, I was supposed to upload at different repository. Never mind.
