### ISSUE TITLE
Copying chainstate folder to other computer returns to renew the blockchain data?

### ISSUE THREAD

**Issue by sakamoto1255** [bitcoin/bitcoin#9147]
Hi. I am the owner of a website services blockchain folder to torrent in order to provide users for faster synchronization. 

I've received an issue that copying  blocks and chainstate folder(located in \appdata\bitcoin) may occur core program to change the pasted folder to sub-directory and download the new(!) blockchain(...). 
However, when coping only blockchain folder the core recognizes the data and ranges raw-data. I think downloading blockchain and arranging it spends more time and recources than just download via client. 

I wonder why bitcoin 0.13.0 just recognized both of the folder which bitcoin 0.13.1 doesn't.

**Comment by laanwj** [comment]
There should be no differences between 0.13.1 and 0.13.0 in this regard. Bitcoin Core will never "change a directory to a subdirectory". I suspect a user copy/paste error.

**Comment by sakamoto1255** [comment]
@laanwj Comparing with other samples. Thanks for your comment!

**Comment by MarcoFalke** [comment]
Closing for now.
