### ISSUE TITLE
Wallet RPCs can return stale info due to ProcessNewBlock Race

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#9148]
I know this issue has been pointed out a few times, but didnt see an issue for it here.

After #7946, if you connect a block, then immediately make some RPC request to get the current block information (eg if you're polling to see when a new block comes in) and then immediately request wallet balance/utxos/etc, the information returned can be up-to-date as of the previous block, not the newly-connected one. This is easy to see in some simple test-cases, and I assume would effect some various use-cases that people might be using in the wild. This is a regression in master, so we should fix it for 0.14.

I think we need to be moving more towards these kinds of callback happening in a background thread anyway, so we have two options - change the API significantly and add some kind of "getwalletchainstate" so that people can wait for wallet to be caught up or add a "sleep until wallet is caught up with chainstate as of entry to RPC function" wrapper to wallet calls.

I generally prefer the second option becuase I think the first will create a somewhat confusing API that people are likely to fuck up, and the sleep should generally never be too long unless your wallet is super slow/too many keys.

**Comment by gmaxwell** [comment]
the rpc returning old data right at the time of the block seems fine to me, what isn't fine is it showing old data after various notify messages have fired-- which is I assume an unstated part of what you described?

**Comment by TheBlueMatt** [comment]
Well you can make an RPC call to getbestblockhash, get the current tip, and then /after that/ call getbalance and get the wallet balance for one block back, not up-to-date with the tip (which would break people who poll for updates, as I'm sure some people do). Indeed, its also possible that notify messages have fired, but I'd have to go look at the order of callbacks to verify that.

**Comment by luke-jr** [comment]
Perhaps the solution ought to be to grab a lock on all the wallets before unlocking the blockchain (and unlocking each once they have synced)?

**Comment by TheBlueMatt** [comment]
@luke-jr that would be a layer violation...nothing blockchain-related should have any concept of wallet(s).

**Comment by luke-jr** [comment]
Should we keep a copy of the tip CBlockIndex* on the wallet then, perhaps? Then RPC calls accessing the wallet can block on that wallet matching the blockchain?

**Comment by TheBlueMatt** [comment]
Fixed (temporarily) with #9583 merge.
