### ISSUE TITLE
HELP - no password Electrum wallet .

### ISSUE THREAD

**Issue by Bitoma** [bitcoin/bitcoin#9153]
I installed electrum ,  it has not asked me for the password  it has not shown me the seed. 
I think that this has happened because probably the electum wallet during the new installation has recovered data from an old installation.    
Unfortunately I have not been paying attention to this,   the wallet was  activated immediately and i send bitcoin to it from a bitcoin core wallet.  ,......       Now my bitcoin are in the electrum wallet  installed on my PC and I do not have the password and e seed. 
how can I recover  the bitcoins?    people say that those bitcoin are lost but I can't belive it....they are in my wallet installed in my pc.......
Can you help me please.......?

thank you in advance

**Comment by achow101** [comment]
This is an issue tracker for Bitcoin Core, not tech support, and certainly not for Electrum. Take your questions about electrum to https://bitcointalk.org/index.php?board=98.0 or https://github.com/spesmilo/electrum

**Comment by Bitoma** [comment]
You are right ,  sorry... i did a mistake......

**Comment by sipa** [comment]
This is the issue tracker for Bitcoin Core, not Electrum. You'll have to
ask them.

**Comment by Bitoma** [comment]
yes,   sorry ....i posted in the wrong place..... terribly sorry


________________________________
Da: Pieter Wuille <notifications@github.com>
Inviato: domenica 13 novembre 2016 14.38
A: bitcoin/bitcoin
Cc: Bitoma; Author
Oggetto: Re: [bitcoin/bitcoin] HELP - no password Electrum wallet . (#9153)

This is the issue tracker for Bitcoin Core, not Electrum. You'll have to
ask them.

-
