### ISSUE TITLE
bitcoin.org fork policy vague

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9161]
https://bitcoin.org/en/posts/hard-fork-policy

This page seems to be misleading - it seems to suggest that "hard forks" are in some way worse than "soft forks" when it seems to me that the opposite is true. This conclusion has also been reached by other bitcoin developers. Can this page be clarified? Can "contentious" be defined, for example? 

Soft forks are being proposed as bad because it makes it harder (if not impossible) for older nods to audit correctly - i.e. it intentionally creates a way for invalid transactions to appear valid to older software thereby taking away their ability to detect that they need to upgrade or change their rules. Hard forks on the other hand provide more "informed consent" being more transparent about a change in protocol.

This arguments above (also made by other developers) seem quite logical and persuasive, and therefore if Core has equally strong logical arguments for soft forks being better/preferable, then I think the opportunity is currently being missed to put these forward in the current web page.

**Comment by rebroad** [comment]
https://medium.com/@octskyward/on-consensus-and-forks-c6a050c792e7#.apjir3k5d - an example of another developer who sees hard-forks as superior to soft-forks. I'm inclined to agree with their analysis, so far, which is why I would like to see more conclusive counter-arguments included in the bitcoin.org website.

**Comment by jonasschnelli** [comment]
Stop spamming please.

**Comment by luke-jr** [comment]
@rebroad A hardfork by nature *must* have consensus from the entire community before deployment. Attempts to deploy without such consensus transform it into an altcoin, which is clearly inappropriate for a Bitcoin webstie.

**Comment by rebroad** [comment]
https://www.reddit.com/r/btc/comments/428tjl/softforking_the_block_time_to_2_min_my_primarily/ - yet another credible developer also saying the same thing. @jonasschnelli do you know what "spam" even means?

**Comment by laanwj** [comment]
Stop spamming this. Bitcoin Core is a separate project from "bitcoin.org". If you have beef with anything on their site you should comment there. Though these discussions have been done so many times and people are tired of it so I don't think people will be thankful to you for regurgitating this.

**Comment by rebroad** [comment]
@laanwj Previously this github repository was the place to report problems with bitcoin.org - I apolgise, I was not aware that it had been moved - where is the new location please?

**Comment by laanwj** [comment]
https://github.com/bitcoin-dot-org/bitcoin.org
