### ISSUE TITLE
keep a copy of genesis block [0] using pruning mode

### ISSUE THREAD

**Issue by fflo** [bitcoin/bitcoin#9184]
Hi,

external applications connecting to bitcoind using rpc calls usually check the details of the genesis block to be sure that bitcoind is serving requests correctly.

Enabling pruning mode throws out error messages in this case, because the genesis block seems to get pruned, too:
like i.e. p2pool.util.jsonrpc.NarrowError: -32603 Block not available (pruned data)

Is it possible to keep a copy of the genesis block enabling pruning mode?

**Comment by laanwj** [comment]
Can you be more specific as to which JSON-RPC calls fail due to a missing genesis block?

I would say it is acceptable that they fail if you specifically refer to the genesis block after it gets pruned (like for any other block), but not otherwise.

**Comment by fflo** [comment]
external applications connecting to bitcoin often check some unique details of the genesis block, i.e. p2pool is running a rpc check: getblock 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f on startup [https://github.com/p2pool/p2pool/blob/master/p2pool/bitcoin/networks/bitcoin.py]

So I guess it's probably a good idea to keep a copy of the genesis block available, even if pruning mode is enabled. This would allow external applications to verify that the rpc connection to bitcoin is working as expected.

**Comment by laanwj** [comment]
What details does it need? Wouldn't `getblockheader` be enough?

**Comment by fflo** [comment]
Yes, it's possible to patch p2pool to reduce the genesis block check using `getblockheader` instead of `getblock` to support the pruning mode.

As a quick check I've disabled the genesis block check and p2pool seem to work stable using the pruning mode with reasonable settings, now.

Nevertheless I think it's a good idea not to prune the genesis block in any case. It's like the source DNA of bitcoin ;)

**Comment by MarcoFalke** [comment]
Closing for now, since it has been fixed upstream in p2pool
