### ISSUE TITLE
Context menu options that are not available should be disabled (in transactions tab)

### ISSUE THREAD

**Issue by nopara73** [bitcoin/bitcoin#9192]
### Describe the issue
In Bitcoin QT, under the Transactions tab when right clicking on the transaction the context menu shows more option then it can always handle.

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:  
0. Open QT.  
1. Make an incoming transaction without label.  
2. Go to the Transactions tab.  
3. Rigth click on a transaction and select "Copy label".  

### Actual behaviour
The clipboard will be empty.  

### Expected behaviour
Copies the label. (What does not exist, of course.)

### What version of bitcoin-core are you using?
v0.13.1, Ubuntu PPA.  

### Any extra information that might be useful in the debugging process.
This behaviour is more problematic in edge cases.  
Like when you send funds with JoinMarket. In this case for example the "Copy address" option does not work.  

### Suggestion
I think when something cannot be copied that should not be present in the context menu in the first place.  
  
![](http://i.imgur.com/hLfAgeF.png)

**Comment by laanwj** [comment]
> I think when something cannot be copied that should not be present in the context menu in the first place.

Yes, disabling the option would be the preferable thing to do in that case.
