### ISSUE TITLE
Debug console needs a little documentation on usage

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9195]
It would be nice if the debug console had a little help page of itself, to describe the syntax to issue commands (also the nested ones), and a disclaimer that usage can be dangerous.

Maybe add a debug-console-only command like help that shows how to use nested commands and potentially other advanced tricks, and add 'for more information on using this console type XXX'.

See also:
- https://github.com/bitcoin/bitcoin/pull/7783#issuecomment-248274853
- https://github.com/bitcoin/bitcoin/issues/8544#issuecomment-240970925
- #8912 Console command paths cannot be specified correctly with backslashes

**Comment by lmlsna** [comment]
Is this issue still in need of a pull request?

I know the standard RPC `help` command is accessible through the console, and the scammer warning has already been added. However, there still appears to be little/no documentation about nested commands (or other peculiarities not applicable to the command line RPC).

There is a comment block in [rpcconsole.cpp#L134](https://github.com/bitcoin/bitcoin/blob/6157e8ce3937af3f46d3e7dd922d19d6dc272145/src/qt/rpcconsole.cpp#L134), that gives a quick overview, and I'd be happy to flush that out (either as a doc or as a debug console only help command). I just wanted to make sure this was still needed before starting.

**Comment by jonasschnelli** [comment]
@lmlsna: Yes. A PR that would add some documentation for the nested command syntax would be highly welcome. Not sure if it should be added directly to the console intro or if there should be sort of an "help" icon with more explanations...

**Comment by lmlsna** [comment]
I pushed a PR adding a `help-console` pseudo-command that dumps some explaination and examples.

Not sure if this is the best way of doing it, but it seemed reasonable, and I'm open to suggestions.

**Comment by fanquake** [comment]
Closing now that #11698 is merged.
