### ISSUE TITLE
sendmany no longer works over the GUI

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#9210]
0.13.1 gitian binaries:

```json
>> sendmany "" '{"ad1":0.1, "ad2":0.1}'
<< "14af4b0aa9a792f32e55d3c9c73b2c6356033825d955ae71313f7dc4008234e1"
```

current master self compiled:
```json
>> sendmany "" '{"ad1":0.1, "ad2":0.1}'
<< "sendmany help text"
```

**Comment by jonasschnelli** [comment]
Probably introduced in #7783.
It looks like, that since #7783 we no longer support empty arguments `""` (often used for the default account).
