### ISSUE TITLE
"Make" Error while installing bitcoind. on Mac 10.12.1 sierra 

### ISSUE THREAD

**Issue by genk1** [bitcoin/bitcoin#9228]
When I tried to "make", i get errors below and cannot proceed next step like "which bitocoind"or so.. on the book "o'Reily". Can you please help me out with how to solve this problem.

git - v0.9.0rc1
Homebrew 1.1.1
Homebrew/homebrew-core (git revision 41a3; last commit 2016-11-23)

Thank you very much.

$ make
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
Making all in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CXXLD    test_bitcoin
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pie'
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [test_bitcoin] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by sipa** [comment]
You're using v0.9.0rc1? That's a prerelease from almost 3 years ago. Does the same thing happen with v0.13.1?

**Comment by genk1** [comment]
Thank you. I could install well. 
I was referring the book from 2014. Dec. This causes me a problem.

**Comment by genk1** [comment]
I thought I could solve the problem as I could use the commands "which bitcoind" or "which bitcoin-cli".
but when I use "make" there is still errors left and cannot use "bitcoind"
Here is what i get from make,
Please help me. And I have not much knowledge with command line. sorry and thank you for your help.

$make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/GenkiA/bitcoin/src/build-aux/missing aclocal-1.15 -I src/m4
aclocal-1.15: warning: couldn't open directory 'src/m4': No such file or directory
 cd . && /bin/sh /Users/GenkiA/bitcoin/src/build-aux/missing automake-1.15 --foreign
configure.ac:441: error: required file 'build-aux/compile' not found
configure.ac:441:   'automake --add-missing' can install 'compile'
configure.ac:22: error: required file 'build-aux/config.guess' not found
configure.ac:22:   'automake --add-missing' can install 'config.guess'
configure.ac:22: error: required file 'build-aux/config.sub' not found
configure.ac:22:   'automake --add-missing' can install 'config.sub'
configure.ac:32: error: required file 'build-aux/install-sh' not found
configure.ac:32:   'automake --add-missing' can install 'install-sh'
configure.ac:32: error: required file 'build-aux/missing' not found
configure.ac:32:   'automake --add-missing' can install 'missing'
configure.ac:13: error: required file 'src/config/bitcoin-config.h.in' not found
src/Makefile.am:57: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:57:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:57:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:57:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:57:   its definition is in aclocal's search path.
src/Makefile.am: error: required file 'build-aux/depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
parallel-tests: error: required file 'build-aux/test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
make: *** [Makefile.in] Error 1

**Comment by rebroad** [comment]
@genk1 it looks like you might have deleted some files/directories since running autogen.sh (or confgure) - try running ./autogen.sh and ./configure again. (Admittedly it would be nice if the Makefile was able to intelligently realise this).

**Comment by genk1** [comment]
@rebroad Thanks for you help. I could finally figured out the way with your suggestion.
The reason i couldn't run was "libtool" on autogen.sh, "libevent" on configure. Thank you very much.
