### ISSUE TITLE
Floating point exception during "make"

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9231]
I've been getting this problem when compiling (make check) for well over a month now. It is an intermittent problem, i.e. simply running the command again usually allows the make process to continue until the error occurs again - usually several times during a single "make check" procedure:-

`/bin/bash: line 1: 29417 Floating point exception(core dumped) /bin/bash ../libtool --silent --tag=CXX --mode=link g++ -std=c++11 -Wstack-protector -fstack-protector-all -fPIE -g -O2 -g3 -O0 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -pthread -Wl,-z,relro -Wl,-z,now -pie -o qt/test/test_bitcoin-qt qt/test/qt_test_test_bitcoin_qt-rpcnestedtests.o qt/test/qt_test_test_bitcoin_qt-test_main.o qt/test/qt_test_test_bitcoin_qt-uritests.o qt/test/qt_test_test_bitcoin_qt-paymentservertests.o qt/test/qt_test_test_bitcoin_qt-moc_rpcnestedtests.o qt/test/qt_test_test_bitcoin_qt-moc_uritests.o qt/test/qt_test_test_bitcoin_qt-moc_paymentservertests.o qt/libbitcoinqt.a libbitcoin_server.a libbitcoin_wallet.a libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a libbitcoin_consensus.a crypto/libbitcoin_crypto.a univalue/libunivalue.la leveldb/libleveldb.a leveldb/libmemenv.a -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lboost_chrono -lQtDBus -lQtXml -lQtCore -lQtTest -lQtGui -lQtNetwork -lQtCore -lqrencode -lprotobuf -pthread -lpthread -ldb_cxx-4.8 -lssl -lcrypto -lminiupnpc secp256k1/libsecp256k1.la -levent_pthreads -levent -levent -lanl`

**Comment by jonasschnelli** [comment]
Do you encounter this on a our master branch or on a local modified repository?

**Comment by laanwj** [comment]
Cannot troubleshoot this without a traceback. Some randomized test may be
dividing by zero or this is a CPU or other hw issue we can't tell.

Which test triggers this? Make check creates a log file with the detailed
test output.

**Comment by sipa** [comment]
> Which test triggers this?

I think this is during linking.

**Comment by laanwj** [comment]
If so that means it is either a linker or hw issue. Outside our scope.
Linker bugs are rare. Also no one else ever reported this. I remember
rebroad filed similar issues with crashes during build before so my guess
is a hw issue.

**Comment by rebroad** [comment]
@jonasschnelli it's a slightly modified local repository based off master. I don't think my changes are likely to increase the compilation failure, but if I am the only person seeing this then it might be an unrelated issue - I've not seen any other software failing to compile like this though.

**Comment by dcousens** [comment]
@rebroad does it happen on *purely* master?

**Comment by MarcoFalke** [comment]
@rebroad Could you please run a hardware check (memtest et al) over night or so?

**Comment by dcousens** [comment]
Upstream?
