### ISSUE TITLE
Document RBF settings

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#9232]
v0.13.1.
I've been trying to figure out how RBF works and at first, I couldn't find the settings in the docs.
Once I gathered these from the source, I couldn't get it to work (still get that `txn-mempool-conflict (code -26)`). 

Because I can't get this to work, I can't create a doco PR myself, but I'd like to see the following documented:
* what options need to be added to bitcoin.conf
* is that enough or are any per-tx parameters required as well (I couldn't find any)

**Comment by achow101** [comment]
IIRC nothing needs to be added to the bitcoin.conf file as opt-in RBF should already be enabled by default.

To send a transaction that signals opt-in RBF, at least one input's sequence number must be less than MAX_INT.

**Comment by MarcoFalke** [comment]
@unsystemizer Can you provide exact step to reproduce the txn-mempool-conflict? Also, you might want to enable the option added in #8601 to opt-in with the wallet.

**Comment by unsystemizer** [comment]
Yes I can, but that's not really why I've created this issue. What I want is that once the docs or manpages are improved, noone who RTFM will end up asking what settings have to be enabled for this to work. 
Put another way, IMHO https://github.com/bitcoin/bitcoin/search?utf8=%E2%9C%93&q=walletrbf should contain at least one Markdown or text result, but there are none. One shouldn't need to go thru C++ code to figure this out.

Now, to answer your question: I enabled walletrbf as well as the other one which you didn't mention (mempoolreplacement) and restarted. Then I created 2 signed tx, one with a 0 fee, one with a non-0 fee, and broadcast them in that order using debug console. The 2nd one failed with the above mentioned error. But again, I am not looking for help on how to make this work, but for the settings to be documented somewhere (https://github.com/bitcoin/bitcoin/tree/master/doc/man or wherever appropriate). Once it's documented, I'll read the docs and make it work.

**Comment by achow101** [comment]
@unsystemizer the release notes say

> Transaction replacement can be disabled with a new command line option, '-mempoolreplacement=0'.

That implies that transaction replacement is already enabled by default and command to disable is the given onee.

**Comment by unsystemizer** [comment]
Okay. I tried without mempoolreplacement in the config file as well, also got the same error. So likely my transactions weren't correct.

> To send a transaction that signals opt-in RBF, at least one input's sequence number must be less than MAX_INT.

My input sequence number is identical in the both transactions.
Is there an example or a unit test of for this that we can reference? 

Back to this topic of docs: I just did `bitcoind -help` one more time and had another look, and there's no mempoolreplacement  or walletrdf in the output. Do you agree that these options should be documented as other defaults are?

**Comment by achow101** [comment]
> My input sequence number is identical in the both transactions.
> Is there an example or a unit test of for this that we can reference?

BIP 125: https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki documents what needs to be done.

RBF tests are available at https://github.com/bitcoin/bitcoin/blob/master/qa/rpc-tests/replace-by-fee.py

> Back to this topic of docs: I just did bitcoind -help one more time and had another look, and there's no mempoolreplacement or walletrdf in the output. Do you agree that these options should be documented as other defaults are?

Look more closely, under Node relay options. Here it is in the code: https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L468

It would probably be a good idea to document all default node policy behavior. I will write those.

**Comment by luke-jr** [comment]
`mempoolreplacement` only controls node acceptance of BIP-125 RBF transactions, it has no influence on the wallet.

`walletrbf` causes the wallet to set the flag, but is not supported by any released version of Bitcoin Core. (it is, however, supported by Bitcoin Knots since v0.12.0)

**Comment by MarcoFalke** [comment]
> v0.13.1.

According to 37ac67816afbefe88806e0325b8d3719c411183e this option was added in 0.14.0
