### ISSUE TITLE
ZapWalletTxes should backup the wallet

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9275]
Consider the case where the user has many outstanding unconfirmed transactions which are viable and will confirm. After hitting the depth limit, they read some bad advice on the internet and zap.  Now they've lost information about all their payments.  At a minimum zap should be backing up the wallet like salvage does.

(really zap should be made harder to use foolishly too-- esp now what we have abandon and will presumably have bump sometime soon)

**Comment by laanwj** [comment]
The default zap keeps metadata, right?

**Comment by jonasschnelli** [comment]
I agree it should backup the wallet.

`-zapwallettxes(=1)` does keep the metadata. Though, the transactions(-metadata) are hold in memory during the time of the wallet-recreation, if something goes wrong there, all tx-metadata is lost.

`-zapwallettxes(=2)` does always erase metadata thus backup in a such case would be desirable.

**Comment by gmaxwell** [comment]
Even keeping the metadata is a destructive operation.

I encountered someone who was making payments end ended up with dozens of unconfirmed ones at one point before running into the unconfirmed chain limit. When his transactions stopped relaying he responded by running zapwallettxes based on a forum post.

This made his wallet forget all the unconfirmed payments. He then continued using the wallet, making more payments, -- some of which doublespent the prior ones.  Resulting in a state where he had no idea what was paid, potentially paid, double paid, or not paid at all.-- or what double-spent with what (since he didn't even know what he'd signed before).

Fortunately in his case he has backed up the wallet first, so the information was all recoverable. But I was horrified enough to open this issue. :)

**Comment by MarcoFalke** [comment]
```
$ ./src/bitcoind -zapwallettxes 
Error: -zapwallettxes has been removed. If you are attempting to remove a stuck transaction from your wallet, please use abandontransaction instead.
