### ISSUE TITLE
test_bitcoin fails valgrind

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#9278]
On recent master, test_bitcoin generates new valgrind warnings, specifically, rpc_tests.cpp:91 calls getnetworkinfo(), which, on rpc/net.cpp:437 looks up the connman's nLocalServices, which were never initialized (normally this would happen with CConnman::Start).

@theuni might want to take a look here.

**Comment by theuni** [comment]
Thanks. This really needs an Init() that the ctor and Start both call.

Will fix.

**Comment by achow101** [comment]
This is still a problem. Any fixes yet? @theuni

**Comment by fanquake** [comment]
Was this fixed by #10977 ?

**Comment by achow101** [comment]
Looks fixed to me.
