### ISSUE TITLE
bitcoin-tx locktime - sequence

### ISSUE THREAD

**Issue by wargo32** [bitcoin/bitcoin#9285]
When setting _locktime_ with _bitcoin-tx_ it doesn't update _sequence_ to turn this feature on.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
