### ISSUE TITLE
Adding fixed seed nodes as DNS doesn't seem to be available.

### ISSUE THREAD

**Issue by shouhuas** [bitcoin/bitcoin#9287]
fork  a  bitcoin
the node:
bitcoin.conf
`rpcuser=Ulysseys
rpcpassword=YourSuperGreatPasswordNumber
addnode=192.168.26.131
addnode=192.168.26.132
addnode=192.168.26.133
rpcport=9332

but debug.log
`Adding fixed seed nodes as DNS doesn't seem to be available.`
`

**Comment by paveljanik** [comment]
This is only debug message when there is no connection at the start. Or do you see some issue?

I think you should use `connect=` in your case.

**Comment by shouhuas** [comment]
@paveljanik 
I had did ,but

connect() to 192.168.26.133:1333 failed after select(): Connection refused (111)

**Comment by paveljanik** [comment]
Why is it trying to connect to port 1333?

**Comment by shouhuas** [comment]
because .
try  create my coin

**Comment by paveljanik** [comment]
So let's close this issue please as there is no issue.

**Comment by shouhuas** [comment]
can you  teach me .create my coin

**Comment by MarcoFalke** [comment]
We don't provide support for non-bitcoin-core code here.
