### ISSUE TITLE
Make: Error 4 all recursive

### ISSUE THREAD

**Issue by bitafterbit** [bitcoin/bitcoin#9320]
### Machine specs:
- OS: Ubuntu 14.04
- CPU: 1 Core
- RAM: 512
- Disk size: 25GB
- Disk Type SSD

Hello, I seem to be having an issue when executing the make command.
`root@vps:/usr/local/src/bitcoin-0.9.2# make
Making all in src
make[1]: Entering directory `/usr/local/src/bitcoin-0.9.2/src'
make  all-recursive
make[2]: Entering directory `/usr/local/src/bitcoin-0.9.2/src'
Making all in .
make[3]: Entering directory `/usr/local/src/bitcoin-0.9.2/src'
  CXX      init.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[3]: *** [init.o] Error 4
make[3]: Leaving directory `/usr/local/src/bitcoin-0.9.2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/src/bitcoin-0.9.2/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/bitcoin-0.9.2/src'
make: *** [all-recursive] Error 1
root@vps:/usr/local/src/bitcoin-0.9.2#
`

I've tried it on 3 different distros, all with fresh installs. Debian, Ubuntu 14.04 and 16.04.

All gave me the same error message when making, not sure what I'm doing wrong :/

I've tried doing what current issues have fixed but it still hasn't worked!

**Comment by paveljanik** [comment]
0.9.2 -> Use current master
Only 512MB RAM...

**Comment by bitafterbit** [comment]
Figured it out, using: ./configure CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768"

fixed it :D

**Comment by MarcoFalke** [comment]
Would you mind to share your rationale for choosing 0.9.2 over 0.12.1 or 0.13.1?

**Comment by bitafterbit** [comment]
The guide I followed provided the wget for 0.9.2, I didn't know about the newer versions 0.0
