### ISSUE TITLE
how to make bitcoin core setup fast ?

### ISSUE THREAD

**Issue by almoharebh** [bitcoin/bitcoin#9321]
I try to install bitcoin core from 3 days but still sync with net work .
how to make load fast

**Comment by jonasschnelli** [comment]
If you have enough RAM, use `-dbache=4000` (4GB of utxo set cache).

**Comment by laanwj** [comment]
This is a issue (bug tracker), not a questions forum.
Next time use the stack exchange: https://bitcoin.stackexchange.com/
