### ISSUE TITLE
MinRelayFee algorithm revist

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9328]
Currently, when looking at the historical MinRelayFee over time, it's usual pattern is to suddenly jump high when the Memory Usage reaches 100% to then slowly decrease until the same happens again. This causes wildly fluctuating MinRelayFees.

Intuitively I feel that the maths could be improved such that the MinRelayFee goes up prior to reaching 100% utilization such that an equilibrium can be reached where the memory utilization rarely reaches 100% and the MinRelayFee stays fairly constant (save for influences by market dynamics). For this to be possible the algorithm needs to change to at least allow it to increase in situations other than reaching 100% utilization.

**Comment by paveljanik** [comment]
Please change the subject to "Predict the future".

**Comment by rebroad** [comment]
@paveljanik I appreciate the levity :) I think the future does not need to be predictable for what I am suggesting but perhaps I am not being clear in what I am proposing. I am proposing that the algorithm tries to avoid sudden jumps, so for this to happen it needs to be something akin to the physics of two magnets opposing each other - i.e. when it gets nearer to being full the MinFeeFilter goes up at a rate such that it is unlikely to become full.

There may need to be some mathematical differentiation to achieve this where the speed at which 100% is being reached if used to decelerate it enough to stop it being reached. Inertial dampening I think might be the term for it.

If I am missing something here, please let me know.

**Comment by MarcoFalke** [comment]
Can you explain the technical advantages of such approach?
