### ISSUE TITLE
How to verfing Bitcoin Core Release Signing Keys

### ISSUE THREAD

**Issue by almoharebh** [bitcoin/bitcoin#9341]
How to verfing Bitcoin Core Release Signing Keys

**Comment by MarcoFalke** [comment]
Currently there is only a single release signing key and you can only
verify it indirectly, i.e. by trusting a person or a chain of persons
who trust Wladimir: Wladimir handles the release key and signed it
with his personal key. Wladimir's personal key is again signed by a
number of people... If you happen to know some of those people, you
can verify their key and thus verify the release signing key. (Given
that they properly verify pgp keys)

Detailed steps can be found in
https://www.reddit.com/r/Bitcoin/comments/4y8m76/0130_binary_safety_warning_bitcoinorg/d6mao05/
(requires basic knowledge about pgp)

Alternatively you can verify a Bitcoin Core Release by recreating it
from the source. Even tough each released tag is signed with Wladimirs
personal key, it is not required to verify the signature in this case.
Instead, you follow the gitian guide for the released git tag (details
in the /doc folder). And finally you verify your gitian result again
one or more other gitian results that are signed by persons you trust.
For example, you can find the signed results for 0.13.1 linux here:
https://github.com/bitcoin-core/gitian.sigs/tree/master/0.13.1-linux
(Again, this requires you to set up pgp and go to a key signing party)

Further reading: https://www.reddit.com/r/Bitcoin/wiki/verifying_bitcoin_core

**Comment by almoharebh** [comment]
I use Gpg4win  but I don't know the step to verify the Bitcoin Core Release. can you give me the instruction to verify released .

**Comment by MarcoFalke** [comment]
Sorry, we don't provide software support. I am sure you will get an answer on https://bitcoin.stackexchange.com/ if you let them know which software you are using.
