### ISSUE TITLE
Ambiguous message: Chain state database corruption likely.

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9360]
In validation.cpp, this is a warning message that can be produced, but it is ambiguous as it could mean either:-

1) Chain state database corruption is likely the reason for the message (and the large fork reported is a false alarm).

or

2) Chain state database corruption is likely to occur (or has occured?) as a result of this (referring to the previous sentence of "Large valid fork found, forking the chain")

**Comment by laanwj** [comment]
It means it is likely that there is chainstate corruption, that is what the message warns about. Feel free to improve the message accordingly.
