### ISSUE TITLE
Could not link against boost_system !

### ISSUE THREAD

**Issue by rg83rg** [bitcoin/bitcoin#9383]
Ubuntu 14.04

On ./configure I get the above error. please can you assist

Terminal output

https://paste.ubuntu.com/23656040/

**Comment by sipa** [comment]
Please follow the build instructions (https://github.com/bitcoin/bitcoin/blob/v0.13.1/doc/build-unix.md). It will tell you how to install all dependencies for common Linux distributions, including Ubuntu.

**Comment by rg83rg** [comment]
I have followed but still receive this error

**Comment by sipa** [comment]
Have you run this line?

> sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev

**Comment by rg83rg** [comment]
Sipa, sorry, I did not see your reply and was referring to a change in the error. That done the trick. Thanks you

**Comment by ViacheslavUKR** [comment]
Dear Sepa. You answer is wrong. Look please to this screen. Of course this library is installed. But compilation process produced error. **configure: error: Could not find a version of the boost_system library!**
![Docker-T252020_0142571](https://user-images.githubusercontent.com/20413407/103111181-df25ef80-4652-11eb-8faf-c6b23ba72ee3.png)
