### ISSUE TITLE
configure: error: Could not find a version of the boost_program_options library!

### ISSUE THREAD

**Issue by rg83rg** [bitcoin/bitcoin#9385]
ubuntu@ubuntu:~/bitcoin$ sudo ./configure --disable-wallet --enable-logging --enable-debug --enable-dht --with-boost-libdir=/usr/lib/x86_64-linux-gnu

checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not find a version of the boost_program_options library!
ubuntu@ubuntu:~/bitcoin$

**Comment by sipa** [comment]
Please stop spamming.

I've asked you a question in #9383.
