### ISSUE TITLE
Wallet ancestor sanity-check ignores sigops

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#9392]
As noted at in the discussion for #9262 (see https://github.com/bitcoin/bitcoin/pull/9262#discussion_r93130302 and https://github.com/bitcoin/bitcoin/pull/9262#discussion_r93126373) the version of #9262 merged for 0.13.2 backport doesnt take into account sigops.

The real fix for this is to provide a decent API from mempool to query if a transaction would violate the mempool's limits.

**Comment by TheBlueMatt** [comment]
This isnt so trivial, as it turns out...the sigops stuff needs access to a CCoinsViewCache with all of a transaction's inputs, which is hard to generate from wallet. Probably untag for 0.14, and maybe just drop this one alltogether (I dont think it matters all that much?)

**Comment by instagibbs** [comment]
@TheBlueMatt This is why I originally didn't do it. I agree this is likely out of scope for 0.14.

**Comment by MarcoFalke** [comment]
Removed 0.14 tag as per current irc log.

**Comment by adamjonas** [comment]
>  Probably untag for 0.14, and maybe just drop this one alltogether (I dont think it matters all that much?)

Closing for lack of movement (and low priority).
