### ISSUE TITLE
CentOS Test Failures

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#9394]
Someone on the mailing list was reporting test failures on 0.13.0 and 0.13.1:

For 0.13.0 I had to do

export LANG=en_US.utf8

before running the test suite. I build in clean chroot build environment to avoid accidental linking to non-standard libraries, and in that environment the LANG is normally set to C as LANG normally doesn't matter for compiling software that is expected to run regardless of what the LANG is.

That I believe was fixed in 0.13.1.

In 0.13.1 the error is

Running test/bitcoin-util-test.py...
Traceback (most recent call last):
  File "./test/bitcoin-util-test.py", line 12, in <module>
    "bitcoin-util-test.json",buildenv)
  File "/builddir/build/BUILD/bitcoin-0.13.1/src/test/bctest.py", line 54, in bctester
    bctest(testDir, testObj, buildenv.exeext)
  File "/builddir/build/BUILD/bitcoin-0.13.1/src/test/bctest.py", line 26, in bctest
    outputData = open(testDir + "/" + outputFn).read()
FileNotFoundError: [Errno 2] No such file or directory: './test/data/blanktx.json'
make[3]: *** [check-local] Error 1
make[3]: Leaving directory `/builddir/build/BUILD/bitcoin-0.13.1/src'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/builddir/build/BUILD/bitcoin-0.13.1/src'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/builddir/build/BUILD/bitcoin-0.13.1/src'
make: *** [check-recursive] Error 1

0.13.0 test works just fine (once the LANG is set to something utf8)

**Comment by MarcoFalke** [comment]
I tried 03422e5 on centos7:

```sh
git checkout 03422e5 && ./configure  --with-incompatible-bdb && make -j 2 check
```

and it worked fine.

**Comment by laanwj** [comment]
> before running the test suite. I build in clean chroot build environment to avoid accidental linking to non-standard libraries, and in that environment the LANG is normally set to C as LANG normally doesn't matter for compiling software that is expected to run regardless of what the LANG is.

Yes IIRC I fixed this in one of the OpenBSD/FreeBSD pulls, there LANG is not set at all by default. Unfortunately the C library as well as boost, as well as Python, have unexpected dependencies on the locale so these kind of problems are hard to avoid. Might make sense to do one of the Travis runs without LANG or with LANG=C @theuni

The second (missing blanktx) issue should be fixed by 23208ac (#9376). That issue only existed in master and I'm surprised you're encountering it on the 0.13 branch?

**Comment by TheBlueMatt** [comment]
Yea, I'm betting they checked out the wrong branch, figured I'd open here to make sure others saw it. Feel free to close now.

**Comment by laanwj** [comment]
Ok, closing then.
