### ISSUE TITLE
change address in send dialog is ignored if its private key is unknown

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#9410]
If I try to send change to an address in a different wallet, I see the message "Warning: Unknown change address" and the change is sent to a new address in the current wallet. There is no indication my request to use a specific change address is being ignored.

See [this reddit post](https://www.reddit.com/r/btc/comments/5jsj6d/im_doing_something_wrong_with_change_address_but/) for an example of this behavior confusing a user.

I think it would be better to use the provided address whether or not the private key is available, so long as the warning is provided when we don't know the private key.

**Comment by fanquake** [comment]
Copying in the Reddit comment and images:

"""
Can someone please explain what is happening here?
Note: Everything done on testnet so the only value lost was time.
In this first screenshot:
![1](https://cloud.githubusercontent.com/assets/863730/21445090/c4c2fe4c-c8ef-11e6-9342-257cb55086bf.png)
it shows that:
1 I am making a payment to mwCwTceJvYV27KXBc3NJZys6CjsgsoeHmf
2 I am sending change to mogwtVo5bDzJRWsVNLEpfDDt5dXHcC2tf5 <- cold wallet address.
The second screenshot shows extra translation fees being calculated:
![2](https://cloud.githubusercontent.com/assets/863730/21445093/c970f1f6-c8ef-11e6-8905-4abfeebdaf9d.png)
The third screenshot shows the change going to a completely different address, change went to n18wMXVBXoE134AQsd7GcQKnjBah2MsPdD
![3](https://cloud.githubusercontent.com/assets/863730/21445095/cd797dd6-c8ef-11e6-8ab7-77a2b552be96.png)
I have tested this twice, and twice the change went to an address other than the address I specified.
What's going on?
"""

**Comment by jonasschnelli** [comment]
A custom change address thats not part of the wallet can result in lost funds. We need to be careful.
But if one provides a non-wallet-owned change address, it should never fallback to an internal/different change address (without warning and accepting by the user).

If its not already the case (need to retest), we should warn significant but then accept the custom non-wallet-change address.

This is part of CoinControl and we can expect expert users here.

**Comment by sylvandb** [comment]
Using 13.0 on linux the only warning is "unknown change address" which to me does not inform that it will ignore my input and send instead to a new generated wallet change address. Which is what happens.

**Comment by dooglus** [comment]
@jonasschnelli 

> A custom change address thats not part of the wallet can result in lost funds

It is possible, for sure. But ignoring the provided change address and instead sending the change to a new address could also result in lost funds since the user will be expecting the change to be in the address he specified (in a different wallet) and may feel safe to delete the wallet.dat file because he thinks he has just emptied it.

**Comment by jonasschnelli** [comment]
Fixed by #9413

**Comment by sylvandb** [comment]
Hooray!  Thank you! :)
