### ISSUE TITLE
Live rescans don't convert sent payments to payment-to-self until restart

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#9421]
1. Use vanitygen to create a key/address pair.
2. Send bitcoins to the address from your Core wallet.
3. Import the private key to the Core wallet (with rescan).
4. Observe transaction list still shows merely the send.
5. Restart the client.
6. Observe the transaction list now shows payment-to-self correctly.

Expected behaviour: The rescan should change the transaction immediately.

Not sure if this affects RPC, but it does at least the GUI.

**Comment by aureleoules** [comment]
I have reproduced the bug with the same steps (used Electrum instead of vanitygen).
It doesn't seem to affect the RPC `listtransactions`, only the GUI.

One way to fix this would be to reload the wallet on the GUI after a rescan?

**Comment by jarolrod** [comment]
> One way to fix this would be to reload the wallet on the GUI after a rescan?

Instead of closing and re-opening the wallet, we should handle the event, updating the UI. Appears to be an issue of just not handling the signal properly.

**Comment by hebasto** [comment]
Moved to bitcoin-core/gui#636.
