### ISSUE TITLE
[RPC]  Include monotonically updating total-work-done metric in any relevant query response 

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#9426]
RPC responses should include a monotonically updating metric that guarantees to be correct any value equal or less-than itself.

The only monotonically updating metric in bitcoin is the 'total-work-done'. That even in the case of a reorg, must always update monotonically.

PRC responses should have a 'correct as of: (total-work-done)' metric.

Clients of the RPC can sort responses by the (total-work-done) metric to find the most current result.  (say if querying a few servers at once).

**Comment by MarcoFalke** [comment]
That wouldn't work in case of reorgs. An alternative would be to increment a counter for each rpc request and/or pass the block hash of the current tip.
