### ISSUE TITLE
[Wallet] Implment Wallet Pruning

### ISSUE THREAD

**Issue by da2ce7** [bitcoin/bitcoin#9429]
As mentioned by @gmaxwell on IRC: https://botbot.me/freenode/bitcoin-core-dev/2016-12-22/?msg=78338240&page=4

A pruned wallet is a wallet that has had some transactions removed.

The is very useful for merchants who deal with very large (say 500mb+) wallets.

Possible command:

Prune Wallet:  (possibly a useful command for privacy)
[int: start block height] - Start Range (inclusive)
[int: end block height] - End Range - (exclusive)
(bool: keep unspent, default true) - If transaction has unspent output, exclude from removal.
(bool: test run, default true) - Return transactions that would be removed, but don't execute.
(list of txid: excluded transactions) - List of transactions that should be not removed.
(bool: error if excluded txid not found, default true) - If excluded txid not found, don't continue.

**Comment by MarcoFalke** [comment]
How is this issue different from #9409?

**Comment by da2ce7** [comment]
Sorry. Indeed. Duplicate.
