### ISSUE TITLE
Opening the 13.2rc1

### ISSUE THREAD

**Issue by FabioCarpi** [bitcoin/bitcoin#9431]
![2016-12-26](https://cloud.githubusercontent.com/assets/6897978/21484744/e82a5dbc-cb7e-11e6-9bcc-1c80446aa56a.png)

**Comment by MarcoFalke** [comment]
@FabioCarpi Mind to share which version you are up(/down)grading from and what config parameters you set?

**Comment by FabioCarpi** [comment]
Upgrading from 13.1 and no parameters

--- Mensagem Original ---

De: "MarcoFalke" <notifications@github.com>
Enviado: 27 de dezembro de 2016 13:03
Para: "bitcoin/bitcoin" <bitcoin@noreply.github.com>
Cc: "Fabio" <fabiocarpi@hotmail.com.br>, "Mention" <mention@noreply.github.com>
Assunto: Re: [bitcoin/bitcoin] Opening the 13.2rc1 (#9431)



@FabioCarpi<https://github.com/FabioCarpi> Mind to share which version you are up(/down)grading from and what config parameters you set?

-

**Comment by sipa** [comment]
Do you get the same problem if you try opening with 0.13.1 again?

**Comment by MarcoFalke** [comment]
ping @FabioCarpi Do you get the same problem if you try opening with 0.13.1 again?

**Comment by FabioCarpi** [comment]
0�	*�H��
��0�10	+0�	*�H��
��$���Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: 7bit

sorry for being late
Apparently it was a mistake in my blockchain files
Redownload fixed
��:0�60��0
	*�H��
0o10	USE10U
AddTrust AB1&0$UAddTrust External TTP Network1"0 UAddTrust External CA Root0
000530104838Z
200530104838Z0o10	USE10U
AddTrust AB1&0$UAddTrust External TTP Network1"0 UAddTrust External CA Root0�"0
	*�H��
�0�
���3��-9�N[��l���#����3��)L}���J�������mPZ��)�Z��Iz�.�����78->�A�pV��O?�2�t���T��_x��@<�a�^����jP���N���q��q�P`
��8����i&��L�O#�:O������io��B�kD����mA_rZq7�ye�Y��7�/
��r��8r��E�]*}�������D��+�C%�a�ijX#��3�VuY��)�F�
+e��Bo��{���]S�4Z'���0��0U���z4�&���&T���$�T0U0U�0�0��U#��0������z4�&���&T���$�T�s�q0o10	USE10U
AddTrust AB1&0$UAddTrust External TTP Network1"0 UAddTrust External CA Root�0
	*�H��
�����%��#����A����y��[#6e���w��AlG`�Q��2=���&����Z���xy�!��L
�5���Q�����~N�p�9�Q-�����Fu�$���B���pg��5J�+z�QB�zc�����+�6�
��c~y{�	
@�j�������BQ�E���b!h C<��|�$���s�?V18�q�����.�����1�DL�sIv`����k.��LZ�y 
.��c&U����Z{����N�0��0����#��S��anzTgk!0
	*�H��
0o10	USE10U
AddTrust AB1&0$UAddTrust External TTP Network1"0 UAddTrust External CA Root0
141222000000Z
200530104838Z0��10	UGB10UGreater Manchester10USalford10U
COMODO CA Limited1A0?U8COMODO SHA-256 Client Authentication and Secure Email CA0�"0
	*�H��
�0�
���
�zSNpR�V�&��I���Q���ZI���`�zQB�y��"�aN��v#
�J�	�n�=�������.CRC|�2P��OZ����%�{��0d���V��*$3��D�i��FK�3��@�����@���:�*S��= a<U��Nv%!)��|qvO��_���T���{5R���"=,0-1Y�R7�3i-C������wgQ���'���8v���8�����I���s�:2���:=F:WtaP��@?�����!��0�0U#0����z4�&���&T���$�T0U�ak�����O�g��������0U��0U�0�0U%0++0U 
00U 0DU=0;09�7�5�3http://crl.usertrust.com/AddTrustExternalCARoot.crl05+)0'0%+0�http://ocsp.usertrust.com0
	*�H��
�*n�U�:������U��ka+�	#��fjo����w^a�}�������[jr
A���X�&���M������X�"c�R��6�}X���;c���s����{����B#����M>�K��-���BK�i���74�{����:��O�4n�e�������6����d)5����q�C��>���2S�v���4�,��J��
������ZBj#!�e����~��� b��:,Y��3�8����zy�J&�|���0�I0�1�B���RRQ��8,|��0
	*�H��
0��10	UGB10UGreater Manchester10USalford10U
COMODO CA Limited1A0?U8COMODO SHA-256 Client Authentication and Secure Email CA0
161023000000Z
171023235959Z0*1(0&	*�H��
	fabiocarpi@hotmail.com.br0�"0
	*�H��
�0�
��
�s0`�uZ��r��^B��_
'�{/R����{���+J>��5�
�A7!����!1������X���as��k(��Ay�?�DE�����E��=Z�t�Xp��6
����e�4�3��"`������OQTz���k�/.�������i�������wY���������W.8!�L5��	!uZB!3� 8����
B��^.fZ���q\o@l��	��l���@�$��(Pj6�$3������G��M
��D��68���R��g`�#�>��p��"�:,������N��=2"��Mc���O�U��.T(kr(��B��j�'4�Q��	O(��3,���tZ��Z��	���P�qS��)�}�\�p�G�p����b_,���x��@�����r��QwB��[�����s^V���\��w�L������l�AWBaSE'������G�&���:�g�t
�������,l]�,��
�5��j��g���M\��(}�V]����������iW���0��0U#0��ak�����O�g��������0Ul�h��AT`���S:+0���
0U��0U�00 U%0++�10	`�H��B 0FU ?0=0;+�10+0)+https://secure.comodo.net/CPS0]UV0T0R�P�N�Lhttp://crl.comodoca.com/COMODOSHA256ClientAuthenticationandSecureEmailCA.crl0��+��0��0X+0�Lhttp://crt.comodoca.com/COMODOSHA256ClientAuthenticationandSecureEmailCA.crt0$+0�http://ocsp.comodoca.com0$U0�fabiocarpi@hotmail.com.br0
	*�H��
�Y�
�8qJ������t�l��eW��{C��n���t�+�N�

��h{�%gCa-��E�_�+.$+�G�������X��_���$��f?�id��HY<�K$J�*�u�D��
����x7�N�`��������r.s�M�_C����5D���C��ROqe-�,����0���rJ��;n*��h�j����6�p2m�}\�rg��{�wN�%�n�)k�D)�!��/���GY�����w�1�Y0�U0��0��10	UGB10UGreater Manchester10USalford10U
COMODO CA Limited1A0?U8COMODO SHA-256 Client Authentication and Secure Email CAB���RRQ��8,|��0	+��}0	*�H��
	1	*�H��
0	*�H��
	1
170102165507Z0#	*�H��
	1�L8k�w4�{����o����0��	*�H��
	1��0��0	`�He*0	`�He0
*�H��
0	`�He0*�H��
�0
*�H��
@0+0	`�He0	`�He0	`�He0��	+�71��0��0��10	UGB10UGreater Manchester10USalford10U
COMODO CA Limited1A0?U8COMODO SHA-256 Client Authentication and Secure Email CAB���RRQ��8,|��0��*�H��
	1�����0��10	UGB10UGreater Manchester10USalford10U
COMODO CA Limited1A0?U8COMODO SHA-256 Client Authentication and Secure Email CAB���RRQ��8,|��0
	*�H��
���i�"���f
���iQ�K*��b����������R��V����amh��.��Z�9w��@���Z����6�SJ������r�����&�	����:T��2�q'�����g,��Z�%�'��8<�6EB$�q&�� ����;��7����v�5N���� a3������	�)���B��]���!F�H&������Uz�������N��Y��Y*n���������X�D�[���&�����N��^L����=j#��X�������������4k
YN8w0��ifK��j��T�q��_6���c��"{���������H���cj��B�������L�@�l�j�n��������`|�t��Mg�b"��r��L,�b
mM���d���>��;�#��x�������5��;��}�W��F{��%,�#Y���x���of�K�b#�3X������jx��/X����t�8�T
��l}.2�B�v�q�D���'�v$
