### ISSUE TITLE
Can't connect through proxy on winXP

### ISSUE THREAD

**Issue by sanyanet2** [bitcoin/bitcoin#9432]
The client just start listening TCP 8334 and thats it.
Though it should use sock5 proxy from the network settings and sync with the network like bitcoin core of version .0.8.6 (just checked) do it.

OS winxp x32
Bitcoin Core 0.13.1

**Comment by fanquake** [comment]
@sanyanet2 Please be aware that as of version 0.13.1, Windows XP is no longer officially supported by Bitcoin-Core. See the Compatibility section of the [release-notes](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.13.1.md#compatibility).

**Comment by laanwj** [comment]
Yes, windows XP is dead.
