### ISSUE TITLE
Bad allocation in Raspberry Pi

### ISSUE THREAD

**Issue by Frederic94500** [bitcoin/bitcoin#9434]
Hello!

I run a full node in a Raspberry Pi 3 (OS: Raspbian (lastest)) with 1 To of Hard Drive where the blockchain is stocked and then, I have this error:

> EXCEPTION: St9bad_alloc       
> std::bad_alloc       
> bitcoin in ProcessMessages()

I don't know what is this and after this error, I have a lot of errors!

[http://pastebin.com/m572ySGj](url)

After this, the blockchain is corrupted!

PS: My English is not very good, sorry!

**Comment by fanquake** [comment]
It looks like you are running out of memory. How much do you have available?

**Comment by Frederic94500** [comment]
@fanquake It's a Raspberry Pi 3 so 1 Gb of RAM

**Comment by Frederic94500** [comment]
Oh I forgot a thing, the node was run during almost a day

**Comment by jonasschnelli** [comment]
Your node ran out of ram.
Can you post your `bitcoin.conf` or the startup arguments you have provided?
Try to reduce memory consumption.`-dbcache=100` and `-maxmempool=100` maybe.

Also, have a look at the ram consumption of other apps on your RPI.

**Comment by Frederic94500** [comment]
I don't have bitcoin.conf, but the configuration is in one command:

`./bitcoind -server -rpcuser=pi -rpcpassword=XXXXXX -disablewallet -datadir=/media/pi/9E56F5CB56F5A3E5/Bitcoin -addnode=192.168.0.12 -listen -timeout=10000`

I think it's the maxmempool.
What is the best configuration for RPI?

**Comment by jonasschnelli** [comment]
> What is the best configuration for RPI?

Depends on your use-case.
If you want to estimate fees (run a wallet or something similar), you shouldn't set it to low. Maybe 100MB is enough.
If you don't need 0-conf and a mempool, try the `-blocksonly` mode.

**Comment by Frederic94500** [comment]
@jonasschnelli I want a full node to support Core. I don't know if this config is good.

`./bitcoind -server -rpcuser=pi -rpcpassword=XXXXXX -disablewallet -datadir=/media/pi/9E56F5CB56F5A3E5/Bitcoin -addnode=192.168.0.12 -listen -timeout=10000 -maxmempool=75 -maxconnections=150`

**Comment by jonasschnelli** [comment]
Whats the reason for the `-addnode=192.168.0.12` (do you have a local node running there?).
`-maxconnections=150` can also be a thing to reduce RAM. 125 is default. Maybe go down to 32 if you have further out-of-memory issues.

**Comment by Frederic94500** [comment]
Ah `-addnode=192.168.0.12` it's for fun ^^
Maybe for `-maxconnections`, I try with 50 and for `-timeout`, I try with 7500

**Comment by unsystemizer** [comment]
Just search Google for recommended options for Pi, there are hundreds of examples of working configs. Some can probably be found here in Issues. This isn't a unique situation or setup.
The simplest approach for Pi is to set everything to minimum, rather than decrease the values until the daemon stops crashing.
Five connections work just as fine as 50.

**Comment by Frederic94500** [comment]
Alright! The node is running since 1-2 days ^^
It's just to add some swap space
