### ISSUE TITLE
Can't link correct version of openssl

### ISSUE THREAD

**Issue by jeremyreikes** [bitcoin/bitcoin#9439]
I'm trying to get the following openssl: "OpenSSL 1.0.1f 6 Jan 2014", but I'm getting "OpenSSL 0.9.8zh 14 Jan 2016".  How can I revert to the older version?  I've tried using "brew link openssl --force", but I get the following error: "Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib"

**Comment by jonasschnelli** [comment]
Maybe use `brew switch <name> <version>`?
Hence the fact that OpenSSL is only used for the PRNG and – if you compile the GUI – for the payment server/BIP70 stuff.
