### ISSUE TITLE
Negate the need for blockchain explores and full blockchain syncing for simple queries

### ISSUE THREAD

**Issue by benzmuircroft** [bitcoin/bitcoin#9444]
Rather than download the full blockchain or a pruned version; would it be viable to peer-to-peer ask 'what is this block' or 'what is this tx'?

We download the full blockchain from several peers so why not ask peers for just on piece of info?

**Comment by sipa** [comment]
Because Bitcoin Core is a full node, and for full validation, we need all blocks. Otherwise we would not know whether certain coins aren't already spent by an earlier transaction.

**Comment by rebroad** [comment]
@benzmuircroft Thanks for the suggestion though - bitcoin is a complex thing, so I know from experience, it can be difficult to tell the difference between thinking we've found something missed, vs. not fulling understanding the requirements. Your suggestion is more in-line with what an "SPV" node does, which requires a level of trust with the nodes providing the results of the queries you mention. #9076 may be a step in the direction of what you are proposing.
