### ISSUE TITLE
Curl issue when downloading dependancies on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by saower** [bitcoin/bitcoin#9445]
System： Windows subsytem

thanks

More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
make: *** [/root/bitcoin-master/depends/sources/download-stamps/.stamp_fetched-native_ccache-ccache-3.3.1.tar.bz2.hash] Error 60

**Comment by fanquake** [comment]
Curl error 60 seems to be a local issue as far as I can tell, and not related to how we are downloading dependencies. Please re-open with more information if this is still a problem.
