### ISSUE TITLE
trouble with bitcoin core wallet

### ISSUE THREAD

**Issue by fightofthedog** [bitcoin/bitcoin#9449]
i requested money using the receiving address and the money is showing it was received on blockchain but not in the wallet.  this was done on wednesday 12-28.  how long does it take to get money?

This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by MarcoFalke** [comment]
@fightofthedog Are you synced with the network? (See status bar of the Bitcoin Core GUI)

**Comment by fightofthedog** [comment]
says 28 weeks until sync, would that matter?

**Comment by fightofthedog** [comment]
I have the app open for two days trying to get it in sync or uploaded the updates

**Comment by sipa** [comment]
Synchronization time will depend on your hardware and configuration (in particular, the database cache setting - if you have a few GB extra it will sync much faster). You will not see any transactions show up until you've synchronized past the point where they were confirmed by the network.

**Comment by fightofthedog** [comment]
okay thank you sipa and marco

**Comment by fightofthedog** [comment]
okay so my surface pro doesn't have enough space for the mega file of 7 year of syncing bitcoin core.  now i am downloading it on my desktop.  But since there is no sign in you can't use the same codes on two different computers, how can i switch it?  Or do i have to cancel all funding and if that doesn't work do i lose the current money in  the surface pro account.

**Comment by MarcoFalke** [comment]
@fightofthedog You do not need to store all the old blocks. To delete blocks once they are verified, you need to modify the config file:

* Stop the Bitcoin Core GUI
* Open the bitcoin data directory. (c.f. https://en.bitcoin.it/wiki/Data_directory#Windows)
* Create or open the file `bitcoin.conf`
* Add a line with `prune=550` to the conf file

**Comment by fightofthedog** [comment]
I must have erased the wrong thing.  sorry i am not computer techi that much.  so now it is back to 5 year and 26 weeks.  i just wish i understood this to get it to work.  i knew i should have not used this and not it will be forever to get my money back since i don't under coding and the reset,

**Comment by MarcoFalke** [comment]
@fightofthedog No need to delete anything. Also, be careful and keep your `wallet.dat` safe. Better make a backup right now (you can find it in the data dir).

**Comment by fightofthedog** [comment]
I can't figure out how to create the file you are talking about and as these updates keep coming and taking all my memory, this is ridiculously not a simple as it was sounding.

**Comment by fightofthedog** [comment]
i had to wait all weekend again for it to reload all the stuff, why is this app so difficult and time consuming.  not to mention the files are too large.

**Comment by MarcoFalke** [comment]
@fightofthedog I think there is an easier solution:

* Try to create a link to the bitcoin-qt.exe
* Edit this link and add `    -prune=550` within the double quotes (see screenshot)
* Always start Bitcoin Core through this link.

![ktswf2p](https://cloud.githubusercontent.com/assets/6399679/21612411/5580bb6a-d1d1-11e6-9422-4a567b1c9ce1.png)

**Comment by fightofthedog** [comment]
so i clicked on the properties on the app and this is what i got now.  Is this what you are talking about???  THen why does the do not work sign come up

<img width="685" alt="untitled picture" src="https://cloud.githubusercontent.com/assets/24845016/21618975/a63410d6-d1bb-11e6-95a6-fc1230de27a1.png">

**Comment by fightofthedog** [comment]
then it will not let me do anything until i take that out or cancel

**Comment by MarcoFalke** [comment]
@fightofthedog Sorry, my bad (I am not a windows user). The option goes *after* the double quotes.

**Comment by fightofthedog** [comment]
i get the same message so it doesn't work.

**Comment by sipa** [comment]
Please move this discussion to http://bitcoin.stackexchange.com/

This site is for reporting software issues, not support.

**Comment by fightofthedog** [comment]
thats fine but somehow i better get my money that was sent.  because these system uploads and sync is not working so it is support or software.  just make it happen

**Comment by sipa** [comment]
@fightofthedog I understand you're frustrated, and people are willing to help you. But not here.
