### ISSUE TITLE
Cannot broadcast multisig redeem tx

### ISSUE THREAD

**Issue by Jpja** [bitcoin/bitcoin#9455]
Error `Error 16: mandatory-script-verify-flag-failed (Non-canonical DER signature)`

when broadcasting although transaction verifies ok.

More details : https://counterpartytalk.org/t/redeem-multisig-dust-cannot-broadcast-mandatory-script-verify-flag-failed/2568

**Comment by jonasschnelli** [comment]
How do you sign the failing transactions? Openssl?

Did you make sure you confirming to BIP62: https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki (strict DER encoding)?

**Comment by dexX7** [comment]
Based on the other thread @Jpja used https://coinb.in to sign the transaction.

My guess is their service still produces high-S values.

Can you try to sign the transaction via CounterWallet or Bitcoin Core, as described [here](https://bitcointalk.org/index.php?topic=573342.msg6336408#msg6336408)?

**Comment by unsystemizer** [comment]
@dexX7 I ran a sample address through your site and tried to sign the unsigned transaction with Bitcoin Core 0.12.1 and get this:
 `"error": "Public key is neither compressed or uncompressed"` 
Maybe it's something about how the raw transaction is composed.

**Comment by dexX7** [comment]
@unsystemizer: some Counterparty outputs are unfortunally non-redeemdable due to https://github.com/bitcoin/bitcoin/issues/5939#issuecomment-91820234.

**Comment by Jpja** [comment]
#5939 is from early 2015.
Someone did manage to redeem Counterparty multisig outputs in December 2015.
https://www.blocktrail.com/BTC/tx/f4e2d186ed56aad9b965370411cece4e65fb8dba33ba04d03295299c273e527f
Unless something has changed since, it should be possible. (?)

**Comment by sipa** [comment]
The DER signature requirement was added by BIP66, which activated in july
2015.
