### ISSUE TITLE
bitcoinD - sendmany - strange additional transaction

### ISSUE THREAD

**Issue by wojciechmorawski** [bitcoin/bitcoin#9456]
Strange thing - each time, when I use sendmany there is one additional transaction which goes from my wallet to my wallet :) Even when I declare just one pair of address:btcAmt and exec sendfrom method in blockchain I can find another abstract transaction - as always, from my wallet to my wallet.

It is happening on os x 10.11. Is it normal? What should I think about it?

**Comment by MarcoFalke** [comment]
Please include exact steps to reproduce and the version you are using.

**Comment by gmaxwell** [comment]
Are you asking about change?

**Comment by sipa** [comment]
I suspect so.

For more information:
http://bitcoin.stackexchange.com/questions/1629/why-does-bitcoin-send-the-change-to-a-different-address

**Comment by MarcoFalke** [comment]
I think @wojciechmorawski is referring to the GUI transaction tab, which may create a separate row  for change, but I could not reproduce right now. (Though I am sure I saw it once)

**Comment by MarcoFalke** [comment]
@wojciechmorawski Please clarify or provide further information, I guess we can't help here with the current information...
