### ISSUE TITLE
i'm have problem on setting fee transfer BTC PHP JSON-RPC

### ISSUE THREAD

**Issue by drsaluml** [bitcoin/bitcoin#9458]
Hi guys

i'm have problem on setting fee transfer BTC, the code develop in PHP RPC, i've using commands agrument fee "settxfee" amount 0.0002 BTC then use "sendfrom" to transfer 0.00200000 BTC  and then after execute i got fee result as 0.00009273 BTC , it's possible settxfee is not working correctly, please suggest me how to resolve this issue.

**PHP code test**
```
require_once('easybitcoin.php');
$bitcoin = new Bitcoin('bitcoinrpc','xxxxxxxxxxxxxxxxxx','localhost','8332');
$bitcoin->settxfee(0.00020000);
$result[0] = $bitcoin->getinfo();
$result[1] = $bitcoin->sendfrom('kernel','bbbbbbbbbbbbbbbbbbbbbb',0.00200000);
$bitcoin->dump($result);
```

**Bitcoin getinfo**
```
Array
(
    [0] => Array
        (
            [result] => Array
                (
                    [version] => 130100
                    [protocolversion] => 70014
                    [walletversion] => 60000
                    [balance] => 0.00417854
                    [blocks] => 446297
                    [timeoffset] => -6
                    [connections] => 8
                    [proxy] => 
                    [difficulty] => 317688400354.03
                    [testnet] => 
                    [keypoololdest] => 1467389630
                    [keypoolsize] => 101
                    [paytxfee] => 0.0002
                    [relayfee] => 0.0002
                    [errors] => 
                )
            [error] => 
            [id] => 2
            [status] => 200
            [method] => getinfo
        )
)
```

**Transaction** 
[https://blockchain.info/tx/fb89d133495d88592e6c2a34501574f297c4c9ae71f65feb8fda1e92403fdb0d](https://blockchain.info/tx/fb89d133495d88592e6c2a34501574f297c4c9ae71f65feb8fda1e92403fdb0d)

**Comment by MarcoFalke** [comment]
Does the problem exist in Bitcoin Core? (i.e. the GUI debug window or rpc interface)

**Comment by drsaluml** [comment]
Yes problem exist in Bitcoin Core , Bitcoin Core 0.13.1

![01](https://cloud.githubusercontent.com/assets/13068514/21595296/092bad50-d15f-11e6-96bc-c289a9654b64.jpg)

**Comment by sipa** [comment]
You're aware that settxfee sets the fee per kilobyte? The size of a
transaction in bytes isn't know in advance. You can use the raw transaction
API to see constructed transactions before broadcasting them, if you want
more control.

**Comment by drsaluml** [comment]
If I want a fee high priority transaction , I want sample setting

Sorry, my english is not good

**Comment by jonasschnelli** [comment]
Try to use
1. `estimatesmartfee <blocktarget>` (2 if you want fast confirmation)
2. `createrawtransaction [] {'addr':<amount>}`
3. `fundrawtransaction <hex> {'feeRate': <feerate_per_kb_form_step1>}`
4. optionally: check the fee
5. `singrawtransaction <hex>`
6. `sendrawtransaction <hex>`

This is the preferred way that allows one to better control fees, etc.

**Comment by jonasschnelli** [comment]
Closing. This probably belongs to http://bitcoin.stackexchange.com (or similar).

**Comment by MarcoFalke** [comment]
This could also be #9466, as the fee per kb does not match with settxfee.

**Comment by drsaluml** [comment]
Cannot send by account ?

> Try to use
> 
>     estimatesmartfee <blocktarget> (2 if you want fast confirmation)
>     createrawtransaction [] {'addr':<amount>}
>     fundrawtransaction <hex> {'feeRate': <feerate_per_kb_form_step1>}
>     optionally: check the fee
>     singrawtransaction <hex>
>     sendrawtransaction <hex>
> 
> This is the preferred way that allows one to better control fees, etc.
