### ISSUE TITLE
getaddr over RPC

### ISSUE THREAD

**Issue by chris-belcher** [bitcoin/bitcoin#9463]
A proposed new feature / RPC call.

A way to get IP addresses of other bitcoin nodes known to your node via RPC.

This would be useful for bitcoin wallets that unlink the source IP address from a transaction by connecting through tor to any bitcoin node out there for a short time. Examples of projects that might do this are JoinMarket (https://github.com/JoinMarket-Org/joinmarket/pull/662), laanwj's submit-tx tool or anything else built on top of Bitcoin Core such as Armory.

Right now these projects might use the DNS seeds instead, which are much less decentralized and which could be shut down to stop the tor-broadcast feature working.

I think this new call would be exactly the same as the `getaddr` command from the p2p protocol but as an RPC instead.

**Comment by sipa** [comment]
Seems reasonable.

**Comment by gmaxwell** [comment]
Perhaps the RPC could take some filtering arguments, in particular service flags and recentness, maybe flags to use the tried vs not tried results?  Not necessary for a first cut but might make them easier. (and even open up a new way of doing a dnsseed server; just proxy to the getaddr result :))

**Comment by dcousens** [comment]
`getnodeaddr`

**Comment by gmaxwell** [comment]
@dcousens I don't understand what 'rpc' is for in those lines.

**Comment by dcousens** [comment]
@gmaxwell disregard,  I misread the OP.

**Comment by laanwj** [comment]
Agree that this would be useful.

**Comment by kvsari** [comment]
Please check out this [WIP](https://github.com/kvsari/bitcoin/commit/4e2b78a0b3991c68490b1fa240618d291fc74c1c) and let me know if I'm headed in the right direction.

**Comment by sipa** [comment]
@kvsari Looks good codewise, but I think you're solving a different problem. It's already possible to know what IPs you're connected to (use `getpeerinfo`). The request here is to get IPs your node *knows* about. Presumably its implementation would be similar to the handling of GETADDR in net_processing.cpp.
