### ISSUE TITLE
Database error on Virtual Box shared folder

### ISSUE THREAD

**Issue by borneq** [bitcoin/bitcoin#9482]
I have Ubuntu under Virtual Box and I try keep 100 giga block on shared folder to save space.
1. Install Virtual Box on Windows host
2. Install Ubuntu, for example 16.04
3. Let Windows directory G:\vbshare be shared folder
4. In Ubuntu : sudo mount -t vboxsf vbshare ~/host
5. In this dir can be (but not necessary) blocks
6. Install bitcoin-qt
7. Choose /home/andrzej/host/.bitcoin as data dir

### Expected behaviour
Loading blocks

### Actual behaviour
When bitcoin-qt start tell me in Polish: "Błąd otwierania bazy bloków" (error opening blocks database)

#
![zrzut ekranu z 2017-01-06 16-27-40](https://cloud.githubusercontent.com/assets/757493/21722493/2f3d25e8-d42d-11e6-9400-f8c57cd371fc.png)
## Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
0.13.2-xenial1
### Machine specs:
- OS: Ubuntu
- CPU: i3
- RAM:8 GiB
- Disk size: 1TB
- Disk Type (HD/SDD):HD

**Comment by jonasschnelli** [comment]
Sudden shutdowns (happens quickly with virtual machines) can cause a block (database) corruptions.
What you can do in a such case is to delete the `blocks/` and `chainstate/` directory and start Bitcoin-Qt (or bitcoind) again and resync the chain.

Once we have something like this (regular incremental UTXO dumps https://github.com/bitcoin/bitcoin/issues/8037), this is probably the simplest and most effective solution (although it takes again a while to re-sync the chain).

**Comment by achow101** [comment]
There have been issues in the past with using network shares (which is what VBox shared folders are) as the network share does not always do things properly. See #7981

**Comment by unsystemizer** [comment]
I've never seen that network shares are supported for DB storage, but especially in this case (vboxsf).

**Comment by juiceayres** [comment]
I have a rpi node running in pruned mode seating in front of 1TB NAS (only supporting samba). Decided to run a full node using NAS storage for ` /blocks` ; got the same error described in #7981. Apparently the problem is leveldb not properly supporting cifs.

**Comment by unsystemizer** [comment]
Well, there are issues about SMB too, but this is vboxsf as I mentioned above. I haven't looked, maybe it's a modified Samba protocol. In any case neither of the two is supported.

**Comment by laanwj** [comment]
What you could do is moving and symlinking just the `blocks` directory to your external storage, and leaving the rest of on the local filesystem. In my experience this works - the part of bitcoin core that have problems with "weird filesytems" are BerkelyDB for the wallet and LevelDB for the block index / utxo set. The block storage is based on just dumb files.

> Let Windows directory G:\vbshare be shared folder

Just to be clear as you mention "shared": no part of the state should be shared between multiple running instances of Bitcoin Core at any time. This will cause awful corruptions.

**Comment by juiceayres** [comment]
Could we have natively support for a different `blocks` path in future? For example `-blocksdir` in config to move the block data elsewhere.

**Comment by borneq** [comment]
Is -datadir; rest data apart from blocks like wallet are small

**Comment by MarcoFalke** [comment]
> For example -blocksdir in config to move the block data elsewhere.

Yes, this is now available.
