### ISSUE TITLE
Final Alert for 0.14

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#9501]
Just a gentle reminder (since feature freeze is coming soon) that 0.14 is supposed to include the final alert that will officially end the alert system. It is supposed to be hard coded tand broadcast continuously so that everyone receives it.

@gmaxwell

**Comment by MIGUELWAXX** [comment]
cheers them all

**Comment by laanwj** [comment]
Yes, we shouldn't forget this.

**Comment by MarcoFalke** [comment]
See pull #9594.
