### ISSUE TITLE
Negative mining fee in coinbase tx

### ISSUE THREAD

**Issue by bitkevin** [bitcoin/bitcoin#9523]
this wired coinbase tx is just mined at testnet3.

https://www.blocktrail.com/tBTC/tx/042e9225966258ec7d133d90a978d21ef1d7e4edc4800331a80f73f2d71316d8

* Height : 1,064,329
* Block Reward, inputs: 1.56250000 tBTC (calc by height)
* Total Outputs: 0.15625000 tBTC
* Mining Fee :  0.15625000 - 1.56250000 = `-1.40625000 tBTC`

there is no check on the coinbase transaction outputs amount?

**Comment by achow101** [comment]
This is a display issue with blocktrail, nothing to do with Bitcoin Core.

The outputs of a coinbase transaction can be less than the actual amount that they should be. This has been done before. See https://blockchain.info/block/0000000000004c78956f8643262f3622acf22486b120421f893c0553702ba7b5

**Comment by bitkevin** [comment]
I thought it's a strict rule, bitcoind have to make them equal, but it didn't. All right, let me close this issue.
