### ISSUE TITLE
-blocksonly should disable sharing of mempool with dbcache

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#9526]
Whenever -blocksonly is specified, there is implicitly a zero size mempool. However, there is still a non-zero value for -maxmempool which will be shared with dbcache, leading to 300 MB extra usage. Fix this.

**Comment by dcousens** [comment]
Maybe just make `blocksonly` set `maxmempool` to 0?

**Comment by TheBlueMatt** [comment]
0.14 tag?

**Comment by MarcoFalke** [comment]
Remove the 0.14 milestone for this, because the pull that tries to fix this issue is not tagged for 0.14 and needs some more work.
