### ISSUE TITLE
Bitcoin Core should throw a warning if peerbloomfilters=1

### ISSUE THREAD

**Issue by tulip0** [bitcoin/bitcoin#9540]
In line with conversation about the risks of BIP37 peer bloom filters (#6579, #7708), Bitcoin Core should throw a warning during init if the `peerbloomfilters` boolean is enabled (this is currently set by default). Running `NODE_BLOOM` enabled presents severe risks to node operators (#9238) which they may be unaware of. 

In public knowledge the p2p protocol extension has been used for large scale anti attacks using the `mempool` command to bypass transaction trickling, denial of service due to the enormous CPU load caused by the act of filtering blocks, and potentially other undisclosed issues. This is a stepping stone towards eventually default disabling the feature.

**Comment by jonasschnelli** [comment]
I think this would be wise.
Concept ACK.

**Comment by sipa** [comment]
It seems strange to show a warning for a setting that is default?

**Comment by tulip0** [comment]
It seems strange to have BIP37 enabled by default, but there's no alternatives to it yet.

**Comment by leshacat** [comment]
This "fix" ***may*** be causing issues with NOMP (possibly yiimp too) where p2p is disconnecting...

Can we not find a way to prevent DDoS with ***peerbloomfilters=1*** ???

**Comment by leshacat** [comment]
Nevermind, the restart issue was fixed.

https://github.com/foxer666/node-stratum-pool/issues/31#issuecomment-432073801

**Comment by MarcoFalke** [comment]
Closing for now. Not sure what the goal here is, now that "#16152: Disable bloom filtering by default" has been merged
