### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jeremyreikes** [bitcoin/bitcoin#9541]
When I try to download on OSX, I get the following error after ./configure.
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

How can i get these libdb_cxx headers?

I should also note that it looks like I'm still running the wrong version of openssl, but I don't know if that should cause any issues. Please let me know if OpenSSL 0.9.8zh 14 Jan 2016 is correct.

**Comment by fanquake** [comment]
Have you installed the dependancies as per the [documentation](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md)?
```
brew install berkeley-db4
```

Should install the missing headers.

**Comment by jeremyreikes** [comment]
That worked.  Now this issue has arisen.  

`configure: error: libevent not found.`

What specifically do I need to install now? I am struggling to understand the instructions.

**Comment by jonasschnelli** [comment]
You should probably follow the OSX build doc (https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md):
```
brew install automake berkeley-db4 libtool boost --c++11 miniupnpc openssl pkg-config protobuf --c++11 qt5 libevent
```
