### ISSUE TITLE
dumpwallet behavior

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#9564]
In v0.13: `dumpwallet` "dumps all wallet keys in a human-readable format." (according to console help).

First, it's hard to tell *where* it dumps them.
```
Arguments:
1. "filename"    (string, required) The filename
```
I executed the action and couldn't find the file. Another way to look at this is "I executed the action and nothing happened".
Well, it turns out it did work, but the file ended up in the Bitcoin "root" directory (for me, `c:\Bitcoin`). 
I bet some users would think that the command simply didn't work and you can see where it goes from there.

Second, the action behavior isn't particularly intuitive. 
For example, I'm in `E:\backup` and I run 
`c:\bitcoin\bin\bitcoin-cli.exe dumpwallet wallet.txt`
I think this shouldn't dump the wallet to c:\bitcoin\wallet.txt.

`dumpwallet e:\backup\wallet.txt`works as expected (both from debug console and from the CLI).

This could be classified as a doco bug (e.g. change "The filename" to "The full path and filename"), or it could be improved in the code.

OS: English Windows 10 x64.

**Comment by jonasschnelli** [comment]
More documentation is always good. Hence the fact that the Console/RPC interface if for experience users and (maybe) most of them are aware that a dump-to-filename command better gets supplied with a full absolute path.
Related: https://github.com/bitcoin/bitcoin/pull/9330

**Comment by cdecker** [comment]
It appears that this was addressed in #9740, so this can be closed.

**Comment by unsystemizer** [comment]
@MarcoFalke it seems this should be reopened as doesn't seem fixed (at last not on Linux; originally I reported this with 0.13.2 for Windows).

Current help:

`"1. \"filename\"    (string, required) The filename with path (either absolute or relative to bitcoind)\n"`
https://github.com/bitcoin/bitcoin/blob/v0.15.1/src/wallet/rpcdump.cpp#L600

Below we can see that relative path isn't relative to bitcoind, but to "user's home directory"

```
$ /home/user/Downloads/bitcoin-0.15.1/bin/bitcoin-cli dumpwallet github.txt
{
  "filename": "/home/user/github.txt"
}
```

Trying to use `/tmp/Downloads`:

```
$ cd /tmp
$ /home/user/Downloads/bitcoin-0.15.1/bin/bitcoin-cli dumpwallet Downloads/github.txt
{
  "filename": "/home/user/Downloads/github.txt"
}
```


In my case:

* Bitcoin 0.15.1 (binary from BitcoinCore.org)
* bitcoin.conf: `/home/user/.bitcoin/bitcoin.conf`
* bitcoind location: `/home/user/Downloads/bitcoin-0.15.1/bin/bitcoind`

**Comment by d-rams** [comment]
I'm on OSX and I can't get `dumpwallet` to work in any sense

If I try a home-relative path, an absolute path, just a filename, in quotes, not in quotes etc.  Absolutely nothing results in anything but `Cannot open wallet dump file (code -8)`

**Comment by d-rams** [comment]
The current help on SOX is ```Dumps all wallet keys in a human-readable format.

Arguments:
1. "filename"    (string, required) The filename

Examples:
> bitcoin-cli dumpwallet "test"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "dumpwallet", "params": ["test"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
 (code -1)```

**Comment by d-rams** [comment]
bitcoin-cli doesn't even come with bitcoin-Qt on OSX.

**Comment by jonasschnelli** [comment]
> If I try a home-relative path, an absolute path, just a filename, in quotes, not in quotes etc. Absolutely nothing results in anything but Cannot open wallet dump file (code -8)

Works for me on OSX.
Something like `dumpwalet /Users/myuser/Desktop/wallet.dump`.
Do you have special chars in your absolute path? Maybe a whitespace in your username?

> bitcoin-cli doesn't even come with bitcoin-Qt on OSX.

Bitcoin-cli is not directly necessary when using bitcoin-Qt, because there is the internal QT based console.

**Comment by MarcoFalke** [comment]
@unsystemizer I think you'd have to *start* bitcoind from `/tmp/` to make it the cwd.

In light of this, the path should either be normalized with a base path of the data dir (wallet dir) or the call should just reject all non-absolute paths.

**Comment by d-rams** [comment]
Ok, I got past the error I was getting by running as root.  Not sure why that should be necessary.  But I still get only empty dump files even though I have a valid wallet.dat imported from cold storage.  I'm assuming I don't need to dl the blockchain in order to dump my keys right?

**Comment by MarcoFalke** [comment]
Please just use absolute paths if relatives paths don't work for you. I don't think we can fix relative paths in a way to make everyone happy.
