### ISSUE TITLE
Synchronization problems with wallet.

### ISSUE THREAD

**Issue by morcos** [bitcoin/bitcoin#9584]
Since #7946 we don't hold cs_main while syncing transactions connected in a block with our wallet.  There have been several previously identified open issues such as #9148 and proposed fixes before 0.14.   

There are at least two more potential unsolved problems:
1. There is a race condition where if two blocks are connected in different threads the wallet could receive the transactions in the connected blocks out of order.  In particular if there was a reorg, and a wallet transaction appeared on both chains of the reorg, and the wallet received notification of the transaction in the stale block after receiving notification of the transaction in the current tip block, then this could lead to the wallet believing a confirmed transaction is currently conflicted because it will have the wrong `hashBlock`.  One potential scenario that could cause this race is a miner issuing a preciousblock rpc call (for a block tied with the current tip) simultaneously with receiving a new block building off the current tip.
2. `CreateTransaction` calls take cs_main, which used to mean that the wallet, mempool and chainstate were necessarily synced.  However it is unknown whether problems could be caused by trying to create a new transaction while the mempool and chain state might be ahead of where the wallet is synced.  This is probably not an actual problem, but needs further review.
    - Certainly it is possible that transactions might be created which are no longer valid and won't be accepted to the mempool.
    - Additionally it needs to be carefully thought about whether it is ok for the wallet transaction to be created based on chain state information from the current tip but then possibly updated afterwards with stale information.

**Comment by TheBlueMatt** [comment]
For 2. There dont seem to be too many issues here, however, there is at least one - you could go to select coins, need to use 0-conf change, but such 0-conf change may have been included in a block who's callbacks have not yet been processed - resulting in thinking they are not in mempool and, thus, not selectable.

**Comment by ryanofsky** [comment]
@TheBlueMatt, are all the "unsolved problems" mentioned in your and Alex's comments above fixed by #10286, or will some still remain?

**Comment by TheBlueMatt** [comment]
@ryanofsky they were technically fixed in #9583, but I do not believe #10286 introduces any new (serious) bugs. It is the case that you may not select some coins based on a mistaken belief that they are unconfirmed when they are, but this should still only happen if they confirmed in a block you processed *after* the RPC call was entered (ie after the block-until-caught-up call) but before the actual CreateTransaction call. I do not believe it ever is an issue, but its probably worth re-reading (and re-re-reading) a bunch of wallet logic to make sure the new InMempool()-may-be-out-of-sync-with-GetDepthInMainChain() semantics dont cause issues.

**Comment by jarolrod** [comment]
This appears to have been fixed by #9583 and #10286.

Additionally, there appears to be test coverage for this in [test/functional/wallet_reorgrestore.py](https://github.com/bitcoin/bitcoin/blob/master/test/functional/wallet_reorgsrestore.py)

**Comment by ryanofsky** [comment]
Will close this issue. #18842 is a current example of a wallet state & notification race, but I think we settled into a general approach to dealing with these problems: updating wallet transaction state in anticipation of node notifications where possible, and blocking to wait for notifications where it's not possible. I think there's no need to keep an umbrella issue open, but this can be reopened if there are more problems.
