### ISSUE TITLE
restore cpu GenerateBitcoins - Mars mining 

### ISSUE THREAD

**Issue by isghe** [bitcoin/bitcoin#9611]
Please restore cpu GenerateBitcoins - Mars mining.

I am planning to fly to another planet in a few (years, centuries… who knows); I don't think I'll be able to bring with me a GPU or an ASICS . For sure I'll need a Bitcoin blockchain.
thanks

**Comment by sipa** [comment]
The distance between earth and mars can be up to 401 million kilometers, which takes 45 minutes for roundtrip communication - far more than the Bitcoin block interval, so there is no way that the same chain can maintain consensus across the two systems (unless all miners are on one side).

You'll need different technology, which may mean another blockchain with a larger block interval. In any case, not an issue for Bitcoin itself, and certainly not a current development priority for this codebase. Even if you plan to use CPU mining, I'm sure the Bitcoin Core mining code will be the last one you'd want to use (it was already completely outdated by the time we removed it, by the time you get to fly to Mars it will be horribly so).

**Comment by laanwj** [comment]
You won't be able to take your CPU with you either, sorry.
