### ISSUE TITLE
Error during build 0.12

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9629]
```
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:149:in `build_one_configuration'
        from ./bin/gbuild:285:in `block (2 levels) in <main>'
        from ./bin/gbuild:280:in `each'
        from ./bin/gbuild:280:in `block in <main>'
        from ./bin/gbuild:278:in `each'
        from ./bin/gbuild:278:in `<main>'
```

```
debian@debian:~/gitian-builder$ tail -f var/build.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to samba.org port 80: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [/home/ubuntu/cache/common/download-stamps/.stamp_fetched-native_ccache-ccache-3.2.4.tar.bz2.hash] Error 22
make: Leaving directory `/home/ubuntu/build/bitcoin/depends'

```

**Comment by MarcoFalke** [comment]
ccache might not be the only dependency link which broke. I think qt
moves their releases into an /archives/ subfolder when they are no
longer supported, which breaks links as well.

**Comment by DATSEC** [comment]
:(

**Comment by MarcoFalke** [comment]
It should be easy to fix if you find the right location. Make sure to edit
it here
https://github.com/bitcoin/bitcoin/blob/c1b7421781b7a53485c6db4a6005a80e32267c9f/depends/packages/qt.mk#L3
and submit a patch to our branch.

​Please also note that maintenance end for 0.12 is when 0.14.0 is released
according to https://bitcoincore.org/en/lifecycle/

**Comment by theuni** [comment]
ccache is the first dependency downloaded. I would say it's more likely that @DATSEC is building with LXC and there's no network support in the guest.

@DATSEC Please try again without skipping the optional "make download" step.

**Comment by laanwj** [comment]
> I would say it's more likely that @DATSEC is building with LXC and there's no network support in the guest.

But would it give `404 Not Found` in that case?

**Comment by MarcoFalke** [comment]
Just verified that you need to call `make download` @DATSEC .

Though, I still get the 404 for qt:

```
Fetching qt...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make[1]: *** [/root/bitcoin/depends/sources/download-stamps/.stamp_fetched-qt-qtbase-opensource-src-5.5.0.tar.gz.hash] Error 22
make: *** [download-osx] Error 2
```

**Comment by DATSEC** [comment]
@theuni 
I collected all the versions, starting with version 0.12 and below shows the error

**Comment by MarcoFalke** [comment]
@DATSEC You can try to populate the depends cache manually for gitian as a workaround if you need that: https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#optional-seed-the-gitian-sources-cache-and-offline-git-repositories

**Comment by DATSEC** [comment]
@MarcoFalke Yes, thank you.

**Comment by DATSEC** [comment]
Replace

https://github.com/bitcoin/bitcoin/blob/c1b7421781b7a53485c6db4a6005a80e32267c9f/depends/packages/qt.mk#L3

download.qt.io/**archive**/qt/5.5/$($(package)_version)/submodules

Works without errors if you create a fork without a wizard

**Comment by goldlaser** [comment]
Thank you @DATSEC!

This works.
bitcoin/depends/packages/qt.mk Line 3

Replace "official_releases":
$(package)_download_path=http://download.qt.io/official_releases/qt/5.5/$($(package)_version)/submodules 

with "archive":
$(package)_download_path=http://download.qt.io/archive/qt/5.5/$($(package)_version)/submodules

**Comment by amd5** [comment]
Support  bitcoin
