### ISSUE TITLE
Qt: Incorrect output index reported

### ISSUE THREAD

**Issue by theymos** [bitcoin/bitcoin#9631]
In the transactions list, if you right click a transaction and choose "view transaction details", the "Output index" listed in the resulting window is usually wrong.

With outgoing transactions, if you have a transaction with outputs like:

    vout 0: AddrA
    vout 1: AddrB, which belongs to sender
    vout 2: AddrC
    vout 3: <change>
    vout 4: AddrD

Then the output index as reported by the GUI will be:

    tx to AddrA: 0
    tx to AddrB: <transaction not listed>
    tx to AddrC: 1
    tx to AddrD: 2
    
With received transactions, the output index always seems to be reported as 0 in transactions I've checked.

I'd guess that rather than the actual vout index, some internal wallet index is being reported.

This is 0.13.2. I don't know when the bug was introduced.

**Comment by jonasschnelli** [comment]
Bug confirmed. Should not be over complicated to fix.

<img width="1070" alt="bildschirmfoto 2017-01-26 um 08 51 36" src="https://cloud.githubusercontent.com/assets/178464/22323704/e23d669a-e3a4-11e6-999e-67f83379c931.png">
