### ISSUE TITLE
how can I create altcon from version 0.13?

### ISSUE THREAD

**Issue by Corsairs** [bitcoin/bitcoin#9633]
I can not understand how to start to get the first coin
created the Genesis block and everything else, but the pool was not working
I will be glad if you tell me how you started the first pool

**Comment by Corsairs** [comment]
@sipa I understand you don't even get a hint?

**Comment by MarcoFalke** [comment]
@Corsairs There is a hint about where to find information about "altcons", that you deleted after clicking on "new issue".

**Comment by Corsairs** [comment]
@MarcoFalke Tell me then how you use a pool for bitcoin
I just could not start it from scratch
I understand if the entire network is reset you will not be able to restore it or something?
for example what will you do if you disconnect the Internet?
