### ISSUE TITLE
BitCoin Core Wallet - Uninstall

### ISSUE THREAD

**Issue by pratik91s** [bitcoin/bitcoin#9635]
Hello All,

I have received bitcoin on 2013 in my Bitcoin Core Wallet and in between from 2013 till today I have formatted my system.
I have reinstalled the windows and Bitcoin Core Wallet but I didn't found my bitcoin balance in newly installed Bitcoin Core Wallet (I have synced it till date) but still there is no balance in my Wallet Sad

As per my knowledge, The private key, which is what gives you access to my Bitcoin, is kept in wallet.dat. If the addresses that I have in my new wallet.dat are different then it will not showing my balance.

Is there any way that I can get my Bitcoin to my Bitcoin Core Wallet?

p.s. I don't have old wallet.dat , I have tried some data/file recover software but didn't get success :(

I really appreciate your quick help!

Thanks

**Comment by jonasschnelli** [comment]
> [...] I have formatted my system. [...]
> p.s. I don't have old wallet.dat , I have tried some data/file recover software but didn't get success

If you have lost your old wallet.dat (your private keys), there is nothing you can do to recover your funds.

Try to look for a backup.

Undelete (recover files) will very likely not be capable of restoring your old wallet.dat if you have – either low-level formatted (wrote all with zero bytes) – or written extensively on your disk (reinstalled a OS, wrote a couple of thousands of files, ...).

**Comment by jonasschnelli** [comment]
This probably belongs to http://bitcoin.stackexchange.com. Closing.

**Comment by pratik91s** [comment]
Is there any hope or way?
Or I have to forget about my balance? If so that is not perfect system, i can say.
How one can lost their balance if they lost the wallet.dat

**Comment by laanwj** [comment]
You need to stop using that harddisk immediately to avoid that matters get worse. Turn off the computer and boot from some Live CD, for example. Then try some tools that can scan raw harddisks for private keys, see this topic: https://bitcointalk.org/index.php?topic=25091.0 . This will work if the wallet was not encrypted and it has not been overwritten since.

**Comment by xuzizhenhello** [comment]
> 大家好，
> 
> 我在2013年的比特币核心钱包中收到了比特币，从2013年至今，我格式化了系统。
> 我已经重新安装了Windows和Bitcoin Core Wallet，但是在新安装的Bitcoin Core Wallet中没有找到我的比特币余额（到目前为止，我已经对其进行了同步），但是Wallet Sad中仍然没有余额
> 
> 据我所知，可以让您访问我的比特币的私钥保存在wallet.dat中。如果我在新wallet.dat中拥有的地址不同，则不会显示我的余额。
> 
> 有什么办法可以将我的比特币送到我的比特币核心钱包？
> 
> ps我没有旧的wallet.dat，我尝试了一些数据/文件恢复软件，但是没有成功:(
> 
> 非常感谢您的快速帮助！
> 
> 谢谢



> 大家好，
> 
> 我在2013年的比特币核心钱包中收到了比特币，从2013年至今，我格式化了系统。
> 我已经重新安装了Windows和Bitcoin Core Wallet，但是在新安装的Bitcoin Core Wallet中没有找到我的比特币余额（到目前为止，我已经对其进行了同步），但是Wallet Sad中仍然没有余额
> 
> 据我所知，可以让您访问我的比特币的私钥保存在wallet.dat中。如果我在新wallet.dat中拥有的地址不同，则不会显示我的余额。
> 
> 有什么办法可以将我的比特币送到我的比特币核心钱包？
> 
> ps我没有旧的wallet.dat，我尝试了一些数据/文件恢复软件，但是没有成功:(
> 
> 非常感谢您的快速帮助！
> 
> 谢谢

I can help you,contract me xuzizhen19980531@gmail.com
