### ISSUE TITLE
Linux Cross Compiling Windows Wallet Error: Makefile:5315: the Rule for target „libbitcoin_server_a-httprpc.o“ failed??

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#9648]
Even if i try to Compile Windows Wallets for Bitcoin Core on my Linux Ubuntu 16.04 LTS 64 bit, I got this Error:

// Followed the Guide in docs -> build-windows -> until typing "make"

It fails after ~ 10 seconds with this  Error:

`root@Ubuntu-16:/mnt/bitcoin# make
Making all in src
make[1]: directory „/mnt/bitcoin/src“ will be entered
make[2]: directory „/mnt/bitcoin/src“ will be entered
  CXX      crypto/libbitcoinconsensus_la-aes.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      primitives/libbitcoinconsensus_la-block.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      script/libbitcoinconsensus_la-script_error.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: directory „/mnt/bitcoin/src/secp256k1“ will be entered
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
/usr/bin/x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: directory „/mnt/bitcoin/src/secp256k1“ will be leaved
  CXXLD    libbitcoinconsensus.la
/usr/bin/x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      bitcoind-bitcoind.o
  GEN      bitcoind-res.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
In file included from support/allocators/secure.h:9:0,
                 from key.h:11,
                 from base58.h:18,
                 from httprpc.cpp:7:
./support/lockedpool.h:195:18: error: ‘mutex’ in namespace ‘std’ does not name a type
     mutable std::mutex mutex;
                  ^
./support/lockedpool.h:228:17: error: ‘once_flag’ in namespace ‘std’ does not name a type
     static std::once_flag init_flag;
                 ^
./support/lockedpool.h: In static member function ‘static LockedPoolManager& LockedPoolManager::Instance()’:
./support/lockedpool.h:215:9: error: ‘call_once’ is not a member of ‘std’
         std::call_once(LockedPoolManager::init_flag, LockedPoolManager::CreateInstance);
         ^
./support/lockedpool.h:215:24: error: ‘init_flag’ is not a member of ‘LockedPoolManager’
         std::call_once(LockedPoolManager::init_flag, LockedPoolManager::CreateInstance);
                        ^
Makefile:5315: the Rule for target „libbitcoin_server_a-httprpc.o“ failed
make[2]: *** [libbitcoin_server_a-httprpc.o] Fehler 1
make[2]: directory „/mnt/bitcoin/src“ will be leaved
Makefile:8897: the Rule for target „all-recursive“ failed
make[1]: *** [all-recursive] Fehler 1
make[1]: directory „/mnt/bitcoin/src“ will be leaved
Makefile:685: the Rule for target „all-recursive“ failed
make: *** [all-recursive] Fehler 1
root@Ubuntu-16:/mnt/bitcoin# ^C
root@Ubuntu-16:/mnt/bitcoin# ^C
root@Ubuntu-16:/mnt/bitcoin# ^C
root@Ubuntu-16:/mnt/bitcoin#
`

What am I'm missing?

**Comment by achow101** [comment]
This is a known issue with mingw. See https://github.com/bitcoin/bitcoin/issues/8732

**Comment by globaltoken** [comment]
Ok, where I have to include this?
https://github.com/meganz/mingw-std-threads

**Comment by achow101** [comment]
This issue has not been fixed. There are suggestions, but none that are known to fix all problems or not introduce other problems.

**Comment by globaltoken** [comment]
Okay, thanks for your help. But how can I solve this? Is Debian Working with this? Which System is stable for Compiling? Am I'm missing maybe a Dependency?

Thanks in advance.

**Comment by achow101** [comment]
You have to use Ubuntu 14.04.

**Comment by DATSEC** [comment]
@globaltoken 

1) https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md
2) https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#fetch-and-create-inputs-first-time-or-when-dependency-versions-change

You need to do everything according to instructions, use what I wrote to you

VirtualBox (covered by this guide)

Debian 8.x net installer  http://cdimage.debian.org/mirror/cdimage/archive/8.5.0/amd64/iso-cd/debian-8.5.0-amd64-netinst.iso

**Mini manual**

```
sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

/etc/init.d/ssh restart

apt-get install git ruby sudo apt-cacher-ng qemu-utils debootstrap lxc python-cheetah parted kpartx bridge-utils make ubuntu-archive-keyring curl

adduser debian sudo

echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-start" > /etc/sudoers.d/gitian-lxc
echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-execute" >> /etc/sudoers.d/gitian-lxc

echo '#!/bin/sh -e' > /etc/rc.local
echo 'brctl addbr br0' >> /etc/rc.local
echo 'ifconfig br0 10.0.3.2/24 up' >> /etc/rc.local
echo 'iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE' >> /etc/rc.local
echo 'echo 1 > /proc/sys/net/ipv4/ip_forward' >> /etc/rc.local
echo 'exit 0' >> /etc/rc.local

echo 'export USE_LXC=1' >> /home/debian/.profile
echo 'export GITIAN_HOST_IP=10.0.3.2' >> /home/debian/.profile
echo 'export LXC_GUEST_IP=10.0.3.5' >> /home/debian/.profile
reboot

wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz
echo "76cbf8c52c391160b2641e7120dbade5afded713afaa6032f733a261f13e6a8e  vm-builder_0.12.4+bzr494.orig.tar.gz" | sha256sum -c
# (verification -- must return OK)
tar -zxvf vm-builder_0.12.4+bzr494.orig.tar.gz
cd vm-builder-0.12.4+bzr494
sudo python setup.py install
cd ..

git clone https://github.com/devrandom/gitian-builder.git
git clone https://github.com/bitcoin/bitcoin
git clone https://github.com/bitcoin-core/gitian.sigs.git

cd gitian-builder
bin/make-base-vm --lxc --arch amd64 --suite trusty

pushd ./gitian-builder
mkdir -p inputs
wget -P inputs https://bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch
wget -P inputs http://downloads.sourceforge.net/project/osslsigncode/osslsigncode/osslsigncode-1.7.1.tar.gz
popd

pushd ./gitian-builder
make -C ../bitcoin/depends download SOURCES_PATH=`pwd`/cache/common
popd

./bin/gbuild --memory 3000 --commit bitcoin=v${VERSION} ../bitcoin/contrib/gitian-descriptors/gitian-win.yml
./bin/gsign --signer $SIGNER --release ${VERSION}-win-unsigned --destination ../gitian.sigs/ ../bitcoin/contrib/gitian-descriptors/gitian-win.yml
mv build/out/bitcoin-*-win-unsigned.tar.gz inputs/bitcoin-win-unsigned.tar.gz
mv build/out/bitcoin-*.zip build/out/bitcoin-*.exe ../
```
if you need a key
```

sudo apt-get install rng-tools
sudo rngd -r /dev/urandom

gpg2 --gen-key
```

Maybe there's a simplified version, but I didn't study

**Comment by globaltoken** [comment]
@DATSEC 

Thanks for your help buddy, but I can't use gitian Build because my CPU doesn't Support Software Virtualisation :(

**Comment by DATSEC** [comment]
@globaltoken take advantage of this
https://bitcoin.org/bin/bitcoin-core-0.13.2/

**Comment by globaltoken** [comment]
I will try with 14.04 :)

**Comment by gawaynX** [comment]
@globaltoken  iam new here,  i downloaded my globaltoken wallet from github yesterday and deposited coins. a few hours later the wallet reseted and my coins were away. I need help. 
who can i speak to? thanks

**Comment by globaltoken** [comment]
@gawaynX Post your Wallet .log

**Comment by achow101** [comment]
@globaltoken @gawaynX your discussion is off topic for this github issue and repo. Please take your discussion elsewhere.

**Comment by globaltoken** [comment]
@gawaynX Pls open your Topic here: https://github.com/globaltoken/globaltoken/issues

**Comment by gawaynX** [comment]
I am sorry, iam new, so i send you all data i found with Log :D

i hope you can help me

 

Gesendet: Mittwoch, 21. Juni 2017 um 09:44 Uhr
Von: globaltoken <notifications@github.com>
An: bitcoin/bitcoin <bitcoin@noreply.github.com>
Cc: gawaynX <joschua.schmidtke@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [bitcoin/bitcoin] Linux Cross Compiling Windows Wallet Error: Makefile:5315: the Rule for target „libbitcoin_server_a-httprpc.o“ failed?? (#9648)


@gawaynX Post your Wallet .log

**Comment by gawaynX** [comment]
forgot these....
 

Gesendet: Mittwoch, 21. Juni 2017 um 09:44 Uhr
Von: globaltoken <notifications@github.com>
An: bitcoin/bitcoin <bitcoin@noreply.github.com>
Cc: gawaynX <joschua.schmidtke@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [bitcoin/bitcoin] Linux Cross Compiling Windows Wallet Error: Makefile:5315: the Rule for target „libbitcoin_server_a-httprpc.o“ failed?? (#9648)


@gawaynX Post your Wallet .log

**Comment by beckdaipeng** [comment]
@globaltoken Could you tell us is 14.04 success? I have the same problem

**Comment by globaltoken** [comment]
@beckdaipeng Yap 14.04 worked for me to compile Windows, but OSX failed on 14.04 so I compiled OSX on 16.04

**Comment by wolfoxonly** [comment]
@globaltoken 
It's that the only way?
because ,I'm using win10+bash.

**Comment by globaltoken** [comment]
@wolfoxonly 

Are you able to install all dependencies there?
