### ISSUE TITLE
how to build from this source code??

### ISSUE THREAD

**Issue by jameshentai** [bitcoin/bitcoin#9652]
i want to build from this source code in visual studio or what kind of IDE for it. Not sure this project is c# or c++.

**Comment by jonasschnelli** [comment]
Compiling on windows native can be difficult. Most developers as well as the "official" binaries are using cross compilation (linux).

Have a look here: https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

For an IDE, I can recommend "Qt Creator". It's a decent C++ IDE with all common features like code-completion, class/method index (and jumps), interactive debugger, etc.
Qt Creator will also allow you to debug the Qt objects.
And it's free.

**Comment by jameshentai** [comment]
how to build it in linux???

**Comment by MarcoFalke** [comment]
Have a look at https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#to-build and make sure to install the dependencies first. (Scroll down to "Ubuntu", etc)

**Comment by laanwj** [comment]
Please don't open issues like this. It only shows you're too lazy to look for documentation. We can't hand-hold everyone trying to build the source, certainly not on github which is for reporting code issues not a support forum. There's:

- https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md  for how to build for (and on, if you count the linux subsystem) windows
- https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md for how to build for Linux and general unix
