### ISSUE TITLE
Add editor button bitcoin.conf in wallet bitcoin

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9655]
I noticed that in linux there is no additional menus and windows do not understand where it is located. 
I think it would be not bad to have a button and set the config manually. 
In the future, this button can be used to edit the wallet.

**Comment by jonasschnelli** [comment]
I can't 100% follow the text above. Do you mean a button (like the debug.log button we have) which directly opens the `bitcoin.conf` file in a text-editor?
This would indeed be a neat function.

**Comment by fanquake** [comment]
This this was fixed by #9890.
