### ISSUE TITLE
How to run 4 wallet?

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9664]
You need to run 4 wallet on windows OS?
unless of course it is possible

**Comment by jonasschnelli** [comment]
At the moment, Bitcoin Core does not support multiple wallet during runtime.
What you can do is stop Bitcoin-Core, replace (or move away) the wallet.dat file in your data-dir and restart Bitcoin-Core to "load the new wallet".

**Comment by DATSEC** [comment]
@jonasschnelli Thanks the question can be closed.

**Comment by TheBlueMatt** [comment]
Do be careful that Bitcoin Core has fully and cleanly shut down before
doing that, otherwise the BDB log file may still be present and contain
data which is vital to your wallet.

**Comment by jonasschnelli** [comment]
Seems to be resolved. Closing.

**Comment by luke-jr** [comment]
Actually, even cleanly shutting down may not settle the `wallet.dat`. But better than moving it around, just use the `-wallet=filename` option...

(Note also that Bitcoin Knots supports multiwallet already, if you really want to load multiple at the same time.)

**Comment by DATSEC** [comment]
@luke-jr Yes, I already understood what better not to do so. 
I thought you just implemented a function that you could open multiple window :)
