### ISSUE TITLE
How to get BIP34Hash and nMinimumChainWork?

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9667]
I'm interested in the technical question of how you got BIP34Hash and nMinimumChainWork

I will be glad if someone will tell 

here's the story changes
IBD check https://github.com/bitcoin/bitcoin/commit/ad20cddce2097c6561202777fccd257deb1a9810
BIP34Hash and BIP34Height  https://github.com/bitcoin/bitcoin/commit/33c90cf197223fb95f858db80d090d570d70498a

**Comment by laanwj** [comment]
Please use the Bitcoin Stack exchange for questions: https://bitcoin.stackexchange.com/

This issue tracker is for tracking software issues, nothing more.

**Comment by DATSEC** [comment]
@laanwj Understood, I'll be there to ask questions, thank you

**Comment by DATSEC** [comment]
http://bitcoin.stackexchange.com/questions/51112/how-to-get-bip34hash-and-nminimumchainwork
