### ISSUE TITLE
shutdown delays

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9668]
There are a number of areas where bitcoin{d,-qt} is slow in dealing with shutdown requests.

- getaddrinfo (for the -externalip settings) can take over 25s to return when the DNS entry cannot be found. This causes init.cpp to wait until this has finished, even if shutdown is requested during.
- ActivateBestChain() currently uses ConnectBlock() which can take >30s per block, and does not respond to shutdown requests while looping through the txs in a block.
- LoadBlockIndex() although only run at start-up, there are still cases where we may want to shutdown bitcoin (e.g. power-failure) so again it could be more responsive here.

**Comment by jonasschnelli** [comment]
Yes. We could optimise the shutdown blocking.

**Comment by rebroad** [comment]
4a69ae96139eda1ca321b73a9b935e982655dbba is my attempt to rectify the 2nd example.

**Comment by MarcoFalke** [comment]
Are these still issues on current master?
