### ISSUE TITLE
That hid Satoshi Nakamoto in your code?

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9678]
I tried to find in the code puzzles from Satoshi Nakamoto and I may have found them.
How do you think the meaning of these symbols?

https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L110-L113

https://en.bitcoin.it/wiki/Protocol_documentation

magic values

```
d9b4bef9
f9beb4d9
bed9b4f9
b4d9bef9
d9f9beb4
d9f9b4be
```

Base64 online decoder
http://base64.ru/

/-------------------------------------

罿֞罭罯罯渷枯罭罭罷ָ睷枷֞潭罿ָ罭罷

罀 罷 渀 港 罿֞ 渷 枀 枭 罭 罿ָ 

Jan dead bird net ֞ Seine Seine strike ָ lake bird net ָ net of impact impact Ben harbour bird net bird net ֞ Yansong owl Seine Seine ָ Zhao Jian chain ֞

/-------------------------------------

You can try iterating combinations of those numbers, you get Chinese or Korean letter 
I don't know what these letters mean. But one who knows the Chinese language, can touch the letters and create words

I'd like to read the letter, and I will be glad if someone will try to solve it :)

**Comment by rublev** [comment]
How is this an issue?

**Comment by DATSEC** [comment]
@rublev No I just forgot the question mark removed
question how do you think the meaning of these symbols?

**Comment by sipa** [comment]
Please take this to reddit or something.

**Comment by DATSEC** [comment]
@sipa I don't use reddit.

**Comment by sipa** [comment]
@DATSEC I don't care. This is not the place to discuss conspiracy theories.

**Comment by madovsky** [comment]
@sipa -> @DATSEC  has the right to express himself, and what he found can be a very intersting clue of who is behind bitcoin. So no it's not a conspiracy theory, it's a cnn term like fake news. less tv and more programming is better...
@DATSEC please PM me I can help you to spread the word and find out the mystery

**Comment by sipa** [comment]
From the Bitcoin v0.1.5 source code:

```
// The message start string is designed to be unlikely to occur in normal data.
// The characters are rarely used upper ascii, not valid as UTF-8, and produce
// a large 4-byte int at any alignment.
static const char pchMessageStart[4] = { 0xf9, 0xbe, 0xb4, 0xd9 };
```

I think that is a perfectly reasonable rationale for the character choice. You're free to go look for patterns in that as much as you like, but don't spam the development repository with such theories.

**Comment by DATSEC** [comment]
@sipa I don't understand what you want to say with this review
Why these characters are chosen?
f9 - what do you mean?
be - what do you mean?
b4 - what do you mean?
d9 - what do you mean?

**Comment by sipa** [comment]
@DATSEC None of this is relevant for development. Take this elsewhere.

**Comment by DATSEC** [comment]
This has a direct relationship to the history bitcoin, a message that will affect the plot

**Comment by madovsky** [comment]
@sipa why to be so rude? you are not the owner of bitcoin and his comment has nothing to do with spam. it's directly related to the subject, bitcoin.

**Comment by sipa** [comment]
@DATSEC Take 'the plot' to Stackexchange, or the Bitcoin forums, or reddit. This repository is for development of the Bitcoin Core software.

**Comment by DATSEC** [comment]
@sipa I do not believe that Satoshi Nakamoto did not leave no mystery behind 
I am sure that he left, even if it was a group of people or one person, a mystery should be
Aren't you curious to at least try to find a riddle?

**Comment by sipa** [comment]
> @sipa I do not believe that Satoshi Nakamoto did not leave no mystery behind

You can believe what you want. This place is for development, not religion. I'm locking this thread.
