### ISSUE TITLE
getmempoolinfo returns incorrect data

### ISSUE THREAD

**Issue by vayvanne** [bitcoin/bitcoin#9685]
```
C:\Program Files\bitcoin>0.13.2\bin\bitcoin-cli getmempoolinfo
{
  "size": 0,
  "bytes": 0,
  "usage": -72057594037927840,
  "maxmempool": 256000000,
  "mempoolminfee": 0.08850557
}
```
This is after a few days of running. It was ok after the start for decent period of time. Never seen this on 0.13.0.

**Comment by jnewbery** [comment]
@vayvanne can you provide some more details:

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Thanks!

**Comment by vayvanne** [comment]
Hi,
That was windows 7 x64 laptop with 6 Gb RAM and HDD running bitcoin core v. 0.13.1.
I have upgraded to 0.14.1 already. Now it works all right except I see:
`C:\>"%programfiles%\bitcoin\0.14.1\bin\bitcoin-cli" getmempoolinfo
{
  "size": 164667,
  "bytes": 98544263,
  "usage": 299935536,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00051578
}`
I use default maxmempool which is increased to 450MB in 0.14.1. But I still see 300MB.

**Comment by jnewbery** [comment]
> I use default maxmempool which is increased to 450MB in 0.14.1. But I still see 300MB.

I believe `DEFAULT_MAX_MEMPOOL_SIZE` is still 300 in v0.14.1. What makes you think it's changed to 450?

**Comment by vayvanne** [comment]
https://bitcoin.org/en/release/v0.14.1
> The default -dbcache has also been changed in this release to 450MiB

**Comment by sipa** [comment]
The default dbcache size was increased to 450 MB.
The default mempool size is still at 300 MB.

**Comment by vayvanne** [comment]
O, sorry, my bad... confused with borrowing from mempool for dbcache... Unfortunately can't rollback to 0.13.1 to reproduce initial issue again. Thank you.
