### ISSUE TITLE
getmempoolinfo - How to set mempoolminfee?

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#9688]
Hey guys,

Question is above.

Thank you!

**Comment by TheBlueMatt** [comment]
mempoolminfee is set automatically if mempool grows beyond the
-maxmempool size to kick out anything below that fee until the mempool
is within its size limit.

**Comment by globaltoken** [comment]
Ok, nice and how to set maxmempool?

**Comment by MarcoFalke** [comment]
You are not required to set it, it comes with a sensible default.

If you really want to set it, pass -maxmempool to the binary when starting
or modify the conf file.

**Comment by gmaxwell** [comment]
The rpc output is really confusing. e.g. it shows 0 when really the minfee is the configured one.

**Comment by laanwj** [comment]
Please use the [bitcoin stack exchange](https://bitcoin.stackexchange.com/) for questions. This is a bug tracker, not a q/a forum.
