### ISSUE TITLE
Banning incoming connection from a node connected via Tor does not work as expected

### ISSUE THREAD

**Issue by madmarks** [bitcoin/bitcoin#9689]
Blocking via GUI one connected incoming Tor node with 127.0.0.1:port blocks any other incoming 127.0.0.1 nodes.

![banincommingtornode](https://cloud.githubusercontent.com/assets/10898884/22619364/cd411288-eafb-11e6-858b-bcad1335d7eb.png)

I want to ban incoming connections just from specific Tor node but now it is not possible.

- Version: Bitcoin Core v0.13.2 64-bit
- OS: Windows 7 x64

**Comment by sipa** [comment]
That's not possible as Tor connections' source node is not visible. To your node, they all look like they're coming from 127.0.0.1.

**Comment by madmarks** [comment]
Thanks @sipa. Is there some workaround?

**Comment by gj12** [comment]
Why would you want to block tor nodes? You can block them via IP tables, but you can't get every bridge of the tor network. It's basically useless.

**Comment by madmarks** [comment]
> Why would you want to block tor nodes? 

@gj12, I want to ban nodes running old version. It is easy with regular nodes but not possible for tor nodes.

**Comment by MarcoFalke** [comment]
Closing, because it is not possible
