### ISSUE TITLE
How to use stratum-mining with getwork?

### ISSUE THREAD

**Issue by globaltoken** [bitcoin/bitcoin#9692]
Hey,

Has anyone an Idea how to use stratum-mining with getwork?

https://github.com/Crypto-Expert/stratum-mining/issues/358

Because the Current Version doesn't Support getwork, but stratum-mining requires it.

Thanks.

**Comment by sipa** [comment]
I don't know what stratum-mining is, but if it requires `getwork`, it's horribly outdated, as that RPC call was removed almost 3 years ago.

**Comment by globaltoken** [comment]
stratum-mining is a Mining Protocol to create Stratum Servers (Mining with stratum+tcp://)

**Comment by globaltoken** [comment]
Open #9692.

**Comment by laanwj** [comment]
Use the [bitcoin stack exchange](https://bitcoin.stackexchange.com/) for questions, not the bug tracker.
