### ISSUE TITLE
over-sized blocks are downloaded

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9702]
Given that the size of a message is included in the message header, it is possible to determine that an incoming block is over-sized without downloading it, thereby saving bandwidth by not needing to download it before rejecting it and determining misbehavior.

**Comment by laanwj** [comment]
It's the CPU overhead that counts here, not the bandwidth overhead \*. Does it check the size of the packet before trying to deserialize it?

It doesn't look like it:
https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L2108

\*: this would be a lousy bandwidth DoS protection: It's possible for a peer to flood you with an infinite number of other types of messages (including unknown ones) as well. Protecting against floods would need protection at a higher level, or throttling at the network level.
