### ISSUE TITLE
downloaded blocks are not stored upon shutdown

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9703]
Especially noticeable during initial block download, there can be quite a number of blocks downloaded which do not get processed (i.e. not saved) when shutdown is requested, yet activation of chain (which takes much longer) is permitted to continue.

**Comment by laanwj** [comment]
> yet activation of chain (which takes much longer) is permitted to continue.

That's weird - unless this changed recently, activation of the chain is supposed to run on next start, not continue.

Shutdown is really supposed to break off things as soon as possible. So I'm not sure this should go in.

**Comment by jonasschnelli** [comment]
IMO shutdown means shutdown. We already have issues with delayed shutdowns. In memory data that A) won't lead to corruption when not written down – or B) can be quickly be rebuilt, should be ignored/flushed if a shutdown is requested.

**Comment by paveljanik** [comment]
The same applies when killed. The faster the shutdown, the better. Not a bug.

**Comment by unsystemizer** [comment]
Ironically you recently also opened an issue in the opposite direction, that shutdown is too slow :-) - https://github.com/bitcoin/bitcoin/issues/9668

**Comment by DATSEC** [comment]
You can add a pause button, as do the customers of online MMMO games

**Comment by rebroad** [comment]
@paveljanik I agree, although if it just stores blocks and doesn't try adding them to the chain then the time spent is very minimal - far less time than any of the delays mentioned in #9668
