### ISSUE TITLE
Feature request: getnewaddress 'count'

### ISSUE THREAD

**Issue by laudaa** [bitcoin/bitcoin#9723]
Currently it is only possible to generate 1 address per command:
`getnewaddress 'account'`

I think it would be really useful to add an optional count in the command. Therefore, if someone wanted to generate e.g. 200 addresses, they could simply do so with a single call of this command.

I'm also not sure why it still has 'account' as an argument considering that it's deprecated? 
Bitcoin Core 0.13.2

**Comment by TheBlueMatt** [comment]
You should be able to batch repeated getnewaddress RPC calls, which I cant imagine would be all that much different in performance, though maybe some RPC libraries dont expose that feature?

**Comment by jonasschnelli** [comment]
I think its not worth to add a such feature. Just call getnewaddress in a loop. If performance is that critical, consider adding a patch locally.

> I'm also not sure why it still has 'account' as an argument considering that it's deprecated?
Bitcoin Core 0.13.2

Removing the accounts API is not a simple task. There are still users and organisation depending on the system. I first transition approach is #7729.

**Comment by laudaa** [comment]
I should have probably clarified that I was using the debug console, and not the RPC interface. I think that it would be a neat modification to have. However, if you feel that it's not worth the time then so be it.

> Removing the accounts API is not a simple task. There are still users and organisation depending on the system. I first transition approach is #7729.

Initially 'deprecated' made me believe it was already removed. I've just looked into that, thanks.

**Comment by laudaa** [comment]
Unless someone is interested in doing this, I'll close this in a few days.
