### ISSUE TITLE
I propose to modify the output images bitcoin.png v0.13.2

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9742]
I noticed that in windows, there is a large picture instead of a small 

bitcoin.png size 1024 x 1024 

and this picture is used in the bottom Wndows 10 menu it shrinks and does not look nice 
There is a maximum size should be 32x32, offer to fix 

Also, there is a flaw in ubuntu 14.04, there is the icon merges with the text bitcoin

![](http://i.imgur.com/O86BoLN.jpg)

**Comment by jonasschnelli** [comment]
Thanks for the report: can you post a screenshot?

**Comment by MarcoFalke** [comment]
I remember we use a multi resolution ico for windows, no?

Agree screenshots are helpful to document the issue.

**Comment by jonasschnelli** [comment]
To achieve a flexible icon during runtime (testnet/regtest), we set the Icon during `BitcoinGUI` init. The relevant function is `getTrayAndWindowIcon()` which should return a 256x256 Icon. I expect Qt (or the Os) to downsample is correctly.

**Comment by DATSEC** [comment]
here is an example, as you see bitcoin.png they use everywhere, but its size is too great and in the sources there are many other sizes

http://imgur.com/a/7ppl8

**Comment by jonasschnelli** [comment]
@Datasec: 
Why is the size to big?

It looks good on your screenshot? Doesn't it?
The source should contain a large enough "base" icon for future changes (HiDPI is getting more popular for Linux and Windows as well).

**Comment by DATSEC** [comment]
@jonasschnelli This change is not particularly important, the icons look fine 

But I think it's better to use icons that fit the size :)

**Comment by laanwj** [comment]
Looks good to me, there is no problem here. The base icon is large to allow scaling to different screen resolutions, and smaller icons are used where necessary.
