### ISSUE TITLE
Users might share BDB database/*.log files thinking they are logs and leak private keys.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9769]
After asking someone on IRC for their debug.log file today they pastebinned one of their BDB 'logs'. (In this case it didn't appear to contain any key material, fortunately.)

We should rename these things to make this error less likely in the future, at a minimum putting the environment in a directory named 'walletdatabase' would be a big improvement.

It may have been a factor that their error said something about that BDB file, which further encouraged them to paste it... if so I'm not sure how much we can do there.

**Comment by jnewbery** [comment]
How about a dump_diags() RPC that dumps all non-sensitive data and log files into a tar file? Asking average users to go through the data directory is always going to be risky.

**Comment by laanwj** [comment]
This is certainly an issue, but I'd say that whatever new format that is going to be used for the wallet should fix this in one go. Going through an intermediate phase in renaming files, which may break forward/backward compatibility anyway with the lousy old BDB 4.8 really isn't worth it in my opinion at least.

**Comment by gmaxwell** [comment]
We could make a dummy file in the database directory? "All_files_in_this_directory_could_contain_wallet_secrets.txt"

**Comment by laanwj** [comment]
Yes, that makes sense.

**Comment by JeremyRubin** [comment]
I would make sure to include something on how to back up -- if all files contain secrets do I need back up all the files in that directory? Could see a lot of users being confused by that.

**Comment by laanwj** [comment]
It should be necessary only to backup wallet.dat.

**Comment by MarcoFalke** [comment]
> We should rename these things to make this error less likely in the future, at a minimum putting the environment in a directory named 'walletdatabase' would be a big improvement.

This has been done. I think the issue can be closed.
