### ISSUE TITLE
Initial wallet loading takes locks in wrong order causing POTENTIAL DEADLOCK DETECTED

### ISSUE THREAD

**Issue by morcos** [bitcoin/bitcoin#9772]
In init.cpp we call `InitLoadWallet` which eventually calls `CWalletDB::LoadWallet` which takes `cs_wallet`, in the course of loading the wallet it calls `LoadToWallet` which calls `MarkConflicted` which takes `cs_main`.  This is the opposite order that these locks are taking in countless other places in the code (often in a `LOCK2(cs_main, cs_wallet)`).  I don't think there is a risk of actual deadlock here because `LoadWallet` only gets called from init.cpp before network threads or rpc threads are functional.  However since it causes an assertion failure with -DDEBUG_LOCKORDER it can make it difficult to do other lock order debugging.   

One work around is to just not have any transactions in the wallet which need to be marked conflicted.

It may be the case that the proper lock order is actually wallet and then main, and the right fix is to actually fix all the other locks in the code, so I'm just noting the issue for now.

**Comment by laanwj** [comment]
> It may be the case that the proper lock order is actually wallet and then main, and the right fix is to actually fix all the other locks in the code, so I'm just noting the issue for now.

Not ever holding them at the same time would be the ideal. Not quite a short-term solution to this issue, but it'd be a step in disentangling the wallets dependencies on the core.

**Comment by ryanofsky** [comment]
Can be closed. This was reported separately by luke and fixed in #11126.
