### ISSUE TITLE
Check returned value of fopen()

### ISSUE THREAD

**Issue by viennadd** [bitcoin/bitcoin#9775]
[util.cpp#L216](https://github.com/bitcoin/bitcoin/blob/master/src/util.cpp#L216) 
if `fopen `failed, a null file pointer could be passed to `FileWriteStr(vMsgsBeforeOpenLog->front(), fileout);`

**Comment by kirit93** [comment]
As I've understood the problem, the solution would be simply passing a "NULL" to FileWriteStr as the second argument and an empty string as the first argument. Is that correct or did you have something else in mind?

**Comment by laanwj** [comment]
I'd say the most straightforward and correct solution is to put everything until the `delete vMsgsBeforeOpenLog` under the `if (fileout)` conditional.
