### ISSUE TITLE
what is ide for build, not on terminal?

### ISSUE THREAD

**Issue by jameshentai** [bitcoin/bitcoin#9776]
how to build on ide, what ide, not terminal?

**Comment by NicolasDorier** [comment]
duplicate https://github.com/bitcoin/bitcoin/issues/9652

**Comment by MarcoFalke** [comment]
@jameshentai Such questions are usually already answered on bitcoin stackexchange: See https://bitcoin.stackexchange.com/questions/50046/how-to-open-bitcoin-source-in-ide
