### ISSUE TITLE
better protection needed against compromised authors 

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9781]
https://www.eff.org/deeplinks/2014/04/warrant-canary-faq

I am not aware if any canaries have yet been used by any authors on this project, but given the risk of the project being compromised by backdoors enforced by gag orders, i would suggest that canaries be deployed by all authors working on the project at their earliest convenience.

I can confirm that as of today I have not received any gag orders or similar. <-- simple example

**Comment by dcousens** [comment]
Canaries are not legal in every country.

**Comment by fanquake** [comment]
I don't this this is the right place to discuss this. Maybe the stackexchange would be better? https://bitcoin.stackexchange.com/
