### ISSUE TITLE
Suggestion: Increase MAX_OUTBOUND_CONNECTIONS for initial syncing if node accepts incoming connections.

### ISSUE THREAD

**Issue by i-rme** [bitcoin/bitcoin#9800]
I am setting up a node and I notice that the initial sync is slow and I am not fully using my CPU nor my bandwidth. (CPU load averages in 50% and Bandwidth averages 40Mbps out of 300Mbps available).

I believe that when a node is doing the first blockchain syncing it needs more outbound connections, for example, 16.

To avoid using too many peers and too many resources I propose only increasing  MAX_OUTBOUND_CONNECTIONS to 16 temporarily when the node is doing its initial syncing and only if port 8333 is open and accepting connections (to encourage nodes to be reachable).

This would not harm the network as it would only be during the initial syncing and It would speed up it while encouraging owners to accept incoming connections.

**Comment by TheBlueMatt** [comment]
"I am not fully using my CPU nor my bandwidth" often this is an indication that you're disk is saturated. In cases where people really are on sufficient hardware (which pretty much means high -dbcache and memory usage, not fast disks), we might consider having smarter logic to limit the timeout necessary to kick peers, though probably only during IBD.

**Comment by i-rme** [comment]
@TheBlueMatt thanks for your response.
 Im running it on a desktop pc, the hard drive supports up to 40MB/s (320Mbps) so that is not the issue here.
I want to clarify that I am not complaining about slow IBD, just pointing out that might be some setting that limits my IBD speed. 

The ideal would be that my hardware or my connection bottletrottle the process. That would assure the best speed possible.

**Comment by MarcoFalke** [comment]
@i-rme I assume you are running 0.13.2, in which case you can expect
some speedups by switching to 0.14.0 (planned to be released in about
two weeks).

See #9787 for a summary of the speedups as well as
https://github.com/bitcoin/bitcoin/pull/8610#issuecomment-243143404

**Comment by i-rme** [comment]
@MarcoFalke I am already running 0.14 rc1, and I want to thank all developers for improving Bitcoin Core and in particular by assume-valid block feature.

I believe that the problem is that just 8 peers cant max out my hardware or my bandwidth.

**Comment by gmaxwell** [comment]
Then it should change peers until they can, it does this now, but it's a known area for improvement.  More peers really isn't the solution here. There are many nodes on the network that can serve blocks out faster than any existing hardware can index them. :)

**Comment by TheBlueMatt** [comment]
"Im running it on a desktop pc, the hard drive supports up to 40MB/s (320Mbps) so that is not the issue here" if you're running on a desktop hard drive then that is almost definitely your bottleneck after the first 150-200k blocks. It isn't a question of your drive's sequential throughout (the number you quoted), but a question of seek latency, which is usually rather high.

**Comment by laanwj** [comment]
Closing this, as said: the solution is not to add more outgoing peers but choose better peers.

**Comment by rebroad** [comment]
does #9599 help fix this?
