### ISSUE TITLE
0.14 not loading mempool.dat?

### ISSUE THREAD

**Issue by stefment** [bitcoin/bitcoin#9810]
### Describe the issue

Restarting bitcoin, mempool starts filling from scratch.

#### If so, please list the steps to reproduce below:
1. Wait for mempool to reach for example 3000 transactions
2. Restart bitcoin
3. Watch mempool filling slowly from scratch

### Expected behaviour
Mempool would already contain ~3000 TX on startup

### Actual behaviour
It starts at 0 and fills up slowly with a few per second.

### Screenshots.
http://imgur.com/a/or82d

### What version of bitcoin-core are you using?
Windows x64 0.14rc1 binary from https://bitcoin.org/bin/bitcoin-core-0.14.0/test.rc1/

### Any extra information that might be useful in the debugging process.
I may not be aware of how the mempool.dat thing works and there could just be a misunderstanding.

**Comment by paveljanik** [comment]
How do you "Restart bitcoind"? Is `mempool.dat` saved after stopping bitcoind? Do you have something in the `debug.log`?

**Comment by stefment** [comment]
i found this in the debug.log

2017-02-20 14:52:29 Failed to deserialize mempool data on disk: CAutoFile::read: end of file. Continuing anyway.

the way i close bitcoin is by right clicking on the tray icon and choosing "exit"

**Comment by paveljanik** [comment]
Can you please upload the `mempool.dat` file somewhere? Please think about its contents first (your transactions etc...).

**Comment by stefment** [comment]
im not sure which place people recommed for uploading files but i found the following place from a quick google search. 

[mempool.dat](http://s000.tinyupload.com/index.php?file_id=44177496656390024749)

**Comment by paveljanik** [comment]
I can confirm the files does not load.

Can you please try removing the file and not killing the client from the tray, but correctly via menu?

**Comment by paveljanik** [comment]
Do you have enough disc space? Any antivirus or something like that?

**Comment by stefment** [comment]
thank you for being so swift with the help.

i deleted mempool.dat, closed via menu, and notice it created a new mempool.dat. but on restart i get the same error in debug.log and the mempool is empty and start filling from scratch again.

i only have windows defender activated, no other antivirus etc. i tried doing the same steps above but with windows defender off, but i got the same results.

**Comment by stefment** [comment]
I have to add that i didnt to a "clean" install of 0.14rc1 but merely installed it on top of my 0.13.2 install. Is that a problem?

**Comment by laanwj** [comment]
I'm not 100% sure that 0.14.0 can read 0.13.2's mempool.dat files. 

If that's the case then after starting the mempool from scratch once, it will work from there on.

**Comment by stefment** [comment]
I deleted the mempool.dat before i shut down 0.14rc1 so the mempool.dat should be a 0.14 type. Right? Yet it seems to fail to load when i start up 0.14rc1 again. I wish there was something i can do to help.

**Comment by paveljanik** [comment]
Ok, I have modified `validation.cpp` to contain:
```C++
            fprintf(stderr, "Loading tx %d\n", num);
            file >> tx;
            fprintf(stderr, "tx loaded...\n");
```

and with the supplied file, "tx loaded" is not printed at all.

**Comment by paveljanik** [comment]
Hmm, CRLF could be an issue?

Raw TX by blockr here:
http://btc.blockr.io/api/v1/tx/raw/2713042c4f667e00a70d1d7bc4e4939c294e6272934026ea0bd618ef6e236318 compared with saved `mempool.dat`:

```
01000000024c054f6beb9b7287221b05257dc1927afa13847459aaced17aafc13221a753a5010000006a47304402200f8445501f17ac97c16e7bfd16eb65dd4622c8bc70b3b7618e4a6c8d28a77ac802204865b3f4aa83eedc597773d4c206ccec4d24b353dca2642e156698d12144de04012103ab9330e34b208a76a2472e0dcca391a0626bcfbdccc36c2bc2905a2381417d8cfeffffffa44a01b249e55323d15df1a0ef233a8475bd3e94e69b5c4554e7c39d4bc1e0cc000000006b483045022100c93c1a083d9fea577b43d59f93cf09dceea0dfcadb484c18ef8e3c8e6200464b02202574053ac4485774ccc22a3c9d441375e422e32d0271c8d00ab35e621f3224da012103a8bd590e5ba1e0fb79a39845182a10cce0c289ee38c93c3e3320215e928c2b91feffffff025b110200000000001976a9145ba9f27ea1eeb54d5436d5ed153dda571430243f88ac585f4800000000001976a914e8f5ebe914299f9a7c289b063d2c704f7e5aa40488ac18ed0600
01000000024c054f6beb9b7287221b05257dc1927afa13847459aaced17aafc13221a753a5010000006a47304402200f8445501f17ac97c16e7bfd16eb65dd4622c8bc70b3b7618e4a6c8d28a77ac802204865b3f4aa83eedc597773d4c206ccec4d24b353dca2642e156698d12144de04012103ab9330e34b208a76a2472e0dcca391a0626bcfbdccc36c2bc2905a2381417d8cfeffffffa44a01b249e55323d15df1a0ef233a8475bd3e94e69b5c4554e7c39d4bc1e0cc000000006b483045022100c93c1a083d9fea577b43d59f93cf09dceea0dfcadb484c18ef8e3c8e6200464b02202574053ac4485774ccc22a3c9d441375e422e32d0271c8d00d0ab35e621f3224da012103a8bd590e5ba1e0fb79a39845182a10cce0c289ee38c93c3e3320215e928c2b91feffffff025b110200000000001976a9145ba9f27ea1eeb54d5436d5ed153dda571430243f88ac585f4800000000001976a914e8f5ebe914299f9a7c289b063d2c704f7e5aa40488ac18ed0600
```

**Comment by paveljanik** [comment]
@stefment Thank you for reporting the problem. We have identified your issue and will provide fix for it in the next release candidate. I hope that someone will provide a test build for you so you can verify the build yourself even before the next RC!

**Comment by stefment** [comment]
Wow that was fast. Dont worry about making a test build for me. I will ask a friend of mine to help me build my own binaries. I should be able to figure out which pullrequest has the fix. Thank you for your work!

**Comment by paveljanik** [comment]
@stefment That would be great! We need more Windows testers! The PR #9813 fixes this issue.

**Comment by stefment** [comment]
Seems to be working now. Im using the latest development build which i built myself. No error in debug.log and i see mempool with transactions after a restart now :) Just thought id let you know. Have a nice day.

**Comment by laanwj** [comment]
@stefment Thanks for testing!
