### ISSUE TITLE
Running with --disablewallet gives a segfault

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#9816]
Run `src/qt/bitcoin-qt --disablewallet=1`. 
Quitting after any amount of time will result in `Segmentation fault: 11`

0.14.0 branch at 861cb0c83db0571c2863f6b6276314e115c266ee , osx 10.12.3, Qt5.8

**Comment by paveljanik** [comment]
Confirmed.

**Comment by paveljanik** [comment]
@jonasschnelli Do you have an idea?

**Comment by jonasschnelli** [comment]
I'll take a look at this. Thanks for the report.
