### ISSUE TITLE
Intermittent FAIL: test/test_bitcoin in Travis

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9825]
This seems to happen at least on 0.14:
```
FAIL: test/test_bitcoin
=======================
test_bitcoin: /home/travis/build/bitcoin/bitcoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
Running 228 test cases...
unknown location(0): fatal error: in "rpc_tests/rpc_rawparams": signal: SIGABRT (application abort requested)
test/rpc_tests.cpp(29): last checkpoint
test_bitcoin: key.cpp:300: void ECC_Start(): Assertion `secp256k1_context_sign == __null' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_format_monetary_values": signal: SIGABRT (application abort requested)
...
*** 37 failures are detected in the test module "Bitcoin Test Suite"
test_bitcoin: /home/travis/build/bitcoin/bitcoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/condition_variable_fwd.hpp:102: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
```

Somehow it fails to lock a mutex even before the tests start, and all tests after that fail. I cannot reproduce it locally.

**Comment by laanwj** [comment]
Another one: https://travis-ci.org/bitcoin/bitcoin/jobs/204158785
```
test_bitcoin: tpp.c:62: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= __sched_fifo_min_prio && new_prio <= __sched_fifo_max_prio)' failed.
Running 228 test cases...
unknown location(0): fatal error: in "rpc_tests/rpc_rawparams": signal: SIGABRT (application abort requested)
test/rpc_tests.cpp(29): last checkpoint
...
```

**Comment by laanwj** [comment]
Another one on 0.14: https://travis-ci.org/bitcoin/bitcoin/jobs/204167533
```
FAIL: test/test_bitcoin
=======================
Running 228 test cases...
unknown location(0): fatal error: in "rpc_tests/rpc_rawsign": signal: illegal operand; address of failing instruction: 0x2b73cbf4cf3b
test/rpc_tests.cpp(29): last checkpoint
```

**Comment by laanwj** [comment]
@theuni Do you perhaps have any guess what this could be? 

I think the random errors are pretty scary. I've tried running a few test_bitcoins in parallel on a trusty VM locally but never get this error. It could be that some of their testing machines have broken CPUs but that doesn't explain why it always happens in test_bitcoin and not during the RPC tests or compilation.

**Comment by laanwj** [comment]
Apparantly this was reproduced by someone outside of travis in #9850

**Comment by laanwj** [comment]
There's a new wave of probably related travis failures. Here, Travis will just time out during run of `make check` without any output. Most likely this is `test_bitcoin` hanging at start.

**Comment by ryanofsky** [comment]
I'm not sure I understand how #9875 would fix #9825. Isn't the pthread_mutex_lock/new_prio assertion failing before any test even runs?

I do think it's likely that this bug started with #9773. As I mentioned during the IRC meeting, I was seeing these crashes first over a week ago, and looking back at travis pull request logs (https://travis-ci.org/bitcoin/bitcoin/pull_requests), the first instance of this bug that I could find was https://travis-ci.org/bitcoin/bitcoin/builds/202600549 from #9773.

**Comment by laanwj** [comment]
> I'm not sure I understand how #9875 would fix #9825. Isn't the pthread_mutex_lock/new_prio assertion failing before any test even runs?

I haven't seen the issue since.

Also remember: messages can be out of order if one is written to stdout and the other to stderr. I think that may very well be the case here.

**Comment by MarcoFalke** [comment]
Closing for now, please let me know when the issue appears again.

**Comment by ryanofsky** [comment]
I see, if the messages are out of order that makes perfect sense.
