### ISSUE TITLE
Intermittent failure of `import-rescan.py`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9826]
On master, the `import-rescan.py` test fails intermittently. See for example: https://travis-ci.org/bitcoin/bitcoin/jobs/203878010
```
import-rescan.py:
Initializing test directory /tmp/testzpotg5c7/46
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC successfully started
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC successfully started
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC successfully started
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC successfully started
start_node: bitcoind started, waiting for RPC to come up
start_node: RPC successfully started
Assertion failed: not(False == True)
Stopping nodes
Not cleaning up dir /tmp/testzpotg5c7/46
...
 Shutdown: done
Failed
stderr:
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/test_framework.py", line 145, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/import-rescan.py", line 172, in run_test
    variant.check(variant.sent_txid, variant.sent_amount, 1)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/import-rescan.py", line 87, in check
    assert_equal("involvesWatchonly" not in tx, True)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/util.py", line 529, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
Pass: False, Duration: 9 s
```

**Comment by ryanofsky** [comment]
Was able to reproduce this locally (after ~150 times running in a loop). Will debug.

**Comment by ryanofsky** [comment]
I think I see the cause of the error. "involvesWatchonly" can be true either if source or destination address of the transaction is watch only, but the test doesn't know anything about the source address of the transaction. The test is trying to assert that the destination is not watchonly when money is being sent to an address with an imported private key. But once in a while due to coin selection the source address will be watchonly and cause the check to fail. I can modify the test to only send from non-watchonly sources by adding a new node to the test and sending money from that node. Using sendfrom("") RPC would be another alternative since all the watchonly addresses all have non-empty labels. However the sendfrom RPC is deprecated and also appears to be broken (https://botbot.me/freenode/bitcoin-core-dev/msg/81405475/)

**Comment by laanwj** [comment]
@ryanofsky Thanks for investigating. That makes a lot of sense.

>Using sendfrom("") RPC would be another alternative since all the watchonly addresses all have non-empty labels.

That's a common misunderstanding: sendfrom doesn't, and never had any influence on coin selection. It just changes what internal account the send is charged to.

So yes I guess the solution would be to send from another node. Or change the sequence of the test.

**Comment by ryanofsky** [comment]
Implemented rescan test fix in #9839 and sendfrom help update in 9840.

It does seem like it would be easy to add a feature to sendtoaddress/fundrawtransaction that would allow labels to be used for coin selection. This would have been nice here, and it seems the type of feature that could be touted as an advantage of the label concept over the account concept after #7729, but I don't know if it actually would have practical uses outside of qa testing.

**Comment by laanwj** [comment]
That would be a nice feature to have, I guess, some time after account functionality has been removed and replaced with label API. When it's added with account functionality still in place it's going to magnify confusion even more, as people would assume account balance = amount of coins on labeled UTXOs.

**Comment by sipa** [comment]
I think that multiwallet is a better abstraction for keeping coins separated.

**Comment by laanwj** [comment]
@sipa Agreed on that, multiwallet is a better abstraction for that.

**Comment by ryanofsky** [comment]
Also agree. With multiwallet, this whole test could run one node instead of several.
