### ISSUE TITLE
Design for a bitcoin wallet (white)

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9835]
This is a continuation of design options for the purse
https://github.com/bitcoin/bitcoin/issues/9639

White design and less colors flat buttons without shadows 
Almost 2 color black and white

![](https://i.imgur.com/nqLvGzX.jpg)
![](https://i.imgur.com/eol6BQE.jpg)
![](https://i.imgur.com/iheGpPh.jpg)
![](https://i.imgur.com/VJEpDoP.jpg)

PSD: https://www.dropbox.com/s/p74abfghheci682/bitcoin2.psd?dl=0

**Comment by MarcoFalke** [comment]
Closing as duplicate of #9639
