### ISSUE TITLE
Sync problem crashes Bitcoin: EXCEPTION: St9bad_alloc

### ISSUE THREAD

**Issue by Smiggel** [bitcoin/bitcoin#9857]
I have installed core 0.14.0rc1 after running my node (Raspberry Pi 2) successfully on 0.13.2 for weeks .

After upgrading I am getting errors and having issues keeping the node running. Once in a while core crashes with this error in the terminal:

************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
bitcoin in scheduler       

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

This happens when I use previously downloaded blockchain and also when I start to download the whole blockchain all over again.

My system settings:
Raspberry Pi 2
4GB SD card
NFS share to Synology NAS (blockchain is successfully stored on the nas). Have a backup on an 128GB USB Stick in the pi.

**Comment by laanwj** [comment]
It means your node is out of memory. You need to either add more swap space, and/or reduce the memory requirements of your node by decreasing the `-dbcache` or the mempool size.

**Comment by laanwj** [comment]
Reopening this as it may be an issue with higher memory usage on 0.14

**Comment by Smiggel** [comment]
@laanwj Would like to give it a try with other settings. Perhaps that van help. My Pi has 1GB memory. It doesn't use all of it. About 50% when core is syncing. My swapfile is set to 1024 in /etc/dphys-swapfile and my db cache in bitcoin.conf is set to 64.

**Comment by sipa** [comment]
Can you give your full bitcoin.conf (if any), and an excerpt at the end of debug.log?

**Comment by Smiggel** [comment]
@sipa 
My bitcoin.conf:
`listen=1
bind=0.0.0.0
port=8333
maxconnections=64
upnp=1

dbcache=64
par=2
checkblocks=24
checklevel=0

disablewallet=1

rpcbind=127.0.0.1
rpcport=8332
rpcallowip=127.0.0.1

#maxuploadtarget=144

server=1
testnet=0
`

Debug.log:
http://gofile.me/2I87y/U8JPyyl2L

**Comment by sipa** [comment]
Can you try reducing the maximum mempool as well? (maxmempool=64, for example)

**Comment by Smiggel** [comment]
@sipa Done. I am starting the node again. Going to keep an eye on it.

**Comment by Smiggel** [comment]
@laanwj @sipa It seems the maxmempool limit fixed the issue. Node is still running, where it used to crash already before. Also memory usage is more stable now. 

I'll keep monitoring it closely, but so far it seems fixed.

**Comment by theuni** [comment]
@Smiggel Did it always crash with the same error? Specifically this part:
```
bitcoin in scheduler
```
That's interesting because we're dumping the addrdb/bandb to disk. I wouldn't be surprised if we make a few copies of them in the process.

**Comment by Smiggel** [comment]
@theuni The other error I had before was 

> ************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
bitcoin in ProcessMessages()

**Comment by Smiggel** [comment]
@GameKyuubi Does it run stable when you set the maxmempool limit? Ever since I set it to 64 my node runs stable. All crashes are gone.

**Comment by GameKyuubi** [comment]
Whoops, syntax error in my conf

**Comment by jnewbery** [comment]
Out of interest, what was the syntax error in your conf?

**Comment by sipa** [comment]
mempool instead of maxmempool

**Comment by GameKyuubi** [comment]
Alright, so bitocoind is still getting killed even with my change to the config.

```
/var/log/syslog.1:Mar  4 16:14:49 ip-172-31-34-248 kernel: [126646.452271] Out of memory: Kill process 6336 (bitcoind) score 779 or sacrifice child
/var/log/syslog.1:Mar  4 16:14:49 ip-172-31-34-248 kernel: [126646.458536] Killed process 6336 (bitcoind) total-vm:1270232kB, anon-rss:387052kB, file-rss:0kB
```

**Comment by GameKyuubi** [comment]
Any suggestions for a fix or acknowledgement that this is a real issue yet?

**Comment by sipa** [comment]
@GameKyuubi It looks like bitcoind was only using 387  MB of memory. That is totally expected. If that's enough to get it killed on your system, you must be using too much memory for other things.

**Comment by GameKyuubi** [comment]
@sipa is there a clear description of how much memory bitcoind is supposed to use with `maxmempool=64` and `dbcache=64`?  This was on a 512mb VPS with nothing else running except tmux and htop.

**Comment by laanwj** [comment]
512MB is not enough for running bitcoind. 1GB is absolutely the lower bound.

**Comment by GameKyuubi** [comment]
Noted.  Back to 1GB, no problems so far.

**Comment by Smiggel** [comment]
> Noted. Back to 1GB, no problems so far.

Is that on a Raspberry Pi?

**Comment by Leviathn** [comment]
This appears to have resolved -- unless necessary as a warning re - minimum memory usage..

@gamekyuubi I assume things are still going well? Feel free to report if upgrade to .15 went smoothly as well.

**Comment by cevap** [comment]
This error message means that your client is still running. Try switching off/restarting your wallet differently. 

I close it with that. Feel free to open if there is something.

**Comment by rebroad** [comment]
out of interest, have any pulls since this issue addressed this issue to handle running out of memory more elegantly?
