### ISSUE TITLE
GUI: OpenType support missing for script

### ISSUE THREAD

**Issue by keystrike** [bitcoin/bitcoin#9860]
Under 0.14.0rc2 I receive the following errors repeated several times in debug.log when entering Settings->Options under Windows 8.1 and Windows 10.

GUI:   OpenType support missing for script 11
GUI:   OpenType support missing for script 16

**Comment by MarcoFalke** [comment]
What language are you using?

If you compiled yourself, please include the version of qt you are using.

**Comment by keystrike** [comment]
en-US and I have not compiled it myself.

**Comment by laanwj** [comment]
That's certainly an upstream issue, unrelated to any of our code. Google has a few hits on it.

**Comment by MeshCollider** [comment]
This may have been fixed in Qt 5.1.0 https://bugreports.qt.io/browse/QTBUG-30213
