### ISSUE TITLE
FundRawTransaction select inputs which can be rejected by the mempool

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#9874]
Will write tests and fix, just putting as memo.

### Describe the issue

Input selected by FundRawTransaction might be rejected by too-long-mempool-chain when actually broadcasted.

### Expected behaviour
FundRawTransaction should not select input that would not be accepted in the mempool

### Actual behaviour
FundRawTransaction  select inputs that can be rejected by sendrawtransaction.

**Comment by jonasschnelli** [comment]
Can you retest this with https://github.com/bitcoin/bitcoin/pull/9262 on top (if you haven't done this already) and with `-walletrejectlongchains`?
I think this problem is not specific for `fundrawtransaction` (it's the coin selection part).

**Comment by NicolasDorier** [comment]
I am already on top of this PR, I will take a look deeper, as it can come from other PR I am using.

From what I see: coin will too long chain are took as last resort instead of just being ignored. Will make a test.

**Comment by FndNur1Labs** [comment]
still it's not unconfirmed tough and long. have this long problem and bitcoin not back @_@

**Comment by kouloumos** [comment]
As mentioned in https://github.com/bitcoin/bitcoin/pull/10015#issuecomment-288596931 changing default value of `-walletrejectlongchains` to true solves this issue. That PR lacked consensus but https://github.com/bitcoin/bitcoin/pull/24502 was merged thus this should now be solved.
