### ISSUE TITLE
about external variable chainActive

### ISSUE THREAD

**Issue by viennadd** [bitcoin/bitcoin#9877]
our tool reported a NULL pointer dereference, but I don't sure the thing,

I am wondering under what situation that we can assure the `extern CChain chainActive;` in validation.h has more than one element? (doesn't need NULL checking after chainActive.Tip())

one of the reported locations:
[mining.cpp#L504](https://github.com/bitcoin/bitcoin/blob/master/src/rpc/mining.cpp#L504)
 ```c
           while (chainActive.Tip()->GetBlockHash() == hashWatchedChain && IsRPCRunning())
```

**Comment by TheBlueMatt** [comment]
I assume this was being reported to you by some automated tool, which "our tool" was a reference to. Generally chainActive.Tip() is set after initialization has completed (either to a block or the genesis block).

**Comment by laanwj** [comment]
Looks like this question is answered, closing.
