### ISSUE TITLE
negative balance

### ISSUE THREAD

**Issue by btcid** [bitcoin/bitcoin#9887]
#### If so, please list the steps to reproduce below:
`bitcoin-cli getbalance '*' `
and 
`bitcoin-cli listaccounts`

### Expected behaviour
same as **bitcoin-cli getbalance** 
the result is **61.65250439**

### Actual behaviour
```
bitcoin-cli getbalance '*'
-14.03410034
```

```
bitcoin-cli listaccounts
{
  "": -14.03410034
}
```

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
  "version": 130200,
  "protocolversion": 70015,
  "walletversion": 130000,

### Machine specs:
- OS: Ubuntu 16.04
- CPU: 4
- RAM: 8Gb
- Disk size: 200Gb
- Disk Type (HD/SDD): SSD

**Comment by jonasschnelli** [comment]
AFAIK this has to do with the internals of the accounting system.

Related:
https://github.com/bitcoin/bitcoin/issues/3810
https://github.com/bitcoin/bitcoin/issues/3816
https://github.com/bitcoin/bitcoin/issues/2079

**Comment by ryanofsky** [comment]
Also #9614. `bitcoin-cli getbalance` and `bitcoin-cli getbalance *` compute balances differently, and the latter can (temporarily) show low or negative balances if there are multiple unconfirmed transactions that spend the same inputs. From #9614, "The biggest difference is that GetBalance sums up all unspent TxOuts paying to the wallet, while [getbalance *] sums up both spent and unspent TxOuts paying to the wallet, and then subtracts the values of TxIns spending from the wallet."

**Comment by laanwj** [comment]
Yes, this is a known issue, that will go away when the accounting system (which is already deprecated) goes away.
