### ISSUE TITLE
[Minor issue] getmemoryinfo returns 0 memory used

### ISSUE THREAD

**Issue by stefment** [bitcoin/bitcoin#9896]
Hi Bitcoin Core. I was going through the relase notes today to try the various new things. I noticed that getmemoryinfo returns 0 which i thought was suspicious. However everything seems to be working fine and the node runs without issue. However its only online between 10-15hours per day.

### Describe the issue

trying the new getmemoryinfo command, and it returns 0 memory used

### Can you reliably reproduce the issue?
Yes. I tired restarting and the result was the same.

#### If so, please list the steps to reproduce below:
1. Type getmemoryinfo in debug console
2. Read the output :)
3. Profit

### Expected behaviour
I am expecting it to match the memory used according to windows resource manager..

### Actual behaviour
It returns 0

### Screenshots.
![image](https://cloud.githubusercontent.com/assets/8888420/23443529/9e9773d6-fe2f-11e6-8cab-2172c388e4c2.png)

(662.968 Kb allocated)

`

03:31:31
￼
getmemoryinfo

03:31:31
￼
{
  "locked": {
    "used": 0,
    "free": 262144,
    "total": 262144,
    "locked": 0,
    "chunks_used": 0,
    "chunks_free": 1
  }
}
`

### What version of bitcoin-core are you using?
Bitcoin Core 0.14rc2 win64

### Machine specs:
- OS: Windows 10 64bit home

## Additonal info ##

I am running the node with standard settings and no fancy startup arguments etc.

I hope this report can be of some use, if not i apologise. Im still trying to wrap my head around this thing. Have a nice day.

**Comment by benma** [comment]
The docs say:

`Information about locked memory manager`

So this is not about the full memory used by bitcoind, but the locked memory.

I am not quite sure where locked memory is used. After a quick grep session it seems like the wallet and its keys/encryption use that.

Are you using the wallet?

**Comment by laanwj** [comment]
Yes, there is only locked memory information in there at the moment. This is only used by the wallet.

It would be nice to have general dynamic heap information in there but that's not implemented.

**Comment by laanwj** [comment]
PR #10038 adds a mode to get general heap statistics, though I think that method works on Linux only.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
