### ISSUE TITLE
Message when Ctrl+C pressed

### ISSUE THREAD

**Issue by jeffersoncarpenter** [bitcoin/bitcoin#9901]
I just ran bitcoind for the first time, and tried to exit with Ctrl+C.  It appeared to be stuck, so I killed the process.  Before I could start it again I had to delete the lock file.  However, later I found out bitcoind does handle sigint, and exits.

It would be nice if it displaced an "Exiting..." message so that you know it is busy exiting.

**Comment by fanquake** [comment]
What operating system are you using, and which version of Bitcoin-Core?

You should have seen a message similar to this:
![exit](https://cloud.githubusercontent.com/assets/863730/23495688/1ae265ec-ff55-11e6-83e7-032475d5ca36.png)

**Comment by jeffersoncarpenter** [comment]
v0.13.2, and gentoo linux.  There was no such window visible.  I was running bitcoind, not bitcoin-qt.

**Comment by laanwj** [comment]
Agree this would be useful. Due to specifics of UNIX signal handling, this may not be as trivial as it seems to implement. One cannot just LogPrintf from the signal handler. The Qt shutdown detection works by periodically polling a global shutdown flag. I guess this could work similarly.

**Comment by matlongsi** [comment]
Is it easy to replicate the issue? Does it always happen when bitcoind is run for the first time? Is it specific to gentoo linux? I tried replicating the issue a few times on Ubuntu. While the message "Shutdown requested. Exiting." is displayed only when exiting very early in the startup process, "Shutdown: In progress..." was consistently displayed every time.
