### ISSUE TITLE
Usage tutorial

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#9915]
It would be helpful to new users, if there was a tutorial (run at first-start or the Help menu) explaining when and how to use the GUI and backup their wallet.

**Comment by FndNur1Labs** [comment]
that point. nice @luke-jr  but as now you can go to about and there command. people just need look on help. thank for dev i used that command to easy way 👍 
![commandline](https://cloud.githubusercontent.com/assets/11433397/23606867/ef89e89e-02a5-11e7-9a22-086ef97a0541.png)

**Comment by EricPonvelle** [comment]
I'd be interested in writing a guide. Is there anything that absolutely must be included? If not, I'll just cover the GUI and the backup process. I am exclusively a writer, but I can attempt to add a guide to the Help menu if that's desired.

**Comment by fanquake** [comment]
Moved this to the GUI repo: https://github.com/bitcoin-core/gui/issues/529.
