### ISSUE TITLE
Inconsistency with the standard bip-0044 real work bitcoind

### ISSUE THREAD

**Issue by rattrap19** [bitcoin/bitcoin#9917]
1. Software should prevent the creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before).

But I can easily create an account even if the previous account is empty.

2. Address gap limit.

I can also see that the amount has reached the account, in which there are many more consecutive addresses without a transaction history, even if the amount is sent to the address after those addresses without a transaction.

Addresses created by the command: bitcoin-cli getnewaddress <account>

**Comment by laanwj** [comment]
> But I can easily create an account even if the previous account is empty.

The account system in bitcoind is kind of crappy. Do not confuse it with BIP44 accounts, it pre-dates any of that. This is why it is deprecated, and will be removed in the future. See #3816.

I don't understand your address gap comment.

**Comment by sipa** [comment]
Bitcoin Core does not implement BIP44 in any way.

**Comment by rattrap19** [comment]
When will the account feature be removed then?

**Comment by laanwj** [comment]
> When will the account feature be removed then?

First a label API should be introduced to replace it. Hopefully that can be done for 0.15. Then something like: in 0.16 it could be disabled by default (but reenabled with an option) and in 0.17 removed completely. But it's not entirely decided yet. In any case: do not use it, it's broken.

Closing this issue, as indeed BIP44 is not applicable at all here.
