### ISSUE TITLE
EXCEPTION: St9bad_alloc

### ISSUE THREAD

**Issue by Smiggel** [bitcoin/bitcoin#9922]
My node suddenly crashed in the middle of the night, after running stable for many days. I got this error in the terminal:

EXCEPTION: St9bad_alloc       
std::bad_alloc       
bitcoin in ProcessMessages()       

bitcoin-qt: validation.cpp:1751: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, const CChainParams&, bool): Controletest 'hashPrevBlock == view.GetBestBlock()'

### What version of bitcoin-core are you using?
0.14.0RC1

### Machine specs:
- OS: Raspbian
- CPU: ARM
- RAM: 1GB
- Disk size: 500GB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
My bitcoin.conf file contents:
listen=1
bind=0.0.0.0
port=8333
maxconnections=64
upnp=1
maxmempool=64

dbcache=64
par=2
checkblocks=24
checklevel=0

disablewallet=1

rpcbind=127.0.0.1
rpcport=8332
rpcallowip=127.0.0.1

#maxuploadtarget=144

server=1
testnet=0

**Comment by laanwj** [comment]
You had already reported this in #9857.

**Comment by TheBlueMatt** [comment]
I believe the reporter's point is that it still crashes with -maxmempool set (the purported fix for #9857).

**Comment by Smiggel** [comment]
@TheBlueMatt That's correct. The error I get now is also different then the errors I had before. It ran stable for long time using the maxmempool setting. However, not it suddenly stopped.

**Comment by laanwj** [comment]
That's fine, but #9857 is still open, so you should not report a new issue then (or at least close the old one).

**Comment by Smiggel** [comment]
Ok. I'll Remember that.
