### ISSUE TITLE
Unconfirmed Long. is there we can know how much pay to bloc chain. default is 1k sat.

### ISSUE THREAD

**Issue by FndNur1Labs** [bitcoin/bitcoin#9927]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. Unconfirmed Transaction
2.
3.

### Expected behaviour
If can possible we know ho much trigger fees

### Actual behaviour
No confirm. sorry new posted

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
5.6.1

### Machine specs:
- OS: Windows 7
- CPU: I7
- RAM: 32 GB
- Disk size: 4TB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
Nothing
![bitcoin bug](https://cloud.githubusercontent.com/assets/11433397/23606445/1b8d2eee-02a4-11e7-94f1-80ec45350989.png)

don't kill me if that not related. im still wanna know basic and wanna help dev.

**Comment by jonasschnelli** [comment]
It looks like you haven't used a sufficient fees or spent a unconfirmed input. In order to analyse that further one would need to transaction details. But better not here.

This is a user question and should be posted on stack-exchange or a similar portal (https://bitcoin.stackexchange.com/)

Closing.

**Comment by FndNur1Labs** [comment]
ok sir you can close. i post there right?
