### ISSUE TITLE
Uninstaller should have option to remove data (except for wallet)

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#993]
Install and then run Bitcoin-Qt.
Then quit and uninstall.

RESULT: C:\Program Files\Bitcoin\locale folder is left behind.
RESULT: %APPDATA%\Bitcoin\addr.dat, .lock, db.log, debug.log, etc left behind

I'd expect everything except wallet.dat to be removed (and it would be nice if there was an uninstall checkbox, NOT checked by default, to remove the wallet, too).

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
