### ISSUE TITLE
p2pool inside of the wallet

### ISSUE THREAD

**Issue by DATSEC** [bitcoin/bitcoin#9931]
I propose to implement p2pool inside of the wallet, what would you can mine in solo.
You can mine bitcoins without a server
I don't know if there was ever realized, but the idea is interesting.

**Comment by laanwj** [comment]
Historically speaking this made a lot of sense. Nowadays relatively speaking so few node owners are mining, though, and miners have such special setups that installing one more program isn't a big deal.

**Comment by jameshilliard** [comment]
You probably don't want to be running a stratum server(which is how miners connect to p2pool) within bitcoin core. P2pool is currently implemented in python using the twisted framework so it would have to be rewritten(which would be a large undertaking).

**Comment by DATSEC** [comment]
I read your comments and realized that you did not quite understand me 
I propose to do is not a simple pool and p2pool which should work without a server. 
How it should work. 
1) User comes into the wallet and connect to your wallet 
2) If the user has a white ip address, any other user on the Internet can connect to it putting inside a purse (p2pool) it's ip 
3) once it to connect to this ip, the user downloads all the attached addresses of other users who linked to this ip address
Thus, any user can become the main network for mining, he can mine as one if, and can mine with other users.

**Comment by sipa** [comment]
I have no clue what you're suggesting here.

**Comment by DATSEC** [comment]
@sipa I won't offer ideas, I realized that it's pointless
