### ISSUE TITLE
dumpwallet walletfile overwrite footgun

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9934]
19:02 < $user> gmaxwell: I have the new version. I opened the console. I ran dumpwallet, and it's not giving anything back to me. I passed wallet.dat and /Users/pawn/Library/Application\ Support/Bitcoin/wallet.dat as an argument.

**Comment by laanwj** [comment]
This is one of the reasons I'd be happier if it would streams the data over the socket, so that the client-side can handle it, instead of overwriting an arbitrary server-side file (which shouldn't even work with proper sandboxing).

**Comment by laanwj** [comment]
See #9937.
