### ISSUE TITLE
bitcoin.conf.5 manpage missing

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#9944]
Previous versions bundled a simple manpage for bitcoin.conf, but it seems to have been lost in the migration to properly installed manpages.

**Comment by laanwj** [comment]
I think it was lost on purpose because of the questionable license status of the old manpages.

So will need to write a new one.

To avoid redundancy I guess it could just refer to the options list in `man bitcoind`? There's no need to have the same list in two places.

**Comment by luke-jr** [comment]
Yes, the old one also just deferred to the bitcoind manpage.

```
BITCOIN.CONF(5)                             File Formats Manual                            BITCOIN.CONF(5)

NAME
       bitcoin.conf - bitcoin configuration file

SYNOPSIS
       All command-line options (except for '-conf') may be specified in a configuration file, and all
       configuration file options may also be specified on the command line. Command-line options override
       values set in the configuration file.

       The configuration file is a list of 'setting=value' pairs, one per line, with optional comments
       starting with the '#' character. Please refer to bitcoind(1) for a up to date list of valid
       options.

       The configuration file is not automatically created; you can create it using your favorite plain-
       text editor. By default, bitcoind(1) will look for a file named bitcoin.conf(5) in the bitcoin data
       directory, but both the data directory and the configuration file path may be changed using the
       '-datadir' and '-conf' command-line arguments.

LOCATION
       bitcoin.conf should be located in $HOME/.bitcoin

SEE ALSO
       bitcoind(1)

AUTHOR
       This manual page was written by Micah Anderson <micah@debian.org> for the Debian system (but may be
       used by others). Permission is granted to copy, distribute and/or modify this document under the
       terms of the GNU General Public License, Version 3 or any later version published by the Free Soft‐
       ware Foundation.

       On Debian systems, the complete text of the GNU General Public License can be found in
       /usr/share/common-licenses/GPL.

bitcoin.conf 0.12                              February 2016                               BITCOIN.CONF(5)
```

**Comment by DATSEC** [comment]
And you can make a button in the wallet, which you push and it shows everyone what is written in bitcoin.conf 
If bitcoin.conf was not created, the button will show what the configuration was set.

**Comment by laanwj** [comment]
> And you can make a button in the wallet, which you push and it shows everyone what is written in bitcoin.conf

This has nothing to do with this issue at all. See #9890 and  #9655.

**Comment by MarcoFalke** [comment]
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.
