### ISSUE TITLE
Doc: 0.14 release date is TBA on bitcoincore.org

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#9954]
https://bitcoincore.org/en/lifecycle/ still says 0.14 release date is TBA. Not sure where this is stored but someone should change it. (Is there a repo for that web site or something?)

**Comment by laanwj** [comment]
Yes shoud be filed here: https://github.com/bitcoin-core/bitcoincore.org

**Comment by kallewoof** [comment]
Thanks!
