### ISSUE TITLE
Compiling v0.14.0 boostlib = 1.58.0 gcc-5.2.1 wily ubuntu 64 fails libbitcoin_server.a(libbitcoin_server_a-init.o): In function `CleanupBlockRevFiles()':

### ISSUE THREAD

**Issue by mmacedoeu** [bitcoin/bitcoin#9957]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1. Followed https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md instructions
2. make

### Expected behaviour
Compiles

### Actual behaviour
  CXXLD    bitcoind
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `CleanupBlockRevFiles()':
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::program_options::detail::basic_config_file_iterator<char>::getline(std::string&)':
/usr/include/boost/program_options/detail/config_file.hpp:161: undefined reference to `boost::program_options::to_internal(std::string const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::program_options::detail::basic_config_file_iterator<char>::basic_config_file_iterator(std::istream&, std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)':
/usr/include/boost/program_options/detail/config_file.hpp:145: undefined reference to `boost::program_options::detail::common_config_file_iterator::common_config_file_iterator(std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)'
collect2: error: ld returned 1 exit status
Makefile:3546: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
github tag v0.14.0

### Machine specs:
- OS: Wily Ubuntu 64bits
- CPU: model name	: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
- RAM: Mem:      32801660
- Disk size: /dev/sda2       2.0T  987G  850G  54% /
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Package: libboost-all-dev
Versions: 
1.58.0.0ubuntu1 (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_wily_universe_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_wily_universe_binary-amd64_Packages
                  MD5: 53ae85f8e1c5428077dfe573dd683a2c
 Description Language: en
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_wily_universe_i18n_Translation-en
                  MD5: 53ae85f8e1c5428077dfe573dd683a2c

gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010

[config.txt](https://github.com/bitcoin/bitcoin/files/829275/config.txt)

[error.txt](https://github.com/bitcoin/bitcoin/files/829274/error.txt)

**Comment by paveljanik** [comment]
See #6772. Looks like you think you use gcc-5.2.1 but your config.log shows gcc-4.9 is used.

**Comment by laanwj** [comment]
Yes, this is the same ABI conflict as in #6772. Having both gcc 4.x and 5.x installed, or gcc 5.x with libraries compiled with gcc 4.x, or the other way around, is going to cause pain. Don't mix them.

**Comment by mmacedoeu** [comment]
Confirmed the ABI conflict, using this, https://askubuntu.com/a/26500/663447, technique to pick the right version has passed this phase of compilation:

```
$CC="gcc-5" CXX="g++-5" ./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/"
$CC="gcc-5" CXX="g++-5" make
```
