### ISSUE TITLE
0.14 ignoring dbcache

### ISSUE THREAD

**Issue by mb300sd** [bitcoin/bitcoin#9967]
### Describe the issue

0.14 is ignoring dbcache, cache grows until out of memory

### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1. Do initial sync with bitcoind -dbcache=1000
2. tail -f debug.log during sync

### Expected behaviour
cache size should stop at 1000mb

### Actual behaviour
bitcoind runs out of memory

### Machine specs:
- OS: Debian Stretch
- CPU: N3050
- RAM: 4GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

**Comment by sipa** [comment]
Since 0.14, the dbcache will borrow unused memory space from the mempool, so it can grow to 1.3 GB in your case (assuming you didn't increase the mempool). Also, bitcoind can use a few hundred MB of RAM in addition to the mempool and dbcache.

How do you observe that it grows beyond 1000mb?

**Comment by mb300sd** [comment]
No longer have the debug.log, but I was staring at tail -f and it kept rising above the dbcache setting until it ran out of memory. Lost about 4 hours of syncing.

**Comment by mb300sd** [comment]
I'll see if it goes much above 1300. I kept stopping and restarting it to save progress.

**Comment by mb300sd** [comment]
Never mind, looks like a non issue.
