### ISSUE TITLE
0.14.0 Runtime Error/Out of memory

### ISSUE THREAD

**Issue by hoke81** [bitcoin/bitcoin#9969]
Updated to 0.14 on my netbook, because it was promised to be faster and less resource consuming in some ways. It runs for from 15 minutes only to some hours until a Runtime Error occurs. 
![screenshot 5](https://cloud.githubusercontent.com/assets/26319817/23799041/5e305afe-05a7-11e7-98a6-454ad940fa4b.png)
Last entry in debug.log is "Error: Out of memory. Terminating.", before nothing special. 
I have installed it on an external HD, because no internal one had over 100GB free, 0.13.2 was running fine with that and is again now.

### Machine specs:
- OS: Windows 10 home
- CPU: N570 1,66 GHz
- RAM: 2GB
- Disk size: 149GB
- Disk Type (HD/SDD): USB-HDD

**Comment by alafax** [comment]
I have same issue on 0.14 BTC wallet,Runtime errors during sync.I had to revert on 0.13.2 which works perfectly.


**Machine specs:**

OS - Windows 7 32bit
CPU -  Intel Core Quad Q8200 2.33GHz
RAM - 4GB
Disk size - 640GB HD

**Comment by alafax** [comment]
I think that 0.14 wallet has serious memory leaking problem.

With dbcache set on 300MB on 0.13.2  I had no problems(4GB RAM) - (but setting on 500MB resulted in Out of memory after 12 or more hours of continuos working). 

Users with 2GB RAM should try to set dbcache on 150MB or less.

**Comment by laanwj** [comment]
> I think that 0.14 wallet has serious memory leaking problem.

What makes you suspect the wallet?

**Comment by chandlerchao** [comment]
I don't believe it is the wallet that is causing the memory leak. I compile with the wallet disabled. At this point 13.2 is running without the memory issue with all default settings.

**Comment by sipa** [comment]
@alafax As far as I know, Bitcoin Core has no memory leaks at all (which means it doesn't lose track of allocated memory, making it accumulate over time). However, it's certainly the case that 0.14 has slightly higher default memory usage than 0.13, and during IBD a higher peak memory usage while flushing. We're looking into it, and for now, you can avoid the issue wiht just lower -dbcache and -maxmempool settings.

**Comment by alafax** [comment]
@chandlerchao I agree for 0.13.2. It works OK on default settings (dbcache 300MB).During 24h test it did not crash.
But 0.14 crash every time after 15-25 minutes, with same settings as 0.13.2. I monitored memory usage and did not see that 0.14 has bigger memory peaks than 0.13.2.Though it is definetly memory handling problem and if it is not memory leakage than I suspect IBD pushed weaker machines over their limits.

**Comment by mecampbellsoup** [comment]
Also experienced a crash with the message "Out of memory. Terminating." I took @sipa suggestion and lowered `dbcache` from 5GB to 2GB and `maxmempool` from 300 (the default) to 200; have not experienced another crash since restarting with those changes.

**Comment by coinsmith** [comment]
Bitcoin Core Version 0.14, Bitcoin-qt terminated here too due to 'error, out of memory' in the debug.log. Ubuntu 14.04 - 32 bit, 1g mem + 1 g swap. Never had that with 0.13 or earlier versions.

**Comment by sipa** [comment]
@coinsmith Known issue, please upgrade to 0.14.1.

**Comment by coinsmith** [comment]
Will do.

**Comment by Leviathn** [comment]
This appears closeable.
