### ISSUE TITLE
listunspent's new include_unsafe parameter doesn't work

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#9982]
$ ./bitcoin-cli listunspent 0 9999999 '[]' true
    error code: -3
    error message:
    Expected type bool, got string

`rpc/client.cpp` probably needs to list the parameter along with the other 3:

        { "listunspent", 0, "minconf" },
        { "listunspent", 1, "maxconf" },
        { "listunspent", 2, "addresses" },

Add this?

        { "listunspent", 3, "include_unsafe" },

**Comment by NicolasDorier** [comment]
I confirm. This is strange I would have swear I already used it successfully.
I do not see what is wrong with the code either...

**Comment by dooglus** [comment]
rpc/client.cpp needs to list the parameter as needing interpretation for any non-string parameter.

Can confirm that this change fixes the problem:

    diff --git a/src/rpc/client.cpp b/src/rpc/client.cpp
    index 5bdd84e..16eb723 100644
    --- a/src/rpc/client.cpp
    +++ b/src/rpc/client.cpp
    @@ -79,6 +79,7 @@ static const CRPCConvertParam vRPCConvertParams[] =
         { "listunspent", 0, "minconf" },
         { "listunspent", 1, "maxconf" },
         { "listunspent", 2, "addresses" },
    +    { "listunspent", 3, "include_unsafe" },
         { "getblock", 1, "verbose" },
         { "getblockheader", 1, "verbose" },
         { "gettransaction", 1, "include_watchonly" },

**Comment by jonasschnelli** [comment]
Good catch. Thanks @dooglus

**Comment by dooglus** [comment]
Do I need to make a pull request for this? It seems to have been missed in 0.14.1 rc1.
