### ISSUE TITLE
RPC tests with --tracerpc flag does not increase logging output to stdout (on OSX?)

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#9986]
I can't figure out why, but on OSX 10.10.5 with python3 version 3.6.0 adding the flag `--tracerpc` does not increase the log level to `stdout` (which, am I mistaken? should be the active terminal session right in front of me, right?). Actually, shouldn't I expect to see more output (from other log levels) than this even without `--tracerpc`? Or is the extra logging info going somewhere else...?

```
$ qa/pull-tester/rpc-tests.py bumpfee
.................................................................................................................................................................................................................
bumpfee.py:
Pass: True, Duration: 105 s

TEST | PASSED | DURATION

bumpfee.py | True   | 105 s

ALL | True   | 105 s (accumulated)

Runtime: 105 s
$ qa/pull-tester/rpc-tests.py bumpfee --tracerpc
...................................................................................................................................................................................................................................
bumpfee.py:
Pass: True, Duration: 114 s

TEST | PASSED | DURATION

bumpfee.py | True   | 114 s

ALL | True   | 114 s (accumulated)

Runtime: 114 s
```

**Comment by MarcoFalke** [comment]
The rationale was that you only want to debug when the test fails:
fa427cef130583440779bce9eacfda537c2e6d14

Anyway, it seems you are only running a single test, so maybe it is easier
to just call ./qa/rpc-tests/bumpfee.py --tracerpc directly

**Comment by pinheadmz** [comment]
Oh thank you!
